### ISSUE TITLE
extra space below textblock's text with wrapping enabled

### ISSUE THREAD

**Issue by ivanjx** [AvaloniaUI/Avalonia#10000]
**Describe the bug**
i noticed that there is an extra space below the textblock when i have wrapping enabled.

**To Reproduce**

1. add a border with MaxWidth and background color for easier observation.
2. inside the border, add a textblock with text wrapping enabled.
3. add long text.
4. observe the behavior.

**Expected behavior**
no extra space below the textblock.

**Screenshots**
![image](https://user-images.githubusercontent.com/12814796/213076753-8d7941ee-27b6-4fbc-b807-c38475538f06.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.999-cibuild0028625-beta

**Additional context**
[reproduce.zip](https://github.com/AvaloniaUI/Avalonia/files/10441873/AvaloniaApplication.zip)

**Comment by timunie** [comment]
@Gillibald @ivanjx I just cloned the sample and changed the Windows Content a bit: 

```xml
	<StackPanel Margin="10" Spacing="20">
		<Border Background="Pink"
        			HorizontalAlignment="Center"
        			VerticalAlignment="Center"
        			MaxWidth="100">
        		<TextBlock x:Name="tb" TextWrapping="Wrap" Text="{Binding #Input.Text}"></TextBlock>
        	</Border>
		
		<ComboBox SelectedItem="{Binding #tb.TextWrapping}">
			<TextWrapping>Wrap</TextWrapping>
			<TextWrapping>WrapWithOverflow</TextWrapping>
			<TextWrapping>NoWrap</TextWrapping>
		</ComboBox>
		
		<TextBox Text="this is supposed to be a very very very very very long text :)" x:Name="Input"></TextBox>
		
	</StackPanel>
```

I can reproduce what you see. Interestingly, if I remove each white space it looks okay: 

![image](https://user-images.githubusercontent.com/47110241/213130927-e50a60b6-d5b3-4d6d-ae19-3c0ab7ebf8d5.png)

Probably the text measurement is wrong somehow. 

@ivanjx thank you for the sample and also for finding this.

**Comment by ivanjx** [comment]
mind you that it is also showing incorrectly if you set the textblock's text alignment to center
