### ISSUE TITLE
The screen page in the controls catalog samples does not show multiple screens correctly

### ISSUE THREAD

**Issue by mgnslndh** [AvaloniaUI/Avalonia#10017]
I'm using a laptop with an external monitor and when I use the controls catalog sample on Windows and navigate to the page for screens, the screens are not displayed correctly. See screenshot.

**To Reproduce**

1. Run ControlCatalog.Desktop sample (using multiple monitors)
2. Click on 'Screens' navigation button
3. See error

**Expected behavior**
I expect a list or a grid of screens with detailed information.

**Screenshots**

![image](https://user-images.githubusercontent.com/1139118/213414801-4fe065ef-1d4a-48ce-8ee5-c68957a0ca1b.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Build/Version: 19044.2486 / 21H2

**Additional context**

I'm using a Dell S2240T touch screen.

**Comment by robloo** [comment]
This isn't a user-facing part of Avalonia and I don't think it needs to be as polished as Windows. The text arrangement certainly needs to be fixed and it can be better separated by screen. However, detecting monitor positions and showing it in physical orientations is largely out of scope I think.

**Comment by rabbitism** [comment]
I got same issue. I will try to raise PR and fix. 

![image](https://user-images.githubusercontent.com/14807942/213640043-b9140723-8c33-49c6-8223-6caefea4175a.png)
