### ISSUE TITLE
MenuFlyout ItemTemplate not Applied

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#10010]
![immagine](https://user-images.githubusercontent.com/12531229/213249414-714b59a3-8db0-4daf-a7c7-d6a41644da6c.png)

**To Reproduce**

1. Download Attach
2. Extract
3. Open
4. Run
5. Click on DropDownButton
6. You Can se error

**Expected behavior**
ItemTemplate is applied

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version: **11.0.0-preview4**

**Additional context**

[DropDownButton_Issue.zip](https://github.com/AvaloniaUI/Avalonia/files/10448891/DropDownButton_Issue.zip)

**Comment by rabbitism** [comment]
Maybe duplicate with mine https://github.com/AvaloniaUI/Avalonia/issues/9696

**Comment by workgroupengineering** [comment]
Duplicated

**Comment by workgroupengineering** [comment]
After some thorough investigation the problem is similar but not the same.

**Comment by FG-rgb** [comment]
Fix does not work with Avalonia 11.0.0-preview5.
Now it is complete broken and shows no items:
[Binding]Error in binding to 'Avalonia.Controls.MenuFlyout'.'Items': 'Null value in expression '{empty}' at ''.'(MenuFlyout #5560998)

My Window xaml looks like this:
```
<Button Content="Testen">
    <Button.Flyout>
	    <MenuFlyout Placement="Left" Items="{Binding Path=TestItems,Mode=OneWay}">
		    <MenuFlyout.ItemTemplate>
			    <DataTemplate>
				    <TextBlock Text="{Binding Path=Name,Mode=OneWay}" />
			    </DataTemplate>
		    </MenuFlyout.ItemTemplate>
	    </MenuFlyout>
    </Button.Flyout>
</Button>
```

And the ViewModel looks like this:
```
public record class TestItem(string Name, string Info);

public class MainWindowViewModel
{
    public MainWindowViewModel()
    {
        TestItems = new ObservableCollection<TestItem>
        {
            new TestItem("Hallo", "Hallo Welt"),
            new TestItem("Bla", "Hallo Welt"),
            new TestItem("Blubb", "Hallo Welt"),
            new TestItem("Etwas mehr Text", "Hallo Welt"),
            new TestItem("Hallo Ihr da", "Hallo Welt")
        };
    }

    public ObservableCollection<TestItem> TestItems { get; }
```
With Avalonia 0.10.18 the items are plain shown in UI as ToString()

**Comment by timunie** [comment]
@FG-rgb please open this as a new issue. Closed issues will not be followed up. Also your issue seems to be different to the one posted above.

**Comment by FG-rgb** [comment]
Ok @timunie bug created:
https://github.com/AvaloniaUI/Avalonia/issues/10626
