### ISSUE TITLE
Space bar not working in Textbox on linux 

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#10028]
**Describe the bug**
on recent nightly builds the TextBox ignores the space bar on linux i.e. you press space and it does not appear in the textbox.
It works on windows and mac but not on linux x64 or linux arm32.

**To Reproduce**
type a space into any TextBox

**Expected behavior**
A space appears.

**Screenshots**

**Desktop (please complete the following information):**

11.0.999-cibuild0028785-beta

**Additional context**

**Comment by tomenscape** [comment]
Any possible relation to #9623?

**Comment by ahopper** [comment]
the whitespace test here looks a bit suspicious
https://github.com/AvaloniaUI/Avalonia/blob/ac491e798c25426349516fbef3e5a2882e1992d5/src/Avalonia.X11/X11Window.cs#L734
