### ISSUE TITLE
TextBlock inlines

### ISSUE THREAD

**Issue by Sfairait** [AvaloniaUI/Avalonia#10025]
With moving from pure wpf to avalonia i've encountered problems with using TextBlock.Inlines.
I'm using the latest nuget version of avalonia (0.10.18). 
In the documentaion (https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBlock.cs) TextBlock inherits Control and IInlineHost and contains Inlines.
But in TextBlock.cs via sourcelink in my project TextBlock inherits only Control and the  Inlines property is absent.

**Comment by rabbitism** [comment]
TextBlock only support inlines in V11.0 previews. it's not available in 0.10.x

**Comment by Sfairait** [comment]
Thank you for your answer.

**Comment by bairog** [comment]
@rabbitism what is the approximate release plan of V11.0?

**Comment by maxkatz6** [comment]
@Sfairait textblock isn't editable, there can't be a spell check, unless I misunderstood something. 
TextBox with spellcheck isn't planned for 11.0, but maybe for 11.x. It would highly depend on the platform apis, I suppose.

**Comment by Sfairait** [comment]
@maxkatz6 , of course TextBox, i mistyped. Thank you for the answer.
