### ISSUE TITLE
MacOS Korean input is weird

### ISSUE THREAD

**Issue by blluv** [AvaloniaUI/Avalonia#10031]
**Describe the bug**
When typing Korean, the input does not continue.

**To Reproduce**
1. Create TextBox
2. Typing Korean

**Expected behavior**

https://user-images.githubusercontent.com/87003194/213730857-52aef8a2-ed72-48a3-8cec-7e4763963e3a.mp4

**Screenshots**

https://user-images.githubusercontent.com/87003194/213729440-5c694cc9-9071-422d-9b69-86c64c840233.mp4

**Desktop (please complete the following information):**

- OS: MacOS 13.0.1
- Version: 11.0.0-preview4

**Comment by maxkatz6** [comment]
I suppose this PR fixes that https://github.com/AvaloniaUI/Avalonia/pull/9526
