### ISSUE TITLE
`WindowNotificationManager.Show()` throws `NullReferenceException`

### ISSUE THREAD

**Issue by Crauzer** [AvaloniaUI/Avalonia#10030]
**Describe the bug**
Calling `WindowNotificationManager.Show()` in a `ReactiveCommand.ThrownExceptions` observable subscription in a view model's constructor causes a `NullReferenceException` to be thrown

**To Reproduce**
1. Add `public WindowNotificationManager NotificationManager { get; set; }` to a ViewModel
2. Initialize `NotificationManager` in the View like so:
```cs
protected override void OnAttachedToVisualTree(VisualTreeAttachmentEventArgs e)
{
    base.OnAttachedToVisualTree(e);

    this.ViewModel.NotificationManager = new((Window)this.VisualRoot);
}
```
3. Call `Show()` in a `ReactiveCommand.ThrownExceptions` handler like so:
```cs
this.LoadMapGeometryCommand.ThrownExceptions.Subscribe(ex =>
{
    this.NotificationManager?.Show(
        new Notification("Oopsie woopsie fucky wucky!!!", "amogus", type: NotificationType.Error)
    );
    this.Log().Error(ex);
});

```

**Expected behavior**
I expect a notification to be shown in the window

**Screenshots**
![image](https://user-images.githubusercontent.com/18646077/213689143-5f51c593-b5fe-494b-ac41-1fa391020693.png)

**Desktop (please complete the following information):**
- OS: Windows 11 22H2
- Version: 0.10.18

**Additional context**
Since there is absolutely no documentation for how to use the notifications API, I followed the usage at: https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/NotificationsPage.xaml.cs

**Comment by Crauzer** [comment]
I found a solution for how to use the `WindowNotificationManager` properly by replicating the notifications code used in WalletWasabi.

1. Import the `Avalonia.Xaml.Interactivity` nuget package.
2. Create a `DisposingBehavior` class in `Behaviors` folder
```cs
using Avalonia;
using Avalonia.Xaml.Interactivity;
using System.Reactive.Disposables;

namespace lol2gltf.Behaviors
{
    public abstract class DisposingBehavior<T> : Behavior<T> where T : class, IAvaloniaObject
    {
        private CompositeDisposable _disposables;

        protected override void OnAttached()
        {
            base.OnAttached();

            this._disposables?.Dispose();
            this._disposables = new CompositeDisposable();

            OnAttached(this._disposables);
        }

        protected abstract void OnAttached(CompositeDisposable disposables);

        protected override void OnDetaching()
        {
            base.OnDetaching();

            this._disposables?.Dispose();
        }
    }
}
```
3. Create a `NotificationHelper` static class which will store a static instance of the `WindowNotificationManager`
4. Create a `RegisterNotificationHostBehavior`:
```cs
using Avalonia.Controls;
using lol2gltf.Helpers;
using System.Reactive.Disposables;

namespace lol2gltf.Behaviors
{
    public class RegisterNotificationHostBehavior : DisposingBehavior<Window>
    {
        public RegisterNotificationHostBehavior() { }

        protected override void OnAttached(CompositeDisposable disposables)
        {
            if (this.AssociatedObject is null)
                return;

            NotificationHelper.SetNotificationManager(this.AssociatedObject);
        }
    }
}
```
5. Add the following into your `MainWindow.axaml`
```xml
xmlns:i="using:Avalonia.Xaml.Interactivity"
```
```
<i:Interaction.Behaviors>
    <behaviors:RegisterNotificationHostBehavior />
  </i:Interaction.Behaviors>
```
6. You can now use the `NotificationHelper` any where in your code to show notifications

**Comment by Crauzer** [comment]
This should probably be added into the Avalonia documentation. I find it quite shocking that such a useful control/feature is not documented at all.

**Comment by maxkatz6** [comment]
It was expected behavior in 0.10.
But in 11.0 WindowNotificationManager was changed to not require you to wait until window is loaded.
