### ISSUE TITLE
How Can I use it for Mac ?

### ISSUE THREAD

**Issue by EbramSamy** [AvaloniaUI/Avalonia#1003]
I installed the extension for visual studio and created a demo but how can I use it for creating an executable file for Mac ?!

**Comment by kekekeks** [comment]
You need `gtk+3` from `brew` to be installed on your Mac. Native Cocoa-based backend is currently under development and will be available in June.

For running your app you have 2 options:

### Mono
- Use regular Avalonia Application template, compile your app in Visual Studio and grab binaries from bin
- Install Mono on your Mac
- Run `mono YourApp.exe`

### .NET Core
- Use Avalonia Core Application template, copy your *source code* on your Mac machine
- `dotnet restore`, `dotnet run -f netcoreapp1.1`


We currently lack the tooling for creating `.app` bundles, it's [planned](https://github.com/AvaloniaUI/Avalonia/issues/981) for 0.6.

**Comment by sonarworks** [comment]
What are the updates on the Cocoa-based backend? Is there a remote branch with any work that we could check out?

**Comment by kekekeks** [comment]
We need to switch to `netstandard2.0` before merging it to the main branch. 
Other than that it's mostly working and you can grab it from NuGet: https://www.nuget.org/packages/Avalonia.MonoMac/0.0.2-experimental

**Comment by kekekeks** [comment]
MonoMac backend is now merged and available from nightly builds
