### ISSUE TITLE
Further improve new FilePicker API

### ISSUE THREAD

**Issue by 0x90d** [AvaloniaUI/Avalonia#10034]
The new FilePicker API is great but also a bit confusing and annoying. For example:

##### Problem:
`FilePickerOpenOptions` and `FilePickerSaveOptions` both have file type filters. But the naming of the property are different: `FileTypeFilter` vs `FileTypeChoices`.

##### Suggestion:
 I'd suggest that both should have an identical name.

##### Problem:
The next thing is that all pickers only provide fast access to the NAME but not to the path. I don't know the reason for that but at least on Desktop you definitely want the file path. And here it gets annoying as the amount of code you'd have to write including error checks (as almost everything is declared as nullable) seems way too much:

Example of getting the selected folders:
```C#
var paths = await window.StorageProvider.OpenFolderPickerAsync(new FolderPickerOpenOptions() {
					AllowMultiple = true,
					Title = "Select folder"
				});

if (paths?.Count > 0) {

    List<string> results = new();
    foreach (var item in paths) {
        	if (item.TryGetUri(out Uri? uriPath))
        		results.Add(uriPath.LocalPath);
    }
}
```

##### Suggestion:
I'd suggest to provide direct access, for example:

```C#
public interface IStorageItem {

    /// <summary>
    /// Gets the local file path if there is one
    /// </summary>
    string? LocalPath { get; }

}
```

And for pickers where we can have multiple items I'd also suggest providing direct access:

```C#
public interface IStorageItem {

    /// <summary>
    /// Gets the local file paths of all items if there are any
    /// </summary>
    string[]? LocalPaths { get; }

}
```

Then we could reduce the amount of lines developers have to write down to:

```C#
var paths = await window.StorageProvider.OpenFolderPickerAsync(new FolderPickerOpenOptions() {
					AllowMultiple = true,
					Title = "Select folder"
				});

if (paths?.Count > 0) 
    List<string> results = new(paths);

```

**Comment by maxkatz6** [comment]
1. Current naming makes sense, as it's contextual. "Filter" keyword doesn't make sense when you save file. And "choice" doesn't make sense as on most OS you don't have a choice file type choice when you save file. 
2. There is a full path information. Currently it's "bool TryGetUri(out Uri)" but there is opened PR to make it more convenient "Uri Path".

**Comment by maxkatz6** [comment]
See https://github.com/AvaloniaUI/Avalonia/issues/9029

**Comment by 0x90d** [comment]
As for 1. WPF and I'm sure WinUI don't do that. And why doesn't `filter` make sense when you save a file? When its applied the list of files that appear in the save dialog are filtered. And you can choose a file and overwrite it. Makes perfectly sense to me.
