### ISSUE TITLE
Exception thrown when using CommunityToolkit and the cancellation token

### ISSUE THREAD

**Issue by pavlexander** [AvaloniaUI/Avalonia#10048]
**Describe the bug**

I am trying to use the cancellation token as described in documentation here [RelayCommand](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/relaycommand#asynchronous-commands)

```
[RelayCommand]
private async Task GreetUserAsync(CancellationToken token)
{
    try
    {
        User user = await userService.GetCurrentUserAsync(token);

        Console.WriteLine($"Hello {user.Name}!");
    }
    catch (OperationCanceledException)
    {
    }
}
```

However, whenever I add the cancellation token to the method - the program starts throwing the `Object reference not set to an instance of an object` exception when invoking the command.

**To Reproduce**

1. using .Net 6.0 Avalonia MVVM app on Windows 10 x64, `CommunityToolkit.Mvvm v.8.1.0`, rest of the information along with full repro code you will find in a repo https://github.com/pavlexander/avaloniaExceptionTest1

2. Create fresh `Avalogia` app, add the community toolkit `nuget` package
3. Add a new dummy window
4. add 2 buttons to the main widnow. 

```xml
  <StackPanel>
    <Button Command="{Binding OpenNewWindowWithToken}">Open new window (with CancellationToken)</Button>
    <Button Command="{Binding OpenNewWindow}">Open new window</Button>
  </StackPanel>
```

5. create 2 commands in the main view model, one with cancellation token, one without

```cs
    [RelayCommand]
    public async Task OpenNewWindowWithToken(CancellationToken token)
    {
        var newWindow = new Window1();
        newWindow.Show();
    }

    [RelayCommand]
    public async Task OpenNewWindow()
    {
        var newWindow = new Window1();
        newWindow.Show();
    }
```

6. Launch the app. First click on the button that uses command without cancellation token. Works Ok.
7. Now click on the button that has cancellation token as an input parameter. Observe exception.

Stacktrace: 

>    at Avalonia.Controls.Button.OnClick()\r\n   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)\r\n   at System.Reactive.Subjects.Subject`1.OnNext(T value)\r\n   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)\r\n   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)\r\n   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)\r\n   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)\r\n   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)\r\n   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)\r\n   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)\r\n   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)\r\n   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)\r\n   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)\r\n   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)\r\n   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)\r\n   at AvaloniaApplication2.Program.Main(String[] args) in C:\\repos\\avaloniaExceptionTest1\\AvaloniaApplication2\\Program.cs:line 14

**Expected behavior**
I expect the method to work, no exceptions to be thrown, as documented.

**Screenshots**
![image](https://user-images.githubusercontent.com/20644772/213923803-7352be43-5fab-4861-90ef-342e34b9339b.png)

**Desktop (please complete the following information):**

- OS: Windows 10 x64
- Avalonia Version="0.10.18"
- Avalonia.Desktop Version="0.10.18"
- Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.4.3
- CommunityToolkit.Mvvm v.8.1.0

**Additional context**
I have originally reported this bug to CommunityToolkit github page https://github.com/CommunityToolkit/dotnet/issues/579, however, from the response of the toolkit maintainer I understood that the problem is within the Avalonia itself, rather than the toolkit.. Hence this issue is essentialy a duplicate of what I have reported earlier.

The code that reproduces the problem is located in repo https://github.com/pavlexander/avaloniaExceptionTest1

Please let me know if some additional input is needed.

**Comment by Sergio0694** [comment]
Here is a minimal repro, without the MVVM Toolkit at all:

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Input;

namespace AvaloniaApplication2.ViewModels;

public partial class MainWindowViewModel
{
    private ICommand _OpenNewWindowWithTokenCommand;

    public ICommand OpenNewWindowWithTokenCommand => _OpenNewWindowWithTokenCommand ??= new AsyncRelayCommand2(OpenNewWindowWithToken);

    public async Task OpenNewWindowWithToken(CancellationToken token)
    {
    }
}

public sealed class AsyncRelayCommand2 : ICommand
{
    private readonly Func<CancellationToken, Task> cancelableExecute;
    public event EventHandler? CanExecuteChanged;

    public AsyncRelayCommand2(Func<CancellationToken, Task> cancelableExecute)
    {
        this.cancelableExecute = cancelableExecute;
    }

    public Task? ExecutionTask { get; private set; }

    public bool CanExecute(object? parameter)
    {
        return ExecutionTask is not { IsCompleted: false };
    }

    public async void Execute(object? parameter)
    {
        Task executionTask = ExecutionTask = this.cancelableExecute(default);

        CanExecuteChanged?.Invoke(this, EventArgs.Empty);

        await executionTask;
    }
}
```

If you change that `Func<CancellationToken, Task>` to `Func<Task>` and adjust the method signature accordingly, the issue goes away. No idea why that parameter is causing the issue, but hopefully this helps the investigation in Avalonia 🙂

**Comment by rabbitism** [comment]
The usage is weird. I'm checking on my phone, no very clear so might be wrong. 
1. If you want to utilize the command generated by mvvm toolkit, the you should bind to that generated command, but not this method. 
2. If you want to pass a parameter to command, then you  should set CommandParameter.

Reference: https://github.com/AvaloniaUI/Avalonia/pull/8905

**Comment by Sergio0694** [comment]
Oooh I didn't even notice that the binding was incorrectly pointing to the method and not the command 😆
Then yes this is completely unrelated to the command and an exception makes sense. Though probably a NRE is not the best exception to end up with even with an incorrect binding.

**Comment by maxkatz6** [comment]
@Sergio0694 weirdly, your code doesn't have any issue for me. Or maybe it was just fixed already in 11.0.

@pavlexander as mentioned, your code is invalid. But error message should be better.
Avalonia does support binding command to a method, but that method is supposed to have either no parameters or single parameter that accepts CommandParameter. In your case, it's null, so it tries to convert null to CancellationToken. Eventually, it fails in runtime. Decompiled XAML code:
```csharp
	public static void Sandbox:Sandbox.MainWindowViewModel+OpenNewWindowWithToken_1!CommandExecuteTrampoline(object P_0, object P_1)
	{
		MainWindowViewModel obj;
		obj = (MainWindowViewModel)P_0;
		TypeUtilities.TryConvert(typeof(CancellationToken), P_1, CultureInfo.CurrentCulture, out var result);
		obj.OpenNewWindowWithToken((CancellationToken)result);
	}
```

**Comment by maxkatz6** [comment]
If I replace Binding with ReflectionBinding, it works as expected - button is disabled, as method to bind wasn't found. Expected, assuming that ReflectionBinding doesn't know any compile time information and cannot validate anything.

**Comment by maxkatz6** [comment]
I will close this issue, and open another more specific https://github.com/AvaloniaUI/Avalonia/issues/10075
