### ISSUE TITLE
Unable to bind DataGridTextColumn

### ISSUE THREAD

**Issue by KuroiRoy** [AvaloniaUI/Avalonia#10042]
**Describe the bug**
Trying to bind DataGridTextColumn to a property on my class causes the following error:
`Import.axaml(16, 48): [XAMLIL] Unable to resolve property or method of name 'OtherAccountNumber' on type 'FinanceTracker.ViewModels.ImportModel'. Line 16, position 48.`

Doing the same with a textbox inside a DataGridTemplateColumn works without issue.

**To Reproduce**
``` csharp
public class ImportModel {
    public ObservableCollection<TransactionRecord> TransactionRecords { get; }
    
    public ImportModel () {
        TransactionRecords = new ObservableCollection<TransactionRecord> {
            new TransactionRecord() {OtherAccountNumber = "Testnumber"}
        };
    }
}

public class TransactionRecord {
    public string OtherAccountNumber { get; set; }
}
```

``` xaml
<Design.DataContext>
    <viewModels:ImportModel />
</Design.DataContext>
<DataGrid Items="{Binding TransactionRecords}" AutoGenerateColumns="True">
    <DataGrid.Columns>
        <DataGridTextColumn Header="Hello" Binding="{Binding OtherAccountNumber}">
        </DataGridTextColumn>
        <DataGridTemplateColumn Header="Test">
            <DataGridTemplateColumn.CellTemplate>
                <DataTemplate DataType="import:TransactionRecord">
                    <TextBlock Text="{Binding OtherAccountNumber}" />
                </DataTemplate>
            </DataGridTemplateColumn.CellTemplate>
        </DataGridTemplateColumn>
    </DataGrid.Columns>
</DataGrid>
```

- OS: Windows
- Version 11.0.0-preview4

**Comment by maxkatz6** [comment]
Use ReflectionBinding for the DataGrid or disabled compiled bindings. Alternatively, you can set x:DataType on each DataGridTextColumn.

**Comment by maxkatz6** [comment]
But technically XAML compiler could guess the type based on the `DataGrid Items` property, just like it does for `ListBox Items`.

**Comment by KuroiRoy** [comment]
Ah I didn't get that DataGridTextColumn needs `x:DataType` where DataTemplate has a `DataType` property. I'm using the Rider plugin and, using ReflectionBinding, it isn't able to resolve the binding so using CompiledBinding makes debugging a lot easier.
``` xaml
<DataGridTextColumn Header="Hello" Binding="{Binding OtherAccountNumber}" x:DataType="import:TransactionRecord">
```
That works. Thank you!
