### ISSUE TITLE
Exception is thrown when working with the dev tools

### ISSUE THREAD

**Issue by pavlexander** [AvaloniaUI/Avalonia#10049]
**Describe the bug**
The exception is thrown when working with the devtools (F12)

**To Reproduce**
0. In VS make sure that "Just My Code" is disabled in debug config:
![image](https://user-images.githubusercontent.com/20644772/213926441-d20def1d-4ea5-4730-ba1b-f2c2ab33eca0.png)
1. During the app runtime make sure that "common language runtime exceptions" in exception settings is fully enabled like so (**checkbox on a white background**)

![image](https://user-images.githubusercontent.com/20644772/213926496-e8ad1e99-2e39-44ea-a773-0f6d6eb841ce.png)

2. Create fresh `Avalogia` app, add the community toolkit `nuget` package
3. Add a new dummy window
4. add 2 buttons to the main widnow. 

```xml
  <StackPanel>
    <Button Command="{Binding OpenNewWindowWithToken}">Open new window (with CancellationToken)</Button>
    <Button Command="{Binding OpenNewWindow}">Open new window</Button>
  </StackPanel>
```

5. create 2 commands in the main view model, one with cancellation token, one without

```cs
    [RelayCommand]
    public async Task OpenNewWindowWithToken(CancellationToken token)
    {
        var newWindow = new Window1();
        newWindow.Show();
    }

    [RelayCommand]
    public async Task OpenNewWindow()
    {
        var newWindow = new Window1();
        newWindow.Show();
    }
```

6. Launch the app. 
7. Press F12 to enter the Dev tools.
8. Click on a main window item:

![image](https://user-images.githubusercontent.com/20644772/213926550-369d267b-0cb9-4bba-80eb-618918bc12b9.png)

see the exception thrown `System.Reflection.TargetException: 'Object does not match target `

>  at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 431"

now, if you click "Continue" - the app will continue to execute just fine. This exception is only shown when you do the pre-config from "point 1".

**Expected behavior**
Exceptions shall not be thrown. If thrown - shall be handled.

**Screenshots**

![image](https://user-images.githubusercontent.com/20644772/213926525-71731a8d-84b3-4aa7-abd2-98631d6b4501.png)

**Desktop:**

- OS: Windows 10 x64
- Avalonia Version="0.10.18"
- Avalonia.Desktop Version="0.10.18"
- Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.4.3
- CommunityToolkit.Mvvm v.8.1.0

**Additional context**
The code that reproduces the problem is located in repo https://github.com/pavlexander/avaloniaExceptionTest1

**Comment by rabbitism** [comment]
I think this failure is exactly the same as https://github.com/AvaloniaUI/Avalonia/issues/10048 . You need to bind to the generated Command, which is `OpenNewWindowWithTokenCommand` and `OpenNewWindowCommand`, but not the raw method.

**Comment by maxkatz6** [comment]
Seems so. I will close this issue, as another one has more details.
