### ISSUE TITLE
Xaml Compiler error when code-behind class contains a `DllImport` method

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#10046]
**Describe the bug**
Add this code to the main class of any any `.axaml.cs` file:

```C#
[DllImport("kernel32", SetLastError = true, CharSet = CharSet.Unicode)]
public static extern IntPtr LoadLibrary(string libname);
```

`XamlCompilerTaskExecutor` will crash:

```
1>Avalonia\samples\GpuInterop\MainWindow.axaml : Avalonia error AVLN: 0004: System.NullReferenceException: Object reference not set to an instance of an object. [Avalonia\samples\GpuInterop\GpuInterop.csproj]
1>Avalonia\samples\GpuInterop\MainWindow.axaml : Avalonia error AVLN: 0004:    at Avalonia.Build.Tasks.XamlCompilerTaskExecutor.<>c__DisplayClass5_0.<CompileCore>g__CompileGroup|3(IResourceGroup group) in Avalonia\src\Avalonia.Build.Tasks\XamlCompilerTaskExecutor.cs:line 443 [Avalonia\samples\GpuInterop\GpuInterop.csproj]
1>Avalonia\packages\Avalonia\AvaloniaBuildTasks.targets(137,5): error MSB3073: The command "dotnet msbuild /nodereuse:false GpuInterop.csproj /t:CompileAvaloniaXaml /p:_AvaloniaForceInternalMSBuild=true /p:Configuration=Debug /p:TargetFramework=net7.0 /p:RuntimeIdentifier= /p:BuildProjectReferences=false" exited with code 1.
```

**Expected behavior**
The project should compile successfully.

**Desktop (please complete the following information):**

- OS: Windows
- Version: git master

**Comment by maxkatz6** [comment]
This line of code should check if Body is null or not before using it
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Build.Tasks/XamlCompilerTaskExecutor.cs#L443

`method.Body` actually can be null in case of abstract or extern members.

**Comment by codecat** [comment]
Was able to reproduce this error after updating to preview7 (it didn't give me a stack trace though). I moved my `DllImport`'s to a different static class to work around this for now.
