### ISSUE TITLE
Very slow Direct2D back-end bitmap rendering compared to SkiaSharp

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1006]
Avalonia: 0.5.1

**Demonstration:**
https://files.gitter.im/AvaloniaUI/Avalonia/E6US/Avalonia-0.5.1-SkiaSharp.mp4
https://files.gitter.im/AvaloniaUI/Avalonia/qm8E/Avalonia-0.5.1-Direct2D.mp4
**Rendering code:**
https://github.com/wieslawsoltes/Core2D/blob/master/src/Renderer.Avalonia/AvaloniaRenderer.cs#L605-L674
**Binaries:**
https://ci.appveyor.com/api/buildjobs/s5w2yaic67ovur4y/artifacts/artifacts%2Fzip%2FCore2D.Avalonia.Skia-Release-0.2.0-build1796.zip
https://ci.appveyor.com/api/buildjobs/s5w2yaic67ovur4y/artifacts/artifacts%2Fzip%2FCore2D.Avalonia.Direct2D-Release-0.2.0-build1796.zip
**Project:**
https://files.gitter.im/AvaloniaUI/Avalonia/oaHq/Rendering-Perf.project

**Comment by grokys** [comment]
I think this is because we convert WIC bitmaps to Direct2D bitmaps for each render. We probably need to cache D2D bitmaps.

**Comment by Gillibald** [comment]
This must be cached per render target and should be removed from the cache when the render target gets disposed. Quite hard to keep track.
