### ISSUE TITLE
Make all `Render` method overrides sealed

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#10066]
At some point we might want to change the way built-in primitives are rasterized.

**Comment by Mrxx99** [comment]
What @angelsix does in his youtube tutorial wouldn't work anymore? https://github.com/angelsix/youtube/blob/develop/Avalonia/AvaloniaLoudnessMeter/AvaloniaLoudnessMeter/Views/MainView.axaml.cs

**Comment by kekekeks** [comment]
There are no `Render` method overrides in `UserControl`'s inheritance hierarchy, so overriding `Render` would continue to work there.

**Comment by kekekeks** [comment]
Note that it's a bad idea to override `Render` for the `UserControl`, since it's a `ContentControl` which shows its background using `ContentPresenter`. So if `Background` property is set, it would be painted on top whatever rendering commands you have in your `UserControl`.

**Comment by maxkatz6** [comment]
Inheriting Control and overriding Render on it should be more than enough. UserControl has additional functionality to host a content inside of it which you don't need when you want to have custom draw operations from the Render method.
