### ISSUE TITLE
Make `GetPropertyChangedObservable` easier to work with

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#10062]
**Is your feature request related to a problem? Please describe.**

After #9749, using `AvaloniaObject.GetPropertyChangedObservable` becomes less friendly to work with as it still works using observables, such that the syntax:
```C#
splitView.GetPropertyChangedObservable(SplitView.IsPaneOpenProperty).Subscribe(OnSplitViewPropertyChanged)
```
is no longer valid because the `.Subscribe(Action)` is an extension from System.Reactive package that was removed. This forces either the need to get that package anyway (which is a waste to only use 1 extension method), or write something that implements `IObservable<T>` to pass in. In my case, I'm not familiar enough with observables/RxUI to do the latter.

**Describe the solution you'd like**
Avalonia.Reactive folder has extension methods that make this work again, but they're kept internal to the project. At the very least, I think having a public extension method that replaces `.Subscribe(Action)` should exist.

Alternatively, following UWP's [`DependencyProperty.RegisterPropertyChangedCallback`](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.dependencyobject.registerpropertychangedcallback?view=winrt-22621) would also work. Internally, that could probably just work off the internal extension method and return an `IDisposable`  to release it (UWP has a counterpart UnregisterPropertyChangedCallback instead, but an IDisposable would be fine here)

There is the `PropertyChanged` event on `AvaloniaObject` which could also be used, but that would notify every property where `GetPropertyChangedObservable` can focus on just one.

**Comment by maxkatz6** [comment]
From our options, what I was thinking about:

- Add Subscribe(Action) method extension in the hidden namespace, so advanced IDE can reference it and won't cause conflicts with Reactive package from out of nowhere
- Add extension method with difference name, like `SubscribeAction(Action)`
- Make single AnonymousObserver public. It still can conflict with original Reactive.AnonymousObserver, but at least it's easier to deal with class conflicts comparing to extension methods conflicts. 
- Reference System.Reactive package, so it will be always available for the developers, but not used internally in the framework. This way framework still can be trimming friendly, and for the applications it would depend if they use this package or not.
-  ... ?

We need to keep in mind, that System.Reactive have put `Subscribe(Action)` into `using System;` namespace, which is another pita. How it will work if developer reference namespaces with both extension methods?

Answering some of your questions
> This forces either the need to get that package anyway (which is a waste to only use 1 extension method)

It shouldn't be a huge waste, as one shouldn't bring too much of the code, and everything else should be trimmed out. But I am afraid it still can pollute app with "UseWPF/UseWinForms" dependencies on windows.

> or write something that implements IObservable<T> to pass in

Basically, this:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Reactive/AnonymousObserver.cs#L6

And optionally this extension method:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Reactive/Observable.cs#L20-L23

> Alternatively, following UWP's [DependencyProperty.RegisterPropertyChangedCallback](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.dependencyobject.registerpropertychangedcallback?view=winrt-22621)

But we have PropertyChanged event...

> but that would notify every property where GetPropertyChangedObservable can focus on just one.

Ah, I see what's the problem with PropertyChanged. But internally either way PropertyChanged is actually used, so there is no benefits aside from maybe more convenient way to write it.
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Reactive/AvaloniaPropertyChangedObservable.cs#L40

**Comment by maxkatz6** [comment]
Conveniently, from this PR https://github.com/AvaloniaUI/Avalonia/pull/10051/files I can get list of all IObservable used as a return type in our API:
```csharp
    public static partial class AvaloniaObjectExtensions
    {
        public static System.IObservable<Avalonia.Data.BindingValue<object?>> GetBindingObservable(this Avalonia.AvaloniaObject o, Avalonia.AvaloniaProperty property) { throw null; }
        public static System.IObservable<Avalonia.Data.BindingValue<T>> GetBindingObservable<T>(this Avalonia.AvaloniaObject o, Avalonia.AvaloniaProperty<T> property) { throw null; }
        public static System.IObservable<object?> GetObservable(this Avalonia.AvaloniaObject o, Avalonia.AvaloniaProperty property) { throw null; }
        public static System.IObservable<T> GetObservable<T>(this Avalonia.AvaloniaObject o, Avalonia.AvaloniaProperty<T> property) { throw null; }
        public static System.IObservable<Avalonia.AvaloniaPropertyChangedEventArgs> GetPropertyChangedObservable(this Avalonia.AvaloniaObject o, Avalonia.AvaloniaProperty property) { throw null; }
    }

    public abstract partial class AvaloniaProperty : Avalonia.Data.Core.IPropertyInfo, System.IEquatable<Avalonia.AvaloniaProperty>
   {
        public System.IObservable<Avalonia.AvaloniaPropertyChangedEventArgs> Changed { get { throw null; } }
   }

    public static partial class NotifyCollectionChangedExtensions
    {
        public static System.IObservable<System.Collections.Specialized.NotifyCollectionChangedEventArgs> GetWeakCollectionChangedObservable(this System.Collections.Specialized.INotifyCollectionChanged collection) { throw null; }
    }

    public partial class NameScopeLocator
    {
        public static System.IObservable<object?> Track(Avalonia.Controls.INameScope scope, string name) { throw null; }
    }

    public static partial class ResourceNodeExtensions
    {
        public static System.IObservable<object?> GetResourceObservable(this Avalonia.Controls.IResourceHost control, object key, System.Func<object?, object?>? converter = null) { throw null; }
        public static System.IObservable<object?> GetResourceObservable(this Avalonia.Controls.IResourceProvider resourceProvider, object key, System.Func<object?, object?>? converter = null) { throw null; }
    }

    public partial class InstancedBinding
    {
        public System.IObservable<object?> Source { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } }
    }

    public partial interface IInputManager
    {
        System.IObservable<Avalonia.Input.Raw.RawInputEventArgs> PostProcess { get; }
        System.IObservable<Avalonia.Input.Raw.RawInputEventArgs> PreProcess { get; }
        System.IObservable<Avalonia.Input.Raw.RawInputEventArgs> Process { get; }
    }

    public static partial class InteractiveExtensions
    {
        public static System.IObservable<TEventArgs> GetObservable<TEventArgs>(this Avalonia.Interactivity.Interactive o, Avalonia.Interactivity.RoutedEvent<TEventArgs> routedEvent, Avalonia.Interactivity.RoutingStrategies routes = Avalonia.Interactivity.RoutingStrategies.Bubble | Avalonia.Interactivity.RoutingStrategies.Direct, bool handledEventsToo = false) where TEventArgs : Avalonia.Interactivity.RoutedEventArgs { throw null; }
    }

    public partial class RoutedEvent
    {
        public System.IObservable<(object, Avalonia.Interactivity.RoutedEventArgs)> Raised { get { throw null; } }
        public System.IObservable<Avalonia.Interactivity.RoutedEventArgs> RouteFinished { get { throw null; } }
    }

    public static partial class ControlLocator
    {
        public static System.IObservable<Avalonia.LogicalTree.ILogical?> Track(Avalonia.LogicalTree.ILogical relativeTo, int ancestorLevel, System.Type? ancestorType = null) { throw null; }
    }

    public partial class VisualLocator
    {
        public static System.IObservable<Avalonia.Visual?> Track(Avalonia.Visual relativeTo, int ancestorLevel, System.Type? ancestorType = null) { throw null; }
    }

    public static partial class AncestorFinder
    {
        public static System.IObservable<Avalonia.StyledElement?> Create(Avalonia.StyledElement control, System.Type ancestorType) { throw null; }
        public static System.IObservable<T?> Create<T>(Avalonia.StyledElement control) where T : Avalonia.StyledElement { throw null; }
    }
```

CC @grokys @kekekeks

**Comment by amwx** [comment]
> From our options, what I was thinking about:
> 
>     * Return a special interface instance that implements IObservable with `Subscribe(Action)`defined in it or as an extension. This way, IDE should always prefer ours `Subscribe(Action)` regardless or using System.Reactive or not.
> 
>     * Add a `Subscribe(Action)` method extension in the hidden namespace, so advanced IDEs can reference it and won't cause conflicts with the Reactive package from out of nowhere.
> 
>     * Add an extension method with a different name, like `SubscribeAction(Action)`.
> 
>     * Make the single `AnonymousObserver` public. It still can conflict with the original `Reactive.AnonymousObserver`, but at least it's easier to deal with class conflicts compared to extension methods conflicts.
> 
>     * Reference the `System.Reactive` package, so it will always be available for the developers, but not used internally in the framework. This way, the framework can still be trimming friendly, and for the applications it would depend if they use this package or not.
> 
>     * ...?

I think # 3 is the best there as it avoids the IDE hacks 1 & 2 would require (especially with it Subscribe being in `System`). The name is also more clear on how it works. `SubscribeAction` or even deviating from Subscribe name with something like `AddHandler` (similar to RoutedEvents) or `RegisterHandler/Callback` would be fine too.

<br />

> Ah, I see what's the problem with PropertyChanged. But internally, either way, PropertyChanged is actually used, so there are no benefits aside from maybe a more convenient way to write it. https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Reactive/AvaloniaPropertyChangedObservable.cs#L40

Oh, I didn't realize that's how that worked (I hadn't looked at that source). I assumed it worked directly off of the property system for that specific property (e.g., AvaloniaProperty has `IObservable<T>.Changed`). Still, as you said it is more convenient.

Also looking at that public API, InputManager is another area where this would benefit and `GetResourceObservable`. Probably not very common to need to interact with the InputManager, but there are use cases (debugging, third-party controls with a "light dismiss-like" behavior, etc)

**Comment by grokys** [comment]
I'm rather torn on this.

On one hand I understand that System.Reactive has problems ("UseWPF/UseWinForms" dependencies on Windows) and people want a simple way to subscribe to observables without having to worry about those problems.

On the other hand, we really don't have the bandwidth to reimplement and support a System.Reactive alternative, even a small subset of it. This issue is just asking for an implementation of `.Subscribe(Action<T>)` but elsewhere there are already requests for an implementation of `.Select`.

Possibly a good compromise would be to add a method to easily subscribe to property changes. Something like:

```csharp
IDisposable AddListener<T>(AvaloniaProperty<T> property, Action<T> listener)
```

IMO, this should suffice for a large portion of use-cases.

For all other usages, there are three ways forward:

1. Get System.Reactive fixed
2. The community creates a "mini rx" library
3. Projects include a simple `IObserver<T>` implementation in their source and use that

Note that for option 3, an observer that will work for most cases can be as simple as:

```csharp
    class SimpleObserver<T> : IObserver<T>
    {
        private readonly Action<T> _listener;
        public SimpleObserver(Action<T> listener) => _listener = listener;
        public void OnCompleted() { }
        public void OnError(Exception error) { }
        public void OnNext(T value) => _listener(value);
    }
```

Used like this:

```
observable.Subscribe(new SimpleObservable(x => { /* code here */ }));
```

**Comment by amwx** [comment]
> On one hand I understand that System.Reactive has problems ("UseWPF/UseWinForms" dependencies on Windows) and people want a simple way to subscribe to observables without having to worry about those problems.
> 
> On the other hand, we really don't have the bandwidth to reimplement and support a System.Reactive alternative, even a small subset of it. This issue is just asking for an implementation of `.Subscribe(Action<T>)` but elsewhere there are already requests for an implementation of `.Select`.

I think my issue here is that so much of Avalonia is built on observables which is quite different from WPF/UWP where events or callback handlers are used. Observables are more powerful and can do more than just a simple CLR/Routed event or Action, but as I've said above, I'm not that familiar with observables/RxUI, so some things are more unintuitive, where events or something like AddHandler() is quite straightforward. #9749 caught me off guard because I didn't realize that `.Subscribe(Action)` was an extension method and I used it because that's what the Avalonia source does (as that's usually my reference for a lot of things like this). It probably also doesn't help it was in the `System` namespace.


> Possibly a good compromise would be to add a method to easily subscribe to property changes. Something like:
> 
> ```cs
> IDisposable AddListener<T>(AvaloniaProperty<T> property, Action<T> listener)
> ```

That's pretty similar to the UWP method (`RegisterPropertyChangedCallback`). Although, I'm not sure how this would be all that different from the `.Subscribe(Action)` implementation (in terms of maintenance & public API) unless you just want something that distances itself from IObservable


Worst case, for me at least, I can just write a wrapper class that works on `PropertyChanged` and avoids observables completely (since that's what `Subscribe(Action)` did anyway). Any other case (which is much less common to be fair), I guess I can just use that SimpleObserver approach (thanks for the example).

**Comment by maxkatz6** [comment]
Alright, I was going to add AddListener, but found that we already have AddListener at home:
```csharp
target.GetPropertyChangedObservable(Visual.BoundsProperty)
    .AddClassHandler<Visual>((t, args) =>
    {
        var (oldV, newV) = args.GetOldAndNewValue<Rect>();
    });
```
