### ISSUE TITLE
System.MissingMethodException in latest Avalonia nightly build

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#10073]
**Describe the bug**

An exception is shown when using DoubleTransition for the Border:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/25716486/214446529-49c3af3b-4d65-4bbb-a019-45dc360cedc8.png">

**To Reproduce**

1. Create a Border with DoubleTransition
4. See the error

**Screenshots**

<img width="825" alt="image" src="https://user-images.githubusercontent.com/25716486/214446427-ce0447a7-3144-4423-a190-28af56164a66.png">

**Desktop (please complete the following information):**

- OS: Windows 11 22H2
- Version: Latest Avalonia Nightly Build

**Comment by maxkatz6** [comment]
Looks like something wasn't recompiled on your side. 
Please do full clean and compile again.

**Comment by laolarou726** [comment]
> Looks like something wasn't recompiled on your side. 
> 
> Please do full clean and compile again. 

I tried to rebuild the project and also remove the obj folder under the project folder. But this error still pops up.

**Comment by timunie** [comment]
@laolarou726 in this case we need a minimal sample to reproduce on our side. Thx 🙏

**Comment by laolarou726** [comment]
> @laolarou726 in this case we need a minimal sample to reproduce on our side. Thx 🙏

Just found that Avalonia.Xaml.Behaviors caused this issue. I think I'll just wait for the package to update.

**Comment by timunie** [comment]
This package has also nightly builds. You may want to try them or wait as you said.
