### ISSUE TITLE
Implement ValueChanged for slider

### ISSUE THREAD

**Issue by squidink7** [AvaloniaUI/Avalonia#10080]
**Is your feature request related to a problem? Please describe.**
Currently there is no (easy) way to react to a sliders value changing. I attempted to subscribe to the slider's thumb's DragCompleted event, but due to https://github.com/AvaloniaUI/Avalonia/issues/4210 even that doesn't work.

**Describe the solution you'd like**
A ValueChanged event that gets triggered when a slider moves, similar to NumericUpDown's ValueChanged event (or WPF's slider)

**Describe alternatives you've considered**
Fixing https://github.com/AvaloniaUI/Avalonia/issues/4210 would also allow this behavior, although is a bit more cumbersome.

**Comment by maxkatz6** [comment]
> Currently there is no (easy) way to react to a sliders value changing.

You just subscribe on PropertyChanged and check for value property. 

But this event does make sense anyway for consistency with our couple of new events added recently, i.e. TextChanged.

**Comment by robloo** [comment]
I definitely like adding support for the older Event pattern. It helps a lot with migrating code. Events also *CAN* in several instances give more information than a property changed notification.

**Comment by timunie** [comment]
In Avalonia, you can just listen to PropertyChanged which is very handy. But the way you have written will also work. So test both and decide what suits your situation best.

**Comment by Antix-Development** [comment]
As a new user to Avalonia I found it very confusing that there was no ValueChanged event for sliders when they exist for other controls.
Although you can "just subscribe on PropertyChanged and check for value property", it would be much better from a new users perspective to have ValueChanged events, especially when new users are generally coming from an environment where such things exist.

**Comment by robloo** [comment]
@squidink7 I opened https://github.com/AvaloniaUI/Avalonia/pull/11362 to close this. Please take a look if you can.

**Comment by squidink7** [comment]
Looks good to me! Everything seems well with that PR, and in the case something goes wrong this can be reopened if need be, but otherwise this issue can be closed! Thanks for your work!
