### ISSUE TITLE
Underline, Strikethrough et al. Broken in TextBlock

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#10086]
**Describe the bug**

Looks like underline, strikethrough and baseline text decoration is broken in current master for TextBlock.

**To Reproduce**

1. Go to ControlCatalog TextBlock page

**Expected behavior**

Mentioned decorations should render in the middle or below text.

**Screenshots**

![image](https://user-images.githubusercontent.com/17993847/214755842-393c184a-4d3a-4b7f-89c6-1403b2827392.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version Master f38b7b223e889d38ba3e04b6aa18275ce79b3ffb

**Additional context**

**Comment by Gillibald** [comment]
Fixed by: #10167

**Comment by dayAndnight2018** [comment]
> Fixed by: #10167

By the way, How to change the underline to be wavy style?
