### ISSUE TITLE
Inconsistent render result on Avalonia Nightly and Avalonia 11.0-preview4

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#10088]
**Describe the bug**

There are some different between the latest Avalonia Nightly build and Avalonia 11.0-preview4.
In the latest nightly build, some of the elements are been removed after the animation is finished. However, they should not be removed.

**To Reproduce**

See this repo: https://github.com/laolarou726/RenderBug

`master` branch is the latest Avalonia Build (buggy)
`avalonia-11.0-preview4` branch is the Avalonia 11.0-preview4 (correct)

**Expected behavior**

The render result should be the result in [avalonia-11.0-preview4](https://github.com/laolarou726/RenderBug/tree/avalonia-11.0-preview4)

**Screenshots**

Latest Nightly:
![record-bug](https://user-images.githubusercontent.com/25716486/214788130-0329bfa6-037e-4e5e-b0d1-7c1456f952d6.gif)

Avalonia 11.0-preview4:
![record-normal](https://user-images.githubusercontent.com/25716486/214788180-f71394cd-2938-4abe-87c1-48b3b2732ceb.gif)

**Desktop (please complete the following information):**

- OS: Windows 11 22H2
- Version: Latest Avalonia Nightly Build and Avalonia 11.0-preview4

**Comment by laolarou726** [comment]
Any update on this issue? It still happens in the latest nightly build.

**Comment by maxkatz6** [comment]
@laolarou726 there is a problem in your code. You use "notifying" callback as it's like a property changed event.
Instead, you need to use actual PropertyChanged event or OnPropertyChanged virtual method.

I am not sure if it's by design or not, "notifying" callback is pretty misteryous one and used internally only.
CC @grokys

**Comment by laolarou726** [comment]
> @laolarou726 there is a problem in your code. You use "notifying" callback as it's like a property changed event. Instead, you need to use actual PropertyChanged event or OnPropertyChanged virtual method.
> 
> I am not sure if it's by design or not, "notifying" callback is pretty mysterious one and used internally only. CC @grokys

I tried using OnPropertyChanged for the AnimationLayer:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/25716486/218378100-3016ceaf-f3b6-4af5-a6a2-e39009df8c3e.png">

However, the problem still exists. It seems there are other issues related to this bug?

**Comment by maxkatz6** [comment]
Not sure about MouseEnterAnimationProperty, but I fixed that for the ActivatedProperty property:
```csharp
public static readonly StyledProperty<bool> ActivatedProperty = AvaloniaProperty.Register<WaveToggle, bool>(
    nameof(Activated));

protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
{
    base.OnPropertyChanged(change);

    if (change.Property == ActivatedProperty)
        OnActivatedChanged((AvaloniaObject)change.Sender, false);
}
```

[RenderBug.zip](https://github.com/AvaloniaUI/Avalonia/files/10719045/RenderBug.zip)

**Comment by maxkatz6** [comment]
And found this about notifying callback: https://github.com/AvaloniaUI/Avalonia/issues/3523#issuecomment-582456173

**Comment by grokys** [comment]
We should probably make the overload that accepts `notifying` internal, because this isn't the first time someone has mistaken it for `changed`.

**Comment by laolarou726** [comment]
@grokys @maxkatz6 Just noticed that if I comment those line out in the `AnimationLayerStyle.axaml`, everything will be fine:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/25716486/219225907-e50490d5-91f0-43df-a75b-ff97f2e12551.png">

Is that a bug (maybe a conflict between transition and user set value)?

**Comment by grokys** [comment]
I'm having real difficulty seeing the difference in the two screenshots in the description, they both look the same to me. What should I be looking out for?

**Comment by laolarou726** [comment]
> I'm having real difficulty seeing the difference in the two screenshots in the description, they both look the same to me. What should I be looking out for?

In 11.0 Preview-4. The red rect will preserve after the click. However in the latest nightly build. It will been removed after the click.

**Comment by maxkatz6** [comment]
@grokys I tried demo project locally and found that on 11.0 glowing animation was triggered only once for each item. After replacing "notifying" with OnPropertyChanged, I got the same result in both versions, unless I am missing something.

@laolarou726 can you give more details or update issue with latest nightly?

**Comment by laolarou726** [comment]
> @grokys I tried demo project locally and found that on 11.0 glowing animation was triggered only once for each item. After replacing "notifying" with OnPropertyChanged, I got the same result in both versions, unless I am missing something.
> 
> 
> 
> @laolarou726 can you give more details or update issue with latest nightly? 

I'll update the repro tomorrow to see the result.

**Comment by laolarou726** [comment]
> @grokys I tried demo project locally and found that on 11.0 glowing animation was triggered only once for each item. After replacing "notifying" with OnPropertyChanged, I got the same result in both versions, unless I am missing something.
> 
> @laolarou726 can you give more details or update issue with latest nightly?

Just got a new exception after updated to latest Avalonia:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/25716486/221446805-19d6f18f-f858-4b9d-a4c1-1414fe0031be.png">

**Comment by timunie** [comment]
This will be fixed soon. For now, I think there is a nuget which you need to include manually to load Fonts.Inter.

**Comment by laolarou726** [comment]
It seems because of my incorrect use of the `notifying:` callback in the property. Thank you so much for your help!
