### ISSUE TITLE
RadioButton does not correctly use GroupName when unchecking other RadioButtons

### ISSUE THREAD

**Issue by abenedik** [AvaloniaUI/Avalonia#10093]
**Describe the bug**
1. When RadioButton does not have GroupName set, then when it is checked, it unchecks all other RadioButton (regardless of their GroupName).

2. If IsChecked property is set before GroupName property is set, then this will uncheck all other RadioButtons - probably because at the time when IsChecked is processed the GroupName is not yet set and the problem from (1) will uncheck all other RadioButtons.

**To Reproduce**
Example xaml:
```
<!-- Does not work because IsChecked is set BEFORE GroupName -->
<RadioButton Content="A1" IsChecked="True" GroupName="GroupA" />
<RadioButton Content="A2" GroupName="GroupA" />
<RadioButton Content="B1" IsChecked="True" GroupName="GroupB" />
<RadioButton Content="B2" GroupName="GroupB" />

<!-- Works correctly when because IsChecked is set AFTER GroupName (also E1 and E2 below must be removed) -->
<RadioButton Content="C1" GroupName="GroupC" IsChecked="True" />
<RadioButton Content="C2" GroupName="GroupC" />
<RadioButton Content="D1" GroupName="GroupD" IsChecked="True"/>
<RadioButton Content="D2" GroupName="GroupD" />

<!-- When no GroupName is set, then IsChecked unchecks all other RadioButtons -->
<RadioButton Content="E1" IsChecked="True"/>
<RadioButton Content="E2" />
```

To reproduce (1):
When started only the E1 will be checked. If E2 is initially unchecked, then some other RadioButtons will be initially checked, but as soon as a user checks E1 or E2, all other RadioButtons will be unchecked.

**Expected behavior**
Checking RadioButton should uncheck only RadioButtons from the same GroupName. If GroupName is not set, then this should be considered as a group with empty GroupName (group only RadioButtons without GroupName set).

In WPF setting IsChecked before GroupName is correctly processed.

**Desktop**

- OS:  Windows 10
- Avalonia version: 11.0.0-preview4

**Additional context**
May be related to #2717

**Comment by rabbitism** [comment]
I submitted a PR to fix the first issue, but surprisingly the second issue is also fixed by this fix.

**Comment by kekekeks** [comment]
We have support for [DependsOnAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.windows.markup.dependsonattribute?view=windowsdesktop-7.0) which should be used for `GroupName`/`IsChecked`.
