### ISSUE TITLE
Theme Desktop vs Mobile

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#10106]
Here's a simple window shown with Theme Light / Dark on desktop and mobile.

Light mode is fine.

![Screenshot_NavigationRootWindow_1](https://user-images.githubusercontent.com/8528033/215200320-3ed13955-c2b1-4302-95fe-5cf2f2e757ad.png)
![Screenshot_android-x86 on QEMU_KVM_1](https://user-images.githubusercontent.com/8528033/215200315-ffc99870-250a-47d8-927e-3159b57aff13.png)

Dark mode is very inconsistent between desktop and mobile! The background is a different color, and more importantly... the text is not visible by default!!

![Screenshot_android-x86 on QEMU_KVM_2](https://user-images.githubusercontent.com/8528033/215200318-63a58b6e-2083-44ba-b872-275b7ec8f03e.png)
![Screenshot_NavigationRootWindow_2](https://user-images.githubusercontent.com/8528033/215200321-423ecd19-1090-4e2e-85ee-49550616427e.png)

I don't think that this is optimal behavior. Note that setting Forecolor to White makes the text appear.

Avalonia v11-preview4
OS: Garuda (Arch-based Linux)
.NET 7
Default project template. I made sure that there's no color defined in the View or Window.

**Comment by maxkatz6** [comment]
> Dark mode is very inconsistent between desktop and mobile! The background is a different color, and more importantly... the text is not visible by default!!

There should be zero difference.

**Comment by maxkatz6** [comment]
Was fixed by this PR https://github.com/AvaloniaUI/Avalonia/pull/9665
