### ISSUE TITLE
TransitioningContentControl is completely broken

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#10108]
First, the animation do not work at all. When I change `CurrentView`, the image freezes until the delay elapses.

```xaml
<TransitioningContentControl Content="{Binding CurrentView}">
    <TransitioningContentControl.PageTransition>
        <PageSlide Orientation="Horizontal" Duration="0:00:00.300" />
    </TransitioningContentControl.PageTransition>
</TransitioningContentControl>
```

Second, sometimes the new View fails to show at all and appears blank.

It's completely broken.

Avalonia11-preview4
OS: Garuda (Arch-based Linux)
.NET 7

**Comment by maxkatz6** [comment]
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/9621 https://github.com/AvaloniaUI/Avalonia/issues/9802 https://github.com/AvaloniaUI/Avalonia/issues/9463

Was fixed by https://github.com/AvaloniaUI/Avalonia/pull/9893 https://github.com/AvaloniaUI/Avalonia/pull/9803
