### ISSUE TITLE
Combobox dropdown has no items, despite items being actually presented

### ISSUE THREAD

**Issue by ZecosMAX** [AvaloniaUI/Avalonia#10100]
I have following XAML code in my `MainWindow.xaml`:
```XAML
<ComboBox SelectedIndex="0">
    <ComboBoxItem>Item 1</ComboBoxItem>
    <ComboBoxItem>Item 2</ComboBoxItem>
    <ComboBoxItem>Item 3</ComboBoxItem>
    <ComboBoxItem>Item 4</ComboBoxItem>
    <ComboBoxItem>Item 5</ComboBoxItem>
</ComboBox>
```
And a dark fluent theme in `App.xaml`: 
```XAML
<Application.Styles>
    <FluentTheme Mode="Dark"/>
</Application.Styles>
```
And when application is running, combobox's dropdown has no items inside of it:
![image](https://user-images.githubusercontent.com/20259054/215078669-c1559a09-9013-4ee6-b3f4-de34283e7d83.png)

Despite that, when combobox is in focus, i can still use keyboard arrows to navigate through items, meaning they are presented in control.
![image](https://user-images.githubusercontent.com/20259054/215078880-d18f4734-c2d8-4421-9cbb-549019f3bb19.png)

I expected items being presented inside dropdown.

- OS: Windows 10.0 build 19045
- Version: 0.10.18

**Comment by ZecosMAX** [comment]
I have more context, when ComboBox's property `IsDropDownOpen` is set to `true`, for some reason item presenter has property `IsVisible` set to `false`. Setting it manually to `true` fixes things
![image](https://user-images.githubusercontent.com/20259054/215082002-d6ec18d3-4e3c-4eeb-b8a0-2af2aa547801.png)

**Comment by timunie** [comment]
Can you please prepare a minimal sample app showing your issue? I really think there must be a custom style or whatever that does this. It's not a known issue. And I'm sure if that's by default, someone would have complained already.

**Comment by timunie** [comment]
A minimal sample would still be useful. That way we can check if there's anything else we can do. For now I'll move this issue into the discussion section as I think it's not a bug in Avalonia itself.

**Comment by ZecosMAX** [comment]
@timunie 
Absolutely. It's this project at this commit where i opened the issue and made screenshots.
https://github.com/Sweet-Devs/SweetSaber/tree/2ba50506978a15eafeaba20387e4595b9095d352.

repo is built from vs, so there shouldn't be any problem setting it up. But if anything happens i'd like to help setting it up

**Comment by ZecosMAX** [comment]
@timunie false alarm, yes, this was a fault in our project. This `ComboBox` was inside of a `TabControl` which has following styles:
```
<TabControl.Styles>
    <Style Selector="ItemsPresenter#PART_ItemsPresenter">
        <Setter Property="IsVisible" Value="False"/>
    </Style>
</TabControl.Styles>
```

So the default header would not be visible. 
And the style selector affected nested control.
We (me in particular) to notice that, sorry for that :(
