### ISSUE TITLE
[help]How to show context menu on andriod or ios?

### ISSUE THREAD

**Issue by charleypeng** [AvaloniaUI/Avalonia#10122]
I am merging my avalonia desktop app into ipad/andriod pad,  the app just fired up in andriod emulator, everything works fine except context menu won't popup, just need some help.

thanks

avalonia version: 11.0.0-preview4
emulator: android 12 teblet with 2G memory

**Comment by timunie** [comment]
Which Avalonia version do you use? What is the setup of your emulator?

**Comment by charleypeng** [comment]
> Which Avalonia version do you use? What is the setup of your emulator?

hi, i just added info in the main thread.

**Comment by timunie** [comment]
Thx. Now we need to check it out on our side. Anyway, one last hint: the development of Android is ongoing. Many bug fixes and new controls are done in the nightly builds. Probably something you want to check out.

**Comment by maxkatz6** [comment]
How are you expecting for context menus to popup?
In latest master it's working on long press / holding.

**Comment by charleypeng** [comment]
> How are you expecting for context menus to popup?
> 
> In latest master it's working on long press / holding. 

i was using context menu on a livecharts2 control, didn't try others,matbe it is the control's problem?

**Comment by maxkatz6** [comment]
@charleypeng possibly. But they likely need preview5 to get holding gesture support.

**Comment by maxkatz6** [comment]
Closing this issue as in preview5 we have Holding event and ContextRequestedEvent is raised. Once livecharts2 is updated to use this version and handle ContextRequestedEvent, it should work there.
