### ISSUE TITLE
Transparency issue when ExtendClientAreaToDecorationsHint is set

### ISSUE THREAD

**Issue by Abdesol** [AvaloniaUI/Avalonia#10128]
**Describe the bug**
Transparency issue when setting the prophet `ExtendClientAreaToDecorationsHint` to `true`. If this is not set and I only have the `TransparencyLevelHint` and `Background` properties set to `Transparent` it works.

**To Reproduce**

1. Create a new Avalonia project
2. Go to the `MainWindow.axaml`
3. In the Window tag, set the `Background` and `TransparencyLevelHint` properties to `Transparent` and `ExtendClientAreaToDecorationsHint` to true.
4. See the transparency issue

**Expected behavior**
The window should've remained transparent by adding the property `ExtendClientAreaToDecorationsHint`.

**Screenshots**
**With ExtendClientAreaToDecorationsHint set to True**
![image](https://user-images.githubusercontent.com/69455299/215386665-fddee7a7-babc-4eb3-830d-6d5edd29fd20.png)

**Without ExtendClientAreaToDecorationsHint set to True**
![image](https://user-images.githubusercontent.com/69455299/215386591-3a55fda6-b9d1-4944-8d13-a020b85480f2.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version: 0.10.18

**Comment by timunie** [comment]
Does it only happen in Release mode or also in Debug mode? If it only happens in release mode, make sure you publish with `win7-x64` or `win10-x64`

**Comment by Abdesol** [comment]
> Does it only happen in Release mode or also in Debug mode? If it only happens in release mode, make sure you publish with `win7-x64` or `win10-x64`

It is in debug mode. I didn't test it in release mode.

**Comment by timunie** [comment]
I can confirm it for 0.10.18. In version 11.0 preview4 it works as expected for me. 

*Note: I Used a semi-transparent brush for better visibility*

![image](https://user-images.githubusercontent.com/47110241/215421927-c3ffbcb9-1c8a-4e15-900d-b13dbf5c2c3e.png)

**Comment by Abdesol** [comment]
Ok. Thank you for the info. Let's settle this issue.
