### ISSUE TITLE
X11KeyTransform doesn't respect keyboard layouts

### ISSUE THREAD

**Issue by Gutawer** [AvaloniaUI/Avalonia#10123]
**Describe the bug**
On X11 and on keyboard layouts other than ANSI (e.g. ISO, which is used in most of Europe), `X11KeyTransform` doesn't work properly as it just maps directly from X11 keys to Avalonia keys without consulting the keyboard layout. For example `'` gets the correct key `Key.OemQuotes`, whereas `"` gets the wrong key (`Key.OemQuotes`, should be `Key.D2`) and `@` gets the wrong key also (`Key.D2`, should be `Key.OemQuotes`).

**To Reproduce**

1. Set up a handler via something like `OnPreviewKeyDown`, logging `e.Key`.
2. Using Linux with an ISO layout, play around with pressing keys with shift un-pressed and pressed, and the same key name will not be printed twice.

**Expected behavior**
When using shift on a key, it shouldn't change the value of `e.Key`.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Linux
- Version 6.1.6

**Additional context**
N/A

**Comment by kekekeks** [comment]
We are using `XKeycodeToKeysym` to convert keycode to a keysym which should use the current keyboard layout.

**Comment by Gutawer** [comment]
I'm assuming that this is the relevant line: https://github.com/AvaloniaUI/Avalonia/blob/81fab67becf5499f1893d23e556e1b84abcce135/src/Avalonia.X11/X11Window.Ime.cs#L99

In that case, it seems to me that what would happen here is essentially that, when shift is pressed, `index == 1` gets passed to `XKeycodeToKeysym`, so it will give the second index registered on that key on my keyboard since it's layout-aware - in other words, it returns `X11Key.at` when I press `Shift+Apostrophe`.

It then would go through `X11KeyTransform`, which maps `X11Key.at` to `Key.D2`, when the expected result would be `Key.OemQuotes`.

**Comment by kekekeks** [comment]
Not using the index breaks something else but I don't quite remember what exactly.
