### ISSUE TITLE
DataGrid Custom KeyDown Handler on Key.Enter

### ISSUE THREAD

**Issue by Artrosis** [AvaloniaUI/Avalonia#10130]
Right now, enter switches to a new row in the table. I need to assign my action to Enter, but pressing Enter is already being processed in DataGrid.cs. Is it possible to add a setting that disable KeyDown += DataGrid_KeyDown in the DataGrid constructor or separate key handlers inside ProcessDataGridKey?

**Comment by maxkatz6** [comment]
Pseducode: `dataGrid.AddHandler(KeyDown, Handler, Tunnel)` should work.
By specifying Tunnel handling, your handler will be executed before events goes to the source DataGrid.
If you want to cancel further handlers (including DataGrid itself), you can set `args.Handled = true`

For some theory how it works: https://docs.avaloniaui.net/docs/input/routed-events

**Comment by Artrosis** [comment]
Thanks. It works!
