### ISSUE TITLE
Modal Windows appear behind main window when "Stay On Top"

### ISSUE THREAD

**Issue by kuiperzone** [AvaloniaUI/Avalonia#10147]
**Describe the bug**
Previously, in v0.10, when the parent window was set to "stay on top" (in Linux), modal windows would appear on top of the main window and behave as normal.

Now, with v11 preview 4, modal windows appear behind the parent window and are not fully accessible.

See screenshot.

**To Reproduce**

Build an app with a main window and a modal child window. Set the main window to stay on top with right-click option on the title bar. Show the child modal window.

**Expected behavior**
Modal child windows appear on top of the parent, even if the parent is "stay on top".

**Screenshots**
Screenshot of the AvantGarde app built with 11 preview 4. The "stay on top" flag is set on the main window. Shown is a settings modal window, which is hidden behind the main window. This is a breaking change in preview4 for this app.

![image](https://user-images.githubusercontent.com/17156238/215910968-e82b59f4-6bd4-4fc2-a1f1-27f82c53ebc9.png)

**Desktop (please complete the following information):**

- OS: Linux Fedora 37
- Version 11 preview4 (previously worked OK in 0.10).

**Additional context**

**Comment by grokys** [comment]
@kekekeks any idea what could have caused this?

**Comment by emmauss** [comment]
@kuiperzone Does it still occur for you with preview6? Showing a window as dialog works fine on Fedora 37, even when the parent is set as always on top.

**Comment by emmauss** [comment]
Could it be an issue with the window manager. Here's a test I tried and it works fines.
https://github.com/emmauss/DialogTest
Could you try it. 
Clicking the title bar causes the parent window to activate, but it doesn't bring it on top.
And I'm also running fedora 37

**Comment by kuiperzone** [comment]
Hi @emmauss 

I've tried your project, and here is the video. As you can see, the problem is definitely still there.

The problem seems to be when you double-click on the Window Title bar behind -- this just grants focus from then on.




[Screencast from 2023-04-04 10-35-04.webm](https://user-images.githubusercontent.com/17156238/229752144-34245e5e-b7af-41d8-b61a-1fdabda7f1d7.webm)

**Comment by kuiperzone** [comment]
I'm running stock Fedora 37, with Wayland.

I have Gnome Tweaks and here my settings:

![image](https://user-images.githubusercontent.com/17156238/229752733-b052553b-6b21-4215-9428-02fefb7d34fe.png)

![image](https://user-images.githubusercontent.com/17156238/229752809-f8a4731e-f427-47b9-b8a6-fff7734362a4.png)

**Comment by kuiperzone** [comment]
Additionally, I've just tried to build your project on Pop-OS (Ubuntu 22). It won't build out of the box:

kuiper@pop-os:~/Scratch/DialogTest$ dotnet build
Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : warning CS8032: An instance of analyzer Avalonia.Generators.NameGenerator.AvaloniaNameSourceGenerator cannot be created from /home/kuiper/.nuget/packages/avalonia/11.0.0-preview6/analyzers/dotnet/cs/Avalonia.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/kuiper/Scratch/DialogTest/AvaloniaApplication4/AvaloniaApplication4.csproj]
CSC : warning CS8032: An instance of analyzer Tmds.DBus.SourceGenerator.DBusSourceGenerator cannot be created from /home/kuiper/.nuget/packages/tmds.dbus.sourcegenerator/0.0.4/analyzers/dotnet/cs/Tmds.DBus.SourceGenerator.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/kuiper/Scratch/DialogTest/AvaloniaApplication4/AvaloniaApplication4.csproj]
/home/kuiper/Scratch/DialogTest/AvaloniaApplication4/MainWindow.axaml.cs(9,13): error CS0103: The name 'InitializeComponent' does not exist in the current context [/home/kuiper/Scratch/DialogTest/AvaloniaApplication4/AvaloniaApplication4.csproj]

Build FAILED.

**Comment by emmauss** [comment]
> Ubuntu 22

is the dotnet sdk up to date?

**Comment by kuiperzone** [comment]
It's .NET 6 on Ubuntu. Literally just installed the SDK.

**Comment by emmauss** [comment]
> 

Could you install dotnet 7

**Comment by kuiperzone** [comment]
I would have to go to a Microsoft repository feed. See here: https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204

Your project was for .NET 6.

I'll have to come back to this later.

**Comment by kuiperzone** [comment]
And recall -- this problem doesn't not exhibit itself with Avalonia 0.10.19. It's only with the newer 11 versions. So I would suggest there's a change in there somewhere.

**Comment by kuiperzone** [comment]
@emmauss I was able to compile your test project, but only by changing the line:

`InitializeComponent();`

to

`AvaloniaXamlLoader.Load(this);`

Running on Pop OS, it does NOT appear to exhibit the problem. Strange!

However, I get the following warnings during the build:

CSC : warning CS8032: An instance of analyzer Avalonia.Generators.NameGenerator.AvaloniaNameSourceGenerator cannot be created from /home/kuiper/.nuget/packages/avalonia/11.0.0-preview6/analyzers/dotnet/cs/Avalonia.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/kuiper/Scratch/DialogTest/AvaloniaApplication4/AvaloniaApplication4.csproj]
CSC : warning CS8032: An instance of analyzer Tmds.DBus.SourceGenerator.DBusSourceGenerator cannot be created from /home/kuiper/.nuget/packages/tmds.dbus.sourcegenerator/0.0.4/analyzers/dotnet/cs/Tmds.DBus.SourceGenerator.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/kuiper/Scratch/DialogTest/AvaloniaApplication4/AvaloniaApplication4.csproj]

**Comment by kuiperzone** [comment]
This is very strange indeed. No other application exhibits this behaviour problem other than Avalonia apps built with Avalonia 11. Note the problem DOES NOT apply to Avalonia 10.19.

Below is a video of my app. The first part shows the app built against 10.19. No problem is displayed with 10.19.

The second part of the video shows the same app built against 11P6. Note that it displays the problem, which also applies to FilePickerDialogs. NOTE ALSO there is an intermittent element to this problem -- you can actually see it in the second part of the video. See how I open a file dialog and it initially does NOT drop behind the main the window. Then I close it and open it again -- and then it displays the problem and drops behind the window.

This does not appear to be an issue with my own code, as your own demo exhibits this issue on my system.

I'll test on Centos Stream later. I can only suggest there is a difference both between your Fedora 37 system and mine, combined with a difference between Avalonia 10.19 and 11P6. It is most bizarre!

[Screencast from 2023-04-05 12-34-26.webm](https://user-images.githubusercontent.com/17156238/230069920-3447943a-57e0-41c6-8a91-8174f1e510fc.webm)

**Comment by kuiperzone** [comment]
Actually, if you look closely at the second part of the video, you'll see that the FilePicker initially opened behind the main window.

**Comment by kuiperzone** [comment]
To be clear - the video and bug description above is when the main windows is NOT "Stay on Top". The modal interaction is just not working.

**Comment by kuiperzone** [comment]
Another update - have just tried this on AlmaLinux 9. It seems OK on this system.

**Comment by kuiperzone** [comment]
@emmauss Are you running Wayland or X11?

I've just tried it on Fedora with X11, and it seems to work.

**Comment by kuiperzone** [comment]
Actually, I haven't given up.

I've just tested your demo program on new hardware with a clean installation of Fedora 37.

It displays the same problem.

I think that Avalonia 11 P6 has an issue.

**Comment by timunie** [comment]
@kuiperzone acc. to #10751 this issue may have been solved. If possible, please double-check this issue using your machine. Thx.

**Comment by kuiperzone** [comment]
> @kuiperzone acc. to #10751 this issue may have been solved. If possible, please double-check this issue using your machine. Thx.

I'm not running Fedora anymore (now Debian 12).

However, I appreciate the update and it's great to know that it appears resolved. I will let you know if I encounter any problem in the future.

Thank you

**Comment by timunie** [comment]
closing until further notice.
