### ISSUE TITLE
ScrollViewer hijacks touch pointer captures

### ISSUE THREAD

**Issue by jhimes144** [AvaloniaUI/Avalonia#10159]
**Describe the bug**
When controls that rely on dragging elements are placed within a scroll viewer, touch events cease to be captured outside said controls. In other words - when dragging a slider within a scroll viewer via touch the drag ceases if touch leaves the confines of the slider track. This does not happen with mouse pointers. When control is not inside a scroll viewer - behavior is as expected.

**To Reproduce**

1. Create a slider within a scroll viewer
2. Observe behavior on a mobile or touch device

**Expected behavior**
When dragging a slider, I should have a "capture" so that I'm allowed to move my finger outside the confines of the small slider track while still controlling the slider until I release my touch.

**Desktop (please complete the following information):**

- OS: Windows 10 & Android
- Version 11-preview4

**Comment by kekekeks** [comment]
Slider doesn't seem to mark the event as handled, so ScrollViewer has no idea that it shouldn't handle the event. I suppose the problem here is in the Slider code.

**Comment by jhimes144** [comment]
@kekekeks It's a good thing you mentioned this. I noticed the same thing, but I found this issue originally with a custom slider control I made from scratch that does handle the events, and I still have the same issue.

**Comment by kekekeks** [comment]
PointerEventArgs now have `PreventGestureRecognition()` which is called from Thumb
