### ISSUE TITLE
Can't override `FocusAdorner` in ControlTheme

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#10158]
**Describe the bug**

Trying to customize a focus adorner in a ControlTheme will fail to apply:

```Xaml
<ControlTheme TargetType="ComboBox"
				BasedOn="{StaticResource {x:Type ComboBox}}"
				x:Key="CustomAdornerTheme">
  <Setter Property="FocusAdorner">
	  <FocusAdornerTemplate>
		  <Border BorderThickness="{DynamicResource SystemControlFocusVisualPrimaryThickness}"
				  BorderBrush="Red"
				  Margin="0">
			  <Border BorderThickness="{DynamicResource SystemControlFocusVisualSecondaryThickness}"
					  BorderBrush="{DynamicResource SystemControlFocusVisualSecondaryBrush}" />
		  </Border>
	  </FocusAdornerTemplate>
  </Setter>
</ControlTheme>
```
Will still apply the default FocusAdorner:
![image](https://user-images.githubusercontent.com/40413319/216160781-d06f2142-ebef-490d-ac06-8b50b1f01f5e.png)

The default FocusAdorner is applied using a Style Selector which seems to always take priority over the ControlTheme:
https://github.com/AvaloniaUI/Avalonia/blob/c49b8c301a89f689dad2ef85d0fe86579e9fbbdf/src/Avalonia.Themes.Fluent/Controls/FocusAdorner.xaml#L10-L21

**Comment by amwx** [comment]
Looking at this, it makes sense why this is happening (`Style`s are evaluated after `ControlTheme`) so this isn't a bug of the styling system, its a bug of how focus adorners are applied

https://github.com/AvaloniaUI/Avalonia/blob/c49b8c301a89f689dad2ef85d0fe86579e9fbbdf/src/Avalonia.Base/StyledElement.cs#L399-L415

I can think of two ways to mitigate this:

1- Define the `FocusAdornerTemplate` as a resource and make every control's ControlTheme set that. That's a lot of work and could be left off in external themes without thinking

2- Define a `DefaultFocusAdorner` property on `AdornerLayer` (with a corresponding style to globally set it). Then, in `AdornerLayer.SetAdornedElement(adorner, target)`, if `adorner` is null, it falls back to `DefaultFocusAdorner`

**Comment by maxkatz6** [comment]
Ideally, I would want to get rid of this style at all. As it would be one step closer to having whole fluent or simple theme inside of the single ResourceDictionary (after being merged by the compiler).
Possibly by overriding default value of the template properties.
