### ISSUE TITLE
Setting Transitions in ControlTheme causes a memory leak

### ISSUE THREAD

**Issue by Superhaha-1** [AvaloniaUI/Avalonia#10151]
**Describe the bug**
If Transitions are set in ControlTheme and applied to Control, when the Control is removed from the logical tree, the GC will not collect the Control, which causes a memory leak. The ControlTheme of many default controls (such as Button, ToggleSwitch) has set Transitions, as long as these controls are used, memory leaks may occur.

**To Reproduce**

1. Create new AvaloniaApplication with Avalonia Package(11.0.999-cibuild0026512-beta or later).
2. Add the following code to the end of the MainWindow method of MainWindow.xaml.cs:

            var panel = new StackPanel();
            Content = panel;
            Observable.Timer(TimeSpan.FromSeconds(3), TimeSpan.FromSeconds(1), AvaloniaScheduler.Instance).Subscribe(l =>
            {
                panel.Children.Clear();
                foreach (var i in Enumerable.Repeat(0, 100))
                {
                    panel.Children.Add(new ToggleSwitch() { Content = "Test" });
                }
            });

    This will remove previously added controls and add 100 new ToggleSwitches to the main window every second.
3. Build and run the program.
4. Observe memory consumption.

**Expected behavior**
Memory usage grows for a short period and tends to balance.

**Screenshots**
![image](https://user-images.githubusercontent.com/21350279/216023578-b22a1795-c77b-4263-8664-a4eee5dacc37.png)

**Desktop (please complete the following information):**

- OS: [Version Windows 11 Pro Version 22H2]
- Version [11.0.999-cibuild0026512-beta or later]

**Additional context**
After debugging, I have located the problem point.
When a Transitions value is applied to Animatable, it will Add Handler For NewValue and Remove Handler  for OldValue in Transitions.Transitions,This usually doesn't cause any problems.
But when the property is applied by ControlTheme and the control is removed from the logical tree, OnPropertyChanged for the property is not raised, which causes the reference of the control to be kept in OldValue.
https://github.com/AvaloniaUI/Avalonia/blob/5896e3328676ec0aaf36b35f09356051f88c24c6/src/Avalonia.Base/Animation/Animatable.cs#L112
https://github.com/AvaloniaUI/Avalonia/blob/5896e3328676ec0aaf36b35f09356051f88c24c6/src/Avalonia.Base/Animation/Animatable.cs#L125
This problem did not exist before version 11.0.999-cibuild0026512-beta.This bug may be introduced by (https://github.com/AvaloniaUI/Avalonia/commit/693065fa1e2f1f5fbbb3327d79a4a9596d236416)

**Comment by maxkatz6** [comment]
We should also subscribe and unsubscribe from the OnAttachedToVisualTree and OnDetachedFromVisualTree
Like we do for Button.IsDefault https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Button.cs#L230-L236
