### ISSUE TITLE
Has Any plan to support KotlinNative  in future ?

### ISSUE THREAD

**Issue by sgf** [AvaloniaUI/Avalonia#1015]
Kotlin-Native is C#-like language.(https://github.com/JetBrains/kotlin-native/)
i like C#,but u know,C# seems no plan to supports native compilation.
Almost all projects have stopped development.
such as like :
https://github.com/xen2/SharpLang
https://github.com/afrog33k/SharpNative
https://github.com/AlexAlbala/Alter-Native
https://github.com/ciplogic/CodeRefractor
https://github.com/dotnet/llilc
https://github.com/Microsoft/LLVMSharp

the Microsoft official's **.Net Native** is only for UWP.

only 
https://github.com/dotnet/corert
https://github.com/ASDAlexander77/cs2cpp
is Activity

but **corert** slow development of long term there will be no results
and **cs2cpp** filled with uncertainty....

but kotlin-native team seems very quickly.
and made many improvements to the C# and Java.
prospects seems will be good.And is likely very lack of UI support.

any plan to support Kotlin-Native in future ?
(In fact, C++ is also a great need for such a UI Library.But C++ are too big, too old, too complex.To support C++ is little significance.)

where,
**im using Avalonia developed a .net Core application now.
but seems its need about 50mb size files(about more than 300 dll files) [50mb size is when without compression].(using self-contained for win7-x86 platform)
It's not easy to Publish and deploy.**

**Comment by kekekeks** [comment]
Huge publish size mostly comes from Roslyn compilers, libuv and other stuff that's getting including with .NET Core by default. We've experimented with it and managed to reduce the size to ~35MB by manually referencing CoreCLR from .NET Standard project. 

For native compilation you can use Mono with AOT, it has pretty good integration with LLVM and clang toolchains which is used by Xamarin.iOS.

Not sure what do you mean by supporting Kotlin. It can't compile and use C# code as far as I know, and porting our codebase to other languages isn't something that we are planning to invest resources in in the immediate future.

**Comment by sgf** [comment]
just because C# hard to support native.
kotlin-native will support for windows.

thank u,mate. i will try different framework.

**Comment by RUSshy** [comment]
+1 for kotlin native
