### ISSUE TITLE
Style in ControlTemplate does not work for content

### ISSUE THREAD

**Issue by yll690** [AvaloniaUI/Avalonia#10161]
**Describe the bug**
Style in ControlTemplate works for template child but does not work for content

**To Reproduce**
```
  <Window.Styles>
    <Style Selector="TextBlock">
      <Setter Property="Background" Value="Red"/>
    </Style>

    <Style Selector="Button">
      <Setter Property="Template">
        <ControlTemplate TargetType="Button">
          <StackPanel>
            <StackPanel.Styles>
              <Style Selector="TextBlock">
                <Setter Property="Background" Value="Green"/>
              </Style>
            </StackPanel.Styles>
            <TextBlock Text="33333"/>
            <ContentPresenter Content="{TemplateBinding Content}"/>
          </StackPanel>
        </ControlTemplate>
      </Setter>
    </Style>
  </Window.Styles>

  <StackPanel>
    <Button>
      <TextBlock Text="11111"/>
    </Button>
    <TextBlock Text="22222"/>
  </StackPanel>
```

Copy these codes to an empty window and show it. You can see the TextBlock1 is red.

**Expected behavior**
The TextBlock1 should be green.

**Screenshots**
![image](https://user-images.githubusercontent.com/16819902/216245701-d09766b2-745b-4b27-8aac-428529ee5b64.png)

**Desktop (please complete the following information):**

- OS: Windows10
- Version 11.0 preview4 from nuget

**Additional context**
DataTemplate may has the same problem.

**Comment by maxkatz6** [comment]
I might be wrong, but IIRC that's by design, that logical tree is used for the styles lookup.
CC @grokys please confirm.

**Comment by yll690** [comment]
The "Button" actually means a custom control derived from ItemsControl. Now I add the style to the control in its constructor, then the style can apply to all its items. So is there other way to achieve this?

**Comment by maxkatz6** [comment]
`Selector="Button > TextBlock"` to handle content logically inside (it won't be applied on the template content).

**Comment by yll690** [comment]
Thank you. The Child and Descendant Selectors really work.
