### ISSUE TITLE
Window not render any more

### ISSUE THREAD

**Issue by Coloryr** [AvaloniaUI/Avalonia#10164]
**Describe the bug**
Window not render any more

**To Reproduce**

1. open the progrom
2. wait a minute
3. the window render stick

**Screenshots**
![FDZ D7X865AP7D6PJO18YWE](https://user-images.githubusercontent.com/26276037/216261453-48787c3f-a4a7-42d5-a003-016112ec731b.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version11.0.0-preview4

**Additional context**

Press `F12` open the `Debug window`, it same not render.

[my project](https://github.com/Coloryr/ColorMC)

**Comment by timunie** [comment]
In 11.0 preview builds we have many breaking changes. For example the themes have now it's own nuget package. Make sure to include them all. 

See also: https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes 

Note: If you think you found a bug, please fill out the issue template carefully. For questions use Discussions or Telegram chat.

**Comment by Coloryr** [comment]
It occur with a short time to run.

**Comment by Coloryr** [comment]
Nope, the window just not render, that is a chance that it will happen.

**Comment by Coloryr** [comment]
![M$FG5E@ M4EYTZI@D4@SX%N](https://user-images.githubusercontent.com/26276037/216265188-e2291aad-8bd7-45dc-9c01-bf053f1aeb01.png)
![N274BR67RG%IF 1G4IY4SZ9](https://user-images.githubusercontent.com/26276037/216265293-9a01a738-a80b-4a5b-82cd-fb61f85b612d.png)
![Q_91JMI3Z TR0KSXX{AA85Y](https://user-images.githubusercontent.com/26276037/216265354-6d2ffe7d-f974-4257-bbd5-22bc35a65c63.png)

I think the problem is
```
.With(new Win32PlatformOptions { UseWgl = true })
```

**Comment by timunie** [comment]
Probaly. Some errors were fixed in latest master. Maybe you want to try out nightly builds for now? 

Just a suggestion.

**Comment by maxkatz6** [comment]
Why do you need UseWGL enabled?

**Comment by Coloryr** [comment]
I need use opengl render something

**Comment by Coloryr** [comment]
> Probaly. Some errors were fixed in latest master. Maybe you want to try out nightly builds for now?
> 
> Just a suggestion.

The `nightly builds` was fix render bug, but some control not work well.

**Comment by timunie** [comment]
Yeah another bunch of breaking changes. You may need to adjust your own Styles. Check out FluentTheme for reference.

**Comment by timunie** [comment]
> The nightly builds was fix render bug, but some control not work well.

I'll close this issue now as this specific issue was fixed in nightly builds already. If you disagree, let me know.

**Comment by Coloryr** [comment]
And the `OpenGlControlBase` not render....
