### ISSUE TITLE
Textblock Inline Run inherit FontWeight from previous Run

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#10170]
**Describe the bug**

**To Reproduce**

1. Add following code to Sandbox
   ```xaml
      <TextBlock FontSize="24">
         <TextBlock.Inlines>
             <Run Text="Option("/>
             <Run Text="Active" Foreground="Red" FontWeight="Bold"/>
             <Run Text=")"/>
        </TextBlock.Inlines>
     </TextBlock>
   ```
3. Run 
4. You can see that `)` is Bold instead of Normal

**Expected behavior**
The  `)` FontWeight is Normal

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Pro x 6400 22H2
- Version 6df06941791e372f70f7c34414b3e616e721e145

Avalonia 6df06941791e372f70f7c34414b3e616e721e145
![immagine](https://user-images.githubusercontent.com/12531229/216309078-4eb7bcf7-74ef-499c-9b42-ba9cdef0ef69.png)

WPF
![immagine](https://user-images.githubusercontent.com/12531229/216309761-4db23ba2-6586-4886-b33b-07a5c9131749.png)

**Additional context**

**Comment by Gillibald** [comment]
This produces all underlying styled runs: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBlock.cs#L893

The I would have a look at that area.
