### ISSUE TITLE
Fix BindingExpressionTests

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#1018]
For now those two are skipped:

https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Markup.UnitTests/Data/BindingExpressionTests.cs#L187
https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Markup.UnitTests/Data/BindingExpressionTests.cs#L213

See #1017

**Comment by grokys** [comment]
Fixed by #1038
