### ISSUE TITLE
Window CornerRadius don't work

### ISSUE THREAD

**Issue by t115liyanpeng** [AvaloniaUI/Avalonia#10185]
I set Window CornerRadius,but dosen't work on version 0.10.18

**Comment by maxkatz6** [comment]
To get templated properties work on window, you need to remove decorations (SystemDecorations="None") and set window to transparent (TransparencyLevelHint="Transparent"). Note, you will need to implement these window decorations yourself, although it's a fine solution for splash screens and similar content.
