### ISSUE TITLE
View locator breaks when moving from preview 4 to preview 5

### ISSUE THREAD

**Issue by jaeaton** [AvaloniaUI/Avalonia#10197]
**Describe the bug**
When updating Nuget package from preview 4 to preview 5 IDataTemplate doesn't recognize the functions in viewlocator.cs ICommand isn't found.

**To Reproduce**
New Avalonia MVVM project using 10.8.5 templates
Update from preview 4 to preview 5

**Additional context**
Am I using the wrong templates?

**Comment by kikipoulet** [comment]
Try to change "IConmand" to "Command".
Lots of interfaces as "IControl" have been removed.

**Comment by timunie** [comment]
ICommand should still be there. IControl not. It's Control now. The templates are nlt yet updated, so you need to do it on your own.

**Comment by jaeaton** [comment]
After making changes as suggested "ExpressionObserver" and DataAnnotationsValidationPlugin" are inaccessible. I am likely missing something simple. 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0122	'ExpressionObserver' is inaccessible due to its protection level	ECWP Winch Data	C:\Users\Josh\source\repos\jaeaton\ECWP-Winch-Data\ECWP_Data_Programe_Ava\App.axaml.cs	24	Active
Error	CS0122	'DataAnnotationsValidationPlugin' is inaccessible due to its protection level	ECWP Winch Data	C:\Users\Josh\source\repos\jaeaton\ECWP-Winch-Data\ECWP_Data_Programe_Ava\App.axaml.cs	24	Active

**Comment by timunie** [comment]
@jaeaton please see: https://github.com/AvaloniaUI/Avalonia/discussions/10239

Note: It's not wise to answer closed issues. Your question may get missed. Use Discussions or our Telegram chat.
