### ISSUE TITLE
ThemeVariantScope doesn't refresh resources on first change of RequestedThemeVariant

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#10201]
**Describe the bug**

In my FluentAvalonia sample app, I have an option to toggle the theme for controls without changing the entire app theme. With the new ThemeVariant stuff, I've added a `ThemeVariantScope` control into the page to keep this behavior. When the theme toggle is requested the first time on the ThemeVariantScope, it doesn't tell the resources to refresh, and requires multiple attempts to get it to apply.

Video: (hopefully the clicking comes across) It takes 3 clicks to get the theme change to apply and then it works normally

https://user-images.githubusercontent.com/40413319/216727438-13159d21-51fb-4020-8618-e759a81c2bde.mp4

- Version 11.0.999-cibuild0029462-beta

**Comment by maxkatz6** [comment]
Is it pushed to the branch? Theme switch works from the first change in the control catalog which makes it weird.
Only known issue so far was with popups inside of theme variant scope.

**Comment by amwx** [comment]
> Is it pushed to the branch? Theme switch works from the first change in the control catalog which makes it weird. Only known issue so far was with popups inside of theme variant scope.

Not yet, I'm still cleaning up some of the old theme switch code but I'll try to push something out later this evening.

**Comment by robloo** [comment]
There are a few instances I see where the theme variant isn't being applied correctly. For example, a popup isn't getting it set correctly. And even overlays that were hidden but then changed to visible keep the old theme variant. Doesnt relate exactly to this issue so just FYI. Seems to indicate invalidating is broken or the property isn't (re)applied on visibility changes.

**Comment by maxkatz6** [comment]
@amwx found the issue https://github.com/AvaloniaUI/Avalonia/issues/10345
