### ISSUE TITLE
[Preview 5] CreateGlyphTypeface NullReferenceException when FontFamily is $Default

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#10205]
**Describe the bug**
Been getting random crashes in FontManagerImpl during CreateGlyphTypeface. It seems there been a regression recently that the FontManager no longer knows what to do when the FontFamily is set to $Default. This particular crash originated from DevTools

![image](https://user-images.githubusercontent.com/40413319/216743730-90130c03-b9f0-4c91-89a7-1d4e4de5404d.png)

In TextLayout:
![image](https://user-images.githubusercontent.com/40413319/216743946-8dd77bac-5006-4a81-bcec-d229d59efe6d.png)

TextCharacters.CreateShapeableRun: fallbackTypeface is null (matchFound wasn't available in the debugger but I'm assuming it was false)
![image](https://user-images.githubusercontent.com/40413319/216743997-a43c3d2b-a556-484a-ac02-93c1ac4a7e4d.png)

Which is then passed in to `FontManager.GetOrAddGlyphTypeface` with a `null` FontFamily in the Typeface, and null refs in `CreateGlyphTypeface` at `if (typeface.FontFamily.Key == null)`

Interestingly in the second screenshot, _cachedGlyphTypeface isn't null and _glyphTypefaceCache in FontManager shows an entry for $Default that seems to be properly initialized:
![image](https://user-images.githubusercontent.com/40413319/216745119-d21032f6-629e-42c2-b4db-0b57f53e7d5f.png)

Note I'm calling it preview5, but I'm actually still on `11.0.999-cibuild0029462-beta`. When I encountered this earlier I was able to repro on preview5, and I don't think there was much between that nightly build and preview5 anyway

- OS: Windows 11

**Comment by amwx** [comment]
Ok, I think this might be related to symbol fonts.
To repro:
```Xaml
<TextBlock Text="&#xE70D;"
			   FontFamily="Segoe Fluent Icons"
			   FontSize="50" />
```
(If not on Win 11, Segoe MDL2 Assets for Win 10 still works to repro)

Open DevTools & the VisualTree tab

Use Ctrl+Shift+pointer to select the TextBlock. If it doesn't crash, scroll dev tools datagrid to materialize the `Text` property row and it should crash.

**Comment by Gillibald** [comment]
So the issue is that the emergency fallback for not found typefaces isn't working? Should be able to cover this.
