### ISSUE TITLE
[Preview 5] ExpressionObserver class is no longer accessible

### ISSUE THREAD

**Issue by nsrahmad** [AvaloniaUI/Avalonia#10209]
**Describe the bug**
If using CommunityToolkit MVVM template and preview avalonia, the following line is present in `App.xaml.cs` to address #8397:
```csharp
ExpressionObserver.DataValidators.RemoveAll(x => x is DataAnnotationsValidationPlugin);
```
However, In preview 5, `ExpressionObserver` class is made internal. So I had to remove the above line. This makes the original issue come back. In my VM class, I have:
```csharp
public partial class MainWindowViewModel : ObservableValidator
{
 //...

    private DateTime? flightDate;

    [Required(ErrorMessage = "You must provide a valid flight date.")]
    public DateTime? FlightDate
    {
        get => flightDate;
        set
        {
            _ = SetProperty(ref flightDate, value, true);
            ValidateProperty(ReturnFlightDate, nameof(ReturnFlightDate));
        }
    }
 //...
```
and I see the Validation error twice:
![image](https://user-images.githubusercontent.com/10996250/216781268-4fae098d-d0d7-4669-bda9-6dd936d41ae6.png)
What is the proper way to fix this?
**To Reproduce**
The test project is at https://github.com/nsrahmad/7GUI-Avalonia/tree/master/FlightBooker

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.0 Preview 5

**Comment by maxkatz6** [comment]
It's in `BindingPlugins.DataValidators`
