### ISSUE TITLE
Control binding additional property error

### ISSUE THREAD

**Issue by Coolkeke** [AvaloniaUI/Avalonia#10208]
Demo Image:
![image](https://user-images.githubusercontent.com/37786276/216771952-9814d855-8668-42c0-9bc3-b816e48c4373.png)
![image](https://user-images.githubusercontent.com/37786276/216771999-a6dfaa7d-2d0f-4b7d-95b9-0ee74c1bb3af.png)

In fact, my IsLoaded has come into effect. Does Avalonia currently support my additional attribute binding method?

Here is my project. Please click the button with the text of "Picture" in the navigation button to immediately appear an exception
[LayuiAvaloniaPack.zip](https://github.com/AvaloniaUI/Avalonia/files/10608836/LayuiAvaloniaPack.zip)

**Comment by lintao185** [comment]
<Window
    x:Class="verification.MainWindow"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="using:verification"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Title="verification"
    d:DesignHeight="450"
    d:DesignWidth="800"
    mc:Ignorable="d">
    <Grid>
        <StackPanel>
            <Button
                x:Name="N"
                local:AA.Column="96"
                Click="MainWindow_Click"
                Content="点我啊"
                TextBlock.FontSize="45" />
            <TextBlock  Text="{ CompiledBinding #N.(local:AA.Column)}" />
        </StackPanel>

        <Popup
            x:Name="PP"
            Width="300"
            Height="300"
            StaysOpen="False">
            <Grid Background="Red" />
        </Popup>
    </Grid>
</Window>

**Comment by lintao185** [comment]
`<Window
    x:Class="verification.MainWindow"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="using:verification"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Title="verification"
    d:DesignHeight="450"
    d:DesignWidth="800"
    mc:Ignorable="d">
    <Grid>
        <StackPanel>
            <Button
                x:Name="N"
                local:AA.Column="96"
                Click="MainWindow_Click"
                Content="点我啊"
                TextBlock.FontSize="45" />
            <TextBlock  Text="{ CompiledBinding #N.(local:AA.Column)}" />
        </StackPanel>
    </Grid>
</Window>
`

**Comment by Coolkeke** [comment]
thank you

**Comment by timunie** [comment]
@Coolkeke is your issue solved? If yes, please close the issue.
