### ISSUE TITLE
Can't reference DataTemplates in style resources.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#1020]
In WPF you could add templates to resources and reference them from `ItemsControl`s. However the following doesn't currently work in Avalonia:

```
  <Window.Styles>
    <Style>
      <Style.Resources>
        <DataTemplate x:Key="PurpleData">
          <TextBlock Text="{Binding Name}" Background="Purple"/>
        </DataTemplate>
      </Style.Resources>
    </Style>
  </Window.Styles>

  <ListBox Items="{Binding Items}" ItemTemplate="{StyleResource PurpleData}"/>
```
We probably want to allow this, and might possibly also consider allowing "named" data templates in the `DataTemplates` collection which can somehow be selected.

**Comment by derekantrican** [comment]
It seems like this was checked in and completed a while ago, but it still doesn't seem to be working for me in 0.9.12. Trying this:

```
<Window.Styles>
  <Style Selector="ComboBox.enum">
    <Style.Resources>
      <DataTemplate>
        <TextBlock Text="{Binding Name}"/>
      </DataTemplate>    
    </Style.Resources>
  </Style>
</Window.Styles>
```

Gives me the error: "Unable to find suitable setter or adder for property Resources of type Avalonia.Styling:Avalonia.Styling.Style for argument Avalonia.Markup.Xaml:Avalonia.Markup.Xaml.Templates.DataTemplate, available setter parameter lists are:
Avalonia.Controls.IResourceDictionary"

**Comment by maxkatz6** [comment]
@derekantrican at least you are missing x:Key

**Comment by derekantrican** [comment]
Ah, thanks. Adding `x:Key` allows me to compile (didn't know that was required). I still have another issue but possibly unrelated to this

**Comment by maxkatz6** [comment]
@derekantrican yes, it is required. Resources without key doesn't make any sense.
Although I agree on that it should have better error message.
