### ISSUE TITLE
Add BeginMoveDrag to 'PointerPressed' event to MainWindow in preview 5

### ISSUE THREAD

**Issue by AhmedZero** [AvaloniaUI/Avalonia#10217]
**Describe the bug**
when I Add BeginMoveDrag to the 'PointerPressed' event to MainWindow, it stops all released clicks from MainWindow and there is no button working in released click mode.
**To Reproduce**
```C#
using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.ReactiveUI;
using AvaloniaClickTest.ViewModels;

namespace AvaloniaClickTest.Views
{
    public partial class MainWindow : ReactiveWindow<MainWindowViewModel>
    {
        public MainWindow()
        {
            InitializeComponent();
            PointerPressed += (_, e) =>
            {
                if (WindowState == WindowState.Normal)
                    BeginMoveDrag(e);
            };

            CloseButton.Click += CloseWindow;

        }
        private void CloseWindow(object? sender, RoutedEventArgs e)
        {
            Close();
        }

    }
}

```
```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:AvaloniaClickTest.ViewModels"
		        xmlns:views="using:AvaloniaClickTest.Views"

        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaClickTest.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="AvaloniaClickTest">

    <Design.DataContext>
        <vm:MainWindowViewModel/>
    </Design.DataContext>
	<Grid  Name="RootPanel" Margin="3">
		<Grid.RowDefinitions>
			<RowDefinition Height="auto" />
			<RowDefinition Height="*" />

		</Grid.RowDefinitions>

		<Button Name="CloseButton" ToolTip.Tip="Exit" VerticalContentAlignment="Center" HorizontalContentAlignment="Center" >
		Exit
		</Button>
	</Grid>

</Window>

```
**Expected behavior**
the button should be clicked.

**Screenshots**
there is no PointerReleased event.
![image](https://user-images.githubusercontent.com/26312527/216794219-0965570d-ef15-4416-bb03-37ef039132b2.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version [11.0.0 Preview 5](https://github.com/AvaloniaUI/Avalonia/releases/tag/11.0.0-preview5)

**Comment by Coloryr** [comment]
Like this?
https://github.com/AvaloniaUI/Avalonia/discussions/10165

**Comment by timunie** [comment]
@Coloryr probably I was wrong and it is a bug. We need to investigate it further. At least we have a workaround for now.

**Comment by AhmedZero** [comment]
> Like this? #10165

I think the problem with no PointerReleased is sent, only PointerPressed. and it doesn't send it when I use 'BeginMoveDrag'.

**Comment by maxkatz6** [comment]
Is it still reproducible after https://github.com/AvaloniaUI/Avalonia/pull/10252?
I.e., on 11.0.999-cibuild0029715-beta build.

**Comment by AhmedZero** [comment]
ok, I'll test it.
