### ISSUE TITLE
Expander styles broken when using Simple Theme

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#10226]
**Describe the bug**

Expanding an expander breaks its styles. This bug only seems to occur when using the Simple Theme. I could only create a simple repro for pointer over styles not working, although the original bug is that the list box would measure 0 height after the expander is expanded at least once. I believe it's the same bug.

**To Reproduce**

1. Clone branch https://github.com/jp2masa/Avalonia/tree/styles-bug-repro
2. Run `Sandbox`
3. Expanding any item will break its styles. At least, the border color doesn't change anymore on pointer over

**Expected behavior**

Expander's border color should change according to pointer over, even after expanding it at least once.

**Screenshots**

https://user-images.githubusercontent.com/10765201/216821300-46f71d00-98de-48eb-9b88-4004de3082d8.mp4

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: https://github.com/AvaloniaUI/Avalonia/commit/64155069c5ec97aa496fc0f3f437d475e2bf4b24

**Comment by robloo** [comment]
See here: https://github.com/AvaloniaUI/Avalonia/issues/10237#issuecomment-1418879685

It is likely all related.

**Comment by jp2masa** [comment]
After investigating a bit more, I suspect it may be related to `<Setter Property="Theme" ...>`. Fluent theme uses those too, but only for default styles, while simple theme uses those with `:expanded` pseudoclass, which triggers a theme change and breaks stuff.

### Relevant code

Simple theme control template:

https://github.com/AvaloniaUI/Avalonia/blob/d8cdac1974c817312d4ccee367e5a13f7e46cda7/src/Avalonia.Themes.Simple/Controls/Expander.xaml#L142

Simple theme setter for `Theme`:

https://github.com/AvaloniaUI/Avalonia/blob/d8cdac1974c817312d4ccee367e5a13f7e46cda7/src/Avalonia.Themes.Simple/Controls/Expander.xaml#L155-L157

Fluent theme setter for `Theme`:

https://github.com/AvaloniaUI/Avalonia/blob/d8cdac1974c817312d4ccee367e5a13f7e46cda7/src/Avalonia.Themes.Fluent/Controls/Expander.xaml#L314-L316

Additionally, I believe that the theme setter should have no effect because it has lower priority than the local value in the control template, but not sure if priorities behave the same in control themes. Also tried moving from local value to "default" style (i.e. without `:expanded`, but nothing changed.

**Comment by jp2masa** [comment]
I think I finally understand what's happening. The template changes, but the selectors are applied before the template is applied, so the styles are applied to the old template and not the new one.

I could fix it by adding `ApplyTemplate();` to `TemplatedParent.OnControlThemeChanged` override, on line 402 here:

https://github.com/AvaloniaUI/Avalonia/blob/87af06092cc4d64082fe2829364f15b085413ca1/src/Avalonia.Controls/Primitives/TemplatedControl.cs#L399-L412

Not sure if this is a fix or a hack though, could someone please confirm? Maybe @maxkatz6 or @grokys?
