### ISSUE TITLE
What Control can be Tapped

### ISSUE THREAD

**Issue by tivewsalaeharad** [AvaloniaUI/Avalonia#10225]
I need a picture with tapped event, but Image.Tapped doesn't work. Putting Image instance into border has the same effect. I can arouse Tapped when I put Image into Button, but I don't need focusable image.
Help please: what to wrap Image into, so it could be Tapped?

**Comment by jp2masa** [comment]
I just tried it on 0.10.18 and latest master, and both work correctly.

What version are you using? Can you create a minimal repro?

**Comment by timunie** [comment]
I guess either the control isn't HitTestVisivle or no Background is set. We need a Background for HitTest on Border or any other control. Transparent is fine, but null (default for Border) not.

**Comment by tivewsalaeharad** [comment]
> I guess either the control isn't HitTestVisivle or no Background is set. We need a Background for HitTest on Border or any other control. Transparent is fine, but null (default for Border) not.
@timunie Thank you very much. Right you are. Even `Background = new SolidColorBrush(Colors.Transparent)` works fine

**Comment by timunie** [comment]
There's a shortcut Brushes.Transparent if you prfer not to use XAML
