### ISSUE TITLE
Transparent window is not working on macOS with 11.0.0-preview5

### ISSUE THREAD

**Issue by carina-studio** [AvaloniaUI/Avalonia#10235]
**Describe the bug**
Setting ```Window.TransparencyLevelHint``` to ```Transparent``` seems not working on macOS with 11.0.0-preview5. The Window background is still there no matter setting ```Background``` to null or transparent. Popups with ```CornerRadius``` are also affected by this issue, there will be a visible rectangle background under the popup which should not be there. It works fine with 11.0.0-preview4.

**To Reproduce**
1. Set ```Window.TransparencyLevelHint``` to ```Transparent```.
2. Set ```Window.Background``` to null or transparent.
3. Check the window.

**Expected behavior**
No window background when setting ```TransparencyLevelHint``` to ```Transparent``` and set ```Background``` to null or transparent.

**Screenshots**
<img width="149" alt="截圖 2023-02-06 下午2 18 33" src="https://user-images.githubusercontent.com/83774431/216898833-c66eadd2-5995-42b6-a440-5d89b3c92ff4.png">

**Desktop

- OS: macOS 13.2
- Avalonia Version 11.0.0-preview5
- .NET Version: 7

**Additional context**
N/A

**Comment by maxkatz6** [comment]
It was fixed in current master. Broken in preview5.
https://github.com/AvaloniaUI/Avalonia/pull/10196
