### ISSUE TITLE
ClearButton and RevealPasswordButton doesn't work anymore

### ISSUE THREAD

**Issue by hez2010** [AvaloniaUI/Avalonia#10237]
**Describe the bug**
ClearButton and RevealPasswordButton doesn't work anymore

**To Reproduce**

1. Build CC.NetCore
2. Go to TextBox page
3. Click the clear button next to the TextBox containing "Clear Content"
4. The text will not be cleared
5. Click the reveal button next to the TextBox containing password
6. Text password cannot be revealed

**Desktop (please complete the following information):**

- Version 11.0-preview5

**Comment by rabbitism** [comment]
Can you check in dev tool to see if that button's command is bound to anything?

**Comment by MrJul** [comment]
The issue was introduced by #10133: the pointer press now always pass through the button: the underlying control handles it instead (here, the textbox). See also #10233 which has likely the same cause.

**Comment by timunie** [comment]
@MrJul great finding!
