### ISSUE TITLE
Link to building from source in wiki wrong

### ISSUE THREAD

**Issue by Mrxx99** [AvaloniaUI/Avalonia#10253]
**Describe the bug**
The (GitHub) wiki had a link under Useful links section linking to https://github.com/AvaloniaUI/Avalonia/wiki/Build-Avalonia-from-Source which does not exist, it should link to https://docs.avaloniaui.net/guides/developer-guides/build-avalonia-from-source instead

**To Reproduce**

1. Go to https://github.com/AvaloniaUI/Avalonia/wiki
2. Click on 'Building from source'
4. Message on top appears you don't have permission to edit and you stay on wiki start page

**Expected behavior**
Link works and links to build instructions

**Comment by maxkatz6** [comment]
Fixed, thanks!
Link should go here: https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md
At least for now
