### ISSUE TITLE
Rewrite BoundsTracker.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#1026]
Currently it stores the transferred bounds for each control as an attached property. This is wasteful of memory and unperformant as most of the time this information won't be needed (and attached properties aren't cheap).

I think a better system would be for the renderer to notify the bounds tracker with the bounds for each control at render time (as it does currently) but for the bounds tracker to keep a dictionary of subscriptions, to which the latest bounds are pushed. This will require a invalidation of the visual when the bounds are first subscribed, and a slight delay until the first notification, but will have lower overhead in the general case.

**Comment by jkoritzinsky** [comment]
Fixed in #1312.
