### ISSUE TITLE
TextBox When you re-enter the value, there will be multiple '0' at the end

### ISSUE THREAD

**Issue by qfmee** [AvaloniaUI/Avalonia#10262]
TextBox When binding double data type, deleting all contents will prompt the input error "is not a valid number". At this time, I don't want to have an error prompt because I haven't finished typing.
When you re-enter the value, there will be multiple '0' at the end

https://user-images.githubusercontent.com/74282924/217458253-7b8a3d8c-0ddd-4300-be09-3c2b67a0ffb1.mp4

**Comment by maxkatz6** [comment]
I don't remember exactly, but I think this behavior was changed in 11.0.
Can you confirm what version are you using, and if it works differently for you in 11.0 empty project?

Either way, having property binded to the double values make it expected to result in 0, as double cannot have "" value. Nullable double, on the other hand, might.

**Comment by qfmee** [comment]
11.0.0-preview5，After deleting all characters, the default value of 0 will be filled in, but the input cursor is before 0. You need to move the cursor backward to delete 0 again.

Yes, "double?" type is no problem. But the "double" type is the most commonly used type. So I think this is the same problem as "UpdateSourceTrigger". If there is "UpdateSourceTrigger", These problems are easy to solve

**Comment by maxkatz6** [comment]
Even with UpdateSourceTrigger you would basically delay problem to the point when control loses focus.
For the numbers input I really recommend using appropriate control - NumericUpDown.
