### ISSUE TITLE
TextBlock "Invalid size returned for measure" on headless platform

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#10274]
**Describe the bug**
Experimenting moving my unit tests to the headless platform per the suggestion following the event args public constructor stuff, and ran into an issue with TextBlock.
I've found [this](https://github.com/kekekeks/Avalonia-unit-testing-with-headless-platform) which helped with figuring out how to get the headless platform initialized (with a few tweaks for changes in 11.0). This simple test repros the problem
```C#
[Fact]
public void TextBlockWorks()
{
    var wnd = new Window();
    wnd.Content = new TextBlock() { Text = "Text" };
    wnd.LayoutManager.ExecuteInitialLayoutPass();
}
```

The `TextLayout` within `TextBlock` is returning `NaN` for `Bounds.Height` in `MeasureOverride` and it seems all of the metrics are set to `NaN` on `ShapedTextRun`. As far as I can tell, the font & glyph typeface initialize ok

![image](https://user-images.githubusercontent.com/40413319/217658800-d6cdb4fb-2df6-4e95-9c32-2fb332f38ee5.png)

- OS: Windows
- Version 11-preview5

**Comment by satial-interfaces** [comment]
I've been using headless mode for testing for a while now. Versions 0.10.18 through 11.0.0-preview4 work just fine.

I can confirm this issue on preview5 with macOS 13 as well.
