### ISSUE TITLE
Theme Variant Won't Apply to Popup

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#10292]
**Describe the bug**

First mentioned here: https://github.com/AvaloniaUI/Avalonia/issues/10201#issuecomment-1420205331, Theme Variant doesn't seem to apply to popups for controls that are in-scope of the change theme variant. 

**To Reproduce**

1. Go to ControlCatalog Theme Variants page
2. Change the dropdown to the opposite theme variant than that currenlty applied to the app
3. Open the variant drop down again
4. Notice the ComboBox drop down popup is the wrong theme variant.

**Expected behavior**

If a Theme Variant applies to a control, it also needs to be inherited by a Popup. I know we've had problems with this type of thing in the past but it's a must to at least have a special case here.

**Screenshots**

![image](https://user-images.githubusercontent.com/17993847/217997973-02e710e0-ce5f-4464-86d0-3eecd0472d2e.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.0-preview5

**Comment by robloo** [comment]
Thinking about this some more, Foreground is correct. So the issue may be more complex than simply the variant not being applied.

**Comment by rabbitism** [comment]
> Thinking about this some more, Foreground is correct. So the issue may be more complex than simply the variant not being applied.

I think Foreground is applied because ThemeVariantScope has a default textelement foreground in control theme.

**Comment by robloo** [comment]
Good point. I really should have gone through the theme variant PR by now...

**Comment by maxkatz6** [comment]
> I think Foreground is applied because ThemeVariantScope has a default textelement foreground in control theme.

So is the same about Background. There is most likely some issue with inheriting properties from the Popup. I haven't investigated it yet.

**Comment by maxkatz6** [comment]
Or wait. 
PopupRoot has null background, as it's expected for the popups to have transparent background by default.
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/PopupRoot.xaml#L4
Foreground is set though.

Now, ComboBox popup root element has background set, which apparently ignores inherited theme variant (which should be inherited from the ComboBox itself).
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/ComboBox.xaml#L122

**Comment by robloo** [comment]
@maxkatz6 It looks like this one is more than just the background and isn't quite resolved yet. The issue is visible in FluentAvalonia's current master with the ColorPicker.

![image](https://user-images.githubusercontent.com/17993847/221744601-8689ba62-8349-4fe3-aa40-a643c11e5eaf.png)

https://github.com/amwx/FluentAvalonia/issues/314
