### ISSUE TITLE
Textblock rendered as visual brush in combobox. 

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#10291]
**Describe the bug**
When directly set `TextBlock` as `ComboBox` 's Items, selected item will be rendered as Rectangle with the text as brush.

**To Reproduce**
Add below control in any of your sample project. 
```xaml
  <ComboBox>
    <TextBlock>AAA</TextBlock>
    <TextBlock>BBB</TextBlock>
    <TextBlock>CCC</TextBlock>
  </ComboBox>
```
The selected Item looks abnormal. 

![image](https://user-images.githubusercontent.com/14807942/217986621-f5d35d73-0dc7-4686-b9b9-ff881cce01d8.png)

**Expected behavior**
It should behave exactly as set `ComboBoxItem` directly as `Items`, which looks like below. 
![image](https://user-images.githubusercontent.com/14807942/217986879-bd39a73c-7acc-41b3-a093-5cc32c34f7e0.png)

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0.0-preview5

**Additional context**
Checking the Visual tree, when item is TextBlock, it is converted to a Rectangle with the text as visual brush. 
![image](https://user-images.githubusercontent.com/14807942/217987254-8d1df100-3a09-4135-b4b1-9e758431c39e.png)

This is the logic from 

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/ComboBox.cs#L421-L454

Here TextBlock is not a ContentControl thus it goes to the Rectangle logic. Why do we need to do this? 

I found this issue when I was developing Semi.Avalonia, it looks way much worse when apps are published. 

![image](https://user-images.githubusercontent.com/14807942/217989419-46749586-83bc-4376-aef9-f56d366d986a.png)

**Comment by danielmayost** [comment]
Well, the same control cannot be simultaneously attached to both the ComboBox and its Popup.

When it is inside a ComboBoxItem, then its Content is a string, which causes a new TextBox control to be created inside the ComboBox, but when you specify that it is a TextBlock, it is not possible to connect the same TextBlock twice to the visual tree.

**Comment by danielmayost** [comment]
It still seems to me a bug in VisualBrush.

**Comment by rabbitism** [comment]
> It still seems to me a bug in VisualBrush.

Yep, the visual brush looks awkward. But I think it's another issue.
