### ISSUE TITLE
DevTools can't inspect views that aren't windows or single view of a mobile app

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#10296]
For some reason it's now tightly coupled with application lifetimes (those aren't guaranteed to be present at all) and only shows windows or the main view. So it's no longer possible to inspect any embedded TopLevels.

Since it's a regression from 0.10.x I'm considering to revert https://github.com/AvaloniaUI/Avalonia/pull/6771

**Comment by workgroupengineering** [comment]
I don't agree to copletaly revert the PR. Original PR can manage both path, see [this](https://github.com/AvaloniaUI/Avalonia/pull/6771#issuecomment-974524079). If you want, I can fix the current behavior to handle both molality.

**Comment by workgroupengineering** [comment]
Hi, @kekekeks 
What  is issue you found?
I have moditfy following file:

`./samples/MobileSandbox/App.xaml.cs`

```diff
    public class App : Application
    {
        public override void Initialize()
        {
            AvaloniaXamlLoader.Load(this);
        }

        public override void OnFrameworkInitializationCompleted()
        {
            if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktopLifetime)
            {
                desktopLifetime.MainWindow = new MainWindow();
            }
            else if (ApplicationLifetime is ISingleViewApplicationLifetime singleViewLifetime)
            {
                singleViewLifetime.MainView = new MainView();
            }

            base.OnFrameworkInitializationCompleted();
+            this.AttachDevTools(new()
+            {
+                StartupScreenIndex = 1,
+            });
        }
    }
```

`./samples/MobileSandbox.Desktop/Program.cs`
```diff
 using System;
 using Avalonia;
+using Avalonia.Controls;
+using Avalonia.Controls.ApplicationLifetimes;
 
 namespace MobileSandbox.Desktop
 {
     static class Program
     {
         [STAThread]
-        static int Main(string[] args) =>
-            BuildAvaloniaApp()
+        static int Main(string[] args)
+        {
+            var lt = new MyClass();
+            var app = BuildAvaloniaApp()
                 .StartWithClassicDesktopLifetime(args);
+            lt.Start();
+            return app;
+        }
 
         /// <summary>
         /// This method is needed for IDE previewer infrastructure
@@ -18,4 +25,17 @@ public static AppBuilder BuildAvaloniaApp()
                 .UsePlatformDetect()
                 .LogToTrace();
     }
+
+    class MyClass : ISingleViewApplicationLifetime
+    {
+        public Control MainView { get ; set; }
+        public void Start()
+        {
+            var host = new MainWindow()
+            {
+                Content = MainView,
+            };
+            host.Show();
+        }
+    }
 }
```

And i try run, it work as expected.

**Comment by kekekeks** [comment]
1) try attaching devtools to a window when running without application lifetime
2) try attaching devtools to embedded toplevels in WindowsInteropTest test app

**Comment by kekekeks** [comment]
Note, that application lifetimes has always been an _entirely optional feature_ and is documented as such. Even `ApplicationLifetime` is nullable. Nothing in the framework should break if there is no registered lifetime.

This is important for various embedding scenarios like this one:



https://user-images.githubusercontent.com/1067584/218268515-ede3a3d6-2e20-46ad-83da-4a77353fe4cc.mp4

**Comment by workgroupengineering** [comment]
> 

OK! I got it. Can you give me a sample repo to try and fix this?

**Comment by maxkatz6** [comment]
@workgroupengineering 
[AppMain.zip](https://github.com/AvaloniaUI/Avalonia/files/10760446/AppMain.zip)

```csharp
[STAThread]
public static void Main(string[] args)
{
    BuildAvaloniaApp().Start(AppMain, args);
}

private static void AppMain(Application app, string[] args)
{
    app.Run(new MainWindow());
}

public static AppBuilder BuildAvaloniaApp()
    => AppBuilder.Configure<App>()
        .UsePlatformDetect()
        .LogToTrace();
```
