### ISSUE TITLE
DataGrid control

### ISSUE THREAD

**Issue by Sergey-Terekhin** [AvaloniaUI/Avalonia#1030]
May be it is possible not to implement control from scratch, but port one of OS controls

Possible candidates:

1. http://wpftoolkit.codeplex.com (MS-PL license) - and many other controls can be ported from that
2. http://jibgridwpf.codeplex.com/ (MS-PL license) - never used it
3. "vanilla" wpf control (don't know if it's license allows to port it) - I think, it's successor of p.1

**Comment by kekekeks** [comment]
JibGrid is an *extension* for built-in WPFs DataGrid.

Xceed.Wpf.DataGrid consists of 562 `.cs` files (78610 lines of code excluding whitespace and lines with only `{` and `}` characters) and 59 `.xaml` files (54604 lines of code).  Avalonia itself consists of ~125K lines of code excluding tests and samples.

Other open-sourced data grids (notably [Telerik's one for UWP](https://github.com/telerik/UI-For-UWP)) are comparable in size.

**Comment by Sorien** [comment]
there are few more at github like https://github.com/akgulebubekir/Xamarin.Forms.DataGrid/tree/master/Xamarin.Forms.DataGrid, https://github.com/oriches/Simple.Wpf.DataGrid

**Comment by kekekeks** [comment]
WPF's implementation of DataGrid is available [here](https://wpf.codeplex.com/SourceControl/latest#Toolkit-development/DataGrid/Microsoft/Windows/Controls/DataGrid.cs) under MS-PL

**Comment by ForNeVeR** [comment]
Another option is to port [SilverLight DataGrid](https://github.com/mono/moon/tree/cb343939d3f5731d8c1509beb90c051c63a83903/class/Microsoft.SilverlightControls/Controls/Data/src/DataGrid) available under the terms of MS-PL (thanks to @kekekeks for the link).

**Comment by redbaty** [comment]
Up 👍

**Comment by KvanTTT** [comment]
Is it time to close this issue?
