### ISSUE TITLE
ISkiaDrawingContextImpl and DrawText isn't anymore available on 11.0.0-preview5

### ISSUE THREAD

**Issue by inforithmics** [AvaloniaUI/Avalonia#10304]
**Describe the bug**
ISkiaDrawingContextImpl isn't anymore available

**To Reproduce**

1. https://github.com/Mapsui/Mapsui/pull/1829
2. Uncomment following Code Section in the File MapControl.cs

```
//var canvas = (context as ISkiaDrawingContextImpl)?.SkCanvas;
//if (canvas == null)
//    context.DrawText(Brushes.Black, new Point(), _noSkia.PlatformImpl);
//else
//{
//    canvas.Save();
//    _mapControl.CommonDrawControl(canvas);
//    canvas.Restore();
//}
```

**Expected behavior**
ISkiaDrawingContextImpl is availble it seems this Interface was removed and no alternative for it exists.
DrawText was removed too. But this is not so important.

- OS: Windows
- Version [11.0.0-preview5]

**Comment by maxkatz6** [comment]
New API:
```csharp
var leaseFeature = context.GetFeature<ISkiaSharpApiLeaseFeature>();
if (leaseFeature == null)
    return;
using var lease = leaseFeature.Lease();
var canvas = lease.SkCanvas;
```
