### ISSUE TITLE
Tracking issue: breaking changes and common problems with 0.10.x -> 11.0 upgrade

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#10300]
This is mostly a bullet list of stuff we'll need to put in the docs.

Q:
>all my UserControls and Window now get an error saying missing InitializeComponent. 
>
> ```
>  public MainWindow() {
>    InitializeComponent();
>  }
>
> Is InitializeComponent no longer needed?

A: update / add package reference to avalonia sourcegenerators https://www.nuget.org/packages/XamlNameReferenceGenerator/

Q: Next one, I used to have `<FluentTheme Mode="Dark"/>` in my App.axaml, but Mode seems to no longer be there?
A: `<App RequestedThemeVariant="Dark" />`

**Comment by robloo** [comment]
Might be a good idea to run a script listing GitHub PRs with the breaking change tag.

**Comment by maxkatz6** [comment]
Do we need this issue, when we have mostly up to date this page https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes ?

At some point we should double check PRs with breaking change tag, yes.

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/wiki/Avalonia-11-Porting-Guide
