### ISSUE TITLE
duplicated lines

### ISSUE THREAD

**Issue by jcyuan** [AvaloniaUI/Avalonia#10315]
err, this is not a bug, not sure if that's an oversight?

https://github.com/AvaloniaUI/Avalonia/blob/f5d28eb08c957f49c091349311666e8ce1579a10/src/Windows/Avalonia.Win32/Win32GlManager.cs#L18-L19

**Comment by maxkatz6** [comment]
Not a bug, just oversight. Maybe merge conflict. 
One line can be removed, but it's also not harmful.

**Comment by jcyuan** [comment]
> Not a bug, just oversight. Maybe merge conflict. One line can be removed, but it's also not harmful.

yeah.  ✌

**Comment by timunie** [comment]
@jcyuan if you want to file a PR for this, feel free to do.

**Comment by jcyuan** [comment]
> @jcyuan if you want to file a PR for this, feel free to do.

done~
