### ISSUE TITLE
DBus OpenFolderPickerAsync returns an empty list on Ubuntu

### ISSUE THREAD

**Issue by 0x90d** [AvaloniaUI/Avalonia#10320]
**Describe the bug**
Calling `OpenFolderPickerAsync` returns an empty list on Ubuntu. Works fine on Windows.

**To Reproduce**

```C#
var paths = await window.StorageProvider.OpenFolderPickerAsync(new FolderPickerOpenOptions() {
					Title = "Select folder"
				});
Console.WriteLine(paths.Count.ToString());
```

**Expected behavior**
1, but I got 0 instead.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04.5 LTS
- Version: 11.0.0-preview4

**Additional context**
I've also noticed I cannot select an empty folder. I have to select a file within a folder, otherwise the "open" button is disabled.

**Comment by maxkatz6** [comment]
Is it managed file picker or gtk or dbus? See https://github.com/AvaloniaUI/Avalonia/issues/9383#issuecomment-1308330326

All of these options were tested with folders. Though I assume you might have a specific linux that doesn't support dbus folder yet.

**Comment by 0x90d** [comment]
I'm not fully sure, my program.cs looks like this:

```
		public static AppBuilder BuildAvaloniaApp()
			=> AppBuilder.Configure<App>()
				.UsePlatformDetect()
				.With(new SkiaOptions { MaxGpuResourceSizeBytes = 8096000 })
				.With(new Win32PlatformOptions { UseWindowsUIComposition = true })
				.UseReactiveUI();
```

FYI: Also happens on 11.0.0-preview5

**Comment by 0x90d** [comment]
Tried the mentioned workaround, works fine. It indeed doesn't support dbus... that must be an exotic feature if Ubuntu cannot work with it.

**Comment by maxkatz6** [comment]
What is your specific ubuntu version, desktop environment and file manager? I can try to run it in the virtual machine. Probably not too soon though.

**Comment by 0x90d** [comment]
As written above its OS: Ubuntu 20.04.5 LTS. Not sure what you mean with desktop environment or file manager. I don't use anything specific. Everything should be "default". I can confirm that disabling dbus makes it work again.

Ideally Avalonia would see if dbus is supported on the OS and if not disable it itself, as I cannot really control what Linux distro a user is running. So I'd have to disable that feature forever if I dont want to risk complaints. Is there a way for Avalonia to do that in the future?

**Comment by pelva** [comment]
Many people start doing cross-platform development from the Windows platform and don't know what the difference is between DBus or GTK, so I recommend OpenFolderPickerAsync in Tutorials explaining the special settings for Ubuntu.

public static AppBuilder BuildAvaloniaApp()
    => AppBuilder.Configure<App>()
        .UsePlatformDetect()
        .With(new X11PlatformOptions
        {
            UseDBusFilePicker = false // to disable FreeDesktop file picker
        })

**Comment by pelva** [comment]
![image](https://github.com/AvaloniaUI/Avalonia/assets/135562884/1dfcb127-a004-4b63-81f3-02cc46b7468f)
Such a simple introduction will only make people think it is a universal method.

**Comment by pelva** [comment]
In fact, users don't care at all about what technology is used to select folders. Why can't this function detect the types supported by the current system?
The less users think, the more successful Avalonia will be.

**Comment by maxkatz6** [comment]
> Why can't this function detect the types supported by the current system?

Because it's difficult on Linux. And right now Avalonia does fallback to GTK, if FreeDesktop implementation is not available. But it doesn't fallback, if FreeDesktop failed for some reason.

**Comment by maxkatz6** [comment]
Any working ideas to improve current dialogs are welcomed, as well as PRs.

**Comment by maxkatz6** [comment]
Avalonia has a better fallback mechanism now in nightly builds - https://github.com/AvaloniaUI/Avalonia/pull/15929. Closing this issue.
