### ISSUE TITLE
Expose `Avalonia.Win32.Input.KeyInterop`

### ISSUE THREAD

**Issue by tomenscape** [AvaloniaUI/Avalonia#10322]
This type contains a mapping between `Avalonia.Input.Key` and Windows' [virtual keys](https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes). This mapping will (I hope!) never change, so there is no reason for the type to be internal. It should become public.

We are currently copy/pasting the dictionary into our own application to work around the type being private.

**Comment by maxkatz6** [comment]
It will be unlikely to added, as we went in the opposite direction - make internal everything that isn't part of the Framework API itself.
As we don't want to maintain API stability of the implementation details.
For instance, virtual keys enum is unlikely to change in the Windows, but we planned to migrate to https://github.com/microsoft/CsWin32 at some point. Which would replace this enum with internal codegen anyway.

> We are currently copy/pasting the dictionary into our own application to work around the type being private.

I can only recommend trying CsWin32.

**Comment by tomenscape** [comment]
The only public members of the type are these two methods:

* `public static Key KeyFromVirtualKey(int virtualKey, int keyData)`
* `public static int VirtualKeyFromKey(Key key)`

These method signatures are not tied to any implementation details.
