### ISSUE TITLE
ItemsProperty of ItemsPresenter is gone in 11-preview-5

### ISSUE THREAD

**Issue by sekkit** [AvaloniaUI/Avalonia#10353]
Upgrade avalonia from 11-preview-4 to 11-preview-5
<ItemsPresenter 
       Items="{TemplateBinding Items}">

When compile, ItemsProperty is gone, throws an error.

**Comment by rabbitism** [comment]
Expected change. Just remove this property.

**Comment by sekkit** [comment]
how to rewrite ItemsPresenter to be compatible with preview5?
`<Setter Property="Template">
            <ControlTemplate>
                <DockPanel>
                    <ItemsPresenter x:Name="PART_ItemsPresenter"
                                    Items="{TemplateBinding Items}"
                                    ItemsPanel="{TemplateBinding ItemsPanel}"
                                    ItemTemplate="{TemplateBinding ItemTemplate}"
                                    ZIndex="1"
                                    DockPanel.Dock="{TemplateBinding TabStripPlacement}"/>
                    <Border BorderBrush="{DynamicResource AeroTabControlOuterBorderBrush}"
                            BorderThickness="0,0,2,1">
                        <Border BorderBrush="{TemplateBinding BorderBrush}"
                                BorderThickness="{TemplateBinding BorderThickness}"
                                Background="{TemplateBinding Background}">
                            <DockPanel>
                                <Control x:Name="EdgePaddingHelper"
                                        Width="4"
                                        Height="4"
                                        DockPanel.Dock="{TemplateBinding TabStripPlacement}"/>
                                <ContentPresenter x:Name="PART_SelectedContentHost"
                                                Margin="{TemplateBinding Padding}"
                                                HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}"
                                                VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}"
                                                Content="{TemplateBinding SelectedContent}"
                                                ContentTemplate="{TemplateBinding SelectedContentTemplate}" />
                            </DockPanel>
                        </Border>
                    </Border>
                </DockPanel>
            </ControlTemplate>
        </Setter>`

**Comment by maxkatz6** [comment]
Check templates from default controls as a reference
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Simple/Controls/TabControl.xaml#L16-L17
