### ISSUE TITLE
ListBox with variable height items using Expander and virtualization shows items on top of each other

### ISSUE THREAD

**Issue by msneijders** [AvaloniaUI/Avalonia#10367]
**Describe the bug**
A ListBox with variable height ItemTemplate by using an Expander shows items on top of each other while scrolling them into view.
(also some scroll 'skipping' while scrolling them out of view? see video)

(ps. after multiple scroll passes, there seem to appear 'ghost' items in view)

this is using `11.0.999-cibuild0030035-beta`.

**To Reproduce**
[ListBox_VariableHeightItems.zip](https://github.com/AvaloniaUI/Avalonia/files/10757213/ListBox_VariableHeightItems.zip)

ListBox looks like:
```xaml
    <ListBox Items="{Binding Items}">
        <ListBox.ItemTemplate>
            <DataTemplate DataType="vm:Item">
                <Expander HorizontalAlignment="Stretch" IsExpanded="{Binding IsExpanded, Mode=TwoWay}">
                    <Expander.Header>
                        <TextBlock Text="{Binding Index}" />
                    </Expander.Header>
                    <Panel Height="250" Background="Black" />
                    <!--  instead of panel I'd like to do an inner ListBox for a simple master-detail pattern  -->
                </Expander>
            </DataTemplate>
        </ListBox.ItemTemplate>
    </ListBox>
```

**Expected behavior**
Items adjacent to each other.

**Screenshots**

https://user-images.githubusercontent.com/27849065/219400418-5ba2c2ed-a295-42dc-8923-55304016cd8a.mp4

**Comment by grokys** [comment]
@msneijders I wonder if you could give #10892 a try and see if it fixes your issue, or introduces any new issues?

**Comment by msneijders** [comment]
yes! def will give it a try in my real-world case (somewhere this week)
