### ISSUE TITLE
No minimum animation in `Windows` but it show in `Linux` and `macOS`

### ISSUE THREAD

**Issue by Coloryr** [AvaloniaUI/Avalonia#10365]
**Describe the bug**
when set `SystemDecorations="BorderOnly"`, minimum animation not display

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win11
- Version: 11.0.0-preview4

**Additional context**

**Comment by maxkatz6** [comment]
Not sure if it's Avalonia bug. Can it be reproducible with winforms or wpf?

**Comment by Coloryr** [comment]
> Not sure if it's Avalonia bug. Can it be reproducible with winforms or wpf?

wpf same....
