### ISSUE TITLE
Preview 5 - Controls not Responding to Mouse Clicks

### ISSUE THREAD

**Issue by HobbesKo** [AvaloniaUI/Avalonia#10385]
**Describe the bug**
Buttons, DatePicker, and Window Close and Minimize buttons are not responding to mouse clicks.
The running (or debugging) app needs to be closed from within the IDE (Rider).
I've had no problem with click events until Avalonia Preview 5.

**To Reproduce**
Click on a control.

**Expected behavior**
Control should respond to the mouse click and run the associated event.

- Avalonia 11.0.0-preview5
- Microsoft Windows 11 Pro
- 10.0.22621 Build 22621

**Comment by maxkatz6** [comment]
It was fixed with the latest nightly builds.

**Comment by HobbesKo** [comment]
Ah, OK. Thanks.

Is the latest nightly reasonably stable?
