### ISSUE TITLE
Compile error trying to bind event handler in View if event handler is in ViewModel

### ISSUE THREAD

**Issue by TrevorDArcyEvans** [AvaloniaUI/Avalonia#10383]
**Describe the bug**
Compile error trying to bind event handler in _View_ if event handler is in _ViewModel_

**To Reproduce**

1. extract project
2. `dotnet build`
3. compile error

**Expected behaviour**
compile cleanly

**Observed behaviour**
compile error:
```text
C:\dev\trevorde\Avalonia_EventHandler\MainWindow.axaml(39,7,39,7): Avalonia error XAMLIL: Unable to find suitable setter or
 adder for property SelectionChanged of type Avalonia.Controls:Avalonia.Controls.AutoCompleteBox for argument Avalonia.Mark
up:Avalonia.Data.Binding, available setter parameter lists are: [C:\dev\trevorde\Avalonia_EventHandler\AstroGrep.Core.UI.cs
proj]
C:\dev\trevorde\Avalonia_EventHandler\MainWindow.axaml(39,7,39,7): Avalonia error XAMLIL: System.EventHandler`1<Avalonia.Co
ntrols.SelectionChangedEventArgs> Line 39, position 7. [C:\dev\trevorde\Avalonia_EventHandler\AstroGrep.Core.UI.csproj]
```
**Avalonia versions:**
* Avalonia ="0.10.18"
* Avalonia.Desktop ="0.10.18"
* Avalonia.ReactiveUI ="0.10.18"
* ReactiveUI ="18.4.20"

**dotnet version**
```bash
$ dotnet --version
7.0.103
```

**Workaround**
* put event handler in _View_
* raise event in _View_
* subscribe to event in _ViewModel_

[Avalonia_EventHandler.zip](https://github.com/AvaloniaUI/Avalonia/files/10768581/Avalonia_EventHandler.zip)

**Comment by timunie** [comment]
EventHandler goes into code behind. If you want to do it the ViewModel, use Behaviors or use the SelectionModel instead.

**Comment by TrevorDArcyEvans** [comment]
Thanks for the prompt response and guidance.

I have bound the _ViewModel_ to a suitable property (_Text_) which allows me to monitor changes.

MainWindow.axaml
```xaml
  <Grid>
    <AutoCompleteBox 
      Items="{StaticResource FileFilters }"
      Text="{Binding CurrentText}"
      />
  </Grid>
```

MainWindowViewModel.cs
```csharp

  public void OnTextChanged(object sender, string newValue)
  {
    Debug.WriteLine($"OnTextChanged --> {newValue}");
  }

  private string _currentText;
  public string CurrentText
  {
    get => _currentText;

    set
    {
      if (_currentText == value)
      {
        return;
      }

      this.RaiseAndSetIfChanged(ref _currentText, value);
      OnTextChanged(this, CurrentText);
    }
  }
```
