### ISSUE TITLE
Re-Implement OpenFolderDialog

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1039]
For some reasoned open folder dialog implementation for windows was removed.

Can we have it back?

**Comment by grokys** [comment]
The code hasn't been removed - it's just been disabled when building the .NET standard libraries. I'm not 100% sure why this is, but there's likely something missing from .NET standard that was needed by the method.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/SystemDialogImpl.cs#L158

**Comment by kekekeks** [comment]
There are two sections in UnmanagedMethods.cs that are excluded from netstandard build:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs#L1158

`FileOpenDialogRCW` could be completely replaced by a call to [CoCreateInstance](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686615(v=vs.85).aspx)

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs#L814

I have no idea why `
[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]` is even there, it probably could be safely removed from interface declaration.

**Comment by kekekeks** [comment]
Was fixed by https://github.com/AvaloniaUI/Avalonia/commit/f330132dc3232ebd914a29d095a9a44e9f1f45c5#diff-9def25676bc7b05de7954630a4f9da10
