### ISSUE TITLE
Null DataTemplate at the top of DataTemplates eats left DataTemplates

### ISSUE THREAD

**Issue by Sophisticated-IS** [AvaloniaUI/Avalonia#10397]
**Describe the bug**
Null DataTemplate at the top of DataTemplates eats others DataTemplates. After Binded property was changed to concrete type(not null) template does not changes.

If you put x:Null dataTemplate to bottom of DataTemplates List it works fine!

**To Reproduce**

  ```
<ContentControl Margin="5"
                        Content="{Binding SelectedTag,Mode=TwoWay}"
                        Background="WhiteSmoke">
            <ContentControl.DataTemplates>
                
                <DataTemplate DataType="{x:Null}">
                    <TextBox Text="Tempalte Null" />
                </DataTemplate>
                
                <DataTemplate DataType="{x:Type netPlatform:RandomTag}">
                    <TextBlock Text="TemplateRandomTag"/>
                </DataTemplate>
                
                <DataTemplate DataType="{x:Type netPlatform:SinusTag}">
                    <TextBox Text="TemplateSinusTag" />
                </DataTemplate>
                
                <DataTemplate DataType="{x:Type netPlatform:PulseTag}">
                    <TextBox Text="TemplatePulseTag" />
                </DataTemplate>
                
            </ContentControl.DataTemplates>
        </ContentControl>
```

**Expected behavior**
When Binded property is not null it should show its concrete type template.

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.18

**Comment by maxkatz6** [comment]
This scenario is not supported. When using DataTemplates, user must set specific non-null DataType.
It was undefined behavior in 0.10 but will produce an error in 11.0 version.
See https://github.com/AvaloniaUI/Avalonia/pull/8221 for more details.

> If you put x:Null dataTemplate to bottom of DataTemplates List it works fine!

DataTemplates is a collection, priority goes in order of definition.

**Comment by maxkatz6** [comment]
Also, you can define a custom IDataTemplate and use it in ContentTemplate property of ContentControl.
See https://docs.avaloniaui.net/docs/templates/implement-idatatemplate
