### ISSUE TITLE
DevTools take snapshot while clicking

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#10402]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/10401

<div type='discussions-op-text'>

<sup>Originally posted by **mysteryx93** February 19, 2023</sup>
I have to debug some visual issues that appear in a mouse pressed state.

DevTools have a Snapshot feature, but I cannot click there while also clicking in my app. Also ALT+S shortcut isn't working while I'm clicking.

Is there a way that I can capture the bogus state so that I can then review it?</div>

I'll note that when pressing, F12 shortcut works, but ALT+S doesn't, so it looks like a limitation that could easily be fixed.

**Comment by maxkatz6** [comment]
Cannot reproduce anymore
