### ISSUE TITLE
Incorrect AVP1032 Warning: CLR property accessor accessibility does not match...

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#10418]
**Describe the bug**

I think AVP1032 should be adjusted to account for more modifiers on get/set.

![image](https://user-images.githubusercontent.com/17993847/220242815-ef1387ce-a9b6-482d-b304-75a13b9aee48.png)

This seems like a valid use-case to me for derived controls to still have access to this property. This could be debated as SetValue/SetCurrentValue can be used instead.

**Additional context**

**Comment by jp2masa** [comment]
I think what this warning means is that anyone can call `SetValue(ThirdComponentProperty, value)` (i.e. as if it was public), so it doesn't make much sense to have a protected setter.

**Comment by robloo** [comment]
Hm, yes, you are probably right. I've become accustomed to having the "clean" API in the CLR property while allowing a work-around with the SetValue() method for those that know what they are doing. That always seemed harmless to me. Perhaps that was a bad habit.

I guess this is a candidate for a read-only DirectProperty as was suggested by @maxkatz6 originally too.

**Comment by tomenscape** [comment]
Yes, this should be a read-only `DirectProperty`.
