### ISSUE TITLE
ItemsPresenter's panel shouldn't have the items as logical chidren

### ISSUE THREAD

**Issue by MrJul** [AvaloniaUI/Avalonia#10413]
Details
--

While investigating #10258, I found after a while (debugging recursive structures is always fun!) that the root cause of the problem is that the `Panel` created by an `ItemsPresenter` adds the items from its parent control as its own logical children.

When a `TemplatedControl` is being detached from the logical tree, `NotifyChildResourcesChanged` calls `NotifyResourcesChanged` on each one of its visual and logical children.

For an `ItemsControl`, the call trace of `NotifyResourcesChanged` looks like this:
 - From the visual tree of `ItemsControl`: `ItemsPresenter`
 - From the logical tree of `ItemsPresenter`: `StackPanel`
 - From the logical tree of `StackPanel`: *every item from the ItemsControl*
 - ... up the stack until we get back to `ItemsControl` ...
 - From the logical tree of `ItemsControl`: *every item from ItemsControl*

We can notice the items being processed twice. `TreeViewItem` being an `ItemsControl` itself, an item of depth `n` will get processed `n × ((n + 1) ÷ 2)` times. Considering all levels at once, the algorithm complexity is `O(2ⁿ)`. For a treeview with 18 nested items (1 item per level), this takes ≈0.8s on my machine, ≈1.6s for 19 items, etc. A depth of 75 should get us to the death of the sun, but I was getting a bit lazy here and didn't bother waiting.

Anyway, a simple solution for a complex problem: simply ensuring that the `StackPanel` doesn't add the items to its logical children is sufficient to get back to `O(n)` complexity. [That's what WPF does](https://github.com/dotnet/wpf/blob/be08c08b0cddfe075b8535ab7b3b591113d2f3c2/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Panel.cs#L158) when the panel is an items host. I'm planning to open a PR with this change.

Is that it? No, next I went down the rabbit hole. How was this situation possible at all? The items are obviously already logical children of the `ItemsControl`, they shouldn't be able to be added to another collection. When this happens, Avalonia [doesn't change the logical parent](https://github.com/AvaloniaUI/Avalonia/blob/3e3dbb1d3db98efe81cdcfcb18e0ab1c291c42ca/src/Avalonia.Base/StyledElement.cs#L951) but still allows the `ILogical` object to be the child of multiple parents. This results in an illogical (ahah) tree.

I've added some debug code to check whether this situation happens with other controls. I've seen `TabControl` stealing the `SelectedContent` even if it's already the owned child of an existing `TabItem`. `ContentPresenter.Content` appears to have some issues in nested template cases where it doesn't detect its host properly (I didn't investigate much yet), adding its parent `Content` a second time as a logical child.

Anyway, I think it's worth detecting these cases and throwing, at least in debug mode. Having the same node at several places in the tree likely won't cause general issues but is still incorrect, and might cause performance problems as demonstrated. I can at least add some unit tests for the common controls.

Next, I wondered about the whole `NotifyChildResourcesChanged` recursive calls when a control is detached from the logical tree. The start of this recursive call is [here](https://github.com/AvaloniaUI/Avalonia/blob/3e3dbb1d3db98efe81cdcfcb18e0ab1c291c42ca/src/Avalonia.Base/StyledElement.cs#L524). Notice that it isn't symmetric with the attached case. When an element is attached to the logical tree, `NotifyResourcesChanged` is [called without propagation](https://github.com/AvaloniaUI/Avalonia/blob/3e3dbb1d3db98efe81cdcfcb18e0ab1c291c42ca/src/Avalonia.Base/StyledElement.cs#L888) since we're already on a recursive path. When detached, I think the same logic can be used. It would avoid walking through the whole tree twice: once in `OnDetachedFromLogicalTreeCore` and once in `NotifyChildResources`. Quick changes don't show any issues, but this of course requires more testing.

Continuing the reasoning, I think there's the opportunity to potentially do nothing when detaching. There are cases when one might want to reset all resources that aren't accessible anymore after detaching. But isn't that the special case? For example, when detaching the old tree, it can't inherit the theme variant anymore: every single freshly detached control will reset back to its default resources.  This isn't theoretical: request a dark theme at the app level and notice (by debugging) every color and every brush of every detached control being reset to the light theme. This seems to be a bit wasteful: either it's never reattached or it has a high probability of being reattached to the same tree. `TemplatedControl` already optimizes for this scenario and will keep its applied template. (Note: I'm talking only about *resources* here; `DataContext` and bindings should be reset if their source isn't accessible anymore.)

Summary
--

1. I'll open a PR to fix the `ItemsControl` logical tree and associated performance.
2. Should we throw in debug if there's a logical child abduction?
3. Should we avoid the double tree walk by calling `NotifyChildResources(false)` in `OnDetachedFromLogicalTreeCore` (symmetry with attach)?
4. Can we avoid changing the resources when the tree is detached?

Depending on the discussion of points 2 to 4, I'm willing to open pull requests to change these behaviors and get feedback.

Pinging @grokys since he seems to be owning this area.

**Comment by rabbitism** [comment]
Maybe related to this https://github.com/AvaloniaUI/Avalonia/pull/10338

**Comment by grokys** [comment]
Thanks for investigating this @MrJul, however I'm not yet convinced that your diagnosis is the actual cause of the problem because in #10258 the submitter suggests that this issue started happening during in the 11.0 CI build timeline, and the stuff you're describing has been in place for a lot longer than that. The build signed out in that discussion is I think incorrect so I think the first thing to do is a `git bisect` to find where the problem reared its head.

> Anyway, a simple solution for a complex problem: simply ensuring that the StackPanel doesn't add the items to its logical children is sufficient to get back to O(n) complexity. 

I'm afraid that would probably break styling of `ItemsControl` items as in Avalonia, style selectors work on the logical tree. WPF doesn't have this problem, not having a CSS-like styling system.

> The items are obviously already logical children of the ItemsControl, they shouldn't be able to be added to another collection. When this happens, Avalonia [doesn't change the logical parent](https://github.com/AvaloniaUI/Avalonia/blob/3e3dbb1d3db98efe81cdcfcb18e0ab1c291c42ca/src/Avalonia.Base/StyledElement.cs#L951) but still allows the ILogical object to be the child of multiple parents.

This is actually perfectly normal (though surprising) and something I wrote about years back (2016!!): https://grokys.github.io/avalonia/logical-tree-weirdness/

**Comment by MrJul** [comment]
Thank you for the answer :)

Sorry, it's been a busy week, I didn't have time to open the PR I talked about yet (it needs some cleanup first).

Styling is still possible even if the items aren't logical children of the panel, as there should be no problem targeting an item through the parent `ItemsControl`. True, it will break styles that target something like `ListBox StackPanel ListBoxItem`. The fix is to target `ListBox ListBoxItem` instead which I personally find acceptable and even more natural (if the items couldn't be styled at all, that's would be a different story).

I didn't see that blog post before, thanks for sharing! Indeed, this is surprising. I'd expect to be able to walk through the entire logical tree, processing each item exactly once without having to keep a list of processed items.

As for the issue, the O(2ⁿ) complexity predates the `ItemsControl` refactor (and it's probably been this way for a long time, as you mentioned): it was simply faster before and thus less noticeable. On a003b90bffa3ebc8f58d9bfb00d5f20491814301 (the commit right before the new `ItemsControl` was merged), I need a depth of 23 to get the same ≈0.8s slowdown that I got on master with a depth of 17. It's still exponential though.

[Here's the gist](https://gist.github.com/MrJul/a85a5122aa23e0af8a2a8ab9b81a49f1) if you need a simple repro.

**Comment by grokys** [comment]
> The fix is to target ListBox ListBoxItem instead which I personally find acceptable and even more natural (if the items couldn't be styled at all, that's would be a different story).

True, that would be acceptable IMO.

> Indeed, this is surprising. I'd expect to be able to walk through the entire logical tree, processing each item exactly once without having to keep a list of processed items.

It's not just in this case where this happens, consider the following:

```
ContentControl
  |- ContentPresenter (in template)
       |- Button
```

In this case the `Button` is a logical child of the `ContentControl` but it's also a logical child of `ContentPresenter`.

> As for the issue, the O(2ⁿ) complexity predates the ItemsControl refactor (and it's probably been this way for a long time, as you mentioned): it was simply faster before and thus less noticeable. 

Ah ok, that makes sense.

**Comment by grokys** [comment]
>  I didn't have time to open the PR I talked about yet (it needs some cleanup first).

I'd be interested to see it, though I'm very wary about dropping such a change at this point. We were planning to do the final 11.0 RC within a month, and I fear that this could be quite a disruptive change...

@danwalmsley @MikeCodesDotNET @kekekeks would we want to accept a fundamental change in architecture for the sake of performance at this point?

**Comment by grokys** [comment]
> I think there's the opportunity to potentially do nothing when detaching. 

This would probably be a less potentially destabilizing change I think?

**Comment by MrJul** [comment]
> In this case the `Button` is a logical child of the `ContentControl` but it's also a logical child of `ContentPresenter`.

Unless I'm mistaken `ContentPresenter` has special handling of its `IContentPresenterHost`: in this case the presenter is only present in the visual tree, not the logical one. I believe that `ItemsPresenter` and its inner panel could use the same notion of "logically invisible presenter"?

> I'd be interested to see it, though I'm very wary about dropping such a change at this point. We were planning to do the final 11.0 RC within a month, and I fear that this could be quite a disruptive change...

The PR will be quite simple and can be reverted easily if necessary: basically if the panel is an items host, don't add its children to the logical tree. Since the items are still part of the logical tree through the parent `ItemsControl` it shouldn't cause problems, but I'm well aware that this kind of change should be well monitored for any unexpected side effect.

> @MrJul would you have time to be responsible any issues that came up due to this change before the 11.0 release? We may not have the bandwidth.

I should have the time to take care of any issues happening in the next few weeks and can take responsibility.

> This would probably be a less potentially destabilizing change I think? Though I'd worry about it causing leaks.

This at least made one test fail (I don't remember its name off the top of my head) that specially checked for resource changes when detaching. Leaking is indeed the main potential problem here: it's "just" resources, but you never know what kind of resources people have stored and used.
