### ISSUE TITLE
OpenFileDialog.ShowAsync exception OSX

### ISSUE THREAD

**Issue by azecom-com** [AvaloniaUI/Avalonia#1043]
OpenFileDialog throws safehandle exception on dotnetcore1.1/OSX, avalonia 0.5.1

**Comment by kekekeks** [comment]
It's a known issue, you have to pass a window instance as an argument.

**Comment by azecom-com** [comment]
I tried it, but still not working when i pass "this" instance.  Have you example that works fine?

**Comment by kekekeks** [comment]
It seems to also be happening when `Title` is null.

Should be fixed by these commits:

https://github.com/AvaloniaUI/Avalonia/commit/6ea0635c7faa33a01816a5835ade423d6fb9e058
https://github.com/AvaloniaUI/Avalonia/commit/85f29305572917202ac75df7b1e058347a0308a5

**Comment by danwalmsley** [comment]
I can confirm this is now fixed. closing.
