### ISSUE TITLE
MouseDevice uses initial buttons for an unrelated mouse up event

### ISSUE THREAD

**Issue by YohDeadfall** [AvaloniaUI/Avalonia#10434]
**Describe the bug**

Each `WindowImpl` owns a personal instance of `MouseDevice` which tracks buttons used last time by a key down event, but if there's another overlapping window opens and closes immediately on a mouse down even, the follow up mouse up will be raised on the background window with old and unrelated initial buttons.

**To Reproduce**

1. Make an app which has a context menu for the main window.
2. In that context menu add an entry which opens a system open file dialog.
3. Ensure that the file you want to double click on is over the main window.
4. Double click on the file and see the context menu being opened.

**Expected behavior**

The context menu must not be displayed.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version 10.0.22000.0

**Comment by timunie** [comment]
@YohDeadfall which Version of Avalonia do you use?

**Comment by YohDeadfall** [comment]
There's no exact version because we have a fork from which build packages to keep everything up to date and have broken things fixed ASAP. What I can tell you is that the bug was the for a long time according to our app builds I tested.

@MarchingCube, I made a pull request to fix the bug.
