### ISSUE TITLE
Problems with av_libglesv2.dll

### ISSUE THREAD

**Issue by sekkit** [AvaloniaUI/Avalonia#10441]
Use preview-5 with av_libglesv2.dll, together with options set below
ExtendClientAreaToDecorationsHint="True"
ExtendClientAreaChromeHints="NoChrome"  
ExtendClientAreaTitleBarHeightHint="40"  
 will result in no DropShadow window.

**Comment by maxkatz6** [comment]
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/9989
