### ISSUE TITLE
DevTools: Tree not scrolling to selected element (when selecting via Ctrl+Shift)

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#10449]
**Describe the bug**
Seems that the tree view inside DevTools doesn't scroll to selected elements anymore

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.11

**Additional context**

**Comment by LegendTheDeveloper** [comment]
Hello, I want to reopen this issue, this is related with the new developer tools from accelerate (Now we have to use CTRL + SHIFT + C or K)

It just doesn't work. I won't select the element in the hierarchy in the latest version.
