### ISSUE TITLE
Allow for hooking into WndProc on windows

### ISSUE THREAD

**Issue by sanjay900** [AvaloniaUI/Avalonia#10447]
**Is your feature request related to a problem? Please describe.**
I would like to listen to USB device hotplug events on windows, and doing this requires listening for WM_DEVICECHANGE. It would be nice to have some sort of device detection event built into avalonia, but I understand that would probably be out of scope, so some way to hook into WndProc would be enough.

**Describe the solution you'd like**
I would like to be able to add my own hooks that get called whenever WndProc is called, so I can listen for these events.

**Describe alternatives you've considered**
An alternative would be for avalonia to build in some sort of cross platform USB device handling including hotplug events but that would probably be a large undertaking.

I also was able to get something working by just manually using p/invoke to create a hidden window and listen to it's events but this is quite messy and it would be preferable to have something built into avalonia for this instead.

**Comment by maxkatz6** [comment]
WinAPI already supports it with SetWindowLong/GetWindowLong
https://github.com/AvaloniaUI/Avalonia/discussions/8650

**Comment by sanjay900** [comment]
Thanks for that, got it working
