### ISSUE TITLE
TextBlock inside tooltip doesn't wrap long lines in v11

### ISSUE THREAD

**Issue by rfvgyhn** [AvaloniaUI/Avalonia#10452]
A TextBlock inside a ToolTip doesn't wrap long lines.

```xaml
<ItemsControl.ItemTemplate>
    <DataTemplate DataType="m:MissableInfo">
        <Border CornerRadius="3" Background="{DynamicResource ThemeAccentBrush4}" Padding="4" Margin="0 4 4 0">
            <ToolTip.Tip>
                <StackPanel MaxWidth="300">
                    <TextBlock Text="{Binding QuestName}" VerticalAlignment="Center" FontWeight="Bold" />
                    <ItemsControl Items="{Binding Notes}">
                        <ItemsControl.ItemTemplate>
                            <DataTemplate DataType="s:Array">
                                <TextBlock TextWrapping="Wrap" Text="{Binding ., StringFormat='* {0}'}" Margin="0 10 0 0" />
                            </DataTemplate>
                        </ItemsControl.ItemTemplate>
                    </ItemsControl>
                </StackPanel>
            </ToolTip.Tip>
            <StackPanel>
                <!-- Snip -->
            </StackPanel>
        </Border>
    </DataTemplate>
</ItemsControl.ItemTemplate>
```

- OS: Arch linux 6.1.12-arch1-1, Windows 10
- Version: 11 preview 5

In the dev tools, if I set `ToolTip.IsOpen` to true, inspect the text block in the visual tree, the `TextBlock.TextWrapping` property is set to `NoWrap`. I don't know if that's part of the issue, or just a product of viewing it via the inspector. Manually setting it to `Wrap` though causes the text to be properly wrapped.

**Comment by maxkatz6** [comment]
Not sure if I understand issue. By default, text wrapping is NoWrap. So you had expected behavior, and you solved it by setting property to Wrap.

To compare with simple tooltips (i.e. ToolTip.Tip="Simple text"), they have Wrap set for conveniency, as it's normal for text tooltips to have max width and wrap to avoid extra-long lines. While you have tooltip with a custom content, you decide how it wraps.

**Comment by rfvgyhn** [comment]
The second `TextBlock` inside the tooltip's custom content has `Wrap` specified yet it isn't being wrapped.

`<TextBlock TextWrapping="Wrap" Text="{Binding ., StringFormat='* {0}'}" Margin="0 10 0 0" />`

**Comment by rfvgyhn** [comment]
It looks like it has something to do with it being in an `ItemPresenter`. Setting the first `TextBlock` to wrap properly wraps. It seems as though multiple things are broken when inside an `ItemPresenter`. The `StringFormat` isn't applied either.

Here's a before and after with v9.3 vs v11-preview5:

v9.3
![v9 3](https://user-images.githubusercontent.com/731861/221112824-856f0668-c95e-4266-9150-eb906b27b314.png)

v11-preview5
![v11-preview5](https://user-images.githubusercontent.com/731861/221112871-97b1fbf3-ee0d-48b1-a5d2-3f7ae60bc755.png)

**Comment by maxkatz6** [comment]
So, it's a different issue. Nothing to do with wrapping, but whole template isn't applied.

Are you sure that "<DataTemplate DataType="s:Array">" is correct? Specifically DataType. It seems like you have array of strings, but you set data type of each item as an array.

**Comment by rfvgyhn** [comment]
🤦 Yep, it should be a string and not an array. Looks like it was my bug. Thanks for spotting that.
