### ISSUE TITLE
ComboBox drop down list cannot be opened by clicking the button when using the Simple theme (11.0.0-preview5)

### ISSUE THREAD

**Issue by megazyz** [AvaloniaUI/Avalonia#10453]
**Describe the bug**
When using the Simple theme, clicking the drop down button of a ComboBox opens the drop down list, but immediately closes it.
It works as expected when the content area is being clicked instead of the drop down button.
The issue does not occur when using the Fluent theme.

It worked fine in 11.0.0-preview4, the issue appeared in 11.0.0-preview5.

**To Reproduce**

1. Create a new Avalonia application using the template
2. Update Avalonia packages to 11.0.0-preview5
3. Change the theme from Fluent to Simple in App.axaml
4. Add a ComboBox to the main window with some ComboBoxItems
5. Run the application and click on the drop down button to see the issue

**Expected behavior**
The drop down list should be openable by clicking on the drop down button.

**Desktop:**
- OS: Windows 11
- Version: 11.0.0-preview5

**Comment by maxkatz6** [comment]
Possibly the same problem as here https://github.com/AvaloniaUI/Avalonia/issues/10420
And will be fixed by https://github.com/AvaloniaUI/Avalonia/pull/10448

**Comment by megazyz** [comment]
I confirm that #10448 fixed this and it works as expected in 11.0.999-cibuild0031642-beta.
