### ISSUE TITLE
NumericUpDown has value of 0 when text is deleted

### ISSUE THREAD

**Issue by sonicsmooth** [AvaloniaUI/Avalonia#10469]
**Describe the bug**
When a minimum value is set in `NumericUpDown`, and the text is deleted by the user, the control's `Value` is 0.  The control should probably behave as when attempting to set a value outside its min and max range, which means the property should not be set at all.

**To Reproduce**

    <NumericUpDown
       Value="{Binding myproperty}"
       Minimum="2"
       Maximum="12"/>

Set a breakpoint in `myproperty` setter.
Delete the initial value so the text box is blank.
The breakpoint will show `value`=0.  
![image](https://user-images.githubusercontent.com/672429/221277263-130a6316-ef28-46ba-a7d9-51d5721dbcc4.png)

**Expected behavior**
Proper behavior should be that the property change is not attempted, same as when you type in a number out of range, such as 1 in this case.

**Screenshots**
Here the user has deleted the text
![image](https://user-images.githubusercontent.com/672429/221276521-6c88b67c-1cd0-4256-87d1-a1e1b18fa393.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10
- Version [e.g. 11 preview 4

**Additional context**

**Comment by maxkatz6** [comment]
I believe expected value is a default value here. 
That's why you should set property to nullable int.

**Comment by amwx** [comment]
FWIW, WinUI's NumberBox requires an explicit commit (either lose focus or hit enter key) for the text to be processed and update the value. I wonder if that behavior should be copied or add a property to control it for cases like this?

**Comment by timunie** [comment]
> FWIW, WinUI's NumberBox requires an explicit commit (either lose focus or hit enter key) for the text to be processed and update the value. I wonder if that behavior should be copied or add a property to control it for cases like this?

I think this is a great example for a property where `UpdateSourceTrigger` would be very useful. See #7797 and https://github.com/AvaloniaUI/Avalonia/issues/3754
