### ISSUE TITLE
Canvas does not work within VisualBrush

### ISSUE THREAD

**Issue by joesunley** [AvaloniaUI/Avalonia#10479]
**Describe the bug**
Nothing is displayed when using a Canvas as the Visual Property for a VisualBrush. When using other controls such as Grid it works as intended.

**To Reproduce**

```xaml
<Path Stroke="Black" StrokeThickness="1">
  <Path.Data>
    <EllipseGeometry RadiusX="300" RadiusY="300" Center="500,400" />
  <Path.Data>
  <Path.Fill>
    <VisualBrush TileMode="None">
      <VisualBrush.Visual>
        <Canvas>
          <Rectange Fill="Red" Width="300" Height="300" />
        </Canvas>
      </VisualBrush.Visual>
    </VisualBrush>
  </Path.Fill>
</Path>
```
Using the above xaml results in just an ellipse with a black border.

**Expected behavior**
An ellipse with size (300, 300) should be visible with a black border and a Red background should appear.

**Screenshots**
Expected results (achieved using Grid):
![Bug_withGrid](https://user-images.githubusercontent.com/57263040/221367611-ffd9678e-5beb-41ce-bfbd-73042340aff8.png)

Actual results (when using Canvas):
![Bug_withCanvas](https://user-images.githubusercontent.com/57263040/221367623-bc35c8fd-95db-4f30-9909-350548b4df15.png)

**Desktop:**

- Windows 11 22621
- Windows 11 Insider Preview 22623

**Additional context**
It's not only when using a rectangle as the background, when trying to add more complex objects using Canvas specific properties it also does not work.

**Comment by maxkatz6** [comment]
I think it is expected here. Canvas won't be resized depending on its children. I.e., canvas always returns size of its parent (none, in current context). So, you have to define width/height on it directly.

Grid, on other hand, does resize depending on its children and how row/column definitions are set.

**Comment by kekekeks** [comment]
Set the _Canvas_ size to 300x300 as well. I'm not sure why, but our VisualBrush drawing code uses the dimensions of the root visual rather than content dimensions.

**Comment by joesunley** [comment]
Yeah that works, thanks for the help
