### ISSUE TITLE
Latest beta, Avalonia.Xaml.Interactions not found

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#10482]
Using the nightly build

    <PackageReference Include="Avalonia.Xaml.Interactions" Version="11.0.999-cibuild0030643-beta" />
    <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.0.999-cibuild0030643-beta" />

`Avalonia.Xaml` namespace is not found.

Thus I can't find EventTriggerBehavior

    GC.KeepAlive(typeof(EventTriggerBehavior));

**Comment by mysteryx93** [comment]
ah I also get this compile error

```
  Common.Avalonia.App.csproj: [NU1102] Unable to find package Avalonia.Xaml.Interactions with version (>= 11.0.999-cibuild0030643-beta)
  - Found 96 version(s) in nuget.org [ Nearest version: 11.0.0-preview5 ]
  - Found 0 version(s) in Avalonia
```

Does `Avalonia.Xaml.Interactions` simply not support the beta?

**Comment by timunie** [comment]
@mysteryx93 it has it's own nightly builds feed. Check out the Behaviors GitHub repo. If it's compatible with actual nightly, I don't know.

**Comment by maxkatz6** [comment]
It's not Avalonia issue. Please open an issue in behaviors repository.

**Comment by mysteryx93** [comment]
Added the other feed, it works now.
