### ISSUE TITLE
Publish/Trimming Template Project

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#10483]
I'm trying to publish/trim the template project. Using the latest nightly build.

Publish command on `Avalonia11.Desktop` throws

> The target "Avalonia11:Restore" does not exist in the project.

**Comment by mysteryx93** [comment]
I'm noting more trimming problems with .NET 7 and Avalonia11.

    <Slider Value="{Binding Settings.Encode.QualityOrSpeed}">

Application binding is throwing

    System.MissingMemberException: Could not find a matching property accessor for 'QualityOrSpeed' on 'Hanuman.BassAudio.EncodeSettings'

My build command

    dotnet publish -r linux-x64 -c Release --self-contained true -p:DebugSymbols=false -p:PublishSingleFile=false -p:PublishTrimmed=true -p:TrimMode=copyused -o "bin/AppImages/AppDir/usr/bin"

**Comment by maxkatz6** [comment]
> Publish command on Avalonia11.Desktop throws
> The target "Avalonia11:Restore" does not exist in the project.

It doesn't look like Avalonia issue.

> I'm noting more trimming problems with .NET 7 and Avalonia11.

Are you using CompiledBindings? Either set `<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>` in csproj or x:CompiledBindings="true" in each file.
0.10 documentation, since then almost all of the limitations were removed - https://docs.avaloniaui.net/docs/data-binding/compiledbindings
But you still need to specify x:DataType.
Otherwise, there is no type safety, which means no trimming safety.

**Comment by maxkatz6** [comment]
>  -p:TrimMode=copyused

I think "copyused" is no-op in .NET 7. And it always will do member-level trimming. You can use "partial" instead though, but Avalonia supports fully trimmed applications or fully AOT, if user code is safe too (i.e., no reflection bindings).

**Comment by mysteryx93** [comment]
> It doesn't look like Avalonia issue.

Could it be an issue with the template?

Converting bindings to compile bindings, I have an error here

    Command="{Binding ViewModel.ShowAbout, RelativeSource={RelativeSource AncestorType={x:Type Window}}}"

> MainView.axaml(93, 33): [AVLN:0004] AncestorType must be set for RelativeSourceMode.FindAncestor when searching the visual tree. Line 93, position 33.

**Comment by maxkatz6** [comment]
> Could it be an issue with the template?

Not sure, it worked just yesterday.

> AncestorType must be set for RelativeSourceMode.FindAncestor when searching the visual tree. Line 93, position 33.

1. Window doesn't have ViewModel property.
2. Can you try `"{Binding $parent[views:YourWindowType].ViewModel.ShowAbout|"`? I guess we don't have enough unit tests for this old full RelativeSource syntax.

**Comment by mysteryx93** [comment]
That works.

Now it gives compile-time error at each ComboBox binding. It's bound to a custom CollectionView class.

    <ComboBox HorizontalAlignment="Right" Width="120" 
    Items="{Binding FormatsList}" SelectedItem="{Binding FormatsList.CurrentItem}">

```
  MainView.axaml(99, 65): [AVLN:0004] Internal compiler error while emitting node Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.XamlIlBindingPathHelper+XamlIlBindingPathNode:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Cecil.ImportGenericContext.TypeParameter(String type, Int32 position)
   at Mono.Cecil.DefaultMetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
   at Mono.Cecil.DefaultMetadataImporter.ImportType(TypeReference type, ImportGenericContext context)
   at Mono.Cecil.DefaultMetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
```

**Comment by mysteryx93** [comment]
Created a repo and posted a separate issue here
https://github.com/AvaloniaUI/Avalonia/issues/10485

**Comment by maxkatz6** [comment]
Thanks, I will close this one then
