### ISSUE TITLE
How to bind command to loaded event?

### ISSUE THREAD

**Issue by MonkAlex** [AvaloniaUI/Avalonia#1049]
Has Avalonia any api similar with [this](https://stackoverflow.com/a/17933290/3768545)?

**Comment by wieslawsoltes** [comment]
Yes. https://github.com/wieslawsoltes/AvaloniaBehaviors

**Comment by Slesa** [comment]
Is there a way to find the possible events? Loaded seems not to exist, but the Click-Example works.

**Comment by vflame** [comment]
Events:

http://avaloniaui.net/api/Avalonia.Controls/Window/

You can try the Opened or Initialized events. Both work.

**Comment by M0rdecay** [comment]
At what point does the `Initialized` event fire? Maybe I'm doing something wrong, the method attached to this event never works.

**Comment by Casper-SC** [comment]
> At what point does the `Initialized` event fire? Maybe I'm doing something wrong, the method attached to this event is never executed.

`    public class MainWindow : Window
    {
        public MainWindow()
        {
            Initialized += OnInitialized;

            InitializeComponent();
#if DEBUG
            this.AttachDevTools();
#endif
        }

        private void OnInitialized(object sender, System.EventArgs e)
        {
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }`

**Comment by maxkatz6** [comment]
AttachedToVisualTree event is equivalent or WPF Loaded event

**Comment by AstralisSomnium** [comment]
For me also only `Opened` worked.
AttachedToVisualTree and Initialized  didn't work.

I hooked up after `InitializeComponent();`.

Any recommendations?

**Comment by maxkatz6** [comment]
@AstralisSomnium  What do you mean by "didn't work"? Event wasn't called?
AttachedToVisualTree is always called for controls that attached to visual tree, but for window it Is never called if I remember, because it doesn't attach to any visual or logical tree of elements. 
For windows you need to use Opened.
