### ISSUE TITLE
CompiledBinding unable to bind to base class in different assembly

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#10494]
As a separate issue from [this](https://github.com/AvaloniaUI/Avalonia/issues/10485), here's another problem.

I created a repo project.
[CompileBindingSample.zip](https://github.com/AvaloniaUI/Avalonia/files/10835115/CompileBindingSample.zip)

Open it and it runs fine.

Open `Converter432hz.csproj` and uncomment `<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>`

Compile and you get this error

>  Member 'System.Version' is declared in another module and needs to be imported

Compile again and you get this error (I removed ReactiveUI.Fody from the project to exclude that)

>  Format of the executable (.exe) or library (.dll) is invalid.

Using the latest nightly build on Linux.

**Comment by mysteryx93** [comment]
I completely stripped down the sample down to this, and it crashes.

    <Button Classes="round" Width="110" HorizontalAlignment="Center" Margin="0,5"
        Command="{Binding ShowSettings}" Content="Advanced" />

[CompileBindingSample.zip](https://github.com/AvaloniaUI/Avalonia/files/10835931/CompileBindingSample.zip)

So... why doesn't it like ShowSettings? What's so special about it?

It's defined in a base class. Morever, that base class is in a separate assembly. If I move the base class into the same assembly, then it works.

**Comment by timunie** [comment]
Doesn't crash on Windows for me. I tried the sample attached to the second comment.

**Comment by mysteryx93** [comment]
I made a mistake before submitting the sample. Move `MainViewModelBase` file into `Common.Avalonia.App/Common/` and you'll get the error. Reproduced in Windows.

**Comment by timunie** [comment]
Yes then I can reproduce. But for me the error message is pointing to ReactiveCommand.

**Comment by maxkatz6** [comment]
@mysteryx93 hi. Do you still have this issue in 11.1 builds?

**Comment by mysteryx93** [comment]
I just tested and it works.

**Comment by timunie** [comment]
In that case let's close this issue now.
