### ISSUE TITLE
Sandbox not running : Avalonia.Fonts.Inter missing

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#10507]
Seems that on latest master Sandbox project is not running anymore:

> Could not load file or assembly Avalonia.Fonts.Inter

I tried cleaning the solution and rebuilding everything, but the only thing that fixed it is adding a reference to `Avalonia.Fonts.Inter.csproj` in Sandbox

**Comment by mysteryx93** [comment]
I'm also having this error when running the latest nightly build

**Comment by timunie** [comment]
It's a known issue. For now either add the needed font via nuget or define your own Font

**Comment by maxkatz6** [comment]
Should be fixed by https://github.com/AvaloniaUI/Avalonia/pull/10496?notification_referrer_id=NT_kwDOADBE7rI1NzEyOTgwMzg4OjMxNjMzNzQ#issuecomment-1448612635
