### ISSUE TITLE
ListBox is leaking memory in preview5 (and not in preview4)

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#10509]
**Describe the bug**
`ListBox` objects are not GC'd from memory.

**To Reproduce**
Execute the following NUnit test:

```csharp
        [Test]
        public void TestListBoxLeak()
        {
            static void CreateForLeakTest<T>(
                Func<T> construct, out T value, out WeakReference reference)
            {
                value = construct();
                reference = new WeakReference(value);
            }
           
            // Arrange
            CreateForLeakTest(
                () =>
                {
                    ListBox result = new ListBox();
                    result.Items = null;
                    return result;
                },
                out ListBox listBox,
                out WeakReference reference);

            // Act
            listBox = null; // release the reference
            GC.Collect(); // ensure a GC pass
            GC.WaitForPendingFinalizers();

            // Assert
            Assert.IsFalse(reference.IsAlive, "ListBox was not released");
        }
```
**Expected behavior**
The test doesn't fail. Note that the test **passes OK in preview4** (11.0.0-preview4-cibuild0029143-beta)

**Desktop (please complete the following information):**
- OS: Windows/Mac/Linux.
- Version preview5 (11.0.999-cibuild0030125-beta)

**Additional context**
- The test passes OK in preview 4, so **it seems to be a regression in preview 5**.
- Commenting out the line ` result.Items = null;` **makes the test pass**. So it seems that the leak is caused somehow by assigning the items in the `ListBox`.

**Open question about the existing leak unit test**
Question: Are the Leak tests passing ok in your CI build? I'm asking because I noticed that [there is a test](https://github.com/AvaloniaUI/Avalonia/blob/033c1e29ce83ff1aba878d027ab892453c5bc364/tests/Avalonia.LeakTests/ControlTests.cs#L713) that already creates a `ListBox`. So I guess this leak should be detected but it was not. 

I tried to pass the `Avalonia.LeakTests` but for me, they all pass green due to the attribute `[DotMemoryUnit(FailIfRunWithoutSupport = false)]` (this attribute avoids the tests to fail if the tests are run without the support for dotMemory). So I just wanted to double-check with you these tests are effectively passed in the CI builds. CCing/ @grokys since you seem to own those tests.

**Comment by grokys** [comment]
The test here now passes in #10590 - looks like I fixed it as a side-effect of that work!

**Comment by danipen** [comment]
That's awesome!
