### ISSUE TITLE
Resources used in UserControl Code-Behind Won't Apply ThemeVariant

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#10502]
**Describe the bug**

There is a control that, for generics/inheritance reasons, is constructed in code behind. However, when resolving resources it won't pick up the correct ones.

 1. I'm using FluentAvalonia and know the control themes are loaded. However, it won't apply them.
 2. Light theme variant works OK (I expect because it is default) however dark theme variant resources do NOT apply properly leaving a semi-corrupted light theme variant.

**To Reproduce**

I'm hoping someone else will run across this too and have a more direct repro. The situation occurs in a base UserControl that initializes its own content in code-behind. During that initialization it is looking up resources. The base UserControl is then inherited by several other UserControl views.

**Expected behavior**

Application.Resources.TryGetResource() should correctly resolve light/dark theme variant resources in all stages of the application lifecycle.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0-preview5 @11.0.999-cibuild0030643-beta

**Additional context**

**Comment by maxkatz6** [comment]
> Application.Resources.TryGetResource() should correctly resolve light/dark theme variant resources in all stages of the application lifecycle.

It's static. Also, you need to pass a theme variant as a parameter there. 
We could fall back to the application global theme, but it won't be a good practice, if theme variant is overridden in between the tree.

Where can I find code where this control is constructed?

**Comment by robloo** [comment]
I wish it was something I could easily pull out and share with you but it isn't. This is also an unfortunate time of the year and I've had little free time the last few months. So I don't think I can spend the time to create a minimal repro for this.

However, there is a chance it is directly related to https://github.com/AvaloniaUI/Avalonia/issues/10292#issuecomment-1447545321. It is quite similar in some ways. That one is reproducible and FluentAvalonia is very easy to get building.

The application resource lookup is done with a helper extension method to make it more similar to WPF/UWP:

```csharp
        public static T GetResource<T>(
            this Application app,
            object key)
        {
            if (app.Resources.TryGetResource(key, app.ActualThemeVariant, out object resource))
            {
                if (resource is T)
                {
                    return (T)resource;
                }
            }
#if DEBUG
            //throw new Exception("Missing resource: " + key?.ToString());
#endif
            return default(T);
        }
```

FWIW I'm also getting random failures to resolve resources I know are there in other parts of the application. Not sure how to file an issue for that one yet though.

**Comment by maxkatz6** [comment]
@robloo @amwx is this problem still reproducible in the preview7?

**Comment by robloo** [comment]
@maxkatz6 Yes, it's still an issue with preview 7. I think the resource lookup issue is actually more complex than discussed here and there are more cases.

The other publicly reproducible problem is in Fluent Avalonia: https://github.com/amwx/FluentAvalonia/issues/314. This is similar where it just isn't finding/applying resources (and entire theme variants) in some cases. The ColorPicker's popup Components tab is the worst offender (but it also might have a little to do with the visibility issue https://github.com/AvaloniaUI/Avalonia/pull/11127).

**Comment by amwx** [comment]
@robloo At least for the ColorPicker, it's the StaticResources that are inside the DropDownButton for the ColorPicker:
https://github.com/amwx/FluentAvalonia/blob/ead724348817b2d61613a3eba1485d3c563795da/src/FluentAvalonia/Styling/ControlThemes/BasicControls/ColorPicker/ColorPicker.axaml#L60-L67

It looks like they were removed from Avalonia fluent theme, but haven't been removed in FA yet. Removed them and it displays correctly:
![image](https://user-images.githubusercontent.com/40413319/234413469-25f893eb-88c3-4737-ab7c-0dc29ecc74cb.png)

**Comment by robloo** [comment]
@amwx Thanks as always for taking a look at this. Concerning these resources in ColorPicker. My understanding is that when one is aliasing an existing ResourceKey you must use StaticResource -- it will work correctly with theme changes. At least that is what I have seen done several other places. However, it seems these resources are NOT being found/applied.

```xaml
<Grid.Resources>
  <StaticResource x:Key="ColorViewContentBackgroundBrush" ResourceKey="LayerFillColorAltBrush" />
  <StaticResource x:Key="ColorViewContentBorderBrush" ResourceKey="DividerStrokeColorDefaultBrush" />
  <SolidColorBrush x:Key="ColorViewTabBackgroundBrush" Color="Transparent" />
  <SolidColorBrush x:Key="ColorViewTabBorderBrush" Color="Transparent" />
  <!-- This radius must follow OverlayCornerRadius -->
  <CornerRadius x:Key="ColorViewTabBackgroundCornerRadius">8,8,0,0</CornerRadius>
</Grid.Resources>
```

Concerning the existence of the resources themselves, I double checked and it is correct that these are re-defined for Fluent v2. Fluent V2 content areas use those two brushes. Any top/bottom area is left transparent. This is different than Fluent v1 and also what is done in the ColorView.

![image](https://user-images.githubusercontent.com/17993847/234439808-a89c6f90-114f-4adc-9da9-d68ee88de534.png)

**Comment by robloo** [comment]
@maxkatz6 So maybe this is the one problem with the ColorPicker:

```xaml
<StaticResource x:Key="ColorViewContentBackgroundBrush" ResourceKey="LayerFillColorAltBrush" />
<StaticResource x:Key="ColorViewContentBorderBrush" ResourceKey="DividerStrokeColorDefaultBrush" />
```

Is pulling in the default white theme variant resources and it's why it is setting a white background first. Because these are not dynamic, they are never re-evaluated for dark theme variant changes so always stay white.

However, changing the XAML to:

```xaml
<DynamicResource x:Key="ColorViewContentBackgroundBrush" ResourceKey="LayerFillColorAltBrush" />
<DynamicResource x:Key="ColorViewContentBorderBrush" ResourceKey="DividerStrokeColorDefaultBrush" />
```

Then doesn't find the light or dark resources and just returns null. No resources are found. I seem to recall an old discussion about perhaps this case not being supported? Resource aliasing with DynamicResource instead of StaticResource?

**Comment by amwx** [comment]
`StaticResource` aliases don't do a lookup with the theme context (or they do it with the current one), so it only really works if the resource its aliasing is in the same theme dictionary. If you want to redefine it elsewhere, you have to do it with theme dictionaries again so the context is correct during the lookup. See the [`NumberBox` template in WinUI](https://github.com/microsoft/microsoft-ui-xaml/blob/c8d3b4ad5655d7eda9045e8a5d273cfb855a2ee1/dev/NumberBox/NumberBox.xaml#L74) where they redefine the RepeatButton resources.

**Comment by maxkatz6** [comment]
That's right.
When you put StaticResource into resource dictionary, it will lookup the referenced resource once and won't update it, will use default theme.
If it's defined in the ThemeDictionary, it will lookup once with the same theme as current resource dictionary (new behavior in preview7, same behavior as in UWP). Meaning, if you want theme-aware resources, it must be defined inside of the ThemeDictionary (duplicated or reused with ResourceInclude, but I didn't test the last one, should work in theory).

DynamicResource is simply not supported as resource value. Not before, not now, not even in WPF, not even in UWP with their ThemeResource (as far as I remember). DynamicResource returns a binding, and resource dictionaries do not support bindings as values in all XAML frameworks (though, I kinda wish they could).
It doesn't produce an error, as technically you can save detached binding in the resources, but that's it.

**Comment by robloo** [comment]
@amwx thanks, it would have taken me a while to figure that out and the example is perfect. It does make sense this is needed.

Part of me also thinks DynamicResource on an aliased resource that itself is within theme variants should be able to support this itself though.

**Comment by robloo** [comment]
@maxkatz6 Thanks for the details as well. Using a theme dictionary will work fine. I'm glad that option is supported now for cased like this.

**Comment by robloo** [comment]
The ColorPicker Fluent v2 issue is fixed by inserting a new theme dictionary in the grid resources as discussed above. Thanks for this fix.

With this in mind I'll take another more careful look at the original issue and see if it is somehow related.

**Comment by robloo** [comment]
I'm closing this as fixed now.

 1. Some of the older Avalonia styling system bugs have been fixed
 2. The colorpicker case required thinking about it a different way as discussed above but it works
 3. FluentAvalonia resources have to be retrieved specially at the moment

Bottom line: I think I have figured out all issues now and things work as intended for Avalonia as best as I can tell.
