### ISSUE TITLE
No window rendering since version 11

### ISSUE THREAD

**Issue by pazof** [AvaloniaUI/Avalonia#10526]
Trying and passe to versions 11 for `Avalonia`,
without template, I had to remove the App Style setup (`FulentTheme` not being ported),
the App launches, but only window decorations are visible. 

1. choose any Avalonia 11.* App to check under Debian 
4. See the transparent window rendering, instead of your app

**Expected behavior**
The hello `Avalonia 11.x` window under Debian

**Screenshots**
TODO

- OS: Debian 11 x64
- Version 11.*

**Additional context**
TODO : find an example to build from the HEAD of the main branch (I've got to submit and close my session)

**Comment by maxkatz6** [comment]
FluentTheme needs to be included. Or any alternative theme.
See https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#avaloniathemesfluent-and-simple

**Comment by pazof** [comment]
sorry, a bad click certainly ...

**Comment by pazof** [comment]
thanks a lot!
