### ISSUE TITLE
ControlCatalog: Side-menu toggling breaks after a page is opened

### ISSUE THREAD

**Issue by warappa** [AvaloniaUI/Avalonia#10537]
### Describe the bug
In the ControlCatalog, if you open the previously collapsed side-menu and select an menu item, you cannot re-open the collapsed side-menu again.

### To Reproduce

1. Open ControlCatalog (Windows, Android,...)
2. Reduce the width of the Window until the **left side-menu collapses/hides** (important!)
3. Click the Hamburger button multiple times - the side-menu **shows and hides as expected**
4. Now, **open a menu item** like "Calendar"
5. Try to open the side-menu again
6. The side-menu **does not open anymore** - **you have to restart the app to select another page**

### Expected behavior
The side-menu should always open/close.

### Desktop (please complete the following information):
- OS: Windows 11 22H2 (22621.1344)
- Version:  
  - Works on 11 Preview 5,
  - Broken on current Master branch (92562b0d9979becc8d8c2316e1c2f0678bdae19d)

### Investigation
The `SplitView`'s `IsPaneOpen` is bound by the Hamburger button.

`SplitView.CoerceIsPaneOpen` should always get triggered when the Hamburger button (`ToggleButton`) gets clicked. When it works, it is called for `true` and `false`. As soon as its broken, it's **only** called when the value is `true`.

Wild guess: As the side-menu already closes as soon as the menu-item is pressed (not released!), it seems as the mouse is captured in a weird way by the menu item or something.

#### Guilty Commit
80394d0097c4acc9b3b74024a863b97774c35d3e (but I think it's an unhider as this changes `IsPaneOpen` from `DirectProperty` to `StyledProperty`)

Maybe some issue with `StyledProperty`?

**Comment by robloo** [comment]
I had the same thought as your analysis when I read this: Could be a side effect in SplitView of switching to StyledProperty.

The thing is, https://github.com/AvaloniaUI/Avalonia/pull/10497 was supposed to fix the known issues. So it seems there is something else here.

**Comment by warappa** [comment]
### LastValue
(As far as I remember my debugging adventure)
What I also noticed is that when it works, `SettableNode`/`ExpressionNode`'s `LastValue` gets updated, afterwards it stays `false` (aka. no update). There is only 1 place where this gets updated, but this all of a sudden won't get called anymore.

`SettableNode.ShouldNotSet` gets invoked on every interaction, but as it's using `LastValue` to determine if it should be processed further, it skips the further processing.

### Guess: Default Value Handling?
`false` is the default value for this `StyledProperty`, so it could be  related to **default-value-handling** of `StyledProperty`.

**Comment by amwx** [comment]
In case it was the same as #10655, I had a look, and the issue here is:
https://github.com/AvaloniaUI/Avalonia/blob/cbe0bb861a767b7bf7b268bbaa1d89dcf8523aea/samples/SampleControls/HamburgerMenu/HamburgerMenu.cs#L56-L62

Selecting an item with the SplitView display mode in `Overlay` results in setting `IsPaneOpen` to `false` with Animation priority - which is never reset so the pane can never be reopened as the `HamburgerMenuButton` ToggleButton in the template is two-way bound to the SplitView

**Comment by warappa** [comment]
@amwx Thank you, that's the issue!
Using `BindingPriority.LocalValue` fixes it.

Nontheless, this should be fixed as this is sample code :)

**Comment by robloo** [comment]
@amwx Thanks for tracking that down!

The fix seems easy: use the brand-new SetCurrentValue() method that won't destroy bindings and also won't change binding priority or require setting as animation. Quick test seems to work OK, will open a PR to close.
