### ISSUE TITLE
The content of the DataGrid control overflows the bottom border

### ISSUE THREAD

**Issue by chenjing1294** [AvaloniaUI/Avalonia#10562]
**Describe the bug**
The content of the DataGrid control overflows the bottom border
![datagrid_border](https://user-images.githubusercontent.com/21185657/223061884-03686109-fbb7-42da-a794-0767ad24b9cb.gif)
![datagrid_border2](https://user-images.githubusercontent.com/21185657/223061900-3e7f1973-e830-4136-b484-c29e96d36fb0.gif)

**To Reproduce**
```xml
  <DataGrid Items="{Binding Users, Mode=OneWay}"
            BorderThickness="3"
            BorderBrush="red"
            Background="white"
            RowBackground="#e2e2e2">
    <DataGrid.Columns>
      <DataGridTextColumn Header="Username"
                          Binding="{Binding Path=Username, Mode=OneWay}" />
      <DataGridTextColumn Header="Address" Binding="{Binding Path=Address, Mode=OneWay}" />
    </DataGrid.Columns>
  </DataGrid>
```

**Expected behavior**
DataGrid bottom border should not disappear.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.0-preview4，11.0.0-preview5

**Comment by timunie** [comment]
Good catch, thank you for finding this out.

**Comment by timunie** [comment]
Why did you close this issue? The PR will do it automatically.
