### ISSUE TITLE
IME, global menu and tray icon crash the app on Linux

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#10581]
DBus callbacks get executed on some random thread.

Introduced by https://github.com/AvaloniaUI/Avalonia/pull/9810

**Comment by maxkatz6** [comment]
@affederaffe hi, do you have time to take a look at this issue? Could be an issue with capturing synchronization context needed to run call backs.

**Comment by affederaffe** [comment]
I'll see what I can do 👍
