### ISSUE TITLE
App after publishing shows original Window outline

### ISSUE THREAD

**Issue by lukaszossowski** [AvaloniaUI/Avalonia#10586]
**Describe the bug**
I have an app with a custom main window, with the following properties:

TransparencyLevelHint="Transparent"
ExtendClientAreaToDecorationsHint="true"
ExtendClientAreaChromeHints="NoChrome"
ExtendClientAreaTitleBarHeightHint="-1"  
SystemDecorations="None"

When runnig it from VS everything is correct, the original Windows window does not show. However, after publishing the app as a self contained, single file, when I run it it shows the outline.

![outline](https://user-images.githubusercontent.com/112421929/223521785-803723c7-4c07-400f-b236-f460d16982e4.JPG)

**Comment by lukaszossowski** [comment]
After doing some more research I changed runtime identifierr to win7-x64 instead and it works now. Is this intended? I thought Avalonia doesn't officially support Windows 7.

**Comment by timunie** [comment]
Yes this is by design. The .NET compiler is missing a dll otherwise, for whatever reason.

**Comment by timunie** [comment]
win10-x64 should also work.

**Comment by lukaszossowski** [comment]
win10-x64 indeed works. Thank you. I think it might be worthwile to create a short tutorial in the documentation on how to publish, because currently there is nothing I could find and I only stumbled on the solution for this problem in one of the issues here. The other thing that might be worth mentioning is the necessity to add:
	`<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>`
into .csproj to actually publish into a single file, otherwise some dlls remain separate.

**Comment by timunie** [comment]
1. yes, docs are under review for 11.0 anyway
2. I think we might have found a solution for this particular requirement in latest nightly
