### ISSUE TITLE
BeginMouseDrag(...) behavior changed in 11-preview 5

### ISSUE THREAD

**Issue by halgari** [AvaloniaUI/Avalonia#10625]
**Describe the bug**
I recently upgraded to 11-preview 5, and my chromeless window stopped working properly. In preview-4 I added a `PointerPressed` handler to the window that had the following definition:

```csharp
    private void PointerPressed_Handler(object? sender, PointerPressedEventArgs e)
    {
        if (e.GetCurrentPoint(this).Properties.IsLeftButtonPressed)
        {
            BeginMoveDrag(e);
        }
    }
```

This allowed the window contents to continue to work properly, but any click not on a button could be used to drag the window around. 

Now the drag still works, but all the controls on the page no longer activate. Mouseover events work, but when I click the button everything is eaten by the Window `PointerPressed` command

**To Reproduce**
Create a window, add the above handler as a `PointerPressed` event, add a button. The Button's click handler is no longer called when the above event is registered

**Expected behavior**
I should be able to drag the window as long as I'm not clicking on a control.

**Desktop (please complete the following information):**

- OS: Windows 11
- .NET 7

**Comment by timunie** [comment]
That's sounds like a known issue in preview5. Shold be fixed already. Can you try latest nightly and give me a feedback if it works again?
