### ISSUE TITLE
Glitchy rendering when removing elements with visible Tooltip

### ISSUE THREAD

**Issue by VisualMelon** [AvaloniaUI/Avalonia#10632]
A single frame 'flicker' or 'glitchy' render occurs in some cases when modifying a control when there is a ToolTip showing. I can't nail down the specific behaviour, but my use-case is a user-control with clickable elements that - when clicked - causes the user-control to be rebuilt. If a clickable element's ToolTip is visible then the control either disappears momentary, or otherwise renders incorrectly.

Glitchy render seems to be across the whole application, not specific to the part of the UI with the control with the ToolTip (e.g. removing a control with a ToolTip somewhere and also rebuilding parts of the UI elsewhere causes the rebuilt UI to flicker).

**To Reproduce**
A minimal example can be found in https://gist.github.com/VisualMelon/faa66d64a8b2bf65ba8a350bbf479a35#file-mainwindow2-axaml-cs involving a `TextBlock` that replaces itself when clicked. Clicking the textbox before the tooltip appears replaces it clearly without any visual errors; allowing the tooltip to open before clicking causes it to 'flicker' between removing the old `TextBlock` and presenting the new `TextBlock`.

**Expected behavior**
ToolTip being open on a removed control should not affect render of other UI elements: there should be no 'flicker' or glitchy rendering.

**Workaround**
In simple cases, can work around by manually closing the ToolTips with `ToolTip.SetIsOpen(c, false)` before performing other UI changes.

**Environment**

Observed on Windows 10 in non-trivial application with Avalonia11-Preview5 and recent nightly.
Observed on Windows 10 in minimal examples with local build from ~2023-02-23, and local build as of commit c298a7ffbfed12d7974040704652f80b4502a31b

Not observed in the same application in 0.10; minimal examples not tested in 0.10. Not tested on other operating systems.

**Comment by VisualMelon** [comment]
Just confirming that this still seems to be present in Preview7

**Comment by maxkatz6** [comment]
> In simple cases, can work around by manually closing the ToolTips with ToolTip.SetIsOpen(c, false) before performing other UI changes.

Probably an easier workaround would be to not change the tooltip.tip property, but reuse the same textblock.
And instead rebuild text block properties.

**Comment by VisualMelon** [comment]
I think I've seen the same when a combo-box (the drop-down hides when selection is changed) causing a data-grid whose content is changed to flicker (looks blank for a 'frame'). Same behaviour is not observed, for example, when a checkbox that also causes the data-grid content to change is toggled.

**Comment by VisualMelon** [comment]
Having seen that weird behaviour from the above commit, I've found you can reproduce the same effect by performing UI changes (e.g. change the `ItemsSource` of an `ItemsControl`) and then immediately closing the tooltip without having to do anything remotely weird (like removing the element that is showing the tooltip): I assume this is performing the implicit close that occurs when you remove and item with an active tooltip. Again, moving the `ToolTip.SetIsOpen(btn, false);` before the other UI changes makes the problem go away.

**Comment by VisualMelon** [comment]
Indeed, if you go crazy and repeatedly show/hide the tooltip, then the UI stays in the broken state of a while.

```
for (int t = 0; t < 10; t++)
{
    ToolTip.SetIsOpen(btn, true);
    ToolTip.SetIsOpen(btn, false);
}
```

It's as though the UI changes put the UI into a not-complete state, and then showing hiding the tool-tip forces a re-render. Setting the FPS counter overlay, the frame number goes up by 2 instead of 1 (it doesn't go up by the number of times you hide/show the tooltip, always only one extra fram).

I've tried digging through the code a bit, but somehow I think I'm not going to be able to surmise where the problem is without a much better idea as to how the layout engine works.

**Comment by VisualMelon** [comment]
I can't repro this with 11.1.0, so going to close.
