### ISSUE TITLE
Memory leak in OpenGL control

### ISSUE THREAD

**Issue by hez2010** [AvaloniaUI/Avalonia#10631]
**Describe the bug**
Memory leak in OpenGL control

**To Reproduce**
Run CC.NetCore with default options, and follow the below video.

https://user-images.githubusercontent.com/14960345/224390063-813c3101-a13e-4769-a6bd-eabe53d6ce8b.mp4

**Expected behavior**
The memory consumption shouldn't keep increasing. 

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: Avalonia build from master

**Comment by jp2masa** [comment]
Duplicate of #10457?

**Comment by maxkatz6** [comment]
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/10457
