### ISSUE TITLE
ListBox traps into infinite cycle on scroll

### ISSUE THREAD

**Issue by dragondangun** [AvaloniaUI/Avalonia#10643]
**Describe the bug**
I have next `ListBox`:

```
<StackPanel Orientation="Horizontal">
  <ListBox x:Name="DomainUpDown1" Height="38">
    <ListBoxItem>Even</ListBoxItem>
    <ListBoxItem>None</ListBoxItem>
  </ListBox>
</StackPanel>
```

When I try to scroll it up (after scroll down) app freezes and go into infinite loop in `AvaloniaObject.cs` function `private T GetValueOrInheritedOrDefault<T>` (lines 716-743).

**To Reproduce**

1. Create ListBox as that I've written before
2. Hang mouse on ListBox and do at least one scroll down
3. Scroll up
4. See error -- application will freeze and if you click on it "Application is not responding" will show up.

**Expected behavior**
Apps must not freeze and `ListBox` must be scrolled to the first element.

**Desktop (please complete the following information):**

- OS: Windows
- Version: 0.10.18

**Comment by timunie** [comment]
@dragondangun I have tested this on 0.10.18 and can confirm the issue. However, using latest nightly builds it looks like the issue is solved. Can you double-check in a sample App if using latest 11.0 nightly builds?

**Comment by dragondangun** [comment]
@timunie, I've tried on 0.11.0-preview4 and there is still the issue. I couldn neither test it on nightly build cause of when I update my project to nightly build it creates `CS0102`. `CS0121` and `CS0111` errors and I don't know how to fix them, nor I could create new project with nightly build

**Comment by timunie** [comment]
Nightly builds is required to test, as it introduces some fixes to ListBox. Please read the breaking changes page for reference https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#010--110 

If you were not successful, please upload a minimal sample to GitHub and I'll guide you.

**Comment by grokys** [comment]
Should now be fixed.
