### ISSUE TITLE
Change how SplitView pointer light dismiss triggers

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#10652]
**Describe the bug**
Some recent changes seem to have broken my `NavigationView` which results in the pane toggle button not being able to close the pane if the underlying `SplitView` is in an "overlay" mode. I'm thinking this is some unintended side effect of the switch to a `StyledProperty`, though not sure how. I've figured out the issue actually stems from how the light dismiss behavior works in SplitView (which is my fault from the original addition). The simple fix is to change it to work on PointerRelease and bubble only - allowing the toggle button to actually work and stop the SplitView's default light dismiss behavior.

Essentially:
https://github.com/AvaloniaUI/Avalonia/blob/cbe0bb861a767b7bf7b268bbaa1d89dcf8523aea/src/Avalonia.Controls/SplitView/SplitView.cs#L309-L312
needs to change to
```C#
_pointerDisposable = window.AddDisposableHandler(PointerReleasedEvent, PointerReleasedOutside, RoutingStrategies.Bubble);
```
(and probably change it to work on `TopLevel` rather than `Window`

I'll do the PR if it will be accepted (I already have the change), but with community PRs paused, I wanted to ask first.

**Comment by maxkatz6** [comment]
Regression sounds like a critical bug to me, so yes, will be accepted. Thanks.
