### ISSUE TITLE
Bug in disabled scrollviewer after start app

### ISSUE THREAD

**Issue by MonkAlex** [AvaloniaUI/Avalonia#1065]
Use this ScrollViewer:

```
        <ScrollViewer VerticalScrollBarVisibility="Auto" CanScrollHorizontally="False">
          <ItemsControl Items="{Binding Items}">
            <ItemsControl.ItemTemplate>
              <DataTemplate>
                <Grid RowDefinitions="*,Auto" Margin="10"
                    Width="150" Height="300">
                  ...
                </Grid>
              </DataTemplate>
            </ItemsControl.ItemTemplate>
            <ItemsControl.ItemsPanel>
              <ItemsPanelTemplate>
                <WrapPanel/>
              </ItemsPanelTemplate>
            </ItemsControl.ItemsPanel>
          </ItemsControl>
        </ScrollViewer>
```

After start app i see horizontall scrollbar, then i resize window and all ok. On ubuntu see good, on windows7 - bugged.

![scrollbug](https://user-images.githubusercontent.com/6784764/28214231-791de676-68ba-11e7-89d7-18150f8561e7.gif)

**Comment by grokys** [comment]
From @MonkAlex in gitter:

> elements correct start on new line, but has horizontal scrollbar on start - and hide then after resize

**Comment by MonkAlex** [comment]
![horizontal](https://user-images.githubusercontent.com/6784764/34661389-cdeed9ba-f462-11e7-962a-6da4bfd5386a.gif)
