### ISSUE TITLE
Button foregroud black instead of white with dark theme in nightly build

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#10668]
After switching to nightly build `11.0.999-cibuild0031881-beta`, button foreground in dark theme is now black instead of white.

This affects [MediaPlayerUI sample](https://github.com/mysteryx93/MediaPlayerUI.NET) toolbar.

What's the work-around for now?

**Comment by maxkatz6** [comment]
@mysteryx93 hi! Is it still reproducible on 11.0?

**Comment by mysteryx93** [comment]
I haven't seem such problem since using stable releases; stopped using nightly builds.
