### ISSUE TITLE
debug model can catch exception ,but release app crash

### ISSUE THREAD

**Issue by 292390450** [AvaloniaUI/Avalonia#10679]
https://github.com/xamarin/xamarin-android/issues/7870

Can you see what caused it? I think it may be related to the mono runtime, because there is no such problem when publishing desktop applications

avalonia version 11.0.0-preview5

**Comment by timunie** [comment]
@292390450 can you do us two favors?

1. Please try to provide a minimal sample to reproduce 
2. Please try your sample again using latest nightly builds. Does it change anything?
