### ISSUE TITLE
SplitView TemplateSettings aren't set with the required values for Overlay Display mode.

### ISSUE THREAD

**Issue by emmauss** [AvaloniaUI/Avalonia#10694]
**Describe the bug**
When a SplitView with default DisplayMode is loaded, the default TemplateSettings do not match the required settings for Overlay DisplayMode, as compared to the TemplateSettings set when the DisplayMode is changed from Inline to Overlay. Thus, it behaves like Inline.

**To Reproduce**

1. Create a SplitView with Overlay DisplayMode, or leave it unset
2. Trigger/Set IsPaneOpen to true.

**Expected behavior**
Pane overlaps the main area.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version: master as of 3f46326948c994781f402cc6592adeae3e4fc510

**Additional context**

**Comment by emmauss** [comment]
@amwx This may interest you.

**Comment by amwx** [comment]
Working on it - will wrap into a couple other fixes for the SplitView
