### ISSUE TITLE
GridSplitter ShowPreview doesn't work

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#10700]
**Describe the bug**
GridSplitter should show a preview line, but the preview line disappear after mouse leaving the original area. 

**To Reproduce**

Add below xaml code in sandbox

```xaml
  <Grid Width="200" Height="200" RowDefinitions="*, Auto, *">
    <Border Background="Transparent"></Border>
    <GridSplitter Grid.Row="1" ShowsPreview="True" Background="Red"/>
    <Border Background="Transparent" Grid.Row="2"></Border>
  </Grid>
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: latest master (cbbc27f6)

**Additional context**
I think the root cause is that preview content in AdornerLayer is not rendered outside GridSplitter clip.

**Comment by rabbitism** [comment]
Oh nvm, I figured it out as soon as I posted this issue. We have to set ClipToBounds explicitly, but I think it should not be clipped by default?

**Comment by rabbitism** [comment]
More updates:
when checking the adorner layout demo, I found the lines are frozen on the region outside content area. 

![1679153739399](https://user-images.githubusercontent.com/14807942/226115579-c0fde7f1-e1cc-42b9-95a1-1692a1ba1546.jpg)

**Comment by robloo** [comment]
I just saw the adorner layer issue too and filed a new bug for it.
