### ISSUE TITLE
Reactive Command not executed on UI threat

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#10711]
Using nightly build `11.0.999-cibuild0031748-beta`.

Here I have Load and Save buttons bound to those commands.

When I Save a preset, the Load button becomes enabled. It actually works fine.

Until I publish the application with Assembly Trimming. After trimming, the Load button will not enable unless I add a Dispatcher invoke.

    Dispatcher.UIThread.Post(() => Settings.Presets.Add(preset));

```c#
global using RxCommandUnit = ReactiveUI.ReactiveCommand<System.Reactive.Unit, System.Reactive.Unit>;

public RxCommandUnit LoadPreset => _loadPreset ??= ReactiveCommand.CreateFromTask(LoadPresetImpl,
    Settings.Presets.ToObservableChangeSet().Select(x => x.Any()));
private RxCommandUnit? _loadPreset;
private async Task LoadPresetImpl()
{
    var loadItem = await _dialogService.ShowLoadPresetViewAsync(this).ConfigureAwait(true);
    if (loadItem != null)
    {
        loadItem.SaveAs(Playlist);
    }
}

public RxCommandUnit SavePreset => _savePreset ??= ReactiveCommand.CreateFromTask(SavePresetImpl,
    Playlist.Files.ToObservableChangeSet().ToCollection().Select(x => x.Any()));
private RxCommandUnit? _savePreset;
private async Task SavePresetImpl()
{
    var saveName = await _dialogService.ShowSavePresetViewAsync(this).ConfigureAwait(true);
    if (!string.IsNullOrWhiteSpace(saveName))
    {
        var preset = GetPresetByName(saveName);
        if (preset == null)
        {
            preset = new PresetItem();
            // DOES NOT WORK WITHOUT DISPATCHER!!!
            Dispatcher.UIThread.Post(() => Settings.Presets.Add(preset));
        }

        Playlist.SaveAs(preset);
        preset.Name = saveName;
    }
}
```

[So let's look at ReactiveUI documentation](https://www.reactiveui.net/docs/handbook/commands/#controlling-scheduling)

> It's important to understand that the execution logic for a reactive command is not scheduled to execute on the provided scheduler (just as is the case for any canExecute observable you provide). Instead, it is left to the caller to implement any required scheduling inside their execution pipeline. This means it is entirely possible for your execution logic to execute on a thread other than that owned by the provided scheduler:

```c#
var command = ReactiveCommand.Create(
    () => Console.WriteLine(Environment.CurrentManagedThreadId), 
    outputScheduler: RxApp.MainThreadScheduler
);

// This will output the ID of the thread from which you make 
// this call, not necessarily the ID of the main thread!
command.Execute().Subscribe();
```

Essentially, it says that Avalonia is responsible for this.

**Comment by jp2masa** [comment]
> Essentially, it says that Avalonia is responsible for this.

I think I didn't understand this, which part are you referring to? The ReactiveUI docs seem to indicate that the caller (i.e. your viewmodel) is responsible for implementing the required scheduling.

Also confused because `ConfigureAwait(true)` should work, but apparently it's not. Did you check the thread id before and after `await _dialogService...`?

**Comment by mysteryx93** [comment]
I tested again. `Environment.CurrentManagedThreadId` returns 1 before and after.

Currently it works without the Dispatcher.

What could have happened before? Are there any circumstances that could cause the issue I experienced? Not able to reproduce it right now.

**Comment by jp2masa** [comment]
For the code you posted, I can't think of any situation where you get the wrong synchronization context. The command is always invoked by the view, right?

**Comment by mysteryx93** [comment]
Yes, bound to a button

**Comment by mysteryx93** [comment]
I am now unable to reproduce. Wondering what happened.

I'll close this for now. Will open a discussion if I encounter the problem again.

**Comment by nrenzoni** [comment]
I was receiving the exception:
```System.InvalidOperationException: Call from invalid thread``` after my ```ICommand``` built using ```ReactiveCommand.Create()```, bound to a Button command was invoked.

Although my google search led me here, it was an easy fix, my ```AppBuilder.Configure``` in Program.cs was missing ```UseReactiveUI() in the following:
```
AppBuilder.Configure<App>()
   .UseReactiveUI()
```

I am using Avalonia 0.10.18, so might not be related to your issue @mysteryx93. But I came to this issue after googling my exception so maybe this will help someone.

**Comment by timunie** [comment]
@nrenzoni can you open a Q&A discussion for it and send your command definition? It's not wise to answer closed issues. Thx.
