### ISSUE TITLE
Why Transitions only work once?

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#10717]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/10714

<div type='discussions-op-text'>

<sup>Originally posted by **kyuranger** March 20, 2023</sup>
I want to change the height with animation by checkbox. Here is my code:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1">
	<Window.Styles>
		<Style Selector="Border.TestChecked">
			<Setter Property="Height" Value="150"/>
		</Style>
		<Style Selector="Border.TestUnChecked">
			<Setter Property="Height" Value="0"/>
		</Style>
	</Window.Styles>
	<Grid RowDefinitions="auto,auto">
		<CheckBox Name="CB"></CheckBox>
		<Border Width="100" HorizontalAlignment="Left" Background="Red" Classes.TestChecked="{Binding #CB.IsChecked}" Classes.TestUnChecked="{Binding !#CB.IsChecked}" Grid.Row="1">
			<Border.Transitions>
				<Transitions>
					<DoubleTransition Property="Height" Duration="0:0:0.5"></DoubleTransition>
				</Transitions>
			</Border.Transitions>
		</Border>
	</Grid>
</Window>
```

![1](https://user-images.githubusercontent.com/30720036/226242553-bfaebb57-717f-45c6-92a9-078763e3009a.gif)

However, as you see above. When I uncheck the checkbox, Transitions will not work. What's wrong with my code?
</div>

**Comment by kyuranger** [comment]
> Even if we have a possible workaround, we consider this as a bug. Therefore I'm converting this into an issue now.
> 
> @kyuranger thank you for the great sample to reproduce it easily 👍
> 
> /cc @jmacato

Not at all. Hope it can be fixed.

**Comment by grokys** [comment]
The problem is that between the `TestChecked` class being cleared and the `TestUnChecked` class being set, there is a period of time where neither classes are applied and so the border `Height` reverts to `NaN`. Transitioning to/from NaN isn't possible, so no transition is shown.

**Comment by dbriard** [comment]
Hi, 
I also have an issue with transition that was working only once.
I added a VectorTransition to the Offset property of scrollviewer to be able to animate scrolling page by page.
So in this case, it is not because of NaN value as suggested in previous reply.

```
<Setter Property="Transitions">
    <Setter.Value>
        <Transitions>
            <VectorTransition Property="Offset" Duration="0:0:1.167" />
        </Transitions>
    </Setter.Value>
</Setter>
```
https://github.com/AvaloniaUI/Avalonia/assets/3595443/25e5fbf5-456b-4c64-a762-0b5af346c057

Anyone have an idea why it is not working several times?
Thank you

**Comment by timunie** [comment]
The solution that @grokys suggests works now after #13970 using nightly builds. NaN is still not supported, but I believe that is by design. If anyone disagrees, please ping me.
