### ISSUE TITLE
Data Templates in Menu Item and TreeView no longer work in 11 preview 5

### ISSUE THREAD

**Issue by dvbianculli** [AvaloniaUI/Avalonia#10718]
**Describe the bug**
Data Templates that were previously working in 0.10.18 no longer work after upgrading to 11 preview 5.
For MenuItems, all the items are empty, but the correct amount of items is there.
For TreeViews, the root node is displayed, but all sub nodes cannot be accessed, because the expander is never rendered.

**To Reproduce**
I have created a small sample with both versions
https://github.com/dvbianculli/SampleBrokenDataTemplates

**Expected behavior**
The templates apply and render as they did previously

**Screenshots**
v0.10.18 
TreeView
![image](https://user-images.githubusercontent.com/9488862/226392021-2a6ff5bc-dfc6-4f2e-b044-07b150941437.png)
MenuItem
![image](https://user-images.githubusercontent.com/9488862/226392074-1e340d95-285d-4564-93fd-9e1a759c4252.png)

v11 preview 5
TreeView
![image](https://user-images.githubusercontent.com/9488862/226392193-c5a01aff-b5bb-4881-875b-26cd2ccee522.png)
MenuItem
![image](https://user-images.githubusercontent.com/9488862/226392236-1ed5a2f7-1eb4-428d-b41b-e72e4ae96e2c.png)

- OS: Windows 10
- Version 10.0.19044 Build 19044

**Comment by workgroupengineering** [comment]
In 11v align behavior to wpf and uwp, to style the container you do:

For MenuItem add
```xaml
              <MenuItem.ItemContainerTheme>
                <ControlTheme TargetType="MenuItem" BasedOn="{StaticResource {x:Type MenuItem}}" x:DataType="vm:FileViewModel">
                  <Setter Property="Header" Value="{Binding}"/>
                </ControlTheme>
              </MenuItem.ItemContainerTheme>
```
for tree

```xaml
            <TreeView.ItemContainerTheme>
              <ControlTheme TargetType="MenuItem" BasedOn="{StaticResource {x:Type TreeViewItem}}" x:DataType="vm:BaseViewModel">
                <Setter Property="Header" Value="{Binding}"/>
              </ControlTheme>
            </TreeView.ItemContainerTheme>
```

You must use night build.

**Comment by workgroupengineering** [comment]
I think because is working in progress.

**Comment by stevemonaco** [comment]
> For the TreeView it does need to be nightly.

You probably ran into https://github.com/AvaloniaUI/Avalonia/issues/10398 on this part which was a regression. There's a workaround in preview5 and it's been fixed for preview6. A lot of internals have been rewritten for collection controls and some things were broken in the process.

**Comment by timunie** [comment]
can you please double-check if updating to preview6 solves the issue for you?

**Comment by dvbianculli** [comment]
In preview 6 the TreeDataTemplates work like they did in the last stable release. So thats fixed!

MenuItems still need the workaround of using an ItemContainerTheme to actually use DataTemplates.
