### ISSUE TITLE
StaticResource within a ThemeDictionary unable to look up a resource of another ThemeDictionary

### ISSUE THREAD

**Issue by TheXamlGuy** [AvaloniaUI/Avalonia#10727]
**To Reproduce**

Create a Default and Dark ThemeDictionary in a ResourceDictionary somewhere.

```
   <ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Default">
            <SolidColorBrush x:Key="Foo" Color="Green" />
        </ResourceDictionary>
        <ResourceDictionary x:Key="Dark">
            <SolidColorBrush x:Key="Foo" Color="Red" />
        </ResourceDictionary>
    </ResourceDictionary.ThemeDictionaries>
```

Declare another ResourceDictionary, lets say in App.axaml which includes the above ResourceDictionary. Create a ThemeDictionary  for Default and Dark both using a StaticResource declaring the ResourceKey from this other ResourceDictionary.

 ```
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceInclude Source="Test.axaml" />
            </ResourceDictionary.MergedDictionaries>
            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Default">
                    <StaticResource x:Key="Bar" ResourceKey="Foo" />
                </ResourceDictionary>
                <ResourceDictionary x:Key="Dark">
                    <StaticResource x:Key="Bar" ResourceKey="Foo" />
                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```

Examples of resource usage 

```
      <!--Direct resource-->
        <Border
            Width="100"
            Height="100"
            Background="{DynamicResource Foo}" />

      <!--Indirect resource-->
      <Border
          Width="100"
          Height="100"
          Background="{DynamicResource Bar}" />
```

**Expected behavior**
With the above example with the direct resource key as Foo, and the indirect resource key pointing to Bar, while the application is running in Dark mode I'd expect both border control to be red.  When the application is running in Light mode, both border are green as expected.

**Screenshots**
Dark mode
![image](https://user-images.githubusercontent.com/14894973/226742085-0f18d076-911c-4d54-8cc6-398f990f6c16.png)

Light mode
![image](https://user-images.githubusercontent.com/14894973/226742245-08e4e947-5d42-483a-aca3-99625f2895a9.png)

Am I doing something incorrect, or is this a case of being an unsupported scenario? This is supported in WinUI/UWP.

**Comment by amwx** [comment]
IIRC `StaticResource` doesn't do the lookup with the ThemeVariant context, so when the xaml is parsed, the resource is evaluated using the 'default' ThemeDictionary. This is why we have monster sized theme resource files right now as colors, brushes, and StaticResource aliases need to be in the same theme dictionary to init properly.
