### ISSUE TITLE
Updating the Accent color in Fluent theme does not properly apply the darker and lighter variants

### ISSUE THREAD

**Issue by zerppa** [AvaloniaUI/Avalonia#10746]
I'm trying to implement a simple UI customization for my app that involves changing the Accent color. The base resource `SystemAccentColor` does update as expected, but styles that use the variants such as `SystemAccentColorDark1` or `SystemAccentColorLight1` don't get applied. As a result, the mouseover and pressed styles will remain the same regardless from the new accent color.

This can be verified by running the The **Avalonia Control Gallery** example app:

1. Open the sample app
2. Go to the **Buttons** view
3. Open Windows' "Color settings" dialog that lets you change the OS accent color
4. Select a new OS accent color
5. The Avalonia Control Gallery will detect the change and adjusts the accent color accordingly. Observe the button titled "Accent" to change its color
6. Now mouseover the button and try to press it. Observe that both the hover and pressed styles remain unchanged, breaking consistency

The same problem concerns at least the following controls: Toggle button, Toggle split button, Checkbox, Radio button, Slider, Toggle switch.

This is how the sample app changes the accent related resources (https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/MainView.xaml.cs):
```csharp
Application.Current!.Resources["SystemAccentColor"] = e.AccentColor1;
Application.Current.Resources["SystemAccentColorDark1"] = ChangeColorLuminosity(e.AccentColor1, -0.3);
Application.Current.Resources["SystemAccentColorDark2"] = ChangeColorLuminosity(e.AccentColor1, -0.5);
Application.Current.Resources["SystemAccentColorDark3"] = ChangeColorLuminosity(e.AccentColor1, -0.7);
Application.Current.Resources["SystemAccentColorLight1"] = ChangeColorLuminosity(e.AccentColor1, 0.3);
Application.Current.Resources["SystemAccentColorLight2"] = ChangeColorLuminosity(e.AccentColor1, 0.5);
Application.Current.Resources["SystemAccentColorLight3"] = ChangeColorLuminosity(e.AccentColor1, 0.7);
```

I tried to apply these also on the `MainWindow` and even directly to the FluentTheme instance's resources, it doesn't seem to matter where you're defining them, the end result is still the same. Affects both **Light** and **Dark** themes.

master (74d0241e7fefe38d1bfcdbac1a95c2dd50a30578) 11.0.0-preview6 era
Tested on Window 10.

**Comment by robloo** [comment]
Does this work now with preview 8? There were changes that might have fixed this.

**Comment by maxkatz6** [comment]
Yes. Before preview8 some resources have statically keep first accent color value without allowing it to dynamically change. See this commit that fixed the issue https://github.com/AvaloniaUI/Avalonia/pull/11097/commits/1aba81a27f1f568d41c948676ac3580c58cb6a5b

With preview8 your code should work just fine.

Although I would recommend using ColorPaletteResources for fluent to change these colors as it has a better and stable API for these resources instead of relying on resources initialization order and internal structure: https://github.com/AvaloniaUI/Avalonia/pull/11097#issue-1679291634
