### ISSUE TITLE
IME experience not good

### ISSUE THREAD

**Issue by dayAndnight2018** [AvaloniaUI/Avalonia#10742]
Background:  I switch to Chinese Input mode in an IME, just like "SouGou".
I type in some words just like this:
<img width="160" alt="image" src="https://user-images.githubusercontent.com/44399091/226953891-f7a87499-0b51-4348-bb61-af8ae1a04464.png">
but when i use backspace to delete one character, it delete the words already in the TextBox! What I expect is it just like the following, maybe a preview "ser" in the TextBox, when I use backspace, it turns to "se"，or I enter the space, they are replaced by "色"？

Am i describe it clearly?

**Comment by dayAndnight2018** [comment]
just some example in sublime3 on mac:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/44399091/226958061-50875744-3468-4af4-af28-bfc21ef3b22c.png">
use backspace，it delete the "o" in the preview mode, not "，"
<img width="257" alt="image" src="https://user-images.githubusercontent.com/44399091/226958348-6f6011bf-5f59-4b2d-ae29-2c7677a739c0.png">

**Comment by Gillibald** [comment]
Are you using preview6?

**Comment by dayAndnight2018** [comment]
> Are you using preview6? We might need to intercept the backspace command and just modify the current composition.

yes, what is the schedule?

**Comment by hez2010** [comment]
I didn't encounter any problems while using Microsoft IME. Maybe you can record a video to demonstrate your issue in detail?

**Comment by maxkatz6** [comment]
Looks like it's from the older avalonia versions. MacOS IME improvements were done in latest preview6.

**Comment by dayAndnight2018** [comment]
> I didn't encounter any problems while using Microsoft IME. Maybe you can record a video to demonstrate your issue in detail?

on macbook

**Comment by dayAndnight2018** [comment]
Is there any progress? @Gillibald

**Comment by Gillibald** [comment]
Should be fixed in preview7
