### ISSUE TITLE
Incorrect ActualTransparencyLevel on win-x64 RID

### ISSUE THREAD

**Issue by X9VoiD** [AvaloniaUI/Avalonia#10748]
**Describe the bug**
When the application is built with `win-x64` as RID, the `ActualTransparencyLevel` is set to whatever I set `TransparencyLevelHint` to or `AcrylicBlur` if trying to set to `Mica`. However, actual behaviour shows `WindowTransparencyLevel.None`.

tl;dr it's misreporting `ActualTransparencyLevel`

**To Reproduce**

1. Create any kind of transparent window. For example:
```xaml
<Window
        ...
        Background="Transparent"
        ExtendClientAreaChromeHints="PreferSystemChrome"
        ExtendClientAreaToDecorationsHint="True">
</Window>
```
2. `dotnet build --runtime "win-x64"`
3. Run the application

**Expected behavior**
`ActualTransparencyLevel` should be set to `WindowTransparencyLevel.None`.

**Screenshots**

The text in these screenshots are binded to text representation of `ActualTransparencyLevel`

`win-x64`
![image](https://user-images.githubusercontent.com/10338031/227053573-26b1350c-ad36-44ec-9a37-af2634b91858.png)

`win10-x64`
![image](https://user-images.githubusercontent.com/10338031/227054031-1db681c1-f61e-4370-a529-bcfa28e47fa7.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0.0-preview 5

**Comment by maxkatz6** [comment]
Please try preview6

**Comment by X9VoiD** [comment]
11.0.0-preview6 works as expected :thumbsup:
