### ISSUE TITLE
TrayIcon broken with 11.0.0-preview6

### ISSUE THREAD

**Issue by weskoerber** [AvaloniaUI/Avalonia#10749]
**Describe the bug**

Upgrading from `11.0.0-preview5` => `11.0.0-preview6` broke `TrayIcon`. On linux, a placeholder icon is displayed for a few seconds then disappears. The `NativeMenu` attached to the `TrayIcon` does not work either - the menu does not show when clicking the placeholder icon where the actual `TrayIcon` should be.

**To Reproduce**

1. Using 11.0.0-preview6, create new `avalonia.mvvm` project
2. Add `TrayIcon` to `App.xaml` from [docs](https://docs.avaloniaui.net/docs/controls/tray-icon)
3. Run app, observe broken `TrayApp`

**Expected behavior**
The `TrayIcon` should work as it did in `11.0.0-preview5` :)

**Screenshots**

11.0.0-preview5:
![preview5](https://user-images.githubusercontent.com/28966224/227068889-12074b41-333e-40b1-a890-e54df480952d.png)

11.0.0-preview6:
![preview6](https://user-images.githubusercontent.com/28966224/227068888-91527cad-3190-4603-aed2-0ec9ad54750b.png)

**Desktop (please complete the following information):**

- OS: Linux (Fedora 37, kernel 6.1.15-200.fc37.x86_64)
- Version: 11.0.0-preview6

**Additional context**
Add any other context about the

---

Edit: `TrayIcon` on version `11.0.0-preview6` is working fine on Windows 10. Seems to be a Linux-specific issue.

Edit2: I attached output from `systemd-journald`:
[syslog.log](https://github.com/AvaloniaUI/Avalonia/files/11046061/syslog.log)

**Comment by kekekeks** [comment]
@affederaffe 
```
Impossible to get basic properties: Gio.IOErrorEnum: Method “org.freedesktop.DBus.Properties.Get” returned type “(s)”, but expected “(v)”
GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "Activate" with signature "ii" on interface "org.kde.StatusNotifierItem" doesn't exist
Gio.IOErrorEnum: Method “org.freedesktop.DBus.Properties.Get” returned type “(s)”, but expected “(v)”
```
It seems to be a problem with variant handling.
