### ISSUE TITLE
StorageProvider.OpenFilePickerAsync - dialog hides behind app main window -- 11P6

### ISSUE THREAD

**Issue by kuiperzone** [AvaloniaUI/Avalonia#10751]
**Describe the bug**
Running on Fedora 37 (Gnome) with Avalonia 11P6.

When open a file dialog with:

        public async void OpenSolutionDialog()
        {
            var opts = new FilePickerOpenOptions();
            opts.Title = "Open Solution or Project";
            opts.AllowMultiple = false;

            var type = new FilePickerFileType("Solution (*.sln; *.csproj)");
            type.Patterns = new string[] { "*.sln", "*.csproj" };
            opts.FileTypeFilter = new FilePickerFileType[] { type };

            var paths = await StorageProvider.OpenFilePickerAsync(opts);

            if (paths?.Count > 0)
            {
                Console.WriteLine("++++++++++++++++");
                Console.WriteLine(paths[0].Name);
                Console.WriteLine("++++++++++++++++");
                //OpenSolution(paths[0].Name);
            }
        }

The FilePicker dialog hides behind the main window when shown. If the MainWindow is maximized, then it will appear to the user that nothing has happened (no picker dialog appears). See screenshot.

Expect this issue will apply to other dialogs kinds, not just OpenFilePicker.

Also note, that if the parent window is "stay-on-top" (it's not in my test, but if it was...) --  then the file dialog should still appear in front of the parent window. Ref https://github.com/AvaloniaUI/Avalonia/issues/10147

UPDATE - The file dialog window in 11P6 is NOT MODAL either. Meaning that it does not behave as a dialog -- it is possible to open the dialog, and then continue interacting with the main app window, while the dialog is left open and visible (or hiding behind the main window).

UPDATE: I note that the old deprecated method is now also broken on 11P6:

            var dialog = new OpenFileDialog();
            dialog.Title = "Open Solution or Project";
            dialog.Filters?.Add(new FileDialogFilter() { Name = "Solutions (*.sln; *.csproj)", Extensions = { "sln", "csproj" } });
            var paths = await dialog.ShowAsync(this);

COMPARE THE BEHAVIOUR NOW ON 11P6 with the previous 10.18.

![image](https://user-images.githubusercontent.com/17156238/227124498-34d2cb51-e3ae-4a2e-95e5-62716717c524.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

**Comment by maxkatz6** [comment]
Does switching dialog implementation fixes the issue?  See https://github.com/AvaloniaUI/Avalonia/issues/9383#issuecomment-1308330326

**Comment by kekekeks** [comment]
Was it working with preview5?

**Comment by kuiperzone** [comment]
> 

Just tried it. Looks broken in P5.

I've just committed to changes for P6 to AvantGarde master. You might like to use this for test. It should build straight out of the box. 

https://github.com/kuiperzone/AvantGarde

**Comment by kuiperzone** [comment]
> Does switching dialog implementation fixes the issue? See [#9383 (comment)](https://github.com/AvaloniaUI/Avalonia/issues/9383#issuecomment-1308330326)

If you mean creating a Dialog class instance, no, I think the deprecated implementation is broken also in P6.

**Comment by maxkatz6** [comment]
No, I meant changing linux platform options. Disabling dbus dialog or enabling managed dialogs.

**Comment by kuiperzone** [comment]
Strange...

Source code below.

Setting `UseDBusFilePicker = false` makes no difference. Picker dialog opens behind main window and the user can switch focus between the two.

Setting `UseDBusFilePicker = true` ... no on the first occurrence, the dialog appears in front and is modal (i.e. cannot switch focus). Seems to work as expected. HOWEVER, if you click Open File again, subsequent picker dialogs appear behind the main window are not model (i.e. broken).

        // Avalonia configuration, don't remove; also used by visual designer.
        public static AppBuilder BuildAvaloniaApp()
        {
            return AppBuilder.Configure<App>().UsePlatformDetect()
                .With(new X11PlatformOptions
            {
                UseDBusFilePicker = true // to disable FreeDesktop file picker
            });

            // return AppBuilder.Configure<App>().UsePlatformDetect().LogToTrace().UseReactiveUI();
        }

Here's the app. Version 11P6 in mainline. Should build out of the box. Easy to test.

https://github.com/kuiperzone/AvantGarde

Screenshot below.

![image](https://user-images.githubusercontent.com/17156238/227585333-110344ab-06d5-4db3-b346-ef933d439685.png)

**Comment by kuiperzone** [comment]
See also https://github.com/AvaloniaUI/Avalonia/issues/10147

**Comment by manuc66** [comment]
I had this bug on 11.0.0 and no longer reproduce it after upgrading to 11.0.3

**Comment by timunie** [comment]
@kuiperzone can you double check with latest version?

**Comment by timunie** [comment]
closing this issue for now as we have positive feedback from the community. If issue persist, let me know and I'll re-open it.
