### ISSUE TITLE
I want to need tansparent NativeHostControl 

### ISSUE THREAD

**Issue by ChisterWu** [AvaloniaUI/Avalonia#10758]
Hellow Avalonia Development Team:
When I use NativeControlHost  to host windows ， I find that the background is always black. But there is an urgent need for a tansparent background. I found through the  source code that it is always black, so can you consider opening a configuration to modify this value?
![image](https://user-images.githubusercontent.com/28770378/227159523-647a8ff1-099c-42e5-870a-7e2ec712d3af.png)

**Comment by kekekeks** [comment]
We are creating the parent window with WS_EX_LAYERED. You might need a [compatibility manifest with the recent windows version](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#supportedos) to enable that behavior.

[Example](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog.NetCore/app.manifest)
