### ISSUE TITLE
MenuItem children are vertically centered with parent instead of top-aligned [11-preview6]

### ISSUE THREAD

**Issue by stevemonaco** [AvaloniaUI/Avalonia#10765]
**Describe the bug**
Seems to be a regression with vertical alignment when moving from 11-preview5 to 11-preview6 / nightly. Horizontal alignment seems correct.

**To Reproduce**
1. Create project with Mvvm template, use `FluentTheme` (default).
2. Use this XAML in `MainWindow.axaml`:

```xml
<Grid RowDefinitions="auto,*">
    <Menu>
        <MenuItem Header="First">
            <MenuItem Header="First.A" />
            <MenuItem Header="First.B">
                <MenuItem Header="First.B.1" />
                <MenuItem Header="First.B.2" />
                <MenuItem Header="First.B.3" />
                <MenuItem Header="First.B.4" />
                <MenuItem Header="First.B.5" />
                <MenuItem Header="First.B.6" />
            </MenuItem>
            <MenuItem Header="First.C" />
        </MenuItem>
        <MenuItem Header="Second">
            <MenuItem Header="Second.A" />
            <MenuItem Header="Second.B" />
        </MenuItem>
    </Menu>
</Grid>
```

3. Run app and check menu.
4. Upgrade app to preview6 and re-check menu.

**Screenshots**
11-preview5 shows expected alignment:
![image](https://user-images.githubusercontent.com/1782158/227244007-4f82bd30-2366-4b32-b338-a99ddac1fbeb.png)

11-preview6 (and 11.0.999-cibuild0032155-beta nightly) shows vertical centering on parent for child items:
![image](https://user-images.githubusercontent.com/1782158/227244294-90c0cf08-75d7-4a09-9929-da5d498531b1.png)

**Desktop (please complete the following information):**

- OS: Win10
- Version 11-preview5 -> 11-preview6 / 11.0.999-cibuild0032155-beta

**Additional context**
Horizontal alignment, while ok with only `FluentTheme` here, also suffers from horizontal centering in FluentAvalonia in 2-preview6. I will post an additional issue over there.

**Comment by robloo** [comment]
Related to #10662
