### ISSUE TITLE
ItemsControl items won't show

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#10769]
**Describe the bug**
In some cases, inserting/adding new items to an `ObservableCollection` that's bound to a `ListBox` or `ItemsControl` will cause these items to not show.
This seems to be the case consistently when inserting at the index 0.
This also seems to cause a "defective" state for the `VirtualizingStackPanel` causing items to overlap.

**To Reproduce**
In Control Catalog, `ListBoxPageViewModel` change the following - 

Line 23 - 
https://github.com/AvaloniaUI/Avalonia/blob/74d0241e7fefe38d1bfcdbac1a95c2dd50a30578/samples/ControlCatalog/ViewModels/ListBoxPageViewModel.cs#L23
```
Items = new ObservableCollection<ItemModel>(Enumerable.Range(1, 7).Select(i => GenerateItem()));
```
Change to less items to notice anything.

Line 37 - 
https://github.com/AvaloniaUI/Avalonia/blob/74d0241e7fefe38d1bfcdbac1a95c2dd50a30578/samples/ControlCatalog/ViewModels/ListBoxPageViewModel.cs#L37
```
AddItemCommand = MiniCommand.Create(() => Items.Insert(0,GenerateItem()));
````
Change the item to be inserted at index zero.

1. Run Control Catalog
2. Click on ListBox page
3. Click the add item button

**Expected behavior**
Items to be added reliably.

**Screenshots**
This is the overlapping -
![image](https://user-images.githubusercontent.com/27368554/227310369-89c482db-0f27-433a-b191-70dad29e8eba.png)

**Additional context**
Commenting the `if` in line 1094 in `VirtualizingStackPanel` and letting the `else` section always execute, seems to solve the issue.
https://github.com/AvaloniaUI/Avalonia/blob/74d0241e7fefe38d1bfcdbac1a95c2dd50a30578/src/Avalonia.Controls/VirtualizingStackPanel.cs#L1094

@grokys I believe you're the most relevant guy for this (sorry for notification if not)

**Comment by Mikolaytis** [comment]
this bug definitely has a blocker priority. @adirh3 thanks for a hotfix hint. will try this

**Comment by grokys** [comment]
Thanks @adirh3 - that one was a bit of a 🤦 . #10788 should fix it.

**Comment by Mikolaytis** [comment]
Tried your solution. Still has issue with crash. trying to get element with index -22 from my collection.
<img width="1552" alt="Screenshot 2023-03-25 at 02 25 56" src="https://user-images.githubusercontent.com/4997065/227661011-afffba22-aebf-4c68-a7f4-c7028c139455.png">
