### ISSUE TITLE
Publish app opens console in Windows

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#10771]
Great, published my app with `preview6`!! Works beautifully in Linux.

On Windows... it opens up a console window in the background?? What's the deal with that?

**Comment by kekekeks** [comment]
See 
https://github.com/AvaloniaUI/Avalonia/issues/6672
https://github.com/dotnet/runtime/issues/3828

**Comment by mysteryx93** [comment]
ah that's the difference. Normally I build on Windows; this time I built quickly on Linux just for testing the app.

OK fine; there are other issues with publishing in Linux, like icons and metadata not being applied.
