### ISSUE TITLE
NumericUpDown: leaving the textbox empty produces null in a compiled bindings even on a value type (regression from preview5 -> 6)

### ISSUE THREAD

**Issue by aldelaro5** [AvaloniaUI/Avalonia#10793]
**Describe the bug**
When I have a NumericUpDown's value bound to a `float` (NOT a `float?`) and I clear the textbox, it will throw and emit an error if the binding is a CompiledBinding, but nothing bad happens if it's a ReflectionBinding.

**To Reproduce**
I used the Sandbox project in this repos sources. You can reproduce the issue with the following code:
MainWindow.xaml:
```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'
        xmlns:vm="clr-namespace:Sandbox"
        x:DataType="vm:MainWindowViewModel"
        RequestedThemeVariant="Dark"
        x:Class="Sandbox.MainWindow">
  <NumericUpDown Width="200" Value="{CompiledBinding test}" Increment="1" ParsingNumberStyle="Float"/> 
</Window>
```

MainWindowViewModel.cs
```cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace Sandbox;

public class MainWindowViewModel : INotifyPropertyChanged
{
    private float _test = 0;
    public float test
    {
        get => _test;
        set
        {
            _test = value;
            OnPropertyChanged();
        }
    }
    
    public event PropertyChangedEventHandler PropertyChanged;

    protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    protected bool SetField<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value)) return false;
        field = value;
        OnPropertyChanged(propertyName);
        return true;
    }
}
```
From there, run the sandbox project, select the 0 that appears inside the NumericUpDown and press backspace to delete it. You should see a validation error pop. You can change the binding to be a ReflectionBinding to see that no error occured and it actually sets the value to the default of float.

**Expected behavior**
To have the value be set to the default of float as it's a value type. It cannot be null. Basically, I am expecting the current behavior of ReflectionBinding.

**Additional context**
I performed a bisection and this issue was introduced by #10039 which sounded odd to me: why would a PR made to remove unpredictability with null binding values causes this? It seems that this PR introduced a change that maybe wasn't adapted to compiled bindings because it does mention it is supposed to emit an error, but the question is more how did this even TRIED to push null? When I found it that it applied specifically to compiled bindings, that's when I knew it was just broken.

**Comment by aldelaro5** [comment]
So far, this line is the most suspicious to me: https://github.com/AvaloniaUI/Avalonia/pull/10039/files#diff-a399661754b2504cc1c701d3e945dc52d9c6e5c55d228320893301b75f6be220L33

Why would we not push unset if it's a valueType? I understand not pushing unset for nullable value types, but you can't push null to a float.

**Comment by aldelaro5** [comment]
Yeah ok I think I understand what's happening, I'll submit a pr and we'll see.

**Comment by aldelaro5** [comment]
So I was going to file a PR about this because something felt odd to me, but I am realising that maybe the problem is somewhere else so I'll give my idea and let's discuss if I am on the right track.

The line I linked above would actually return unset with nullable value types (I did not know a Nullable<T> was a value type) which is what the pr was trying to not do.

The problem is it also means we are attempting to push null for non nullable value type. The PR I mentioned above does seem to imply that it's intented to emit an error...

But that doesn't seem to make sense. How could empty resolve to null for a non nullable value type?

My idea was to change that return null to be:
```cs
return targetType.IsValueType && Nullable.GetUnderlyingType(targetType) is null ? AvaloniaProperty.UnsetValue : null;
```

I would just like to know if this is something I should pr. This will only return unset for non nullable value types.

**Comment by maxkatz6** [comment]
@grokys @tomenscape any ideas?

**Comment by Artfunkel** [comment]
[Here's the problem.](https://github.com/AvaloniaUI/Avalonia/blob/6ad2f2a2f4a5ab183f5f125de9df197281eb9720/src/Avalonia.Controls/NumericUpDown/NumericUpDown.cs#L846-L857) `NumericUpDown` is passing `null` to the binding when there is no text. It should clear the property instead, which will result in the binding reverting to its default value, or a lower-priority value source taking over.

We shouldn't add a special case for `Nullable` to the default converter, because a different value type can always be defined to be compatible with `null` in the same way that `Nullable` is.

**Comment by tomenscape** [comment]
[Here's the problem.](https://github.com/AvaloniaUI/Avalonia/blob/6ad2f2a2f4a5ab183f5f125de9df197281eb9720/src/Avalonia.Controls/NumericUpDown/NumericUpDown.cs#L846-L857) `NumericUpDown` is passing `null` to the binding when there is no text. It should clear the property instead, which will result in the binding reverting to its default value, or a lower-priority value source taking over.

We shouldn't add a special case for `Nullable` to the default converter, because a different value type can always be defined to be compatible with `null` in the same way that `Nullable` is.

**Comment by rabbitism** [comment]
This is really determined by the control author. Like in devexpress, they even have an "AllowNullInput" property to control the behavior.

**Comment by tomenscape** [comment]
Looking a bit more closely, my comment above got it a bit wrong. `NumericUpDown.Value` is `decimal?` and the default is actually `null`. So it's behaving correctly. (Side note: we could still clear the property instead of assigning null, since that would use the default value defined by a derived type.)

The viewmodel property in question is non-nullable `decimal`, which is not a compatible type. No matter what we do inside the control, someone can come along and manually assign `null` to the property, and the same exception will then occur.

**Comment by timunie** [comment]
I still believe a property either called AlllowNull or FallbackValue could help in that situation. When one clears thw control, the fallback will be set. If the fallback is null as well, null is set.

**Comment by timunie** [comment]
@maxkatz6 let me know what you prefer and I can file a PR

**Comment by tomenscape** [comment]
Sounds like a good idea. But what if the user's desired behaviour is not to update the binding source at all when a value can't be parsed from the text? AFAIK that would have to be implemented in the binding itself, i.e. with a converter.

**Comment by aldelaro5** [comment]
My opinion is I feel like if I want to bind a numeric up down that the type is a non nullable number. I use this control because it allows me to be sure that whatever comes out of this is a number.

But by the same token, I should also be able to prevent the possibility that you could push invalid values with it. It feels like I would want to OPT IN to nullability rather than OPT OUT.

In other words, it seems more logical to me that I should be more explicit if I want null than if I don't want it.

**Comment by timunie** [comment]
@aldelaro5 I think everyone has a different feeling about this. But if you prefer to OPT-IN, I think a Style can do this for you. You could add it to your personal styles library.

**Comment by aldelaro5** [comment]
I ended up having this as a workaround, it's p ugly, but it works:
```cs
using System;
using System.Globalization;
using Avalonia.Data.Converters;

namespace BugFablesSaveEditor.Converters;

public class NumericUpDownValueConverter : IValueConverter
{
  public object Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
  {
    if (value is null)
      return default(decimal);
    return (decimal?)((IConvertible)value).ToDecimal(culture);
  }

  public object ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
  {
    if (value is null)
    {
      if (targetType == typeof(int))
        return 0;
      if (targetType == typeof(float))
        return 0f;
      throw new ArgumentNullException($"Unsupported type: {targetType.FullName}");
    }

    if (targetType == typeof(int))
      return ((IConvertible)value).ToInt32(culture);
    if (targetType == typeof(float))
      return ((IConvertible)value).ToSingle(culture);
    throw new ArgumentNullException($"Unsupported type: {targetType.FullName}");
  }
}
```

**Comment by cok666n** [comment]
Im not sure what you all are planning on this one, but I just wanted to point out I also stumbled upon it by binding (compiled binding) an int to the control (preview 8). Same issue though as the null value was passed to the non nullable int. 

My workaround was to allow for it in the VM, I made the public prop nullable. The backing field is still not nullable but I default it to 0, which works in this specific case.

**Comment by timunie** [comment]
Consider to make your property nullable for now. You can also use a converter it a  proxy property if that's not what you whish to have

**Comment by Developer-Alexander** [comment]
I would recommend at least putting that in the documentation.

**Comment by timunie** [comment]
I don't want to put it in docs, instead I want to find a valid fix.
