### ISSUE TITLE
Why Avalonia.Platform.Storage.IStorageItem.AbsolutePath  return garbled code

### ISSUE THREAD

**Issue by Zhou-Pixel** [AvaloniaUI/Avalonia#10805]
# Code 
```c#
        var ret = await StorageProvider.OpenFilePickerAsync(new FilePickerOpenOptions()
        {
            Title = "选择视频",
            FileTypeFilter = new[]
            {
                new FilePickerFileType("全部")
                {
                    Patterns = new []{"*"}
                }

            },
            AllowMultiple = false

        });
        if (ret.Count == 0) return;
        var file = ret[0].Path;
        Console.WriteLine(file);
        Console.WriteLine(file.AbsolutePath);
        Console.WriteLine(file.LocalPath);
```

# result
```
file:///Users/zhou/Downloads/测试中文名字.txt
/Users/zhou/Downloads/%E6%B5%8B%E8%AF%95%E4%B8%AD%E6%96%87%E5%90%8D%E5%AD%97.txt
/Users/zhou/Downloads/测试中文名字.txt
```

# Env
-  `macOS 12.6.4` `net6.0` `avalonia11-preview5`

**Comment by jp2masa** [comment]
That's how `Uri` works. You can use `Uri.UnescapeDataString(uri.AbsolutePath)` to get the desired result.

Additional info:

- https://stackoverflow.com/questions/436520/uri-absolutepath-messes-up-path-with-spaces
- https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYAMBYAUBgRjzwDcBDMAAgjAEtKBeSqAUwHdKBVOgCgCIAZrQA2LEAHpJnAM4sw08QC8AFgHsI4gCKq2UYarJwFgaVtAq9GBaOUDhpoFgVQOraAOmAAPYHwCUAbmL4CATh40tJ54qH4BdPYAggBG0qrCEMAsAApkwMrBPv7ctPacrNIAxmQADiyaaWQAysB0UADm4bkxcQlJqelumaH+gfYAMqrFwh0ZXrhAA==
