### ISSUE TITLE
ListBox will not show when visibility change while SizeToContent is active

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#10814]
**Describe the bug**
When a `ListBox` is visible in a `Window` with `SizeToContent` enabled, if it's hidden and reshown again it will not show.

**To Reproduce**

Create new Avalonia app with the following code -

MainWindow.axaml
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="Avalonia.ListBoxRepro.MainWindow"
        SizeToContent="Height"
        Title="Avalonia.ListBoxRepro">
    <StackPanel>
        <StackPanel Orientation="Horizontal">
            <Button Click="Hide">Hide</Button>
            <Button Click="Show">Show</Button>
        </StackPanel>
        <ListBox Name="ListBox">
            <ListBoxItem>Item 1</ListBoxItem>
            <ListBoxItem>Item 2</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 3</ListBoxItem>
            <ListBoxItem>Item 4</ListBoxItem>
        </ListBox>    
    </StackPanel>
    
</Window>
```

MainWindow.axaml.cs
```
      private void Hide(object? sender, RoutedEventArgs e)
        {
            this.FindControl<ListBox>("ListBox").IsVisible = false;
        }

        private void Show(object? sender, RoutedEventArgs e)
        {
            this.FindControl<ListBox>("ListBox").IsVisible = true;
        }
```

Click hide, then click show, the list box will not show again.

**Expected behavior**
ListBox (or any VirtualizingStackPanel usage) to show in this scenario.

**Additional context**
This seems to be due to `VirtualizingStackPanel`'s `MeasureOverride` not having any space to work with and then not generating any elements. I believe this should stay like this, but `MeasureOverride` should trigger again when the control becomes visible.
I can confirm it by manually calling ` this.FindControl<ListBox>("ListBox").ItemsPanelRoot.InvalidateMeasure()` after making it visible.

Not sure if it makes sense, but doing this change solves the issue - 
https://github.com/AvaloniaUI/Avalonia/blob/ee62816405916c1d8014b1121e1c206151e4c804/src/Avalonia.Controls/VirtualizingStackPanel.cs#L132-L135
to -
```
      protected override Size MeasureOverride(Size availableSize)
        {
            if (!IsEffectivelyVisible)
            {
                InvalidateMeasure();
                return default;
            }
```

**Comment by timunie** [comment]
> Not sure if it makes sense, but doing this change solves the issue -
[Avalonia/src/Avalonia.Controls/VirtualizingStackPanel.cs](https://github.com/AvaloniaUI/Avalonia/blob/ee62816405916c1d8014b1121e1c206151e4c804/src/Avalonia.Controls/VirtualizingStackPanel.cs#L132-L135)

@adirh3 I think this us worth a PR. Are you willing to provide one?

**Comment by adirh3** [comment]
> > Not sure if it makes sense, but doing this change solves the issue -
> > [Avalonia/src/Avalonia.Controls/VirtualizingStackPanel.cs](https://github.com/AvaloniaUI/Avalonia/blob/ee62816405916c1d8014b1121e1c206151e4c804/src/Avalonia.Controls/VirtualizingStackPanel.cs#L132-L135)
> 
> @adirh3 I think this us worth a PR. Are you willing to provide one?

Sure I didn't create one because I thought there is a PR freeze for non core members

**Comment by adirh3** [comment]
> @adirh3 for new features, yes. Bugfixes are still okay ;-)

Created - 
https://github.com/AvaloniaUI/Avalonia/pull/10828
So far, it's working without any issues in my app.

**Comment by grokys** [comment]
Reopened. Is it possible to reproduce at all with the original repro now? I didn't see any problems but didn't look too deeply after I saw the original problem was fixed. You may also want to try #10869 as that fixes a few more problems with the virtualizing panel.

**Comment by adirh3** [comment]
@grokys sorry I didn't have time lately. I just checked with latest master, and the bugs are extreme.
I can't repro in ControlCatalog, but I believe most of the bugs happen when you hide/show the window/control.

Hopefully I will have more time today to make a repro for all the issues, but either way I suggest you take a deeper look into cases where ItemsSource is changed rapidly or the ObservableCollection has many changes consequently.

**Comment by adirh3** [comment]
@grokys Found a way to repro -

Main Window -
```
  <StackPanel>
        <StackPanel Orientation="Horizontal">
            <Button Click="Hide">Hide</Button>
            <Button Click="Show">Show</Button>
            <Button Click="Randomize">Randomize</Button>
        </StackPanel>
        <ListBox Name="ListBox" ItemsSource="{Binding Items}"/>    
    </StackPanel>
``` (no need for sizetocontent)

View model -
```
    public ObservableCollection<string> Items
    {
        get => _items;
        set
        {
            _items = value; 
            OnPropertyChanged();
        }
    }
```

Main window cs -
```
   private void Hide(object? sender, RoutedEventArgs e)
    {
        this.FindControl<ListBox>("ListBox").IsVisible = false;
    }

    private void Show(object? sender, RoutedEventArgs e)
    {
        this.FindControl<ListBox>("ListBox").IsVisible = true;
    }

    private void Randomize(object? sender, RoutedEventArgs e)
    {
        var random = new Random();
        int next = random.Next(0,100);
        var mainWindowViewModel = (ViewModels.MainWindowViewModel)DataContext;
        mainWindowViewModel.Items = new ObservableCollection<string>();
        for (int i = 0; i < next; i++)
        {
            mainWindowViewModel.Items.Add(i.ToString());
        }
    }
```

Repro -
1. Click randomize 
2. Click hide
3. Click randomize 
4. Click show

ListBox will not be visible now. (repeat these multiple times if it doesn't happen at first)

**Comment by grokys** [comment]
> Edit - Seems like https://github.com/AvaloniaUI/Avalonia/pull/11127 fixes the issue in the repro.

Great! I'll close this issue when that PR gets merged then.

**Comment by adirh3** [comment]
@grokys @maxkatz6 thanks as always!
Unfortunately, seems like the issue wasn't solved completely, but it happens rarely now -

![image](https://user-images.githubusercontent.com/27368554/235307801-3e090010-0730-4a1f-bc44-d8fa37c151d8.png)
![image](https://user-images.githubusercontent.com/27368554/235307981-60a2c160-db49-47d4-a9ef-5e88858b29ac.png)

I'm not sure if it is related to `SizeToContent` anymore, it's just that `ListBoxItem`s disappear randomly.
Hard to repro even in Fluent Search, will try to figure out how to repro it and will update here.
