### ISSUE TITLE
Application throws exception when the namespace and the project name are different

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#1081]
For example, creating a .NET Core project with the name "my-project" will generate a project where the namespace is "my_project". The application doesn't run with the exception: "System.IO.FileNotFoundException: Unable to find view for my_project.App". The same exception occurs in the designer.

**Comment by kekekeks** [comment]
Your assembly name doesn't match the file name, which in turn breaks assembly loading conventions. Don't do that, it will break other things in .NET ecosystem.

**Comment by jp2masa** [comment]
The assembly name matches the file name. I tried changing the AssemblyName property in the csproj file to a name with a dash and it compiled and ran correctly (the file name contains the dash). But if I change the project name to a name with a dash, the assembly name still matches the file name, but it doesn't run.

**Comment by kekekeks** [comment]
It also makes your namespace not match dll name, messes up with resource names, etc. Don't do that. Use alphanumeric characters in namespace and assembly names
