### ISSUE TITLE
ListBox inside Scrollviewer cause crash

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#10825]
**Describe the bug**
When ListBox are scrolled in and out of Scrollviewer visible area, app crash with exception 
System.InvalidOperationException: 'The control already has a visual parent.'

**To Reproduce**

1. Clone https://github.com/rabbitism/ListBoxCrashDemo
2. Run App
3. Scroll up and down

**Expected behavior**
Nothing should happen

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0-preview6

**Additional context**
I think this is ScrollViewer issue. I also encountered similar issue when change theme of a control with ScrollViewer in control template. I will prepare another sample if I can reproduce.

**Comment by timunie** [comment]
@rabbitism simple but great sample. I just tried it in the sandbox App and it also can be reproduced there. It's enough to copy this into `MainWindow.axaml`: 

```xml
<Grid Margin="20">
    <ScrollViewer
        Name="scroll"
        HorizontalScrollBarVisibility="Visible"
        IsScrollInertiaEnabled="True"
        VerticalScrollBarVisibility="Visible">
        <StackPanel>
            <Border
                Width="300"
                Height="300"
                Background="LightBlue" />
            <ListBox>
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
                <TextBlock Text="111" />
            </ListBox>
        </StackPanel>
    </ScrollViewer>
</Grid>
```

**Comment by grokys** [comment]
@rabbitism I wonder if you could give #10892 a try and see if it fixes your issue, or introduces any new issues?

**Comment by rabbitism** [comment]
@grokys Thanks for your fix. It works as expected now.
