### ISSUE TITLE
textbox can not input chinese words

### ISSUE THREAD

**Issue by ptpt666** [AvaloniaUI/Avalonia#10829]
**Describe the bug**
There's an Chinese input method bug when i tried the version 11.0.0-preview6.
When using the Sogou input method, the textbox cannot input Chinese. When using the Microsoft Pinyin input method, the textbox can input Chinese. However, using these two input methods, the textbox cannot input punctuation such as commas (,) periods (.).

**To Reproduce**

1. Run my test app
2. Focus a textbox
3. Switch my input method to Sogou input method,textbox can not input chinese words and punctuation
4. Switch my input method to Microsoft Pinyin input method,textbox can input chinese words but can not input punctuation

**Expected behavior**
i hope that i can input any words with any chinese input method

**Desktop (please complete the following information):**

- OS: OS: Windows 19042
- Version 11.0.0-preview6

**Comment by rabbitism** [comment]
I can confirm this, cannot input most punctuations either.
