### ISSUE TITLE
Preview6: Dictionary bound to ListBox or ItemsControl not shown

### ISSUE THREAD

**Issue by Sputnik24** [AvaloniaUI/Avalonia#10823]
**Describe the bug**
I have a ListBox or ItemsControl in a View and Items property binds to a Dictionary in the ViewModel. The Dictionary is populated in the ViewModel code and optionally RaisePropertyChanged(nameof(DictionaryProperty)) is called in case Dictionary is populated/changed after ctor.

**To Reproduce**
Steps to reproduce the behavior. Please note that this is a very simple example not using DataTemplate to show Key and Value of DictionaryItem, but issue occurs regardless of that.

View:
`<ListBox Items="{Binding TestList}" />`

ViewModel:
```csharp
private Dictionary<string, string> _testList = new() { {"Foo", "Bar"} };
public Dictionary<string, string> TestList => _testList;
```

**Expected behavior**
Dictionary items shall show in ListBox.

**Desktop (please complete the following information):**

- OS: Windows 10 21H2
- Version 11.0.0.-preview6

**Additional context**
Was working in preview5 and previous. Binding to DataGrid, it is still working.

**Comment by rabbitism** [comment]
There is a change in preview6, you should bind to ItemsSource.

**Comment by Sputnik24** [comment]
Thanks a lot. It is working. Issue which is not an Issue can be closed.
