### ISSUE TITLE
TextBlock: TextAlignment != Left conflicts with Padding

### ISSUE THREAD

**Issue by tbolon** [AvaloniaUI/Avalonia#10852]
**Describe the bug**
When using a TextBlock with a TextAlignment set at `Center` or `Right` and applying any padding on all directions, the text will not be correctly rendered:

* When `TextAlignment ="Center"` text will be centered then shifted right by the amount of padding
* When `TextAlignment ="Right"` text will be centered then shifted right by the amount of padding, resulting in truncation.

**To Reproduce**

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="MyAvaloniaApp.MainWindow"
        Title="MyAvaloniaApp">
  <StackPanel>
    <TextBlock TextAlignment="Left" Padding="10" Background="Red">Hello</TextBlock>
    <TextBlock TextAlignment="Left" Padding="0">Hello</TextBlock>
    <TextBlock TextAlignment="Left" Margin="0">Hello</TextBlock>
    <TextBlock TextAlignment="Center" Padding="10" Background="Red">Hello</TextBlock>
    <TextBlock TextAlignment="Center" Padding="0">Hello</TextBlock>
    <TextBlock TextAlignment="Center" Margin="0">Hello</TextBlock>
    <TextBlock TextAlignment="Right" Padding="10" Background="Red">Hello</TextBlock>
    <TextBlock TextAlignment="Right" Padding="0">Hello</TextBlock>
    <TextBlock TextAlignment="Right" Margin="0">Hello</TextBlock>
  </StackPanel>
</Window>
```

<img width="625" alt="image" src="https://user-images.githubusercontent.com/127185/228770263-16a0d1b0-f94e-467b-993c-93bd14ad26cd.png">

**Expected behavior**

When text is centered, the text should remain centered even when padding is applied both left and right by the same value.

When text is aligned to the right, the text should remain visible and aligned to the right, padded by the value specified on right.

WPF rendering for comparison:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/127185/228772457-edd57415-018c-444b-9d80-988a73d6d848.png">

**Desktop (please complete the following information):**

- OS: Win11
- Version: 0.10.18

**Comment by timunie** [comment]
This issue seems to be fixed in upcomming v11: 

![image](https://user-images.githubusercontent.com/47110241/228772169-ff84a6b8-4a7a-46e5-936e-5031a87a56a8.png)

0.10.x will most likely not get huge updates as 11.0 RC is close. Thank you for your understanding.

**Comment by tbolon** [comment]
No problem, I was just trying to reproduce it using the source code directly, you helped me save some time :)
