### ISSUE TITLE
"Member 'Color/Cursor/Thickness' is declared in another module and needs to be imported" for generic MarkupExtension

### ISSUE THREAD

**Issue by graealex** [AvaloniaUI/Avalonia#10856]
**Describe the bug**
Using a generic MarkupExtension that uses an Avalonia-internal type like Color, Cursor or Thickness throws an error during compilation:

`{local:Conditional, Path=#MyCheckbox.IsChecked, True=Green, False=Red, x:TypeArguments=Color}`

_MSBUILD : Avalonia error AVLN: 9999: System.ArgumentException: Member 'Avalonia.Media.Color' is declared in another module and needs to be imported [C:\Work\Avalonia\samples\Sandbox\Sandbox.csproj]_

**To Reproduce**
Use the attached SandBox/minimal project to reproduce (MainWindow.axaml)

**Expected behavior**
The MarkupExtension should work in the same way as it does with System.* types like Boolean or String.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11 preview 6

**Additional context**
[Sandbox.zip](https://github.com/AvaloniaUI/Avalonia/files/11112124/Sandbox.zip)

**Comment by timunie** [comment]
Related? #8789

**Comment by maxkatz6** [comment]
Reopening, as Avalonia doesn't yet use this XamlX build.
