### ISSUE TITLE
Custom font crash on Android

### ISSUE THREAD

**Issue by czendoo** [AvaloniaUI/Avalonia#10855]
The following xaml code is working fine on desktop, but it's crashing on Android:

`<TextBlock FontFamily="/Assets/Fonts/Font Awesome 6 Free-Solid-900.otf#Font Awesome 6 Free Solid">&#xf013;</TextBlock>`

The following variant crashes too on Android:

`<TextBlock FontFamily="avares://AvaloniaTest/Assets/Fonts/Font Awesome 6 Free-Solid-900.otf#Font Awesome 6 Free Solid">&#xf013;</TextBlock>`

**Exception thrown**
System.InvalidOperationException: 'Could not create glyphTypeface.'

**Tested versions**
11.0.0-preview6
11.0.0-preview5
Android Emulator (Android 11 API 30)

**Comment by emmauss** [comment]
Could you provide a repro?

**Comment by czendoo** [comment]
> Could you provide a repro?

https://github.com/czendoo/AvaloniaFontTest.git

Thank you!

**Comment by emmauss** [comment]
> > Could you provide a repro?
> 
> https://github.com/czendoo/AvaloniaFontTest.git
> 
> Thank you!

From investigations, the font typeface name retrieved on desktop and mobile are different. This isn't from our implementation, but from skia. You can load your font on both desktop and mobile using this name, `Font Awesome 6 Free` instead of `Font Awesome 6 Free Solid`

**Comment by czendoo** [comment]
> From investigations, the font typeface name retrieved on desktop and mobile are different. This isn't from our implementation, but from skia. You can load your font on both desktop and mobile using this name, `Font Awesome 6 Free` instead of `Font Awesome 6 Free Solid`

I can confirm the other typeface name on Android works. It would be nice to find way how to unify it though. Thank you.

**Comment by 13xforever** [comment]
I have the same issue, except I need to use both the regular version and solid. On Windows desktop two font files have different family names as expected, but on Linux they're merged together, and you can only access the regular style.

**Comment by emmauss** [comment]
> I have the same issue, except I need to use both the regular version and solid. On Windows desktop two font files have different family names as expected, but on Linux they're merged together, and you can only access the regular style.

If this is not related to Android, open a new issue and post a small sample that reproduces the issues.

**Comment by 13xforever** [comment]
The issue is exactly the same between android and linux
