### ISSUE TITLE
IME and TabTip.exe not working in some case

### ISSUE THREAD

**Issue by flier268** [AvaloniaUI/Avalonia#10862]
**Describe the bug**
When I use the Chinese input method, if I press Backspace, I won't be able to input any characters. After selecting a word, the text is sent out, but Avalonia does not receive it (or it does not appear on the TextBox). The current workaround is to press Space once when this happens, and then it will resume normal operation.

**To Reproduce**

1. put a TextBox on UI
2. Debug
3. Open TabTip.exe
4. Click backspace
5. Enter some text using an input method editor (IME) such as Zhuyin (Bopomofo) input method.
6. The char does not appear

**Expected behavior**
The text appears in the TextBox when entered using an IME such as Zhuyin Input Method.

**Desktop (please complete the following information):**

- OS: Windows 10 21H2
- Version 11.0.0-preview6

**Additional context**

**Comment by rabbitism** [comment]
Can you provide some information about TapTip?

**Comment by hez2010** [comment]
Can you try the latest nightly build?

**Comment by kyuranger** [comment]
> Can you provide some information about TapTip? Edit: this might have been fixed by #10834

I tested with Sogou input method and I found this bug only available in Preview 6(But Preview 5 works well). In Preview 6 Sogou IME can not input anything no matter whether you input Backspace.

OS: Windows 10 22H2 19045.2728

**Comment by timunie** [comment]
@kyuranger please try latest nightly. https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

**Comment by flier268** [comment]
i will try it in 4 days, thanks.

**Comment by timunie** [comment]
@flier268 all right. Please close this issue if it is also for you fixed. Have a good time.

**Comment by flier268** [comment]
@timunie It does not fix
![Keyboard](https://user-images.githubusercontent.com/19989232/230255511-02a9415a-dcd9-4d4e-8704-ea0fc9008250.gif)


Avalonia version:11.0.999-cibuild0032880-beta

**Comment by Gillibald** [comment]
Bopomofo is special in terms of committing the composition string. How do you usually finish a sequence and start typing a new one? Some IMEs use the space key and some the return key.

**Comment by flier268** [comment]
It does not have a special key to finish. The traditional approach is to press " ", "ˊ", "ˇ", "ˋ", "·" to finish it, but there are some new methods to do that. 
For example, if I want to input "你好", I should type "ㄋㄧˇㄏㄠˇ", but in some cases, I can just type "ㄋㄏ", and then choose the first one on the bar.

**Comment by danipen** [comment]
@flier268 @Gillibald is this issue still alive in the latest changes/preview8?

**Comment by flier268** [comment]
> @flier268 @Gillibald is this issue still alive in the latest changes/preview8?

Thank you, @danipen. This issue has indeed been fixed in version 11.0.999-cibuild0034558-beta.
