### ISSUE TITLE
When the OpenGlControlBase control is instantiated, the on OpenGlInit method will be executed twice.(11.0.0-Preview-6)

### ISSUE THREAD

**Issue by qqJoker** [AvaloniaUI/Avalonia#10905]
**Describe the bug**
When the control inherited from Avalonia.OpenGL.Controls.OpenGlControlBase is initialized, the OnOpenGlInit() method will be executed repeatedly

**To Reproduce**

1.Create a new control and inherit from OpenGlControlBase
2.Initialize controls
3.See...

**Expected behavior**
Should execute OnOpenGlInit repeatedly

**Screenshots**
![图片](https://user-images.githubusercontent.com/25498939/229749542-1deafb4c-7152-44b7-bb05-8783446a2039.png)

**Desktop (please complete the following information):**

- OS: Windows 10 LTSC

**Comment by jp2masa** [comment]
#10371
