### ISSUE TITLE
[Browser] Pointer capture not released when pointer up outside of browser

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#10904]
**Describe the bug**
Pointer capture is not released when pointer was captured inside the render area of the browser, but release outside the render area. For example, when dragging the thumb of the slider.

**To Reproduce**
(in browser only)
1. Keep the mouse button pressed on a slider's thumb.
2. Move the mouse outside of the render area of the browser.
3. Release the mouse button
4. Move the mouse inside the render area of the browser.
5. The slider thumb is still moving because pointer up has not been handled. 

**Expected behavior**
Pointer must be released.

- OS: Windows 10, Edge browser
- Version 11 preview6

Not sure it is possible to fix, but I report as it may be anoying for users.

**Comment by TomEdwardsEnscape** [comment]
Can you still reproduce this issue with the changes from #13489?

**Comment by dbriard** [comment]
> Can you still reproduce this issue with the changes from #13489?

Thank you, I'll try to install the latest nighly build tomorrow to test.

**Comment by dbriard** [comment]
> Can you still reproduce this issue with the changes from #13489?

Yes, sorry, I just retested in Chrome and Edge with latest nightly, and this issue is not fixed.
