### ISSUE TITLE
Set SharedSizeGroup in code not work

### ISSUE THREAD

**Issue by Flithor** [AvaloniaUI/Avalonia#10907]
as title.
Parent panel set `IsSharedSizeScope` as `true` not work too.
Looks change the `SharedSizeGroup` or set `IsSharedSizeScope` not call this method again.
 https://github.com/AvaloniaUI/Avalonia/blob/ec6cd48de9408cb39b12f52cf4af708a93e42988/src/Avalonia.Controls/DefinitionBase.cs#L33

**Comment by timunie** [comment]
Works for me: 

false: 
![image](https://user-images.githubusercontent.com/47110241/229790986-1520361c-ce25-467e-abe0-203216e49ccf.png)

true:
![image](https://user-images.githubusercontent.com/47110241/229791037-64417b97-306e-40cb-ba3e-19a576841b90.png)


Here is the repo: 

```xml
<StackPanel Spacing="5" Grid.IsSharedSizeScope="{Binding #TglSharedGrid.IsChecked}">
    <ToggleButton x:Name="TglSharedGrid">Toggle me</ToggleButton>

    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto" SharedSizeGroup="A"></ColumnDefinition>
            <ColumnDefinition Width="*"></ColumnDefinition>
        </Grid.ColumnDefinitions>
        <TextBlock>Hello World</TextBlock>
        <Border Grid.Column="1" Background="Aqua" Margin="2"></Border>
    </Grid>
    
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto" SharedSizeGroup="A"></ColumnDefinition>
            <ColumnDefinition Width="*"></ColumnDefinition>
        </Grid.ColumnDefinitions>
        <TextBlock>Foo</TextBlock>
        <Border Grid.Column="1" Background="Aqua" Margin="2"></Border>
    </Grid>
    
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto" SharedSizeGroup="A"></ColumnDefinition>
            <ColumnDefinition Width="*"></ColumnDefinition>
        </Grid.ColumnDefinitions>
        <TextBlock>Bar</TextBlock>
        <Border Grid.Column="1" Background="Aqua" Margin="2"></Border>
    </Grid>
    
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto" SharedSizeGroup="A"></ColumnDefinition>
            <ColumnDefinition Width="*"></ColumnDefinition>
        </Grid.ColumnDefinitions>
        <TextBlock>Foo Bar</TextBlock>
        <Border Grid.Column="1" Background="Aqua" Margin="2"></Border>
    </Grid>
</StackPanel>
```

If that is not your issue, please provide more info and attach or link a simple sample to reproduce the issue. 

NOTE: Next time please respect the issue templates we have. They are there for a reason.

**Comment by Flithor** [comment]
Close this and reopen a new one.

**Comment by peter0302** [comment]
@timunie your example verbatim doesn't work.

![image](https://github.com/AvaloniaUI/Avalonia/assets/9038131/3c022507-1c00-4ccb-b7da-337b985be93f)

**Comment by malex81** [comment]
This example work correctly. But if you add one more Grid in code? this new grids not work!
