### ISSUE TITLE
Cannot select text in multi-line SelectableTextBlock easily

### ISSUE THREAD

**Issue by ivanjx** [AvaloniaUI/Avalonia#10913]
**Describe the bug**
I dont really know how to explain the bug but it is difficult to select text manually in a `SelectableTextBlock` that has multiple lines in it. See the video below.

**To Reproduce**

1. Add a `SelectableTextBlock`.
2. Add some texts with multiple line.
3. Try to select the text as shown in the video.

**Expected behavior**
Can easily select the text inside the control as shown with Notepad in the latter part of the video below.

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.999-cibuild0032750-beta

**Additional context**
[Sample project](https://github.com/AvaloniaUI/Avalonia/files/11156598/App.zip)

https://user-images.githubusercontent.com/12814796/230022153-e57ba4b2-832b-4f1c-ae6e-7e0ddd2533eb.mp4

**Comment by diogotr7** [comment]
I am also experencing this. I've made a video that shows another scenario with unexpected behavior, it's easily seem with alternating lines of different widths. I've also included the same movements in a notepad++ window as a way to show expected (at least to me) behavior.

https://github.com/AvaloniaUI/Avalonia/assets/29486064/c85ec6f5-8d11-46df-a0f8-25ccf3a886af

The app used is the sample project provided by the OP, with just the text in some of the lines made wider to properly show the issue.

**Comment by maxkatz6** [comment]
@diogotr7 please make sure that SelectabeTextBlock has a background, at least Transparent. (from the video I am not sure if it's a Border behind or not).

**Comment by diogotr7** [comment]
@maxkatz6 Here's the axaml from the video:
```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication.MainWindow"
        Title="AvaloniaApplication">

	<Border HorizontalAlignment="Center"
			VerticalAlignment="Center"
			Width="300"
			BorderThickness="1"
			BorderBrush="Black">
		<SelectableTextBlock Background="LightGray">
			<Run>Hello World!Hello World!Hello World!Hello World!</Run>
			<LineBreak/>
			<Run>Hello World!</Run>
			<LineBreak/>
			<Run>Hello World!Hello World!Hello World!Hello World!</Run>
			<LineBreak/>
			<Run>Hello World!</Run>
			<LineBreak/>
			<Run>Hello World!Hello World!Hello World!Hello World!</Run>
			<LineBreak/>
			<Run>Hello World!</Run>
			<LineBreak/>
			<Run>Hello World!Hello World!Hello World!Hello World!</Run>
			<LineBreak/>
			<Run>Hello World!</Run>
			<LineBreak/>
		</SelectableTextBlock>
	</Border>
</Window>
```

There's a border and a Background. Should i try with any other change?

**Comment by BAndysc** [comment]
+1 it is pretty annoying. Anyway, thank you a lot for the text rework in Avalonia 11, including new SelectableTextBlock :)

**Comment by Gillibald** [comment]
Fixed in current master
