### ISSUE TITLE
HeaderedContentControl default theme missing

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#10918]
**Describe the bug**
There is a default theme for ContentControl, but not for HeaderedContentControl.

**To Reproduce**
1. Create a <HeaderedContentControl><TextBlock Text="MyText"/><HeaderedContentControl> in XAML
2. Nothing appear in the view, because there is no default theme.

**Expected behavior**
I would like to have a default theme for HeaderedContentControl that look like the Header of many controls in UWP (Slider, TextBox, etc...) so that I can quickly add Headers to Avalonia Controls out of the box without the need to create my own theme.

Ideally, the header should have normal and disabled state (Grayed Header foreground), TopHeaderMargin such as 0,0,0,8 by default, and might have a different Margin in case the content is a Slider (for example) if the default margin do not look good with Slider (just an example, I know that UWP may have different margin for special cases).

**Comment by rabbitism** [comment]
I think this is discussed in https://github.com/AvaloniaUI/Avalonia/pull/3913

**Comment by dbriard** [comment]
> I think this is discussed in #3913

Yes, but with no explanation why this control do not have a template at all. It is not a problem in any way, but I just do not see any cons of adding a theme for that control that would look like headered control of WinUI/UWP way.

As a user, that look strange the first time you add it in XAML and nothing happen. I had to look at the code of Fluent theme to figure out why...
