### ISSUE TITLE
Unable to build app using 11.0 Preview 6 with .NET 6 SDK

### ISSUE THREAD

**Issue by jonthysell** [AvaloniaUI/Avalonia#10911]
**Describe the bug**

I have an app project targeting .NET 6. If I build on my local machine (which has the .NET 7 SDK installed) everything builds fine. However, if I build in CI, with just the .NET 6 SDK installed, it looks like the codegen/code-behind for partial controls doesn't run.

Running `dotnet build -v d --configuration Debug ./Mzinga.sln`:

```
"C:\Users\Jon\Documents\Code\Mzinga\src\Mzinga.sln" (default target) (1:2) ->
 "C:\Users\Jon\Documents\Code\Mzinga\src\Mzinga.Viewer\Mzinga.Viewer.csproj" (default target) (7:6) ->
 (CoreCompile target) ->
   CSC : warning CS9057: The analyzer assembly 'C:\Users\Jon\.nuget\packages\avalonia\11.0.0-preview6\analyzers\d
 otnet\cs\Avalonia.Generators.dll' references version '4.4.0.0' of the compiler, which is newer than the currentl
 y running version '4.3.0.0'. [C:\Users\Jon\Documents\Code\Mzinga\src\Mzinga.Viewer\Mzinga.Viewer.csproj]
   CSC : warning CS9057: The analyzer assembly 'C:\Users\Jon\.nuget\packages\tmds.dbus.sourcegenerator\0.0.4\anal
 yzers\dotnet\cs\Tmds.DBus.SourceGenerator.dll' references version '4.4.0.0' of the compiler, which is newer than
  the currently running version '4.3.0.0'. [C:\Users\Jon\Documents\Code\Mzinga\src\Mzinga.Viewer\Mzinga.Viewer.cs
 proj]

 "C:\Users\Jon\Documents\Code\Mzinga\src\Mzinga.sln" (default target) (1:2) ->
 "C:\Users\Jon\Documents\Code\Mzinga\src\Mzinga.Viewer\Mzinga.Viewer.csproj" (default target) (7:6) ->
 (CoreCompile target) ->
   C:\Users\Jon\Documents\Code\Mzinga\src\Mzinga.Viewer\Views\AboutWindow.axaml.cs(29,13): error CS0103: The name
  'InitializeComponent' does not exist in the current context [C:\Users\Jon\Documents\Code\Mzinga\src\Mzinga.View
 er\Mzinga.Viewer.csproj]
```

So when I call `InitializeComponent` in the generated code-behind, it doesn't exist.

From https://github.com/jonthysell/Mzinga/pull/119

**To Reproduce**

I can force `dotnet` to use .the .NET 6 SDK by creating a `global.json` file with:

```json
{
  "sdk": {
    "version": "6.0.407"
  }
}
```

**Expected behavior**
The build completes.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 11.0.0-preview6

**Additional context**
N/A

**Comment by rabbitism** [comment]
This is fixed in https://github.com/AvaloniaUI/Avalonia/pull/10775

**Comment by timunie** [comment]
@jonthysell as you reacted with 👍 I assume your issue is solved. For that reason I'll close this issue. Feel free to ping me and I'll reopen, if your issue is not solved in latest nightly builds.
