### ISSUE TITLE
How to get the handle of the Avalonia control？

### ISSUE THREAD

**Issue by staneee** [AvaloniaUI/Avalonia#1091]
I would like to get Avalonia control handle, such as Canvas handle, I want to put it into the cpp dll for some processing, in WPF I can use:

`IntPtr hwnd = ((HwndSource) PresentationSource.FromVisual (uielement)). Handle;`

But in Avalonia how to get it?

**Comment by kekekeks** [comment]
`((TopLevel)control.GetVisualRoot()).PlatformImpl.Handle.Handle`.

`GetVisualRoot` is extension method from `Avalonia.VisualTree` namespace

**Comment by DhananjayHuidrom** [comment]
((TopLevel)control.GetVisualRoot()).PlatformImpl.Handle.Handle works in window but failed 

Error in centOS: Unable to cast object of type 'Avalonia.X11.X11Window' to type 'Avalonia.Win32.WindowImpl'

**Comment by kekekeks** [comment]
Why are you casting it to `Avalonia.Win32.WindowImpl`?

**Comment by DhananjayHuidrom** [comment]
Thanks kekekeks, I have created a project of Avalonia app with one window (xaml) and assigned the handle of this window to get a stream from an IP camera in below code and it is working in windows OS and got the casting error in centOS. 

//login to camera 
IntPtr loginID = NETClient.Login("cameraIp", 25001, "username", "password",EM_LOGIN_SPAC_CAP_TYPE.TCP, IntPtr.Zero, ref deviceInfo);
if (loginID != IntPtr.Zero)
{
                 // get the handle of current current
                  var handle = this.PlatformImpl.Handle.Handle;

                 //passing this handle to update live streaming of camera
                    IntPtr realHandle = NETClient.StartRealPlay(loginID, 0, handle, 0, m_RealDataCallBack, m_RealPlayDisConnectCallBack, IntPtr.Zero, 3000);
                    if (realHandle != IntPtr.Zero)
                    {                            

                    }
                }

**Comment by Gao996** [comment]
```C#
var toplevel = (TopLevel)this.GetVisualRoot();

var platformImpl = (WindowImpl)toplevel.PlatformImpl;

var handle = platformImpl.Handle.Handle;
```

**Comment by tms320** [comment]
Methods above don't work for me.

`((TopLevel)control.GetVisualRoot()).PlatformImpl.Handle.Handle`
gives error:
'ITopLevelImpl' does not contain a definition for 'Handle'

This code:
```
var toplevel = (TopLevel)this.GetVisualRoot();
var platformImpl = (WindowImpl)toplevel.PlatformImpl;
var handle = platformImpl.Handle.Handle;
```
gives error:
The type or namespace name 'WindowImpl' could not be found
I replaced `WindowImpl` with `IWindowImpl`, it gives error:
'IWindowBaseImpl.Handle' is inaccessible due to its protection level

**Comment by jp2masa** [comment]
https://docs.avaloniaui.net/docs/next/stay-up-to-date/upgrade-from-0.10#windows
