### ISSUE TITLE
Pinch Gesture on Mac with trackpad

### ISSUE THREAD

**Issue by Tenjim** [AvaloniaUI/Avalonia#10921]
**Describe the bug**
With ControlCatalog.NetCore projet from sample, I have tried to use pinch with two finger on trackpad to zoom in and zoom out from an image with PinchGestureRecognizer

**To Reproduce**

1. Go to ControlCatalog.NetCore sample
2. Run the sample and go to Gesture page
3. Try to use pinch gesture with two finger to zoom in and zoom out from the image

**Desktop (please complete the following information):**

- OS: Mac OS Ventura 13.2
- Version 11 preview 6 (or master branch)

**Comment by maxkatz6** [comment]
PinchGestureRecognizer is for touch input. Trackpad is not a touch input, but a "mouse".
For the trackpad specifically there is a dedicated [PointerTouchPadGestureMagnifyEvent](https://github.com/AvaloniaUI/Avalonia/blob/ec6cd48de9408cb39b12f52cf4af708a93e42988/src/Avalonia.Base/Input/Gestures.cs#L56) event
