### ISSUE TITLE
ComboBox is unclickable

### ISSUE THREAD

**Issue by gdir2110** [AvaloniaUI/Avalonia#10925]
**Describe the bug**
I can't click on the ComboBox. If I select the ComboBox using the Tab key, then I am able to select an item using the Up/Down keys. Either way, if I click on the ComboBox, nothing happens. I made sure that it IsEnabled is `true`

**To Reproduce**
Create a new ComboBox and populate it with anything

**Expected behavior**
When I click on the ComboBox I aspect a drop-down menu/list to appear.

**Screenshots**
No screenshots, but I added a recording.

**Desktop:**

- OS: Mac
- Version Ventura 13.3

**Additional context**

[Recording](https://user-images.githubusercontent.com/127754978/230239406-057b4e9c-13ee-47dc-8dc7-fdd7f70ba3e6.mov)
[Code](https://github.com/AvaloniaUI/Avalonia/files/11165075/Problema5.zip)

**Comment by timunie** [comment]
Can you try it using a fresh new sample App with just a ComboBox in it?

**Comment by gdir2110** [comment]
> Can you try it using a fresh new sample App with just a ComboBox in it?

I tried it, no luck. I will add the sample code I used.

[Code](https://github.com/AvaloniaUI/Avalonia/files/11173386/AvaloniaApplication1.zip)

**Comment by timunie** [comment]
Works using Windows. I can't say much about MacOS. Can you try latest 11.0 preview 6 with your sample?

**Comment by nikita-myr** [comment]
I have exactly the same problem. Have you been unable to find a solution?

**Comment by maxkatz6** [comment]
@timunie no, I can't reproduce it on my mac.

**Comment by nikita-myr** [comment]
My problem was solved after a clean reinstall and update for last version of all frameworks (Xamarin, Mono,  .Net)
