### ISSUE TITLE
IME won't work before switching to a new IME

### ISSUE THREAD

**Issue by hez2010** [AvaloniaUI/Avalonia#10934]
**Describe the bug**
IME won't work before switching IME

**To Reproduce**

1. Run CC.NetCore
2. Switch to a CJK IME
3. Navigate to the TextBox page and try to type something in a TextBox without switching IME again
4. You will observe that the IME input doesn't work

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0.0 preview 6

**Additional context**

**Comment by Gillibald** [comment]
I can't find any issue. When I switch to traditional Chinese IME I always had to press shift first to be able to compose something. This works the same with all applications.

**Comment by hez2010** [comment]
It seems that it doesn't repro again in preview 7. I'm closing the issue.
