### ISSUE TITLE
Drop Down mouse click is processed on controls beneath the dropdown list.

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1094]
If you open a drop down, and the list covers controls.

When you select an item, the click gets handled by the control beneath as well.

**Comment by grokys** [comment]
I tried adding a click handler to the `DropDown` page in ControlCatalog and couldn't repro. Any chance of a minimal repro?

**Comment by MarchingCube** [comment]
It seems that I have encountered the same bug. Prepared small repro here: [https://github.com/MarchingCube/DropDownRepro](https://github.com/MarchingCube/DropDownRepro).

![dropdownrepro](https://user-images.githubusercontent.com/2588062/38671196-1266f82a-3e4b-11e8-94dd-939563eea85c.gif)

**Comment by grokys** [comment]
Fixed by #1492.
