### ISSUE TITLE
[Compiled Bindings] DataContext type should be inferred when using named elements in bindings

### ISSUE THREAD

**Issue by Mrxx99** [AvaloniaUI/Avalonia#10957]
**Is your feature request related to a problem? Please describe.**
When binding to the DataContext of a named element, and that named element has the x:DataType set, the ugly looking casts should not be required in XAML.

**Describe the solution you'd like**
The type of the DataContext should be inferred from the named elements x:DataType (if present), so the casts could be omitted.

**Describe alternatives you've considered**
Still using the verbose casts even all information would be present to not need them.

**Additional context**
Example:
When having code like this:
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:AvaloniaCompiledBindings.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaCompiledBindings.Views.MainWindow"
        x:DataType="vm:MainWindowViewModel"
        Icon="/Assets/avalonia-logo.ico"
        x:Name="root"
        Title="AvaloniaCompiledBindings">

    <Design.DataContext>
        <!-- This only sets the DataContext for the previewer in an IDE,
             to set the actual DataContext for runtime, set the DataContext property in code (look at App.axaml.cs) -->
        <vm:MainWindowViewModel/>
    </Design.DataContext>

  <ItemsControl ItemsSource="{Binding Items}">
    <ItemsControl.ItemTemplate>
      <DataTemplate>
        <Button Content="{Binding}"
                Command="{Binding #root.((vm:MainWindowViewModel)DataContext).Greet}"
                CommandParameter="{Binding}"
                />
      </DataTemplate>
    </ItemsControl.ItemTemplate>
  </ItemsControl>

</Window>
```

With this feature the binding could be reduce to this (because Window has x:DataType set):
`Command="{Binding #root.DataContext.Greet}"`

(Ideally there would also be intellisens completion with that datatype, but that is for the IDE extensions)

**Comment by maxkatz6** [comment]
I like the idea. Should be possible by modifying this compiler transformer https://github.com/AvaloniaUI/Avalonia/blob/master/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlDataContextTypeTransformer.cs
