### ISSUE TITLE
DataGrid - Items don't update properly

### ISSUE THREAD

**Issue by erythana** [AvaloniaUI/Avalonia#10965]
Hello! I'm having troubles with the DataGrid and i think im using it correctly. Any advice welcome.

**Describe the bug**
I have a DataGrid, the ItemsGrid Property is bound to an ObservableCollection (also tried a custom one with the additional collectionchanged implementation).
When i call a "Clear()" and then add items to the collection, they don't show properly in the grid (see reproduce)

**To Reproduce**
https://github.com/erythana/DataGridMinimalExample - MVVM Template, sorry for that. Just check the MainWindow and the MainWindowViewModel

Create a DataGrid and bind it to a ObservableCollection
Clear the ObservableCollection and Add Items (either with AddRange or when you iterate over it and add one by one)
This works as long as you don't try to add more items than previously added. EXCEPT you never call Clear (or, remove one by one either)
If you don't .Clear() the items and just add, you can add more items to it.
In the above example, if you add three elements, you can't add five elements anymore, even though the items change.
When you order the columns, you can see that the last item is still there (NOTE: the ordering didn't work in this example, for whatever reason), but there are only three rows rendered

**Expected behavior**
I expect to see all rows from my ObservableCollection

**Desktop (please complete the following information):**

- OS: Linux - Fedora 37, latest kernel 6.2.9
- Tried Avalonia 0.10.18 ~~and the latest preview (11.0.0.preview6)~~

**Additional context**
I tried to swap the observable collection, manually raise property changed, reapply bindings and everything i could imagine. The only workaround i found is replacing the DataGrid during runtime in the View with a new one...
I THINK this also occured on a TreeDataGrid but at this point i forgot...

**Comment by ivanjx** [comment]
similiar bug maybe but i also have a problem when using `SelectableTextBlock` `InlineCollection`. after calling `.Clear()` and adding one item to it, it is not updating the gui. it only updates the gui after the 2nd, 3rd, etc insertions. so the workaround is to add an empty `new Run()` to the `InlineCollection` right after i called `Clear()`.

**Comment by erythana** [comment]
Sorry, i messed up and remembered incorrectly: It seems to work in latest preview 11.0.0.

**Comment by timunie** [comment]
@erythana closing the issue as it seems to be resolved acc. To your comment. Let me know if it was a misunderstanding.
