### ISSUE TITLE
Setting CheckBox.IsChecked does not update UI with .NET Framework 4.6.1, working on .NET Core

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1096]
Repro using `Menu` page in `ControlCatalog`: 

https://gist.github.com/wieslawsoltes/be3fcf4bccaed1aa21eafd0cb38b21b8

Try toggling items in `Debug` menu using `Desktop` build and `NetCore` build of `ControlCatalog`.

Version: 0.5.1-build3602-alpha

**Comment by danwalmsley** [comment]
I have seen something similar with RadioButton but not Framework related, I get the same behaviour on .net 461 and netcore2.0

https://files.gitter.im/AvaloniaUI/Avalonia/R7Wb/scenegraph-bug.gif

**Comment by danwalmsley** [comment]
and upload a repro soon

**Comment by wieslawsoltes** [comment]
@grokys I have seen the issue also on .NET Core but on different machine (with slower CPU, running Win7 instead of Win10) and in Release build (reported issue was in Debug mode).

**Comment by danwalmsley** [comment]
I can also confirm deferredrender: true / false does not make a difference.

**Comment by danwalmsley** [comment]
My guess would be that it does the render pass before the state has updated.

If you trigger another full render (i.e. by window resize) it then renders correctly (for me anyway)

**Comment by grokys** [comment]
@wieslawsoltes' problem seems to be caused by the fact that the `CheckBox` is in a `Popup` and it's not getting updated correctly.

@danwalmsley you said you'd upload a repro? I suspect your problem might be different.
