### ISSUE TITLE
AutoScrollToSelectedItem in TreeView with VirtualizingStackPanel does not work

### ISSUE THREAD

**Issue by TheXamlGuy** [AvaloniaUI/Avalonia#10985]
**Describe the bug**
Take the below TreeView example, bounded to a collection

```
        <TreeView
            AutoScrollToSelectedItem="True"
            SelectedItem="{Binding Selected}"
            ItemsSource="{Binding Items}">
          <TreeView.ItemsPanel>
            <ItemsPanelTemplate>
              <VirtualizingStackPanel />
            </ItemsPanelTemplate>
          </TreeView.ItemsPanel>
        </TreeView>
```
When setting the SelectedItem property to an item outside of the visible TreeView boundary, the selection changes but it does not automatically scroll to that item. However, if I switch to using a ListBox control all is working spot on.

```
       <ListBox
            AutoScrollToSelectedItem="True"
            SelectedItem="{Binding Selected}"
            ItemsSource="{Binding Items}">
            <ListBox.ItemsPanel>
                <ItemsPanelTemplate>
                    <VirtualizingStackPanel />
                </ItemsPanelTemplate>
            </ListBox.ItemsPanel>
        </ListBox>
```

**Expected behavior**
TreeView should automatically scroll to selected item when using VirtualizingStackPanel as the ItemsPanel.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0.999-cibuild0033096-beta

**Comment by TheXamlGuy** [comment]
Added sample app: 
[AutoScrollToSelectedItem.zip](https://github.com/AvaloniaUI/Avalonia/files/11201946/AutoScrollToSelectedItem.zip)

**Comment by grokys** [comment]
Usage of `VirtualizingStackPanel` with `TreeView` isn't supported yet. Does this issue go away if you don't change the `ItemsPanel`?

**Comment by grokys** [comment]
Ok, that's not really that surprising then. As I mentioned, `VirtualizingStackPanel` isn't expected to work yet with `TreeView` - it will need extra features in order to handle it. To be honest I'm surprised this was the only issue you had! Hopefully I'll manage to get it working during 11.x.
