### ISSUE TITLE
Design preview starts external process

### ISSUE THREAD

**Issue by bdoyle159** [AvaloniaUI/Avalonia#10988]
**Describe the bug**
AXAML preview can start a .NET Process object if set up correctly

**To Reproduce**
Create a new Avalonia .NET Core App Project. In code-behind, add this to the Main function after InitializeComponent
```
   ProcessStartInfo startInfo = new()
            {
                CreateNoWindow = true,
                FileName = "calc.exe",
                UseShellExecute = false
            };
            Process newProcess = new() { StartInfo = startInfo };
            newProcess.Start();
```

Build the application (you do NOT need to run or debug)
Open the design preview of MainWindow

**Expected behavior**
The design preview should be more 'sandboxed' so it cannot start external processes. This has caused a major annoyance because the designer is keeping a file handle open in my project, so when I am debugging or running the project, that file is still open by the designer. This could also be seen as a security issue, especially since the executable does not need to actually be started, but building the solution will cause this to happen.

**Desktop (please complete the following information):**

- OS: Tested on Windows 10 21H2 and Linux Debian 11
- IDE: Both Visual Studio 2022 and Jetbrains Rider 2023.1

**Additional context**
This does not happen in WPF projects in Visual Studio.

**Comment by maxkatz6** [comment]
It is by design.
Previewer process is basically your application, which was run from the IDE.
If you want to isolate some parts of code, please use `Design.IsDesignMode` property.
