### ISSUE TITLE
RatingControlSample doesn't work with Avalonia 11 preview 6

### ISSUE THREAD

**Issue by DmitriyYukhanov** [AvaloniaUI/Avalonia#10981]
**Describe the bug**
After updating the project to the preview 6, stars doesn't add anymore, the container remains empty.

**To Reproduce**

1. Download and open [RatingControlSample](https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src/Avalonia.Samples/CustomControls/RatingControlSample) 
2. Update Avalonia to 11 Preview 6 and fix compilation errors caused by API changes.
3. Build and run.
4. See no stars appear.

**Expected behavior**
Example renders just like in 11 preview 4 - with fully functional stars.

**Screenshots**
11 preview 6
![image](https://user-images.githubusercontent.com/883587/231108603-2f9c2449-6fe2-4a26-ba73-95b08a804461.png)

11 preview 4
![image](https://user-images.githubusercontent.com/883587/231109715-c50ba710-84c0-4ddb-af8f-a2572b8bafe0.png)

**Desktop (please complete the following information):**

- OS: Windows 11 22H2
- Version 11 preview 6

**Comment by timunie** [comment]
Samples are not for preview versions made. They will be updated when it's time to do, so only after 11.0 dropped. Previews can have breaking changes and I don't want to confuse newbies.

Thanks for your understanding.

**Comment by DmitriyYukhanov** [comment]
That's totally understandable. Cheers for the quick response guys, you rock.
Will keep this open on your behalf.
