### ISSUE TITLE
OpenFilePickerAsync fails and returns null when called from a dialog utilizing the MainWindow's StorageProvider

### ISSUE THREAD

**Issue by Aurumaker72** [AvaloniaUI/Avalonia#10998]
**Describe the bug**
`OpenFilePickerAsync` fails to open the dialog and returns null immediately when called from a dialog utilizing the MainWindow's StorageProvider

**To Reproduce**

1. Create a `Window`
2. Add following code to a `Button`'s EventHandler in the dialog:
```cs
 await (Application.Current.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime).MainWindow.StorageProvider.OpenFilePickerAsync();
```
4. Open the `Window` as a modal dialog utilizing `ShowDialog` from your `MainWindow`
5. The file dialog will not appear, instead returning null immediately from `OpenFilePickerAsync`

**Expected behavior**
The dialog is expected to function normally.

**Desktop (please complete the following information):**

- OS: Windows
- Build 19045.2728

**Comment by Aurumaker72** [comment]
Accidentally closed it

**Comment by Aurumaker72** [comment]
Yes, indeed the user is supposed to use the relevant `StorageProvider`, but I would expect the API to have *some* sort of fallback for a `StorageProvider`<->`Window` mismatch.

Having `OpenFilePickerAsync` return null instantly with no indication of what's wrong, which is what led me onto a brief cryptic error debugging journey, is poor DX.

**Comment by maxkatz6** [comment]
> which is what led me onto a brief cryptic error debugging journey, is poor DX.

That's up to MS, as this seem to be win32 api behavior. 
In Avalonia we didn't force any of this behavior. 
Most likely it would fail with an exception or cancel result. 

> but I would expect the API to have some sort of fallback for a StorageProvider<->Window mismatch.

Not sure what you mean here. Automatically resolve current dialog child window?

**Comment by maxkatz6** [comment]
Wasn't able to reproduce with the main window file picker, while the child dialog was shown.
Either way, wontfix.
