### ISSUE TITLE
RadioButton checked style is gone with simple theme

### ISSUE THREAD

**Issue by ivanjx** [AvaloniaUI/Avalonia#10991]
**Describe the bug**
Cannot see the radio button checked state with simple theme. Works fine in preview 5. A workaround is to do this at init:
```
await Task.Delay(1);
r1.IsChecked = true;
await Task.Delay(1);
r2.IsChecked = true;
await Task.Delay(1);
r1.IsChecked = true;
```

**To Reproduce**

1. Create 2 radio buttons.
2. Run the app. Try selecting one of them.
3. Checked state is not visible on the checked radio button.

**Expected behavior**
Can see checked state of selected radio button.

**Desktop (please complete the following information):**

- OS: Windows
- Version latest nightly

**Additional context**
[AvaloniaApplication.zip](https://github.com/AvaloniaUI/Avalonia/files/11209178/AvaloniaApplication.zip)

**Comment by maxkatz6** [comment]
@grokys @tomenscape is it related to SetCurrentValue?
Looks like some SetValue usages were not replaced in RadioButton code
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/RadioButton.cs#L196
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/RadioButton.cs#L89

**Comment by tomenscape** [comment]
Seems so, those two cases are definitely bugs. The analyser doesn't report them because the control isn't setting its own values.

**Comment by tomenscape** [comment]
Nope, those bad assignments in fact are not the cause. It seems to be a rendering issue: in the control gallery, if you switch away from and then back to the radio buttons tab, they are redrawn in the correct state.

**Comment by ivanjx** [comment]
is there a workaround to redraw the screen manually @tomenscape ?

**Comment by tomenscape** [comment]
You can call the `InvalidateVisual` method to force the control to be redrawn, but I'm not sure if that will redraw enough stuff. Worth trying until a proper fix can be made, though.

**Comment by ivanjx** [comment]
unfortunately `InvalidateVisual` didnt work

**Comment by ivanjx** [comment]
checkbox works fine so i think i will just use that in replacement of radio button

**Comment by ivanjx** [comment]
it seems that rendering issue is also affecting stackpanel's layout control.
```
[stackpanel]
[control1]
[control2]
[end of stackpanel]
```
if i hide control1 then show it again, it overlaps with control2. if i switched to another view and switch back, it went to normal without doing anything.

**Comment by tomenscape** [comment]
@kekekeks want to take a look?

**Comment by kekekeks** [comment]
> if you switch away from and then back to the radio buttons tab, they are redrawn in the correct state.

Try resizing the window. If simple resize helps, it usually means that dirty rects are broken. Switching pages fixing stuff is usually not related to the renderer, since it triggers a full detach/attach and layout cycle.

**Comment by tomenscape** [comment]
Tried it, but resizing does not fix the problem.

**Comment by tomenscape** [comment]
This is the same issue as #11015, a fix is on the way.
