### ISSUE TITLE
Get old selected value instead of new selected value from comboBox in MVVM application

### ISSUE THREAD

**Issue by dellbeat** [AvaloniaUI/Avalonia#11006]
### **Describe the bug**

I use avalonia to build a MVVM application,  using a comboBox to select items. I set selectedItem with viewmoel binding ,set a reactivecommand for handle SelectionChanged event and bind this event.
But when i select other item from combobox , in command for handle event , i got the old selected value instead of the new selected value.
I write a  [exmaple application](https://github.com/dellbeat/AvaloniaComboBoxIssueExample/) to show the bug. Here are [view code](https://github.com/dellbeat/AvaloniaComboBoxIssueExample/blob/master/ComboBoxExample/Views/MainWindow.axaml) and [viewmodel code](https://github.com/dellbeat/AvaloniaComboBoxIssueExample/blob/master/ComboBoxExample/ViewModels/MainWindowViewModel.cs) .

### **To Reproduce**

1.Clone the code , build and run the example application
2.Select any item in comboBox , for example First , you can see the textBlock's text is "Current Selected "
3.Select another item in comboBox ,for example Second you can see the textBlock's text is "Current Selected First"

the setp 2 and 3 can reproduce the behavior , because the event for command get the old selected value rather than new selected value.

### **Expected behavior**

I can get the new selected value when SelectionChanged event is raised.

### **Screenshots**

![image](https://user-images.githubusercontent.com/30553983/231743481-b45ce23f-8f5a-41ca-8639-a9b75d97ceb9.png)
the application startup

![image](https://user-images.githubusercontent.com/30553983/231743628-ab63f7ee-4ea2-4250-82d4-17e71f5380f3.png)
step 2

![image](https://user-images.githubusercontent.com/30553983/231743804-c7424aef-c81e-4dee-a6fd-9e17ff1be999.png)
step 3

### **Desktop (please complete the following information):**

- OS: Windows 10 Perfessional 21H2
- Version 0.10.19

### **Additional context**
I try to debug it , and i found afrer the selectedItem changed , the control raise the SelectionChanged event first the update the selectedItem to new value. I guess the occurrence of bugs is related to the order of execution.
But i couldn't write a correct test in Avalonia.Controls.UnitTests to prove the bug is exist and code change is right. I have no idea to write a binding code equal to axaml binding like [this](https://github.com/dellbeat/AvaloniaComboBoxIssueExample/blob/5dc75acb2489bb9eb523fda082b4ba9ede7f4925/ComboBoxExample/Views/MainWindow.axaml#L30) in test .
This is the unfinished test code I wrote

```
        [Fact]
        public void Binding_SelectionChanged_Event()
        {
            var inputManagerMock = new Moq.Mock<IInputManager>();
            var services = TestServices.StyledWindow.With(inputManager: inputManagerMock.Object, keyboardDevice: () => new KeyboardDevice());

            using (UnitTestApplication.Start(TestServices.StyledWindow))
            {
                var window = new Window();
                var target = new ComboBox()
                {
                    Items = { "First", "Second", "Third", "Fourth" },
                    SelectedIndex = -1,
                    Template = GetTemplate(),
                };
                string recordText = null;
                string bindText = null;//the variable need to bind

                target.SelectionChanged += (sender, args) =>
                {

                };

                window.Content = target;

                target.Focus();

                target.RaiseEvent(new KeyEventArgs
                {
                    RoutedEvent = InputElement.KeyDownEvent,
                    Key = Key.Down,
                });


                target.RaiseEvent(new KeyEventArgs
                {
                    RoutedEvent = InputElement.KeyDownEvent,
                    Key = Key.Down,
                });

                Assert.True(recordText == target.SelectionBoxItem.ToString());
            }
        }
```

**Comment by maguro1kan** [comment]
When fix it?

**Comment by dellbeat** [comment]
邮件已收到

**Comment by timunie** [comment]
@maguro1kan once someone got time to do. If it's urgent for you, a PR is welcome.

**Comment by maguro1kan** [comment]
Hi, @timunie .
Added same issue in my repo.
Name: BugSample2
https://github.com/maguro1kan/BugSample1

Thanks.

**Comment by timunie** [comment]
PR means file a pull request to fix your issue :-)

**Comment by maguro1kan** [comment]
Should I pull request my BugSample2 code to https://github.com/AvaloniaUI/Avalonia/pulls?

**Comment by timunie** [comment]
No a fix if you are able to fix it.

**Comment by timunie** [comment]
Otherwise you will need to wait for someone to have a time for it to do.
