### ISSUE TITLE
Combobox popup width changes with variable Combobox item sizes

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#11018]
**Describe the bug**
When the combo box items are different sizes, the popup changes it's width while scrolling wich makes it quite unusable.

**To Reproduce**
Create a combo that forces to display a scroll, width of different item sizes:
```
  <ComboBox SelectedIndex="0">
    <ComboBoxItem>Example Item 01</ComboBoxItem>
    <ComboBoxItem>Example Item 02</ComboBoxItem>
    ... etc ...
    <ComboBoxItem>Very very very very very very very long item</ComboBoxItem>
    <ComboBoxItem>Example Item 25</ComboBoxItem>
    <ComboBoxItem>Example Item 26</ComboBoxItem>
    ... etc ...
  </ComboBox>
```
![combo](https://user-images.githubusercontent.com/501613/232035153-b15a2598-6c49-49a5-bcb9-ead235e200b5.gif)

**Expected behavior**
The width of the popup should be the max width of the longest item in the combo.

**Desktop (please complete the following information):**

- OS: Windows
- Version master latest.

**Comment by danipen** [comment]
Well, the reason I reported this, is because it was working as expected in 0.10.x and the default panel for `ComboBox` was already a `VirtualizingStackPanel`. 

So maybe it's worth taking a look.

https://github.com/AvaloniaUI/Avalonia/blob/45c009e3d2d7e1f383dfff0cd33b95de0b4b11a1/src/Avalonia.Controls/ComboBox.cs#L31

The usage in 0.10.x is much better in my opinion:
![combox](https://user-images.githubusercontent.com/501613/232078632-e3430324-f764-4bd9-bc50-2c31842cde76.gif)

**Comment by maxkatz6** [comment]
> Well, the reason I reported this, is because it was working as expected in 0.10.x and the default panel for ComboBox was already a VirtualizingStackPanel.

In 0.10 ComboBox wasn't virtualized by default. So it makes sense that it worked before. Now, there is no context information for the combobox to know possible width of unrealized items.

**Comment by danipen** [comment]
Can virtualization be disabled or do I need to replace the combo items panel?

**Comment by timunie** [comment]
Maybe you can also limit drop down width or set MinWidth to maximum known size via Behavior. That way it will still grow if needed but not shrink anymore.

**Comment by maxkatz6** [comment]
I think you can replace panel with a StackPanel.

**Comment by danipen** [comment]
@maxkatz6 do you mean replacing VirtualizingStackPanel with StackPanel?

**Comment by maxkatz6** [comment]
Yes

**Comment by danipen** [comment]
A workaround is to disable virtualization for the ComboBox.

```
ComboBox result = new ComboBox();
result.ItemsPanel = new FuncTemplate<Panel>(new(() => new StackPanel()));
```
