### ISSUE TITLE
Cannot move the slider thumb

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#11015]
**Describe the bug**
The slider thumb cannot be moved.

**To Reproduce**
Open the control catalog, and try the slider demo:
![slider](https://user-images.githubusercontent.com/501613/232019531-290913e0-de8d-4478-8842-49ffb6a3aaa0.gif)

**Desktop:**
- OS: Windows
- Version latest master.

**Comment by kekekeks** [comment]
Note that:
1) updating it with keyboard doesn't work either
2) Value property does get updated

I believe it's something with bindings or templates

**Comment by danipen** [comment]
In my case, the value gets updated (that slider modifies the size of the icon). 
![slider2](https://user-images.githubusercontent.com/501613/232032659-c8187678-ec86-4d8b-9f1d-4153ed3c8ad3.gif)

**Comment by grokys** [comment]
Was broken by 6dd9106fe55ed51aa9ecf34768b3138c067d04e6 in #10864. Will fix.
