### ISSUE TITLE
Layout is not working as expected

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#11019]
**Describe the bug**
Centering `StackPanel` and then `TextBlocks` inside the `StackPanel` is not working as expected.

**To Reproduce**
Execute the minimal repro case: https://github.com/danipen/LayoutReproCase.git
**Actual behavior**
The text is not centered.
![actual](https://user-images.githubusercontent.com/501613/232043346-9def3b15-94e9-4adf-bc1a-01cc6b691358.gif)

**Expected behavior**
The text is centered.
![expected](https://user-images.githubusercontent.com/501613/232043374-3988d196-d03b-416c-9f8e-6082ccc2edd7.gif)

**Desktop**
- OS: Windows
- Version latest master

**Comment by Gillibald** [comment]
This seems to be a rendering issue. Measurements are updated properly.
