### ISSUE TITLE
Button:pressed seems to replace template if it was overridden

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1102]
repro code

```
 <UserControl.Styles>
    <Style Selector="Button.RoundedButton">
      <Setter Property="Template">
        <ControlTemplate>
          <Border Background="Red" CornerRadius="8">
            <ContentPresenter Content="{TemplateBinding Content}"/>
          </Border>
        </ControlTemplate>
      </Setter>
    </Style>
    <Style Selector="Button.RoundedButton:pointerover">
      <Setter Property="Template">
        <ControlTemplate>
          <Border Background="Green" CornerRadius="4">
            <ContentPresenter Content="{TemplateBinding Content}"/>
          </Border>
        </ControlTemplate>
      </Setter>
    </Style>
  </UserControl.Styles>


<Button Content="Test" Classes="RoundedButton" />
```

If the button is pressed it gets no default colour and not red as it should be. Added the pointerover template to prove that selector was working...

[Secondary Bug]
interestingly after first template is applied, I cant change the second one to:
```    
<Style Selector="Button.RoundedButton:pointerover /template/ Border">
      <Setter Property="Background" Value="Green" />
    </Style>
```

**Comment by grokys** [comment]
I've spent some time looking into this and it's strange. This is what I've found so far:

The template is actually getting applied. If I change the markup to look like this:

```
  <UserControl.Styles>
    <Style Selector="Button.RoundedButton">
      <Setter Property="Template">
        <ControlTemplate Name="Button.RoundedButton">
          <Border Background="Red" CornerRadius="8">
            <ContentPresenter Content="{TemplateBinding Content}"/>
          </Border>
        </ControlTemplate>
      </Setter>
    </Style>
    <Style Selector="Button.RoundedButton:pointerover">
      <Setter Property="Template">
        <ControlTemplate Name="Button.RoundedButton:pointerover">
          <Border Background="Green" CornerRadius="4">
            <ContentPresenter Content="{TemplateBinding Content}"/>
          </Border>
        </ControlTemplate>
      </Setter>
    </Style>
    <Style Selector="Button.RoundedButton:pressed">
      <Setter Property="Template">
        <ControlTemplate Name="Button.RoundedButton:pressed">
          <Rectangle Fill="Blue" Width="100" Height="100"/>
        </ControlTemplate>
      </Setter>
    </Style>
  </UserControl.Styles>
```

Then when clicked, indeed a big blue square appears. I've not worked out why the example you posted isn't working yet however.

**Comment by grokys** [comment]
Ok, I now know what's causing this. In the default `Button` template there's this:

```
  <Style Selector="Button:pressed  /template/ ContentPresenter">
    <Setter Property="Background" Value="{StyleResource ThemeControlDarkBrush}"/>
  </Style>
```

Which means that when the button is pressed, the `ContentPresenter` in the template is getting its background set to `ThemeControlDarkBrush`. This selector is matching even when the `RoundedButton` class is present, meaning that the `ContentPresenter` is getting drawn over the `Border` with the `CornerRadius`.

I'm not sure what to do about this. It took me a good hours or so of debugging to work out what's happening, but it's actually correct behavior. So on one hand there's nothing wrong, but on the other hand, it's not a good user experience. Any ideas?

**Comment by OronDF343** [comment]
I have a related issue, which may be relevant here since it concerns the same default Button template.

I have the following styles:
```
<StyleInclude Source="resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"/>
        <StyleInclude Source="resm:Avalonia.Themes.Default.Accents.BaseLight.xaml?assembly=Avalonia.Themes.Default"/>
<Style Selector="Button">
        <Setter Property="Foreground" Value="#FF94E6EF" />
        <Setter Property="FontWeight" Value="Bold"/>
        <Setter Property="Background" Value="#FF425A6B" />
        <Setter Property="BorderThickness" Value="0"/>
        <Setter Property="Padding" Value="0"/>
      </Style>
      <Style Selector="Button:pointerover">
        <Setter Property="Background" Value="#FF52639C"/>
      </Style>
      <Style Selector="Button:pressed">
        <Setter Property="Background" Value="#FF529CDE"/>
      </Style>
```

The `:pointerover` style works perfectly, but the `:pressed` style has no effect. Only if I change it to `Button:pressed  /template/ ContentPresenter` it actually has an effect. There seems to be an issue specific to `:pressed` here...

Just making a wild guess here, but wouldn't both problems be resolved by changing the selector in the default style you showed to just `Button:pressed`? There's really no reason to target the `ContentPresenter` specifically since its `Background` has a `TemplateBinding`, which is (probably) why my `:pointerover` selector works fine.

**Comment by Gillibald** [comment]
This is the same issue as with TabItem before I fixed the default template to target the TabItem.Background property directly instead of accessing the ContentPresenter's Background. Will fix this when I find time.
