### ISSUE TITLE
[Browser] Publish experience compared to Blazor WebAssembly

### ISSUE THREAD

**Issue by nxtn-staged** [AvaloniaUI/Avalonia#11030]
It seems that the publish experience of Blazor WebAssembly is better polished. I'm not familiar with these WebAssembly stuff, but I'm wondering if we can reuse their optimizations or have to roll our own.

Example of steps to reproduce:

**Avalonia**

```
dotnet new avalonia.xplat -o Test.Avalonia -f net7.0
cd .\Test.Avalonia\Test.Avalonia.Browser\
dotnet workload restore
dotnet publish -c Release
dotnet serve --directory .\bin\Release\net7.0\browser-wasm\AppBundle\
```

When accessed twice from Microsoft Edge version 112:

1. 45 requests 14.8 MB transferred 14.8 MB resources
1. 45 requests 0 B transferred 14.8 MB resources

When accessed twice from Firefox version 112:

1. 45 requests 14.78 MB / 14.79 MB transferred
1. 45 requests 14.78 MB / 6.25 MB transferred

**Blazor**

```
dotnet new blazorwasm -o Test.Blazor -f net7.0
cd .\Test.Blazor\
dotnet workload restore
dotnet publish -c Release
dotnet serve --directory .\bin\Release\net7.0\publish\wwwroot\
```

When accessed twice from Microsoft Edge version 112:

1. 42 requests 5.9 MB transferred 5.9 MB resources
1. 10 requests 208 B transferred 513 kB resources

When accessed twice from Firefox version 112:

1. 42 requests 5.91 MB / 5.92 MB transferred
1. 42 requests 5.91 MB / 0 B transferred

The following is a non-exhaustive list of differences.

- Blazor automatically generates Brotli/Gzip compressed static files (not used in the repro steps above).
- Blazor only fetches static files once on Chromium, so it doesn't rely on the browser's caching behavior and is probably faster.
- Avalonia doesn't publish the app into the *publish* folder, making it difficult to separate the `publish` artifacts from the `build` artifacts.

You can find more information about Blazor WebAssembly on https://learn.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly.

**Comment by maxkatz6** [comment]
I think it's not the right place for this issue, as dotnet team manages app publishing process.

In general, I need to say that WebAssembly (no-Blazor) app is smaller (assuming it was compressed with the same algorithm, what you still can do automatically on static web servers), and faster.
Not sure if saving binaries in the local storage is faster than browser build-in caching, could be.

**Comment by maxkatz6** [comment]
dotnet/runtime issue already exists for that:
https://github.com/dotnet/runtime/issues/70762

**Comment by nxtn-staged** [comment]
Thank you, so these are not issues specific to Avalonia, and there's not much to do here.
