### ISSUE TITLE
[Browser] Can't display Chinese

### ISSUE THREAD

**Issue by znoliver** [AvaloniaUI/Avalonia#11031]
**Describe the bug**
I am trying to develop a sample using 11.0-preview-5，but if my program contains Chinese, it will report exception

**Has Chinese**
![image](https://user-images.githubusercontent.com/59060212/232397692-60c09a34-beaf-460c-a09d-492d02deb498.png)
![image](https://user-images.githubusercontent.com/59060212/232397835-59e8860f-8100-4b8d-9136-8635c301aa20.png)

**Don't has Chinese**
![image](https://user-images.githubusercontent.com/59060212/232398035-429757c1-58ed-4f26-94f0-e0c9fa2abdfa.png)
![image](https://user-images.githubusercontent.com/59060212/232398055-e174e237-4816-4c54-be3d-16d545ad650a.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04 LTS
- Version 11.0-preview 5

**Comment by Gillibald** [comment]
A known limitation of the Sandboxed environment. You need to embed a font that contains the required glyphs.

**Comment by znoliver** [comment]
> A known limitation of the Sandboxed environment. You need to embed a font that contains the required glyphs.
I have already embed a font in my program，but it still reported an error:
![image](https://user-images.githubusercontent.com/59060212/232401454-64972ab7-a669-485b-9f61-09963efe2e43.png)
Did I make a mistake somewhere？

**Comment by znoliver** [comment]
I solved this problem：
```
    public static AppBuilder BuildAvaloniaApp()
        => AppBuilder.Configure<App>()
            .With(new FontManagerOptions()
            {
                FontFallbacks = new []
                {
                    new FontFallback
                    {
                        FontFamily = new FontFamily("avares://ZKSD.RTE/Assets/Fonts/微软雅黑.ttf#Microsoft YaHei")
                    }
                }
            });
```
