### ISSUE TITLE
Improve error message when missing IAssetLoader in AvaloniaXamlLoader.Load

### ISSUE THREAD

**Issue by mterwoord** [AvaloniaUI/Avalonia#1104]
Right now, when using ```AvaloniaXamlLoader.Load``` inside the Application's constructor, you get the error: ```Could not create IAssetLoader : maybe Application.RegisterServices() wasn't called?```.

How about we improve this message in the case of initializing an application? To read:
```Could not create IAssetLoader : maybe Application.RegisterServices() or is AvaloniaXamlLoader.Load getting called in the Application's constructor?" 

(Exact message text is of course up for discussion, my main point is that it hints about the location of the .Load call)

**Comment by kekekeks** [comment]
You shouldn't do *anything* from constructur. There is `Initialize` method. I guess, exception should say something about that.

**Comment by mterwoord** [comment]
Doing that would be possible using a hack like the CallerMemberName attribute or something like that, but sounds like a hack... :)

**Comment by grokys** [comment]
Going to close this as our application lifetime API has changed, and our templates make clear [you shouldn't do stuff like that](https://github.com/AvaloniaUI/AvaloniaVS/blob/master/templates/AvaloniaApplicationTemplate/Program.cs#L10-L12).
