### ISSUE TITLE
Watermark in CalendarDatePicker breaks the display of empty dates

### ISSUE THREAD

**Issue by Kibnet** [AvaloniaUI/Avalonia#11055]
**Describe the bug**
If the watermark is enabled in the CalendarDatePicker, and SelectedDate is binding to a property with the type (DateTime?), then the actual selected date is not always displayed in the control.

**To Reproduce**
`<CalendarDatePicker SelectedDate="{Binding PlannedDateTime}" Watermark="Planned"/>`
PlannedDateTime is property with the type (DateTime?) in DataContext INPC.

1. PlannedDateTime = DateTime.Now;
2. PlannedDateTime = null;
4. The CalendarDatePicker displays the date from DateTime.Now

**Expected behavior**
The CalendarDatePicker displays the Watermark

**Desktop (please complete the following information):**
- OS: Windows
- Version 0.10.19

**Comment by timunie** [comment]
That is a really interesting issue. The Text can be cleared if no Watermark is set, but once the Watermark is set, it will not work 🤔
