### ISSUE TITLE
[Feature] Saving source generator output in source control

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#11050]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/10359

<div type='discussions-op-text'>

<sup>Originally posted by **workgroupengineering** February 16, 2023</sup>
The files created by the source generator by default are created on the fly in the intermediate files and consequently excluded from the SCM (source control manager). Since generate files they are not persisted on the SCM it is not possible to include them in the debug information of the SourceLink.

To improve the debugging experience of us developers I would like to propose setting EmitCompilerGeneratedFiles to true, so that we can indicate where to save the generated files.

Ref: [Saving source generator output in source control](https://andrewlock.net/creating-a-source-generator-part-6-saving-source-generator-output-in-source-control/)</div>

**Comment by maxkatz6** [comment]
The point of source generators in composition API was to avoid keeping tons of repetitive files in the source control (and not to write them by hand as well).

Visual Studio and Rider are able to decompile missing code, so SourceLink shouldn't be necessary there.

**Comment by workgroupengineering** [comment]
> Visual Studio and Rider are able to decompile missing code, so SourceLink shouldn't be necessary there.

Yes, but in many cases they are not able to inspect the symbols.
