### ISSUE TITLE
Scrolling in a ListBox changes the SelectedItem.

### ISSUE THREAD

**Issue by mvegaca** [AvaloniaUI/Avalonia#11079]
**Describe the bug**
Scrolling in a large items ListBox control in a touchscreen (Avalonia XPlat Android Device) change the SelectedItem of the ListBox.

The SelectedItem of the ListBox should be changed if the finger touch the screen in a single tap, but now if you use your finger to scrolldown the listbox, the selecteditem is changed and this is wrong. 

**To Reproduce**
 - Create Avalonia XPlatform app with a ListBox of items, the items count should be engoht to create a scroll in the ListView.
 - Create a CompiledBinding TwoWays in the SelectedItem and navigate to a detail view on the setter method.

**Expected behavior**
Yo should navigate to any item at the bottom of the scroll.

**Desktop (please complete the following information):**
Only happens on touch screen devices.
Avalonia version: 11.0.0-preview5
Development enviroment: MacBook Pro M2.
Deployment device: Xiaomi Pad 5

**Comment by timunie** [comment]
@mvegaca can you double-check using latest nightly? Since preview5 we had some huge changes, so things may be different now. Thx 🙏

**Comment by mvegaca** [comment]
I've configured the Avalonia to Nightly CI 11.0.999-cibuild0033534-beta and the issue still happens :(

**Comment by mvegaca** [comment]
Hi, do you have any updates here?

Thank you very much!
