### ISSUE TITLE
SaveFilePickerAsync is broken on wasm firefox

### ISSUE THREAD

**Issue by aldelaro5** [AvaloniaUI/Avalonia#11077]
**Describe the bug**
An error occur whenever I try to call the SaveFilePicker on Firefox because it uses an api that is not supported on that browser.

**To Reproduce**

1. Have a SaveFilePickerAsync call in your app
2. Observe the following error in the console with no dialog:
![Screenshot from 2023-04-20 03-07-11](https://user-images.githubusercontent.com/8932978/233309395-3dd7b895-2755-4106-9fb4-581d6a387083.png)

**Expected behavior**
The SaveFilePickerAsync to work correctly on Firefox.

**Desktop (please complete the following information):**

- OS: Arch Linux
- Firefox 111.0.1
- Version 11 preview 6

**Additional context**
Essentially, I investigated myself and found this line https://github.com/AvaloniaUI/Avalonia/blob/master/src/Browser/Avalonia.Browser/webapp/modules/storage/storageProvider.ts#L50 which seemed to call a function on the window, but in checking the mdn documention, if you scroll down at the end, it specifically says that Firefox has "No Support": https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker#browser_compatibility

I currently have issues to test on my end, but the `native-file-system-adapter` module does seem to provide a `showSaveFilePicker` which could fix this problem. I wonder why this feature was used considering Firefox doesn't support it.

**Comment by maxkatz6** [comment]
> I currently have issues to test on my end, but the native-file-system-adapter module does seem to provide a showSaveFilePicker which could fix this problem. I wonder why this feature was used considering Firefox doesn't support it.

That's correct. This library has support for save file picker. Unfortunately, it's quite a big hack, as it either works through "download link" (i.e. works horribly with big files) or a service worker (needs to be set-up separately, might conflict with user defined service workers). It's still something we can use though, just wasn't done because of time limitations. Ideally, BrowserOptions should have a way to disable/enable service worker.

Off-topic, but I have feeling like we should close Firefox related issues, as this browser has its own policy about supporting new features or discussing standards, and we have nothing to do until they find out any better API.

https://github.com/mozilla/standards-positions/issues/154
https://github.com/mozilla/standards-positions/issues/738#issuecomment-1401367367
https://mozilla.github.io/standards-positions/

**Comment by maxkatz6** [comment]
Also, I would recommend to always check "StorageProvider.CanSave" flag, as you might find out that iOS also doesn't have Save File Picker APIs at all.
Ideally, Share API should be supported for these cases, and it is better UX-wise on mobile, where people usually share files and not save them. 

But guess what, you also can't share files on Firefox: https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API#api.navigator.canshare

**Comment by aldelaro5** [comment]
> > I currently have issues to test on my end, but the native-file-system-adapter module does seem to provide a showSaveFilePicker which could fix this problem. I wonder why this feature was used considering Firefox doesn't support it.
> 
> That's correct. This library has support for save file picker. Unfortunately, it's quite a big hack, as it either works through "download link" (i.e. works horribly with big files) or a service worker (needs to be set-up separately, might conflict with user defined service workers). It's still something we can use though, just wasn't done because of time limitations. Ideally, BrowserOptions should have a way to disable/enable service worker.
> 
> Off-topic, but I have feeling like we should close Firefox related issues, as this browser has its own policy about supporting new features or discussing standards, and we have nothing to do until they find out any better API.
> 
> [mozilla/standards-positions#154](https://github.com/mozilla/standards-positions/issues/154) [mozilla/standards-positions#738 (comment)](https://github.com/mozilla/standards-positions/issues/738#issuecomment-1401367367) https://mozilla.github.io/standards-positions/

Huh, this is all very interesting, well for the purpose of this issue, what are the current workaround options?

For context, my app is a game save editor: it simply offers the option to open a file for edition and an option to save it when the user wants later. I ask because I unfortunately don't have too much experience in web development and from the sound of it, it sounds like it might be possible to make it work if a bit complicated, but I recently learned how jsimport and jsexport works so I wonder if it could be possible to implement myself a proper substitute.

You mentioned using a service worker, how is that something I could implement?

**Comment by maxkatz6** [comment]
@aldelaro5 to save the file in a conventional way, you convert a file into encoded URI, which is later can be downloaded from a fake `<a>` link. See https://stackoverflow.com/questions/35038884/download-file-from-bytes-in-javascript
This is probably the best way, if your files aren't too big (i.e., gigabytes).

**Comment by aldelaro5** [comment]
@maxkatz6 I think I must be missing something because this polyfill doesn't work at all.

On firefox, It appears to act as if it suceeded, but no save file picker appears, not downloads, nothing.

On chrome (if I use the option to force to use the polyfill, had to test it since I can't debug on firefox, only chrome), now it can't register the service worker due to SSL issue despite the fact I told chrome to trust this localhost one.

I am just very confused, am I missing something?

**Comment by maxkatz6** [comment]
>  It also seems to like...do something, but only redirect to a non existent page if I wait long enough whose name is the suggestedFilename I sent.

That's basically how this hack works, same as old hacks from stackoverflow - https://stackoverflow.com/questions/35038884/download-file-from-bytes-in-javascript

I.e., creating a huge URI blob, creating `<a>` link, and opening it. Though modern apps don't open a new window for that.
There won't be any save dialog for that obviously.

https://github.com/AvaloniaUI/Avalonia/assets/3163374/39827dec-3f2b-4d52-adc1-0f1d7c0e4026

> if I use the option to force to use the polyfill

Looks like saving is broken, when polyfill is forced. As it fails with no permissions, when native API actually exists. Not really a problem for production apps, where polyfill shouldn't be forced.

**Comment by maxkatz6** [comment]
Also see console logs for any information

**Comment by aldelaro5** [comment]
> > It also seems to like...do something, but only redirect to a non existent page if I wait long enough whose name is the suggestedFilename I sent.
> 
> That's basically how this hack works, same as old hacks from stackoverflow - https://stackoverflow.com/questions/35038884/download-file-from-bytes-in-javascript
> 
> I.e., creating a huge URI blob, creating `<a>` link, and opening it. Though modern apps don't open a new window for that. There won't be any save dialog for that obviously.

See, the problem is it's not actually downloading anything. It literally just act as if it did, but no download is actually done. I ended up having better result doing what I been doing which was to do js interop to make it work manually.

Also, how did you got the ControlCatalog project running? I tried it for hours last time and I was getting multiple unrelated errors related to rendering on my end with Firefox (it was working on chrome)

**Comment by maxkatz6** [comment]
> Also, how did you got the ControlCatalog project running

dotnet run

> See, the problem is it's not actually downloading anything.

Well, I just tried in Firefox and it just works. At least how it's expected from polyfil.
Probably can you try to find any logs or debug JS code in your browser? Browser devtools are quite powerful. Also Firefox should automatically use readable TypeScript code when you set breakpoints in the browser.
Debugging JS from VS/Rider is a pain.
