### ISSUE TITLE
DeferredRenderer in Avalonia 11.0.0preview6

### ISSUE THREAD

**Issue by Wael1231** [AvaloniaUI/Avalonia#11082]
hey i am updating old project avalonia it was 0.1O.0 when i update to 11.0.0preview6 . what is equivalent of DeferredRenderer in the newest version and thanks.

**Comment by maxkatz6** [comment]
There is no deferred renderer in 11.0.
CompositionRenderer is used instead.
Why do you need this class in your code?

**Comment by Wael1231** [comment]
thanks, i have annother what is equivalent of this xmlns:styles="clr-namespace:Material.Styles;assembly=Material.Styles"
The error : Unable to resolve type Card from namespace "clr-namespace:Material.Styles;assembly=Material.Styles" 

how i can fix it please in 11.0.0preview6 ? and thanks

**Comment by maxkatz6** [comment]
Card is not part of Avalonia. You can ask this question at https://github.com/AvaloniaCommunity/Material.Avalonia

**Comment by Wael1231** [comment]
CompositionRenderer is in Avalonia or annother ?
