### ISSUE TITLE
[preview6] Default font family name can't be null or empty

### ISSUE THREAD

**Issue by yangjieshao** [AvaloniaUI/Avalonia#11084]
**Describe the bug**
need a way to set default font family

![2023-04-21_09-56-43](https://user-images.githubusercontent.com/3275834/233527723-f33baece-9d8c-4166-b3ea-840bb966d1f4.png)
![image](https://user-images.githubusercontent.com/3275834/233527876-3796dbed-b450-417b-90ea-e782833a4bf2.png)

![image](https://user-images.githubusercontent.com/3275834/233528328-1891dd51-1fbc-4025-b62c-15a39552ce59.png)

**Desktop (please complete the following information):**
- OS: 银河麒麟桌面操作系统V10(SP1)
- Version 2203
![6145077340b8d17f2cdd3097d090ba9](https://user-images.githubusercontent.com/3275834/233528015-06f716bc-771d-40d7-a3bb-c9d7e59995f5.jpg)

**Comment by znoliver** [comment]
you can use ``FontManagerOptions`` to solve this problem：
```
public static AppBuilder BuildAvaloniaApp()
        => AppBuilder.Configure<App>()
            .UsePlatformDetect()
            .LogToTrace()
            .UseReactiveUI()
            .With(new FontManagerOptions
            {
                DefaultFamilyName = "avares://AvaloniaTest/Assets/Fonts/微软雅黑.ttf#Microsoft YaHei",
                FontFallbacks = new[]
                {
                    new FontFallback
                    {
                        FontFamily = new FontFamily("avares://AvaloniaTest/Assets/Fonts/微软雅黑.ttf#Microsoft YaHei")
                    }
                }
            });
```

**Comment by bouyeijiang** [comment]
Can i load ttc format?
