### ISSUE TITLE
CompiledBindingExtension vs AvaloniaRider plugin

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#11102]
**Describe the bug**
After compile binding is enabled, <Binding/> markup is parsed as CompiledBindingExtension, where RelativeResource is not available. 
But it still compiles and runs as expected. So what should we do? change Binding to ReflectionBinding, or it is a bug from plugin?

**To Reproduce**
Add x:CompileBindings="True" in FluentTheme scrollviewer theme page. 

**Expected behavior**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/14807942/233799182-9c726d87-5f0d-415a-93ee-a4484d6a0f8b.png)

![image](https://user-images.githubusercontent.com/14807942/233799210-6682f2d0-512b-48fa-958d-33cab738b19d.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version: Avalonia: latest nightly. Plugin: 1.0.3.104

**Additional context**

**Comment by maxkatz6** [comment]
Please report Rider bugs to the Rider youtrack.
This one specifically was already reported and I added it to the list in this issue https://github.com/AvaloniaUI/Avalonia/issues/10356 just to keep it in one place.

**Comment by maxkatz6** [comment]
Specifically this https://youtrack.jetbrains.com/issue/RSRP-491613/Avalonia-not-all-bindings-properties-are-properly-supported-by-XAML-editor
Seems like it was fixed in the latest builds, not sure if public or eap.

**Comment by rabbitism** [comment]
@maxkatz6 thanks
