### ISSUE TITLE
need a way to read real font FamilyName in 11.0.999-cibuild0033657-beta

### ISSUE THREAD

**Issue by yangjieshao** [AvaloniaUI/Avalonia#11100]
i can read real font  familyname in 11.0.0-preview6 by fontManager.TryCreateGlyphTypeface(stream, out var glyphTypeface)

but in 11.0.999-cibuild0033657-beta 
TryCreateGlyphTypeface is internal and Obsolete
![image](https://user-images.githubusercontent.com/3275834/233793504-0a35cebf-d2a9-4c07-a1a2-b2f24fb0990b.png)

Sometimes the downloaded font file name does not have a font familyname ，or the file name has been renamed
So it is necessary to obtain the real font name familyname  through code

**Comment by Gillibald** [comment]
GlyphTypeface.Name yields the loaded family name

**Comment by yangjieshao** [comment]
> GlyphTypeface.Name yields the loaded family name

but  how to Create GlyphTypeface in 11.0.999-cibuild0033657-beta

fontManager.TryCreateGlyphTypeface is internal  in  11.0.999-cibuild0033657-beta

**Comment by Gillibald** [comment]
new Typeface("MyFont").GlyphTypeface.Name

**Comment by yangjieshao** [comment]
> new Typeface("MyFont").GlyphTypeface.Name

![image](https://user-images.githubusercontent.com/3275834/233794936-04fe3d59-ebca-4eab-92aa-0360547b469f.png)
if i know real font FamilyName ,i can use it

But my problem is that **I didn't know the real font FamilyName** in advance and needed a method to obtain the real font FamilyName

**Comment by yangjieshao** [comment]
> new Typeface("MyFont").GlyphTypeface.Name


for example 
maybe I have a font file named 'abcd-Bold.ttf'
But this is a file name that has been modified by someone
And I don't know its original name，
how can I know its real font family name is  'Alibaba PuHuiTi 2.0'

**Comment by Gillibald** [comment]
Load it via https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Media/Fonts/EmbeddedFontCollection.cs#L19

**Comment by yangjieshao** [comment]
> Load it via https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Media/Fonts/EmbeddedFontCollection.cs#L19

yes,  I can load ttf by EmbeddedFontCollection then use it if I know  font family name,

In preview6 , I can copy EmbeddedFontCollection and print  font family name like:
```
        public void Initialize(IFontManagerImpl fontManager)
        {
            var assetLoader = AvaloniaLocator.Current.GetRequiredService<IAssetLoader>();

            var fontAssets = FontFamilyLoader.LoadFontAssets(_source);

            foreach (var fontAsset in fontAssets)
            {
                var stream = assetLoader.Open(fontAsset);

                if (fontManager.TryCreateGlyphTypeface(stream, out var glyphTypeface))
                {
                    // glyphTypeface.FamilyName 真实名字
                    Debug.WriteLine($"Path:{fontAsset.AbsolutePath}");
                    Debug.WriteLine($"FamilyName:{glyphTypeface.FamilyName}");
                    Debug.WriteLine($"Style:{glyphTypeface.Style} Weight:{glyphTypeface.Weight} Stretch:{glyphTypeface.Stretch} ");
                }
            }
        }
```

but in 11.0.999-cibuild0033657-beta, i can't do this because `TryCreateGlyphTypeface` is internal 
![image](https://user-images.githubusercontent.com/3275834/233818308-7ccdc5c3-d8fa-4cc3-8d91-62917b50ca34.png)
