### ISSUE TITLE
Carousel doesn't detach old items, and always show first

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaUI/Avalonia#11119]
**Describe the bug**
We have carousel, and if we cycle through all elements (to initialize it), and return to first and continue cycling, when first element doesn't detached. Here is example:  
![956607e6-4e25-4a89-9e08-1db3c1d3881a](https://user-images.githubusercontent.com/29896317/234126623-a75ac9fb-0c15-452c-909d-9090fc38d913.gif)

**To Reproduce**

Repro below
1. Create a new Avalonia `11.0.0-preview7` project
2. Add listbox with items (for cycling purposes)
3. Add carousel with items
4. Cycle it

**Expected behavior**
Carousel should remove old items.

- Version: 11.0.0-preview7

**Additional context**
Cycling code:
```
private void SelectingItemsControl_OnSelectionChanged(object? sender, SelectionChangedEventArgs e) {
    Carousel1.SelectedIndex = ListBox1.SelectedIndex;
}
```
[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/11314975/AvaloniaApplication1.zip)

**Comment by rabbitism** [comment]
A simpler reproduce:
1. Go to control catelog carousel page
2. press next 
3. press previous
4. press next again

and Carousel will jump back and forth between pic1 and pic2
