### ISSUE TITLE
MenuItem ICommand.CanExecuteChanged does not work via styles

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#11112]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/11110

<div type='discussions-op-text'>

<sup>Originally posted by **Tokter** April 24, 2023</sup>
I'm new to Avalonuia, so I'm not sure if this is a bug, or if I'm missing something.

If I'm binding a MenuItem to a command like this:

```xml
<MenuItem Header="Test" Command="{Binding	SaveCommand}" />
```

Then everything works fine, I can call RaiseCanExecuteChanged on my command and the menu item enables/disables accordingly:

```C#
        public void RaiseCanExecuteChanged()
        {
            CanExecuteChanged?.Invoke(this, EventArgs.Empty);
        }
```

If I bind the same command to a dynamically created MenuItem, and do the bindings via style. Then RaiseCanExecuteChanged() does nothing, the only time CanExecute() gets checked, is the first time the menu appears.

```XML
		<Style Selector="MenuItem">
			<Setter Property="Header" Value="{Binding Name}"/>
			<Setter Property="Items" Value="{Binding Items}"/>
			<Setter Property="Command" Value="{Binding Command}"/>
      <Setter Property="CommandParameter" Value="{Binding Playground}"/>
			<Setter Property="Icon">
				<Template>
					<PathIcon Data="{Binding Icon}" Width="14" Height="14" />
				</Template>
			</Setter>
		</Style>
````

Any help is appreciated, thanks!</div>

**Comment by timunie** [comment]
Here is a great sample to reproduce: 

> Here's a minimal project: [AvaloniaMenuItemIssue.zip](https://github.com/AvaloniaUI/Avalonia/files/11307646/AvaloniaMenuItemIssue.zip)
> 
> Steps to see the issue:
> 
> * First open both menus once
> * Execute command 1, that should disable command 1 and enable command 2
> * Inspect menus:
> 
> Compile time menu is in sync with the buttons: 
> ![image](https://user-images.githubusercontent.com/3439101/233925230-1f3a7c27-d971-44df-99e3-d16bd383f344.png)
> 
> Runtime bound menu has still Command 1 as active: 
> ![image](https://user-images.githubusercontent.com/3439101/233925357-1f436ae4-b145-44ae-b926-0c612555c7b0.png)

**Comment by maxkatz6** [comment]
Not a bug, answered in https://github.com/AvaloniaUI/Avalonia/discussions/11110

**Comment by timunie** [comment]
To clarify, the issue is about the command not being invalidated if the menu is not open while invalidated. Probably an issue with logical or visual tree.

**Comment by terinfire** [comment]
I was able to make a fix via behavior.  This would need to be patched in.  

In MenuItem.cs:

```
        private void SubMenuOpenChanged(AvaloniaPropertyChangedEventArgs e)
        {
            var value = (bool)e.NewValue!;

            if (value)
            {
                foreach (var item in ItemsView.OfType<MenuItem>())
                {
                    item.TryUpdateCanExecute();
                }

                RaiseEvent(new RoutedEventArgs(SubmenuOpenedEvent));
                SetCurrentValue(IsSelectedProperty, true);
                PseudoClasses.Add(":open");
            }
            else
            {
                CloseSubmenus();
                SelectedIndex = -1;
                PseudoClasses.Remove(":open");
            }
        }
```

would need to become

```
        private void SubMenuOpenChanged(AvaloniaPropertyChangedEventArgs e)
        {
            var value = (bool)e.NewValue!;

            if (value)
            {
                var found = false;
                foreach (var item in ItemsView.OfType<MenuItem>())
                {
                    item.TryUpdateCanExecute();
                    found = true;
                }

                //Not found in the ItemsView?  It's in the LogicalChildren.
                if(!found)
                {
                  foreach(var item in LogicalChildren.OfType<MenuItem>())
                  {
                    item.TryUpdateCanExecute();
                  }
                }

                RaiseEvent(new RoutedEventArgs(SubmenuOpenedEvent));
                SetCurrentValue(IsSelectedProperty, true);
                PseudoClasses.Add(":open");
            }
            else
            {
                CloseSubmenus();
                SelectedIndex = -1;
                PseudoClasses.Remove(":open");
            }
        }
```

**Comment by timunie** [comment]
@terinfire you maybe pointed me to the right direction. Opened a PR which fixes your sample for me at least. Thx ❤️
