### ISSUE TITLE
TextAlignment not working in preview7

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#11125]
**Describe the bug**
TextAlignment is not working, text always aligns left. 

**To Reproduce**

Take sample code from issue https://github.com/AvaloniaUI/Avalonia/issues/10852

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/14807942/234190076-5df41bf9-3826-4fa4-a4de-0a30d8a4226e.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version: master

**Additional context**

**Comment by kyuranger** [comment]
I met same issue here in preview 7.
