### ISSUE TITLE
Pasting into textbox does not trigger TextInputEvent

### ISSUE THREAD

**Issue by KuromeSan** [AvaloniaUI/Avalonia#11122]
**Describe the bug**
Pasting into textbox doesn't trigger TextInputEvent

**To Reproduce**

```
this.txtBox.AddHandler(TextInputEvent, onTxtInput, RoutingStrategies.Tunnel);
private void onTxtInput(object? sender, TextInputEventArgs e)
{       
    string? newTxt = e.Text;
    if (newTxt is null) newTxt = "";
    Console.WriteLine(newTxt);
}
```
if you type into the textbox, it comes up however pasting into it, it will not

**Expected behavior**
I expected the TextInputEvent to trigger when i pasted into the textbox, 
however this doesn't happen..

- OS: Windows 8.1
- Version 0.10.19

**Comment by maxkatz6** [comment]
It's expected. Text input is triggered, when user actually inputs some text. Also, this event is raised by the platform backend, not the text box.

If you want to handle text changes in the text box, you can either subscribe on PropertyChange and check if it was TextProperty, or in 11.0 previews there are two new methods TextChanging and TextChanged. 
Also, there is a TextBox.PastingFromClipboard event if you need it.

**Comment by KuromeSan** [comment]
unfortunately PastingFromClipboard does not allow you to see what the text you pasted actually was,.

**Comment by maxkatz6** [comment]
This event is raised before reading the clipboard, so developers can redefine what should be pasted. 
I.e., depending on expected behavior, developer can block text box from using default pasting behavior (args.Handled = true) and execute their own logic.
