### ISSUE TITLE
DevTools tabs switching doesn't work properly

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaUI/Avalonia#11120]
**Describe the bug**
Open any devtools on `11.0.0-preview7`, try to switch tabs:  
![9d703134-5532-4349-8f43-34a5849af26e](https://user-images.githubusercontent.com/29896317/234128119-10512e53-c823-4170-955f-0cdcb5850fbf.gif)

**Desktop (please complete the following information):**

- Version: `11.0.0-preview7`

Repro on this almost empty project from my last issue: 
[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/11315026/AvaloniaApplication1.zip)

**Comment by grokys** [comment]
Seems to have been caused by #11084, specifically this line:

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Diagnostics/Diagnostics/Views/TreePageView.xaml.cs#L46

`OnDataContextChanged` is called also when the `DataContext` is set to null.
