### ISSUE TITLE
Could not create glyphTypeface

### ISSUE THREAD

**Issue by bouyeijiang** [AvaloniaUI/Avalonia#11133]
Referencing 0.10.19 is normal, but using 11.0.0 preview 6 is abnormal.

![image](https://user-images.githubusercontent.com/4083760/234457565-c82c189d-e757-415f-9aa3-dcd5e9eacd96.png)

**Comment by yangjieshao** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/11084#issuecomment-1517190826

```
.With(new FontManagerOptions
            {
                DefaultFamilyName = "avares://AvaloniaTest/Assets/Fonts/微软雅黑.ttf#Microsoft YaHei",
                FontFallbacks = new[]
                {
                    new FontFallback
                    {
                        FontFamily = new FontFamily("avares://AvaloniaTest/Assets/Fonts/微软雅黑.ttf#Microsoft YaHei")
                    }
                }
            });
```

**Comment by bouyeijiang** [comment]
I have already resolved it:
.With(new FontManagerOptions
            {
                DefaultFamilyName = "avares://GCOM/Assets/Fonts#Microsoft"
            });

**Comment by yangjieshao** [comment]
> FontFallbacks = new[]
>                 {
>                     new FontFallback
>                     {
>                         FontFamily = new FontFamily("avares://AvaloniaTest/Assets/Fonts/微软雅黑.ttf#Microsoft YaHei")
>                     }
>                 }

```
FontFallbacks = new[]
                {
                    new FontFallback
                    {
                        FontFamily = new FontFamily("avares://AvaloniaTest/Assets/Fonts/微软雅黑.ttf#Microsoft YaHei")
                    }
                }
```
这个呢？  我在P6 和p7 用的是正常的

**Comment by bouyeijiang** [comment]
又试了，都可行了

**Comment by yangjieshao** [comment]
> 又试了，都可行了

- - 那你还不关掉

**Comment by 1324278444** [comment]
> 还没试过在linux是否正常捏

我现在windows都不行，字体文件不管设为AvaloniaResource还是复制到本地文件都不行都无法加载

**Comment by maxkatz6** [comment]
Seems like this issue was resolved. cc @Gillibald

**Comment by netsmallhao** [comment]
> .With(new FontManagerOptions
>             {
>                 DefaultFamilyName = "avares://AvaloniaTest/Assets/Fonts/微软雅黑.ttf#Microsoft YaHei",
>                 FontFallbacks = new[]
>                 {
>                     new FontFallback
>                     {
>                         FontFamily = new FontFamily("avares://AvaloniaTest/Assets/Fonts/微软雅黑.ttf#Microsoft YaHei")
>                     }
>                 }
>             });

Kylin V10 system  How did you solve it  ，My version is Avalonia 11.0.0 Still reporting an error

**Comment by Barryyue** [comment]
> > .With(new FontManagerOptions
> > {
> > DefaultFamilyName = "avares://AvaloniaTest/Assets/Fonts/微软雅黑.ttf#Microsoft YaHei",
> > FontFallbacks = new[]
> > {
> > new FontFallback
> > {
> > FontFamily = new FontFamily("avares://AvaloniaTest/Assets/Fonts/微软雅黑.ttf#Microsoft YaHei")
> > }
> > }
> > });
> 
> Kylin V10 system How did you solve it ，My version is Avalonia 11.0.0 Still reporting an error

![image](https://github.com/AvaloniaUI/Avalonia/assets/16954023/6848ed9c-d741-4fee-bb1d-c4569356173e)

**Comment by shuche** [comment]
我的麒麟V10系统，版本是Avalonia 11.1.1 报错解决不了。。。。

**Comment by aqingGitHub** [comment]
> 我的麒麟V10系统，版本是Avalonia 11.1.1 报错解决不了。。。。

你好，请问你解决了没呀？我也遇到同样的问题。
