### ISSUE TITLE
Preview7: "Unable to get org.kde.kdeglobals.General.AccentColor" on start

### ISSUE THREAD

**Issue by aldelaro5** [AvaloniaUI/Avalonia#11147]
**Describe the bug**
I am seeing the message ```Unable to get org.kde.kdeglobals.General.AccentColor``` whenever any application boot.

**To Reproduce**
Simply started the Sandbox project with the latest masters, but make sure to put this at the end of `OnFrameworkInitializationCompleted` because idk why, but this is needed to get the logs in rider:
```cs
Trace.Listeners.Add(new TextWriterTraceListener(Console.Out));
Trace.AutoFlush = true;
```
You should see the message after the application starts in Rider's console.

**Expected behavior**
To not see this. It only started appearing in preview7, this was not in preview6.

**Desktop (please complete the following information):**

- OS: Arch Linux kernel 6.2.8-arch1-1 #1 SMP PREEMPT_DYNAMIC
- Version 11.0.0-preview7

**Additional context**
I actually don't use kde. I use Cinnamon 5.6.8 which is why I find this error a little strange to appear like this.

**Comment by timunie** [comment]
Should be fixed by #11298
