### ISSUE TITLE
managed dialog crash

### ISSUE THREAD

**Issue by ChisterWu** [AvaloniaUI/Avalonia#11144]
**Describe the bug**
When I open  Filepicker or folder picker with managed dialog,  it crash.  

**To Reproduce**

1. Open sample ‘ControlCatalog.NetCore’
2. Go to 'Dialogs'
3. Scroll down to 'Picker' 
4. Click on 'FilePicker API'
5. Checked Force managed dialog
6. Click on 'Select Folder' or 'Open file'
7. See error

**Expected behavior** 
open any managed dialog will collapse.

**Screenshots**
![image](https://user-images.githubusercontent.com/28770378/234740405-dc7251f4-492e-46bf-a976-d2ccafaae5c3.png)

![image](https://user-images.githubusercontent.com/28770378/234740433-07b5df37-e89d-4c8f-b079-cd3745b76efa.png)

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [v11-preview7]

**Comment by maxkatz6** [comment]
Can you add more details?
Steps to reproduce and stacktrace at least.

**Comment by ChisterWu** [comment]
> Can you add more details? Steps to reproduce and stacktrace at least.

Sorry ,it was my mistake. I update for it.

**Comment by rabbitism** [comment]
I believe this issue can be closed by https://github.com/AvaloniaUI/Avalonia/pull/11265 cc @maxkatz6
