### ISSUE TITLE
[Clipboard] GetFormatsAsync empty on Windows

### ISSUE THREAD

**Issue by ADIX7** [AvaloniaUI/Avalonia#11140]
GetFormatsAsync returns an empty array. Is it a known behavior or a bug? Getting and setting text does work. I want to implement file copy/paste for my app. I was surprised that GetFormatsAsync is empty on Windows.

Windows 11 22H2
Avalonia 11.0.0-preview7

On linux I get an array with 13 items with the same codebase, same Avvalonia version.

**Comment by yll690** [comment]
On my computer it works well (Win10 22H2, Avalonia latest master version). 
Does clipboard in other program works well? Do you try on other computer? As I know some remote-desktop software could break clipboard.

**Comment by timunie** [comment]
@ADIX7 preview7 is pretty outdated now. Please try again using latest RC2.2 or even nightly builds. Thx.

**Comment by ADIX7** [comment]
It seems GetFormatsAsync must be called from UI thread. I cached a result from TopLevel of MainWindow in the constructor of MainWindow and got clipboard from it on a different thread in a service and somehow I did not get an exception but an empty array... After getting TopLevel every time instead of caching it I get the exception. Scheduling the code on UIThread solved the problem.
