### ISSUE TITLE
[CompiledBindings] Preview6-7: Exception thrown on close under specific circumstances

### ISSUE THREAD

**Issue by aldelaro5** [AvaloniaUI/Avalonia#11149]
**Describe the bug**
Essentially, I ran into a problem in my app where if some specifc conditions were met (mostly being on a specific tab) and you closed the window, it would throw an invalidCastException and I have no idea why.

**To Reproduce**

1. Download the zip I linked in this issue
2. Build the solution.
3. Start the application
4. Once the window appears, close the window using your platform's X button in the corner.
5. You should see an exception getting thrown before the app exits fully.

This is the error I get:
```
System.InvalidCastException: Unable to cast object of type 'BugFablesSaveEditor.ViewModels.MainViewModel' to type 'BugFablesSaveEditor.Models.BfNamedIdModel'.
   at CompiledAvaloniaXaml.XamlIlHelpers.BugFablesSaveEditor.Models.BfNamedIdModel,BugFablesSaveEditor.AllResourceNames!Getter(Object)
   at Avalonia.Data.Core.ClrPropertyInfo.Get(Object target) in /_/src/Avalonia.Base/Data/Core/ClrPropertyInfo.cs:line 27
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.InpcPropertyAccessor.get_Value() in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindings/PropertyInfoAccessorFactory.cs:line 88
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.InpcPropertyAccessor.SendCurrentValue() in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindings/PropertyInfoAccessorFactory.cs:line 132
```

**Expected behavior**
The application to exit cleanly without throwing.

**Desktop (please complete the following information):**

- OS: Arch Linux kernel 6.2.8-arch1-1
- Version 11.0.0-preview7, but it is reproducible in preview6

**Additional context**
Here is the zip of the best I could do to minimise the project that was reproducing the issue (I maneged to strip like 97% of the whole thing, but there's still a fair bit of abstractions that I don't really know how to reduce well for this): 
[Bug-Fables-Save-Editor.zip](https://github.com/AvaloniaUI/Avalonia/files/11340354/Bug-Fables-Save-Editor.zip)

Additionally, I was able to get a workaround: I did something like this in the mainWindow:
```cs
private void Window_OnClosing(object? sender, WindowClosingEventArgs e) => MainView.DataContext = null;
```
The MainView being the full one in my whole app. I am not sure why setting it to null causes no problems, but I can't quite figure out how to start investigating this one nor have an idea of how to reduce my repro further.

**Comment by MrJul** [comment]
A bit simpler repro:

XAML:
```xml
<Window
  xmlns="https://github.com/avaloniaui"
  xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'
  xmlns:local="clr-namespace:Sandbox"
  x:Class="Sandbox.MainWindow">

  <Window.DataTemplates>

    <DataTemplate DataType="local:ModelA">
      <TextBlock Text="{CompiledBinding PropA}" />
    </DataTemplate>

    <DataTemplate DataType="local:ModelB">
      <TextBlock Text="{CompiledBinding PropB}" />
    </DataTemplate>

  </Window.DataTemplates>

  <StackPanel>

    <StackPanel.DataContext>
      <local:ModelA />
    </StackPanel.DataContext>

    <Button Content="Go" Click="OnButtonClick" />

    <ContentControl x:Name="ContentControl">
      <ContentControl.Content>
        <local:ModelB />
      </ContentControl.Content>
    </ContentControl>

  </StackPanel>

</Window>
```

Click handler:
```csharp
private void OnButtonClick(object sender, RoutedEventArgs e)
{
    var contentControl = this.GetControl<ContentControl>("ContentControl");
    var panel = (Panel) contentControl.Parent!;
    panel.Children.Remove(contentControl);
    contentControl.Content = null;
    panel.Children.Add(contentControl);
}
```

Models:
```csharp
namespace Sandbox;

public class ModelA
{
    public int PropA { get; set; } = 123;
}

public class ModelB
{
    public string PropB { get; set; } = "ABC";
}
```

Click the button to crash.

When the `ContentPresenter.Content` changes after being removed from the logical tree, it incorrectly inherits from its parent context. The already applied data template gets this wrong context, and the compiled binding fails unexpectedly.

The root cause is that the built template tree isn't removed from the correct logical collection: https://github.com/AvaloniaUI/Avalonia/blob/9f64bad365880fa12d29d17eaecd68b92504f35a/src/Avalonia.Controls/Presenters/ContentPresenter.cs#L695

It's added to `Host.LogicalChildren` but removed from `this.LogicalChildren`. I'll open a PR to fix this and add a test.
