### ISSUE TITLE
binding error in scrollviewer

### ISSUE THREAD

**Issue by aldelaro5** [AvaloniaUI/Avalonia#11148]
**Describe the bug**
Since preview7, I am seeing a binding error for each scrollviewer present. I am not even attempting to bind anything, its presence is enough to cause this error to be logged.

**To Reproduce**
In the Sandbox project, change the Window to be this:
```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'
        x:Class="Sandbox.MainWindow">
  <ScrollViewer/>
</Window>
```
And (still don't know why this is needed), add these to the end of `OnFrameworkInitializationCompleted`:
```cs
Trace.Listeners.Add(new TextWriterTraceListener(Console.Out));
Trace.AutoFlush = true;
```
Now start the app, you should see an error like:
```
[Binding]Error in binding to 'Avalonia.Input.GestureRecognizers.ScrollGestureRecognizer'.'IsScrollInertiaEnabled': 'Null value in expression '{empty}' at '$self.TemplatedParent'.'(ScrollGestureRecognizer #44307222)
```

**Expected behavior**
To not see this binding error.

**Desktop (please complete the following information):**

- OS: Arch Linux kernel 6.2.8-arch1-1 #1 SMP PREEMPT_DYNAMIC
- Version 11.0.0-preview7

**Comment by amwx** [comment]
Based on the discussion in #5762, there isn't really anything that can be done as these are thrown from AvaloniaObjects that don't have a concept of being "attached". But these errors are showing up more often now, so could logging binding errors just be turned off by default? The push for CompiledBinding would mostly mitigate this, StaticResource throws an exception, and I don't think I've ever seen a DynamicResource error (that would've made some things easier); and with the number of logged errors showing up now it makes it difficult to find a "true" error if one pops up

**Comment by aldelaro5** [comment]
I don't think it's a good idea: I still get very useful binding errors and I am using compiled bindings all the way (even compatible with trimming).

My problem is more that I am seeing errors in places that I don't know if avalonia has issues or not. There's https://github.com/AvaloniaUI/Avalonia/issues/10846 that I opened which this one I doubt means nothing because there's def some problems related to tabs I been getting notably https://github.com/AvaloniaUI/Avalonia/issues/9438 being by far the worst one I am experiencing (had to do a workaround actually).

So if there is noise, then it's not as simple as turn it off completely.

**Comment by llfab** [comment]
I agree, such errors are useful. If they become more and more noisy they are not helping. If the only solution was to turn them off, then you could even remove them from the code completely (which I would not want)

**Comment by llfab** [comment]
Logging seems to be implemented in a quite generic fashion, hence, the objects throwing a warning do not have the context to decide whether that actually is a warning. So maybe that generic concept is not so good? Yes, it seems that putting that into less generic places would be some work.

**Comment by grokys** [comment]
I agree this is really annoying, will try to fix at some point soon - sorry, we've been prioritising serious bugs and breaking changes and although this isn't one, it needs to be addressed.
