### ISSUE TITLE
ComboBox opportunity to clear selected item

### ISSUE THREAD

**Issue by kulikov-dev** [AvaloniaUI/Avalonia#11151]
TextBox provides the user with the opportunity to clear all the text at once by pressing the button.
It would be nice if ComboBox had the same opportunity to clear selected item.

**Comment by maxkatz6** [comment]
As it was discussed in the telegram chat, it would be nice to add ComboBox.Clear() event (just like we have TextBox.Clear()).
So it can be executed from the custom templates, where users want to have an icon.

**Comment by timunie** [comment]
the question for me is, what should `Clear()` do? 
a) Set `SelectedItem` to `null` and / or
b) Set `SelectedIndex` to `-1`

**Comment by kulikov-dev** [comment]
> the question for me is, what should `Clear()` do? a) Set `SelectedItem` to `null` and / or b) Set `SelectedIndex` to `-1`

I would prefer just event 'OnClear' and process it on my side.

**Comment by rabbitism** [comment]
> the question for me is, what should `Clear()` do? a) Set `SelectedItem` to `null` and / or b) Set `SelectedIndex` to `-1`

Maybe both.
