### ISSUE TITLE
[11.0] App hangs when closing with debugger attached

### ISSUE THREAD

**Issue by satial-interfaces** [AvaloniaUI/Avalonia#11159]
**Describe the bug**
Closing the app (avalonia.xplat template) in desktop mode, will hang it, using VS Code and macOS Ventura (M1).

**To Reproduce**

1. Create a new avalonia.xplat based solution.
2. Update the version to preview7. 
3. Change the IControl reference to Control.
4. Run it from VS Code.
5. Close it.

**Expected behavior**
The application should close properly, stop the debugger and return to VS Code.

**Desktop (please complete the following information):**

- OS: macOS (M1)
- Version Ventura

**Comment by Gillibald** [comment]
Is a debugger attached to the application?

**Comment by Rwing** [comment]
me too.
and my IDE is rider, OS is macOS(intel)

**Comment by james-brighton** [comment]
Yes, the debugger is running. Without the debugger, the problem does not occur.

**Comment by xecrets** [comment]
Problem persists in 11.0.0-rc1.1, .NET 7, macOS 12.6.6 Monterey in both Visual Studio Code and Visual Studio 2022 for Mac.

**Comment by TheWerewolf** [comment]
Confirming the issue on 11.0.0-rc1.1, .Net 7, macOS Ventura 13.4 Visual Studio 2022 for Mac in debug and release.
Clicking on 'break' doesn't stop the app. If you quit VSMac the app keeps on running and has to be force quit.

**Comment by sergevm** [comment]
Same here, Monterey 12.6.6, dotnet 6, JetBrains Rider.

**Comment by kekekeks** [comment]
It seems to be either CLR bug or debugger bug, since:
- it only happens with debugger attached
- we've checked that `Main` exits correctly

We still do not know what exactly triggers it.

**Comment by TheWerewolf** [comment]
Actually, it’s happening in release for me as well.

Is there anything I can do to help test?

**Comment by kekekeks** [comment]
>Is there anything I can do to help test?

Yes, bisect the exact commit that introduced the issue.

**Comment by TheWerewolf** [comment]
I’ll try, but I’ve never tried building or deploying the entire kit.

It WAS on my list of things to do. 😉

**Comment by TheWerewolf** [comment]
Quick test:

0.10.19 Core 6/7 debug/release – quit works

0.10.21 Core 6 /7 debug/release – quit works

11.0.0-preview1 Core 7 debug/release – quit works

11.0.0-preview2 Core 7 debug/release – quit works

11.0.0-preview3 Core 7 debug/release – quit fails

11.0.0-preview4 Core 7 debug/release – quit fails

 

Previews 5-8 break the template app I generated for 0.10.x and I can’t generate a templated app lower than 11.0.0-RC1.1, and I’m having troubles rolling back from that to preview5-8 but I think we’ve found the point.

 

11.0.0-RC1.1 Core 6 or 7 debug or release – quit fails

**Comment by TheWerewolf** [comment]
A bit more info,

 

The hang happens AFTER Window.Closed event, so a (bad – very bad - hacky) temp solution is this:

 

public MainWindow()

{

              InitializeComponent();

              this.Closed += MainWindow_Closed;

}

 

private void MainWindow_Closed(object? Sender, System.EventArgs e)

{

              System.Diagnostics.Process.GetCurrentProcess().Kill();

}

 

It successfully terminates the macOS version of the app on 11.0-rc1.1 – but it’s a really bad solution since it also short circuits Avalonia’s actual shutdown process.

 

I’ve also compared snapshots of the Avalonia codebase at 11.0-prerelease2 and 3 and not seeing what might cause this, but still looking. There really weren’t that many changes between them in most of the code.

**Comment by Gillibald** [comment]
Probably worth it to try a commit before this change: https://github.com/AvaloniaUI/Avalonia/pull/9241

**Comment by TheWerewolf** [comment]
I was wondering if it might be MicroCom since that was one of the major changes between preview 2 and 3. 

I can give it a try tomorrow after work.

**Comment by TheWerewolf** [comment]
Having troubles building master around 9241 using the instructions "dotnet restore; dotnet run;" There seem to be some syntax errors and issues with XamlX... builds fine at the current master head though, I'll keep tinkering. :)

**Comment by jp2masa** [comment]
Did you update submodules?

**Comment by timunie** [comment]
@TheWerewolf I think one day there was an issue where the submodules were not updated correctly (maybe around the # you mention above. Try to init submodules again as @jp2masa suggested or if that doesn't help, do a fresh clone of Avalonia :-)

**Comment by TheWerewolf** [comment]
Thank you. I’ll try that.

 

I need a better Git client as well. 😊

 

TW

**Comment by TheWerewolf** [comment]
Ok.. bizarre thing. In the previous tests, I used the VS templates "Avalonia .NMet Core MVVM App (AvaloniaUI) C#, .Net 7, Community Toolkit, Avalonia Version 0.10.21, built it and it ran and worked on Windows. I moved the entire folder to MacOS and rebuilt and run and it worked as well and closed correctly.

I then used nuget to move the version of the Avalonia components forward, testing each time as above, and when I hit 11.0.0.-preview3, quitting the app caused it to hang.

I then went back to Windows and built a new project using the Template Studio for Avalonia and same selections except I selected 11.0.0-rc1.1 and that also hung on quit.

I've just pulled a fresh close of the entire Avalonia repository at head and built it on the Mac as per instructions and it worked... AND ControlCatalog.NetCore quits correctly! So not sure what's happening here. Is it possible an update between the published nuget 11.0.0-rc1.1 and the current

**Comment by timunie** [comment]
@TheWerewolf can you try to use nightly builds in your project and confirm if the issue is gone? In that case, this issue can probably be closed. 

Instructions: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed (*Mind the changed URL for nightly builds*)

Thank you for the testings 💐
