### ISSUE TITLE
Splitter position doesn't follow the cursor position

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#11162]
**Describe the bug**
The splitter position doesn't match the cursor position after moving it beyond the limits of the window or beyond the min/max allowed size

**To Reproduce**
Try to use a splitter that has defined some minWidths.
https://user-images.githubusercontent.com/501613/234911764-782f6f23-fa9d-42ba-9b85-bd9433e5ad42.mp4

**Expected behavior**
The splitter follows the mouse position.

**Desktop (please complete the following information):**

- OS: Windows, Mac, Linux
- Version preview7

**Comment by maxkatz6** [comment]
I wonder if it was the same in preview6 and needs similar fix https://github.com/AvaloniaUI/Avalonia/pull/11087/files

**Comment by maxkatz6** [comment]
Or more likely it was actually affected by that PR.
