### ISSUE TITLE
IStorageProvider.TryGetFolderFromPathAsync method causes the application to hang

### ISSUE THREAD

**Issue by berruezo** [AvaloniaUI/Avalonia#11164]
**Describe the bug**
When calling the method `IStorageProvider.TryGetFolderFromPathAsync` for any path, and trying to obtain its Result, the application hangs. I can't interact with it, nor close it - I have to kill the process
The issue happens on Linux but not on macOS

**To Reproduce**
Execute the following line from a `Window`:

`this.StorageProvider.TryGetFolderFromPathAsync(new System.Uri("/")).Result;`

Or run this minimal app https://github.com/berruezo/BrowseIssue
On macOS, the button does nothing (correct behavior) and you can continue interacting with the application
On Linux, the application is frozen after clicking the button

**Expected behavior**
The IStorageFolder should be returned

**Desktop (please complete the following information):**

- OS: Linux
- Avalonia 11.0.0-preview7

**Additional context**
This is the stack trace of the main thread when the application hangs on Linux:
![Screenshot_2023-04-27_17-57-48](https://user-images.githubusercontent.com/28261333/234918999-35e09ba0-c9e4-4070-9104-a2bf89e0ebf1.png)

**Comment by jp2masa** [comment]
Probably a deadlock, `Async` methods are supposed to be `await`ed. Calling `Wait` or `Result` will block and, most of the time, cause a deadlock.

**Comment by danipen** [comment]
Note that it works fine in macos and windows... Do you think the deadlock is platform-specific?

**Comment by maxkatz6** [comment]
> this.StorageProvider.TryGetFolderFromPathAsync(new System.Uri("/")).Result;

Platforms have different storage implementations. Some are in fact sync, some are async. Blocking async call is a bad practice and shouldn't be done not supported by framework.

**Comment by danipen** [comment]
Ok we will try to workaround making the call asynchronous. Justo note that this was working in `preview 4 `... just in case it's a regression.

**Comment by maxkatz6** [comment]
Note, there is a `Task<IStorageFolder?> TryGetFolderFromPathAsync(this IStorageProvider provider, string folderPath)` extension method, which will check if it's a classic desktop backend to get folder by path without converting Uri's. Also, might help with sync code, as part of the async [code is skipped on Linux](https://github.com/AvaloniaUI/Avalonia/blob/82c7c0d17b9f9cc633053cbf6bd0acddf28c8bab/src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs#L73) this way.

Still, keep in mind, block waiting on async code cannot be guaranteed to work. On some platforms, like Browser (which you don't target, but still), it's straight impossible.
