### ISSUE TITLE
Avolonia XAML Preview does not work with design time viewmodel properly occasionally

### ISSUE THREAD

**Issue by GeorgKapp** [AvaloniaUI/Avalonia#11187]
**Describe the bug**

The following code will result in the following error in the avolonia diagnostics window in visual studio:
System.Xaml.XamlException: 'Unable to resolve type MainViewModel from namespace using:CCA.Source.Features.Main Line 11, position 4.' Line number '11' and line position '4'.

View
```axaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="CCA.Source.Features.Main.MainView"
	xmlns:vm="using:CCA.Source.Features.Main"
        Title="MainView">

	<Design.DataContext>
		<vm:MainViewModel/>
	</Design.DataContext>

    <TextBlock Text="{Binding Title2}"/>
	
</Window>
```
ViewModel
```csharp
namespace CCA.Source.Features.Main;

internal partial class MainViewModel : ViewModelBase
{
    [ObservableProperty]
    private string _title2;

    public MainViewModel()
    {
        Title2 = "This is a test title";
    }
}
```

My Folder Structure:
![image](https://user-images.githubusercontent.com/46827863/235322050-50ed391e-3f9b-42a7-9476-3dae590ebaaf.png)

Removing the "Design.DataContext" attribute will show the preview again.
Also the behaviour in visual studio and rider differs:

Visual Studio 2022 Version: 17.5.4: The property "Title2" will not be suggested in visual studio
![image](https://user-images.githubusercontent.com/46827863/235321799-eedd38e1-5375-4c13-9078-2a3395c2ec38.png)
![image](https://user-images.githubusercontent.com/46827863/235321842-2c386e0c-cee6-4397-b8b1-e3bcf8c43e9d.png)

Rider 2023 Version 1.1 Build: RD-231.8770.54: Rider will show me at least the property suggestion
![image](https://user-images.githubusercontent.com/46827863/235321980-1d612f46-0ead-49e0-b815-85953d04bc95.png)

If i open the sample application from avalonia or create a new avalonia project without changing to a custom name eg: CCA, this error usually does not occur.
Debugging the project works without problems.

- OS: Windows
- Version 10.0.19045 Build 19045
- Nuget Packages: 
    Avalonia 0.10.19
    Avalonia.Desktop 0.10.19
    Avalonia.Diagnostics 0.10.19
    CommunityToolkit.Mvvm 8.2.0
    XamlNameReferenceGenerator 1.6.1

Am i doing something wrong here ?

**Comment by maxkatz6** [comment]
> Removing the "Design.DataContext" attribute will show the preview again.

This bug was fixed in 11.0 previews. In 0.10 you can use full clr-assembly syntax for xmlns attributes, including assembly name. Like `xmlns:custom="clr-namespace:SDKSample;assembly=SDKSampleLibrary"`.

> Visual Studio 2022 Version: 17.5.4: The property "Title2" will not be suggested in visual studio

I don't think it was implemented in [AvaloniaVS](https://github.com/AvaloniaUI/AvaloniaVS/issues/18) plugin. 
Rider has richer functionality built in.

Closing as fixed (in 11.0 with workaround for 0.10).
