### ISSUE TITLE
Bitmap CopyPixels has errors because it not copy the correct rect

### ISSUE THREAD

**Issue by xiaokun** [AvaloniaUI/Avalonia#11181]
the code in the CopyPixelsCore 
```
for (var y = 0; y < sourceRect.Height; y++)
  {
      var srcAddress = fb.Address + fb.RowBytes * y;
      var dstAddress = buffer + stride * y;
      Unsafe.CopyBlock(dstAddress.ToPointer(), srcAddress.ToPointer(), (uint)minStride);
  }
```
must changed to 
```
 for (var y = 0; y <sourceRect.Height; y++) 
{
    var srcAddress = fb.Address + fb.RowBytes * (y + sourceRect.Y) + sourceRect.X * 4;
    var dstAddress = buffer + stride * y;
    Unsafe.CopyBlock(dstAddress.ToPointer(), srcAddress.ToPointer(), (uint)minStride);
}
```

**Comment by kekekeks** [comment]
>` * 4;`
Note that pixel isn't guaranteed to take 4 bytes, it technically can be anything from 1 _bit_ to 128 _bits_ depending on the pixel format.

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/2866/files#diff-5002ef30a9c4ca91718f83b19d3cb8dc0425a5decdf67124cac8bae0fc251277R10

**Comment by xiaokun** [comment]
I mean the old code didn't take sourceRect.X and sourceRect.Y into account.

sourceRect.Y lines buffer and sourceRect.X pixels buffer needs to be skipped when calculating srcAddress in each line.

**Comment by dbriard** [comment]
@maxkatz6 Just run across this issue in 11.0.7, and after I checked the current code on Github, it is not fixed.

The code is still var srcAddress = fb.Address + fb.RowBytes * y;

This is blocking for the app I am working on, and I don't think there is a temporary workaround :(

**Comment by dbriard** [comment]
> Can you provide some code snippet that is failing for you?

Just use CopyPixels on a Bitmap with sourceRect with X and/or Y not zero.

Use case: I want to divide the Bitmap into tiles and call CopyPixels for each tile, all the tiles are the same because sourceRect.Position is ignored.

![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/aec47a17-ca25-46a7-a1c6-30eae017c0b3)

![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/2b1aa0b0-b958-49b7-a769-7d76e10d52b9)

**Comment by Gillibald** [comment]
Okay thanks

**Comment by dbriard** [comment]
@Gillibald Thanks for having a look! The tricky part is to handle rare PixelFormats where BitsPerPixel is not multiple of 8.

**Comment by dbriard** [comment]
FYI, there is useful code in WPF's WriteableBitmap > WritePixelsImpl to compute: outputBufferOffsetInBits, inputBufferOffsetInBits and copyWidthInBits.

But we cannot see the code of the copy function below.

```
internal extern static unsafe void MILCopyPixelBuffer( 
            byte *  pOutputBuffer,
            uint    outputBufferSize, 
            uint    outputBufferStride, 
            uint    outputBufferOffsetInBits,
            byte *  pInputBuffer, 
            uint    inputBufferSize,
            uint    inputBufferStride,
            uint    inputBufferOffsetInBits,
            uint    height, 
            uint    copyWidthInBits
            ); 
```

**Comment by maxkatz6** [comment]
@VladimirDrobyshev can you check latest master/nightly builds?

**Comment by VladimirDrobyshev** [comment]
> @VladimirDrobyshev can you check latest master/nightly builds?

Still reproducing on latest Master
