### ISSUE TITLE
Cursor "Hand" not working in WASM

### ISSUE THREAD

**Issue by doublecount** [AvaloniaUI/Avalonia#11202]
**Describe the bug**
In WebAssembly, setting the Cursor to "Hand" is not working

**To Reproduce**
See screenshot

**Expected behavior**
Show Hand-Cursor.
Works fine in Windows. Other Cursors "IBeam", "Cross", "Help" work in WebAssembly too.

**Screenshots**
![image](https://user-images.githubusercontent.com/87464788/235595595-60d1556f-d456-4de9-8b1c-487b46f1ffed.png)

**Additional context**

**Comment by maxkatz6** [comment]
Avalonia uses "pointer" browser cursor type for "Hand" value. 
https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Browser/Avalonia.Browser/Cursor.cs#L44

It should work fine.

**Comment by maxkatz6** [comment]
Seems to be a problem in this code: https://github.com/AvaloniaUI/Avalonia/blob/58ef07bc10bbb632b3af59ba85e345e4c9d12fb8/src/Browser/Avalonia.Browser/webapp/modules/avalonia/input.ts#L268-L274

It should clear value on "default" and not on "pointer".

**Comment by timunie** [comment]
Ah yes, seems like this will be the issue. I'll prepare a PR.
