### ISSUE TITLE
Unicode rendering bug

### ISSUE THREAD

**Issue by telecomadm1145** [AvaloniaUI/Avalonia#11201]
**Describe the bug**
Avalonia renders "月\\" as "月¥".
(The character "月" means month or moon in Chinese.)

**To Reproduce**
Render any text includes the unicode character "月" and character "\\"(for example, by placing it in a textbox or displaying it in a textblock)

**Expected behavior**
The text should be rendered correctly

**Screenshots**
Before inserting the character "月":
![图片](https://user-images.githubusercontent.com/47657299/235589918-2d754b8e-f83b-4782-86ad-748be6cc9a16.png)
After inserting the character "月":
![图片](https://user-images.githubusercontent.com/47657299/235589939-ea5276da-0e09-4f56-9160-e9b6da3599cf.png)

**Desktop (please complete the following information):**

- OS: Windows 11 (Build 25300)
- Version 11.0.0-preview4

**Additional context**
None

**Comment by timunie** [comment]
@telecomadm1145 preview4 is pretty outdated. Since we had many improvements regarding IME, please check preview7 or even better nightly builds. Please let us know if the error present, otherwise please close the issue.

**Comment by hez2010** [comment]
If you are using a Japanese locale/font, then \ will be rendered as ¥.

**Comment by telecomadm1145** [comment]
the issue disappears in preview7,thx
