### ISSUE TITLE
Text is not rendered properly in VisualBrush

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#11229]
**Describe the bug**
![image](https://user-images.githubusercontent.com/14807942/236174548-6b9e90cf-a7b7-4a53-89a0-d70e380884b4.png)

**To Reproduce**

rec in this sample is a Rectagle. 

**Expected behavior**
Clear Text

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version: preview7

**Additional context**

**Comment by rabbitism** [comment]
Originally discovered in https://github.com/AvaloniaUI/Avalonia/issues/10291

**Comment by Gillibald** [comment]
ClearType needs to be disabled here

**Comment by timunie** [comment]
I think only inside the Visual you added to your VisualBrush, so the TextBlock in this case. 

like this: 

```cs
var content = new TextBlock()
{
    Text = "Hello World", Foreground = Brushes.Blue
};

RenderOptions.SetTextRenderingMode(content, TextRenderingMode.Antialias);
```

Note: This works only in latest nightly builds.
