### ISSUE TITLE
Running on MacOS13.3.1 shows 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by imJack6** [AvaloniaUI/Avalonia#11259]
**Describe the bug**
When I tested Avalonia cross platform, I was able to run on both Windows and Linux, and also on MacOS13.3. However, after upgrading MacOS13.3.1 (possibly), it no longer worked properly.

**To Reproduce**

1. Running on MacOS13.3.1

**Expected behavior**
can run

**Screenshots**
![QQ截图20230506183049](https://user-images.githubusercontent.com/58357771/236618918-36938f14-c20d-4029-9590-bd8aa3982ff5.png)

**Desktop (please complete the following information):**

- OS: [MacOS]
- Version [13.3.1]

**Additional context**

**Comment by maxkatz6** [comment]
Can you attach full stack trace?

**Comment by imJack6** [comment]
> Can you attach full stack trace?

Sorry, I am a beginner and not very familiar with these, but I can show you my video of reproducing this issue. Currently, I have only tested versions 0.10.19 and 11.0.0 previews7, where 0.10.19 runs normally, but an error will be reported when it reaches 11.0.0 previews7. I have tested using NET6 and NET7, but NET6 cannot see detailed error information. NET7 is fine.

In the video, 

1. I first used the "dotnet new avalonia. app - o MyApp" command to generate an avalonia project.
2. In the second step, I opened it using Visual Studio 2022 for Mac. 
3. In the third step, I used the default generated project to run it successfully (at this time, the versions were NET6 and Avalonia 0.10.19). 
4. In the fourth step, I modified NET6 to NET7 and tried running it again, but it also ran successfully, 
5. In the fifth step, I upgraded the version of Avalonia to 11.0.0-preview 7 based on NET7 and removed the style code in XamlNameReferenceGenerator and App.axaml. I tried to run it, but it prompted System. NullReferenceException - "Object reference not set to an instance of an object." 
6. In the sixth step, I still uninstalled Avalonia 11.0.0-preview 7 and installed version 0.10.19 and XamlNameReferenceGenerator on the current basis, Run it again and it will be normal.

This is a reproduction video:
https://user-images.githubusercontent.com/58357771/236636545-491f6037-6ebe-4667-8b78-5de547dc395d.mp4

**Comment by maxkatz6** [comment]
To test with preview7 please create a new project from preview7 template as it will be easier.
Because on your video you did a mistake with removing FluentTheme - it should be still be used from Avalonia.Themes.Fluent package.

This command line creates a new preview7 project:
```
dotnet new avalonia.app -o MyApp -av=11.0.0-preview7 
```
You might need to update your templates though. See https://github.com/AvaloniaUI/avalonia-dotnet-templates or console messages.

Also, if this problem still repeats, please share full StackTrace value from the error dialog.

**Comment by imJack6** [comment]
> To test with preview7 please create a new project from preview7 template as it will be easier. Because on your video you did a mistake with removing FluentTheme - it should be still be used from Avalonia.Themes.Fluent package.
> 
> This command line creates a new preview7 project:
> 
> ```
> dotnet new avalonia.app -o MyApp -av=11.0.0-preview7 
> ```
> 
> You might need to update your templates though. See https://github.com/AvaloniaUI/avalonia-dotnet-templates or console messages.
> 
> Also, if this problem still repeats, please share full StackTrace value from the error dialog.

I use "dotnet new avalonia.app -o MyApp -av=11.0.0-preview7" The error is also "Object reference not set to an instance of an object"

This is the exception that replicates
`System.NullReferenceException: "Object reference not set to an instance of an object."
  at Avalonia.Native.WindowImpl..ctor(IAvaloniaNativeFactory factory, AvaloniaNativePlatformOptions opts, AvaloniaNativeGlPlatformGraphics glFeature)\n   at Avalonia.Native.AvaloniaNativePlatform.CreateWindow()\n   at Avalonia.Controls.Platform.PlatformManager.CreateWindow()\n   at Avalonia.Controls.Window..ctor()\n   at MyApp.MainWindow..ctor() in /Users/jack/Desktop/avatest/MyApp/MainWindow.axaml.cs:line 7\n   at MyApp.App.OnFrameworkInitializationCompleted() in /Users/jack/Desktop/avatest/MyApp/App.axaml.cs:line 18\n   at Avalonia.AppBuilder.Setup()\n   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)\n   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)\n   at MyApp.Program.Main(String[] args) in /Users/jack/Desktop/avatest/MyApp/Program.cs:12
`

**Comment by maxkatz6** [comment]
@imJack6 is it a virtual machine? Just in case.

**Comment by imJack6** [comment]
Yes, I saw other issues, maybe this error is related to the virtual machine
