### ISSUE TITLE
RefreshContainer does not show the refresh indicator

### ISSUE THREAD

**Issue by edgarfgp** [AvaloniaUI/Avalonia#11257]
**Describe the bug**

When testing the ControlCatalog samples. I notice that `RefreshContainer` does not seem to work.

```xaml
<DockPanel HorizontalAlignment="Stretch"
             Height="600"
             VerticalAlignment="Top">
    <Label DockPanel.Dock="Top">A control that supports pull to refresh</Label>
    <RefreshContainer Name="Refresh"
                      DockPanel.Dock="Bottom"
                      HorizontalAlignment="Stretch"
                      VerticalAlignment="Stretch"
                      PullDirection="TopToBottom"
                      RefreshRequested="RefreshContainerPage_RefreshRequested"
                      Margin="5">
      <ListBox HorizontalAlignment="Stretch"
               VerticalAlignment="Top"
               ItemsSource="{Binding Items}"/>
    </RefreshContainer>
  </DockPanel>
```

**To Reproduce**

1. Create a new app using Avalonia Templates
2. Copy over the code(XAML, ViewModel) from RefreshContainerPage.cs(ControlCatalog)
3. Run the app
4. RefreshContainer does not work(RefreshVisualizer is not visible)

**Expected behavior**
When trigger Pull to refresh, the RefreshVisualizer should be visible

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOs, IOS, Android
- Version Since preview 6

**Additional context**

**Comment by grokys** [comment]
I can repro this with ControlCatalog on current master: if I run on Windows with a touchscreen, pulling the `RefreshContainer` down has no effect.
