### ISSUE TITLE
Erro generated "cannot find suitable setter or getter for  Items Property" on comboBox and ListBox Items Property in Templated Controls

### ISSUE THREAD

**Issue by Noggington** [AvaloniaUI/Avalonia#11266]
**Describe the bug**
I upgraded to Avalonia 11.0.0 Preview 7 from Preview 6

After upgrade, I get the following error on templates control that use a Combo and ListBox when I try to set the items property using templatebinding.

The error I get is 
Error	AVLN:0004	Unable to find suitable setter or adder for property Items of type Avalonia.Controls:Avalonia.Controls.ItemsControl for argument Avalonia.Base:Avalonia.Data.IBinding, available setter parameter lists are:
System.Object

**To Reproduce**
Create a new Avalonia Cross Platform MVVM C# Application
Create a Templated Control where one of its properties is Items which is bound using TemplateBinding

The app wont build, but instead gives the error described above.

A sample app is included as zip

**Expected behavior**
The application should compile without this error as there were no code changes except for upgrading nuget packages to Preview 7

**Desktop (please complete the following information):**

- OS: Windows 10 21H2 & Windows 11 . Cross Platform MVVM App 
- Version 11.0.0-Preview7

**Additional context**
I have uploaded a sample project which is just the basic template control (doesn't do anything - so you can see the error)
[AvaloniaTemplatedControls.zip](https://github.com/AvaloniaUI/Avalonia/files/11414129/AvaloniaTemplatedControls.zip)
<img width="863" alt="image" src="https://user-images.githubusercontent.com/88229234/236663057-4ce89eae-f363-4d20-9fa3-169887b61c0b.png">

<img width="743" alt="image" src="https://user-images.githubusercontent.com/88229234/236663078-c40d8fba-56fc-4bf8-9d35-92647326af32.png">

**Comment by rabbitism** [comment]
You can read breaking changes. https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes
Here you need to change Items to ItemsSource.

**Comment by Noggington** [comment]
My Bad - I missed that when reading breaking changes - I'll give it a try thanks
