### ISSUE TITLE
Cannot change RadioButton corner radius

### ISSUE THREAD

**Issue by sakya** [AvaloniaUI/Avalonia#11261]
**Describe the bug**
I'm unable to change the RadioButton corner radius

**To Reproduce**
I tried to change the corner radius both using the RadioButton CornerRadius property and using a style like this
```
<Style Selector="RadioButton /template/ Border#RootBorder">
  <Setter Property="CornerRadius" Value="0" />
</Style>
```
With both methods the radio button does not change

**Expected behavior**
The corner radius should change

**Desktop (please complete the following information):**

- OS: Windows and Linux
- Version 0.10.19

**Comment by maxkatz6** [comment]
```
<Style Selector="RadioButton">
  <Setter Property="CornerRadius" Value="0" />
</Style>
```

**Comment by sakya** [comment]
Sorry, I didn't notice that in the style there was an override of the RadioButton control template...
