### ISSUE TITLE
Slider with tooltip not releasing mouse capture

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#11296]
**Describe the bug**
Something about having a tooltip is preventing `Slider` from releasing mouse capture, when the mouse button is released while outside the Avalonia window.

**To Reproduce**

1. Open the Control Gallery, and go to the Slider page
2. Start dragging the third slider (`SliderWithTooltip`)
3. Move the mouse outside the window
4. Release the mouse button
5. Move back into the window without pressing any buttons

The slider's thumb is still responding to the mouse. This does not happen with any other sliders on the page.

**Expected behavior**
The slider should not respond to the mouse after the mouse button has been released.

**Desktop (please complete the following information):**

- OS: Windows
- Version Git master

**Comment by maxkatz6** [comment]
I think the same problem is with GridSplitter, so probably Thumb is the reason.

**Comment by yll690** [comment]
I found 10.18 does not have this bug. So by comparing the stacktrace between 11.0 and 10.18, I found the problem may lays in `PointerOverPreProcessor.ClearPointerOver`. Then I add a simple check, seems solving the bug. I'm not sure if its correct.
```
        private void ClearPointerOver(IPointer pointer, IInputRoot root,
            ulong timestamp, Point? position, PointerPointProperties properties, KeyModifiers inputModifiers)
        {
            var element = root.PointerOverElement;
            if (element is null)
            {
                return;
            }

            // check if the element has been captured
            if(element == pointer.Captured)
            {
                return;
            }

            // other codes
        }
```

**Comment by mgnslndh** [comment]
This issue is probably the same as the one reported in #10904
