### ISSUE TITLE
Windows are not topmost after changing `WindowBase.Topmost` to be true by default

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#11307]
**Describe the bug**
We have a category of windows which should always be topmost, so we override the default value for `WindowBase.TopmostProperty` in a shared base class. The value is now `true` as expected, but instances of these windows are not topmost. [This is because `PlatformImpl` is only updated when the value _changes_,](https://github.com/AvaloniaUI/Avalonia/blob/482cf0295e7a31408792731e2a54e261aaae641e/src/Avalonia.Controls/WindowBase.cs#L48) which it never does.

**To Reproduce**

1. Execute this line of code: `WindowBase.TopmostProperty.OverrideDefaultValue<Window>(true);`.
2. Create and open a `Window`. It is not topmost.

**Expected behavior**
The window should configure its topmost-ness when its `PlatformImpl` is first created.

**Desktop (please complete the following information):**

- OS: N/A
- Version: Git master

**Comment by maxkatz6** [comment]
There quite a lot of issues with Topmost both on Win and macOS: https://github.com/AvaloniaUI/Avalonia/issues/4630 https://github.com/AvaloniaUI/Avalonia/issues/2841 https://github.com/AvaloniaUI/Avalonia/issues/7694
Making it easier to use popup in some cases which seem to have a better platform implementation.

All of it should be fixed with integration tests added.

**Comment by tomenscape** [comment]
The `os-windows` label is incorrect, this bug affects all platforms.

I don't see the connection to the other bugs, either. This isn't an issue with topmost itself, it's an issue with the WindowBase class not configuring itself correctly.

**Comment by tomenscape** [comment]
[The same problem exists for various `Window` properties.](https://github.com/AvaloniaUI/Avalonia/blob/f52fa669f3ef1e7e21478444b2a991bbe23dc02a/src/Avalonia.Controls/Window.cs#L179-L207)
