### ISSUE TITLE
TransitioningContentControl causes the control style to be lost during animation

### ISSUE THREAD

**Issue by BiDuang** [AvaloniaUI/Avalonia#11302]
English is not my native language; please excuse typing errors.

**Describe the bug**

`TransitioningContentControl` causes the control style to be lost during the `PageTransition` animation. For example, `Button` would lose its original style and only the text will remain.

![Bug Exmaple](https://cdn.friendship.org.cn/LightPicture/2023/05/bca718b05b0e2bcd.gif)

I have already read about #9621 and related PR #9802. But looks like Avalonia 0.10.19 didn't fixes this issue. Is this problem only fixed in 0.11.0 or later? Please let me know if there is a solution in 0.10.x.

**To Reproduce**

1. Create a project with Avalonia IDE plugin.
2. Set a `TransitioningContentControl` with `TransitioningContentControl.PageTransition` in `MainWindow.axaml`.
3. Try to change the content.

**Desktop (please complete the following information):**

Tested at:

- OS: Windows 10 22H2 19045.2846, Windows 11 22H2 22621.1555, Ubuntu-x64 20.04.5 LTS (KVM), Ubuntu-ARM64 22.04 

Thanks for your help.

**Comment by BiDuang** [comment]
> yes, #9803 fixes this. but It didn't roll back to version 0.10.x, I'm not sure why. @maxkatz6

I think 0.10.9 is still a release version of Avalonia, so how about push a small patch to fix this bug?

**Comment by timunie** [comment]
Atm almost all energy goes into 11.0. So while technically it can be fixed, its unlikely to be fixed soon in 0.10.x

**Comment by timunie** [comment]
As we now have 11.0 RC1 out and issue is fixed there, I think this issue can be closed. If anyone disagree, let me know.

**Comment by BiDuang** [comment]
> As we now have 11.0 RC1 out and issue is fixed there, I think this issue can be closed. If anyone disagree, let me know.

Okay, I have already migrated my project into the latest version. Thanks.
