### ISSUE TITLE
Failed to start debug session on M1 Max Chip system

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#11317]
**Describe the bug**

Debug session can not start on system with M1 Max Chip with following error message:

```
Failed to load /Users/laolarou/Documents/GitHub/LauncherX.Avalonia/LauncherX.Avalonia/bin/Debug/net7.0/osx-x64/libhostpolicy.dylib, error: dlopen(/Users/laolarou/Documents/GitHub/LauncherX.Avalonia/LauncherX.Avalonia/bin/Debug/net7.0/osx-x64/libhostpolicy.dylib, 0x0001): tried: '/Users/laolarou/Documents/GitHub/LauncherX.Avalonia/LauncherX.Avalonia/bin/Debug/net7.0/osx-x64/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/laolarou/Documents/GitHub/LauncherX.Avalonia/LauncherX.Avalonia/bin/Debug/net7.0/osx-x64/libhostpolicy.dylib' (no such file), '/Users/laolarou/Documents/GitHub/LauncherX.Avalonia/LauncherX.Avalonia/bin/Debug/net7.0/osx-x64/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
An error occurred while loading required library libhostpolicy.dylib from [/Users/laolarou/Documents/GitHub/LauncherX.Avalonia/LauncherX.Avalonia/bin/Debug/net7.0/osx-x64/]
```

**To Reproduce**

1. Get a random Avalonia project
2. Build and Debug using Visual Stuidio on the macOS
3. See error

**Expected behavior**

Debugger should start.

**Desktop (please complete the following information):**

- OS: macOS 13.3.1 (a) (22E772610a)
- Version: Latest Avalonia Nightly Build

**Comment by maxkatz6** [comment]
> An error occurred while loading required library libhostpolicy.dylib from

It's not an Avalonia dependency. Could be an issue with .NET runtime. Have you researched if it's a known problem on their side?

**Comment by Gillibald** [comment]
I wonder why the debug process is trying to load x64 binaries instead of native arm64. The error message clearly states there is a mismatch of architectures.

**Comment by maxkatz6** [comment]
Probably they have set RuntimeIdentifier to x64. And m1 is supposed to support x64 as well. 
But good point.

**Comment by laolarou726** [comment]
Manually installing the x64 version of .NET SDK solved the issue. Thank you guys so much!
