### ISSUE TITLE
NumericUpDown decrement/increment of null value is confusing

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#11318]
**Describe the bug**

Probably not quite a bug, but confusing behavior.
When empty NumericUpDown (with Value=null ) is decremented, value is getting reset to the NumericUpDown.
Which doesn't look right with default NumericUpDown.Maximum value - decimal.MaxValue.
Probably it should check if Maximum was set, if not - use Minimum (i.e. no decrement less then minimum) or reset to 0.

Same about incrementing.

![image](https://github.com/AvaloniaUI/Avalonia/assets/3163374/ceef5b03-9e41-49d9-95c7-8605c33170f2)

**Desktop (please complete the following information):**

- Version 11.0

**Comment by rabbitism** [comment]
😂 it is

**Comment by timunie** [comment]
I prefer 0 in case there is no maximum set. Should I work on this?

**Comment by maxkatz6** [comment]
@timunie note, 0 is not valid value, if Minimum is greater than 0. So it should be adjusted by these properties if it's set (`this.IsSet(MinimumProperty)`...)
