### ISSUE TITLE
Bogus warning when a `TopLevel` does not have a parameterless constructor

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#11312]
**Describe the bug**
If a `TopLevel` control does not have a parameterless constructor (e.g. because dependency injection is being used), [the compiler emits this warning](https://github.com/AvaloniaUI/Avalonia/blob/482cf0295e7a31408792731e2a54e261aaae641e/src/Avalonia.Build.Tasks/XamlCompilerTaskExecutor.cs#L551-L552):

> Avalonia warning AVLN:0005: XAML resource "avares://foo" won't be reachable via runtime loader, as no public constructor was found

This warning is bogus for a `TopLevel`, because as the name suggests it can only be a root element of a XAML file. A compile error regarding this was already fixed in #2593.

According to blame, the warning was introduced as part of #9541.

**Expected behavior**
No warnings are emitted when a `TopLevel` does not have a parameterless constructor.

**Comment by kekekeks** [comment]
> it can only be a root element of a XAML file

That is not true, you can have references to other toplevels, since XAML just builds an object graph.

**Comment by tomenscape** [comment]
That doesn't sound like a common use case to me. The warning should still be skipped, or at least demoted to a message.

I discovered just now that the warning `AVLN:0005` cannot be suppressed, probably because it's part of a special Avalonia compile process. Because our CI builds with warnings as errors, I now have to go back to including dummy parameterless constructors to keep Avalonia happy. This defeats the changes made to fix #2593.

**Comment by maxkatz6** [comment]
I agree that this warning is expected there. 
But as any other warning it should be possible to suppress. This is the actual bug in my opinion. Any ideas how to teach msbuild task to respect NoWarn?

Also, we can make TopLevel ad a special use case, but it won't be consistent with UserControl, which also can be used with DI (page navigation, mobile top level content...). 
Not a huge tradeoff though.

**Comment by kekekeks** [comment]
>. Any ideas how to teach msbuild task to respect NoWarn?

Pass `NoWarn` property as a task parameter

**Comment by lhsrebel72** [comment]
@kekekeks  any examples of this being done or guidleines on where and how to add this?

**Comment by RandallFlagg** [comment]
@maxkatz6 why close this issue and not fix the warning to not show in case of a parameter less constructor window? why do you think this is not a bug in Avalonia?

**Comment by timunie** [comment]
@RandallFlagg please check the PR #13447 and comments above. The linked PR will be available in 11.1

**Comment by topeterk** [comment]
Running version 11.0.10 now but warning is still there.
Is this warning by design? For me it still sounds like a false positive warning.
May workaround is still adding a dummy ctor or is there a better way now?
```csharp
        public Menu()
        {
            // Dummy constructor to resolve this issue:
            // Avalonia warning AVLN:0005: XAML resource "avares://SystemTrayMenu/UserInterface/Menu.axaml" won't be reachable via runtime loader, as no public constructor was found
            // See: https://github.com/AvaloniaUI/Avalonia/issues/11312
        }
```

**Comment by maxkatz6** [comment]
@topeterk it won't be backported to 11.0.
