### ISSUE TITLE
UI dos not refresh when press and hold mouse on  the window title bar

### ISSUE THREAD

**Issue by yangjieshao** [AvaloniaUI/Avalonia#11322]
**Describe the bug**
UI dos not refresh when press and hold mouse on  the window title bar

**To Reproduce**

1. start
2. Update data on child threads
3. Hold down the mouse on the window title bar
4. UI dos not refresh

**Screenshots**

https://github.com/AvaloniaUI/Avalonia/assets/3275834/e27a6e43-41f9-4796-95a2-e3163281edbe

**Desktop (please complete the following information):**

- OS: [Windows]
- Version [11.0.0-preview8]

**Additional context**
```
    public class MainWindowViewModel : INotifyPropertyChanged
    {
        public MainWindowViewModel()
        {
            Task.Run(() =>
            {
                while (true)
                {
                    Time = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff");
                    Task.Delay(1).Wait();
                }
            });
        }
        public string? Time
        {
            get => time;
            set
            {
                time = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Time)));
                Debug.WriteLine("PropertyChanged");
            }
        }
        private string? time;

        public event PropertyChangedEventHandler? PropertyChanged;
```

**Comment by yangjieshao** [comment]
> As an alternative, you can also use a `DispatcherTimer` which is imo the way to go to update data frequently.

看上去是鼠标按住窗口标题栏的时候，UI线程锁住了？
(It seems that the UI thread was locked while the mouse was holding down the window title bar?)
https://github.com/AvaloniaUI/Avalonia/assets/3275834/9899d795-416c-4384-adb8-e1d570751503

**Comment by jcyuan** [comment]
i don't think this is bug.
