### ISSUE TITLE
The CaptionButtons control spells Minimize and Maximize inconsistently

### ISSUE THREAD

**Issue by billhenn** [AvaloniaUI/Avalonia#11329]
I was theming the `CaptionButtons` class and noticed that there is inconsistent spelling of "Minimize" (currently "Minimise") and "Maximize" (currently "Maximise"), even in a PART name.

It would be ideal to stick with the US English version of the words instead of the British English version since those are what WPF is based on, and your pseudoclasses (`:minimized`, `:maximized`) and `WindowState` types are already using them.

## Part Name

```
[TemplatePart("PART_MinimiseButton",   typeof(Button))]
```

Should be:

```
[TemplatePart("PART_MinimizeButton",   typeof(Button))]
```

There are other variables that need to be renamed in the [CaptionButtons class source](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Chrome/CaptionButtons.cs) as well.

## AutomationProperties.Name

The `AutomationProperties.Name` assigned in templates like in the [Simple theme](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Simple/Controls/CaptionButtons.xaml) is using the British English version instead of the US English version.

## Summary

This is a quick change but one that should be made for consistency.

**Comment by timunie** [comment]
> This is a quick change but one that should be made for consistency.

I think this is also a breaking change, so should be done now or never.

@AvaloniaUI/core are we happy with such a PR at the current stage?

**Comment by billhenn** [comment]
Perhaps you could avoid the breaking change by looking for both part names if the UI English-spelled one isn't found?  It would be nice to get this in for v11 before it's permanently locked in.

**Comment by robloo** [comment]
This is definitely an API bug and should be consistent. The project already follows EN-US spelling for official API largely because of WPF legacy as you said. I think we definitely should fix this now.

If no one else will pick it up I'll plan to do it.

**Comment by robloo** [comment]
I'm opening a PR to close this shortly.

> And time to switch to static string member.

Feel free to bring this up again in the other issue. I think it can be done after 11.0 without breaking changes though.

**Comment by billhenn** [comment]
@robloo - The changes in the PR look good.
