### ISSUE TITLE
DynamicResources using FloatingResourceObservable don't update when theme variant changes

### ISSUE THREAD

**Issue by mgarstenauer** [AvaloniaUI/Avalonia#11324]
**Describe the bug**
`{DynamicResource ...}` bindings that internally use `FloatingResourceObservable` are not updated when the theme variant (Light, Dark) changes. (Resource bindings that internally use `ResourceObservable` work as expected.)

**To Reproduce**
–

**Expected behavior**
Properties that bind a resource from a theme dictionary should be updated when the theme variant is changed.

**Screenshots**
–

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.0.0-preview6, 11.0.0.0-preview8

**Additional context**
After reviewing `ResourceNodeExtension.cs` it looks like a bug in `FloatingResourceObservable.OwnerChanged`.
`FloatingResourceObservable` doesn't correctly attach to `ActualThemeVariantChanged`. Line 256 and 267 should be swapped. 

https://github.com/AvaloniaUI/Avalonia/blob/31e2f3375c8b913f9d02b3f858994540eef6ccc6/src/Avalonia.Base/Controls/ResourceNodeExtensions.cs#LL248C1-L271C14

**Comment by mgarstenauer** [comment]
I don't have a simple, isolated repro case. Please let me know if I need to provide more context.

**Comment by timunie** [comment]
Can you try with preview8 again please?

**Comment by maxkatz6** [comment]
Thank you for finding this bug. Can you submit a PR with this fix?
