### ISSUE TITLE
Support at ActualWidth and ActualHeight 

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#11325]
**Is your feature request related to a problem? Please describe.**
Semplify porting app form WPF

**Describe the solution you'd like**
Add read only DirecetPropery that act as a proxy for `Bounds.Width` and `Bounds.Height`.

**Describe alternatives you've considered**
(none)

**Additional context**
(none)

**Comment by robloo** [comment]
This has been discussed a few times before. As far as I know the behavior of Bounds is exactly the same. You can find/replace from WinUI or WPF code.

That said, if we ever get proxy properties this seems like a good compatibility step.
