### ISSUE TITLE
Low Opacity = No rendering

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#11332]
**Describe the bug**
When you set Opacity to a low value, 0.04 or 0.05, the element do not show at all.

**To Reproduce**
1. Try to add an element in the view
2. Set its opacity to something low such as 0.04 or 0.05
3. See that nothing is rendered
4. Increase opacity a little bit
5. Now the element is rendered

I don't know if it is a bug or a desired behavior?
And I don't know about the value, but:
In the designer, opacity = 0.04 render nothing, while 0.04001 render ok
In real application, opacity = 0.05 render nothing, while opacity = 0.06 render ok

**Expected behavior**
Opacity should work any low value.

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/4508dbdc-ce76-4c65-a68a-6b509a553385)
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/645d0616-f70d-409b-97a2-b01688e455f4)

**Desktop (please complete the following information):**

- OS: Windows 10 (and designer)
- Version 11 preview8

**Comment by jcyuan** [comment]
will it work if run directly with 0.05 without changing in devtools?

**Comment by MrJul** [comment]
Probably a typo here: https://github.com/AvaloniaUI/Avalonia/blob/31e2f3375c8b913f9d02b3f858994540eef6ccc6/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs#L212

Should be `0.004` instead since `1 / 255 ≈ 0.0039` so that's the threshold where white pixels become invisible.
I'll wait for a confirmation that this was the intended behavior then I can PR a fix.

**Comment by dbriard** [comment]
> Probably a typo here:
> 
> https://github.com/AvaloniaUI/Avalonia/blob/31e2f3375c8b913f9d02b3f858994540eef6ccc6/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs#L212
> 
> Should be `0.004` instead since `1 / 255 ≈ 0.0039` so that's the threshold where white pixels become invisible. I'll wait for a confirmation that this was the intended behavior then I can PR a fix.

Mystery resolved! 😃

**Comment by timunie** [comment]
> Probably a typo here:
> 
> https://github.com/AvaloniaUI/Avalonia/blob/31e2f3375c8b913f9d02b3f858994540eef6ccc6/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs#L212
> 
> Should be `0.004` instead since `1 / 255 ≈ 0.0039` so that's the threshold where white pixels become invisible. I'll wait for a confirmation that this was the intended behavior then I can PR a fix.

I think the actual value should be even `0.003` as otherwise 1/255 would still not pass which seems to be an actual valid value. I' kind of sure that such a PR will pass, so feel free to open one.
