### ISSUE TITLE
[DevTools] show time of event

### ISSUE THREAD

**Issue by MarnixCroes** [AvaloniaUI/Avalonia#11338]
**Is your feature request related to a problem? Please describe.**
I'm trying to figure out what event (/event chain) happens during a certain action in an app, but I'm unable to tell. 
![image](https://github.com/AvaloniaUI/Avalonia/assets/93143998/572d4043-9e35-4cc2-97e0-400f716edafc)
Which action is related to my recent scroll? IDK

**Describe the solution you'd like**
Show the time of an event

**How to implement**
Show it permanently, or with right click, or enable it as a setting?...

**Additional context**
Trying to repro a [bug](https://github.com/zkSNACKs/WalletWasabi/issues/10497) in Wasabi Wallet and see what the related event/ event chain is, but I'm unable to tell because of no time being displayed.

**Comment by yll690** [comment]
I agree with you so I try to implement it. However there are several problems:

1. I use the time where EventTreeNode.HandleEvent triggered as the event trigger time as it's inappropriate to add time property to `RoutedEventArgs`. It seems accurate enough however I'm not sure if it's the best way.
2. Is it nesassary to display time in event chain? I think no as they basiclly have the same trigger time.
3. Which format should the time be displayed in? The default format has no millisecond. The "O" format is too long. I prefer the "yyyy-MM-dd HH:mm:ss.fff" or simply "HH:mm:ss.fff". However I'm also worry about the localization.

```
private void HandleEvent(object? sender, RoutedEventArgs e)
{
    // other codes
    var s = sender!;
    var handled = e.Handled;
    var route = e.Route;
    var triggerTime = DateTime.Now;

    void handler()
    {
        if (_currentEvent == null || !_currentEvent.IsPartOfSameEventChain(e))
        {
            _currentEvent = new FiredEvent(e, new EventChainLink(s, handled, route, triggerTime));
            // other codes
        }
        else
        {
            _currentEvent.AddToChain(new EventChainLink(s, handled, route, triggerTime));
        }
    };
    // other codes
}
```

![image](https://github.com/AvaloniaUI/Avalonia/assets/16819902/ab72b3ca-5b0e-4d21-b9f8-541a8f0fce66)
![image](https://github.com/AvaloniaUI/Avalonia/assets/16819902/0d9f30c7-0454-45d6-82da-29afce384416)

**Comment by maxkatz6** [comment]
@yll690 thanks for looking into it!
1. Yes, it should be sufficient, as it's only a diagnostic tool.
2. No, no need to duplicate the same time. Order of events is known anyway.
3. "HH:mm:ss.fff" sounds good. Yes, it won't localize into details, but this format is still has enough information and is part of diagnostic tool
