### ISSUE TITLE
Opacity on element with CustomDrawOperation affect Clip or ClipToBounds

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#11343]
**Describe the bug**
I have a custom control that use CustomDrawOperation to blur an image.
ClipToBounds is false on element and its ancestors... 
The custom draw operation draw outside of the element bounds (what I want to do).
But when I set opacity to something different from 1, my element get clipped to its bounds (what I never asked for)

**Expected behavior**
Opacity on element with CustomDrawOperation should NOT clip to bounds, just change the opacity... 

**Screenshots**
Blur with Opacity=1
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/df942524-8441-4b89-b8ba-783196919070)

Same Blur with Opacity < 1 (the element is clipped, I don't want that).
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/03700ea7-da4a-4dca-b6e6-e2e26881efd8)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11 preview 8

**Additional context**

**Comment by kekekeks** [comment]
@Gillibald ?

**Comment by Gillibald** [comment]
Only possible if UseOpacitySaveLayer is enabled

**Comment by dbriard** [comment]
> Only possible if UseOpacitySaveLayer is enabled
> 
> @dbriard Please provide a minimal repro and I will have a look

@Gillibald @kekekeks 

Thanks for looking at this issue guys.
**The Opacity bug only happen when UseOpacitySaveLayer is enabled.**
Here is minimal repro:

[AvaloniaOpacityBug.zip](https://github.com/AvaloniaUI/Avalonia/files/11469359/AvaloniaOpacityBug.zip)

When writting this repro, I run into a new refresh bug: (happen with SaveLayer on or off)

1. Run the app -> the space around the image is not what I asked for, part of the image is missing at left and top.
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/10a65a4a-66c3-4fa4-9c4d-f146b079f6bf)

2. Change anything that refresh the image (opacity or blur slider, or resize the window)
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/bc3d4751-dfc8-47e6-be33-fe5ba623184f)

The image is in a border with uniform padding
`<Border Padding="100">
			<local:ImageFX x:Name="image"/>
		</Border>`
		
It is loaded in Window's Loaded event:
```
private void OnLoaded(object? sender, Avalonia.Interactivity.RoutedEventArgs e)
        {
            var loader = AvaloniaLocator.Current.GetService<IAssetLoader>();
            var s = loader.Open(new Uri("avares://AvaloniaOpacityBug/hirsch-899118_640.jpg"));
            var bitmap = SKBitmap.Decode(s);
            image.Source = bitmap;
        }
```

When the render function is called again without changing the sliders or resizing, for example when I ctrl+tab between VS and the app, the bug is still present, I have to change sliders or resize to remove it... 

and the values in the custom draw op are the same when the issue is visible or not:
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/da64bd98-8eb8-43ca-a8fa-e114de8ad2d9)

The issue is present in the designer too:
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/e332a6d5-e1f7-42bb-b301-24bc5a1b6266)

It is not present with the Avalonia Image, only with the custom draw image in the sample, which basically is the Avalonia image with IImage replaced with SKBitmap and render replaced with custom draw.

Hope that help...
