### ISSUE TITLE
Bitmaps showing incorrectly

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#11356]
**Describe the bug**
Bitmap show incorrectly and seems like there is a performance impact.

**To Reproduce**

Download the correct image below and show it in an `Image` control.

**Expected behavior**
Image shown like below.

**Screenshots**
Latest master (image blurry) -
![image](https://github.com/AvaloniaUI/Avalonia/assets/27368554/28081f58-e7c3-48f4-a27f-8564573edc27)

Correct - 
![image](https://github.com/AvaloniaUI/Avalonia/assets/27368554/4e1ffbed-2ef4-49b1-b17b-30a26d9c559c)

PNG -
![file](https://github.com/AvaloniaUI/Avalonia/assets/27368554/dc96b1ae-181f-4e83-9918-a49afce4eaa7)

**Comment by Gillibald** [comment]
Interpolation is disabled by default. This will be changed to low quality. You can set RenderOptions.BitmapInterpolationMode="HighQuality"

**Comment by robloo** [comment]
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/11319. Should close in favor of original issue.
