### ISSUE TITLE
[Regression] TextBox text selection is not set to End while SelectAll and click on white space after text

### ISSUE THREAD

**Issue by Mikolaytis** [AvaloniaUI/Avalonia#11350]
**Describe the bug**
TextBox text selection is not set to End while SelectAll and click on white space after text

https://github.com/AvaloniaUI/Avalonia/assets/4997065/10a557e4-f785-4d57-8a6d-644c248e2f57

On Any OS.

**Comment by rabbitism** [comment]
Actually it doesn't deselect at all even if you click on the selected area.
