### ISSUE TITLE
IME - Windows, avoid loss of selected result from IME when continue entering composition string

### ISSUE THREAD

**Issue by lnxon** [AvaloniaUI/Avalonia#11355]
**Describe the bug**
As a normal workflow to enter Japanese text, you enter some words and press spacebar or up/down arrow keys to select and convert it into the desired Kanji-mixed sentence. Then you PRESS ENTER TO CONFIRM the conversion. But, for easy operation, often you DO NOT PRESS ENTER and go straight to next words to convert. Even so, textbox should accept the selected Kanji as converted string and continue the composition of subsequent string entered.
Currently, you key-in the word, press spacebar, select the Kanji and if you DO NOT PRESS ENTER and go directly to next word, you loss the selected Kanji. 

**To Reproduce**

1. Open Clipboard page of the ControlCatalog
2. Enter for example "nihongo", press spacebar (see にほんご being converted to 日本語), avoid press ENTER and go directly type "nyuuryoku"
3. Selected word 日本語 is lost, remaining just にゅうりょく (or 入力)

**Expected behavior**
Should have entered 日本語入力 by steps above

**Screenshots**
See video below.

**Desktop (please complete the following information):**

-OS: [e.g. Windows, Mac, Linux (State distribution)]
Windows 10 Home 22H2 19045.2965
Version Avalonia 11.0.0.preview 8

**Additional context**

https://github.com/AvaloniaUI/Avalonia/assets/118665938/85216236-1c1a-4a2e-a3a1-964619a361af

**Comment by lnxon** [comment]
I really believe these features to easy operation are very important to wider adoption of Avalonia UI in Japan...

**Comment by Gillibald** [comment]
I think there must be a distinct flag present in the composition change message that we are not handling properly. Must likely the IME requests to commit current composition and adds a new composition at the same time.

I will be working on this next week to properly handle all these flags.

**Comment by Gillibald** [comment]
Interacting with IMM32 isn't straight forward. Each writing system has multiple IME and these IME can have their own distinct behavior. As long as you report these issues with an easy reproduction and a description how the natural behavior should be this is fixable.

**Comment by lnxon** [comment]
I noted that this issue HAS ALREADY BEEN CORRECTED FOR Avalonia 11.0.2! So I am closing this issue.
