### ISSUE TITLE
PlatformImpl.Handle not accessible

### ISSUE THREAD

**Issue by mgth** [AvaloniaUI/Avalonia#11367]
**Describe the bug**
PlatformImpl.Handle is reported as internal and cannot be accessed.

Checking source code, the interface is public, and I'm not aware of the possibility to make interface properties as internal, so I don't understand the error.

**To Reproduce**
put 
        `var handle = PlatformImpl.Handle.Handle;`
to window constructor, the first Handle is underlined and it does not compile.

**Expected behavior**
should compile

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 22H2

**Additional context**
Avalonia 11 preview 8 / Visual studio 2022 preview

**Comment by rabbitism** [comment]
Use WindowBase.TryGetPlatformHandle iirc

**Comment by kekekeks** [comment]
Every interface with `Impl` suffix has always been considered to be a private API that should only be available for out-of-tree platform backends. This rule is now enforced. Use `TryGetPlatformHandle` instead.
