### ISSUE TITLE
[Preview8] Dispatcher exception after re-creating lifetime

### ISSUE THREAD

**Issue by jangernert** [AvaloniaUI/Avalonia#11383]
**Describe the bug**
When re-creating the application lifetime to "reinitialize" the application the Dispatcher throws `"Cannot perform requested operation because the Dispatcher shut down"` with Avalonia 11 preview 8.

**To Reproduce**
Code to reproduce the behavior:

```
private static int StartApplication(string[] args)
{
    int exitCode;
    AppBuilder builder = BuildAvaloniaApp().SetupWithoutStarting();

    do
    {
        using (ILifetimeScope childScope = _container.BeginLifetimeScope())
        {
            using (ClassicDesktopStyleApplicationLifetime lifetime = new ClassicDesktopStyleApplicationLifetime())
            {
                lifetime.MainWindow = childScope.Resolve<MainWindow>();
                builder.Instance.ApplicationLifetime = lifetime;
                exitCode = lifetime.Start(args);

                // make sure that builder.Instance has no references to old instances
                lifetime.MainWindow = null;
                builder.Instance.ApplicationLifetime = null;
            }
        }

    } while (exitCode == -1);

    return exitCode;
}
```

The second iteration of creating a new lifetime and calling `Start()` will fail with above mentioned exception.

**Expected behavior**
A new application lifetime with a working dispatcher after the first loop.

**Desktop (please complete the following information):**

- OS: Window 10
- Version 11.0.0-preview8

# Additional Context
Looking at the code the `UIThread` Dispatcher is only created once and its `_hasShutdownFinished` is set to `true` after shutdown but never reset again. So it seems there is no chance for an application to work around the issue.

**Comment by kekekeks** [comment]
This behavior matches WPF and our 0.10.x behavior on macOS

**Comment by jangernert** [comment]
@kekekeks is it considered an issue? How would one reinitialize the whole application with a new lifetime?

**Comment by kekekeks** [comment]
You can implement your own lifetime that doesn't shut down the dispatcher or restart the process

**Comment by jangernert** [comment]
Okay, I'll try that. Thanks!
