### ISSUE TITLE
Un-globalize the rest of platform services

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#11381]
Those should be provided by a toplevel:

- [x] `IKeyboardDevice`
- [x] `IPlatformSetting` (should be split into two interfaces, one for colors which are required by App.xaml, another for the rest)
- [x] `PlatformHotKeyConfiguration`
- [x] `IClipboardImpl` (just remove from locator)

We should probably hide the locator as well, but it's sometimes usable for overriding stuff.

**Comment by workgroupengineering** [comment]
Just a curiosity?
Why did you think about this choice?
Wasn't it better to move these interfaces to Application?
Do you plan to instantiate a TopLevel without an App?
Will it be possible to instantiate more Applications?

This choice complicates access to services such as the Clipboard in MVVM scenarios, it will force you to pass the View to the ViewModel with the possibility of creating memory leaks. If moved to the application level it could be accessed simply like this:

```csharp
    var sp = Application.Current.TryGetFeature<IStorageProvider>();
```

**Comment by kekekeks** [comment]
1) Some platforms (like Android) require a _specific_ native view to get access to platform features, like clipboard, storage provider, etc.
2) It's possible to have several distinct types of output surfaces in Avalonia. Notable examples are offscreen content being exposed via VNC (see headless platform) or our own protocol (see IDE previewer and Avalonia.RemoteServer in general) and various embedding scenarios like video game engines, where you can have one set of input devices handled by the game engine and another set being handled by our platform backend that shows a proper devtools window

**Comment by workgroupengineering** [comment]
Thanks for the explanation.

**Comment by maxkatz6** [comment]
> IKeyboardDevice

I am not sure if this way is even needed at all as public API. Control should have sufficient focus navigation methods. And for keyboard input, it's as useless as MouseDevice.

**Comment by maxkatz6** [comment]
> We should probably hide the locator as well, but it's sometimes usable for overriding stuff.

We can mark locator methods unstable in 11.0. With a comment, that it shouldn't be used for DI and we don't guarantee API stability of anything inside of it.

**Comment by affederaffe** [comment]
In preparations for the wayland backend it might be a good idea to un-globalize `IRenderTimer` and `IRenderLoop` as well since each surface is told when to draw seperately, see https://wayland.app/protocols/wayland#wl_surface:request:frame

**Comment by maxkatz6** [comment]
IRenderTimer is used internally without any public APIs to read it globally, I think.
Except avalonia locator.

**Comment by kekekeks** [comment]
Technically we do allow customizations like forcing the render timer to tick on the UI thread. But I guess it could be moved to platform options instead
