### ISSUE TITLE
VS extension: Add templates for .NET Core 2.0

### ISSUE THREAD

**Issue by OronDF343** [AvaloniaUI/Avalonia#1139]
The templates included do not support netcoreapp2.0 and I can't change the target framework like in a standard .NET Core project created by VS (maybe due to the multiple targeting?). Editing the csproj (fixing the target) leads to many errors (same as those mentioned in #1134), so the best solution currently is to create a project manually.

**Comment by kekekeks** [comment]
With the new project system visual studio's UI is *completely* unusable, you have to edit csproj file manually.

**Comment by jkoritzinsky** [comment]
Our templates support .NET Core 2.0 so I'm going to close this issue.
