### ISSUE TITLE
Support Win11 Snap Layout with custom window decorations

### ISSUE THREAD

**Issue by WarWithinMe** [AvaloniaUI/Avalonia#11409]
**Is your feature request related to a problem? Please describe.**
In Win11, hovering the Maximize button will show Snap Layout. However, with `ExtendClientAreaToDecorationsHint="True"`, the default Window frame is removed, and the Min/Max/Close button is rendered by Avalonia, which results in losing the Snap Layout functionality.

**Describe the solution you'd like**
According to [this](https://github.com/grassator/win32-window-custom-titlebar/blob/832ed2d76b50ed33d6cd0f699f095caa8b144343/main.c#L278), the problem can be solved by processing `WM_NCHITTEST` message and returning `HTMAXBUTTON` when appropriate.

**Describe alternatives you've considered**
It would be better if we allow custom controls to specify which WM_NCHITTEST return value to be returned, i.e. `HTMINBUTTON`, `HTMAXBUTTON`, `HTCLOSE`...

**Additional context**
Snap Layout in Win11 (Howering the Maximize button shows a layout popup):
![image](https://github.com/AvaloniaUI/Avalonia/assets/567110/abda33a3-59b9-4814-a278-848cd538b6aa)

**Comment by andrewragy** [comment]
Any progress?

**Comment by timunie** [comment]
@andrewragy the issue has the help wanted badge. So if you need that feature, feel free to drop a PR to implement it. Otherwise you need to wait for someone else to pick it up.
