### ISSUE TITLE
context.custom() isn't always being called (even with InvalidateVisual)

### ISSUE THREAD

**Issue by cyraid** [AvaloniaUI/Avalonia#11400]
**Describe the bug**
When using context.Custom(drawop), following a `Dispatcher.UIThread.InvokeAsync(InvalidateVisual, DispatcherPriority.Background)`, it only repaints as 'needed' it seems (calling `Render()` of `ICustomDrawOperation` very seldom).

Using `context.FillRectangle()` for example inside Render will update always. Why is context.Custom(drawop) only being called seldom?

**To Reproduce**
Use SkiaSharp Example at: https://github.com/AvaloniaUI/Avalonia/blob/master/samples/RenderDemo/Pages/CustomSkiaPage.cs

**Expected behavior**
`context.Custom()` to draw whenever it's called.

**Desktop (please complete the following information):**

- OS: Windows 11

**Comment by kekekeks** [comment]
Rendering is driven by the render timer on the background thread, on Windows it's synchronized to the DWM refresh rate. 
A drawing op isn't guaranteed to be called if a newer one was submitted before the next frame.
