### ISSUE TITLE
Clicking "Open" or "Cancel" in OpenFileDialog closes application on Linux

### ISSUE THREAD

**Issue by the-owl** [AvaloniaUI/Avalonia#1141]
I have some code that shows an `OpenFileDialog` and prints selected filename to console:
```
private async void Open () {
    var openDialog = new OpenFileDialog();
    openDialog.Title = "Test";
    openDialog.AllowMultiple = false;

    var files = await openDialog.ShowAsync(this);
    if (files != null && files.Length != 0) {
        Console.WriteLine(files[0]);
    }
}
```

Dialog shows up and everything is fine until I click "Open" or "Cancel". If I click "Open", filename is printed to console, if I click "Cancel" nothing is printed, but in both cases application exits with code 0 and some GTK messages:
```

(dotnet:27559): Gtk-WARNING **: Failed to measure available space: Указанный адрес не поддерживается

(dotnet:27559): Gtk-WARNING **: Failed to measure available space: Указанный адрес не поддерживается
/home/theowl/words_small.txt

(dotnet:27559): GLib-GObject-CRITICAL **: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed

(dotnet:27559): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer

(dotnet:27559): GLib-GObject-CRITICAL **: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(dotnet:27559): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer

(dotnet:27559): GLib-GObject-CRITICAL **: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
The program '[27559] AvaloniaTest.dll' has exited with code 0 (0x0).
```

When I just close the dialog without clicking any buttons, the application does not crash.

OS: Fedora 26
GTK3 Version: 3.22.17
.NET Core: 2.0.0

Maybe this is related to #85, but in my case the messages from GTK are different and no exceptions are thrown.

**Comment by kekekeks** [comment]
Could you provide us with some repro project?

**Comment by the-owl** [comment]
https://github.com/the-owl/AvaloniaTest
Clicking "File -> Open" will open the dialog.

**Comment by aarroyoc** [comment]
I'm also affected

**Comment by jkoritzinsky** [comment]
I can replicate the GTK errors, but I can't replicate the crash with 0.6.1 with the repro @the-owl provided. So I'm going to mark this as fixed.
