### ISSUE TITLE
Strange Translation when control has Opacity < 1 and Maximise / Restore Occurs

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1142]
To repro:

1) Set screen scaling on windows display properties > 100% (I used 125%)

2) Run the control catalog and open the buttons page. (Ensuring at least 1 button has opacity < 1 ( some are disabled so this should be the case)

3) Maximise and restore (not minimise) the window a few times.

4) Note that opaque buttons are now translated.

**Comment by danwalmsley** [comment]
here is a demo of the same issue in Avalon studio.
https://files.gitter.im/AvaloniaUI/Avalonia/YNqe/avalonia-bug.gif

**Comment by kekekeks** [comment]
I think that #1183 is somehow related
