### ISSUE TITLE
Remove Dashed Line Properties from Border

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#11424]
**Is your feature request related to a problem? Please describe.**

In preparation for BackgroundSizing, dashed line properties need to be removed from Border. This was first discussed here: 
https://github.com/AvaloniaUI/Avalonia/issues/9946#issuecomment-1376650980.

**Additional context**

I think this must be done before 11.0 to avoid breaking changes in the 11.0 series.

@avaloniaui-team Thoughts?

**Comment by grokys** [comment]
Having said that, #9942 feels like reason enough to remove the property. Either it should work for all cases or should be removed.

**Comment by robloo** [comment]
@grokys Avalonia has two rendering code paths: one simple and one complex.

 1. Simple Path : This is the original border rendering code path used in Avalonia. It constructs simple rectangle geometry and passes it to Skia to render. Skia then renders uniform borders (on center edge) along with the background.
 2. Complex Path : With the addition of CornerRadius and non-uniform BorderThickness simple geometries were no longer enough to render borders. Skia itself isn't powerful enough to do this with existing rectangle geometries (even if it was passing the properties down into Skia would be problematic). To work around this, Avalonia now fully renders the background and border using complex geometries -- actual path geometries that can account for varying corner radius and non-uniform border thickness.

Well, when CornerRadius and the complex path was expanded #9942 became an issue. The complex path cannot take into account line dashes. Can you imagine the complexity of that geometry? It would be extremely expensive computationally. It worked before with the simple path because Skia was doing the work (as I understand it).

Well, now with BackgroundSizing we are going to have to remove the Simple path. Everything is going to need to be complex path geometries for the border and background elements. With removal of the simple path, dashes go too.

A benefit of this is there will only be one rendering path in Avalonia for this area going forward.

**Comment by maxkatz6** [comment]
I think there is no objections of removing it inside of the team. Especially when it was added mid 11.x.

**Comment by grokys** [comment]
Thanks for the explanation, @robloo - yeah that makes sense. I'm +1 on removing it then.
