### ISSUE TITLE
Drag&Drop with files is broken

### ISSUE THREAD

**Issue by affederaffe** [AvaloniaUI/Avalonia#11439]
**Describe the bug**
Since DataFormats.FileNames is marked as `Obsolete`, users are encouraged to use DataFormts.Files instead.
DataFormats.Files requires the usage of `IStorageItem` instead of strings, which makes it impossible to use file paths since `BclStorageFile/Folder` are internal.

**To Reproduce**

Drag the `files` text in the DnD page of the ControlCatalog.
The file path should be visible below, though `GetFiles` returns `null` since `dataObject.Get(DataFormats.Files)` is a `string[]` and not an `IEnumerable<IStorageItem>`.

**Expected behavior**
For supported platforms, there should be a way to create a `BclStorageFile/Folder` in order to use it for DnD.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Arch Linux

**Comment by maxkatz6** [comment]
I think control catalog was fixed before already. But this cast to array is wrong for sure. 

> For supported platforms, there should be a way to create a BclStorageFile/Folder in order to use it for DnD.

It's not an expected behavior. And dragndrop is not broken. 

You already can create a file from string. See StorageProvider.TryGetFileFromPathAsync (Or FromUriAsync).
