### ISSUE TITLE
SVGImage issue on CrossPlatform Avalonia application using 11.0.0-preview4

### ISSUE THREAD

**Issue by MattManuel03** [AvaloniaUI/Avalonia#11440]
Receive the following error when referencing an SVGImage in a source for an image.
System.IO.FileNotFoundException: 'Could not load file or assembly 'Avalonia.Visuals, Version=0.10.18.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'. The system cannot find the file specified.'

I ported over my UI from my Avalonia desktop project that was utilizing 0.10.19 and everything worked great.  After porting over the axaml code into the new project and all converted just fine but the SVGImage tags.

**To Reproduce**
Create a crossplatform application in visual studio using the MVVM Avalonia template.
Add the Avalonia.svg.skia nuget
Add the following tag to the ui and try to run the application
`<Image` Source="{SvgImage `/Assets/Minimal-Computer-Screen-Monitor.svg}"/>`

I received the error that I mentioned above.

I expected the this tag to work correctly in the new Crossplatform application as it did in the Avalonia Desktop application.

- OS: Windows 11
- Version 11.0.0-preview4

**Comment by maxkatz6** [comment]
You are using dependency built for 0.10 version of Avalonia. In order to use it with 11.0, please check if newer version of this dependency supports Avalonia 11.0.  Possibly there is a preview version of that dependency as well.
