### ISSUE TITLE
Images are aliased after goring from Preview 4 to Preview 8

### ISSUE THREAD

**Issue by lukaszossowski** [AvaloniaUI/Avalonia#11450]
After updating to the latest preview version (11 Preview 8) I noticed that all the images that I use are no longer aliased. 
Before:
![notaliased](https://github.com/AvaloniaUI/Avalonia/assets/112421929/d39cf2e0-74ca-488e-a582-409e68c9f484)
After:
![aliased](https://github.com/AvaloniaUI/Avalonia/assets/112421929/9d15d769-6c81-4fab-b2c9-4310daebe954)

In the picture above both the colour wheel and the tooltip icon in left upper corner are images that are resized. 

Is there something that changed in rendering of pictures or perhaps an option that I need to change?

**Comment by jp2masa** [comment]
#11319

**Comment by lukaszossowski** [comment]
Closing since it is a duplicate.

**Comment by timunie** [comment]
@lukaszossowski should be fixed in latest nightly, fyi.
