### ISSUE TITLE
ListBox set AutoScrollToSelectedItem to false is not work

### ISSUE THREAD

**Issue by myzhysz** [AvaloniaUI/Avalonia#11459]
**Describe the bug**
ListBox set AutoScrollToSelectedItem to false is not work

**To Reproduce**

1. Create a simple window has a ListBox with three TextBlocks. And set ListBox's AutoScrollToSelectedItem to false.
```c#
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="300" d:DesignHeight="200"
        x:Class="Avalonia1.MainWindow"
        Title="Avalonia1" Background="LightBlue"
		Width="300" Height="200">

	<Border Padding="20">
		<ListBox AutoScrollToSelectedItem="False">
			<ListBox.Items>
				<TextBlock Text="ABC" FontSize="32"/>
				<TextBlock Text="ABC" FontSize="32"/>
				<TextBlock Text="ABC" FontSize="32"/>
			</ListBox.Items>
		</ListBox>
	</Border>
</Window>
``` 
2. Run program and click the third TextBlock, the ListBox will scroll to end.
<img src="https://github.com/AvaloniaUI/Avalonia/assets/4530758/7dfdf94e-1a74-4b79-92fa-9a265d1ce1aa" width="300">

**Expected behavior**
When set AutoScrollToSelectedItem to false, ListBox should not scoll when select item. Like below.
<img src="https://github.com/AvaloniaUI/Avalonia/assets/4530758/08b534a2-b09c-4601-9d1a-d90452e888c2" width="300">

**Desktop (please complete the following information):**

- OS: [Windows 11 22H2]
- Version [since 11.0.999-cibuild0035149-beta]

**Comment by workgroupengineering** [comment]
Duplicate #6263

**Comment by grokys** [comment]
I don't think this is a duplicate, this issue is the opposite problem: that's it's scrolling when asked not to.

**Comment by grokys** [comment]
I think it is actually working, however what you're seeing is probably #11442 which is a slightly different mechanism (focus rather than selection). Try setting `<ListBox ScrollViewer.BringIntoViewOnFocusChange="False">`.

**Comment by myzhysz** [comment]
@grokys 
ScrollViewer.BringIntoViewOnFocusChange="False" solves this issue. Thanks very much, this issue can be closed.
