### ISSUE TITLE
Unable to bind to attached property on pointerover

### ISSUE THREAD

**Issue by Mochengvia** [AvaloniaUI/Avalonia#11452]
```
<Style Selector="Button:pointerover /template/ ContentPresenter">
	<Setter Property="Background"
		Value="{Binding Path=(local:ButtonHelper.HoverBackground), RelativeSource={RelativeSource Self}}"/>
</Style>
```

```
<Button Content="Button"
	local:ButtonHelper.HoverBackground="Blue" />
```

![anima](https://github.com/AvaloniaUI/Avalonia/assets/23360265/448f5ef0-606e-48a0-886f-d78ee1ddae37)

**Comment by maxkatz6** [comment]
I might be wrong, but "{RelativeSource Self}" in this binding will refer to the styled element - ContentPresenter.
If you want to bind to the button, the use `{Binding $parent[Button].(local:ButtonHelper.HoverBackground)}` (shorten syntax with $parent).

**Comment by Mochengvia** [comment]
The code works, thanks.
