### ISSUE TITLE
Hosting Avalonia User Controls in Windows Forms on DotNet 7+

### ISSUE THREAD

**Issue by fitdev** [AvaloniaUI/Avalonia#11454]
**Is your feature request related to a problem? Please describe.**

There is a need to gradually migrate some of our WinForms apps to Avalonia. To that end, we need to slowly, piece-by-piece replace WinForms user controls with Avalonia alternatives, eventually replacing the whole main window with one based on Avalonia. This approach requires us to be able to host Avalonia controls within WInForms Forms / UserControls.

So, I was trying to figure out a way to do it. The reverse  (hosting WinForms control inside of Avalonia app) seems pretty straight forward. Not so however with the other way around. I stumbled across `Avalonia.Win32.Interoperability` nuget package, however it was for an older Avalonia version and more crucially seemed to be targeting .Net Framework (as opposed to DotNet 7+). Researching a bit more I came across: [WinFormsAvaloniaControlHost](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32.Interop/WinForms/WinFormsAvaloniaControlHost.cs) from that same package.

So, I tried using it directly in my DotNet7 project. It was pretty easy to port. However there were 2 remaining issues:
- `private IntPtr WindowHandle => ((WindowImpl) _root?.PlatformImpl)?.Handle?.Handle ?? IntPtr.Zero;` could not be ported because apparently recently `WindowImpl` was made `internal`, nor was there a public interface on it that exposes the needed `IPlatformHandle Handle` propety.
- `EmbeddableControlRoot.FocusManager` was not there which I needed to port `if (_root.IsFocused) _root.FocusManager.ClearFocus();`, though this seemed less important.

I resolved the first issue with an ugly reflection hack, basically gaining access to `((WindowImpl) _root?.PlatformImpl)?.Handle?.Handle` through reflection, which for the purposes of testing sufficed.

So then I proceeded with a simple code to host my Avalonia control inside of WinForms:

```cs

  public Form1() {
    InitializeComponent();
    var avahost = new WinFormsAvaloniaControlHost(); // <-- Implemented in my project as I ported it from https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32.Interop/WinForms/WinFormsAvaloniaControlHost.cs
    panel1.Controls.Add(avahost);
    avahost.Dock = DockStyle.Fill;
    avahost.Content = new UserControl1();
  }
```

However once I ran my program, I would always be getting a pure white background in place where my Avalonia control should be.

**Describe the solution you'd like**
Basically I should just be able to host Avalonia control within any WinForms Form or User Control, so that we can migrate large WinForms app slowly over time, and this scenario is important not just for .Net Framework, but for modern DotNet (i.e. 7+)

- As an aside, for such scenarios it is especially important to be able to access Avalonia control's native handles (when they exist), such that there is no need to use Reflection hacks. These handles should be part of a public surface APIs.
- Also how should Avalonia be properly initialized for such a scenario (i.e. where the main program / app is WInForms). Do we just use `BuildAvaloniaApp().SetupWithoutStarting();` in our porogram main before we do `System.Windows.Forms.Application.Run(new Form1());`, or do we do something else?

**Describe alternatives you've considered**
There are really no feasible alternatives. Hosting WinForms inside Avalonia - doing it the other way around in other words is not really possible since the whole form would somehow need to be hosted inside of Avalonia. Not to mention there will still be a need to host Avalonia controls inside of WinForms container controls (until the entire UI was migrated to Avalonia).

**Additional context**
Using DotNet 7+ in VS 2022.

**Comment by profix898** [comment]
I agree that `Avalonia.Win32.Interoperability` needs to get fixed at some point (after the v11 release). However, for now, it is quite simple to include the ControlHost in your own project. Here is a minimal example. Hope it helps ...

[AvaloniaAppWinForms.zip](https://github.com/AvaloniaUI/Avalonia/files/11523072/AvaloniaAppWinForms.zip)

**Comment by jp2masa** [comment]
Did you check this sample?

https://github.com/AvaloniaUI/Avalonia/tree/7d879cf6febe500a6f5f7fcda786b88d075abbf0/samples/interop/WindowsInteropTest

**Comment by fitdev** [comment]
@profix898 Thanks so much for this sample. It's working great! Not sure what I did wrong but very similar code was not working for me.

I wish there was a way to replace this `var platformHandle = (IPlatformHandle?)platformImpl?.GetType().GetProperty("Handle", typeof(IPlatformHandle))?.GetMethod?.Invoke(platformImpl, null);` with something proper. Hope they can address this before v11.

**Comment by fitdev** [comment]
@jp2masa Thank you for the information. Somehow I missed this. And thanks for the tip on `TryGetPlatformHandle`.

**Comment by fitdev** [comment]
@jp2masa
Do you know if I still need in V11: `_renderer = ((TopLevel)avaloniaHost.Content.GetVisualRoot()).Renderer; _renderer.Start();` or setting `ControlHost.Content = new MyAvaloniaView();` is enough?

**Comment by fitdev** [comment]
Thank you all for your help. Thanks to @profix898 example I have got it working. Though I do think that:

1. It should be clarified somewhere that people on modern DotNet should use their own implementation of `WinFormsAvaloniaControlHost` slike the one provided by @profix898 above instead of using the older `Avalonia.Win32.Interoperability` package.

2. There is an urgent need to provide a clear public API to get at the Avalonia's control native handle without resorting to reflection hacks. I.e. no `var platformHandle = (IPlatformHandle?)platformImpl?.GetType().GetProperty("Handle", typeof(IPlatformHandle))?.GetMethod?.Invoke(platformImpl, null);` business.

**Comment by maxkatz6** [comment]
> It should be clarified somewhere that people on modern DotNet should use their own implementation of WinFormsAvaloniaControlHost slike the one provided by @profix898 above instead of using the older Avalonia.Win32.Interoperability package.

No need to clarify that. Instead this package should be updated to .NET Core. Due to low demand, it wasn't really touched in a while. If somebody from the community is willing to multitarget this project and test it, it can be accepted in 11.0 release.

It seems whole Avalonia.Win32.Interop package isn't published to the nuget since 11.0 previews. That's another problem that I need to fix.

> There is an urgent need to provide a clear public API to get at the Avalonia's control native handle without resorting to reflection hacks.

As mentioned above, TryGetPlatformHandle is the public API. But we might need to move it from Window class to a more general TopLevel class.

**Comment by fitdev** [comment]
> As mentioned above, TryGetPlatformHandle is the public API. But we might need to move it from Window class to a more general TopLevel class.

But how would I get it from `EmbeddableControlRoot`, if that's all I have as is the case with the implementation of WinFormsAvaloniaControlHost? I.e. there is no Avalonia Window to speak of since it is a WinForms app where Avalonia views/controls get embedded. So, perhaps it can be exposed on `ITopLevelImpl` in some form, since doing this `((WindowImpl)_root?.PlatformImpl).Handle` is not allowed because `WindowImpl` is internal?

**Comment by maxkatz6** [comment]
EmbeddableControlRoot is a TopLevel. As I mentioned, TryGetPlatformHandle should be moved from Window to TopLevel.

**Comment by timunie** [comment]
@fitdev this issue has the `help-wanted` label. Do you want to file a PR that does what @maxkatz6 suggests?

**Comment by fitdev** [comment]
@timunie I am very new to Avalonia and do not know much about it and what is expected in terms of coding practices, etc. Therefore at this stage I am not the best candidate for such a thing to put it mildly.

**Comment by fitdev** [comment]
Actually since this looked simple enough, decided to give it a try. Hopefully everything that was needed is in my PR.

**Comment by timunie** [comment]
@fitdev everyone has started at some point. The PR will be checked and if there is anything that is "wrong" or could made different, you'll get the feedback. 

Thanks for your contribution btw 🙏

**Comment by fitdev** [comment]
@profix898 Thank you for giving a hint. Hopefully corrected it this time.
@timunie I know. But since this project is not really my area of expertise I did not feel like I am eligible for contributing.

**Comment by maxkatz6** [comment]
@fitdev thanks! I will do the rest with updating interop package and making it publish to the nuget again.

**Comment by StornZ** [comment]
> Did you check this sample?
> 
> https://github.com/AvaloniaUI/Avalonia/tree/7d879cf6febe500a6f5f7fcda786b88d075abbf0/samples/interop/WindowsInteropTest
> 
> **EDIT:** I see, it's actually kind of broken. To get the handle you can use `TryGetPlatformHandle` I think ([Breaking Changes Wiki](https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#platform-implementation-members-were-hidden-from-the-ref-assemblies)). The white control is probably because you need to start the renderer manually, like the sample in the link.

I was referencing this and thought I was going insane when stuff didn't work.  Breaking changes weren't corrected in the samples yet I suppose.

**Comment by StornZ** [comment]
> I agree that `Avalonia.Win32.Interoperability` needs to get fixed at some point (after the v11 release). However, for now, it is quite simple to include the ControlHost in your own project. Here is a minimal example. Hope it helps ...
> 
> [AvaloniaAppWinForms.zip](https://github.com/AvaloniaUI/Avalonia/files/11523072/AvaloniaAppWinForms.zip)

This solution won't work anymore with the breaking changes that came about sometime between 11.0.0-preview8 and the release candidate 11.0.0-rc1.1. I'm trying to figure out how to make the WinFormsAvaloniaControlHost that you've provided work with the release candidate. Renderer changed, but looks like they added a start and stop renderer. Focus Manager was internalized and I don't have a solution for that one yet.

**Comment by maxkatz6** [comment]
@StornZ this issue was already fixed and winforms controls was already updated.
