### ISSUE TITLE
Value cannot be changed through the Setter after the property is bound

### ISSUE THREAD

**Issue by Mochengvia** [AvaloniaUI/Avalonia#11464]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/11463

<div type='discussions-op-text'>

<sup>Originally posted by **Mochengvia** May 21, 2023</sup>
It seems that in Avalonia, the value of a property cannot be modified once it is bound.
I bind a custom attached property VisualStateHelper.Background to the Background property of the TemplatedControl, and when I try to modify its value in the Setter, it doesn't take effect.
If I remove the binding code then everything works fine.
Is there any way to solve this problem ?

```
//Codes in VisualStateHelper
private static void OnRegistChanged(IAvaloniaObject sender, ICommand? command)
{
    if (sender is TemplatedControl control)
    {
        control.Bind(BackgroundProperty, new Binding()
        {
            Path = "Background",
            Source = control,
            Mode = BindingMode.OneWay,
        });
    }
}
```

```
//Codes in style
<Style Selector="Button">
  <Setter Property="i:VisualStateHelper.Regist" Value="True" />
  <Setter Property="Template">
    <ControlTemplate>
      <ContentPresenter Name="PART_ContentPresenter"
        Background="{Binding Path=(i:VisualStateHelper.Background), RelativeSource={RelativeSource TemplatedParent}}"
        .../>
    </ControlTemplate>
  </Setter>
</Style>

<Style Selector="Button:pointerover">
  <Setter Property="i:VisualStateHelper.Background" Value="Red"/>
</Style>
```

**Comment by tomenscape** [comment]
Your method is binding the property with "local" priority. This is a higher priority than values provided by styles, and so will always override them.

A better solution to your problem would be for your method to apply a class to the control, and then write a style which activates when that class is active. This style would be able to replace any other value set by another style.

**Comment by Mochengvia** [comment]
I understand what you mean.
But I found another way, if I try to bind Background in xaml then everything works fine.
```
<Style Selector="Button">
	<Setter Property="i:VisualStateHelper.Background"
			Value="{Binding Background, RelativeSource={RelativeSource Self}}"/>
</Style>

<Style Selector="Button:pointerover">
	<Setter Property="i:VisualStateHelper.Background" Value="Red"/>
</Style>
```
Can you tell me what is the difference between these two ways? In other words, how do I implement this binding through codebehind》

**Comment by timunie** [comment]
@Mochengvia see https://docs.avaloniaui.net/docs/styling/troubleshooting#locally-set-properties-override-styles

**Comment by Mochengvia** [comment]
After setting Priority to TemplatedParent everything works fine. Thanks.

```
control.Bind(BackgroundProperty, new Binding()
{
    Path = "Background",
    Source = control,
    Mode = BindingMode.OneWay,
    Priority = BindingPriority.TemplatedParent
});
```
