### ISSUE TITLE
[Android] App crashes when started from intent fiilter

### ISSUE THREAD

**Issue by lukaszossowski** [AvaloniaUI/Avalonia#11468]
Crash when app is started from intent filter (android.hardware.usb.action.USB_DEVICE_ATTACHED)

My app connects to a device via usb serial. I also have an intent filter to automatically start the app when a device with specified vid/pid is connected. However, the device crashes when it starts automatically that way. 

I have the following crash log from my phone:

> --------- beginning of crash
05-21 21:44:29.296 13801 13801 E AndroidRuntime: FATAL EXCEPTION: main
05-21 21:44:29.296 13801 13801 E AndroidRuntime: Process: LHDesigner, PID: 13801
05-21 21:44:29.296 13801 13801 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object.
05-21 21:44:29.296 13801 13801 E AndroidRuntime:    at Avalonia.Android.Platform.SkiaPlatform.TopLevelImpl.CreateRenderer(IRenderRoot root)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:    at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:    at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:    at Avalonia.Controls.Embedding.EmbeddableControlRoot..ctor(ITopLevelImpl impl)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:    at Avalonia.Android.AvaloniaView..ctor(Context context)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:    at Avalonia.Android.AvaloniaMainActivity.OnCreate(Bundle savedInstanceState)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:    at LHDesigner.Android.MainActivity.OnCreate(Bundle savedInstanceState)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at crc643195a8c2474eeb97.MainActivity.n_onCreate(Native Method)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at crc643195a8c2474eeb97.MainActivity.onCreate(MainActivity.java:38)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8591)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8570)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8757)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
05-21 21:44:29.296 13801 13801 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

When it is started manually everything works fine. Also as far as I remember the app worked from autostart before I updated my phone to the latest Android version.

I am currently on 11.0 Preview 4.

**Comment by maxkatz6** [comment]
> I am currently on 11.0 Preview 4.

Please update. We do not support half year old preview versions.

> I have the following crash log from my phone:

Is AppBuilder initialization executed in your project? In later previews it was moved from MainActivity to SplashActivity in templates, but you can call it manually.

**Comment by lukaszossowski** [comment]
> > I am currently on 11.0 Preview 4.
> 
> Please update. We do not support half year old preview versions.

I'd love to, but after updating to preview 8 my app has abysmal performance, so I am waiting for 11.0 release.



 >>  I have the following crash log from my phone:
>
>Is AppBuilder initialization executed in your project? In later previews it was moved from MainActivity to SplashActivity in >templates, but you can call it manually.

Thanks for pointing me in the right direction. I am very new to mobile so not everything is clear to me. The issue seems to be as follows:

When I put the intent filter to the main activity, open the app and connect my device, it asks if I want to open this app (already running) to service the device:

> Allow MyApp to access MyDevice? 
> (optional) Always open MyApp when MyDevice is connected.

 If I agree then my device connects properly and it remembers the permission every time it is run manually again. But since the intentfilter is on mainactivity, when I connect the device with nothing running, I'm guessing it starts the mainactivity (without the splashactivity) which causes the app to crash, because appbuilder is executed in the omitted splashactivity.

However, when I put the intentfilter in the splashactivity it works fine when the app is started automatically (because it runs the splashactivity which in turn starts the mainactivity). However when I start the application manually and then connect my device, the app crashes with the following error: 

>System.InvalidOperationException: 'Setup was already called on one of AppBuilder instances' 

Which I'm guessing is because the app is already running, and the intentfilter starts the splashactivity again.

It worked in earlier version because I was using an older Avalonia version with only MainActivity (which was of type AvaloniaActivity<App> and had the builder run there) and my phone Android version was below Android 12 which made splash screen no longer optional.

I am quite stumped on how to resolve this. 
1. If I skip the intentfilter and manually ask for permission every time my device is connected, the permission is not remembered and thus annoying. 
2. If I put the intentfilter in the splashactivity, it will crash my app every time I connect my device when mainactivity is already running.
3. If I put the intentfilter in mainactivity, it will crash the app when it is automatically started by connecting my device.

I'm guessing this might not be an Avalonia issue anymore, but perhaps some solution would be to leave the intentfilter in mainactivity and run the appbuilder manually, I would very much appreciate information on how/where to do that.

**Comment by maxkatz6** [comment]
> I'd love to, but after updating to preview 8 my app has abysmal performance, so I am waiting for 11.0 release.

It's important to report this kind of problem, as I don't think we have any known performance issue of that scale. It might end up getting to the release as well.

**Comment by lukaszossowski** [comment]
> @lukaszossowski best way for us to look into it would be a simple sample App demonstrating just the issue you have mentioned above. Maybe this gives us a clue where to look at.

Do you mean the crashing issue or the Preview 8 performance one? The crashing issue seems to be at least mostly not Avalonia related, I will have to learn more about activities and intents to hopefully find a way to solve it.

When it comes to the performance issue, I will give it another go when I have more time, but when I first did the update from Preview 4 to Preview 8 I noticed that tha app runs far slower now (only in Debug though, Release is fine), but other than perceived choppiness the only other thing that stood out is the fact that my navigation and info bar colours (on top and obttom of phone) no longer have the color specified in the styles.xml but rather default white. I will gladly make an issue out of it once I have something more concrete to describe.

**Comment by timunie** [comment]
@lukaszossowski do you agree to closing this issue? Feel free to open another issue with the performance impact you see, but please add a way to reproduce the issue. So that we are able to work on a solution.

**Comment by lukaszossowski** [comment]
Sure, the actual issue I had turns out to not be strictly Avalonia related, so I'm closing it.
