### ISSUE TITLE
grid.ShowGridLines Binding doesn't work

### ISSUE THREAD

**Issue by zBugi** [AvaloniaUI/Avalonia#11478]
**Describe the bug**
When binding the ShowGridLines parameter, the window/usercontrol doesn't refresh the view I even tried InvalidateVisual().
Setting the value that is bound to ShowGridLines to false and then resizing the window it crashes.

**To Reproduce**
1. Set the ShowGridLines value from true to false while your app is running
2. Resize the window or even a part of the grid
3. see error 

**Expected behavior**
The gridlines shouldn't be visible after setting the bound value to false and you can archive it through the following workaround but there this is just a "reopen" to get the rendering happen again.
```csharp
private bool _ShowGridLines = false;
        public bool ShowGridLines
        {
            get => _ShowGridLines; set
            {
                this.RaiseAndSetIfChanged(ref _ShowGridLines, value);
                IReadOnlyList<Window>? windows = ((IClassicDesktopStyleApplicationLifetime?)Avalonia.Application.Current?.ApplicationLifetime)?.Windows;
                if(windows != null)
                foreach (Window window in windows)
                {
                    if (window.DataContext == this)
                    {
                        // rebuild the window:
                        var newWindow = new MainWindow();
                        newWindow.DataContext = window.DataContext; // Preserve the data context of the existing window
                        newWindow.Show();

                        (window as Window)?.Close(); // Close the existing window
                    }
                }
            }
        }
```
- OS: Windows 11
- Version 0.10.19

**Comment by timunie** [comment]
fyi: I can confirm this happens in latest master (Sandbox tested) as well
