### ISSUE TITLE
AvaloniaObject.CoerceValue invokes callback multiple times and uses previously coerced value on subsequent invocation.

### ISSUE THREAD

**Issue by boydpatterson** [AvaloniaUI/Avalonia#11484]
**Describe the bug**
If a `StyledProperty` is defined with a value coercion callback and the `AvaoloniaObject.CoerceValue` is called for that property, the coercion callback is invoked twice.

On first invocation, the current value (`null` in my testing) is passed as the value to coerce and a non-null string is returned. Then a second invocation occurs where the non-null string from the first invocation is passed as the value to coerce.  If `CoerceValue` is called again for the same property, it continues to call the invocation twice, but both calls will pass the non-null coerced string from the original invocation. The original `null` value appears to be completely lost and permanently replaced by the first coerced value.

**To Reproduce**
[CoerceDemo.zip](https://github.com/AvaloniaUI/Avalonia/files/11537135/CoerceDemo.zip)
Attached are two projects. AvCoerceDemo (Avalonia demo project) and WpfCoerceDemo (WPF equivalent demo).  Run the demo and click the button on the main window. Observe the debug output.

On Avalonia, the following output is received on the first coercion request:
```
Coercing value 'NULL' to 'Hello Actipro'
Coercing value 'Hello Actipro' to 'Hello Actipro'
```

Then the following is received on the second coercion request:
```
Coercing value 'Hello Actipro' to 'Hello Actipro'
Coercing value 'Hello Actipro' to 'Hello Actipro'
```

Running the WPF demo application, the following is received every time a coercion request is made:
```
Coercing value 'NULL' to 'Hello Actipro'
```

**Expected behavior**
Expect behavior like WPF. The coercion callback should only be executed once, and the value returned from coercion should not be used for future coercion callbacks.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 11.0.0-preview8

(Update: Confirmed issue in preview7 as well. In preview6, the coercion callback is not invoked at all, so it could be changes between preview6 and preview7 that introduced the current behavior).

**Comment by boydpatterson** [comment]
I tested the sample project with the new build from the PR #11501 and it fixed half the problem.  The coerce method is no longer getting called multiple times (good), but if I trigger a value to be coerced a second time it is coercing the previously coerced value instead of the original value.

First click:
```
Coercing value 'NULL' to 'Hello Actipro'
```

Second click:
```
Coercing value 'Hello Actipro' to 'Hello Actipro'
```

Expected the second click to have the same result as the first click.

**Comment by grokys** [comment]
Thanks for catching that @boydpatterson - we didn't have enough tests for coerced default values. Hopefully will be fixed now.

**Comment by boydpatterson** [comment]
Quick update... still present in `11.0.0-rc1.1`. The previously coerced value is passed as `value` in callback to future coerce calls. Maybe this is intentional, but it is different behavior than WPF and might lead to issues as people convert from WPF to Avalonia since it is not obvious this behavior is different.
