### ISSUE TITLE
Non-uniform Border Thickness is rendered with corner radius

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#11490]
**Describe the bug**
Same code
```xaml
<Border
    Width="100"
    Height="100"
    BorderBrush="Red"
    BorderThickness="20,20,20,1" />
```
In Avalonia 
![image](https://github.com/AvaloniaUI/Avalonia/assets/14807942/c5dd11b8-5514-4629-a82e-f448159b1aa3)

In WPF
![image](https://github.com/AvaloniaUI/Avalonia/assets/14807942/36f36d42-3b87-4618-9729-1113f917990c)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows11
- Version 11p8

**Additional context**

**Comment by timunie** [comment]
I think this is not quite a bug but something that can be defined in the render options. In SVG it's common to specify how corner should be rendered. If would really be great if we can define this in `RenderOptions`. Probably defualt to sharp edges. 

See: 
- https://inkscape-manuals.readthedocs.io/en/latest/strokes.html?highlight=Join%20type#id4
- https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap
- https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin
- https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-miterlimit


@Gillibald I think you are quite experienced in this kind of stuff. What do you think about it?

**Comment by robloo** [comment]
For XAML frameworks with separate BorderThickness and CornerRadius properties WPF is correct. This appears to be a bug in Avalonia.

That said, both border render paths are going to have to change in order to support BackgroundSizing. It might not be worth the time to fix this right now.

**Comment by rabbitism** [comment]
I can confirm this issue is resolved in latest nightly after https://github.com/AvaloniaUI/Avalonia/pull/14048 
![image](https://github.com/AvaloniaUI/Avalonia/assets/14807942/53108154-89a9-4727-8c3d-9fa50edbd58d)
