### ISSUE TITLE
Screenname

### ISSUE THREAD

**Issue by Hummel37** [AvaloniaUI/Avalonia#11512]
Is it possible to add the monitor name to the screen class?
This would be useful for example for a presentation application where the user should be able to select a monitor where the presentation should start.
Currently the screen class has no name or Id or something like that.

**Comment by maxkatz6** [comment]
It would be an excellent addition, but somebody needs to research if this information is available on Linux and macOS API.

**Comment by maxkatz6** [comment]
Completed in 11.2 nightly. Mobile support is coming later.
