### ISSUE TITLE
Remove generated XamlLoader from Simple and Fluent themes

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#11516]
**Is your feature request related to a problem? Please describe.**

For context, it breaks StyleInclude and ResourceInclude to the internal files of the themes. Like `<ResourceInclude Source='avares://Avalonia.Themes.Fluent/FluentControls/Button.xaml' />`.

We have many ideas on default themes improvement that we are not able to do before 11.0 release. Mostly it includes changes to what exactly is generated by the XAML compiler, making controls trimmable, improving theme assembly size, improving startup performance, etc... Some of these changes require changing the internal structure and how dictionaries are organized.

Removing XamlLoader from default themes is a breaking change that might be annoying for some, but should be acceptable in overall. 

In 0.10.x timeline we have not considered the internals of the themes as a public API, even though it was possible to use StyleInclude/ResourceInclude to them. **In WPF/UWP theme internals were never publicly available at all**. 

It's still possible to use only parts of the theme, by creating FluentTheme/SimpleTheme objects and accessing their content with TryFindResource instead of assigning the whole theme to the Application. This won't be changed.

Previously, there was a use case to use only a part of the Fluent theme in order to override some resources. For instance, include all files except AccentColors.xaml, which would be replaced with a custom one. Now it's not needed, as developers can override ColorPaletteResources for the fluent theme providing custom accent color or base colors (todo - add documentation link here).

Note, it doesn't affect their party controls and in-app XAML files by default.

**Comment by danipen** [comment]
So... Is this going to stop working? https://github.com/AvaloniaUI/AvaloniaEdit/blob/41ed3f15d0cdb71698b52653667d939019ad94fc/src/AvaloniaEdit.Demo/App.xaml#L8

**Comment by kekekeks** [comment]
Only built-in themes from the main repo
