### ISSUE TITLE
Custom Skia Page In RenderDemo does not display on master

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#11528]
**Describe the bug**
Neither the custom skia page in renderdemo or my own skia controls work with master, the page is blank and render does not get called.

**To Reproduce**
Run renderdemo and select skcanvas page, it is blank here.

**Expected behavior**
fancy graphics should appear

**Desktop (please complete the following information):**

- OS: windows 10
- Version 11.0.999-cibuild0035380-beta

**Comment by maxkatz6** [comment]
Fixed in https://github.com/AvaloniaUI/Avalonia/pull/11506

**Comment by ahopper** [comment]
yep that fixes it for my code as well, cheers.
