### ISSUE TITLE
Rendering bug with line control in nightly build (0.5.2-build3857-alpha)

### ISSUE THREAD

**Issue by ImoutoChan** [AvaloniaUI/Avalonia#1152]
Adding line control to xaml partly break rendering. At least on the windows.

Video with demonstration:
[2017-09-18_16-33-03.zip](https://github.com/AvaloniaUI/Avalonia/files/1310893/2017-09-18_16-33-03.zip)

Sample project:
[AvaloniaCoreApplicationTest.zip](https://github.com/AvaloniaUI/Avalonia/files/1310908/AvaloniaCoreApplicationTest.zip)

All works fine without Line control in MainWindow.xaml.

**Comment by kekekeks** [comment]
```xml
<Window xmlns="https://github.com/avaloniaui" MinWidth="500" MinHeight="300">
    <StackPanel>
        <Grid Height="10" Background="Red"/>
        <Line Height="5"
          Stroke="Red"
          Stretch="Fill"
          StrokeThickness="10"
          Fill="Red"
          Width="10"/>
        <Grid Height="10" Background="Red"/>
    </StackPanel>
</Window>
```

Seems to be enough to reproduce this.

BTW, with Skia backend it just crashes.

**Comment by kekekeks** [comment]
Actually it's `StartPoint="0,0" EndPoint="0,0"` that causes the issue.
