### ISSUE TITLE
Runtime Requirements

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#11538]
Here it says that Avalonia requires .NET Standard 2.0

https://docs.avaloniaui.net

Here it says that Avalonia requires .NET Core 3.1

https://github.com/AvaloniaUI/Avalonia/wiki/Runtime-Requirements

Which is it?

And what are the requirements of Avalonia 11?

**Comment by maxkatz6** [comment]
1. .NET Standard 2.0 is not an executable target.
2. Technically, Avalonia can run anything that supports .NET Standard 2.0. But we officially provide support to .NET Core 3.1 and newer.

Same as with Win8.1 and Win7. Technically runs on Win7, but we don't test on it, don't spend time on it, and guarantee nothing for it.

**Comment by maxkatz6** [comment]
As for the third-party libraries, I would recommend targeting .NET Standard 2.0 + .NET 6 (as a multitarget)
Unless you need specific features from newer targets and can't do it with .NET Standard 2.0 apis.

**Comment by mysteryx93** [comment]
Documentation in the Wiki should be updated to clarify that.
