### ISSUE TITLE
Can't use Binding when setting RenderTransform Property.

### ISSUE THREAD

**Issue by ImmortalLotus** [AvaloniaUI/Avalonia#11545]
**Describe the bug**
 I have a roulette and so I need to apply the render transform with (360+random amount)deg, and when I finally got to making the roulette spin(I had to implement a control and it's render part and it's my first time with avalonia), I found out that this `<Setter Property="RenderTransform" Value="{Binding Spin}"/>` simply does not work. Is this a bug? or is it an intended feature? It was so intuitive to try it out that it feels like a bug.

**To Reproduce** 

 `<Setter Property="RenderTransform" Value="{Binding Spin}"/>`

with any binding, will throw a weird exception: `Error in binding to 'Roleta.Controls.CirculoControl'.'RenderTransform': 'Null value in expression '{empty}' at ''.'`
and then will not spin(It's what I'm trying to do)
**Expected behavior**

it spins.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win11

**Additional context**
although the code is horribly messy since I'm currently more interested in playing around with the framework instead of coding well, here is the repo for reference: https://github.com/ImmortalLotus/RoletaDaIndecisao

**Comment by danielmayost** [comment]
IIRC, it should be something like this (Not tested): 

```
<Setter Property="RenderTransform">
   <RotateTransform Angle="{Binding Angle}"/>
</Setter>
```
Note that `Angle` should be int or double in ViewModel.

**Comment by ImmortalLotus** [comment]
>` <RotateTransform Angle="{Binding Angle}"/>`

` Error in binding to '{ {M11:1 M12:0} {M21:0 M22:1} {M31:0 M32:0} }'.'Angle': 'Null value in expression '{empty}' at ''.' (RotateTransform #58577354)`

I get this exception on startup, and afterwards simply nothing happens(in relation to the spinning part, the rest works just fine). On my view model's constructor I initialize the value as 360 just to be sure. Could it be that the rotatetransform looks for a binding relative to the control it's being applied to, instead of the default datacontext? Would explain both current and previous behavior.

**Comment by danielmayost** [comment]
> I get this exception on startup

It's a known bug, but it's just a logging issue, not something to worry about.

> and afterwards simply nothing happens

I took a look at your repo, you didn't set the variable as observable.

you need to do somthing like this:

```
    Private int _angle;
    Public int Angle
    {
        get => _angle;
        set => this.RaiseAndSetIfChanged(ref _angle, value);
    }
}
```
see https://docs.avaloniaui.net/docs/data-binding/change-notifications

**Comment by danielmayost** [comment]
also you should replace the Transition to:
```
<DoubleTransition Property="RotateTransform.Angle" Duration="0:0:10"/>
```

**Comment by ImmortalLotus** [comment]
Thank you! it seems that that was part of the issue, however even after that,
Doing this:
`<Setter Property="RenderTransform">
   <RotateTransform Angle="{Binding Angle}"/>
</Setter>`
 
 Instead of:
`<Setter Property="RenderTransform" Value="{Binding Spin}"/>`
 
seems to either not work or hide an exception. If I use render transform the way I was using it before this convo, it would throw an exception every single time I tried to set the class that had the render transform. When I used it in the style you recommended me, it seemed to hide the exception, which got me very curious to test something.

when using {Binding} inside the rendertransform it does not apply to the default datacontext(as in, the data context of the page itself). It applies to the dataContext of the renderTransform itself, which is empty. As such it would get an empty datacontext and not work. 
I figured out a workaround with :

`<Style Selector="Button#Circulo.clicarao">
    <Setter Property="RenderTransform" Value="{Binding #Window.DataContext.Angle}"/>
</Style>`

which then allowed me to do what I expected would happen. I also tried to apply it the way you specified, however it seemed to not work, even after figuring out the correct dataContext+ value:
<Setter Property="RenderTransform">
   <RotateTransform Angle="{Binding Angle}"/>
</Setter>

You can look at it in my repo now that it works! However I'll leave this open as I still think it's a bug.

**Comment by ImmortalLotus** [comment]
> also you should replace the Transition to:
> 
> ```
> <DoubleTransition Property="RotateTransform.Angle" Duration="0:0:10"/>
> ```

I didn't see this part before(hadn't reloaded the page). Could you kindly explain how double transition works?

**Comment by danielmayost** [comment]
You're probably right, I didn't check before I offered you the code, i was just trying to remember what I did because I also had a similar problem, I don't remember what I did in the end.

But I don't think this is a general problem when using {Binding} inside the RenderTransform, it only happens when you try to define a class, try for example replacing the selectors:
```
                <Style Selector="Button#Circulo.clicarao">
			<Setter Property="RenderTransform" Value="rotate(0)"/>
		</Style>
		<Style Selector="Button#Circulo">
			<Setter Property="RenderTransform" Value="{Binding Angle}"/>
		</Style>
```

now the Binding works. interesting.

**Comment by ImmortalLotus** [comment]
which might be a common scenario for people trying to animate stuff on a trigger-like basis. Either way, it's not that common. thx!

**Comment by danielmayost** [comment]
> > also you should replace the Transition to:
> > ```
> > <DoubleTransition Property="RotateTransform.Angle" Duration="0:0:10"/>
> > ```
> 
> I didn't see this part before(hadn't reloaded the page). Could you kindly explain how double transition works?

Never mind, I got confused between animation and transition, it probably won't work in transitions.

**Comment by danielmayost** [comment]
Good news! I checked and this bug no longer exists in V11, you can try.

Change the all Version PackageReference to `11.0.0-preview8`, and don't forget to replace `<FluentTheme Mode="Dark"/>` with `<FluentTheme/>`.

**Comment by ImmortalLotus** [comment]
> 
good to know!
but why do I have to change that? is the default fluent theme being set to dark?

**Comment by danielmayost** [comment]
https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#avaloniathemesfluent-and-avaloniathemessimple-themes

**Comment by ImmortalLotus** [comment]
will try to upgrade to .11 sometime soon(maybe tmrw), then I'll likely close this thread.
