### ISSUE TITLE
Draw CircleSector/ Ellipse Sector

### ISSUE THREAD

**Issue by ImmortalLotus** [AvaloniaUI/Avalonia#11550]
**Is your feature request related to a problem? Please describe.**

When creating controls it might be common that people need to draw pieces of a circle/ellipse based on angle/radians, instead of a whole circle. It's currently not possible to do so with the geometry classes(at least what I found), as it requires one curved line to be drawn.

I might be wrong though, as I found the geometry classes mildly confusing to navigate and there seems to be no documentation about them.

**Describe the solution you'd like**
A .DrawCirclePart/ CircleSector on the drawingContext that receives the center point, the Radius length and an angle of a circle for it to draw a part of.

**Describe alternatives you've considered**
Adapt geometry classes for rounded lines to be possible(might be worse)

**Additional context**
wikipedia article that helps visualize what I'm talking about: https://en.wikipedia.org/wiki/Circular_sector

**Comment by timunie** [comment]
It's ArcSegment iirc

**Comment by robloo** [comment]
It's possible now with Avalonia v11 as a shape.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Shapes/Sector.cs

If you want to draw the geometry yourself just have a look at how Sector does it internally.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Shapes/Arc.cs is related
