### ISSUE TITLE
Unable to resolve suitable regular or attached property 'X' on type 'Y'

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#11568]
**Describe the bug**
XamlX throw  `Unable to resolve suitable regular or attached property` exception when defining `ControlTemplate` in resource the attached example.

**To Reproduce**

1. Extract the attached example.
2. Compile
3. See error

**Expected behavior**
The exception is not thrown

**Screenshots**

**Desktop (please complete the following information):**

- OS: *all*
- Version:  **Avalonia 11.0.0-preview8**

**Additional context**

From the tests I did on the attached example, I saw that xamlx ignores the TargetType of the `ControlTemplate` and tries to find the `ItemsPanel` property on the `windows` type.

[ACompileIssue.zip](https://github.com/AvaloniaUI/Avalonia/files/11598787/ACompileIssue.zip)

**Comment by rabbitism** [comment]
same as https://github.com/AvaloniaUI/Avalonia/issues/11334,

btw my comment there seems incorrect...
