### ISSUE TITLE
Support for Font features

### ISSUE THREAD

**Issue by soosr** [AvaloniaUI/Avalonia#11570]
The font [Inter](https://github.com/AvaloniaUI/Avalonia/tree/b879144acee97363bd5d98f21561197d9b28ccc3/src/Avalonia.Fonts.Inter) based on the creator of it, has many features. 
Some of them would be pretty useful even in production like `tnum` and `zero`.
On the right you can see the features: https://rsms.me/inter/lab/?antialias=default&sample=Numbers

Would be nice if those features could be enabled/disabled on a Avalonia application.

**Comment by soosr** [comment]
@Gillibald Is this fixed by https://github.com/AvaloniaUI/Avalonia/pull/14157?

**Comment by timunie** [comment]
@soosr you can test it if you try nightly builds

**Comment by Gillibald** [comment]
It should be y
