### ISSUE TITLE
Avalonia Browser dosen't responsed to changes

### ISSUE THREAD

**Issue by BiDuang** [AvaloniaUI/Avalonia#11576]
**Describe the bug**
Avalonia Browser doesn't responsed to any change, but Desktop does.

**To Reproduce**

1. Create a `Avalonia Cross Platform Application` project which the NuGet package's version is 11.0.0-preview8
2. Change any element ( For example: change the `Greeting`'s content into `"Foo bar"`  
3. Build and run the Browser project
4. The content displayed on the page is still `"Welcome to Avalonia!"`
 
**Expected behavior**
Respond to my changes.

**Screenshots**
![Screenshot](https://github.com/AvaloniaUI/Avalonia/assets/40264028/15b121ef-11ec-498b-8c4a-3fe24dd89613)

**Desktop (please complete the following information):**

- OS: Windows 11
- IDE: Rider latest stable version
- Avalonia 11.0.0-preview8
- Tested on Firefox and Edge

**Comment by rabbitism** [comment]
Maybe browser cache is not cleared.

**Comment by BiDuang** [comment]
> Maybe browser cache is not cleared.

I found the cause of the problem: Avalonia Browser's process cannot be closed cleanly by the debugger. So the `${browser_project_dir}\bin\Debug\net7.0\${project_name}.dll` is in use and cannot be deleted. So, it resulted in no changes after your first preview of the project.

It appears that Rider, Visual Studio, or the .NET CLI are all causing a process named ".NET Host" to escape debugger control. Kill the process manually, the changes of the project can be view correctly.

**Comment by BiDuang** [comment]
Worse, sometimes the process cannot be killed manually. It keeps trying to restart.

**Comment by BiDuang** [comment]
Update: To solve the above issue, simply avoid using Rider as the editor for the Browser project. Having Rider open will cause a .NET Host process to continuously occupy the project files. Is it because of a problem with the Avalonia for Rider plugin?

**Comment by maxkatz6** [comment]
> Browser's process cannot be closed cleanly by the debugger. So the ${browser_project_dir}\bin\Debug\net7.0\${project_name}.dll is in use and cannot be deleted

Please report it to Rider YouTrack or .NET runtime. It's not related either to Avalonia or Avalonia for Rider plugin.

> Maybe browser cache is not cleared.

Cache might need to be manually cleared. Improvements on this side also not really related to Avalonia, and tracked here https://github.com/dotnet/runtime/issues/70762. .NET 8 will come with most of them.
