### ISSUE TITLE
Binding string array property to ListBox.Items does not work anymore in 11.0.0-preview8 but does still work in 11.0.0-preview4

### ISSUE THREAD

**Issue by TheCrossPlatformGuy37** [AvaloniaUI/Avalonia#11578]
**Describe the bug**
Binding string array property to ListBox.Items does not work anymore in 11.0.0-preview8 but does still work in 11.0.0-preview4.

**To Reproduce**
Create a new Avalonia MVVM Application from template in Visual Studio.

To install 11.0.0-preview4 run this from cmd:
`dotnet new uninstall Avalonia.Templates`
And then run the vsix from Avalonia website.

To install 11.0.0-preview8 just run this from cmd:
`dotnet new install Avalonia.Templates`

In the new created Application:

MainWindowViewModel.cs:
Replace line
`public string Greeting => "Welcome to Avalonia!";`
with
`public string[] Greeting { get; set; } = new string[] { "Welcome to", "Avalonia!" };`

MainWindow.axaml:
Replace line
`<TextBlock Text="{Binding Greeting}" HorizontalAlignment="Center" VerticalAlignment="Center"/>`
with
`<ListBox Items="{Binding Greeting}"/>`

Compile.

**Expected behavior**
If App was created from 11.0.0-preview4 template everything compiles and works fine. But if App was created from 11.0.0-preview8 template you get the following compiler error message:
`Error AVLN:0004 Unable to find suitable setter or adder for property Items of type Avalonia.Controls:Avalonia.Controls.ItemsControl for argument Avalonia.Markup:Avalonia.Data.Binding, available setter parameter lists are:
System.Object`

**Desktop**
- OS: Windows 10

**Comment by maxkatz6** [comment]
See https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#itemscontrol-changes-including-all-itemscontrol-inherited-controls-like-listbox-or-menus

**Comment by rabbitism** [comment]
use ItemsSource
