### ISSUE TITLE
Failure to compile following tutorial Binding Classes

### ISSUE THREAD

**Issue by KyleC69** [AvaloniaUI/Avalonia#11580]
**Describe the bug**
A compiler error is received trying to compile a templated control based on tutorials

**To Reproduce**

1 Create a new templated control with an attached property of type bool
2 use style classes in the selector to control color of object base on bool property. (on/off state)
3. create the binding to the class using the negate operator. (as in tutorial "Binding Classes") {Binding !Property}

**Expected behavior**
A successful compilation. The properties and other bindings produce no design-time errors

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/68043041/8d0dd7e7-513f-4ef7-b084-922f89c66e94)

**Desktop (please complete the following information):**

- OS Ubuntu  22.04.2 JetBrains Rider 2023.2
- Avalonia Nightly Build Version -- <PackageReference Include="Avalonia" Version="11.0.999-cibuild0035433-beta" />

The error is Internal compiler error Unexpected '!'

The **Additional context**

**Comment by KyleC69** [comment]
Version used is    Include="Avalonia" Version="11.0.999-cibuild0035433-beta"

**Comment by maxkatz6** [comment]
TemplateBinding does not support "!" operator. Was it mentioned anywhere in the samples?
TemplateBinding is a simplified binding that redirects template parent properties as they are.
Though, you can use a Converter property.

There was a proposal for template binding bang operator https://github.com/AvaloniaUI/Avalonia/issues/8519
