### ISSUE TITLE
Register for custom animator missing

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaUI/Avalonia#11594]
**Describe the bug**
Before i can register my own custom animators with `Animation.RegisterAnimator`, not it is internal. Seems like API for registering animation missing now. 

I'm creating this so it doesn't get lost, @kekekeks 

**Desktop (please complete the following information):**

- Version: 11.0.0-rc1.1

**Comment by edgarfgp** [comment]
It seems that `RegisterAnimation` is now internal. I’m facing the same issue my custom animators are now crashing because the registration is missing.
