### ISSUE TITLE
Exception within MediaContext.CommitCompositorsWithThrottling() when running the Samples

### ISSUE THREAD

**Issue by npolyak** [AvaloniaUI/Avalonia#11598]
I am running the 11.0.0-rc1.1 Desktop samples on Windows. 

I am getting some errors:
System.InvalidOperationException: 'Collection was modified; enumeration may not operate' line 81 MedialContext.Compositor.cs file.

It happens in many different places, including when I am rotating the adorner in AdornerLayer sample

**Comment by maxkatz6** [comment]
Seems to be only reproducible with .NET Framework.

**Comment by kekekeks** [comment]
Apparently modifying a HashSet during enumeration is safe in .NET Core which is why I've missed it.
