### ISSUE TITLE
AvaloniaLocator.Current is no longer accessible

### ISSUE THREAD

**Issue by TobiasSchulte** [AvaloniaUI/Avalonia#11619]
**Describe the bug**
AvaloniaLocator was recently marked with the PrivateApi attribute and thus its no longer accessible from outside of the Avalonia projects.

**To Reproduce**

1. Try to access e.g. `AvaloniaLocator.Current.GetRequiredService<IAssetLoader>()` for e.g. loading assets dynamically
2. Observe that it's no longer possible in 11.0.0 rc1.1  (was still working in 11.0.0 preview 8)

**Expected behavior**
Either make it available again or offer a different way to access services created within Avalonia that are needed in user code.

**Desktop (please complete the following information):**

- OS: Windows 11, Linux (Raspberry Pi OS & custom image built with yocto)

**Comment by maxkatz6** [comment]
> offer a different way to access services created within Avalonia that are needed in user code.

Done 
https://github.com/AvaloniaUI/Avalonia/wiki/Avalonia-11-Porting-Guide#locator

**Comment by martinstenhoff** [comment]
@maxkatz6 
The Porting Guide with the anchor link you mention ([Avalonia-11-Porting-Guide#locator](https://github.com/AvaloniaUI/Avalonia/wiki/Avalonia-11-Porting-Guide/7ffa833a4454edc2bb87ca8e9a38db9bdcb6b080#locator)) takes you to the following section:

> # Locator
> The AvaloniaLocator is no longer available. Most services that were available via the locator now have alternative methods of access:
> 
> 1. AssetLocator is a static class now with all of the old methods.

I take it `AssetLocator` is supposed to be `AssetLoader`.

**Comment by ImparTechnologyCeo** [comment]
Resolve logo essa palhaçada ai
![Capturar](https://github.com/AvaloniaUI/Avalonia/assets/136930232/e67c72d8-d414-475d-b53f-79418fec75bd)

**Comment by timunie** [comment]
@ImparTechnologyCeo please ask your questions in telegram or discussions. Please also ask on english and with a description what is wrong.

**Comment by timkicker** [comment]
Just letting you know, that the docs [have not been updated yet](https://docs.avaloniaui.net/docs/getting-started/assets).

**Comment by timunie** [comment]
@timkicker then open an issue in docs repo. Or, even better, provide a PR to fix the docs. Thx. 
https://github.com/AvaloniaUI/avalonia-docs

**Comment by timunie** [comment]
@timkicker you need to swtich to 11.0 docs, see: 
![image](https://github.com/AvaloniaUI/Avalonia/assets/47110241/3ac5702c-437e-4010-9ce6-13778da2668a)

**Comment by nickdaria** [comment]
Is there still no way to register a custom implementation of IAssetLoader? Used to be able to do so and now it appears to not be an option.
