### ISSUE TITLE
Raise a building error in my avalonia.browser project (Avalonia 11.0.0-rc1.1)

### ISSUE THREAD

**Issue by hkf7703** [AvaloniaUI/Avalonia#11623]
**Describe the bug**
严重性	代码	说明	项目	文件	行	类别	源	禁止显示状态	工具
错误		Parameter types of pinvoke callback method 'System.Int32 SetMinMaxSize(System.Void*, Avalonia.Native.Interop.AvnSize, Avalonia.Native.Interop.AvnSize)' needs to be blittable.	ActionCell.Demo.Browser	C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.5\Sdk\WasmApp.Native.targets	290		生成		ManagedToNativeGenerator

**Comment by maxkatz6** [comment]
Remove Avalonia.Desktop project. It's not compatible with browser.
