### ISSUE TITLE
`DispatcherTimer` behavior changes since `11.0.0-preview7`

### ISSUE THREAD

**Issue by Gigas002** [AvaloniaUI/Avalonia#11621]
**Describe the bug**

`DispatcherTimer` starts at moment being initialized

**To Reproduce**

1. `dotnet new avalonia.mvvm`
2. change version to `11.0.0-preview7` or higher
3. add timer to `ViewModel` and `View` and run the app

(or clone [my repo](https://github.com/senketsu03/AvaloniaTimerIssue) with example)

**Expected behavior**

Timer not starts until `Timer.Start();` is called

**Desktop (please complete the following information):**

- OS: Windows, Linux
- Version: `11.0.0-preview7` and higher, lower ones not affected

**Additional context**

[Example](https://github.com/AvaloniaUI/Avalonia/discussions/11593#discussioncomment-6066512) of what's expected in details

**Comment by kekekeks** [comment]
This change was made to improve compatibility with WPF which [does the same](https://github.com/dotnet/wpf/blob/0aca160dd04da87d775611b16d0cab7d9059be8e/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/DispatcherTimer.cs#L77-L98).

Probably need to add that to the breaking changes list.

**Comment by Gillibald** [comment]
You can use this ctor https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Threading/DispatcherTimer.cs#L42 to be able to manually start the timer
