### ISSUE TITLE
Application using the LinuxFramebufferPlatform constantly keeps a whole processor core on 100% load

### ISSUE THREAD

**Issue by TobiasSchulte** [AvaloniaUI/Avalonia#11628]
**Describe the bug**
On several different systems we can observe that a very basic sample application utilizes a whole procesor core with 100% load, even if it idles and no animations etc. are displayed. This happens with an application started using StartLinuxFbDev and StartLinuxDrm. The systems are configured to use a windowmanager as well without any problems.

**To Reproduce**
This the most easily to reproduce setup we found:

Hardware: Raspberry Pi 4 Model B with 4gb RAM
OS: Raspberry Pi OS Lite Kernel version 6.1.21 released on May, 3rd 2023
Avalonia Version: 11.0.0 RC 1.1

1. Setup OS 
2. Start system and login on the shell
3. Checkout the sample project: https://github.com/TobiasSchulte/Avalonia_Sample_Repro_HighCPU
4. install dotnet sdk and build the project using `dotnet build -c Release`
5. run the executable using `dotnet run`
6. Observe one CPU core being fully utilized all the time

Starting the same application in a desktop environment (Pixel in case of Raspberry Pi OS) doesn't lead to the same problem.

We can observe the same problem in several other Hardware/OS combinations:
- Fedora 38 with Kernel 6.3.4-201.fc38.x86_64 on AMD Ryzen 4750U
- custom designed hardware using an I.MX6 Duallite and a linux image built with yocto (Kernel 5.15.63)

**Comment by TobiasSchulte** [comment]
As I'm not able to access the systems at work over the weekend I setup a vm running fedora and in this configuration your suggestion doesn't seem to solve this problem. 11.0.0 rc 1.1 and 11.0.999-cibuild0036036-beta behave exactly the same in the vm, both consuming one of two cpus completely.

I'll test it again on monday at work on the systems mentioned above.

**Comment by kekekeks** [comment]
Sorry, wrong PR link, should be: #11596

**Comment by TobiasSchulte** [comment]
No worries, in the vm it's fixed with that commit.

Thanks for your quick responses and your work in general!

**Comment by TobiasSchulte** [comment]
It's resolved on the other systems as well 👍
