### ISSUE TITLE
AccessKeyHandler now internal and eats alt presses

### ISSUE THREAD

**Issue by Mikolaytis** [AvaloniaUI/Avalonia#11633]
It's not obvious that the reason of alt presses not coming to event handlers is AccessKeyHandler.
It's subscribing to global key events and setting e.Handled = true on alt up.
We've spent a day investigating this issue a 1+ year ago. Our fix was to Set MainMenu to null on app start to disable this.
Now because it's internal in 11.0 - we've decided to not use AccessText at all. And still I think it will eat alt presses to open menu. will test this later.
I think there can be or should be a possibility to write code that not making e.Handled=true, or add an ability to disable this handler.

**Comment by grokys** [comment]
Definitely sounds like a bug. I wasn't aware of this; the hack shouldn't be needed I don't think.
