### ISSUE TITLE
Clipboard format names not as expected on macOS

### ISSUE THREAD

**Issue by xecrets** [AvaloniaUI/Avalonia#11632]
Clipboard format name is not as expected. On Windows, it's "Text" as defined in `DataFormats.Text`, but on the Mac I'm getting "public.utf8-plain-text" and "NSStringPboardType". I shouldn't need to have platform-specific code for this, right? Similar for files copied in Finder. On Windows, getting the expected `DataFormats.Files` ("Files"), but on the Mac it's "public.file-url" (and a zillion other formats as well...).

```
IClipboard clipboard = (Application.Current!.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime)!.MainWindow!.Clipboard!;
string[] formats = await clipboard.GetFormatsAsync();
```
I expect the native clipboard formats where appropriate to be mapped to the platform independent names as defined in the `DataFormats` static class.

- OS: macOS 12.6.6 Monterey
- Version 11.0.0-rc1.1

It works as expected on Windows. Have not had the time to check Linux yet.

**Comment by kekekeks** [comment]
Probably need a virtual (non-platform-specific) format list too.

@maxkatz6

**Comment by xecrets** [comment]
Similar issue on Ubuntu Linux as well. Text seems to work as expected here, but copying files does not work. Using `DataFormats.Files` does not work, the clipboard is populated, with among other formats `x-special/gnome-copied-files` and `text/uri-list` but not the expected `DataFormats.Files` .

**Comment by maxkatz6** [comment]
@kekekeks our DataFormats already works as a virtual list on some platforms. 
Like, on Browser, when you request Text or Files, browser backend will match it to the platform format and return an expected value.
Seems like it wasn't properly implemented for Linux and macOS from the beginning.

**Comment by xecrets** [comment]
Awesome! But... Should I open a new issue for the Linux side of things?

**Comment by timunie** [comment]
if there is no open issue for Linux, yes in my opinion
