### ISSUE TITLE
Ctrl Shift in devtools doesn't work

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaUI/Avalonia#11635]
**Describe the bug**
Pressing Ctrl+Shift while devtools opened should bring us to the hovered element, but it's doesn't work for now.

**To Reproduce**

1. Go to RenderDemo
2. Open devtools
3. Press ctrl shift, while hovering above any element

- Version: 11.0.0-rc1.1

**Comment by jp2masa** [comment]
Duplicate of #10449?
