### ISSUE TITLE
About bugs derived from IInputManager

### ISSUE THREAD

**Issue by Coolkeke** [AvaloniaUI/Avalonia#11644]
At present, there is a problem with the removal of InputManager.Instance in the RC1 project, which has caused trouble for our company's project. In actual application scenarios, a virtual keyboard is embedded on the page to achieve the function of controlling the current control focus and changing content. Instead of developing an input method embedded in the operating system, this would be an immeasurable task. Due to the current changes, the project application that extends the relevant interface has been blocked, which will cause confusion or even devastating damage to the project functionality of this application. Currently, our company has extended the project functionality for its InputManager.Instance, I believe we are not the only company that has done this. If it is due to project planning considerations, we respect and support it. However, may I ask if there are any reference scenarios similar to our company's actual development of InputManager.Instance that can solve a series of problems? If there are any relevant examples, please provide them. Thank you
For this reason, there is a related demo project named LayUI Avalonia in my open source project. The original purpose of creating it was to build a good learning environment for its Avalonia ecosystem. The current Avalonia version of the project is 0.10.18
The project address is: [https://github.com/Coolkeke/LayUI-Avalonia](url)
Page name: KeyboardPage
I hope my project and questions can be helpful for the planning and design of the Avalonia project. Once again, I sincerely thank the Avalonia project for creating value for our developers. I hope the Avalonia team can develop better and better!!

**Comment by kekekeks** [comment]
For OSK you can track the focused element via `InputElement.GotFocusEvent.Raised.Subscribe(...)` and  `InputElement.LostFocusEvent`. Input events should be raised via 
```cs
focusedElement.RaiseEvent(new KeyEventArgs
{
    RoutedEvent = InputElement.KeyDownEvent,
    Key = ...,
    KeyModifiers = ..,
    Source = element,
};
```

**Comment by Coolkeke** [comment]
May I ask what I need to do to obtain the interface related to ILogSink? Please provide guidance. Thank you

**Comment by timunie** [comment]
@Coolkeke see: 
- https://docs.avaloniaui.net/docs/getting-started/logging-errors-and-warnings
- https://docs.avaloniaui.net/docs/getting-started/unhandledexceptions

You can get the trace output into your own sink, like this (for NLog):
https://nlog-project.org/2010/09/02/routing-system-diagnostics-trace-and-system-diagnostics-tracesource-logs-through-nlog.html

**Comment by qfmee** [comment]
I also encountered the same problem, unable to create a virtual keyboard! What solution did you use to solve it now?
