### ISSUE TITLE
MenuItem do not update on ReactiveUI update.

### ISSUE THREAD

**Issue by terinfire** [AvaloniaUI/Avalonia#11656]
[AvaloniaMenuProblem.zip](https://github.com/AvaloniaUI/Avalonia/files/11652692/AvaloniaMenuProblem.zip)

See attached project/solution.  This was previously working in Avalonia 0.10.x.x.  Situation involves a MenuItem having a Style set that binds to an INotifyPropertyChanged (MenuCommandModel in this example).

When a MenuItem is bound to a Menu on a Window, top-level items will update based on reactive command changes.  Children will not.

Open Project/Close Project on the top level menu will update and show accordingly.

Using the File \ Open Project or File \ Close Project will not update accordingly.

**Comment by timunie** [comment]
Related? #11112

**Comment by terinfire** [comment]
100% related.

**Comment by timunie** [comment]
Okay, so closing this as duplicate. The sample is useful anyway 👍
