### ISSUE TITLE
ClipToBounds=False has no effect on TextBox

### ISSUE THREAD

**Issue by Mochengvia** [AvaloniaUI/Avalonia#11652]
I put a border with BoxShadow in `ControlTemplate` and add a setter `<Setter ClipToBounds=False />` in Style. 
It seems that on Button and TextBox, they behave completely differently. is there any solution?
![图片](https://github.com/AvaloniaUI/Avalonia/assets/23360265/6ed151f4-e6e8-4806-bcd9-178c4e29aec4)

```
<Setter Property="ClipToBounds" Value="False"/>
<Setter Property="Template">
  <ControlTemplate>
    <Grid>
      <Border ... BoxShadow="5 5 10 2 Red">
...
```

**Comment by rabbitism** [comment]
TextBox default template was wrapped in a DataValidationError, you need to check if that impacts border shadow first.
