### ISSUE TITLE
Build time very slow in RC

### ISSUE THREAD

**Issue by MonsieurTib** [AvaloniaUI/Avalonia#11653]
**Describe the bug**
Since I upgrade my project from 11.0.0.0-preview5 to 11.0.0-rc1.1, build time ( in Rider ). takes 5x more time (from 7s to 38s).
I tried with a blank project, and build time is also very long.
- OS:  Mac

**Comment by workgroupengineering** [comment]
Have you tried [disabling telemetry](https://github.com/AvaloniaUI/Avalonia/pull/11116)?

**Comment by MonsieurTib** [comment]
@workgroupengineering yes that solved the problem.
Thank you

**Comment by danwalmsley** [comment]
Please provide more information, as we are unable to repro here: are you building from cli, rider, vs?

**Comment by MonsieurTib** [comment]
Very strange... I enabled telemetry once again, and I am no longer experiencing the issue.

**Comment by danwalmsley** [comment]
iv made a fix, that means there is definitely no chance this can delay the builds.
