### ISSUE TITLE
Animation trouble after moving to RC1

### ISSUE THREAD

**Issue by rodrigovaras** [AvaloniaUI/Avalonia#11663]
I have been puzzle trying to figure out what happen to a third party Avalonia library that we have been using on our project.
The reference project is here: https://github.com/Projektanker/Icons.Avalonia
The maintainers are not doing anything about the new v11 and recently after the RC1 release now everything is totally broken.

So, i decided to give it a try and attempting to fix the project myself.
I was able to fix most of the issues and refactor the strategy being used.
When i run their demo app i notice the animation is broken. After debugging using the Avalonia source code i decided to add an invisible progress bar to compare the animation code path and voila the custom control animation start working.
In summary:
Adding an invisible progress bar make things works, removing is causing no animation to happen on the page.

This minimal xaml repro the problem:
```xaml
<Grid RowDefinitions="Auto,Auto,Auto,Auto,Auto" >
 <ProgressBar IsIndeterminate="true" IsVisible="False" />
 <i:Icon Value="mdi-cog" Animation="Spin" Grid.Row="1" />
</Grid>
```
Remove the progress bar and the animation stops working on the <i:Icon> control.

Here the styles using on my Fluent.xaml from the custom library:
```xaml
	<Style Selector="local|Icon[Animation=Spin]">
		<Style.Animations>
			<Animation Duration="0:0:2" IterationCount="Infinite">
				<KeyFrame Cue="0%">
					<Setter Property="RotateTransform.Angle" Value="0" />
				</KeyFrame>
				<KeyFrame Cue="100%">
					<Setter Property="RotateTransform.Angle" Value="360" />
				</KeyFrame>
			</Animation>
		</Style.Animations>
	</Style>
	<Style Selector="local|Icon[Animation=Pulse]">
		<Style.Animations>
			<Animation Duration="0:0:2"
					   IterationCount="Infinite">
				<Animation.Easing>
					<local:PulseEasing />
				</Animation.Easing>
				<KeyFrame Cue="0%">
					<Setter Property="RotateTransform.Angle" Value="0" />
				</KeyFrame>
				<KeyFrame Cue="100%">
					<Setter Property="RotateTransform.Angle" Value="360" />
				</KeyFrame>
			</Animation>
		</Style.Animations>
	</Style>
```
Rodrigo.

**Comment by hez2010** [comment]
May be related to animation registration. Can you try the latest nightly ci build?

**Comment by timunie** [comment]
As I have it in clipboard anyway, here is how to consume nightly builds: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

**Comment by rodrigovaras** [comment]
Confirmed the problem is gone after I run against the latest nightly build. Thanks
