### ISSUE TITLE
Avalonia.Headless.NUnit.AvaloniaTestAttribute is missing constructors from base class

### ISSUE THREAD

**Issue by stogle** [AvaloniaUI/Avalonia#11677]
**Describe the bug**
I want to use `AvaloniaTestAttribute` from `Avalonia.Headless.NUnit` to identify test cases for my NUnit tests, but it is missing the constructors from its base class ([NUnit.Framework.TestCaseAttribute](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TestCaseAttribute.cs)) so I can't pass any arguments to it.

**To Reproduce**
Attempt to write a test with `AvaloniaTestAttribute`, e.g.
```
[TestFixture]
public class Tests
{
    [AvaloniaTest(1, 2, 3)]
    public void Test(int arg1, int arg2, int expected)
    {
        int result = arg1 + arg2;
        Assert.AreEqual(expected, result);
    }
}
```
This causes `error CS1729: 'AvaloniaTestAttribute' does not contain a constructor that takes 3 arguments`.

**Expected behavior**
This code should compile and run successfully. `AvaloniaTestAttribute` should include the following constructors.
```
        public AvaloniaTestAttribute(params object?[]? arguments) : base(arguments) { }
        public AvaloniaTestAttribute(object? arg) : base(arg) { }
        public AvaloniaTestAttribute(object? arg1, object? arg2) : base(arg1, arg2) { }
```

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0.0-rc1.1

**Comment by stogle** [comment]
Alternatively, maybe what was intended is that `AvaloniaTestAttribute` extends `TestAttribute` (note `TestCaseAttribute`)? So it would be used in conjunction with `TestCaseAttribute` like this:
```
    [AvaloniaTest]
    [TestCase(1, 2, 3)]
    public void Test(int arg1, int arg2, int expected)
```

**Comment by maxkatz6** [comment]
> maybe what was intended is that AvaloniaTestAttribute extends TestAttribute

Yes, it was this mistake. Interesting that it still works without any parameters.
For test cases there is a separated AvaloniaTheoryAttribute attribute.

**Comment by stogle** [comment]
> Yes, it was this mistake. Interesting that it still works without any parameters. For test cases there is a separated AvaloniaTheoryAttribute attribute.

So is it just a matter of changing
https://github.com/AvaloniaUI/Avalonia/blob/dc9b47b9bef586b404e04372bbd4bb47cd14f3fb/src/Headless/Avalonia.Headless.NUnit/AvaloniaTest.cs#L16
to
```C#
public sealed class AvaloniaTestAttribute : TestAttribute, IWrapSetUpTearDown
```
?

**Comment by maxkatz6** [comment]
Yes
