### ISSUE TITLE
Position of control gets calculated wrong with MinHeight

### ISSUE THREAD

**Issue by KeKl** [AvaloniaUI/Avalonia#1167]
The position of a control gets calculated wrong if MinHeight is involved:

    <StackPanel Orientation="Horizontal">
        <TextBox Name="tb" MinHeight="100" />
    </StackPanel>

The TextBox flew out of the upper windows border. 
In WPF it resizes the control althought MinHeight is set.

**Comment by grokys** [comment]
Just tried this and seems to work now so closing.
