### ISSUE TITLE
Drag/Dropping Window to Maximized Cuts Taskbar (BorderOnly Deco)

### ISSUE THREAD

**Issue by ArchLeaders** [AvaloniaUI/Avalonia#11685]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/11222

<div type='discussions-op-text'>

<sup>Originally posted by **ArchLeaders** May  3, 2023</sup>
I'm setting up a custom window chrome for my application, but I'm getting some weird behavior with the drag/drop to fullscreen action in Windows 10.

Setting `WindowState` to `WindowState.Maximized` works just fine, but when I drag the window to the top of the screen and drop it cuts out the task bar and about 7 pixels off the side of the window.

https://user-images.githubusercontent.com/80713508/236018412-8c7b7983-62ab-4fbd-b272-6aa63c661e9d.mp4

Is there a way to intercept this behavior and call whatever Avalonia does to fullscreen to the correct bounds instead? Or just another way to fix this?

- **Avalonia Version:** 11.0.0-preview6 and 11.0.0-r1.1
- **OS:** Windows 10</div>

**Comment by ArchLeaders** [comment]
I should also mention that the other window decoration properties did not work in my case, the main issue being the window drop shadow. This is the only solution I could find that would remove the system chrome but retain the shadow (border) was using `BorderOnly` with a custom resize border and drag region.

**Comment by ArchLeaders** [comment]
> Window has a property called `OffScreenMargin`. Can you try to apply this to your inner Content?
> 
> ```
> <Window xmlns="https://github.com/avaloniaui"
>         ... other namespaces etc ... >
>    <Grid Margin="{Binding $parent[Window].OffScreenMargin}">
>      ... Content ...
>    </Grid>
> </Window>
> ```

No luck with that sadly, still cuts the border when drop/dropping to fullscreen (same effect as before)

![image](https://github.com/AvaloniaUI/Avalonia/assets/80713508/9a22d843-5177-4829-8caa-653eaec296b7)

**Comment by cyraid** [comment]
Apparently my bug report got deleted? It was when it's maximized and no chrome it gets cut by 8 pixels or so in a maximized state.

**Comment by rprimora-pricer** [comment]
I experience the same issue. I think you are right for the pixels. It should be 8px which is the padding applied to the Window when it's maximized. 

It's as if this way of maximizing resizes the Window without padding and then internally changes state to maximized.

**Comment by ApaulMyLittleAirport** [comment]
Margin="{Binding $parent[Window].OffScreenMargin} ，This one really works, thank you!!

**Comment by rprimora-pricer** [comment]
I have looked closer at the issue today and managed to get a working code.

In your constructor add the following code block:

``` csharp
this.GetPropertyChangedObservable(WindowStateProperty).AddClassHandler<Visual>((t, args) =>
{
    /// I am doing this only for Windows.
    if (OperatingSystem.IsWindows())
    {
        /// If the state is maximised we will enter our code block.
        if (args.GetNewValue<WindowState>() == WindowState.Maximized)
        {
            /// Get the screen from the window.
            var screen = Screens.ScreenFromWindow(this);
            /// This is the part where we check if the actual height is more than the working area cos that would
            /// mean the window has gone over the taskbar.
            if (screen.WorkingArea.Height < ClientSize.Height)
            {
                /// We set the client size of our window to be exactly the size of our working area.
                ClientSize = screen.WorkingArea.Size.ToSize(screen.Scaling);
                /// This is the last piece of the puzzle. If we maximize the Window by setting the state
                /// then this position will be correct. But, if the state is set as a result of dragging the window
                /// to the top then the position will most likely be less then 0 ( it will be (-7,-7) in our case).
                if (Position.X < 0 && Position.Y < 0)
                    Position = new(0, 0);
            }
        }
    }
});
```

I really hope Avalonia solves this issue.

**Comment by ArchLeaders** [comment]
> I have looked closer at the issue today and managed to get a working code.
> 
> In your constructor add the following code block:
> 
> ```cs
> this.GetPropertyChangedObservable(WindowStateProperty).AddClassHandler<Visual>((t, args) =>
> {
>     /// I am doing this only for Windows.
>     if (OperatingSystem.IsWindows())
>     {
>         /// If the state is maximised we will enter our code block.
>         if (args.GetNewValue<WindowState>() == WindowState.Maximized)
>         {
>             /// Get the screen from the window.
>             var screen = Screens.ScreenFromWindow(this);
>             /// This is the part where we check if the actual height is more than the working area cos that would
>             /// mean the window has gone over the taskbar.
>             if (screen.WorkingArea.Height < ClientSize.Height)
>             {
>                 /// We set the client size of our window to be exactly the size of our working area.
>                 ClientSize = screen.WorkingArea.Size.ToSize(screen.Scaling);
>                 /// This is the last piece of the puzzle. If we maximize the Window by setting the state
>                 /// then this position will be correct. But, if the state is set as a result of dragging the window
>                 /// to the top then the position will most likely be less then 0 ( it will be (-7,-7) in our case).
>                 if (Position.X < 0 || Position.Y < 0)
>                     Position = screen.WorkingArea.Position; // <-- This is needed because you might have your taskbar in a different position (Left | Right | Top | Bottom).
>             }
>         }
>     }
> });
> ```
> 
> I really hope Avalonia solves this issue.

Hey, thanks for this! I just tested it and it almost works perfectly.

One thing I noticed; when you check the height it should be multiplied by the screen scale. It didn't work on a 4K monitor because the check failed.

```cs
if (screen.WorkingArea.Height < ClientSize.Height * screen.Scaling) {
  // . . .
}
```

Visual it looks fine, but it seems to restrict actually using the taskbar. I'll mess around with it and see if I can fix that issue.

Thanks again for the research on this!

**Comment by ArchLeaders** [comment]
> Visual it looks fine, but it seems to restrict actually using the taskbar. I'll mess around with it and see if I can fix that issue.

The taskbar seems to work fine if the window position is anything but `0, 0`. A.k.a if the taskbar is not docked to the bottom, or the position is hardcoded to `0, 1` or something.

I don't know enough about how windows work to say why this happens, but maybe it will be insightful to someone else.

**Comment by rprimora-pricer** [comment]
@ArchLeaders good catch on scaling. I'll check it out.

I am not sure about the usage of taskbar. What do you mean by this?

**Comment by timunie** [comment]
@ArchLeaders how does latest nightly look for you? 

Also probably check what FluentAvalonia does to get AppWindow working on Windows. They did a heavy lifting to get it somewhat work.

**Comment by ArchLeaders** [comment]
> @ArchLeaders how does latest nightly look for you?

Can't seem to connect to `https://nuget-feed-nightly.avaloniaui.net/api/download/symbols`.

**Output**
```
NU1301: Unable to load the service index for source https://nuget.emzi0767.com/api/v3/index.json.
```

**Errors**
```
Unable to load the service index for source https://nuget.emzi0767.com/api/v3/index.json.
  The content at 'https://nuget.emzi0767.com/api/v3/index.json' is not a valid JSON object.
  Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
```
```
Unable to load the service index for source https://nuget.emzi0767.com/api/v3/index.json.
```

**Comment by ArchLeaders** [comment]
Latest nightly has the same issue as `>11.0.1`, there's a weird white border around the window and sizing isn't applied.

![image](https://github.com/AvaloniaUI/Avalonia/assets/80713508/95169e31-dad0-404a-bee0-5dff1214224b)

With this hack, sizing is weirdly off when dragging to fullscreen.

![image](https://github.com/AvaloniaUI/Avalonia/assets/80713508/7757d045-ab23-4f15-9c94-ccf141fe03a0)

Clicking the maximize button (with and without the hack) results in it having about 7-8px of padding on the inside of the border.

![image](https://github.com/AvaloniaUI/Avalonia/assets/80713508/930733ac-cca7-40e8-9ad1-fd5f28632744)

Dragging to fullscreen without the hack seals it to the edge of the screen (without the 7-8px cutoff that it had previously)

(My other monitor is in the screenshot as a reference to the taskbar)

![image](https://github.com/AvaloniaUI/Avalonia/assets/80713508/03577f6f-a10b-4ac0-aeb7-9054cdd20308)

**Comment by timunie** [comment]
is there any minimal sample I can check on my computer?

**Comment by ArchLeaders** [comment]
Not currently, but I can put one together pretty quick.

**Comment by ArchLeaders** [comment]
@timunie I created a minimal reproduction using the latest nightly, hope this helps:

https://github.com/ArchLeaders/AvaloniaBorderOnlyWindow

Thanks for looking into this :D

**Comment by rprimora-pricer** [comment]
> Latest nightly has the same issue as `>11.0.1`, there's a weird white border around the window and sizing isn't applied.
> 
> ![image](https://user-images.githubusercontent.com/80713508/273014478-95169e31-dad0-404a-bee0-5dff1214224b.png)

If zou are refering to the white border on top part of the Window, isn't this the `ExtendClientAreaTitleBarHeightHint` set to something above 0?

**Comment by ArchLeaders** [comment]
> If zou are refering to the white border on top part of the Window, isn't this the `ExtendClientAreaTitleBarHeightHint` set to something above 0?

Yes I am refering to that, I don't think that's the case though. Setting it to `0` has the same effect.

![image](https://github.com/AvaloniaUI/Avalonia/assets/80713508/e278cf1b-f92a-45bf-8e06-b97ff33e1615)

**Comment by rprimora-pricer** [comment]
@ArchLeaders Can zou try and set it to `-1`?

**Comment by timunie** [comment]
```diff
<Window x:Class="AvaloniaBorderOnlyWindow.ShellView"
        xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        Title="ShellView"
        Width="400"
        Height="400"
        d:DesignHeight="450"
        d:DesignWidth="800"
+       ExtendClientAreaChromeHints="SystemChrome"
+       ExtendClientAreaToDecorationsHint="True"
        SystemDecorations="BorderOnly"
        mc:Ignorable="d">
```

That works for me at least

**Comment by ArchLeaders** [comment]
> @ArchLeaders Can you try and set it to `-1`?

@rprimora-pricer Same effect with `ExtendClientAreaTitleBarHeightHint="-1"`.

**Comment by ArchLeaders** [comment]
> ```diff
> <Window x:Class="AvaloniaBorderOnlyWindow.ShellView"
>         xmlns="https://github.com/avaloniaui"
>         xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>         xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
>         xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
>         Title="ShellView"
>         Width="400"
>         Height="400"
>         d:DesignHeight="450"
>         d:DesignWidth="800"
> +       ExtendClientAreaChromeHints="SystemChrome"
> +       ExtendClientAreaToDecorationsHint="True"
>         SystemDecorations="BorderOnly"
>         mc:Ignorable="d">
> ```
> 
> That works for me at least

Oh yeah that does work. I wonder why I never tried that before.

**Comment by rprimora-pricer** [comment]
What issues you have with resizing?

**Comment by ArchLeaders** [comment]
Same as here: https://github.com/AvaloniaUI/Avalonia/issues/11685#issuecomment-1747436905

(Taskbar is not clickable when dragging to fullscreen)

**Comment by timunie** [comment]
then please update your minimal sample to reproduce the mentioned issue.

**Comment by ArchLeaders** [comment]
Changes should be synced.

Now the main button changes the window state from the code behind (which works as expected)

But dragging with window to the fullscreen (or `Win + ArrowUp`) disallows the use of the taskbar.

**Comment by rprimora-pricer** [comment]
> Same as here: [#11685 (comment)](https://github.com/AvaloniaUI/Avalonia/issues/11685#issuecomment-1747436905)
> 
> (Taskbar is not clickable when dragging to fullscreen)

Oh, I just saw what you meant by it. The hack does indeed fix the sizing but for some reason the Taskbar is not functioning. It is curious behavior.

Feels like a fullscreen gone wrong. I say this because normally in Windows to go fullscreen all you have to do is maximize the screen and set its bounds to be the same as the screen size. Windows will then hide the taskbar automatically. In our case, without the hack, when you drag a window for maximize same will happen.

**Comment by ArchLeaders** [comment]
> can't reproduce using Windows 11 and your Button, but see the issue using [Win]+[Arrow Up]. Strange issue.

Yes, the button works correctly on my end too.

**Comment by rprimora-pricer** [comment]
I found some more workarounds :)

Try adding this to a static class somewhere.

```cs
public static class WindowHelper
{
	[Flags]
	private enum SetWindowPosFlags : uint
	{
		HideWindow = 128,
		ShowWindow = 64
	}

	[DllImport("user32.dll", SetLastError = true)]
	private static extern int SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int x, int y, int cx, int cy, uint uFlags);

	public static void FixAfterMaximizing(IntPtr hWnd, Screen screen)
	{
		SetWindowPos(hWnd, IntPtr.Zero, screen.WorkingArea.X, screen.WorkingArea.Y, screen.WorkingArea.Width, screen.WorkingArea.Height, (uint)SetWindowPosFlags.ShowWindow);
	}
}
```

Then in that workaround that I gave you add this:
```cs
this.GetPropertyChangedObservable(WindowStateProperty).AddClassHandler<Visual>((t, args) =>
{
    /// I am doing this only for Windows.
    if (OperatingSystem.IsWindows())
    {
        /// If the state is maximised we will enter our code block.
        if (args.GetNewValue<WindowState>() == WindowState.Maximized)
        {
            /// Get the screen from the window.
            var screen = Screens.ScreenFromWindow(this);
            /// This is the part where we check if the actual height is more than the working area cos that would
            /// mean the window has gone over the taskbar.
            if (screen.WorkingArea.Height < ClientSize.Height * screen.Scaling) // <- Part with scaling is your suggestion
            {
                /// We set the client size of our window to be exactly the size of our working area.
                ClientSize = screen.WorkingArea.Size.ToSize(screen.Scaling);
                /// This is the last piece of the puzzle. If we maximize the Window by setting the state
                /// then this position will be correct. But, if the state is set as a result of dragging the window
                /// to the top then the position will most likely be less then 0 ( it will be (-7,-7) in our case).
                if (Position.X < 0 || Position.Y < 0)
                {
                    Position = screen.WorkingArea.Position; // <-- This is needed because you might have your taskbar in a different position (Left | Right | Top | Bottom).
                    WindowHelper.FixAfterMaximizing(TryGetPlatformHandle().Handle, screen);
                }
            }
        }
    }
});
```

I tried it on many screens and it works. Before it worked only on primary screen.

**Comment by timunie** [comment]
@rprimora-pricer I think instead of searching for several workarounds, it would be better to fix it in source. So if you want to, do this:
- Add your sample to src/samples/Sandbox
- Apply the "fix" in Win32 project
- File a PR if you found a valid fix

Still up to you, if you want to do a PR. I don't want to force you. Any help is appreciated ❤️

**Comment by emmauss** [comment]
could you test with, https://github.com/AvaloniaUI/Avalonia/pull/13228

**Comment by ArchLeaders** [comment]
> could you test with, #13228

@emmauss doesn't seem to have any effect.
