### ISSUE TITLE
[BUG] No more OnKeyDown for UserControl on RC1.

### ISSUE THREAD

**Issue by cyraid** [AvaloniaUI/Avalonia#11701]
**Describe the bug**
In 11 preview8 and below the `protected override void OnKeyDown` would fire, as long as the control is focused. The control would automatically gain focus using `Focus()` on `OnPointerEntered`. Now I notice even after calling `Focus()` my UserControl will not get focus and `OnGotFocus` will not be called.

**To Reproduce**
Create a custom UserControl (I override mine with custom render and ICustomDrawOperation, but that all still works), and override the `OnKeyDown`, `OnPointerEntered`, `OnGotFocus` etc.

So minimal would be make a UserControl, in OnPointerEntered add a Focus(), and see if OnGotFocus() works?

**Expected behavior**
The focus to work and my Key Events to still come in.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0.0-rc1.1

**Comment by maxkatz6** [comment]
Does your control has Focusable=true set?

**Comment by cyraid** [comment]
> Does your control has Focusable=true set?

@maxkatz6 Yup it does, thanks for the quick reply Max. Anything else I should look at?

**Comment by cyraid** [comment]
@maxkatz6 Apparently setting `Focusable="True"` on where I use it seems to work? Doesn't work being set on the `<UserControl>` itself? Before I didn't even need Focusable.

**Comment by maxkatz6** [comment]
Control that you are going to focus needs to have Focusable set to true. Previously it was a bug that this property was ignored.

**Comment by cyraid** [comment]
@maxkatz6 why doesn't it work when I put it on UserControl though? (Inside the view axaml)?

**Comment by timunie** [comment]
@cyraid has your UserControl set `Focusable="True"`?
