### ISSUE TITLE
Rendering glitch in ControlCatalog with DeferredRenderer

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#1171]
![default](https://user-images.githubusercontent.com/1067584/31050398-06c7785a-a652-11e7-94f5-d1c066a0c068.png)

Change the first line in `MainWindow.xaml.cs` to 
```xml
<Window xmlns="https://github.com/avaloniaui" MinWidth="500" MinHeight="300" Height="300"
```
and resize the window using the bottom grip.

**Comment by danwalmsley** [comment]
possibly related to #1194
