### ISSUE TITLE
Avalonia.Controls.ItemsRepeater does not use DataTemplate (ViewLocator) 11.0.0-rc1.1

### ISSUE THREAD

**Issue by cap5lut** [AvaloniaUI/Avalonia#11718]
**Describe the bug**
When implementing a view locator as explained [here](https://docs.avaloniaui.net/tutorials/todo-list-app/locating-views), simply binding the view models to the `ItemsSource` does not use the view locator, but uses the view model's `ToString()` method.
When using a data template with a content control, it works as expected.

```xml
        <ItemsRepeater ItemsSource="{Binding Examples}"/> <!-- broken -->
        
        <ItemsRepeater ItemsSource="{Binding Examples}"> <!-- works -->
            <ItemsRepeater.ItemTemplate>
                <DataTemplate x:DataType="vm:ExampleViewModel">
                    <ContentControl Content="{Binding}" />
                </DataTemplate>
            </ItemsRepeater.ItemTemplate>
        </ItemsRepeater>
        
        <ListBox ItemsSource="{Binding Examples}"/> <!-- works -->
```
The view locator is completely ignored. Neither the `IDataTemplate.Match()` method nor the `IDataTemplate.Build()` method will be called.

**To Reproduce**

1. [Clone this repository](https://github.com/cap5lut/Repro.AvaloniaItemsRepeater)
2. Build and start the application
3. See the differences

**Expected behavior**
Both `ItemsRepeater` variants should display exactly the same, the numbers from the `ExampleViewModel` instances.

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/31340422/0ce0be74-0471-473f-961c-5056434e2a34)

**Desktop**

- OS: Windows 10
- Version 11.0.0-rc1.1
- .NET 7.0.302

**Additional context**
Might be a similar issue as [https://github.com/AvaloniaUI/Avalonia/issues/10398](https://github.com/AvaloniaUI/Avalonia/issues/10398)

**Comment by maxkatz6** [comment]
It is by design with ItemsRepeater. See https://github.com/AvaloniaUI/Avalonia/issues/5362
