### ISSUE TITLE
Performance of scrolling ListBox in 11.0.0-rc1.1 is noticable worse than 11.0.0-preview4.

### ISSUE THREAD

**Issue by hamster620** [AvaloniaUI/Avalonia#11722]
Performance of scrolling ListBox with lots of items and complex DataTemplate becomes worse after upgrading from ```11.0.0-preview4``` to ```11.0.0-rc1.1```. The UI will get stucked when scrolling ListBox in our project which didn't happen in ```11.0.0-preview4```.

After doing some profiling, we found that the main thread takes long time executing ```MediaContext.Render()``` when scrolling ListBox in ```11.0.0-rc1.1```:
<img width="1288" alt="截圖 2023-06-09 下午1 46 46" src="https://github.com/AvaloniaUI/Avalonia/assets/26860570/2a7bedb8-6041-42a3-ae2d-070783291a6e">

While in ```11.0.0-preview4``` the main thread is not so busy as ```11.0.0-rc1.1```:
<img width="1282" alt="截圖 2023-06-09 下午1 45 11" src="https://github.com/AvaloniaUI/Avalonia/assets/26860570/2d9e07db-c77a-405a-a603-865f543fc88c">

The issue almost blocks our project, so we may need your help for some workaround or fix.

Here is a small demo for the issue:
[AvaloniaListBoxDemo.zip](https://github.com/AvaloniaUI/Avalonia/files/11702818/AvaloniaListBoxDemo.zip)

The layout of ListBoxItem in our project is much more complex than demo, so the issue is more noticeable in our project.

**To Reproduce**
1. Create a ListBox with complex DataTemplate.
2. Set ListBox.ItemsSource with lots of data (maybe > 100000).
3. Scroll the ListBox.

**Expected behavior**
Performance should be better than or equivalent to ```11.0.0-preview4```.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: macOS 13
- Version 11.0.0-rc1.1

**Comment by rabbitism** [comment]
relate to https://github.com/AvaloniaUI/Avalonia/issues/11641

**Comment by hamster620** [comment]
Performance in 11.0.0 seems to be better than 11.0.0-rc1.1 and acceptable.
