### ISSUE TITLE
Trim warnings for ObservableStreamPlugin etc

### ISSUE THREAD

**Issue by xecrets** [AvaloniaUI/Avalonia#11727]
**Describe the bug**
Still getting trim warnings in Avalonia UI 11.0.0rc1.1 (some of them may be out of Avalonia control, but the ObservableStreamPlugin is at least Avalonia, although it may of course depend on other libraries which may be the root cause of the issue. Don't know, just reporting what I'm seeing.)

As I don't think the application needs this functionality, is there anyway otherwise of getting rid of the warnings (short of just suppressing them)?

```
2>Avalonia.Data.Core.Plugins.ObservableStreamPlugin.ObservableStreamPlugin(): Using member 'Avalonia.Data.Core.Plugins.ObservableStreamPlugin.GetBoxObservable()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. StreamPlugin might require unreferenced code.
2>Avalonia.Data.Core.Plugins.ObservableStreamPlugin.ObservableStreamPlugin(): Using member 'Avalonia.Data.Core.Plugins.ObservableStreamPlugin.GetBoxObservable(Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. StreamPlugin might require unreferenced code.
2>Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForTypeInternal(ComActivationContextInternal*): Using member 'Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForType(ComActivationContext)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Built-in COM support is not trim compatible. https://aka.ms/dotnet-illink/com
2>Assembly 'Avalonia.Win32' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries
2>Assembly 'ReactiveUI' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries
2>Assembly 'System.Reactive' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries
```

**To Reproduce**
Start with the default Avalonia template.

Publish it for, for example win-x64, with the following publish profile:

```
<Project>
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Release\net7.0\publish\win-x64\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <_TargetId>Folder</_TargetId>
    <TargetFramework>net7.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
</Project>
```

and the following in the project:

```
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TrimMode>link</TrimMode>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
  </PropertyGroup>
```

Please note that the publish target is pretty smart about determining if it needs to bundle and trim, so do delete the `obj` folder before publish, otherwise it may appear to work...

**Expected behavior**

I would not expect trim errors, unless of course this for some reason is fundamental, but I don't really see how it can or should be, compile bindings is enabled as per default also. Then again, I'm a little out of my depth here. I just don't like warnings, and try to heed them when I can.

**Desktop (please complete the following information):**

- OS: Windows 11, .NET 7, Visual Studio 2022
- Version Avalonia UI 11.0.0-rc1.1

**Comment by maxkatz6** [comment]
ObservableStreamPlugin isn't used and should be trimmed away when you don't use ReflectionBinding (which is enabled by default). If you use compiled bindings only, you are safe.

But it seems ObservableStreamPlugin type is referenced somewhere somehow keeping it in assembly still, causing these warnigns.

**Comment by xecrets** [comment]
As mentioned, the app (it's just the `Avalonia .NET Core MVVM App` template) is using compiled bindings, and it does appear to work. But for one the warning is "scary", and for another this should mean that `ObservableStreamPlugin` and it's dependencies are kept in the trimmed output, which thus is not quite as trimmed as it could be.

**Comment by timunie** [comment]
@xecrets can you share your sample? I know you said it's from the template, but probably we have overseen something. So please upload it here.

**Comment by xecrets** [comment]
Of course! Do remember that you need to delete the `obj` folder to ensure that the trimming process actually runs. Not even `clean` or `rebuild` will work to ensure that...

[avalonia-mvvm.zip](https://github.com/AvaloniaUI/Avalonia/files/11712052/avalonia-mvvm.zip)

**Comment by timunie** [comment]
@xecrets thanks for the sample. I can also see the trim warnings. They get less if I remove Diagnostics package and ReactiveUI package (Expected) but I don't get zero. I have no idea how harmful these are, but at lease something we should keep an eye on.

**Comment by xecrets** [comment]
Yes, I think the primary thing to look into is *why* does `ObservableStreamPlugin` get referenced at all? While the app will work as long as you don't actually *use* any of the trimmed code, the warning is just that. Thinking about it, I'll revise my statement earlier about the warning indicating that code that should be trimmed is not, if I understand it correctly, it's the other way around. So the code after trimming does not get unnecessarily big, but what the warning says is that there's a potential of problem if `ObservableStreamPlugin` is actually used, since it's marked as possibly referencing types via reflection which then the trimmer will know nothing about. It would be best I guess if the `ObservableStreamPlugin` was in a separate nuget package and assembly, so it could be completely excluded when not needed, like the `Diagnostics` package. Now there's apparently a reference, and while it's not actually normally called or used, it *could* be... Thus the warning, if I understand this correctly.

The `Diagnostics` package should not be problem, as there's a conditional include, excluding it in `Release` mode:

```
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.0-rc1.1" />
```

**Comment by laolarou726** [comment]
Any ideas of how to get rid of this warning message?
