### ISSUE TITLE
Applying a Color to an image in avalonia

### ISSUE THREAD

**Issue by YWilix** [AvaloniaUI/Avalonia#11742]
Hello while I'm working on my project I thaught it would be cool to have an attached property to images that lets you change the image color easily something like this :

**Normal Image : **
![outlet](https://github.com/AvaloniaUI/Avalonia/assets/87858497/88d500f9-e533-4307-abab-970c8be58e48)

**After Setting the color property to Red : **

![RedOutlet](https://github.com/AvaloniaUI/Avalonia/assets/87858497/962b6c75-f42d-4268-883d-955fd3280965)

**Comment by robloo** [comment]
I think this is out of scope for a UI framework. This type of thing should be done using an image library and processing your bitmaps directly before passing to an Image.

The only useful general-purpose feature I can see similar to this would be grayscale mode which some frameworks have I believe.

Unless you can give a really compelling use case I think this feature request should be closed. Keep coming up with good ideas though!

**Comment by YWilix** [comment]
@robloo In Reality , I was searching for a way in my project to make a button (with an image as it's background) darker when the mouse is over it  something like this : 
![imagecoloravaloniaproblem](https://github.com/AvaloniaUI/Avalonia/assets/87858497/18ce02b9-8eac-45db-8487-8e510aae37c1)

I suggested adding this features to images because it will give a solution to this problem for the majority of controls

**Comment by maxkatz6** [comment]
> darker when the mouse is over it something like this :

Usually, it's done by changing the opacity or adding a second prepared image. Possibly can be done with Border on top of it with OpacityMask, but the quality might suffer this way.

In general, having the possibility to apply a filter on the control would be a good feature. Something like https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.effects.shadereffect?view=windowsdesktop-7.0 from WPF (or UWP lower level composition APIs, with some extensions on top of it). But it probably wouldn't be done anytime soon. We have basic [bitmap effects](https://github.com/AvaloniaUI/Avalonia/pull/11014) support though now.

**Comment by robloo** [comment]
A general effect would be fine. But a special property just to control image hue still doesn't sound like a good idea.

**Comment by YWilix** [comment]
@maxkatz6 I understand , Thanks for the info though !

**Comment by Sorien** [comment]
maybe I'm wrong but there is an example to create blur effect https://gist.github.com/kekekeks/ac06098a74fe87d49a9ff9ea37fa67bc same method should be used to tint image.

**Comment by Fido789** [comment]
Well, I had such a control, unfortunately it is not working in v11 due to breaking changes.

```
using System.IO;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Media;
using Avalonia.Media.Imaging;
using Avalonia.Skia;
using SkiaSharp;

namespace Mvvm.Avalonia;

public class ColorizedImage : Image
{
    public static readonly StyledProperty<Color> ColorProperty =
        AvaloniaProperty.Register<ColorizedImage, Color>(nameof(Color));

    static ColorizedImage()
    {
        AffectsRender<ColorizedImage>(ColorProperty);
    }

    public Color Color
    {
        get => GetValue(ColorProperty);
        set => SetValue(ColorProperty, value);
    }

    public override void Render(DrawingContext context)
    {
        var source = Source;

        if (source == null || !(Bounds.Width > 0) || !(Bounds.Height > 0))
        {
            return;
        }

        var viewPort = new Rect(Bounds.Size);
        var sourceSize = source.Size;

        var scale = Stretch.CalculateScaling(Bounds.Size, sourceSize, StretchDirection);
        var scaledSize = sourceSize * scale;
        var destRect = viewPort
            .CenterRect(new Rect(scaledSize))
            .Intersect(viewPort);

        var interpolationMode = RenderOptions.GetBitmapInterpolationMode(this);
        var pixelSize = new PixelSize((int)destRect.Width, (int)destRect.Height);
        var dpi = new Vector(96, 96);

        using var originalRenderTarget =
            new RenderTargetBitmap(pixelSize, dpi);
        using var originalContextImpl = originalRenderTarget.CreateDrawingContext(null);
        using var originalSkiaContext = originalContextImpl;
        using var originalContext = new DrawingContext(originalContextImpl);

        originalContext.DrawImage(source, new Rect(source.Size), destRect, interpolationMode);

        using var colorizedRenderTarget =
            new RenderTargetBitmap(pixelSize, dpi);
        using var colorizedContextImpl = colorizedRenderTarget.CreateDrawingContext(null);
        using var colorizedSkiaContext = colorizedContextImpl;

        using var paint = new SKPaint
        {
            ColorFilter = SKColorFilter.CreateBlendMode(
                Color.ToSKColor(),
                SKBlendMode.SrcIn)
        };

        using var stream = new MemoryStream();
        originalRenderTarget.Save(stream);
        stream.Seek(0, SeekOrigin.Begin);

        using var skBitmap = SKBitmap.Decode(stream);

        var leaseFeature =
            colorizedSkiaContext.GetFeature(typeof(ISkiaSharpApiLeaseFeature)) as ISkiaSharpApiLeaseFeature;
        using var lease = leaseFeature?.Lease();
        var canvas = lease?.SkCanvas;

        canvas?.DrawBitmap(skBitmap, 0, 0, paint);

        context.DrawImage(colorizedRenderTarget, destRect, destRect, interpolationMode);
    }
}
```

**Comment by Fido789** [comment]
@maxkatz6 Max you seem to know about this stuff. Now when the Image.Render is sealed, what is a proper way to adapt the code above to v11?

**Comment by timunie** [comment]
@Fido789 you may need to inherit Control instead.
