### ISSUE TITLE
Visual studio previewer does not work on update to avalonia 11

### ISSUE THREAD

**Issue by Eugenenoble2005** [AvaloniaUI/Avalonia#11745]
I've updated a few of my projects to Avalonia 11.0.0-rc1.1 and the visual studio previewer no longer functions. It shows the preview, but on any xaml update it goes blank and required a rebuild before it starts again. This is exceedingly frustrating as i cannot keep building my project every time i change xaml. Issue started on update to avalonia 11. Works fine in Rider previewer.

**Comment by maxkatz6** [comment]
Duplicate of https://github.com/AvaloniaUI/AvaloniaVS/issues/334
