### ISSUE TITLE
EllipseGeometry.Clone missing Center, RadiusX, and RadiusY property assignments

### ISSUE THREAD

**Issue by boydpatterson** [AvaloniaUI/Avalonia#11754]
**Describe the bug**
The method for [EllipseGeometry.Clone](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Media/EllipseGeometry.cs#L95) only initializes the `Rect` of the new geometry and does not initialize the properties `Center`, `RadiusX`, and `RadiusY`.

**Expected behavior**
The clone should have the same `Center`, `RadiusX`, and `RadiusY` as the original.

**Comment by robloo** [comment]
Great catch, I'll do a PR to fix that soon if someone doesn't beat me to it.
