### ISSUE TITLE
Can't Acess to CompositingRenderer

### ISSUE THREAD

**Issue by Wael1231** [AvaloniaUI/Avalonia#11757]
Hey, when i was updating an old project avalonia 0.10.0 to 11.0.0rc-1.1 i can't acess CompositingRenderer.  and there anymore DeferredRenderer The Error : CompositingRenderer is inaccessible due to its protection level

I wante to use it in  [HarmonyPatch(typeof(CompositingRenderer), "Avalonia.Rendering.IRenderLoopTask.Render")] 

How i can fix it ?

**Comment by timunie** [comment]
@Wael1231 why do you open an issue for a question? Please use Telegram or Discussion for such a question. Moreover, if you consider it a bug, please always fill in the issue template. Thank you for your understanding. 

Back to the topic: Please let us know what exactly you want to achieve, so we hopefully can give you an alternative. I really don't know what HarmonyPatch does tbh.

**Comment by maxkatz6** [comment]
It's not a bug.
CompositingRenderer is an implementation detail and was hidden in recent previews/rc.
We do not provide source/binary compatibility with patching tools that access internal APIs.
