### ISSUE TITLE
Avalonia Web not support CJK. How can i fix this?

### ISSUE THREAD

**Issue by honeyhead** [AvaloniaUI/Avalonia#11774]
![image](https://github.com/AvaloniaUI/Avalonia/assets/3714819/c60b94a1-52ec-43f2-a3b2-d5117aac829b)

Korean is printed normally on platforms other than browsers, but Korean is broken in browsers.

Do I need to add a Korean font separately?
What do you need to do to fix this part?

**Comment by honeyhead** [comment]
![image](https://github.com/AvaloniaUI/Avalonia/assets/3714819/1b51290f-331d-401a-9fea-1766cfc3d67c)

**Comment by maxkatz6** [comment]
Yes, you need to include your fonts. As browser API doesn't really tell enough information about system fonts, so empty canvas-rendered web app will have a basic monospaced font.

See https://github.com/AvaloniaUI/Avalonia/issues/8938
And https://docs.avaloniaui.net/docs/getting-started/assets#referencing-assets

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/7037#issuecomment-981521743
