### ISSUE TITLE
investigate use of REMOBJECT c# Sslands toolshains

### ISSUE THREAD

**Issue by cesarchefinho** [AvaloniaUI/Avalonia#11772]
Investigate use of remobjects c#

( see https://www.elementscompiler.com/elements/hydrogene/ )

Remobjects c# toolchain compiles to windows, Linux, macos, ios and for android

Why is this needed:

Because remobjecta compile directly to plarform native without aot, vm, jit or even interop and in android performance will be better than xamarin.android because compiled code is lready native java bytecode

**Comment by kekekeks** [comment]
The current plan is to support NativeAOT (which would produce native assembly code instead of bytecode) and minimize JNI calls.

**Comment by MikeCodesDotNET** [comment]
> but investigatin use of remobjects can be bether than nativeaot, also remobjects can produce native arm machine code ndk (like aot but bether) and java byte code (that is interoplesss because already is java)

Does anyone even use RemObjects? I certainly don’t see the value in spending time on this.
