### ISSUE TITLE
OpenGlControlBase not rendering on Android - avalonia 11-preview7

### ISSUE THREAD

**Issue by zeusware** [AvaloniaUI/Avalonia#11788]
**Describe the bug**
Teapot is showing at Windows Desktop but on Android Device and Emulator dont. 

**To Reproduce**

***files***
[AUI_0.11-preview7_OpenGL_not_Render_on_Android.zip](https://github.com/AvaloniaUI/Avalonia/files/11751706/AUI_0.11-preview7_OpenGL_not_Render_on_Android.zip)

Create a Project via "Template for Avalonia" (C#), select Desktop and Android, Select Reactive UI Or Community Toolset (both tested)
Add Snippet Control "https://github.com/AvaloniaUI/Avalonia/tree/master/samples/ControlCatalog/Pages)/OpenGlPage.xaml" to it.
![image](https://github.com/AvaloniaUI/Avalonia/assets/18285340/6af32df8-e3df-4b72-b61d-50be4454b065)

(See attached project Files)

Run both examples to compare.
Rund Android on Emulator and/or connected development Device (e.g 
![image](https://github.com/AvaloniaUI/Avalonia/assets/18285340/fef51b2c-dfa7-4c67-b109-7a1e3725f828)
)

**Expected behavior**
teapot should be rendered on Desktop and Android Emulator and especial on the Device.

**Screenshots**

**Desktop (please complete the following information):**
[AUI_0.11-preview7_OpenGL_not_Render_on_Android.zip](https://github.com/AvaloniaUI/Avalonia/files/11751706/AUI_0.11-preview7_OpenGL_not_Render_on_Android.zip)

Desktop works fine (Win 10)
Android Device:
![image](https://github.com/AvaloniaUI/Avalonia/assets/18285340/fef51b2c-dfa7-4c67-b109-7a1e3725f828)
Android Emulator's
![image](https://github.com/AvaloniaUI/Avalonia/assets/18285340/a2670d6b-b087-40d5-ae48-472e88000888)

- Version 0.11-preview7 

**Additional context**
--

**Comment by maxkatz6** [comment]
Can you test with RC builds?

**Comment by zeusware** [comment]
Nope,... v11.0.0-rc1.1 do not work either...

Image is showing the emulator but on the device is even not working:
![image](https://github.com/AvaloniaUI/Avalonia/assets/18285340/a59f575f-24e4-4073-9be8-d2ea017d9b73)

Desktop is working as expected:
![image](https://github.com/AvaloniaUI/Avalonia/assets/18285340/a09cab99-2cd9-4a3f-b8d5-1414ea44ebd2)

**Comment by emmauss** [comment]
Could you test on a real device?

**Comment by zeusware** [comment]
I Did, like i written b4...
I tested it on an Samsung Android Device..
![image](https://github.com/AvaloniaUI/Avalonia/assets/18285340/fef51b2c-dfa7-4c67-b109-7a1e3725f828)

**Comment by anose001** [comment]
Is this in plan to work in the future on the simulator?

**Comment by orosbogdan** [comment]
The same question, will this work on the android simulator from visual studio ?
