### ISSUE TITLE
Interruption during Macos build

### ISSUE THREAD

**Issue by Azukiro** [AvaloniaUI/Avalonia#11792]
**Describe the bug**
I want to try to compile my project for macos. But I got the error can't open the app because it may be damaged or incomplete

**To Reproduce**
I create a default Avalonia Template Crossplaform app.

1. On the desktop project I modify it for build on macos :
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>

	  <RuntimeIdentifiers>osx-x64</RuntimeIdentifiers>
	  <CFBundleName>inpixio.desktop</CFBundleName>
	  
	  <CFBundleDisplayName>inpixio</CFBundleDisplayName>
	  <CFBundleIdentifier>com.inpixio.macos</CFBundleIdentifier>
	  <CFBundleVersion>1.0.0</CFBundleVersion>
	  <CFBundlePackageType>APPL</CFBundlePackageType>
	  <CFBundleExecutable>inpixio</CFBundleExecutable>
	  <CFBundleShortVersionString>1.0.0</CFBundleShortVersionString>
	  
	  <NSPrincipalClass>NSApplication</NSPrincipalClass>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Dotnet.Bundle" Version="0.9.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\inpixio\inpixio.csproj" />
  </ItemGroup>
</Project>
`

2. Then I execute the command :  `dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-x64 -property:Configuration=Release -p:UseAppHost=true`

3. I send my file to my mac
4. I change the chmod of the whole app to 777

5. I click on my .app and I get the error "Can't open the app because it may be damaged or incomplete".

Can someone help me to resolve that please ?

**Comment by maxkatz6** [comment]
Please check [macOS Console app](https://macpaw.com/how-to/use-mac-console-app) to see logs related to the crash (similar to how Event Viewer works in Windows).
Quite likely it's related to signing, as m1 builds require app to be signed without telling reasonable error runtime time.
Also, you can try official .NET 6 packaging using "net6.0-macos" target framework (for convenience, requires separated executable project). I wrote [a minimal example project](https://github.com/maxkatz6/avalonia-net6-macos-sample/blob/main/README.md) a while ago.

Closing as not related to Avalonia.
