### ISSUE TITLE
ProgressBar

### ISSUE THREAD

**Issue by ncarrillo** [AvaloniaUI/Avalonia#118]
ProgressBar is currently missing these properties compared to its counterparts in the XAML world:
- [ ] `IsIndeterminate`
- [ ] `Orientation`

[Here](https://msdn.microsoft.com/en-us/library/system.windows.controls.progressbar%28v=vs.110%29.aspx) is a link to the WPF ProgressBar documentation to serve as a reference for these properties.

**Comment by jp2masa** [comment]
I'd like to work on this.

**Comment by grokys** [comment]
This would be a good one to tackle I think, don't think there will be any difficulties here ;)

**Comment by jkoritzinsky** [comment]
Fixed by #1175.
