### ISSUE TITLE
Clicking on submenu causes it to reappear

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#1180]
![menubug](https://user-images.githubusercontent.com/1067584/31111967-bef2c506-a819-11e7-95a8-b1c9508e35d8.gif)

**Comment by JurjenBiewenga** [comment]
This appears to not happen on Win32 platforms.

**Comment by philthomasme** [comment]
This behavior of the menu not disappearing is happening on OSX as well.

**Comment by grokys** [comment]
Fixed by #1812.
