### ISSUE TITLE
Macos and windows behave inconsistently

### ISSUE THREAD

**Issue by jim-jiang-github** [AvaloniaUI/Avalonia#11806]
**Describe the bug**
Like this code:
In MacOS openfiledialog can not run in thread, but Windows works well.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="775" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/29189410/b0143cf3-7491-4279-aeda-1a62c48c2dd5">

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. preview4]

**Additional context**

**Comment by maxkatz6** [comment]
It's not a bug, and it's not a supported scenario. 
MacOS supports only single UI thread, and any windows must be opened from it.

There are two solutions for this inconsistency:
1. Either disallow windows backend to open picker on non-main thread.
2. Or force macos backend to dispatch picker on the main thread (i.e. first thread).

I believe both solutions are bad and cause more issues than it solves. Though first one would be at least consistent with `new Window()` thread validation.

**Comment by tomenscape** [comment]
"Can not run in a thread" means that the process crashes in native code if this is tried. `Open*PickerAsync` could at least check for this ahead of time and throw a C# exception instead.
