### ISSUE TITLE
The FileTypeFilter for FilePickerOpenOptions is not perfect

### ISSUE THREAD

**Issue by enycw001** [AvaloniaUI/Avalonia#11824]
**Describe the bug**
Now I have two files
1."a.data"
2."Avalonia.Controls.DataGrid.dll"
The second file will appear in openfiledialog, and its suffix will not be ".data"
I don't know if this is my problem, look at my code below

**To Reproduce**

`
FileTypeFilter = new FilePickerFileType[]
            {
                new("ElementsData")
                {
                    Patterns = new[] { "*.data" },
                    MimeTypes = new[] { "*/*" }
                },
                FilePickerFileTypes.All
            }
`

**Expected behavior**
Only files with the correct suffix will appear

**Desktop (please complete the following information):**

- OS: Windows 11  22621.963
- Version 11.0.0-rc1.1

**Comment by maxkatz6** [comment]
> FileTypeFilter = new FilePickerFileType[] { new("ElementsData") { Patterns = new[] { "*.data" }, MimeTypes = new[] { "*/*" } }, FilePickerFileTypes.All }

If you don't know the correct mime type, better to not specify it then. Some backends will use "*.*" over the pattern if it's available.

**Comment by enycw001** [comment]
> > FileTypeFilter = new FilePickerFileType[] { new("ElementsData") { Patterns = new[] { "_.data" }, MimeTypes = new[] { "_/*" } }, FilePickerFileTypes.All }
> 
> If you don't know the correct mime type, better to not specify it then. Some backends will use "_._" over the pattern if it's available. But it's likely unrelated to windows backend.

I just need to ".data" file suffix, but "Avalonia.Controls.DataGrid.dll"  also appeared, see figure
![666](https://github.com/AvaloniaUI/Avalonia/assets/9591833/aef584e2-5183-4b02-be13-2ec4a2e1021a)

**Comment by timunie** [comment]
Ahhh I see. So the issue is that the file name is `Avalonia.Controls.DataGrid.dll` where `.Data` is found in the middle of the name. Interesting finding. How does WPF deal with this?

**Comment by enycw001** [comment]
I modified the RE to fix this feature
At present, I have not found any other problems caused by such modification
Here's my code
File:src/Avalonia.Dialogs/Internal/ManagedFileChooserFilterViewModel.cs
Line:21
`
_patterns = filter.Patterns?
                .Select(e => new Regex("^" + Regex.Escape(e).Replace("\\*", ".*") + "$", RegexOptions.Singleline | RegexOptions.IgnoreCase))
                .ToArray();
`

**Comment by maxkatz6** [comment]
@enycw001 just to confirm, your issue was specifically about managed file dialog? You haven't mentioned it before.
If you have a fixed code, can you open a PR? Just make sure it works with patterns like "*.png" and "*proj" (matching "av.csproj").

**Comment by enycw001** [comment]
> @enycw001 just to confirm, your issue was specifically about managed file dialog? You haven't mentioned it before. If you have a fixed code, can you open a PR? Just make sure it works with patterns like "*.png" and "*proj" (matching "av.csproj").

Now I have four files
![444444](https://github.com/AvaloniaUI/Avalonia/assets/9591833/2111708c-e36f-4fb4-a06c-0ec7eb3c968f)

patterns are defined as
`
Patterns = new[]  {
                                "*proj",
                                "*.png",
                                "*e*.data"
}
`
The file is now matched correctly and only the file suffix is judged
![6666](https://github.com/AvaloniaUI/Avalonia/assets/9591833/7d265c88-d223-4dca-b90e-08c8480413d0)
As for PR, I'm really sorry because my network is so rubbish

**Comment by timunie** [comment]
> As for PR, I'm really sorry because my network is so rubbish

Really? o.O it's just one tiny file, didn't expect it to be a heavy task but you never stop learning. However, i can do it for you. Thanks for the fix and support anyway.
