### ISSUE TITLE
NRE in Avalonia.Media.MediaContext.CommitCompositor

### ISSUE THREAD

**Issue by TETYYS** [AvaloniaUI/Avalonia#11825]
**Describe the bug**
![devenv_b9NQtVPdpT](https://github.com/AvaloniaUI/Avalonia/assets/3091645/6ab99fac-e521-4383-ac6f-02c88c9ef5f7)

**To Reproduce**
I don't know how, as you can see I have 15 minutes on my debugging session, I was using my application, nothing special in particular when I got greeted with this error

**Expected behavior**
No exception

**Desktop (please complete the following information):**

- OS: Windows 22H2 19045.2965
- Version 11.0.0-rc1.1 with Avalonia.Controls.TreeDataGrid 11.0.0-preview8 which does not work

**Additional context**
I have a minidump with heap for a Avalonia developer if needed

**Comment by rabbitism** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/11605
