### ISSUE TITLE
UI becomes unresponsive after long idle time (RC1.1)

### ISSUE THREAD

**Issue by cok666n** [AvaloniaUI/Avalonia#11839]
**Describe the bug**
We have an app that runs on linux desktop mode (Debian 12, LXDE) it uses ReactiveUI and the MVVM pattern. 
The app eventually becomes unresponsive when left idle for long periods of time. 

Only the UI refresh/interactivity seems to have a problem as we can see from the logs that some requests handled by other threads that were launched by the app seem to work fine. We also see some threads being launched from time to time (using htop) and they are most likely launched by a DispatcherTimer the app has set up. Yet their expected results don't show on screen. 

The app logs to the trace, we can retrieve the events using journalctl, however nothing appears in the logs at the time of the bug (we have the exact time since the program displays a clock which stopped being updated). 

I realize this is somewhat vague, please let me know if you have any idea on how I could solve that and/or get more information on what is actually happening. 

**To Reproduce**
We have experienced this on 2 machines, the app has to be left alone for several hours and at some point it becomes unresponsive. One machine took about 12 hours, the other about 2 days. 

**Expected behavior**
As this is a POS app it is expected that it will often be idle for long periods of time and should always be ready to operate. 

**Desktop (please complete the following information):**
- OS: Debian 12
- Version: 11 rc1.1

**Comment by timunie** [comment]
you can do two things to help us here

1. try again with latest nightly builds. Maybe the issue is magically gone
2. If 1 does not help, try to reproduce the issue in a simpler minimal sample. Any I/O operations? Do you see any RAM values increasing all the time?

**Comment by MercyPillow** [comment]
I've experienced this too on (windows 11) RC1.1, although a lot more frequent (~10min), I have yet to be able to track down any cause either.

So far it happened about every 10 min's with ContentControl binding to a view. the program still accepts events etc but no graphical changes are displayed, dragging the window around works but does not cause any redraws. the only way to "reset" it has been to drag the window to aero snap (win11) and then things start functioning again.

no IO operations just sitting idle and no memory leaks that I've noticed. 

standard app builder. and nothing suspicious logged with LogToTrace.

**Comment by timunie** [comment]
@MercyPillow also for you the question if you can try nightly builds again? If still no better, please try to file a simple sample of what you have if possible. We'd like to investigate this issue further as I don't see it in my Apps.

**Comment by cok666n** [comment]
I've repeated the same issue on Debian 11.7 and another Debian 12, still no luck in reproducing in Windows though.

Ive built and started 2 new versions, one is built on Preview 8 and the other on the nightly build. Both are running fine right now, I will report back if they fail in the long run. If the bug is still there they should freeze overnight. 

The reason for trying out Preview 8 is I am fairly certain we did not have those issues in that version, unless something else has changed on those computers that I would not be aware of.

**Comment by cok666n** [comment]
Something that might be interesting too: 

I have a dispatcher timer in my ViewModel, it ticks every 5 seconds to check if it should update a "CurrentTime" property that is binded to a TextBlock. When the textblock updates I get the following in the trace : 
```
Jun 19 22:32:04 CDL-MTL-12 cdl_hmi[3060]: [Layout]Layout pass finished in '00:00:00.0044502'(LayoutManager #62074597)
Jun 19 22:33:04 CDL-MTL-12 cdl_hmi[3060]: [Layout]Started layout pass. To measure: '1' To arrange: '0'(LayoutManager #62074597)
```

I get those 2 lines every minute, as expected I suppose. Last night my UI froze displaying 22:38 on that clock, yet the underlying code did not seem to mind as it continued logging the same thing : 
```
Jun 19 22:36:04 CDL-MTL-12 cdl_hmi[3060]: [Layout]Started layout pass. To measure: '1' To arrange: '0'(LayoutManager #62074597)
Jun 19 22:36:04 CDL-MTL-12 cdl_hmi[3060]: [Layout]Layout pass finished in '00:00:00.0003465'(LayoutManager #62074597)
Jun 19 22:37:04 CDL-MTL-12 cdl_hmi[3060]: [Layout]Started layout pass. To measure: '1' To arrange: '0'(LayoutManager #62074597)
Jun 19 22:37:04 CDL-MTL-12 cdl_hmi[3060]: [Layout]Layout pass finished in '00:00:00.0096265'(LayoutManager #62074597)
Jun 19 22:38:04 CDL-MTL-12 cdl_hmi[3060]: [Layout]Started layout pass. To measure: '1' To arrange: '0'(LayoutManager #62074597)
Jun 19 22:38:04 CDL-MTL-12 cdl_hmi[3060]: [Layout]Layout pass finished in '00:00:00.0088320'(LayoutManager #62074597)
Jun 19 22:39:04 CDL-MTL-12 cdl_hmi[3060]: [Layout]Started layout pass. To measure: '1' To arrange: '0'(LayoutManager #62074597)
Jun 19 22:39:04 CDL-MTL-12 cdl_hmi[3060]: [Layout]Layout pass finished in '00:00:00.0004412'(LayoutManager #62074597)
Jun 19 22:40:04 CDL-MTL-12 cdl_hmi[3060]: [Layout]Started layout pass. To measure: '1' To arrange: '0'(LayoutManager #62074597)
Jun 19 22:40:04 CDL-MTL-12 cdl_hmi[3060]: [Layout]Layout pass finished in '00:00:00.0082354'(LayoutManager #62074597)
```

Not sure that is relevant to the case or not, just thought Id share that.

**Comment by timunie** [comment]
this gets us maybe a bit further. try to create a minimal sample using nightly build that only does this update. Not every 5 sec but maybe every 200 ms. It should become unresponsive much sooner if that's the root. In that case, share the sample with us.

**Comment by dbriard** [comment]
Not sure it could be the same issue but I have very anoying freezes that make the app unresponsive. It is on windows, with a maximized window and I have to move the title bar to resolve the freeze. I didn't had time to investigate but I never noticed it until I upgraded to rc1.1 from preview 8. Look like issue with mouse capture for my case, but it is totally random, and I do not changed my code recently..

**Comment by timunie** [comment]
@dbriard can you try again nightly? There was something but don't remember if it's fixed.

**Comment by dbriard** [comment]
> @dbriard can you try again nightly? There was something but don't remember if it's fixed.

Thanks, I am on vacation this week but I will try with latest nightly build on Monday (crossed fingers)

**Comment by cok666n** [comment]
This one is kinda hard to report on... Ive built my application with Preview8 and with the Nightly, both versions have been running on 2 Debian machines for over 48 hours now with no issues. 

I could not re-create the bug  in a smaller application (with rc1.1), so far anyway.

**Comment by timunie** [comment]
@cok666n I still have a feeling that the timer does invoke something "bad". So maybe an idea to follow that path. Other than that, I see no option for us to help solving the issue. 

Other idea: Do you have any animation running constantly?

**Comment by MercyPillow** [comment]
I had a custom rich text box that had a timer for the blinking caret ( lifted from the avalonia textbox ) and after removing that i have been running the program for 40h with no locking.

![image](https://github.com/AvaloniaUI/Avalonia/assets/1374183/8793534d-5786-450d-bdfe-d74d7c666327)
![image](https://github.com/AvaloniaUI/Avalonia/assets/1374183/66da272c-388b-4acf-a440-60f927d7beee)

So i think its related somehow to the timer or excessive InvalidateVisual calls as put by timunie. but dont see how as the Avalonia.Controls.TextBox has an identical implementation and has no issue I'm aware of. sorry i cant be of more help.

**Comment by timunie** [comment]
@MercyPillow that is of great help. If you can file a minimal sample with your custom control included, we can take a way deeper look into it and try it in our sandbox.

**Comment by workgroupengineering** [comment]
> I had a custom rich text box that had a timer for the blinking caret ( lifted from the avalonia textbox ) and after removing that i have been running the program for 40h with no locking.
> 
> ![image](https://user-images.githubusercontent.com/1374183/248064038-8793534d-5786-450d-bdfe-d74d7c666327.png) ![image](https://user-images.githubusercontent.com/1374183/248064261-66da272c-388b-4acf-a440-60f927d7beee.png)
> 
> So i think its related somehow to the timer or excessive InvalidateVisual calls as put by timunie. but dont see how as the Avalonia.Controls.TextBox has an identical implementation and has no issue I'm aware of. sorry i cant be of more help.

I'll rewrite your code as follows to avoid unnecessary allocations:

```csharp
        public IBrush? CaretBrush
        {
            get => GetValue(CaretBrushProperty);
            set => SetValue(CaretBrushProperty, value);
        }

        private ImmutablePen _caretPen = new ImmutablePen(Brushes.Black);

        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);
            if (change.Property == CaretBrushProperty)
            {
                var brush = (change.NewValue as IBrush
                    ?? Brushes.Black).ToImmutable();
                _caretPen = new ImmutablePen(brush);
            }
        }

        public override void Render(DrawingContext context)
        {
            base.Render(context);
            //Your code for detect blink
            ....
           //Draw caret
            var (p1, p2) = GetCaretPoints();
            context.DrawLine(_caretPen, p1, p2);
        }
```

**Comment by 292390450** [comment]
I also encountered the same problem, upgrading to rc1.1 on the Android platform, the interface did not respond, but the program code was running normally

**Comment by timunie** [comment]
@292390450 I still have not seen a sample to reproduce. So if you have a minimal sample to reprdocue, please share it 🙏

**Comment by cok666n** [comment]
From my end, I've tried to reproduce the error in a minimal application, in RC1.1, MVVM pattern with ReactiveUI, VM starting a DispatcherTimer and updating a binded property every 10ms or so (thousands times faster than my app). I could not reproduce the bug. 

This is basically what my application does when totally idle, so there must be something else at play here. 

In my main application though, I cannot reproduce the bug in preview8 (yet, anyway). And my attempts at reproducing it in the nightly builds also did not succeed. 

We decided to stick on preview8 for now since we never witnessed the bug in that version.

**Comment by timunie** [comment]
@cok666n are you saying the issue is gone in nightly builds for you? If yes, consider to close this issue as you were the opener.

**Comment by dbriard** [comment]
I do not have my above issue anymore.

**Comment by cok666n** [comment]
@dbriard might I ask which Avalonia version you are now using?

**Comment by dbriard** [comment]
> @dbriard might I ask which Avalonia version you are now using?

I noticed occasional UI freeze issue many times in rc1, but not sure it is the same bug. It resolved with rc2 I think, but not sure. After my vacation I worked 1 day with the same project still in rc1 with no issue, so may be the cause was outside Avalonia... But in all cases, it seems I do not have UI freeze anymore with rc2.

**Comment by cok666n** [comment]
So, as far as I know this bug is gone as of the 11.0 release, I could not reproduce it over long periods of time in the 11.0 version while I could reproduce it multiple times in RC1. I have no clue as to why it happened and could not have it happen in a minimal application (even in RC1). 

Thanks
