### ISSUE TITLE
Multiple selection in virtualized ListBox lose one of selected items

### ISSUE THREAD

**Issue by reejk** [AvaloniaUI/Avalonia#11866]
**Describe the bug**
When trying to extend the selection when the selected items are out of view, they may lose their selected state. When `ItemsPanel=StackPanel` works correctly.

**To Reproduce**

1. Run the VirtualizationDemo sample
2. Enable `Multiple` Selection
3. Select the first item in the ListBox _(or multiple items)_
4. Scroll to the end of the list
5. Select the last item with Ctrl key pressed
6. Scroll to the top of the list
7. The item _(one of the items if more than one item was selected)_ selected at step 3 is not selected

**Expected behavior**
Selecting items in a ListBox works the same way as without virtualization.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.0-rc1.1

**Comment by timunie** [comment]
@reejk can you double-check with latest nightly if the issue is solved?

**Comment by reejk** [comment]
Can't reproduce on 11.0.999-cibuild0036924-beta
