### ISSUE TITLE
When using AutoCompleteBox, it freeze when inputting anything with a large amount of data.

### ISSUE THREAD

**Issue by jim-jiang-github** [AvaloniaUI/Avalonia#11867]
**Describe the bug**
When using AutoCompleteBox, it freeze when inputting anything with a large amount of data.

**To Reproduce**

https://github.com/AvaloniaUI/Avalonia/assets/29189410/72c358d8-ee17-4fbd-a76f-0b687e2e5906

**Expected behavior**
No freeze

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [preview4]

**Additional context**

**Comment by timunie** [comment]
Is that 11.0 preview4? If yes, it's too outdated to investigate. Please use at minimum RC1 or even better latest nightly.

**Comment by maxkatz6** [comment]
Also, how is this control used?
If you use ValueMemberBinding, it might noticeably slow down your app on huge data sets, as binding needs to be executed on each item.
Instead, you can use TextSelector and ItemSelector delegates with custom logic from your view model.

**Comment by jim-jiang-github** [comment]
> 那是 11.0 预览版4吗？如果是，它太过时了，无法调查。请至少使用RC1甚至更好的每晚。

Can also reproduce on RC2.2

**Comment by jim-jiang-github** [comment]
> Is that 11.0 preview4? If yes, it's too outdated to investigate. Please use at minimum RC1 or even better latest nightly.

Can also reproduce on RC2.2

**Comment by jim-jiang-github** [comment]
> Also, how is this control used? If you use ValueMemberBinding, it might noticeably slow down your app on huge data sets, as binding needs to be executed on each item. Instead, you can use TextSelector and ItemSelector delegates with custom logic from your view model.

It just a Simple code, Let AutoCompleteBox.ItemsSource binding a large data and input something like comment video

![image](https://github.com/AvaloniaUI/Avalonia/assets/29189410/8faeccb1-06e5-4dba-8d77-007e67ae7491)

**Comment by timunie** [comment]
What does that behavior do? Does it cycle over each item probably via reflection? Please provide a complete, minimal sample to test. 

Thank you.

**Comment by jim-jiang-github** [comment]
> What does that behavior do? Does it cycle over each item probably via reflection? Please provide a complete, minimal sample to test.
> 
> Thank you.

[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/11936909/AvaloniaApplication1.zip)

The key problem is   FilterMode="Contains", If not set FilterMode It work well.
```
 <AutoCompleteBox
        Width="200"
        FilterMode="Contains"
        ItemsSource="{Binding Items}" />
```

**Comment by timunie** [comment]
I think you may want to look into AsyncPopulator as this can be cancelled when typing more text. Don't know if Avalonia can cancel the filtering when user types more text.

**Comment by timunie** [comment]
@jim-jiang-github can you try to test my PR https://github.com/AvaloniaUI/Avalonia/pull/12338#issuecomment-1651928160 ?
