### ISSUE TITLE
Slider clamps bound value to default min max value when removed from visual tree

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#11870]
**Describe the bug**
A slider or any RangeBase control with Value, Minimum and Maximum bound writes a value back to the binding clamped to the default (0 ,100) rather than the bound min max.

**To Reproduce**
Run the repro and click flip  twice, The slider will change value when it should not

[RangeBaseRepro.zip](https://github.com/AvaloniaUI/Avalonia/files/11847437/RangeBaseRepro.zip)

**Expected behavior**
The view model should maintain the requested value.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.999-cibuild0036924-beta

**Comment by timunie** [comment]
Here is a falling test for this 

```cs
[Fact]
public void ChangingDataContextShouldNotChangeOldDataContext()
{
    var viewModel = new RangeTestViewModel()
    {
        Minimum = -5000, 
        Maximum = 5000, 
        Value = 4000
    };
    
    var target = new TestRange
    {
        [!RangeBase.MinimumProperty] = new Binding(nameof(viewModel.Minimum)),
        [!RangeBase.MaximumProperty] = new Binding(nameof(viewModel.Maximum)),
        [!RangeBase.MaximumProperty] = new Binding(nameof(viewModel.Value)),
    };
    
    var root = new TestRoot(target);
    target.DataContext = viewModel;
    target.DataContext = null;
    
    Assert.Equal(4000, target.Value);
    Assert.Equal(-5000, target.Minimum);
    Assert.Equal(5000, target.Maximum);
}

private class RangeTestViewModel
{
    public double Minimum { get; set; }
    public double Maximum { get; set; }
    public double Value { get; set; }
}
```

**Comment by ahopper** [comment]
Your test seems to set Maximum Property twice rather than value.
btw this is a recent regression/issue

**Comment by X9VoiD** [comment]
This bug also happens when binding to a nested viewmodel (or any observable object/property) that is set later.

```xml
<AnyRangeBase Value="{Binding NestedViewModel.Value}"/>
```

> xaml above is just to clarify what I meant with nested view model.

**Comment by mightypanda** [comment]
This bug is driving me mad, i get a "100" set value in when, for example, deselecting an element where a Slider was present.
How can i fix it?
