### ISSUE TITLE
Documentation problems and support

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#11874]
I appreciate your interest in developing with the new Avalonia version RC11. It would be helpful to have access to documentation that provides information on working with the latest release and any breaking changes.

While I understand that updating documentation takes time, it would be great to know where I can find information about the breaking changes in Avalonia RC11. I noticed that there was previously a guide called "Avalonia 11 Porting Guide" available at https://github.com/AvaloniaUI/Avalonia/wiki/Avalonia-11-Porting-Guide. However, it seems to have been removed.

In order to understand the changes and any affected APIs, it would be beneficial to have access to the necessary information. I kindly request assistance in obtaining any available resources or documentation that can provide insights into the breaking changes in Avalonia RC11.

Additionally, if there are alternative sources or community forums where I can find information about the breaking changes, I would greatly appreciate being directed to those as well.

Thank you for your understanding, and I look forward to any assistance you can provide.

**Comment by jmacato** [comment]
Apologies for the inconvenience, we have just restored the old wiki and that link should work now.

**Comment by MikeCodesDotNET** [comment]
We're still working on the v11 docs portal, but you can get a sneak [peek here](https://zealous-desert-09e073403.3.azurestaticapps.net/docs/next/stay-up-to-date/upgrade-from-0.10)
