### ISSUE TITLE
Incorrect behaviour of CTRL+Backspace hotkey in TextBox

### ISSUE THREAD

**Issue by ImoutoChan** [AvaloniaUI/Avalonia#1188]
Tested on windows 10 with avalonia 0.5.0 and 0.5.2-build3963-alpha on core project created by Avalonia for Visual Studio extension.

![9ff2b3ab-3def-403a-803b-dc5b1242212e](https://user-images.githubusercontent.com/14975965/31178878-01a28c74-a923-11e7-98f6-8bf977ea4810.GIF)

[AvaloniaCoreBackspaceProblemApp.zip](https://github.com/AvaloniaUI/Avalonia/files/1355996/AvaloniaCoreBackspaceProblemApp.zip)

**Comment by MonkAlex** [comment]
#1073
