### ISSUE TITLE
Propagate `WindowBase` `MinWidth` and `MinHeight` to `IWindowBaseImpl

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#1191]
We are getting black margins otherwise.

![default](https://user-images.githubusercontent.com/1067584/31234326-4a7faf1a-a9f7-11e7-8008-c53c0590f4a6.png)

**Comment by kekekeks** [comment]
On win32 that causes flicker, apparently.

**Comment by Woldemar89** [comment]
This issue also relates to `MaxWidth` and `MaxHeight` properties. 
We need to think what else properties may relate to this flickering issue too.

**Comment by kekekeks** [comment]
Flicker/black border are caused by our layout system that respects Min/Max Width/Height when actual window size does not match those constraints.

**Comment by Sorien** [comment]
partially, missing features/bugs have own tickets #1562 #1563 so this one can be closed
