### ISSUE TITLE
Nightly Build feed not working

### ISSUE THREAD

**Issue by Eugenenoble2005** [AvaloniaUI/Avalonia#11919]
I dont know if i'm the only one going throught this but i havent been able to get the package feed for PRs working.  I've added the following to visual studio's package source:
https://nuget-feed-all.avaloniaui.net/v3/index.json
https://nuget-feed-nightly.avaloniaui.net/v3/index.json
And none of them have returned any packages. I'm trying to use a nightly build since the visual studio previewer is apparently broken in RC1

**Comment by timunie** [comment]
Have you checked the preview checkmark in nuget package manager?

**Comment by robloo** [comment]
Had the same issue a few days ago. Ended up switching to the All feed and just using packages from specific PRs.

**Comment by Eugenenoble2005** [comment]
> Have you checked the preview checkmark in nuget package manager?

Oh my bad LOLL, recently reinstalled Visual studio and completetly forgot i had to turn on prerelease filter. Thanks a bunch!
