### ISSUE TITLE
Separator of DataGridColumnHeader will clipped by header bound.

### ISSUE THREAD

**Issue by Flithor** [AvaloniaUI/Avalonia#11938]
**Describe the bug**
Separator of `DataGridColumnHeader` will clipped by header bound.

**Screenshots**
Issue:
![image](https://github.com/AvaloniaUI/Avalonia/assets/23412916/51d2179d-6360-4125-b926-d338ac9443c4)
Fixed:
![image](https://github.com/AvaloniaUI/Avalonia/assets/23412916/e2157bd4-7e64-427c-b851-8a7bf8a7cfda)

Because of the `Grid` in auto size will fit for content. But in shown code, the `Path` named `SortIcon` docked column has setted `MinWidth`, it caused Grid also implicitly has a minimum width. Then the outer panel all implicitly has a minimum width. And `VerticalSeparator` put right column of this column, so it will be clipped by the header container panel.  
But `StackPanel` will not fit content size, but content fit the `StackPanel` size. If put this `Grid` into `StackPanel`, then the outer panel can ignore the content minimum width.

**Expected behavior**
ColumnHeader separator should display.

**Codes**
Current Code:
https://github.com/AvaloniaUI/Avalonia/blob/81d455762d4b5dc49eab425898afd81ca131b99c/src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml#L173-L192

Fix Code:
```
<StackPanel Margin="{TemplateBinding Padding}"
        HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
        VerticalAlignment="{TemplateBinding VerticalContentAlignment}">
  <Grid>
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="*" />
      <ColumnDefinition Width="Auto" MinWidth="{DynamicResource DataGridSortIconMinWidth}" />
    </Grid.ColumnDefinitions>
  
    <ContentPresenter Content="{TemplateBinding Content}"
                      ContentTemplate="{TemplateBinding ContentTemplate}" />
  
    <Path Name="SortIcon"
          IsVisible="False"
          Grid.Column="1"
          Height="12"
          HorizontalAlignment="Center"
          VerticalAlignment="Center"
          Fill="{TemplateBinding Foreground}"
          Stretch="Uniform" />
  </Grid>
</StackPanel>
```

**Comment by timunie** [comment]
@Flithor can you file a PR with your fix? I wonder if `Panel` instead of `StackPanel` can also work?

**Comment by Flithor** [comment]
I'm not work on V0.11. No more time to do this.

**Comment by Flithor** [comment]
> @Flithor can you file a PR with your fix? I wonder if `Panel` instead of `StackPanel` can also work?

So... should I PR a fix? Or any others did this?
