### ISSUE TITLE
`Array` element type ignored by Xaml compiler

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#11946]
The method [`AvaloniaXamlIlLanguageParseIntrinsics.GetElementType`](https://github.com/AvaloniaUI/Avalonia/blob/81d455762d4b5dc49eab425898afd81ca131b99c/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlLanguageParseIntrinsics.cs#L417-L422) only works for `IEnumerable<T>` types. To support arrays too, these lines should be added:

```C#
if (type.IsArray)
{
    return type.ArrayElementType;
}
```

Unfortunately this change won't have an immediate effect due to kekekeks/XamlX/issues/89, which causes `ArrayElementType` to return the wrong value.

However, once both of these bugs are fixed then Avalonia starts to support defining arrays with comma-delimited strings! e.g. `MyIntArray="1,2,3"` or `MyDockArray="Top,Bottom,Top"`. This syntax is something that I wanted to write earlier today, but was unable to.

**To Reproduce**
Add an array property to a control, then try to assign a value to it in XAML. You will receive a compiler error that looks like this:

`Avalonia error AVLN: 0004: XamlX.XamlLoadException: Unable to find suitable setter or adder for property [...] of type [...] for argument netstandard:System.String, available setter parameter lists are:`

**Expected behavior**
Arrays can be defined in XAML with comma-delimited strings, using the same parsing rules as single values of the same type.

**Comment by maxkatz6** [comment]
> However, once both of these bugs are fixed then Avalonia starts to support defining arrays with comma-delimited strings! 

Side note, this syntax is already working at least with other kinds of collections, like IList or AvaloniaList.

**Comment by tomenscape** [comment]
Thanks for the tip. I can confirm that those two types work, but as far as I can tell only those two types and `IReadOnlyList<T>`. If the property is `List<T>`, `ICollection<T>`, or even `IEnumerable<T>` then a compiler error is emitted instead.

**Comment by TomEdwardsEnscape** [comment]
To fix this bug, a change also has to be made to Avalonia. Or does it work already?

**Comment by timunie** [comment]
Would be great if anyone could try using nightly build. 

/cc @TomEdwardsEnscape

**Comment by workgroupengineering** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/13328

**Comment by TomEdwardsEnscape** [comment]
It's not fixed yet, see the PR above.
