### ISSUE TITLE
Stackoverflow exception when binding double type into textbox

### ISSUE THREAD

**Issue by nikminer** [AvaloniaUI/Avalonia#11957]
I am trying to organize the input of user values from the TextBox field to a Double variable for subsequent calculations in the program, however, during an attempt to enter any values into this textbox, it leads to a Stackoverflow exception and the application crashes.

1. Create double type variable
![image](https://github.com/AvaloniaUI/Avalonia/assets/24512363/311c63b1-73ea-4016-89fc-cc875893c8c5)
2. Bind variable to TextBox
![image](https://github.com/AvaloniaUI/Avalonia/assets/24512363/2d8643a3-f9db-44e3-aba3-f45317a33980)
3. Input any value ( '.' or any not number)
4. Getting exception and application crash
![image](https://github.com/AvaloniaUI/Avalonia/assets/24512363/ef61e984-b7d9-4d72-8a10-1326ad07d4b9)

I expect that the TextBox will not allow you to enter values other than numeric ones, or at least it will not crash when you type. Plus, I would like to see the PreviewTextInput wpf event, which allows you to receive and edit the entered values before they are entered into the TextBox.

- OS: Windows 10,
- Version 0.10.21

**Comment by timunie** [comment]
Why don't you use a numeric up down? You can hide the buttons if they are not for you.

**Comment by nikminer** [comment]
Because NumericUpDown processes the values and passes them after the focus has been removed from it. And my interface is very simple, one input field and one button, so the user enters a value and wants to click next to enter values, he will press it and won't even notice, because NumericUpDown will not pass the value to the variable and data validation in the ViewModel will not work and the command will be executed.  

There is no processing based on the PreviewTextInput event that could save it from all this.

**Comment by timunie** [comment]
I can't reproduce on my end. Please provide a very minimal sample to check. I feel like you try to handle invalid values somehow and this gets into an infinite loop.

**Comment by nikminer** [comment]
[MinimalSimpleApp.zip](https://github.com/AvaloniaUI/Avalonia/files/11906238/MinimalSimpleApp.zip)

**Comment by timunie** [comment]
I managed to make it run.

1. Specify DataType for DataTemplate. This is pretty much needed!
2. move inner partial class to a new file in order to not confuse source gen.
