### ISSUE TITLE
`ICompositionImportedGpuImage.ImportCompeted` should be called `ImportCompleted`

### ISSUE THREAD

**Issue by jgcodes2020** [AvaloniaUI/Avalonia#11960]
**Describe the bug**
Here is the interface `ICompositionImportedGpuImage`:

https://github.com/AvaloniaUI/Avalonia/blob/81d455762d4b5dc49eab425898afd81ca131b99c/src/Avalonia.Base/Rendering/Composition/CompositionExternalMemory.cs#L87-L99

The member `ImportCompeted` should be called `ImportCompleted`.

**To Reproduce**
See the above source code.

**Expected behavior**
The member `ImportCompeted` should be called `ImportCompleted`.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Linux (ArcoLinux), KDE/Wayland
- Version 11.0.0-rc1.1

**Comment by jgcodes2020** [comment]
I am willing to submit the PR to fix this.

**Comment by robloo** [comment]
This is classified as a bug IMO and should be fixed for 11.0. I would just open a PR and see where it goes from there.

Considering other breaking changes, and that this is a brand new API, this fix should get merged.

**Comment by maxkatz6** [comment]
Yes, it should be fixed now.

**Comment by robloo** [comment]
@jgcodes2020 I went ahead and created the PR to fix this

**Comment by maxkatz6** [comment]
Since this fix wasn't included in the 11.0 release, it should be fixed again without removing mistyped member. It should be hidden/obsoleted without actually breaking compatibility as some apps and libraries might already use it.

**Comment by hez2010** [comment]
I searched the entire GitHub using ImportCompeted, seems that currently no one is using it except Avalonia and its fork: https://github.com/search?q=ImportCompeted&type=code
My suggestion is to fix it now before people actually start to use it, and a release 11.0.1 ASAP.

**Comment by kekekeks** [comment]
>I searched the entire GitHub using ImportCompeted, seems that currently no one is using it

That doesn't matter, unfortunately. Once 11.0.0 API contract is published it can not be broken.

**Comment by kekekeks** [comment]
Should have marked `ICompositionGpuInterop` and `ICompositionGpuImportedObject` as `[NotClientImplementable]`. Not sure if it's still too late since those aren't supposed to be provided by anything but compositor. @maxkatz6

**Comment by jgcodes2020** [comment]
@kekekeks is it OK if I obsolete `ImportCompeted`?

**Comment by kekekeks** [comment]
sure
