### ISSUE TITLE
[RFE] Finer control over the creation of shared OpenGL contexts

### ISSUE THREAD

**Issue by jgcodes2020** [AvaloniaUI/Avalonia#11977]
**Is your feature request related to a problem? Please describe.**
I was working on integrating a library's OpenGL rendering into Avalonia. When creating a shared context via `IOpenGlTextureSharingRenderInterfaceContextFeature`, the only attribute of the context that can be controlled is the OpenGL version (and whether it is ES or not). 

**Describe the solution you'd like**
### Option 1
OpenGL context creation methods should provide options for the following:
- Multisample anti-aliasing (additional parameter to `CreateSharedContext`)
- Core/Compatibility OpenGL profiles (this can be added to `GlVersion`)

### Option 2
Provide a method to expose the native OpenGL context objects and their underlying APIs (`HGLRC` on Windows, `EGLContext` on Linux, etc.) so that I can create my contexts via those APIs.
```c#
public enum OpenGlContextApi {
  Wgl,
  Egl,
  Glx,
  // etc.
}
public interface IOpenGlTextureSharingRenderInterfaceContextFeature {
  public (OpenGLContextApi api, nint handle) GetUnderlyingContext();
}
```

**Describe alternatives you've considered**
Since interop with Vulkan and D3D are only supported on Windows, the only other alternative is to host an OpenGL window using `NativeControlHost`. Unfortunately I can't layer anything on top of that, and I need to layer something on top of it.

**Comment by jgcodes2020** [comment]
I could potentially PR this, though I'm not sure how to implement the MacOS stuff, since I don't have a Mac to test with.

**Comment by cyraid** [comment]
@maxkatz6 I'm not sure #15598 closes this issue? The code in that PR contains adding a compatibility option, and this Issue is about getting the underlying context?

How can we get the Egl Shared Context (using ANGLE) for example? I can't create multiple shared context's with ANGLE (and I must use ANGLE as the requirement).
