### ISSUE TITLE
Avalonia.BuildServices package does not have any metadata

### ISSUE THREAD

**Issue by VMelnalksnis** [AvaloniaUI/Avalonia#11984]
**Describe the bug**
The `Avalonia.BuildServices` NuGet package does not have any metadata. I guess most information is not really needed, as no one will directly reference it, but license information is needed for dependency analysis. I'm assuming the license and other details are the same as for other packages.

**Expected behavior**
Package metadata is set same as for other packages.

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/7999137/8f963279-fe0f-47e8-962e-60f9e1e546e9)
![image](https://github.com/AvaloniaUI/Avalonia/assets/7999137/ee9acbae-fb58-4d79-9ae6-c7b7395a0341)

**Comment by InTack2** [comment]
When I tried to use it at work, I was told that I couldn't use it because it didn't have a license.
Do you have any plans to describe it?

**Comment by maxkatz6** [comment]
@InTack2 use `<PackageReference Include="Avalonia.BuildServices" Version="0.0.30" />` in your project. It should have complete metadata now.

**Comment by InTack2** [comment]
@maxkatz6 
I didn't expect it to be taken care of so quickly.
Thanks for the response!

**Comment by SOsterbrink** [comment]
Hi, 
I saw your fix, but I wanted to mention, that technically you have to include the license and copyright notice in your package if you release it with an MIT license. 

`The above copyright notice and this permission notice (including the next paragraph) shall be included in all copies or substantial portions of the Software.`

Our license scanner is throwing errors because the package license can't be identified because it's missing required content.

**Comment by maxkatz6** [comment]
I don't think any of our packages has license file included in package, but all of them have `<license type="expression">MIT</license>` in the manifest, which is handled by NuGet client as link to https://licenses.nuget.org/MIT. And https://learn.microsoft.com/en-us/nuget/nuget-org/licenses.nuget.org

**Comment by SOsterbrink** [comment]
I noticed the same. And I'm currently slightly confused why our tooling had a problem with the Avalonia.BuildServices package but not with the other packages.  Your License attribute should be sufficient. 

Sorry to bother you with me being nitpicking.
