### ISSUE TITLE
RC2.1 Unexpected failure of the "AvaloniaStatsTask" task

### ISSUE THREAD

**Issue by flarive** [AvaloniaUI/Avalonia#11993]
Hello,

When i switch my avalonia project from rc1.1 to rc2.1 I have this compilation error :(

Error MSB4018 Unexpected failure of the "AvaloniaStatsTask" task.
System.NotSupportedException: FileStream had to open a device that was not a file. For support of devices such as 'com1:' or 'lpt1:', call CreateFile, then use FileStream constructors that use an OS handle such as IntPtr.
   to Microsoft.Win32.Win32Native.SafeCreateFile(String lpFileName, Int32 dwDesiredAccess, FileShare dwShareMode, SECURITY_ATTRIBUTES securityAttrs, FileMode dwCreationDisposition, Int32 dwFlagsAndAttributes, IntPtr hTemplateFile)
   to System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   to System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   to Avalonia.Telemetry.WinProcUtil.StartBackground(String exe, String cmdline)
   to Avalonia.Telemetry.AvaloniaStatsTask.StartCollector()
   to Avalonia.Telemetry.AvaloniaStatsTask.Execute()
   to Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   to Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() Avalonia.Themes.Neumorphism C:\Users\flari\.nuget\packages\avalonia.buildservices\0.0.27\buildTransitive\Avalonia.BuildServices.targets 9	

What should I do ????

Thanks

Eviral

**Comment by timunie** [comment]
Wait a few hours. We are working hard on a fix. We have one, but needs some tests running.

Thanks for your patience

**Comment by timunie** [comment]
Fix should be available now via RC2.2 Please update and try again.

**Comment by flarive** [comment]
Problem fixed with RC2.2 !
Thanks a lot !
