### ISSUE TITLE
Can not use IClock as now is internal.

### ISSUE THREAD

**Issue by edgarfgp** [AvaloniaUI/Avalonia#11996]
As shown below. Creating animation in the code-behind is creating an `AnimationController` and providing our own `Clock` like https://github.com/AvaloniaUI/Avalonia/blob/42fd63ecadfb12c069f7c0948d1afbb8e0cadeb9/tests/Avalonia.Base.UnitTests/Animation/TestClock.cs

Would it make sense to have it back to public ? 

I have been playing with code-behind animation here https://github.com/wieslawsoltes/Animator

_Originally posted by @wieslawsoltes in https://github.com/AvaloniaUI/Avalonia/discussions/7707#discussioncomment-2249546_

**Comment by kekekeks** [comment]
Clocks are planned to be removed completely

**Comment by jmacato** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TopLevel.cs#L543

This is the better analog for the old IClock API now

**Comment by edgarfgp** [comment]
Thanks for the explanation 👍🏻. Will try the new API

**Comment by chenjing1294** [comment]
> Thanks for the explanation 👍🏻. Will try the new API

Hi, how to use avaloniaui RequestAnimationFrame?
```C#
Clock clock = new Clock();
var animation = new Avalonia.Animation.Animation()
{
    Duration = TimeSpan.FromSeconds(0.4),
    Children =
    {
        keyframe1,
        keyframe2,
        keyframe3
    },
    PlaybackDirection = PlaybackDirection.Normal
};

var animationRun = animation.RunAsync(this, clock);
```

**Comment by timunie** [comment]
@chenjing1294 better not answer closes issues. Better open a new Q&A in Discussions.


Hope this helps: https://docs.avaloniaui.net/docs/next/concepts/toplevel#requestanimationframe
