### ISSUE TITLE
How do I go about adding a new form/page?

### ISSUE THREAD

**Issue by blahlicus** [AvaloniaUI/Avalonia#1200]
I am attempting to transition to Avalonia from Eto.Forms but understandably there's currently a lack of documentation since Avalonia is in alpha, so I'm unsure if below is expected behaviour.

I was attempting to add a new form/page by doing right-click+add new item but there's nothing under the Avalonia selection:
![screenshot](https://imgur.com/fZ0dhho.png)

Is this expected behaviour? If so, how am I supposed to add new .xaml pages?

**Comment by grokys** [comment]
Hmm, that is strange - the dialog shows entries on my machine:

![image](https://user-images.githubusercontent.com/1775141/31310232-9c1187f6-ab94-11e7-95ff-55dee2bcbc13.png)

What version of the Avalonia for Visual Studio extension do you have installed?

**Comment by blahlicus** [comment]
I just installed it a couple of hours ago, I have 0.5.0.2 installed as the VS extension.

The solution is running 0.5.0 of the NuGet packages (Avalonia and Avalonia.Desktop)

VS edition is VS2017 community.

**Comment by grokys** [comment]
This should have been fixed - I can't remember the exact problem but it was something to do with GUIDs.
