### ISSUE TITLE
NativeControlHost not working on Windows x64 (Windows ARM64 works fine)

### ISSUE THREAD

**Issue by StefanKoell** [AvaloniaUI/Avalonia#12012]
**Describe the bug**
When using a NativeControlHost control in a view, the view is not shown/displayed when running/compiling against x64 while it is working fine when running/compiling agains ARM64.

**To Reproduce**

1. Go to https://github.com/royalapplications/royalapps-community-avalonia
2. Clone reprository
3. Run the Avalonia app 'InteropDemo'
4. Click on Tabs -> Add

This applies to RC1.1 and RC2.2.

**Expected behavior**
A new tab should appear hosting a WinForms control. Running the same app on ARM64 works just fine.

**Desktop (please complete the following information):**

- OS: Windows 11 
- Version 22H2 (22621.1928)
- I'm using Rider 2023.1.3

**Additional context**
From what I can see using the Debugger, the OnAttachedToVisualTree in the NativeControlHost is never invoked on x64 Platform. There is no error, exception or any helpful debug output from what I can tell.

**Comment by tomenscape** [comment]
We also have a `NativeControlHost`, but it works just fine in RC2.2. Not sure what's going wrong here. I tried creating a non-generic child type and inserting that, but the issue persisted.

If I click the "Add" button in your demo application and then afterwards resize the window, I get this exception:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to create child window for native control host. Application manifest with supported OS list might be required.
  Source=Avalonia.Win32
  StackTrace:
   at Avalonia.Win32.Win32NativeControlHost.DumbWindow..ctor(Boolean layered, Nullable`1 parent)
   at Avalonia.Win32.Win32NativeControlHost.CreateNewAttachment(Func`2 create)
   at Avalonia.Controls.NativeControlHost.UpdateHost()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore()
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
```

Could just be a symptom of `CreateNativeControlCore` not being called, though.

**Comment by StefanKoell** [comment]
Hey @tomenscape 

That's actually really helpful. I wasn't aware that I need an app.manifest file (as mentioned here: #8609)

After adding it to my project, all works fine now on x64 and ARM64!

Not sure why I didn't need that on my ARM64 system though but I'm glad I could resolve that.
