### ISSUE TITLE
DataGrid control appears to be broken

### ISSUE THREAD

**Issue by StornZ** [AvaloniaUI/Avalonia#12022]
The DataGrid control isn't appearing in version 11.0.0-rc1.1. 

I created a new user control. 
Added the namespace
xmlns:control="clr-namespace:Avalonia.Controls;assembly=Avalonia.Controls.DataGrid" after including the package Avalonia.Controls.DataGrid.

I added the theme to App.axaml
```
    <Application.Styles>
        <FluentTheme/>
      <StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Fluent.xaml"/>
    </Application.Styles>
```

I have a view model with a public observable collection called Samples and it is filled in the constructor. 

In the user control this is how I am creating the DataGrid:

```
  <UserControl.DataContext>
    <local:DataGridSampleViewModel/>
  </UserControl.DataContext>
  
  <Grid>
    <control:DataGrid ItemsSource="{Binding Samples}" AutoGenerateColumns="False">
    </control:DataGrid>
  </Grid>
```

What has changed that this no longer works?

**Comment by zii-dmg** [comment]
You didn't add columns.
```xaml
<DataGrid ...>
  <DataGrid.Columns>
     <DataGridTextColumn Header="First Name"  Binding="{Binding FirstName}"/>
     <DataGridTextColumn Header="Last Name" Binding="{Binding LastName}" />
  </DataGrid.Columns>
</DataGrid>
```

**Comment by StornZ** [comment]
> You didn't add columns.
> 
> ```
> <DataGrid ...>
>   <DataGrid.Columns>
>      <DataGridTextColumn Header="First Name"  Binding="{Binding FirstName}"/>
>      <DataGridTextColumn Header="Last Name" Binding="{Binding LastName}" />
>   </DataGrid.Columns>
> </DataGrid>
> ```

I should have mentioned that I had also tried AutoGenerateColumns = "True" and that also was not working.

**Comment by StornZ** [comment]
> You didn't add columns.

Hey it seems I've overlooked something in my code. It was one of those small details. It's solved now.
