### ISSUE TITLE
InvalidOperationException:Unable to locate IPlatformGraphicsOpenGlContextFactory

### ISSUE THREAD

**Issue by AhmedZero** [AvaloniaUI/Avalonia#12051]
**Describe the bug**
I just make the control based on OpenGL
it worked in 11.0.0-RC1.1.
but it stopped working in 11.0.0-RC2.2 and 11.0.0

**To Reproduce**

```
[OpenGL]Unable to initialize OpenGL: 'System.InvalidOperationException: Unable to locate 'Avalonia.OpenGL.IPlatformGraphicsOpenGlContextFactory'.
   at Avalonia.LocatorExtensions.GetRequiredService[T](IAvaloniaDependencyResolver resolver) in /_/src/Avalonia.Base/AvaloniaLocator.cs:line 140
```

**Expected behavior**
Render without any problems

**Desktop:**

- OS: Windows
- Version 11.0.0

**Comment by kekekeks** [comment]
@maxkatz6 seems to be broken by this commit: https://github.com/AvaloniaUI/Avalonia/commit/a390f9f50cbf1db5d670b23243ec6328c3e90658#diff-389ceea3d8f7a93304301eeb63774e31101da61f1ba97faceadf9e7bc036ad5cL46-L47
