### ISSUE TITLE
Can't bind Items property from axaml in listbox or itemscontrol

### ISSUE THREAD

**Issue by joomlaidiots** [AvaloniaUI/Avalonia#12061]
**Describe the bug**
Application won't compile when binding Items property via axaml

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**
![Screenshot from 2023-07-05 13-14-36](https://github.com/AvaloniaUI/Avalonia/assets/136251544/2f7a830b-2437-41e1-bd46-68f8cab940e9)

**Comment by maxkatz6** [comment]
See [ItemsControl](https://docs.avaloniaui.net/docs/next/stay-up-to-date/upgrade-from-0.10#ItemsControl) section
