### ISSUE TITLE
[11.0.0] TextBox input broken on Android since RC2

### ISSUE THREAD

**Issue by msneijders** [AvaloniaUI/Avalonia#12067]
**Describe the bug**

Input using device keyboard on a few tested devices (Samsung S21 android 13, Zebra TC21 android 11, Datalogic Skorpio x5 android 10, all using their default keyboards) is broken with digit input (maybe other inputs as well).

For example on the Zebra TC21 this is the result, when typing "1 2 3 4 5":

In the default TextBox character '5' is doubled.
In the password TextBox '3', '4' and '5' are doubled.
Results differ per type of device (the Samsung S21 in password textbox shows "234" as result).

![image](https://github.com/AvaloniaUI/Avalonia/assets/27849065/1b7eda87-cb68-44bd-b421-48d9a74cbf7e)
(label shows content of password textbox)

**To Reproduce**

```xaml
    <StackPanel Margin="20" Spacing="20">
        <TextBox
            x:Name="text"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Center" />
        <TextBox
            x:Name="pass"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Center"
            PasswordChar="*" />

        <TextBlock HorizontalAlignment="Stretch" Text="{Binding #pass.Text}" />
    </StackPanel>
```

- OS: Android
- Version 10, 11 and 13 tested
- - Avalonia 11.0.0 RC2.2 and 11.0.0 -- problem does not exist on RC1 and before (it was a problem back in a preview in november last year)

**Comment by msneijders** [comment]
PS: on the Zebra TC21, disabling "Auto-Correction" in the onscreen keyboard settings seems to fix it. (this was not necessary in previous avalonia versions, and none of the other apps on this devices had this typing behavior in text fields with autocorrect enabled). Testing the other devices now without autocorrect.

**Comment by elargacha** [comment]
Using versions 11.1.0-beta1 and 11.1.0-beta2, this behavior is reproduced again.
Using the same code as indicated at the beginning of the thread, in my case, the first character that is written is repeated once.

https://github.com/AvaloniaUI/Avalonia/assets/143801477/bb90bed2-14fd-40f5-829f-24809b3e7703


I can also add the video where we initially saw that something was happening.

https://github.com/AvaloniaUI/Avalonia/assets/143801477/d8745e00-1e12-467f-874b-c97b474337f7

As also indicated in the thread, disabling predictive text, the behavior is correct.

**Comment by timunie** [comment]
@elargacha answering closed issues is not a good idea. Open a new one filing a minimal sample if applicable

**Comment by elargacha** [comment]
> @elargacha answering closed issues is not a good idea. Open a new one filing a minimal sample if applicable

@timunie, thank you for the notice! I have already opened a new issue 👌
