### ISSUE TITLE
Font Fallbacks not working and Not able to load custom font either

### ISSUE THREAD

**Issue by TheMulhima** [AvaloniaUI/Avalonia#12099]
**Describe the bug**
I'm trying to add Chinese font compatibility in my app but I'm not able to get it to work.
Initially there was a font problem and this was added which changed the default font and also add fall backs.
How it was done can be found here

https://github.com/TheMulhima/Scarab/blob/3821c180b9e838bc68e0cc8b288664e952098495/Scarab/Program.cs#L184-L213

However, if the user doesn't have the primary font installed, the app just crashes instead of trying a fall back font which does exist. 

See https://github.com/TheMulhima/Scarab/issues/53

This is one of the issues I'm having with fonts

The other issue is I tried to add Noto Sans SC as a embedded font in my app (and set it as the primary font family) but whenever I open the app I get the error could not create glyph Typeface. I added the font as avalonia resource and in the configure fonts extension on app builder I added the font but it doesn't work. The code trying to add that is here
https://github.com/TheMulhima/Scarab/commit/ec4c6cd874ac59988b6217435b58e76b72834c13

Fixing either one of these issues would fix the underlying problem that is Chinese font isn't working. Thanks

**Expected behavior**
- Specifying fallback fonts would use the fallback fonts when primary font is not found.
- Embedding the primary font in the app similar to how Avalonia.Fonts.Inter does it should help resolve the couldn't create the Glyph Typeface error 

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0.0.rc-2.2

**Comment by Gillibald** [comment]
Where do you reference `fonts:Noto Sans SC`?

**Comment by TheMulhima** [comment]
After the builder is created, I call [this](https://github.com/TheMulhima/Scarab/blob/ec4c6cd874ac59988b6217435b58e76b72834c13/Scarab/Program.cs#L215) function if the current culture is Chinese. Which then sets the font family to [this](https://github.com/TheMulhima/Scarab/blob/ec4c6cd874ac59988b6217435b58e76b72834c13/Scarab/Program.cs#L25) (whose primary font is noto sans SC) using [this](https://github.com/TheMulhima/Scarab/blob/ec4c6cd874ac59988b6217435b58e76b72834c13/Scarab/Program.cs#L186-L197) code

**Comment by Gillibald** [comment]
FontFamily="fonts:Noto Sans SC#Noto Sans SC"

**Comment by TheMulhima** [comment]
Where should that be added?

**Comment by TheMulhima** [comment]
Adding that like this worked <https://github.com/TheMulhima/Scarab/blob/fc8069e443b283afbb0b1b8e9d4d9cf232cc72a7/Scarab/Program.cs#L26> 
Thank you
