### ISSUE TITLE
Binding error when binding to parent control property value in datatemplate

### ISSUE THREAD

**Issue by KyleC69** [AvaloniaUI/Avalonia#12100]
**Describe the bug**
Receiving binding error binding the width of child textbox to parent border width property
However it does visually show as expected.
Error text is "Avalonia.Controls.Border is not a valid number

**To Reproduce**

`<Border BorderThickness="1" BorderBrush="Blue" Grid.Row="3" Grid.Column="0" Grid.ColumnSpan="2">
                <ItemsControl x:Name="BlockText" ItemsSource="{Binding BlockList}">
                    <ItemsControl.ItemTemplate>
                        <DataTemplate>
                            <Border BorderBrush="Blue" BorderThickness="1" CornerRadius="4" Padding="4">
                                <TextBox Text="{Binding}" Width="{Binding $parent}" Height="{Binding $parent}" />
                            </Border>
                        </DataTemplate>
                    </ItemsControl.ItemTemplate>
                </ItemsControl>
</Border>`

**Expected behavior**
Controls are visually set as expected but errors are still generated for each item in the control

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**
![Screenshot from 2023-07-07 21-58-40](https://github.com/AvaloniaUI/Avalonia/assets/68043041/36f5fa45-111c-47c6-8eaa-afe820b01d7a)

**Comment by rabbitism** [comment]
This is not a bug. 
You should use
```xaml
Width="{Binding $parent.Width}"
```

and actually this is not needed, you should use HorizontalAlignment=Stretch and VerticalAlignment=Stretch to stretch TextBox to fill the entire border.
