### ISSUE TITLE
AvaloniaUI ProgressBar doesn't update using ReactiveUI

### ISSUE THREAD

**Issue by zewa1999** [AvaloniaUI/Avalonia#12116]
**Describe the bug**
Trying to create a simple window with a progress bar and the progress bar... progress doesn't change.

**To Reproduce**
The code below:
**XAML:**

`<StackPanel Orientation="Vertical" Grid.Row="0" HorizontalAlignment="Center" Margin="0,-30,0,60" >

		<Image Source="/Assets/eyes-guard-logo.png" Grid.Row="0" HorizontalAlignment="Center" Width="150" Height="150"/>

		<TextBlock Text="Take more care of your eyes" HorizontalAlignment="Center" Margin="0,-30,0,0"/>

		<TextBlock x:Name="UserText" HorizontalAlignment="Center" Margin="0,-30,0,0"/>

		<ProgressBar Value="{Binding Progress}" Width="600" Height="30" Minimum="0" Maximum="20" Background="Green" IsEnabled="True" />

	</StackPanel>`

And this is the **ViewModel**:

`    public class ViewModelBase : ReactiveObject
    {
    }`

`public class PopupWindowViewModel : ViewModelBase
{
    public PopupWindowViewModel()
    {
        StartProgressBar();
    }

    private void StartProgressBar()
    {
        Observable.Interval(TimeSpan.FromSeconds(1))
            .Take(20)
            .Subscribe(_ =>
            {
                Progress += 1;
            });
    }

    private int _progress = 8;

    public int Progress
    {
        get
        {
            return _progress;
        }
        set
        {
            _progress = value;
            this.RaiseAndSetIfChanged(ref _progress, value);
        }
    }
}`

**Expected behavior**
I want the progress to keep rising, as it should.
When going with the debugger I can see that the set of the property is called as it should and the backing field is changed, but the progress isn't moving.

If I hardcode the progress backing field as a certain value, on the UI it is changed when starting the app, but after it doesn't change at all.
![image](https://github.com/AvaloniaUI/Avalonia/assets/63615069/454b6daf-875f-4378-b46e-dca113827654)

I've tried also changing from ReactiveUI to IPropertyChanged, but it still doesn't work.

- OS: Windows 11
- Version build 22622.1635

Please help

**Comment by maxkatz6** [comment]
Observable.Interval produces actions on the thread pool working as a timer. If you need to update UI components, you need to dispatch these actions on the UI thread. Using ReactiveUI, you need to add `.ObserveOn(RxApp.MainThreadScheduler)`

**Comment by zewa1999** [comment]
@maxkatz6 
Changed to the reactive main scheduler as you said, and it is the same thing, for some reason, even if I understood your answer and now I don't understand why it doesn't work.
`
 Observable.Interval(TimeSpan.FromSeconds(1))
            .ObserveOn(RxApp.MainThreadScheduler)
            .Take(20)
            .Subscribe(_ =>
            {
                Progress += 1;
            });
`

**Comment by timunie** [comment]
@zewa1999 let me be honest, I personally kind of hate the reactive commands as they sometimes just don't do what I want. Nowadays I use `RelayCommand` form the CT-MVVM package. They also provide source generators if needed. https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/relaycommand 
It works side by side with RxUI if needed. 

What is missing probably is the Inverval thing, For this, I use a `DispatcherTimer`.
