### ISSUE TITLE
[11.0.0] BindCommand throw Exception when publish use PublishTrimmed 

### ISSUE THREAD

**Issue by YJammak** [AvaloniaUI/Avalonia#12122]
**Describe the bug**
Using `BindCommand` to bind `Button` and `ReactiveCommand`, and then using `PublishTrimmed` and `PublishSingleFile` when publishing will cause the program to crash.There is no problem using `Command` binding in `Button` of axaml.

**To Reproduce**

1. Use `BindCommand` to bind `Button` and `ReactiveCommand`
2. Set the `PublishTrimmed` and `PublishSingleFile` parameters to `true` when publishing the software
3. Run the exe file
4. Software crash
5. The error log is as follows

[log.txt](https://github.com/AvaloniaUI/Avalonia/files/11998788/log.txt)

**Expected behavior**
The software is running normally

**Desktop**
- OS: Windows 10
- Version 11.0.0

**Comment by maxkatz6** [comment]
It's not an Avalonia bug, assuming it's BindCommand from RxUI.
It does use reflection, meaning you can't get BindCommand work properly with trimming. https://github.com/reactiveui/ReactiveUI/blob/022d778a0f6c299277966d9665fb86c0459c0291/src/ReactiveUI/Bindings/Command/CreatesCommandBindingViaCommandParameter.cs#L20

Uness you root these methods so it can't be trimmed - https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0.
