### ISSUE TITLE
File Explorer Crash

### ISSUE THREAD

**Issue by CoolCoderSuper** [AvaloniaUI/Avalonia#12148]
**Is your feature request related to a problem? Please describe.**
Whenever i drag  an avalonia window on windows 11 file explorer crashes.

**Describe the solution you'd like**
File explorer not to crash

**Describe alternatives you've considered**

**Additional context**
VisualBasic, .NET 7.0, Avalonia 11.0.0

**Comment by CoolCoderSuper** [comment]
Ok will do that tonight

**Comment by CoolCoderSuper** [comment]
[AvaloniaCalculator.zip](https://github.com/AvaloniaUI/Avalonia/files/12034211/AvaloniaCalculator.zip)

https://github.com/AvaloniaUI/Avalonia/assets/76707331/92e96a4a-4501-48c6-89b3-374a114f841b

Faulting application name: explorer.exe, version: 10.0.23493.1000, time stamp: 0xdf7f3ef2
Faulting module name: SnapLayout.dll, version: 723.17012.0.0, time stamp: 0x6490e42e
Exception code: 0xc000027b
Fault offset: 0x00000000000628e2
Faulting process id: 0x0x5BC8
Faulting application start time: 0x0x1D9B51AE44CE454
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\SnapLayout.dll
Report Id: 0a142fca-8e07-4f32-bb5f-52667d1a668e
Faulting package full name: 
Faulting package-relative application ID: 

I am on an insider build so that might have something to do with it.
I'll try updating to the latest build and see if its fixed.

**Comment by maxkatz6** [comment]
Please report this bug to windows insider portal.

**Comment by timunie** [comment]
@CoolCoderSuper thanks for the update 👍
