### ISSUE TITLE
Using TrayIcon.Icons in app.xaml - exit code 139 segmentation fault

### ISSUE THREAD

**Issue by sergevm** [AvaloniaUI/Avalonia#12145]
**Describe the bug**

**To Reproduce**
1. Create a new empty MVVM Avalonia application
2. Paste the following in App.axaml:

`
    <TrayIcon.Icons>
        <TrayIcons>
            <TrayIcon Icon="/Assets/avalonia-logo.ico" ToolTipText="My demo app">
                <NativeMenu.Menu>
                    <NativeMenu>
                        <NativeMenuItem Header="Quit" />
                    </NativeMenu>
                </NativeMenu.Menu>
            </TrayIcon>
        </TrayIcons>
    </TrayIcon.Icons>
`

3. Start the app in debug mode => build succeeds, but doesn't start
4. Start the app without debugger => exit code 139

**Expected behavior**
The application starts

**Screenshots**
-

**Desktop (please complete the following information):**

- OS: MacOS with M1 processor
- Ventura 13.4.1

**Additional context**
I upgraded my OS to Ventura 13.4.1, coming from Monterey, and tried to execute my project after a reboot. 
The issue exists in both v11 rc1 and in v11 GA
Still works just fine on my other machine with Monterey OS. So looks like it may be linked to Ventura with the mentioned version.

**Comment by PentaPinguino** [comment]
I have created a new Avalonia project with the following `App.axaml` and it runs as expected on Windows 10 Pro 22H2.

```
<Application
    x:Class="AvaloniaApplication1.App"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    RequestedThemeVariant="Default">
    <!--  "Default" ThemeVariant follows system theme variant. "Dark" or "Light" are other available options.  -->

    <Application.Styles>
        <FluentTheme />
    </Application.Styles>

    <TrayIcon.Icons>
        <TrayIcons>
            <TrayIcon Icon="/Assets/avalonia-logo.ico" ToolTipText="My demo app">
                <NativeMenu.Menu>
                    <NativeMenu>
                        <NativeMenuItem Header="Quit" />
                    </NativeMenu>
                </NativeMenu.Menu>
            </TrayIcon>
        </TrayIcons>
    </TrayIcon.Icons>
</Application>
```

**Comment by timunie** [comment]
@PentaPinguino fyi: this is a platform specific "bug". So it works on Windows, but not on all linux os as there a tons of different distributions to support. We cannot test / develop all of them on our own.

**Comment by uthidata** [comment]
@maxkatz6 @timunie This is a bug on macOS, not Linux (as stated by the OP). Also I tested on Linux (OpenSUSE) and it doesn't crash. Please relabel it.

**Comment by timunie** [comment]
thx. re-labled it.

**Comment by maxkatz6** [comment]
Going through some issues with NativeMenu, and I cannot reproduce this one on macOS. Let me know, if you have a minimal sample where it's stable.
