### ISSUE TITLE
OnOpenGlInit does not work

### ISSUE THREAD

**Issue by Zhou-Pixel** [AvaloniaUI/Avalonia#12143]
OnOpenGlInit in OpenGlControlBase does not work since avalonia `11.0.0-rc2.2`

env: `.net7` `win11`

**Comment by fengyang86** [comment]
Me too

**Comment by maxkatz6** [comment]
Please add more information, steps to reproduce and minimal repro if possible. This issue is invalid.

**Comment by fengyang86** [comment]
> Please add more information, steps to reproduce and minimal repro if possible. This issue is invalid.

Deubg Output:
" [OpenGL]Unable to initialize OpenGL: 'System.InvalidOperationException: Unable to locate 'Avalonia.OpenGL.IPlatformGraphicsOpenGlContextFactory'." 
AvaloniaVersion:
![image](https://github.com/AvaloniaUI/Avalonia/assets/48636111/001bd3c8-089a-45c4-bd86-37892f0dca86)
OS:
Win11
Program:
![image](https://github.com/AvaloniaUI/Avalonia/assets/48636111/245089f1-3e63-49a1-bd62-3f295d722b00)
OpenGlControl:
![image](https://github.com/AvaloniaUI/Avalonia/assets/48636111/ec4a30c1-8586-45c1-ae0b-f987180c89b4)
MainWindow:
![image](https://github.com/AvaloniaUI/Avalonia/assets/48636111/6629a289-da12-4c8e-9079-e0083b25a2dc)
UseWgl has been remove in this version,I dont know  thre new way to useWgl

**Comment by Zhou-Pixel** [comment]
> d minimal repro if possible. This issue is invalid.

## code:
![image](https://github.com/AvaloniaUI/Avalonia/assets/72525794/780b246b-87fd-4406-b3f7-6fa1b2c40211)

![image](https://github.com/AvaloniaUI/Avalonia/assets/72525794/6d4f3e2a-fd95-43b5-802b-3f0a955af6fa)


## result:
![image](https://github.com/AvaloniaUI/Avalonia/assets/72525794/3f627d57-69b3-4b73-800e-bf904c334c8a)

**Comment by kekekeks** [comment]
It should be already fixed, see https://github.com/AvaloniaUI/Avalonia/pull/12056

**Comment by maxkatz6** [comment]
You can use nightly builds safely, as these won't have breaking changes compared to 11.0.

**Comment by fengyang86** [comment]
> You can use nightly builds safely, as these won't have breaking changes compared to 11.0.

Thanks
