### ISSUE TITLE
Offscreen rendering

### ISSUE THREAD

**Issue by KeKl** [AvaloniaUI/Avalonia#1215]
It would be great to have the opportunity to render the whole scene into an `OffScreenSurface` to use
it as a texture in a 3d app.

**Comment by kekekeks** [comment]
See https://github.com/AvaloniaUI/Avalonia/tree/master/samples/interop/Direct3DInteropSample

**Comment by elad8a** [comment]
@kekekeks as far as I can tell, this sample does not shows how to do offscreen rendering. It merely shows how on can add Direct3D content to an existing screen (window) that uses avalonia. also, this sample seems to be broken. The ImmediateRenderer clears the screen effectively deleteing the rendered content.

**Comment by kekekeks** [comment]
You can also try to use RenderTargetBitmap and cast platform impl to `WicRenderTargetBitmapImpl`. This API is, unfortunately, not stable and is a subject to change.

**Comment by kekekeks** [comment]
One is supposed to implement their own ITopLevelImpl for game engine embedding.
