### ISSUE TITLE
Precompiling failed for my android build  

### ISSUE THREAD

**Issue by tomziegler** [AvaloniaUI/Avalonia#12152]
Here's my error message after trying to build my Avalonia Android project:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Precompiling failed for C:\Users\tomz.opr\source\repos\RoseburgForkliftApp\RoseburgForkliftApp\RoseburgForkliftApp.Android\obj\Release\net7.0-android\android-x86\linked\Markdown.Avalonia.dll with exit code 1.
Failed to load method 0x600004d from 'C:\Users\tomz.opr\source\repos\RoseburgForkliftApp\RoseburgForkliftApp\RoseburgForkliftApp.Android\obj\Release\net7.0-android\android-x86\linked\Markdown.Avalonia.dll' due to Could not resolve type with token 01000060 from typeref (expected class 'Avalonia.Controls.IPanel' in assembly 'Avalonia.Controls, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b') assembly:Avalonia.Controls, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b type:Avalonia.Controls.IPanel member:(null).
Mono Ahead of Time compiler - compiling assembly C:\Users\tomz.opr\source\repos\RoseburgForkliftApp\RoseburgForkliftApp\RoseburgForkliftApp.Android\obj\Release\net7.0-android\android-x86\linked\Markdown.Avalonia.dll
AOTID 3773095F-DAA6-1E30-F00C-36080C93D4AB
Run with MONO_LOG_LEVEL=debug for more information.
AOT of image obj\Release\net7.0-android\android-x86\linked\Markdown.Avalonia.dll failed.	RoseburgForkliftApp.Android	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.46\targets\Microsoft.Android.Sdk.Aot.targets	91	

Anyone know how to fix this? 

Thanks,
Tommy

**Comment by maxkatz6** [comment]
It looks like you have mixed versions of Avalonia. Double check that you don't have any 0.10 or 11-preview dependencies.

**Comment by robloo** [comment]
Yea, you shouldn't be referencing IPanel anymore.

**Comment by tomziegler** [comment]
Yeah its using -preview dependencies by default when I create a new project.  When I try to downgrade by uninstalling the dependencies, and reinstalling  11.0.0 versions of Avalonia, it shows more errors :

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0111	Type 'Window1' already defines a member called 'InitializeComponent' with the same parameter types	RoseburgForkliftApp	C:\Users\tomz.opr\source\repos\RoseburgForkliftApp\RoseburgForkliftApp\RoseburgForkliftApp\Avalonia.NameGenerator\Avalonia.NameGenerator.AvaloniaNameSourceGenerator\RoseburgForkliftApp.Window1.g.cs	19	Active

Maybe I'm doing this the wrong way? 

Thanks.

**Comment by jp2masa** [comment]
Point 3 on [v11 porting guide]:

> Remove the package reference to XamlNameReferenceGenerator - Avalonia now includes an inbuilt generator by default

**Comment by tomziegler** [comment]
Okay , that seemed to fix that issue.  Now there's another bug on the .Android file:

Severity	Code	Description	Project	File	Line	Suppression State
Error	XA4204	Unable to resolve interface type 'Avalonia.Platform.IPlatformNativeSurfaceHandle'. Are you missing an assembly reference?	RoseburgForkliftApp.Android	C:\_\src\Android\Avalonia.Android\Platform\SkiaPlatform\InvalidationAwareSurfaceView.cs	16

**Comment by tomziegler** [comment]
d

**Comment by tomziegler** [comment]
Had to create a new project sadly. and use 11.0.0 references.
