### ISSUE TITLE
Crash in Composition Renderer on MacOS

### ISSUE THREAD

**Issue by mightypanda** [AvaloniaUI/Avalonia#12156]
I have succesfully built my application cross-platform Windows / MacOS on Avalonia.
Everything is smooth, i am making a lot of use of Skia drawing with the immediate context.

I experienced some crashes on MacOS, the problem seems to be in the mainloop of the composition renderer.
Not being able to reproduce it at the moment.
The question is: is there something i can do to catch the exception and just wait next frame?

p.s. Dan suggested to tag you @kekekeks 

Exception:

**System.InvalidOperationException**
Collection was modified; enumeration operation may not execute.

Here is the stacktrace:

/_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositor.cs in void ServerCompositor.NotifyBatchesProcessed() at line 141:35
In App

Assembly:
Avalonia.Base
Version:
11.0.0.0
PublicKeyToken:
c8d484a7012f9a8b
/_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositor.cs in void ServerCompositor.RenderCore() at line 203:9
In App

/_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositor.cs in void ServerCompositor.Render() at line 174:9
In App

/_/src/Avalonia.Base/Media/MediaContext.Compositor.cs in void MediaContext.SyncCommit(Compositor compositor, bool waitFullRender) at line 113:5
In App

/_/src/Avalonia.Native/WindowImplBase.cs in void WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.Paint() at line 228:13
In App

/_/src/Avalonia.Native/Interop.Generated.cs in int __MicroComIAvnWindowBaseEventsVTable.Paint(Void* this) at line 4152:21
In App

/_/src/Avalonia.Native/DispatcherImpl.cs in void DispatcherImpl.RunLoop(CancellationToken token) at line 113:17
In App

/_/src/Avalonia.Base/Threading/DispatcherFrame.cs in void DispatcherFrame.Run(IControlledDispatcherImpl impl) at line 117:17
In App

/_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs in void Dispatcher.PushFrame(DispatcherFrame frame) at line 53:17
In App

/_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs in void Dispatcher.MainLoop(CancellationToken cancellationToken) at line 80:9
In App

/_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs in int ClassicDesktopStyleApplicationLifetime.Start(string[] args) at line 127:13
In App

/_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs in int ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, string[] args, ShutdownMode shutdownMode) at line 220:13
In App

void Program.Main(string[] args)

**Comment by kekekeks** [comment]
From the stack trace it seems that new batches somehow got added and processed during enumeration, so it seems to be some sort of reentrancy.

Notes to self:
1) make sure that batch completions are always scheduled asynchronously
2) prevent (and log) reentrancy in compositor right in the `Render` call
