### ISSUE TITLE
 IME chinese characters disable after editing text

### ISSUE THREAD

**Issue by dianafilazop** [AvaloniaUI/Avalonia#12154]
**Describe the bug**
After edit text block input method doesn't switch to Chinese 

**PRE:** Chinese keyboard is set, Chinese language mode is set

**Steps to reproduce the behavior:**

1. Сreate a text block
2. Enter Chinese characters
3. Enter edit mode 
4. Exit selection
5. Enter the text block
6. Enter characters

**Actual behavior:**
English input method is enabled, does not switch to Chinese via Shift

**Expected behavior:**

Chinese input method remains, it is possible to enter Chinese characters, Shift switch to different input method working

**Expected behavior**

**Screenshots**
[Video_2023_07_03-8.webm](https://github.com/AvaloniaUI/Avalonia/assets/139213257/b301f099-a823-406d-bab8-3cdc4d0d7cce)

**Comment by hez2010** [comment]
Cannot reproduce this issue on ControlCatalog.NetCore. Which Avalonia version are you using?

**Comment by dianafilazop** [comment]
Sorry, incorrect bug, I'll check on controlCatalog and reopen it
