### ISSUE TITLE
API to efficiently draw a visual to an externally provided framebuffer

### ISSUE THREAD

**Issue by navhaxs** [AvaloniaUI/Avalonia#12169]
**Is your feature request related to a problem? Please describe.**
Creating this issue out from this discussion: https://github.com/AvaloniaUI/Avalonia/discussions/11593#discussioncomment-6090317
There are use cases for drawing an Avalonia visual to a framebuffer or exposing as a Skia image, e.g. for graphics applications.

**Describe the solution you'd like**
A way to (somewhat) efficiently draw a visual to an externally provided framebuffer.

In WPF this could be done by RenderTargetBitmap - https://stackoverflow.com/a/5189179
and then something like `targetBitmap.CopyPixels(new Int32Rect(0, 0, xres, yres), bufferPtr, bufferSize, stride);` to copy the pixels into a buffer.

**Describe alternatives you've considered**
Prior to Avalonia 11.0 we could use hacks to extract the SKImage from an Avalonia visual.
e.g. 
```
RenderTargetBitmap rtb = ... init ...;
rtb.Render(this.Child);

IRenderTargetBitmapImpl item = rtb.PlatformImpl.Item;
IDrawingContextImpl drawingContextImpl = item.CreateDrawingContext();
var leaseFeature = drawingContextImpl.GetFeature<ISkiaSharpApiLeaseFeature>();
using var lease = leaseFeature.Lease();
using SKImage skImage = lease.SkSurface.Snapshot();
destinationCanvas.DrawImage(skImage, new SKPoint(0, 0));
```
or in Avalonia 0.x we could simply do
```
ImmediateRenderer.Render(visual, context);
```
As of Avalonia 11.0 these are no longer possible as the interfaces are now internal, and there is no alternative way to structure this.

**Additional context**
Related discussion:
- https://github.com/AvaloniaUI/Avalonia/discussions/10386

Example code which need this functionality and can't be updated to Avalonia 11.0
- https://github.com/Oaz/AvaloniaUI.PrintToPDF/blob/c27d3f052d580c63e49ad241cc0e9143c0694ae5/src/Print.cs#L23
- https://github.com/navhaxs/AvaloniaNDI/blob/d5340a2a1d05a0960b50d302c7f29c128e0e4d64/AvaloniaNDI/NDISendContainer.cs#L577C13-L577C13

**Comment by pixsperdavid** [comment]
I also have need of this for the use case of rendering a UI using Avalonia which is then sent to a USB device.

**Comment by navhaxs** [comment]
If I am understanding correctly, `RenderTargetBitmap.CopyPixels` has been implemented in the latest Avalonia 11.x release (see https://github.com/AvaloniaUI/Avalonia/issues/12329) which I believe actually solves this issue?

I just tried out CopyPixels and it is working in the latest Avalonia 11.0.2 🎉 - for example see
https://github.com/navhaxs/AvaloniaNDI/commit/e6706bd4422308a99ce2817f3ba425f4ade49fb6

@pixsperdavid would I be correct in saying this issue has a resolution?

Been getting my head around Skia and Avalonia, it's been lots of learning 😅 But also very cool being able to start building apps using this awesome framework!

**Comment by pixsperdavid** [comment]
@navhaxs  Looks good, I will test and verify with my use case!

**Comment by navhaxs** [comment]
I also saw `DrawingContextHelper.RenderAsync(...)` was recently added which "Renders Avalonia visual into a SKCanvas instance."

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Skia/Avalonia.Skia/Helpers/DrawingContextHelper.cs#L14

Going to close this issue. Thanks for your awesome work Avalonia team! ❤️
