### ISSUE TITLE
Avalonia.Metadata.DependsOn with AvaloniaProperty

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#12175]
**Describe the bug**
The AvaloniaProperty change notification is not fired when a related property changes.

**To Reproduce**

1. Run this test

```csharp
     [Fact]
        public void SetCurrentValue_Notify_Fired_When_Depend_Property_Changed()
        {
            var target = new Class1();

            target.SetCurrentValue(Class1.ContentProperty, "a");
            target.SetCurrentValue(Class1.ContentTemplateProperty, 0);
            Assert.Equal(2, target.NotifyCount);
        }

        [Fact]
        public void SetValue_Notify_Fired_When_Depend_Property_Changed()
        {
            var target = new Class1();

            target.SetValue(Class1.ContentProperty, "a");
            target.SetValue(Class1.ContentTemplateProperty, 0);
            Assert.Equal(2, target.NotifyCount);
        }
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: **independent**
- Version: **11.0.0**

**Additional context**

Related to #12168 #12158

cc @grokys

**Comment by kekekeks** [comment]
DependsOn only affects the XAML loader, it indicates that certain properties should be processed before others. It has no other effect.

**Comment by kekekeks** [comment]
It is [consistent with WPF](https://learn.microsoft.com/en-us/dotnet/api/system.windows.markup.dependsonattribute?view=windowsdesktop-7.0) where the attribute was even moved to System.Xaml.

**Comment by workgroupengineering** [comment]
Ok then, there is a bug in the following controls:

**ContentControl**

https://github.com/AvaloniaUI/Avalonia/blob/7d10558995ed298c7fd475505b8c9eb077896ba0/src/Avalonia.Controls/ContentControl.cs#L119-L131

ContentChanged is not called if ContentTemplate change.

**SplitView**

https://github.com/AvaloniaUI/Avalonia/blob/7d10558995ed298c7fd475505b8c9eb077896ba0/src/Avalonia.Controls/SplitView/SplitView.cs#L319-L371

When the panel model changes the Penel change is not notified.

Consequently in both cases the Logical Children will not be updated.

I have a memory that DependsOn worked as I described in the past.

**Comment by danielmayost** [comment]
Since I messed with it a bit, maybe you could give a small repro or test?

**Comment by kekekeks** [comment]
>I have a memory that DependsOn worked as I described in the past.

Are you sure it wasn't [the attribute from `PropertyChanged.Fody` with the same name](https://github.com/Fody/PropertyChanged/blob/master/PropertyChanged/DependsOnAttribute.cs)?
