### ISSUE TITLE
Issue building with android

### ISSUE THREAD

**Issue by tomziegler** [AvaloniaUI/Avalonia#12184]
Got an issue when trying to build with android.

Severity Code Description Project File Line Suppression State
Error XA4204 Unable to resolve interface type 'Avalonia.Platform.IPlatformNativeSurfaceHandle'. Are you missing an assembly reference? RoseburgForkliftApp.Android C:_\src\Android\Avalonia.Android\Platform\SkiaPlatform\InvalidationAwareSurfaceView.cs 16
![image](https://github.com/AvaloniaUI/Avalonia/assets/75702366/72850cb5-4d1d-4a23-adec-23e8fb60e2de)

Any idea how to fix?
Thanks.

**Comment by maxkatz6** [comment]
Old preview version of avalonia and unknown file that isn't part of templates.

**Comment by maxkatz6** [comment]
Recommendation - update your templates and recreate project from them.

**Comment by tomziegler** [comment]
Okay, i've installed the Latest Stable version of Avalonia on my android app 11.0.0 .

![image](https://github.com/AvaloniaUI/Avalonia/assets/75702366/4579efe5-69e9-46c8-9a38-5b9c00ff6340)

And now I have a different Error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'AvaloniaSplashActivity<>' could not be found (are you missing a using directive or an assembly reference?)	RoseburgForkliftApp.Android	C:\Users\tomz.opr\source\repos\RoseburgForkliftApp\RoseburgForkliftApp\RoseburgForkliftApp.Android\SplashActivity.cs	12	Active

![image](https://github.com/AvaloniaUI/Avalonia/assets/75702366/b1f4655e-8462-4c40-a7ad-588b1ee89d3a)

**Comment by tomziegler** [comment]
When I create a new project, it defaults to preview

**Comment by maxkatz6** [comment]
You have not updated your templates.
https://github.com/AvaloniaUI/avalonia-dotnet-templates
