### ISSUE TITLE
MainWindow KeyDown event does not fire when running in the browser (WASM)

### ISSUE THREAD

**Issue by roboptics** [AvaloniaUI/Avalonia#12180]
**Bug description**
For a newly created Avaliona project, that includes building for browser (WASM), the MainWindow KeyDown event is not fired when running in the browser. For desktop it works.

**How to reproduce**
1. Create a new project and select desktop and browser modes
2. Subscribe the MainWindow KeyDown event in the Loaded event.
3. Run in browser mode
4. The KeyDown event registered method does not get called

- OS:  Windows 10
- Browser: chrome, firefox
- Version 11.0.0

**Comment by maxkatz6** [comment]
There are no windows in the browser. As you have only singe view lifetime there. So you probably want to have event handling on top-level or mainview possibly.
