### ISSUE TITLE
ScrollViewer with Padding cut content and not scrollable to end

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#12182]
**Describe the bug**
This is a bug that come from various generations of avalonia that presents a big annoyance.
When using `Padding` on a ScrollViewer the content gets padded correctly, but causes a bug on scroll value that won't show all content, this affects H and V scroll.

**To Reproduce**

Without padding (Work fine):

```xml
	<StackPanel>
		<ScrollViewer Height="200"
					  Background="AntiqueWhite"
					  VerticalAlignment="Top">

			<StackPanel Spacing="5">
				<NumericUpDown Value="100"/>
				<NumericUpDown Value="200"/>
				<NumericUpDown Value="300"/>
				<NumericUpDown Value="400"/>
				<NumericUpDown Value="500"/>
				<NumericUpDown Value="600"/>
				<NumericUpDown Value="700"/>
				<NumericUpDown Value="800"/>
				<NumericUpDown Value="900"/>
			</StackPanel>
		</ScrollViewer>

    <TextBlock Text="END" Background="BlueViolet"/>

	</StackPanel>
```

![image](https://github.com/AvaloniaUI/Avalonia/assets/113281/d6ae52a3-00c4-4606-920f-3287e46e3865)

___

With padding=50 (Content is cut and no able to further scroll down)

```xml
	<StackPanel>
		<ScrollViewer Height="200"
                      Background="AntiqueWhite"
                      VerticalAlignment="Top"
                      Padding="50">

			<StackPanel Spacing="5">
				<NumericUpDown Value="100"/>
				<NumericUpDown Value="200"/>
				<NumericUpDown Value="300"/>
				<NumericUpDown Value="400"/>
				<NumericUpDown Value="500"/>
				<NumericUpDown Value="600"/>
				<NumericUpDown Value="700"/>
				<NumericUpDown Value="800"/>
				<NumericUpDown Value="900"/>
			</StackPanel>
		</ScrollViewer>

    <TextBlock Text="END" Background="BlueViolet"/>

	</StackPanel>
```

![image](https://github.com/AvaloniaUI/Avalonia/assets/113281/a99bccd8-ff94-4007-8859-e9b05dcdcd2a)

___

To solve that we must use a child content with a padding or margin and then the scroll is now correct, however that is a bit "hacky" when doing custom controls, also not expected as we would expect that padding works without produce such "bug". It makes Padding property inside the ScrollViewer not usable at all

```xml
<StackPanel>
		<ScrollViewer Height="200"
                      Background="AntiqueWhite"
                      VerticalAlignment="Top">

			<StackPanel Spacing="5" Margin="50">
				<NumericUpDown Value="100"/>
				<NumericUpDown Value="200"/>
				<NumericUpDown Value="300"/>
				<NumericUpDown Value="400"/>
				<NumericUpDown Value="500"/>
				<NumericUpDown Value="600"/>
				<NumericUpDown Value="700"/>
				<NumericUpDown Value="800"/>
				<NumericUpDown Value="900"/>
			</StackPanel>
		</ScrollViewer>

    <TextBlock Text="END" Background="BlueViolet"/>

	</StackPanel>
```

![image](https://github.com/AvaloniaUI/Avalonia/assets/113281/f240406d-c176-49e6-aa6f-4c10e853d8dd)

**Expected behavior**
Padding to work and not cut content/scroll max value

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 0.10 and 11

**Additional Content**

The problem looks like `Padding` affect `Bounds` when it should not, Margin for example do not affect Bounds, I have seen this strange behaviour on other controls like `TextBox` that clips the content by using padding...

![image](https://github.com/AvaloniaUI/Avalonia/assets/113281/ee124d34-1b0f-4d15-9f8b-9abb6dca6865)

To "fix" the scroll view this hacky solution works by editing ScrollContentPresenter.cs @ 485:

```C#
            var padding = Padding;
            if (UseLayoutRounding)
            {
                var scale = LayoutHelper.GetLayoutScale(this);
                padding = LayoutHelper.RoundLayoutThickness(padding, scale, scale);
            }

            Extent = Child!.Bounds.Size.Inflate(childMargin + padding * 2);
```
Still the `Bounds` are incorrectly set and should be fixed to fix all controls from clip using Padding
Over the course while using Avalonia and Padding always got me problems...

**Comment by sn4k3** [comment]
Will the removal of `Span` fix the problem?

**Comment by timunie** [comment]
Yes, I think so. However this cannot be done in a style setter as it is "hard-coded". We may want to swap it out into a style and disable it if the Scroller shouldn't Autohide. I'll try to do it, but can't promise anything rn.

**Comment by sn4k3** [comment]
Saw your PR, I think the problem will continue if we have `AllowAutoHide=true`. I don't fully understand why with AllowAutoHide=true we expect the scrollbars to be on top of content but with AllowAutoHide=false they will be outside the content, more when a single bar can be auto hidden.

Instead, I think the right approach is to let user to opt where bars goes (Top of content) OR (Outside content). This give more control and better logic.

**Comment by timunie** [comment]
@sn4k3 that is what the WinUI style does and it is the desired behavior. I have discussed that earlier with the team and lost that discussion. But you can with my PR adjust this on your own with a very tiny style instead of re-templating everything. So still better solution imo.

**Comment by sn4k3** [comment]
Does the WinUI also suffer from same problem when using the `Padding`?

**Comment by timunie** [comment]
at least the scrollbar renders over the content, see: https://github.com/microsoft/microsoft-ui-xaml/issues/6703#issuecomment-1060916532

Have no idea about padding in WinUI ScrollViewer
