### ISSUE TITLE
DevTools Popup Freeze does not work

### ISSUE THREAD

**Issue by IsaacMarovitz** [AvaloniaUI/Avalonia#12198]
**Describe the bug**
Trying to freeze popups with Ctrl + Alt + F does not correctly freeze pop-ups or menus.

**To Reproduce**
1. Open DevTools
2. Enable popup freeze
3. Open a popup
4. Change window focus, popup will close

**Expected behavior**
Popup remains open

**Desktop:**

- OS: Windows 11 & macOS Sonoma
- Version 11.0.0

**Comment by danielmayost** [comment]
iirc, it never worked, and it's really quite annoying.
