### ISSUE TITLE
TextBox throws exception if `CanCopy` / `CanCut` / `CanPaste` / `CanRedo` / `CanUndo` being modified

### ISSUE THREAD

**Issue by mozesa** [AvaloniaUI/Avalonia#12218]
**Describe the bug**
Any attempt to change the `TextBox`'s `CanCopy` / `CanCut` / `CanPaste` / `CanRedo` / `CanUndo` attributes, causes exception.

```text
Unhandled exception. System.MethodAccessException: Attempt by method 'AvaloniaApplication12.Views.MainWindow.!XamlIlPopulate(System.IServiceProvider, AvaloniaApplication12.Views.MainWindow)' to access method 'Avalonia.Controls.TextBox.set_CanCopy(Boolean)' failed.
```

**To Reproduce**
* Create a `<TextBox CanCopy="True" CanCut="False" CanPaste="False" CanRedo="False" CanUndo="False" Text="Hello World" />`

**Expected behavior**
No exception.

**Desktop (please complete the following information):**

- OS: Windows 10
- Avalonia: v11.0.0

**Comment by kekekeks** [comment]
You have Avalonia package version mismatch somewhere.

**Comment by rabbitism** [comment]
These are not public set properties. You should not try to set it.

**Comment by mozesa** [comment]
Rider suggests them to me without any hassle.

![image](https://github.com/AvaloniaUI/Avalonia/assets/49973426/aafc3057-b736-418d-8e08-34c8b6b63309)

**Comment by maxkatz6** [comment]
These properties still need to be visible, when you need to have OneWayToSource binding (from control to view model, for example).

**Comment by maxkatz6** [comment]
Add to https://github.com/AvaloniaUI/Avalonia/issues/4466
