### ISSUE TITLE
Avalonia Browser is broken on net8.0 (Emscripten 3.1.34)

### ISSUE THREAD

**Issue by fMichaleczek** [AvaloniaUI/Avalonia#12225]
**Describe the bug**
Wasm app is broken when use latest dotnet sdk 8.0 which use Emscripten 3.1.34

**To Reproduce**
1. Install dotnet sdk 8.0.100-preview.6.23330.14
2. Upgrade your wasm projet to net8.0
3. Build.
4. See Error in MSBuild.log
1>wasm-ld : warning : function signature mismatch: time

**Expected behavior**
It works

**Logs**
wasm-ld : warning : function signature mismatch: time
error MSB3073: The command "emcc exited with code 1.

**Desktop:**

- OS: Microsoft Windows 11 (22621)
- SDK : dotnet 8.0.100-preview.6.23330.14
- Avalonia : 11.0

**Additional context**
 
https://github.com/mono/SkiaSharp/issues/2494
https://github.com/mono/SkiaSharp/pull/2495

**Comment by maxkatz6** [comment]
Yes, it's a known skiasharp issue, should be already fixed with the latest skia nightly builds.

**Comment by fMichaleczek** [comment]
@maxkatz6 My Workaround bellow. 
Next dotnet8.0 preview should contain first improvements with a SynchronisationContext in multithreading (it's merged) 
https://github.com/dotnet/runtime/pull/87567#discussion_r1231122246

In Avalonia : 
- update SkiaSharp.props with the latest preview available on nuget (2.88.4-preview.84)
- update HarfBuzzSharp.props with the latest preview available on nuget (2.8.2.4-preview.84)
- recompil

In your Browser App csproj (example here MobileSandbox.Browser)
- update MobileSandbox.Browser csproj to net8.0
- in an Itemgroup, add this to use Emscripten 3.1.34
```
<ItemGroup>
    <NativeFileReference Include="$(SkiaSharpStaticLibraryPath)\3.1.34\st\*.a" />
    <NativeFileReference Include="$(SkiaSharpStaticLibraryPath)\3.1.34\st\*.a" />
<ItemGroup>
```
PS : multithreading compile too but it's not working at end (expected result)
```
<PropertyGroup>
    <WasmEnableThreads>true</WasmEnableThreads>
</PropertyGroup>
<ItemGroup>
    <NativeFileReference Include="$(SkiaSharpStaticLibraryPath)\3.1.34\mt\*.a" />
    <NativeFileReference Include="$(HarfBuzzSharpStaticLibraryPath)\3.1.34\mt\*.a" />
<ItemGroup>
```

18>wasm-ld : error : --shared-memory is disallowed by libHarfBuzzSharp.hb-common.o because it was not compiled with 'atomics' or 'bulk-memory' features.

**Comment by kekekeks** [comment]
You don't need to update Avalonia to use a newer SkiaSharp, you can just add relevant PackageReference entries directly to your project.

**Comment by webprofusion-chrisc** [comment]
Hi, I see this is considered a skiasharp issue, so are we still waiting for someone in another project to do something? I'd really like to publish my app as net8 but it, and I assume any browser target app, fails to compile with undefined symbol warnings if I target net8.

**Comment by timunie** [comment]
We have a WIP PR #12729 . Still need to work out how and when to finally update, as this is a breaking change and 3.0 of SkiaSharp is not released yet

**Comment by curia-damiano** [comment]
Hi I am interested in this issue
