### ISSUE TITLE
ICustomDrawOperation.Render not being called after DrawingContext.Custom call

### ISSUE THREAD

**Issue by Aurumaker72** [AvaloniaUI/Avalonia#12247]
**Describe the bug**
When implementing a custom draw operation via `ICustomDrawOperation`, its `Render` method isn't always invoked when the associated control calls `DrawingContext.Custom`.

**Minimal Issue Reproduction**
```cs
public class SkiaCanvas : UserControl
{
    private class SkiaCallbackRenderOperation : ICustomDrawOperation
    {
        public Action<SKCanvas>? RenderCall;
        public Rect Bounds { get; set; }

        public void Dispose()
        {
        }

        public bool Equals(ICustomDrawOperation? other)
        {
            return false;
        }

        public bool HitTest(Point p)
        {
            return false;
        }

        public void Render(ImmediateDrawingContext context)
        {
            // This method is reached only when resizing the window or opening a menuitem over the control
            // No calls from Render, invoked via custom.Render reach this
            if (!context.TryGetFeature<ISkiaSharpApiLeaseFeature>(out var leaseFeature))
                throw new Exception("SkiaSharp is not supported.");

            using var lease = leaseFeature.Lease();

            RenderCall?.Invoke(lease.SkCanvas);
        }
    }

    public event Action<SkiaRenderEventArgs>? RenderSkia;
    private readonly SkiaCallbackRenderOperation _skiaCallbackRenderOperation;

    public SkiaCanvas()
    {
        _skiaCallbackRenderOperation = new SkiaCallbackRenderOperation
        {
            RenderCall = canvas =>
            {
                RenderSkia?.Invoke(new SkiaRenderEventArgs
                {
                    Sender = this,
                    Canvas = canvas
                });
            }
        };
        ClipToBounds = true;
    }


    public override void Render(DrawingContext context)
    {
        // This method (Render) is called at refresh rate, everything is fine

        _skiaCallbackRenderOperation.Bounds = new Rect(0, 0, DesiredSize.Width, DesiredSize.Height);

        // Jump into SkiaCallbackRenderOperation.Render
        context.Custom(_skiaCallbackRenderOperation);

        Dispatcher.UIThread.InvokeAsync(InvalidateVisual, DispatcherPriority.Background);
    }
}
```

**Expected behavior**
`ICustomDrawOperation.Render` is executed when calling `DrawingContext.Custom`

**Comment by Aurumaker72** [comment]
Care to elaborate and correct my API usage?

**Comment by beto-rodriguez** [comment]
The render method will be called while the control is `Invalid`, Avalonia will call (or invalidate) the method for you when the size changes or the first time the control needs to render, then it is your responsibility to call the `InvalidateVisual();` method to let Avalonia know that that control needs to be redrawn.

**Comment by maxkatz6** [comment]
Your control isn't rendered, as custom draw operation has empty bounds.

>         _skiaCallbackRenderOperation.Bounds = new Rect(0, 0, DesiredSize.Width, DesiredSize.Height);

I suppose you want `new Rect(0, 0, Bounds.Width, Bounds.Height);` here

**Comment by Aurumaker72** [comment]
`DesiredSize` isn't empty, it has correct values.

**Comment by maxkatz6** [comment]
I have run your code locally, and Bounds was not empty. Moreover, Bounds in general is a property you usually need to read when you want to get the current size of the control.
As with any other control, actual bounds of the control depend on the parent panel (Grid, StackPanel, Canvas...they all will allocate size for a child differently) and control properties (Alignment, Min/MaxWidth/Height...)
