### ISSUE TITLE
[DevTools] Pinned Property

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#12242]
**Is your feature request related to a problem? Please describe.**
When debugging with Devtools in some circumstances you need to keep the focus on only a few properties. As it is now if the properties have different names it is necessary to scroll the datagrid to see the value.

**Describe the solution you'd like**
Adding pinned properties like VS Debug Visualizer, which shows the pinned properties at the top of the property list.

**Describe alternatives you've considered**
Problem, where to store pinned properties for restore between debug session?

**Additional context**
none

**Comment by lhsrebel72** [comment]
@maxkatz6  I am currently working on this

**Comment by timunie** [comment]
@lhsrebel72 👍 great, thanks for your contribution. I assigned you to the issue, so everyone should see you're working on it.

**Comment by lhsrebel72** [comment]
Just put in a PR for this. As i described in the request there is one thing I am not happy with that I would like to continue attempting to fix but, it is functional. I will add screenshots here of the two headers and if you guys think it looks fine as it is then that is okay as well.

**Comment by lhsrebel72** [comment]
![pin properties screenshot](https://github.com/AvaloniaUI/Avalonia/assets/24578342/80337692-ca73-432c-9d23-9a259ef8f6da)

**Comment by lhsrebel72** [comment]
I would ideally like only one header so that the pinned properties will have the look of "floating" above the others but, I need to figure out how to bind the column widths together since they are in two seperate data-grids
