### ISSUE TITLE
Will link and download API Buttons get supported soon for the Webassembly?

### ISSUE THREAD

**Issue by RayanFarhat** [AvaloniaUI/Avalonia#12267]
Hey guys, I am working on my project that has a version that run on the web, But my problem is that I need to allow the user to download files from my backend API with a button just like the normal website, But it seem that there is no support for it right now.
Will this feature released soon or at least a feature that allow the button to open new link in the browser. or there is no plan right now?

**Comment by RayanFarhat** [comment]
> 

Yes I am leaving this as the last option

**Comment by maxkatz6** [comment]
"download API" won't be a part of the UI framework. Why would it be? Just use HttpClient. 
HyperlinkButton might be part of the UI framework though, which either opens a link or you process the click.
