### ISSUE TITLE
Touch and Pen input randomly lost after upgrading to Avalonia 11

### ISSUE THREAD

**Issue by Speedberg** [AvaloniaUI/Avalonia#12289]
**Describe the bug**
When using Avalonia 11, touch and pen input is randomly lost after moving a certain distance away from the starting point. This issue does not appear to happen with mouse input.

**To Reproduce**

1. Build and run 'Control Catalog Sample' for Android
2. Goto 'Pointers' page
3. Drag with finger / stylus

**Expected behavior**
The control shouldn't lose capture of the input.

**Screenshots**

https://github.com/AvaloniaUI/Avalonia/assets/49727693/bf829f64-d663-429c-afd1-d2c6e0676924

- OS: Android
- Avalonia Version: 11

**Comment by Flithor** [comment]
May related: in 0.10.21, `Dispatcher.UIThread.MainLoop` caused touch msg lost.

**Comment by emmauss** [comment]
Due to updated gesture and pointer behavior in Avalonia 11, if your control needs to prevent gestures from happening when it handled pointer events, call the `PreventGestureRecognition` method in the pointer event args.
This is available since 11.0.0

**Comment by Speedberg** [comment]
> Due to updated gesture and pointer behavior in Avalonia 11, if your control needs to prevent gestures from happening when it handles pointer events, call the `PreventGestureRecognition` method in the pointer event args. This is available since 11.0.0

Thank you, that has solved the issue :)
