### ISSUE TITLE
Page cannot be re-rendered in Browser

### ISSUE THREAD

**Issue by znoliver** [AvaloniaUI/Avalonia#12298]
**Describe the bug**
When I change my Browser size ， the page cannot be re-rendered

**Screenshots**

**Desktop (please complete the following information):**

![image](https://github.com/AvaloniaUI/Avalonia/assets/59060212/7a8a94c5-7a7e-4325-afaf-f261f1ca96de)
![image](https://github.com/AvaloniaUI/Avalonia/assets/59060212/81b8faea-3ab1-4775-b1a4-d2ad4ff0bf6d)

- OS: Ubuntu 22.04
- Version 11.0
- Browser: Google Chorme/Microsoft Edge

**Comment by timunie** [comment]
Please provide a minimal sample to reproduce.

**Comment by znoliver** [comment]
> Please provide a minimal sample to reproduce.


Here：https://github.com/znoliver/AvaloniaBrowserDemo

**Comment by timunie** [comment]
hm, I think there was something that blocks a wasm from stretching vertically. See https://github.com/dotnet/aspnetcore/issues/10147

Don't know it that's the issue in your case, but I'm not that much experienced in WASM, so I was unable to get it running. 

My idea: 
in AppBundle > app.css add this: 
```css
html, body {
    height: 100%;
    width: 100%;
    padding: 0;
    margin: 0;
}
```

**Comment by znoliver** [comment]
Sorry, my problem is still not solved,is there any other way？

**Comment by timunie** [comment]
running your sample in Desktop-mode I saw the same result. TextBox is inside StackPanel, which never has a fixed height and thus cannot stretch it's children. Use `Grid` or `DockPanel` instead.

**Comment by timunie** [comment]
works for me now in browser and on Desktop

**Comment by znoliver** [comment]
That is invalid，when my browser is maximized, the button is also enlarged and cannot get the mouse focus

**Comment by timunie** [comment]
Have you tried the PR I filed you yesterday?

Note: If you have tried grid, make sure the first row is Auto and the second row is *. Read about different Panels in the docs also.

**Comment by timunie** [comment]
The PR I mentioned: https://github.com/znoliver/AvaloniaBrowserDemo/pull/1

**Comment by znoliver** [comment]
Yes，I merge the PR ,but it is invalid
![image](https://github.com/AvaloniaUI/Avalonia/assets/59060212/f633731a-3e3b-47e6-9350-c892e5619b17)

**Comment by timunie** [comment]
I'm sorry, the body style I wrote above in app.css is not needed at all. Just using Dockpanel was the key to love it. Still during window resize the button can flicker a bit, but that's probably acceptable.

**Comment by timunie** [comment]
I have seen it. Remove what I told you earlier form app.css pls. It was wrong information. 

```diff
- html, body {
-    height: 100%;
-    width: 100%;
-    padding: 0;
-    margin: 0;
- }
```

**Comment by znoliver** [comment]
I've removed that conten，and is there a solution to my problem, is it a bug?

**Comment by maxkatz6** [comment]
Can't reproduce on chrome and mozilla with your sample. Locally it does invalidate visual and rerenders itself.

**Comment by znoliver** [comment]
> Can't reproduce on chrome and mozilla with your sample. Locally it does invalidate visual and rerenders itself.



I find this is a bug，the WASM playground also has the problem,my system is Ubuntu 22.04,Browser is Edge

[录屏 2023年07月26日 11时50分56秒.webm](https://github.com/AvaloniaUI/Avalonia/assets/59060212/c0783662-a88c-4d58-b65c-533bb675e8f9)

**Comment by appel1** [comment]
It looks like it happens with both Edge and Chrome on Windows when rendering play.avaloniaui.net. Changing the browser size sometimes causes Avalonia to get stuck at an incorrect size until the browser is resized again. I can't reproduce it with Firefox. 

<img width="986" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/973314/f9a5ea5c-1e05-43fb-8fa8-1c739a5ed7fb">
