### ISSUE TITLE
Button not visible in Grid when the background of Grid is white

### ISSUE THREAD

**Issue by UPIMMUNITY** [AvaloniaUI/Avalonia#12293]
**Describe the bug**
Same as the title.
I am new to avalonia and following the tutorial listed in the official website which is about building a soundness meter. 

**To Reproduce**
1. Using Rider to create **Avalonia .NET App** with Avalonia 11.0.0
2. Paste the following sample code for `MainWindow`
```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="400" d:DesignHeight="400"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1">

    <Grid ColumnDefinitions="*" Background="White">
        <Button VerticalAlignment="Center" HorizontalAlignment="Center">button</Button>
    </Grid>
</Window>

```
3. Press `F5` to run.

**Screenshots**
Preview offered by avalonia plugin looks fine.
![image](https://github.com/AvaloniaUI/Avalonia/assets/77432836/7b1f56e4-97d3-4659-8e9b-3bcb47220fe7)

But when it actually runs, button is not visible.
![image](https://github.com/AvaloniaUI/Avalonia/assets/77432836/4eda0f18-a0e6-4d8b-8ed5-59b0c4cfee3a)

And if I change the background to other colors, it functions well.
![image](https://github.com/AvaloniaUI/Avalonia/assets/77432836/e6f459d9-d2f5-4e41-a4c0-5420c5bfcafc)

**Desktop (please complete the following information):**

- OS: Windows 10 22H2
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**
By the way, the default foreground of any text is white instead of black. It seems not the same as on macOS? And the default background of any is black?

**Comment by Mrxx99** [comment]
Instead of setting the background of the Grid if you just want to have a light mode app, change the ThemeVariant in App.xaml to "Light". "Default" will use your system settings regarding Dark mode.

**Comment by maxkatz6** [comment]
Yes. It's not a bug.
Previewer uses Light variant always.
Actual app inherits it from the system. In your case you see the app with Dark variant (==white foreground), with forcefully set White background (==white foreground on white background).

See https://docs.avaloniaui.net/docs/next/guides/styles-and-resources/how-to-use-theme-variants for more details
