### ISSUE TITLE
Previous ToolTip not disposed.

### ISSUE THREAD

**Issue by KeKl** [AvaloniaUI/Avalonia#1229]
Following code throws an exception after hovering from the first button to the second (tooltip after tooltip has displayed)

     <Expander Header="Fruits" ExpandDirection="Down">
            <StackPanel>
                <Button ToolTip.Tip="I can be green, red...">
                    Apple
                </Button>
                <Button ToolTip.Tip="Normally I am orange.">
                    Orange
                </Button>
                <Button ToolTip.Tip="Normally I am yellow.">
                    Banana
                </Button>                
            </StackPanel>            
        </Expander>

An unhandled exception of type 'Avalonia.AvaloniaInternalException' occurred in Avalonia.Controls.dll
Additional information: Previous ToolTip not disposed.

**Comment by grokys** [comment]
Which version of Avalonia are using using here?

**Comment by KeKl** [comment]
Version. 0.5.1 Is this already fixed

**Comment by grokys** [comment]
Yes, this should have been fixed by https://github.com/AvaloniaUI/Avalonia/pull/1031.
