### ISSUE TITLE
linux上无边框窗口设置失效

### ISSUE THREAD

**Issue by t115liyanpeng** [AvaloniaUI/Avalonia#12305]
在Windows上设置这三个属性后可以实现无边框窗口
ExtendClientAreaToDecorationsHint="True"
ExtendClientAreaChromeHints="NoChrome"
ExtendClientAreaTitleBarHeightHint="-1"
可是发布到linux上后失效了，我使用的版本是Avalonia 11

**Comment by timunie** [comment]
Not all Linux distos support this. Not an Avalonia bug.

**Comment by t115liyanpeng** [comment]
好的，谢谢 我再试试其他的方法

**Comment by t115liyanpeng** [comment]
我找到问题的原因了，是因为我设置了背景为Transparent，如果改为 背景为画刷同时Opacity="0" 就可以解决我上面的问题，Giao！！！
