### ISSUE TITLE
Exiting avalonia application crashes on MAC OS Ventura 13.4.X

### ISSUE THREAD

**Issue by Ehrode** [AvaloniaUI/Avalonia#12310]
**Describe the bug**
Closing the main window or using app.Shutdown() freeze for ever and requires to manually kill the process on MAC OS Ventura 13.4.X

**To Reproduce**
1. Create an Avalonia app from visual studio exetension template (MVVM or not doesn't matter).
2. Update the app nugget packages to avalonia 11.
3. Run the app on mac.
4. Click on the red close button of the main window.

**Expected behavior**
The app exit without any freeze or crash

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac
- Version; Ventura 13.4.1

**Additional context**

**Comment by kekekeks** [comment]
That's with debugger only, you can ignore safely ignore it until 11.0.1 comes out (fixed in master).

**Comment by timunie** [comment]
@Ehrode if you have time to, you can also try latest nightly and double-check if your issue is fixed. Issue can be closed then.

**Comment by Ehrode** [comment]
The issue seems to still be here on Avalonia 11.0.1.

**Comment by maxkatz6** [comment]
It was fixed
