### ISSUE TITLE
Control.KeyDown event not registering properly on macOS

### ISSUE THREAD

**Issue by IsaacMarovitz** [AvaloniaUI/Avalonia#12312]
**Describe the bug**
Control.KeyDown fails to trigger when non-modifier keys are initially pressed on macOS. Modifier keys like Shift or Cmd are registered immediately, but non-modifier keys must be held in order to trigger the event.

**To Reproduce**
Subscribe to the KeyDown event on macOS, and log the event to Console. Try pressing a non-modifier key; it will not be registered. Try holding a non-modifier key; it will be registered.

**Expected behavior**
Non-modifier keys get immediately registered.

**Desktop**
- OS: macOS Ventura & Sonoma
- Version: 11

**Comment by IsaacMarovitz** [comment]
Worth noting that this is a pretty severe issue for Ryujinx's use case, as we rely on this event for all key inputs.

**Comment by IsaacMarovitz** [comment]
Also worth noting that the result of the TextInput event is correct

**Comment by riperiperi** [comment]
The delayed event for the key down seems to coincide with the appearance of this dialog (for s in the example):

![image](https://github.com/AvaloniaUI/Avalonia/assets/6294155/fdbb8ae8-b0dc-43a6-b858-ce1558c0c59f)

For Ryujinx, this appears at the bottom left corner of the screen. We don't need to select a variant of the key, we just want the raw one.
