### ISSUE TITLE
Flickering of Window while trying to resize less than MinWidth, MinHeight

### ISSUE THREAD

**Issue by Woldemar89** [AvaloniaUI/Avalonia#1232]
VS 2017, Win10.
Default AvaloniaNetCore project.
Reproduced on Debug, Release configs and while running without debugger\vs attaching too.
[AvaloniaCoreApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/1391630/AvaloniaCoreApplication1.zip)
[avalonia_flickering_bug_video.zip](https://github.com/AvaloniaUI/Avalonia/files/1391646/avalonia_flickering_bug_video.zip)

**Comment by kekekeks** [comment]
Duplicates #1191
