### ISSUE TITLE
IRenderer.SceneInvalidated event is no longer available in Avalonia 11

### ISSUE THREAD

**Issue by MikeXAML** [AvaloniaUI/Avalonia#12324]
**IRenderer.SceneInvalidated** event is no more public with the last release. We need a trigger when visual tree has been rendered and its elements are ready for hit test.

**To Reproduce**
1. Build and run the project attached - [Avalonia11_HitTest.zip](https://github.com/AvaloniaUI/Avalonia/files/12161018/Avalonia11_HitTest.zip).
2. Keep clicking on 'Click me' content control and 'Hide' button below it.
3. See the result of hit test in the ListBox below. The most of time **HitTestInside** label is **false**.

We try to hit test an element that just was added to visual tree. In most of cases, it is not visible for hit test. We tried different events (**Control.Loaded**, **Layoutable.LayoutUpdated**), posting an action to **Dispatcher** with different priorities and even subscribing to hidden **CompositingRenderer.SceneInvalidated** event via reflection - a new element is not visible by hit test methods most of time.

**Expected behavior**
In Avalonia 10, we used **IRenderer.SceneInvalidated** event for our scenario - and it always finds the required element. You can check the behavior in the second project attached - [Avalonia10_HitTest.zip](https://github.com/AvaloniaUI/Avalonia/files/12161262/Avalonia10_HitTest.zip). 

**Screenshots**
https://github.com/AvaloniaUI/Avalonia/assets/140514013/f4003b0c-2673-4393-9c32-4f1811feec5d
This is how it works in Avalonia 10.

https://github.com/AvaloniaUI/Avalonia/assets/140514013/fcc1cfa5-ad99-4529-9d2b-6aec62b399bd
And this is behavior in Avalonia 11.

**Desktop:**
- OS: Windows
- Version:  11.0.0

**Additional context**
Our scenario is a custom DataGrid control. When a cell is inactive, it contains minimal lightweight visual tree without user interaction. When a cell is activated, its content is changed to full functional heavy editors and we re-raise mouse pointer events on a new elements. Below is a screencast of this behavior. It actually recorded from WPF, but the idea is the same. And it worked great until Avalonia 11.
https://github.com/AvaloniaUI/Avalonia/assets/140514013/548adc7f-7f77-43e0-b993-b90d12422f8b

Could you please help? Is there any approach for us to get a right place when rendering is finished and available for hit test?

**Comment by timunie** [comment]
Consider to give `TreeDataGrid` a try. It works very performant. Also its open source, so you can see how editing is started.

**Comment by timunie** [comment]
@MikeXAML this works for me: 

```cs
textBox.AttachedToVisualTree += TextBoxOnAttachedToVisualTree;

[...]

private void TextBoxOnAttachedToVisualTree(object? sender, VisualTreeAttachmentEventArgs e)
{
    var textBox = (TextBox)sender!;
    textBox.AttachedToVisualTree -= TextBoxOnAttachedToVisualTree;
    
    Dispatcher.UIThread.Post(() => DoHitTest("TextBox Attached to Visual tree"));
}
```

would this solve your issue?

**Comment by MikeXAML** [comment]
@timunie, thanks for your help. unfortunately, both advices do not solve the issue.

**TreeDataGrid** is in early beta as stated in its [documentation](https://docs.avaloniaui.net/docs/controls/treedatagrid#current-status). So we cannot use it in our project.

The **AttachedToVisualTree** event does not work for me - HitTest result is incorrect in most of cases too. I checked that the event is actually triggered from
`contentControl.Content = textBox;`
so it works in the same way as posting an action to UIThread after setting the content.

**Comment by MikeXAML** [comment]
The issue is resolved. It works via the **CompositionBatch.Rendered** task in version 11.0.5-rc1.
Many thanks to Avalonia team!

**Comment by timunie** [comment]
@MikeXAML thx for cleaning up the issue. Appreciate it.
