### ISSUE TITLE
Shutdown on Linux Framebuffer DRM

### ISSUE THREAD

**Issue by Varmod** [AvaloniaUI/Avalonia#12334]
**Describe the bug**
Shutdown method from IControlledApplicationLifetime doesn't work on LinuxFramebuffer DRM.
After shutdown the app will become unresponsive but the process won't terminate.

**Expected behavior**
Shutdown method will terminate the app and process.

**Desktop (please complete the following information):**
- OS: Linux
- Version 11.0

**Comment by timunie** [comment]
Does it only happen in Debug mode or also in Release mode? Also please try with latest nightly.

**Comment by Varmod** [comment]
It happens both in debug and release mode. I've also tried the latest nightly build and it didn't help.

**Comment by masterworgen** [comment]
I get the same result, after closing the project, it doesn't go back to terminal mode

**Comment by masterworgen** [comment]
Fix it #13677
