### ISSUE TITLE
Upgrade of Portable.Xaml breaks Template loading in some cases

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1234]
![image](https://user-images.githubusercontent.com/4672627/31709533-36bf508c-b3ea-11e7-8b75-e5c9801b0dcc.png)

Repro commit:
https://github.com/VitalElement/AvalonStudio/commit/acabb2d1a8371f5946707eb758c33ccd078c21d2

just compile and run Avalon studio, will throw an exception during launch.

This code runs perfectly fine when running on the previous version

**Comment by danwalmsley** [comment]
Interestingly in XamlObjectWriter where it crashes:

```
// FIXME: this condition needs to be examined. What is known to be prevented are: PositionalParameters, Initialization and Base (the last one sort of indicates there's a lot more).
			else
			{
				if (property.IsUnknown)
					throw new XamlObjectWriterException($"Cannot set unknown member '{property}'");
				if (!property.IsDirective || ReferenceEquals(property, XamlLanguage.Name)) // x:Name requires an object instance
					InitializeObjectIfRequired(false);
			}
```

**Comment by danwalmsley** [comment]
![image](https://user-images.githubusercontent.com/4672627/31709702-a673d7ae-b3ea-11e7-9f43-b945ea04ce1a.png)

**Comment by jkoritzinsky** [comment]
I know what's going on. I'll fix this later today.

**Comment by jkoritzinsky** [comment]
Just noticed this is actually a typo, not a bug on our end.
