### ISSUE TITLE
Windows Task Bar Icon and Task Manager Icon doesn't show at random

### ISSUE THREAD

**Issue by Ehrode** [AvaloniaUI/Avalonia#12343]
**Describe the bug**
Often the app Icon in the windows Task bar and 9 on 10 times the task manager icon doesn't show. Instead a blank file icon is shown.
The Icon is set on my views using

```
 Icon = new WindowIcon(AssetLoader.Open(new Uri($"avares://{Assembly.GetExecutingAssembly().GetName().Name}" +
                $"/Assets/Images/MyIcon.ico")));
```
and on my csproj (to have a task bar and exe icon) using

```
<ApplicationIcon>Assets\Images\MyIcon.ico</ApplicationIcon>
```

What makes me think this is an Avalonia issue and not a windows one is that no other processes seem to have this issue on the task manager.
The issue appears in release mode and debug mode.

**To Reproduce**
I have tried on the Avalonia sample project and it doesn't seems to have this issue. The problem happens on my larger application the uses the whole ReactiveUI stack.
What happen is that I start my app, most of the time that task bar icon works. But if I exit my app without closing the main windows through the UI by task killing it or clicking visual studio stop button, the next time at start the app the icon will be bugged. On the other end, in the task manager, I get the correct Icon I would say 1 time out of 10.
I can just literally close and start my app without touching any single line of code and have different behavior (correct or bugged icon).

**Expected behavior**
The correct Icon is show every time.

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/40527875/21508aed-08c9-4c54-a385-086d31d6f798)

Those 4 differents screen shots has been taken in 4 different execution without touching code or doing anything but closing and starting the app.
Note that you can have the icon correctly displayed in task bar but not in task manager and also the opposite, the two not working isn't correlated.

**Desktop (please complete the following information):**

- OS: Windows 11 10.0.22621 Build 22621
- Version Avalonia 11.0.1

**Comment by Ehrode** [comment]
I figured out by chance that the issue doesn't comes from AvaloniaUI.
I had a native lib that was creating an app shortcut in Windows Start Menu.
The shortcut (which had no Icon) was pointing to my exe and I don't exactly know why but Windows was confused and sometime was using the "bugged shortcut icon" and sometimes the working Icon of the exe.
I recompiled the native lib after removing the shortcut creation code and the problem seams to be gone.
Therefore I close this issue.

**Comment by asural** [comment]
> I figured out by chance that the issue doesn't comes from AvaloniaUI. I had a native lib that was creating an app shortcut in Windows Start Menu. The shortcut (which had no Icon) was pointing to my exe and I don't exactly know why but Windows was confused and sometime was using the "bugged shortcut icon" and sometimes the working Icon of the exe. I recompiled the native lib after removing the shortcut creation code and the problem seams to be gone. Therefore I close this issue.

 think I shouldn’t close this issue. The problem I’m facing is the same as yours: when I create a shortcut, the icon doesn’t display. After creating the installer package with Inno Setup, the icon still doesn’t show. When I delete the shortcut, it still doesn’t display. I also tried copying the code to the installation directory and overwriting it, then deleting the shortcut, but the icon still doesn’t show.
