### ISSUE TITLE
Custom font (*.ttf) weight not working anymore with Avalonia 11

### ISSUE THREAD

**Issue by Fruchtzwerg94** [AvaloniaUI/Avalonia#12342]
**Describe the bug**
After migrating from Avalonia 10 to 11 the font weight is not applied anymore for custom fonts.

**To Reproduce**
- Add a custom font (e.g. [SA Inkspot](http://www.myfont.de/fonts/infos/5621-SA-Inkspot.html)) as resource to project
- Set the font as global font in _App.xaml_
```
<Style Selector="Window">
    <Setter Property="FontFamily" Value="../Assets/Inkspot.ttf#SA Inkspot"/>
</Style>
```
- Use different font weights
```
<StackPanel>
    <TextBlock Text="Hello" FontWeight="Regular"/>
    <TextBlock Text="Hello" FontWeight="Bold"/>
    <TextBlock Text="Hello" FontWeight="UltraBold"/>
</StackPanel>
```

**Expected behavior**
Font weights are applied in Avalonia 11 like in Avalonia 10.

**Screenshots**
Avalonia 10:
![grafik](https://github.com/AvaloniaUI/Avalonia/assets/29866610/6c1c2291-619c-443d-b912-50b072954dd4)

Avalonia 11:
![grafik](https://github.com/AvaloniaUI/Avalonia/assets/29866610/f86d6db1-d005-4559-9316-03dff5543bcd)

**System**
- Windows 10 Desktop
- Avalonia Version 11.0.1

**Sample project**
[Sample.zip](https://github.com/AvaloniaUI/Avalonia/files/12175582/Sample.zip)

**Comment by Gillibald** [comment]
You are only referencing one typeface. Just reference the folder and it should work.

**Comment by Fruchtzwerg94** [comment]
Hi @Gillibald ,
do you mean like `<Setter Property="FontFamily" Value="../Assets/#SA Inkspot"/>`? The effect is unfortunately still the same.

**Comment by Gillibald** [comment]
I think this might have worked via simulating the bold typeface. Are you actually having multiple files for this font?

**Comment by Fruchtzwerg94** [comment]
Unfortunately, there are no other files available.
Is there a major change between Avalonia 10 and Avalonia 11 "simulating" this bold typeface? Any way to enable it again manually?

**Comment by JakubMarecek** [comment]
I have same problem. My ttf doesn't exist with bold version.
