### ISSUE TITLE
Switch mainView on android platform is not work

### ISSUE THREAD

**Issue by zyknow** [AvaloniaUI/Avalonia#12348]
**Describe the bug**

running in android emulator , is Android 11

use this code to switch mainView, them work on desktop,but don't work on android
``` cs
    private void Button_OnClick(object? sender, RoutedEventArgs e)
    {
        if (Application.Current.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
        {
            desktop.MainWindow.Content = new TestView();
        }
        else if (Application.Current.ApplicationLifetime is ISingleViewApplicationLifetime singleViewPlatform)
        {
            singleViewPlatform.MainView = new TestView();
        }
    }
```

**Expected behavior**
android should switch to TestView

**Desktop (please complete the following information):**

- OS: [Windows]
- Version [11.0.1]

**Additional context**

**Comment by zyknow** [comment]
i find other way to change current view on android platform

to changed current view context,this code can work for me
```cs
if (Application.Current.ApplicationLifetime is ISingleViewApplicationLifetime { MainView: UserControl mainView })
            {
                mainView.Content = App.Services.GetService<MainView>();
            }
```

but i don't know this is correct ? or have better code to do this

**Comment by timunie** [comment]
Better to use the MVVM approach here imo: https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src/Avalonia.Samples/Routing/BasicViewLocatorSample

**Comment by maxkatz6** [comment]
You need to setup the initial main view of the application there. Please use any of many approaches with navigation in single view application. @timunie mentioned one, but you also can use anything based on switching ContentControl content or ReactiveUI approaches.
