### ISSUE TITLE
ItemsRepeater InvalidCastException when using the ElementView inside the DataTemplate

### ISSUE THREAD

**Issue by PhilWeisz** [AvaloniaUI/Avalonia#12366]
**InvalidCastException when using:**
```
<ItemsRepeater.ItemTemplate>
    <DataTemplate x:DataType="vm:RepeaterElementViewModel">
        <views:RepeaterElementView DataContext="{Binding}"/>           
    </DataTemplate>
</ItemsRepeater.ItemTemplate>
```

**while this works without issues:**
```
<ItemsRepeater.ItemTemplate>
    <DataTemplate x:DataType="vm:RepeaterElementViewModel">
        <ContentControl x:Name="ContentControl" Content="{Binding}" />
    </DataTemplate>
</ItemsRepeater.ItemTemplate>
```

Despite the InvalidCastException the project builds and displays it correctly,
this wasn't the case in my other project where I tried to open a Window with 
the ElementHost as content.

**To Reproduce**

Clone this concise example specifically created for reproduction:
https://github.com/PhilWeisz/ItemsRepeaterOddDataTemplateBehaviorTest

**Expected behavior**
No issues

**Actual behavior**
InvalidCastException that states `Cannot cast 'ElementHostViewModel' to 'ElementViewModel'`.

(ElementHostViewModel is the ViewModel that contains the ItemsSource/ObservableCollection<ElementViewModel>)

**Screenshots**
![ScreenShot showing the Exception.](https://github.com/PhilWeisz/ItemsRepeaterOddDataTemplateBehaviorTest/blob/master/ExampleImages/InvalidCastException.png)

![ScreenShot showing the relevant Code part.](https://github.com/PhilWeisz/ItemsRepeaterOddDataTemplateBehaviorTest/blob/master/ExampleImages/Code.png)

**Desktop (please complete the following information):**

- OS: Win10
- Version 11.0.0 and 11.0.1

**Comment by timunie** [comment]
the exception can be skipped and is only active if all exceptions are processed. You can resume without an issue. So looks more like an artifact than a bug. 

Additional hint: if you remove `DataContext="{Binding}"` (which isn't needed anyway) the issue should be gone.  

- So closing this issue now -

**Comment by PhilWeisz** [comment]
Perfect! Yes that solves it! 
So I learned: 
Don't use DataContext="{Binding}" in the DataTemplate. 
If you do Avalonia maps it to the ViewModel that is around the ItemsControl!

Thank you!
