### ISSUE TITLE
Exception running Avalonia with NativeAOT in reflection free mode

### ISSUE THREAD

**Issue by trampster** [AvaloniaUI/Avalonia#12373]
**Describe the bug**
When running a bare bones avalonia app (dotnet new avalonia.mvvm) with reflection free mode then the following unhandled exception occurs:

> Unhandled Exception: EETypeRva:0x01C8F9E0: TypeInitialization_Type_NoTypeAvailable
>  ---> EETypeRva:0x01C8F9E0: TypeInitialization_Type_NoTypeAvailable
>  ---> EETypeRva:0x01C8F9E0: TypeInitialization_Type_NoTypeAvailable
>  ---> EETypeRva:0x01C8F9E0: TypeInitialization_Type_NoTypeAvailable
>  ---> EETypeRva:0x01C8F9E0: TypeInitialization_Type_NoTypeAvailable
>  ---> EETypeRva:0x01C8EB40: Reflection_Disabled
>    at Internal.Reflection.RuntimeTypeInfo.GetAttributeFlagsImpl() + 0x36
>    at Avalonia.AvaloniaPropertyExtensions.CanValueAffectRender(AvaloniaProperty) + 0x18
>    at Avalonia.Visual.AffectsRender[T](AvaloniaProperty[]) + 0xf9
>    at Avalonia.Visual..cctor() + 0x4dd
>    at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0xb9
>    Exception_EndOfInnerExceptionStack
>    at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x153
>    at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnNonGCStaticBase(StaticClassConstructionContext*, IntPtr) + 0x9
>    at Avalonia.Visual.AffectsRender[T](AvaloniaProperty[]) + 0x22
>    at Avalonia.Controls.Border..cctor() + 0x2b2
>    at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0xb9
>    Exception_EndOfInnerExceptionStack
>    at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x153
>    at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnGCStaticBase(StaticClassConstructionContext*, Object) + 0x9
>    at Avalonia.Controls.Primitives.TemplatedControl..cctor() + 0x1e
>    at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0xb9
>    Exception_EndOfInnerExceptionStack
>    at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x153
>    at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnGCStaticBase(StaticClassConstructionContext*, Object) + 0x9
>    at Avalonia.Controls.Window..cctor() + 0x4c0
>    at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0xb9
>    Exception_EndOfInnerExceptionStack
>    at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x153
>    at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnGCStaticBase(StaticClassConstructionContext*, Object) + 0x9
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime..cctor() + 0x24
>    at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0xb9
>    Exception_EndOfInnerExceptionStack
>    at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x153
>    at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnNonGCStaticBase(StaticClassConstructionContext*, IntPtr) + 0x9
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime..ctor() + 0x14
>    at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], ShutdownMode) + 0x2d
>    at AvaloniaPlayground!<BaseAddress>+0x1162768

**To Reproduce**

1. Create a new avalonia mvvm project:
`dotnet new avalonia.mvvm`
3. Change to .net7.0 is csproj (not sure if this matter
4. Add the following to the csproj file:
```
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <IlcDisableReflection>true</IlcDisableReflection>
```
5. Build using the following:
`dotnet publish -r linux-x64 -c Release`
6. Try to run:
./bin/Release/net7.0/linux-x64/publish/AvaloniaPlayground
7. Unhandled exception detailed above accurs

**Expected behavior**
I would be amazing if Avalonia could work in reflection free mode as this reduces the deployment size significantly

**Desktop (please complete the following information):**

- OS: linux (ubuntu
- Version 11.0.0

**Additional context**

**Comment by kekekeks** [comment]
> I would be amazing if Avalonia could work in reflection free mode as this reduces the deployment size significantly

According to @MichalStrehovsky that mode is discontinued and no longer significantly affects the binary size, see https://github.com/dotnet/runtime/issues/67193
