### ISSUE TITLE
Leading spaces in TextBlock with fixed-width font are rendered incorrectly

### ISSUE THREAD

**Issue by psobolik** [AvaloniaUI/Avalonia#12370]
**Describe the bug**
In a `TextBlock` that uses a fixed-width font, if the text has leading spaces, the spaces are rendered too wide.

**To Reproduce**
Create a boilerplate app and set the main window to the following:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="avalonia_fun.MainWindow"
        FontFamily="Courier New"
        FontSize="20"
        Title="Avalonia Fun">
    <StackPanel>
        <TextBlock Text="---------1---------2---------3"/>
        <TextBlock Text="123456789012345678901234567890"/>
        <TextBlock Text="Column One"/>
        <TextBlock Text=".Column Two"/>
        <TextBlock Text=" Column Two"/>
        <TextBlock Text="..Column Three"/>
        <TextBlock Text="  Column Three"/>
        <TextBlock Text="...Column Four"/>
        <TextBlock Text="   Column Four"/>
        <TextBlock Text=".......Column Eight"/>
        <TextBlock Text="       Column Eight"/>        
    </StackPanel>
</Window>
```

**Expected behavior**
Lines with leading spaces should have the same width as those with dots.

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/6830839/39a4263f-43aa-40c7-b828-753c41de4c3d)

**Desktop (please complete the following information):**
- OS: Windows 11 & Mac 13.4.1

**Additional context**

**Comment by Gillibald** [comment]
![Screenshot 2023-10-25 135519](https://github.com/AvaloniaUI/Avalonia/assets/5928797/5ac697a0-e74f-4fa7-adb1-3008c132b06c)
Tested with current master
