### ISSUE TITLE
Fcitx5 causes crash due to missing dbus name

### ISSUE THREAD

**Issue by ThereGoesMySanity** [AvaloniaUI/Avalonia#12371]
**Describe the bug**
With Fcitx5 (on my system), the available dbus names are `org.fcitx.Fcitx-0`, `org.fcitx.Fcitx5`, and `org.freedesktop.portal.Fcitx`. 

On version 11.0.1 my application crashes when a text box is rendered with the error 
```
Tmds.DBus.Protocol.DBusException : org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.fcitx.Fcitx': no such name
```

When I change `org.fcitx.Fcitx` on these lines:
https://github.com/AvaloniaUI/Avalonia/blob/9808a441dcde8b3f5865c849baf7ffa50a5246cf/src/Avalonia.FreeDesktop/DBusIme/Fcitx/FcitxX11TextInputMethod.cs#L18
https://github.com/AvaloniaUI/Avalonia/blob/9808a441dcde8b3f5865c849baf7ffa50a5246cf/src/Avalonia.FreeDesktop/DBusIme/Fcitx/FcitxX11TextInputMethod.cs#L22
to `org.fcitx.Fcitx-0`, it works correctly.

**To Reproduce**

Run an application on a Linux system with Fcitx5 installed and try to use a text box.

**Expected behavior**
The application should not crash.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version 11.0.1, commit 9808a44

**Additional context**

**Comment by kekekeks** [comment]
If you look closer, you'll see that it tries multiple dbus names in a try/catch block: https://github.com/AvaloniaUI/Avalonia/blob/9808a441dcde8b3f5865c849baf7ffa50a5246cf/src/Avalonia.FreeDesktop/DBusIme/DBusTextInputMethodBase.cs#L95-L108

So it would eventually find the portal-based version.

**Comment by ThereGoesMySanity** [comment]
The portal version is failing with a different error:
```
Exception thrown: 'Tmds.DBus.Protocol.DBusException' in System.Private.CoreLib.dll: 'org.freedesktop.DBus.Error.ServiceUnknown: The name :1.1655 was not provided by any .service files'
   at Tmds.DBus.Protocol.DBusConnection.<CallMethodAsync>d__41`1.MoveNext()
   at Tmds.DBus.Protocol.Connection.<CallMethodAsync>d__28`1.MoveNext()
   at Avalonia.FreeDesktop.DBusIme.Fcitx.FcitxX11TextInputMethod.<Connect>d__3.MoveNext() in Avalonia/src/Avalonia.FreeDesktop/DBusIme/Fcitx/FcitxX11TextInputMethod.cs:line 34

```

**Comment by ThereGoesMySanity** [comment]
Ignore my previous comment - it looks like only the first dbus name is actually being tried. 

When I change the order of the names so that "org.freedesktop.portal.Fcitx" is first in the list, it works correctly.

**Comment by ThereGoesMySanity** [comment]
Figured it out. Exceptions were causing the for loop to end early.
