### ISSUE TITLE
:nth-child(even) stops working in ListBox after scrolling

### ISSUE THREAD

**Issue by BAndysc** [AvaloniaUI/Avalonia#12381]
**Describe the bug**
:nth-child(even) rule in ListBox seem to stop working after the user starts scrolling. For some reason only the `yellow` rule is applied, whereas the `yellowgreen` rule is ignored.

It looks like the child index is correctly calculated and the bug is somewhere in the style application code?

**To Reproduce**

1. Create a view:
```
  <ListBox ItemsSource="{CompiledBinding Items}">
    <ListBox.Styles>
      <Style Selector="ListBoxItem:nth-child(odd)">
        <Setter Property="Background" Value="Yellow" />
      </Style>
      <Style Selector="ListBoxItem:nth-child(even)">
        <Setter Property="Background" Value="YellowGreen" />
      </Style>
    </ListBox.Styles>
  </ListBox>
```
  
  and a viewmodel:
```
public class ViewModel 
{
    public List<string> Items { get; } = Enumerable.Range(0, 100).Select(x => x.ToString()).ToList();
}
```

2. Start scrolling
3. Notice :even rules stop working

**Screenshots**

https://github.com/AvaloniaUI/Avalonia/assets/5689666/a9520a8a-bd86-4bee-85f9-7e95aa35e81b

**Workaround**
Since the `odd` rule works correctly, it is possible to workaround this bug using following styles:
```
      <Style Selector="ListBoxItem">
        <Setter Property="Background" Value="YellowGreen" />
      </Style>
      <Style Selector="ListBoxItem:nth-child(odd)">
        <Setter Property="Background" Value="Yellow" />
      </Style>
``` 

**Desktop (please complete the following information):**

- OS: macOS
- Version 11.0.1

**Comment by robloo** [comment]
Changing/updating the ItemsSource may also cause it to stop working.
