### ISSUE TITLE
Avalonia application crashed on Linux-Ubuntu when keyboard is pressed

### ISSUE THREAD

**Issue by oritnaf** [AvaloniaUI/Avalonia#12400]
I have a simple GUI application with a textbox.
I use binding to bind the textbox to a string property.
When running my Avalonia application in Linux-Ubuntu, the application crashes when the user tries to enter a text into the textbox.
Actually, it crashes as soon as I press any key on the keyboard. I don't even get to the property's set function. 
When I run the SAME application on Windows, it runs OK and embraces the textbox input as expected.

I use the dotnet 6.0 (on both windows and linux)

I install these libraries: {x11-locale, x11-xkb-utils, libxkbcommon-dev, libevdev-dev}  but it didn't make any difference.
What can be the problem?

**Comment by kekekeks** [comment]
See https://github.com/AvaloniaUI/Avalonia/issues/12049

**Comment by kekekeks** [comment]
Should be fixed in 11.0.2
