### ISSUE TITLE
Parsing/Loading xaml-code during runtime causes exception on physical iOS device

### ISSUE THREAD

**Issue by CoolTortoise877** [AvaloniaUI/Avalonia#12419]
**Describe the bug**
When trying to parse or load xaml-code during the runtime of the app, using the AvaloniaRuntimeXamlLoader class from the Avalonia.Markup.Xaml.Loader nuget package on a physical iOS device, this exception occurs:

**"XamlX.XamlTypeSystemException: 'Unable to resolve type Avalonia.Metadata.TrimSurroundingWhitespaceAttribute'"**

**To Reproduce**
1. Create a new Avalonia C# Project with at least target platform iOS and the "Community Toolkit" design pattern
2. Update your nuget packages for the main project and the iOS project to the current version (11.0.2 at time of writing) 
3. Install the Avalonia.Markup.Xaml.Loader nuget package for your main project (also version 11.0.2 here)
4. Add some logic to your project so you can use the AvaloniaRuntimeXamlLoader.Load function during runtime (I added a button to my MainView and call the function from the MainView code behind in the click event handler)
5. Build the iOS app with the physical iOS device (I used an iPhone 7)
6. Try to load xaml-code during runtime (I pressed the button I implemented in step 4)
7. See error

**Expected behavior**
The AvaloniaRuntimeXamlLoader correctly loads/parses the xaml-code into a view and no exception occurs.

**Screenshots**

My button click event handler:
![image](https://github.com/AvaloniaUI/Avalonia/assets/141222446/5193d3f0-a429-4d72-91a9-3ee118fc47d6)

The exception: 
![image](https://github.com/AvaloniaUI/Avalonia/assets/141222446/312cdd9a-6187-41ae-a6a4-151c8383e22b)

The call stack for the exception: 
![image](https://github.com/AvaloniaUI/Avalonia/assets/141222446/97f4f478-5b83-4407-b1ac-94d31774733d)

**Desktop**
- Windows 11 with VS 2022 17.7 Preview V4, Mac mini 2018 with macOS Ventura 13.5
- tested on iPhone 7 with iOS 15.7.8

**Additional context**
The issue only appears on a physical iOS device. 
iOS simulators, android simulators, physical android devices, desktop and browser all work correctly.

**Comment by CoolTortoise877** [comment]
Is there any update on the status of this particular issue?

**Comment by kekekeks** [comment]
iOS device build is AOT-ed and trimmed, so required types are missing and SRE doesn't work.

Try doing the following:

1) Enable IL interpreter
2) Make sure that all avalonia assemblies are preserved via TrimmerRootAssembly

**Comment by timunie** [comment]
issue is still open, so most likely not fixed yet. But feel free to test lastest nightly if issue is fixed there.

**Comment by CoolTortoise877** [comment]
I've looked into the trimming and how to ensure it doesn't accidentally remove necessary code but I'm not sure I'm doing it right, as the issue still remains. 

I used [this](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming?pivots=dotnet-7-0) as reference on how to utilize the TrimmerRootAssembly.

Could you prove some example code on how this should look?
Also, does this go into the .csproj file of the general avalonia project or the iOS project?

Thank you for your patience.

**Comment by maxkatz6** [comment]
@CoolTortoise877 our XamlPlayground web app that parses XAML in runtime (including in AOT mode) has added everything to the roots https://github.com/AvaloniaUI/XamlPlayground/blob/main/src/XamlPlayground.Wasm/Roots.xml

"Avalonia.Markup.Xaml.Loader" and "Avalonia.Base" are probably the most important here.

Either way, I plan on making Avalonia.Markup.Xaml.Loader assembly trimmable. Hopefully it will work properly.

**Comment by CoolTortoise877** [comment]
I set up a roots.xml in my iOS project, similar to the example you provided, and the xaml parsing seems to work now! 
Thank you for the help!
