### ISSUE TITLE
MenuItem DisplayMemberBinding Bug

### ISSUE THREAD

**Issue by TheBestWorldProgrammer** [AvaloniaUI/Avalonia#12417]
When  we set itemsource and then DisplayMember Binding, the values are output as references to the object.
Windows

![Screenshot_14](https://github.com/AvaloniaUI/Avalonia/assets/61782172/48349176-5bba-40e1-a48c-d2e05dba1f8b)
![Screenshot_15](https://github.com/AvaloniaUI/Avalonia/assets/61782172/c7ed64a1-e9d2-4b2c-8d3f-49885daf31f4)

**Comment by timunie** [comment]
easiest would be to override ToString() in QueueItem as for now. 

In general: please mind the issue template if you think you found an issue.

**Comment by Boschindi** [comment]
I stumbled over some more problems with the `DisplayMemberBinding` property which seems to be related to this issue. It works for displaying the name in newer versions (+1) but other features are not working any more.

```axaml
<ComboBox ItemsSource="{Binding Entries, Mode=OneWay}"
              SelectedItem="{Binding SelectedEntry}"
              DisplayMemberBinding="{Binding Name}"
              PlaceholderText="Select…"
              IsTextSearchEnabled="True">
</ComboBox>
```

Both placeholder and text search are not working this way.

The workaround with `ToString()` works for me. Nevertheless, are there any means to fix this or am I doing something wrong?
