### ISSUE TITLE
Changes to entry point (Program.cs/App.xaml.cs) requirements

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#1242]
Our new previewer needs to get all options from appbuilder, so it requires the type with entry point to have `BuildAvaloniaApp` static method.

Another problem that we need to solve is preloading all assemblies with interesting data (types, markup extensions, styles, etc) before AppBuilder actually starts doing anything. Having to provide them manually is inconvenient, so I propose to write an MSBuild task that will patch the target assembly.

So the entry point class should look somewhat like that:

```csharp

// Actual entry point
static void Main(string[] args) => BuildAvaloniaApp().Start<MainWindow>();

// App configuration, used by the entry point and previewer
static AppBuilder BuildAvaloniaApp()
   => AppBuilder
        .Configure<App>(LoadAvaloniaAssemblies())
        .UsePlatformDetect()
        .UseReactiveUI();

// Will be replaced by the actual code in MSBuild task
static extern List<Assembly> LoadAvaloniaAssemblies();

```

MSBuild task should insert loading code for every assembly that has direct or indirect references to Avalonia *or* referenced using `clr-namespace` from XAML files.

That should solve our issues with AOT platforms and XmlnsNamespace attributes not being loaded in time.

**Comment by jkoritzinsky** [comment]
An alternative we could do is add MSBuild scripts to generate an Rd.xml file or Xamarin equivalent depending on the platform to declare the reflection roots so the linker preserves the data.

**Comment by kekekeks** [comment]
>the linker preserves the data

The problem is that `Assembly.Load` does not work on iOS and assembly metadata won't be loaded in time anyway. The only way to get the list of assemblies is to reference them using `ldtoken` + `Type.GetFromHandle`.

Another problem with non-AOT platforms is that there are several of assemblies in output/publish directory that we don't really need to load, but they still consume RAM and increase application load time. So we still need a separate method for loading them. And that separate method should not rely on external files, so we need to patch CIL image anyway.

**Comment by jkoritzinsky** [comment]
Is there any chance we can patch the C# instead of the IL? I really don't like doing IL patching unless absolutely necessary.

Also, how does Xamarin.Forms deal with this problem?

**Comment by kekekeks** [comment]
>patch the C# 

That would be really rude to people who are using F#/VB/IronPython/IronRuby/Nemerely.

**Comment by jkoritzinsky** [comment]
Good point. We should figure out a way to patch the pdb as well then so we dont break step debugging. I think Mono.Cecil can do that, but I'm not positive.

**Comment by kekekeks** [comment]
>We should figure out a way to patch the pdb

That's the whole point of having
```csharp
static extern List<Assembly> LoadAvaloniaAssemblies();
```

When we replace the method marked as `extern` we don't need to make changes to PDB since that method has no code to begin with.

**Comment by jkoritzinsky** [comment]
Ok. As long as it won't mess up debugging I'm fine with the patching.
Let's change the signature to `static extern IEnumerable<Assembly> LoadAvaloniaAssemblies();` though so we don't have the hard dependency on `List`. That way we can have more control how we implement it.

**Comment by jkoritzinsky** [comment]
So I've been looking through the Xamarin.iOS linker tests and some Xamarin.Forms plugins, and I've come up with a method that should not require code-gen.

Using `assembly.GetReferencedAssemblies` to get `AssemblyName` objects, which with the iOS linker (and other IL linkers) we **can** use `Assembly.Load` as long as the assemblies are compiled into the result (`Assembly.Load` only doesn't work with dynamic loading). So we could use `assembly.GetReferencedAssemblies()` recursively to load assemblies on different platforms and ensure they are preserved on AOT platforms with the linker configuration files.

**Comment by kekekeks** [comment]
>we can use Assembly.Load as long as the assemblies are compiled into the result 

Well, for some reason `Avalonia.Themes.Default.dll` gets linked away even though it's not an SDK assembly. We need an actual assembly reference to make linking work properly.

I've also tried using GetReferencedAssemblies (AssemblyLoadContext, actually, but that's essentially the same thing) and the resulted in 15-20MB RAM consumption increase for our control catalog, so we need to analyze dependencies beforehand.

**Comment by jkoritzinsky** [comment]
> Well, for some reason Avalonia.Themes.Default.dll gets linked away even though it's not an SDK assembly. We need an actual assembly reference to make linking work properly.

That's what the Preserve attribute and the custom linker configuration files are for.

> I've also tried using GetReferencedAssemblies (AssemblyLoadContext, actually, but that's essentially the same thing) and the resulted in 15-20MB RAM consumption increase for our control catalog, so we need to analyze dependencies beforehand.

We could automatically exclude SDK references since we will have the assembly name beforehand. Just exclude anything starting with `System.` and we won't be accidentally pre-loading the whole SDK into memory. It's rare we'll need to avoid loading in non-framework assemblies.

**Comment by kekekeks** [comment]
>That's what the Preserve attribute and the custom linker configuration files are for.

That doesn't work, unfortunately.

>We could automatically exclude SDK references since we will have the assembly name beforehand. 

That won't help with some deep regular (non-sdk) nuget package dependency hierarchies when half of the assemblies aren't actually needed.

**Comment by kekekeks** [comment]
Also we still need to load SDK assemblies *if* they are referenced from XAML.

**Comment by jkoritzinsky** [comment]
Why doesn't the preserve attribute or custom linker config work?

And the only assemblies we should have to patch the IL for would be ones using XmlnsDefinitions the rest we should be able to use with custom linker scripts to keep them from being optimized out.

**Comment by kekekeks** [comment]
>preserve attribute

Because linker doesn't even see the assembly, since it has literally no references.

**Comment by GeorgePlotnikov** [comment]
Hi all, just have faced this issue. Provide you or somebody who will look for a solution working example.

```
        static void Main(string[] args)
        {
            InitializeLogging();
            BuildAvaloniaApp().Start<MainWindow>();
        }

        static AppBuilder BuildAvaloniaApp() => AppBuilder
                .Configure<App>()
                .UsePlatformDetect();

```

**Comment by kekekeks** [comment]
Here is a [working example](https://github.com/AvaloniaUI/AvaloniaVS/blob/master/src/Templates/AvaloniaApplicationTemplate/Program.cs)

**Comment by GeorgePlotnikov** [comment]
@kekekeks look similar to mine 🤣
