### ISSUE TITLE
Homepage has dead link

### ISSUE THREAD

**Issue by Rand-Random** [AvaloniaUI/Avalonia#12426]
dead link
https://docs.avaloniaui.net/misc/wpf

found on https://avaloniaui.net/ in paragrah

> A proven path for WPF app modernization.
> Familiar. Considered a spiritual successor to WPF, Avalonia UI provides a [familiar developer experience](https://docs.avaloniaui.net/misc/wpf) allowing you to leverage years of pre-existing knowledge and investments.

**Comment by ArchLeaders** [comment]
Here's the correct link for anyone looking to patch this: 
https://docs.avaloniaui.net/docs/next/get-started/wpf/

**Comment by MikeCodesDotNET** [comment]
Thanks for letting us know. I've pushed a fix :)
