### ISSUE TITLE
AutoCompleteBox on Android not functional

### ISSUE THREAD

**Issue by msneijders** [AvaloniaUI/Avalonia#12437]
**Describe the bug**
On Android you cannot select an autocomplete suggestion from the popup of the AutoComplete control.

**To Reproduce**

1. Go to 'AutoCompleteBox' in ControlCatalog.Android
2. Click on top left autocompletebox
3. Type 'a', 'l'
4. In popup you get 'Alabama' en 'Alaska'
5. Click on 'Alabama'
6. Popup closes, but state of autocompletebox is not changed to alabama.

**Expected behavior**
Like on desktop, I expect 'Alabama' in the box.

**Screenshots**

https://github.com/AvaloniaUI/Avalonia/assets/27849065/62d69fcd-667b-4c6e-82e5-7bfa54dc5e05

**Notable**
In the 11.0.1 version (.2 not tested) the reproduce steps would produce a NRE, but not since https://github.com/AvaloniaUI/Avalonia/commit/ec21caf7fe0419b2284e34d63cd13da6de9460dc

- OS: Android (tested android 10 and 13)
- Version: latest commit at writing

**Comment by msneijders** [comment]
some analysis:

- AutoCompleteBox.HasFocus() gives false during PointerPressed on the ListBoxItem in the popup. This makes it set IsDropDownOpenProperty to false; this closes the popup and no more PointerReleased on the ListBoxItem, so UpdateSelectionFromPointerEvent is not called in ListBoxItem.OnPointerReleased.

After preventing the IsDropDown to false in AutoCompleteBox.FocusChanged, the selected autocomplete is selected and also to the textbox; but the popup is not getting closed. This is because AutoCompleteBox.OnAdapterSelectionComplete is not called. Because the SelectingItemsControlSelectionAdapter is not receiving a PointerReleased event as this event is set handled by the ListBoxItem.PointerReleased.

Should SelectingItemsControlSelectionAdapter not always do a Commit? even though the ListBoxItem sets the pointerreleased as handled? Or should the AutoCompleteBox close its popup in OnAdapterSelectionChanged?

**Comment by msneijders** [comment]
Trying to fix the `AutoCompleteBox.HasFocus()`, letting it return true if the `FocusedElement` in inside the `DropDownPopup`.

On Android I cannot fix this reliably, because when clicking on an item in the dropdown, inside the `AutoCompleteBox.HasFocus()` the `FocusManager.GetFocusedElement()` returns `null`. It is null because it is explicitly set to `null` in `Avalonia.Android.SoftKeyboardListener.OnGlobalLayout()` (as a response to closing of the soft keyboard?).

I presume `SoftKeyboardListener` sets the focusedelement to null, for the case when the user manually closes the softkeyboard? But in this use case, the keyboard closes because the user sets focus to another control.

This also causes this in `ControlCatalog.Android` app:
- Go to "TextBox"
- Focus to first textboxl this opens softkeyboard
- Click on hamburger menu to try open offcanvas menu -> the button show its being pressed, but canvas menu does not open, softkeyboard does close.
- Click again on hamburger menu, and it does open offcanvas menu
- Now set focus to the 'readonly TextBox'.
- Then click on hamburger menu, and it opens offcanvas with a single click.

I think SoftKeyboardListener should be fixed? Not setting focusedelement to null when focus is shifted to another control? Or OnLostFocus event is not reliable on Android?

**Comment by timunie** [comment]
fixed according to https://github.com/AvaloniaUI/Avalonia/pull/12883#issuecomment-1723251320
