### ISSUE TITLE
Visual tree element detaching and reattaching operations can lead to memory leaks

### ISSUE THREAD

**Issue by liwuqingxin** [AvaloniaUI/Avalonia#12455]
### Scenario
I need to dynamically modify ControlTheme or Style and apply the changes to the existing interface immediately.

In 11.0.0, I can only apply real-time changes to ControlTheme by using reflection to call the `StyledElement.OnControlThemeChanged` and `StyledElement.OnTemplatedParentControlThemeChanged` methods on all elements in the visual tree. Then, I call `StyledElement.InvalidStyles()` to apply Style changes.

I know this is not a robust and good solution. But currently, I have no other way. Then, I encountered a **memory leak** issue.

### Describe the bug
So I modified the approach by breaking down the content of the Window from the visual tree and then putting it back to update the ControlTheme and Style of all elements under this subtree. Unfortunately, this operation also resulted in a memory leak.

I repeated this process 100 times and monitored the memory changes, and found that there were many objects in **Generation 2** that increased during this process, even though I manually executed GC.Collect(), it didn't have any effect.

### The Code To Reproduce
```csharp

// Note that the window should have something as it's content.

public class MainWindow : Window
{
        protected override void OnLoaded(RoutedEventArgs e)
        {
            base.OnLoaded(e);

            var content = this.Content;

            Task.Delay(3000).ContinueWith(t =>
            {
                for (var i = 0; i < 100; i++)
                {
                    Dispatcher.UIThread.Post(() =>
                    {
                        this.Content = null;
                        this.Content = content;
                    });
                    Thread.Sleep(200);
                }
            });
        }
}
```

### Expected behavior
Even without considering the rare and unconventional scenarios described above, frequent detaching and reattaching operations from the visual tree should not lead to the continuous generation of unreleased memory objects.

### Screenshots

![image](https://github.com/AvaloniaUI/Avalonia/assets/20198528/350593e3-2e3e-4203-8858-c3a7534524c2)

![image](https://github.com/AvaloniaUI/Avalonia/assets/20198528/39a9e12e-2365-4df8-985b-1e16c8df39b4)

### Desktop
- OS: Windows 11
- Version 11.0.0.

**Comment by liwuqingxin** [comment]
I created a simple application which could reproduce that problem.

[Avalonia.11.0.0.MemoryLeak.zip](https://github.com/AvaloniaUI/Avalonia/files/12287614/Avalonia.11.0.0.MemoryLeak.zip)

**Comment by timunie** [comment]
@liwuqingxin it's great if you attach a sample. However, I would highly suggest to test it against latest version 11.0.2 or even better latest nightly. There are many fixes already merged, so the issue might have changed.

**Comment by timunie** [comment]
Upd: tried your sample using 11.0.2 and issue seems to be gone. Can you please double-check?

**Comment by liwuqingxin** [comment]
@timunie Ok, I will try it in 11.0.2. Thank you~ : )

**Comment by liwuqingxin** [comment]
@timunie I checked it in 11.0.2. And, it is still there. Am I missing something critical?

![image](https://github.com/AvaloniaUI/Avalonia/assets/20198528/b58bed11-1f3c-4081-81ea-6aebb88020cd)

![image](https://github.com/AvaloniaUI/Avalonia/assets/20198528/91dbd65d-60c2-49d7-af8a-90e0b61dacb6)

![screenshots](https://github.com/AvaloniaUI/Avalonia/assets/20198528/5ecfd3d4-74ce-4ed0-b892-6389ec6acac4)

**Comment by timunie** [comment]
No I guess I stopped debugger too early. Sorry. After having a deeper look it may be related to: https://github.com/AvaloniaUI/Avalonia/issues/12416 

There's a PR which should address this. You can try it here: https://github.com/AvaloniaUI/Avalonia/pull/12418#issuecomment-1662069675

**Comment by liwuqingxin** [comment]
> No I guess I stopped debugger too early. Sorry. After having a deeper look it may be related to: #12416
> 
> There's a PR which should address this. You can try it here: [#12418 (comment)](https://github.com/AvaloniaUI/Avalonia/pull/12418#issuecomment-1662069675)

Ok, I will see that later. Thank you 👍 @timunie

**Comment by maxkatz6** [comment]
This issue was fixed by https://github.com/AvaloniaUI/Avalonia/pull/12418 (not in 11.0.5-rc, but in nightly builds)
