### ISSUE TITLE
Attached Flyout leak

### ISSUE THREAD

**Issue by Scratch75** [AvaloniaUI/Avalonia#12451]
**Describe the bug**
Opening an Attached Flyout will leak PopupRoot instances if the user mouses over an InputElement within the Flyout. Note that if you do not mouse over the Flyover, no PopupRoot instances appear to be orphaned and therefore no leak.

**To Reproduce**
Create a simple Attached Flyout with one or more InputElement child elements. The following repo contains a very simple example: [https://github.com/Scratch75/FlyoutLeak](url).

1. Click the "Click Me" TextBlock.
2. Hover the mouse over the Calendar within the Flyout. Note that this doesn't need to be a Calendar; a simple TextBlock also exhibits the problem.
3. Click away to dismiss the Flyout.
4. Repeat steps 1-3 several times to exaggerate the problem. There is a 1:1 (or very nearly) ratio between the number of times you repeat this to the number of retained PopupRoot instances.

**Expected behavior**
PopupRoots created as part of showing the Flyout should be GC'd.

**Screenshots**

<img width="707" alt="FlyoutLeakScreenshot1" src="https://github.com/AvaloniaUI/Avalonia/assets/3085903/4d8decdd-9b8b-46d3-b9f9-9602d1cc40d6">

<img width="713" alt="FlyoutLeakScreenshot2" src="https://github.com/AvaloniaUI/Avalonia/assets/3085903/1905f64a-7852-4b02-bf65-830a8f619a0d">

**Desktop (please complete the following information):**

- OS: Windows 11 22H2
- Version 11.0.2

**Additional context**

NOTE: if you open the Flyout and then dismiss it without hovering over the Flyout content, the leak does not occur.

Is it possible that this is caused by TopLevel.PointerOverElementProperty? I'm not familiar with the code, but wondering if cursor management is the culprit?

**Comment by mgnslndh** [comment]
I can confirm that this leak is no longer an issue. It was fixed by https://github.com/AvaloniaUI/Avalonia/commit/7ee12d27b3703274e45cf0d7d8f7efb46ae9d3d9 and I've tested on 5b02b0389aee7aac695b04735e40779b5682b063 (master at the time of testing) and it works without holding on to PopupRoot references in dotMemory.

**Comment by timunie** [comment]
close acc. to user feedback
