### ISSUE TITLE
VirtualizingPanel.RemoveInternalChildRange(int index, int count) remove elements from 0.

### ISSUE THREAD

**Issue by liwuqingxin** [AvaloniaUI/Avalonia#12476]
**Describe the bug**

I have created my virtual panel that derived from VirtualizingPanel. When I called the VirtualizingPanel.RemoveInternalChildRange(...), I found that the first child of the ItemsContorl was always removed.

In the loop in VirtualizingPanel.[RemoveInternalChildRange](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/VirtualizingPanel.cs), a 0 is used instead of the parameter index.

```csharp
public abstract class VirtualizingPanel : Panel, INavigableContainer
{
        /// <summary>
        /// Removes child elements from the <see cref="Panel.Children"/> collection.
        /// </summary>
        /// <param name="index">
        /// The beginning index position within the collection at which the first child element is
        /// removed.
        /// </param>
        /// <param name="count">The number of child elements to remove.</param>
        protected void RemoveInternalChildRange(int index, int count)
        {
            var itemsControl = EnsureItemsControl();
            
            //
            // Should remove from index?
            //
            for (var i = 0; i < count; ++i)
            {
                var c = Children[i];
                itemsControl.RemoveLogicalChild(c);
            }

            Children.RemoveRange(index, count);
        }
}
```

**Desktop (please complete the following information):**

- OS: Win11
- Version 11.0.0

**Comment by timunie** [comment]
please check again with 11.0.2

**Comment by liwuqingxin** [comment]
@timunie It is the same in 11.0.2.

![image](https://github.com/AvaloniaUI/Avalonia/assets/20198528/2564a633-2ae8-4acc-a66a-e8fb2046e2d2)
