### ISSUE TITLE
Dead key doesn't trigger KeyDown on macOS

### ISSUE THREAD

**Issue by MrJul** [AvaloniaUI/Avalonia#12483]
**Describe the bug**
The `KeyDown` event isn't raised for dead key presses in macOS, but the `KeyUp` event is.

**To Reproduce**
Press then release a dead key, for example `^` on an AZERTY keyboard.

**Expected behavior**
Both `KeyDown` and `KeyUp` events are raised.

**Additional context**
macOS Ventura

The dead key press results in `setMarkedText` being called, marking the key as handled, preventing the event for being triggered: https://github.com/AvaloniaUI/Avalonia/blob/655f199647c36b16cad24d68b14f38380c70c8ed/native/Avalonia.Native/src/OSX/AvnView.mm#L602C5-L602C21 (introduced by #11021)

**Comment by Gillibald** [comment]
I think we can add an additional check for that flag. We only need to set if if marked text actually has any content and content has changed
