### ISSUE TITLE
Win32 windows which are constructed but never opened leak memory

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#12487]
`Avalonia.Win32.WindowImpl` [adds itself to the `s_instances` list on construction](https://github.com/AvaloniaUI/Avalonia/blob/655f199647c36b16cad24d68b14f38380c70c8ed/src/Windows/Avalonia.Win32/WindowImpl.cs#L187). But it isn't removed from this list [unless the window receives a `WM_CLOSE` message](https://github.com/AvaloniaUI/Avalonia/blob/655f199647c36b16cad24d68b14f38380c70c8ed/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs#L117).

There is no guarantee that a close message will ever be received. For example, a `Window` can be constructed and discarded without ever opening. This results in large memory leaks.

**To Reproduce**

1. Inspect `Avalonia.Win32.WindowImpl.s_instances` (using the debugger if necessary).
2. Construct a `Window` and immediately discard the object.
3. Run the garbage collector.
4. Inspect `s_instances` again. The `WindowImpl` for the window created at step 2 is still there, and there is no longer any way to remove it.

This keeps the window and all of its contents, viewmodels, etc. alive.

**Expected behavior**
* Avalonia does not keep strong references to a window which is not open.
* All native references are cleaned up in a `~WindowImpl` finalizer.
* `WindowImpl` inherits from [`CriticalFinalizerObject`](https://learn.microsoft.com/dotnet/api/system.runtime.constrainedexecution.criticalfinalizerobject) if necessary.

**Desktop:**

- OS: Windows
- Version 11.0.2

**Comment by kekekeks** [comment]
You need to close an Window, since the platform implementation is created in window ctor, not on the first Show. This is currently by design.
