### ISSUE TITLE
Unhandled native exception in MacOS causing 'System.InvalidOperationException: Cannot show window with non-visible parent.`

### ISSUE THREAD

**Issue by jeromemanzano** [AvaloniaUI/Avalonia#12485]
**Describe the bug**
## 1. An unhandled native exception
Following the code from the stacktrace below
```
 "function": "Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)", "lineno": 90
```

It seems like `MicroComRuntime` gets an [UnhandledException](https://github.com/AvaloniaUI/Avalonia/blob/5ebe956413e58af6377999c1356b2ff599c3ab86/src/Avalonia.MicroCom/MicroComRuntime.cs#L89) which eventually [terminates the native app and dispatches the exception](https://github.com/AvaloniaUI/Avalonia/blob/5ebe956413e58af6377999c1356b2ff599c3ab86/src/Avalonia.Native/CallbackBase.cs#L21).
```csharp
threadingInterface.TerminateNativeApp();
threadingInterface.DispatchException(ExceptionDispatchInfo.Capture(e));
```

Is there a way for us to capture this native exception so we can further investigate the cause of the issue?

## 2. System.InvalidOperationException : Cannot show window with non-visible parent.

The native exception seems to eventually lead to [NativeMenuItem getting clicked](https://github.com/AvaloniaUI/Avalonia/blob/5ebe956413e58af6377999c1356b2ff599c3ab86/src/Avalonia.Native/AvaloniaNativeMenuExporter.cs#L81C34-L81C44), which then causes to show [AboutAvaloniaDialog](https://github.com/AvaloniaUI/Avalonia/blob/5ebe956413e58af6377999c1356b2ff599c3ab86/src/Avalonia.Native/AvaloniaNativeMenuExporter.cs#L81), which then throws the `System.InvalidOperationException` (possibly because the `MainWindow` is not visible anymore after the app termination beforehand?)

```csharp
var aboutItem = new NativeMenuItem("About Avalonia");
aboutItem.Click += async (_, _) =>
{
    var dialog = new AboutAvaloniaDialog();

    if (Application.Current is
        { ApplicationLifetime: IClassicDesktopStyleApplicationLifetime { MainWindow: { } mainWindow } })
    {
        await dialog.ShowDialog(mainWindow);   
    }
};
```

**To Reproduce**

We were unable to reproduce this. This occasionally occurs to our users and we are only able to capture it through sentry when the application crash.

**Expected behavior**
1. A way to capture the native exception.
2. I'm not sure about this but I think we shouldn't receive the `InvalidOperationException` here since it's not directly related to the native exception?

**Screenshots**
```JSON
"exception": {
  "type": "System.InvalidOperationException",
  "value": "Cannot show window with non-visible parent."
},
"stacktrace": {
  "frames": [
    { "function": "Mailbird.Program.BuildMailbirdApp(IBootstrapperInit`1 bootstrapperInit)" },
    { "function": "Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)",
      "lineno": 209 },
    { "function": "Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)",
      "lineno": 120 },
    { "function": "Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)",
      "lineno": 65 },
    { "function": "Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)",
      "lineno": 90 },
    { "function": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()" },
    { "function": "Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue)",
      "filename": "/_/src/Avalonia.Native/Interop.Generated.cs",
      "lineno": 4343 },
    { "function": "Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue)",
      "lineno": 39 },
    { "function": "Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)",
      "lineno": 37 },
    { "function": "System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)" },
    { "function": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()" },
    { "function": "Avalonia.Native.AvaloniaNativeMenuExporter.<>c.<<CreateDefaultAppMenu>b__18_0>d.MoveNext()",
      "lineno": 81 },
    { "function": "Avalonia.Controls.Window.ShowDialog(Window owner)",
      "lineno": 722 },
    { "function": "Avalonia.Controls.Window.ShowDialog[TResult](Window owner)",
      "lineno": 755 }
  ]
}
```

**Desktop (please complete the following information):**

- OS: MacOS
- Version Ventura 13.5

**Additional context**
- Avalonia Version: 0.10.21
- .NET Version: 7.0.4

**Comment by timunie** [comment]
@jeromemanzano there is a high chance that Avalonia 0.10.x will not recieve many fixes anymore as all the capacity is going into the current version 11.0. If you are able to reproduce it using 11.0, plesae let us know. Also it would be good if there is a clear way to reproduce.

**Comment by jeromemanzano** [comment]
@timunie thanks for the quick response.

> there is a high chance that Avalonia 0.10.x will not recieve many fixes anymore as all the capacity is going into the current version 11.0. If you are able to reproduce it using 11.0, plesae let us know.

We'll try to upgrade and see if we will still be able to reproduce the issue.

> Also it would be good if there is a clear way to reproduce.

I'll update this when we find a reliable way to reproduce the issue.

**Comment by maxkatz6** [comment]
Second issue is fixed. 

But actually, I can't really reproduce the first one. Let me know if it's still happening on 11.1 builds.
