### ISSUE TITLE
DragDrop does not work when main is async (Task)

### ISSUE THREAD

**Issue by ArchLeaders** [AvaloniaUI/Avalonia#12499]
**Describe the bug**
Drag/drop (DragDrop.AllowDrop) targets do not work when the `Main` function is `async Task`

**To Reproduce**

1. Create a new Avalonia project
2. In `MainWindow.axaml` add a `Border` with `DragDrop.AllowDrop="True"`
3. Run the application (copy/move icon will show up and drop events are fired)
4. Set the `Main` function in `Program.cs` to return `async Task` instead of `void`
5. Run the application (invalid/unsupported icon will show up and drop events are never fired)

**Expected behavior**
Drag/drop should work in async context

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.0 and 11.0.2

**Additional context**
Minimal reproduction can be found here: https://github.com/ArchLeaders/DragDropAvalonia

**Comment by kekekeks** [comment]
1) Windows drag-n-drop requires the main thread to use STA apartment
2) macOS requires the UI thread to be the **first** thread of the application

Both are OS requirements that should be met by your application.

With `async` `Main` roslyn runs your code on some random thread from the pool.

You can try filing an issue with Roslyn to make it to run the code on the true first thread.

**Comment by ArchLeaders** [comment]
> 1. Windows drag-n-drop requires the main thread to use STA apartment
> 2. macOS requires the UI thread to be the **first** thread of the application
> 
> Both are OS requirements that should be met by your application.

Ah cool, thanks. I was able to use this on Windows and that worked fine.

```cs
if (OperatingSystem.IsWindows()) {
    Thread.CurrentThread.SetApartmentState(ApartmentState.Unknown);
    Thread.CurrentThread.SetApartmentState(ApartmentState.STA);
}
```

Not sure what I'll do for macOS, but I'll post here in case anyone else is looking for a solution.
