### ISSUE TITLE
ContextMenu can not be opened at pointer position from code-behind

### ISSUE THREAD

**Issue by DmitryZhelnin** [AvaloniaUI/Avalonia#12504]
**Describe the bug**
`ContextMenu` created and opened from code-behind always appears at the bottom of the control.

**To Reproduce**

```xaml
    <Border
        Width="200"
        Height="200"
        Background="Red"
        ContextRequested="Control_OnContextRequested">
    </Border>
```

```cs
    private void Control_OnContextRequested(object? sender, ContextRequestedEventArgs e)
    {
        if (sender is not Border border)
        {
            return;
        }

        var items = new List<string>
        {
            "Item 1",
            "Item 2",
            "Item 3"
        };

        var menu = new ContextMenu
        {
            ItemsSource = items,
            Placement = PlacementMode.Pointer
        };

        menu.Open(border);
    }
```

**Expected behavior**

Context menu should be opened at pointer position.

**Screenshots**

![изображение](https://github.com/AvaloniaUI/Avalonia/assets/4993430/1dbdfa30-a93f-43fe-820f-c5281ca97d11)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 11.0.2

**Additional context**

When `ContextMenu` is opened via public `Open` method later private `Open` method is called. This private method receives `requestedByPointer` parameter which is false. So `PlacementMode.Pointer` is replaced by `PlacementMode.Bottom`.

https://github.com/AvaloniaUI/Avalonia/blob/1896e8ad68dc0fdb6c1055d36a97b926e0a32f17/src/Avalonia.Controls/ContextMenu.cs#L334-L336

However if I call private method directly via reflection `ContextMenu` is opened at pointer position. So what is the purpose of this check in `Open` method?

```cs
        typeof(ContextMenu)
            .GetMethod("Open", BindingFlags.NonPublic | BindingFlags.Instance)?
            .Invoke(menu, new object[] { border, border, true });
```

![изображение](https://github.com/AvaloniaUI/Avalonia/assets/4993430/78fc7f8c-76ee-4bf1-86a3-d572da42f08b)

**Comment by timunie** [comment]
looks like a wrong check to me. Not 100% sure. Maybe you can find the PR that introduced this and see if there is any reasoning. Otherwise, maybe you can file a PR to fix this issue.

**Comment by DmitryZhelnin** [comment]
I think this is done for the situations when ContextMenu is opened by keyboard. If you focus TextBox and press context menu button on the keyboard the popup is opened at bottom of the TextBox.

![изображение](https://github.com/AvaloniaUI/Avalonia/assets/4993430/8bb71a38-63b7-4a21-9480-b78271f021d7)

In case of TextBox I prefer it is opened at caret position, but I think it is another issue and should be investigated separately.

**Comment by maxkatz6** [comment]
Please don't use ContextMenu unless you need it for compatibility with Wpf. 
Use MejuFlyout. 
Also, you can get pointer position from the args.

**Comment by DmitryZhelnin** [comment]
Yes, I can open ContextFlyout at the pointer position.
But can we get behavior similar to ContextMenu: when menu is opened on every right button click?

https://github.com/AvaloniaUI/Avalonia/assets/4993430/fac8f32d-b96f-4b63-85f9-99e03626c374


https://github.com/AvaloniaUI/Avalonia/assets/4993430/fc0ea03f-ce4c-42b9-99a7-3f5e4d9d2c65

**Comment by robloo** [comment]
Personally, I kind-of agree with both points.
 1. It makes no sense to be overriding PointerPosition like this in all cases. That special purpose code probably isn't wanted.
 2. This is a good opportunity to move to ContextFlyout/MenuFlyout which is a general-purpose equivalent of the ContextMenu and what code should be going to in the future.
