### ISSUE TITLE
DataGrid cell does not update on INotifyPropertyChanged

### ISSUE THREAD

**Issue by Sophisticated-IS** [AvaloniaUI/Avalonia#12509]
**Describe the bug**
DataGrid cell does not update content on InotifyPropertyChanged event. Only update when fires datagrid embedded sort.
**To Reproduce**

Example:
[AvaloniaTestGround.zip](https://github.com/AvaloniaUI/Avalonia/files/12313845/AvaloniaTestGround.zip)

1. select row in datagrid
2. Press update property button
3. You see Nothing changed
4. Press datagrid sort by DateTime column and you see changes

**Expected behavior**
DataGrid cell updates its content on InotifyPropertyChanged event

**Screenshots**

https://github.com/AvaloniaUI/Avalonia/assets/57034720/976127db-11bf-48fe-ab77-11164ac452cf

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Windows 10
- Avalonia 11.0.3

**Additional context**

**Comment by Sophisticated-IS** [comment]
The problem is not in Avalonia. Problem was in wrong using/injection of "PropertyChanged.Fody" library

**Comment by timunie** [comment]
@Sophisticated-IS try CommunityToolkitMvvm. It has source generators which are way more powerful these days.
