### ISSUE TITLE
Incorrect IsCheckedChanged events triggered in ListBox with CheckBox controls when hidden by GridSplitter

### ISSUE THREAD

**Issue by maciej-izak** [AvaloniaUI/Avalonia#12505]
**Describe the bug**
When using a `GridSplitter` to hide a `ListBox` containing `CheckBox` controls in Avalonia, incorrect `IsCheckedChanged` events are generated for all items except the first one in the `ListBox`. This leads to unexpected behavior and incorrect event handling.

**To Reproduce**
1. Open the application containing the `GridSplitter` and `ListBox` with `CheckBox` controls:
[CheckBoxBug.zip](https://github.com/AvaloniaUI/Avalonia/files/12312250/CheckBoxBug.zip)
2. Use the `GridSplitter` to hide the `ListBox`.
3. Observe that incorrect `IsCheckedChanged` events are triggered for all items except the first one.

**Expected behavior**
The `IsCheckedChanged` events should only be triggered when the actual state of the `CheckBox` controls is changed. Hiding the `ListBox` using the `GridSplitter` should not generate these events.

**Screenshots**
none

**Desktop (please complete the following information):**
- OS: Windows 10
- Version: Avalonia 11.0.2

**Additional context**
This issue might lead to unexpected behavior in applications that rely on accurate `IsCheckedChanged` events for `CheckBox` controls within a `ListBox`. Careful handling and validation may be needed to avoid potential problems caused by these false events.

**Comment by robloo** [comment]
I don't think you can use IsCheckedChanged like this with ListBox virtualization. The best thing to do is have an IsSelected property on your view model and update that through other means. Otherwise, with recycling and virtualization it's going to be difficult I think.

**Comment by timunie** [comment]
If I try the sample with a non-virtualized ItemPanel, it does not trigger the event as expected. So this behavior is by design in case of using virtualization. 

```diff
<ListBox Grid.Column="2" Name="listBox" ItemsSource="{Binding CbItems}">
        <ListBox.ItemTemplate>
            <DataTemplate>
                <StackPanel Orientation="Horizontal">
                    <CheckBox IsChecked="{Binding IsChecked}" IsCheckedChanged="IsCheckedChangedEvent" />
                    <TextBlock Text="{Binding Name}" />
                </StackPanel>
            </DataTemplate>
        </ListBox.ItemTemplate>

!       <!-- DO NOT USE THIS APPROACH IF YOU EXPECT MORE THAN A FEW ITEMS! -->
!       <!-- Performance will decrease noticeable --> 
+       <ListBox.ItemsPanel>
+           <ItemsPanelTemplate>
+               <StackPanel />
+           </ItemsPanelTemplate>
+       </ListBox.ItemsPanel>
    </ListBox>
```
