### ISSUE TITLE
Implement Closing event on Window

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#1252]
It should be possible to handle a window closing, and prevent it if necessary.
This would be similar to the [`Window.Closing` event](https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.closing?view=netframework-4.7.1) in WPF.

**Comment by Gillibald** [comment]
This can probably closed or is something missing?

**Comment by jp2masa** [comment]
Right. Fixed by #1383.
