### ISSUE TITLE
Cross platform iOS apps crash when targeting iOS 17

### ISSUE THREAD

**Issue by TrueGeek** [AvaloniaUI/Avalonia#12530]
**Describe the bug**
iOS apps fail when targeting iOS 17

**To Reproduce**
1. Create app using Cross Platform template
2. Run iOS app targeting an iOS 17 device / simulator
3. iOS app crashes without opening with error "Library not loaded: /System/Library/Frameworks/NewsstandKit.framework/NewsstandKit"

**Expected behavior**
The app should open without crashing

- OS: iOS
- Version 17.0 Simulator (beta)

**Additional context**
I believe the cause is that Xamarin.iOS will not support Xcode 15 / iOS 17:
https://github.com/xamarin/xamarin-macios/issues/18409

But I'm hoping there is a fix that will allow Avalonia to work around this.

**Comment by maxkatz6** [comment]
Avalonia doesn't use legacy Xamarin.iOS mentioned in your linked issue, so shouldn't be related. 

Please try to run a simple net6.0-ios app or maui app on ios. 

> Library not loaded: /System/Library/Frameworks/NewsstandKit.framework/NewsstandKit"

What is even this?

**Comment by TrueGeek** [comment]
> Please try to run a simple net6.0-ios app or maui app on iOS.

Yes, that also fails. Okay, cool, this my first Avalonia project so I wanted to make sure it wasn't going to have the same limitations as Xamarin. Thank you so much!

> Library not loaded: /System/Library/Frameworks/NewsstandKit.framework/NewsstandKit"
> What is even this?

Apparently some iOS SDK for building news apps. From WAY back in iOS 5, but removed now in iOS 17!

**Comment by gentledepp** [comment]
@TrueGeek how come you completed this?
Did you get it to run eventually?

We still have the same problem

**Comment by TrueGeek** [comment]
Sorry, for this project we ended up not using Avalonia and just went with MAUI but not because of this issue. Like marketz6 says this wasn't an Avalonia issue, but a Microsoft thing.

**Comment by maxkatz6** [comment]
@TrueGeek there shouldn't be any difference between MAUI and Avalonia in terms how these handle dependencies like `NewsstandKit.framework`. As in both cases it's handled by the .NET iOS workload. 

It might depend on the .NET version used. Either .NET 7 or .NET 8.
