### ISSUE TITLE
TextBlock Control does not display line breaks in inline text

### ISSUE THREAD

**Issue by ZeroOne010101** [AvaloniaUI/Avalonia#12534]
**Describe the bug**
The Builtin `TextBlock` Control does not respect line breaks.
The Documentation claims otherwise: https://docs.avaloniaui.net/docs/next/reference/controls/detailed-reference/textblock

**To Reproduce**

1. Create a new Avalonia C# Project (i use the CommunityToolkit) in Visual Studio.
2. Paste the example code into the MainView.axml file (result repeated below for clarity.
```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:vm="clr-namespace:TextBlockTest.ViewModels"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="TextBlockTest.Views.MainView"
             x:DataType="vm:MainViewModel">
	
  <Design.DataContext>
    <!-- This only sets the DataContext for the previewer in an IDE,
         to set the actual DataContext for runtime, set the DataContext property in code (look at App.axaml.cs) -->
    <vm:MainViewModel />
  </Design.DataContext>

	<StackPanel Margin="20">
		<TextBlock Margin="0 5" FontSize="18" FontWeight="Bold">Heading</TextBlock>
		<TextBlock Margin="0 5" FontStyle="Italic">This is  a single line.</TextBlock>
		<TextBlock Margin="0 5">
			This is a multi-line display
			that has returns in it.
			The text block repects the line breaks
			as set out in XAML.
		</TextBlock>
	</StackPanel>
</UserControl>
```
3. As you can see, the last TextBlock is displayed in a single line, which it shouldn't.

**Expected behavior**
Either TextBlock should respect line breaks in the .axml file, or the Documentation should be updated to reflect that it does not.

**Screenshots**
![grafik](https://github.com/AvaloniaUI/Avalonia/assets/43586679/5fb7ea08-e311-43bf-b691-b28908c4100b)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 22H2
- Version 22H2 Build 19045.3208

**Additional context**
Using Avalonia 11.0.2

I am new to Avalonia, MVVM, Frontend Development and C#.
Please excuse any errors i might have made.
I have also tried adding xml:space="preserve" to the code which did work, but did not behave as implied by the documentation (it displayed all spaces, contrary to the docs example).

**Comment by Gillibald** [comment]
Works as expected

Either add line breaks explicitly via `&#x0a;`

Or add `xml:space="preserve"` to the TextBlock node

**Comment by ZeroOne010101** [comment]
I missed that visual studio automatically formats my paste from the wiki.
My bad.

**Comment by timunie** [comment]
You're welcome anyway. Enjoy Avalonia 🙂
