### ISSUE TITLE
Unable to Open a New Window in a Separate Thread

### ISSUE THREAD

**Issue by kadir-ince** [AvaloniaUI/Avalonia#12554]
### Description

When I try to create a new window within a different thread, I encounter a "Call from invalid thread" error. In WPF, creating a window in this manner results in the creation of a separate UI thread for that window. However, in Avalonia, it appears I can't open a window this way.

### Steps to Reproduce

1. Create a new Avalonia project.
2. Try to create and show a new window within a separate thread:

```csharp
Thread newWindowThread = new Thread(() =>
{
    Window newWindow = new Window();
    newWindow.Show();
});
newWindowThread.SetApartmentState(ApartmentState.STA);
newWindowThread.Start(); 
```

**Expected behavior**
A new window should open in a separate thread, similar to the behavior in WPF.

**Actual Behavior**
Call from invalid thread

**Desktop**
Avalonia version: 11.0.0
OS: Windows 11
Development Environment: Visual Studio 2022

**Additional context**
I believe that being able to open windows in separate threads can be valuable for specific use-cases, and this behavior should be supported, given that it's present in WPF. If this is by design in Avalonia or if there are any workarounds available, I'd appreciate any guidance on this matter.

**Comment by maxkatz6** [comment]
It's not a bug but by design.
The biggest reason it's not supported is macOS, which forces every window to be created and used from the Main UI Thread, i.e. the first thread.

It's only technically possible on Windows and Linux, but we don't have plans to support this scenario only partially.
