### ISSUE TITLE
ProgressBar is not stretched inside panel by default

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1256]
Repro:
```XAML
<UserControl xmlns="https://github.com/avaloniaui">
  <Grid ColumnDefinitions="50,50,*">
    <ProgressBar Value="50" Orientation="Vertical" Grid.Column="0"/>
    <ProgressBar Value="75" Orientation="Vertical" IsIndeterminate="True" Grid.Column="1"/>
    <Grid RowDefinitions="50,50,*" Grid.Column="2" >
      <ProgressBar Value="25" Grid.Row="0" />
      <ProgressBar Value="40" IsIndeterminate="True" Grid.Row="1"/>
    </Grid>
  </Grid>
</UserControl>
```
![dotnet_2017-11-01_17-07-07](https://user-images.githubusercontent.com/2297442/32284310-26b26bf0-bf27-11e7-996e-d38321b8f95a.png)

In WPF `ProgressBar` control has ` VerticalAlignment="Stretch"` and `HorizontalAlignment="Stretch"` set by default. In avalonia you have to set it manually in Xaml:
```XAML
<UserControl xmlns="https://github.com/avaloniaui">
  <Grid ColumnDefinitions="100,100,*">
    <ProgressBar Value="50" Orientation="Vertical" Grid.Column="0" VerticalAlignment="Stretch" HorizontalAlignment="Stretch"/>
    <ProgressBar Value="75" Orientation="Vertical" IsIndeterminate="True" Grid.Column="1" VerticalAlignment="Stretch" HorizontalAlignment="Stretch"/>
    <Grid RowDefinitions="100,100,*" Grid.Column="2" >
      <ProgressBar Value="25" Grid.Row="0"  VerticalAlignment="Stretch" HorizontalAlignment="Stretch"/>
      <ProgressBar Value="40" IsIndeterminate="True" Grid.Row="1" VerticalAlignment="Stretch" HorizontalAlignment="Stretch"/>
    </Grid>
  </Grid>
</UserControl>
```
![dotnet_2017-11-01_17-06-43](https://user-images.githubusercontent.com/2297442/32284316-2a6e7d56-bf27-11e7-8530-12f4e5d57a5a.png)

Version: 0.5.2-build4189-alpha

**Comment by danwalmsley** [comment]
iv noticed this also, its definitely used to be stretched by default, so this must have been introduced at some point

**Comment by grokys** [comment]
This seems to have been introduced in this commit: https://github.com/AvaloniaUI/Avalonia/commit/7cb4485d

@jp2masa do you remember why you changed this? I think it should be changed back.

**Comment by jp2masa** [comment]
I think that I changed it to match some WPF behaviour, but it broke this one... I can take a look.

**Comment by grokys** [comment]
afaics, the default is `Stretch` in WPF.
