### ISSUE TITLE
Can't use Tab/Enter in IME candidates list

### ISSUE THREAD

**Issue by MrJul** [AvaloniaUI/Avalonia#12571]
**Describe the bug**
After #12560, Tab can't be used anymore to select composition candidates, and Enter never commits the composition.

**To Reproduce**
Switch to Japanese Kana keyboard layout, type a few chars until the IME candidates list appear.
Try to use Tab to select a candidate: Tab is handled by Avalonia instead and the focus moves.
Try to use Enter to validate the IME: Enter is handled by Avalonia instead and inputs a line break.
(And probably other special shortcuts I'm not aware of.)

**Expected behavior**
While an IME session is active, the keys should go to it.

**Remarks**
I'm not sure what's the best resolution is here, the reversed `TextInput`/`KeyDown` events order before #12560 wasn't ideal but it ensured that special keys were handled by the IME.

There's no IME start/end notification on macOS?

@danwalmsley @Gillibald

**Comment by kekekeks** [comment]
If IME is in play user code should **never** get events that are processed by IME. Attempting to handle those is invalid behavior which needs to be removed.
