### ISSUE TITLE
The wasm project release directory does not refer to the directory structure defined by the “FolderProfile.pubxml”

### ISSUE THREAD

**Issue by Red6789** [AvaloniaUI/Avalonia#12591]
When i run publish command and define FolderProfile.pubxml,
The prefetch result is bin\Release\net7.0\browser-wasm\publish\AppBundle,
But the actual result is bin\Release\net7.0\browser-wasm\AppBundle,
Is this normal behavior or does it need to be fixed?
This is my FolderProfile.pubxml
```
<Project>
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Release\net7.0\browser-wasm\publish\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <_TargetId>Folder</_TargetId>
    <TargetFramework>net7.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>
</Project>
```
I use avalonia.browser and version is 11.0.3.

**Comment by maxkatz6** [comment]
Please open this bug in dotnet/runtime or dotnet/sdk repository. Is has nothing to do with Avalonia.
