### ISSUE TITLE
Browser Control / CEF?

### ISSUE THREAD

**Issue by robertmuehsig** [AvaloniaUI/Avalonia#1259]
Hi 
I'm currently working on a X-Plat project called "[Electron.NET](https://github.com/ElectronNET/Electron.NET)" - it is currently a more or less a wrapper around the nodejs Electron stuff and hosting a embedded ASP.NET Core application with the goal to have a X-Plat desktop app.

We had a lot of feedback and the questions came up if it would be possible to remove the dependency on Electron at all. Electron itself (at least the very basic) seems to be a x-plat host of the Chromium Embedded Framework. 
Now I searched for a CEF .NET Core port, but unfortunately it seems there isn't one. I know CEFSharp, which is Windows Only and there is CEFGlue, which has a port, but it's not working on my machine (https://github.com/VitalElement/CefGlue.Core) 

Few years ago I asked the same question the [CEFSharp-Team](https://github.com/cefsharp/CefSharp/issues/1435) and they pointed me just to the CEF-project.

I saw that the CefGlue.Core port is using Avalonia, so my question is: Have you any plans to support a Browser Control based on CEF inside Avalonia? 
My "main" problem is, that my C++ knowledge is very limted, so I was looking for a solution to have a X-plat browser control working with .NET Core.

If you don't plan something like this or if this is out of scope of this project it fine, but I wanted to ask if there are some bits out there to help me out :)

**Comment by danwalmsley** [comment]
@robertmuehsig hey, I'm the one responsible for that port of CEF Glue to Avalonia! I was working on a project that needed rich text editor quickly, so I used that. It can easily be made to work again.

My port did not involve and changes to the c++ part, I just used pre-built binaries I obtained from the web, all the porting was done on the c# bit.

I managed to get it running on mac and windows. The port is not complete however, it was just enough for what I needed.

Essentially this is a very simple browser control, but it would need a lot of work to support some of the advanced features id imagine you may require, like DOM access.

I did manage to get C# to invoke methods in javascript, and if I remember correctly javascript was able to notify back to c# world, code was very convoluted and "hacky" to make this work however.

If you need any help getting it to work again I would be happy to help.

**Comment by robertmuehsig** [comment]
Oh nice! Maybe we should continoue on [this issue](https://github.com/VitalElement/CefGlue.Core/issues/8) instead and close this one? 

Sorry for my impatience - we had a bunch of questions why we need Electron etc. and I was looking for an alternative (even it is super "simple")
