### ISSUE TITLE
DataGrid - Add Ability To Direct Add New Row

### ISSUE THREAD

**Issue by furesoft** [AvaloniaUI/Avalonia#12603]
Currently the DataGrid can only view and edit rows that are already present in the list. The windows datagrid has an empty line to insert a new row. This would be really useful.

**Comment by Mrxx99** [comment]
Is this a duplicate of #9922?

**Comment by timunie** [comment]
@Mrxx99 yeah I think it is. So I'm closing this in favor of the original one
