### ISSUE TITLE
CheckBox and ToggleButton should support three states

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#1262]
- `IsChecked` should be a nullable `bool`. [WPF reference](https://msdn.microsoft.com/en-us/library/system.windows.controls.primitives.togglebutton.ischecked(v=vs.110).aspx)
- `IsThreeState` needs to be added. [WPF reference](https://msdn.microsoft.com/en-us/library/system.windows.controls.primitives.togglebutton.isthreestate(v=vs.110).aspx)
- The `CheckBox` template needs to be updated.

If this is a planned feature, I can work on it.

**Comment by jkoritzinsky** [comment]
You can go for it.

**Comment by Shadowblitz16** [comment]
RadioButton doesn't work with three state.
```xaml
                <Grid Grid.Column="1" RowDefinitions="Auto, Auto, Auto, Auto, Auto, Auto">
                    <Grid Grid.Row="0" RowDefinitions="Auto, Auto">
                        <RadioButton Grid.Row="0" Content="{Binding RadioBoxText}"/>
                        <RadioButton Grid.Row="1" Content="{Binding RadioBoxText}" IsChecked="True"/>
                    </Grid>
                    <RadioButton Grid.Row="1" Content="{Binding CheckBoxText}" IsThreeState="True" IsChecked="{x:Null}"/>
                </Grid>
```

![Image](https://github.com/user-attachments/assets/49cb353c-f730-4970-9a2e-4573be01d35c)
