### ISSUE TITLE
Win 11 system default font Segoe UI cannot work on Avalonia program

### ISSUE THREAD

**Issue by Flithor** [AvaloniaUI/Avalonia#12625]
**Describe the bug**
I set the `Segoe UI` on FontFamily not change the font, software font still use the default(system run with chinese language).

**To Reproduce**
Set `FontFamily="Segoe UI"` on `TemplatedElement`

**Expected behavior**
Segoe UI is the default font of Win10/11, program should use this default font.

- OS: Windows 11
- Version 0.10.21

**Comment by timunie** [comment]
wasn't it `TextBlock.FontFamily="Segoe UI"` which one needed to set? 🤔

**Comment by Flithor** [comment]
@timunie  Window, TextBlock, ListBox, Label and so on, are not work.

**Comment by timunie** [comment]
FluentTheme or DefaultTheme?

**Comment by timunie** [comment]
I guess one needs to override this: https://github.com/AvaloniaUI/Avalonia/blob/88852695bcb519c5a13b01956df583920aaf992a/src/Avalonia.Themes.Fluent/Accents/Base.xaml#L16C112-L16C112

which is used here: https://github.com/AvaloniaUI/Avalonia/blob/88852695bcb519c5a13b01956df583920aaf992a/src/Avalonia.Themes.Fluent/Controls/Window.xaml#L6

**Comment by Flithor** [comment]
Oh I use fluent.
Override this still not work, I tried.

**Comment by timunie** [comment]
@Flithor I can't reproduce in a simple sample on my end using 0.10.x
Please provide a minimal sample to reproduce. Maybe some style leaking in or stuff like that.

**Comment by Flithor** [comment]
Ah, I get it.
Segoe UI not contains Chinese character graphy... and the alternate font is not handled correctly.
The same bug caused cannot display right Chinese character graphy in TextBox.
