### ISSUE TITLE
Building from master

### ISSUE THREAD

**Issue by sonarworks** [AvaloniaUI/Avalonia#1264]
I really did not want to open this, since I guess you get lots of this kind of questions, but I couldn't manage myself so...

I am trying to build from master on Windows using the cake build scripts and ran into several issues, any info on tackling them would be appreciated.

1) The tests in Avalonia.Input.UnitTests fail all the time (there is an exception that CustomNavigatingStackPanel does not have a GetNext method even though it seems to be there). I resolved this by removing that particular test from the build.cake file. I also tried the -SkipTests argument but that did not work (does it actually do anything?).

2) I don't want to build iOS and Android (which fails since I don't have Xamarin installed) so how can I control that ? Again I tackled this by commenting out the NuspecNuGetSettings.AddRange(nuspecNuGetSettingsMobile); line in packages.cake. 

I want to build from sources because I am having issues with line height in DirectWrite and wanted to have a look, but could not find a way to produce a package with debug info. How do you guys do debugging internally? Just by running the samples and putting in things that you need to check? If I have an external app that uses Avalonia through NuGet, what is the most efficient way to throw in some debug binaries to do some debugging?

**Comment by jkoritzinsky** [comment]
During development we usually just build within VS. That's how we get our debug assemblies. Also, in VS you can unload the projects for iOS and Android. The `ReplaceNugetCache` script in our scripts directory can be used to replace the Avalonia version pulled from nuget with a local copy.

 The Cake scripts (at least for me) are primarily used on CI. They take too long to run on my machine for regular development.

**Comment by sonarworks** [comment]
Thanks for pointing to the `ReplaceNugetCahce` script, I'll try that.

**Comment by sonarworks** [comment]
I'm not too familiar with NuGet package cache in the user directory (actually I did not know it was there), but I see that the script places the binaries right in the `packages\Avalonia` folder without any versions (I have folders `0.5.1`, `0.5.2-build4186-alpha` and `0.5.2-build4199-alpha` there). Is that fine? With the binaries override the versioned ones?

**Comment by jkoritzinsky** [comment]
You need to pass the version of Avalonia you want it to replace the packages for as a parameter to the script. Like `0.5.2-build4186-alpha`.

**Comment by sonarworks** [comment]
I assume this question is not relevant here, but just for my understanding - how do the multiple places that the NuGet packages are stored at override each other? I mean they are copied to the output folder, then there is the `packages` folder in the solution, then this folder in the user directory.

**Comment by jkoritzinsky** [comment]
`PackageReference` style packages use the `.nuget` folder in the user directory. `packages.config` packages use the `packages` folder in the solution. The packages in those folders are copied to the output folder.

**Comment by sonarworks** [comment]
Thanks for the info:)
