### ISSUE TITLE
Avalonia Inter font look stretched vertically

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#12663]
After I replaced my embeded Inter font with Avalonia.Fonts.Inter a few month ago, I noticed that the text of my app looked stretched vertically.

I haven't had time to investigate until now, but now that I implemented RichTextKit in my app, I gave another try with same text and same fontsize, and yes Avalonia Inter is taller by 1px for size=13. Any idea what's wrong?

I also have collegues that work with Inter font on the web and it doesn't look the same as in Avalonia.

Here is a video comparing Avalonia Inter and Inter using RichTextKit:

https://github.com/AvaloniaUI/Avalonia/assets/3595443/f5f37de3-9492-4b13-b6f6-035f5efa275a

NOTE: the Inter fonts downloaded on Google weight 300kb, while the Avalonia ones weight 350kb. May be you could upgrade the fonts to save a few kilobytes? espeacially on WASM.

Windows 10 or 11
Avalonia 11.0.4

**Comment by dbriard** [comment]
I found the guilty!

I recreated Avalonia.Fonts.Inter project and replaced the fonts with newly downloaded Inter from Google Fonts.
And no more stretching :)

Moreover, the newly downloaded fonts are lighter, about 300 kb, vs 350 kb currently in avalonia project! That still a few kilobytes save for WASM apps.

Here is a video:
https://github.com/AvaloniaUI/Avalonia/assets/3595443/7b6d1f6f-1154-440f-931f-6b30ef77e31b

The texts now looks much better, no more vertical stretch anoying effect.

Would you like I replace the fonts in a PR?

**Comment by Gillibald** [comment]
I am fine with updating the font

**Comment by timunie** [comment]
@dbriard go ahead and file a PR 🙏

**Comment by dbriard** [comment]
> @dbriard go ahead and file a PR 🙏

done!

**Comment by timunie** [comment]
Just  a Hint @dbriard: if you write Fixes #... In the PR, the issues are getting closed automatically ☺️

Thx for the PR anyway.
