### ISSUE TITLE
Weird 1 pixel layout bug when a control is loaded. Repro and video included.

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#12676]
**Describe the bug**
There is a layout issue when a control is loaded and before it is touched. It is 1 pixel too long in width. After its state change, the control with is reduce by 1 pixel.
This is related to ContentDialog foreground change.

**To Reproduce**
1. Create a new Avalonia Application.
2. Add a button (for example)
3. Run the app
4. MouseOver the Button
5. The width of the button change, it is reduced by 1 pixel ??!!! 

To better see the result, put the button inside a LayoutTransformControl with x8 scaling, and set padding to 0
When you run the app, there is 2 pixels between text and border on left side, and 1 pixel on right side.
When you mouseover (in fact, when the state of the foreground change), the left side become 1 px.

If you create a custom theme for the button, with BrushA for Foreground, BrushA again for MouseOver, and BrushB for Pressed.
The 1-pixel shift only happen when the button is pressed, that allow to measure with the inspector, and we can see that the DesiredSize of the text is reduced by 1 pixel after the foreground state change.

**Expected behavior**
The layout must be good when the control is loaded, and should not change after.

**Screenshots**

https://github.com/AvaloniaUI/Avalonia/assets/3595443/1c827615-6378-4aff-9d6e-72b18b259941

**Repro sample**
[OnePixelBug.zip](https://github.com/AvaloniaUI/Avalonia/files/12446123/OnePixelBug.zip)

**Desktop (please complete the following information):**

- OS: Windows 11 (with OS scaling 100%)
- Version: tested with v11.0.2, v11.0.4 and latest nighly

**Additional context**

**Comment by timunie** [comment]
place your sample into samples > Sandbox and add breakpoints into the layout pass if you want to investigate it on your own further.

**Comment by Gillibald** [comment]
Could be related to rounding differences. First layout snaps the control to the left. Second to the right. Just some theory.

**Comment by MrJul** [comment]
I had a look at this: please see #12765 for details about the problem and a potential fix.
