### ISSUE TITLE
CanExecute field of RelayCommand does not work when Binding TextBox.Text using CommunityTookit

### ISSUE THREAD

**Issue by cylix-lee** [AvaloniaUI/Avalonia#12678]
**Describe the bug**
I'm using CommunityTookit instead of ReactiveUI for MVVM. I followed the official Getting Started guide to create a ToDo app, but the OK button remains disabed when the `TextBox` isn't empty. But when I debug and call `Debug.Print()` to reveal the value of TextBox.Text, it's exactly what I typed in. So I assume that `CanExecute` of `RelayCommand` causes the problem.

I've created a repository here: [AvaloniaToDo.BugReport](https://github.com/cylix-lee/AvaloniaToDo.BugReport)

**To Reproduce**

1. Create an `AddItemView` and its viewmodel called `AddItemViewModel`.

2. Setting up the view like this and bind the two buttons with their command respectively, and bind `TextBox.Text` to an `ObservableProperty` called `Description`.
![image](https://github.com/AvaloniaUI/Avalonia/assets/73686879/e3cf8029-eff4-4822-963a-24dc10097c25)
*Figure 1: AddItemView setup*

3. `AddItemViewModel` contains the two commands and the text property. Note that `CanExecute` is set to a property for determining whether the `Ok` command can be executed.
![image](https://github.com/AvaloniaUI/Avalonia/assets/73686879/c4a774b7-150c-4be1-a7c4-5a12e4359dfe)
*Figure 2: Implement AddItemViewModel using CommunityTookit*

4. Run the program, and you'll see the OK button remains disabled all the time, even if you changes the text of the textbox.

**Expected behavior**
According to the official tutorial (which uses ReactiveUI though), the OK button should be enabled once the text of textbox is not empty, as the *Figure 3* and *Figure 4* show below:
![image](https://github.com/AvaloniaUI/Avalonia/assets/73686879/cae74f47-bf4d-493b-bc37-1caa4fad7518)
*Figure 3: OK button is disabled when the textbox is empty*

![image](https://github.com/AvaloniaUI/Avalonia/assets/73686879/d5842e64-ffd5-48b0-85f3-c0ee3dda87aa)
*Figure 4: OK button is enabled when typed something in textbox*

**Desktop:**

- OS: Windows 11 
- Version 22H2 (22621.2134)

**Additional context**
I've noticed some relative issues like #11610, in which the UI remains unchanged when a property binded to Text is changed. Maybe my issue and #11610 both come from a certain mis-programmed code?

**Comment by rabbitism** [comment]
You also need to add 
`[NotifyCanExecuteChangedFor(nameof(OkCommand))]`
attribute to description field.

**Comment by cylix-lee** [comment]
> You also need to add `[NotifyCanExecuteChangedFor(nameof(OkCommand))]` attribute to description field.

Thanks! I didn't expect the problem is solved such easy😂
![image](https://github.com/AvaloniaUI/Avalonia/assets/73686879/bfa0d34c-56b7-4091-a90c-63e4830d24cd)

**Comment by timunie** [comment]
@cylix-lee if you have more questions, please use Github Discussions or joyn us on Telegram https://t.me/Avalonia
