### ISSUE TITLE
BorderThickness

### ISSUE THREAD

**Issue by vertexpipeline** [AvaloniaUI/Avalonia#1267]
I want to use Border with a Thickness. 
```xml
<Border BorderThickness="2,2,2,0"/>
```
but in code it was defined as
 ```csharp
if (borderBrush != null && borderThickness > 0)
{
      context.DrawRectangle(new Pen(borderBrush, borderThickness), rect, cornerRadius);
}
```
I think You didn't defined the Thickness class and I must do it?

**Comment by danwalmsley** [comment]
@vertexpipeline Thickness is defined, but it isn't implemented for BorderThickness yet!

It should be very easy to implement, the complicated part is then border radius is involved.

**Comment by Krakean** [comment]
@vertexpipeline any progress on this? :)

**Comment by vertexpipeline** [comment]
I was busy. Writing...

**Comment by vertexpipeline** [comment]
@Krakean  I was busy. Writing...

**Comment by vertexpipeline** [comment]
Sorry, cannot solve it now. Have no time:/

**Comment by jkoritzinsky** [comment]
@vertexpipeline I'm going to close the PR for this for now and punt the issue. You can re-open it when you have time to work on it again.

**Comment by Gillibald** [comment]
This can be closed
