### ISSUE TITLE
MacOS version support.

### ISSUE THREAD

**Issue by rubu** [AvaloniaUI/Avalonia#1269]
With the addition of the MonoMac windowing assembly I wanted to understand the MacOS version support correctly. Since the build targets for master branch are either net461 or netstandard2.0 then the minimum MacOS version this runs on would be 10.12? Anything lower does not support .Net Core SDK so netstandard2.0 is a no go and mono has only net 4.5 so net461 also cannot be satisfied. Am I getting this right? Or are there options to use Avalonia on older MacOS versions (I am interrested un versions starting 10.9)?

**Comment by jkoritzinsky** [comment]
@kekekeks

**Comment by kekekeks** [comment]
You can use Mono 5.2. It supports net461 and netstandard20 profiles.

**Comment by kekekeks** [comment]
We are now supporting 10.12+ via .NET Core. Native library is built via 10.13 SDK and is tested on 10.12+.
