### ISSUE TITLE
Popup placement doesn't show the popup on the desire position on mobile platforms

### ISSUE THREAD

**Issue by ClayAchahui** [AvaloniaUI/Avalonia#12693]
**Describe the bug**
Popup PlacementRect and Placement is not working well on mobile plaftforms, it should show the popup in a specific position,but it is only working well on desktop.

**To Reproduce**
- Create a Popup
- Set the Placement to Placement.Pointer
- Set the PlacementRect to new AvaloniaRect with the positions where you want to show the popup.
- Open the popup.

**Expected behavior**
The popup should appear in the position that we specified.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac
- Version: 11.0.0-rc1.1

**Additional context**

**Comment by timunie** [comment]
your're using 11.0-rc1? If so, please double-check using 11.0.4. RC1 is pretty outdated.

**Comment by maxkatz6** [comment]
Is it mobile-only issue? As you mentioned "mac" platform in the description.

Strictly speaking, there is no active pointer with touch input after you remove finger from the screen, `Placement.Pointer` could have issues because of that. 
Still, the latest registered position should be used.

**Comment by maxkatz6** [comment]
Flyout repro from @ClayAchahui https://github.com/ClayAchahui/TestAvaloniaFlyoutBug

**Comment by ClayAchahui** [comment]
As I mentioned, this is only working on desktop but on mobile platforms like android and ios is not working, I executed the project on Mac machine :)

**Comment by emmauss** [comment]
This is fixed by https://github.com/AvaloniaUI/Avalonia/pull/12879
