### ISSUE TITLE
Button with bound ReactiveCommand causes loss of focus

### ISSUE THREAD

**Issue by IanRawley** [AvaloniaUI/Avalonia#12705]
**Describe the bug**
When a Button in Avalonia has a command bound to the Command property, triggering the button causes focus to vanish

**To Reproduce**

1. Clone [this repository.](https://github.com/IanRawley/ButtonFocusExperiments)
2. Run app and watch Debug output.
3. Clicking the button labeled Click should show it gain focus, and subsequent clicks/returns don't change focus.
4. Tab to the button labeled Command, and press enter.  See focus is lost, not gained by anything, and keyboard navigation no longer responds (on Windows).

**Expected behavior**
A button using a Command should not lose focus when clicked/activated.

**Desktop:**

- OS: Windows, Android (emulator)
- Version 11.0.4

**Additional context**
On Windows focus is completely lost, and the app will no longer respond to Tab until the pointer is used to return focus to the window.  The interesting thing to note is that it appears focus is lost, and then the command fires.
On Android focus is lost, but the app will still respond to Tab, setting focus to the first InputElement.  On Android the command appears to fire before focus is lost.

**Comment by IanRawley** [comment]
Looking at the stack with a breakpoint what seems to be happening is that ReactiveCommands set CanExecute to false while the command is being executed.  This is causing Avalonia to disable the button, and because a disabled button can't have focus, focus is cleared.  On Windows though Focus(null) is being too thorough, and focus is being completely lost.

```
 	ButtonFocusExperiments.dll!ButtonFocusExperiments.Views.MainView.OnLostFocus(Avalonia.Interactivity.RoutedEventArgs e) Line 26	C#
 	Avalonia.Base.dll!Avalonia.Input.InputElement..cctor.AnonymousMethod__32_1(Avalonia.Input.InputElement x, Avalonia.Interactivity.RoutedEventArgs e) Line 217	C#
 	Avalonia.Base.dll!Avalonia.Reactive.LightweightObservableBase<(object, Avalonia.Interactivity.RoutedEventArgs)>.PublishNext((object, Avalonia.Interactivity.RoutedEventArgs) value) Line 149	C#
 	Avalonia.Base.dll!Avalonia.Interactivity.EventRoute.RaiseEventImpl(Avalonia.Interactivity.RoutedEventArgs e) Line 144	C#
 	Avalonia.Base.dll!Avalonia.Interactivity.EventRoute.RaiseEvent(Avalonia.Interactivity.Interactive source, Avalonia.Interactivity.RoutedEventArgs e) Line 102	C#
 	Avalonia.Base.dll!Avalonia.Interactivity.Interactive.RaiseEvent(Avalonia.Interactivity.RoutedEventArgs e) Line 125	C#
 	Avalonia.Base.dll!Avalonia.Input.KeyboardDevice.SetFocusedElement(Avalonia.Input.IInputElement element, Avalonia.Input.NavigationMethod method, Avalonia.Input.KeyModifiers keyModifiers) Line 157	C#
 	Avalonia.Base.dll!Avalonia.Input.FocusManager.SetFocusedElement(Avalonia.Input.IFocusScope scope, Avalonia.Input.IInputElement element, Avalonia.Input.NavigationMethod method, Avalonia.Input.KeyModifiers keyModifiers) Line 148	C#
>	Avalonia.Base.dll!Avalonia.Input.FocusManager.Focus(Avalonia.Input.IInputElement control, Avalonia.Input.NavigationMethod method, Avalonia.Input.KeyModifiers keyModifiers) Line 92	C#
 	Avalonia.Base.dll!Avalonia.Input.FocusManager.ClearFocus() Line 98	C#
 	Avalonia.Base.dll!Avalonia.Input.InputElement.IsEffectivelyEnabled.set(bool value) Line 471	C#
 	Avalonia.Base.dll!Avalonia.Input.InputElement.UpdateIsEffectivelyEnabled(Avalonia.Input.InputElement parent) Line 721	C#
 	Avalonia.Base.dll!Avalonia.Input.InputElement.UpdateIsEffectivelyEnabled() Line 682	C#
 	Avalonia.Controls.dll!Avalonia.Controls.Button.CanExecuteChanged(object sender, System.EventArgs e) Line 567	C#
 	ReactiveUI.dll!ReactiveUI.ReactiveCommandBase<System.Reactive.Unit, System.Reactive.Unit>.OnCanExecuteChanged(bool newValue) Line 219	C#
 	System.Reactive.dll!System.Reactive.AnonymousSafeObserver<bool>.OnNext(bool value) Line 44	C#

...
 	System.Reactive.dll!System.ObservableExtensions.Subscribe<System.Reactive.Unit>(System.IObservable<System.Reactive.Unit> source) Line 37	C#
 	ReactiveUI.dll!ReactiveUI.ReactiveCommandBase<System.Reactive.Unit, System.Reactive.Unit>.ICommandExecute(object parameter) Line 250	C#
 	ReactiveUI.dll!ReactiveUI.ReactiveCommandBase<System.Reactive.Unit, System.Reactive.Unit>.System.Windows.Input.ICommand.Execute(object parameter) Line 135	C#
 	Avalonia.Controls.dll!Avalonia.Controls.Button.OnClick() Line 349	C#

```

**Comment by maxkatz6** [comment]
Looks like by design to me. ReactiveUI sets CanExecute to false when command is executed, we don't control that. Disabled command doesn't have a focus, we do control it.
Not sure what exactly is a bug here, and how it can be improved.

**Comment by timunie** [comment]
Please check out: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/relaycommand#handling-concurrent-executions 

fyi: It can be used side-by-side with ReactiveUI and should solve the issue. I still doubt Avalonia can do much about it.

**Comment by IanRawley** [comment]
> Looks like by design to me. ReactiveUI sets CanExecute to false when command is executed, we don't control that. Disabled command doesn't have a focus, we do control it. Not sure what exactly is a bug here, and how it can be improved.

Yeah, I can understand that.  The bug would be that on Windows triggering a button bound to a ReactiveCommand causes the entire Window to lose focus, and no longer responds to keyboard navigation because nothing has focus anymore.  As one of the main requirements for my work at the moment is being fully keyboard navigable that means I can't use command bound buttons for anything except navigation, which messes with focus anyway.

It sounds like I'm going to have to figure out how to work around focus issues related to disabling a focused button anyway to get things working nicely, but I wouldn't expect a button that prints a debug message to cause the app to completely lose focus.

**Comment by maxkatz6** [comment]
> The bug would be that on Windows triggering a button bound to a ReactiveCommand causes the entire Window to lose focus

Probably because app doesn't have anything to focus instead. Possibly, set Window.Focusable=true.

**Comment by timunie** [comment]
@IanRawley I still think you should look into alternative commands ;-). Your user also don't want the focus to move, if you need keyboard navigation.

**Comment by IanRawley** [comment]
I've been doing everything in code-behind, including using code-behind to call the reactive commands.  It's a bit of a pain, and I should look into a better way of doing it.  I'm going to have to do something to work around the focus issues either way.

I also went back and tested, and it seems the window wasn't completely losing focus, although nothing was adorned.  At least in the minimal reproduction.  So either I was imagining it, or my full project has something else going on.

Anyway, I guess I'll close this as the problem I thought I was having needs more investigation to see if it actually exists or is just me.

**Comment by timunie** [comment]
@IanRawley check CommandSamples and MVVM samples in general.
