### ISSUE TITLE
Possible bug? Actual window content depends on when `Show()` is called

### ISSUE THREAD

**Issue by BreyerW** [AvaloniaUI/Avalonia#12703]
**Describe the bug**
Depending on the order of inserting childs and customizing appearance against `Show()` call can result in very different looking window

**To Reproduce**

1. Paste in blank avalonia project one of these snippets:

```csharp
      var Item = new Window();
      Item.Show();
      Item.Content = //place any controls here
      Item.SizeToContent = SizeToContent.WidthAndHeight;
```
or
```csharp
      var Item = new Window();
      Item.Content = //place any controls here
      Item.SizeToContent = SizeToContent.WidthAndHeight;
      Item.Show();
```
3. Start project (need to do it twice, once for ech snippet
4. Observe differences between actual window renderings 

**Expected behavior**
Both snippets should look the same

**Screenshots**

early `Show()` call in my project:

![Zrzut ekranu (4)](https://github.com/AvaloniaUI/Avalonia/assets/12634170/a7c6ceaf-0bb0-46a6-8d17-d010e613802c)

late `Show()` call in my project:

![Zrzut ekranu (3)](https://github.com/AvaloniaUI/Avalonia/assets/12634170/8dd14468-130c-4fe2-b3d4-4347416ea9f8)

Note: these shots are from my actual project not from provided snippets, just to illustrate whats the problem. Both are exactly same data, exactly same steps to reproduce and exactly same code except for `Show()` call placement

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.4

Tried to find duplicate, after 10 pages worth of open bugs i gave up sorry if it is already known.

**Comment by timunie** [comment]
@BreyerW best if you can provide a very minimal sample

**Comment by BreyerW** [comment]
@emmauss  actually its the 2nd sample that went haywire despite having content before `Show()` call. But after making clean project from reinstalled and newest templates i cant reproduce it either and on old project im unable to do it too buts thats after several commits. Must have been a bug in control layout/bindings on my part as i was experimenting heavily with `ControlTheme` for `TabItem` (`TabControl`, `Grid` and `DockPanel` with some dummy `TextBox`es are practically the only controls i use currently for development). Didnt notice it since there were no errors and calling `Show()` worked without issues which was weird.  And just for the record i wasnt using Min/Max Width/Height, `Window` itself was used directly w/o XAML.

**Comment by timunie** [comment]
I'm closing this as it is not reproducible. Ping me if you found a way to reproduce.
