### ISSUE TITLE
Simple theme is missing resources for TimePicker & DatePicker

### ISSUE THREAD

**Issue by mgnslndh** [AvaloniaUI/Avalonia#12702]
**Describe the bug**
The Simple theme version 11.0.4 is missing resources related to TimePicker and DatePicker. At least the following resources are missing:

```
<Thickness x:Key="DateTimeFlyoutButtonBorderThickness">0</Thickness>
<Thickness x:Key="DateTimeFlyoutBorderThickness">1</Thickness>
<Thickness x:Key="DateTimeFlyoutBorderPadding">1</Thickness>
```

I'm not sure about the values.

**To Reproduce**

1. Create new Avalonia project with the Simple theme.
2. Add TimePicker or DatePicker.
3. Run application
4. Click on the picker to see the missing border

**Expected behavior**
I expect the Simple theme to include all resources that are referenced. I expect the control themes for TimePicker and DatePicker to be complete and following the overall Simple theme.

**Screenshots**

![DateTimePickerResources](https://github.com/AvaloniaUI/Avalonia/assets/1139118/d6c06d3d-f5e6-4998-972c-4a6b8a500af6)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 11.0.4 & 11.0.2

**Additional context**

There might be more missing resources. The ones reported are the only ones I noticed. It would be great if we could have a unit test that asserts all referenced resources are actually defined.

**Comment by timunie** [comment]
@mgnslndh a PR to fix the missing resources is welcome. If you have a good idea for a unit test, this would be really great in addition 👍
