### ISSUE TITLE
Bitmap function :  'CopyPixels'   is error

### ISSUE THREAD

**Issue by qqJoker** [AvaloniaUI/Avalonia#12721]
**Describe the bug**
CopyPixels function parameters has problem,the positions of the two parameters srcAddress and dstAddress are reversed.

**Screenshots**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 11.0.0-rc1.1]

![image](https://github.com/AvaloniaUI/Avalonia/assets/25498939/2833a607-e76f-444f-87d2-5ff5bd113412)

**Comment by timunie** [comment]
Please fill the form. It's there for a reason. 

Important: which version of Avalonia? Can you file a minimal repo to check?

**Comment by qqJoker** [comment]
I am using version 11.0.4, but I see this problem also exists under the master branch

**Comment by timunie** [comment]
Ah I see, the screenshot is from Avalonia source. So I guess if you can provide a valid fix for the mentioned issue, a PR is welcome. 

@Gillibald may have more knowledge if there is a specific reason for the order to be reversed, but I can't imagine any.

**Comment by timunie** [comment]
WAIT, it will be a breaking change. So only can be considered for 12.0. 

Sorry for the confusion 😆

**Comment by kekekeks** [comment]
CopyPixels transfers pixel data out of the image into a user-provided buffer. It is working as intended. To update bitmap contents use WriteableBitmap.
