### ISSUE TITLE
SelectionMode.AlwaysSelected isn't properly enforced when DataContext changes and SelectedItem isn't bound.

### ISSUE THREAD

**Issue by IanRawley** [AvaloniaUI/Avalonia#12733]
**Describe the bug**
When the DataContext for a SelectingItemsControl changes and SelectionMode includes AlwaysSelected, it is only properly enforced if SelectedItem is also bound to a VM.

**To Reproduce**

1. Clone [this repository](https://github.com/IanRawley/ListBoxFocusIssues), build, and run.
The two listboxes are identical apart from the one on the left binding SelectedItem to the ViewModel and the one on the right not doing so.
3. See that the first item in both ListBoxes is selected.
4. Click the "Change DataContext" Button, which produces a new VM.
5. If the newly generated list doesn't contain the old SelectedItem, the left-hand listbox will have index 0 selected, and the right-hand listbox will have nothing selected.
If the newly generated list does contain the old SelectedItem, the left-hand listbox will still have index 0 selected, while the right-hand will have the old SelectedItem selected.
6. Click the Button again.  Now both ListBoxes should have the first item selected.
7. Clicking again should have the same result as step 4, with an empty selection on the right.  The AlwaysSelected is enforced every other DataContext change.

**Expected behavior**
Even if SelectedItem is not bound to a VM, a SelectingItemsControl with SelectionMode.AlwaysSelected should always have something selected assuming there is something to select.

**Desktop (please complete the following information):**

- OS: Windows and Android (Emulator)
- Version 11.0.4

**Additional context**
This behavior has been confirmed for both ListBox and TreeView.

**Comment by timunie** [comment]
@IanRawley I think you are totally right here. So if you have a free minute, 
 1. make a Unit-test from your sample
 2. Fix the failing test
 3. Provide a PR :-)
