### ISSUE TITLE
ListBox/VirtualizingStackPanel places several items at the same "line"

### ISSUE THREAD

**Issue by pavelovcharov** [AvaloniaUI/Avalonia#12744]
**Describe the bug**
ListBox is bound to a collection of items. If items are inserted at the beginning of the collection, multiple containers may appear at the same "line" simultaneously.

**To Reproduce**
1. Clone [this repository](https://github.com/pavelovcharov/avalonia-listbox-virtualization-issue), build the solution, and run.
2. Items start to fill the ListBox
3. When scrollbars appear, scroll down, and the scroll up. You may need to repeat this a few times to reproduce the issue.

**Expected behavior**
Multiple containers shouldn't appear at the same "line" of ListBox.

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/1357165/060f9c55-d40d-4865-b688-881aff9abe18)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Version [11.0.4]

**Additional context**

**Comment by timunie** [comment]
Adding items from non ui thread is forbidden. Use Dispatch.UiThread.Post or DynmaicData for async item adding. 

This is by design.

**Comment by timunie** [comment]
Investigating the sample I still think its wise to change using the following:
- DynmaicData 
- DispatcherTimer

I can still observe the items being doubled, but this seems to be the selected item and is happening when scrolling. This needs further investigation.

**Comment by liugangnhm** [comment]
same issue

**Comment by hamster620** [comment]
Is there any progress on this issue? I found the same symptom in our project. The selection of ListBox will also be abnormal when the symptom happens.

![Screenshot 2023-10-18 213429](https://github.com/AvaloniaUI/Avalonia/assets/26860570/4eba71cd-f479-475c-b6fb-29fe0f861c34)

**Comment by timunie** [comment]
@hamster620 this is an open source project where things are done when they are done. Help is always welcome, so if you want to investigate the issue deeper, go ahead and help us solving this.

**Comment by CodeDevAM** [comment]
I am cureently not able to build Avalonia from source. So my question is: Are there debug builds available that could be used for debugging Avalonias internals?

**Comment by workgroupengineering** [comment]
> I am cureently not able to build Avalonia from source. So my question is: Are there debug builds available that could be used for debugging Avalonias internals?

Have you see https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md

**Comment by CodeDevAM** [comment]
Yes I did. But it is not working. I am still in clarification why: https://github.com/AvaloniaUI/Avalonia/discussions/13670

**Comment by CodeDevAM** [comment]
I made some tests to figure out the root cause. It seems to be related to `UseLayoutRounding` on the `ListBox`. (https://github.com/AvaloniaUI/Avalonia/issues/13607#issuecomment-1823301673)

**Comment by CodeDevAM** [comment]
The issue reoccured in my app with version 11.0.6.

**Comment by timunie** [comment]
@CodeDevAM answering closed issues doesn't help here. Better to test it against nightly. If issue reproduces, open a new issue and attach a minimal sample to reproduce.

**Comment by CodeDevAM** [comment]
Okay sorry. I thought issues could be reopened.
