### ISSUE TITLE
Missing PolyBezierSegment

### ISSUE THREAD

**Issue by JakubMarecek** [AvaloniaUI/Avalonia#12741]
I am porting a WPF app to Avalonia and found that I'm using in the app PolyBezierSegment class which unfortunately isn't available in Avalonia. There is just BezierSegment which isn't much usable because it has only 3 points whereas PolyBezierSegment can contain as many points as I want.

[PolyBezierSegment Class
](https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.polybeziersegment?view=windowsdesktop-7.0)

**Comment by timunie** [comment]
sounds like a useful extension to me. @grokys you were working on geometry improvements earlier. Do we want this feature in 11.x? 

@JakubMarecek If we get a 👍, a PR is welcome :-)

**Comment by JakubMarecek** [comment]
Nevermind, I found there are another breaking bugs in Avalonia, so I rather stick with WPF.

**Comment by timunie** [comment]
I'm reopening this as the idea is still useful. 

If you need xplat support and want to stick with WPF, we can also offer XPF. if you are interested and have some budget, reach out to the team.
