### ISSUE TITLE
Flyout is not showing on the pointer location correctly

### ISSUE THREAD

**Issue by ClayAchahui** [AvaloniaUI/Avalonia#12747]
**Describe the bug**
Flyout is not showing on the pointer location on mobile platforms.

**To Reproduce**
1. Create a Flyout
2. Set the Content
3. Call the ShowAt method setting the placement target and showAtPointer = true

**Expected behavior**
The Flyout should appear on the right location and this is appearing on the top left side of the screen.

**Desktop (please complete the following information):**
- OS: Mac
- Version 11.0.4

**Comment by maxkatz6** [comment]
I will close this issue, as it's a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/12693
Internally, there is no difference in popup placement between these controls, so it works the same
