### ISSUE TITLE
Telemetry Opt-out?

### ISSUE THREAD

**Issue by slater1** [AvaloniaUI/Avalonia#12740]
Is it possible to opt-out of build telemetry?

I set up mitmproxy to debug an Android application I am creating with Avalonia. It happened to catch some Avalonia telemetry. They all return HTTP 500. But anyway, I'd like to opt out of telemetry. I didn't know any was happening. I am sure you disclosed this somewhere (who actually reads Terms and Conditions?) but I think many would want telemetry on an open-source project to be opt-in.

![image](https://github.com/AvaloniaUI/Avalonia/assets/2089725/cd11f5ff-ce22-4c15-ba32-49b507fc98ef)

**Comment by Gillibald** [comment]
Set `AVALONIA_TELEMETRY_OPTOUT` environment variable
