### ISSUE TITLE
Mobile device soft keyboard 'Next' button does not shift focus to next input

### ISSUE THREAD

**Issue by kevkov** [AvaloniaUI/Avalonia#12758]
**Describe the bug**
Creating an Input element with attribute/value `TextInputOptions.ReturnKeyType="Next"` correctly configures the soft keyboard with a 'Next' return key but the key does shift focus to the next input.

**To Reproduce**

1. Create an Avalonia cross-platfom app: `dotnet new avalonia.xplat -o MyApp`
2. Edit the non-boileplate content of `MainView.xaml`:
```
<StackPanel>
    <TextBox TextInputOptions.ReturnKeyType="Next"></TextBox>
    <TextBox TextInputOptions.ReturnKeyType="Next"></TextBox>
</StackPanel>
```
3. Deploy to an Android or iOS emulator
4. Click in first TextBox: soft keyboard is displayed. Select 'Next' or '->|' button: input focus does not change.

**Expected behavior**
Input focus should move to the second TextBox.

**Desktop (please complete the following information):**

- OS: Windows/Android emulator, MacOS/iOS simulator
- Version 11.0.4

**Comment by maxkatz6** [comment]
Is it an expected behavior from iOS and android native apps?
IIRC, right now this property only affects visual key representation.

**Comment by timunie** [comment]
https://developer.android.com/reference/kotlin/androidx/compose/ui/text/input/ImeAction#Next()

**Comment by Gillibald** [comment]
More actions can be implemented here:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs#L622

And here:

https://github.com/AvaloniaUI/Avalonia/blob/master/src/iOS/Avalonia.iOS/TextInputResponder.cs#L182

**Comment by kevkov** [comment]
This appear to work on Android:
```csharp
                case ImeAction.Next:
                    {
                        var focusedElement = FocusManager.GetFocusManager(_toplevel.InputRoot).GetFocusedElement();
                        KeyboardNavigationHandler.GetNext(focusedElement, NavigationDirection.Next)?.Focus();
                        break;
                    }
```

but I am complete noob to all of this.
