### ISSUE TITLE
ComboBox width set

### ISSUE THREAD

**Issue by mzy666888** [AvaloniaUI/Avalonia#12762]
**Describe the bug**
the textbox and combobox display in `border`. but the property `width`  display is different

**To Reproduce**
```
<Grid>
	<Grid.RowDefinitions>
		<RowDefinition Height="Auto" />
		<RowDefinition Height="Auto" />
	</Grid.RowDefinitions>
	<Border Margin="3">
		<TextBox Margin="4">
		</TextBox>
	</Border>
	<Border Grid.Row="1" Margin="3">
		<ComboBox Width="100" Margin="4">
		</ComboBox>
	</Border>
</Grid>
```
1. add upside code to  usercontrol 
2.  design window show different 
3.  `F5` run to show 
![image](https://github.com/AvaloniaUI/Avalonia/assets/2587129/1b73c4e6-8ef2-4e49-b7e1-13bd4a8584c2)

5. See error

**Expected behavior**
I think the `combobox` width should the same the `textbox` in the same control `border`.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 
- Version 11.0.4

**Additional context**

**Comment by timunie** [comment]
This is by design. ComboBox has HorizontalAlignment set to Left. Set it to Stretch and remove the Width property you defined and you are done.

**Comment by mzy666888** [comment]
> This is by design. ComboBox has HorizontalAlignment set to Left. Set it to Stretch and remove the Width property you defined and you are done.

it's  right!
