### ISSUE TITLE
Web canvas expects to be in the top left corner, if not, causes a mouse click offset bug

### ISSUE THREAD

**Issue by zborowa** [AvaloniaUI/Avalonia#12780]
**Describe the bug**

Embedding the canvas or offsetting the canvas causes the mouse click not to be registered appropriately. In the following demo I've embedded the Ava div out in an Angular app and added a couple of `<br/>` elements before the div out element. As you can see the mouse click events are then not registered properly. It seems that the canvas looks at the mouse position from the top left corner of the viewport and not the canvas.

![ava-canvas-button-in-angular-app](https://github.com/AvaloniaUI/Avalonia/assets/2786784/e836eca3-3ea8-451a-9d70-42a94a04fa0d)

```html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>AngularAvalonia</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href="favicon.ico">

  <!-- Avalonia resources -->
  <link rel="modulepreload" type="application/javascript" href="./AppBundle/main.js" />
  <link rel="modulepreload" type="application/javascript" href="./AppBundle/dotnet.js" />
  <link rel="modulepreload" type="application/javascript" href="./AppBundle/avalonia.js" />
  <link rel="stylesheet" href="./AppBundle/app.css" />
</head>
<body>
  <br/><br/><br/><br/><br/><br/>

  <!-- Avalonia main div -->
  <div id="out" style="height: 500px;">
    <div id="avalonia-splash">
        <div class="center">
            <h2>
                Loading...
            </h2>
        </div>
    </div>
</div>

  <!-- Angular main component -->
  <app-root></app-root>

  <!-- Avalonia resources -->
  <script type='module' src="./AppBundle/main.js"></script>
</body>
</html>
```

**To Reproduce**

Embed the Avalonia app with additional margin or <br/> before the element. Not setting the margin to 0 on the body has a similar effect but just less recognizable.

**Expected behavior**

Track mouse position from the left top canvas corner.

**Desktop (please complete the following information):**

- OS: browser
- Version: 11.0.4

**Additional context**

I'm trying to figure out how to approach embedding Avalonia pages/elements in an Angular application for a page by page basis transition from Angular to Avalonia. Ideally speaking I would like to embed Avalonia pages in any div I want to have full control over the pages look, feel and position.

Spawned from conversation on how to approach Avalonia application embedding in other web apps, https://github.com/AvaloniaUI/Avalonia/discussions/12755.

**Comment by maxkatz6** [comment]
It took me a while, but after trying to fix this issue, I found that it works as it should.
The problem with your specific use case is that you missed `position:absolute` on the out element (relative should also work). The reason is that child controls inside of the `out` element use `position:absolute` relatively to the parent element that also has to be either absolute or relative (or flex as I believe).
