### ISSUE TITLE
Invalid selection rectangle size for ListBoxItem when using keyboard up/down keys

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1278]
Version: 0.5.2-build4248-alpha

Repro:
![2017-11-14_18-05-58](https://user-images.githubusercontent.com/2297442/32793604-b884113e-c966-11e7-918d-2300eac6b02a.gif)

**Comment by jkoritzinsky** [comment]
I think this is from the `AdornerLayer` not passing the clip rectangle to the adorning element. So for elements that extend out of bounds (possibly clipped by ClipToBounds), their adorner extends to their actual bounds.

**Comment by grokys** [comment]
This should have been fixed by #1350. Closing, please comment if it's still a problem and I'll reopen.
