### ISSUE TITLE
Pixelated image rendering regression in 11.0.2 and 11.04

### ISSUE THREAD

**Issue by hhyyrylainen** [AvaloniaUI/Avalonia#12786]
**Describe the bug**
The following issue is happening again: https://github.com/AvaloniaUI/Avalonia/issues/11319 so I'm opening a new issue to point out the regression.

**To Reproduce**

1. Add an Image with a size much smaller than the native resolution of the image
2. Don't add the manual fix which should have been set as the default in Avalonia according to #11319  (`RenderOptions.BitmapInterpolationMode="HighQuality"`)
3. Run the program and see the image have a lot of jagged / pixelated edges

**Expected behavior**
According to that closed issue this should be fixed, but apparently the problem is back.

**Screenshots**
Here's how my example project looks without manually setting that option that shouldn't be necessary:

![Kuvakaappaus - 2023-09-05 11-07-18](https://github.com/AvaloniaUI/Avalonia/assets/3796411/30dc4c58-3121-420e-8342-73523fc75545)

And here it is when I manually put in that workaround:

![Kuvakaappaus - 2023-09-05 11-08-25](https://github.com/AvaloniaUI/Avalonia/assets/3796411/3a94a545-bfec-4bf7-8733-dc480961af91)

The difference is slight but I can't unsee it in my real Avalonia application where multiple buttons with icons on them now look bad in comparison to how they should look.

**Desktop (please complete the following information):**

- OS: Linux
- Version 11.0.2 and 11.04 both show this issue (11.0.2 is the current version used by the templates)

**Additional context**
This is a sample project showing the problem, I just used the new avalonia.mvvm template and did just the few changes needed to add the image file and code to display it:

[AvaloniaImageTest.zip](https://github.com/AvaloniaUI/Avalonia/files/12520765/AvaloniaImageTest.zip)

**Comment by hhyyrylainen** [comment]
I was under the impression after reading the discussion in #11319 that the default value was supposed to be fixed back to what it was in Avalonia in 0.x versions (i.e. high quality)... But reading the PR #11397 makes low quality the default option, which looks worse than in previous Avalonia versions.

**Comment by hhyyrylainen** [comment]
That'd be a pretty good option as long as the Avalonia documentation mentions that in some sensible place. For example the Image control could have a short warning section explaining that scaling big images down a lot will not look good without an extra setting. Otherwise I doubt people would actually find that (it took me a bit of searching to find that existing issue about this) and have to resort to workarounds for the image drawing. 

That'd be the second best option in my opinion after doing the right thing by default, which was what Avalonia did before version 11. Is there a big performance impact from this or what's the reason with the change to the default? I find that maybe some other performance thing like not constantly looping the X11 messages when there's nothing to receive would save a lot more CPU time in a long running application...

**Comment by wieslawsoltes** [comment]
> RenderOptions.BitmapInterpolationMode="HighQuality

@Gillibald Would be nice if I could set this via style but I get error `Writable property is expected`:
![image](https://github.com/AvaloniaUI/Avalonia/assets/2297442/81d50385-fe36-4aa2-926f-de65c4070ac9)

**Comment by timunie** [comment]
After internal discussion this is by design and need to be set per each root control. This is done on purpose for performance overhead. A behavior or custom attached properties should still be possible to add in your own library. 

Will open an issue to reflect that in the docs.
