### ISSUE TITLE
WASM multitasking / multithreading needed

### ISSUE THREAD

**Issue by MarkBrainfire** [AvaloniaUI/Avalonia#12785]
Background asynchronous tasks work great on desktop and Android, but seem to be missing on WASM.

This is needed so that computationally intense tasks don't interfere with the UI thread.

Is support for awaitable tasks using Task.Run() => etc. being implemented?

**Comment by kekekeks** [comment]
It's currently blocked by the lack of support from .NET.

We are waiting for .NET 8 release and updated SkiaSharp.

**Comment by maxkatz6** [comment]
It is possible to use threads in .NET 8 by adding `<WasmEnableThreads>true</WasmEnableThreads>`:
```
                   Console.WriteLine("Thread ID {0}", Thread.CurrentThread.ManagedThreadId);
                   await Task.Run(() =>
                   {
                       Console.WriteLine("Thread ID {0}", Thread.CurrentThread.ManagedThreadId);
                       while (true)
                       {
                           Thread.Sleep(100);
                           Console.WriteLine("Thread ID {0}", Thread.CurrentThread.ManagedThreadId);
                       }
                   });
```

This code will work fine without blocking main thread.
