### ISSUE TITLE
Add CombinedGeometry or GeometryGroup classes

### ISSUE THREAD

**Issue by jkoritzinsky** [AvaloniaUI/Avalonia#1279]
Add a CombinedGeometry class and/or GeometryGroup similar to WPF's implementations so users can combine geometries without switching to `PathGeometry`.

**Comment by na2axl** [comment]
Hello, There are any update on this feature ?

**Comment by desneill** [comment]
I would also be very interested to know.  We are currently working on an app to display vector charts and have run into this as a blocker

**Comment by kekekeks** [comment]
There is an on switching on a new composition engine, so changes to the rendering infrastructure are frozen for the time being.
But I will put combined geometries on my TODO list for said engine.

**Comment by desneill** [comment]
Nikita

 

Do you know when this might be ?   

 

Is this something we could sponsor?

 

 

 

Regards,

 

Des Neill

Director

 

eMail  <mailto:des@jargoon.co.uk> des@jargoon.co.uk 

Switch +44 (0) 1224-213-388

Direct +44 (0) 1224-213-338

Mobile +44 (0) 7920-154-203

----------------------------------------------------------------------------
----------------------------------

Jargoon Ltd  Torridon House, 73-75 Regent Quay, Aberdeen, Scotland, AB11 5AR

----------------------------------------------------------------------------
----------------------------------

Website
<https://t.sidekickopen82.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX4
8q-c8PW5vfQyH2zqjtWW3LyyXR56dxWpf3xDrmb02?te=W3R5hFj26QkHmW4mKDt03zgD15W43Tw
8L43m_191V3&si=4792694832496640&pi=4f440279-3728-434a-9dd3-7ec007af9f5c>
www.jargoon.co.uk

Blog
<https://t.sidekickopen82.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX4
8q-c8PW5vfQyH2zqjtWW3LyyXR56dxWpf3xDrmb02?te=W3R5hFj26QkH6W3zgD1543TBLqW43QB
Sj3ZZn7kW45SBgq3FbmCt348Q2&si=4792694832496640&pi=4f440279-3728-434a-9dd3-7e
c007af9f5c> jargoonblog.blogspot.co.uk

 

Please consider the environment - only print this e-mail if absolutely
necessary

Jargoon Limited, Registered in Scotland No 289791, VAT 98444777

Registered Office, 1 Station Park, Gourdon, Aberdeenshire, Scotland, DD10
0NF

 

The information contained in this e-mail may contain confidential or
privileged material and is intended only for the stated addressee(s). If you
are not a valid addressee, the use, disclosure, copying or distribution of
this information is prohibited and may be unlawful.  If you have received
this message in error, please notify the sender immediately and delete all
copies of the message from your computer. All information or opinions
expressed in this message and/or any attachments are those of the author and
are not necessarily those of Jargoon.

**Comment by RomanSoloweow** [comment]
@kekekeks Is there any news on this issue?

**Comment by grokys** [comment]
I'm working on this now.

**Comment by desneill** [comment]
Steven

 

This is brilliant news and thankyou very much for getting back to us.  Can you let me know then there I something I can try out please. 

 

 

 

Regards,

 

Des Neill

Director

 

eMail  ***@***.***> ***@***.*** 

Switch +44 (0) 1224-213-388

Direct +44 (0) 1224-213-338

Mobile +44 (0) 7920-154-203

--------------------------------------------------------------------------------------------------------------

Jargoon Ltd  Torridon House, 73-75 Regent Quay, Aberdeen, Scotland, AB11 5AR

--------------------------------------------------------------------------------------------------------------

Website  <http://www.jargoon.co.uk/> www.jargoon.co.uk

Blog  <http://jargoonblog.blogspot.co.uk/> jargoonblog.blogspot.co.uk

 

Please consider the environment – only print this e-mail if absolutely necessary

Jargoon Limited, Registered in Scotland No 289791, VAT 98444777

Registered Office, 1 Station Park, Gourdon, Aberdeenshire, Scotland, DD10 0NF

 

The information contained in this e-mail may contain confidential or privileged material and is intended only for the stated addressee(s). If you are not a valid addressee, the use, disclosure, copying or distribution of this information is prohibited and may be unlawful.  If you have received this message in error, please notify the sender immediately and delete all copies of the message from your computer. All information or opinions expressed in this message and/or any attachments are those of the author and are not necessarily those of Jargoon.

**Comment by grokys** [comment]
@desneill the pull request is here: https://github.com/AvaloniaUI/Avalonia/pull/6576

Hopefully will be part of 0.10.8.
