### ISSUE TITLE
CI on linux

### ISSUE THREAD

**Issue by Mafii** [AvaloniaUI/Avalonia#1280]
Right now only windows and mac are tested by your CI, adding linux would give you another layer of assurance that it works and the builds are alright.

Is there a reason that it has not been configured yet?

**Comment by jkoritzinsky** [comment]
We are currently testing on Windows and Linux. The mac image on Travis was really unstable so we turned it off.

**Comment by Mafii** [comment]
Thanks for the feedback. that's understandable.
