### ISSUE TITLE
nth-child can't target ListBox content (children of ListBoxItem)

### ISSUE THREAD

**Issue by MihaMarkic** [AvaloniaUI/Avalonia#12838]
**Describe the bug**
For some reason I can't use nth-child to target ListBoxItem's child(ren).

**To Reproduce**
```xaml
<ListBox ItemsSource="{Binding Data, Mode=OneWay}">
        <ListBox.Styles>
            <Style Selector="ListBox > ListBoxItem:nth-child(odd) > TextBlock">
                <Setter Property="FontSize" Value="40" />
                <Setter Property="Foreground" Value="Red" />
            </Style> 
        </ListBox.Styles>
        <ListBox.ItemTemplate>
            <DataTemplate>
                <TextBlock Text="{Binding}"></TextBlock>
            </DataTemplate>
        </ListBox.ItemTemplate>
    </ListBox>
```

Bind something to ListBox, i.e.
```csharp
public List<int> Data { get; } = new List<int>( Enumerable.Range(0, 10));
```

Run it, nothig is applied to TextBlocks within ListBoxItem.
If I remove nth-child selector, style is applied correctly (to all elements, of course).
Also tried to apply nth-child selector to ListBoxItem (I suppose it should work as well?) but the result is the same - nothing is applied.
If using selector `ListBox > ListBoxItem:nth-child(odd)` then it works, but I can't apply FontSize.

**Expected behavior**
I'd expect style to be applied to odd TextBlocks.

**Desktop (please complete the following information):**

- OS: macOS
- Version 11.0.4

**Additional context**
Is this a bug or am I doing it incorrectly?

EDIT: Corrected wrongly written selector

**Comment by maxkatz6** [comment]
> `ListBox > ListBoxItem > TextBlock:nth-child(odd)`

This one definitely won't work. ListBoxItem can possibly only have a single child, there is nothin `odd` to it.

> `ListBox > ListBoxItem:nth-child(odd) > TextBlock`

This should work. No idea why it doesn't for you.

> but I can't apply FontSize.

Adding `<Setter Property="FontElement.FontSize" Value="40" />` should be properly inherited even from ListBox I think.

**Comment by MihaMarkic** [comment]
> > `ListBox > ListBoxItem > TextBlock:nth-child(odd)`
> 
> This one definitely won't work. ListBoxItem can possibly only have a single child, there is nothin `odd` to it.

Ha, good one. You are right, that couldn't work. My mistake (bad paste), it was meant to be `ListBox TextBlock:nth-child(odd)`. This one should work, right?

> > `ListBox > ListBoxItem:nth-child(odd) > TextBlock`
> 
> This should work. No idea why it doesn't for you.

Did you try my sample or talking from experience? I'm curious if that code actually works for you.

> > but I can't apply FontSize.
> 
> Adding `<Setter Property="FontElement.FontSize" Value="40" />` should be properly inherited even from ListBox I think.

Right, I think it's `TextElement`. I've tried this
```xaml
<Style Selector="ListBox > ListBoxItem">
                <Setter Property="TextElement.FontSize" Value="50" />
                <Setter Property="Foreground" Value="Red"></Setter>
```
but it still doesn't apply the FontSize setter. It applies Foreground though.

**Comment by timunie** [comment]
Is TextBlock a direct child? Otherwise omit the last > as it mean direct child. Having just a space matches any child

**Comment by MihaMarkic** [comment]
@timunie See my first post (in that sample selector is wrongly written though, but it shows ListBox content). Yes, it's a direct child and my selectors seem to work until I use nth-child on ListBoxItem.

**Comment by timunie** [comment]
Which style do you use?

**Comment by timunie** [comment]
Fluent or simple?

**Comment by timunie** [comment]
checking visual tree using DevTools it is not a direct child but: 
![image](https://github.com/AvaloniaUI/Avalonia/assets/47110241/f9b4db65-2e59-4c2b-9d82-8dccdae2b350)

this seems to work for me: 
```xml
<Style Selector="ListBoxItem:nth-child(odd) /template/ ContentPresenter#PART_ContentPresenter">
    <Setter Property="TextElement.FontSize" Value="40" />
    <Setter Property="TextElement.Foreground" Value="Red" />
</Style> 
```

**Comment by MihaMarkic** [comment]
Using the one from Avalonia template - `FluentTheme`.

And yes, your solution works ... almost. I'm seeing style applied only after I hover mouse pointer over the item. If I merely run the app, no style is applied. Does it work differently for you? (I'm on macOS if that matters), will try it on Windows as well.

Furthermore, I don't like it that much, because:
a) it is complicated
b) documentation explicitly mentions that style selectors work over logical tree, not visual (perhaps docs are wrong, but see next point)
c) if I omit nth-child selector, style is properly applied to logical tree `ListBoxItem > TextBlock`. That would imply it works over logical tree after all.

I still thinks `nth-child` style selector has issues.

**Comment by timunie** [comment]
that's why I accessed the /template/ thing. But yeah, didn't investigate it in deep. You are right, only after hover it gets applied. So let's wait for @maxkatz6 to give a feedback on it.

**Comment by MihaMarkic** [comment]
Same (unsurprisingly) behavior on Windows - style is applied only when pointer is over the item.

**Comment by MihaMarkic** [comment]
Looking at sources, it seems that VirtualizingStackPanel._realizedElements is always a single ListBoxItem instance and its IndexFromContainer always returns -1.

**Comment by MihaMarkic** [comment]
Indeed, switching to `StackPanel` as `ItemsPanel` instead of `VirtualizingStackPanel` produces expected effect.
@maxkatz6 Is this by design, or is there something fundamentally wrong with virtualization in this context?

**Comment by MihaMarkic** [comment]
Digging some more and learning about selectors. It seems like a "timing" issue. It wrongly works like this:

1. nth selector for first `ListBoxItem` is created.
2. `EvaluateIsActive()` is called, but it doesn't find its `_control` among children.
3. `ChildIndexChanged` is called, however with the next `ListBoxInstance`, so it isn't processed.
4. goto 1 with next index

It looks like nth selector is too early to query for index and too late to catch `ChildIndexChanged` event. Probably because _realizedElements is assigned too late.

**Comment by timunie** [comment]
If you have any idea how to fix acc to your findings, please file a PR 🙏

**Comment by MihaMarkic** [comment]
I wish. Smells to me like a nasty problem to solve because any change of this process could break like a zillion of dependent code. But if I find a solution, I'll most certainly create a PR.

**Comment by MihaMarkic** [comment]
I'm also not sure that this will work properly even if the core problem is fixed. Looking at `VirtualizingStackPanel.IndexFromContainer` method it returns index withing `_realizedElements`. Which means if VSP realized elements from, let's say, 1-3, the index of element 1 will be 0, not 1.

**Comment by MrJul** [comment]
Thanks for digging into this @MihaMarkic, it helped shave time understanding the issue!
See #12957 for a potential fix.

**Comment by MihaMarkic** [comment]
@MrJul Awesome, both fixes are working on my test sample.

**Comment by maxkatz6** [comment]
Okay, so there was nothing wrong with styling, but ListBoxItem itself has it hardcoded. Good to know.
