### ISSUE TITLE
DynamicResource in code-behind does not take effect for SolidColorBrush.

### ISSUE THREAD

**Issue by liwuqingxin** [AvaloniaUI/Avalonia#12854]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/12847

<div type='discussions-op-text'>

<sup>Originally posted by **liwuqingxin** September 10, 2023</sup>
### Senario
I want to create a **color resource** and a **brush resource** from code. And I have checked the #4616.

- Firstly, I create the color resource whose key is '**ColorFromCodeBehind**' and add it to the styles's resources.
- Then, I create a SolidColorBrush object and bind it's ColorProperty to DynamicResourceExtension("**ColorFromCodeBehind**").
- At last, I add the styles object to the App's styles.

### Problem
The problem is the brush can not get the color dynamicly. 
> Note that the color resource does take effect. The brush that references to it in axaml performs well.

```csharp
public partial class App : Application
{
    public override void Initialize()
    {
        AvaloniaXamlLoader.Load(this);

        BuildResource();
    }

    private void BuildResource()
    {
        var styles = new Styles();

        var color = Color.Parse("Red");
        var dic = new ResourceDictionary();
        styles.Resources.MergedDictionaries.Add(dic);
        dic.Add("ColorFromCodeBehind", color);

        // Create the brush resource.
        var brush = new SolidColorBrush
        {
            [!SolidColorBrush.ColorProperty] = new DynamicResourceExtension("ColorFromCodeBehind")
        };
        dic.Add("BrushFromCodeBehind", brush);

        // Create a brush resource that binds to a Color resource defined in the axaml.
        var brush2 = new SolidColorBrush
        {
            [!SolidColorBrush.ColorProperty] = new DynamicResourceExtension("ColorFromXaml")
        };
        dic.Add("BrushFromCodeBehindButColorFromXaml", brush2);

        this.Styles.Add(styles);
    }
}

```

### Result

![image](https://github.com/AvaloniaUI/Avalonia/assets/20198528/566d989b-bd1a-449e-a021-75d6a8772b4d)

### Sample

[Avalonia.DynamicResource.Desktop.zip](https://github.com/AvaloniaUI/Avalonia/files/12568433/Avalonia.DynamicResource.Desktop.zip)

Any suggustions would be appreciated! 😄 </div>

// End for Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/12847.

---

### Issue
I overcame it by setting the DynamcResourceExtension.**_anchor** to Application.Current. It is not a stable way for that. 

**IMPORTANT** ❓  So is there any issue for the DynamicResourceExtension? Or some public api for setting anchor should be provided?

**Comment by liwuqingxin** [comment]
@jp2masa Hi, there, how to get a service provider for that?

**Comment by jp2masa** [comment]
I think you have to implement the interface.

**Comment by liwuqingxin** [comment]
Hi, @timunie , wait a minute please. If I have not a ResourceDictionary reference in the context that should do the binding. How can I do it?

**Comment by timunie** [comment]
without a resource dictionary at all, I guess there is no good way. In that case better to write a class that implements `INPC` and bind to that.

**Comment by timunie** [comment]
INotifyPropertyChanged

**Comment by liwuqingxin** [comment]
> actually, you can simply do:
> 
> ```cs
> var brush = new SolidColorBrush
> {
>     [!SolidColorBrush.ColorProperty] = dic.GetResourceObservable("TestColor").ToBinding()
> };
> 
> // or
> 
> brush.Bind(SolidColorBrush.ColorProperty,  dic.GetResourceObservable("TestColor"));
> ```

Performs well for me. Thank you @timunie, and @jp2masa too.
