### ISSUE TITLE
AvaloniaPropertyAnalyzer entering infinite loop in the wild

### ISSUE THREAD

**Issue by davkean** [AvaloniaUI/Avalonia#12864]
**Describe the bug**
Hey folks, I'm from the Visual Studio perf & reliability team at Microsoft, we've detected a situation where AvaloniaPropertyAnalyzer.ResolveOperationTarget appears to be entering an infinite loop, consuming upwards of 6 CPU cores forever.

This was caught using our new CPU telemetry system, which I've described here: https://twitter.com/davkean/status/1672295235026829312.

We've caught this 5 times over the past 30 days.
```
 Microsoft.CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<TryProcessSymbolDeclaredAsync>d__137.MoveNext()
+ Microsoft.CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1[Microsoft.CodeAnalysis.CSharp.SyntaxKind].ExecuteDeclaringReferenceActions(class Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent,class Microsoft.CodeAnalysis.Diagnostics.AnalysisScope,bool,class IGroupedAnalyzerActions,value class System.Threading.CancellationToken)
 + Microsoft.CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1[Microsoft.CodeAnalysis.CSharp.SyntaxKind].ExecuteDeclaringReferenceActions(class Microsoft.CodeAnalysis.SyntaxReference,class Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent,class Microsoft.CodeAnalysis.Diagnostics.AnalysisScope,class GroupedAnalyzerActions,class GroupedAnalyzerActions,bool,bool,bool,bool,bool,value class System.Threading.CancellationToken)
  + Microsoft.CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1+<>c__DisplayClass11_0[Microsoft.CodeAnalysis.CSharp.SyntaxKind].<ExecuteDeclaringReferenceActions>g__executeExecutableCodeActions|2()
   + Microsoft.CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1+<>c__DisplayClass11_0[Microsoft.CodeAnalysis.CSharp.SyntaxKind].<ExecuteDeclaringReferenceActions>g__executeOperationsActionsByKind|5(value class System.Collections.Immutable.ImmutableArray`1,class GroupedAnalyzerActions,bool)
    + Microsoft.CodeAnalysis!AnalyzerExecutor.ExecuteOperationActions
     + Microsoft.CodeAnalysis!AnalyzerExecutor.ExecuteOperationActions
      + Microsoft.CodeAnalysis!AnalyzerExecutor.ExecuteOperationAction
       + Microsoft.CodeAnalysis!AnalyzerExecutor.ExecuteAndCatchIfThrows
        + Microsoft.CodeAnalysis!AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock
         + Microsoft.CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor+<>c.<ExecuteOperationAction>b__50_0(value class System.ValueTuple`2,value class Microsoft.CodeAnalysis.Diagnostics.OperationAnalysisContext>)
          + Avalonia.Analyzers!Avalonia.Analyzers.AvaloniaPropertyAnalyzer+CompileAnalyzer.AnalyzePropertyWrapperAssignment(value class Microsoft.CodeAnalysis.Diagnostics.OperationAnalysisContext)
           + Avalonia.Analyzers!AvaloniaPropertyAnalyzer.ResolveOperationTarget
```

**To Reproduce**
There is no repro, this was caught using telemetry. We do not have access to the user's code they were writing when this hit.

**Expected behavior**
To not enter an infinite loop.

**Screenshots**
Here is a Visual Studio session where ServiceHub.RoslynCodeAnalysisService.exe consumed 3 cores over the period of approx 22 hours. We automatically recorded a trace within this period, and found that all 3 cores were consumed by the above stacks running on 3 different threads.
![image](https://github.com/AvaloniaUI/Avalonia/assets/1103906/0d8a1845-0ced-4a9f-985a-75b5f9f06276)

![image](https://github.com/AvaloniaUI/Avalonia/assets/1103906/72961313-d359-45b0-8114-d182c6aef21c)

**Desktop (please complete the following information):**

- OS: Windows
- Version: 22621.1.amd64fre.ni_release.220506-1250 (This is from one trace, OS version likely isn't relevant but if it is, I can manually retrieve this from all traces)

**Additional context**
We don't believe that Visual Studio version matters, but we see one hit in all the following versions:

<img width="830" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/1103906/e03b6693-a3db-42b3-9e3c-de199e32e133">

**Comment by timunie** [comment]
avalonia version used would be interesting I guess.

**Comment by davkean** [comment]
In one session it appears to be 11.0.2.0, but the version appears to be not relevent as the code for this method has not changed since it was merged: https://github.com/AvaloniaUI/Avalonia/commit/2b68e42e31a2e92bae7e12f01931317f0d652d95.

**Comment by timunie** [comment]
thx for pointing that out. 

/cc @TomEdwardsEnscape fyi as you seem to be the author of this area

**Comment by TomEdwardsEnscape** [comment]
Thanks for the report, David. Is there a place where we can see this information ourselves? I'd like to be able to view crash reports too.

**Comment by davkean** [comment]
Unfortunately, this data is only available to Microsoft.

**Comment by davkean** [comment]
@TomEdwardsEnscape I want to add some clarification to what you called out in the fix. We sample our collections (between 1-5% of actual hits) and there is pipeline loss, so hit counts are not comparable against download counts. This telemetry is also new for 17.6 so we have no insight into prior versions before this. Its very likely that significantly more 5 customers hit this.
