### ISSUE TITLE
Animatable: subscriptions to Transitions collection are leaked

### ISSUE THREAD

**Issue by DmitryZhelnin** [AvaloniaUI/Avalonia#12860]
**Describe the bug**
The subscription to collection changes made in `OnPropertyChangedCore` method doesn't take into account whether the control was attached to visual tree or not.

https://github.com/AvaloniaUI/Avalonia/blob/050ae370ad02f90b237ce27c869343e628030465/src/Avalonia.Base/Animation/Animatable.cs#L126-L126

For example, you have `TabControl` with two `TabItem`s and the second tab contains a `Button`. But you never activate the second tab and later detach the whole  `TabControl` from visual tree. In this scenario the subscription is made when the `Button` is created but since this `Button` was never attached to visual tree there is no unsubscription when parent control is detached. So the whole parent control can not be garbage collected.

**To Reproduce**
- MainWindow.axaml
```xaml
<Grid RowDefinitions="Auto *">
  <Button Grid.Row="0" Content="Update content" Click="Button_OnClick" />
  <ContentControl Grid.Row="1" Name="contentControl" />
</Grid>
```

- MainWindow.axaml.cs
```cs
private void Button_OnClick(object sender, RoutedEventArgs e)
{
    contentControl.Content = contentControl.Content is null ? new TabbedContent() : null;
}
```

- TabbedContent.axaml
```xaml
<TabControl>
  <TabItem Header="First Item">
    <TextBlock Text="First" />
  </TabItem>
  <TabItem Header="Second Item">
    <Button Content="Second" />
  </TabItem>
</TabControl>
```

1. Click `Update content` button multiple times
2. Force GC and take memory dump
3. See count of `TabbedContent` controls in the memory dump

**Expected behavior**
Detached instances are garbage collected.

**Screenshots**
![изображение](https://github.com/AvaloniaUI/Avalonia/assets/4993430/0e344e42-9411-49f9-9a66-74c35aa2eb05)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.4

**Comment by hamster620** [comment]
I just faced the same issue these days which cause Window leakage in our application.
