### ISSUE TITLE
Autogenerated InitializeComponent() fucks up!

### ISSUE THREAD

**Issue by DrDryg** [AvaloniaUI/Avalonia#12888]
**Describe the bug**
I downloaded a project that basically just overload a Border to a CustomBorder. It worked, but then I updated the Avalonia version from 0.10.4 to 11.0.4. Then I get that there are two definitions of InitializeComponent in my MainWindow:

```
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
    }
}

```
But the code is autogenerated on the fly I suppose. Cannot se any files, but has noted that before. 
 
**To Reproduce**
Download this project (https://github.com/Abdesol/MovableControl/tree/main) and upgrade to latest avalonia.

Ive had this issue a few more times for other projects. But randomly changing some namespaces seemed to get it working again. But Im not sure exactly what I did, very new to Avalonia. Im using visual studio 2022 with the Avalonia xml extension. Some test projects I basically have needed to scarp since I cannot get them working after making some mistake and the code cannot get back to its original state even if I change everything back to how it started.

Error output: 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0111	Type 'MainWindow' already defines a member called 'InitializeComponent' with the same parameter types	MovableControl	C:\Users\ander\Downloads\MovableControl-main\MovableControl-main\src\Avalonia.NameGenerator\Avalonia.NameGenerator.AvaloniaNameSourceGenerator\MovableControl.Views.MainWindow.g.cs	19	Active
Error	CS0121	The call is ambiguous between the following methods or properties: 'MainWindow.InitializeComponent(bool, bool)' and 'MainWindow.InitializeComponent(bool, bool)'	MovableControl	C:\Users\ander\Downloads\MovableControl-main\MovableControl-main\src\Views\MainWindow.axaml.cs	9	Active
 

**Expected behavior**
Ideally that an upgrade works. And if not, that there is something one can do to correct the autogenerated code.

**Desktop (please complete the following information):**

- Win 11

**Additional context**

**Comment by jp2masa** [comment]
Point 3 in the [upgrade guide - Updating the project](https://docs.avaloniaui.net/docs/next/stay-up-to-date/upgrade-from-0.10#updating-the-project)?

> Remove the package reference to `XamlNameReferenceGenerator` - Avalonia now includes an inbuilt generator by default

**Comment by DrDryg** [comment]
Thanks, had missed that one.
