### ISSUE TITLE
Review two way binding behaviour

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#1289]
Currently, if a control property is bound to a view model property, the property getter is called, then the setter is called with the value which was returned from the getter and then the getter is called again.
On WPF, the setter is only called if the control property was changed.
I have a method which is called by the view model property setter, and I want to call the method only if the control property changed.

## Example

There's a `TextBox` and the `Text` property is bound to a property in the view model, called `MyProperty`.
In Avalonia, the getter of `MyProperty` is called, which returns "", then the setter is called with value "", and then the getter is called again. After that, the setter is called when the property changes.
In WPF, the getter of `MyProperty` is called, and the setter is called only if the control property changes.

**Comment by jkoritzinsky** [comment]
This might be fixed as a side effect of #856. I'll verify when I've got some free time.
