### ISSUE TITLE
Font information API

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#129]
At least `FontFamily.LineSpacing` and `UnderlinePosition`

**Comment by grokys** [comment]
Could you give more details about this? Where should it be made available, on `FormattedText`?

**Comment by kekekeks** [comment]
Separate classes for Font and FontFamiliy. Just like in WPF.

**Comment by jmacato** [comment]
I'd like to suggest this library https://github.com/LayoutFarm/Typography for our future Font API, it seems quite advanced and it's all netstandard & pure c#.

**Comment by kekekeks** [comment]
Seems to cover our needs, but the problem is that we need to somehow integrate it with existing Skia and Direct2D rendering pipelines.

**Comment by kekekeks** [comment]
PixelFarm, however, seems to be a suitable rendering engine for running Avalonia in WebAssembly. Thanks for the link.

**Comment by jmacato** [comment]
You're welcome @kekekeks  :) However, to put it bluntly, we should probably reorganize/refactor PixelFarm, their code is organized horribly and the tons of license headers will not fit the coding style of Avalonia. But that's just me being petty. I'm hoping that this library could unify the look of texts/fonts in Avalonia across devices when we do use it.

**Comment by jmacato** [comment]
Another potentially useful library for our future Text Metrics and Font API : https://github.com/SpacialCircumstances/SharpFont ; It is purely c# and outputs the glyph data and the relevant kerning data and other cool stuff

**Comment by Gillibald** [comment]
Implemented by #3195
