### ISSUE TITLE
Skia: Unable to Load bitmap from Memory Stream

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1290]
Easy to repro:

```
var bitmap = new Bitmap("jpegfile.jpg");
var imgStream = new MemoryStream();
bitmap.Save(imgStream);
var bitmapfromstream = new Bitmap(imgStream);
```

throws an exception on Skia, but works on Direct2D.

I had a feeling it could be related to:
https://github.com/mono/SkiaSharp/issues/335 but upgrading didnt seem to fix it.

**Comment by kekekeks** [comment]
You are trying to load the bitmap from the end of stream. Obviously, that fails.

Add `imgStream.Seek(0, SeekOrigin.Begin)` before trying to load the bitmap.
