### ISSUE TITLE
Crash with trimming and zoom/magnifier (win+plus)

### ISSUE THREAD

**Issue by zii-dmg** [AvaloniaUI/Avalonia#12909]
**Describe the bug**
Avalonia app crashes if compiled with trimming and user opens zoom/magnifier (win+plus hotkey).

**To Reproduce**
1. dotnet new avalonia.app -o AvaTrim
2. change Avalonia version to 11.0.4 in csproj
3. dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true
4. run app exe
5. open zoom/magnifier with win+plus, move mouse cursor around Avalonia app
6. crash (app silently closes)

**Expected behavior**
Don't crash.

**Desktop (please complete the following information):**

- OS: Windows 10 22H2 x64
- Version: 11.0.4

**Additional context**
Also crashes on start if zoom/magnifier already runs.

Running under native debugger (mingw, gdb) I get SIGSEGV with stacktrace:
```
1 ntdll!RtlRetrieveNtUserPfn    0x7ff89455c73e 
2 UiaRaiseAutomationEvent       0x7ff867cec0ff 
3 UiaRegisterProviderCallback   0x7ff867d0636b 
4 UiaRegisterProviderCallback   0x7ff867d06550 
5 UiaReturnRawElementProvider   0x7ff867cc0766 
6 ??                            0x7ff627aee2b7 

```
Looks like something in accessibility support was trimmed.

**Comment by maxkatz6** [comment]
Related https://github.com/AvaloniaUI/Avalonia/issues/11767

It still shouldn't crash though. Accessibility-related code shouldn't be enabled while app is trimmed or built with AOT.
You can try adding `<BuiltInComInteropSupport>true</BuiltInComInteropSupport>` to the csproj file.

**Comment by zii-dmg** [comment]
`<BuiltInComInteropSupport>` already enabled in avalonia.app template.

**Comment by ilmandorlone** [comment]
I've encountered the same issue, and unfortunately, I have low vision 😄. 
When I launch the app after compiling and publishing with the system magnifier active, it crashes.
Interestingly, this doesn’t happen in debug mode.

Specifications:

    Windows 11
    Avalonia version: 11.1.4
    Avalonia.Desktop version: 11.1.4
    Avalonia.ReactiveUI version: 11.1.4
    Avalonia.Svg.Skia version: 11.1.0.1
    Avalonia.Themes.Fluent version: 11.1.4
    Avalonia.Fonts.Inter version: 11.1.4
    Avalonia.Diagnostics version: 11.1.4
    CommunityToolkit.Mvvm version: 8.3.2
    Material.Icons.Avalonia version: 2.1.10
    NModbus4.NetCore version: 3.0.0
    
```
<PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net8.0</TargetFramework>
	<Nullable>enable</Nullable>
	<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
	<ApplicationManifest>app.manifest</ApplicationManifest>
	<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	<ApplicationIcon>Assets\favicon.ico</ApplicationIcon>
	<PublishSingleFile>true</PublishSingleFile>
	<SelfContained>true</SelfContained>
	<PublishReadyToRun>true</PublishReadyToRun>
	<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
</PropertyGroup>
```
