### ISSUE TITLE
SVG support?

### ISSUE THREAD

**Issue by ydogus** [AvaloniaUI/Avalonia#1291]
Hello,
I think adding svg support would be useful.
I found there are shape controls (line, path, rect or shapes etc.) but couldn't find a way to render a svg file directly.
Maybe adding svg file type support for `Image` control?

**Comment by jmacato** [comment]
@Gillibald perhaps link this issue when you get around to SVG support in the future

**Comment by wieslawsoltes** [comment]
For reference I have experimental `Svg` support for `Image`. It requires usage of `SkiaSharp` backend and CI builds from `master` branch.

Library: https://github.com/wieslawsoltes/Svg.Skia/tree/master/src/Svg.Skia.Avalonia
Sample: https://github.com/wieslawsoltes/Svg.Skia/tree/master/samples/AvaloniaSgvImage

**Comment by define-private-public** [comment]
I'd like to bump this, or at least add my support to have this included. Working with SVGs for multi-DPI displays is much preferable to using Bitmaps.

**Comment by wieslawsoltes** [comment]
https://github.com/wieslawsoltes/Svg.Skia#avaloniaui
https://www.nuget.org/packages/Svg.Skia.Avalonia/0.10.0-preview1

**Comment by kekekeks** [comment]
Supported via https://github.com/wieslawsoltes/Svg.Skia
