### ISSUE TITLE
VS/Resharper build failure, file in use, locked by .Net Host (dotnet.exe)

### ISSUE THREAD

**Issue by mgth** [AvaloniaUI/Avalonia#12910]
**Describe the bug**
using Resharper build tool,
compiler fails to copy dll because it's in use by dotnet.exe.

**To Reproduce**
Just compile with resharper builder and run, keeping a xaml editor opened.

**Expected behavior**
should run app

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.11.0.4

**Comment by MihaMarkic** [comment]
I see this occasionally on macOS as well, however on the next build is fine.

**Comment by timunie** [comment]
I'm not sure if that is really an Avalonia issue.

**Comment by MihaMarkic** [comment]
@timunie It could be that previewer is keeping a dll locked at the same time as build process, or xaml "intellisense".

**Comment by timunie** [comment]
I've heard similar from ppl usign WPF together with Resharper. Do you have a chance to test against other Avalonia version (0.10.x) and or other Resharper version?

**Comment by mgth** [comment]
checked with 11.0.5-rc1 it's ok now
