### ISSUE TITLE
How can I find the reason?

### ISSUE THREAD

**Issue by dayAndnight2018** [AvaloniaUI/Avalonia#12927]
upgrade from 0.0.18 to 11.0.4, the mainWindow is blank. I can not find it any problem...

<img width="905" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/44399091/bc93b840-ad76-4063-ab89-1d1eda849319">

**Comment by rabbitism** [comment]
https://docs.avaloniaui.net/zh-Hans/docs/next/stay-up-to-date/upgrade-from-0.10

**Comment by dayAndnight2018** [comment]
> https://docs.avaloniaui.net/zh-Hans/docs/next/stay-up-to-date/upgrade-from-0.10

thanks a lot!
