### ISSUE TITLE
Idle application suddenly takes 100% CPU 

### ISSUE THREAD

**Issue by cok666n** [AvaloniaUI/Avalonia#12933]
**Describe the bug**
We have 30 to 40 Debian 12 machines running an app in Avalonia 11.0.2, this is an industrial operator interface and must stay up and fullscreen 24/7. We started seeing very high CPU usage on some of our machines, especially ones that had been up for a longer time. The app hogs 100% of one core for no apparent reason, it starts to behave poorly, and some timer events stop occuring (they run using a dispatcher timer at background priority). 

We did some tests, and it seems this happens around the 24.8 days of uptime mark, we've already had 4 systems do that. 

While this happens, the strace shows a constant stream of EAGAIN errors (over 18k lines a second) 
```
recvmsg(53, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(53, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(53, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
```

We ran a 10 seconds dotnet-trace on a faulty instance, the file is over 200mb, but it seems to highlight the function causing the issues being around the RunLoop or OnOsTimerFunction (see screenshot). 

![2023-09-18 14_33_57-CPU Usage - cdl_hmi_20230918_135916_10s_highcpu nettrace - Microsoft Visual Stud](https://github.com/AvaloniaUI/Avalonia/assets/3584469/46a0706c-51c4-4f70-9239-d7f309de0b81)

**Reproduction steps**
I have not built an empty app exhibiting the bug, however we have had the same thing happen on 4 almost identical machines, just let the app run for 25 days. 

**Versions and OS**
The bug happens on 11.0.2, we have not yet confirmed if it happens on 11.0.4 as the test takes 25 days. We do however have a machine running a 11.0.4 version right now. 
OS : Debian 12

Let me know if I can give anything to help the dev team with this one, I have one machine at 100% CPU right now and I am leaving it that way for now if there are further tests needed. I can also provide the trace files if there is a handy way to do so.

**Comment by kekekeks** [comment]
> 24.8 days of uptime mark

This looks like int32 overflow for some value expressed in milliseconds (`(double)int.MaxValue / 1000/60/60/24 = 24,8551348032407`)

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/12941 - probably this one

**Comment by cok666n** [comment]
That was quick! Thanks! Funny thing is we did notice it being an int32 overflow but doubted our code for the longest time since we had no idea what exactly was overflowing.

Do you happen to have an ETA for the next release? We'd definitely want to give this fix a try. 

I can start a test run with the prerelease build if that could speed up the pull-request process. 

Thanks again for all your hard work

**Comment by cok666n** [comment]
As mentioned in https://github.com/AvaloniaUI/Avalonia/pull/12941 ,I've built our application with the PR build and started a test. We shall see what happens in 25 days...

**Comment by cok666n** [comment]
So we ran a 25+ days test using the PR build and I can now confirm this is solved. 
Thanks
