### ISSUE TITLE
Packaging macOS executable sans brew

### ISSUE THREAD

**Issue by AdamFrisby** [AvaloniaUI/Avalonia#1294]
Is it possible to package a .NET Core macOS executable without needing to install gtk+3 via brew - we're currently forcing that installation on our users as part of a setup procedure, but it's a suboptimal solution.

Is there a way to bundle in the required libraries alongside everything else - even if it requires copying files by hand into the directory?

(I see that in the upcoming platform notes - and really do appreciate the fact that Mac support is available here - it's the only way to get cross platform UI working through .NET Core right now)

**Comment by danwalmsley** [comment]
nightly builds no longer have a dependency on gtk3. 

https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

As long as you don't override the appbuilder on Mac and use the default UsePlatformDetect it will now use MonoMac.

Hope this helps

**Comment by AdamFrisby** [comment]
Awesome - that's fantastic.

**Comment by grokys** [comment]
Closing this as it looks like it's fixed.
