### ISSUE TITLE
Is it no longer possible to derive a subclass from an Avalonia control in 11?

### ISSUE THREAD

**Issue by kuiperzone** [AvaloniaUI/Avalonia#12967]
I have an app where I derive several custom controls from existing controls. A full complete (previously but now non-working) example is given below.

In fact, the Avalonia documentation gives an example of how to do precisely this:  https://docs.avaloniaui.net/docs/next/guides/custom-controls/add-custom-control-class

It has all worked and my app relies on it. However, since circa 11.0.3, it just stopped working. The behaviour is that the control is created as normal, but is just invisible.

Was there a secret breaking change? Or am I missing something here?

See also: https://github.com/AvaloniaUI/Avalonia/issues/12966

```
using System.Globalization;
using System.Text;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using AvantGarde.Utility;

namespace AvantGarde.Views;

/// <summary>
/// A custom TextBox. By default, it has monospace font.
/// </summary>
public class CodeTextBox : TextBox
{
    public CodeTextBox()
    {
        FontFamily = "monospace";
        CornerRadius = new CornerRadius(0);
        TextWrapping = Avalonia.Media.TextWrapping.NoWrap;
        AcceptsReturn = true;

        GotFocus += GotFocusHandler;
        LostFocus += LostFocusHandler;
    }

    /// <summary>
    /// Gets or sets the tab character width. Used only for caret position calculation.
    /// </summary>
    public int TabWidth { get; set; } = 4;

    /// <summary>
    /// Gets the caret position as (line, col). If the box is empty, the result is (1, 1).
    /// </summary>
    public Tuple<int, int> GetCaretPos()
    {
        int line = 1;
        int col = 1;

        var text = Text;

        if (text != null)
        {
            int idx = CaretIndex;

            for (int n = 0; n < text.Length; ++n)
            {
                if (n == idx)
                {
                    break;
                }

                var c = text[n];

                if (c == '\n')
                {
                    line += 1;
                    col = 1;
                }
                else
                if (c == '\t')
                {
                    col += TabWidth;
                }
                else
                if (c >= ' ' && !Char.IsControl(c))
                {
                    col += 1;
                }
            }
        }

        return Tuple.Create(line, col);
    }

    /// <summary>
    /// Gets caret position as "Ln y, Row x".
    /// </summary>
    public string GetCaretLabel()
    {
        var c = GetCaretPos();
        var sb = new StringBuilder("Ln ");
        sb.Append(c.Item1);
        sb.Append(CultureInfo.CurrentCulture.TextInfo.ListSeparator);
        sb.Append(" Col ");
        sb.Append(c.Item2);

        return sb.ToString();
    }

    /// <summary>
    /// Sets the caret position based on column and line. It returns CaretIndex.
    /// </summary>
    public int SetCaretPos(int line, int col)
    {
        var text = Text;
        col = Math.Max(col, 1);

        if (col > 0 && text != null)
        {
            int x = 1;
            int y = 1;

            for (int n = 0; n < text.Length; ++n)
            {
                if ((y == line && x == col) || y > line)
                {
                    CaretIndex = n;
                    return n;
                }

                var c = text[n];

                if (c == '\n')
                {
                    y += 1;
                    x = 1;
                }
                else
                if (c == '\t')
                {
                    x += TabWidth;
                }
                else
                if (c >= ' ' && !char.IsControl(c))
                {
                    x += 1;
                }
            }

            // Set end
            CaretIndex = Math.Max(text.Length - 1, 0);
        }

        return CaretIndex;
    }

    protected override async void OnKeyDown(KeyEventArgs e)
    {
        if (e.KeyModifiers == KeyModifiers.Control)
        {
            var clippy = this.GetOwnerWindow().Clipboard;

            if (e.Key == Key.C)
            {
                if (clippy != null && !string.IsNullOrEmpty(SelectedText))
                {
                    await clippy.SetTextAsync(SelectedText);
                }
            }
            else
            if (e.Key == Key.A)
            {
                SelectAll();
            }
        }
    }

    private void GotFocusHandler(object? sender, GotFocusEventArgs e)
    {
    }

    private void LostFocusHandler(object? sender, RoutedEventArgs e)
    {
    }

}
```

**Comment by timunie** [comment]
there shouldn't be any breaking change between 11.0.0 and 11.0.4. So if it worked in 11.0.0, please file a minimal sample for us to reproduce. If you are comming from 0.10, that's a different story.

**Comment by kuiperzone** [comment]
Yeah, I think I've got confused between the versions (sorry). I can confirm it's broken in 11.0.0, as just tried it.

I'll come back to you with a minimal sample. In the meantime, some screen shots:

![image](https://github.com/AvaloniaUI/Avalonia/assets/17156238/c88b8521-edcb-4ec9-bff1-f16fc45d9f41)

![image](https://github.com/AvaloniaUI/Avalonia/assets/17156238/a52a0890-5f97-4063-996c-68b53508cefc)

**Comment by timunie** [comment]
check original control themes if you try to override them. We renamed some template parts. So if these are missing in your style, the template cannot be applied and control will fail.

**Comment by IanRawley** [comment]
You're missing the StyleKey override. https://docs.avaloniaui.net/docs/next/stay-up-to-date/upgrade-from-0.10#optional-but-recommended

If you don't override the StyleKey it looks for a custom control template, which if all you're doing is functionality changes rather than appearance you probably haven't made.  Add the following:
```
protected override Type StyleKeyOverride => typeof(TextBox);
```
and it should reappear looking like any other TextBox.

**Comment by maxkatz6** [comment]
Your CodeTextBox wouldn't work in 0.10 either. I assume you have removed stylekey override during migration, while it should be kept there, just changed to new StyleKeyOverride property. See the migration guide (linked in the message above).

**Comment by kuiperzone** [comment]
> Your CodeTextBox wouldn't work in 0.10 either. I assume you have removed stylekey override during migration, while it should be kept there, just changed to new StyleKeyOverride property. See the migration guide (linked in the message above).

Correct. It actually inherited from `IStyleable` and did implement the interface. It was indeed removed during migration. Thank you for you help. Still a problem with https://github.com/AvaloniaUI/Avalonia/issues/12966 though.

**Comment by kuiperzone** [comment]
> You're missing the StyleKey override. https://docs.avaloniaui.net/docs/next/stay-up-to-date/upgrade-from-0.10#optional-but-recommended
> 
> If you don't override the StyleKey it looks for a custom control template, which if all you're doing is functionality changes rather than appearance you probably haven't made. Add the following:
> 
> ```
> protected override Type StyleKeyOverride => typeof(TextBox);
> ```
> 
> and it should reappear looking like any other TextBox.

Thank you.
