### ISSUE TITLE
CalendarDatePicker Prevents Re-selection of Date After Resetting SelectedDate to Null

### ISSUE THREAD

**Issue by sprvtelida** [AvaloniaUI/Avalonia#13037]
Describe the bug
After resetting the selected date in the CalendarDatePicker control by setting SelectedDate to null, it's impossible to re-select the same date because the control seems to think it's still selected.

To Reproduce

Embed a CalendarDatePicker control in an Avalonia view.
Select a date (e.g., September 26, 2023).
Programmatically set the SelectedDate of the CalendarDatePicker to null.
Try selecting the previously selected date (September 26, 2023) using the CalendarDatePicker control.
Observe that the date cannot be re-selected.
Expected behavior
After resetting the SelectedDate to null, any date (including the one that was previously selected) should be selectable without any issues.

Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/61797264/a1b0b191-a06b-40fc-b316-8230fb993262)

Desktop:
OS: Windows 11
Version: Avalonia v. 11.0.4

Additional context
The issue was noticed after updating from Avalonia 0.10.21 to 11.0.0. The DatePicker control in version 0.10.21 did not exhibit this behavior.

**Comment by Alshain01** [comment]
Possibly related to #13000

**Comment by sprvtelida** [comment]
Yes, same issue, do I need to close this issue?

**Comment by timunie** [comment]
Closing this as duplicate
