### ISSUE TITLE
Avalonia apps doesen't work with .netcore TFM's below netcoreapp3.1 anymore 

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/Avalonia#13053]
**Describe the bug**
In fact every .netcore TFM below netcoreapp3.1 is unsupported from 11.0 in 0.10.22 everything worked as expected. Now you will get a build error from System.Threading.Channels package. It isn't directly referenced in any of Avalonia assemblies so it might be an transitive dependency.
![image](https://github.com/AvaloniaUI/Avalonia/assets/53405089/39eb0c40-5dab-4ff6-b701-eda96b082c53)

**To Reproduce**
To reproduce just create an Avalonia 11 ap from the template and change the TFM to netcoreapp2.0

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version 11.0.0 and above

**Comment by rabbitism** [comment]
Add some info here 
https://github.com/dotnet/runtime/issues/38046

**Comment by kekekeks** [comment]
System.Threading.Channels dependency comes from Tmds.DBus.Protocol package.
Consider raising an issue about not properly supporting netstandard2.0/netcoreapp2.0 there - https://github.com/tmds/Tmds.DBus
