### ISSUE TITLE
Option to dispose DataContext automatically

### ISSUE THREAD

**Issue by deerchao** [AvaloniaUI/Avalonia#13051]
Hi, I noticed that view models aren't disposed automatically, we have to subscribe several events to dispose them manually. It would be very convenient if we can dispose `DataContext` automatically in certain sceneries. Here is one possible approach to add this feature:

Add a boolean property `AutoDisposeDataContext` to `Window` and `UserControl`;

When their `DataContext` changes, and the old value is `IDisposable`, call its `Dispose()` method if  `AutoDisposeDataContext` is true.
When themselves got detached from logical tree, and current `DataContext` is `IDisposable`, call  its `Dispose()` if  `AutoDisposeDataContext` is true.

**Comment by timunie** [comment]
> Add a boolean property AutoDisposeDataContext to Window and UserControl;

If one wants to have that feature, I guess it should be added to AvaloniaObject (or whatever class actually adds DataContextProperty), so each control can benefit from it. 

I don't know if it would have any other side effects, but having this opt in could work well probably.

**Comment by Alshain01** [comment]
I can't think of any side effects if it defaults to false, but it's an antipattern.  That which creates the object should dispose it. Also, you would be adding a feature that is better served by using Dependency Injection.  Since the host container is creating the objects, it disposes them.

**Comment by deerchao** [comment]
> I can't think of any side effects if it defaults to false, but it's a bit of a code smell. That which creates the object should dispose it. Also, you would be adding a feature that is better served by using Dependency Injection. Since the host is creating the objects, it disposes them.

Of course, the host should dispose view models they create, while it could be difficult sometimes. For example, in an app like Visual Studio, user can open and close documents/tool panes dynamically, and there are intense usages of `ContentControl` and `DataTemplate`, it would not be so easy to track every object's lifetime.

I think this feature is just like what GC brings to C++, or finalizers brings to C#: convenience. You can manage memory yourself; you can release unmanaged resources yourself, but it would be a little hard to do it right every time, every place, so it's good to have an option to give up some degree of control for simplicity.

**Comment by deerchao** [comment]
> > Add a boolean property AutoDisposeDataContext to Window and UserControl;
> 
> If one wants to have that feature, I guess it should be added to AvaloniaObject (or whatever class actually adds DataContextProperty), so each control can benefit from it.
> 
> I don't know if it would have any other side effects, but having this opt in could work well probably.

`DataContext` and `DetachedFromLogicalTree` are defined in `StyledElement`, so I think it should be added to `StyledElement`.

**Comment by jp2masa** [comment]
> Of course, the host should dispose view models it creates, while it could be difficult sometimes. For example, in an app like Visual Studio, user can open and close documents/tool panes dynamically, and there are intense usages of `ContentControl` and `DataTemplate`, it would not be so easy to track every object's lifetime.

In your data templates, you can always create a control deriving from a custom implementation of `UserControl` (for ReactiveUI, there is `ReactiveUserControl` which provides `WhenActivated` IIRC). So, you could handle `Loaded`/`Unloaded` or `AttachedToVisualTree`/`DetachedFromVisualTree` in your custom implementation to control the lifecycle of the `DataContext` as needed.

**Comment by maxkatz6** [comment]
Disposing on DetachedFromLogicalTree might be fine for specific application's needs. But as a framework feature, I am afraid, it's very of a limited use, and way too easy to shoot your foot while using it.

Each control/view might (and quite often - will) will have AttachedToVisualTree and DetachedFromVisualTree executed many times over the lifetime. Simple examples - tab controls, virtualized lists, page navigation. 
Page #1 is selected, control is attached to the visual tree, page #2 is selected, Page #1 control is detached (and DataContext is disposed), then page #1 is selected again - but DataContext was disposed already.

I know, this proposal explicitly says that this property should be disabled by default, but I don't think it's anyhow safe enough to be ever enabled.

Manual handling of Loaded and Unloaded events, as mentioned above, is a more fool-proof solution that isn't much more complicated.

**Comment by rabbitism** [comment]
And technically this can be achieved by attached property or behavior, I think it's not necessary to embed this feature to Avalonia itself.

**Comment by timunie** [comment]
> DataContext and DetachedFromLogicalTree are defined in StyledElement, so I think it should be added to StyledElement.

I also think Loaded and Unloaded are a better place to handle it. Probably one could just write a custom Behavior 🤔 which can be attached to any visual as needed. 

https://github.com/AvaloniaUI/Avalonia.Xaml.Behaviors 

Like that: 
```cs
public class DisposeBehavior : Behavior<Visual>
{
    protected override void OnAttached()
    {
        base.OnAttached();

        if (AssociatedObject is not null)
        {
            AssociatedObject.DetachedFromVisualTree += AssociatedObjectOnDetachedFromVisualTree;
        }
    }

    protected override void OnDetaching()
    {
        if (AssociatedObject is not null)
        {
            AssociatedObject.DetachedFromVisualTree -= AssociatedObjectOnDetachedFromVisualTree;
        }

        if (AssociatedObject?.DataContext is IDisposable disposable)
        {
            disposable.Dispose();
        }
        
        base.OnDetaching();
    }

    private void AssociatedObjectOnDetachedFromVisualTree(object? sender, VisualTreeAttachmentEventArgs e)
    {
        if (AssociatedObject?.DataContext is IDisposable disposable)
        {
            disposable.Dispose();
        }
    }
}
```

Usage:

```xml
<UserControl>
    <Interaction.Behaviors>
        <views:DisposeBehavior />
    </Interaction.Behaviors>
</UserControl>
```

**Comment by timunie** [comment]
@deerchao after all input and after thinking about it again, I think the risk of side effects is not really worth the benefits for some Apps. We already have several easy to implement options:
- Use ReactiveUI
- Use an attached property
- Use a Behavior
- Handle it in code behind

So I hope you agree that we can close this ticket for now. If you disagree, please let me know your thoughts. I'm open to re-open the issue if there is a good reason. 

Thanks for the suggestion and input anyway 🙏
