### ISSUE TITLE
Stepper Screen

### ISSUE THREAD

**Issue by MoHamzawy** [AvaloniaUI/Avalonia#13075]
A very useful and common UI component is a stepper screen. It would be very nice to have a component like this

![image](https://github.com/AvaloniaUI/Avalonia/assets/64315042/458a8461-e280-4287-b75b-e0e00ef91d43)

I tried to do a similar thing with tabs but it was painful to achieve something like this

**Comment by rabbitism** [comment]
You can check suki ui

https://github.com/kikipoulet/SukiUI

**Comment by timunie** [comment]
probably something for Avalonia.Labs. I'll move the issue there for now.

**Comment by workgroupengineering** [comment]
there is in https://github.com/AvaloniaUI/Avalonia.Labs

**Comment by timunie** [comment]
Apparently, not needed 🤔 
https://github.com/AvaloniaUI/Avalonia.Labs/blob/main/src/Avalonia.Labs.Controls/StepBar/StepBar.cs

will close this issue as we already seem to have such a control.
