### ISSUE TITLE
TwoWay TemplateBinding failed for Calendar in ControlTemplate

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#13086]
## Describe the bug
After Calendar's SelectedDate value is set internally, the value no longer get updated when value is set via template parent when using {TemplateBinding} syntax. But works for {RelativeResource TemplateParent} syntax. 

## To Reproduce
<img width="953" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/14807942/95ff6599-d54c-488a-9061-bc2f1d45f9d3">

Go to repo https://github.com/rabbitism/AvaloniaTemplateBindingIssue
1 and 3 are TemplateBinding, 2 and 4 are RelativeResource=TemplateParent

1. Select on 1, 2 3 4 properly updated
2. Select on 2, since 1 is already set internally, thus not updated, 3 and 4 properly updated
3. Select on 3, since 1 is already set internally, thus not updated, 2 and 4 properly updated
4. Select on 4, Since 1 and 3 are already set internally, thus not updated, 2 properly updated. 

As a reference, I made another demo for string value binding to TextBlock and TextBox, works well.

## Expected behavior
Value is properly updated. 

## Screenshots
No. 

## Environment 

- OS: [Windows 11]
- Avalonia-Version: [11.0.x]

## Additional context
Related to issue #13000 

Part of generated C# code of XAML template:

```csharp
        Calendar calendar1;
        Calendar calendar2 = calendar1 = new Calendar();
        calendar1.BeginInit();
        children1.Add((Control) calendar1);
        Calendar target1 = calendar2;
        StyledProperty<DateTime?> selectedDateProperty1 = Calendar.SelectedDateProperty;
        TemplateBinding templateBinding1 = new TemplateBinding((AvaloniaProperty) CalendarDemo.DateProperty);
        templateBinding1.Mode = BindingMode.TwoWay;
        IBinding binding1 = templateBinding1.ProvideValue();
        target1.Bind((AvaloniaProperty) selectedDateProperty1, binding1, (object) null);
        target1.EndInit();
        Avalonia.Controls.Controls children2 = stackPanel2.Children;
        Calendar calendar3;
        Calendar calendar4 = calendar3 = new Calendar();
        calendar3.BeginInit();
        children2.Add((Control) calendar3);
        Calendar calendar5;
        Calendar calendar6 = calendar5 = calendar4;
        context.PushParent((object) calendar6);
        Calendar target2 = calendar6;
        StyledProperty<DateTime?> selectedDateProperty2 = Calendar.SelectedDateProperty;
        CompiledBindingExtension bindingExtension1 = new CompiledBindingExtension();
        bindingExtension1.Path = new CompiledBindingPathBuilder().Self().Property((IPropertyInfo) StyledElement.TemplatedParentProperty, new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>((object) null, __methodptr(CreateAvaloniaPropertyAccessor))).Property((IPropertyInfo) CalendarDemo.DateProperty, new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>((object) null, __methodptr(CreateAvaloniaPropertyAccessor))).Build();
        bindingExtension1.Mode = BindingMode.TwoWay;
        XamlIlContext.Context<CalendarDemo> provider1 = context;
        context.ProvideTargetProperty = (object) Calendar.SelectedDateProperty;
        CompiledBindingExtension bindingExtension2 = bindingExtension1.ProvideValue((IServiceProvider) provider1);
        context.ProvideTargetProperty = (object) null;
        target2.Bind((AvaloniaProperty) selectedDateProperty2, (IBinding) bindingExtension2, (object) null);
        context.PopParent();
        calendar5.EndInit();
```

**Comment by Takoooooo** [comment]
Not goind to be fixed. The problem here is caused by binding priorities. If you click 4 Calendar all 4 Calendars will change value since they will inherit it from the template with the Template priority.But once you change value locally on 1 or 3rd calendar they will have values set with LocalValue priority and values with Template priority don't affect them anymore. So it is more of the expected behavior

**Comment by rabbitism** [comment]
> Not goind to be fixed. The problem here is caused by binding priorities. If you click 4 Calendar all 4 Calendars will change value since they will inherit it from the template with the Template priority.But once you change value locally on 1 or 3rd calendar they will have values set with LocalValue priority and values with Template priority don't affect them anymore. So it is more of the expected behavior

I would expect templatebinding is a shorter syntax of relativeresource. Why do they have different priority?

**Comment by timunie** [comment]
> I would expect templatebinding is a shorter syntax of relativeresource 

TemplateBinding is not a shorter version, it is a special type with special behaviors.
