### ISSUE TITLE
Avalonia UI Showcase - Alternative Application Submission Method

### ISSUE THREAD

**Issue by mihnea-radulescu** [AvaloniaUI/Avalonia#13099]
## Issue
The Avalonia UI Showcase _Submit your app_ functionality points the user to send an application submission to the Avalonia UI team. The provided e-mail address is likely swamped with e-mails, thus application submissions are easily getting overlooked.

## Solution
Allow Avalonia UI Showcase submission requests to be raised as issues, including the following data: application name, description, screenshots, and icon.

## Alternative solution
Pull requests, instead of raising an issue, would also work, potentially with a separate repository and a specific folder and file structure for application submissions.

**Comment by Alshain01** [comment]
I don't run the show here but I can tell you from personal experience in similar situations, if it hasn't already, the showcase list of apps will simply become untenable as the popularity of the platform increases.

**Comment by timunie** [comment]
Showcase is most likely for commercial Apps showing the power of Avalonia. The team decides with customers what will be shown. If you want to showcase your open source App, file a PR to awsome-avalonia.

**Comment by mihnea-radulescu** [comment]
Thanks @timunie for your suggestion, I've already added a PR to **awesome-avalonia**!

Since the issue has been solved, I am closing it.
