### ISSUE TITLE
TransitioningContentControl (and other Transitions?) not working properly on iOS after web authentication

### ISSUE THREAD

**Issue by LyleRolleman-plst** [AvaloniaUI/Avalonia#13110]
## Describe the bug
When changing a bound Content property of a TransitioningContentControl on iOS after returning from a Web Authentication view (using MAUI.Essentials WebAuthenticator), it fails to navigate until I tap on some other control (say a button)

It works fine if it's just a regular ContentControl so presumably there is something funky going on with transitions

It also works fine if I do not launch the authentication flow

I think this is also happening on ReactiveUI's routing

## To Reproduce

1. Create a basic "sign in" kind of screen and launch a WebAuthenticator 
2. upon returning, attempt to set the Content property bound to the control, navigating to a view with a button (presumably some sort of router/view locator is in place, but don't think it matters). 
3. Observe nothing happens
4. Tap a button (probably the sign in button), note instantly switches to the intended view

## Expected behavior
Transition should occur

## Screenshots

N/A

## Environment 

- OS: iOS
- Avalonia-Version: 11.0.4

## Additional context
I don't know how specific using WebAuthenticator is to this, perhaps any deep link or any native modal style view will cause it? Not sure at this point

**Comment by timunie** [comment]
@LyleRolleman-plst please provide a minimum sample to reproduce. Probably it's an issue of call order simply

**Comment by LyleRolleman-plst** [comment]
[TransitionsTest.zip](https://github.com/AvaloniaUI/Avalonia/files/12785988/TransitionsTest.zip)

I've attached a quick and dirty app demonstrating the problem. 

Note, no actual sign in was setup, but you can trigger the bug by just tapping Cancel on the browser window

**Comment by timunie** [comment]
Better to use DataTemplates instead of placing a UserControl into the ViewModel. In the MVVM world, you try to strictly have Model - View - and VeiwModel separated. 

So please don't do this: 
![image](https://github.com/AvaloniaUI/Avalonia/assets/47110241/64829591-8916-4f26-9ae3-7430e8dcce31)

Instead, please check out https://github.com/AvaloniaUI/Avalonia.Samples#%EF%B8%8F-datatemplate-samples and https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src/Avalonia.Samples/Routing/BasicViewLocatorSample how to use DataTemplates for navigation

**Comment by LyleRolleman-plst** [comment]
@timunie Oh I know, this is just the absolutely simplest demonstration of the bug I could cook up in what time I had available. It certainly is not a demonstration of proper MVVM design...

The bug also affects ReactiveUI (which I don't use, I prefer Community Toolkit. So much less boilerplate). In the ReactiveUI case, it resolves the view fine, and shows up in the router's history, but no navigation until you tap something to "unstick" it

**Comment by timunie** [comment]
@LyleRolleman-plst thx for the clarification, I got it. 

One idea I have which sometimes helps is to utilize  Dispatcher.UiThread.Post in order to wait for the UI to "unfreeze". 

However if that also doesn't help, we nned to wait for someone with an iOS as I own no such device on my own.

**Comment by LyleRolleman-plst** [comment]
@timunie I tried that without success :(

On the off chance that it matters, this is on an iPhone SE (3rd gen) running iOS 16.6.1
