### ISSUE TITLE
ButtonSpinnerLocation does not work with Simple theme

### ISSUE THREAD

**Issue by stogle** [AvaloniaUI/Avalonia#13123]
## Describe the bug
Setting ButtonSpinner's ButtonSpinnerLocation to Location.Left has no effect when using the Simple theme.

## To Reproduce

```
      <ButtonSpinner Height="30" ButtonSpinnerLocation="Left">
        <TextBlock HorizontalAlignment="Center" VerticalAlignment="Center" Text="Everest"/>
      </ButtonSpinner>
```

## Expected behavior
Setting ButtonSpinner's ButtonSpinnerLocation to Location.Left should move the spinner buttons to the left side of the content.

## Environment 

- Windows 11
- Avalonia-Version: 11.0.x

## Additional context
The selector in `ButtonSpinner.xaml` is incorrect. Instead of
https://github.com/AvaloniaUI/Avalonia/blob/8c23a35335294ac4dfc0500bb666920fac124b59/src/Avalonia.Themes.Simple/Controls/ButtonSpinner.xaml#L74
it should be
```
      <Style Selector="^ /template/ UniformGrid#PART_SpinnerPanel">
```

**Comment by timunie** [comment]
@stogle can you file a PR to solve this? Would be appreciated.
