### ISSUE TITLE
Color picker is not showing correctly on Android

### ISSUE THREAD

**Issue by ClayAchahui** [AvaloniaUI/Avalonia#13126]
## Describe the bug
ColorPicker is not showing correctly the colors in the first and third tab of the control.

## To Reproduce
- Create a project with the lastest version of avalonia.
- Add the color picker to the view.
- Open the color picker.

## Expected behavior
We should see the color picker with the colors and not all gray.

## Screenshots
<img width="252" alt="Screenshot 2023-10-03 at 16 29 59" src="https://github.com/AvaloniaUI/Avalonia/assets/43356162/b6e3bd84-c509-482e-a15e-72278da55ad9">

## Environment 

- OS:Android
- Avalonia-Version: 11.0.4

## Additional context here.

The color picker is showing correctly the colors on iOS and Desktop.

**Comment by robloo** [comment]
This is almost certainly an issue rendering the WriteableBitmap color spectrums. The bitmap itself is created in code and will work the same on all platforms, there is just something wrong displaying it on Android. That is likely not an issue with the ColorPicker itself.

I would also be curious if there is a difference between the Android emulator and a real device.

**Comment by maxkatz6** [comment]
Last time I checked, ColorPicker worked fine on Android, as it should (since, on Avalonia level, there are no many differences in how it's rendered).
Logs from Trace.Output might be helpful to know.

**Comment by rabbitism** [comment]
I have a semi demo installed on my physical device and works well. 
![Screenshot_2023-10-04-10-31-25-21_a8049838651edb7ecf7dc70ebad04da0.jpg](https://github.com/AvaloniaUI/Avalonia/assets/14807942/c67a35aa-87a2-40e0-bce8-3461097711ad)

**Comment by timunie** [comment]
@ClayAchahui please prepare a minimal sample and attach it here for us to try out. Also which Android version did you test? Emulator or physical device?

Thx.

**Comment by ClayAchahui** [comment]
> This is almost certainly an issue rendering the WriteableBitmap color spectrums. The bitmap itself is created in code and will work the same on all platforms, there is just something wrong displaying it on Android. That is likely not an issue with the ColorPicker itself.
> 
> I would also be curious if there is a difference between the Android emulator and a real device.
> 
> Edit: Can you click around on the spectrum and see if the color changes from black? It should be operating on internally calculated values and not actually what you see in the image. If those internal values are correct (and they should be) you should see the color changing in the preview color area. That will help confirm it's just the spectrum bitmaps not getting rendered to the screen.

Yeah, I can change the colors clicking on the spectrum, it is just a visual issue, I tested that only on emulator, I will try to test on real device.

**Comment by ClayAchahui** [comment]
Additional info: I tested the color picker with the 11.0.0-rc1.1 and the color picker is showing well but when I updated the 11.0.0 the issue will appear and testing in the same emulator.

**Comment by timunie** [comment]
Could be something needs to be imported which was not required in rc1. Please file a minimal sample showing your issue. Thx.

**Comment by ClayAchahui** [comment]
Sample: https://github.com/ClayAchahui/ColorPickerIssueSample
