### ISSUE TITLE
The way we should load custom fonts

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#1313]
#### WPF approach:

Specify font family with `pack://application:,,,/fonts/#MySuperFont Bold` (`res://AssemlyName.dll/fonts/#MySuperFont` or `res:/fonts/#MySuperFont` in our case)
Upsides:
- really easy to isolate fonts between assemblies
- auto-discovery of font variants (italic, bold)
Downsides:
- verbose
- fonts might get duplicated
- we need to migrate to WPF's model of handling resources that preserves actual file paths in the project. That will require an MSBuild task and runtime support in our asset loader. We need to completely migrate from `resm`, because relative uris won't work otherwise. That will *break* existing applications.

#### CSS approach

Register fonts globally somewhere. CSS does it like that:
```
 @font-face {
    font-family: myFirstFont;
    src: url(sansation_bold.woff);
    font-weight: bold;
    font-style: italic;
}
```

In our cast that would be:
```xml
<Application.Fonts>
  <FontResource FontFamily="MyFont" Uri="resm:Fonts.myfont.ttf" FontWeight="Normal" FontStyle="Italic"/>
</Application.Fonts>
```

Upsides:
- It would be possible to write `<TextBlock FontFamily="MyFont">` and it will just work

Downsides:
- It's needed to manually specify ttf file for each font variant (bold, italic)
- It won't be possible to have assembly-local fonts that don't interfere with anything else
- It would be troublesome to register fonts from component assemblies

@grokys @danwalmsley @jkoritzinsky @wieslawsoltes

**Comment by danwalmsley** [comment]
About fonts duplicating / interfering, as part of this we should allow comma separated font family names, where it searches maybe: Local assembly, then resources, then system fonts. 

The issues with css method like trouble registering from component assembly, we are able tondo this with styles already so this could be overcome? Font variants perhaps we can have a syntax to specify multiple ttf files?

**Comment by jkoritzinsky** [comment]
I like the WPF way, even if just for the relative paths for resources.

Also, couldn't we get syntax similar to the pro in the CSS section while still using the WPF-style loading?

**Comment by kekekeks** [comment]
As a temporary measure we could use `zip` files embedded as resources and treat them as "font collections".

**Comment by kekekeks** [comment]
The real question here is whether we want to switch to path-preserving resource model or not.

**Comment by grokys** [comment]
> we need to migrate to WPF's model of handling resources that preserves actual file paths in the project. 

What prevents loading fonts via the existing `resm:` scheme?

> We need to completely migrate from resm, because relative uris won't work otherwise. That will break existing applications.

You mean that support for `resm:` resources would have to be removed? Why is that?

**Comment by kekekeks** [comment]
>What prevents loading fonts via the existing resm: scheme?

Fonts consist of several `ttf` files. Some of them contain only one font variant, some contain multiple. WPF solves that by accepting a *directory* path with font name, then it scans all font files in said resource directory and constructs a collection of typefaces for that font. We can't do that with `resm`, because directory separator char becomes dot and we can't distinguish between them at run time.

>You mean that support for resm: resources would have to be removed? Why is that?

Relative paths won't work between `res` and `resm` schemes, that will generate a lot of confusion. `resm` scheme was a workaround for Mono not having proper build targets, if I remember correctly. We were planning to implement our own build task later, but never done so.

**Comment by kekekeks** [comment]
Another option that won't require us to have path-preserving resource system is globbing. 
E. g. `<TextBlock FontFamily="resm:Some.Namespace.myfont*.ttf">`

**Comment by jkoritzinsky** [comment]
For relative paths between `resm` and `res`, we could standardize on `resm` always being in the root directory.

**Comment by grokys** [comment]
> resm scheme was a workaround for Mono not having proper build targets, if I remember correctly

I don't think so - if I remember correctly it was because mono didn't have support for WPF-style resources (reading or writing)

**Comment by kekekeks** [comment]
>mono didn't have support for WPF-style resources 

Mono can read them without any issues, but xbuild/msbuild-on-mono doesn't have the required build targets for generating them.

**Comment by jkoritzinsky** [comment]
Now that #1564 is merged I'm going to mark this as fixed.
