### ISSUE TITLE
Using the Manual Lifetime Management `Window.KeyBindings` doesn't work

### ISSUE THREAD

**Issue by mozesa** [AvaloniaUI/Avalonia#13138]
## Describe the bug
Using [Manual Lifetime Management](https://docs.avaloniaui.net/docs/next/concepts/application-lifetimes#manual-lifetime-management) `Window.KeyBindings` doesn't work.

## To Reproduce

1. Create a new Avalonia MVVM project.
2. Add a new `KeyBinding` to `MainWindow.axaml`.
```axaml
<Window.KeyBindings>
    <KeyBinding Gesture="F8" Command="{Binding Test}"/>
</Window.KeyBindings>
```
3. Implement the appropriate method in the `MainWindowViewModel`.
```csharp
public class MainWindowViewModel : ViewModelBase
{
    public string Greeting => "Welcome to Avalonia!";

    public void Test(object? parameter)
    {
        Console.WriteLine("Hello World");
    }
}
```
4. Update your `Program.cs` to use Manual Lifetime Management.
```csharp
class Program
{
    [STAThread]
    public static void Main(string[] args)
        => BuildAvaloniaApp().Start(AppMain, args); // Keybinding doesn't work.

    // public static void Main(string[] args) => BuildAvaloniaApp()
        // .StartWithClassicDesktopLifetime(args); // Keybinding works.

    static void AppMain(Application app, string[] args)
    {
        var cts = new CancellationTokenSource();

        new Window().Show();

        app.Run(cts.Token);
    }

    public static AppBuilder BuildAvaloniaApp()
        => AppBuilder.Configure<App>()
            .UsePlatformDetect()
            .WithInterFont()
            .LogToTrace()
            .UseReactiveUI();
}
```
5. Start the program, and press `F8`.

## Expected behavior
The set up keybinding i.e. `<KeyBinding Gesture="F8" Command="{Binding Test}"/>` should fire, and see `Hello World` in console.

## Environment

- OS: Windows
- Avalonia-Version: 11.0.4

**Comment by timunie** [comment]
where exactly do you set the DataContext for Window? Use DevTools [F12] to investigate DataContext and KeyBindings of Window shown.

**Comment by mozesa** [comment]
Okay, I got it.
Thanks for your help.

```csharp
static void AppMain(Application app, string[] args)
{
    var cts = new CancellationTokenSource();

    new MainWindow { DataContext = new MainWindowViewModel() }.Show();

    app.Run(cts.Token);
}
```
