### ISSUE TITLE
DevTools console is not working

### ISSUE THREAD

**Issue by HermanKirshin** [AvaloniaUI/Avalonia#13144]
## Describe the bug
Dev tools console do not allow access to any predefined variables, without which it is useless.

## To Reproduce
Press F12 -> View -> Console
Type any well-known variable (e, root)
Get exception

Caused by commit f1cde62c where ConsoleContext become internal.

## Expected behavior
Either working console or its complete removal from devtools

## Screenshots
<img width="1095" alt="Screenshot 2023-10-05 at 18 07 21" src="https://github.com/AvaloniaUI/Avalonia/assets/25755704/f5ab97eb-787f-4a4a-a304-6ed438eb7f09">

- OS: Any
- Avalonia-Version: [11.x]

**Comment by timunie** [comment]
Ah now I got what you were talking about. Thx for finding this bug.

**Comment by maxkatz6** [comment]
There was an idea to remove console feature at all, as it's not much useful (considering that you can debug app in the IDE, and execute code on break point), but also introduces more unwanted dependencies in debug mode.
