### ISSUE TITLE
[Android] Raise Button Click on mouse Wheel

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#13148]
## Describe the bug
When mouse pointer is up button e trigger mouse wheel, Button Click event is raise

## To Reproduce

1. Run `MobileSandbox.Android`
2. Posiion pointer on Button
3. Rotate mouse Wheel
4. You can see in output console the message `Button pressed`

## Expected behavior
Button Click Event does not raise when mouse wheel trigger

## Environment 

- OS: **Android 11.0**
- Device: Emulator **Pixel 5 - Api 30 (Android 11.0)**
- Avalonia-Version: **965d0e973da61d279dad9b382497248de3416e20**

**Comment by timunie** [comment]
could that be related to Emulator? Can you check in DevTools events Tab which events the App reached?

**Comment by maxkatz6** [comment]
Yes, I think it's just how emulator works. Better to double check with a real mouse connected to the real device.

**Comment by workgroupengineering** [comment]
> Yes, I think it's just how emulator works. Better to double check with a real mouse connected to the real device.

I'll try. With MAUI it doesn't happen in the emulator, so I don't know if it depends on its configuration.

**Comment by timunie** [comment]
https://github.com/unoplatform/uno/issues/530 I guess this is the same issue. Looks like it depends on if you can scroll or not in current view 🤷

**Comment by emmauss** [comment]
Android Emulator simulates wheel by sending ACTION_DOWN and ACTION_UP motion events for each wheel tick, with positions adjusted to simulate a swipe.

**Comment by timunie** [comment]
@workgroupengineering in the emulator there's an option to configure this iirc

**Comment by workgroupengineering** [comment]
> @workgroupengineering in the emulator there's an option to configure this iirc

I see. I don't understand why in MAUI it works without changing settings. Closing for now, thanks for the support.

**Comment by timunie** [comment]
Then it's an issue on their side not respecting that setting
