### ISSUE TITLE
Deffered renderer sometimes does not dispose all layers

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1314]
https://files.gitter.im/AvaloniaUI/Avalonia/nFRX/image.png

I'm not sure how to trigger this, but iv seen it a few times. Will try to find out more.

**Comment by jkoritzinsky** [comment]
This might be related to/duplicate of #1187.

**Comment by grokys** [comment]
Just to check: this is happening when shutting down the application, right?

**Comment by danwalmsley** [comment]
no, this is happening at run time.

**Comment by danwalmsley** [comment]
I can usually trigger it by changing my colour scheme a few times, with skia backend, and changing editor tabs in AS, but seems pretty random

**Comment by danwalmsley** [comment]
![image](https://user-images.githubusercontent.com/4672627/34060143-4a375376-e1da-11e7-8a59-14113cfda21a.png)
getting this quite a lot now

**Comment by grokys** [comment]
@danwalmsley are you still seeing this?

**Comment by grokys** [comment]
Closing this as it's been stale for years.
