### ISSUE TITLE
[Android] Current tab lost when changing theme.

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#13151]
## Describe the bug
Current tab lost when changing theme

## To Reproduce

1. Run `Avalonia.Labs.Catalog.Android`
2. Go `Tab Layout` page
3. Select `Page 2`
4. Changing theme.
5. You can see thath active page is `Page 1`

## Expected behavior
When changing theme, the active page is maintained

## Screenshots

![issue](https://github.com/AvaloniaUI/Avalonia/assets/12531229/14a4f2e0-7a92-431b-b7d6-bab88460060b)

## Environment 

|   |  |
|:-|-:|
|OS | Android 11
|Avalonia-Version|  **11.0.0** and **11.0.4**
|Avaloina Labs Version| **11.0.1**

## Additional context
On windows works as expected

**Comment by maxkatz6** [comment]
It's pretty weird since changing the theme variant shouldn't recreate any templates. It's simply a brushes change.
