### ISSUE TITLE
Add Background color in MainWindow causes window unable to drag and move

### ISSUE THREAD

**Issue by lxymahatma** [AvaloniaUI/Avalonia#13164]
## Describe the bug
When setting background color in my project's main window, the app cannot be drag and move

## To Reproduce
When adding Background="#2D2D2D", i can't drag and move the whole app
https://github.com/MDModsDev/MuseDashModToolsUI/blob/d499bc520b22d9258f2d410d28ab86b5cfb13beb/UI/Views/MainWindow.axaml#L15C65-L15C65
However, after removing the background assign, it's working

![image](https://github.com/AvaloniaUI/Avalonia/assets/66151783/a94c74da-46de-4ae5-9400-190bf52dd5e3)

## Screenshots
![bug](https://github.com/AvaloniaUI/Avalonia/assets/66151783/581c10e7-9a9b-4e0f-838d-8bb49a36ab0f)

## Environment 
- OS: Windows 11
- Avalonia-Version: 11.0.4

**Comment by timunie** [comment]
This is by design. As soon as you have a Background, your control can be hitted by your pointer. So you can either set Background to null and place a colored element below or set `IsHittestVisible=false`. Note, it will most likely also apply to children of your Grid

**Comment by Alshain01** [comment]
In your particular scenario, I would just set the background of the window itself, not the grid.

**Comment by lxymahatma** [comment]
> In your particular scenario, I would just set the background of the window itself, not the grid.

thanks! this is the easiest way to do that lol
~~the reason i set grid background is that in my opinion cz u only have one element in the window there's no difference to set window background and grid background~~ and now i know the difference 🤣

**Comment by lxymahatma** [comment]
> This is by design. As soon as you have a Background, your control can be hitted by your pointer. So you can either set Background to null and place a colored element below or set `IsHittestVisible=false`. Note, it will most likely also apply to children of your Grid

Thank u for ur explanation! I thought it's a bug lol 😂
I'll close the issue then
