### ISSUE TITLE
ScrollViewer handles wrapped Image incorrectly

### ISSUE THREAD

**Issue by mihnea-radulescu** [AvaloniaUI/Avalonia#13165]
## Description
When a **ScrollViewer** is wrapped around an **Image**, where the Image.Size is an **exact multiple** of ScrollViewer.Viewport (e.g. image size is 3840x2160, and view port is 1920x1080), the Image cannot be scrolled at all, and the following **ScrollViewer** properties are invalid:
- Extent is equal to Viewport, regardless of image size
- ScrollBarMaximum is { 0, 0 }
- Offset is { 0, 0 }

Changing the Image size by even 1 pixel (e.g. image size is 384**1**x2160, and view port is 1920x1080), such that it no longer is an exact multiple of ScrollViewer.Viewport, results in the correct scrolling behavior, and the properties of ScrollViewer being valid.

## Code sample exposing the issue
- [Window definition](https://github.com/mihnea-radulescu/imagefanreloaded/blob/master/ImageFanReloaded-Avalonia/Views/Implementation/ImageWindow.axaml)
- [ScrollViewer logic](https://github.com/mihnea-radulescu/imagefanreloaded/blob/master/ImageFanReloaded-Avalonia/Views/Implementation/ImageWindow.axaml.cs) - method **DragImage()** - lines 147-196

## Behavior in WPF
A close-to-identical implementation in WPF does not exhibit the bug.
- [Window definition](https://github.com/mihnea-radulescu/imagefanreloaded/blob/master/ImageFanReloaded-WPF/Views/Implementation/ImageWindow.xaml)
- [ScrollViewer logic](https://github.com/mihnea-radulescu/imagefanreloaded/blob/master/ImageFanReloaded-WPF/Views/Implementation/ImageWindow.xaml.cs) - method **DragImage()** - lines 165-214

## Environment
- OS: Windows 10
- .NET: 6
- Avalonia-Version: 11.0.4

**Comment by timunie** [comment]
This is one of the weirds issues I've seen. Must be some division error 🧐. All other makes no sense to me. 

Does it also happen in a minimal sample App?

**Comment by mihnea-radulescu** [comment]
The issue seems to appear when ScrollViewer.HorizontalScrollBarVisibility or ScrollViewer.VerticalScrollBarVisibility is initially set to ScrollBarVisibility.Disabled, and then set to ScrollBarVisibility.Hidden.

I have managed to add a workaround to my application by removing the transition from ScrollBarVisibility.Disabled to ScrollBarVisibility.Hidden, and using only ScrollBarVisibility.Hidden instead.

Since I have not been able to reproduce the bug in the Avalonia **AppWithoutLifetime** project, coupled with the bug being highly specific, I am closing the issue for now.
