### ISSUE TITLE
%20 in AbsolutePath not supported on Windows 11

### ISSUE THREAD

**Issue by NumbGnat** [AvaloniaUI/Avalonia#13173]
## Describe the bug
When calling `File.ReadAllTextAsync()` with an AbsolutePath that contains spaces, represented by `%20`, the file cannot be found on Windows 11.

## To Reproduce

1. Using the following code...

``` cs
if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime { MainWindow: not null } desktop)
{
    IHostStorageProvider storageProvider = new HostStorageProvider(desktop.MainWindow.StorageProvider);

    var filePickerOpenOptions = new FilePickerOpenOptions
    {
        FileTypeFilter = new FilePickerFileType[]
        {
            new("All Files")
            {
                Patterns = new[] { "*.*" },
            }
        },
    };

    var result = await _storageProvider.OpenFilePickerAsync(filePickerOpenOptions);
            
    if (result.Any())
    {
        string Text = await File.ReadAllTextAsync(result[0].Path.AbsolutePath);
    }
}
```
...attempt to open a file on Windows 11, in a location that contains a space in one of the folders of its path.

2. Notice the error...

## Expected behavior
The file's contents should be loaded into `Text`

## Screenshots

![image](https://github.com/AvaloniaUI/Avalonia/assets/1946849/51d6a3a7-f180-4f9d-98f7-921356baf6ea)

## Environment 

- OS: Microsoft Windows 11 Pro v 10.0.22621 Build 22621
- Avalonia-Version: Avalonia for Visual Studio 2022 v11.1

## Additional context

If I manually replace the `%20`s with spaces, the file loads successfully.

If I paste the AbsolutePath containing the `%20`s into Windows File Explorer, it generates the same error.

**Comment by jp2masa** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/12784#issuecomment-1706065698

**Comment by maxkatz6** [comment]
> await File.ReadAllTextAsync(result[0].Path.AbsolutePath)

1. Please use `result[0].OpenReadAsync()`. 
2. Uri.LocalPath returns file system-friendly path
3. It's not a bug.
