### ISSUE TITLE
CalendarDatePicker object BlackoutDates property not initialize on creation

### ISSUE THREAD

**Issue by mate1213** [AvaloniaUI/Avalonia#13183]
## Describe the bug
The following on the Calendar object works perfectly
`TestCalendar.BlackoutDates.AddDatesInPast();`
But the same way the CalendarDatePicker fails with NullReferenceException on BlackoutDates object:
`CalendarDatePicker.BlackoutDates.AddDatesInPast();`

## To Reproduce

1. Add CalendarDatePicker to the UI
2. Try to set the BlackoutDates property

## Expected behavior
I would like to able to add BlackoutDates to the CalendarDatePicker.

## Screenshots
Please comment if you need any.

## Environment 

- OS: Windows Desktop
- Avalonia-Version: 11.0.2

## Additional context
If it would possible, to create binding from AXAML would be the best. But any solution would be great.

**Comment by timunie** [comment]
This works for me if I wanted to set the BackoutDates from constructor: 

`Dispatcher.UIThread.Post(() => Picker.BlackoutDates?.AddDatesInPast());`

The reason is, that the template is not yet fully loaded so it does not find the child calendar.
