### ISSUE TITLE
Cultural Unicode text cannot be typed into Textbox.

### ISSUE THREAD

**Issue by dieuminhs** [AvaloniaUI/Avalonia#13190]
## Describe the bug
When the Textbox is inputted by typing with Cultural Unicode text, the whole text disappears but it doesn't when the text is copied and pasted.

## To Reproduce

1. Create a Textbox.
2. Type a culture Unicode type of text, for example in my culture: á, é can be created by typing aa and ee using keyboard tools or Windows display language.

## Expected behavior
The "á, é" text should be display normally instead of blank.

## Screenshots
Expected result (Works on WPF).
![image](https://github.com/AvaloniaUI/Avalonia/assets/48360748/90155a4d-37fd-4081-aaf2-39a7b54e2876)

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.4

## Additional context
 - I had already used another font family like Arial Regular but the result is still the same.

**Comment by timunie** [comment]
>  for example in my culture

what is your culture explicitly?

**Comment by timunie** [comment]
What are keyboard tools? do you have a screen record for us?

**Comment by dieuminhs** [comment]
> > for example in my culture
> 
> what is your culture explicitly?

My culture is Vietnamese (vi-vn)

> What are keyboard tools? do you have a screen record for us?

The tool i'm using is this one: https://evkeyvn.com/
And here's the config of the tools:

![image](https://github.com/AvaloniaUI/Avalonia/assets/48360748/39103620-0dd8-4ca7-b5d0-7a007047e037)

It seems that the error only occurs when i'm using the tools, not by using Windows Cultural display language. But it still works in WPF apps.

Here's the recording

https://github.com/AvaloniaUI/Avalonia/assets/48360748/f3336cd5-5d44-4354-a687-6330c9281fd2

**Comment by timunie** [comment]
Thank you 🙏 

Our text export will have a look once he finds the time to do.

**Comment by sloweyyy** [comment]
I am encountering the same issue with Vietnamese characters in the TextBox control. When typing using a keyboard tool like evkeyvn.com, the text disappears, which is not the case when pasting text directly. This issue is impacting the usability of the application for Vietnamese users. Looking forward to a resolution or any suggested workarounds.

**Comment by Gillibald** [comment]
The issue is such a tool isn't translated into English and I do not know how to use it.

**Comment by timunie** [comment]
@dieuminhs maybe you can try to help us supporting this? So you may try to adjust the Avalonia source as needed to make it work. For reference check out the PRs that added other keyboard support https://github.com/AvaloniaUI/Avalonia/pulls?q=is%3Apr+ime

**Comment by Gillibald** [comment]
I think that the app simulates key presses instead of implementing some proper input method

**Comment by dieuminhs** [comment]
> I think that the app simulates key presses instead of implementing some proper input method

I don't know how the app works but it's working fine in WPF so i think there must be something buggy in AvaloniaUI.

**Comment by dieuminhs** [comment]
> @dieuminhs maybe you can try to help us supporting this? So you may try to adjust the Avalonia source as needed to make it work. For reference check out the PRs that added other keyboard support https://github.com/AvaloniaUI/Avalonia/pulls?q=is%3Apr+ime



> @dieuminhs maybe you can try to help us supporting this? So you may try to adjust the Avalonia source as needed to make it work. For reference check out the PRs that added other keyboard support https://github.com/AvaloniaUI/Avalonia/pulls?q=is%3Apr+ime

It's kinda advanced for me haha, but i'll check it out.

**Comment by dieuminhs** [comment]
Hi @timunie , it seems like everytime a special cultural character is entered (by typing), the WndProcMessageHandler only receives backspace character. So I wanna ask if there is a way to see what is passed to the delegate in the below picture?

![image](https://github.com/AvaloniaUI/Avalonia/assets/48360748/3452be27-c220-4498-8361-4bdb52627b54)

**Comment by timunie** [comment]
adding @Gillibald here as it is far beyond my knowledge tbh.

**Comment by workgroupengineering** [comment]
> Hi @timunie , it seems like everytime a special cultural character is entered (by typing), the WndProcMessageHandler only receives backspace character. So I wanna ask if there is a way to see what is passed to the delegate in the below picture?
> 
> ![image](https://private-user-images.githubusercontent.com/48360748/297002887-3452be27-c220-4498-8361-4bdb52627b54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTIyMjgsIm5iZiI6MTcwNTQxMTkyOCwicGF0aCI6Ii80ODM2MDc0OC8yOTcwMDI4ODctMzQ1MmJlMjctYzIyMC00NDk4LTgzNjEtNGJkYjUyNjI3YjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEzMzIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjN2NjMjM1ZDg0NGQ1MWNmMzU5MzM4NzA4MWNjNjBjNzI1NjIyZDk3NzYxM2NkNDNiOWIzNTZjY2I0YjIwMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ncI9_cHXnP4AUZfHJNR2a168xgCWMA8CsBf07L8bIAY)

see 

https://github.com/AvaloniaUI/Avalonia/blob/2a7b5568b7f61fe6df9c46a05bf1c9d474c9290e/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs#L26

**Comment by dieuminhs** [comment]
> > Hi @timunie , it seems like everytime a special cultural character is entered (by typing), the WndProcMessageHandler only receives backspace character. So I wanna ask if there is a way to see what is passed to the delegate in the below picture?
> > ![image](https://private-user-images.githubusercontent.com/48360748/297002887-3452be27-c220-4498-8361-4bdb52627b54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTIyMjgsIm5iZiI6MTcwNTQxMTkyOCwicGF0aCI6Ii80ODM2MDc0OC8yOTcwMDI4ODctMzQ1MmJlMjctYzIyMC00NDk4LTgzNjEtNGJkYjUyNjI3YjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEzMzIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjN2NjMjM1ZDg0NGQ1MWNmMzU5MzM4NzA4MWNjNjBjNzI1NjIyZDk3NzYxM2NkNDNiOWIzNTZjY2I0YjIwMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ncI9_cHXnP4AUZfHJNR2a168xgCWMA8CsBf07L8bIAY)
> 
> see
> 
> https://github.com/AvaloniaUI/Avalonia/blob/2a7b5568b7f61fe6df9c46a05bf1c9d474c9290e/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs#L26

It's not this one, what i mean is AppWndProc is called by WndProc and WndProc is called by WndProcMessageHandler which is assigned to _wndProcDelegate, so i wanna know where will _wndProcDelegate be called, thanks.

**Comment by dieuminhs** [comment]
@Gillibald I've found the way our cultural tool works, in order to write a cultural character for example á (typing 's' after 'a'), the tool simulate a backspace to delete 'a', then it will perform a SendInput function (winuser.h) using the below input (The keycode is the int value of cultural custom map table. I wonder if these procedures is allowed by Avalonia?
![image](https://github.com/AvaloniaUI/Avalonia/assets/48360748/ec95830e-b1da-46f7-aff5-ea9699455e15)
If you need, i can provide the source of the tool. Thanks in advance.

**Comment by dieuminhs** [comment]
> Text input is handled via WM_KEYDOWN, WM_KEYUP and WM_CHAR The actual text input should always produce a WM_CHAR message
> 
> https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs#L177C45-L177C45
> 
> Make sure always to produce key_up and key_down
> 
> Unicode text can be sent via `KEYEVENTF_UNICODE`
> 
> Update: It seems this is the most ideal way of sending emulated key events: https://stackoverflow.com/a/67937018 It uses scancodes so there is no difference to a physical keyboard

It seems like when the cultural character is not parseable from Virtual Key or Physical Key, but it can be retrieved correctly by the GetKeySymbol method, is there a way to resolve this ?

**Comment by bui-cong-nghia** [comment]
Hello, I am also a Vietnamese user and currently I am having the same error. I don't know if you have fixed this error yet. If you have successfully fixed it, please guide me. @dieuminhs

**Comment by dieuminhs** [comment]
> Hello, I am also a Vietnamese user and currently I am having the same error. I don't know if you have fixed this error yet. If you have successfully fixed it, please guide me. @dieuminhs

I've found 2 workarounds currently, 

1. Using the clipboard option to send key in cultural tools. 
![image](https://github.com/AvaloniaUI/Avalonia/assets/48360748/cffd1de0-8493-4eb1-9e9e-f05d187b4997)

2. Build a custom Avalonia that override the RawKeyEvent method.
Before
![image](https://github.com/AvaloniaUI/Avalonia/assets/48360748/0c56da48-a0a7-4569-922c-72862d12928c)

After
![image](https://github.com/AvaloniaUI/Avalonia/assets/48360748/319b1113-62a5-4846-baee-3d7ba22510d7)

The method belongs to WindowImpl.AppWndProc.cs source file in Avalonia.Win32 Project.
I don't know if this alteration will affect others as well but worth a try.

**Comment by Gillibald** [comment]
I think we can add that fix to Avalonia because it seems to be the right thing to do

**Comment by sloweyyy** [comment]
Nice, it works for me @dieuminhs

**Comment by dieuminhs** [comment]
> I think we can add that fix to Avalonia because it seems to be the right thing to do

Ok, i will create a pull request for it, thank you for your help.
