### ISSUE TITLE
Text measurement improvements

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#132]
We need something to be able to implement methods like 
`public override void MeasureString(string str, Font font, double maxWidth, out int charFit, out double charFitWidth)` (HtmlRenderer requires this). 

For example, [Graphics.MeasureCharacterRanges](https://msdn.microsoft.com/en-us/library/system.drawing.graphics.measurecharacterranges%28v=vs.110%29.aspx) returns info about each character's position.

**Comment by grokys** [comment]
Is there an equivalent API in WPF that we can copy?

**Comment by tshcherban** [comment]
There is no equivalent, but WPF contains FormattedText class. Usage example: http://stackoverflow.com/a/840642

**Comment by kekekeks** [comment]
@tshcherban https://github.com/Perspex/Perspex/blob/master/src/Perspex.SceneGraph/Media/FormattedText.cs

**Comment by h0730303779** [comment]
How did you solve it later? I am now rendering some strings and also need to know the width of each rendered string.

**Comment by kekekeks** [comment]
See TextFormatter and friends.

In HtmlRenderer `MeasureString` is now implemented like this:
https://github.com/AvaloniaUI/Avalonia.HtmlRenderer/blob/f4e8c20a53a4cb4cc09b4f2ad8460e75d9f1fb36/Avalonia.HtmlRenderer/Adapters/GraphicsAdapter.cs#L115-L124
