### ISSUE TITLE
Missing TemplatePart causes window freeze instead of exception

### ISSUE THREAD

**Issue by stevemonaco** [AvaloniaUI/Avalonia#13200]
## Describe the bug
When creating a `ControlTemplate` and forgetting some required `TemplatePart`s, the window will freeze if the broken control is loaded sometime after startup. Behind a `TabItem` that needs to be clicked after startup in this case. Seemed to freeze the Previewer in Rider, too, but I didn't investigate in-depth.

When the broken control is loaded while starting, a `KeyNotFoundException` immediately closes the program.

## To Reproduce
Clone [this repo](https://github.com/stevemonaco/AvaloniaMissingPartFreeze)

Run. Click the "Crash" tab. Window should be unresponsive until you try to resize it. Then it will crash.

## Expected behavior
I expect a crash/exception immediately after clicking the tab instead of a window freeze.

## Environment 

- OS: Windows 10
- Avalonia-Version: 11.0.4
- IDE: Rider 2023.2.1, VS 17.7.0

**Comment by maxkatz6** [comment]
Most likely is going to be fixed by this PR https://github.com/AvaloniaUI/Avalonia/pull/13189

**Comment by stevemonaco** [comment]
Can confirm fixed by that PR. Can close this issue when it gets merged.

**Comment by timunie** [comment]
added to the fixes list
