### ISSUE TITLE
Direct2D1 backend crashes immediatly with (-1073740791 (0xc0000409). on AvalonStudio

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1320]
no exception or anything.

**Comment by jkoritzinsky** [comment]
I've started to make progress on this. It's an AV on the finalizer thread for a PNG decoder object. I'll keep investigating.

**Comment by jkoritzinsky** [comment]
This is a SharpDX bug that's revealed by us having objects that get destroyed on the finalizer thread.

I'm pretty sure that internal SharpDX managed objects are getting finalized and their native thunks are collected while WIC is still holding references to them. However, SharpDX deallocates the native thunks on dispose, irrespective of ref-count. Then when WIC tries to access the native callback (to reduce refcount or whatever), we get an AV.

**Comment by jkoritzinsky** [comment]
Filed the bug with SharpDX.

**Comment by danwalmsley** [comment]
any news on this, im still unable to run AvalonStudio on direct2d.

**Comment by jkoritzinsky** [comment]
We’re waiting on another release of SharpDX. I think it’s fixed there but I’m not sure.

**Comment by danwalmsley** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/1911 fixed it.
