### ISSUE TITLE
Styling should support inheritance

### ISSUE THREAD

**Issue by colejohnson66** [AvaloniaUI/Avalonia#13209]
In order to support a consistent theme within an application, style setters must be duplicated for each control template. It would be nice to have something like Tailwind CSS where classes are used to define properties. For example, the following doesn't work, despite `TextBlock` inheriting from `Control`:

```axaml
<Window.Styles>
    <Style Selector="Control.h-center">
        <Setter Property="HorizontalAlignment" Value="Center" />
    </Style>
</Window.Styles>

<TextBlock Text="{Binding Greeting}" Classes="h-center" VerticalAlignment="Center" />
```

## Describe the solution you'd like
I would like my selector to be `Layoutable.h-center`.

## Additional context
Centering horizontally is a contrived example, but this idea is easily usable to enforce, say, a consistent background color on certain controls, through generic styles instead of duplicated `<Setter Property="SomeProperty" Value="{DynamicResource SomethingSomething}" />` on each control's stylesheet.

**Comment by wieslawsoltes** [comment]
:is(Control)

**Comment by colejohnson66** [comment]
`Selector=":is(Layoutable).h-center"` works! Thanks!
