### ISSUE TITLE
Text alignment mismatch when using icon fonts

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#13235]
## Describe the bug

Text alignment mismatch when using icon fonts such as SegoeFluentIcons.

## To Reproduce

Check out `icon-font-err` branch for both repo:

[Avalonia Test](https://github.com/laolarou726/TypesettingErrorDemo)
[WPF Test](https://github.com/laolarou726/TypesettingErrorDemoWPF)

## Screenshots

In Avalonia:
<img width="225" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/25716486/cbcc067e-c8d8-4d5c-aa9d-6caff4924f8c">

In WPF:
<img width="186" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/25716486/2c85bcb6-a93f-4cf1-a7f9-fa337d3d7325">

## Environment

- OS: Windows 11 22H2
- Avalonia-Version: 11.1.999-cibuild0040792-beta

**Comment by robloo** [comment]
Two notes here:

 1. This may be a Skia issue
 2. I recall UWP/WinUI has a similar problem that remains unfixed: https://github.com/microsoft/microsoft-ui-xaml/issues/3077. This was not for fonts though, just paths.

**Comment by Alshain01** [comment]
I saw this issue as well with a piece of art I made myself. It almost seemed like it was using relative pathing even when the absolute path symbols were used (capital letters instead of lower case).  In my case I was able to move an arc that was being drawn incorrectly to the front of the path and it corrected itself.  It really was quite bizarre.

**Comment by robloo** [comment]
@Alshain01 Do you happen to have the path data you can share? That is probably easier to debug than a font.

**Comment by Alshain01** [comment]
> @Alshain01 Do you happen to have the path data you can share? That is probably easier to debug than a font.

I would love to help but while I made it, I did so on the job, so it's proprietary and doesn't belong to me.

**Comment by SmRiley** [comment]
I have a similar situation, but I don’t know if it is the same problem as you. My icon will have one or two extra paddngs on the left side.
![image](https://github.com/AvaloniaUI/Avalonia/assets/45205313/5b204152-a742-4d01-aaaa-29966d0ebfb0)

**Comment by timunie** [comment]
@SmRiley do you have a sample xaml and font file for us ?

**Comment by SmRiley** [comment]
> @SmRiley do you have a sample xaml and font file for us ?
[AvaloniaIconFontErrorDemo.zip](https://github.com/AvaloniaUI/Avalonia/files/13191450/AvaloniaIconFontErrorDemo.zip)
Sure, and this is the demo running result
![image](https://github.com/AvaloniaUI/Avalonia/assets/45205313/53855632-ea0b-4042-a871-804b68b83407)
@timunie

**Comment by timunie** [comment]
thx ❤️

**Comment by workgroupengineering** [comment]
Can anyone test the PR #14013 ? On my side, it solves the issue.
