### ISSUE TITLE
Topics for Youtube Tutorials

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1324]
@grokys @kekekeks @jkoritzinsky @mterwoord @wieslawsoltes @Seeker1437 

I would like to record some walkthroughs / tutorials on Avalonia for youtube partly to help showcase Avalonstudio and Avalonia, but also I think it might be helpful when people ask how do you do this and we can say check out tutorial 10.

So if you can help me compile a list of topics / ideas for tutorials.

I am thinking first few will be basic things:
1) Introduction to Avalonia - what it can do, where it can run
2) How to create your first app. (hello world)
3) Layout - Grid, StackPanel, Dockpanel
4) Basic controls, Textblock, TextBox, Button, Border 
5) What is MVVM how to create an Avalonia MVVM app.
6) Binding, (textbox, update other part of ui, via model, and just within view)
7) Commands  (buttons, etc)
8) Lists, lisbox + templates,
9) Styling
10) Observables and observing properties
11) Templated controls how to override templates, etc
12) create custom user controls

Ideally it would be nice to have all the tutorials slowly build up some kind of cool demo app, that perhaps actually did something useful but also demonstrate important features.

feel free to suggest more ideas an elaborate on some of the details that should be included in the above topics.

**Comment by KvanTTT** [comment]
What about articles?

**Comment by danwalmsley** [comment]
@KvanTTT probably I will produce some video walkthroughs and a repo with the example code, then perhaps if someone has time they may be able to help turn them into articles too.

**Comment by danwalmsley** [comment]
Ok I made a start on these, you can preview here:
https://blog.vitalelement.co.uk/avalonia-ui-tutorials/

**Comment by danwalmsley** [comment]
work in progress.

**Comment by timunie** [comment]
@danwalmsley I think as we now have discussions, this topic can be moved to "Show and Tell" do you agree? 

Also I think there is already a series of youtube videos. Should we link them here?
