### ISSUE TITLE
TreeView / DataBindings issue - With DataBinding SelectedItem setter gets called recursivley

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1326]
Basically in Avalonstudio If I select 1 top level item in the solution explorer tree view, then another top level item, the `:selected` pseudo class doesn't get removed, so you can end up with loads of selections.

The control catalog doesn't exhibit this issue.

After debugging I found that the SelectedItem setter in `TreeViewItem` calls itself in the error case. Putting a guard around it

```
private bool insideSetter = false;

        /// <summary>
        /// Gets or sets the selected item.
        /// </summary>
        public object SelectedItem
        {
            get
            {
                return _selectedItem;
            }

            set
            {
                if (!insideSetter)
                {
                    insideSetter = true;

                    if (_selectedItem != null)
                    {
                        var container = ItemContainerGenerator.Index.ContainerFromItem(_selectedItem);
                        MarkContainerSelected(container, false);
                    }

                    SetAndRaise(SelectedItemProperty, ref _selectedItem, value);

                    if (_selectedItem != null)
                    {
                        var container = ItemContainerGenerator.Index.ContainerFromItem(_selectedItem);
                        MarkContainerSelected(container, true);

                        if (AutoScrollToSelectedItem && container != null)
                        {
                            container.BringIntoView();
                        }
                    }

                    insideSetter = false;
                }
            }
        }
```

fixes the issue and tree view then behaves correctly, though I suspect this is a hack and the correct fix is somewhere in the binding system?

@grokys @kekekeks 

I'm pretty sure I wont be able to find a simple repro for this, so here are instructions on how to debug the issue in AS.

launch powershell

`git clone --recursive https://github.com/VitalElement/AvalonStudio.git`
`git checkout implement-roslyn-workspaces`
`git submodule update --init`

goto Avalonia directory
`cd scripts`
`dotnet build ..\samples\ControlCatalog.NetCore'
`.\ReplaceNugetCache.ps1 0.5.2-build4358-alpha`

open AvalonStudio in VS and run it. Open the file TreeView.cs.

Open a sample project in AvalonStudio or open AvalonStudio.sln or Avalonia.sln (as long as it has more than one project we can repro the issue)

Click on 1 of the projects in Solution Explorer
it goes blue and `:selected` is applied in the dev tools

Set a breakpoint inside TreeView SelectedItem setter.

Click on another project 

Notice that the SelectedItem setter is called twice, the first time setting the correct value, the second setting it to null (and a recursive call)

Then if you let it run, you will see both items are now selected and `:selected` has been applied to both `TreeViewItems` in DevTools.

**Comment by jkoritzinsky** [comment]
I think this is another situation similar to #855. I'll take a stab at this.

**Comment by danwalmsley** [comment]
@jkoritzinsky did you manage to do the repro, the fix didn't quite fix it, it just changed how the bug manifested itself. I'm around to assist with repro if needed.

**Comment by jkoritzinsky** [comment]
I didn't manage to get a repro. I put this together between studying for exams. If you can put together a small repro that'd be great!

**Comment by danwalmsley** [comment]
Ok Iv found the real cause of this! If selectedItem generates a:
`AvalonStudio Warning: 0 : Binding: Error in binding to "Avalonia.Controls.TreeView"."SelectedItem": "Could not convert 'AvalonStudio.Controls.Standard.SolutionExplorer.SolutionFolderViewModel' to 'ProjectItemViewModel'."`

Then the selection update fails.

**Comment by danwalmsley** [comment]
ok new repro commit here:
https://github.com/AvaloniaUI/Avalonia/tree/repro/1326-data-binding-issue
@jkoritzinsky @grokys 

It looks to be an issue with the SetAndRaise logic and DefferedSetter in AvaloniaObject.

**Comment by danwalmsley** [comment]
Repro shows this on TreeViewPage.

![image](https://user-images.githubusercontent.com/4672627/39545348-d85f41e2-4e48-11e8-819e-3fb3969556c2.png)

Selecting Item 2 will cause a casting error, and :selected wont get removed from the treeviewitem.

My issue is that although the user should fix the problem causing the binding error, the TreeViews logic shouldnt be affected.

This would work if the SetAndRaise was deffered until the setter had exited, in this case we cause the setter to be re-entered with value == null and then causing _selectedItem to be set to null. Missing the opertunity to clear the :selected psuedo class.

**Comment by grokys** [comment]
@danwalmsley are you still seeing this?

**Comment by MarchingCube** [comment]
@grokys I will see if that repros with my changed implementation, since I changed selection logic and the `SelectedItem` itself. Sadly I forgot to push my changes from my work computer so I can only check on Monday.

**Comment by Takoooooo** [comment]
I guess this one is outdated already. If that's not the case feel free to reopen
