### ISSUE TITLE
Is Value field of a NumericUpDown a double or a decimal?

### ISSUE THREAD

**Issue by FraserElectronics** [AvaloniaUI/Avalonia#13262]
## Describe the bug
Not sure if this is a misunderstanding on my part but when I bind a double value to the Value field of a NumericUpDown, I get an exception as shown in the screenshot below.

## To Reproduce
Create a NumericUpDown control and bind its Value field to a property that has the double type.

## Expected behavior
I am expecting it to be happy with a double.

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/19693425/cf0b8aef-94d7-48cf-b5ee-77b1d51ae9ae)

## Environment 

- Windows 11 x64
- Avalonia 11.0.4

## Additional context
Here is my AXAML and the property that is bound to the Value field.

```
      <ControlTemplate>
		  <Grid RowDefinitions="Auto,Auto" ColumnDefinitions="Auto,Auto" Margin="4">
			  <TextBlock Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="2" Text="{TemplateBinding Caption}" Foreground="{TemplateBinding CaptionForeground}" FontWeight="Bold"/>
			  <NumericUpDown
				  Grid.Row="1" Grid.Column="0"
				  Width="160"
				  Value="{TemplateBinding DisplayValue, Mode=TwoWay}"
				  FormatString="{TemplateBinding DisplayFormat}"
				  Minimum="{TemplateBinding MinimumAllowable}"
				  Maximum="{TemplateBinding MaximumAllowable}"
				  ShowButtonSpinner="{TemplateBinding ShowButtons}"
				  Increment="{TemplateBinding Increment}"
				  />
			  <ComboBox Grid.Row="1" Grid.Column="1" Width="120" Margin="8,0,0,0" SelectedIndex="{TemplateBinding SelectedUnits, Mode=TwoWay}">
				  <ComboBoxItem>MM</ComboBoxItem>
				  <ComboBoxItem>INS</ComboBoxItem>
			  </ComboBox>
		  </Grid>
	  </ControlTemplate>
```

```
    public static readonly DirectProperty<DistancePickerControl, double> DisplayValueProperty =
    AvaloniaProperty.RegisterDirect<DistancePickerControl, double>(nameof(DisplayValue), o => o.DisplayValue, ( o, v ) => o.DisplayValue = v );
    private double _displayValue;
    public double DisplayValue
    {
        get
        {
            return _displayValue;
        }
        set
        {
            //
            // Set the _displayValue backing field to the new value and if the new value is different then
            // SetAndRaise will also raise the NotifyPropertyChanged event.
            //
            SetAndRaise( DisplayValueProperty, ref _displayValue, value );
        }
    }
```

Andy

**Comment by FraserElectronics** [comment]
Well that is really annoying as I want to use it for doubles or floats and it is a pain having to do the conversion  :-(
In any case, the latest docs say:

![image](https://github.com/AvaloniaUI/Avalonia/assets/19693425/716749ab-1e26-47fc-9337-413f621c211a)

So I guess they need to be updated?

Andy

**Comment by FraserElectronics** [comment]
But I binding to doubles as can be shown in my code above and that is what is causing me problems.
I guess I could use a value converter to handle the bi-directional conversion between double and decimal?

Andy

**Comment by FraserElectronics** [comment]
Interesting, yes - it works for just a simple NumericUpDown on a view but does not seem to work when bound inside a template. Bug perhaps?

Andy

**Comment by FraserElectronics** [comment]
@timunie Tim, for the one that worked I simply dropped a NumericUpDown on a view on an old Avalonia project I had and bound it to a float and it worked.

So the AXAML is simply:

```
		<NumericUpDown Grid.Row="3" Value="{Binding Value}"/>
```

and I dropped an ObservableProperty on the view model:

```
   [ObservableProperty]
   private float value = 12.4f;
```

And if shows 12.5 in the control and I could use the up and down arrows.

For the code that does not work - it is part of a very big (for me) Avalonia project so I can't really attach it here.
However, I simply created a TemplatedControl using the Avalonia templates in Visual Studio and added the AXAML shows at the top of this post and in the code-behind I had the binding properties (also shown at the top of this post).

If you need a full solution showing the issue, let me know and I will see if I can find some time today to create it.

Andy

**Comment by FraserElectronics** [comment]
FYI,

I have created a simple solution that shows the issue and put it up on my GitHub.

https://github.com/FraserElectronics/AvaloniaNumericUpDownTest

Andy

**Comment by stevemonaco** [comment]
So as I see in the sample, you have a custom control that wraps `NumericUpDown` and forwards the `RealValue` dependency value from the custom control into `Value` through a `TemplateBinding`. With some trimming:

```xml
<Style Selector="controls|NumberPicker">
	<Setter Property="Template">
	  <ControlTemplate>
		  <NumericUpDown Value="{TemplateBinding RealValue}"/>
	  </ControlTemplate>
	</Setter>
</Style>
```

I think this may be a case of `TemplateBinding` being too simple and therefore not going through the `TypeConverter` system which will allow for automatic built-in conversions. I'm not entirely familiar with the area. In any case, it seems to be fixed when I use a normal binding: `Value="{Binding $parent[controls:NumberPicker].RealValue}" />`.

**Comment by FraserElectronics** [comment]
@stevemonaco 

Okay, so that seems to work :-)
Many thanks for your suggestion, that will allow me to press on with my project.

I am not sure if this should be submitted as a bug ?

Andy

**Comment by timunie** [comment]
TemplateBinding is s special type of binding with low level support. If that doesn't serve all function needed, you can fallback to Binding with `RelativeSource=TemplatedParent`

**Comment by FraserElectronics** [comment]
@timunie 

Thanks Tim, still trying to get my head around all the binding types :-)

Andy
