### ISSUE TITLE
d:DesignInstance unable to resolve

### ISSUE THREAD

**Issue by vszekeress-sportradar** [AvaloniaUI/Avalonia#13289]
## Describe the bug
`d:DesignInstance` expression no longer works. I'm getting an error `XamlX.XamlParseException: Unable to resolve type DesignInstance from namespace http://schemas.microsoft.com/expression/blend/2008`.

## To Reproduce
1. Add code snippet
```
<Window x:Class="AvaloniaApplication2.MainWindow"
        xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:avaloniaApplication2="clr-namespace:AvaloniaApplication2"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        Title="AvaloniaApplication2"
        d:DesignHeight="450"
        d:DesignWidth="800"
        Design.DataContext="{d:DesignInstance avaloniaApplication2:ViewModel}"
        mc:Ignorable="d">
    Welcome to Avalonia!
</Window>
```
3. Build the app
4. XamlParseException

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/88656333/9551130f-3928-4942-9317-2441b56e7642)

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.4

**Comment by maxkatz6** [comment]
I don't think it ever worked. And we don't have plans to make it work.
If this VM type has a parameters constructor, then you can create an object in XAML with XML syntax.
If this type doesn't have a parameters constructor, you need to create an instance in C# and reference it with x:Static, resolving DI in your way.

**Comment by vszekeress-sportradar** [comment]
@maxkatz6 It was definitely working in Avalonia 0.10. So I thought that something just got broken and fix would be easy.

**Comment by workgroupengineering** [comment]
> @maxkatz6 It was working in Avalonia 0.10. By that I mean it didn't produce any build error and it did resolve DataContext type and that's all I wanted. So I thought that something just got broken and fix would be easy. The VM constructor is parameterless. I think it's unfortunate and not trivial, that we must use element syntax and not attribute syntax like in WPF.

https://docs.avaloniaui.net/docs/getting-started/ide-support#design-time-properties

**Comment by ArchibaldMacdonald-cyacomb** [comment]
Is the best practice to have viewmodels with parameterless constructors, as this seems to be the encouraged workflow?
