### ISSUE TITLE
TextBlock misaligned when text starts with '1'

### ISSUE THREAD

**Issue by ATZ-FR** [AvaloniaUI/Avalonia#13285]
## Describe the bug
A text in TextBlock looks a bit misaligned if the first symbol is '1'.

## To Reproduce
- Make a new Avalonia .Net application;
- Insert the following lines in the empty Window:
```
  <Grid>
    <StackPanel Margin="10">
      <TextBlock Text="12345"/>
      <TextBlock Text="22345"/>
      <TextBlock Text="22315"/>
    </StackPanel>
  </Grid>
```

## Expected behavior
All block should have the same width.

## Screenshots
![изображение](https://github.com/AvaloniaUI/Avalonia/assets/44577155/c95c61d9-5e81-436a-bafa-e61643bd0c3b)

The first TextBlock has an offset at the beginning and appears wider than the two others. Also note the 3rd text where '1' is in the middle - it appears ok.

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.5rc1

**Comment by Gillibald** [comment]
This perfectly aligns:
```
      <TextBlock>
        <Run Text="12345"/>
        <LineBreak/>
        <Run Text="22345"/>
        <LineBreak/>
        <Run Text="22345"/>
        <LineBreak/>
      </TextBlock>
```

**Comment by timunie** [comment]
@ATZ-FR which font do you use? can you maybe file a minimal sample to reproduce?

**Comment by Gillibald** [comment]
This is with Courier New:

![Screenshot 2023-10-17 145329](https://github.com/AvaloniaUI/Avalonia/assets/5928797/76397f41-2b6f-4f0a-a707-c8dd6a90e180)
But it looks like there is an issue with the leading overhang

**Comment by Alshain01** [comment]
> Sorry forgot to mention, this happens with most of regular fonts (non-monospace) like Arial, Segoe, Times etc. I don't use InterFont.

But you are comparing characters with different widths.  What does it look like if you compare different permutations of the same characters?  Try the following:

12345
21345
32514

If these still produce the problem then there may be an issue, but it's likely this is not a bug.
