### ISSUE TITLE
Avalonia Visual Studio 2022 extension broken in the latest VS preview

### ISSUE THREAD

**Issue by bobasaurus** [AvaloniaUI/Avalonia#13306]
## Describe the bug

I just tried installing the "Avalonia for Visual Studio 2022" extension (11.4) in Microsoft Visual Studio Community 2022 (64-bit) - Preview, Version 17.8.0 Preview 4.0.  

When trying to create a new Avalonia C# Project, it shows an error dialog stating "Attempted to access a missing method":

![avalonia error](https://github.com/AvaloniaUI/Avalonia/assets/450407/a4d3d021-b2fd-438c-9a08-fa98c5a77f02)

Clicking "OK" just closes the error dialog, but you cannot proceed to create a new Avalonia project, it just shows the same error dialog again.  

There are similar complaints on the questions page of VS Marketplace:  https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaVS&ssr=false#qna

## To Reproduce

1. Install the latest preview version of visual studio community 2022
2. Install the latest Avalonia for Visual Studio 2022 extension (I installed it by downloading the extension file and double-clicking)
3. Try to create a new Avalonia C# Project
4. The error dialog prevents the project from being created

## Environment

- OS: Windows 10 x64
- Avalonia-Version: 11.4

**Comment by timunie** [comment]
Known issue. But we don't support the preview yet for backward compatibility.

**Comment by bobasaurus** [comment]
Got it, thanks.  I uninstalled preview and installed the regular VS 2022 instead... Avalonia works fine now.
