### ISSUE TITLE
Window does not take into account the specified Height and Width if it is launched in the minimised state

### ISSUE THREAD

**Issue by flexxxxer** [AvaloniaUI/Avalonia#13300]
## Describe the bug
If you set the `Window.WindowState` property in the constructor to `WindowState.Minimised`, then the window after unfolding (transition to `WindowState.Normal`) will not take into account the previously set (for example, through `ViewModel` or just in the constructor) `Window.Width` and `Window.Height.` 

## To Reproduce
1. Clone [this repo](https://github.com/flexxxxer/Avalonia.WindowSizeBug)
2. See [these lines](https://github.com/flexxxxer/Avalonia.WindowSizeBug/blob/master/Avalonia.WindowSizeBug/Views/MainWindow.axaml.cs#L9-L12): `MainWindow.Width`, `.Height` and `.WindowState` are set in the constructor.
3. Build and run app: window will be in minimized state.
4. After opening an application window (e.g. clicking in the taskbar), the application window will have a different size than the one specified. 

## Expected behavior
Application window size after application opening corresponds to the values set in the constructor.

## Screenshots
https://github.com/AvaloniaUI/Avalonia/assets/44833369/1ae5908c-2bbf-4858-bff2-139fb2752030

## Environment 

- OS: Windows 11
- Avalonia-Version: reproduced on 0.10.5, 0.10.10, 0.10.21, 11.0.0, 11.0.1, 11.0.2, 11.0.3, 11.0.4, 11.0.5

**Comment by Antonbreakble** [comment]
The reason is that resize only works for WindowState.Normal. In other cases it just return from Resize method input win32 WindowImpl
https://github.com/AvaloniaUI/Avalonia/blob/39ce0c206fe318c6a1dc820d6f5c16cacb188a82/src/Windows/Avalonia.Win32/WindowImpl.cs#L544-L547
