### ISSUE TITLE
Avalonia.Controls.Shapes.Sector does not fill

### ISSUE THREAD

**Issue by jpmikkers** [AvaloniaUI/Avalonia#13303]
## Describe the bug
When using Sector with SweepAngle < 360 degrees, it doesn't get filled.

## To Reproduce

- use this:

    `<Sector Width="100" Height="100" Fill="LightBlue" StartAngle="0" SweepAngle="45" StrokeThickness="1" Stroke="Black"/>`

- notice sector isn't filled
- once you modify sweepangle to above 360 it shows a circle that **is** filled with the correct color

## Expected behavior
The sector should be filled

## Screenshots
![Sector 2023-10-18 142644](https://github.com/AvaloniaUI/Avalonia/assets/10578746/6ae1c13f-283e-4f64-8955-9a672d70c1a6)

## Environment 

- OS: Win11
- Avalonia-Version: 11.0.5

## Additional context
I managed to find the problem cause in [src/Avalonia.Controls/Shapes/Sector.cs#L83](https://github.com/AvaloniaUI/Avalonia/blob/26035be8492883e93b12b432e541d1d683c49075/src/Avalonia.Controls/Shapes/Sector.cs#L83). The `isFilled` parameter should be true.

**Comment by robloo** [comment]
Good catch, that's a copy-paste bug because the original code was carried over from `Arc` that doesn't need to be filled.

I'll open a PR to fix this in a few minutes.

**Comment by jpmikkers** [comment]
nice! I was bored so I managed to create a unit test for it, see [https://github.com/jpmikkers/Avalonia/commit/ebf34a03defbe1c9a0a5e83db989886f466dfe59](https://github.com/jpmikkers/Avalonia/commit/ebf34a03defbe1c9a0a5e83db989886f466dfe59). Had to do some changes to Headless stubs to propagate the Fill property though..

**Comment by robloo** [comment]
@jpmikkers It might be overkill, but if you want feel free to open a PR for it. The only thing that might be debated is the headless changes. If it was me, I might render to a bitmap too and actually check for a color rather than a property being set. Seems safer and more robust.

**Comment by maxkatz6** [comment]
In a case of geometries/shapes, it's probably better to add a render test instead. We actually have some for other shapes: https://github.com/AvaloniaUI/Avalonia/tree/master/tests/Avalonia.RenderTests/Shapes
