### ISSUE TITLE
subpixel antialiased text rendering on Linux

### ISSUE THREAD

**Issue by nsrahmad** [AvaloniaUI/Avalonia#13310]
## Describe the bug
I tried setting `RenderOptions.TextRenderingMode="SubpixelAntialias"`, which does not have any effect. Tested on multiple linux distros (Linux mint and Void Linux) with as close to vanilla settings as possible.

Does anyone on Linux has subpixel antialiasing working?

## Environment 

- OS: Linux mint 21.2, Void linux KDE
- Avalonia-Version: 11.0.5

**Comment by Gillibald** [comment]
Only supported on Windows

**Comment by nsrahmad** [comment]
Thanks. good to know.
