### ISSUE TITLE
CaptionButtons FluentCaptionButton theme used hardcoded Background, Foreground and BorderBrush color

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#13341]
## Describe the bug

CaptionButtons FluentCaptionButton theme used hardcoded Background, Foreground and BorderBrushcolor.

## To Reproduce

https://github.com/AvaloniaUI/Avalonia/blob/77e1abcc68cd7d2433e4eef4edb7c4f27b551447/src/Avalonia.Themes.Fluent/Controls/CaptionButtons.xaml#L13

https://github.com/AvaloniaUI/Avalonia/blob/77e1abcc68cd7d2433e4eef4edb7c4f27b551447/src/Avalonia.Themes.Fluent/Controls/CaptionButtons.xaml#L74

## Expected behavior

CaptionButtons FluentCaptionButton theme used Background color set from style

## Environment 

- Avalonia-Version: 11.0.5 and master

**Comment by Alienmario** [comment]
Is it just me, or is this still not working?
Seeing the same artifact as in #13347 in the Avalonia.MusicStore demo app.

**Comment by hjred** [comment]
The caption button background (and border?) colors for minimize and maximize on hover and pressed still use the wrong colors in dark style with both the simple and the fluent theme.
For light and dark styles they are simply set to the same values as as in the light style which does not look correct when expanding the client area:

Simple light: https://github.com/AvaloniaUI/Avalonia/blob/3c317f5224fc74703892562e22f78849f0ba38ed/src/Avalonia.Themes.Simple/Accents/Base.xaml#L47
Simple dark: https://github.com/AvaloniaUI/Avalonia/blob/3c317f5224fc74703892562e22f78849f0ba38ed/src/Avalonia.Themes.Simple/Accents/Base.xaml#L92

Fluent light: https://github.com/AvaloniaUI/Avalonia/blob/3c317f5224fc74703892562e22f78849f0ba38ed/src/Avalonia.Themes.Fluent/Accents/FluentControlResources.xaml#L816
Fluent dark: https://github.com/AvaloniaUI/Avalonia/blob/3c317f5224fc74703892562e22f78849f0ba38ed/src/Avalonia.Themes.Fluent/Accents/FluentControlResources.xaml#L1634

As #13347 was closed as duplicate this should be the correct issue then?

**Comment by Alienmario** [comment]
Thank you, I was able to make a workaround by adding these resources to app style.
```xml
<!-- PointerOver -->
<SolidColorBrush x:Key="CaptionButtonBackground" Color="{DynamicResource SystemBaseLowColor}" />
<!-- Pressed -->
<SolidColorBrush x:Key="CaptionButtonBorderBrush" Color="{DynamicResource SystemBaseMediumLowColor}" />
```

<img width="118" height="36" alt="Image" src="https://github.com/user-attachments/assets/e45917dc-c4d0-442b-82ad-612c62170545" />

<img width="118" height="36" alt="Image" src="https://github.com/user-attachments/assets/72e32e53-48db-4be8-bf9f-2ace6e943373" />
