### ISSUE TITLE
ListBox within TabControl crashes when switching tabs

### ISSUE THREAD

**Issue by Jammyo** [AvaloniaUI/Avalonia#13344]
## Describe the bug
I have a tab control which I'm using for a preferences dialog. Within each tab, I want a scrollable list of options. I tried to put these inside a ListBox which works fine initially, but when I return to any tab which has already been opened, I get an exception: System.InvalidOperationException: The control already has a visual parent. I have been ignoring this issue for a few months, but finally need to resolve it to start building a feature for my product, and got the time this weekend to build a standalone example showing the problem.

## To Reproduce
See the attached project for a repro. Simply switch to tab two, then back to tab one.
[ListInsideTabControl.zip](https://github.com/AvaloniaUI/Avalonia/files/13063731/ListInsideTabControl.zip)

## Expected behavior
I expect tab one to be shown rather than the app crashing.

## Environment 

- OS: Tested on Windows and Mac with the same error.
- Avalonia-Version: 11, but before upgrading I was also experiencing this problem on 10 (I upgraded in the hopes that it had been fixed).

**Comment by timunie** [comment]
I don't know much about the WhenActivated stuff. I guess it is called another time when it gets activated again. If you bind in XAML instead, is your issue solved?

**Comment by Jammyo** [comment]
Ah, didn't even think of that for some reason. Thank you so much!
