### ISSUE TITLE
MenuItem PART_IconPresenter has hardcoded Width and Height in template

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#13342]
## Describe the bug

MenuItem PART_IconPresenter has hardcoded Width and Height in template.

https://github.com/AvaloniaUI/Avalonia/blob/77e1abcc68cd7d2433e4eef4edb7c4f27b551447/src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml#L90

## Expected behavior

MenuItem PART_IconPresenter Width and Height can be set from style.

## Environment 

- OS: 
- Avalonia-Version: 11.0.5 and master

**Comment by mgnslndh** [comment]
- Whould it be OK to control the size by dynamic resource? or is it more appropriate to use IconWidth/IconHeight properties on MenuItem?
- The ViewBox is set to have a StretchDirection=DownOnly which kind of defeats the purpose of controling size so I guess that needs to be removed.
- When I test various Height/Width combos with the ViewBox it seems to me that both Height and Width needs to be changed to the same value for the ViewBox to work properly. Does this mean it is enough to have one DynamicResource/Property to control the size?

**Comment by timunie** [comment]
IMO this is a totally valid scenario for dynamic resources and or child selector style

**Comment by maxkatz6** [comment]
Another option is to replace Viewbox with ContentControl, and set a custom ControlTheme on it with a template that includes Viewbox inside. This way it would be possible to replace the whole control theme on the PART_IconPresenter, as well as style specific parts:

```xaml
<!--  From MenuItem template: -->
<ContentControl x:Name="PART_IconPresenter"
                Theme="{StaticResource FluentMenuItemIconTheme}"
                Content="{TemplateBinding Icon}"
                IsVisible="False"
                Margin="{DynamicResource MenuIconPresenterMargin}" />
```

```xaml
<ControlTheme x:Key="FluentMenuItemIconTheme" TargetType="ContentControl">
    <Setter Property="Width" Value="16" />
    <Setter Property="Height" Value="16" />
    <Setter Property="Template">
        <Viewbox>
                 <!-- Fill other properties -->
                <ContentPresenter  x:Name="PART_ContentPresenter" />
        </Viewbox>
    </Setter>
</ControlTheme>
```

**Comment by maxkatz6** [comment]
The same could be later reused in https://github.com/AvaloniaUI/Avalonia/pull/11441

**Comment by maxkatz6** [comment]
Two disadvantages:
1. It adds some complexity, especially if there is no icon. But we can live with that for now.
2. Soft breaking change with styling, as PART_IconPresenter is of another type with this change. But minor breaking changes are acceptable for 11.1 release, as it won't break third-party libraries.
