### ISSUE TITLE
Window buttons (Minimize, Maximize) are wrong color when using ExtendClientAreaToDecorationsHint and dark theme

### ISSUE THREAD

**Issue by werdes** [AvaloniaUI/Avalonia#13347]
## Describe the bug
The window buttons for maximize and minimize actions are always white background on hover, regardless of theme selection (fluent, simple), when using the dark variants.

## To Reproduce
Create a 11.0.5 project, set the ExtendClientAreaToDecorationsHint property on your window to true, set  RequestedThemeVariant="Dark" in your App.axaml, run the project, hover over the window buttons

## Expected behavior
On light themes, the button foreground (the minimize/maximize icons) should be black, while the background should be white, or light gray on hover - this works fine.
On dark themes, the button foreground should be white (works), while the background should be dark gray (also works), and a lighter dark gray on hover (<-- this doesn't work).

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/7100506/8658fc73-dd29-47d6-a4fa-dd90c15c9cfc)
![image](https://github.com/AvaloniaUI/Avalonia/assets/7100506/587fa927-0a45-4cbb-b7d4-af813750488e)
![image](https://github.com/AvaloniaUI/Avalonia/assets/7100506/58faa91c-afeb-4bd2-8fa2-c8762e6db8d2)

## Environment 
- OS: Windows 10
- Avalonia-Version: 11.0.5

**Comment by wieslawsoltes** [comment]
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/13341

**Comment by timunie** [comment]
closing as duplicate
