### ISSUE TITLE
Bitmap.DecodeToWidth crashes on macOS m1 without any runtime exceptions

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#13359]
## Describe the bug

`Bitmap.DecodeToWidth` will crash on Apple M1 Systems without any runtime exceptions. Only with the macOS crash report.

## To Reproduce

Here are the codes for me to load an image to the Bitmap:

```c#
... // async context

try
 {
    await using var fs = File.OpenRead(path);
    var image = Bitmap.DecodeToWidth(fs, 256);

    await Dispatcher.UIThread.InvokeAsync(() => { ImageSource = image; });
}
catch (Exception e)
{
    Console.WriteLine(e);
    throw;
}

...
```

Application will always crash after the execution of `Bitmap.DecodeToWidth` even without jumping to the catch section

## Environment

- OS: macOS Sonoma 14.0
- Avalonia-Version: 11.0.5

## Additional context

macOS generated crash reports: [err.log](https://github.com/AvaloniaUI/Avalonia/files/13074666/err.log)

**Comment by maxkatz6** [comment]
But in SkiaSharp most likely: https://github.com/mono/SkiaSharp/issues/2645

**Comment by manuc66** [comment]
I had to implement this workarround : https://github.com/manuc66/ImgTagFanOut/commit/fb58f4bb7c331ea3881c1d0f45c3f4812e9300a1

**Comment by dbriard** [comment]
Arg, this bug is annoying, I am not sure I can use Skia 2.88.5 if Avalonia is using the 2.88.6 version.

**Comment by timunie** [comment]
if anyone wants to try SkiaSharp 3 preview if it would fix the issue: https://github.com/AvaloniaUI/Avalonia/pull/13900#issuecomment-1850339413

**Comment by AlexeiScherbakov** [comment]
Avalonia version 11.0.0 is working normally, but 11.0.6 crashes

**Comment by timunie** [comment]
@AlexeiScherbakov known but we had to upgrade SkiaSharp version for a good reason and we cannot downgrade even if we wanted to.

**Comment by Arcus92** [comment]
Had the same crash on Linux with `11.0.6` and an upgrade to `11.0.7` fixed the issue. Thanks!

**Comment by timunie** [comment]
@laolarou726 if issue is still reproducing in 11.0.7 ping me
