### ISSUE TITLE
I think it should sure the foreground.Opacity>0 when DrawText.

### ISSUE THREAD

**Issue by lindexi** [AvaloniaUI/Avalonia#1335]
https://github.com/AvaloniaUI/Avalonia/blob/3381c490e81483960147df465b0fa2a1adacbffe/src/Avalonia.Visuals/Media/DrawingContext.cs#L130

       public void DrawText(IBrush foreground, Point origin, FormattedText text)
        {
            Contract.Requires<ArgumentNullException>(text != null);

            if (foreground != null)
            {
                PlatformImpl.DrawText(foreground, origin, text.PlatformImpl);
            }
        }

But when the foreground.Opacity ==0 that cant draw text

**Comment by danwalmsley** [comment]
That might be handled at the rendering system level for all controls, @grokys would be able to say for sure.

**Comment by grokys** [comment]
Yes this is handled by the renderer itself, this way we don't need to put a check for 0 opacity in all the draw methods: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs#L252
