### ISSUE TITLE
Get alerts from program.cs in webassembly

### ISSUE THREAD

**Issue by CastelloBrancoTecnologia** [AvaloniaUI/Avalonia#13360]
When we have erros that cause exceptions in program.cs 
in webassembly, the developper does not have feedback of error.

Please improve program.cs of browser project to some like this
```
using System;
using System.Runtime.Versioning;
using System.Threading.Tasks;

using Avalonia;
using Avalonia.Browser;

[assembly: SupportedOSPlatform("browser")]

internal partial class Program
{
    private static async Task Main(string[] args)
    {
        try
        {
             await BuildAvaloniaApp()
                .WithInterFont()
                .StartBrowserAppAsync("out");
        }
        catch (Exception ex)
        {
            JSRuntime.InvokeVoidAsync ("alert", ex.Message);
        }
    }

    public static AppBuilder? BuildAvaloniaApp()
    {
        try
        {
            return AppBuilder.Configure<App>();
        }
        catch (Exception ex)
        {
            JSRuntime.InvokeVoidAsync ("alert", ex.Message);

            return null;
        }
    }
}
```

**Comment by maxkatz6** [comment]
You can add these alert calls using JSImport/JSExport if you need it for your application.
But it shouldn't be part of the default templates, especially as alerts are considered a bad practice in debugging.

As another alternative, simple Console.WriteLine or Console.Output works in WASM as a browser dev-tools console too.

**Comment by cesarchefinho** [comment]
> You can add these alert calls using JSImport/JSExport if you need it for your application. But it shouldn't be part of the default templates, especially as alerts are considered a bad practice in debugging.

Not only, to debugging , but to show to user that an exception ocours and not an blank window.

 bad practices is having a default avalonia implementation that dont handle exceptions end crash with an bkank window
> 
> As another alternative, simple Console.WriteLine or Console.Output works in WASM as a browser dev-tools console too.

I like the console to orogrammer, but the user need to be informed that some is wrong
