### ISSUE TITLE
CollapseRowGroup System.NullReferenceException

### ISSUE THREAD

**Issue by ge73roma** [AvaloniaUI/Avalonia#13375]
By applying two groups to the DataGridCollectionView, the CollapseRowGroup throws a System.NullReferenceException. 
I attach the code used, any ideas? Thanks to anyone who will help me
With just one group, it works
I use avalonia 11.0
```
var collectionView2 = new DataGridCollectionView(((MainWindowViewModel)this.DataContext).ListInfoProject);
                collectionView2.GroupDescriptions.Add(new DataGridPathGroupDescription("Application"));
                collectionView2.GroupDescriptions.Add(new DataGridPathGroupDescription("Version"));
                this.FindControl<DataGrid>("dgInfoProject").ItemsSource = collectionView2;

                if (collectionView2.Groups != null)
                    foreach (var v in collectionView2.Groups)
                        if (v is DataGridCollectionViewGroup group)
                            this.FindControl<DataGrid>("dgInfoProject").CollapseRowGroup(group, true);
```

**Comment by ge73roma** [comment]
var collectionView2 = new DataGridCollectionView(((MainWindowViewModel)this.DataContext).ListInfoProject);
                collectionView2.GroupDescriptions.Add(new DataGridPathGroupDescription("Application"));
                collectionView2.GroupDescriptions.Add(new DataGridPathGroupDescription("Version"));
                this.FindControl<DataGrid>("dgInfoProject").ItemsSource = collectionView2;

                HashSet<DataGridCollectionViewGroup> groups = new HashSet<DataGridCollectionViewGroup>();

                foreach (object item in this.FindControl<DataGrid>("dgAPFiles").ItemsSource)
                    **groups.Add(this.FindControl<DataGrid>("dgAPFiles").GetGroupFromItem(item, 0));**

By inserting level 0 (closing all levels) it goes into exception null, by inserting level 1 (sublevel), it closes the child levels but not the parent level.

**Comment by timunie** [comment]
I guess you have different levels of grouping, so if have group and level mixed up, it will return null by design. What works for me is this if I wanted to collapse all groups including childs: 

```cs
// We do this on window loaded as it need the controls to be actually loaded, constructor will fail

protected override void OnLoaded(RoutedEventArgs e)
{
	base.OnLoaded(e);

        // Get the CollectionView
	var items = (dg.DataContext as MainWindowViewModel)!.MyItems;

        // Cycle over all groups
	foreach (var group in items.Groups)
	{
		if (group is DataGridCollectionViewGroup description)
		{
			dg.CollapseRowGroup(description, true);
		}
	}
}
```
