### ISSUE TITLE
Previewer doesn't work for particular project on Avalonia 11.0.0-preview4

### ISSUE THREAD

**Issue by ForNeVeR** [AvaloniaUI/Avalonia#13399]
_(Originally reported as https://github.com/ForNeVeR/AvaloniaRider/issues/304)_

## Describe the bug
Previewer doesn't work for project https://github.com/ddorab/lumper

## To Reproduce
1. Open the project in VS or Rider
2. Go to `Lumper.UI/Views/MainWindow.axaml`
3. See how previewer doesn't show anything.

## Expected behavior
Well, it should work, I believe.

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/92793/6dcb68e3-c405-4475-8a26-0d5c9af0bd36)

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.0-preview4

## Additional context
There's nothing interesting in the previewer process stdout in Rider.

**Comment by stevemonaco** [comment]
`MainWindowViewModel` has some crusty code that shouldn't be in a VM:
```cs
public MainWindowViewModel()
{
    if (Application.Current?.ApplicationLifetime is not IClassicDesktopStyleApplicationLifetime desktop)
        throw new InvalidCastException(
            nameof(Application.Current.ApplicationLifetime));
```

With errors:
```
08:11:39.424 [Debug] 3848 <= UpdateXamlResultMessage { Error: "System.Reflection.TargetInvocat…", Handle: null, Exception: ExceptionDetails { ExceptionType: "InvalidCastException", Message: "ApplicationLifetime", LineNumber: null, LinePosition: null } }
08:11:39.426 [Error] 3848 UpdateXamlResult error
System.Xaml.XamlException: ApplicationLifetime
```

`Application.Current` appears to be null in the previewer (I wrote out state to a file). I'm not sure of the lifecycle of the designer, so maybe someone else can clarify why this is the case.

Besides that, there should be some way to send output to Avalonia Diagnostics in IDE. I tried `Console.WriteLine`, `Debug.WriteLine`, and `Trace.WriteLine` without luck.

**Comment by timunie** [comment]
Is it reproducible in 11.0 stable branch? I mean preview 4 is really much outdated as of today.

**Comment by stevemonaco** [comment]
Yes, it still happens in 11.0.5 / AvaloniaVS 11.4. There's an exception in the VM ctor because the current application doesn't exist (while previewing). The previewer doesn't like that and the reported information is a bit minimal in helping track the cause down, even on Verbose. Granted, the message provided to the thrown `InvalidCastException` in the original app was also minimal.

**Comment by timunie** [comment]
Ah yeah, that doesn't work and this is by design. In that case a check `if (Deisng.IsDesignTime) ...` is needed to make the app run. 

In general better to use a different approach to get the window or lifetime.

**Comment by timunie** [comment]
@ForNeVeR https://github.com/ddorab/lumper/blob/c201ce60e6c09bbda465a2ade7d1e68275d2c4c6/src/Lumper.UI/ViewModels/MainWindowViewModel.cs#L25 

if you comment out this line, the previewer should work again. Can you verify it? I don't know what exactly Avalonia could do to improve this situation as the previewer simply has no DesktopLifetime.

**Comment by timunie** [comment]
okay in a simpler test App I tried the code linked above. If I modify it like shown below, previewer works again: 
```cs
if (!Design.IsDesignMode && Application.Current?.ApplicationLifetime is not
    IClassicDesktopStyleApplicationLifetime desktop) ...
```

So imo this is by design. If anyone disagrees, let me know and I'll reopen the issue.

**Comment by michaelkruglos** [comment]
The templates for new projects should enable preview, like in the message above IMO

**Comment by maxkatz6** [comment]
@michaelkruglos message above is strictly a workaround for an existing project. It's not applicable for new templates.
