### ISSUE TITLE
TextBlock with leading whitespace is too wide

### ISSUE THREAD

**Issue by runelkrone** [AvaloniaUI/Avalonia#13396]
When TextBlock.Text starts with a space character, it renders the leading character wider than it should.

It can easily be seen using this code
```
<StackPanel>
  <TextBlock Text=" + " HorizontalAlignment="Center"/>
  <TextBlock Text="a + b" HorizontalAlignment="Center"/>
  <TextBlock Text="+" HorizontalAlignment="Center"/>
</StackPanel>
```

In the top image you see that the leading space is much larger than the trailing space.
In the middle image you see that when the space is preceded by a character it is the correct size.
![image](https://github.com/AvaloniaUI/Avalonia/assets/21201782/53ae67c5-d3f7-4850-9858-78fe4189f333)

- OS: Windows 11
- Avalonia-Version:  11.4

**Comment by Gillibald** [comment]
Fixed in current master
