### ISSUE TITLE
FileTypeFilter can be bypassed on KDE

### ISSUE THREAD

**Issue by IsaacMarovitz** [AvaloniaUI/Avalonia#13426]
## Describe the bug
On KDE file picker dialogues, an "all files" option is available even when it is undesirable. This means FileTypeFilters can be bypassed where they cannot be on other platforms such as macOS. 

## To Reproduce
Run OpenFilePickerAsync and include a restrictive FileTypeFilter. In the options of the resulting dialogue, you can disable the filter on KDE. 

## Expected behavior
Filter is not bypassable.

## Screenshots
![Filter](https://github.com/AvaloniaUI/Avalonia/assets/42140194/bfcb8d50-1d9b-4214-b8e5-294232b8eac9)
![Filter Gone](https://github.com/AvaloniaUI/Avalonia/assets/42140194/a46d1a46-894c-48f2-a69a-07f6fd0df610)

Only `.nsp` should be selectable in this instance.

## Environment

- OS: Arch Linux
- Avalonia-Version: 11.0.4

**Comment by kekekeks** [comment]
File type filter can be bypassed even on windows if you enter the file name in quotes. 
That's a platform behavior we don't have any control of, you can try enabling the managed file picker in X11PlatformOptions.
