### ISSUE TITLE
Add an interface IMarkupExtension

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#13424]
## Is your feature request related to a problem? Please describe.
One can just add ProvideValue method sure, but the interface would make sure the names and parameters are what is expected by Avalonia. Inheriting MerkupExt also not always works as you may want to derive from other classes. The IDE can add the missing method which is very convenient 

## Describe the solution you'd like
Add the interface in addition to the already implemented options

## Describe alternatives you've considered
Remember the syntax better.

## Additional context
I can pick up the PR if I get an okay for that.

**Comment by maxkatz6** [comment]
Well. One can simply create a custom interface IMarkupExtension and use it. It still will work via duck typing.
But in general, it really feels like a really unnecessary feature that brings new optional API.

**Comment by timunie** [comment]
closing as per comment
