### ISSUE TITLE
AutoCompleteBox should have a bindable Property for CaretIndex

### ISSUE THREAD

**Issue by CodeDevAM** [AvaloniaUI/Avalonia#13463]
An AutoCompleteCox should have a bindable property for the CaretIndex of the underlying TextBox. The CaretIndex is a very useful information when using the AutoCompleteBox with a custom Populator.

This would make a workaround like this https://github.com/AvaloniaUI/Avalonia/discussions/13423#discussioncomment-7454283 unnecessary.

**Comment by timunie** [comment]
sounds like a good idea to me at lease. So as far as I can tell, any PR would be welcome.
