### ISSUE TITLE
Simplest custom control based on Button doesn't display, but Button does

### ISSUE THREAD

**Issue by buzzware** [AvaloniaUI/Avalonia#13467]
## Describe the bug

A Button inside a grid displays, but the simplest custom control based on Button does not.

What is wrong with this custom control ?

```
<Button 
	xmlns="https://github.com/avaloniaui"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
	xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
	mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
	x:Class="CustomControlPlay.RedButton"
	Background="Red"
/>

```

## To Reproduce

Clone and run this repo https://github.com/buzzware/CustomControlPlay

## Expected behavior

The green rectangle and red button on the left are standard controls.
The green rectangle and red button on the right are the simplest possible custom control subclassing the same class as the left.
Both rectangles appear, but the button custom control does not - why?

## Screenshots

<img width="594" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/28285/da3db225-0b56-42d4-9dce-d4efd00da0bc">

## Environment 

- OS: Mac
- Avalonia-Version: 11.0.2

**Comment by timunie** [comment]
either add the needed Style or override StyleKey in MyButton.cs

**Comment by buzzware** [comment]
This was answered in Telegram :

> Steve Monaco, [2 Nov 2023 at 9:23:48 pm (2 Nov 2023 at 9:33:59 pm)]:
> There's no style and therefore no ControlTemplate. So therefore no visual children are added. The easy fix is to do this to specify the Button style:
> public partial class RedButton : Button
> {
>     protected override Type StyleKeyOverride => typeof(Button);
> 
>     public RedButton()
>     {
>         InitializeComponent();
>     }
> }
> 
> Before that, you can verify that the RedButton has no visual children by using DevTools (press F12 in app while debugging)
> 

Could the style be inherited by default when you subclass ?

**Comment by timunie** [comment]
> Could the style be inherited by default when you subclass ?

No, you need to do it on your own by adding the StyleKeyOverride. For most users it's not intended to override the styles.
