### ISSUE TITLE
SuggestedStartLocation is not working for DBus open file pickers

### ISSUE THREAD

**Issue by HermanKirshin** [AvaloniaUI/Avalonia#13477]
## Describe the bug
If you pass any value there result is:
![image](https://github.com/AvaloniaUI/Avalonia/assets/25755704/5dfcc2c4-c5f2-4a61-8d08-200a3a52639c)

## To Reproduce

```       
        Uri.TryCreate("file://" + "/home/user/Downloads", UriKind.Absolute, out var uri);        
        var folder = await this.StorageProvider.TryGetFolderFromPathAsync(uri);    
        await StorageProvider.SaveFilePickerAsync(new FilePickerSaveOptions()
        {
            //SuggestedFileName = "Test.txt",
            SuggestedStartLocation = folder
        });
```

## Expected behavior
File picker opened at specified path w/o error

## Environment 

- OS: Ubuntu 22.04.3 LTS (Gnome)
- Avalonia-Version: 11.0.5

## Workaround

Use GTK Dialogs by setting UseDBusFilePicker = false in X11PlatformOptions

**Comment by HermanKirshin** [comment]
With TryGetWellKnownFolderAsync(Downloads) it fails with same error, and in real app we save last used folder, so it may be any path.

Just suggestion - according to comment you mentioned they expect null-terminated value, but Encoding.UTF8.GetBytes(folderPath) returns string w/o null termination. I'll try to experiment with these parameters and return with results.

**Comment by HermanKirshin** [comment]
Yes, adding \0 solves the problem with save dialog (I'll make PR). But open dialog just ignores SuggestedStartLocation, and always opens at Recents

**Comment by maxkatz6** [comment]
> But open dialog just ignores SuggestedStartLocation, and always opens at Recents

It looks like "current_folder" parameter for open file dialog was added only recently (5 months ago according to git blame in the org.freedesktop.portal.FileChooser file). Our backend currently doesn't even try to set this property.
It should be added with a dbus version check https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.portal.FileChooser.xml#L158-L160

**Comment by maxkatz6** [comment]
> Yes, adding \0 solves the problem with save dialog

It seems it was removed accidentally while migrating to source-generated dbus mappings. Good find.

**Comment by HermanKirshin** [comment]
> It looks like "current_folder" parameter for open file dialog was added only recently (5 months ago according to git blame in the org.freedesktop.portal.FileChooser file). Our backend currently doesn't even try to set this property.

Yep, I tried to set it, but DBus in my setup is ignoring it, I think because of older version.

**Comment by maxkatz6** [comment]
Maybe. But keeping version checks should be safer for some other distributives just in case.

**Comment by HermanKirshin** [comment]
Looks like smth fishy is going on also in Tmds.DBus.SourceGenerator.GetVersionPropertyAsync (which is called in DBusSystemDialog). I tried to use its result for version check, but it returns to me value 29953 which obviously looks weird. While in dbus-monitor value is 3
![image](https://github.com/AvaloniaUI/Avalonia/assets/25755704/030debc9-a044-47dc-8517-06e53225e3a5)
I looked to message body content via debugger, it has total size 8 instead of 4 and contains value 3 but with offset of 4 bytes, and GetVersionPropertyAsync takes only first 4.
![image](https://github.com/AvaloniaUI/Avalonia/assets/25755704/51d0ba11-8034-4e22-a2ec-a91f2c3f80c8)

**Comment by workgroupengineering** [comment]
@affederaffe

**Comment by affederaffe** [comment]
> I think it should call ReadSignature before, like it is done in GetAllProperties, and content also points to this, because 117 is character 'u', which is also expected in 'version' read by GetAllProperties. So probably using GetAllProperties instead GetVersion may be a workaround.

Fixed with https://github.com/affederaffe/Tmds.DBus.SourceGenerator/commit/7258a96676c96375075657aae8c68a8d0ca6ebce

**Comment by HermanKirshin** [comment]
@affederaffe when to expect new package version? As I see latest version 0.0.11 on nuget.org was released day before this fix

**Comment by affederaffe** [comment]
0.0.11 seems to have this fix as far as I can tell.

**Comment by HermanKirshin** [comment]
Version check works good now. But I was not able to test it with version 4 because I have not yet linux environments with it.
