### ISSUE TITLE
Editing axaml file has no intellisense (code-completion) in Visual Studio 2022

### ISSUE THREAD

**Issue by arviedelgado** [AvaloniaUI/Avalonia#13486]
## Describe the bug
Editing _axaml_ file has no intellisense (code-completion) in Visual Studio 2022

## To Reproduce

1. Install Visual Studio 2022.
![image](https://github.com/AvaloniaUI/Avalonia/assets/11804514/3342e7dd-21df-4dd3-9839-33e3777d7f99)
2. Install Avalonia VS Extension (https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaVS)
![image](https://github.com/AvaloniaUI/Avalonia/assets/11804514/96477e0f-744d-4c42-bca8-c3fafab7385d)
3. Create a new Avalonia C# Project.
![image](https://github.com/AvaloniaUI/Avalonia/assets/11804514/bf56279e-e6eb-4628-afa4-ba1c0e067415)
4. Edit "MainView.axaml" file, type "<" to add controls (e.g., <Button/>) and trigger intellisense
![image](https://github.com/AvaloniaUI/Avalonia/assets/11804514/0321ae84-1621-417d-baa6-77c9ac805385)
5. Error: Intellisense (code-completion) is not showing any relevant suggestions

## Expected behavior
Editing axaml file should have intellisense. here is an example for a WPF application editing a _xaml_ file.
![image](https://github.com/AvaloniaUI/Avalonia/assets/11804514/08130262-2739-4376-bc39-772882c9309e)

**Comment by workgroupengineering** [comment]
Before start editing, you must build .

**Comment by timunie** [comment]
As @workgroupengineering said, an initial build is needed to make the editor work. This is by design.

**Comment by arviedelgado** [comment]
> As @workgroupengineering said, an initial build is needed to make the editor work. This is by design.

Thanks, that helps!

However, looks like the "initial build" solution does not work if the target platform is "Web" only.

![image](https://github.com/AvaloniaUI/Avalonia/assets/11804514/64ada346-22d9-48f4-ba7d-237f0b360a99)

![image](https://github.com/AvaloniaUI/Avalonia/assets/11804514/9fc7556e-6f20-4cbe-add2-502d9de923fc)

![image](https://github.com/AvaloniaUI/Avalonia/assets/11804514/b854a3e3-4bbe-4f4a-92a7-32460b76bb48)

**Comment by timunie** [comment]
I'd highly recommend to also target desktop always. Much easier to debug imo, then take care of web after the main things work as expceted.

**Comment by DaiYu-233** [comment]
After I built it, I still have this problem

**Comment by Dblm0** [comment]
> After I built it, I still have this problem

The latest extension seems broken
Try this one https://marketplace.visualstudio.com/_apis/public/gallery/publishers/AvaloniaTeam/vsextensions/AvaloniaVS/11.5/vspackage. And disable auto updates for extensions.
Worked for me.

**Comment by Julimuz** [comment]
> > After I built it, I still have this problem
> 
> The latest extension seems broken Try this one https://marketplace.visualstudio.com/_apis/public/gallery/publishers/AvaloniaTeam/vsextensions/AvaloniaVS/11.5/vspackage. And disable auto updates for extensions. Worked for me.

This work for me too

Thanks!

**Comment by ProviceUnify** [comment]
Suffering this issue from start of developing at Avalonia in Visual Studio. 11.5 didn't resolved my problem.
Arch: x64,
Native: Off,
Build: successful

![image](https://github.com/user-attachments/assets/cab7e41c-6579-465e-9b20-f699681ad527)
![image](https://github.com/user-attachments/assets/ee766e46-c7df-447e-b4bd-81e83796787e)
![image](https://github.com/user-attachments/assets/bc9de3d1-7b12-4a49-b303-4af1707b89ab)
![image](https://github.com/user-attachments/assets/be2548a2-f680-4afa-99bb-cbbfcd44efde)
![image](https://github.com/user-attachments/assets/d5caf8ce-5774-4e9f-ad1a-8d7d8da716f8)

But, sometimes it is starting work until next rebuild/solution clear/solution reopen

**Comment by malex81** [comment]
I have problem with IntelliSense in 2026.

<img width="565" height="76" alt="Image" src="https://github.com/user-attachments/assets/ca08333c-baa1-47c3-af85-4730ca341276" />

**Comment by maxkatz6** [comment]
@malex81 can you open a new issue at [AvaloniaVS](https://github.com/AvaloniaUI/AvaloniaVS) repository? Ideally with a minimal repro.
