### ISSUE TITLE
Opengl controls are not available on web platforms.

### ISSUE THREAD

**Issue by CeSun** [AvaloniaUI/Avalonia#13494]
Does the wasm platform not support OpenGlControlBase controls? The OnOpenGlInit and OnOpenGlRender functions do not trigger.

Avalonia Version: **11.0.5**

Browser: Microsoft Edge 119.0.2151.44

Code：

```c#
using Avalonia.OpenGL;
using Avalonia.OpenGL.Controls;
using Silk.NET.OpenGLES;
using System.Drawing;

namespace AvaloniaApplication1
{
    public class OpenglControl : OpenGlControlBase
    {
        protected override void OnOpenGlRender(GlInterface gl, int fb)
        {
            var api = GL.GetApi(gl.GetProcAddress);

            api.ClearColor(Color.AliceBlue);
            api.Clear(ClearBufferMask.ColorBufferBit);
        }
    }
}
```

```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:vm="clr-namespace:AvaloniaApplication1.ViewModels"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
			 xmlns:cc="using:AvaloniaApplication1"
             x:Class="AvaloniaApplication1.Views.MainView"
             x:DataType="vm:MainViewModel">
  <Design.DataContext>
    <!-- This only sets the DataContext for the previewer in an IDE,
         to set the actual DataContext for runtime, set the DataContext property in code (look at App.axaml.cs) -->
    <vm:MainViewModel />
  </Design.DataContext>
	<cc:OpenglControl ></cc:OpenglControl>
</UserControl>

```

![image](https://github.com/AvaloniaUI/Avalonia/assets/54771283/5a77d1d6-55a7-42b4-ba27-5d4b6e977b1e)

**Comment by LucasGandel** [comment]
This is still happening with 11.0.7 and master on Chrome (121.0.6167.85).
The webGL context seems to be initialized, and the constructor of OpenGLControlBase is called.

Any insight from an Avalonia-GL-wasm expert would be highly appreciated.
Could it be an issue with missing emscripten main_loop function calls or similar?
I'm happy to contribute but not really sure where to start.

@CeSun It could also be interesting to see how a SDL2 window embedded in a NativeHostControl behaves? That could potentially be an option to wrap the OpenGL rendering in a window container.

**Comment by zacoons** [comment]
According to the Avalonia team "browser backend doesn't support OpenGL control currently". They plan to add support in the future but it's "currently out of scope for nearest releases".
+1 to adding it.

**Comment by maxkatz6** [comment]
It's supported now, but only via CreateCustomVisual + TryLeasePlatformGraphicsApi.
See https://github.com/AvaloniaUI/Avalonia/pull/15707/files#diff-845bedf883f3a87ad8e4154a7696a9d55f862ea2e97c7d825069a038e0f5c466R23 as an example.

**Comment by maxkatz6** [comment]
Plain OpenGlControlBase won't be supported on browser, as it has complication with contexts.

**Comment by vpenades** [comment]
for web browsers, maybe it would make more sense to create a WebGPUControlBase  supporting WebGPU instead

**Comment by CeSun** [comment]
> for web browsers, maybe it would make more sense to create a WebGPUControlBase supporting WebGPU instead

I want to develop a small 3D control, but I don't have the ability to handle rhi well

**Comment by kekekeks** [comment]
>maybe it would make more sense

It would but SkiaSharp uses an old Skia version that doesn't support WebGPU.
