### ISSUE TITLE
TransitioningContentControl issue

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#13493]
## Describe the bug

TCC will throw an exception when switch back to the old content:
Even I ensured control's Visual Parent is cleared:

<img width="536" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/25716486/9038a0ba-2ead-41af-8dd4-f193ae299e3a">

I tried to write a repro but I failed to do so.

## Expected behavior

Content should switch between old and new content.

## Environment 

- OS: Windows 11 22H2
- Avalonia-Version: 11.0.5

**Comment by laolarou726** [comment]
Okay, I just successfully created a repro for this issue:

```diff
! There is a possible photosensitive epilepsy warning, and there is a 100ms fast page switching in the recurrence.
```

[https://github.com/laolarou726/TCCExceptionTest](https://github.com/laolarou726/TCCExceptionTest)

Download and build the repro, then click the `Start` button, then wait for a few seconds, and the exception will pop.

**Comment by laolarou726** [comment]
It seems when I changing the content for a TCC that is inside another TCC will cause this issue. My repro has the similar structure.

**Comment by timunie** [comment]
are you setting the content directly? Imo it would be much safer to use DataTemplates instead of setting the content directly.

**Comment by laolarou726** [comment]
> are you setting the content directly? Imo it would be much safer to use DataTemplates instead of setting the content directly. 

But in this case it's impossible to use the DataTemplate to replace the content setting right. I'm using the TCX as the NavigationFrame here.

**Comment by laolarou726** [comment]
My current temporary solution is this:

Rewrite the Theme of the TCC like this:

```xaml
<ControlTheme x:Key="{x:Type TransitioningContentControl}"
                  TargetType="TransitioningContentControl">
        <!--  Set Defaults  -->
        <Setter Property="Template">
            <ControlTemplate>
                <Panel>
                    <ContentPresenter Name="PART_ContentPresenter"
                                      Background="{TemplateBinding Background}"
                                      BorderBrush="{TemplateBinding BorderBrush}"
                                      BorderThickness="{TemplateBinding BorderThickness}"
                                      CornerRadius="{TemplateBinding CornerRadius}"
                                      ContentTemplate="{TemplateBinding ContentTemplate}"
                                      Content="{TemplateBinding Content}"
                                      Padding="{TemplateBinding Padding}"
                                      VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}"
                                      HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}" />
                    <ContentPresenter Name="PART_TransitionContentPresenter"
                                      Background="{TemplateBinding Background}"
                                      BorderBrush="{TemplateBinding BorderBrush}"
                                      BorderThickness="{TemplateBinding BorderThickness}"
                                      CornerRadius="{TemplateBinding CornerRadius}"
                                      ContentTemplate="{TemplateBinding ContentTemplate}"
                                      Padding="{TemplateBinding Padding}"
                                      VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}"
                                      HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}" />
            </Panel>
        </ControlTemplate>
    </Setter>
</ControlTheme>
```

Then everything will work just fine except all the transition animations will be loss. But the page switch will be fine.

**Comment by laolarou726** [comment]
@timunie @MrJul Does this bug have anything to do with this [PR #12173](https://github.com/AvaloniaUI/Avalonia/pull/12173)？

**Comment by timunie** [comment]
Could be, yeah. If you test a release just before that PR was merged, is the issue resolved? 

I don't know what a proper solution would be. The TCC is kind of nightmare to me 😃

/cc @danielmayost

**Comment by laolarou726** [comment]
> Could be, yeah. If you test a release just before that PR was merged, is the issue resolved?
> 
> I don't know what a proper solution would be. The TCC is kind of nightmare to me 😃
> 
> /cc @danielmayost

Just created a PR to fix this issue, it should be good right now. https://github.com/AvaloniaUI/Avalonia/pull/13518
