### ISSUE TITLE
`ExtendClientAreaToDecorationsHint` window covered by `TabControl` can't be dragged by its title

### ISSUE THREAD

**Issue by lostmsu** [AvaloniaUI/Avalonia#13492]
## Describe the bug
It is impossible to drag a window by its title when the window has `ExtendClientAreaToDecorationsHint` == `True` and is covered by a `TabControl`.

## To Reproduce

1. Create a window like this:
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="Avalonia_CantDrag.MainWindow"
        ExtendClientAreaToDecorationsHint="True"
        Title="Can't drag me">
  <Grid>
    <TabControl Background="Transparent"/>
  </Grid>
</Window>
```

2. Launch the app
3. Try dragging window by its titlebar

## Expected behavior
The window should move

## Screenshots
N/A

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.5

## Additional context
Removing `TabControl` or replacing it with a non-empty `TextBlock` makes window draggable again.

**Comment by timunie** [comment]
That's by design. TabControl is Hittest visible which means it will not pass the pointer events throug. Try to set Background to `x:Null`.
