### ISSUE TITLE
Bitmap should implement IDisposable

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#135]

**Comment by danwalmsley** [comment]
Is this resolved now?

**Comment by kekekeks** [comment]
Nope.
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Platform/IBitmapImpl.cs

**Comment by kekekeks** [comment]
It's the same for icons. We are leaking resources.

**Comment by kekekeks** [comment]
We need some kind of ref-counting infrastructure, so bitmaps captured by DeferredRenderer won't get prematurely disposed.
