### ISSUE TITLE
DataGrid should support inertial scrolling

### ISSUE THREAD

**Issue by stogle** [AvaloniaUI/Avalonia#13502]
## Is your feature request related to a problem? Please describe.
`DataGrid` does not support inertial scrolling when using touch gestures to scroll, unlike other controls that use `ScrollViewer` internally. This makes it harder to use on touch-enabled devices.

## Describe the solution you'd like
`DataGrid` should have an `IsScrollInertiaEnabled` property, just like `ScrollViewer` does, that is true by default.

## Describe alternatives you've considered
I'm able to enable inertial scrolling by adding a `TemplateApplied` event handler to the `DataGrid`, finding its `DataGridRowPresenter`, finding that object's `ScrollGestureRecognizer`, and setting `IsScrollInertiaEnabled` to true, but it is convoluted and needs to be done for every `DataGrid` in my application. Perhaps there is an easier way?

## Additional context
I think this can be implemented the same way it is done in ScrollViewer, by adding a property to [DataGrid.cs](https://github.com/AvaloniaUI/Avalonia/blob/52cbe29916fb8ab62837257cbb8e5d63a1e4ed37/src/Avalonia.Controls.DataGrid/DataGrid.cs):
```
        /// <summary>
        /// Defines the <see cref="IsScrollInertiaEnabled"/> property.
        /// </summary>
        public static readonly AttachedProperty<bool> IsScrollInertiaEnabledProperty =
            AvaloniaProperty.RegisterAttached<ScrollViewer, Control, bool>(
                nameof(IsScrollInertiaEnabled),
                defaultValue: true);

        /// <summary>
        /// Gets or sets whether scroll gestures should include inertia in their behavior and value.
        /// </summary>
        public bool IsScrollInertiaEnabled
        {
            get => GetValue(IsScrollInertiaEnabledProperty);
            set => SetValue(IsScrollInertiaEnabledProperty, value);
        }
```
then changing the [Fluent](https://github.com/AvaloniaUI/Avalonia/blob/b62b00d7e134e0a32042ec08a3c61cadf6ec9208/src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml#L532-L539) and [Simple](https://github.com/AvaloniaUI/Avalonia/blob/b62b00d7e134e0a32042ec08a3c61cadf6ec9208/src/Avalonia.Controls.DataGrid/Themes/Simple.xaml#L336-L343) templates to use it:
```
              <DataGridRowsPresenter Name="PART_RowsPresenter"
                                     Grid.Row="1"
                                     Grid.ColumnSpan="2"
                                     ScrollViewer.IsScrollInertiaEnabled="{TemplateBinding IsScrollInertiaEnabled}">
                <DataGridRowsPresenter.GestureRecognizers>
                  <ScrollGestureRecognizer CanHorizontallyScroll="True"
                                           CanVerticallyScroll="True"
                                           IsScrollInertiaEnabled="{Binding (ScrollViewer.IsScrollInertiaEnabled), ElementName=PART_RowsPresenter}" />
                </DataGridRowsPresenter.GestureRecognizers>
```
If this is the right approach I would be happy to submit a pull request.

**Comment by maxkatz6** [comment]
Yes, previously there wasn't `IsScrollInertiaEnabled` property, and inertia was enabled always with touch input. 
It seems DataGrid was missed when IsScrollInertiaEnabled property was added.

Your proposal changes make sense. Except, you can try to create a property definition with AddOwner:
```
        public static readonly AttachedProperty<bool> IsScrollInertiaEnabledProperty =
            ScrollViewer.IsScrollInertiaEnabledProperty.AddOwner<DataGrid>();
```

**Comment by timunie** [comment]
@stogle I assigned you as you mentioned you want to contribute. If that changes, let me know. Your help is welcome ❤️

**Comment by stogle** [comment]
> @stogle I assigned you as you mentioned you want to contribute. If that changes, let me know. Your help is welcome ❤️

Thanks @timunie, I created !13511 and the checks passed but it didn't give me a link to a package I can use for testing?
