### ISSUE TITLE
The "ContextRequested" event does not work correctly on touchscreens

### ISSUE THREAD

**Issue by Elorucov** [AvaloniaUI/Avalonia#13508]
## Describe the bug
While holding the Button control on touchscreens, ```ContextRequested``` event fires twice and ```Click``` event also fires.

## To Reproduce
1. Create a new window with this XAML:

```xml
  <Grid RowDefinitions="* 2*">
    <Button HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Click="Button_Click" ContextRequested="Button_ContextRequested" Content="Click me!"/>
    <TextBlock x:Name="log" Grid.Row="1" FontFamily="Consolas" FontSize="13"/>  
  </Grid>
```

...and this code:

```csharp
    private void Button_Click(object? sender, Avalonia.Interactivity.RoutedEventArgs e) {
        string r = $"CLICKED!\n";
        r += $"Source type: {e.Source?.GetType()}\n";
        log.Text += r + "\n";
    }

    private void Button_ContextRequested(object? sender, ContextRequestedEventArgs e) {
        string r = $"CONTEXT REQUESTED!\n";
        r += $"Source type: {e.Source?.GetType()}\n";
        log.Text += r + "\n";
    }
```

2. After launch, hold on button on touchscreen.

When holding down the button, ```ContextRequested``` event fires twice. When releasing the button, ```Click``` event fires.

## Expected behavior
While holding down on Button, ```ContextRequested``` event fires only once, and releasing the Button does not fire ```Click``` event (like in UWP).

## Screenshots
![photo_2023-11-06_16-10-14](https://github.com/AvaloniaUI/Avalonia/assets/22731185/ad73dff2-b7f8-4295-a68a-8a9f282cda96)

## Environment 

- OS: Windows 11 23H2
- Avalonia-Version: 11.0.5

**Comment by maxkatz6** [comment]
ContextRequested should be raised once on inner ContentPresenter and bubbled up. For some reason it was raised second time on a Button (Source=Button).  This is a bug.

But not sure about Click, since ContextRequested event wasn't Handled=true. But if UWP does it differently, we should be at least consistent with it.

**Comment by Elorucov** [comment]
I decided to check the code above in the UWP project, and found out that the ```Click``` event also fires after holding down and releasing the button. It’s strange that I haven’t seen this behavior in UWP apps, so this may not be considered a bug.

However, I want the ```Click``` event not to be triggered. I added the line ```args.Handled = true``` into ```ContextRequested```, but it didn't work.
