### ISSUE TITLE
Cannot bind to self in MultiBinding

### ISSUE THREAD

**Issue by appel1** [AvaloniaUI/Avalonia#13528]
## Describe the bug
Binding to $self or RelativeSource Self in a MultiBinding causes compilation error.

## To Reproduce
Silly contrived example:
```xml
<StackPanel>
  <TextBlock>
    <TextBlock.Text>
      <MultiBinding Converter="{x:Static BoolConverters.And}">
        <Binding Path="$self.IsVisible"/>
      </MultiBinding>
    </TextBlock.Text>
  </TextBlock>
</StackPanel>
```

`Avalonia error AVLN:0004: Unable to resolve property or method of name 'IsVisible' on type 'Avalonia.Data.MultiBinding'.`

But at runtime it looks like the correct items are bound to. 
```xml
  <StackPanel>
    <TextBlock>
      <TextBlock.Text>
        <MultiBinding StringFormat="{} $self = {0}, $parent = {1}">
          <Binding Path="$self"/>
          <Binding Path="$parent"/>
        </MultiBinding>
      </TextBlock.Text>
    </TextBlock>
  </StackPanel>
```
<img width="405" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/973314/9e8bc703-7b58-4e94-a4c2-552f14f90a64">

## Expected behavior
No compilation error.

## Environment

- OS: Windows
- Avalonia-Version: 11.0.5

## Workaround
Use ElementName instead.
```xml
<StackPanel>
  <TextBlock Name="BindingTarget">
    <TextBlock.Text>
      <MultiBinding Converter="{x:Static BoolConverters.And}">
        <Binding Path="IsVisible" ElementName="BindingTarget"/>
      </MultiBinding>
    </TextBlock.Text>
  </TextBlock>
</StackPanel>
```

**Comment by nixtar** [comment]
I also ran into this here https://github.com/AvaloniaUI/Avalonia/discussions/13664.
Thanks for posting a workaround. 👍.
