### ISSUE TITLE
Geometry rendering performance

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#1352]
I think I've brought this up before, but using stream geometry for simple shapes (rects, ellipses, lines) is quite slow, since instead of using known optimized methods of drawing, the graphics library has to do a tessellation for our custom streaming geometry, which is a *very* expensive CPU-bound process. I have a case when calling DrawLine in cycle instead of using a prepared geometry with Direct2D makes a ~400 times difference in terms of performance.

I'm a bit concerned that we are relying on geometry implementations being the actual `Path`-like objects provided by the rendering system. That makes it harder to optimize in the future, since we'll have to implement all of that `IGeometryImpl` logic for each simple shape and do it at least twice (for skia and direct2d).

**Comment by grokys** [comment]
Yes, we definitely need to do this. The current solution was just a temporary solution that never got done properly. I'm adding this to the beta2 milestone for now, but I might get chance to do it sooner.

**Comment by lindexi** [comment]
I think the inherent tree is too long.

**Comment by grokys** [comment]
@lindexi could you explain? I don't understand.

**Comment by grokys** [comment]
This is implemented for D2D in #1406, needs a skia implementation still.

**Comment by Gillibald** [comment]
This was recently implemented for both backends
