### ISSUE TITLE
SelectingItemsControl and its derivatives

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#13525]
## Describe the bug
A followinng is a list of issues affected  `SelectingItemsControl` presents in a6e936d74accdcf7ead6b776f374defb501e4434 and **Avalonia 11.0.5**

- [ ] Item selection should be idempotent from position on ItemsSource in Xaml. 
      - The issue can not be resolved before PR #13522 will be merge.
      - #13543
- [ ] NRE is throwed when `SelectedValue` is binding a non nullable property. 
      - #13284
      - See discussion #13248 [minimal project](https://github.com/AvaloniaUI/Avalonia/files/13281216/Sandox.zip)
- [ ] When property binding at `SelectedValue` has initial value, it is not respected 
[minimal project](https://github.com/AvaloniaUI/Avalonia/files/13281235/Sandbox.zip)

## Environment 

- OS: Any
- Avalonia-Version: a6e936d74accdcf7ead6b776f374defb501e4434  and <= **Avalonia 11.0.5**

**Comment by robloo** [comment]
Nice summary here!

For the second noted issue NRE thrown when `SelectedValue` is bound to non-nullable property. I believe this is a related to or a duplicate of:
 * https://github.com/AvaloniaUI/Avalonia/issues/13284

I see #13284 every time I bind to a ComboBox with a value type.

**Comment by workgroupengineering** [comment]
> Nice summary here!
> 
> For the second noted issue NRE thrown when `SelectedValue` is bound to non-nullable property. I believe this is a related to or a duplicate of:
> 
>     * [SelectedValue on ComboBox throws Xamlll exception in debug mode #13284](https://github.com/AvaloniaUI/Avalonia/issues/13284)
> 
> 
> I see #13284 every time I bind to a ComboBox with a value type.

Thanks, I missed that.
This issue is a summary of issues affecting `SelectingItemsControl`. Each problem will be resolved separately.

**Comment by workgroupengineering** [comment]
fixes from #13800
