### ISSUE TITLE
DataGridTextColumn should support UpdateSourceTrigger=PropertyChanged behavior

### ISSUE THREAD

**Issue by AArnott** [AvaloniaUI/Avalonia#13533]
Per [the conversation on StackOverflow](https://stackoverflow.com/questions/75147401/what-is-the-avalonia-data-binding-equivalent-to-updatesourcetrigger-propertycha/75380811?noredirect=1#comment136490887_75380811), apparently Avalonia's default (and indeed only) update trigger is `PropertyChanged`, as opposed to the WPF default of `LostFocus` or whatever it is.

But that isn't true for text boxes created by `DataGridTextColumn`, which only updates the data binding source on focus loss. In fact, depending on how the UI is dismissed or replaced, the source update may _never_ happen, which is how I discovered this issue to begin with. If the user is typing in such a textbox, and then clicks a button that swaps the UI out for something else, the content of the textbox is lost instead of applied to the underlying view model.

I workaround this by using a `DataGridTemplateColumn` and creating my own `TextBox` control. But it would be great to be able to use the stock one.

Avalonia version 11.0.2

**Comment by timunie** [comment]
imo this depends on #3754
