### ISSUE TITLE
TextBox.Paste() doesn't respect MaxLines nor AcceptsReturn

### ISSUE THREAD

**Issue by WarWithinMe** [AvaloniaUI/Avalonia#13534]
## Describe the bug
When `MaxLines` sets to 1 and `AcceptsReturn` sets to False, a TextBox can still paste text which contains newline characters.

## To Reproduce
1. Create a TextBox control, set `MaxLines` to 1 and `AcceptsReturn` to False.
2. Copy some multiline text.
3. Paste into the TextBox control.

## Expected behavior
All newline characters should be removed right before pasting.

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.4

## Additional context
None.

**Comment by sccombp** [comment]
This might be better served by using a [Behaviour ](https://github.com/AvaloniaUI/Avalonia.Xaml.Behaviors) to format the text being pasted how you want. Not everyone might want it to handle the newline the way you do (some people might only want to accept the first line and discard the rest, or raise an error if it detects multiple lines being pasted) so having it in a behaviour gives you that flexibility.

Here's a quick and dirty example behaviour 
```csharp
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Input.Platform;
using Avalonia.Interactivity;
using Avalonia.Xaml.Interactivity;
using System;

namespace TextBoxMaxLinesPasteBehaviour .Behaviours
{
    public class TextBoxMaxLinesPasteBehaviour : Behavior<TextBox>
    {
        static TextBoxMaxLinesPasteBehaviour()
        {
        }

        protected override void OnAttached()
        {
            if (AssociatedObject is not null)
            {
                AssociatedObject.PastingFromClipboard += IsPastingFromClipboard;
            }

            base.OnAttached();
        }

        private async void IsPastingFromClipboard(object? sender, RoutedEventArgs e)
        {
            IClipboard clipboard = (App.Current!.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime)!.MainWindow!.Clipboard!;
            var t = await clipboard.GetTextAsync() ?? string.Empty;

            if (AssociatedObject is not null && AssociatedObject.MaxLines == 1 && !AssociatedObject.AcceptsReturn)
            {
                AssociatedObject.Text = t.Replace(Environment.NewLine, " ");
                e.Handled = true;
                return;
            }

            e.Handled = false;
        }

        protected override void OnDetaching()
        {
            if (AssociatedObject is not null)
            {
                AssociatedObject.PastingFromClipboard -= IsPastingFromClipboard;
            }

            base.OnDetaching();
        }

    }
}
```

and then you attach it to the text box like so
```csharp
    <TextBox MaxLines="1" AcceptsReturn="False">
      <i:Interaction.Behaviors>
        <bh:TextBoxMaxLinesPasteBehaviour/>
      </i:Interaction.Behaviors>
    </TextBox>
```

and here's what a basic window looks like
```csharp
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:bh="using:TextBoxMaxLinesPasteBehaviour.Behaviours"
        xmlns:i="clr-namespace:Avalonia.Xaml.Interactivity;assembly=Avalonia.Xaml.Interactivity"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="TextBoxMaxLinesPasteBehaviour .MainWindow"
        Title="TextBoxMaxLinesPasteBehaviour ">

  <DockPanel>
    <TextBox MaxLines="1" AcceptsReturn="False">
      <i:Interaction.Behaviors>
        <bh:TextBoxMaxLinesPasteBehaviour/>
      </i:Interaction.Behaviors>
    </TextBox>
  </DockPanel>
</Window>
```

**Comment by Gillibald** [comment]
`MaxLines` indicates the number of lines that are visible at once

**Comment by sccombp** [comment]
> `MaxLines` indicates the number of lines that are visible at once

The metadata for TextBox MaxLines is a little misleading in this case (Avalonia 11.0.5)
![image](https://github.com/AvaloniaUI/Avalonia/assets/124018297/deaeaa79-c2ed-472d-9a79-1ad283482e0a)

**Comment by timunie** [comment]
@sccombp if you know of a better metadata here, a PR would be welcome.

**Comment by Gillibald** [comment]
We follow this definition: https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.textbox.maxlines?view=windowsdesktop-7.0

**Comment by robloo** [comment]
Note for this whole discussion we should simply follow WPF behavior and not try to re-invent anything.

**Comment by zii-dmg** [comment]
Duplicate of #5438. And it's not fixed - AcceptsReturn=false allows multiline paste.

**Comment by WarWithinMe** [comment]
> Duplicate of #5438. And it's not fixed - AcceptsReturn=false allows multiline paste.

Closing this issue due to being duplicate of #5438
