### ISSUE TITLE
TextBox content truncated when text width exceed control width

### ISSUE THREAD

**Issue by vkotov** [AvaloniaUI/Avalonia#1354]
Steps to reproduce:
1. Open **Avalonia Control Gallery**
2. Select **TextBox** page.
3. Type long text that exceed control width to **singleline TextBox**.
4. Text is truncated.

**Comment by kpietraszko** [comment]
I have the same issue, can someone reproduce this?

**Comment by grokys** [comment]
Yes, I can reproduce, this is a serious bug - needs to be fixed before beta1. I will try to fix it tonight.
