### ISSUE TITLE
TexBox with Touch Panel

### ISSUE THREAD

**Issue by Mr4g** [AvaloniaUI/Avalonia#13551]
## Describe the bug
When I use the app on the touch screen in windows in tablet mode. When I press on the texbox, the on-screen keyboard does not open. I asked for help on telegarama and we tried version 11.1.999 unfortunately also there nothing happens when I press on TexBox the onscreen keyboard does not open.

## To Reproduce

1. add textbox to source
2. set the tablet mode on the addty screen 
3. press your finger on the textbox 
4. and the keyboard does not open 

## Expected behavior
An on-screen keyboard from windows in tablet mode should open up

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/133530721/12c2604c-5d02-4576-8203-13e3775ebcd4)

## Environment 

- OS: Windows 10
- Avalonia-Version: we tried on 11.0.5, 11.0.999, 11.1.999

**Comment by workgroupengineering** [comment]
Duplicate #10136

**Comment by timunie** [comment]
yeah, closing this as duplicate. 
@Mr4g sorry, my fault. Didn't see this issue back then.
