### ISSUE TITLE
MainWindow.xaml Project Placement

### ISSUE THREAD

**Issue by jamiewest** [AvaloniaUI/Avalonia#1356]
Currently when moving the MainWindow.xaml file to another location in a project (i.e. /Views/) you have to update the namespace within the MainWindow class to match its relative path (i.e. namespace AvaloniaApp.Views). This may cause issues for people new to Avalonia or those who wish to have more control over where they put resources. 

Proposals:
1. Wpf has a `StartupUri` property in the Application class that defines where to look for MainWindow.xaml, this could override the namespace matching the relative path requirement.

Example
```xml
<Application xmlns="https://github.com/avaloniaui" StartupUri="Views/MainWindow.xaml">
  <Application.Styles>
    <StyleInclude Source="resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"/>
    <StyleInclude Source="resm:Avalonia.Themes.Default.Accents.BaseLight.xaml?assembly=Avalonia.Themes.Default"/>
  </Application.Styles>
</Application>
```

2. Another idea is to have the `XamlLoader` scan all of the assemblies for matching resources by name and attempt to load them. This would be a lot more developer friendly in that we could move files around the project and organize namespaces later or never, it would just work. However, this could be problematic if there are multiple matching by name results and there would need to be a way to fail out.

**Comment by jkoritzinsky** [comment]
In terms of item 2 above, I think we really need to consider changes to our resource setup as mentioned in #1313.

**Comment by grokys** [comment]
Should be fixed by https://github.com/AvaloniaUI/Avalonia/pull/2104.
