### ISSUE TITLE
In touch screen mode, Unable to copy text

### ISSUE THREAD

**Issue by qfmee** [AvaloniaUI/Avalonia#13562]
In touch screen mode, when selecting text and long pressing to pop up the "Copy Paste" option, the selection will be lost, resulting in the inability to copy text in touch mode

**Comment by timunie** [comment]
@qfmee please fill the issue template. We need to know your environment and steps to reproduce. If possible, please test again using latest nightly.

**Comment by maxkatz6** [comment]
Please try the latest master builds. This issue should have been solved. Also, if this problem is still present, recreate issue with full template, as device, build and OS information is really important here

**Comment by qfmee** [comment]
> Please try the latest master builds. This issue should have been solved. Also, if this problem is still present, recreate issue with full template, as device, build and OS information is really important here

Avalonia: 11.0.5  
Operation mode: Multi touch screen
Windows 11 and Ubuntu  also have this bug

**Comment by timunie** [comment]
@qfmee 11.0.5 is not nightly / master build. Check: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed
