### ISSUE TITLE
Missing Intefaces in GlInterface

### ISSUE THREAD

**Issue by viniciusmiguel** [AvaloniaUI/Avalonia#13575]
Hello,

I am porting an application to avalonia based in OpenGL and I am missing many functions like listed bellow:

- glUniform3f
- glUniform1i
- glVertexAttrib4f
- glDisableVertexAttribArray

I would like to understand if there is a reason they are not being exposed and if I can submit a PR to include those.

Cheers,
Vinicius

**Comment by jp2masa** [comment]
https://github.com/AvaloniaUI/Avalonia/discussions/10646#discussioncomment-5290679

**Comment by maxkatz6** [comment]
Yes, it's not planned to be added.
