### ISSUE TITLE
Folder selection has padding and popup in Ubuntu 23.04

### ISSUE THREAD

**Issue by drweb86** [AvaloniaUI/Avalonia#13576]
## Describe the bug

Ubuntu select folder dialog shows black borders near window selection.

![image](https://github.com/AvaloniaUI/Avalonia/assets/4712173/e8cce1e8-c050-4f75-bbe8-2923ee240b9c)

Title of folder selection window is shown as popup

![image](https://github.com/AvaloniaUI/Avalonia/assets/4712173/8c615dd7-ec85-45e4-9bc4-57460de8a6c9)

## To Reproduce

1. Create empty app with select folder button pointed to HOME directory in Ubuntu.
2. Click on button

## Expected behavior
No popup with title folder is ready.
No black padding around the window.

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/4712173/e8cce1e8-c050-4f75-bbe8-2923ee240b9c)

![image](https://github.com/AvaloniaUI/Avalonia/assets/4712173/8c615dd7-ec85-45e4-9bc4-57460de8a6c9)

## Environment 

- OS: Ubuntu 23.04
- Avalonia-Version: latest

**Comment by maxkatz6** [comment]
It's not an Avalonia issue.
If you have problems with Ubuntu file picker implementation of FreeDesktop protocol (which is Avalonia uses to open the dialog), please open an issue in Ubuntu tracker.

**Comment by drweb86** [comment]
Can you please point to their github repository, I'll create bug there.

**Comment by timunie** [comment]
maybe here? https://gitlab.freedesktop.org/explore/groups

**Comment by drweb86** [comment]
Thanks. I've created issue there
https://gitlab.freedesktop.org/freedesktop-sdk/test_daniel/freedesktop-sdk/-/issues/31
