### ISSUE TITLE
Allow users to change menu show delay

### ISSUE THREAD

**Issue by WillisXue** [AvaloniaUI/Avalonia#13587]
I'm looking for a way to change the menu show delay.

https://github.com/AvaloniaUI/Avalonia/pull/6392
I saw that a previous PR had changed DefaultMenuInteractionHandler.MenuShowDelay to public.

https://github.com/AvaloniaUI/Avalonia/pull/6438
But then another PR changed it back.

Or is there any other way to change the menu show delay?

**Comment by timunie** [comment]
@WillisXue why do we need a show delay for a Menu? Most likely the user requests the Menu and it should be there without a delay imo. For a ToolTip it is a different story. 

Do you have a concrete use-case for us to evaluate?

**Comment by WillisXue** [comment]
@timunie You are right, but now the menu is not displayed immediately. DefaultMenuInteractionHandler.MenuShowDelay has a delay of 400 milliseconds by default, which does not feel so smooth. I want to change it to 20 milliseconds.

**Comment by WillisXue** [comment]
I found a solution

```C#
public class MenuFlyoutEx:MenuFlyout
{
    protected override Control CreatePresenter()
    {
        return new MenuFlyoutPresenter(new DefaultMenuInteractionHandler(true,null, (action,timeSpan) =>
        {
            DispatcherTimer.RunOnce(action, TimeSpan.FromMilliseconds(20));
        }))
        {
            ItemsSource = Items,
            [!ItemsControl.ItemTemplateProperty] = this[!ItemTemplateProperty],
            [!ItemsControl.ItemContainerThemeProperty] = this[!ItemContainerThemeProperty],
        };
    }
}
```

**Comment by timunie** [comment]
@WillisXue glad to hear you found a work around. But in the same time I have to say that I understand your original issue now better. Let's keep this ticket open until the team decides how to proceed with this. If we get the okay to do, would you be willing to file the needed PR?

/cc @avaloniaui-team any thoughts?

**Comment by WillisXue** [comment]
If possible, I can submit a PR. I just want to change MenuShowDelay to public as before.
