### ISSUE TITLE
Aynchronous reactive commands on Avalonia.iOS never complete

### ISSUE THREAD

**Issue by kyurkchyan** [AvaloniaUI/Avalonia#13594]
## Describe the bug
I have a straightforward scenario - a reactive command in the view model that invokes an awaitable async task. For the demo purposes, it's just `Task.Delay(2000)`. The problem is that on iOS, when the command execution starts, it never completes. Please take a look at the demo project I've attached. 

The command works as expected when launching the desktop version of the sample. In the demo project, I also have a Maui.iOS app that re-uses the same view model with the same set of bindings, and the reactive command works as expected there.

## To Reproduce

1. Download the [sample project](https://github.com/kyurkchyan/AvaloniaReactiveUIAsyncCommand/tree/main)
2. Launch the `AvaloniaReactiveUIAsyncCommand.iOS` on iOS Simulator
3. Press the "Load" button
4. Observe that the `Load command is busy` stays to value of "true" and the "Load" button is never reactivated.

## Expected behavior
After the load command completes its execution, the load command should be reactivated and its `IsExecuting` property should be set back to `true`

## Environment 

- OS: Mac
- Avalonia-Version: 11.1.999-cibuild0041899-beta

**Comment by jhimes144** [comment]
The above comment is a low quality ChatGPT generated response and it should be removed and discouraged.
