### ISSUE TITLE
Android cross-platform fullscreen doesn't work

### ISSUE THREAD

**Issue by andyld97** [AvaloniaUI/Avalonia#13598]
## Describe the bug
I created an app which is always open (KeepScreenOn). The idea is to deploy it to a tablet, so you can always see the information provided. The app itself works really well so far, but no matter what I do, I am not able to get it in fullscreen. Neither on the tablet (Android 7) nor on my phone (Pixel 6a, Android 14).

Previously I created a Xamarin.Android app with these settings:

```xml
<style name="AppThemeLaunch" parent="Theme.AppCompat.Light.DarkActionBar">
    <item name="windowActionBar">false</item>
    <item name="windowNoTitle">true</item>
    <item name="android:windowFullscreen">true</item>
    ...
</style>
```
There I was able to hide at least the title bar. But trying the same thing (on the same devices) with Avalonia doesn't work:

`styles.xml`:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<resources>

  <style name="MyTheme">
  </style>

  <style name="MyTheme.NoActionBar" parent="@style/Theme.AppCompat.DayNight.NoActionBar">
    <item name="android:windowActionBar">false</item>
    <item name="android:windowNoTitle">true</item>
    <item name="android:windowFullscreen">true</item>
  </style>
</resources>
```
`MainActivity.cs`:
```cs
[Activity(
    Label = "FullscreenTest.Android",
    Theme = "@style/MyTheme.NoActionBar",
    Icon = "@drawable/icon",
    MainLauncher = true,
    ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize | ConfigChanges.UiMode)]
public class MainActivity : AvaloniaMainActivity<App>
{
    protected override AppBuilder CustomizeAppBuilder(AppBuilder builder)
    {
        return base.CustomizeAppBuilder(builder)
            .WithInterFont();
    }

    protected override void OnCreate(Bundle savedInstanceState)
    {
        base.OnCreate(savedInstanceState);
        Window.SetFlags(WindowManagerFlags.Fullscreen, WindowManagerFlags.Fullscreen);
    }
}
```

## To Reproduce
Deploy repo to an Android device:
[FullscreenTest.zip](https://github.com/AvaloniaUI/Avalonia/files/13342583/FullscreenTest.zip)

## Expected behavior
- Android Fullscreen (hiding the title bar at least)

## Screenshots
![grafik](https://github.com/AvaloniaUI/Avalonia/assets/10423894/34f4cb59-1d76-4ead-9693-1c9d414c199d)

## Environment 

- OS: Android 7 & 10 Tablet, Android 14 Phone
- Avalonia-Version: 11.0.5

## Additional context
I already saw the discussion here: https://github.com/AvaloniaUI/Avalonia/discussions/13505. But there is no working soloution for me.
Am I missing something or am I doing something wrong? It would be nice if this would work, because I think this is just basic Android functionality.

**Comment by maxkatz6** [comment]
> because I think this is just basic Android functionality.

Have you used InsetsManager? It was also mentioned in the discussion.

cc @emmauss

**Comment by emmauss** [comment]
@andyld97  It's advisable to leave the default android styles, and activity classes as is from the template, unless you want to register services that need access to the activity. Use the insets manager to enable fullscreen. I've modified your sample.
[FullscreenTest.zip](https://github.com/AvaloniaUI/Avalonia/files/13346324/FullscreenTest.zip)

**Comment by andyld97** [comment]
Thank you guys for your help and clarification! It works perfectly fine! I am so sorry that I overlooked it in the discussion ...
