### ISSUE TITLE
SEHException in defferedrenderer

### ISSUE THREAD

**Issue by MonkAlex** [AvaloniaUI/Avalonia#1359]
Use simple listbox with images, then scroll it. 15 items in list (2-3 lines), only 2 has images.
Images stored as byte[], then converted with [converter](https://github.com/MonkAlex/MangaReader/blob/AvaloniaUI/MangaReader.Avalonia/BitmapConverter.cs)

Then, app crashed: System.Runtime.InteropServices.SEHException (0x80004005)
CallStack:
> SharpDX.Direct2D1.dll!SharpDX.Direct2D1.RenderTarget.CreateBitmapFromWicBitmap(SharpDX.WIC.BitmapSource wicBitmapSource, SharpDX.Direct2D1.BitmapProperties? bitmapProperties, out SharpDX.Direct2D1.Bitmap bitmap)	Unknown	No symbols loaded.
> Avalonia.Direct2D1.dll!Avalonia.Direct2D1.Media.WicBitmapImpl.GetDirect2DBitmap(SharpDX.Direct2D1.RenderTarget renderTarget)	Unknown	No symbols loaded.
> Avalonia.Direct2D1.dll!Avalonia.Direct2D1.Media.DrawingContextImpl.DrawImage(Avalonia.Platform.IBitmapImpl source, double opacity, Avalonia.Rect sourceRect, Avalonia.Rect destRect)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.SceneGraph.ImageNode.Render(Avalonia.Platform.IDrawingContextImpl context)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Platform.IDrawingContextImpl context, Avalonia.Rendering.SceneGraph.VisualNode node, Avalonia.VisualTree.IVisual layer, Avalonia.Rect clipBounds)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.RenderToLayers(Avalonia.Rendering.SceneGraph.Scene scene)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Rendering.SceneGraph.Scene scene)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.OnRenderLoopTick(object sender, System.EventArgs e)	Unknown	No symbols loaded.
> Avalonia.Visuals.dll!Avalonia.Rendering.DefaultRenderLoop.InternalTick()	Unknown	No symbols loaded.
> Avalonia.Win32.dll!Avalonia.Win32.RenderLoop.StartCore.AnonymousMethod__0(uint id, uint uMsg, System.UIntPtr user, System.UIntPtr dw1, System.UIntPtr dw2)	Unknown	No symbols loaded.
>

**Comment by grokys** [comment]
@MonkAlex are you still seeing this problem? Any chance of a repro?

**Comment by MonkAlex** [comment]
Cannot reproduce on master(0.7.1-cibuild0001581-beta) now.
