### ISSUE TITLE
System.InvalidOperationException: Neither DBus nor GTK are available on the system

### ISSUE THREAD

**Issue by Anonymous941** [AvaloniaUI/Avalonia#13609]
When trying to open a file dialog, I get the error `System.InvalidOperationException: Neither DBus nor GTK are available on the system` on Ubuntu.  I've tried to install several packages mentioned in #11554, but none of them fix the issue and I am not using WSL.

**Comment by timunie** [comment]
@Anonymous941 we have the issue template for a reason. Please let us know the Avalonia version and the specific OS you use. Best would also be some sample code to reproduce.
