### ISSUE TITLE
NullReferenceException in Avalonia.Rendering.Composition.Compositor

### ISSUE THREAD

**Issue by arnirichard** [AvaloniaUI/Avalonia#13608]
## Describe the bug
I am getting occasional NullReferenceException and crash

`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Avalonia.Base
  StackTrace:
   at Avalonia.Rendering.Composition.Compositor.RequestCompositionUpdate(Action action) in Avalonia.Rendering.Composition\Compositor.cs:line 238
`

`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Avalonia.Base
  StackTrace:
   at Avalonia.Rendering.Composition.Compositor.RequestCommitAsync() in Avalonia.Rendering.Composition\Compositor.cs:line 105`

## To Reproduce
I do not have a minimal reproducible sample yet. I am generating `WriteableBitmap` in async function.

Any suggestions are welcome on how to investigate.

It does seem like a concurrency problem `_nextCommit` is assigned to null by another thread.

## Environment 

- OS: Windows 11 Business (build 22621.2506)
- Avalonia-Version 11.0.5
- dotnet 7.0.403

**Comment by timunie** [comment]
Some events need to be called form UI-thread. Try to use `Dispatcher.UiThread.Post()` to inform the UI about changed data.

**Comment by maxkatz6** [comment]
> I am generating WriteableBitmap in async function.

Generating or updating? It might not be a good idea to update a writeable bitmap from another thread, not sure if it's supported.

**Comment by arnirichard** [comment]
I am generating in a worker thread, and the UI thread awaits the `WriteableBitmap` and assigns it to `Image.Source` unless if a new  `WriteableBitmap` has been requested (user is zooming and moving with the mouse).

However, I am not able to reproduce the problem right now, now sure why. I will report when I find out more.

**Comment by Enigmatrix** [comment]
I've gotten this twice, but I'm not sure what's causing it either, and it's not reproducible. When the exception is caught Visual Studio gives me so little useful information that I don't even know how to trace it ...

**Comment by arnirichard** [comment]
Still getting this, I create `WriteableBitmap` in a worker thread, which might be causing, and I assign it to Image.Source in UI thread. This happens rarely.

**Comment by Enigmatrix** [comment]
Similarly, I have a task run using `Task.Run` then bound to a value afterwards

**Comment by timunie** [comment]
@Enigmatrix make sure to use Dispatcher.UiThread to set value.

**Comment by arnirichard** [comment]
I am finally able to reproduce this in the Avalonia project

The problem is in `Compositor.RequestCompositionBatchCommitAsync()`

`_nextCommit` is assigned to null before returning the method.

![image](https://github.com/user-attachments/assets/0f787f83-7c25-420e-b7ec-3ab9414e530e)

**Comment by arnirichard** [comment]
Comment added to 

https://github.com/AvaloniaUI/Avalonia/issues/15226
