### ISSUE TITLE
Feature Suggestion: Rider integration

### ISSUE THREAD

**Issue by RUSshy** [AvaloniaUI/Avalonia#1361]
Hi,
Is it possible to add integration with the IDE rider ?

Something like a ui preview

**Comment by VladimirAkopyan** [comment]
I feel Rider would be a better integration product than VS cause it's cross-platform.

**Comment by Gaulomatic** [comment]
Jesus, VS became to frickin' slow over the last few iterations, I am not using it anymore - simply to avoid a heart disease. Rider has become my main IDE, especially because I can use it on my Mac and on Windows alike. Plus its more stable, faster and more productive.

**Comment by ingvar1995** [comment]
Technically that's possible (Rider is ready for plugin development) but it will be long process. Even writing [simple plugin](https://github.com/ingvar1995/rider-avalonia-plugin) with just adding avalonia project types to Rider isn't easy due to lack of documentation.

**Comment by MostHated** [comment]
+10 on this, I hate having to use VS ever since switching to Rider and the whole JetBrains family last year.

**Comment by rstm-sf** [comment]
It's available now

**Comment by maxkatz6** [comment]
Rider now integrated with Avalonia
https://www.jetbrains.com/rider/whatsnew/#avalonia-support

And previewer is available from this repo
https://github.com/ForNeVeR/AvaloniaRider
