### ISSUE TITLE
Android: ListBox in Viewbox throws System.InvalidOperationException: 'Transform is not invertible.'

### ISSUE THREAD

**Issue by Hodster** [AvaloniaUI/Avalonia#13616]
I am having problems getting viewbox to work when the contents has a ListBox in it. It works perfectly as a desktop app but not on Android.  I have created a very simple screen that demonstrates the problem:

<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:local="clr-namespace:PES.Assets"
             xmlns:vm="clr-namespace:PES.ViewModels"
			 xmlns:views="clr-namespace:PES.Views"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="480"
             mc:MinWidth="800" mc:MinHeight="400"
			 x:Class="PES.Views.MainView"
             x:DataType="vm:MainViewModel"
			 FontFamily="DynamicResource applicationFont">

	<Design.DataContext>
		
		<vm:MainViewModel />
	</Design.DataContext>

	<Viewbox Stretch="Uniform">
		<ListBox >
			<ListBoxItem>Hello 1</ListBoxItem>
			<ListBoxItem>Hello 2 </ListBoxItem>
			<ListBoxItem>Hello 3</ListBoxItem>
			<ListBoxItem>Hello 4</ListBoxItem>
		</ListBox>
	</Viewbox>
</UserControl>
	
When running on Android the splash screen appears followed by a System.InvalidOperationException: 'Transform is not invertible.' exception is thrown. I have tried setting many properties on both Viewbox and ListBox fixing sizes etc. but to no avail. 

I use Visual Studio 2022 on a PC with the latest Avalonia support from NuGet. The Android target version is 33.

What I am trying to achieve is a resize of all controls when the parent window on desktop resizes or when Android screen is rotated. Viewbox work really well for screens that don't contain a ListBox. 

Many thanks for any help or suggestions to try.

**Comment by timunie** [comment]
please try latest nightly also

**Comment by MrJul** [comment]
> please try latest nightly also

Yes please, as this is normally already fixed by #13188.

**Comment by Hodster** [comment]
Thank you both. Issue has indeed been fixed in more recent build.
