### ISSUE TITLE
RTL text rendering issue

### ISSUE THREAD

**Issue by techseat** [AvaloniaUI/Avalonia#13623]
## Describe the bug
It seems Text rendered by Element witch its flow direction is RightToLeft is rendered in invalid position at outside of the window. Resizing the window comes that text from right side to the window. It seems that invalid position is related to the element's size.

## To Reproduce

1. Create a new Avalonia desktop app project
2. Open `MainWindow.axaml`
3. Add a `TextBlock` element as root and set `FlowDirection="RightToLeft" Text="<Some RTL Text here>" Background="Red"`
4. Build and Run the app to see that text is not visible!
5. Resizing window will cause to that text to come in from right side. And It seems that text is rendering in invalid position.

## Expected behavior
That RTL text must be rendered in the window's view port correctly, sticked to the right side.

## Screenshots
![explorer_mMy4IrlgRj](https://github.com/AvaloniaUI/Avalonia/assets/53011829/551d146b-e589-4f5a-8369-3bc974f923af)

`MainWindow.axaml` :
  ```c#
  <Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1">
	<StackPanel>
		<TextBlock Text="Sample Text in true position" FlowDirection="LeftToRight" Background="Green"/>
		<TextBlock Text="Sample Text in invalid position" FlowDirection="RightToLeft" Background="Red"/>
	</StackPanel>
</Window>
  ```

## Environment:
- OS: Windows
- Avalonia-Version: 11.1.999-cibuild0041918-beta

**Comment by robloo** [comment]
cc @danielmayost

**Comment by maxkatz6** [comment]
Just in case @Gillibald too depending on how RTL should be implemented on the text controls.

**Comment by Gillibald** [comment]
This is a bug with the text metrics
