### ISSUE TITLE
Graphic corruption occuring on Nvidia GPUs (Checkerboard effect - flashes) with heavy GUI draws

### ISSUE THREAD

**Issue by Tetedeiench** [AvaloniaUI/Avalonia#13620]
## Describe the bug
A random checkerboard effect appears on screen for a frame when a Nvidia GPU is used.
The window is drawn for a frame semi-transparent with a checkerboard effect kicking in. 
It results in annoying flashes.
Debug mode makes this more prevalent.

This seems to be due to Direct Composition, as it also occurs with Chrome as described here : 
https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/529146/possible-cause-of-the-chromium-checkerboard-bug/
https://forums.guru3d.com/threads/solution-fix-checkerboard-like-patterns-randomly-appearing-in-chromium-based-applications.449341/

Direct composition seems to be hard-coded in Avalonia and we have no control about it.

## To Reproduce
(this seems to only occur on Nvidia GPUs)

1. Run an Avalonia app with heavy refreshes on screen ( real time graphs helps )
2. wait for the checkerboard effect to kick in

Debug mode makes this prevalent.

## Expected behavior
The window is displayed correctly

## Screenshots
bad resolution, but the best I could do to capture the exact frame it occurs
![image](https://github.com/AvaloniaUI/Avalonia/assets/23140774/69badd6e-838f-454e-a922-21e6911d5fcc)

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.4 (in prod), also occurs in 11.0.5 ( in debug mode).

## Additional context
Not sure how to tackle this : 
* Giving us control over Direct composition would be great, but a workaround at best ?
* I'm not sure how to find the root cause of this.

I'm up for ideas here !

**Comment by MrJul** [comment]
Probably similar to #10306? Hard to tell from the screenshot :)

**Comment by Tetedeiench** [comment]
It is. Couldn't find it through searching the issue. Closing this then and switching to #10306
