### ISSUE TITLE
The graphs close a program with the error "System.Exception" in Avalonia.Base.dll

### ISSUE THREAD

**Issue by MrOldOwl** [AvaloniaUI/Avalonia#13632]
**Error Description**
I upload 3600 points from the database to the graphs. After that, I grab the graphs with the mouse cursor and start moving the graph sharply to the left and right. If you continue doing this for about 1 minute, the application closes with the error "System.Exception" in Avalonia.Base.dll (SigtermEvent).

I also wrote to the graph developers.
https://github.com/beto-rodriguez/LiveCharts2/issues/1362

**I am using:**
- LiveCharts2 v. 2.0.0-rc2
- Avalonia v. 11.0.5
- .Net 7

The code is written according to the example from the site:
https://livecharts.dev/docs/avalonia/2.0.0-rc2/samples.general.scrollable
General -> Scrollable

**Computer Characteristics**
- Windows 10 Pro 22H2 19045.2006
- Intel i7-11700
- 32G RAM
- NVIDIA GeForce RTX 3060
- Samsung SSD 980 1TB

**Comment by timunie** [comment]
@MrOldOwl please link both issues. thx.

**Comment by MrOldOwl** [comment]
Hello. Today I wrapped the Main method in try-catch and saw that the error is not the one I described earlier. 
It is also already discussed at the link: https://github.com/beto-rodriguez/LiveCharts2/issues/1076
I apologize.
