### ISSUE TITLE
DataGrid: IDataGridCollectionViewFactory and IDataGridCollectionView need to be public

### ISSUE THREAD

**Issue by Some1Nebo** [AvaloniaUI/Avalonia#13650]
## Is your feature request related to a problem? Please describe.
Currently there is no way for the user collection to implement IDataGridCollectionViewFactory and to provide own implementation of IDataGridCollectionView. In fact, IDataGridCollectionViewFactory is not used at all.

It is needed to avoid the default implementation (DataGridCollectionView), which iterates over the whole collection and doesn't allow a user to implement data virtualization (to avoid keeping large amounts of data in memory).

## Describe the solution you'd like
Both IDataGridCollectionViewFactory and IDataGridCollectionView need to be public.

**Comment by Some1Nebo** [comment]
@timunie I would actually prefer to close this request in case no one else finds it useful. It turned out that TreeDataGrid doesn't have this problem, so I went with that approach.

**Comment by timunie** [comment]
I let @maxkatz6 decide.

**Comment by maxkatz6** [comment]
We can keep this issue open
