### ISSUE TITLE
TimePicker should respect `HorizontalAlignment` and `VerticalAlignment` properties set in XAML

### ISSUE THREAD

**Issue by SignalMQ** [AvaloniaUI/Avalonia#13658]
![image](https://github.com/AvaloniaUI/Avalonia/assets/77734001/a999f15c-91b3-43f7-bf9a-e1061e784db6)

**Details:**
_Avalonia Extension:_ 11.0.2 (used default by Visual Studio)
_OS:_ Windows 11 (23H2)
_IDE:_ Microsoft Visual Studio Community 2022 (64-bit) - Current (Version 17.8.0)

**Comment by timunie** [comment]
I currently don't see the issue. Your textbox has a margin of 15px all around so this is what I would expect.

**Comment by maxkatz6** [comment]
Everything on the screenshot looks correct.
Keep in mind, for buttons you might want to set HorzontalContentAlightnment as well.

**Comment by SignalMQ** [comment]
> I currently don't see the issue. Your textbox has a margin of 15px all around so this is what I would expect.

Hi, sorry for my mistake. What about of different problem, I changed from `Grid.RowDefinitions` column `0` from `30` to `50`.
I expected the TimePicker to increase vertically if I increased the grid size, but here's what I got:
![image](https://github.com/AvaloniaUI/Avalonia/assets/77734001/4799bfb7-b764-4ac8-9555-cd0fc9bf2227)

**Comment by timunie** [comment]
That seems to be a hard-coded value for TimePicker (Last two lines): https://github.com/AvaloniaUI/Avalonia/blob/1a798ff44cd2e976cfb828aaf3f8d8e790d811eb/src/Avalonia.Themes.Fluent/Controls/TimePicker.xaml#L86-L97

So I'm re-open this issue with an updated title. If anyone wants to update the style, a PR is welcome.
