### ISSUE TITLE
Custom font seems be used only on system where the font is installed

### ISSUE THREAD

**Issue by CodeDevAM** [AvaloniaUI/Avalonia#13669]
## Describe the bug
I set the font of my app like this:

RobotoMono-Light.ttf is put to the Asset Folder:
![grafik](https://github.com/AvaloniaUI/Avalonia/assets/125025268/042fe5c1-249e-49be-8f27-31e2f9a40b3e)

In App.axaml.cs:
```
AppResources["Font"] = new FontFamily(new Uri("avares://Assets/fonts/RobotoMono-Light.ttf"), "Roboto Mono");
```

In App.axaml:
```
<Style
    Selector="Window">
    <Setter
        Property="FontFamily"
        Value="{DynamicResource Font}" />
    <Setter
        Property="FontWeight"
        Value="Light" />
</Style>
```

It works fine on my PC. But it doesn't work on other machines wehre the font is not installed.
On other machines it falls back to default font without any warning or error.

## Environment

- OS: Windows 11
- Avalonia-Version: 11.0.5

**Comment by timunie** [comment]
Use AssetLoader to load the font from the assets please.

**Comment by Gillibald** [comment]
`new FontFamily("avares://Assets/fonts/RobotoMono-Light.ttf#Roboto")`

**Comment by CodeDevAM** [comment]
Thanks for the help!

However the documentation could be more clear about this topic. For my understanding it does not become clear what the part after the # actually mean. In my example: Why it has to be `Roboto` and not `Roboto Mono`?

And on the other hand does it make a difference when you project has multiple different libs. Then it is not clear to me how the URI has to look like.

**Comment by Gillibald** [comment]
Both should work. I just used `Roboto` so it matches 100%. If you have multiple variants of the font family you can be more precise.

**Comment by timunie** [comment]
@CodeDevAM if you think the docs can improve here, a PR to the docs is welcome :-)

**Comment by CodeDevAM** [comment]
I did not know how to specify the correct resource path. And I am thankful for the explanation.

However I still consider it as a bug when it works on my machine with a wrong uri without throwing an error. Additionally it does not work on other machines also without throwing an error and just falling back to some other font.
