### ISSUE TITLE
Clipped Text in TextBlock (Nightly Build)

### ISSUE THREAD

**Issue by cfnfy** [AvaloniaUI/Avalonia#13671]
## Describe the bug
TextBlocks are being clipped very slightly on the left bounds.

## To Reproduce

1. Add a TextBlock with text.

or

1. Open DevTools in Debug

## Screenshots

The following shows this issue within the DevTools window in a new project with Inter font (no custom styling overrides).

Nightly Build (Issue)
<img width="111" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/28407053/91e5c671-07c5-4b15-89a7-eccea3bc652f">

11.0.5 (No Issue)
<img width="104" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/28407053/760e4cc1-df05-42ae-b095-874d8461fab7">

The issue is more prominent in our app
<img width="38" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/28407053/e84b293f-10c8-43e0-91c7-79b44293f4f6">

## Environment

- OS: macOS - Arm64
- Avalonia-Version: 11.1.999-cibuild0042031-beta

N.B The last nightly build without this issue is 11.1.999-cibuild0041954-beta

**Comment by Gillibald** [comment]
I can't reproduce the issue here:

![Screenshot 2023-11-20 165033](https://github.com/AvaloniaUI/Avalonia/assets/5928797/6f36151f-0694-45ba-a6a3-e32097146525)

**Comment by cfnfy** [comment]
I'm on macOS rather than Windows. I did a quick test on Windows and the same project doesn't have the issue. 

I'm using 11.1.999-cibuild0042033-beta which is the latest available on the nighly feed. I'll test ...39 when it's available.

**Comment by cfnfy** [comment]
The below screen grabs are from DevTools in the same project using `11.1.999-cibuild0042033-beta`

**Windows**
<img width="337" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/28407053/c633df62-bb7b-492a-a32f-98cdb86967d2">

**maxOS**
<img width="270" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/28407053/07a23f5b-1ddb-4ad3-86b2-7d7cd1558b07">
