### ISSUE TITLE
TrayIcon doesn't work on some distros

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#13684]
TrayIcons has not been working on most linux distros since 11 preview 4 for some reason.  Upon investigation it seems that it bugged out after https://github.com/AvaloniaUI/Avalonia/commit/bdebcca9 (#9810) . I'm not sure if the introspection error described here (https://github.com/affederaffe/Tmds.DBus.SourceGenerator/issues/7) has anything to do with it since it kinda still works on Linux Mint Debian Edition 6 despite it.

cc @affederaffe

**Comment by jmacato** [comment]
Here on LMDE it works "fine" despite the introspection error:
![Screenshot from 2023-11-21 19-21-03](https://github.com/AvaloniaUI/Avalonia/assets/16554748/ac83b40f-61fe-4814-bc72-0cbc4ba5c7c0)
![Screenshot from 2023-11-21 19-33-42](https://github.com/AvaloniaUI/Avalonia/assets/16554748/4357ea53-0a1b-445b-987a-1390c3ac1ce5)

**Comment by jmacato** [comment]
While here on Deepin 20.9 it doesnt work at all

![image](https://github.com/AvaloniaUI/Avalonia/assets/16554748/9e0a24e6-ebdc-490c-9bca-7875f7ef025d)

**Comment by affederaffe** [comment]
Tested with Deepin (whatever version Arch ships, their versioning is all over the place), works with https://github.com/tmds/Tmds.DBus/pull/213 applied.

**Comment by jmacato** [comment]
Hi @affederaffe! 

So i've tried that patch by building the nupkg locally and using it on ControlCatalog, sadly it still didn't worked.

If you want to try the exact same Deepin distro, here's the link for the [iso](https://drive.google.com/file/d/1u219K1fWgNTsMZX2yg0h15jIlLQkBG36/view?usp=drive_link). But the introspection stuff seems to work. Just not sure why 11 preview 4 works while master doesnt

11-preview4 + Deepin 20.9:
![image](https://github.com/AvaloniaUI/Avalonia/assets/16554748/cefd6750-48e9-4cf2-a995-ab6e51fe0cf2)


Master + Deepin 20.9:
![image](https://github.com/AvaloniaUI/Avalonia/assets/16554748/d9d89a5c-92af-40fd-8083-30609b34452d)

**Comment by jmacato** [comment]
Here's some logs from dbus-monitor as well. 5 digit numbers are the controlcatalog PID's.

Log 1 is the one from master
[dbus-log1.14709.txt](https://github.com/AvaloniaUI/Avalonia/files/13457904/dbus-log1.14709.txt)

Log 2 is from preview4
[dbus-log2.14797.txt](https://github.com/AvaloniaUI/Avalonia/files/13457905/dbus-log2.14797.txt)

**Comment by jmacato** [comment]
@affederaffe after much debugging, it was simply a missing org.freedesktop.DBus.Peer Ping call. I think it needs to be implemented on base sourcegen.
