### ISSUE TITLE
Task Main() breaks Drag and Drop (and more?)

### ISSUE THREAD

**Issue by xecrets** [AvaloniaUI/Avalonia#13694]
## The bug
Using a Task-returning Main(), async or not , breaks Drag and Drop.

If Main() is written to return a Task, then when an attempt is made to drag
over an area where it should be possible to drop, the DragOver event is never raised.

## To Reproduce
Starting with the template app, change it to include a drag and drop area, and then
change `public static void Main(string[] args)` to `public static Task Main(string[] args)`,
and also add `return Task.CompletedTask;`.

Try to drag anything over the blue drop area, and you'll never get the event and the
cursor never changes to indicate that it can accept the drop.

## Expected behavior
I would expect nothing to change because Main happens to return a Task. I'm also
worried that more things are broken, as yet unknown.

## Environment

- OS: Windows 11
- Avalonia-Version: 11.0.5

## Sample
A sample project is included that demonstrates the issue:

[AvaloniaApplication2.zip](https://github.com/AvaloniaUI/Avalonia/files/13439911/AvaloniaApplication2.zip)

**Comment by MrJul** [comment]
The main thread must be STA, and `[STAThread]` is ignored on `async Main`.

Duplicate: https://github.com/AvaloniaUI/Avalonia/issues/12499
Underlying compiler issue: https://github.com/dotnet/roslyn/issues/22112

**Comment by xecrets** [comment]
Ok, that's annoying - on several levels ;-) I did search the issue list first, but I searched for "Drag" - and the existing issue was tagged with "DragDrop" - and thus I didn't find it. But more annoying is that it took most part of a day to figure this out - wouldn't it be nice to have the framework let us know that this isn't going to work? Something like:
```
            if (Thread.CurrentThread.GetApartmentState() != ApartmentState.STA)
            {
                throw new InvalidOperationException("The main thread must be STA, async Task Main() is not supported.");
            }
```

And it's of course very annoying that it doesn't work in the first place... Thanks for the response anyway. Another day wasted ;-) .

**Comment by xecrets** [comment]
A logged warning is of course better than nothing, but in my world if it's broke it's broke. Obviously conditional on running on Windows, but perhaps also conditional on using the Drag and Drop feature, perhaps when setting AllowDrop to true or some other good place. A framework should help a user to do right, and throwing an exception when something is wrong is the best way. Silent fails, even if logged, is never a good thing.

**Comment by damian-666** [comment]
.this is closed so ill check general tooling discussion later if people have recommendations about  . AI plugins models, tokens, etc.. that currently help and what to expect from them.  i juy tried a find bugs chatpt plug in that would have saved you time.


 
  but in this context ill just put a suggestion, in spite of all the half-backed but so promising AI plugins and tools, at least try the AI ( find bugs ) and it could have saved you hours with its guesses on developability.  it gave the clues right away.
  

as [MrJul](https://github.com/MrJul)  said 
   the .net team are putting in a warning or something, its a general problem with a big  discussion.     so the warning , style cop ex is general fix that wil get in a preview ..      see all this discussion..
  https://github.com/dotnet/csharplang/issues/97
   
 
   so never mind style cops, the AI sees  a problem right away.
   
   even when wrong ,it give you ideas..  it cant do your  coding chores yet) but a quick "**find bugs" its guessing via how logical and developable your code is, and what Its Expectations are .. some of which are not extant**,  as in 
  **StartWithClassicDesktopLifetimeAsync** they are "imagined "or as some say "hallucinated",  but it tells you something it expects to exist.
  
so i have this one.  
   https://marketplace.visualstudio.com/items?itemName=jefferson-pires.VisualChatGPTStudio
  set to chatgpt4 via model w prompt  "Apply the change requested by the user to the code, but don't rewrite the original code that was not changed"  
   
   highlight the code, 
   
 
    the the Ai can see a pattern problem already .     but don't follow the AI white rabbit too far,  is will take more time , i google **StartWithClassicDesktopLifetimeAsync** , never existed?, the fact that is not there tells you something about your expectations and its.  
    
    its hard to get the bots to code against APIs tha changed after it was trained over a year ago..v 10?   but you can feed is JSON from nugets XAML on apis or give it some of all of the new source, but... i would build the source and try a cheaper bot..    if someone knows which work with Avalonia ill check the discussion.
    
    its work the 30$ a morth for the keys, i don t use the copilots now, and  still looking  at 
 



>>>then 


first try..
 "STAThread] attribute is typically used for Windows Forms applications. If this is not a Windows Forms application, this attribute may not be necessary.Without more context, it's hard to say if these...
 
 



it get .. 
//The code provided is a part of a C# application that uses Avalonia UI framework. The Main method is marked as async but it doesn't await any asynchronous operations. This might not be a bug, but it's a bit misleading.Here is the corrected version:



//```csharp[STAThread]
//public static void Main(string[] args)
//{
// BuildAvaloniaApp()
// .StartWithClassicDesktopLifetime(args);
//}
//```
//If you want to keep the Main method asynchronous, you should use the async keyword and await the StartWithClassicDesktopLifetime method:
//```csharp[STAThread]
//public static async Task Main(string[] args)
//{
// await BuildAvaloniaApp()
// .**StartWithClassicDesktopLifetimeAsync**(args);
//}
//```
//Please note that the **StartWithClassicDesktopLifetimeAsync method is available starting from Avalonia0.10.0. I**f you're using an older version, you might need to upgrade.
