### ISSUE TITLE
UI Rendering Not Updating

### ISSUE THREAD

**Issue by cfnfy** [AvaloniaUI/Avalonia#13690]
## Describe the bug

At seemingly random times, TextBox inputs become 'less responsive'. While they still capture input, there are instances when an characters won't display until additional input is made, or the cursor is moved over the TextBox. 

While this issue is happening, the caret does not blink. 

I've been unable to pinpoint the cause here, as whilst it's happening quite often it I can't directly link it to any other action. I have however found that the caret blink DispatcherTimer does not fire events during this time, but will fire when the pointer moves over the control.

## To Reproduce

As I'm not sure of the cause here, I can't provide clear steps to re-produce. I will update if able to identify the cause.

## Expected behavior

Inputs to TextBox's should be immediately visible, and the caret should blink consistently to indicate the current position in the TextBox.

## Environment

- OS: macOS arm64
- Avalonia-Version: 11.1.999-cibuild0042190-beta

## Additional context
I have only tested on macOS and will try to test on Windows today.

**Comment by cfnfy** [comment]
I've noticed now that it's actually all the UI that goes unresponsive. TextBox's were just highlighting the issue due to the input delay and lack of blinking caret. When this issue is happening, the UI will only update when pointer is moving.

**Comment by timunie** [comment]
Please try to reproduce in a minimal sample and upload it here. Without any idea how to reproduce, what should we do? 

Do you have probably long running ooerations done on the UI thread?

**Comment by cfnfy** [comment]
I still haven't been able to completely narrow down the cause, so currently can't provide a minimal sample. However, I found a similar issue reported here. 

https://www.stackoverflow.com/questions/76875199/piechart-is-not-refreshed-in-avalonia-11-with-communitytoolkit-mvvm-8-it-worked

I'm was also using CommunityToolkit MVVM 8.0. After a few painful hours, I migrated our project to ReactiveUI and seemingly the issue has now gone. It's hard to say with complete certainty at this point as I need a bit more time to test, but the typical time from run to issue has long passed.

I'll report back when I have done more testing.

**Comment by maxkatz6** [comment]
You can double-check on which thread update is occurring. In case it wasn't a UI thread as it should be.
ReactiveUI has some hidden threading manipulations with its schedulers.

**Comment by timunie** [comment]
@cfnfy as we have no chance to reproduce and you seem to have found a solution that works for you, I'm closing this issue  for now. If you find steps to reproduce, please ping me and we will re-open it.

**Comment by cfnfy** [comment]
@timunie - No worries at all. I'm still experiencing the issue but it's intermittent and despite attempts to track it down I'm having no luck. If I figure out the cause I'll add drop you a message.

Adding more details in case someone else comes across this with a similar issue in the future. The UI is seemingly randomly 'freezing' to a point where even the debug window is not updating without moving the pointer over the window. Currently uncertain if only happening on Mac only as we primarily develop on Mac's. The issue is happening in debug, release and release ready builds.

The only way to fix this issue is to reset the application. We're not getting any errors logged when using    ```.LogToTrace(LogEventLevel.Error, LogArea.Visual);``` and we can't find any directly related cause. 

Whilst ReactiveUI has seemingly reduced the frequency of the issue, it hasn't fixed it.

**Comment by timunie** [comment]
Cound it be that https://github.com/AvaloniaUI/Avalonia/issues/14382?

**Comment by BAndysc** [comment]
> Cound it be that #14382?

During my tests, too deep visual trees were simply crashing the app completely. So I am not sure as the symptoms here look different.

**Comment by cfnfy** [comment]
Interesting that you point that out. I've just done some tests and in the more complex areas of our application we have depths and counts of the following.

<img width="284" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/28407053/075f1c60-3f82-46b7-940d-aae1e007310b">

We're not experiencing any crashes at this level using recent nightly builds. This might help narrow down the cause.

**Comment by timunie** [comment]
I believe you are rendering too many items at once without virtualization. If that is the case, consider to add virtualization or to render on your own. But again, a sample may be helpful

**Comment by cfnfy** [comment]
I'm hopefully able to close this one off. 

After finding the issue [Avalonia causes a deadlock in mono's runtime during Garbagge Collection in macOS](https://github.com/AvaloniaUI/Avalonia/issues/9444#top), it looks to be that our issue was related to our use of MonoMac to handle windows being shown in the MacOS Dock #https://github.com/AvaloniaUI/Avalonia/issues/7487.

It's hard to be 100% sure of the fix, but so far so good.
