### ISSUE TITLE
Cannot mix HTML and Avalonia View in Avalonia 11.5

### ISSUE THREAD

**Issue by npolyak** [AvaloniaUI/Avalonia#13713]
I have trouble making very simple Avalonia view appear under some HTML. Here is the code:
https://github.com/npolyak/sketches/tree/main/NP.MixedHtmlAndAvaPage

 created a default Avalonia 11.5 project simplified it by removing the view models and placing a hardcoded text within the main view.

Then I modified the index.html file to have Hello World heading on top of the (the div that is replaced with the MainView)

It appears fine before the main view is loaded, but the main view actually takes the whole window space so that I cannot display html above or next to it.

Please help

**Comment by maxkatz6** [comment]
By itself this scenario is supported with correct html. But there is at least one blocking issue that makes this scenario  unusable https://github.com/AvaloniaUI/Avalonia/issues/12780

**Comment by maxkatz6** [comment]
Well. I checked this sample. And also tried to fix https://github.com/AvaloniaUI/Avalonia/issues/12780.
In both cases there is no issue with Avalonia, but only confusion about how (badly) HTML works.

1. "out" component has to have position=relative or absolute
2. You also can't just put couple of HTML elements in order and expect any kind of layout - it's not XAML. The easiest way to layout something properly would be CSS flex or grid.
3. Minor: `<p>` can't have complex children AFAIK. You can check in Chrome devtools that your markup with single `<p>` is broken on two different `<p>` elements.

I tried your sample with some modifications to use CSS Grid (as it's the closest to XAML what we can get):

```diff
-<body style="margin: 0px; overflow: hidden">
+<body style="margin: 0px; overflow: hidden; display: grid; height: 100vh; grid-template-rows: auto 1fr auto">
    <h1>Hello World!</h1>
-   <p>
-    <div id="out">
+    <div id="out" style="position: relative">
        <div id="avalonia-splash" class="center">
            <div class="center">
                <h2 class="purple">
                    Powered by
                    <a class="highlight" href="https://www.avaloniaui.net/" target="_blank">Avalonia UI</a>
                </h2>
            </div>
            <img class="icon" src="Logo.svg" alt="Avalonia Logo" />
        </div>
    </div>
-   <p>
+    <h1>Hello World!</h1>
    <script type='module' src="./main.js"></script>
</body>
```

![image](https://github.com/AvaloniaUI/Avalonia/assets/3163374/0bc19d7e-f509-45e5-8f5e-496e3a149faa)
