### ISSUE TITLE
Windows OpenGL and bgra texture: Angle vs Wgl

### ISSUE THREAD

**Issue by Cpasjuste** [AvaloniaUI/Avalonia#13715]
## Describe the bug
In my project, I'm using an opengl control to render a bgra texture (with silk.net). This worked fine in Linux, but when I switched to windows the texture is just black. When I switch to an rgba texture, the rendering is ok but with red and blue inverted, of course.
Now I noticed that using wgl (opengl core) instead default angle (opengl es) the texture is correctly rendered in bgra.
Unfortunately, when using wgl, my opengl control is more "laggy", not sure how to explain this (the texture data is updated every frames).

I did read somewhere:

```
OpenGL ES 3 does not have mandatory support for GL_BGRA,
but the extension `GL_EXT_texture_format_BGRA8888` supports it and it is present in ANGLE. 
Fallback for OpenGL ES implementations without `GL_EXT_texture_format_BGRA8888` is to use RGBA8 with texture swizzle mask to swap the red and blue channels.
```
So I'm not sure if it's really an avalonia problem, I'll try to investigate more tomorrow.

## Environment 

- OS: windows 11
- Avalonia-Version: 11.05
- GPU: Nvidia rtx 3060 mobile

**Comment by maxkatz6** [comment]
OpenGL ES 3.x support is limited in Angle - https://github.com/google/angle?tab=readme-ov-file#level-of-opengl-es-support-via-backing-renderers
Not sure if your user case fails under these limitations.

**Comment by Cpasjuste** [comment]
Hi,

Thanks for your reply @maxkatz6. I'm still not sure what is the real root of the problem, but for sure it's not really related to Avalonia, so i close this issue..

Just for your information, i do "fix" this problem by using an rgba texture instead bgra then swap red and blue: 
```
gl.TexParameter(TextureTarget.Texture2D, GLEnum.TextureSwizzleR, (int)GLEnum.Blue);
gl.TexParameter(TextureTarget.Texture2D, GLEnum.TextureSwizzleB, (int)GLEnum.Red);
```
