### ISSUE TITLE
Can't override value from style

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#13722]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/13639

<div type='discussions-op-text'>

<sup>Originally posted by **mohdimas** November 17, 2023</sup>
hi there,
it seems that since updating to avalonia 11.0.5, I can no longer override a property of a control inline. It'll always pick the value from the style. So for example:

```
<Style Selector="Path.DownArrowBoldPath">
        <Setter Property="Width"
                Value="12" />
        <Setter Property="Height"
                Value="12" />
        <Setter Property="Data"
                Value="..." />
    </Style>

...

<Path Classes="DownArrowBoldPath"
           Width="20"
           Height="20" />

```

Then the path will have width and height of 12. is there any known issue? many thanks</div>

**Comment by timunie** [comment]
@mohdimas seems to be fixed in latest nightly. Please ping me if it is not fixed for you yet.

**Comment by mohdimas** [comment]
> @mohdimas seems to be fixed in latest nightly. Please ping me if it is not fixed for you yet.

Is it available in `nuget`? I only see `11.0.7`

**Comment by timunie** [comment]
@mohdimas https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

**Comment by mohdimas** [comment]
> @mohdimas https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

I tried to update to the latest version in the nightly build, but unfortunately it doesn't solve the issue. I tested it in this [repo](https://github.com/mohdimas/AvaloniaTest).


The inline property in a path that is defined in a template still can't override property from the style.

<img width="1041" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/1266072/b64ed216-5325-4b29-9182-509db0dcf3f4">
