### ISSUE TITLE
Add RadiusX/RadiusY to RectangleGeometry

### ISSUE THREAD

**Issue by msneijders** [AvaloniaUI/Avalonia#13725]
In WPF RectangleGeometry has `RadiusX` and `RadiusY` properties to get rounded corners.

I'd like to use a rounded rectangle as a clipping to a control in Avalonia.

In [WPF](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/how-to-round-the-corners-of-a-rectanglegeometry?view=netframeworkdesktop-4.8):
```xaml
<!-- Create a rectangle with rounded corners
             by giving the RectangleGeometry a RadiusX
             and a RadiusY of 10.  -->
          <RectangleGeometry
            Rect="20,20,150,50" RadiusX="10" RadiusY="10" />
```

**Comment by robloo** [comment]
I might get to this over the holidays along with the BackgroundSizing work. What is required here is also similar to what I did for Rectangle itself and I can use it there too.

**Comment by robloo** [comment]
This is coming in with BackgroundSizing. It's sharing the same code a few other places.
