### ISSUE TITLE
Add a possibility to refresh a binding from the code-behind.

### ISSUE THREAD

**Issue by VladiStep** [AvaloniaUI/Avalonia#13734]
## Is your feature request related to a problem? Please describe.
In WPF, it's possible to do something like this: `textBlock.GetBindingExpression(TextBlock.TextProperty).UpdateSource()`.
But it seems you can't do that in AvaloniaUI.

## Describe the solution you'd like
There should be some alternative to the WPF method I described.

## Describe alternatives you've considered
I guess it's needed to rework an existing `internal BindingExpression` class so that you can get it for a property and then call `UpdateSource()` on it.

**Comment by maxkatz6** [comment]
There is no `UpdateSourceTrigger=Explicit` support yet, and this API doesn't make sense without it.
But it is planned https://github.com/AvaloniaUI/Avalonia/commit/bee98ad9479a2c27dfd68dc38b09b01882b1c762#diff-ccfdf6768edfce7a5cf7bb4a103e15abeeb53ba684bf457df6d52d3f61a9cdb2

**Comment by timunie** [comment]
Avalonia.Behviors may be useful for the time beeing. See: https://github.com/AvaloniaUI/Avalonia/issues/3754#issuecomment-861576596

**Comment by grokys** [comment]
I'm currently working in a binding refactor which includes this feature. It's not quite ready for a PR yet but the brach is `refactor/bindings`.
