### ISSUE TITLE
Can not bind a style class using a Multibinding

### ISSUE THREAD

**Issue by exp111** [AvaloniaUI/Avalonia#13741]
## Is your feature request related to a problem? Please describe.
I'm trying to bind a style class using a Multibinding:
```xml
 <Button>
     <Button.Classes.Checked>
         <MultiBinding Converter="{StaticResource EqualsConverter}">
             <Binding Path="$parent[ItemsControl].((vm:ChannelListViewModel)DataContext).SelectedChannel" />
             <Binding Path="." />
         </MultiBinding>
     </Button.Classes.Checked>
</Button>
```
[(supposed to be used here instead of a ToggleButton)](https://github.com/TurbulenceDev/Turbulence/blob/master/Turbulence.Desktop/Views/Main/ChannelListView.axaml#L38-L42)

This causes the error `Unable to resolve suitable regular or attached property Classes.Checked on type Avalonia.Controls:Avalonia.Controls.Primitives.Button Line 36, position 22`

Also asked here: https://stackoverflow.com/questions/77235308/binding-classes-in-avalonia-using-a-multibinding

## Describe the solution you'd like
Make it possible to bind a style class using a multibinding

## Describe alternatives you've considered
I can use `Classes.Checked={Binding .}`, but that does not support Multibinding.
Someone also mentioned Markup Extensions, but I have no clue how to do that.

## Additional context
<details>
<summary>Complete Sample</summary>

Window.xaml
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:vm="clr-namespace:Turbulence.Desktop;assembly=Turbulence.Desktop"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="Turbulence.Desktop.Window"
        x:DataType="vm:WindowViewModel"
        Title="Window">
    <Window.DataContext>
        <vm:WindowViewModel />
    </Window.DataContext>
    <Button>
        <Button.Classes.Checked>
            <MultiBinding Converter="{x:Static BoolConverters.And}">
                <Binding Path="Bool1" />
                <Binding Path="Bool2" />
            </MultiBinding>
        </Button.Classes.Checked>
    </Button>
</Window>
```
WindowViewModel.cs
```cs
namespace Turbulence.Desktop;

public class WindowViewModel
{
    public bool Bool1 { get; set; } = true;
    public bool Bool2 { get; set; } = false;
}
```
</details>

**Comment by timunie** [comment]
can you test:

```xml
 <Button>
     <Classes.Checked>
         <MultiBinding Converter="{StaticResource EqualsConverter}">
             <Binding Path="$parent[ItemsControl].((vm:ChannelListViewModel)DataContext).SelectedChannel" />
             <Binding Path="." />
         </MultiBinding>
     </Classes.Checked>
</Button>
```

**Comment by exp111** [comment]
> can you test:
> 
> ```
>  <Button>
>      <Classes.Checked>
>          <MultiBinding Converter="{StaticResource EqualsConverter}">
>              <Binding Path="$parent[ItemsControl].((vm:ChannelListViewModel)DataContext).SelectedChannel" />
>              <Binding Path="." />
>          </MultiBinding>
>      </Classes.Checked>
> </Button>
> ```

Yes this worked. I will close this issue and we will pretend this never happened.
