### ISSUE TITLE
`BoxShadow` Render issue with `Border` in `11.1.999-cibuild0042398-beta`

### ISSUE THREAD

**Issue by Coloryr** [AvaloniaUI/Avalonia#13744]
## Describe the bug
BoxShadow render incorrect.

## To Reproduce

```
<Window
    x:Class="AvaloniaApplication1.Views.MainWindow"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:views="clr-namespace:AvaloniaApplication1.Views"
    xmlns:vm="using:AvaloniaApplication1.ViewModels"
    Title="AvaloniaApplication1"
    d:DesignHeight="450"
    d:DesignWidth="800"
    Background="Transparent"
    ExtendClientAreaChromeHints="NoChrome"
    ExtendClientAreaTitleBarHeightHint="-1"
    ExtendClientAreaToDecorationsHint="True"
    Icon="/Assets/avalonia-logo.ico"
    SystemDecorations="BorderOnly"
    TransparencyBackgroundFallback="Transparent"
    mc:Ignorable="d">
    <Border Margin="5" BoxShadow="0 0 5 0 DarkGray">
        <DockPanel>
            <views:MainView Background="White" />
        </DockPanel>
    </Border>
</Window>
```

## Expected behavior
BoxShadow render well

![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/8a864f6f-b41d-4766-be79-fdd929956a60)

## Screenshots
In `11.1.999-cibuild0042398-beta`
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/e3aad2a3-3804-4b60-8824-e168ded7cf46)

In `11.0.5`
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/8a864f6f-b41d-4766-be79-fdd929956a60)

## Environment 

- OS: [e.g. Windows, Mac, Linux (State distribution), Android, iOS, Browser]
- Avalonia-Version: [e.g. 11.x.y or 0.10.x]

**Comment by maxkatz6** [comment]
It doesn't look like it has anything to do with a box shadow, but instead a problem with Window border. Right?

**Comment by Coloryr** [comment]
> It doesn't look like it has anything to do with a box shadow, but instead a problem with Window border. Right?

No, the `Window border` is remove, I use a `Border` and `BoxShadow` to make a fake `Window border`

**Comment by Coloryr** [comment]
I need some `API` in nightly-build, so can't use `11.0.5`.

**Comment by Coloryr** [comment]
> /cc @emmauss as you were working on the Win32 stuff iirc. Is the new behavior by design?

It look like change something in nightly-build
