### ISSUE TITLE
Suggestion: Rename or alias StackPanel.Gap to StackPanel.Spacing to match UWP

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1374]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.stackpanel#Windows_UI_Xaml_Controls_StackPanel_Spacing

**Comment by grokys** [comment]
Good idea! I didn't realize UWP had this property.

**Comment by danwalmsley** [comment]
its not had it for very long! only since fall creators update.

**Comment by grokys** [comment]
@VladimirAkopyan I noticed you gave this a thumbs-down. Would this cause problems for you?

**Comment by VladimirAkopyan** [comment]
@grokys nah just randomly clicked the wrong button
