### ISSUE TITLE
Targeting .NET 8 is missing libHarfBuzzSharp.so and libSkiaSharp.so

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#13758]
## Describe the bug
Switching to .NET 8 and publish, there is no libSkiaSharp.so and libHarfBuzzSharp.so file in publish folder. Thus the application doesn't work. Switching back to .NET 7 these files are copied to publish folder.

## To Reproduce

1. Create avalonia project
2. Create Visual Studio publish profile with:
&nbsp;&nbsp;&nbsp;- Self-contained
&nbsp;&nbsp;&nbsp;- Target framework: .NET 8.0
&nbsp;&nbsp;&nbsp;- Target runtime: linux-x64
&nbsp;&nbsp;&nbsp;- [X] Produce single file
&nbsp;&nbsp;&nbsp;- [X] Trim unused code
3. Publish and open publish folder -> files are missing
4. Change publish profile to .NET 7, publish and open folder again -> files exist

## Expected behavior
libSkiaSharp.so and libHarfBuzzSharp.so are copied to publish folder

## Environment 

- OS: Target: Linux, built on: Windows 11
- Avalonia-Version: 11.0.5
- VS Community 17.9.0 Preview 1

## Additional context
Switching to .NET 7 and publish again, the files are copied.

**Comment by timunie** [comment]
please try nightly for .NET8 support. I believe it should be fixed there.

**Comment by Symbai** [comment]
Confirmed its fixed
