### ISSUE TITLE
Remove need for assembly in clr-namespace.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#1375]
We should be able to specify `clr-namespace` XAML namespaces without the `;assembly=` part now.

In addition, if the assembly part is not supplied, we just throw a `"System.ArgumentOutOfRangeException: Length cannot be less than zero"` exception so it's not obvious what's going wrong.

**Comment by kekekeks** [comment]
Where it should load the type from? What if the assembly containing the type wasn't loaded yet?

**Comment by grokys** [comment]
It would load the type from the assembly containing the XAML, so the assembly would be loaded. This is how it works on WPF, and we already do something [similar for bitmaps](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Markup/Avalonia.Markup.Xaml/Converters/BitmapTypeConverter.cs#L33).

**Comment by kekekeks** [comment]
We should set `LocalAssembly` property on `XamlXmlReaderSettings`, I think it does exactly that.

**Comment by kekekeks** [comment]
Hmmm, it's already being set in https://github.com/AvaloniaUI/Avalonia/blob/master/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoaderPortableXaml.cs#L178

**Comment by kekekeks** [comment]
I've just checked with control catalog and it already works this way:

```xml
<Window xmlns="https://github.com/avaloniaui" MinWidth="500" MinHeight="300"
        Title="Avalonia Control Gallery"
        Icon="resm:ControlCatalog.Assets.test_icon.ico?assembly=ControlCatalog"
        xmlns:local="clr-namespace:ControlCatalog">
    <local:MainView/>
</Window>
```

It does *not* however, work with previewer, since it doesn't pass any rootInstance.
