### ISSUE TITLE
[Feature]: Make CalendarDayButton to expose it's assigned date

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#13757]
Options:
- add it as a Property
- use the `Tag`-property for it

### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/13642

<div type='discussions-op-text'>

<sup>Originally posted by **alessandrofrancesconi** November 17, 2023</sup>
I have a `<Calendar>` and I need to highlight particular days.

For example, currently I have this UI (today is 17th):
![image](https://github.com/AvaloniaUI/Avalonia/assets/1595223/a4265b21-aaff-49c6-aa31-948a500d1068)

While I need to re-color some cells depending on some logic:
![image](https://github.com/AvaloniaUI/Avalonia/assets/1595223/e5120980-a0f5-4ba1-8080-f5abf0c3b6d8)

thanks for the help!
</div>

**Comment by maxkatz6** [comment]
I think this issue can be closed, as original author already got answer with multiple possible solutions. I just sent one another alternative how to do it.

**Comment by timunie** [comment]
Turns out `DataContext` is actually the assigned date. However when used in a converter the DataContext can be `MainViewMOdel` when the control is not loaded yet. So make sure to use a safe-cast.
