### ISSUE TITLE
.NET 8.0 using PublishAot causes the previewer not to work.

### ISSUE THREAD

**Issue by BlankWhite** [AvaloniaUI/Avalonia#13760]
## Describe the bug
.NET 8.0 using PublishAot causes the previewer not to work ,Switching to .net7.0 works normally.

## To Reproduce

1. change target framework to .net8.0
2. add publishAot ,then rebuild project
```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
    One for Windows with net7.0-windows TFM, one for MacOS with net7.0-macos and one with net7.0 TFM for Linux.-->
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
	<PublishAot>true</PublishAot>
	<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>
```
3. reopen previewer ,see errors
![Snipaste_2023-11-28_16-44-17](https://github.com/AvaloniaUI/Avalonia/assets/11631255/0f30f671-5450-4c13-8b49-8560ea5e4e88)

## Environment 
- IDE VS2022
- OS: Windows10
- Avalonia-Version: 11.0.5

**Comment by timunie** [comment]
Please try nightly builds for NET8 support.

**Comment by maxkatz6** [comment]
Well, previewer cannot be supported with PublishAot binaries, as AOT doesn't support dynamic code which is essential for the previewer.
Can you replace PublishAot with something like this:
```
<PublishAot Condition="'$(Configuration)' != 'Debug'" >true</PublishAot>
```
?

**Comment by BlankWhite** [comment]
> Well, previewer cannot be supported with PublishAot binaries, as AOT doesn't support dynamic code which is essential for the previewer. Can you replace PublishAot with something like this:
> 
> ```
> <PublishAot Condition="'$(Configuration)' != 'Debug'" >true</PublishAot>
> ```
> 
> ?
thank you ,it works

**Comment by TerryYoung518** [comment]
It seems that the `Condition` attribute doesn't work as expected for `PublishAot`. As a workaround, you can use the following configuration in your csproj file:

```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PublishAot>false</PublishAot>
</PropertyGroup>
```

This configuration explicitly sets `PublishAot` to false in the Debug configuration for AnyCPU platform. This should ensure that Ahead-Of-Time (AOT) compilation is not enabled during debugging.

**Comment by Asces** [comment]
> Well, previewer cannot be supported with PublishAot binaries, as AOT doesn't support dynamic code which is essential for the previewer. Can you replace PublishAot with something like this:
> 
> ```
> <PublishAot Condition="'$(Configuration)' != 'Debug'" >true</PublishAot>
> ```
> 
> ?

I have the same problem,   When I set to False ，It works.   But I want the VS to give me compatibility tips for AOT。Is there any other way?

**Comment by MrJul** [comment]
> I have the same problem, When I set to False ，It works. But I want the VS to give me compatibility tips for AOT。Is there any other way?

You can set `IsAotCompatible` to `true`, which enables trim and AOT analyzers.
See [AOT-compatibility analyzers](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=windows%2Cnet8#aot-compatibility-analyzers)

**Comment by Asces** [comment]
> > I have the same problem, When I set to False ，It works. But I want the VS to give me compatibility tips for AOT。Is there any other way?
> 
> You can set `IsAotCompatible` to `true`, which enables trim and AOT analyzers. See [AOT-compatibility analyzers](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=windows%2Cnet8#aot-compatibility-analyzers)

Thanks !    It  works !
