### ISSUE TITLE
AcceptsReturn & Shift not working in TextBox within Flyout (macOS)

### ISSUE THREAD

**Issue by cfnfy** [AvaloniaUI/Avalonia#13761]
## Describe the bug
When a TextBox is within a Flyout, the shift key isn't recognised, restricting input of capital letters to CapsLock. Also, return key always results in a new line, even when AcceptsReturn is false.

This appears to be a macOS specific issue. I have tested on Windows and TextBox's are working as expected there.

## To Reproduce
Minimal repro below.

```
<Button Content="Click Here">
        <Button.Flyout>
            <Flyout>
                <TextBox AcceptsReturn="False"/>
            </Flyout>
        </Button.Flyout>
    </Button>
```

## Expected behavior
- Shift + letter should input capitalised letter.
- AcceptsReturn set to False should prevent return from creating a new line.

## Environment

- OS: macOS Arm64
- Avalonia-Version: 11.1.999-cibuuld0042410-beta

**Comment by timunie** [comment]
I don't find that build number even. Using latest nightly works as expected for me. Please make sure to test again using latest nightly build.

**Comment by timunie** [comment]
Okay so mac only then. Thx for clarifying
