### ISSUE TITLE
When canceling `Collapsing` event of `Expander` its icon still flips

### ISSUE THREAD

**Issue by sinatrocious** [AvaloniaUI/Avalonia#13768]
## Describe the bug
I am trying to programmatically prevent user from collapsing `Expander`, for this I set `e.Cancel = true` in `Collapsing` event of `Expander`. This works, the content of expander is not collapsing, but the icon flips.

## To Reproduce

1. Create new "Avalonia C# Project", 
2. Add `Expander` to main window:

```
<Expander x:Name="expander" Header="Expander"/>`
```

4. In constructor of main window add handler:

```
expander.Collapsing += (s, e) => e.Cancel = true;
```

6. Compile project and either run desktop project or directly in axaml designer click `Expander`: the icon flips.

## Expected behavior
The icon of `Expander` should not flip when collapsing is cancelled.

## Screenshots

![Avalonia Expander Collapsing Cancel](https://github.com/AvaloniaUI/Avalonia/assets/91904521/19dd0d2d-cf04-47af-915c-54a442e2083d)

## Environment 

- OS: Windows 11, 64x
- Avalonia-Version: 11.0.2

## Additional context
---

**Comment by robloo** [comment]
I no expert in Avalonia's animations but it's probably a problem with the property change notification due to the way cancel collapsing is occurring. The ToggleButton checked state is initially allowed to change and then immediately reverted by the Expander control itself. For some reason animations aren't picking up that change from Checked -> Not Checked -> Checked properly.

https://github.com/AvaloniaUI/Avalonia/blob/b630f21b7e8c940f51fa341d575027041b92bd96/src/Avalonia.Themes.Fluent/Controls/Expander.xaml#L118-L139

**Comment by timunie** [comment]
I wonder if the bindings refractory helps here 🤔

**Comment by memorydream** [comment]
I have a hack fix (maybe?) , add `:expanded` to expander header(ToggleButton) and replace `<Style Selector="^:checked ...>` with `<Style Selector="^:expanded ...>` and set header PseudoClasses in Expander after ContentTransition running done

like this:
![image](https://github.com/AvaloniaUI/Avalonia/assets/34763046/56c399f6-03f1-4e72-8fc9-2145eab391d3)

![image](https://github.com/AvaloniaUI/Avalonia/assets/34763046/ad6cbf02-5b41-4b78-aa43-6b297e00081d)

but Simple theme how do ?

**Comment by robloo** [comment]
@memorydream It's actually an interesting idea to trigger animations from the :expanded pseudoclass instead. That pseudoclass should always have the correct state and not quickly change and then reverted. It actually seems more correct this way.

I wonder if we can make this a permanent fix by moving the styles for the animations out of the header toggle button and into the expander itself... although I think we might run into a problem where nested template access is no longer allowed in Avalonia v11+.

**Comment by memorydream** [comment]
> @memorydream It's actually an interesting idea to trigger animations from the :expanded pseudoclass instead. That pseudoclass should always have the correct state and not quickly change and then reverted. It actually seems more correct this way.
> 
> I wonder if we can make this a permanent fix by moving the styles for the animations out of the header toggle button and into the expander itself... although I think we might run into a problem where nested template access is no longer allowed in Avalonia v11+.

I tried , but can not access nested template... so have other idea? or should accecpt the hack fix?

**Comment by robloo** [comment]
Let me think about this some more.

It also seems logical to set the :expanded pseudoclass on the header control itself. It's essentially inheriting the pseudoclass which does make sense and is probably done other places. I'm thinking it might be OK to upgrade this from "hack fix" to an actual "fix" :) Then the header control would always have the pseudoclass state information too which seems useful for other future styling or if apps need it.

I want to dig into the code a bit and see how pseudoclass inheritance works. @timunie might have some good feedback here too.

**Comment by robloo** [comment]
I recalled the "hack" that was done for SplitButton as well. This is another idea here to convey the "IsExpanded" information to the header ToggleButton. So we have two options now:

 1. Above discussion about setting `:expanded` on the header `ToggleButton` in the template directly from code-behind
 2. Pass the information using the `Tag` property from the `Expander` to the header `ToggleButton`. This bypasses the nested template restriction. Below is what is done in `SplitButton`:

The SplitButton creates special values and adds them to the Tag of the child Button. These special values generally represent the pseudoclass(es).

https://github.com/AvaloniaUI/Avalonia/blob/b630f21b7e8c940f51fa341d575027041b92bd96/src/Avalonia.Themes.Fluent/Controls/SplitButton.xaml#L194-L204

The Button has selectors based on these special Tag values

https://github.com/AvaloniaUI/Avalonia/blob/b630f21b7e8c940f51fa341d575027041b92bd96/src/Avalonia.Themes.Fluent/Controls/SplitButton.xaml#L78-L89

---

I'm thinking we probably shouldn't re-invent the wheel here and should go with option 2 the same as SplitButton. This isn't great but is established convention and can be done entirely within the XAML control theme itself. It also should work just fine for the simple theme.

cc @grokys @maxkatz6 as this is another place nested template selectors in ControlTheme would be useful.

**Comment by robloo** [comment]
@memorydream Let me know if you plan on doing a PR for this. Otherwise, I will probably get to it this weekend myself.
