### ISSUE TITLE
Black screen on fast resize

### ISSUE THREAD

**Issue by zii-dmg** [AvaloniaUI/Avalonia#1378]
Windows 7, ControlCatalog.Desktop-0.6.0.zip from https://ci.appveyor.com/project/AvaloniaUI/Avalonia/branch/master/artifacts (c93335e6)

Try to fast resize window, part of it turns black forever, mouse clicks on buttons not working anymore.
![blackscreenonfastresize](https://user-images.githubusercontent.com/2846896/36355411-d8d21d04-14f3-11e8-97ff-8bd7e1462462.png)
[BlackScreenOnFastResizeVideo.zip](https://github.com/AvaloniaUI/Avalonia/files/1734970/BlackScreenOnFastResizeVideo.zip)

**Comment by grokys** [comment]
Hmm unable to reproduce this here. Main difference is that I'm on Windows 10. Wonder if this is a Win7 problem?

**Comment by zii-dmg** [comment]
No bug if I disable Aero. Have Nvidia Geforce GTX 970, driver version 388.71.

**Comment by zii-dmg** [comment]
Launched debug in VS 2017. After black screen have repeating line in output: `Exception thrown: 'SharpDX.SharpDXException' in SharpDX.dll`.

Breaking on all exceptions showed:
```
SharpDX.SharpDXException: 'HRESULT: [0x88982F80], 
Module: [SharpDX.Direct2D1], 
ApiCode: [D2DERR_UNSUPPORTED_PIXEL_FORMAT/UnsupportedPixelFormat], 
Message: Unknown'
```

in `src\Windows\Avalonia.Direct2D1\Media\Imaging\D2DRenderTargetBitmapImpl.cs` line 36:
```
public static D2DRenderTargetBitmapImpl CreateCompatible(
    ImagingFactory imagingFactory,
    DirectWriteFactory dwriteFactory,
    SharpDX.Direct2D1.RenderTarget renderTarget,
    Size size)
{
    var bitmapRenderTarget = new BitmapRenderTarget(
        renderTarget,
        CompatibleRenderTargetOptions.None,
        new Size2F((float)size.Width, (float)size.Height));
    return new D2DRenderTargetBitmapImpl(imagingFactory, dwriteFactory, bitmapRenderTarget);
}
```

**Comment by zii-dmg** [comment]
Maybe some race condition on using Direct2D.

**Comment by zii-dmg** [comment]
ControlCatalog.NetCore doesn't have this bug, only ControlCatalog.Desktop.

**Comment by kekekeks** [comment]
@grokys I guess deferred renderer keeps trying to create a layer for a stale render target. We need to handle such condition as `RenderTargetCorruptedException` and react accordingly.

**Comment by Gillibald** [comment]
Is this still an issue? If so it would be interesting if this still happens with my D2D cleanup.

**Comment by zii-dmg** [comment]
Still exists on b02d0c23.

**Comment by zii-dmg** [comment]
On b02d0c2:

Message:
HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown

Stack:
```
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.Factory2.CreateSwapChainForHwnd(ComObject deviceRef, IntPtr hWnd, SwapChainDescription1& descRef, Nullable`1 fullscreenDescRef, Output restrictToOutputRef, SwapChain1 swapChainOut)
   at SharpDX.DXGI.SwapChain1..ctor(Factory2 factory, ComObject device, IntPtr hwnd, SwapChainDescription1& description, Nullable`1 fullScreenDescription, Output restrictToOutput)
   at Avalonia.Direct2D1.HwndRenderTarget.CreateSwapChain(Factory2 dxgiFactory, SwapChainDescription1 swapChainDesc)
```

**Comment by Gillibald** [comment]
The issue here is the fact that a resize of the render target is implicitly triggered by a new render call. We should resize the render target explicitly by introducing a resize method and stop all render calls until the render target is resized. That way the surface(window) and the render target should not get out of sync. We just need clean states during that process.

**Comment by ahopper** [comment]
something very similar happens with the skia gpu code for me on windows 10.

**Comment by Omniusz** [comment]
I'm still having the same issue with .7 build.

I'm using Windows 10 18334.19h1 build
GTX 970 with driver 418.91 build

**Comment by zii-dmg** [comment]
Not having issue anymore on Windows 7 / 10 (1909), nvidia GPU, current master branch.
