### ISSUE TITLE
Window become higher when repeat `Maximized` and `Normal`

### ISSUE THREAD

**Issue by Coloryr** [AvaloniaUI/Avalonia#13791]
## Describe the bug
Window become bigger when repeat `Maximized` and `Normal`.
it appear at `11.1.999-cibuild0042513-beta` not `11.0.5`, and `11.0.5` no such issue.

## To Reproduce

1. WindowState = WindowState.Maximized
2. WindowState = WindowState.Normal
3. repeat 1 and 2

[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/13522101/AvaloniaApplication1.zip)

## Screenshots
first size
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/8b5cf202-586e-42f0-9a23-810ee0c6d964)

`Maximized` it and `Normal`
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/44892931-702a-4e18-b044-a09631d5ffd2)

## Environment 

- OS: Windows
- Avalonia-Version: 11.1.999-cibuild0042513-beta

**Comment by Coloryr** [comment]
It happen when window set 
```
    ExtendClientAreaChromeHints="NoChrome"
    ExtendClientAreaTitleBarHeightHint="-1"
    ExtendClientAreaToDecorationsHint="True"
```

**Comment by timunie** [comment]
@Coloryr please fill out Avalonia version and OS used. Also worth to try nightly if it is not.

**Comment by Coloryr** [comment]
> @Coloryr please fill out Avalonia version and OS used. Also worth to try nightly if it is not.

ok, but i need some API in `nightly`, so i'm try use it.

**Comment by timunie** [comment]
probably, yes.

**Comment by Coloryr** [comment]
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/f8517486-7828-46c7-9e1f-95235670b844)
open it, and change state
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/ba36b8d8-e980-471c-9a1c-2b6f5aafba06)
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/d940ff18-5bde-4989-96c3-f6388e1fb749)
the title bar white is gone
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/a069ba67-2f32-469b-9e65-2f81e53cbb33)

**Comment by Coloryr** [comment]
Wait what?
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/8914b4f2-574c-4271-af70-6e5279ecf9ff)

**Comment by Coloryr** [comment]
I can't find why is become higher.

**Comment by Coloryr** [comment]
> probably related - combination of
> 
> ```
> ExtendClientAreaToDecorationsHint="True" 
> ShowInTaskbar="False"
> ```
> 
> Causing this window to not respect Width / Height setted in XAML. Manual setting width/heigh after InitializeComponent works fine.
> 
> ```
> <Window xmlns="https://github.com/avaloniaui"
>         xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>         xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
>         xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
>         mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
>         x:Class="JustyBase.Window1"
> 		Width="200"
> 		Height="200"
> 		ExtendClientAreaToDecorationsHint="True"
>                 ShowInTaskbar="False"
>         Title="Window1">
>   Welcome to Avalonia!
> </Window>
> ```
Setted Width / Height no work, still higher

**Comment by Coloryr** [comment]
`HandelResized` call twice too, first time is right height, but second is incorrect, so it make `ClientSize` heigher.
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/597f2a01-6174-47d2-99ca-368cb6705a72)
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/46270eaf-7c74-4f4d-824d-bb6bcf9af8db)

**Comment by timunie** [comment]
@Coloryr can you test nightly again? Not that the issue is in nightly but not in 11.0.6 release. If it is present in nightly, maybe re-open this issue.

Thx

**Comment by Coloryr** [comment]
No issus in 11.1.999-cibuild0042682-beta
https://github.com/AvaloniaUI/Avalonia/assets/26276037/efa30020-f31e-45d6-8b44-c2da2e55be56

**Comment by Coloryr** [comment]
issue in `11.1.999-cibuild0042513-beta`

**Comment by timunie** [comment]
Thanks :-). Good news!
