### ISSUE TITLE
Design.DataContext causes 2nd viewmodel instance at runtime

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#1380]
To reproduce use the mvvm 0.6.0.1 template , add a constructor to the view model and break on it.  Here it is called twice. Removing  
<Design.DataContext>
    <vm:MainWindowViewModel/>
  </Design.DataContext>
from the view causes only one instance to be created.

**Comment by kekekeks** [comment]
That's a  known issue, we need to somehow ignore the content of design properties during runtime XAML parsing..

For now you can use `x:Static` with a property that checks for `Design.IsDesignMode`.

**Comment by ahopper** [comment]
Thanks,
is it worth commenting out the Design.DataContext in the template until it is fixed.  It could cause all sorts of subtle errors for the unaware.

**Comment by kekekeks** [comment]
It's only *evaluated* in the runtime, it shouldn't affect anything else. Designer applies design-mode properties by calling [`Design.ApplyDesignModeProperties`](https://github.com/AvaloniaUI/Avalonia/blob/9a1348b37b87a30048ddb197c5c2f3d6545bfe6e//src/Avalonia.Controls/Design.cs#L67) You should be fine with a static property with `IsDesignMode` condition.

**Comment by ahopper** [comment]
I'm fine with the work around but for a newcomer to avalonia, using the mvvm template as is, they will have a second copy of the view model floating around and it may not be obvious but may cause bugs. In my case it was obvious as each model tried to bind to the same udp port and threw an exception, I still wasted time checking nothing else was using the port before realizing what was happening.

**Comment by kekekeks** [comment]
I agree that we should document it somewhere or at least implement that static property approach.

**Comment by kekekeks** [comment]
https://github.com/cwensley/Portable.Xaml/pull/88

**Comment by ahopper** [comment]
This is still an issue with the default 8.0 template.

**Comment by kekekeks** [comment]
I think we should remove `Design.*` attached properties in the next release.

**Comment by grokys** [comment]
I admit that I'm not a great fan of 1. their syntax (all the `xmlns` noise) 2. the way that design view models have to be defined in code (some sort of markup would be preferable to me) and 3. this bug.

However I'm not sure we should completely remove them without an alternative.

**Comment by grokys** [comment]
Reading this again, I may have misunderstood: are you suggesting we remove the `Design.*` but leave the `d:DesignWidth` etc properties?

**Comment by kekekeks** [comment]
>are you suggesting we remove the Design.* properties but leave the d:DesignWidth etc properties?

Yes.

**Comment by kekekeks** [comment]
Alternatively, we can wait for compiler and make `Design.*` properties completely ignored at run time.

**Comment by grokys** [comment]
I actually prefer the `Design.*` properties because of the `xmlns` noise when using the `d:` properties...

So yeah It would be nice if we could just have a way of marking certain attached properties as design-time only when using the compiler.
