### ISSUE TITLE
`OpenGlControlBase` enters `OnOpenGlInit` with OpenGL errors

### ISSUE THREAD

**Issue by Dragorn421** [AvaloniaUI/Avalonia#13807]
## Describe the bug
When implement `OnOpenGlInit` in an `OpenGlControlBase` and checking `gl.GetError()` for any error, there is one, presumably from something in Avalonia's code.

## To Reproduce

1. Clone, build and run https://github.com/Dragorn421/DragoStuff/tree/ffe12b1003c3e6cd92419d7fdaab97b3c90c5dc4
2. Check the debug prints:
```
GL1.OnOpenGlInit
GL1.CheckError 1280
GL1.OnOpenGlRender
GL1.CheckError OK
GL1.CheckError OK
GL1.OnOpenGlRender
GL1.CheckError OK
GL1.CheckError OK
```
3. Notice `GL1.CheckError 1280`. It is printed by https://github.com/Dragorn421/DragoStuff/blob/ffe12b1003c3e6cd92419d7fdaab97b3c90c5dc4/MyOpenGLControl.cs#L29 , before the child control does any OpenGL call, so it seems to be an error originating from something in Avalonia.

## Expected behavior
`gl.GetError()` should always return `GL_NO_ERROR` on entering child/user methods like `OnOpenGlInit`

## Environment

- OS: Kubuntu 23.10 (Linux, X11)
- Avalonia-Version: 11.0.5

**Comment by Coloryr** [comment]
`1280` is mean `GL_INVALID_ENUM`
Some operations use incorrect parameters, but this is related to the version of `OpenGL`

**Comment by Dragorn421** [comment]
Still in Avalonia 11.0.10

**Comment by timunie** [comment]
@Dragorn421 if you wanted to check newer version, worth to try 11.1 betas

**Comment by Dragorn421** [comment]
Still in Avalonia 11.1.1
