### ISSUE TITLE
Build error on Avalonia project template

### ISSUE THREAD

**Issue by TonyHenrique** [AvaloniaUI/Avalonia#1381]
I installed Avalonia ( https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaforVisualStudio )

On Visual Studio 2017 (Version 15.6.0 Preview 5.0)

Then created a new Project:

![image](https://user-images.githubusercontent.com/6307623/36392185-e487b6c8-1588-11e8-8a26-bf1d360f0384.png)

Then when I BUILD the solution, this error appears:

`1>C:\Program Files\dotnet\sdk\2.1.100-preview-007363\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file 'C:\temp\AvaloniaApplication1\AvaloniaApplication1\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.1/win7-x86'. Ensure that restore has run and that you have included 'net461' in the TargetFrameworks for your project. You may also need to include 'win7-x86' in your project's RuntimeIdentifiers.`

**Comment by grokys** [comment]
Hi @TonyHenrique, that's strange, not sure what's wrong there. Have you edited the .csproj after creating the project at all? What happens if you change the target framework to just target `netcoreapp2.0`?

**Comment by TonyHenrique** [comment]
Hum, I did not edit the .csproj

What happened is that the template comes with:

    <TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>

Then after changing it to 

    <TargetFrameworks>netcoreapp2.0</TargetFrameworks>

It Works.

**Comment by TonyHenrique** [comment]
I managed to get it working. 
I ended running a XAML GUI (Avalonia) on Linux WSL + Windows 10

See https://twitter.com/tonyvca/status/966674120476909569

![dwpq8okwkaa9hfe](https://user-images.githubusercontent.com/6307623/36545170-1a36196e-17c7-11e8-8eb6-2272d4010e67.jpg)

**Comment by Squantilian** [comment]
Hey there, just dropping in to say that I also received this error when creating a new Avalonia Application (a standard client application, not of the MVVM variety) with Visual Studio 2017 (15.6.1). More importantly, TonyHenrique's solution of removing net461 from the TargetFrameworks in the .csproj corrected this error for me as well.

**Comment by grokys** [comment]
Glad you got it working @TonyHenrique @Squantilian. I'm not sure what was going wrong here, I assume it's some problem in the .NET SDK...

**Comment by RayyanTahir** [comment]
**I'm having following build errors when I create a project template:**


Package Avalonia.Skia 0.6.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Avalonia.Skia 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
The type 'TargetFrameworkAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Predefined type 'System.String' is not defined or imported
The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?)
Predefined type 'System.String' is not defined or imported
Package Avalonia.Win32 0.6.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Avalonia.Win32 0.6.1 supports:
Package Avalonia.Win32 0.6.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / win7-x86. Package Avalonia.Win32 0.6.1 supports:
Package Avalonia.Skia 0.6.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / win7-x86. Package Avalonia.Skia 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Skia 0.6.1 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Avalonia.Skia 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Skia 0.6.1 is not compatible with net461 (.NETFramework,Version=v4.6.1) / win7-x86. Package Avalonia.Skia 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Remote.Protocol 0.6.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Avalonia.Remote.Protocol 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Remote.Protocol 0.6.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / win7-x86. Package Avalonia.Remote.Protocol 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Remote.Protocol 0.6.1 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Avalonia.Remote.Protocol 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Remote.Protocol 0.6.1 is not compatible with net461 (.NETFramework,Version=v4.6.1) / win7-x86. Package Avalonia.Remote.Protocol 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.MonoMac 0.6.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Avalonia.MonoMac 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.MonoMac 0.6.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / win7-x86. Package Avalonia.MonoMac 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.MonoMac 0.6.1 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Avalonia.MonoMac 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.MonoMac 0.6.1 is not compatible with net461 (.NETFramework,Version=v4.6.1) / win7-x86. Package Avalonia.MonoMac 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Gtk3 0.6.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Avalonia.Gtk3 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Gtk3 0.6.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / win7-x86. Package Avalonia.Gtk3 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Gtk3 0.6.1 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Avalonia.Gtk3 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Gtk3 0.6.1 is not compatible with net461 (.NETFramework,Version=v4.6.1) / win7-x86. Package Avalonia.Gtk3 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Direct2D1 0.6.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Avalonia.Direct2D1 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Direct2D1 0.6.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / win7-x86. Package Avalonia.Direct2D1 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Direct2D1 0.6.1 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Avalonia.Direct2D1 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Avalonia.Direct2D1 0.6.1 is not compatible with net461 (.NETFramework,Version=v4.6.1) / win7-x86. Package Avalonia.Direct2D1 0.6.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
One or more packages are incompatible with .NETFramework,Version=v4.6.1.
One or more packages are incompatible with .NETFramework,Version=v4.6.1 (win7-x86).
One or more packages are incompatible with .NETCoreApp,Version=v2.0.
One or more packages are incompatible with .NETCoreApp,Version=v2.0 (win7-x86).

**After removing net461 from target framework in csproj file, I get the following build errors:**


Predefined type 'System.Void' is not defined or imported
Predefined type 'System.Void' is not defined or imported
Multiple assemblies with equivalent identity have been imported: 'C:\Users\clary\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Runtime.InteropServices.WindowsRuntime.dll' and 'C:\Users\clary\.nuget\packages\system.runtime.interopservices.windowsruntime\4.0.1\ref\netstandard1.0\System.Runtime.InteropServices.WindowsRuntime.dll'. Remove one of the duplicate references.
Multiple assemblies with equivalent identity have been imported: 'C:\Users\clary\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Reflection.Emit.Lightweight.dll' and 'C:\Users\clary\.nuget\packages\system.reflection.emit.lightweight\4.3.0\ref\netstandard1.0\System.Reflection.Emit.Lightweight.dll'. Remove one of the duplicate references.
Multiple assemblies with equivalent identity have been imported: 'C:\Users\clary\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Reflection.Emit.ILGeneration.dll' and 'C:\Users\clary\.nuget\packages\system.reflection.emit.ilgeneration\4.3.0\ref\netstandard1.0\System.Reflection.Emit.ILGeneration.dll'. Remove one of the duplicate references.
Multiple assemblies with equivalent identity have been imported: 'C:\Users\clary\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Diagnostics.Contracts.dll' and 'C:\Users\clary\.nuget\packages\system.diagnostics.contracts\4.0.1\ref\netstandard1.0\System.Diagnostics.Contracts.dll'. Remove one of the duplicate references.
Multiple assemblies with equivalent identity have been imported: 'C:\Users\clary\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.ComponentModel.dll' and 'C:\Users\clary\.nuget\packages\system.componentmodel\4.3.0\ref\netstandard1.0\System.ComponentModel.dll'. Remove one of the duplicate references.
Predefined type 'System.Void' is not defined or imported
Predefined type 'System.Boolean' is not defined or imported
Predefined type 'System.Void' is not defined or imported
Predefined type 'System.Void' is not defined or imported
The type 'AssemblyCompanyAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Predefined type 'System.String' is not defined or imported
The type 'AssemblyConfigurationAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Predefined type 'System.String' is not defined or imported
The type 'AssemblyDescriptionAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Predefined type 'System.String' is not defined or imported
The type 'AssemblyFileVersionAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Predefined type 'System.String' is not defined or imported
The type 'AssemblyInformationalVersionAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Predefined type 'System.String' is not defined or imported
The type 'AssemblyProductAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Predefined type 'System.String' is not defined or imported
The type 'AssemblyTitleAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Predefined type 'System.String' is not defined or imported
The type 'AssemblyVersionAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Predefined type 'System.String' is not defined or imported
Predefined type 'System.Object' is not defined or imported
Predefined type 'System.Void' is not defined or imported
Predefined type 'System.String' is not defined or imported
Predefined type 'System.Object' is not defined or imported
The type 'TargetFrameworkAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Predefined type 'System.String' is not defined or imported
The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?)
Predefined type 'System.String' is not defined or imported

**Your help is much appreaciated**

**Comment by jp2masa** [comment]
If you're building from VS, make sure you have at least version 15.3. If you're using the dotnet CLI, make sure you have at least version 2.0.

**Comment by RayyanTahir** [comment]
Thank you jp2masa, turns out I was using VS 2017 (15.1). I'll upgrade now. Thanks again!

**Comment by jmacato** [comment]
Will close this issue since OP's problem has been resolved already. Ping us up when this needs to be reopened.
