### ISSUE TITLE
Fullscreen Functionality on Ubuntu with AvaloniaUI

### ISSUE THREAD

**Issue by hn-lyf** [AvaloniaUI/Avalonia#13817]
Hello,

I hope this message finds you well. I am currently working on an AvaloniaUI application and I have a requirement to implement fullscreen functionality specifically for Ubuntu. I have been exploring different methods, but I haven't been successful so far.

Could you please provide guidance on how to achieve fullscreen functionality in an AvaloniaUI application running on Ubuntu? I would like the application to occupy the entire screen, hiding the title bar and borders for a better user experience.

Any help or code examples you can provide would be greatly appreciated. Thank you in advance for your assistance.

Best regards,

**Comment by timunie** [comment]
hello @hn-lyf 

you are welcome. However filing an issue requires the filling of the issue templates. For questions like yours, please use Discussions or join us on telegram https://t.me/Avalonia

Thanks and happy coding
Tim
