### ISSUE TITLE
AndroidSystemNavigationManagerImpl object not to be garbage collected

### ISSUE THREAD

**Issue by vrjure** [AvaloniaUI/Avalonia#13829]
## Describe the bug

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Android/Avalonia.Android/Platform/AndroidSystemNavigationManager.cs

`AndroidSystemNavigationManagerImpl` subscribed the `IActivityNavigationService.BackRequested` event but did not unsubscribe.
It causes the `AndroidSystemNavigationManagerImpl` object not to be garbage collected.

## To Reproduce

Just new an AvaloniaView.

## Expected behavior

`AndroidSystemNavigationManagerImpl` object unsubscribe `ISystemNavigationManagerImpl.BackRequested` event at the right time.

## Environment 

- OS: [Android]
- Avalonia-Version: [11.0.5]

**Comment by timunie** [comment]
@vrjure as you seem to know where in the code the issue is, maybe you want to provide a PR?

**Comment by vrjure** [comment]
I want to embed a native control and display avalonia content on top of it. So i manually create AvaloniaView, the code like this:
```csharp
public class EmbedSampleAndroid : INativeDemoControl
{
    public IPlatformHandle CreateControl(bool isSecond, IPlatformHandle parent, Func<IPlatformHandle> createDefault)
    {
        var parentContext = (parent as AndroidViewControlHandle)?.View.Context
            ?? global::Android.App.Application.Context;

        var webView = new global::Android.Webkit.WebView(parentContext);
        webView.LoadUrl("https://www.android.com/");

        var container = new RelativeLayout(parentContext);
        container.AddView(webView);

        var lp = new RelativeLayout.LayoutParams(WindowManagerLayoutParams.MatchParent, 120);
        lp.AddRule(LayoutRules.AlignParentBottom);

        var _overlayLayer = new AvaloniaView(parentContext);
        container.AddView(_overlayLayer, lp);

        return new AndroidViewControlHandle(container);
    }
}
```
The `parentContext` is `AvaloniaMainActivity`, it is alaways used. The `parentContext` is right? Is there another context i can get?

**Comment by emmauss** [comment]
There's still a chance of it not being collected. Take a view hierarchy like this; Activity -> AvaloniaView -> NativeControlHost -> AvaloniaView -> Overlay. The overlay's AvaloniaView may be disposed while the Activity still exist and the parent AvaloniaView still active. That prevents the overlay avaloniaview's toplevel from being GC'd.
