### ISSUE TITLE
Out of Memory crash when D3D Device lost using LowLatencyDxgiSwapChain

### ISSUE THREAD

**Issue by ClxS** [AvaloniaUI/Avalonia#13822]
## Describe the bug
When using LowLatencyDxgiSwapChain, if you lose the D3D Device this causes an allocation loop which will consume all system memory, eventually crashing your app as well as any other process on the system which doesn't handle the OOM state well.

When this issue occurs, you'll notice the memory consumption metric graph in Visual Studio spikes rapidly, hundreds of repeats of the following message get logged:

> [Visual]Exception when rendering: 'System.Runtime.InteropServices.COMException (0x087A0001): Present failed
   at Avalonia.Win32.DirectX.Impl.__MicroComIDXGISwapChainProxy.Present(UInt16 SyncInterval, UInt16 Flags)
   at Avalonia.Win32.DirectX.DxgiRenderTarget.<>c__DisplayClass11_0.<BeginDrawCore>b__0()
   at Avalonia.OpenGL.Egl.EglPlatformSurfaceRenderTargetBase.Session.Dispose()
   at Avalonia.Skia.GlRenderTarget.GlGpuSession.Dispose()
   at Avalonia.Skia.DrawingContextImpl.Dispose()
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #58414077)

## To Reproduce
My setup involves working via Remote Desktop. I don't know if that portion of these steps is necessary but I'll include it for completeness.

1. Connect to another Windows machine using Remote Desktop. This setup should have settings to auto lock the screen after a period of time.
2. Create an app using LowLatencyDxgiSwapChain.
 ```cs
public static AppBuilder BuildAvaloniaApp()
{
    return AppBuilder.Configure<TApp>().UsePlatformDetect().With(
        new Win32PlatformOptions
        {
            CompositionMode = new[]
            {
                Win32CompositionMode.LowLatencyDxgiSwapChain,
            },
        }).WithInterFont().UseReactiveUI().LogToTrace();
}
  ```
3. Run the application.
4. Minimize the Remote Desktop instance
5. Go back to the Remote Desktop instance after several minutes.

## Expected behavior
It to not do this. Confirmed that this behaviour does not occur using either WinUIComposing or RedirectionSurface.

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.5

**Comment by ShadowMarker789** [comment]
Oh, I see. 

(Thanks for the ping kekekeks) 

I'll start working on it.

**Comment by ShadowMarker789** [comment]
> 0x087A0001. The Present operation was invisible to the user. DXGI_STATUS_CLIPPED

🤦‍♂️

If the Microcom runtime hadn't presumed that a non-zero HRESULT code was a failure, everything would have just worked. 

I'll need to make changes to the Microcom IDL definitions to change it to not throw exceptions on non-zero HRESULT codes.

**Comment by ShadowMarker789** [comment]
Fix in [PR 13869](https://github.com/AvaloniaUI/Avalonia/pull/13869)
