### ISSUE TITLE
Checkboxes does not render the check area when added inside a Control template

### ISSUE THREAD

**Issue by rodrigovaras** [AvaloniaUI/Avalonia#13835]
using Avalonia 11.05

It seems that the Checkboxes does not render well inside a ControlTemplate definition. I swear this work on previous versions of Avalonia, so I assume is a regression or the way I'm sharing Control templates is wrong and has to be changed.
Here is a trivial XAML that is shows the error. 

<UserControl 
             x:Class="AvaloniaApplication7.Views.MainView"
             x:DataType="vm:MainViewModel">
	<UserControl.Resources>
		<ControlTemplate x:Key="Test">
			<Grid>
				<CheckBox IsChecked="True" Content="One" />
			</Grid>
		</ControlTemplate>

	</UserControl.Resources>
	<StackPanel>
		<CheckBox Content="One" />
		<ContentControl Template="{StaticResource Test}" />
	</StackPanel>
</UserControl>

<img width="424" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/4292977/6f3765a9-1af7-4f58-a1c7-0cc73f977860">

**Comment by timunie** [comment]
Do you maybe mean ContentTemplate? Template is a different thing...

**Comment by rodrigovaras** [comment]
The scenario in my case was to use something like this:
<ControlTemplate x:Key="Test">
	<Grid>
		<CheckBox IsChecked="True" Content="One" />
	</Grid>
</ControlTemplate>

<ContentControl Template="{StaticResource Test}" />

maybe there is a better way to share XAML between different projects but thats the way i was sharing several XAML content.
<StackPanel>
	<CheckBox Content="One" />
	<ContentControl Template="{StaticResource Test}" />
</StackPanel>

I'm sure this worked before.

**Comment by timunie** [comment]
I don't see the usecase tbh. But we had some refractory on ContentPresenter so I wonder if that's due to this. I honestly think that this is not really intended. Better to use Template as content or ContentTemplate. Alternative you can do:

- add styles using classes
- use ControlThemes
- inheit CheckBox or create your custom ContentControl
...

**Comment by rodrigovaras** [comment]
Changing to 'TemplatedControl' fix all the issue i saw with the Checkbox rendering.

**Comment by rodrigovaras** [comment]
Checking again the Avalonia code confirm that TemplatedControl is the parent of the ContentControl and hence there is no reason why the it would be make the Checkbox behave differently. I'm pretty sure there is a regression on the ContentControl.
In my case I'm fine with using TemplatedControl  but i will need to start using the 'Content' property to pass a template binding into my control templates

**Comment by timunie** [comment]
That's by design in 11.0. You are missing the required `PART_ContentPresenter`: 

https://github.com/AvaloniaUI/Avalonia/blob/a02834717ff459100e7902862ab057629a8d4666/src/Avalonia.Controls/ContentControl.cs#L17C70-L17C70

DataTemplate can also have a Key for sharing: 
```xml
<Window.Resources>
    <DataTemplate x:Key="Test" DataType="system:Object">
        <Grid>
            <CheckBox IsChecked="True" Content="{Binding}" />
        </Grid>
    </DataTemplate>
</Window.Resources>

<!-- Usage -->
<ContentControl ContentTemplate="{StaticResource Test}" Contrent="One" />
```
