### ISSUE TITLE
Avalonia nuget site provides an incorrect PackageReference node :)

### ISSUE THREAD

**Issue by lsoft** [AvaloniaUI/Avalonia#13846]
PTAL at https://nuget-feed-all.avaloniaui.net/packages/avalonia/11.1.999-cibuild0042674-beta

![image](https://github.com/AvaloniaUI/Avalonia/assets/5988558/965490a3-c7cf-4e3e-9602-86678032fd8e)

please compare with nuget.org:

![image](https://github.com/AvaloniaUI/Avalonia/assets/5988558/dcadf88b-9871-4809-bb71-57cfc89f2c9b)

:)

**Comment by timunie** [comment]
ahhh the `/` is missing 😄

**Comment by timunie** [comment]
fixed by https://github.com/loic-sharma/BaGet/pull/737 but not yet released by them.
