### ISSUE TITLE
Avalonia MVVM Application crashes on net461

### ISSUE THREAD

**Issue by DarkDaskin** [AvaloniaUI/Avalonia#1384]
Just created an app in Visual Studio with Avalonia MVVM Application template. It runs OK on `netcoreapp2.0` platform, but crashes at startup on `net461` platform:

System.IO.FileNotFoundException: "Could not load file or assembly "System.ComponentModel.Annotations, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or one of its dependencies. The system cannot find the file specified."

**Comment by jkoritzinsky** [comment]
Fixed by #1628.
