### ISSUE TITLE
Implement CornerRadius

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#1385]
Right now it is defined by float type and does not allow setting distinct values for each corner like this:

```xml
<Border CornerRadius="1,2,3,4"/>
```

**Comment by kekekeks** [comment]
The previous attempt to implement this: https://github.com/AvaloniaUI/Avalonia/pull/1281

**Comment by vertexpipeline** [comment]
OK, I'll return to work soon.

**Comment by grokys** [comment]
@vertexpipeline this has now been implemented: https://github.com/AvaloniaUI/Avalonia/pull/1462
