### ISSUE TITLE
Getting tons of AXN0002 error when using source generated MarkupExtensions

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#13862]
## Describe the bug

Avalonia Compiler are throwing many AXN0002 errors when I using the MarkupExtensions from the SourceGenerator:
<img width="901" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/25716486/c623acdf-c894-443a-96f9-3ae7e475968a">
<img width="962" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/25716486/5e63cbd7-9405-4ee2-90b1-b01936f2ff31">

## Environment 

- OS: Windows 11 23H2
- Avalonia-Version: 11.0.6

**Comment by laolarou726** [comment]
Is this caused by the order of the source generator? Because I'm pretty sure the code is right. It will only fail when I introduce the SourceGenerator.

**Comment by maxkatz6** [comment]
I would say, this error is essentially fixed in the master, as our name reference source generator will ignore any XAML type errors, and continue generating properties for named controls.
But yes, it might be the order, if you generator is working after our generator.

XAML compiler, on the other hand, is definitely executed after all of these, as it doesn't use build-in source generation.

**Comment by laolarou726** [comment]
@maxkatz6 @timunie Just created a repro: [https://github.com/laolarou726/SourceGeneratorException](https://github.com/laolarou726/SourceGeneratorException)

**Comment by maxkatz6** [comment]
@laolarou726 double checked and name generator works well on 11.1 nightly.
But there is another issue with your generator - it can't find LauncherX defined anywhere.
After I manually added this class, it worked well.

I am closing this issue, as we can't override order of source generators, and it's not as important with latest nightly, where errors are ignored (and properties are still generated).

**Comment by maxkatz6** [comment]
[LauncherX.SourceGenerator.Shared.zip](https://github.com/AvaloniaUI/Avalonia/files/13608920/LauncherX.SourceGenerator.Shared.zip)
