### ISSUE TITLE
`OpenGlControlBase`: early `RequestNextFrameRendering` call prevents rendering

### ISSUE THREAD

**Issue by Dragorn421** [AvaloniaUI/Avalonia#13879]
## Describe the bug
Calling `RequestNextFrameRendering` "early", before the `OpenGlControlBase` control is initialized enough, prevents the control from drawing. In this case `OnOpenGlInit`, `OnOpenGlRender` are not called

## To Reproduce

1. Clone and build https://github.com/Dragorn421/DragoStuff/tree/e093c2792117264a8581a20a7e2c7feb505c183a
2. Run the executable with argument `RequestNextFrameRenderingNo`.
For example: `./bin/Debug/net6.0/avalonia_gl_minimal RequestNextFrameRenderingNo`.
This makes `RequestNextFrameRendering` *not* be called, to demonstrate correct behavior.
4. Notice the OpenGL control drawing as expected:
![image](https://github.com/AvaloniaUI/Avalonia/assets/5306619/b5e8324d-6016-4e29-a9f7-ef7883cbc0f2)
`OnOpenGlInit` and `OnOpenGlRender` are correctly called:
```
$ ./bin/Debug/net6.0/avalonia_gl_minimal RequestNextFrameRenderingNo
DoRequestNextFrameRendering=False
GL1.OnOpenGlInit
...
GL1.OnOpenGlRender
...
```
5. Run the executable again but now with argument `RequestNextFrameRenderingYes`
This makes `RequestNextFrameRendering` be called "early", before the OpenGL control is initialized enough
7. Notice the OpenGL control "not drawing":
![image](https://github.com/AvaloniaUI/Avalonia/assets/5306619/cdf2f4c2-4c79-4179-9e74-8bc4790dbf10)
And `OnOpenGlInit` and `OnOpenGlRender` are not called:
```
$ ./bin/Debug/net6.0/avalonia_gl_minimal RequestNextFrameRenderingYes
DoRequestNextFrameRendering=True
GL1.RequestNextFrameRendering()
```

Note: of course in this sample code it's stupid to just call `RequestNextFrameRendering` where I do, but in more elaborate applications this can creep in (and did creep in in my case)

## Expected behavior
Calling `RequestNextFrameRendering` at any time, including "early", should not lead to the control never drawing

## Environment

- OS: Kubuntu 23.10 (Linux, X11)
- Avalonia-Version: 11.0.5 (I did not try master but I have reasons to believe this wasn't fixed yet, see below)

## Explanation of bug

I think this is very simply a bug in `OpenGlControlBase.RequestNextFrameRendering`:

https://github.com/AvaloniaUI/Avalonia/blob/release/11.0.5/src/Avalonia.OpenGL/Controls/OpenGlControlBase.cs#L224-L232
```cs
        public void RequestNextFrameRendering()
        {
            if ((_initialization == null || _initialization is { Status: TaskStatus.RanToCompletion }) &&
                !_updateQueued)
            {
                _updateQueued = true;
                _compositor?.RequestCompositionUpdate(_update);
            }
        }
```
When calling early, it will set `_updateQueued` to true even if `_compositor` is null, but then `RequestCompositionUpdate` is not actually called and no update was actually queued.
Then when the control is actually ready to draw, the inner workings of `OpenGlControlBase` call `RequestNextFrameRendering` to start drawing, but the method does nothing since it checks for `_updateQueued` which was previously set to true.

It seems to me that in essence this would be fixed by changing the code in some way like this:
```diff
        public void RequestNextFrameRendering()
        {
            if ((_initialization == null || _initialization is { Status: TaskStatus.RanToCompletion }) &&
-               !_updateQueued)
+               !_updateQueued && _compositor != null)
            {
                _updateQueued = true;
-               _compositor?.RequestCompositionUpdate(_update);
+               _compositor.RequestCompositionUpdate(_update);
            }
        }
```
i.e. only set `_updateQueued` when an update is actually enqueued

In current master `RequestNextFrameRendering` didn't change since 11.0.5 so I have no reason to believe upgrading would fix this:
https://github.com/AvaloniaUI/Avalonia/blob/0a6987b0855bc7cd0b371571bb0234dc779da181/src/Avalonia.OpenGL/Controls/OpenGlControlBase.cs#L225-L233

## Workaround

If anyone is looking for a workaround, I ended up adding a method `RequestNextFrameRenderingIfInitialized`:

```cs
private bool _initialized = false;
public void RequestNextFrameRenderingIfInitialized()
{
    if (_initialized)
        RequestNextFrameRendering();
    // If not initialized yet no need to call RequestNextFrameRendering,
    // OpenGlControlBase will basically do it when it's ready to.
}

protected override void OnOpenGlInit(GlInterface gl)
{
    _initialized = true;
    // ...
}

protected override void OnOpenGlDeinit(GlInterface gl)
{
    _initialized = false;
    // ...
}
```

**Comment by Gillibald** [comment]
@kekekeks
