### ISSUE TITLE
ItemsRepeater is broken when used inside a LayoutTransformControl

### ISSUE THREAD

**Issue by BobLd** [AvaloniaUI/Avalonia#13875]
## Describe the bug
I'm having an issue using the `ItemsRepeater` inside a `LayoutTransformControl`.
I'm using the `LayoutTransformControl` to zoom in and out of the items. It seems that doing so breaks the `ItemsRepeater`. When I zoom out, objects that should be visible are not displayed. When I zoom in and scroll, some items become invisible.

I asked the question on the Avalonia Gitter chat, and another user (Steve) noticed that it also happens with an `ItemsControl` with a `VirtualizingStackPanel` but works as expected without virtualization.

## To Reproduce
I have created a minimal app to reproduce the issue: https://github.com/BobLd/ItemsRepeaterLayoutTransform/tree/master

## Expected behavior
`ItemsRepeater` should still work as exepected even after LayoutTransform is changed.

## Environment 
- OS: Windows 10
- Avalonia-Version: 11.0.6

## Additional context
Might be related to #12432

**Comment by stevemonaco** [comment]
Also happens on nightly (11.1.999-cibuild0042757-beta).

**Comment by BobLd** [comment]
I managed to find a fix for that: putting the `ItemsRepeater` inside a `Grid` fixes the problem I was having with the zooming. I've updated the minimal app to reflect that.

I'm closing the issue as it now works on my side. Thanks @stevemonaco for helping in diagnosing the bug.
