### ISSUE TITLE
SaveFilePickerAsync does not work on Firefox

### ISSUE THREAD

**Issue by aldelaro5** [AvaloniaUI/Avalonia#13876]
## Describe the bug
SaveFilePickerAsync does not work under Firefox while it works under Chrome.

## To Reproduce

1. Open the zipped project I have attached and run it under Chrome
2. Click the button, observe expected behaviors
3. Now shut down the server and this time, run it under firefox
4. Click the button, notice nothing happens
5. After a period of time (seems to be about a minute), observe the console and a new tab opening saying "Page Blocked"

## Expected behavior
To have a download of the file initiating (see the additional info section for why this is expected as opposed to a file save dialog).

## Screenshots
This is the console messages I get:
![Screenshot from 2023-12-07 20-46-03](https://github.com/AvaloniaUI/Avalonia/assets/8932978/958afe05-fa1c-4af7-b57e-9f98abc4f845)

And this is the message I get in that new tab:
![Screenshot from 2023-12-07 20-46-50](https://github.com/AvaloniaUI/Avalonia/assets/8932978/b22ecca9-146e-4062-8193-d79e2711097b)

## Environment 

- OS: `6.6.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 04 Dec 2023 00:29:19 +0000 x86_64 GNU/Linux`
- Avalonia-Version: 11.0.6

## Additional context
I actually reported a similar issue in the past, but I never really checked with a relatively minimal project until now because I had found a workaround back then, details here #11077 . The gist of it is I actually expect a download to initiate because firefox doesn't support the needed api for a regular save file dialog.

However, while #11085 was merged, it doesn't seem to work and the problem is I cannot get any more information on what is happening. I even had an unrelated cast exception that I was never able to see a log on rider on my browser and the same went for chrome too.

So what I sent here is all I got. I think I am missing something because it's a blank project and no exceptions are logged. Still, I am expecting the button in this project to initiate. The following zip is a very minimal project that on my end, reproduces the issue.

[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/13608025/AvaloniaApplication1.zip)

**Comment by maxkatz6** [comment]
![image](https://github.com/AvaloniaUI/Avalonia/assets/3163374/211342e9-4405-490d-9e9b-713b1ef170c3)

**Comment by maxkatz6** [comment]
Most likely you have enabled service worker, but now it's disabled. Please keep it disabled for your app (see BrowserPlatformOptions.RegisterAvaloniaServiceWorker) and unregister service worker from the browser web tools.

**Comment by aldelaro5** [comment]
hmm, well this is confusing.

After unregistering all service workers on the browser and turning that option to false in the code, now it works....

But I still get the page blocked tab. Any way to not get that?

**Comment by aldelaro5** [comment]
@maxkatz6 ^perhaps you can answer the question I had above because it sounds conflicting with the docs that says I should register it to make it work, but disabling it is what makes it work so I am confused.

**Comment by maxkatz6** [comment]
Can you point to these docs?

**Comment by maxkatz6** [comment]
It is a fallback, but not the single one. By default Avalonia will use the same approach, as you did before with `<a>` link. Service worker is supposed to make it more optimal with less RAM consumed while downloading, streaming the file instead of loading everything at once. But well, I guess it also only works on Chrome.
