### ISSUE TITLE
Incorrect text cursor position in TextBox during text input.

### ISSUE THREAD

**Issue by Jackhammer88** [AvaloniaUI/Avalonia#13886]
### Describe the bug
Incorrect text cursor position in TextBox during text input.

### To Reproduce

Select "First1" from a ComboBox.
Enter some text at the end of the "First1" string in the TextBox.
Switch the ComboBox to "First2".
Enter text at the end of the "First2" string in the TextBox.
Observe that upon the first key press, the text cursor takes an incorrect position.
### Expected behavior
The text cursor should maintain the correct position relative to the text input, regardless of ComboBox selection changes.

### Screenshots
https://github.com/AvaloniaUI/Avalonia/assets/19895415/849b4772-43fd-4cc2-a444-f1d86c869b02

### Environment
OS: [Windows 10, Linux]
Avalonia-Version: [11.0.6 and 11.1.999-cibuild0042781-beta]
### Additional context
This issue seems to be related to how the TextBox handles cursor positioning in conjunction with dynamic content changes, possibly linked to the ComboBox selection logic.

The example is here: https://github.com/Jackhammer88/AvaloniaTextBoxTest

**Comment by jp2masa** [comment]
Related? #13648

**Comment by Jackhammer88** [comment]
> Related? #13648

I'm not sure. It doesn't seem to be related.

**Comment by workgroupengineering** [comment]
In Avalonia 11.0.7, the issue does not appear to be present

**Comment by Jackhammer88** [comment]
> In Avalonia 11.0.7, the issue does not appear to be present

It appears in 11.0.7 too. I've just tested it.

**Comment by Jackhammer88** [comment]
It's still actual in 11.0.10.
This code doesn't seem buggy... Why does carret position sets to seventh index in the described scenario, but actually it looks like sixth?
And the most important fact that you don't need to manipulate moreover than in the video. Just edit first textbox, select second item in the combobox, add a char to the first textbox and caret position will look incorrect. 

```csharp
public class MainWindowViewModel : ReactiveObject
{
    public MainWindowViewModel()
    {
        var command = ReactiveCommand.Create(() =>
        {
            Counter++;
        });

        var obs2 = this.WhenAnyValue(vm => vm.SelectedItem)
            .Where(i => i != null)
            .Select(item =>
            {
                return Observable.Merge(
                    item.WhenAnyValue(i => i.FirstName),
                    item.WhenAnyValue(i => i.LastName)
                    );
            })
            .Switch()
            .Select((_, _) => Unit.Default)
            .Throttle(TimeSpan.FromMilliseconds(200))
            .InvokeCommand(command);

        Items = new List<Item>
        {
            new Item { FirstName = "First1", LastName = "Last1" },
            new Item { FirstName = "First2", LastName = "Last2" },
            new Item { FirstName = "First3", LastName = "Last3" },
        };

        SelectedItem = Items.FirstOrDefault();
    }


    private int _counter = 0;
    public int Counter
    {
        get => _counter;
        set => this.RaiseAndSetIfChanged(ref _counter, value);
    }

    public List<Item> Items { get; }


    private Item? _selectedItem;
    public Item? SelectedItem
    {
        get => _selectedItem;
        set => this.RaiseAndSetIfChanged(ref _selectedItem, value);
    }
}

public class Item : ReactiveObject
{
    private string _firstName = "";
    public string FirstName
    {
        get => _firstName;
        set => this.RaiseAndSetIfChanged(ref _firstName, value);
    }

    private string _lastName = "";
    public string LastName
    {
        get => _lastName;
        set => this.RaiseAndSetIfChanged(ref _lastName, value);
    }
}
```
