### ISSUE TITLE
IL2026 & 2104 Trim Warnings

### ISSUE THREAD

**Issue by styris-ame** [AvaloniaUI/Avalonia#13897]
## Describe the bug
Trimming warnings on fresh Avalonia MVVM template.

## List of warnings:

| Code | Description |
|--------|--------|
| IL2026 | Avalonia.Data.Converters.MethodToCommandConverter.CanExecuteChanged: Using member 'Avalonia.Data.Converters.MethodToCommandConverter.CanExecuteChanged.remove' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. BindingExpression and ReflectionBinding heavily use reflection. Consider using CompiledBindings instead. |
| IL2026 | Avalonia.Data.Converters.MethodToCommandConverter.CanExecuteChanged: Using member 'Avalonia.Data.Converters.MethodToCommandConverter.CanExecuteChanged.add' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. BindingExpression and ReflectionBinding heavily use reflection. Consider using CompiledBindings instead. |
| IL2026 | Avalonia.Data.Core.Plugins.ObservableStreamPlugin.ObservableStreamPlugin(): Using member 'Avalonia.Data.Core.Plugins.ObservableStreamPlugin.GetBoxObservable()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. StreamPlugin might require unreferenced code. |
| IL2026 | Avalonia.Data.Core.Plugins.ObservableStreamPlugin.ObservableStreamPlugin(): Using member 'Avalonia.Data.Core.Plugins.ObservableStreamPlugin.GetBoxObservable(Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. StreamPlugin might require unreferenced code. |
| IL2026 | Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForTypeInternal(ComActivationContextInternal*): Using member 'Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForTypeImpl(ComActivationContextInternal*, Boolean)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Built-in COM support is not trim compatible. https://aka.ms/dotnet-illink/com | 
| IL2104 | Assembly 'Avalonia.Controls.DataGrid' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries |
| IL2104 | Assembly 'Avalonia.Diagnostics' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries |
| IL2104 | Assembly 'Avalonia.Win32' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries |
| IL2104 | Assembly 'Microsoft.CodeAnalysis' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries |
| IL2104 | Assembly 'Microsoft.CodeAnalysis.Scripting' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries | 
| IL2104 | Assembly 'ReactiveUI' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries |
| IL2104 | Assembly 'System.Reactive' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries |

## To Reproduce

1. Install Avalonia templates: `dotnet new install Avalonia.Templates`
2. Create a new solution with "Avalonia .NET MVVM App" template
3. Add a Publish to folder deployment configuration with the following configuration:

![rider64_8ocwp0wiV8](https://github.com/AvaloniaUI/Avalonia/assets/123859041/9d4e826d-853e-4f8a-a145-4bb149ca639b)
[A modified csproj](https://youtrack.jetbrains.com/issue/RIDER-103066/Self-Contained-deployment-does-not-work) may also be necessary:
<details><summary>csproj</summary>
<p>

    <PropertyGroup>
        <PublishTrimmed>true</PublishTrimmed>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    </PropertyGroup>

</p>
</details> 
4. Compile the app with that configuration

## Expected behavior
No warnings

## Environment

- OS: Windows 11
- Avalonia-Version: 11.0.6
- IDE: JetBrains Rider
- Template: `Avalonia .NET MVVM App` with .NET 8

## Additional context
Similar to [issue 8925](https://github.com/AvaloniaUI/Avalonia/issues/8925).
Note: `<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>` is in the csproj file.

**Comment by maxkatz6** [comment]
About severity of these problems:

MethodToCommandConverter, ObservableStreamPlugin are not a problem, since these classes are used only if a developer uses ReflectionBinding. With CompiledBindings these classes are not used.

`Built-in COM support` probably mentions [this issue](https://github.com/AvaloniaUI/Avalonia/issues/11767). In short - current accessibility code uses old COM interop which isn't supported with NativeAOT/trimming. That's pretty much the only actual problem with these warnings.

Anything `Avalonia.Diagnostics` related (including `Microsoft.CodeAnalysis`) is expected, as we don't expect Avalonia.Diagnostics project to be used in Release builds. They are not trimming/AOT friendly because of the console feature that requires dynamic code.

**Comment by timunie** [comment]
@styris-ame why exactly do you think it is a bug? I think it is more of a feature request if there is anything you think we are missing. Can you specify what the "bug" for you is?

**Comment by styris-ame** [comment]
@timunie I was going off [issue 8925](https://github.com/AvaloniaUI/Avalonia/issues/8925), which is very similar and is listed as a bug. Also, even if they are just meaningless warnings, I would still consider something like this a slight bug.
Feel free to change it to a feature request if you see fit, or even close it since it has been explained.

**Comment by timunie** [comment]
@styris-ame it's still good to track it 👍

**Comment by alexrp** [comment]
Given that these do not seem to be particularly severe, is there a way to actually suppress them?

**Comment by Tyrrrz** [comment]
As it stands right now, trying to use Avalonia in an application with trimming enabled produces a bunch of errors. I got around it by manually suppressing each error code, but it doesn't feel right. I'm concerned I may be silencing actual errors that might appear in the future. What's the correct solution in this case?

I'm using Avalonia `11.0.10`.

![image](https://github.com/AvaloniaUI/Avalonia/assets/1935960/f195794f-2768-426d-8bc8-c56b418968ae)
