### ISSUE TITLE
Command in Button doesnt work when in code behind

### ISSUE THREAD

**Issue by OceanOC** [AvaloniaUI/Avalonia#13904]
## Describe the bug
When a new button is created in code behind Command = (void function) doesnt work
Error: CS0029 Cannot implicitly convert type 'void' to 'System.Windows.Input.ICommand'

## To Reproduce
Code to reproduce the behavior:

```c#
var button = new Button() { Content = $"Broken :(", Command=Button_Click()};
panel.Children.Add(button);

private void Button_Click()
{
    
}
``` 

## Expected behavior
If clicked it should run the void function like when in XAML

## Environment

- OS: [Windows 11]
- Avalonia-Version: [11.0.6]

_I couldnt find anything about this on Google_

**Comment by maxkatz6** [comment]
We can’t change rules of C# language. 
Command property accepts ICommand interface. If you need to set it from the C# code - you need to implement this interface. XAML compiler makes it automatically, as we control this step. 

But you likely just need `button.Click += EventHandler` which is a plain C# event.
