### ISSUE TITLE
Intermittent COM Exception freezes UI from D3D11: Removing Device.

### ISSUE THREAD

**Issue by tkefauver** [AvaloniaUI/Avalonia#13919]
## Describe the bug
Randomly after a few minutes of running my app, the interface becomes unresponsive with this error:
```
D3D11: Removing Device.
Exception thrown at 0x00007FF9C09C567C in MyApp.exe: Microsoft C++ exception: _com_error at memory location 0x00000031DCB7AC68.
Exception thrown at 0x00007FF9C09C567C in MyApp.exe: Microsoft C++ exception: _com_error at memory location 0x00000031DCB7B410.
Exception thrown at 0x00007FF9C09C567C in MyApp.exe: Microsoft C++ exception: _com_error at memory location 0x00000031DCB7B6B0.
Could not allocate vertices
Exception thrown at 0x00007FF9C09C567C (KernelBase.dll) in MyApp.exe: WinRT originate error - 0x887A0005 : 'The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.'.
onecoreuap\windows\dwm\dcomp\dll\kerneltokenfactory.cpp(90)\dcomp.dll!00007FF9B961B6FA: (caller: 00007FF9B966BECB) ReturnHr(1) tid(5ddc) 887A0005 The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
```
Any help/suggestions/clues to what's going wrong would be much appreciated.

## Environment 

- OS: Windows 11 23H2
- Avalonia-Version: 11.0.5

## Additional context
I've updated Windows and GPU drivers to their latest which is the only suggestions I could find online for `D3D11: Removing Device.`. 

Since its intermittent its hard to isolate what maybe happening but it seems to happen when views are being unloaded but it could be unrelated. It never occurs immediately, usually after a few minutes.

**Comment by timunie** [comment]
@tkefauver try to extract a minimal sample. Also try to upgrade to 11.0.6 or nightly to test more recent Avalonia version

**Comment by tkefauver** [comment]
Ah didn't know about the update, will give that a try. I also enabled dumps cause its a kernel error so maybe I can get more info for a sample.

**Comment by kekekeks** [comment]
Please check if `dxcap -forcetdr` has the same effect

**Comment by tkefauver** [comment]
`dxcap -forcetdr` gives this output (usually multiple times):
```
D3D11: Removing Device.
[Visual]Exception when rendering: 'System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EglContext'.
   at Avalonia.OpenGL.Egl.EglContext.get_Context()
   at Avalonia.Skia.FboSkiaSurface.Dispose()
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #23801339)
```
Not the same error, but I DO also get this one intermittently. Both have the same result, unresponsive UI besides show/hide. 

Only difference is after `dxcap -forcetdr` the window completely disappears, can't show it again.

**Comment by kekekeks** [comment]
Will need a stack trace for the exception with 'GetDeviceRemovedReason' text.

**Comment by tkefauver** [comment]
Ok will do once it happens again.

**Comment by tkefauver** [comment]
Here's the exception's stack trace:
```
System.ObjectDisposedException
  HResult=0x80131622
  Message=Cannot access a disposed object.
Object name: 'EglContext'.
  Source=Avalonia.OpenGL
  StackTrace:
   at Avalonia.OpenGL.Egl.EglContext.get_Context() in /_/src/Avalonia.OpenGL/Egl/EglContext.cs:line 44
```
The console also reported this:
```
D3D11: Removing Device.
Exception thrown: 'Avalonia.Platform.PlatformGraphicsContextLostException' in Avalonia.OpenGL.dll
Exception thrown: 'System.ObjectDisposedException' in Avalonia.OpenGL.dll
Cannot access a disposed object.
```
And this is the full call stack I'm getting:
![egl_stacktrace](https://github.com/AvaloniaUI/Avalonia/assets/134575/4212eb41-6318-42e9-96bb-df1490d101e9)

**Comment by tkefauver** [comment]
Here's a better stack trace I just got, same exception source:
```
   at Avalonia.OpenGL.Egl.EglContext.get_Context() in /_/src/Avalonia.OpenGL/Egl/EglContext.cs:line 44
   at Avalonia.Skia.FboSkiaSurface.Dispose() in /_/src/Skia/Avalonia.Skia/Gpu/OpenGl/FboSkiaSurface.cs:line 103
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render() in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.cs:line 129
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore() in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositor.cs:line 222
```
It would seem this is something similar to [here](https://github.com/AvaloniaUI/Avalonia/issues/8320#issuecomment-1263229155) but that's just a guess.
