### ISSUE TITLE
Quick start link on website is broken.

### ISSUE THREAD

**Issue by tommymh** [AvaloniaUI/Avalonia#1391]
On http://avaloniaui.net/, not the repo.  Its throwing a 404.  Also you might want to consider throwing a SSL cert on the site, Google is going to start flagging non-https sites as insecure in July.  LetsEncrypt is free and easy.

**Comment by ForNeVeR** [comment]
It is already fixed by https://github.com/AvaloniaUI/avaloniaui.net/pull/10 (and the fix will be published soon, I hope).

Valid point regarding HTTPS though.

**Comment by jmacato** [comment]
Already addressed at https://github.com/AvaloniaUI/avaloniaui.net/pull/21
