### ISSUE TITLE
Problem with high DPI screen in Ubuntu

### ISSUE THREAD

**Issue by pozyx** [AvaloniaUI/Avalonia#1392]
Avalonia apps (including sample ControlCatalog) do not respect scaling settings in Ubuntu.

Ubuntu 16.04 with high DPI display with adjusted scaling ("Scale menu and title bars" option in Display settings) has no effect on Avalonia apps, rendering its UI very small on high DPI screens.

**Comment by kekekeks** [comment]
We  are using scaling settings from GTK3. Make sure that [gdk_window_get_scale_factor](https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-get-scale-factor) returns the correct value on your system.

You are probably trying to change global font size from the system settings dialog. It doesn't have anything to do with DPI.

**Comment by pozyx** [comment]
You are right. Most apps respect the setting I was using, but it is not system-wide scaling. I now use the proper way to set scaling and it works as expected.
