### ISSUE TITLE
`BoxShadow` style doesn't trigger redraw on style change

### ISSUE THREAD

**Issue by Al12rs** [AvaloniaUI/Avalonia#13925]
## Describe the bug
Depending on what changes between `:focus` and not `:focus` styles, the style of control that should lose focus isn't updated correctly.

Image shows three buttons where a white `BoxShadow` is applied to `:focus` style. Only one button should be in focus, but pressing the second one didn't remove the `BoxShadow` style from the first one.
![image](https://github.com/AvaloniaUI/Avalonia/assets/26797547/18cd6f6a-16a4-44e8-bed9-6e8394d00ab3)

If I change the `:focus` style to also change the background color of the Button, then the style is updated correctly when changing focus.
If I set the background to the same color as the default state, then the focus state isn't updated, so my guess it that the `BoxShadow` change isn't getting registered as something that needs a redraw of the control for some reason.

## To Reproduce
Sample code:
EDIT: Updated sample
```xml
<Styles xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <Design.PreviewWith>
        <StackPanel Orientation="Vertical" Spacing="4">
            <Button Classes="test"> Button 1 </Button>
            <Button Classes="test"> Button 2 </Button>
        </StackPanel>
    </Design.PreviewWith>

    <Style Selector="Button.test">
        <Style Selector="^ /template/ ContentPresenter#PART_ContentPresenter">
            <Setter Property="BoxShadow" Value="0 0 3 2 Red" />
            <Setter Property="Foreground" Value="Red" />
        </Style>
        <Style Selector="^:focus /template/ ContentPresenter#PART_ContentPresenter">
            <Setter Property="BoxShadow" Value="0 0 3 2 White" />
            <Setter Property="Foreground" Value="Blue" />
        </Style>
    </Style>
</Styles>
```

## Expected behavior
The focus styling should be removed correctly when the focus is changed, without requiring background to be changed as well.

## Environment:

- OS: Windows
- Avalonia-Version: 11.0.5

**Comment by Al12rs** [comment]
> Add a neutral setter for non focused style

I tried that as well with no luck. I think that BoxShadow changes in this case are just getting ignored.

**Comment by Al12rs** [comment]
Another thing, hovering over the item with the leftover :focus styling correctly updates it.
Potentially due to :pointerover styling triggering a redraw.

**Comment by timunie** [comment]
> > Add a neutral setter for non focused style
> 
> I tried that as well with no luck. I think that BoxShadow changes in this case are just getting ignored.
> 

Please update the sample to reflect your neutral setter. Is it only the BoxShadow not updating?

**Comment by timunie** [comment]
Did a simple test and seems to be related to BoxShadow explicitly not triggering the redraw. Using this sample shows that Foreground updates while BoxShadow does not: 

```xml
<Style Selector="Button.Standard">
    <Style Selector="^ /template/ ContentPresenter#PART_ContentPresenter">
        <Setter Property="BoxShadow" Value="0 0 3 2 Red" />
        <Setter Property="Foreground" Value="Red" />
    </Style>
    <Style Selector="^:focus /template/ ContentPresenter#PART_ContentPresenter">
        <Setter Property="BoxShadow" Value="0 0 3 2 White" />
        <Setter Property="Foreground" Value="Blue" />
    </Style>
</Style>
```

![image](https://github.com/AvaloniaUI/Avalonia/assets/47110241/09646a34-351e-45af-98bf-cc1e1e24d8d1)

**Comment by Al12rs** [comment]
Updated the sample and issue title

**Comment by Al12rs** [comment]
Are there any workarounds that I could use that wouldn't involve changing the appearance of the button to trigger a redraw?

**Comment by timunie** [comment]
best bet: 
1. copy that into src/Samples/Sandbox
2. Try to add AffectsRender for BoxShadows
3. Prive a PR if 2) was successful

**Comment by Al12rs** [comment]
I can't seem to build the Avalonia project, apparently missing some dependency (`Error CS0246 : The type or namespace name 'DCOMPOSITION_FRAME_STATISTICS' could not be found (are you missing a using directive or an assembly reference?)`).

Don't want to derail this issue with building problems though. If anyone else is able to try the above out I would be very grateful!

**Comment by timunie** [comment]
read build instructions carefully. Most likely submodule not init correctly

**Comment by Al12rs** [comment]
Fixed the build issue I had, had to install .net framework 2.0. 

Created a PR with the Fix above. I tested it and with the change the BoxShadow now updates correctly.

**Comment by timunie** [comment]
Thank you for your first contribution ❤️. Now it's up to the team to review it, but looks good to me 👍
