### ISSUE TITLE
DataGrid cell double-click to edit not working - Avalonia 11.0.6

### ISSUE THREAD

**Issue by alexandrehtrb** [AvaloniaUI/Avalonia#13928]
With Avalonia 11.0.6, double-click to edit on a DataGrid text cell does not work. The cell does not enter into edition mode.

If Avalonia 11.0.5 is used, everything works as expected.

Tested with Windows 11 and .NET 8.

**Comment by jp2masa** [comment]
Duplicate of #13843?
