### ISSUE TITLE
VSCode extension doesn't recognize my build

### ISSUE THREAD

**Issue by hermitcat** [AvaloniaUI/Avalonia#13949]
## Describe the bug
I've created my project with `dotnet new avalonia.app -o MyApp`
and then I built it with `dotnet build`
but the VSCode extension keeps saying "build your project first" and just not doing any other function

## Environment 

- OS: [Windows]
- Avalonia VSCode extension version 0.0.25

**Comment by timunie** [comment]
it needs a debug build afaik. Please transfer this issue into the VSCode repro. Thx.
