### ISSUE TITLE
Performance of ListBox

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#1394]
It takes ~3 sec. on my machine to load 100 items into ListBox via ReactiveList. UI thread freezes for that time.

How to reproduce:

1) Have a ListBox with binding to a ReactiveList

```xml
<ListBox
    Items="{Binding Items}"
    >
    
    <ListBox.ItemTemplate>
        <DataTemplate>

            <TextBox Text="{Binding Text}" />

        </DataTemplate>
    </ListBox.ItemTemplate>
    
</ListBox>
```

2) Load 100 items into the list

```csharp
public ReactiveList<Item> Items { get; } = new ReactiveList<Item>();

// ...

var items = await Task.Run(() =>
{
    return Enumerable.Range(1, 100)
        .Select(id => new Item
        {
            Text = "Blah blah"
        })
        .ToList();
});

// this causes UI thread hang
using (Items.SuppressChangeNotifications())
{
    Items.AddRange(items);
}
```

**Comment by x2bool** [comment]
Changed the title. Any nontrivial control inside template takes 1+ sec to render for 100 items. Disabling virtualization to get smooth scrolling makes it 100x worse (1-2 min to render).

**Comment by x2bool** [comment]
I discovered that it's the ListBox layout performance. Simple repro:
* Have a Carousel with two children (on of them should be ListBox bound to ReactiveList of 20 items)
* Switch Carousel's SelectedIndex back and forth between 0 and 1

At this point you should observe UI hang when Carousel switched to ListBox control, but no problem when it's switched to a simpler controls like Button for example.

**Comment by x2bool** [comment]
So I've spent some time profiling and measuring things. The main issue is styling: applying selectors for nested elements such as "Panel Button" or "Panel > Button" seems to have exponential growth of layout time depending on the level of nesting. This is a bit unexpected because CSS does not have such problems.

I got rid of such selectors and performance in my case improved. Still there is a noticeable UI freeze, so I'd like to leave this issue opened. Should I open issue about selectors?

**Comment by grokys** [comment]
Hmm interesting. This was actually something I was worried about when implementing the styling system, but I figured that CSS must have the same problem. I can think of several ways to speed this up, but I think we'd need some benchmarks first.

If you could open a new issue for this that would be great!

**Comment by grokys** [comment]
@x2bool is this better after the recent performance improvements? I think I remember you saying it had improved.

**Comment by x2bool** [comment]
Definitely better. Please feel free to close this if it's the same for other people.
