### ISSUE TITLE
Error from Avalonia.Skia

### ISSUE THREAD

**Issue by mail2mhossain** [AvaloniaUI/Avalonia#13985]
Getting following error from Avalonia.Skia:

Unhandled exception at 0x00007FFE6B58F349 (ntdll.dll) in CommChat Calls.exe_231214_085110.dmp: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFE6B5F97F0).

![image](https://github.com/AvaloniaUI/Avalonia/assets/6905164/708477f1-4ff1-4cd7-80aa-c166c71c9f20)

**Comment by timunie** [comment]
@mail2mhossain please fill in out templates and add a minimal repro for us to test. That way, where should we start to debug? Which Avalonia version? Which OS?

**Comment by mail2mhossain** [comment]
OS: Windows, Avalonia Version: 0.10.13

fill in out templates mean?

**Comment by rabbitism** [comment]
![image](https://github.com/AvaloniaUI/Avalonia/assets/14807942/12ce1660-2f73-4665-923d-6beb476d74b7)
This is the template.

**Comment by timunie** [comment]
0.10.13 is pretty outdated. Please update to 0.10.21 at minimum, if not even 11.0.6

Template is when you open a bug report, there is predefined text with info which sou should fill in and not delete.
