### ISSUE TITLE
Suggestion: Can WritableBitmap be renamed to WriteableBitmap

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#1398]
I guess this was a typo at some point.

**Comment by lindexi** [comment]
I think it is may a typo.

**Comment by ForNeVeR** [comment]
Both words do exist, while `writable` seems like a most common one?
- https://en.wiktionary.org/wiki/writable
- https://en.wiktionary.org/wiki/writeable: "Alternative spelling"

**Comment by lindexi** [comment]
@ForNeVeR I think the WriteableBitmap is well for WPF is [WriteableBitmap](https://msdn.microsoft.com/en-us/library/system.windows.media.imaging.writeablebitmap(v=vs.110).aspx )

We can copy the code to Avalonia when we use `WriteableBitmap` but we should change the code when we use `WritableBitmap`

**Comment by ahopper** [comment]
@ForNeVeR it is interesting that writeable appears less common in English but it is certainly more common in xaml frameworks. The avalonia version has caught me out more than once.

**Comment by kekekeks** [comment]
The name was initially chosen to match the WPF's counterpart.

**Comment by lindexi** [comment]
@kekekeks WPF is WriteableBitmap

**Comment by kekekeks** [comment]
Ouch.

**Comment by ahopper** [comment]
Sorry, I should have been clearer in my original post.

**Comment by lindexi** [comment]
233

**Comment by kekekeks** [comment]
It might be a breaking change for https://github.com/VitalElement/CefGlue.Core/blob/cabfb71a1b7cb537fa7f5fa33c73e8bd3daef817/CefGlue.Avalonia/AvaloniaCefBrowser.cs

I don't see other libraries on github that are using it. It might be worth to rename this class early.

@grokys  @jkoritzinsky

**Comment by danwalmsley** [comment]
rename it!

**Comment by grokys** [comment]
Yeah rename it!
