### ISSUE TITLE
Can't bind any value inside a DefaultFocusAdorner FocusAdornerTemplate

### ISSUE THREAD

**Issue by flarive** [AvaloniaUI/Avalonia#13992]
Hello,

I have 3 buttons with 3 differents CornerRadius.

I have created a new theme using ControlThemes.
When i press Tab key, i would like to have a TabNavigation adorner that fit perfectly my buttons with the same CornerRadius as the button.

![1](https://github.com/AvaloniaUI/Avalonia/assets/7724904/dffea0bc-8437-4730-a008-2003d3273530)
![2](https://github.com/AvaloniaUI/Avalonia/assets/7724904/58b1b40d-08cb-4f6f-ba56-9c842c7b26dc)

I have tried to play with AdornerLayer.xaml from my theme, but i can't have any Binding or TemplateBinding working for the Border CornerRadius property :(

```
<ResourceDictionary xmlns="https://github.com/avaloniaui"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

  <ControlTheme x:Key="{x:Type AdornerLayer}" TargetType="AdornerLayer">
    <Setter Property="DefaultFocusAdorner">
      <FocusAdornerTemplate>
        <Border BorderThickness="1" CornerRadius={Binding or TemplateBinding NOT WORKING !!!}
                BorderBrush="Red"
                Margin="0"/>
      </FocusAdornerTemplate>
    </Setter>
  </ControlTheme>
</ResourceDictionary>

```

I have also tried to define a custom AdornerLayer in my Button.xaml theme file but nothing is working, can't set CornerRadius value using a binding coming from Button CornerRadius :(

I have made a sample repro if you could have a look to it...
https://github.com/flarive/FocusAdornerTemplate_No_Binding

Thanks a lot !
Really

Eviral

**Comment by maxkatz6** [comment]
Not sure if TemplateBinding is expected to work there, as it's technically not a normal control template.
Binding, on the other hand, should work, but you need to remember, that Adorner is not a child of the adorned control.

Something like this works:
```xaml
<FocusAdornerTemplate>
  <Border BorderThickness="4"
          CornerRadius="{Binding $self.(AdornerLayer.AdornedElement).(Border.CornerRadius)}"
          BorderBrush="Red"
          Margin="0"/>
</FocusAdornerTemplate>
```

`AdornerLayer.AdornedElement` property is set on the adorner, when it's created and shown.

**Comment by flarive** [comment]
Works perfectly @maxkatz6, thank you soooo much :)
Going to have some nice focus adorner in Neumorphism.Avalonia thanks to you !
