### ISSUE TITLE
DispatcherTimer should inherit IDisposable

### ISSUE THREAD

**Issue by lindexi** [AvaloniaUI/Avalonia#1399]
https://github.com/AvaloniaUI/Avalonia/blob/ec9af9cefaea9e78d5ed012d5523be247fcb291c/src/Avalonia.Base/Threading/DispatcherTimer.cs#L13

As this code that DispatcherTimer is the property `_timer` and it can be disposed in the destructor .

https://github.com/AvaloniaUI/Avalonia/blob/ec9af9cefaea9e78d5ed012d5523be247fcb291c/src/Avalonia.Base/Threading/DispatcherTimer.cs#L58

But it cant be disposed in DispatcherTimer that we should call the Stop to dispose it.

And I find another bug in DispatcherTimer like wpf. If the dever use DispatcherTimer and give the zero interval and dont write the Tick it will use 100% cpu in a thread.

I think it needs to check if the Tick is null and when the Tick is null, it will not really run.

**Comment by kekekeks** [comment]
Dispatcher timers are now tracked by dispatcher rather than the platform code

**Comment by Shadowblitz16** [comment]
@kekekeks please reopen this, your implementation has a memory leak.
```cs
    private double             _animationDuration;
    private  DispatcherTimer?  _animationTimer = null;
    private  DispatcherTimer    AnimationTimer
    {
        get
        {
            if (_animationTimer != null) return _animationTimer;
            
            Console.WriteLine("New Timer!");
            _animationDuration       = FrameSpeed / 60d;
            _animationTimer          = new DispatcherTimer();
            _animationTimer.Interval = TimeSpan.FromSeconds(_animationDuration);
            _animationTimer.Tick    += (s, e) =>
            {
                _animationDuration       = FrameSpeed / 60d;
                _animationTimer.Interval = TimeSpan.FromSeconds(_animationDuration);

                var direction = int.Sign(FrameSpeed);
                    
                FrameIndex = (uint)(int)(FrameIndex + direction);
                if      (direction > 0 && FrameIndex >= FrameCount-1) FrameIndex = 0;
                else if (direction < 0 && FrameIndex ==            0) FrameIndex = FrameCount-1;
                
                Console.WriteLine("Tick Timer!");
            };
            return _animationTimer;
        }
    }
```

When Animation is accessed it creates a new timer but the old one is still running.
