### ISSUE TITLE
SplitButton should have `HotKey` property like Button and DropDownButton

### ISSUE THREAD

**Issue by ionite34** [AvaloniaUI/Avalonia#14002]
## Is your feature request related to a problem? Please describe.
Currently SplitButton is the only Button that does not support the `HotKey` property, and setting the `HotKeyManager.HotKey` attached property does not work when the view is loaded and unloaded (`Button` handles this by resetting the property in `Button.OnAttachedToLogicalTree`)

## Describe the solution you'd like
Copy over the `HotKeyProperty` and `OnAttachedToLogicalTree` handling from `Button` to `SplitButton`, linking the HotKey to the main `SplitButton.Command`

**Comment by timunie** [comment]
Sounds like an oversight to me. A PR is welcome. Use AddOwner when adding the StyledProperty

**Comment by robloo** [comment]
Yea, I missed this with the initial implementation. I'll check WinUI as well but this shouldn't be an issue to add. I'll add it to the list.
