### ISSUE TITLE
Dispatcher's InvokeAsync should check the action is null

### ISSUE THREAD

**Issue by lindexi** [AvaloniaUI/Avalonia#1400]
https://github.com/AvaloniaUI/Avalonia/blob/ec9af9cefaea9e78d5ed012d5523be247fcb291c/src/Avalonia.Base/Threading/Dispatcher.cs#L76

For the user give the null to InvokeAsync, what is his intention?

I think we should check it.

            Contract.Requires<ArgumentNullException>(action != null);

**Comment by kekekeks** [comment]
It's probably better to wait for https://github.com/dotnet/csharplang/blob/master/proposals/nullable-reference-types.md instead of flooding the code base with null reference checks.
