### ISSUE TITLE
DataGridRow uses a different palette

### ISSUE THREAD

**Issue by zavaleriy** [AvaloniaUI/Avalonia#14025]
## Describe the bug
The selected DataGridRow uses the OS theme, not Requested Theme Variant.

## To Reproduce

1. Create a custom color palettes with https://theme.xaml.live
2. Create DataGrid with items
3. Create any switch for a theme

[AvaloniaDataGridBug.zip](https://github.com/AvaloniaUI/Avalonia/files/13759458/AvaloniaDataGridBug.zip)

## Expected behavior
DataGridRow should uses a Requested Theme Variant.

## Screenshots
OS Dark style:
![image](https://github.com/AvaloniaUI/Avalonia/assets/137711511/46869db3-635b-4f35-9b8f-eb4202dc53bb)
![image](https://github.com/AvaloniaUI/Avalonia/assets/137711511/14710725-0aac-49ba-be63-91832ec64e3e)

OS Light style:
![image](https://github.com/AvaloniaUI/Avalonia/assets/137711511/914c7b43-8394-415c-b6d7-25d6a4665125)
![image](https://github.com/AvaloniaUI/Avalonia/assets/137711511/aab25ca0-4117-4882-8e40-f13006e475dd)

## Environment

- OS: Windows 10
- Avalonia-Version: 11.0.6

**Comment by maxkatz6** [comment]
DataGrid uses `AltHigh` color for the headers.
