### ISSUE TITLE
.NET 8 WASM not supporting await in Avalonia

### ISSUE THREAD

**Issue by satial-interfaces** [AvaloniaUI/Avalonia#14022]
## Describe the bug
Using an await call in WASM, .NET 8 and Avalonia doesn't work anymore. The function call never completes. It used to work fine in .NET 7 and Avalonia 11.0.5.

## To Reproduce

1. Create a WASM project using the Avalonia template
2. Update references to .NET 8 and Avalonia 11.0.6
3. Add a button Test in the view, and add the click event
4. Add the following code: 

	async void TestClick(object? sender, RoutedEventArgs e)
	{
		if (sender is not Button button) return;
		button.Content = "Working";
		await Task.Delay(4000);
		button.Content = "Done!";
	}

## Expected behavior
After clicking the button, it first shows "Working" and then after 4 seconds "Done!".

## Environment 

- OS: macOS Sonoma
- Browser: Brave and Chrome
- .NET version: 8
- Avalonia-Version: 11.0.6

**Comment by maxkatz6** [comment]
At first, I thought there could be a problem with our Dispatcher implementation. I.e. task continuation is scheduled as a UI job, but dispatcher never executes it. 

But it looks like issues is somewhere **before** code even reaches dispatcher. And even before SyncContext.

As I reproduced here: https://github.com/AvaloniaUI/Avalonia/tree/wasm-threads
```csharp
    Console.WriteLine("Before 2 {0}", SynchronizationContext.Current?.GetType());
    await Task.Delay(100);
    Console.WriteLine("After 2 {0}", SynchronizationContext.Current?.GetType());
```
`Before 2` is executed. Sync Context has a right type of AvaloniaSynchronizationContext.
But AvaloniaSynchronizationContext.Post/Send are never reached.

Maybe @pavelsavara has some idea what a reason could be, or how we can diagnose this issue. 
Just in case, wasm threads are disabled here.

**Comment by maxkatz6** [comment]
Interestingly, I can't reproduce it with plain net8.0-browser app by creating a custom sync context - it is executed properly.
It's like browser tab main thread is deadlocked, but application itself is fully interactable - input and rendering are not blocked.

**Comment by maxkatz6** [comment]
Changed the title, because it has nothing to do with 11.0.6. 
Previous version simply did not work with .NET 8.

**Comment by pavelsavara** [comment]
Sorry, I don't know Avalonia codebase very well, so just few hints.

I can see in your samples that you use `runMainAndExit`. In Net8 there is change that it will really exit the runtime "process" and it would not execute further events. You could use `runMain` instead or simply never call it and just use all of your `[JSExport]` after `dotnet.create()`

The other option is that C# `public static void Main` could be replaced with `public static Task Main` which never resolves the task and keeps "running".

Please let me know if that didn't help and I will try to reproduce after new year.

In single-threaded build of the runtime, I'm not sure how our "thread pool" interacts with `SynchronizationContext`.
In multi-threaded build, I'm almost sure things are broken in Net8 and I'm working on fixing it for Net9.
Obviously I'm interested to learn about any problems.

**Comment by maxkatz6** [comment]
@pavelsavara oh, now it makes sense. Thank you!

There is no reason for Avalonia to use `runMainAndExit`, and I suppose it was mistakenly misused since very beginning. 
At least it is pretty easy to fix.

> public static Task Main which never resolves the task and keeps "running".

In Avalonia Browser is the only backend that doesn't have even loop on the managed side, and instead it is controlled by the Browser loop itself. So, yeah, we can only fake an infinite Task.

> In multi-threaded build, I'm almost sure things are broken in Net8 and I'm working on fixing it for Net9.

I have just tested WasmEnableThreads=true with Avalonia app. And it works fine with running a while loop with a Thread.Sleep in the task/thread. 
In the future we are planning to integrate Wasm Threads deeper into Avalonia code and use them for background canvas rendering at least.

**Comment by satial-interfaces** [comment]
Yup, but replacing the JavaScript call:

await dotnetRuntime.runMainAndExit(...

with 

await dotnetRuntime.runMain(...

the program can await again.

Thanks for this insight!

**Comment by maxkatz6** [comment]
Instead of changing behavior of `StartBrowserAppAsync` method, I replaced misused method in our templates. In this repo projects will be updated, when we migrate our samples to .NET 8.
https://github.com/AvaloniaUI/avalonia-dotnet-templates/pull/242
