### ISSUE TITLE
Android app crashes in Release build but not Debug

### ISSUE THREAD

**Issue by metal450** [AvaloniaUI/Avalonia#14036]
My app works fine on Windows (both Debug & Release builds), and on Android if it's a Debug build, but crashes immediately upon launch on Android if it's a Release build.

* When I run the Release build from Visual Studio, the Output window shows only `Android application is running (debug is disabled in android project properties)`
* I've tried to "Enable developer instrumentation" in the project settings, but the behavior is the same.
* I've tried to add some logging (to RequestBin) in MainActivity as suggested here: https://stackoverflow.com/questions/49649627/xamarin-app-runs-on-debug-but-crashes-on-release . By doing that, I can see that it's crashing in OnCreate, i.e.:

```
// overriding just so I can log
protected override void OnCreate(Bundle savedInstanceState)
{
   // Log here - reaches RequestBin
   base.OnCreate(savedInstanceState);
   // Log here - doesn't reach RequestBin
}
```

* If I wrap that in a try/catch block, and try to log the caught exception, it doesn't log - so it doesn't seem to be actually throwing an exception.

**Comment by metal450** [comment]
Addendum: 

* Added `android:debuggable="true" ` to the `application` element in AndroidManifest.xml (per [here](https://stackoverflow.com/questions/2409923/what-do-i-have-to-add-to-the-manifest-to-debug-an-android-application-on-an-actu))
* Added all of the following to the Android csproj (per [here](https://stackoverflow.com/questions/34336740/how-can-i-enable-debug-in-android-project-properties-xamarin-android)):

```
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugSymbols>True</DebugSymbols>
	<Debugger>Xamarin</Debugger>
	<DebugType>full</DebugType>
	<DevInstrumentationEnabled>True</DevInstrumentationEnabled>
	<DefineConstants>DEBUG;TRACE</DefineConstants>
	<Optimize>False</Optimize>
  </PropertyGroup>
```

* Cleaned the solution, quit Visual Studio, then built & ran

I'm then able to see a bit more logging - lines before the crash:
```
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=127.0.0.1:8854,server=y,embedding=1,timeout=1703541404
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.CoreLib.dll
[appname] * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:2714, condition `corlib' not met
[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 19105 (appname), pid 19105 (appname)
```

**Comment by metal450** [comment]
Addendum:

* Enabled "Use Fast Deployment" & disabled Trimming, to try to get Release's project settings more similar to Debug's. It worked.
* So I reverted all the other changes, & just isolated Trimming (disabled Trimming on Release build). It also made me disable AOT (Ahead-Of-Time). It worked.

So it seems like Trimming (which I didn't change - was enabled by default) breaks it.

**Comment by thevortexcloud** [comment]
I am not sure what's going on here, but for the record there are uncatchable exceptions in .NET, meaning no matter what you do you will never be able to catch them. They are fairly rare though.

**Comment by timunie** [comment]
Most likely a trimming issue. Make sure to use as less reflection as possible or edit the csproject file to disable AOT and trimming

**Comment by metal450** [comment]
yeah, found the issue as trimming in my last follow-up above

**Comment by timunie** [comment]
@metal450 that means it's by design and should be handled by yours.

**Comment by metal450** [comment]
So as a newcomer, this was super not intuitive & very time-consuming to figure out. Since it sounds like trimming/AOT are optional optimizations, and are known to cause issues, wouldn't it be far better to default to them being disabled, & just have a note in the docs that they can optionally be turned on, with a warning about the potential side-effects? Rather than having them be on by default, possibly breaking apps, & leading to confusion & support tickets? If they're opt-in, they cannot unknowingly break anyone's app.

**Comment by timunie** [comment]
@metal450 not sure here. Either way is nit perfect tbh. I'd like to have better support overall from .NET itself but that is comming slowly.

**Comment by metal450** [comment]
Right, but we have no control over .NET, so what would be wrong with having potentially breaking optimizations be opt-in rather than opt-out?

**Comment by damian-666** [comment]
This happens to nearly everyone wth xaramin and trimming . .  for me i was loading   plugins in dynamically, when  deserializing level files .       a workarounf was  makeing a direct reference to one on the obects in the plugin dll, make cure the caller,  didnt get optimzed out as unused., or the whole dll was trimmed 

but for adoption:

  if you would look at what feature uses corelib or whatever else  is missing, in your case then make a direct or indrect call to it in your program . Is it something that a typical ui component needsd, or an edge caae?  if its a commonly useable ui feature..

if i google  coreclr or corelib and avalonia, it came  up in older versions..so maybe the little workaroud in the frameowrk, , /and or samples or a note,  or  bild warning will  lhelp noobs.

  
     if its off by defuault people might evaluate the baresamples  as bloated and not use avalonia. But  ifs typical use case..then we could stick the workaround in the code,  tag it, as workaround,  revisit ..   
      
     Generally, in .net and  tooling for a smart trimmer that runs your code then makes a call graph for trimming , so could be  a enhancement to devstudio , or  xamarin, etc.   in JIT in net 8  the optimizer does a second compile based on each  user.. thats sort of like this.. and.the AOT run some converage code  , then could talk to the bundler thing..   you can just trim sdk also..
     
     in general.to me seems JIT seems better but you might have to obfuscate if some hack can cost you ..i would not  bother ..
     this casn helpo you decide..
     
     https://www.reddit.com/r/dotnet/comments/zoxhkp/aot_vs_jit_in_net/

**Comment by metal450** [comment]
Right, but again, my point was: if this happens to so many people, it really seems like it should be opt-in rather than opt-out, so the default behavior out of the box is not "the one that's likely to crash." Then just have in the docs "enable this option, but be aware that it might cause x."

**Comment by timunie** [comment]
@metal450 we are not planning to switch that yet as it would be a breaking change. If we feel we have too many support tickets about it for 12.0 release we can rethink that. But for now, templates will stay as they are. AOT has a huge benefit on mobile ans wasm which is worth it. 

And to note, you and other get support for free if we or someone from the community finds time to answer. 

Thanks for your kind understanding

**Comment by metal450** [comment]
>it would be a breaking change. 

Oh really? Assumed it was solely an optimization, so it can only break things when enabled, but not disabled. Just curious, what's the break if it's not enabled?
