### ISSUE TITLE
Xaml previewer doesn't work without a fluent theme in an executable project

### ISSUE THREAD

**Issue by KatterMaw** [AvaloniaUI/Avalonia#14033]
## Describe the bug
I'm creating my own theme (at the moment only a minimal example for tests) based on the Avalonia.Themes.Fluent sources, but the previewer in Rider doesn't display anything, unless you add the Fluent (or perhaps Simple/Material) theme to the executable project, then after the build the previewer works until you remove the Fluent theme and rebuild the project, then the previewer freezes and does not respond to changes. Visual Studio displays an [internal compiler exception](https://gist.github.com/KatterMaw/94a42143b7a167d3b43bc957f3605955) in all axaml files. At the same time, the executable project runs normally and will be displayed in accordance with the control themes present.

## To Reproduce

1. Clone [repro](https://github.com/KatterMaw/PreviewerTest)
2. Build the solution
3. Open ButtonTheme.axaml in Theme project and ensure previewer is empty
4. Go to App.axaml in AvaloniaApp project and uncomment the usage of Fluent theme
5. Build the solution
6. Ensure previewer works in ButtonTheme.axaml and responds to changes

## Expected behavior

The preview is working or showing error message about missing theme resources

## Screenshots

Fluent theme isn't used, previewer is empty and no error messages:
![rider64_Qy2zc17CYn](https://github.com/AvaloniaUI/Avalonia/assets/68691636/af428c04-06fd-44af-8cd9-4438a3ebf059)

Fluent theme is used, previewer works correctly:
![rider64_rZOLTyGoZG](https://github.com/AvaloniaUI/Avalonia/assets/68691636/ad59ce6c-5cef-4263-8d3b-efdcb070c826)

## Environment

- OS: Windows
- Avalonia-Version: 11.0.6

## Additional context
-

**Comment by rabbitism** [comment]
https://github.com/AvaloniaUI/AvaloniaVS/issues/431

same here. And mine also breaks in rider.

**Comment by timunie** [comment]
Maybe the custom theme needs to implement IResourceNode just like the FluentTheme does in order for the previewer to find the needed resources?

**Comment by KatterMaw** [comment]
> Maybe the custom theme needs to implement IResourceNode just like the FluentTheme does in order for the previewer to find the needed resources?

MyTheme.axaml.cs inherits Styles, so it's already implements IResourceNode
![image](https://github.com/AvaloniaUI/Avalonia/assets/68691636/811ab112-5575-49b7-98b8-ee826e39ac06)

**Comment by Shadowblitz16** [comment]
This still doesn't work.

<img width="1896" height="1031" alt="Image" src="https://github.com/user-attachments/assets/3f1f5e4d-860c-4621-a75b-16f73dce99ce" />
