### ISSUE TITLE
Black window screen  windows 7 

### ISSUE THREAD

**Issue by a191046083** [AvaloniaUI/Avalonia#14039]
Hello, I also have three or four users who also encountered this situation, but I checked the code and found that the ClipToBounds and CornerRadius properties mentioned above were not set at the same time. The avalonia 11.0.0 version was used. Their system was windows 7. Adopted RenderingMode = new List < Win32RenderingMode > {Win32RenderingMode. Software} this mode renders them just normal, excuse me this how to program can be perceived, thank you very much! [https://github.com/AvaloniaUI/Avalonia/issues/4486](url)

**Comment by thevortexcloud** [comment]
Windows 7 is not officially supported by Avalonia any more. Have you confirmed that this also happens on Windows 8.1/10/11?

https://docs.avaloniaui.net/docs/faq

**Comment by a191046083** [comment]
Windows 8.1/10/11  No feedback has been received up to now，windows 7 is also mostly fine，Only three or four user feedback，I wonder if you could help me out, see where we can start, and I'll give it a try，Thank you very much @thevortexcloud

**Comment by thevortexcloud** [comment]
If software rendering is working, that probably indicates some sort of driver bug/bug in the hardware rendering path. In which case, using software rendering is a valid work around. You could add some code to your app to detect if it's running on Windows 7 and force the software renderer during boot. But Software rendering does have limitations.

However I assume if someone is running Windows 7 still, their hardware is probably fairly old. So software rendering may be rather slow. 

In any case, if this is a Windows 7 only bug: it likely wont be fixed. Windows 7 is not really supported by anybody anymore (including Microsoft). If you can you should also try to convince your users to upgrade as well.

Beyond that I am not sure what else I can help with here, I am not particularly familiar with how Avalonia's rendering system works.

**Comment by a191046083** [comment]
Thank you very much
