### ISSUE TITLE
On Mac, it should use Xamarin.Mac instead of MonoMac

### ISSUE THREAD

**Issue by migueldeicaza** [AvaloniaUI/Avalonia#1403]
MonoMac was an early version of the Mac bindings, and it predates our understanding of how to properly manage memory in the combined .NET and Objective-C worlds.

Xamarin.Mac is an evolution of MonoMac which benefits from all the investments that we did in memory management and startup for iOS and is actively maintained.

Xamarin.Mac is also fully open source: http://github.com/xamarin/xamarin-macios

**Comment by danwalmsley** [comment]
@kekekeks

**Comment by kekekeks** [comment]
@migueldeicaza Is Xamarin.Mac compatible with .NET Core already? Last time I've asked on gitter, I was told, that Xamarin.Mac requires a set of runtime patches for Mono to work.

**Comment by kekekeks** [comment]
I think another issue was building on Linux and on Windows (without a Mac host). Xamarin.Mac tooling also seems to not be compatible with .NET Core SDK, i. e. one can't just set `TargetFramework` property to `xamarinmac10` and get it working.

**Comment by migueldeicaza** [comment]
It does not.

MonoMac is broken by design, you are free to keep using it, but it will just produce broken applications.

**Comment by kekekeks** [comment]
We could potentially make a separate Xamarin.Mac backend, but the main problem with that is being unable to even build libraries targeting Xamarin.Mac from Windows or Linux.
So having it in the main repo will pretty much force us to use OS X for Avalonia development and greatly limit the amount of people who can contribute.

**Comment by jkoritzinsky** [comment]
We can use https://github.com/onovotny/MSBuildSdkExtras to target Xamarin.Mac from the .NET Core SDK projects.

**Comment by jkoritzinsky** [comment]
Targets have to already be available on the system, so probably not. We could have it conditionally compile only on the windows solution build.

**Comment by kekekeks** [comment]
The problem with Xamarin.Mac is that unlike Xamarin.iOS targets and reference assemblies aren't available even on Windows.

**Comment by jkoritzinsky** [comment]
That's what I thought, but I was told otherwise (or that it's a bug if they aren't available) during my internship.

**Comment by jkoritzinsky** [comment]
The targets are available on my Windows installation at `%VSINSTALLROOT%\MSBuild\Xamarin\Mac`.

**Comment by jmacato** [comment]
Our MonoMac bindings are interfering somehow with VSCode/Omnisharp's Intellisense. Removing it makes the whole repo work in vscode under linux (i tested it with or without mono in the system).

**Comment by kekekeks** [comment]
It works perfectly fine with Rider and Avalon Studio, so it's probably a bug in OmniSharp.

**Comment by migueldeicaza** [comment]
Visual Studio on Windows can open the Xamarin.Mac projects on Windows

It wont run them, but it will build them.

**Comment by kekekeks** [comment]
Closing this since we are now using ObjC++ library as our Mac backend.
