### ISSUE TITLE
Dynamically add a usercontrol to a grid, the control didn't show!

### ISSUE THREAD

**Issue by VeGoPeng** [AvaloniaUI/Avalonia#14034]
this is my usercontrol :
    public class TestControl : TextBox
    {
    }

i added the control to the grid, it didn't appear!
codes:
var ctl = new TestControl();
Grid.SetRow(ctl,0);
Grid.SetColumn(ctl,0);

but if i use textbox,and it appeares in the grid;
var ctl = new TextBox();
Grid.SetRow(ctl,0);
Grid.SetColumn(ctl,0);

is this a bug?

avalonia 11.0.6, .net8

**Comment by timunie** [comment]
It's not a bug. You're most likely missing the needed StyleInclude . If it should look like a TextBox you can also override the StyleKey on your UserControl. 

> Note: If you're unsure it's a bug you can also open a Q&A discussion first.

**Comment by VeGoPeng** [comment]
> It's not a bug. You're most likely missing the needed StyleInclude . If it should look like a TextBox you can also override the StyleKey on your UserControl.
> 
> > Note: If you're unsure it's a bug you can also open a Q&A discussion first.

Thanks.
And any sample codes?

**Comment by timunie** [comment]
Avalonia.Sampels > RatingControl for custom style. 

StyleKeyOverride I have not at hand, sorry. Check intellisense pls

**Comment by VeGoPeng** [comment]
> > It's not a bug. You're most likely missing the needed StyleInclude . If it should look like a TextBox you can also override the StyleKey on your UserControl.
> > > Note: If you're unsure it's a bug you can also open a Q&A discussion first.
> 
> Thanks. And any sample codes?

i got it! thank you very much!
public class TestControl : TextBox
{
protected override Type StyleKeyOverride => typeof(TextBox);
}
