### ISSUE TITLE
Memory leak at Transitions

### ISSUE THREAD

**Issue by AhmedZero** [AvaloniaUI/Avalonia#14042]
## Describe the bug
Memory leak at Transitions, it takes more than 9 GB.
I don't use any transitions.

## To Reproduce
when I leave the program works for a long time without touching it.

## Expected behavior
low memory.

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/26312527/cf31b6f6-d738-47dc-bee8-38577101d8ac)
![image](https://github.com/AvaloniaUI/Avalonia/assets/26312527/bc7cdb8f-9bec-4a70-a5af-98c80c174d3d)

## Environment 

- OS: Windows X64
- Avalonia-Version: 11.0.6

**Comment by timunie** [comment]
Should be fixed by https://github.com/AvaloniaUI/Avalonia/pull/12861 afaik. Please try nightly if that fixes the issue.

**Comment by maxkatz6** [comment]
Yes, it was fixed
