### ISSUE TITLE
App Not Behaving Well in Browser

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#14065]
I'm trying the `MvvmDialogs.Samples.CrossPlatform` project in a Browser in Linux (hadn't tested it before because I was having trouble running it in Linux but now it works).

If I click the button Show Dialog, it navigates to a new window and the Close button brings you back. So far so good.

However,

- The clock in that page isn't counting
- The Show Dialog button remains disabled after navigating back

This is definitely not working.

Am I missing something, or Browser support is just not ready?

**Comment by thevortexcloud** [comment]
I believe you need to use .NET 8 for WASM to work properly. But I am not sure.

**Comment by mysteryx93** [comment]
Samples are updated to .NET 8

**Comment by maxkatz6** [comment]
.NET 7 Browser works too, but for .NET 7 everybody need to make this modification: https://github.com/AvaloniaUI/avalonia-dotnet-templates/pull/242/files

Replace runMainAndExit with runMain

**Comment by maxkatz6** [comment]
> Am I missing something, or Browser support is just not ready?

There is nothing major to add to the browser backend in Avalonia, it is ready. There are some places to improve, but nothing major. WASM support in .NET and browsers in general is not perfect though. 

Do your samples work in AOT? It might be another reason.

**Comment by timunie** [comment]
@mysteryx93 without even seeing a sample or code to reproduce, what should we do? 

Note: make sure to use as less reflection as possible . If you need reflection, make sure the needed members are not trimmed.

**Comment by mysteryx93** [comment]
> .NET 7 Browser works too, but for .NET 7 everybody need to make this modification: https://github.com/AvaloniaUI/avalonia-dotnet-templates/pull/242/files
> 
> Replace runMainAndExit with runMain

Could be just that.

I updated that project to run from a new template; but template was not up-to-date.

Will test later.

**Comment by mysteryx93** [comment]
Ya it was just that. It's working now.

**Comment by maxkatz6** [comment]
Template wasn't yet updated. We found out about this issue last week only.

**Comment by mysteryx93** [comment]
eewwww that was a pretty serious issue to be found that late!
