### ISSUE TITLE
zoom in/out on Avalonia Android

### ISSUE THREAD

**Issue by AbdalaMask** [AvaloniaUI/Avalonia#14066]
how zoom in/out controls  on Avalonia Android

**Comment by thevortexcloud** [comment]
Please:

1. Follow the issue template
2. Describe the actual issue

This sounds more like a question than an issue. In which case it probably belongs in the discussions rather than here. I am not clear if you are trying to scale your UI or you want a pan and zoom style control.

**Comment by timunie** [comment]
If that's related to your question on telegram, then this should be askes at MapsUi and nit Avalonia. The maps control is not provided by us. 

Sidenote: if you contact us in the chat please look at our responses. They are not always live, but would be fair to take a look at least for 24 hours from time to time.

**Comment by timunie** [comment]
As discussed in the chat again, here is a possible solution: https://github.com/wieslawsoltes/PanAndZoom

We will not have it out of the box, so you may need to implement it according to your needs on your own.

**Comment by AbdalaMask** [comment]
not working to Avalonia Android

**Comment by timunie** [comment]
Then open the issue there. Or implement the gesture recognizing by your own. We have no plans to do that for you at the moment.

**Comment by AbdalaMask** [comment]
What are the zoom in and zoom out events in Avalonia Android ?

**Comment by AbdalaMask** [comment]
The feature of zooming in and out is available in uwp

**Comment by AbdalaMask** [comment]
![image](https://github.com/AvaloniaUI/Avalonia/assets/37013638/ea52699a-7cda-4f2e-861c-eef8b1d68997)

**Comment by timunie** [comment]
But not in Avalonia

**Comment by AbdalaMask** [comment]
yas

**Comment by thevortexcloud** [comment]
There are pinch gestures if that's what you want?

https://docs.avaloniaui.net/docs/reference/gestures/pinchgesturerecognizer

**Comment by AbdalaMask** [comment]
Thanks everyone, the problem has been solved
