### ISSUE TITLE
Button aways disabled if there is a command bind to it.

### ISSUE THREAD

**Issue by martinrhan** [AvaloniaUI/Avalonia#14079]
## Describe the bug
I have a button, and a RelayCommand from Community Toolkit. The button is bind to the command. The button is aways disabled even the command is aways executable.
Moreoever, in the dev tool, the UI treeview shows that the button is disabled. But when you goto the list of properties, it is enabled. Changing the enabled property makes no change to its appearance in the applicaiton window.

## To Reproduce
1. Create a new Avalonia C# Project. In the wizard, choose community toolkit.
2. In MainView.xaml, change the Content to 
```
  <Button Content="Button" Command="{Binding Command}"/>
```
3. In MainViewModel.cs, add property
```
public RelayCommand Command = new RelayCommand(() => { });
```
4. Run the app

## Expected behavior
The button should not be disabled.

## Screenshots
![屏幕截图 2024-01-02 222115](https://github.com/AvaloniaUI/Avalonia/assets/53336429/93f8ff98-190f-4855-9af2-6aab372a96e0)
As shown in the image, Command == null and IsEnabled == true

## Envir
- OS: Windows 11 Home 22H2
- Avalonia-Version: 11.0.2

## Additional context
None

**Comment by timunie** [comment]
Any property needs to have a getter at least. Otherwise XAML cannot find it. 

```cs
public RelayCommand Command { get; } = new RelayCommand(() => { });
```

This is by design, so not a bug.
