### ISSUE TITLE
Feature Suggestion: add SelectedValuePath and SelectedValue to DropDown

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#1409]
These are implemented in wpf ComboBox and are quite hard to work around without changing view models when converting from wpf.  I've so far failed to work around it with converters, the ConverterParameter does not appear to support binding so it is hard to pass the value and items collection, the multivalue converter is oneway only.

**Comment by contextfree** [comment]
This is supported by other WPF and WinUI/UWP controls such as ListView as well.

**Comment by maxkatz6** [comment]
Since a newer issue received more feedback, I will close this one as a duplicate - https://github.com/AvaloniaUI/Avalonia/issues/4718
