### ISSUE TITLE
Android/Touch performing a LongPress/Holding on ListBoxItem throws NRE on PointerReleased

### ISSUE THREAD

**Issue by msneijders** [AvaloniaUI/Avalonia#14092]
## Describe the bug
Performing a 'LongPress'/'Holding' gesture on a ListBoxItem using the ControlCatalog.Android project, ListBox page, throws a NullReferenceException in `Avalonia.Input.Gestures.PointerReleased` row 300:

```csharp
i.RaiseEvent(new HoldingRoutedEventArgs(HoldingState.Completed, s_lastPressPoint, s_lastPointer!.Type, e));
```

s_lastPointer is null.

App crashes.

## To Reproduce

1. Go to 'page ListBox of the ControlCatalog app'
2. Tap down and hold on a ListBoxItem
3. Release the tap.

## Expected behavior
No error and no crash.

## Environment 

- OS: Android
- Avalonia-Version: latest master

**Comment by msneijders** [comment]
some logging done:

- s_isHolding is set to true in PointerPressed on Source `ContentPresenter`.

Then two PointerReleased events are received:
- first is on Source `ListBox`. This sets s_lastPointer to null.
- second is on Source `ContentPresenter`. s_isHolding is still true, but s_lastPointer null, throws error.

**Comment by msneijders** [comment]
In my own app I do not get a NRE (do not know why yet). But I am not receiving the 'HoldingState Completed` from inside a ListBoxItem -- as the NRE is at the RaiseEvent Completed call, I am assuming the cause is the same.

**Comment by IanRawley** [comment]
This is probably related to #12883 where the original PointerReleased event is raised again on the host of the ListBoxItem, and is why you see two PointerReleased events.  It's the same event twice.

**Comment by maxkatz6** [comment]
@emmauss
