### ISSUE TITLE
KeyEventArgs.Handled no longer seems to work.

### ISSUE THREAD

**Issue by lassebro** [AvaloniaUI/Avalonia#14108]
After upgrading from Avalonia version 11.0.4 to version 11.0.6, e.Handled = true in the KeyDownEvent of the NumericUpDown no longer seems to work. 

**Expected:**
- Press Key
- e.Handled is set to true in the KeyDown event handler.
- The key is not written. 

**Actual:** 
- e.Handled is true but the char is still written. 

**Code:**
```
void BlockNonNumericInput(object? sender, KeyEventArgs e)
    {
        if (e.KeySymbol == null)
        {
            return;
        }
        
        if(!decimal.TryParse(Volume.Text + e.KeySymbol, out _))
        {
            e.Handled = true;
        }
    }
```

## Environment 

- OS: Mac
- Avalonia-Version: 11.0.6

Thank you for your help.

**Comment by timunie** [comment]
I suggest to use the `TextInputEvent` instead. 

> [!NOTE]
> You need to tunnel the event

```cs
public ContentPage()
{
    InitializeComponent();
    
    NumericUpDown.AddHandler(NumericUpDown.TextInputEvent , Num_OnTextInput, RoutingStrategies.Tunnel); 
}

private void Num_OnTextInput(object? sender, TextInputEventArgs e)
{
    if (e.Text == "x")
    {
        e.Text = "5";
    }
}
```

**Comment by lassebro** [comment]
Hei @timunie. 

Thanks for the tip. I have now converted it to this and it works great.  

I'm still leaving the bug open though, as the e.Handled thing still looks like a bug.

**Comment by maxkatz6** [comment]
It's by design. If TextInput was handled, then KeyDown is not raised - something by design in XAML frameworks. 
It was like this on windows, but not on mac. Now it's consistent.
