### ISSUE TITLE
Change calculation of "forward" flag in VirtualizingCarouselPanel

### ISSUE THREAD

**Issue by LuckyGeorge1975** [AvaloniaUI/Avalonia#14115]
## Current Behaviour
The VirtualizingCarouselPanel currently does not behave like a real carousel when using a PageTransition. In the current implementation the transition is reversed when switching from the last item to the first one and when switching from the first one to the last. I would not expect this kind of behaviour. The transitions should only change when the switching direction is changed.

https://github.com/AvaloniaUI/Avalonia/assets/152692858/21f61e32-edf4-47be-b111-8c00a728275e

## Expected Behaviour
The transitions should behave like in a circular list (as a carousel is round). When the current item is the last item in the list and the next item ist the first item in the list the pagetransition should go forward (and not backward). The same should happen when the current item is the first one and the next item is the last one. In this case the transition should go backward (and not forward).
The user should be able to cycle through the list forward and backward seamlessly.

https://github.com/AvaloniaUI/Avalonia/assets/152692858/11945e16-abd3-471a-bce8-971b6a43b345

## Solution
To achieve this, the `VirtualizingCarouselPanel.ArrangeOverride` method should be as this:

```csharp
protected override Size ArrangeOverride(Size finalSize)
{
    var result = base.ArrangeOverride(finalSize);

    if (_transition is null &&
        _transitionFrom is not null &&
        _realized is { } to &&
        GetTransition() is { } transition)
    {
        _transition = new CancellationTokenSource();

        var forward = (_realizedIndex > _transitionFromIndex) || (_transitionFromIndex == Items.Count - 1 && _realizedIndex == 0);
        forward = forward && !(_transitionFromIndex == 0 && _realizedIndex == Items.Count - 1);
        
        transition.Start(_transitionFrom, to, forward, _transition.Token)
            .ContinueWith(TransitionFinished, TaskScheduler.FromCurrentSynchronizationContext());
    }

    return result;
}
```

**Comment by timunie** [comment]
You seem to have  a fix for it. Would be great to see it as a PR.

**Comment by LuckyGeorge1975** [comment]
I created a Preview-PR. But:
 
1. This my first github PR ever. Hopefully it meets your requirements.
2. This change may break current usages of the carousel control. I think the PR corrects a wrong behaviour but that's only my opinion. It would be great to hear if the core team also sees this as bug or if my expectation of a carousel transitioning behaviour is wrong.
3. When using only 2 items (as in the unit test), the current behaviour is not changed. There is no way to predict the correct transition with only 2 items.

**Comment by timunie** [comment]
> This my first github PR ever. Hopefully it meets your requirements.

cool :-) appreciate it. 

> This change may break current usages of the carousel control. I think the PR corrects a wrong behaviour but that's only my opinion

I see it same as you do, but I'll leave it up to someone else to review. 

> When using only 2 items (as in the unit test), the current behaviour is not changed. There is no way to predict the correct transition with only 2 items.

If you get an okay on the PR in general, the test can be adopted to cover it. 👍
