### ISSUE TITLE
Why is the main window still closed?

### ISSUE THREAD

**Issue by alabohai** [AvaloniaUI/Avalonia#14113]
I want a confirmation window to pop up when I click the close button in the upper right corner of the application. If I click the "yes" button, the application will be closed. If I click the "no" button, the application will not be closed. How can I achieve this?

I tried to implement it through the following code, but when I clicked the "No" button, the application was still closed. Why?

public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        this.DataContext = new MainViewModel();
    }

    private async void Window_Closing(object sender, WindowClosingEventArgs e)
    {
           var result = await MsBox.Avalonia.MessageBoxManager.GetMessageBoxStandard("Quit?", "Are you sure you want to exit the application?",  ButtonEnum.YesNo, MsBox.Avalonia.Enums.Icon.Question).ShowAsync();
            if (result.Equals(ButtonResult.No))
            {
                e.Cancel = true;
                return;
            }
    }
}

I stepped into debugging the code and found that this line of code (e.Cancel = true; ) was executed. Why is the main window still closed?

**Comment by jp2masa** [comment]
You should never create an async event handler (or `async void` method in general).

I think the easiest way to solve this is:

1. Keep a flag `private bool _confirmedClose = false;`
2. In the event handler, if `!_confirmedClose`, then set `e.Cancel = true` and call an async method (without awaiting, the event handler is not async)
    - That async method awaits the dialog and a dispatcher invoke that sets `_confirmedClose = true` if the user clicked "Yes"

This code can also be adjusted to avoid having more than one confirmation dialog open, using a nullable bool, for example.

**Comment by gigiwotou** [comment]
` e.Cancel = true;
    var result = await MsBox.Avalonia.MessageBoxManager.GetMessageBoxStandard("Quit?", "Are you sure you want to exit the application?",  ButtonEnum.YesNo, MsBox.Avalonia.Enums.Icon.Question).ShowAsync();
    if (result.Equals(ButtonResult.Yes))
    {
        base.Close(e);
    }`
