### ISSUE TITLE
ComboBox SelectedIndex does not update from binding ViewModel

### ISSUE THREAD

**Issue by rtazaki** [AvaloniaUI/Avalonia#14112]
## Describe the bug
 - TransitioningContentControl with ViewLocator has successful only SelectedIndex of ComboBox. 
 - (below were not successful)
   - SelectedItem
   - SelectedValue
   - SelectedValueBinding
 - Next, I tried updating the screen by changing the Index from the ViewModel.
 - This challenge was successful and I was able to confirm that the screen was updated. but I noticed that the combobox itself was not updating accordingly.

## To Reproduce
1. git clone https://github.com/rtazaki/ComboboxTransitionIssueTest
1. build and run (.Desktop)
1. ComboBox changed 111 <--> 222 : "One." <---> "Two!"
1. Click on Button (TransitioningContentControl: "One." <---> "Two!")

## Expected behavior
Combobox does changed.

## Environment 

- OS: Windows 10 (maybe 11)
- .NET 8.0 (maybe 7.0)
- Avalonia-Version: 11.0.6
- ReactiveUI.Fody: 19.5.39 (latest)

**Comment by thevortexcloud** [comment]
I am not seeing a combobox anywhere in your code?

**Comment by rtazaki** [comment]
>I am not seeing a combobox anywhere in your code?
MainView.axaml
~~~
    <DockPanel>
        <DockPanel DockPanel.Dock="Top">
            <ComboBox ItemsSource="{Binding PageNames}" SelectedIndex="{Binding PageIndex}">
                <ComboBox.ItemTemplate>
                    <DataTemplate>
                        <TextBlock Text="{Binding Name}" />
                    </DataTemplate>
                </ComboBox.ItemTemplate>
            </ComboBox>
            <Button Command="{Binding TransitionfromViewModel}" Content="ViewModelから遷移したとき、コンボボックスが切り替わらない。(画面遷移自体は成功している。)" />
        </DockPanel>
        <TransitioningContentControl Content="{Binding CurrentPage}" DockPanel.Dock="Top" />
    </DockPanel>
~~~

**Comment by timunie** [comment]
PageIndex is not "Reactive", means it will not notify the UI about changes.

**Comment by rtazaki** [comment]
>PageIndex is not "Reactive", means it will not notify the UI about changes.

I understood. Added RaiseAndSetIfChanged to PageIndex.

**Comment by rtazaki** [comment]
By the way, since this issue wasn't actually an issue, should it be labeled as a "by-design" rather than a bug?
And can the report author simply close this ticket?

**Comment by timunie** [comment]
@rtazaki I can label it by-design, sure. But you as the author are allowed to close the issue 👍 

Also we have a telegram chat and Discussions for questions.
