### ISSUE TITLE
The network request is abnormal in the browser

### ISSUE THREAD

**Issue by 292390450** [AvaloniaUI/Avalonia#14122]
## Describe the bug
A normal http call has no exception and no response in the browser
The previous version seems to work fine, I don't know if it's a problem with the .net runtime
## To Reproduce

Open the page after debugging or publishing

[demo.zip](https://github.com/AvaloniaUI/Avalonia/files/13839729/demo.zip)

## Screenshots

![image](https://github.com/AvaloniaUI/Avalonia/assets/20938585/7c77bca8-17f1-4602-bb00-8ccc74a4f70c)

## Environment 

- OS: [ Windows11]
- Avalonia-Version: [ 11.0.6]
- .net 8

**Comment by 292390450** [comment]
Debugging the Brower project

**Comment by maxkatz6** [comment]
Replace runMainAndExit with runMain in main.js file.

**Comment by maxkatz6** [comment]
@292390450 I ran your code and it works fine.
Changes you might need to consider:
1. Replace runMainAndExit with runMain in main.js file, as I mentioned above.
2. Make Greeting property bindable. https://docs.avaloniaui.net/docs/guides/data-binding/inotifypropertychanged. Right now when you set a value to the property, there is nothing to tell UI that something has changed.

In general, though, be careful with calling Rest APIs from the web, that you don't own. You might have problems with [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), a problem that is specific to the Browser HttpClients.
