### ISSUE TITLE
Controls having their children removed in custom Content Control implementation.

### ISSUE THREAD

**Issue by sirdoombox** [AvaloniaUI/Avalonia#14126]
## Describe the bug
I implemented a custom `TransitioningContentControl` for a UI library as the existing `TransitioningContentControl` within Avalonia was far from smooth, however my implementation is bumping up against a part of Avalonia I either don't fully understand or is some kind of bug.

When I go to use the control (Which is embedded inside another control)
This implementation works as expected - [(Full source here)](https://github.com/sirdoombox/SukiUI/blob/main/SukiUI.Demo/SukiUIDemoView.axaml)
```xaml
<suki:SukiSideMenu ItemsSource="{Binding DemoPages}">
    <suki:SukiSideMenu.ItemTemplate>
        <DataTemplate>
            <suki:SukiSideMenuItem Header="{Binding DisplayName}"/>
        </DataTemplate>
    </suki:SukiSideMenu.ItemTemplate>
<suki:SukiSideMenu/>
```
However the implementation below causes the view to only render on the first time the view is opened, on any subsequent opens the page doesn't render at all, I checked inside the debugger and the view had all it's children stripped away whenever the view was opened again. [(Full source here)](https://github.com/sirdoombox/SukiUI/blob/main/SukiTest/MainWindow.axaml)
```xaml
<!-- SukiSideMenu container here... -->
<suki:SukiSideMenu.Items>
    <suki:SukiSideMenuItem Header="Foo">
        <suki:SukiSideMenuItem.PageContent>
            <sukiTest:FooPage />
        </suki:SukiSideMenuItem.PageContent>
    </suki:SukiSideMenuItem>
</suki:SukiSideMenu.Items>
```
I'm wrapping two `ContentPresenter`s in a single `ControlTemplate` acting as a simple swap buffer for a control that derives from `ContentControl`.
This is the control here - [Source](https://github.com/sirdoombox/SukiUI/blob/main/SukiUI/Controls/SukiTransitioningContentControl.axaml.cs)
The specific method where "Swapping" occurs in the control itself is here - [Source](https://github.com/sirdoombox/SukiUI/blob/main/SukiUI/Controls/SukiTransitioningContentControl.axaml.cs#L135)
Whilst the code that handles swapping the views in and out of that control specifically is within this block here - [Source](https://github.com/sirdoombox/SukiUI/blob/main/SukiUI/Controls/SukiSideMenu.axaml.cs#L98)

## To Reproduce
As this is a fairly complex bug based on a custom implementation there isn't an obvious way for me to provide a simple sample, though I could make a minimal sample if necessary.

However pulling [this fork of the repo](https://github.com/sirdoombox/SukiUI/) and running the `SukiTest` project will demonstrate the bug, whilst running `SukiUI.Demo` will show the control working as intended.

## Expected behavior
Pages correctly switch in and out of the `ContentPresenters` within the `ContentControl` without having their children detached.

## Screenshots
I screen recorded a couple of videos of the control working and not working:
[Video of the control behaving correctly here.](https://dl.dropboxusercontent.com/scl/fi/vvmvj8eiei3b1uqbi15fi/SukiUI.Demo_2024-01-05_14-14-42.webm?rlkey=jlwzhslcsw44ft24m5rtbfslv&dl=0)
[Video of the control behaving incorrectly here.](https://dl.dropboxusercontent.com/scl/fi/ieu1mhvzgmvpuaa71un9x/SukiTest_2024-01-05_14-11-24.webm?rlkey=m7722kp364jbqlfiuwkeu9ze3&dl=0)

## Environment
- OS: Any Desktop.
- Avalonia-Version: 11.0.5

## Additional context
Implementation of this control was necessary as the built in `TransitioningConcentControl` left a lot to be desired, with page transitions being completely hidden by any even moderately complex view hanging the main thread being redrawn.

**Comment by thevortexcloud** [comment]
I am not sure exactly what is going on here, but Avalonia will delete a view if the view is made invisible/no longer active. It will then create a new instance when the reverse happens. It can lead to a loss of state if you are not careful.

**Comment by sirdoombox** [comment]
After some tinkering the lead dev on the project discovered the source of the bug was setting the `Content` property on our type derived from `ContentControl`, if we bypassed that property entirely the control works as expected.

For whatever reason the `Content` property of the base `ContentControl` isn't properly managing the views assigned to it correctly in our case at least.

So for us the fix is to simply use `TemplatedControl` and explicitly call a method to push new content into the control instead.

**Comment by sirdoombox** [comment]
As I've now pushed fixes to this, the code linked in the original issue no longer exists, closing this issue as there is a reasonable workaround.
