### ISSUE TITLE
ScrollViewer swallows PageDown/PageUp with modifiers

### ISSUE THREAD

**Issue by Bip901** [AvaloniaUI/Avalonia#14129]
## Describe the bug
Pressing Ctrl+PageUp/Ctrl+PageDown while a ListBox (i.e. its ScrollViewer) is focused scrolls it instead of bubbling the event upwards.

## To Reproduce

1. Include the following control in a window:
```xml
<ListBox Height="90">
	<ListBoxItem>Test1</ListBoxItem>
	<ListBoxItem>Test2</ListBoxItem>
	<ListBoxItem>Test3</ListBoxItem>
	<ListBoxItem>Test4</ListBoxItem>
	<ListBoxItem>Test5</ListBoxItem>
</ListBox>
```
2. Include the following code in the parent window:

```csharp
    protected override void OnKeyDown(KeyEventArgs e)
    {
        Debug.WriteLine("Got OnKeyDown!");
        base.OnKeyDown(e);
        if (e.KeyModifiers == KeyModifiers.Control && (e.PhysicalKey == PhysicalKey.PageUp || e.PhysicalKey == PhysicalKey.PageDown))
        {
            Debug.WriteLine("Got PageDown/PageUp!");
    }
```
3. Run the app, focusing on the ListBox (by pressing Tab) then pressing Ctrl+PageDown
4. Observe that none of the debug logs are written, and instead the listbox is scrolled

## Expected behavior

The keypress event bubbles up to the window.

## Environment

- OS: Windows (probably applies globally though)
- Avalonia-Version: 11.0.6

## Additional context
Ctrl+PageUp and Ctrl+PageDown are common key bindings for switching between tabs. I want to bind to these keys in my app, but if a listbox is focused they're being swallowed.

**Comment by maxkatz6** [comment]
ListBox handles these keys **before** you. That's expected.
If you need to handle them before ListBox, you need to use Tunnel handling strategy.
`listBox.AddHandler(KeyDownEvent, KeyDownHandler, Tunnel)`

https://docs.avaloniaui.net/docs/concepts/input/routed-events
https://docs.avaloniaui.net/docs/guides/implementation-guides/developer-tools#events
