### ISSUE TITLE
DataGridColumn `ReadOnly` property default is true

### ISSUE THREAD

**Issue by dameng324** [AvaloniaUI/Avalonia#14127]
## Describe the bug
I set a ObservableCollection<T> to DataGrid.ItemsSource, the datagrid is readonly by default. and I set DataGrid.IsReadOnly=false, It still readonly. I cannot edit the cell. Only if I set every column's IsReadonly =false, It will be editable.

## To Reproduce
reproduce code here:
https://github.com/dameng324/AvaloniaDataGridDemo/tree/datagrid_readonly_by_default

if I change 

```
<DataGridTextColumn  Header="Int32" x:DataType="controls:TestModel" Binding="{Binding Int32Field}" />
```

```
<DataGridTextColumn IsReadOnly="False"  Header="Int32" x:DataType="controls:TestModel" Binding="{Binding Int32Field}" />
```

It will editable.

## Expected behavior
The IsReadOnly Property default value should be false.

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.6

## Additional context

I dive into this problem and I found:
`DataGridCollectionView` IList.IsReadOnly is true 
https://github.com/AvaloniaUI/Avalonia/blob/4a30a546fa17c95a06ec0da76c0b67707088a986/src/Avalonia.Controls.DataGrid/Collections/DataGridCollectionView.cs#L1157C39-L1157C39

lead to 
`DataGridDataConnection.AllowEdit` is false

so the default value is false.

**Comment by dameng324** [comment]
I see the `master` branch has a fix of `DataGridCollectionView IList.IsReadOnly`.

Already fixed this issue?

**Comment by thevortexcloud** [comment]
You can try the latest nightly: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

**Comment by dameng324** [comment]
@thevortexcloud Yes, It's fixed. Thanks.
