### ISSUE TITLE
DataGrid's bounding container does not expand to container size before enabling row scroll bar 

### ISSUE THREAD

**Issue by KentSwan** [AvaloniaUI/Avalonia#14120]
## Describe the bug
I have a view window The Window Width="1000" and a Height="800" with a Grid a the content container. The grid is divided into 2 columns using width="*" to divide the bounding container in half.  A DataGrids "DG1" is installed in the Left grid column and a second DataGrid is installed in the right grid column.  Each of the data grids is sourced from a ViewModel public ObservableCollection's having sample data.  On view initialization Both data grids are expanded and visibly show the complete content of each of their bound collections.  When I select a row from the left data grid the SelectionChanged event fires in the code behind which then adds that item to the right data grid.   When I unselect a row in the left data grid it removes the copy of that row from the right-hand data grid.

Problem.  When I select items in the left data-grid, I add copies of the selected items to the right-hand data grid. As soon as I add the first one, a vertical scroll bar appears in the right data-grid container rather than expanding the data-grid container vertically.  If I move the scroll bar I can cause the right-hand data-grid container to expand vertically to show all added rows but the vertical scroll bar remains enabled enabled.    
      
Once moving the right-hand data-grid scroll-bar shows all of the rows deselecting items in the left-data grid deletes the matching item from the right-hand data-grid AND its containing envelope gets smaller but the scroll bar remains enabled. 

## To Reproduce
See above. I can upload a test app to demonstrate but I'd have to strip it out of where it is.  Instead what I need to know is whether I'm missing something unobvious about how to set up a DataGrid such that the bounding rectangle to the Height attribute of the DataGrid self-container works automagically when adding and deleting items.

## Expected behavior
I expected the data-grid row view container to expand to fit the space that the data-grid background limits (eg as defined by the data-grid background color(as it would be for a fixed height data-grid size).  I would then expect additional data-grid rows would continue filling the row view container even after it grows larger than the data-grid's background container.  Only when that occurs should the vertical scroll bar appear.  When deleting items from a data-grid the reverse occurs with the row view container shrinking vertically and, when the row container is less than the vertical size of the background container, the scroll bar auto disables if automatic.  

Whether enabled or auto-enabled, the scroll bar should extend the full length of the data grid background container, not the row view container to be consistent with the concept that ScrollBars only appear when the content size exceeds the size of the view container the control is in.

## Screenshots
See added screenshot.

## Environment 

Windows 10, VS2022, Avalonia 11.06,  SimpleTheme.

## Additional context
![AvaloniaDataGridScrollExpandIssue](https://github.com/AvaloniaUI/Avalonia/assets/7853729/05159c22-1472-4253-be5a-7ac2eae5fd3d)

**Comment by timunie** [comment]
Looks like an additional StackPanel around the DataGrid. That will break the AcrollViewer. If I'm wrong please file a minimum sample

**Comment by KentSwan** [comment]
Concur that there is likely a panel nesting error in the intrinsic layering of the control system. It will take me a day or so to break this out into something that I can verify shows the problem and get it submitted.

**Comment by KentSwan** [comment]
It took less time than I thought.   Unzipl, Select the sln file, Compile and run.  Click on the tab for the test code then follow the instructions above the data grid displays. 

Note: I started this particular test tab to experiment on how to Style a DataGrid after extracting properties from the DataGrid's 


Environment: 

Windows 10 (up to date), 
VS2022 (Up to date),  
Avalonia 11.06 using that releases DataGrid (Did not newget load Avalonia Datagrid)
Simple theme.  (You can switch to FluentTheme in App.axaml)
CommunityToolkit.Mvvm (using the attributed code generators)

[AvaloniaDataGridErrorExample 2024-01-04.zip](https://github.com/AvaloniaUI/Avalonia/files/13839010/AvaloniaDataGridErrorExample.2024-01-04.zip)

**Comment by timunie** [comment]
DataGrid itself is located in a StackPanel, which makes it grow infinite and thus the internal ScrollViewer cannot work as intended. Replate the StackPanel by DockPanel or Grid and your issue should be solved. 

```xml
<DockPanel Grid.Column="1" Grid.Row="1"
	Classes="stkp1"
	>
<TextBlock	Text="Selected Items"
		HorizontalAlignment="Center"
		DockPanel.Dock="Top"
		FontWeight="Bold"
		FontSize="20"
				/>
<DataGrid	Name="DGPS"
			VerticalAlignment="Stretch"
			ItemsSource="{Binding SelectedPersonsCollection}"
			AutoGenerateColumns="True"
			/>
</DockPanel>
```

Nice looking UI btw.

**Comment by KentSwan** [comment]
Thanks for the cudos on UI but the view in this Tab is just a playground to test out certain styling and resolve some MVVM data and event management issues and ideas. 

The real question is why the DataGrid even has a built-in ScrollViewer because the control would normally be placed in a cell wrapped with an external Scrollviewer to handle the case where the render panel is larger than the current cell size as the cell or container size should ALWAYS determine when the scroll bar needs to activate.  This makes a DataGrid, Grid cell compliant.  As it is now the internal scroll viewer works wrong and cannot disabled because, AFIK, none of the configuration properties are exposed.  

Next, relates to UI design.  Placing controls in a Grid Cell is a completely normal approach to designing an elastic UI view layout and, as such, is deterministically controllable. Dockable MVVM views give us a wonderful UI capability and are highly useful. On the other hand, it is an entirely different UI layout concept and, unless I don't understand your workaround, is not suitable as a replacement for dynamically sized rendering panels of item lists, textboxes, text blocks and canvas controls that are scrollviewr compliant content for a grid cell.

Given the above soapbox diatribe, I think I need to look to pull a copy of DataGrid into this test app to gain a better understanding of the flaws I'm tripping over in its layout and what needs to be done to retain the internal scroll functionality...Any pointers would be helpful though I will try the Dock approach if you can explain how it fits into my grid layout.
