### ISSUE TITLE
When interacting with the Combobox in Datagrid under certain conditions, an error occurs and the program exits.

### ISSUE THREAD

**Issue by IronEaterBeast** [AvaloniaUI/Avalonia#14136]
## Describe the bug
An anchor control must be a visual descendent of the ScrollContentPresenter

## To Reproduce
1. Put two columns in the Datagrid, one is DataGridTextColumn and the other is Combobox. 
2. After selecting an item in Combobox, sorting is performed on the DataGridTextColumn to change the order of rows. 
3. Then clicking the Combobox causes the program to terminate with an error message: 'An anchor control must be a visual descendent of the ScrollContentPresenter'

## Screenshots
1.
![1](https://github.com/AvaloniaUI/Avalonia/assets/9688223/5c4f5e22-03e3-4561-8431-24c157e6eb47)
2.
![2](https://github.com/AvaloniaUI/Avalonia/assets/9688223/300833f3-203a-4e18-beb2-66dad219b5c9)
3.
![3](https://github.com/AvaloniaUI/Avalonia/assets/9688223/3523fd34-ca2a-4b83-8e0d-b45dec93a270)
4.
![4](https://github.com/AvaloniaUI/Avalonia/assets/9688223/252904e2-bcd1-49a1-bda5-a51cffe40374)

## Environment 

- OS: Windows 10
- Avalonia-Version: 11.0.5

## My Code:

<DataGrid AutoGenerateColumns="False" CanUserReorderColumns="False" CanUserResizeColumns="True" CanUserSortColumns="True" Grid.Row="1" Height="200" GridLinesVisibility="All" BorderThickness="1" Margin="10"><DataGrid.Columns>

		<DataGridTextColumn Width="*" Header="name" Binding="{Binding name}" CanUserSort="True" IsReadOnly="True" />

		<DataGridTemplateColumn Width="0.9*" Header="To Category" CanUserSort="False">

			<DataGridTemplateColumn.CellTemplate>

				<DataTemplate>

					<ComboBox ItemsSource="{Binding category}" SelectedItem="{Binding SelectedItem}" x:DataType="local:InfoModel" HorizontalAlignment="Stretch" VerticalAlignment="Center"/>

				</DataTemplate>

			</DataGridTemplateColumn.CellTemplate>

		</DataGridTemplateColumn>

	</DataGrid.Columns></DataGrid>

**Comment by timunie** [comment]
Please upload a minimum sample. I've used similar before without an issue.

**Comment by IronEaterBeast** [comment]
> Please upload a minimum sample. I've used similar before without an issue.

Please don't forget to select different items in the Combobox before clicking on the sorting button.

[DatagridErrorSample.zip](https://github.com/AvaloniaUI/Avalonia/files/13857810/DatagridErrorSample.zip)

**Comment by timunie** [comment]
@IronEaterBeast you use `ComboBoxItem` in your model, which is an UI class. That is not intended. Use `string` instead or create a model for `Category`

```cs
    public class TestModel
    {
        public string Name { get; set; } = "";
        public List<string>? ComboBoxItemsList { get; set; }
        public string SelectedItem { get; set; } = "";
    }

// Inside your constructor:

            var newData = new TestModel
            {
                Name = "row1",
                ComboBoxItemsList = new (){"1", "2"},
            };

            TestModelOC.Add(newData);

            var newData2 = new TestModel
            {
                Name = "row2",
                ComboBoxItemsList = new (){"3", "4"},
            };

            TestModelOC.Add(newData2);
```

**Comment by IronEaterBeast** [comment]
Use List<string> that only sets the Content of one ComboBoxItem, how can I set the tag value (value of ComboBoxItem)?

**Comment by timunie** [comment]
Why would you need to? Doesn't make much sense to me. However, a Style may solve it which binds to $self.Content

**Comment by IronEaterBeast** [comment]
Sometimes two options may have the same content, just like the "History" in my picture, they may have different parents.

![171135](https://github.com/AvaloniaUI/Avalonia/assets/9688223/70d80cc5-bccc-41c0-b8be-e6f291056e89)

**Comment by timunie** [comment]
the great thing if you use the MVVM approach, that is no issue. Binding will take care of it.

**Comment by IronEaterBeast** [comment]
@timunie  Yes, now I wish I had used MVVM from the beginning, but most of my project has already been developed. 

Is there a way to use MVVM only in a newly added window while keeping the rest unchanged?

**Comment by timunie** [comment]
Sure. Also you can start adding the pattern partially. Check Avalonia.Samples for general tutorials.

**Comment by IronEaterBeast** [comment]
Which part of Avalonia.Samples demonstrates how to use MVVM in a newly added window in a non-MVVM project? There seems to be a lot of content, which part should I study directly?

**Comment by timunie** [comment]
@IronEaterBeast The MVVM samples in general. I have no sample showing your exact use case
