### ISSUE TITLE
Is there any cross platform web view supported by Avalonia ?

### ISSUE THREAD

**Issue by Amine-Smahi** [AvaloniaUI/Avalonia#14135]
Hi Avalonia team,

Is there any cross platform web view supported by Avalonia ?

My goal is to display my web app that has a transparent background on an Avalonia shell window to give my app a mica look,

But was hard to find any webview that is cross platform and supports transparent background

**Comment by timunie** [comment]
Please use Discussion or Telegram for questions, not an issue. Thx.

In general, we don't have a WebView that works for all platforms. You can check Awsome-Avalonia for available ones. Also there was a paid product iirc.

**Comment by maxkatz6** [comment]
> My goal is to display my web app that has a transparent background on an Avalonia shell window to give my app a mica look,

That’s a very difficult task in cross-platform development.

**Comment by ravikumarchopra** [comment]
try https://github.com/sakib1361/Avalonia.WebView2
