### ISSUE TITLE
Exceptions are being lost at InpcPropertyAccessorPlugin.SendCurrentValue

### ISSUE THREAD

**Issue by jinek** [AvaloniaUI/Avalonia#14137]
Current implementation of InpcPropertyAccessorPlugin swallows all the exceptions:
https://github.com/AvaloniaUI/Avalonia/blob/38e839997d2c204548e6fad396c178780a010cb1/src/Avalonia.Base/Data/Core/Plugins/InpcPropertyAccessorPlugin.cs#L180
Probably no need to elaborate the outcome of an application silently resuming after a failure? In best case it's just difficult to spot and debug.

In my case stacktrace is about 'property changed' -> 'ui updates' -> 'binding reads a value' -> 'exception happens' -> 'exception lost':
![image](https://github.com/AvaloniaUI/Avalonia/assets/10516222/466f8007-84d7-467a-abde-2dbe3840707c)

I think this catch can be just removed? not sure what it is supposed to do besides hiding bugs.

Just as an idea, may be, an analyzer of [ca1031](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1031) can be introduced into the project to prevent such issues in the future?

**Comment by jinek** [comment]
Is workaround possible here? Can the plugin be replaced?

**Comment by timunie** [comment]
There's a draft PR to improve the binding system. Can you probably test it's preview package with your usecase and feedback if it works better for you? https://github.com/AvaloniaUI/Avalonia/pull/13970#issuecomment-1878906233

**Comment by maxkatz6** [comment]
It is by design, as with InpcPropertyAccessorPlugin enabled developer can throw validation exception from properties, which shouldn't break the app, but instead should populate visual Control with the error state (normally, using DataValidationErrors control, that is integrated into most controls).
And InpcPropertyAccessorPlugin is enabled by default, and can be disabled as you did, or just removed from the list.

**Comment by jinek** [comment]
> There's a draft PR to improve the binding system. Can you probably test it's preview package with your usecase and feedback if it works better for you? [#13970 (comment)](https://github.com/AvaloniaUI/Avalonia/pull/13970#issuecomment-1878906233)

Thank you. Will take time to check.

**Comment by jinek** [comment]
> It is by design, as with InpcPropertyAccessorPlugin enabled developer can throw validation exception from properties, which shouldn't break the app, but instead should populate visual Control with the error state (normally, using DataValidationErrors control, that is integrated into most controls). And InpcPropertyAccessorPlugin is enabled by default, and can be disabled as you did, or just removed from the list.

But it catches not only validation exceptions, but all exceptions like OutOfMemoryException for instance.

**Comment by maxkatz6** [comment]
You can use any kind of exception for validation purposes. And OutOfMemoryException cannot be caught as well as StackOverflowException.

**Comment by jinek** [comment]
> You can use any kind of exception for validation purposes. And OutOfMemoryException cannot be caught as well as StackOverflowException, that's a platform/.NET limitation.

OOM was always possible to catch, you can try yourself:

```
try
{
    _ = new byte[int.MaxValue];
}
catch (OutOfMemoryException)
{
    Console.WriteLine("OOM Exception");
}

Console.WriteLine("Hello, World after OOM!");
```

OOM sure has different behavior on different versions of linux, but in general it can be raised and caught, especially on windows.
Besides OOM there are number of exceptions which are generated by platform, like FileLoadException on dll failure or TypeInitializationException. It just looks strange that all of this are considered as validation errors.
