### ISSUE TITLE
Border inside Window makes Window immobile and override Window colour

### ISSUE THREAD

**Issue by Wowhere** [AvaloniaUI/Avalonia#14158]
## Describe the bug
Border makes Window immobile

## To Reproduce
Create an application with Border like this:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:voicio.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="600" Width="800" Height="600" MinWidth="800" MinHeight="240"
        x:Class="voicio.Views.MainWindow"
        x:DataType="vm:MainWindowViewModel"
		Name="HintWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="voicio"
		Background="#121212"
        Topmost="{Binding IsPinnedWindow}"
		WindowStartupLocation="CenterScreen"
		ExtendClientAreaToDecorationsHint="True"
		ExtendClientAreaTitleBarHeightHint="-1"
		>
	<Design.DataContext>
		<vm:MainWindowViewModel/>
	</Design.DataContext>
	<Border BorderThickness="1" Background="Red" CornerRadius="2" IsVisible="True">
	</Border>
</Window>
```
2. Build it and run

## Expected behavior
Window with border will appear
[avalonia_log.txt](https://github.com/AvaloniaUI/Avalonia/files/13879070/avalonia_log.txt)

In fact colour of border used as background colour for whole window and window is immobile (can`t move it)

## Screenshots
![изображение](https://github.com/AvaloniaUI/Avalonia/assets/69252550/710d1f69-7473-4ac1-a305-d5012f446fb2)

- OS: Windows 10
- Avalonia-Version: 11.0.2

**Comment by timunie** [comment]
Set HitTestVisible to False on the border. Otherwise it will eat up the pointer which is by design.

**Comment by Wowhere** [comment]
Thanks, it helped. Also i forgot that i must use BorderBrush instead of Background.
