### ISSUE TITLE
Focusing an element from code doesn't set focused visual style

### ISSUE THREAD

**Issue by JosefNemec** [AvaloniaUI/Avalonia#14164]
## Describe the bug
When using `Focus()` from code behind to focus an element, element is focused (can confirm by keyboard navigation and Focus method returning `true` as well) but element's visual style doesn't get focused style.

## To Reproduce

1) Create desktop project using VS template
2) Add this to MainView.axaml's content:

```xml
  <ItemsControl HorizontalAlignment="Right">
    <ItemsControl.ItemsPanel>
      <ItemsPanelTemplate>
        <StackPanel Orientation="Horizontal" />
      </ItemsPanelTemplate>
    </ItemsControl.ItemsPanel>

    <Button Content="Yes" Name="ButtonYes" />
    <Button Content="No" Name="ButtonNo" />
    <Button Content="Cancel" Name="ButtonCancel" />
  </ItemsControl>
```

3) Set focus from code behind in MainView.axaml.cs:

```csharp
public partial class MainView : UserControl
{
    public MainView()
    {
        InitializeComponent();
        ButtonNo.AttachedToVisualTree += ButtonNo_AttachedToVisualTree;
    }

    private void ButtonNo_AttachedToVisualTree(object? sender, Avalonia.VisualTreeAttachmentEventArgs e)
    {
        ButtonNo.Focus();
    }
}
```

4) Use right or left keys to navigate. Yes and Cancel buttons will receive focus accordingly navigating from focused No button, but initial state of No button visually stays unfocused.

## Expected behavior
Focused element should get focused visual style.

## Screenshots

Current behavior:
![image](https://github.com/AvaloniaUI/Avalonia/assets/3874087/553a10cd-18de-4ff7-bc6a-c3b926b42a51)

Excepted state:

![image](https://github.com/AvaloniaUI/Avalonia/assets/3874087/694c186f-6885-49b7-8ab4-07e9667d2fe6)

## Environment 

- OS: Windows 10 19045
- Avalonia-Version: 11.0.6

**Comment by maxkatz6** [comment]
It’s not a bug. Only keyboard focus sets visual style on the control. The same way as pointer focus doesn’t add borders to every button. 

You can specify focus kind with a parameter in Focus method.
