### ISSUE TITLE
Missing InheritDataTypeFromItemsAttribute on AutoCompleteBox.ValueMemberBinding

### ISSUE THREAD

**Issue by gehongyan** [AvaloniaUI/Avalonia#14161]
## Describe the bug
The `ValueMemberBinding` property on the `AutoCompleteBox` is missing the `InheritDataTypeFromItemsAttribute`. This results in the need for an explicit declaration of the generic type of the `ItemsSource` collection in the compiled binding expression for that property.

See: [AutoCompleteBox.ValueMemberBinding](https://github.com/AvaloniaUI/Avalonia/blob/0e014f9cb627d99fb4e1afa389b4c073c836e9b6/src/Avalonia.Controls/AutoCompleteBox/AutoCompleteBox.Properties.cs#L280-L300)

## To Reproduce

1. Declares a struct
```csharp
public struct Resolution
{
    public Resolution(int width, int height)
    {
        Width = width;
        Height = height;
    }
    public int Width { get; set; }
    public int Height { get; set; }
}
```

2. Declares a property in ViewModel
```csharp
public ObservableCollection<Resolution> AvailableResolutions { get; } = new(
[
    new Resolution(2560, 1440),
    new Resolution(1920, 1080),
    new Resolution(1280, 720),
    new Resolution(1024, 768)
]);
```

3. Bind the property in View
```xaml
<!-- Make sure the compiled binding feature is enabled. -->
<AutoCompleteBox ItemsSource="{Binding AvailableResolutions}"
                 ValueMemberBinding="{Binding Width}"/>
```

4. Compile the project
The compiler complains, "Unable to resolve property or method of name 'Width' on type 'Sandbox.MainWindowViewModel.'"

![image](https://github.com/AvaloniaUI/Avalonia/assets/21241496/ec0cafcf-92ac-47d6-ad02-19a60d169ac8)

5. Current workaround
Declares the property type in the binding expression
```xaml
<!-- Add namespace alias xmlns:sandbox="clr-namespace:Sandbox" -->
<!-- Make sure the compiled binding feature is enabled. -->
<AutoCompleteBox ItemsSource="{Binding AvailableResolutions}"
                 ValueMemberBinding="{Binding (sandbox:Resolution).Width}"/>
```

## Expected behavior
Similar to the `DisplayMemberBinding` property on `ItemsControl`, the type of `ValueMemberBinding` on `AutoCompleteBox` typically comes from the generic type within the `ItemsSource` collection. To simplify binding operations in most cases, declaring `InheritDataTypeFromItemsAttribute` for this property can streamline the binding expression.

## Environment 

- OS: unrelated to the operating system
- Avalonia-Version: 11.0.6

**Comment by gehongyan** [comment]
> https://youtrack.jetbrains.com/issue/RSRP-497884

**Comment by maxkatz6** [comment]
@gehongyan thank you, added to the list https://github.com/AvaloniaUI/Avalonia/issues/10356
