### ISSUE TITLE
Context Menu MaxWidth is arbitrary 456 pixels

### ISSUE THREAD

**Issue by Ehrode** [AvaloniaUI/Avalonia#14160]
## Describe the bug
My context menu width can't exceed 456 pixels for some reason.
I tries from a blank app setting a context menu width by hand : the width increase until it reach 456 pixels and can't be larger afterward.

## To Reproduce
Create an avalonia blank app

Add this code to the MainWindow:

`<Button Content="{Binding MyTextValue}">
        <Button.ContextMenu>
            <ContextMenu Width="300">
                <MenuItem Header="{Binding $parent.Bounds.Width}"></MenuItem>
            </ContextMenu>
        </Button.ContextMenu>
    </Button>`

Open the context menu, you should see 300 and the context menu size effectively seams to be 300 pixels

Now change the width to 800 pixels:

<Button Content="{Binding MyTextValue}">
        <Button.ContextMenu>
            <ContextMenu Width="800">
                <MenuItem Header="{Binding $parent.Bounds.Width}"></MenuItem>
            </ContextMenu>
        </Button.ContextMenu>
    </Button>

Open the context menu by right clicking the button, the parent bounds width is 456 pixels instead of 800.

## Expected behavior
Context menu size can be increased more than 456 pixels

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/40527875/707558da-4c7e-4961-b824-e68b3dafc1db)

## Environment 

Windows 11
Avalonia 11.0.5

**Comment by Ehrode** [comment]
Setting the max width along with the width seams to fix the problem.
If it's intended behavior and the max width of the control by default is 456 I could close the issue.
But is it wanted to have the context menu default max size to 456 pixels?

**Comment by timunie** [comment]
ContextFlyout is better than ContextMenu and should be used for newer Apps
