### ISSUE TITLE
Visual Studio Extension Doesn't show .NET Core option

### ISSUE THREAD

**Issue by SomeProgrammerGuy** [AvaloniaUI/Avalonia#1418]
I’ve just come across this today so I though I would have a play.

I installed the “Visual Studio Extension” in the latest updated version of Visual Studio and it didn’t have any selection for .NET Core”

I think this is a really worthwhile project and could go far but simply put without documentation I will (and most) ignore it. Especially when the documentation is so out of date (and admittedly so).

I get its Alpha / Beta whatever but that isn’t an excuse.

Bootstrap is a good example of how it should be. With each of the latest releases Alpha and otherwise it had good comprehensive documentation at each step.

Programmers like to code and don’t like to document I get this. But if you want this project to go far you need to document it at every real step of development.

I’ve seen so many good projects fall by the wayside simply because it had none (or a very poor out of date example).

In real life few people don’t care how cool your code is (even programmers). People just want to know how it works, how to use it and some good examples whatever stage of development it’s at.

I think this project is even worthy of a Kickstarter and I’ve noticed it has a sort of funding option (that’s being ignored).

I would put money into this as a Kickstarter etc if it had good documentation and I could actually use it even now (bugs and all). Without any up to date docs I can’t be bothered even trying to install it again.

Most would rather it took longer to develop and had good documentation than it was developed faster.

Yes, its free, etc but your time is rather wasted if nobody can use and test it. “We will do the docs when its finished” just doesn’t cut it as these projects are never finished. Nor will you get any real feedback if developers can’t even install it with the current docs.

I would love this project to get some traction but you need to document it NOW...

**Comment by grokys** [comment]
Hi @WHBitbucket 

Yeah we know our documentation sucks :( I'm working on documentation over at https://github.com/AvaloniaUI/avaloniaui.net/pull/8 but I'm doing this alongside a day job and a life, meaning that it takes a while. All of our contributors are volunteering at the moment, and while we may in future be able to make a living from it in future, we're not able to at the current time.

Regarding your particular problem, this is mentioned in the docs I'm working on:

https://github.com/AvaloniaUI/avaloniaui.net/blob/30ac2d8a0b386dd592c8c42d1f303638e6c0737f/wwwroot/docs/quickstart/create-new-project.md
https://github.com/AvaloniaUI/avaloniaui.net/blob/30ac2d8a0b386dd592c8c42d1f303638e6c0737f/wwwroot/docs/quickstart/change-target-framework.md

@kekekeks maybe we should merge the documentation in that PR as it is and get it live?

**Comment by WHBitbucket** [comment]
Ha ha no programmer has a life :-)

**Comment by kekekeks** [comment]
@grokys 

I'll upload the updated website when I'll get back from Minsk. I really need to setup CI instead of manually doing this.

**Comment by cmshawns** [comment]
@grokys A small correction for the new docs: It looks like 

> dotnet install -i [path-to-repository]

should actually be

> dotnet new -i [path-to-repository]

For me, the first complained about not being able to find a `dotnet-install` executable, while the second installed the templates.

**Comment by maxkatz6** [comment]
Our templates are .NET Core for a long time already

**Comment by SomeProgrammerGuy** [comment]
Nothing like a response to a three year old question lol.
