### ISSUE TITLE
Skia ignores IStreamGeometryContextImpl.BeginFigure isFilled parameter

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#1419]
This API [comes from WPF](https://msdn.microsoft.com/en-us/library/system.windows.media.streamgeometrycontext.beginfigure(v=vs.110).aspx) but Skia's `Path` object doesn't seem to have a concept of non-filled paths as far as I can see.

We have two choices here:

1. Remove the parameter - you can always pass a null brush to draw a non-filled path
2. Make Skia fill with a null brush when this parameter is passed

Not sure what the best option is - @kekekeks your thoughts?

**Comment by wieslawsoltes** [comment]
@grokys 
I think you have to use MoveTo to begin new figure in skia. 

https://github.com/wieslawsoltes/Core2D/blob/master/utilities/Core2D.Renderer.SkiaSharp/XPathGeometryConverter.cs#L34

**Comment by wieslawsoltes** [comment]
And for drawing with or without fill I use something like this in skia:  https://github.com/wieslawsoltes/Core2D/blob/master/utilities/Core2D.Renderer.SkiaSharp/SkiaSharpRenderer.cs#L299-L310

```C#
        private void DrawPathInternal(SKCanvas canvas, SKPaint brush, SKPaint pen, bool isStroked, bool isFilled, SKPath path)
        {
            if (isFilled)
            {
                canvas.DrawPath(path, brush);
            }

            if (isStroked)
            {
                canvas.DrawPath(path, pen);
            }
        }
```

**Comment by kekekeks** [comment]
For Skia we are doing stroke and fill operations separately.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Skia/Avalonia.Skia/DrawingContextImpl.cs#L72

If isFilled is applied to the entire path we could just skip the fill operation here.

**Comment by kekekeks** [comment]
Our Skia backend also doesn't support multiple figures in the same geometry. We might have to refactor that part of the backend, so geometry could contain several SKPath objects.

**Comment by tombo86** [comment]
It looks like this issue was never resolved.  Is it still on the table?  I am running into an issue with the PathFigure.IsFilled attribute not being respected.  For example, for the following code:
```
                <Path StrokeThickness="2" Stroke="Black" Fill="Black" Width="20" Height="20">
                    <Path.Data>
                        <PathGeometry>
                            <PathFigure StartPoint="19 19" IsFilled="False" IsClosed="False">
                                <LineSegment Point="6 19"/>
                                <LineSegment Point="6 6"/>
                            </PathFigure>
                            <PathFigure StartPoint="6 2" IsClosed="True">
                                <LineSegment Point="2 6"/>
                                <LineSegment Point="10 6"/>
                            </PathFigure>
                        </PathGeometry>
                    </Path.Data>
                </Path>
```
Looks like this in WPF:
![WPF](https://user-images.githubusercontent.com/1319006/154384893-e7ca4767-0020-4c8d-8e0c-b591d64e9d0b.jpg)

And this in Avalonia:
![Avalonia](https://user-images.githubusercontent.com/1319006/154384890-fd033547-4202-436d-9415-bee92f746025.jpg)
