### ISSUE TITLE
Inconsistent tooltips updates

### ISSUE THREAD

**Issue by Coloris** [AvaloniaUI/Avalonia#14201]
## Describe the bug

ToolTips are not consistently updated correctly. They often display the parent Tooltip, get stuck on the screen, or fail to appear altogether.

## To Reproduce

```
<Panel ToolTip.Tip="Outer Panel"

       Background="White">
    <Grid Margin="100" 
          Background="Red"
          ToolTip.Tip="Inner Panel">
			     <TextBlock Text="{Binding Greeting}" HorizontalAlignment="Center" VerticalAlignment="Center"/>
        <Button Content="hi" Background="Blue" Foreground="White"
                ToolTip.Tip="hello" />
    </Grid>
</Panel>
```

## Expected behavior
ToolTips should be updated correctly based on the current context and not get stuck on the screen

## Screenshots
![](https://raw.githubusercontent.com/Coloris/FluentAvaloniaNavViewTooltipIssue/main/AvaloniaTooltipIssue.gif)

## Environment 

- OS:  Windows 11
- Avalonia-Version: 11.0.6

## Additional context
Spotted first in the FA project : https://github.com/amwx/FluentAvalonia/issues/509

**Comment by timunie** [comment]
@Coloris can you check what nightly does?

**Comment by timunie** [comment]
duplicate of https://github.com/AvaloniaUI/Avalonia/issues/5780

**Comment by Coloris** [comment]
Oh sorry for the duplicate, I did check for similar issues before posting, but unfortunately, I missed that one.
