### ISSUE TITLE
Setting background transparency does not work on Windows Server 2016 systems

### ISSUE THREAD

**Issue by Naylor55** [AvaloniaUI/Avalonia#14210]
## Describe the bug
Setting background transparency does not work on Windows Server 2016 systems

## To Reproduce

1. init a Avalonia Project 
2. setting MainWindows transparency ，I tried two ways 。 first is  set Background="Transparent" ， The second is use follow code 

~~~

<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:AvaloniaApplication1.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:views="clr-namespace:AvaloniaApplication1.Views"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="AvaloniaApplication1" >
        <views:MainView />
  <Window.Styles>
    <Style Selector="Window">    
      <Setter Property="Background">
        <Setter.Value>
          <SolidColorBrush Color="White" Opacity="0"></SolidColorBrush>
        </Setter.Value>
      </Setter>
    </Style>
  </Window.Styles>
</Window>


~~~

4. build & publish 
5. Run separately on Windows11  and WindowsServer 2016

## Expected behavior

Expected behavior can achieve transparency in both Windows11 and WindowsServer2016, but in reality, it is only transparent in Windows11

## Screenshots

Windows11:
![1](https://github.com/AvaloniaUI/Avalonia/assets/13940383/5e8b3954-2000-4101-920f-2eeb3cbd5ed6)

Windows Server 2016:
![2](https://github.com/AvaloniaUI/Avalonia/assets/13940383/b443016a-e87c-4bec-88d9-96eb4b69a7bd)

## Environment 

- OS: Windows11 ,   WindowsServer2016
- Avalonia-Version: 11.0.6

## Additional context

I have attempted to modify the rendering engine to Avalonia Direct2D1 ， Not solving this problem 。

~~~

  public static AppBuilder BuildAvaloniaApp()
      => AppBuilder.Configure<App>()
          .UsePlatformDetect()
          .UseDirect2D1()
          .WithInterFont()
          .LogToTrace();

~~~

**Comment by maxkatz6** [comment]
Try lates nightly builds, where we have DirectComposition available on Windows backend.

**Comment by Naylor55** [comment]
If the windows Server 2016 theme is set to dark, the background is black; If the windows Server 2016 theme is set to light color, the background is white. It's so interesting，Although my code has made the background transparent

**Comment by timunie** [comment]
RequestedThemeVariant follows system by default. So expected here if transparent fails. Does transparent works on other platforms for you btw?

**Comment by Naylor55** [comment]
@maxkatz6 Is your suggestion for me to switch the  nuget package source  to avalonia-nighty ? I found a [wiki ](https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed) and followed it, but the background still cannot be transparent on Windows Server 2016 OS

**Comment by Naylor55** [comment]
After multiple attempts, I found that on Windows Server 2016, controls （eg:Border）can have background transparency, while window cannot have background transparency.

**Comment by timunie** [comment]
@Naylor55 what is your `TransparencyLevelHint="Transparent"` set to on MainWindow?

**Comment by Naylor55** [comment]
@timunie 
I have tried many ways:
* MainWindow.axaml - Background=Transparent

~~~

<Window
......
Background="Transparent"

>

~~~

* MainWindow.axaml  - windowStyle

~~~
<Window

......

        >
  <Window.Styles>
    <Style Selector="Window">
      <Setter Property="ExtendClientAreaChromeHints" Value="NoChrome"></Setter>
      <Setter Property="ExtendClientAreaTitleBarHeightHint" Value="-1"></Setter>
      <Setter Property="SystemDecorations" Value="None"></Setter>
      <Setter Property="CanResize" Value="False"></Setter>

    </Style>
  </Window.Styles>

or

  <Window.Background>
    <SolidColorBrush Color="Transparent" />
  </Window.Background>


~~~

* win32 api - SetLayeredWindowAttributes

~~~


public partial class MainWindow : Window
{

    public MainWindow()
    {
        InitializeComponent();


    }


    //根据窗体的类名或者标题名来找到窗口的句柄
    [DllImport("user32.dll", EntryPoint = "FindWindow")]
    private extern static IntPtr FindWindow(string lpClassName, string lpWindowName);

    //指定扩展窗口，以便控制窗口的透明度
    [DllImport("user32", EntryPoint = "SetWindowLong")]
    private static extern uint SetWindowLong(IntPtr hwnd, int nIndex, uint dwNewLong);

    //设置窗体的透明度，dwFlags指定为2时，bAlpha才能起作用
    [DllImport("user32", EntryPoint = "SetLayeredWindowAttributes")]
    private static extern int SetLayeredWindowAttributes(IntPtr hwnd, int crKey, int bAlpha, int dwFlags);



    [DllImport("user32", EntryPoint = "UpdateWindow")]
    private static extern uint UpdateWindow(IntPtr hwnd);

    private const uint WS_EX_LAYERED = 0x80000;
    private const int GWL_EXSTYLE = (-20); //设置为分层窗口 20 才能进行控制
    private const int LWA_ALPHA = 0x2;




    /// <summary>
    /// 
    /// </summary>
    /// <param name="handle"></param>
    /// <param name="windowName"></param>
    /// <param name="windowOpacity">范围从 0（完全透明）到 255（完全不透明）</param>
    public static void changeOpacity(IPlatformHandle handle, string windowName, int windowOpacity)
    {
        uint v = SetWindowLong(handle.Handle, GWL_EXSTYLE, WS_EX_LAYERED);
        int v1 = SetLayeredWindowAttributes(handle.Handle, 0, windowOpacity, LWA_ALPHA);
        UpdateWindow(handle.Handle);
    }

    private void Button_Click(object? sender, Avalonia.Interactivity.RoutedEventArgs e)
    {

        IPlatformHandle? platformHandle = this.TryGetPlatformHandle();
        changeOpacity(platformHandle, "", 0);

        Button b = new Button();
        b.Width = 100;
        b.Height = 100;
        b.Background = Brushes.Red;

        this.Content = b;
    }
}

~~~


and   then , I  found a  [wiki](https://docs.avaloniaui.net/zh-Hans/docs/concepts/toplevel) ，the wiki tell me can call TopLevel.ActualTransparencyLevel to know   platform was able to provide  TransparencyLevel  is . 

~~~

        TopLevel topLevel = TopLevel.GetTopLevel(this);
        WindowTransparencyLevel actualTransparencyLevel = topLevel.ActualTransparencyLevel;
        string v = actualTransparencyLevel.ToString();

~~~

*  in  windows 11 : v = Transparency
*  in  windows server 2016 : v = None 

so , my current conclusion is that windows server 2016  does not support  ` Window  Transparency`

**Comment by timunie** [comment]
I still don't see where you set `TransparencyLevelHint` ? This is a property that can be set by you. The defaults may differ per OS.

**Comment by Naylor55** [comment]
@timunie Is it like this?   

~~~


public partial class MainWindow : Window
{

    public MainWindow()
    {
        InitializeComponent();
    }

    private void Button_Click(object? sender, Avalonia.Interactivity.RoutedEventArgs e)
    {
       TopLevel topLevel = TopLevel.GetTopLevel(this);
       WindowTransparencyLevel actualTransparencyLevel = topLevel.ActualTransparencyLevel;
       string v = actualTransparencyLevel.ToString();
       LogUtil.SetLogTx(v);

        List<WindowTransparencyLevel> list = new List<WindowTransparencyLevel>();
        list.Add(WindowTransparencyLevel.Transparent);
        topLevel.TransparencyLevelHint = list;
        WindowTransparencyLevel actualTransparencyLevel2 = topLevel.ActualTransparencyLevel;
        string v2 = actualTransparencyLevel.ToString();
        LogUtil.SetLogTx(v2);
    }
}

~~~

I tried setting it up through  topLevel.TransparencyLevelHint =Transparent , and after setting it up,  I obtained topLevel.ActualTransparencyLevel, it is still None .

**Comment by timunie** [comment]
no idea if that is supported that way. I only have used that property in XAML directly

**Comment by Naylor55** [comment]
> Contributor

aha

**Comment by Naylor55** [comment]
@timunie aha

**Comment by timunie** [comment]
I'm having the feeling that Windows Server does not support it correctly. So seems to be by design. See also: https://learn.microsoft.com/en-us/answers/questions/766907/window-cannot-be-made-transparent-half-transparent

**Comment by Naylor55** [comment]
@timunie ok,thanks!!!
