### ISSUE TITLE
BoxShadow.ToString() do not allow to parse it again (exception thrown)

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#14211]
## Describe the bug
The ToString() method of BoxShadow to not allow to Parse it again. It throw an exception.

## To Reproduce
1. Create a BoxShadow with OffsetX=1, OffsetY=0, Blur=0, Color=#ffaa00
2. ToString => 1 #ffaa00
3. Try to parse it => if (p.Length < 3 || p.Length > 6) throw new FormatException();

## Expected behavior
ToString() should write all BoxShadow properties all the time, or we cannot parse it again, and also we don't know what value in the string correspond to what properties...

I would like to do:
var boxShadow2 = BoxShadow.Parse(boxShadow1.ToString())

## Environment 

- Avalonia-Version: 11.0.6

## Additional context

In the code below, we don't know don't know what value in the string correspond to what property...
```
internal void ToString(StringBuilder sb)
{
    if (this == default(BoxShadow))
    {
        sb.Append("none");
        return;
    }

    if (IsInset)
    {
        sb.Append("inset ");
    }

    if (OffsetX != 0.0)
    {
        sb.AppendFormat("{0} ", OffsetX.ToString(CultureInfo.InvariantCulture));
    }

    if (OffsetY != 0.0)
    {
        sb.AppendFormat("{0} ", OffsetY.ToString(CultureInfo.InvariantCulture));
    }

    if (Blur != 0.0)
    {
        sb.AppendFormat("{0} ", Blur.ToString(CultureInfo.InvariantCulture));
    }

    if (Spread != 0.0)
    {
        sb.AppendFormat("{0} ", Spread.ToString(CultureInfo.InvariantCulture));
    }

    sb.AppendFormat("{0}", Color.ToString());
}
```

**Comment by Gillibald** [comment]
OffsetX and OffsetY are required all the time

**Comment by dbriard** [comment]
@Gillibald Sure, but in the ToString method, if OffsetX or OffsetY is zero, it is skiped.

The two BoxShadow below produce the same output string, and cannot be parsed as they do not have a minimum of 3 values.
OffsetX=0 OffsetY=1 Color=Red => "1 Red"
OffsetX=1 OffsetY=0 Color=Red => "1 Red"

it is even worse when using other parameters
OffsetX=1 OffsetY=0 Color=Red => "1 Red"
OffsetX=0 OffsetY=0 Blur=1 Color=Red => "1 Red"

My suggestion is to remove the four zero checks in the ToString()

**Comment by Gillibald** [comment]
It should look like so:

```
internal void ToString(StringBuilder sb)
{
    if (this == default(BoxShadow))
    {
        sb.Append("none");
        return;
    }

    if (IsInset)
    {
        sb.Append("inset ");
    }

    sb.AppendFormat("{0} ", OffsetX.ToString(CultureInfo.InvariantCulture)); 

    sb.AppendFormat("{0} ", OffsetY.ToString(CultureInfo.InvariantCulture));
    
    if (Blur != 0.0)
    {
        sb.AppendFormat("{0} ", Blur.ToString(CultureInfo.InvariantCulture));
    }

    if (Spread != 0.0)
    {
        sb.AppendFormat("{0} ", Spread.ToString(CultureInfo.InvariantCulture));
    }

    sb.AppendFormat("{0}", Color.ToString());
}
```

**Comment by dbriard** [comment]
Personnally I never use Spread so that's fine to me, but if you keep the checks you cannot differentiate those cases:

Blur = 0 and Spread = 1
and Blur = 1 and Spread = 0

So I think it is better to always write all four values.
