### ISSUE TITLE
Incorrectly Ordered Character Input in AutoCompleteBox

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#14216]
## Describe the bug

AutoCompleteBox text input is broken in a rather severe way. Typed characters are incorrectly ordered.

## To Reproduce

1. Type first character
2. Type second character
3. Note the cursor moves to the wrong position...
4. Type third character, it's in the wrong position

## Expected behavior

Normal text input

## Screenshots

![issue](https://github.com/AvaloniaUI/Avalonia/assets/17993847/6aa9a942-a7cc-4f07-90ec-be5077394449)

## Environment 

- OS: Windows 10 Pro 22H2
- Avalonia-Version: 11.0.6+ (36e7ab50043a871d725f72be5366950d93737801)

## Additional context

The PR https://github.com/AvaloniaUI/Avalonia/pull/13851 likely broke this. cc @RobertMut

**Comment by robloo** [comment]
There are issues with selection as well it seems.

I think we should consider reverting the related PRs before the next release. These issues make AutoCompleteBox unusable.

**Comment by maxkatz6** [comment]
Original PR wasn't backported to 11.0, so we have a bit more time.

**Comment by RobertMut** [comment]
Hi, thanks for mentioning. 
I've opened a pull request #14264 with a fix. By the accident I added CoerceCaretIndex to CaretIndexProperty in AutoCompleteBox, which caused this weird behaviour, if I understand correctly.
Sorry for causing trouble!

**Comment by timunie** [comment]
> Sorry for causing trouble!

@RobertMut don't worry, we appreciate your contributions and also your sense of fixing things introduced by accident ❤️
