### ISSUE TITLE
Linux Framebuffer DRM mode + AOT compilation leads to Segmentation Fault on linux-x64

### ISSUE THREAD

**Issue by BenniSim** [AvaloniaUI/Avalonia#14227]
## Describe the bug
When creating an Avalonia application that's configured to use DRM (via Avalonia.LinuxFramebuffer), if publishing the application against linux-x64 with the PublishAot property set to true, then on attempting to run the application the following error will be returned:
```
Segmentation fault (core dumped) 
```

This error does not occur if simply publishing with trimming (`PublishTrimmed=true` & `TrimMode=full`) nor when using ReadyToRun (`PublishReadyToRun=true`).

## To Reproduce

1. Create an Avalonia project with DRM support per the documentation here: https://docs.avaloniaui.net/docs/guides/platforms/rpi/running-on-raspbian-lite-via-drm
2. When publishing the application, set the following properties:
  * `RuntimeIdentifier=linux-x64`
  * `PublishAot=true`
3. When attempting to run the application in a DRM supported context, e.g. the virtual console in Ubuntu (Alt + Ctrl + F3), the application will fail to launch and the error message `Segmentation fault (core dumped) will be displayed.

## Expected behavior
That the application is displayed exactly when not publishing with AOT compilation.

## Environment 

- OS: Ubuntu 22.04 LTS
- Avalonia-Version: 11.0.6
- Architecture: x64
- .NET SDK Version: 8.0.101

## Additional context
I've tested doing the publish from the following linux environments:
* Ubuntu 20.04 (WSL2)
* Ubuntu 22.04 (Host)
* Debian 10 (Docker container)

And with their default C compilation tools used for the AOT compilation tools used. Same issue regardless.

**Comment by BenniSim** [comment]
After some trial and error I've managed to narrow it down so that the error happens when [Avalonia.LinuxFrameBuffer.Output.DrmOutput:GetFbIdForBo(IntPtr bo)](https://github.com/AvaloniaUI/Avalonia/blob/11.0.7/src/Linux/Avalonia.LinuxFramebuffer/Output/DrmOutput.cs#L126) tries to call the `drmModeAddFB2` method located in [Avalonia.LinuxFramebuffer.Output.LibDrm](https://github.com/AvaloniaUI/Avalonia/blob/11.0.7/src/Linux/Avalonia.LinuxFramebuffer/Output/Drm.cs#L184), but without knowing exactly why it happens, or if it can be resolved to work with AOT compilation.

**Comment by maxkatz6** [comment]
These PInvoke methods can be possibly improved by avoiding runtime marshaling, and replacing these arrays with pointers/spans. 
But it shouldn't really affect AOT.

**Comment by kekekeks** [comment]
Please, use LLDB to identify the place where it crashes. It should provide you with a proper call stack

**Comment by workgroupengineering** [comment]
This

```csharp
var offsets = Array.Empty<uint>();
```

is equal to

```csharp
var offsets = new uint[0];

```


```csharp
var offsets = new uint[]{0, 0, 0, 0};

```

equal

```csharp
var offsets = new uint[4];
```

**Comment by maxkatz6** [comment]
> is equal to

Not always. `Array.Empty<uint>()` will reuse the same object.
I.e. `Array.Empty<uint>() == Array.Empty<uint>()`, but `new uint[0] != new uint[0]`.
