### ISSUE TITLE
Crashes and will not start an untouched "app" in VS 2017 if there is a hyphen in the name.

### ISSUE THREAD

**Issue by WHBitbucket** [AvaloniaUI/Avalonia#1422]
If I create a Solution / Project called "Avalonia-Test" it crashes when started. Im assuming its the Hyphen it doesnt like.

**Comment by jp2masa** [comment]
I had the same problem: #1081.

**Comment by WHBitbucket** [comment]
Without reading to deep into it I guess its to do with this https://github.com/dotnet/project-system/issues/2016
