### ISSUE TITLE
DevTools overlay only shows while hovering text in control tree

### ISSUE THREAD

**Issue by AtomCrafty** [AvaloniaUI/Avalonia#14230]
While hovering over an element in the DevTools control tree, the corresponding element is highlighted in the application window. However this only happens while the mouse cursor is positioned over the actual text (the control type name, class list or element name). It's pretty annoying, especially with controls like `Grid` or `Panel`, since the type name is so short you actually have to aim to hit the text.

The reason for the current behavior is that the `AddAdorner` and `RemoveAdorner` event handlers are added to the stack panel containing the text elements, but that stack panel doesn't have a background set, so only its children receive pointer events.

https://github.com/AvaloniaUI/Avalonia/blob/2a7b5568b7f61fe6df9c46a05bf1c9d474c9290e/src/Avalonia.Diagnostics/Diagnostics/Views/TreePageView.xaml#L14-L20

An easy improvement would be to just add a transparent background, but that still isn't a perfect solution. The stack panel doesn't cover the full height of the tree view item, so when moving the mouse from one item to the next the adorner flickers, even if both controls have the same bounds. Also hovering the chevron or the area left to it would still not show the adorner

Ideally the event handlers would be attached to the `TreeViewItem` itself, but without event setters I'm not sure how one would do that.

![image](https://github.com/AvaloniaUI/Avalonia/assets/4553050/a6848156-7bd9-4016-96f9-5a2cab470219)

**Comment by timunie** [comment]
probably the event can be added to the TreeView itself. e.Sender could point to the control that first send the event.

**Comment by AtomCrafty** [comment]
Yeah that appears to work. I'll get a PR ready.
