### ISSUE TITLE
Unable to change the selected item of a Combobox by clicking on a button.

### ISSUE THREAD

**Issue by IronEaterBeast** [AvaloniaUI/Avalonia#14248]
## Describe the bug
The Combobox has three options: 1, 2, and 3. When the button is clicked, the expectation is that the selected item of the Combobox will change to 2, but it doesn't.

## To Reproduce

1. Run.
2. Click on button
3. The selected item of the Combobox did not change.

## Expected behavior
Combobox will change to 2

![3](https://github.com/AvaloniaUI/Avalonia/assets/9688223/755c6f3a-2bdf-4bf6-8306-8dd3a95fa844)
![2](https://github.com/AvaloniaUI/Avalonia/assets/9688223/55d4bc82-61c6-4f63-82b8-77fb4290de9c)
![1](https://github.com/AvaloniaUI/Avalonia/assets/9688223/e3e00b05-5ae8-4887-a37c-1837d12381b7)

**A minimum sample is uploaded.**
[testmvvm.zip](https://github.com/AvaloniaUI/Avalonia/files/13964307/testmvvm.zip)

**Comment by timunie** [comment]
Use SelectedItem instead of SelectedValue should work

**Comment by IronEaterBeast** [comment]
> Use SelectedItem instead of SelectedValue should work

@timunie  still doesn't work.

![4](https://github.com/AvaloniaUI/Avalonia/assets/9688223/b2b9ffdf-1334-4a20-82fe-7f2c256e585f)

**Comment by timunie** [comment]
It's no Binding? 
`SelectedItem="{Binding SelectedItem}"`
