### ISSUE TITLE
Headless Test Button Command not executed

### ISSUE THREAD

**Issue by epsmae** [AvaloniaUI/Avalonia#14251]
## Describe the bug

In a Headless test it is not possible to get the command executed when we trigger a button click.
I would expect that the command is trigger and not only the click event fired when we trigger a button click with `button.RaiseEvent(new RoutedEventArgs(Button.ClickEvent, null));` .

## To Reproduce

ViewModel
```
public partial class ButtonTextViewPageViewModel : ObservableObject
{

	[ObservableProperty]
	private string _text = "Not Set";

	[RelayCommand]
	private void SetTestText()
	{
		Text = "Test";
	}
}
```

Usercontrol
```
<UserControl
    x:Class="ButtonTextViewPage"
	...
    xmlns:viewModels="clr-namespace:.ViewModels"
    d:DesignHeight="450"
    d:DesignWidth="800"
    x:DataType="viewModels:ButtonTextViewPageViewModel">

    <StackPanel Orientation="Vertical">
        <TextBox Name="TestTextBox" Text="{Binding Text}" />
        <Button
            Name="TestButton"
            Command="{Binding SetTestTextCommand}"
            Content="Set Test Text" />
    </StackPanel>
</UserControl>
```

Test which shows that the command binding in general works but `button.RaiseEvent(new RoutedEventArgs(Button.ClickEvent, null));` does not trigger command
```
[AvaloniaTest]
public void TestButtonAndText()
{
	ButtonTextViewPageViewModel viewModel = new ButtonTextViewPageViewModel();

	ButtonTextViewPage page = new ButtonTextViewPage
	{
		DataContext = viewModel
	};

	Window window = new Window
	{
		Content = page
	};

	window.Show();

	Dispatcher.UIThread.RunJobs();

	TextBox textBox = page.Get<TextBox>("TestTextBox");
	
	const string expectedText = "SetOverInput";
	textBox.Text = expectedText;

	Assert.That(textBox.Text == viewModel.Text);


	Button button = page.Get<Button>("TestButton");

	const string expectedTextOverButton = "Test";

	button.Focus();
	
	// Fails if we use this
	button.RaiseEvent(new RoutedEventArgs(Button.ClickEvent, null));
	
	// works if I use this
	// button.Command.Execute(null);

	Dispatcher.UIThread.RunJobs();

	Assert.That(expectedTextOverButton == viewModel.Text);
}
```

## Expected behavior
That the command is trigger on simulated button click.

## Environment 
- OS: All
- Avalonia-Version: 11.0.6

**Comment by maxkatz6** [comment]
The reason why is pretty clear - Button doesn't listen for Click event, it raises right before executing a command - https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Button.cs#L343-L344. In normal world it would still be a normal behavior, but is confusing with unit testing.

Alternatively, you can raise key or pointer events. Also possible to use extension methods on Window class - `window.KeyRelease(Space)` (Space key triggers click on the button). In this case button needs to be focused.

**Comment by epsmae** [comment]
@maxkatz6 thanks It works like that:

```
button.Focus();
window.KeyReleaseQwerty(PhysicalKey.Space, RawInputModifiers.None);
```

I made a PR as this was not clear for me after reading the docs:
https://github.com/AvaloniaUI/avalonia-docs/pull/328
