### ISSUE TITLE
CanResize="True" setting behaves differently on Windows and Ubuntu in Avalonia

### ISSUE THREAD

**Issue by autodeal** [AvaloniaUI/Avalonia#14291]
I am developing a cross-platform application using the Avalonia UI framework. I have set CanResize="True" in the XAML of my window, which allows the window to be resized by dragging its edges on Windows. However, this setting does not seem to work on Ubuntu, and the window cannot be resized by dragging its edges.

Here is the code I used in XAML:
```
<Window CanResize="True">
    <!-- Window content -->
</Window>
```
I am using Avalonia version 11.0.7, Windows version 11, and Ubuntu version 22.04. I would appreciate any help in resolving this issue. Thank you!

**Comment by autodeal** [comment]
The main purpose is to use Avalonia to achieve the purpose of dragging and resizing windows in Ubuntu. During this process, it was found that WPF's ResizeMode="CanResizeWithGrip" does not have a corresponding implementation method in Avalonia.

**Comment by thevortexcloud** [comment]
Ubuntu now uses Wayland by default. Avalonia does not have a native wayland backend (although one is being worked on) as such everything goes via XWayland. Wayland works fairly differently from X11 and things are a lot more restricted/impossible to do. The other problem with Wayland is it delegates a lot of stuff like this up to the implementation of the window manager so each Window Manager has their own protocols for it.

I would suggest trying to use a real X11 session to see if that can solve your problem for now, Although that may not work for very long as a lot of distros are planning to remove X11 support entirely in the next few years. I can confirm it works for me (but I am also not using gnome).

**Comment by maxkatz6** [comment]
Likely a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/5829
Assuming that you use CanResize together with ExtendClientAreaToDecorationsHint .

**Comment by emmauss** [comment]
> Likely a duplicate of #5829 Assuming that you use CanResize together with ExtendClientAreaToDecorationsHint .

Not a duplicate of that issue. The property has no effect on Linux. They are probably using SystemDecorations.None or BorderOnly for the main window. On Linux, BorderOnly falls back to None, and you can't resize the window when it has no decorations.

**Comment by autodeal** [comment]
Thank you for your reply. I feel that application forms developed using the Avalonia framework may not be supported in Ubuntu and can be dynamically resized. I have solved the problem using the following method first, and I will keep an eye on the progress of this issue in the future.
`var screens = Screens.Primary;
var screenWidth = screens.Bounds.Width;
var screenHeight = screens.Bounds.Height;
this.Width = screenWidth;
this.Height = screenHeight;`
