### ISSUE TITLE
[DataGrid] Can OnLoadingRow be called for all of the remaining rows when some rows deleted

### ISSUE THREAD

**Issue by AlvinRey** [AvaloniaUI/Avalonia#14295]
## Description
I tried to automatically generate the row number(in row header, not in column) through the OnLoadingRow event, which is also the way that official ControlCatalog sample use. It works fine when only adding rows, but when it comes to deleting a row, an error occurs. For example, there are 5 rows now, and the row numbers are 1, 2, 3, 4, 5. When I delete the third row, the row numbers become 1, 2, 4, 5.

## Describe solution
I have read another WPF project, whose method of automatically generating row numbers is the same as mine, it is also done in OnLoadingRow. But the difference is that after a row is deleted, WPF's DataGrid will call OnLoadingRow once for all of the remaining rows, so that it can update all row numbers. So I'm wondering if Avalonia's DataGrid can call OnLoadingRow once for the remaining rows after deleting a certain row, like WPF's.

**Comment by maxkatz6** [comment]
It's interesting, because it is not really an expected behavior to reload all rows, when single was removed.

**Comment by AlvinRey** [comment]
I think don't need to actually reload all the rows, you just need to call OnLoadingRow for the rows whose Index has changed. Such as in `private void CorrectSlotsAfterDeletion(int slotDeleted, bool wasRow)` in `DataGridRows.cs`

```
// line 769
for (int index = 0; index < _loadedRows.Count;)
{
    DataGridRow dataGridRow = _loadedRows[index];
    if (IsSlotVisible(dataGridRow.Slot))
    {
        index++;
    }
    else
    {
        if (dataGridRow.Slot > slotDeleted)
        {
            CorrectRowAfterDeletion(dataGridRow, wasRow);
            OnLoadingRow(new DataGridRowEventArgs(dataGridRow)); // add this line
            index++;
        }
        else if (dataGridRow.Slot == slotDeleted)
        {
            _loadedRows.RemoveAt(index);
        }
        else
        {
            index++;
        }
    }
}
```

**Comment by timunie** [comment]
@AlvinRey I guess a converter could also work here.

**Comment by AlvinRey** [comment]
@timunie I have saw a [post](https://stackoverflow.com/questions/59935286/how-to-update-row-number-in-datagrid-wpf) on StackOverFlow showing line numbers via MultiBinding. In that case, it use a binding(Binding Items.Count) as trigger. But in Avalonia, there is not Items, but just ItemsSource. And ItemsSource is IEnumerable, it do not has Count Property.

**Comment by timunie** [comment]
@AlvinRey Luckily Avalonia is better here than WPF. 

I have this converter: 
```cs
// Assume first item is always the DataGridRow
public static FuncMultiValueConverter<object ,int> GetIndexConv { get; } =
	new FuncMultiValueConverter<object, int>(arr => (arr.First() as DataGridRow)!.GetIndex());
```

Usage:
```xml
<DataGrid.Styles>
	<Style Selector="DataGridRow">
		<Setter Property="Header">
			<Setter.Value>
				<MultiBinding Converter="{x:Static vm:MainWindowViewModel.GetIndexConv}">
					<!-- This is DataGridRow -->
					<Binding Path="$self"></Binding>
					<!-- This will trigger index calculation once DataContext has changed, e.g. after sorting -->
					<Binding /> 
				</MultiBinding>
			</Setter.Value>
		</Setter>
	</Style>
</DataGrid.Styles>
```

happy coding

**Comment by howzew** [comment]
@timunie In this method, why did I use (arr.First() as DataGridRow)!.GetIndex()+1 and the line number still starts at 0?
