### ISSUE TITLE
"Unable to load DLL 'api-ms-win-core-winrt-string-l1-1-0.dll' or one of its dependencies" on windows7 

### ISSUE THREAD

**Issue by sandsc** [AvaloniaUI/Avalonia#14309]
latest version 11.0.7 crashed on windows 7, while 11.0.6 is ok. I know Windows 7 has not been supported, but it would be nice to be able to continue running on Windows 7 with a small change.

` at Avalonia.Win32.WinRT.NativeWinRTMethods.WindowsCreateString(String sourceString, Int32 length)
   at Avalonia.Win32.WinRT.NativeWinRTMethods.WindowsCreateString(String sourceString)
   at Avalonia.Win32.WinRT.HStringInterop..ctor(String s)
   at Avalonia.Win32.WinRT.WinRTApiInformation.IsTypePresent(String typeName)
   at Avalonia.Win32.Win32PlatformSettings.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Avalonia.Win32.Win32PlatformSettings.GetColorValues()
   at Avalonia.Application.RegisterServices()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)`

**Comment by timunie** [comment]
Hey @sandsc I don't think that this is an actual bug but an enhancement. Anyways, if you want to file a PR to support Win 7 and it doesn't break anything else, a PR is welcome.

**Comment by maxkatz6** [comment]
In this file we have version check in Lazy factory, but this condition is executed way too late.
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/WinRT/WinRTApiInformation.cs#L11

HStringInterop itself cannot be created on older OS, so there should be another windows version check before that. 

If anybody wants to create a PR, this one should be pretty easy to fix.

**Comment by a191046083** [comment]
Hello. @sandsc @maxkatz6  I'm a experiment on the Windows 7 system I had other projects in order to solve the problem of lack of dependency on Windows 7 microsoft.net core is introduced. The Windows. The apisets - x86 nuget this package If I put the DLL in the nuget package here The latest version will work, but I only tested windows 7 and concluded that windows 7 will work with the new version 11.0.7

**Comment by timunie** [comment]
Should be solved in latest nightly builds and upcoming 11.1

**Comment by PRNDA** [comment]
> latest version 11.0.7 crashed on windows 7, while 11.0.6 is ok. I know Windows 7 has not been supported, but it would be nice to be able to continue running on Windows 7 with a small change.
> 
> ` at Avalonia.Win32.WinRT.NativeWinRTMethods.WindowsCreateString(String sourceString, Int32 length) at Avalonia.Win32.WinRT.NativeWinRTMethods.WindowsCreateString(String sourceString) at Avalonia.Win32.WinRT.HStringInterop..ctor(String s) at Avalonia.Win32.WinRT.WinRTApiInformation.IsTypePresent(String typeName) at Avalonia.Win32.Win32PlatformSettings.<>c.<.cctor>b__8_0() at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor) at System.Lazy`1.CreateValue() at System.Lazy`1.get_Value() at Avalonia.Win32.Win32PlatformSettings.GetColorValues() at Avalonia.Application.RegisterServices() at Avalonia.AppBuilder.SetupUnsafe() at Avalonia.AppBuilder.Setup() at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime) at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)`

Hi, can you still able to run Avalonia application on Windows 7? I created a hello-world Avalonia application, using the 11.0.6 that you said above, but got no luck, it gave me a "Avalonia Application 3 stop working" error dialog, could you please kindly to share me a sample application that confirmed running on Windows 7?

**Comment by maxkatz6** [comment]
@PRNDA 11.0.6 version is 9 months old. As @timunie mentioned, you should check 11.1.x instead, latest one is 11.1.3.

**Comment by PRNDA** [comment]
> @PRNDA 11.0.6 version is 9 months old. As @timunie mentioned, you should check 11.1.x instead, latest one is 11.1.3.

Our app needs to support Windows 7, this is a must for our customers. Is the latest version Avalonia supports Windows 7?

**Comment by timunie** [comment]
@PRNDA no official support for Win 7 anymore but it should kinda work.
