### ISSUE TITLE
ListBox inside a StackPanel inside a ScrollViewer on touch device stutters while scrolling

### ISSUE THREAD

**Issue by msneijders** [AvaloniaUI/Avalonia#14300]
## Describe the bug
Touch scrolling a ScrollViewer containing a StackPanel containing a ListBox will stutter up and down the outside scrollviewer.

```xaml
<ScrollViewer>
   <StackPanel>
      <Panel Height="200">content</Panel>
      <ListBox Items="some text items added" \>
      <Panel Height="200">content</Panel>
   </StackPanel>
</ScrollViewer>
```

## To Reproduce

[ListBoxInScrollViewer.zip](https://github.com/AvaloniaUI/Avalonia/files/14014032/ListBoxInScrollViewer.zip)

1. Open app on touch device (I tested this on Android emulator, and android devices).
2. Do a slow touch move from top to bottom starting on a listbox item.
3. The more you scroll move down in a single drag, the bigger the scroll position will stutter up and down.

## Expected behavior
Scrolling without stuttering up and down would be nice ;p.

## Screenshots

https://github.com/AvaloniaUI/Avalonia/assets/27849065/941e9179-4c8b-4c58-8fa0-e7988e736896

## Environment 

- OS: Android
- Avalonia-Version: 11.0.7

## Workaround

The workaround I use for this scenario, is a copy of the ListBox ControlTemplate, but without the ScrollViewer, and assign this template to the ListBox.

Easier workaround: set ScrollViewer.VerticalScrollBarVisibility="Disabled" on the ListBox.

**Comment by timunie** [comment]
Doesn't really look like an ideal design to me tbh. Better would be to use Grid or DockPanel as outer Panel and let ListBox do the work. But if you really need it as is, conisder to Disable the SV by `ScrollViewer.VerticalScrollBarVisibility="Disabled"`.

**Comment by msneijders** [comment]
thank you for your suggestion -- but is that not just another workaround for the problem?

imo the scrollviewer inside the ListBox, which has nothing to scroll, should not interfere with scrolling in this example, without any workarounds?

**Comment by maxkatz6** [comment]
If it's related to the virtualization, you can disable it in the ListBox by replacing ItemsPanel with StackPanel.

**Comment by msneijders** [comment]
ListBox without virtualization (StackPanel as ItemsPanel) shows the same stuttering scroll behavior.

**Comment by timunie** [comment]
have you tried my "workaround"? Does it help in any way?

**Comment by msneijders** [comment]
> If it's related to the virtualization, you can disable it in the ListBox by replacing ItemsPanel with StackPanel.
> Virtualization wouldn't work anyway inside of another StackPanel, which is expected.

In my tests in this scenario, virtualization in the listbox seems to work normally? I am scrolling using the outer ScrollViewer, but all my 500 items in the listbox I can get into view, and devtools shows the max amount of listitem containers is about 20) (also performance is good, if it is not virtualized performance drops quite a bit.

**Comment by msneijders** [comment]
> have you tried my "workaround"? Does it help in any way?

yes, setting ScrollViewer.VerticalScrollBarVisibility="Disabled" on the ListBox makes scrolling on the outer scrollviewer without stutter

**Comment by timunie** [comment]
In that case I think this is a valid solution for a really rare situation. However I let @emmauss decide if that should be investigated further or closed as `by-design`

**Comment by emmauss** [comment]
Could you check if https://github.com/AvaloniaUI/Avalonia/pull/14329 fixes your issue?

**Comment by msneijders** [comment]
Checked it, unfortunately I can't say I see any different behavior, or maybe it is different but still jittering.

Maybe I am doing it wrong, this is the example solution attached to that PR build (11.1.999-cibuild0043889-beta):
[ListBoxInScrollViewer.zip](https://github.com/AvaloniaUI/Avalonia/files/14025200/ListBoxInScrollViewer.zip)

**Comment by timunie** [comment]
@msneijders there is no preivew build of the PR to test yet I believe. A unit test is failing /cc @emmauss

**Comment by msneijders** [comment]
Wait, I think I spoke too soon -- after properly cleaning and rebuilding and uninstalling on device and redeploy -- it now does seem to fix it -- let me test some more

**Comment by emmauss** [comment]
> @msneijders there is no preivew build of the PR to test yet I believe. A unit test is failing /cc @emmauss

Ok. Will look into that.

**Comment by timunie** [comment]
@msneijders that's interesting tbh, so looks like anything else has fixed your issue already. Still the PR may improve it even further.

**Comment by msneijders** [comment]
and checked with 11.1.999-cibuild0043895-beta, the latest build of your pr @emmauss: no more jitter

(I tried checking it with the nightly build, to see if it was indeed fixed earlier -- but with that package I get a compile error on `AvaloniaMainActivity<App>` -- it cannot find type with generic, didnt know how to fix that)

**Comment by emmauss** [comment]
> I checked it now twice:
> 
> version 11.0.7 -> scrolling jitter version 11.1.999-cibuild0043889-beta -> **no** more jitter

The build points to this, https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=43889&view=results which is an earlier successful build of my pr.

**Comment by msneijders** [comment]
yes indeed -- your pr fixes it, so :thumbsup:.
