### ISSUE TITLE
TextBox SelectedForegroundColor

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#14317]
## Is your feature request related to a problem? Please describe.
When text is selected in a TextBox, it can be difficult to read because of poor contrast.
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/73aa2544-0f96-4549-b8f7-91a95ef0320f)
On the above example, I would like white text color for the selected text.

## Describe the solution you'd like
Would it be possible to add a property to set an alternate text color when text is selected?
Such property exists in WPF.

Thanks in advance if you could consider that improvement request!

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBox.cs#L86

**Comment by dbriard** [comment]
> https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBox.cs#L86

Thanks a lot @Gillibald and sorry... how did I overlook that!? :(
