### ISSUE TITLE
404 nont found on web-page

### ISSUE THREAD

**Issue by danamir522** [AvaloniaUI/Avalonia#1431]
Hello. You have simple bug on main page of your web site . Links on quickstart guide is "http://avaloniaui.net/guides/quickstart", but on main page link is "http://avaloniaui.net/guide/quickstart.html". Please, change this link. Sorry for my english and thanks for you project! Best regards!

**Comment by ForNeVeR** [comment]
Thanks. Already reported at #1391 and fixed by https://github.com/AvaloniaUI/avaloniaui.net/pull/10
