### ISSUE TITLE
Binding on TextBox.Text is not updated when using StringFormat

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#14338]
## Describe the bug

Text is not updated on TextBox with a binding that have StringFormat
Text="{Binding SomeValue, StringFormat='{}{0:F2} cm'}"

The same binding work perfectly on TextBlock.
And this binding without StringFormat work on TextBox.

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.7

**Comment by timunie** [comment]
StringFormat requires Mode=OneWay iirc. Maybe #13970 helps here?

**Comment by dbriard** [comment]
> StringFormat requires Mode=OneWay iirc. Maybe #13970 helps here?

Make sense, thank you!
