### ISSUE TITLE
Add MaxLength property to the TextBox control

### ISSUE THREAD

**Issue by worldbeater** [AvaloniaUI/Avalonia#1433]
Seems that MaxLength bindable property is missing from TextBox control https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBox.cs

For now, we can use [data annotations](https://github.com/AvaloniaUI/Avalonia/blob/7b4c10a7f8b03f767da435f052a878dc10593b41/samples/BindingTest/ViewModels/DataAnnotationsErrorViewModel.cs#L11) to do what we need, but there are cases, when one may need to set that value manually!

UWP, WPF, and Xamarin support this, so Avalonia should do also 😄 https://msdn.microsoft.com/ru-ru/library/system.windows.controls.textbox.maxlength(v=vs.110).aspx

**Comment by grokys** [comment]
Yep, this should definitely be added.

**Comment by pr8x** [comment]
What's up with this one? Is this getting merged any time soon?

**Comment by worldbeater** [comment]
@pr8x this should be pretty easy to fix, will send a PR next weekend if this won't get implemented earlier by someone (feel free to try doing it yourself!). Basically you need to declare a new `AvaloniaProperty` named `MaxLength` and then add a check to `HandleTextInput` method https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBox.cs#L341 also worth adding a unit test for this feature.

**Comment by The-One-Who-Speaks-and-Depicts** [comment]
Still not added

**Comment by maxkatz6** [comment]
@The-One-Who-Speaks-and-Depicts https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBox.cs#L74

**Comment by The-One-Who-Speaks-and-Depicts** [comment]
@maxkatz6 oh, yes, now I see, sorry about that.
