### ISSUE TITLE
Can't open Context Menu in control position - Accidental breaking change in 11.0.7

### ISSUE THREAD

**Issue by Bip901** [AvaloniaUI/Avalonia#14357]
Hi!

I updated today from version 11.0.6 to 11.0.7 (a patch release), but it seems like a breaking change was introduced while fixing issue #12504 in [this PR](https://github.com/AvaloniaUI/Avalonia/pull/13967) 

`ContextMenu.Open()` now shows the context menu near the pointer instead of the bottom of the control, which breaks accessibility keybindings which show a context menu via the keyboard (e.g. simulating clicking the **⋮** button)

It seems like there is now no public API to opening a context menu in the bottom of the control programmatically.

What is the solution for users migrating from 11.0.6 to 11.0.7?

**Comment by maxkatz6** [comment]
You still should be able to set ContextMenu.Placement property before showing.
Also, general recommendation is migration to ContextFlyout control instead.

**Comment by Bip901** [comment]
Alright, thank you!
