### ISSUE TITLE
Adorners are constrained to the bounds of the adorned element in 11.0.7

### ISSUE THREAD

**Issue by chris835** [AvaloniaUI/Avalonia#14379]
## Description
After updating to 11.0.7 adorners no longer seem to be able to be rendered outside the bounds of the adorned element.

## To reproduce
Try the following axaml:

```
<Button Content="Button" HorizontalAlignment="Center">
    <AdornerLayer.Adorner>
        <Rectangle Fill="Red" Opacity="0.2" Margin="-10 -10"/>
    </AdornerLayer.Adorner>
</Button>
```

In 11.0.6 this generates an adorner that covers the button +10 units around. In 11.0.7 the adorner stays inside the button. The result is the same if forcing a specific Width/Height instead of using a negative margin.

## Screenshots
11.0.6:
![image](https://github.com/AvaloniaUI/Avalonia/assets/66271042/1d1dc6b4-9523-48a8-b406-e6583f3ef147)

11.0.7:
![image](https://github.com/AvaloniaUI/Avalonia/assets/66271042/1385e021-5489-429d-bb1f-fc9d071f56a2)

## Environment
- OS: Windows 10
- Avalonia-Version: 11.0.7

**Comment by stevemonaco** [comment]
I've tested `<Button ClipToBounds="False" ...>` and it works (in 11.0.7).
`<Button AdornerLayer.IsClipEnabled="False" ...>` doesn't work, but I might misunderstand its purpose.

**Comment by chris835** [comment]
> I've tested `<Button ClipToBounds="False" ...>` and it works (in 11.0.7). `<Button AdornerLayer.IsClipEnabled="False" ...>` doesn't work, but I might misunderstand its purpose.

I figured putting that on the Button and not the adorner wouldn't do anything as the adorner lives in the adorner layer, but it turns out it does do something. If I put `ClipToBounds="False"` on the outer Button, half the adorner shows up (the top-left part). If I instead put `AdornerLayer.IsClipEnabled="False"` on the Rectangle, it works as it did previously, with or without `ClipToBounds` on the Button. Thanks for the idea!

Just doing `ClipToBounds="False"` on the Rectangle used to be a thing, I think. Seems some changes have been made and that we now need the `AdornerLayer.IsClipEnabled` you mentioned. Interesting!
