### ISSUE TITLE
SelectedItem in ListBox not always actual

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#1437]
Consider the following xaml code:

```xaml
<Window xmlns="https://github.com/avaloniaui" Width="300" Height="200">
  <Grid RowDefinitions="100,30">
    <ListBox Grid.Row="0" Items="{Binding Items}" SelectedItem="{Binding SelectedItem, Mode=TwoWay}"/>
    <Button Grid.Row="1" Command="{Binding ChangeListItem}">Change</Button>
  </Grid>
</Window>
```

And the respective C# code:

```csharp
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using ReactiveUI;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace ListBoxItemUpdateBug
{
    public class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
            this.AttachDevTools();

            this.DataContext = new MainWindowViewModel();
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }

    public class MainWindowViewModel : ReactiveObject
    {
        public ObservableCollection<ListItem> Items { get; } = new ObservableCollection<ListItem>(
            new List<ListItem>()
            {
                new ListItem("test"),
                new ListItem("test"),
                new ListItem("test"),
                new ListItem("test"),
                new ListItem("test"),
                new ListItem("test"),
                new ListItem("test"),
                new ListItem("test"),
                new ListItem("test"),
            }
        );

        public ListItem SelectedItem { get; set; }

        public void ChangeListItem()
        {
            if (SelectedItem != null)
            {
                SelectedItem.Data = "Changed";
                this.RaisePropertyChanged(nameof(SelectedItem));
            }
        }
    }

    public class ListItem
    {
        public string Data { get; set; } = "Test";

        public ListItem(string data) => Data = data;

        public override string ToString() => Data;
    }
}
```

SelectedItem is not updated in ListBox when I click the button. But if I scroll ListBox down and scroll up, the item will be updated with the new value `Changed`.

**Comment by MonkAlex** [comment]
Why ListItem not notify about changes? INotifyPropertyChanged can help, i think.

**Comment by danwalmsley** [comment]
Looks like it's because you haven't changed the actual selected item, just selected item. Data

**Comment by KvanTTT** [comment]
I called `this.RaisePropertyChanged(nameof(SelectedItem));` after. It should be changed whatever.

**Comment by danwalmsley** [comment]
If you set IsVirtualized = false on your listbox does the issue remain? This is not a solution, just to narrow the problem down

**Comment by KvanTTT** [comment]
With the option, `VirtualizationMode="None"` selected item is not changed even with scroll up and scroll down.

**Comment by grokys** [comment]
@KvanTTT sorry, I'm confused, where are you setting the selected item? I can only see you setting `SelectedItem.Data`. That won't have an effect because `ListItem.Data` doesn't notify changes, as @MonkAlex said.

**Comment by KvanTTT** [comment]
There is `this.RaisePropertyChanged(nameof(SelectedItem));` call after setting of `Data`.

**Comment by MonkAlex** [comment]
Maybe ListItem must be override GetHashCode and Equals, for RaisePropertyChanged correct working in case.

**Comment by grokys** [comment]
>There is this.RaisePropertyChanged(nameof(SelectedItem)); call after setting of Data.

Yes, but you're _not setting `SelectedItem`_! You're setting `Data`. You need to raise the property changed event for `Data`.

**Comment by KvanTTT** [comment]
How can I raise an event for `Data`?

**Comment by Gillibald** [comment]
The selection of your listbox will never change if you dont update your SelectedItem. You never change it so you dont get updates on your selection. You have to assign it to update your SelectedItem property. The listbox itself works as expected. Just and error on your side.

**Comment by grokys** [comment]
@KvanTTT you can make your `ListItem` model inherit from `ReactiveObject` and use `RaiseAndSetIfChanged` to raise the events:


```
    public class ListItem : ReactiveObject
    {
        string data = "Test";
        public string Data 
        { 
            get => data;
            set => this.RaiseAndSetIfChanged(ref data, value);
        }

        public ListItem(string data) => Data = data;

        public override string ToString() => Data;
    }```

**Comment by KvanTTT** [comment]
@grokys, unfortunately, it works in the same way :(

**Comment by Gillibald** [comment]
What is the expected result you want to see? Maybe that's not clear? What should change after you updated your model?

**Comment by danwalmsley** [comment]
Any chance you can zip up a repro so we can take a look?

**Comment by KvanTTT** [comment]
Sure. Attached project with sample video: [ListBoxItemUpdateBug.zip](https://github.com/AvaloniaUI/Avalonia/files/1844725/ListBoxItemUpdateBug.zip)

**Comment by MonkAlex** [comment]
@KvanTTT so, remove to string overriding. And add template to show u ListItem class:

```
<Window xmlns="https://github.com/avaloniaui" 
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:c="clr-namespace:ListBoxItemUpdateBug;assembly=ListBoxItemUpdateBug"
        Width="300" Height="200">
  <Window.DataTemplates>
    <DataTemplate DataType="c:ListItem">
      <TextBlock Text="{Binding Data}"/>
    </DataTemplate>
  </Window.DataTemplates>
  <Grid RowDefinitions="100,30">
    <ListBox Grid.Row="0" VirtualizationMode="Simple" Items="{Binding Items}" SelectedItem="{Binding SelectedItem, Mode=TwoWay}"/>
    <Button Grid.Row="1" Command="{Binding ChangeListItem}">Change</Button>
  </Grid>
</Window>
```

Now all work as expected.

**Comment by KvanTTT** [comment]
I'm getting the following exception:

```
"Could not convert object 'c:ListItem' (of type System.String) to {clr-namespace:System;assembly=mscorlib}Type: Invalid typeName: 'c:ListItem'"}	Portable.Xaml.XamlObjectWriterException
```

Could you please attach the full working project?

**Comment by MonkAlex** [comment]
[ListBoxItemUpdateBug.zip](https://github.com/AvaloniaUI/Avalonia/files/1845209/ListBoxItemUpdateBug.zip)

**Comment by KvanTTT** [comment]
Now it works fine. Thanks!
