### ISSUE TITLE
Issue after add any control to default app

### ISSUE THREAD

**Issue by qwordptr** [AvaloniaUI/Avalonia#1438]
I creted default project using Avalon Studio. 
When I add button to MainWindow.xml, then run I have following exception:

> Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Portable.Xaml.XamlDuplicateMemberException: Property '{clr-namespace:Avalonia.Controls;assembly=Avalonia.Controls}ContentControl.Content' is already set to this '{clr-namespace:Avalonia.Controls;assembly=Avalonia.Controls}Window' 

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Test App">
    Hello World!
asd

<Button>Test</Button>
</Window>```

**Comment by grokys** [comment]
Hi @qwordptr - you're trying to set your window content twice:

1. Once to the string "Hello World\nasd"
2. Then to an instance of `Button`

Either remove the string or the button to make it work - a `Window` can only have a single child. If you want to add more than one child, you should add a `Panel` such as `StackPanel` and add your multiple children to this.
