### ISSUE TITLE
Debugging browser app fails in Avalonia 11.0.7

### ISSUE THREAD

**Issue by appel1** [AvaloniaUI/Avalonia#14393]
## Describe the bug
Not sure but the underlying error seems to be a mono_assert that kills the runtime because of a missing function, InputHelper.subscribeVisibilityChange.

## To Reproduce
mkdir sample
cd sample
dotnet new avalonia.xplat
Change to 11.0.7 in Directory.build.props
Open sln in VS
Change startup project to sample.Browser
Debug sample

The splash screen remains indefinitely and the following is written to the console:
[object Object]

If you inspect the exception object in the browser debugger it shows that the application was aborted due to an assert in mono_wasm_lookup_function.

InputHelper.subsccribeVisiblityChange must be a function but was 

## Expected behavior
A Welcome to Avalonia! message in the browser.

## Environment 

.NET 8.0
Debugging with Visual Studio 2022 17.8.4
Edge 121.0.2277.83

It works fine outside of the debugger or if I revert to 11.0.6.

**Comment by maxkatz6** [comment]
Reset your browser cache for the specific web site. 
Also: https://github.com/dotnet/runtime/issues/97097

**Comment by appel1** [comment]
Thanks, I thought I tried that but apparently not since when I tried now it worked.
