### ISSUE TITLE
ItemsRepeater with UniformGridLayout takes very much space

### ISSUE THREAD

**Issue by CodeDevAM** [AvaloniaUI/Avalonia#14402]
## Describe the bug

A clear and concise description of what the bug is.I am new to `ItemsRepeater` with `UniformGridLayout` so maybe my expectation ist wrong. However when I use an ItemsRepeater with an `UniformGridLayout` with `Orientation` set to `Horizontal` it creates a giant container without need.

## To Reproduce

See attached example
[EvenlySpaved.zip](https://github.com/AvaloniaUI/Avalonia/files/14093702/EvenlySpaved.zip)

## Expected behavior

My expectation is something like this:
![grafik](https://github.com/AvaloniaUI/Avalonia/assets/125025268/4ae50628-82f3-4fc7-a48c-0f94b11424ee)

But I get this:
![grafik](https://github.com/AvaloniaUI/Avalonia/assets/125025268/c6fbd6c6-3190-4c39-9a84-155c2ffcf1da)

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.7

**Comment by stevemonaco** [comment]
It's the combination of `ItemsStretch="Uniform"`, a large `MinItemHeight`, and very small width elements.

Uniform stretch maintains aspect ratio. This means your tiny elements are stretched 50x+ times to fit the window width. This multiplies the item height during layout which is already quite large with `MinItemHeight`.

**Comment by timunie** [comment]
ItemStretch="Fill" solves it for me
