### ISSUE TITLE
App crashes immediately on Startup on Mac OS if any arguments are passed (11.0.7)

### ISSUE THREAD

**Issue by yankun** [AvaloniaUI/Avalonia#14411]
## Describe the bug
Hi, I've updated Avalonia to 11.0.7 and since then Apps can't be langer started with arguments. As soon as any argument is passed, the app will crash with following (native) error:

`*** Assertion failure in -[AvnApplication run], NSApplication.m:3493
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSApp with wrong _running count'
*** First throw call stack:
(
        0   CoreFoundation                      0x000000018d134540 __exceptionPreprocess + 176
        1   libobjc.A.dylib                     0x000000018cc25eb4 objc_exception_throw + 60
        2   Foundation                          0x000000018e27e39c -[NSCalendarDate initWithCoder:] + 0
        3   AppKit                              0x000000019089047c -[NSApplication run] + 732
        4   libAvaloniaNative.dylib             0x00000001305c9d7c _ZN26PlatformThreadingInterface7RunLoopEP20IAvnLoopCancellation + 484
        5   ???                                 0x0000000108415fc4 0x0 + 4433469380
        6   ???                                 0x0000000108e38600 0x0 + 4444096000
        7   ???                                 0x0000000108e37fc0 0x0 + 4444094400
        8   ???                                 0x0000000108e37a28 0x0 + 4444092968
        9   ???                                 0x0000000108e374a0 0x0 + 4444091552
        10  ???                                 0x0000000108e36fa8 0x0 + 4444090280
        11  ???                                 0x0000000108cc1678 0x0 + 4442560120
        12  ???                                 0x000000010840aa10 0x0 + 4433422864
        13  ???                                 0x0000000108408e4c 0x0 + 4433415756
        14  ???                                 0x0000000104def994 0x0 + 4376689044
        15  ???                                 0x0000000108408ad0 0x0 + 4433414864
        16  ???                                 0x00000001056342b4 0x0 + 4385358516
        17  ???                                 0x0000000105634098 0x0 + 4385357976
        18  ???                                 0x0000000105633dec 0x0 + 4385357292
        19  libcoreclr.dylib                    0x00000001018e7484 CallDescrWorkerInternal + 132
        20  libcoreclr.dylib                    0x000000010176280c _ZN18MethodDescCallSite16CallTargetWorkerEPKyPyi + 856
        21  libcoreclr.dylib                    0x0000000101665814 _Z7RunMainP10MethodDescsPiPP8PtrArray + 632
        22  libcoreclr.dylib                    0x0000000101665b60 _ZN8Assembly17ExecuteMainMethodEPP8PtrArrayi + 260
        23  libcoreclr.dylib                    0x000000010168e018 _ZN8CorHost215ExecuteAssemblyEjPKDsiPS1_Pj + 616
        24  libcoreclr.dylib                    0x0000000101652e68 coreclr_execute_assembly + 204
        25  libhostpolicy.dylib                 0x0000000100c79ad4 _Z19run_app_for_contextRK20hostpolicy_context_tiPPKc + 1052
        26  libhostpolicy.dylib                 0x0000000100c7a8d0 corehost_main + 320
        27  libhostfxr.dylib                    0x0000000100ba6898 _ZN10fx_muxer_t24handle_exec_host_commandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK19host_startup_info_tS8_RKNS0_13unordered_mapI13known_optionsNS0_6vectorIS6_NS4_IS6_E     28  libhostfxr.dylib                    0x0000000100ba5b18 _ZN10fx_muxer_t7executeENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEiPPKcRK19host_startup_info_tPciPi + 860
        29  libhostfxr.dylib                    0x0000000100ba26bc hostfxr_main_startupinfo + 128
        30  Interface.Chat                      0x0000000100b2152c _Z9exe_startiPPKc + 1516
        31  Interface.Chat                      0x0000000100b21740 main + 184
        32  dyld                                0x000000018cc610e0 start + 2360
)
libc++abi: terminating due to uncaught exception of type NSException
`

**Comment by timunie** [comment]
@yankun can you try nightly builds?

**Comment by yankun** [comment]
Tried it (11.0.999-cibuild0043921-beta), unfortunately same error.

**Comment by timunie** [comment]
11.1.... is current nightly build.

**Comment by yankun** [comment]
Sorry! But with 11.1.999-cibuild0044133-beta I still get the same error.

**Comment by timunie** [comment]
If you run the App with a file as argument that seems to be broken currently.

**Comment by yankun** [comment]
Hi, not a file but any Arg will cause this issue.

**Comment by timunie** [comment]
> Hi, not a file but any Arg will cause this issue. Just tested it, args removed: Everything runs fine. Any arg added to any app: The app will crash. Ive updated the issue description accordingly.

That's a useful observation. We try to dig into it.
