### ISSUE TITLE
New AvaloniaApplication template fails to build.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#1441]
Creating a new project using the ["Avalonia Application" template in our extension](https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaforVisualStudio) fails with the following build error:

```
Assets file 'D:\temp\avalonia\AvaloniaApplication19\AvaloniaApplication19\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.1/win7-x86'. Ensure that restore has run and that you have included 'net461' in the TargetFrameworks for your project. You may also need to include 'win7-x86' in your project's RuntimeIdentifiers.
```

Removing the `net461` target fixes it, but we need to work out what is wrong here. Adding the suggested `RuntimeIdentifiers` doesn't seem to fix it.

**Comment by grokys** [comment]
Actually it seems that adding the `<RuntimeIdentifiers>` does work, but not until after the `bin` and `obj` directories are deleted.

**Comment by grokys** [comment]
Nope, looking further into this, it seems that simply restarting VS causes it to build.

**Comment by Kryptos-FR** [comment]
I can confirm that deleting the `bin` and `obj`, then restarting Visual Studio seems to be the only trick that works.
