### ISSUE TITLE
ListBox with VirtualizedStackPanel doesn't scroll correctly horizontally

### ISSUE THREAD

**Issue by BAndysc** [AvaloniaUI/Avalonia#14418]
## Describe the bug
Virtualized ListBox doesn't bring correctly items to view horizontally when the _bring to view item bounds_ are out of the currently set ScrollViewer extents.

## To Reproduce

1. Clone https://github.com/BAndysc/AvaloniaVirtualizedStackPanelInvalidEstimate
2. Press 'Select row 99'
3. See horizontal scroll offset is wrong
4. Select row 98
5. Press 'Select row 99'
6. See horizontal scroll offset is now correct, because the scroll viewer extent was correct

## Expected behavior
No matter what was the initial ScrollViewer extents, BringToView should always scroll correctly.

## Screenshots

https://github.com/AvaloniaUI/Avalonia/assets/5689666/d25e54dc-c00f-448b-9043-e3063bd1fa4b

## Environment 

- OS: macOS
- Avalonia-Version: 11.0.7

## Additional context
This bug exists in my virtualized tree view implementation here: https://github.com/AvaloniaUI/Avalonia/pull/14417

**Comment by timunie** [comment]
maybe related:
#14415 
#14365
