### ISSUE TITLE
Compiled/reflection bindings not consistent with RelativeSource=Self

### ISSUE THREAD

**Issue by billhenn** [AvaloniaUI/Avalonia#14456]
## Describe the bug

When `RelativeSource=Self` is used in a binding on an element, the resulting source should be the element, as it is in WPF.  This works fine in `ReflectionBinding`, however `CompiledBinding` returns the data context instead.

I retested this in a recent PR build for the data binding refactor (https://github.com/AvaloniaUI/Avalonia/pull/13970), but the bug still seems to be present.

## To Reproduce

Use this XAML:
```
<StackPanel x:DataType="x:String" DataContext="Foo">
	<Button x:Name="button" DataContext="Bar">Test</Button>
	<TextBlock Text="{CompiledBinding ElementName=button}" />
	<TextBlock Text="{ReflectionBinding ElementName=button}" />
	<TextBlock Text="{CompiledBinding RelativeSource={RelativeSource Self}}" />
	<TextBlock Text="{ReflectionBinding RelativeSource={RelativeSource Self}}" />
</StackPanel>
```

The `TextBlock` controls currently output:
```
Foo
Avalonia.Controls.Button
Foo
Avalonia.Controls.TextBlock
```

## Expected behavior

The `TextBlock` controls should output this instead:
```
Avalonia.Controls.Button
Avalonia.Controls.Button
Avalonia.Controls.TextBlock
Avalonia.Controls.TextBlock
```

**Comment by robloo** [comment]
Note that this is very similar to:
 * https://github.com/AvaloniaUI/Avalonia/discussions/14353

I tried `{Binding RelativeSource={RelativeSource Self}}` and that did not work either. Decided not to open an issue for it.

@billhenn 

Note that a work around is to use the Avalonia syntax in the attached discussion.

**Comment by billhenn** [comment]
@robloo we originally used `Binding` syntax (it's in a compiled binding enabled project) and noticed the issue.  We ended up flipping that to `ReflectionBinding` syntax to work around the issue for now.  But as mentioned in the other issue, reflection and compiled should have the same results, so we wanted to report it before the all the great data binding enhancements went out in v11.1.

**Comment by robloo** [comment]
> we originally used Binding syntax (it's in a compiled binding enabled project)

Yes, I should have been clear on my end as well. Binding above is in a compiled binding enabled project. It's ported code from WinUI and was original reflection binding. When everything was switched over to compiled bindings at once (with the project setting) an error was noticed here. Probably the same as how you found this.

Agree that reflection and compiled should have the same results. Since there was such an easy work-around I didn't spend the time to create an issue myself. Just wanted to note the case I saw this here though.

**Comment by billhenn** [comment]
Thanks @grokys, this PR update appears to fix the problem.
