### ISSUE TITLE
Simmilar to https://github.com/AvaloniaUI/Avalonia/issues/12182

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#14458]
Simmilar to https://github.com/AvaloniaUI/Avalonia/issues/12182
and to https://github.com/AvaloniaUI/Avalonia/discussions/11726
If we set AllowAutoHide to false in datagrid ScrollBar selector in this way 
```
				<Style Selector="ScrollBar">
					<Setter Property="Background" Value="Blue"/>
					<Setter Property="AllowAutoHide" Value="False"/>
				</Style>
```
last row is not visible..  for demonstration i used  very big ScrollBarSize
```
		<DataGrid.Resources>
			<x:Double x:Key="ScrollBarSize">20.0</x:Double>
		</DataGrid.Resources>
```
![image](https://github.com/AvaloniaUI/Avalonia/assets/69449360/e7e88a52-0b4b-47a5-988c-aa647071b08f)

i found than I can achieve this effect by editing Fluent.xaml in Avalonia.Controls.DataGrid/Themes
![image](https://github.com/AvaloniaUI/Avalonia/assets/69449360/67cd0f6e-4f94-46e9-b453-b627b6af468f)
by changing Grid.RowSpan/Grid.ColumnSpan
![image](https://github.com/AvaloniaUI/Avalonia/assets/69449360/50c962de-6d47-4a18-9ab3-56c022c741ac)
from 2,3 to respectivly 1,2 is there any way to ovveride this values ? 
https://github.com/AvaloniaUI/Avalonia/blob/e0fb7db6c56f745027ef1b041ea0ca24feb27ab5/src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml#L538

i tried this.. Color works but row/column spans not :(
```
				<Style Selector="DataGridRowsPresenter#PART_RowsPresenter">
					<Setter Property="Grid.RowSpan" Value="1"/>
					<Setter Property="Grid.ColumnSpan" Value="2"/>
					<Setter Property="Background" Value="Green"/>
				</Style>	
```

_Originally posted by @KrzysztofDusko in https://github.com/AvaloniaUI/Avalonia/discussions/14445_

**Comment by KrzysztofDusko** [comment]
@timunie Can I try with this ?
