### ISSUE TITLE
Don'n spam NSEVENT into console window on every event 

### ISSUE THREAD

**Issue by d-dizhevsky** [AvaloniaUI/Avalonia#1445]
Regarding #1390, has it been released yet? 
I've just created an empty project using template from avalonia-dotnet-templates repo and still facing this issue. So if it was released in 0.6.1 please update nuget version in template project to point to the latest one because it is outdated, otherwise the issue has not been fixed.

**Comment by grokys** [comment]
No, it's not been included in a release yet, but if you want to get hold of a NuGet package which includes the fix you can use our CI NuGet feed: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed.
