### ISSUE TITLE
2 controls bind to same chained/nested property won't update each other

### ISSUE THREAD

**Issue by butaixianran** [AvaloniaUI/Avalonia#14453]
I'm binding a chained/nested property to both `NumericUpDown` and `Slider` like this:
```xaml
<NumericUpDown Increment="1" Minimum="12" Maximum="72" Value="{Binding CurrentSetting.FontSize}" />
<Slider Minimum="12" Maximum="72"  Value="{Binding CurrentSetting.FontSize}" />
```

But when I changing the value with `Slider` or `NumericUpDown`, the other control won't update. I checked the value of ` CurrentSetting.FontSize`, which is actually changed, but the other control's UI just won't update.  

But, if bind to a Non-chained/nested property like this:
```xaml
<NumericUpDown Increment="1" Minimum="12" Maximum="72" Value="{Binding FontSize}" />
<Slider Minimum="12" Maximum="72"  Value="{Binding FontSize}" />
```
Then both control work fine, I can change value with one control, the other one will update.  

----
Don't tell me it is designed to not work with chained/nested property. 

----

Avalonia version: v11.07
.net target: .net 7.0
Platform: windows 11

**Comment by timunie** [comment]
How is CurrentSetting.FontSize defined?

**Comment by timunie** [comment]
FontSize must be observalbe, not CurrentSetting

**Comment by butaixianran** [comment]
So it is designed to not work with chained/nested property, ok.

**Comment by timunie** [comment]
@butaixianran I talked to @grokys and he also thinks this should be supported. So in case it does not work using nightly builds, please upload a minimal sample for us to analyze.

**Comment by butaixianran** [comment]
I just tested it with WPF, it works perfectly! 

In wpf, I did the exactly same binding with nested/chained property. And when adjusting slider, text box will adjust with it automatically. Also tested nested string property with 2 text boxes, works too.

Now I'm thinking it gonna work with maui too.

**Comment by butaixianran** [comment]
Uploaded an Avalonia example project for testing.
https://drive.google.com/file/d/1lCGTHeDDwG1adwwwgXZUyBNJFosadXiw/view?usp=sharing

**Comment by butaixianran** [comment]
video:
wpf (work):
https://github.com/AvaloniaUI/Avalonia/assets/5558722/fd5b751d-213a-4a3b-8d47-523077f0ddde

avalonia (not work):
https://github.com/AvaloniaUI/Avalonia/assets/5558722/01905c49-260b-49c0-81b4-65e27996e4b7

**Comment by timunie** [comment]
Thanks for sharing this. We will look into, but I cannot tell a due date yet.

**Comment by maxkatz6** [comment]
> So it is designed to not work with chained/nested property, ok. This is Avalonia team's choice, I won't argue on this. As a user, I can only choose to not use avalonia.

It's not how it is.
Chained and nested property bindings ARE supported, as it's pretty obvious use case. 
But as it mentioned before `FontSize` must be observable. How would you expect change notifications to be raised to the second control, if there is no PropertyChanged event?

Now, WPF example is different, as WPF creates a proxy class that wraps your data - PropertyDescriptor. I.e. with WPF you binding is created not to your data directly, but to that proxy class. That's where it comes to our choice to NOT support this feature.
PropertyDescriptor is known to heavily rely on Reflection usage, which is banned for any new feature in Avalonia. And it might cause heavy memory leaks as well. It's not recommended in WPF community to rely on PropertyDescriptor, and it is recommended to use observable properties just like in Avalonia.

**Comment by maxkatz6** [comment]
You can find some more info on this topic by these links:
https://stackoverflow.com/questions/7767218/why-does-the-binding-update-without-implementing-inotifypropertychanged
https://stackoverflow.com/questions/19784028/propertydescriptor-and-wpf-binding-mechinsm
