### ISSUE TITLE
Tooltip and MenuItem Dropdown position gets extra offset by the distance from the top left of the screen to the top left of the viewport

### ISSUE THREAD

**Issue by The-Fireplace** [AvaloniaUI/Avalonia#14476]
## Describe the bug
When using a tooltip, the position it appears at gets an extra offset of however far the top left of the Avalonia app is from the top left of the screen(s).

## To Reproduce

1. Create an element with a tooltip, leaving the positioning as default
2. Run the app with this tooltip
3. Mouse over the element
4. See that the tooltip appears further from the pointer than it should, the distance depending on where the window is positioned on the screen. If that distance is further than the size of the window, it does not display at all.

Alternatively:
1. Create an element with a Menu
2. Run the app with this menu
3. Click the parent menu item
4. See that the child items appear further away from the parent than they should, the distance depending on where the window is positioned on the screen. If that distance is further than the size of the window, it does not display at all.

## Expected behavior
Tooltip appears below the mouse / Menu Items appear below their parent which opened them

## Screenshots
Taken from a quick example I put together (see Additional Context):
![image](https://github.com/AvaloniaUI/Avalonia/assets/5914284/eef9fcd8-f8d9-4ced-8cdc-d2220ebd65e3)
![image](https://github.com/AvaloniaUI/Avalonia/assets/5914284/ea48ecb0-deaf-4aaf-bb79-9c5c1c818415)
![image](https://github.com/AvaloniaUI/Avalonia/assets/5914284/186f20f8-a8d3-4fed-8abf-fcf7d18bb231)
![image](https://github.com/AvaloniaUI/Avalonia/assets/5914284/4e176417-1888-4913-a39b-065cdf1f7eb9)
![image](https://github.com/AvaloniaUI/Avalonia/assets/5914284/30c3f95d-15a5-40b5-9929-85d17d12d45f)

## Environment

- OS: MX Linux 23.2 (with desktop Xfce 4.18.1)
- Avalonia-Version: Bleeding edge nightly (verified that it occurs with 11.1.999-cibuild0044396-beta)

## Additional context
- I put together a quick example, shown in the screenshots (Adjusted partway through to show MenuItem as well):
https://github.com/The-Fireplace/Avalonia.Samples/blob/main/src/Avalonia.Samples/Testing/TestableApp/Views/MainWindow.axaml#L14
- This does not occur on Windows.
- Also tested to verify that the Tooltip problem doesn't occur if I switch back to 11.0.7 (didn't verify again after I added MenuItem to the test app, but I assume it's the same)
- Tested on a multi-monitor setup, and this always seems to base itself on the distance from the top left corner of my primary monitor, which is on the left (e.g. putting the Avalonia window on my right monitor results in the tooltip/menuitem never displaying because the distance puts them out of bounds of the window)

**Comment by maxkatz6** [comment]
@The-Fireplace can you check latest master again?

**Comment by The-Fireplace** [comment]
Just confirmed, it's fixed in 11.1.999-cibuild0044824-beta @maxkatz6
