### ISSUE TITLE
TextBox: non default aligned text selection issue

### ISSUE THREAD

**Issue by DmitryZhelnin** [AvaloniaUI/Avalonia#1448]
When `TextBox.TextAlignment` is set to `Center` or `Right` and I try to apply text selection the rendering becomes very strange.
![textbox](https://user-images.githubusercontent.com/4993430/37558800-c88fd17e-2a2a-11e8-8b49-b65d002fb7c0.gif)

**Comment by achal7** [comment]
I still sees issues related to text alignments

![text box alignment issue](https://user-images.githubusercontent.com/3909090/38739775-81753714-3f53-11e8-8dea-9735a10a5dcf.gif)

**Comment by Karnah** [comment]
![default](https://user-images.githubusercontent.com/6525732/39891710-bb74ad72-54b7-11e8-88db-ce8d97a0e592.JPG)
In commit bc3d6ec8 still having problem with selected text for CenterAllignment and RightAllignment. 
I have a fix which looks like crutch. In Avalonia.Skia.FormattedTextImpl, method Draw, after string "float x = TransformX(origin.X, 0, paint.TextAlign);" add this:
```
if (paint.TextAlign != SKTextAlign.Left)
{
    var measure = paint.MeasureText(Text);

    x -= paint.TextAlign == SKTextAlign.Center
        ? measure / 2
        : measure;

    paint.TextAlign = SKTextAlign.Left;
}
```
I think problem in canvas.DrawText, when using several brushes

**Comment by DmytroProg** [comment]
Hello everyone! I work with Avalonia 0.10.18 and I face the problem with the text selection behaviour when TextAlignment is set to Center. I cannot change the version. How can I fix this bug?

**Comment by timunie** [comment]
@DmytroProg please do not answer closed issues. 
Meanwhile I highly suggest trying to upgrade to 11.0. Make sure to read upgrade guide carefully.
