### ISSUE TITLE
Avalonia.BuildServices 0.0.30 breaks build 

### ISSUE THREAD

**Issue by marklam** [AvaloniaUI/Avalonia#14497]
## Describe the bug
Updated to Avalonia.BuildServices 0.0.30. now Visual Studio build or command-line `dotnet build` report the error
```
C:\Users\markl\.nuget\packages\avalonia.buildservices\0.0.30\buildTransitive\Avalonia.BuildServices.targets(9,9): error
 MSB4062: The "AvaloniaStatsTask" task could not be loaded from the assembly C:\Users\markl\.nuget\packages\avalonia.bu
ildservices\0.0.30\buildTransitive\\..\tools\netstandard2.0\Avalonia.BuildServices.dll. Bad IL format. The format of th
e file 'C:\Users\markl\.nuget\packages\avalonia.buildservices\0.0.30\tools\netstandard2.0\Avalonia.BuildServices.dll' i
s invalid. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are availabl
e, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [c:\Git\...\....fsproj]
```

## To Reproduce

1. Update Avalonia.BuildServices nuget package
2. dotnet build

## Expected behavior
Built successfully with 0.0.29

## Environment 

- OS: Windows, .net 8
- Avalonia-Version: 11.0.7

**Comment by timunie** [comment]
why and where do you need to reference this package on your own?

**Comment by marklam** [comment]
It's pulled in [as a dependency of Avalonia](https://www.nuget.org/packages/Avalonia.BuildServices#usedby-body-tab).

Then nuget.exe default behaviour is (I believe) to use the oldest allowable version of a dependency, which for Avalonia 11.0.7 is Avalonia.BuildServices 0.0.29.

The paket dependency manager (by default) tries to use the newest allowable version of a dependency , which is Avalonia.BuildServices 0.0.30.

I can work around this by locking Avalonia.BuildServices to 0.0.29, but I thought it best to report it, because there seems to be something wrong with the build task assembly in 0.0.30.

**Comment by timunie** [comment]
probably 0.0.30 is only compatible with 11.1.0 (upcoming). You can verify it by trying nightly builds

**Comment by marklam** [comment]
I tried updating packages such that I'm using:
|Package|Version|
|---|---|
|    Avalonia |11.1.999-cibuild0044452-beta|
|    Avalonia.Angle.Windows.Natives |2.1.22087.20231008|
|    Avalonia.BuildServices |0.0.30|
|    Avalonia.Controls.ColorPicker |11.1.999-cibuild0044452-beta|
|    Avalonia.Controls.DataGrid |11.1.999-cibuild0044452-beta|
|    Avalonia.Desktop |11.1.999-cibuild0044452-beta|
|    Avalonia.Diagnostics |11.1.999-cibuild0044452-beta|
|    Avalonia.FreeDesktop |11.1.999-cibuild0044452-beta|
|    Avalonia.Native |11.1.999-cibuild0044452-beta|
|    Avalonia.Remote.Protocol |11.1.999-cibuild0044452-beta|
|    Avalonia.Skia |11.1.999-cibuild0044452-beta|
|    Avalonia.Themes.Fluent |11.1.999-cibuild0044452-beta|
|    Avalonia.Themes.Simple |11.1.999-cibuild0044452-beta|
|    Avalonia.Win32 |11.1.999-cibuild0044452-beta|
|    Avalonia.X11 |11.1.999-cibuild0044452-beta|

And `dotnet build` produces
```
C:\Users\markl\.nuget\packages\avalonia.buildservices\0.0.30\buildTransitive\Avalonia.BuildServices.targets(9,9): error
 MSB4062: The "AvaloniaStatsTask" task could not be loaded from the assembly C:\Users\markl\.nuget\packages\avalonia.bu
ildservices\0.0.30\buildTransitive\\..\tools\netstandard2.0\Avalonia.BuildServices.dll. Bad IL format. The format of th
e file 'C:\Users\markl\.nuget\packages\avalonia.buildservices\0.0.30\tools\netstandard2.0\Avalonia.BuildServices.dll' i
s invalid. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are availabl
e, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. 
```

**Comment by maxkatz6** [comment]
@marklam please try [0.0.31](https://www.nuget.org/packages/Avalonia.BuildServices/0.0.31)

**Comment by marklam** [comment]
That works, thanks.
