### ISSUE TITLE
AppDomain.CurrentDomain.UnhandledException handlers are not called in 11.0.7 on macOS

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#14493]
## Describe the bug

Handling AppDomain.CurrentDomain.UnhandledException does not work in 11.0.7, it works in 11.0.6

## To Reproduce

Subscribe to AppDomain.CurrentDomain.UnhandledException and throw unhandled  execpetion while running the app.

## Expected behavior

The handler from AppDomain.CurrentDomain.UnhandledException is called.

## Environment 

- OS: macOS 14.2.1
- Avalonia-Version: 11.0.7

**Comment by danwalmsley** [comment]
verified that this 100% works on 11.0.7
