### ISSUE TITLE
It's not possible to restore window position, size and state

### ISSUE THREAD

**Issue by sinatrocious** [AvaloniaUI/Avalonia#14517]
## Describe the bug
No matter where I set window properties, such as `Width`, `Height`, `Position` and `WindowState`, the final values of displayed window properties is rather undeterministic. There is some logic running behind, which alters values I set and I am not yet able to figure it out.

## To Reproduce
1. Create new avalonia desktop application.
2. Try **anywhere** to set:

```c#
WindowState = WindowState.Maximized;
Width = 100;
Height = 100;
Position = new(0, 0);
```
3. Start application and see for youself, that either position or size will not work.

<details>
  <summary>Here are my attempts</summary>

1. In `App.axaml.cs`:

```c#
    public override void OnFrameworkInitializationCompleted()
    {
        if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
        {
            var window = desktop.MainWindow = new MainWindow
            {
                DataContext = new MainViewModel()
            };
            window.WindowState = WindowState.Maximized;
            window.Width = 100;
            window.Height = 100;
            window.Position = new(0, 0);
        }
```

Doesn't work, the window size is wrong. Try to comment `WindowState` line to see expected size.

2. In `MainWindow.axaml.cs`:

```c#
    protected override void OnOpened(EventArgs e)
    {
        WindowState = WindowState.Maximized;
        Width = 100;
        Height = 100;
        Position = new(0, 0);

        base.OnOpened(e);
    }
```

Doesn't work, the window size and position are wrong! Try to comment `WindowState` line to see expected size and position.
</details>

## Expected behavior
I expect to be able to set window state (maximized, minimized or normal), size, position, etc. and have exactly that values, not something different.

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.7

## Additional context
My story begins 9 months ago when I tried to simply save window state and restore it on next start. But this just didn't worked: window shifts after several restarts, the window size or position gets reset... Today I have even more ugly bug (can't reproduce, but it motivate me to write a bug report) where maximized window is not occupying whole screen, but is shifted to the middle  ><

I was waiting for #3387 to be fixed and noticed just today, that it was simply closed. Great. The suggested there workaround to utilize `OnOpened` worked for some time, then stopped working. Then after I changed the order of setting properties (window state before position/size) it was working again and today everything stops working another time and I have ugly maximized window which is not maximized. ><

So I tried to reproduce the bug and it was too easy ><

Perhaps I am doing something wrong? Then show me, I'll refer to your attempt in my next bug report, when this thing stops working again =)

**Comment by timunie** [comment]
@sinatrocious I cannot reproduce it or I am not able to understand what you expect. Please file a minimal sample attached. Thx.

**Comment by stevemonaco** [comment]
I can't seem to set both `WindowState` and Width/Height/Position during the same "resizing operation". You also can't seem to set Width/Height/Position while the WindowState is Maximized and have it remember. Would take some digging to figure out if Avalonia is using `SetWindowLong`, `SetWindowPos`, or `SetWindowPlacement` and read through the win32api docs to see what's to blame.

The least number of resize operations I can get at startup and still have memory is using both `OnFrameworkInitializationCompleted` and `OnLoaded`:

```cs
public override void OnFrameworkInitializationCompleted()
{
    if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
    {
        desktop.MainWindow = new MainWindow
        {
            DataContext = new MainWindowViewModel(),
            WindowStartupLocation = Controls.WindowStartupLocation.Manual,
            Position = new(0, 0),
            Width = 100,
            Height = 100
        };
    }

    base.OnFrameworkInitializationCompleted();
}
```
```cs
protected override void OnOpened(EventArgs e)
{
    base.OnOpened(e);
    WindowState = WindowState.Maximized;
}
```

Alternatively, if you need this to happen in one spot, you can use the Dispatcher at (I think) the cost of an extra window resizing operation:
```cs
protected override void OnOpened(EventArgs e)
{
    base.OnOpened(e);

    Width = 100;
    Height = 100;
    Position = new(0, 0);

    Dispatcher.UIThread.Post(() =>
    {
        WindowState = WindowState.Maximized;
    });
}
```

**Comment by timunie** [comment]
would this PR fix that issue? https://github.com/AvaloniaUI/Avalonia/pull/14470

**Comment by sinatrocious** [comment]
@stevemonaco, thanks for digging a new solution for me. In WPF I often need to use dispatcher-invoke-trick, so I am ok with invoking `WindowState`:

```c#
    public override void OnFrameworkInitializationCompleted()
    {
        if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
        {
            var window = desktop.MainWindow = new MainWindow
            {
                DataContext = new MainViewModel()
            };

            window.Width = 100;
            window.Height = 100;
            window.Position = new(0, 0);

            Dispatcher.UIThread.InvokeAsync(() =>
            {
                window.WindowState = WindowState.Maximized;
            });
        }
    }
```

@timunie
> would this PR fix that issue? #14470

Not sure. `WindowState.Minimized` causes same issue and can be fixed similarly.

**Comment by TomEdwardsEnscape** [comment]
Yesterday I rewrote #14470 to entirely change the way in which a window's restored size is set, including for maximised windows. Please test with the PR again, if you tried it earlier.

**Comment by sinatrocious** [comment]
@TomEdwardsEnscape, I can report bugs, but I am unable to test PRs, sorry.

**Comment by timunie** [comment]
> I can report bugs, but I am unable to test PRs, sorry.

Why?

**Comment by maxkatz6** [comment]
Let me know if this issue is still reproducible.

**Comment by sinatrocious** [comment]
@maxkatz6, just tried with 11.1.0, the issue is not reproducable anymore.
