### ISSUE TITLE
AXN0002 Unable to resolve type FluentTheme from namespace https://github.com/avaloniaui

### ISSUE THREAD

**Issue by Alex-1347** [AvaloniaUI/Avalonia#14544]
I have ancient workable XAML application what I need upgrade to current NET 8.0 version
Application look as

     <Application xmlns="https://github.com/avaloniaui"
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 x:Class="My.Visualiser.App">
          <Application.Styles>
              <FluentTheme Mode="Light"/>
          </Application.Styles>
     </Application>

Unfortunately I can not found package like Avalonia.Themes.Fluent. I try install Avalonia.Themes.Simple and replace tag FluentTheme to SimpleTheme - but this is not solve this issue, project still can not compiled. What I need to do?

**Comment by rabbitism** [comment]
https://docs.avaloniaui.net/docs/stay-up-to-date/upgrade-from-0.10#theme-handling

please check this doc

**Comment by Alex-1347** [comment]
@rabbitism Very thanks, I delete Mode attribute, and install Avalonia.Themes.Simple, but still receive issue.      
This is not exactly my project, customer want just upgraded it to current .NET 8.0 version. 
And this project working fine on NET Core 3.1      
What I need more?  

![Game-02082024_192947](https://github.com/AvaloniaUI/Avalonia/assets/81580242/7123b8ff-485a-456d-aa81-58ed66aab6d0)

**Comment by workgroupengineering** [comment]
https://www.nuget.org/packages/Avalonia.Themes.Fluent/11.0.7

**Comment by Alex-1347** [comment]
thank you, @workgroupengineering  finally my project started.

**Comment by timunie** [comment]
@Alex-1347 next time pls use Discussions or Telegram for questions. Thx.
