### ISSUE TITLE
Rendering stop when the window closed

### ISSUE THREAD

**Issue by Coloryr** [AvaloniaUI/Avalonia#14540]
## Describe the bug
Rendering stop when the window closed.
this issue in 11.0.8

## To Reproduce

1. open a window A
2. open a window B
3. close window B
4. window A rendering stop

## Expected behavior
window A rendering.

## Screenshots
11.0.8

https://github.com/AvaloniaUI/Avalonia/assets/26276037/386caae4-ec6a-47ef-82ec-fe99db294e1a

11.0.7

https://github.com/AvaloniaUI/Avalonia/assets/26276037/e3a5fa2c-46e9-4b76-a5d2-3e0b8163a707

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.8

## Additional context
no issue in 11.0.7

**Comment by maxkatz6** [comment]
Can you check Avalonia logs?

**Comment by Coloryr** [comment]
> Can you check Avalonia logs?

where is `Avalonia logs`?

**Comment by Coloryr** [comment]
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/e8595c00-e4ea-455a-bf15-6a068cd291fb)

**Comment by Coloryr** [comment]
main thread over?
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/7166d160-7dbe-4dd9-8330-ad58ceb5e37c)

**Comment by maxkatz6** [comment]
If main thread is over, then first window should be closed as well, as process is ended. 

Do you have a minimal project to reproduce this issue?

**Comment by Coloryr** [comment]
I try write a minimal project now.

**Comment by Coloryr** [comment]
Here, i found it
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/7b83f605-47d7-412c-b009-c4ce11a8d318)

**Comment by Coloryr** [comment]
After setting the `IClassicDesktopStyleApplicationLifetime.MainWindow`, it works well
