### ISSUE TITLE
Bad gateway Error code 502 for https://nuget.avaloniaui.net/

### ISSUE THREAD

**Issue by angulion** [AvaloniaUI/Avalonia#14549]
NuGet repsitory is returning 502 Bad Gateway (Cloudflare)

Time on error-page is: 2024-02-08 20:22:02 UTC

**Comment by maxkatz6** [comment]
https://nuget-feed-nightly.avaloniaui.net/
https://nuget-feed-all.avaloniaui.net/

**Comment by kekekeks** [comment]
The feed was hosted via sonatype nexus that decided to eat like 16GB of ram to serve it. Since it wasn't being updated for quite a while, we've disabled it.

**Comment by angulion** [comment]
Trying a dotnet restore on AvaloniaEdit still just yields same
... : error NU1301: Unable to load the service index for source https://nuget.avaloniaui.net/repository/avalonia-all/index.json.

**Comment by kekekeks** [comment]
Again, https://nuget.avaloniaui.net is disabled.

**Comment by kekekeks** [comment]
Probably need to remove those: https://github.com/AvaloniaUI/AvaloniaEdit/blob/master/NuGet.config#L6-L7
They are no longer needed.

**Comment by angulion** [comment]
> Probably need to remove those: https://github.com/AvaloniaUI/AvaloniaEdit/blob/master/NuGet.config#L6-L7 They are no longer needed.

Confirming that that resolves the issue.
