### ISSUE TITLE
Avalonia 11.0.8 break Menu in Linux

### ISSUE THREAD

**Issue by isergvb** [AvaloniaUI/Avalonia#14554]
## Describe the bug
After upgrade from Avalonia `11.0.7` to `11.0.8` Menu popup position is broken.
The Submenu doesn't show up at all. Also Menu transparency disappeared.

## To Reproduce
Create the Menu and MenuItems in .axaml
```xml
..
        <Menu>
            <MenuItem Header="_File">
                <MenuItem Header="_Open..."/>
                <Separator/>
                <MenuItem Header="_Exit"/>
            </MenuItem>
..
        </Menu>
..
```

## Expected behavior
Like in `11.0.7`

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/6366933/753a79fe-92de-48d6-8414-d420ce28e2d9)

## Environment
- OS: Linux Ubuntu 20.04 amd64, Astra Linux, +nvidia
- Avalonia-Version: `11.0.8`
- net7.0, net6.0

## Additional context
`11.0.7` works great

**Comment by jp2masa** [comment]
The position issue should be fixed by #14551. I don't know about transparency, though.

**Comment by maxkatz6** [comment]
Fixed by #14551 

Let me know if transparency issue is still there. But I would expect it to work properly with fixed popup parents.

**Comment by IsaacMarovitz** [comment]
@maxkatz6 Transparency issue remaines

**Comment by ThePBone** [comment]
Apart from the transparency issue, Menus are now also cut off at the window border: https://github.com/AvaloniaUI/Avalonia/issues/14568

**Comment by HendrikMennen** [comment]
Can confirm this, noticed after upgrade too. Submenu doesnt show up after 11.0.8
