### ISSUE TITLE
[X11] Menu regression in 11.0.8 and 11.0.9

### ISSUE THREAD

**Issue by ThePBone** [AvaloniaUI/Avalonia#14568]
## Describe the bug

Two issues with menus on X11 popped up since Avalonia 11.0.8 (also present in 11.0.9):
* Borders and rounded corners of menus are transparent and show the background behind the root window
* Menus are cut off and only drawn within the root window's bounds

## To Reproduce

1. Build the 'ControlCatalog.NetCore' sample project
2. Go to 'Menu' and open a menu

## Expected behavior
* The borders/corners of the menu should not show the background behind the root window
* Menus should not get cut off at the border of the root window

## Screenshots

ControlCatalog:
![image](https://github.com/AvaloniaUI/Avalonia/assets/38386967/fb41f8e9-2770-462a-8422-e4414b43446c)

In my app, it's much more noticeable due to the rounded corners: 
![image](https://github.com/AvaloniaUI/Avalonia/assets/38386967/0702788e-9836-4ef0-b324-7956bcba748c)

## Environment 

- OS: Arch Linux X11
- Avalonia-Version: 11.0.9

## Additional context
* Avalonia 11.0.7 worked fine
* Possible cause: #14366

**Comment by curvedspace** [comment]
I see a similar effect on tooltips with Linux.

**Comment by dc740** [comment]
wayland is also affected:
https://github.com/sn4k3/UVtools/issues/836#issuecomment-1949546997

UVtools had to downgrade to 11.0.7 to get it to work again.

**Comment by kekekeks** [comment]
Need to release 11.0.10 with that revered PR.

**Comment by ThePBone** [comment]
Fixed by https://github.com/AvaloniaUI/Avalonia/releases/tag/11.0.10
