### ISSUE TITLE
CanExecute in non-reactive binding does not work.

### ISSUE THREAD

**Issue by huestack** [AvaloniaUI/Avalonia#14572]
## Describe the bug
CanExecute method does not work when binding a Button's command directly with ViewModel's method. I am following this tutorial:
https://docs.avaloniaui.net/docs/guides/data-binding/how-to-bind-to-a-command-without-reactiveui

View:
```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:vm="clr-namespace:TestApp.ViewModels.Settings"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="TestApp.Views.TestView"
             x:DataType="vm:TestViewModel">
    <StackPanel>
        <ComboBox ItemsSource="{Binding Values}" SelectedItem="{Binding Value}" />
        <Button Command="{Binding Save}">Save</Button>
    </StackPanel>
</UserControl>
```

ViewModel:

```
public sealed class TestViewModel : ViewModelBase
{
    public void Save(object _)
    {
        //
    }

    public bool CanSave(object _)
    {
        return Value > 0;
    }
    
    public int[] Values { get; } = [0, 10, 20, 40];
    
    private int _value;
    public int Value
    {
        get => _value;
        set => this.RaiseAndSetIfChanged(ref _value, value);
    }
}
```

## Expected behavior
The Button must be enabled when selected dropdown value is more than 0. CanSave method remains uncalled.

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/11208563/bebec4fa-f025-445c-8647-2b3a1904d4c9)

## Environment 

- OS: Windows 2019
- Avalonia-Version: 11.0.7

**Comment by workgroupengineering** [comment]
You missing to read [this](https://docs.avaloniaui.net/docs/guides/data-binding/how-to-bind-to-a-command-without-reactiveui#trigger-can-execute). 

For trigger it, you should add code like this in your vm

```c#
public sealed class TestViewModel : ViewModelBase
{
    public void Save(object _)
    {
        //
    }

    [DependsOn(nameof(Value))]
    public bool CanSave(object _)
    {
        return Value > 0;
    }
    
    public int[] Values { get; } = [0, 10, 20, 40];
    
    private int _value;
    public int Value
    {
        get => _value;
        set => this.RaiseAndSetIfChanged(ref _value, value);
    }
}
```

**Comment by maxkatz6** [comment]
Yes, DependsOn attribute is mandatory, when you bind to methods. Otherwise, there is no way for Avalonia to know if CanSave should be executed again.

**Comment by huestack** [comment]
@workgroupengineering @maxkatz6 
Thanks for the help, guys. Sorry for the trouble.

Just tested, and found that for use of multiple values in `Can` method, we can add more `DependsOn` attribute.
