### ISSUE TITLE
TemplateBinding throws an exception when used in a Selector in the ControlTheme

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#14576]
## Describe the bug

XamlX throws `Unable to cast object of type 'XamlX.Ast.SkipXamlValueWithManipulationNode' to type 'XamlX.Ast.IXamlAstPropertyReference'.`

### Stack

```
10:31:07.792 [Error] 9076 UpdateXamlResult error
System.Xaml.XamlException: Unable to cast object of type 'XamlX.Ast.SkipXamlValueWithManipulationNode' to type 'XamlX.Ast.IXamlAstPropertyReference'.
10:31:31.176 [Information] 9076 Stopping previewer process
10:31:31.177 [Information]  Process exited
10:31:31.177 [Information]  Stopping previewer process
10:32:25.478 [Information]  Started AvaloniaDesigner.CreateCompletionMetadataAsync() for "C:\GitHub\Avalonia\samples\Sandbox\obj\Debug\net6.0\Avalonia\references"
10:32:25.479 [Information]  Starting previewer process for '"C:\GitHub\Avalonia\samples\Sandbox\bin\Debug\net6.0\Sandbox.dll"'
10:32:25.483 [Information] 24432 Started previewer process for '"C:\GitHub\Avalonia\samples\Sandbox\bin\Debug\net6.0\Sandbox.dll"'. Waiting for connection to be initialized.
10:32:25.926 [Information] 24432 Connection initialized
10:32:27.424 [Error] 24432 UpdateXamlResult error
System.Xaml.XamlException: Unable to cast object of type 'XamlX.Ast.SkipXamlValueWithManipulationNode' to type 'XamlX.Ast.IXamlAstPropertyReference'.
``` 

## To Reproduce

Add folowing xaml

```xaml
  <ControlTheme x:Key="{x:Type NumericUpDown}"
                TargetType="NumericUpDown">
        ....
        <Style Selector="^[ButtonSpinnerLocation=Left] /template/ TextBox#PART_TextBox">
          <Setter Property="InnerRightContent" Value="{TemplateBinding InnerContent}"/>
        </Style>

        <Style Selector="^[ButtonSpinnerLocation=Right] /template/ TextBox#PART_TextBox">
          <Setter Property="InnerLeftContent" Value="{TemplateBinding InnerContent}"/>
        </Style>
  </ControlTheme>
```

## Environment 

- OS: **Any**
- Avalonia-Version: **ffff19e6f0d89cd1a8ffa48dd5063a0500512022**

## Additional context

if change like this works:

```xaml
  <ControlTheme x:Key="{x:Type NumericUpDown}"
                TargetType="NumericUpDown">
        ....
    <Style Selector="^[ButtonSpinnerLocation=Left] /template/ TextBox#PART_TextBox">
      <Setter Property="InnerRightContent" Value="{Binding InnerContent, RelativeSource={RelativeSource TemplatedParent}}"/>
    </Style>

    <Style Selector="^[ButtonSpinnerLocation=Right] /template/ TextBox#PART_TextBox">
      <Setter Property="InnerLeftContent" Value="{Binding InnerContent, RelativeSource={RelativeSource TemplatedParent}}"/>
    </Style>
  </ControlTheme>
```

**Comment by timunie** [comment]
TemplateBinding is more limited than Binding for performance reasons. I believe this is by design and if it's not enough, you need to fall back to a normal Binding (like you did already). Note, you are outside ControlTemplate here. I agree that the error message could be improved.

**Comment by maxkatz6** [comment]
There should be another warning or an error before this one.

**Comment by maxkatz6** [comment]
I also can't reproduce this issue by adding InnerContent property and these setters.

**Comment by workgroupengineering** [comment]
> TemplateBinding is more limited than Binding for performance reasons. I believe this is by design and if it's not enough, you need to fall back to a normal Binding (like you did already). Note, you are outside ControlTemplate here. I agree that the error message could be improved.

Then this shouldn't have worked either `{Binding InnerContent, RelativeSource={RelativeSource TemplatedParent}}` but only

`{Binding InnerContent, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type NumericUpDown}}}`



> I also can't reproduce this issue by adding InnerContent property and these setters.

I attach a modified SandBox that simulates the problem

[Sandbox.zip](https://github.com/AvaloniaUI/Avalonia/files/14237873/Sandbox.zip)
