### ISSUE TITLE
Wrong cursor type on macOS

### ISSUE THREAD

**Issue by JacobCZ** [AvaloniaUI/Avalonia#14597]
## Describe the bug
Setting a cursor on a control to `StandardCursorType.DragMove` on macOS results in that control having the incorrect cursor type (expected cursor type: move, actual cursor type: copy; see attached pictures)

## To Reproduce

1. Define a control in your AXAML (e.g. a Rectangle)
2. Set the cursor to `StandardCursorType.DragMove` (e.g. `YourControl.Cursor = new Cursor(StandardCursorType.DragMove);`)
3. Run your app and hover over the control

## Expected behavior
The cursor is the correct type.

## Screenshots

Expected cursor:
![move](https://github.com/AvaloniaUI/Avalonia/assets/1533848/5dd5afd9-6d9c-4a6c-9673-65e66cb1d46e)

Actual cursor:
![copy](https://github.com/AvaloniaUI/Avalonia/assets/1533848/e130a1bb-99a8-4c5f-bc8e-c657fd83b48f)

## Environment

- OS: macOS 14.3
- Avalonia-Version: 11.0.6

**Comment by timunie** [comment]
if anyone wants to pick this up, I believe it needs to be set here: https://github.com/AvaloniaUI/Avalonia/blob/master/native/Avalonia.Native/src/OSX/cursor.mm

**Comment by TonyHenrique** [comment]
Perhaps on [this code line](https://github.com/AvaloniaUI/Avalonia/blob/0c0d4497ef156aa6defaa4cce05fac5831576dd4/native/Avalonia.Native/src/OSX/cursor.mm#L39) it should be The open-hand cursor (openHand) ?

The following page shows and describes the system cursors: https://developer.apple.com/documentation/appkit/nscursor
