### ISSUE TITLE
Checkbox is checked on mouse release

### ISSUE THREAD

**Issue by DmitryZhelnin** [AvaloniaUI/Avalonia#1459]
If you have a `DropDown` and its popup covers a `Checkbox` so when you select an item `CheckBox`'s `IsChecked` state will be changed.
Alternatively you can press mouse button outside the `CheckBox`, move the cursor to the `CheckBox` and release the button.

![checkbox](https://user-images.githubusercontent.com/4993430/37684283-9bc8d712-2ca0-11e8-96ef-318411ed915e.gif)

**Comment by grokys** [comment]
Fixed by #1492
