### ISSUE TITLE
OpenFileDialog returns null if more than ~12 files are selected

### ISSUE THREAD

**Issue by plule** [AvaloniaUI/Avalonia#1460]
Platform: Windows 10, Avalonia 0.6.1

Hello! Given an OpenFileDialog initialized with AllowMultiple:
```
OpenFileDialog ofd = new OpenFileDialog(); 
ofd.AllowMultiple = true; 
 
string[] files = await ofd.ShowAsync(VisualRoot as Window); 
```
The OpenFileDialog returns null when selecting more than ~12 files, which is very limiting.

I don't know much about the Windows API, but looking at [SystemDialogImpl](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/SystemDialogImpl.cs), this is probably coming from the 256 chars buffer. On Linux/Gtk3, the issue did not appear or the limit is bigger.

Maybe with AllowMultiple this buffer should be made far larger, or the API could expose this as a property?

**Comment by Sorien** [comment]
there is returned error FNERR_BUFFERTOOSMALL 0x3003 from CommDlgExtendedError

as i found out there is just one way how to prevent this
https://cboard.cprogramming.com/windows-programming/135115-avoiding-fnerr_buffertoosmall.html

**Comment by plule** [comment]
Right, it seems that the proposed solutions are:
 - Use the returned size to call the method again, and it seems that it reopens the dialog, not acceptable?
 - Use a large buffer

Windows default is 260 characters, in Avalonia 256 characters are used which is the minimum size according to [the documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646839(v=vs.85).aspx). It seems to me that sparing 100ko here would cover most cases and be negligible in term of memory usage (a normal application displays at most one file dialog at the same time).

I might submit a pull request for this, but before I have to learn how to build Avalonia...

**Comment by Sorien** [comment]
probably it should be done same way as its done in .net
https://referencesource.microsoft.com/#PresentationFramework/src/Framework/Microsoft/Win32/FileDialog.cs,779

**Comment by plule** [comment]
You're right that's the way to go, I also did not read well your first link that also dynamically resize the buffer.

**Comment by plule** [comment]
@CommonGuy Thank you for the fix!
