### ISSUE TITLE
In WindowBase.PositionChanged event handler Point value is wrong

### ISSUE THREAD

**Issue by sinatrocious** [AvaloniaUI/Avalonia#14604]
## Describe the bug
The value of `PixelPointEvenArgs.Point` inside event handler is wrong.

## To Reproduce

1. Create new Avalonia C# project.
2. In `MainWindow.axaml.cs` add line in constructor to output argument value and actual value:

```c#
    public MainWindow()
    {
        InitializeComponent();
        PositionChanged += (s, e) => Debug.WriteLine($"Position={e.Point}, actual={Position}");
        //Position = new(666, 666); // optional
    }
```

3. Run and observe debugger "Output" window.
4. My outputs are

```
Position=190, 213, actual=188, 182
or
Position=668, 697, actual=666, 666
```

## Expected behavior
I expect `e.Point` value to be equal to actual window `Position`.

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.9

## Additional context
I tried to use `PositionChanged` event to store position of window in normal state, see #14517 ,but unfortunately discovered a new frustrating bug in Avalonia.

**Comment by TomEdwardsEnscape** [comment]
Looks like `Position` is considered the position of the client area in some places, and the position of the window frame in others.

**Comment by TomEdwardsEnscape** [comment]
Maximising the window reveals that `e.Point` is the location of the client area, but `Position` is the location of the whole window including its frame.

```
Position=0, 23, actual=-1, -8
```

The raw value that comes from GetWindowRect is `-8, -8`. [An attempt is being made](https://github.com/AvaloniaUI/Avalonia/blob/e35e94902eb4eef415e205fa0ca7e911ac2aa2f4/src/Windows/Avalonia.Win32/WindowImpl.cs#L514-L517) to counteract [the window's drop shadow](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowrect#remarks), but it doesn't seem to be working very well.

What should the `Position` property really represent? The client area? The window frame? (I think we can discard the option of the window frame including drop shadow.)

**Comment by maxkatz6** [comment]
cc @emmauss
