### ISSUE TITLE
`TabControl` does not respect initial value of `SelectedValue`

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#14624]
Paste this XAML into any window and execute it:

```xaml
<StackPanel>
	<ListBox SelectedValue="{Binding $self.Tag}" Tag="World" SelectedValueBinding="{Binding Content}">
		<ListBoxItem Content="Hello"/>
		<ListBoxItem Content="World"/>
	</ListBox>
	<TabControl SelectedValue="{Binding $self.Tag}" Tag="World" SelectedValueBinding="{Binding Header}">
		<TabItem Header="Hello"/>
		<TabItem Header="World"/>
	</TabControl>
</StackPanel>
```

You will see that the `ListBox` has selected "World" as expected, but the `TabControl` has selected "Hello" instead.

![image](https://github.com/AvaloniaUI/Avalonia/assets/109803929/53112089-faeb-4ed6-874e-d35c0540ab70)

Inspecting the logical tree shows that `TabControl.Tag` has been incorrectly changed to "Hello".

## Expected behavior
The `TabControl` should start a `SelectedValue` of "World" and the second tab item should be selected.

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.9

**Comment by timunie** [comment]
Maybe you need to set DataContext also to $self? Inspect with DevTools maybe the current DataContext of TabControl.

**Comment by TomEdwardsEnscape** [comment]
There is no DataContext at all in this sample.
