### ISSUE TITLE
Wrong titlebar color in dark mode on Windows 10

### ISSUE THREAD

**Issue by autodotua** [AvaloniaUI/Avalonia#14642]
## Describe the bug
The titlebar color in dark mode in Windows 10 is still white, but it works well on Windows 11.

## To Reproduce

1. Set to dark mode in Windows Settings
2. Create a new avalonia application with a window
3. try to run on Windows 10 and Windows 11

## Expected behavior
There should be dark title bar in dark mode on both Windows 10 and Windows 11

## Screenshots

On Windows 10:
![image](https://github.com/AvaloniaUI/Avalonia/assets/26277009/9f238fc8-78e4-4636-8835-25777760a1e1)

On Windows 11:
![image](https://github.com/AvaloniaUI/Avalonia/assets/26277009/b573cda9-2b8a-4678-a7a0-b658f85ba41e)

## Environment 

- OS: Windows10
- Avalonia-Version: 11.0.9

**Comment by maxkatz6** [comment]
Windows 10 **does not** support dark window mode for win32 applications. Only for UWP/MS-Store applications.

Official and documentated API to change window decorations color was added only in windows 11 22000 - DWMWA_USE_IMMERSIVE_DARK_MODE attribute https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute

Alternatively, you can use undocumented Windows APIs on your own risk, or you can use custom rendered titlebar.

**Comment by autodotua** [comment]
> Windows 10 **does not** support dark window mode for win32 applications. Only for UWP/MS-Store applications.
> 
> Official and documentated API to change window decorations color was added only in windows 11 22000 - DWMWA_USE_IMMERSIVE_DARK_MODE attribute https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
> 
> Alternatively, you can use undocumented Windows APIs on your own risk, or you can use custom rendered titlebar.

Thank you for your reply. I decided to use the custom rendered titlebar.
