### ISSUE TITLE
Avalonia control embedded in windows forms shows chrome

### ISSUE THREAD

**Issue by Basnederveen** [AvaloniaUI/Avalonia#14640]
When embedding an Avalonia user control in a windows forms application using the WinFormsAvaloniaControlHost class, the chrome shows. Since it is a user control I would expect no chrome or some way of controlling the chrome.

## Reproduction steps
1. Clone repo: https://github.com/Basnederveen/WinFormsAvaloniaHost
2. Run the windows forms project.

## Expected behavior
Not seeing a chrome, being able to dock the control in its parent container.

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/16050771/06941501-f5f9-449e-b414-20f17619027d)
![image](https://github.com/AvaloniaUI/Avalonia/assets/16050771/09616201-7dd9-44bf-8f33-da8654bea6d2)

## Environment 
- OS: Windows 11

**Comment by maxkatz6** [comment]
Looks like a regression.

**Comment by Basnederveen** [comment]
I've looked in the source code and the problem is being caused by:

The _windowProperties property must be overridden in Avalonia.Win32.EmbeddedWindowImpl. 

This is the base class 'WindowImpl': 

![image](https://github.com/AvaloniaUI/Avalonia/assets/16050771/1f3c27ce-4daf-4d2f-ae10-8c5a767018a1)

Overriding it in EmbeddedWindowImpl fixes the problem.

![image](https://github.com/AvaloniaUI/Avalonia/assets/16050771/dcfa6ccc-64ca-4cd0-9e73-8ab3ab0239d8)

It will be my first, but will try to create a PR
