### ISSUE TITLE
Minor issues with documentation

### ISSUE THREAD

**Issue by kunjee17** [AvaloniaUI/Avalonia#1467]
There seems to be some minor issues with documentation.  I couldn't find where to change it, so I am filling issue instead of PR. Hope that is ok.

On home page quick start link is hitting 404. Quick start link should be `http://avaloniaui.net/guides/quickstart` instead of `http://avaloniaui.net/guide/quickstart.html`

On quick start page. Installing templates command seems to be wrong. It should be `dotnet new -i Avalonia.Templates.NetCore` instead of `dotnet install -i Avalonia.Templates.NetCore`.

**Comment by kunjee17** [comment]
I tried with new command but seems that Template name is changed to not available anymore. It would be great to update Getting Started Guide with details.

**Comment by jmacato** [comment]
Already addressed over @ https://github.com/AvaloniaUI/avaloniaui.net/pull/21
