### ISSUE TITLE
ComboBox dropdown gets cutoff by the parent window (regression in 11.0.9)

### ISSUE THREAD

**Issue by hhyyrylainen** [AvaloniaUI/Avalonia#14685]
## Describe the bug
When a combobox dropdown is opened, it is now cutoff by the parent window it is in. This used to work in 11.0.7 fine.

I'll also note that I tested 11.0.8, but in it the dropdown didn't render at all so whatever the fix made for that in 11.0.9 doesn't fully work it seems.

## To Reproduce

1. Create a non-fullscreen window with a ComboBox in it that has a reasonable number of options
2. Run the program
3. Click on the ComboBox
4. See that the popup to select the active item is clipped by the parent window

## Expected behavior
I expect that the dropdown wouldn't be clipped by the parent window (or that the dropdown would be positioned over the window so that it doesn't get clipped due to this bug).

## Screenshots

When using 11.0.9:
![Kuvakaappaus - 2024-02-21 14-50-54](https://github.com/AvaloniaUI/Avalonia/assets/3796411/b675c036-d1ce-4ed7-b3d1-039d6de28e95)

The exact same program (I just swapped Avalonia package reference versions) running with Avalonia 11.0.7 where the bug doesn't happen:
![Kuvakaappaus - 2024-02-21 14-56-44](https://github.com/AvaloniaUI/Avalonia/assets/3796411/e89129f2-613d-4731-9c6b-db68c21bccec)

## Environment 

- OS: Linux (Fedora 39), also happens in Flatpak environment (org.freedesktop.Platform:23.08). Both are when using Wayland.
- Avalonia-Version: 11.0.9

**Comment by rabbitism** [comment]
Known issue and fixed in https://github.com/AvaloniaUI/Avalonia/pull/14573

**Comment by hhyyrylainen** [comment]
Good to know that there is a fix coming. I didn't find any discussions related to this, but then again I only checked open and recently closed issues.
