### ISSUE TITLE
Fields created for named resources have no values assigned

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#14693]
Paste the following XAML into any window:

``` xaml
<Window.Resources>
	<Panel Name="MyPanel" x:Key="MyPanel"/>
</Window.Resources>
```

Then execute the following code in its constructor:

``` C#
InitializeComponent();
Debug.Assert(MyPanel != null);
```

The assertion will fail.

## Expected behavior
Either no field is created for `MyPanel`, or the field is correctly populated by `InitializeComponent`.

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.9

**Comment by maxkatz6** [comment]
Resources are deferred, and I suppose it's not registered in the namescope until somebody accesses it by key once:
![image](https://github.com/AvaloniaUI/Avalonia/assets/3163374/57c05d34-698d-4caf-903e-817060b699ae)

**Comment by maxkatz6** [comment]
Also, from DeferredTransformationFactoryV2 implementation, it always uses ChildNameScope for deferred content, so it's not even populated back into the parent one, which makes sense.

I suppose the easiest and still reasonable fix would be to disable deferred resources, if they have x:Name on them.
