### ISSUE TITLE
Changing visibility of DataGridColumns causes "DataGridColumnHeader:nth-last-child(1)" to act unexepectedly

### ISSUE THREAD

**Issue by mb-luwi** [AvaloniaUI/Avalonia#14695]
## Describe the bug
When changing IsVisible to "false" on the second last visible column the selector for `DataGridColumnHeadersPresenter DataGridColumnHeader:nth-last-child(1)`, and when change IsVisible to "false" on third, fourth etc. the style that should be applied to the last child is applied to the 2nd last child.
Before:
![image](https://github.com/AvaloniaUI/Avalonia/assets/160882577/e204538f-5b8f-4c02-8345-3dea18e4cb2f)

After turning of Col1:
![image](https://github.com/AvaloniaUI/Avalonia/assets/160882577/02178924-38d9-4544-9aaa-880f171237f4)

Or if you instead turn of Col0:
![image](https://github.com/AvaloniaUI/Avalonia/assets/160882577/f15c81df-cbe8-441a-bd08-c6cebefadfc5)

## To Reproduce
Example code, axaml:
```
<UserControl.Styles>
	<Style Selector="DataGridColumnHeadersPresenter DataGridColumnHeader:nth-last-child(1) ContentPresenter">
		<Setter Property="Background" Value="Red"/>
	</Style>
</UserControl.Styles>
<Grid Background="Wheat">
	<DataGrid>
		<DataGrid.Columns>
			<DataGridTextColumn Header="Col0" Width="*" IsVisible="{Binding ShowCol0}"/>
			<DataGridTextColumn Header="Col1" Width="*" IsVisible="{Binding ShowCol1}"/>
			<DataGridTextColumn Header="Col2" Width="*" IsVisible="{Binding ShowCol2}"/>
			<DataGridTextColumn Header="Col3" Width="*" IsVisible="{Binding ShowCol3}"/>
		</DataGrid.Columns>
	</DataGrid>
	<ToggleButton IsChecked="{Binding ShowCol0}" Content="Col0"/>
	<ToggleButton IsChecked="{Binding ShowCol1}" Margin="50" Content="Col1"/>
	<ToggleButton IsChecked="{Binding ShowCol2}" Margin="100" Content="Col2"/>
	<ToggleButton IsChecked="{Binding ShowCol3}" Margin="150" Content="Col3"/>
</Grid>
```
ViewModel:
```
    [Reactive] public bool ShowCol0 { get; set; } = true;
    [Reactive] public bool ShowCol1 { get; set; } = true;
    [Reactive] public bool ShowCol2 { get; set; } = true;
    [Reactive] public bool ShowCol3 { get; set; } = false;
```

Change ShowCol1 or ShowCol0 to false to reproduce their respective problems.

## Expected behavior
The last item should always be seen and be the one with red.

- OS: Windows 11, tried on desktop and web
- Avalonia-Version: 11.0.9

**Comment by appel1** [comment]
In `DataGrid.OnInsertedColumn_PreNotification` the new column is inserted, `InsertDisplayedColumnHeader`, before `EnsureHorizontalLayout`. 

The call to `InsertDisplayedColumnHeader` leads to `DataGridColumnHeadersPresenter.InvalidateChildIndex` that uses `DataGridColumnCollection._columnsMap` but it is not yet updated because it is updated in `EnsureVisibleEdgedColumnsWidth` called by `EnsureHorizontalLayout`.
