### ISSUE TITLE
Cannot bind to explicitly-implemented interface properties

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#14709]
Avalonia's binding system does not understand explicit interface implementations. Even if you tell it to cast to the interface type, it won't be able to find explicitly-implemented properties.

## To Reproduce

Create this class:

``` C#
public class VM : INamed
{
    string? INamed.Name => "Bob";
}
```

Now insert this XAML into a window, and assign an instance of the `VM` class as the `DataContext`:

``` xaml
<StackPanel>
	<TextBlock x:DataType="INamed" Text="{Binding Name}"/>
	<TextBlock Text="{Binding $self.((INamed)DataContext).Name}"/>
</StackPanel>
```

When opening the window, no text will be displayed. These errors will be logged:

```
[Binding]Error in binding to 'Avalonia.Controls.TextBlock'.'Text': 'Could not find a matching property accessor for 'Name' on 'AvaloniaApplication1.VM''(TextBlock #20084682)
[Binding]Error in binding to 'Avalonia.Controls.TextBlock'.'Text': 'Could not find a matching property accessor for 'Name' on 'AvaloniaApplication1.VM''(TextBlock #46544415)
```

Worse still, if the class so happens to have a public property with the same name as the interface property (e.g. `public string Name => "Alice";`), then this value will incorrectly be displayed.

## Expected behavior
If the property path has been explicitly declared as / cast to an interface type, Avalonia should use the CLR interface map to find properties to bind to. `PropertyChanged` events for such properties should trigger re-evaluation as for public properties.

In the sample above, both `TextBox`es should display "Bob".

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.9

**Comment by timunie** [comment]
probably worth to check nightly (Binding refractor *may* have changed things here)

**Comment by TomEdwardsEnscape** [comment]
Excellent point, the bindings do indeed work on master. Closing this issue.
