### ISSUE TITLE
Android: Skipping Frames, not responding, no focus after coming from standby

### ISSUE THREAD

**Issue by inf9144** [AvaloniaUI/Avalonia#1470]
Hello,
i am developing an App with your Framework and am really happy with it - under windows everything i tested runs really problemless.

I run this app now under Android and have a few problems:
- When you rotate the application redraws in original orientation and then after seconds it redraws with the new size. Feels unresponsive while it does so. I added ConfigurationChanges = ConfigChanges.ScreenLayout | ConfigChanges.ScreenSize | ConfigChanges.Orientation) to MainActivity.

- When you turn off and on / lock and unlock the phone and press something the debugger yields: 
 Dropping event due to no window focus: MotionEvent
 Cancelling event due to no window focus: MotionEvent
After going to history and reechoosing the app (causing surface recreation) the touch events do fire again.

- The app has a huge delay when you click something (tested the control catalog - same behaviour) - in the debugger you can see Messages like "I/Choreographer(16397): Skipped 786 frames!  The application may be doing too much work on its main thread."

I looked into it - the only thing i saw and thougt worth mentioning was that the threading interface does not test if you are already on main thread and always posts to mainlooper - but changing this does not seem to change the behaviour / fix the problems i mentioned.

I hope you can help me.

**Comment by maxkatz6** [comment]
Deferred renderer was implemented and I believe android support is way better now (not yet production ready though for most applications)
