### ISSUE TITLE
TimePicker default text could be user set.

### ISSUE THREAD

**Issue by Coloryr** [AvaloniaUI/Avalonia#14706]
## Describe the bug
`TimePicker` default text(hour,minute etc) could edit
https://github.com/AvaloniaUI/Avalonia/blob/3194e3206eac90e172615048748d016145953fa3/src/Avalonia.Controls/DateTimePickers/TimePicker.cs#L235-L236

`DatePicker` also could edit
https://github.com/AvaloniaUI/Avalonia/blob/3194e3206eac90e172615048748d016145953fa3/src/Avalonia.Controls/DateTimePickers/DatePicker.cs#L377-L379

```
- _hourText.Text = "hour";
+ _hourText.Text = something user can edit
```

## To Reproduce
none.

## Expected behavior
`TimePicker` default text can change by user.

## Screenshots
none.

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.9

## Additional context
none.

**Comment by maxkatz6** [comment]
Fixed by https://github.com/AvaloniaUI/Avalonia/pull/13773 in two ways:
1. Control code-behind doesn't override text value set by style. So, user can set their own styles if needed.
2. There are dynamic localizable resources that also can be overridden.

**Comment by Coloryr** [comment]
Ok, waiting for branch merge/
