### ISSUE TITLE
RequestNextFrameRendering on OpenGL Control partially drawn

### ISSUE THREAD

**Issue by marklam** [AvaloniaUI/Avalonia#14725]
## Describe the bug
For an OpenGLControlBase-derived control, calling RequestNextFrameRendering causes the rendered scene to only be partially drawn (a subset of the draw calls, or only the left side of the bitmap, it seems). Causing a re-render via a window resize paints successfully.

## To Reproduce

I've got a class derived from OpenGLControlBase in Avalonia 11.0.9, running on WIndows with Avalonia.Angle.Windows.Natives 2.1.0.2023020321.

My program setup includes  .With(Win32PlatformOptions(RenderingMode = [Win32RenderingMode.Wgl]))

Sample code: https://github.com/marklam/AvaloniaOpenGLPointCloud

I'm rendering two point clouds (actually arranged in planes at the moment) and a wireframe cube in my OnOpenGlRender override (ignoring fb and using the GlInterface passed during OnOpenGlInit)

When mouse interaction changes the model transform, I request a new render by calling RequestNextFrameRendering()

The strange paint problem I'm seeing is that as the mouse drags, some of the re-renders are missing bits (either half of one of the point clouds, or an entire cloud, or the wireframe cube).

The really weird bit is that if I stop the drag operation on a badly drawn frame, and then resize the window, the calls to my OnOpenGLRender will show the full scene.

In my real app, not the sample app, I'm checking all the OpenGL return codes, and RenderDoc doesn't show anything strange.

## Expected behavior

The image should  draw fully in response to the RequestNextFrameRendering when handlng mouse moves, as it does when the app window is resized.

## Screenshots

In the attached animation, the messages in the console window "OnOpenGLRender" shows the render calls, in response to the transform changing (and RequestNextFrameRendering being called) or Avalonia's redraws from the window resizing.

![DragClouds](https://github.com/AvaloniaUI/Avalonia/assets/1962640/93c78631-4f3b-4bda-95a9-7800cfaccf2a)

## Environment 

- OS: Windoss 11
- Avalonia-Version: 11.0.9

## Additional context
Tried with nvidia and intel graphics cards.

**Comment by marklam** [comment]
I've added an[ OpenTK version](https://github.com/marklam/AvaloniaOpenGLPointCloud/tree/master/OpenTKPointCloudTest) (no Avalonia) to the above repo, and it **doesn't** have the flicker.

![OpenTKDragClouds](https://github.com/AvaloniaUI/Avalonia/assets/1962640/683a4af1-9fea-49c8-b151-1c2b5c8b4aeb)

**Comment by marklam** [comment]
I've also switched the Avalonia project to use OpenTK for the bindings, it still exhibits the flickering. So it definitely seems to be a diffrerence between OpenTK's GameWindow and Avalonia's OpenGLControlBase.

**Comment by kekekeks** [comment]
Please check if it happens with ANGLE-backed OpenGL ES. WGL mode is experimental and isn't really supported.

**Comment by marklam** [comment]
I've [created an 'angle' branch ](https://github.com/marklam/AvaloniaOpenGLPointCloud/tree/angle) but I can't persuade Angle to draw anything for the point clouds, so it doesn't help. I've added GL Debug logging and error checks and Angle isn't complaining about anything.

I'm not sure what the problem is with the point arrays.
* I made the shaders compatible with Angle, and they still draw the points OK under Wgl 
* I can either have no 'cube' drawn, or a solid cube because GLPolygonMode isn't resolved under Angle, even with OpenTK 5 pre-release.

So all I can get from the Angle version is a blank screen because the clouds don't render, or a solid cube which doesn't exhibit the problem (probably because there's no point clouds being drawn)

The solid cube under Angle doesn't flicker, but nor does just-the-cube under Wgl so without the point rendering it's not telling me anything.

**Comment by kekekeks** [comment]
Just in case, try calling glFinish before exiting from OnOpenGlRender

**Comment by marklam** [comment]
That fixes it (the Wgl flicker, which was my initial problem)! 

You're the remote-debugging wizard (and I get the clown nose).

**Comment by kekekeks** [comment]
It's probably a problem on our side, will need to read more on context sharing.
