### ISSUE TITLE
Null reference exception on Android When press done button in the input method

### ISSUE THREAD

**Issue by BaiUpWind** [AvaloniaUI/Avalonia#14735]
## Describe the bug
When press done button in the input method, the App will crash and VS throw Exception also can't locate the.

## To Reproduce

1. Link to device and start debug
2. Type something in Textbox and press done(完成), see that red circle in image1.
3. See Error 
 
## Expected behavior
fixed!

## Screenshots
<img width="640" alt="bug1" src="https://github.com/AvaloniaUI/Avalonia/assets/35480921/f5b18025-179e-4ab3-9d43-e3806f204cd9">
 
<img width="1280" alt="bug2" src="https://github.com/AvaloniaUI/Avalonia/assets/35480921/bb4c5d78-9d38-448b-8251-3c53a1b2c798">
  
## Environment 

- OS:  Windows 11 ,   Android 
- Device: Urovo DT40(Android 11.0 -API 30)
- Avalonia-Version: 11.0.9

## Additional context
I think is input method problem, that input method name call IFLY(讯飞)

**Comment by emmauss** [comment]
Please update your avalonia version to 11.0.6 or newer. you can change it in Directory.Build.props.

**Comment by BaiUpWind** [comment]
> Please update your avalonia version to 11.0.6 or newer. you can change it in Directory.Build.props.

I tried. Same thing

**Comment by BaiUpWind** [comment]
Problem solving, update version to 11.0.9
make sure all project files are up to date,sometimes VS only updates one project in a sln.
