### ISSUE TITLE
Receiving "no static method ViewCompat.setWindowInsetsAnimationCallback" when in Android/Release

### ISSUE THREAD

**Issue by alessandrofrancesconi** [AvaloniaUI/Avalonia#14730]
I'm using Avalonia 11.0.9 for a iOS+Android app. The framework version is NET 7.0. 

For Android, `minSdkVersion="24"` and `targetSdkVersion="34"` and the following packages are installed:

```
<ItemGroup>
    <PackageReference Include="Avalonia.Android" Version="11.0.9" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.0.1.6" />
    <PackageReference Include="Xamarin.Essentials" Version="1.8.1" />
</ItemGroup>
```

If the app runs in Debug mode, I have no issues. While if running in Release mode on an Android 34 device, this error appears at startup:

`Java.Lang.Error: 'no static method "Landroidx/core/view/ViewCompat;.setWindowInsetsAnimationCallback(Landroid/view/View;Landroidx/core/view/WindowInsetsAnimationCompat$Callback;)V"'`

The configuration for Release mode is as follows:

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AndroidEnableMultiDex>True</AndroidEnableMultiDex>
    <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
    <AndroidLinkTool>r8</AndroidLinkTool>
    <AndroidUseAapt2>True</AndroidUseAapt2>
    <AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
  </PropertyGroup>
```

Am I missing something? Thanks for your support

**Comment by maxkatz6** [comment]
It might be https://github.com/xamarin/AndroidX compatibility issue as well.
cc @emmauss

**Comment by alessandrofrancesconi** [comment]
> It might be https://github.com/xamarin/AndroidX compatibility issue as well. cc @emmauss

So is there a known open issue related to AndroidX? Any workaround maybe?

**Comment by emmauss** [comment]
> > It might be https://github.com/xamarin/AndroidX compatibility issue as well. cc @emmauss
> 
> So is there a known open issue related to AndroidX? Any workaround maybe?

Does it occur with emulators targeting API 33 and 34?

**Comment by alessandrofrancesconi** [comment]
I have two Emulators based on:

- Pixel 5 - API 34 (Android 14.0 - API 34)
- Pixel 5 - API 33 (Android 13.0 - API 33)

The issue happens in both of them.

**Comment by emmauss** [comment]
> I have two Emulators based on:
> 
>     * Pixel 5 - API 34 (Android 14.0 - API 34)
> 
>     * Pixel 5 - API 33 (Android 13.0 - API 33)
> 
> 
> The issue happens in both of them.

Can you set Trimming granularity, i.e. `TrimMode` to `link`?

**Comment by emmauss** [comment]
Could you target net8-android?

**Comment by alessandrofrancesconi** [comment]
Not solved even by setting `<TargetFramework>net8.0-android34.0</TargetFramework>` (using .NET 8.0.102)
Also tried with/without `TrimMode=link`

Any ideas?

**Comment by emmauss** [comment]
I can't reproduce your specific case. I did get a crash at launch with Release config on a new project, but don't trim mode removed the issue somehow. It never came back for that project even with everything reverted. Could you provide a sample that also has the crash.

**Comment by alessandrofrancesconi** [comment]
I think I've found the reason of the crash: it is due to the coexistence of these two settings:

```
<EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
<AndroidLinkTool>r8</AndroidLinkTool>
```

When both are set, the application crashes. I temporary solved by settings EmbedAssembliesIntoApk=True

Here is a sample multi-platform project (just focus on "ReleaseCrashTest.Android"): 
[ReleaseCrashTest.zip](https://github.com/AvaloniaUI/Avalonia/files/14474695/ReleaseCrashTest.zip)

It is a bug on Avalonia, or .NET itself?

**Comment by emmauss** [comment]
Those settings aren't part of the default .net android templates, or our xplat android templates. Why are they added in your project.

**Comment by alessandrofrancesconi** [comment]
Honestly I can't remember the reason, maybe it was changed during some tests. By the way, the [docs about `EmbedAssembliesIntoApk`](https://learn.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-properties#embedassembliesintoapk) says:

> This property should be True for Release builds and False for Debug builds. 

So I agree my situation was not "standard". I close this, thanks.
