### ISSUE TITLE
Unable to cancel App Shutdown from Window Closing

### ISSUE THREAD

**Issue by nixtar** [AvaloniaUI/Avalonia#14748]
## Describe the bug
I have an application that prompts the user to confirm when they try and close the apps main window.

I'm currently doing this using [Avalonia.Xaml.Behaviors](https://github.com/AvaloniaUI/Avalonia.Xaml.Behaviors) to wire up the Closing event to an async RelayCommand in the viewmodel.

When you close the window with the red X this works as desired.
However, on macOS when you close the app from the menu bar or from the dock this does not work.
The closing event is raised but the app closes when the first await is fired (even if `e.Cancel = true;` is set).

## To Reproduce

1. Create a new Avalonia Project
2. Wire up the MainWindow Closing event to a new method in the code behind
3. Set body of the Closing method to:
```c#
e.Cancel = true;
```
4. Run the app on macOS and try closing the window directly (it shouldn't close)
5. Close the app from the menu bar or the dock (it will close)

## Expected behavior
All methods to gracefully close the app should be cancellable.

## Environment 

- OS: macOS 13.6
- Avalonia-Version: 11.0.9

## Additional context
You can cancel the app shutdown from the ShutdownRequested event however the remarks for this event reads:

This event provides a first-chance to cancel application shutdown; if shutdown is not canceled at this point the application will try to close each non-owned open window, invoking the Closing event on each and allowing each window to cancel the shutdown of the application.

**Comment by THE-KONDRAT** [comment]
I have the same issue but on windows.
I use `ShutdownRequested` event and set `e.Cancel = true;`.
When I click the red cross button main window closes, but app continues to work.

I also have another problem.
When I call save project method and then I click the red cross or shutdown my app in another way I want to wait for saving finished. I think I should do this in `OnShutdownRequested` (handler) but the handler blocks saving process. What should I do? Maybe I should call save method in some different way?

**Comment by timunie** [comment]
@THE-KONDRAT if you want to prevent a Window from closing, why not override `OnClosing` in the Window or listen to the `Closing`-Event?

**Comment by THE-KONDRAT** [comment]
> @THE-KONDRAT if you want to prevent a Window from closing, why not override `OnClosing` in the Window or listen to the `Closing`-Event?

I'm sorry but where should i override this event?
I want to control both the cross button click and manual shutdown request.
I thought i should use IClassicDesktopStyleApplicationLifetime (in my case) in app.axaml.cs.

**Comment by timunie** [comment]
In MainWindow.axaml.cs

**Comment by THE-KONDRAT** [comment]
> In MainWindow.axaml.cs
Ok. That works.

And how can i wait another method inside OnClosing?

**Comment by THE-KONDRAT** [comment]
> something like that should work
> 
> ```cs
> private bool _canClose;
>     
> protected override void OnClosing(WindowClosingEventArgs e)
> {
>     if (!_canClose)
>     {
>         // cancel closing 
>         e.Cancel = true;
>        
>         _canClose = await DoAsyncStuff(); // async stuff should return bool here
>         if (_canClose) this.Close(); // request close again if above was successful
>     }
>     base.OnClosing(e);
> }
> ```

Thanks! This also works. Maybe someone find this usefull.

```csharp
protected override async void OnClosing(WindowClosingEventArgs e)
{
    var context = Ioc.Default.GetRequiredService<ApplicationContext>();
    if (!context.CanClose)
    {
        e.Cancel = true;
        await context.WaitForAsync(nameof(context.CanClose), q => q.CanClose);
        if (context.CanClose) this.Close();
    }
    base.OnClosing(e);
}
```

**Comment by nixtar** [comment]
Just to clarify, this is not what this issue is about.

The issue I'm having is when the app is being closed by the OS (not when clicking close on the window).

If you wire up the OnClosing the same as above, but on macOS you close the application from the menu bar or by right clicking it on the dock. The OnClosing event will fire but the app will close regardless.

**Comment by timunie** [comment]
@nixtar I'm aware of that, and this is why I didn't close it.

**Comment by maxkatz6** [comment]
From how it looks, this functionality was broken for two years since https://github.com/AvaloniaUI/Avalonia/pull/7400

**Comment by nixtar** [comment]
Finally got a chance to test this with 11.1.0-beta2 and am happy to confirm it now works as expected. 👍
