### ISSUE TITLE
PointerPressedEvent and PointerReleasedEvent will not fire properly if you press multiple mouse buttons

### ISSUE THREAD

**Issue by alexander-miglis** [AvaloniaUI/Avalonia#14777]
If I press left button and hold it, then press right button then there is no PointerPressed event for the second button press.

If I then release left button (while still holding right button) there is no PointerReleased event.

Finally if I release the right button I do get an event, but nothing indicates the left button was released.

I would expect either that the event is fired on every event and that I can read current state from the mouse buttons or that the events fire only when the first button that was pressed is released. The current behavior seems wrong.

I use Avalonia 11.0.9 when I'm testing this

**Comment by IanRawley** [comment]
It's by design, see #2857

**Comment by maxkatz6** [comment]
Yes, and you can handle PointerMoved update event checking UpdateKind parameter.
