### ISSUE TITLE
managed StorageProvider.OpenFolderPickerAsync() throws exception when user empties folder textbox

### ISSUE THREAD

**Issue by jpmikkers** [AvaloniaUI/Avalonia#14772]
## Describe the bug
the managed version of OpenFolderPickerAsync() throws ArgumentException 'the path is empty' when the user empties the folder textbox and presses OK.

## To Reproduce
- add .UseManagedSystemDialogs() to BuildAvaloniaApp
- call StorageProvider.OpenFolderPickerAsync() 
- empty the path textbox at the top and press OK
- result: (unhandled) ArgumentException 'the path is empty'

## Expected behavior
The native dialog (on windows) does path validation of manually entered paths within the folder picker context, showing messageboxes if something is wrong. So perhaps add validation, block the OK button until a valid path is selected.

## Screenshots
N/A

## Environment 

- OS: win11
- Avalonia-Version: tested on 11.0.9 and 11.1.999-cibuild0045411-beta

## Additional context
The workaround is (of course) to try-catch the OpenFolderPickerAsync call.

**Comment by timunie** [comment]
What does ManagedFilePicker do in that case?

**Comment by maxkatz6** [comment]
Depending on stack trace, fix might be as simple, as checking if selected path is null or empty in these methods:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Dialogs/ManagedStorageProvider.cs#L31-L55

Or, alternatively, probably better, filter them before calling `CompleteRequested` event: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Dialogs/Internal/ManagedFileChooserViewModel.cs#L369-L405

**Comment by jpmikkers** [comment]
@timunie the OpenFilePickerAsync() seems more robust, I can fill in nonsense paths and non-existing filenames and it will simply return an empty list.

**Comment by timunie** [comment]
Imo the OpenFolderPicker should follow this and return `null` in that case. A PR is welcome to fix that.
