### ISSUE TITLE
Button.Flyout unable to display

### ISSUE THREAD

**Issue by duxunmi** [AvaloniaUI/Avalonia#14805]
## Describe the bug
Button.Flyout unable to display

## To Reproduce
![图片](https://github.com/AvaloniaUI/Avalonia/assets/13842235/b11a62c0-1f5d-4870-85f5-897f3a496fc6)

<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
	    xmlns:i="clr-namespace:Projektanker.Icons.Avalonia;assembly=Projektanker.Icons.Avalonia"
		xmlns:material="using:Material.Icons.Avalonia"
        mc:Ignorable="d" d:DesignWidth="600" d:DesignHeight="60" MaxHeight="60" MaxWidth="600" Height="60" Width="600"
		TransparencyLevelHint="Transparent"
		SystemDecorations="None"
        Background="Transparent"
        x:Class="AvaloniaApplication2.MainWindow"
        Title="AvaloniaApplication2" RenderOptions.BitmapInterpolationMode="HighQuality">
	<Window.Styles>
		<Style Selector="Button.op">
			<Setter Property="Width" Value="48" />
			<Setter Property="HorizontalContentAlignment" Value="Center" />
			<Setter Property="Height" Value="48"></Setter>
			<Setter Property="FontSize" Value="14"></Setter>
			<Setter Property="FontWeight" Value="Medium"></Setter>
			<Setter Property="Foreground" Value="White"></Setter>
			<Setter Property="Background" Value="#11ffffff"></Setter>
			<Setter Property="Cursor" Value="Hand"></Setter>
			<Setter Property="CornerRadius" Value="30"></Setter>
		</Style>
		<Style Selector="Button.op:pointerover">
			<Setter Property="Foreground" Value="White"></Setter>
			<Setter Property="Background" Value="#30dddddd"></Setter>
		</Style>
		<Style Selector="Button.op:disabled">
			<Setter Property="Foreground" Value="LightGray"></Setter>
			<Setter Property="Background" Value="#40e3e3e3"></Setter>
		</Style>
		<Style Selector="Button.oplarge">
			<Setter Property="Width" Value="90" />
			<Setter Property="HorizontalContentAlignment" Value="Center" />
			<Setter Property="Height" Value="36"></Setter>
			<Setter Property="FontSize" Value="14"></Setter>
			<Setter Property="FontWeight" Value="Medium"></Setter>
			<Setter Property="Foreground" Value="White"></Setter>
			<Setter Property="Background" Value="#11ffffff"></Setter>
			<Setter Property="Cursor" Value="Hand"></Setter>
			<Setter Property="CornerRadius" Value="30"></Setter>
		</Style>
		<Style Selector="Button.oplarge:pointerover">
			<Setter Property="Foreground" Value="White"></Setter>
			<Setter Property="Background" Value="#30dddddd"></Setter>
		</Style>
		<Style Selector="Button.oplarge:disabled">
			<Setter Property="Foreground" Value="LightGray"></Setter>
			<Setter Property="Background" Value="#40e3e3e3"></Setter>
		</Style>
		<Style Selector="Button.op1">
			<Setter Property="Width" Value="48" />
			<Setter Property="HorizontalContentAlignment" Value="Center" />
			<Setter Property="Height" Value="48"></Setter>
			<Setter Property="CornerRadius" Value="30"></Setter>
			<Setter Property="FontSize" Value="14"></Setter>
			<Setter Property="FontWeight" Value="Medium"></Setter>
			<Setter Property="Foreground" Value="White"></Setter>
			<Setter Property="Background" Value="Transparent"></Setter>
			<Setter Property="Cursor" Value="Hand"></Setter>
		</Style>
		<Style Selector="Button.op1:pointerover">
			<Setter Property="Foreground" Value="White"></Setter>
			<Setter Property="Background" Value="#30dddddd"></Setter>
		</Style>
		<Style Selector="Button.op1:disabled">
			<Setter Property="Foreground" Value="Gray"></Setter>
			<Setter Property="Background" Value="#30dddddd"></Setter>
		</Style>
		<Style Selector="TextBlock">
			<Setter Property="FontSize" Value="18" />
			<Setter Property="TextAlignment" Value="Center" />
			<Setter Property="HorizontalAlignment" Value="Center" />
			<Setter Property="VerticalAlignment" Value="Center" />
		</Style>
		<Style Selector="DataGrid">
			<Setter Property="BorderBrush" Value="WhiteSmoke"/>
			<Setter Property="ColumnWidth" Value="180"/>
			<Setter Property="RowHeight" Value="48"/>
			<Setter Property="ColumnHeaderHeight" Value="48"></Setter>
			<Setter Property="SelectionMode" Value="Extended"/>
			<Setter Property="BorderThickness" Value="1,1,1,1"/>
			<Setter Property="GridLinesVisibility" Value="Horizontal"/>
			<Setter Property="CanUserResizeColumns" Value="True"/>
			<Setter Property="CanUserReorderColumns" Value="False"/>
			<Setter Property="AutoGenerateColumns" Value="False"/>
			<Setter Property="AreRowGroupHeadersFrozen" Value="True"/>
		</Style>
		<Style Selector="DataGridRow:selected /template/ Rectangle#BackgroundRectangle">
			<Setter Property="Fill" Value="DodgerBlue"/>
		</Style>
		<Style Selector="DataGridRow:selected">
			<Setter Property="Foreground" Value="White"/>
		</Style>
		<Style Selector="DataGridRow:nth-child(2n) /template/ Rectangle#BackgroundRectangle">
			<Setter Property="Fill" Value="#E7EAEC"/>
		</Style>
		<Style Selector="DataGridRow:nth-child(2n):selected /template/ Rectangle#BackgroundRectangle">
			<Setter Property="Fill" Value="DodgerBlue"/>
		</Style>
		<Style Selector="Button.grid">
			<Setter Property="Width" Value="68"></Setter>
			<Setter Property="Height" Value="32"></Setter>
			<Setter Property="FontSize" Value="14"></Setter>
			<Setter Property="Foreground" Value="Black"></Setter>
			<Setter Property="Background" Value="White"></Setter>
			<Setter Property="Cursor" Value="Hand"></Setter>
			<Setter Property="Template">
				<ControlTemplate>
					<Border Background="{TemplateBinding Background}" CornerRadius="20" BorderThickness="2" BorderBrush="{TemplateBinding BorderBrush}">
						<TextBlock TextAlignment="Center" HorizontalAlignment="Center" VerticalAlignment="Center" Text="{TemplateBinding Content}" FontSize="{TemplateBinding FontSize}"></TextBlock>
					</Border>
				</ControlTemplate>
			</Setter>
		</Style>
		<Style Selector="Border.Twinkle">
			<Style.Animations>
				<Animation Duration="0:0:1" IterationCount="INFINITE" SpeedRatio="1">
					<KeyFrame Cue="0%">
						<Setter Property="RotateTransform.Angle" Value="0"/>
					</KeyFrame>
					<KeyFrame Cue="25%">
						<Setter Property="RotateTransform.Angle" Value="15"/>
					</KeyFrame>
					<KeyFrame Cue="50%">
						<Setter Property="RotateTransform.Angle" Value="0"/>
					</KeyFrame>
					<KeyFrame Cue="75%">
						<Setter Property="RotateTransform.Angle" Value="-15"/>
					</KeyFrame>
					<KeyFrame Cue="100%">
						<Setter Property="RotateTransform.Angle" Value="0"/>
					</KeyFrame>
				</Animation>
			</Style.Animations>
		</Style>
		<Style Selector="Border.Roll">
			<Style.Animations>
				<Animation Duration="0:0:1" IterationCount="INFINITE" SpeedRatio="0.3">
					<KeyFrame Cue="0%">
						<Setter Property="TranslateTransform.X" Value="20"/>
					</KeyFrame>
					<KeyFrame Cue="25%">
						<Setter Property="TranslateTransform.X" Value="-30"/>
					</KeyFrame>
					<KeyFrame Cue="50%">
						<Setter Property="TranslateTransform.X" Value="-60"/>
					</KeyFrame>
					<KeyFrame Cue="75%">
						<Setter Property="TranslateTransform.X" Value="-90"/>
					</KeyFrame>
					<KeyFrame Cue="100%">
						<Setter Property="TranslateTransform.X" Value="-120"/>
					</KeyFrame>
				</Animation>
			</Style.Animations>
		</Style>
		<Style Selector="Border.Rotate">
			<Style.Animations>
				<Animation Duration="0:0:6" IterationCount="INFINITE" SpeedRatio="1" FillMode="Both">
					<KeyFrame Cue="0%">
						<Setter Property="RotateTransform.Angle" Value="0"/>
					</KeyFrame>
					<KeyFrame Cue="25%">
						<Setter Property="RotateTransform.Angle" Value="90"/>
					</KeyFrame>
					<KeyFrame Cue="50%">
						<Setter Property="RotateTransform.Angle" Value="180"/>
					</KeyFrame>
					<KeyFrame Cue="75%">
						<Setter Property="RotateTransform.Angle" Value="270"/>
					</KeyFrame>
					<KeyFrame Cue="100%">
						<Setter Property="RotateTransform.Angle" Value="360"/>
					</KeyFrame>
				</Animation>
			</Style.Animations>
		</Style>
	</Window.Styles>
	<Border Background="Transparent" CornerRadius="80" ClipToBounds="True">
		<Grid Background="#0F8DF1"> 
			<StackPanel Orientation="Vertical" Spacing="5" VerticalAlignment="Center" Margin="5">
				<Button  Classes="op1" Content="插队" ToolTip.Tip="{Binding $self.Content}">
					<Button.Template>
						<ControlTemplate>
							<Border HorizontalAlignment="Center" VerticalAlignment="Center" CornerRadius="{TemplateBinding CornerRadius}" Height="{TemplateBinding Height}" Width="{TemplateBinding Width}" Background="{TemplateBinding Background}">
								<StackPanel VerticalAlignment="Center" HorizontalAlignment="Center">
									<material:MaterialIcon Cursor="Hand" Kind="PagePreviousOutline" Height="20" Width="20" HorizontalAlignment="Center" />
								</StackPanel>
							</Border>
						</ControlTemplate>
					</Button.Template>
					<Button.Styles>
						<Style Selector="FlyoutPresenter">
							<Setter Property="MaxWidth" Value="800"></Setter>
							<Setter Property="Background" Value="White"></Setter>
							<Setter Property="Height" Value="600"></Setter>
							<Setter Property="Width" Value="400"></Setter>
						</Style>
					</Button.Styles>
					<Button.Flyout>
						<Flyout Placement="Bottom"  ShowMode="TransientWithDismissOnPointerMoveAway">
							<Grid x:Name="grid">
								<StackPanel Orientation="Vertical">
									<TextBlock Text="asdasdasdasd"></TextBlock>
									<TextBlock Text="asdasdasdasd"></TextBlock>
									<TextBlock Text="asdasdasdasd"></TextBlock>
									<TextBlock Text="asdasdasdasd"></TextBlock>
									<TextBlock Text="asdasdasdasd"></TextBlock>
									<TextBlock Text="asdasdasdasd"></TextBlock>
								</StackPanel>
							</Grid>
						</Flyout>
					</Button.Flyout>
				</Button>
			</StackPanel>
		</Grid>
	</Border>
</Window>

## Environment 

- OS: [Linux]
- Avalonia-Version: [11.0.9]

## Additional context
 Avalonia-Version:  11.0.6，the display is normal

![Uploading 图片.png…]()

**Comment by duxunmi** [comment]
11.0.9  The abnormal display effect is as follows：
![图片](https://github.com/AvaloniaUI/Avalonia/assets/13842235/830b1764-9316-4ac5-a00d-36b32616dcdf)

**Comment by rabbitism** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/14802#issuecomment-1975398009
