### ISSUE TITLE
Broken link for "getting started" page in the readme 

### ISSUE THREAD

**Issue by Mondier97** [AvaloniaUI/Avalonia#1481]

**Comment by SIkebe** [comment]
>select "Avalonia .NET Core Application" and press OK (<a href="http://avaloniaui.net/tutorial/images/add-dialogs.png">screenshot</a>).

**Comment by kekekeks** [comment]
I guess it should be http://avaloniaui.net/docs/quickstart/images/new-project-dialog.png

**Comment by jmacato** [comment]
Already Fixed (unknown commit hash), Closing this now.
