### ISSUE TITLE
[ControlCatalog] DecoratedWindow uses private API

### ISSUE THREAD

**Issue by afluegge** [AvaloniaUI/Avalonia#14825]
## Describe the bug
DecoratedWindow uses private API:

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
            this.Get<Control>("TitleBar").PointerPressed += (i, e) =>
            {
                PlatformImpl?.BeginMoveDrag(e);  // BeginMoveDrag is internal
            };
...
...

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/036d5463a6476570798898b46e5372ac576601ed/src/Avalonia.Controls/Window.cs#L433-L439
