### ISSUE TITLE
Avalonia.Markup.Xaml won't build in VS2017

### ISSUE THREAD

**Issue by edward-a** [AvaloniaUI/Avalonia#1482]
I followed the build instructions listed at http://avaloniaui.net/contributing/build, but i couldn't build the samples. It's failing to build Avalonia.Markup.Xaml assembly saying that stuff from Portable.Xaml is missing:  XamlXmlReaderSettings, XamlXmlReader, XamlReader, XamlServices, etc. I added Portable.Xaml 0.21.0 nuget package to the project that fixed the unresolved references, but now i receive other errors such as ambiguous ICustomAttributeProvider and invalid overrides OnAfterBeginInit, OnAfterEndInit, OnAfterProperties, etc.

> git describe --tags: nuget-release-0.6.1-159-g829d6957

**Comment by jkoritzinsky** [comment]
Did you clone the submodules when cloning?
