### ISSUE TITLE
Value types cannot be TemplateBinding

### ISSUE THREAD

**Issue by JIIIIL** [AvaloniaUI/Avalonia#14831]
### Describe the bug

In the custom template control, if the binding type is value, the binding fails. If the binding type is reference, the binding succeeds. Binding can be successfully achieved through converter conversion.Not sure if this is a bug or if it's just the way it's used
[Uploading AvaloniaApplication5.zip…]()

### To Reproduce

![1709690273810](https://github.com/AvaloniaUI/Avalonia/assets/83105448/9262f038-3560-4606-b01b-17c05831e81a)

### Avalonia version

11.0.9 11.0.10

### OS

Windows

**Comment by rabbitism** [comment]
Yes, In this case you should use Binding RelativeSource={RelativeSource TemplateParent}

**Comment by JIIIIL** [comment]
thanks
