### ISSUE TITLE
WindowStartupLocation="CenterScreen" not working on Linux Mint 21.3 w/ Cinnamon and X11

### ISSUE THREAD

**Issue by JeromyWalsh** [AvaloniaUI/Avalonia#14850]
### Describe the bug

I'm going through the Avalonia.MusicStore tutorial on the website and came to the "Dialog Position and Size" segment where we're instructed to set the WindowStartupLocation in MainWindow.axaml to CenterScreen.

This does not appear to be working as of 11.0.6 or earlier, and as late as 11.0.10 in Linux Mint 21.3 (Virginia) using the Cinnamon Desktop and X11. See the attached image below.

### To Reproduce

On a Linux Mint 21.3 machine, using the Cinnamon Desktop...

1. Create any avalonia.mvvm project. 
2. Go the MainWindow.axaml
3. Add: WindowStartupLocation="CenterScreen" to the window properties
4. Launch/debug the application

### Expected behavior

Expected behavior is that the main window opens in the center of the screen. What actually happens is it opens near the top left corner of the screen. 

### Avalonia version

11.0.10

### OS

Linux

### Additional context

![screenshot](https://github.com/AvaloniaUI/Avalonia/assets/17633767/5c0b0121-546a-4018-aebf-5fd4242b3776)

**Comment by maxkatz6** [comment]
Can you check with nightly builds? There were related PRs that might have fixed this issue.

**Comment by JeromyWalsh** [comment]
@maxkatz6 Checked the nightly build (11.1.999-cibuild0045888-beta) and it's still exhibiting the same behavior.
