### ISSUE TITLE
`Embedded controls` does't display in `TextBlock` Inline

### ISSUE THREAD

**Issue by Tulesha** [AvaloniaUI/Avalonia#14855]
### Describe the bug

`TextBlock` doesn't display `Embedded controls` which presenter as `Inline`.

### To Reproduce

Paste this code in any View:
``` xaml
<TextBlock>
    <TextBlock.Inlines>
        <Span>
            Foo
            <LineBreak />
            <Span>
                Picture:
                <!--Something like a HyperLink-->
                <TextBlock>
                    <InlineUIContainer>
                        <Image Width="200" Height="200" Source="../Assets/patric.jpg" />
                    </InlineUIContainer>
                </TextBlock>
            </Span>
            <LineBreak />
            Bar
        </Span>
    </TextBlock.Inlines>
</TextBlock>
```

I get the following output:
![image](https://github.com/AvaloniaUI/Avalonia/assets/43892140/7bfa9fb1-a69d-4d61-be31-d2892fde205d)

You can replace `Image` to another `Control` (for example: `TextBox`) and behaviour will be the same

### Expected behavior

Expected output (11.0.7 version):
![image](https://github.com/AvaloniaUI/Avalonia/assets/43892140/7bedabbe-63b1-44f3-92e1-9fc51deaf9fc)

### Avalonia version

11.0.10

### OS

Windows

### Additional context

In 11.0.7 this bug is not reproducible.

I thing it is related with new logic of Adding `Visual Children` from this pull request #14590

I also note that the `Embedded control` is displayed if we do not have nested `Span` in `Inlines`.
For example:
```xaml
<TextBlock>
    <TextBlock.Inlines>
        Foo
        <LineBreak />
        <Span>
            Picture:
            <!--Something like a HyperLink-->
            <TextBlock>
                <InlineUIContainer>
                    <Image Width="200" Height="200" Source="../Assets/patric.jpg" />
                </InlineUIContainer>
            </TextBlock>
        </Span>
        <LineBreak />
        Bar
    </TextBlock.Inlines>
</TextBlock>

```

**Comment by timunie** [comment]
@Tulesha can you also check latest nightly please?

**Comment by Tulesha** [comment]
> @Tulesha can you also check latest nightly please?

Same behavior on `11.1.999-cibuild0045848-beta`

**Comment by Gillibald** [comment]
Renders just fine with latest master

**Comment by Tulesha** [comment]
@Gillibald

I create `TestPage` in `ControlCatalog` project with latest master, and behavior is same.

```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="ControlCatalog.Pages.TestPage">
  <TextBlock>
    <TextBlock.Inlines>
      <Span>
        Foo
        <LineBreak />
        <Span>
          TextBox: <TextBox/>
        </Span>
        <LineBreak />
        Bar
      </Span>
    </TextBlock.Inlines>
  </TextBlock>
</UserControl>
```

Output:
![image](https://github.com/AvaloniaUI/Avalonia/assets/43892140/20f74ecc-44bf-43c4-bc9d-13599fe0e566)

**Comment by timunie** [comment]
@Tulesha you forgot to add InlineUiContainer: 

```diff
  <TextBlock>
    <TextBlock.Inlines>
      <Span>
        Foo
        <LineBreak />
        <Span>
-          TextBox: <TextBox/>
+          TextBox:
        </Span>
+       <InlineUIContainer><TextBox/></InlineUIContainer>
        <LineBreak />
        Bar
      </Span>
    </TextBlock.Inlines>
  </TextBlock>
```

**Comment by Tulesha** [comment]
> @Tulesha you forgot to add InlineUiContainer:
> 
> ```diff
>   <TextBlock>
>     <TextBlock.Inlines>
>       <Span>
>         Foo
>         <LineBreak />
>         <Span>
> -          TextBox: <TextBox/>
> +          TextBox:
>         </Span>
> +       <InlineUIContainer><TextBox/></InlineUIContainer>
>         <LineBreak />
>         Bar
>       </Span>
>     </TextBlock.Inlines>
>   </TextBlock>
> ```

Yep, this works, because in this case `Embedded control` located in non nested `Span` element.

But if I add `Embedded control` in nested `Span`, still get same behavior:
```xaml
<TextBlock>
  <TextBlock.Inlines>
    <!-- If you remove this Span will work fine -->
    <Span>
      Foo
      <LineBreak />
      <Span>
        TextBox:
          <InlineUIContainer><TextBox/></InlineUIContainer>
      </Span>
      <LineBreak />
      Bar
    </Span>
  </TextBlock.Inlines>
</TextBlock>
```

**Comment by Gillibald** [comment]
Thanks for the clarification. The linked PR should fix your issue.
