### ISSUE TITLE
Image not displayed on linux-arm

### ISSUE THREAD

**Issue by nicolasr75** [AvaloniaUI/Avalonia#1486]
I did some tests with a Raspberry Pi and am having problems with Image controls.
On at least Linux Mate and Raspbian the Image controls don't get rendered correctly,
only gray rectangles.

I used Visual Studio with the Avalonia extension and created a new app with the template. To be able to compile the app for either Windows or the Raspberry, I added RIDs to my csproj, namely _win-x64_ and _linux-arm_. I then published it self-contained and copied it to the Raspberry. The first problem was that I needed an ARM compatible libSkiaSharp. I built one using the build script here https://github.com/terwoord/skiasharp-raspberry.

The app starts and displays the window but Image controls are rendered as gray rectangles (tested with png images which are specified in Xaml for the Image.Source property). There are no error messages in the terminal except the same few messages that occur on a full Ubuntu where the Images are rendered. They are also rendered on my Windows machine.

I played around with assigning the image file in Xaml and also programmatically. In the latter case I was able to check that no exception occurs during loading the image from file into a Bitmap. Also I could verify that the Bitmap object has the correct dimensions after loading the file. It just gets not rendered when assigned to Image.Source.

Any idea what could be going wrong here?
Is there any other way to draw an image on the window as an intermediate solution?

**Comment by nicolasr75** [comment]
I tried what happens with an ImageBrush in a Canvas: same result, only gray rectangles.

**Comment by lindexi** [comment]
Can you show the memory?

**Comment by nicolasr75** [comment]
Thanks, that's a good idea. However, on my way to debug the memory I encountered surprising results. Unfortunately my intentionally simple test app was already to complex in that it scaled the Image controls. Now it turns out that the gray rectangles that I see  are simply the upper left corners of my original image (by coincidence the test image had a solid gray in the upper left corner, had it been a photo I would have noticed it immediately :-( ). When I don't scale the Images, everything is rendered correctly. 

That means there is no problem with pixel rendering on the Raspberry but with scaling the images! On Windows 10 the Images are scaled correctly. 

I guess I should close this issue and create a new one...
