### ISSUE TITLE
ComboBox.ItemSource not working probably with PSCustomObject 

### ISSUE THREAD

**Issue by stephannn** [AvaloniaUI/Avalonia#14884]
### Describe the bug

Hi there,

I am using the https://github.com/ironmansoftware/psavalonia - PowerShell version updated to version 11 of Avalonia.

I am now trying to use the ItemSource property of the ComboBox and get a strange outcome when using PSCustomObject. Using own defined classes everything is working fine.

### To Reproduce

The XAML

```
        <ComboBox x:Name="ComboBoxTenant"  
                    Width="200" MaxDropDownHeight="300">
            <ComboBox.ItemTemplate>
                <DataTemplate>
                    <TextBlock Text="{Binding Name}" />
                </DataTemplate>
            </ComboBox.ItemTemplate>
        </ComboBox>
```

At first creating the array list:

```
class Tree {
    [string]$Name
    [string]$Server
}

$tree1 = new-object Tree
$tree2 = [Tree]::new()

$tree1.Name = "New"
$tree1.Server = "1"

$tree2.Name = "Old"
$tree2.Server = "2"

$ArrayList.Add($tree1)
$ArrayList.Add($tree2)
$ArrayList.Add([PSCustomObject]@{  PSTypeName = "Contact"; Name="Test"; Server="3"})
```

then we assign it to the ComboBox

```
$ComboBoxTenant = Find-AvaloniaControl -Name 'ComboBoxTenant' -Window $Window
$ComboBoxTenant.ItemsSource = $ArrayList
$ComboBoxTenant.SelectedIndex = 0
```

Now when I run the App I have three items in the ComboBox, but only the first two have a visible name. However, when I call $ComboBoxTenant.SelectedItem.Name on the selected ComboBox item it returns the correct name, even if this is just empty in the ComboBox before.

![image](https://github.com/AvaloniaUI/Avalonia/assets/38951729/7a6b25c1-6426-4aa1-a71d-9441d08d99f3)

### Expected behavior

All three items should be visible

### Avalonia version

11.0.10

### OS

Windows

### Additional context

Please let me know if I shall upload the complete project, incl. the updated PowerShell module from ironmansoftware

**Comment by timunie** [comment]
Guess it's more a question about ps avalonia. Please ask them for correct usage.
