### ISSUE TITLE
Avalonia on the WEB

### ISSUE THREAD

**Issue by TonyHenrique** [AvaloniaUI/Avalonia#1490]
How to run Avalonia App on the Web Browser ?

There could be an Avalonia Page, we can run on the web browser.

**Comment by danwalmsley** [comment]
Currently not possible, there is a discussion on how avalonia could run on Webassembly here
https://github.com/AvaloniaUI/Avalonia/issues/1387

**Comment by grokys** [comment]
Closing this as a duplicate of #1387
