### ISSUE TITLE
Proposal: Window.DecorationType attached property

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#14908]
We might want to introduce another API that works better. `BeginResizeDrag/BeginMoveDrag` copied from WPF [are just broken](https://github.com/AvaloniaUI/Avalonia/issues/8429) (even on Windows, when touch comes to action).

In general, I always was of opinion of adding some attached property like `Window.DecorationType="Titlebar"` API (with other options like ResizeGrip and Minimize button), where platform would do visuals hit test (which we already do), and depending on attached property value it would start relevant operation associating with the pointer.

_Originally posted by @maxkatz6 in https://github.com/AvaloniaUI/Avalonia/discussions/14891#discussioncomment-8738558_

**Comment by maxkatz6** [comment]
P.S. I have no idea, how exactly we should emulate these actions on X11/Wayland, so any info can be helpful on them. Right now, it seems to be similar to our current win32 handling via SendNetWMMessage. I.e. it should be fine with old API even on wayland (I guess?) - https://github.com/AvaloniaUI/Avalonia/blob/3befcbbe816a0be1f04ed4c1d1de2d0e8528b865/src/Avalonia.Wayland/WlToplevel.cs#L163-L173

**Comment by maxkatz6** [comment]
Related - https://github.com/AvaloniaUI/Avalonia/issues/11409

**Comment by maxkatz6** [comment]
Also, would help to remove hacks like this https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/WindowImpl.CustomCaptionProc.cs#L12

**Comment by kekekeks** [comment]
>    _xdgToplevel?.Move(_platform.WlSeat, _platform.WlInputDevice.Serial); 

This is simply incorrect, it should be extracting the serial from `PointerPressedEventArgs`, since the compositor identifies the corresponding touch contact by the serial.

**Comment by affederaffe** [comment]
> > _xdgToplevel?.Move(_platform.WlSeat, _platform.WlInputDevice.Serial);
> 
> This is simply incorrect, it should be extracting the serial from `PointerPressedEventArgs`, since the compositor identifies the corresponding touch contact by the serial.

Yes, it's not really correct, but the same as Qt.
If we want a better behavior, we'd (as far as I can tell) need to add a `Serial` property to the appropriate `Raw*EventArgs` and then somehow expose them (internally) to the standard Avalonia Event.

**Comment by workgroupengineering** [comment]
I think adding only the serial is reductive, it would be better to make IInputDevice public or something similar and identify the source of the event.

**Comment by maxkatz6** [comment]
IInputDevice shouldn't be public as per https://github.com/AvaloniaUI/Avalonia/issues/7939
We can't really use IInputDevice as an identifier of the pointer. We have IPointer (public) instead for that.

**Comment by workgroupengineering** [comment]
IInputDevice is not only useful for the pointer but also for the keyboard if more than one.
