### ISSUE TITLE
ScrollViewer Inertia not working on Android/iOS

### ISSUE THREAD

**Issue by LyleRolleman-plst** [AvaloniaUI/Avalonia#14919]
### Describe the bug

The title pretty much says it, even with inertial scrolling explicitly enabled, there is no inertia. As soon as I withdraw my finger, the scroll stops. 

Have tested on 11.0.7 and on the nightly builds (tried a couple, currently on 11.1.999-cibuilds0045786-beta)

Is this a known issue? and does anyone have any ideas for a workaround?

### To Reproduce

Create a ScrollViewer with enough content to require scrolling
Flick finger on Android or IOS device that would normally cause an inertial scroll. 

### Expected behavior

Scroll should have inertia

### Avalonia version

11.0.7

### OS

Android, iOS

**Comment by LyleRolleman-plst** [comment]
This has been tested on an iPhone SE (3rd gen), and a Samsung phone and tablet (don't know exact model, can find out if needed)

In short, it appears to be universal

**Comment by emmauss** [comment]
Please do provide the models and OS versions. Also could you provide a reproduction? I've tested on multiple devices and do not see any issue with scrolling inertia

**Comment by LyleRolleman-plst** [comment]
[ScrollViewerInertiaTest.zip](https://github.com/AvaloniaUI/Avalonia/files/14577776/ScrollViewerInertiaTest.zip)

I've included a super basic project (just a new project from VS template with a bunch of rectangles in a scrollviewer). I would expect a fast scroll and release would continue scrolling through the rectangles with inertia upon release. Instead it stops dead

One of the Android devices is a Samsung Galaxy Note 10+. Will update with the other when I get it

**Comment by emmauss** [comment]
I've been able to reproduce the issue. If a touch point is flicked so fast that, input doesn't recognize a continue swipe motion, scrolling is immediately stopped. This could be related to our input polling. I'll look into how to improve swipe detection.

**Comment by timunie** [comment]
@LyleRolleman-plst can you record a screen capture just to be sure we're talking about the same?

**Comment by emmauss** [comment]
Though the pr was supposed to fix this, the author hasn't confirmed it fixed and we are waiting on a reply.

**Comment by LyleRolleman-plst** [comment]
I've uploaded a quick video of what I'm seeing and expecting

https://drive.google.com/file/d/13XpaT9hTaRpt2USApfPt_q7wLQkUI-wO/view?usp=sharing

**Comment by emmauss** [comment]
Do you have the avalonia all build nuget feed in your nuget config? https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed#all-builds-feed

**Comment by LyleRolleman-plst** [comment]
> Do you have the avalonia all build nuget feed in your nuget config? https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed#all-builds-feed

Yes I do

**Comment by LyleRolleman-plst** [comment]
I have discovered something interesting on this. When I checkout the repo and run the sample ControlCatalog application from source, the scroll inertia seems to work fine. However running from a blank template (per attached app above) it does not

**Comment by timunie** [comment]
@LyleRolleman-plst do you have a sample App to share?

**Comment by LyleRolleman-plst** [comment]
Yes, see my comment up above https://github.com/AvaloniaUI/Avalonia/issues/14919#issuecomment-1992410807

**Comment by LyleRolleman-plst** [comment]
Further on using the ControlCatalog app, if I copy the markup from the test app I included above and simply overwrite MainView.xaml (and comment out most of the code behind) it _also_ works fine. The issue seems to have something to do with either the template app, or gettng Avalonia via nuget (seems unlikely but never know...)

**Comment by LyleRolleman-plst** [comment]
Just updated to latest nightly build again sure enough, now it works

Not sure when it got fixed. On the version still pointed at 11.2.999-cibuild0046159-beta it definitely wasn't but 11.2.999-cibuild0046730-alpha does

Will check it out further to confirm it's stable enough for our needs, Thanks for the help

**Comment by LyleRolleman-plst** [comment]
Turns out the story is a bit more complicated here. The new package fixed it for my test app but not the one I'm actually working on. 

After much poking around, I narrowed it down to the MaterialTheme causing the problem. Swapped in the FluentTheme and the scroll inertia starting working fine

Will report this over in their repo
