### ISSUE TITLE
[.NET Core 2.0] ControlCatalog crash on latest master

### ISSUE THREAD

**Issue by Krakean** [AvaloniaUI/Avalonia#1494]
Hello.
Just updated to latest master and decided to compile and test Avalonia. Got this crash on NumericUpDown example: https://i.imgur.com/AemzRKg.png

**Comment by danwalmsley** [comment]
I have also been seeing this exception lately seems to be:

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Utils/UndoRedoHelper.cs#L62

doesnt account for the fact that `Last` might be null.

**Comment by grokys** [comment]
Should now have been fixed. Please comment if you're still seeing this.
