### ISSUE TITLE
Width and Height Window Properties are Ignored when SystemDecorations is Set to BorderOnly

### ISSUE THREAD

**Issue by Elbon-Eastmage** [AvaloniaUI/Avalonia#14942]
### Describe the bug

When the SystemDecorations property of a Window is set to BorderOnly, the Width and Height properties don't have any effect. However, they do work when SystemDecorations is set to either None or Full.

### To Reproduce

1. Set up a new Avalonia Project.
2. Go to MainWindow.axaml.
3. Add Width="450" and Height="450".
4. Add SystemDecorations="BorderOnly".
5. Run the program.

### Avalonia version

11.0.10

### OS

Windows

**Comment by maxkatz6** [comment]
cc @emmauss

**Comment by timunie** [comment]
@Elbon-Eastmage does it also happen using 11.1.0-beta1?

**Comment by emmauss** [comment]
I can reproduce it on master.
