### ISSUE TITLE
Double-clicks in `TextBox` with `PasswordChar` should select all text, not individual words

### ISSUE THREAD

**Issue by nil4** [AvaloniaUI/Avalonia#14956]
### Describe the bug

In a `TextBox` with `PasswordChar` set, double-clicking currently selects individual 'words' from the underlying `Text`. 

This is a helpful behavior for regular text boxes, and when a password is revealed. For cloaked password input, however, selecting *the entire text* on double-click would arguably be more useful and consistent with desktop OS native controls.

### To Reproduce

```
git clone https://github.com/AvaloniaUI/ControlCatalogStandalone.git
cd ControlCatalogStandalone/ControlCatalogStandalone.Desktop
dotnet run
```

Select **TextBox** from the left-hand side menu, and type a few individual words in the input field labeled *Password Box*. 

In the repro below, the text entered is `123   456`. Double-clicking any of the `*` characters displayed selects the closest 'word' in the underlying value:

![PasswordCharSelection](https://github.com/AvaloniaUI/Avalonia/assets/139133/ca5ffaeb-e270-4dba-b69a-20d7691f3e1c)

### Expected behavior

Double-clicking in a `TextBox` with a `PasswordChar` set should select all text, not just individual words. 

Doing so would match native OS controls behavior (tested on Windows, Linux and MacOS). It might arguably also help users paste or overtype to replace the entire password value, instead of doing so piecewise.

### Avalonia version

11.0.10, 11.0.999-cibuild

### OS

Windows, macOS, Linux

**Comment by timunie** [comment]
@nil4 if you want, a PR is welcome.

**Comment by rabbitism** [comment]
What 'native OS control' are your testing for Windows?

**Comment by nil4** [comment]
The password inputs under Control Panel > User Accounts > Credential Manager and the built-in RDP client `mstsc` authentication dialog are a couple of examples.

**Comment by rabbitism** [comment]
@nil4 Thank you! never notice this feature, I think it's important to avoid potential password pattern leakage.
