### ISSUE TITLE
NativeAOT-compiled app fails to start with `11.1.0-beta1`

### ISSUE THREAD

**Issue by nil4** [AvaloniaUI/Avalonia#14963]
### Describe the bug

NativeAOT-compiled apps built with 11.1.0-beta1 packages throw on initialization and fail to start, on Linux, Mac and Windows. 

This appears to be a regression, as similar apps built with 11.0.10 work as expected.

### To Reproduce

Install latest Avalonia templates (one-time setup):

```shell
> dotnet new install Avalonia.Templates
The following template packages will be installed:
   Avalonia.Templates

Success: Avalonia.Templates::11.0.10.1 installed the following templates: 
[ -- list of installed templates elided -- ]
```

### AOT with 11.0.10

```shell
dotnet new avalonia.app -o TestAppStable   -av 11.0.10
```

Edit the generated project file `TestAppStable.csproj` to add:

```diff
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
+  <PublishAot>true</PublishAot>
```

Publish the app:

```shell
> dotnet publish
MSBuild version 17.9.6+a4ecab324 for .NET
  Determining projects to restore...
  Restored ~/TestAppStable/TestAppStable.csproj (in 176 ms).
  TestAppStable -> ~/TestAppStable/bin/Release/net8.0/linux-arm64/TestAppStable.dll
  Generating native code
[ -- AOT warnings elided -- ]
  TestAppStable -> ~/TestAppStable/bin/Release/net8.0/linux-arm64/publish/
```

Run the app:

```shell
> bin/Release/net8.0/linux-arm64/publish/TestAppStable
```

![image](https://github.com/AvaloniaUI/Avalonia/assets/139133/018af137-5cea-4961-b472-9bd1b521e83e)

### AOT with 11.1-beta1

```shell
dotnet new avalonia.app -o TestAppBeta   -av 11.1.0-beta1
```

Same as before, edit the generated project file `TestAppBeta.csproj` and add `<PublishAot>true</PublishAot>`.

Publish and run the app:

```shell
> dotnet publish
[ -- output elided -- ]
  TestAppBeta -> ~/TestAppBeta/bin/Release/net8.0/linux-arm64/publish/

> bin/Release/net8.0/linux-arm64/publish/TestAppBeta
```

The app fails to start:

```
Unhandled Exception: Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for TestAppBeta.App, make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object) + 0x15c
   at TestAppBeta.App.Initialize() + 0xc
   at Avalonia.AppBuilder.SetupUnsafe() + 0x128
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action`1) + 0x3c
   at TestAppBeta!<BaseAddress>+0x6da0d8
Aborted (core dumped)
```

This reproduces on MacOS (14.4, osx-arm64) with the same message printed to the console.

On Windows 11 (win-arm64), there is no console output, and the application UI does not appear, but the Windows Application Log confirms the app failed to start:

```
Faulting application name: TestAppBeta.exe, version: 1.0.0.0, time stamp: 0x65f1c1d6
Faulting module name: TestAppBeta.exe, version: 1.0.0.0, time stamp: 0x65f1c1d6
Exception code: 0xc0000409
Fault offset: 0x0000000000161e2c
Faulting process id: 0x0x1B80
Faulting application start time: 0x0x1DA75589A211E69
Faulting application path: C:\dev\TestAppBeta\bin\Release\net8.0\win-arm64\publish\TestAppBeta.exe
Faulting module path: C:\dev\TestAppBeta\bin\Release\net8.0\win-arm64\publish\TestAppBeta.exe
```

### Expected behavior

NativeAOT sample apps should run with 11.1.0-beta1 packages, similar to 11.0.10. 

Is there anything specific that needs to be done on 11.1.* to allow NativeAOT-compiled apps to start?

### Avalonia version

11.1.0-beta1

### OS

Windows, macOS, Linux

### Additional context

Environment information (Linux):

```shell
> dotnet --version
8.0.202

> uname -a
Linux ubuntu-linux-22-04-02-desktop 5.15.0-100-generic #110-Ubuntu SMP Wed Feb 7 13:28:04 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by MrJul** [comment]
Thank you for the report!

#14966 should fix it, can you please try the build from that PR once it's available?
I've only tested Windows, but the root cause isn't specific to the environment.

**Comment by nil4** [comment]
Testing with `11.2.999-cibuild0046171-beta` packages confirms the issue is resolved -- thank you!
