### ISSUE TITLE
OpenGlControlBase is missing a method to have the FrameBuffer size for Retina display

### ISSUE THREAD

**Issue by DigitalBox98** [AvaloniaUI/Avalonia#14967]
### Describe the bug

When this control is used on MacOS, if we rely only on the Control's size, there's an issue on the display as below (control's display is divided by 2) : 

<img width="964" alt="avalonia" src="https://github.com/AvaloniaUI/Avalonia/assets/57635141/06787b2f-763c-43c9-b20b-b5b9e8529896">

It's due to a scale factor existing on Retina display between the FrameBuffer's size and the display's size of the OpenGL control.

### To Reproduce

Compile and launch the program below on MacBook Pro  : 
https://github.com/SamboyCoding/OpenTKAvalonia

### Expected behavior

The size of the display should be consistent with the scale factor

### Avalonia version

11.0.9

### OS

macOS

**Comment by maxkatz6** [comment]
That's expected. Don't use scaled control bounds, use pixel size:
```csharp
private PixelSize GetPixelSize()
        {
            var scaling = TopLevel.GetTopLevel(this).RenderScaling;
            return new PixelSize(Math.Max(1, (int)(Bounds.Width * scaling)),
                Math.Max(1, (int)(Bounds.Height * scaling)));
        }
```

**Comment by DigitalBox98** [comment]
Working like a charm, thanks !

**Comment by DannyDS** [comment]
Hi,

I have have a similar issue primarily when using Mac OS

this is using  "gl.Viewport(0, 0, (uint)Bounds.Width, (uint)Bounds.Height);" which works fine on our test Windows and Linux machines

<img width="993" alt="Without scaling" src="https://github.com/AvaloniaUI/Avalonia/assets/6506579/0483a786-9d49-486b-91f7-7bd47b9ab49b">

this is using the solution posted above its much better but still wrong

<img width="995" alt="With scaling" src="https://github.com/AvaloniaUI/Avalonia/assets/6506579/823ab250-477d-4636-aead-729da3e1a8e9">


The grey image in the corner of the green box should be filling the whole screen, do you have any ideas?

Thanks
