### ISSUE TITLE
Allow accessing BindingExpressions to make proper use of `UpdateSourceTrigger=Explicit` 

### ISSUE THREAD

**Issue by timschneeb** [AvaloniaUI/Avalonia#14965]
### Is your feature request related to a problem? Please describe.

I'm trying to use the new `UpdateSourceTrigger=Explicit` parameter for some bindings.

At the moment, I can't seem to find a way to access BindingExpressions for existing bindings defined in XAML, but I need that to call `BindingExpressionBase.UpdateSource`.

### Describe the solution you'd like

WPF has a public API to retrieve binding expressions:
```
control.GetBindingExpression(Control.TargetProperty)
```
Maybe something similar could be implemented.

### Describe alternatives you've considered

--

### Additional context

#13734 also requested this functionality, and although it was closed, there doesn't seem to be any public API for that particular use case yet.

**Comment by timunie** [comment]
@ThePBone which version did you test? 11.1 beta may have that API now

**Comment by ThePBone** [comment]
I tested 11.1 beta-1.
 `UpdateSourceTrigger.Explicit` and `BindingExpressionBase.UpdateSource` are available as mentioned in PR #13970.
However, I don't think there is currently a way to obtain a reference to a BindingExpressionBase for an existing binding using the public API, so the `UpdateSource` method can't actually be accessed, as far as I can see.

**Comment by geferon** [comment]
Any idea when this will be added? I find myself in need of being able to access the binding(s) of a control
