### ISSUE TITLE
[11.1.0-beta1] cross platform Avalonia.Browser project hangs on Splash Screen

### ISSUE THREAD

**Issue by Coz540** [AvaloniaUI/Avalonia#14998]
### Describe the bug

11.1.0-beta1 default template Avalonia.Browser project hangs on Splash Screen

firefox browser - Web Developer tools shows these errors 

12:02:51.459 MONO_WASM: Failed to load config file ./blazor.boot.json SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data 
Ne/<@https://localhost:5001/dotnet.js:3:26612
dotnet.js:3:918
    u https://localhost:5001/dotnet.js:3
    ke https://localhost:5001/dotnet.js:3
    ke https://localhost:5001/dotnet.js:3
    Ne https://localhost:5001/dotnet.js:3
12:02:51.460 Uncaught Error: Failed to load config file ./blazor.boot.json SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data 
    Ne https://localhost:5001/dotnet.js:3
dotnet.js:3:26612
    Ne https://localhost:5001/dotnet.js:3
    AsyncFunctionThrow self-hosted:856
12:02:51.460 Uncaught (in promise) Error: Failed to load config file ./blazor.boot.json SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data 
    Ne https://localhost:5001/dotnet.js:3
5 dotnet.js:3:26612
12:02:58.140 Source map error: request failed with status 404
Resource URL: https://localhost:5001/dotnet.js
Source Map URL: dotnet.js.map
12:02:58.269 Source map error: Error: request failed with status 404
Resource URL: https://localhost:5001/dotnet.js
Source Map URL: dotnet.js.map

### To Reproduce

call dotnet new install Avalonia.Templates

call dotnet new avalonia.xplat -o betaX -av 11.1.0-beta1

build betaX.sln with visual studio2022 in Debug  

set betaX.Browser as startup project 

run project from visual studio 

![image](https://github.com/AvaloniaUI/Avalonia/assets/7672626/f45b4083-d0e8-46ed-819d-f12ff480e2e5)

### Expected behavior

should display welcome to avalonia in browser window. 

similar to 
![image](https://github.com/AvaloniaUI/Avalonia/assets/7672626/18c56590-70eb-4b13-949f-84dd7e03aebb)

### Avalonia version

11.1.0-beta1 

### OS

Windows, WebAssembly

### Additional context

using Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.9.0 and firefox browser 123.0.1 (64-bit)
on 
Windows 11 Home
Version	23H2
OS build	22631.3296

**Comment by MrJul** [comment]
I can't reproduce with the current templates.

This looks like either an old template (unlikely since you have 11.1.0-beta1), or a browser cache issue.
In .NET 8, both .NET and Avalonia are served from the `_framework` folder, which should be reflected at the top of `main.js`: 

```typescript
import { dotnet } from './_framework/dotnet.js'
```

Since you're getting `dotnet.js` from the root, I suspect the browser is using a cached version from a previous project.

**Comment by Coz540** [comment]
@MrJul 
Thank you ! 
  Browser cache was the issue.

**Comment by bharathdpv** [comment]
i am getting same issue. app hangs in splash screen.
![image](https://github.com/user-attachments/assets/9c223364-2da6-438e-afe8-d34d16e7015d)

**Comment by maxkatz6** [comment]
@bharathdpv check browser console
