### ISSUE TITLE
Android: soft keyboard closing prevents Button clicked with ClickMode Release

### ISSUE THREAD

**Issue by msneijders** [AvaloniaUI/Avalonia#15000]
### Describe the bug

The soft keyboard is opened on Android with focus on TextBox. Then tapping a Button, with default ClickMode=Release, does not trigger its Clicked event. The first tap only closes the soft keyboard; a second tap is needed to give a click.

I feel it should do so; the 'native' android apps I tried do trigger click events on buttons, or switching a ToggleSwitch etc., while also closing the softkeyboard with a single tap. Also my app users complain about it; but nvm them thats my problem ;-).

A Button with ClickMode=Press does give a click event with a single tap; I am guessing a pointer released event is being eaten by the softkeyboard close handling?

### To Reproduce

https://github.com/AvaloniaUI/Avalonia/assets/27849065/69405c29-835c-42c4-bef5-f341bb04ba56

A small solution to test:
[AvaloniaOnScreenKeyboard.zip](https://github.com/AvaloniaUI/Avalonia/files/14616425/AvaloniaOnScreenKeyboard.zip)

### Expected behavior

I expect tapping on a Button, ToggleSwitch or Checkbox to work with a single tap when the softkeyboard is opened (and closing that softkeyboard).

### Avalonia version

11.0.10

### OS

Android

**Comment by mosabnasri** [comment]
This bug was fixed on the latest beta release (11.1.0-beta1)

**Comment by msneijders** [comment]
Tested with 11.1.0-beta1: it is indeed fixed already.

Things get fixed so quickly here, I don't even get the chance to complain ;p.
