### ISSUE TITLE
Effects like a Blur\Shadows

### ISSUE THREAD

**Issue by vertexpipeline** [AvaloniaUI/Avalonia#1501]
I want to make a card in Material Design that implies shadow effect. Are there any capabilities to do it?
![image](https://user-images.githubusercontent.com/26230414/38775890-0dcc76f2-4042-11e8-845c-a83fa33235a6.png)
WPF has a Effect Parameter, does Avalonia has something similar?

**Comment by danwalmsley** [comment]
No built in effects yet, perhaps it might be possible with some kind of border and a gradient brush. Would be nice to get support for this though.

**Comment by vertexpipeline** [comment]
How I understood, rendering API doesn't support shaders like in WPF?

**Comment by Sorien** [comment]
You don't need shader support there is sharon effect build in d2d https://msdn.microsoft.com/en-us/library/windows/desktop/hh706334(v=vs.85).aspx and skia https://developer.xamarin.com/api/member/SkiaSharp.SKImageFilter.CreateDropShadow/ but its not implemented in avalonia

**Comment by vertexpipeline** [comment]
Thanks, I'll try to implement this feature where I can

**Comment by maxkatz6** [comment]
Just for case, there is BoxShadow in Avalonia 0.10+
https://github.com/AvaloniaUI/Avalonia/pull/3871

Although there still no convenient in-app blur.

**Comment by balthild** [comment]
In Avalonia v0.10.0-rc1, If I wrap BoxShadow value into multiple lines, for example,

```xaml
                    <Setter Property="BoxShadow">
                        <Setter.Value>
                            inset -1 0 1 -1 #10000000,
                            inset -2 0 2 -2 #20000000,
                            inset -6 0 6 -6 #16000000,
                            inset -16 0 16 -16 #16000000
                        </Setter.Value>
                    </Setter>
```

then the view cannot load (but don't throw any exceptions). Is this intended?

**Comment by maxkatz6** [comment]
> but don't throw any exceptions

It throws:
System.FormatException: 'One of the identified items was in an invalid format.'
    Avalonia.Media.BoxShadow.Parse(string)
    Avalonia.Media.BoxShadows.Parse(string)

**Comment by balthild** [comment]
Oh, sorry... Didn't noticed that the exception is caught internally.

In CSS, newlines are allowed between tokens for all property, but not inside quoted values. Sometimes newlines are useful for keeping code tidy. The following code is valid in Chrome and Firefox:

```css
.ugly-syntax {
  box-shadow: 10px  
      5px         5px
   blue,
-10px -10px 4px
   red;
font-family: Segoe
                UI, sans-serif;
}
```

and this does not:

```css
.invalid-syntax {
font-family: "Segoe
                UI", sans-serif;
}
```

**Comment by maxkatz6** [comment]
We have BoxShadow for a while and now we have effects `Effect="blue(10)"` syntax in 11.0
