### ISSUE TITLE
Pencil usage on iPads is broken (possibly mouse usage as well)

### ISSUE THREAD

**Issue by Amenti** [AvaloniaUI/Avalonia#15011]
### Describe the bug

Clicks from the Apple Pencil are ignored since at least 11.1.0-beta1. This still works on 10.0.10.

### To Reproduce

- Create simple iOS-App
- Add Button to app with a Command or Click event
- Click on it with an Apple Pencil or alternatively with the iPad Simulator with active "Capture Pointer" mode
- The button does nothing but stays pressed

I added a very simple sample app to show the behavior.

[PencilTestSampleApp.zip](https://github.com/AvaloniaUI/Avalonia/files/14623468/PencilTestSampleApp.zip)

### Expected behavior

- When the Button is clicked Commands are executed
- Button is "released" afterwards and doesn't stay pressed

### Avalonia version

11.1.0-beta1

### OS

iOS

**Comment by maxkatz6** [comment]
I have good and bad news after testing on my ipad.
Good: mouse input work fine.
Bad: my pencil seems to be dead at 0% without being able to charge back.

**Comment by Amenti** [comment]
> I have good and bad news after testing on my ipad. Good: mouse input work fine. Bad: my pencil seems to be dead at 0% without being able to charge back.

You can simulate the Pencil problem via the iPad simulator when you click "Capture Pointer". The behavior is the same.

**Comment by maxkatz6** [comment]
@Amenti thanks, I was able to reproduce it and fix it.
Although I still don't know what's an issue with iOS-on-macOS installation.

**Comment by Amenti** [comment]
> @Amenti thanks, I was able to reproduce it and fix it. Although I still don't know what's an issue with iOS-on-macOS installation.

Thanks. I'll try and test if your fix also solves this problem.
