### ISSUE TITLE
AvaloniaMainActivity should allow customized App factory

### ISSUE THREAD

**Issue by AArnott** [AvaloniaUI/Avalonia#15010]
### Is your feature request related to a problem? Please describe.

Desktop apps can call `AppBuilder.Configure` in order to provide a custom factory for their `App` construction. But Android apps only get to override `CustomizeAppBuilder` which is beyond the point of calling the static `Configure` method. As a result, my app non-default constructor can't be called on Android.

### Describe the solution you'd like

`AvaloniaMainActivity.CreateAppBuilder` could be made `virtual`. Then I could override it.

### Describe alternatives you've considered

I guess I can just discard the `AppBuilder` instance passed in and create my own:

```cs
protected override AppBuilder CustomizeAppBuilder(AppBuilder builder)
{
	// Discard the builder we're given because we want to call the non-default App constructor.
	return base.CustomizeAppBuilder(AppBuilder.Configure(() => new App(PrepareAppPlatformSettings(), new WindowsPlatformServices())))
		.WithInterFont()
		.UseReactiveUI();
}
```

**Comment by maxkatz6** [comment]
Same could be applied for iOS https://github.com/AvaloniaUI/Avalonia/blob/84b06b22d4a62043d1fda56db7ced5ce9d722a6f/src/iOS/Avalonia.iOS/AvaloniaAppDelegate.cs#L45
And Tizen https://github.com/AvaloniaUI/Avalonia/blob/84b06b22d4a62043d1fda56db7ced5ce9d722a6f/src/Tizen/Avalonia.Tizen/NuiTizenApplication.cs#L58

**Comment by timunie** [comment]
@AArnott in case you want to PR that, this would be appreciated.

**Comment by maxkatz6** [comment]
I will pick it up, since I am already changing related initialization code a bit.

**Comment by maxkatz6** [comment]
CreateAppBuilder is virtual now.
