### ISSUE TITLE
Renderers doesn't respect window scaling

### ISSUE THREAD

**Issue by Sorien** [AvaloniaUI/Avalonia#1502]
when scaling is set to different value from 1 (hidpi support where effective dpi > 96)

![image](https://user-images.githubusercontent.com/1270275/38794893-e1afadda-4156-11e8-94cf-1b7b9891a4ad.png)

**Comment by kekekeks** [comment]
Are you using wayland or something?

**Comment by Sorien** [comment]
win 10, hmm it seems to be working now, don't know know what happened
