### ISSUE TITLE
The last Korean character is removed after pressing space or enter. (Windows 10 Home)

### ISSUE THREAD

**Issue by calee88** [AvaloniaUI/Avalonia#15023]
### Describe the bug

While I am typing Korean in a TextBox, if I press space or enter key, the last character is removed.
This bug occurs in the version 11.0.5 or higher.
It is okay in 11.0.4.

### To Reproduce

```bash
# Create a project.
dotnet new avalonia.xplat -av 11.0.10 -o KoreanTextBoxTest
```
Change TextBlock to TextBox in a file: KoreanTextBoxTest\Views\MainView.axaml
```bash
# Run the program.
cd KoreanTextBoxTest.Desktop
dotnet build
dotnet bin\\Debug\\net8.0\\KoreanTextBoxTest.Desktop.dll
```
Type any Korean and press space or enter key.

### Expected behavior

Typed characters should not be deleted after pressing space or enter key.

### Avalonia version

11.0.5~11.0.10

### OS

Windows 10 Home

**Comment by timunie** [comment]
can you test 11.1-beta as well?

**Comment by calee88** [comment]
It is fine on 11.1.0-beta1. Thank you! I am closing the issue.
