### ISSUE TITLE
Cannot build browser version

### ISSUE THREAD

**Issue by Templayer** [AvaloniaUI/Avalonia#15022]
### Describe the bug

The default Rider Avalonia template fails to build the browser version.

Stacktrace: 
[Urtica3 Browser Build Failure Stacktrace.txt](https://github.com/AvaloniaUI/Avalonia/files/14633924/Urtica3.Browser.Build.Failure.Stacktrace.txt)

### To Reproduce

Build a Browser template under Linux Mint, presumably. :)

### Expected behavior

Successful build.

### Avalonia version

11.1.0-beta1

### OS

WebAssembly

### Additional context

![image](https://github.com/AvaloniaUI/Avalonia/assets/11728067/83d33ff2-d229-4ff7-9ea2-7bdcd4a69363)

NAME="Linux Mint"
VERSION="21.3 (Virginia)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.3"
VERSION_ID="21.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=virginia
UBUNTU_CODENAME=jammy

JetBrains Rider 2023.3.4
Build #RD-233.14475.66, built on March 6, 2024
Subscription is active until November 17, 2024.
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-25-generic
.NET Core v7.0.10 x64
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
  editor.config.csharp.support=true
Non-Bundled Plugins:
  com.intellij.javafx (1.0.4)
  com.intellij.resharper.HeapAllocationsViewer (2023.3.0)
  avalonia-rider (1.3.0.126)
  com.intellij.ideolog (222.2.0.0)
  com.jetbrains.rider.android (233.11799.261)
  com.codeium.intellij (1.4.22)
  Statistic (4.2.7)
  com.intellij.resharper.StructuredLogging (2023.3.0.315-eap04)
  com.github.syuchan1005.emojiprefix (2.2.1)
  mobi.hsz.idea.gitignore (4.5.2)
  com.intellij.resharper.azure (3.50.0.1755-2023.3)
Current Desktop: X-Cinnamon

**Comment by Templayer** [comment]
That Blazor there was my attempt to switch it to legacy web version, which didn't change anything, so I reverted my changes. Except for forgetting to uninstall the Blazor package.

**Comment by timunie** [comment]
could you try nightly builds?

**Comment by Templayer** [comment]
> could you try nightly builds?

It took me quite some time updating NuGet packages to the newest beta, and it was quite frustrating, so I would like to avoid that for now. :p

**Comment by timunie** [comment]
well if it is fixed in nightly, you will have to wait for it to be released as next stable version.

**Comment by maxkatz6** [comment]
Latest templates worked with both 11.0 and 11.1 versions. Can't really read these localized log files.
But this csproj on the screenshot is definitely not from the templates. 
Would recommend recreating project.

**Comment by Templayer** [comment]
> Latest templates worked with both 11.0 and 11.1 versions. Can't really read these localized log files. But this csproj on the screenshot is definitely not from the templates. Would recommend recreating project.

Oh, how I love when people close issues without them being solved. Especially when they don't even read the log file. The problematic parts seem not to be localized.

But hey, another Issue closed, what a great day! Must be great to work like that.
