### ISSUE TITLE
Viewbox in ComboBox.ItemTemplate not working correctly

### ISSUE THREAD

**Issue by StefanKoell** [AvaloniaUI/Avalonia#15032]
### Describe the bug

Using a Viewbox in the ComboBox.ItemTemplate doesn't render its content in the selected item visual at all. The dropdown items render correctly:

![image](https://github.com/AvaloniaUI/Avalonia/assets/6168777/d8a9089e-cc84-4ff4-82c3-8c658941c627)

### To Reproduce

Simply use a Viewbox element in the ItemTemplate, like this:
```xml
<ComboBox.ItemTemplate>
    <DataTemplate x:DataType="models:LanguageItem">
        <DockPanel Margin="2">
            <Viewbox DockPanel.Dock="Left" Margin="0 0 8 0" Width="16" Height="16" Child="{Binding Icon}" />
            <TextBlock FontStyle="Italic" Text="{Binding Text}" TextTrimming="CharacterEllipsis" />
        </DockPanel>
    </DataTemplate>
</ComboBox.ItemTemplate>
```

### Expected behavior

Also render the Viewbox content in the selected item visual.

### Avalonia version

11.0.10, 11.1.0-beta1, nightly

### OS

Windows

### Additional context

The Viewbox child in my case is an IconElement (descendent of Control).

**Comment by MrJul** [comment]
`ViewBox` isn't the problem here.

You're trying to have a single control instance (your `IconElement` through the `{Binding Icon}`) displayed in several places at once, which isn't possible.

I would suggest having `Icon` be a `Geometry` instead, and display it through a `PathIcon` or `Path`:
```
<ComboBox.ItemTemplate>
    <DataTemplate x:DataType="models:LanguageItem">
        <DockPanel Margin="2">
            <PathIcon DockPanel.Dock="Left" Margin="0 0 8 0" Width="16" Height="16" Data="{Binding Icon}" />
            <TextBlock FontStyle="Italic" Text="{Binding Text}" TextTrimming="CharacterEllipsis" />
        </DockPanel>
    </DataTemplate>
</ComboBox.ItemTemplate>
```

**Comment by StefanKoell** [comment]
Now that you mention that, it makes perfectly sense. For some use cases I was able to replace the Viewbox with an Image control and bind the Source to a DrawingImage (or whatever is needed to be displayed). Having the IconElement base class in a Viewbox has a couple of benefits (see Menu.Icon for example). There are various descendants (including some of my own implementations) of IconElements which allows me to have multiple different image sources for several scenarios. Sometimes it's possible to use a PathIcon or Path but sometimes I have a bitmap or SvgImage or a custom control I need to display.

So the question is, can we somehow enable this scenario for the ComboBox? Maybe a dedicated template for the SelectedItem visual where I can do a binding to a dedicated instance of the selected Viewbox child?

**Comment by MrJul** [comment]
That would be akin to WPF's `SelectionBoxItemTemplate`, but settable.

You can have something similar right now that by changing the template through style:
```xaml
<Style Selector="ComboBox /template/ ContentControl#ContentPresenter">
    <Style Selector="ContentTemplate" Value="{StaticResource YourTemplateHere}" />
</Style>
```

As an alternative solution, instead of having the `Icon` property be a control, you can set it to non-visual value, such as `IImage`, `Geometry` (or some custom class defining the icon in a more abstract way) and rely on data templates. For example:
```xaml
<Window.DataTemplates>
  <DataTemplate DataType="IImage">
    <Image Source="{Binding}" />
  </DataTemplate>
  <DataTemplate DataType="Geometry">
    <Path Data="{Binding}" />
  </DataTemplate>
</Window.DataTemplates>
```

**Comment by StefanKoell** [comment]
Thanks for the input, @MrJul 
That's really helpful. I will play around and I'm sure I will find a good solution. Thanks again, much apprecuated!
