### ISSUE TITLE
Transparent window on Linux ARM-64

### ISSUE THREAD

**Issue by AlphaBs** [AvaloniaUI/Avalonia#15040]
### Describe the bug

it doesn't show anything. 
![Screenshot_20240319_224110_TermuxX11](https://github.com/AvaloniaUI/Avalonia/assets/17783561/385adae6-1bba-4e13-ba4a-1c0e69b749ef)

### To Reproduce

```
dotnet new avalonia.mvvm
dotnet run
```

### Expected behavior

show UI elements

### Avalonia version

11.0.10

### OS

Linux

### Additional context

Ubuntu 22.04.3 LTS, Xfce 4.18
CPU: Snapdragon 8 Gen1 SM8450
GPU: Adreno 730

I'm using Termux PRoot to boot Linux distro in Android. and also using virgl to accelerate the GPU.

**Comment by geferon** [comment]
Having this issue too on Windows

**Comment by dovydasm** [comment]
Same issue on Windows after updating packages from 11.0.2 to 11.0.10. Adding Avalonia.Skia nuget fixed it for me.
