### ISSUE TITLE
Unable to paste multiple lines of text into a TextBox

### ISSUE THREAD

**Issue by hfjooste** [AvaloniaUI/Avalonia#15041]
### Describe the bug

I'm unable to paste multiple lines of text into a TextBox. Only the first line is pasted and the rest is ignored

### To Reproduce

1. Create a simple UI with a TextBox control (no need to set any properties on the TextBox)
2. Copy multiple lines of text
3. Paste the text into the TextBox

### Expected behavior

All the text is pasted into the TextBox

### Avalonia version

11.0.9, 11.0.10

### OS

Windows

### Additional context

It seems like this bug was introduced in v11.0.9. I've downgraded to 11.0.8 without changing any code and everything works as expected on that version.

**Comment by rabbitism** [comment]
Expected, introduced in this PR.
https://github.com/AvaloniaUI/Avalonia/pull/14173

**Comment by maxkatz6** [comment]
@hfjooste does it work, if you set AcceptsReturn=true?

**Comment by hfjooste** [comment]
Thanks @rabbitism @maxkatz6 

I wasn't aware of this change. Everything works as expected on the latest version after adding AcceptsReturn=true
