### ISSUE TITLE
Converter will be reached only once - when application starts

### ISSUE THREAD

**Issue by FuadNagiyev** [AvaloniaUI/Avalonia#1504]
Hello,

first of all - I'm really new to Avalonia.
I noticed that Converters will not be reached after initialization. 
So what I want to do is - make many configuration text Boxes visible, when there is an input in a specified TextBox.
Example:
This is my Xaml Code

`<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="clr-namespace:ApplicationConfigurator.ViewModels;assembly=ApplicationConfigurator"
        xmlns:local="clr-namespace:ApplicationConfigurator.Converter;assembly=ApplicationConfigurator"
        Icon="resm:ApplicationConfigurator.Assets.avalonia-logo.ico"
        Title="ApplicationConfigurator"
        Width="800"
        Height="400">
  <Window.Resources>
    <local:StringToBooleanConverter x:Key="StringToBooleanConverter"/>
  </Window.Resources>
  <Design.DataContext>
    <vm:MainWindowViewModel/>
  </Design.DataContext>

    <Grid RowDefinitions="Auto, Auto, Auto, Auto, *" ColumnDefinitions="Auto, *">

      
      <TextBlock Grid.Row="0" Grid.Column="0" Text="TestApplication Path: "/>
      <TextBox Grid.Row="0" Grid.Column="1" Text="{Binding TestApplicationPath}"/>

      
      <TextBlock Grid.Row="1" Grid.Column="0" Text="MongoDB Path: "/>
      <TextBox Grid.Row="1" Grid.Column="1" Text="{Binding MongoDbPath}"/>

      
      <TextBlock Grid.Row="2" Grid.Column="0" Text="EventStore Path: "/>
      <TextBox Grid.Row="2" Grid.Column="1" Text="{Binding EventStorePath}"/>
    </Grid>
    
    
    <Grid RowDefinitions="Auto, Auto, Auto, Auto, Auto, *" ColumnDefinitions="*, *" Margin="0,15,0,5" IsVisible="{Binding TestApplicationPath, Converter={StaticResource StringToBooleanConverter}}">
      <TextBlock Grid.Row="0" Grid.ColumnSpan="2" Text="MongoDB Connection Configuration" Margin="0,0,0,5" HorizontalAlignment="Center"/>
      
      
      <TextBlock Grid.Row="1" Grid.Column="0" Text="Username:" />
      <TextBox Grid.Row="1" Grid.Column="1" Text="{Binding MongoDbUsername}" />

      
      <TextBlock Grid.Row="2" Grid.Column="0" Text="Password:" />
      <TextBox Grid.Row="2" Grid.Column="1" Text="{Binding MongoDbPassword}" />

      
      <TextBlock Grid.Row="3" Grid.Column="0" Text="Database:" />
      <TextBox Grid.Row="3" Grid.Column="1" Text="{Binding MongoDbDatabase}" />

      
      <TextBlock Grid.Row="4" Grid.Column="0" Text="Host:" />
      <TextBox Grid.Row="4" Grid.Column="1" Text="{Binding MongoDbHost}" />

      
      <TextBlock Grid.Row="5" Grid.Column="0" Text="Port:" />
      <TextBox Grid.Row="5" Grid.Column="1" Text="{Binding MongoDbPort}" />
      
    </Grid>`

This is my Converter:
` public class StringToBooleanConverter : IValueConverter
    {
      public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
      {
        var stringValue = value.ToString();
        return !string.IsNullOrEmpty(stringValue) && !string.IsNullOrWhiteSpace(stringValue);
      }

      public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
      {
        throw new NotImplementedException();
      }
    }`

When I write something into the TestApplicationPath TextBox, which is binded to a property in the ViewModel - my other two grids will not be "rerendered", so that the visibility turns true.

**Comment by ahopper** [comment]
How is TestApplicationPath defined? 
Does it notify changes eg https://github.com/AvaloniaUI/Avalonia/blob/25b92e83f4fdef2d74a44c18f0fa3cb2da070e21/samples/BindingTest/ViewModels/MainWindowViewModel.cs#L73-L77
Converters work ok for me.

**Comment by FuadNagiyev** [comment]
in the ViewModel
`private string _testApplicationPath= string.Empty;
public string TestApplicationPath
    {
      get => _testApplicationPath;
      set => SetProperty(ref _testApplicationPath, value);
    }`

my ViewModel inherits from ViewModelBase, which hase following additions from my side: 
`public class ViewModelBase : ReactiveObject
  {
    public event PropertyChangedEventHandler PropertyChanged;

    /// <summary>
    /// This method sets the value of a property to the value. Additionally it fires the PropertyChanged method
    /// which is important for Bindings.
    /// </summary>
    public void SetProperty<T>(ref T property, T value, [CallerMemberName]string propertyName = null)
    {
      if (EqualityComparer<T>.Default.Equals(property, value)) { return; }
      property = value;
      RaisePropertyChanged(propertyName);
    }

    public void RaisePropertyChanged(string propertyName)
    {
      PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
  }`

**Comment by FuadNagiyev** [comment]
ahh ok - I have tried it with the RaiseAndSetIfChanged - and it is working well.
I think my WPF Background was making trouble this time.
Thanks a lot. I will close this issue then.
