### ISSUE TITLE
Query FontManager for all available fonts

### ISSUE THREAD

**Issue by appel1** [AvaloniaUI/Avalonia#15067]
### Is your feature request related to a problem? Please describe.

Currently there's only a SytemFonts property but that is not very helpful when running in a browser since it will only ever contain Noto Mono. It would be useful if there was a way to query FontManager for all available fonts. 

### Describe the solution you'd like

Not sure what would make the most sense but maybe an AllFonts property. 
```csharp
public IEnumerable<FontFamily> AllFonts { get; }
```

### Describe alternatives you've considered

The current workaround is to keep track of our IFontCollection instances elsewhere in addition to FontManager.

**Comment by Gillibald** [comment]
You can replace the system font collection with your own

**Comment by appel1** [comment]
Good idea, wasn't aware of that since the key was internal but of course I can create an Uri with the same string as key. 

Is there any way to get around having to prefix all font names with `fonts:SystemFonts#` now that I've overridden the system fonts collection?

**Comment by appel1** [comment]
Ok, that works.
