### ISSUE TITLE
Multibinding with Converter handles Enum Value as AvaloniaProperty.UnsetValue

### ISSUE THREAD

**Issue by HHHChrist** [AvaloniaUI/Avalonia#15076]
### Describe the bug

Using this converter
`	class SelectIconConverter : ADC.IMultiValueConverter
	{
		public object? Convert(IList<object?> values, Type targetType, object? parameter, CultureInfo culture)
		{
			if (values.Count != 3) return null;
			if (values[0] is not bool IsToggled) return null;
			if (values[1] is not Icon Untoggled) return null;
			if (values[2] is not Icon Toggled) return null;
			return IsToggled ? Toggled : Untoggled;
		}
	}`
and the enum Icon the Multibinding handles a valid enum value as an Unset Value.
![image](https://github.com/AvaloniaUI/Avalonia/assets/45006101/81d8a14a-0c17-4e8e-a162-b2376e0f97de)
Code is in Avalonia.Data.Multibinding

### To Reproduce

Make a multiconverter, which takes a bool and two Enum Values to select from.
Pass this Converter to an Property by Code.

### Expected behavior

obj is not UnsetValue, so it should return obj an not FallbackValue

### Avalonia version

11.0.10

### OS

Windows

**Comment by timunie** [comment]
file a minimum sample to reproduce please. Thanks.

**Comment by HHHChrist** [comment]
In my Test Project everything works fine. Also, the so Value to return gets set to the calced obj.
There are other Problems but not for this issue, so I close this ticket.
Anyway thanks.
