### ISSUE TITLE
11.1.0-beta1 Exception occurred while editing DataGrid

### ISSUE THREAD

**Issue by WillisXue** [AvaloniaUI/Avalonia#15081]
### Describe the bug

Exception occurred while editing DataGrid
![image](https://github.com/AvaloniaUI/Avalonia/assets/9125768/e0ada198-6b60-4681-9087-73111d6587f1)

### To Reproduce

[DataGridEditingIssue.zip](https://github.com/AvaloniaUI/Avalonia/files/14720492/DataGridEditingIssue.zip)

### Expected behavior

no exception 

### Avalonia version

11.1.0-beta1

**Comment by timunie** [comment]
consider using DataGridTemplateColumn
