### ISSUE TITLE
Moving an item in an ObservableCollection has no effect on a DataGrid

### ISSUE THREAD

**Issue by Dmitrii-a11** [AvaloniaUI/Avalonia#15102]
### Describe the bug

After calling the Move method on an ObservsbleCollection, DataGrid won't change.

### To Reproduce

[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/14734765/AvaloniaApplication1.zip)

### Expected behavior

Excpected a new position of a row after calling the Move method on an ObservableCollection

### Avalonia version

11.0.2

### OS

Windows

**Comment by rabbitism** [comment]
IIRC it's not implemented at all. You are welcomed to file a PR if you know how to implement this.

**Comment by maxkatz6** [comment]
Yeah, move is not supported. Remove and add is supported though.

**Comment by ltetak** [comment]
ref https://github.com/AvaloniaUI/Avalonia/issues/3606

**Comment by timunie** [comment]
closing as duplicate
