### ISSUE TITLE
IEnumerable ICommand couldn't be bound in 11.1.0-beta1

### ISSUE THREAD

**Issue by rtazaki** [AvaloniaUI/Avalonia#15101]
### Describe the bug

- I have an array of command to binding multiple commands.
- Availability of this varies between 11.0.10 and 11.1.0-beta-1.

### To Reproduce

![CommandCollectionTest](https://github.com/AvaloniaUI/Avalonia/assets/19927260/52e73859-f07b-4339-b3ad-7b0a0152656e)

### Expected behavior

![CommandCollectionTest](https://github.com/AvaloniaUI/Avalonia/assets/19927260/f1e01bba-7d6a-4035-bfc2-728c0355ff4d)

### Avalonia version

11.1.0-beta1

### OS

Windows

**Comment by rtazaki** [comment]
[CommandCollectionTest.zip](https://github.com/AvaloniaUI/Avalonia/files/14734477/CommandCollectionTest.zip)

**Comment by rtazaki** [comment]
- The products I manage work around this problem by using CommandParameter.
(This is because you can use switch-cases to split the processing within a single command, rather than having multiple commands for each processing.)
- However, CommandParameter cannot pass multiple values(?), so must specify another command in this case.

**Comment by stevemonaco** [comment]
I can repro, so this is probably a regression from the binding system rework in 11.1?

It's a strange pattern to me. You should avoid iterating `IEnumerable`s multiple times which is what happens when you index. It works in 11.1-beta if you expose it as an array instead: `public ICommand[] SomeCommands { get; }`

**Comment by rtazaki** [comment]
> public ICommand[] SomeCommands { get; }
- It worked correctly.  Thanks.
> IEnumerables multiple times which is what happens when you index.
- Yes. And since it seems to be working fine at times, I decided to check it carefully in my project.
- This modification also worked.
## wrong

```cs
        SomeCommands =
        [
            ReactiveCommand.Create(() => Results[0]="Hello"),
            ReactiveCommand.Create(() => Results[1]="World!"),
        ];
```
## correct

```cs
        SomeCommands = new ObservableCollection<ICommand>
        {
            ReactiveCommand.Create(() => Results[0]="Hello"),
            ReactiveCommand.Create(() => Results[1]="World!"),
        };
```

**Comment by timunie** [comment]
> - However, CommandParameter cannot pass multiple values(?), so must specify another command in this case.

It can. Use MultiBinding.

**Comment by rtazaki** [comment]
> > * However, CommandParameter cannot pass multiple values(?), so must specify another command in this case.
> 
> It can. Use MultiBinding.
Thanks, but using converters for MultiBinding is a pain.
(like a behavior)
I wonder if I can write it a little better if I use QuickConverter?

**Comment by rtazaki** [comment]
Now that I know the steps to reproduce and the solution, I would like to close this ticket.
