### ISSUE TITLE
NameScope is completed, no further registrations are allowed

### ISSUE THREAD

**Issue by startewho** [AvaloniaUI/Avalonia#15126]
### Describe the bug

I use the x:Name in a UserControl like this:

```xaml
<Grid Grid.Row="2" >
	<Border Margin="14,0"  Grid.Row="0" BorderBrush="{StaticResource BgMainColor}" BorderThickness="0,2">
		<StackPanel HorizontalAlignment="Center" Orientation="Horizontal" >
			<Button x:Name="okButton" Command="{Binding Confirm}" Margin="10,0" HotKey="Enter"  CommandParameter="true">
				<Image Source="/Assets/ok.png"/>
			</Button>
			<Button  Command="{Binding Confirm}" Margin="10,0" HotKey="Escape" CommandParameter="false">
				<Image Source="/Assets/cancel.png"/>
			</Button>
		</StackPanel>
	</Border>

</Grid>
```
and in the cs file it like this:

```cs
protected override void OnLoaded(RoutedEventArgs e)
{
    base.OnLoaded(e);
    okButton.Focus();
}
```

the  design  preview  can not work ,it show the message 

    NameScope is completed, no further registrations are allowed

But when i run ,it normal work.so i think maybe a but or something else i missed set.

### To Reproduce

As the describe

### Expected behavior

design preview works

### Avalonia version

11.0.10

### OS

Windows

**Comment by maxkatz6** [comment]
1. I can't reproduce this issue with your code. Do you have a minimal sample? 
2. Is there any stacktrace maybe? Check Avalonia Previewer logs in the output window (in VS it can be switched via drop down).

**Comment by startewho** [comment]
Sorry to the misinform,i found the reason because i  invoke the 
   
   AvaloniaXamlLoader.Load(this);

twice. and the reason because the update frome 0.10 to 11 .i  use the old template like this

```cs
public partial class CurrentTimeView : UserControl
{
    public CurrentTimeView()
    {
        InitializeComponent();
        AvaloniaXamlLoader.Load(this);
    }

    private void InitializeComponent()
    {
        AvaloniaXamlLoader.Load(this);
    }
}
```

**Comment by startewho** [comment]
the name generator is  so cute and great. thanks  a lot
