### ISSUE TITLE
Unable to bind to $self attached property in theme styles

### ISSUE THREAD

**Issue by KatterMaw** [AvaloniaUI/Avalonia#15129]
### Describe the bug

when using a setter with binding to attached properties using `$self`, an exception will be thrown about an unresolved namespace which is used in styles's file when using a control with this style in some view, even if you add this namespace in the view's file.

### To Reproduce

Clone and run [repro](https://github.com/KatterMaw/AvaloniaSelfBindingAttachedPropertyBugRepro), an exception "Unable to resolve namespace for type assists:ButtonAssist" ([full](https://gist.github.com/KatterMaw/3ca1406e7850e0272fc7d303b4047dd6)) will be thrown.

### Expected behavior

The control will be shown without an exception, as if this binding were used, for example, through TemplateBinding (which is impossible in this context because this setter is outside of the template)

### Avalonia version

11.0.10, 11.2.999-cibuild0046614-alpha

### OS

Windows

### Additional context

![rider64_F4Xku9GeVz](https://github.com/AvaloniaUI/Avalonia/assets/68691636/6413bb3a-ea1d-4819-a2e3-0551ed763c61)
Style used: https://github.com/KatterMaw/AvaloniaSelfBindingAttachedPropertyBugRepro/blob/master/ThemesProject/Controls/Button.axaml
Problematic lines is [71](https://github.com/KatterMaw/AvaloniaSelfBindingAttachedPropertyBugRepro/blob/fa97263f7d3d54e1110ac6cf0fd03b83a73fbadd/ThemesProject/Controls/Button.axaml#L71) and [76](https://github.com/KatterMaw/AvaloniaSelfBindingAttachedPropertyBugRepro/blob/fa97263f7d3d54e1110ac6cf0fd03b83a73fbadd/ThemesProject/Controls/Button.axaml#L76). They can be removed, the exception will not be thrown, but accordingly the required behavior will also not be.

This can be avoided by using simple styles with selectors such as :pointerover and :pressed instead of attached properties, but using attached properties in my situation, can make a less cluttered and more flexible definition of styles.

**Comment by maxkatz6** [comment]
This error shouldn't be reproducible with Compiled Bindings enabled. Which is generally a recommended way to use bindings in Avalonia.

Another possible workaround might be to specify assembly name in `xmlns:assists="clr-namespace:Sightful.Avalonia.Theme.Assists"`.

**Comment by KatterMaw** [comment]
> This error shouldn't be reproducible with Compiled Bindings enabled. Which is generally a recommended way to use bindings in Avalonia.

compiled bindings have already been [enabled](https://github.com/KatterMaw/AvaloniaSelfBindingAttachedPropertyBugRepro/blob/fa97263f7d3d54e1110ac6cf0fd03b83a73fbadd/AvaloniaSelfBindingAttachedPropertyBugRepro/AvaloniaSelfBindingAttachedPropertyBugRepro.csproj#L8) in the app project, [enabling](https://github.com/KatterMaw/AvaloniaSelfBindingAttachedPropertyBugRepro/blob/master/ThemesProject/ThemesProject.csproj) it in the theme project apparently solves the issue.

> Another possible workaround might be to specify assembly name in `xmlns:assists="clr-namespace:Sightful.Avalonia.Theme.Assists"`.

Specifying using with the assembly neither in the [MainWindow.xaml](https://github.com/KatterMaw/AvaloniaSelfBindingAttachedPropertyBugRepro/blob/master/AvaloniaSelfBindingAttachedPropertyBugRepro/Views/MainWindow.axaml), nor in the [App.xaml](https://github.com/KatterMaw/AvaloniaSelfBindingAttachedPropertyBugRepro/blob/master/AvaloniaSelfBindingAttachedPropertyBugRepro/App.axaml), nor in the [Button.xaml](https://github.com/KatterMaw/AvaloniaSelfBindingAttachedPropertyBugRepro/blob/master/ThemesProject/Controls/Button.axaml) did not help.

However, compiled bindings are suitable in my case anyway.
