### ISSUE TITLE
[DataGrid] Add DataGridRow.IsSelected

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#15176]
### Is your feature request related to a problem? Please describe.

Allow Xaml like this:

```xaml
  <Style Selector="DataGridRow">
	<Setter Property="Header">
	  <Setter.Value>
		<Template>
		  <CheckBox IsChecked="{Binding $parent[DataGridRow].IsSelected}"/>
		</Template>
	  </Setter.Value>
	</Setter>
  </Style> 
```

### Describe the solution you'd like

Add IsSelected  StyledProperty to DataGridRow

**Comment by jpgarza93** [comment]
This would be great to be able to notify the ViewModel about selected items in a straightforward way

**Comment by dowdybrown** [comment]
With this change, can DataGridRow.IsSelected be bound to a bool property in the ItemSource? If so, what is the syntax? I am using 11.1.2.
