### ISSUE TITLE
Linux DRM not working after apt-upgrade

### ISSUE THREAD

**Issue by MultiXaNos** [AvaloniaUI/Avalonia#15186]
### Describe the bug

Hi,

I just tried to upgrade my RPi and then I wasn't able to run my program again and I have this error : 

![image](https://github.com/AvaloniaUI/Avalonia/assets/59912908/96017241-ce8e-4816-b0d4-f28f15383439)

Thanks for help !

### To Reproduce

Run apt-upgrade
Try to run your program

### Avalonia version

11.1.10

### OS

Linux

**Comment by thevortexcloud** [comment]
Are you using AOT by any chance? If so you may need to rebuild your app.

**Comment by MultiXaNos** [comment]
> Are you using AOT by any chance? If so you may need to rebuild your app.

Yeah I'm definitely using AOT ! I already tried to rebuild my app but it is still not working.
But if I'm using Linux FBDev as startup method it's currently working...

**Comment by thevortexcloud** [comment]
There might be a breaking change in a native library then. I am not sure though. On a side note, it would probably help if you mentioned which distro you are using. EG Raspberry Pi OS or Ubuntu. Raspberry Pi OS is directly based on Debian for example, as such it has older packages than Ubuntu.

**Comment by MultiXaNos** [comment]
> There might be a breaking change in a native library then. I am not sure though. On a side note, it would probably help if you mentioned which distro you are using. EG Raspberry Pi OS or Ubuntu. Raspberry Pi OS is directly based on Debian for example, as such it generally has older packages than Ubuntu.
> 
> I am guessing that error message is related to this:
> 
> https://github.com/AvaloniaUI/Avalonia/blob/c3aecf67f65931813c9cb626834f324471f1ea00/src/Linux/Avalonia.LinuxFramebuffer/Output/Drm.cs#L157-L158
> 
> Which is a call into `libdrm`. So also sharing what version of libdrm you have would also be helpful for anybody trying to debug this.

I finally get it working ! 
I was using UseManagedSystemDialogs() in BuildAvaloniaApp() method, by removing this piece of code it was working successfully.

Next time I will add which distro I'm using, but yes I am using Raspberry Pi OS Lite :)

**Comment by timunie** [comment]
@MultiXaNos can we close this ticket if you found out how to run Avalonia? Probably a docs update is welcome though if that's something needed for a special device.

**Comment by kekekeks** [comment]
With RPi one needs to specify the card directly, otherwise auto-detection will pick /dev/dri/card0 which isn't connected to any outputs
