### ISSUE TITLE
MonoMac crash under mono32

### ISSUE THREAD

**Issue by jfmherokiller** [AvaloniaUI/Avalonia#1518]
It seems I found a corner case in the MonoMac backend when its run under mono32.
Stacktrace can be found here: https://pastebin.com/mfjg0kYX

Mono Version Info:
```
➜ mono32 --version
Mono JIT compiler version 5.8.1.0 (2017-10/6bf3922f3fd Thu Mar  8 16:47:23 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
```
source of MainWindow.xaml which cases the crash: https://pastebin.com/WL746mA5

source of Program.cs

```
using System;
using Avalonia;
namespace Test
{
    class Program
   {
               [STAThread]
        static void Main(string[] args)
        {
            GameInit();
            RunAlavlonUI();
            GameDeInit();
        }
        public static AppBuilder BuildAvaloniaApp()
        {
            return AppBuilder.Configure<src.UI.App>().UseSkia().UseMonoMac();
        }

        static void RunAlavlonUI()
        {
            BuildAvaloniaApp().Start<src.UI.MainWindow>();

        }
}
```

**Comment by jkoritzinsky** [comment]
Our MonoMac backend only supports 64-bit builds. Also, Apple said that they are planning on no longer fully supporting 32-bit x86 programs on the next version of macOS, so I don't know if we'll get around to fixing this.

**Comment by kekekeks** [comment]
We will probably have a separate backend for Xamarin.Mac, since it will be needed for interop anyway.

**Comment by kekekeks** [comment]
VS4Mac allows using mono64, so I'm closing this issue.

See https://stackoverflow.com/questions/45873340/can-i-use-mono64-with-visual-studio-for-mac
