### ISSUE TITLE
Tests with numeric strings fail under non-en-US culture

### ISSUE THREAD

**Issue by amis92** [AvaloniaUI/Avalonia#1520]
There is an issue with three tests in `Avalonia.Markup.UnitTests.Data`:

* `Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Convert_Get_String_To_Double`
* `Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Convert_Set_Double_To_String`
* `Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Handle_DataValidation`
* `Avalonia.Visuals.UnitTests.Media.MatrixTests.Parse_Parses`
* `Avalonia.Visuals.UnitTests.Media.RectTests.Parse_Parses`

When run under a culture that has another decimal separator than en-US  full stop `.` (e.g. comma `,` in fr-FR), these tests fail as the conversion from/to string of these numeric values fails.

These tests surface a general problem: XAML type conversion is done with CurrentCulture which isn't explicitly set. I'm not exactly sure how it *should* behave, but I suspect that XAML parsing should be done explicitly in InvariantCulture (i.e. decimal separator is dot/full stop `.`).

**Comment by amis92** [comment]
First off, for your changes it'd be much nicer to write `$"{12.3}"` instead of ToString with culture.

Also, I think it'd be better off in it's own PR. These fixes are only valid for BindingExpressionTests, though.

With Rect and Matrix, it's not that simple, because they perform `string.Split(new[]{',',' '})` which simply invalidates any culture-specific parsing later. They also differ in performing ToString: Rect uses InvariantCulture, Matrix CurrentCulture.

**Comment by Gillibald** [comment]
This can be closed

**Comment by amis92** [comment]
For the sake of reference, the Matrix/Rect cases were fixed by #1539
