### ISSUE TITLE
The source property setter is called for no reasons in SelectedValue binding

### ISSUE THREAD

**Issue by sinatrocious** [AvaloniaUI/Avalonia#15231]
### Describe the bug

I was binding `ComboBox` to dictionary and using `SelectedValue`/`SelectedValueBinding` to display dictionary entry `Value`. And I noticed that the setter of property in `SelectedValue` binding is called for no reason with default value and then again with actual value.

### To Reproduce

1. Create Avalonia C# project.
2. Do small modification

<details>
  <summary>Modifications</summary>

In `MainViewModel.cs`

```c#
public class MainViewModel : ViewModelBase
{
    public List<int> Items { get; } = [0, 1, 2, 3, 4, 5, 6];

    int selectedItem = 3;
    public int SelectedItem
    {
        get => selectedItem;
        set
        {
            selectedItem = value;
            Debug.WriteLine($"Kaboom! Set={value}");
        }
    }
}
```

In `MainView.xaml`

```xaml
    <ComboBox ItemsSource="{Binding Items}"
              SelectedValue="{ReflectionBinding SelectedItem}"/>
```

</details>

3. Run and observe Output window:

> Kaboom! Set=0
> Kaboom! Set=3

4. The setter of `SelectedItem`  is called with default value and then again with actual value.

### Expected behavior

The setter shouldn't be called.

### Avalonia version

11.0.10

### OS

Windows

### Additional context

Using `CompiledBinding` throws `NullReferenceException`, quite similar to another bug #15216.

`SelectedValueBinding="{Binding}"` makes no difference.

In real project with datatemplates (where initialization occurs every now and then) and observing such properties in different viewmodels, such unexpected propery changes may cause a headache. I just had one.

**Comment by MrJul** [comment]
It's already fixed in 11.1/master thanks to the binding refactor, the setter isn't called at all, as you expected.
