### ISSUE TITLE
Choose a folder on macOS

### ISSUE THREAD

**Issue by shanhongyue** [AvaloniaUI/Avalonia#15257]
### Describe the bug

At first, I thought it was a simple matter, but it exceeded my expectations.

Firstly, I tried using await GetStorageProvider() OpenFolderPickerAsync(...). It does work when using TFM net8.0. But when I switched to net8.0-macos, it didn't work anymore. I think it's because sandbox makes it unusable.

Then, I want to try using NSOpenPanel. 
I added NSApplication.Init(); into Main function, so I can use AppKit framework. But the following code doesn't work:

        var openPanel = NSOpenPanel.OpenPanel;
        openPanel.AllowsOtherFileTypes = false;
        openPanel.CanChooseDirectories = true;
        openPanel.CanChooseFiles = false;
        openPanel.AllowsMultipleSelection = false;
        var response = openPanel.RunModal();

Because NSOpenPanel.OpenPanel returns null. Perhaps OpenPanel should be assigned a value within the AppKit framework, but I don't know at what stage.

### To Reproduce

As detailed in the previous text.

### Expected behavior

Let NSOpenPanel.OpenPanel work.

### Avalonia version

11.0.10

### OS

macOS

**Comment by maxkatz6** [comment]
> Firstly, I tried using await GetStorageProvider() OpenFolderPickerAsync(...). It does work when using TFM net8.0

It works with net8.0 TFM.

> I think it's because sandbox makes it unusable.

Sandbox wouldn't affect a file picker, only a direct access to them. 

> Let NSOpenPanel.OpenPanel work.

I don't think NSOpenPanel.OpenPanel being null is related to Avalonia.

**Comment by shanhongyue** [comment]
I have made a new discovery. If I change TFM from net8.0-macos to net8.0 and introduce 
`<PackageReference Include="MonoMac. NetStandard" Version="0.0.4"/>`
 into my project, the following code will work properly: `var openPanel=NSOpenPanel OpenPanel;`.

**Comment by timunie** [comment]
@shanhongyue can we close this issue ? I don't see what we can do from our side tbh.
