### ISSUE TITLE
What is the correct way to use fonts

### ISSUE THREAD

**Issue by RayyanTahir** [AvaloniaUI/Avalonia#1525]
What is the correct way to set fontfamily in styles? I've tried the following but doesn't work:

**Style**
`<Style Selector="TextBlock.SwapIcon">
        <Setter Property="FontFamily" Value="resm:AvaloniaApplication4.Assets.swap-custom-icon.ttf#swap-custom-icon" />
</Style>`
**Usage**
`<TextBlock Foreground="Blue" Classes="SwapIcon" Text="{Binding Converter={StaticResource EnumToTextConverter}, ConverterParameter={x:Static converter:FontIcons.AnnotateIcon}}" />`

**Comment by Gillibald** [comment]
See #1564

**Comment by Gillibald** [comment]
Can this be closed?
