### ISSUE TITLE
Textbox Scrolls when it shouldnt

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1527]
see the gif here, iv permanently enable scrollbars to show whats happening, but happens anyway.

Needs to be in a treeview item to occur.

![textbox bug](https://user-images.githubusercontent.com/4672627/39365207-6981b328-4a28-11e8-96c4-672351e71b06.gif)

So the width of the textbox has increased, but the scrollviewer scrolled when it didn't need to!

**Comment by danwalmsley** [comment]
On TreeViewPage just change the textblock to 
`<TextBox Text="{Binding Header}" />`
to repro.

**Comment by danwalmsley** [comment]
Could be related to #1448 #1512

**Comment by grokys** [comment]
Just tried this on master and doesn't seem to happen any more I don't think?
