### ISSUE TITLE
Better exception message than "Could not create glyphTypeface"

### ISSUE THREAD

**Issue by jhimes144** [AvaloniaUI/Avalonia#15314]
### Is your feature request related to a problem? Please describe.

Every time I start a new Avalonia App with a custom font, I'm subjected to a 30 minute exercise of pain and anger trying to get custom fonts to work. The only message that is ever shown when a custom font is unable to load is "Could not create glyphTypeface". This is not at all helpful.

### Describe the solution you'd like

Different messages for different errors. Such as "Couldn't find font resource/file" or "Invalid font format" ect ect

**Comment by jp2masa** [comment]
Duplicate of #13040?

**Comment by maxkatz6** [comment]
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/13040
