### ISSUE TITLE
X11NativeControlHost can't receive any events because of X11NativeControlHost XCreateWindow does not have event mask or use XSelectInput?

### ISSUE THREAD

**Issue by sandsc** [AvaloniaUI/Avalonia#15310]
### Describe the bug

I am using sdl3 to create render window from NativeControlHost's  native control,  and use SDL3 event poll system to process events, but events can't be received on X11, there are relative issues mention this:
>#15284 #5256

I found that [X11NativeControlHost](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/X11NativeControlHost.cs) `CreateDefaultChild` create a dump x11 window without giving any event mask or use XSelectInput to allow receiving events. Could this be the cause of those issues?
BTW. Creating a new top level native window by using SDL_CreateWindow without using NativeControlHost's  default window handle , events  can be received, however as mentioned in #15284 window is detached from main window.

### To Reproduce

Create sdl3 window by platform handle created by `NativeControlHost's CreateNativeControlCore` 
then poll events in a loop by using `SDL_PollEvent`

### Expected behavior

Receiving input and resize events in event loop.

### Avalonia version

11.0.10

### OS

Linux

**Comment by kekekeks** [comment]
XSelectInput is specific to a connection-window pair, not to a window (i. e. you can subscribe for events of a window created by another client).

So calling XSelectInput with Avalonia's X11 connection will do nothing for SDL side of things

**Comment by sandsc** [comment]
> XSelectInput is specific to a connection-window pair, not to a window (i. e. you can subscribe for events of a window created by another client).
> 
> So calling XSelectInput with Avalonia's X11 connection will do nothing for SDL side of things

yes, I modified sdl's code, use XSelectInput on XWindow use SDL's connection. Indeed，events can be received by `SDL_PollEvent` correctly, I report an issue on SDL too,  so I close this issue for now.

**Comment by niuzhaosen** [comment]
> > XSelectInput 特定于连接窗口对，而不是窗口（即您可以订阅由另一个客户端创建的窗口的事件）。
> > 因此，使用 Avalonia 的 X11 连接调用 XSelectInput 对 SDL 方面没有任何作用
> 
> 是的，我修改了 SDL 的代码，在 XWindow 上使用 XSelectInput 使用 SDL 的连接。确实，事件可以被正确接收，我也在 SDL 上报告了一个问题，所以我暂时关闭这个问题。`SDL_PollEvent`

Hello ?Can you show the code?
