### ISSUE TITLE
Unable to parse formatted <Color> tag

### ISSUE THREAD

**Issue by crobibero** [AvaloniaUI/Avalonia#15320]
### Describe the bug

With formatted Xaml as:
```
<ResourceDictionary xmlns="https://github.com/avaloniaui"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <Color x:Key="White">
        White
    </Color>

</ResourceDictionary>
```

I get a build error:
```
0>Colors.axaml(4,26): Error AVLN:0004 Avalonia: Unable to parse "
        White
    " as a color Line 4, position 26.
```

### To Reproduce

Attempt to build a project that has a file with the above `<Color>` tag

### Expected behavior

The whitespace should be ignored		

### Avalonia version

11.0.10

### OS

Linux

### Additional context

I utilize https://github.com/Xavalon/XamlStyler for consistent Xaml formatting.

**Comment by maxkatz6** [comment]
I don't think it's a good idea to modify Color.Parse to trim input. But we should trim parsing input on the compiler side.
Somewhere in this method https://github.com/AvaloniaUI/Avalonia/blob/b5db6bb0f6c19070e2a09a23231bcc1e01c40610/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlLanguageParseIntrinsics.cs#L166-L179 (possibly before other types as well).

**Comment by maxkatz6** [comment]
Timespan parsing is trimmed already https://github.com/AvaloniaUI/Avalonia/blob/b5db6bb0f6c19070e2a09a23231bcc1e01c40610/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlLanguageParseIntrinsics.cs#L37

If trimming doesn't break other types, we can move it above. And also add some tests in https://github.com/AvaloniaUI/Avalonia/blob/b5db6bb0f6c19070e2a09a23231bcc1e01c40610/tests/Avalonia.Markup.Xaml.UnitTests/Xaml/AvaloniaIntrinsicsTests.cs
