### ISSUE TITLE
Why not use string.Split to split the grid length string ?

### ISSUE THREAD

**Issue by lindexi** [AvaloniaUI/Avalonia#1532]
We need to parse the grid length string in the code below. But I think the easy way to do it is to use string.Split.

https://github.com/AvaloniaUI/Avalonia/blob/35b29d8f2367fcc62775bc4de7d5f8a3802d8c07/src/Avalonia.Controls/GridLength.cs#L212

And I try to use `string.Split` to replace this code and I found it can work and pass the unit test.

![](https://user-images.githubusercontent.com/16054566/39428262-50f2f2f2-4cb9-11e8-857a-27d455cdacf2.png)

This is my code

```
      public static IEnumerable<GridLength> ParseLengths(string s, CultureInfo culture)
        {
            foreach (var temp in s.Split(new []{',',' '}, StringSplitOptions.RemoveEmptyEntries))
            {
                yield return Parse(temp, culture);
            }      
        }
```

**Comment by lindexi** [comment]
And we can see the `c` is assigned twice and the first one is useless in this code below.

https://github.com/AvaloniaUI/Avalonia/blob/35b29d8f2367fcc62775bc4de7d5f8a3802d8c07/src/Avalonia.Base/Utilities/StringTokenizer.cs#L113

It will be assigned twice and then use the last value.

https://github.com/AvaloniaUI/Avalonia/blob/35b29d8f2367fcc62775bc4de7d5f8a3802d8c07/src/Avalonia.Base/Utilities/StringTokenizer.cs#L120

**Comment by grokys** [comment]
For context, we previously used `string.Split` for parsing but this PR changed it to use the `StringTokenizer`: https://github.com/AvaloniaUI/Avalonia/pull/1125. The reason this was done was to reduce allocations.

**Comment by lindexi** [comment]
@grokys Thx, but do you test for its performance? I found the `StringTokenizer.CurrentToken` also uses string.Substring just like the `string.Split`.

And I found `StringTokenizer` have some to be optimized.

1. The `Dispose` do not any clean thing but throw an exception when `_index != _length`.
  
 https://github.com/AvaloniaUI/Avalonia/blob/35b29d8f2367fcc62775bc4de7d5f8a3802d8c07/src/Avalonia.Base/Utilities/StringTokenizer.cs#L47

   When we use `using(var tokenizer = new StringTokenizer(s, culture))` and we have some condition to make we dont read all of the string that the `_index` is less than `_length` and it will throw an exception.

![image](https://user-images.githubusercontent.com/16054566/39457970-f3e21fbe-4d23-11e8-8139-17c328535c9d.png)

```
            using (var tokenizer = new StringTokenizer(s, culture))
            {
                while (tokenizer.TryReadString(out var item))
                {
                    yield return Parse(item, culture);
                    
                    if (someCondition)
                    {
                        yield break;
                    }
                }
            }
```

We should know its code when we use it.

The better way to know whether the string is the legal format is we check the `_index` and `_length` when we use `TryReadxx` return false.

1. I think we should change `Int32` to `int` in the code below.

https://github.com/AvaloniaUI/Avalonia/blob/35b29d8f2367fcc62775bc4de7d5f8a3802d8c07/src/Avalonia.Base/Utilities/StringTokenizer.cs#L53

1. The `s` in the code below is never null for we check it in above.

https://github.com/AvaloniaUI/Avalonia/blob/35b29d8f2367fcc62775bc4de7d5f8a3802d8c07/src/Avalonia.Base/Utilities/StringTokenizer.cs#L29

**Comment by grokys** [comment]
Hmm, it looks like that PR has problems. Do you think we should revert it back to `string.Split` or just fix the problems? cc: @aelij

**Comment by SIkebe** [comment]
`string.Split` was improved to reduce allocation in .NET Core 2.1 by `Span`. 
https://blogs.msdn.microsoft.com/dotnet/2018/04/18/performance-improvements-in-net-core-2-1/

**Comment by lindexi** [comment]
@aelij Thx for your explain. But I try to use `StringTokenizer ` and the code break in some someCondition will throw an exception. Could you give pointers about this pattern?

**Comment by aelij** [comment]
@lindexi Can give me a test case?

**Comment by lindexi** [comment]
@aelij 

            using (var tokenizer = new StringTokenizer(s, culture))
            {
                while (tokenizer.TryReadString(out var item))
                {
                    yield return Parse(item, culture);
                    
                    if (someCondition)
                    {
                        yield break;
                    }
                }
            }

**Comment by aelij** [comment]
@lindexi Your test case is broken - you shouldn't be breaking the loop. The tokenizer considers it an error when there's data left on the string that hasn't been parsed (except for whitespace) - which makes sense - you usually want to parse the entire string. If you don't want it to throw, you can skip the `using` (this check is invoke during `Dispose`).

**Comment by lindexi** [comment]
@aelij Thx for your description.

**Comment by aelij** [comment]
@lindexi Sorry, I don't follow. What can't you do? This is how you should use the tokenizer in your case:

```csharp
var tokenizer = new StringTokenizer(s, culture);
while (tokenizer.TryReadString(out var item))
{
    yield return Parse(item, culture);
    
    if (someCondition)
    {
        yield break;
    }
}
```

**Comment by lindexi** [comment]
@aelij But the StringTokenizer inherit IDispose that means we are suggested to dispose of it. I think API design can be improved. At less, I can not get the point at first and break it.

Can we return false in the `TryReadxx` method when the string is not the legal format string by checking the `_index` and `_length` value?

**Comment by aelij** [comment]
@lindexi This design is meant to be **safe** - the use case you suggested is uncommon (and unless I'm wrong, not required within Avalonia). How would the `TryRead` methods know the proper length to read? They can only read the next full token or fail.

You may want to check out the API suggestion for the `Span`-based split, which is similar to a tokenizer, but a bit more general:
https://github.com/dotnet/corefx/issues/26528

**Comment by lindexi** [comment]
@aelij Thank for your patience. I understand what you mean. Can we use `Span` to improve it?

**Comment by aelij** [comment]
@lindexi Definitely! We could probably eliminate all string allocations here, but I think we'll need to wait for .NET Standard 2.1. Or provide alternate implementations for .NET Core and .NET Framework.

**Comment by lindexi** [comment]
Good @aelij

**Comment by Gillibald** [comment]
There is nothing that prevents you from using Span<T> etc now. We are already using it in several places.

**Comment by aelij** [comment]
@Gillibald The real advantage from `Span` here would come from parsing APIs (e.g. `Int32.TryParse(Span<char>)`) and that's currently available only in .NET Core 2.1.
