### ISSUE TITLE
Cannot use Window if owner is changed/removed and original owner is closed

### ISSUE THREAD

**Issue by lahma0** [AvaloniaUI/Avalonia#15339]
### Describe the bug

Let's say we have windowA and windowB. We set windowA to be the owner of windowB by using `windowB.Show(windowA);`. If we then call `windowB.Hide();`, this removes windowA as the owner of windowB and windowA no longer has any owned windows. If we now close windowA by calling `windowA.Close();`, both windowA and windowB will be removed from the global Windows list: `((IClassicDesktopStyleApplicationLifetime)Application.Current?.ApplicationLifetime).Windows;`. The result is that if you now try to call `windowB.Show();`, weird unexpected behavior will ensue. Even if you try to set a different a different owner for windowB, the same will happen. There does not appear to be any way to continue using a window after its original window owner is closed, even if that window no longer owns it or has any association with it. Looking at the Avalonia code, this does look like an unexpected bug due to the way the Window Hide and Close methods work. I think the issue is related to (in this case) windowB being removed from the global Window list after windowA is closed, even though there should no longer be any association between the 2.

### To Reproduce

- Create a window named windowA
- Create a window named windowB
- Run `windowB.Show(windowA);`
- Notice that windowB now shows in the list of OwnedWindows in windowA
- Notice that windowB.Owner is now set to windowA
- Run `windowB.Hide();`
- Notice that windowB no longer shows in the list of OwnedWindows in windowA
- Notice that windowB.Owner is now null
- Notice that `((IClassicDesktopStyleApplicationLifetime)Application.Current?.ApplicationLifetime).Windows;` correctly shows both windows
- Run `windowA.Close();`
- Notice that `((IClassicDesktopStyleApplicationLifetime)Application.Current?.ApplicationLifetime).Windows;` now shows NO windows
- Try running `windowB.Show();` and you will see that it fails

### Expected behavior

I expect windowB to not be removed from the global window list and I expect it to be shown correctly since it is no longer associated with windowA.

### Avalonia version

11.0.10

### OS

Windows

### Additional context

I am running Windows 11. I have not yet tested what this does on other platforms such as X11 or Wayland.

Also, changing `((IClassicDesktopStyleApplicationLifetime)Application.Current?.ApplicationLifetime).MainWindow` at any point in this process changes nothing.

**Comment by lahma0** [comment]
If it would be helpful, I can try to pin point the code responsible for the issue. Heck, maybe I can even work out how to fix the problem. I suspect I'm not the most qualified individual to do so but if you're ok with me giving it a shot, I'd be happy to try.

**Comment by maxkatz6** [comment]
Owner management is mostly done in Window.cs class:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Window.cs#L608-L612
and
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Window.cs#L1086-L1098

**Comment by timunie** [comment]
@lahma0 contributions are welcome and everyone has started to learn at some point. A pull request will be reviewed anyways, so not much harm in it beside the possibility a change could not be accepted in worst case.

**Comment by emmauss** [comment]
Could you confirm if this issue still occurs on the latest nightly build?

**Comment by lahma0** [comment]
Sure. I'll check it out asap and report back here.

**Comment by lahma0** [comment]
Good news! Looks like this is indeed working correctly now. Thanks for fixing this issue. I apologize I never got around to looking at it myself. I will try to keep a look out for some other issues that maybe I can help out with to try to get my feet wet and start contributing back to the project.
