### ISSUE TITLE
Browser (WASM): the SIzeChanged event is not thrown at startup

### ISSUE THREAD

**Issue by Patrick8639** [AvaloniaUI/Avalonia#15341]
### Describe the bug

When the application is started in the browser, the `SizeChanged` event is not thrown at startup.
If the browser window is resized, the event is thowned.

the event is throwned in desktop (Windows) and Android.

### To Reproduce

Create an Avalonia application.
Add a named empty `TextBox` in `MainView.axaml`.
Add the `OnSizeChanged` overriden method, to set the `TextBox`.

When run in desktop or Android, the text is displayed. In the browser, the text is only displayed after the brpwser window is resized.

### Expected behavior

The `OnSizeChanged` method must also be called at startup when running in the browser.

### Avalonia version

11.0.10

### OS

WebAssembly

**Comment by timunie** [comment]
can you test 11.1 beta for Browser usage? We have some improvements in.

**Comment by Patrick8639** [comment]
Hello Tim,
after changing Avalonia.Browser to 11.1.0-beta1, I have the following error when compiling:
> Error CS0234: The type or namespace name 'Browser' does not exist in the namespace 'Avalonia' (are you missing an assembly reference?)

What's also strange is the how the reference is displayed in VS:

![image](https://github.com/AvaloniaUI/Avalonia/assets/26135035/a3ffea51-55c9-4c99-893f-024591c88a6b)

Is the package broken?

**Comment by timunie** [comment]
NET8 has some breaking changes, see release notes: #14922

**Comment by Patrick8639** [comment]
>Browser backend now also requires .NET 8 or newer, but also has changes to its project structure.

My application is under .NET 8.

>We recommend using newer Avalonia templates as a reference, but a migration guide specifically for the browser is also planned.

So I need to change something on my project, as it was created with the old template?

**Comment by timunie** [comment]
> So I need to change something on my project, as it was created with the old template?

Yes, exactly. I don't know what, so you need to figure out. Sorry ^^

**Comment by Patrick8639** [comment]
I've tried with a demo application and it works!
I now must figure out how to change the existing application to make it work...

**Comment by timunie** [comment]
closing this as it works in newer version.
