### ISSUE TITLE
Binding to Generic property on a class outside assembly causes AVLN9999

### ISSUE THREAD

**Issue by BobbyCannon** [AvaloniaUI/Avalonia#15345]
### Describe the bug

Repo project that demonstrates the issue. https://github.com/BobbyCannon/BugProjects,

Open the AvaloniaBindingIssues.sln and build, it'll fail.

> Build started at 8:21 PM...
> 1>------ Build started: Project: AvaloniaBindingIssues, Configuration: Debug Any CPU ------
> 1>MSBUILD : Avalonia error AVLN9999: Member 'System.Collections.ObjectModel.ReadOnlyObservableCollection`1' is declared in another module and needs to be imported
> 1>Done building project "AvaloniaBindingIssues.csproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
> ========== Build completed at 8:21 PM and took 01.616 seconds ==========

 If you move the CustomList.cs from [ClassLibrary] back into back into the [AvaloniaBindingIssues] project then it'll build.

### To Reproduce

pull the repo and build it

### Expected behavior

it should build?

### Avalonia version

11.1.0-beta1

### OS

Windows

**Comment by jp2masa** [comment]
There is a recent fix for a similar problem (kekekeks/XamlX#113, pulled in #15333), can you try the latest nightly build (11.2.999-cibuild0047232-alpha)?

**Comment by BobbyCannon** [comment]
> There is a recent fix for a similar problem ([kekekeks/XamlX#113](https://github.com/kekekeks/XamlX/pull/113), pulled in #15333), can you try the latest nightly build (11.2.999-cibuild0047232-alpha)?

No, problem still exists.

<AvaloniaVersion>11.2.999-cibuild0047228-alpha</AvaloniaVersion>

> Rebuild started at 9:37 PM...
> 1>------ Rebuild All started: Project: ClassLibrary, Configuration: Debug Any CPU ------
> Restored C:\Workspaces\GitHub\BugProjects\ClassLibrary\ClassLibrary.csproj (in 0.6 ms).
> Restored C:\Workspaces\GitHub\BugProjects\AvaloniaBindingIssues\AvaloniaBindingIssues.csproj (in 14 ms).
> Restored C:\Workspaces\GitHub\BugProjects\AvaloniaBindingIssues.Desktop\AvaloniaBindingIssues.Desktop.csproj (in 17 ms).
> 1>ClassLibrary -> C:\Workspaces\GitHub\BugProjects\ClassLibrary\bin\Debug\net7.0\ClassLibrary.dll
> 2>------ Rebuild All started: Project: AvaloniaBindingIssues, Configuration: Debug Any CPU ------
> 2>MSBUILD : Avalonia error AVLN9999: Member 'System.Collections.ObjectModel.ReadOnlyObservableCollection`1' is declared in another module and needs to be imported
> 2>Done building project "AvaloniaBindingIssues.csproj" -- FAILED.
> 3>------ Rebuild All started: Project: AvaloniaBindingIssues.Desktop, Configuration: Debug Any CPU ------
> 3>CSC : error CS0006: Metadata file 'C:\Workspaces\GitHub\BugProjects\AvaloniaBindingIssues\obj\Debug\net7.0\ref\AvaloniaBindingIssues.dll' could not be found
> 3>Done building project "AvaloniaBindingIssues.Desktop.csproj" -- FAILED.
> ========== Rebuild All: 1 succeeded, 2 failed, 0 skipped ==========
> ========== Rebuild completed at 9:37 PM and took 00.842 seconds ==========

**Comment by BobbyCannon** [comment]
I committed the changes to the linked repo.

**Comment by maxkatz6** [comment]
@BobbyCannon this issue might be fixed in 11.1 builds.

**Comment by user98392** [comment]
this is really bad, in my app I created a separate project to move common UI classes related to viewmodels containing properties to bind and because of this bug I'm forced to move the classes back and basically remove the changes.

**Comment by user98392** [comment]
@maxkatz6 when it will be released?

**Comment by maxkatz6** [comment]
@user98392 11.1-rc2 is on nuget right now. Stable is planned on following weeks.
