### ISSUE TITLE
"CSS selectors" are slow. 

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#1538]
Applying complex selectors makes layout slow. How to reproduce: have a ListBox with some items, then include styles with selectors like "Panel Button" or "Panel > Button" or even "ListBox Panel Button". More nesting in selectors leads to slower rendering.

**Comment by grokys** [comment]
Related: https://github.com/AvaloniaUI/Avalonia/issues/1394

**Comment by grokys** [comment]
@x2bool could you try https://github.com/AvaloniaUI/Avalonia/pull/1690 and see if it improves things for you?

**Comment by x2bool** [comment]
Sure! I could give you subjective feedback.

Also would Stopwatch class be appropriate for measuring?

**Comment by grokys** [comment]
Yeah, well it's better than nothing! I tried to repro the problem here both on master and on the PR branch in the `VirtualizationDemo` sample but I couldn't get it to go particularly slow, so maybe it was already fixed?

**Comment by x2bool** [comment]
Awesome stuff! I have a Carousel with navigation between two ListBoxes. And on Windows it's as smooth as possible, there is still a tiny UI freeze on Macos though, but it's nowhere as bad as it was. (Maybe it's just hardware that is faster on my Windows machine???)

Also I've tried to add redundant nesting for styles, and I am sure that it does make performance worse on Avalonia 0.6.1, but I have no evidence of the same behavior on that branch (with level 3 selector nesting).

Great job! Can't wait for the next Beta.

**Comment by x2bool** [comment]
Hmm... It's kind of interesting that this PR says it improved memory usage, but in fact also made layout faster 😄

**Comment by x2bool** [comment]
I'd like to close this. With the new OSX backend I haven't experienced perf issues for some time.
