### ISSUE TITLE
a way to get native Screen handle & rotation info

### ISSUE THREAD

**Issue by jcyuan** [AvaloniaUI/Avalonia#15382]
### Is your feature request related to a problem? Please describe.

just like TopLevel.GetTopLevel(win).TryGetPlatformHandle();
Screen needs a way to get its native handle too.

and, there is no screen rotation info...

### Describe the solution you'd like

just a way to get native handle & rotation info

**Comment by maxkatz6** [comment]
So, I assume something like this would be enough? cc @kekekeks 

```diff
public class Screen
{
+     public IPlatformHandle? TryGetPlatformHandle();
}
```

Returning
- IntPtr platform handle from `Monitor` on Windows
https://github.com/AvaloniaUI/Avalonia/blob/bca559b84b1123ea324df5ea0e57af516caa65cf/src/Windows/Avalonia.Win32/ScreenImpl.cs#L33

- [NScreen](https://developer.apple.com/documentation/appkit/nsscreen) object IntPtr handle from macOS
https://github.com/AvaloniaUI/Avalonia/blob/b4ddce64a5d72ea12d21693afb47a55d45ed8089/native/Avalonia.Native/src/OSX/Screens.mm#L32

- And I assume X11Monitor Name on X11?
https://github.com/AvaloniaUI/Avalonia/blob/bca559b84b1123ea324df5ea0e57af516caa65cf/src/Avalonia.X11/X11Structs.cs#L1899

Where in all cases it can be a IntPtr wrapped in a PlatformHandle.

**Comment by maxkatz6** [comment]
At some point I wish we could unify Screens API with mobile, moving Screens property to TopLevel. It will also make more sense to add orientation property.

**Comment by jcyuan** [comment]
> At some point I wish we could unify Screens API with mobile, moving Screens property to TopLevel. It will also make more sense to add orientation property.

it does make sense~ 👍

**Comment by maxkatz6** [comment]
Completed in 11.2 nightly. Mobile support is coming later.
