### ISSUE TITLE
TextBlock binding not working correctly

### ISSUE THREAD

**Issue by Patrick8639** [AvaloniaUI/Avalonia#15395]
### Describe the bug

When running under Windows, the content of the `TextBlock` is updated,when the property changes. But in WebAssemblyand in Android, it isn't. I've not tried under the other platforms as I don't have the hardware to test.

### To Reproduce

The source code of the test application is in GitHub: [Avalonia-Test-TextBlock-Binding](https://github.com/Patrick8639/Avalonia-Test-TextBlock-Binding).
Run it and click the button to update the count.

### Expected behavior

In all platform, the `TextBlock` must update.

### Avalonia version

11.0.10 - 11.1.0-Beta1

### OS

Windows, WebAssembly, Android

**Comment by timunie** [comment]
nothing to see in that repo, beside the License

**Comment by Patrick8639** [comment]
Sorry Tim, something went wrong.
It is OK now.

**Comment by timunie** [comment]
Any reason you are re-setting the ViewModel from the constructor? 

1. https://github.com/Patrick8639/Avalonia-Test-TextBlock-Binding/blob/d166a2c601f52a2673512214202ec378d1075aaf/TestTextBlockBinding/Views/MainView.axaml.cs#L21

2. https://github.com/Patrick8639/Avalonia-Test-TextBlock-Binding/blob/d166a2c601f52a2673512214202ec378d1075aaf/TestTextBlockBinding/App.axaml.cs#L28

**Comment by Patrick8639** [comment]
> Any reason you are re-setting the ViewModel from the constructor?

Because I wanted to access it by code in `MainView`... and I forget to remove it from `App`.

**Comment by timunie** [comment]
Better to use this in your code behind: 

```cs
private MainViewModel MyViewModel => this.DataContext as MainViewModel;
```

**Comment by timunie** [comment]
filed a fix https://github.com/Patrick8639/Avalonia-Test-TextBlock-Binding/pull/1

**Comment by Patrick8639** [comment]
@timunie @TheJarX 
Even if it's working with the change, there seems to still be a problem, as the Desktop application doesn't have the behaviour as the Android and Browser one.
Perhaps it's because these versions doesn't like that the `DataContext`changes, perhaps because the screen is not updated correctly, etc. Who knows.
I can try to create a new test case for the first option, but having it not working, it doesn't mean that this is the real problem.

**Comment by timunie** [comment]
Your problem is that on startup you override the DataContext. 

1. MainView is created
2. You set DataContext in constructor
3. App.axaml.cs sets a new one, your MainView is not aware of. 

On desktop the Data context is set for Window that's why your in constructor isn't overridden

**Comment by Patrick8639** [comment]
Thank you for the clarification.

**Comment by timunie** [comment]
@Patrick8639 one more hint: If you want to verify it on your own, consider to add some Logs to your code `Debug.WriteLine("Creating a ViewModel in MainView-constructor);` (and similar)
