### ISSUE TITLE
DevTools should display a list of hotkeys

### ISSUE THREAD

**Issue by stevemonaco** [AvaloniaUI/Avalonia#15390]
### Is your feature request related to a problem? Please describe.

I keep forgetting how to activate certain features, notably the Popup Freeze. This means I need to double-check the [DevTools docs](https://docs.avaloniaui.net/docs/guides/implementation-guides/developer-tools#hotkeys). There's no in-app discoverability for Popup Freeze, AFAIK.

### Describe the solution you'd like

A new menu option (View -> Hotkeys) that pops up a dialog that lists all hotkeys and what they do.

### Describe alternatives you've considered

A new tab to accompany "Logical Tree", "Visual Tree", and "Events" called "Hotkeys". This eliminates the need for a dialog (especially a new window dialog), but probably gives Hotkeys too much visual importance.

**Comment by maxkatz6** [comment]
It's mixed right now. Some hot keys are displayed in the status bar. Some are visible in the menu. And some (like popup freeze) aren't nowhere to find. 

~~If we add a new tab, I expect some kind of Welcome page just like in Chrome~~
Nevermind, Chrome has a dedicated menu option that opens a hotkey page:
![image](https://github.com/AvaloniaUI/Avalonia/assets/3163374/0ee6424c-fdf2-49bc-b067-a9e914a0d0d1)

**Comment by workgroupengineering** [comment]
we could add an item to system menu.
