### ISSUE TITLE
dotnet has stopped working

### ISSUE THREAD

**Issue by RayyanTahir** [AvaloniaUI/Avalonia#1540]
dotnet crashes on application startup when platform target of project is set to `x86 `from here:

`Project properties -> Build -> Platform target`

Any help would be appreciated.
Thanks

**Comment by danwalmsley** [comment]
which dotnet are you targeting?

**Comment by RayyanTahir** [comment]
I believe from the issue my project is probably targeting x64 version. Is there a way to re-target from Visual Studio?

**Comment by RayyanTahir** [comment]
A workaround was to uninstall the x64 version, install the x86 version and restart visual studio.
