### ISSUE TITLE
Check mark doesn't show on MenuItem with Simple theme on 11.1.0-beta1

### ISSUE THREAD

**Issue by AnErrupTion** [AvaloniaUI/Avalonia#15417]
### Describe the bug

The check mark on a ``MenuItem`` when it's using ``ToggleType="CheckBox"`` doesn't appear with the Simple theme.

### To Reproduce

1. Create a new Avalonia project
2. Use the simple theme instead of the fluent theme in ``App.axaml``
3. Use the following XAML code in ``MainWindow.axaml``:
```xaml
<StackPanel>
    <Menu>
        <MenuItem Header="Menu">
            <MenuItem ToggleType="CheckBox" IsChecked="True" Header="Checked Menu Item"/>
        </MenuItem>
    </Menu>
</StackPanel>
```

### Expected behavior

I'd have expected the check mark to appear on the Simple theme as well.

### Avalonia version

11.1.0-beta1

### Additional context

Fluent:
![fluent](https://github.com/AvaloniaUI/Avalonia/assets/49339966/559553b9-280b-49c4-8d88-8af74d0531a0)

Simple:
![simple](https://github.com/AvaloniaUI/Avalonia/assets/49339966/33a18ca5-e0e5-4f2f-b392-2c844e109d3b)

**Comment by timunie** [comment]
@AnErrupTion if you want, figure out the differences between these styles and provide a PR to fix it.
