### ISSUE TITLE
Nuget pachage conflict

### ISSUE THREAD

**Issue by LoongArum** [AvaloniaUI/Avalonia#15461]
### Describe the bug

When i try to install "Microsoft.EntityFrameworkCore.Design" this Nuget package and i get some error: "Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.CodeAnalysis.CSharp. Install/reference Microsoft.CodeAnalysis.CSharp 4.5.0 directly to project DDset to resolve this issue. 
 DDset -> Microsoft.EntityFrameworkCore.Design 8.0.4 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.CSharp (= 4.5.0) 
 DDset -> Avalonia.Diagnostics 11.0.10 -> Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 -> Microsoft.CodeAnalysis.CSharp (= 3.8.0).	DDset /home/ar0m/Document/C-sharp/Avalonia-code/DDset/DDset .csproj 	1	
"

### To Reproduce

Install "Microsoft.EntityFrameworkCore.Design" package.

### Expected behavior

Maybe we can upgrade the dependence of Avalonia.Diagnostics?

### Avalonia version

11.0.10

### OS

Linux

**Comment by timunie** [comment]
it's not an issue anymore in 11.1-beta. For 11.0, you need to downgrade your nuget or remove the package `Avalonia.Diagnostics`

**Comment by LoongArum** [comment]
> it's not an issue anymore in 11.1-beta. For 11.0, you need to downgrade your nuget or remove the package `Avalonia.Diagnostics

Thank you!
