### ISSUE TITLE
Button command binding not worked with .NET Framework build target

### ISSUE THREAD

**Issue by Krey81** [AvaloniaUI/Avalonia#1550]
With netcore\standard target all fine
If i integrate test page with command binding in ControlsCatalog.Desktop(net47) all fine too
But in standalone .NET Framework projects binded commands not executed. I attach simple sample app
[CommandTest.zip](https://github.com/AvaloniaUI/Avalonia/files/1975270/CommandTest.zip)

**Comment by jkoritzinsky** [comment]
I found the issue. On .NET Framework, the Avalonia package does not have a package dependency on `System.ComponentModel.Annotations`, so it fails to load that assembly, which breaks any bindings that support validation.
