### ISSUE TITLE
Window can't be dragged using title bar and no caption buttons rendered with extend client area

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#15522]
### Describe the bug

Window can't be dragged using title bar and no caption buttons rendered with extend client area.

![image](https://github.com/AvaloniaUI/Avalonia/assets/2297442/9e041671-6e06-47f1-bc46-aef6abea0c57)

![image](https://github.com/AvaloniaUI/Avalonia/assets/2297442/fd83484e-ce6d-4966-9425-76187e916597)

### To Reproduce

Set on Window
```
        ExtendClientAreaToDecorationsHint="True"
        ExtendClientAreaChromeHints="Default, PreferSystemChrome, OSXThickTitleBar"
```

### Expected behavior

Window can be dragged using title bar and caption buttons are rendered with extend client area

### Avalonia version

11.1.0-beta2

### OS

Windows

**Comment by wieslawsoltes** [comment]
When I open DevTools and set manually ExtendClientAreaChromeHints  to PreferSystemChrome it fixed the issue, but setting from xaml or code does not help.

**Comment by wieslawsoltes** [comment]
https://github.com/AvaloniaUI/Avalonia/assets/2297442/407436bb-5087-4193-9dcb-3944880ca82c

**Comment by wieslawsoltes** [comment]
On 11.1.0-beta1 I can drag window but caption buttons are not rendered (they are actually rendered when window is maximised).

**Comment by wieslawsoltes** [comment]
I did try setting ExtendClientAreaChromeHints only from code but did not help, same results as from xaml.

**Comment by wieslawsoltes** [comment]
This is what happens on 11.1.0-beta1

https://github.com/AvaloniaUI/Avalonia/assets/2297442/fbd8cb23-a948-4cba-ae99-0fd9e3940781

**Comment by Gillibald** [comment]
Might be related to: https://github.com/AvaloniaUI/Avalonia/commit/4c949ee628ae5394e85003ff64d054b26d32c3f4

**Comment by jmacato** [comment]
test

**Comment by jmacato** [comment]
test

**Comment by jmacato** [comment]
test
