### ISSUE TITLE
AutoCompleteBox: Setting MinimumPrefixLength to 0 causes dropdown to open when control is shown for the first time

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#1554]
AutoCompleteBox with `MinimumPrefixLength` opens on it's own when show for the first time. Simplest repro is setting `MinimumPrefixLength` to `0` for any of the controls in `AutoCompleteBoxPage.xaml`.

In example below I have set it to all controls, which opens dropdowns for them all. And it requires a click per each to close them.

![autocompletebox](https://user-images.githubusercontent.com/2588062/39671987-4ee7079c-5122-11e8-885e-431c8c2764f5.gif)

Sample below simply wraps `AutoCompleteBox` in a `Expander`. For the first time `Expander` is opened the dropdown will show, subsequent opens do not trigger a dropdown open.
```
<ListBox Items="{Binding TestItems}">
    <ListBox.ItemTemplate>
      <DataTemplate>
        <Expander Header="Test Element">
            <AutoCompleteBox Items="{Binding CompleteItems}" MinimumPrefixLength="0" FilterMode="ContainsOrdinal"/>
        </Expander>
      </DataTemplate>
    </ListBox.ItemTemplate>
  </ListBox>
```

![autocompletebox_2](https://user-images.githubusercontent.com/2588062/39672042-48eb46d6-5123-11e8-8f1a-57d4676333b1.gif)

cc: @sdoroff since he ported this control from Silverlight and maybe can shed some light on this behavior.

**Comment by sdoroff** [comment]
@MarchingCube - this is clearly bug. I'll hopefully have a fix for it this week. Thank you for pointing it out.
