### ISSUE TITLE
AvaloniaAppDelegate<TApp>.FinishedLaunching is not virtual - cannot initialize Maui.Essentials

### ISSUE THREAD

**Issue by gentledepp** [AvaloniaUI/Avalonia#15553]
### Is your feature request related to a problem? Please describe.

We need the functionality that Maui.Essentials provides.
E.g. Clipboard, Camera, MediaPicker, etc.

Accodring to their docs, [you need to initialize the platform in FinishedLaunching](https://learn.microsoft.com/en-us/dotnet/maui/migration/native-essentials?view=net-maui-8.0&tabs=ios)
```chsarp
using Microsoft.Maui.ApplicationModel;

namespace MyiOSApp;

[Register("AppDelegate")]
public class AppDelegate : UIApplicationDelegate
{
    public override UIWindow? Window
    {
        get;
        set;
    }

    public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
    {
        // create a new window instance based on the screen size
        Window = new UIWindow(UIScreen.MainScreen.Bounds);

        // create a UIViewController with a single UILabel
        var vc = new UIViewController();
        // ...
        Window.RootViewController = vc;

        Platform.Init(() => vc);

        // make the window visible
        Window.MakeKeyAndVisible();

        return true;
    }
}
```

However, AvaloiaAppDelegate<TApp> is not marked virtual:
![image](https://github.com/AvaloniaUI/Avalonia/assets/1175751/edcf57eb-8805-4e46-9b84-96e834fc042b)

### Describe the solution you'd like

While I understand, that the logic in `FinishedLaunching` should not be tampered with, we still need this callback together with the RootViewController.

Is there any other way to initialize Maui.Essentials?

Maybe like so:

![image](https://github.com/AvaloniaUI/Avalonia/assets/1175751/f470b30a-6750-4e33-9f33-6fa38a78c85f)

If so, since the APIs provided are so important, could you add documentation on how to integrate Maui.Essentials?
Thank you so much!

**Comment by timunie** [comment]
Is that really needed? Related: 
- https://github.com/AvaloniaUI/Avalonia/discussions/12621
- https://github.com/AvaloniaUI/Avalonia.Essentials

**Comment by gentledepp** [comment]
@timunie I do not understand the question.
regarding: Avalonia.Essentials is "archived" - so not futureproof at all, right?
regarding: #12621 - they are merely discussing if it is needed or not.

Do we need Maui Essentials: Definitive "YES" since avalonia ui lacks most of the platform APIs it provides.
Do we need a documentation: Definitive "YES" since not every dev is as experienced/tortured as I am and manages to dig through open source code all day just to get things done.  😅

**Comment by maxkatz6** [comment]
https://learn.microsoft.com/en-us/dotnet/api/foundation.exportattribute?view=xamarin-ios-sdk-12

```csharp
[Export("application:didFinishLaunchingWithOptions:")]
public bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
{
     base.FinishedLaunching(application, launchOptions);
}
```

**Comment by maxkatz6** [comment]
Also, come on, this project already handles initialization - https://github.com/AvaloniaUI/AvaloniaMauiHybrid
It was mentioned in these discussions and avalonia.essentials.

> Do we need Maui Essentials: Definitive "YES"

Probably, no, since you can access platform specific APIs directly from platform projects. I.e. "net8.0-ios" projects gives you access to iOS APIs. That's a .NET feature, available with any GUI framework. But there is nothing wrong with using Essentials too, if you only need limited platforms they support.

**Comment by timunie** [comment]
@gentledepp in case you think docs should be imporved, contributions to the docs are welcome.
