### ISSUE TITLE
Selection of text in TextBox does not work

### ISSUE THREAD

**Issue by LyleRolleman-plst** [AvaloniaUI/Avalonia#15558]
### Describe the bug

When I attempt to select text in a TextBox with the intent of copying it, I can't on Android or iOS.

When I tap or tap and hold or tap and drag, I always get a flyout box wit cut and copy, always greyed out, paste not greyed out and select all, which seems to select the text, but then the flyout disappears, which appears to be a related problem

### To Reproduce

Start with a TextBox with some text in it
1. For the first issue, attempt to select text (ex. long hold and drag). Observe it only places the caret
2. For the second issue, select the Select All option, observe the text is selected but then nothing can be done with it

### Expected behavior

I should be able to select and copy/cut text out of a TextBox

### Avalonia version

11.1.0-beta2 (and probably earlier)

**Comment by jp2masa** [comment]
This is probably a regression. It is supposed to work using text selection handles (#13107).

**Comment by emmauss** [comment]
Could you provide a minimal repro and/or a video. I'm not able to reproduce the issue. Though some gestures for selecting text on touch devices aren't yet supported, for any avalonia text box on the content layer, selection and copy/paste work well enough.
Also, we do not have select all option in our default text box context menu.
