### ISSUE TITLE
Unable to set window size on MVVM template with d:DesignWidth and d:DesignHeight

### ISSUE THREAD

**Issue by eSqadron** [AvaloniaUI/Avalonia#15577]
### Describe the bug

Changing d:DesignWidth or d:DesignHeight doesn't change the width or height of window

### To Reproduce

1. I create `Avalonia .NET MVVM App (AvaloniaUI)` via VIsual Studio 2022 "Create a New Project"
2. Calling it `AvaloniaApplication1`, solution and project in the same directory
3. Framwork .NET 6.0, Toolkit Reactive UI, Avalonia Version 11.0.2, Use Compiled Bindings selected
4. I open `Views/MainWindow.axml`
5. I change `d:DesignWidth="800"` to `d:DesignWidth="200"`
6. Window has still width of 800 instead od 200

### Expected behavior

6. Window should have reduced width

### Avalonia version

11.0.2

### OS

Windows

### Additional context

I think it is the same as Issue [4303](https://github.com/AvaloniaUI/Avalonia/issues/4303), but that one was closed 3 years ago as solved, but it seems like exact same issue reappeared.

I also tried some tricks like cleaning the solution, rebuilding it, debug build, release build, but nothing worked, I am stuck with 800x450 window.

**Comment by rabbitism** [comment]
You need to use Width and Height.
 Design time property are only for IDE previewing.

**Comment by eSqadron** [comment]
Thanks for your answer, It works now, sorry, my bad.
Might want to add a note about that to [ToDo List Tutorial](https://docs.avaloniaui.net/docs/tutorials/todo-list-app/creating-a-view), as it is a little bit misleading, at least for me.

**Comment by timunie** [comment]
No need to update that tutorial as it will be replaced soon. A PR is in review mode currently so shouldn't last more than few weeks.

**Comment by timunie** [comment]
In case anyone wants to try the new tutorial: https://github.com/timunie/Avalonia.Samples/tree/feat/ToDoListApp/src/Avalonia.Samples/CompleteApps/SimpleToDoList
