### ISSUE TITLE
styled property not working on UserControl

### ISSUE THREAD

**Issue by touhidurrr** [AvaloniaUI/Avalonia#15572]
### Describe the bug

same as above.

### To Reproduce

```cs
// LoginView.axaml.cs
public static readonly StyledProperty<bool> TriggerProperty = AvaloniaProperty.Register<LoginView, bool>("Trigger");

public bool Trigger
{
    get => GetValue(TriggerProperty);
    set => SetValue(TriggerProperty, value);
}
```

`// LoginView.axaml`

![image](https://github.com/AvaloniaUI/Avalonia/assets/46617994/c9b42fb9-b60e-4c3a-9e50-2fc6aeeb551b)

As you can see there is no error or warning. However... When I try to build it....
```
0>LoginView.axaml(22,35): Error AVLN3000 : Unable to find the parent scope for AvaloniaProperty lookup Line 22, position 35.
```

I tried many things. But could not fix this issue.

### Expected behavior

Build succeeds.

### Avalonia version

11.1.0-beta2

### OS

Windows

### Additional context

Autocompletions work but build fails.

**Comment by maxkatz6** [comment]
You can only use TemplateBinding inside of the actual template. In your UserControl code you don't have any templates (from what I can see here).

So, you probably need:
```
IsVisible="{Binding $parent[ns:LoginView].Trigger}"
```
where "ns:LogingView" - is this user control.

Alternatively, you can add x:Name on your LoginView root element, and then use named control binding `"{Binding #MyLoginView.Trigger}"`

**Comment by touhidurrr** [comment]
@maxkatz6 this is off-topic but can you answer this also... In login view after login is done I want to set trigger to false and make login invisible. How can I do it?

**Comment by timunie** [comment]
I'd swap views tbh. See Avalonia.Spamples for a simple Navigation sample
