### ISSUE TITLE
Add Font Features, Languages, and Name IDs on GlyphTypeface

### ISSUE THREAD

**Issue by stevemonaco** [AvaloniaUI/Avalonia#15597]
### Is your feature request related to a problem? Please describe.

Querying the capabilities and informational data of a font is not directly supported by Avalonia. Besides apps that load fonts at runtime, such support could also open up new avenues for DevTools improvements.

### Describe the solution you'd like

These should be added to `GlyphTypeface`:

* `Feature` is exposed by HarfBuzzSharp and exists as `FontFeature(Collection)` in Avalonia.
* `Language` is exposed by HarfBuzzSharp.
* Name IDs (`OpenTypeNameId`) are not exposed and need to be added to HarfBuzzSharp's `Face` via `hb_ot_name_get_utf8`.

### Additional context

Online tools such as https://fontdrop.info/#/?darkmode=true exposes this information in a usable way. This is sufficient for working with fonts with characteristics known at compile-time and may help others until Avalonia provides better information.

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/15837
