### ISSUE TITLE
Browser doesn't launch the application by default (and can't use debugger)

### ISSUE THREAD

**Issue by gosub-com** [AvaloniaUI/Avalonia#15617]
### Describe the bug

When running the app from the Visual Studio debugger, the browser shows a blank page.  I can manually enter the URL, and it runs, but the debugger is not attached.

### To Reproduce

Followed directions here https://docs.avaloniaui.net/docs/guides/platforms/how-to-use-web-assembly to get latest templates, then installed all the latest extension from visual studio as well.

Create a new project:
![image](https://github.com/AvaloniaUI/Avalonia/assets/36462607/675d0886-02d3-4b5d-b282-81ca0b20d7d5)

![image](https://github.com/AvaloniaUI/Avalonia/assets/36462607/4c135a64-a8c1-4d97-89af-ec97488a03a0)

Right Click and start Debugger:
![image](https://github.com/AvaloniaUI/Avalonia/assets/36462607/3f13232c-ac4c-4a9c-9837-8e1983e0f26e)

Blank Firefox browser window appears:
![image](https://github.com/AvaloniaUI/Avalonia/assets/36462607/a464948c-3ff4-4a0d-ac1a-be9d729bcc6d)

If I wait long enough, this appears "Failed to launch debug adapter":
![image](https://github.com/AvaloniaUI/Avalonia/assets/36462607/df9bfa72-14e3-4142-bf20-6d7a04db314c)

If I enter the URL before that message, the browser opens and runs:
![image](https://github.com/AvaloniaUI/Avalonia/assets/36462607/68904961-1a43-4c44-8433-215cbd041140)

But it can't be debugged, and the browser will eventually show the above popup message and then exit.

### Expected behavior

The application should launch the browser with the correct URL, and I should be able to debug it.

### Avalonia version

11.0.10

### OS

WebAssembly

### Additional context

None.

**Comment by maxkatz6** [comment]
It's not a bug in Avalonia. 
.NET 8 is known to have debugging problems. 
It should be better with .NET 9 release.
