### ISSUE TITLE
Android white screen after exiting using physical back button

### ISSUE THREAD

**Issue by yumikou** [AvaloniaUI/Avalonia#15620]
### Describe the bug

After opening an app, I click the back button on my Android phone to exit, and when I click the app icon on my phone again to enter, the screen turns completely white and I can’t see anything.
I'm using android 9 api 28, this problem occurs when using 11.1.0-beta2 and 11.2.999-cibuild0048108-alpha, 11.1.0-beta1 has no problem

### To Reproduce

1. Open an app.
2. Click the Android physical back button to exit the app.
3. Click on the app icon to open it again.

### Expected behavior

It will display normally when you open the app again.

### Avalonia version

11.1.0-beta2

### OS

Android

**Comment by timunie** [comment]
@yumikou you can use src/Samples/MobileSandbox to see if you find the code that does produce this behavior.

**Comment by yumikou** [comment]
> @yumikou you can use src/Samples/MobileSandbox to see if you find the code that does produce this behavior.

Thank you for your reply. I tested the SafeAreaDemo.Android in the example and still have the same problem and I don't see any exception logs. I am not familiar with the source code of avalonia yet, It is a bit difficult for me to locate the problem code, so I am reading slowly now, but may not be able to find it.

**Comment by timunie** [comment]
I was hoping you see an obvious error message or smth. So yeah I don't expect you to scan all source code. Thanks for your time anyways 👍

**Comment by timunie** [comment]
@afunc233 thanks for your help ❤️
