### ISSUE TITLE
Add an event to detect the screen changes

### ISSUE THREAD

**Issue by walterlv** [AvaloniaUI/Avalonia#15637]
### Is your feature request related to a problem? Please describe.

Supposed that we are developing such an app:

1. It has a floating icon on the desktop/screen
2. The icon will reposition and rescale itself when the screen resolution or scaling is changed

Avalonia 11.1.0 now only provide an event of `Window.ScalingChanged` that will be raised when the screen scaling is changed. But if the screen resolution is changed, it provide nothing. So our desktop icon doesn't know when to reposition it.

For example, the desktop icon is position at the top-right corner of the screen displaying in 3840x2160 and now the user changes the resolution to 1920x1080, the icon will be out of the screen. *(Note: If the window is an override redirect window, the desktop window manager will not reposition it.)*

### Describe the solution you'd like

1. Add an event `Changed` to `Avalonia.Controls.Screens` class
2. The event should be raised when the screen resolution, scaling, orientation, layout, count, etc. are changed

### Describe alternatives you've considered

1. Add a native callback into the `X11Properties` class, which is the same as what in the `Win32Properties` class.

### Additional context

![image](https://github.com/AvaloniaUI/Avalonia/assets/9959623/fffe6bf4-7c35-4c90-9234-5d7981a2ee84)

**Comment by lindexi** [comment]
Thank you. This feature is exactly what I need and look forward to adding it.

**Comment by walterlv** [comment]
Before we get the framework support, we can use this work-around:

```csharp
using var display = XDisplay.Open(0);
var window = XDefaultRootWindow(display);

XSelectInput(display, window, (nint)(ExposureMask | StructureNotifyMask));

while (_isRunning)
{
    XNextEvent(display, out var e);

    if (e.type is XEventName.ConfigureNotify)
    {
        var configureEvent = e.ConfigureEvent;
        var bounds = new PixelRect(configureEvent.x, configureEvent.y, configureEvent.width, configureEvent.height);
        if (bounds != _lastScreenBounds)
        {
            _lastScreenBounds = bounds;
            RaiseScreenChanged(bounds);
        }
    }
}
```

We'are trying to know the changes of the root window and we assume that the position and the size of it equals to the screen position and size.

Just run this code above on a long-running task and we'll get the screen resolution changed event.

**Comment by maxkatz6** [comment]
Completed in 11.2 nightly. Mobile support is coming later. Linux support needs some help from community.

**Comment by maxkatz6** [comment]
Opened this issue to track remaining platforms including Linux https://github.com/AvaloniaUI/Avalonia/issues/16572
