### ISSUE TITLE
GTK fullscreen/maximize bug when MaxWidth/MaxHeight is set

### ISSUE THREAD

**Issue by Sorien** [AvaloniaUI/Avalonia#1563]
Introduced in https://github.com/AvaloniaUI/Avalonia/pull/1495, OSX probably has same problem  

![image](https://user-images.githubusercontent.com/1270275/39687439-c143b1da-51ce-11e8-8062-3fcc9ad8dcb9.png)

I don't see any way how to prevent window to maximize.

Should max constraints be ignored when switching to fullscreen/maximize?

**Comment by grokys** [comment]
Closing this as GTK3 backend has been removed for years now.
