### ISSUE TITLE
Publish NativeAOT failed with .NET 9

### ISSUE THREAD

**Issue by noliar** [AvaloniaUI/Avalonia#15646]
### Describe the bug

publish aot failed with .NET 9 and 11.1.0-beta2.
![image](https://github.com/AvaloniaUI/Avalonia/assets/5773982/f39f51ad-9735-48b4-b41b-c5e17cdac309)

### To Reproduce

1. install .NET 9 nightly
2. Install latest Avalonia templates
3. update packages version to 11.1.0-beta2
4. set PublishAot to true
5. publish

![image](https://github.com/AvaloniaUI/Avalonia/assets/5773982/f39f51ad-9735-48b4-b41b-c5e17cdac309)

### Expected behavior

publish nativeaot with .NET 9 successfully.

### Avalonia version

11.1.0-beta2

### OS

Windows

### Additional context

sample repo: https://github.com/noliar/AvaloniaTest
github action results: https://github.com/noliar/AvaloniaTest/actions/runs/8987494959

build avalonia(version: 11.1.0-beta1) with .NET 9 is ok.
build avalonia(version: 11.1.0-beta2) with .NET 9 is failed.
build avalonia(version: 11.1.0-beta1) with .NET 8 is ok, but run failed.
build avalonia(version: 11.1.0-beta2) with .NET 8 is ok.

related: #14966

**Comment by maxkatz6** [comment]
@MrJul should we add an sdk check in the InjectIlcAvaloniaXamlOutput target?

**Comment by kekekeks** [comment]
We can probably add `<ManagedBinary Remove="@(_AvaloniaXamlCompiledAssembly)" />` before `<ManagedBinary Include="@(_AvaloniaXamlCompiledAssembly)" />` (as long as SDK doesn't set any item properties)

**Comment by MrJul** [comment]
Both would work, but my preference goes to checking the SDK version, as the workaround shouldn't be needed anymore (and should be removed down the road). I think it's better than maintaining a hack for several different SDK versions :)
