### ISSUE TITLE
Application shuts down when second window is opened from first window and first window is closed

### ISSUE THREAD

**Issue by RayyanTahir** [AvaloniaUI/Avalonia#1565]
Attached is an example project that opens a second window on user's input and closes the first one. It turns out that in doing so the application unexpectedly shuts down with no exception.
[AvaloniaApplication3.zip](https://github.com/AvaloniaUI/Avalonia/files/1980070/AvaloniaApplication3.zip)

**Comment by Gillibald** [comment]
This is still a problem because the application just crashes. Closing the MainWindow stops the MainLoop of the application. Before stopping the MainLoop all Windows should be closed.

**Comment by Naradius** [comment]
Maybe it's not a good solution, but in my small app I hide first window after opening the second, and then close the first window when I close this new one. And it kinda works.

**Comment by MonkAlex** [comment]
So, i do it as #857

**Comment by Gillibald** [comment]
Can this be closed?

**Comment by jkoritzinsky** [comment]
I'm going to close this as ExitMode has been implemented.
