### ISSUE TITLE
Bindings starting with an indexer don't work

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#1566]
This 
```
<TextBlock Text="{Binding [0].msg}"/>
```
 works in wpf but not in Avalonia (the DataContext is a collection).

**Comment by grokys** [comment]
If you need a workaround for the moment, I _think_ you could use:

```
<TextBlock Text="{Binding $self.DataContext[0].msg}"/>
```

(untested)

**Comment by ahopper** [comment]
@grokys thanks for that, I can confirm that the workaround works.
