### ISSUE TITLE
11.1.0 regression: FontFamily="Monospace" doesn't do anything

### ISSUE THREAD

**Issue by AnErrupTion** [AvaloniaUI/Avalonia#15678]
### Describe the bug

On 11.1.0-beta2, setting `FontFamily="Monospace"` anywhere (it can be in the global `Window` or an individual component) produces no visual effect, whereas it works on 11.0.10.

### To Reproduce

1. Create a new `Avalonia .NET App` project
2. Upgrade the dependencies to 11.1.0-beta2
3. In `MainWindow.axaml`, add `FontFamily="Monospace"` to the `Window` tag

### Expected behavior

I expect the font to change to the system's monospace font (see screenshots below).

### Avalonia version

11.1.0-beta2

### OS

Linux

### Additional context

11.1.0-beta2:
![Image with 11.1.0-beta2](https://github.com/AvaloniaUI/Avalonia/assets/49339966/6a8418de-9255-4946-ae96-91cb30fee9ec)

11.0.10:
![Image with 11.0.10](https://github.com/AvaloniaUI/Avalonia/assets/49339966/f4913dac-019a-4924-8b72-bbf80c1aa8f5)

**Comment by rabbitism** [comment]
Maybe that issue is targeting 0.10.x and it is too outdated.

**Comment by Gillibald** [comment]
I do not see this ever working in a cross platform way. This might only work with Fontconfig.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/AvaloniaUI/Avalonia/issues/15678#issuecomment-2261006446

@Gillibald, FontConfig indeed sets `monospace` via `fc-alias` by default *whereas Windows does not*, but the alias can be easily registered on Windows. Doing this at the Avalonia level would certainly be useful, but it's trivial for any application developer that wants to use the alias across platforms to register it via the Registry. [^1]

[^1]: [`superuser.com/revisions/1512700/2`](https://superuser.com/revisions/1512700/2#:~:text=20-,You%20could%20use%20Font%20substitution,the%20Microsoft%20Font%2Dname%20documentation.,-answered%20Dec%2026)
