### ISSUE TITLE
ILauncher launch events and intercept

### ISSUE THREAD

**Issue by profix898** [AvaloniaUI/Avalonia#15673]
### Is your feature request related to a problem? Please describe.

It's great that we now have a cross-platform URI/file launcher (``ILauncher``) in Avalonia. However, I would like to add the ability

1. to be notified by an event about the URI/file launch and
2. to intercept the call and handle the URI/file myself

Use cases are situations where you want to either a) redirect an external Uri (e.g. to you app's website) to a view within your app or b) your app uses Uri-based navigation (to perform UI actions based on the user invoking a Uri path).
In principle, it would even allow rewriting the URI (before launching a platform browser).

### Describe the solution you'd like

I would like to introduce a new event on ``ILauncher`` implementations that gets invoked when a Uri/file launch happens. The event arguments should carry information about the Uri/file and have a property to cancel the default invocation.

### Describe alternatives you've considered

Previously I had a custom Hyperlink(button) and URI launcher implementation. Having the launcher in Avalonia directly means that there will be third-party controls using ``ILauncher``. So it would be great to have some flexibility to intercept, rewrite or handle Uri/file launch calls.

**Comment by maxkatz6** [comment]
Sorry, but we don't plan on adding this API to the framework.
As it was discussed in the PR #15674, Avalonia providers a lower-level service implementation that interacts directly with the platform. It's a single responsibility of ILauncher interface - to call platform API.

It's also likely, that user might want to redefine behavior of HyperlinkButton, for example. For what they should handle ClickEvent (likely with Tunnel strategy) allowing them to handle button click in their own way. Optionally calling platform specific ILauncher if needed.

Example on how to do so:
```csharp
public MainWindow()
{
    InitializeComponent();

    var button = MyHyperlinkButton;  // defined in XAML
    // RoutingStrategies.Tunnel is important, when it's required to handle event before any default behavior. 
    button.AddHandler(HyperlinkButton.ClickEvent, MyButton_OnClick, RoutingStrategies.Tunnel);
}

private void MyButton_OnClick(object sender, RoutedEventArgs e)
{
    e.Handled = true; // marking Handled = true will cancel any other hanlers coming after.
    var button = (HyperlinkButton)sender;

    if (button.NavigateUri?.Scheme == "my-scheme")
    {
        // custom handler if necessary, under some condition (in this case, I used a `Scheme` check.
    }
    else if (button.NavigateUri is not null)
    {
        // Fall back to platform ILauncher
        _ = TopLevel.GetTopLevel(this)!.Launcher.LaunchUriAsync(button.NavigateUri);
    }
}
```
