### ISSUE TITLE
Properties overhaul has broken some styles getting applied

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1568]
To repro:

Checkout this branch: 
https://github.com/AvaloniaUI/Avalonia/tree/repro-properties

this is a repro built on the last master commit before the properties overhaul was merged.

if you run control catalog you will see:
![image](https://user-images.githubusercontent.com/4672627/39761962-54658b84-52d1-11e8-81a3-d7c38168ed46.png)

and hovering over the first startpage tab you will see background go purple. 

These styles are defined here: https://github.com/AvaloniaUI/Avalonia/blob/repro-properties/samples/ControlCatalog/DocumentTabControl.xaml#L21

ok now checkout the branch: https://github.com/AvaloniaUI/Avalonia/tree/repro/properties-overhaul-bug

this is the exactly the same but with the properties overhaul branch included.
if you run it, you will see:

![image](https://user-images.githubusercontent.com/4672627/39762112-c1bd809c-52d1-11e8-80f0-e3a9924d8a0a.png)

and hovering also fails to change the tab colour.

**Comment by grokys** [comment]
This is being called because `AvaloniaProperty.Initialize` is no longer being called for attached properties. Fix incoming.
