### ISSUE TITLE
Custom font family is not working in WebAssembly

### ISSUE THREAD

**Issue by amirhoseinadlfar** [AvaloniaUI/Avalonia#15683]
### Describe the bug

in desktop :
![image](https://github.com/AvaloniaUI/Avalonia/assets/56865457/3bb04094-92af-42c8-9eed-892609a80759)
in WebAssembly:
![image](https://github.com/AvaloniaUI/Avalonia/assets/56865457/e9541cb1-0e82-4f60-9714-655adeba3e2b)

Is there any arabic/persian support for WebAssembly?

### To Reproduce

code :
im using Avalonia.Markup.Declarative

    protected override object Build()
    {
        return new StackPanel()
            .Orientation(Orientation.Vertical)
            .Children(
                new TextBlock()
                    .Text("نام کاربری"),
                new TextBox(),

                new TextBlock()
                    .Text("رمزعبور"),
                new TextBox(),

                new TextBlock()
                    .Text("تکرار رمزعبور"),
                new TextBox()
            );
    }

font style :

        Styles.Add(new Style()
            .Selector(selector => selector.Is<TemplatedControl>())
            .Setter(TemplatedControl.FontFamilyProperty, new FontFamily("Nahid")));

font resource loading :

        //avares://AvaloniaClient/Assets/Fonts/Nahid.ttf
        FontFamily nahidFontFamily = new FontFamily(Assets.Fonts.NahidPath);

        Resources.Add("Nahid", nahidFontFamily);

### Avalonia version

11.0.10

### OS

WebAssembly

### Additional context

font family is https://github.com/rastikerdar/nahid-font

**Comment by amirhoseinadlfar** [comment]
without any font:
![image](https://github.com/AvaloniaUI/Avalonia/assets/56865457/3d3cc1cd-dcf1-447d-9e22-9079551c7ae3)
![image](https://github.com/AvaloniaUI/Avalonia/assets/56865457/0b4ed85d-3de4-4805-bda0-d2270c6b0d6d)
also, with default font, some characters like 'م' are not rendering correctly.

**Comment by timunie** [comment]
can you try 11.1 beta? Please mind the breaking changes for browser when you do so (mentioned in 11.1 beta1 thread)

**Comment by amirhoseinadlfar** [comment]
> can you try 11.1 beta? Please mind the breaking changes for browser when you do so (mentioned in 11.1 beta1 thread)

for some reason its do not recognize Avalonia.Browser namespace after updating to 11.1.0-beta1 and 11.1.0-beta2. I'm not sure if its a bug or I am missing something, its working fine on 11.0.10

csproj :
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <WasmMainJSPath>AppBundle\main.js</WasmMainJSPath>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <WasmExtraFilesToDeploy Include="AppBundle\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" Version="11.1.0-beta1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AvaloniaClient\AvaloniaClient.csproj" />
  </ItemGroup>
</Project>
```
Error :
`The type or namespace name 'Browser' does not exist in the namespace 'Avalonia' (are you missing an assembly reference?)	AvaloniaClient.Browser`
`'AppBuilder' does not contain a definition for 'StartBrowserAppAsync' and no accessible extension method 'StartBrowserAppAsync' accepting a first argument of type 'AppBuilder' could be found (are you missing a using directive or an assembly reference?)`
so I'm referenced it manually and move  staticwebassets to my project AppBundle with Copy Always option.

```

  <ItemGroup>
    <Reference Include="Avalonia.Browser">
      <HintPath>C:\Users\{USER}\.nuget\packages\avalonia.browser\11.1.0-beta1\lib\net8.0-browser1.0\Avalonia.Browser.dll</HintPath>
    </Reference>
  </ItemGroup>
```
and for some reason when I'm start project with debug, visual studio do open browser but dose not redirect browser to localhost:5000 and after sometime its give me error and close the browser so I'm have to do all my troubleshooting again. so I'm changed to Start Without Debugging and its also has some wired problems like not finding content inside _framework folder so I'm have to copy paste content manually every time, the project do not include Avalonia.Skia and I'm added it in nuget to browser project. and now I'm have this error which I'm have no idea what is about and I'm really did not expect project to run
![image](https://github.com/AvaloniaUI/Avalonia/assets/56865457/76863a62-3da5-4521-aabc-1f85550db8a0)

**Comment by amirhoseinadlfar** [comment]
> can you try 11.1 beta? Please mind the breaking changes for browser when you do so (mentioned in 11.1 beta1 thread)

but at least problem with character 'م' is fixed in desktop app

**Comment by jp2masa** [comment]
> and for some reason when I'm start project with debug, visual studio do open browser but do not redirect browser to localhost:5000 and after sometime its give me error and close the browser so I'm have to do all my troubleshooting again.

That's probably #14570.

**Comment by amirhoseinadlfar** [comment]
problem fixed.
the path of `//avares://AvaloniaClient/Assets/Fonts/Nahid.ttf` was wrong and changed to `//avares://AvaloniaClient/Assets/Fonts#Nahid` and now font can be load correctly.
it was falling back to default font instead of using nahid font so its must be the default font bug and its looks fine right now
