### ISSUE TITLE
Visibility of Text selection handles on empty TextBoxes on Android

### ISSUE THREAD

**Issue by mosabnasri** [AvaloniaUI/Avalonia#15694]
### Describe the bug

Text selection handles appears as soon as the user clicks on the TextBox even when the TextBox is empty

![image](https://github.com/AvaloniaUI/Avalonia/assets/3807345/360b74f5-17e6-4b89-98c8-b67f3724fc84)

### To Reproduce

This happens for any Basic TextBox when you run your Avalonia (11.1.0-beta2) app on Android

### Expected behavior

Text selection handles shouldn't appear when the user clicks on an empty TextBox

### Avalonia version

11.1.0-beta2

### OS

Android

**Comment by robloo** [comment]
In some android OSes (Samsung in my case) I see this same behavior. If it doesn't happen on first click into an empty TextBox it definitely happens on the second click.

I don't think this is really a bug and gives the user some useful visual feedback.
