### ISSUE TITLE
Soft Keyboard Reappearance Issue for an already focused TextBox

### ISSUE THREAD

**Issue by mosabnasri** [AvaloniaUI/Avalonia#15695]
### Describe the bug

After I focus a TextBox and manually close the keyboard, it will not reappear when I click on the TextBox again. the only way to have it back is to change the focus to another control and then clicking the TextBox again so that it has a new focus.

![AvaloniaUI_Issue_TextBox_2](https://github.com/AvaloniaUI/Avalonia/assets/3807345/3a95572f-c6a8-406b-ac4f-a46778ee681f)

### To Reproduce

This happens for any Basic TextBox when you run your app on Android

### Avalonia version

11.1.0-beta2

### OS

Android

**Comment by jp2masa** [comment]
Will be fixed by #15603.
