### ISSUE TITLE
Arabic diacritics rendered incorrectly

### ISSUE THREAD

**Issue by kerams** [AvaloniaUI/Avalonia#15693]
### Describe the bug

Certain Arabic diacritics are rendered in the wrong place, across other glyphs.

### To Reproduce

Using Noto Sans Arabic (download the ttf [here](https://fonts.google.com/noto/specimen/Noto+Sans+Arabic?preview.text=%D8%A7%D9%84%D9%92%D8%AE%D8%A8%D8%A7%D9%91%D8%B2)), put `الْخباّز` in a text block, and see
![qemu-system-x86_64_xY9d5MHzPr](https://github.com/AvaloniaUI/Avalonia/assets/5063478/8108cbd9-c602-425a-b809-93781721108b)

### Expected behavior

![vivaldi_QhaRL4jZNZ](https://github.com/AvaloniaUI/Avalonia/assets/5063478/7d40fe40-46dc-4c7d-8b65-ffd16e08bfb5)
or see https://fonts.google.com/noto/specimen/Noto+Sans+Arabic?preview.text=%D8%A7%D9%84%D9%92%D8%AE%D8%A8%D8%A7%D9%91%D8%B2

### Avalonia version

11.1.0-beta2

### OS

Android

**Comment by khaledhosny** [comment]
Looks like glyph positioning in the Y direction are applied with the wrong sign (in OpenType negative moves down and positive moves up, in many graphics libraries it is the other way around).
