### ISSUE TITLE
Website: Architecture Guide outdated and/or missing

### ISSUE THREAD

**Issue by dbenzhuser** [AvaloniaUI/Avalonia#15718]
### Describe the bug

The "Get Started" page on https://avaloniaui.net/GettingStarted links via "Architecture Guide" to https://github.com/AvaloniaUI/Avalonia/wiki/High-level-architecture-overview which describes itself as outdated. The page instead refers to https://avaloniaui.net/Blog/avalonia-platform-support-why-it-s-simple,ca378b03-fb47-4c34-a347-182acaa43d05 which doesn't exist.

### To Reproduce

Go to https://avaloniaui.net/GettingStarted and try to find an up-to-date Architecture Guide.

### Expected behavior

The Get Started page should not link to outdated or missing information.

### Avalonia version

-

**Comment by maxkatz6** [comment]
Thanks.
Fixed broken https://avaloniaui.net/Blog/avalonia-platform-support-why-it-s-simple link.

But https://avaloniaui.net/GettingStarted needs to be updated too, yeah. cc @MikeCodesDotNET

**Comment by MikeCodesDotNET** [comment]
Changed the website to point to https://avaloniaui.net/Blog/avalonia-platform-support-why-it-s-simple
