### ISSUE TITLE
Tunneling KeyDown Event not fired if TextBox has input Focus

### ISSUE THREAD

**Issue by mikeyusc** [AvaloniaUI/Avalonia#15727]
### Describe the bug

If a TextBox has input Focus, keypresses that generate TextInput events are not fired as KeyDown events as well.  Keypresses that do not generate TextInput events do fire KeyDown events (Tunnel) 
This only seems to happen on macOS, Windows & Linux function correctly.

### To Reproduce

MyText is a Vanilla TextBox

```
/* Does not appear to ever be invoked for Keys that cause TextInput*/
MyText.AddHandler(KeyDownEvent, (sender, args) =>
{
    Debugger.Break();
}, RoutingStrategies.Tunnel);
```

### Expected behavior

I expect that the KeyDown events will fire for every keystroke, as they do on Windows & Linux.

### Avalonia version

11.1.0-beta2

### OS

macOS

### Additional context

[AvaloniaTest.zip](https://github.com/AvaloniaUI/Avalonia/files/15313262/AvaloniaTest.zip)

**Comment by IanRawley** [comment]
This also happens on Android.

**Comment by mikeyusc** [comment]
So this appears to have been broken in 26035be8492883e93b12b432e541d1d683c49075
