### ISSUE TITLE
`[NotClientImplementable]` does not prevent builds

### ISSUE THREAD

**Issue by colejohnson66** [AvaloniaUI/Avalonia#15736]
### Describe the bug

Avalonia tags interfaces with `[NotClientImplementable]` to prevent downstream users from deriving their own classes. This produces an error in Rider, but not during builds.

### To Reproduce

Add the following class:

```csharp
public class MyCustomPen : IPen
{
    public IBrush? Brush { get; }
    public IDashStyle? DashStyle { get; }
    public PenLineCap LineCap { get; }
    public PenLineJoin LineJoin { get; }
    public double MiterLimit { get; }
    public double Thickness { get; }
}
```

### Expected behavior

A compiler error. Instead, it compiles fine despite the error in Rider.

### Avalonia version

11.0.10

### Additional context

The [IL rewriter](https://github.com/AvaloniaUI/Avalonia/blob/5e323b8fb1e2ca36550ca6fe678e487ff936d8bf/nukebuild/RefAssemblyGenerator.cs#L76-L90) only patches up the "ref" assemblies. This causes errors in tools using them, but not during builds that use the normal assemblies.

Using dotPeek, I can confirm that `internal void (This interface or abstract class is -not- implementable by user code !)();` only exists in the "ref" assemblies, but is missing from the "lib" ones.

#### ~/.nuget/avalonia/11.0.10/lib/net6.0/Avalonia.Base.dll
![image](https://github.com/AvaloniaUI/Avalonia/assets/11381599/a890996d-dfb8-4da1-b3d3-b7e6e2e53417)

#### ~/.nuget/avalonia/11.0.10/ref/net6.0/Avalonia.Base.dll
![image](https://github.com/AvaloniaUI/Avalonia/assets/11381599/eee12a6a-d850-45ad-9a78-48171911dafe)

#### My Implementation
![image](https://github.com/AvaloniaUI/Avalonia/assets/11381599/2827fa38-1503-4e5f-ac19-8589ba810a83)

**Comment by maxkatz6** [comment]
That's mostly by design, as we wanted to keep non-ref assemblies with no changes. Making it possible to access private APIs if needed (for example, if somebody writes a custom backend). 

But that's not ideal situation. Yes.

Alternative idea was to use C# analyzers, which would work better in this scenario. But won't support F# or other non-C# languages.

**Comment by robloo** [comment]
Personally, I think it's best to allow this usage. It's a good middle road: you get the warning telling you not to use the API. If you need it or know better you can override.

**Comment by colejohnson66** [comment]
I would be fine with that as well, but I'd expect an analyzer warning I can silence. With the current setup, Rider shows an error that I can't get rid of.

**Comment by maxkatz6** [comment]
> With the current setup, Rider shows an error 

As it should.

> that I can't get rid of.

`<AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>`

**Comment by colejohnson66** [comment]
I think my gripe is that it's an _error_, not a warning. Yet, it still behaves like a warning. I'm fine with Rider flagging usage, but not in a way that abuses ref assemblies.

Also, that property is not documented anywhere on the website.

**Comment by maxkatz6** [comment]
> Also, that property is not documented anywhere on the website.

Correct. We don't want users to rely on this property, as these APIs are unstable and can break in minor releases. Still, this option exists.

**Comment by kekekeks** [comment]
This is rather interesting. Previously Roslyn was using reference assemblies for compilation and the build would fail.
Perhaps something got changed in .NET SDK?

**Comment by kekekeks** [comment]
Actually, CoreCompile is being fed with `11.0.0/ref/net6.0/Avalonia.Dialogs.dll`, not sure why compiler ignores the internal interface member there.
