### ISSUE TITLE
Mica backdrop not working when RenderingMode is set to Win32RenderingMode.Wgl

### ISSUE THREAD

**Issue by halfuwu** [AvaloniaUI/Avalonia#15738]
### Describe the bug

Title basically says it all, when using Win32RenderingMode.Wgl, the mica backdrop doesn't work. Was using mica in my program until I started integrating [OpenTKAvalonia](https://github.com/SamboyCoding/OpenTKAvalonia) into my project and had to switch to Wgl rendering, then mica stopped working.

### To Reproduce

Create a new project.
Set RenderingMode = [Win32RenderingMode.Wgl] in Win32PlatformOptions in AppBuilder.
Make a window with TransparencyLevelHint="Mica".

### Expected behavior

Mica backdrop should be working? (Apologies if this is an already known limitation)

### Avalonia version

11.1.0-beta2

### OS

Windows

### Additional context

AppBuilder:
![image](https://github.com/AvaloniaUI/Avalonia/assets/69497698/bfd57b35-6724-4cce-9ad9-285eeb515320)

Expected Behavior:
![image](https://github.com/AvaloniaUI/Avalonia/assets/69497698/2dfd5fb5-a81f-4c78-ba14-2917e775ff6d)

Actual Behavior:
![image](https://github.com/AvaloniaUI/Avalonia/assets/69497698/443dfad4-db7e-466d-b240-5932013df883)

**Comment by maxkatz6** [comment]
That's expected, mica/acrylic require composition and directx based rendering (which is usually done via Angle OpenGL in Avalonia). It won't work with WGL.

**Comment by maxkatz6** [comment]
Btw, WGL shouldn't be necessary for OpenTK with 11.1 avalonia. But it might require some adjustments.

**Comment by halfuwu** [comment]
thank you for the clarification!!
