### ISSUE TITLE
Popup's HorizontalOffset & VerticalOffset doesn't work

### ISSUE THREAD

**Issue by RayyanTahir** [AvaloniaUI/Avalonia#1573]
Attached is a repro of the issue. There are two popups that open on the click of a button. One with horizontal offset and the other without any offset. Both show at the same location.
[PopupOffsetRepro.zip](https://github.com/AvaloniaUI/Avalonia/files/1987852/PopupOffsetRepro.zip)

**Comment by danwalmsley** [comment]
Looks like some issue with styled properties, I need @grokys or @jkoritzinsky to have a look
