### ISSUE TITLE
SafeAreaPadding is zero when keyboard is in view

### ISSUE THREAD

**Issue by kerams** [AvaloniaUI/Avalonia#15746]
### Describe the bug

The `SafeAreaPadding` value reported from `InsetsManager.SafeAreaChanged` is always zero. This is a regression compared to 11.0.10.

### To Reproduce

Subscribe to `TopLevel.InsetsManager.SafeAreaChanged`, print `SafeAreaPadding` and open/close the Android keyboard.

### Avalonia version

11.1.0-beta2

### OS

Android

**Comment by maxkatz6** [comment]
That's by design.

Keyboard taking over the screen is not part of the insets. 
To handle on screen keyboard (or other types of input panels), use TopLevel.InputPane API.
