### ISSUE TITLE
ListBox SelectionMode setting using Style

### ISSUE THREAD

**Issue by Zelibiba** [AvaloniaUI/Avalonia#15762]
### Describe the bug

I want to set SelectionMode in ListBox to 'Multiple'. If I do it directly in the ListBox, it works fine and I can choose multiple items.
However, if I set it using Style, the ListBox doesn't change selection behaviour.

### To Reproduce

Set SelectionMode using Style. Then you won't be able to select multiple items in the ListBox while holding down ctrl key.
```xaml
<ListBox>
	<ListBox.Styles>
		<Style Selector="ListBox">
			<Setter Property="SelectionMode" Value="Multiple"/>
		</Style>
	</ListBox.Styles>
	<Label>1</Label>
	<Label>2</Label>
	<Label>3</Label>
</ListBox>
```

### Expected behavior

The behavior should be the same as when setting SelectionMode directly in the ListBox.
```xaml
<ListBox SelectionMode="Multiple">
        <Label>1</Label>
	<Label>2</Label>
	<Label>3</Label>
</ListBox>
```

### Avalonia version

11.0.0, 11.0.6, 11.0.10

### OS

Windows

### Additional context

This bug doesn't occur in version 0.10.22.

**Comment by timunie** [comment]
I believe the issue is that you add the style inside ListBox styles. But the ListBox will only look for patent styles. Can you try to add the style in your root element or App.Styles?

**Comment by Zelibiba** [comment]
Oh, I forgot to mention that. This doesn't work with the style in root element or App.Styles either.

**Comment by timunie** [comment]
Can't reproduce this issue. Please file a minimal sample with the style being in App.axaml

**Comment by timunie** [comment]
will reopen this is there is a sample showing the issue
