### ISSUE TITLE
OleContext throws in ControlCatalog.Desktop

### ISSUE THREAD

**Issue by zii-dmg** [AvaloniaUI/Avalonia#1577]
Windows 7 SP1 x64, ControlCatalog.Desktop retargeted to .NET 4.7.1, 32-bit process.

OleInitialize returns random numbers (non 0).
https://github.com/AvaloniaUI/Avalonia/blob/bc3d6ec8db54f13fe89706c8272031329e955f1e/src/Windows/Avalonia.Win32/OleContext.cs#L29-L30

* OleInitialize can return S_FALSE if already initialized (https://msdn.microsoft.com/en-us/library/windows/desktop/ms690134(v=vs.85).aspx).
* I wanted to find HRESULT constant but I always have random numbers in return value. So I found [this](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751(v=vs.85).aspx):
```
typedef LONG HRESULT;
typedef long LONG;
```
Microsoft states that HRESULT is 32-bit signed integer.

Avalonia declares HRESULT as long (64-bit):
https://github.com/AvaloniaUI/Avalonia/blob/bc3d6ec8db54f13fe89706c8272031329e955f1e/src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs#L1203

I suppose this is problem - marshaling takes 8 native bytes instead of 4 so we can have garbage in HRESULT.

HRESULT from Microsoft employee: https://github.com/AArnott/pinvoke/blob/master/src/Windows.Core/HResult.cs

**Comment by Gillibald** [comment]
Should be easy to fix and makes sense. I can confirm that Hresult is represented as a 32 bit integer.

**Comment by zii-dmg** [comment]
Also shouldn't we throw Win32Exception with message and last error code instead of generic SystemException without error code?

**Comment by jkoritzinsky** [comment]
Is this fixed with both #1581 and #1583 merged in?

**Comment by zii-dmg** [comment]
Fixed
