### ISSUE TITLE
Color inconstancy between Desktop and WASM app.

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#15794]
### Describe the bug

I just noticed that colors of my app are different between Windows desktop version and WASM version.

![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/b4a117f2-b16c-46e1-b5db-ef5fc0e49193)
As you can see the WASM colors (on the left) looks washed out compared to the Desktop version (on the right).

### To Reproduce

I can see the same behavior when I open a SVG file in Edge browser (left) and Photoshop desktop (right)
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/4f30521e-4a9d-49cb-adc4-4c1e005fdba0)

We also have a non-WASM web app with same washed out colors.

### Expected behavior

Expected behavior is to have same goods colors in Web and Desktop.

I am wondering if this is a known issue, and if something can be done about that? It is probably a color profile issue, but I don't know if this is related to Skia setup which is not the same on both platform or something else???

### Avalonia version

11.0.10

### OS

Windows, WebAssembly

**Comment by dbriard** [comment]
My screenshots on Github are also washed out compared what I see outside of browser... so it is harder to see the difference on Github. Basically, I have washed out colors on Web, and pop color on Windows!

**Comment by dbriard** [comment]
I reply to myself, I found that :
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/80a4daa9-0d86-43b7-b0fc-99524743b4ae)
and changing from Default to sRGB fixed the color issue in Chrome...

Any changed there is a javascript or Avalonia option to change it for a specific website?

**Comment by maxkatz6** [comment]
Looks like sRGB should already be a default with canvas: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#colorspace
