### ISSUE TITLE
Publish: The "CompileAvaloniaXamlTask" task failed unexpectedly.

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#15816]
### Describe the bug

When I publish my app (11.1.0-beta2), I'm getting this error. The app otherwise builds fine.

```
error MSB4018: The "CompileAvaloniaXamlTask" task failed unexpectedly.
error MSB4018: System.IO.FileNotFoundException: Could not find file '/home/hanuman/GitHub/HanumanInstituteApps/Src/App.Player432Hz/Player432Hz.Desktop/obj/Release/net8.0/linux-x64/Player432Hz.pdb'.
error MSB4018: File name: '/home/hanuman/GitHub/HanumanInstituteApps/Src/App.Player432Hz/Player432Hz.Desktop/obj/Release/net8.0/linux-x64/Player432Hz.pdb'
```

It fails because of this.
```
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebuggerSupport>false</DebuggerSupport>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
  </PropertyGroup>
```

If I comment out DebugType=None, it builds fine; then I uncomment it, and it then builds fine again.

If I delete all bin and obj folders, then the error comes back.

### To Reproduce

I'm simply running my publish script.

Here's the build command

    dotnet publish "Player432Hz.Desktop/" -r linux-x64 -c Release -p:Version=3.3.1 --self-contained true -o "Output"

With DebugType=None set either in the prof file or command-line.

### Expected behavior

It should build as usual. I tried on Windows and Linux.

### Avalonia version

11.1-beta2

### OS

Linux

**Comment by maxkatz6** [comment]
It was fixed in https://github.com/AvaloniaUI/Avalonia/pull/15509
Not yet released
