### ISSUE TITLE
Objects Render Outside of Window When Maximized

### ISSUE THREAD

**Issue by mamohammadi** [AvaloniaUI/Avalonia#15822]
### Describe the bug

I am using a 1920x1080 display with 100% scaling. When I set `ExtendClientAreaToDecorationsHint="True"` and **maximize** the window, objects render outside of the window boundaries. I checked the client size and it says 1936x1048, which seems to be causing my objects to render outside the window.

Also tested on other systems and display (resolution & scaling) with different configuration but the problem still exists.

### To Reproduce

- Clone [Sample Project](https://github.com/mamohammadi/WrongWindowSize.git)
- Position window in a known screen resolution (scaling 100% to make it easier to compare Width and Height values)
- Maximize window and check window top-left and bottom-right to see texts are rendering outside
- Also check the red border (left & right) that shows the border also render outside window boundaries
- Click Update size button to see window size and compare it

### Expected behavior

When the window is maximized, all objects should render within the window boundaries.

### Avalonia version

11.0.2, 11.0.10, Latest nightly build

### OS

Windows

### Additional context

Everything works fine when window is not maximized

<img width="479" alt="Normal" src="https://github.com/AvaloniaUI/Avalonia/assets/38100774/3e410d6d-6492-499c-8027-1f1c42217b5d">

Objects render outside of window boundary when it is maximized

<img width="959" alt="MAximized" src="https://github.com/AvaloniaUI/Avalonia/assets/38100774/040d50c7-7cef-402b-b95a-4af60a60689e">

Display configuration

![Screenshot 2024-05-27 131132](https://github.com/AvaloniaUI/Avalonia/assets/38100774/43f5b815-acff-47b4-8ffd-8d836012a95e)

**Comment by timunie** [comment]
that's by design for Winodows. You should fix it by adding `Padding="{Binding $self.OffScreenMargin}"` to your Window.
