### ISSUE TITLE
Add LineHeight property to AutoCompleteBox

### ISSUE THREAD

**Issue by federicocodo** [AvaloniaUI/Avalonia#15843]
### Is your feature request related to a problem? Please describe.

I just noticed that the AutoCompleteBox control doesn't have the LineHeight property (inside the text search) like the TextBox, is it possible to add this property? I have a project where I definitely need to include this property for font customization

### Describe the solution you'd like

Is it not possible to add the property as in the TextBox control only for the text search font?

**Comment by rabbitism** [comment]
It should be easy to change with below selector

```xml
            <Style Selector="AutoCompleteBox /template/ TextBox">
                <Setter Property="LineHeight" Value="10"></Setter>
            </Style>
```

**Comment by federicocodo** [comment]
I didn't think of that, thank you very much
