### ISSUE TITLE
Menu & Flyout Rendering Artifacts

### ISSUE THREAD

**Issue by CalvinWilkinson** [AvaloniaUI/Avalonia#15845]
### Describe the bug

If the rendering mode is set to `Wgl` or `Software`, artifacts are rendered around menus or flyouts.

> [!Note]
> Rendering with the mode of AngleEgl does not show these artifacts

When using the **ActiPro** library, the rendering artifacts are much more prominent and visible. However, when using the standard built-in `<FluentTheme/>` with Avalonia, the artifacts are much more subtle but still present.

In an attempt to resolve the issue, I changed my monitor's scaling from **150%** to **100%** to see if this would change the behavior or fix the issue. However, this troubleshooting step did not have any effect on the bug.

---

Below are images of the artifact issues under each scenario between standard **Avalonia** themes and **Actipro** themes.

**Actipro Menu Artifacts**
![image](https://github.com/AvaloniaUI/Avalonia/assets/85414302/3d96bef9-0814-4920-b99d-39ef3f59e683)

**Actipro Flyout Artifacts**
![image](https://github.com/AvaloniaUI/Avalonia/assets/85414302/a8cc5e63-06e5-4465-9cd3-e73994418cfc)

**Standard Menu Artifacts**
![image](https://github.com/AvaloniaUI/Avalonia/assets/85414302/b9c60003-01b7-4ac8-b3b1-5bf2a90d0f3b)

**Standard Flyout Artifacts**
![image](https://github.com/AvaloniaUI/Avalonia/assets/85414302/ec0eb234-5900-4a84-b3c5-fa50febba3e6)

### To Reproduce

1. Create an empty standard **Avalonia** application.
2. If not updated, update the **Avalonia** Nuget packages to _**v11.0.10**_
3. Set the rendering mode to `Wgl` in the _**Program.cs**_ file
```cs
public static AppBuilder BuildAvaloniaApp()  
=> AppBuilder.Configure<App>()  
	.UsePlatformDetect()  
	.WithInterFont()  
	.With(new Win32PlatformOptions  
	{  
		RenderingMode = new[]  
		{
			Win32RenderingMode.Wgl,
		},  
	})  
	.LogToTrace();
```
4. Create a simple menu.
5. Create a button with a simple `<Flyout/>`.
6. Run the application to view the smaller artifacts. Refer to the images above.
7. Add the **ActiproSoftware.Controls.Avalonia** Nuget package version _**v24.1.0**_
8. Add the `xmlns:generation="using:ActiproSoftware.UI.Avalonia.Themes.Generation"` namespace in the _**App.axaml**_ file
9. Disable the `<FluentTheme/>`
10. Set the **Actipro** theme as shown below.
```xml
<actipro:ModernTheme AreNativeControlThemesEnabled="True">  
    <actipro:ModernTheme.Definition>  
        <generation:ThemeDefinition TabAppearanceKind="Subtle"/>  
    </actipro:ModernTheme.Definition>  
</actipro:ModernTheme>
```
11. Run the application to view the much larger and visible artifacts. Refer to the images above.

### Expected behavior

The expected behavior is that no rendering artifacts related to `<Menu/>`, `<MenuItem/>`, or `<Flyout/>` components should be shown, regardless of the rendering mode used.

### Avalonia version

v11.0.10

### OS

Windows

### Additional context

To show the issue, I created a [Sample GitHub Project](https://github.com/CalvinWilkinson/MenuRenderingIssue).

### **Windows Version**
_**Windows 11 Version 23H2 (OS Build 22631.3593)**_

### **Nuget Packages & Versions**
1. **ActiproSoftware.Controls.Avalonia** - _**v24.1.0**_
2. **Avalonia** - _**v11.0.10**_
3. **Avalonia.Desktop** - _**v11.0.10**_
4. **Avalonia.Diagnostics** - _**v11.0.10**_
5. **Avalonia.Fonts.Inter** - _**v11.0.10**_
6. **Avalonia.Svg.Skia** - _**v11.0.0.18**_
7. **Avalonia.Themes.Fluent** - _**v11.0.10**_
8. **Avalonia.Xaml.Behaviors** - _**v11.0.10.9**_
9. **CommunityToolkit.Mvvm** - _**v8.2.2**_
10. **MessageBox.Avalonia** - _**v3.1.5.1&&_

**Comment by maxkatz6** [comment]
Only AngleEgl supports window transparency. So that's by design.
In general, it would be nice to add an API to provide platform capabilities, like availability of transparency.

**Comment by CalvinWilkinson** [comment]
> Only AngleEgl supports window transparency. So that's by design. Software should be technically possible too, but not WGL.
> 
> That's because Avalonia relies on WinRT Composition rendering target on Win10 and Direct Composition on Win8.1. And these are not compatible with WGL.
> 
> In general, it would be nice to add an API to provide platform capabilities, like availability of transparency.

I agree that transparency should be available. It seems strange to have the option at all if we can't use it because transparency is not available. Or is it available on other platforms besides Windows when using `Wgl`?

**Comment by CalvinWilkinson** [comment]
I just discovered one reason this is an issue for me @maxkatz6.

I originally had my project explicitly set to `Wgl`.  It has been a while since I worked on it, so I did not remember why I was not using the default value of `AngleEgl`.

I am using 'Wgl' because my application performs some OpenGL rendering inside a custom control that I have built. This custom control, which inherits from 'OpenGlControlBase ', plays a crucial role in the rendering process. My application is a tool used to create particle effects for video game developers and their games.  

The rendering is performed and executed by [Velaptor](https://github.com/KinsonDigital/Velaptor), a 2D game development framework I have built. This framework can perform the rendering, shaders, buffers, and all of the OpenGL stuff needed to do it.

**_Velaptor_** does not use `Angle`, which is why I have to have it set to `Wgl`. This means that my application is stuck with these artifacts, which is not ideal.

I know you said that Avalonia relies on WinRT Composition, which is not compatible with WGL, but at this point, I'm eager to hear your thoughts or any suggestions you might have.  This is not good for me and might be a deal breaker.

**Options I thought of:**
1. Custom ava renderer
I could rewrite the rendering setup custom for my application, but that is a ton of work, and there are no guarantees that it will not have issues. Using my 2D game framework for the rendering saves me a ton of work. I have indeed got the rendering working as well.
2. Update Velaptor renderer
This means I could rewrite or replace **_Velaptor_**'s current rendering to use Angle or add support for Angle and also leave standard OpenGL in place, so I can choose either.  This as well could be a lot of work and cause other unknown issues for _**Velaptor**_.


Do you maybe know of or have any ideas for a workaround?

Thanks!!

**Comment by maxkatz6** [comment]
@CalvinWilkinson does Velaptor rely on any specific GL function that isn't available on the AngleGL? Note, OpenGlControlBase works with AngleGL now.
Assuming all Velaptor needs is a gl context with correct GetProcAddress.

> Do you maybe know of or have any ideas for a workaround?

You can get a handle of the popup (topLevel.TryGetPlatformHandle()), and execute any of the known transparency approaches on Windows.

**Comment by CalvinWilkinson** [comment]
> @CalvinWilkinson does Velaptor rely on any specific GL function that isn't available on the AngleGL? Note, OpenGlControlBase works with AngleGL now. Assuming all Velaptor needs is a gl context with correct GetProcAddress.
> 
> > Do you maybe know of or have any ideas for a workaround?
> 
> You can get a handle of the popup (topLevel.TryGetPlatformHandle()), and execute any of the known transparency approaches on Windows.

Correct.  All Velaptor needs is a gl context.  My application does this in the `OpenGlControlBase.OnOpenGlInit()`  method override by doing the following:
```cs
    protected override void OnOpenGlInit(GlInterface gl)
    {
        if (this.isInitialized || Design.IsDesignMode)
        {
            return;
        }

        base.OnOpenGlInit(gl);

        var glObj = GL.GetApi(gl.GetProcAddress);

        var width = (uint)Bounds.Width;
        var height = (uint)Bounds.Height;

        RenderPosition = new Vector2(width, height);

        this.scaleFactor = HardwareFactory.GetMainDisplay().HorizontalScale;
        this.renderContext = Velaptor.App.UseAvaloniaRenderContext(glObj, width, height);

        this.batcher = RendererFactory.CreateBatcher();
        this.textureRenderer = RendererFactory.CreateTextureRenderer();

        this.batcher.ClearColor = Color.FromArgb(255, 34, 34, 34);

        this.isInitialized = true;
    }
```

Are you saying to use Velaptor to render a transparent color to the popup's surface? I did not know I could do that to an Avalonia control.  🤔

Even if I had Velaptor do this, wouldn't the next render pass/update for the popup rerender the non-transparent background onto the popup again?

**Comment by maxkatz6** [comment]
> Are you saying to use Velaptor to render a transparent color to the popup's surface? I did not know I could do that to an Avalonia control. 🤔

No.
Your best choices are:
1. See how hard it would be to run Velaptor on top of angle. Unless there are any missing APIs in Angle, you might not need to change any line of Velaptor code.
2. Run Win32 API to make popup transparent. It's not related to rendering or anything. There are some legacy and slow win32 APIs for that, most likely using `WS_EX_LAYERED`. Avalonia itself uses more performant `WS_EX_NOREDIRECTIONBITMAP`, but it's only integrated with Direct/Win32 Composition engines that only supports DirectX (and Angle).

**Comment by CalvinWilkinson** [comment]
> > Are you saying to use Velaptor to render a transparent color to the popup's surface? I did not know I could do that to an Avalonia control. 🤔
> 
> No. Your best choices are:
> 
> 1. See how hard it would be to run Velaptor on top of angle. Unless there are any missing APIs in Angle, you might not need to change any line of Velaptor code.
> 2. Run Win32 API to make popup transparent. It's not related to rendering or anything. There are some legacy and slow win32 APIs for that, most likely using `WS_EX_LAYERED`. Avalonia itself uses more performant `WS_EX_NOREDIRECTIONBITMAP`, but it's only integrated with Direct/Win32 Composition engines that only supports DirectX (and Angle).

ok perfect.  I will look into these.  Thanks for your help!

**Comment by kekekeks** [comment]
Controls are supposed to bind to `TopLevel.ActualTransparencyLevel` property to detect if transparency is enabled for the current toplevel and act accordingly.

**Comment by kekekeks** [comment]
![image](https://github.com/AvaloniaUI/Avalonia/assets/1067584/79a25e53-c4ea-4d4e-9ff4-acc4ebb363a3)
This is a bug in our fluent theme, BTW, and should be raised as a separate issue
