### ISSUE TITLE
Error publishing NativeAOT win x86 with .NET 9

### ISSUE THREAD

**Issue by dhirennjaypal** [AvaloniaUI/Avalonia#15863]
### Describe the bug

I made blank project with Avalonia prerelease and moved Program.cs from Project.Desktop to Project and deleted Project.desktop
Changed CPU to x86 and changed .NET version to .NET 9.
Added publishaot to true to csproj
when i build and run project, it runs correctly but when i publish i get error
here are files for reference

[publish_log.txt](https://github.com/AvaloniaUI/Avalonia/files/15499364/publish_log.txt)
[GalaxyResearchTools.csproj.txt](https://github.com/AvaloniaUI/Avalonia/files/15499374/GalaxyResearchTools.csproj.txt)
[FolderProfile.pubxml.txt](https://github.com/AvaloniaUI/Avalonia/files/15499379/FolderProfile.pubxml.txt)

### To Reproduce

- make blank project 
- Update to Avalonia prerelease
- move Program.cs from Project.Desktop to Project and delete Project.desktop
- Change CPU to x86 and changed .NET version to .NET 9.
- Add publishaot to true to csproj
- Publish project, self contained win-x86

### Expected behavior

It should have build the program

### Avalonia version

11.1.0-beta2

### OS

Windows

**Comment by maxkatz6** [comment]
Please try latest nightly builds.
