### ISSUE TITLE
VS Code extension ?

### ISSUE THREAD

**Issue by SeleDreams** [AvaloniaUI/Avalonia#1587]
Hello, i'm wondering if there's any plans for a VS Code extension since VS Code is one of the best IDE for the cross platform C# development

**Comment by circler3** [comment]
Do you mean a *xaml* extension?

**Comment by pikachuk** [comment]
I'm mostly talking about an equivalent to the visual studio extension https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaforVisualStudio

**Comment by j4nbob** [comment]
yes, for truly cross platform, avalonia is barking up with wrong tree with the visual extension. the correct tree would be Visual Studio Code.

**Comment by tuan-tu-tran** [comment]
So is this a duplicate of #999 ?

**Comment by vleeuwenmenno** [comment]
Sadly they are still Windows and not cross-platform by only supporting Visual Studio and not Visual Studio Code.

**Comment by maxkatz6** [comment]
@vleeuwenmenno Rider is recommended IDE to work with Avalonia and it works on Windows, Linux and macOS.
Also I want to mention, that Rider XAML editor works better with Avalonia, than Visual Studio does.

**Comment by vleeuwenmenno** [comment]
Cool, I will give Rider a try but I don't like the fact it costs 139 euro per year ... VSCode is free and works very well but I will give Rider a try and see if it's worth the 139 euro per year. (Still doesn't quite solve this issue however it points out a hopefully good alternative)

**Comment by maxkatz6** [comment]
Closing as duplicate of https://github.com/AvaloniaUI/Avalonia/issues/999 to simplify issue tracking
