### ISSUE TITLE
DBus folder dialog doesn't work with RHEL 8.5

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#15886]
### Describe the bug

Literally nothing happens from the app point of view

### To Reproduce

Run an avalonia app on RHEL 8.5, CentOS 8.5, AlmaLinux 8.5 (exact version)

### Expected behavior

Folder dialog is shown

### Avalonia version

11.x

### OS

Linux

### Additional context

DBus thingy should gracefully fall back if the distro doesn't support the latest thing.

![image](https://github.com/AvaloniaUI/Avalonia/assets/1067584/7e700ed5-40c3-4e25-9431-981a15f049f3)

**Comment by kekekeks** [comment]
https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.portal.FileChooser.xml
>```
>      * ``directory`` (``b``)
>
>        Whether to select for folders instead of files. Default is to select files.
>
>        This option was added in version 3.
>```

**Comment by ptasev** [comment]
Can this be closed?
