### ISSUE TITLE
SaveFilePickerAsync duplicates FilePickerFileType extension when there is more than one period in the extension.

### ISSUE THREAD

**Issue by halfuwu** [AvaloniaUI/Avalonia#15887]
### Describe the bug

When passing a FilePickerFileType into SaveFilePickerAsync that has an extension with two or more periods, the extension is duplicated upon save.

With a SuggestedFileName of "DefaultPlaylist":
A pattern of "*.playlist" results in "DefaultPlaylist.playlist"
A pattern of "*.fp.playlist" results in "DefualtPlaylist.fp.playlist.fp.playlist"

### To Reproduce

Create a FilePickerFileType with the pattern "*.fp.playlist"
Save a file using SaveFilePickerAsync and any SuggestedFileName

### Expected behavior

The extension should only be tacked onto the saved filename once instead of twice.

### Avalonia version

11.1.0-beta1

### OS

Windows

### Additional context

**FilePickerFileType**
![image](https://github.com/AvaloniaUI/Avalonia/assets/69497698/fc53f479-c2ca-4cc1-be43-7d00fc563601)
**Popup from SaveFilePickerAsync**
![image](https://github.com/AvaloniaUI/Avalonia/assets/69497698/55d1b077-95a4-4576-875b-038b37ae1729)
**Saved file**
![image](https://github.com/AvaloniaUI/Avalonia/assets/69497698/25c66528-90e7-4196-a2d9-c70cb6671c6b)

**Comment by daraber** [comment]
[IFileDialog](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ifiledialog) appends the pattern/filter extension to the inserted file name when more than 1 period is specified (as can be seen in provided screenshot). When only one period is included, no extension is appended to the file name when the dialog is shown. Hence, when you exit the dialog, the resulting path will have duplicated extensions (as expected given the file name text). This behavior can not be avoided (AFAIK) when calling the IFileDialog API.

Furthermore, Win32 documents state the following:
> All file systems follow the same general naming conventions for an individual file: a base file name and an optional extension, separated by **a period**.  ([Win32: Naming Files, Paths, and Namespaces](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file))

**Comment by halfuwu** [comment]
gotcha thanks for the clarification, will figure out an alternative
