### ISSUE TITLE
[Linux] WindowStartupLocation does not respect DesktopScaling factor

### ISSUE THREAD

**Issue by logiclrd** [AvaloniaUI/Avalonia#15905]
### Describe the bug

When `WindowStartupLocation` is set to `CenterScreen` or `CenterOwner`, if the desktop environment has an ambient scaling factor, the window is not centred properly. Its position is set as though its size were unscaled -- so if `DesktopScaling` is 2, for instance, the window is offset to the right and down by a quarter of its size. It gets centred as though the window is half of its actual size, so it extends further to the right and bottom than it should. This has been observed on an Ubuntu 24.04 system using Xorg.

### To Reproduce

Set up a window with `WindowStartupLocation` set to `CenterScreen`. Set the `DesktopScaling` factor to a non-zero value. I actually don't know how this is done -- just that it already has the value `2` on my system, which is a laptop with a 2560x1600 resolution screen. Start the application. Note that the window is not precisely in the centre of the screen.

### Expected behavior

The window should be precisely in the centre of the screen's working area.

### Avalonia version

11.0.10

### OS

Linux

### Additional context

The following work-around seems to work for me:
```
		void CenterWindow()
		{
			if (Screens.Primary is Screen primaryScreen)
			{
				this.Position = new PixelPoint(
					primaryScreen.WorkingArea.X + (int)(primaryScreen.WorkingArea.Width - this.Width * this.DesktopScaling) / 2,
					primaryScreen.WorkingArea.Y + (int)(primaryScreen.WorkingArea.Height - this.Height * this.DesktopScaling) / 2);
			}
		}
```
This can be called from the `Loaded` event of the `Window`.

**Comment by thevortexcloud** [comment]
> actually don't know how this is done

https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI

**Comment by logiclrd** [comment]
Awesome, good to know :-)
