### ISSUE TITLE
Windows OpenGL FullScreen artifacts with popups and wrong mouse hittests

### ISSUE THREAD

**Issue by peter-friedland-t2i** [AvaloniaUI/Avalonia#15921]
### Describe the bug

We use Avalonia in Windows OpenGL Mode. The reason is we use [ActiVIZ.NET](https://www.kitware.eu/activiz/) to integrate VTK as an avalonia control (no support for angle :().

Switching to fullscreen or even to a none styled window with manually setting the size of the window to the desktop produce the same artifacts and flickering. In addition hit tests behave wrongly when I click an element on the popup controls on the main window react.

We need the fullscreen feature to run the application in a medical environment on a windows laptop and therefore are very open for help and advice.

### To Reproduce

Open attached application and open the combobox. On Open and close the window procudes some flickering:

[FullScreenError.zip](https://github.com/user-attachments/files/15575475/FullScreenError.zip)

### Expected behavior

When the application is fullscreen, the app should not produce flickering, artifacts and hit detection should work.

### Avalonia version

11.0.10

### OS

Windows

### Additional context

Graphics Card: Intel Iris XE Graphics
Operating System Details: Windows 10.0.19045

**Comment by kekekeks** [comment]
Note that the entire WGL mode is more or less experimental and is not really supported.

You can try adding glFinish call though.

**Comment by peter-friedland-t2i** [comment]
@kekekeks where should I add this call?

**Comment by kekekeks** [comment]
Once you've finished rendering the frame

**Comment by peter-friedland-t2i** [comment]
it seems that it works with avalonia 11.1.2 fine. It used to work also well for PCs with nvidia graphics cards. we can close this issue.
