### ISSUE TITLE
Feature Request: Keep a single VkDevice alive per VkInstance so RenderDoc works

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#15926]
### Is your feature request related to a problem? Please describe.

Currently, at least 2 `VkDevice`s are created: one for initialization and one for rendering. The initialization device is `Dispose`d, but `Dispose` is not implemented (probably due to threading concerns?):

https://github.com/AvaloniaUI/Avalonia/blob/6b48721391af7a34f235baabbbfb6fe07db7772f/src/Avalonia.Vulkan/VulkanPlatformGraphics.cs#L89-L90

https://github.com/AvaloniaUI/Avalonia/blob/6b48721391af7a34f235baabbbfb6fe07db7772f/src/Avalonia.Vulkan/Interop/VulkanDevice.cs#L60-L63

As such, there are 2 active `VkDevice`s in the same `VkInstance`, which likely won't ever be supported by RenderDoc: https://github.com/baldurk/renderdoc/issues/2974#issuecomment-1630446021.

### Describe the solution you'd like

I think the correct solution would be to implement `Dispose` properly.

### Describe alternatives you've considered

The following alternatives are easier and may be valid as well, for now:

- Call `vkDestroyDevice` after the no-op `Dispose` call, here:

    https://github.com/AvaloniaUI/Avalonia/blob/6b48721391af7a34f235baabbbfb6fe07db7772f/src/Avalonia.Vulkan/VulkanPlatformGraphics.cs#L89-L90

- Implement `Dispose` by simply calling `vkDestroyDevice`, ignoring any threading concerns, here:

    https://github.com/AvaloniaUI/Avalonia/blob/6b48721391af7a34f235baabbbfb6fe07db7772f/src/Avalonia.Vulkan/Interop/VulkanDevice.cs#L60-L63

**Comment by kekekeks** [comment]
I think the idea was to track all associated resources so we could prevent potential crashes. But calling vkDestroyDevice from VulkanDevice.Dispose makes the most sense.
