### ISSUE TITLE
Possibly wrong pattern match in `VirtualizingStackPanel.GetControl`

### ISSUE THREAD

**Issue by jnyrup** [AvaloniaUI/Avalonia#15955]
### Describe the bug

In C# the pattern `x is not A or B` is interpreted as `x is (not A) or B` and not `x is not (A or B)`.

I was grep'ing my local git repositories for code that matched and stumbled upon 
https://github.com/AvaloniaUI/Avalonia/blob/82e3613939af5451597d3c19f3a48e0a8ba888f3/src/Avalonia.Controls/VirtualizingStackPanel.cs#L284

So this code is not checking whether `direction` is "_neither_ `First` _nor_ `Last`".
As `Last` is covered by `not First` Roslyn even lowers this to `!= First`.
As such this looks like a bug to me

![image](https://github.com/AvaloniaUI/Avalonia/assets/919634/e9180989-2e66-4f69-b754-07f71a4cb83e)

[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+wIQDYAIBiWAFAHICGAbgJYDmZALlRAHYAiVsYjLuAJhzC5NmASlwBeAHy4AsAChcivgKE8qAZ1zMI9XOWp1ubFUYB0+Dut3Q9lWg2HtOZgDJkrAbnnzMOAlgAmUjtDRxNhZWdhMSlZBSV+KLVNbV1ggwcWJ0EzCygrXBt9eyNs1WZTNysRLzl5AAEAZlwYZgBXAFtbDNLwlnkAb3klPRgEegAaYaUABVhqCDb1KfjFPKsVkarJ6cUXGAAzHdXcACVaAAtjkYBVAAdNpVYIAHdmR8UZshoYe4/cL4/Z5vFYAXyAA===)

### To Reproduce

I found this by analyzing the code and didn't write any code I don't know and haven't looked into if this potential bug can be hit.

### Avalonia version

master

**Comment by maxkatz6** [comment]
It is wrong, you are correct.
Whole condition should be changed from
```diff
if (count == 0 || 
-                fromControl is null && direction is not NavigationDirection.First or NavigationDirection.Last)
+               (fromControl is null && direction != NavigationDirection.First && direction != NavigationDirection.Last)
```

**Comment by timunie** [comment]
@jnyrup maybe you can file a PR with the fix? 🙏 thx

**Comment by jnyrup** [comment]
> @jnyrup maybe you can file a PR with the fix? 🙏 thx

Unfortunately I don't have the time to do this.
I'll pass it on to other contributors.
