### ISSUE TITLE
DevTools Tree Jumps

### ISSUE THREAD

**Issue by IvanJosipovic** [AvaloniaUI/Avalonia#15970]
### Describe the bug

When using the DevTools, the tree jumps when expanding the items. This makes the DevTools very frustrating to use.

### To Reproduce

Open DevTools, go to the visual tree, and expand the items until you notice the issue.

https://github.com/AvaloniaUI/Avalonia/assets/9521987/bb91648a-bfd1-4776-bfd6-36f5c23e36cf

### Avalonia version

11.0.10

### OS

Windows

**Comment by stevemonaco** [comment]
To expand on this, the automatic scrolling to keep text on the window (after inspecting a control) seems to be reset (the horizontal scroll) when viewport changes happen in the DevTools `TreeView`: expand an item, click scroll up/down, etc.

I've replicated this in ControlCatalog:
1. Pick a new page.
2. Inspect a control that's "deep" while in the Visual Tree in DevTools. Large changes seem to replicate better.
3. Expand item or click scrollbar.

**Comment by rabbitism** [comment]
related https://github.com/AvaloniaUI/Avalonia/issues/15335

**Comment by workgroupengineering** [comment]
#11704

**Comment by timunie** [comment]
Closing as duplicate
