### ISSUE TITLE
The text display is offset upwards in the Ubuntu system

### ISSUE THREAD

**Issue by qfmee** [AvaloniaUI/Avalonia#15984]
### Describe the bug

The text display is offset upwards in the Ubuntu system, but there is no problem in Windows.
avalonia 11.1.0-beta2
ubuntu-24.04-desktop-amd64
<img width="443" alt="屏幕截图 2024-06-11 131712" src="https://github.com/AvaloniaUI/Avalonia/assets/74282924/f15ae037-4b33-46bc-ae4f-ff18bca90593">

### To Reproduce

Publishing the same program to different systems may result in different display effects

### Avalonia version

11.1.0-beta2

### OS

Linux

**Comment by timunie** [comment]
Windows and Linux may use different fonts which may lead to different results. Can you check applied font in dev tools? Also please file a minimal sample to reproduce if applicable.

**Comment by thevortexcloud** [comment]
Also scaling on Linux works a bit differently. You can see if setting the value as described here fixes it:

https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI

**Comment by kerams** [comment]
Noticed the same thing. I have a font that only covers a handful of glyphs in the private use area and if I reference it first in `FontFamily` in the resource dictionary, texts across the entire application are shifted upwards, even when they do not contain characters that use the said font. If I reference the font last, the shift does not occur.

**Comment by timunie** [comment]
@kerams please test latest nightly. If issue persists, file a minimal sample for further investiagtion

**Comment by kerams** [comment]
@timunie, https://github.com/kerams/font

There are 2 problems:

- both text blocks should look the same - there's no reason (as far as I understand this) that a difference in the ordering of font references should result in vertical alignment changes, especially when it's the same glyphs that are being rendered
- neither text block looks right - the left and right parts of the text in the text block should be aligned.
