### ISSUE TITLE
AffectsRender<TVisual> only seems to work with properties defined in TVisual class

### ISSUE THREAD

**Issue by beemobile4net** [AvaloniaUI/Avalonia#15996]
### Describe the bug

In reference to #15993 - it seems, that call to `AffectsRender<TVisual>` will only work with those properties, which are defined for type TVisual. If the properties are defined on a different type `TComponent` and `TVisual` contains an object of `TComponent`, then even calling `AffectsRender<TVisual>` in static constructor for `TVisual` and passing those properties from `TComponent` into it, will not cause proper re-rendering of `TVisual`, upon changes of values of properties in `TComponent`.

### To Reproduce

Say I have a control, which may look like this:

```csharp
public class Ctrl : TemplatedControl
{
    static Ctrl()
    {
        AffectsRender<Ctrl>(LinethicknessProperty);
    }

    public static readonly StyledProperty<double> LinethicknessProperty = AvaloniaProperty.Register<Ctrl, double>(
     nameof(Linethickness),
     1.0);

    public double Linethickness
    {
        get => this.GetValue(LinethicknessProperty);
        set => this.SetValue(LinethicknessProperty, value);
    }

    public override void Render(DrawingContext context)
    {
        base.Render(context);
        /// Do some drawing with LinethicknessProperty.
    }

}
```

In order for value changes of `Linethickness` property to cause re-render of the control, call to `AffectsRender<Ctrl>(LinethicknessProperty);` must be performed.

Now say I have more properties, which influence the rendering, but I want to have them in a different class from `Ctrl`. Let's say I want to have a `DrawingSettings` class, which will contain multiple properties, values of which will influence rendering, in this example these would be: `Linethickness` and `AnotherThickness`:

```csharp
public class DrawingSettings : AvaloniaObject
{
    public static readonly StyledProperty<double> AnotherThicknessProperty = AvaloniaProperty.Register<Ctrl, double>(
        nameof(AnotherThickness),
        0.0);

    public double AnotherThickness
    {
        get => this.GetValue(AnotherThicknessProperty);
        set => this.SetValue(AnotherThicknessProperty, value);
    }

    public static readonly StyledProperty<double> LinethicknessProperty = AvaloniaProperty.Register<Ctrl, double>(
        nameof(Linethickness),
        1.0);

    public double Linethickness
    {
        get => this.GetValue(LinethicknessProperty);
        set => this.SetValue(LinethicknessProperty, value);
    }
}
```

Now I'm going to change `Ctrl` class so that it just contains one property of `DrawingSettings` type, which can be used to manipulate (change) drawing settings. At the same time, I would assume, that I would perform a call to `AffectsRender<Ctrl>` and pass it the properties to be monitored for value changes:

```csharp
public class Ctrl : TemplatedControl
{
    static Ctrl()
    {
        AffectsRender<Ctrl>(DrawingSettings.LinethicknessProperty);
        AffectsRender<Ctrl>(DrawingSettings.AnotherThickness);
    }

    public static readonly StyledProperty<DrawingSettings> SettingsProperty = AvaloniaProperty.Register<Ctrl, DrawingSettings>(
     nameof(Settings),
     new());

    public DrawingSettings Settings
    {
        get => this.GetValue(SettingsProperty);
        set => this.SetValue(SettingsProperty, value);
    }

    public override void Render(DrawingContext context)
    {
        base.Render(context);
        /// Do some drawing with LinethicknessProperty.
    }

}
```

However, if values of `Ctrl.DrawingSettings.AnotherThickness` property or `Ctrl.DrawingSettings.Linethickness` property change, no re-rendering happens.

### Expected behavior

I would expect `Render(DrawingContext)` method to be called on `Ctrl` object.

### Avalonia version

11.0.10

### OS

Windows

**Comment by maxkatz6** [comment]
It is expected, since these two properties are not changed in the Ctrl object. It doesn't know about anything nested.
You can subscribe on Settings.PropertyChanged, check the property and call `ctrl.InvalidateVisual()` directly.
