### ISSUE TITLE
EagerParentStackEnumerator is incompatible with XAML built with older avalonia versions

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#16020]
### Describe the bug

![image](https://github.com/AvaloniaUI/Avalonia/assets/1067584/e52a8423-a12b-4fa0-b03e-ef235ce952e0)

The new generated XAML and IAvaloniaXamlIlEagerParentStackProvider assume that all parents in the chain will also support IAvaloniaXamlIlEagerParentStackProvider. But it's not the case if relevant parent XAML was built with a previous Avalonia version. 

### To Reproduce

1) have XAML referencing SimpleTheme via StyleInclude in a library built with Avalonia 11.0.0
2) use that library with Avalonia from the current master
3) Kaboom

### Avalonia version

11.1.x

**Comment by kekekeks** [comment]
Introduced by https://github.com/AvaloniaUI/Avalonia/pull/15070

@MrJul

**Comment by MrJul** [comment]
Ah, good one.

I kept type checks everywhere in C# code and verified that old compiled XAML without the eager provider still loaded correctly. However I didn't consider that a XAML context with the *new* implementation could directly call an old one.

I'll handle fixing that either tomorrow or over the weekend.
