### ISSUE TITLE
Regression in 11.1 Beta2 and RC1 concerning EmbeddableControlRoot's EmbeddableWindow implementation on Windows

### ISSUE THREAD

**Issue by fitdev** [AvaloniaUI/Avalonia#16048]
### Describe the bug

If Avalonia is hosted inside a Windows app, like WinForms for example, then whenever user interacts with Avalonia's content embedded in the `EmbeddableControlRoot`, the containing app window (i.e. WinForms main window) loses focus.

### To Reproduce

Just use EmbeddableControlRoot directly or via WinFormsAvaloniaControlHost to see this behavior.

### Expected behavior

The containing parent window should not lose focus when user interacts with Avalonia embedded via EmbeddableControlRoot.

### Avalonia version

11.1

### OS

Windows

### Additional context

After some investigation turns out the actual EmbeddableWindow implementation used by EmbeddableControlRoot to create a native Windows window does _NOT_ set `WS_CHILD` style:

![Screenshot_20240618_000557](https://github.com/AvaloniaUI/Avalonia/assets/8166847/bdb15cb7-e369-4719-9917-8a354dd2da7a)

Once that style is added manually (via, for instance User32's `SetWindowLong` API) everything works fine.

So it seems, that the code for creating embedded windows on Windows should be reviewed, especially within the Interop context.

**Comment by maxkatz6** [comment]
This line is responsible for attaching embeddable control to the parent: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32.Interoperability/WinForms/WinFormsAvaloniaControlHost.cs#L60

It never really did set CHILD style on parent though, so regression must come from something else. On other hand, this style would make sense anyway.

**Comment by timunie** [comment]
@fitdev a PR is welcome if you know how to improve it.

**Comment by fitdev** [comment]
After some more digging, the culprit seems in the [WindowImpl.UpdateWindowProperties](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/WindowImpl.cs#L1401) which unconditionally does this `WindowStyles style = WindowStyles.WS_CLIPCHILDREN | WindowStyles.WS_OVERLAPPEDWINDOW | WindowStyles.WS_CLIPSIBLINGS;` and then modifies that style, _without taking into account the already existing style_ (i.e. throws away `WS_CHILD` that was set by `EmbeddedWindowImpl.CreateWindowOverride`.

The `WindowImpl.UpdateWindowProperties` itself is called through:
[Win32Platform.CreateEmbeddableWindow](https://github.com/AvaloniaUI/Avalonia/blob/af104b98e83a6216324607f023e93000d2b770c1/src/Windows/Avalonia.Win32/Win32Platform.cs#L223)
[WindowImpl.Show](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/WindowImpl.cs#L689) 
[WindowImpl.ShowWindow](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/WindowImpl.cs#L1162)

So, the bottom line is that this gets screwed up in the `WindowImpl.UpdateWindowProperties` routine which does not preserve the initially correctly set `WS_CHILD` flag. So someone who owns this area should look into how best to pass the information to the UpdateWindowProperties that it should preserve certain window styles (perhaps via WindowProperties struct, a field, a parameter, or a check within the routine itself)

**Comment by fitdev** [comment]
Submitted PR. Can someone review it please? @timunie , @maxkatz6
