### ISSUE TITLE
PathMarkupParser doesn't support comma separator for implicit commands

### ISSUE THREAD

**Issue by miguelrochefort** [AvaloniaUI/Avalonia#1606]
This works:
```xml
<Path Data="M0,0 L 10,10 20,20" />
```
This doesn't work:
```xml
<Path Data="M0,0 L 10,10,20,20" />
```

According to the [SVG specification](https://www.w3.org/TR/SVG11/paths.html#PathDataGeneralInformation):

> - Superfluous white space and separators such as **commas** can be eliminated (e.g., "M 100 100 L 200 200" contains unnecessary spaces and could be expressed more compactly as "M100 100L200 200").
> - The command letter can be eliminated on subsequent commands if the same command is used multiple times in a row (e.g., you can drop the second "L" in "M 100 200 L 200 100 L -100 -200" and use "M 100 200 L 200 100 -100 -200" instead).

**Comment by Gillibald** [comment]
I think you cant distinguish between them if you would allow comma seperator for commands.
