### ISSUE TITLE
Qt for WebAssembly

### ISSUE THREAD

**Issue by Suriman** [AvaloniaUI/Avalonia#1607]
This is great news!. 
http://blog.qt.io/blog/2018/05/22/qt-for-webassembly/

Will it mean that in the future we can see Avalonia running in a browser with WebAssembly?

**Comment by jmacato** [comment]
I don't see the connection between Qt & Avalonia with regards to WebAssembly so closing this for now.

**Comment by Suriman** [comment]
@jmacato Sorry, I was wrong. Avalonia works with GTK not with QT.

**Comment by jmacato** [comment]
@Suriman No worries pal, I'm quite stoked at the possibilities that WebAssembly support on Avalonia will show :smile:
