### ISSUE TITLE
TrayIcon becomes unresponsive

### ISSUE THREAD

**Issue by logiclrd** [AvaloniaUI/Avalonia#16085]
### Describe the bug

I have an application that defines a `<TrayIcon>` in App.axaml. It has an associated menu. I left it running overnight, and in the morning I found it to be very nearly unresponsive. Right-clicking on it displays the menu -- after a delay of about 25 seconds. I selected an option and several minutes later the application still has not received the associated `Command` activation. Upon restarting the application, the `<TrayIcon>` and associated menu are responsive once more.

### To Reproduce

I don't have an isolated reproduction at this time. But, if my application is left running for a long time, eventually the behaviour becomes as described.

### Expected behavior

The `<TrayIcon>` and associated menu should remain responsive & functional.

### Avalonia version

c71d999

### OS

Linux

### Additional context

I am running on a C.I. build from PR #16024, because I need the bug fix for `TrayIcon` menu item crashes.

**Comment by maxkatz6** [comment]
Fixed by https://github.com/AvaloniaUI/Avalonia/pull/16024

**Comment by logiclrd** [comment]
I haven't seen a recurrence of this, but it was originally observed with a C.I. build of #16024, i.e. already with the fix. Hopefully you're right, though, and it's a thing of the past :-) I'll keep an eye out for it.
