### ISSUE TITLE
In some cases, the application may become partially transparent

### ISSUE THREAD

**Issue by zg4455** [AvaloniaUI/Avalonia#16099]
### Describe the bug

In some cases, the application may become partially transparent
When clicking the button, it generates more frequently and the program will not report any errors, but it will instantly become normal

### To Reproduce

When clicking the button, it generates more frequently and the program will not report any errors, but it will instantly become normal

### Avalonia version

11.0.10

### OS

Windows

### Additional context

![111](https://github.com/AvaloniaUI/Avalonia/assets/25166463/dfb86f6f-a4c6-4ac4-90d1-8ed1ea3a0a54)
![222](https://github.com/AvaloniaUI/Avalonia/assets/25166463/7875602a-00d5-44f5-8732-f33aede73163)

**Comment by timunie** [comment]
Need a minimum sample to reproduce

**Comment by zg4455** [comment]
sample URL:      http://soft.redefine.ltd/A8.zip

**Comment by zg4455** [comment]
https://github.com/AvaloniaUI/Avalonia/assets/25166463/177c3a09-f21f-4faf-9e3d-89ab9ce079a2

**Comment by zg4455** [comment]
The video flashes at the 26th second

**Comment by zg4455** [comment]
The current code has been streamlined a lot, and the complete system will flash very frequently

**Comment by zg4455** [comment]
> Need a minimum sample to reproduce

sample URL: http://soft.redefine.ltd/A8.zip

**Comment by maxkatz6** [comment]
This is likely might be a bug in skia or video drivers.
