### ISSUE TITLE
The large number of text controls affects the animation frame rate with a custom font

### ISSUE THREAD

**Issue by 1324278444** [AvaloniaUI/Avalonia#16095]
### Describe the bug

I created a keyboard control and placed it on the window. When the window runs, the animation frame rate will be relatively low. When I remove the keyboard, everything works fine, but the same interface works fine in WPF

### To Reproduce

![动画](https://github.com/AvaloniaUI/Avalonia/assets/22444419/670fb74f-3db0-4eff-9a1b-b990bbe6f410)

### Avalonia version

11.1.0-rc1

### OS

Windows

### Additional context

![image](https://github.com/AvaloniaUI/Avalonia/assets/22444419/eed0a751-4a45-4fd2-b973-5b17bed5bdbe)
![image](https://github.com/AvaloniaUI/Avalonia/assets/22444419/0138ceb1-4147-406e-a7e8-557a856e1056)

**Comment by timunie** [comment]
Is that debug mode? Performance can only be judged using the App in release mode without a debugger attached.

**Comment by 1324278444** [comment]
> Is that debug mode? Performance can only be judged using the App in release mode without a debugger attached.

In release mode, the animation is not smooth either

**Comment by 1324278444** [comment]
> 需要重现或 dotTrace 分析。否则，这里没有什么可操作的，因为很难说到底是什么很慢。

[AvaloniaApplication1.zip](https://github.com/user-attachments/files/15966764/AvaloniaApplication1.zip)
I hope you can help me solve this problem. Thank you

**Comment by maxkatz6** [comment]
@1324278444 thanks. Checked with dotTrace, and found two details:
- UI thread is mostly fine, render thread is choking on animation.
- It's not related to the number of controls, but more specific to text entries
- The most time (and memory) is spent on native Skia side rendering text for each tick of the each frame

**Comment by 1324278444** [comment]
> @1324278444 thanks. Checked with dotTrace, and found two details:
> 
> * UI thread is mostly fine, render thread is choking on animation.
> * It's not related to the number of controls, but more specific to text entries
> * The most time (and memory) is spent on native Skia side rendering text for each tick of the each frame

Thank you, how can I solve this problem

**Comment by maxkatz6** [comment]
@1324278444 apparently, it's also font related. As @MrJul noticed, Source Han Sans CN doesn't ASCII characters at all, only full width fallbacks, which makes its rendering pretty slow. If you remove this font (or use another font for ASCII text), it should be smooth.

**Comment by 1324278444** [comment]
> @1324278444 apparently, it's also font related. As @MrJul noticed, Source Han Sans CN doesn't ASCII characters at all, only full width fallbacks, which makes its rendering pretty slow. If you remove this font (or use another font for ASCII text), it should be smooth.

Thank you. After changing the font, the animation became smoother
