### ISSUE TITLE
Creating Avalonia custom controls

### ISSUE THREAD

**Issue by uxmal** [AvaloniaUI/Avalonia#1610]
Look at the screen shot of the Windows Forms Reko decompiler (https://github.com/uxmal/reko)
![image](https://user-images.githubusercontent.com/10154465/40479075-00f3997e-5f4b-11e8-97ee-16840d9b643e.png)
I'm evaluating alternate GUI front ends to supplant the Windows Forms UI to make the interface more modern and make it possible to run on other platforms than Windows. After searching the web I encountered Avalonia and what I'm seeing is promising. 

Many of the existing user interface elements have natural equivalents in Avalonia (textboxes, tree views etc).  However, some of the controls are specific to Reko and I would have to port them to make it all work. I've been programming with Windows Forms since the early Paleolithic and I'm very familiar with the Windows USER.EXE underpinnings, having programmed Windows applications since 1990. Regrettably, I'm unfamiliar with the details of WPF and Avalonia, so my questions may appear naive, but I'm eager to learn.

In no particular order:

* There are two controls that display graphical data. They want to render on a pixel 
  level. Today they are implemented as a back end that renders to a memory Bitmap object,
  which is then blitted to the screen on Paint events and recalculated when the
  control is resized or changes appearance in some other way.

  How could an Avalonia custom control be developed that has this pixel-orientation? 
  Would I have to do this for the N platforms that Avalonia supports or is there a 
  cross-platform rendering API I could render to? 

* I vaguely recall that Avalonia doesn't use pixel coordinates but some other 
  logical unit for measurement. How is pixel-to-logical and logical-to-pixel translation
  accomplished in code?

* The bottom field uses the Virtual List capability of Windows Forms. The search
  results can be very long (10000's of items or more) so I don't want to create widgets
  for items that woudn't be visible on screen. Instead, the widget stores a list
  of items, and only when it needs to render item #N does it ask the client program
  (using a callback mechanism) for the details of that particular item How would this be accomplished
  with Avalonia?

* I'm abusing a tab control here to simulate Visual Studio's tabbed document 
  windows. It looks awful but I didn't want to write my own custom control for this.
  Are there any Avalonia controls that implement this look?

* Also aiming to imitate the look of Visual Studio, the tool widgets are "docked"
  around the document area. The "docking" is accomplished by the judicious use
  of splitter windows, but is a hack. Are you aware of any docker controls for 
  Avalonia one could use here?

I'm excited about the prospect of using Avalonia to modernize Reko's look and
feel and bring it to other platforms than Windows. Any answers or pointers to 
documentation would be greatly appreciated. I also lurk in the Avalonia gitter.im 
room, so perhaps I could trouble you on that channel as well.

**Comment by liquidboy** [comment]
have you seen AvalonStudio's use of Avalonia? They have some common patterns that may be useful for you https://github.com/VitalElement/AvalonStudio
