### ISSUE TITLE
Centered Textblock Text is not visible when inside a vertically centered Border in Fullscreen

### ISSUE THREAD

**Issue by zaha** [AvaloniaUI/Avalonia#16117]
### Describe the bug

The text in my Textblock is not visible when I run my application in Fullscreen.
![AvaloniaTextblockBug Desktop_xVb7Engf4P](https://github.com/AvaloniaUI/Avalonia/assets/1721211/f583b306-6df7-4efe-a536-7bcf5f2918f5)
As you can see you don't see anything 😬 

I tried many things and narrowed the issue down. The text becomes visible again when one of the following is changed:

- The main window is not in fullscreen'
![AvaloniaTextblockBug Desktop_UAnGYVJ98E](https://github.com/AvaloniaUI/Avalonia/assets/1721211/80830829-1fdb-4d6a-80df-fe1266313ad4)
- The border is not centered vertically
![image](https://github.com/AvaloniaUI/Avalonia/assets/1721211/4b8f76de-eb71-4d1a-a717-7c460d405bd0)
- The Textblock text alignment is not centered
![image](https://github.com/AvaloniaUI/Avalonia/assets/1721211/aee03320-61af-4727-a675-3f23e337de70)

### To Reproduce

Minimal reproducible example: [AvaloniaTextblockBug.zip](https://github.com/user-attachments/files/15967918/AvaloniaTextblockBug.zip)

1. Set **AvaloniaTextblockBug.Desktop** as Startup project
2. Start debugging.

No text is visible. To make the text appear, either do one of the following:
- In `MainWindow.xaml` remove `WindowState="FullScreen"`.
- In `MainView.xaml` remove `VerticalAlignment="Center"` from the `Border`
- In `MainView.xaml` remove `TextAlignment="Center"` from the `TextBlock`

Then run the project again.

### Expected behavior

The text should be visible in fullscreen.

### Avalonia version

11.0.11

### OS

Windows

### Additional context

.NET 8.0
Desktop Application

**Comment by Gillibald** [comment]
This should be fixed with the latest master
