### ISSUE TITLE
Multiple gesture interaction

### ISSUE THREAD

**Issue by latnec** [AvaloniaUI/Avalonia#16162]
### Describe the bug

This is very similar to the issue described here: https://github.com/AvaloniaUI/Avalonia/issues/3133.

In particular:

The gestures recognizers collection contains two gesture recognizers

one is looking for single finger touch gestures
the second is looking for two finger touch gestures
Both recognizers will receive a PointerPressed event when the first finger touch occurs, both store the pointer information (touch ID etc).
The finger is moved triggering PointerMoved events for both recognizers.
The first recognizer now decides this is a single finger gesture and captures the input via IGestureRecognizerActionsDispatcher.
From this time forwards only the first recognizer receives pointer (touch) events for the touch ID.

The finger is removed and the first recognizer gets a PointerReleased event.
The second recognizer never gets a notification to discard the touch ID.

Now another single finger down occurs and both recognizers receive a PointerPressed event with a new touch ID.
The second gesture recognizer now thinks there is a two finger touch in progress.
The first recognizer thinks there is a single touch in progress.

### To Reproduce

Create a control and enable 2 gestures:

`UserControl.GestureRecognizers>
		<PinchGestureRecognizer/>
		<ScrollGestureRecognizer CanHorizontallyScroll="True"
                              CanVerticallyScroll="True"/>
	</UserControl.GestureRecognizers>`

### Expected behavior

After releasing the initial tap (to scroll) the next single tap should still be handled by scroll. Instead it is recognized as a second concurrent tap and handled by zoom instead

### Avalonia version

11.0.11

### OS

WebAssembly

**Comment by emmauss** [comment]
Is this a custom gesture recognizer? I do not recognize `IGestureRecognizerActionsDispatcher`, nor is there any code related to it. Please confirm the behavior occurs on the latest 11.x releases, and the actual reproduction steps.

**Comment by latnec** [comment]
Thank you for the reply @emmauss . I am not using `IGestureRecognizer`. I think that was the way things were done back in 2019.  Since then there were some major refactoring. For example, I found this https://github.com/AvaloniaUI/Avalonia/issues/11522

To answer your questions:

1. It is confirmed in 11.0.11. WebAssemply. Tested with an android and ios.
2. Create a new Avalonia project for Web. Enable 2 gestures for any user control (a rectangle is sufficient)
```
<UserControl.GestureRecognizers> 
  <PinchGestureRecognizer/> 
  <ScrollGestureRecognizer CanHorizontallyScroll="True" CanVerticallyScroll="True"/> 
</UserControl.GestureRecognizers>
```
3. When testing, the behavior described in the first report occurs: 

When the first touch even occurs, `ScrollGestureRecognizer` receives a `ScrollGestureEvent`  (as it should)
After we release, `ScrollGestureRecognizer` receives a `ScrollGestureEndedEvent`. However, it seems `PinchGestureRecognizer` does NOT receive any release events. Hence on the next touch event (single finger) `PinchGestureRecognizer` receives a `PinchEvent` and it should not. It means we are effectively doing a "pinch" with one finger.

Another note: enabling only `Pinch` or `Scroll` at a time everything works as expected. Independent behaviors are ok. The problem occurs when both are present

**Comment by emmauss** [comment]
> Thank you for the reply @emmauss . I am not using `IGestureRecognizer`. I think that was the way things were done back in 2019. Since then there were some major refactoring. For example, I found this #11522
> 
> To answer your questions:
> 
>     1. It is confirmed in 11.0.11. WebAssemply. Tested with an android and ios.
> 
>     2. Create a new Avalonia project for Web. Enable 2 gestures for any user control (a rectangle is sufficient)
> 
> 
> ```
> <UserControl.GestureRecognizers> 
>   <PinchGestureRecognizer/> 
>   <ScrollGestureRecognizer CanHorizontallyScroll="True" CanVerticallyScroll="True"/> 
> </UserControl.GestureRecognizers>
> ```
> 
>     3. When testing, the behavior described in the first report occurs:
> 
> 
> When the first touch even occurs, `ScrollGestureRecognizer` receives a `ScrollGestureEvent` (as it should) After we release, `ScrollGestureRecognizer` receives a `ScrollGestureEndedEvent`. However, it seems `PinchGestureRecognizer` does NOT receive any release events. Hence on the next touch event (single finger) `PinchGestureRecognizer` receives a `PinchEvent` and it should not. It means we are effectively doing a "pinch" with one finger.
> 
> Another note: enabling only `Pinch` or `Scroll` at a time everything works as expected. Independent behaviors are ok. The problem occurs when both are present

I've tried to reproduce this, using your exact method. Gestures work fine, even with multiple recognizers.
This is my test with 11.0.11
[AvaloniaApplication9.zip](https://github.com/user-attachments/files/16086334/AvaloniaApplication9.zip)

**Comment by latnec** [comment]
Thank you again @emmauss . You are correct, the sample project you sent works as expected. I've added more code to do manipulations for scroll and pinch and works as expected. 

The only difference I can see is that in the sample you sent the .net framework is 8.0 whereas in the project I was using it is targeting 7.0. 

I will switch my project to 8.0 and confirm the fix, but I wanted to let you know it is indeed working. 

This can be closed and marked as "user error". 

Thank you again for your help.
