### ISSUE TITLE
InputPane reports incorrect keyboard height

### ISSUE THREAD

**Issue by kerams** [AvaloniaUI/Avalonia#16171]
### Describe the bug

On keyboard open, `InputPane.StateChanged` occasionally reports `EndRect` with height of 0, sometimes even double the actual size. I am able to reliably reproduce this with orientation switching, but it is not a necessary condition - I've seen this happen immediately after startup too.

### To Reproduce

1. https://github.com/kerams/input, launch in Android emulator in Debug
2. Change orientation to horizontal, wait a couple of seconds
3. Change orientation back to vertical
4. Click on the textbox
5. Notice no padding is added and the textbox is hidden
6. Close the keyboard and then reopen it by clicking on the textbox again
7. Notice padding is added to the bottom of the view
---
1. https://github.com/kerams/input, launch in Android emulator in Debug
2. Change orientation to horizontal
3. Click on the texbox
4. Notice no padding is added and the textbox is hidden
5. Close the keyboard
6. Change orientation back to vertical
7.  Click on the textbox
8. Notice padding is twice as high as the keyboard

https://github.com/AvaloniaUI/Avalonia/assets/5063478/e5434a4e-4189-4fd5-921a-d6416e0cd9a6

### Expected behavior

When the soft keyboard is opened `EndRect.Height` in the `StateChanged` event should be exactly equal to the height of the keyboard. When it's closed, height should be 0.

### Avalonia version

11.2.999-cibuild0049152-alpha

### OS

Android

**Comment by emmauss** [comment]
I've been able to reproduce this issue, and it only occurs on Android 11 API 30. It seems that the first inset update has incorrect bounds. So far, it hasn't been fixed on Android 30. 
Similar reports on the net;
https://stackoverflow.com/questions/67521051/windowinsetlistener-doubles-offset-in-android-r-api-30
https://github.com/flutter/flutter/issues/65821
I'm working on a fix for just api 30, by disabling animations and only reporting state change when the system animation ends.
