### ISSUE TITLE
Items appear constricted or squeezed within itself when in itemsRepeater using UniformGridLayout

### ISSUE THREAD

**Issue by Eugenenoble2005** [AvaloniaUI/Avalonia#16172]
### Describe the bug

I have setup a minimal reproduction of this using the latest version of avalonia here:
https://github.com/Eugenenoble2005/UniformGridLayoutBugRepo

When using the ItemsRepeater control and setting it's layout to UniformGridLayout, the contents will appear squeezed hiding much of it when the content is a number. No amount of internal padding set on the control fixes it , it's as if no content is rendered after the first digit. This only happens when UniformGridLayout is used. StackLayout, WrapLayout and DockLayout afaik do not cause this bug. Experienced this bug on Windows and Linux(arch and ubuntu). 

Images:
Bug when using UniformGridLayout
![Screenshot_29-Jun_16-55-27_20735](https://github.com/AvaloniaUI/Avalonia/assets/71329328/4e650e7d-2f0c-4893-bb79-012803f3ca2f)

No bug(expected output) when using WrapLayout:
![Screenshot_29-Jun_16-57-51_2285](https://github.com/AvaloniaUI/Avalonia/assets/71329328/e24d968b-25d7-4e2b-b6c9-da1bf4ccd52b)

### To Reproduce

See cited reproduction: 
https://github.com/Eugenenoble2005/UniformGridLayoutBugRepo

For example an itemsRepeater that prints 1 to 100 in buttons. The bug seems to only happen when numerical digits are being printed. Strings are fine and do not cause the bug, But strings that contain a number in them e.g "This is a long string 44" will cause the bug and the end of the sentence will be cut out. I have also tried converting the number to a string before binding them like so : number.toString(), the bug still occurs.

### Avalonia version

11.1.0

### OS

Windows, Linux

**Comment by stevemonaco** [comment]
It's not squeezed, it's uniform. IIRC, the first item is measured and that is what is used for the layout. You can set `MinItemWidth` otherwise. Remember that these controls are designed to support many thousands of child controls (or more) so measuring each one individually to find a maximum is expensive.

**Comment by Eugenenoble2005** [comment]
@stevemonaco works great now. Thank you.
