### ISSUE TITLE
Button should check `RoutedEventArgs.Source` before handling keys

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#16184]
### Describe the bug

Reported in https://github.com/amwx/FluentAvalonia/issues/591. 

Placing a text control into an Expander header does not allow spaces. The cause is the `Button` that is found in the Expander's header (which is part of the template for my SettingsExpander control in the referenced issue) is consuming this event and the TextBox never sees it.

I looked at WPF source, they do a check in `ButtonBase` to see if the event source is the button and only handle it in that case - Avalonia should do the same check.

https://github.com/dotnet/wpf/blob/0628a7722ccdc47ebe66beb5eb8cee756d05f7d9/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/ButtonBase.cs#L612-L647

### To Reproduce

Add a TextBox to an Expander and try to type text with spaces. Only the text will be entered, the space key will open/close the expander.

### Avalonia version

11.1-rc1

### OS

Windows

**Comment by robloo** [comment]
@workgroupengineering Would SplitButton be affected by this issue as well? It handles space in a similar way.

**Comment by workgroupengineering** [comment]
> Would SplitButton be affected by this issue as well? It handles space in a similar way.

I haven't checked, if it handles in a similar way probably is affected from same issue. As soon as I have a moment I'll do some tests.
