### ISSUE TITLE
AVLN:0004	Data at the root level is invalid  - due to adding a gguf file as asset

### ISSUE THREAD

**Issue by markat1** [AvaloniaUI/Avalonia#16223]
### Describe the bug

I'm getting a AVLN:0004	Data at the root level is invalid , when I tried adding a gguf to the  csproj 

 ```
 <ItemGroup>
    <AvaloniaResource Include="Assets\avalonia-logo.ico" />
    <AvaloniaResource Include="Assets\qween.gguf" />

  </ItemGroup>

```

Here's the Asset folder:

![image](https://github.com/AvaloniaUI/Avalonia/assets/8057282/cb94ef2d-66b5-405b-86f4-321ab2c080ea)

here's the complete error:

Severity	Code	Description	Project	File	Line	

`Severity	Code	Description	Project	File	Line	Suppression State Error (active)	AVLN:0004at the root level is invalid. Line 1, position 1.	AvalTest.AvaloniaProject	C:\Users\test\source\repos\AvalTest.AvaloniaProject\AvalTest.AvaloniaProject\App.axaml	1	
`

![image](https://github.com/AvaloniaUI/Avalonia/assets/8057282/c6b30d0e-d8fe-4b26-942c-5d3e828bbe15)

### To Reproduce

1. Create a new avalonia project
2. add a gguf file to the Asset folder.  (gguf is 4 GB in size)
3. include following code in the csproj

```
  <ItemGroup>
    <AvaloniaResource Include="Assets\avalonia-logo.ico" />
    <AvaloniaResource Include="Assets\qween.gguf" />
  </ItemGroup>

```

or just leave standard setup like this and run a build.

```
 <ItemGroup>
   <AvaloniaResource Include="Assets\**" />
 </ItemGroup>

```

### Expected behavior

Expected behaivor is that it can run the application without creating any errors like AVLN:0004

### Avalonia version

11.0.11

### OS

Windows 11 

### Additional context

Avolonia desktop application

**Comment by maxkatz6** [comment]
We probably should add a max size limit for avalonia resources and output a better error instead.

> add a gguf file to the Asset folder. (gguf is 4 GB in size)

Are you sure you want to embed 4 GB file into an executable? That's what avalonia resources are.
You still can use it as a `<Content  />` entry copied to the output folder, and use FileIO apis to read it.

**Comment by markat1** [comment]
Hello @maxkatz6 - thank you so much for your fast reply!

Hmm as long as I can read the file via  FileIO, then that's the way to go.

But should I copy gguf into  bin/debug and bin/release via csproj?

**Comment by timunie** [comment]
What is that even this gguf-file and why is it as big as an entire DVD film?

**Comment by timunie** [comment]
Ah okay, so I'd rather provide such a file independent from the exenin order to allow an easier update of it if needed. Anyways, don't ship as an asset due to file size and startup performance. Use disc IO for fhe acccess to it.

**Comment by markat1** [comment]
thank you for your reply @timunie 

okay, so I should copy gguf-file directly over to bin/debug and bin/Release ?

**Comment by timunie** [comment]
You can ask dotnet to copy a file to output dir, see: https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2022#compile
