### ISSUE TITLE
Force decimal separator in browsers

### ISSUE THREAD

**Issue by ZecosMAX** [AvaloniaUI/Avalonia#16236]
### Is your feature request related to a problem? Please describe.

I had a problem with a custom converter, which takes a double as it's argument. Like '2.3' 

Because my system settings uses a dot (.) as a decimal separator, i haven't ever experienced any problems with that
Until now, for some reason my converter worked in previewer and in desktop builds:
![Screenshot1](https://github.com/AvaloniaUI/Avalonia/assets/20259054/783df53f-5003-484c-9af6-8732a627866b)

However it didn't work in any of my browsers (Firefox dev 128.0b9; Google Chrome 126.0.6478.127; MS Edge 126.0.2592.87)
Until i specifically installed in my Firefox browser an en-GB locale as suggested in this ticket on Mozilla support: (https://support.mozilla.org/en-US/questions/1172233)
![изображение](https://github.com/AvaloniaUI/Avalonia/assets/20259054/3321466b-aa83-4336-a9ed-9f9929b6331c)

### Describe the solution you'd like

Maybe somehow force these types of settings to match the globalization settings of UI thread?
(I can't confirm if this is a C# side problem or a Browser side problem because debugging isn't working. Maybe i'll try to force globalization settings for UI Thread later)

Or give a warning that this can happen and avoid parsing doubles altogether.

### Describe alternatives you've considered

As for now, changing locale of browser to one that uses decimal separator as yours are works as a fix, but it's not consumer friendly...

**Comment by stevemonaco** [comment]
I suspect your `MathConverter` implementation is not using an `InvariantCulture` as that `ConverterParameter` should be string data as far as Avalonia is concerned.

**Comment by timunie** [comment]
Can you please file a minimum sample or ar least the converter impl? I guess you just need to consume the correct culture. CultureInfo class has some info about current culture btw.

**Comment by ZecosMAX** [comment]
@stevemonaco @timunie finally got time to check for culture.
Consuming `culture` from converter argument didn't help, but setting `InvariantCulture` to double.Parse did

```CSharp
public class MathConverter : IValueConverter
{
    object? IValueConverter.Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        if (value == null)
            return value;

        if (parameter == null)
            return value;

        if (value is double v && parameter is string p && targetType.IsAssignableTo(typeof(double)))
        {
            var args = p.Split(' ', StringSplitOptions.RemoveEmptyEntries);

            if (args.Length % 2 != 0)
                throw new ArgumentException("ConverterParameter should contain '{operation} {value}'");

            for (var i = 0; i < args.Length; i += 2)
            {
                double opv = double.Parse(args[i + 1], CultureInfo.InvariantCulture); // <- Added InvariantCulture here
                v = args[i + 0] switch
                {
                    "div" => v / opv,
                    "mul" => v * opv,
                    "add" => v + opv,
                    "sub" => v - opv,
                    _ => v,
                };
            }

            return v;
        }
        else
        {
            return value;
        }
    }

    object IValueConverter.ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        throw new NotSupportedException();
    }
}
```

So, now it works with all browsers that i've tested previously. 
Probably can close this issue now

**Comment by maxkatz6** [comment]
Culture passed in the converter is a UI culture by default, retried from the .NET BCL. Unless it was redefined in the Binding - which is the way how you can force it.

But yes, if you want it to be always invariant in the converter - just use CultureInfo.InvariantCulture
