### ISSUE TITLE
Context menu keyboard shortcut ignored until menu is visible at least once (Windows)

### ISSUE THREAD

**Issue by TangDave** [AvaloniaUI/Avalonia#16314]
### Describe the bug

Context menu keyboard shortcuts do not work until the menu has been visible once.

### To Reproduce

Create a TextBox with a ContextMenu with just one item - give that item a shortcut 'Ctrl-M'. Add a handler to do something like show a message (I know that Avalonia doesn't have this simplest of features, but you get the idea - create your own messagebox like the rest of us).
At runtime:
1. Press 'Ctrl-M' - nothing happens
2. Bring up the context menu via right-click and then close the context menu
3. Press 'Ctrl-M' - the message appears

Obviously, you shouldn't have to show a context menu once to activate a keyboard shortcut - otherwise what's the point of a keyboard shortcut?

### Avalonia version

11.0.11

### OS

Windows

**Comment by timunie** [comment]
That's a known current limitation. Use KeyBindings instead.

**Comment by timunie** [comment]
#2441
