### ISSUE TITLE
ILauncher is not working in browser

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#16317]
### Describe the bug

ILauncher is not working properly on wasm project. 

### To Reproduce

Run ControlCatalog.Browser, click on the Buttons/HyperlinkButton demo

### Expected behavior

It should open a new window

### Avalonia version

latest master

### OS

WebAssembly

### Additional context

No error info in brower console.

**Comment by maxkatz6** [comment]
It was fixed recently. To be shipped with 11.1.1 https://github.com/AvaloniaUI/Avalonia/pull/16271
