### ISSUE TITLE
GetRealizedTreeContainers doesn't return all the TreeViewItem

### ISSUE THREAD

**Issue by Chenyichen12** [AvaloniaUI/Avalonia#16329]
### Describe the bug

I try to get the TreeViewItem in code behind by using GetRealizedTreeContainers. But it return a list which just contain the shallowest level TreeViewItem. I looked at the source code and find it should return all the TreeViewItem in the TreeView.

### To Reproduce

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:AvaloniaApplication1.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.Views.MainWindow"
        x:DataType="vm:MainWindowViewModel"
        Icon="/Assets/avalonia-logo.ico"
        Title="AvaloniaApplication1">

    <Design.DataContext>
        <!-- This only sets the DataContext for the previewer in an IDE,
             to set the actual DataContext for runtime, set the DataContext property in code (look at App.axaml.cs) -->
        <vm:MainWindowViewModel/>
    </Design.DataContext>
    <TreeView Name="Tree">
        <TreeViewItem Header="Item 1">
            <TreeViewItem Header="Item 1.1"/>
            <TreeViewItem Header="Item 1.2"/>
        </TreeViewItem>
        <TreeViewItem Header="Item 2">
            <TreeViewItem Header="Item 2.1"/>
            <TreeViewItem Header="Item 2.2"/>
        </TreeViewItem>
    </TreeView>

</Window>
```
code behind
```cs
using System;
using Avalonia.Controls;
using Avalonia.ReactiveUI;
using AvaloniaApplication1.ViewModels;
using ReactiveUI;

namespace AvaloniaApplication1.Views;

public partial class MainWindow : ReactiveWindow<MainWindowViewModel>
{
    public MainWindow()
    {
        this.WhenActivated((_)=>{
            var t = Tree.GetRealizedTreeContainers();
            var count = 0;
            foreach(var S in t){
                count++;
            }
            Console.WriteLine(count); // it should be 6 but write 2
        });
        InitializeComponent();
    }
}
```

### Avalonia version

11.0.11

### OS

Windows

### Additional context

I try to debug and find some information
The source code in TreeView
```cs
public IEnumerable<Control> GetRealizedTreeContainers()
    {
        return GetRealizedContainers(this);
        static IEnumerable<Control> GetRealizedContainers(ItemsControl itemsControl)
        {
/* I think it go wrong at this line. I have debug and saw that the TreeViewItem which has Children retrun a null List by using GetRealizedContainer */
            foreach (Control container in itemsControl.GetRealizedContainers())
            {
                yield return container;
                if (container is ItemsControl itemsControl2)
                {
                    foreach (Control realizedContainer in GetRealizedContainers(itemsControl2)) 
                    {
                        yield return realizedContainer;
                    }
                }
            }
        }
    }
```

**Comment by maxkatz6** [comment]
> // it should be 6 but write 2

Why should it return 6? What if these containers were not yet realized?
Keep in mind, items control won't create more containers that it really needs to display at once.

**Comment by Chenyichen12** [comment]
![AvaloniaApplication1_or3kjW5nBC](https://github.com/user-attachments/assets/b85f3ddc-ef70-4f33-84ce-c7f707b525ee)

But Intuitively, I do create 6 item. 
If it is not a bug, How can I get all the TreeViewItem in the view

**Comment by Chenyichen12** [comment]
> > // it should be 6 but write 2
> 
> Why should it return 6? What if these containers were not yet realized? Keep in mind, items control won't create more containers that it really needs to display at once.
![AvaloniaApplication1_or3kjW5nBC](https://github.com/user-attachments/assets/6db047bd-80a2-4829-93c5-6e1104300349)

But Intuitively, I do create 6 item.
If it is not a bug, How can I get all the TreeViewItem in the view

**Comment by Chenyichen12** [comment]
Oh It's my fault. It just return the items which is visible. When I expand the group item, It correctly return 6. haha
Does TreeViewItem just alive when it is visible? If not, can I using other way to get it?

> Keep in mind, items control won't create more containers that it really needs to display at once.

**Comment by maxkatz6** [comment]
> Does TreeViewItem just alive when it is visible? 

Yes. When it's not visible, there is no TreeViewItem.
You likely need to solve your task in a different way.

**Comment by Chenyichen12** [comment]
> > Does TreeViewItem just alive when it is visible?
> 
> Yes. When it's not visible, there is no TreeViewItem. You likely need to solve your task in a different way.

Ok, Thanks for your reply
