### ISSUE TITLE
Hi guys , i want to port my existing application in dotnet core. I am having a winforms.wpf in front end .Can we use angularjs 5  as  a replacement for winforms/wpf in dotnet core?

### ISSUE THREAD

**Issue by sanjayicy** [AvaloniaUI/Avalonia#1632]

**Comment by danwalmsley** [comment]
Welcome, I'm not sure why you would want to use angularjs with Avalonia? However Avalonia is basically a cross platform. Wpf so it's not required. You can use mvvm frameworks like reactive ui which comes with Avalonia.

**Comment by Gillibald** [comment]
This can probably closed. Seems not be related to Avalonia.
