### ISSUE TITLE
Missing methods for DrawingContext

### ISSUE THREAD

**Issue by Shadowblitz16** [AvaloniaUI/Avalonia#16349]
### Describe the bug

The following are missing from DrawingContext

- FillGeometry
- FillEllipse
- FillLine
- FillText
- DrawPixel
- FetchPixels

### To Reproduce

```cs
public class Surface : RenderTargetBitmap
{
    
    public Surface(uint width, uint height) : base(new((int)width, (int)height), Vector.One)
    {
        var target = CreateDrawingContext()
            target.
    }
}
```

### Expected behavior

FillLine is a bit obscure due to lines usually not having outlines but the others would be really nice to have.

### Avalonia version

11.0.10

### OS

Linux

**Comment by maxkatz6** [comment]
1. FillGeometry, FillEllipse - existing DrawGeometry method accepts both Pen and Brush parameters for outline and filling accordingly. This is not missing.
2. FillLine - use DrawLine.
3. FillText - build FormattedText and call BuildHighlightGeometry on it. Now you have a highlight/outline geometry than can be outlined independently. This is not missing.
4. DrawPixel and FetchPixels - drawing context doesn't operate with pixels. It's a set of commands that will be send to the GPU. You can draw a rectangle with width calculated depending on the RenderScaling though.

**Comment by Shadowblitz16** [comment]
thankyou for clarifyng
