### ISSUE TITLE
Difference with platform.uno

### ISSUE THREAD

**Issue by zeroonestring** [AvaloniaUI/Avalonia#1636]
Difference with platform.uno

**Comment by bricelam** [comment]
See also #587

**Comment by robloo** [comment]
Here is a link to a high-level comparison if anyone is curious in the future.

https://github.com/robloo/PublicDocs/blob/master/XAMLFrameworkComparison.md

**Comment by lindexi** [comment]
> Here is a link to a high-level comparison if anyone is curious in the future.
> 
> https://github.com/robloo/PublicDocs/blob/master/XAMLFrameworkComparison.md

@robloo Are you interested in updating your blog?

**Comment by robloo** [comment]
@lindexi What needs to be updated?
