### ISSUE TITLE
Lock screen password and biometric identification API

### ISSUE THREAD

**Issue by tsctsc6** [AvaloniaUI/Avalonia#16385]
### Is your feature request related to a problem? Please describe.

Certain operations in certain apps require authentication of the user's identity, through the operating system's lock screen password, fingerprints, face, etc.

### Describe the solution you'd like

In viewmodel, call a async function, and GUI show a new view, tell user to validate(PIN or something else).
```
bool result = await SystemAuthentication();
```

**Comment by emmauss** [comment]
This doesn't look like a feature Avalonia shoould have, or any ui toolkit.

**Comment by tsctsc6** [comment]
All right.
