### ISSUE TITLE
Avalonia error AVLN:9999: Member 'System.Nullable`1' is declared in another module and needs to be imported.

### ISSUE THREAD

**Issue by schauerte** [AvaloniaUI/Avalonia#16397]
### Describe the bug

After moving a large number of views from one project to another (within the same solution) and adjusting namespaces, the build fails with:
> Avalonia error AVLN:9999: Member 'System.Nullable`1' is declared in another module and needs to be imported [/path/My.Project.csproj]

But there is no obvious error in the change set.

### To Reproduce

Build error was observed on different computers, but there is no way to create a minimal project to reproduce.

### Expected behavior

1. `dotnet build` should just work without error.
2. If there is a problem, the error message should contain more details (to identify the source).

### Avalonia version

11.0.11

### OS

Windows, Linux

### Additional context

The same code compiles fine, when using 11.1.0-rc2 instead of 11.0.11 so it might be fixed with the next version, but I assume there might be other workarounds (like disabling a compiled binding) which can't be found, if the problem arises in a big change set but with no location information.

Note: System.Nullable was not used in the moved views (or the whole target project) directly.

**Comment by maxkatz6** [comment]
Sorry, can't really help here without having a repro.
We do have various improvements in type handling in 11.1 release, so you can test it. 
But nothing of these changes is planned to be backported to 11.0.

**Comment by schauerte** [comment]
Of course. I mainly was asking for improving the error message to contain more context (and I assume this might help in other cases as well - especially for AVLN9999).

**Comment by timunie** [comment]
If 11.1.0 is fine, imo the issue can be closed.

**Comment by schauerte** [comment]
Agreed.
