### ISSUE TITLE
Analyzer error when binding to `RadioButton.IsChecked` property in Avalonia 11.1.0-rc2 compared to 11.0.11

### ISSUE THREAD

**Issue by mysticpillow** [AvaloniaUI/Avalonia#16394]
### Describe the bug

While binding to the `RadioButton.IsChecked` property in XAML, Rider's analyzer mistakenly assumes that I intend to bind to the private `IRadioButton.IsChecked` property. This assumption results in an analyzer error in XAML, although the binding functions correctly at runtime. Additionally, there is no IntelliSense hint for `IsChecked` when typing it out in XAML.

### To Reproduce

            <StackPanel>
                <RadioButton Name="radioButton" />
                <RadioButton />
                <NumericUpDown IsEnabled="{Binding #radioButton.IsChecked}" /> 
            </StackPanel>

### Expected behavior

The analyzer should recognize that the binding is intended for the public `ToggleButton.IsChecked` property. Maybe there is a way to cast `#radioButton` to `ToggleButton` within the binding expression as a workaround?

### Avalonia version

11.1.0-rc2

### OS

Windows

### Additional context

![image](https://github.com/user-attachments/assets/191beecd-b66a-4d96-ad05-f4f238ba0275)

**Comment by maxkatz6** [comment]
This is a Rider bug. 
RadioButton.IsChecked property is inherited from ToggleButton.IsChecked which is still public.
But Rider mistakenly reads internal explicit interface implementation of another property with the same name: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/RadioButton.cs#L36

Can you open an issue in the Rider Youtrack? I will add it to the list of other issue https://github.com/AvaloniaUI/Avalonia/issues/10356 to track

**Comment by mysticpillow** [comment]
Sure, as soon as YouTrack is out of read-only mode.

**Comment by mysticpillow** [comment]
https://youtrack.jetbrains.com/issue/RIDER-115130/Rider-analyzer-error-when-binding-to-RadioButton.IsChecked-property-in-Avalonia-11.1.0
