### ISSUE TITLE
PathMarkupParser doesn't support implicit lineto commands following a moveto command

### ISSUE THREAD

**Issue by miguelrochefort** [AvaloniaUI/Avalonia#1640]
This works:

```xml
<Path Data="M0,0L10,10" />
```

This doesn't work:

```xml
<Path Data="M0,0 10,10" />
```

According to the [SVG specification](https://www.w3.org/TR/SVG/paths.html#PathDataMovetoCommands):
> - If a moveto is followed by multiple pairs of coordinates, the subsequent pairs are treated as implicit lineto commands

**Comment by jmacato** [comment]
You already posted the same issue https://github.com/AvaloniaUI/Avalonia/issues/1606; please close either issues for brevity.

**Comment by jmacato** [comment]
Can you combine this with https://github.com/AvaloniaUI/Avalonia/issues/1606 ? If you have any `Path` related queries, make them in a single ticket :)

**Comment by miguelrochefort** [comment]
This is a different issue, but I can merge them together if you prefer.

**Comment by jmacato** [comment]
Yeah sorry 'bout that, they looked the same at a glance ;)

**Comment by miguelrochefort** [comment]
#1606 snippets exhibit both issues. I can edit them to make the difference more obvious.

**Comment by jmacato** [comment]
Alright, please edit them as you see fit 😄

**Comment by jmacato** [comment]
@miguelrochefort Thanks! and sorry again that i misunderstood the issues you filed

**Comment by Gillibald** [comment]
I am currently working on a rewrite of the PathMarkupParser to improve error handling and make the component testable.  Can you tell me what exactly isn't working? Is the implicit move command executed?

**Comment by miguelrochefort** [comment]
The two snippets above should be equivalent.

Given:
```xml
<Path Data="M0,0 10,10" />
```

Actual:
- moveto 0,0
- moveto 10,10

Expected:
- moveto 0,0
- lineto 10,10

**Comment by Gillibald** [comment]
Those two paths aren't equal.

M0 0 10 0 is translated to moveto(0, 0) moveto(0, 10)

If you wanted to have moveto(0, 0) lineto(10, 0) you would have to write M0 0L10 0 or M0,0L10,0

**Comment by Gillibald** [comment]
I will adress this case in my rewrite of the PathMarkupParser
