### ISSUE TITLE
Erroneous debug output for binding error of TemplateBinding to boolean property when null.

### ISSUE THREAD

**Issue by boydpatterson** [AvaloniaUI/Avalonia#16409]
### Describe the bug

Starting with Avalonia 11.1.0, some control templates are generating error messages like the following:

```
[Binding]An error occurred binding 'IsVisible' to 'TemplateBinding: IsIconVisible': 'Could not convert '(null)' (null) to 'System.Boolean'.' (ContentPresenter #PART_IconPresenter)
```

The binding referenced by the control template is defined as:

```xaml
<ContentPresenter ... IsVisible="{TemplateBinding IsIconVisible}" />
```

Once loaded, the binding works as expected, but the error output is misleading to customers.

### To Reproduce

I was unable to reproduce in a simple sample application with a custom control, but it is easy to reproduce referencing the publicly available Actipro InfoBar control.

Step 1: 
Use Visual Studio on Windows to load a sample Avalonia desktop application.

Step 2:
Add a NuGet reference to `ActiproSoftware.Controls.Avalonia.Pro` v24.1.0
```xml
<PackageReference Include="ActiproSoftware.Controls.Avalonia.Pro" Version="24.1.0" />
```

Step 3:
Update `App.axaml` to include Actipro themes like in the following:
```xaml
<Application xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    x:Class="AvaloniaApplication.App"
    xmlns:actipro="http://schemas.actiprosoftware.com/avaloniaui">

    <Application.Styles>
        <actipro:ModernTheme Includes="Pro" />
        <FluentTheme />
    </Application.Styles>
</Application>
```

Step 4:
Add an Actipro InfoBar control to any view like the following:

```xaml
xmlns:actipro="http://schemas.actiprosoftware.com/avaloniaui"
...
<actipro:InfoBar Title="Title" Message="An essential application message for the user." />
```

Step 5:
Run the application with Avalonia 11.1.0.  If necessary, navigate to the view with the InfoBar control.  When the "Actipro Controls" popup is displayed, click the **Evaluate** button to continue.  Once InfoBar is displayed, the Visual Studio Output tool window should display a message like the following:

```
[Binding]An error occurred binding 'IsVisible' to 'TemplateBinding: IsIconVisible': 'Could not convert '(null)' (null) to 'System.Boolean'.' (ContentPresenter #PART_IconPresenter)
```

Step 6:
Optionally run the application with Avalonia 11.0.11 and the same error message is not observed.

### Expected behavior

No error message should be displayed for any TemplateBinding before the template is ready.

### Avalonia version

11.1.0

### OS

Windows

**Comment by grokys** [comment]
Hi @boydpatterson ,

Thanks for reporting this, but I'm not sure that this warning is erroneous. From what I can see, the binding is from `InfoBar.IsIconVisible` to `ContentPresenter.IsVisible`. `InfoBar.IsIconVisible` is a `bool?` whereas `ContentPresenter.IsVisible` is a `bool`.

At the time that the template binding starts up, the `InfoBar.IsIconVisible` property is null:

![image](https://github.com/user-attachments/assets/709c74af-1613-46bd-9f05-2f6a4b791333)

And so the warning is logged. I don't have access to the source for `InfoBar`, so I'm not sure what conditions cause `IsIconVisible` to be non-null, but at this point the `InfoBar` is attached to a logical and visual tree. You say "No error message should be displayed for any TemplateBinding before the template is ready" but I'm not sure what you mean here - in this case, what part of applying the template will cause `IsIconVisible` to become non-null?

As for why this wasn't logging a warning in 11.0.x - we didn't log binding errors for template bindings in that version.

**Comment by boydpatterson** [comment]
Hi @grokys. You're absolutely right, and my apologies for missing that. Recovering from COVID this week, so I'll blame it on the brain fog 😶‍🌫️

We define that property as `Nullable<bool>` so that we can coerce some default behavior about only showing the icon when there's content to be shown, so the issue appears to be that the property has not been coerced yet.  We typically wait to coerce all properties in `OnApplyTemplate`, but the warning message is being generated before the template is applied.  It basically never should be `null`, so that's primarily why I forgot about it.  If we also coerce properties in the constructor, that prevents the binding message from being displayed.  It's redundant, but not a big deal to prevent the warning.

Thank you for looking, and sorry, again, for taking your time on this.
