### ISSUE TITLE
Dev Tools causes Avalonia to crash when Application targets netcoreapp2.1

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1641]
To repro simply change control catalog to target netcoreapp2.1, run it press f12.

**Comment by jkoritzinsky** [comment]
Looks like it's a crash somewhere in unmanaged code...

**Comment by jkoritzinsky** [comment]
Only crashes when the debugger is attached for non-native code. Otherwise stuff just fails to correctly draw on the devtools window until you force a re-render.

**Comment by jkoritzinsky** [comment]
Maybe it's heap corruption?

**Comment by danwalmsley** [comment]
They have changed stuff in the debugger for sure, when I ran the debugger on AS with 2.1 I got lots of com. Errors saying interface missing, mainly unmanaged ones.

**Comment by grokys** [comment]
Just tested this on latest master and still hapening.

**Comment by jp2masa** [comment]
This was discussed on gitter I think, the solution is to use CTRL + F12.

**Comment by grokys** [comment]
Note that this doesn't seem to be a problem in `netcoreapp3.0`.

I'm going to add an overload of `DevToolsExtensions..AttachDevTools` which accepts a `KeyGesture` so that people using `netcoreapp2.1` can change the hotkey to `Ctrl+F12`.
