### ISSUE TITLE
Custom Localisation MarkupExtension broken by 11.1.0

### ISSUE THREAD

**Issue by IsaacMarovitz** [AvaloniaUI/Avalonia#16430]
### Describe the bug

In Ryujinx, we use a compiled binding-based markup extension to provide localised strings to text blocks. The implementation is as follows:

```csharp
internal class LocaleExtension : MarkupExtension
{
    public LocaleExtension(LocaleKeys key)
    {
        Key = key;
    }

    public LocaleKeys Key { get; }

    public override object ProvideValue(IServiceProvider serviceProvider)
    {
        LocaleKeys keyToUse = Key;

        var builder = new CompiledBindingPathBuilder();

        builder.SetRawSource(LocaleManager.Instance)
            .Property(new ClrPropertyInfo("Item",
            obj => (LocaleManager.Instance[keyToUse]),
            null,
            typeof(string)), (weakRef, iPropInfo) =>
            {
                return PropertyInfoAccessorFactory.CreateInpcPropertyAccessor(weakRef, iPropInfo);
            });

        var path = builder.Build();

        var binding = new CompiledBindingExtension(path);

        return binding.ProvideValue(serviceProvider);
    }
}
```

LocaleManager is a singleton that triggers `OnPropertyChanged` events when strings change due to switching language or dynamic values in the string changing.

As of Avalonia 11.1.0 this system no longer seems to properly update the displayed text when `OnPropertyChanged` is triggered, this results in dynamic values not being updated, and locale changes only taking effect when the view is destroyed and recreated.

### To Reproduce

Providing concrete steps for reproduction is a little difficult. However, a branch of Ryujinx displaying this issue is available here: https://github.com/Ryujinx/Ryujinx/pull/6733.

Locales failing to update can be observed on the bottom bar:
<img width="1440" alt="Screenshot 2024-07-23 at 16 28 40" src="https://github.com/user-attachments/assets/eb567962-aa6b-48f4-b4db-5ce490001f4d">

Or after changing locale:
<img width="440" alt="Screenshot 2024-07-23 at 16 28 54" src="https://github.com/user-attachments/assets/b2291d0b-6e98-4de1-aa51-0e048758a456">

### Expected behavior

This should continue to work as it did in prior versions of Avalonia, with change events properly updating the text displayed.

### Avalonia version

11.1.0

### OS

Windows, macOS, Linux

**Comment by MrJul** [comment]
I had a look at this, `RawSource` doesn't seem to do anything anymore.
Set the binding `Source` instead:

```diff
             var builder = new CompiledBindingPathBuilder();
 
-            builder.SetRawSource(LocaleManager.Instance)
+            builder
                 .Property(new ClrPropertyInfo("Item",
                 obj => (LocaleManager.Instance[keyToUse]),
                 null,
 
             var path = builder.Build();
 
-            var binding = new CompiledBindingExtension(path);
+            var binding = new CompiledBindingExtension(path)
+            {
+                Source = LocaleManager.Instance
+            };
 
             return binding.ProvideValue(serviceProvider);
         }
```

----

AFAICT, there's no way to have `RawSource` be generated from XAML code and it's now completely unused.
We should obsolete `SetRawSource()`.

**Comment by MrJul** [comment]
Since I had the change ready, I went ahead and submitted a PR: https://github.com/Ryujinx/Ryujinx/pull/7121

**Comment by IsaacMarovitz** [comment]
Thanks for the fix! Gonna keep this open tho as if `RawSource` doesn't do anything, it should probably be deprecated or removed.

**Comment by MrJul** [comment]
> Thanks for the fix! Gonna keep this open tho as if `RawSource` doesn't do anything, it should probably be deprecated or removed.

I completely agree. Obsoleted in #16505.
