### ISSUE TITLE
EntryPointNotFoundException when Window.ShowDialog() called on Windows 1511

### ISSUE THREAD

**Issue by SKasperczyk** [AvaloniaUI/Avalonia#16444]
### Describe the bug

When trying to show window in dialog mode via `Window.ShowDialog()` on Windows 1511 the following exception is thrown and application crashes:
`System.EntryPointNotFoundException`
`Unable to find an entry point named 'AdjustWindowRectExForDpi' in DLL 'user32.dll'.`

### To Reproduce

Execute `Window.ShowDialog()` on Windows 1511.

### Expected behavior

Apparently `AdjustWindowRectEx()` should be called instead of `AdjustWindowRectExForDpi()` at `WindowImpl.cs`: `RECT WindowImpl.ClientRectToWindowRect(RECT clientRect, WindowStyles? styleOverride, WindowStyles? extendedStyleOverride)` for windows 1511 or earlier.

### Avalonia version

11.1.0-beta1

### OS

Windows

### Additional context

I might be wrong, but it seems that `Windows10_1607` const in `PlatformConstants.cs` is defined wrong.
Shouldn't it be `10.0.14393` instead of `10.0.1607`. Crashed system was reported as `10.0.10586` so it might be that `10.0.10568 > 10.0.1607`. Though I'm no cerain about that as I'm unable to check what `Win32Platform.WindowsVersion` is actually returning.

Either way, it looks like following statement:
```cs
var result = Win32Platform.WindowsVersion < PlatformConstants.Windows10_1607
                ? AdjustWindowRectEx(ref clientRect, (uint)style, false, (uint)extendedStyle)
                : AdjustWindowRectExForDpi(ref clientRect, style, false, extendedStyle, (uint)(RenderScaling * StandardDpi));
```
calls always `AdjustWindowRectExForDpi()`

**Comment by maxkatz6** [comment]
> I might be wrong, but it seems that Windows10_1607 const in PlatformConstants.cs is defined wrong.

That's correct. It should be 10.0.14393.
