### ISSUE TITLE
Huge memory leaks in my app

### ISSUE THREAD

**Issue by AuroraZiling** [AvaloniaUI/Avalonia#16465]
### Describe the bug

After triggering any event, it results in a significant increase in unmanaged memory usage, and I don't know how to troubleshoot these suspected memory leaks.

My repo: https://github.com/AuroraZiling/Hollow
Release without runtime: https://github.com/AuroraZiling/Hollow/releases/download/v0.0.3-alpha/withoutRuntime.zip
Release with runtime: https://github.com/AuroraZiling/Hollow/releases/download/v0.0.3-alpha/withRuntime.zip

### To Reproduce

Switching pages multiple times after opening the app (this is the most obvious) and other actions (clicking on checkboxes in the settings page, etc.) can also cause the memory usage to rise

### Expected behavior

memory usage remains stable

### Avalonia version

11.1.0

### OS

Windows

### Additional context

10gb screenshot:
![6bb15b997267117417978a81527221fb](https://github.com/user-attachments/assets/5178a511-7d38-4831-a7e7-67e471bcbb49)

**Comment by washingtown** [comment]
同样的问题，请问解决了吗？

**Comment by AuroraZiling** [comment]
我最后通过改renderingmode解决了这个问题，但至今不知道为什么
```csharp
public static AppBuilder BuildAvaloniaApp()
        => AppBuilder.Configure<App>()
            .UsePlatformDetect()
            .With(new Win32PlatformOptions
            {
                RenderingMode = [Win32RenderingMode.AngleEgl]
            });
```

**Comment by washingtown** [comment]
我的问题也解决了，内存泄露是因为我使用了自定义字体，改为默认字体就正常了……
