### ISSUE TITLE
XMLNS Definitions not working on external libraries.

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#1646]
This issue has been tested on latest nightly builds. 
To repro, make a new Avalonia project, and add [AvaloniaEdit](https://www.nuget.org/packages/Avalonia.AvaloniaEdit/) package. Add the following namespace to `MainWindow` tag:

```xml
xmlns:ae="https://github.com/avaloniaui/avaloniaedit"
```

It should fail to find the type when you add the following control on `MainWindow`'s main `Grid`:
```
<ae:TextEditor/>
```

**Comment by jmacato** [comment]
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/523.

**Comment by GF-Huang** [comment]
Same issue, any workaround?

![image](https://user-images.githubusercontent.com/4510984/103857211-ff44bc80-50f0-11eb-838d-39e0ad2be489.png)

**Comment by maxkatz6** [comment]
@GF-Huang this issue about xmlns definition attributes, so it's not the same as yours.
Are you using 0.10-rc1 version?
Have you rebuild your project after adding reference to the ScottPlot package?

**Comment by GF-Huang** [comment]
Yes, it's `0.10-rc1`.
Yes, I had rebuild all the solution.

**Comment by maxkatz6** [comment]
I don't think 0.10-rc1 project can be buildable with ScottPlot.Avalonia package, because it doesn't support 0.10 Avalonia yet.
See:
https://github.com/swharden/ScottPlot/pull/656

**Comment by GF-Huang** [comment]
OK, I will back to 0.9x

**Comment by maxkatz6** [comment]
You also can use 0.10.0-preview6 which should work fine with that library. Haven't tested though.

**Comment by GF-Huang** [comment]
> You also can use 0.10.0-preview6 which should work fine with that library. Haven't tested though.

So what's breaking the compatibility?

**Comment by GF-Huang** [comment]
Still not work.

![image](https://user-images.githubusercontent.com/4510984/103860147-379ac980-50f6-11eb-9786-c2ba34152b55.png)

![image](https://user-images.githubusercontent.com/4510984/103860166-3e294100-50f6-11eb-90d6-e9005347bab4.png)

**Comment by GF-Huang** [comment]
@maxkatz6 Please see this #5259

**Comment by kekekeks** [comment]
Try specifying the xmlns the old-fashioned way with `clr-namespace` and `assembly=`. I suspect that designer is unable to resolve the type because the assembly wasn't loaded yet.

**Comment by GF-Huang** [comment]
But I'm facing another issue, I create `AnotherView.axaml` for testing purpose just now, and then I delete it. But now I give me an error as following.

![image](https://user-images.githubusercontent.com/4510984/103864387-76804d80-50fd-11eb-8951-dd4d7ab11c52.png)

**Comment by maxkatz6** [comment]
> So what's breaking the compatibility?

0.10.0-rc1 is signed and is not compatible with previous versions.

And yoh can't use "using:" syntax in 0.9 versions, so you need clr-namespace as it was already said. 

Not sure what can be a problem in your latest message, maybe @kekekeks knows. But try to delete bin/obj folders (simple Clear target may not do it completely).

**Comment by GF-Huang** [comment]
`0.10-preiview6` still not work, did you try it?

![image](https://user-images.githubusercontent.com/4510984/103887503-18179700-511e-11eb-9e42-ee52e2fdcba4.png)

![image](https://user-images.githubusercontent.com/4510984/103887530-2665b300-511e-11eb-81fe-f2e251cc42e8.png)

**Comment by Gillibald** [comment]
`Scottplot` uses `Avalonia 0.9.11`

**Comment by GF-Huang** [comment]
> `Scottplot` uses `Avalonia 0.9.11`

Thanks, I had give up `Scottplot`, I will try draw by myself.

**Comment by grokys** [comment]
This issue seems to have drifted from the original problem, which I think should have been fixed for a long time. @GF-Huang if you're still having problems please open a new issue with your problem.
