### ISSUE TITLE
Avalonia 11.1.1 Fullscreen doesn't work anymore (Android Tablet)

### ISSUE THREAD

**Issue by andyld97** [AvaloniaUI/Avalonia#16493]
### Describe the bug

Previously using `Avalonia 11.0.11` I used the following code:

`MainView.axaml.cs:`

```cs
    protected override void OnLoaded(RoutedEventArgs e)
    {
        base.OnLoaded(e);

        // See https://github.com/AvaloniaUI/Avalonia/issues/13598#issuecomment-1809748252
        var insetsManager = TopLevel.GetTopLevel(this)?.InsetsManager;

        if (insetsManager != null)
        {
            insetsManager.DisplayEdgeToEdge = true;
            insetsManager.IsSystemBarVisible = false;
        }

        GridWeather.IsVisible = Settings.Instance.DisplayWeatherInfo;            
    }
```

`MainWindow.axaml`:

```cs
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:views="clr-namespace:Bahntafel.Views"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="Bahntafel.Views.MainWindow"
        Icon="/Assets/icon.ico"
		WindowState="FullScreen"
        Title="Bahntafel">
        <views:MainView />
</Window>
```

This displayed the application fully on screen on Android. Thats means no navigation and no statusbar.
Upgrading the packages to `11.1.1` leads to a not fully working fullscreen.

Previously:
![Screenshot_20240726-183849](https://github.com/user-attachments/assets/3f543292-bbc7-4a0e-b7a5-9bc5962fc77c)
The navigationbar and the statusbar are visible because I created the screenshot, but I think the image between those pictures is clearly visibile.

Now:
![Screenshot_20240726-184229](https://github.com/user-attachments/assets/43667a2b-5857-466f-aa95-0a3851095ba1)

If it helps, I can also make a repro project!

### To Reproduce

Using the given code to make a fullscreen app and run in on an android device.

### Avalonia version

11.1.1

### OS

Android 10 / API 29

**Comment by andyld97** [comment]
You are indeed right, I tried the example app you modified for me last year and I wasn't able to reproduce it firstly. But I was able to reproduce the problem, the app actually is in fullscreen mode, if I set a different background color on the `MainView.axaml`-UserControl it is visibile:

![Screenshot_20240730-213953 1](https://github.com/user-attachments/assets/2697e4ce-fa3d-489e-a509-69f3b3ff3396)

So it seems like the grid is not fully stretched to the viewport and if I downgrade the version it is working, as I said before.

To make it easier for your I made two repos:

Faulty one (You can see the green background)
[FullscreenTest-Faulty.zip](https://github.com/user-attachments/files/16432755/FullscreenTest-Faulty.zip)

Working one (You cannot see the green background) (Exactly the same code, but downgraded Avalonia Version)
[FullscreenTest-Working.zip](https://github.com/user-attachments/files/16432792/FullscreenTest-Working.zip)

I hope this helps to reproduce or at least to find the problem, maybe its a problem with my code, but I don't think there is anything special, just some grid mechanics.

**Comment by emmauss** [comment]
Found out the difference between version. In 11.1, we added auto safe area padding to the TopLevel here, https://github.com/AvaloniaUI/Avalonia/pull/13047 . It is by default `true`. This would ensure the child always fits the safe area, while allowing the parent to fill the whole screen. Good for out-of-box safe area support.
To disable this, set the attached property to false in your main view.
`TopLevel.AutoSafeAreaPadding="False"`
Like this;
```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:vm="clr-namespace:FullscreenTest.ViewModels"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="FullscreenTest.Views.MainView"
             Background="Green"
             TopLevel.AutoSafeAreaPadding="False"
             x:DataType="vm:MainViewModel">
```

**Comment by andyld97** [comment]
Thank you so much, that did the trick! I read the changelog, but not in that detail, only that what was announced. But it's also mentioned on the InsetManager-Documentation, that's pretty good.
