### ISSUE TITLE
ColorView - broken style in Simple theme

### ISSUE THREAD

**Issue by cho3ek89** [AvaloniaUI/Avalonia#16497]
### Describe the bug

I have noticed a few problems with Simple theme style of **ColorView** control (Fluent theme seems to be fine).

Slight defect of **TabControl**:
In Fluent theme, You can just click anywhere in **TabItem** in order to switch tabs.
In Simple theme, You must click _specifically_ on **PathIcon** which is a bit annoying.

Upper button of a **ScrollBar** is visible in ARGB **TextBox** controls.
This can be worked around by setting fixed Height in a **TextBox** (see an example).

Text is not vertically centered in # **TextBox**.

### To Reproduce

Extract and launch:
[ColorPickerStylesRepro.zip](https://github.com/user-attachments/files/16398376/ColorPickerStylesRepro.zip)

### Avalonia version

11.1.1

### OS

Windows

**Comment by timunie** [comment]
A PR to adopt it would be welcome. You need a transparent background for the TabHeader to make it work accepting click everywhere

**Comment by cho3ek89** [comment]
> You need a transparent background for the TabHeader to make it work accepting click everywhere
Works indeed! THX

**Comment by timunie** [comment]
@cho3ek89 could you create a Pull request to fix it in source? Would be really nice 🙂

**Comment by cho3ek89** [comment]
OK. I'll give it a try.

**Comment by timunie** [comment]
@cho3ek89 will try to assist where needed. You can also ask on Telegram https://t.me/Avalonia

**Comment by cho3ek89** [comment]
I did some digging.
We can set Background="Transparent" in TabItem and VerticalContentAlignment="Center" in '#' TextBox in `ColorView.xaml`.

But when it comes to those ScrollBars - problem lies deeper:
`src\Avalonia.Themes.Simple\Controls\NumericUpDown.xaml`
Margin of nested TextBox is set to 4 (-1 in Fluent) for whatever reason.
As a result, if Height of NumericUpDown is below 33 - ScrollBar shows up. Try this on Simple theme:
`<NumericUpDown ShowButtonSpinner="False" Height="32" Value="11111" />`

It can be worked around in `ColorView.xaml` of course, but would it not be better to fix `NumericUpDown.xaml`? But that smells like very low level change...

**Comment by timunie** [comment]
> Margin of nested TextBox is set to 4 (-1 in Fluent) for whatever reason. 

@maxkatz6 any idea about this one?

**Comment by robloo** [comment]
I'll open a PR to fix this since it's ColorPicker
