### ISSUE TITLE
Adding features to Carousel component.

### ISSUE THREAD

**Issue by Aminion** [AvaloniaUI/Avalonia#165]
1. Vertical sliding.
2. The ability to make visible part of the previous and the next slide.

**Comment by ncarrillo** [comment]
- [ ] Add support for an Orientation property in [PageSlide.cs](https://github.com/Perspex/Perspex/blob/master/src/Perspex.SceneGraph/Animation/PageSlide.cs)
- [ ] Modify [DeckStyle](https://github.com/Perspex/Perspex/blob/a2aecd3d91633633eeafd420c2764bb4c7a3b026/src/Perspex.Themes.Default/DeckStyle.cs) to perhaps use a `VisualBrush` to render the prev and next slide.

**Comment by grokys** [comment]
I like your thinking! So it's turning into more of a Carousel control. Maybe we should rename it to that?

**Comment by grokys** [comment]
Already changed name from `Deck` to `Carousel`, updated issue title to reflect this.

**Comment by jmacato** [comment]
Closing this for now since it's been a while since the issue has been responded to.
