### ISSUE TITLE
Caption Buttons disappearing

### ISSUE THREAD

**Issue by Gurylev** [AvaloniaUI/Avalonia#16503]
### Describe the bug

If you use this markup, the caption buttons are not visible.

`WindowState="Maximized"
SystemDecorations="Full"
ExtendClientAreaToDecorationsHint="True"`

![image](https://github.com/user-attachments/assets/a159c83e-daa2-4c48-87ce-1ae51785185e)

### To Reproduce

Add this code in window markup

`WindowState="Maximized"
SystemDecorations="Full"
ExtendClientAreaToDecorationsHint="True"`

### Expected behavior

The caption buttons will be visible and the window will be expanded to maximized.

![image](https://github.com/user-attachments/assets/514168bf-e018-4598-bfe5-b82ed3e0123d)

### Avalonia version

11.1.1

### OS

Windows

**Comment by grokys** [comment]
Looks to have been introduced by https://github.com/AvaloniaUI/Avalonia/pull/15177.

**Comment by rabbitism** [comment]
> Looks to have been introduced by https://github.com/AvaloniaUI/Avalonia/pull/15177.

Feel free to close my pr if you need to fix in other approaches.
