### ISSUE TITLE
First time window without borders has incorrect position

### ISSUE THREAD

**Issue by npolyak** [AvaloniaUI/Avalonia#16529]
### Describe the bug

This window is still shifted as if it has the borders and the title bar. For example here is a pink window without borders and title bar 

        SystemDecorations = SystemDecorations.None
       CanResize = false

I attempt to start this window at position (0,0).

![image](https://github.com/user-attachments/assets/5b16f0c5-c835-416a-bbac-27fc87481591)

It is still shifted horizontally and vertically as if it has title bar and border. 

Then if I hide the window and show it again, it is displayed at a correct position. 

### To Reproduce

Please, see above

### Expected behavior

The window should be displayed at a correct position specified by its Position property. 

### Avalonia version

11.1.1

### OS

Windows

### Additional context

Not sure if it started happening with 11.1.1 or was there before. I noticed it only now.

**Comment by TomEdwardsEnscape** [comment]
This was introduced by #14954.
