### ISSUE TITLE
FontWeight.ExtraBold is rendered heavier since 11.1

### ISSUE THREAD

**Issue by mterwoord** [AvaloniaUI/Avalonia#16537]
### Describe the bug

I'm using FontWeight.ExtraBold in an application. After upgrading from 11.0.10 to 11.1.1, the text is rendered way heavier, and is harder to read.

### To Reproduce

See attached solution. Set all avalonia package versions to 11.0.10 to see the old behavior. Upgrade to 11.1.1 or (at this moment) latest preview version to see the changed rendering.
[AvaloniaApplication1Changed.zip](https://github.com/user-attachments/files/16426789/AvaloniaApplication1Changed.zip)

### Expected behavior

I didn't expect any changes, or I would have expected a breaking change notice in the release notes somewhere.

Old behavior:
![image](https://github.com/user-attachments/assets/2d3c501a-a434-403b-8d2c-a72c306472ae)

New behavior:
![image](https://github.com/user-attachments/assets/f9439345-16c9-4d99-a5ad-b42050027aaa)

### Avalonia version

11.1.1

### OS

Windows

**Comment by genment** [comment]
I'm using Avalonia version 11.1.3 and encountered a similar issue. I'm not sure if it's the same bug. From the image, it seems that the font weights 600 and 700 are swapped, and the same issue appears between 800 and 900 as well.

![图片](https://github.com/user-attachments/assets/0e9dc0c9-794d-412e-85d4-d6d2246ca0c2)

```xml
<Grid RowDefinitions="Auto Auto Auto Auto Auto Auto Auto Auto Auto">
  <Grid.Styles>
    <Style Selector="TextBlock">
      <Setter Property="FontFamily" Value="Arial"></Setter>
      <Setter Property="FontSize" Value="28"></Setter>
    </Style>
  </Grid.Styles>

  <TextBlock Grid.Row="0" Grid.Column="0" FontWeight="100">FontWeight 100</TextBlock>
  <TextBlock Grid.Row="1" Grid.Column="0" FontWeight="200">FontWeight 200</TextBlock>
  <TextBlock Grid.Row="2" Grid.Column="0" FontWeight="300">FontWeight 300</TextBlock>
  <TextBlock Grid.Row="3" Grid.Column="0" FontWeight="400">FontWeight 400</TextBlock>
  <TextBlock Grid.Row="4" Grid.Column="0" FontWeight="500">FontWeight 500</TextBlock>
  <TextBlock Grid.Row="5" Grid.Column="0" FontWeight="600">FontWeight 600</TextBlock>
  <TextBlock Grid.Row="6" Grid.Column="0" FontWeight="700">FontWeight 700</TextBlock>
  <TextBlock Grid.Row="7" Grid.Column="0" FontWeight="800">FontWeight 800</TextBlock>
  <TextBlock Grid.Row="8" Grid.Column="0" FontWeight="900">FontWeight 900</TextBlock>

</Grid>
```
