### ISSUE TITLE
Controls in NativeControlHost are not displayed in Windows and are now transparent in linux

### ISSUE THREAD

**Issue by wang-ning-wn** [AvaloniaUI/Avalonia#16532]
### Describe the bug

Dear avalonia developer, I have a problem now, I hope you can help me look at it。
The premise is: I use the hikvision sdk to show the video, the official example to the winform example, the example passed a picturebox handle. In wpf I embedded the winform picturebox, or used the wpf window handle.
I tried some of the ways to use NativeControlHost, as follows:
```
public class MyNativeControlHost : NativeControlHost
 {
     public IntPtr Handle { get; private set; }
     protected override IPlatformHandle CreateNativeControlCore(IPlatformHandle parent)
     {
         //1
         //var handle = base.CreateNativeControlCore(parent);
         //Handle = handle.Handle;
         //return handle;
         //2
         //The following code demonstrates a window embedded in NativeControlHost
         //var win = new MyWindow();
         //Handle = (IntPtr)win.TryGetPlatformHandle()?.Handle;
         //return win.TryGetPlatformHandle();
         //3
         //The following code demonstrates a qwidget embedded with a qt project in NativeControlHost
         QtLibForm form = new QtLibForm(parent.Handle, true);
         Handle = parent.Handle;
         return base.CreateNativeControlCore(parent);
     }
 }
```
xaml code：
```
>  <Grid>
    <TextBlock Text="IP：" Margin="10,20,0,0" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <TextBox x:Name="TxtIp" Width="200" Margin="70,10,0,0" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <TextBlock Text="Port：" Margin="290,20,0,0" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <TextBox x:Name="TxtPort" Width="200"  Margin="360,10,0,0" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <TextBlock Text="Name：" Margin="10,70,0,0" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <TextBox x:Name="TxtName" Width="200"  Margin="70,60,0,0" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <TextBlock Text="     PW："  Margin="290,70,0,0" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <TextBox x:Name="TxtPw" Width="200" Margin="360,60,0,0" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <Button Content="Login" Width="80" Height="60" HorizontalContentAlignment="Center" VerticalContentAlignment="Center"
            Margin="600,20,0,0"  Click="Button_Click_1" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <TextBlock Text="Channel：" Margin="10,120,0,0" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <TextBox x:Name="TxtTd" Width="200" Margin="70,110,0,0"  HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <Button Content="Live View" Width="80" Height="40" HorizontalContentAlignment="Center" VerticalContentAlignment="Center"
            Margin="300,105,0,0"  Click="Button_Click_2" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <TextBlock x:Name="TxtLog" Width="490" IsEnabled="False" Margin="700,10,0,0" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    <ContentControl x:Name="MyContentControl"  Margin="10,180,0,0" Background="Gray" Width="600" Height="400" HorizontalAlignment="Left"/>
  </Grid>
```
cs code：
> MyNativeControlHost host = new MyNativeControlHost();
MyContentControl.Content = host;

MyWindow：

avalonia's new window, "Welcome to Avalonia!"

I tried Method 1 and hikvision didn't display properly under Linux.
I tried method 2, there is a very strange problem, under window, MyWindow only shows the title, the middle content is black is not displayed, in linux MyWindow is transparent.
![1722302801170](https://github.com/user-attachments/assets/d67a925e-f52f-4f9f-bb33-718815cbc9c0)

I tried method 3, QtLibForm is my qwidget for qt, the problem phenomenon is the same as problem 2, I feel like a problem.

### To Reproduce

qt that code is a little too much, you can try to embed window in NativeControlHost, this in Windows and linux effect and qt the same, I guess is a problem

### Avalonia version

11.0.10

### OS

Windows, Linux

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/8609#issuecomment-1196642227

**Comment by wang-ning-wn** [comment]
> [#8609（评论）](https://github.com/AvaloniaUI/Avalonia/issues/8609#issuecomment-1196642227)

@kekekeks Thanks for reply,But I've already added it to the app.manifest file

![1722330510106](https://github.com/user-attachments/assets/199c6f05-5713-4ce3-8dee-7a610fc8d9a3)

**Comment by wang-ning-wn** [comment]
> [#8609 (comment)](https://github.com/AvaloniaUI/Avalonia/issues/8609#issuecomment-1196642227)

And I'm not throwing any exceptions

**Comment by wang-ning-wn** [comment]
> What does `QtLibForm` do with the parent handle? does it render when show as a window on its own?

@emmauss I use the parent handle to create the qwidget. I can display qt pages in winform, but not in avalonia. In avalonia, I directly pass the window handle to create the qwidget which is transparent. Do not display qt content with NativeControlHost。
![1722408809993](https://github.com/user-attachments/assets/e9ca495a-910a-4e07-b427-75002b71f9f5)

**Comment by emmauss** [comment]
> > What does `QtLibForm` do with the parent handle? does it render when show as a window on its own?
> 
> @emmauss I use the parent handle to create the qwidget. I can display qt pages in winform, but not in avalonia. In avalonia, I directly pass the window handle to create the qwidget which is transparent. Do not display qt content with NativeControlHost。 ![1722408809993](https://private-user-images.githubusercontent.com/176862931/353725508-e9ca495a-910a-4e07-b427-75002b71f9f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTM1NjksIm5iZiI6MTcyMjQxMzI2OSwicGF0aCI6Ii8xNzY4NjI5MzEvMzUzNzI1NTA4LWU5Y2E0OTVhLTkxMGEtNGUwNy1iNDI3LTc1MDAyYjcxZjlmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwODA3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWYzNDZmNjU0NTRjOTkyYzc5NjRlMjhmZWI3NjUzNzk2OTk3ZDcxNzkzMDg3YWRjODgyMWVjOGY1YzhmODYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I_mKPu-Hz2OXkd9JMPanLrh4znECsaWMGgiL7WolLvY)

We don't recommend directly using our window handle from a normal window, as we set up our own message queue and rendering. Other windowing toolkits will interfere with it. As for handle passed in the native control host, could you create a child window using win32 apis and parent it with the handle provided, then use that child window for the qt form?

**Comment by wang-ning-wn** [comment]
> > > What does `QtLibForm` do with the parent handle? does it render when show as a window on its own?
> > 
> > 
> > @emmauss I use the parent handle to create the qwidget. I can display qt pages in winform, but not in avalonia. In avalonia, I directly pass the window handle to create the qwidget which is transparent. Do not display qt content with NativeControlHost。 ![1722408809993](https://private-user-images.githubusercontent.com/176862931/353725508-e9ca495a-910a-4e07-b427-75002b71f9f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTM1NjksIm5iZiI6MTcyMjQxMzI2OSwicGF0aCI6Ii8xNzY4NjI5MzEvMzUzNzI1NTA4LWU5Y2E0OTVhLTkxMGEtNGUwNy1iNDI3LTc1MDAyYjcxZjlmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwODA3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWYzNDZmNjU0NTRjOTkyYzc5NjRlMjhmZWI3NjUzNzk2OTk3ZDcxNzkzMDg3YWRjODgyMWVjOGY1YzhmODYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I_mKPu-Hz2OXkd9JMPanLrh4znECsaWMGgiL7WolLvY)
> 
> We don't recommend directly using our window handle from a normal window, as we set up our own message queue and rendering. Other windowing toolkits will interfere with it. As for handle passed in the native control host, could you create a child window using win32 apis and parent it with the handle provided, then use that child window for the qt form?

@emmauss Thank you very much for your help, I found that the window embedded in NativeControlHost is not displayed, it is black. The reason is that I don't show ().
