### ISSUE TITLE
Custom font with ligatures

### ISSUE THREAD

**Issue by johannesegger** [AvaloniaUI/Avalonia#1654]
Is it possible to render font ligatures if the font supports it? E.g. I use [FiraCode](https://github.com/tonsky/FiraCode) (see code snippet below) and want to render its ligatures inside a text box (e.g. for `->`, `==`, etc.). I'm pretty sure that the font loads correctly (it's not the default font that the text is rendered with) but there are no ligatures rendered.

```csharp
FontFamily fontFamily = "resm:PlayAndLearn.Fonts.FiraCode.FiraCode-*.ttf?assembly=PlayAndLearn#Fira Code";
```

**Comment by Gillibald** [comment]
I am not sure how font ligatures work. FiraCode is just a font. Don't know if there is some special handling needed.

**Comment by johannesegger** [comment]
Yes I think it needs special treatment. I recently read about an issue concerning the *treatment* in WPF. I might have a look into this and you might get a PR at some point.

**Comment by aplocher** [comment]
I'm not sure either exactly how it works, but font ligatures definitely must be supported by the app using them in order for them to work properly.  It's not as simple as simply utilizing a font.  Firacode is badass btw, best coding font ever (when lig's work) and if you get that working then you guys rock!

**Comment by Gillibald** [comment]
Fonts support embedded scripts and the render backend has to understand them properly. That is what goat want.

**Comment by johannesegger** [comment]
I think it can't be handled by Avalonia directly but must be adressed by the underlying rendering engine. I had a look at how Avalonia renders text using Skia and debugging took me no further than [here](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Skia/Avalonia.Skia/FormattedTextImpl.cs#L247) because the rest is SkiaSharp's business.  
I also had a look at VSCode's implementation of ligature support and the only hint I found was that [large tokens are not being split if ligatures are enabled](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/viewLayout/viewLineRenderer.ts#L355-L357).  
My (somewhat bold) guess is that SkiaSharp (or something underneath it) renders text token by token but should render them in token groups (so that the font can combine multiple tokens to a single glyph - the ligature). However I'm totally not sure if that's the case, I would have to dig much deeper into this.

**Comment by Gillibald** [comment]
Ligatures are just replacements for specific glyph combinations. If these combinations accure the involved glyphs are replaced by one glyph that belongs to that combination. This can be supported but I think there are other features that are more important at the moment.

**Comment by johannesegger** [comment]
As I said I don't think Avalonia is able to fix this because the problem seems to be somewhere downstream (at least for Skia I'm quite sure). Feel free to close this issue.
