### ISSUE TITLE
Android screen rotation causes crash

### ISSUE THREAD

**Issue by 3rob3** [AvaloniaUI/Avalonia#16588]
### Describe the bug

After updating my Avalonia versions to 11.1.1 (from 11.0.13), screen rotations cause my Android app to crash. When debugging on emulator the error is:
System.NotSupportedException: 'Unable to activate instance of type Avalonia.Android.AvaloniaView from native handle 0x7fffc4d5fc38 (key_handle 0x82127b2).'

### To Reproduce

I'm not sure exactly, as the demo/default app created with a new project rotates fine.

### Expected behavior

Doesn't crash :). As mentioned this doesn't happen in 11.0.13.

### Avalonia version

11.1.1

**Comment by 3rob3** [comment]
repo is: https://github.com/3rob3/ImmichFrame

**Comment by maxkatz6** [comment]
Seems to be the same as https://github.com/AvaloniaUI/Avalonia/issues/16468 and https://github.com/AvaloniaUI/Avalonia/issues/15903

**Comment by 3rob3** [comment]
> Seems to be the same as #16468 and #15903

The ConfigurationChanges? I had found and tried that already. Same thing happens.
