### ISSUE TITLE
Unsupported IBinding implementation after migration on 11.1

### ISSUE THREAD

**Issue by ds1709** [AvaloniaUI/Avalonia#16623]
### Describe the bug

I have custom `IBinding` implementation, based on math expressions. After migrating from versio `11.0` to `11.1` I got `Unsupported IBinding implementation` exception becaus my MathExpressionBinding doesn't implement `IBinding2` interface. How can I implement it if it's internal, how can I implement any custom `IBinding`? Also I can't inherits from `BindingBase` because I cant implement it's `private protected` members. Version `11.1` is backward incompatible with `11.0`, it breaks binary compatibility, it breaks behavior compatibility, it breaks sematic versioning principles. It must be `12.0`, but not `11.1`. It's fully incompatible with 11.0.

### To Reproduce

Just try to implement `IBinding2` interface.

### Avalonia version

11.1.2

**Comment by kekekeks** [comment]
How exactly did you manage to implement an interface marked with [NotClientImplementable]? We are injecting special non-implementable methods to our ref assemblies to prevent that

**Comment by ds1709** [comment]
Interface `IBinding` is not `NotClientImplementable`, it works in version `11.0.*`. But it throws exception in version `11.1.*`. It's backward compatibility violation, and it must be major version update, not minor.

**Comment by grokys** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/11.0.13/src/Avalonia.Base/Data/IBinding.cs#L8

**Comment by grokys** [comment]
See also: https://github.com/AvaloniaUI/Avalonia/issues/15270

**Comment by kekekeks** [comment]
It's marked as such at least since 11.0.0-preview1. I think our injected method no longer prevents Roslyn from building the assembly.

**Comment by ds1709** [comment]
Seems like we're talking about different things...
https://semver.org
```
If you have a huge audience that will be drastically impacted by changing the behavior back to what the public API intended, then it may be best to perform a major version release, even though the fix could strictly be considered a patch release.
```
It doesn't matter mark you it like `NotClientImplementable`, you are changing behavior compatibility, it MUST be major update, version `12.0`.
Also, in version `11.0.11` I implemented my own `MathExpressionBinding : IBinding` and it works fine.

**Comment by ds1709** [comment]
> IBinding not working when implemented by user code is expected.

My own binding works as expected, and implementing my own binding was the best solution in my case.

If you want to prevent user code from implementing interface, just make it internal (like `IBinding2`), or mark it with `ObsoleteAttribute`. Yes, making `public` interface `internal` breaks API and ABI compatibility, but breaking behavior is the worst of all.
