### ISSUE TITLE
Tooltip doesn't disapear after mouse moves away

### ISSUE THREAD

**Issue by gbrzeczek** [AvaloniaUI/Avalonia#16628]
### Describe the bug

If a tooltip is added to an element, after hovering over the element the tooltip appears correctly. However, after moving the mouse away, the tooltip stays visible and in some cases it can cover other elements of the UI. After clicking the mouse anywhere, the tooltip disappears.

Occurred on Windows 10, build 19045.4651

### To Reproduce

1. Create a StackPanel with some content
2. Set `ToolTip.Tip="Some text"` on the stackpanel
3. Start the application, hover the mouse over the stackpanel - tooltip should appear
4. Move the mouse away from the stackpanel - the tooltip should stay on
5. Click the mouse anywhere - the tooltip should disappear

### Expected behavior

The tooltip should disappear after moving the mouse away from the element, without the need to click the mouse button

### Avalonia version

11.1.2

### OS

Windows

### Additional context

![image](https://github.com/user-attachments/assets/a0c3fa2e-9090-4e57-acef-aa49dc394f19)

At the moment of the screenshot, the mouse was already outside of the stackpanel for several seconds

**Comment by MrJul** [comment]
Can you please try latest nightly builds? It should have been fixed by #16564.

**Comment by gbrzeczek** [comment]
I confirm, works as expected on the nightly build. Thank you
