### ISSUE TITLE
Can't build in release mode. Can't find SimpleTheme

### ISSUE THREAD

**Issue by bign0name** [AvaloniaUI/Avalonia#16624]
### Describe the bug

Everything works in debug, however when I switch to release mode I get the following error from App.axaml:
AVLN2000	Unable to resolve type SimpleTheme from namespace https://github.com/avaloniaui Line 8, position 6	

### To Reproduce

Build an app in debug, then switch to release. Simple theme can't be found.

https://github.com/user-attachments/assets/876da9c1-deba-43c6-821e-b38302337387

### Expected behavior

Should be able to switch to release mode and simple theme should work.

### Avalonia version

11.1.0

### OS

Windows

**Comment by stevemonaco** [comment]
Double check that you've added the `Avalonia.Themes.Simple` package from NuGet in your csproj.

DevTools (which is available only in Debug builds by default) will transitively import several Avalonia-related dependencies so it can do its job. One of which is `SimpleTheme`. When in Release mode, these dependencies will not be included so your app must explicitly include them.

**Comment by maxkatz6** [comment]
Avalonia.Themes.Simple is not included.
In Debug mode, you would have it included via [Avalonia.Diagnostics](https://www.nuget.org/packages/Avalonia.Diagnostics)
