### ISSUE TITLE
writeablebitmap performance issues

### ISSUE THREAD

**Issue by qingyu-sama** [AvaloniaUI/Avalonia#16641]
### Describe the bug

When I set the PixelFormat of writeablebitmap to Bgr24, there will be serious performance issues on Android. When playing a 30fps video, it can't even reach 10fps. But when I change the PixelFormat to Bgra8888, it becomes very smooth.

I'm not sure if this is a bug or what, but this situation does not occur on Windows.

### To Reproduce

// Initialize
var bitmap = new WriteableBitmap(new(1920, 1080), new(96, 96), PixelFormats.Bgr24);
Img.Source = bitmap;

// Playing
using (var bits = bitmap.Lock())
    Unsafe.CopyBlock((void*)bits.Address, buffer, (uint)size);

### Avalonia version

11.1.0

### OS

Android

**Comment by MrJul** [comment]
Can you please try latest nightly builds?
Transcoding should have been improved by #14111.

If possible, use 32 bit bitmaps as they won't require any additional processing.

**Comment by maxkatz6** [comment]
I don't think transcoding is feasible at all, when you want to have good enough performance for video playback. AOT might improve transcoding performance noticeable, but it will add other problems to the table.
As @MrJul recommended, you should use Bgra8888 instead if possible.

**Comment by qingyu-sama** [comment]
You are right, I have already changed all to Bgra8888, thanks
