### ISSUE TITLE
TextBlock unexpectedly deletes first character when using input method auto-complete

### ISSUE THREAD

**Issue by realybin** [AvaloniaUI/Avalonia#16656]
### Describe the bug

When using the `auto-complete` feature of an input method (IME) with a `TextBlock` control, the first English character at the beginning of a line is unexpectedly deleted. This behavior occurs consistently and affects the user experience.

### To Reproduce

1. Set up a TextBlock control in your application.
2. Enable an input method that supports auto-complete (e.g., Gboard).
3. Begin typing at the start of a line, using the IME's auto-complete feature.
4. Observe that the first English character is deleted after auto-complete is applied.

### Expected behavior

The TextBlock should maintain all characters, including the first one, when using IME `auto-complete`.

### Avalonia version

11.1.2

### OS

Android

### Additional context

https://github.com/user-attachments/assets/cb47cf6b-979a-46e1-a653-a7145818bda3

Code
```
<StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
        <TextBlock Text="Base &lt;TextBox Width=&quot;200&quot; Height=&quot;50&quot; /&gt;"/>
        <StackPanel Background="Aqua">
            <TextBlock Text="Base With Height and Width attributes" />
            <TextBox Width="200" Height="50" />
        </StackPanel>
        <StackPanel Background="Chocolate">
            <TextBlock Text="TextInputOptions.ReturnKeyType=&quot;Return&quot;" />
            <TextBox Width="200"
                     Height="50"
                     TextInputOptions.ReturnKeyType="Return" />
        </StackPanel>
        <StackPanel Background="Crimson">
            <TextBlock Text="AcceptsReturn=&quot;True" />
            <TextBox Width="200"
                     Height="50"
                     AcceptsReturn="True" />
        </StackPanel>
        <StackPanel Background="DarkOrange">
            <TextBlock Text="AcceptsReturn=&quot;True&quot; TextInputOptions.ReturnKeyType=&quot;Return&quot;" />
            <TextBox Width="200"
                     Height="50"
                     AcceptsReturn="True"
                     TextInputOptions.ReturnKeyType="Return" />
        </StackPanel>
    </StackPanel>
```

**Comment by emmauss** [comment]
Could you test with https://github.com/AvaloniaUI/Avalonia/pull/16666

**Comment by ybin42** [comment]
> Could you test with #16666

``<PackageReference Include="Avalonia.Android" Version="11.2.999-cibuild0051177-alpha" />``
I tested it on my Android 10 device and my first letter still gets eaten.

**Comment by ybin42** [comment]
> Could you test with #16666

> Could you test with #16666

``<PackageReference Include="Avalonia.Android" Version="11.2.999-cibuild0051177-alpha" />``

![image](https://github.com/user-attachments/assets/ee0800e2-0ca0-48a3-8485-212d14c9374c)

I tested it on my Android 10 device and my first letter still gets eaten.

- [x] Solution Cleaned
- [x] Packges Download from https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=51177

**Comment by realybin** [comment]
> Try this 11.2.999-cibuild0051149-alpha

I tested it on my Android 10 device`Gboard` and my first letter still gets eaten.
But [Sogou Pinyin](https://en.wikipedia.org/wiki/Sogou_Pinyin) works well. I don't know how it can be. But Google develops Gboad, it is more likely to adopt the standard.

**Comment by emmauss** [comment]
What's your GBoard version? I've tested many versions across many android versions(OS 6,9, 10, 11, 13, 14), only the AOSP keyboard(not GBoard) on stock Android 10 has an issue with not sending composing regions which is fixed in the linked pr. GBoard itself works fine.

**Comment by realybin** [comment]
> What's your GBoard version? I've tested many versions across many android versions(OS 6,9, 10, 11, 13, 14), only the AOSP keyboard(not GBoard) on stock Android 10 has an issue with not sending composing regions which is fixed in the linked pr. GBoard itself works fine.

14.4.04.646482735-release-arm64-v8a
System: Android 10 with MIUI 12.5.1 (MIX2S)

**Comment by emmauss** [comment]
Could you test with this?
11.2.999-cibuild0051267-alpha

**Comment by realybin** [comment]
Fixed

**Comment by emmauss** [comment]
The fix isn't merged yet.
