### ISSUE TITLE
Default button press no longer triggered on input submit

### ISSUE THREAD

**Issue by kerams** [AvaloniaUI/Avalonia#16655]
### Describe the bug

Using the submit button on a software keyboard on Android no longer triggers a press of a default button.

### To Reproduce

Using 11.2.999-cibuild0050849-alpha

- ```xml
  <StackPanel>
    <TextBox></TextBox>
    <Button x:Name="btn" IsDefault="true"></Button>
  </StackPanel>
  ```
- Attach a `Click` handler to the button.
- Run, click the textbox, press submit.
- Observe that the handler is not called.

Repeat with 11.2.999-cibuild0049087-alpha and notice the handler *is* called.

### Expected behavior

_No response_

### Avalonia version

11.2.999-cibuild0050849-alpha

### OS

Android

### Additional context

_No response_

**Comment by timunie** [comment]
No longer means it worked before? If so, which version was the last one working? That way we may find the difference quicker.

**Comment by kerams** [comment]
It worked about a month ago. Version info is included above.

**Comment by MrJul** [comment]
The culprit is most likely #16490, pinging @emmauss for confirmation.

**Comment by emmauss** [comment]
Could you test with https://github.com/AvaloniaUI/Avalonia/pull/16666
