### ISSUE TITLE
Main window buttons don’t appear maximized and with ExtendClientAreaToDecorationsHint

### ISSUE THREAD

**Issue by guilhermeolisi** [AvaloniaUI/Avalonia#16688]
### Describe the bug

The window buttons don’t appear on the main window if it starts maximized and uses ExtendClientAreaToDecorationsHint="True". After changing the WindowState to normal or minimized, the buttons appear, even in the maximized state. If the main window starts in the normal state, the buttons appear normally.
This issue occurred after updating Avalonia to version 11.1.0 and persists in version 11.1.2.
Avalonia Version: 11.1.2
Windows Version: 11

### To Reproduce

In a new Avalonia project, set the properties of MainWindow as follows: ExtendClientAreaToDecorationsHint="True" and WindowState="Maximized".

Run the attached project to reproduce the issue.

[TestButtonsMainWindow.zip](https://github.com/user-attachments/files/16606104/TestButtonsMainWindow.zip)

### Avalonia version

11.1.X

### OS

Windows

### Additional context

Main Window without buttons (started maximized)

![Avalonia without window buttons maximized](https://github.com/user-attachments/assets/c737f884-9295-4d96-a7eb-5662b0342dba)

Main Windows with buttons (started normal)

![Avalonia with window buttons normal](https://github.com/user-attachments/assets/6fa6cf8a-4be4-439d-a6b7-2491f53f9e3d)

**Comment by emmauss** [comment]
Duplicate https://github.com/AvaloniaUI/Avalonia/issues/16503
