### ISSUE TITLE
GetObservable couldn't subscrible event in UserControls

### ISSUE THREAD

**Issue by Caritusy** [AvaloniaUI/Avalonia#16695]
### Describe the bug

Complier always report "Cannot convert lambda expression to type 'IObserver<bool>' because it is not a delegate type." in using a GetObservable's Subscrible Method.
![image](https://github.com/user-attachments/assets/bbccc5e9-1405-4af6-b715-5864927f6ab8)
![image](https://github.com/user-attachments/assets/040b78be-c4e4-4d9b-b6e4-54a58e26a846)

### To Reproduce

1. Create a AvaloniaUI Project (Any platform is all the same)
2. Be sure installed "Avalonia.ReactiveUI" from NuGet,or you even can't subcribe that in window
3. Try to Subscrible any event in usercontrol,like `this.GetObservable(IsVisibleProperty).Subscribe(value => { });`
4. Then you got CS1660 error.

### Avalonia version

11.1.3

### OS

Windows

**Comment by maxkatz6** [comment]
As error says (in Chinese, but I memorized this specific error long time ago), you need to pass IObserver object and not lambda.
`System.Reactive` provides extension method to use it with lambdas too, but you need to add `using System;`.

Either way, it's unrelated to Avalonia.
If you didn't use ReactiveUI (and won't have System.Reactive extensions), you could use `AnonymousObserver` object from Avalonia.
