### ISSUE TITLE
Mobile Text Selection Handles

### ISSUE THREAD

**Issue by tkefauver** [AvaloniaUI/Avalonia#16704]
### Is your feature request related to a problem? Please describe.

Mobile `TextBox` and `SelectableTextBox` controls don't provide selection handles so altering the selection range is problematic.

### Describe the solution you'd like

Provide adorner handles like common mobile textboxes:
![android_handles](https://github.com/user-attachments/assets/36fc3f71-de26-42d2-b394-f15cfdfa25f9)

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/13107

**Comment by maxkatz6** [comment]
Yes, check our 11.1.3 version, we already have text selection handles in stable.

**Comment by tkefauver** [comment]
It is!? I should definitely update then I'm still back in 11.0.10. Thanks
for letting me know

**Comment by maxkatz6** [comment]
I am going to close this issue then. Feel free to open any bug issue, if you find anything wrong with handles in the stable.
