### ISSUE TITLE
When using Vulkan rendering for Android, app presents black screen when resuming.

### ISSUE THREAD

**Issue by jhimes144** [AvaloniaUI/Avalonia#16718]
### Describe the bug

When using the app and then navigating away from the app (to home screen, app switcher, or locking device) causes the app to display a black screen when reopened. This only occurs with Vulkan rendering enabled, and does not when using the default EGL rendering. I have not tested software rendering.

### To Reproduce

Modify xplat template MainActivity.cs to have the following app builder code

```
        return base.CustomizeAppBuilder(builder).With(new AndroidPlatformOptions
        {
            RenderingMode = new [] { AndroidRenderingMode.Vulkan }
        }).UseReactiveUI();
```

Run app on a physical android device, navigate away and then back to app.

### Expected behavior

The app resumes without issue.

### Avalonia version

11.1.1

### OS

Android

### Additional context

See my related discussion post here:

https://github.com/AvaloniaUI/Avalonia/discussions/16717

**Comment by kekekeks** [comment]
We are probably not handling device loss condition for Vulkan yet. Suspend/Resume is likely to trigger those

**Comment by emmauss** [comment]
Could you test with the latest nightly builds?

**Comment by PapLabros** [comment]
I have tested with the nightly builds (11.2.999-cibuild0051406-alpha) and can confirm that the bug still persists.
