### ISSUE TITLE
Hidden close & resize buttons when ExtendClientAreaToDecorationsHint is True and WindowsState is Maximized

### ISSUE THREAD

**Issue by marcb152** [AvaloniaUI/Avalonia#16714]
### Describe the bug

In the latest version of AvaloniaUI (11.1.3), the application caption buttons in the upper right corner are invisible at startup. They become visible after resizing the window (Windows + Arrow keys).
On version 11.0.6 it worked as expected (close and resize buttons were visible right after starting the application).

### To Reproduce

- Create a new *Avalonia .NET App (AvaloniaUI)* OR a new *Avalonia .NET MVVM App (AvaloniaUI)*
- Add `ExtendClientAreaToDecorationsHint="True"` and `WindowState="Maximized"` to the `MainWindow.axaml`
- Launch the app, the close & resize buttons are visible as expected
- Run NuGet Package Manager and update all Avalonia packages to 11.1.3
- Once updated, launch the app, the buttons are no longer visible

### Expected behavior

The caption buttons (close and resize buttons in the upper right corner) should be visible immediately after launching the application.

### Avalonia version

11.1.3

### OS

Windows

### Additional context

I can send screenshots & code examples if required.

**Comment by MrJul** [comment]
Please try the latest nightly build, this should have been fixed by #16593.

**Comment by marcb152** [comment]
Thanks for your insight, I'll wait for the 11.1.4 release to see if it's fixed (can't ship software with nightly built libraries).
I have downgraded to 11.0.10 for now (11.1.0 also has this problem, haven't tested other 11.1.x and 11.0.1x versions).

**Comment by robloo** [comment]
@marcb152 If you could still test it to make sure it's fixed with nightly we can close this issue. You wouldn't have to ship anything after a quick confirmation test.

**Comment by marcb152** [comment]
My bad, sure!
Upgrading to nightly `11.2.999-cibuild0051335-alpha` solves the issue. Thanks for your support!
