### ISSUE TITLE
The SmallIcon for notifications in android doesn't set to app icon.

### ISSUE THREAD

**Issue by J0nathan550** [AvaloniaUI/Avalonia#16802]
### Describe the bug

Hello, I encountered a bug that whenever I wish to create a notification in Android (SmallIcon) it doesn't grab my application icon (Drawable.Icon) it just renderes blank gray square.

Here is my code that is creating a foreground service + instantiating in phone the message of application:

```cs
using Android.App;
using Android.Content;
using Android.Graphics;
using Android.OS;
using Android.Util;
using AndroidX.Core.App;
using System.Threading.Tasks;

namespace SoundScapes.Android;

[Service]
public class InfiniteForegroundService : Service
{
    static readonly string? TAG = typeof(InfiniteForegroundService).FullName;
    static readonly int NOTIFICATION_ID = 1000;
    static readonly string CHANNEL_ID = "ForegroundServiceChannel";

    public override void OnCreate()
    {
        base.OnCreate();
        CreateNotificationChannel();
    }

    public override StartCommandResult OnStartCommand(Intent? intent, StartCommandFlags flags, int startId)
    {
        // Load the large icon from resources
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
        Bitmap largeIcon = BitmapFactory.DecodeResource(Resources, _Microsoft.Android.Resource.Designer.ResourceConstant.Drawable.Icon); // Replace with your large icon resource
#pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.

        Notification notification = new NotificationCompat.Builder(this, CHANNEL_ID)
            .SetContentTitle("SoundScapes")
            .SetContentText("Application is running! Enjoy the music!")
            .SetSmallIcon(Resource.Drawable.Icon)
            .SetLargeIcon(largeIcon)
            .SetOngoing(true)
            .Build();

        StartForeground(NOTIFICATION_ID, notification);

        return StartCommandResult.Sticky;
    }

    public override IBinder? OnBind(Intent? intent)
    {
        // Return null because this is a pure started service.
        return null;
    }

    public override void OnDestroy()
    {
        base.OnDestroy();
    }

    private void CreateNotificationChannel()
    {
        if (Build.VERSION.SdkInt >= BuildVersionCodes.O)
        {
            string channelName = "SoundScapes Notifications";
#pragma warning disable CA1416 // Validate platform compatibility
            NotificationChannel channel = new(CHANNEL_ID, channelName, NotificationImportance.Default)
            {
                Description = "SoundScapes Notifications"
            };
#pragma warning restore CA1416 // Validate platform compatibility

            NotificationManager? notificationManager = GetSystemService(NotificationService) as NotificationManager;
#pragma warning disable CA1416 // Validate platform compatibility
            notificationManager!.CreateNotificationChannel(channel);
#pragma warning restore CA1416 // Validate platform compatibility
        }
    }
}
```

Resources of my android app looks like this: 

![Screenshot_1](https://github.com/user-attachments/assets/51239915-cc90-4445-aea1-bf1571c2eff5)

How it looks like:
![Screenshot_3](https://github.com/user-attachments/assets/bff75697-6e5c-4c84-af32-e3a556e32f88)
![Screenshot_2](https://github.com/user-attachments/assets/3ef55a84-58a9-4880-9416-35717580b5ee)

### To Reproduce

Try to create a notification set the icon of you application (even default avalonia one) and set the resources to be the icon of app in notification manager. It will give you blank gray square in the output.

### Expected behavior

Well, my icon. Large Icon works, Small Icon doesn't.

### Avalonia version

11.1.3

### OS

Android

**Comment by timunie** [comment]
I don't see any Avalonia specific code in your snippet. Can you elaborate why and how you think it's a bug on our side?

**Comment by J0nathan550** [comment]
> I don't see any Avalonia specific code in your snippet. Can you elaborate why and how you think it's a bug on our side?

There is actually no code of Avalonia specific code. Because you can't use the framework to load SmallIcon using Avalonia code.
I don't know which bug it is, Xamarin or Avalonia. I simply can't load the SmallIcon. In Resources.Drawing.Icon it should use the `@drawable/icon` which it doesn't use for some reason. I need an advise of what to try.
