### ISSUE TITLE
The AlignmentX and AlignmentY properties of DrawingBrush class do not work on v11.1.1，v11.1.2，v11.1.3

### ISSUE THREAD

**Issue by YangCuisong** [AvaloniaUI/Avalonia#16810]
### Describe the bug

The AlignmentX and AlignmentY properties of DrawingBrush class do not work on v11.1.1，v11.1.2，v11.1.3
but it's work on v11.1.0-beta1, v11.0.10.
On v11.1.0-beta1,v11.0.10 version,It's default value is Center,
On v11.1.1，v11.1.2，v11.1.3,It's default value is Top and Left,

### To Reproduce

After upgrading the version, these two properties changed to Top and Left, and resetting the values has no effect.

### Expected behavior

I hope to enable these two properties in the latest version, or change their default values to Center

### Avalonia version

e.g. 11.1.1,11.1.2,11.1.3

### Additional context

![11 0 10](https://github.com/user-attachments/assets/3795bb1e-eafa-4a21-9a4a-ff7ed285e565)
This is normal, in version 11.0.10。
![11 1 2](https://github.com/user-attachments/assets/44a71511-48f1-4aa7-b912-59647f9348ad)
This is abnormal in version 11.1.3。

**Comment by Gillibald** [comment]
Please add a sample we can easily run at our end

**Comment by maxkatz6** [comment]
Shouldn't these properties align content inside of the tile boundaries? I.e., in your case - inside of 64;64 tile.

**Comment by timunie** [comment]
Yeah looks like a bug in previous versions which was fixed. I remember slightly something like that before but it was wrong. Can't recall issue number atm.

**Comment by YangCuisong** [comment]
> Yeah looks like a bug in previous versions which was fixed. I remember slightly something like that before but it was wrong. Can't recall issue number atm.

Thank you, will it be fixed in the next version? When will the next version be released?

**Comment by YangCuisong** [comment]
> Shouldn't these properties align content inside of the tile boundaries? I.e., in your case - inside of 64;64 tile.

Yes,these properties align content inside of the tile boundaries. Using the same code, in the latest version, they do not work, but they work in versions before 11.1.0-beta1

**Comment by YangCuisong** [comment]
Thank you, everyone. I have seen it and it has been fixed in version 11.2.0-beta1. Thank you very much for your support。
