### ISSUE TITLE
Can't set UserControl DataContext in XAML with compiled bindings if parent DataContext is set in constructor

### ISSUE THREAD

**Issue by Earlh21** [AvaloniaUI/Avalonia#16826]
### Describe the bug

When attempting this configuration, you will receive the following error in the parent window's XAML on the user control:

`System.InvalidCastException: Unable to cast object of type 'UserControlIssue.ViewModels.MainWindowViewModel' to type 'UserControlIssue.ViewModels.SubViewModel'.`

The user control's DataContext is bound to a SubViewModel property, not a MainWindowViewModel, yet gives the casting error.

### To Reproduce

1. Create a Window with a view model (we'll call it MainViewModel)
2. In the window's constructor, set DataContext to a new instance of MainViewModel
3. Create another view model, call it SubViewModel and give MainViewModel a SubViewModel property
4. Create a UserControl with x:CompiledBindings=true and x:DataType of SubViewModel
5. In the user control's XAML, create a reference to some property of SubViewModel via binding (e.g. a TextBox with Text bound to a string in SubViewModel)
6. In the window's XAML, create an instance of the user control with DataContext bound to MainViewModel's SubViewModel property
7. Construct and show the window
8. Observe the error

If the user control's DataContext is set to be a primitive type like String instead of a sub view model, the issue doesn't occur.

If you disable compiled bindings for the user control, no issue.

If the user control doesn't reference anything from its DataContext view model, no issue.

If the window's constructor doesn't set the DataContext, no issue.

Here's a repository showcasing the issue: https://github.com/Earlh21/UserControlIssue

### Expected behavior

I expected the application to compile and run with no issues and to see the user control in my window.

### Avalonia version

11.1.0

### OS

Windows

**Comment by stevemonaco** [comment]
The repro link cannot be found. Could be private. Can you fix?

**Comment by Earlh21** [comment]
> The repro link cannot be found. Could be private. Can you fix?

It's public now. My bad.

**Comment by timunie** [comment]
For compiled bindings you need to specify `x:DataType` which you forgot to do. This is by design.

**Comment by Earlh21** [comment]
> For compiled bindings you need to specify `x:DataType` which you forgot to do. This is by design.

I'm confused. In the example repo, x:DataType is set for both the user control and the main window. I know I have to set it for compiled bindings, I would be getting a different error if I hadn't.

**Comment by stevemonaco** [comment]
I don't get an error here. I only get runtime logged messages:

```
Exception thrown: 'System.InvalidCastException' in UserControlIssue.dll
[Binding]An error occurred binding 'Text' to 'SubProperty' at 'SubProperty': 'Unable to cast object of type 'UserControlIssue.ViewModels.MainWindowViewModel' to type 'UserControlIssue.ViewModels.SubViewModel'.' (TextBlock #62718864)
```

The `TextBlock` still shows the proper text at runtime, so this may be an issue with logging too early.

The XAML in question is:

```xml
<userControls:SubModelControl DataContext="{Binding SubViewModel}" />
```

The control should be instantiated first using the implicitly inherited `DataContext` (the `MainWindowViewModel`) and directly after the property setters are called (creating the binding). So `SubModelControl` does one update with `MainWindowViewModel` and then at least one update with `SubViewModel`.

I'm not sure any workaround can be done to mitigate the error in this specific pattern.
