### ISSUE TITLE
Emojis are rendered in black and white since version 11.1.0 for certain font weights

### ISSUE THREAD

**Issue by alexanderdeman** [AvaloniaUI/Avalonia#16839]
### Describe the bug

Previously it didn't matter which font weight was used, but since version 11.1.0 only certain font weights render emoji in color.

v11.0.13
![image](https://github.com/user-attachments/assets/b84db1f2-fc5e-4c95-8296-5b6427a1a94c)

v11.1.0
![image](https://github.com/user-attachments/assets/57dde48c-3e34-4835-b917-96257e3de987)

### To Reproduce

	<StackPanel Spacing="10" HorizontalAlignment="Center" VerticalAlignment="Center">
		<Button Content="Black 🥳" Width="120" FontFamily="Segoe UI" FontWeight="Black" />
		<Button Content="Bold 🥳" Width="120" FontFamily="Segoe UI" FontWeight="Bold" />
		<Button Content="DemiBold 🥳" Width="120" FontFamily="Segoe UI" FontWeight="DemiBold" />
		<Button Content="ExtraBlack 🥳" Width="120" FontFamily="Segoe UI" FontWeight="ExtraBlack" />
		<Button Content="ExtraBold 🥳" Width="120" FontFamily="Segoe UI" FontWeight="ExtraBold" />
		<Button Content="ExtraLight 🥳" Width="120" FontFamily="Segoe UI" FontWeight="ExtraLight" />
		<Button Content="Heavy 🥳" Width="120" FontFamily="Segoe UI" FontWeight="Heavy" />
		<Button Content="Light 🥳" Width="120" FontFamily="Segoe UI" FontWeight="Light" />
		<Button Content="Medium 🥳" Width="120" FontFamily="Segoe UI" FontWeight="Medium" />
		<Button Content="Normal 🥳" Width="120" FontFamily="Segoe UI" FontWeight="Normal" />
		<Button Content="Regular 🥳" Width="120" FontFamily="Segoe UI" FontWeight="Regular" />
		<Button Content="SemiBold 🥳" Width="120" FontFamily="Segoe UI" FontWeight="SemiBold" />
		<Button Content="SemiLight 🥳" Width="120" FontFamily="Segoe UI" FontWeight="SemiLight" />
		<Button Content="Thin 🥳" Width="120" FontFamily="Segoe UI" FontWeight="Thin" />
		<Button Content="UltraBlack 🥳" Width="120" FontFamily="Segoe UI" FontWeight="UltraBlack" />
		<Button Content="UltraBold 🥳" Width="120" FontFamily="Segoe UI" FontWeight="UltraBold" />
		<Button Content="UltraLight 🥳" Width="120" FontFamily="Segoe UI" FontWeight="UltraLight" />
	</StackPanel>

### Expected behavior

All emojis to be rendered in color

### Avalonia version

11.1.0+

### OS

Windows

**Comment by stevemonaco** [comment]
Can you try on 11.2.0-beta1 (NuGet preview) or nightly? I can repro the B&W bug for 11.1.3, but 11.2.0-beta1 works for me.

**Comment by alexanderdeman** [comment]
Thank you! I can confirm that version 11.2.0-beta1 resolves the issue.

As a simple workaround, I'm using two separate TextBlock elements.

**Comment by seleborg** [comment]
FYI, I'm seeing the same issue with Avalonia 11.3.2, whereas 11.1.4 does not exhibit the issue for me. Here's a side-by-side screenshot, showing `TextBlock`s with `FontWeight="Bold"` displaying strings that contain emojis. If I disable the style rule that sets the font weight, the emojis are displayed in color.

<img width="1806" height="637" alt="Image" src="https://github.com/user-attachments/assets/6a8df047-b44b-4d26-b85e-724000f44245" />

**Comment by timunie** [comment]
11.3.11 is the latest release available.
