### ISSUE TITLE
LinearGradientBrush behaviour mismatch with WPF

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#1683]
![image](https://user-images.githubusercontent.com/16554748/41666672-9ccc1108-74dd-11e8-90de-ff11d9af8253.png)

The above image was reported by @Splitwirez over at Gitter. Seems like a problem with Relative units.

**Comment by Splitwirez** [comment]
Long story short, WPF's `LinearGradientBrush` uses the target element's dimensions as units for its `StartPoint` and `EndPoint` properties, while Avalonia's version uses units which are either pixels or approximately equal to pixels, atleast at 96 DPI (100% scaling).

Note that while the Avalonia result for an EndPoint of `1,0` may appear black, there is a slight line of grey on the left. That line is the result of the white middle GradientStop being crushed into less than a pixel's width.

The WPF one for EndPoint="0,64" isn't pure black either - the gradient is 64 times the width of the square, so it isn't exactly visible...but while the leftmost visible column is coloured #FF000000, the rightmost visible column is coloured #FF080808, proving that it is present.

Thus far, this is untested at other DPI levels - my screens aren't big enough for that, lol

**Comment by grokys** [comment]
`StartPoint` and `EndPoint` in Avalonia are `RelativePoint`s which mean they can either use pixels or percentages. What happens if you change the Avalonia version to use `EndPoint="100%,0%"`?

**Comment by Splitwirez** [comment]
After changing the `EndPoint` to `100%,0%`...all works as it would in WPF with a value of `1,0`. I'm an idiot. So sorry to bother you folks over a problem that doesn't actually exist... ;~;

**Comment by jmacato** [comment]
We'll definitely need to document these sort of things where WPF and Avalonia differs. Closing this issue now :)
