### ISSUE TITLE
Add stack trace to remote protocol ExceptionDetails

### ISSUE THREAD

**Issue by codecat** [AvaloniaUI/Avalonia#16857]
### Is your feature request related to a problem? Please describe.

We currently don't get any stack trace in the Avalonia designer, meaning that problems are extremely hard to track down. For example, when the designer shows "Invalid markup" (see screenshot):

![image](https://github.com/user-attachments/assets/ab8c6036-0ad8-4fa3-a3f1-c7599e9757e8)

And the Avalonia Diagnostics output shows this:

```
23:00:59.004 [Information] 34320 Connection initialized
23:00:59.773 [Error] 34320 UpdateXamlResult error
System.Xaml.XamlException: Value cannot be null. (Parameter 'control')
```

It's practically impossible to know what really happened here without a stack trace.

### Describe the solution you'd like

If we serialize the stack trace, we can display it in places where it matters.

I believe this commit should do the trick: https://github.com/codecat/Avalonia/commit/607f31febebe8b2e946a4168ac87669eff1e8d95

Then, we can make a change in AvaloniaVS to display the stack trace:

https://github.com/AvaloniaUI/AvaloniaVS/blob/3c210142a90d4a99f682c4df30ad8f6f03baca6f/AvaloniaVS.Shared/Services/PreviewerProcess.cs#L465

(I'm unsure how/if this would display in the Error List tab in AvaloniaVS, but that's probably an issue for that specific repository 😅)

As per contribution guidelines, I am opening an issue first, but I can have a PR ready to go. I assume it also needs some tests?

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/db10780e15c1de4c4d02028b2ce3dfc4a4ace7ab/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs#L243-L247 seems to include the full exception details in Error field.

**Comment by kekekeks** [comment]
ExceptionDetails object was supposed to be there to indicate a particular line number and line position, not to swallow all the info.

**Comment by codecat** [comment]
I see, I must've missed that! In that case, the required change would just be in AvaloniaVS, here:

https://github.com/AvaloniaUI/AvaloniaVS/blob/3c210142a90d4a99f682c4df30ad8f6f03baca6f/AvaloniaVS.Shared/Services/PreviewerProcess.cs#L452-L468

The `ExceptionDetails` is only used if `Error` is null or empty. Okay - I will make a PR there. 😊

**Comment by timunie** [comment]
Thx for your contribution @codecat 👍. This is indeed a very useful info.
