### ISSUE TITLE
IActivatableLifetime does not work anymore on iOS

### ISSUE THREAD

**Issue by Amenti** [AvaloniaUI/Avalonia#16875]
### Describe the bug

`TryGetFeature<IActivatableLifetime>() `always returns null on iOS.

### To Reproduce

Trying to get the feature IActivatableLifetime in `public override void OnFrameworkInitializationCompleted()` doesn't work anymore:

`       
         if (this.TryGetFeature<IActivatableLifetime>() is { } activatableLifetime)
        {
            // This code is never reached
            activatableLifetime.Activated += ActivatableApplicationLifetimeOnActivated;
            activatableLifetime.Deactivated += ActivatableApplicationLifetimeOnDeactivated;
        }
`

Calls to `Application.Current.TryGetFeature<IActivatableLifetime>()` always return null.

### Expected behavior

A working IActivatableLifetime instance.

### Avalonia version

11.1.3

### OS

iOS

### Additional context

This worked in 11.2.999-cibuild0046421-alpha which I used before.

When updating to version > 11.1.3 it has broken. I'll try to narrow the version down.

**Comment by maxkatz6** [comment]
You might need to pass app delegate instance to the UseiOS method.

**Comment by Amenti** [comment]
@maxkatz6 Thanks a lot, this works. I did not know that this call is necessary and didn't read anything in the documentation regarding it. I guess I also must call the equivalents on each platform now.
