### ISSUE TITLE
MVVM Project template for Visual Studio needs update

### ISSUE THREAD

**Issue by alehro** [AvaloniaUI/Avalonia#1688]
For now I have discovered two problems related to DataContext there:
1. Two instances of the same ViewModel: https://github.com/AvaloniaUI/Avalonia/issues/1380
2. The way of assigning of View DataContext to ViewModel is wrong:
`static void Main(string[] args)
{
    BuildAvaloniaApp().Start<MainWindow>(() => new MainWindowViewModel());
}`
Because it leaves the DataContext actually null. Which makes it more confusing is that it is described in help: http://avaloniaui.net/docs/binding/datacontext
The way I found to have the context is adding to WPF:
`<Window.DataContext>  
    <vm:MainWindowViewModel/>   
  </Window.DataContext>`
And the Main function should be:
`static void Main(string[] args)
{
    BuildAvaloniaApp().Start<MainWindow>();//eliminate callback to not have two instances of the same ViewModel 
}`

Sorry for missing new lines in code blocks - didn't find how to make them.

**Comment by Kaev** [comment]
I guess this can be closed after merging https://github.com/AvaloniaUI/AvaloniaVS/pull/83

**Comment by grokys** [comment]
This is very old and the templates have been updated; should be fixed.
