### ISSUE TITLE
WPF DLLs are loaded when EXE is targeting .NET Framework

### ISSUE THREAD

**Issue by gerhard17** [AvaloniaUI/Avalonia#1691]
## Symptoms: 
When starting an EXE targeting the full .NET Framework, three WPF assemblies are loaded: "PresentationFramework", "WindowsBase" and "PresentationCore". This loading is not neccessary and costs at my Workstation aprox 100ms while starting up a small sample application with 6 controls (about 5% startup time).

## Cause:
The System.Windows.Input.ICommand interface was originally member of the PresentationFramework assembly.
Later the ICommand interface was forwarded to System assembly.
Too bad, the ICommand still has attached a TypeConverterAttribut targeting System.Windows.Input.CommandConverter, which is still located in PresentationFramework assembly.

During startup the TypeConverters are evaluated and cause loading these WPF assemblies.

You can see it in this Visual Studio Output when runnig ControlCatalog.Desktop.exe:

```
'ControlCatalog.Desktop.exe' (CLR v4.0.30319: ControlCatalog.Desktop.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Cannot find or open the PDB file.
'ControlCatalog.Desktop.exe' (CLR v4.0.30319: ControlCatalog.Desktop.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Cannot find or open the PDB file.
'ControlCatalog.Desktop.exe' (CLR v4.0.30319: ControlCatalog.Desktop.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Cannot find or open the PDB file.
```

## Possible Fix:
A single change in Portable.Xaml.XamlType (I do not know, if it is a good place, but it works)

```
    virtual XamlValueConverter<TypeConverter> LookupTypeConverter() {
            var t = UnderlyingType;
            if (t == null)
                return null;

#if WPF_COMMAND_CONVERTER_FIX
            // PURPOSE: Prevent loading of WPF PresentationFramework assemblies when compiling against full dotnet framework.
            // TECHNOTE: ICommand is forwarded from PresentationFramework to System, but CommandConverter (TypeConverter) still lives there...
            // Even in dotnet core, but here is the assembly not resolvable.
            // Under dotnet framework fix this with a self written TypeConverter or null.
            // This saves about 100ms / ~5% startup time of a very simple application.
            if (t == typeof(System.Windows.Input.ICommand)) {
                // If we need a TypeConverter return a self written one (e.g. AvaloniaCommandConverter)
                //return SchemaContext.GetValueConverter<TypeConverter>(typeof(AvaloniaCommandConverter), this);
                // If we do not need a TypeConverter, simply return null.
                return null;
            }
#endif //WPF_COMMAND_CONVERTER_FIX

            var converterName = CustomAttributeProvider.GetTypeConverterName(false);
            if (converterName != null)
                return SchemaContext.GetValueConverter<TypeConverter>(Type.GetType(converterName), this);
            ...
    }
```
The original CommandConverter states that it can converts from/to string type. If such a conversion to RoutedCommand is neccessary, Avalonia will have to implement its own WPF agnostic CommandConverter.

## Note:
There is also a ValueSerializer attached, it has the same reference to PresentationFramework, but it seems it is not evaluated in Avalonia. 

Hope this helps!
Avalonia is an impressive Framework!
Regards, Gerhard

**Comment by jmacato** [comment]
Please open up a Pull Request for this so that we can thoroughly check and test the changes you propose! :smile:

**Comment by OmidID** [comment]
I have same problem. when i run the app with normal .Net Framework all the commands stop working.

**Comment by kekekeks** [comment]
We don't use Portable.Xaml anymore
