### ISSUE TITLE
Custom `Window` control does not apply `ControlTheme` of its own type

### ISSUE THREAD

**Issue by Justin113D** [AvaloniaUI/Avalonia#16926]
### Describe the bug

When creating a custom window type that inherits from `Avalonia.Controls.Window` with a `ControlTheme` of its type, the control theme will not apply.

### To Reproduce

1. Create a new desktop project
2. Create a class called `CustomWindow` that inherits from `Window`
3. Change the `MainWindow` type to inherit from `CustomType`
4. Create a resource dictionary file with a control theme named `CustomWindowTheme` that targets `CustomWindow` with `BasedOn={StaticResource {x:Type Window}}`
5. Add setters for e.g. `Background`
6. Add the ControlTheme as a resource to `App.Styles`
7. Use the theme inside `MainWindow` (`Theme={StaticResource CustomWindowTheme}`)

Minimum reproduction project:
[AvaloniaWindowIssue.zip](https://github.com/user-attachments/files/16874620/AvaloniaWindowIssue.zip)

### Expected behavior

Expected behavior: 
The ControlTheme gets applied.

Observed behavior:
- The setters added to the theme do **not** get applied
- Inherited setters from `BasedOn` get applied
- By removing `BasedOn`, all inherited setters get lost and the window has no styling more at all.
- Changing the target type of `CustomWindowTheme` to `Window` will make it work

Screenshots for the minimum reproduction project:
1. How it should be
![image](https://github.com/user-attachments/assets/337a5e40-a567-4dab-8ece-b5d7619b86dd)

2. How it is
![image](https://github.com/user-attachments/assets/32c3270c-feef-4d28-85ab-649327d33832)

### Avalonia version

11.1.3

### OS

Windows

**Comment by rabbitism** [comment]
Custom Window is special, you need to explicitly set the StyleKey to apply it's own theme. 
Example:

```csharp
public class SampleWindow: Window
{
    protected override Type StyleKeyOverride => typeof(SampleWindow);
}
```

**Comment by Justin113D** [comment]
> Custom Window is special, you need to explicitly set the StyleKey to apply it's own theme. Example:
> 
> ```cs
> public class SampleWindow: Window
> {
>     protected override Type StyleKeyOverride => typeof(SampleWindow);
> }
> ```

thank you SO much, this is exactly what i was looking for!
