### ISSUE TITLE
TextBox handles don't work on Android

### ISSUE THREAD

**Issue by Amenti** [AvaloniaUI/Avalonia#16925]
### Describe the bug

No amount of holding and touching shows the Copy/Cut" menu items on a real Android device. I only ever could the "Paste" item to appear. I tried this with the Simple and Fluent themes.

### To Reproduce

- Add a TextBox to a default Avalonia project:

`<TextBox Text="Something"/>`

- Deploy on an Android device
- Try to select text with the finger.

### Expected behavior

A text selection and the subsequent opening of the Copy/Cut/Paste menu.

### Avalonia version

11.1.3 and newest Nightly build 11.2.999-cibuild0051600-alpha

### OS

Android

**Comment by emmauss** [comment]
Works fine in master. The context menu shows up if you hold down for a while, or you tap the selection handles.

**Comment by Amenti** [comment]
Thank you for testing this. Sadly, I really can't get this to work. I attached a very simple sample project. Maybe I'm doing something very wrong.

[TextBoxHandlesTest.zip](https://github.com/user-attachments/files/16898099/TextBoxHandlesTest.zip)

Or is this only supposed to work with a specific Android version possibly? Most of the time I'm testing on an Android 9 (Android One without any vendor additions)

**Comment by emmauss** [comment]
> Thank you for testing this. Sadly, I really can't get this to work. I attached a very simple sample project. Maybe I'm doing something very wrong.
> 
> [TextBoxHandlesTest.zip](https://github.com/user-attachments/files/16898099/TextBoxHandlesTest.zip)
> 
> Or is this only supposed to work with a specific Android version possibly? Most of the time I'm testing on an Android 9 device (Android One without any vendor additions) and the newer Android versions in the emulator, where it's also not working for me.

There's no Android project in what you sent

**Comment by Amenti** [comment]
> > Thank you for testing this. Sadly, I really can't get this to work. I attached a very simple sample project. Maybe I'm doing something very wrong.
> > [TextBoxHandlesTest.zip](https://github.com/user-attachments/files/16898099/TextBoxHandlesTest.zip)
> > Or is this only supposed to work with a specific Android version possibly? Most of the time I'm testing on an Android 9 device (Android One without any vendor additions) and the newer Android versions in the emulator, where it's also not working for me.
> 
> There's no Android project in what you sent

Sorry about that. 🙈 Here with Android:

[TextBoxHandles2.zip](https://github.com/user-attachments/files/16905055/TextBoxHandles2.zip)

**Comment by emmauss** [comment]
I have tried on an android 9 emulator and multiple devices. Text Handles work as expected. Could you send a recording of the issue?

**Comment by Amenti** [comment]
Thanks a lot for your effort. Will do this soon. I'l also try to build the app on a different machine. Maybe my machine has some build problem, who knows...

**Comment by Amenti** [comment]
https://github.com/user-attachments/assets/01339d84-2e5c-4f7a-ae34-8dc05ad6a6e1

I tried another computer (macOS now instead of Windows) and see the same behaviour. Wherever and how long I click, only the Paste menu entry is seen.  Any ideas are appreciated.

**Comment by emmauss** [comment]
Copy and cut are only shown when there's a valid selection. You can't copy an empty selection.

**Comment by Amenti** [comment]
That makes sense but I’m unable to make the selection on the first place.

**Comment by emmauss** [comment]
Double tap the words

**Comment by Amenti** [comment]
Ok now I feel dumb. 🙈 My whole life I’m using the long click on Android to select text. I didn’t even know that the  double click works. Of course on iOS only the double click works. Do you think maybe both methods should work on both OS since there could be other people on Android used to the long click?

**Comment by maxkatz6** [comment]
@Amenti there is an opened issue for that already. https://github.com/AvaloniaUI/Avalonia/issues/16132
