### ISSUE TITLE
Support Theos package .ipa

### ISSUE THREAD

**Issue by ryanryanorient** [AvaloniaUI/Avalonia#16946]
### Is your feature request related to a problem? Please describe.

The [theos](https://github.com/theos/theos) project supports generating and packaging iOS projects without a MAC. It supports objective-C and Swift. Does it support generating ipa files with this project??

### Describe the solution you'd like

new feature request

### Describe alternatives you've considered

new feature request

### Additional context

new feature request

**Comment by emmauss** [comment]
We use dotnet to create and publish avalonia. If theos supports publishing dotnet ios projects, then it should work with avalonia. Build systems and packaging are the responsibilities of the dev, and no Avalonia.
