### ISSUE TITLE
Content Control Datatemplate binding

### ISSUE THREAD

**Issue by AWAS666** [AvaloniaUI/Avalonia#16950]
### Describe the bug

I have this weird bug where adding a primitive type onto a content control only binds one way to the datatemplate, not two way, no matter what I try

### To Reproduce

this will only bind one way:
```
<ContentControl Content="{Binding Value}" Width="100" VerticalAlignment="Center">
		<ContentControl.DataTemplates>
			<DataTemplate DataType="{x:Type x:String}">
				<TextBox Text="{Binding }"/>
			</DataTemplate>
			<DataTemplate DataType="{x:Type x:Boolean}">
				<CheckBox IsChecked="{Binding Mode=TwoWay}"/>
			</DataTemplate>
		</ContentControl.DataTemplates>
</ContentControl>
```

my temporary workaround to make it work:
```
<ContentControl Content="{Binding Value}" Width="100" VerticalAlignment="Center">
	<ContentControl.DataTemplates>
		<DataTemplate DataType="{x:Type x:String}">
			<TextBox Text="{Binding $parent[UserControl].((vm:PropertyViewModel)DataContext).Value}"/>
		</DataTemplate>
		<DataTemplate DataType="{x:Type x:Boolean}">
			<CheckBox IsChecked="{Binding $parent[UserControl].((vm:PropertyViewModel)DataContext).Value, Mode=TwoWay}"/>
		</DataTemplate>
	</ContentControl.DataTemplates>
</ContentControl>
```

the workaround for me is basically bind back to the view model that is the data context, in that case it will bind two ways again.

at first I assumed it's just an issue with bools and the checkbox, but it's the same for strings and the textbox

### Avalonia version

11.1.3

### OS

Windows

**Comment by stevemonaco** [comment]
Don't use primitive types as the `DataContext` if you expect to mutate it. Always bind to properties when mutating (in this case, by the control). Why?

1. Strings are immutable. When "modifying" a string, you're assigning a different string instance to a local variable, property, field, etc. `{Binding}` lacks this information and is conceptually working with something closer to `this`.
2. Value types are copied by value. So even if you could mutate it, it's not necessarily the same memory location.

**Comment by AWAS666** [comment]
> Don't use primitive types as the `DataContext` if you expect to mutate it. Always bind to properties when letting a control mutate binded state. Why?
> 
>     1. Strings are immutable. When "modifying" a string, you're assigning a different string instance to a local variable, property, field, etc. `{Binding}` lacks this information and is conceptually working with something closer to `this`.
> 
>     2. Value types are copied by value. So even if you could mutate it, it's not necessarily the same memory location.

yeah I'm aware of that, I just sorta expected it to behave differently in this case, so it seemed off to me

**Comment by timunie** [comment]
That's by design. TwoWay bindings can't edit the bound object, but only Properties of that object.
