### ISSUE TITLE
Android: Crashes and oddities with shortcuts on external keyboards

### ISSUE THREAD

**Issue by Amenti** [AvaloniaUI/Avalonia#16961]
### Describe the bug

- Use a mobile device or emulator (I tested this with Android but saw similar problems with iOS in the past)
- Add a `<TextBox />`
- Connect an external keyboard

### To Reproduce

The following shortcuts/behaviors behave oddly:

- Select some text via "Left + Shift" -> Crash
- Select some text via "Right + Shift", hit "Left" -> selection doesn't change
- Ctrl + Left/Right -> No word jump

### Avalonia version

11.1.3 + Nightly Builds

### OS

Android

**Comment by maxkatz6** [comment]
Stacktrace or logcat-logs would be useful.
