### ISSUE TITLE
The textbox control does not display when used as an Adorner

### ISSUE THREAD

**Issue by maoyy** [AvaloniaUI/Avalonia#16977]
The textbox control does not display when used as an Adorner。Replacing the textbox with a textblock or button control will display it normally。

Avalonia version：11.1.3
operating system：windows10

test code:
var text = new TextBox(); //TextBlock
text.Text = "asdfasdfsdf";
text.Background = Brushes.Red;
text.Width = 10;
text.Height = 10;

AdornerLayer.SetAdorner(this, text);
AdornerLayer.SetIsClipEnabled(text, false);

Sorry, I'm not very good at operating GitHub

**Comment by stevemonaco** [comment]
I can only repro when trying to adorn a `Window` (which may or may not be a supported use case). The adorner shows for any other case I've tried: a `UserControl` that creates + attaches the adorner to itself and creating+attaching the adorner to a child `StackPanel`.

Can you create a minimal repro and post the project?

**Comment by maoyy** [comment]
thanks for your answer
i create a project that Similar to my project，it Reproduce the fault
wpf project is normal
thanks
[test.zip](https://github.com/user-attachments/files/16972300/test.zip)

**Comment by maoyy** [comment]
I'm sorry

Because my custom panel is incorrect, the textbox is not displaying. I will study again. Thank you

**Comment by maoyy** [comment]
A new problem has been discovered.
The TestText Box control inherits from the Text Box and does not display when using it as a decorator. I have created a test project, thank you
[test.zip](https://github.com/user-attachments/files/16977540/test.zip)

**Comment by maoyy** [comment]
Thank you
I uploaded the project, but I don't know why it hasn't.
I used StyleKeyOverride，I'll stick out the code。

test code:

public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();


        var testPanel = new TestPanel();
        testPanel.Width = 600;
        testPanel.Height = 500;

        this.Content = testPanel;
    }
}

public class TestPanel : Panel
{
    public TestPanel()
    {
        Background = Brushes.Red;

        var testControl = new TestControl();
        testControl.Width = 200;
        testControl.Height = 200;

        this.Children.Add(testControl);
    }
}

public class TestControl : Control
{
    public TestControl() 
    {
        this.PointerEntered += TestControl_PointerEntered;
    }
    public override void Render(DrawingContext context)
    {
        context.DrawRectangle(Brushes.Transparent, new Pen(Brushes.Black, 1), new Rect(0, 0, Width, Height));
    }
    private void TestControl_PointerEntered(object? sender, Avalonia.Input.PointerEventArgs e)
    {
        var text = new TextBox();//TextBox
        text.Text = "asdfasdfsdf";
        text.PointerExited += Text_PointerExited;

        AdornerLayer.SetAdorner(this, text);
        AdornerLayer.SetIsClipEnabled(text, false);
    }
    private void Text_PointerExited(object? sender, Avalonia.Input.PointerEventArgs e)
    {
        AdornerLayer.SetAdorner(this, null);
    }
}

public class TestTextBox : TextBox
{
    protected override Type StyleKeyOverride => base.StyleKeyOverride;
    public TestTextBox() { }
}

thank you very much
