### ISSUE TITLE
Add inherent DI support

### ISSUE THREAD

**Issue by glennblock** [AvaloniaUI/Avalonia#17]
Being that this is a new stack, it would be great is if was designed with IoC in mind from the get go.

This means ideally then runtime and all its components can be constructed via a container. Custom user components like controls could have dependencies injected as well, all via ctor injection.

I would recommend looking to Fubu MVC and also ASP.NET MVC/Web API for inspiration.

**Comment by nerdshark** [comment]
These are just a few really general examples, but making Perspex DI-friendly would make it really easy to build composable application shells, such as:
* [Gemini](https://github.com/tgjones/gemini)
* [Wide](https://github.com/chandramouleswaran/Wide)
* [Orchestra](https://github.com/WildGums/Orchestra)

Not only would having DI support baked in (whether through a specific framework, or via an interface implemented by the user) make it easier to build composable applications, it would make it easier to build applications that gain reliability through running parts of the application in separate processes, like how Chrome runs each browser tab in a separate process. [Baktun Shell](http://www.ikriv.com/dev/wpf/BaktunShell/) is an example of this in .NET.

**Comment by grokys** [comment]
Thanks for your input @nerdshark. Is there anything in particular that you think is missing today, or could be implemented today? I'd like to hear some more concrete proposals surrounding this.

**Comment by glennblock** [comment]
I will try to find some cycles to give you an illustration of what I mean.
