### ISSUE TITLE
Status bar color not changing color as specified by the style in style.xml. Avalonia 11.1.0 Android 11 API30 - Android 12 API31

### ISSUE THREAD

**Issue by Nemonek** [AvaloniaUI/Avalonia#17003]
### Describe the bug

As said in the title, when using the following code in the styles.xml file the status bar color does not change as it's supposed to.
Instead, on Android 12 API31 the status bar remains white, even if the following line of code is applied in both MyTheme.NoActionBar and MyTheme.Main. On Android 11 API30, when specified, the status bar color changes only for the splash screen, and not for the whole application. Again, the color change is in both theme also for the Android 11 version.
Below the line I used based on [documentation](https://developer.android.com/design/ui/mobile/guides/foundations/system-bars?hl=it):
``` xml
<item name="android:statusBarColor">@android:color/holo_blue_bright</item>
```
Here's a screenshot on Android 11 API30:
![Screenshot_2024-09-13-09-25-19-48_f6399c510db824fecaf291ff47a3ec2d](https://github.com/user-attachments/assets/dd80926a-880e-4440-bad5-32518fbbd083)

### To Reproduce

Create an Avalonia.xplat project, open the styles.xml file depending on what API level you're using, try to change the status bar color.

### Expected behavior

The expected behavior is for it to change color to the one specified.

### Avalonia version

11.1.0

### OS

Android

**Comment by J0nathan550** [comment]
Use this code my friend:

Subscribe to the MainView of your event to `Loaded` and use this:

`MainView.xaml.cs`:
```cs
    private void UserControl_Loaded(object? sender, RoutedEventArgs e)
    {
        if (OperatingSystem.IsAndroid())
        {
            var insetsManager = TopLevel.GetTopLevel(this).InsetsManager;
            insetsManager.SystemBarColor = Colors.Black;
            insetsManager.DisplayEdgeToEdge = true;
        }
    }
```
