### ISSUE TITLE
Window with SystemDecorations set to "BorderOnly"  or "None" cannot be resized. 

### ISSUE THREAD

**Issue by zhanxh** [AvaloniaUI/Avalonia#17008]
### Describe the bug

Window with SystemDecorations set to "BorderOnly"  or "None" cannot be resized. 
Avalonia Version 11.1.0

### To Reproduce

        <Setter Property="WindowStartupLocation" Value="CenterOwner" />
        <Setter Property="ExtendClientAreaChromeHints" Value="NoChrome"></Setter>
        <Setter Property="ExtendClientAreaToDecorationsHint" Value="True" />
        <Setter Property="ExtendClientAreaTitleBarHeightHint" Value="-1" />
        <Setter Property="SystemDecorations" Value="None" />

### Avalonia version

11.1.0

### OS

Windows, Linux

### Additional context

no

**Comment by timunie** [comment]
If you remove the system border it's up to you to add the functionality as needed. That's by design imo
