### ISSUE TITLE
EMF/WMF File support

### ISSUE THREAD

**Issue by jogibear9988** [AvaloniaUI/Avalonia#17010]
### Is your feature request related to a problem? Please describe.

These File types are supported in WPF

### Describe the solution you'd like

Same as in WPF

**Comment by timunie** [comment]
Are these fileformats not Windows specific? I refer to https://docs.fileformat.com/image/emf/ this page for example. 

As Avalonia is a cross platform library this limitation makes it hard to undoable for us. 3rd party controls could still render it on Windows if they want to.

**Comment by jogibear9988** [comment]
Here is a description of the format
https://formats.kaitai.io/wmf/csharp.html

Found this, wich seems to render to svg
https://github.com/tbluemel/rtf.js/blob/master/src/emfjs/Renderer.ts

Maybe I'll take a look to convert this to C#, so I could use Avalonia.Avg and display it

**Comment by Gillibald** [comment]
These formats are Windows specific so there are no plans to support them

**Comment by jogibear9988** [comment]
I now convert them to SVG using https://github.com/dlemstra/Magick.NET
