### ISSUE TITLE
WASM issue using dotnet-serve

### ISSUE THREAD

**Issue by houstonhaynes** [AvaloniaUI/Avalonia#17036]
### Describe the bug

FYI - I'm running into an issue with `dotnet serve` per the [instructions](https://docs.avaloniaui.net/docs/guides/platforms/how-to-use-web-assembly). This is confirmed when running dotnet-serve on either Windows or Linux - I get a "nice clean" console in the browser with no issues but the screen is simply blank after loading (the index.html pre-load/splash page loads as expected). 

Running locally from JetBrains Rider or `dotnet run` from the command line is fine, BTW. It's only when serving from the AppBundle 

Avalonia 11.1.0
dotnet sdk 8.0.4

![Screenshot 2024-09-16 133856](https://github.com/user-attachments/assets/0aea074e-71a2-41c0-940f-62593efc7d7e)

### To Reproduce

```pwsh
dotnet publish -p:CompressionEnabled=false 
dotnet serve -d:./bin/Release/net8.0-browser/browser-wasm/AppBundle --port 5000 --address any 
```

### Expected behavior

load of WASM page in browser

### Avalonia version

11.1.0

### OS

Windows, Linux, WebAssembly

### Additional context

running from command line `dotnet run` is fine.

**Comment by maxkatz6** [comment]
I just updated documentation to mention correct `dotnet publish` output path used in `dotnet serve`
https://docs.avaloniaui.net/docs/guides/platforms/how-to-use-web-assembly#deployment

Also tried to reproduce this problem with correct output path, but couldn't.
If it's still reproducible for you, can you attach a minimal repro?

**Comment by houstonhaynes** [comment]
Thanks so much for looking into this. We had to go to SAFEr stack for the primary web interface, but I may still use Avalonia for the admin console. If anything, it will be a valid exercise for deployment in the cloudflare pages, which we still have to sort out for this particular client.
