### ISSUE TITLE
Setting WindowStartupLocation doesn't work for different Width/Height values

### ISSUE THREAD

**Issue by RayyanTahir** [AvaloniaUI/Avalonia#1704]
Setting `WindowStartupLocation="CenterScreen"` works perfectly if Width/Height of window are set to default (or not set at all). But if you change the width and height to any value other than the default then the window does not start at the specified location. I have attached a repro below:

**Repro** - tested with latest pre-release  build 5547
[WindowStartupLocationRepro.zip](https://github.com/AvaloniaUI/Avalonia/files/2140130/WindowStartupLocationRepro.zip)

**Comment by grokys** [comment]
ping @jp2masa as you wrote the `WindowStartupLocation` feature!
