### ISSUE TITLE
TextBox in Expandable.Header Captures Space Input

### ISSUE THREAD

**Issue by TosiRikhard** [AvaloniaUI/Avalonia#17055]
### Description
When placing a TextBox control within an Expandable.Header, the space key input is captured by the Expandable Control. This causes the Expandable control to unexpectedly collapse or uncollapse instead of inserting a space character in the TextBox.

### To Reproduce
1. Create a new Avalonia application
2. Add an Expandable control to your XAML
3. Place a TextBox control within the Expandable.Header
4. Run the application
5. Click on the TextBox to focus it
6. Try to type a space character

### Expected behavior
The space character should be inserted into the TextBox without affecting the Expandable control's state.

### Actual Behavior
The space key input causes the Expandable control to collapse or uncollapse, and no space character is inserted into the TextBox.

### Avalonia version

11.1.3

### OS

Windows

### Additional context

A workaround can been implemented by placing the TextBox inside the Expandable content and binding its value to a TextBlock in the header. However, this is not an ideal solution and complicates the UI structure.
This issue is particularly problematic when trying to provide descriptive names for UI elements that end users can edit. The current behavior significantly hampers usability and creates a counter-intuitive user experience.

**Comment by MrJul** [comment]
Can you please try Avalonia 11.2.0-beta2?
This should have been fixed by #16619.

**Comment by TosiRikhard** [comment]
Works great with suggested beta. Thanks.
