### ISSUE TITLE
Path parse errors

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#1708]
the following path from the visual studio image lib no longer parses

Could not convert object 'F1M9.0771,11C9.1161,10.701,9.1801,10.352,9.3031,10L9.0001,10 9.0001,6.166 3.0001,9.767 3.0001,10 9.99999999997669E-05,10 9.99999999997669E-05,0 3.0001,0 3.0001,0.234 9.0001,3.834 9.0001,0 12.0001,0 12.0001,8.062C12.1861,8.043 12.3821,8.031 12.5941,8.031 15.3481,8.031 15.7961,9.826 15.9201,11L16.0001,16 9.0001,16 9.0001,12.562 9.0001,11z' (of type System.String) to {clr-namespace:Avalonia.Media;assembly=Avalonia.Visuals}Geometry: Invalid double value

to repro use https://github.com/ahopper/Avalonia.IconPacks with v0.6.2-build5555-beta

**Comment by ahopper** [comment]
It appears the new parser does not like the E notation on numbers ( 9.99999999997669E-05), the visual studio image lib uses these lots!

**Comment by Gillibald** [comment]
Have fixed it and will create a PR later this day.

**Comment by ahopper** [comment]
I think it needs to support lowercase e
Could not convert object 'M 10.9041,8.42781L 11,8C 11,7.44772 10.5523,7 10,7L 4.92592,7.00001L 5.84748,3.56073L 5.85238,3.54243C 5.94159,3.20888 5.85526,2.83821 5.59356,2.57652L 1.585,6.58508L 1.58577,6.58585C 1.22384,6.94778 0.999981,7.44778 0.999981,8.00007L 0.999996,12C 0.999996,13.1046 1.89543,14 3,14L 7,14C 7.79733,14 8.48568,13.5334 8.80693,12.8584L 8.80481,12.8574L 10.9041,8.42781 Z M 7,15L 3,15C 1.34315,15 0,13.6569 0,12L -1.01725e-005,8.00006C -1.01725e-005,7.17257 0.335012,6.42333 0.87682,5.88058L 5.59355,1.16233L 6.30065,1.86943C 6.83373,2.40249 7.00298,3.16158 6.80841,3.83818L 6.22915,6.00002L 10,6.00001C 11.1046,6.00001 12,6.89544 12,8C 12,8.34024 11.915,8.66063 11.7652,8.94112L 9.76384,13.1687C 9.30819,14.2449 8.24227,15 7,15 Z M 12.0959,16.5722L 12,17C 12,17.5523 12.4477,18 13,18L 18.0741,18L 17.1525,21.4393L 17.1476,21.4576C 17.0584,21.7911 17.1447,22.1618 17.4064,22.4235L 21.415,18.4149L 21.4142,18.4142C 21.7762,18.0522 22,17.5522 22,16.9999L 22,13C 22,11.8954 21.1046,11 20,11L 16,11C 15.2027,11 14.5143,11.4666 14.1931,12.1416L 14.1952,12.1426L 12.0959,16.5722 Z M 16,10L 20,10C 21.6568,10 23,11.3431 23,13L 23,16.9999C 23,17.8274 22.665,18.5767 22.1232,19.1194L 17.4064,23.8377L 16.6993,23.1306C 16.1663,22.5975 15.997,21.8384 16.1916,21.1618L 16.7708,19L 13,19C 11.8954,19 11,18.1046 11,17C 11,16.6598 11.085,16.3394 11.2348,16.0589L 13.2362,11.8313C 13.6918,10.7551 14.7577,10 16,10 Z ' (of type System.String) to {clr-namespace:Avalonia.Media;assembly=Avalonia.Visuals}Geometry: Invalid double value
from the materialLight mahapps import

**Comment by Gillibald** [comment]
Just checked. You're right lower case e is also valid. Will fix that tomorrow.
