### ISSUE TITLE
Minimize Button is not working in MacOS Sequoia Version 15.0

### ISSUE THREAD

**Issue by mail2mhossain** [AvaloniaUI/Avalonia#17083]
### Describe the bug

We are using Avalonia, Avalonia.Desktop, and Avalonia.ReactiveUI. All are version 11.1.3.

In MacOS Sonoma Version 14.6.1, minimize button is working BUT in MacOS Sequoia Version 15.0, minimize button is not working

### To Reproduce

Run AvaloniaUI in MacOS Sequoia Version 15.0.

### Expected behavior

Should minimize the UI

### Avalonia version

11.1.3

### OS

macOS

**Comment by Amenti** [comment]
This also happens when using the Nightly Builds.

**Comment by BaseHead** [comment]
Yes we are seeing this also with macOS 15 and our users on macOS12 it's even worse.  Their whole UI freezes.  Super bad one.  8(

**Comment by MrJul** [comment]
Fixed by #17181.

**Comment by mail2mhossain** [comment]
Waiting for public release in NuGet

**Comment by grokys** [comment]
Fixed in 11.1.4.

**Comment by BaseHead** [comment]
Sweetness!  Thx man!

**Comment by mail2mhossain** [comment]
We have upgraded our application to version 11.1.4. Minimized issue is resolved. 

Currently, we use the following method to capture key events and close the view when the Escape key is pressed:

```csharp
private void Window_KeyDown(object? sender, KeyEventArgs e)
{
    if (e.Key == Key.Escape)
    {
        Close();
    }
}
```

Previously, this functionality worked as expected. In version 11.1.4, it continues to work on Windows; however, it now crashes on macOS.

The error report indicates that our application encounters a segmentation fault (`EXC_BAD_ACCESS (SIGSEGV)`) due to invalid memory access. The crash occurs in the `libAvaloniaNative.dylib` library within the `keyDown` method, suggesting there may be an issue with how keyboard events are handled or with memory access related to UI elements on macOS.
