### ISSUE TITLE
IStorgeProvider not returning Download WellKnownFolders on Windows 11

### ISSUE THREAD

**Issue by jm-abellan** [AvaloniaUI/Avalonia#17086]
### Describe the bug

Hi
I am trying to get the Download folder from the IStorageProvider
I am working on a Windows 11 machine

Although I can get the the Desktop or Documents folder, the TryGetWellKnownFolderAsync fails when asking for Downloads folder

### To Reproduce

var downloadsFolder = await storageProvider.TryGetWellKnownFolderAsync(knownFolder);

Above sentence returns null in my Windows 11 machine

### Expected behavior

It should return the downloads folder as it does with Documents or Desktop WellKnownFolders

### Avalonia version

11.2.999-cibuild0051993-alpha

### OS

Windows

**Comment by stevemonaco** [comment]
Adding some context from Telegram.

This appears to be an issue with Avalonia's P/Invoke signature for `SHGetKnownFolder`:

https://github.com/AvaloniaUI/Avalonia/blob/2299d96f9851aaf9b3ccc5390d69b6e8d6f877a0/src/Avalonia.Base/Platform/Storage/FileIO/BclStorageProvider.cs#L152-L153

The actual win32api signature returns an HRESULT and has 4 parameters, so I'm not sure if there's any magic I'm missing.

I've fixed it in the following repro on nightly version:

```cs
public static partial class NativeMethods
{
    [LibraryImport("shell32.dll", SetLastError = false, StringMarshalling = StringMarshalling.Utf16)]
    public static partial int SHGetKnownFolderPath(
        in Guid rfid,
        uint dwFlags,
        IntPtr hToken,
        out string ppszPath);

    public static Guid DownloadGuid { get; } = new Guid("374DE290-123F-4565-9164-39C4925E467B");
}
```

[Issue17086Repro.zip](https://github.com/user-attachments/files/17090884/Issue17086Repro.zip)

![downloadfolderissue](https://github.com/user-attachments/assets/baa68eae-7184-4367-a4a0-ef725f6d34d9)

I can PR if maintainers want (and change to using `DllImport`).

**Comment by maxkatz6** [comment]
To avoid runtime dllimport marshalling, it should be something like
```
 [DllImport("shell32.dll")] 
 private static extern int SHGetKnownFolderPath([MarshalAs(UnmanagedType.LPStruct)] Guid id, int flags, IntPtr token, IntPtr* ppszPath); 
```

And then used via 
```
IntPtr result;
if (SHGetKnownFolderPath(s_folderDownloads, 0, IntPtr.Zero, &result))
{
    return Marshal.PtrToStringUni(result);
}
```

**Comment by jpmikkers** [comment]
@maxkatz6 shouldn't result be freed then before returning?

**Comment by stevemonaco** [comment]
I will PR this.

@jpmikkers Yes, it requires `Marshal.FreeCoTaskMem` even when the method fails. 🤷‍♂️

**Comment by orchardpark** [comment]
It's a recent problem. This did not used to occur on Avalonia 11.0.7.
