### ISSUE TITLE
InjectAvaloniaXamlOutput appears to mangle property IntermediateAssembly on multiple runs and prevents trimming

### ISSUE THREAD

**Issue by noorez** [AvaloniaUI/Avalonia#17099]
### Describe the bug

(For some reason this only appears on android builds..)

It looks like when InjectAvaloniaXamlOutput build target is run multiple times (for this case: (target "InjectAvaloniaXamlOutput" depends on it):)  which has already run because "Compile" target required it, the path becomes mangled.

```
CompileAvaloniaXamlInputs=
 816620                            obj/Release/net8.0-android/Avalonia/project.dll
 816621                                    AvaloniaCompileOutput=obj/Release/net8.0-android/Avalonia/Avalonia/project.dll
```

notice how there are now two /Avalonia/Avalonia nested directories when in fact all the build objects are only in Avalonia.

This in turn causes the trimmer targets to not look in the correct location for the assemblies which need to be trimmed

### To Reproduce

Compile android targets when trimming enabled.

### Expected behavior

previous version on which this worked without issue for me 11.1.999-cibuild0045786-beta. expect that it should also work in recent versions too.

### Avalonia version

11.1.2

### OS

Android

**Comment by timunie** [comment]
Can you try latest nightly in a minimum sample? If it still is a bug for you, share the minimum sample please.

**Comment by TomEdwardsEnscape** [comment]
The issue will be that `PrepareToCompileAvaloniaXaml` is running multiple times. But a target is not supposed to run twice.

In addition to a code sample, please compile with binary logging enabled and attach the `.binlog` output. Sample command: `dotnet build -bl:MyLog.binlog`.

**Comment by noorez** [comment]
https://github.com/noorez/AvaloniaTest17099 Test code which reproduces the issue

**Comment by noorez** [comment]
[MyLog.log](https://github.com/user-attachments/files/17154248/MyLog.log)
attached the binlog requested.

Note, this didn't appear to produce any errors on output,  however, Visual Studio and also msbuild from the console do produce the error

**Comment by noorez** [comment]
I think what might be throwing off the msbuild target is the <ApplicationIcon> directive in the android project you can see in the test project I uploaded...

**Comment by TomEdwardsEnscape** [comment]
This is the problem: it's running inner builds, and overriding the path to the intermediate assembly with its own value:

![image](https://github.com/user-attachments/assets/8c162051-5eb4-47e2-8cd3-8449f8888f79)

The good news is that it also configures the `SkipCompilerExecution` property. We should be respecting this anyway, but aren't. By skipping the Avalonia XAML targets when that property is true we should be able to fix the issue.

**Comment by TomEdwardsEnscape** [comment]
Please try with the build from the linked PR (once it has been generated).

**Comment by noorez** [comment]
pushed update to my test project to show that it works now (it also builds correctly on the actual project)

**Comment by noorez** [comment]
while the issue with building was fixed and it produced the various android binaries,  the app crashed, and this was taken from adb.  It appears that perhaps the patch skipped too much when trying to avoid the additional transformation of the msbuild properties? 

```
9-27 10:09:17.197 14531 14531 E AndroidRuntime: Process: air.com.myapp, PID: 14531
09-27 10:09:17.197 14531 14531 E AndroidRuntime: android.runtime.JavaProxyThrowable: [Avalonia.Markup.Xaml.XamlLoadException]: No precompiled XAML found for myapp.Client.App, make sure to specify x:Class and include your XAML file as AvaloniaResource
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Unknown Source:0)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at myapp.Client.App.Initialize(Unknown Source:0)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at Avalonia.AppBuilder.SetupUnsafe(Unknown Source:0)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at Avalonia.AppBuilder.Setup(Unknown Source:0)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at Avalonia.AppBuilder.SetupWithLifetime(Unknown Source:0)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at Avalonia.Android.AvaloniaMainActivity.InitializeAvaloniaView(Unknown Source:0)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at Avalonia.Android.AvaloniaActivity.OnCreate(Unknown Source:0)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at PasswordServer.Client.Android.MainActivity.OnCreate(Unknown Source:0)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(Unknown Source:0)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(Unknown Source:0)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at crc64ef7a11524a16ed7d.MainActivity.n_onCreate(Native Method)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at crc64ef7a11524a16ed7d.MainActivity.onCreate(MainActivity.java:41)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8975)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8944)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8918)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
09-27 10:09:17.197 14531 14531 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by TomEdwardsEnscape** [comment]
Please send another .binlog.

**Comment by TomEdwardsEnscape** [comment]
I think I finally found where thing go wrong. First, the project is built and everything is fine. Then the Android SDK executes a target of its own called `_ResolveAssemblies`, which sets properties including `SkipCompilerExecution` and `_OuterIntermediateAssembly` and executes a project target which computes a list of files to publish.

As part of this second build, `CopyFilesToOutputDirectory` executes.  But because of `SkipCompilerExecution`, we haven't replaced the original assembly with the one containing Avalonia XAML compilation...and despite being passed to the project, the value of `_OuterIntermediateAssembly` has NOT been applied, so the pre-XAML assembly is copied to the bin folder and used for the rest of the build.

This seems to be the root cause of the problem: the SDK sometimes applies this `_OuterIntermediateAssembly` value (causing the double-correction of the path if we inject our files) and at other times doesn't (causing the pre-XAML assembly to be copied to the output folder if we don't inject our files).

Either way something breaks.

**Comment by noorez** [comment]
any updates on how this can be fixed?

**Comment by TomEdwardsEnscape** [comment]
I've not done anything more. Been busy with my actual job, and I'm also not well-placed to work on the issue as I don't have any of the bloated dependencies required to build and run Android applications.

@MrJul please reopen this issue.
