### ISSUE TITLE
Reduce Shader Jank

### ISSUE THREAD

**Issue by jhimes144** [AvaloniaUI/Avalonia#17104]
### Is your feature request related to a problem? Please describe.

When an Avalonia app rich with animations first opens, there is noticeable lag and stuttering with these animations on first run. This suboptimal experience continues until the user interacts enough with the UI until which point where all the shaders have had a chance to compile. For instance, the first time a modal opens it will stutter, but afterwards its fine.

### Describe the solution you'd like

It would be nice if Avalonia had some sort of way to compile shaders at app start. Flutter (uses a skia backend) had the same issue. There solution to it is found here https://docs.flutter.dev/perf/shader

Over the years, Avalonia's performance has continue to improve. Its animation performance is beginning to rival that of UI solutions marketed towards games and real time apps, like NoesisGUI. I believe addressing shader jank would be the final nail.

**Comment by maxkatz6** [comment]
> When an Avalonia app rich with animations first opens, there is noticeable lag and stuttering with these animations on first run.

I would be confident, it's caused by JIT, and less so by shaders.
And, for instance, R2R or AOT normally noticeably improve this experience. 

Or do you have any specific hints that it's actually skia shaders.

**Comment by jhimes144** [comment]
@maxkatz6 

Looks like I can confirm that switching the compilation to AOT or R2R fixes this issue. Thanks for the information!
