### ISSUE TITLE
UI Frozen or don't work when the Minimize button is clicked on macOS

### ISSUE THREAD

**Issue by xingxing21** [AvaloniaUI/Avalonia#17120]
### Describe the bug

UI is frozen or don't work when the Minimize button of Window is clicked.
I'm developing the cross-platform application for the Windows and macOS.
I'm using the 11.1.0-rc2 but UI is frozen when the minimize button is clicked on macOS 12.
So I cloned your sample code from AvaloniaUI git repository on macOS 12 and faced same issue.
I tested the 11.1.0-rc2 and the latest version on macOS 15 and clicking the minimize button don't working with two Avalonia Version.

### To Reproduce

- click the Minimize button of Window

### Expected behavior

- the Window have to be minimized and put on Task bar on macOS

### Avalonia version

one is latest, another 11.1.0-rc2

### OS

macOS

**Comment by MrJul** [comment]
Should be fixed by #17181.
