### ISSUE TITLE
Unable to make error validation visible...

### ISSUE THREAD

**Issue by trashhacker** [AvaloniaUI/Avalonia#17128]
### Describe the bug

Error validation is not visible / indicated.
![Screenshot 2024-09-25 205220](https://github.com/user-attachments/assets/ff0c78ec-9577-4567-8b38-06bf12734d1b)

its working for the TextBox but not for my usercontrol, what do i miss?

### To Reproduce

Im using the INotifyDataErrorInfo interface for property value validation in combination with ValidatinAttributes for the differenct errors and messages (evalutating the attributes in viewmodel and raising ErrorsChanged). But its not visible.
Do i miss something?

### Avalonia version

11.1.3

**Comment by timunie** [comment]
@trashhacker don't ask questions as a bug report please. 🙏 Thx.

To answer your question: please have a look at Avalonia.Samples > RatingControlSample how we did add validation there.

**Comment by trashhacker** [comment]
Sorry.. cant find RatingControlSamples

**Comment by timunie** [comment]
https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src%2FAvalonia.Samples%2FCustomControls%2FRatingControlSample
