### ISSUE TITLE
ViewLocator doesn't work in the browser.

### ISSUE THREAD

**Issue by lukewire129** [AvaloniaUI/Avalonia#17147]
### Describe the bug

![image](https://github.com/user-attachments/assets/7803f220-9bfa-4d3e-9c0d-d6bbb8e1acda)

### To Reproduce

```xml
<!-- MainView.xaml-->
<Grid RowDefinitions="51, *">
    <StackPanel  Orientation="Horizontal">
            <Button Command="{Binding ScrrenCommand}" CommandParameter="0">Home</Button>
            <Button Command="{Binding ScrrenCommand}" CommandParameter="1">Home</Button>
    </StackPanel>
    <ContentControl Grid.Row="1" Content="{Binding CurrentViewModel}" />
</Grid>
```
`ViewModels` Add files to the folder(AViewModel, BViewModel) 
```csharp
// AViewModel.cs
public class AViewModel :ViewModelBase
{
    
}

// BViewModel.cs
public class BViewModel :ViewModelBase
{
    
}
```

![image](https://github.com/user-attachments/assets/dc4a5338-ccf2-4030-b479-30881959bd79)

`Views` Add files to the folder(AView, BView) 
![image](https://github.com/user-attachments/assets/83d8b76a-05c5-4a58-8471-9cfe41c9ac13)

// MainViewModel.cs
```csharp
public partial class MainViewModel : ViewModelBase
{
    [ObservableProperty] private string _greeting = "Welcome to Avalonia!";
    [ObservableProperty] List<ViewModelBase> _viewModels = null!;
    [ObservableProperty] ViewModelBase _currentViewModel = null!;

    public MainViewModel()
    {
        ViewModels = [new AViewModel(), new BViewModel()];
        ScrrenCommand.Execute("0");
    }
    [RelayCommand]
    private void Scrren(string idx)
    {
        this.CurrentViewModel = ViewModels[Convert.ToInt32((idx))];
    }
}
```

### Expected behavior

This is a normal ViewLocator implementation in Windows or Android, but in WebAssembly, when I take a Console.log through Dev Tools on the web, I get the above error message.

### Avalonia version

11.1.3

### OS

WebAssembly

**Comment by stevemonaco** [comment]
The default reflection-based ViewLocator does not work when trimming or AoT is enabled, which is typical for mobile and WASM platforms.

**Comment by lukewire129** [comment]
> The default reflection-based ViewLocator does not work when trimming or AoT is enabled, which is typical for mobile and WASM platforms.

So, should we do it the way we did with ReactiveUI? [Example](https://docs.avaloniaui.net/docs/concepts/reactiveui/routing)

**Comment by workgroupengineering** [comment]
See https://github.com/AvaloniaUI/Avalonia.Samples/tree/274b622565564aead4338378efc958e4f9b7f668/src/Avalonia.Samples/Routing/BasicViewLocatorSample

**Comment by stevemonaco** [comment]
> So, should we do it the way we did with ReactiveUI? [Example](https://docs.avaloniaui.net/docs/concepts/reactiveui/routing)

That should work and be trim-safe. It's one way of at least a few ways to do it.
