### ISSUE TITLE
`AndroidLauncher.LaunchUriAsync` always returns `false`

### ISSUE THREAD

**Issue by daniel-lerch** [AvaloniaUI/Avalonia#17162]
### Describe the bug

Avalonia's Launcher does not work on Android. It always returns `false` and does not open any URI.

### To Reproduce

1. Create an Avalonia application with Android as target platform in Visual Studio
2. Add a button to `MainView.axaml`
3. Add a click event listener which executes
```cs
private async void Button_Click(object? sender, Avalonia.Interactivity.RoutedEventArgs e)
{
    bool success = await TopLevel.GetTopLevel(this).Launcher.LaunchUriAsync(new Uri("https://github.com/"));
    Console.WriteLine($"LaunchUriAsync: {success}");
}
```
4. Run your app and click the button
5. You will see `LaunchUriAsync: false` in the logs, no browser will open

### Expected behavior

The URL should be opened in the default browser and the method should return true. It should only return false, if there is no browser app installed on the device.

### Avalonia version

11.1.3

### OS

Android

### Additional context

Android version: 14
Default browser: Google Chrome

I also tested with Avalonia 11.1.0 and 8742dbdf78185422561698023fa5e80faecbd684 but the problem is always the same.

**Comment by emmauss** [comment]
On android projects targeting API 30 and above, android restricts the external apps an app can launch. Without specifying which intent queries in your manifest your app wishes to use, avalonia can't query if a uri is supported on your device. Please read this for more info https://developer.android.com/training/package-visibility
