### ISSUE TITLE
SplitView ":open"/":closed" pseudoclasses aren't set on control initialization

### ISSUE THREAD

**Issue by OccVeneficus** [AvaloniaUI/Avalonia#17176]
### Describe the bug

SplitView control after it initialized does not have `:open` or `:closed` pseudoclass set. Regardless of the value in the `IsPaneOpen` property. 

### To Reproduce

Create Window with a SplitView control, set IsPaneOpen to any value (e.g, by binding to ViewModel)
Run the application in Debug, open Debug tools
In Logical Tree, find SplitView. The SplitView doesn't have `:open` / `:closed` pseudoclass set regardless of the value in the `IsPaneOpen` property. 
![image](https://github.com/user-attachments/assets/1a26583e-303c-428b-8bca-3e2ab323dfaa)

Pseudoclass is set only after first change of `IsPaneOpen` property

### Expected behavior

SplitView control after initialization should have `:open` / `:closed` pseudoclass set depending of the value in the `IsPaneOpen` property

### Avalonia version

11.1.0

### OS

Windows

### Additional context

After looking into `SplitView.cs` source code, the problem appears to be that the logic for changing pseudoclass based on `IsPaneOpen` value is present only in `OnPropertyChanged` method. Adding same logic to constructor should fix the issue

**Comment by timunie** [comment]
@OccVeneficus if you have an idea how to solve it, a PR is welcome.

**Comment by OccVeneficus** [comment]
> @OccVeneficus if you have an idea how to solve it, a PR is welcome.

Created PR with fix. While working on it discovered that issue reproduces only if before added on view tree `IsPaneOpen` property is set to `false`, in that case `:closed` pseudoclass won't be added after control first rendered.
