### ISSUE TITLE
Window: Pass down RequestedThemeVariant to dialog windows.

### ISSUE THREAD

**Issue by giard-alexandre** [AvaloniaUI/Avalonia#17187]
### Describe the bug

Currently, I'm opening a Dialog Window using `window.ShowDialog(parent)`. This works and the dialog inherits the app-wide theme variant properly but, if the RequestedThemeVariant override is set on the `parent`, the child window does not inherit that value and so it's theme variant is "wrong"

### To Reproduce

1. Create a parent window and override it's `RequestedThemeVariant` to be the opposite of whatever the current variant is.
2. Create a child window and use `childWindow.ShowDialog(parentWindow)` to show the window
3. The child window will not inherit its theme variant from the parent.

### Expected behavior

A window opened as a child of another should inherit that windows theme variant.

### Avalonia version

11.0.10, 11.1.3

### OS

Windows, macOS, Linux

**Comment by maxkatz6** [comment]
It's by design.
If you want a global theme variant, you should set it on Application instance.
If you want to manually control it per window - you should continue doing that, and manually set on child windows too.

**Comment by giard-alexandre** [comment]
While I understand the distinction, I wonder if it would be good to consider letting SPECIFICALLY a window shown as a child window (or at least using `ShowDialog(parent)` inherit from the parents' theme variant? You're explicitly saying that you want this dialog to be the child of its parent, Seems logical to me that the theme variants should be the same.

In this case, I'm actually showing a dialog window from a library, so I have no way of inferring the requested theme variant automatically other than by grabbing it from the TopLevel window. Again, I can do that, of course, but it may be a good new feature to have ShowDialog automatically do that?

Code I'm referring to:
https://github.com/giard-alexandre/DynamicTreeDataGrid/blob/e00438464d72e68cff491ed1aaa211494fe530b5/src/DynamicTreeDataGrid/DynamicTreeDataGrid.cs#L23-L29

**Comment by timunie** [comment]
Why don't you set RequestedThemeVariant in App axaml in that case?

**Comment by giard-alexandre** [comment]
@timunie The users app has Theme Variants set per-window. Depending on the control, they sometimes want the dark version, sometimes the light version :)
