### ISSUE TITLE
11.2.0-rc1 net5 MacOS Unable to load libSkiaSharp

### ISSUE THREAD

**Issue by ArtjomP** [AvaloniaUI/Avalonia#17189]
### Describe the bug

I updated the project from Avalonia 11.1.3 to 11.2.0-rc1 and the window does not appear anymore on MacOS. In release & debug.
I get the next error message:
`Unable to load libSkiaSharp`

My project uses .net5.

### To Reproduce

Run Avalonia 11.2.0-rc1 with .net5.0 on macOS

### Avalonia version

11.2.0-rc1

### OS

macOS

**Comment by kekekeks** [comment]
Please, use `net6.0` if you want Metal. We aren't using .NET Core specific APIs for netcoreapp1.0-net5.0 TFMs and the way Metal support works is by utilizing `NativeLibrary` class.
