### ISSUE TITLE
Another name for Perspex

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#172]
Perspex is a registered trademark of Imperial Chemical Industries so our lives would probably easier if we changed our name before we got too well known. Please add ideas for a new name in the comments.

**Comment by grokys** [comment]
Avalonia

**Comment by grokys** [comment]
Perspectiv

**Comment by grokys** [comment]
Ferro

**Comment by kekekeks** [comment]
Ametrine - a mixture of minerals. Cross platform UI is a mixture of platforms.
![Ametrine](http://inspiritcrystals.com/wp-content/uploads/2013/10/ametrine.jpg)

**Comment by grokys** [comment]
Joya
Kivi

**Comment by kekekeks** [comment]
@grokys  Do you even google names before suggesting?
Perspectiv, Ferro, Joya, Kivi all have some companies on the first page of google results.

**Comment by grokys** [comment]
Right, but do they have trademarks? Because if not, then there shouldn't be a problem.

**Comment by grokys** [comment]
Gong

**Comment by kekekeks** [comment]
We also need something that has less than million google results. Because if we are changing the name, let's have something easy to google.

**Comment by grokys** [comment]
*everything* has a million google results.

**Comment by kekekeks** [comment]
Ametrine has 585,000 :wink:

**Comment by grokys** [comment]
Constant

**Comment by kekekeks** [comment]
Google for "constant create window". 94,900,000 results.

**Comment by danwalmsley** [comment]
If the wonderful Perspex name had to be dropped, I like Avalonia 2nd!

**Comment by danwalmsley** [comment]
Perhaps it could be "Perspex UI"

people will just call it Perspex, but at least legally it wont be Perspex will it?

**Comment by kekekeks** [comment]
>people will just call it Perspex, but at least legally it wont be Perspex will it?

Legally it will be considered as "[confusingly similar](https://en.wikipedia.org/wiki/Confusing_similarity)"

**Comment by danwalmsley** [comment]
1 vote for Perspectiv

**Comment by kekekeks** [comment]
https://github.com/Perspectiv - github name already taken

**Comment by SuperJMN** [comment]
Glass!

**Comment by danwalmsley** [comment]
Glass is nice!

**Comment by danwalmsley** [comment]
probably the kind of word that cant be (c)

**Comment by ImaBrokeDude** [comment]
Crosspex

**Comment by kekekeks** [comment]
>Microsoft Glass! ;D

Come on guys, come up with something that is google-friendly.

**Comment by grokys** [comment]
Glass *is* nice but @SuperJMN has already stolen the NuGet package name ;) However I think the potential confusion with MS Glass would be a problem.

Google-ability would be nice, but IMO a catchy name is more important. There's no point being google-able if nobody can remember the name. Google learns very quickly what you're looking for in a query these days!

**Comment by grokys** [comment]
How about just changing a letter? 

Perspix

No existing products and and easy change. Probably a rude word in some language or other though.

**Comment by ImaBrokeDude** [comment]
DTK 
Decoupled Tool Kit

**Comment by ImaBrokeDude** [comment]
Or simply Perspex.NET

**Comment by kekekeks** [comment]
>Or simply Perspex.NET
>Perspix

[Confusingly similar](https://en.wikipedia.org/wiki/Confusing_similarity)

**Comment by grokys** [comment]
I don't think Perspix would be considered confusingly similar. In the email that Martin Woodward sent me he mentions a product that changed one letter to avoid trademark problems. 

Perspex.NET though wouldn't help - it's still the same name essentially.

**Comment by ImaBrokeDude** [comment]
Xrosspex

**Comment by danwalmsley** [comment]
Can we just add an extra letter also? Like Perspexx?
Or change to Perspeks?

**Comment by danwalmsley** [comment]
Its nice if it can sound in English still like Perspex,

Perspeks, Perspecs, Purspex,

I wonder if separating it to 2 words Like Per Spex, but Logo PerSpex?

**Comment by Sorien** [comment]
glase, glaze

**Comment by danwalmsley** [comment]
Vitro - According to @SuperJMN  it is like latin for Glass Vitrum

**Comment by SuperJMN** [comment]
* Neutrino
* Aurora
* Stratos
* Tempest
* Halogen
* Iris

**Comment by SuperJMN** [comment]
Please, list your best names here:

https://github.com/Perspex/Perspex/wiki/Suggested-Names

**Comment by jjrdk** [comment]
Xavalon - as in Avalon (original WPF) but x-plat.

Doesn't seem to conflict with anything similar or proprietary on Google.

**Comment by ImaBrokeDude** [comment]
AvalonX?

**Comment by flcl42** [comment]
wNext

**Comment by bitbonk** [comment]
XPlatter pronounced "splatter"

**Comment by dadhi** [comment]
__FunTalk__  just because it is fun to talk about. Very view search results, mostly from China.

__OmniPF__, or OPF  almost no search results.

**Comment by aloisdg** [comment]
Some variantes of Avalon?
- Lonava (but taken)
- Navalo (my favorite)
- Nolava (complicated as "no lava")
- Vaalno
- Lanova (looks like "Lenovo")

**Comment by dadhi** [comment]
__WpfNext__ - very few results in context of WPF - which is good.

**Comment by wieslawsoltes** [comment]
**CoreUI**

or 

**WPF Core** 1.0

or

**PureXamlUI**

**Comment by kekekeks** [comment]
Omnilon

**Comment by aloisdg** [comment]
I like OmniPF, but I prefer Omnilon.

**Comment by kekekeks** [comment]
Which turned out to be a [registered trademark](http://omniplastics.com/high-performance-products/omnilon/).

**Comment by grokys** [comment]
sublimate
muo
alonia
vria
vinica
isola
anori
zenica
wylan
zefira
tholin

**Comment by ImaBrokeDude** [comment]
AUI (AbsoluteUI)

**Comment by ImaBrokeDude** [comment]
Construk

**Comment by aloisdg** [comment]
> alonia

I like it.

**Comment by KingSora** [comment]
I like something like 
**Omni-Loops** 
**Omni-Shapes**
