### ISSUE TITLE
Support keyboard hints for mobile platforms in TextBox

### ISSUE THREAD

**Issue by gentledepp** [AvaloniaUI/Avalonia#17225]
### Is your feature request related to a problem? Please describe.

On mobile devices, the virtual keyboard changes its layout depending on keyboard hints coming from an input.

E.g. I can specify that an input is a number, so the keyboard shows the numeric layout.
I can specify that it is an e-mail, so the e-mail layout (with directly accessible "@") is shown

[Here is an extensive guide with screen shots](https://andyp.dev/posts/xamarin-forms-essentials-keyboard-master-guide)

I could not find anything related in the docs.

### Describe the solution you'd like

An implementation [similar to Xamarin.Forms as described here](https://andyp.dev/posts/xamarin-forms-essentials-keyboard-master-guide)

```xaml
<TextBox
   Keyboard="KeyboardType.Email"
/>
```

Or at least a way to specify platform-specific hints.
E.g. [for Android](https://learn.microsoft.com/ja-jp/dotnet/api/android.views.keyboardtype?view=net-android-34.0&viewFallbackFrom=xamarin-android-sdk-9)
and [for iOS](https://learn.microsoft.com/en-us/dotnet/api/uikit.uikeyboardtype?view=xamarin-ios-sdk-12)

**Comment by kerams** [comment]
`TextInputOptions.ContentType=Email`

**Comment by gentledepp** [comment]
Awesome!

Unfortunately, this is missing in the docs it seems.
I cannot find anything on google.

For the sake of completeness, here is the list of options:

```csharp

 public enum TextInputContentType
 {
     /// <summary>
     /// Default keyboard for the users configured input method.
     /// </summary>
     Normal = 0,
     
     /// <summary>
     /// Display a keyboard that only has alphabetic characters.
     /// </summary>
     Alpha,
     
     /// <summary>
     /// Display a numeric keypad only capable of numbers. i.e. Phone number
     /// </summary>
     Digits,
     
     /// <summary>
     /// Display a numeric keypad for inputting a PIN.
     /// </summary>
     Pin,
     
     /// <summary>
     /// Display a numeric keypad capable of inputting numbers including decimal seperator and sign.
     /// </summary>
     Number,
     
     /// <summary>
     /// Display a keyboard for entering an email address.
     /// </summary>
     Email,
     
     /// <summary>
     /// Display a keyboard for entering a URL.
     /// </summary>
     Url,
     
     /// <summary>
     /// Display a keyboard for entering a persons name.
     /// </summary>
     Name,
     
     /// <summary>
     /// Display a keyboard for entering sensitive data.
     /// </summary>
     Password,
     
     /// <summary>
     /// Display a keyboard suitable for #tag and @mentions.
     /// Not available on all platforms, will fallback to a suitable keyboard
     /// when not available.
     /// </summary>
     Social,
     
     /// <summary>
     /// Display a keyboard for entering a search keyword.
     /// </summary>
     Search
 }

```
