### ISSUE TITLE
Memory leak on re-binding ListBox to a heavy list from an empty list

### ISSUE THREAD

**Issue by RayyanTahir** [AvaloniaUI/Avalonia#1723]
When a ListBox is re-bound to a large list from an empty list there is an increase in memory usage which is never decreased later on. In the repro below, if you jump to "Heavy List" from "Empty List" after a 2-3 seconds delay repeatedly, you will experience a (not too huge) memory leak (maybe around 1 MB). In my other Avalonia app I am experiencing a 4-5 MB memory leak every time I switch from empty list to a heavy list. I'm using the pre-release build (0.6.2-build5603-beta)

**Repro**
[MemoryLeakRepro.zip](https://github.com/AvaloniaUI/Avalonia/files/2158231/MemoryLeakRepro.zip)

**Comment by jkoritzinsky** [comment]
Fixed by #1727
