### ISSUE TITLE
[11.2.0-rc1] OpenFolderPickerAsync returns a directory path with an extra "/".

### ISSUE THREAD

**Issue by oneo-me** [AvaloniaUI/Avalonia#17263]
### Describe the bug

OpenFolderPickerAsync returns a directory path with an extra "/".

### To Reproduce

```cs
var result = await topLevel.StorageProvider.OpenFolderPickerAsync(new()
{
    AllowMultiple = false
}).ConfigureAwait(true);

var localPath = result[0].Path.LocalPath;
// localPath = "/User/oneo/"
// localPath should not end with “/”
```

### Avalonia version

11.2.0-rc1

**Comment by maxkatz6** [comment]
Can you explain in what conditions directory path trailing slash is a bug for you?

It was changed for consistency with macOS APIs, where `assumes that path is a directory if it ends with a slash` in various APIs, like https://developer.apple.com/documentation/foundation/nsurl/1410828-fileurlwithpath?language=objc.

**Comment by oneo-me** [comment]
I understand this change, Our program is designed in the WPF API style without a "/" suffix, and may require some adjustments to accommodate the changes, thank you.
