### ISSUE TITLE
Launch URIs on Android without declaring intent queries 

### ISSUE THREAD

**Issue by daniel-lerch** [AvaloniaUI/Avalonia#17265]
### Is your feature request related to a problem? Please describe.

`AndroidLauncher.LaunchUriAsync` requires an `<intent>` element in the `<queries>` part of the app manifest as [documented by Google](https://developer.android.com/training/package-visibility/use-cases#check-browser-available). If developers forget to add this to their manifest `LaunchUriAsync` will always return `false`: #17162

### Describe the solution you'd like

Instead of queries packages that can handle the `Uri`, I would propose to optimistically launch the `Intent` and catch the `ActivityNotFoundException` for the rare case that there is no app that can handle the `Uri`. This is actually described as [recommended approach by Google](https://developer.android.com/training/package-visibility/use-cases#open-urls-browser-or-other-app).

Following that approach would have the benefit that developers would not need to add anything to their manifest. That would be less error-prone and even slightly more privacy for end users.

### Describe alternatives you've considered

If the behavior should not be changed, the necessity for declaring an intent query in the manifest should be added to Avalonia's documentation not only for `LaunchUriAsync` but also for `HyperlinkButton`.

**Comment by timunie** [comment]
@daniel-lerch if you want to add this, a PR would be welcome 👐
