### ISSUE TITLE
CS0246 ItemContainerEventArgs, but Avalonia.Controls.Primitives are imported

### ISSUE THREAD

**Issue by Wowhere** [AvaloniaUI/Avalonia#17277]
### Describe the bug

ItemContainerEventArgs not found, even if Avalonia.Controls.Primitives is imported
![изображение](https://github.com/user-attachments/assets/678b14c2-2a65-427d-af08-d43ab2852b00)
![изображение](https://github.com/user-attachments/assets/0fb37762-9b6f-45a0-9320-2e15172ec3e4)

### To Reproduce

0. Avalonia 11
1. Avalonia.Controls.Primitives are imported
2. use ItemContainerEventArgs in code

### Expected behavior

I can use ItemContainerEventArgs

### Avalonia version

11*

### OS

Windows

**Comment by stevemonaco** [comment]
`ItemContainerEventArgs` was long removed over two years ago by https://github.com/AvaloniaUI/Avalonia/pull/9677

I noticed you're using a third-party library that hasn't been updated for over two years and is on Avalonia 0.10.13. Such unmaintained libraries are not compatible with Avalonia 11.

**Comment by Wowhere** [comment]
Pull request description doesnt mention anything about ItemContainerEventArgs, thats bad, i dont know what to use then. Also i`am trying to port ExtendedToolkit to Avalonia11, i have my own fork

**Comment by stevemonaco** [comment]
> Pull request description doesnt mention anything about ItemContainerEventArgs, thats bad, i dont know what to use instead of ItemContainerEventArgs. Also i`am trying to port ExtendedToolkit to Avalonia11, i have my own fork

It was a large PR for a rewrite. The author can't specify every detail in text and readers need to actually examine what has been changed. I'm not sure if there's equivalent functionality exposed, but you could start a Discussion.
