### ISSUE TITLE
Blurry image rendering when using Direct2D back-end 

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1728]
SkiaSharp
![skiasharp](https://user-images.githubusercontent.com/2297442/42293172-88aae6bc-7fd8-11e8-9c53-5163325ba8db.png)

Direct2D
![direct2d](https://user-images.githubusercontent.com/2297442/42293173-8e3c7a5a-7fd8-11e8-9ea3-7be32d24cac3.png)

Version: 0.6.2-build5622-beta
OS: Windows 10

**Comment by grokys** [comment]
@wieslawsoltes where are the images in your screenshots? The only differences I can see are in fonts.

**Comment by jmacato** [comment]
@grokys compare the docking window's icons sir, D2D looks blurry in comparison to Skia's

**Comment by nc4rrillo** [comment]
Can you provide the source images @wieslawsoltes ? Probably the same issue with bitmap scaling we've seen in #1592

**Comment by wieslawsoltes** [comment]
https://github.com/wieslawsoltes/Dock/tree/master/src/Dock.Avalonia/Assets

**Comment by wieslawsoltes** [comment]
The issue was not solved by https://github.com/AvaloniaUI/Avalonia/pull/1762

Using latest master with `RenderOptions.BitmapInterpolationMode="HighQuality"`, I have also tried all other modes, none of them result in non-blurry image.

![2018-07-26_17-24-41](https://user-images.githubusercontent.com/2297442/43271895-05e8d126-90f9-11e8-8f7a-e3c1fb14de44.png)

**Comment by nc4rrillo** [comment]
Yeah I believe #1762 is only the Skia backend.

**Comment by jmacato** [comment]
@wieslawsoltes you'd have to set BitmapInterpolationMode to either None/LowQuality to have a crisp, pixelated image

**Comment by wieslawsoltes** [comment]
@jmacato Well the question is why by default images in skia look crip and in Direct2D not.

**Comment by Gillibald** [comment]
This is because the Direct2D1 backend needs an upgrade to support better interpolation.
