### ISSUE TITLE
CustomDateFormatString is not used for text input in CalendarDatePicker

### ISSUE THREAD

**Issue by JokaDev** [AvaloniaUI/Avalonia#17291]
### Describe the bug

The CalendarDatePicker with a CustomDateFormatString seems to display the date correctly but ignores the custom date format when the date is entered by keyboard.

### To Reproduce

1. Create a CalendarDatePicker with CustomDateFormatString set to "dd.MM.yyyy"
`<CalendarDatePicker SelectedDateFormat="Custom" CustomDateFormatString="dd.MM.yyyy" SelectedDate="{Binding Datum}">`
2. Type in the date "17.10.2024" and press enter => not accepted,  the date changes to previous value 
3. Type in the date "12.10.2024" and press enter => the date changes to 10.12.2024

### Expected behavior

Type in the date "17.10.2024" and press enter => "17.10.2024" ramains in the textbox
Type in the date "12.10.2024" and press enter => "12.10.2024" ramains in the textbox

### Avalonia version

11.1.0

### Additional context

I'm new to avalonia, but looking at the code the problem seems to be in CalendarDatePicker.cs `ParseText(string text) `  in Line 733:
` newSelectedDate = DateTime.Parse(text, DateTimeHelper.GetCurrentDateFormat());`
Shouldn't CustomDateFormatString be used here when SelectedDateFormat is set to Custom?

**Comment by timunie** [comment]
@JokaDev without looking too deep into, I think you may be right. Maybe you can file a PR to fix it? Adding some tests if possible would be great.
