### ISSUE TITLE
ScreenPage throws NullReferenceException

### ISSUE THREAD

**Issue by CommonGuy** [AvaloniaUI/Avalonia#1730]
The ScreenPage in the ControlCatalog currently does not work. It creates a new `FormattedText`, but without a typeface.

Both Skia and Direct2D will fail to create a `FormattedTextImpl`, because they assume that the typeface is non-null.

Maybe make passing a non-null typeface a requirement when creating a FormattedText? Or just defaulting to a typeface when it is null?

**Comment by grokys** [comment]
I'm not sure why this page draws everything in its `Render` method, it's a bit strange.

Also `Screen` isn't a control so I'm not sure it's even relevant to have it in ControlCatalog. Should we remove it?

**Comment by CommonGuy** [comment]
I think there two separate issues:

- The Screen page is a little strange (but also cool IMO).
- FormattedText without a Typeface throw a NullReferenceException

**Comment by grokys** [comment]
> FormattedText without a Typeface throw a NullReferenceException

Yes, but if we made the page a more standard control then we wouldn't have this problem...

**Comment by nc4rrillo** [comment]
Can we fallback to `typeface = new Typeface(FontFamily.Default)` , but yeah...the Screen page is pretty weird..

**Comment by grokys** [comment]
Yeah we should do that at least. I would prefer to have it removed or at least rewritten to be less weird, but that would prevent the exception for the moment.
