### ISSUE TITLE
Opening file with LaunchFileInfoAsync where path/filename contains space character

### ISSUE THREAD

**Issue by voidray** [AvaloniaUI/Avalonia#17301]
### Describe the bug

When LaunchFileInfoAsync is used in Linux and the path/filename contains a space, then it fails, because the rest of the string after the space is interpreted as parameter.
  xdg-open: unexpected argument 'rest-of-filename.txt'
  Try 'xdg-open --help' for more information.

### To Reproduce

> Code:
var launcher = TopLevel.GetTopLevel(control).Launcher;
await launcher.LaunchFileInfoAsync(fileInfo); // fileInfo where the path or the filename contains a space character

> Run under Linux

> Workaround (used extra "" for filepath):
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
   Process.Start(new ProcessStartInfo(filePath) { UseShellExecute = true });
}
else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
{
   Process.Start(new ProcessStartInfo
   {
       FileName = "xdg-open",
       Arguments = $"\"{filePath}\"",
       UseShellExecute = false,
       CreateNoWindow = true
   });
}

### Expected behavior

Space characters should be supported.

### Avalonia version

11.1.4

### OS

Linux

**Comment by nickodei** [comment]
Will work on that
