### ISSUE TITLE
Deleting space on Android/iOS throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by kerams** [AvaloniaUI/Avalonia#17303]
### Describe the bug

https://github.com/user-attachments/assets/dd9c665a-1e37-43b6-8e94-2311f6dc0323

### To Reproduce

`<TextBox>etwas finden</TextBox>`, place the caret after the space and press delete.

```
System.IndexOutOfRangeException Index was outside the bounds of the array.

0xFFFFFFFFFFFFFFFF in Android.Runtime.RuntimeNativeMethods.monodroid_debugger_unhandled_exception	C#
0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:12,5	C#
0x1E in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_Z at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:45,26	C#
0x10 in Avalonia.Utilities.ArraySlice<Avalonia.Media.TextFormatting.GlyphInfo>.get_Item	C#
0x7 in Avalonia.Media.TextFormatting.ShapedBuffer.get_Item	C#
0x60 in Avalonia.Media.GlyphRun.FindNearestCharacterHit	C#
0x3A in Avalonia.Media.GlyphRun.GetCharacterHitFromDistance	C#
0x74 in Avalonia.Media.TextFormatting.TextLineImpl.GetRunBoundsLeftToRight	C#
0x36 in Avalonia.Media.TextFormatting.TextLineImpl.GetTextBoundsLeftToRight	C#
0x243 in Avalonia.Media.TextFormatting.TextLineImpl.GetDistanceFromCharacterHit	C#
0x42 in Avalonia.Controls.Presenters.TextPresenter.UpdateCaret	C#
0x55 in Avalonia.Controls.Presenters.TextPresenter.MoveCaretToTextPosition	C#
0x76 in Avalonia.Controls.TextBox.DeleteSelection	C#
0x6D5 in Avalonia.Controls.TextBox.OnKeyDown	C#
```

### Expected behavior

Space is deleted.

### Avalonia version

11.3.999-cibuild0052531-alpha

### OS

Android

**Comment by kerams** [comment]
Also reproduces in iOS simulator, but only when using the software keyboard, not physical.

**Comment by kerams** [comment]
@emmauss, you're right. Tried to trigger this in one of my other repro repos with no luck. Here's a solution that does exhibit the issue though - https://github.com/kerams/input2

**Comment by kerams** [comment]
Are you sure it's because of Skia? I removed the reference and the problem persists.

**Comment by kerams** [comment]
So can this be reopened? Reproducible across iOS and Android, simulators and real devices, `11.3.999-cibuild0052531-alpha` and `11.1.4`, with SkiaSharp 2. Text input issues are really bad, not least those that cause crashes.

**Comment by emmauss** [comment]
The crash is caused by Material.Avalonia theme.

**Comment by kerams** [comment]
Thanks. Any idea what to look for, what thing would manifest in this kind of a problem?

**Comment by kerams** [comment]
If I remove [`SelectionForegroundBrush="{TemplateBinding SelectionForegroundBrush}"`](https://github.com/AvaloniaCommunity/Material.Avalonia/blob/cb295481fa32f82a45585517f903b9114228ac0c/Material.Styles/Resources/Themes/TextBox.axaml#L251) from `TextPresenter Name="PART_TextPresenter"`, the exception is gone. For the life of me I don't understand why this should cause any issue in code dealing with glyph runs, but in any case, is this really the theme's fault?
