### ISSUE TITLE
Android statusbar has white text on white background

### ISSUE THREAD

**Issue by Pierre808** [AvaloniaUI/Avalonia#17313]
### Describe the bug

The statusbar does not change it's color as it is supposed to. 
In my app.axaml I set the requested Theme to light:
`RequestedThemeVariant="Light"`
Now the statusbar is white, but the text and icons are also white.
If I set it to dark, then the statusbar is black with white foreground.

I also tried using InsetsManager in my MainWindow:
```C#
public MainWindow()
    {
        InitializeComponent();
        this.Loaded += UserControl_Loaded;
    }

    private void UserControl_Loaded(object? sender, RoutedEventArgs e)
    {
        if (OperatingSystem.IsAndroid())
        {
            var insetsManager = TopLevel.GetTopLevel(this).InsetsManager;
            insetsManager.IsSystemBarVisible = true;
            insetsManager.SystemBarColor = Colors.White;
        }
    }
```

The problem still remains.
![avalonia statusbar](https://github.com/user-attachments/assets/537d8d2b-24e7-4677-8cbe-232e5456f0c8)

### To Reproduce

Run Avalonia application on android with Light theme.

### Expected behavior

Have white background with dark text and icons.

### Avalonia version

11.1.0

### OS

Android

**Comment by emmauss** [comment]
With the large number of color choices you can have on the android Status and Nav bars, we do not automatically set the foreground color. Users should set the system bar theme, whether dark or light using `InsetsManager.SystemBarTheme`, to match the color they set for the system bar.

**Comment by emmauss** [comment]
Also, `MainWindow` isn't used on Android.

**Comment by Pierre808** [comment]
InsetsManager doesnt seem to have an attribute for SystemBarTheme. There is only an enum called SystemBarTheme.
Am I missing something?

**Comment by emmauss** [comment]
> InsetsManager doesnt seem to have an attribute for SystemBarTheme. There is only an enum called SystemBarTheme. Am I missing something?

Access it using the same instance you used for setting the status bar colour

**Comment by Pierre808** [comment]
It doesn't seem to have SystemBarTheme as attribute:

![{3E9F3904-39A9-4BC8-B53F-AADD91F9E35B}](https://github.com/user-attachments/assets/7df339d2-5303-40f5-9f08-46db2bb13375)

**Comment by IanRawley** [comment]
The AndroidInsetsManager has a SystemBarTheme member, but it's not part of the general IInsetsManager interface.  You'll need to cast it to the Android specific concrete class to get access.

**Comment by emmauss** [comment]
Try setting the RequestedThemeVariant of TopLevel to Light

**Comment by Pierre808** [comment]
Setting RequestedThemeVariant in codebehind doesn't work neither:
```C#
TopLevel.GetTopLevel(this).RequestedThemeVariant = ThemeVariant.Light;
```

How do I use AndroidInsetsManager? There is not class called `AndroidInsetsManager`. I couldn't find any documentation online.

**Comment by Pierre808** [comment]
Also I noticed that when I quit the App, without actually closing it completely, and then reopen it, the text and icons will be dark.  
Same goes for the initial (default) loading screen, it has white background and dark foreground in the statusbar. 
![Screenshot_20241022_221006.jpg](https://github.com/user-attachments/assets/8c0a738c-f9c6-47ed-9991-2fff0163adec | width=200)

**Comment by emmauss** [comment]
Please update your avalonia version to the latest 11.2 stable or 11.3 beta.

**Comment by Pierre808** [comment]
That actually fixed the issue, without any changes in the code. 
Thanks :)
