### ISSUE TITLE
Cannot input Chinese (even change IME to Chinese) in Textbox on Kylin V10

### ISSUE THREAD

**Issue by a6754z** [AvaloniaUI/Avalonia#17315]
### Describe the bug

Cannot change input method to Chinese and input Chinese in a textbox defined like below on Kylin V10, But works fine on Windows. The default font has been installed on the system and can be displayed correctly.

<FontFamily x:Key="DefaultFont">Noto Sans CJK TC Regular</FontFamily>

<TextBox x:Name="txtDesc" Margin="10,0,0,0" FontFamily="{DynamicResource DefaultFont}" FontSize="{DynamicResource DefaultFontSize}" Grid.Column="1" Height="220" VerticalAlignment="Top" AcceptsReturn="True" TextWrapping="Wrap"
                          Text="{Binding Description}"
                          Watermark="{x:Static resx:Resource.IDS_PROBLEM_REPORT_PLACE_HOLDER}"/>
                          
I also tried the solution for the issue https://github.com/AvaloniaUI/Avalonia/issues/6155, but still not work.

![image](https://github.com/user-attachments/assets/d6b06330-a380-447f-83f9-582c23d6b7c3)

### To Reproduce

Run a applicaiton with textboxes on Kylin V10.

### Expected behavior

Can change input method to Chinese and input Chinese in the Textbox.

### Avalonia version

11.0.10

### OS

Linux

**Comment by a6754z** [comment]
![image](https://github.com/user-attachments/assets/446e2f6e-4001-4981-add7-2a2137cd35e7)

![image](https://github.com/user-attachments/assets/d4472a6b-eb0d-42ec-8cd0-d9de8aeff42e)

**Comment by yangjieshao** [comment]
你是不是用root权限启动了？

**Comment by a6754z** [comment]
> 你是不是用root权限启动了？

是的

**Comment by yangjieshao** [comment]
> > 你是不是用root权限启动了？
> 
> 是的

输入法不是root权限的  root权限的程序没法加载非root权限的输入法

**Comment by timunie** [comment]
@yangjieshao @a6754z any chance to translate it to ebglish as well?

**Comment by a6754z** [comment]
> > > 你是不是用root权限启动了？
> > 
> > 
> > 是的
> 
> 输入法不是root权限的 root权限的程序没法加载非root权限的输入法
> 
> A program with root privileges cannot load input methods whitch do not had root privileges

确实是这个原因，非常感谢！

Yes. That's indeed the reason. After change to start the application with non-root privilege, I can enter the Chinese in textbox.
Thanks a lot!

**Comment by GitYonglin** [comment]
@a6754z 我现在也想用这个IME功能，找了很久都么有参考和可用的资料，可以分享一些您的程序给我看看吗？谢谢
