### ISSUE TITLE
Setting ShowInTaskbar to false on Window with SizeToContent set to WidthAndHeight doesn't work

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#1731]
Sample:

```xaml
<Window xmlns="https://github.com/avaloniaui"
        ShowInTaskbar="False"
        SizeToContent="WidthAndHeight">

    <TextBlock Text="Hello world!" />

</Window>
```

If I remove `ShowInTaskbar="False"`, then the window size will be correct.

**Comment by grokys** [comment]
@jp2masa is this on Windows?

**Comment by jp2masa** [comment]
Yes. I just tested it and I can still repro it.

**Comment by dmrayt** [comment]
With this code, Width and Height are on Windows totally ignored. On Linux ShowInTaskbar is ignored see #3455.

```csharp
<Window xmlns="https://github.com/avaloniaui"
        ShowInTaskbar="False"
        Width=800
        Height=400>
    <TextBlock Text="Hello world!" />
</Window>
```

**Comment by grokys** [comment]
Just tested this again and seems to have been fixed (we've done a fair bit of work on this stuff recently). Closing - please let me know if it's still a problem for you.
