### ISSUE TITLE
Not all default theme brushes are using Accents resources

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1733]
https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/AutoCompleteBox.xaml#L41

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/CalendarButton.xaml#L31

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/CalendarDayButton.xaml#L45

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/CalendarDayButton.xaml#L106

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/CalendarItem.xaml#L156

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/DataValidationErrors.xaml#L24

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/DatePicker.xaml#L31

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/DatePicker.xaml#L69

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/DatePicker.xaml#L103

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/DropDownItem.xaml#L22

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/DropDownItem.xaml#L25

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/Expander.xaml#L111

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/ListBoxItem.xaml#L19

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/ListBoxItem.xaml#L22

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/ScrollViewer.xaml#L3

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/TabStripItem.xaml#L3

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/TreeViewItem.xaml#L53

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/TreeViewItem.xaml#L57

**Comment by jp2masa** [comment]
Also the scroll bar arrows, like this one:

https://github.com/AvaloniaUI/Avalonia/blob/08be99c273b4f9ee2ba963c5e167fde185226038/src/Avalonia.Themes.Default/ScrollBar.xaml#L13

**Comment by wdcossey** [comment]
I don't mind picking this up.

Just browsing the code, are there any dos and don'ts for the theme?

i.e. Use ThemeAccentBrush4 for the ListBoxItem:pointerover rather than a grey colour (ThemeBorderMidBrush).
![image](https://user-images.githubusercontent.com/1089478/44276025-3d9a6200-a23e-11e8-9083-56ea88bd84c8.png)

**Comment by wdcossey** [comment]
@wieslawsoltes I'm not sure how **Transparent** (see ScrollViewer.xaml & TabStripItem.xaml) would violate the styling as these are specific to the accent resources.
