### ISSUE TITLE
ScrollIntoView does not work as expected.

### ISSUE THREAD

**Issue by NeverMorewd** [AvaloniaUI/Avalonia#17347]
### Describe the bug

`ScrollIntoView(itemsControl.Items.Count - 1)` can not work as expected,
while  `scrollViewer?.ScrollToEnd();` can work well.

### To Reproduce

```csharp
  // not work
  itemsControl.ScrollIntoView(itemsControl.Items.Count - 1);
  itemsControl.ItemsView.CollectionChanged += (sender, args) =>
  {
      itemsControl.ScrollIntoView(itemsControl.Items.Count - 1);
  };
  itemsControl.Items.CollectionChanged += (s,e)=> 
  {
      itemsControl.ScrollIntoView(itemsControl.Items.Count - 1);
  };
  itemsControl.Items.Add(viewName);
  // work
  var scrollViewer = itemsControl.FindLogicalAncestorOfType<ScrollViewer>(includeSelf: false);
  scrollViewer?.ScrollToEnd();
```

### Expected behavior

`ScrollIntoView(itemsControl.Items.Count - 1)` can work like   `scrollViewer?.ScrollToEnd();`

### Avalonia version

11.1.3

### OS

Windows

**Comment by timunie** [comment]
You may need to use the Dispatcher in order to wait for items to be loaded.

**Comment by NeverMorewd** [comment]
> You may need to use the Dispatcher in order to wait for items to be loaded.

Thank you!

I have solved this issue with adding `Dispatcher.UIThread.RunJobs(DispatcherPriority.Loaded); ` after `Items.Add`
