### ISSUE TITLE
Xaml-Styling-Test: test fails on non-english localized Windows machines

### ISSUE THREAD

**Issue by nickodei** [AvaloniaUI/Avalonia#17359]
### Describe the bug

When you run the test `Fails_Use_Classes_In_Setter_When_Selector_Is_Complex()` under `Avalonia.Markup.Xaml.UnitTests.Xaml.StyleTests`, the test will fail on non-english localized windows machienes:

![image](https://github.com/user-attachments/assets/f56a1ef9-43a5-4296-b1da-3974d81c61ec)

This happens because the assert expects "Line 6, position 14" but this part of the exception is localized and in my case in german.

### To Reproduce

Run the test `Fails_Use_Classes_In_Setter_When_Selector_Is_Complex()` on a non-english localized machine.

### Expected behavior

Test should pass independent on the localization of the machine

### Avalonia version

master

### OS

Windows

### Additional context

I would like to fix this bug and open a PR. 
Some possibilities in my mind:

- Setting `new CultureInfo("en-US")` at the beginning of the tests fixes this (this works)
- Remove the Line part from the expected string and only assert the beginning
- Use regex to look for the line and position number in the exception message

Any suggestions?

**Comment by nickodei** [comment]
This happens in Rider and with dotnet test

**Comment by timunie** [comment]
I think the correct fix is to set culture to Invariant here which is basically English.
