### ISSUE TITLE
Binding TextBox Text property to DynamicResource does not display value

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1736]
Repro:
```XML
<TextBox Text="{DynamicResource FontSizeSmall}" IsReadOnly="True"/>
```
FontSizeSmall is defined in BaseLight.xaml
```XML
<sys:Double x:Key="FontSizeSmall">10</sys:Double>
```

**Comment by grokys** [comment]
Just tried this and it doesn't work on WPF either:

![image](https://user-images.githubusercontent.com/1775141/42597016-b5ac82f4-8557-11e8-8ab2-55ca6b83246c.png)
