### ISSUE TITLE
Memory leak in Vulkan Renderer

### ISSUE THREAD

**Issue by iejeecee** [AvaloniaUI/Avalonia#17363]
### Describe the bug

The Vulkan Command Buffers created in the function ImportedSemaphore.SubmitSemaphore in the file Avalonia.Vulkan.VulkanExternalObjectsFeature.cs are never released causing a memory leak.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Vulkan/VulkanExternalObjectsFeature.cs#L171

Adding a call to _pool.FreeFinishedCommandBuffers() at the beginning of the function fixes the leak, but I cannot oversee if this breaks something unintentionally

```csharp
void SubmitSemaphore(VulkanSemaphore? wait, VulkanSemaphore? signal)
{
    _pool.FreeFinishedCommandBuffers();

    var buf = _pool.CreateCommandBuffer();
    buf.BeginRecording();
    _context.DeviceApi.CmdPipelineBarrier(
        buf.Handle,
        VkPipelineStageFlags.VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
        VkPipelineStageFlags.VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
        0,
        0,
        IntPtr.Zero,
        0,
        IntPtr.Zero,
        0,
        null);
    
    buf.EndRecording();
    buf.Submit(wait != null ? new[] { wait }.AsSpan() : default,
        new[] { VkPipelineStageFlags.VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT },
        signal != null ? new[] { signal }.AsSpan() : default);
}
```

### To Reproduce

E.g running the GpuInterop sample (with a Vulkan backend) and continuously modifying the teapot causing the screen to update. You can observe the memory leak in Task Manager on Windows

### Expected behavior

Expected behavior is that the amount of memory allocated doesn't keep increasing while moving the teapot around

### Avalonia version

11.1.4

### OS

Windows

**Comment by Gillibald** [comment]
@kekekeks

**Comment by kekekeks** [comment]
We probably want to do that once per frame rather than in random parts of the codebase (like we currently do with ImportImage).
