### ISSUE TITLE
Templates for .NET Core CLI

### ISSUE THREAD

**Issue by arthrp** [AvaloniaUI/Avalonia#1738]
Would you consider making templates available for .NET Core CLI, without Visual Studio dependency? It shouldn't be difficult, judging by https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates.

**Comment by jp2masa** [comment]
https://github.com/AvaloniaUI/avalonia-dotnet-templates

**Comment by grokys** [comment]
👍  It's already mentioned in the [docs](http://avaloniaui.net/docs/quickstart/create-new-project) so closing this.

**Comment by arthrp** [comment]
Fair enough! Even though IMO it should be mentioned in the readme's **Getting started** section. Currenly I noticed the link to docs only in one place:
>You can take a look at the getting started page for an overview of how to get started but probably the best thing to do for now is to already know a little bit about WPF/Silverlight/UWP/XAML and ask questions in our Gitter room.

Doesn't really encourage to read those docs.

**Comment by grokys** [comment]
Yep, good point - that should be updated. It came from a time before we had much docs.
