### ISSUE TITLE
[linux] glib minimal version is raised?

### ISSUE THREAD

**Issue by isergvb** [AvaloniaUI/Avalonia#17390]
### Describe the bug

In 11.2.0 on Ubuntu 22.04 (and early) with glib 2.64 stopped working OpenFilePickerAsync.
It's broken by Avalonia/src/Avalonia.X11/Interop/Glib.cs in the RunOnGlibThread function call.
Now used **g_timeout_add_once** (available in glib since 2.74) instead of old call **g_timeout_add_full** (base api)

Is the minimal required version Avalonia is raised from Ubuntu 16.04 to 24.04,
or is it possible to return to the previous api glib?

### To Reproduce

use OpenFilePickerAsync

### Expected behavior

no crash

### Avalonia version

11.2.0

### OS

Linux

### Additional context

Unable to find an entry point named 'g_timeout_add_once' in shared library 'libglib-2.0.so.0'

**Comment by maxkatz6** [comment]
Fixed in https://github.com/AvaloniaUI/Avalonia/pull/17392
Planned to be shipped with 11.2.1

**Comment by JerryJian** [comment]
@maxkatz6 Is there any way around this issue?

**Comment by maxkatz6** [comment]
@JerryJian use nightly builds or wait for 11.2.1 which is expected next week.
