### ISSUE TITLE
TextBlock render position error in `11.2.0`

### ISSUE THREAD

**Issue by Coloryr** [AvaloniaUI/Avalonia#17396]
### Describe the bug

TextBox render text position deviate.
At 11.2.0
![image](https://github.com/user-attachments/assets/b385d6fe-f482-464f-836d-834634cdc26c)
At 11.1.4
![image](https://github.com/user-attachments/assets/a8c25abe-0188-4641-8d80-f1f136fa8135)

### To Reproduce

1. Add a textblock
2. Add text
3. Use `11.2.0`

### Expected behavior

Same with `11.1.4`

### Avalonia version

11.2.0

### OS

Windows

**Comment by Coloryr** [comment]
The TextBlock
```
<TextBlock
    HorizontalAlignment="Center"
    FontSize="13"
    Text="{Binding Name, FallbackValue=1234}"
    TextAlignment="Center"
    TextTrimming="{Binding Trim}"
    TextWrapping="{Binding Wrap}" />
```
When
```
 HorizontalAlignment="Center"
```
will render in error position, delete it or set Left is work.

**Comment by Coloryr** [comment]
`HorizontalAlignment` and `TextAlignment` cannot be set the same `Center`

**Comment by ADdy2142** [comment]
I have the same problem and my text is not displayed in the middle. This problem appeared from version 11.2.0-rc2

**Comment by Gillibald** [comment]
I can't reproduce this issue

```
  <Border>
    <TextBlock
      HorizontalAlignment="Center"
      TextAlignment="Center"
      Text="Hello World"
      TextWrapping="Wrap"
      TextTrimming="CharacterEllipsis">     
    </TextBlock>
  </Border>
```

**Comment by Coloryr** [comment]
<Border Width="80">
    <TextBlock
      HorizontalAlignment="Center"
      TextAlignment="Center"
      Text="Hello World"
      TextWrapping="NoWrap"
      TextTrimming="CharacterEllipsis">     
    </TextBlock>
  </Border>

**Comment by Coloryr** [comment]
<Border Width="80">
    <TextBlock
      HorizontalAlignment="Center"
      TextAlignment="Center"
      Text="Hello World"
      TextWrapping="NoWrap"
      TextTrimming="CharacterEllipsis">     
    </TextBlock>
  </Border>

**Comment by timunie** [comment]
@ADdy2142 do you have a snippet to reproduce?

**Comment by Gillibald** [comment]
This reproduces the issue:
```
  <Border 
    Width="200" 
    HorizontalAlignment="Center"
    VerticalAlignment="Center">
    <TextBlock
      Text="Hello World"
      Foreground="White"
      HorizontalAlignment="Center"
      TextAlignment="Center">
    </TextBlock>
  </Border>
```

**Comment by Coloryr** [comment]
> This reproduces the issue:
> 
> ```
>   <Border 
>     Width="200" 
>     HorizontalAlignment="Center"
>     VerticalAlignment="Center">
>     <TextBlock
>       Text="Hello World"
>       Foreground="White"
>       HorizontalAlignment="Center"
>       TextAlignment="Center">
>     </TextBlock>
>   </Border>
> ```

yes, set Width and off TextWrapping

**Comment by Coloryr** [comment]
I found only set `TextAlignment=Center` some time will render in error position

**Comment by timunie** [comment]
@Coloryr please test this PR 
https://github.com/AvaloniaUI/Avalonia/pull/17402#issuecomment-2451717495

Thanks 🙏

**Comment by Coloryr** [comment]
> @Coloryr please test this PR [#17402 (comment)](https://github.com/AvaloniaUI/Avalonia/pull/17402#issuecomment-2451717495)
> 
> Thanks 🙏

![image](https://github.com/user-attachments/assets/fd7787d7-23a2-4ec7-a3bd-17f62cd02e3b)

```
<Project>
  <PropertyGroup>
    <AvaloniaVersion>11.3.999-cibuild0052951-alpha</AvaloniaVersion>
  </PropertyGroup>
</Project>
```

**Comment by timunie** [comment]
Make sure you have the nuget feed set correctly. 

/cc @Gillibald

**Comment by Coloryr** [comment]
> Make sure you have the nuget feed set correctly.
> 
> /cc @Gillibald

No, it's a problem with my configuration nuget file. I can get the corresponding Nuget package.
