### ISSUE TITLE
Can HarmonyOS be supported?

### ISSUE THREAD

**Issue by bxjg1987** [AvaloniaUI/Avalonia#17404]
### Is your feature request related to a problem? Please describe.

In China, HarmonyOS is very important and even receives first level support from the government. It has huge market potential. Should we consider supporting it?
At present, Unity3D has launched a special edition for China and supports HarmonyOS. We hope that Avalonia can evaluate its support for HarmonyOS.

### Describe the solution you'd like

none

### Describe alternatives you've considered

none

### Additional context

none

**Comment by rabbitism** [comment]
This question has been asked multiple times here. 
https://github.com/AvaloniaUI/Avalonia/discussions/16377

**Comment by maxkatz6** [comment]
Closing as a duplicate
