### ISSUE TITLE
Solution display problem

### ISSUE THREAD

**Issue by DanCadwellcs** [AvaloniaUI/Avalonia#17407]
### Describe the bug

is:issue is:open Rename MainWindow, I chose WindowStart, then repair any errors.  The axaml and then cs are not collapsing under the plus symbol.  Not big just a note

### To Reproduce

See above

### Avalonia version

11.

**Comment by thevortexcloud** [comment]
Is this a problem with Visual Studio, Rider, VS Code, Fleet, or something else?

**Comment by timunie** [comment]
@DanCadwellcs please file a minimum sample

**Comment by timunie** [comment]
I doubt it's an Avalonia issue. Since we can't even reproduce, I'll close this issue for now. 

If you can reproduce, please open a new discussion and attach the repro there.
