### ISSUE TITLE
Use Avalonia for commercial project

### ISSUE THREAD

**Issue by OmidID** [AvaloniaUI/Avalonia#1740]
We want to start a new project that will be work on LINUX + Custom hardware. Do you think is it good idea to use Avalonia for GUI? 

Maybe we will have some complicated GUI.

**Comment by danwalmsley** [comment]
there are a few commercial applications in development using Avalonia. Things are fairly stable now.

You may encounter the odd issue, so be prepared for that. It also depends on the processing power of your custom hardware.

**Comment by OmidID** [comment]
@danwalmsley , Thanks,
This is the CPU we using:
https://www.toradex.com/computer-on-modules/colibri-arm-family/nvidia-tegra-2
