### ISSUE TITLE
Can't get Screens in Design Preview in `11.2.0`

### ISSUE THREAD

**Issue by Coloryr** [AvaloniaUI/Avalonia#17401]
```
10:03:18.175 [Error] 28276 <= "Unhandled exception. System.InvalidOperationException: Windowing backend wasn't properly initialized."
10:03:18.177 [Error] 28276 <= "   at Avalonia.Controls.WindowBase.get_Screens()"
10:03:18.177 [Error] 28276 <= "   at ColorMC.Gui.UI.Windows.ABaseWindow.SetWindowState() in E:\code\ColorMC\src\ColorMC.Gui\UI\Windows\ABaseWindow.cs:line 114"
10:03:18.178 [Error] 28276 <= "   at ColorMC.Gui.UI.Windows.AMultiWindow.FindGoodPos() in E:\code\ColorMC\src\ColorMC.Gui\UI\Windows\AMultiWindow.cs:line 140"
10:03:18.178 [Error] 28276 <= "   at ColorMC.Gui.UI.Windows.AMultiWindow.InitMultiWindow(BaseUserControl con) in E:\code\ColorMC\src\ColorMC.Gui\UI\Windows\AMultiWindow.cs:line 62"
10:03:18.178 [Error] 28276 <= "   at ColorMC.Gui.UI.Windows.MultiWindow..ctor(BaseUserControl con) in E:\code\ColorMC\src\ColorMC.Gui\UI\Windows\MultiWindow.axaml.cs:line 22"
10:03:18.179 [Error] 28276 <= "   at ColorMC.Gui.Manager.WindowManager.ShowWindow(BaseUserControl con) in E:\code\ColorMC\src\ColorMC.Gui\Manager\WindowManager.cs:line 212"
10:03:18.179 [Error] 28276 <= "   at ColorMC.Gui.Manager.WindowManager.AWindow(BaseUserControl con, Boolean newwindow) in E:\code\ColorMC\src\ColorMC.Gui\Manager\WindowManager.cs:line 238"
10:03:18.179 [Error] 28276 <= "   at ColorMC.Gui.Manager.WindowManager.ShowMain() in E:\code\ColorMC\src\ColorMC.Gui\Manager\WindowManager.cs:line 366"
10:03:18.179 [Error] 28276 <= "   at ColorMC.Gui.Manager.WindowManager.Init(String path) in E:\code\ColorMC\src\ColorMC.Gui\Manager\WindowManager.cs:line 120"
10:03:18.180 [Error] 28276 <= "   at ColorMC.Gui.App.OnFrameworkInitializationCompleted() in E:\code\ColorMC\src\ColorMC.Gui\App.axaml.cs:line 103"
10:03:18.180 [Error] 28276 <= "   at Avalonia.AppBuilder.SetupUnsafe()"
10:03:18.180 [Error] 28276 <= "   at Avalonia.AppBuilder.Setup()"
10:03:18.182 [Error] 28276 <= "   at Avalonia.AppBuilder.SetupWithoutStarting()"
10:03:18.182 [Error] 28276 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.AppInitializer.ConfigureApp(IAvaloniaRemoteTransportConnection transport, CommandLineArgs args, Object obj)"
10:03:18.182 [Error] 28276 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline)"
10:03:18.183 [Error] 28276 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args)"
```

https://github.com/Coloryr/ColorMC/blob/9c0fe2d4e543e38d7d26c06f57a3f77f194c832c/src/ColorMC.Gui/UI/Windows/ABaseWindow.cs#L114

_Originally posted by @Coloryr in https://github.com/AvaloniaUI/Avalonia/discussions/17395_

**Comment by timunie** [comment]
Maybe you try to access it too early? Try Dispatcher.UiThread.Post to wait for window to be loaded.

**Comment by timunie** [comment]
Wait the previewer doesn't know about screens at all afaik. So if you are seeing it in the designer, this is probably by design.

**Comment by thevortexcloud** [comment]
As was mentioned in the in the discussion, it does in fact have an implementation for Screens and it does look like it's wired up properly.

https://github.com/AvaloniaUI/Avalonia/discussions/17395#discussioncomment-11120135

I am however not clear why it's not working as it looks fine to me just from looking at the code.

**Comment by maxkatz6** [comment]
I actually tried to reproduce this issue using new AvaloniaRider feature, allowing to debug designer process.

It works fine here:
![image](https://github.com/user-attachments/assets/ef6fc8a6-a0c5-4ac6-b08f-4fe0a569eefc)

**Comment by maxkatz6** [comment]
@Coloryr can you try to isolate the issue? Maybe project configuration overrides backend or breaks something unexpectedly.

**Comment by Coloryr** [comment]
I know what happend, I opened a new window on `OnFrameworkInitializationCompleted`, and the new window to get the `Screens`, like your pic. 

> I actually tried to reproduce this issue using new AvaloniaRider feature, allowing to debug designer process.
> 
> It works fine here: ![image](https://private-user-images.githubusercontent.com/3163374/382423980-ef6fc8a6-a0c5-4ac6-b08f-4fe0a569eefc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MjAxNDIsIm5iZiI6MTczMDUxOTg0MiwicGF0aCI6Ii8zMTYzMzc0LzM4MjQyMzk4MC1lZjZmYzhhNi1hMGM1LTRhYzYtYjA4Zi00ZmUwYTU2OWVlZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDJUMDM1NzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTRiODVmZmU2Yjk3NjhkMzAzYzE3YTMwNWRhNGZhMGM3Y2ViNGVhMjA4M2MwMDA4M2E3Zjk2Yjk4MWQyYjA1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qkkoIH3lsh0hdSI97LryRbFB9ojvqCMll1c5LrIKgaE)

**Comment by Coloryr** [comment]
[AvaloniaApplication1.zip](https://github.com/user-attachments/files/17605523/AvaloniaApplication1.zip)

**Comment by Coloryr** [comment]
11.1.4 is work well
