### ISSUE TITLE
Won't start on Android

### ISSUE THREAD

**Issue by qingyu-sama** [AvaloniaUI/Avalonia#17424]
### Describe the bug

When I run the Avalonia project on an Android device, I get an error

![image](https://github.com/user-attachments/assets/8c727275-360a-46a2-985b-bb28c7d766b1)

App.axaml
![image](https://github.com/user-attachments/assets/d5bc8293-6b06-4980-9ed7-be5a3872eaa7)

App.axaml.cs
![image](https://github.com/user-attachments/assets/66474f1a-2e06-4cd7-933e-3e8974a8a072)

MainActivity
![image](https://github.com/user-attachments/assets/9ab61245-0a49-4dc1-b31b-a2765bea0b14)

But this problem does not occur when I downgrade the Avalonia version from 11.2.0 to 11.1.4

### To Reproduce

Same as above

### Avalonia version

11.2.0

### OS

Android

**Comment by maxkatz6** [comment]
@qingyu-sama can you isolate a minimal project to reproduce? This error usually indicates either that XAML compiler failed to run, or .NET trimmer for some reason deleted XAML compiled code.

**Comment by qingyu-sama** [comment]
I think I found the problem, when I created a new project and reinstalled Android Workflow everything worked fine.

**Comment by qingyu-sama** [comment]
Sorry, I found this problem is still not solved
Here is the test project link https://github.com/qingyu-sama/AvaloniaApplication1

**Comment by qingyu-sama** [comment]
I tested it carefully and found that this problem only exists in the second build. The specific manifestation is:
When I clean the entire solution, the build can run normally
But when I build again, this problem will occur even if I don't change any code

**Comment by Keboo** [comment]
I am also seeing similar behavior. A few additional details:
- Running Avalonia version 11.2.0, .NET SDK 8.0.403
- This only appears to occur with Android when running `Release` builds. I am triggering it by running `git clean -dfx` then `dotnet build .\<Project>.Android\<Project>.Android.csproj -c Release -bl`
- Decompiling at the bin\Release\net8.0\<Project>.dll the compiled XAML does appear to be missing. The same for `\obj\Release\net8.0\<Project>.dll`.

**Comment by Trueber** [comment]
Same issue here. My observations
* My project and the minimal example above both have the `App.axaml` in a 'shared' project and the andorid part in an own project
* It happens also on Debug builds
* It does not happen after Clean of Solution
* Exception:
```
Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for Xovis.Production.Warehouse.App.Common.App, make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
   at Xovis.Production.Warehouse.App.Common.App.Initialize() in C:\git\xovis\production-warehouse-app\Xovis.Production.Warehouse.App.Common\App.axaml.cs:line 24
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.Android.AvaloniaMainActivity.InitializeAvaloniaView(Object initialContent)
   at Avalonia.Android.AvaloniaActivity.OnCreate(Bundle savedInstanceState)
   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Activity.cs:line 3082
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121
```

* When building on CI (first `dotnet build <Solution>`, then `dotnet publish <Android>.csproj --no-restore`, I also get the Exception: 
```
/usr/share/dotnet/sdk/8.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1127,5): error MSB4018: The "GetAssemblyAttributes" task failed unexpectedly. [${WORKSPACE}/<SharedProject>/<SharedProject>.csproj]

/usr/share/dotnet/sdk/8.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1127,5): error MSB4018: System.IO.FileNotFoundException: ${WORKSPACE}/<SharedProject>/obj/Release/net8.0/<SharedProject>.dll [${WORKSPACE}/<SharedProject>/<SharedProject>.csproj]

/usr/share/dotnet/sdk/8.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1127,5): error MSB4018:    at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName) [${WORKSPACE}/<SharedProject>/<SharedProject>.csproj]

/usr/share/dotnet/sdk/8.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1127,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GetAssemblyAttributes.ExecuteCore() [${WORKSPACE}/<SharedProject>/<SharedProject>.csproj]

/usr/share/dotnet/sdk/8.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1127,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [${WORKSPACE}/<SharedProject>/<SharedProject>.csproj]

/usr/share/dotnet/sdk/8.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1127,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute() [${WORKSPACE}/<SharedProject>/<SharedProject>.csproj]

/usr/share/dotnet/sdk/8.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1127,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [${WORKSPACE}/<SharedProject>/<SharedProject>.csproj]
```

**Comment by juchom** [comment]
I created a very minimal project from scratch to learn what is necessary to run an app on Android and I have the exact same issue as @qingyu-sama.

Avalonia version
11.2.0

Rider
2024.2.7

Dotnet
8.0.403

**Comment by TomEdwardsEnscape** [comment]
This is related to #17099, specifically [this comment](https://github.com/AvaloniaUI/Avalonia/issues/17099#issuecomment-2380017961). There are some new details here which are interesting, particularly about a clean build working. At least there is a workaround.

One strange thing: downgrading to 11.4 fixes it, even though the original issue was reported as 11.2, and nothing changed in between these two releases.
