### ISSUE TITLE
avalonia.js 404 error

### ISSUE THREAD

**Issue by jeffersyuan1976** [AvaloniaUI/Avalonia#17434]
### Describe the bug

I followed the document with: .net9  9.0.100-rc.2.24474.11 and avalonia 11.2.0, vs template version is:1.4
Start the browser project, got the error as:
avalonia.js 404

Any ideas?
Thanks.

### To Reproduce

in vs 2022 preview version, create new project via avalonia crossplatform.
Select dotnet9 and avalonia 11.2.0

Then nothing changed.

### Avalonia version

11.2.0

### OS

WebAssembly

**Comment by maxkatz6** [comment]
dotnet workload install wasm-tools-net8
