### ISSUE TITLE
Why does the ScrollScrollViewer in TextBox not display when the content exceeds

### ISSUE THREAD

**Issue by AscendLiu** [AvaloniaUI/Avalonia#17440]
### Describe the bug

![PixPin_2024-11-06_16-02-58](https://github.com/user-attachments/assets/6620c717-0da4-4bf8-b458-212317c4aa57)

### To Reproduce

`    <Grid RowDefinitions="*,Auto">
        <TextBlock Text="xxxxxxxx" Background="Gainsboro"/> 
        <Expander Grid.Row="1" HorizontalAlignment="Stretch" Header="XXXXXXXXXXX">
            <TextBox HorizontalAlignment="Stretch" TextWrapping="Wrap" 
                     VerticalAlignment="Stretch"
                     />
        </Expander>
    </Grid>`

### Avalonia version

11.1.0

### OS

Windows

**Comment by timunie** [comment]
If you set Row to Auto, it can grow infinite. ScrollViewer needs fixed height however. So either give TextBox a fixed height or MaxHeight or change grid row to * or fixed value.

**Comment by AscendLiu** [comment]
> 如果将 Row 设置为 Auto，则它可以无限增长。但是 ScrollViewer 需要固定高度。因此，要么为 TextBox 指定固定高度或 MaxHeight，要么将网格行更改为 * 或固定值。

Sorry, I'm not very familiar with it. I thought it was a bug, but that's true
