### ISSUE TITLE
AutoCompleteBox loses selection when context menu opened

### ISSUE THREAD

**Issue by isergvb** [AvaloniaUI/Avalonia#17453]
### Describe the bug

Selection of text get lost when context menu opened.
Moreover, small part of selection (not empty) is expanded to full selection at first time and lost too.

### To Reproduce

1. Write text in AutoCompleteBox
2. Select part of text (or not)
3. Right click on selection
4. Move pointer over context menu items
5. Cut, Copy items after 4. will be disabled with selection empty

Example styles:
```xml
<Styles.Resources>
...
<MenuFlyout x:Key="testTextBoxContextFlyout" Placement="Bottom">
 <MenuItem Header="Cut" Command="{Binding $parent[TextBox].Cut}" IsEnabled="{Binding $parent[TextBox].CanCut}" InputGesture="{x:Static TextBox.CutGesture}"/>
 <MenuItem Header="Copy" Command="{Binding $parent[TextBox].Copy}" IsEnabled="{Binding $parent[TextBox].CanCopy}" InputGesture="{x:Static TextBox.CopyGesture}"/>
 <MenuItem Header="Paste" Command="{Binding $parent[TextBox].Paste}" IsEnabled="{Binding $parent[TextBox].CanPaste}" InputGesture="{x:Static TextBox.PasteGesture}"/>
</MenuFlyout>
...
</Styles.Resources>

<Style Selector="TextBox">
 <Setter Property="ContextFlyout" Value="{StaticResource testTextBoxContextFlyout}"/>
</Style>
```

### Expected behavior

Not lose selection.
Not expand not empty selection.

### Avalonia version

11.2.0

### OS

Windows, macOS, Linux

### Additional context

The same problem with TextBox was solved:
https://github.com/AvaloniaUI/Avalonia/pull/4498

**Comment by timunie** [comment]
@isergvb if you want to apply a similar fix to that control, a PR is welcome.
