### ISSUE TITLE
`TextBlock.TextAlignment` broken after upgrading from `11.1.4` to `11.2.0`

### ISSUE THREAD

**Issue by Tyrrrz** [AvaloniaUI/Avalonia#17450]
### Describe the bug

The following element tree:

```xml
<StackPanel
    Margin="8,32,8,8"
    HorizontalAlignment="Center"
    IsVisible="{Binding !Downloads.Count}"
    Orientation="Vertical">
    <materialIcons:MaterialIcon
        Width="256"
        Height="256"
        HorizontalAlignment="Center"
        Foreground="{DynamicResource MaterialDividerBrush}"
        Kind="Youtube" />

    <TextBlock
        HorizontalAlignment="Center"
        FontSize="18"
        FontWeight="Light"
        LineSpacing="8"
        TextAlignment="Center"
        TextWrapping="Wrap">
        <Run Text="Copy-paste a" />
        <Run FontWeight="SemiBold" Text="URL" />
        <Run Text="or enter a" />
        <Run FontWeight="SemiBold" Text="search query" />
        <Run Text="to start downloading" />
        <LineBreak />
        <Run Text="Press" />
        <Run FontWeight="SemiBold" Text="Shift+Enter" />
        <Run Text="to add multiple items" />
    </TextBlock>
</StackPanel>
```

Is rendered differently between `11.1.4` and `11.2.0`.

On `11.1.4` it's rendered correctly:

![image](https://github.com/user-attachments/assets/37c25147-fc1a-4f37-873d-d5a43d324cb8)

On `11.2.0` it's rendered incorrectly:

![image](https://github.com/user-attachments/assets/66209337-8745-4f3f-8303-7f690677a7fc)

Removing the `TextAlignment` property seems to fix the visual issues, but then the text is obviously not aligned as desired:

![image](https://github.com/user-attachments/assets/57cd21e1-f880-476c-9194-3a70b53522aa)

None of the other properties seem to have an effect.

### To Reproduce

The project where this happens is open source, so it's easy to reproduce by just checking out the right refs.

- Works as intended (`11.1.4`): https://github.com/Tyrrrz/YoutubeDownloader/tree/223e4a04e848661d6bd7c963ceadfad8ae815298 (`223e4a`)
- Broken (`11.2.0`): https://github.com/Tyrrrz/YoutubeDownloader/tree/b1632f8d119302ad9e79e01df3d4f2d9176276c7 (`b1632f`)

To reproduce, simply run the only Avalonia project in the solution. The issue should present itself immediately as soon as the window is opened.

### Expected behavior

The text should be center-aligned, as it was before `11.2.0`.

### Avalonia version

11.2.0

### OS

Windows

**Comment by rabbitism** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/17402

**Comment by Tyrrrz** [comment]
> #17402

Thanks. Although in my case, removing `HorizontalAligntment` on the text block did not help. Is it because the parent element also has `HorizontalAlignment`?

**Comment by Gillibald** [comment]
Try this build `11.3.999-cibuild0053119-alpha` to make sure the fix is working for you

**Comment by Tyrrrz** [comment]
Fixed in the latest release, thank you!
