### ISSUE TITLE
Incorrect vertical scrollbar size in `VirtualizingStackPanel`

### ISSUE THREAD

**Issue by BobLd** [AvaloniaUI/Avalonia#17460]
### Describe the bug

When using a Vertical `VirtualizingStackPanel`, the Vertical scroll bar size is not correct until the view is scroll down to its maximum.

Incorrect (Current)
![image](https://github.com/user-attachments/assets/32b7faf3-28a2-4f73-a600-c2a4e003cd8f)

Expected
![image](https://github.com/user-attachments/assets/93f9d3d7-be48-4c91-a1d5-a0655033aa62)

Sorry for the bad pictures, this is part of an app I'm working on. The current hack I am using is to force a ScrollIntoView of the last item

```csharp
    private void EnsureScrollBars()
    {
        int currentPage = SelectedPageIndex.HasValue ? SelectedPageIndex.Value - 1 : 0;

        try
        {
            _isSettingPageVisibility = true;

            // There's a bug in VirtualizingStackPanel. Scroll bars do not display correctly
            // This hack fixes that by scrolling into view a page that's not realised
            if (currentPage >= GetMinPageIndex() && currentPage <= GetMaxPageIndex())
            {
                // Current page is realised
                if (currentPage != 0)
                {
                    ScrollIntoView(0);
                }
                else if (currentPage != PageCount - 1)
                {
                    ScrollIntoView(PageCount - 1);
                }
            }
        }
        finally
        {
            _isSettingPageVisibility = false;

            ScrollIntoView(currentPage);
        }
    }
```

After investigation, it is my understanding that the problem comes from the `VirtualizingStackPanel.MeasureOverride(..)`:

The `CalculateDesiredSize(...)` is called before the `_lastEstimatedElementSizeU` variable is set (i.e. the default value 25 is used).

I will create a PR to fix this issue

### To Reproduce

See https://github.com/BobLd/Caly

I'm currently using a hack in `PdfPageItemsControl` (see `EnsureScrollBars()`)

I you comment this code and open a pdf document with the app, you will see that the vertical scroll bar is not correct

### Avalonia version

11.2.0

**Comment by BobLd** [comment]
Closing as issue is not complete and cannot be reproduced as such

**Comment by Whiletru3** [comment]
Hi,

Can it be backported to 11.2.x ?

**Comment by BobLd** [comment]
@Whiletru3 I've asked the team on Telegram, apparently it will be for 11.3.0 (I'd also be interested in having the fix in the current version)

Maybe @timunie can give more details

**Comment by timunie** [comment]
We can consider to backport if paying customer asks for it. Otherwise, no. Everyone can consume nightly if a fix is urgently needed.
