### ISSUE TITLE
Window.ShowDialog frozen application on MacOSX

### ISSUE THREAD

**Issue by ficnar** [AvaloniaUI/Avalonia#1747]
When I open window as dialog by Window.ShowDialog then application frozen.
This occurs only on MacOSX. On Windows and Linux it works properly.

**Comment by CommonGuy** [comment]
Maybe use https://developer.apple.com/documentation/appkit/nsapplication/1428418-beginmodalsession?

**Comment by WojciechKrysiak** [comment]
This was fixed with #1804, but there's a rework of MacOSX backend comming up
