### ISSUE TITLE
Window.SizeToContent="Height" not work on Linux

### ISSUE THREAD

**Issue by ficnar** [AvaloniaUI/Avalonia#1748]
When I set Window.SizeToContent="Height" then after show window is the height of window correct. But when next I change content, for example, increase the length of text in content, the height of the window not changed.
This occurs only on Linux (I tried on CentOS). On Windows and MaxOSX its work properly.

**Comment by ficnar** [comment]
Any progress on this old issue?

**Comment by kekekeks** [comment]
The problem is that resize on X11 is an asynchronous operation. Unfortunately the guy who actually knows how autosizing works only uses Windows.

So, no, no progress yet.
