### ISSUE TITLE
Avalonia.Win32 causes Invalid IL in Avalonia.Android projects starting from version Win32 v11.1.0

### ISSUE THREAD

**Issue by anose001** [AvaloniaUI/Avalonia#17481]
### Describe the bug

We are facing an issue where the Avalonia.Win32 package version 11.1.0 and higher causes a runtime exception in an Avalonia.Android compiled project. The same versions work properly in Avalonia desktop projects. The last known working version for Android is 11.0.13.

```
System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.InvalidProgramException: Invalid IL due to: method Avalonia.Win32.DComposition.Impl.__MicroComIDCompositionDeviceVTable:CreateTargetForHwnd (void*,intptr,bool,void**) with UnmanagedCallersOnlyAttribute has non-blittable parameters or return type assembly:<unknown assembly> type:<unknown type> member:(null)
   at Avalonia.Win32.DComposition.Impl.__MicroComIDCompositionDeviceVTable..ctor()
   at Avalonia.Win32.DComposition.Impl.__MicroComModuleInit()
   at <Module>..cctor()
   --- End of inner exception stack trace ---
   at Project.Android.MainActivity.CustomizeAppBuilder(AppBuilder builder) in Project.Android\MainActivity.cs:line 53
   at Avalonia.Android.AvaloniaMainActivity.InitializeAvaloniaView(Object initialContent)
   at Avalonia.Android.AvaloniaActivity.OnCreate(Bundle savedInstanceState)
   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Activity.cs:line 3082
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121
```

### To Reproduce

1. Create an Avalonia.Android project.
2. Install Avalonia.Win32 version 11.1.0 or later.
3. Use Avalonia.Win32 in the MainActivity class as shown in the code snippet below.
4. Build and run the project.
5. Observe the runtime exception described above.

```csharp
using Avalonia.Win32;

public class MainActivity : AvaloniaMainActivity<App>
{
    protected override AppBuilder CustomizeAppBuilder(AppBuilder builder)
    {
        return base.CustomizeAppBuilder(builder)
            .WithInterFont()
            .With(new AngleOptions
            {
                GlProfiles = new[] { new GlVersion(GlProfileType.OpenGLES, 3, 2) }
            })
            .UseReactiveUI();
    }
}

```

### Expected behavior

The Avalonia.Win32 package should be compatible with Avalonia.Android projects, without causing runtime exceptions.

### Avalonia version

starting from 11.1.0

### OS

Android

### Additional context

The issue does not occur with Avalonia.Win32 version 11.0.13.
The issue manifests only in Android projects, not in desktop projects.

Avalonia.Win32 Working Version: 11.0.13
Avalonia.Win32 Failing Versions: 11.1.0 and 11.2.0
Operating System: Android
Framework: .NET 8.0

**Comment by maxkatz6** [comment]
Avalonia.Win32 shouldn't be referenced in your projects. It's also not included by default.

> Install Avalonia.Win32 version 11.1.0 or later.

Why do you install Win32 in Android project?

**Comment by maxkatz6** [comment]
Also, why do you set AngleOptions in Android project? It will be ignored there.

**Comment by anose001** [comment]
I was under the impression that on earlier releases of Avalonia I can set the Angle version on Android like above. At least that seemed to work like that. Can I not set the version at this point?

On Desktop, while experimenting, I used Win32 to use OpgenGL 4.x like below. This is where this originally stems from.

```
win32Options = new Win32PlatformOptions
  {
      RenderingMode = new[] { Win32RenderingMode.Wgl }, // this is OpenGL with GPU rendering
      WglProfiles = new[] { glVersion }
  };

  return AppBuilder.Configure<App>()
      .UsePlatformDetect()
      .With(win32Options)
      .WithInterFont()
      .UseReactiveUI();
```

So you are suggest to remove the Win32 dependency and I guess Avalonia automatically decides what OpenGL ES version is running?

**Comment by maxkatz6** [comment]
Yes, `AngleOptions` is no-op on Android, as "angle-gl" is windows specific library.
