### ISSUE TITLE
Mouse wheel is not implemented for the GTK platform.

### ISSUE THREAD

**Issue by ncarrillo** [AvaloniaUI/Avalonia#175]

**Comment by DavidKarlas** [comment]
From my understanding to implement this... This method is needed: https://developer.gnome.org/gdk3/3.4/gdk3-Events.html#gdk-event-get-scroll-deltas which is part of GTK+ 3... In GTK2 user can only be notified what scrolling occurred but not for how much...

**Comment by kekekeks** [comment]
Implemented in GTK3 backend
