### ISSUE TITLE
Artifacts on translucent WritableBitmap

### ISSUE THREAD

**Issue by Karnah** [AvaloniaUI/Avalonia#1751]
I drawed translucent WritableBitmap on Bitmap with alpha channel and catched some interesting artifacts. This problem reproduce on Skia and Win32, on Direct2D1 is OK.
![artefacts](https://user-images.githubusercontent.com/6525732/42638079-2e3f2fa6-8606-11e8-80aa-204fa7a20af3.gif)

View:
```
<Grid>
    <Image Source="{Binding Bitmap}" />
    <Image Source="{Binding Background}" />
</Grid>
```

ViewModel:
```
Background = new Bitmap(PATH_TO_BACKGROUND_FILE);

var data = new byte[256 * 256 * 4];
for (int y = 0; y < 256; y++) {
    for (int x = 0; x < 256; x++) {
        var pos = (y * 256 + x) * 4;
        data[pos] = 255;
        data[pos + 1] = 255;
        data[pos + 2] = 255;
        data[pos + 3] = 1;
    }
}

var writeableBitmap = new WriteableBitmap(256, 256, PixelFormat.Rgba8888);
using (var l = writeableBitmap.Lock()) {
    for (var r = 0; r < 256; r++) {
        Marshal.Copy(data, r * l.RowBytes, new IntPtr(l.Address.ToInt64() + r * l.RowBytes), l.RowBytes);
    }
}

WritableBitmap = writeableBitmap;
```
[Background for example](https://avatanplus.com/files/resources/mid/5831d5ebe351215882aba19b.png)

**Comment by danwalmsley** [comment]
@jmacato wasn't this fixed recently? Im sure I read something somewhere...

**Comment by nc4rrillo** [comment]
Weird. Looking into this.

**Comment by Karnah** [comment]
This is how it looks in my application (sorry for huge gifs):
Direct2D1 - all working.
![direct2d1](https://user-images.githubusercontent.com/6525732/44320672-f0480b80-a45c-11e8-96f6-300ec3ebd2f9.gif)

Skia
![skia](https://user-images.githubusercontent.com/6525732/44320681-fb9b3700-a45c-11e8-9bb2-60da617749c9.gif)

Skia with reload image via memory stream. But it seems to me this is a separate bug
![skiawithresave](https://user-images.githubusercontent.com/6525732/44320687-005feb00-a45d-11e8-9bc4-3ded894a5435.gif)


If this can help I can create separate project with this images.

**Comment by nc4rrillo** [comment]
Can you provide a separate project? I believe we just need to clear the SKBitmap to transparent in this case.

**Comment by Karnah** [comment]
@nc4rrillo, here the project - https://github.com/Karnah/Avalonia.SkiaWritableBitmap
I created it with NuGet packages, should I have created from a Avalonia master?

**Comment by ahopper** [comment]
@Karnah I had a quick play with your project, when I flip the endianness of the aural data before loading it into the WriteableBitmap it works fine on Skia. Also I would not assume that .RowBytes is equal to PixelWidth*4, on some platforms it might be padded larger for alignment optimizations.

**Comment by kekekeks** [comment]
Direct2D and Skia backends might different pixel formats on Win32. Check `ILockedFramebuffer.Format` property.

**Comment by Karnah** [comment]
@ahopper, I can't understand, how you did this :C 
@kekekeks, ILockedFramebuffer.Format always PixelFormat.Rgba8888, which I set in WritableBitmap ctor.

**Comment by ahopper** [comment]
@Karnah I just looped through the data just before copying it into the WriteableBitmap and reversed the byte order of every 4 bytes, it appears only the aural data is wrong the other images don't need this. It works both for skia and d2d.

**Comment by Karnah** [comment]
@ahopper, I have wrong color in this situation:
![default](https://user-images.githubusercontent.com/6525732/46408852-f522ff00-c72c-11e8-8231-03eaf9d5df78.PNG)
Should be yellow :)
And d2d is always crashes

**Comment by ahopper** [comment]
@Karnah yep I didn't know what the colour should be but I think the problem is your aural files are just not saved in the correct byte order.  Before the alpha channel was obviously getting one of r,g or b, my first guess has moved the alpha channel to the correct byte but the rgb are now wrongly ordered, the other files appear correct (assuming the character is mainly blue) . On d2d you are probably hitting the image load bug that you can avoid by either not loading the background or updating to the lastest build

**Comment by ahopper** [comment]
I believe this is the same problem as https://github.com/AvaloniaUI/Avalonia/issues/2604 and that the alpha needs pre-multiplying  for the WriteableBitmap

**Comment by Karnah** [comment]
@ahopper, wow! Yes, this is working! I think, my issue is solved and i can close it.
But i would like to ask one question :) Is it possible use one behavior for Skia and Direct2D1 in the future? It was really unexpected for me!

**Comment by Gillibald** [comment]
If the Direct2D1 version isn't using premultiplied alpha it is a bug

**Comment by Karnah** [comment]
@Gillibald, I checked, Direct2D1 works well in both cases. 

So, i close issue. Thanks to all :)

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/f0a8e64189c7bf60ce7486a35e4a0a67ca644d18/src/Windows/Avalonia.Direct2D1/PrimitiveExtensions.cs#L99 we are using Format32bppPBGRA and Format32bppPRGBA pixel formats. Direct2D might be doing some preprocessing after image bits are unlocked.
