### ISSUE TITLE
Unable to type Chinese with pinyin layout

### ISSUE THREAD

**Issue by kerams** [AvaloniaUI/Avalonia#17523]
### Describe the bug

When using the pinyin input method to type Chinese characters on iOS, a text box always holds one character which gets replaced with every key press. The character cannot be deleted either.

### To Reproduce

- Add Chinese Simplified, Pinyin QWERTY keyboard in iOS settings
- Try to type `nihao` in a text box

[rec.webm](https://github.com/user-attachments/assets/acf87352-31d0-44b1-8a05-92a81087ad3b)

### Expected behavior

Text box contains `ni hao`, and `你好` appears in the keyboard toolbar. When pressed, the Chinese characters then replace `ni hao`. See the Safari part in the clip above.

### Avalonia version

11.3.999-cibuild0053328-alpha

### OS

iOS

### Additional context

Possibly related to #16956.

**Comment by Arktische** [comment]
I encountered the same issue on iOS. Seems that only system IME will be affected.

**Comment by Arktische** [comment]
@kerams Hey, I found the solution. It all caused by a stupid indent. 

The original code was like below, it returns the current marked text.
```csharp
string result = "";
// wrong, when _markedText is not null returns empty string, breaks the entire pre-edit logic
if (string.IsNullOrEmpty(_markedText))
    if(surroundingText != null && r.EndIndex < surroundingText.Length)
    {
        result = surroundingText[r.StartIndex..r.EndIndex];
    }
else
{
     // ...
}
Logger.TryGet(LogEventLevel.Debug, ImeLog)?.Log(null, "result: {res}", result);

return result;
```
 And notice the indent, it actually equals to
```csharp
string result = "";
if (string.IsNullOrEmpty(_markedText))
{
    if(surroundingText != null && r.EndIndex < surroundingText.Length)
    {
          result = surroundingText[r.StartIndex..r.EndIndex];
    }
    else
    {
           // ...
    }
}
Logger.TryGet(LogEventLevel.Debug, ImeLog)?.Log(null, "result: {res}", result);
return result;
```

You just add a correct bracket and it will works with any Chinense characters.
```csharp
        string IUITextInput.TextInRange(UITextRange range)
        {
            var r = (AvaloniaTextRange)range;
            var surroundingText = _client.SurroundingText;

            var currentSelection = _client.Selection;

            Logger.TryGet(LogEventLevel.Debug, ImeLog)
                ?.Log(null, "IUIKeyInput.TextInRange {start} {end}", r.StartIndex, r.EndIndex);

            string result = "";
            if (string.IsNullOrEmpty(_markedText))
            {
                if (surroundingText != null && r.EndIndex < surroundingText.Length)
                {
                    result = surroundingText[r.StartIndex..r.EndIndex];
                }
            }
            else
            {
                var span = new CombinedSpan3<char>(surroundingText.AsSpan().Slice(0, currentSelection.Start),
                    _markedText,
                    surroundingText.AsSpan().Slice(currentSelection.Start));
                var buf = new char[r.EndIndex - r.StartIndex];
                span.CopyTo(buf, r.StartIndex);
                result = new string(buf);
            }

            Logger.TryGet(LogEventLevel.Debug, ImeLog)?.Log(null, "result: {res}", result);

            return result;
        }
```

**Comment by Arktische** [comment]
I believe your related issue #16956  on Android is similar. I'll make a pull request after check

**Comment by Arktische** [comment]
@kerams Hey I made a PR to fix it. Maybe it's helpful to your another issue #16956

**Comment by kerams** [comment]
Fantastic. I'll try it when it's built.
