### ISSUE TITLE
Can not input Chinese in xaml playground

### ISSUE THREAD

**Issue by fallenleavesguy** [AvaloniaUI/Avalonia#17535]
### Describe the bug

Can not input Chinese in xaml playground

### To Reproduce

open [xaml playground](https://play.avaloniaui.net/), then input Chinese in input element.
You will see this:
![image](https://github.com/user-attachments/assets/9452ad45-924b-4e3b-b44f-008eda78d8ce)

### Expected behavior

display what I input

### Avalonia version

11.x.x

### OS

Windows

### Additional context

Chrome 130.0.6723.117 for windows x64 version

**Comment by rabbitism** [comment]
xaml playground does not have embedded font that support Chinese. 
You can try Ursa demo, which works well.
https://irihitech.github.io/Ursa.Avalonia/

**Comment by Ultramund1** [comment]
将中文字体文件加到资源里，将中文字设置为这个字体即可
![1](https://github.com/user-attachments/assets/cb6a2954-efd3-44ca-9fea-1b4705f19398)

**Comment by Gillibald** [comment]
This is a browser sandbox limitation. We do not have access to the system fonts. This might change some day for chromium-based browsers.
