### ISSUE TITLE
I'm getting XAPRAS7023 when upgrading from 11.2.0 to 11.2.1.

### ISSUE THREAD

**Issue by BobbyCannon** [AvaloniaUI/Avalonia#17542]
### Describe the bug

I'm getting XAPRAS7023 when upgrading from 11.2.0 to 11.2.1.

error XAPRAS7023: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Workspaces\BobsToolbox\BobsToolbox\BobsToolbox.Android\obj\Debug\net9.0-android\Avalonia\Avalonia\BobsToolbox.Android.dll'.

I think the problem is that Avalonia is listed twice (\Avalonia\Avalonia\)...

> \obj\Debug\net9.0-android\Avalonia\Avalonia\BobsToolbox.Android.dll

Should be

> \obj\Debug\net9.0-android\Avalonia\BobsToolbox.Android.dll

### To Reproduce

Change the version of AvaloniaVersion in the Directory.Build.props file from 11.2.0 to 11.2.1.

### Expected behavior

Upgrade should just work.

### Avalonia version

11.2.1

### OS

Windows

**Comment by maxkatz6** [comment]
Please try nightly build from this PR https://github.com/AvaloniaUI/Avalonia/pull/17539#issuecomment-2481337267

**Comment by BobbyCannon** [comment]
problem still exist in 11.2.2, is fixed in nightly build 11.3.999-cibuild0053376-alpha

**Comment by BobbyCannon** [comment]
problem still exists in 11.2.3

**Comment by timunie** [comment]
Not everything can be backported. Some will only be on customer request. So if you have paid support please ask for a backport or stay at nightly until 11.3

**Comment by BobbyCannon** [comment]
What this an accident? @timunie what do you mean back backport?

**Comment by rubiomiguel06** [comment]
For the record, and as I mentioned [here](https://github.com/AvaloniaUI/Avalonia/discussions/17250#discussioncomment-12646306), this issue is still present in 11.2.5. In my particular case, only when adding an `<AvaloniaResource>` to the .csproj file.
Manually copying and pasting the contents of `[..]\obj\Debug\net9.0-android\Avalonia\` to `[...]\obj\Debug\net9.0-android\Avalonia\Avalonia\` makes it work

**Comment by MrJul** [comment]
This should be definitely fixed by #17539, which will be in 11.3.0.
