### ISSUE TITLE
IActivatableLifetime doesn't work on MacOS

### ISSUE THREAD

**Issue by JamesSmith85** [AvaloniaUI/Avalonia#17561]
### Describe the bug

I have updated the Avalonia version in my application from an older nightly build to 11.4.1 (The issue can be reproduced from 11.1.0 to 11.2.1).

I had to update my code as `IActivatableApplicationLifetime` interface doesn't exist anymore, but I can use `TryGetFeature<IActivatableLifetime>()` instead.
The new code successfully finds the feature and subscribe to its event, but sadly the behavior changed.
`Deactivated` event never gets called, at least in the scenario where it was called before now it is not.

### To Reproduce

1. Create a new Avalonia app.
2. Hide it from macOS's Dock.
3. Deactivated event is not called (Activated is called instead)

Simple repo:

```
 public MainViewModel()
    {
        if (Application.Current?.TryGetFeature<IActivatableLifetime>() is { } activatableLifetime)
        {
            activatableLifetime.Activated += OnActivated;
            activatableLifetime.Deactivated += OnDeactivated;
        }
        
    }

    private void OnActivated(object? sender, ActivatedEventArgs e)
    {
        Console.WriteLine("Activated");
    }
    
    private void OnDeactivated(object? sender, ActivatedEventArgs e)
    {
        Console.WriteLine("Deactivated");
    }
```

### Avalonia version

11.1.0 - 11.2.1

### OS

macOS

**Comment by maxkatz6** [comment]
Can you confirm, that subscribing earlier doesn't solve the problem?
For example, in OnFrameworkInitializationCompleted method.

**Comment by maxkatz6** [comment]
You are right. It should call OnDeactived from OnHide method:
https://github.com/AvaloniaUI/Avalonia/blob/a7c3ad9e8a3087ac37070e14bd354f5644c24f7e/src/Avalonia.Native/AvaloniaNativeApplicationPlatform.cs#L89-L103
