### ISSUE TITLE
`IsVisible` binding without a path is not applied

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#17587]
### Describe the bug

A binding without a property path applied to `IsVisible` will not be evaluated. The control will remain visible when it should be hidden.

Adding a path of `$self.DataContext` works around the issue.

### To Reproduce

Start Sandbox with this window XAML:

``` xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'
        x:Class="Sandbox.MainWindow" x:CompileBindings="False">
  <StackPanel>
    <Border IsVisible="{Binding, Converter={x:Static ObjectConverters.IsNotNull}}" Height="19" Background="Red" />
    <Border IsVisible="{Binding $self.DataContext, Converter={x:Static ObjectConverters.IsNotNull}}" Height="19" Background="Green" />
  </StackPanel>
</Window>
```

You will see this:

![image](https://github.com/user-attachments/assets/1dbc775e-e249-41d8-9540-3097548a432c)

### Expected behavior

The `Border` with the red background should not be visible.

### Avalonia version

11.2.1

### OS

Windows

### Additional context

Not reproducible in 11.1.x

**Comment by stevemonaco** [comment]
AFAIK, objects can't notify for themselves, only their properties. Hence `INotifyPropertyChanged`. When you use `{Binding}` which has no path to a property, then you should think of this as a get-only property fetched only when the View itself demands it (ie. on object initialization for a `Control` or on command execution for `CommandParameter`). The binding system doesn't have access to a parent object and therefore won't be aware of when it changes.

**Comment by robloo** [comment]
Note that Avalonia has had a long-standing issue with changing DataContexts. I have several places in code where I needed to set a DataContext first to null then to the new view model instance. That is loosely related to the discussion above and I wonder if it might be fixed at the same time.
