### ISSUE TITLE
After upgrading to version 11.2.1, the usercontrol response speed has become very slow.

### ISSUE THREAD

**Issue by nipeone** [AvaloniaUI/Avalonia#17585]
### Describe the bug

I designed a usercontrol to display search images and text content. Each page shows 20 records, and each record is wrapped in the usercontrol. With version 11.2.0, resizing the mainform was very smooth, but after upgrading to version 11.2.1, the response speed has significantly slowed down, and it feels very laggy.

### To Reproduce

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             x:Class="OmnipocketLiteAvalonia.SearchResultItem">
    <Border BorderBrush="{DynamicResource SystemControlForegroundBaseMediumBrush}" 
            BorderThickness="1" Margin="0,0,0,10" Padding="10" CornerRadius="15">
        <Grid ColumnDefinitions="Auto,*">
            <Image Grid.Column="0"
				   x:Name="DocTypeImage"
				   Width="64"
				   Height="64"
				   Margin="0,0,10,0" />
            <StackPanel Grid.Column="1">
                <TextBlock x:Name="TextContent"
						   TextWrapping="Wrap"
                           Foreground="{DynamicResource SystemControlForegroundBaseHighBrush}"
                           Margin="0,0,0,5"/>
                <Separator Height="1"
						   Margin="0,5,0,5"
                           Background="{DynamicResource SystemControlForegroundBaseLowBrush}"/>
                <Button x:Name="FilePathButton" 
                        Foreground="{DynamicResource SystemControlForegroundBaseMediumBrush}" 
                        FontStyle="Italic"
                        Background="Transparent"
						BorderThickness="0"
						Padding="0"
                        HorizontalAlignment="Left"
						Cursor="Hand"/>
            </StackPanel>
        </Grid>
    </Border>
</UserControl>
```

### Avalonia version

11.2.1

### OS

Windows

**Comment by timunie** [comment]
@nipeone please provide a full minimum sample to reproduce. Also I wonder how you set the data, are you doing it in code behind? Is the image loading async?

**Comment by nipeone** [comment]
@timunie thks you reply, i upload code here [example code](https://github.com/nipeone/OmnipocketLite)

**Comment by nipeone** [comment]
i have found another problem.In 11.1.5, my settings button and theme button icon was displayed perfectly, but in versions 11.2.0 and 11.2.1, there were some missing.
11.1.5:
![1732349771202](https://github.com/user-attachments/assets/4227aa36-8c57-414c-9a5c-61b9604ec298)
11.2.*
![1732349846671](https://github.com/user-attachments/assets/778e80a6-dda6-49a1-9cd4-62ca49700201)

**Comment by MrJul** [comment]
The slowness in 11.2.1 is fixed by https://github.com/AvaloniaUI/Avalonia/pull/17519 - this fix will be part of 11.2.2.

**Comment by robloo** [comment]
Note that slowness of custom controls has been an older issue as well. I have custom controls that are very slow during debug and blazing fast at release. I seem to recall reading some time ago (By @TomEdwardsEnscape perhaps) there was suspicion that debug outputs, diagnostics or logging were slowing things down quite a bit but I personally never bothered to dig into it more.

Long story short -- do let us know if the above issue doesn't fix the problem.

**Comment by nipeone** [comment]
@robloo yes, update to 11.2.2, the problem of slowness has addressed.
