### ISSUE TITLE
ItemsControl with userontrols collection doesn't work.

### ISSUE THREAD

**Issue by Alexbeerses** [AvaloniaUI/Avalonia#17643]
### Describe the bug

I used Avalonia ItemsControl in my project with Avalonia 11.0.10. ItemsControl worked fine with my own viewmodel usercontrols. The update to 11.2.2 broke this scenario. 

```xml
<Window
    x:Class="AvaloniaItemsControlTest.Views.MainWindow"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:v="using:AvaloniaItemsControlTest.Views"
    xmlns:vm="using:AvaloniaItemsControlTest.ViewModels"
    Title="AvaloniaItemsControlTest"
    d:DesignHeight="450"
    d:DesignWidth="800"
    Height="400"
    Width="400"
    x:DataType="vm:MainWindowViewModel"
    Icon="/Assets/avalonia-logo.ico"
    mc:Ignorable="d">

    <ItemsControl ItemsSource="{Binding PanelPages}">
        <ItemsControl.ItemTemplate>
            <DataTemplate DataType="vm:PageViewModel">
                <StackPanel Margin="0,0,0,10" Orientation="Vertical">
                    <v:Page DataContext="{Binding}" />
                </StackPanel>
            </DataTemplate>
        </ItemsControl.ItemTemplate>
    </ItemsControl>

</Window>
```

```cs
using CommunityToolkit.Mvvm.ComponentModel;
using System.Collections.ObjectModel;

namespace AvaloniaItemsControlTest.ViewModels;

public partial class MainWindowViewModel : ViewModelBase
{
    //-----------------------------------------------------------------------------------------------
    [ObservableProperty]
    public string _TestText = "Binding Text ";

    [ObservableProperty]
    ObservableCollection<PageViewModel> _PanelPages = [];
    //-----------------------------------------------------------------------------------------------

    public MainWindowViewModel()
    {
        for (int i = 0; i < 3; i++)
            PanelPages.Add(new PageViewModel(TestText + i));
    }
    //-----------------------------------------------------------------------------------------------
}
```

```xml
<UserControl
    x:Class="AvaloniaItemsControlTest.Views.Page"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:vm="using:AvaloniaItemsControlTest.ViewModels"
    d:DesignHeight="450"
    d:DesignWidth="800"
    x:DataType="vm:PageViewModel"
    mc:Ignorable="d">

    <Border
        Grid.Row="0"
        Margin="10,10,10,0"
        BorderBrush="#D1D1D1"
        BorderThickness="1"
        CornerRadius="10">

        <TextBlock
            Margin="5,5,5,5"
            HorizontalAlignment="Left"
            VerticalAlignment="Top"
            Text="{Binding TestText}" />
    </Border>
</UserControl>
```
```cs
namespace AvaloniaItemsControlTest.ViewModels;

public partial class PageViewModel : ViewModelBase
{
    //-----------------------------------------------------------------------------------------------
    [ObservableProperty]
    public string _TestText = "TestText";
    //-----------------------------------------------------------------------------------------------

    public PageViewModel(string text)
    {
        TestText = text;
    }
    //-----------------------------------------------------------------------------------------------
}
```

Programm incorrect behavior:
![55555](https://github.com/user-attachments/assets/45e03cb5-0f11-46e3-8bb9-3e4003805604)

I have created a test project to show the issue.
[https://drive.google.com/file/d/13O38Ea1-MfUSdeA6OBNF7T2bRSpZCaXx/view?usp=sharing](url)

### To Reproduce

1) Create your own viemodel user control.
2) Create its instances collection in other viemodel control.
3) Try to place this collection with ItemsControl.

### Expected behavior

![777777777777777777](https://github.com/user-attachments/assets/e228a61c-ec95-44cb-b12f-4008bf90bd5a)

### Avalonia version

11.2.2

### OS

Windows, Linux

**Comment by timunie** [comment]
DataContext="{Binding}"

This assignment is probably useless. Could you test it without this? I don't say it shouldn't, it should. But may be a workaround for the moment.

**Comment by Alexbeerses** [comment]
> DataContext="{Binding}"
> 
> This assignment is probably useless. Could you test it without this? I don't say it shouldn't, it should. But may be a workaround for the moment.

This assignment isn't useless. It binds the usercontrol datacontext with viemodel instance of datacontexts collection (PanelPages) of parent control.

[https://docs.avaloniaui.net/docs/basics/data/data-binding/data-binding-syntax](url)
Empty Binding Path
You can specify data bindings without a Path. This binds to the DataContext of the Control itself (where the binding is defined). These two syntaxes are equivalent:
<TextBlock Text="{Binding}" />
<TextBlock Text="{Binding .}" />	

I really don't konow how to bind it another way in ItemsControl.ItemTemplate. In Avalonia 11.0.10 it worked fine.
Could you suggest another way of binding?

**Comment by timunie** [comment]
Again, you may not need a binding here at all since it should inherit DataContext automatically. Typically that should magically work. If not, I will try to check your sample the other day

**Comment by Alexbeerses** [comment]
> Again, you may not need a binding here at all since it should inherit DataContext automatically. Typically that should magically work. If not, I will try to check your sample the other day

I understand now.
The solution is:
```xml
<ItemsControl ItemsSource="{Binding PanelPages}">
        <ItemsControl.ItemTemplate>
            <DataTemplate DataType="vm:PageViewModel">
                <StackPanel Margin="0,0,0,10" Orientation="Vertical">
                    <v:Page />
                </StackPanel>
            </DataTemplate>
        </ItemsControl.ItemTemplate>
    </ItemsControl>
```
Thank you very much!

**Comment by timunie** [comment]
Close as duplicate
