### ISSUE TITLE
Unable to bind to attached property from style

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1764]
Repro commit here:
https://github.com/AvaloniaUI/Avalonia/tree/repro/binding-attached-property-from-style

xaml:
```
<Window xmlns="https://github.com/avaloniaui" MinWidth="500" MinHeight="300"
        Title="Avalonia Control Gallery"
        Icon="resm:ControlCatalog.Assets.test_icon.ico?assembly=ControlCatalog"
        xmlns:local="clr-namespace:ControlCatalog">
    <Window.Styles>
        <Style Selector="local|MainView">
            <Setter Property="local:MyControl.Proportion" Value="{Binding Proportion}" />
        </Style>
    </Window.Styles>
    <local:MainView/>
</Window>
```

throws an exception https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/AvaloniaPropertyRegistry.cs#L126

hope its an easy fix :)

**Comment by wieslawsoltes** [comment]
@grokys @jkoritzinsky This is big thing missing for the Dock control, more detail is in this issue https://github.com/wieslawsoltes/Dock/issues/47
