### ISSUE TITLE
Programatically changed resources at runtime is broken

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1765]
Code such as:https://github.com/VitalElement/AvalonStudio.Shell/blob/master/src/AvalonStudio.Shell.Extensibility/Theme/ColorTheme.cs#L100

no longer updates the ui at runtime.

**Comment by jkoritzinsky** [comment]
Any chance you have a smaller repro than AvalonStudio? I having some trouble reproing this.

**Comment by danwalmsley** [comment]
Just put that line in control catlog and override like border colour or something

**Comment by danwalmsley** [comment]
Its nothing specific to my app, its any resource cannot be changed at runtime anymore

**Comment by Gillibald** [comment]
Is this still an issue? Just tried to change a DynamicResource in code and everything updated properly.

**Comment by Gillibald** [comment]
I have found out that DynamicResources work and produce updates in the UI on change. The part that doesn't work is the propagation of the change to other dictionaries. DynamicResource only works if you change the resource in the dictionary it was originaly defined in. I hope that helps.

**Comment by danwalmsley** [comment]
@grokys os that a bug or newly intwnded behavior, i could update globally before.

**Comment by grokys** [comment]
No, this isn't intended behavior, and in fact I cannot repro this behavior. I'd have to debug AvalonStudio to see what's happening unless you can provide a simple repro?

**Comment by danwalmsley** [comment]
Ill work on one

**Comment by grokys** [comment]
@danwalmsley i will try reproing this next week. Could you give some details of how to trigger it?

**Comment by danwalmsley** [comment]
1) clone recursively https://github.com/VitalElement/AvalonStudio.git (if you have a copy from a long time, probably easiest just to delete as submodule urls may have changed and other things that could complicate the process)

2) open in visual studio

3) build just the AvalonStudio project

4) enable either source link on avalonia, or use the /scripts/ReplaceNugetCache.ps1 to add your locally build copy of avalonia to nuget cache dir.

`ReplaceNugetCache.ps1 0.6.2-build6362-beta`

5) In visual studio run the AvalonStudio project inside the debugger
AvalonStudio will open...
![image](https://user-images.githubusercontent.com/4672627/46729516-7888a700-cc7d-11e8-9a6f-87caf361ddc2.png)

6) Click Tools->Options
![image](https://user-images.githubusercontent.com/4672627/46729565-9a822980-cc7d-11e8-9e46-6baf10741e04.png)

Change the color scheme selection to Light or Dark, the UI should update the colours.

You can put a breakpoint on ColorThreme.cs line 100 (https://github.com/VitalElement/AvalonStudio.Shell/blob/master/src/AvalonStudio.Shell.Extensibility/Theme/ColorTheme.cs#L100)

so see the point where avalonia has its app resources updated.

This did work before but broke at somepoint so Im hoping its probably an easy fix.

Ping me if you need help with the repro
