### ISSUE TITLE
Slider stops working.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#1775]
Repro:

- Run ControlCatalog
- Go to Slider page
- Click on slider track to move thumb (don't drag it)
- Go to LayoutTransformControl page
- Drag Rotation slider
- It is broken

**Comment by wdcossey** [comment]
Avalonia.Controls.Slider.cs

Original code:
```
        private void MoveToNextTick(double value)
        {
            double next = SnapToTick(Math.Max(Minimum, Math.Min(Maximum, value)));
            if (next != value)
            {
                Value = next;
            }
        }
```

The issue with the above code is that **next** & **value** will always be the same.

Modified code:
```
        private void MoveToNextTick(double value)
        {
            double next = SnapToTick(Math.Max(Minimum, Math.Min(Maximum, value)));
            Value = next;
        }
```
Since the property Value will always check the value before raising the PropertyChanged event, this workaround should suffice.
