### ISSUE TITLE
TextAlign="Center" TextBox strange behavior

### ISSUE THREAD

**Issue by Muny** [AvaloniaUI/Avalonia#1776]
![Demonstration](https://pcbx.us/muny/cfin.gif)
I've noticed some interesting behavior with the TextBox element. The TextAlign property is set to "Center". When there is no text present, or if just the Watermark is showing, the text and cursor will not respect the Center align property. It behaves as-expected once text is entered.

**Comment by Muny-** [comment]
Just noticed there is similar behavior with right-aligned text.

![Demonstration](https://pcbx.us/cfip.gif)

**Comment by grokys** [comment]
Mostly fixed in current `master` but there still seems to be an issue with the caret not showing on an empty `TextBox` with right-aligned text. @Gillibald are you able to repro?

**Comment by Gillibald** [comment]
Will have a look

**Comment by Gillibald** [comment]
Fixed in master
