### ISSUE TITLE
In all the avalonia versions I've used, GeometryDrawing has a bug in dynamically changing the color of the brush.

### ISSUE THREAD

**Issue by ApaulMyLittleAirport** [AvaloniaUI/Avalonia#17770]
### Describe the bug

When I bind colors and dynamic color resources to the Brush in my GeometryDrawing, the Brush can't change the color, and I have to force the InvalidateVisual method to do so. But in WPF there is no such problem. I submitted both the avalonia demo and the wpf demo.
[avaloniaApp.zip](https://github.com/user-attachments/files/18135853/avaloniaApp.zip)
[WpfApp.zip](https://github.com/user-attachments/files/18135856/WpfApp.zip)

### To Reproduce

Run the software by clicking the ChangeColor button

### Expected behavior

Same as WPF 

### Avalonia version

ALL

### OS

Windows

**Comment by TomEdwardsEnscape** [comment]
This is the same issue as #8767. I worked around this by creating a `DrawingImage` which subscribes to changes in the drawing(s) it displays.

**Comment by ApaulMyLittleAirport** [comment]
> 这与 #8767 的问题相同。我通过创建一个订阅它显示的绘图中的更改来解决这个问题。`DrawingImage`

Thank you very much for your help, can I ask if there is any latest progress in fixing this bug?

**Comment by timunie** [comment]
Closing this as duplicate. 

In case you have paid support, you can ask for priority on bug fixes. PRs are also welcome. Otherwise it's done when it's done.
