### ISSUE TITLE
Unicode text rendering is cut mid way

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#17795]
### Describe the bug

Since recent changes (something from 26.11 to now), icon characters (Tested with `Segoe MDL2 Assets`) do not render properly.
![image](https://github.com/user-attachments/assets/2f029140-2049-4c8b-8f36-a5e7dc8ac91b)
![image](https://github.com/user-attachments/assets/818d860b-e8c3-482f-9e8a-fa9a6a181c7f)

### To Reproduce

Easy way to reproduce with Control Catalog is to replace in `ComboBox.xaml` - 
```
  <PathIcon x:Name="DropDownGlyph"
                      Grid.Column="1"
                      UseLayoutRounding="False"
                      IsHitTestVisible="False"
                      Height="12"
                      Width="12"
                      Margin="0,0,10,0"
                      HorizontalAlignment="Right"
                      VerticalAlignment="Center"
                      Foreground="{DynamicResource ComboBoxDropDownGlyphForeground}"
                      Data="M1939 486L2029 576L1024 1581L19 576L109 486L1024 1401L1939 486Z"/>
```
with 
```
  <TextBlock x:Name="DropDownGlyph"
                      Grid.Column="1"
                      UseLayoutRounding="False"
                      IsHitTestVisible="False"
                      Height="12"
                      Width="12"
                      Margin="0,0,10,0"
                      HorizontalAlignment="Right"
                      VerticalAlignment="Center"
                      FontFamily="Segoe MDL2 Assets"
                      Foreground="{DynamicResource ComboBoxDropDownGlyphForeground}"
                      Text="&#xE70D;"/>
```

### Expected behavior

Unicode icons to display properly.

### Avalonia version

master

### OS

Windows

**Comment by Gillibald** [comment]
I can't see any issue here. You are explicitly limiting the width of TextBlock to 12 and the glyph is wider

**Comment by adirh3** [comment]
@Gillibald I apologize, the issue is only happening with Fluent Avalonia theme, it doesn't repro with Avalonia control catalog.
I messed up when trying to reproduce it with the control catalog.

It seems like recent fixes you made caused FluentAvalonia icons to not be aligned, probably due to some of the custom rendering they do with icons.

Sorry again and thanks for the great work on text rendering!
