### ISSUE TITLE
Android can not full screen

### ISSUE THREAD

**Issue by znoliver** [AvaloniaUI/Avalonia#17791]
### Describe the bug

I use Avalonia develop an Android, when version is  Avalonia 11.1.0 , app can full screen ,but when update to 11.2, can not.
My code:
![image](https://github.com/user-attachments/assets/dcf41a80-f733-45a0-a1bd-8f6a44699512)

### To Reproduce

1. Create a crossplantfrom applicaiton.
2. run in android, can full screen.
3. update all avalonia nuget to 11.2.2
4. run in android, can not full screen.

### Avalonia version

11.2.2

### OS

Android

**Comment by emmauss** [comment]
Use the InsetsManager(retrieved from Toplevel) to configure full screen.

**Comment by znoliver** [comment]
> Use the InsetsManager(retrieved from Toplevel) to configure full screen.

I set IsSystemBarVisible, but not effect
![image](https://github.com/user-attachments/assets/83d3572b-5cc2-423a-9404-06e83714121f)

**Comment by znoliver** [comment]
> > Use the InsetsManager(retrieved from Toplevel) to configure full screen.
> 
> I set IsSystemBarVisible, but not effect ![image](https://private-user-images.githubusercontent.com/59060212/396745498-83d3572b-5cc2-423a-9404-06e83714121f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0OTUwODMsIm5iZiI6MTczNDQ5NDc4MywicGF0aCI6Ii81OTA2MDIxMi8zOTY3NDU0OTgtODNkMzU3MmItNWNjMi00MjNhLTk0MDQtMDZlODM3MTQxMjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA0MDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMzJlZTBlM2M1NDJmYzBkYTQ3OTk4ODM5ZGE5ZGMyNzE1ZmU5MzNkYzYzZDlhNTYwMjdlMjdhMTJiNzcwYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6nXU25z9SvNjanQtequZkG5VHfJnljHTrmL7Nmi8t7E)

I solved this problem. InsetsManager should used in Loaded Event:
![image](https://github.com/user-attachments/assets/c0f1f181-d9f7-461f-876b-1bb8cec4a8d1)
