### ISSUE TITLE
WindowNotificationManager with NotificationPosition.BottomCenter incorrectly opens at the top

### ISSUE THREAD

**Issue by lebhero** [AvaloniaUI/Avalonia#17818]
### Describe the bug

 There is an issue with the WindowNotificationManager control in Avalonia when using the NotificationPosition.BottomCenter setting. While the notification is expected to appear at the bottom center of the window, it instead opens at the top of the window. Other NotificationPosition values (e.g., TopLeft, BottomLeft, etc.) work as expected. This behavior seems to be specific to BottomCenter.

### To Reproduce

```
_windowNotificationManager = new WindowNotificationManager(mainWindow)
{
    MaxItems = 3,
    Position = NotificationPosition.BottomCenter
};
var not = new Notification("Test", "this is a test notification message", NotificationType.Warning);
_windowNotificationManager.Show(not);

```

### Expected behavior

The notification should appear at the bottom center of the window when the NotificationPosition.BottomCenter setting is used, with its position adjusted appropriately at the bottom edge of the window.

### Avalonia version

11.2.3

### OS

Windows

**Comment by rabbitism** [comment]
![image](https://github.com/user-attachments/assets/85a10162-7cab-4244-a04a-829afb20fc4a)

It works well in demo. Which theme are you using?

**Comment by lebhero** [comment]
@rabbitism : sorry, my mistake ... i am using FluentAvaloniaTheme...
