### ISSUE TITLE
TextBlock uses Run to concatenate Text values, which in certain cases may not be displayed

### ISSUE THREAD

**Issue by ms1094392787** [AvaloniaUI/Avalonia#17828]
### Describe the bug

![1](https://github.com/user-attachments/assets/8246b9b5-d6e3-438d-a052-0ee7f3c5b81f)
Above is my code to verify the problem
![2](https://github.com/user-attachments/assets/70f8bc59-874b-4f4b-88f4-d19d2a4bf36a)
This is the normal effect
![3](https://github.com/user-attachments/assets/b1ba5668-72c1-44fc-8fb0-3e84f1b089c2)
If there is a problem, you can see that the purple text is displayed normally. But the use of "Run" concatenation is already small

### To Reproduce

I am using version "11.2.3". I currently have two views, one is empty and the other is this TextBlock page. This bug occurs when I switch between the two pages using the "RoutedViewHost" control

### Avalonia version

11.2.3

### OS

Windows

### Additional context

![image](https://github.com/user-attachments/assets/43a59bb4-b52c-4e67-aa43-d09278cfc61c)
This is everything I use Nuget package

**Comment by ms1094392787** [comment]
As if the above steps didn't cause the bug to reappear, I used a widget that controls the size of the region. Only when the original size is changed, the "RoutedViewHost" control switch will cause the "RUN" concatenated Text not to display

**Comment by ms1094392787** [comment]
But in my project it was stable and reproducible, and I can confirm that there were certain conditions that caused problems with "RUN"

**Comment by Gillibald** [comment]
Whitespace is always normalized within the TextBlock's content. So you get an extra space for the linebreak within the XAML. Write everything on one line an it should work as you want.

**Comment by ms1094392787** [comment]
What I'm actually trying to do is use the two Text parts of the two "runs" to concatenate the number with the unit after the number like (°).

**Comment by timunie** [comment]
I suggest to use a converter for it instead tbh.

**Comment by ms1094392787** [comment]
Ok, thank you for your advice. I know there are many ways to concatenate this string, and I've used other ways to avoid this problem in my project, but I was just wondering why the "run" concatenation had this problem.
