### ISSUE TITLE
When using resx as a localized resource file, it cannot be published in browser mode, and an error message will be displayed: Can't find the original satellite assembly in the list of resolved files to publish for asset

### ISSUE THREAD

**Issue by xuxiaokang0723** [AvaloniaUI/Avalonia#17824]
### Describe the bug

![image](https://github.com/user-attachments/assets/462f32e0-8875-4dd2-b5a0-c027b2bed7cd)

### To Reproduce

![image](https://github.com/user-attachments/assets/d406b1e8-bf59-4d4e-bd9b-f06abe8bae59)
The actual resource file is in this directory

### Avalonia version

11.2.2

### OS

WebAssembly

**Comment by timunie** [comment]
See https://github.com/AvaloniaUI/Avalonia/discussions/15223

**Comment by xuxiaokang0723** [comment]
> See #15223

I did solve the problem of not being able to use resx in WASM according to the above solution, but now it is a new problem. It is normal to compile and run in VS. When I need to publish the wasm project, it will always report an error and cannot be published.

**Comment by xuxiaokang0723** [comment]
Now the problem is not that it cannot be used, but that it cannot be published. I created a new cross-platform project. When I added the Resx resource file and executed "dotnet pulish", it would report the error I showed in the screenshot above.

**Comment by xuxiaokang0723** [comment]
> See #15223

Now the problem is not that it cannot be used, but that it cannot be published. I created a new cross-platform project. When I added the Resx resource file and executed "dotnet pulish", it would report the error I showed in the screenshot above.
