### ISSUE TITLE
Expander collapses in VirtualizingStackPanel when scrolled out of the view

### ISSUE THREAD

**Issue by Hunv** [AvaloniaUI/Avalonia#17835]
### Describe the bug

If you have a list of `Expander`s in a `ItemsControl` which is in a `ScrollViewer` and the `ItemsControl` is using a `VirtualizingStackPanel` as `ItemsPanel`, an expanded `Expander` that was scrolled out of the view, collapses when getting out of the view and leaving the space, that was used before emptyat the top of the scrollviewer until scrolled to the top.
![ExpanderCollapse](https://github.com/user-attachments/assets/513a5f80-3bd6-4824-8492-a98a53a768d4)

### To Reproduce

- Create a new Avalonia Project (at least with Desktop App)
- In the `MainView.axaml` paste the following content: 
``` XAML
<ScrollViewer>
  <ItemsControl ItemsSource="{Binding Source}">
    <ItemsControl.ItemTemplate>
      <DataTemplate>
        <Expander HorizontalAlignment="Stretch">
          <Expander.Header>
            <Label Content="{Binding}"/>
          </Expander.Header>
          <TextBlock Text="My Content" Height="100" Background="Red"/>
        </Expander>
      </DataTemplate>
    </ItemsControl.ItemTemplate>
    <ItemsControl.ItemsPanel>
      <ItemsPanelTemplate>
        <VirtualizingStackPanel Orientation="Vertical" />
      </ItemsPanelTemplate>
    </ItemsControl.ItemsPanel>
  </ItemsControl>
</ScrollViewer>
```
- In the `MainViewModel.cs` paste the following content:
``` C#
    private List<string> _Source = new List<string>() { "1", "2", "3", "4", "5", "6", "7", "8", "9" };
    public List<string> Source => _Source;
```
- Run the app, expand and scroll. Maybe you need to make the window size smaller to get into this issue for demonstration.

### Expected behavior

The Expander stays expanded.

### Avalonia version

11.2.3

### OS

Windows

### Additional context

Tested in Windows Desktop App only.

**Comment by timunie** [comment]
That's by design. Virtualization means that a control is destroyed when scrolling out of view. What you could do is to bind to IsExpanded in your ItemViewModel to keep the state.

**Comment by Hunv** [comment]
> That's by design. Virtualization means that a control is destroyed when scrolling out of view. What you could do is to bind to IsExpanded in your ItemViewModel to keep the state.

Thx. I thought it might be like this, but maybe not.
I will implement your suggenstion to store the state in the ItemViewModel.
