### ISSUE TITLE
Why shape Render method is sealed

### ISSUE THREAD

**Issue by lishilei0523** [AvaloniaUI/Avalonia#17840]
public sealed override void Render(DrawingContext context); 

------------------------------------------------------
please remove the sealed

**Comment by timunie** [comment]
That's by design. If you want to override OnRender, please inherit Control. 

See: https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src%2FAvalonia.Samples%2FCustomControls%2FSnowflakesControlSample

> [!TIP]
> For questions please use Telegram or GitHub discussions. If you open bug reports or feature requests please provide as much details as possible, for example why exactly you need this or that API.
