### ISSUE TITLE
MainWindow.KeyDown doesn't register as many keys as KeyUp

### ISSUE THREAD

**Issue by rmanosuthi** [AvaloniaUI/Avalonia#1791]
## System info
OS: Ubuntu 18.04 x64
DE: Cinnamon
Device: MacBook Pro Retina 2014
Hardware Keyboard Layout: Thai
Software Keyboard Layout: Canadian English
.NET Core 2.1.302
Avalonia 0.6.2-build5674-beta

## Problem
The KeyDown event doesn't seem to fire for a lot of keys when typing in English (i.e. none of the letter keys work, some keys display "None" when using e.Key.ToString())
For KeyUp those things seem to work fine.

## KeyDown code
```
this.KeyDown += MainWindow_KeyDown;
void MainWindow_KeyDown(object sender, KeyEventArgs e) {
    Debug.WriteLine(e.Key.ToString());
}
```
## KeyDown output
```
<pressed a> (nothing)
<pressed s> (nothing)
<pressed d> (nothing)
<pressed f> (nothing)
<pressed Esc> Escape
<pressed Tab> None
<pressed Shift> None
```
## KeyUp code
```
this.KeyUp += MainWindow_KeyUp;
void MainWindow_KeyUp(object sender, KeyEventArgs e) {
    Debug.WriteLine(e.Key.ToString());
}
```
## KeyUp output
```
<pressed a> A
<pressed s> S
<pressed d> D
<pressed f> F
<pressed Esc> Escape
<pressed Tab> Tab
<pressed Shift> None
```

**Comment by maxkatz6** [comment]
Cleaning up label a bit, we are not using GTK for input anymore (at least for input), and I believe this issue was fixed.
