### ISSUE TITLE
TextBlock does not render inside TreeViewItem

### ISSUE THREAD

**Issue by MV10** [AvaloniaUI/Avalonia#1794]
TextBlock is working normally elsewhere, just not inside TreeViewItem. Same result on Win, OSX, and Linux.

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Window1" Height="450" Width="800">
  <Panel>
    <TextBlock Margin="10">Outside</TextBlock>
    <TreeView>
      <TreeViewItem Margin="20" Header="Test" IsExpanded="True">
        <TextBlock Margin="30">Inside</TextBlock>
      </TreeViewItem>
    </TreeView>
  </Panel>
</Window>
```

![image](https://user-images.githubusercontent.com/794270/43610835-4b54921e-9675-11e8-9bfd-dd68d543873a.png)

(Is Panel really supposed to be usable? It's abstract in WPF... although I like having a big generic container.)

**Comment by chiefmb** [comment]
not only TextBlock nothing won't render in TreeViewItem.
if you want to have some controll int it, put it in header of a TreeViewItem. Like this:
```xml
<TreeViewItem>
         <TreeViewItem.Header>
              <TextBlock Text="A TextBlock" />
         </TreeViewItem.Header>
</TreeViewItem>
```

**Comment by Gillibald** [comment]
Shouldn't this throw an error like "The property Header is already defined"? That's what is happening here.

**Comment by chiefmb** [comment]
if you had a "Header" so it's not a TextBlock anymore.

**Comment by danwalmsley** [comment]
Iv not had a problem doing that, see https://github.com/VitalElement/AvalonStudio/blob/develop/AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/SolutionExplorerView.paml

**Comment by danwalmsley** [comment]
Header is where you need to put those controls, the content is only for child treeviewitems

**Comment by grokys** [comment]
I think the replies here have explained how to do this so going to close.

> Is Panel really supposed to be usable? It's abstract in WPF... although I like having a big generic container

Yes, `Panel` is not abstract in Avalonia intentionally: you can use it as a container which makes all children fill the entire available space. In WPF one had to use `Grid` which is a more heavyweight control for this, e.g.:

```xml
<Grid>
  <TextBlock>This is how you do it<TextBlock>
  <TextBlock>in WPF<TextBlock>
</Grid>
```

```xml
<Panel>
  <TextBlock>You can also do this<TextBlock>
  <TextBlock>in Avalonia<TextBlock>
</Panel>
```
