### ISSUE TITLE
Issues opening solution with latest VS2017? (v15.7.6)

### ISSUE THREAD

**Issue by MV10** [AvaloniaUI/Avalonia#1797]
I've been debating whether I have the time to try helping out with the project. Today I cloned the repo and to my surprise VS responded with a csproj upgrade notice and a few failures. It also threw an error I haven't seen before. The [build instructions](http://avaloniaui.net/contributing/build) say VS2017 is required so these were surprising to me.

I went ahead with the conversions to see what happens, but as I'm very new to the project I won't PR anything until someone weighs in on the problem. The images below show the error that is thrown whenever I open the SLN, the one-time csproj update notice, and the csproj conversion failures (Android and OSX, everything else converted ok). 

The link on the csproj conversion failures goes to the Xamarian home page, so I'm guessing the Android and iOS projects need some sort of extension installed, or something of that nature? Whatever the fix is, I suppose the build instructions should clarify this. Meanwhile, what else do I need to install to get this to load correctly?

![image](https://user-images.githubusercontent.com/794270/43663385-41cd9e80-9737-11e8-8162-d755bc28bf4f.png)

![image](https://user-images.githubusercontent.com/794270/43663393-49791be6-9737-11e8-9873-79e0e10d060b.png)

![image](https://user-images.githubusercontent.com/794270/43663402-4fba6a28-9737-11e8-980c-ec0966aebfef.png)

**Comment by Gillibald** [comment]
You need to install the modules for mobile development first to be able to open these projects. Just open the visual studio installer and select the mobile development workload.

**Comment by MV10** [comment]
@Gillibald Is anything beyond the basic SDK required?

![image](https://user-images.githubusercontent.com/794270/43678659-56748e9e-97e5-11e8-9325-f08de8fb9f5e.png)

**Comment by Gillibald** [comment]
The android images are just for the emulator. In general the mobile workload should be enough.
