### ISSUE TITLE
Only call popuproot.SnapInsideWindow edges once a popup is in visual tree

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1807]

**Comment by jkoritzinsky** [comment]
@danwalmsley can you remind me what the symptom of this issue was? I can't quite remember at this point.

**Comment by danwalmsley** [comment]
We were getting a crash occassionally, i fixed that, it was because this got called in some cases when this wasnt in visual tree. But you wanted to prevwnt that happening rather than my fix which just put a guard around that condition

**Comment by grokys** [comment]
@danwalmsley is this still an issue? Can you add more description? I can't tell what the problem is.

**Comment by danwalmsley** [comment]
I think this is probably superceeded by the popup rework
