### ISSUE TITLE
Missing Right-to-Left text support

### ISSUE THREAD

**Issue by GihanSoft** [AvaloniaUI/Avalonia#1809]
Please put FlowDirection property in ui elements. i want to build an app that use languages like Arabic and Persian. but I can't change direction. also characters are separated and is like ل‌ع‌ف but they must be فعل.

**Comment by danwalmsley** [comment]
@cheifmb welcome to avalonia. Would you like to attempt a PR for this we always welcome new contributions. If so we are here to assist.

**Comment by jmacato** [comment]
Please mind your language when issuing bug reports.

**Comment by chiefmb** [comment]
I really need this for my app.

**Comment by chiefmb** [comment]
@Gillibald 
Thanks.
I mention one more time.
RtL for Arabic and Persian need letters to gather.
This ف‌ع‌ل is not good.
It must be فعل.
Thank you for your great avalonia

**Comment by jmacato** [comment]
@chiefmb Hi, i was informed by @Gillibald that Bidirectional Text works on windows only (via Direct2D). Can you test the latest Avalonia nightly with your app? It should be capable of handling right-to-left text now, at least on windows that is.

**Comment by JimBobSquarePants** [comment]
Feel free to borrow anything else useful in the codebase in the interim.

**Comment by ShaharMS** [comment]
is this planned to release soon (or present in the master branch)?

I really need RTL and reshaping support for my app, so i just wanna know if i can depend on avalonia/3rd party lib for BiDi

**Comment by maxkatz6** [comment]
@Gillibald can it be closed now? RTL is available in nightly builds.

**Comment by ShaharMS** [comment]
im kinda new to C# libs, so how do i pull an installation from git?

(i come from haxe, there its `haxelib git <libname> <git link>`)

**Comment by Gillibald** [comment]
https://nuget.avaloniaui.net/repository/avalonia-all/index.json

**Comment by grokys** [comment]
Full details on how to do this here: https://github.com/AvaloniaUI/Avalonia#bleeding-edge-builds
