### ISSUE TITLE
Emoji support 👉😎👉 💩

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#1817]
Support emoji in text. Without emoji this framework is not Hipster enough.

😂😂😂

**Comment by jmacato** [comment]
We will need a font fallback mechanism for this to work properly or rewrite the text handling somehow, though i'll defer to @Gillibald & @nc4rrillo for that subject :)

**Comment by Gillibald** [comment]
After we have migrated Direct2D1 to the highest possible version we can work on this. 

The hard thing is we have to do character matching on our own because we use a TextRenderer. 

Skia can support it with the help of some other libraries like Harfbuzz etc.

You can already use emojis if you use a font that supports it we just don't support character fallbacks. Skia even supports colored fonts.

**Comment by prepare** [comment]
Loading Emoji from OpenType font ...

I invite / recommend you to visit this https://github.com/samhocevar/emoji.wpf too.

**Comment by Gillibald** [comment]
Thanks for the link. Seeing how Typography can work in such a environment helps to hopefully get it integrated into Avalonia some time in the future. I would much prefer using Typography for all text processing. We currently don't support visual inlines that are needed for this approach.

**Comment by jairbubbles** [comment]
I played a bit with [Lunacy](https://icones8.fr/lunacy) recently and the emojis were working nicely:

![image](https://user-images.githubusercontent.com/15875066/149668502-bfa81dbc-5769-4f5e-82b6-4252916cf75b.png)

At first I concluded than Avalonia was supporting font Emojis but I then saw that issue. Might be interesting to see how they do it.

There seems to be some restrictions with "joint" emojis:

![image](https://user-images.githubusercontent.com/15875066/149668617-52920c8c-56ed-4d1a-a195-3ca2c558273b.png)

**Comment by Takoooooo** [comment]
Fixed in #4893.

**Comment by atcarter714** [comment]
Emojis seem to work on everything except web assembly. Is there a way to get it to work? I've tried using Noto Color Emoji and other fonts and it just mangles things up. Emojis display properly on other platforms but WASM just gives me the 3 lines or a box.

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/7089

FreeType is used here and that does not support all color glyph formats.

This requires a newer SkiaSharp version that uses a newer FreeType

**Comment by Kibnet** [comment]
Please tell me what needs to be done to make emojis appear in text fields on Android?
