### ISSUE TITLE
ReactiveUI updates

### ISSUE THREAD

**Issue by SpawnProd** [AvaloniaUI/Avalonia#1818]
Good time of day.

As for now, Avalonia.ReactiveUI has reference on System.Reactive < 4.0 and it's impossible to use AvaloniaUI with other projects, where we have Reactive > 4.0 (for now it's 4.1.0).
I was trying to recompile Avalonia.ReactiveUI with new references and there was no problems, I can create new brunch with this fix, or you planned to update references soon?

Sincerely yours.

**Comment by wdcossey** [comment]
If there's no breaking changes between the major versions I don't see why you can't put in a pull request, it'll be reviewed in any case.
