### ISSUE TITLE
ContentControl does not have any VisualChildren

### ISSUE THREAD

**Issue by jeffreye** [AvaloniaUI/Avalonia#1826]
Example:
`<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:local="clr-namespace:AvaloniaApplication"
        Width="274" Height="400">
  <Button Name="btn"></Button>
</Window>`

after calling `AvaloniaXamlLoader.Load(this)`, the Button `btn` would not have VisualParent nor VisualRoot.

**Comment by danwalmsley** [comment]
You need to try overriding OnAttachedToVisualTree, at that point it will.

**Comment by jeffreye** [comment]
`OnAttachedToVisualTree` would not be fired on `Window`, but overriding `OnTemplateApplied` would make it work. My intention is to focus a specific element by `Application.Current.FocusManager.Focus` at startup.

Example 2:
```
<Window xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:local="clr-namespace:AvaloniaApplication" Width="274" Height="400">
    <ContentControl Name="c1">
        <Button Name="btn">
        </Button>
    </ContentControl>
</Window>
```
If we have nested ContentControl, the order in which events are raised is `Window.TemplateApplied`->`c1.TemplateApplied`->`btn.TemplateApplied`. This will make `FocusManager.Focus` really hard to use. 
Does Avalonia have something similar to [FrameworkElement.Loaded](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.loaded?redirectedfrom=MSDN&view=netframework-4.7.2)?

**Comment by grokys** [comment]
@jeffreye you need to make sure you show the window, if the window isn't shown yet then there will _be_ no visual tree.
