### ISSUE TITLE
TextBox makes BEEP sound when typing on Mac

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#1828]
TextBox makes sound like if it was an error each time some key is pressed.

**Comment by danwalmsley** [comment]
New mac backend based on winit doesnt do this, will close when we switch over

**Comment by grokys** [comment]
@danwalmsley can this be closed now?

**Comment by x2bool** [comment]
New macOS backend doesn't produce beep sounds. Thanks!
