### ISSUE TITLE
OpenFileDialog.ShowAsync() get no response

### ISSUE THREAD

**Issue by qcmiao1998** [AvaloniaUI/Avalonia#1837]
When I call OpenFileDialog.ShowAsync() and after I choose the files, the main thread locks and the function has no response.

~~~~c#
        private async Task<string[]> ChooseFiles()
        {
            OpenFileDialog openFileDialog = new OpenFileDialog();
            openFileDialog.Title = "Choose Files";
            openFileDialog.AllowMultiple = true;
            string[] outPathStrings = await openFileDialog.ShowAsync();
            return outPathStrings;
        }
~~~~

**Comment by Kryptos-FR** [comment]
On which platform(s)? The actual implementation is platform-dependent.

**Comment by qcmiao1998** [comment]
On Windows 10 Pro (1803) 
Dotnet core 2.0

**Comment by Kryptos-FR** [comment]
Looks like `Win32` implementation use `Task.Factory.StartNew` which is probably an issue.

See https://blog.stephencleary.com/2013/08/startnew-is-dangerous.html for the rationale.

**Comment by qcmiao1998** [comment]
Thank you very much! After I put it into Task.Run(), it works correctly.

**Comment by Kryptos-FR** [comment]
Do you mean you modified Avalonia's code or use `Task.Run()` around your code?

In the latter case, we should keep that issue open, because it means there might still be an issue in Avalonia itself.

**Comment by qcmiao1998** [comment]
I use Task.Run() in my code, and I think it may be a bug of Avalonia.
~~~~c#
var task = Task.Run(() =>
{
    OpenFileDialog openFileDialog = new OpenFileDialog
    {
        Title = "Choose Images",
        AllowMultiple = true
    };
    openFileDialog.Filters.Add(new FileDialogFilter { Name = "Images", Extensions = { "jpg", "png", "tif" } });
    var outPathStrings = openFileDialog.ShowAsync();
    return outPathStrings;
});
var filelistStrings = task.GetAwaiter().GetResult();
~~~~

**Comment by Kejardon** [comment]
I've been struggling with this all day. After some debugging I've found that the program freezes on Avalonia.Win32's call to frm.Show(hWnd), and never actually shows the dialog. But if I put a breakpoint near there, it works fine. I think the breakpoint needs to be after the call to CoCreateInstance. I have tried several cases all with the same results: ShowFolderDialogAsync on Main thread or on threadpool thread, and trying to read the result on the UI thread or trying to use ContinueWith or even just ignoring the result of the Task entirely. I have not found any workarounds for this.

**Comment by dashenxian** [comment]
I'm having the same problem
```c#
 OpenFileDialog openFileDialog = new OpenFileDialog();//if add a break point in this line,will not stuck
 var outPathStrings = openFileDialog.ShowAsync((Window)this.VisualRoot);//when execute here，It's stuck
```
my os :win10，
AvaloniaUI：0.9.12

The program I published (win-64) had the same problem on my system, but it wouldn't be a problem on another colleague's computer, and it wouldn't be a problem on a linux system on my computer's virtual machine (published as linux-64)

**Comment by Kryptos-FR** [comment]
It is an `async`/`await` method, so you need to `await` it. Your `outPathStrings` variable doesn't contain an array of `string` but a `Task<string[]>`.

**Comment by dashenxian** [comment]
> It is an / method, so you need to it. Your variable doesn't contain an array of but a .`async``await``await``outPathStrings``string``Task<string[]>`

That's not the point, even with the addition of async/await
