### ISSUE TITLE
TextBox Text not updated when PasswordChar changes

### ISSUE THREAD

**Issue by MihaMarkic** [AvaloniaUI/Avalonia#1847]
Using nightly build I'm seeing that TextBox's Text doesn't change when its PasswordChar changes.
Unless I click into textbox.

Repro: Run attached sample, click on Toggle (text is still visible) then click in TextBox (text changes to masked).

I guess there is a "redraw" missing somewhere but I can't find it easily to create a PR.

[PasswordChar.zip](https://github.com/AvaloniaUI/Avalonia/files/2342360/PasswordChar.zip)

**Comment by Gillibald** [comment]
Probably needs to call
```
InvalidateFormattedText();
InvalidateMeasure();
```
on change

**Comment by MihaMarkic** [comment]
Hm, InvalidateMeasure does nothing while there is no InvalidateFormattedText on TextBox (seems it's on TextBlock).

**Comment by danwalmsley** [comment]
Need to add AffectsRender in the static ctor of textbox for PasswordChar property.

**Comment by Gillibald** [comment]
I think this should happen in TextPresenter not in the control's implementation. Just invalidate FormattedText in TextPresenter on PasswordChar change.

**Comment by MihaMarkic** [comment]
InvalidateFormattedText works, I catch PasswordChar changes with

```
this.GetObservable(PasswordCharProperty)
                .Subscribe(PasswordCharChanged);
```
Is this a proper way? Should I submit a PR?

**Comment by Gillibald** [comment]
Looks good to me. Please submit a PR.

**Comment by MihaMarkic** [comment]
At the end I had to add AffectsRender as well, otherwise it doesn't trigger the rener.
