### ISSUE TITLE
Enhance ReactiveUI support

### ISSUE THREAD

**Issue by worldbeater** [AvaloniaUI/Avalonia#1852]
Hi,

ReactiveUI team would like to improve Avalonia support. We'd like to implement type-safe bindings for Avalonia platform, Reactive UserControls that implement IViewFor, etc. See https://github.com/reactiveui/ReactiveUI/issues/1739

We could create a new package providing support for AvaloniaUI, but there is one <a href="https://www.nuget.org/packages/Avalonia.ReactiveUI/">already published to NuGet</a>. 

It would be great if you could transfer the ownership to the ReactiveUI organization and rename it to ReactiveUI.Avalonia, so we can improve the UX when publishing updates with enhanced ReactiveUI support.

Thanks in advance!

**Comment by jmacato** [comment]
Hello @worldbeater! This is just an inquiry on the behalf of the team with regards to your proposal. 

We would like to see a more detailed plan with regards to the integration of `Avalonia.ReactiveUI` port to the mainline ReactiveUI project and also the type-safe bindings. But nevertheless, this is a great initiative that I personally would like to see bloom into fruition :smile: 

Hoping to hear back soon!

**Comment by worldbeater** [comment]
Hello @jmacato! Glad to hear you like the initiative! ✨

We've started implementing support for `WhenActivated` and bindings here: reactiveui/ReactiveUI#1748 Any help on completing this PR would be highly appreciated. After we finish, let's continue the discussion in our <a href="http://reactivex.slack.com">Slack room</a> and find out how we could transfer the packages.
