### ISSUE TITLE
Slider control broken

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1856]
1) SmallChange property is ignored.

2) If you have more than 1 slider on a page, the second 1 wont work...

can be reproduced by placing 2 sliders and binding a textbox to each #slider.Value.

**Comment by wdcossey** [comment]
I have a [PR](https://github.com/AvaloniaUI/Avalonia/pull/1831) that hopefully fixes this issue.

![image](https://user-images.githubusercontent.com/1089478/45004829-9d875b80-afe7-11e8-9419-fd7836f5697f.png)

**Comment by danwalmsley** [comment]
@wdcossey yes that fixes the issue thanks
