### ISSUE TITLE
Question: Using preexisting ShiaSharp Context

### ISSUE THREAD

**Issue by BernhardGlueck** [AvaloniaUI/Avalonia#1862]
Hi !

I  have a maybe unique problem, but in the way Avalonia is designed it think its a perfect fit.
I am working on a Game, that is relatively UI-Heavy.
I already use a mixture of OpenGL ES and SkiaSharp to draw everything, and before i write my own ui controls on top of skiasharp i was wondering if it is possible to embed Avalonia, hand it my SkiaSharp Context/Surface/RenderTarget etc, and use it to draw my UI ....

**Comment by Gillibald** [comment]
As far as I know we currently don't have GPU support for Skia. This will change in the near future. We render to a SKSurface so it should be possible to share that. Could be mistaken.

**Comment by BernhardGlueck** [comment]
I am still familiarizing myself with the Avalonia CodeBase and its Initialization Sequence as well as the architecture.. 

I will write something up.  

As far as i can see, though right now enabling basic hardware acceleration should be quite a simple change
