### ISSUE TITLE
WindowStartupLocation does not show window on expected position

### ISSUE THREAD

**Issue by ficnar** [AvaloniaUI/Avalonia#1868]
Using WindowStartupLocation property not show window on expected position.
Tested on 0.6.2-build6147-beta 

On Windows:
CenterOwner - show window top-left from the expected position
CenterScreen - OK

On Linux:
CenterOwner - show window bottom-right from the expected position
CenterScreen - show window bottom-right from the expected position

On Mac OSX:
CenterOwner - show window on static position independently on owner position, horizontally centered to screen, vertically top of center screen
CenterScreen - OK

**Comment by na2axl** [comment]
For me (on Linux) `CenterScreen` uses as origin the **top-left** corner of the window :

![image](https://user-images.githubusercontent.com/14062034/49707554-f2acbc00-fc2b-11e8-8640-69c726478e06.png)

**Comment by grokys** [comment]
Should have been fixed by #2250. Please let me know if not.

**Comment by ficnar** [comment]
@grokys With night build 0.7.1-cibuild0001581-beta now work properly:
Windows: - all is OK
Linux: - center to screen is OK, center to parent is a little bit top-left from expected position, but it is OK
OSX: center to screen is OK, center to parent is a litle bit top-right from expected position, but it is OK
