### ISSUE TITLE
Provide event to prevent window from closing

### ISSUE THREAD

**Issue by PathogenDavid** [AvaloniaUI/Avalonia#1875]
As far as I could find, this feature doesn't exist in Avalonia today and there's no issue tracking this feature.

This would be similar to the [Window.Closing event](https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.closing) in WPF and the [Form.Closing event](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.closing) in Winforms.

This feature is useful for applications which prompt the user for confirmation or hide the window instead of destroying it when the user closes it.

**Comment by grokys** [comment]
Hi @PathogenDavid - this should already be implemented in the [nightly builds](https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed), it was implemented in #1383

**Comment by PathogenDavid** [comment]
Ah, sorry about that. I thought my local copy of Avalonia was on master, but it was actually on 0.6.1.
