### ISSUE TITLE
Use XamlType.IsUsableDuringInitialization when supported by Portable.Xaml

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#1876]
This setting is used to notify XAML that a created object should be attached to its parent immediately after construction:

https://docs.microsoft.com/en-us/dotnet/api/system.xaml.xamltype.isusableduringinitialization?view=netframework-4.7.2

We currently implement some hacks to make things happen in this order; it would be good to remove them if/when supported in Portable.Xaml. See https://github.com/cwensley/Portable.Xaml/issues/110

**Comment by maxkatz6** [comment]
@grokys @kekekeks do we still need it with XamlX?

**Comment by kekekeks** [comment]
`UsableDuringInitializationAttribute` is supported by XamlX from day 1
