### ISSUE TITLE
Hit testing with ImmedateRenderer is broken

### ISSUE THREAD

**Issue by jkoritzinsky** [AvaloniaUI/Avalonia#1879]
Since we made `AdornerLayer` hit test visible (#1722), `ImmediateRenderer`'s hit-testing algorithm has been directing all input events to the `AdornerLayer` instead of the underlying controls.

**Comment by grokys** [comment]
Hmm this is indeed a problem. Not 100% sure how to solve this, but here's an idea:

How about an interface called say `IImmediateHitTest` which when implemented on a control is called by the `ImmediateRenderer`'s `HitTest` method to do the actual hit-testing within the control?

This could also be implemented on other controls, e.g. `Shape`s, and could implement hit-testing based on their geometry.

**Comment by jkoritzinsky** [comment]
I've prototyped this out and gotten it to work but we have another bug with `ImmediateRenderer`. It doesn't correctly calculate dirty rectangles for animations that move outside of their arranged box (aka animated render transforms aren't quite working).
