### ISSUE TITLE
Controls overlay each other during tabs switching

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#1890]
### Condition

Project: ControlCatalog.Desktop-0.6.2-build6217-beta
OS: Windows 7 SP 1

### Expected 

All controls displayed clear.

### Actual

Controls overlay each other during tabs switching:

![controlsoverlay](https://user-images.githubusercontent.com/1150330/45411185-3cf9bd80-b67c-11e8-85da-20e2128434e8.png)

**Comment by jmacato** [comment]
This is trippy, did you do any modification to ControlCatalog?

**Comment by KvanTTT** [comment]
No. I tried the latest version from artifacts.

**Comment by jmacato** [comment]
cc @Gillibald : this could be a deferred renderer/D2D bug

**Comment by jkoritzinsky** [comment]
I'm pretty sure this is the CrossFade page transition working as expected.

**Comment by Gillibald** [comment]
Hopefully, this is not limited to Windows 7.

**Comment by KvanTTT** [comment]
@jkoritzinsky it's definitely a bug. I can add a video.

**Comment by jkoritzinsky** [comment]
Yeah a video would help me see the bug better.

**Comment by grokys** [comment]
Does this still happen?

**Comment by Gillibald** [comment]
This can no longer happen with the new TabControl because it doesn't use transitions anymore.
