### ISSUE TITLE
TextTrimming for TextBlock

### ISSUE THREAD

**Issue by nicolasr75** [AvaloniaUI/Avalonia#1897]
I would like to vote for the addition of a `TextTrimming` property to` TextBlock` as in WPF.

Especially for TextBlocks that display status and error messages, the text often is longer than the TextBlock, even if the TextBlock spans the entire window. It looks much better if an ellipsis is rendered instead of just cutting off the text.

**Comment by Gillibald** [comment]
Will have this in mind for my skia text layout implementation. DirectWrite already supports this out of the box. There is already a lot of complexity.

**Comment by maxkatz6** [comment]
@Gillibald can this issue be closed?

**Comment by Gillibald** [comment]
Can be close y. Thanks.
