### ISSUE TITLE
Binding with dot

### ISSUE THREAD

**Issue by teast** [AvaloniaUI/Avalonia#1898]
Hello,

I noticed that after the pull request #1772 binding with dot stopped working.
One sollution would be to change
`            if (string.IsNullOrWhiteSpace(expression))
            {
                return (new EmptyExpressionNode(), default);
            }
`
that is located at start of ExpressionObserverBuilder.Parse.

To:
`            if (string.IsNullOrWhiteSpace(expression) || expression == ".")
            {
                return (new EmptyExpressionNode(), default);
            }
`

But I'm not involved enough to know if there could be any other side effects from this solution.

**Comment by Gillibald** [comment]
What is the benefit of that notation?

**Comment by teast** [comment]
I guess it is equivalent to
`{Binding Path=.}`
It makes it possible to bind to current source.
One example of use would be if you want to do an custom ItemTemplate and inside that template bind to the items object.
Another example is if you want to use an converter on the source itself
`{Binding ., Converter={StaticResource CustomConverter}}`

**Comment by danwalmsley** [comment]
{Binding } does the same, but if other frameworks support this then we should fix it.
