### ISSUE TITLE
Avalonia.DotNetCoreRuntime UsePlatformDetect implementation crashes without Avalonia.Desktop reference.

### ISSUE THREAD

**Issue by jkoritzinsky** [AvaloniaUI/Avalonia#1899]
The way that the `UsePlatformDetect` method is written in `Avalonia.DotNetCoreRuntime` will cause it to crash without a reference to `Avalonia.Desktop`. That's because the methods directly reference the windowing/rendering subsystems, so if they are automatically selected and not available, the application will crash on loading the assembly. 

The implementation in `Avalonia.DotFrameworkRuntime` doesn't have this problem since it dynamically loads the implementation assemblies from the working directory. We can use this implementation for both .NET Core and .NET Framework. However, this implementation prevents AOT applications from correctly working since the assemblies don't have a hard reference.

**Comment by jmacato** [comment]
@jkoritzinsky considering that CoreRT doesn't even have any proper runtime assembly loading yet, i dont think we should be as worried as to breaking it because it's currently broken too...

**Comment by jkoritzinsky** [comment]
Another interesting note I just remembered. CoreRT just re-enabled their experimental JIT support for dynamic assembly loading and has it hooked in to their build scripts so it is less likely to bit-rot. So my statement about stuff not working in CoreRT may not be the case in the future (possibly by the time that CoreRT and Avalonia are both v1.0+).
