### ISSUE TITLE
Tab order with containers

### ISSUE THREAD

**Issue by MihaMarkic** [AvaloniaUI/Avalonia#1903]
I found out that if I have something like

```
<TextBox>
  <Grid>
    <TextBox>
  </Grid>
<TextBox />
```

then nested TextBox will be skipped when tabbing through controls
it helps if I set Grid.Focusable=true but then focus will go first to grid and only then to nested TextBox
Focusable shouldn't affect nested controls I think.

**Comment by grokys** [comment]
I think this was fixed a while ago. Please re-open if that's not the case.
