### ISSUE TITLE
CornerRadius with border and fill results in white gaps

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#1904]
If I change the `ContentPresenter` in the template for `Button`' to have a 4 pixel `CornerRadius` I see the following:

![image](https://user-images.githubusercontent.com/1775141/45598125-ed4a2780-b9d6-11e8-94b4-5a1990ac1078.png)

You can see that the fill and the border don't line up properly. I think `BorderRenderHelper` needs to adjust the corner radius of the fill depending on the border thickness somehow? This happens on both D2D and Skia so I don't think it's a renderer problem.

cc: @Gillibald because you wrote the code.

**Comment by grokys** [comment]
I think this may be the relevant formula? https://stackoverflow.com/questions/2932146/math-problem-determine-the-corner-radius-of-an-inner-border-based-on-outer-corn

**Comment by Gillibald** [comment]
This is already done for the complex render path. Will add this to the fast path as well.

**Comment by SkyZero1228** [comment]
Hello @grokys 
Could you help me how I can make RoundButton exactly?
There isn't any CornerRadius property in Button.
