### ISSUE TITLE
Ambiguous call between Dispatcher.InvokeAsync (Action and Dispatcher.InvokeAsync(Func<Task>

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1906]
https://files.gitter.im/AvaloniaUI/avalonia-core/BzRL/image.png

This would be a breaking api change.

**Comment by Kryptos-FR** [comment]
What is the signature of the `CloseIfFocusLost` method?

**Comment by danwalmsley** [comment]
Its void CloseIfFocusLost()

**Comment by danwalmsley** [comment]
Ill try langversion 7.3

**Comment by grokys** [comment]
@danwalmsley can this be closed?
