### ISSUE TITLE
GTK3 implementation should check xft.dpi settings, not just scaling factor

### ISSUE THREAD

**Issue by davex25** [AvaloniaUI/Avalonia#1907]
My dpi settings under gnome and i3 seem to be ignored.  There's another github issue (which now I'm having trouble finding again) indicating Avalonia currently only uses the gdk window scale factor setting. 
 It's an int, 1 is not scaled, and 2 or more makes everything huge so i'm not sure why anyone would actually set this.  

I think Avalonia should be checking this: https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-xft-dpi.

More details here:
https://bugs.chromium.org/p/chromium/issues/detail?id=723931 (see comment 13)

**Comment by danwalmsley** [comment]
@jameswalmsley did you have a similar issue before?

**Comment by kekekeks** [comment]
Fixed by switching to X11 backend. For configuring per-monitor DPI see https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI

**Comment by davex25** [comment]
From what I can tell, this line is where you are getting scale factor (from Avalonia.Gtk3/WindowBaseImpl.cs):
`
        public double Scaling => LastKnownScaleFactor = (int)
(Native.GtkWidgetGetScaleFactor?.Invoke(GtkWidget) ?? 1);
`

According to [this](https://stackoverflow.com/questions/417384/get-dpi-settings-via-gtk) StackOverflow answer, you can get the DPI from the (poorly-named) gdk_screen_get_resolution.  A gdk screen instance can be retrieved from gtk_widget_get_screen.

Unless I'm missing something, seems like the GTK backend should be doing this.

**Comment by danwalmsley** [comment]
@davex25 Gtk backend is being removed, you should switch to using X11 backend.

**Comment by kekekeks** [comment]
>Doesn't this mean requiring users to configure yet another thing?

It should detect your DPI automatically from EDID. If it does, see https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI

**Comment by davex25** [comment]
Ok.
