### ISSUE TITLE
Autocomplete doesn't work in Visual Studio

### ISSUE THREAD

**Issue by CtrlShiftEscape** [AvaloniaUI/Avalonia#1916]

**Comment by CtrlShiftEscape** [comment]
Microsoft Visual Studio Enterprise 2017 
Version 15.8.5
VisualStudio.15.Release/15.8.5+28010.2036

Microsoft .NET Framework Version: 4.7.03056

AvaloniaPackage Extension version: 1.0

**Comment by danwalmsley** [comment]
Did you build your project first?

**Comment by CtrlShiftEscape** [comment]
Yes

**Comment by danwalmsley** [comment]
Hmmm, perhaps @kekekeks might have an idea

**Comment by CtrlShiftEscape** [comment]
Also the XAML editor from AvaloniaUI projects has this tab, but UWP and WPF editor don't 
![image](https://user-images.githubusercontent.com/36315896/45960793-a9ce6980-c025-11e8-8630-d9b58f87d8bc.png)
Does VS recognize Avalonia XAML as XML?

**Comment by Harry09** [comment]
I have same issue. MS VS Community 2017 15.8.7.
I have installed Avalonia for Visual Studio.

**Comment by kristoof** [comment]
Same issue on VS Community 2017 and avalonia for vs 0.7

**Comment by donandren** [comment]
same issue here i think it has started week or 2 ago, may be when 0.7 was released

**Comment by donandren** [comment]
should be fixed in https://github.com/AvaloniaUI/AvaloniaVS/pull/76

**Comment by dfkeenan** [comment]
I have been playing with Avalonia UI in VS 15.9.4.  The completion is rather painful compared to the WPF one at least. Some examples:

* If you use `Space` to complete a tag name it doesn't insert the space.
* If you use `Space` to complete a property name the carot ends up after the last double quote.
* If you use `=` to complete a property: it doesn't complete the name it just has whatever you have typed so far; it doesn't close the completion window and the only suggestions is the property name you just selected.
* If you type `/` to complete a self-closing tag it doesn't insert `/>`.

**Comment by lock9** [comment]
Hello. I'm having this problem in new machines, but my computer from home has auto-complete working fine. Is there any way I can help?

**Comment by grokys** [comment]
Hi @lock9 I'm currently working on improving the intellisense completion in a new version of the designer. I'll let you know when I have something you can try out!

**Comment by grokys** [comment]
Intellisense should now be greatly improved with more improvements coming. Closing this: if there are any more problems please file them in our VS extension repo: https://github.com/AvaloniaUI/AvaloniaVS
