### ISSUE TITLE
Deffered Renderer broken on Hi DPI monitors

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1918]
https://i.imgur.com/JpXDFCh.png

@kekekeks knows more.

**Comment by nc4rrillo** [comment]
Is this a recent regression?

**Comment by jmacato** [comment]
@nc4rrillo seems to be after the unify timers PR merge

**Comment by danwalmsley** [comment]
@jmacato did you manage to repro on linix, set scaling = 2 causes it, and resize window to trigger.

**Comment by jmacato** [comment]
Yep i can repro, maximizing it then restore triggers the bug
![screenshot from 2018-09-25 22-08-08](https://user-images.githubusercontent.com/16554748/46019914-b5965a80-c10f-11e8-98b5-22daa6392ae4.png)

**Comment by KvanTTT** [comment]
Maybe related issue: https://github.com/AvaloniaUI/Avalonia/issues/1890

**Comment by grokys** [comment]
I can't repro this on Windows. Is it a Linux/Mac-only bug or am I missing something?

**Comment by danwalmsley** [comment]
after finding issues with scaling and fixing on win32, was still unable to repo on windows, so I guess this has to be something specific to Linux / mac backends

**Comment by grokys** [comment]
Managed to repro this on win32 after applying #2010. It seems to be a skia issue as it doesn't occur when using D2D backend.

**Comment by kekekeks** [comment]
This should be fixed by https://github.com/AvaloniaUI/Avalonia/pull/2011/commits/37c65262ac1db3f2cf89669253a44639adcd03fe in X11 backend PR.

Please, check using `0.7.1-build1179-beta` build from [PR feed](https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed#pr-feed)
