### ISSUE TITLE
Japanese and Korean texts don't render properly on Skia backend

### ISSUE THREAD

**Issue by akunchev** [AvaloniaUI/Avalonia#1925]
Japanese and Korean texts don't work properly on Skia backend, altought they work fine on Direct2D backend.
Examples:
Japanese Example: 日本のテキストの例
Korean Example: 일본 텍스트 예제
Repro steps:

Add this textboxes to control catalog core project:

```
          <TextBlock Text="Japanese Example: 日本のテキストの例" />
          <TextBlock Text="Korean Example: 일본 텍스트 예제" />
```
result:
![image](https://user-images.githubusercontent.com/37666507/46210448-6c295380-c339-11e8-8c6b-e501ffa39666.png)

Same action on control catalog desktop is working fine:
![image](https://user-images.githubusercontent.com/37666507/46210507-92e78a00-c339-11e8-845b-c862fa729049.png)

**Comment by jmacato** [comment]
This is a known issue but unfortunately, until a major rework with our Text backend happens, all unicode chars will not be guaranteed to work.

**Comment by Gillibald** [comment]
Thanks for reporting this. I am currently working on a new text layout for the skia backend that should handle these characters just fine.

**Comment by define-private-public** [comment]
@Gillibald , I saw that you had PR #3438  Would this fix it as well.  I'm working on an internationalized app.

**Comment by Gillibald** [comment]
Yes. You will be able to use non Latin text in TextBlock.
