### ISSUE TITLE
DevTools don't highlights controls when ImmediateRenderer is used

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#1927]
DevTools don't highlights controls when ImmediateRenderer is used.

When mouse cursor in DevTools is over element in Logical (or Visual ) tree, controls are not highlighted.

Note: It's working properly with DeferedRenderer.

Repro Steps:

1. Use Control Catalog Desktop as Example change: 
`AppBuilder.Configure<App>().LogToDebug().UsePlatformDetect()`
to 
 `AppBuilder.Configure<App>().LogToDebug().UseWin32(false).UseDirect2D1()`
e.g. use ImmediateRenderer
2. Start the App
3. press F12 DevTools to show
4. In Logical Tree tree view it's expected when mouse is over to highlight controls, but it's not

**Comment by Gillibald** [comment]
Is this a hit test related issue?
