### ISSUE TITLE
Disposing of Path in Cairo

### ISSUE THREAD

**Issue by DavidKarlas** [AvaloniaUI/Avalonia#193]
Path in Cairo must be disposed :(
So Path created here: https://github.com/Perspex/Perspex/blob/3573591feeca5ec66644d5bbaf6b256bec4f800e/src/Gtk/Perspex.Cairo/Media/StreamGeometryContextImpl.cs#L62 must be disposed...
Disposing in https://github.com/Perspex/Perspex/blob/3573591feeca5ec66644d5bbaf6b256bec4f800e/src/Gtk/Perspex.Cairo/Media/StreamGeometryContextImpl.cs#L67 is too early... And https://github.com/Perspex/Perspex/blob/3573591feeca5ec66644d5bbaf6b256bec4f800e/src/Perspex.Controls/Shapes/Path.cs doesn't have IDisposable... Not sure how to fix this...

**Comment by ImaBrokeDude** [comment]
Couldn't we null out the path and GC it?

**Comment by ncarrillo** [comment]
`Cairo.Path` holds on to a native `cairo_path_t` resource.

**Comment by ImaBrokeDude** [comment]
Ooh grr

**Comment by grokys** [comment]
We hope that cairo will be replaced by skia so closing this.
