### ISSUE TITLE
ReactiveCommand System.InvalidOperationException: Call from invalid thread 

### ISSUE THREAD

**Issue by stdcall** [AvaloniaUI/Avalonia#1934]
Hello!

  I have an application with a simple view which contains only a button

```
<Button Command={Binding TestCommand}/>
```
The TestCommand property of the DataContext is a 

```
TestCommand = ReactiveCommand.Create(() => {});
```

The AppBuilder inside Main method looks like this.

```
...
var context = new ApplicationContext();
AppBuilder
  .Configure(app)
  .UsePlatformDetect()
  .UseReactiveUI()
  .Start<MainWindow>(() => context);  // The problem is here.
```

With this code, when i click the button my application crashes  with
```
System.InvalidOperationException: Call from invalid thread 
```

I can fix this by changing AppBuilder chain with 
```
...
  .Start<MainWindow>(() => new ApplicationContext());
```

However, I really would like to create ApplicationContext before calling the AppBuilder. Can I actually do this?

**Comment by grokys** [comment]
What is `ApplicationContext` and what does `.Start<MainWindow>(() => context);` do?

**Comment by stdcall** [comment]
I have uploaded the Application which reproduces the error -
https://github.com/stdcall/Avalonia-Hello

**Comment by danwalmsley** [comment]
Ive not had chance to look at your example, but its highly likely you need to initialise ReactiveUI, add UseReactiveUI() to your appbuilder (where it says UsePlatformDetect).

**Comment by kekekeks** [comment]
You shouldn't use any Avalonia APIs before either `SetupWithoutStarting` or `Start<TWindow>` is called on AppBuilder. The same goes for RxUI, since it needs to use Avalonia's synchronization primitives which are not available before setup.

**Comment by worldbeater** [comment]
@stdcall In addition, I'd like to mention that writing such code at the beginning of your Main method will likely do the trick:
```cs
public void Main(string[] args) 
{
    RxApp.MainThreadScheduler = AvaloniaScheduler.Instance; // Interesting line of code!
    var context = new ApplicationContext();
    AppBuilder
        .Configure(app)
        .UsePlatformDetect()
        .Start<MainWindow>(() => context);
}
```
That <a href="https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.ReactiveUI/AppBuilderExtensions.cs#L17">UseReactiveUI</a> method actually initializes the <a href="https://reactiveui.net/docs/guidelines/framework/ui-thread-and-schedulers">ReactiveUI main thread scheduler</a> using a static instance of the <a href="https://github.com/AvaloniaUI/Avalonia/blob/d6578eba5089e267d9701a6b7380a5830fbe2465/src/Avalonia.Base/Threading/AvaloniaScheduler.cs">AvaloniaScheduler</a>. Why are you getting that `InvalidOperationException`? 'Cause you are trying to create your ReactiveUI ViewModel when things haven't been initialized yet. So, if you initialize the schedulers by hangs, the exception will go away.

But I'd not recommend you doing so - let the fameworks initialize the things for you. 
So this is the best way for you to go:
```cs
.Start<MainWindow>(() => new ApplicationContext());
```
