### ISSUE TITLE
Blank/Black popup when using opengl skia 

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#1944]
I had a popup (used as a dialog) come up black all over. Closing and reopening it did not change it.  I have not been able to recreate it. I had never seen it before I used the gpu code. This was on windows10.

**Comment by grokys** [comment]
@ahopper have you had this happen recently?

**Comment by ahopper** [comment]
I've not seen this again and have run with gpu quite a lot even though it is off by default on windows so I'll close it.

**Comment by joaompneves** [comment]
I'm seeing this problem too, A very simple Popup or a PopupRoot render black on Windows 10. Not sure how can I help troubleshooting the problem.
