### ISSUE TITLE
Support binding to dynamic Proxy (IDynamicMetaObjectProvider) 

### ISSUE THREAD

**Issue by ffetech** [AvaloniaUI/Avalonia#1949]
Hello,

are you interested to support bindings to dynamic proxies like it is possible in WPF.

Heres an example for a base class of a dynamic proxy which i use as base class for some of my special view models:
http://customer.ffe-tech.com/code/DynamicProxy.cs

Currently a binding to such dynamic properties is not working. It's working only for declared properties.

Access dynamic properties of a proxy which implements IDynamicMetaObjectProvider is working like this:

```
if (dataContext is IDynamicMetaObjectProvider provider)
{
	// Dynamischer Getter
	CallSiteBinder gBinder = Microsoft.CSharp.RuntimeBinder.Binder.GetMember(CSharpBinderFlags.None, property, typeof(object),
								 new List<CSharpArgumentInfo> { CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null) });
	var propertyDynamicGet = CallSite<Func<CallSite, object, object>>.Create(gBinder);
	object value = propertyDynamicGet.Target(propertyDynamicGet, dataContext);

	// Dynamischer Setter
	CallSiteBinder sBinder = Microsoft.CSharp.RuntimeBinder.Binder.SetMember(CSharpBinderFlags.None, property, typeof(object),
								 new List<CSharpArgumentInfo>
		{
			CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null),
			CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null)
		});
	var propertyDynamicSet = CallSite<Func<CallSite, object, object, object>>.Create(sBinder);
	propertyDynamicSet.Target(propertyDynamicSet, dataContext, value);
}
```

**Comment by jkoritzinsky** [comment]
I've been thinking about adding this for a while. The only thing I'm iffy about is that there's no good way to allow the user to specify which set of runtime binders to use, so we'd have to use the C# ones (which would make it hard to work with other DLR based languages like IronPython or IronRuby).

That might not be much of an issue though.

**Comment by ffetech** [comment]
Is there some alternative approach to manage such customized binding? For example an Interface my ViewModel could implement?

**Comment by jkoritzinsky** [comment]
If you want you can make your own implementation of `Avalonia.Data.Core.IPropertyAccessorPlugin` to pull from a dynamic object and add it to the front of the `ExpressionObserver.PropertyAccessors` collection at startup. Then it should automatically be picked up by the binding system. Fair warning: it won't support indexer bindings.

**Comment by ffetech** [comment]
Ok, this would be nice. Here I wrote such a plugin: http://customer.ffe-tech.com/code/DynamicPropertyAccessorPlugin.cs
How is the way now to provide this plugin - without changing the orgin code of ExpressionObserver?

**Comment by jkoritzinsky** [comment]
Create an extension method on AppBuilderBase called UseDynamicBinding or something and add it to the collection in there. Then you can call it on the AppBuilder instance at startup.

**Comment by ffetech** [comment]
Oh sorry, was confused about the collection - thought it is an fixed array. Simple adding it (as first element) works perfectly:
```
ExpressionObserver.PropertyAccessors.Insert(0, new DynamicPropertyAccessorPlugin());
```
Thank you very much. A very scaleable framework 👍

**Comment by grokys** [comment]
Glad you got this working @ffetech - going to close the issue.

**Comment by Kryptos-FR** [comment]
Given that the links are dead, can this issue be reopened? I'd like to have that support directly in Avalonia. Or maybe you can point me to another alternative that would work with dynamic properties.

I'm working on porting the GameStudio of the [Stride](https://github.com/stride3d/stride) game engine from WPF to Avalonia. And this is currently a blocker for our "property grid".
