### ISSUE TITLE
Rendering artifacts with DPI 150% on Windows / Skia

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1960]
![image](https://user-images.githubusercontent.com/4672627/46735352-e8069280-cc8d-11e8-92e8-97ccc9a1a5c4.png)

**Comment by danwalmsley** [comment]
BTW with immediate rendering we get this which is also wrong (and scaling isnt important in this case)
![animation-bug](https://user-images.githubusercontent.com/4672627/46740221-3588fc80-cc9a-11e8-9f9d-8da18cdda091.gif)

**Comment by grokys** [comment]
I think this issue is fixed. Please re-open if not @danwalmsley
