### ISSUE TITLE
AttachedToVisualTree event handler for UserControl is called twice

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1967]
Repro:

1. Add below code in ControlCatalog to AutoCompleteBoxPage:
```C#
        public AutoCompleteBoxPage()
        {
            this.InitializeComponent();

            AttachedToVisualTree += AutoCompleteBoxPage_AttachedToVisualTree;
            DetachedFromVisualTree += AutoCompleteBoxPage_DetachedFromVisualTree;
```
```C#
        private void AutoCompleteBoxPage_AttachedToVisualTree(object sender, Avalonia.VisualTreeAttachmentEventArgs e)
        {
        }

        private void AutoCompleteBoxPage_DetachedFromVisualTree(object sender, Avalonia.VisualTreeAttachmentEventArgs e)
        {
        }
```
2. Set break-points for above two event handlers.

3. Run ControlCatalog.NetCore in debug mode.

Actual order of events:
- AutoCompleteBoxPage_AttachedToVisualTree
- AutoCompleteBoxPage_DetachedFromVisualTree
- AutoCompleteBoxPage_AttachedToVisualTree

Expected  order of events:
- AutoCompleteBoxPage_AttachedToVisualTree

![2018-10-13_14-04-24](https://user-images.githubusercontent.com/2297442/46905256-ff918580-cef0-11e8-9933-c74b7a87b25f.gif)

**Comment by grokys** [comment]
Just tried this on `master` and seems to be fixed, so closing.
