### ISSUE TITLE
FontFamily ignored on Linux

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#1970]
Setting FontFamily on Window no longer seems to work on Linux, it works on windows with Skia. The default font on Linux also appears to have changed to something very old.

**Comment by danwalmsley** [comment]
@Gillibald

**Comment by Gillibald** [comment]
Do you mean by not working that controls down the visual tree don't get the FontFamily applied?

**Comment by Gillibald** [comment]
If it works on windows with skia and on your Linux system it doesn't this is most likely an issue of skia. Currently I don't have a Linux system but I will try to setup one soon and investigate this issue further.

**Comment by ahopper** [comment]
OK. that makes sense. It does work with the stable beta but I don't know when it stopped working as I've only just started testing on Linux again.  I'm a bit surprised that no one else has mentioned this. I checked on two Linux systems(both mint) to check it it was not something local.

**Comment by ahopper** [comment]
The problem seems to be that it has got more precise about the font name. SKTypeface.FromFamilyName("Sans") returns a font with a name of DejaVu Sans but putting Sans in FontFamily does not work, DejaVu Sans does work.
The font returned when it can't find one in Liberation Serif which does not look good :)

**Comment by Gillibald** [comment]
Thats expected behavior. We could change the logic to check for `FamilyName.Contains("...")` that way new `FontFamily("Sans")` would work I guess.

**Comment by ahopper** [comment]
Ok, it obviously slightly changed at some point. Slightly odd that "Sans" is listed as a font on my Linux box but can't be selected.  Making it less strict is probably a good thing as fonts on Linux seem to vary between distros.

**Comment by Gillibald** [comment]
Sans is probably just an alias

**Comment by ahopper** [comment]
I think by having an exact match here we are throwing away some of the cleverness of the font backend in finding a match.  Perhaps if an exact match is not found for any of the passed options it should take the first match that isn't the ultimate fallback

**Comment by Gillibald** [comment]
If DirectWrite does the same matching I will change this otherwise this behavior wouldn't be consistent I guess. Or what do you think?

**Comment by ahopper** [comment]
Good point about DirectWrite, a quick try with Sans didn't work.  Not sure how much it matters if they are consistent as with DirectWrite you have more chance of knowing what fonts exist.  This issue is obviously not anywhere near as serious as the title suggests but I think we need to do something to improve the default font on Linux either by clever selection of fonts in the theme or using some of the cleverness of SKTypeface.FromFamilyName.

**Comment by Gillibald** [comment]
I will introduce a Default for FontFamily that uses the system-defined default when the new version of SkiaSharp is released.
