### ISSUE TITLE
Size render layers to content.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#1983]
Render layers currently fill the entire window, no matter the size of the content - this is very wasteful! We make render layers be no larger than they need to be. #1634 tried to address this, but the issue was more complicated:

> Particularly, I'm concerned what will happen if a layer needs to change size? Will the whole layer be redrawn? If not, what if the layer needs to expand to the left or the top? Will the existing layer content be shifted over correctly?

**Comment by Sorien** [comment]
maybe it's not such a good idea to have hundreds small layers, i'd say that some kind [layer atlas](https://en.wikipedia.org/wiki/Texture_atlas) would be more suitable

**Comment by Gillibald** [comment]
This change would make it easier to apply effects I guess. If you look how layering is done with Direct2D1 you will see that they have LayerParameters thar define the size of the layer. Still wondering what prevents us to use the platforms layering capability instead of managing layers on our own.

**Comment by kekekeks** [comment]
We don't have layers anymore
