### ISSUE TITLE
Should ShowDialog method hang parent window code until dialog is closed?

### ISSUE THREAD

**Issue by BlackDragonDv** [AvaloniaUI/Avalonia#1984]
Hello.

I've recently discovered Avalonia and started to love it because it's similar to WPF, open source and multiplatform. I'm writing some testing application using Avalonia and I've discovered one thing - ShowDialog doesn't block parent code. Let me illustrate this using code.

MainWindow.xaml
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Test App" SizeToContent="WidthAndHeight">

  <StackPanel Margin="10">
    <Button Content="Click Me!" Click="Button_Click" />
  </StackPanel>
  
</Window>
```

Button_Click method
```
 private void Button_Click(object sender, RoutedEventArgs e)
        {
            Window1 window = new Window1();

            window.ShowDialog();

            System.Console.WriteLine("Hello");
        }
```

Window1 is just empty Avalonia Window. What puzzles me is moment when console prints "Hello". This happen just after I click button. New window opens and console prints "Hello". Shouldn't console print text after window is closed? ShowDialog blocks UI (I can't operate on main window when child is open) but shouldn't it block code too? On WPF similar code is working same way I've explained (console prints hello after dialog is closed).

So the question is - is this bug? It's not big deal because we can simply attach method to the Closed event and put code here. But what about it? Thank you in advance for answer.

**Comment by danwalmsley** [comment]
ShowDialog api in Avalonia returns a Task or Task<T> 

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Window.cs#L400

You can await the task to get the result.

The main window should become "Inactive" until the child window is closed.

**Comment by BlackDragonDv** [comment]
I understand this now. Thank you very much for answer.
