### ISSUE TITLE
Disposing Lock on WriteableBitmap fails to update the image. 

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#1995]
Repro via Skia-based backends:
1. Clone https://github.com/jmacato/AvaloniaGif and run AvaloniaGif.Demo
2. Image should intermittently update when the window is resized.

**Comment by grokys** [comment]
Was this fixed by #1996?

**Comment by jmacato** [comment]
@grokys it doesnt work on `DeferredRenderer` yet sir. Though #2185 sidesteps the issue

**Comment by jmacato** [comment]
@grokys @kekekeks I've retested it and it doesn't work anymore on both renderers
