### ISSUE TITLE
:valid pseudoclass is being applied to all ContentControls.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#1999]
It appears that a `:valid` pseudoclass is being applied to all `ContentControl`s:

![image](https://user-images.githubusercontent.com/1775141/47321974-b3fc7b80-d656-11e8-931f-339815cb7904.png)

@wdcossey this was added in https://github.com/AvaloniaUI/Avalonia/commit/71d74fe7cdb20811e32dccf882c7cb5fcd0c4dba - what is the purpose of this pseudoclass, and why is it applied to all `ContentControl`s?

**Comment by Gillibald** [comment]
I think we should just remove these and add a null check selector to the style that is using this.

**Comment by grokys** [comment]
There doesn't even seem to be any style using it. 🔥 it i say.

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/71d74fe7cdb20811e32dccf882c7cb5fcd0c4dba/src/Avalonia.Themes.Default/CheckBox.xaml#L43

**Comment by grokys** [comment]
Seems that change snuck in in #1773 and I didn't notice it. It's not mentioned anywhere in the description as far as I can see.

I'm not sure I really like adding a class to _every_ `ContentPresenter` in the application just for this one case, especially when it's named something as unintuitive as `valid`. What's invalid about a `ContentPresenter` with no content? `:valid` in CSS seems to only apply to input fields, which makes more sense.

> Note: The :valid selector only works for form elements with limitations, such as input elements with min and max attributes, email fields with a legal email, or number fields with a numeric value, etc.

`ContentPresenter` definitely isn't one of these.

`:empty` would be a better name for it, but I think a null property selector as suggested by @Gillibald would be a better solution.

**Comment by wdcossey** [comment]
**:empty** doesn't really help with _ContentControl_

Say the Content of a CheckBox is a an empty string (String.Empty) then **:empty** would be true/positive.

If the Content is _null_ then **:empty** would fail (from what I remember during my tests) as null != String.Empty.

If the end-user intentionally sets the Content to String.Empty, this could cause further complications/confusion.

I would be more than happy to correct the issue if we could decide on a course of action.
