### ISSUE TITLE
ListBox does not select properly with repeated items

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2004]
Only one of the top three lines will be selected wherever you click
```
<ListBox >
    <ListBox.Items xmlns:sys="clr-namespace:System;assembly=mscorlib">
      <sys:String>Hello</sys:String>
      <sys:String>Cruel</sys:String>
      <sys:String>World</sys:String>
      <sys:String>Hello</sys:String>
      <sys:String>Cruel</sys:String>
      <sys:String>World</sys:String>
      <sys:String>Hello</sys:String>
      <sys:String>Cruel</sys:String>
      <sys:String>World</sys:String>
      <sys:String>Hello</sys:String>
      <sys:String>Cruel</sys:String>
      <sys:String>World</sys:String>
      <sys:String>Hello</sys:String>
      <sys:String>Cruel</sys:String>
      <sys:String>World</sys:String>
      <sys:String>Hello</sys:String>
      <sys:String>Cruel</sys:String>
      <sys:String>World</sys:String>
      <sys:String>Hello</sys:String>
      <sys:String>Cruel</sys:String>
      <sys:String>World</sys:String>
    </ListBox.Items>

   
    <ListBox.ItemsPanel>
      <ItemsPanelTemplate>
        <StackPanel Spacing="2" />
      </ItemsPanelTemplate>
    </ListBox.ItemsPanel>
    <ListBox.ItemTemplate >
      <DataTemplate >
        <StackPanel Orientation="Horizontal">
          <StackPanel Orientation="Horizontal" Height="24">
            <TextBlock Width="80" Text="{Binding}"></TextBlock>
          </StackPanel>
        </StackPanel>
      </DataTemplate>
    </ListBox.ItemTemplate>
  </ListBox>
```

**Comment by Kermalis** [comment]
ListBox.ScrollIntoView() is also affected by this. It'll only scroll the first instance into view.

**Comment by grokys** [comment]
@MarchingCube you mentioned you'd found some issues in `SelectingItemsControl`: was this one of them?

**Comment by MarchingCube** [comment]
This is a different issue and I can already see it would cause issues in `TreeView` as well.

**Comment by MarchingCube** [comment]
@grokys I checked the TreeView and it just crashes if there are duplicate items.

**Comment by kekekeks** [comment]
BTW, once we get compiler merged those duplicates would be *literally* the same instance. Because compiler uses `ldstr` for loading strings those would be interned by the runtime.

**Comment by ahopper** [comment]
There may be perf benefits from changing how this works, the current solution calls IndexOf on the items collection which causes the bug but also is not very performant with big collections in virtualized lists.

**Comment by MarchingCube** [comment]
One problem is that the `SelectedItem` there just discards the change to the selection as the item is the same. Interestingly if I double click the `SelectedIndex` will get updated.

**Comment by ahopper** [comment]
I only found this as a side effect of creating a repro for another issue, it's not ever been a real world issue for me. but I can see uses for repeated items.

**Comment by Kermalis** [comment]
In my case, I had messages added to the list from events in my game and from players sending messages. It happens very often that the same message is displayed more than once, and scrolling to the first instance of that message automatically is very awkward.

**Comment by FoggyFinder** [comment]
any updates? 
Workaround probably will be simple: just add Id property to the object.

**Comment by grokys** [comment]
I'll try and fix this tomorrow.
