### ISSUE TITLE
High CPU usage on idle when using ProgressBar IsIndeterminate=True

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2012]
I use ControlCatalog Pages for preview in the Theme Editor, when program is at idle the CPU usage is around 23% (4 core machine, so one core is almost 100%). When I switch tabs to simpler layout the CPU usage is almost 0%. Tested with software and hardware rendering (Skia, OpenGL, Win7 x64)  and difference is few percent only.

![perfissuescontrolcatalogpages](https://user-images.githubusercontent.com/2297442/47420610-223c5d80-d77f-11e8-9bbf-cc6e659726c8.gif)

Repro: Just run the app and see CPU usage is task manager.

https://github.com/wieslawsoltes/Avalonia/tree/7b90780404aa178a1e728c0acf764a73acb2a6ba/samples/ThemeEditor

**Comment by wieslawsoltes** [comment]
When you remove progress bar page `ProgressBarPage.xaml` usage comes down do 0%.

So this xaml is responsible for high cpu usage:

```
<UserControl xmlns="https://github.com/avaloniaui">
  <StackPanel Orientation="Vertical" Spacing="4">
    <TextBlock Classes="h1">ProgressBar</TextBlock>
    <TextBlock Classes="h2">A progress bar control</TextBlock>

    <StackPanel>
      <StackPanel Orientation="Horizontal"
                  Margin="0,16,0,0"
                  HorizontalAlignment="Center"
                  Spacing="16">
        <StackPanel Spacing="16">
          <ProgressBar Value="{Binding #hprogress.Value}" />
          <ProgressBar IsIndeterminate="True"/>
        </StackPanel>
        <ProgressBar Value="{Binding #vprogress.Value}" Orientation="Vertical" />
        <ProgressBar Orientation="Vertical" IsIndeterminate="True" />
      </StackPanel>
      <StackPanel Margin="16">
        <Slider Name="hprogress" Maximum="100" Value="40"/>
        <Slider Name="vprogress" Maximum="100" Value="60"/>
      </StackPanel>
    </StackPanel>
  </StackPanel>
</UserControl>
```

**Comment by wieslawsoltes** [comment]
And FPS goes down from 60 to 50 FPS.

**Comment by wieslawsoltes** [comment]
When I set `IsIndeterminate="False"` for both progress bars then CPU usage goes to 0%.

**Comment by devel0** [comment]
I noticed the progressbar IsIndeterminate=true continue to consume cpu even when IsVisible become false ; but there is the need that IsVisible was true for at least one time.

**Comment by grokys** [comment]
I'm unable to get an indeterminate progress bar to show any meaningful amount of CPU usage on my machine, but I can confirm that animation isn't stopped when the control is hidden. Will fix that at least.

**Comment by grokys** [comment]
Ok, seems that the animation system just doesn't respect visibility, and it's going to need a pretty big refactor to work properly :(

**Comment by devel0** [comment]
@grokys thx, i just reported the behavior when not visible to help in identify possible causes, but of course these could not so obviously to fix.
More, the specific case atm I overcome using a textbook "loading...".

**Comment by grokys** [comment]
@devel0 no problem, thanks for reporting it! I'm not that familiar with the animation parts of our code so I didn't even know that we had that problem.

**Comment by CrazyAlex25** [comment]
I build https://github.com/AvaloniaUI/XamlControlsGallery/commit/585f20f36560bf3ae955ae155009eb663b5ff206 and i got the same error.
On tab "Overview" CPU usage ~10-12% (intel i3-3240 @3.4Ghz, 2 cores, 4 threads), but on other tabs ~0.5-2%

If fast scrolling DatePicker , CPU usage ~6-9%
It looks like animations are taking up too many CPU resources
```
Пакет SDK для .NET (отражающий любой global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by maxkatz6** [comment]
It doesn't seem to be a problem with composition renderer anymore.
While it still has potential for improvements, like replacing UI thread animation with render thread animation. But since it would reduce customizability of the control, I would leave as the last resort.
