### ISSUE TITLE
Rendering artifacts when using Skia and OpenGL under Windows

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2013]
![skiaopenglresizingartifacts](https://user-images.githubusercontent.com/2297442/47421595-3aad7780-d781-11e8-95d7-681d86339353.gif)

Repro: Run app with Skia+OpenGL hardware acceleration enabled and resize window.

https://github.com/wieslawsoltes/Avalonia/tree/7b90780404aa178a1e728c0acf764a73acb2a6ba/samples/ThemeEditor

**Comment by kekekeks** [comment]
What happens here is viewport being resized in the middle of a render pass. ANGLE (or DirectX driver) seems to be discarding even back buffer contents. 
In X11 backend I circumvent that by having a separate child window that is resized from the render thread.

If you are referring to black borders, that's DeferredRenderer filling the window with empty background before rendering the scene which isn't yet updated for the new size.

**Comment by grokys** [comment]
Is this still an issue after https://github.com/AvaloniaUI/Avalonia/pull/2092 ?

**Comment by wieslawsoltes** [comment]
@grokys Its still an issue, just tested with 0.8.1-cibuild0001914-beta

**Comment by kekekeks** [comment]
Should no longer be the case when using WinUI composition API. Win7 is supported on "if it works it works" basis
