### ISSUE TITLE
Not fluid animation of ContentTransition when using Expander control

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2014]
![expanderanimation](https://user-images.githubusercontent.com/2297442/47422324-a3e1ba80-d782-11e8-91ab-0edc59326709.gif)

Repro: Just run the app and expand or collapse Expander controls.

https://github.com/wieslawsoltes/Avalonia/tree/7b90780404aa178a1e728c0acf764a73acb2a6ba/samples/ThemeEditor

**Comment by ahopper** [comment]
I wondered if this https://github.com/AvaloniaUI/Avalonia/pull/2056 helped.  I suspect the other cause of jumpy animations I've seen is slow loading of controls so the animation has timed out before the control has loaded (you see no fade on the first time you open calander in control catalog),
