### ISSUE TITLE
Managed file dialog

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2016]
We need one for X11/Wayland backends since we can't rely on native toolkits to do it for us.

Anatomy of GTK file dialog:

![default](https://user-images.githubusercontent.com/1067584/47429257-76a30580-d79e-11e8-8da0-3b079808e67a.png)
![default](https://user-images.githubusercontent.com/1067584/47429460-25dfdc80-d79f-11e8-8343-7fed09929648.png)

1. XDG user directories. Those have *localized names*, but standartized across DEs
2. User's favorites. They are stored in different locations of the file system depending on the toolkit. We should detect available ones and select one by looking at `XDG_CURRENT_DESKTOP` environment variable
3. Icons extracted from the current icon theme
4. Mountable locations. Can be obtained and manipulated using udisks DBus

Basically we need some managed dialog, that consumes a service providing those and with Linux implementation.

Later on we could extend the support to Windows/OSX and make the dialog available in our public API, so people could make customizations.

So, where to get the info on Linux.

1. The list of directories is located in `XDG_CONFIG_HOME/user-dirs.dirs` (if exists) and in `XDG_CONFIG_DIRS/user-dirs.defaults`. Note that there could be multiple directories in `XDG_CONFIG_DIRS`. Localization data is stored in `/usr/share/locale/{LANGID}/LC_MESSAGES/xdg-user-dirs.mo` and can be obtained with `gettext` from `libc`
2. User's favorites can be stored in following locations:
- gsettings: `gsettings get org.gnome.shell favorite-apps`
- `~/.gtk-bookmarks`
- `~/.gtk-bookmarks`
- `~/.kde/share/apps/kfileplaces/bookmarks.xml`
- `~/.kde/share/apps/kfile/bookmarks.xml`
3. Icon theme is configured in either gsettings or plasmarc. We need to guess the one that we need to use (if there are multiple) by looking at `XDG_CURRENT_DESKTOP`. After that we should follow the location process described in https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
The problem here is that icons are associated with MIME-types, not file extensions. For MIME types we should use https://standards.freedesktop.org/shared-mime-info-spec/latest/

4. Mountable locations (like USB drives) are managed via UDisks DBUS interface: http://storaged.org/doc/udisks2-api/2.8.1/ref-dbus.html
We can use this library for DBus communication: https://developers.redhat.com/blog/2017/09/18/connecting-net-core-d-bus/

For now we could skip network locations since it would be way too DE/toolkit specific.

**Comment by danwalmsley** [comment]
done
