### ISSUE TITLE
ItemTemplateSelector and XamlLoader

### ISSUE THREAD

**Issue by SpawnProd** [AvaloniaUI/Avalonia#2018]
Good time of day.
Is there something like WPF's ItemTemplateSelector in TreeView? An also how i can load some xaml at runtime. If no ItemTemplateSelector, then what i can use instead?
Thanks,

**Comment by kekekeks** [comment]
1) Use `DataTemplates` property, you can specify multiple templates, each for a particular data type, see http://avaloniaui.net/docs/templates/datatemplate
2) AvaloniaXamlLoader.Parse

**Comment by SpawnProd** [comment]
> 1. Use `DataTemplates` property, you can specify multiple templates, each for a particular data type, see http://avaloniaui.net/docs/templates/datatemplate
> 2. AvaloniaXamlLoader.Parse

Well, I don't have any special type, everything creating dynamically. ItemTemplateSelector allow us to choose different DataTemplates for one type.

**Comment by grokys** [comment]
One possibility might be to create a new template type which inherits from `Avalonia.Markup.Xaml.Templates.DataTemplate`. You can then override `IDataTemplate.Match` to add your matching logic. For example if you wanted to match all view models which have `Foo == "bar"` you could do:

```
public class MyDataTemplate : DataTemplate, IDataTemplate
{
  bool IDataTemplate.Match(object data) => (data is MyViewModel)?.Foo == "bar";
}
```

Without knowing more details of your scenario it's hard to say however.

**Comment by SpawnProd** [comment]
> One possibility might be to create a new template type which inherits from `Avalonia.Markup.Xaml.Templates.DataTemplate`. You can then override `IDataTemplate.Match` to add your matching logic. For example if you wanted to match all view models which have `Foo == "bar"` you could do:
> 
> ```
> public class MyDataTemplate : DataTemplate, IDataTemplate
> {
>   bool IDataTemplate.Match(object data) => (data is MyViewModel)?.Foo == "bar";
> }
> ```
> Without knowing more details of your scenario it's hard to say however.

Great idea, i'll try it.
