### ISSUE TITLE
Direct3DInteropSample is not working propertly

### ISSUE THREAD

**Issue by mudi2k** [AvaloniaUI/Avalonia#2024]
HI,

_Direct3DInteropSample_ runs a black screen with overlayed Avalonia controls when it's configured as normal rendering:

![deferredfalse](https://user-images.githubusercontent.com/7009218/47508109-c30c4500-d873-11e8-9ef5-0c260e87bb0b.jpg)

 and shows the Direct3D image when deferredRendering is set, but hides the Avalonia controls.

![deferredtrue](https://user-images.githubusercontent.com/7009218/47508110-c3a4db80-d873-11e8-80e0-e955967bd40e.jpg)

Regards

**Comment by elad8a** [comment]
Seems like the Avalonia.Rendering.ImmediateRenderer clears the render target right after direct3d renders its content:

```
public void Paint(Rect rect)
...
context.PlatformImpl.Clear(Colors.Transparent);
```
