### ISSUE TITLE
Portable.Xaml.Schema missing in src?

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [AvaloniaUI/Avalonia#2029]
Hello I cannot compile the source,there is too more errors.like Portable.Xaml.Schema missing:

![untitled](https://user-images.githubusercontent.com/5262218/47588703-e1596a00-d973-11e8-994c-373ff1fb1b84.png)

**Comment by ahopper** [comment]
Have you pulled the submodules as described here http://avaloniaui.net/contributing/build

**Comment by Ali-YousefiTelori** [comment]
Thank You @ahopper after remove all git and clone again with your solution works fine
