### ISSUE TITLE
Warning Message at Startup

### ISSUE THREAD

**Issue by jeffreye** [AvaloniaUI/Avalonia#2030]
Here are the messages I get from the logger at startup

1. Error loading libegl.dll error 

2. Property: Property '"Avalonia.Media.TranslateTransform"."X"' is not registered on  '"Avalonia.Controls.Border"'.  ( This is coming from the style of [ProgressBar](https://github.com/AvaloniaUI/Avalonia/blob/a39739b24dcf4d126de03a62ed2e97daaf4abaf1/src/Avalonia.Themes.Default/ProgressBar.xaml) )

3. Binding: Error in binding to "Avalonia.ValueStore"."Value": "Null value in expression ''."

Reproduce steps:
- Add Avalonia.Logging.Serilog project reference to ControlCatalog
- using Avalonia.Logging.Serilog;
- Add .LogToDebug() to BuildAvaloniaApp method
- Run it

**Comment by jmacato** [comment]
This is due to animations subsystem reusing the style's setter class, it can animate 2nd-order properties (RenderTransforms etc.) hence the warning that the target property is missing on the target control.

**Comment by jmacato** [comment]
We should probably give Animations a free ticket on those warnings so that it wont litter the Binding subsystem's logs.

**Comment by jmacato** [comment]
No. 3 (null warnings) is not related to the abovementioned issues. @jkoritzinsky knows more about those than me
