### ISSUE TITLE
Line rendering issue

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#2038]
When using two lines one pixel apart from one another, they affect each others' colors even though the stroke thickness is 1 pixel.
Before and after changing a line's stroke color:
![image](https://user-images.githubusercontent.com/29823718/47629074-75136d80-db0f-11e8-81e4-ed3abebc1ac8.png)
I only changed the top line in this case, but the one directly under it changes color as well (and the one under that also slightly changes)
This is really annoying because I need exact colors for each y coordinate and them affecting one another when they have no reason to seems to be unintentional

The xaml:
```
<Line StartPoint="0,335" EndPoint="512,335" Stroke="#C3000000" IsVisible="{Binding IsMessageBoxVisible}" ZIndex="2"/>
<Line StartPoint="0,336" EndPoint="512,336" Stroke="#35000000" IsVisible="{Binding IsMessageBoxVisible}" ZIndex="2"/>
<Line StartPoint="0,337" EndPoint="512,337" Stroke="#7C000000" IsVisible="{Binding IsMessageBoxVisible}" ZIndex="2"/>
```

**Comment by Gillibald** [comment]
Related to: #199
Needs implementation of RenderOptions. EdgeMode
