### ISSUE TITLE
Window is not drawn correctly when running Windows 7 SP1 x64 and ANGLE dll are missing

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2045]
The window is only white rectangle, nothing else is drawn. 

This is caused by missing:
```
d3dcompiler_47.dll
libegl.dll
libglesv2.dll
```
in this case software rendering should be used instead.

This is using `netcoreapp2.0` published as `win7-x64`.

https://github.com/AvaloniaUI/Avalonia/tree/326f74f3989e3358c87bbec60cdcf263edda4d1f

**Comment by danwalmsley** [comment]
fixed https://github.com/AvaloniaUI/Avalonia/commit/67c2ff25dee0e5cfff7c322cb15aef40414922ef
