### ISSUE TITLE
Window is not invalidated when maximized or restored when running Windows 7 SP1 x64 Skia+OpenGL

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2047]
Windows 7 SP1 x64
Skia+OpenGL
netcoreapp2.0

Normal:
![normal](https://user-images.githubusercontent.com/2297442/47662130-a8e7a500-db9a-11e8-9c7e-26052136888a.PNG)

Maximized:
![maximized](https://user-images.githubusercontent.com/2297442/47662147-b00eb300-db9a-11e8-98bb-e624f3ccf664.PNG)

Restored:
![restored](https://user-images.githubusercontent.com/2297442/47662168-b735c100-db9a-11e8-8a83-8e4479d24467.PNG)

https://github.com/AvaloniaUI/Avalonia/tree/326f74f3989e3358c87bbec60cdcf263edda4d1f

**Comment by danwalmsley** [comment]
fixed https://github.com/AvaloniaUI/Avalonia/commit/67c2ff25dee0e5cfff7c322cb15aef40414922ef
