### ISSUE TITLE
Invalid key mapping with azerty keyboard and ctrl modifier

### ISSUE THREAD

**Issue by latop2604** [AvaloniaUI/Avalonia#2049]
With latest prerelease package (0.7.0-build429-beta), on OSX, when I press `Ctrl+A`, `Key_Up` event (or other key events) send me an `Avalonia.InputKeyEventArgs.Key` == `Avalonia.Input.Key.Q`

Common shortcut like undo/redo (ctrl+z/ctrl+y) are also map on querty schema instead of azerty.

But inside a textbox the mapping is correct.

**Comment by grokys** [comment]
@danwalmsley is this still a problem?

**Comment by Energizer188** [comment]
Hey there,
I'm experiencing kind of the same problem on v. 0.10.18.
My keyboard is an azerty one. When I run my app on Windows the mapping is correct, but when I run it on mac it maps like a qwerty (so my A key raises a Q key pressed event for example).

Any idea on how to make it work correctly?
