### ISSUE TITLE
Dialogs rework

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2052]
I don't quite like how our dialogs work. Right now we are showing a window that grabs all events and disallows interaction with other windows basically. That's not how other toolkits work and that's not how window systems work.

There is a concept of "transient" windows. In Win32 API it's represented by GWL_HWNDPARENT, in X11 it's WM_TRANSIENT_FOR hint. Effectively those make sure that a window stays on top of a particular window parent.

Our dialog API is async, so ShowDialog should return immediately. So there is no point of having a parentless dialog window.

I propose to make ShowDialog to have a parent window. Same thing for file dialogs, since we have issues with them not showing properly because of that.

I'm not sure that it makes sense to have non-dialog transient windows.

This was somewhat discussed in #1542 

Another question is if we should block non-parent windows when showing a dialog. In multi-window applications (e. g. some kind of a document editor) that makes sense for some global settings dialog, but doesn't make sense for a print dialog that's associated with a particular document. I'm not sure if we can make this behavior application controlled though.

**Comment by aelij** [comment]
I don't like using OS (modal) dialogs at all. See my reasoning here: https://arbel.net/2014/04/23/the-misbehaving-dialog/
Perhaps something to consider as an alternate dialog API :)

**Comment by kekekeks** [comment]
> I believe most browsers do not use OS-based dialogs for these reason.

Firefox and Chrome are opening an OS file dialog when I press Ctrl+O.

We could introduce `Show` method for OS file dialogs.
I'm also currently developing a managed file dialog which could be used as a *control* in the future.
