### ISSUE TITLE
Wrong TextBox Text Selection

### ISSUE THREAD

**Issue by Sorien** [AvaloniaUI/Avalonia#2065]
there is wrong text box selection when you move pointer outside of control 

![broken_selection](https://user-images.githubusercontent.com/1270275/47915935-b8b9fe80-dea4-11e8-8b20-8586ed870ead.gif)

something like that fixes it but it just hides the problem
```c#
// TextPresenter.cs
        public int GetCaretIndex(Point point)
        {
+            point = point.WithY(Math.Max(Math.Min(point.Y, FormattedText.Constraint.Height - 1), 0));
            var hit = FormattedText.HitTestPoint(point);
            return hit.TextPosition + (hit.IsTrailing ? 1 : 0);
        }
```

![selection](https://user-images.githubusercontent.com/1270275/47915947-c1aad000-dea4-11e8-9acd-def5bd71a622.gif)

**Comment by Gillibald** [comment]
So you try to hit test a point that is outside the boundaries of the text layout and that crashes or what is wrong about it?

Selection handling will change soon with the new skia text layout and all its changes to TextBox.

We should write a failing unit test for this.

**Comment by Sorien** [comment]
it sets endSelection to 0 when you move pointer over top and sets endSelection to textlength when you move pointer bellow textbox

e.g. you have selected carret 10, endselection 9 and you move pointer over top it will set endselction to 0   instead of keeping 9

**Comment by Gillibald** [comment]
Isn't that expected behavior? We should make sure how other editors handle this. It makes sense to me to set the end selection to 0 when above and to textlength when beneath.

**Comment by Sorien** [comment]
nop, just check native controls

**Comment by Sorien** [comment]
and there is broken selection in right aligned text

![broken_right_selection](https://user-images.githubusercontent.com/1270275/47915711-02eeb000-dea4-11e8-9753-23290fb37259.gif)

**Comment by Gillibald** [comment]
I think the fix to this should happen in the mouse event handler. The current point should never move outside the boundaries of the TextPresenter.
