### ISSUE TITLE
Shapes in negative 2D space are not rendered

### ISSUE THREAD

**Issue by Polymaker** [AvaloniaUI/Avalonia#2068]
I am trying to render lines in a canvas that are defined using a 2D space with origin {0,0} at the center of the screen. To accomplish that I apply a TranslateTransform to my canvas (or to each line but it has the same effect).
I noticed that when a shape's bottom-right corner is in negative 2d space, it's bounds are not properly calculated and thus is it not rendered.
I am not sure if this is intended or a bug, but there is no issue doing that with WPF.

**Comment by wieslawsoltes** [comment]
Try setting property ClipToBounds="False"
