### ISSUE TITLE
Opaque regions around window corners

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#2069]
<img width="83" alt="screen shot 2018-10-19 at 09 09 54" src="https://user-images.githubusercontent.com/892945/47200418-c89ef200-d37e-11e8-9aa6-cbc50abf2964.png">

You could see white corners on the screenshot.

**Comment by ForNeVeR** [comment]
Additional info from #2665: issue seem to only appear when I set `MinHeight` or `MinWidth` on the window.
