### ISSUE TITLE
I create a project and build, there is the error in design-view (visual studio 2017):

### ISSUE THREAD

**Issue by LazyCuteLion** [AvaloniaUI/Avalonia#2072]
Designer process crashed
Launching designer process: 
c:\users\hj-lazysheeeep\appdata\local\microsoft\visualstudio\15.0_eafbc034\extensions\5cv5pyhk.thi\lib\Avalonia.Designer.HostApp.exe --transport tcp-bson://127.0.0.1:53305/ --session-id ff94054a-9267-4f9a-8e53-8b248edbf945 --method win32 "C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Demo.exe"
from directory C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Animation.dll
Loading 
……
……
Obtaining AppBuilder instance from Avalonia.Demo.Program.BuildAvaloniaApp
Initializing application in design mode

未经处理的异常:  System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 Avalonia.OpenGL.EglDisplay..ctor(EglInterface egl)
   在 Avalonia.OpenGL.EglGlPlatformFeature.TryCreate()
   在 Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__5_0()
   在 Avalonia.AvaloniaLocator.RegistrationHelper`1.<>c__DisplayClass3_0`1.<ToFunc>b__0()
   在 Avalonia.AvaloniaLocator.GetService(Type t)
   在 Avalonia.LocatorExtensions.GetService[T](IAvaloniaDependencyResolver resolver)
   在 Avalonia.Skia.PlatformRenderInterface..ctor()
   在 Avalonia.Skia.SkiaPlatform.Initialize()
   在 Avalonia.SkiaApplicationExtensions.<>c__0`1.<UseSkia>b__0_0()
   在 Avalonia.Controls.AppBuilderBase`1.Setup()
   在 Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.AppInitializer`1.GetConfiguredApp(IAvaloniaRemoteTransportConnection transport, CommandLineArgs args, Object obj)
   在 Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline)
   在 Avalonia.Designer.HostApp.NetFX.Program.Exec(String[] args)
   在 Avalonia.Designer.HostApp.NetFX.Program.Main(String[] args)

**Comment by LazyCuteLion** [comment]
Designer process crashed
Launching designer process: 
c:\users\hj-lazysheeeep\appdata\local\microsoft\visualstudio\15.0_eafbc034\extensions\5cv5pyhk.thi\lib\Avalonia.Designer.HostApp.exe --transport tcp-bson://127.0.0.1:53305/ --session-id ff94054a-9267-4f9a-8e53-8b248edbf945 --method win32 "C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Demo.exe"
from directory C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Animation.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Base.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Controls.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.DesignerSupport.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Desktop.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.DesktopRuntime.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Diagnostics.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Direct2D1.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Gtk3.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Input.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Interactivity.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Layout.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Logging.Serilog.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Markup.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Markup.Xaml.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Native.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.OpenGL.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Remote.Protocol.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Skia.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Styling.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Themes.Default.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Visuals.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Avalonia.Win32.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\JetBrains.Annotations.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\libSkiaSharp.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Microsoft.Win32.Primitives.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\netstandard.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Serilog.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Serilog.Sinks.Debug.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\Serilog.Sinks.Trace.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\SharpDX.Direct2D1.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\SharpDX.Direct3D11.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\SharpDX.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\SharpDX.DXGI.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\SharpGen.Runtime.COM.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\SharpGen.Runtime.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\SkiaSharp.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.AppContext.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Buffers.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Collections.Concurrent.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Collections.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Collections.NonGeneric.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Collections.Specialized.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.ComponentModel.Annotations.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.ComponentModel.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.ComponentModel.EventBasedAsync.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.ComponentModel.Primitives.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.ComponentModel.TypeConverter.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Console.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Data.Common.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Diagnostics.Contracts.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Diagnostics.Debug.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Diagnostics.DiagnosticSource.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Diagnostics.FileVersionInfo.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Diagnostics.Process.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Diagnostics.StackTrace.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Diagnostics.TextWriterTraceListener.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Diagnostics.Tools.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Diagnostics.TraceSource.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Diagnostics.Tracing.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Drawing.Common.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Drawing.Primitives.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Dynamic.Runtime.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Globalization.Calendars.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Globalization.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Globalization.Extensions.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.IO.Compression.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.IO.Compression.ZipFile.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.IO.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.IO.FileSystem.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.IO.FileSystem.DriveInfo.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.IO.FileSystem.Primitives.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.IO.FileSystem.Watcher.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.IO.IsolatedStorage.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.IO.MemoryMappedFiles.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.IO.Pipes.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.IO.UnmanagedMemoryStream.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Linq.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Linq.Expressions.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Linq.Parallel.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Linq.Queryable.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Memory.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Net.Http.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Net.NameResolution.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Net.NetworkInformation.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Net.Ping.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Net.Primitives.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Net.Requests.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Net.Security.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Net.Sockets.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Net.WebHeaderCollection.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Net.WebSockets.Client.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Net.WebSockets.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Numerics.Vectors.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.ObjectModel.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Reactive.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Reflection.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Reflection.Extensions.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Reflection.Primitives.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Resources.Reader.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Resources.ResourceManager.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Resources.Writer.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Runtime.CompilerServices.Unsafe.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Runtime.CompilerServices.VisualC.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Runtime.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Runtime.Extensions.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Runtime.Handles.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Runtime.InteropServices.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Runtime.InteropServices.RuntimeInformation.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Runtime.Numerics.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Runtime.Serialization.Formatters.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Runtime.Serialization.Json.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Runtime.Serialization.Primitives.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Runtime.Serialization.Xml.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Security.Claims.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Security.Cryptography.Algorithms.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Security.Cryptography.Csp.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Security.Cryptography.Encoding.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Security.Cryptography.Primitives.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Security.Cryptography.X509Certificates.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Security.Principal.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Security.SecureString.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Text.Encoding.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Text.Encoding.Extensions.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Text.RegularExpressions.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Threading.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Threading.Overlapped.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Threading.Tasks.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Threading.Tasks.Parallel.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Threading.Thread.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Threading.ThreadPool.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Threading.Timer.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.ValueTuple.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Xml.ReaderWriter.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Xml.XDocument.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Xml.XmlDocument.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Xml.XmlSerializer.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Xml.XPath.dll
Loading C:\Users\hj-lazysheeeep\Desktop\Avalonia\Avalonia.Demo\bin\Debug\net461\System.Xml.XPath.XDocument.dll
Obtaining AppBuilder instance from Avalonia.Demo.Program.BuildAvaloniaApp
Initializing application in design mode

未经处理的异常:  System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 Avalonia.OpenGL.EglDisplay..ctor(EglInterface egl)
   在 Avalonia.OpenGL.EglGlPlatformFeature.TryCreate()
   在 Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__5_0()
   在 Avalonia.AvaloniaLocator.RegistrationHelper`1.<>c__DisplayClass3_0`1.<ToFunc>b__0()
   在 Avalonia.AvaloniaLocator.GetService(Type t)
   在 Avalonia.LocatorExtensions.GetService[T](IAvaloniaDependencyResolver resolver)
   在 Avalonia.Skia.PlatformRenderInterface..ctor()
   在 Avalonia.Skia.SkiaPlatform.Initialize()
   在 Avalonia.SkiaApplicationExtensions.<>c__0`1.<UseSkia>b__0_0()
   在 Avalonia.Controls.AppBuilderBase`1.Setup()
   在 Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.AppInitializer`1.GetConfiguredApp(IAvaloniaRemoteTransportConnection transport, CommandLineArgs args, Object obj)
   在 Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline)
   在 Avalonia.Designer.HostApp.NetFX.Program.Exec(String[] args)
   在 Avalonia.Designer.HostApp.NetFX.Program.Main(String[] args)

**Comment by johnmbaughman** [comment]
I'm not sure if this is related, but with the net461 build, I get the following exception
`Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: No rendering subsystem found. Are you missing assembly references?
   at Avalonia.AppBuilder.UsePlatformDetect()
   at AvaloniaMvvmTest.Program.BuildAvaloniaApp()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline)
   at Avalonia.Designer.HostApp.NetFX.Program.Exec(String[] args)
   at Avalonia.Designer.HostApp.NetFX.Program.Main(String[] args)`

All other builds work fine.

**Comment by grokys** [comment]
We will have a new designer for 0.8 which should fix this. In the meantime you can try https://github.com/AvaloniaUI/AvaloniaVS (you'll need to build it yourself as it's changing hourly).
