### ISSUE TITLE
[OSX] Remove _clock_gettime to support < macOS 10.12

### ISSUE THREAD

**Issue by nopara73** [AvaloniaUI/Avalonia#2073]
A user of ours reported that macOS 10.11.6 doesn't work, because the backend uses `_clock_gettime` call that was only introduced in macOS 10.12.  https://github.com/zkSNACKs/WalletWasabi/issues/785

There might be other problems, there might not. Is it possible to somehow remove it?

```sh
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/WasabiOsx/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/WasabiOsx/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```
https://github.com/pocoproject/poco/issues/1453#issuecomment-254663587

> clock_gettime() was added in macOS 10.12. You need to build against an earlier SDK if you want to be backwards compatible.

**Comment by danwalmsley** [comment]
@kekekeks

**Comment by kekekeks** [comment]
It's limitation of .NET Core which requires OS X 10.12. You may try to run on Mono.

**Comment by kekekeks** [comment]
I'm closing this issue, since it's related to the used .NET runtime rather than Avalonia.
