### ISSUE TITLE
Add Support for System.Windows.Interactivity Equivalent

### ISSUE THREAD

**Issue by Mike-EEE** [AvaloniaUI/Avalonia#208]
System.Windows.Interactivity adds two important concepts in WPF/Silverlight development: [Behaviors](https://msdn.microsoft.com/en-us/library/system.windows.interactivity.behavior(v=expression.40).aspx) and [Triggers](https://msdn.microsoft.com/en-us/library/system.windows.interactivity.triggerbase(v=expression.40).aspx).

Behaviors enable encapsulated composition on a component, where you can design a behavior to meet a control type and it will wireup and perform the desired behavior on the control.  An example of this would be [focusing a default control item in a scene](https://github.com/DragonSpark/Framework/blob/LightSwitch-Legacy/DragonSpark.Client/Application/Presentation/Interaction/DefaultFocusElement.cs).

Triggers are what they sound like.  There is definitely overlap with the built-in triggers, and honestly I never explored this as there was only one built-in trigger in Silverlight (EventTrigger) so I do not know the difference.  However, they do work the same.  You can create a trigger, and then you can create an action that occurs when a trigger is fired.  Here is an example of a [trigger that would fire when the underlying model changed a property](https://github.com/DragonSpark/Framework/blob/LightSwitch-Legacy/DragonSpark.Client/Application/Presentation/Interaction/PropertyChangedTrigger.cs).  And here is an example of a TriggerAction that [sets the index on a selector](https://github.com/DragonSpark/Framework/blob/LightSwitch-Legacy/DragonSpark.Client/Application/Presentation/Interaction/SetIndexAction.cs).

If interested, a good list of legacy components/examples (mostly Behaviors) [can be found here](https://github.com/DragonSpark/Framework/tree/LightSwitch-Legacy/DragonSpark.Client/Application/Presentation/Interaction).

Some use cases:
- As a developer, I want to drag and drop elements in a elegant and controlled way ([DragAndDropBehavior](https://github.com/SuperJMN/Glass-Legacy/tree/master/Glass.Basics/Basics/Behaviors/DragDrop/DragDropBehavior.cs)).
- As a developer, I want to display a dialog when a certain amount of time passes (DelayTrigger paired with DisplayDialogTriggerAction).
- As a developer, I want to play an animation when a user closes a screen (EventTrigger paired with ControlPlayboardTriggerAction)
- As a developer, I want to update the size of one control when another control resizes (ResizeBehavior).

... and many many more. :)

**Comment by SuperJMN** [comment]
Sample usage for me was adding a DragDropBehavior in WPF that enabled the implementation of Drag & Drop, that is tightly coupled to the UI, making use of MVVM.

Behaviors provide a very high level of encapsulation AND the reusability. 
Event Triggers that launch commands are a must in my opinion, for MVVM sake. And yes, MVVM is my creed :)

**Comment by ncarrillo** [comment]
I think Behaviors are important to have to encapsulate view functionality for reusability. +1 to this idea. Not sure about Triggers/Actions, I have little experience. How do they compare to triggers in WPF? And what we may have in Perspex

**Comment by Michael-DST** [comment]
Yeah that is a good question.  There are built-in Triggers for WPF, but then System.Windows.Interactivity also adds them as well.  SWI was available in Silverlight, so that is the only exposure I have had to them.  Conceptually I know that they are the same, so that adds to confusion.  Here is a nice article describing Interactivity:
http://www.codeproject.com/Tips/401707/Behavior-and-Trigger-in-WPF-Silverlight

**Comment by jazzay** [comment]
I have a preliminary implementation working. Will see if my implementation fulfills the needs of this request.

**Comment by wieslawsoltes** [comment]
Support for XAML defined Behaviors for Perspex can be found here https://github.com/XamlBehaviors/XamlBehaviors.
