### ISSUE TITLE
Problem with TabControl (TabItem header) and custom controls.

### ISSUE THREAD

**Issue by igorstefus** [AvaloniaUI/Avalonia#2083]
I am trying to use custom control from control library in another project as content of TabItem header. Problem is that our custom control can’t find default template when placed in TabItem header. It loads template just fine in any other case I tried it in header of expander control for example.

This is the [link](https://bitbucket.org/igorstefus/avalonia_tab_control_issue/src/master/) to repo of small project demonstrating this issue.

I would appreciate if somebody can check it as it seems like something that can create problem for many users. 

Igor

**Comment by grokys** [comment]
Hi @igorstefus - yeah sorry our `TabControl` isn't great at the moment. I wonder if you would be able to try out https://github.com/AvaloniaUI/Avalonia/pull/1842 which @Gillibald has been working on and see if that fixes it for you?

If you build the PR, the easier way to test might be to use the `ReplaceNugetCache` scripts in https://github.com/AvaloniaUI/Avalonia/tree/master/scripts to overwrite the libraries in your package cache to with the libraries you built.

It would be really helpful if you could help us test this PR!

**Comment by Gillibald** [comment]
I have just merged that PR with current master to make sure it is up to date.

**Comment by Gillibald** [comment]
Should be fixed by #1842
