### ISSUE TITLE
Compact scrollbar

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#2086]
It's visual improvements, which is already implemented in UWP.
As description, I quote [docs](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/scroll-controls):

> Depending on the situation, the scroll viewer's scrollbar uses two different visualizations, shown in the following illustration: the panning indicator and the traditional scrollbar.
> The scroll viewer is conscious of the user’s input method and uses it to determine which visualization to display.
> - When the region is scrolled without manipulating the scrollbar directly, for example, by touch, the panning indicator appears, displaying the current scroll position.
> - When the mouse or pen cursor moves over the panning indicator, it morphs into the traditional scrollbar. Dragging the scrollbar thumb manipulates the scrolling region.

![image](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/images/conscious-scroll.gif)

**Comment by grokys** [comment]
Damn for a second I thought this was a PR and got really excited ;) Yes - this feature - please!

**Comment by maxkatz6** [comment]
Done with https://github.com/AvaloniaUI/Avalonia/pull/4119
Thanks @MarchingCube !
