### ISSUE TITLE
Context menus for textboxes

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2093]
```
Undo
Redo
----
Cut
Copy
Paste
Delete
----
Select All
```

We probably also need some basic system for translations.

**Comment by danwalmsley** [comment]
This likely points to the need for ApplicationCommands class (see wpf)

**Comment by kekekeks** [comment]
The need of `RoutedCommand` infrastructure, actually. For now these items could be hardcoded in TextBox control itself.

**Comment by maxkatz6** [comment]
Was mostly done with 0.10, without RoutedCommand though.
It still makes sense to implement something similar to TextCommandBarFlyout from WinUI.
