### ISSUE TITLE
SetDpiAwareness on Win7 causes EntryPointNotFoundException

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#2095]
Windows 7 only crash.

```
Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'Avalonia.Win32.Win32Platform' threw an exception. ---> System.EntryPointNotFo
undException: Unable to find an entry point named 'SetProcessDpiAwarenessContext
' in DLL 'user32.dll'.
at Avalonia.Win32.Interop.UnmanagedMethods.SetProcessDpiAwarenessContext(IntP
tr dpiAWarenessContext)
at Avalonia.Win32.Win32Platform.SetDpiAwareness()
at Avalonia.Win32.Win32Platform..ctor()
at Avalonia.Win32.Win32Platform..cctor()
```

**Comment by kekekeks** [comment]
#1801

**Comment by grokys** [comment]
Hmm, strange - what version of Avalonia and Win7 are you using? This should have been fixed to not call that method if it doesn't exist in #2010. I've just tried again on my Win7 SP1 VM and it seems to work:

![image](https://user-images.githubusercontent.com/1775141/48872480-83d90180-ede9-11e8-9fa0-c6cb1b9323d3.png)

**Comment by x2bool** [comment]
Usually the most recent version from nightly feed. This was reported by a user of my project. I'll ask him to try again.

**Comment by x2bool** [comment]
I finally tested it myself. Win7 works now just fine. Thanks.
