### ISSUE TITLE
ListBox Virtualization sometimes prevents last item selection

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2106]
To repro run the VirtualizationDemo, select an item in the list then use the down arrow to move to the last item, sometimes the last item is never shown.  If the last item is made visible by scrolling to it, sometimes clicking on it causes it to be scrolled out of view.

**Comment by donandren** [comment]
another repro:
scroll to last item in listbox, then scroll again with code:

```
//get listbox from usercontrol with many items
var lb = this.Get<ListBox>("listbox");
lb.ScrollIntoView(lb.Items.OfType<object>().Last());
//second time it scrolls to item before last
lb.ScrollIntoView(lb.Items.OfType<object>().Last());
```

**Comment by donandren** [comment]
another repro:
change MainWindow.xaml in VirtualizationDemo, add listbox in Grid like:

```xaml
<Window xmlns="https://github.com/avaloniaui"
        Title="AvaloniaUI Virtualization Test"
        Width="800"
        Height="800">
        ...
        <Grid RowDefinitions="*,*" Height="576" VerticalAlignment="Center">
        <ListBox Name="listBox" 
        ...
      </Grid>
```
resize it little bit as current master have some strange black borders.
press Recreate, then Select Last, then Recreate, then Select Last -> Last item it's partially visible
![2018-12-05_23-37-42](https://user-images.githubusercontent.com/13854631/49545947-ca4d5680-f8e7-11e8-8f54-d6b2611531a2.gif)
