### ISSUE TITLE
Menu is not closed when window Titlebar is clicked

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#211]
![bez tytulu](https://cloud.githubusercontent.com/assets/2297442/10119942/2e260f28-64a6-11e5-9faa-a2d4008ce10c.png)

**Comment by wieslawsoltes** [comment]
After the fix you can not move the window. The close, minimize and maximize window buttons do not work.

**Comment by ncarrillo** [comment]
@wieslawsoltes It should be fixed now

**Comment by wieslawsoltes** [comment]
After the fix you titlebar and buttons are usable, but there are issues with menu showing when you click on window titlebar or one of window titlebar buttons.

**Comment by wieslawsoltes** [comment]
https://github.com/Perspex/Perspex/blob/master/src/Windows/Perspex.Win32/WindowImpl.cs#L326

Changing `new Point(0, 0)` to `new Point(-1, -1)` fixes Menu not showing when you click to window titlebar.

**Comment by wieslawsoltes** [comment]
Is it necessary to handle this messages?

``` C#
case UnmanagedMethods.WindowsMessage.WM_NCLBUTTONDOWN:
case UnmanagedMethods.WindowsMessage.WM_NCRBUTTONDOWN:
case UnmanagedMethods.WindowsMessage.WM_NCMBUTTONDOWN:
```

**Comment by grokys** [comment]
Yesm @ncarrillo's fix has caused other problems, namely that when clicking on the non-client area, it activates the control at 0,0.

@wieslawsoltes' suggestion of using `Point(-1, -1)` would work for most cases, but if there's a control at 0,0 with a negative margin for example, that will be activated.

I think we need a separate even for non-client clicks.

**Comment by grokys** [comment]
This should now be fixed.
