### ISSUE TITLE
Add Avalonia topic to github explore

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#2110]
Here: https://github.com/github/explore

Moreover, I recommend marking Avalonia projects with the corresponding topic. It would be more convenient to search Avalonia projects through GitHub.

**Comment by worldbeater** [comment]
Avalonia topic is now added to GitHub Explore, see https://github.com/github/explore/pull/691
Related topics are: [#avalonia](https://github.com/topics/avalonia), [#avaloniaui](https://github.com/topics/avaloniaui) 🎉

**Comment by KvanTTT** [comment]
Great! I'm closing this.
