### ISSUE TITLE
Add TabControl page to ControlCatalog

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2113]
I think we need to have TabControl page with TabControl  examples so when making changes to themes we can quickly visually inspect theme changes and if something has broken.

**Comment by grokys** [comment]
#1842 adds this! I'm hoping to get it merged soon

**Comment by wieslawsoltes** [comment]
@grokys Great news!

**Comment by grokys** [comment]
I've merged #1842 so closing this!
