### ISSUE TITLE
How to set DataContext in own UserControl?

### ISSUE THREAD

**Issue by Slesa** [AvaloniaUI/Avalonia#2121]
Hi all,

is there an example how to write your own UserControl with a correct DataContext? MainWindow works out of the box. Now I wanted to have my own control as part of it. The view itself is shown, but the viewmodel must be taken from the DI due to ctor injection.

I already tried it with a datatemplate for the viewmodel, as there is a ViewLocator.cs generated, but then I get the error that the type of the viewmodel would be unknow. Not sure if this is the right way anyway...

**Comment by kekekeks** [comment]
DI shouldn't be involved on the view level, that's what view model level is here for.

Basic design would be something like:
```cs
class SomeViewModel
{
}

class MainWindowModel
{
     public MainViewModel(SomeViewModel subViewModel)
     {
           SubViewModel = subViewModel;
     }
     public SomeViewModel SubViewModel {get;set;}
}
```
(make sure to either implement INotifyPropertyChanged manually, use Fody.PropertyChanged, or ReactiveUI)

Then somewhere in MainWindow.xaml
```xml
<MyView DataContext="{Binding SubViewModel}"/>
```

**Comment by kekekeks** [comment]
Also see 
https://blog.qmatteoq.com/the-mvvm-pattern-dependency-injection/
https://stackoverflow.com/questions/25366291/how-to-handle-dependency-injection-in-a-wpf-mvvm-application
http://www.wpftutorial.net/referencearchitecture.html

**Comment by Slesa** [comment]
The theory was clear, but I did not notice that the binding of the datacontext in Avalonia resolves dependencies automatically. And because Design.DataContext wants a parameterless ctor, I did not consider it would simply work.

**Comment by kekekeks** [comment]
You can use d:DataContext, d:DesignWidth and d:DesignHeight now. `d:DataContext` avoids actual view model creation in runtime since it's value is completely ignored during XML parsing stage

**Comment by kekekeks** [comment]
```cs
static class DesignData
{
     public SomeViewModel SomeModel {get;} = ...
}
```

```xml
<Window xmlns="https://github.com/avaloniaui"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:dd="clr-namespace:Your.Namespace;assembly=YourAssembly"
    mc:Ignorable="d"
    d:DataContext="{x:Static dd:DesignData.SomeModel}"
>
```

**Comment by Slesa** [comment]
So, using AutoFac as DI-Container, this results in:

```
    var builder = new ContainerBuilder();
    var container =builder.Build();
    ...
    var cs = new AutofacServiceLocator(container);
    ServiceLocator.SetLocatorProvider(() =>cs);
```
fills in the registrations and sets the service locator. And

```
    static class ViewModelLocator
    {
        public static T GetDataContext<T>() => ServiceLocator.Current.GetInstance<T>();
    }

    static class WaiterInputViewModelLocator
    {
        public static WaiterInputViewModel ViewModel => ViewModelLocator.GetDataContext<WaiterInputViewModel>();
    }
```
then I can use it in my UserControl:

```
<UserControl
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:t="clr-namespace:pos.frontend.xaml;assembly=pos.frontend.xaml"
    DataContext="{x:Static t:WaiterInputViewModelLocator.ViewModel}"
```

well, it *feels* miles away from Dependency Injection, but on ther other hand - does it harm at this place. I think not.

**Comment by kekekeks** [comment]
Setting non-design mode DataContrxt via static property is a bad practice. 

Usually you want to construct you *tree* of biew models via DI and then use binding to parent control's DataContext to extract a partucular view model fron there

**Comment by Gillibald** [comment]
I use dependency injection in all my projects in conjunction with a bootstrapper. For design time I usually don't need DI and in most cases a mock is enough. This is more a question about MVVM in general.

**Comment by Gillibald** [comment]
What prevents you from constructing childs in a parent ViewModel? You usually start with a MainViewModel and assign that to your windows DataContext. From there you just populate everything.

**Comment by kekekeks** [comment]
This approach is called "state tree". You can initialize child models in a lazy manner if you are concerned about memory/performance implications.

**Comment by Slesa** [comment]
I've once started one Backoffice thing in WPF with Prism, using its modules. It has one Shell, which dynamically loads all Backoffice parts installed, without knowing them. All "Products" are shown as one icon, just like in the "System explorer" of Windows. And each "product" has its categories, which again were decoupled from their parents and so on. I never had something like a state tree of all viewmodels - why would I? I want to decouple and split the parts. Wasn't that the reason I started MVVM?

**Comment by kekekeks** [comment]
MVVM is a separation of view, view model and model itself. There are different approaches for composition of view models, "state tree" is one of them, Prism uses a different one.

If you want an MVVM-framework, you can use ReactiveUI which has integration with Avalonia.
