### ISSUE TITLE
Suggestion: Collection of 3rd party Avalonia controls/libraries?

### ISSUE THREAD

**Issue by TheColonel2688** [AvaloniaUI/Avalonia#2130]
I think it would be nice if there was a collection of 3rd party avalonia controls and libraries. Blazor has one called awesome-blazor.

https://github.com/AdrienTorris/awesome-blazor

I was thinking about this because I'm currently looking for charting controls for Avalonia.

**Comment by wieslawsoltes** [comment]
https://github.com/AvaloniaUI/Avalonia/wiki/3rd-Party-Control-Gallery

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaCommunity/awesome-avalonia
