### ISSUE TITLE
How do I correctly use MonoMac?

### ISSUE THREAD

**Issue by rabejens** [AvaloniaUI/Avalonia#2133]
I started a new Avalonia application on the mac. So far, it works, but the UI looks like a foreign body.

So I installed `Avalonia.MonoMac` into my project and changed:

```csharp
        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                         .UsePlatformDetect()
                         .UseReactiveUI()
                         .LogToDebug();
```

to

```csharp
        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                         .UseMonoMac()
                         .UseReactiveUI()
                         .LogToDebug();
```

But now when I run the program, it crashes at
```csharp
BuildAvaloniaApp().Start<MainWindow>(() => new MainWindowViewModel());
```

with:
```
"Method 'Add' in type 'Avalonia.MonoMac.RenderLoop' from assembly 'Avalonia.MonoMac, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation."
```

What am I missing / doing wrong?

**Comment by rabejens** [comment]
> Monomac is no longer used or supported.

OK, I see.

>  Avalonia is a lookless UI framework so it can be styled and templated to look like anything you want, it doesnt use native controls, similar to frameworks like electron.

That explains the look when using the defaults. It is just for a small tool that is just for me so I can live with it. But is it possible to use the Mac's native menu bar instead having a local one in the window? Electron can use the menu bar.

**Comment by danwalmsley** [comment]
We are going to implement the menubar for the next release, but it isnt yet available.

**Comment by maxkatz6** [comment]
I believe it was answered. And we are not using monomac at all now.
Although it's possible to use MonoMac as third party library with avalonia application.
