### ISSUE TITLE
Using byte array from C SDL to display a frame

### ISSUE THREAD

**Issue by santanor** [AvaloniaUI/Avalonia#2135]
Hello guys,
This is more of a question rather than a proper issue but I've been trying for a while and I can't get my head around this:

_(Bit of background)_
I've got a C .dll that is running an NES emulator, in the past, I used SDL to present the frames but I wanted widgets and whatnot so I moved it to Avalonia. I've got my code so that C builds a frame based on a `byte[]` and sends it to C# to be displayed. That `byte[]` is formed of 3 bytes per pixel (RGB).
 **What I get on the C# side is a struct with a IntrPtr and a size `int` component.** 

_(Now for the problem/question)_
I've created a view with this component in it: 
```<Image Source="{Binding Patterntable}" Width="512" Height="240"></Image>``` 
And I tried to crete a bitmap from `Avalonia.Media.Imaging;` using different constructors. None of them worked. For instance the one that receives an `PixelFormat, IntPtr, Width, Height, Stride` comes back as null when I pass the pointer that I get from C. 
The one that receives a `Stream` which I create by marshalling the `IntPtr` throws an exception saying "Can't create the Bitmap with the given information" 

Should I use a different Bitmap? Maybe one from SharpDX? and how do I hook that one in XAML? I had a look at the samples but I still can't get it to work. 

I would really appreciate help here if you don't mind :)

**Comment by santanor** [comment]
I can, no problem at all. Just add another byte to each pixel. Still, how would that work? Would I be able to use `Avalonia.Media.Imaging.Bitmap` then?

**Comment by kekekeks** [comment]
```cs
    public class MyBitmapControl : Control
    {
        private WriteableBitmap _bitmap =
            new WriteableBitmap(new PixelSize(255, 255), new Vector(96, 96), PixelFormat.Bgra8888);
        
        public override unsafe void Render(DrawingContext context)
        {
            uint color = 0xff000000u;
            using (var l = _bitmap.Lock())
            {
                var ptr = (uint*)l.Address;
                for(var x=0; x<l.Size.Width; x++)
                for (var y = 0; y < l.Size.Height; y++)
                {
                    color++;
                    ptr[y * l.RowBytes / 4 + x] = (uint)color;
                }
            }
            context.DrawImage(_bitmap, 1, new Rect(_bitmap.Size), Bounds, BitmapInterpolationMode.HighQuality);
        }
    }
```

**Comment by santanor** [comment]
Hey! Thanks a lot for the example! 

I assume that would create a `MyBitmapControl` that I can use in my XAML. Would the bindings still work? so instead of having 

```     private Bitmap patterntable;
        public Bitmap Patterntable
        {
            get {return patterntable;}
            set {this.RaiseAndSetIfChanged(ref patterntable, value);}
        }
```
I would now have 

```
        private WriteableBitmap patterntable;
        public WriteableBitmap Patterntable
        {
            get {return patterntable;}
            set {this.RaiseAndSetIfChanged(ref patterntable, value);}
        
}

**Comment by kekekeks** [comment]
The problem with `WriteableBitmap` is that currently you have to call `InvalidateVisual` on the control every time when bitmap gets updated. It's a known issue that we hope to get fixed soon-ish.
That's why I've provided you with the example with a custom control.


It's also better to reuse WriteableBitmap instances, since otherwise GC might kick in too late, so your app will be wasting memory.

You can create a new bitmap each time and dispose old instances, but it has some performance penalty, but you'll be able to reuse existing `Image` control this way.

**Comment by santanor** [comment]
Ahhh I see. Yup no problem at all calling `InvalidateVisual`. Thanks a lot for the example sir, you've been really helpful. Let's see if I can make this work once and for all :) 

Kudos to you!
