### ISSUE TITLE
Clicking on CheckBox content doesn't change it's value

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2148]
```
<CheckBox>
     Some label text
</CheckBox>
```

Clicking on "Some label text" does nothing

**Comment by MonkAlex** [comment]
But this work:
```
<CheckBox IsChecked="{Binding Property}">
        <TextBlock Text="Some label text"/>
</CheckBox>
```

**Comment by kekekeks** [comment]
Not on my machine.
This check returns false: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Button.cs#L259

hittest correctly identifies TextBlock inside CheckBox, but it checks for TemplatedParent, not logical one.

![default](https://user-images.githubusercontent.com/1067584/49233659-7fbf6c00-f407-11e8-8ecc-55b2be927013.png)


@grokys

**Comment by kekekeks** [comment]
Seems to be broken by https://github.com/AvaloniaUI/Avalonia/pull/2001

@donandren

**Comment by donandren** [comment]
we have few options:

- add parent in the check:

**Comment by grokys** [comment]
There's `IsVisualAncestorOf` which might help here? I don't think performance is really an issue as this is only happening when a user clicks.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/VisualTree/VisualExtensions.cs#L228

**Comment by donandren** [comment]
easy repro in control catalog Layout transform page:

change layout transform button like this and button will not fire click:

```XAML
            <LayoutTransformControl Name="layoutTransform" Grid.Column="1" Grid.Row="1">
                <LayoutTransformControl.LayoutTransform>
                    <RotateTransform Angle="{Binding #rotation.Value}"/>
                </LayoutTransformControl.LayoutTransform>
                <Button Background="{x:Null}" BorderThickness="0">
                    <Button.Styles>
                        <Style Selector="Button:pointerover /template/ ContentPresenter">
                            <Setter Property="Background" Value="{x:Null}"/>
                        </Style>
                        <Style Selector="Button:pressed  /template/ ContentPresenter">
                            <Setter Property="Background" Value="{x:Null}"/>
                        </Style>
                    </Button.Styles>
                    <TextBlock Text="Layout Transform" Background="Red" />
                </Button>
            </LayoutTransformControl>
```
