### ISSUE TITLE
:pointerover isn't removed from recycled item on listbox scroll via mouse wheel

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2150]
It's also not updated properly when item is just moved.
![scroll](https://user-images.githubusercontent.com/1067584/49251667-0178bf00-f433-11e8-929b-099073d4a01a.gif)

**Comment by ahopper** [comment]
this is fixed by https://github.com/AvaloniaUI/Avalonia/pull/2067
