### ISSUE TITLE
Binding to ActualWidth

### ISSUE THREAD

**Issue by toytonics** [AvaloniaUI/Avalonia#2153]
Quick question: Is binding to `ActualWidth` supported?

```xaml
  <StackPanel>
    <Grid ColumnDefinitions="300">
      <Button Name="Test" Content="Hello"></Button>
    </Grid>

    <Button Content="World" Width="{Binding #Test.ActualWidth}"></Button>
  </StackPanel>
```

The second button should have a width of 300 now, but it's `NaN` instead. What am I missing out?

**Comment by wieslawsoltes** [comment]
Use Bounds.Width instead.

**Comment by toytonics** [comment]
Thanks, this works for the example above. But how about the following scenario:
```xaml
<StackPanel>
    <Grid ColumnDefinitions="*" Margin="100">
      <local:UC Name="Test"></local:UC>
    </Grid>

    <ItemsControl Items="{Binding Items}" Background="#272727">
      <ItemsControl.ItemTemplate>
        <DataTemplate>
          <Button Content="World" Width="{Binding #Test.Bounds.Width}"></Button>
        </DataTemplate>
      </ItemsControl.ItemTemplate>
    </ItemsControl>
  </StackPanel>
```
Binding to controls inside a `DataTemplate`. Any ideas 😄 ?

**Comment by ahopper** [comment]
I think # inside a template is broken, you could use parent[n] as a work around

**Comment by toytonics** [comment]
You mean like: `{Binding $parent[3].Bounds.Width}`? Because this does not work either.

**Comment by ahopper** [comment]
Yep, that has worked for me, sometimes the number is not obvious.  I noticed that the control you want to bind to is not a parent so it can't work perfectly. I have not tried the wpf  ElementName syntax so that might just work.

**Comment by wieslawsoltes** [comment]
Try `{Binding $parent[StackPanel].Bounds.Width}`.

**Comment by toytonics** [comment]
Unfortunately, neither of this worked for me.

```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:sys="clr-namespace:System;assembly=mscorlib"
        Title="AvaloniaSandbox"
        xmlns:local="clr-namespace:AvaloniaSandbox">
  
  <StackPanel>
    <Grid ColumnDefinitions="*" Margin="100">
      <Button Content="World"></Button>
    </Grid>
    <ItemsControl Items="{Binding Items}" Background="#272727">
      <ItemsControl.ItemTemplate>
        <DataTemplate>
          <Button Content="World" Width="{Binding $parent[StackPanel].Bounds.Width}"></Button>
        </DataTemplate>
      </ItemsControl.ItemTemplate>
    </ItemsControl>
  </StackPanel>
</Window>
```

![image](https://user-images.githubusercontent.com/4670166/49295212-902e2000-f4b5-11e8-83ec-da8e08d06b82.png)

**Comment by toytonics** [comment]
Unfortunately, neither of this worked for me.

```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:sys="clr-namespace:System;assembly=mscorlib"
        Title="AvaloniaSandbox"
        xmlns:local="clr-namespace:AvaloniaSandbox">
  
  <StackPanel>
    <Grid ColumnDefinitions="*" Margin="100">
      <Button Content="World"></Button>
    </Grid>
    <ItemsControl Items="{Binding Items}" Background="#272727">
      <ItemsControl.ItemTemplate>
        <DataTemplate>
          <Button Content="World" Width="{Binding $parent[StackPanel].Bounds.Width}"></Button>
        </DataTemplate>
      </ItemsControl.ItemTemplate>
    </ItemsControl>
  </StackPanel>
</Window>
```

![image](https://user-images.githubusercontent.com/4670166/49295275-b2c03900-f4b5-11e8-83c8-b376e4467919.png)

**Comment by ahopper** [comment]
not sure what would happen if you bound the stackpanel width to the width of the world button.

**Comment by grokys** [comment]
Hi @toytonics,

Not 100% what you're trying to do here... You're binding the `Button` to the ancestor `StackPanel` but the ancestor `StackPanel`'s width is determined by its contents, which are the `Button`s!

Can you not just make the `ItemsControl` be the width that you want? That way the buttons can be made to fill it, and will be the correct size.

**Comment by toytonics** [comment]
I tried to to extract this snippet from a large project and condense it into a minimal example, so it's not so easy to explain. Yes, I could also make the ItemsControl the size I want. However, that doesn't solve the problem that - apparently - binding to controls from within a `DataContext` is not supported/broken. I really need this functionality. Is there any workaround?

**Comment by grokys** [comment]
You mean within a `DataTemplate`? I think this should actually work, I'll take a look.

**Comment by toytonics** [comment]
Ups. Yes, a `DataTemplate`.

**Comment by ahopper** [comment]
I think this is https://github.com/AvaloniaUI/Avalonia/issues/1572

**Comment by toytonics** [comment]
@ahopper yeah, this issue turned into a copy of yours. But yours didn't get much traction :). So I'll leave this open for now.

**Comment by grokys** [comment]
Ah, I didn't notice that one. Ok, I will close this and assign myself to that issue, hope that's ok. Will fix asap.

**Comment by grokys** [comment]
@toytonics I've done some investigation over in #1572. Basically, I don't quite understand how this works in WPF. 

In the meantime, the only thing I can suggest is binding `Bounds.Width` to a property on your `Window` (or whatever) using `Mode=OneWayToSource` and then binding to that from the controls in the `DataTemplate`.

In the meantime I'll try to work out this works in WPF...

**Comment by toytonics** [comment]
@grokys Thanks, I appreciate the effort.
