### ISSUE TITLE
How do I test an Avalonia UI E2E?

### ISSUE THREAD

**Issue by priverop** [AvaloniaUI/Avalonia#2157]
Hi, I want to know how do you usually make e2e tests for Avalonia.

Is there any driver? Can I use Selenium C# or WinAppDriver?

Thanks

**Comment by kekekeks** [comment]
Only in-process tests are available yet. You can access `Application.Windows` and enumerate controls in the visual tree (e. g. `FindControl<T>(name)`). Then you can simulate input events like this: https://github.com/AvaloniaUI/Avalonia/blob/db9678041eb69d6e6ccb6d54dcec11dbd2c504ae/tests/Avalonia.Controls.UnitTests/TextBoxTests.cs#L117

**Comment by lsoft** [comment]
anything new about UI tests automation since 2018?

**Comment by kekekeks** [comment]
There was an effort to get a [headless platform backend](https://github.com/AvaloniaUI/Avalonia/pull/2847) that even allowed to connect via VNC.

No selenium automation, one still has to find windows manually.

**Comment by maxkatz6** [comment]
Headless backend exists for a while now, and recommended to use in e2e testing.
For non-headless scenarios we have automation support now in master branch and nightly builds, see https://github.com/AvaloniaUI/Avalonia/tree/master/tests/Avalonia.IntegrationTests.Appium

**Comment by francisferreira** [comment]
@maxkatz6 Great to know we can actually run e2e tests using WinAppDriver, coz that's exactly what we are attempting on our end!

That said, how can we inspect the controls/elements of an Avalonia app? I tried with inspect.exe (recommended by the WinAppDriver folks), but I can't get anything with that. One can see in the attached screenshot that no elements are listed in the inspect.exe tree-view, only the main app's window.

![avalonia-no-elements](https://user-images.githubusercontent.com/80012455/201810144-3d98d088-d3fd-4805-9511-2083f78ab209.png)

I've checked the integration tests repo you shared in your last comment, but couldn't find any info about that in the readme.md file. I see that your tests look pretty much like ours, so it is a relief to know we are on the right path. However, how can one find the "ButtonWithAcceleratorKey" automation ID or the "AcceleratorKey" attribute name having only the Avalonia app at hand? Which inspector tools I should be using to get those?

```
[PlatformFact(TestPlatforms.Windows)]
public void ButtonWithAcceleratorKey()
{
    var button = _session.FindElementByAccessibilityId("ButtonWithAcceleratorKey");

    Assert.Equal("Ctrl+B", button.GetAttribute("AcceleratorKey"));
}
```

**Comment by maxkatz6** [comment]
@francisferreira hi! Which version of Avalonia are you using? Automation support was added only in 11.0-preview1 and newer.

**Comment by francisferreira** [comment]
@maxkatz6 Hey, thanks for the prompt reply!

Ah, I see. Our usage is bound to stable versions only, so we are using 0.10 at the moment (unfortunately for us)...
Just to be sure tho, if we were using 11.0-preview1+ would we be able to just use inspect.exe to get those elements?

And would there be any alternative we can use for older versions? XPath(ing) our way in the root window using only class names for our controls, perhaps? Or could we set automation/accessibility IDs in code for our Avalonia apps and look for those in our e2e tests? Until the next version is out, any help with this matter is highly appreciated.

**Comment by maxkatz6** [comment]
@francisferreira it works with inspect.exe:
![image](https://user-images.githubusercontent.com/3163374/201817683-a93af297-6be6-4887-beec-332af6b93436.png)

Or same with Accessibility Insights which shows a cleaner tree:
![image](https://user-images.githubusercontent.com/3163374/201818035-811fda18-abee-4b66-be0f-20178e6b1d05.png)


Not every control is mapped to the automation tree IIRC, @grokys might help here better with specific issues.
You can try to build small demo yourself with latest preview and see, if it is good enough for your needs.

**Comment by maxkatz6** [comment]
> And would there be any alternative we can use for older versions? 

Well, automation API won't be backported. Too big a feature for that.

> XPath(ing) our way in the root window using only class names for our controls, perhaps? Or could we set automation/accessibility IDs in code for our Avalonia apps and look for those in our e2e tests? The following is an example for a control we have for a textbox:

Not sure if I understand your specific requirements. But if you want to be able to search for a control from with some XPath-like syntax, you can traverse the visual tree (`control.GetVisualChildren()`) until you find it. Filtering by Name or type or maybe set custom attached properties. But I don't see how it would help integration with third party tools like inspect.exe (I am not sure if it's possible to write some kind of plugins there).

**Comment by francisferreira** [comment]
@maxkatz6 That's awesome, thanks man! Looking forward to the next Avalonia release.

About the workaround for 0.10, we don't care much about integration with inspect.exe (or other tools). I'll try and traverse the element tree with WinAppDriver the way you suggested. If that works and we can manipulate our controls like that, all is well.

Cheers!

**Comment by givanft** [comment]
Is it possible to test Avalonia UI by GTest?

**Comment by ChristoWolf** [comment]
> Is it possible to test Avalonia UI by GTest?

GoogleTest is a general-purpose test framework (i.e. test execution, assertions, etc.) and does not offer UI automation APIs.

**Comment by alexandrehtrb** [comment]
Related:

https://github.com/AvaloniaUI/Avalonia/discussions/12645
