### ISSUE TITLE
StyledProperty Binding with Converter

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#2161]
```xaml
    <seqc:MarkerControl Margin="205 0 0 20" 
                        MarkerOffset="{Binding RelativeMarkerOffset, Converter={StaticResource TrackCoordsConverter}}"/>
```

`MarkerOffset` is declared as: 
```c#
 public static readonly StyledProperty<int> MarkerOffsetProperty
            = AvaloniaProperty.Register<MarkerControl, int>(nameof(MarkerOffset));

        public int MarkerOffset
        {
            get => GetValue(MarkerOffsetProperty);
            set => SetValue(MarkerOffsetProperty, value);
        }
```

Unfortunately, it keeps binding to zero, even if the correct value (515) is displayed in the avalonia debugger. Binding without a Converter and binding to `Width` works just fine. What am I missing out?

**Comment by toytonics** [comment]
Hi, haven't tried your suggestion yet. But I think it's pretty weird that the correct value is displayed in the debugger, but is not used as the final value...

![image](https://user-images.githubusercontent.com/4670166/49745469-4c9a9980-fc9f-11e8-9ab4-1f025524b55e.png)
 
What does the `*` mean here? How do I force it to use the bound value (`61,5`)?

**Comment by grokys** [comment]
Hmm, that is strange. As you say it looks like the binding is producing the correct value, but that's somehow not reflected in the property value. Would you be able to create a minimal repro in a repository or something for me to debug?

**Comment by toytonics** [comment]
https://github.com/toytonics/Avalonia_Bug_StyledProperty

Should reproduce this bug.

**Comment by ahopper** [comment]
@toytonics if you convert to a string in your converter it then works here.
