### ISSUE TITLE
Black Area inside window

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#2166]
Repro: current master, start VirtualizationDemo
Black area around top and left of the window,  actually all hittesting is also completely broken.
![image](https://user-images.githubusercontent.com/13854631/49546964-2e711a00-f8ea-11e8-9f67-5cd7bf8de7f9.png)

After user resize of the window everything start to work as expected

**Comment by donandren** [comment]
this undesired behavior started after merge of #2128 @danwalmsley @kekekeks

**Comment by kekekeks** [comment]
Seems to be "content is larger than viewport" type of issue. Our layout can't handle client size being less than advertized minimum size of the `Window`.

**Comment by donandren** [comment]
@kekekeks VirtualizationDemo was working fine until recently, no black artifacts

**Comment by ahopper** [comment]
another repro is the dev tools window in control catalog, in fact control catalog is the only thing I've tried that does not do it.

**Comment by kekekeks** [comment]
@danwalmsley

**Comment by LordBenjamin** [comment]
Able to reproduce with very minimal code:

```xaml
<Window
  xmlns="https://github.com/avaloniaui"
  Width="320">
</Window>
```

```c#
AppBuilder.Configure<App>()
    .UsePlatformDetect()
    .Start<MainWindow>()
```

It seems that setting the `Width` **or** `Height` properties on the `Window` causes this.

```xaml
<Window
  xmlns="https://github.com/avaloniaui">
</Window>
```

Works correctly.

**Comment by LordBenjamin** [comment]
Working correctly for me using MyGet build `1091`.

**Comment by ahopper** [comment]
@jeffreye can you describe the 'buggy' behaviour? What version of windows are you using?

**Comment by ahopper** [comment]
@jeffreye I think this is related to scaling/dpi as it fails on my surface and not my desktop, I'll fix it.
