### ISSUE TITLE
problem with Avalonia.Native when testing with local nuget on pc

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2168]
To test local builds of Avalonia and prs with apps not in the avalonia solution I simply reference the locally built nuget packages, built with ./build.ps1 --target CreateNugetPackages --skip Clean RunTests.
On a pc the Avalonia.Native package is not built and restore on my project then fails because Avalonia.Desktop can't find it.  As a work around, copying an existing Avalonia.Native package and fixing the internal version number works. Is there a simpler way?

**Comment by kekekeks** [comment]
I think it's currently built by azure-pipelines rather than Nuke script. We might want to call `xcodebuild` manually.

**Comment by maxkatz6** [comment]
It's built now with nuke script, but Xcode is still required to build objective-c project. I don't think we can do in better way while having obj-c project.
