### ISSUE TITLE
Test Mac OS Mojave

### ISSUE THREAD

**Issue by nopara73** [AvaloniaUI/Avalonia#2169]
Someone who has a Mac, can he test the new Mac OS Mojave that came out today? It may be only our software, but there is a possibility that Avalonia as a whole is broken on it, too.

> After updating to latest version of Mac OS Mojave v10.14.2 (18C54), the wallet screen never loads

https://github.com/zkSNACKs/WalletWasabi/issues/935

**Comment by kekekeks** [comment]
Should be fixed by https://github.com/AvaloniaUI/Avalonia/commit/700752c4c26a55c1c68843becbbf62d1129a3d01
