### ISSUE TITLE
Application.current.Exit() freezes on Mac OSX.

### ISSUE THREAD

**Issue by JonathaN7Shepard** [AvaloniaUI/Avalonia#2178]
I have a button that can close the app, it uses Application.Current.Exit(). The app is freezing (spinning colorwheel) when this is called on Mac OSX. The user must then force quit. Is this still the recommended way of quitting an app?

The last time I'm 100% sure it was working was before 0.7.0.

**Comment by grokys** [comment]
@danwalmsley is the still an issue?

**Comment by MikeCodesDotNET** [comment]
It'd now be (with v11) and works as expected. 

```
 if (Application.Current.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
{
    desktop.TryShutdown();
}
```
