### ISSUE TITLE
Button is always grayed out, command can't be executed

### ISSUE THREAD

**Issue by rabejens** [AvaloniaUI/Avalonia#2179]
I extended the basic Hello World example when you create a new `avalonia.mvvm` app. I added a button like this:

```xml
<Button Content="{Binding Greeting}" Command="{Binding MyCommand}" />
```

And in my `MainWindowViewModel` I have:

```csharp
    public class MainWindowViewModel : ReactiveObject {

        public MainWindowViewModel() {
            MyCommand = ReactiveCommand.Create(MyAction);
        }

        private void MyAction() {
            Console.WriteLine("foofoo");
        }

        public string Greeting => "Hello World!";

        public ICommand MyCommand;
    }
```

The binding works (the button's caption is `Hello World!`) but the button itself is grayed out and cannot be clicked.

When I use a menu instead, it is not grayed out but the method is not executed when selecting.

When I try to call `MyCommand.CanExecute(anything)` I receive `true` so the command can execute.

I am using the following dependencies:
```xml
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="0.7.1-build989-beta" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.7.1-build989-beta" />
  </ItemGroup>
```

I am on Mac and outputting as .net Core 2.1.

Is this a bug or am I missing anything?

**Comment by donandren** [comment]
can you try define MyCommand as property
... C#
public ICommand MyCommand { get; }
...

**Comment by rabejens** [comment]
Yeah, I just noticed I forgot `{ get; }`. With this it works. Stupid mistake...
