### ISSUE TITLE
The value for 'DataContext' property is null when opening a window programmatically

### ISSUE THREAD

**Issue by rabejens** [AvaloniaUI/Avalonia#2180]
I am trying to open a window programmatically like this:

```csharp
        private void OpenSettings(Window win) {
            var sw = new SettingsWindow { DataContext = new SettingsViewModel() };
            sw.ShowDialog<bool>(win);
        }
```

However, when I run this, my application crashes with an `XamlObjectWriterException` where the message is `The value for 'DataContext' property is null`.

How do I open a window correctly?

EDIT: I changed this to be async like this:

```csharp
        public MainWindowViewModel() {
            SettingsCommand = ReactiveCommand.Create<Window>(async win => await OpenSettings(win));
        }

        private async Task OpenSettings(Window win) {
            var sw = new SettingsWindow { DataContext = new SettingsViewModel() };
            await sw.ShowDialog<bool>(win);
        }
```

However, this only causes the application to not crash, the window doesn't open. I suppose it throws the exception silently.

**Comment by rabejens** [comment]
Turned out that I had a typo in the `Design.DataContext` in the XAML file.

**Comment by Lemoan-01** [comment]
kys
