### ISSUE TITLE
Text selection in multiline TextBox is freezing the app

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#2181]
repro: start control catalog try make selection in multiline textbox

look like it's caused by recent change: update of skia sharp to 1.68 -> #2173

**Comment by Gillibald** [comment]
This will be obsolete when the new text layout is used. I hope my requested changes to HarfBuzzSharp are implemented soon.

**Comment by donandren** [comment]
look like fixed by recent changes
