### ISSUE TITLE
Loading Bitmap using Relative File Path

### ISSUE THREAD

**Issue by jeffreye** [AvaloniaUI/Avalonia#2183]
Before #2104, it is able to use the relative path for Image 

```<Image Width="16" Height="16" Source="Images/File.png" />```

(mak sure ` Directory.SetCurrentDirectory(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location));` first)

, where File.png is a Content that will copy to output directory. Currently, It throws a error of : 

`System.ArgumentException: Relative uris for 'resm' scheme aren't supported; resm:SampleApp.MainWindow.xaml?assembly=SampleApp uses resm`.

 However, it still is able to load the image with relative path by 

`Bitmap image = new Bitmap("Images/File.png");`

**Comment by Gillibald** [comment]
I don't think supporting this in the way you used it was intended. We need to introduce the file scheme to support loading assets from file. Currently the only way to load assets from file is in code. You could load the image in some viewmodel or in your code behind that should work. 

When you load the file from your application folder why don't you embed that file into your application and load it from resources?

**Comment by jeffreye** [comment]
Considering the assembly has to be loaded into memory before it can be run, I think that's bad. Shipping the resource as a separate standalone file would be a better choice, especially for a large file.

**Comment by kekekeks** [comment]
We might add Host handling for `file:` scheme. So app-relative paths would look like `file://appdir/Images/File.png`. I *think* hostname in `file://` is never used, so it should be fine.

**Comment by nicolasr75** [comment]
We used to bind Image controls to relative paths to files. This was important for us because users wanted to be able to exchange the files with their own ones (logos etc. for "branding" the software). Therefore I strongly vote for supporting files with relative paths again!

**Comment by Gillibald** [comment]
I would suggest using a custom converter for this until this is implemented.

**Comment by nicolasr75** [comment]
Could you provide a short sketch or a link to some resource showing how to do this?

**Comment by Gillibald** [comment]
Just implement IValueConverter that converts a string to Bitmap.

This ctor needs to be called within the converter:
`return new Bitmap(path);`

**Comment by nicolasr75** [comment]
Ok, thanks.

**Comment by Gillibald** [comment]
I would introduce static fields for the image paths and use them in a binding for the corresponding image control.

https://stackoverflow.com/questions/42159000/xaml-converter-for-static-resource

**Comment by nicolasr75** [comment]
Ok, I ended up with a mix of property and static resource binding. As a reference, here is my demo code:

	xmlns:clr="clr-namespace:System;assembly=mscorlib"
	xmlns:local="clr-namespace:MyNamespace"
	...
	<Window.Resources>
		<clr:String x:Key="logoPath">Graphics/StaticLogo.png</clr:String>
		<local:PathToBitmapConverter x:Key="pathToBitmapConverter"/>
	</Window.Resources>
	...
	<Image Source="{Binding Source={StaticResource logoPath}, Converter={StaticResource pathToBitmapConverter}}"></Image>
	<Image Source="{Binding DynamicImage, Converter={StaticResource pathToBitmapConverter}}"></Image>

And the converter class

    public class PathToBitmapConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            string path = (string)value;

            return new Bitmap(path);
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
