### ISSUE TITLE
Failed to build ControlCatalog.NetCore on OS X

### ISSUE THREAD

**Issue by KonH** [AvaloniaUI/Avalonia#2186]
Hello! I tried to build & run a sample from samples/ControlCatalog.NetCore on OS X but failed to build it with error:
```
~/.nuget/packages/sharpgentools.sdk/1.1.2/build/SharpGenTools.Sdk.targets(162,5):
Process error CX0003: Unable to generate XML file with castxml 
[~/Projects/Avalonia/src/Avalonia.Native/obj/Debug/netstandard2.0/SharpGen/SharpGen-MSBuild.xml]. 
Check previous errors.
[~/Projects/Avalonia/src/Avalonia.Native/Avalonia.Native.csproj]
```

Steps to reproduce:
```
git clone https://github.com/AvaloniaUI/Avalonia.git
git submodule update --init
cd samples/ControlCatalog.NetCore
dotnet build
```

Info:
```
git log --pretty=format:'%h' -n 1
1478f0668 
(https://github.com/AvaloniaUI/Avalonia/commit/1478f066829c93f2c5ea6dbb929bfdcd70663405)
```
```
dotnet --version
2.2.101
```
Build log is attached here - https://gist.github.com/KonH/f3611b36916b685e1688a09434fef1e0.
I can run from an app from template (`dotnet new avalonia.app -o ..`.) with Avalonia.Desktop 0.7.0 package, but not from sources.
I will provide additional info if it's required.

**Comment by kekekeks** [comment]
`brew install castxml`. Only needed to build Avalonia itself. Also make sure to build libAvaloniaNative via XCode.
