### ISSUE TITLE
Live previewer

### ISSUE THREAD

**Issue by collectioner** [AvaloniaUI/Avalonia#2187]
Hi,

Does previewer work in live mode? I made some changes in XAML and cannot see changes in previewer. So I need to rebuild project/solution.
It's weird solution, because everytime I change XAML -> I need rebuild whole solution.

Is it only my problem or known one?

VS 2017, net461, netcore2.0

Thanks

**Comment by SLAVONchick** [comment]
@collectioner, I have same issue.

**Comment by kekekeks** [comment]
It should automatically update changes from the file that you are currently previewing. Changes from themes and resource dictionaries require a rebuild.

**Comment by collectioner** [comment]
It should, but it doesn't. I understand about themes/resources, but simple MainWindow.xaml. I edited the text and previewer doesn't "see" it.

**Comment by collectioner** [comment]
Wil you investigate this? Or we should wait for a standalone previewer?
Btw, maybe Blend can work with Avalonia?

**Comment by kekekeks** [comment]
Will investigate.

**Comment by collectioner** [comment]
My current VS version is 15.9.3. I have update for 15.9.4, so if it works fine with this one - I'll update, it isn't a problem.
Otherwise, patiently waiting for your updates, thanks!

**Comment by grokys** [comment]
I've been working on a new VS previewer here: https://github.com/grokys/AvaloniaVS

For the moment it's still WIP (though very nearly finished) so you'll have to build/install yourself for the moment.

We're hoping to release 0.8 very soon and with that this designer will be published to the marketplace.

**Comment by maxkatz6** [comment]
It works now with previewing currently editing control/window, as was mentioned in https://github.com/AvaloniaUI/Avalonia/issues/2187#issuecomment-449263860

If it does not update content, most likely there are some logs in the output window.
