### ISSUE TITLE
TabControl - UserControls inside DataTemplates are not rendered

### ISSUE THREAD

**Issue by braca** [AvaloniaUI/Avalonia#2191]
When using DataTemplates in a TabControl, if the DataTemplate contains a UserControl, the UserControl won't be displayed.

Example
```
<TabControl>
    <TabControl.DataTemplates>
      <DataTemplate DataType="vms:SampleViewModel">
        <StackPanel Orientation="Vertical">
          <TextBlock Text="SampleViewModel.."/>
          <local:SampleView />
        </StackPanel>
      </DataTemplate>
    </TabControl.DataTemplates>
    <TabItem Header="Tab 1 - Content from DataTemplate"><vms:SampleViewModel /></TabItem>
    <TabItem Header="Tab 2" Content="Content for item 2"/>
    <TabItem Header="Tab 3 - View without DataTemplate"><local:SampleView /> </TabItem>
</TabControl>
```
When I select Tab 1, it shows me my DataTemplate but any UserControl (local:SampleView) inside the DataTemplate is not displayed, it only shows the TextBlock
If I select Tab 3, the UserControl (local:SampleView) is shown properly..

**Comment by Gillibald** [comment]
What happens when you replace the StackPanel with a DockPanel? Also try to set a MinHeight on your UserControl. A Grid as the panel should also work.

**Comment by braca** [comment]
It still doesn't work, using a MinHeight has no effect.. :\

**Comment by braca** [comment]
I have created a repro project https://github.com/braca/avalonia-tabcontrol/tree/master/AvaloniaTabControl

This was working properly with the stable version (0.7.0) but now with the latest builds from master, it doesn't work.

**Comment by Gillibald** [comment]
```
<TabControl>
    <TabControl.ContentTemplate>
      <DataTemplate DataType="vms:SampleViewModel">
        <StackPanel Orientation="Vertical">
          <TextBlock Text="SampleViewModel.."/>
          <local:SampleView />
        </StackPanel>
      </DataTemplate>
    </TabControl.DataTemplates>
    <TabItem Header="Tab 1 - Content from DataTemplate"><vms:SampleViewModel /></TabItem>
    <TabItem Header="Tab 2" Content="Content for item 2"/>
    <TabItem Header="Tab 3 - View without DataTemplate"><local:SampleView /> </TabItem>
</TabControl>
```

**Comment by braca** [comment]
@ahopper wrapping the view model in a ContentControl works
@Gillibald It didn't work

**Comment by ksigne** [comment]
@braca In `ContentPresenter.cs:249` replace 
`if (newChild.Parent == null && TemplatedParent == null)`
to
`if (newChild.Parent == null)`
It will help though side effects are not clear yet.

**Comment by Gillibald** [comment]
Didn't know I had to do that so a mistake on my side. Probably should look at the code of the ContentControlMixin to understand what it is doing.

**Comment by braca** [comment]
Cool, I'm glad the root cause was found :) 
Thank you guys

**Comment by grokys** [comment]
@Gillibald yeah it's really not obvious. I think there might be a better way...

Fixed by https://github.com/AvaloniaUI/Avalonia/pull/2218 btw.
