### ISSUE TITLE
Avalonia Xaml as xml fails

### ISSUE THREAD

**Issue by rogalmic** [AvaloniaUI/Avalonia#2195]
I am trying to make VSCode usage easier by creating some kind of [XML editor extension](https://github.com/rogalmic/vscode-xml-complete) that would not require java.

One idea was to embed XSD location in Avalonia Xaml, therefore generic XML parser should show xml tag/attribute hints.

When I add some `schemaLocation` to root element i get:
```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://raw.githubusercontent.com/rogalmic/vscode-xml-complete/master/test/Avalonia/AvaloniaXamlSchema.xsd"
```

```
An exception of type 'Portable.Xaml.XamlObjectWriterException' occurred in Avalonia.Markup.Xaml.dll but was not handled in user code: 'Cannot set unknown member '{http://www.w3.org/2001/XMLSchema-instance}schemaLocation''
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteStartMember(XamlMember property)
   at Portable.Xaml.XamlWriterInternalBase.WriteStartMember(XamlMember property)
   at Portable.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
```
from:
https://github.com/AvaloniaUI/Portable.Xaml/blob/99d2b0e1bc40a4804d374e7fd76c71413c9db69c/src/Portable.Xaml/Portable.Xaml/XamlObjectWriter.cs#L456

There is some `FIXME` mention there for this condition, so is there a chance that this will be allowed in Avalonia?

**Comment by kekekeks** [comment]
xsi:schemaLocation is indeed invalid XAML directive. It should be possible to extend our xaml context to support it, but I see no value in doing that. 
We've tried to express our XAML via XML schema and failed miserably. That resulted in our current VS extension.
It would be better to continue somewhat abandoned work on the language server for VSCode. If you wish  for proper XAML autocomplete with previewer in VSCode, see https://github.com/kekekeks/Avalonia.Ide/tree/master/src/Avalonia.Ide.LanguageServer and https://github.com/kekekeks/Avalonia.Ide/blob/master/vscode-extension/src/extension.ts

The current code can extract solution/project information and even run XAML preview in browser window if started in standalone (`--web`) mode. LSP protocol isn't implemented, but it should be easy to do using the extracted solution/project info and our CompletionEngine class from the same repo.

**Comment by rogalmic** [comment]
Thanks for this detailed answer. I will take a look at the VSCode extension in `Avalonia.Ide`, maybe I can help...

**Comment by rogalmic** [comment]
I added some changes to vscode extension, so it can be built to vsix automatically.
https://github.com/kekekeks/Avalonia.Ide/pull/17

Sample output:
https://github.com/rogalmic/Avalonia.Ide/releases

Again, thanks for this answer. If I find some time, I will help more...
