### ISSUE TITLE
ShowDialog() ignores WindowStartupLocation

### ISSUE THREAD

**Issue by braca** [AvaloniaUI/Avalonia#2207]
Using the latest code from master, setting a window `WindowStartupLocation` property has no effect when using `ShowDialog(..)`. If I use `Show()` it works properly

I've tried both `WindowStartupLocation.CenterScreen` and `WindowStartupLocation.CenterOwner `

**Example**
```
var window = new Window();
window.Height = 100;
window.Width = 100;
window.Content = new TextBlock { Foreground = Brushes.White, Text = "Test" };
window.WindowStartupLocation = WindowStartupLocation.CenterScreen;
window.ShowDialog(Application.Current.MainWindow);
```
**Expected behaviour**
Window should be displayed in the desired location

**Comment by Gillibald** [comment]
It seems the call to https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Window.cs#L463 is missing in the ShowDialog implementation.

**Comment by x2bool** [comment]
WindowStartupLocation.CenterOwner is probably still broken on MacOS, but works as it should on Windows.

Right now showing a dialog on Mac centers dialog to the right of the parent window.

**Comment by mat1jaczyyy** [comment]
CenterOwner works fine on macOS in my app.
