### ISSUE TITLE
Binding image source to file path

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#2208]
The image control doesn't show the image. How can I bind it to a file path?
```
<Image Source="{Binding Image}" />
public string Image { get; set; } // => /home/karl/Desktop/imagetest.jpeg
```

**Comment by jp2masa** [comment]
I think you have to use a custom converter like this one: https://github.com/VitalElement/AvalonStudio.Shell/blob/master/src/AvalonStudio.Shell.Extensibility/Converters/BitmapValueConverter.cs.

Related: #853.

**Comment by Symbai** [comment]
Thanks, that worked!
