### ISSUE TITLE
VS 2019 integration

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#2212]
Is there a way to install the extension in VS 2019?

**Comment by MartenF** [comment]
That seams more like a [AvaloniaVS](https://github.com/AvaloniaUI/AvaloniaVS) question, but I dont know how active that extension still is developed (it is still using 0.6) or if the focus is on Avalon studio.

**Comment by Symbai** [comment]
Yes sorry I haven't seen this repo before creating this issue. It still seems to be actively developed but like Avalonia release builds are only published once a year and unlike Avalonia, the VS addon has no daily / nightly releases to download.

**Comment by grokys** [comment]
@Symbai - yes we need to release a new version of the VS extension, but something seems to be broken with the previewer on current master, and we've not really got a maintainer for it :(

I realise this isn't really acceptable, and I'll try to spend some time getting the extension working in the near future if possible.
