### ISSUE TITLE
Listbox Item Groups

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#2214]
I've noticed the listbox does not have a groupstyle member. Is there any way to group a list in Avalonia?

**Comment by ahopper** [comment]
the DataGrid allows this https://github.com/AvaloniaUI/DataGrid 
https://github.com/AvaloniaUI/Avalonia/pull/2109

**Comment by Symbai** [comment]
DataGrid is an overkill for my purpose but I'll check it out, thanks for pointing
