### ISSUE TITLE
Nightly builds on Myget are outdated

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#2215]
Using link on wiki: https://www.myget.org/F/avalonia-ci/api/v2 says latest version is 0.7.1build989, published (12/10/2018)
Using link on wiki for PR feeds: https://www.myget.org/F/avalonia-prs/api/v3/index.json says latest version is 0.7.1-build997-beta, published (12/11/2018)

However when browsing the azure page https://dev.azure.com/AvaloniaUI/AvaloniaUI/_release?view=mine&definitionId=2 I see the latest builds are published on 01/03/2019 including artifacts which contains the actual latest nuget package so there seems to be an issue with MyGet stopped somewhere in December?

**Comment by ahopper** [comment]
I noticed this in the vs nuget explorer, it appears to be a simple sorting issue on version number with the 1000+ numbers at the bottom of the list

**Comment by Symbai** [comment]
Thank you so much. Was already trying to integrate the artifacts somehow as nuget manager also didn't notified about an update.

**Comment by ahopper** [comment]
I'd leave this open as it needs fixing and you and I won't be the only ones.
