### ISSUE TITLE
MyGet nightly feed out of order

### ISSUE THREAD

**Issue by LordBenjamin** [AvaloniaUI/Avalonia#2217]
See #2215.

The MyGet feed seems to be ordering alphabetically rather than numerically, which means that Nuget considers `0.7.1-build989-beta` to be newer than `0.7.1-build1091-beta`.

This means that Nuget won't automatically update packages to the latest version, as it actually considers this a downgrade. After installing `1091`, it now offers me an "update" to `989`.

![image](https://user-images.githubusercontent.com/13396705/50726658-2d5d2380-1108-11e9-8ca9-3f55f15eccc3.png)

**Comment by grokys** [comment]
Hmm, yeah that sucks. I'm not sure what to do about this... @jkoritzinsky @kekekeks @wieslawsoltes @danwalmsley any ideas?

**Comment by jkoritzinsky** [comment]
I experienced this issue on SharpGenTools as well. Here's the options I can think of:

- Update our version to something greater than 0.7.1. Our next version will likely not be 0.7.1 so we could change it to 0.7.2 or 0.8.0 and we'd be fine (at least until build 10000).
- Remove all -buildXXX where XXX < 1000 builds from MyGet
- Change our build numbering scheme (probably combined with the first option).
   - We could go to an "always-releasable" scheme where our generated build numbers don't use prerelease tags. We could even embed the git commit ID into the version using the Semver 2 with the `0.8.X+SHA` syntax.
   - Use the Semver2 `-build.XXX.beta` syntax where XXX is the build number. Those are correctly compared as integers by NuGet. (See https://github.com/NuGet/Home/wiki/SemVer-2.0.0-support)

**Comment by kekekeks** [comment]
`0.7.2-nightly-001091` would fit nicely for now, I suppose. That won't force people to update to semver-capable nuget client.

**Comment by jkoritzinsky** [comment]
@kekekeks are there any NuGet clients that aren’t semver2 compatible that also support packages targeting netstandard2.0 in their current versions?

The NuGet version that added netstandard2.0 support also added semver2 support. And Paket has had support for 8 months.

**Comment by kekekeks** [comment]
Fixed by https://github.com/AvaloniaUI/Avalonia/pull/2269/files since it seems to have the lowest impact.
