### ISSUE TITLE
Image.Clip when EllipseGeometry applied renders without anti-aliasing

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#2220]
The following code produces circular image with visible pixelated edges, anti-aliasing is not applied:

```xml
<Image
    Source="{Binding Avatar}"
    Width="32"
    Height="32">

    <Image.Clip>
        <EllipseGeometry Rect="0,0,32,32" />
    </Image.Clip>

</Image>
```

**Comment by Gillibald** [comment]
Is your image scaled down? Anti-aliasing is enabled by default but bitmap interpolation is low quality by default. Pls try to set BitmaoInterpolationMode="HighQuality" on your control just to make sure.

**Comment by x2bool** [comment]
@Gillibald sorry I am not sure where am I supposed to put the BitmapInterpolationMode property? Image does not seem to have it.

**Comment by Gillibald** [comment]
Ohh sry didn't mention it is an attached property.

```
<Image
    Source="{Binding Avatar}"
    Width="32"
    Height="32"
    RenderOptions.BitmapInterpolationMode="HighQuality">
    <Image.Clip>
        <EllipseGeometry Rect="0,0,32,32" />
    </Image.Clip>
</Image>
```

**Comment by x2bool** [comment]
Does not change anything for me :(
(Avalonia v0.7.1-build1091-beta)

Original image:

![255434285_122305](https://user-images.githubusercontent.com/892945/50735383-44128180-11bf-11e9-8961-f59dc773ea6f.jpg)

This is how it gets rendered with Skia on Mac (Retina):

![image](https://user-images.githubusercontent.com/892945/50735412-b4b99e00-11bf-11e9-8a6f-2797040a776f.png)

Windows + Direct2D1:

![screenshot_1](https://user-images.githubusercontent.com/892945/50735453-6789fc00-11c0-11e9-96a3-b5715b19365e.png)

Windows + Skia:

![screenshot_2](https://user-images.githubusercontent.com/892945/50735474-b899f000-11c0-11e9-9294-b582fdaf9c28.png)
