### ISSUE TITLE
Get All System Fonts

### ISSUE THREAD

**Issue by jeffreye** [AvaloniaUI/Avalonia#2222]
Is there an API that could get all available fonts in the system?  

The similar API in System.Drawing is:
https://docs.microsoft.com/en-us/dotnet/api/system.drawing.text.installedfontcollection?view=netframework-4.7.2

**Comment by Gillibald** [comment]
This is currently not supported but will hopefully come in the future.

**Comment by jeffreye** [comment]
Close via #2227
