### ISSUE TITLE
Memory Leak using OxyPlot --> Canvas?

### ISSUE THREAD

**Issue by olfk** [AvaloniaUI/Avalonia#2224]
I observe strange behavior when trying to use OxyPlot. There seems to be a memory leak.

- Build https://github.com/AvaloniaUI/oxyplot-avalonia 
- Run AvaloniaExamples, select 1st item AlignedAxesDemo
- Resize the window several times
- Watch memory consumption

**The example is built against Avalonia 0.6.1. It works fine**. Memory usage goes up initially and then stays constant.

Now try to **convert it to Avalonia 0.7.0**. PixelWidth / PixelHeight has to be replaced by PixelSize struct in order to build. I did this on my fork.

- Build https://github.com/olfk/oxyplot-avalonia (or update nuget packages to 0.7.0 and do small fixes to compile)
- Run AvaloniaExamples, select 1st item AlignedAxesDemo
- Resize the window several times
- Watch memory consumption

With **Avalonia 0.7.0** Memory usage **increases with every redraw of the window**.

I know that might be caused by OxyPlot. But the code is 99% identical (just the Bitmap PixelSize thing that changed), and does not have a memory leak with 0.6.1.

See also  #2198 
Can this be related to Canvas oder Rendering in general?

**Comment by maxkatz6** [comment]
Oxyplot is maintained in this repository https://github.com/oxyplot/oxyplot-avalonia
