### ISSUE TITLE
Create custom Window Style

### ISSUE THREAD

**Issue by JanTamis** [AvaloniaUI/Avalonia#2226]
How does one create a custom window Style?

like this:
![image](https://user-images.githubusercontent.com/24406714/50824481-00428800-1337-11e9-89bc-ddc57f7178d2.png)

**Comment by danwalmsley** [comment]
https://github.com/VitalElement/AvalonStudio.Shell/blob/master/src/AvalonStudio.Shell/Controls/MetroWindow.cs

https://github.com/VitalElement/AvalonStudio.Shell/blob/master/src/AvalonStudio.Shell/Controls/MetroWindow.paml

**Comment by danwalmsley** [comment]
yes, you can see here it hides the client decorations on macosx, but if you don't want that then you can modify the code.

https://github.com/VitalElement/AvalonStudio.Shell/blob/master/src/AvalonStudio.Shell/Controls/MetroWindow.cs#L84

**Comment by JanTamis** [comment]
thank you so much for your help, much appreciated!

**Comment by geroddokar** [comment]
Hey. I am new to avalonia. You can show a simple example of how to style a window; I need to change the control buttons and the window header. The design should be the same for macos and windows.
this is an example from wpf that i am aiming for
`    <Style TargetType="local:XGWindow" x:Key="XGWindowStyle">
        <Setter Property="FontSize" Value="20" />
        <Setter Property="Foreground" Value="White"></Setter>
        <Setter Property="Background" Value="White"/>
        <Setter Property="BorderBrush" Value="Black"/>
        <Setter Property="MinHeight" Value="320"/>
        <Setter Property="MinWidth" Value="480"/>
        <Setter Property="RenderOptions.BitmapScalingMode" Value="HighQuality"/>
        <Setter Property="Title" Value="{Binding Title}"/>
        <Setter Property="WindowChrome.WindowChrome">
            <Setter.Value>
                <WindowChrome GlassFrameThickness="1" 
                              ResizeBorderThickness="4"
                              CaptionHeight="0"/>
            </Setter.Value>
        </Setter>
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="{x:Type local:XGWindow}">

                    <Grid Background="Transparent" x:Name="WindowRoot">

                        <Grid x:Name="LayoutRoot"
                              Background="{TemplateBinding Background}">
                            <Grid.RowDefinitions>
                                <RowDefinition Height="36"/>
                                <RowDefinition Height="*"/>
                            </Grid.RowDefinitions>

                            
                            <Grid x:Name="PART_HeaderBar" Background="Black">
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="Auto"/>
                                    <ColumnDefinition Width="*"/>
                                    <ColumnDefinition Width="Auto"/>
                                </Grid.ColumnDefinitions>
                                <Image Source="{StaticResource MyImageSource}" Margin="10,5,0,5"></Image>

                                <TextBlock Text="{TemplateBinding Title}" 
                                           Grid.Column="0"
                                           Grid.ColumnSpan="3"
                                           TextTrimming="CharacterEllipsis"
                                           HorizontalAlignment="Stretch" 
                                           FontSize="13"
                                           TextAlignment="Center"
                                           VerticalAlignment="Center"
                                           Width="Auto"
                                           Padding="200 0 200 0"
                                           Foreground="Black"
                                           Panel.ZIndex="0"
                                           IsEnabled="{TemplateBinding IsActive}"/>

                                <Grid x:Name="WindowControlsGrid" Grid.Column="2" Background="Black">
                                    <Grid.ColumnDefinitions>
                                        <ColumnDefinition Width="36"/>
                                        <ColumnDefinition Width="36"/>
                                        <ColumnDefinition Width="36"/>
                                    </Grid.ColumnDefinitions>
                                    <Button x:Name="MinimizeButton" Style="{StaticResource WindowButtonStyle}" Grid.Column="0">
                                        <Grid Width="30" Height="25">
                                            <Path Data="M9,0 L8,1 8,1 8,1 0,1 0,1 z" Width="9" Height="9" VerticalAlignment="Bottom" HorizontalAlignment="Center"
              Stroke="{Binding Foreground, RelativeSource={RelativeSource AncestorType={x:Type Button}, Mode=FindAncestor}}" StrokeThickness="2" />
                                        </Grid>
                                    </Button>

                                    <Button x:Name="RestoreButton"  Grid.Column="1"  Visibility="Collapsed" Style="{StaticResource WindowButtonStyle}">
                                        <Grid Width="30" Height="25" UseLayoutRounding="True" RenderTransform="1,0,0,1,.5,.5">
                                            <Path Data="M2,0 L8,0 L8,6 M0,3 L6,3 M0,2 L6,2 L6,8 L0,8 Z" Width="8" Height="8" VerticalAlignment="Center" HorizontalAlignment="Center"
                Stroke="{Binding Foreground, RelativeSource={RelativeSource AncestorType={x:Type Button}, Mode=FindAncestor}}" StrokeThickness="1"  />
                                        </Grid>
                                    </Button>
                                    <Button x:Name="MaximizeButton"  Grid.Column="1"  Style="{StaticResource WindowButtonStyle}">
                                        <Grid Width="31" Height="25">
                                            <Path Data="M0,1 L9,1 L9,8 L0,8 Z" Width="9" Height="8" VerticalAlignment="Center" HorizontalAlignment="Center"
                Stroke="{Binding Foreground, RelativeSource={RelativeSource AncestorType={x:Type Button}, Mode=FindAncestor}}" StrokeThickness="2"  />
                                        </Grid>
                                    </Button>

                                    <Button x:Name="CloseButton" Style="{StaticResource WindowButtonStyle}"    Grid.Column="2" >
                                        <Grid Width="30" Height="25">
                                            <Path x:Name="Cross" Data="M0,0 L1,1 M0,1 L1,0" Stretch="Fill" Width="8" Height="8"
              Stroke="{Binding Foreground, RelativeSource={RelativeSource AncestorType={x:Type Button}, Mode=FindAncestor}}" StrokeThickness="2" />
                                        </Grid>
                                    </Button>
                                </Grid>
                            </Grid>

                            <Grid x:Name="PART_MainContentGrid"
                                  Grid.Row="1"
                                  Panel.ZIndex="10">
                                <Grid.Background>
                                    <ImageBrush ImageSource="/Icons/bg.jpg" Stretch="UniformToFill"/>
                                </Grid.Background>
                                <ContentPresenter x:Name="PART_MainContentPresenter" Grid.Row="1"/>
                            </Grid>
                        </Grid>
                    </Grid>

                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>`

**Comment by pebble76** [comment]
<Grid Background="Transparent" x:Name="WindowRoot">

                    <Grid x:Name="LayoutRoot"
                          Background="{TemplateBinding Background}">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="36"/>
                            <RowDefinition Height="*"/>
                        </Grid.RowDefinitions>

                        
                        <Grid x:Name="PART_HeaderBar" Background="Black">
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="Auto"/>
                                <ColumnDefinition Width="*"/>
                                <ColumnDefinition Width="Auto"/>
                            </Grid.ColumnDefinitions>
                            <Image Source="{StaticResource MyImageSource}" Margin="10,5,0,5"></Image>

                            <TextBlock Text="{TemplateBinding Title}" 
                                       Grid.Column="0"
                                       Grid.ColumnSpan="3"
                                       TextTrimming="CharacterEllipsis"
                                       HorizontalAlignment="Stretch" 
                                       FontSize="13"
                                       TextAlignment="Center"
                                       VerticalAlignment="Center"
                                       Width="Auto"
                                       Padding="200 0 200 0"
                                       Foreground="Black"
                                       Panel.ZIndex="0"
                                       IsEnabled="{TemplateBinding IsActive}"/>

                            <Grid x:Name="WindowControlsGrid" Grid.Column="2" Background="Black">
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="36"/>
                                    <ColumnDefinition Width="36"/>
                                    <ColumnDefinition Width="36"/>
                                </Grid.ColumnDefinitions>
                                <Button x:Name="MinimizeButton" Style="{StaticResource WindowButtonStyle}" Grid.Column="0">
                                    <Grid Width="30" Height="25">
                                        <Path Data="M9,0 L8,1 8,1 8,1 0,1 0,1 z" Width="9" Height="9" VerticalAlignment="Bottom" HorizontalAlignment="Center"
          Stroke="{Binding Foreground, RelativeSource={RelativeSource AncestorType={x:Type Button}, Mode=FindAncestor}}" StrokeThickness="2" />
                                    </Grid>
                                </Button>

                                <Button x:Name="RestoreButton"  Grid.Column="1"  Visibility="Collapsed" Style="{StaticResource WindowButtonStyle}">
                                    <Grid Width="30" Height="25" UseLayoutRounding="True" RenderTransform="1,0,0,1,.5,.5">
                                        <Path Data="M2,0 L8,0 L8,6 M0,3 L6,3 M0,2 L6,2 L6,8 L0,8 Z" Width="8" Height="8" VerticalAlignment="Center" HorizontalAlignment="Center"
            Stroke="{Binding Foreground, RelativeSource={RelativeSource AncestorType={x:Type Button}, Mode=FindAncestor}}" StrokeThickness="1"  />
                                    </Grid>
                                </Button>
                                <Button x:Name="MaximizeButton"  Grid.Column="1"  Style="{StaticResource WindowButtonStyle}">
                                    <Grid Width="31" Height="25">
                                        <Path Data="M0,1 L9,1 L9,8 L0,8 Z" Width="9" Height="8" VerticalAlignment="Center" HorizontalAlignment="Center"
            Stroke="{Binding Foreground, RelativeSource={RelativeSource AncestorType={x:Type Button}, Mode=FindAncestor}}" StrokeThickness="2"  />
                                    </Grid>
                                </Button>

                                <Button x:Name="CloseButton" Style="{StaticResource WindowButtonStyle}"    Grid.Column="2" >
                                    <Grid Width="30" Height="25">
                                        <Path x:Name="Cross" Data="M0,0 L1,1 M0,1 L1,0" Stretch="Fill" Width="8" Height="8"
          Stroke="{Binding Foreground, RelativeSource={RelativeSource AncestorType={x:Type Button}, Mode=FindAncestor}}" StrokeThickness="2" />
                                    </Grid>
                                </Button>
                            </Grid>
                        </Grid>

                        <Grid x:Name="PART_MainContentGrid"
                              Grid.Row="1"
                              Panel.ZIndex="10">
                            <Grid.Background>
                                <ImageBrush ImageSource="/Icons/bg.jpg" Stretch="UniformToFill"/>
                            </Grid.Background>
                            <ContentPresenter x:Name="PART_MainContentPresenter" Grid.Row="1"/>
                        </Grid>
                    </Grid>
                </Grid>

            </ControlTemplate>
        </Setter.Value>
    </Setter>
</Style>`

**Comment by liwuqingxin** [comment]
Just set `ExtendClientAreaToDecorationsHint="True"`. Then you can render everything you like! The window keep all system behaviors, including resize animation.

![image](https://user-images.githubusercontent.com/20198528/208422373-106709eb-f790-42a7-bbc5-cf949ca49674.png)
