### ISSUE TITLE
Using Avalonia in OWIN or Nancy Self Hosted service application with web page display

### ISSUE THREAD

**Issue by diwakarpp** [AvaloniaUI/Avalonia#2236]
Hi, I am trying to integrate Avalonia to our existing [OWIN Self Hosted service](http://owin.org/) (windows + linux) application with web pages display. I am stuck as I am not sure if there are any middleware modules that can work with [OWIN](http://owin.org/). Alternatively [Nancy Self Hosted](http://nancyfx.org/) module too should be fine. Can you pl point me for the references to integrate Avalonia with [OWIN](url) or [Nancy](url)?

**Comment by Gillibald** [comment]
Avalonia is just a UI framework like wpf or uwp. There is no build in control that magicly works with some complex web services. Just with any other technology I would implement some layered application that can talk to your service and is able to transform your data into models that your UI understands.

**Comment by diwakarpp** [comment]
Hi, Sorry for the confusion. I meant about the UI display rendition and not about the web services functionality. In other words to use Analonia in an asp.net and IIS environment, what configs do I need to specify in web.config? If anyone points me to the reference, I can use the same for the OWIN/Nancy and make it to display the wpf files under OWIN/Nancy environment. Thanks.

**Comment by diwakarpp** [comment]
Just add, if Avalonia does not work in the browsers but just a wpf based "standalone application" development framework then obviously its not possible to use with IIS or OWIN or Nancy. Pl advise me if it does not support the browser based applications development (and just a stand alone one). Thanks.

**Comment by diwakarpp** [comment]
Just to add, if Avalonia does not produce a browser based display but just a wpf based "standalone application" development framework then obviously its not possible to use with IIS or OWIN or Nancy. Pl advise me if it does not support the browser based applications development (and just a stand alone one). Thanks.

**Comment by Gillibald** [comment]
Not sure if that is what you want:
http://galratner.com/blogs/net/archive/2014/01/31/creating-hybrid-html5-and-wpf-applications-with-self-hosted-owin-web-api-signalr-and-awesomium.aspx
We currently have don't have a WebView control but you can use this:
https://github.com/VitalElement/CefGlue.Core

Still, don't know what benefit you would get from a build in browser view instead of just using a major browser application.

**Comment by diwakarpp** [comment]
@Gillibald thank you for the references. The first [link](http://galratner.com/blogs/net/archive/2014/01/31/creating-hybrid-html5-and-wpf-applications-with-self-hosted-owin-web-api-signalr-and-awesomium.aspx) is helpful and partly solves my question.

Basically what we are developing is a windows service that sits on the web servers and monitors for the hack/crack attempts and other attacks on the server and prevents them. However, the sys admin person wants to access and control the windows stand alone service (listening on port) remotely through a web page part of the same service. Through an admin web page, the sys admin would view the log reports and other stuff remotely through their local browsers.  They would not need to install any bloated desktop or mobile applications to view it. Infact we were already partly done with the development using the OWIN Self Hosted service based on Wisej but because of their expensive licensing model, we would not want to use Wisej ahead and instead we prefer to use ASP.Net MVC/WebForms or Avalonia or React JS or Fyde which can sit along side of the OWIN or Nancy Self Hosted Windows Service and expose the html page display for our remote access page implementation. Hope this makes it clear about our requirement. Anyway, thanks for your help with the references.

**Comment by FreezeSoul** [comment]
mark
