### ISSUE TITLE
Xaml alias Tag

### ISSUE THREAD

**Issue by drearyrainDeng** [AvaloniaUI/Avalonia#2238]
anyone tried to use html5 tags as  avalonia  xaml tag alias? or directly support html as avalonia UI  layout file?

**Comment by grokys** [comment]
Hi @drearyrainDeng - could you give some more background on what you're asking?

**Comment by drearyrainDeng** [comment]
for now ,almost programers know "html"  not xaml,  so  i just think  whether we can use it to replace xaml as  avalonia layout file (MainWindow.xaml => MainWindow.html), because some tag is same like "Button".   but now ,i dont think it is good  idea!   on the contrary,it is better to develop avalonia as a cross-platform  xaml  frame.
