### ISSUE TITLE
Add IsChecked property support for MenuItem

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#224]

**Comment by mikel785** [comment]
Hello:

Btw it would be nice to implement mechanism allowing RadioButton, ToggleButton, MenuItem and etc. to act like a part of radio group. 

Initially do that:

class CheckedEventArgs {
  ...
}

interface ICheckable {
   bool IsCheckable { get; set; }
   bool IsChecked  { get; set; }
   event EventHangler CheckdChanged;
}

and finally create check/uncheck tracker something like
class RadioGroup {
   public ICheckable CheckedItem {get;set;}
   public ICollection<ICheckable> Item {get;}
   ...
}

Grokys, assign me there please.

**Comment by grokys** [comment]
@mikel785 : not sure what you mean here. In Perspex there is no radio group control currently, a radio group is implicit among radio buttons that have the same parent.

**Comment by mikel785** [comment]
Ok. 
I meant that:
1. We have some controls which support Checkable state(RadioButton, MenuItem, ToggleButton and etc.)
2. It would be good to create ICheckable interface and make mentioned above inherited from that interface.
3. And then Implement some kind of "just-one-control-is-checked-at-one-time" tracker which will work with ICheckable items to unify behaviour between different controls.

So it will be usefull in radio-group like behaviour to use just one code for different controls.

**Comment by grokys** [comment]
Ok, yes I agree that `ICheckable` would be a good interface to have.

As for tracking "one control checked at a time", WPF and HTML use a simple group name property to specify the group, however I feel we would also want to be able to scope these group names somehow.

**Comment by jgcodes2020** [comment]
Is this worth doing for a PR (at least after Avalonia 11 releases)?

**Comment by maxkatz6** [comment]
@jgcodes2020 instead of IsChecked property, UWP-like API should be ported with MenuItem, ToggleMenuItem, RadioMenuItem.
But not in 11.0 release, possibly in 11.1, yes.
