### ISSUE TITLE
ICollectionView - Group, Sort, etc.

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#2243]
It would be nice to have support for ICollectionView adding grouping, sorting etc.

**Comment by kekekeks** [comment]
https://github.com/RolandPheasant/DynamicData

**Comment by grokys** [comment]
@Symbai to give a bit more context to @kekekeks' answer: yes I'd recommend using `DynamicData` for this (at least for now). `ICollectionView` is a bottomless well of bugginess and strange behavior (it's what made me give up on the [original Avalonia](https://github.com/grokys/Avalonia)) and I don't really want to port that stuff to Avalonia :/

Having said that, I appreciate that we don't really have a great story for grouping at the moment in Avalonia and it's something that `DynamicData` won't solve by itself. I'd like to think/talk about grouping some more at some point in the near future and see what we want to do there.

We also need some documentation on best practises for doing this stuff with `DynamicData`.

**Comment by Symbai** [comment]
Is there any example how to use DynamicData as ICollectionView replacement? There are lots of examples on the repo but it's not clear to me how to use it on an ObservableCollection. Plus it looks like sorting creates a new collection all the time. I searched for a simple tutorial on how to use it on WPF but I couldn't find any.

Maybe Avalonia can provide a wrapper making it easier for people switching to it which uses then dynamicdata behind the scenes?

**Comment by Symbai** [comment]
My previous comment wasn't that great, I apologize. I would like to change the request into providing grouping at least in various controls such as Listbox natively. Even when group / sort using dynamicdata there could still be some visual feedback to the end user and I dont see any way to achieve this myself at this moment.

**Comment by grokys** [comment]
Hey @Symbai - no problem, your question is totally valid. We don't have any documentation for any of this, and not really any examples either. I think the closest you can find at the moment is https://github.com/RolandPheasant/DynamicData/wiki/Introduction-for-ReactiveUI-users and https://reactiveui.net/docs/handbook/collections/.

As I said, we don't really have a good story for grouping yet - it's definitely something we need to work on.

**Comment by Symbai** [comment]
Thanks for the links. I've been able to group and sort and filter using DynamicData now. For sort I just added two buttons and for filter a textbox. But I have no idea how to add group headers to the Listbox. In WPF the listbox has a group header style but on Avalonia it's missing. Is there a workaround for it?

**Comment by grokys** [comment]
> As I said, we don't really have a good story for grouping yet - it's definitely something we need to work on.

☝️ this pretty much. We don't have grouping yet in our controls. I think the closest you will be able to come is to display something like a `ListBox` of `ItemsControls` with a header. Unfortunately you'll lose virtualisation support.

Another option might be to present a flat list of view models, where each view model is either and `ItemViewModel` or a `HeaderViewModel`. You'd then use `DataTemplates` to display the correctly styled item. However currently it wouldn't be easy to make the headers non-selectable like this.

**Comment by Symbai** [comment]
With DataGridCollectionView and DataGrid added to main Avalonia repo, we received possibilities to display collections with group and sorting support. This can be closed.

**Comment by Toemsel** [comment]
@Symbai could you please point out where to find an example of grouping/sorting a DataGrid?
All I found is [code behind](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/DataGridPage.xaml.cs#L25) and the [official docs ](http://reference.avaloniaui.net/api/Avalonia.Collections/DataGridCollectionView/). I would be interested in a XAML representative of the DataGridPage.xaml.cs example. Thanks in advance

**Comment by TobiasSchulte** [comment]
> With DataGridCollectionView and DataGrid added to main Avalonia repo, we received possibilities to display collections with group and sorting support. This can be closed.

@Symbai DataGridColelctionView doesn't implement IList and can therefore not be used as the source IEnumerable of an ItemsSourceView  which in turn is used by e.g. ItemsControl. So as far as I understand this issue is still not resolved.

**Comment by timunie** [comment]
@TobiasSchulte 
1. which Avalonia version? 
2. if 11.0 preview 8 or newer, please provide a sample App with your issue to reproduce. Maybe a new issue is needed in that case.

**Comment by TobiasSchulte** [comment]
@timunie 
1. Latest preview (8) of version 11.0

2. The sample is pretty  simple:

- ViewModel with a public Property `Items` of Type `DataGridCollectionView`
- View with an `ItemsControl` with its `ItemsSource` bound to the property `Items` of the ViewModel (`ItemsSource="{Binding Items}"`)

This situation leads to an ArgumentException "Collection implements INotifyCollectionChanged but not IList." because the `DataGridCollectionView` implements `INotifyCollectionChanged` (through `IDataGridCollectionView`) but not `IList`.

Relevant sources:
- `DataGridCollectionView`: https://github.com/AvaloniaUI/Avalonia/blob/1c927688e9bb97ce4886447dd6c693ace36a6819/src/Avalonia.Controls.DataGrid/Collections/DataGridCollectionView.cs
- Origin of the exception in `ItemsSourceView` (used by the `ItemsControl`): https://github.com/AvaloniaUI/Avalonia/blob/1c927688e9bb97ce4886447dd6c693ace36a6819/src/Avalonia.Controls/ItemsSourceView.cs#L263-L273
