### ISSUE TITLE
Controls with assigned layer ignore Z order and overwrite everything on top of them

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2244]
Repro:
```xml
  <Grid>
    <Border Background="Blue" Classes="Animate">
        <Border.Styles>
            <Style Selector="Border.Animate:pointerover">
                <Style.Animations>
                    <Animation Duration="0:0:1" IterationCount="Infinite" PlaybackDirection="Alternate"> 
                        <KeyFrame Cue="0%">
                            <Setter Property="Opacity" Value="0.3"/>
                        </KeyFrame>
                        <KeyFrame Cue="100%">
                            <Setter Property="Opacity" Value="1.0"/>
                        </KeyFrame>
                    </Animation>
                </Style.Animations>
            </Style>
        </Border.Styles>
        <!-- Needed to match "animating opacity and has children condition for creating a layer -->
        <Border />
    </Border>
    <!-- This button should be on top of the Border -->
    <Button Margin="50" Content="Test"/>
  </Grid>
```
Normal state (without a layer)
![default](https://user-images.githubusercontent.com/1067584/51227790-ee7c6880-1966-11e9-9543-45d372607011.png)

With a layer (animation triggered by pointerover):
![default](https://user-images.githubusercontent.com/1067584/51227803-005e0b80-1967-11e9-8548-2c92279c23db.png)

**Comment by kekekeks** [comment]
Layer contents:

Base (0) layer:
![frame-621-layer-0](https://user-images.githubusercontent.com/1067584/51227984-b75a8700-1967-11e9-8c50-6db12d843cc1.png)

Animated border layer:
![frame-621-layer-1](https://user-images.githubusercontent.com/1067584/51227989-bde8fe80-1967-11e9-841d-bc9315495e13.png)

**Comment by ameliadiedrich** [comment]
What would be a possible way to fix this ? @kekekeks
