### ISSUE TITLE
Understanding How to Style Control Inner Parts

### ISSUE THREAD

**Issue by danhanly** [AvaloniaUI/Avalonia#2256]
I've been exploring Avalonia and trying to experiment with it over the past few days, and I'd like to understand a bit more about how certain controls are constructed and how you're able to style individual subcontrols.

See the below style which I've taken wholesale (pretty much) from the ControlGallery application:

```
  <Style Selector="TabControl.Menu">
    <Setter Property="Template">
      <ControlTemplate>
        <DockPanel>
          <ScrollViewer MinWidth="190" Background="{DynamicResource ThemeAccentBrush}" DockPanel.Dock="Left">
            <TabStrip Name="PART_TabStrip"
                      MemberSelector="{x:Static TabControl.HeaderSelector}"
                      Items="{TemplateBinding Items}"
                      SelectedIndex="{TemplateBinding SelectedIndex, Mode=TwoWay}">
              <TabStrip.ItemsPanel>
                <ItemsPanelTemplate>
                  <StackPanel Orientation="Vertical"/>
                </ItemsPanelTemplate>
              </TabStrip.ItemsPanel>
            </TabStrip>
          </ScrollViewer>
          <Carousel Name="PART_Content"
                    Margin="8 0 0 0"
                    MemberSelector="{x:Static TabControl.ContentSelector}"
                    Items="{TemplateBinding Items}"
                    SelectedIndex="{TemplateBinding SelectedIndex}"
                    PageTransition="{TemplateBinding PageTransition}"
                    Grid.Row="1"/>
        </DockPanel>
      </ControlTemplate>
    </Setter>
  </Style>
```
By this logic, I can see that a `TabControl` has within it a `DockPanel`, `ScrollViewer`, `TabStrip` and `Carousel`.

Yet within my xaml file, I'm defining it more simply:

```
<TabControl Classes="Menu" Name="Menu">
    <TabControl.PageTransition>
      <CrossFade Duration="0.25"/>
    </TabControl.PageTransition>
    <TabItem Header="Title"><views:ButtonView /></TabItem>
  </TabControl>
```

Questions:

1. How am I able to work out what subcontrols make up a control itself? I can happily use this example, but I can't find anywhere in the documentation where it tells me what a TabControl is comprised of? Or is my style xaml actually defining the subcontrol make-up?
2. What's the relevance of `PART_Content` and `PART_TabStrip` within the style?

**Comment by Gillibald** [comment]
Looks like your example is quite outdated.

Have a look at this:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Default/TabControl.xaml
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Default/TabItem.xaml

And the current ControlCatalog usage:
https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/MainView.xaml
The sidebar class is defined here:
https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/SideBar.xaml

In general, default templates are defined here:
https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.Themes.Default

**Comment by danhanly** [comment]
@Gillibald thanks, the default templates link cleared it up perfectly for me; thanks!

I'm currently messing about with 0.7 as it's the last stable - do you recommend working from master instead?

**Comment by danwalmsley** [comment]
@danhanly you can use latest builds which follow master here: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

0.7 works well, but if you come across any issues nightly builds have a some fixes in there, and fixes for mac osx, and linux.
