### ISSUE TITLE
ListBox Virtualization initially creates too many items

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2259]
If a ListBox is created with a large collection, too many items are materialized.
This https://github.com/AvaloniaUI/Avalonia/blob/0f94a0012dcb462a82aa4cca4ad8cc72b90e2995/src/Avalonia.Controls/Presenters/ItemVirtualizerSimple.cs#L120
causes enough to fill the whole screen to be created initially.  Once the measurement has sorted itself out the correct number exist.  This is a big performance hit for lists using only part of the display.
Repro - run virtualization demo and count the number of materialized items

**Comment by grokys** [comment]
Yeah, I'm not sure what to do about this. We need to work out the desired size given the constraints on the measure pass, and the only way to really do that is to materialize enough items.

Once WPF is open sourced, I intend to take a look at their code and try to work out how they do this.

**Comment by ahopper** [comment]
I did try setting width/height to zero if infinity and it worked for my code and the virtualization demo but some tests failed

**Comment by ahopper** [comment]
A work around for some cases is to set the Height on the VirtualizingStackPanel in the ItemsPanelTemplate of a ListsBox, simply setting Height on the ListBox does not prevent the issue.
