### ISSUE TITLE
MenuItem with sub-items is not closed when other menu item without sub-items is selected

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#226]
Sample code:

``` xml
    <Menu>
        <MenuItem Header="Test">
            <MenuItem Header="Item1"/>
            <MenuItem Header="Item2"/>
            <MenuItem Header="Item3">
                <MenuItem Header="SubItem3"/>
            </MenuItem>
            <MenuItem Header="Item44">
                <MenuItem Header="SubItem4"/>
            </MenuItem>
        </MenuItem>
    </Menu>
```

Screenshot:
![perspexmenusubitem](https://cloud.githubusercontent.com/assets/2297442/10191507/b85322a0-6774-11e5-8450-0912e7b21ba7.png)

When Item2 is selected Item3 sub-menu should be closed.

**Comment by mikel785** [comment]
Done for mouse actions.
Unable to test with keyboard cuz keyboard navigation seems not implemented.

**Comment by grokys** [comment]
Link to related PR: https://github.com/Perspex/Perspex/pull/372
