### ISSUE TITLE
Image not calculating its size properly

### ISSUE THREAD

**Issue by MGageMorgan** [AvaloniaUI/Avalonia#2260]
As per @grokys request, I'm filing a bug for this.

The image tag does not calculate its size properly when in a grid. 

A temporary fix right now is to resize the image and set the Width and Height attributes in XAML, but a long term solution should be getting the Image element to fix its size according to the Grid it's in automatically.

**Comment by donandren** [comment]
reason is the same as in #2138

**Comment by grokys** [comment]
Opened https://github.com/AvaloniaUI/Avalonia/issues/2263 to track the `Grid` problem.
