### ISSUE TITLE
Strange interaction between Grid width and fixed size columns

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#2263]
**Note: this problem was diagnosed after the changes in #2260 have been applied.**

Given the following XAML in `ControlCatalog.MainWIndow.xaml`:

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        x:Class="ControlCatalog.MainWindow"
        Title="MainWindow" Width="880" Height="580">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>

        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="158" />
        </Grid.ColumnDefinitions>

        <Image Grid.Row="0" Source="/Assets/delicate-arch-896885_640.jpg" />
        <Image Grid.Row="1" Source="/Assets/hirsch-899118_640.jpg" />
    </Grid>
</Window>
```

There is a strange interaction between the `Window` width and the image width:

![2019-01-24_11-32-33](https://user-images.githubusercontent.com/1775141/51672450-cbd3fa80-1fcb-11e9-94d4-a78dba0019f0.gif)

From the single grid column of a fixed size, it should be that the images maintain the same size as they should be stretched to the column width of 158 and take up the height they need due to the row height of "Auto", however that's not happening.

I believe this is a bug in `Grid`.

cc: @walterlv

**Comment by rstm-sf** [comment]
Hello! Now I do not observe similar behavior. [These ](https://github.com/AvaloniaUI/Avalonia/blob/7f6816d89de440f312a43744af5ac42c753980cf/samples/ControlCatalog/MainWindow.xaml.cs#L24-L34) lines were previously deleted

![pic](https://user-images.githubusercontent.com/2669927/85542638-b9337a00-b632-11ea-9364-295db0e6c42e.png)
![pic](https://user-images.githubusercontent.com/2669927/85542672-c18bb500-b632-11ea-9eba-017914a97a48.png)
![pic](https://user-images.githubusercontent.com/2669927/85543524-95bcff00-b633-11ea-832d-9134c4c453b9.png)

**Comment by jmacato** [comment]
This is probably fixed in my WPF Grid import...
