### ISSUE TITLE
[Skia] ListBoxItem.Foreground: Red renders as Blue and Blue renders as Red

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#2273]
Funny thing.

MCVE:

xaml:
```xml
    <ListBox Items="{Binding Data}">
        <ListBox.Styles>
            <Style Selector="ListBoxItem">
                <Setter Property="Foreground" Value="Red" />
            </Style>
        </ListBox.Styles>
    </ListBox>
```

```csharp
public IEnumerable<int> Data { get; } = Enumerable.Range(0, 5);
```
![avalonia](https://user-images.githubusercontent.com/16510738/52049514-b96f3900-2556-11e9-9e15-65e72f587bc7.jpg)

Version SkiaSharp: 1.68.0

Worked fine with SkiaSharp 1.60.0

**Comment by kekekeks** [comment]
Are you trying to use SkiaSharp 1.68 with Avalonia 0.7? That won't work because SkiaSharp has breaking ABI changes.

**Comment by FoggyFinder** [comment]
> Are you trying to use SkiaSharp 1.68 with Avalonia 0.7?

Yep, but it wasn't by purpose - it was installed after updating packages.

> That won't work because SkiaSharp has breaking API and ABI changes between versions. 

Got it, thank you. Will close then.

> Always use the version that comes with Avalonia.

It comes with Avalonia 🤷‍♂️
