### ISSUE TITLE
DropDown list is not shown when exceeds screen size

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2277]
Avalonia: 0.7.1-cibuild0001342-beta

Repro:
![2019-02-01_19-30-38](https://user-images.githubusercontent.com/2297442/52142126-1c94c480-2658-11e9-8ff1-3a71e0ed93d0.gif)

**Comment by maxkatz6** [comment]
Fixed with https://github.com/AvaloniaUI/Avalonia/pull/2778
