### ISSUE TITLE
StyledProperteries do not work on UserControls 

### ISSUE THREAD

**Issue by JCBurnside** [AvaloniaUI/Avalonia#2280]
Say you have a `UserControl` named `Star` and it has the following `StyledProperty`
```cs
public static readonly StyledProperty<uint> PointsProperty = AvaloniaProperty.Register<Star, uint>(nameof(Points),3);
        public uint Points
        {
            get => GetValue(PointsProperty);
            set
            {
                if (value < 3) throw new ArgumentOutOfRangeException(nameof(value), value, "Points Cannot be less than 3. Actual {0}.");
                if (Points != value)
                {
                    List<LinePointsViewModel> old = Lines;
                    this.SetValue(PointsProperty, value);
                    this.RaisePropertyChanged(LinesProperty, old, Lines);
                }
            }
        }
```
Styling said property with (given you have an instance of `Star` with `Classes` of `Seven`)
```xaml
        <Style Selector="v|Star.Seven">
            <Setter Property="Points" Value="7"/>
        </Style>
```
it will still have the default value of 3.

**Comment by donandren** [comment]
by default User controls are not styleable:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/UserControl.cs#L31

you can override stylekey if you need to make it styleable like:
``` C#
...
public class Star : UserControl, IStyleable
...
Type IStyleable.StyleKey => typeof(Star);
...
```
thus implemented you need to supply default ControlTemplate in the style also:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/UserControl.cs#L31

but usually if you want to make a control support styling, standard approach is not inherit from `UserContol`

**Comment by kekekeks** [comment]
http://avaloniaui.net/docs/styles/selectors#is should check for the CLR type, I think.

**Comment by JCBurnside** [comment]
Interesting what approach should be taken?

**Comment by ahopper** [comment]
It would be nice if this worked.  I think it is not unreasonable to make the assumption it should work from the documentation/intent of the styling system.

**Comment by grokys** [comment]
Yeah I agree that this should work by default. I think we should do this:

- Remove `StyleKey` on `UserControl`
- Make `UserControl`s default template selector use `:is(UserControl)`

What do you think?
