### ISSUE TITLE
F# Templates

### ISSUE THREAD

**Issue by JaggerJo** [AvaloniaUI/Avalonia#2281]
How do you guys feel about adding F# templates ?

maybe [this](https://github.com/AvaloniaUI/Avalonia/issues/593) is related and could help

**Comment by grokys** [comment]
I don't think there is anyone currently working with F# and Avalonia, but we'd definitely be happy to support F# better! What formats are F# templates built in? The same as the `dotnet new` templates? If so, a PR to https://github.com/AvaloniaUI/avalonia-dotnet-templates would be gratefully received!

**Comment by JaggerJo** [comment]
I’m working in F# 😉

Started adding a very basic F# template. XAML would also be interesting, but I had some problems with resource loading.. So I’m working on it..

Pull Request (I’d be happy to get some more feedback - template naming, ... - never did this before)

https://github.com/AvaloniaUI/avalonia-dotnet-templates/pull/16

**Comment by grokys** [comment]
Oh, thank you! That had passed me by, I will take a look.

**Comment by jmacato** [comment]
@JaggerJo Why was this closed? The PR linked to this issue hasn't been merged yet

**Comment by Takoooooo** [comment]
we have added F# templates to our avalonia-dotnet-templates repo and AvaloniaVS repo also,I think we can close that issue
