### ISSUE TITLE
Pausing Avalonia App in Visual Studio 2017 leaking threads?

### ISSUE THREAD

**Issue by garyhertel** [AvaloniaUI/Avalonia#2300]
If I create a create a simple Avalonia App with just a MainWindow like so:

            BuildAvaloniaApp().Start<MainWindow>();

And then I pause the app in Visual Studio 2017, it shows 11 threads in use. If I pause it again, 26 threads, pausing again 107 threads, then 164 threads, and then visual studio stops showing any more because it's reached the default limit. It seems like pausing the app is what triggers it, although I have no idea why AvaloniaUI doesn't react well (WPF apps don't seem to have a problem here). It does make developing a lot harder as I can only pause the app so many times before it becomes unresponsive.

**Comment by kekekeks** [comment]
The thing is that we don't spawn any threads at all. There is one ticking System.Threading.Timer instance though.

**Comment by garyhertel** [comment]
Any updates on this? I've since tried this using the Control Catalog DotNetCore sample in both Visual Studio 2019 and JetBrains Rider and they all show the same behavior of starting off with a few background worker threads and after pausing there's runaway thread creation that ends up bringing the program & IDE to a crawl. Before pausing the first time everything is fine though. I can wait 1 or 10 minutes and it always shows 5 threads the first time. But afterwards, there can be hundreds in less than a minute. This also only seems to be happening in my projects that use Avalonia.

Visual Studio 2019:

1st Pause:
![1stpause_visual_studio_2019](https://user-images.githubusercontent.com/32446542/62828791-44368d80-bba3-11e9-8df2-3a02320350f3.PNG)

2nd Pause:
![2ndpause_visual_studio_2019](https://user-images.githubusercontent.com/32446542/62828793-4bf63200-bba3-11e9-8206-c162cb615f26.PNG)

JetBrains Jider
![2ndpause_rider](https://user-images.githubusercontent.com/32446542/62828845-a217a500-bba4-11e9-8b1f-3311c423f18e.PNG)

**Comment by kekekeks** [comment]
We've identified the culprit: it's the custom implementation of render timer for win32 platform, which, apparently, leaks threads from the system thread pool.

**Comment by kekekeks** [comment]
For 0.8 you can fix it like this: https://github.com/zkSNACKs/WalletWasabi/commit/02338667e0c2fd577bbcdb7c575a29c9b0cc4d01

**Comment by garyhertel** [comment]
Perfect! I gave that a try and no more thread leaks. Thanks!
