### ISSUE TITLE
Set background image very vague.

### ISSUE THREAD

**Issue by hccoo** [AvaloniaUI/Avalonia#2304]
I using Avalonia to set a background image for a window, but the image very vague. How to do can solute it? the code:

            ImageBrush b = new ImageBrush(new Bitmap("./Images/success.png"));
            b.Stretch = Stretch.Fill;
            b.SourceRect= new RelativeRect(0, 0, 1200, 1920, RelativeUnit.Absolute);
            Background = b;

**Comment by danwalmsley** [comment]
Set the opacity to 0.2 or something, you may have to do something like this.

```
<Grid Opacity=0.2 Background=...imagebrush stuff.. />
<Grid Background="Transparent" />
```

Second grid is your content over the opaque background.

**Comment by grokys** [comment]
`ImageBrush` has an `Opacity` property: can't that be used?

**Comment by hccoo** [comment]
> `ImageBrush` has an `Opacity` property: can't that be used?

this operate can not solve my problem. my window still vague.

**Comment by jmacato** [comment]
@hccoo would be great if you can post a screenshot of your problem

**Comment by hccoo** [comment]
> @hccoo would be great if you can post a screenshot of your problem

<img width="415" alt="jt" src="https://user-images.githubusercontent.com/21059824/53068371-3452c080-3513-11e9-83f3-25082727d45a.png">
 this is the screenshot, the following is the original picture
![1](https://user-images.githubusercontent.com/21059824/53068404-4f253500-3513-11e9-82f5-0acc5fc5a98f.jpg)
