### ISSUE TITLE
DeferredRenderer holding onto Controls causing Leaks, until window is resized

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#2310]
I am trying to find a fix, looks like either the RefCount of the IVisual isn't been cleared to 0 after removing control from visual tree.

Immediate renderer doesnt have this leak and you can also trigger release by resizing window, triggering other changes in the ui doesnt release the controls either.

**Comment by MarchingCube** [comment]
I found this during my tests as well, most of my controls that are added dynamically (via ContentControl or ContentPresenter) are kept alive by the `DeferredRenderer`.

**Comment by MarchingCube** [comment]
@danwalmsley Is this already solved for you or do you still experience some leaks from the renderer?

**Comment by danwalmsley** [comment]
I believe its solved, but waiting to confirm in my apps when the remaining leaks are solved to close issue.
