### ISSUE TITLE
DatePicker displays months at the start and end of display range not correct

### ISSUE THREAD

**Issue by ReIaxo** [AvaloniaUI/Avalonia#2312]
I discovered not expected behaviour in DatePicker. Lets say it is declared like this:
``` 
<DatePicker SelectedDateFormat="Long" SelectedDate="2009-03-23"
        DisplayDateStart="2009-01-01" DisplayDateEnd="2009-12-31"
        FirstDayOfWeek="Monday"/>
```
If I use the DropDown Calendar, the months which contains the DisplayDateStart or DisplayDateEnd do not Display correct. If I click through the months and reach the start or end month that one is not displayed instantly. I have to hover over the Control a little and then it is displayed correct.

**Comment by rstm-sf** [comment]
Hello!

Could you double-check at the latest nightly builds? If I understood you correctly, then I could not reproduce this problem. The only thing after the transitions found a strange behavior  in an obsolete theme (now called [CalendarDatePicker](https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#datepicker))


![pic](https://user-images.githubusercontent.com/2669927/85548479-6a88de80-b638-11ea-877a-b7f6f092e6f0.png)![pic](https://user-images.githubusercontent.com/2669927/85548608-8db38e00-b638-11ea-845c-2c718db63d76.png)![pic](https://user-images.githubusercontent.com/2669927/85547334-3b25a200-b637-11ea-8b3f-0843c22d1fed.png)

**Comment by ReIaxo** [comment]
Hi, 
I have tested it with 0.9.11 and it works. I know, that it was 100% reproduceable when i posted this bug. My fault, that i do not mention a version. I think it was 0.7.0 or 0.8.0. 

I think you can close this now. Thank you.
