### ISSUE TITLE
Incorrect calls of AddClassHandler

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#2315]
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Input/FocusManager.cs#L28

others that need checking:

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Diagnostics/ViewModels/EventTreeNode.cs#L59

@MarchingCube @grokys @kekekeks 

Perhaps we could find a way to catch these or a Roslyn analyser to create warning.

**Comment by MarchingCube** [comment]
Good to know, I only checked the `.Changed` handlers, seems this is a wider problem. Finding cases like `FocusManager` should be doable via analyzer. Second case I think could be handled by just storing the subscription disposable and disposing it.
