### ISSUE TITLE
AffectsRender is causing memory leaks

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#2320]
After checking for memory leaks in my application I have found that `AffectsRender` is causing memory leaks.

https://github.com/AvaloniaUI/Avalonia/blob/0b3d3568ed24d9514deb78fc896d8112ec44dc25/src/Avalonia.Visuals/Visual.cs#L347-L355

The problem is that we subscribe to `Invalidated` events on certain resources (like `SolidColorBrush`) and never unsubscribe (unless the property value changes). So when we subscribe to something like a theme foreground brush, it prevents freeing of the control.

**Comment by Gillibald** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/weak-event-patterns

**Comment by MarchingCube** [comment]
@Gillibald It seems that AvaloniaEdit has an implementation of this pattern
(https://github.com/AvaloniaUI/AvaloniaEdit/blob/e6359ec742b5ec628666b1cce364f84791e056f5/src/AvaloniaEdit/Utils/WeakEventManagerBase.cs). Since we can’t use `WeakSubscriptionManager` that we already have (Visual would need to implement weak subscriber interface), one option would be to pull that class in. Opinion @grokys ?

**Comment by danwalmsley** [comment]
@MarchingCube we have https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Utilities/WeakSubscriptionManager.cs can this be used:

**Comment by grokys** [comment]
@danwalmsley: as @MarchingCube mentioned, `WeakSubscriptionManager` would require us to implement `IWeakSubscriber<EventArgs>` on `Visual`, which would mean that no derived classes would be able to add weak subscriptions to an `EventHandler` without breaking `AffectsRender`. We really need something that doesn't require us to implement an interface.

**Comment by grokys** [comment]
If `AvaloniaEdit`'s weak event manager would work for all of Avalonia's weak event requirements and doesn't necessitate implementing an interface, then I say that we should migrate to that. However, I'm unsure what the `Base` in `WeakEventManagerBase` means. Does it have to be used as a base class ?

**Comment by Gillibald** [comment]
In general, we should make sure to unsubscribe properly. Not sure how AffectsRender, AffectsMeasure works but can't we subscribe to the events on AttachedToVisualTree and unsubscribe on DetachedFromVisualTree? Maybe I am missing something here.

**Comment by grokys** [comment]
Yes, that's definitely an option. However I suspect it would be a) more complicated and b) have more runtime overhead than weak event subscriptions and for little gain.

I'd be happy to be proven wrong here though.

**Comment by kekekeks** [comment]
The problem with weak event manager from AvaloniaEdit is that it doesn't work with adding a lambda as event subscriber and doesn't check for that.

**Comment by kekekeks** [comment]
IWeakSubscriber interface is there to enforce the subscriber to be a proper method of a class that adds a subscription.

**Comment by kekekeks** [comment]
Basically most delegates constructed from a lambda function will have some compiler generated class as an object. The problem is that such target object doesn't have any GC roots and would be collected. AvaloniaEdit's weak event manager uses such target for WeakReferences. Basically it will be something really, really bug-prone.

**Comment by grokys** [comment]
What about the technique described here: http://faithlife.codes/blog/2008/08/event_subscription_using_weak_references/

Does this do anything differently/better?

**Comment by donandren** [comment]
Time ago i've created and using some weak observable utils (forgot where exactly got the idea from).
But combine using SubscribeWeakly from here and ObservableFromEventPattern should work
https://gist.github.com/donandren/c8af54e91b4b0085abafbb10d35bfcab
need to be tested for this scenario tough

**Comment by MarchingCube** [comment]
@donandren This might work, but my question would be - how can we handle the explicit unsubscribe from `e.OldValue` if we don't have the `IDisposable` for the subscription stored. Unless we start storing the weak refs to this subscription disposable as well it might be quite tricky, unless I am missing something.

**Comment by kekekeks** [comment]
We might implement yet another WeakEventManager that won't need an interface, but the API would look like this:
```cs
Subscribe<TThisClass, TEventOwner, TDelegate>(
    owner,
    SubscriptionMethod,
    (o,v)=>o.Event+=v,
    (o,v)=>o.Event-=v));
```

`Subscribe` will check that `SubscriptionMethod`'s `Target` is, in fact, `TThisClass`, solving the issue I've described earlier.

**Comment by aelij** [comment]
IIRC the AvalonEdit `WeakEventManagerBase` had some design issues, so it might need a bit of work before using it.

Another option is to copy WPF's `WeakEventManager<TEventSource, TEventArgs>` (which has static methods similar to what @kekekeks suggested) once the source becomes available.

**Comment by MarchingCube** [comment]
This should be resolved from a long time.
