### ISSUE TITLE
Errors when trying to compile current master

### ISSUE THREAD

**Issue by Krakean** [AvaloniaUI/Avalonia#2327]
Just downloaded master branch, trying to compile in Release and getting this:
https://pastebin.com/ihNsiJxU

**Comment by kekekeks** [comment]
1) Run `git submodule update --init --recursive` to download the rest of the sources
2) on Linux/OSX also install `castxml` from your package manager (`brew install castxml` on OSX)

**Comment by Krakean** [comment]
@kekekeks yes, my bad. 1st fixed issue.
