### ISSUE TITLE
Can't resize window larger on x11 if width and height set

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2329]
If the Width and Height are set on the main window you can't resize the window larger than the set size using the mouse to drag an edge or corner.  The maximise button still works. It works on windows but not linux x11.  If the Width and Height are not set it works as expected.

**Comment by ahopper** [comment]
this line
https://github.com/AvaloniaUI/Avalonia/blob/bebb53cb3436eafef562a065a556fb792577773f/src/Avalonia.X11/X11Window.cs#L878
looks a bit suspicious to me

**Comment by kekekeks** [comment]
That line was intended to ensure that max size is larger or equal to the min size. It seems that `minSize` should be replaced by `maxSize` there. Not sure if that causes your particular issue with regular Height/Width though.

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/commit/64a0ae0921ec0625081b8a976f8df22a0e589c6a
