### ISSUE TITLE
How do I use the BaseDark style?

### ISSUE THREAD

**Issue by BrianAllred** [AvaloniaUI/Avalonia#2330]
I generated a basic Avalonia app using the DotNet CLI and it works great. However, I'm trying to change the `StyleInclude` source in App.xaml from `BaseLight.xaml` to `BaseDark.xaml`, but when I do that, I get the following exception:

```
Unhandled Exception: System.IO.FileNotFoundException: The resource resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default could not be found
```

I've also tried following the example at `samples/ControlCatalog/MainView.xaml.cs` with no luck.

Any help is appreciated!

**Comment by kekekeks** [comment]
Are you using `0.7.0` from nuget or the recent build from the [nightly feed](https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed)?

**Comment by BrianAllred** [comment]
Yep, I was using 0.7.0. Updating to the nightly build fixed it, thanks!
