### ISSUE TITLE
AvaloniaUI not working properly in MacOS

### ISSUE THREAD

**Issue by lock9** [AvaloniaUI/Avalonia#2336]
Hello,
I'm using AvaloniaUI in my project, but it seems that:
- When it renders for the first time, the screen is totally black. I have to click to make it appear
- In some Mac computers, it never renders, not even clicking.

https://www.dropbox.com/s/qs8q2ro4mfjs51g/weird.mov?dl=0
https://www.dropbox.com/s/6y9x2979ewcq104/debugger-blank.mov?dl=0

This code is open source, if you want to try it, please use the development branch of this repository:
https://github.com/CityOfZion/neo-debugger-tools

Thanks

**Comment by ahopper** [comment]
Probably worth trying the nightly builds, a lot has been improved since 0.7.0

**Comment by lock9** [comment]
It worked. You just saved my day. Thanks a lot! And also thanks to those who worked hard in this lib.
