### ISSUE TITLE
Method 'get_InstalledFontNames' in type 'Avalonia.Skia.PlatformRenderInterface' does not have an implementation

### ISSUE THREAD

**Issue by Simon-Thompson** [AvaloniaUI/Avalonia#2340]
I don't know if this is the proper place to post this, but I'm getting the above error when trying to run a simple app on Linux, targeting Ubuntu 18.04 x64

I'd like direction as to where to look to debug this issue. Any help is appreciated. 

Thanks,
Simon

**Comment by Gillibald** [comment]
https://stackoverflow.com/questions/948785/typeloadexception-says-no-implementation-but-it-is-implemented

Pls double check all references. This feature was added quite recently.
