### ISSUE TITLE
.NET Core 2.1: Could not CreateWindow(): IWindowingPlatform is not registered.

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#2360]
I've added Avalonia and Avalonia.Desktop to my existing .NET Core Application. I plan on targeting both Windows and macOS. Currently testing on Windows, I've created a new Window using Visual Studio 2017 (Avalonia extension) and I'm trying to get it to show from my Program's Main.

Program.cs:
```cs
using System.Threading;

namespace api {
    class Program {
        public static ManualResetEvent close = new ManualResetEvent(false);

        static void Main(string[] args) {
            Window1 a = new Window1();
            a.Show();

            close.WaitOne();
        }
    }
}
```

Window1.xaml:
```cs
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Window1">
    Hello World!
</Window>
```

Window1.xaml.cs:
```cs
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace api {
    public class Window1 : Window {
        public Window1() { // System.Exception here: Could not CreateWindow(): IWindowingPlatform is not registered.
            this.InitializeComponent();
#if DEBUG
            this.AttachDevTools();
#endif
        }

        private void InitializeComponent() {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
```

How do I resolve this problem?

**Comment by ahopper** [comment]
You could create a new avalonia project in vs then look at the generated program.cs to see how to start up Avalonia

**Comment by mat1jaczyyy** [comment]
I understand how to start one now. However, I would not like to have a MainWindow as BuildAvaloniaApp().Start requires me to, but rather open/close windows on the fly and handle terminating the application myself. So the specific issue is solved, I will look into the follow up separately if needed.

**Comment by asmemara** [comment]
I have issue with .net core 3.1. how to  fix it ?

**Comment by kekekeks** [comment]
You need to follow the framework initialization procedure, see project templates for examples.
