### ISSUE TITLE
Slider clamps value if attributes set in wrong order

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2372]
Slider clamps Value to be between Minimum and Maximum which causes
``` <Slider Width="400" Minimum="0" Maximum="1000" Value="500" />```
to produce a different outcome to
```<Slider Width="400" Value="500" Minimum="0" Maximum="1000"  />```
which  has value clamped to 100 by the default Maximum value.
if binding is used the order also matters but with hard coded values having priority so
```
<Slider Value="{Binding filterLow}"
        Minimum="{Binding filterLowMin}" 
        Maximum="{Binding filterLowMax}" />
```
clamps to 0 or 100
but
```
<Slider Minimum="{Binding filterLowMin}" 
        Maximum="{Binding filterLowMax}" 
        Value="{Binding filterLow}"/>
``` 
does what I expected
and so does
```
<Slider  Value="{Binding filterLow}"
        Minimum="-6000" 
        Maximum="6000" />
``` 
Maybe this is expected behaviour but it caught me out. A simple fix would be to set the default limits to double.MinValue and double.MaxValue

**Comment by ahopper** [comment]
Wpf does not have this behaviour, it does not appear to bind the clamped value back to the source unless the slider is moved.

**Comment by grokys** [comment]
Yeah, we need a way to signal to the XAML reader that `Minimum` and `Maximum` should be set before `Value`. XAML has a [`[DependsOn]`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.markup.dependsonattribute?view=netframework-4.7.2) attribute which does something like this, but it's only specified for XAML writers.

We should see how easy it would be to add support for `[DependsOn]` when reading in the XAML compiler.

cc: @kekekeks

**Comment by Stripe76** [comment]
Issue still there for Sliders.
