### ISSUE TITLE
Window: Opened Event fires when using .Show() after the Window closed

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#2388]
To match WPF behavior, the Window does not open again. However, the Opened event is still fired.

**Comment by Gillibald** [comment]
I don't think this is possible under WPF. Once you close a Window you can't open it again. Just hide the window if you want to reuse it.

**Comment by grokys** [comment]
@Gillibald I don't think that is what the issue is saying. I believe the issue is that the `Opened` event is fired when trying to re-open the window even though the window won't show.

**Comment by mat1jaczyyy** [comment]
@grokys That's correct.
