### ISSUE TITLE
Linux Assertion width > 0

### ISSUE THREAD

**Issue by AbitTheGray** [AvaloniaUI/Avalonia#2392]
I have used template **Avalonia .NET Core App** in JetBrains **Rider** (it was pain to even add it).

In `MainWindow.xaml` was `Hello World!` which was underlined as Error (compiled and could be run).

`(dotnet:20264): Gtk-CRITICAL **: 13:27:27.597: gtk_window_resize: assertion 'width > 0' failed`

The window has "transparent" background (not clearing what was in its place, stuck in the windows even when moving).
To render its content, I needed to resize the window.
FIXED by itself when I was writing this and opened 2 different Riders at same time (or because of starting Rider 2018.3.4).

- Microsoft.NETCore.App/2.1.0
- Avalonia.Desktop/0.7.0

Tested with **JetBrains Rider 2019.1 Nightly** and **JetBrains Rider 2018.3.4**, both under Linux (Debian Sid, amd64 architecture).

**Comment by ahopper** [comment]
I'd try the nightly builds of Avalonia, they have a very much improved linux backend.

**Comment by kekekeks** [comment]
GTK backend is discontinued
