### ISSUE TITLE
Application crashed with Image and DefferedRenderer

### ISSUE THREAD

**Issue by vmelnikov** [AvaloniaUI/Avalonia#2394]
Sometimes the application crashes when the image is resized with exception in SharpDX.Direct2D1.dll:

`System.AccessViolationException: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."`

![1nem09S0Jz](https://user-images.githubusercontent.com/909417/55073400-b6984c80-509e-11e9-942f-996025a16ba2.gif)

This happens only with Direct2D1 renderer and DeferredRenering.

Program.cs:
`        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                 .UsePlatformDetect()
                 .With(new Win32PlatformOptions { UseDeferredRendering = true })
                 .UseDirect2D1()
                 .LogToDebug();
`

Current Avalonia version: 0.7.1-cibuild0001714-beta

**Comment by kekekeks** [comment]
Do you have the stack trace?

**Comment by vmelnikov** [comment]
No I haven't. The stack trace is null

![image](https://user-images.githubusercontent.com/909417/55141110-b2296d80-514a-11e9-9b00-bbc5aeb3c741.png)

This is the simple app to reproduce
[ImageTest.zip](https://github.com/AvaloniaUI/Avalonia/files/3017068/ImageTest.zip)

The exception is not stable. Most often occurs when resizing a window.
[Like here](http://recordit.co/fBHnTtLJVF)

**Comment by adirh3** [comment]
@kekekeks Any way to fixing this? Happens to me as well with D2D with UseDeferredRendering=true/false.
Tested on multiple machines
![image](https://user-images.githubusercontent.com/27368554/80606772-5c09b680-8a3d-11ea-8324-6d0ba60ee2b4.png)

**Comment by danwalmsley** [comment]
@adirh3 you should switch to using skia, it supports GPU and Direct2D is likely to be removed from the framework at some point in the near future. The skia backend is now the default one.

**Comment by adirh3** [comment]
@danwalmsley Thanks, I'm using Skia on my released application, the thing is I'm noticing better performance on rendering text with Direct2D

**Comment by Gillibald** [comment]
What exactly is better in terms of text rendering with the Direct2D1 backend?

**Comment by adirh3** [comment]
I noticed a **liitle** faster rendering performance when comparing the two with some automated tests (just run a function in my app that updates a large list of text and images)
The thing is that when using Direct2D, some of the text and images are not sharp, so I guess I will stick with Skia anyways.
Thanks
