### ISSUE TITLE
Strange issue on app exit

### ISSUE THREAD

**Issue by VoteForPedro** [AvaloniaUI/Avalonia#2395]
![image](https://user-images.githubusercontent.com/7259290/55087690-8a3ef900-50bb-11e9-9fef-849cad907d32.png)

The program '[9812] PTCorp.Forms.Desktop.exe' has exited with code -1073610751 (0xc0020001).

**Comment by VoteForPedro** [comment]
Unhandled exception at 0x00007FF8D2F65549 (KernelBase.dll) in PTCorp.Forms.Desktop.exe: 0xC0020001: Неправильная строка привязки (parameters: 0xFFFFFFFF8007042B).

net472 x64

**Comment by ahopper** [comment]
Can you can create a simple repro of this?

**Comment by VoteForPedro** [comment]
repro attached 

[Avalonia_2395.zip](https://github.com/AvaloniaUI/Avalonia/files/3027838/Avalonia_2395.zip)
![image](https://user-images.githubusercontent.com/7259290/55304757-afce5880-5455-11e9-887e-4434a12525a8.png)

Try run and close window. Error occurred 2 out of 3 times

**Comment by ahopper** [comment]
I had a quick play and it did not error for me on windows. I noticed a couple of odd things, you don't seem to be using the new csproj structure for consoleapp and there seemed to be a mix of avalonia versions. Strangely it built on vs2017 but not 2019.

**Comment by timunie** [comment]
@VoteForPedro this seems to be not reproducing using latest Avalonia. If you still have the issue, please ping me.
