### ISSUE TITLE
(macOS) Window.Activate does not focus and bring Window to front

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#2398]
I want to bring an existing, opened Window to the front and focus it.

`Window.Activate();` works on Windows as expected, but does nothing on macOS.

**Comment by ericoferreira** [comment]
Any update on this one?

**Comment by sergevm** [comment]
Upgraded from 0.10.10 to 0.10.18 this morning, and the created window stays behind the main window

**Comment by nesteruk** [comment]
Still broken on 11.2.3
