### ISSUE TITLE
PlacementMode (for Popup) is missing a lot of options compared to WPF

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#2404]
[WPF docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.placementmode?view=netframework-4.7.2)

**Comment by kekekeks** [comment]
Several of these options won't be supported due to the limitations of Wayland display protocol. See https://github.com/wayland-project/wayland-protocols/blob/master/stable/xdg-shell/xdg-shell.xml#L118 for more details of what can be implemented.

Namely we won't be implementing `Absolute`, `AbsolutePoint` and `Custom`. `Mouse` and `MousePoint` will be limited to the window area.

**Comment by mat1jaczyyy** [comment]
I understand. We should still support other modes that are missing though, such as `Center` for example.

**Comment by Xarlot** [comment]
We are widely using a CustomPopupPlacementCallback for popup resizing and positioning in WPF. It is just curious why Windows developers and users should struggle with popup limitations if some backend doesn`t support smth. May be you should consider a platform support options...

**Comment by kekekeks** [comment]
If we make the core parts of the framework like popups not cross-platform, Avalonia itself won't be cross-platform anymore. You are free to use platform-specific features via P/Invoke.

**Comment by kekekeks** [comment]
BTW, why do you need `CustomPopupPlacementCallback`? Our API won't allow to use screen-global coordinates, but window-relative positioning rules will be still there. We can expose raw access to `IPopupPositioner` (see https://github.com/AvaloniaUI/Avalonia/issues/2405), which should cover window-relative popup positioning rules.

**Comment by Xarlot** [comment]
The IPopupPositioner looks cool. We have something similar in our code. I think this will be more that enough.

**Comment by kekekeks** [comment]
Fine grained control over popup positioning is exposed via PlacementGravity and PlacementAnchor properties with  PlacementMode=AnchorAndGravity
