### ISSUE TITLE
DataGrid: Rework ICollectionView

### ISSUE THREAD

**Issue by sdoroff** [AvaloniaUI/Avalonia#2412]
`ICollectionView` is a somewhat necessary evil. I feel all non-essential members should be removed from the interface and implemented through a modern, generic API. In most instances, a user will set or bind an `IEnumberable` to the `DataGrid.Items` property, in which case an `ICollectionView` is created within the `DataGridDataConnection` and the details of the `ICollectionView` can be ignored by the user. But there are three areas of functionality where the `DataGrid` is dependent upon `ICollectionView`

### **Current Item Tracking**
`CurrentItem` and `SelectedItem` are slightly different concepts within the implementation. The user can use the `ICollectionView` to monitor and cancel changes to the `CurrentItem` and set the current position. There are current helper methods to move current to First and Last.

- I feel this functionality can be removed from the `ICollectionView`
- I personally have never used it and am fairly certain all functionality can be achieved with the existing `DataGrid` API

### **Grouping**
 `ICollectionView` determines if a collection is grouped and stores the grouped data structure. It currently allows grouping to be changed in place and provides information on what properties a collection is being grouped by.

- I'm torn between keeping this functionality on the `ICollectionView` or using a new interface for grouped collections
- If using a new interface, the performance hit from having to reset the `Items` property when switching from an un-grouped collection to a grouped one is relatively small
- Though, I'm not a huge fan of using an interface check to determine if a collection is grouped
- Either way a much better API for grouping should be implemented on top of it.

### **Sorting**
`ICollectionView` maintains a mutable list of the current properties being sorted by. The `DataGrid` uses this list to display sort direction in the `ColumnHeader` and to allow the user to sort the collection when a `ColumHeader` is clicked

- This functionality is pretty essential, but kind of ugly
- Due to the untyped nature of controls, it rather reflection dependent. 
- It might be possible to sort by an `IBinding` provided by the `DataGridColumn`. Though, I'm not sure how much of an improvement that is.

It's important to note, this issue is not about what a robust, user facing, data API should look like. But, instead, how a relatively hidden interface that the `DataGrid` interacts with directly needs to operate. 

Any input would be greatly appreciated

**Comment by grokys** [comment]
When we transferred `DataGrid` to the main Avalonia repo, we renamed `ICollectionView` to `IDataGridCollectionView` https://github.com/AvaloniaUI/Avalonia/pull/2109

**Comment by ShadowDancer** [comment]
@sdoroff do you need any help with this?
