### ISSUE TITLE
[LinuxFrameBuffer] Touchscreen support

### ISSUE THREAD

**Issue by Int32Overflow** [AvaloniaUI/Avalonia#2414]
Hey,

I have a Raspberry Pi with official 7 inch touchscreen. When I use Avalonia in FrameBuffer mode, only the mouse works. It would be nice if the touchscreen would also be supported :-)

Thanks

**Some infos (my Raspberry Pi Raspian 9.8):**
(https://wiki.ubuntu.com/Multitouch/Testing/CheckingMTDevice) 
```
root@raspberrypi:/home/pi# lsinput 
/dev/input/event0
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "FT5406 memory based driver"
   bits ev : EV_SYN EV_KEY EV_ABS
```

**Comment by kekekeks** [comment]
Processing code for EV_ABS is here: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Linux/Avalonia.LinuxFramebuffer/Mice.cs#L86

Try with altering this condition to also check for EV_ABS: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Linux/Avalonia.LinuxFramebuffer/EvDevDevice.cs#L63
