### ISSUE TITLE
DataGrid: Could not resolve type DataGridCell

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#2426]
I am using Avalonia and DataGrid (0.8.0). Including DataGrid theme into the application provokes the following error:

```
Error loading xaml at resm:Avalonia.Controls.DataGrid.Themes.Default.xaml?assembly=Avalonia.Controls.DataGrid: Could not convert object 'DataGridCell' (of type System.String) to {clr-namespace:Avalonia.Styling;assembly=Avalonia.Styling}Selector: Could not resolve type 'DataGridCell'
```

.csproj

```xml
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="0.8.0" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="0.8.0" />
    </ItemGroup>
```

App.xaml

```xml
<Application xmlns="https://github.com/avaloniaui">
    <Application.Styles>
        <StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml" />
        <StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseLight.xaml" />
        <StyleInclude Source="resm:Avalonia.Controls.DataGrid.Themes.Default.xaml?assembly=Avalonia.Controls.DataGrid" />
    </Application.Styles>
</Application>
```

The following workaround exists: execute some code to make sure Avalonia.Controls.DataGrid is loaded before using AvaloniaXamlLoader.

App.xaml.cs

```csharp
public override void Initialize()
{
    var dataGridType = typeof(DataGrid); // HACK
    AvaloniaXamlLoader.Load(this);
}
```

**Comment by grokys** [comment]
Yes, there is currently a problem with portable.xaml in that it doesn't load all referenced assemblies correctly.

Your workaround works, but we've also added a `UseDataGrid` extension method for `AppBuilder` which will do the same thing in a slightly tidier way.

**Comment by x2bool** [comment]
Okay, I didn't know about this extension method. Should we leave this issue opened?

**Comment by grokys** [comment]
Yeah, `DataGrid` has no documentation yet, so lets leave this open for other people looking for the solution.

**Comment by grokys** [comment]
The `UseDataGrid` method is now no longer needed since #2322 so closing.

**Comment by ennerperez** [comment]
> I am using Avalonia and DataGrid (0.8.0). Including DataGrid theme into the application provokes the following error:
> 
> ```
> Error loading xaml at resm:Avalonia.Controls.DataGrid.Themes.Default.xaml?assembly=Avalonia.Controls.DataGrid: Could not convert object 'DataGridCell' (of type System.String) to {clr-namespace:Avalonia.Styling;assembly=Avalonia.Styling}Selector: Could not resolve type 'DataGridCell'
> ```
> 
> .csproj
> 
> ```
>     <ItemGroup>
>         <PackageReference Include="Avalonia" Version="0.8.0" />
>         <PackageReference Include="Avalonia.Controls.DataGrid" Version="0.8.0" />
>     </ItemGroup>
> ```
> 
> App.xaml
> 
> ```
> <Application xmlns="https://github.com/avaloniaui">
>     <Application.Styles>
>         <StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml" />
>         <StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseLight.xaml" />
>         <StyleInclude Source="resm:Avalonia.Controls.DataGrid.Themes.Default.xaml?assembly=Avalonia.Controls.DataGrid" />
>     </Application.Styles>
> </Application>
> ```
> 
> The following workaround exists: execute some code to make sure Avalonia.Controls.DataGrid is loaded before using AvaloniaXamlLoader.
> 
> App.xaml.cs
> 
> ```cs
> public override void Initialize()
> {
>     var dataGridType = typeof(DataGrid); // HACK
>     AvaloniaXamlLoader.Load(this);
> }
> ```

Also works with  Avalonia.Svg.Skia.Svg for
> XamlX.XamlParseException: Unable to resolve type SvgImage from namespace https://github.com/avaloniaui Line 17, position 16.
