### ISSUE TITLE
add DesignerSurface as standard control

### ISSUE THREAD

**Issue by furesoft** [AvaloniaUI/Avalonia#2429]
add the designer as standard control

**Comment by grokys** [comment]
What do you mean by this? The Visual Studio designer? That is a WPF control as VS is WPF.

**Comment by grokys** [comment]
We do have https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Remote/RemoteWidget.cs but I'm not sure what state it's in. You might want to give that a try?
