### ISSUE TITLE
Can't set ScrollBar Thumb Background using style selectors

### ISSUE THREAD

**Issue by garyhertel** [AvaloniaUI/Avalonia#2435]
I'd like to set the Background color when mousing over the ScrollBar thumb. Unfortunately, I still can't get this to work without copying over the entire original ScrollBar.xaml and modifying it.

I think the problem is the DynamicResource used for the Background. It appears to be overriding any changes I make to the background afterwards.
From the ScrollBar.xaml template
```
<Thumb Name="thumb">
    <Thumb.Template>
        <ControlTemplate>
            <Border Background="{DynamicResource ThemeControlHighBrush}" />
        </ControlTemplate>
    </Thumb.Template>
</Thumb
```
Custom overrides for the mouse over
```
<Style Selector="ScrollBar:horizontal /template/ Thumb#thumb /template/ Border">
    <Setter Property="Background" Value="Blue"/>
</Style>
<Style Selector="ScrollBar:horizontal /template/ Thumb#thumb /template/ Border:pointerover">
    <Setter Property="Background" Value="Red"/>
</Style>
```
The above overrides don't work until I remove the Background in the initial declaration.

> Benedikt Schroeder@Gillibald
I think the template should be fixed by using a TemplateBinding and assigning the default to the background property. That way you can override it. Could you create an issue?

**Comment by garyhertel** [comment]
It might also be a good idea to add a default hover style to the default template to give it a more responsive feel.

**Comment by garyhertel** [comment]
One additional issue, even after disabling that original `DynamicResource Background` color, once I start dragging the thumb it reverts back to the original color.

**Comment by Gillibald** [comment]
This should be fixed.

**Comment by garyhertel** [comment]
Thanks for fixing this!

Do you know if the original style selectors I posted should work, or do they require some modification? I tried adding the code to the control catalog demo and it didn't seem to have any affect.

```
<Style Selector="ScrollBar:horizontal /template/ Thumb#thumb /template/ Border">
    <Setter Property="Background" Value="Blue"/>
</Style>
<Style Selector="ScrollBar:horizontal /template/ Thumb#thumb /template/ Border:pointerover">
    <Setter Property="Background" Value="Red"/>
</Style>
```

**Comment by Gillibald** [comment]
You need to target the Thumb itself

**Comment by Cifalse** [comment]
#

> Thanks for fixing this!
> 
> Do you know if the original style selectors I posted should work, or do they require some modification? I tried adding the code to the control catalog demo and it didn't seem to have any affect.
> 
> ```
> <Style Selector="ScrollBar:horizontal /template/ Thumb#thumb /template/ Border">
>     <Setter Property="Background" Value="Blue"/>
> </Style>
> <Style Selector="ScrollBar:horizontal /template/ Thumb#thumb /template/ Border:pointerover">
>     <Setter Property="Background" Value="Red"/>
> </Style>
> ```

when I implement this code, the pointerover part actually works but the default color isn't changed for some reason. This is even the case after I change the line to Selector="ScrollBar:horizontal /template/ Thumb#thumb". Has there been a change in how this should be approached?

**Comment by garyhertel** [comment]
FWIW, I'm still using a custom ScrollBar because I couldn't figure out how to override the default thumb color. The pointer over color is changeable as you mention though.
