### ISSUE TITLE
Add support for d:DesignInstance when using d:DataContext in designer

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2445]
Error:
```
Cannot create unknown type '{http://schemas.microsoft.com/expression/blend/2008}DesignInstance'.
```
Repro:
```XAML
<UserControl x:Class="Draw2D.Views.MainView"
             xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:editor="clr-namespace:Draw2D.Editor"
             mc:Ignorable="d"
             d:DataContext="{d:DesignInstance Type=editor:CanvasEditor, IsDesignTimeCreatable=True}"
             d:DesignWidth="800" d:DesignHeight="600">
```

**Comment by worldbeater** [comment]
For those who came across this issue while looking for a way to set a design-time `DataContext`. In Avalonia, this works as easy as:
```xml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="clr-namespace:AssemblyName.DesignTime;assembly=AssemblyName"
             x:Class="AssemblyName.Views.LoginView">
    <Design.DataContext>
        <d:DesignTimeLoginViewModel />
    </Design.DataContext>
</UserControl>
```
See also: https://avaloniaui.net/docs/quickstart/vs-designer#design-time-properties

Should be quite easy to add support for `d:DesignInstance`, we just need to write a custom [`IXamlAstTransformer`](https://github.com/AvaloniaUI/Avalonia/tree/cebd287a63fd4bb8d3a6a5c452ce7630272e5cca/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers) I guess.

**Comment by patrickklaeren** [comment]
Docs have moved to https://docs.avaloniaui.net/docs/getting-started/ide-support#design-time-properties FYI

**Comment by EricEzaM** [comment]
Whenever I use `d:DataContext` or `Design.DataContext`, the Rider previewer stops updating. If I have the design datacontext set and then changing a margin, for example, the preview will not update. As soon as I remove the design datacontext line, the preview updates.

https://github.com/ForNeVeR/AvaloniaRider/issues/209

**Comment by EricEzaM** [comment]
Yes thank you, that issue is exactly what I am having. This is just the issue that showed up when I googled the issue :P I have commented and will continue discussion there.
