### ISSUE TITLE
CommandParameter not passing when using Hotkey

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#2446]
When using Command and CommandParameter for Button the command paramter will pass only if I click the button, when I use HotKey the command triggers without the parameter. (Tried both ReactiveCommand and function)
`       <Button Name="SettingsBtn"
                               Content="Settings"                                
                                HotKey="ALT+ENTER"
                                CommandParameter="5"
                                Background="Transparent" Width="65"
                                Command="{Binding OpenSettings}" />`

**Comment by haiyaku365** [comment]
Also affect MenuItem.
For now, I hard code parameter into method call.
