### ISSUE TITLE
DataGrid selecting cell element only on third click

### ISSUE THREAD

**Issue by Ticky-Ticky** [AvaloniaUI/Avalonia#2448]
Hello! 
We made a DataGrid, and one of it columns contains checkboxes. To change the value of checkbox we need to click thrice. On first click the row is selected, on second click the cell is selected, and only the third click change the value of checkbox. 
Nearly the same problem we have with editing cell values. To edit the value of cell we need to click twice. 
Do you know about this issue? Are you planning to do something with it?

**Comment by Riccorbypro** [comment]
Confirming this issue exists, exact same behaviour as reported here is currently happening in my app.

DataGrid element (inside a Window):
```XAML
<DataGrid Items="{Binding MyListOfThings}" SelectionMode="Single"
          CanUserReorderColumns="False" >
    <DataGrid.Columns>
        <DataGridCheckBoxColumn Header="" Binding="{Binding Selected, Mode=TwoWay}"
                                Width="24" />
        <DataGridTextColumn Header="Name" Binding="{Binding Name, Mode=OneWay}"
                            Width="2*" IsReadOnly="True" />
        <DataGridTextColumn ....... />
    </DataGrid.Columns>
</DataGrid>
```

When running the app, the checkbox requires 3 clicks to tick. I'll upload an example repo showcasing the issue to my github and link it here when I have a chance, will be soon.

**Comment by cauefelipe1** [comment]
I'm here withe the same issue.

**Comment by timunie** [comment]
Use a DataGridTemplateColumn instead with a CheckBox inside. It is by design that you need to double-click to enter edit mode and then another click for the actual value to change.
