### ISSUE TITLE
Implement TextBlock.TextTrimming property

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#2452]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.texttrimming?view=netframework-4.7.2
@Gillibald perhaps this is something you might enjoy?

**Comment by Gillibald** [comment]
Will implement this feature when my other text related work is merged. This will not take much time. DirectWrite supports it out of the box and the skia text layout is flexible enough.

**Comment by jmacato** [comment]
Closing this in favor of https://github.com/AvaloniaUI/Avalonia/issues/1897
