### ISSUE TITLE
Render XAML to PNG

### ISSUE THREAD

**Issue by kotovaleksandr** [AvaloniaUI/Avalonia#2464]
Hi! I'm trying use Avalonia to render XAML to image file. 

Code (copy-paste from TestBase):
```csharp
var xaml = AvaloniaXamlLoader.Parse(File.ReadAllText(@"stamp.xaml"));
SkiaPlatform.Initialize();
var target = xaml as Grid;
var pixelSize = new PixelSize((int)target.Width, (int)target.Height);
var size = new Size(target.Width, target.Height);
var dpiVector = new Vector(96, 96);
using (var renderBitmap = new RenderTargetBitmap(pixelSize, dpiVector))
{
	target.Measure(size);
	target.Arrange(new Rect(size));
	renderBitmap.Render(target);
	renderBitmap.Save("result.png");
}
```

XAML content:
```xaml
<Grid
	xmlns="https://github.com/avaloniaui"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	xmlns:d="http://schemas.microsoft.com/expression/blend/2008" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
	Width="250"
	Height="100"
	Margin="1"
	VerticalAlignment="Center">
	<Grid.ColumnDefinitions>
		<ColumnDefinition Width="120"/>
		<ColumnDefinition Width="20"/>
		<ColumnDefinition Width="*"/>
	</Grid.ColumnDefinitions>
	<Border>
		<TextBlock x:Name="RegistrationDate" FontFamily="Arial" FontSize="14" HorizontalAlignment="Center">Text</TextBlock>
	</Border>
	<Border Grid.Column="2">
		<TextBlock x:Name="RegistrationNumber" FontSize="12">[ХХ-012345]</TextBlock>
	</Border>
</Grid>
```

In designer xaml rendered correctly:
![image](https://user-images.githubusercontent.com/2936914/56584028-8c757400-65e3-11e9-9774-15b0e6e8adef.png)

But result image rendered with low quality:
![image](https://user-images.githubusercontent.com/2936914/56584088-a911ac00-65e3-11e9-8bea-9496e07083ac.png)

Increasing font size to 50 can increase quality:
![image](https://user-images.githubusercontent.com/2936914/56584254-14f41480-65e4-11e9-9e2e-4c50285a1559.png)

How i can render xaml "like a designer" by code on Linux?

Avalonia version 0.8.0, .NET Core 2.2

**Comment by kekekeks** [comment]
I've tried to run [your code](https://gist.github.com/kekekeks/011a04d48dbf3f983c3cbbc9a8055eac) on Ubuntu 18.04 and it produces:
![result](https://user-images.githubusercontent.com/1067584/56604815-84312f00-660b-11e9-8673-c009d87ce894.png)


You are probably missing the required font.

**Comment by kotovaleksandr** [comment]
@kekekeks I may have confused you: i ran this code on Windows 10, but i expect it to work under Linux. 

TextBlock does not contains FontFamily property:
```xml
<TextBlock x:Name="RegistrationNumber" FontSize="12">[ХХ-012345]</TextBlock>
```
And increasing font size fix image quality.

Tomorrow i can check this code on Ubuntu, if result will be like yours - question can be closed.

**Comment by kotovaleksandr** [comment]
Yes, on Ubuntu and Debian works fine (tested in docker by your example https://github.com/kekekeks/avalonia-net-core-example - thanks!), but does not work on Alpine (voted in https://github.com/mono/SkiaSharp/issues/453).

On this moment my problem solved, do you have plans to investigate reason what Windows render differ Linux?

**Comment by Gillibald** [comment]
You should make sure to use the same font on all systems when you want a similar result everywhere.

**Comment by kotovaleksandr** [comment]
Windows 10, Consolas font:
```xaml
<Border>
	<TextBlock x:Name="RegistrationDate" FontFamily="Consolas" FontSize="14" HorizontalAlignment="Center">Text</TextBlock>
</Border>
<Border Grid.Column="2">
	<TextBlock x:Name="RegistrationNumber" FontFamily="Consolas" FontSize="14">[ХХ-012345]     </TextBlock>
</Border>
```
Result:
![image](https://user-images.githubusercontent.com/2936914/56719454-6bc72e80-6749-11e9-9b8d-4cda38e2d802.png)

Courier New font size 14:
![image](https://user-images.githubusercontent.com/2936914/56719815-235c4080-674a-11e9-8b82-7dae62e4d76c.png)

If increase font size and control size:
```xaml
<Border>
	<TextBlock x:Name="RegistrationDate" FontFamily="Courier New" FontSize="50" HorizontalAlignment="Center">Text</TextBlock>
</Border>
<Border Grid.Column="2">
	<TextBlock x:Name="RegistrationNumber" FontFamily="Courier New" FontSize="50">[ХХ-012345]</TextBlock>
</Border>
```
Result is very good:
![image](https://user-images.githubusercontent.com/2936914/56719985-6ae2cc80-674a-11e9-9ccf-c4d5dddb9ca4.png)

I just want get render image like a visual studio designer which render xaml correctly.

**Comment by danwalmsley** [comment]
Have you looked at the designer code in Avalonia repo? It does the same but controls Dpi.

**Comment by MageNuada** [comment]
Hi. The same problem with very poor text quality occurs when i tried to render FormattedText to image. May be they have the same root issue.
`                
                FormattedText text = new();
                text.Constraint = new Size(150, 0);
                text.TextWrapping = TextWrapping.Wrap;
                text.FontSize = 14;
                text.Typeface = new Typeface("Times New Roman", FontStyle.Normal, FontWeight.Normal);
                text.Text = "abc wefvwfvw wveergvb3rtb 3rwe ew2rf vw 24gr3evtewv vefv vwefrw3t vvweer ";

                var renderTargetBitmap = new RenderTargetBitmap(
                    new PixelSize((int)(text.Bounds.Width), (int)(text.Bounds.Height))
                    /*, new Vector(500, 500)*/);

                using (var context = renderTargetBitmap.CreateDrawingContext(null))
                    context.DrawText(Brushes.Black, new Point(0, 0), text.PlatformImpl);

                renderTargetBitmap.Save(@"C://temp//123.png");
`

![123](https://user-images.githubusercontent.com/22857920/113457789-684e7e80-9419-11eb-8464-3ed0a4240fc8.png)

**Comment by ghelyar** [comment]
This seems to change depending on the background colour:
```csharp
SkiaPlatform.Initialize();

var xaml = """
<StackPanel xmlns="https://github.com/avaloniaui">
  <TextBlock FontFamily="Arial" FontSize="20">Hello, World!</TextBlock>
  <TextBlock FontFamily="Arial" FontSize="20" Background="White">Hello, World!</TextBlock>
</StackPanel>
""";
var target = AvaloniaRuntimeXamlLoader.Parse<StackPanel>(xaml);
target.Measure(new Size(640, 480));
target.Arrange(new Rect(0, 0, target.DesiredSize.Width, target.DesiredSize.Height));
        
var renderBitmap = new RenderTargetBitmap(PixelSize.FromSize(target.DesiredSize, 1));
renderBitmap.Render(target);
var stream = new MemoryStream();
renderBitmap.Save(stream);
```

On Windows 10, with Avalonia 11.0.0-preview6 (and SkiaSharp 2.88.3), this renders with ClearType when used on a white background, but breaks on a transparent background (the default).
![avalonia_out](https://user-images.githubusercontent.com/3225358/230401278-869e72f6-ffaf-44d7-b091-c1781714b9f3.png)

**Comment by Gillibald** [comment]
> This seems to change depending on the background colour:
> 
> ```cs
> SkiaPlatform.Initialize();
> 
> var xaml = """
> <StackPanel xmlns="https://github.com/avaloniaui">
>   <TextBlock FontFamily="Arial" FontSize="20">Hello, World!</TextBlock>
>   <TextBlock FontFamily="Arial" FontSize="20" Background="#80FFFFFF">Hello, World!</TextBlock>
>   <TextBlock FontFamily="Arial" FontSize="20" Background="White">Hello, World!</TextBlock>
> </StackPanel>
> """;
> var target = AvaloniaRuntimeXamlLoader.Parse<StackPanel>(xaml);
> target.Measure(new Size(640, 480));
> target.Arrange(new Rect(0, 0, target.DesiredSize.Width, target.DesiredSize.Height));
>         
> var renderBitmap = new RenderTargetBitmap(new PixelSize((int)target.Bounds.Width, (int)target.Bounds.Height));
> renderBitmap.Render(target);
> var stream = new MemoryStream();
> renderBitmap.Save(stream);
> ```
> 
> On Windows 10, with Avalonia 11.0.0-preview6 (and SkiaSharp 2.88.3), this renders with ClearType when used on a white background, but breaks on a transparent background (the default), and is kind of half-broken on a 50% opacity background, which might help to work out what is going on. In this case it has both the clear type and the artifacts.
> 
> 3 lines of text: ![avalonia_out](https://user-images.githubusercontent.com/3225358/230404993-c1f7bc54-0dca-4bc8-8767-be8005c780ba.png)

ClearType only works with an opaque background so this is expected

**Comment by ghelyar** [comment]
Is there a way to disable ClearType on Avalonia?

In WPF this could be done with
```csharp
TextOptions.SetTextRenderingMode(this, TextRenderingMode.Grayscale);
```

Or maybe https://github.com/AvaloniaUI/Avalonia/pull/9584 will do this once it's merged?

**Comment by maxkatz6** [comment]
Yes, I believe this issue can be closed after #9584 merged, as it's possible to configure text rendering mode there.

**Comment by ghelyar** [comment]
I can confirm that setting `RenderOptions.TextRenderingMode="Antialias"` does work with version `11.0.999-cibuild0032897-beta` , although it has to be set on every `TextBlock`, it does not inherit like WPF's `System.Windows.Media.TextOptions.TextRenderingModeProperty`, but this is not a huge deal breaker for us.

![avalonia_out](https://user-images.githubusercontent.com/3225358/231125382-5d05dbb8-42d0-4ce7-872e-568b4c01ae40.png)

**Comment by yariker** [comment]
I'm facing the same issue with text rendering when doing custom drawing via `RenderTargetBitmap`. Is there a way to specify `RenderOptions` for the `DrawingContext` created by `CreateDrawingContext`?

**Comment by timunie** [comment]
You can set these per visual in v11. RenderOptions.Setxxx(myVisual)  
Not sure about RTB in this case tbh.
