### ISSUE TITLE
How to delete?

### ISSUE THREAD

**Issue by Cherkes001** [AvaloniaUI/Avalonia#2466]
How to remove Avalonia?
I click delete, the process starts and gives an error "Installation failed, rollback is in progress"

**Comment by FoggyFinder** [comment]
Can you provide more informations?

Also, I think this kind of questions better to ask at the [chat](https://gitter.im/AvaloniaUI/Avalonia).

**Comment by JayPolah** [comment]
can you also put the solution here instead of _just_ closing the issue?

**Comment by maxkatz6** [comment]
@JayPolah issue didn't have a complete and descriptive question to begin with.
If you have a similar problem, please open a new issue with details
