### ISSUE TITLE
IntegerTransition on Width/Height throws error

### ISSUE THREAD

**Issue by Wyvernius** [AvaloniaUI/Avalonia#2467]
setting an IntegerTransition to Property Width/Height throws an error: Invalid property type "Int32" for this transition: IntegerTransition.

Yet DoubleTransition does not, but width/height snaps to the new set width/height.

`<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="60" d:DesignHeight="60"
             x:Class="AvaloniaApplication1.Views.TopBarView" Background="Red" Height="{Binding TopBarHeight}" Width="{Binding TopBarWidth}">
  <Panel Height="{Binding TopBarHeight}" Width="{Binding TopBarWidth}">
    <Grid RowDefinitions="60,60,60,*" ColumnDefinitions="60,60,60,*">
      <Button Grid.Row="0" Grid.Column="0" Background="Yellow" Command="{Binding TopBarButtonPressed}"></Button>
    </Grid>
    <Panel.Transitions >
      <IntegerTransition Property="Width" Duration="0:0:2"/>
      <IntegerTransition Property="Height" Duration="0:0:2"/>
    </Panel.Transitions>
  </Panel>
</UserControl>
`

TopBarButtonPressed sets/expands the UserControl from code-behind;

**Comment by jmacato** [comment]
@Wyvernius with how the animation type registry is wired, the transitions and animators will only work with a property that has the exact type as defined in their registry. Hence `IntegerTransition` will only work with `Int32` types and so on.

**Comment by AzyIsCool** [comment]
That would be because Width/Height is a double, not an Integer. Use DoubleTransition instead of IntegerTransition (even tho Transitions seems to be broken on controls with a Width/Height property which I'm about to make an issue on)

**Comment by aragubas** [comment]
2022 and still having this issue, but now when applying DoubleTransition to Width/Height property I get this error

![image](https://user-images.githubusercontent.com/47148297/175827354-ed2cb5be-aee6-4a9e-9b1f-15f938ad4c40.png)

```
<Grid.Transitions>
    <DoubleTransition Property="Height" Duration="0:0:1" />
</Grid.Transitions>
```

I'm setting the transition property in the grid object itself

**Comment by maxkatz6** [comment]
Closing as integer transition is not supposed to be used with doubles. If you need custom behavior with rounding, you can create custom transition. 

@aragubas
