### ISSUE TITLE
TextWrap not working

### ISSUE THREAD

**Issue by AzyIsCool** [AvaloniaUI/Avalonia#2472]
Text is not Warping as it should when using ``TextWrapping="Wrap"``

![image](https://user-images.githubusercontent.com/21204235/56815126-757b8f80-6838-11e9-95c9-bf05dccd1b31.png)

Seems to only happen on Windows but not on Linux

repo with code: https://github.com/AzyIsCool/HATE

**Comment by grokys** [comment]
I think this is another symptom of the fact our `Grid` is broken :(

I'd advise changing your use of `Grid` in `MessageBox.xaml` to `DockPanel` for now. Sorry about the inconvenience. I'll close this issue because I think it's the same as #2471 - we can track the problem there.

**Comment by AzyIsCool** [comment]
Ah ok, well that means I won't be able to port some apps to Avalonia for now :(, but I can wait for when ``Grid`` gets fixed from seeing the WPF dotnet port (when that shows up out of nowhere xD) 👍
