### ISSUE TITLE
Buttons not using Foreground

### ISSUE THREAD

**Issue by AzyIsCool** [AvaloniaUI/Avalonia#2473]
I got a button which isn't using the Colour that is put in the xaml file

![image](https://user-images.githubusercontent.com/21204235/56815234-b70c3a80-6838-11e9-8b30-f4a26b806907.png)

```xaml
        <StackPanel Margin="0,5,0,0" Orientation="Vertical">
            <Button Content="-CORRUPT-"
                    Background="Black" BorderBrush="Coral" Foreground="Coral" Margin="0,0,0,5" x:Name="btnCorrupt"
                    Click="button_Corrupt_Clicked" FontWeight="Bold" FontSize="10" />
            <Button Content="-LAUNCH-"
                    Background="Black" BorderBrush="Fuchsia" Foreground="Fuchsia" x:Name="btnLaunch"
                    Click="btnLaunch_Clicked" FontWeight="Bold" FontSize="10" />
        </StackPanel>
```

but yet it using the colour in another file

![image](https://user-images.githubusercontent.com/21204235/56815413-3437af80-6839-11e9-92bf-61fd02362a8f.png)

repo with code: https://github.com/AzyIsCool/HATE

**Comment by grokys** [comment]
This is happening for the same reason as https://github.com/AvaloniaUI/Avalonia/issues/2474#issuecomment-488340074, so closing.
