### ISSUE TITLE
File Names on MacOS are percent-encoded

### ISSUE THREAD

**Issue by DanTheMan827** [AvaloniaUI/Avalonia#2475]
Per the SystemDialogs.mm file:
https://github.com/AvaloniaUI/Avalonia/blob/42af4ee24b20866a58e346da2034f794a6564247/native/Avalonia.Native/src/OSX/SystemDialogs.mm#L141

just stripping file:// off the start of the url results in a string that's still url encoded

according to the apple documentation, to get a url decoded path, line 140 should be
```
auto string = [url path];
```
and line 141 should be removed altogether

**Comment by DanTheMan827** [comment]
I can confirm that #2476 fixes this, I tested by downloading the build artifacts for the OSX native dylib and replacing the one that I had

**Comment by jmacato** [comment]
Closing this issue since @DanTheMan827 already said this is fixed (https://github.com/AvaloniaUI/Avalonia/pull/2476#issuecomment-487259056)
