### ISSUE TITLE
Avalonia crashes when maximizing and restoring main window

### ISSUE THREAD

**Issue by DieselMachine84** [AvaloniaUI/Avalonia#2479]
This issue can be reproduced every time. You can use [my project](https://github.com/DieselMachine84/RutheniumGrid).
1. Start the application - a window with a grid will be shown.
2. Maximize the window
3. Restore the window - it's client area becomes blue (I don't know why)
4. Click into the window - Avalonia crashes with NullReferenceException
`VisualNode.HitTest() in Avalonia.Rendering.SceneGraph, Avalonia.Visuals.dll
Scene.HitTest()+MoveNext() in Avalonia.Rendering.SceneGraph, Avalonia.Visuals.dll
Scene.HitTest()+MoveNext() in Avalonia.Rendering.SceneGraph, Avalonia.Visuals.dll
Scene.HitTest()+MoveNext() in Avalonia.Rendering.SceneGraph, Avalonia.Visuals.dll
Scene.HitTest()+MoveNext() in Avalonia.Rendering.SceneGraph, Avalonia.Visuals.dll
Scene.HitTest()+MoveNext() in Avalonia.Rendering.SceneGraph, Avalonia.Visuals.dll
Scene.HitTest()+MoveNext() in Avalonia.Rendering.SceneGraph, Avalonia.Visuals.dll
Scene.HitTest()+MoveNext() in Avalonia.Rendering.SceneGraph, Avalonia.Visuals.dll
Scene.HitTest()+MoveNext() in Avalonia.Rendering.SceneGraph, Avalonia.Visuals.dll
Scene.HitTest()+MoveNext() in Avalonia.Rendering.SceneGraph, Avalonia.Visuals.dll
Scene.HitTest()+MoveNext() in Avalonia.Rendering.SceneGraph, Avalonia.Visuals.dll
Scene.HitTest()+MoveNext() in Avalonia.Rendering.SceneGraph, Avalonia.Visuals.dll
Enumerable.<CastIterator>d__34<IInputElement>.MoveNext() in System.Linq, System.Linq.dll
Enumerable.TryGetFirst<Avalonia.Input.IInputElement>() in System.Linq, System.Linq.dll
Enumerable.FirstOrDefault<Avalonia.Input.IInputElement>() in System.Linq, System.Linq.dll
InputExtensions.InputHitTest() in Avalonia.Input, Avalonia.Input.dll
MouseDevice.SetPointerOver() in Avalonia.Input, Avalonia.Input.dll
MouseDevice.MouseMove() in Avalonia.Input, Avalonia.Input.dll
MouseDevice.ProcessRawEvent() in Avalonia.Input, Avalonia.Input.dll
MouseDevice.ProcessRawEvent() in Avalonia.Input, Avalonia.Input.dll
InputManager.ProcessInput() in Avalonia.Input, Avalonia.Input.dll
TopLevel.HandleInput() in Avalonia.Controls, Avalonia.Controls.dll
X11Window.<ScheduleInput>b__94_0() in Avalonia.X11, Avalonia.X11.dll
JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in Avalonia.Threading, Avalonia.Base.dll
JobRunner.RunJobs() in Avalonia.Threading, Avalonia.Base.dll
Dispatcher.RunJobs() in Avalonia.Threading, Avalonia.Base.dll
X11PlatformThreading.HandleX11() in Avalonia.X11, Avalonia.X11.dll
X11PlatformThreading.RunLoop() in Avalonia.X11, Avalonia.X11.dll
Dispatcher.MainLoop() in Avalonia.Threading, Avalonia.Base.dll
Application.Run() in Avalonia, Avalonia.Controls.dll
AppBuilderBase<AppBuilder>.Start<Ruthenium.TestApp.MainWindow>() in Avalonia.Controls, Avalonia.Controls.dll
Program.Main() in Ruthenium.TestApp, Ruthenium.TestApp.dll`

**Comment by kekekeks** [comment]
What distro, window manager are you using? Also, please, provide the output of `glxinfo |egrep 'OpenGL (renderer|vendor)'`

**Comment by DieselMachine84** [comment]
I use Gentoo with kwin-5.14.3-r1, mesa-18.2.8, nvidia-drivers-390.87
xxx ~ $ glxinfo | egrep 'OpenGL (renderer|vendor)'
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 630/PCIe/SSE2

OpenGL version string: 4.6.0 NVIDIA 390.87

**Comment by DieselMachine84** [comment]
Works fine with latest Avalonia
