### ISSUE TITLE
Add support for IValueConverter and IMultiValueConverter

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#248]

**Comment by grokys** [comment]
We need XAML resources before we can implement this.

**Comment by tshcherban** [comment]
We have interface 'IValueConverter<TFirst, TSecond>', but BindingDescriptor is not generic
Maybe we should switch value conversion to wpf style (use 'object' type)?

**Comment by jkoritzinsky** [comment]
Is there more work to do on this, or should we close it?

**Comment by wieslawsoltes** [comment]
I think we can close issue.
