### ISSUE TITLE
Binding Foreground in DataGridTextColumn

### ISSUE THREAD

**Issue by Guddiny** [AvaloniaUI/Avalonia#2482]
Code
`public IBrush Color { get; set; } = Brushes.BlueViolet;`
XAML
`<DataGridTextColumn Foreground="{Binding Color}" Header="B0" />`

Exception:
_Value of type Avalonia.Data.Binding cannot be assigned to member with type Avalonia.Media.IBrush_

**Comment by maxkatz6** [comment]
Was fixed
