### ISSUE TITLE
Multiple transitions running for a AvaloniaProperty change

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2485]
I have an AvaloniaProperty for which I have created a transition that runs for 500ms with QuarticEaseOut.
The property changes whenever the user interacts with a Canvas by dragging or zooming with mouse or touch.

Every time the property changes a new TransitionInstance is created running in parallel with any previous unfinished TransitionInstances.

This leads to the property value jumping around as the multiple TransitionInstances fight over the current value.

Please could we have an option to cancel the running TransitionInstance when creating a new TransitionInstance for a property change?

**Comment by jmacato** [comment]
Yeah, that seems to be a problem indeed, i havent got to properly count and dispose the previous `TransitionInstance`s like what i did with animations (via https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Animation/DisposeAnimationInstanceSubject.cs). I hope i can find time soon to fix this one

**Comment by jmacato** [comment]
@aguahombre Hi, i'd like to confirm if the PR fixed your issue? We still have dangling TransitionInstances but i assume they dont have any effect on the property when they are disposed.

**Comment by aguahombre** [comment]
I can't test this ATM as the nightly build of 17 May breaks my app.
XAML compiling now throws errors for type converters and markup extensions.
I will try again when the nightly build is more stable.
