### ISSUE TITLE
RelativePanel: new container panel proposal

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#2509]
Grid is traditional way to layout complex controls in WPF and Avalonia. However Grid implies predefined number of rows and columns. This creates a number of challenges, for example adding or removing controls implies changing XAML and Grid.Column or Grid.Row properties. Also Grid does not always prevent nesting of controls.

There is a control in Android Support Library called ConstraintLayout. With this control user can place views relatively to each other. It greatly reduces nesting and improves performance by eliminating multiple measure and layout passes.

![image](https://user-images.githubusercontent.com/892945/57547889-39801880-7368-11e9-843a-3e9727f08240.png)

Is there a place for such control in Avalonia?

More info:
https://developer.android.com/training/constraint-layout
https://developer.android.com/reference/android/support/constraint/ConstraintLayout

**Comment by grokys** [comment]
I think there's something similar in UWP, if I remember correctly? I wonder if that is open source?

**Comment by Gillibald** [comment]
https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.RelativePanel

**Comment by x2bool** [comment]
Yep! RelativePanel from UWP does exactly this. Didn't know about it, even though I named it correctly :)

**Comment by kekekeks** [comment]
Implementation for WPF - https://github.com/dotMorten/UniversalWPF/blob/master/src/UniversalWPF.RelativePanel/RelativePanel.cs

![image](https://cloud.githubusercontent.com/assets/1378165/10120048/b76250f0-645e-11e5-9b4d-2a0d7026a467.gif)

**Comment by kekekeks** [comment]
It seems to require IXamlNameProvider with forward reference support, though.

**Comment by danwalmsley** [comment]
this is fixed by #3987
