### ISSUE TITLE
XAML compiler: error when using custom property defined in code-behind

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#2520]
I have a `Window` (`MainWindow`) where I define a custom property in code-behind called `MyProperty`. In XAML I use the property like:

```xaml
<Window x:Class="My.Namespace.MainWindow" MyProperty="{Binding ...}" ...>...
```

It used to work fine, but with the XAML compiler it throws this error:

```
Avalonia error XAMLIL: Unable to resolve suitable regular or attached property MyProperty on type Avalonia.Controls:Avalonia.Controls.Window (line 1 position 2) Line 1, position 2.
```
I'm not sure if it's supposed to work.

It works if I replace `Window` with `MainWindow` in XAML:

```xaml
<views:MainWindow x:Class="My.Namespace.MainWindow" MyProperty="{Binding ...}" ...>...
```

**Comment by Gillibald** [comment]
The first definition doesn't look right. It makes no sense trying to use a property that is defined on an inherited class.
