### ISSUE TITLE
Maximized on different platform

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#2523]
``` WindowState="Maximized"```
Works on windows 10, macOs but don't support or create any effect on Ubuntu 18.04
Don't know why

**Comment by markmcgookin** [comment]
Both `this.WindowState = WindowState.Maximized;` and `WindowState="Maximized"` don't seem to be working at all on macOS. 

**dotnetcore 2.2.102
macOS 10.14.5
Avalonia Version="0.8.0
Avalonia.Desktop Version="0.8.0
Avalonia.ReactiveUI Version="0.8.0**

**Comment by kekekeks** [comment]
I think on Linux changing this property only works after window is shown and doesn't have any effect before that. Setting the window state works by sending a message to the Window manager and it ignores messages from not mapped windows.

**Comment by myblindy** [comment]
Just ran into this bug too, you have to add an event handler for `Opened` and set `WindowState = WindowState.Maximized;` in that. Clunky as all hell, but it works. 

It would be nice though that if this is a known issue, Avalonia would just store the property changes (I assume it's more than just maximized that doesn't work) and send them after the window is shown, if they were set before hand.

**Comment by danwalmsley** [comment]
@kekekeks pretty sure we can fix this!

**Comment by kekekeks** [comment]
I think it *should* have be fixed in master by https://github.com/AvaloniaUI/Avalonia/commit/96bd813fe449f0079792441e05e471d1d5c87042

At least we actually change the corresponding property when offscreen.

**Comment by danwalmsley** [comment]
@myblindy @CreateLab @markmcgookin this should fully work now on `0.10.0-preview1` and above.. if anyone finds otherwise please reopen the issue.
