### ISSUE TITLE
Please suggest how to streaming a  Ip camera on Avalonia UI for cross platform (window and linux) ? 

### ISSUE THREAD

**Issue by DhananjayHuidrom** [AvaloniaUI/Avalonia#2525]
How to streaming a live view of Ip camera view in Avalonia UI ?

**Comment by grokys** [comment]
@DhananjayHuidrom can you give more details? I'm not sure what you're asking.

**Comment by fortminors** [comment]
@grokys Is it possible to have a frame in which I can put the output from a camera, so a video stream? I haven't found anything on the Web, apart from using WritableBitmap. Is it still used or there is an update to this?

**Comment by fforjan** [comment]
I would be using VLC as the viewer, either with https://www.nuget.org/packages/LibVLCSharp.Avalonia/ or https://github.com/donandren/vlcsharpavalonia

**Comment by maxkatz6** [comment]
As an alternative there is now official avalonia package from VLC
https://github.com/videolan/libvlcsharp/tree/3.x/src/LibVLCSharp.Avalonia

**Comment by fortminors** [comment]
Thank you! @fforjan @maxkatz6

**Comment by maxkatz6** [comment]
There also was this experimental project https://github.com/AvaloniaUI/Avalonia.WebCam
Closing as answered

**Comment by workgroupengineering** [comment]
> There also was this experimental project https://github.com/AvaloniaUI/Avalonia.WebCam Closing as answered

is dead?
