### ISSUE TITLE
Unable to cast object of type 'Avalonia.X11.X11Window' to type 'Avalonia.Win32.WindowImpl'.

### ISSUE THREAD

**Issue by DhananjayHuidrom** [AvaloniaUI/Avalonia#2531]
Unable to cast object of type 'Avalonia.X11.X11Window' to type 'Avalonia.Win32.WindowImpl'
in ((TopLevel)control.GetVisualRoot()).PlatformImpl.Handle.Handle

**Comment by grokys** [comment]
@DhananjayHuidrom could you give more details on this? How do we reproduce?

**Comment by DhananjayHuidrom** [comment]
This error has come when  current window handle used to view the live camera view
Code:
IntPtr loginID = NETClient.Login("cameraIp", 25001, "username", "password", EM_LOGIN_SPAC_CAP_TYPE.TCP, IntPtr.Zero, ref deviceInfo);
                    if (loginID != IntPtr.Zero)
                    { 

                        //this.PlatformImpl.Handle.Handle   -> Error is here and 'this' is the current window where I am trying to view the camera view 
                        IntPtr realHandle = NETClient.StartRealPlay(loginID, 0, this.PlatformImpl.Handle.Handle, 0, m_RealDataCallBack, m_RealPlayDisConnectCallBack, IntPtr.Zero, 3000);
                        if (realHandle != IntPtr.Zero)
                        {                            

                        }
                    }

**Comment by grokys** [comment]
`'Avalonia.Win32.WindowImpl` is the platform implementation for a window on the _Windows operating system_.

If you're running on centOS then you won't have a Win32 platform implementation by definition so the cast will fail.
