### ISSUE TITLE
Binding to enum with [Flags] attribute does not work correctly

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2534]
When binding to a property of type `enum` with `[Flags]` attribute the binding produces incorrect values. This should work like standard C# and produce correct values both ways.
When I set `Mode` to `SelectionMode.Point | SelectionMode.Shape` I will get `None` in the `TextBox`. When I set `TextBox` `Text` to ` "Point, Shape"` then I get validation error.

```XAML
<TextBox Text="{Binding Mode}"/>
```
```C#
    [Flags]
    public enum SelectionMode
    {
        None = 0,
        Point = 1,
        Shape = 2
    }
```
```C#
    public static void Main()
    {
        Console.WriteLine($"{SelectionMode.Point | SelectionMode.Shape}");
        SelectionMode mode = (SelectionMode)Enum.Parse(typeof(SelectionMode),  "Point, Shape");
        Console.WriteLine($"{mode}");
    }
```

![enum_Flags](https://user-images.githubusercontent.com/2297442/57843036-e37afd00-77cd-11e9-841f-136bce9831dd.png)

Version: 0.8.1-cibuild0002387-beta

**Comment by kekekeks** [comment]
Actually not compiler related since `{Binding}` uses run-time parsing
