### ISSUE TITLE
Add a DrawingContext.DrawRect method with stroke and fill

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#2538]
On our `DrawingContext` we have `DrawRectangle` and `FillRectangle` but there's no way to draw a filled, stroked rectangle which feels rather wasteful because we're having to store two rectangles in the scene graph for each stroked and filled rectangle. We should add:

```
public void DrawRectangle(Brush brush, Pen pen, Rect rect, float cornerRadius = 0.0f)
```

To DrawingContext and have only this method on `DrawingContextImpl`.

**Comment by Kermalis** [comment]
Perhaps this can be closed now
