### ISSUE TITLE
Add attached property style selector.

### ISSUE THREAD

**Issue by dfkeenan** [AvaloniaUI/Avalonia#2545]
Hi,

Currently you can not use selectors for attached properties such as `Grid.Column`. It would be good if we could use some thing like `TextBlock[Grid.Colum=0]` to style all labels in a grid for example.

Cheers,
dfkeenan

**Comment by Mrxx99** [comment]
It works if you use `TextBlock[(Grid.Colum)=0]`

**Comment by maxkatz6** [comment]
It was implemented
