### ISSUE TITLE
Menu offscreen on Linux

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2550]
I have a menu in the top right hand corner. 
When the window is maximized on WIndows the menu always displays on screen
![image](https://user-images.githubusercontent.com/17591364/58011391-0832e580-7aea-11e9-87de-3e73a7de894d.png)

On Linux (Raspbian running LXDE) with maximized window, the menu opens either onscreen or with only the icon part on the left side is visible. This appears to alternate every time the menu is opened.
![image](https://user-images.githubusercontent.com/17591364/58011762-e25a1080-7aea-11e9-9fe1-d6a82adfa4e5.png)

**Comment by kekekeks** [comment]
#2778

**Comment by kekekeks** [comment]
Should be already fixed by #2778
