### ISSUE TITLE
IMarkupExtension

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2554]
Can I suggest that Avalonia supports IMarkupExtension (as well as MarkupExtension from Portable.Xaml.Markup)?

At the moment you can't create a markup extension that has bindable properties as you can't inherit from both MarkupExtension and AvaloniaObject. By implementing an interface version of MarkupExtension you could have bindable properties which would be extremely useful.

`public interface IMarkupExtension
{
    object ProvideValue(IServiceProvider serviceProvider);
}
`

**Comment by kekekeks** [comment]
Update to nightly builds. XamlIl uses duck typing and just tries to find ProvideValue by a signature in the following order:

```
T ProvideTypedValue();
T ProvideTypedValue(IServiceProvider provider);
T ProvideValue();
T ProvideValue(IServiceProvider provider);
object ProvideValue();
object ProvideValue(IServiceProvider provider);
```

where T is some type that is not a `System.Object`.

**Comment by aguahombre** [comment]
OK, so if I understand you correctly, custom markup extensions don't need to be derived from MarkupExtension; just define a ProvideValue method.
That would solve the problem.
I will give it a go.
