### ISSUE TITLE
Window resizing from bottom moves its position upward

### ISSUE THREAD

**Issue by yakiro-nvg** [AvaloniaUI/Avalonia#2557]
Tested with AvalonStudio on OSX.

When I resize its main window using bottom border to make it smaller, after it reaches minimal height it started to move the window's position upward. Is it an expected behavior?

**Comment by kekekeks** [comment]
@danwalmsley

**Comment by danwalmsley** [comment]
@yakiro-nvg @kekekeks its a bug, im doing some work on osx backend this week so will trying and find a fix for it.
