### ISSUE TITLE
Inherits from TabItem is not working in v0.8

### ISSUE THREAD

**Issue by OmidID** [AvaloniaUI/Avalonia#2566]
I have problem with TabControl after upgrade
Inheritance from TabItem is not working properly. The tab strip will disappear.

```cs
public class MainPageItem : TabItem {...}
```

**Comment by Gillibald** [comment]
Will have a look at it

**Comment by Gillibald** [comment]
Pls implement IStylable on your custom control then it should work

```
public class MainPageItem :TabItem, IStyleable
{
    Type IStyleable.StyleKey => typeof(TabItem);
}
```

**Comment by OmidID** [comment]
@Gillibald It's worked well. Should we say is a bug or this is how it's should function from now?

**Comment by Gillibald** [comment]
It is working as intended

**Comment by OmidID** [comment]
OK, Thanks. I'll close this issue
