### ISSUE TITLE
SelectionStart and SelectionEnd not working

### ISSUE THREAD

**Issue by HendrikMennen** [AvaloniaUI/Avalonia#2567]
Hello,

I am new to Avalonia and I am trying to select the text in a TextBox.
In WPF this works:

`textBox.SelectionStart = 0`
`textBox.SelectionEnd = 3`

This code gets executed when the textbox gets focus.
But to be sure I tried to give it focus manually with 

> textBox.Focus()

before setting Selection.

This should select the first 4 characters in my textbox.
But it does nothing so far.
Doing other stuff with the textBox like changing the text or background works without problems.

I am not 100% sure if this is a bug since there are many things different than in WPF.
If you need more of my code please let me know.

**Comment by kekekeks** [comment]
Looks like a bug. I think the textbox just doesn't get re-rendererd for some reason

**Comment by ahopper** [comment]
I have seen something that may have the same cause. If you select text with the mouse on a readonly TextBox the selection only shows if something else updates the text. I suspect some updates currently only work because the flashing caret updates the whole control.

**Comment by HendrikMennen** [comment]
It works if the cursor is not inside the textbox. The problem occurs only when selecting text after gaining focus by clicking in the textbox

**Comment by kekekeks** [comment]
I've pushed several changes to TextBox and TextPresenter, please check, if the issue is still present

**Comment by HendrikMennen** [comment]
Looks like you fixed it :)
