### ISSUE TITLE
How to animate a rotation?

### ISSUE THREAD

**Issue by alessandrofrancesconi** [AvaloniaUI/Avalonia#2572]
Dears, 

I have this image:
`<Image Classes="Rotating" Source="/Assets/icon_gear.png" />`

and I want it to start spinning right after the window is shown. So I've followed this: http://avaloniaui.net/docs/animations/keyframe

I've added this Style:
  ```
<UserControl.Styles>
    <Style Selector="Image.Rotating">
      <Style.Animations>
        <Animation Duration="0:0:5">
          <KeyFrame Cue="0%">
            <Setter Property="**Angle???**" Value="0"/>
          </KeyFrame>
          <KeyFrame Cue="100%">
            <Setter Property="**Angle???**" Value="360"/>
          </KeyFrame>
        </Animation>
      </Style.Animations>
    </Style>
  </UserControl.Styles>
```

As you see, I don't know which Property to set so that it can spin.
In "classic" XAML, one way it to use Storyboards: https://stackoverflow.com/a/12298305/901046
But I don't see them in Avalonia...

**Comment by jmacato** [comment]
Try doing `RotateTransform.Angle`

**Comment by alessandrofrancesconi** [comment]
Aaaaand it works! 🥇

**Comment by TheMalgot** [comment]
This doesn't work for me anymore to rotate an image. Has the release candidate changed the approach to this?
