### ISSUE TITLE
DataGrid binding not working

### ISSUE THREAD

**Issue by braca** [AvaloniaUI/Avalonia#2577]
Hi,

Using the latest nightly builds, the DataGrid control seems to be buggy, when binding to objects.

Example (xaml):

```
  <DataGrid
    Items="{Binding Items}">
    <DataGrid.Columns>
      <DataGridTextColumn Header="Name" Binding="{Binding Name}"/>
      <DataGridTextColumn Header="Not working" Binding="{Binding OtherProperty}"/>
    </DataGrid.Columns>
  </DataGrid>
```
```
    public class Person
    {
        public Person(string name)
        {
            this.Name = name;
        }

        public string Name { get; set; }
        
        public OtherObject OtherProperty
        {
            get
            {
                return new OtherObject();
            }
            set
            {

            }
        }
    }

    public class OtherObject
    {
        public override string ToString()
        {
            return "Test";
        }
    }
```

Binding to this `Person.OtherProperty` is not working, there is no error, but the value doesn't appear in datagrid, and it also makes the whole DataGrid very unresponsive (the scroll becames very slow)

This same sample works as perfectly with the latest 'stable' build 0.8.0

Repro: https://github.com/braca/avalonia-datagrid

**Comment by braca** [comment]
I've tested this again (same sample) but now with only 1 item in the items list.

For some reason when rendering the DataGrid (when initializing the app, or sorting the datagrid, 
 etc) Avalonia tries to set the property `OtherProperty` to `null`, weird :| 

Besides that nasty bug, it also seems that it does that a lot of times!
For ex, Avalonia tried to set the `OtherProperty` to `null` aprox 600 times at startup

That's weird, and it should explain why DataGrid get's so slow when I have a list with many items

**Comment by braca** [comment]
I've found the change that caused this issue
It was a change in PropertyAccessorNode.cs in this https://github.com/AvaloniaUI/Avalonia/commit/197d7d4904b4767d882c676232cad67ffe3fd566 commit from #2486

**Comment by braca** [comment]
@grokys can you help?

**Comment by braca** [comment]
I've updated my test repo to the latest CI build, and the problem is now even worse, my demo app won't start at all, it seems that it enters an infinite loop as it keeps set `OtherProperty` to null (OtherProperty had a value, and DataGrid shouldn't be changing it value to null!!)

**Comment by TETYYS** [comment]
still relevant in 0.9.7

**Comment by rstm-sf** [comment]
> Binding to this Person.OtherProperty is not working, there is no error, but the value doesn't appear in datagrid, and it also makes the whole DataGrid very unresponsive (the scroll becames very slow)

> Repro: https://github.com/braca/avalonia-datagrid

In the nightly build 0.9.999-cibuild0008348-beta this is falling on stackoverflow

**Comment by maxkatz6** [comment]
@braca you can set Mode=OneWay or OneTime (as it seems to be expected from bindings to class). Probably it also is expected to set readonly on the column or grid, but isn't necessary.
Real issue with looping set-method calling should be fixed too though.
