### ISSUE TITLE
(macOS) All Text appears to be shifted a few pixels up

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#2579]
Comparisons between macOS and Windows in [mat1jaczyyy/apollo-studio](https://github.com/mat1jaczyyy/apollo-studio):

![image](https://user-images.githubusercontent.com/13300194/58474343-1d8fbb80-814b-11e9-8a89-41f057d79680.png) ![image](https://user-images.githubusercontent.com/13300194/58474355-25e7f680-814b-11e9-8ade-6e39eb275c47.png)

![image](https://user-images.githubusercontent.com/13300194/58474378-35673f80-814b-11e9-9f87-09cc65d50c66.png) ![image](https://user-images.githubusercontent.com/13300194/58474374-313b2200-814b-11e9-9ea6-abb52d5592b5.png)

![image](https://user-images.githubusercontent.com/13300194/58474392-3e581100-814b-11e9-940d-fa1dd3712e0b.png) ![image](https://user-images.githubusercontent.com/13300194/58474404-49ab3c80-814b-11e9-8085-70ee19f20065.png)

The difference is pretty obvious and I'd say it gives my app a completely different, unnatural feel on macOS.

**Comment by Gillibald** [comment]
We can clearly see that that you don't use the same font for your App on all platforms. To make sure you use the same font you have to use an embedded font that is shared on all platforms. Rendering quality can differ because on Window text is rendered by DirectWrite and on Mac FreeType is used. Pls check if an embedded font works for you.

https://fonts.google.com/

**Comment by mat1jaczyyy** [comment]
I don't use a font at all in fact - I use whatever Avalonia throws at me by default. In my opinion, while the font doesn't necessarily need to match, the measures and positioning should.

**Comment by HendrikMennen** [comment]
If you don't specify a font you will use the one your system uses by default. Some fonts have different sizes for whatever reason. Now I am using NotoSans because it has the same size as Segoe UI (Default from Windows) and looks almost the same.

**Comment by mat1jaczyyy** [comment]
I've worked around this with Open Sans, but yeah, free to use any font we want. Close if you don't consider the inconsistent vertical positioning an issue.

**Comment by Gillibald** [comment]
We can keep this open until the new text layout has been merged. You can also try it out via myget pr feed if you want.

**Comment by maxkatz6** [comment]
@Gillibald I believe this can be closed. I also can see this issue on mac.
