### ISSUE TITLE
 Breaking Change in pointer capture 

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2586]
Currently there are several issues with pointer capturing and tracking the pressed state of the pointer.

1) if your control gets PointerPressed event, *not* obtains a capture, and pointer is moved away, your control won't get any PointerReleased notifications.
2) If your control gets PointerPressed event, obtains a capture and then some parent control obtains a capture, your control won't  get any PointerReleased notifications.

To resolve these issues (and to allow us to implement touch scrolling somewhat properly), we are planning to change the pointer capture behavior in the following way:

- always take a capture on PointerPressed (now there is only one PointerPressed per pointer, extra mouse buttons will result in PointerMoved), so a pressed pointer will always have a capturing control
- when a capture is transferred,  the previous control and all controls on the path to the common parent with the new captured element will receive PointerCaptureLost direct event

Also, W3C [is doing something like that](https://bit.ly/2JJJLX8) for browsers, so we should be fine.

Affected parts of the framework:
- managed DnD implementation will have to do manual hit testing on the current visual root

------

Please, check if this affects any of your usage scenarios and tell us our opinion.

**Comment by grokys** [comment]
Some notes on how other frameworks handle this:

> always take a capture on PointerPressed

- WPF and UWP: do _not_ do an implicit capture of the pointer on a press with either mouse or touch.
- WinForms: does an implicit capture
- Web: touch devices do an implicit capture in all cases. Some other controls do implicit capture. https://www.w3.org/TR/pointerevents/#implicit-pointer-capture
  - W3C is considering changing to implicit capture for all controls https://github.com/w3c/pointerevents/issues/125

> now there is only one PointerPressed per pointer, extra mouse buttons will result in PointerMoved

WPF: sends multiple `MouseDown` events
UWP: behaves as proposed here

**Comment by mat1jaczyyy** [comment]
Sounds like a good change!
