### ISSUE TITLE
Add IsCancel property to Button

### ISSUE THREAD

**Issue by jhofinger** [AvaloniaUI/Avalonia#2588]
Avalonia already has an `IsDefault` property on `Button`s.

[Similar to WPF](https://docs.microsoft.com/de-de/dotnet/api/system.windows.controls.button.iscancel?view=netframework-4.8), I propose adding an `IsCancel` property. This property should raise the Click event / command when the `Esc` key is pressed.

**Comment by konstantingross** [comment]
Issue can be closed because the [property](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Button.cs#L157) already exists.
