### ISSUE TITLE
Resizing when Window has fixed size, tries to resize content.

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#259]
![image](https://cloud.githubusercontent.com/assets/4672627/10332731/258ba182-6cd7-11e5-828c-54a7800856ac.png)

This happens when you resize a window with:
MaxWidth="600" MaxHeight="250" MinWidth="600" MinHeight="250"

**Comment by danwalmsley** [comment]
Quick note to say this issue persists.

**Comment by grokys** [comment]
This no longer happens, though there is a flickering as described in #401. Closing this and tracking there.
