### ISSUE TITLE
Allow un-escaped braces in property values

### ISSUE THREAD

**Issue by jhofinger** [AvaloniaUI/Avalonia#2592]
In WPF, it is [perfectly legal](https://stackoverflow.com/questions/19278515/use-stringformat-to-add-a-string-to-a-wpf-xaml-binding) to write

```{Binding World, StringFormat=Hello {0}}```

In Avalonia, this leads to the error `Invalid character after the end of the extension root node at position 38`. 

A workaround for that is using 

```{Binding World, StringFormat=Hello \{0\}}```

I propose adding support for unescaped curly braces in Property values.

**Comment by grokys** [comment]
WPF also supports having a leading `{}` to escape a format string: https://stackoverflow.com/a/2552911/6448

**Comment by grokys** [comment]
In addition, currently the XAML compiler doesn't handle escaped curly braces in XML attributes properly. Writing this:

```
<MultiBinding StringFormat="\{0\} \{1\}">
```

Results in `StringFormat` being set to that exact string without the escape characters being removed.

**Comment by grokys** [comment]
Added a failing test in #2598: https://github.com/AvaloniaUI/Avalonia/blob/fdd5d7afec4151862327a0b225359fd15291cf08/tests/Avalonia.Markup.Xaml.UnitTests/Xaml/BindingTests.cs#L335

**Comment by kekekeks** [comment]
`{}` at the beginning of the string can be used to treat the whole string as plain text.
