### ISSUE TITLE
Classes without parameterless constructors can not be used as root elements for XAML

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2593]
XAMLIL tries to build a object creation node even in cases where it's not needed

**Comment by pr8x** [comment]
Hey, is any work on this planned?

**Comment by laolarou726** [comment]
Still get this error in the latest Avalonia. Are there any plans to fix it?

**Comment by cdytoby** [comment]
Bump this. I'm trying to use Window and View with dependency injection, and I encountered this with Window with parameter in constructor.
