### ISSUE TITLE
[Animation] Black screen and Render problems

### ISSUE THREAD

**Issue by mameolan** [AvaloniaUI/Avalonia#2599]
Hello,

thank you for your project. I play around with Animations and get some drawing problems (black screen and render issues) on windows 7. Here is the playgrond project:
[AvaloniaAnimationTest.zip](https://github.com/AvaloniaUI/Avalonia/files/3240221/AvaloniaAnimationTest.zip). I used this repo [LoadingIndicators.WPF](https://github.com/zeluisping/LoadingIndicators.WPF) for the animation tests. I also recognize that some effects in Avalonia are different to Wpf (ScaleTransform, TranslateTransform,...). 

Screenshot:
![animation-error](https://user-images.githubusercontent.com/51226030/58933820-c43a1480-8768-11e9-8a15-cc0942bcc992.gif)

Regards

**Comment by smartguy1196** [comment]
@maxkatz6 what was the solution? I'm trying to make PSAvalonia asynchronous by running avalonia inside of a powershell runspace, but I'm getting a black window

**Comment by smartguy1196** [comment]
Going to try to run it without using the runspace to see if that makes a difference.

**Comment by smartguy1196** [comment]
It's also possible that I'm using the wrong rendering libraries for my platform (I'm having to install the dependencies manually at the moment). I'm running on Win x64

**Comment by smartguy1196** [comment]
Here's the powershell script for running Avalonia Asynchronously (This doesn't use PSAvalonia, but I'm planning on porting it) to resolve https://github.com/ironmansoftware/psavalonia/issues/6

```pwsh
# Create new runspace
$Runspace = [Management.Automation.Runspaces.RunspaceFactory]::CreateRunspace( $Host )
        
# Initialize the runspace object
# - Some Windows Forms and WPF controls are only STA
$Runspace.ApartmentState = 'STA'
$Runspace.ThreadOptions = 'ReuseThread'
$Runspace.Open() | Out-Null

# Add the window tracker to the Runspace environment
# - Makes the windows usable inside the runspace
$Runspace.SessionStateProxy.SetVariable( 'Avalonia_Wins', $Avalonia_Wins ) | Out-Null
# - To access the application object from inside the runspace:
#   - use [Avalonia.Application]::Current

# Create a new PowerShell object (a Thread)
$PowerShellRunspace = [System.Management.Automation.PowerShell]::Create()

# Initialize the PowerShell object with the runspace
$PowerShellRunspace.Runspace = $Runspace

$PowerShellRunspace.AddScript({

    # Set platform-specific services on the main loop
    $AppBuilder = [Avalonia.AppBuilder]::Configure[Avalonia.Application]()
    $AppBuilder = [Avalonia.AppBuilderDesktopExtensions]::UsePlatformDetect( $AppBuilder )
    
    # Set the lifetime for the applicaiton
    $LifeTime = [Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime]::new()
    $LifeTime.ShutdownMode = [Avalonia.Controls.ShutdownMode]::OnExplicitShutdown
    $AppBuilder = $AppBuilder.SetupWithLifetime( $LifeTime )
    
    # Set the Avalonia main loop
    $App = $AppBuilder.Instance
    
    $Window = [Avalonia.Markup.Xaml.AvaloniaRuntimeXamlLoader]::Parse[Avalonia.Controls.Window](@"
    <Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        Width="800" Height="450"
        Title="Test">
        <StackPanel>
            <Button Width="160" Name="button">My Button</Button>
            <TextBox HorizontalAlignment="Left" Margin="12,12,0,0" Name="txtDemo" VerticalAlignment="Top" Width="500" Height="25" />
        </StackPanel>
    </Window>
"@)
    
    $Window.Show()
    
    # Set application lifetime via cancellation token (required for cross-platform dev)
    $CancellationTokenSource = [System.Threading.CancellationTokenSource]::new()
    
    # Run the main loop
    [Avalonia.Controls.DesktopApplicationExtensions]::Run( $App, $CancellationTokenSource.Token )
    
}) | Out-Null

$PowerShellRunspace.BeginInvoke() | Out-Null
```

**Comment by smartguy1196** [comment]
Well I think I notice an issue with my dependencies. From the build files of PSavalonia, it looks like my implementation of Avalonia in PowerShell is missing Avalonia.Angle.Windows.Natives

This missing dependency seems to be the culprit. According to https://github.com/AvaloniaUI/angle/, that native library is the implementation of [Google's Angle in Avalonia](https://en.wikipedia.org/wiki/ANGLE_(software)). I'm shocked that Avalonia isn't erroring out when this library is missing.

**Comment by smartguy1196** [comment]
Though, timeline-wise there could be another issue. The last fix for Avalonia.Angle that should have affected my imp was in February of this year: https://github.com/AvaloniaUI/Avalonia/pull/10204

This issue was closed on June 18th of last year, so whatever solution was implemented here was not resolved by that pull request, but rather by something else

**Comment by smartguy1196** [comment]
Ok, fixing the dependency, fixed that problem, but... new problem, my window is transparent :/

### This is my window with this github issue as a background...

![image](https://user-images.githubusercontent.com/12621101/226543135-49ba0e26-fa5d-4115-83bb-d8a908a4c57d.png)

**Comment by smartguy1196** [comment]
From an initial search, it looks like the problem is caused by missing an application theme

https://github.com/AvaloniaUI/Avalonia/search?q=invisible+window&type=discussions

**Comment by smartguy1196** [comment]
Will need to figure out how to add the theme dynamically using powershell...

**Comment by smartguy1196** [comment]
Ok. translating this into powershell, and using the sources that are used in `Application.Styles` for PSAvalonia, I got Avalonia to work in my own implementation of Avalonia in PowerShell:

https://github.com/AvaloniaUI/Avalonia/blob/b002de40f27fafd5229e0f5ffd4a323cb0e6dbf8/samples/ControlCatalog/MainView.xaml.cs#L35-L58

Screenshot of it working now:

![image](https://user-images.githubusercontent.com/12621101/226763900-1e8725d3-bdaf-4a98-8cd1-efdc1f9940af.png)

**Comment by ALIENQuake** [comment]
@smartguy1196  Care to share a solution? Sorry for pinging you here but I'm interested in what you have done for your own Avalonia PowerShell implementation and your PSAvalonia fork has disabled issues and discussions.

**Comment by smartguy1196** [comment]
@ALIENQuake I'm working on it. The fork was to just to get PSAvalonia to upgrade from 0.8.x

My imp will be hosted from its own repo, as it was built from the ground up, and doesn't just support Avalonia, but WPF, and WinForms. I used PSAvalonia as a reference when I would come across bugs in my imp. I'll have the repo uploaded before the end of the week

My implementation runs Avalonia/WPF/WinForm asynchronously. It's actually pretty simple todo, especially if you are just looking to use WPF/WinForms.

You setup the Application instance inside of a PowerShell Runspace. While in the runspace, share the System.Window.Threading.Dispatcher Object for the runspace with the the host runspace (I use a hashtable stored on a sessionproxy variable).

Then call the Dispatcher from the host runspace thread to run code on the application's runspace/thread.

**Comment by ALIENQuake** [comment]
@pinuke Very nice! Thanks! I will look at it and try to provide feedback directly inside repo.
