### ISSUE TITLE
AvaloniaList MoveRange fails on some overlapped moves

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2602]
Moving items to a higher index with overlap will either move to the wrong place or throw an index out of bounds exception.
This https://github.com/AvaloniaUI/Avalonia/blob/9b8485122317d42bf522309cd3ddf0fa3d12082e/src/Avalonia.Base/Collections/AvaloniaList.cs#L355-L358
subtracts too much if overlapped

**Comment by ahopper** [comment]
My mistake here, I got it into my head that the to index was final position.

**Comment by sudongg** [comment]
Same error:

```
Children.Add(1);
Children.Add(2);
Children.Add(3);
Children.Add(4);
Children.MoveRange(0,2, 1);
```

crash: OutOfRangeExceptions 
```

    if (newIndex > oldIndex)
    {
       ==> modifiedNewIndex -= count;
     }
```
