### ISSUE TITLE
Is it possible to select not the first item if source contains equal items?

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#2609]
A bit odd behaviour:

![sindAv](https://user-images.githubusercontent.com/16510738/58766807-bb401c00-858b-11e9-84a6-fc1d17f40cc2.gif)

MCVE:
xaml:
```xml
<ListBox Name="lb" />
```
```fsharp
let lb = self.Find<ListBox>("lb")
do lb.Items <- "0123401234"
```

Is it bug or feature? In the latest case it will be better to document it somewhere.

**Comment by ahopper** [comment]
probably a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2004

**Comment by FoggyFinder** [comment]
@ahopper thank you, you're right. It's duplicate. Closed.
