### ISSUE TITLE
Handle ctrl+v in textbox 

### ISSUE THREAD

**Issue by Ticky-Ticky** [AvaloniaUI/Avalonia#2611]
Hello!
I am trying to restrict user to type some characters into textbox. I use TextInputEvent in this case and everything works fine until user use ctrl+v to paste text. Ctrl+v fires 4 events (KeyDown Ctrl, KeyDown V, KeyUpCtrl, KeyUp V), TextInputEvent is not fired, and I can't check text added into textbox and I can't prevent invalid characters from being added.
Maybe you can help me with this problem. Thanks in advance.

**Comment by kekekeks** [comment]
Our current TextBox implementation [checks for keyboard mappings](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBox.cs#L407) and triggers its [internal Paste](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBox.cs#L355) implementation which calls [HandleTextInput](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBox.cs#L319) directly. 

We should probably trigger routed TextInputEvent instead.

**Comment by maxkatz6** [comment]
It's possible to handle PastingFromClipboard event or disable CanPaste.

**Comment by Energizer188** [comment]
@maxkatz6 how can we disable CanPaste? The property is readonly
I also tried to remove the event handler for PastingFromClipboard event but that's not possible too
How an we prevent any copy/pasting in a textbox?

**Comment by maxkatz6** [comment]
> I also tried to remove the event handler for PastingFromClipboard event but that's not possible too

You don't remove even handler, but instead you handle it and set EventArgs.Handled property to true.
That's how handling event "cancellation" is normally done with routed events.
Sometimes you need to handle even with tunnel strategy (so it won't be handled by other controls first), but in this case I don't think you need.

> @maxkatz6 how can we disable CanPaste? The property is readonly

**Comment by Energizer188** [comment]
> You don't remove even handler, but instead you handle it and set EventArgs.Handled property to true.
That's how handling event "cancellation" is normally done with routed events.

Yesterday I tried :
`

                textbox.AddHandler(PastingFromClipboardEvent, textbox_PastingFromClipboard, RoutingStrategies.Tunnel);

                private static void textbox_PastingFromClipboard(object? sender, RoutedEventArgs e)
                {
                    e.Handled = true;
                }
`
It happens that the tunnel version of PastingFromClipboardEvent is never raised, maybe it's intended?
So today I tried with the bubble version of the event and it worked fine.

And I understand the purpose of CanPaste now, thank your for your answers !
