### ISSUE TITLE
Context menu is broken

### ISSUE THREAD

**Issue by jhofinger** [AvaloniaUI/Avalonia#2612]
In the control catalog, the context menu doesn't work anymore. Neither of the two context menus open, and I tried most of the button combinations (right click, left click, ctrl+right click and so on).

**Comment by grokys** [comment]
Seems to have been broken by f556db57b439f8474d8ed36834a27577ea974442

@kekekeks

**Comment by kekekeks** [comment]
Will attempt a fix after merging https://github.com/AvaloniaUI/Avalonia/pull/2595

**Comment by kekekeks** [comment]
Fixed by https://github.com/AvaloniaUI/Avalonia/pull/2595/commits/9f249b6b53da1dd655030e6811c92817ce84fd6c
