### ISSUE TITLE
Chars restriction for PropertyPath

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#2621]
Currently there are next restrictions to the symbols:

```cs
        private static bool IsValidIdentifierChar(char c)
        {
            if (IsValidIdentifierStart(c))
            {
                return true;
            }
            else
            {
                var cat = CharUnicodeInfo.GetUnicodeCategory(c);
                return cat == UnicodeCategory.NonSpacingMark ||
                       cat == UnicodeCategory.SpacingCombiningMark ||
                       cat == UnicodeCategory.ConnectorPunctuation ||
                       cat == UnicodeCategory.Format ||
                       cat == UnicodeCategory.DecimalDigitNumber;
            }
        }
```
[Source](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Utilities/IdentifierParser.cs#L31-L46)

These constraints are definitely more strict than WPF has. For example, `UnicodeCategory.DashPunctuation` is valid for WPF.

**Comment by grokys** [comment]
Why would you need to use a dash in a property path? Is there anywhere a dash is valid in a .NET property name?

Also by allowing dashes, we'd be ruling out the future possibility for allowing mathematical expressions in a binding.

**Comment by FoggyFinder** [comment]
> Is there anywhere a dash is valid in a .NET property name?

I don't think so.  Not sure although.

Anyway, properties with dashes might be exposed as helper properties in some libraries.
For example, in [_Gjallarhorn.Bindable_](https://github.com/ReedCopsey/Gjallarhorn.Bindable):

```fs
    let getErrorsPropertyName propertyName =
        propertyName + "-" + "Errors"
    let getValidPropertyName propertyName =
        propertyName + "-" + "IsValid"
```
[Source](https://github.com/ReedCopsey/Gjallarhorn.Bindable/blob/master/src/Gjallarhorn.Bindable/BindingSource.fs#L30-L33)

So it won't work for Avalonia as for WPF.

If dashes won't be allowed in principle then I'll open issue there to discuss how to handle it better. I just want to be sure that it is intentional restriction and not bug or something.

**Comment by FoggyFinder** [comment]
Closing this one since that not a bug and last reply was long ago.
