### ISSUE TITLE
Issue with items highligthing in listbox

### ISSUE THREAD

**Issue by Ticky-Ticky** [AvaloniaUI/Avalonia#2625]
Problem sometimes appears after scrolling. The previous item is not on hover but remains highlighted and the current item is set highlighted too. 
![image](https://user-images.githubusercontent.com/38004061/59009799-7e547d80-8848-11e9-95a6-83753ff0e19c.png)

**Comment by grokys** [comment]
I think this is a duplicate of #2518.

What version of Avalonia are you using? This should have been fixed on master by #2524. Could you try using our [nightly packages](https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed)?
