### ISSUE TITLE
LinearGradientBrush is not working with StartPoint/EndPoint

### ISSUE THREAD

**Issue by Ticky-Ticky** [AvaloniaUI/Avalonia#2626]
Hello! 
I'm trying to use . It's working fine with horizontal gradient:
```
<LinearGradientBrush x:Key="BackgroundGradient">
            <GradientStop Offset="0" Color="#C2E4F6" />
            <GradientStop Offset="1" Color="#95CDEC" />
        </LinearGradientBrush>
```

But when I'm trying to make vertical gradient, background becomes solid:

```
<LinearGradientBrush x:Key="BackgroundGradient" StartPoint="0,0" EndPoint="0,1" >
            <GradientStop Offset="0" Color="#C2E4F6" />
            <GradientStop Offset="1" Color="#95CDEC" />
        </LinearGradientBrush>
```

**Comment by ahopper** [comment]
<LinearGradientBrush StartPoint="0%,0%" EndPoint="0%,100%"> works for me

**Comment by kekekeks** [comment]
I guess we need to add that to http://avaloniaui.net/docs/quickstart/from-wpf

It was weird for me as well.

**Comment by Gillibald** [comment]
I don't see why WPF's syntax isn't possible.

**Comment by kekekeks** [comment]
Our brush uses RelativePoint which considers coordinates to be absolute by default https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/RelativePoint.cs

**Comment by Gillibald** [comment]
But isn't `0%` equal to `0.0` and `100%` equal to `1.0`? The example that works just uses `%` syntax everything else is equal.

**Comment by kekekeks** [comment]
`100%` equals to `1.0` + `RelativeUnit.Relative` while `1` equals to `1.0` + `RelativeUnit.Absolute`

**Comment by ahopper** [comment]
yep this is not very intuitive, I guess I struck lucky and copied an example from somewhere in the samples.

**Comment by grokys** [comment]
How could it be made more intuitive do you think? I based it around how CSS expresses such things.

**Comment by ahopper** [comment]
the fact that the offsets are 0..1 and the endpoints are % is not something you would guess, they are both ratios so my initial feeling is they should be the same.

**Comment by grokys** [comment]
I'm not sure what you mean by "offsets are 0..1 and the endpoints are %" - could you explain?

**Comment by ahopper** [comment]
well in the example at the top the GradientStop Offset is given a value from 0 to 1 which I understand to be a proportion (ratio) of the distance between the StartPoint and EndPoints , it would make some sense to me for these to be in % . I've not studied what the possible values for Start and end are, if they can be virtual pixels or % that make sense.

**Comment by grokys** [comment]
If you mean the example that says `EndPoint="0,1"`, then that is _not_ a value from 0 to 1. That markup is setting the endpoint to `0, 1` _pixels_ which is why it didn't work.

In markup, if the value is specified without a `%` then it indicates pixels. With a `%` it means percentage.

WPF is different in that you can only set the offset as a percentage (expressed by the range 0..1) which is maybe what you're thinking of?

There is a good point to be made about this being confusing when coming from WPF. How could we minimize this confusion while still allowing both relative and absolute points?

**Comment by ahopper** [comment]
My point is that on two consecutive lines of xaml you have to use 100% (in the StartPoint) and 1 in the offset to mean the same thing i.e. all of it.

**Comment by grokys** [comment]
Ahhh, the `GradientStop`. Gotcha! Yeah, I agree that isn't very consistent.

**Comment by Gillibald** [comment]
Would it make sense to have something like a `Length` that has a `Unit` of type `pt, px, %` etc to make this consistent? Similar to `RelativePoint` but for a scalars.

**Comment by mstr2** [comment]
Why not simply swap the default behavior? So "0,1" would be interpreted as a percentage (as it is in WPF, but adding the percentage sign would be optional), and "0px,1px" would be interpreted as pixels.

**Comment by mysteryx93** [comment]
This isn't working for me. Horizontal gradient works, but this gives solid Red. Strangely, if I switch offset values (set Blue with offset 1), it makes no difference and remains red.

```xaml
<LinearGradientBrush x:Key="BackgroundBrush" EndPoint="0%,100%" StartPoint="0%,100%">
    <GradientStop Color="Blue" Offset="0" />
    <GradientStop Color="Red" Offset="1" />
</LinearGradientBrush>
```

**Comment by maxkatz6** [comment]
But your start and end points are the same

**Comment by mysteryx93** [comment]
AAhhhh... there's that. Works now :)

**Comment by Coolkeke** [comment]
`<Border Height="40">
    <Border.Styles>
        <Style Selector="Border">
            <Style.Animations>
                <Animation
                    FillMode="None"
                    IterationCount="Infinite"
                    Duration="0:0:0.5">
                    <KeyFrame Cue="0%">
                        <Setter Property="Background">
                            <Setter.Value>
                                <LinearGradientBrush StartPoint="0%,100%" EndPoint="100%,100%">
                                    <GradientStop Offset="0" Color="#C2E4F6" />
                                    <GradientStop Offset="0" Color="#95CDEC" />
                                    <GradientStop Offset="1" Color="#C2E4F6" />
                                </LinearGradientBrush>
                            </Setter.Value>
                        </Setter>
                    </KeyFrame>
                    <KeyFrame Cue="100%">
                        <Setter Property="Background">
                            <Setter.Value>
                                <LinearGradientBrush StartPoint="0%,100%" EndPoint="100%,100%">
                                    <GradientStop Offset="0" Color="#C2E4F6" />
                                    <GradientStop Offset="1" Color="#95CDEC" />
                                    <GradientStop Offset="1" Color="#C2E4F6" />
                                </LinearGradientBrush>
                            </Setter.Value>
                        </Setter>
                    </KeyFrame>
                </Animation>
            </Style.Animations>
        </Style>
    </Border.Styles>
</Border>`

You may need this answer

**Comment by Coolkeke** [comment]
You may need this answer
```
<Border Height="40">
    <Border.Styles>
        <Style Selector="Border">
            <Style.Animations>
                <Animation
                    FillMode="None"
                    IterationCount="Infinite"
                    Duration="0:0:0.5">
                    <KeyFrame Cue="0%">
                        <Setter Property="Background">
                            <Setter.Value>
                                <LinearGradientBrush StartPoint="0%,100%" EndPoint="100%,100%">
                                    <GradientStop Offset="0" Color="#C2E4F6" />
                                    <GradientStop Offset="0" Color="#95CDEC" />
                                    <GradientStop Offset="1" Color="#C2E4F6" />
                                </LinearGradientBrush>
                            </Setter.Value>
                        </Setter>
                    </KeyFrame>
                    <KeyFrame Cue="100%">
                        <Setter Property="Background">
                            <Setter.Value>
                                <LinearGradientBrush StartPoint="0%,100%" EndPoint="100%,100%">
                                    <GradientStop Offset="0" Color="#C2E4F6" />
                                    <GradientStop Offset="1" Color="#95CDEC" />
                                    <GradientStop Offset="1" Color="#C2E4F6" />
                                </LinearGradientBrush>
                            </Setter.Value>
                        </Setter>
                    </KeyFrame>
                </Animation>
            </Style.Animations>
        </Style>
    </Border.Styles>
</Border>
