### ISSUE TITLE
Mouse capture broken on Win32

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#2627]
After updating to latest version I found out that custom decorated windows get broken when dealing with resizing. This has a repro in control catalog when opening custom decorated dialog, trying to resize it will end up with window getting stuck in resize mode.

From some rough code check it seems we no longer call win32 apis responsible for mouse capture, and window gets event about mouse leaving window even though it is suppposed to have active capture.

cc: @kekekeks as you did latest input changes

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/commit/85a5288fdd835481764ffc6c10dfb77c90708c3a
