### ISSUE TITLE
Single quotes are no longer ignored in xaml converter source

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#2630]
I have some xaml that converts objects and strings into bitmaps like this:
```xaml
          <CheckBox Grid.Row="0" Grid.Column="0" HorizontalAlignment="Left" Name="Illegal">
            <Image Source="{Binding Source='Allow illegal data', Converter={x:Static infrastructure:ObjectToTextBitmapConverter.Instance}, ConverterParameter=MenuWhite, Mode=OneWay}"/>
          </CheckBox>
          <CheckBox Grid.Row="0" Grid.Column="1" HorizontalAlignment="Center" Name="Shiny">
            <Image Source="{Binding Source='Shiny', Converter={x:Static infrastructure:ObjectToTextBitmapConverter.Instance}, ConverterParameter=MenuWhite, Mode=OneWay}"/>
          </CheckBox>
```
Previously, the quotes in 'Allow illegal data' and 'Shiny' were simply used to convert the string, but now they are parsed into the converter:
![image](https://user-images.githubusercontent.com/29823718/59138720-a6cd9c00-895c-11e9-9655-0b793e59ffb5.png)
Started happening once I switched from stable 0.8.0 to 0.8.1 nightly builds

**Comment by Kermalis** [comment]
It is also ignoring \n:
```xaml
Source="{Binding Source='Moves:\nPP-Ups', Converter={x:Static infrastructure:ObjectToTextBitmapConverter.Instance}, ConverterParameter=MenuWhite, Mode=OneWay}"
```
![image](https://user-images.githubusercontent.com/29823718/59723339-5411a100-91f4-11e9-953d-5f064f692386.png)
I'm unsure if this was working before though, but I find it strange that it removes the \

**Comment by kekekeks** [comment]
`\` is currently treated used as escape character.
