### ISSUE TITLE
Overlays spawn with the wrong coordinates and size when they are inside of a Viewbox

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#2631]
![image](https://user-images.githubusercontent.com/29823718/59139335-77209300-8960-11e9-902a-49e1b06222a1.png)

The Viewbox hosts one of its parents and its Stretch is set to Uniform.

**Comment by grokys** [comment]
Is this in 0.8? I've just tried it on 0.8 and can repro there, but it appears to be fixed on master. Could you try the nightly feed and see if it works there?

**Comment by Kermalis** [comment]
I have been on 0.8.1.cibuild0002893-beta and just tried in 0.8.1-cibuild0003053-beta (newest prerelease as of today) and it still happens:
![image](https://user-images.githubusercontent.com/29823718/60135581-05be4e00-9770-11e9-9d41-b793e1fefcd7.png)
#2633 actually was fixed between these two releases, though

**Comment by grokys** [comment]
Could we get a minimal repro? I've not been able to reproduce the problem.

**Comment by Kermalis** [comment]
Here you go: https://github.com/Kermalis/AvaloniaRepo2631

**Comment by Kermalis** [comment]
It is important to note that they are now spawning at the correct coordinates, just using the incorrect size

**Comment by Kermalis** [comment]
ToolTips are also small in a Viewbox, but I am not sure if they deserve to be big?
My situation:
![image](https://user-images.githubusercontent.com/29823718/60138836-bf6dec80-9779-11e9-9b86-ac1a854b83aa.png)

**Comment by grokys** [comment]
Need to check if `ViewBox` affects popups on WPF/UWP.

**Comment by maxkatz6** [comment]
Fixed with https://github.com/AvaloniaUI/Avalonia/pull/8042 for ComboBox. Any other overlay can be updated to support that as well.
