### ISSUE TITLE
Crash with Grid

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#2632]
I only have one control with Grid, and it is a UserControl. All is fine when I put the control directly into my Window, but if I put the control in another UserControl, and that other UserControl then into the Window, I get this crash:
https://pastebin.com/raw/WJ1xWi08

Occasionally when editing that "other UserControl" in the xaml designer, I see an error in the error list that says "Cannot convert System.Double to Avalonia.Controls.GridLength" which would be the same crash since the only casting in that method is of GridLength.

The control with the Grid is also not being picked up by this.FindControl<T>() anymore, although it was being picked up before I switched to nightly builds from 0.8.0, where this crash didn't exist.

**Comment by jmacato** [comment]
Will fix this in #2620, seems like my changes for checking when Parent is null was not included in the diff...
