### ISSUE TITLE
Some controls do not respond to inputs when inside of a stretched Viewbox.

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#2633]
They work fine if Stretch=None or if they are pressed in a location they would be at if there was no stretching.

![2019-06-07_20-51-44](https://user-images.githubusercontent.com/29823718/59140000-2ca21500-8966-11e9-93bc-a47d3fcd2572.gif)

The gif shows that the textboxes do work. I also had DropDowns inside of the Viewbox that worked (but see #2631)

**Comment by kekekeks** [comment]
It probably has something to do with [this check](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Button.cs#L276)

**Comment by Kermalis** [comment]
This bug also occurs with Checkboxes. I think it is safe to say most controls will need to have their logic take into account this situation, since it was probably overlooked when creating them.

**Comment by Kermalis** [comment]
Some time between 0.8.1.cibuild0002893-beta and 0.8.1-cibuild0003053-beta this got fixed. I'm not sure exactly when, but I will close this

**Comment by grokys** [comment]
I think it was probably #2539 that fixed it.
