### ISSUE TITLE
Add Horizontal & Vertical ContentAlignment to TextBox

### ISSUE THREAD

**Issue by Abdulbaqi-Alshareef** [AvaloniaUI/Avalonia#2634]
In Avalonia TextBox is missing properties to arrange its content
if we face this:

![TextboxWithoutAlignment](https://user-images.githubusercontent.com/18364158/59148248-878b4900-8a06-11e9-9ead-400f9599397e.png)

In this case we need way to arrange the content to look like this:

![TextboxWithAlignment](https://user-images.githubusercontent.com/18364158/59148251-8fe38400-8a06-11e9-8c2b-1cddc729a2cb.png)

We can do it by this code:

`<TextBox Background="#eeeeee" Height="70" Width="200" Text="Some text here">
      <TextBox.Styles>
        <Style Selector="TextBox  /template/  TextPresenter">
          <Setter Property="HorizontalAlignment" Value="Center"/>
          <Setter Property="VerticalAlignment" Value="Center"/>
        </Style>
      </TextBox.Styles>
    </TextBox>`

But if we add watermark it won't get alignment, and we could fix it by this :

`<TextBox Background="#eeeeee" Height="70" Width="200" Text="Some text here">
      <TextBox.Styles>
        <Style Selector="TextBox  /template/ Panel">
          <Setter Property="HorizontalAlignment" Value="Center"/>
          <Setter Property="VerticalAlignment" Value="Center"/>
        </Style>
      </TextBox.Styles>
    </TextBox>`

But I think it's better and easier to do it WPF way like this:

` <TextBox Background="#eeeeee" Height="70" Width="200" Text="Some text here"
             VerticalContentAlignment="Center" HorizontalContentAlignment="Center">
    </TextBox>`

**Comment by derekantrican** [comment]
I'm on 0.9.12 and

```xml
<Style Selector="TextBox /template/ TextPresenter">
  <Setter Property="VerticalAlignment" Value="Center"/>
</Style>
```

seems to provide a workaround for me. Do you have a similar one for NumericUpDown or DatePicker? Both these controls seem to have the same issue (aligned Top by default) on all platforms (NumericUpDown, however, seems to be aligned Center on Windows) and changing the Selector to `NumericUpDown /template/ TextPresenter`, for instance, does not work. I am not sure how I should change the selector for these controls

**Comment by maxkatz6** [comment]
@derekantrican this selector should work, but untested:
NumericUpDown /template/ TextBox /template/ TextPresenter

Anyway, adding these props to NumericUpDown and DatePicker sounds as a good idea.

**Comment by derekantrican** [comment]
Excellent - `NumericUpDown /template/ TextBox /template/ TextPresenter` and `DatePicker /template/ TextBox /template/ TextPresenter` seem to both work. Thanks!
