### ISSUE TITLE
DragAndDrop doesn't work for external files

### ISSUE THREAD

**Issue by onepiecefreak3** [AvaloniaUI/Avalonia#2635]
After looking into the sample application "ControlCatalog.Desktop" to see how to get a drag and drop for files running, I wasn't able to reproduce it in any way.
I copied over most of the sample application into my app and the only drag and drop operation that doesn't work anymore is drag and dropping files onto the app. Drag and drop elements from within the app to another element, which AllowDrop property was enabled for, did work.
I'm at a loss now what I might miss in comparison to the sample app that that single feature I wanted doesn't work.
I attached my current application state, that has this described behaviour.
My goal is: Dragging and dropping a file onto a "AllowDrag"-enabled element within the application, like the sample app does show.
[AvaloniaApplication3.zip](https://github.com/AvaloniaUI/Avalonia/files/3268752/AvaloniaApplication3.zip)

**Comment by mat1jaczyyy** [comment]
I've ran into this as well and can reproduce this on macOS and Windows.

**Comment by JakubK** [comment]
@onepiecefreak3  Did you manage to find a solution ? 
I'm having exact same problem.

**Comment by wieslawsoltes** [comment]
You need to add `[STAThread]` attribute to your `Main` method.
```C#
[STAThread]
public static int Main(string[] args)
```

**Comment by JakubK** [comment]
Yeah, that's right.
Thank you very much for help.
