### ISSUE TITLE
ViewBox

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#2637]
strange size of content of view box
if i use span for this rows
```
 <RowDefinition  Height="Auto"></RowDefinition>
           <RowDefinition  Height="20"></RowDefinition>
            <RowDefinition  Height="Auto"></RowDefinition>
```
![Screenshot from 2019-06-09 10-40-40](https://user-images.githubusercontent.com/33497292/59156390-0df56880-8aa3-11e9-8d54-91166c9749d8.png)
but if i add one row like this to span everything is ok

```
 <RowDefinition  Height="Auto"></RowDefinition>
            <RowDefinition  Height="20"></RowDefinition>
            <RowDefinition  Height="Auto"></RowDefinition>
            <RowDefinition Height="1"></RowDefinition>
```
![Screenshot from 2019-06-09 10-41-56](https://user-images.githubusercontent.com/33497292/59156399-3bdaad00-8aa3-11e9-9d0a-d2605ad81874.png)

**Comment by grokys** [comment]
I think this is a bug with `Grid` which should have been fixed by #2563. Could you try our nightly builds and see if it's fixed there?
