### ISSUE TITLE
Wrong Wrapping

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#2638]
Textblock sometimes "eats" some words before wrapping
![ezgif com-crop](https://user-images.githubusercontent.com/33497292/59156875-3b461480-8aab-11e9-816d-82b832e5e254.gif)

` <TextBlock Grid.Row="1" Grid.Column="3" Text="i set textblock textwrapping, and now it's looks very strange"  TextWrapping="Wrap"/>`

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/1950
