### ISSUE TITLE
Cairo.Path is leaking, programmer is missing a call to Dispose

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#264]
The message is shown in application output when running on Linux/Gtk in MonoDevelop.

**Comment by grokys** [comment]
We need to work what to do here. Problem is that controls are never `Dispose`d of, but `Shape` has a reference to a cairo path. Maybe it should be disposed when removed from visual tree? Would this fix the message?

**Comment by wieslawsoltes** [comment]
I do not use the `Shape` for rendering geometry and text.

I'm overriding the `Render` method for `Control` class:
https://github.com/Core2D/Core2D/blob/master/Core2D.UI.Perspex.Windows/Controls/Drawable.cs#L370

and doing rendering using `DrawingContext`:
https://github.com/Core2D/Core2D/blob/master/Core2D.UI.Perspex.Windows/Renderer/PerspexRenderer.cs

I can use caching for Pen's and Brushes' but from time to time (when style has changed in my program on new project was loaded) I need to dispose them.

Also I need to dispose Bitmap's.

**Comment by wieslawsoltes** [comment]
I think this also is important for other platforms, so the pattern of acquiring and disposing drawing resources is consistent.
