### ISSUE TITLE
Exception proposal

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#2640]
Avalonia 0.8
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:rxui="clr-namespace:Avalonia;assembly=Avalonia.ReactiveUI"
        mc:Ignorable="d" d:DesignWidth="150" d:DesignHeight="100"
        Width="350" Height="150"
        x:Class="MessageBox.Avalonia.Views.MessageBoxWindow"
        Title="AvaloniaAppTemplate">
   <Button Honest="No exception"/>
</Window>
```
Often when avalonia cant render window , it just ignores it, without any exception

**Comment by Gillibald** [comment]
I don't think this can happen with the current master because XamlIl should produce a compile-time error.

**Comment by HankG** [comment]
I often get compile time errors for problems with the XAML.  If it's a problem during resolution of a bound property that usually doesn't happen until runtime.  That may be getting better with the stuff @Gillibald mentioned.

**Comment by rstm-sf** [comment]
![image](https://user-images.githubusercontent.com/2669927/116263260-e7697500-a781-11eb-85b1-5d01e0b5a6c1.png)
