### ISSUE TITLE
Avalonia.iOS/Avalonia.Android packages are not sent to the Nightly or Pull Requests feed

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#2653]
The nuget and nightly builds feeds feature ios builds, but the PR feed does not contain any ios builds.

**Comment by Kermalis** [comment]
Nightly builds has actually stopped pushing iOS builds after May 12th.

**Comment by kekekeks** [comment]
Blocked by Xamarin.iOS bug https://forums.xamarin.com/discussion/120814/xamarin-ios-project-cs1703-multiple-assemblies-with-equivalent-identity-have-been-imported

**Comment by Kermalis** [comment]
Android stopped working as well recently. I'm not using either one at the moment but I figured I'd mention it.

**Comment by maxkatz6** [comment]
Now available on nightly and pr feeds.
