### ISSUE TITLE
Button.IsEnabled is False when being pressed which introduces unexpected behavior

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#2655]
In a situation where a Button's IsEnabled is set to true, and in code it is then set to false, the button will then turn gray and be incapable of activating (normal behavior). However, if it is pressed (via Enter or Touch/Click) and the code it runs in its command changes its IsEnabled to false, it will do nothing, since IsEnabled is actually false from being pressed (bad behavior). Then, the button will remain enabled and will allow unexpected bad behavior since it was expected to become disabled.

I think setting IsEnabled to false when being pressed is a little misleading, since it gives mixed signals when checking IsEnabled; you would then not be sure if it is disabled, if it is just being pressed, or both. If you were looking for pressed, there is IsPressed anyway, and checking IsEnabled with IsPressed is really not that crazy. Would you ever hold down a button for long enough that code would be checking IsEnabled to see if the button is available? I can't think of any good use for that in multi-threading either. I can only think of times when the user is using touch and tries to touch the same button with multiple fingers/pens, but again, IsPressed exists.

Despite whether this is useful or not, when the button is released, it sets IsEnabled to true which overwrites the false value I was trying to set, which I think is unintentional behavior. Since IsEnabled now means multiple things, it seems a little strange that you could even set it to false since it is more like a get property that combines \[enabled & pressed & command allows usage\].

This issue does not happen when the command has a Subject<bool> that feeds enabled values to it (which I was using before but I prefer the IsEnabled setting in code since it's cleaner and I'm used to WinForms)

I understand that IsEnabled could be checked to see if it is available for user interaction in any way, but I still see it as a bug that it will overwrite the value I'm trying to set within its own command. I need to set it to false after it is activated, but now that cannot happen with IsEnabled. Is this why commands will take Subject<bool>? For this specific issue? If so, I am fine with using that instead, but I just thought I'd bring this up in case it is something that needs changing instead of keeping it to myself.

**Comment by grokys** [comment]
Hi @Kermalis, sorry I can't understand the problem here. Could you maybe show a bit of code which demonstrates the problem?

**Comment by Kermalis** [comment]
I think that issue you linked fixed it since this no longer happens (I was on 0.8.1.cibuild0002893-beta and updated to 0.8.1-cibuild0003053-beta where the issue no longer occurs)
