### ISSUE TITLE
TemplateBinding behavior issue

### ISSUE THREAD

**Issue by igorstefus** [AvaloniaUI/Avalonia#2657]
It seems like initial value of bind view model property is not sent to target if target property is changed in property class handlers of other properties for same target. This was working fine before and we noticed it after updating to latest Avalon builds.

Problem seems to be isolated to template binding so in my small [example](https://bitbucket.org/igorstefus/avalonia_binding_issue/src/master/BindingProblem/) we have two custom controls (one nested in other) so I can easily demonstrate this.

In view model minimum is 1, maximum is 180 and value is 75. Value property is clamped between maximum and minimum when maximum and minimum change using class handlers. It seems that minimum and maximum change handlers are called before default value from view model for value property is set and since default for double type is 0 it will be clamped to 1. Problem is that if value property is update in handlers, initial value (75) from view model is not send to value property. As consequence value is 1 and it should be 75.

**Comment by Gillibald** [comment]
Am I right that the issue is that values of different properties are dependent on each other and the order of evaluation is important? I think there is an open issue about NumericUpDown that has the same issue.

**Comment by igorstefus** [comment]
In this case it's not that. It is a problem of source property initial value not been sent to the target property under specific condition.  In this case it seems that if you update property of the target (that didn't yet receive value from binding source) inside of property change handler of any other property for same target than targeted property doesn't receive initial value at all.  I was able to reproduce this behavior only with TempalteBinding inside ControlTemplate of other control. 

We noticed it because our control was resenting to minimum value instead of showing default value that is within range of  minimum and maximum. And this started happening after latest Avalon updates. Previously order of binding evaluation was not important for clamping value since value should be corrected by validation regardless of evaluation order but problem is that initial value is not getting to the target after it property was initial set by clamping. I know this because when I put break point in Value property change handler I never receive update for initial value, only value that was set by clamping.  

It's little bit hard to explain :). Check example I provided and you will notice that value should not be 1 regardless of evaluation order.

**Comment by grokys** [comment]
This seems to be caused by `TemplateBinding` producing an `{unset}` value while the control is still initialized (i.e. before `TemplatedParent` is set).

**Comment by grokys** [comment]
I've made a fix to `TemplateBinding` to not produce a value until the control is initialized but the problem still remains. What happens is:

- `Minimum`, `Maximum` and `Value` are set on `TestControl`
- `TestChildControl.Minimum` is bound to `TestControl.Minimum` and `TestChildControl.Minimum` is set
- `TestChildControl.OnMinimumChanged` is called
- At this point `TestChildControl.Value` is still 0, so `Value` is set to 1
- `Value` is bound to `TestControl`, so 1 is written to `TestControl.Value`

In effect, by setting `Value` in a changed handler for a different property, you're causing the coerced value to be written back to the source _before_ the original value has had chance to arrive.

Does that make sense?

**Comment by igorstefus** [comment]
Thanks for checking it out. Yes that is exactly what is happening. What I see as problem is that default value never arrives to value change handler (before or after assigning minimum value in minimum or maximum change handler). Correct me if I am wrong, but default value should still arrive because it was not corrected in validation method for value property it was just set in change handler of another property. 

For example in this case value was change before it was initialized and it was 0 so it was set to minimum. If Value (change handler or validation function) received default value afterwords I can still validate it again against minimum and maximum and set the proper value.

**Comment by ahopper** [comment]
maybe slightly related to https://github.com/AvaloniaUI/Avalonia/issues/2372 ?

**Comment by grokys** [comment]
> For example in this case value was change before it was initialized and it was 0 so it was set to minimum. If Value (change handler or validation function) received default value afterwords I can still validate it again against minimum and maximum and set the proper value.

When you say "default value" here, what do you mean? Do you mean 75 in this case?

The reason 75 never arrives is because after the coercion is run, `Value` is no longer 75.

I'm not sure we can fix this in the binding system, because one of the conflicting values has to win. I'm also not sure why it worked previously in your control because the fact that the problem exists in `Slider` as well means that the problem was always there. I suspect that something changed the order that bindings fired in and caused the problem to show up.

I'm going to have a think about this and see if I can think of a decent solution.

**Comment by grokys** [comment]
Ok, I think the best way to handle this is to just not do coercion during initialization:

```
private void SetValue()
{
    if (IsInitialized)
    {
        double minimum = Minimum ?? double.MinValue;
        double maximum = Maximum ?? double.MaxValue;

        var newValue = MathUtilities.Clamp(Value, minimum, maximum);
        System.Diagnostics.Debug.WriteLine($"Coercing TestChildControl.Value from {Value} to {newValue}");

        Value = MathUtilities.Clamp(Value, minimum, maximum);
    }
}
```

And then call `SetValue` when `Initialized` fires.

I still need to work out how this works in WPF, but I suspect it's because of the way their property coercion works. It's rather more complex than ours. But also WPF-style coercion won't work well with direct properties so I'm not sure it could be ported to Avalonia without causing problems.

**Comment by igorstefus** [comment]
> When you say "default value" here, what do you mean? Do you mean 75 in this case?
> The reason 75 never arrives is because after the coercion is run, Value is no longer 75.

Yes 75 (initial value is probably better term). But then if this is the case, it means binding is already initialized for Value property (since 1 is sent back to view model)? My understanding was that Value was 0 since binding was not yet initialized. Is there any reason why initial value (75) is not sent on binding initialization (before value correction)? Further more what would be effect of preventing any updates to the view model until initial value is sent to the control? 

Just trying to understand it better so I can predict potential problems :).

**Comment by grokys** [comment]
>  Is there any reason why initial value (75) is not sent on binding initialization (before value correction)?

Yes, because your control is setting it in `SetValue` before the initial value has a chance to propagate,

I'm not sure how we could fix this in Avalonia. The problem is that the behavior of your control depends on which order the properties are set in. My feeling at the moment is that the only proper way to fix it is to wait until initialization has finished before coercing the values, as I suggested in https://github.com/AvaloniaUI/Avalonia/issues/2657#issuecomment-504488605

**Comment by grokys** [comment]
Another fix you might want to try is just binding one-way in `TestChildControl` if possible.

**Comment by igorstefus** [comment]
Ok thanks.

**Comment by grokys** [comment]
@igorstefus we've just merged https://github.com/AvaloniaUI/Avalonia/pull/2683 which should fix this issue in `Slider`.

**Comment by igorstefus** [comment]
Thanks for letting me know.
