### ISSUE TITLE
Selection is shrunk to a single item under the cursor on right click on ListBox

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#2660]
But it should be several items. I've encountered this bug in AvaloniaILSpy: https://github.com/icsharpcode/AvaloniaILSpy/issues/13

See the implementation of multiselection here: https://github.com/AvaloniaUI/Avalonia/issues/206

**Comment by KvanTTT** [comment]
Unfortunately, it is still reproduced with TreeView control. You can check it in my PR with the new functionality of multiselection https://github.com/AvaloniaUI/Avalonia/pull/2694

**Comment by grokys** [comment]
Ah yes, the PR fixed it for `ListBox` only. I'll reopen and close again when it's fixed for `TreeView`.
