### ISSUE TITLE
Black corners on macOS when using MinWidth or MinHeight

### ISSUE THREAD

**Issue by ForNeVeR** [AvaloniaUI/Avalonia#2665]
Compile this simple program with Avalonia 0.8.0 and run it on macOS (I've tested on Mojave 10.14.5):

```csharp
using Avalonia;
using Avalonia.Controls;
using Avalonia.Logging.Serilog;

namespace avaloniatest
{
    class Program
    {
        public static void Main(string[] args) => BuildAvaloniaApp().Start(AppMain, args);

        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToDebug()
                .UseReactiveUI();

        private static void AppMain(Application app, string[] args)
        {          
            var window = new Window
            {
                MinHeight = 200
            };

            app.Run(window);
        }
    }
}
```

The window shown will have weird black top corners. These corners turn white on screenshots, please see the following (I've specially created a screenshot on black background for the error to be visible):
![image](https://user-images.githubusercontent.com/92793/59563212-04e73700-9061-11e9-88bb-c81bb79e3d21.png)

The strange effect will disappear after the user resizes the window manually, here's the screenshot after resize:
![image](https://user-images.githubusercontent.com/92793/59563229-3a8c2000-9061-11e9-8e08-840ad78a3ac9.png)

The same will happen if I set `MinWidth`.

**Comment by x2bool** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/2069

Seems to be the same issue.

**Comment by ForNeVeR** [comment]
You're right, that's a duplicate. Thanks.
