### ISSUE TITLE
Bindings to Canvas.Left and Canvas.Top sometimes place the element at the incorrect coordinates

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#2669]
I've had this issue since I started using Avalonia in October 2018. It happens extremely infrequently and very randomly, but I finally captured the issue so I can report it:
https://gfycat.com/ColossalThirdGnat
The view in the bottom right randomly jumps to the left, then returns to normal on the next call of location setting.
What I have is a UserControl called PokemonView with a simple Location property:
```cs
        private Point location;
        public Point Location
        {
            get => location;
            set
            {
                location = value;
                OnPropertyChanged(nameof(Location));
            }
        }
```

And in my parent view I have simple bindings in a canvas:
```xaml
    <views:PokemonView Name="Battler1_Right" Canvas.Left="{Binding Location.X}" Canvas.Top="{Binding Location.Y}" Scale="1"/>
    <views:PokemonView Name="Battler1_Left" Canvas.Left="{Binding Location.X}" Canvas.Top="{Binding Location.Y}" Scale="1"/>
    <views:PokemonView Name="Battler1_Center" Canvas.Left="{Binding Location.X}" Canvas.Top="{Binding Location.Y}" Scale="1"/>
    <views:PokemonView Name="Battler0_Center" Canvas.Left="{Binding Location.X}" Canvas.Top="{Binding Location.Y}" Scale="2"/>
    <views:PokemonView Name="Battler0_Left" Canvas.Left="{Binding Location.X}" Canvas.Top="{Binding Location.Y}" Scale="2"/>
    <views:PokemonView Name="Battler0_Right" Canvas.Left="{Binding Location.X}" Canvas.Top="{Binding Location.Y}" Scale="2"/>
```

And every time a PokemonView needs changing I update the location of them all in code (it is inefficient but it is necessary for now before my code is finalized \[yes, this code has been the same since October 2018, lol\]):
```cs
                    case PBEBattleFormat.Triple:
                    {
                        TemporaryFix<HPBarView>("Bar0_Left").Location = new Point(50, 35);
                        TemporaryFix<HPBarView>("Bar0_Center").Location = new Point(204, 35);
                        TemporaryFix<HPBarView>("Bar0_Right").Location = new Point(358, 35);

                        TemporaryFix<HPBarView>("Bar1_Right").Location = new Point(50, 6);
                        TemporaryFix<HPBarView>("Bar1_Center").Location = new Point(204, 6);
                        TemporaryFix<HPBarView>("Bar1_Left").Location = new Point(358, 6);

                        TemporaryFix<PokemonView>("Battler0_Left").Location = new Point(-53, 51);
                        TemporaryFix<PokemonView>("Battler0_Center").Location = new Point(92, 31);
                        TemporaryFix<PokemonView>("Battler0_Right").Location = new Point(221, 76);

                        TemporaryFix<PokemonView>("Battler1_Right").Location = new Point(209, -1);
                        TemporaryFix<PokemonView>("Battler1_Center").Location = new Point(282, 16);
                        TemporaryFix<PokemonView>("Battler1_Left").Location = new Point(362, 8);
                        break;
                    }
```
(If you are wondering what "TemporaryFix" is, it is just an alternative to "FindControl" while #2562 exists, and this bug has been present when I was using FindControl all these months prior)

If I had to guess how often this bug occurred, I'd say once every 1500+ calls to this method. It's really so infrequent that it happens once over several weeks of me programming, and that's why I haven't had proof of this until now.

This also happens with the "HPBarView" in this code you see, because it has the same types of bindings to Canvas.Left and Canvas.Top as PokemonView. It also happens just as infrequently as you probably expected while reading this.

The one that is misbehaving in the example gif is "Battler0_Right", but I think it can happen to any of the 6 PokemonViews and any of the 6 HPBarViews. I can't remember off the top of my head or verify that claim, but I think it can happen to all of them.

I am also unsure if this would happen with Canvas.Right or Canvas.Bottom, since I do not use them anywhere.

**Comment by Kermalis** [comment]
I find it interesting that the scrollbar of the ListBox missed the bottom element (with ScrollIntoView) at the same time this PokemonView was placed at the incorrect location. I should also mention that all of this code to ScrollIntoView and change these locations is on the UI thread. However, that ListBox issue happens once every 20+ messages (which is a lot more frequent than this obviously, so I don't think they are related, but I am pointing it out just in case). I also think there exists an open issue for the ListBox measurement issue, so I didn't create one.

**Comment by grokys** [comment]
I'll keep a look out for this, but it's a bit hard to diagnose the problem without a decent repro :( In the meantime, maybe you could add some debug logging to your positioning code to check that it's not that that's occasionally doing something wrong?

**Comment by Kermalis** [comment]
Well the position code is always as you see there, there are no variables for the positions and the switch statement will always jump to the same case for all calls since the battle format doesn't change at all.

I looked through the Canvas code and also don't see anything that would show problems, so I'm unsure what it could be aside from binding errors or something.
