### ISSUE TITLE
TextWrapping="Wrap" breaks rendering on macOS

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#2671]
If a TextBlock uses TextWrapping, the Window renders black and the UI elements don't respond to clicks.

![image](https://user-images.githubusercontent.com/13300194/59812958-17d36300-9310-11e9-8c0b-f3cf22dd3036.png)

**Comment by maxkatz6** [comment]
Seems to be already fixed.
If it's still reproducible, ping me here, I will reopen.
