### ISSUE TITLE
Reuse DataTemplate(s) in multiple Views

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2688]
I have two or more views that need to share a large number of DataTemplates.
I understand that I could put them into the Application.DataTemplates but the other views don't need them so it seems wasteful to have them loaded when not needed. Also they cannot be easily reused in other applications other than by cut and paste.

Styles can be reused using the StyleInclude markup extension so perhaps a DataTempateInclude markup extension could be considered.

**Comment by trommlbomml** [comment]
Another point is that data templates should be considered as resources which can be included as styles. I you heavily rely on data templates you do not want to pack all of them in a single place but in separated files, e.g. structured in a feature based manner.

I heavily prefer data templates over user control to have a zero-code behind strategy as a must. I also tend to describe my view using viewmodels, ItemsControls and ContentControls automatically detecting views by DataTemplate.DataType. It would be a great boost for coming from WPF to Avalonia having support for this.

**Comment by maxkatz6** [comment]
Similarly, as in WPF you can reuse them with ResourceDicionaries.
First define ResourceDictionary file (MyTemplate.axaml):
```xaml
<ResourceDictionary xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <DataTemplate x:Key="MyTemplate">
         <!-- -->
    </DataTemplate>
</ResourceDictionary>
```

and then include it once in the top level/application like this:
```xaml
<Application.Resources>
    <ResourceInclude Source="./MyTemplate.axaml" />
</Application.Resources>
```

**Comment by maxkatz6** [comment]
Alternatively (untested, but should work), you can do it with code behind (from what I recall, same works in WPF as well):
```xaml
<DataTemplate xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                          x:Class="Namespace.MyTemplate">
         <!-- -->
</DataTemplate>
```
and codebehind
```csharp
namespace Namespace;
public class MyTemplate : DataTemplate { }
```

After that you can add this template to the resources or directly to the control by its type-name.
