### ISSUE TITLE
Raspbian: No Keyboard or Mouse response

### ISSUE THREAD

**Issue by DogWalker3400** [AvaloniaUI/Avalonia#2691]
I took the official tutorial for data binding an transfered the project to the RaspberryPi3 B+.
I can see the check boxes and the button but there is no response when I click the boxes or the button.
The project was published self contained and with the nuget package avalonia.skia.linux.natives 1.68.2.
Is something missing on my Raspberry?
Console Apps without Avalonia are working as expected (keyboard input)

Can anybody help me?

**Comment by norbastic** [comment]
It looks, it is a bug :( #2465

**Comment by kekekeks** [comment]
This should be fixed by https://github.com/AvaloniaUI/Avalonia/commit/24d153932f5b966db5131eaf643eeb3872d5973e try nightly builds

**Comment by DogWalker3400** [comment]
Thank you for your fast answer.

I copied the nuget packages from https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=3074
Linux. Then I replaced the packages in my VS 2017 solution. When trying to install package Avalonia.Desktop the packet Manager had an error: Avalonia.Native was missing in my Directory. I copied this package from Avalonia.Native.OSX to my local directory.

Then I was able to Install Avalonia.Desktop and Avalonia.ReactiveUI.

I was not able to compile the solution: „Unable to resolve type ToDo.Views.TodoListView“

I deleted all custom controls, views, only the main window was in the solution: I could compile and run the empty program (netcoreapp2.1).

Next I added an Avalonia User Control: The XAML Editor opened and immediately an error was thrown: „Unable to resolve type ToDo.Views.TodoListView “ / Invalid Markup in the design view:

<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="AvaloniaTutorial.Views.ToDoListView">
    Welcome to Avalonia!
</UserControl>

The same error is thrown when I want to add a Avalonia Window!

Do I Need another Extension for my VS 2017?
Or how do I change the templates (if they are not compatible with the beta build)?

Thank You!

________________________________
Von: Nikita Tsukanov <notifications@github.com>
Gesendet: Thursday, June 27, 2019 11:01:34 PM
An: AvaloniaUI/Avalonia
Cc: DogWalker3400; Author
Betreff: Re: [AvaloniaUI/Avalonia] Raspbian: No Keyboard or Mouse response (#2691)


This should be fixed by 24d1539<https://github.com/AvaloniaUI/Avalonia/commit/24d153932f5b966db5131eaf643eeb3872d5973e> try nightly builds

**Comment by kekekeks** [comment]
>I copied the nuget packages from

https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed


Not sure about VS designer issues.

**Comment by DogWalker3400** [comment]
OK, I used the same source and updeted to the preview versions.


  *   I am sorry, I get the same error message



________________________________
Von: Nikita Tsukanov <notifications@github.com>
Gesendet: Friday, June 28, 2019 11:40:01 AM
An: AvaloniaUI/Avalonia
Cc: DogWalker3400; Author
Betreff: Re: [AvaloniaUI/Avalonia] Raspbian: No Keyboard or Mouse response (#2691)


I copied the nuget packages from

https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

Not sure about VS designer issues.

**Comment by DogWalker3400** [comment]
One update:

I created one new Avalonia MVVM Project, updated the nuget packages, and tryed to run the app:

Error: „AppBuilder does not contain a Definition for UseReactiveUI and no UseReactiveUI-Extensionmethod was found. Are you missing a reference… It is in the file Program.cs, line 21.

So I added „using Avalonia.ReactiveUI;“ -> turned out to be a failure….

I think I found what’s happening: The .UseReactiveUI() in the version without update is an extension method of AppBuilder.

After the update the Extension method is not found!!


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Von: Nikita Tsukanov <notifications@github.com>
Gesendet: Friday, June 28, 2019 11:40:01 AM
An: AvaloniaUI/Avalonia
Cc: DogWalker3400; Author
Betreff: Re: [AvaloniaUI/Avalonia] Raspbian: No Keyboard or Mouse response (#2691)


I copied the nuget packages from

https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

Not sure about VS designer issues.

**Comment by Gillibald** [comment]
`x:Class="AvaloniaTutorial.Views.ToDoListView"` is wrong -> `x:Class="AvaloniaTutorial.Views.TodoListView`

**Comment by DogWalker3400** [comment]
Project from the scratch:

After inserting a user control without any coding:

<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="AvaloniaApplication4.Views.UserControl2">
    Welcome to Avalonia!
</UserControl>

Unable to resolve type AvaloniaApplication4.Views.UserControl2


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Von: Benedikt Schroeder <notifications@github.com>
Gesendet: Friday, June 28, 2019 12:26:43 PM
An: AvaloniaUI/Avalonia
Cc: DogWalker3400; Author
Betreff: Re: [AvaloniaUI/Avalonia] Raspbian: No Keyboard or Mouse response (#2691)


x:Class="AvaloniaTutorial.Views.ToDoListView" is wrong -> x:Class="AvaloniaTutorial.Views.TodoListView

**Comment by Gillibald** [comment]
Is the XAML added as AvaloniaResource?

**Comment by DogWalker3400** [comment]
Yes

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Von: Benedikt Schroeder <notifications@github.com>
Gesendet: Friday, June 28, 2019 12:41:32 PM
An: AvaloniaUI/Avalonia
Cc: DogWalker3400; Author
Betreff: Re: [AvaloniaUI/Avalonia] Raspbian: No Keyboard or Mouse response (#2691)


Is the XAML added as AvaloniaResource?

**Comment by kekekeks** [comment]
`Unable to resolve type AvaloniaApplication4.Views.UserControl2`
Check if `UserControl2` class actually exists in `AvaloniaApplication4.Views` namespace. There might be an issue in control file templates, or something

**Comment by DogWalker3400** [comment]
No, sorry the fool was me: I am used to Code with WPF and VS 2017. In very rare cases you need to recompile, but in Avalonia a recompile after inserting a window helps to get rid of the error Messages.

So I can continue my tests with my Raspbery…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Von: Nikita Tsukanov <notifications@github.com>
Gesendet: Friday, June 28, 2019 12:43:46 PM
An: AvaloniaUI/Avalonia
Cc: DogWalker3400; Author
Betreff: Re: [AvaloniaUI/Avalonia] Raspbian: No Keyboard or Mouse response (#2691)


Unable to resolve type AvaloniaApplication4.Views.UserControl2
Check if UserControl2 class actually exists in AvaloniaApplication4.Views namespace. There might be an issue in control file templates, or something

**Comment by DogWalker3400** [comment]
Final Status: On the Raspberry I can click the checkboxes

But the development is time consuming: Add a new Ava Window oder Ava user control and from time to time you cannot compile because the designer is throwing the error message I described and it seems the the designer opened the application dll. When you compile: Cannot access XY.dll because it is opened in another process. So close VS, open it again and if you are fast enuogh (or opened another tab before Closing VS) you can compile

Thank you all for your help and time!

________________________________
Von: Nikita Tsukanov <notifications@github.com>
Gesendet: Friday, June 28, 2019 12:43:46 PM
An: AvaloniaUI/Avalonia
Cc: DogWalker3400; Author
Betreff: Re: [AvaloniaUI/Avalonia] Raspbian: No Keyboard or Mouse response (#2691)


Unable to resolve type AvaloniaApplication4.Views.UserControl2
Check if UserControl2 class actually exists in AvaloniaApplication4.Views namespace. There might be an issue in control file templates, or something

**Comment by grokys** [comment]
Could you try updating the VS extension? We just released a new version which should fix this problem.

**Comment by DogWalker3400** [comment]
Thank you and sorry for the delay: I was swimming with my dog in an old arm of the Danube…

Yes, the „problem“ that you cannot compile after adding a new Avalonia Window to an existing or new solution is fixed.

Folks, thank you for your fast response!

I will continue developing with Avalionia, bye bye „Mono“


________________________________
Von: Steven Kirk <notifications@github.com>
Gesendet: Friday, June 28, 2019 11:49:53 PM
An: AvaloniaUI/Avalonia
Cc: DogWalker3400; Author
Betreff: Re: [AvaloniaUI/Avalonia] Raspbian: No Keyboard or Mouse response (#2691)


Could you try updating the VS extension? We just released a new version which should fix this problem.
