### ISSUE TITLE
Add mathematical operators to Vector.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#2693]
Our `Vector` struct is missing common mathematical operators such as:

- `Normalize`
- `Dot`
- `CrossProduct`
- `Length`
- `LengthSquared`

There are many others that could be added but these are the main missing ones.

**Comment by Gillibald** [comment]
There are operators for `Dot` and `Length`
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Vector.cs#L69
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Vector.cs#L97

**Comment by JaggerJo** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/2761

**Comment by JaggerJo** [comment]
created a pr - just needs review and merge ✌🏼
