### ISSUE TITLE
TabControl with empty TabItem causes StackOverflowException

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#2699]
So I found out if you have a view containing a `TabControl`, like this one:
https://github.com/MarchingCube/TabControlRepro/blob/master/Views/StackOverflowView.xaml
application will crash due to `StackOverflowException` as `TabItem.Content` will be set to `DataContext`, which in this case will be `StackOverflowViewModel`. This will cause `ViewLocator` to look for a view, and our view will be resolved to `StackOverflowView`, which contains a `TabControl`, and story repeats.

I am not sure if this is intended behavior, I found it a bit confusing at first and I only found it because I just made a few dummy tab controls in my app to test things out and I started getting `StackOverflowException` all over the place.

WPF does not set `Content` to `DataContext` in this scenario.

Repro repository:
https://github.com/MarchingCube/TabControlRepro

cc: @Gillibald @grokys

**Comment by Gillibald** [comment]
Sry that it took me so long to fix this. Just some error on my side caused this. Your Scenario should work after this fix.
