### ISSUE TITLE
RenderTransform style on Path not working

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2704]
When I apply a RenderTransform on a Path control via a Style it has no affect.
v0.8.0

```
<UserControl.Styles>
   <Style Selector="Path.dot">
      <Setter Property="RenderTransformOrigin" Value="200,322"/>
      <Setter Property="RenderTransform">
        <Setter.Value>
          <TranslateTransform X="120" Y="20"/>
        </Setter.Value>
      </Setter>
    </Style>
</UserControl.Styles>

...
   <Canvas>
          <Path Fill="Black" Data="M 199,320 A 2,2 360 1 0 201,320" Classes="dot"/>
   </Canvas>
```

**Comment by Tridy** [comment]
I think it could be connected to the problem that RenderTransformOrigin is not working:

```
<Grid x:Name="LayoutRoot" Background="Orange" HorizontalAlignment="Center" VerticalAlignment="Center" Height="120" Width="120">
    <Canvas RenderTransformOrigin=".5,.5"  HorizontalAlignment="Center" VerticalAlignment="Center" Background="Green" Width="120" Height="120">
      <Canvas.RenderTransform>
        <RotateTransform x:Name="spinnerRotate"  Angle="45" />
      </Canvas.RenderTransform>
    </Canvas>
  </Grid>
```

here is the comparison of AvaloniaUI and WPF with the same transformation:

![render_transform](https://user-images.githubusercontent.com/7138873/63678399-6e1cc080-c7ef-11e9-8c14-f67e53116816.png)

Changing RenderTransformOrigin values does not affect the transformation.

**Comment by kekekeks** [comment]
Our `RenderTransformOrigin` is a `RelativePoint` instead of just a `Point` in WPF, so one can specify both absolute and relative units. 
It accepts different string values than WPF. For `.5,.5` you actually need `50%,50%`. `.5,.5` is treated as "half of the logical pixel" in both directions instead of "half of the control"

**Comment by Tridy** [comment]
> It accepts different string values than WPF. For .5,.5 you actually need 50%,50%

Thanks! I got it working and it works as expected for me.

I guess then it is not connected to the original problem of the Path. Sorry about jumping in here.
