### ISSUE TITLE
Why our current way of handling `Name` is broken

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2712]
Broken scenarios that are expected to work
=========

User control having different names in its own XAML file and in referencing XAML file
-------

```xml
<UserControl x:Class="MyControl" x:Name="foo">
    ....
</UserControl>
```

```xml
<Window>
     <MyControl x:Name="bar" />
</Window>
```

1) what is the value of the Name property of MyControl?
2) where does it unregister itself once detached from the visual tree?
3) which name will it use to unregister itself?

Template should be able to reference elements by name from the parent scope
-------

```xml
<Window>
    <Window.DataTemplates>
         <DataTemplate DataType="...">
                <StackPanel>
                       <TextBox x:Name="foo"/>
                       <TextBlock Text="{Binding #foo.Text}"/>
                       <TextBlock Text="{Binding #bar.Text}"/>
                </StackPanel>
         </DataTemplate>
    </Window.DataTemplate>
    <StackPanel>
        <TextBox x:Name="foo"/>
        <TextBox x:Name="bar"/>
        <Expander Header="Test" Content="{Binding Data}"/>
    </StackPanel>

</Window>
```

- `{Binding #foo.Text}` should resolve the TextBox from the template itself
- `{Binding #bar.Text}` should resolve the TextBox from the window scope
- Bindings from the data template shouldn't be able to see `PART_ContentPresenter` from `Expander.xaml`

This doesn't work and can not work with our current automatic registration voodoo because controls and bindings lack the required context.

Objects outside of the visual tree
----
- One should be able to reference objects like `SolidColorBrush` by name from other parts of the XAML
-  `SolidColorBrush` should be able to reference other objects of the XAML by name

Our current system uses visual tree traversal that doesn't see objects outside of it.

Proposal
======

1) Remove `Name` property entirely
2) Let XAML engine handle name scope registrations
3) Make bindings to get the target scope *stack* from the `IServiceProvider` passed to markup extensions by the XAML engine
4) "UI from code" can and should use actual C# local variables which are more suitable for the task anyway

Part №2 is implemented in https://github.com/AvaloniaUI/Avalonia/pull/2705

**Comment by kekekeks** [comment]
@grokys @Gillibald @jkoritzinsky

**Comment by HankG** [comment]
With no more name property how does one do the compontent-to-component binding like you listed above "{Binding #foo.Text}"?  In code when adding handlers often one is finding controls by name. What is the proposed alternative to that?

**Comment by kekekeks** [comment]
@HankG we'll keep `INameScope` and the corresponding registration logic. `this.Find<TControl>("name")` will continue to work.

**Comment by grokys** [comment]
I think we also decided in gitter to keep the `Name` property as removing it feels like a big breaking change.

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/2705
