### ISSUE TITLE
Setting ZIndex requires window resize to work

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#2714]
Setting `ZIndex` via bindings or code behind doesn’t work. I made a small repro here: https://github.com/MarchingCube/Avalonia/tree/feature/zindex-repro. I also tried to invalidate parent visual, but it does not work either. Only way that actually works is resizing the window as it redraws everything.

Repro is in RenderDemo on Drawing page. I added two sliders bound to `ZIndex` of both ellipses. Could probably make an unit test out of it, but I am out of time this week.

cc: @kekekeks and @grokys as you both worked on `DeferredRenderer`

**Comment by MarchingCube** [comment]
Related to https://github.com/AvaloniaUI/Avalonia/issues/2610

**Comment by MarchingCube** [comment]
I did some research on this issue and I found out why `ZIndex` does not work correctly. This only affects `DeferredRenderer` as it is related to `SceneBuilder`. 

- First issue is that changing `ZIndex` does not notify parent `Panel` that something happened. This is easily fixed, by implementing something similar to existing `AffectsParentXXX` methods.
- Rendering invalidation means that we will ad an entry to a `DirtyVisuals` collection, and later `SceneBuilder` will be notified for each element. Unfortunately update method will not recurse into children of a `Panel`, because `ZIndex` is not even a factor for updating children. Furthermore even if `ZIndex` would be checked, it wouldn't work - since `ZIndex` changes but for children.

WPF deals with that by setting a flag on each `Visual` and traversing upwards, setting flag that subtree needs an update. Later renderer consumes that info, and resets flags. This is obviously more complicated with Avalonia, as it has dedicated render thread so communication must be deferred.

Additionally in WPF `ZIndex` also affects order of visual children, so if we were to reorder controls via `ZIndex` - this order would be also visible in visual tree.

At this point I am not sure what level of compatibility Avalonia wants to have with WPF, but such issues will become more often as people port more advanced controls from WPF.

Pinging @kekekeks and @grokys again, as I can't really work on a fix until we figure out compatibility plan.

**Comment by kekekeks** [comment]
We might want to export Z-Index to the scene graph, since visuals themselves to not have the control over the child rendering. That way we won't have to re-render all of the siblings of the changed visual.

**Comment by MarchingCube** [comment]
What do you mean by exporting Z-Index?

**Comment by kekekeks** [comment]
Saving it in `VisualNode`

**Comment by MarchingCube** [comment]
This will mean that we know if `ZIndex` of particular `VisualNode` changed, but to have any effect we also need to redraw siblings. In my example I have 2 ellipses stacked on each other, if I don't redraw both results would look wrong. Since I can control `ZIndex` of one, lower values will cause it to "hide" underneath.

Parent nodes could check if children `ZIndex` changed and redraw but this will be quite expensive.

**Comment by grokys** [comment]
Looking into this, this is also a problem when reordering `Panel.Children`.

**Comment by grokys** [comment]
Another question re: compatibility - do we want to make `ZIndex` an attached property of `Canvas` as in WPF/UWP instead of a property on `Visual`?

**Comment by kekekeks** [comment]
In WPF ZIndex works with non-Canvas containers Grid. I'd like to keep it that way.

**Comment by grokys** [comment]
Yeah, in WPF it's `Panel.ZIndex` (in UWP `Canvas.ZIndex`). Would `Panel.ZIndex` make sense for us, or should we leave it as-is?

**Comment by Gillibald** [comment]
I think under Wpf panel is responsible to render children in the right order based on the attached ZindexProperty. So as long as inheritance works with the current approach nothing has to change. The scene graph does not need to know the ZIndex. The moment a panel's child's ZIndex diverges from its parent it should be reordered in the child collection based on the ZIndex. VisualChildren is an ordered list.

**Comment by kekekeks** [comment]
> under Wpf panel is responsible to render children in the right order

Our panels don't render child elements, it's the renderer that's responsible for that.

> The scene graph does not need to know the ZIndex

If scene graph is aware of ZIndex, we don't need to re-render all 100 child elements of a canvas, only the one with changed ZIndex.

**Comment by grokys** [comment]
> Our panels don't render child elements, it's the renderer that's responsible for that.

This is the same as WPF. I think what @Gillibald is talking about is that a WPF `Panel`'s children are re-ordered due to changes in ZIndex (which @MarchingCube) also mentioned. 

However this is a red herring. As I mentioned above, re-ordering controls in an Avalonia `Panel`'s children _also doesn't work correctly_ at the moment.

> If scene graph is aware of ZIndex, we don't need to re-render all 100 child elements of a canvas, only the one with changed ZIndex.

Storing `ZIndex` in scene graph nodes is definitely one way to detect changed `ZIndex`, however it has a few downsides:

- We'd essentially be sorting the child collection on each render
- An extra scene node property for every control (which most of the time would be 0)

I'd suggest that a better way to do this would be to [do something similar to WPF](https://github.com/dotnet/wpf/blob/2651715b87f94d1ea1e2d9a0328ab6a2d2dcf6c0/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Visual.cs#L2735), and set a flag when marking the control dirty, e.g.:

```
public void AddDirty(IVisual visual, bool recalculateChildren)
```

This flag would then need to be passed to `SceneBuilder` in order for it to recalculate the child node ordering when necessary.

I think this would give all the advantages of storing the `ZIndex` in the scene graph without the disadvantages,

**Comment by MarchingCube** [comment]
@grokys I thought about this approach, but what happens if:

Example XAML
```xaml
<Grid>
    <Panel>
        <Rectangle/>
    </Panel>
</Grid>
```

- We change `ZIndex` of `Rectangle`, this causes `AddDirty(Panel, true)` since we need to notify parent.
-Somebody changes `Grid` property (`Background`), this causes `AddDirty(Grid, false`). 
- `DirtyVisuals` sort by distance to root, so `Grid` will be the first one to update.
- `SceneBuilder` marks visual subtree of `Grid` as updated, no children are updated as we didn't mark `Grid` for recomputing children (it is expected).
- We try to update `Panel`, but that tree was already updated so it is skipped.

What do we do here - force `Panel` to recompute again?

**Comment by grokys** [comment]
Good point. Thinking out loud, what if, before updating the dirty controls normally, we iterate through the controls with `recalculateChildren` set and simply reorder their existing child nodes?
