### ISSUE TITLE
ContextMenu not open on click between grid controls

### ISSUE THREAD

**Issue by MonkAlex** [AvaloniaUI/Avalonia#2718]
```
    <Grid RowDefinitions="*,Auto" Margin="10" Width="150" Height="300">
      <TextBlock Grid.Row="0" Text="First text"/>
      <TextBlock Grid.Row="1" Text="Second text"/>
      <Grid.ContextMenu>
        <ContextMenu>
          <MenuItem Header="MenuHeader"/>
        </ContextMenu>
      </Grid.ContextMenu>
    </Grid>
```
When click on TextBlock - menu opened
When click on free space between controls - menu not opened

Test on  0.8.1-cibuild0003134-beta

**Comment by jp2masa** [comment]
Try setting `<Grid Background="Transparent" ...`, I think that the `Background` is `null` by default, so hit test ignores it.

**Comment by MonkAlex** [comment]
Thanks, `Background="Transparent"` help.
Its not intuitive, need i close issue?

**Comment by Gillibald** [comment]
That's the expected behavior

**Comment by jp2masa** [comment]
I agree it's not really intuitive, I also had that problem and had to read the source to understand what was happening. But I also think it makes sense not to hit test visuals with `Background == null`. Maybe leave this open to add that to the docs?

**Comment by MonkAlex** [comment]
> 
> 
> That's the expected behavior

But when its ListBox and this Grid selected as item (has visual selection), but context menu clicked _sometimes_ -- look very bad.

**Comment by grokys** [comment]
This is the same behavior that WPF and UWP have too, as far as I know.

**Comment by MonkAlex** [comment]
Test WPF - work fine in all grid (blue border) area:
![изображение](https://user-images.githubusercontent.com/6784764/61409001-6285d200-a8f2-11e9-966c-1bcf8078ccd6.png)

**Comment by grokys** [comment]
This seems to be that although the `TextBlock` is filling the first grid row, the hit-test area is limited to the area that actually contains text. In WPF, the hit-test area is the whole of the `TextBlock`.

We should change our behavior to match that of WPF's.

**Comment by grokys** [comment]
This seems to be because WPF's `TextBlock` overrides `HitTestCore`: https://github.com/dotnet/wpf/blob/b71b8b339ce667d6e49ff08aea3bc8d148a1c851/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextBlock.cs#L1717-L1733

We don't have an equivalent mechanism for overriding hit-testing at the moment I don't think. In the meantime you could just set your `TextBlock`'s background to `Transparent` and it should work.

**Comment by MonkAlex** [comment]
@grokys thanks.

Because `Background =" Transparent "` helps, I close the issue.
