### ISSUE TITLE
How make windows style none?

### ISSUE THREAD

**Issue by ahvahsky2008** [AvaloniaUI/Avalonia#2721]
Subj

**Comment by Gillibald** [comment]
The first step would be setting `HasSystemDecorations=false` on your window

**Comment by ahvahsky2008** [comment]
@Gillibald thx, but its no draggable. I cannot move windows

**Comment by Gillibald** [comment]
You have to implement managed dragging yourself. https://github.com/VitalElement/AvalonStudio.Shell/blob/e6b8d79a340607f556f0d3933ab0518bdc94241f/src/AvalonStudio.Shell/Controls/MetroWindow.cs

**Comment by kekekeks** [comment]
While it's possible to have completely custom decorated window (see [1](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/DecoratedWindow.xaml) and [2](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/DecoratedWindow.xaml.cs)), consider not doing this unless absolutely required. It severely breaks the user experience on macOS and various Linux desktop environments.
