### ISSUE TITLE
Auto sizing TextBox does not behave correctly after pasting large text

### ISSUE THREAD

**Issue by garyhertel** [AvaloniaUI/Avalonia#2723]
Currently, if you have an auto sizing TextBox without a width defined, when you paste text larger than the TextBox width the cursor and pasted text is not position correctly.

The ideal scenario is the TextBox resizes to fit all the text, with the caret positioned at the far right side of the TextBox. However, currently Avalonia will resize the TextBox to almost fit the text, and it will position the caret to the previous max width instead of the new max width. The latter is especially problematic as it tends to disorient users as they don't quite understand what's going on since they can only see a little bit of the text.

Testing this same thing out in WPF, it matches the ideal behavior with the cursor positioned at the far right of the TextBox and everything fitting exactly.

**Comment by Gillibald** [comment]
Note: We have to test this against the new TextLayout that is available soon

**Comment by grokys** [comment]
Fixed by #3075
