### ISSUE TITLE
Support nested types in DataTemplate.DataType

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#2725]
Currently TypeResolver goes crazy - raises exception (for 0.8.x version [clarification: only for F# modules that don't have namespace]) and gives error in compile time from the master branch.

Just to show some sample. This kind of code is perfectly valid in WPF:

```xml
        <ItemsControl ItemsSource="{Binding Items}">
            <ItemsControl.ItemTemplate>
                <DataTemplate DataType="{x:Type local:SomeClass+Data}">
                    <TextBlock Text="{Binding Value}" />
                </DataTemplate>
            </ItemsControl.ItemTemplate>
        </ItemsControl>
```

```csharp
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            DataContext = this;
        }

        public IEnumerable<Data> Items { get => Enumerable.Range(0, 10).Select(_ => new Data()); }
    }

    public static class SomeClass
    {
        public class Data
        {
            public string Value { get; } = "Hello World";
        }
    }
```

While this is a rare use-case for C# in F# world it's common. Instead (or additional to) of using namespace, types are grouped in modules, like this:

```fs
module Test = 
    type SomeType = { Id : int; Value : string }
```

So I think it would be very nice to have support for this scenario.

**Comment by FoggyFinder** [comment]
Slightly changed code:

```xaml
  <ItemsControl Items="{Binding Items}">
    <ItemsControl.ItemTemplate>
      <DataTemplate DataType="{x:Type local:SomeClass+Data}">
        <TextBlock Text="{Binding Value}" />
      </DataTemplate>
    </ItemsControl.ItemTemplate>
  </ItemsControl>
```

 is works in 0.8 but doesn't for latest version (0.8.999-cibuild0003188-beta).

**Comment by FoggyFinder** [comment]
Any updates?

**Comment by FoggyFinder** [comment]
Any news? :-)

**Comment by BAndysc** [comment]
+1

**Comment by grokys** [comment]
Investigating this now, looks like this works fine in unit tests, which makes it harder to fix...

**Comment by yankun** [comment]
Using 11.04 I'be autocompletion for the + syntax, but getting a compile error that the type can't be found. Still not solved?

**Comment by timunie** [comment]
@yankun issue is open and milestone is 11.x, so guess, no it's not available yet and doesn't have high priority seems like.

**Comment by nuc134r** [comment]
I have written a replacement `x:Static` markup extension which supports nested classes in the meantime. It uses WPF code. Can be used in the meantime

https://gist.github.com/nuc134r/a28efe6363ac5228df7d12d97af03f8d

Just remove the `x:` in your code and let autocomplete import it's XAML namespace (wherever you put it) and you're ready to go

**Comment by timunie** [comment]
@nuc134r if you have an idea how to properly support this, consider to file a PR instead of relying on a workaround. Community support is appreciated as far as I can tell.

**Comment by nuc134r** [comment]
> @nuc134r if you have an idea how to properly support this, consider to file a PR instead of relying on a workaround. Community support is appreciated as far as I can tell.

It looks like PRs which seem to exactly fix the issue are already filed

https://github.com/AvaloniaUI/Avalonia/pull/7354
https://github.com/kekekeks/XamlX/pull/54

**Comment by maxkatz6** [comment]
@nuc134r keep in mind, that this workaround will use reflection, and these static members might be trimmed out from the assembly if they are not used compile time.

**Comment by Dragorn421** [comment]
Just to make sure, is the current state of things in Avalonia that you cannot use a nested class to set DataType explicitly?

**Comment by DmitriiShamrikov** [comment]
I'm using Avalonia 11.2.3 but this is still not working. Any idea when the fix going to be published?

**Comment by timunie** [comment]
if 11.2 doesn't have it, please try nightly, In this case should be shipped with 11.3

**Comment by Nshtk** [comment]
Still not working as of 11.3.4.

EDIT: Nevermind, I accidentally typed x:Data*t*ype instead of x:Data*T*ype, Avalonia needs better integration with VS Code to avoid these kind of errors. Autocomplete is not working :(

**Comment by lextm** [comment]
@Nshtk [This fork](https://marketplace.visualstudio.com/items?itemName=lextudio.vscode-axaml) resolved many known issues with autocompletion in VS Code, so you might try that out.

There are other gaps in the open source AXAML language server today, which Avalonia team announced that will be resolved by their closed-source new implementation. We will see what happens next.

**Comment by Nshtk** [comment]
@lextm, thanks for the suggestion, will try that!
