### ISSUE TITLE
TextBox pointerover not working

### ISSUE THREAD

**Issue by K0beBean** [AvaloniaUI/Avalonia#2726]
Hi, I'm trying to change the borderbrush on textboxes on pointerover, but it remains a black border. The pointerover works for the buttons so I'm not sure what I'm doing wrong

      <Style Selector="Button:pointerover">
         <Setter Property="Background" Value="red"/>
       </Style>
      <Style Selector="TextBox">
        <Setter Property="BorderBrush" Value="red"/>
      </Style>
      <Style Selector="TextBox:pointerover">
        <Setter Property="BorderBrush" Value="blue"/>
      </Style>

**Comment by Abdulbaqi-Alshareef** [comment]
Because in the default theme for Textbox targeting border inside template to change the borderbrush you can't change it that way but you can do this way :
```
<Style Selector="TextBox:pointerover /template/ Border#border">
    <Setter Property="BorderBrush" Value="Blue"/>
</Style>
```

Have a look at this:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Default/TextBox.xaml

**Comment by Gillibald** [comment]
Hmm I should fix these styles. They shouldn't be targetting controls directly.

**Comment by K0beBean** [comment]
> Because in the default theme for Textbox targeting border inside template to change the borderbrush you can't change it that way but you can do this way :
> 
> ```
> <Style Selector="TextBox:pointerover /template/ Border#border">
>     <Setter Property="BorderBrush" Value="Blue"/>
> </Style>
> ```
> 
> Have a look at this:
> https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Default/TextBox.xaml

ah I see, thanks. I used something similar for another button that wasnt working (/template/ ContentPresenter) but ContentPresenter didnt work for TextBox either

**Comment by Gillibald** [comment]
The proposed fix to this is the way to override default style selectors so nothing to fix here. Everything behaves as expected. Maybe we will find a way to change this in the future.

**Comment by Odepax** [comment]
Shouldn't this `TemplateBinding` make it all automatic and transparent?

https://github.com/AvaloniaUI/Avalonia/blob/30985019430fa5a5d496b1979a69d612c9eebc2f/src/Avalonia.Themes.Default/Button.xaml#L14

**Comment by maxkatz6** [comment]
There is a reason, why this syntax won't work for Buttons https://github.com/AvaloniaUI/Avalonia/pull/2662#issuecomment-515764732
Local value will have higher priority than any other value from the styles. 
Same reason is for any other control.
