### ISSUE TITLE
DoubleTapped not catched by ListBoxItem

### ISSUE THREAD

**Issue by MonkAlex** [AvaloniaUI/Avalonia#2730]
Has listbox with items, want to catch double click.
Event not raised, because:
https://github.com/AvaloniaUI/Avalonia/blob/9ebeeb0efb5fa940e1e285080f0ad4be0c68c88a/src/Avalonia.Input/Gestures.cs#L49-L52
https://github.com/AvaloniaUI/Avalonia/blob/fc193e6e27ee69e5d7c8c4f57665d1f44f09191a/src/Avalonia.Controls/ListBox.cs#L125-L133

Then, only MouseButton.Middle raise DoubleTapped event.

**Comment by grokys** [comment]
Hmm, yeah, should we raise double-clicked events when the click event was handled by a control? Need to look into what other frameworks do.

**Comment by grokys** [comment]
This was caused by #2580, which I think is incorrect behavior. See https://github.com/AvaloniaUI/Avalonia/pull/2580#issuecomment-514801845

**Comment by MonkAlex** [comment]
Local hotfix by:
```
  public class ListBox : global::Avalonia.Controls.ListBox, IStyleable
  {
    Type IStyleable.StyleKey => typeof(global::Avalonia.Controls.ListBox);

    protected override void OnPointerPressed(PointerPressedEventArgs e)
    {
      base.OnPointerPressed(e);
      e.Handled = false;
    }
  }
```
