### ISSUE TITLE
Handle applicationShouldTerminate

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2736]
To properly handle system shutdown or user clicking on Quit menu item, we need to handle [applicationShouldTerminate](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428642-applicationshouldterminate?language=objc).

The implementation should go through all opened windows and attempt to gracefully close them. If any window cancels the exit, the process should stop.

We should also add 
```
interface INativeDesktopLifetimeProvider
{
     event  EventHandler<CancelEventArgs> OnExit;
}
```
So it can be wired up with `ClassicDesktopApplicationLifetime` or be used separately

**Comment by kekekeks** [comment]
@danwalmsley

**Comment by mat1jaczyyy** [comment]
Keep in mind if an application refuses to quit during shutdown, macOS can cancel the cancel the shutdown sequence and tell the user that "this app is preventing shutdown" which gives the user an opportunity to cleanly save their work and reexecute the shutdown. This can be utilized in cases where a user is prompted to save their work, but selects the 'Cancel' option instead.

**Comment by Gillibald** [comment]
I think Windows supports this as well.

https://docs.microsoft.com/de-de/windows/win32/shutdown/wm-queryendsession

https://docs.microsoft.com/de-de/windows/win32/shutdown/wm-endsession

**Comment by mat1jaczyyy** [comment]
I've noticed there was some progress with NativeMenu, what's the state of this right now?
