### ISSUE TITLE
Resource could not be found when adding image as asset

### ISSUE THREAD

**Issue by colinparks** [AvaloniaUI/Avalonia#2741]
I'm trying to add an image to my project as an asset. I am following the MVVM template and the Assets guide on the Quickstart page. I have my image in a folder called Assets in my project directory and have included assets in my project file. 

The image is present in the folder:
Assets\image.png
which is in my project directory

In my .csproj file I have:
`<AvaloniaResource Include="Assets\*" />`

In my view I have:
`<Image Source=:image.png" />`

The error I am getting is:
Could not convert object 'imapge.png' (of type System.String) to {clr-namespace:Avalonia.Media.Imaging;assembly=Avalonia.Visuals}IBitmap: The resource image.bmp could not be found.

**Comment by ahopper** [comment]
I think it should be <Image Source="/Assets/image.png" />
https://github.com/AvaloniaUI/Avalonia/blob/c637d616ba26584e9add2cd09d58788be7833b06/samples/ControlCatalog/Pages/ImagePage.xaml#L21

**Comment by colinparks** [comment]
That worked, I thought that was one of the first things I tried.  Thanks.

**Comment by colinparks** [comment]
This worked on one of my views, but when I try to add the image to the other view, it gives me:
`Portable.Xaml.XamlObjectWriterException: 'Could not convert object '/Assets/Help.bmp' (of type System.String) to {clr-namespace:Avalonia.Media.Imaging;assembly=Avalonia.Visuals}IBitmap: Relative uris for 'resm' scheme aren't supported; resm:ControlUnitGenerator.Main.File.Settings.SecondGenLoosePiece.SecondGenLoosePieceView.xaml?assembly=ControlUnitGenerator uses resm'`

Any idea why it's not allowing me to add it to this view?

**Comment by Abdulbaqi-Alshareef** [comment]
This works for me
```
<Image Source="resm:YourNameSpace.Assets.YourImage.png?assembly=YourAssemblyName"/>
```
http://avaloniaui.net/docs/quickstart/assets

**Comment by colinparks** [comment]
After I changed the Build Action to Embedded Resource this worked. Thanks.

**Comment by zhanxh** [comment]
Can't use PNG format images.

**Comment by timunie** [comment]
@zhanxh don't answer closed issues. Better open a new Q&A in discussions with sample code or join us on Telegram

**Comment by gaino1122** [comment]
Change The build action to Avalonia Resource and its Fixed
