### ISSUE TITLE
OpenFolderDialog freezes the program

### ISSUE THREAD

**Issue by tommaier123** [AvaloniaUI/Avalonia#2742]
Here is a simple example with a OpenFolderDialog which freezes the program. Originally I tried it without the Task.Run() and instead used await for the result but that had the same issue. So I switched to this code after taking a look at [https://github.com/AvaloniaUI/Avalonia/issues/1837](https://github.com/AvaloniaUI/Avalonia/issues/1837)

```
 public void SelectFolder()
        {
            var task = Task.Run(() =>
            {
                var dialog = new OpenFolderDialog()
                {
                    Title = "Select Folder...",
                    InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)
                };

                var result = dialog.ShowAsync(Application.Current.MainWindow);
                if (result == null)
                {
                    return "Canceled";
                }
                else
                {
                    return "Selected";
                }
            });

            this.statusUpdate = task.GetAwaiter().GetResult();
        }

```
I am running on Win7 with .net core 3.0 (I also tested .net core 2.1)

**Comment by kekekeks** [comment]
It's not the dialog freezing the program, it's `task.GetAwaiter().GetResult();` causing a deadlock. Use async/await. For more details see [TAP.docx](https://download.microsoft.com/download/5/B/9/5B924336-AA5D-4903-95A0-56C6336E32C9/TAP.docx).

**Comment by tommaier123** [comment]
> 
> 
> It's not the dialog freezing the program, it's `task.GetAwaiter().GetResult();` causing a deadlock. Use async/await. For more details see [TAP.docx](https://download.microsoft.com/download/5/B/9/5B924336-AA5D-4903-95A0-56C6336E32C9/TAP.docx).

My first approach was using async/await which didn't work. I also tried commenting out the `task.GetAwaiter().GetResult();` and it still froze.

```
public async void SelectFolder()
        {
            var dialog = new OpenFolderDialog()
            {
                Title = "Select Folder...",
                InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)
            };

            var result = await dialog.ShowAsync(Application.Current.MainWindow);
            if (result == null)
            {
                statusUpdate = "User canceled request";
            }
            else
            {
                statusUpdate = "User selected";
            }
        }
```

**Comment by christosk92** [comment]
@tommaier123 A bit late.. But for anyone who is also stuck with this. 
What worked for me is adding .ConfigureAwait(false)

`dialog.ShowAsync(GetWindow()).ConfigureAwait(false);`

**Comment by tommaier123** [comment]
Thanks for the tip. I'll try it out.

**Comment by rbnswartz** [comment]
For anyone that was like me trying to do this in a non-async method if you put it in a async method then you can just use ShowAsync without needing to do anything else.
