### ISSUE TITLE
Grid layout issues with elements bigger than constraint size

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#2746]
After updating to newer Avalonia that has WPF `Grid` integrated some controls in my app started shifting content in a weird way. In the beginning I thought this may be how WPF `Grid` works, but same XAML works just fine in WPF (also this XAML can just be pasted into WPF or Avalonia, as it works in both).

```xaml
<Grid Width="120" Height="120">

        <Border BorderBrush="#292e34" BorderThickness="1" Background="#494B4D" Margin="2">

            <Grid >
                <Grid.RowDefinitions>
                    <RowDefinition Height="*"/>
                    <RowDefinition Height="Auto"/>
                    <RowDefinition Height="Auto"/>
                </Grid.RowDefinitions>

                <DockPanel Grid.Row="0">

                    <Border>
                        <Border.Background>
                            <SolidColorBrush Color="Red" />
                        </Border.Background>
                        <Rectangle Width="16" Height="16" Fill="Blue" />
                    </Border>
                </DockPanel>

                <Rectangle Grid.Row="1" Height="1" Fill="#292e34" />

                <Border Grid.Row="2" Background="#494B4D" Padding="2">
                    <TextBlock HorizontalAlignment="Center" Text="Very very very very very very very long text" />
                </Border>

            </Grid>

        </Border>

    </Grid>
```

Avalonia:
![image](https://user-images.githubusercontent.com/2588062/61378149-034da080-a8a5-11e9-90da-5ac004afc34e.png)

WPF:
![image](https://user-images.githubusercontent.com/2588062/61378168-11032600-a8a5-11e9-8198-f8e6664615a6.png)

Any idea what might be going on there? Also if I add `MaxWidth="112"` to `TextBlock` it looks the same as WPF.

cc: @jmacato as you ported `Grid` from WPF

**Comment by jmacato** [comment]
Will look into this next week, thanks for reporting this. 
Though be it as it may, we need more unit tests for Grid, StackPanel & WrapPanel... I hope WPF releases theirs soon so that we can adopt theirs.

**Comment by Abdulbaqi-Alshareef** [comment]
> 
> 
> Will look into this next week, thanks for reporting this.
> Though be that as it may, we need more unit tests for Grid, StackPanel & WrapPanel... I hope WPF releases theirs soon so that we can adopt theirs.

Could Xamarin.Forms Tests be helpful?
https://github.com/xamarin/Xamarin.Forms/tree/master/Xamarin.Forms.Core.UnitTests

**Comment by jmacato** [comment]
@Abdulbaqi-Alshareef that's a very helpful resource, thanks so much for linking that :)

**Comment by MarchingCube** [comment]
@jmacato Hey, do you have time to check this issue this week? I tried to port devtools console from @grokys devtools repo, but it seems that control growing outside of constraint just breaks grid layout completely.

**Comment by grokys** [comment]
Seems to be caused by #2431 which removed the `.Constrain(availableSize)` call in `Layoutable.Measure`. Now that the WPF source is available, I can see i that WPF _does_ in fact constrain measure to `availableSize` and `Grid` relies on this.

The difference is that WPF has two "Bounds": layout bounds and render bounds and they can be different in the case where a control cannot fit in `availableSize`.

We need to at least add the constraint back in, and think about whether we want to have two bounds like WPF.

**Comment by jmacato** [comment]
@MarchingCube Sorry for not reporting on time, i repro'd the issue and I was really oblivious what's going on and why the bug happened. I forgot to use `git bisect` and didn't have time really digging into it last week. Thanks once again sir @grokys for noticing whats wrong on this issue.

**Comment by jmacato** [comment]
I also think this would make a good unit test case so perhaps i could write that one later.
