### ISSUE TITLE
Changing SolidColorBrush opacity on binding does not render immediately

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#2755]
Hey,
I'm using this code to control my window's background and when I change the opacity in the view model it will not change the actual gui. I also noticed that the next time I change anything that will trigger changes in the gui it will also change the opacity, so I'm assuming the problem is that changing opacity does not call the render method 
`   <Border.Background>
            <SolidColorBrush Color="{Binding AppearanceViewModel.BackgroundColor.Color}"
                             Opacity="{Binding AppearanceViewModel.WindowOpacity}" />
        </Border.Background>
`

**Comment by kekekeks** [comment]
@jmacato @grokys We really need a proper resource invalidation infrastructure. The [approach I've used in image effects PR](https://github.com/AvaloniaUI/Avalonia/pull/2622/files#diff-bf115e9ca52b3e4cc83b0ce715615ffeR38) could work, but it's not a long term solution, DeferredRenderer should handle brush/bitmap invalidation internally, so only nodes in the scene graph are subscribed.
