### ISSUE TITLE
Fullscreen not working on macOS or Linux

### ISSUE THREAD

**Issue by markmcgookin** [AvaloniaUI/Avalonia#2759]
I have a very simple app that I want to run full screen. I can't seem to get it to work on either my mac dev machine or the linux (raspberry pi) machine that I am running it on. 

`WindowState="Maximized"`

and setting

```
this.HasSystemDecorations = false;
this.WindowState = WindowState.Maximized;
this.Topmost = true;
this.WindowStartupLocation = WindowStartupLocation.CenterScreen;
```

On the MainWindow.xaml(.cs) doesn't seem to work at all. It does hide system decorations and jump to the screen, but it's not fullscreen.

**Comment by kekekeks** [comment]
On Linux the full screen mode can not be achieved by combination of the lack of decorations  and maximizing (`_NET_WM_STATE_MAXIMIZED_VERT`+`_NET_WM_STATE_MAXIMIZED_HORZ`) the window. A separate `_NET_WM_STATE_FULLSCREEN` state is required. 

On OSX, I believe, we need [NSWindow::toggleFullscreen](https://developer.apple.com/documentation/appkit/nswindow/1419527-togglefullscreen?language=objc)

**Comment by markmcgookin** [comment]
Yeah, if it could just be a window state, then a check within that to determine which OS it is running on and do the appropriate command

**Comment by kekekeks** [comment]
For now you can copy-paste [SendNetWMMessage](https://github.com/AvaloniaUI/Avalonia/blob/90f6d849bd48bfe6749d49a9f85269ec7627a489/src/Avalonia.X11/X11Window.cs#L818) and required classes and use it [like this](https://github.com/AvaloniaUI/Avalonia/blob/90f6d849bd48bfe6749d49a9f85269ec7627a489/src/Avalonia.X11/X11Window.cs#L494).

**Comment by markmcgookin** [comment]
Thanks! I'll try that.

**Comment by Norc89** [comment]
Does exist any new approach ?

**Comment by danwalmsley** [comment]
We now have WindowState = FullScreen.

**Comment by tjacobhi** [comment]
@danwalmsley, I am not seeing a WindowState.FullScreen. I only see WindowState.Normal, WindowState.Maximized, and WindowState.Minimized. Am I missing anything? It looks like WindowState.cs hasn't been modified in this repository for 4 years. How do I use this feature?

**Comment by dev-bre** [comment]
The Fullscreen option doesn't show up in the possible choices for me and even if I set it, it doesn't compile.

**Comment by dougmill** [comment]
> The Fullscreen option doesn't show up in the possible choices for me and even if I set it, it doesn't compile.

It's only in pre-release at this point.

**Comment by bogeyorpar** [comment]
I have the same issue -- can not hide taskbar when running on Ubantu. When will the WindowState = FullScreen be released? Or, how do I install the pre-release version of AvaloniaUI?

**Comment by rstm-sf** [comment]
You can use the [preview version](https://www.nuget.org/packages/Avalonia/0.10.0-preview6)

**Comment by bogeyorpar** [comment]
@rstm-sf , thanks! It works now with FullScreen!

**Comment by phillijw** [comment]
> For me, it worked to set topmost as first statement. So while
> 
> ```
> this.HasSystemDecorations = false;
> this.WindowState = WindowState.Maximized;
> this.Topmost = true;
> ```
> 
> does not show the window in full screen,
> 
> ```
> this.Topmost = true;
> this.HasSystemDecorations = false;
> this.WindowState = WindowState.Maximized;
> ```
> 
> will do it.

why would the order matter?

Has anyone noticed that desktop widgets show through fullscreen mode?
