### ISSUE TITLE
WPF-style styles

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2765]
Basically we need a way for controls to have their *own* styles that would provide the control theme.

```xml
<Button>
    <Button.Style>
         <Style> <!-- no Selector here -->
         </Style>
    </Button.Style>
</Button>
```

```xml

<ResourceDictionary>
   <ResourceDictionary.Resources>
        <!-- 
              Same logic as in WPF, TargetType is *only* allowed
              in resources context (enforced by compiler).
              We can have `BasedOn` as well
         -->
       <Style TargetType="{x:Button}" x:Key="{x:Button}"> 
       </Style>
   </ResourceDictionary.Resources>
</ResourceDictionary>
```

If there is no Style manually specified and no Style found in Resources, the system should use the *default* style for such control.

"Own" styles should work alongside with our current resource system, it should be possible to set the own style using a css style, e. g.

```xml
<Style Selector="Button.themed">
     <Setter Property="Style" Value="{StaticResource MyThemeButtonStyle}"/>
</Style>
```

This feature will
- allow us to have proper default styles for controls without the need to add a `StyleInclude` for every 3rd party library
- simplify porting WPF code

**Comment by kekekeks** [comment]
Assigning the default style to a control

On the low level it would
```cs
interface IHaveDefaultStyle
{
       Style GetDefaultStyle();
}
```
implemented by the control.

From user point of view it would be a XAML file looking like this in the same assembly as the control
```xml
<Style x:DefaultStyleFor="{x:Type MyControl}">
</Style>
```
It would be wired into MyControl via IHaveDefaultStyle implementation generated by the XAML compiler

**Comment by kekekeks** [comment]
Since our xaml loader depends on `Avalonia.Controls` we have some kind of a chicken and egg problem. To resolve that, we'll have to move all our default styles to `Avalonia.Markup.Xaml` assembly and write them like this:
```xml
<Style x:Class="Avalonia.Markup.Xaml.DefaultStyles.DefaultButtonStyle" TargetType="x:Type Button">
```

```cs
internal class DefaultButtonStyle : Style
{
}
```

it should allow us to reference such styles from C# code like this:

```cs
new Dictionary<Type, Style>
{
     [typeof(Button)]= new DefaultButtonStyle();
}
```

which could be used to resolve styles for controls from `Avalonia.Controls`.

**Comment by grokys** [comment]
I spoke about a way to specify default themes here: https://github.com/AvaloniaUI/Avalonia/issues/1883

How does this compare?

**Comment by kekekeks** [comment]
Superseded by https://github.com/AvaloniaUI/Avalonia/issues/2769
