### ISSUE TITLE
Can't drag and drop files

### ISSUE THREAD

**Issue by JakubK** [AvaloniaUI/Avalonia#2772]
Hello!
I'm trying to get to work this particular part of Samples (DragAndDropPage):

https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/DragAndDropPage.xaml

https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/DragAndDropPage.xaml.cs

And I can only Drag Text from the control that is placed on that Page, I can't drag files.
The Drop panel acts like it's set to not allow drop but it's set to true - dropping dragged textblock works.
Is something missing from this linked code to make it possible to drag files too ? Dragging files doesn't trigger any of the events handled in the code-behind.

I'm running on .NET Core with Windows 10 if that's important.

**Comment by kekekeks** [comment]
#2635
