### ISSUE TITLE
[0.7 -> 0.8.1] Stackpanel backgrounds in Comboboxes/Dropdowns can no longer be styled

### ISSUE THREAD

**Issue by 2haloes** [AvaloniaUI/Avalonia#2773]
I've been updating my application to Avalonia 0.8.1 which has been mostly a smooth ride, however, I cannot get the ComboBox drop down background to change it's styling even if I set the property inline.

Style code:

```
 <Style Selector="StackPanel"> 
      <Setter Property="Background" Value="{Binding selectedTheme.stackBackgroundCol}" />
</Style>
```

With Avalonia 0.7, this would change the colour with the selectedTheme value, however, on Avalonia 0.8.1, this does not happen and is the only element within my application that this has stopped working for. 

I've experimented, and tried to force the background property to change but it doesn't, no matter what I've tried: 
```
<ComboBox.ItemTemplate  Background="{Binding selectedTheme.stackBackgroundCol}" >
    <DataTemplate>
        <StackPanel Background="{Binding selectedTheme.stackBackgroundCol}" >
            <TextBlock Text="{Binding}" TextAlignment="Center" Background="{Binding selectedTheme.stackBackgroundCol}" />
          </StackPanel>
    </DataTemplate>
</ComboBox.ItemTemplate>
```

I didn't normally use DataTemplates for ComboBoxes but I thought it might have helped, it hasn't.

The foreground colour does still change as expected but this has caused the issue of text in ComboBoxes being almost invisible unless they're highlighted

[Here is an Imgur album to show the issue better than I can explain it](https://imgur.com/a/AexIUQ6)

 I hope I've provided enough information on the issue but if I have missed something, i can post it below.

Edited post as I am using version 0.8.1, not 0.8.0

**Comment by grokys** [comment]
Hi @2haloes,

What control are you wanting to style? Your selector is `StackPanel` - is this referring to the `StackPanel` in your `DataTemplate` above?

If so, simply setting `StackPanel.Background` as you do in your example works:

```
<ComboBox x:Name="fontComboBox"  SelectedIndex="0">
    <ComboBox.ItemTemplate>
        <DataTemplate>
            <StackPanel Background="Red">
                <TextBlock Text="{Binding Name}" FontFamily="{Binding}" />
            </StackPanel>
        </DataTemplate>
    </ComboBox.ItemTemplate>
</ComboBox>
```

![image](https://user-images.githubusercontent.com/1775141/61928673-804dd980-af79-11e9-820c-f6d7f65a4074.png)

**Comment by 2haloes** [comment]
Thank you for replying, I'm trying to style the drop down that appears after clicking a ComboBox, the background of the whole drop down. The StackPanel selector was used as that was what worked. I hadn't used DataTemplates until this issue occured

I have been able to change the StackPanel background from your example but I've had a few issues with it:

* Binding appears not to work for colour names or RGBA values (Created using Brush.Parse())

Working as shown in your image:  
```
<ComboBox.ItemTemplate>
    <DataTemplate>
       <StackPanel Background="Pink">
           <TextBlock Text="{Binding}" TextAlignment="Center"/>
       </StackPanel>
    </DataTemplate>
</ComboBox.ItemTemplate>
```


Not Working:  
```
<ComboBox.ItemTemplate>
    <DataTemplate>
       <StackPanel Background="{Binding selectedTheme.stackBackgroundCol}">
           <TextBlock Text="{Binding}" TextAlignment="Center"/>
       </StackPanel>
    </DataTemplate>
</ComboBox.ItemTemplate>
```

* I'd like the whole display to have the background colour, not just behind the text, as shown in the image below

![Expected ComboBox display result](https://i.imgur.com/3ayVf7h.png)

* There's multiple ComboBoxes and I would prefer setting the style with all of the other styling options. With this method, I would need to go to each ComboBox instance if a style change was to occur down the line

**Comment by grokys** [comment]
> `<StackPanel Background="{Binding selectedTheme.stackBackgroundCol}">`

I'm guessing this is because the `selectedTheme.stackBackgroundCol` resource is a `Color` and not a `Brush`?

> With Avalonia 0.7, this would change the colour with the selectedTheme value, however, on Avalonia 0.8.1,

Could you show the exact style that worked on 0.7.0?

**Comment by 2haloes** [comment]
I'll make some changes and see if the issue is with the value being the wrong type.

The style used for the DropDown/ComboBox before the update:

```
<Style Selector="DropDown">
  <Setter Property="Foreground" Value="{Binding selectedTheme.foregroundCol}" />
</Style>
<Style Selector="StackPanel">
  <Setter Property="Background" Value="{Binding selectedTheme.stackBackgroundCol}" />
</Style>
```

**Comment by grokys** [comment]
Ok, so you were styling _all_ `StackPanel`s in your application?

**Comment by 2haloes** [comment]
Yes but the only StackPanels seem to be within ComboBoxs, I'll go and make a normal StackPanel and see if that works

The binding colour is an IBrush, converted from a string using Brush.Parse() so that's likely not the issue with binding

**Comment by 2haloes** [comment]
I added a regular `StackPanel` into the application and it functions as expected. The "Hello" and "There" `TextBlock`s within the image are separate and within the `StackPanel`. 

It only seems to not be working within `ComboBox`s

![StackPanel Working](https://i.imgur.com/dD9Wedt.png)

**Comment by grokys** [comment]
Thanks! Ok, I think I understand the problem now :) I'll take a look and see what broke.

**Comment by 2haloes** [comment]
Alright, thank you very much!

**Comment by grokys** [comment]
Apologies for the delay looking into this.

The problem is that the `ComboBox` no longer displays its items using a `StackPanel`; it uses a `VirtualizingStackPanel`.

So the following works:

```
  <Window.Styles>
    <Style Selector="VirtualizingStackPanel">
      <Setter Property="Background" Value="Red"/>
    </Style>
  </Window.Styles>
  
  <ComboBox HorizontalAlignment="Center" VerticalAlignment="Center" SelectedIndex="0">
    <ComboBoxItem Content="Hello"/>
    <ComboBoxItem Content="Goodbye"/>
  </ComboBox>
```
