### ISSUE TITLE
Styles applying order

### ISSUE THREAD

**Issue by Axavo** [AvaloniaUI/Avalonia#2788]
Styles applied to an element not in the order they are declared in xaml, or the complexity of their selectors. In exаmple "Maximize" button have to be hidden,  but it is not.
[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/3440926/AvaloniaApplication1.zip)

**Comment by kekekeks** [comment]
The last CustomWindow-related selector in Theme.xaml
```xml
  <Style Selector="l|CustomWindow[CanResize=false] /template/ Button#PART_MaximizeButton">
    <Setter Property="IsVisible" Value="False" />
  </Style>
```

should hide the maximize button, when CanResize=False, but it doesn't

**Comment by grokys** [comment]
You seem to be setting `IsVisible = true` as a local value in the template in Theme.xaml:

```
<Button x:Name="PART_MaximizeButton"
        IsVisible="True"
        Classes="WindowTitleButton">
  <TextBlock Text="Max"/>
</Button>

```

Local values have a higher priority than styles, so it will always be `true`.

**Comment by grokys** [comment]
By the way, this is the same behavior as WPF/UWP.

We would like to improve the experience here, by setting properties in control templates with `Style` priority, but we've been unable to do that with Portable.Xaml. Now we have our own XAML compiler we hope to improve this in future.

**Comment by Axavo** [comment]
The workaround is to remove the property from the template and add it to another style?

**Comment by grokys** [comment]
In this case you just need to remove `IsVisible="True"` from the `Button`, as `true` is the default value.

In general, yes, you should add the default value to a style so it can be overridden, e.g.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Default/ListBoxItem.xaml#L26-L28

**Comment by kekekeks** [comment]
#2789
