### ISSUE TITLE
Set Template-provided properties with a separate BindingPriority

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2789]
Right now template-provided properties are being set with `LocalValue` priority which makes them to take precedence over any style setters. That's really inconvenient since it makes some control aspects impossible to style without changing the entire ControlTemplate.

We should have a separate `TemplateProperty` binding priority which can be overridden by `StyleTrigger` binding priority.

**Comment by grokys** [comment]
I'm not even sure we'd need a separate priority. I think using `Style` priority would do it.

**Comment by grokys** [comment]
Actually I think `TemplatedParent` priority is the correct one (should probably be renamed to `Template`)
