### ISSUE TITLE
AutoSuspendHelper - crash previewer

### ISSUE THREAD

**Issue by Guddiny** [AvaloniaUI/Avalonia#2790]
When i create an instance of `AutoSuspendHelper`:
`var suspension = new AutoSuspendHelper(ApplicationLifetime);`
i got previewer crash (coz `ApplicationLifetime `is null in design time )
```

11:54:15.676 [Error] 13528 <= "Unhandled Exception: System.ArgumentNullException: Value cannot be null."
11:54:15.713 [Error] 13528 <= "Parameter name: ApplicationLifetime is null. Ensure you are initializing AutoSuspendHelper when Avalonia application initialization is completed."
```

**Comment by kekekeks** [comment]
Application lifetime is not guaranteed to be configured since it's platform/application dependent. No lifetime is configured for previewer platform since there there is no application running.

**Comment by worldbeater** [comment]
Started working on a fix for this.
