### ISSUE TITLE
macOS AppBuilder must be created in same thread as Main() or else exception is thrown 

### ISSUE THREAD

**Issue by TylerLeonhardt** [AvaloniaUI/Avalonia#2800]
Hello! FIrst off - love what you folks are making. I work on the PowerShell team and we are working on porting some of our WPF stuff over to Avalonia like the ever famous command `Out-GridView` which [first appeared](https://devblogs.microsoft.com/powershell/out-gridview/) over 10 years ago!

Here's the problem, to port this over, we need to be able to use `AppBuilder` outside of the "main thread" - aka where main is.

> NOTE: This issue only happens on macOS because this issue is in the [native part of the code](https://github.com/AvaloniaUI/Avalonia/blob/42af4ee24b20866a58e346da2034f794a6564247/native/Avalonia.Native/src/OSX/platformthreading.mm#L89-L92) where avalonia calls `isMainThread` instead of doing what [Linux](https://github.com/AvaloniaUI/Avalonia/blob/0f94a0012dcb462a82aa4cca4ad8cc72b90e2995/src/Avalonia.X11/X11PlatformThreading.cs#L112) and [Windows](https://github.com/AvaloniaUI/Avalonia/blob/c978cb39ab2192b6073234e786d1b96dd0119712/src/Windows/Avalonia.Win32/Win32Platform.cs#L159) does which is rely on saving the `Thread.CurrentThread` at constructor time and calling that the "main thread"

If you take the sample MVVM project generated by the [donet new template](https://github.com/AvaloniaUI/avalonia-dotnet-templates), and make the following tweak to the `Main()` function, you can easily repro the issue:

```csharp
        public static void Main(string[] args)
        {
            Task.Run(() => BuildAvaloniaApp().Start(AppMain, args)).Wait();
        }
```

All I'm doing is wrapping it in a `Task.Run`... which gives me:

```
dotnet run

Unhandled Exception: System.AggregateException: One or more errors occurred. (Call from invalid thread) ---> System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in D:\a\1\s\src\Avalonia.Base\Threading\Dispatcher.cs:line 51
   at Avalonia.Rendering.RenderLoop.Add(IRenderLoopTask i) in D:\a\1\s\src\Avalonia.Visuals\Rendering\RenderLoop.cs:line 66
   at Avalonia.Controls.AppBuilderBase`1.Setup() in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 302
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args) in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 153
   at MyApp.Program.<>c__DisplayClass0_0.<Main>b__0() in /Users/tyler/Code/CSharp/MyApp/Program.cs:line 17
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MyApp.Program.Main(String[] args) in /Users/tyler/Code/CSharp/MyApp/Program.cs:line 17
```
`Call from invalid thread` because I didn't run the builder from the thread that `Main` is running in.

Perhaps the path forward is to do the same thing that Windows and Linux does?

GUI creation with PowerShell is a big deal - see sites like [posh gui](https://poshgui.com/) that have made tooling around making GUI's for PowerShell. It'd be awesome to support all the OS's we support. macOS is a big one.

Let me know if I can help supply any more details. I tried to make the repro simple enough to repro out of PowerShell but if you want a PowerShell version, you can try out @adamdriscoll's [ps-avalonia module](https://github.com/ironmansoftware/ps-avalonia) (first you need PowerShell Core, then you can run `Install-Module PSAvalonia`) which, today, only works on windows and linux because of this issue.

cc @SteveL-MSFT @jzeiders

**Comment by kekekeks** [comment]
Cocoa has its own idea about the thread being the main one and that's the first thread of the app. 
See https://developer.apple.com/documentation/foundation/nsthread/1412704-ismainthread?language=objc
You can't utilize any UI-related types on other threads than the main one. You can try asking Apple to change that, but I doubt that they'll listen.

**Comment by yatli** [comment]
@TylerLeonhardt any chance that powershell allow us execute a bit of code on the main thread?

**Comment by kekekeks** [comment]
It's not just "a bit of code" the entire UI main loop has to run on the main thread. Basically the entry point should look like this:

```cs
private static TaskCompletionSource<Action> _mainThreadCallback= new TaskCompletionSource<Action>();
static int Main(string[] args)
{
	var main = Task.Run(() => OriginalMain(args));
	if (Task.WaitAny(new Task[] {_mainThreadCallback.Task, main}) == 0)
	{
		_mainThreadCallback.Task.Result();
	}
	return main.Result;
}

public static void HijackMainThread(Action cb) => _mainThreadCallback.SetResult(cb);
```

**Comment by yatli** [comment]
Took a look at powershell stacktrace via windbg -- the mainthread is polling user input.
Seems trivial enough that some other thread takes over?

**Comment by SteveL-MSFT** [comment]
@yatli I think that's what we'll have to try
