### ISSUE TITLE
DataGridTextColumn with Converter shows empty cell

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2803]
v0.8.1
Binding a double property to a DataGrid column using a Converter displays an empty cell.
Binding without the converter shows the double values correctly.

For example, this will display an empty column for Range but values for Range2.
```
<DataGrid>
  <DataGrid.Columns>
    <DataGridTextColumn Header="Range" Binding="{Binding Range, Mode=TwoWay, Converter={StaticResource UnitsConverter}}" Width="*"/>
    <DataGridTextColumn Header="Range2" Binding="{Binding Range, Mode=TwoWay}" Width="*"/>
```

**Comment by aguahombre** [comment]
If ```UnitsConverter.Convert``` returns a double, the ```DataGridTextColumn.Binding``` doesn't call ToString() and an empty column is displayed.

The same converter works fine when binding to a TextBlock.Text
```
<TextBlock Text="{Binding Range, Mode=TwoWay, Converter={StaticResource UnitsConverter}}" />
```

**Comment by devel0** [comment]
I got the same problem and a workaround is to use DataGridTemplateColumn
