### ISSUE TITLE
SelectedItem setter is triggered for unchanged value in SelectingItemsControl

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#2807]
## Repro

```xaml
<ComboBox Items="{Binding Items}" SelectedItem="{Binding SelectedItem}" />
```

```cs
class ViewModel : ReactiveObject
{
    private string _selectedItem = "4";

    public IEnumerable<string> Items { get; } = Enumerable.Range(0, 5).Select(i => i.ToString()).ToArray();

    public string SelectedItem
    {
        get => _selectedItem;
        set => this.RaiseAndSetIfChanged(ref _selectedItem, value); // breakpoint here
    }
}
```

The breakpoint will be triggered on initialization, even though the selected item is correct and exists on `Items`.

## Problem

The problem is comparing by reference here: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Data/Core/SettableNode.cs#L45.

Replacing `Object.ReferenceEquals` with `Object.Equals` works as expected, but I'm not sure if this would be the correct behavior.

**Comment by MrJul** [comment]
Fixed by #13970
