### ISSUE TITLE
How to use Material Design theme in Avalonia Reactive UI WPF(.Net Core)

### ISSUE THREAD

**Issue by Dhirajsakariya** [AvaloniaUI/Avalonia#2812]
Hello,

I am developing app using following technologies:
WPF( .Net Core) , Avalonia Reactiveui
I would like to use Material Design theme in this app.

I tried to add Material design resource in app.xaml as below:
`
<Application.Resources>
		<ResourceDictionary>
			<ResourceDictionary.MergedDictionaries>
				
				<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
				<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
				<ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Teal.xaml" />
				<ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Teal.xaml" />
</ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
</Application.Resources>
`
But it throws error at runtime.

This is because Avalonia using xmlns="https://github.com/avaloniaui"

whereas resource dictionary file used xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" in plain WPF.

Could you please suggest how to resolve this problem.

**Comment by kekekeks** [comment]
The material design library you are using needs to be ported.

**Comment by Dhirajsakariya** [comment]
Could you please elaborate more on this. I didn't get you.
how can we port material design library?

**Comment by ahopper** [comment]
There are ported Material Design icons here https://github.com/ahopper/Avalonia.IconPacks

**Comment by Dhirajsakariya** [comment]
Thanks ahopper for your reply.
How to use this ported Material Design Icons in app.
I need to use Material Design Theme and Color in Avalonia Reactive UI WPF?
What I need to do? how can I port theme and use it?
Thanks in advance.

**Comment by ahopper** [comment]
The IconPacks app is an example in itself. MainWindow.xaml https://github.com/ahopper/Avalonia.IconPacks/blob/master/MainWindow.xaml uses an icon for search. The icon is in a file in the icons directory and it is referenced as a StyleInclude in App.xaml. You typically don't want to include all icons so the IconPacks program is there to allow easy copy and pasting of just the icons you want.  I think the ControlCatalog sample has an example of themes.

**Comment by Dhirajsakariya** [comment]
I am not able to find ControlCatalog  there.
Is it a separate repo?

**Comment by ahopper** [comment]
https://github.com/AvaloniaUI/Avalonia/tree/master/samples

**Comment by Dhirajsakariya** [comment]
I have downloaded whole solution (it has 70+ projects) but I am not able to find any project which is using Material Design them

**Comment by ahopper** [comment]
There is not a current Material Design theme but there are examples of theme changing which might help you port/create a Material theme, this may also be useful https://github.com/wieslawsoltes/Avalonia.ThemeManager

**Comment by ahopper** [comment]
and https://github.com/wieslawsoltes/ThemeEditor

**Comment by Dhirajsakariya** [comment]
Do you mean that Material Design won't integrate with Avalonia Reactiveui as  it is.

Do I need to Adapt theme of Avalonia using ThemeManger to make similar to Material Design theme?

**Comment by ahopper** [comment]
> Do you mean that Material Design won't integrate with Avalonia Reactiveui as it is.
yes, the wpf library wont magically work.

> Do I need to Adapt theme of Avalonia using ThemeManger to make similar to Material Design theme?
I'm no expert on themes but ThemeEditor might be a good place to start

**Comment by Dhirajsakariya** [comment]
Thanks ahopper for your quick response.

**Comment by Dhirajsakariya** [comment]
I have looked at Avalonia Theme Editor and play around it.

It support only Color modification. I would like make style similar to Material Design.

How can I do this.

**Comment by Gillibald** [comment]
Avalonia has lookless controls like WPF. To have controls to look like you want you have to override the default templates. 

https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.Themes.Default
