### ISSUE TITLE
X11 windows does not respect initial Width/Height values 

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#2815]
![image](https://user-images.githubusercontent.com/16554748/62622643-66d16800-b951-11e9-8dff-b00814722274.png)

Seems like X11 backend doesn't remember nor adjusts to the initial width/height values of `MainWindows` and other related controls.

**Comment by kekekeks** [comment]
I've just checked with `Width="1024" Height="800"` and it works on KDE 5.12. It might be either your IDE not recompiling on XAML file changes or your window manager ignoring window resize for not-mapped windows

**Comment by jmacato** [comment]
@kekekeks I'm currently on Cinnamon DE, also tested with MATE and it did the same

**Comment by kekekeks** [comment]
Make sure that
1) you actually have Width/Height in your XAML file (*not* MinWidth/MinHeight)
2) project was actually recompiled after the change

**Comment by jmacato** [comment]
I was using ControlCatalog btw, not a custom project

**Comment by kekekeks** [comment]
ControlCatalog [only specifies](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/MainWindow.xaml#L1) `MinWidth="500" MinHeight="300"` which is exactly the dimensions the window is created with

**Comment by jmacato** [comment]
Hmm.. cc @danwalmsley seems like it's working as intended?, perhaps we should set `MinWidth`/`MinHeight` on dialogs perhaps?

**Comment by jmacato** [comment]
Seems like the issue was that the default window sizes are not consistent across windows and linux. That issue is tangental to this one so im gonna close this.
