### ISSUE TITLE
Enable for each row a separate RowBackground in DataGrid per row binding

### ISSUE THREAD

**Issue by audioprog** [AvaloniaUI/Avalonia#2819]
In order to highlight a few rows in the table due to a property, I wanted to adjust the background of the respective row. Unfortunately, I haven't found a way to do that.
Alternatively CellBackground with same abilities.

**Comment by ferreus** [comment]
`
<UserControl.Resources>
    <conv:TestGridBackgroundConverter x:Key="BackgroundConverter"/>
    <conv:TestGridForegroundConverter x:Key="ForegroundConverter"/>
  </UserControl.Resources>
  <UserControl.Styles>
    <Style Selector="DataGridCell.colored">
      <Setter Property="Foreground" Value="{Binding Path=Result, Mode=OneWay, Converter={StaticResource ForegroundConverter}}"/>
      <Setter Property="Background" Value="{Binding Path=Result, Mode=OneWay, Converter={StaticResource BackgroundConverter}}"/>
    </Style>
  </UserControl.Styles>
...
<DataGridTextColumn IsReadOnly="True" Header="Name" Width="5*" Binding="{Binding Name}" CellStyleClasses="colored"/>
        <DataGridTextColumn IsReadOnly="True" Header="Status" Width="5*" Binding="{Binding Status}" CellStyleClasses="colored"/>
        <DataGridTextColumn IsReadOnly="True" Header="Result" Width="8*" Binding="{Binding Result}" CellStyleClasses="colored"/>
        <DataGridTextColumn IsReadOnly="True" Header="Info" Width="8*" Binding="{Binding Info}" CellStyleClasses="colored"/>
`

Worked like a charm :)

**Comment by audioprog** [comment]
Would you share the source code of the converters?

**Comment by audioprog** [comment]
Would you share the source code of the converters?

**Comment by ferreus** [comment]
`
public class TestGridBackgroundConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value is TestLib.ResultStatus result)
            {
                if (result == TestLib.ResultStatus.OK)
                {
                    return Brushes.DarkGreen;
                } else if (result == TestLib.ResultStatus.ERROR)
                {
                    return Brushes.DarkRed;
                }
            }
            return Brushes.White;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
`

**Comment by MihaMarkic** [comment]
But still, DataContext to (Alternate)RowBackground could be the row source itself. How would you handle i.e pointerover over a row with this approach?

**Comment by maxkatz6** [comment]
@MihaMarkic pointerover selector can go after with higher priority. If you need to change the color depending on the row data context AND pointer over property, it's easier to use multi binding to bind to both data context and parent row's IsPointerOver property.

**Comment by MihaMarkic** [comment]
@maxkatz6 Ah, right, one has access to row properties through a parent relationship.

**Comment by maxkatz6** [comment]
Solution was provided. Alternatively, developer can use LoadingRow to set classes to the row and use it in the styles, correct data context is set in this event.
