### ISSUE TITLE
Menus are broken

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#2821]
On current master (dcf6821ef99d26dad83a30e2e7eb45d5f5e6501d) there are a couple of problems with menus:

- There's no longer a 1px border around the menu
- Clicking on a menu item with a submenu closes the menu instead of opening the submenu

There seem to be 3 separate issues that are causing this:

- [x] When a popup gets closed, pointerover state is not cleared (fix: #2924)
- [ ] Popup is clipping 1 pixel of the top and left edges of its content
- [x] `ContentPresenter` sometimes doesn't set the logical parent of its child control (probably caused by #2825) (fix #2926)

I will open PRs to fix each one separately.

**Comment by mat1jaczyyy** [comment]
Noticed this as well

**Comment by danwalmsley** [comment]
Also having real difficulty clicking on some menu items.

**Comment by waliarubal** [comment]
Menu items no longer show check boxes. This is issue with 0.8.1, 0.8.2 and nightly builds.

```
<MenuItem Header="Navigation Pane">
                <MenuItem.Icon>
                    <CheckBox BorderThickness="0" IsHitTestVisible="False" />
                </MenuItem.Icon>
            </MenuItem>
```

**Comment by wieslawsoltes** [comment]
Menu are really broken.

**Comment by HendrikMennen** [comment]
Noticed that clicking on the icon part on menus works every time. The other part registers a click only sometimes

**Comment by ahopper** [comment]
I wonder if wrong menus closing is caused by the same thing as https://github.com/AvaloniaUI/Avalonia/issues/2921 PopupRoot no longer has a VisualParent
