### ISSUE TITLE
How to switch theme at runtime?

### ISSUE THREAD

**Issue by Dhirajsakariya** [AvaloniaUI/Avalonia#2824]
I would like to have multiple themes for my app.

I would like to load theme based on user preferred theme at run time when user logs in to the app.

How can it be done using Avalonia?

**Comment by wieslawsoltes** [comment]
### The simplest way

https://github.com/AvaloniaUI/Avalonia/blob/b002de40f27fafd5229e0f5ffd4a323cb0e6dbf8/samples/ControlCatalog/MainView.xaml#L9-L12
https://github.com/AvaloniaUI/Avalonia/blob/b002de40f27fafd5229e0f5ffd4a323cb0e6dbf8/samples/ControlCatalog/MainView.xaml.cs#L35-L58

### Use external library

https://github.com/wieslawsoltes/Avalonia.ThemeManager#usage
https://github.com/wieslawsoltes/Avalonia.ThemeManager/tree/master/samples/AvaloniaApp

**Comment by Dhirajsakariya** [comment]
Just now I have tried it out and it worked.

Question : How can I do this in view model?

I don't have acces to Styles in viewModel.

**Comment by CreateLab** [comment]
@Dhirajsakariya 
Some time ago I wrote about it in my blog. (Styling in avalonia)
https://habr.com/en/post/471342/

**Comment by maxkatz6** [comment]
New API for theme switching, reuse same FluentTheme instance, but change Mode.
#7256

Or if you want to customize it, use the same approach as in that PR - keep control styles always loaded, but replace resource dictionaries.

**Comment by smartguy1196** [comment]
> New API for theme switching, reuse same FluentTheme instance, but change Mode. #7256
> 
> Or if you want to customize it, use the same approach as in that PR - keep control styles always loaded, but replace resource dictionaries.

For anyone reading this from the future, that comment was in regards to Fluent Light vs Fluent Dark switching. Not necessarily dynamic loading for all themes.
