### ISSUE TITLE
Button in ListBoxItem not firing event

### ISSUE THREAD

**Issue by HendrikMennen** [AvaloniaUI/Avalonia#2830]
Hello,
I am trying to place a button inside a ListViewItem like this:
```
<ListBox FontSize="13" Items="{Binding Path=SelectedFPGA.Connections}" SelectedItem="{Binding Path=SelectedFPGA.SelectedConnection, Mode=TwoWay}" Background="{StaticResource DarkColor}" BorderThickness="0" VerticalAlignment="Stretch">
                <ListBox.ItemTemplate>
                  <DataTemplate>
                    <DockPanel>
                      <TextBlock Text="{Binding Signal}"></TextBlock>
                      <Image Height="18" Source="avares://VHDPlus/Assets/Images/Icons/twotone_link_white_18dp.png"></Image>
                      <TextBlock Text="{Binding Pin}"></TextBlock>                     
                      <Button Height="18" Width="18" Classes="Seperate" DockPanel.Dock="Right" Command="{Binding Seperate}" HorizontalAlignment="Right" ToolTip.Tip="Seperate connection" Margin="0" Padding="0">
                        <Image Height="18" Source="avares://VHDPlus/Assets/Images/Icons/Close_White_16x.png"></Image>
                      </Button>
                    </DockPanel>
                  </DataTemplate>
                </ListBox.ItemTemplate>
</ListBox>
```
![Unbenannt](https://user-images.githubusercontent.com/25281882/62822747-c3b66380-bb87-11e9-9a60-d5b018efe7b0.PNG)

It shows correcty but I can't figure out how to get the click event from it.
The :pointerover style does not work too so I am guessing that the Listboxitem consumes the click so the button does not fire the event. 

I tried experimenting with Z-Index but it didn't change anything

**Comment by FoggyFinder** [comment]
Your command `Seperate` is in the same level as `SelectedFPGA.Connections` in VM?

**Comment by HendrikMennen** [comment]
Seperate is in the same level as Signal or Pin. But I already tried moving it somewhere else. I also tried the `Click="Seperate"` which would access the method in the View.cs file but it did nothing

**Comment by MarchingCube** [comment]
You can check what happens to the event in the dev tools.

**Comment by FoggyFinder** [comment]
Can you provide MCVE?
Version of Avalonia?

**Comment by HendrikMennen** [comment]
I don't know what is wrong here but in I managed to make it work in a different ListBox so I guess it was my mistake

**Comment by Touhid9814** [comment]
Can your share your last code of that Listbox?

**Comment by timunie** [comment]
@Touhid9814 answering closed issues will most likely not help you. If you have a question you need an advice, please open a new Q&A in discussion or join us on telegram https://t.me/Avalonia
