### ISSUE TITLE
Cycle Detected. NU1108

### ISSUE THREAD

**Issue by evanricard** [AvaloniaUI/Avalonia#2832]
Hello Avalonia, 

I'm using VS2019 and there seems to be something wrong with my .csproj or my .sln? I started tooling around by using _dotnet new avalonia.app_ and then _dotnet sln add avalonia.csproj_. I've made a cyclical dependency somehow.  

Severity	Code	Description	Project	File	Line	Suppression State
Error		NU1108	Cycle detected. 
  avalonia -> Avalonia (>= 0.8.0).	avalonia	C:\Users\evanr\Desktop\avalonia\avalonia.csproj	1	

Both dotnet restore and clean solution do not fix what is now broken...including my myget packages.
<PackageReference Include="Avalonia" Version="0.8.0" />
<PackageReference Include="Avalonia.Desktop" Version="0.8.0" />

In any event, thanks!

**Comment by jp2masa** [comment]
I guess the problem is that the project name is the same as the Avalonia package. You can try creating the project using `dotnet new avalonia.app -n MyApp`.

**Comment by evanricard** [comment]
Oh, strange...I should have thought to try that. Thanks!

**Comment by CSharpTeoMan911** [comment]
Yes....you are right. I made a dummy project to test the new Avalonia features called "Avalonia", but as it seems it was masking the namespace of the Framework, and thus it created a ton of errors, including this one.

**Comment by giuliohome** [comment]
You should fix the documentation here!!!!


https://docs.avaloniaui.net/docs/guides/platforms/how-to-use-web-assembly

**Comment by timunie** [comment]
@giuliohome PRs to the docs are welcome.
