### ISSUE TITLE
Unable to parse binding expression

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#2834]
`IsVisible="{Binding !$parent[cont|MetroWindow].DataContext.LockScreen.IsLocked}"`

gives a runtime error.

but:

`IsVisible="{Binding !$parent[Window].DataContext.LockScreen.IsLocked}"`

works

transfered from:
https://github.com/kekekeks/XamlIl/issues/3

**Comment by donandren** [comment]
separator `|` is used only for style selectors i believe.
on theory the right expression should be :
`IsVisible="{Binding !$parent[cont:MetroWindow].DataContext.LockScreen.IsLocked}"`
