### ISSUE TITLE
XAMLIL cannot resolve selector type for named elements without type qualifier

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2840]
Using build 0.8.999-cibuild0003548-beta, I get a XAMLIL compiler error for the following XAML

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:cv="clr-namespace:AvaloniaApplication7;assembly=AvaloniaApplication7"
             xmlns:v="clr-namespace:AvaloniaApplication7.Views;assembly=AvaloniaApplication7"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="AvaloniaApplication7.Views.ViewA">
  <UserControl.Styles>
    <Style Selector="v|ViewA[MyViewProperty=Test] #_myTextBlock">
      <Setter Property="Background" Value="White"/>
    </Style>
  </UserControl.Styles>
  <TextBlock Text="{Binding UrlPathSegment}" Name="_myTextBlock"/>
```

```
Error	XAMLIL	Can not resolve parent Style Selector type (line 11 position 8) Line 11, position 8.	AvaloniaApplication7	
```

Code behind
```
namespace AvaloniaApplication7.Views
{
    public class ViewA : ReactiveUserControl<ViewModelA>
    {
        public static readonly StyledProperty<string> MyViewPropertyProperty = AvaloniaProperty.Register<ViewA, string>(nameof(MyViewProperty));

        public string MyViewProperty
        {
            get => GetValue(MyViewPropertyProperty);
            set => SetValue(MyViewPropertyProperty, value);
        }

        public ViewA()
        {
            this.WhenActivated(disposables =>
            {
            });
            AvaloniaXamlLoader.Load(this);
        }
    }
}

This is a cut down version of some code that worked in v0.8.1
```

**Comment by kekekeks** [comment]
`v|ViewA[MyViewProperty=Test] #_myTextBlock` since you are resolving the element by name, it's impossible to resolve the type of the target element at compile time.

Try `v|ViewA[MyViewProperty=Test] TextBlock#_myTextBlock`

**Comment by aguahombre** [comment]
Thanks, the XAML now compiles using the type qualifier.

The error message didn't help me find that; maybe the error message should say something like the XAMLIL compiler couldn't resolve the type of #_myTextBlock. That would have helped.

Incidentally, why is it impossible to determine that _myTextBlock is the element name of a TextBlock, the information is there in the source XAML. It worked in v0.8.1.

BTW thanks for the quick responses, appreciated.

**Comment by kekekeks** [comment]
Well, not quite possible without hacks in the current implementation since it's allowed to have multiple elements with the same name in different scopes. We could probably do that once compiled bindings are there, but for now we require the type qualifier.

**Comment by aguahombre** [comment]
If there is only one element with the name in the visible XAML namescopes then there is no conflict and the compiler could choose that element; as in this case.
Multiple elements with the same name of course would need qualifying somehow and the compiler should output an error message.

**Comment by kekekeks** [comment]
Compiler doesn't have the required info to resolve the type. Attempts to do that at the run time are likely to hurt performance.
