### ISSUE TITLE
TextBox with color support

### ISSUE THREAD

**Issue by Jivko1212** [AvaloniaUI/Avalonia#2842]
What is the easiest way to use the RichTextBox functionality in Avalonia that allows for different colored text? Such text box can be used to display application logs for example with different lines having different color depending on the log level (Debug, Info, Error,Fatal).

Thanks

**Comment by Gillibald** [comment]
This is currently not supported but will be by this: https://github.com/AvaloniaUI/Avalonia/pull/1950

**Comment by derekantrican** [comment]
@Gillibald looks like that PR is closed. Any updates on this?

**Comment by Gillibald** [comment]
Inlines support will come later this year

**Comment by hopeko** [comment]
> Inlines support will come later this year
2020 is over...

**Comment by Gillibald** [comment]
You can pay me to speed things up that I do in my free time. Trust me I am not cheap....

**Comment by derekantrican** [comment]
@hopeko Have you looked into https://github.com/AvaloniaUI/AvaloniaEdit?

**Comment by hopeko** [comment]
> You can pay me to speed things up that I do in my free time. Trust me I am not cheap....

Funny... You said that, not me.

**Comment by hopeko** [comment]
@derekantrican Thanks, I'll try.

**Comment by alexandrehtrb** [comment]
Hello,

Is there a way to colourize parts of text in a TextBox?
I managed to do that with Inlines and Runs in TextBlock, I would like to do with TextBox too.

### UPDATE 2026-06-01:

[SyntaxHighlightingTextBox.cs](https://github.com/carina-studio/AppSuiteBase/blob/master/SyntaxHighlighting/Controls/SyntaxHighlightingTextBox.cs) from the [ULogViewer](https://github.com/carina-studio/ULogViewer) can be used.

I've [adapted](https://github.com/alexandrehtrb/Pororoca/blob/develop/src/Pororoca.Desktop/Controls/SyntaxHighlightingTextBox.cs) the solution above for my project.

**Comment by timunie** [comment]
Beside AvaloniaEdit or custom control? None I am aware of for the time being.

**Comment by alexandrehtrb** [comment]
Would it be possible for TextBox to support Inlines? TextEditor is a bit too much for my use-case...

**Comment by alexandrehtrb** [comment]
> Beside AvaloniaEdit or custom control? None I am aware of for the time being.

How could I make a custom control for that? Do you guys have an idea of where to start?
