### ISSUE TITLE
Allow Unit Testing outside of repo

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#2843]
something like this naive implementation:

https://gist.github.com/danwalmsley/dfcd6fa0362a5ef551e8ea5569c0f789

possibly with headless branch merged in.

@kekekeks has a lot of ideas.

**Comment by kekekeks** [comment]
The current idea is to start the app in headless mode.

See https://github.com/kekekeks/Avalonia-unit-testing-with-headless-platform for a reference implementation
