### ISSUE TITLE
StyleInclude NRE if assembly not present in URI

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2850]
Using build 0.8.999-cibuild0003548-beta.
I get an NRE from the following XAML:

```
  <UserControl.Styles>
    <StyleInclude Source="resm:MyApp.Views.MyStyles.xaml"/>
  </UserControl.Styles>
```

It generates an NRE with stack trace:
```
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri, Uri baseUri) in D:\a\1\s\src\Shared\PlatformSupport\AssetLoader.cs:line 103
```

This used to work in v0.8.1 but now I need to include the assembly in the URI

```
  <UserControl.Styles>
    <StyleInclude Source="resm:MyApp.Views.MyStyles.xaml?assembly=MyApp"/>
  </UserControl.Styles>
```

**Comment by Gillibald** [comment]
I am not sure if the `resm:` sheme is supported here. Could you try to use `avares:` here. Also how is that XAML embedded into your application? It is probably added as `AvaloniaResource` and therefore only `avares` works.

**Comment by aguahombre** [comment]
It's an embedded resource
![image](https://user-images.githubusercontent.com/17591364/63089541-21fc9100-bf50-11e9-8ae6-76f04500987c.png)
