### ISSUE TITLE
PointerReleasedEventArgs MouseButton obsolete

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2856]
The MouseButton property of PointerReleasedEventArgs  is marked as obsolete.
But on Windows at least, the InputModifiers is set to None when 
```protected override void OnPointerReleased(PointerReleasedEventArgs e)``` is called.
Without using MouseButton there is no way to find out which mouse button was released.

I see that the ```RawPointerEventArgs``` that is used to create the ```PointerReleasedEventArgs  ``` contains the event type ```RawPointerEventType.LeftButtonUp``` etc, perhaps this could be used to set the InputModifiers to show the release mouse button.

**Comment by kekekeks** [comment]
`e.GetPointerPoint(null).Properties.PointerUpdateKind`

**Comment by kekekeks** [comment]
Also keep in mind that pointer events now work in UWP way, so `PointerReleased` event will be triggered when *last* button is released, other button update events will come as `PointerMoved`

**Comment by kekekeks** [comment]
Actually, the UWP docs state
```


Mouse input is associated with a single pointer assigned when mouse input is first detected. Clicking a mouse button (left, wheel, or right) creates a secondary association between the pointer and that button through the PointerPressed event. The PointerReleased event is fired only when that same mouse button is released (no other button can be associated with the pointer until this event is complete). Because of this exclusive association, other mouse button clicks are routed through the PointerMoved event. You can test the mouse button state when handling this event, as shown in the following example.
```
so we need to update that.

**Comment by kekekeks** [comment]
#2857

**Comment by aguahombre** [comment]
I just tried ```e.GetPointerPoint(null).Properties.IsLeftButtonPressed``` in the ```OnPointerReleased``` method but get false for a left mouse button release; so that's no use.

**Comment by kekekeks** [comment]
`IsLeftButtonPressed` reports the *current* state (i. e. after the button was already released). You need the `PointerUpdateKind` property.

**Comment by aguahombre** [comment]
That doesn't exist in ```Using build 0.8.999-cibuild0003548-beta.``` the latest NuGet release.

**Comment by TheSwerik** [comment]
not solved yet?

**Comment by maximilien-noal** [comment]
PointerReleasedEventArgs example:
e.InitialPressMouseButton

PointerEventsArgs example:
e.GetCurrentPoint(this).Properties.IsLeftButtonPressed

Seems to work for me.

**Comment by aguahombre** [comment]
I believe this was fixed when the releases caught up with the dev branch
