### ISSUE TITLE
Change PointerPressed/PointerReleased to work as in UWP

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2857]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.pointerreleased

>    Mouse input is associated with a single pointer assigned when mouse input is first detected. Clicking a mouse button (left, wheel, or right) creates a secondary association between the pointer and that button through the PointerPressed event. The PointerReleased event is fired only when that same mouse button is released (no other button can be associated with the pointer until this event is complete). Because of this exclusive association, other mouse button clicks are routed through the PointerMoved event. You can test the mouse button state when handling this event, as shown in the following example.

**Comment by kekekeks** [comment]
>The PointerReleased event is fired only when that same mouse button is released (no other button can be associated with the pointer until this event is complete

This turned out to be a blatant lie. I've checked the UWP behavior and it seems that they are waiting for the last mouse button to be released before triggering PointerReleased event.

While experimenting I've captured the following event sequence:

|Event|UpdateKind|LeftPressed|MiddlePressed|RightPressed|
|----|--|--|--|--|
|PointerPressed|LeftButtonPressed|True|False|False|
|PointerMoved|MiddleButtonPressed|True|True|False|
|PointerMoved|RightButtonPressed|True|True|True|
|PointerMoved|RightButtonReleased|True|True|False|
|PointerMoved|LeftButtonReleased|False|True|False|
|PointerMoved|RightButtonPressed|False|True|True|
|PointerMoved|MiddleButtonReleased|False|False|True|
|PointerReleased|RightButtonReleased|False|False|False|

```

**Comment by kekekeks** [comment]
So we only need to make the obsolete `MouseButton` to return the button that caused the initial `PointerPressed` event and call it a day.

**Comment by grokys** [comment]
Can this be closed due to #3101?
