### ISSUE TITLE
WindowStartupLocation=CenterOwner on Windows makes window appear for a short period of time at other location before it's centered

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#2859]
Code:

```csharp
var mainWindow = Application.Current.Windows.First();
var dialogWindow = new MyWindow();
dialogWindow.ShowDialog(mainWindow);
```

XAML (dialog window):

```xml
<Window
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    WindowStartupLocation="CenterOwner">
```

The dialog window "flashes" at some other location on the screen before appearing at intended destination.

**Comment by Deadpikle** [comment]
Repro: https://github.com/Deadpikle/AvaloniaBugs/tree/master/DialogStartupLocation (can repro on Windows using latest `master` as of 2020-04-01)

**Comment by MikeCodesDotNET** [comment]
Tested on v11 RC, and it works as expected. (at least on macOS)
