### ISSUE TITLE
Avalonia error XAMLIL: Unable to find public constructor for type ResourceInclude

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2861]
Error:
```
/home/ubuntu/projects/Dock/samples/AvaloniaDemo.Experimental/Layouts/Default.xaml(9,31,9,31): Avalonia error XAMLIL: Unable to find public constructor for type Avalonia.Markup.Xaml:Avalonia.Markup.Xaml.MarkupExtensions.ResourceInclude(System.Runtime:System.String) (line 9 position 31) Line 9, position 31. [/home/ubuntu/projects/Dock/samples/AvaloniaDemo.Experimental/AvaloniaDemo.Experimental.csproj]
```
Repro:
```XAML
<Style xmlns="https://github.com/avaloniaui" 
       xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
       xmlns:idc="clr-namespace:Dock.Avalonia.Controls;assembly=Dock.Avalonia"
       xmlns:dmc="clr-namespace:Dock.Model.Controls;assembly=Dock.Model.Avalonia"
       xmlns:vmd="clr-namespace:AvaloniaDemo.ViewModels.Documents;assembly=AvaloniaDemo"
       xmlns:vmt="clr-namespace:AvaloniaDemo.ViewModels.Tools;assembly=AvaloniaDemo"
       xmlns:vmv="clr-namespace:AvaloniaDemo.ViewModels.Views;assembly=AvaloniaDemo"
       Selector="idc|DockControl.Default">
    <Setter Property="Layout" Value="{ResourceInclude avares://AvaloniaDemo/Layouts/Root.xaml}"/>
</Style>
```

**Comment by kekekeks** [comment]
I'm not sure how your XAML is supposed to work. According to the tests, it's supposed to be used like this:
https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/ResourceIncludeTests.cs#L25

I don't see any code that would load anything but IResourceProvider.

**Comment by wieslawsoltes** [comment]
@kekekeks I was just trying stuff and found the issue. I was also unsure if this will work.

**Comment by kekekeks** [comment]
It doesn't seem to be compiler-related. The `ResourceInclude` doesn't have a constructor that accepts a string as a parameter. It also seems to be only used in merged resource dictionaries. 

However this brings up a question. Should we cache loaded xaml resource instances?

**Comment by wieslawsoltes** [comment]
I am not sure about the questions. 

My use case is to instantiate custom object declared using xaml.

**Comment by kekekeks** [comment]
I think the current supported way of instantiating custom xaml-declared objects is an empty class in XAML's codebehind that could be used as an alias.

**Comment by wieslawsoltes** [comment]
> I think the current supported way of instantiating custom xaml-declared objects is an empty class in XAML's codebehind that could be used as an alias.

What about a scenario when I want to instantiate existing class and not derived.

From my example: https://github.com/kekekeks/XamlIl/issues/6

The `Dock` class is already present in my library, I just want to instantiate it and use as value for some property. Requiring additional empty class is not possible here as you have to create new class which seems unnecessary. This would make XAML so much powerful in Avalonia and enable more scenarios.

```XAML
<Dock xmlns="https://github.com/avaloniaui" 
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:vm="clr-namespace:Demo.ViewModels;assembly=Demo"
      ActiveLayout="{x:Reference layout1}">
  <Dock.Items>
      <vm:Item1ViewModel x:Name="item1"/>
      <vm:Item2ViewModel x:Name="item2"/>
      <vm:Item3ViewModel x:Name="item3"/>
  <Dock.Items>
  <Dock.Layouts>
    <Layout x:Name="layout1">
      <x:Reference Name="item1"/>
      <x:Reference Name="item2"/>
    </Layout>
    <Layout x:Name="layout2">
      <x:Reference Name="item1"/>
      <x:Reference Name="item2"/>
      <x:Reference Name="item3"/>
    </Layout>
  </Dock.Layouts>
</Dock>
```

**Comment by wieslawsoltes** [comment]
@kekekeks I have managed to resolve my issue. If you want we can close this issue.

For reference this is my solution for loading object instances from xaml using custom markup extension.

https://github.com/wieslawsoltes/Dock/blob/8eed1ba62b3f3da51c40aad0a13c9fbe00d14639/samples/AvaloniaDemo.Perspectives/Views/MainView.xaml#L19

https://github.com/wieslawsoltes/Dock/blob/8eed1ba62b3f3da51c40aad0a13c9fbe00d14639/src/Dock.Avalonia/Controls/LayoutIncludeExtension.cs#L12-L51
