### ISSUE TITLE
How to compile for Mac?

### ISSUE THREAD

**Issue by feyscontrol** [AvaloniaUI/Avalonia#2874]
Dear team,

I am not sure I am doing the correct steps trying to build a test app for Mac
 What I did.
1. Installed Avalonia.
2. Compiled the barebone template.
3. Moved the debug bin files to Mojave machine.
4. As mono was previously installed for Xamarin tests, from terminal I entered into the folder containing the avalonia exe and run "mono Avalonia-august.exe" where Avalonia-august.exe is the name of the compiled exe. Capitalisation observed.
Issue 1: Cannot open assembly "Avalonia-august.exe". No such file or directory. 
5. From your Blog I found that I AppBuilder should be modified (https://avaloniaui.net/blog/2018-10-09-avalonia-native-osx)
Issue 2: Platform class was not recognized even I add the avalonia.native namespace.
6. So them I found the LINQ-like syntax for AppBuilder and there I added
~~~csharp
public static AppBuilder BuildAvaloniaApp() => AppBuilder.Configure<App>()
     .UsePlatformDetect()
     .With(new X11PlatformOptions { UseGpu = false })
     .With(new AvaloniaNativePlatformOptions { UseGpu = false })
     .With(new MacOSPlatformOptions { ShowInDock = false })
     .With(new Win32PlatformOptions { UseDeferredRendering = false });
~~~
I added both syntaxes (from the 2 articles) and changed the MacOS line to 

~~~csharp
 .With(new MacOSPlatformOptions { ShowInDock = false }).UseAvaloniaNative().UseSkia()
~~~
but compiling this gave me 

issue 3:
Unable to load DLL 'libAvaloniaNative' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E) 

Very confused and struggling! Please help me in order for me to dive into your world :)

**Comment by kekekeks** [comment]
`dotnet publish -f netcoreapp2.0 -r osx-x64`. Change `netcoreapp2.0` to your .NET Core version. This will produce a self-contained bundle with a runnable OSX executable.


Mono-based *packaging* is not supported, if you need Mono instead of .NET Core you are basically on your own.

**Comment by feyscontrol** [comment]
Hi kekekeks,

thanks for answering. I am still confused how to proceed after running the command as now I have a publish folder with dlls, dylibs and jsons. I don't see any even an exe inside. How I am supposed to launch the result on Mac? Still very confused...

**Comment by feyscontrol** [comment]
Ok just for the sake of documentation. After I ran the command. I copied the publish folder to the Mac machine and from terminal ran dotnet <myappname>.dll which launched the application.

**Comment by kekekeks** [comment]
`dotnet publish` will produces an executable file named with application name *without any extension*.
