### ISSUE TITLE
Window size not retained after compilation

### ISSUE THREAD

**Issue by feyscontrol** [AvaloniaUI/Avalonia#2877]
I am compiling the default barebone template just adding 2 columns with 2 textblocks. Compiling with dotnet for netcore 2.1.
running dotnet and the respective dll creates the window but the default window size of d:DesignWidth="800" d:DesignHeight="450" is not retained and the actual window appears very very small - like 100x100 px. Is this a configuration issue or a bug?

Mojave 10.14.6

**Comment by Gillibald** [comment]
Properties set with `d:` are only used at design time

**Comment by feyscontrol** [comment]
confirmed. Thanks!
