### ISSUE TITLE
What is the equivalent of a WPF Page Control in Avalonia?

### ISSUE THREAD

**Issue by feyscontrol** [AvaloniaUI/Avalonia#2878]
What is the equivalent? I am not able to find an equivalent in the API.

**Comment by FoggyFinder** [comment]
I think you can replace `Page` with `UserControl`. What is your usecase?

**Comment by feyscontrol** [comment]
I have a WPF app where I used tabitems whose content is pages. I just set their frame to be pages. As now I want to port this in Avalonia I want to make the transfer as close as possible to the original architecture. But if you say that the closest is UserControl I will try to make the necessary modifications. I am not sure if I tested in my WPF that a usercontrol can be set to a frame. control though...

**Comment by FoggyFinder** [comment]
I count `Frame` is very ugly and absolutely inconvenient to use. But that's only my opinion.
