### ISSUE TITLE
Linux/Gtk: The TextBox caret is not removed after control focus is lost

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#288]
Linux/Gtk: The TextBox caret is not removed after control focus is lost.

![linux-caret](https://cloud.githubusercontent.com/assets/2297442/10716030/aee18166-7b2a-11e5-826c-ecee01df7de0.png)

**Comment by grokys** [comment]
Closing this as GTK2 has been removed.
