### ISSUE TITLE
AddRange is not working with IEnumerable

### ISSUE THREAD

**Issue by Ticky-Ticky** [AvaloniaUI/Avalonia#2896]
Hello! 

There is an issue with Panel's AddRange method. 
AddRange has a parameter IEnumerable. 
But when we are adding elements like this
```
StackPanel.Children.AddRange(Enumerable.Range(2, 2).Select(x => new TextBlock() { Text = x.ToString() }));
```
it shows nothing

i.e. this code is working normally
```
StackPanel.Children.AddRange(Enumerable.Range(4, 2).Select(x => new TextBlock() { Text = x.ToString() }).ToList()); 
StackPanel.Children.AddRange(Enumerable.Range(6, 2).Select(x => new TextBlock() { Text = x.ToString() }).ToArray()); 
```

So method is working with Arrays and Lists, but doesn't work with IEnumerable

**Comment by MarchingCube** [comment]
Might be fixed by https://github.com/AvaloniaUI/Avalonia/pull/2882

**Comment by grokys** [comment]
Yeah this looks like #2882 should have fixed it. Will close; @Ticky-Ticky if it's still a problem let us know and we'll reopen.
