### ISSUE TITLE
Optimization opportunity in AvaloniaProperty.NotifyInitialized

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2897]
`AvaloniaProperty.NotifyInitialized` is called for every property(including attached properties) on every Avalonia object.  In control Catalog, once you visit every page, this is 1,230,000 calls.  The only thing I can find that uses this is PsuedoClasses, these receive events from 40,000 of them but only 190 actually change the value.
This is a very expensive way to set PseudoClass defaults.

Is the `IObservable<AvaloniaPropertyChangedEventArgs> Initialized` often/ever used by user code?

Or have I missed some vital use?

The numbers are large in part due to a Datagrid layout/virtualization issue

**Comment by kekekeks** [comment]
It also calls getters for all properties, including direct ones. That prevents us from using lazy initialization of those and causing #2894

**Comment by MarchingCube** [comment]
I have run a memory profiler on ControlCatalog clicking through few pages. It seems that this initialized code causes a lot of property changed event allocations, even though not that many properties actually have initialized observers.

![image](https://user-images.githubusercontent.com/2588062/63898120-f4a3ee80-c9f7-11e9-9bb8-bd1e2c77f0f0.png)

**Comment by ahopper** [comment]
yep, an event is created for every property
https://github.com/AvaloniaUI/Avalonia/blob/1b89f7dfea4302a84180f0dd7b32422d4e93682d/src/Avalonia.Base/AvaloniaPropertyRegistry.cs#L279
I'm rather hoping we can just get rid of most of this, but if not I did wonder if a single eventArgs object could be reused in cases like this on the assumption the process is synchronous.

**Comment by ahopper** [comment]
some more stats, in Control Catalog with every page visited, these are the counts of Avalonia Objects and properties set in NotifyInitialized

AvaloniaObjects 26369 
styled props 486198 (not attached or direct)
direct props 156376 
attached props 591084 
Average props per object 46

**Comment by MarchingCube** [comment]
I guess reusing events is problematic since we don’t know if the user won’t keep the event and store it somewhere. And a lot of .net framework events for property and collection changed are immutable. In my latest PR for AvaloniaList I already added event caching where it was possible.

**Comment by ahopper** [comment]
yep, it was just a thought and is probably too hard to control ( although in the current use in control catalog it would work).

**Comment by ahopper** [comment]
Checking _initialized.HasObservers before creating the event object would greatly reduce the allocations and might be a good pattern to use elsewhere. Avoiding looping through every property would be even better though.
