### ISSUE TITLE
DataGrid selection styling unreadable in dark theme

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2899]
Here is an example from the control gallery app with second row selected

![image](https://user-images.githubusercontent.com/17591364/63847819-807d3280-c986-11e9-963d-ed408f86f1e3.png)

**Comment by aguahombre** [comment]
Ditto grouping

![image](https://user-images.githubusercontent.com/17591364/63951003-ea740580-ca74-11e9-8020-afe228112a79.png)

**Comment by georgiuk** [comment]
A workaround. I am not sure if it is the best way.
```xml
      <DataGrid.Styles>
        <Style Selector="DataGridRow:selected /template/ Rectangle#BackgroundRectangle">
          <Setter Property="Fill" Value="#05769d"/>
        </Style>
      </DataGrid.Styles>
```
