### ISSUE TITLE
`SelectingItemsControl` bugs out when first item is removed on a 2-item List.

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#2901]
Setting a `SelectingItemsControl` with `SelectionMode` set to `AlwaysSelected`, selecting the first item then removing it causes the second item to be unselectable.
Related to #2898 
cc @danwalmsley

**Comment by danwalmsley** [comment]
@jmacato  has also pushed a repro for control catalog here:
https://github.com/AvaloniaUI/Avalonia/pull/2902
