### ISSUE TITLE
Radio Buttons Get Stuck When Switching Between Tabs. (Powershell and Avalonia)

### ISSUE THREAD

**Issue by MaynardMiner** [AvaloniaUI/Avalonia#2903]
Hello,

I am using Avalonia in Powershell. It took me awhile to figure it out, and I had to improve/fix the current module out for it with my own (see https://github.com/MaynardMiner/psavalonia) to make use of datagrids and ReactiveUI (I provide examples). But so far, I haven't had any issues, and I have been using a lot of different items.

The one thing I have noticed, is that I have radio buttons, that are placed in a grid, within a tabitem (tabcontrol). They work fine when I load the window, but when I switch between tabs, and then try to use them- They get "stuck", meaning they don't uncheck themselves when you switch between radio buttons.

The code behind them I am using is pretty simple:

```
## Location Tool

## Name Binding
$USA = Win "USA"
$ASIA = Win "ASIA"
$EUROPE = WIn "EUROPE"

## Change Param Location
$Change = {
    if($Config.Param.Location -ne "USA"){
        $Config.Param.Location = "USA"
    }
}
$USA.add_Click($Change)

$Change = {
    if($Config.Param.Location -ne "ASIA"){
        $Config.Param.Location = "ASIA"
    }
}
$ASIA.add_Click($Change)

$Change = {
    if($Config.Param.Location -ne "EUROPE"){
        $Config.Param.Location = "EUROPE"
    }
}
$EUROPE.add_Click($Change)
```
Note: "Win" is a function call to find the name of the radio button from the ``$window``.

And then obviously, I have a tabcontrol, and the radio buttons are in the first tabitem, inside a grid in the XAML. I can post the whole Xaml if needed to reproduce, but it's a larger file. This is a larger GUI project.

I figured I would mention the little bug I am seeing, but other than that- Good job on this project. It's a life-saver for someone who is constantly developing with Powershell across platforms.

**Comment by MaynardMiner** [comment]
https://github.com/MaynardMiner/SWARM/blob/alpha_testing/gui/MainWindow.xaml#L66

Here is the link to the XAML being used, if you wish to review. Bare in mind, it's in the "rough draft" phase, and I'm still trying to become familiar with Avalonia and XAML.

**Comment by Gillibald** [comment]
If this issue always occurs in combination with switching tabs there should be a way to write a small repro.

**Comment by MaynardMiner** [comment]
```
Import-Module ".\PSAvalonia\1.0\PSAvalonia.psd1"

$Xaml = '<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="900" d:DesignHeight="600"
        Width="900"
        Height="600"
        Title="Test_Radio_Buttons">

  <StackPanel Background="DarkGreen">
    <TabControl TabStripPlacement="Left" DockPanel.Dock="Top">
      <TabItem Header="Tab1">
      <Grid RowDefinitions="50,50,50">
                    <RadioButton GroupName="Location" Grid.Row="0" ZIndex="1" Name="USA" Content="USA" IsDefault="True" IsChecked="True" FontWeight="Bold" BorderBrush="Black" Foreground="Black"/>
                    <RadioButton GroupName="Location" Grid.Row="1" ZIndex="1" Name="EUROPE" Content="EUROPE" FontWeight="Bold" BorderBrush="Black" Foreground="Black"/>
                    <RadioButton GroupName="Location" Grid.Row="2" ZIndex="1" Name="ASIA"  Content="ASIA" FontWeight="Bold" BorderBrush="Black" Foreground="Black"/>
       </Grid>
      </TabItem>

      <TabItem Header="Tab2">
      <Grid RowDefinitions="50,50,50">
      <TextBlock Text="Test" />
      </Grid>
      </TabItem>
      </TabControl>
    </StackPanel>
  </Window>'

$window = convertTo-AvaloniaWindow -Xaml $Xaml
Show-AvaloniaWindow -Window $window
```

Requires the PSAvalonia module for powershell.

Small repro, as requested. Switch between the tabs, then try to use the radio buttons. They will no uncheck themselves/switch.

**Comment by Gillibald** [comment]
Thanks for the repro. Will have a look at it shortly.

**Comment by Gillibald** [comment]
I had a look at this and this is not related to TabControl. This is an issue with RadioButton itself.
