### ISSUE TITLE
Problems with a lot of controls

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#2905]
In Avalonia ui, when I have more then 2000 controls on window, I have a lof  of frizes of gui, the application freezes and responds slowly to clicking on Windows and Linux(Ubuntu) (don't tested on macos)
In wpf for  .net core has no problems with 10 000+ controls
Here is repo with avalonia on [gitlab](https://gitlab.com/maindlab/avalonia.triangle)
Here is the same vm+ m , but view on wpf [gitlab](https://gitlab.com/maindlab/wpf.core)
steps to reproduce
1) run app
2) press button "start"
3) wait 2-3 minutes
4) try to press "clear"

![photo_2019-08-28_20-55-39](https://user-images.githubusercontent.com/33497292/63920174-e8944d00-ca48-11e9-983f-829344bc4366.jpg)

**Comment by grokys** [comment]
I'll take a look at this but note that performance hasn't been a priority in Avalonia until recently (we were concentrating on getting stuff working!), but we're now going through the code and trying to improve performance, so hopefully we can fix this.

**Comment by CreateLab** [comment]
Sounds good
I like avalonia, and it works, that cool
belive that it will be fix.

**Comment by Gillibald** [comment]
Reusing the shape would also help here. You just draw the same shape at multiple places.
