### ISSUE TITLE
Documentation for InputElement.IsFocused

### ISSUE THREAD

**Issue by Tridy** [AvaloniaUI/Avalonia#2908]
When dealing with _InputElement_, I noticed that:
for the IsFocused, the documentation says "Gets or sets" but there is only a getter accessible:

![image](https://user-images.githubusercontent.com/7138873/63943116-4cca0780-ca6f-11e9-983a-481b08f22002.png)

that is in the documentation as well:
https://avaloniaui.net/api/Avalonia.Input/InputElement/E79E39DC

Even though it sates there that it has a private setter,

![image](https://user-images.githubusercontent.com/7138873/63942996-14c2c480-ca6f-11e9-8978-175cfb7b85f6.png)

should it have the reference to the _private_ setters in the documentations for the API?

**Comment by kekekeks** [comment]
Most likely a copy-paste from another property
