### ISSUE TITLE
OneWayToSource binding causes StackOverflow

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2912]
Using 0.8.999-cibuild0003713-beta I get a StackOverflowException if I use OneWayToSource binding to a control property

Here is a very simple repo using just a TextBox in the MainWindow with OneWayToSource  binding
[App12.zip](https://github.com/AvaloniaUI/Avalonia/files/3560374/App12.zip)

**Comment by HendrikMennen** [comment]
You sure it is fixed? I still a StackOverflow while binding the HorizontalScrollBarMaximum using OneWaytoSource. I use the newest nightly

**Comment by grokys** [comment]
Is it fixed for you @aguahombre ? 

Maybe it's a different issue, @HendrikMennen ? Could we get a repro?

**Comment by aguahombre** [comment]
It appears to be fixed in 0.8.999-cibuild0004187-beta.
My repo now runs without a StackOverflowException.
