### ISSUE TITLE
Customize social media preview

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#2914]
> Until you add an image, repository links expand to show basic information about the repository and the owner's avatar. Adding an image to your repository can help identify your project across various social platforms.

See how to do it: https://help.github.com/en/articles/customizing-your-repositorys-social-media-preview

I think it's possible to use a cropped image from the official site: http://avaloniaui.net/

**Comment by worldbeater** [comment]
Now our [GitHub repository card](https://github.com/topics/avalonia) looks like the following:

![image](https://user-images.githubusercontent.com/6759207/84868600-a0045980-b085-11ea-87ae-8a86f523e1a4.png)
