### ISSUE TITLE
Display of UserControl not working

### ISSUE THREAD

**Issue by edOasiot** [AvaloniaUI/Avalonia#2934]
Added a UserControl that inherits from Button to MainWindow, but It doesn't display

**UserControl1.xaml.cs**
using Avalonia;
using Avalonia.Controls;
using Avalonia.Styling;
using Avalonia.Markup.Xaml;
using System;

namespace AvaloniaApplication1
{
    public class UserControl1 : Button, IStyleable
    {
        public UserControl1()
        {
            this.InitializeComponent();
        }
        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
        Type IStyleable.StyleKey => typeof(Button);
    }
}

**UserControl1.xaml**
```
<UserControl` xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="AvaloniaApplication1.UserControl1">
</UserControl>

```
**MainWindow.xaml**
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:b="clr-namespace:AvaloniaApplication1;assembly=AvaloniaApplication1"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1" Width="200" Height="200">
  <StackPanel Margin="10" Spacing="5">
    <B.UserControl1 Name="UC" Width="100"/>
  </StackPanel>
</Window>

```

**Comment by edOasiot** [comment]
**MainWindow.xaml**:

<Window xmlns="https://github.com/avaloniaui"
        xmlns:b="clr-namespace:AvaloniaApplication1;assembly=AvaloniaApplication1"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1" Width="200" Height="200">
  <StackPanel Margin="10" Spacing="5">
    <B.UserControl1 Name="UC" Width="100"/>
  </StackPanel>
</Window>

**Comment by edOasiot** [comment]
MainWindow.xaml

//
<Window xmlns="https://github.com/avaloniaui"
        xmlns:b="clr-namespace:AvaloniaApplication1;assembly=AvaloniaApplication1"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1" Width="200" Height="200">
  <StackPanel Margin="10" Spacing="5">
    <B.UserControl1 Name="UC" Width="100"/>
  </StackPanel>
</Window>
//

**Comment by edOasiot** [comment]
> MainWindow.xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:b="clr-namespace:AvaloniaApplication1;assembly=AvaloniaApplication1"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1" Width="200" Height="200">
  <StackPanel Margin="10" Spacing="5">
    <B.UserControl1 Name="UC" Width="100"/>
  </StackPanel>
</Window>

**Comment by edOasiot** [comment]
`<Window xmlns="https://github.com/avaloniaui"
        xmlns:b="clr-namespace:AvaloniaApplication1;assembly=AvaloniaApplication1"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1" Width="200" Height="200">
  <StackPanel Margin="10" Spacing="5">
    <B.UserControl1 Name="UC" Width="100"/>
  </StackPanel>
</Window>
`

**Comment by edOasiot** [comment]
**UserControl1.xaml:**
`<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="AvaloniaApplication1.UserControl1">
</UserControl>
`

**Comment by ahopper** [comment]
User controls need to inherit from UserControl. You probably need to create a Templated Control for this https://avaloniaui.net/docs/authoring-controls/types-of-control

**Comment by edOasiot** [comment]
Can you point me to an example?
    On Friday, September 6, 2019, 11:03:16 AM CDT, ahopper <notifications@github.com> wrote:  
 
 
User controls need to inherit from UserControl. You probably need to create a Templated Control for this https://avaloniaui.net/docs/authoring-controls/types-of-control

**Comment by danwalmsley** [comment]
This is the same in any XAML framework,

https://www.wpftutorial.net/templates.html

an example:

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Default/Button.xaml

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Button.cs
