### ISSUE TITLE
TreeView not handling removing items correctly anymore

### ISSUE THREAD

**Issue by HendrikMennen** [AvaloniaUI/Avalonia#2944]
This happend on the newest nightly.
Before updating it worked fine so I am pretty sure it is a bug.

Everytime I delete an item in the treeview all other items below turn black and can't get accessed/selected anymore. In this example there were 4 files and I removed the second one so file3 and file4 turned black. I delete the Item just by removing it from the `ObservableCollection` in the viewmodel. 

![Unbenannt](https://user-images.githubusercontent.com/25281882/64494731-e4f69680-d290-11e9-9190-10107e1c2474.PNG)

This is my treeview
```xaml
<TreeView SelectedItem="{Binding SelectedItem}" DoubleTapped="Open_Click" DragDrop.AllowDrop="True" SelectionChanged="Tree_SelectionChanged" Grid.Row="1" Name="ProjectTree" Items="{Binding ProjectEntries}">
        <TreeView.ItemTemplate>
          <TreeDataTemplate ItemsSource="{Binding Items}">
            <StackPanel Orientation="Horizontal" Margin="0, 2, 0, 2">
              <Image Source="{Binding ImagePath, Converter={StaticResource pathToBitmapConverter}}" Height="17" Width="17" Margin="2, 0, 5, 0"/>
              <TextBox VerticalAlignment="Center" Margin="0,1,0,0" IsEnabled="{Binding TextBoxEditable}" Name="labelbox" Text="{Binding Header}" SelectionStart="{Binding SelectionStart}" SelectionEnd="{Binding SelectionEnd}" BorderThickness="{Binding TextBoxThickness}"/>
            </StackPanel>
          </TreeDataTemplate>
        </TreeView.ItemTemplate>       
</TreeView>
```

**Comment by alpensalamander** [comment]
noticed this aswell

**Comment by MarchingCube** [comment]
Caused by https://github.com/AvaloniaUI/Avalonia/pull/2922.
