### ISSUE TITLE
:pointerover not disappearing when cursor leaves the window entirely

### ISSUE THREAD

**Issue by hacklex** [AvaloniaUI/Avalonia#2946]
The title says it all.

Here's the simple test: https://pastebin.com/kLL0KHGa
To reproduce, hover the mouse over the menu, then move it to the left until it leaves the window. The menu won't disappear, although it is supposed to.

**Comment by ahopper** [comment]
This appears to be caused by `MouseDevive.Position' being set to the top left of the window on WM_MOUSELEAVE on windows. This causes hit testing to believe the mouse is still over the DockPanel in this case because it has no margin.
