### ISSUE TITLE
Cannot set attached event handler from XAML.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#2948]
For example doing this in `ControlCatalog.TreeViewPage`:

```
        <TreeView Items="{Binding Items}" SelectedItems="{Binding SelectedItems}" SelectionMode="{Binding SelectionMode}" Width="250" Height="350"
                  Gestures.DoubleTapped="TreeView_DoubleTapped">
```

Gives a compile error:

```
Unable to resolve suitable regular or attached property DoubleTapped on type Avalonia.Input:Avalonia.Input.Gestures
```

**Comment by kekekeks** [comment]
XamlIl looks for `AddDoubleTappedHandler` that is missing on `Gestures` class. That's what expected by WPF XAML parser too, see https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/attached-events-overview

**Comment by grokys** [comment]
👍 will add that then.

**Comment by ConnorFarrell3A** [comment]
I'm experiencing a similar issue with DragDrop events. I believe this is due to DragDrop not having the necessary event handlers.

_"Unable to resolve suitable regular or attached property DragOver on type Avalonia.Base:Avalonia.Input.DragDrop Line 1, position 2."_

**Comment by timunie** [comment]
@ConnorFarrell3A I really think this is a complete different issue. It's not wise to add this into a closed issue. If you think there is something to improve, please open a new issue.
