### ISSUE TITLE
Missing FileDialog filter options

### ISSUE THREAD

**Issue by b2soft** [AvaloniaUI/Avalonia#2949]
There are only 2 options that can be used in filters for FileDialog - InitialFileName and Extensions

In WPF I can specify filter to choose only files named as "Name.exe" in this way:
```
OpenFileDialog dlg = new OpenFileDialog();

dlg.Filter = "Name.exe|Name.exe";

if (dlg.ShowDialog() == true)
{
...
}
```

Requesting to add missing FileDialog's filter options (based on WPF) to Avalonia

**Comment by grokys** [comment]
@kekekeks @danwalmsley can this reasonably be implemented on all our dialog backends?

**Comment by kekekeks** [comment]
OSX file dialogs don't use glob patterns and need a list of accepted file extensions or [UTI](https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/UniformTypeIdentifier.html)s

**Comment by b2soft** [comment]
Is there any workaround to such a problem?

**Comment by kekekeks** [comment]
On OSX? No, I don't think we can restrict the system file dialog to use a fixed name.

**Comment by b2soft** [comment]
I'm targeting only Win and Linux, so OSX is not the case. What will be the best solution to have a strict filename inside file dialog (and not swtiching to WPF instead of avalonia)?

**Comment by kekekeks** [comment]
Copy-pasting dialog implementations and altering them to fit your needs, I guess.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/SystemDialogImpl.cs

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/NativeDialogs/GtkNativeFileDialogs.cs

**Comment by Toemsel** [comment]
```
            var fileExtensions = new List<string>() { $"dump|*.{fileExtension};" };
            var extensionFilter = new FileDialogFilter() { Extensions = fileExtensions };

            var dialog = new OpenFileDialog();
            dialog.AllowMultiple = false;
            dialog.Filters.Add(extensionFilter);
            await dialog.ShowAsync(DjiWindow.Instance);
```

Will throw an ArgumentException, as a filter has been defined. Without the filter it works just fine.

**Comment by chyyran** [comment]
> Copy-pasting dialog implementations and altering them to fit your needs, I guess.
> 
> https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/SystemDialogImpl.cs
> 
> https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/NativeDialogs/GtkNativeFileDialogs.cs

This is untenable because many of the internal APIs used are protected and inaccessible, and we end up needing to vendor a large chunk of Avalonia, not to mention requiring `unsafe` in the project just for fixed name filters.

**Comment by maxkatz6** [comment]
Filter as it is in WPF won't be supported in Avalonia.
Instead, special `FilePickerFileType` will be used (as opposite of what's currently available):
```csharp
class FilePickerFileType
{
    string Title { get; init; }
    // For desktop
    IReadOnlyList<string> Extensions {get; init; }
    // For web and android
    IReadOnlyList<string> MimeTypes {get; init; }
    // For Apple platforms
    IReadOnlyList<string> AppleUniformTypeIdentifiers {get; init; }
}
```

For more details see https://github.com/AvaloniaUI/Avalonia/issues/7234 and https://github.com/AvaloniaUI/Avalonia/pull/8303

**Comment by chyyran** [comment]
Will `FilePickerFileType` allow a fixed filename on supported platforms? There is already a specialization for Apple platforms for UTIs, so I don't see why this functionality would be left out when targeting only platforms where fixed filename filters are supported.

**Comment by maxkatz6** [comment]
You can set suggested file name and a type extension. Not much flexibility here with non-windows platforms.

**Comment by chyyran** [comment]
In addition to Windows, [GTK also allows glob-style filters](https://docs.gtk.org/gtk3/class.FileFilter.html). It is only macOS and mobile/Wasm platforms that do not support this. 

There is already a specialization for Apple platforms with UTIs that are only relevant on iOS and macOS. It would not be difficult to add a property to support fixed filename filters on platforms that support it, which does not just include Windows.

**Comment by chyyran** [comment]
To be clear here I am not asking for full support of WPF style globs. Simply allowing the file picker to filter on a fixed name will already go a long way.

**Comment by chyyran** [comment]
If full support for globs made it in that would be great as well
