### ISSUE TITLE
Binding for Items property in Carousel causes StackOverflowException

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#2957]
In recent builds (0.8.999-cibuild0003941-beta) bindings stopped working for Carousel. On older versions (<= 0.8.999-cibuild0003548-beta) this code worked without problems. StackOverflowException is thrown when an item added to the collection.

XAML:

```xml
<Carousel
            Items="{Binding Workspaces}"
            SelectedItem="{Binding SelectedWorkspace}">
            
            <Carousel.ItemTemplate>
                <DataTemplate>
                    
                    <!-- some controls -->
                    
                </DataTemplate>
            </Carousel.ItemTemplate>
            
        </Carousel>
```

Model:

```csharp
[AddINotifyPropertyChangedInterface]
    public class WorkspacePadModel : ISupportsActivation
    {
        public ObservableCollectionExtended<WorkspaceModel> Workspaces { get; set; }
            = new ObservableCollectionExtended<WorkspaceModel>();
```

**Comment by x2bool** [comment]
So what I discovered is that when using binding to `ObservableCollectionExtended<T>` StackOverflowException is thrown somewhere in Avalonia. As long as there is no binding in XAML everything works as expected.

I was wrong about TabStrip, this only happens with Carousel (I had both in my code).

**Comment by x2bool** [comment]
Going deeper this is a result of combining SelectionMode.AlwaysSelected with NotifyCollectionChangedAction.Add in SelectingItemsControl. This leads to the recursive update of SelectedItemProperty which causes StackOverflowException.

**Comment by grokys** [comment]
I've tried to repro this [on a branch](https://github.com/AvaloniaUI/Avalonia/compare/fixes/2957-carousel-stackoverflow) but I'm unable to. Do you think you could modify the code changed in 350633c08fc419231690048c1c5a7673efa5c987 to repro the problem?

**Comment by x2bool** [comment]
Thanks for the quick reply.

On this branch the issue does not reproduce. I suspect this is a combination of multiple controls/bindings. I'll fork your branch and I'll be back with more specific conditions when this happens.

**Comment by x2bool** [comment]
Turns out I ignored the fact that there is a Mode=OneWayToSource param in the binding. So this issue is a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2912

Thanks for your time.
