### ISSUE TITLE
Window.ShowDialog does not block parent window(Linux)

### ISSUE THREAD

**Issue by SpectreZero** [AvaloniaUI/Avalonia#2958]
On Windows, everything works fine.
On Linux, the window opens as not modaland I have access to the parent window.

**Comment by jhofinger** [comment]
Reproduced in Avalonia 0.10.0, Ubuntu 20.04. Most operations are blocked in the parent window, but styles are still updated on hover/click.

Most importantly, the context menu is still fully functional!) If the dialog was opened from a context menu, you can open the same dialog again, and chaos ensues.

**Comment by luthfiampas** [comment]
> Reproduced in Avalonia 0.10.0, Ubuntu 20.04. Most operations are blocked in the parent window, but styles are still updated on hover/click.
> 
> Most importantly, the context menu is still fully functional!) If the dialog was opened from a context menu, you can open the same dialog again, and chaos ensues.

Not too familiar with X11, perhaps we need `_NET_WM_STATE_MODAL` atom as well. For now the best hack I think is to create overlay element that will be shown when `ShowDialog` is being called.

**Comment by Robotanchik** [comment]
If dialog called from main menu then it works as expected (parent window is blocked), but if it called from context menu that attached to TreeView Item, it does not block parent window

**Comment by RomanKalachik** [comment]
Any updates on this issue?
