### ISSUE TITLE
OSX Popup Positioning not working

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#2962]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/4672627/64633911-fb693300-d3f3-11e9-9cb7-d6277c8358ee.png">

**Comment by x2bool** [comment]
Related: https://github.com/AvaloniaUI/Avalonia/issues/2923

**Comment by grokys** [comment]
Closing as duplicate of #2923
