### ISSUE TITLE
Raspbian Buster - window controls unresponsive

### ISSUE THREAD

**Issue by ebswift** [AvaloniaUI/Avalonia#2963]
Developing in VS 2019, Avalonia 0.8.2, .Net Core 2.2 the app runs fine on windows.  If I publish it and copy it to the raspi the app runs, renders the window and can display console output but it will not respond to any input.  I also published directly from the raspi terminal and it made no difference.

Here is a self-contained compiled version, it is basically just a compiled version of a YT tutorial:

https://drive.google.com/open?id=1-3yTaSeswQUOxi48d86Ug9_A33gCS_d7

Following the Avalonia tutorial produced the same result - a working app but non-responsive window.  Running on Raspbian Stretch produces no text on the window and flattened controls, Buster renders correctly but doesn't respond.  If I minimise the window then restore it, the window shows a repeating pattern of the restore transition, so basically garbage

**Comment by kekekeks** [comment]
Should be already fixed in nightly builds.

**Comment by ebswift** [comment]
I have this worked out now, I was looking at it for some days before making the report.  I used these to get a new project working from fresh:

* Use nightly Avalonia from Nuget 0.8.999-cibuild0003941-beta https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed
* Install Avalonia.Skia.Linux.Natives, then on Windows I also had to create the SkiaSharp.dll.config in the folder where a compile error reported it was missing, I placed this in the contents of the file:
(I don't know how to post the correctly formatted XML so remove the spaces after < and before >):
< ?xml version="1.0" encoding="UTF-8"? >
< configuration >
< /configuration >

* Use this workaround: https://github.com/AvaloniaUI/Avalonia/pull/2322#issuecomment-508679730
