### ISSUE TITLE
Deriving from TreeView breaks TreeViewItem margins

### ISSUE THREAD

**Issue by cocacola89** [AvaloniaUI/Avalonia#2971]
`TreeViewItem` margins get messed up for any control deriving from `TreeView`, e.g.
```CSharp
public class MyTreeView : TreeView, IStyleable
{
    Type IStyleable.StyleKey => typeof(TreeView);
}
```

This is caused by method `CalculateDistanceFromLogicalParent` in [TreeViewItem.cs](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TreeViewItem.cs), which looks up parent `TreeView` using strict type comparison `logical.GetType() != typeof(T)` instead of `!(logical is T)`:
```CSharp
private static int CalculateDistanceFromLogicalParent<T>(ILogical logical, int @default = -1) where T : class
{
    var result = 0;
    while (logical != null && logical.GetType() != typeof(T))
    {
        ++result;
        logical = logical.LogicalParent;
    }
    return logical != null ? result : @default;
}
``` 

This causes setting `Level` property of `TreeViewItem` to `-2`, which messes up margins in default `TreeViewItem` [style](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Default/TreeViewItem.xaml).

```CSharp
protected override void OnAttachedToLogicalTree(LogicalTreeAttachmentEventArgs e)
 {
    base.OnAttachedToLogicalTree(e);

    _treeView = this.GetLogicalAncestors().OfType<TreeView>().FirstOrDefault();

    Level = CalculateDistanceFromLogicalParent<TreeView>(this) - 1;

    if (ItemTemplate == null && _treeView?.ItemTemplate != null)
    {
        ItemTemplate = _treeView.ItemTemplate;
    }
}
``` 

This situation is reproducible in latest Release and nightly builds.

**Comment by grokys** [comment]
Hi @cocacola89, thanks for the issue and for investigating and finding the correct fix! Should be fixed in https://github.com/AvaloniaUI/Avalonia/pull/3050.
