### ISSUE TITLE
non-decorated Windows Resize broken on Linux

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#2973]
@kekekeks  "mouse capture is not reset
we kinda need to change the api"

@jmacato "iv seen this before"

**Comment by jmacato** [comment]
Sometimes it does that randomly when resized. Definitely a pointer capture issue since when locked to resizing mode you can't click anything else inside the app.

**Comment by kekekeks** [comment]
We basically need to pass PointerEventArgs to Begin(Move/Resize)Drag so it will reset the pointer capture. I think it's also required to pass the event id to start dragging on Wayland, so it will be required anyway.
