### ISSUE TITLE
DirtyVisuals.Clear throws quite a lot

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2977]
I'm catching and exception here https://github.com/AvaloniaUI/Avalonia/blob/4c557af078615cab9da9741fbd914a91dbdc2f16/src/Avalonia.Visuals/Rendering/DirtyVisuals.cs#L70 from time to time while debugging. This cannot be a good thing.

**Comment by kekekeks** [comment]
It also gives me an empty window on Linux after moving mouse

**Comment by kekekeks** [comment]
I've also just got this
>System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
>  at at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
>  at at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
>  at Avalonia.Rendering.DirtyVisuals.Add(IVisual visual) in /home/kekekeks/Projects/Avalonia/src/Avalonia.Visuals/Rendering/DirtyVisuals.cs:42

**Comment by kekekeks** [comment]
Nvm, I've broken our dispatcher.

**Comment by KyleC69** [comment]
I am having the same issue that just popped up recently

[Visual] Exception in render loop: 'System.InvalidOperationException: Cannot clear while enumerating
   at Avalonia.Rendering.DirtyVisuals.Clear() in /_/src/Avalonia.Visuals/Rendering/DirtyVisuals.cs:line 70
   at Avalonia.Rendering.DeferredRenderer.UpdateScene() in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 701
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 416
