### ISSUE TITLE
Cannot preselect TabItem in TabControl

### ISSUE THREAD

**Issue by Mikaka27** [AvaloniaUI/Avalonia#2987]
Hi,
I would like to have a TabControl that initially has non-first column selected (second one for example).
See picture:
![TabItemSelected](https://user-images.githubusercontent.com/9214100/64849288-5d53b380-d613-11e9-8687-b06e8488388c.png)

Setting `SelectedIndex=2` on `TabControl` itself changes nothing.
Settings `IsSelected=True` on `TabItem` causes `NullReferenceException`
![TabControlBug](https://user-images.githubusercontent.com/9214100/64848827-5f694280-d612-11e9-9375-4c876758e136.PNG)

Here is xaml that causes this:
```
<TabControl SelectedIndex="2">
    <TabItem Header="Column 1">
        <TextBlock Text="Column 1 content" />
    </TabItem>
    <TabItem Header="Column 2" IsSelected="True">
        <TextBlock Text="Column 2 content" />
    </TabItem>
    <TabItem Header="Column 3">
        <TextBlock Text="Column 3 content" />
    </TabItem>
</TabControl>
```

Attaching reproduction case here:
[AvaloniaApplication2.zip](https://github.com/AvaloniaUI/Avalonia/files/3609114/AvaloniaApplication2.zip)

**Comment by Gillibald** [comment]
Will have a look. Keep in mind indeces are zero based so the second TabItem has index 1 not 2
