### ISSUE TITLE
Window not rendered after Hide()

### ISSUE THREAD

**Issue by MonkAlex** [AvaloniaUI/Avalonia#2994]
Use windows7

Create new project from Avalonia Application template
For MainWindow add:
```
        protected override void HandleWindowStateChanged(WindowState state)
        {
            if (state == WindowState.Minimized)
            {
                this.Hide();
                Task.Run(async () =>
                {
                    await Task.Delay(1000);
                    Dispatcher.UIThread.Post(() =>
                    {
                        var window = this;
                        window.Show();
                        window.Activate();
                        if (window.WindowState == WindowState.Minimized)
                            window.WindowState = WindowState.Normal;
                    });
                });
            }

            base.HandleWindowStateChanged(state);
        }
```

Run (netcore 2.1), minimize, wait
On minimize-show render broken and show black screen:
![image](https://user-images.githubusercontent.com/6784764/64907723-4abaa680-d707-11e9-9d34-dc1433267a25.png)

If i manual resize window after that - all rendered and work fine.
Keyboard events to change VM run render too.
Mouse events dont work.

UPD: also reproduce on second hide-show when run on windows10
not reproduced on macos

UPD2: linux mint 18 (in virtual box) showed bad, resize help too:
![linux](https://user-images.githubusercontent.com/6784764/64908089-7db36900-d70c-11e9-9ada-eef2c9bfd9b6.png)

**Comment by MonkAlex** [comment]
On Windows7 help this simple code:
```
                        window.Show();
                        window.Width += 0.1;
```
Mint not tested.
Ugly, but work :persevere:

**Comment by jmacato** [comment]
Confirmed working on Cinnamon+Ubuntu 18.04. We need to add InvalidateVisual on Window.Activate i suppose.

**Comment by josegomez** [comment]
Can confirm this is still an issue on 0.9.9
![Render](https://user-images.githubusercontent.com/420837/80621800-d3c3eb00-8a15-11ea-8670-ff568a3e16bd.gif)

Workarounds such as changing screen size, InvalidateMeasure() and InvalidateVisual() don't always work consistently.

**Comment by kekekeks** [comment]
Please, record the events sent to the window via `xev -id <window id>`. Window id can be obtained via `xwininfo` utility.

**Comment by alexhauser** [comment]
@kekekeks, here is a link to the recorded window events that you've requested:
https://pastebin.com/y4reQ70T

This is from the same app that @josegomez has postet screenscasts of in the post above.
The last "minimize to tray" and then "restore" triggered the garbled display.

**Comment by kekekeks** [comment]
I don't see any `Expose` events being sent to the window (we are treating them in the same way as WM_PAINT). I guess we should handle `VisibilityNotify` in the same way and trigger an immediate repaint.
