### ISSUE TITLE
Progress bar with zero value still shows one pixel

### ISSUE THREAD

**Issue by RedlineTriad** [AvaloniaUI/Avalonia#3011]
When creating a progress bar, even with a value of zero, it still displays a sliver of progress one pixel wide.
![image](https://user-images.githubusercontent.com/39059512/65165062-53301b80-da3e-11e9-8b91-5aac7b02deed.png)
This is most likely unintended behavior.

**Comment by JaggerJo** [comment]
@grokys Whats the expected style here ?

The intermediate progress bar does not have the 1px margin on the sides the normal progress bar has.

![image](https://user-images.githubusercontent.com/13090415/65315992-5d1a6180-db99-11e9-8d86-7e5f068e335b.png)

If I set the border thickness on the indicator part to 0 it works. This could be done on the horizontal version with left/right and on the vertical version with top/bottom thickness. This should work fine.

I can create a PR but wanted to check with you what the desired style is :)

<img width="283" alt="image" src="https://user-images.githubusercontent.com/13090415/65316230-d31ec880-db99-11e9-9df6-7bb17af57604.png">

<img width="283" alt="image" src="https://user-images.githubusercontent.com/13090415/65316288-f8133b80-db99-11e9-9623-2708c4573d22.png">

**Comment by grokys** [comment]
Not sure tbh, I've not had anything to do with `ProgressBar`. I really don't mind whether it has a border or not, the only important thing is the two styles are the same IMO.

**Comment by JaggerJo** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/3017
PR is open 😉

**Comment by JaggerJo** [comment]
PR is merged. Should be fixed in the current CI / Nightly build.
