### ISSUE TITLE
Extending Panel caused "Exception has been thrown by the target of an invocation." error

### ISSUE THREAD

**Issue by edOasiot** [AvaloniaUI/Avalonia#3013]
I was able to Extend TextBox and CheckBox, but not Panel:

**OAS_Panel.xaml**
```
<Panel xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="OASAvalonia.OAS_Panel">
</Panel>
```
**OAS_Panel.xaml.cs**

```
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using Avalonia.Media;
using Avalonia.Styling;
using System;

namespace OASAvalonia
{
    public class OAS_Panel : Panel, IStyleable
    {
        public OAS_Panel()
        {
            this.InitializeComponent();
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }

        Type IStyleable.StyleKey => typeof(Panel);
    }
}
```

**MainWindow.xaml**

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:b="clr-namespace:OASAvalonia;assembly=OASAvalonia"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="1200" d:DesignHeight="500"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="OAS / Avalonia Application" Width="1200" Height="500">
      <b:OAS_Panel Background="AliceBlue"/>
</Window>
```

**Comment by danwalmsley** [comment]
My suspicion is that its not happy with _ in class name, can you remove and see if the problem goes away?

Also are you using nightly builds? if not try https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

and see if it fixes it, or you get a more useful error message.

**Comment by edOasiot** [comment]
Removing the "_" didn't change the error.
Using the latest nightly build caused this error:
CS1061	'Application' does not contain a definition for 'Run' and no accessible extension method 'Run' accepting a first argument of type 'Application' could be found (are you missing a using directive or an assembly reference?)

**Comment by Gillibald** [comment]
Panel isn't a TemplatedControl and has no visual representation. It is just a container that arranges children. So this will never work the way you want it to work.

**Comment by ahopper** [comment]
the error from nightly builds can be fixed by following https://github.com/AvaloniaUI/Avalonia/wiki/Application-lifetimes
this won't fix the other problem.

**Comment by ahopper** [comment]
You may well have very good reason to subclass these controls but in typical usage this is quite a rare thing to do. It is more common to tweak or change the template using the styling system.

**Comment by danwalmsley** [comment]
@edOasiot oh yeah, not templates for panels, here is about the simplest example I can find of custom panel implementation...

https://github.com/AvaloniaUI/Avalonia/blob/xdatagrid-experiment/samples/RenderDemo/Pages/XDataGridDockPanel.cs
