### ISSUE TITLE
Rendering subsystem TODOs

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#3014]
- Copy-on-write lists
- struct everything (basically all drawing ops could be represented by a single struct with `Type` field
- schedule update on scene consume
- actual layers
- pause timers when nothing happens
- separate render thread for each window to avoid blocking other windows on v-sync

**Comment by kekekeks** [comment]
Animations should also tick on scene update
to avoid triggering animators multiple times between rendered frames
i. e. the render cycle would be:
```
while(true)
{
        if(ConsumeSceneAndTriggerUpdate())
              Render();
}
```
Which would schedule an update to the UI thread for that particular toplevel. The update routine should trigger animation tick, run layoutmanager pass for that particular toplevel and only then build the scene. That way we'll be preparing the next scene graph version while the render thread renders the current one. And won't run any unnecessary computations if renderer can't keep up with the UI thread for some reason.

The only problem would be animations that tick slower than the render timer, so we need to somehow switch the animation timer to something else once the render one gets paused.

**Comment by jmacato** [comment]
@kekekeks i wonder if they can be independent, both timers updating at their own pace.

**Comment by MarioGK** [comment]
Any updates on this issue?
