### ISSUE TITLE
Canvas is not clearing children correctly on current master

### ISSUE THREAD

**Issue by HendrikMennen** [AvaloniaUI/Avalonia#3019]
The Canvas takes about 5-10 times longer on current master to update than it did before.
Ram usage is about the same.

It also appears to not remove it's children correctly anymore while calling canvas.children.Clear()

## before
0.8.999-cibuild0004086-beta
![2019-09-2019-06-15](https://user-images.githubusercontent.com/25281882/65345235-0e40ec00-dbda-11e9-851a-8014e35735ae.gif)

## after
0.8.999-cibuild0004126-beta
![2019-09-2019-07-42](https://user-images.githubusercontent.com/25281882/65345249-1731bd80-dbda-11e9-9191-c80d9f8f6d8c.gif)

**Comment by MarchingCube** [comment]
Could you provide a small repro case?

**Comment by HendrikMennen** [comment]
https://github.com/HendrikMennen/CanvasRepro
I know the performance difference is not really noticeable here. Could be because of using DispatcherTimer?

However it shows that there seems to be something wrong with Canvas.Children.Clear(), since the Canvas is not cleared anymore in the second picture



0.8.999-cibuild0004086-beta
![2019-09-2115-01-08](https://user-images.githubusercontent.com/25281882/65373754-ef963000-dc81-11e9-84f0-285c79fa1f3f.gif)


0.8.999-cibuild0004126-beta
![2019-09-2114-59-50](https://user-images.githubusercontent.com/25281882/65373744-c07fbe80-dc81-11e9-84b7-eeb96c9bfc47.gif)

**Comment by ahopper** [comment]
the dirty rects don't appear to be correctly updated on removing items.

**Comment by ahopper** [comment]
removing this line https://github.com/AvaloniaUI/Avalonia/blob/0491a0de3554a86c3e4372822ebfb313e6fc2a88/src/Avalonia.Visuals/Rendering/SceneGraph/VisualNode.cs#L216 makes it work (not the solution but a pointer maybe) @grokys

**Comment by grokys** [comment]
Thanks @ahopper - looks like this was introduced by #3004 then. Will look into it.

**Comment by ahopper** [comment]
In debugging this the `Bounds` of the `Lines` in the repro seemed to have zero height by the time they were added to the dirty rects.

**Comment by Gillibald** [comment]
When you clear a control's children should that invalidate the region that is covered by the control?
