### ISSUE TITLE
[XAML Compiler] Using enum as resource key crashes

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#3021]
Using an enum as resource key in `App` or `Window`, causes an `ExecutionEngineException`. In a `UserControl`, an exception is thrown because the key is being passed as null.

## Example
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:ns="clr-namespace:MyNamespace"
        x:Class="MyNamespace.MyWindow">
    <Window.Resources>
        <x:String x:Key="{x:Static ns:MyEnum.A}">Resource</x:String>
    </Window.Resources>
</Window>
```

```cs
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace MyNamespace
{
    enum MyEnum { A, B, C }

    class MyWindow : Window
    {
        public MyWindow()
        {
            InitializeComponent();
        }

        private void InitializeComponent() => AvaloniaXamlLoader.Load(this);
    }
}
```

**Comment by tomenscape** [comment]
There is no crash when using enum values as resource keys in Avalonia 11.

**Comment by maxkatz6** [comment]
Yep, I also used them. Will reopen if anybody face it again.

**Comment by Flithor** [comment]
```
<Window.Resources>
    <x:String x:Key="{x:Static ns:MyEnum.A}">Resource</x:String>
</Window.Resources>
```
Now it give me this: `System.Xaml.XamlException: Value cannot be null. (Parameter 'key')`

**Comment by timunie** [comment]
@Flithor it's only supported in upcomming v11.0

**Comment by novikoff** [comment]
It is still not supported in Avalonia v11.1.3.

`<Button HorizontalAlignment="Stretch" Margin="0 5 0 0" Command="{Binding ShowInputDialogAsyncCommand}" CommandParameter="{x:Static enums:EditableFrames.WORLD_TRACKER}" >Edit</Button>`

how much longer do we have to wait 2019-2024?
