### ISSUE TITLE
does avalonia support mdi layout for game development?

### ISSUE THREAD

**Issue by Shadowblitz16** [AvaloniaUI/Avalonia#3022]
does avalonia support mdi layout for game development?
if not can this be added? it's not often used, but it has its use cases.

**Comment by danwalmsley** [comment]
check out https://github.com/vitalelement/avalonstudio.shell

its used by a few apps....

![image](https://user-images.githubusercontent.com/4672627/65394920-55221380-dd8b-11e9-800d-cf607025809e.png)

![image](https://user-images.githubusercontent.com/4672627/65394925-6b2fd400-dd8b-11e9-9d3a-e85d4c5b4302.png)

**Comment by Shadowblitz16** [comment]
there doesn't seem to be much information on that page.
what exactly is it?

**Comment by jmacato** [comment]
@Shadowblitz16 it's a package that lets you do dockable windows akin to Visual Studio. Not exactly the MDI thingy that you're looking for but it's better imho.

**Comment by wieslawsoltes** [comment]
> @Shadowblitz16 it's a package that lets you do dockable windows akin to Visual Studio. Not exactly the MDI thingy that you're looking for but it's better imho.

@jmacato I was actually thinking about adding support for MDI layout to Dock. We already have floating window support. 

@Shadowblitz16 The MDI layout probably can be added to Dock control. I have created issue to track discussion and proposals here: https://github.com/wieslawsoltes/Dock/issues/112

**Comment by danwalmsley** [comment]
So avalonia doesnt support this, its something to be built with Avalonia, and there are a few related community projects as above that do this.

**Comment by danwalmsley** [comment]
@Shadowblitz16 you are probably looking for some layout like this

![image](https://user-images.githubusercontent.com/4672627/65774805-e6500c00-e136-11e9-84b5-332a0030221e.png)

Dock / AvalonStudio.Shell supports this already.

MDI would just replace the tabs, with a kind of windowing area in the middle.

**Comment by Shadowblitz16** [comment]
@danwalmsley this doesn't work. I want to have child windows inside a container, I don't care if they are docked or not.
