### ISSUE TITLE
[Feature Request] Mouse extra buttons

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#3031]
WPF supports the extra mouse buttons (`XButton1` and `XButton2`) with the `MouseDown` event. I believe Avalonia should have an API to handle these buttons. I think this would be part of the `PointerPoint`/`PointerPointProperties` API.

For reference: [WPF MouseButton enum](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.mousebutton)

**Comment by keldor314** [comment]
Some mice have more than 5 buttons.  For instance, my Logitech MX Master 2S has 6 buttons and 2 wheels.  It would be nice to just have an array view for each set, with things like LeftButton being convenient enumerations.

This would let me do things like bind horizontal scrolling to the second mouse wheel, which is what it's designed for, but it's hard to find good software support.

**Comment by egorozh** [comment]
Does it work on macOS? I subscribe to PointerPressed and the event is not handled.

Avalonia version: 0.10.17
MacOs: 12.5 (M1)
