### ISSUE TITLE
Dialog Title, OpenFolderDialog, OpenFileDialog

### ISSUE THREAD

**Issue by GitHubington** [AvaloniaUI/Avalonia#3037]
The title field in OpenFolderDialog is not being applied when the dialog shows. Although, OpenFileDialog applies the title just fine.

**Comment by kekekeks** [comment]
Which OS?

**Comment by gitgiggity** [comment]
Windows 7 x64

**Comment by kekekeks** [comment]
[frm.SetTitle](https://github.com/AvaloniaUI/Avalonia/blob/87021ec10b0111eabce75b4bcb9b5a323c29483f/src/Windows/Avalonia.Win32/SystemDialogImpl.cs#L43) is missing for the folder dialog: https://github.com/AvaloniaUI/Avalonia/blob/87021ec10b0111eabce75b4bcb9b5a323c29483f/src/Windows/Avalonia.Win32/SystemDialogImpl.cs#L116
