### ISSUE TITLE
ItemsRepeater does not respect control alignment

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#3040]
`ItemsRepeater` does not currently respect the `HorizontalAlignment`/`VerticalAlignment` of child controls.

This seems to work on UWP so there's something up with our port.

**Comment by grokys** [comment]
This does actually seem to work correctly when the `ItemsRepeater` is not contained within a `ScrollViewer` which has horizontal scrolling enabled (as in ControlCatalog). I do however think it could handle this a bit better, need to double check with UWP and raise an issue there if necessary.

**Comment by lostmsu** [comment]
@grokys I recently stumbled upon `ItemRepeater` not honoring `HorizontalAlignment`. To my surprise, `ListBox` does o-O

```xaml
<StackPanel
            Orientation="Vertical"
            VerticalAlignment="Center" HorizontalAlignment="Center"
            >
  <ItemsRepeater Items="{Binding RecentDirectories, ElementName=Root, Mode=OneWay}"
                 HorizontalAlignment="Center"
                 >
    <ItemsRepeater.ItemTemplate>
      <DataTemplate>
        <Button Content="{Binding Name, Mode=OneWay}"
                Command="{Binding OpenFolderCommand, ElementName=Root, Mode=OneTime}"
                CommandParameter="{Binding FullPath, Mode=OneWay}"
                CornerRadius="0"
                />
      </DataTemplate>
    </ItemsRepeater.ItemTemplate>
  </ItemsRepeater>

  <Button ... />
</StackPanel>
```

With `ItemsRepeater` (e.g. above XAML):
![image](https://user-images.githubusercontent.com/239520/188217893-9bc0ade0-808a-4769-9129-b8eff539ac61.png)

If I replace `ItemsRepeater` with `ListBox` in the above:
![image](https://user-images.githubusercontent.com/239520/188218001-8cf68c85-d59f-47f4-9e41-f20ab661408d.png)

Avalonia 0.10.18 on Windows
