### ISSUE TITLE
 TextBlock.Text is invalid in Action

### ISSUE THREAD

**Issue by rakuten** [AvaloniaUI/Avalonia#3046]
OS: Mac 10.14.4
Version: 0.8.2
Project type: avalonia.app

When OnTicker is triggered, the setting of Text is always invalid.

```CSharp
//In my program
vo.OnTicker = new Action(OnTicker);
private void OnTicker()
{
     string str = vo.TickerData.ToString();
     pirceTxt.Text = str;
 }

//In the vo class
private Action OnTicker;
```

**Comment by ahopper** [comment]
Is OnTicker being called on the ui thread? You can generally only set properties of AvaloniaObjects on the ui thread, if this is the problem you can use Dispatcher.UIThread.InvokeAsync.

**Comment by rakuten** [comment]
@ahopper  thank you very much

After using Dispatcher.UIThread.InvokeAsync, the problem is solved.
