### ISSUE TITLE
How compile for Mac OS? 

### ISSUE THREAD

**Issue by MakcStudio** [AvaloniaUI/Avalonia#3051]
Hi, everybody. I don't understand the documentation..
The main system is windows 10, I installed mac os through vmware . On mac os put .net core 2.1 (did not install anything else)

I need to develop one project for several systems at once. I want it to compile under both my windows and MacOS , but I don't understand how to do it. 

An example of https://github.com/AvaloniaUI/avalonia-dotnet-templates
it compiles under windows and linux without problems, but it does not work under mac.. How can I fix this?

**Comment by MakcStudio** [comment]
um.. I'm an idiot, I just tried it again with 0 and it worked.. This is strange, tell me, can I create an application so that when running on Mac OS it does not require the installation of .net core?

**Comment by danwalmsley** [comment]
@MakcStudio you do not need to compile on seperate systems.

From windows or linux or mac, you can run the command:

`dotnet publish -c Release -f netcoreapp2.2 -r win-x64`
`dotnet publish -c Release -f netcoreapp2.2 -r linux-x64`
`dotnet publish -c Release -f netcoreapp2.2 -r osx-x64`

The outputs of these build commands will run on the respective systems.

if you target .net core 3.0 you can also publish to a single executable.

**Comment by MakcStudio** [comment]
> @MakcStudio you do not need to compile on seperate systems.
> 
> From windows or linux or mac, you can run the command:
> 
> `dotnet publish -c Release -f netcoreapp2.2 -r win-x64`
> `dotnet publish -c Release -f netcoreapp2.2 -r linux-x64`
> `dotnet publish -c Release -f netcoreapp2.2 -r osx-x64`
> 
> The outputs of these build commands will run on the respective systems.
> 
> if you target .net core 3.0 you can also publish to a single executable.

I just installed some systems for testing. Only began deal with Avalonia , have been arguing understand as to wage 1 project under all system..

**Comment by MakcStudio** [comment]
> @MakcStudio you do not need to compile on seperate systems.
> 
> From windows or linux or mac, you can run the command:
> 
> `dotnet publish -c Release -f netcoreapp2.2 -r win-x64`
> `dotnet publish -c Release -f netcoreapp2.2 -r linux-x64`
> `dotnet publish -c Release -f netcoreapp2.2 -r osx-x64`
> 
> The outputs of these build commands will run on the respective systems.
> 
> if you target .net core 3.0 you can also publish to a single executable.

![image](https://user-images.githubusercontent.com/41212099/65959084-c03dab00-e459-11e9-8166-96bdafab206c.png)

I compiled the sample App on MacOS, removed .net core and it works
Do so:

But then compiled on windows with the same parameters and transferred to Mac, now it does not work.

In both cases used the command:

dotnet publish -f netcoreapp2. 1-c Release-os x-x64

**Comment by MakcStudio** [comment]
I moved the files I compiled on Mac OS to another MacOS (.net core was never installed There)

And the program does not start there, with the same error as in the picture above

This is very strange, because I removed .net core on my Mac and it still works.

**Comment by kekekeks** [comment]
If you are transferring published binaries from a windows machine to OSX/Linux, you need to use `chmod +x` on your executable

**Comment by MakcStudio** [comment]
> If you are transferring published binaries from a windows machine to OSX/Linux, you need to use `chmod +x` on your executable

how to do it? I still don't understand, do I have to have .net core installed to run my app on MacOS?

**Comment by kekekeks** [comment]
` dotnet publish -c Release -f netcoreapp2.2 -r osx-x64 -o publish-osx` will create a self-contained app distribution in `publish-osx` directory. It can copied to OSX machine, but you need to run `chmod +x` on the executable in Terminal because Windows doesn't know anything about UNIX file access flags.

**Comment by MakcStudio** [comment]
> ` dotnet publish -c Release -f netcoreapp2.2 -r osx-x64 -o publish-osx` will create a self-contained app distribution in `publish-osx` directory. It can copied to OSX machine, but you need to run `chmod +x` on the executable in Terminal because Windows doesn't know anything about UNIX file access flags.

This helped) thank you very much)
Can you tell me how to minimize the console after opening?

Кстати, ты, видимо, русский?) Спасибо)

**Comment by kekekeks** [comment]
See https://github.com/AvaloniaUI/Avalonia/issues/1948#issuecomment-427457994
https://t.me/Avalonia

**Comment by MakcStudio** [comment]
Огромное спасибо, сейчас буду разбираться)

**Comment by maxkatz6** [comment]
I believe it was answered
