### ISSUE TITLE
Path Parsing issues

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#3053]
Some path data are not working correct 2 examples:
- example 1:
```
          <Path Stroke="Red" StrokeThickness="1"  Width="100" Height="100" Stretch="Uniform"
                Data="M0,0L100,0 L100,100 L0,100Z m5,5 L95,5 L95,95 L5,95Z" />
```
In wpf it works fine, in avalonia not:

![path1](https://user-images.githubusercontent.com/13854631/65986009-afa62880-e48b-11e9-9894-44f3b05d850e.png)

- example 2
```
                        <Path Stroke="Red" StrokeThickness="1" Width="100" Height="100" Stretch="Uniform" Data="
M59.25 23.58 62.1 3.4h8.44a10.73 10.73 0 0 1 5.8 1.24 3.3 3.3 0 0 1 1.59 3.49A4.5 4.5 0 0 1 76.26 11a8.18 8.18 0 0 1-3.48 1.71v0a6 6 0 0 1 3.73 1.59 3.67 3.67 0 0 1 1 3.23A6.11 6.11 0 0 1 74.63 22a11.63 11.63 0 0 1-6.46 1.63Z
m6.45-8.67L65 20.23h2.83a5.44 5.44 0 0 0 3-.73 2.74 2.74 0 0 0 1.3-2 1.87 1.87 0 0 0-.74-1.9 4.46 4.46 0 0 0-2.73-.69Z
m1.15-8.16-.67 4.78h2.29a4.67 4.67 0 0 0 2.65-.68A2.6 2.6 0 0 0 72.31 9q.31-2.22-3.5-2.22Z
" />
```
![pathB](https://user-images.githubusercontent.com/13854631/65986080-d4020500-e48b-11e9-90d0-6503404d8e4c.png)

**Comment by jp2masa** [comment]
Maybe this works for the first one?

```
          <Path Stroke="Red" StrokeThickness="1"  Width="100" Height="100" Stretch="Uniform"
                Data="M0,0L100,0 L100,100 L0,100Z M5,5 L95,5 L95,95 L5,95Z" />
```

**Comment by donandren** [comment]
@jp2masa i can write path.data for the figures in such a way to work with avalonia, but the point is to make it work same as path.data in svg and wpf already fixed the issue in #3054 now the examples are working fine

**Comment by Gillibald** [comment]
It should comply to the SVG specifications. That's what I had in mind when I rewrote the parser.

**Comment by donandren** [comment]
@Gillibald parser tbh is working great, that's one of the few edge cases i've noticed parser have problems and now should be even better after it's fixed
