### ISSUE TITLE
Adding/Removing classes in codebehind crashes on PriorityLevel.cs

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#3058]
try out RenderDemo on https://github.com/AvaloniaUI/Avalonia/tree/repro-bindingprio-bug and repeatedly click the Pause/Resume Animations button.

cc: @MarchingCube 

I tried fixing it by adding the following check on PriorityLevel.cs and it seem to work but im not sure if that's the correct fix.

Line 204:
```
                    if (_bindings.Count > 0)
                        _bindings.Remove(_binding);
```

**Comment by MarchingCube** [comment]
Looks like we are unsubscribing twice, will investigate.

**Comment by MarchingCube** [comment]
Fixed in https://github.com/AvaloniaUI/Avalonia/pull/3062.
