### ISSUE TITLE
OpenFolderDialog pops up twice, on Linux.

### ISSUE THREAD

**Issue by GitHubington** [AvaloniaUI/Avalonia#3063]
OpenFolderDialog pops up twice, on Linux.

**Comment by danwalmsley** [comment]
Are you using native dialog or managed dialog? Which OS?

**Comment by gitgiggity** [comment]
I'm using template generated by Avalonia for Visual Studio. Which means Managed, I think
I'm testing on Linux Mint 18.3 x64, virtual machine.
