### ISSUE TITLE
WindowStartupLocation.CenterOwner doesn't work in Opened event

### ISSUE THREAD

**Issue by Mikaka27** [AvaloniaUI/Avalonia#3071]
Hi,
I noticed some strange behvior, not sure if this is a bug.

When I try to show the dialog with option:
`WindowStartupLocation.CenterOwner`
And I do that directly in the "Opened" event of another Window, the Dialog shows in top left corner of screen on Linux (Mint 19.2), but shows in the center on Windows.

See attached screenshots:
![CenterOwnerWindows](https://user-images.githubusercontent.com/9214100/66254766-5b48c480-e77b-11e9-9ad0-68a656354848.png)
![CenterOwnerLinux](https://user-images.githubusercontent.com/9214100/66254769-60a60f00-e77b-11e9-94af-9ef263b4d4f5.png)

It can be fixed by using
`await Task.Delay` before calling `ShowDialog` (see comment in MainWindow.xaml.cs).
Reproduction:
[AvaloniaApplication3.zip](https://github.com/AvaloniaUI/Avalonia/files/3693217/AvaloniaApplication3.zip)

**Comment by chylex** [comment]
Ran into the same bug, X11Window doesn't get the `Position` property filled in for some reason. I'm not too happy about the delay workaround but I don't see a better way to make it work - also not sure how it behaves on Mac, so I ended up doing this:
```
if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) {
	await Task.Delay(500);
}
```
