### ISSUE TITLE
Slider.PointerReleased Event

### ISSUE THREAD

**Issue by edOasiot** [AvaloniaUI/Avalonia#3076]
I can't get the Slider.PointerReleased event to fire - code below

mySlider.PointerReleased += SliderChanged;

void SliderChanged(object sender, PointerReleasedEventArgs e)
{
           string name = ((Slider)sender).Name;  // Never hit this break point
}

**Comment by grokys** [comment]
Apologies for the delay on this. Do you mean when clicking and dragging the slider? This is expected, and its the same in WPF too: the `Slider` handles the pointer being release to prevent it bubbling to parent controls.

If you want to receive this event, you need to subscribe to the tunneling version of the event (which will be raised before the slider handles the event) by calling `AddHandler` with `RoutingStrategies.Tunnel`:

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Interactivity/Interactive.cs#L52
