### ISSUE TITLE
How to get control by name?

### ISSUE THREAD

**Issue by M0rdecay** [AvaloniaUI/Avalonia#3078]
Hello.

Please, help. How do I get control as an object by its name?
In ksaml, its code looks like this:
`    <TabControl Width="480" Height="{Binding $parent.Bounds.Height}" x:Name="tabControl">
    </TabControl>`
and i need access to this control from code like this:
`    this.tabControl`

Is it possible to do?
I apologize in advance if this is a stupid question :).

And one more question - as can be seen from the announcement of the TabControl, its height is given as a number. Is there a way to do something like this:
`   Width="{Binding $parent.Bounds.Width * 0.6}" ` ?

Thank you in advance.

**Comment by kekekeks** [comment]
1) `this.FindControl<TabControl>("tabControl")`
2) You need to use value converters http://avaloniaui.net/docs/binding/converting-binding-values#binding-converters

**Comment by M0rdecay** [comment]
@kekekeks Thank you very much!
