### ISSUE TITLE
PointerPressed captures pointers 1 pixel outside of the control

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#3079]
I have a control that's size is 128 wide and 16 tall. When I subscribe to the PointerPressed event, I am getting events from both x=128 and y=16 (which are outside of the control). Any X and Y coords larger do not fire the event. The event also will not fire if there is a different control directly next to this control. For example, if I have another control to the right of this control, then events with x=128 will not be sent to this control.

**Comment by grokys** [comment]
Just tried this on WPF and it's the same there: a button can be clicked one pixel to the right of its actual bounds.

**Comment by robloo** [comment]
That's got to be a bug in WPF. There shouldn't be a goal to copy that functionality over to Avalonia when it just doesn't make sense.

**Comment by Kermalis** [comment]
> That's got to be a bug in WPF. There shouldn't be a goal to copy that functionality over to Avalonia when it just doesn't make sense.

Yes. Not to be rude but I have stopped all of my app development with Avalonia simply because there is basic functionality that remains broken for years because new features or "compatibility" is favored over deprecating or changing things for the better. I like Microsoft, and their acquisition of things usually makes things better, but this workflow I'm describing benefits nobody and it just stalls development for everyone for years.

Most of my bugs were filed in 2017-2019 and they still remain for the most part. I didn't even make reports for everything because  they are so infuriating, or making a reproduction is just so time-consuming, or the issue is SO BASIC (ComboBoxes drive me insane in this) that I'm like "surely they will find and fix this without my report" so I just gave up. Whenever I NEED to update my stuff I end up spending the entire day diagnosing things that broke when updating (so the compatibility argument makes literally no sense since shit breaks anyway EVERY update without fail).

I have janky extension methods and fixes everywhere in every app because again, basic functionality just does not work and I'm waiting for things to get fixed, or events fire in different orders between updates. It's just impossible to justify my day doing this literally every time. I'm glad there is a ContainsExclusive now as I suggested in my PR but it should be used where possible ASAP. Not in 8 months. Then I can remove my extension method that does that in PointerPressed.

And people using my apps understand I have no motivation because of this. They see it's open source and want to help, then attempt to and go "oh Avalonia with their 1000+ issues" and try to port my stuff to GTK or something else since they also have issues with Avalonia. Again I don't want to be mean here but this is actual feedback you should consider seriously. You guys do hard work but the workflow is just not there where it matters. It's the hard truth and I wish it weren't since Avalonia can be so great, and should've been great a long time ago. But when ComboBoxes for example STILL don't perform as expected after 5+ years it really does hurt your users.

I pull every commit locally since I first found Avalonia, even to this day, and I read them all. But I see only new features and macOS low-level window fixes. Nothing that matters to me personally, and I get disappointed every now and then since I see the priorities. Anyway, that's just my rant and my opinion. I hope this new generation of users can develop with less headache than I did.

**Comment by grokys** [comment]
I'm very sorry for you inconvenience but I spend virtually every waking hour working on Avalonia for a fraction of the pay that I could be getting if I got myself a proper job. I can't even keep up with the number of emails that come from this repository, never mind address them all. You're not talking to a corporation here, you're talking to a small group of people who are working for a fraction of their market value to give you something for free.

**Comment by danwalmsley** [comment]
"Most of my bugs were filed in 2017-2019 and they still remain for the most part." You are very welcome to fix those issues yourself, be my guest! Many others do this!

**Comment by danwalmsley** [comment]
If some issue is so important, and needs fixing immediately, that service is available for paying customers. See our website for details.

Please remember you don't pay to use Avalonia. No one is entitled to any fixes or other services without paying. You get to use the software for free as is. Please see the license as it is clearly explained there.

**Comment by Kermalis** [comment]
> I'm very sorry for you inconvenience but I spend virtually every waking hour working on Avalonia for a fraction of the pay that I could be getting if I got myself a proper job. I can't even keep up with the number of emails that come from this repository, never mind address them all. You're not talking to a corporation here, you're talking to a small group of people who are working for a fraction of their market value to give you something for free.

I know that, and I appreciate the effort of all of you because I was in a similar position (not with a project this big). I was just stating why Avalonia is not a fit for me and other people I talked to in the C# space. It is very promising but a project this scale moving this slow is a downer for us.

And speaking for myself right now, I no longer have the time to mess around with it just for cross-platform sake, which is why I went with WPF in my most recent situation even though it has its own share of issues and is Windows-only. My life is just different now than it was in 2017. I don't even have much time to myself now

**Comment by danwalmsley** [comment]
> > I'm very sorry for you inconvenience but I spend virtually every waking hour working on Avalonia for a fraction of the pay that I could be getting if I got myself a proper job. I can't even keep up with the number of emails that come from this repository, never mind address them all. You're not talking to a corporation here, you're talking to a small group of people who are working for a fraction of their market value to give you something for free.
> 
> I know that, and I appreciate the effort of all of you because I was in a similar position (not with a project this big). I was just stating why Avalonia is not a fit for me and other people I talked to in the C# space. It is very promising but a project this scale moving this slow is a downer for us.
> 
> And speaking for myself right now, I no longer have the time to mess around with it just for cross-platform sake, which is why I went with WPF in my most recent situation even though it has its own share of issues and is Windows-only. My life is just different now than it was in 2017. I don't even have much time to myself now

Good luck getting similar issues fixed in WPF!
