### ISSUE TITLE
Get a collection of controls of a given class?

### ISSUE THREAD

**Issue by M0rdecay** [AvaloniaUI/Avalonia#3085]
Is it possible to get a collection of child/content controls of a given class? Like this - https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.oftype?view=netframework-4.8

The task is - get all TextBoxes and save their text in a List.

In WinForms i can do it:
`foreach (TextBox tBox in page.Controls.OfType<TextBox>()) { //some code here }`

Thanks in advance for your reply!

**Comment by grokys** [comment]
One way to do it in Avalonia would be:

```
using Avalonia.VisualTree;

foreach (var tBox in page.GetVisualDescendants().OfType<TextBox>())
{
   // Code here
}
```

See http://avaloniaui.net/api/Avalonia.VisualTree/VisualExtensions/ for useful extension methods for querying the visual tree.

**Comment by ollih1980** [comment]
Perfect. Thx. Works like charm!
