### ISSUE TITLE
ListBox initial SelectedItems are cleared

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#3089]
Using Avalonia 0.8.999
The initial values in the collection bound to ListBox.SelectedItems are cleared and the ListBox displays an empty list.
Expected: the ListBox to show the initial selection using the bound SelectedItems collection.

The view:
```
  <ListBox
  SelectionMode="Multiple,Toggle"
  Items="{Binding Items}"
  SelectedItems="{Binding SelectedItems}">
    <ListBox.ItemTemplate>
      <DataTemplate>
        <CheckBox IsChecked="{Binding $parent[ListBoxItem].IsSelected}" IsHitTestVisible="False" Content="{Binding .}"/>
      </DataTemplate>
    </ListBox.ItemTemplate>
  </ListBox>
```

The ViewModel:
```
        public AvaloniaList<string> Items { get; set; } = new AvaloniaList<string>() { "A", "B", "C", "D", "E" };
        public AvaloniaList<string> SelectedItems { get; set; } = new AvaloniaList<string>() { "B", "D", };
```

Displayed:
![image](https://user-images.githubusercontent.com/17591364/66479426-614ce700-ea94-11e9-9b54-ccace2ad66b0.png)

Expected:
![image](https://user-images.githubusercontent.com/17591364/66479452-7164c680-ea94-11e9-89e6-30442aa0ce0b.png)

**Comment by donandren** [comment]
same issue applies to `SelectedItem `and `SelectedIndex` properties and to ComboBox
