### ISSUE TITLE
(macOS) Rendering broken

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#3095]
Between cibuild0004216 and cibuild0004306 something was merged and causes [one of my windows](https://github.com/mat1jaczyyy/apollo-studio/blob/master/Apollo/Windows/PatternWindow.cs) to entirely break Avalonia's rendering system. Unstable in this state, sometimes crashes in AvaloniaNative when closing windows, sometimes goes beachball, and sometimes logically seems everything's in the right place and if I click where the UI elements are supposed to be the UI responds appropriately.

Tested on 10.13 and 10.14 and the issue manifests in much the same way. Also tested latest (which seems to be just 0.8.999? correct me if wrong - though I tried 0.8.999-cibuild0004475-beta and it repros there as well) and still get the same behavior.

Windows works as intended, I don't target Linux so can't test there.

Repro: [apollo-studio/master](https://github.com/mat1jaczyyy/apollo-studio)

1. Create New Project
2. Double click one Track to open it up
3. Add Pattern Device "Shape" -> "Pattern", see image
![image](https://user-images.githubusercontent.com/13300194/66559069-06c78f80-eb55-11e9-8eeb-fe5f7f713b76.png)
4. Open its window
5. Rendering borked

Context menus on existing windows after rendering borked

![image](https://user-images.githubusercontent.com/13300194/66559380-9a00c500-eb55-11e9-8dcb-2f0fed4099f7.png)

Newly opened windows after rendering borked

![image](https://user-images.githubusercontent.com/13300194/66559405-a38a2d00-eb55-11e9-8d41-1cd544d4b699.png)

**Comment by mat1jaczyyy** [comment]
Persists on 0.9.0-preview1

**Comment by grokys** [comment]
Might be fixed by https://github.com/AvaloniaUI/Avalonia/pull/3118, though it's hard to say without a stacktrace or something.

**Comment by danwalmsley** [comment]
@mat1jaczyyy @mat1jaczyyy I think i can check this today

**Comment by jmacato** [comment]
![image](https://user-images.githubusercontent.com/16554748/66905700-ec9c1e80-f038-11e9-922b-cba985314be6.png)

Works well on Linux (btw your app looks really great:) )... seems to be OSX specific. Also i made use of 0.9.0-preview1 since our cibuilds hasnt reflected my fix for non-decorated windows yet.

**Comment by jmacato** [comment]
@mat1jaczyyy also noticed you use alot of non-decored windows so better update your BeginResize/MoveDrag functions when the release is out :)

**Comment by grokys** [comment]
Can repro on windows too if i click the maximize button after the described steps.

**Comment by mat1jaczyyy** [comment]
@jmacato thanks a lot! there's an avalonia-0.9 branch where I've already fixed the drag functions. the issue repros there as well.
