### ISSUE TITLE
Carousel gestures

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#3098]
v0.8.999
I'm working on adding a swipe gesture to the Carousel control but I have discovered that the control overrides OnKeyDown and OnPointerPressed.
```
        /// <inheritdoc/>
        protected override void OnKeyDown(KeyEventArgs e)
        {
            // Ignore key presses.
        }

        /// <inheritdoc/>
        protected override void OnPointerPressed(PointerPressedEventArgs e)
        {
            // Ignore pointer presses.
        }

```

The OnPointerPressed override prevents gestures from working on the Carousel control.

Is there a good reason why these methods are overriden like this?

**Comment by grokys** [comment]
I can't remember 100% but I think it's to prevent the default keyboard behavior from `SelectingItemsControl` from happening. Could be that we should either:

1. Move the keyboard behavior to a derived class. This would mean that keyboard handling would be implemented in `ListBox`, `ComboBox` etc separately
2. Simply set `e.Handled` in these events in `Carousel`
