### ISSUE TITLE
Binding TextBox to String Property with null value does not clear the TextBox

### ISSUE THREAD

**Issue by stevozilik** [AvaloniaUI/Avalonia#3103]
When binding a TextBox to String property, 

`<TextBox Text="{Binding Text}"/>`

`public class ViewModel { public string Text{ get; set; } }` (inlcuding INotifyPropertyChanged)

when setting the Text to 'null', the TextBox is not cleared

`viewModel.Text = null;`

Only when setting to String.Empty, then the TextBox clears

**Comment by Symbai** [comment]
@grokys: I think this can be closed. I've tried to reproduce this in Avalonia 0.9.3 and the Textbox text gets cleared as expected:

![ezgif-3-2ae89c523001](https://user-images.githubusercontent.com/14368203/74553104-87a4f680-4f4e-11ea-83cb-dae682dd809d.gif)

**Comment by grokys** [comment]
Thanks @Symbai !
