### ISSUE TITLE
Raspberry Pi arm64 error

### ISSUE THREAD

**Issue by DrZhong** [AvaloniaUI/Avalonia#3104]
https://www.nuget.org/packages/Avalonia.Skia.Linux.Natives/1.68.0.2
does't work with Raspberry Pi arm64 

`Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
   at SkiaSharp.SkiaApi.gr_glinterface_assemble_gl_interface(IntPtr ctx, IntPtr get)
   at SkiaSharp.GRGlInterface.AssembleGlInterface(Object context, GRGlGetProcDelegate get)
   at SkiaSharp.GRGlInterface.AssembleGlInterface(GRGlGetProcDelegate get)
   at Avalonia.Skia.PlatformRenderInterface..ctor()
   at Avalonia.Skia.SkiaPlatform.Initialize()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args)
   at UdsUI.Program.Main(String[] args) in /home/curtisy/Projects/Avalonia/UdsUI/Program.cs:line 12`

**Comment by jclapis** [comment]
I ran into this today as well. I worked around it by building v1.68.1.1 for ARM64 on the Pi itself, and dropping the resulting `libSkiaSharp.so` file directly into the output directory of my Avalonia app (so it's in the same dir as `SkiaSharp.dll`). My app ran fine on the Pi after that. I've attached the SO here in case anyone wants to try using it until official support is added.

[libSkiaSharp.zip](https://github.com/AvaloniaUI/Avalonia/files/4169064/libSkiaSharp.zip)

**Comment by Gillibald** [comment]
Did you use the bootstrapper provided by SkiaSharp to build or did you manually run the build? Ideally, we would cross-compile it but haven't figured out to do that.

**Comment by jmacato** [comment]
easier solution right now would be to use JellyFin's SkiaSharp lib for ARM
https://www.nuget.org/packages/Jellyfin.SkiaSharp.NativeAssets.LinuxArm/

**Comment by jmacato** [comment]
@Gillibald we need to figure out how to x-compile these libs for our own SkiaSharp package...

**Comment by jclapis** [comment]
> 
> 
> Did you use the bootstrapper provided by SkiaSharp to build or did you manually run the build? Ideally, we would cross-compile it but haven't figured out to do that.

It was a fairly manual process - I'll write a gist about it and link it here when it's ready. In a nutshell, I mostly followed [these steps](https://github.com/mono/SkiaSharp/wiki/Building-on-Linux) but had to build `gn` from source (since the included binary is for x64), had to use the distro's version of `ninja` since depot_tools doesn't know what to do with aarch64, and had to make a few other tweaks (like [this one](https://github.com/mono/SkiaSharp/issues/797)).

**Comment by jclapis** [comment]
Okay, [here's my writeup](https://gist.github.com/jclapis/d907127dc031ad351b943df7917cd753) of the process I used. Hope it helps!

**Comment by kekekeks** [comment]
SkiaSharp now has built-in support for arm and arm64
