### ISSUE TITLE
DecoratedWindow gets stuck when moved/resized.

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#3105]
![scrn](https://user-images.githubusercontent.com/16554748/66734660-8b3c4a00-ee96-11e9-9e1a-35d75b200bf3.gif)

Only tested on Linux. Not sure if it's reproducable elsewhere.

**Comment by HendrikMennen** [comment]
This was the case for non decorated windows on Linux for a long time. Moving the window would get stuck until you release the mouse twice and resizing would even need restarting the application. Isn't the one in your gif a non decorated window?

**Comment by jmacato** [comment]
related/duplicate: https://github.com/AvaloniaUI/Avalonia/issues/2973

**Comment by jmacato** [comment]
Okay, i have a preliminary fix for this. Will upload a PR shortly
