### ISSUE TITLE
can not render text on raspberry pi 4B 

### ISSUE THREAD

**Issue by DrZhong** [AvaloniaUI/Avalonia#3106]
work with  [2019-07-10-raspbian-buster.img](https://downloads.raspberrypi.org/raspbian_latest) 

## step1
`dotnet publish -r linux-arm -f netcoreapp3.0`
## setp 2
Copy publish directory to the Raspberry Pi and run it with 
`chmod +x publish/xxxx`
`./xxx`
the window can be  show,but can not render the control's text.

### this is the code
![image](https://user-images.githubusercontent.com/8085571/66740248-42d85880-eea5-11e9-8e10-aeb6c4e52c5f.png)

### but  running on the raspberry pi 4B 
![image](https://user-images.githubusercontent.com/8085571/66740341-816e1300-eea5-11e9-84e8-9555a3ff66c5.png)

**Comment by kekekeks** [comment]
You are probably missing some fonts on your RPi

**Comment by jp2masa** [comment]
There are 2 possible solutions:
- Changing the font of the app
- Installing the missing font, this was working last time I tried: `sudo apt-get install ttf-mscorefonts-installer`

**Comment by DrZhong** [comment]
> There are 2 possible solutions:
> 
> * Changing the font of the app
> * Installing the missing font, this was working last time I tried: `sudo apt-get install ttf-mscorefonts-installer`

i have tried `sudo apt-get install ttf-mscorefonts-installer` on my RPI, but it still missing the text,so 
can u tell me how can i changing the font of the app? Thants very much!

**Comment by DrZhong** [comment]
@factormystic 


> There are 2 possible solutions:
> 
> * Changing the font of the app
> * Installing the missing font, this was working last time I tried: `sudo apt-get install ttf-mscorefonts-installer`

i have tried sudo apt-get install ttf-mscorefonts-installer on my RPI, but it still missing the text,so
can u tell me how can i changing the font of the app? Thants very much!

**Comment by Gillibald** [comment]
Try to set a FontFamily that is available on your PI on your Window. `FontFamily="MyAvailableFont"`

**Comment by Gillibald** [comment]
In the future, it will be possible to use a custom font manager that does not rely on the fonts installed on the system. That will make it easier to work on embedded systems and also enables font fallback for WASM builds.

**Comment by DrZhong** [comment]
@Gillibald  Thanks,it work for me.


> In the future, it will be possible to use a custom font manager that does not rely on the fonts installed on the system. That will make it easier to work on embedded systems and also enables font fallback for WASM builds.
