### ISSUE TITLE
It's very hard to compile and run on mac Control Catalog

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#3113]
Even if one has the prerequisities setup (castxml etc.) it's really hard to tryout samples (ControlCatalog.NetCore) from Avalonia on mac with the current build configuration,
One must compile libAvaloniaNative manually and copy/rename to sample bin dir.

**Comment by JaggerJo** [comment]
Yeah, that's really annoying. Could this be easily automated ? / is there an obvious solution ?

**Comment by danwalmsley** [comment]
@grokys @kekekeks perhaps we should have some sample apps that reference the latest nuget package and in a seperate repo, that way they are also more representative of an actual avalonia project someone would have?

**Comment by Gillibald** [comment]
Isn't there a ControlCatalog repository that is already doing that. Probably needs some updates but that would be a good start.

**Comment by donandren** [comment]
This issue is fixed in PR #3114 ,  so if it's approved and merged, local build on mac os will require only:
`nuke Compile`

**Comment by migajek** [comment]
nevertheless, it'd be a nice thing to have the compiled samples distributed as binaries :)
