### ISSUE TITLE
Problem with adding children to the grid after it is initially displayed. 

### ISSUE THREAD

**Issue by igorstefus** [AvaloniaUI/Avalonia#3120]
I have problem with adding children to the grid after it is initially displayed (for example after button click). I have small [example](https://bitbucket.org/igorstefus/grid_problem/src/master/) demonstrating the problem. Can you please take a look.

**Comment by igorstefus** [comment]
This example demonstrates problem with adding children to the grid after it is initially displayed. Before attaching to visual tree “TestGrid” (custom control inheriting Grid) method “Additem” is called and it adds evenly sized rows to row definitions and children (in this case borders) to Children collection set to each row. It works as expected. However same method is called on button click and in that case added children are no longer visible.

**Comment by jmacato** [comment]
Okay, will take a look at this later
