### ISSUE TITLE
Tmds.DBus.dll not found raspberryPI

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#3122]
I just upgraded my project to 0.9.0-preview1 and it now fails to run on the raspberry PI the message:
```
Error:
  An assembly specified in the application dependencies manifest (Nav6pi.deps.json) was not found:
    package: 'Tmds.DBus', version: '0.7.0'
    path: 'lib/netstandard2.0/Tmds.DBus.dll'
```

**Comment by kekekeks** [comment]
You are missing [Tmds.DBus](https://www.nuget.org/packages/Tmds.DBus/) package for some reason. It should be included transitively from `Avalonia.Desktop`->`Avalonia.X11`->`Avalonia.FreeDesktop`->`Tmds.DBus`. Check your nuget dependencies

**Comment by aguahombre** [comment]
I can see the Tmds.DBus.dll file in the ```bin\Release\netcoreapp2.1\linux-arm\publish``` folder and it is copied to the target machine.

Has anything changed in the program start code that I need to update in my project?

**Comment by aguahombre** [comment]
OK, I solved it.
I needed to do a Filezilla refresh as it hadn't copied the Tmds.DBus.dll file to the target machine.
