### ISSUE TITLE
Issue with popup on multiple screens.

### ISSUE THREAD

**Issue by igorstefus** [AvaloniaUI/Avalonia#3125]
I was trying to set popup position to be wherever user pointer is. This is the code I am using (custom control inheriting Popup):

```
private void OnPointerMoved(object sender, Avalonia.Input.PointerEventArgs e)
{ 
      if (_isLeftMouseButton)
      {
                Point location = e.GetPosition(null);

                Host.ConfigurePosition(PlacementTarget, PlacementMode.Top, location);
      }
}
``` 

This works fine as long as pointer is on screen where placement target is. However popup will not follow pointer if it moves to another screen.  Is this behavior intended? We are trying to build custom docking solution and I was thinking of using popups to move content around but I need popup to follow cursor even on another screen. Alternative is to simply use window but using popup is convenient.

**Comment by Gillibald** [comment]
Popup isn't guaranteed to have its own surface. There are platforms that draw popups on the window's surface. So I think you have to use a window instead of a popup to achieve this. Just my thought. Maybe others know more.

**Comment by kekekeks** [comment]
>we are trying to build custom docking solution and I was thinking of using popups to move content around but I need popup to follow cursor even on another screen

Note that it won't work with Wayland because of the lack to access to window coordinates in any way, shape or form
