### ISSUE TITLE
Using indexed accessors for DataGridColumn.SortMemberPath doesn't work

### ISSUE THREAD

**Issue by AcidJunkie303** [AvaloniaUI/Avalonia#3126]
Assuming i have the following object for a DataGrid row which contain most of the values to display in a dictionary called `Properties:`

```
interface IObject
{
    string Name {get;set;}
    IDictionary<string,object> Properties {get;set;}
}
```

When using `"Name"` for `DataGridColumn.SortMemberPath`, it works as expected. However, if i use `"Properties[ColumnId]"` for `DataGridColumn.SortMemberPath`, the DataGrid renders this column as not sortable. Looks like that indexed property accessors are not working.

**Comment by maxkatz6** [comment]
Also it is not possible to sort by array item with property path like "Person[0].FirstName".
Although sorting by dictionary with path like "Dict[Key]" works for me now.
