### ISSUE TITLE
FormattedText.Typeface: NullReferenceException in FormattedTextImpl

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#3132]
Not really a bug, but if you forget to assign a `Typeface` to a `FormattedText `it will cause some crash in the `FormattedTextImpl` (for both Skia and D2D1). Maybe we should use some font (like Arial) by default or give a proper error message to the user.

**Comment by pr8x** [comment]
@Gillibald Do you know if this bug is still relevant?

**Comment by Gillibald** [comment]
There is no FormattedTextImpl anymore
