### ISSUE TITLE
using hw graphics has big memory use on windows

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#3135]
If AllowEglInitialization = true is used on windows the memory use goes from 119 to 244 MB on startup for control catalog, maybe the libraries used are simply this big but it is quite a jump.

**Comment by MarchingCube** [comment]
I noticed this as well, and it is unmanaged memory only that jumps by around 100 MB.

**Comment by Gillibald** [comment]
Do you see this behavior when you use an x86 build? There is a bug in the current SkiaSharp(Skia@m64) release that uses more memory on x64 systems. Just some guess.

**Comment by ShahroozAnsari** [comment]
i have this problem too and i asked before but with this type of support avalonia going to die

**Comment by grokys** [comment]
@ShahroozAnsari this project is run by volunteers. Take a look at your own GitHub contribution graph and compare it with one of the maintainers of this project before you say things like that. If you're going to demand support from us you can pay us.

**Comment by ahopper** [comment]
@ShahroozAnsari if you are referring to https://github.com/AvaloniaUI/Avalonia/issues/3043 I think this is a quite different issue.

**Comment by ahopper** [comment]
> Do you see this behavior when you use an x86 build? There is a bug in the current SkiaSharp(Skia@m64) release that uses more memory on x64 systems. Just some guess.

@Gillibald sorry I only just saw your question
on my radio app with the current nightly build 
x86 goes from 66M to 119M
x64 goes from 80M to 204M
so 64 bit is worse.

**Comment by Gillibald** [comment]
Can you test this against current master?

**Comment by ahopper** [comment]
That was on 0.9.999-cibuild0005372-beta which should be the current master

**Comment by MarchingCube** [comment]
Checked that locally and for me enabling EGL increases memory usage by 50MB in ControlCatalog. 
Around 20 MB is used to just initialize EGL (since it has to load Direct3D 9 dlls and GLES ones, plus whatever init necessary). After that graphics driver kicks in allocating more and when we flush first render something triggers in Direct3D 9 as well as it allocates 20-30 MB again.

**Comment by ahopper** [comment]
)nly seeing minimal extra memory in 0.10.11
