### ISSUE TITLE
At which moment does the Initialized event fire?

### ISSUE THREAD

**Issue by M0rdecay** [AvaloniaUI/Avalonia#3137]
A method attached to an `Initialized` event is never executed.
In constructor of `class MainWindow : Window` :
```
this.Initialized += this.OnLoad;
this.InitializeComponent();
```
Method:
`private void OnLoad(object sender, EventArgs e) { //some code here }`

 Am I doing something wrong?

Case - I need to download some data and change the appearance of the window after the user sees the main form. Using the opening event is not suitable, since it fires before the XAML form is initialized.

**Comment by grokys** [comment]
Which version of Avalonia are you using? Just tried this on current master and the `Initialized` event is raised.

**Comment by M0rdecay** [comment]
@grokys i use v0.8.0

**Comment by M0rdecay** [comment]
Let's close this question. If necessary, I will return to him later.
P.S. Your framework is very good, please continue its development!
