### ISSUE TITLE
What about responsive?

### ISSUE THREAD

**Issue by khoshroomahdi** [AvaloniaUI/Avalonia#3138]
I am web developr so i prefer bootstrap than visual state to make app responsive.
Is there any chance to make col-md and ... Classes to make app responsive in avalonia?

**Comment by kekekeks** [comment]
Bootstrap grid system will most likely require a separate layout class.

ResponsiveGrid from https://github.com/sourcechord/GridExtra seems to be a good candidate for porting

**Comment by khoshroomahdi** [comment]
@kekekeks yeah, that's awesome.

**Comment by jmacato** [comment]
I have a ready to use port of that exact control :)
https://github.com/jmacato/GridExtra.Avalonia/blob/master/GridExtra.Avalonia/ResponsiveGrid.cs

**Comment by jmacato** [comment]
I have a ready to use port of that exact control :)
https://github.com/jmacato/GridExtra.Avalonia/

**Comment by kekekeks** [comment]
https://www.nuget.org/packages/GridExtra.Avalonia/  nuget version seems to work fine with 0.8.3
![Peek-2019-10-20-00-58](https://user-images.githubusercontent.com/1067584/67148741-794e1300-f2ab-11e9-8b38-bca8b72aad50.gif)

**Comment by jpgarza93** [comment]
Does this still work with the latest rc1?

**Comment by timunie** [comment]
@jpgarza93 if it's build against 11.0 RC1, yes. Otherwise clone the source and build on your own or wait for an update.

**Comment by jpgarza93** [comment]
Thank you, I have updated it and added a PR.
