### ISSUE TITLE
Binding fallback not working on latest 0.9 preview 3

### ISSUE THREAD

**Issue by braca** [AvaloniaUI/Avalonia#3139]
Hi,

I have a TranslateExtension that I use in Avalonia, and WPF to translate some stuff, the code is pretty simple.

```
    public class TranslateExtension : MarkupExtension
    {
        public TranslateExtension(string key)
        {
            this.Key = key;
        }

        public string Key { get; set; }

        public string FallBack { get; set; }

        public string Context { get; set; }

        public override object ProvideValue(IServiceProvider serviceProvider)
        {
            ....

            var binding = new BindingExtension($"[{keyToUse}]")
            {
                Mode = BindingMode.OneWay,
                Source = Translator.Instance,
                FallbackValue = fallback,
            };

            return binding.ProvideValue(serviceProvider);
        }
    }
```

Bascialy, when the is no translation for a specific key (returns null), a fallback value is used instead.
This extension works fine with WPF, and Avalonia 0.8.3.

The problem occurs with the latest version 0.9 preview 3, where it seems that it's ignoring the `FallbackValue`

**Repro project:** https://github.com/braca/avalonia-binding-fallback-bug

You can load my repro project, with 0.8.3 it will work perfectly, if you update to the latest 0.9 preview 3, the fallback value won't be used.

Note: When you update to the latest preview, comment this `using Portable.Xaml.Markup;` in `TranslateExtensions.cs`

**Comment by grokys** [comment]
@braca I've not had chance to look into this properly, but does it work if you return a `Binding` rather than a `BindingExtension` from `ProvideValue`?

My guess is that Portable.Xaml supported markup extensions returning markup extensions recursively, whereas our XAML compiler doesnt. In fact I'm not even sure that recursive binding extensions should work, it might have just been a "hidden" feature of Portable.Xaml.

**Comment by braca** [comment]
Hi @grokys,

I've tried to replace
```
            var binding = new BindingExtension($"[{keyToUse}]")
            {
                Mode = BindingMode.OneWay,
                Source = Translator.Instance,
                FallbackValue = fallback,
            };

            return binding.ProvideValue(serviceProvider);
```
with
```
            var binding = new Binding($"[{keyToUse}]", BindingMode.OneWay)
            {
                Source = Translator.Instance,
                FallbackValue = fallback
            };

            return binding;
```
but the end result was the same

**Comment by braca** [comment]
@grokys I think this is not a bug after all, my bad. In WPF the behaviour is the same, I thought it wasn't but my WPF code had a small difference, and that makes all the difference. 
In WPF I'm using `TargetNullValue` alongside with `FallbackValue`.

Removing the `TargetNullValue`, WPF behaves the same way Avalonia 0.9.
Our translator returns `null` when there is no translation available for the key. `null` is a valid 'value' for string, so the correct behaviour seems to be, to use null, instead of the fallbackvalue.

So, I believe that the bug was on 0.8.x where it was behaving differently from WPF :) 

Feel free to close it

**Comment by grokys** [comment]
Thanks for letting us know @braca. We're intending to add `TargetNullValue` soon anyway - here's the issue: https://github.com/AvaloniaUI/Avalonia/issues/2814
