### ISSUE TITLE
Changing Grid RowDefinitions/ColumnDefinitions does not invalidate visual

### ISSUE THREAD

**Issue by JaggerJo** [AvaloniaUI/Avalonia#3141]
When RowDefinitions or ColumnDefinitions change (instantiate new Definitions and set DirectProperty on Grid) changes are not shown until something else triggers the control to render/invalidate.

![2019-10-20 14 04 54](https://user-images.githubusercontent.com/13090415/67159286-c29d7180-f342-11e9-8e7a-03d663dcf71c.gif)

(Tested on 0.9 Preview 2 & 3)

**Comment by jmacato** [comment]
@JaggerJo can you give us a simple repro for this?

**Comment by JaggerJo** [comment]
@jmacato Super busy today, hope I’ll get to it tomorrow.

**Comment by JaggerJo** [comment]
https://gist.github.com/JaggerJo/019eb3cb2c613549ee1526f13d063a62

So it looks like its not the visual that's not invalidated, but the measure.

**Comment by garyhertel** [comment]
I was trying out the new 0.9.0 preview 4 and might be seeing a similar problem as this when adding a new RowDefinition to a grid. You can drop this sample into the control catalog and it should add a new blue box each time you click on one of existing blue boxes, but it only works in 0.8.0, not 0.9.0 preview 4.
[GridPage.zip](https://github.com/AvaloniaUI/Avalonia/files/3769816/GridPage.zip)

![image](https://user-images.githubusercontent.com/32446542/67532665-f1d21c80-f67b-11e9-81c5-0c8cc4073f00.png)
