### ISSUE TITLE
First NativeMenu item on Mac conflict between app name and header

### ISSUE THREAD

**Issue by dtchepak** [AvaloniaUI/Avalonia#3147]
Observed with `0.9.0-preview4`, dotnetcore2.2 on Mac OS Mojave (10.14.6). 

When application loads the first menu item is "dotnet". When I run a command from the menu like `OpenFolderDialog.ShowAsync(...)` and the dialog displays, the menu changes to match the header.

(If `Application.Name` is set, that is shown instead of "dotnet", but will still switch to whatever value is in the header as described below.)

## Steps to reproduce

I started with `dotnet new avalonia.mvvm` and updated the generated code to reference `0.9.0-preview4` and fixed compiler errors due to that package update (such as adding `using Avalonia.ReactiveUI` to get `UseReactiveUI` extension).

Then added `NativeMenu` to `MainWindow.xaml`:

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="clr-namespace:AvaloniaWorkshop.ViewModels;assembly=AvaloniaWorkshop"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaWorkshop.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="AvaloniaWorkshop">

    <Design.DataContext>
        <vm:MainWindowViewModel/>
    </Design.DataContext>

     <NativeMenu.Menu>
        <NativeMenu>
            <NativeMenuItem Header="SampleApplication">
                <NativeMenuItem.Menu>
                    <NativeMenu>
                        <NativeMenuItem Header="Quit" />
                    </NativeMenu>
                </NativeMenuItem.Menu>
            </NativeMenuItem>
            <NativeMenuItem Header="File">
                <NativeMenuItem.Menu>
                    <NativeMenu>
                        <NativeMenuItem Header="Open" Gesture="cmd+o" Command="{Binding OpenCommand}" />
                        <NativeMenuItemSeperator />
                        <NativeMenuItem Header="Quit" />
                    </NativeMenu>
                </NativeMenuItem.Menu>
            </NativeMenuItem>
        </NativeMenu>
    </NativeMenu.Menu>
    

    <TextBlock Text="{Binding Greeting}" HorizontalAlignment="Center" VerticalAlignment="Center"/>

</Window>
```

And updated `MainViewModel.cs` to add an `OpenCommand`:

```csharp
using System;
using System.Reactive;
using System.Threading.Tasks;
using ReactiveUI;

namespace AvaloniaWorkshop.ViewModels
{
    public class MainWindowViewModel : ViewModelBase
    {
        public ReactiveCommand<Unit, string> OpenCommand { get; }

        public MainWindowViewModel(Func<Task<String>> openCommand) {
            OpenCommand = ReactiveCommand
                .CreateFromTask(openCommand, outputScheduler: RxApp.MainThreadScheduler);
        }

        public string Greeting => "Hello World!";
    }
}
```

Lastly, need to update `Program.cs` to inject command:

```csharp
// In Program.cs:
private static void AppMain(Application app, string[] args)
{
    var window = new MainWindow();
    window.DataContext = new MainWindowViewModel(() => new OpenFolderDialog().ShowAsync(window));
    app.Run(window);
}
```

Now if I run the app, the menu displays with the first item "dotnet", and the second item "File". If I select File -> Open, the menu updates the first item to "SampleApplication" (to match the header). Once I close the folder picker, the first item reverts to "dotnet". 

![nativemenu0](https://user-images.githubusercontent.com/70105/67367959-36997d00-f5c2-11e9-9f78-5684d80631b2.png)
![nativemenu1](https://user-images.githubusercontent.com/70105/67367957-3600e680-f5c2-11e9-8120-69ee72aaed6b.png)
![nativemenu2](https://user-images.githubusercontent.com/70105/67367954-3600e680-f5c2-11e9-875e-d32e68d93db8.png)

**Comment by dtchepak** [comment]
Adding the following to `App.xaml` fixes the renaming of the first item:

```
     <NativeMenu.Menu>
        <NativeMenu />
     </NativeMenu.Menu>
```

But when opening the folder picker, the native menu defined in `MainWindow.xaml` disappears.

This might be by-design as the primary window changes, in which case is there another way of binding commands in the menu to a view model?

**Comment by kekekeks** [comment]
>This might be by-design as the primary window changes

Yes, this is basically the same as with Qt: menus are bound to windows and get removed on window deactivation. Which actually makes sense for modal dialogs, the app usually expect the thing to actually be modal.

**Comment by dtchepak** [comment]
Thanks for the info. 👍 
Feel free to close this.
