### ISSUE TITLE
Adopt a Code of Conduct

### ISSUE THREAD

**Issue by alicagamova** [AvaloniaUI/Avalonia#3149]
Some contributors (specifically some Russians) behave inappropriately outside of this project's repository (on other sites and chats). Please adopt a Code of Conduct, so we could ban people from contributing to this project.

**Comment by MonkAlex** [comment]
>behave inappropriately 
any links?

And, not understand, how CoC help?

**Comment by grokys** [comment]
I'm not aware of any inappropriate behavior, but I agree that we should adopt a code of conduct. In fact I believe that if we want to join the .NET foundation we'll need to have one, so probably best to do it preemptively.

**Comment by kekekeks** [comment]
I guess that someone got banned from certain telegram chats and now tries to do some sort of revenge.

**Comment by Keroosha** [comment]
> Some contributors behave inappropriately outside of this project's 

I think, that's personal how contribs behaive yourself outside of project. Only if some one insult or offense other participant inside a project, he should be "ban from contributing to this project"

**Comment by MonkAlex** [comment]
> I think, that's personal how contribs behave yourself outside of project. Only if someone insult or offense other participant inside a project, he should be "ban from contributing to this project"

CoC say another:

> Project maintainers have the right and responsibility to ... ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful.

**Comment by alicagamova** [comment]
@kekekeks I am not banned. I never posted in the chats. But look at your history in the "Green Chat". Calling people leftists and SJWs among many other things. You cannot do this anymore. I've got everything screenshoted.

ps. this issue is raided from the chat right now

**Comment by Keroosha** [comment]
@MonkAlex You don't think that a bit overkill? For example, if I somewhere dispute with other participant and he "offense by me". That should be a reason to restrict me working on project?

Open Source work and personal "feelings" should be aside

**Comment by kekekeks** [comment]
@alicagamova I've re-read my messages containing words "SJW" and "leftists" and haven't found anything offensive. Those was always mentioned as a generic social phenomena never mentioning anyone personally.

You can post screenshots right here, if you want further discussion.

**Comment by MonkAlex** [comment]
> You don't think that a bit overkill?

I dont know. 
Dislike idea to ban person, who write useful code.

But, maintainers _can_ limit access to project by personal reasons.

**Comment by grokys** [comment]
Hey all. I'm sorry, I have no idea what's going on here. Would people mind if I locked the thread temporarily while we take a look at what's been happening? I don't intend to do this to prevent people discussing this, but I would like to avoid a flame-war or similar on a github issue.

Please feel free to get in touch with me or any of the core devs via email or gitter to discuss.

**Comment by grokys** [comment]
Yep, going to lock this thread. @alicagamova in particular, you opened this thread so please let me know if you're unhappy with this by email or gitter.

**Comment by kekekeks** [comment]
Adopted Contributor Covenant v1.4

If anyone wants to report abuse, you can contact @grokys eigher on gitter or via steven@avaloniaui.net


https://github.com/AvaloniaUI/Avalonia/commit/7dc95d5644bd3b14d2760cb664599e24fc239344

**Comment by grokys** [comment]
As Nikita says, we've adopted a CoC. Please, if anyone has any misgivings about the behavior of our contributors - get in touch with me. We're really proud of our community and we want everyone to feel welcome.
