### ISSUE TITLE
KeyGesture not having empty ctor on 0.9 

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#3162]
Hey,

Trying out 0.9 preview 4 and noticed KeyGesture doesn't have empty ctor, is there any reason for it?
Since I can no longer serialize it

Thanks

**Comment by Gillibald** [comment]
Calling `ToString()` and `Parse(string s)` should work for you.

**Comment by adirh3** [comment]
I know, the thing is that when I serialize it to json I prefer that the JsonSerializer will deserialize it automatically.
Anyway just wondered why the constructor was removed. (I will use the Parse and ToString to serialize it)

**Comment by MarchingCube** [comment]
`KeyGesture` is now immutable, all setters have been removed so only constructors that allow to construct a valid object were kept. This is in line with WPF API as well.
