### ISSUE TITLE
Scenebuilder `visual.Render(context)` should perhaps not fail silently

### ISSUE THREAD

**Issue by lokegustafsson** [AvaloniaUI/Avalonia#3167]
This is my first issue here, so feel free to correct me if I am mistaken about something:

In SceneBuilder.cs, lines 234-238:
```
234  try
235  {
236      visual.Render(context);
237  }
238  catch { }
```
So if a user overrides Visual.Render and then throws an exception, the current implementation simply fails silently. This should perhaps not cause the entire application to crash, but I really feel like it at least should be logged. I don't think the user can be expected to know that exceptions in Visual.Render are simply ignored and shouldn't be used.

**Comment by kekekeks** [comment]
Will be addressed in vnext renderer
