### ISSUE TITLE
AvaloniaPropertyChangedEventArgs can be a struct

### ISSUE THREAD

**Issue by mstr2** [AvaloniaUI/Avalonia#3169]
Like its corresponding WPF type, AvaloniaPropertyChangedEventArgs can be a struct to reduce memory allocations.
Avalonia runs fine with this change.

**Comment by kekekeks** [comment]
Might as well be a `readonly` struct, so it could be passed by reference. That would reduce copying.

**Comment by mstr2** [comment]
AvaloniaPropertyChangedEventArgs has a memory footprint of 40 bytes. My guess is that at this size, copying could still be faster than passing by reference.

**Comment by MarchingCube** [comment]
We might want to benchmark this, but `readonly` struct is a valid argument anyway since it also prevents defensive copies. And semantically events should be immutable.
