### ISSUE TITLE
Popup doesn't release capture when closed

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#3182]
ComboBox popup (or may be any toplevel window) doesn't release capture when closed, thus making next mouse click invalid and not recognized by the system.
For example in Control catalog try switch between dark and light themes with the dropdown.
Once theme selected, next click on dropdown will not open the dropdown popup, but need a second click.
![2019-10-29_17-18-19](https://user-images.githubusercontent.com/13854631/67781971-d77bb280-fa70-11e9-9e85-a7faf8edad4e.gif)

**Comment by kekekeks** [comment]
Check if https://github.com/AvaloniaUI/Avalonia/pull/3158 solves your issue

**Comment by donandren** [comment]
@kekekeks #3158 solves partially the issue -1 mouse click is not lost e.g. next click on combo opens it, but `PointerCaptureLostEvent` is never raised

**Comment by donandren** [comment]
it working properly in the latest master
