### ISSUE TITLE
MacOS: NativeMenu unclickable on first load after updating to Catalina

### ISSUE THREAD

**Issue by dtchepak** [AvaloniaUI/Avalonia#3185]
After updating to MacOS Catalina I've found the `NativeMenu` behaviour has changed. When the main window first loads the menu is not clickable (not the apple logo, main app menu or any additional menu items). After switching focus to another app, then back to the Avalonia app, the menu works as expected.

I reproduced this behaviour using the steps from #3147. I have been able to reproduce this on two separate machines. `NativeMenu` was working as expected on the same machine, same app running on Mojave.

**Comment by danwalmsley** [comment]
Are you running under Xcode?

**Comment by dtchepak** [comment]
@danwalmsley This is with `dotnet run` from my machine, or by running the artifact produced from `dotnet publish -c Release -r osx-x64 --self-contained true` on another machine. Using .NET Core SDK 3.0.100.

**Comment by dtchepak** [comment]
Quick update: this mainly seems to happen using `dotnet run` or by copying the artifacts from `dotnet build` to another Mac. If I package the app as a .app bundle it runs fine. 🤦‍♂ 

With that in mind it's probably fine to close this issue (maybe just mention it in docs for `NativeMenu`?).

**Comment by kekekeks** [comment]
It's less critical ins this case, but we'd still like to have it clickable. So let's keep the issue open.

**Comment by danwalmsley** [comment]
@kekekeks repro'd, on catalina.

On Mojave it doesn't do this!

**Comment by kekekeks** [comment]
We might need yet another call to `activateIgnoringOtherApps`

**Comment by danwalmsley** [comment]
Fixed.
