### ISSUE TITLE
CompileAvaloniaXamlTask Issue

### ISSUE THREAD

**Issue by edOasiot** [AvaloniaUI/Avalonia#3192]
![AvaloniaCompileIssue](https://user-images.githubusercontent.com/54422142/67999092-dbeacb80-fc28-11e9-897b-f4d5db8be636.png)

**Comment by kekekeks** [comment]
1) Stop Visual Studio
2) Kill all MSBuild.exe processes
3) Run `dotnet restore` from command line
4) Start Visual Studio again
