### ISSUE TITLE
Progress Bar MinimumWidth/Height

### ISSUE THREAD

**Issue by RedlineTriad** [AvaloniaUI/Avalonia#3194]
Currently the progress bar has a minimum width/height by default meaning that if you want a progress bar with a height of less than 14 you also have to set MinHeight along with Height for it to actually work.

The problem is located here: https://github.com/AvaloniaUI/Avalonia/blob/68b655b5177175fc1b168b2130064992575c1fb6/src/Avalonia.Themes.Default/ProgressBar.xaml#L23-L26

**Comment by grokys** [comment]
@danwalmsley @jmacato I see this is still present in the Fluent port of `ProgressBar` - how is this handled in UWP?

**Comment by maxkatz6** [comment]
@grokys I am late here, but for historical notes:
UWP uses same ProgressBarThemeMinHeight resource (=4) as MinHeight. So it's not suitable if user wants smaller height, in that case he needs to change min value as well.
