### ISSUE TITLE
ComboBox.SelectedItem only returns the typename and not the selected Value When using a Datatemplate

### ISSUE THREAD

**Issue by ajmcateer** [AvaloniaUI/Avalonia#3199]
I have a combobox configured like so

```
      <ComboBox SelectedItem="{Binding SelectedModule, Mode=OneWayToSource}" Grid.Column="0" BorderBrush="Black" Grid.Row="2" Height="25" Margin="5" Items="{Binding SubCommands}">
        <ComboBox.ItemTemplate>
          <DataTemplate>
            <TextBlock Text="{Binding DisplayName}" ToolTip.Tip="{Binding Description}"/>
          </DataTemplate>
        </ComboBox.ItemTemplate>
      </ComboBox>
```
And the viewmodel is 
```
        public string SelectedModule
        {
            get => selectedModule;
            private set
            {
                var res = value;
                this.RaiseAndSetIfChanged(ref selectedModule, value);
            }
        }
```
I am getting back the typename of the Items property instead of the value of the textblock text. How can I get that WPF mentions DisplayMemberName but that doesn't seem to exist in Avalonia.

I also tried 
`SelectionBoxItem="{Binding SelectedModule, Mode=OneWayToSource}" `
but that didn't work either

**Comment by Gillibald** [comment]
This is the expected behavior and matches what the Wpf version does. As you noted we are missing the DisplayMemberPath feature and the SelectedValue property. This needs to be added. For now you could use a converter.

**Comment by grokys** [comment]
How is `SubCommands` defined in the view model?

**Comment by ajmcateer** [comment]
Hi @grokys @Gillibald,

It is defined like
```
public class SubCommandModel : CommandModelBase
    {
        public List<DiagnosticTestModel> DiagnosticTests { get; set; }
        public SubCommandModel()
        {
            DiagnosticTests = new List<DiagnosticTestModel>();
        }
    }
```
and commandbase is
```
    public class CommandModelBase
    {
        public string Description { get; set; }
        public string DisplayName { get; set; }
        public string CommandName { get; set; }
    }
```
It displays fine just returns "Cedar.Model.SubCommand" as a string

**Comment by grokys** [comment]
Thanks... Now I'm confused:

> It displays fine just returns "Cedar.Model.SubCommand" as a string

What do you mean by this? It displays fine? So the problem isn't how it's displayed?

**Comment by ajmcateer** [comment]
@grokys Thank you, I did not realize it was just calling ToString() on subcommand module, it makes a lot of sense in hindsight. I did just as you suggested and it works great.
