### ISSUE TITLE
Separate Colors and Templates

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#3207]
U can't recolor colors which u use in templates like checkMark color
but if u separate colors and templetes 
it's become easier to recolor all controls

**Comment by jp2masa** [comment]
They are separated: https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.Themes.Default/Accents. For the check mark, the `HighlightBrush` is used: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Default/CheckBox.xaml#L22.
