### ISSUE TITLE
Clicking on MenuItem that is covering a button also clicks the button

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#3208]
Seems to be the even it propogated to the controls that are covered by the menus popup.

**Comment by grokys** [comment]
I think @kekekeks and myself have discussed this previously: we need to stop events from popups propagating to the parent visual tree. However, this looks serious enough that we need a fix/hack for 0.9. I'll look into that now.

**Comment by grokys** [comment]
Hmm, i'm unable to repro this on current master in ControlCatalog.

**Comment by danwalmsley** [comment]
Seems to be fixed, will close for now.
