### ISSUE TITLE
Icons on TopLevel MenuItem are not displayed

### ISSUE THREAD

**Issue by wurzelchen68** [AvaloniaUI/Avalonia#3214]
MenuStructure looks like that, System is running on Windows10Pro
Icon on "Edit" is not displayed...

   <Menu DockPanel.Dock="Top">
            <MenuItem Header="_File">
                <MenuItem Header="_Search">
                    <MenuItem.Icon>
                        <Image Source="avares://Avalon/Assets/Icons/search.png" />
                    </MenuItem.Icon>
                </MenuItem>
                <Separator />
                <MenuItem Header="_Exit" />
            </MenuItem>
            <MenuItem Header="_Edit">
                <MenuItem.Icon>
                    <Image Source="avares://Avalon/Assets/Icons/search.png" />
                </MenuItem.Icon>
            </MenuItem>
        </Menu>

**Comment by grokys** [comment]
@wurzelchen68 did you mean to attach an image? Could you also give us some example code?

**Comment by wurzelchen68** [comment]
hm... code is swallowed by this textbox.....

[MainWindow.zip](https://github.com/AvaloniaUI/Avalonia/files/3809265/MainWindow.zip)

**Comment by MikeCodesDotNET** [comment]
This is expected behaviour as Edit is the root menu item.
