### ISSUE TITLE
Line 'StrokeLineCap' and 'StrokeJoin' are ignored

### ISSUE THREAD

**Issue by JaggerJo** [AvaloniaUI/Avalonia#3217]
<img width="123" alt="image" src="https://user-images.githubusercontent.com/13090415/68157376-d1447500-ff4d-11e9-8142-37e616ef4be0.png">

The `StrokeLineCap` and `StrokeJoin` are ignored.

To reproduce just add  `StrokeLineCap` or `StrokeJoin` to the red line on the Canvas Demo Page.

```xml
<Line StartPoint="120,185" EndPoint="30,115" Stroke="Red" StrokeThickness="2" StrokeLineCap="Square" StrokeJoin="Round"/>
```

This also seems to affect other shapes.

Tested on latest master

**Comment by FoggyFinder** [comment]
It does work correctly to me on current master. Can you check it again?

**Comment by JaggerJo** [comment]
Hah, it does.

**Comment by JaggerJo** [comment]
<img width="186" alt="image" src="https://user-images.githubusercontent.com/13090415/69915859-10ce8600-1454-11ea-96e9-dea106b660cb.png">
