### ISSUE TITLE
FontManager.Default is always empty for desktop application

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#3224]
FontManager.Default is always empty fontmanager for desktop application.

repro:

Start ControlCatalog Dektop from master and in some Window constructor type to check:
`var fm = FontManager.Default;`

FontManager.Default is EmptyFontManager for both Skia and Direct2D

Initialization somewhere is not in the right order.
I believe it's the static ctor of ClassicDesktopStyleApplicationLifetime.

**Comment by Gillibald** [comment]
Hmm. FontManager shouldn't be used before the platform is initialized.

**Comment by donandren** [comment]
@Gillibald  here https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs#L20-L24

FontManager.Default is initialized.
 we might need move out this initialization out of static ctor of lifetime to start? or something else

**Comment by Gillibald** [comment]
Y that is the cause. I thought recent changes to initialization order had already fixed this. Will fix it not by moveing theses handlers out of a static context.

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/3225/files
