### ISSUE TITLE
netstandard2.0 The type or namespace AppBuilder could not be found in Avalonia

### ISSUE THREAD

**Issue by NathanielACollier** [AvaloniaUI/Avalonia#3235]
I'm wanting to use Avalonia.AppBuilder in a netstandard2.0 library.  I've got a nuget reference to Avalonia.Desktop 0.8.3.  If my library is dotnetcore2.1 Avalonia.AppBuilder is there and the library works.  I want to compile the library as netstandard2.0.  If I only change that part of the project the code won't compile anymore with the following error.

The type or namespace AppBuilder could not be found in Avalonia

**Comment by kekekeks** [comment]
A concrete `AppBuilder` type is platform and runtime-specific. nestandard libraries should use AppBuilderBase<T> instead (like [this](https://github.com/AvaloniaUI/Avalonia/blob/627999cd6f92cd196b990b9bbc5a8502feee3c8c/src/Avalonia.ReactiveUI/AppBuilderExtensions.cs#L18)

**Comment by NathanielACollier** [comment]
Thanks!  That solved the problem.

**Comment by ApacheTech** [comment]
> A concrete `AppBuilder` type is platform and runtime-specific. nestandard libraries should use `AppBuilderBase<T>` instead (like [this](https://github.com/AvaloniaUI/Avalonia/blob/627999cd6f92cd196b990b9bbc5a8502feee3c8c/src/Avalonia.ReactiveUI/AppBuilderExtensions.cs#L18))

What is T? Could you give a working example of how to do it? It seems like `AppBuilderBase<T>` is self-referential, and has mandatory base initialisers... and needs a paramaterless constructor?

How do I go from:

```
public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToTrace()
                .UseReactiveUI();
```

to:

```
public static AppBuilderBase<T> BuildAvaloniaApp<T>()
            => AppBuilderBase<T>.Configure<App>()
                .UsePlatformDetect()
                .LogToTrace()
                .UseReactiveUI();
```

**Comment by kekekeks** [comment]
This is [planned](https://github.com/AvaloniaUI/Avalonia/issues/7052) to be reworked as a part of the next major release. Can't really do it as a part of 0.10.x, since it's a breaking change

**Comment by kekekeks** [comment]
With the current version extending AppBuilder looks like this:
https://github.com/AvaloniaUI/Avalonia/blob/907a18d832f474d8dbedfa1d5751f4d4940eb1aa/src/Avalonia.ReactiveUI/AppBuilderExtensions.cs#L15

**Comment by ApacheTech** [comment]
Ok, so it's borked in .NET Standard 2.0? Is there a roadmap for major version releases?

Knowing how to extend the AppBuilder is all well and good, but not if there isn't an AppBuilder to extend. :)

**Comment by kekekeks** [comment]
>Ok, so it's borked in .NET Standard 2.0? 

It's not borked, you need to do it in a certain non-intuitive way. See https://github.com/AvaloniaUI/Avalonia/blob/907a18d832f474d8dbedfa1d5751f4d4940eb1aa/src/Avalonia.ReactiveUI/AppBuilderExtensions.cs#L15-L16

**Comment by kekekeks** [comment]
If you want to configure one from scratch, it's not possible with netstandard2.0 right now

**Comment by ApacheTech** [comment]
> > Ok, so it's borked in .NET Standard 2.0?
> 
> It's not borked, you need to do it in a certain non-intuitive way. See
> 
> https://github.com/AvaloniaUI/Avalonia/blob/907a18d832f474d8dbedfa1d5751f4d4940eb1aa/src/Avalonia.ReactiveUI/AppBuilderExtensions.cs#L15-L16

That's an extension method for an AppBuilder. I don't have an AppBuilder to extend. There isn't one in the library. There isn't even a way to make an instance of `AppBuilderBase<TAppBuilder>`, because the required base parameters aren't in the library either.

Is there a roadmap for major version releases?

**Comment by lclslsls** [comment]
Can I understand it this way
Under the official library
Dotnetstandard2.0 cannot create any windows

**Comment by lclslsls** [comment]
> If you want to configure one from scratch, it's not possible with netstandard2.0 right now



> > Ok, so it's borked in .NET Standard 2.0?
> 
> It's not borked, you need to do it in a certain non-intuitive way. See
> 
> https://github.com/AvaloniaUI/Avalonia/blob/907a18d832f474d8dbedfa1d5751f4d4940eb1aa/src/Avalonia.ReactiveUI/AppBuilderExtensions.cs#L15-L16

I noticed that c2e00428dff6e0ea326ac993bfbbb71fcfad2909
It's time to go back
How to use the latest version
