### ISSUE TITLE
Add window resize event

### ISSUE THREAD

**Issue by garyhertel** [AvaloniaUI/Avalonia#3237]
In version 0.9, there doesn't appear to be a way to detect window resizes anymore. In version 0.8, there was a HandleResized() function that could be override, but that was changed to a sealed function in 0.9.

I was using this to save a user's window size and restore it when restarting. I can use the Closed event handler in it's place, but that won't handle crashes or stopping the app in the debugger. It's not a huge issue switching this over. However, there's probably multiple other uses for this event handler.

**Comment by kekekeks** [comment]
You can subscribe to `ClientSize` property changes instead.

**Comment by garyhertel** [comment]
Thanks! That worked great

**Comment by garyhertel** [comment]
@omnjpa27516 

You can try something like this:

```
this.GetObservable(ClientSizeProperty).Subscribe(Resize);

private void Resize(Size size)
{
}
```

**Comment by garyhertel** [comment]
Sorry, that I can't help you with. I only used it to attach to the `Window`, so if you have another use I'm not sure how.
