### ISSUE TITLE
TextBox in ContextMenu does not allow editing on linux

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#3246]
The following works on windows but on linux focus disappears from the text box as soon as you click on it.

```
<Button  >
  <Button.ContextMenu>
    <ContextMenu>
      <TextBox />
    </ContextMenu>
  </Button.ContextMenu>
  <TextBlock Text="?????" />
</Button>
```

**Comment by ahopper** [comment]
I guess this is really an abuse of the ContextMenu so perhaps should not be treated as a bug, still odd it does not behave the same on all platforms.

**Comment by maxkatz6** [comment]
Seems to be fixed after https://github.com/AvaloniaUI/Avalonia/pull/4632
