### ISSUE TITLE
TextBox.Focus() in ModalDilaog not work on OSX

### ISSUE THREAD

**Issue by ficnar** [AvaloniaUI/Avalonia#3249]
Avalonia 0.8.1 and 0.8.0 on OSX.
I need set focus to any TextBox after open Window. I call TextBox.Focus() on Window.OnActivated event. 
If Window is opened by Window.Show(), its work properly. 
But if  I open Window by Window.ShowDialog(this), I see input cursor in TextBox, but input from keyboard not work. I must click to any place in Window, for example to Window background and then keyboard input works fine.
This issue only on OSX. On Windows and Linux works properly.

Example attached:
[AvaloniaTextBoxCursorBugOSX.zip](https://github.com/AvaloniaUI/Avalonia/files/3835044/AvaloniaTextBoxCursorBugOSX.zip)

**Comment by rignatev** [comment]
Avalonia 0.9.0-preview7 on Windows 10
Application has a main window and a not modal window that opens from menu.
If i open from not modal window the new dialog window (message box) and then close the dialog window, the focus sets to main window and then to owner window of message box. It looks like the main window is blinking...
How can i fix it?

Code from ViewModel of not modal window, that opens messagebox
`string messageBoxWindowDialogResult = await messageBoxWindow.ShowDialog(this.View);`

**Comment by danwalmsley** [comment]
@ficnar can you try with 0.9.0-preview7 and tell us if the new release has this bug?

**Comment by ficnar** [comment]
OK. I tried my example code with 0.9.0-preview7 on OSX and the result is the same.

**Comment by ficnar** [comment]
On final version 0.9.0 the problem still occurs.

**Comment by ficnar** [comment]
On last version 0.9.11 the problem still occurs. Do you have plan fix it or exists some workaround?

**Comment by ArtjomP** [comment]
I met the same issue on version 0.10.6.
I tried:
```cs
dialog.Activeate();
dialog.Focus();
```
Noting helps.
Any ideas?

**Comment by workgroupengineering** [comment]
Have you tried with:

```csharp
       // On yours dialog
        protected override void OnAttachedToLogicalTree(LogicalTreeAttachmentEventArgs e)
        {
            base.OnAttachedToLogicalTree(e);
            Dispatcher.UIThread.Post(() => this.Activate());
            Dispatcher.UIThread.Post(() => this.Focus());
        }
```

**Comment by ArtjomP** [comment]
Thank you, @workgroupengineering !
It didn't work for me, unfortunately. I added the same code to the OnAttachedToVisualTree. 
 ```cs
protected override void OnAttachedToVisualTree(VisualTreeAttachmentEventArgs e)
 {
     base.OnAttachedToVisualTree(e);
     Dispatcher.UIThread.Post(() => this.Activate());
     Dispatcher.UIThread.Post(() => this.Focus());
}

protected override void OnAttachedToLogicalTree(LogicalTreeAttachmentEventArgs e)
{
    base.OnAttachedToLogicalTree(e);
    Dispatcher.UIThread.Post(() => this.Activate());
    Dispatcher.UIThread.Post(() => this.Focus());
}
```
No result.
BTW it works well on Windows.

**Comment by ficnar** [comment]
On the actual version 0.10.7, my bug example works properly on OSX.
Thank you.
