### ISSUE TITLE
Problem with focusing on the owner of the dialog window after the dialog window closes

### ISSUE THREAD

**Issue by rignatev** [AvaloniaUI/Avalonia#3252]
Avalonia 0.9.0-preview7 on Windows 10
Application has a main window and a non-modal window that opens from menu.
If i open the message box (dialog window) from the non-modal window and then close the message box, the focus sets to the main window and then to the owner window of message box. I see the main window blinking over the non-modal window.
How can i fix it?

Code from ViewModel of not modal window, that opens messagebox
`string messageBoxWindowDialogResult = await messageBoxWindow.ShowDialog(this.View);`

**Comment by grokys** [comment]
@rignatev I know it's a long time since you filed this issue, but do you have a minimal repro by any chance?

**Comment by joaompneves** [comment]
This happened to me too, when I had more than two windows opened on my app. In my case I had a hidden window. When I switched to another app and switched back to my app, the problem would start.

This solved the problem:

```
class MyWindow : Window
{
    protected override void OnClosing(CancelEventArgs e)
    {
        base.OnClosing(e);
        if (!e.Cancel && IsActive)
        {
            Owner?.Activate();
        }
    }
}
```
