### ISSUE TITLE
Window.Owner works differently than in WPF (Z order is not respected)

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#3254]
In WPF setting window `Owner` makes the child window stay on top of the parent. Quoting https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.owner?view=netframework-4.8:

```
To allow you to create a relationship between a child window and a parent window, Window supports the notion of ownership. Ownership is established when the Owner property of a window (the owned window) is set with a reference to another window (the owner window).

- Once this relationship is established, the following behaviors are exhibited:

- If an owner window is minimized, all its owned windows are minimized as well.

- If an owned window is minimized, its owner is not minimized.

- If an owner window is maximized, both the owner window and its owned windows are restored.

- An owner window can never cover an owned window.

- Owned windows that were not opened using ShowDialog are not modal. The user can still interact with the owner window.

- If you close an owner window, its owned windows are also closed.

- If an owned window was opened by its owner window using Show, and the owner window is closed, the owned window's Closing event is not raised.

```

In Avalonia `An owner window can never cover an owned window.` is not true and parented windows can be obscured by the parent window.

**Comment by kekekeks** [comment]
We currently don't even have a concept of window owner in platform backends. `WindowBase.Owner` isn't wired to anything and basically does not work.

ShowDialog, on the other hand, properly sets things like `GWL_HWNDPARENT` and `WM_TRANSIENT_FOR` and has special handling for window activation.

**Comment by MarchingCube** [comment]
Done via https://github.com/AvaloniaUI/Avalonia/pull/3833.
