### ISSUE TITLE
Disposing any WriteableBitmap causes NRE in WriteableBitmap.Lock() for new WriteableBitmaps

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#3257]
I'm not sure if I could create a consistent repro, but I will explain what happens.

Step 1: I have a Window created (not the parent Window) which has WriteableBitmaps that I write to often. I close this Window (which disposes the WriteableBitmaps)
Step 2: I open a new instance of of this Window which will then create new WriteableBitmaps
Step 3: First WriteableBitmap.Lock() will throw NRE

Stacktrace is simply:
```
   at Avalonia.Media.Imaging.WriteableBitmap.Lock()
```

Unfortunately for me, my entire program revolves around WriteableBitmaps, and this will occur extremely often for all users

**Comment by Kermalis** [comment]
Happens with both .UseSkia() and .UseDirect2D1()

**Comment by Kermalis** [comment]
I really cannot create a repro for this for some reason. I tried for hours to make something really simple and it didn't crash, then I tried to mimic what my project does and it still didn't crash. The best I can do is link you to my faulty project and you can clone/download it and follow the below steps, sorry for the inconvenience. It's currently lightweight since I'm in the very early stages.

Step 1: Download/clone from https://github.com/Kermalis/PokemonGameEngine/tree/c7d12078cafaf6586a61a952746e6da403d35a8a
Step 2: Run the "MapEditor" project (debug and release both have the issue)
Step 3: In the main window that appears, click "Open Block Editor"
Step 4: Click "Clear Block" in the new window
Step 5: Close the new window
Step 6: Click "Open Block Editor" again
Step 7: Click "Clear Block" again (will crash at this point)

The only thing going on in the background of the program is that WriteableBitmaps are getting redrawn when you click "Clear Block" (you can visually see it update the images). When you close the window it will Dispose() the WriteableBitmaps. When you open it again, there are now new WriteableBitmaps, and clicking "Clear Block" again will queue a redraw and the crash will occur on the first WriteableBitmap.Lock() call.

It's really simple, and I really don't know why I wasn't able to reproduce it, but these steps are simple enough to follow in my opinion. As I said before, this is a very necessary workflow for this program; opening the block editor and closing it again over and over. As it stands currently, the user must restart the program each time the block editor is closed in order to avoid this crash.

If you're skeptical that it's my code, I don't see how that is possible. The crash is in Avalonia, and it's upon accessing PlatformImpl which I have no access to in my code. My code doesn't do anything funky, it just uses unsafe code (pointers) to directly write to the pixels of the WriteableBitmap, and yes, there are checks to make sure it's not writing outside of the bitmap, so this should be acceptable behavior. Also, it's not that specific button, it's any Lock() call that comes after opening the new window. I chose that button for the step-by-step to make it as easy as possible to reproduce.

Also, I'm on Windows 7 x64 if that makes any difference.

**Comment by Kermalis** [comment]
@kekekeks I updated to 0.9.0-preview7 as per your request: https://github.com/Kermalis/PokemonGameEngine/tree/ca204fa735aaab655b8f603c398ae38a42fa96bf

**Comment by ahopper** [comment]
It appears this line https://github.com/Kermalis/PokemonGameEngine/blob/ca204fa735aaab655b8f603c398ae38a42fa96bf/MapEditor/Core/Blockset.cs#L297
is calling the event on the previous editor instance and hence working with deleted bitmaps.

**Comment by Kermalis** [comment]
@ahopper ah, thank you so much for pointing that out, it turns out it was me after all. Perhaps WriteableBitmap should throw an ObjectDisposedException so it is easier to figure out what was happening. Anyway, I will close this, as it was not a bug in Avalonia, my apologies to everyone.
