### ISSUE TITLE
Is there compatible report generator for Avalonia?

### ISSUE THREAD

**Issue by raminmjj** [AvaloniaUI/Avalonia#3259]
Hello.
I found [FastReport.Net](http://fropensource.blogspot.com/2019/03/how-to-make-report-viewer-on-avalonia.html) for Avalonia, but it doesn't support direct print.
thank you.

**Comment by kekekeks** [comment]
Does it support PDF generation? That's probably your best bet when printing on Linux/OSX

**Comment by raminmjj** [comment]
For .net core. no, it doesn't. 
only JPG image support at this time.

**Comment by kekekeks** [comment]
According to https://www.fast-report.com/en/blog/177/show/ they claim to support generating PDF files with .NET Core.

To print a PDF file on Linux you can use [`lp` utility](https://makandracards.com/makandra/24202-linux-how-to-print-pdf-files-from-the-command-line) via [Process.Start]. 

To get the list of printers you can P/Invoke [cupsGetPrinters](https://opensource.apple.com/source/cups/cups-33/doc/spm.html#cupsGetPrinters).

**Comment by raminmjj** [comment]
Thanks.
export to PDF is only available in the commercial version.
thank you for your help and introducing the [cups](https://www.cups.org/documentation.html).

**Comment by kekekeks** [comment]
@raminmjj Apparently [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/4.7.0-preview3.19551.4) package already [uses CUPS on *nix](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Drawing.Common/src/System/Drawing/Printing/LibcupsNative.cs). So you can reuse printing code between platforms.
