### ISSUE TITLE
Transferring pointer capture between windows.

### ISSUE THREAD

**Issue by igorstefus** [AvaloniaUI/Avalonia#3260]
What is the best way to transfer pointer capture from one window to another without actually releasing mouse button. To achieve this I am releasing capture from one window by calling `Pointer.Capture(null)` and then calling `MouseDevice.ProcessRawEvent` in another to raise PointerPressed event. It sends events but it doesn't transfer capture to the new window even if I do it manually (MouseDevice.Capture(target) or Pointer.Capture(target)).

**Comment by MarchingCube** [comment]
I think one issue is when you close the window on Win32 all capture is lost (pointed out in https://github.com/AvaloniaUI/Avalonia/pull/3158 comment). Do you know how can we fix this @kekekeks or if there is temporary workaround?

**Comment by kekekeks** [comment]
I don't think that this scenario would be supported by the core framework, since it's outright impossible on some platforms.

On Win32 one could P/Invoke `SetCapture` manually
