### ISSUE TITLE
Webcam 

### ISSUE THREAD

**Issue by DhananjayHuidrom** [AvaloniaUI/Avalonia#3262]
How to integrate a webcam in Avalonia UI?

**Comment by kekekeks** [comment]
Depends on the platform. 

First, you need to get the video stream

Windows - SharpDX.MediaFoundation
Linux - P/Invoke libv4l2
OSX - AVFoundation (will probably need a separate native library)

Then you need to feed the image back to Avalonia either via WritableBitmap or using `CustomDrawingOperation` for better performance.

**Comment by ahopper** [comment]
You could try https://github.com/donandren/vlcsharpavalonia , I use a similar vlc solution in wpf for webcams.

**Comment by Gillibald** [comment]
Let us know if you need further help implementing this.
