### ISSUE TITLE
Memory leak when creating windows

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#3269]
![image](https://user-images.githubusercontent.com/13300194/69002604-da8cf480-08f2-11ea-8aac-862b2472ec73.png)

After closing and creating windows a lot (probably hundreds of times), it can be seen memory usage slowly rises. This screenshot is from a small test repro attached here, but this realistically affects my application since the windows are much more complex and the workflow is such that closing/opening of windows happens a lot.

avalonia 0.9-preview7
tested on windows probably happens elsewhere, not sure

[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/3855200/AvaloniaApplication1.zip)

**Comment by Kermalis** [comment]
@MarchingCube you seem like the guy to call on this issue, any chance you can look into this and maybe see if a fix can make it into 0.9?

**Comment by MarchingCube** [comment]
@Kermalis I had some time to look at this repro case, it looks like when we close the window all controls stay attached to the logical and visual trees. This keeps all styles alive and subscribed, which causes entire window contents to stay in memory despite window being already closed. I will ping people in the core team to see what we can do about it since this bug prevents us from having proper multi-window applications.

**Comment by mat1jaczyyy** [comment]
@MarchingCube Testing with `0.9.999-cibuild0005116-beta` this doesnt look fully fixed to me...

Same test repro project attached in original post, but with 3282 merged. Still having objects go up whenever I switch windows:
![image](https://user-images.githubusercontent.com/13300194/69702961-9c60b380-10f0-11ea-8f89-e59269ab58d4.png)

For reference here's the test project with preview7 as was originally tested, no improvement at all:
![image](https://user-images.githubusercontent.com/13300194/69703126-08431c00-10f1-11ea-8f79-5688d30a8467.png)

This is hell for my multi-window app, which has a much larger footprint than this ([mat1jaczyyy/apollo-studio](https://github.com/mat1jaczyyy/apollo-studio), switching between SplashWindow and ProjectWindow):

0.9.0-preview7
![image](https://user-images.githubusercontent.com/13300194/69705428-d7191a80-10f5-11ea-8ba0-34a468ecab7f.png)

0.9.999-cibuild0005116-beta
![image](https://user-images.githubusercontent.com/13300194/69703759-71775f00-10f2-11ea-9b43-5f76cb7a6705.png)

Maybe my approach to creating windows is flawed? Please check the repro I attached originally and bump the Avalonia version to latest.

**Comment by MarchingCube** [comment]
@mat1jaczyyy Rechecked control catalog as well and now I noticed that styling was not the only system keeping windows alive after all. We have two more issues that need to be solved before most of the allocations would be freed:
- `OleDropTarget` is marked as GC root
- `FocusManager` keeps focus scopes from closed windows.

**Comment by mat1jaczyyy** [comment]
Thanks for taking the time to check this out!

**Comment by ahopper** [comment]
Hopefully it is the same cause for https://github.com/AvaloniaUI/Avalonia/issues/2377

**Comment by MarchingCube** [comment]
Opened a PR to fix `OleDropTarget` : https://github.com/AvaloniaUI/Avalonia/pull/3312. `FocusManager` still remains.

**Comment by mat1jaczyyy** [comment]
Good progress 👍

**Comment by MarchingCube** [comment]
Hopefully https://github.com/AvaloniaUI/Avalonia/pull/3331 will resolve your issue. At least in ControlCatalog after this change memory used by Window and contained controls was reclaimed.

**Comment by mat1jaczyyy** [comment]
Resolved with #3331! Thanks @MarchingCube.
