### ISSUE TITLE
DataGrid: Add TreeView-like functionality

### ISSUE THREAD

**Issue by lempamo** [AvaloniaUI/Avalonia#3270]
In WinForms, I can make a TreeView that has a grid system, with columns that one can use to sort/organize values. I would love to see a similar sort of system with Avalonia's DataGrid! There are a few cases I can think of where it would helpful to combine the DataGrid system with the parent-child relations that a TreeView shows

**Comment by grokys** [comment]
We're actually thinking that something like this would be a good commercial control to sell to try to help fund Avalonia.

**Comment by jhofinger** [comment]
WPF offers a light-weight way of this, using a `GridView`. If Avalonia implements a `GridView` someday, this can be achieved by using the header presenter (`GridViewHeaderRowPresenter` in WPF) and styling the content row presenter.

**Comment by timunie** [comment]
Upd: Right now you can try TreeDataGrid, but it is in beta-mode atm: https://docs.avaloniaui.net/docs/controls/treedatagrid/creating-a-hierarchical-treedatagrid#the-treedatagrid-control

**Comment by maxkatz6** [comment]
TreeDataGrid supports it out of the box.
With old DataGrid you can do row details in a different way.
