### ISSUE TITLE
Button becomes grayed out when command is added in ItemsPresenter.

### ISSUE THREAD

**Issue by ShamanDev** [AvaloniaUI/Avalonia#3274]
Hello! I got an issue im currently struggling with. When i create an ItemsPresenter with button inside of it, the button becomes grayed out when i bind a command from ViewModel to it.

`                <Button Width="80" Height="50" HorizontalAlignment="Right" VerticalAlignment="Center" IsEnabled="True" Margin="0,0,10,0" Command="{Binding PlaySong}">Play now</Button>`

`        public MainWindowViewModel()
        {
            PlaySong = ReactiveCommand.Create(() => {
                Console.WriteLine("Song have been played");
            });
        }
`
       ` public ReactiveCommand PlaySong { get; }`

**Comment by grokys** [comment]
Each item in the `ItemsPresenter` will have its `DataContext` set to the item, not the `MainWindowViewModel`.

You can either:

- Add the `PlaySong` command to the item view model
- Bind to the `PlaySong` command on the data context of a parent control, e.g.

```
Command="{Binding $parent[ItemsControl].DataContext.PlaySong}"
```
http://avaloniaui.net/docs/binding/binding-to-controls#binding-to-an-ancestor

**Comment by ShamanDev** [comment]
This worked, thank you so much!
