### ISSUE TITLE
ScrollBar styling

### ISSUE THREAD

**Issue by v0vc** [AvaloniaUI/Avalonia#3275]
Hi all!
Just discovered that after preview2 scrollbar became more wider than before.

Before: 
![pre2](https://user-images.githubusercontent.com/9407549/69137417-c81ae280-0acd-11ea-942c-04e6fb7d7e77.png)
After: 
![pre3](https://user-images.githubusercontent.com/9407549/69137442-d2d57780-0acd-11ea-8558-874bcab57861.png)

Is there any way to revert preview2 scrollbar view? May be somethig like autohide?

Thanks!

**Comment by kekekeks** [comment]
You can try copy-pasting the [previous style](https://github.com/AvaloniaUI/Avalonia/blob/9a9ef657e26ea7f0bf382ce0041eebe575fb211d/src/Avalonia.Themes.Default/ScrollBar.xaml) to your app.

**Comment by v0vc** [comment]
@kekekeks Thanks, it working.

`<Style Selector="ScrollBar:horizontal /template/ Thumb#thumb">
            <Setter Property="MinWidth" Value="10" />
            <Setter Property="Height" Value="10" />
        </Style>
        <Style Selector="ScrollBar:vertical">
            <Setter Property="Width" Value="10" />
        </Style>
        <Style Selector="ScrollBar:vertical /template/ Thumb#thumb">
            <Setter Property="MinHeight" Value="10" />
            <Setter Property="Width" Value="10" />
        </Style>`
