### ISSUE TITLE
FindNameScope() returns null in Window.OnInitialized() override

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#3277]
If you override OnInitialized in a Window (and possibly other IControls) and call `this.FindControl<T>(name)` you will get an InvalidOperationException because there FindNameScope() returns null. Calling `this.Find<T>(name)` will just return null. Shouldn't everything be ready at this point?

**Comment by Gillibald** [comment]
It should be ready when InitializeComponent is called

**Comment by SinnoSong** [comment]
@Kermalis I have the same problem,what can i do to fix it?

**Comment by SinnoSong** [comment]
> @Kermalis I have the same problem,what can i do to fix it?

I had use 'TemplateApplied' resolve this problem.

**Comment by timahrentlov** [comment]
I'm seeing that this source generated line

UiHost = this.FindNameScope()?.Find<global::Avalonia.ReactiveUI.RoutedViewHost>("UiHost");

returns null in V11 rc1
