### ISSUE TITLE
Inconsistent window decoration behavior in macOS

### ISSUE THREAD

**Issue by balthild** [AvaloniaUI/Avalonia#3280]
### Version

- Avalonia 0.9.0-preview7
- macOS 10.15.1

### Behavior 

- A normal window:
  - There're small black angles at the left-top corner and right-top corner. Likely it's the overflown black background behind the title bar.
  - After resizing, the angles disappeared.
- A window without decoration:
  - There're no shadow and border around the window.
  - After resizing, the shadow and border shows correctly.

![ezgif-2-30568a6b85bb](https://user-images.githubusercontent.com/2662758/69238827-d2bf9f80-0bd3-11ea-8fa7-e2b51cc9e455.gif)

**Comment by mstr2** [comment]
Probably related: https://github.com/AvaloniaUI/Avalonia/issues/2069
