### ISSUE TITLE
Resize fails on Windows if done during minimization

### ISSUE THREAD

**Issue by NicolasDorier** [AvaloniaUI/Avalonia#3291]
1. Get a windows say 800x600
2. Minimize the window
3. Resize the window (either manually via ClientSize OR by triggering a stackpanel to become visible which should change the size of the window if SizeToContent is set to Width/Height)
4. Restore the window

0.9.0-preview7

**Comment by NicolasDorier** [comment]
it seems it happen if an element is expanded while the windows is minimized. When you restore, programatic resizing get completely broken.

**Comment by NicolasDorier** [comment]
The problem happens even if `SizeToContent="Manual"`. 

The root of the problem is that when the window is restored, Avalonia seems to set the `ClientSize` back to what it was before it has been minimized, regardless of whether `SizeToContent` and even if this `ClientSize` changed while the windows was minimized.

**Comment by grokys** [comment]
I think the problem here is that there's no way of telling whether a resize was caused by an auto-resize, a user resize or a minimize/restore.

A user resize always results in auto-resizing being turned off, but we need a way to tell where the resize event came from. I'm not sure there is any of way of knowing that?

**Comment by grokys** [comment]
I tried to solve this here https://github.com/AvaloniaUI/Avalonia/pull/2383 but gave up... Probably need to revisit this soon.

@jmacato I don't think this can be fixed for 0.9, it's not a simple problem.

**Comment by jmacato** [comment]
@grokys got it, i included it to 0.9 for posterity; removing milestones now

**Comment by grokys** [comment]
@NicolasDorier when you say that "it happens even if `SizeToContent="Manual" - what happens? The problem is "Not sizing to content anymore", right? If `SizeToContent="Manual"` then it shouldn't be sizing to content.

Sorry, I'm probably thick here ;)

**Comment by NicolasDorier** [comment]
@grokys so here it what happen precisely, whichever the value of `SizeToContent`.

1. Get a windows say 800x600
2. Minimize the window
3. Resize the window (either manually via `ClientSize` OR by triggering a stackpanel to become visible which should change the size if `SizeToContent` is set to Width/Height)
4. Restore the window

What I noticed was that after step `3.` the windows `ClientSize` and `DesiredSize` is what is expected.
But as soon as `4.` happen, the size go back to 800x600.

**Comment by Gillibald** [comment]
What is the content of your StackPanel? Does it have a fixed size? SizeToContent only works if your content has a fixed size (DesiredSize != infinity)

**Comment by NicolasDorier** [comment]
@Gillibald here is my windows:

https://github.com/btcpayserver/BTCPayServer.Vault/blob/master/BTCPayServer.Vault/MainWindow.xaml

The problematic stackpanel is `<StackPanel IsVisible="{Binding IsVisible}" Margin="0,15,0,0">`
