### ISSUE TITLE
[ Skia ] Caret position doesn't respect TextAlignment when .Text is empty

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#3294]
MCVE:

```xaml
    <TextBox
        MinWidth="120"
        HorizontalAlignment="Center"
        VerticalAlignment="Center"
        TextAlignment="Center" />
```

![textBox](https://user-images.githubusercontent.com/16510738/69656599-849e1680-1081-11ea-94a9-d127d538b3d3.gif)

Version: 0.9.0-preview8

**Comment by Gillibald** [comment]
This is not a Skia issue. Direct2D1 most likly produces the same.

**Comment by FoggyFinder** [comment]
On Direct2D1 I got exception so it is Skia issue
