### ISSUE TITLE
Question - [DataGrid] Missing (0.8.3)

### ISSUE THREAD

**Issue by b14ck1** [AvaloniaUI/Avalonia#3299]
Hey there,
I recently found this project and it fits all my needs since I need to port an existing .Net Core 3.x, WPF application to cross plattform support.

I created a new MVVM-project from the .Net Core 3.x - Templates provided here: https://github.com/AvaloniaUI/avalonia-dotnet-templates

With this template Avalonia, Avalonia.Desktop, Avalonia.ReactiveUI are installed via NuGet and all on version 0.8.3.

Everything works fine, however i cannot specify a DataGrid control. Whether in XAML or in Code it's just not there. I also read through #2426, but according to this it should be resolved.

I also tried updating to the latest 0.9-preview8. After updating I coudln't call UseReactiveUI() from the AppBuilder anymore and still got no DataGrid.

I'm a little lost right now where to search for my error so any help would be greatly appreciated!

**Comment by FoggyFinder** [comment]
Datagrid is placed in the separate NuGet package. Try to install

[Avalonia.Controls.DataGrid](https://www.nuget.org/packages/Avalonia.Controls.DataGrid/0.9.0-preview8)

**Comment by b14ck1** [comment]
Thanks for this .. I was wondering if it is in a seperate dll or something because I coudln't find a trace of it in the dll's or the standard package.
I'll give it a shot when I'm home and report back then.

Is this separate NuGet package stated somewhere in the docs? Just curious if I was to dumb to find it.

**Comment by FoggyFinder** [comment]
No, as far as I can tell. But docs is open source as well: 

https://github.com/AvaloniaUI/avaloniaui.net

so anyone can add missing pages.

**Comment by b14ck1** [comment]
Hey reporting back.
Installing the additional package and following this one: https://www.nequalsonelifestyle.com/2019/06/13/avalonia-datagrid-getting-started/ to add the default dataGrid styles everything now works as expected.

When i have a little more time I'll add it to the docs.

Thanks again!
