### ISSUE TITLE
rich textbox

### ISSUE THREAD

**Issue by Xawx** [AvaloniaUI/Avalonia#3303]
Hi!

Is it possible, or in plans to provide an API to use "rich textbox features"

like ways to manipulate font color / background color of certian characters, accessing caret position, obtaining (x,y) coordinates of caret on screen?

Basically something like this

![img](https://user-images.githubusercontent.com/24208624/69757057-40337900-115c-11ea-86ed-636ca7e66446.png)

**Comment by danwalmsley** [comment]
you need https://github.com/avaloniaui/avaloniaedit

**Comment by Gillibald** [comment]
RichTextBox will come to Avalonia in the future but I can't guarantee when that will happen. For now the posted component might fulfill your needs.

**Comment by jinyuttt** [comment]
Can it support rich text input such as hyperlinks, color text, pictures and so on?
