### ISSUE TITLE
How to get the selected value of CheckBox in TreeView. ?

### ISSUE THREAD

**Issue by huanglunxi** [AvaloniaUI/Avalonia#3305]
<TreeView Name="TreeView1" Width="250" Height="350">
        <TreeView.ItemTemplate>
          <TreeDataTemplate ItemsSource="{Binding list}">
            <CheckBox Content="{Binding ModuleName}" Tag="{Binding Id}"/>
          </TreeDataTemplate>
        </TreeView.ItemTemplate>
      </TreeView>

How to get the selected value of CheckBox in TreeView. ?

**Comment by huanglunxi** [comment]
<TreeView Name="TreeView1" Width="250" Height="350">
        <TreeView.ItemTemplate>
          <TreeDataTemplate ItemsSource="{Binding list}">
            <CheckBox Content="{Binding Name}" Tag="{Binding Id}"/>
          </TreeDataTemplate>
        </TreeView.ItemTemplate>
      </TreeView>

**Comment by huanglunxi** [comment]
![76DA tmp](https://user-images.githubusercontent.com/58202041/69812951-311bfc00-122c-11ea-981d-7d73b2d68f4b.jpg)

**Comment by FoggyFinder** [comment]
There is a `IsChecked` property. See [docs](https://avaloniaui.net/docs/controls/checkbox)

**Comment by Gillibald** [comment]
Did that help to solve your problem? Pls let us know if you need more details. Will close this as solved for now.
