### ISSUE TITLE
Font fallback funtionality is lost

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#3308]
in current master Font fallbacks are lost and default system font is used in case first font is not found:

try 
`<Window FontFamilty="Non existent Font, Times New Roman" ... > ...`

all child content will be rendered with default system font (Segoe UI on windows) instead `Times New Roman`  even if `Times New Roman` is present on the system.

expected:
 Font to fallback to system only after no matching font is found in `FontFamily` names list.

Font fallbacks was working until recently, look like #3195 has incidently removed the support for the fallbacks.
for reference this lines was making fallbacks work (For Skia):
https://github.com/Gillibald/Avalonia/blob/69c24dc99df33a7eb8ee544ccba0a465acd9a632/src/Skia/Avalonia.Skia/FormattedTextImpl.cs#L40-L50

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/3234/files#diff-d7bbd5364243322d4d80ee13c41d8dbbR16

**Comment by donandren** [comment]
@Gillibald #3309

**Comment by donandren** [comment]
fixed by #3234
