### ISSUE TITLE
ListBox Item's Grid Tapped/DoubleTapped not called when tapped directly

### ISSUE THREAD

**Issue by migajek** [AvaloniaUI/Avalonia#3310]
When having `ListBox` with `ListBox.ItemTemplate` containing Grid, and having `Tapped` handler defined on the `Grid`, the handler is not being called when the item is clicked directly.
The handler is being called only when any of the items inside is clicked.

Assuming the following code, I'd expect the `Tapped` handler to be called whenever I click anywhere inside the ListBox `Item`. However it is being called only when I click any of the components inside (Image, TextBlock or Button).

**Suprisingly it is being called properly in XAML designer in VS**

Please find the full repro code here: https://github.com/migajek/Avalonia-Listbox-Tapped-Repro

```
<ListBox Items="{Binding Items}">
      <ListBox.ItemTemplate>
        <DataTemplate>
          <Grid
            ColumnDefinitions="Auto,190,Auto"
            Tapped="GotTapped"
            >
            <Image Grid.Column="0" Source="/Assets/avalonia-logo.ico" Width="32" Height="32" Tag="Image" />
            <TextBlock Grid.Column="1" Margin="4" Text="{Binding Name}" Tag="Name textbox"/>
            <Button Grid.Column="2" Tag="Btn">
              <TextBlock Text="FooBar!" Tag="Text in btn" />
            </Button>
          </Grid>
        </DataTemplate>
      </ListBox.ItemTemplate>
    </ListBox>
```

**Comment by agnauck** [comment]
hitting the same issue right now.
Did you find a workaround for this?

**Comment by sakya** [comment]
Just set a background color to the grid and it works
`          <Grid
            ColumnDefinitions="Auto,190,Auto"
            Background="Transparent"
            Tapped="GotTapped"
            Tag="Grid"
            >`

**Comment by maxkatz6** [comment]
Expected behavior. Background should be set to be able to hit test element.
