### ISSUE TITLE
SharpGen-MSBuild.xml appears to be missing in Linux (Ubuntu)

### ISSUE THREAD

**Issue by rocket0634** [AvaloniaUI/Avalonia#3311]
Hello there, I was looking into working with this project in Linux and I attempted to run the ControlCatalog.NetCore project. Unfortunately, after building the project, I run into the following error:

`.nuget/packages/sharpgentools.sdk/1.1.2/build/SharpGenTools.Sdk.targets(162,5): Process error CX0001: error: no such file or directory: 'projects/Avalonia/Avalonia/src/Avalonia.Native/obj/Debug/netstandard2.0/SharpGen/SharpGen-MSBuild.xml' [~/Other projects/Avalonia/Avalonia/src/Avalonia.Native/Avalonia.Native.csproj]`

I actually realized that this issue was caused by the space in the folder I have the project in. I'm not certain if this is an Avalonia issue or a SharpGen issue. Moving the folder to ~/Avalonia allowed it to build properly.

**Comment by JamesLear92** [comment]
Just had the same problem. I don't think I'd ever have worked out that I couldn't have a space in the folder name if I hadn't come across this page
