### ISSUE TITLE
Any way to Drag-Drop-Order a ListBox?

### ISSUE THREAD

**Issue by adroslice** [AvaloniaUI/Avalonia#3313]
I've looked through the API, searched for libraries and even tried to implement it myself using pointer events but failed, because it seems like IsPointerOver isn't updated for all the elements for as long as the pointer is pressed.
Is there any way to do this, or are there any suggestions for alternatives?
I probably would have posted this somewhere else if I knew a place for less serious community discussion.
Requesting question label.

**Comment by kekekeks** [comment]
> it seems like IsPointerOver isn't updated 

Pointer is automatically captured on press

>tried to implement it myself using pointer events 

`window.GetVisualsAt(pointRelativeToWindow, _ => true)` should give you the list of visuals under particular point. That can be used for triggering drop-interaction from drag source control handling pointer event.

**Comment by adroslice** [comment]
Say I have an AvaloniaList<string> bound to ListBox.Items. How do I figure out which visual belongs to the correct logical element, so I can figure out the correct index? This seems really complicated, I can't quite wrap my head around it. Here's the code I used prior to your suggestion, where HoveredItem was just a get-only property to get the hovered over ListBoxItem using the IsPointerOver property. I reckon this would work if the pointer wasn't captured, and I wonder if there's a way to disable that behaviour just for a certain control.
```csharp
public void OLBMoved(object sender, PointerEventArgs e)
{
    if (DragItem == null) return;
    if (DragItem != HoveredItem && HoveredItem != null)
        Items.Move(
            OrderableListBox.GetLogicalChildren().ToList().IndexOf(DragItem),
            OrderableListBox.GetLogicalChildren().ToList().IndexOf(HoveredItem));
    
    Title = (++MoveCount).ToString();
}
```

**Comment by adroslice** [comment]
I found a solution that I suppose will be sufficient for now. I gave up on the idea of having the element move as you drag for now, and instead only move it as you release the drag, otherwise it'd be quite a bit more complicated. I should also definitely refactor this first line so it's shorter and more readable.

```csharp
public void OLBReleased(object sender, PointerReleasedEventArgs e)
{
    var hoveredItem = (ListBoxItem)OrderableListBox.GetLogicalChildren().FirstOrDefault(x => this.GetVisualsAt(e.GetPosition(this)).Contains(((IVisual)x).GetVisualChildren().First()));
    if (DragItem == null ||
        hoveredItem == null ||
        DragItem == hoveredItem)
        return;
    Items.Move(
        OrderableListBox.GetLogicalChildren().ToList().IndexOf(DragItem),
        OrderableListBox.GetLogicalChildren().ToList().IndexOf(hoveredItem));

    DragItem = null;
}
```
