### ISSUE TITLE
ContextMenu and ToolTip Drawing Irregularities

### ISSUE THREAD

**Issue by HankG** [AvaloniaUI/Avalonia#3314]
There are two behaviors I've been seeing with Tooltips and ContextMenus recently although when building the below demo the problem seems to have existed back in 0.8.2 as well. The most consistent bug is that if a ContextMenu is set to not be visible it actually still renders a ghost menu. For example: 
![image](https://user-images.githubusercontent.com/1683691/69904742-4605a600-1378-11ea-8d2c-3666edf0c78f.png)

The second thing that's happening is frequently, though intermittently, the bounds of a Tooltip or ContextMenu are far greater than their actual bounds. Often once they are drawn once, dismissed, and brought back, they are the right size. For example in the below screenshot you'll often get this display for the Tooltip the first time (but still not every time it runs) but then it draws correctly every other time (it shows up in the above screenshot as well properly sized).

![image](https://user-images.githubusercontent.com/1683691/69904781-c1675780-1378-11ea-936e-88d9754bb345.png)

I have not tried to reproduce this on Windows or Mac. This is just on Linux Mint MATE 19.1

The source code that produces this behavior can be found at: https://gitlab.com/HankG/codepad/tree/master/dotnet/avalonia/ContextMenuDrawingBug

**Comment by MikeCodesDotNET** [comment]
Seems to be fixed in the latest v11 release.
