### ISSUE TITLE
Support .NET Core 3.1

### ISSUE THREAD

**Issue by AlseinX** [AvaloniaUI/Avalonia#3322]
Now .NET Core 3.1 has been released as LTS.
Is Avalonia adapting this?

**Comment by MarchingCube** [comment]
Avalonia targets .NET Standard 2.0 and runs on .NET Core 3.1 out of box.  Tested that locally by targeting our sample `ControlCatalog` to 3.1 and it just works.

**Comment by NicolasDorier** [comment]
I tried on 3.1, works fine as well.

**Comment by jmacato** [comment]
I wonder if we could just wait to both drop legacy .NET and switch to .NET 5.0 when that's out next year. Though thinking about it, we probably should just target the `netstandards` instead of a specific dotnet version.

**Comment by aguahombre** [comment]
On Windows I had no problem retargeting my app to dotnetcore 3.1; I rebuilt and it ran the same as before.

But the Linux build throws an error at compile time:
```dotnet publish -c Release -r linux-arm -f netcoreapp3.1```

```
...\.nuget\packages\avalonia\0.9.999-cibuild0005352-beta\build\AvaloniaBuildTasks.targets(36,5): 
error MSB4062: The "GenerateAvaloniaResourcesTask" task could not be loaded from the assembly 
...\.nuget\packages\avalonia\0.9.999-cibuild0005352-beta\build\\..\tools\netstandard2.0\Avalonia.Build.Tasks.dll. 
Assembly with same name is already 
loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its 
dependencies are available, and that the task contains a public class that implements 
Microsoft.Build.Framework.ITask. [MyApp.csproj]
```
How do I fix this?

**Comment by aguahombre** [comment]
After rolling back to v0.9.0-rc0001 and rebooting my dev machine for some window updates, it works.
Not sure which fixed it.

**Comment by frankhaugen** [comment]
> Now .NET Core 3.1 has been released as LTS.
> Is Avalonia adapting this?

It's working now. I just installed Avalonia extension, created a project from template, chaged the target framework to 3.1, and it just worked

**Comment by AlseinX** [comment]
Well, I mean the direct support, which means running test directly on `netcoreapp3.1` on all supported platforms.

**Comment by kekekeks** [comment]
Actually running tests on `netcoreapp3.1` is a good point. There were some breaking changes (even on JIT level).

**Comment by AlseinX** [comment]
And maybe add some conditional compiled codes that takes advantage of the new apis from `netstandard2.1` and `netcoreapp3.1` for optimization.

**Comment by AlseinX** [comment]
Unless direct IL emitting is used, there could not be a `call` opcode for interface method calls.
Does Avalonia use related features?

**Comment by kekekeks** [comment]
We have our own XAML-to-MSIL compiler, yes.
