### ISSUE TITLE
[Question] DoubleTapped event fires for all pointer presses except right mouse button

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#3325]
Not sure if this is by design, but it's not really intuitive that `DoubleTapped` fires for all clicks except right mouse button ones (i.e. it can occur on left, middle, xbutton 1, xbutton 2, ... mouse button clicks).

The check in question is here: https://github.com/AvaloniaUI/Avalonia/blob/5167cd9d53dc59434b7ad9892473c31e0be90ac4/src/Avalonia.Input/Gestures.cs#L82.

I believe it should only trigger for left button clicks.

**Comment by grokys** [comment]
@jp2masa yep i think you're right!
