### ISSUE TITLE
[Question] Can I show several dynaimc view models in a wiew

### ISSUE THREAD

**Issue by Yavari** [AvaloniaUI/Avalonia#3333]
I am following the tutorial https://avaloniaui.net/docs/tutorial/wiring-up-views and the tutorial shows that I can bind a view to the Content property of Windows in order to dynamically change the view based on the view model. 
Is it possible to the same thing with a Control? I want to be able to do the same thing but for several views. Something similar to the code bellow where TopView and BottomView would be two diffrent ViewModelBase properties on the view model

```
 <DockPanel>
            <viewModels:ViewModelPresenter ViewModel="{Binding TopView}" DockPanel.Dock="Top" />
            <viewModels:ViewModelPresenter ViewModel="{Binding BottomView}" DockPanel.Dock="Bottom" />
..
```

**Comment by Yavari** [comment]
This was what I was looking for

    public class ViewPresenter : UserControl
    {
        public static readonly AvaloniaProperty<object> ViewModelProperty =
            AvaloniaProperty.Register<ViewPresenter, object>(nameof(ViewModel));

        static ViewPresenter()
        {
            ViewModelProperty.Changed.Subscribe(OnViewModelPropertyChanged);
        }

        public object ViewModel { get; set; }

        private static void OnViewModelPropertyChanged(AvaloniaPropertyChangedEventArgs e)
        {
            if (e.Sender is ViewPresenter a && e.NewValue is ViewModelBase)
            {
                a.Content = e.NewValue;
            }
        }
    }

**Comment by FoggyFinder** [comment]
There is a [`ContentControl`](https://avaloniaui.net/docs/controls/contentcontrol)
