### ISSUE TITLE
Microsoft.CodeAnalysis dlls included published output

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#3337]
On netcore 3.0 and 3.1 Microsoft.CodeAnalysis.VisualBasic.dll, Microsoft.CodeAnalysis.CSharp.dll & Microsoft.CodeAnalysis.dll are copied to the output on publish, this adds >18M to the size.

**Comment by ahopper** [comment]
looking at deps.json I suspect this is caused by sharpdx. If a blank project is built without a reference to Avalonia.Desktop and just skia and win32
```
 <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.0-rc.1" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.9.0-rc.1" />
    <PackageReference Include="Avalonia.Skia" Version="0.9.0-rc.1" />
    <PackageReference Include="Avalonia.Win32" Version="0.9.0-rc.1" />
  </ItemGroup>
```
and
```
public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UseWin32()
                .UseSkia()
                .LogToDebug()
                .UseReactiveUI();
```
a framework dependent 3.1 build drops from 25M to 12M in size.
I wonder if using build and compiler defines is a better way to go than UsePlatformDetect for publishing.

**Comment by ahopper** [comment]
https://github.com/ahopper/Avalonia.IconPacks/tree/no-avalonia-desktop has a work around for windows, osx and linux publish (see project file and program.cs) which makes the published output neater and smaller but it would be nice to find a neater solution.  The avalonia native bits are quite large so I can't see many situations where a platform independent publish makes sense.

**Comment by rstm-sf** [comment]
At the moment, .NET 5.0 and Avalonia 0.10, I don't see this

This can happen if we use `Avalonia.Diagnostics`. This package references `Microsoft.CodeAnalysis.CSharp.Scripting`
https://github.com/AvaloniaUI/Avalonia/blob/cae9badc1c3220baa4400c3db3a3e548075c50fe/src/Avalonia.Diagnostics/Avalonia.Diagnostics.csproj#L27

**Comment by ahopper** [comment]
Excluding Avalonia.Diagnostics as above fixes this for .net6.0 as well.
