### ISSUE TITLE
Binding DynamicData observables enhancement

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#3339]
At the moment we can bind a control property to ```IObservable<T>``` using the ^ operator.

It would be nice enhancement to be able to bind ```ItemsControl.Items``` (etc) to DynamicData observables such as``` IObservableList<T>``` and ```IObservable<IChangeSet<T>>``` using the same operator.

```
class MyViewModel
{
   public  IObservableList<MyItem> MyItems { get ;}
}

<ItemsControl Items="{Binding MyItems^}"/>
```
One benefit would be that the ViewModel doesn't need to create and maintain a ```ReadOnlyObservableCollection<T>``` when the view binds directly to ```IObservableList<T>```; the collection will never be created if the View never instantiates the control.

**Comment by Gillibald** [comment]
IObservableList<T> requires a dependency on DynamicData. Unless we use DynamicData in the core of Avalonia support for this is unlikely to happen.

**Comment by aguahombre** [comment]
I think you already have an indirect dependency on it as ReactiveUI  v10.3.6 depends on DynamicData v6.13.9

**Comment by Gillibald** [comment]
Avalonia works perfectly fine without ReactiveUI and has no direct dependency as you stated. The binding system is part of the core of Avalonia. This feature should be optional.

**Comment by aguahombre** [comment]
My mistake, it's only used in the Avalonia.ReactiveUI.
Perhaps someday a DynamicData Binding markup extension could be added to that assembly.

**Comment by Gillibald** [comment]
I think we need a prototype that uses DynamicData in a sortable, groupable "ItemsControl". The control itself would need direct access to IObservableList etc

**Comment by jp2masa** [comment]
It should be possible to extend the binding system with a stream plugin: 

For reference:
- [`IStreamPlugin`](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Data/Core/Plugins/IStreamPlugin.cs)
- [`ObservableStreamPlugin` (implementation for `IObservable`)](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Data/Core/Plugins/ObservableStreamPlugin.cs)
- [The list of stream plugin handlers (you can add custom plugins to this list)](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Data/Core/ExpressionObserver.cs#L48)

**Comment by MikeCodesDotNET** [comment]
Closing as we've removed our dependency on RxUI from our templates.
