### ISSUE TITLE
Main Window does not restore correctly for windows snapped to one side of the screen

### ISSUE THREAD

**Issue by garyhertel** [AvaloniaUI/Avalonia#3341]
On Windows, restoring a minimized Avalonia window will not restore it to its previous position if it's docked to one side of the screen. So if I take the control catalog app and press (<window-key> + <left>) so it fills the left half of the desktop, minimize it, and then restore it, it restores back to the original size instead of filling the left half the desktop. Oddly, the control catalog doesn't have this problem when maximizing the window. 

Trying this with any other windows app behaves as expected, with the app filling the left half the desktop after restoring.

**Comment by salaroglio** [comment]
Same problem here, is there a workaround?

**Comment by tomenscape** [comment]
Cannot reproduce in version 11preview4. I think this can be closed.
