### ISSUE TITLE
Question: Is it possible to use Avalonia within a WPF application

### ISSUE THREAD

**Issue by Yavari** [AvaloniaUI/Avalonia#3351]
I want to try to migrate a WPF application to Avalonia are wondering if it is possible to start doing that by replacing one WPF view at the time to a Avalonia view? 
Are there any examples on how to start using Avalonia within WPF?

**Comment by kekekeks** [comment]
See https://github.com/AvaloniaUI/Avalonia/tree/master/samples/interop/WindowsInteropTest
