### ISSUE TITLE
Dynamic data for an ItemsControl

### ISSUE THREAD

**Issue by tluyben** [AvaloniaUI/Avalonia#3353]
I have an ItemsControl with a DataTemplate which is dynamically built up (in code) from a JSON document; the JSON document contains product data and the list rows need to change depending on what is in that data format. It is not possible to determine the number of fields upfront and so this must be dynamic. Now that that works fine, how do I dynamically bind te JSON to it? I cannot prepare the usual model classes for doing this; it's dynamic and will change (a lot) in the near future. I looked here and in WPF on how to do that and I could not find anything that looks like it does something like that (I found some WPF code which uses a Dictionary instead of a model class, but that's not enough even if that would work as it was only for the value field; I would need the key field be the binding name and the value the value that shows in the row; that could work). So how can I bind the control and template in such way that it picks from a datastructure which does not have getters and setters for the bound fields in the row?

**Comment by tluyben** [comment]
Seems I managed myself: 

https://gist.github.com/tluyben/c8bdfc27024e9ffe4453cbba7cf6ff06

That was what I was looking for. In the end Xamarin old community answers made me figure out how to do it.

**Comment by tluyben** [comment]
When I add a CheckBox it does not work; 

https://gist.github.com/tluyben/f4f55807e056dae5e077752addc5fbd9

It works fine for labels and it works fine when I use the modelList (normal List<ListItem>) but it does not work with a Dictionary. Why is that? Is that something fundamentally impossible or am I doing something weird? I can fix it by just assigning the IsChecked and Notify here but that's ofcourse not the idea of the binding.

**Comment by tluyben** [comment]
This is the exception thrown when I add the CheckBox, so : 

https://github.com/AvaloniaUI/Avalonia/blob/6f2b9b654e0cddbc443a2031e08c11dac0f7082d/src/Markup/Avalonia.Markup/Markup/Parsers/Nodes/StringIndexerNode.cs#L131

target == null ? 


```
Exception has occurred: CLR/System.NullReferenceException
An exception of type 'System.NullReferenceException' occurred in Avalonia.Markup.dll but was not handled in user code: 'Object reference not set to an instance of an object.'
   at Avalonia.Markup.Parsers.Nodes.StringIndexerNode.get_PropertyType()
   at Avalonia.Data.Core.ExpressionObserver.get_ResultType()
   at Avalonia.Data.Core.BindingExpression.OnNext(Object value)
   at Avalonia.Reactive.AvaloniaPropertyObservable`1.Subscribed(IObserver`1 observer, Boolean first)
   at Avalonia.Reactive.LightweightObservableBase`1.Subscribe(IObserver`1 observer)
   at Avalonia.Data.BindingOperations.Apply(IAvaloniaObject target, AvaloniaProperty property, InstancedBinding binding, Object anchor)
   at Avalonia.AvaloniaObjectExtensions.Bind(IAvaloniaObject target, AvaloniaProperty property, IBinding binding, Object anchor)
   at Avalonia.AvaloniaObject.set_Item(IndexerDescriptor binding, IBinding value)
   at Playground.ListView.<>c.<InitializeComponent>b__1_1(Dictionary`2 x) in ``
```

**Comment by MikeCodesDotNET** [comment]
If you're still having issues, I'd recommend joining our Telegram community for help.
