### ISSUE TITLE
Raspberry PI using nightly builds

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#3354]
Does anyone know how to build an app for the Raspberry PI using the latest nightly builds 0.9.999-cibuild0005352-beta?

As per the instruction in the link https://github.com/AvaloniaUI/Avalonia/wiki/Run-an-Avalonia-application-on-Raspberry-Pi,  you include the NuGet package Avalonia.Skia.Linux.Natives v1.68.0.2 to get libSkiaSharp.so but this includes a version of the library that is incompatible with the nightly build; it throws a System.EntryPointNotFoundException.

I assume there is a different NuGet package required, what is it?

**Comment by Gillibald** [comment]
There is currently no support for ARM with the current master

**Comment by aguahombre** [comment]
OK, reverted back to 0.9.0-rc0001

It appears by trial and error that Avalonia.Skia is the replacement for Avalonia.Skia.Linux.Natives

**Comment by kekekeks** [comment]
The official SkiaSharp doesn't produce ARM build. We haven't updated our ARM-capable SkiaSharp package to the latest SkiaSharp version. You can use 0.9 rc versions for now, since 0.9 release will ship with SkiaSharp 1.68.0.
