### ISSUE TITLE
On macOS popups are not closed when clicking on window titlebar

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#3355]
On macOS popups (from ComboBox for example) are not closed when clicking on window titlebar.
As a side effect from that user can move window, but popup stays in it's original position and looking wierd.

This issue is macOS specific only, on windows it's working as expected -> once user click on title bar open popup (from a ComboBox) is closed.
The most possible reason is: event for the non client click on mac os window is not fired here:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Primitives/Popup.cs#L261-L262

**Comment by mohdimas** [comment]
Does https://github.com/AvaloniaUI/Avalonia/pull/6926 fix this issue? Based on our testing on `0.10.11-rc.1`, it's partially fixed. Resizing window sometimes doesn't close the popup only on MacOS.
