### ISSUE TITLE
Touch scroll does not work for DataGrid

### ISSUE THREAD

**Issue by Feroks** [AvaloniaUI/Avalonia#3358]
I am using Avalonia 0.9 stable version on raspberry PI with Touch enabled monitor.
Scrolling works for `ListBox`, but sadly it does not for `DataGrid`. I poked around the code and my guess is that it does not detect gestures, because it does not use `ScrollContentPresenter` like `ListBox`.

Is my assumption correct? Can you check if touch scroll works for you?

**Comment by kekekeks** [comment]
Yes, DataGrid is using scrollbars manually because it's a ported control from silverlight era.

**Comment by dlukach** [comment]
would we be able to add touch scroll to the datagrid, I really need this for my product

**Comment by grokys** [comment]
Fixed by #6342
