### ISSUE TITLE
SizeToContent overrided on macOS if CanResize set to false

### ISSUE THREAD

**Issue by HankG** [AvaloniaUI/Avalonia#3360]
I'm diagnosing the problem with the [MessagBox.Avalonia](https://gitlab.com/HankG/messagebox.avalonia) project where the dialog boxes are opening huge on Mac but fine on Linux and Windows under Avalonia 0.9. I have tracked the problem down but not sure how to fix it. What is happening on Mac is that when CanResize is set in the native code to `false` it ends up generating a native Resize event which then leads us to the `Window.HandleResized` handler which looks like this on Line 567 of Window.cs:
```csharp
        protected sealed override void HandleResized(Size clientSize)
        {
            if (!AutoSizing)
            {
                SizeToContent = SizeToContent.Manual;
            }

            base.HandleResized(clientSize);
        }
```
Since the Window didn't initiate this AutoSizing is set to false. It therefore permanently overrides the SizeContent to be Manual. Thus the rest of the auto-content sizing code never executes. So what looks something like this:

![image](https://user-images.githubusercontent.com/1683691/70878894-51201f00-1f91-11ea-8f7d-7341d2779d78.png)

Looks like this:

![image](https://user-images.githubusercontent.com/1683691/70878897-58dfc380-1f91-11ea-8971-823d568172fc.png)

With the debugger attached I've overriden the value of AutoSizing to true long enough to go through the code during the handling of this native callback and it produces consistent output. I'm not sure what the preferred method of actually addressing that is though. The code in this method is the original implementation so I'm not sure why it started happening with 0.9. For the main developers the solution may be easier to spot. If you have some insights on where to start looking I don't mind nosing around a bit more.

The stack trace is here:
![image](https://user-images.githubusercontent.com/1683691/70879432-4feff180-1f93-11ea-9d8c-c9f45d631f08.png)

**Comment by grokys** [comment]
I've heard that a workaround for the moment is to set `CanResize` before setting `Width`/`SizeToContent` etc

**Comment by Carlos487** [comment]
I can confirm the problem persists on Avalonia 0.9.7 and dotnet 3.1.200 on MacOS Mojave 10.14.6 and the workaround does not work. Tried setting the values in order in the Xaml and in the View constructor but it didn't work either.

**Comment by fncap** [comment]
I faced out this issue too, and as a workaround I set sizes and max size for window. E.g.
`<Style Selector="Window.SplashScreen">
        <Setter Property="Width" Value="450" />
        <Setter Property="MaxWidth" Value="450" />
        <Setter Property="Height" Value="300" />
        <Setter Property="MaxHeight" Value="300" />
        <Setter Property="CanResize" Value="false"/>
        <Setter Property="HasSystemDecorations" Value="false" />
        <Setter Property="WindowStartupLocation" Value="{x:Static WindowStartupLocation.CenterScreen}" />
    </Style>`

**Comment by danwalmsley** [comment]
Seems sizetocontent isnt working at all on OSX right now.

**Comment by danwalmsley** [comment]
fixed.
