### ISSUE TITLE
App writed on F# results in an empty window

### ISSUE THREAD

**Issue by jl0pd** [AvaloniaUI/Avalonia#3362]
I'm learning F# and for educational purposes trying to rewrite C# code to F# just to see how it's different. Now I created Avalonia example through _dotnet new avalonia.mvvm -o SecondApp_ and rewritten all code from C# to F# class after class. On launch compiler doesn't complains on anything, but application window is blank:
![Screenshot from 2019-12-16 21-34-29](https://user-images.githubusercontent.com/36221916/70915127-e1229f00-204b-11ea-98b7-2f8220a85a14.png)
When trying to do same thing with other template _dotnet new avalonia.app -o FirstApp_ everything works fine and window fills with content

Attaching repository with code: [AvaloniaTestApp](https://github.com/jl0pd/AvaloniaTestApp)

Am I doing something wrong when compiling or Avalonia have problems with F#?

### System configuration
dotnet core 3.0.101
os: linux mint 19.1 cinnamon

**Comment by FoggyFinder** [comment]
Avalonia works well with F#.

In your sample you just missed `App` part - you use  default `Application` instead of `SecondApp.App`.

So styles were not applied. Therefore, you can either use your `SecondApp.App` type or add styles like in a sample below:

```fs
let AppMain (app: Application) args =
    app.Styles.AddRange [ 
        new StyleInclude(baseUri = null, Source = Uri("avares://Avalonia.Themes.Default/DefaultTheme.xaml"))
        new StyleInclude(baseUri = null, Source = Uri("avares://Avalonia.Themes.Default/Accents/BaseLight.xaml"))
    ]
```

but I do recommend taking the first way.

**Comment by jl0pd** [comment]
Great thanks!
The problem was that I actually forgot to add generic parameter to AppBuilder. Not it's working :)
