### ISSUE TITLE
Setter is updating property when styles are being detached

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#3365]
## Repro

In `ControlCatalog`, `MainWindow.xaml`:

1. Remove `Icon="..."` (line 5).
2. Add the following markup at the start of the `Window` body:
```xaml
  <Window.Styles>
    <Style Selector="Window">
      <Setter Property="Icon" Value="/Assets/test_icon.ico" />
    </Style>
  </Window.Styles>
```

Then run.

Now, when closing control catalog, it will throw a `NullReferenceException` (which shows other possible issue: `Window.Icon` cannot be set to `null`).

The exception is thrown from a property changed handler, which I think is invoked when styles are being detached.

**Comment by grokys** [comment]
Removing the style when the window is closed is correct behavior I think. The problem is that `Window.Icon` cannot be set to `null`.
