### ISSUE TITLE
Avalonia 0.9.0 With Corert Takes so long To Compile

### ISSUE THREAD

**Issue by Shadow4walker** [AvaloniaUI/Avalonia#3366]
hello guys this is not really an issue but i wanted to post it in here to hear your thoughts.
I'm using Corert with 'Avalonia latest Released Build' and all were good till u guys Released the 0.9.0 V Now my app Takes so much Time To Compile 'I had to Give Up after more than 2 Hours' and this was an issue with every Nightly Build and Now I'm Facing it with he latest Released 0.9.0 the 0.8.3 and before was all good, so why and what's changed in this new Released is there anyway to Update 0.8.3 to the latest version with the same Results like Earlier Releases?

**Comment by kekekeks** [comment]
It's most likely a CoreRT issue. We haven't added anything that would prevent an AOT compiler from compiling the code. An issue in corert repo with a simple repro might be a better way to address this.

**Comment by Shadow4walker** [comment]
https://github.com/dotnet/corert/issues/7920

**Comment by Shadow4walker** [comment]
> It's most likely a CoreRT issue. We haven't added anything that would prevent an AOT compiler from compiling the code. An issue in corert repo with a simple repro might be a better way to address this.

Can You please Update System.Reactive to the Version 4.2.2 or 4.3.2 to Fix this issue
[https://github.com/dotnet/reactive/pull/1116](url)
[https://github.com/dotnet/corert/issues/7920](url)

**Comment by Shadow4walker** [comment]
Can You please Update System.Reactive to the Version 4.2.2 or 4.3.2 to Fix this issue
https://github.com/dotnet/reactive/pull/1116
https://github.com/dotnet/corert/issues/7920

**Comment by PJB3005** [comment]
I still seem to be running into this even with `System.Reactive` 4.3.2.

It's compiling methods like these and it's taking absolutely *forever*:

```
         Compiling [System.Reactive]System.Reactive.Concurrency.DefaultScheduler+LongRunning.ScheduleLongRunning<ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`2<__Canon,__Canon>>>>>>>>>>>>>>>>>>(ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`2<__Canon,__Canon>>>>>>>>>>>>>>>>>,Action`2<ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`2<__Canon,__Canon>>>>>>>>>>>>>>>>>,ICancelable>)...
```

**Comment by hez2010** [comment]
Finally I got the solution, though it's a bit complex.

It uses `RestorePackagesWithLockFile` to force project using a nightly build of System.Reactive, and disables `RootAllApplicationAssemblies` to avoid https://github.com/dotnet/corert/issues/3460.

Sample project:
[AvaloniaApp.zip](https://github.com/AvaloniaUI/Avalonia/files/4420834/AvaloniaApp.zip)

**Comment by phillvancejr** [comment]
Does anyone have an estimate on how long building a default template app with CoreRT shoudld take? I'm using 9.9 but still seem to be having problems building. I'm not getting past "Generative native code"

**Comment by Shadow4walker** [comment]
> Does anyone have an estimate on how long building a default template app with CoreRT shoudld take? I'm using 9.9 but still seem to be having problems building. I'm not getting past "Generative native code"

I'm using the same Version and it takes at maximum 5 Min just install System.Reactive Package the latest version to Your Project and it should Compile Successfully

**Comment by phillvancejr** [comment]
@Shadow4walker  it was definitely the System.Reactive reference, so now I can compile, but now I'm getting a linking error:
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libAvaloniaNative': The specified module could not be found
```

The libAvaloniaNative.dylib file is in the same directory as the executable any ideas?

**Comment by hez2010** [comment]
@phillvancejr Did you copy native dlls to the output directory?

**Comment by phillvancejr** [comment]
@hez2010 yes

**Comment by hez2010** [comment]
@phillvancejr I cannot repro your issue.
Here's an example project:
[AvaTest.zip](https://github.com/AvaloniaUI/Avalonia/files/4543242/AvaTest.zip)

**Comment by phillvancejr** [comment]
Thank you @hez2010 I'll check this out, thanks for taking the time to try to help!
