### ISSUE TITLE
Don't create DispatcherTimers for TextBox undo/redo

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#3370]
It seems that each `TextBox` instance creates an `UndoRedoHelper` which in turn creates a `DispatcherTimer`. This means that we're creating a `DispatcherTimer` for every instance of `TextBox`, and this timer doesn't seem to get removed either.

I don't think a timer should be required for undo/redo: when I've done this sort of thing before the way it usually works is: each text change pushes to the undo stack. If the change is made below a certain time threshold then the undo stack entry is merged with the previous stack entry.

**Comment by MarchingCube** [comment]
Noticed this as well when profiling and it accounts to majority of time spent when constructing new `TextBox` instances.
