### ISSUE TITLE
DataGrid: vertical scrollbar height is not calculated properly after changing window height

### ISSUE THREAD

**Issue by kaminova** [AvaloniaUI/Avalonia#3375]
I use Avalonia 0.9 stable version. If I scroll down and then increase the height of the window (e.g. maximize), the height of vertical scroll bar will be calculated wrong. Good way to reproduce that is to use the number of datagrid rows a bit more than you can see on your screen (on the screenshot there is only one invisble row on the top, but the height of the scrollbar is too small). 
 This leads to jittery scrolling in resized window. I suppose the problem is that the vertical offset (the height of invisble rows) is not updated after resizing the window.

![scroll](https://user-images.githubusercontent.com/45092470/71244599-2e846200-2313-11ea-892f-64a59773bcee.png)

**Comment by ilmian** [comment]
Issue still exists in version 0.10.10 and can be produced on both macOS and Windows.
