### ISSUE TITLE
Font fallback is not working for Bold fonts

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#3376]
if the font in the list of font names is not the first one, fontmanager fallbacks to default font.
example:
`<TextBlock Text="Should be bold (but it'snot)" FontFamily="NotValidFontName, Times New Roman" FontWeight="Bold"/>`
if we don't use `FontWeight="Bold"` fallback is wroking fine.
here font that is used for rendering is 'Segoe UI', but it's expected to be ` Times New Roman` on windows with Skia.
note: working fine with direct2d backend

**Comment by Gillibald** [comment]
Will investigate thanks

**Comment by donandren** [comment]
@Gillibald i've fixed it will provide pr so you can checkout
