### ISSUE TITLE
Default theme for Button in 0.9 is hard to perceive

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#3381]
Currently it's not obvious whether button is enabled or not. At least, for me:

![img](https://user-images.githubusercontent.com/16510738/71306567-a70a2200-23ea-11ea-972f-742b21d4b195.jpg)

Previously it was much clearly. Can it be adjusted a bit ?

Miss old theme :-)

**Comment by kekekeks** [comment]
https://github.com/wieslawsoltes/ThemeEditor
