### ISSUE TITLE
Exception when trying to open new window

### ISSUE THREAD

**Issue by georgiuk** [AvaloniaUI/Avalonia#3383]
Trying to open a new window when clicking a button and I get this exception
Avalonia.Markup.Xaml.XamlLoadException: 'No precompiled XAML found for EditUserWindow, make sure to specify x:Class and include your XAML file as AvaloniaResource'

version 0.9.1 on .Net 4.7.2

**Comment by Gillibald** [comment]
Please show us your window's XAML

**Comment by FoggyFinder** [comment]
Have you specified `x:Class`? Also make sure your `.xaml` files is `EmbeddedResource` or `AvaloniaResource`

Can you share the code?

**Comment by georgiuk** [comment]
Thank you for your quick answer. 
I had duplicated mainwindow to start build another window and wasn't EmbeddedResource. So this did the trick.
