### ISSUE TITLE
<Separator /> doesn't work in Menu

### ISSUE THREAD

**Issue by alexeybut** [AvaloniaUI/Avalonia#3384]
Version 0.9 from nuget.
Can't see separator in Menu using XAML
<MenuItem .. />
<Separator />
<MenuItem .. />
and in runtime 
itemsList.Add(new Separator())

**Comment by Gillibald** [comment]
Add a MenuItem with the magic string "-"

**Comment by alexeybut** [comment]
itemsList.Add(new MenuItem("-"))
or 
<MenuItem Header="Copy"/>
<MenuItem Header="-"/>
<MenuItem Header="Paste"/>

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/MenuItem.cs#L471

**Comment by HendrikMennen** [comment]
I had a similar problem with contextmenu too and solved it by adding the style for the separator manually like this:
```xaml
<Menu.Styles>
         <Style Selector="Separator">
                <Setter Property="Background" Value="{DynamicResource ThemeControlMidBrush}"/>
                <Setter Property="Margin" Value="29,1,0,1"/>
                <Setter Property="Height" Value="1"/>
         </Style>
</Menu.Styles>
```

After that you should be able to add a separator like this:  `itemsList.Add(new Separator());`

**Comment by alexeybut** [comment]
> I had a similar problem with contextmenu too and solved it by adding the style for the separator manually like this:
Thank you. It works.

**Comment by alexeybut** [comment]
I don't know is this a bug or feature, but the workaround with styles works good for me.

**Comment by 0x90d** [comment]
FYI: Only a vertical separator doesn't work. Horizontal separator works fine in menu 
![image](https://user-images.githubusercontent.com/46010672/133922248-c99a0aa4-d818-4977-b99a-72e7e4719cd1.png)
