### ISSUE TITLE
Arch Linux 2019.12.01 support

### ISSUE THREAD

**Issue by irategenius** [AvaloniaUI/Avalonia#3385]
Hello guys, I am trying to launch Avalonia 0.9.0 MVVM application on Arch Linux 2019.12.01 but it doesn't work. 
You can reproduce the issue by launching following commands:
```
dotnet new avalonia.mvvm -o App
cd App
dotnet run
```
The last command takes a lot time to complete but application is not launching and no debug information is written to the terminal output. 
```
dotnet --version
3.0.100-rc1-014190
```
If you need more information about my setup or log files, then just tell me what you need and I will post it to comments
Thank you

**Comment by jmacato** [comment]
Please use the 0.9.1 version that was just released, it fixes the issues on some linux distros that uses EGL.

**Comment by irategenius** [comment]
@jmacato Thank you for suggestion. Version 0.9.1 works
