### ISSUE TITLE
App not starting when published with PublishSingleFile

### ISSUE THREAD

**Issue by vijaysg** [AvaloniaUI/Avalonia#3392]
***** dotnet --info  *****
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db
******************************************

Avalonia and related packages version: 0.9.1

******************************************
Configured Serilog as follows:

```
SerilogLogger.Initialize(output: new LoggerConfiguration()
                .WriteTo.File("log.log", rollingInterval: RollingInterval.Day)
                .CreateLogger());
```
******************************************

Scenario 1: publish normally ` dotnet publish` : **Works!**
******************************************
Scenario 2: publish for runtime `dotnet publish -r win-x64 -c Release --self-contained -o bin/out/win10-x64` : **Works!**
******************************************
Scenario 3: publish single file `dotnet publish -r win-x64 -c Release --self-contained -o bin/out/win10-x64 /p:PublishSingleFile=true`: **Does not work!**
Error logged:
`[WRN] Error in binding to Avalonia.Input.KeyBinding.Command: Null value in expression ''.
`
But I believe this log is related to a ViewModel command bind, and not related to the app start issue.
******************************************
Interesting fact, if I don't clear the output generated in `Scenario 2` and just use `PublishSingleFile` option I am able to get the application to start.

**Comment by kekekeks** [comment]
Note that `PublishSingleFile` essentially makes your app to be an SFX archive that extracts everything to %TEMP% and runs from there. So there might be some issues with resolving paths.

**Comment by vijaysg** [comment]
True, but if we leave the support files generated in scenario 2 at the same output folder as the final exe (generated with `PublishSingleFile`) and execute it works. So I am not sure how it is figuring the link from the extracted `%TEMP%` folder to the additional files at the original single files output folder.

**Comment by vijaysg** [comment]
Ok, I did further investigation with help of Sysinternals `procmon`.  You are right, when executing the final `exe` file the contents are executed from a temp folder (`%TEMP%\\.net\AltusAdmin\3lyky0dc.jy1\`). And the final library it loads is `System.Collections.Immutable.dll` which is a success. The trail runs cold after that. 

There are few `NAME NOT FOUND` results, I am not sure if they are relevant as the source of them seems to be from windows registry. Attaching the full log (related to my executable) for your reference, the file is zipped PML format which can be opened using SysInternals procmon.
[Logfile-20191229.zip](https://github.com/AvaloniaUI/Avalonia/files/4007887/Logfile-20191229.zip)

**Comment by vijaysg** [comment]
Ok, issue solved. The culprit was appsettings.json

Even though the file was available in the extracted `TEMP` folder, the executable was looking for it in the original `exe` files location. Keeping an extra copy of the file in the same folder as the exe file solved the issue.
