### ISSUE TITLE
ScrollBar paging not working in Avalonia 0.9.1

### ISSUE THREAD

**Issue by garyhertel** [AvaloniaUI/Avalonia#3399]
Starting with Avalonia 0.9, trying to page using the scrollbar doesn't seem to work as well unless you've manually set the LargeChange property (and only the DataGrid horizontal scrollbar does this by default). In 0.9, when paging, the scrollbar will only scroll by 10 pixels by default, whereas it used to page by the viewport size in 0.8. You can see this problem with the primary ScrollBar in the Control Catalog. This behavior looks like it might have changed with this commit:

https://github.com/AvaloniaUI/Avalonia/commit/d398d418215a96b3353912c07776095a22bcb14f#diff-7a282687ba30b84d4266419956311a8b

**Comment by maxkatz6** [comment]
Was fixed
