### ISSUE TITLE
TextBlock not updating when text changed, but font-metrics stays the same.

### ISSUE THREAD

**Issue by Wyvernius** [AvaloniaUI/Avalonia#3401]
Code says more then 1000 words:
TextBlock will only be updated on 0 -> 1 | 9 -> 10 | 99 -> 100 | etc.

MainWindow.xaml
` <DockPanel>
    <TextBlock DockPanel.Dock="Left" Height="100" TextAlignment="Center" Margin="20,75,20,0" Text="{Binding SlideStatus}"></TextBlock>
    <Button Command="{Binding Click}"></Button>
  </DockPanel>`

MainWindowViewModel.cs
 
```
string greet;
public string SlideStatus
{
       get { return greet; }
        set { this.RaiseAndSetIfChanged(ref greet, value); }
}

int i = 0;
public void Click()
{
      SlideStatus = "Slide: " + i++.ToString() + "out of 999";
}
```

TextBlock will update if you resize the window, or the total length of the string changes.
This is on Version 9.1

**Comment by Wyvernius** [comment]
Further investigation led me to the conclusion that not assigning a fixed width/height fixes the issue.
But i don't think this is a type of behavior we should expect from it.

**Comment by Gillibald** [comment]
Can't be reproduced anymore
