### ISSUE TITLE
Template created with - in name causes designer to fail.

### ISSUE THREAD

**Issue by ThadHouse** [AvaloniaUI/Avalonia#3412]
If a project name with a `-` is created, the MVVM template replaces any `-` with `_` in the view model namespace in the xml file, including the one for the assembly name. However, Visual Studio still creating the assembly with `-` rather then `_`, causing the designer to not be able to find the assembly.

**Comment by MikeCodesDotNET** [comment]
This is the same for Rider and expected behaviour. You should avoid using dashes in project names. 

https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-assemblies-and-dlls
