### ISSUE TITLE
[Question] Implementing a virtual keyboard

### ISSUE THREAD

**Issue by Int32Overflow** [AvaloniaUI/Avalonia#3415]
I would like to develop a virtual keyboard in Avalonia for touchscreen application.
Can you give me a tip on how I could best implement this?

I tried:
```
        private void SetKey(Key key)
        {
            var keyboard = KeyboardDevice.Instance;
            var inputManager = InputManager.Instance;

            inputManager.ProcessInput(new RawKeyEventArgs(keyboard, (ulong)DateTime.Now.Ticks, null, RawKeyEventType.KeyDown, key, RawInputModifiers.None));
            inputManager.ProcessInput(new RawKeyEventArgs(keyboard, (ulong)DateTime.Now.Ticks, null, RawKeyEventType.KeyUp, key, RawInputModifiers.None));
        }
```

But it is not working :( (TextBox is focused)

**Comment by kekekeks** [comment]
Text input has a separate `RawTextInputEventArgs` event.

**Comment by Int32Overflow** [comment]
> Text input has a separate `RawTextInputEventArgs` event.
Thank you for the repsonse. This solution works for text. But how can I emulate a tab or arrows?

**Comment by kekekeks** [comment]
You are missing input root argument in your `RawKeyEventArgs` constructor invocation.

**Comment by Int32Overflow** [comment]
> You are missing input root argument in your `RawKeyEventArgs` constructor invocation.

Still not work! What's wrong?
![grafik](https://user-images.githubusercontent.com/20139038/72056962-e501b400-32cd-11ea-900b-5f1a6e0acb01.png)

**Comment by Int32Overflow** [comment]
Problem solved :-)

You have to use `RawTextInputEventArgs `for text input and `RawKeyEventArgs `for the other keys.

**Comment by kekekeks** [comment]
You actually need both and proper Ctrl/Alt handling on the virtual keyboard side to make hotkeys work.

**Comment by chrisdilbert** [comment]
@Int32Overflow Can you share the virtual keyboard please!

**Comment by Int32Overflow** [comment]
@chrisdilbert 
Unfortunately, I never had time to develop the virtual keyboard. That means, unfortunately, no code exists.
Shall we work together on an implementation?

**Comment by kekekeks** [comment]
FYI: I'm currently working on IME support which would make virtual keyboard less painful. I. e. you will automatically get focus events, cursor rectangle and access to surrounding text. It will also provide you with input type hints (i. e. number only, email, url, etc).

```cs
    public interface ITextInputMethodImpl
    {
        void SetActive(bool active);
        void SetCursorRect(Rect rect);
        void SetOptions(TextInputOptionsQueryEventArgs options);
        void Reset();
    }

    public class TextInputOptionsQueryEventArgs : RoutedEventArgs
    {
        /// <summary>
        /// The content type (mostly for determining the shape of the virtual keyboard)
        /// </summary>
        public TextInputContentType ContentType { get; set; }
        /// <summary>
        /// Text is multiline
        /// </summary>
        public bool Multiline { get; set; }
        /// <summary>
        /// Text is in lower case
        /// </summary>
        public bool Lowercase { get; set; }
        /// <summary>
        /// Text is in upper case
        /// </summary>
        public bool Uppercase { get; set; }
        /// <summary>
        /// Automatically capita thatlize letters at the start of the sentence
        /// </summary>
        public bool AutoCapitalization { get; set; }
        /// <summary>
        /// Text contains sensitive data like card numbers and should not be stored  
        /// </summary>
        public bool IsSensitive { get; set; }
    }
```

ITextMethodImpl is picked during visual tree traversal when focused element gets changed.

**Comment by ZdravkoHvarlingov** [comment]
Are there any advances on this topic for a virtual keyboard?

**Comment by dlukach** [comment]
Any updates on this?

**Comment by maxkatz6** [comment]
@dlukach in what updates are you interested? As I see, ITextInputMethodImpl is already there, so you implement this interface and register it in AvaloniaLocator.CurrentMutable.
And also InputManager.Instance should just work as it was discussed before.
I don't think there will be any advanced topics about virtual keyboard since it seems to be very specific task.

**Comment by dlukach** [comment]
Yeah I was looking for example code on the IME support like the person above but figured out how to make a virtual keyboard.  I ended up using the code above and making it work. 

The only thing I would like to know now is how to subscribe all textboxes in my project with the same click event to pull the keyboard. I was able to call it in my numeric textbox onclick method since that is a custom control built off a textbox, for the regular textbox I rather not make a new class nor subscribe to click events all over my app.

 If anyone stumbles across this, here is the code for my numeric keypad's buttonclick event.  In my project, when a control is touched using a touchscreen instead of a mouse, the keyboard window will be shown.


```cs
private void ButtonClick(object? sender, RoutedEventArgs e)
{
    if (_textControl == null)
        return;
    Button button = sender as Button;
    Key key;
    bool sendText = false;
    switch ( button.CommandParameter.ToString())
    {
        case "BACK":
            key = Key.Back;
            break;
        case "ENTER":
            key= Key.Enter;
            break;
        default:
            sendText = true;
            key = Key.None;
                break;
            
    }
    
    var inputManager = InputManager.Instance;
    _textControl.Focus();
    if (sendText)
    {
        string text = button.CommandParameter.ToString();
        inputManager.ProcessInput(new RawTextInputEventArgs(KeyboardDevice.Instance, (ulong)DateTime.Now.Ticks, (Window)_textControl.GetVisualRoot(), text ));
    }
    else
    {
        inputManager.ProcessInput(new RawKeyEventArgs(KeyboardDevice.Instance, (ulong)DateTime.Now.Ticks, (Window)_textControl.GetVisualRoot(), RawKeyEventType.KeyDown, key, RawInputModifiers.None ));
        inputManager.ProcessInput(new RawKeyEventArgs(KeyboardDevice.Instance, (ulong)DateTime.Now.Ticks, (Window)_textControl.GetVisualRoot(), RawKeyEventType.KeyUp, key, RawInputModifiers.None ));
    }
   if(key == Key.Enter)
       Hide();
}
```

**Comment by maxkatz6** [comment]
> The only thing I would like to know now is how to subscribe all textboxes in my project with the same click event to pull the keyboard.

Have you tried to implement and register ITextInputMethodImpl? It should have all possibly required methods for you that you can listen:
```
    public interface ITextInputMethodImpl
    {
        void SetActive(bool active);
        void SetCursorRect(Rect rect);
        void SetOptions(TextInputOptionsQueryEventArgs options);
        void Reset();
    }
```

It does not provides reference to specific text box, but do you need it? Focus is set by avalonia when user click on text box.

**Comment by dlukach** [comment]
I have not tried to implement that yet. While focus is set by avalonia, when you click on the virtual keyboard the focus shifts to the keyboard. Would this cause a problem? In my code you see I set focus back to the control. Additionally I still need the calling control so I can position my virtual keyboard relative to the control and I need to only trigger the specific keyboard on touch events on specific controls. I have a numeric and alphanumeric, depending on the box it'll go to whats necessary. In forms, I would just handle this in the click event, I feel like in wpf/avalonia/mvvm there is a more clever way to do this. I know in WPF you can set in a style a event but avalonia doesn't have support for that...

**Comment by maxkatz6** [comment]
> While focus is set by avalonia, when you click on the virtual keyboard the focus shifts to the keyboard. Would this cause a problem?

Oh, I see. It can cause a problem. If you don't need keyboard navigation, you set focusable to false on these buttons. Or handle GotFocus event globally and keep reference to previously focused control. If you need keyboard navigation, I don't have any ideas right now.

> Additionally I still need the calling control so I can position my virtual keyboard relative to the control

I believe "SetCursorRect(Rect rect);" should provide information for positioning, cc @kekekeks 

> I have a numeric and alphanumeric, depending on the box it'll go to whats necessary

Use "SetOptions(TextInputOptionsQueryEventArgs options)". To set specific options you need to handle TextInputOptionsQuery event on text box, see sample: https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/TextBoxPage.xaml.cs#L20

**Comment by violetdefense** [comment]
How can I use ?
private void SetKey(Key key, string v)
        {
            var keyboard = KeyboardDevice.Instance;
            var inputManager = InputManager.Instance;

            inputManager.ProcessInput(new RawTextInputEventArgs(keyboard, (ulong)DateTime.Now.Ticks, null, v));
			inputManager.ProcessInput(new RawKeyEventArgs(keyboard, (ulong)DateTime.Now.Ticks, null, RawKeyEventType.KeyDown, key, RawInputModifiers.None));

		}
