### ISSUE TITLE
DockPanel click anywhere not working correctly

### ISSUE THREAD

**Issue by burtybob** [AvaloniaUI/Avalonia#3416]
Good Day,

I've created a user control with a dockpanel, an image and a TextBlock and added commands and overrode the "OnPointerPressed" method.
However, it seems that the dock panel when clicked doesn't trigger the OnPointerPressed until after I've clicked on either the textblock or image. After clicking either of these clicking anywhere on the dock panel does then result in the OnPointerPressed being triggered.

I'm not sure if this is a bug or by design, or potentially I'm trying to do something that is covered by a suitable built in control.
What I'm looking at using this particular UC for is as a "button" with an image and text.

Many Thanks,
Ben

**Comment by grokys** [comment]
Hi @burtybob,

This is by design, and is the same in WPF/UWP etc. You can make the `DockPanel` receive pointer events by setting `Background="Transparent"`. Here's a StackOverflow answer for WPF that covers it:

https://stackoverflow.com/a/22781094/6448

**Comment by burtybob** [comment]
Thank you, I can't believe it was that simple!
I'll remember to use Wpf as well as Avalonia in my search terms going forwards :)
