### ISSUE TITLE
[RaspberryPi] Memory access error when using DRM instead of Framebuffer

### ISSUE THREAD

**Issue by Int32Overflow** [AvaloniaUI/Avalonia#3417]
Running this Demo application "ControlCatalog.NetCore" on raspberry pi with 7" Touchscreen.

When trying to start the project with the parameter "--drm", a memory access error occurs. Is this error known?

**Comment by kekekeks** [comment]
Most likely some error in P/Invoke import declaration. 
I've only tested DRM backend on my laptop and in QEMU with virgl, both using are 64 bit Intel CPU

**Comment by Int32Overflow** [comment]
You know the quickest way to find out which P/Invoke is faulty?

**Comment by kekekeks** [comment]
Step-by-step debugging, I guess

**Comment by MikeCodesDotNET** [comment]
I've recently demoed using DRM, and it worked well. Closing for now.
