### ISSUE TITLE
Where is Application.Current.MainWindow ?

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#3418]
I'm upgrading from 8.0 to 9.0 and MainWindow property from Application.Current no longer exist. Why has it been removed and what's the replacement? For me it was an easy way to show dialogs on my viewmodel:

```
var result = await new OpenFolderDialog().ShowAsync(Application.Current.MainWindow);
```

**Comment by MonkAlex** [comment]
https://github.com/AvaloniaUI/Avalonia/wiki/Application-lifetimes

**Comment by Symbai** [comment]
Thank you!

**Comment by SpyceTewan** [comment]
How do you now access the mainwindow? Please update these docs https://avaloniaui.net/docs/controls/window#show-a-window-as-a-dialog

**Comment by aspenluxxxy** [comment]
> 
> 
> [AvaloniaUI/Avalonia/wiki/Application-lifetimes](https://github.com/AvaloniaUI/Avalonia/wiki/Application-lifetimes)

this does not help

**Comment by danwalmsley** [comment]
PRs welcome!

**Comment by atresnjo** [comment]
> 
> 
> How do you now access the mainwindow? Please update these docs https://avaloniaui.net/docs/controls/window#show-a-window-as-a-dialog

For anyone else that stumbles upon the issue:

      
```
var starTaskWindow = new StartTaskWindow();
if (Avalonia.Application.Current.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
{
   starTaskWindow.ShowDialog(desktop.MainWindow);
}

```

**Comment by timunie** [comment]
@ahmad2smile in general PRs for the docs are welcome. But atm we are working on docs for v11.0. I'll add this to the list of things to review.

**Comment by GorgonUK** [comment]
Yeah, it's very simple, you just Push `IClassicDesktopStyleApplicationLifetime appLifetime` into your functions from `using Avalonia.Controls.ApplicationLifetimes;`.

`appLifetime.MainWindow` gives you the active window and it may be null
