### ISSUE TITLE
Publish myGet failed since mid December 2019

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#3420]
https://dev.azure.com/AvaloniaUI/AvaloniaUI/_release?_a=releases&view=mine&definitionId=2

If an author may take a look that would be amazing.

**Comment by mhmoudr** [comment]
this is the error: 2019-12-17T21:41:16.8377470Z ##[error]The nuget command failed with exit code(1) and error(System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 413 (**The package size for file 'package.nupkg' is too large. The feed owner may have to upgrade the MyGet subscription to resolve this issue.**).

**Comment by kekekeks** [comment]
Changed retention rules to keep only 50 most recent builds. Hopefully that will be enough for now.

**Comment by Symbai** [comment]
Thanks for taking a look at it so quickly
