### ISSUE TITLE
Zscaler detecting the NuGet package as malicious 

### ISSUE THREAD

**Issue by mhmoudr** [AvaloniaUI/Avalonia#3421]
On scanning the NuGet download URL using zscaler online tools it recognises the package as malicious be detecting the following bad hash "60901c4b1a46cfdc364071e3071e634f"

Full Report can be found in: https://zulu.zscaler.com/report/38c39e95-fc53-47aa-9258-8aa001e56ba9

Scanned URL (After redirect): https://globalcdn.nuget.org/packages/avalonia.0.9.1.nupkg

**Comment by kekekeks** [comment]
It's probably a wrong place to report bugs and false positives in AV software.

**Comment by mhmoudr** [comment]
Excuse me being new to this repo, but when I reported this, I was suspeciuse of some manual packaging were a malware can sneak into the final pack, but after seeing the CI/CD pipeline in azure devops I would say it is unlikely to be the case, and it is more of a false positive.
I will try to follow up with zscaler to clarify, mean while this will be a blocker for anyone using zscaler firewalls

**Comment by mhmoudr** [comment]
after communicating the issue with Zscaler they confirmed that is was false alarm, and whitelisted the package in their engine, as a result anyone using zscaler as a gateway or firewall can download the packages.

for details check the following reply: 
-----------------------------------
zscaler.zendesk.com/hc/requests/997283

Anupam Dua (Zscaler Support)

Jan 10, 1:33 PM IST

Hi Team,

The security team reviewed the URL and found that the URL is clean. This is the Avalonia Package from Nuget.
NuGet is the package manager for .NET. Avalonia is a WPF/UWP-inspired cross-platform XAML-based UI framework providing a flexible styling system

Please get back to us in case you have any queries or questions around this.
Anupam Dua
Zscaler Inc.
