### ISSUE TITLE
Scrolling in ListBox with touch gestures is not working correctly

### ISSUE THREAD

**Issue by dmrayt** [AvaloniaUI/Avalonia#3429]
While scrolling with touch gestures in a ListBox, the touched item doesn't follow the finger as it should. 
This make it very hard to scroll with gestures.

**Comment by kekekeks** [comment]
ListBox currently is incapable of smooth scrolling when virtualization is enabled, it can only scroll items one-by-one and reacts to mouse wheel 'steps'.
For now our `ScrollContentPresenter` attempts to [accumulate the scroll delta](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs#L246) and ]somehow translate it](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs#L255) into mouse wheel scroll steps.

Obviously that's an inprefect solution. There is currently [work in progress](https://github.com/AvaloniaUI/Avalonia/pull/3388) to make our containers to use `ItemsPresenter` which will enable smooth scrolling for virtualized listboxes, we expect it to be available in the next release.

**Comment by dmrayt** [comment]
The problem is the fixed value for `ScrollContentPresenter.LogicalScrollItemSize`. This should be the size of the item as noted in the source code comment, or at least it should be configurable.
I've tested it with a value of 13 and it's (in my case) much better.

I will wait for the `ItemsPresenter`.

**Comment by robloo** [comment]
Somewhat related, not sure if I should open a new issue: Using the mouse Scroll Wheel over the expanded-state ScrollBar doesn't scroll the ListBox. Using the Scroll Wheel on the ListBox itself works just fine.

**Comment by maxkatz6** [comment]
@robloo it's better to create another issue. As I understand, scrollbar handles wheel event instead of listbox under it.
