### ISSUE TITLE
Relax conditions for converters

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#3433]
MCVE

```cs
    public class M2Conv : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value is int v) return v * 2;
            return value;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
```

And usage:

```cs
public int IntValue { get; } = 42;
```

```xml
<TextBlock Background="Yellow" Text="{Binding IntValue, Converter={StaticResource m2}}}" />
```

In Avalonia this will not work due to [`ImplicitConversions`](https://github.com/AvaloniaUI/Avalonia/blob/b9118085e2f4bf254abbe9f27861add6a0dd519c/src/Avalonia.Base/Utilities/TypeUtilities.cs#L35-L52)  restrictions in [`TryConvertImplicit`](https://github.com/AvaloniaUI/Avalonia/blob/b9118085e2f4bf254abbe9f27861add6a0dd519c/src/Avalonia.Base/Utilities/TypeUtilities.cs#L211).

In WPF the same converter works just fine.

Additional thoughts: if I have `int` property that bound to Text and it works I would expect that if my converter returns int it will work as well.

**Comment by grokys** [comment]
Hmm, unsure about this one. Avalonia is asking you to convert `object value` to `targetType` and you're instead converting the value to a different type.

I need to look into how/why WPF handles this, but my initial thought is that your converter is broken.

**Comment by FoggyFinder** [comment]
Any decision? :-)

**Comment by grokys** [comment]
Sorry, I've not had chance to look into it. Any idea where in the WPF codebase it handles `IValueConverter` returning a type other than the type it was asked for?

**Comment by FoggyFinder** [comment]
no, sadly

**Comment by grokys** [comment]
Just to check: what is `targetType` when your converter is called?

**Comment by FoggyFinder** [comment]
`String`

**Comment by grokys** [comment]
Yeah, so I really think this is a bug in your code. I know that WPF handles it fine, but afaik there's nothing to my knowledge that _says_ that WPF should accept this, I expect it's a case of it working by accident.

**Comment by FoggyFinder** [comment]
But can it at least gave a warning or something? Because currently it just does nothing so TextBlock is empty.

**Comment by FoggyFinder** [comment]
Anyway warning is a different Q. Closing the issue since this is not a bug.

**Comment by grokys** [comment]
Hmm yeah it should be outputting an error to the log. If that's not happening then that is a bug I think.

**Comment by FoggyFinder** [comment]
There is a error/warning message on master. So I will wait until next release is out and then re-check again.
