### ISSUE TITLE
Using Avalonia in a Service

### ISSUE THREAD

**Issue by furesoft** [AvaloniaUI/Avalonia#3434]
i want to use avalonia in a service. showing a window works fine, but when i close the window it throws an exception "setup was already called", when i transfer the code in to a custom class it throws an exception: "invalid thread"

my code: https://github.com/furesoft/ExPay/blob/develop/Source/ExPay%20Service/Utils.cs

**Comment by MonkAlex** [comment]
> "setup was already called"

Call it (`BuildAvaloniaApp` and `SetupWithoutStarting`) once (on first show).

**Comment by furesoft** [comment]
i did, ill get this exception: "Call from invalid thread"

**Comment by kekekeks** [comment]
You can only use Avalonia from one thread. Create a separate one and run the GUI there. Then use `Dispatcher.UIThread.InvokeAsync` to send delegates to be invoked on that thread.

**Comment by furesoft** [comment]
i have written a little window manager, that creates a thread with the gui, but now nothing works

**Comment by Gillibald** [comment]
What prevents you from reusing a single application instance? That way you run the setup once. That allows you to show new windows on demand without having the overhead of initializing the platform every time you try to show a window.

Also make sure to set the ShutdownMode if you are using a desktop lifetime.
