### ISSUE TITLE
Inconsistent argument ordering in SelectionChangedEventArgs and ItemsRepeaterElementIndexChangedEventArgs 

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#3437]
The PVS studio analysis at https://www.viva64.com/en/b/0701/ uncovered a couple of bugs related to argument ordering with `SelectionChangedEventArgs` and `ItemsRepeaterElementIndexChangedEventArgs`.

In short: we swap the order of arguments in the constructors of these classes, but some code that has been ported from WPF and WinUI still uses the WPF/UWP ordering.

We should revert the constructors to use the WPF/UWP ordering.

**Comment by MuleaneEve** [comment]
Hi,

I don't know if I should create a new issue, but [the fix](https://github.com/AvaloniaUI/Avalonia/pull/3526) should also be applied to the internal Update() method:

https://github.com/AvaloniaUI/Avalonia/blob/ed373aaaa384952e80f4d839da24cd6c9a2e3e25/src/Avalonia.Controls/Repeater/ItemsRepeaterElementIndexChangedEventArgs.cs#L37

You can see it being used here:

https://github.com/AvaloniaUI/Avalonia/blob/ed373aaaa384952e80f4d839da24cd6c9a2e3e25/src/Avalonia.Controls/Repeater/ItemsRepeater.cs#L560

The oldIndex is sent first.
