### ISSUE TITLE
Example Of Appbuilder.SetupWithoutStarting()

### ISSUE THREAD

**Issue by MaynardMiner** [AvaloniaUI/Avalonia#3439]
https://github.com/AvaloniaUI/Avalonia/wiki/Application-lifetimes

Do you think you can provide an example of how to use Appbuilder.SetupWithoutStarting() method to bootstrap Avalonia? I would like to load it, then use the API to add the App class, and then use App.run() to start it.

https://github.com/MaynardMiner/psavalonia/blob/master/src/AvaloniaBootrapper.cs

Is a simple example of what I am referring to. I'm not sure with the wiki instructions how this would be achieved.

**Comment by Gillibald** [comment]
Have a look at this: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/AppBuilderBase.cs#L117

You need to call `SetupWithLifetime` before this works properly. After this, you should be able to start your App manually. Make sure to call app.Run from the right Thread

**Comment by MaynardMiner** [comment]
So are you stating to ditch SetupWithoutStarting() , and use start<mymainwindow>() instead?

Or are you stating the code would work fine as is but I need to add SetupWithLifetime()?

I've realized I had to change:

```
AppBuilder.Configure(App).UseReactiveUI().UsePlatformDetect().SetupWithoutStarting()
```

to

```
AppBuilder.Configure<App>().UseReactiveUI().UsePlatformDetect().SetupWithoutStarting()
```

For it to work.
Does that mean that it creates an instance of App? So I don't need to use:

```
App = new App();
```

I apologize for the many questions. I am really great with powershell, but not-so-great with C#. That's why I'm trying to make the latest version work for powershell like I did before.

**Comment by MaynardMiner** [comment]
I solved it, after looking at other apps that used Avalonia and reading codebase.

In case anyone searches when they go to update, the direct solution was to use ``SetupWithLifetime`` rather than ``SetupWithoutStarting``. The original link to my repository shows what I did. I seem to have no issues, everything worked as usual after making change, though my app isn't large.
