### ISSUE TITLE
[IDEA] Add a syntax for SharedSizeGroup label on Col/RowDefinition strings

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#3440]
Perhaps something like `<Grid ColumnDefinitions="1*,2*,(SharedSizeGroupLabel)" ...`; Just want to bring this up if there's any interest on this.

**Comment by grokys** [comment]
Not sure, the point of the row/column definition strings to me is that they're a shorthand for the common case. Do we really want to make it a complicated DSL? To me I'd prefer saying "if you want anything fancy use the WPF syntax".

**Comment by jmacato** [comment]
I agree, I may have approached this idea in the wrong direction
