### ISSUE TITLE
[Question] horizontal Listbox or Stackpanel with ItemSource

### ISSUE THREAD

**Issue by Wyvernius** [AvaloniaUI/Avalonia#3442]
Hi, Im trying to layout items horizontal.
I know i can do this from code behind, but is there also a way to do this in xaml?

example:
```
<StackPanel ItemSource="{Binding ....}" Orientation="horizontal">
<Template .... />
</StackPanel>
```

**Comment by Wyvernius** [comment]
Hi @danwalmsley , thanks for the quick reply.

**Comment by ichbinvinh** [comment]
with Listbox there is a hidden VirtualizingStackPanel inside of ItemsPresenter. So you must set Orientation of VirtualizingStackPanel to Horizontal and VirtualizationMode of ItemsPresenter ="None"

<Style Selector="ListBox /template/ VirtualizingStackPanel">
        <Setter Property="Orientation" Value="Horizontal" />
</Style>

**Comment by marknefedov** [comment]
> @Wyvernius this is very easy.
> 
> ```
> <ItemsControl ItemsSource="{Binding ....}">
>     <ItemsControl.ItemsPanel>
>         <ItemsPanelTemplate>
>              <StackPanel Orientation="Horizontal" />
>         </ItemsPanelTemplate>
>      </ItemsControl.ItemsPanel>
> </ItemsControl>
> ```
> 
> ItemsControl can also be replaced with Listbox, etc and StackPanel can be replaced with any Panel, like WrapPanel for instance.
> 
> This is one of my favourite features of Avalonia / WPF, I love it when someone asks this :D

Is this still thing in 11.0?

**Comment by timunie** [comment]
@marknefedov yeah you can still do it in 11.0
