### ISSUE TITLE
Unable to resolve type DataGrid from namespace:

### ISSUE THREAD

**Issue by Wyvernius** [AvaloniaUI/Avalonia#3446]
I've installed the DataGrid package from nuget,
And in the xaml is show all options for datagrid.
Yet:
```
        <DataGrid Items="{Binding SessionList}" Grid.Row="1">
          <DataGrid.Columns>
            <DataGridTextColumn  Header="Title" Binding="{Binding Title}"/>
            <DataGridTextColumn  Header="Description" Binding="{Binding Description}"/>
          </DataGrid.Columns>
        </DataGrid>
```
Throws an error.

**Comment by Gillibald** [comment]
And the error is?

**Comment by Wyvernius** [comment]
Unable to resolve type DataGrid from namespace "https://github.com/avaloniaui"

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/2426

**Comment by Deadpikle** [comment]
@Wyvernius I was having the same problem, and my DataGrid wasn't showing up at all, until I followed the steps [here](https://www.nequalsonelifestyle.com/2019/06/13/avalonia-datagrid-getting-started/). Make sure your NuGet package is up to date (0.9.2 as of this comment).

**Comment by Wyvernius** [comment]
Got it all working, but thanks for the link!

**Comment by antony-scott** [comment]
I had the same issue, it was the missing line in app.xaml for the StyleInclude that fixed it for me

`<StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Default.xaml"/>`

Thanks

**Comment by chylex** [comment]
I was getting the same error, but only in Release configuration; turns out `Avalonia.Diagnostics` has a dependency on `Avalonia.Controls.DataGrid`, so it was installed in Debug implicitly and then disappeared in Release which confused me.

**Comment by maxkatz6** [comment]
Initial issue was about missing style, but in both cases it's expected. Package and style needs to be included in order to use control.
