### ISSUE TITLE
macOS renders fully black windows

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#3449]
macOS High Sierra 10.13.6

Any newly opened window appears fully black.

![Screen Shot 2020-01-18 at 17 09 41](https://user-images.githubusercontent.com/13300194/72666733-5bf92400-3a15-11ea-879b-1f61f11add1c.png)

Usually comes back to life after mouseover, move, resize etc.
![Screen Shot 2020-01-18 at 17 10 21](https://user-images.githubusercontent.com/13300194/72666742-6f0bf400-3a15-11ea-8461-d5ff12455662.png)

When resizing, it flickers between black and working.

cibuild5570

Couldn't find any lower cibuilds and azure seems to be glitching so I can't check which builds exist? I tried stable 0.9.1 from NuGet, works fine there

**Comment by mat1jaczyyy** [comment]
![Screen Shot 2020-01-18 at 17 30 20](https://user-images.githubusercontent.com/13300194/72667075-3faab680-3a18-11ea-83b6-9b83d92cec42.png)
Happens to ToolTips as well

**Comment by kekekeks** [comment]
Are you running on actual hardware or in VM? We don't support running on OSX virtual machines.

**Comment by mat1jaczyyy** [comment]
@kekekeks This is actual hardware, Ryzen 7 2700 Hackintosh with RX 570. I normally do all of my development on Windows, but a large part of my userbase uses macOS so I've had different hackintoshes set up for years to support development. This is a recently introduced regression, haven't had anything like this in a little under a year of using Avalonia

**Comment by kekekeks** [comment]
@danwalmsley

**Comment by danwalmsley** [comment]
@kekekeks ill have to test and work out which PR introduced this.

**Comment by ahopper** [comment]
I'm also seeing this on High Sierra 10.13.6 on a late 2008 mac book pro. Tool tips are frequently but not always black. cibuild0005727-beta

**Comment by kekekeks** [comment]
Try a more recent build. 0.9.3 and nighty 5845+ have a huge OSX rendering rework

**Comment by ahopper** [comment]
cibuild0005911-beta works here thanks 👍

**Comment by mat1jaczyyy** [comment]
I'll try this today

**Comment by mat1jaczyyy** [comment]
Doesn't render flicker black anymore, but I get another crash. Will open a new issue.
