### ISSUE TITLE
WindowStartupLocation is ignored on Linux

### ISSUE THREAD

**Issue by dmrayt** [AvaloniaUI/Avalonia#3454]
Setting `WindowStartupLocation` to `CenterScreen` or `CenterOwner` has no effect on Linux.

**Comment by Symbai** [comment]
Is it not ignored but the child window returns a wrong width/height when the code to set the position runs. It also reports incorrect height/width on Opened event. You can see this yourself:

### XAML
`Width="200"`
### In Code
`this.Opened += (s,e) => { Console.WriteLine(this.Width.ToString());`

It reports in my case a width of 1200. If you a place a button on your children and re-run the WindowStartupLocation code it gets properly set in the middle of the owner window.

I expect that the draw engine on Linux still renders while on Windows it completes before window position is set.

**Comment by maxkatz6** [comment]
Duplicates of https://github.com/AvaloniaUI/Avalonia/issues/3454 https://github.com/AvaloniaUI/Avalonia/issues/6159
I will keep one issue with more details
