### ISSUE TITLE
Does AvaloniaUI work with 3rd party WPF control libraries such as DevExpress?

### ISSUE THREAD

**Issue by SCLD-JBuczkowski** [AvaloniaUI/Avalonia#3458]
Hi:

This is more of a general question than an issue, but I couldn't find an appropriate forum.

We have an existing WPF .NetCore application which heavily utilizes the DevExpress WPF control libraries.

We are very interested AvaloniaUI and it's capabilities.

Does AvaloniaUI work wth 3rd party WPF control libraries such as DevExpress?

Thanks,
JohnB

**Comment by Xarlot** [comment]
No, it`s not. 
DevExpress WPF components heavily rely on WPF, WinForms, and WinApi. 
You can host simple WPF controls inside Avalonia on Windows. However, there is no way to make it work on Linux or Mac. MS is not interested in cross-platform WPF. https://github.com/dotnet/wpf/issues/48 for example. Moreover, any PR that make it more cross-platform will be rejected.

While Avalonia is XAML based framework, it is a completely different framework. WPF controls cant be ported to Avalonia, they must be rewritten from the scratch. Honestly speaking, because of the cross-platform nature of Avalonia and huge differences between WPF and Avalonia styling and functionality, it is simpler to port control to WinForms than to Avalonia.

**Comment by kekekeks** [comment]
>it is simpler to port control to WinForms than to Avalonia.

This is basically not true. Several controls in our code base were ported from WPF/Silverlight using copy/paste + find/replace technique.

**Comment by jinyuttt** [comment]
Does Avalonia plan to borrow some of the controls from devexpress? Some controls of devexpress are well implemented.

**Comment by kvalitetskontrollMarkaryd** [comment]
What are the chances that DevExpress will make controls for Avalonia? 
Especially an advanced DataGrid would be nice.

**Comment by danwalmsley** [comment]
> What are the chances that DevExpress will make controls for Avalonia?
> Especially an advanced DataGrid would be nice.

@kvalitetskontrollMarkaryd 

Avalonia is working on premium controls library that provides that kind of functionality. contact team@avaloniaui.net for more information.

Other than that we would certainly be open to working with companies like DevExpress to help them port their libraries, there is certainly a lot of demand....

please reach out to them and let them know your interest.

**Comment by kvalitetskontrollMarkaryd** [comment]
> Avalonia is working on premium controls library that provides that kind of functionality. contact [team@avaloniaui.net](mailto:team@avaloniaui.net) for more information.
> 

Could you tell us more about it?


> Other than that we would certainly be open to working with companies like DevExpress to help them port their libraries, there is certainly a lot of demand....
> 
> please reach out to them and let them know your interest.

I will and hope that many other do to!

**Comment by kvalitetskontrollMarkaryd** [comment]
Vote for it! 

https://supportcenter.devexpress.com/ticket/details/t1014149/controls-for-avalonia-ui

**Comment by najak3d** [comment]
Add SyncFusion to the list of vital control packages for Avalonia, to bring in a ton more usage.   With MAUI floundering (and Xamarin Forms sucking as always), there is good opportunity here for Avalonia to steal market share.

**Comment by andyb1979** [comment]
I just dropped an email to team@avaloniaui.net to discuss porting [SciChart](https://www.scichart.com/wpf-chart-features). If anyone wants to get in touch to help us (initially we just need a consult of whether this is possible) feel free to email me Andrew [at] scichart.com

**Comment by jmacato** [comment]
@andyb1979 I've let my colleagues know about your mail :)
