### ISSUE TITLE
Menu Navigation on Windows: Tab/Escape/Tab throws Exception

### ISSUE THREAD

**Issue by axlj45** [AvaloniaUI/Avalonia#3459]
Tested on Versions: 0.9.0, 0.9.2
Operating System: Windows 7; Issue does not exist on OSX

**Steps to Reproduce**
- Generate application from MVVM template
- Populate MainWindow with DockPanel + Menu from first example here: https://avaloniaui.net/docs/controls/menu
- Build/Run
- Activate window
- Press Tab to activate within Menu
- Press escape
- Press Tab
- Null Reference Exception occurs within: https://github.com/AvaloniaUI/Avalonia/blob/4299cf3db2dea6329b4a7b668f420c7a5ecf31c3/src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs#L129-L132

**Comment by hack2root** [comment]
There is no checking for null in KeyDown(IMenuItem item, ...), despite the fact that interface is nullable
