### ISSUE TITLE
Avalonia and ReactiveUI usage?

### ISSUE THREAD

**Issue by SCLD-JBuczkowski** [AvaloniaUI/Avalonia#3463]
Hi:

I'm working on coming up to speed with Avalonia
I notice that the tutorial/examples make use of ReactiveUI.

Q: When building apps with Avalonia, are you required to use ReactiveUI as well?
Can Avalonia be used without ReactiveUI?
Can other packages be integrated instead?

Thanks,
JohnB

**Comment by danwalmsley** [comment]
@SCLD-JBuczkowski Avalonia includes ReactiveUI for convenience, however you are free to simply implement `INotifyPropertyChanged` on your viewmodel classes, or use another framework that does this for you.

    We recommend ReactiveUI because it removes the need for a lot of boilerplate code needed to get started with Avalonia, WPF, UWP, Xamarin and other similar frameworks.

**Comment by MikeCodesDotNET** [comment]
V11 no longer ships with RX dependencies. We've also updated our docs to make it clearer that RxUI isn't a requirement.
