### ISSUE TITLE
Temp fix to TextWrapping?

### ISSUE THREAD

**Issue by Wyvernius** [AvaloniaUI/Avalonia#3478]
So, i've been reading up on the issues of TextWrapping:
[#2472](https://github.com/AvaloniaUI/Avalonia/issues/2472)
And
[#2129](https://github.com/AvaloniaUI/Avalonia/issues/2129)

And using DockPanels where ever i could, i could not get the TextWrapping to work.
As my application mostly contains ListBoxes and DockPanels my solution was:
 ```
<ListBox x:Name="MyListBox" Grid.Row="1" Items="{Binding ListBoxItems}" IsVisible="{Binding ListBoxVisible}" BorderThickness="0" BorderBrush="Transparent">
    <ListBox.ItemsPanel>
      <ItemsPanelTemplate>
        <VirtualizingStackPanel Orientation="Vertical" Spacing="0,0,0,20"/>
      </ItemsPanelTemplate>
    </ListBox.ItemsPanel>
    <ListBox.ItemTemplate>
      <DataTemplate>
        <DockPanel Height="200" MaxWidth="{Binding $parent[ListBox].Presenter.Panel.Bounds.Width}" >
          <TextBlock Text="{Binding}" Foreground="Black" FontSize="45" TextWrapping="Wrap"/>
        </DockPanel>
      </DataTemplate>
    </ListBox.ItemTemplate>
  </ListBox>
```
It basicly binds the MaxWidth to the VirtualizingStackPanel.
Hope i can help some people with this little hack till it gets properly sorted.

**Comment by Gillibald** [comment]
Sry this is a total hack. TextWrapping only works with a limited width but a StackPanel measures its children with infinite space. So this is expected behavior.

**Comment by Wyvernius** [comment]
That makes sense.
But wouldn't it be awsome for a stackpanel to have an option to constrain to parent?
like : ContrainToParentHorizontal="true"

**Comment by Gillibald** [comment]
This is about the viewport mainly. Most of the time a ScrollViewer is involved. We might want to propagate the current viewport to containers so a TextBlock can wrap even when there is infinite space for other controls.

**Comment by Wyvernius** [comment]
UPDATE:

I've found out that setting 
`ScrollViewer.HorizontalScrollBarVisibility="Disabled"`
on ListBox will also wrap text in the ListBoxItem.
