### ISSUE TITLE
Stringformat - Display as hex not working

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#3479]
No matter what I try, I cannot get an int/long/ulong value to show as hex decimal in Avalonia:

```
<DataGridTextColumn Binding="{Binding Value, StringFormat={}{0:x}}" Header="Abc" />
<DataGridTextColumn Binding="{Binding Value, StringFormat='{}{0:x}'}" Header="Abc" />
<DataGridTextColumn Binding="{Binding Value, StringFormat='{0:x}'}" Header="Abc" />
<DataGridTextColumn Binding="{Binding Value, StringFormat='\{0:x\}'}" Header="Abc" />
<DataGridTextColumn Binding="{Binding Value, StringFormat=X}" Header="Abc" />
```

What am I doing wrong?

**Comment by MihaMarkic** [comment]
This works in version 0.10

```xaml
         <TextBlock>
            <TextBlock.Text>
              <MultiBinding StringFormat="{}{0} {1:x4}">
                <Binding Path="Name" />
                <Binding Path="Address" />
              </MultiBinding>
            </TextBlock.Text>
          </TextBlock>
```

**Comment by Symbai** [comment]
Yours is different than mine (1. x4 is different format than just x and 2. you have a multibinding). Have you tried if what I wanted to achieve is possible?

Perhaps it makes sense to check that first before we blindly close an issue @kekekeks ?!

**Comment by Gillibald** [comment]
We should make sure `DataGridTextColumn` correctly handles `StringFormat`

**Comment by MihaMarkic** [comment]
This also works (where DataContext is an int.
```xaml
<TextBlock Text="{Binding StringFormat={}{0:x}}" />
```

**Comment by maxkatz6** [comment]
@Symbai just checked in control catalog:
```
<DataGridTextColumn Header="Population" Binding="{Binding Population, StringFormat={}{0:x}}" Width="3*" />
```
Works fine:
![image](https://user-images.githubusercontent.com/3163374/115158669-51d13580-a05d-11eb-906b-91a1ec1c7a06.png)

What am I doing wrong?

**Comment by MihaMarkic** [comment]
@Symbai I suggest you to create a simple repro.
