### ISSUE TITLE
DataGrid: DragDrop.AllowDrop doesn't work on empty space of grid

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/Avalonia#3483]
Hi!

### Dev Setup

* VS 2019 (16.4.2)
* .NET Core 3
* Avalonia 0.9.2

### Bug Description

When I set `DragDrop.AllowDrop="True"` on a `DataGrid`, I can only drop onto the grid where there are already existing rows. I can't drop into an empty `DataGrid` (or into the empty part of a `DataGrid`), as evidenced by the drag and drop icon shown.

### What I Expect

I expect to be able to drag and drop anywhere on the DataGrid.

### Reproducing

In the below project and XAML, I've got a blue `Rectangle` in the UI too to show where the `DataGrid` should be.

Repo project: https://github.com/Deadpikle/AvaloniaBugs (DragDropDataGrid project)

XAML:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="500" d:DesignHeight="450"
        Width="400" Height="400"
        x:Class="DragDropDataGrid.MainWindow"
        Title="DragDropDataGrid">
  <Grid>
    <Rectangle Fill="LightBlue"/>
    <DataGrid Grid.Column="0"
              Grid.Row="2"
              Items="{Binding}"
              DragDrop.AllowDrop="True"
              VerticalAlignment="Stretch"
              HorizontalAlignment="Stretch"
              Grid.ColumnSpan="1">
      <DataGrid.Columns>
        <DataGridTemplateColumn Header="String"
                                IsReadOnly="True"
                                Width="*"
                                CanUserReorder="False">
          <DataGridTemplateColumn.CellTemplate>
            <DataTemplate>
              <TextBlock Text="{Binding .}" TextWrapping="Wrap" MaxHeight="100"/>
            </DataTemplate>
          </DataGridTemplateColumn.CellTemplate>
        </DataGridTemplateColumn>
      </DataGrid.Columns>
    </DataGrid>
  </Grid>
</Window>

```

**Comment by mat1jaczyyy** [comment]
Try set DataGrid's Background property? `<DataGrid Background="Transparent"`...

**Comment by maxkatz6** [comment]
Correct. By default controls have "null" or "unset" background color that is ignored with operations like DragDrop. With "Transparent" or any other specific background it works.
