### ISSUE TITLE
Question: How do I override a style?

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#3485]
Not talking about brushes but a style. In WPF we can create a resource dictionary and then use BasedOn to override. How do I achieve this in Avalonia?

In detail I would like to add column separator line to the Datagrid, so I would need to overwrite the existing:
https://github.com/AvaloniaUI/Avalonia/blob/6c4d1ff1405b6502494bbbcbd2c8df480dcde467/src/Avalonia.Controls.DataGrid/Themes/Default.xaml#L95
and add a border line. Is there any example on this?

**Comment by grokys** [comment]
In avalonia, the style that is closest to the control "wins", so if you have the `DataGrid` theme file in your `Styles` collection just place your override after it, or in the `Window` etc.

For example:

```
  <Application.Styles>
    <StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml"/>
    <StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseLight.xaml"/>
    <StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Default.xaml"/>
    <Style Selector="DataGridRow">
      <!-- Override style here -->
    </Style>
```

See http://avaloniaui.net/docs/styles/styles#style-precedence for more info.

**Comment by SuperJMN** [comment]
The link above is broken. Correct one is https://docs.avaloniaui.net/docs/styling/styles#style-precedence
