### ISSUE TITLE
Hard Crash when Title is bound to a Null String (MacOS)

### ISSUE THREAD

**Issue by josegomez** [AvaloniaUI/Avalonia#3489]
MVVM Application, when Title on Window is bound to Model Property and the Property is not initialized (null)
It produces a HARD CRASH on MacOS, works fine on Linux and Windows.

Min Repro:
```
dotnet new avalonia.mvvm -o myApp

```

Modify MainWindow.xaml
```
Title="{Binding Title}"
```

Modify MainWindowViewModel add Title property
```
publis string Title {get;set;}
```

Produces a Hard Crash
![image](https://user-images.githubusercontent.com/420837/73320985-13104f00-420f-11ea-8e0d-16ab445520fe.png)

**Comment by kekekeks** [comment]
@grokys should we replace invalid values with "" there?

**Comment by MikeCodesDotNET** [comment]
I've tested on v11 RC, and it's now working (no crash when bound to null).
