### ISSUE TITLE
Question: Which assemblies are safe to remove after publish?

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#3490]
`PublishTrimmed=true` fails when using Avalonia. So I would like to manually remove assemblies which are not required at all when targeting Linux 64bit only. Which assemblies are safe to remove (I expect some aren't used at all, for example Avalonia.Win32.dll) ?

```
Avalonia.Animation.dll
Avalonia.Base.dll
Avalonia.Controls.DataGrid.dll
Avalonia.Controls.dll
Avalonia.DesignerSupport.dll
Avalonia.Desktop.dll
Avalonia.DesktopRuntime.dll
Avalonia.Diagnostics.dll
Avalonia.Dialogs.dll
Avalonia.Direct2D1.dll
Avalonia.dll
Avalonia.FreeDesktop.dll
Avalonia.Input.dll
Avalonia.Interactivity.dll
Avalonia.Layout.dll
Avalonia.Logging.Serilog.dll
Avalonia.Markup.dll
Avalonia.Markup.Xaml.dll
Avalonia.Native.dll
Avalonia.OpenGL.dll
Avalonia.ReactiveUI.dll
Avalonia.Remote.Protocol.dll
Avalonia.Skia.dll
Avalonia.Styling.dll
Avalonia.Themes.Default.dll
Avalonia.Visuals.dll
Avalonia.Win32.dll
Avalonia.X11.dll
DynamicData.dll
JetBrains.Annotations.dll
Microsoft.CodeAnalysis.CSharp.dll
Microsoft.CodeAnalysis.dll
Microsoft.CodeAnalysis.VisualBasic.dll
Microsoft.VisualBasic.dll
Microsoft.Win32.SystemEvents.dll
ReactiveUI.dll
Serilog.dll
Serilog.Sinks.Debug.dll
Serilog.Sinks.Trace.dll
SharpDX.Direct2D1.dll
SharpDX.Direct3D11.dll
SharpDX.dll
SharpDX.DXGI.dll
SharpGen.Runtime.COM.dll
SharpGen.Runtime.dll
SkiaSharp.dll
Splat.dll
System.Drawing.Common.dll
System.Reactive.dll
Tmds.DBus.dll
```

**Comment by adroslice** [comment]
I did not have the same issue, at least when I used avalonia 1-2 months ago. The trimming worked, though I could only test the resulting binaries on windows and linux, not mac. I'd like to note that I also published it as self-contained.

**Comment by Symbai** [comment]
I need to publish without self-contained and targeting Linux and if you try that using the latest version you will get an error too. But its the wrong place/repo for discussing this error. So let's focus on which assembly can be safety removed.

Perhaps it also makes sense to split Avalonia into separate nuget packages for Linux / Mac and Windows which can be added depending for which platform you publish.

**Comment by kekekeks** [comment]
Microsoft.CodeAnalysis.* parts are definitely not used. It's not worth stripping platform backends since they are only few KiBs.

**Comment by Symbai** [comment]
Nice, Resharper also lists them as unused references but they always get dropped into output director and I dont know why. They are analyzers in the project solution I cannot remove them. Also they are the biggest part (10mb) together with:

libSkiaSharp.so 9.6mb
System.Reactive.dll 1.2mb
DynamicData.dll 651kb
System.Drawing.Common.dll 639kb
SharpDX.Direct2D1.dll 500kb

and the rest seems okay with <100kb, not worth removing them.

**Comment by ahopper** [comment]
PublishTrimmed is working for me (at least on windows and linux using netcore 3.1) there is an approach in my last comment on https://github.com/AvaloniaUI/Avalonia/issues/3337 that removes a lot of stuff, also on windows using -r win-x64 removed some stuff.

**Comment by kekekeks** [comment]
You can remove the reference to `Avalonia.Desktop` and reference platform backends manually.

**Comment by Symbai** [comment]
@ahopper @kekekeks That did the trick. Total file size dropped by nearly 20mb.

Does Linux requires both X11 and Skia? Or can I only use one?

**Comment by ahopper** [comment]
you need both, X11 gives Skia something to draw on.

**Comment by Symbai** [comment]
Alright, guess there is nothing left to remove then.

**Comment by Symbai** [comment]
> 
> 
> PublishTrimmed is working for me (at least on windows and linux using netcore 3.1) 

FYI: I was on netcore 3.0 still (I guess that's what the Avalonia Template generates?!). After switching to 3.1 the trimmer works and eliminated another 30mb on self contained. So after all changes I went from 117mb to 62mb when publishing self contained.
