### ISSUE TITLE
TextInput event of TextBox

### ISSUE THREAD

**Issue by Thecentury** [AvaloniaUI/Avalonia#3491]
Hi!

TextBox internally marks TextInput's event args as handled, and therefore if you subscribe to its `TextInput` event, it will never be fired.

Is that expected behavior?

**Comment by Toreole** [comment]
Well it's been like that for several years now, but it just does not make sense for the event to be public while being handled entirely internally.
Kinda defeats the purpose of it being public.

**Comment by kekekeks** [comment]
`TextInput` event is *not* `TextBox`'s own event, it's triggered by the text input system for any focused control. `TextBox` has to mark it as handled so it won't be passed to parent controls all over the tree.

**Comment by maxkatz6** [comment]
Some code snipped for future.
Closing as resolved.
```csharp
MyTextBox.AddHandler(TextInputEvent, ViewBlock_TextInput, RoutingStrategies.Tunnel);

void ViewBlock_TextInput(object sender, TextInputEventArgs e)
{
}
```
