### ISSUE TITLE
Switching styles at runtime doesn't update all controls that inherit

### ISSUE THREAD

**Issue by InfinityGhost** [AvaloniaUI/Avalonia#3495]
Put simply, switching styles doesn't update all controls inheriting the style. In this example, its specifically switching the accent style to change themes from light to dark. Notice that only the background on some controls (generally with dropdowns) seem to be updated after changing.

- [Video](https://streamable.com/kmvx6)
- [Reproduction repo from video](https://github.com/InfinityGhost/AvaloniaTests)

Not sure if this is something I'm doing wrong or if this is an isolated case, but its a major issue that I had to work around in my main project, [OpenTabletDriver](https://github.com/InfinityGhost/OpenTabletDriver), by restarting the main window. If there's a better method, I'd really like to know.

**Comment by jp2masa** [comment]
I think that's not supported yet, but I have a workaround for that:
1. [App.xaml.cs](https://github.com/jp2masa/dotnet-properties/blob/master/src/dotnet-properties/App.xaml.cs#L46)
2. [On each window](https://github.com/jp2masa/dotnet-properties/blob/master/src/dotnet-properties/Views/MainWindow.xaml.cs#L38)

**Comment by InfinityGhost** [comment]
So the `Styles` class implements `INotifyCollectionChanged` but it doesn't notify windows that it was changed? A workaround like this shouldn't be required but I'm glad there is one at least.

**Comment by maxkatz6** [comment]
It must have been fixed long time ago.
Ping me to reopen if not.
