### ISSUE TITLE
Direct2D1Platform.Initialize should support DeviceCreationFlags

### ISSUE THREAD

**Issue by zgxnet** [AvaloniaUI/Avalonia#3496]
In the current implementation, Direct2D1Platform.Initialize takes no argument and the d3d device is created with flags DeviceCreationFlags.BgraSupport | DeviceCreationFlags.VideoSupport. Device created with DeviceCreationFlags.VideoSupport is incompatible with visual studio graphics debugging. We can consider adding a parameter to the Initialize function without breaking existing code, e.g.

        public static void Initialize(DeviceCreationFlags deviceCreationFlags = DeviceCreationFlags.BgraSupport | DeviceCreationFlags.VideoSupport)

**Comment by kekekeks** [comment]
Note that we are planning to drop Direct2D1 support and rely on ANGLE support for sharing DXGI handles instead.

**Comment by kekekeks** [comment]
Not planned, however you are welcome to submit a PR with a relevant option in Direct3DOption (see how it works with Skia).
