### ISSUE TITLE
ListBox `SelectionMode`=`Multiple` no events

### ISSUE THREAD

**Issue by JaggerJo** [AvaloniaUI/Avalonia#3497]
ListBox does not work properly when `SelectionMode` is set to `Multiple`. 

Tested on Avalonia 0.9.2

Simple repro
```fsharp
type MainWindow() as this =
    inherit Window()
    do
        let listBox = new ListBox()
        listBox.SelectionMode <- SelectionMode.Multiple
        listBox.Items <- [
            "Item 1"
            "Item 2"
            "Item 3"
            "Item 4"
        ]
        
        listBox.SelectionChanged.Add(fun _ ->
            // only fired if a single item is selected. does not fire
            // for multiple selected items
            printfn "selection changed event"
        )
        
        listBox.GetSubject(ListBox.SelectedItemsProperty).Add(fun args ->
            // never fired when a selection changed
            printfn "subscription 'SelectedItemsProperty'"
        )
        
        base.Content <- listBox
```

**Comment by FoggyFinder** [comment]
The same as #3448 ?

**Comment by JaggerJo** [comment]
@FoggyFinder not exactly, `ListBox.SelectedItemsProperty` subscription also does not work

**Comment by grokys** [comment]
Hoping to fix this with https://github.com/AvaloniaUI/Avalonia/pull/3469 although we may have to remove `SelectedItems` so may be an API breakage.

**Comment by JaggerJo** [comment]
ok 👍 will this be fixed in a dot release ?

**Comment by grokys** [comment]
Probably for 0.10 as it's a breaking change.

**Comment by JaggerJo** [comment]
ok.

**Comment by MarchingCube** [comment]
@JaggerJo Please note that simply subscribing to `SelectedItems` is not enough, you need to subscribe to collection changes since we don't reassign `SelectedItems` but instead add/remove from the collection. Or bind your own collection (like `ObservableCollection`) and listen to `CollectionChanged` events on it.

**Comment by JaggerJo** [comment]
@MarchingCube Wouldn't it be simpler (at least from a consumer perspective) if it would just work ?

IMHO the current behaviour is technically correct and makes sense, but is a bit weird for a consumer. FuncUI currently exposes:

- `onSelectedItemChanged`(subscription of  `SelectedItem`) 
- `onSelectedItemsChanged` (subscription of `SelectedItems`)

and their behaviour is different (while not technically). 

`SelectedItem` gives you the newly selected item because its reassigned while `SelectedItems` does not because its a mutation.

**Comment by Gillibald** [comment]
The current solution is better in scenarios where you transform the collection of selected items.
