### ISSUE TITLE
Drag and drop doesn't work for outside-of-app files on macOS

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/Avalonia#3502]
On macOS, I'm unable to drag files (e.g. from Finder) from outside the application into my app. It works fine on Windows™️. My `Main` has been labeled with `[STAThread]`. I have not tested on Linux yet.

Per a Gitter convo, I was told that this isn't working yet on macOS, so I'm reporting it here for help with tracking.

Thank you!

**Comment by dan0v** [comment]
I can confirm it also doesn't work on Linux (Ubuntu 20.04.1 LTS). `DragDrop.DropEvent` seems to not fire at all.

**Comment by kekekeks** [comment]
OSX support was added in 0.9.10, I think.

**Comment by dan0v** [comment]
Sorry, dragging and dropping files from Finder _does_ work on MacOS Mojave at least (couldn't test on MacOS until now), but does not work on Ubuntu in my testing. Should this ticket be closed and a new one be opened for Linux?
