### ISSUE TITLE
[Question] Software updates on macOS -- somehow link to Sparkle?

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/Avalonia#3503]
It's probably outside the scope of core Avalonia, but it'd be nice if there were software update libraries out there that people could easily pull into their apps for getting their software updates up and running. There are already software updates out there for Windows that could be ported to .NET Core/Avalonia without a ton of work, so Windows wouldn't be a huge problem -- maybe 10 hours of labor for porting a quick version to .NET Core/Avalonia if you used something like [NetSparkle](https://github.com/Deadpikle/NetSparkle) [disclaimer: I'm the maintainer there].

For macOS, though, the usual go-to is [Sparkle](https://github.com/sparkle-project/Sparkle). Since that's a bit more complicated of a project, and Avalonia builds using .NET Core, is there any way to take advantage of `Sparkle` on macOS, or will someone need to create a new software update paradigm for macOS that is written in a compatible way to .NET Core and Avalonia? (This could be difficult due to all of the sandboxing/other restrictions in macOS, in theory. In practice maybe not so much.)

Is there any easy way to link to external macOS libraries without modifying the core framework?

Thanks!

**Comment by kekekeks** [comment]
>Is there any easy way to link to external macOS libraries without modifying the core framework?

The easiest way would be to create a P/Invoke wrapper native library and ship it via nuget.

**Comment by Deadpikle** [comment]
Oh, duh. P/Invoke with a wrapper. Should have thought of that.

I googled for some resources re: Xamarin on macOS, in hopes that they would apply to Avalonia use as well to any future web searchers who end up here. I'll link them here for posterity and close this question. If I ever make a tutorial/write up steps on getting Sparkle working on macOS w/Avalonia, I'll be sure to post them here/get them to the Avalonia docs somehow.

* [Bindings for Sparkle](https://github.com/rainycape/SparkleSharp)
* [Some discussion on sparkle-project about getting things working with Xamarin](https://github.com/sparkle-project/Sparkle/issues/1209)
* [Binding Objective-C libraries](https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-objective-c/walkthrough?tabs=windows)

Thank you! Appreciate your time.

**Comment by kekekeks** [comment]
Unfortunately any Xamarin bindings only work with Mono runtime and are not compatible with .NET Core. Since Avalonia is targeting `netstandard2.0`, you most likely should be able to use it from Xamarin.Mac app.

**Comment by Deadpikle** [comment]
For future Google users, I got an Avalonia app to link to and use Sparkle successfully _when packaging within a `.app` file_, and you can see the details and example repo here:

https://github.com/Deadpikle/macOS.SparkleUpdater.Avalonia
