### ISSUE TITLE
Design.DataContext is not inherited by child controls DataContext

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#351]
Here I set the design-time `Design.DataContext`
https://github.com/Core2D/Core2D/blob/410d98d0d2d1c6e3ad56c00fcb092f38f018bd93/Core2D.Perspex/Controls/Editor/EditorControl.paml#L12
and the following `DataContext` should inherit the `Design.DataContext`:
https://github.com/Core2D/Core2D/blob/410d98d0d2d1c6e3ad56c00fcb092f38f018bd93/Core2D.Perspex/Controls/Editor/EditorControl.paml#L22

**Comment by grokys** [comment]
@wieslawsoltes is this still an issue?

**Comment by wieslawsoltes** [comment]
I do not use this anymore and as discussed in other issue Design.DataContext probably should be removed in the favor of the d:DataContext.
