### ISSUE TITLE
DataGrid does not properly update on ObservableCollection.AddRange

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#3510]
The DataGrid only shows 1 item of a collection when added via AddRange implementation. This is a huge problem as DataGrid cannot be bound to anything else  like a List<T> than ObservableCollection, which by default has no possiblity to add a bunch of items at once. The result is that even a small collection with only 50,000 items take very long for the Grid to update itself. See below:

### ObservableCollection.AddRange Implementation:
Full implementation here: https://github.com/dotnet/corefx/pull/10751
```
public void AddRange(IEnumerable<T> collection, bool clearFirst = false)
{
    CheckReentrancy();

    if (clearFirst) Items.Clear();

    List<T> list = (List<T>)Items;
    list.AddRange(collection);

    OnPropertyChanged(CountString);
    OnPropertyChanged(IndexerName);
    OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Add, new List<T>(collection)));
}
```
### XAML:
```
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition />
    </Grid.RowDefinitions>
    <Button Command="{Binding Generate}" Content="Generate Items" />
    <DataGrid
        Name="dataGrid1"
        Grid.Row="1"
        AutoGenerateColumns="True"
        IsReadOnly="True"
        Items="{Binding MyCollection}" />
</Grid>
```

### C#:
```
public class MainWindowViewModel : ViewModelBase
{
    public ObservableCollectionEx<Abc> MyCollection { get; } = new ObservableCollectionEx<Abc>();

    public MainWindowViewModel()
    {
            
    }

    public ReactiveCommand<Unit, Unit> Generate => ReactiveCommand.Create(() =>
    {
        var l = new List<Abc>();
        for (int i = 0; i < 50000; i++)
        {
            l.Add(new Abc());
        }

        MyCollection.AddRange(l);
    });
}
public class Abc
{
    public string MyColumn { get; } = "Hi";
}
```
### Result:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14368203/73740614-65d29500-4740-11ea-9e39-6275695471f9.gif)

### Expected:
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/14368203/73740628-6c610c80-4740-11ea-964c-f14255b6810a.gif)

##### Expected C# code
```
public ReactiveCommand<Unit, Unit> Generate => ReactiveCommand.Create(() =>
{
    var l = new List<Abc>();
    for (int i = 0; i < 50000; i++)
    {
        MyCollection.Add(new Abc());
    }
});
```

**Comment by stepin105366** [comment]
> The DataGrid only shows 1 item of a collection when added via AddRange implementation. This is a huge problem as DataGrid cannot be bound to anything else like a List than ObservableCollection, which by default has no possiblity to add a bunch of items at once. The result is that even a small collection with only 50,000 items take very long for the Grid to update itself. See below:
> 
> ### ObservableCollection.AddRange Implementation:
> Full implementation here: [dotnet/corefx#10751](https://github.com/dotnet/corefx/pull/10751)
> 
> ```
> public void AddRange(IEnumerable<T> collection, bool clearFirst = false)
> {
>     CheckReentrancy();
> 
>     if (clearFirst) Items.Clear();
> 
>     List<T> list = (List<T>)Items;
>     list.AddRange(collection);
> 
>     OnPropertyChanged(CountString);
>     OnPropertyChanged(IndexerName);
>     OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Add, new List<T>(collection)));
> }
> ```
> 
> ### XAML:
> ```
> <Grid>
>     <Grid.RowDefinitions>
>         <RowDefinition Height="Auto" />
>         <RowDefinition />
>     </Grid.RowDefinitions>
>     <Button Command="{Binding Generate}" Content="Generate Items" />
>     <DataGrid
>         Name="dataGrid1"
>         Grid.Row="1"
>         AutoGenerateColumns="True"
>         IsReadOnly="True"
>         Items="{Binding MyCollection}" />
> </Grid>
> ```
> 
> ### C#:
> ```
> public class MainWindowViewModel : ViewModelBase
> {
>     public ObservableCollectionEx<Abc> MyCollection { get; } = new ObservableCollectionEx<Abc>();
> 
>     public MainWindowViewModel()
>     {
>             
>     }
> 
>     public ReactiveCommand<Unit, Unit> Generate => ReactiveCommand.Create(() =>
>     {
>         var l = new List<Abc>();
>         for (int i = 0; i < 50000; i++)
>         {
>             l.Add(new Abc());
>         }
> 
>         MyCollection.AddRange(l);
>     });
> }
> public class Abc
> {
>     public string MyColumn { get; } = "Hi";
> }
> ```
> 
> ### Result:
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14368203/73740614-65d29500-4740-11ea-9e39-6275695471f9.gif)
> 
> ### Expected:
> ![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/14368203/73740628-6c610c80-4740-11ea-964c-f14255b6810a.gif)
> 
> ##### Expected C# code
> ```
> public ReactiveCommand<Unit, Unit> Generate => ReactiveCommand.Create(() =>
> {
>     var l = new List<Abc>();
>     for (int i = 0; i < 50000; i++)
>     {
>         MyCollection.Add(new Abc());
>     }
> });
> ```

any update on this. I'm also facing same issue

**Comment by redrabbit007** [comment]
I'm having the same issue. Although I'm using a AvaloniaList, not a ObservableCollection. I have the same AvaloniaList bound to both a DataGrid and a itemsControl. The ItemsControl shows all of the items, but the DataGrid only shows the first item when new items are added with AddRange. If I add the items one by one it shows all of them as expected.

**Comment by spreedated** [comment]
Same here, any news?
