### ISSUE TITLE
Unable to find suitable setter or adder for property Click

### ISSUE THREAD

**Issue by DragonSWDev** [AvaloniaUI/Avalonia#3515]
I'm unable to set "Click" event for Button in XAML. Adding "Click" attribute in XAML throws error during compilation (no matter if method exist or not in cs file):
"Avalonia error XAMLIL: Unable to find suitable setter or adder for property Click of type Avalonia.Controls:Avalonia.Controls.Button for argument System.Runtime:System.String, available setter parameter lists are:"

Here is MainWindow.xaml:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="MMHelper.MainWindow"
        Title="MMHelper">
    <Button Click="testClick" Content="Test" />
</Window>
```

I've looked into issues and found similar issue but I seems it was fixed. I'm using .Net Core 3.1 on Arch Linux, Avalonia version is 0.9.2.

**Comment by grokys** [comment]
@DragonSWDev for the moment your `Click` handler needs to be `public`, is that the problem?

Hopefully we can remove this restriction at some point @kekekeks ?

**Comment by Wyvernius** [comment]
try:
`<Button Click="{Binding testClick}" Content="Test" />`
Assuming you're using the MVVM model.

```
public void testClick()
{
}
```

**Comment by DragonSWDev** [comment]
@grokys @Wyvernius Somehow now it's working with private and public handler when I created new project. No idea why it wasn't working before with same code. My apologies for not checking it before creating issue. I will now close this, thank you for answers.

**Comment by kekekeks** [comment]
`public` handlers are required for previewer to work. Compiler itself is fine fine with handlers being private.

**Comment by unominhtuan** [comment]
> `public` handlers are required for previewer to work. Compiler itself is fine fine with handlers being private.

can be used with events located in MainWindowViewModel?

**Comment by Jerkoviz** [comment]
Hi. I have similar problem. I am trying to add event SelectionChanged to drop box, but I get this error. Also getting same error with PointerPressed event in data grid, but LoadingRow works.  So theese are events from documentation.  Am I missing something?
I'm using Avalonia 0.10.14 on Windows and .NET6.

`<ComboBox  Name="ComboBox"
											Width="100"
											Height="28"
											Margin="15,21,0,0"
											Items="{Binding SerialCards}"
											SelectedItem="{Binding Path=SelectedCard, Mode=TwoWay}" SelectionChanged="_DropDownClosed"/>`

`<DataGrid MaxHeight="300"  Name="InvoicesGrid" Items="{Binding SdcImportedInvoices}" AutoGenerateColumns="False"
									  LoadingRow="dataGrid_LoadingRows" IsReadOnly="True" PointerPressed="_OnRowClick">`

**Comment by bsvabic** [comment]
Hello.. I had similar problem, also, and I resolved it on a way that I'm used propper parameter in a given event method. For example, if we want use GotFocus we can use method such as:
`private void Handler(object sender, GotFocusEventArgs e)
        {
            
        }`

If we want use LostFocus we can use it such as:
`private void Handler2(object sender, RoutedEventArgs e)
        {
            
        }`
If we want use TextInput event we can use it such as:
`private void Handler3(object sender, TextInputEventArgs e)
        {
            
        }`
Where Handler, Handler2 and Handler3 are names of given event from xaml. 
You can see documentation, for example for textbox control:
[http://reference.avaloniaui.net/api/Avalonia.Controls/TextBox/](url)
