### ISSUE TITLE
Problem with Chinese/Japanese text

### ISSUE THREAD

**Issue by Wyvernius** [AvaloniaUI/Avalonia#3522]
internationalÏñŧĕŕŋāţלגזסכײת 日本語Вџссибجرطف中文Ηελενιγ
the string above is correctly rendered on all programs on the machine but not in avalonia.
Only the Japanese and Chinese characterd render as ractangles.
The chinise fonts are installed on my system.
MAybse someone has an idea on how to fix this?
Currently using Avalonia 9.2 with NET 4.7.2 on Windows.
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="FontFamilyTest.MainWindow"
        Title="FontFamilyTest"
        >
  internationalÏñŧĕŕŋāţלגזסכײת 日本語Вџссибجرطف中文Ηελενιγ
</Window>
```

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/3438

**Comment by chaojian-zhang** [comment]
Hi I am using **Avalonia 0.9.4** with **.Net Core 3.1**, I am experience issue displaying Chinese characters:

1. I have tried all fonts that's mentioned including ones specifically for Chinese (e.g. **楷体**) and it always displays a boxes (see screenshot) - however it's perfectly safe to **copy those boxes from the application to other places and it will display correctly (e.g. inside Notepad++)** so the encoding is right but somehow either the font is not working or the framework isn't loading the font correctly.
2. The letters display fine in title

![2020-03-13 15 40 13](https://user-images.githubusercontent.com/7077098/76654485-6d583b80-6541-11ea-9906-f28d9236d6e0.png)

I have looked into #3438 and that doesn't work as well.

**Comment by grokys** [comment]
Hi @chaojian-zhang, when you said "I have looked into #3438 and that doesn't work as well" - how have you tested it? That PR isn't part of an official release yet so you'll have to use our unstable packages: http://avaloniaui.net/docs/quickstart/packages#unstable-releases

**Comment by chaojian-zhang** [comment]
I saw on the issue page it's **merged** and thought that's already published.

I used **Version 0.9.4** which was published on Wednesday, March 11, 2020 (3/11/2020). I am not sure whether that's the nightly build you were referring to though.

**Comment by Codexiaoyi** [comment]
> #3438

TextBlock can be displayed, but the TextBox also cannot display Chinese normally.

**Comment by Codexiaoyi** [comment]
> Hi @chaojian-zhang, when you said "I have looked into #3438 and that doesn't work as well" - how have you tested it? That PR isn't part of an official release yet so you'll have to use our unstable packages: http://avaloniaui.net/docs/quickstart/packages#unstable-releases

Hi ,I used unstable-release with version:0.9.999-cibuild0006235-beta,TextBlock can be displayed, but the TextBox also cannot display Chinese normally.Is there any plan to fix it?Hope you can reply me,please.

**Comment by Gillibald** [comment]
TextBox will get a rewrite this year but can't say when.

**Comment by Codexiaoyi** [comment]
> TextBox will get a rewrite this year but can't say when.

Nice!I look forward to using it as soon as possible.

**Comment by JasonGrass** [comment]
Setting TextBox FontFamily like this maybe useful for Chinese ： 
` "Microsoft YaHei,Simsun,苹方-简,宋体-简" `

我这里直接设置系统字体可以解决，将 FontFamily 设置为 ` "Microsoft YaHei,Simsun,苹方-简,宋体-简" `。
详见：[AvaloniaUI TextBox 不能显示中文的问题解决 - J.晒太阳的猫](https://www.cnblogs.com/jasongrass/p/13758003.html )
