### ISSUE TITLE
AvaloniaProperty.Register notifying method not working as expected

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#3523]
Avalonia 0.9.2
I maybe misunderstanding the purpose of the notifying callback parameter of the AvaloniaProperty.Register method, but I expected it to be called before and after the value of the registered property changed.

What I found is that the value of the property has already changed when the notifying callback is called. So the code below leaks memory when the property changes as the CollectionChanged event handler is never released. MyValue is the new value for both before = true and before = false.

```
public static AvaloniaProperty<IEnumerable> MyValueProperty = AvaloniaProperty.Register<MyClass, IEnumerable>(
    nameof(MyValue), Array.Empty<object>(), notifying: OnMyValueChanged);

public IEnumerable MyValue
{
    get => GetValue(MyValueProperty);
    set => SetValue(MyValueProperty, value);
}

private static void OnMyValueChanged(IAvaloniaObject sender, bool before)
{
    if (sender is MyClass instance)
    {
        if (before)
        {
            if (instance.MyValue is INotifyCollectionChanged oldCollection)
            {
                oldCollection.CollectionChanged -= instance.OnCollectionChanged;
            }
        }
        else
        {
            if (instance.MyValue is INotifyCollectionChanged newCollection)
            {
                newCollection.CollectionChanged += instance.OnCollectionChanged;
            }
        }
    }
}
```
Have I misunderstood what the before parameter is intended for in the notifying callback?

For now I will change this to a use the MyValueProperty.Changed  subscription to fix the memory leak.

**Comment by grokys** [comment]
Hi @aguahombre, yes the `notifying` callback is mainly intended for internal in the mechanism around `DataContext` changes. It's very unlikely you'll want to use this callback yourself. I'll refer you to the documentation:

https://github.com/AvaloniaUI/Avalonia/blob/426c67088236386edeb98f5c28e532ebe7958500/src/Avalonia.Base/AvaloniaProperty.cs#L262-L266

The correct way to listen for change notifications as you say is to listen to `MyValueProperty.Changed`.
