### ISSUE TITLE
Is it possible to create named resources in XAML?

### ISSUE THREAD

**Issue by Sergey-Terekhin** [AvaloniaUI/Avalonia#353]
Hi
I try to create simple theme for Perspex, but I would like not to hardcode colors and brushes in the control's styles definitions (like `<Setter Property="Background" Value="#ffaaaaaa"/>`)
Instead I would like to use named resources like
`<Setter Property="Background" Value="{DynamicResource PrimaryHueMidBrush}"/>`
But I do not know how to define brush in the resources and how to reference it. Is it possible?

**Comment by grokys** [comment]
Unfortunately that's something that's not yet implemented.

As a work-around for the moment I would suggest exposing the values as static members of a class and using `Value={Static MyTheme.PrimaryHueMidBrush}`.

**Comment by grokys** [comment]
This is now supported using style resources.
