### ISSUE TITLE
[nvidia] Multiple opening and closing a ToolTip causes UI hang.

### ISSUE THREAD

**Issue by ghost** [AvaloniaUI/Avalonia#3536]
OS: Linux Mint 19.2 x64 (Mate 1.22.0), .net core 3.0 and 3.1

Steps to reproduce:
1) Download and run this example: https://github.com/vmas/TooltipTest
2) Move the mouse over the window (this will make the tooltip show and hide). You will see that the window has stopped updating.

When I tried to resize the window, the window became transparent:
![window](https://user-images.githubusercontent.com/2703561/74100611-22ae6280-4b42-11ea-9cf1-b045a0dd886b.jpg)

Issue does not exist on Windows 10 x64.

Here is stack trace:
```
        Child SP               IP Call Site
00007FFE17616198 00007f670dafebb7 [InlinedCallFrame: 00007ffe17616198] Avalonia.X11.X11PlatformThreading.epoll_wait(Int32, epoll_event*, Int32, Int32)
00007FFE17616198 00007f66955478fa [InlinedCallFrame: 00007ffe17616198] Avalonia.X11.X11PlatformThreading.epoll_wait(Int32, epoll_event*, Int32, Int32)
00007FFE17616180 00007F66955478FA Avalonia.X11.X11PlatformThreading.RunLoop(System.Threading.CancellationToken)
00007FFE176162A0 00007F6695545F6A Avalonia.Threading.Dispatcher.MainLoop(System.Threading.CancellationToken)
00007FFE17616300 00007F6695525295 Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(System.String[])
00007FFE17616370 00007F6693C148CA Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[[System.__Canon, System.Private.CoreLib]](System.__Canon, System.String[], Avalonia.Controls.ShutdownMode)
00007FFE176163B0 00007F6693C0259A TooltipTest.Program.Main(System.String[])
00007FFE176166D8 00007f670d017caf [GCFrame: 00007ffe176166d8] 
00007FFE17616BC0 00007f670d017caf [GCFrame: 00007ffe17616bc0] ```

**Comment by kekekeks** [comment]
Most likely not a hang, but some exception on the render thread. Waiting on epoll_wait is the same as waiting in GetMessage on windows, it's a normal condition.
Try running Rider with "Any exception" breakpoint and decompiler enabled.

**Comment by kekekeks** [comment]
Can't repro on Ubuntu 18.04

**Comment by kekekeks** [comment]
Got a freeze and segfault on nvidia blob.

**Comment by Angular-Angel** [comment]
Yeah I just got this with Irony Mod Manager on Xubuntu. Still a problem. I assume you guys have lots of error logs? I can try and get some, but I'm not sure how to go about it. :/

**Comment by arklumpus** [comment]
I can still reproduce this bug with Avalonia 0.10.7 under .NET 5 on Ubuntu 20.04.

Interestingly, this only happens when the Fluent theme is enabled: the interface does not hang if in `App.xaml` you replace `<FluentTheme Mode="Light"/>` with 

```XAML
<StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml"/>
<StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseLight.xaml"/>
```

Updated example using Avalonia 0.10.7 and Fluent theme: [https://github.com/arklumpus/TooltipTest](https://github.com/arklumpus/TooltipTest)
