### ISSUE TITLE
Menu on monitor with 125% scaling displays black bars

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#3550]
Under Windows, when showing a menu on a screen with 125% scaling the menu has a black bar:

![image](https://user-images.githubusercontent.com/1775141/74256794-3b5e7a00-4cf4-11ea-9bba-0dea5b79e4db.png)

**Comment by grokys** [comment]
Looks like this is happening because `WindowBase.HandleResized()` [calls `LayoutManager.ExecuteLayoutPass()`](https://github.com/AvaloniaUI/Avalonia/blob/c0a903c3d20059cbb81caa865b506636c35b4c99/src/Avalonia.Controls/WindowBase.cs#L233) during a layout pass.

**Comment by kekekeks** [comment]
Do we set `UseLayoutRounding` for our toplevels?

**Comment by grokys** [comment]
The default value of `UseLayoutRounding` is `true`, yeah.

**Comment by kekekeks** [comment]
So why 
>The PopupRoot is arranged with a height of 105.33

happens? Shouldn't it be rounded before the first call to `UpdatePosition`?

**Comment by kekekeks** [comment]
Wait, does popup DPI change after creation for some weird reason?

**Comment by grokys** [comment]
I think because we don't know what the scaling factor will be until `UpdatePosition` is called: i.e. we don't know which screen it's going to be on. Notice in the above list that for the first measure the scaling is 1.5 (my primary monitor) and for the second measure it's 1.25 (my secondary monitor).

**Comment by kekekeks** [comment]
>we don't know which screen it's going to be on.

We know. Popup positioner should fit it to the same screen as the placement rect. Also, our X11 backend just reuses the parent window DPI, so there are no surprises there.

**Comment by grokys** [comment]
Regardless of this though, the fact `ExecuteInitialLayoutPass` doesn't set `_running = true` to prevent re-entrancy is a bug.

**Comment by grokys** [comment]
> We know. Popup positioner should fit it to the same screen as the placement rect.

Ok, looks like we've got two bugs here then...

**Comment by grokys** [comment]
@kekekeks the reason the scaling factor isn't set until the first layout pass is this line:

https://github.com/AvaloniaUI/Avalonia/blob/da571ac5521b5518e1c0f422b9732dcfb9071615/src/Avalonia.Controls/Primitives/PopupRoot.cs#L94-L95

`Popup` calls `ConfigurePosition` before showing the popup but it passes a size of 0,0 so `PopupPositioner.Update()` isn't called.

**Comment by kekekeks** [comment]
Attempting to pass zero size to the window system is an error. On Wayland that will cause immediate termination of the connection to the display server. We can't be sending invalid requests to the system and expect consistent and reasonable behavior.

**Comment by kekekeks** [comment]
We probably need some kind of `IValidatingWindowImpl` or something.

**Comment by grokys** [comment]
Right so we can't get a scaling factor without a position, and we can't set a position without a size. TBH, #3553 fixes the issue that we were seeing so it's not a huge problem right now.
