### ISSUE TITLE
Why am I getting a "Unable to find suitable setter or adder" error when defining a LinearGradientBrush in my <UserControl.Resources>?

### ISSUE THREAD

**Issue by SCLD-JBuczkowski** [AvaloniaUI/Avalonia#3554]
Hi:

I'm running into issues defining a LinearGradientBrush in my <UserControl.Resources> in my UserControl.

**Here is the XAML Definition:**
```
<UserControl x:Class="SampleViews.SplashView"
             xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:views="clr-namespace:SampleViews"             
             mc:Ignorable="d" >

  <UserControl.Resources>
    <LinearGradientBrush x:Key="LGB1" EndPoint="1,0.5" StartPoint="0,0.5">
      <GradientStop Color="#3F000000" Offset="0"/>
      <GradientStop Offset="1"/>
    </LinearGradientBrush>
  </UserControl.Resources>
     
  <Grid>
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width=".2*" />
      <ColumnDefinition Width=".6*" MinWidth="300"/>
      <ColumnDefinition Width=".2*"/>
    </Grid.ColumnDefinitions>
    <Border Grid.Column="0" Background="{StaticResource LGB1}"></Border>
  </Grid>
</UserControl>
```

**Here is the error message:**

> Error	XAMLIL	Unable to find suitable setter or adder for property Resources of type Avalonia.Styling:Avalonia.StyledElement for argument Avalonia.Visuals:Avalonia.Media.LinearGradientBrush, available setter parameter lists are:
> Avalonia.Controls.IResourceDictionary
> System.Collections.Generic.KeyValuePair`2<System.Object,System.Object>

I should be able to define this resource within the UserControl.Resources to be used throughout the page, correct?

Am I doing something wrong here?

Thanks,
JohnB

**Comment by kekekeks** [comment]
This code seems to be compiling fine on my machine. The compiler error suggests that you are missing x:Key, but there is one on your brush. Try cleaning and rebuilding the solution, it seems like some build tasks weren't re-run, so compiler is using a stale version.

**Comment by SCLD-JBuczkowski** [comment]
@kekekeks - If I remove it from the **<UserControl.Resources>** definition and put it as a resource on a different container, it compiles fine.

Such as:
`<Border>
    <Border.Resources>
      <converters:BuilderStateToTooltipStringConverter x:Key="HeightConverterx"/>
      <converters:PercentageConverter x:Key="HeightConverter"/>

      <LinearGradientBrush x:Key="LGB1" EndPoint="1,0.5" StartPoint="0,0.5">
        <GradientStop Color="#3F000000" Offset="0"/>
        <GradientStop Offset="1"/>
      </LinearGradientBrush>
    </Border.Resources>
</Border>`

I've had similar issues with other attributes I've tried to attach to **<UserControl.Resources>**
I'm aware of the other VS issue, so I open the XAML page through "Open with .. 'Avalonia XAML Editor'"

Thoughts?

**Comment by FoggyFinder** [comment]
Can you attach sample project?

**Comment by chenjing1294** [comment]
I have the same problem：
```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        x:Class="Avalonia.NETCoreMVVMApp1.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="Controls" Width="250" Height="150">
  <!--FontFamily="Microsoft YaHei"-->
  <Window.Resources>
    <SolidColorBrush x:Key="Warning">Yellow</SolidColorBrush>
  </Window.Resources>
  <Grid VerticalAlignment="Center" HorizontalAlignment="Center">
    <StackPanel>
      <StackPanel.Resources>
        <Bitmap x:key="Play">
          <x:Arguments>
            <x:String>/Assets/play.png</x:String>
          </x:Arguments>
        </Bitmap>
        <Bitmap x:key="Pause">
          <x:Arguments>
            <x:String>/Assets/pause.png</x:String>
          </x:Arguments>
        </Bitmap>
      </StackPanel.Resources>
      <Button Width="160">My Button</Button>
      <Button Width="200" Foreground="White" Background="Red">White text, red background</Button>

      <Button Name="PlayButton" HorizontalAlignment="Center" Width="36" Command="{Binding PlayCommand}">
        <Panel>
          <Image Source="{StaticResource Play}" IsVisible="{Binding !IsPlaying}" Width="20"
                 Height="20" VerticalAlignment="Center" HorizontalAlignment="Center" />
          <Image Source="/Assets/pause.png" IsVisible="{Binding IsPlaying}" Width="20"
                 Height="20" VerticalAlignment="Center" HorizontalAlignment="Center" />
        </Panel>
      </Button>
    </StackPanel>
  </Grid>
</Window>
```
error:
```
  MainWindow.axaml(13, 10): [XAMLIL] Unable to find suitable setter or adder for property Resources of type Avalonia.Styling:Avalonia.StyledElement for argument Avalonia.Visuals:Avalonia.Media.Imaging.Bitmap, available setter parameter lists are:
Avalonia.Controls.IResourceDictionary
System.Collections.Generic.KeyValuePair`2<System.Object,System.Object>
System.Collections.Generic.KeyValuePair`2<TKey,TValue> 第 13 行，位置 10。
```

**Comment by jp2masa** [comment]
I think the problem is you wrote `x:key` but it's `x:Key`.
