### ISSUE TITLE
CastXML issues with CentOS8

### ISSUE THREAD

**Issue by srl17** [AvaloniaUI/Avalonia#3555]
Trying to build on CentOS 8.  All pre-reqs except castXML are installed.

When using yum to install castxml I get a no match for argument; so I downloaded castxml binary from the CastXML Superbuild site which contained source and a single executable.  When I run the castxml executable it returns "Unable to locate resources..."

Do I need to put the castxml executable in a specific location? Or which yum package repo contains the castxml package?

**Comment by kekekeks** [comment]
We are looking for castxml in `/usr/bin` and `/usr/local/bin` - https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Native/Avalonia.Native.csproj#L7

castxml can be found in [castxml package](https://rpms.remirepo.net/rpmphp/zoom.php?rpm=castxml&pkgdb=1) from epel-testing

It's not required to build Linux-specific backends, just the OSX one. The only thing that would be "broken" by the lack of osx backend is the `UsePlatformDetect` method, so if you have trouble with building, you can unload Avalonia.Desktop project and replace `UsePlatformDetect` with `UseX11`.

**Comment by srl17** [comment]
Thank you! Installed castxml package from epel-testing. Now the samples/ControlCatalog.NetCore build and run on CentOS 8.
