### ISSUE TITLE
Linux - Invalid Window.ClientSize on startup

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#3561]
## Issue
On **Linux** `Window.ClientSize` is invalid on startup only. This is the root cause of `WindowStartupLocation` = Owner/CenterScreen is not working on Linux (Related #3454).

### XAML
```
<Window
    x:Class="AvaloniaApplication1.Views.MainWindow"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:vm="clr-namespace:AvaloniaApplication1.ViewModels;assembly=AvaloniaApplication1"
    Title="AvaloniaApplication1"
    Width="450"
    Height="450"
    Icon="/Assets/avalonia-logo.ico"
    mc:Ignorable="d">
    <Grid>
      <StackPanel>
        <Button Width="200" Height="100" Name="BtnClick" Content="Refresh" />
        <TextBlock Name="Txtblock"/>
      </StackPanel>
    </Grid>
</Window>
```
### In Code
```
        public MainWindow()
        {
            InitializeComponent();
#if DEBUG
            this.AttachDevTools();
#endif
            this.Opened += MainWindow_Opened;
        }

        private void MainWindow_Opened(object sender, System.EventArgs e)
        {
            var txt = this.Find<TextBlock>("Txtblock");
            var sb = new StringBuilder();
            sb.AppendLine($"ClientSize.Width:{ClientSize.Width}");
            sb.AppendLine($"ClientSize.Height:{ClientSize.Height}");
            sb.AppendLine($"this.Width:{Width}");
            sb.AppendLine($"this.Height:{Height}");
            sb.AppendLine();
            txt.Text = sb.ToString();
        }

         public void Button_Clicked(object sender, RoutedEventArgs e)
        {
            MainWindow_Opened(null, null);
        }
```
### Opened Event - Result (Linux vs Windows):
![image](https://user-images.githubusercontent.com/14368203/74387308-1a7b4f00-4df0-11ea-8391-b56753d698bc.png)
### After clicking refresh - Result (Linux only)
![image](https://user-images.githubusercontent.com/14368203/74387418-629a7180-4df0-11ea-8186-43c95dcbb539.png)

**Comment by kekekeks** [comment]
Note: X11 protocol is *asynchronous*. Most likely some part of our code assumes that stuff like size and position will be applied immediately while it wont. We already have huge auto-sizing issues because of that.

**Comment by Symbai** [comment]
This issue also affects SizeToContent to not work correctly. Both makes simulating a messagebox really annoying on Linux. It always shows up at the top left corner and needs to be resized by the user.

Is there a quick workaround possible? Perhaps waiting for X11 to be finished and then resize / apply startup location?!

**Comment by kekekeks** [comment]
>Perhaps waiting for X11 to be finished

The configure event *might not come at all* in case of a tiling window manager that ignores configure requests from the application. Assuming that window will be resized after Resize call is an error.

**Comment by kekekeks** [comment]
E. g. event sequence on a display without a window manager (from `xev`, irrelevant events removed):
```
$ DISPLAY=:8 xev 
Outer window is 0x200001, inner window is 0x200002

CreateNotify event, serial 11, synthetic NO, window 0x200001,
    parent 0x200001, window 0x200002, (10,10), width 50, height 50
border_width 4, override NO

MapNotify event, serial 15, synthetic NO, window 0x200001,
    event 0x200001, window 0x200002, override NO

MapNotify event, serial 16, synthetic NO, window 0x200001,
    event 0x200001, window 0x200001, override NO

VisibilityNotify event, serial 16, synthetic NO, window 0x200001,
    state VisibilityUnobscured

Expose event, serial 16, synthetic NO, window 0x200001,
    (0,0), width 178, height 10, count 3

Expose event, serial 16, synthetic NO, window 0x200001,
    (0,10), width 10, height 58, count 2

Expose event, serial 16, synthetic NO, window 0x200001,
    (68,10), width 110, height 58, count 1

Expose event, serial 16, synthetic NO, window 0x200001,
    (0,68), width 178, height 110, count 0
```

As you can see, we are only getting `CreateNotify` here.

Event sequence from `xev` running with KWin:

```
$ xev
Outer window is 0xee00001, inner window is 0xee00002

CreateNotify event, serial 11, synthetic NO, window 0xee00001,
    parent 0xee00001, window 0xee00002, (10,10), width 50, height 50
border_width 4, override NO

MapNotify event, serial 15, synthetic NO, window 0xee00001,
    event 0xee00001, window 0xee00002, override NO

ConfigureNotify event, serial 29, synthetic NO, window 0xee00001,
    event 0xee00001, window 0xee00001, (0,0), width 178, height 178,
    border_width 0, above 0x2a00021, override NO

ReparentNotify event, serial 29, synthetic NO, window 0xee00001,
    event 0xee00001, window 0xee00001, parent 0x187af65,
    (0,0), override NO

PropertyNotify event, serial 29, synthetic NO, window 0xee00001,
    atom 0x182 (_NET_WM_STATE), time 266535458, state PropertyNewValue

MapNotify event, serial 29, synthetic NO, window 0xee00001,
    event 0xee00001, window 0xee00001, override NO

VisibilityNotify event, serial 29, synthetic NO, window 0xee00001,
    state VisibilityPartiallyObscured

Expose event, serial 29, synthetic NO, window 0xee00001,
    (0,0), width 1, height 1, count 0
```

With KWin we are getting `ConfigureNotify` that comes *after* MapNotify event, that indicates that window is getting resized by the window manager after it was shown. That might be or might not be the case depending on the environment.

Keep in mind that those events are being read from the X11 display connection *way after* you've called `Show`. There are no events that are triggered during `Show` method execution.

Also keep in mind that all windows share the same X11 display connection, so any attempts to wait for an event for a particular window might execute event handlers from other windows which isn't something that we want during the `Window.Show` call.

**Comment by Symbai** [comment]
So you're saying it is impossible to fix?

**Comment by Gillibald** [comment]
Why is the window created with the calculated default dimensions instead of using the initial DesiredSize?

**Comment by kekekeks** [comment]
@Gillibald 
1) The first layout pass happens after IWindowImpl is created. 
2) It's a good practice to use default dimensions for sizeable windows. Our win32 implementation also uses CW_USEDEFAULT as initial window size.

@Symbai We might attempt to additionally call XConfigureWindow, so window manager *might* recognize it as initial size/position request. However, window manager is free to do whatever it wants. It needs further investigation.

**Comment by Gillibald** [comment]
Hmm. I don't see why you would want to have an extra resize if you can ideally live with the initially created surface. By specifying `MaxHeight` `MaxWidth` `Width` `Height` before the window is created you could avoid extra work if the window manager fulfills your requested dimensions. Default dimensions should only be calculated/used when none of the above-mentioned properties are set.

**Comment by kekekeks** [comment]
@Symbai 
>We might attempt to additionally call XConfigureWindow, so window manager might recognize it as initial size/position request.

This seems to be the case.  I've written a simple program and calling XConfigureWindow before XMapWindow makes KWin to respect initial window dimensions.

```cs

    public static void Main()
    {
        var disp = XOpenDisplay(null);
        var win = XCreateSimpleWindow(disp, XDefaultRootWindow(disp), 10, 10, 50, 50,
            1, IntPtr.Zero, IntPtr.Zero);
        
        void MoveResize(int x, int y, int width, int height)
        {
            var changes = new XWindowChanges()
            {
                width = width, height = height, x = x, y = y
            };
            XConfigureWindow(disp, win,
                ChangeWindowFlags.CWHeight | ChangeWindowFlags.CWWidth | ChangeWindowFlags.CWX | ChangeWindowFlags.CWY,
                ref changes);
        }
        // Commenting the line above makes KWin to ignore initial dimensions
        MoveResize(10, 10, 50, 50);
        XSelectInput(disp, win, new IntPtr(0xffffff));
        XMapWindow(disp, win);
        

        while (XNextEvent(disp, out var ev) == IntPtr.Zero)
        {
            if(ev.AnyEvent.type==XEventName.MapNotify)
                Console.WriteLine("MapNotify");
            if (ev.AnyEvent.type == XEventName.ConfigureNotify)
            {
                Console.WriteLine($"ConfigureNotify X: {ev.ConfigureEvent.x} Y: {ev.ConfigureEvent.y} Width: {ev.ConfigureEvent.width} Height: {ev.ConfigureEvent.height}");
            }

            if (ev.AnyEvent.type == XEventName.ButtonPress)
            {
                Console.WriteLine("Attempting to resize");
                MoveResize(50, 50, 400, 400);
            }
        }

    }
```

However when running with i3 window manager the initial size is ignored. We can't even resize the window by calling XConfigureWindow from the button press handler: these calls are simply ignored and no ConfigureNotify events are generated.

**Comment by kekekeks** [comment]
@Gillibald we first create the window with default dimensions because we don't have any info about desired window size at that point. The first layout pass [happens inside Show](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Window.cs#L408) call. 

IWindowImpl::Resize is being called during the layout pass by [Window.ArrangeOverride](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Window.cs#L281). `ClientSize` isn't updated immediately because there is not guarantee that said resize request would have any effect at all, window manager is free to ignore our resize requests completely. So we can't assume that the window has the requested size from `X11Window.Resize`, the size (or might not) applied at some point in the future.


Our current layout system is simply broken with asynchronous display server protocols, I can't do anything about that from the backend code, sorry.

**Comment by kekekeks** [comment]
A possible hack would be to update the client size immediately if the window is currently offscreen. 
We can do that because window manager will send a ConfigureNotify after the window is mapped again (at least that seems to be the case for window managers I'm running my tests with), so our client size will *eventually* become in sync with the actual size.

**Comment by grokys** [comment]
How could we change the layout system such that it worked better for asynchronous display servers?

**Comment by kekekeks** [comment]
1) layout attempts to call `IWindowImpl.Resize` from `ITopLeveImpl.Resized` event handler. It makes no sense in environments where underlying platform is enforcing window size
2) layout assumes that `ITopLevelImpl.Resized` callback would be called from `IWindowImpl.Resize`
3) layout assumes that `ITopLevelImpl.ClientSize` will be changed right away when calling  `IWindowImpl.Resize`
4) layout can't deal with the fact that underlying window system doesn't care about layout's opinions and enforces the window size anyway, which leads to visual artifacts like this:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1067584/76691269-375aaa80-665a-11ea-9886-d731b9fe3b69.png">


Point 4 also bites us in scenarios where we can't resize the viewport at all (e. g. embedding into native views, framebuffer backend, webassembly, etc).

**Comment by kekekeks** [comment]
Our popups work on X11 only thanks to the fact that window managers don't manage popups and allow applications to resize them as they wish. So with popups we are currently emulating the synchronous behavior and set ClientSize and call Resized callback right away. We can't do that for regular windows because such resize requests might be silently ignored by the window system without any rejection notice.

**Comment by kekekeks** [comment]
For now I think we should do

>update the client size immediately if the window has never been onscreen before

hack to mitigate autosizing issues for most X11 systems.

**Comment by danwalmsley** [comment]
Seems this is now fixed: closing.
