### ISSUE TITLE
WPF ContentPresenter has ContentSource - What is Equivalent in Avalonia?

### ISSUE THREAD

**Issue by srl17** [AvaloniaUI/Avalonia#3562]
Trying out this project. Looks very promising and phenomenal work so far.  
On WPF I have some Tab Control and Tab Item Styles I am trying to convert over.  It crashes the previewer, which I am assuming is the universal sign for bad XAML.  The error message mentions PART_ItemsPresenter.  I figure if I can get these styles to work I can figure out most of the differences.

What would be the equivalent Avalonia line for 
`<ContentPresenter ContentSource="SelectedContent"/>`
from the below section?

Is their an equivalent within my stackpanel for IsItemsHost="true" 

Is there equivalency for <ControlTemplate.Triggers> such as for a "IsMouseOver" property.

```xml
   <!-- TabControl style -->
      <Style Selector="TabControl.h1">
         <Setter Property="BorderThickness" Value="5"/>
         <Setter Property="Template">
            <Setter.Value>
               <ControlTemplate>
                  <Grid>
                     <Grid.RowDefinitions>
                        <RowDefinition Height="Auto"/>
                        <RowDefinition Height="*"/>
                     </Grid.RowDefinitions>
                     <Border Grid.Row="1" BorderThickness="2,0,2,2" ZIndex="2" CornerRadius="0,0,2,2"
                                   BorderBrush="Silver"
                                   Background="Gray">
                        <ContentPresenter ContentSource="SelectedContent"/>
                     </Border>
                     <StackPanel Orientation="Horizontal" Grid.Row="0" ZIndex="1" IsItemsHost="true" />
                     <Rectangle Grid.Row="0" Height="2" VerticalAlignment="Bottom"
                                      Fill="Silver"/>
                  </Grid>
               </ControlTemplate>
            </Setter.Value>
         </Setter>
      </Style>
```

**Comment by kekekeks** [comment]
> `<ContentPresenter ContentSource="SelectedContent"/>`

`Content="{TemplateBinding SelectedContent}"`

> Is there equivalency for <ControlTemplate.Triggers> such as for a "IsMouseOver" property.

There is a `:pointerover` [pseudo-class](http://avaloniaui.net/docs/styles/selectors#class)

> Is their an equivalent within my stackpanel for IsItemsHost="true"

I don't think that we have such marker property. The default [TabControl template](https://github.com/AvaloniaUI/Avalonia/blob/9e7014805ef5c72e165a951bf6d714ed8aad7f98/src/Avalonia.Themes.Default/TabControl.xaml#L13) has an ItemsPresenter that, in turn, displays the panel:

```
<ItemsPresenter
  Name="PART_ItemsPresenter"
  Items="{TemplateBinding Items}"
  ItemsPanel="{TemplateBinding ItemsPanel}"
  ItemTemplate="{TemplateBinding ItemTemplate}">
</ItemsPresenter>
```

That missing template part is causing your PART_ItemsPresenter error message.

The general recommendation with templating is to take a look at [our default theme](https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.Themes.Default) first and see how default styles are implementd.

**Comment by srl17** [comment]
Awesome! Those default themes are very helpful. When trying to solve this problem initially I was looking for the default templates; similar to what I would extract using Blend for modifying WPF controls.  I just wasn't looking in the correct place.  I am porting my GUI application over from WPF and it is going very well.  This appears to be a great package, with a LOT of good work and effort put into it!

Consider placing that link to `https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.Themes.Default`
within the pages
`https://avaloniaui.net/docs/quickstart/from-wpf` and `https://avaloniaui.net/docs/styles/styles`
