### ISSUE TITLE
Min/Max height and width for managed FileDialogs

### ISSUE THREAD

**Issue by AmirMahdiNassiri** [AvaloniaUI/Avalonia#3566]
Hello, I am using the newest 0.9.3 package, which I found it amazing. 

The new managed FileDialogs functionality is awesome! Thanks for all your efforts. It's really cumbersome to implement all those dialogs in each project, but thanks to you guys, we don't need to do it ourselves.

Just one improvement that I personally need is to be able to set some template related properties, such as Min/Max height and width for the dialogs. I know that we are able to use our completely customized template by passing the type to the UseManagedSystemDialogs function, but as a matter of fact, your implemented template is awesome and I like it. But I need to set Min/Max sizes for the dialog so they can not shrink into just the window chrome buttons.

Do you guys think it is possible to expose some of this template related properties for us to set?

Once again, thank you so much for all your great efforts.

**Comment by maxkatz6** [comment]
With 11.0 managed file dialog now uses template styles, and it should be easier to style it outside.
Not to mention, even previously it was possible to setup managed file dialog with custom Window type, and defined custom window logic inside.
