### ISSUE TITLE
Managed SaveFileDialog selected FileDialogFilter can not be retrieved

### ISSUE THREAD

**Issue by AmirMahdiNassiri** [AvaloniaUI/Avalonia#3567]
Hello, 

First of all, I have to thank all of you guys for your amazing project and all the support.

I am using the newest 0.9.3 package and leveraging the new managed SaveFileDialog in order to export user data in their desired target format. I used two FileDialogFilter to give the user the options to save their data as an Excel file, or as a CSV text file.

 Sample source code:

    var textFileFilter = new FileDialogFilter { Name = "Comma separated text file" };
    textFileFilter.Extensions = new List<string> { "txt" };

    var excelFileFilter = new FileDialogFilter { Name = "Excel file" };
    excelFileFilter.Extensions = new List<string> { "xlsx" };

    var dialog = new SaveFileDialog
    {
        Title = "Choose the location to save",
        InitialFileName = Name,
        Filters = new List<FileDialogFilter> { textFileFilter, excelFileFilter }
    };
    
    string dialogResult = await dialog.ShowAsync(App.MainWindow);

But the problem is that the resulting dialogResult would not contain the file extension that the user has chosen inside the dialog. So I am not able to identify which file format should I export the data as. This issue was firstly posted as #229, but back then there were no managed FileDialogs.

Is there any possible way of retrieving the selected file extension that I am not aware of?

Thank you so much for all your great efforts!

**Comment by kekekeks** [comment]
@danwalmsley TL;DR: when user tries to save a file and types 'foo' as a file name, the managed dialog doesn't append an extension from the current file filter.
