### ISSUE TITLE
Support from loading bitmap from resources in XAML

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#358]
Currently it [always tries](https://github.com/Perspex/Perspex/blob/708b10544fe00a43af50ecec1bd3b57e439e50e2/src/Markup/Perspex.Markup.Xaml/Converters/BitmapTypeConverter.cs#L25) to load bitmap from file instead of using AssetLoader

Blocked by #282

**Comment by kekekeks** [comment]
We should load from current assembly by default, so I'm reopening the issue.

**Comment by grokys** [comment]
Loading from current assembly should be relative to the assembly in which the XAML file resides, right? If so, this will require support from OmniXAML to pass the URL of the XAML file being parsed to the TypeConverter.

**Comment by kekekeks** [comment]
We can keep it in some thread-static variable. Seems to be a decent solution for keeping ambient state like that.

**Comment by grokys** [comment]
I don't think that would work, as:

1. Often loading a XAML file results in another XAML file getting read (e.g. UserControl)
2. Templates can cause assets to be looked up at any point after the XAML has been loaded

I think we need a solution in OmniXAML to associate a URL etc with each XAML file - this would also be helpful for error messages, as currently it's not clear which file caused an exception to be thrown.

**Comment by grokys** [comment]
Should now work.
