### ISSUE TITLE
ItemsControl - Items out of order when Equals is overridden

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#3580]
When `Equals` is overridden DataGrid/ListBox etc shows wrong items on scrolling (doesn't matter how the user scrolls). This differs from WPF and is a breaking bug when porting applications. Related #3425 

### XAML
```
<DataGrid
  Items="{Binding WindowBla}">
  <DataGrid.Columns>
    <DataGridTextColumn
        Width="1*"
        Binding="{Binding MyColumn}"
        Header="Column 1" />
  </DataGrid.Columns>
</DataGrid>
----------------------------------------------------------
<ListBox
  Items="{Binding WindowBla}">
  <ListBox.ItemTemplate>
    <DataTemplate>
      <TextBlock
        Text="{Binding MyColumn}" />
    </DataTemplate>
  </ListBox.ItemTemplate>
</ListBox>
```
### C#
```
    public ObservableCollection<Abc> WindowBla { get; set; } = new ObservableCollection<Abc>();

    public MainWindowViewModel()
    {
        for (int i = 0; i < 200; i++)
        {
            WindowBla.Add(new Abc(i));
        }
    }

    public class Abc
    {
        private int Bla = 0;
        public Abc(int i) => MyColumn = i.ToString();
        public string MyColumn { get; }
        public override bool Equals(object? obj) => Bla == ((Abc)obj).Bla;
    }
```

## DataGrid
Shows items completely out of order.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14368203/74604735-8b548c80-50b8-11ea-82eb-6d70e6cb1cd8.gif)

## ListBox (same C# code)
Differs from DataGrid behavior as items are not out of order but repeating themselves. Those who were visible on start are being shown again over and over.

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/14368203/74604850-c0adaa00-50b9-11ea-8d05-c0d069b872bb.gif)

**Comment by grokys** [comment]
Looks like WPF uses `Object.Equals` for `string` and value types, and for other types uses `ReferenceEquals` where Avalonia uses `EqualityComparer<T>.Default.Equals` for all values.

We should perhaps look into using `ReferenceEqualityComparer` instead, though that's .NET 5+ only and it's not clear from the docs how it handles value types.
