### ISSUE TITLE
Types conversion in Binding: Binding to TimeSpan: "Could not convert '00:00:10' to 'TimeSpan'." 

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#3584]
Not sure whether it bug or feature.

MCVE:
```xaml
<TextBox Text="{Binding TimeSpan}" />
```
```cs
public TimeSpan TimeSpan { get; set; } = TimeSpan.FromSeconds(10);
```

produces the next error:

```
[Binding] Error in binding to "Avalonia.Controls.TextBox"."Text": "Could not convert '00:00:00' to 'TimeSpan'." (Avalonia.Controls.TextBox #13256970)
```

***Version***: 0.9.3

***Additional info***: 

works fine for TextBlock in Avalonia

works fine in WPF both for TextBox and TextBlock

**Comment by grokys** [comment]
Seems that `TypeUtilities.TryConvert` doesn't try to use `TypeConverter`s, will fix.
