### ISSUE TITLE
Missing package "System.Net.Ping"

### ISSUE THREAD

**Issue by JesterX666** [AvaloniaUI/Avalonia#3587]
Our application uses Avalonia but it seems that it's missing some packages on some installations.

Most of our installations work fine but some have that exception:

Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Ping, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Net.Ping, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at UnitystationLauncher.Models.ServerWrapper..ctor(Server server, AuthManager authManager, InstallationManager installManager)
   at UnitystationLauncher.Models.ServerManager.RefreshServerList()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b139_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>cDisplayClass5_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at UnitystationLauncher.Program.Main(String[] args)

**Comment by MonkAlex** [comment]
>UnitystationLauncher.Models.ServerManager.RefreshServerList

So, why u think its Avalonia bug?

**Comment by DooblyNoobly** [comment]
@MonkAlex
 
Because the app fails to start at all randomly. Like it will work fine for a week then one day it will just refuse to launch. Happens on win and osx. Its like the bundled runtime just decides it will give up for some weird reason. This is the only log we have been able to get from the app.

**Comment by DooblyNoobly** [comment]
@MonkAlex this is the problem: `Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Ping, `

**Comment by DooblyNoobly** [comment]
this is on avalonia 0.9.2

**Comment by Gillibald** [comment]
This has nothing to do with Avalonia. This is a problem in your code.

**Comment by DooblyNoobly** [comment]
btw here is the output on mac:
```
machine:~ user$ /Applications/StationHub ; exit;
Error:
  An assembly specified in the application dependencies manifest (StationHub.deps.json) was not found:
    package: 'Avalonia.Direct2D1', version: '0.9.2'
    path: 'lib/netstandard2.0/Avalonia.Direct2D1.dll'
logout
```

**Comment by Gillibald** [comment]
`Avalonia.Direct2D1` is Windows only. Pls show us your AppBuilder

**Comment by DooblyNoobly** [comment]
![image](https://user-images.githubusercontent.com/20813925/74810941-30cb6280-533c-11ea-9dd9-cbe943d4d044.png)

**Comment by Gillibald** [comment]
How do you publish the app?

**Comment by DooblyNoobly** [comment]
using dotnet publish. here is the command I use: `dotnet publish /p:Configuration=ReleaseWIN64 /p:Platform="x64" -r win10-x64 /p:PublishSingleFile=true`

**Comment by Gillibald** [comment]
And for Mac? This is targeting Windows.

**Comment by DooblyNoobly** [comment]
Mac: `dotnet publish /p:Configuration=ReleasePOSIX64 /p:Platform="x64" -r osx-x64 /p:PublishSingleFile=true`

**Comment by Gillibald** [comment]
Might be good to know what version of the runtime is installed on the system that show this error.

**Comment by Gillibald** [comment]
https://apisof.net/catalog/System.Net.NetworkInformation

**Comment by kekekeks** [comment]
>PublishSingleFile

Don't use it. It's broken by design. It can and will cause issues on various machines.

**Comment by DooblyNoobly** [comment]
@kekekeks yikes I had suspicions 

@Gillibald I know it has happened on this windows machine I am on and runtime version is: 4.0.30319.42000

**Comment by kekekeks** [comment]
```


machine:~ user$ /Applications/StationHub ; exit;
Error:
  An assembly specified in the application dependencies manifest (StationHub.deps.json) was not found:
    package: 'Avalonia.Direct2D1', version: '0.9.2'
    path: 'lib/netstandard2.0/Avalonia.Direct2D1.dll'
logout
```

This message suggests that you've tried to remove a dll referenced from your deps.json. That won't work with .NET Core.

If you want to trim the installation size, remove the reference to `Avalonia.Desktop` and reference `Avalonia.Skia` + `Avalonia.Win32`/`Avalonia.X11`/`Avalonia.Native` based on the target platform and call `UseSkia`, `UseWin32`/`UseX11`/`UseAvaloniaNative` directly.

**Comment by DooblyNoobly** [comment]
if there was any stripping then it wasn't on purpose

**Comment by DooblyNoobly** [comment]
I'm going to test a build with `/p:PublishSingleFile=false` already it has solved another mystery bug I was experiencing on win10
