### ISSUE TITLE
Nested Style Selectors

### ISSUE THREAD

**Issue by sards3** [AvaloniaUI/Avalonia#3593]
It would be nice if we could do something like this:

```xml
<Style Selector=".SomeClass">
  <Style Selector="TextBlock#SomeText">
    <Setter Property="IsVisible" Value="False" />
  </Style>
  <Style Selector="StackPanel#SomeStackPanel">
    <Setter Property="Background" Value="Red" />
  </Style>
</Style>
```

This would allow better organized styles by logically grouping related selectors. This is similar to how LESS and SASS allow nested selectors to improve on plain CSS.

**Comment by kekekeks** [comment]
How exactly should that work. Should `TextBlock#SomeText` be treated as `.SomeClass > TextBlock#SomeText` or `.SomeClass TextBlock#SomeText`?

**Comment by sards3** [comment]
Probably `.SomeClass TextBlock#SomeText`.  Then another possibility would be:

```xml
<Style Selector=".SomeClass">
  <!-- Next line is equivalent to: .SomeClass TextBlock#SomeText  -->
  <Style Selector="TextBlock#SomeText">
    <Setter Property="IsVisible" Value="False" />
  </Style>
  <!-- Next line is equivalent to: .SomeClass > StackPanel#SomeStackPanel. Note the > at the start. -->
  <Style Selector="> StackPanel#SomeStackPanel">
    <Setter Property="Background" Value="Red" />
  </Style>
  <!-- If we want to get fancy, we could also follow LESS/SASS by using & as the parent selector, like so: -->
  <!-- Next line is equivalent to: .SomeClass.AnotherClass -->
  <Style Selector="&.AnotherClass">
    <Setter Property="Background" Value="Blue" />
  </Style>
</Style>
```

**Comment by kekekeks** [comment]
Looks like something that we could implement via AST transform by concatenating selectors and flattening the hierarchy right before `AvaloniaXamlIlSelectorTransformer` and `AvaloniaXamlIlSetterTransformer`. So your example would get converted to 
```xml
<Style Selector=".SomeClass TextBlock#SomeText">
  <Setter Property="IsVisible" Value="False" />
</Style>
<Style Selector=".SomeClass > StackPanel#SomeStackPanel">
  <Setter Property="Background" Value="Red" />
</Style>
<Style Selector=".SomeClass.AnotherClass">
  <Setter Property="Background" Value="Blue" />
</Style>

```

The question is, how should we treat something like this:
```xml
<Style Selector="Border.SomeClass">
  <Setter Property="Background" Value="Red"/>
  <Style Selector="TextBlock#SomeText">
    <Setter Property="IsVisible" Value="False" />
  </Style>
  <Setter Property="BorderBrush" Value="Blue" />
</Style>
```

Should we split the root selector into two? So it would get converted to:

```xml
<Style Selector="Border.SomeClass">
  <Setter Property="Background" Value="Red"/>
</Style>
<Style Selector="Border.SomeClass TextBlock#SomeText">
  <Setter Property="IsVisible" Value="False" />
</Style>
<Style Selector="Border.SomeClass">
  <Setter Property="BorderBrush" Value="Blue" />
</Style>
```

@grokys

**Comment by grokys** [comment]
Yeah i think this might be nice. I'm currently refactoring styling a little bit and I'll bear this in mind. Can't guarantee how soon it'd be implemented, but i'll definitely design with this in mind.

**Comment by kekekeks** [comment]
@grokys it could be implemented entirely on compiler level since it's essentially preprocessing.

**Comment by grokys** [comment]
Yeah, I'm not sure which would be the best way to do it right now.

**Comment by grokys** [comment]
Thinking about this - i think the main advantage of building it into the styling system would be that listeners would have to be subscribed only once for a parent selector.

Following the syntax for https://drafts.csswg.org/css-nesting-1/ would be a good idea I think, except that it uses `&` to refer to the parent selector, which would have to be written `&amp;` in XML. Are we OK with that? Or should we choose an alternative syntax?

**Comment by robloo** [comment]
This is complete now, correct?
