### ISSUE TITLE
Add StackPanel scroll support

### ISSUE THREAD

**Issue by amerkoleci** [AvaloniaUI/Avalonia#36]
WPF StackPanel implements IScrollInfo thus when the user press PageDown, PageUp the content scrolls by one, need to 
add some sort of scroll content to ScrollViewer, this is handled by IScrollInfo in WPF.

**Comment by grokys** [comment]
Yes, this is definitely needed. A good place to start would be the WPF IScrollInfo but we should maybe see if we can simplify it - it has 16 methods/properties which is rather a lot!

**Comment by ncarrillo** [comment]
The API surface for IScrollInfo has been defined with #122

**Comment by grokys** [comment]
Implemented.
