### ISSUE TITLE
DataGrid doesn't handle NotifyCollectionChangedAction.Move

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#3606]
Avalonia 0.9.3
I have a DataGrid bound to a sorted ReadOnlyObservableCollection.
```
_dataGrid.Items = new DataGridCollectionView(ViewModel.Items, true, true);
```
The DataGrid does not display the data sorted correctly as the ```DataGridCollectionView.ProcessCollectionChanged``` method does not process NotifyCollectionChangedAction.Move actions.

**Comment by maxkatz6** [comment]
This issue is older, but I will close it in a favor of more detailed one: https://github.com/AvaloniaUI/Avalonia/issues/13621
