### ISSUE TITLE
MenuItem -> hold mouse down and select item without clicking again

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/Avalonia#3609]
Right now, `Menu/MenuItem` forces you to click once to open the menu, then click again to select an item. In regular WPF/Windows software, you can click and hold your mouse down, then release when you get to the menu option that you want to select.

My request is to adjust the menu functionality such that we can hold the mouse down and only mouse up when we're on the item we want to select. This should make menus act more like other Windows/WPF software.

Doing this might (?) fix an issue where you mouse down on a `MenuItem`, move off of it with your mouse, and then mouse up (anywhere at this point) causes that menu item to be selected anyway, so there's no way to "back out" of selecting a menu item once you've mouse down'ed on it.

**Comment by grokys** [comment]
Huh, in all my time using Windows I've never noticed you can use menus like that. Yeah we should do this.
