### ISSUE TITLE
How to render faster than 10 FPS

### ISSUE THREAD

**Issue by define-private-public** [AvaloniaUI/Avalonia#3611]
I'm working on making some small Avalonia sample apps (to learn the framework for a larger app I want to make).  I finished up building a analogue clock.  I couldn't help but notice that rendering is capped at 10 FPS.  Is there a way to increase this framerate?  I know that SkiaSharp can at least to 60 FPS.

Sample in question:
https://gitlab.com/define-private-public/AvaloniaSamples/-/tree/master/AnalogueClock

**Comment by kekekeks** [comment]
You are using a 100ms timer interval - https://gitlab.com/define-private-public/AvaloniaSamples/-/blob/59f51e20a9a39fa34b5d70e43cc99fb433c45b32/AnalogueClock/ViewModels/ClockViewModel.cs#L15
That's 10 times per second.

**Comment by define-private-public** [comment]
AGH!! I'm dumb, I can't read my own code...

(Thank you very much.  Changing the timer 100x a second yields an FPS of 100ish).
