### ISSUE TITLE
[0.9.3] [Mac OS] EXC_CRASH (SIGABRT) when calling Window.Close while starting

### ISSUE THREAD

**Issue by garyhertel** [AvaloniaUI/Avalonia#3612]
I'm trying to use Avalonia as a GUI Launcher app that retrieves the correct version and starts another Avalonia app. However, I've noticed that if I try closing the Window too soon, the app will crash on Mac OS (Windows shows no such problem). The Launcher will generally only prompt the user if there's a new version available so most of the time will start the main app and exit immediately.

I've tried adding a 1 second delay, but even this isn't enough sometimes for slower computers.

This is what I'm using to close the window. Maybe there's a better way?

`Dispatcher.UIThread.Post(Close);`

Here's the delay workaround as well:

```
		private void ScheduleCloseWindow()
		{
			if (Environment.OSVersion.Platform == PlatformID.Win32NT)
				CloseWindow();
			else
				DelayCloseWindow(); // delay closing on Mac until Opened since the app Segfaults otherwise
		}

		private void CloseWindow()
		{
#if !DEBUG
			Dispatcher.UIThread.Post(Close);
#endif
		}
		
		// delays close on Mac to avoid a segfault when posting Close
		private DispatcherTimer dispatcherTimer;

		private void DelayCloseWindow()
		{
			if (dispatcherTimer == null)
			{
				dispatcherTimer = new DispatcherTimer();
				dispatcherTimer.Interval = new TimeSpan(0, 0, 1);
				dispatcherTimer.Tick += DispatcherTimer_Tick;
				dispatcherTimer.Start();
			}
		}
```

```
Process:               TestApp [77051]
Path:                  /Applications/TestApp.app/Contents/MacOS/TestApp
Identifier:            TestApp
Version:               1.0 (0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           TestApp [77051]
User ID:               1283372252Date/Time:             2020-02-25 16:26:01.776 -0800
OS Version:            Mac OS X 10.14.6 (18G3020)
Report Version:        12
Bridge OS Version:     3.0 (14Y906)
Anonymous UUID:        75E54B8D-41AA-5366-91FC-0E92CD427E69Sleep/Wake UUID:       60E588C4-0BFA-4871-AEA8-E4FE0CCB4863Time Awake Since Boot: 26000 seconds
Time Since Wake:       8700 secondsSystem Integrity Protection: enabledCrashed Thread:        0  Dispatch queue: com.apple.main-threadException Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFYApplication Specific Information:
abort() called
```

**Comment by kekekeks** [comment]
Please, show the stack trace (from Environment.StackTrace) right before you are calling Close. 


There are certain native-to-managed callbacks where closing the window will segfault. 
Notably, it's not advised to close things from dispatcher callbacks with priority higher than Render since those might be called from `NSView:updateLayer` callback. Closing the window in said callback will result in a crash.


We should probably implement delayed closing logic in Avalonia itself.

**Comment by garyhertel** [comment]
Thanks for the tips! I was able to fix this and remove that delay by changing the DispatcherPriority. Feel free to close this issue. Here's what I ended up with.

```csharp
public LauncherWindow() : base()
{
    InitializeComponent();
    Opened += OnOpened;
}

private void OnOpened(object sender, EventArgs e)
{
    Dispatcher.UIThread.Post(Initialize, DispatcherPriority.Background);
}

private void Initialize()
{
    // do stuff
    CloseWindow();
}

private void CloseWindow()
{
    Dispatcher.UIThread.Post(Close, DispatcherPriority.ContextIdle);
}
```
