### ISSUE TITLE
The program I generated didn't respond when I click it.

### ISSUE THREAD

**Issue by zzl4883a** [AvaloniaUI/Avalonia#3615]
Software  operating environment: Ubuntu18 64bit
The .net core 3.0 SDK is installed on the Ubuntu
VS2019 generate configuration: 
    Target runtime:linux-x64
    Deployment patterns:independence
    Target framework:netcoreapp3.0

Problem:
I use visualstudio2019(on windows system) publish an app,then I copy the generated application onto the Ubuntu.I use mouse right click to set the  properties "Allows to execute as a program file".Then I use mouse to double click my generated application, my application didn't respond at all.
So, what should I do when I want to run my application on Ubuntu ? Thanks~

**Comment by kekekeks** [comment]
Try running from the terminal. It should output somewhat meaningful error messages.

**Comment by zzl4883a** [comment]
Thanks a lot!
Maybe I copy wrong file onto Ubuntu,now my program can run normally on Ubuntu.
I have some other systematic questions to solve:
1.I try it on CentOS ,the terminal shows nothing,my application didn't respond at all.
2.Programs also can't run on debian(based on raspbian 3b+,Target runtime:linux-arm)

**Comment by jwcone** [comment]
I'm having similar behavior on Arch Linux. Running from the shell displays nothing, just exits and gives me the shell prompt again. However, it seems that the process is dumping core. The process terminated with a SIGSEGV (segmentation fault) from libSkiaSharp.so.

**Comment by jwcone** [comment]
Saw this is still open and wanted to add I that I no longer experience the issue since updating to 0.9.10.
