### ISSUE TITLE
Add IsDirectionReversed to Slider

### ISSUE THREAD

**Issue by define-private-public** [AvaloniaUI/Avalonia#3617]
I'm working on porting toy app that was made in GtkSharp over to Avalonia.  It was a mini-music player that included a volume slider (which went from 0 to 100).  I was able to create a vertical `Slider`, with the range that i wanted, but I noticed that when the slider is at `100`, the thumb is at the bottom, where as when it's value is at `0` the thumb is at the top.

I tried looking through the Avalonia docs, but I couldn't find anything to flip this direction.  I've never done any XAML programming before, but some googling reveals that there is a property to change this on their `Slider`: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.slider.isdirectionreversed#Windows_UI_Xaml_Controls_Slider_IsDirectionReversed

**Comment by JamRemco** [comment]
Yea thats pretty weird. I've never seen a fader moving down for more valume.
I tried to trick the slider to iverse the the values .. swappig the min and max values,
but that doesn't works either.
There's probebly some logic (MinMax) that prevents that.
Now i am stuck with a fader that works upside down  haha
![image](https://user-images.githubusercontent.com/58340108/80657013-cf81e700-8a82-11ea-9ba2-46f81a2ae3d7.png)

Regards
