### ISSUE TITLE
Use Remote Image

### ISSUE THREAD

**Issue by furesoft** [AvaloniaUI/Avalonia#3620]
How can I use a Remote Image in Avalonia?

**Comment by MarchingCube** [comment]
For others that stumble upon this question. After quick investigation I guess you mean using our `Image` in a way similar to WPF (https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.image.source?view=netframework-4.8) and providing web based `UriSource` ?

And I think the answer here is - no. You can create `Bitmap` from a stream, so probably this would be a good initial solution.

**Comment by MikeCodesDotNET** [comment]
Good example [here](https://github.com/AvaloniaUI/AvaloniaUI.QuickGuides/tree/main/LoadingImages)
