### ISSUE TITLE
Slow closing app on Windows

### ISSUE THREAD

**Issue by MonkAlex** [AvaloniaUI/Avalonia#3622]
Have app with ListBox as presenter with 1k elements.
ListBox with disabled virtualization, because i want this behavior and use WrapPanel as ItemsPanel:
![img](https://user-images.githubusercontent.com/6784764/75613140-950fd280-5b43-11ea-9670-0e58f764f35e.png)

When i close single window of app, my Win7-Win10 "locked" - i cant use any mouse\keyboard actions.
I profile closing:
![img](https://user-images.githubusercontent.com/6784764/75613174-0b143980-5b44-11ea-8ef0-4deb4b6e3350.png)

As @grokys say, stacktrace related with #3282 changes.
So, for fastfix this i change `lifetime.Shutdown()` to `Environment.Exit(0)`, but its bug.

PS: as itemtemplate i use simple grid of image and text:
```
          <Border Name="Border" Background="Transparent">
            <Border.ContextMenu>
              <v:ContextMenu DataContext="{Binding $parent[UserControl].DataContext}" Items="{Binding Commands}"/>
            </Border.ContextMenu>
            <i:Interaction.Behaviors>
              <ia:EventTriggerBehavior EventName="DoubleTapped" SourceObject="{Binding #Border}">
                <ia:InvokeCommandAction Command="{Binding $parent[UserControl].DataContext.DefaultCommand}" CommandParameter="{Binding Mode=OneWay}"/>
              </ia:EventTriggerBehavior>
            </i:Interaction.Behaviors>
            <Grid RowDefinitions="12*, Auto, *" Margin="10" Width="150" Height="300">
              <Image Grid.Row="0" Source="{Binding Cover, Converter={x:Static av:BitmapTypeConverter.Instance}}"/>
              <TextBlock Grid.Row="1" Text="{Binding Name}" TextWrapping="Wrap" ToolTip.Tip="{Binding Name}" HorizontalAlignment="Center"/>
              <ProgressBar Grid.Row="2" IsVisible="{Binding !!Downloaded}" 
                           Value="{Binding Downloaded}" Minimum="0" Maximum="100" 
                           MinWidth="40"
                           Foreground="{Binding Downloaded, Converter={x:Static v:DownloadColorConverter.Instance}}"/>
              <TextBlock Grid.Row="2" Text="{Binding Speed}" HorizontalAlignment="Center" VerticalAlignment="Center" />
            </Grid>
          </Border>
```

**Comment by MarchingCube** [comment]
Can you share full performance trace with us? Stack trace in your screenshot cuts of before anything interesting shows up.

And also for your scenario I highly recommend to just use `ItemsRepeater` since it allows for virtualization in such scenario. I am using it to deal with several thousands of items without any performance issues.

**Comment by MonkAlex** [comment]
> And also for your scenario I highly recommend to just use ItemsRepeater since it allows for virtualization in such scenario. I am using it to deal with several thousands of items without any performance issues.

I want select items, `ItemsRepeater` not support selection, as i know. Ask this in [gitter](https://gitter.im/AvaloniaUI/Avalonia?at=5e14c787821b826f5a7f7dce)

[Trace](https://mega.nz/#!q0slnZwb!kyrlQrs9u2uEqgC3c5YKmK4DIMJYueJK7zAJOhMSbgY) created by dottrace 2019.3.1

**Comment by MarchingCube** [comment]
After a quick look - it seems that you are using `ImmediateRenderer` which has issues and has really slow `AddDirty` implementation. Can you try using `DeferredRenderer`?

**Comment by MonkAlex** [comment]
When `UseDeferredRendering = true`, app closing fast, yes.
But with `DeferredRenderer` scrolling ListBox with images not smooth and look bad.

**Comment by MonkAlex** [comment]
Test 0.10.0-preview3 -- fixed.
Thanks =)
