### ISSUE TITLE
Too many items in a Tree - DataGrid

### ISSUE THREAD

**Issue by mameolan** [AvaloniaUI/Avalonia#3624]
Hello,

I tried to have a datagrid with a tree like structure, but somehow the items are duplicated:

![TreeGrid-issue](https://user-images.githubusercontent.com/51226030/75623812-5fec9a00-5bae-11ea-9974-0b7093ca473f.png)

Here is an example project.
[AvaloniaTreeGrid.zip](https://github.com/AvaloniaUI/Avalonia/files/4271633/AvaloniaTreeGrid.zip)

Best regards.

**Comment by Symbai** [comment]
Duplicated items sounds similar to #3580
