### ISSUE TITLE
Logging doesn't work with Avalonia

### ISSUE THREAD

**Issue by andreyshtern** [AvaloniaUI/Avalonia#3629]
`Console.WriteLine()` doesn't work as `Log.Information`
Methods are getting executed, but i don't see any information in Debug console of VS 2019.
What can i do for logging instead?

**Comment by kekekeks** [comment]
`System.Diagnostics.Debug.WriteLine`

Or you can reuse Avalonia's logging infrastructure: http://avaloniaui.net/docs/logging

**Comment by AlexSchuetz** [comment]
> 
> 
> `System.Diagnostics.Debug.WriteLine`
> 
> Or you can reuse Avalonia's logging infrastructure: http://avaloniaui.net/docs/logging

Unfortunately the link is down.

**Comment by maxkatz6** [comment]
https://docs.avaloniaui.net/docs/getting-started/logging-errors-and-warnings
