### ISSUE TITLE
AttachDevTools() not available in cibuild0006174-beta

### ISSUE THREAD

**Issue by Wyvernius** [AvaloniaUI/Avalonia#3634]
As the title says, the AtachDevTools() is not found in the avalonia namespace.
In previous builds this was not an issue.

Also, dont know if its a bug or do i need to reference some other namespace/package.

Offtopic: Chinese/Japanese chars are working nicely!

**Comment by Deadpikle** [comment]
You need to add a reference to `Avalonia.Diagnostics`. See #3462.

**Comment by Wyvernius** [comment]
Thanks!  i overlooked it.
