### ISSUE TITLE
Textbox doesn't focus when placed in popup

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#3639]
When textbox is placed in popup, no focus is given when clicked on it. It behaves similarly to if IsReadOnly = true, as text can still be highlighted but not edited and it still recognizes when the cursor is over the textbox. 
A textbox will work normally if its set as the header to a MenuItem in a Menu or ContextMenu, however. The only special thing I can find within MenuBase is the InteractionHandler, but I don't know if that adds extra logic that allows it to work when a textbox is within a Menu.
I'm trying to create something along the lines of the WinUI Flyout so the popup control is not part of a control template and is generated in code. All other controls (Button, ComboBox, CheckBox, etc) still work as intended.

**Comment by ahopper** [comment]
What platform is this on? I had something similar just on linux https://github.com/AvaloniaUI/Avalonia/issues/3246

**Comment by amwx** [comment]
Happens on both Windows and Linux

**Comment by amwx** [comment]
So I've figure out this occurs with any classes that inherit directly from WindowBase (except Window). I was able to get it working (at least on Windows) by implementing IFocusScope. I'm still relatively new to Avalonia so I don't know if this has any negative effects on popup behavior, but it seems to be the fix.
