### ISSUE TITLE
NumericUpDown doesn't update displaying value properly

### ISSUE THREAD

**Issue by AntonioMaconzi** [AvaloniaUI/Avalonia#3641]
When you try to change value displaying on NumericUpDown control by clicking on arrow buttons, its plays glitched animation of click and doesn't update value until you click on TextBlock related to NumericUpDown

![DEMO](https://i.imgur.com/X6BkzrE.gif)

Avalonia 0.9.999-cibuild0006181-beta | Linux

**Comment by kekekeks** [comment]
@Gillibald might be caused by your text PR

**Comment by Gillibald** [comment]
NumericUpDown is using a TextBox so it shouldn't be effected but I will have a look.

**Comment by Gillibald** [comment]
Fixed. Thanks for reporting.
