### ISSUE TITLE
DataGrid is not virtualized

### ISSUE THREAD

**Issue by stepulya** [AvaloniaUI/Avalonia#3648]
It looks like DataGrid virtualization is not working if parent container is Grid and DataGrid is associated with a Row with Height="*".
It can be reproduced on basic ControlsCatalog\DataGridPage
I just increased DataSource count 20 times, by modifying ControlCatalog.Models.Countries class:

![image](https://user-images.githubusercontent.com/7665967/76089888-ce6c9600-5fba-11ea-80c8-5fbc9f6558b3.png)

After doing this loading time is about 1min and memory allocation >1GB.
If I change Row.Height to constant value everything works as expected.

**Comment by darkcharmander** [comment]
Just linking these two issues together, because they're both describing the exact same problem: #2873
