### ISSUE TITLE
Avalonia Diagnostics output is very noisy

### ISSUE THREAD

**Issue by lostmsu** [AvaloniaUI/Avalonia#3649]
It rarely prints anything relevant to me, but shows up over Debug and Build outputs in many cases.
It should be off by default.
![image](https://user-images.githubusercontent.com/239520/76152812-fb7f7e00-6078-11ea-8eb9-357ce6e660f0.png)

**Comment by maxkatz6** [comment]
Default is warning now https://github.com/AvaloniaUI/Avalonia/blob/7842883961d094e08e9def7f30cf32fd573179c7/src/Avalonia.Controls/LoggingExtensions.cs#L29
