### ISSUE TITLE
Problem with rendering anything on Linux (Manjaro GNOME)

### ISSUE THREAD

**Issue by michalSolarz** [AvaloniaUI/Avalonia#3650]
I've installed AvaloniaUI template following the manual and after generating project I'm not able to start app. It just exists with exit code 0. I've followed the app startup and found that it's probably caused by this line: https://github.com/AvaloniaUI/Avalonia/blob/a65a64ad9d103b46d25b8cdcd99ae0eb69f39c24/src/Skia/Avalonia.Skia/SkiaPlatform.cs#L23

My app is exiting just after reaching it. It is normal that `options.CostomGpuFactory` is null because it occurs in my case? Is it because I'm missing something in configuration?

Here is my Program.cs

```
class Program
    {
        public static void Main(string[] args) => BuildAvaloniaApp()
            .StartWithClassicDesktopLifetime(args);

        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToDebug()
                .UseReactiveUI();
    }
```

**Comment by kekekeks** [comment]
>Manjaro

There were recent reports about  SkiaSharp font-loading issues on Manjaro 19 that are causing a StackOverflowException. Unfortunately we weren't able to reproduce those locally.

**Comment by michalSolarz** [comment]
Where can I find that font-loading piece? I don't see any exception thrown before calling line mentioned in issue. Even there no exception is thrown, the app just stops.

**Comment by kekekeks** [comment]
Please, try running the following code:
```cs
        Console.WriteLine(SKTypeface.Default.FamilyName);
        Console.WriteLine(SKTypeface.FromFamilyName("Sans").FamilyName);
```

**Comment by michalSolarz** [comment]
I receive following output:
```
Bitstream Vera Sans
Bitstream Vera Sans
```

**Comment by kekekeks** [comment]
Mkay, it's a different issue then.

Have you updated to 0.9.3? If you did, please, run [ControlCatalog.NetCore](https://github.com/AvaloniaUI/Avalonia/tree/master/samples/ControlCatalog.NetCore) project from [release/0.9.3](https://github.com/AvaloniaUI/Avalonia/tree/release/0.9.3) branch and check if it works. If it doesn't, please, run it under debugger and try to step through the app initialization process.

>My app is exiting just after reaching it. 

Could you run

**Comment by michalSolarz** [comment]
After updating it to 0.9.3 app launches properly. So I guess that those fixes solved my issue and I could close it now.
Thanks for help.
