### ISSUE TITLE
Animations can cause entire window to become black/transparent

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/Avalonia#3653]
## Development Environment

* Avalonia 0.9.3
* Not using ReactiveUI
* Windows 10 OR macOS 14 (presumably Linux, too, but untested)

## Bug Description

Under certain animation conditions, the entire window will become black or transparent _except_ for where the animation is taking place.

Windows:

![black](https://user-images.githubusercontent.com/5092399/76327035-dc266200-62bf-11ea-8e01-2a320567df55.png)

macOS:

<img width="273" alt="Screen Shot 2020-03-10 at 11 06 59 AM" src="https://user-images.githubusercontent.com/5092399/76327014-d6308100-62bf-11ea-981f-6c8f24894edb.png">

## How to Replicate

Clone https://github.com/Deadpikle/AvaloniaProgressRing/tree/bug/black-screen and start the sample project. The only difference between this branch and `master` is that the animation `PlaybackDirection` was set to `Normal`. I was able to make it happen in other circumstances too, but didn't write down what those were. (sorry!)

Edit: Have updated the sample for a smaller test case -- only one of the circles will animate now.

Thanks!

**Comment by jmacato** [comment]
Okay, i seemed to have pinpointed the issue and it's because of `KeyTime` for some reason. Please use `Cue` for the keyframes for the moment.
