### ISSUE TITLE
TextBlock text wrapping: Sometimes duplicates and leaves characters behind on wrap

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/Avalonia#3654]
## Development Setup

* Avalonia v0.9.999-cibuild0006280-beta (latest as of 2020-03-10 at 1:50 PM EDT)
* .NET Core 3.1 
* Visual Studio 16.4.5
* Windows 10
* Repo: https://github.com/Deadpikle/AvaloniaBugs/tree/master/ItalicTextWrapping

## Bug description

Sometimes, when wrapping, certain characters are left behind on text wrapping and show up in two places. This only seems to happen with the NotoSans-Italic font (in repro project below); with normal font or default Windows font w/Italic `FontStyle`, things wrap properly. 

This is easiest shown by a picture:

![text-wrapping](https://user-images.githubusercontent.com/5092399/76343429-75607300-62d6-11ea-8965-e08efcf0498b.png)

Notice how "applies" gets broken up on text wrapping -- the "a" is left on the first line and appears again on the second line with the rest of the word.

~~I'm not sure if the `--auth` line breaking is working right either? I'd prefer that to show up on one line, since there's room, but that's debatable.~~ Edit: As Gillibald mentioned, this is working properly, and the non-breaking hyphen (`\u2011`) works great in my app.

XAML:

```xml
<TextBlock Text="Whether to turn off HTTPS. This option only applies if Individual, IndividualB2C, SingleOrg, or MultiOrg aren't used for --auth."
             Margin="0,4,0,0"
             Width="238"
             FontFamily="avares://ItalicTextWrapping/Assets/NotoSans-Italic.ttf#Noto Sans"
             TextWrapping="Wrap"/>
```

Repo for easy reproducing: https://github.com/Deadpikle/AvaloniaBugs/tree/master/ItalicTextWrapping

Thanks!

**Comment by Gillibald** [comment]
`applies` should not be broken into characters in that scenario. For `--auth` you have to glue everything together. Breaking between `--` should be valid.

Will investigate and fix shortly.

**Comment by Gillibald** [comment]
For reference https://www.fileformat.info/info/unicode/char/2011/index.htm

**Comment by Gillibald** [comment]
This issue is super weird. Somehow Skia renders an extra character with this particular font.

**Comment by Gillibald** [comment]
#4240 I think I finally fixed this. Still have to verify 😅

**Comment by Deadpikle** [comment]
Sorry, this bug still exists in `0.9.999-cibuild0008974-beta`. (No problem, but since you mentioned needing to verify still, I thought I would check on it.)

**Comment by Gillibald** [comment]
Too bad. So I need to investigate this further. Thanks for testing.

**Comment by Gillibald** [comment]
![2020-07-28 174241](https://user-images.githubusercontent.com/5928797/88688586-cba14780-d0f9-11ea-85f4-db8f95627025.png)

**Comment by Gillibald** [comment]
Closing because it seems to be fixed

**Comment by Deadpikle** [comment]
8974 is out of date. I apologize for using the wrong build. I can confirm this is fixed. My bad! 😅
