### ISSUE TITLE
Dynamic Resource is not being evaluated inside stylesheets.

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#3655]
As title described. Repro project [here](https://github.com/jmacato/DynamicIconRepro). The project should show a "copy" icon but it doesnt show the white border of the icon. 

Affects https://github.com/zkSNACKs/WasabiDesign/issues/3

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/3597

**Comment by jmacato** [comment]
@Gillibald i tried the latest cibuild and still isnt working :(

**Comment by Gillibald** [comment]
Are you sure that the brush isn't updated? It could be that the GeometryDrawing isn't invalidateing the parent DrawingGroup.

**Comment by jmacato** [comment]
i tried with a regular rectangle and it was the same

**Comment by jmacato** [comment]
Ah crap! i was using `ThemeForegroundBrush` against a black background!! damn it haha. should be using `ThemeBackgroundBrush`!

**Comment by jmacato** [comment]
Yep, confirmed fixed by #3597 :D though @grokys would still want to write a failing test for this?

**Comment by grokys** [comment]
No, if it's already fixed that would explain why I can't write a failing test for it! I think I may have got confused by versions at some point. Going to close this if it's already fixed ;)
