### ISSUE TITLE
TextBox KeyDown event handling

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#3657]
The `TextBox` control currently only handles certain KeyDown events (like Ctrl+C/V for copy/paste) and lets the rest bubble to its parents (it's using TextInput events to handle actual text input). I was wondering how much sense it would make to unconditionally handle all key down events so that parent controls don't get notified about these key events. AFAICT this used to be the behavior until #1357 refactored it. In my application the current behavior causes some issues with modifier-less hotkeys: Pressing space (for instance) on a TextBox will signal the parent control that is executing the hotkey.

PS: I know this question got asked internally, I am just repeating it here for visibility and community feedback.

CC: @grokys, @Gillibald

**Comment by grokys** [comment]
Thanks for opening this @pr8x 

I've just tested on WPF, and WPF indeed seems to have the same behavior as Avalonia:

```xml
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        mc:Ignorable="d" Title="MainWindow">
    <TextBox></TextBox>
</Window>
```

```csharp
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        protected override void OnKeyDown(KeyEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine(e.Key);
            base.OnKeyDown(e);
        }
    }
```
Typing: `test` `Ctrl+C` `Ctrl+V` `Ctrl+Z` `Ctrl+H`  outputs:

```
T
E
S
T
LeftCtrl
LeftCtrl
LeftCtrl
H
```

So it seems that we're not doing anything particularly unexpected here. I'm not sure how this problem is handled in WPF applications, or if we need any extra functionality here?

**Comment by pr8x** [comment]
Could you test if it works with `<Window.CommandBindings>` and `RoutedCommand`?

**Comment by grokys** [comment]
I'm not that familiar with WPF's `CommandBinding`s, but [AFAIU](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/commanding-overview#command-sources), they are usually initiated by an `InputBinding`. `InputBinding` only supports key gestures with modifier keys such as `Ctrl` so I don't think the issue you're seeing can happen here?

I may be misunderstanding how this all works though.

**Comment by MarchingCube** [comment]
`KeyBinding` allows to use just a key without modifiers and it behaves a bit differently than in Avalonia. When text box is focused and you type a character that is bound - text box will ignore that input.

**Comment by grokys** [comment]
Need to look into this, but perhaps our key binding stuff needs to be handling the tunneling events and marking them as handled.
