### ISSUE TITLE
[Feature Request] Support check marks in macOS NativeMenu

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/Avalonia#3660]
It'd be great to see checkbox/checkmark support in macOS for the `NativeMenu` functionality. See [here](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/MenuList/Articles/MenuItemStates.html) for the code -- basically, it's calling `[menuItem setState:NSOnState]` to show a checkmark and `[menuItem setState:NSOffState]` to not show it.

I suppose, ideally, this would be used in Avalonia like this:

```xml
<NativeMenuItem Header="Check me!"
    Command="{Binding ToggleCheck}"
    IsChecked="{BInding Checkmate}" />
```

I googled around a bit and didn't find info on whether native menus in Linux could support checkmarks. There's kind of an allusion to one [in the Ubuntu MenuBar docs here](https://wiki.ubuntu.com/MenuBar) (about 50% down in an image talking about the View menu), but I'm not familiar enough with Linux distros to know if this has widespread support.

Edit: `DBusMenu` should support checkmarks: https://gjs-docs.gnome.org/dbusmenu04~0.4_api/dbusmenu.menuitem_toggle_check

**Comment by Deadpikle** [comment]
I got as far as getting the checkmark to show up in the `NativeMenu` with manually setting `IsChecked` in XAML, but couldn't figure out a way to update the actual native menu item (`NSMenuItem`) when the `{Binding ...}` property updated. In other words, I couldn't figure out how to trigger a binding update to the actual UI when my property updated.

WIP here: https://github.com/Deadpikle/Avalonia/tree/feature/native-menu-macos-checkmark

**Comment by Deadpikle** [comment]
@danwalmsley With #3762 merged, is this safe to close?

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/3837
