### ISSUE TITLE
x:Array in XAML

### ISSUE THREAD

**Issue by JTrotta** [AvaloniaUI/Avalonia#3661]
In Wpf I can:
`               <view:Knob.Segments>
                    <x:Array  Type="{x:Type view:KnobSegment}" >
                        <view:KnobSegment Fill="YellowGreen" AngleInDegrees="60"/>
                        <view:KnobSegment Fill="Gold" AngleInDegrees="30"/>
                        <view:KnobSegment Fill="Orange" AngleInDegrees="20"/>
                    </x:Array>
                </view:Knob.Segments>`

in Avalonia x:Array is not recognized.

**Comment by JTrotta** [comment]
Nobody?

**Comment by kekekeks** [comment]
Arrays aren't currently supported.For now you can use `System.Collections.ArrayList` or `System.Collections.Generic.List`.

**Comment by JTrotta** [comment]
@kekekeks like this?
xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib"

does not work :-<

**Comment by JTrotta** [comment]
No like this:
        xmlns:scg="clr-namespace:System.Collections.Generic;assembly=netstandard"
        xmlns:sys="clr-namespace:System;assembly=netstandard"

Sorry

**Comment by zangetsudo** [comment]
<CheckBox.CommandParameter>
                        <sys:List Type="{x:Type sys:bool}">
                            <MultiBinding>
                                <Binding ElementName="HeaderCheckbox" Mode="OneWay" Path="IsChecked" />
                                <Binding ElementName="HeaderToggleButton" Mode="OneWay" Path="IsChecked" />
                            </MultiBinding>
                        </sys:List>
                    </CheckBox.CommandParameter>
still not work,why?
