### ISSUE TITLE
Incorrect selection changed parameters order in DataGrid

### ISSUE THREAD

**Issue by ingvar1995** [AvaloniaUI/Avalonia#3664]
DataGrid selection changed returns removed items in `AddedItems` collection and added items in `RemovedItems` collection. It happens due to incorrect order of parameters in
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls.DataGrid/DataGridSelectedItemsCollection.cs#L338

**Comment by grokys** [comment]
This was fixed by #3526, @danwalmsley looks like we might need to do another stable release that includes #3526?
