### ISSUE TITLE
How to disable a button when pressed?

### ISSUE THREAD

**Issue by Armegon** [AvaloniaUI/Avalonia#3667]
Here is my button xaml:

```
<Button DockPanel.Dock="Bottom" Content="{Binding DownloadUpdatePlayButton}" Command="{Binding installUpdatePlay}" VerticalAlignment="Bottom" Margin="20 0 0 20"  Height="50" Width="200" HorizontalAlignment="Left"></Button>
```

Is there any way to transfer an instance of the button to `DownloadUpdatePlayButton` so in this function I know the exact button pressed. I need to in order to disable it after pressed and then enable it once `DownloadUpdatePlayButton` finishes it's job.

**Comment by FoggyFinder** [comment]
I think the better way would be using `IsLoading` state that keeps information about all possible options.
Then you can check it for a specific object in `CanExecute`.
Some pseudo-code to show the idea:

```
DownloadUpdatePlayButton = new RelayCommand(StartDownloading, p => IsLoaded[p]);
```

and inside of your `StartDownloading`:

```csharp
StartDownloading(int id)
{
    IsLoading[id] = true;
    // process
    IsLoading[id] = false;
} 
```

`id` is passed via `CommandParameter`.

If you add more details I will be able to write some sample though.
