### ISSUE TITLE
Deferred renderer slow with large number of non overlapping dirty rects

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#3672]
In the case of updating bindings to 400 TextBoxes in an ItemsControl the dirty rects don't overlap and so are not coalesced.  The deferred renderer code shows O(n^2) behavior here which explains the large number of allocations in https://github.com/AvaloniaUI/Avalonia/pull/3656 .  An initial mod to the dirty rects code( which restricted the number of dirty rects ) reduced the rendering time from 220ms to 9ms . PR to follow once I've explored a few more ideas.

**Comment by Splitwirez** [comment]
@ahopper a friend of mine has been facing some pretty nasty performance issues...if this issue is still applicable, how could we obtain (or if needed, recreate) your mod to the dirty rects code, to see if that problem is at all related to this one?

**Comment by ahopper** [comment]
fixed by the new Compositor
