### ISSUE TITLE
TextBox: clicking on border moves caret to end

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/Avalonia#3675]
### Development Environment

* Windows 10 or macOS 14.6 (Linux untested)
* VS 16.4.6
* Latest Avalonia `master`: 36c34b4

### Bug description

When you click on the bottom border of a `TextBox` (or thereabouts), the end position of the text is where the caret ends up, even if you clicked close to the beginning of the `TextBox`. If you click on the top border, the start position of the text is where the caret ends up.

![text-selection-issues](https://user-images.githubusercontent.com/5092399/76900219-4ebeb100-686f-11ea-8653-8af518fdc66b.gif)

### Expected behavior

Because the mouse cursor has changed to the text selection cursor, I expect the caret to end up right next to my mouse (e.g. put the caret just about where I clicked). Another alternative solution would be to only show the text selection cursor when the actual text I'm over/next to will be selected.

**Comment by Deadpikle** [comment]
The cursor being wrong can be fixed with the following tweak to `TextBox.xaml`:

```
<Style Selector="TextBox /template/ DockPanel">
  <Setter Property="Cursor" Value="IBeam" />
</Style>
```
```
<Style Selector="TextBox /template/ DockPanel">
  <Setter Property="Cursor" Value="IBeam" />
</Style>
```

**Comment by Gillibald** [comment]
Not showing the IBeam cursor outside the text bounds is the right fix. Feel free to tweak these kind of issues but don't invest too much time into it. The TextBox needs a major rework and that will come at some point this year.
