### ISSUE TITLE
Avalonia build fails

### ISSUE THREAD

**Issue by JamRemco** [AvaloniaUI/Avalonia#3683]
hi all,

I get an error when building avalonia

**ERROR:**
Severity Code Description Project	File	Line	Suppression State Suppression State
Error CS0136 A local or parameter named 'c' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter _build	C:\Users\Remco\Documents\GitHub\Avalonia\nukebuild\Build.cs

**CODE:**  
  return MSBuild(c => c
           .SetProjectFile(projectFile)
            // This is required for VS2019 image on Azure Pipelines
            .When(Parameters.IsRunningOnWindows &&
                  Parameters.IsRunningOnAzure, c => c   **//HERE!!!!!!!!!!!!!!!!**
                .AddProperty("JavaSdkDirectory", GetVariable<string>("JAVA_HOME_8_X64")))
            .AddProperty("PackageVersion", Parameters.Version)
            .AddProperty("iOSRoslynPathHackRequired", true)
            .SetToolPath(MsBuildExe.Value)
            .SetConfiguration(Parameters.Configuration)
            .SetVerbosity(MSBuildVerbosity.Minimal)
            .Apply(configurator));
    } 

Using VS2019 CE

I must be doimg something wrong. I am  new to this github open source thing.

Regards, 

Remco van Grevenbroek

**Comment by JamRemco** [comment]
No one?

**Comment by kekekeks** [comment]
Well, the build is passing on CI server, so something is probably wrong with your setup. Try updating .NET Core SDK and Visual Studio.

**Comment by Gillibald** [comment]
@JamRemco Why are you so rude? This project is run by volunteers. Sry this is a big off-topic.

**Comment by JamRemco** [comment]
Sorry for sounding rude. 
that was not my intension.

i;ve got on my system installed
vs 2019 16.3.10
.net core sdk 3.1.200 (installed friday)
Windows 10

**Comment by Gillibald** [comment]
You need to use `.Net Core SDK 3.1.101`

**Comment by JamRemco** [comment]
@Gillibald Ok thanks i am going to try that.
