### ISSUE TITLE
Multi-target .Net Standard 2.1 in core framework

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#3691]
Bringing back discussion from .Net Core 3.1 PR.

Currently all framework libraries target .Net Standard 2.0 which has several missing features that .Net Standard 2.1 offers to us:
- number parsing functions that take `ReadOnlySpan`.
- in general more methods accept/returns spans allowing for more flexibility.
- `HashSet` constructor that allow for having initial capacity (we might not need it right now, but I wanted to use it at some point to quickly realize that there is nothing in 2.0), but in general - there are more available functions in collections.
- `RuntimeHelpers.IsReferenceOrContainsReferences<T>` is useful for memory pooling code since it allows us to easily check if we need to clear the memory before freeing. Current implementation of pooled collections always clears because it lacks this info.
- `System.HashCode` since we don't need tons of boilerplate for such basic functionality.

We have two options:
- target .Net Standard 2.1 only - leaves .Net Framework off the table so not really viable due to people still porting their apps.
- target .Net Standard 2.0 and 2.1 and ship packages for both. Probably needs CI work plus more (no idea what does it take really).

**Comment by kekekeks** [comment]
>number parsing functions that take ReadOnlySpan.

>in general more methods accept/returns spans allowing for more flexibility.

> `RuntimeHelpers.IsReferenceOrContainsReferences<T>`

>System.HashCode since we don't need tons of boilerplate for such basic functionality.

Can we polyfill those? We also need a way to make those polyfills available only to Avalonia assemblies while hiding that API surface from app code base. A possible way would be to have `Avalonia.Polyfills` project with `InternalsVisibleTo`for every other assembly in our solution.



>target .Net Standard 2.0 and 2.1 and ship packages for both. Probably needs CI work plus more (no idea what does it take really).

Our [package merger](https://github.com/kekekeks/Numerge) needs to be reworked to know about `netstandard2.1`, right now it considers `netstandard2.0` to be the only compatible TFM when merging netstandard dependencies into platform-specific TFMs.

**Comment by kekekeks** [comment]
Alternative option would be to multi-target the legacy framework explicitly. Xamarin platforms already support netstandard2.1, the only other platform that technically isn't compatible with netstandard2.1 TFM is WASM (due to desktop Mono still using net4xx TFM).

**Comment by MarchingCube** [comment]
@kekekeks .Net Framework does not support .Net Standard 2.1 either. Also I am not so sure what is going to happen during .Net 5 times - will we have only 1 TFM or there will be more?

**Comment by kekekeks** [comment]
>will we have only 1 TFM or there will be more

One "base" TFM with platform-specific  suffixes.

**Comment by rstm-sf** [comment]
.NET Standard 2.1 is dead. .NET Standard 2.0 will die along with the legacy framework. .NET 6 new standard

**Comment by maxkatz6** [comment]
We multitarget netstandard2.0 and net6 now.
