### ISSUE TITLE
I used Avalonia for the first time, but it didn't work on Linux

### ISSUE THREAD

**Issue by BigHeadDev** [AvaloniaUI/Avalonia#3694]
I compiled the program from windows and uploaded it to CentOS 7. 
After running, nothing happened. 
The window didn't render, and there was no error message. 
The light just stopped blinking on the command line

**Comment by BigHeadDev** [comment]
I prefixed each line with Console. Writeline();
all lines work well
but no window was rendered
windows works well but linux
What's the reason, please

**Comment by kekekeks** [comment]
How are you publishing your app before uploading?
What is your XOrg version?
Are you running the app from a terminal emulator running inside X11 session?

**Comment by BigHeadDev** [comment]
> How are you publishing your app before uploading?
> What is your XOrg version?
> Are you running the app from a terminal emulator running inside X11 session?

Thank you for your reply
I use VS2019 publish it.  (release |AnyCPU;.net core 3.0;linux x64)
XOrg is GNOME 3.28
running by terminal emulator

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/3679 has similar symptoms.

Please, check if following code prints anything on console:
```cs
        Console.WriteLine(SKTypeface.Default.FamilyName);
        Console.WriteLine(SKTypeface.FromFamilyName("Sans").FamilyName);
```

**Comment by BigHeadDev** [comment]
> #3679 has similar symptoms.
> 
> Please, check if following code prints anything on console:
> 
> ```cs
>         Console.WriteLine(SKTypeface.Default.FamilyName);
>         Console.WriteLine(SKTypeface.FromFamilyName("Sans").FamilyName);
> ```

thank you for your reply
now, it throw an NullRefrenceException at Console.WriteLine(SKTypeface.FromFamilyName("Sans").FamilyName)

**Comment by BigHeadDev** [comment]
> #3679也有类似的症状。
> 
> 请检查以下代码是否打印出控制台上的任何内容：
> 
> ```cs
>         Console.WriteLine(SKTypeface.Default.FamilyName);
>         Console.WriteLine(SKTypeface.FromFamilyName("Sans").FamilyName);
> ```

thanks so much！
I set the window‘s default FontFamily and solved it!  
It's so cool!!  
I hope that one day Avalonia can be the no.1 of  cross plantform UI framework solutions!!!!!!!
~~~xml
<Application.Resources>
        <FontFamily x:Key="yh">msyh</FontFamily>
</Application.Resources>
<Style Selector="Window">
            <Setter Property="FontFamily" Value="{StaticResource yh}" />
</Style>

**Comment by Gillibald** [comment]
Are you using nightly build or a current release?
