### ISSUE TITLE
TreeView does not behave as expected when inside a Grid with proportional sizing

### ISSUE THREAD

**Issue by advorange** [AvaloniaUI/Avalonia#3697]
When using proportional row heights a TreeView will extend off the screen if there are too many elements. This does not happen when using fixed heights, but then the TreeView wouldn't fill the empty area so that's not a reasonable solution. WPF does not have this issue.

Expected (from WPF):
![](https://user-images.githubusercontent.com/22116714/77707257-d9936000-6f81-11ea-97d3-fa93c913256e.png)

Actual (from Avalonia, notice the buttons are pushed off screen and there is no scrollbar):
![](https://user-images.githubusercontent.com/22116714/77707273-e1530480-6f81-11ea-8f7e-087aaeaf6021.png)

Avalonia version: 0.9.999-cibuild0006379-beta
Reproduction repo: https://github.com/advorange/TreeViewTest

**Comment by ahmedflix25** [comment]
it's not only the TreeView any thing with Items property like ItemsControl or ListBox etc will do the same thing 
if your window is in normal mode and you maximized it the scrollbar shows and the problem solve it self at least with me on windows

**Comment by ahmedflix25** [comment]
i updated to 0.9.7 and it seem to work now

**Comment by Gillibald** [comment]
Might be related to the introduction of the new TextBlock. Could you try using TextBlock instead of TextBox just to make sure that isn't an issue. Textbox has some hacks to measure itself. Maybe something is wrong with that hack.

**Comment by ahmedflix25** [comment]
i', testing here https://github.com/ahmedflix25/SuperPostDroidPunk

**Comment by advorange** [comment]
Updated Avalonia to `0.9.999-cibuild0007149-beta` and this bug is gone. I don't know which version between `0.9.999-cibuild0006379-beta` and `0.9.999-cibuild0007149-beta` fixed the bug.
