### ISSUE TITLE
Gradients in styles

### ISSUE THREAD

**Issue by JamRemco** [AvaloniaUI/Avalonia#3700]
Hoi,

I'm trying to set an gradient in a style like this, but it doesnt work

<Setter Property="Background">
      <Setter.value>
        <LinearGradientBrush StartPoint="50%,0%" EndPoint="50%,100%">
          <LinearGradientBrush.GradientStops>
            <GradientStop Offset="0.0" Color="#ff353539"/>
            <GradientStop Offset="0.5" Color="#ff404044"/>
            <GradientStop Offset="1.0" Color="#ff353539"/>
          </LinearGradientBrush.GradientStops>
        </LinearGradientBrush>
      </Setter.value>
    </Setter>

![xamlcode](https://user-images.githubusercontent.com/58340108/77804994-2f026680-7081-11ea-8ae8-0d4d727ea1c4.jpg)

**Error:**

> Unable to resolve suitable regular or attached property value on type Avalonia.Styling:Avalonia.Styling.Setter (line 158 position 6) 

i hade to include the picture because code was invisible in message

Regards,

Remco

**Comment by kekekeks** [comment]
`Value`. With capital **V**. Not `value`.

**Comment by JamRemco** [comment]
Okay that worked!!!
I feel realy stupid now. hahaha

Remco

**Comment by Sorien** [comment]
@JamRemco see https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by JamRemco** [comment]
Tnx

Op di 31 mrt. 2020 17:53 schreef Sorien <notifications@github.com>:
