### ISSUE TITLE
Debian 10 KDE environment nothing display 

### ISSUE THREAD

**Issue by shynome** [AvaloniaUI/Avalonia#3701]
Hi, I'm interested this project, but it's not working on my linux computer

my environment:
- Debian 10 stable KDE
- dotnet sdk 3.1.201
- language: zh_CN

steps:
- dotnet new avalonia.mvvm -o MyApp
- cd MyApp
- dotnet run -v n  (no error)
- nothing display
- wait 10 second still nothing display 

resolution:
set `<Window FontFamily="MyInstalledFontName"/>` make it work
https://github.com/AvaloniaUI/Avalonia/issues/3701#issuecomment-605416864

**Comment by kekekeks** [comment]
Might be related to https://github.com/mono/SkiaSharp/issues/1181

Please, try running the following code in your environment:
```cs
        Console.WriteLine(SKTypeface.Default.FamilyName);
        Console.WriteLine(SKTypeface.FromFamilyName("Sans").FamilyName);
```

**Comment by Gillibald** [comment]
You could try using https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies/1.68.1.1 in your project. Make sure to set a font family on your window explicitly.

**Comment by shynome** [comment]
@kekekeks 


`SKTypeface.Default.FamilyName` output null

`SKTypeface.FromFamilyName("Sans").FamilyName` throw a error 
````
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
````

**Comment by shynome** [comment]
@kekekeks 

Thank's your suggestion, this seems to be my font problem, my language is `zh_CN`

`SKTypeface.Default.FamilyName` output null

`SKTypeface.FromFamilyName("Sans").FamilyName` throw a error 
````
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
````

**Comment by shynome** [comment]
@Gillibald 
Thanks for your suggestion, I tried it, but I didn't find how to set the font family explicitly, it feels bad for newcomers

**Comment by Gillibald** [comment]
`<Window FontFamily="MyInstalledFontName"/>`

**Comment by shynome** [comment]
@Gillibald Thanks for the reply, it works, setting `<Window Font Family =" Install Font Name "/> is enough
don't need add `https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies/1.68.1.1`, if add that will throw a error
```
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'sk_refcnt_safe_unref' in shared library 'libSkiaSharp'.
   at SkiaSharp.SkiaApi.sk_refcnt_safe_unref(IntPtr refcnt)
   at SkiaSharp.SKObjectExtensions.SafeUnRef(ISKReferenceCounted obj)
   at SkiaSharp.SKObject.DisposeNative()
   at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)
   at SkiaSharp.SKObject.Dispose(Boolean disposing)
   at SkiaSharp.GRGlInterface.Dispose(Boolean disposing)
   at SkiaSharp.SKNativeObject.DisposeInternal()
   at SkiaSharp.SKNativeObject.Dispose()
   at Avalonia.Skia.PlatformRenderInterface..ctor(ICustomSkiaGpu customSkiaGpu)
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options)
   at Avalonia.SkiaApplicationExtensions.<>c__0`1.<UseSkia>b__0_0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at MyApp.Program.Main(String[] args) in /home/shynome/work/MyApp/Program.cs:line 14
```

**Comment by Gillibald** [comment]
So font matching isn't working. One immediate fix could be querying the first installed font and use it instead of the not working default font.

**Comment by mattleibow** [comment]
> Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'sk_refcnt_safe_unref' in shared library 'libSkiaSharp'.

This usually happens when the managed and native libraries are out of sync. Often you just need a rebuild if you just updated a SkiaSharp NuGet package.

**Comment by driver1998** [comment]
Repro in Ubuntu 20.04, locale set to zh-CN.
The workaround works as well.
