### ISSUE TITLE
Incompatible packages in default Avalonia project

### ISSUE THREAD

**Issue by BarsikTheCaT** [AvaloniaUI/Avalonia#3703]
Visual Studio 2019 16.5.1
Avalonia for Visual Studio 0.9.0.0
I am unable to build a default Avalonia project. Trying to build it give the following output:
````
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
1>------ Build started: Project: AvaloniaTest, Configuration: Debug Any CPU ------
1>D:\~\AvaloniaTest\AvaloniaTest\AvaloniaTest.csproj : warning NU1701: Package 'System.Runtime.InteropServices.WindowsRuntime 4.3.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
1>D:\~\AvaloniaTest\AvaloniaTest\AvaloniaTest.csproj : error NU1202: Package JetBrains.Annotations 10.3.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package JetBrains.Annotations 10.3.0 does not support any target frameworks.
1>D:\~\AvaloniaTest\AvaloniaTest\AvaloniaTest.csproj : error NU1202: Package SkiaSharp 1.68.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package SkiaSharp 1.68.0 does not support any target frameworks.
1>D:\~\AvaloniaTest\AvaloniaTest\AvaloniaTest.csproj : error NU1202: Package System.Drawing.Common 4.5.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package System.Drawing.Common 4.5.0 supports:
1>D:\~\AvaloniaTest\AvaloniaTest\AvaloniaTest.csproj : error NU1202:   - monoandroid10 (MonoAndroid,Version=v1.0)
1>D:\~\AvaloniaTest\AvaloniaTest\AvaloniaTest.csproj : error NU1202:   - monotouch10 (MonoTouch,Version=v1.0)
1>D:\~\AvaloniaTest\AvaloniaTest\AvaloniaTest.csproj : error NU1202:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
1>D:\~\AvaloniaTest\AvaloniaTest\AvaloniaTest.csproj : error NU1202:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
1>D:\~\AvaloniaTest\AvaloniaTest\AvaloniaTest.csproj : error NU1202:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
1>D:\~\AvaloniaTest\AvaloniaTest\AvaloniaTest.csproj : error NU1202:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
1>Done building project "AvaloniaTest.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by grokys** [comment]
Strange. I don't see this issue here, and looking at e.g. `Jetbrains.Annotations` on NuGet, it definitely does support target frameworks. I think there must be something wrong with your VS install? Try building from the command line using `dotnet.exe`?

**Comment by BarsikTheCaT** [comment]
> Strange. I don't see this issue here, and looking at e.g. `Jetbrains.Annotations` on NuGet, it definitely does support target frameworks. I think there must be something wrong with your VS install? Try building from the command line using `dotnet.exe`?

Doing 'dotnet build' in powershell gave the same output as building via Visual Studio. Going to repair my VS install and try again.

**Comment by BarsikTheCaT** [comment]
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
1>------ Rebuild All started: Project: AvaloniaTest2, Configuration: Debug Any CPU ------
1>D:\PRJCT\AvaloniaTest2\AvaloniaTest2\AvaloniaTest2.csproj : warning NU1701: Package 'System.Runtime.InteropServices.WindowsRuntime 4.3.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.
1>D:\PRJCT\AvaloniaTest2\AvaloniaTest2\AvaloniaTest2.csproj : error NU1202: Package JetBrains.Annotations 10.3.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package JetBrains.Annotations 10.3.0 does not support any target frameworks.
1>D:\PRJCT\AvaloniaTest2\AvaloniaTest2\AvaloniaTest2.csproj : error NU1202: Package SkiaSharp 1.68.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package SkiaSharp 1.68.0 does not support any target frameworks.
1>D:\PRJCT\AvaloniaTest2\AvaloniaTest2\AvaloniaTest2.csproj : error NU1202: Package System.Drawing.Common 4.5.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package System.Drawing.Common 4.5.0 supports:
1>D:\PRJCT\AvaloniaTest2\AvaloniaTest2\AvaloniaTest2.csproj : error NU1202:   - monoandroid10 (MonoAndroid,Version=v1.0)
1>D:\PRJCT\AvaloniaTest2\AvaloniaTest2\AvaloniaTest2.csproj : error NU1202:   - monotouch10 (MonoTouch,Version=v1.0)
1>D:\PRJCT\AvaloniaTest2\AvaloniaTest2\AvaloniaTest2.csproj : error NU1202:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
1>D:\PRJCT\AvaloniaTest2\AvaloniaTest2\AvaloniaTest2.csproj : error NU1202:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
1>D:\PRJCT\AvaloniaTest2\AvaloniaTest2\AvaloniaTest2.csproj : error NU1202:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
1>D:\PRJCT\AvaloniaTest2\AvaloniaTest2\AvaloniaTest2.csproj : error NU1202:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
1>Done building project "AvaloniaTest2.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
Repaired VS install, on new Avalonia project I get this same output.
However, repairing VS gave an error in the end - it failed to repair Microsoft.AspNetCore.SharedFramework.3.1.3.1.3.x86. Going to uninstall it manually and try repairing again.

**Comment by kekekeks** [comment]
Definitely an SDK issue.

**Comment by BarsikTheCaT** [comment]
> Definitely an SDK issue.

Installed .Net Core SDK 3.1.3 again, now projects build and launch as expected. Thanks for advice!
