### ISSUE TITLE
Cannot disable ReactiveUI transitions animations

### ISSUE THREAD

**Issue by alessandrofrancesconi** [AvaloniaUI/Avalonia#3704]
My Avalonia application uses ReactiveUI for routing. Avalonia version is 0.9.6.
I've followed the [wiki](https://avaloniaui.net/docs/reactiveui/routing), so the content of my pages are "inside" this RoutedViewHost:

```
<rxui:RoutedViewHost Router="{Binding Router}" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">          
  <rxui:RoutedViewHost.DefaultContent>
    <!-- CONTENT... -->
  </rxui:RoutedViewHost.DefaultContent>
</rxui:RoutedViewHost>
```

Tranistions between pages works, but there is a default fadein/out animation that I want to remove.
The wiki says:

> Additionally, you can override animations that are played when RoutedViewHost changes a view — simply override RoutedViewHost.FadeInAnimation and RoutedViewHost.FadeOutAnimation properties in XAML.

However, I cannot find FadeInAnimation / FadeOutAnimation properties in the RoutedViewHost class. How can I turn animation off?

**Comment by Gillibald** [comment]
You need to override this https://github.com/AvaloniaUI/Avalonia/blob/6c40771d941c0c2082fe601f70715f34c0b08386/src/Avalonia.ReactiveUI/TransitioningContentControl.cs#L19

**Comment by alessandrofrancesconi** [comment]
I've extended the `RoutedViewHost` this way:

```
    public class StaticRoutedViewHost : RoutedViewHost
    {
        public static new readonly StyledProperty<IPageTransition> PageTransitionProperty = 
            AvaloniaProperty.Register<TransitioningContentControl, IPageTransition>(nameof(PageTransition),
                new CrossFade(TimeSpan.FromSeconds(0)));

        public StaticRoutedViewHost() : base()
        {

        }
    }
```

You see "TimeSpan.FromSeconds(0)".
The I've used it in the XAML:

```
<my:StaticRoutedViewHost Router="{Binding Router}" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">          
  <my:StaticRoutedViewHost.DefaultContent>
    <!-- CONTENT... -->
  </my:StaticRoutedViewHost.DefaultContent>
</my:StaticRoutedViewHost>
```

But crossfade animation is still visible between views. What am I missing?

**Comment by Gillibald** [comment]
Just set the property to null

**Comment by alessandrofrancesconi** [comment]
Already tried, no luck.

**Comment by Gillibald** [comment]
`RoutedViewHost.PageTransition="{x:Null}"` should work.

**Comment by alessandrofrancesconi** [comment]
This works! Also I don't need to extend the class.

`<rxui:RoutedViewHost PageTransition="{x:Null}" ...`

Thank you.
