### ISSUE TITLE
Add Support for Shorthand Hex Color String in SolidColorBrush etc

### ISSUE THREAD

**Issue by Metric** [AvaloniaUI/Avalonia#3706]
A shorthand color string should be supported. E.g. #000 (which translates to FF000000). WPF supports this, so I am surprised this got left out.

**Comment by rstm-sf** [comment]
I think we can start from [here](https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Parsers.cs#L83-L91)

**Comment by Gillibald** [comment]
`Background="#ff123456"` works without issues

**Comment by wdcossey** [comment]
I suspect that @Metric wants the short color strings supported

i.e. 
`#f00 -> #ff0000`
`#f0f -> #ff00ff`
`#f321 -> #ff332211`
`#3f25 -> #33ff2255`

You can add this to `Color.Parse()`, simply duplicating every char, excluding the `#`
```
if (s.Length >= 4 && s.Length <= 5)
{
    s = string.Concat(s.SelectMany(@char => new[] { @char, @char })).Substring(1);
}
```
