### ISSUE TITLE
Color Animation "bug"

### ISSUE THREAD

**Issue by JamRemco** [AvaloniaUI/Avalonia#3709]
Hello World,

I Think i have found a bug.

When i used named colors it works as expected

![animagoed](https://user-images.githubusercontent.com/58340108/77961727-91a26f00-72da-11ea-8978-f5eb4f5f7e76.jpg)

But when i change on row 269 Value="White"  In: Value="#ff123456" It stops working
No warning or error but no color animation.

Regards, 

Remco

**Comment by JamRemco** [comment]
Update there is a exception in the intermediate window

> [Visual] Exception in render update: "System.InvalidCastException: Unable to cast object of type 'Avalonia.Media.SolidColorBrush' to type 'Avalonia.Media.Color'.
   at Avalonia.Animation.Animators.Animator`1.InterpolationHandler(Double animationTime, T neutralValue)
   at Avalonia.Animation.AnimationInstance`1.InternalStep(TimeSpan time)
   at Avalonia.Animation.AnimationInstance`1.Step(TimeSpan frameTick)


Regards,

Remco

**Comment by Gillibald** [comment]
Avalonia currently doesn't understand colors as hex strings. It probably fails silently.

**Comment by grokys** [comment]
> Avalonia currently doesn't understand colors as hex strings.

Avalonia does understand colors as hex strings: we use them in a number of places, e.g. https://github.com/AvaloniaUI/Avalonia/blob/3c74b9593e2534dabd2f4751c80276897fbb14ad/src/Avalonia.Themes.Default/Accents/BaseDark.xaml#L6

**Comment by grokys** [comment]
What I suspect is happening here is that the animation system isn't correctly converting values. @jmacato when you're feeling better could you take a look?

**Comment by grokys** [comment]
In the meantime, you should be able to do something like:

```
<Setter Property="Background">
    <SolidColorBrush Color="#ff123456"/>
</Setter>
```

**Comment by Gillibald** [comment]
Hex strings work for Color! Not for brushes!

**Comment by JamRemco** [comment]
@Gillibald  Aha!
@grokys 
> What I suspect is happening here is that the animation system isn't correctly converting values.

That was what i espected aswel.

Regards,

Remco

**Comment by Gillibald** [comment]
Okay, my bad. I assumed the hex format isn't working because someone reported it isn't. Just tested it and it works without issues. Sry about that.

**Comment by JamRemco** [comment]
To be clear, this works
```Xaml
 <Style Selector="TabItem:pointerover /template/ ContentPresenter#PART_ContentPresenter">
      <Setter Property="Background" Value="#ff125099"/>
  </Style>
```

But in de context of a animation, this works
```Xaml
  <KeyFrame Cue="10%" >
     <Setter Property="Background" Value="White"/>
  </KeyFrame>
```
But this not
```Xaml
  <KeyFrame Cue="10%" >
     <Setter Property="Background" Value="ff123456"/>
  </KeyFrame>
```

Remco
