### ISSUE TITLE
MainWindow not hiding after calling `this.Hide()`

### ISSUE THREAD

**Issue by Banyc** [AvaloniaUI/Avalonia#3710]
## Environment

.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64

## Code

```csharp
public MainWindow()
        {
            DataContext = new MainWindowViewModel();
            InitializeComponent();

            // this.ShowInTaskbar = false;
            // this.WindowState = WindowState.Minimized;
            this.Hide();
        }
```

## Expected behavior

The window should hide

## Actual behavior

The window does not hide.

**Comment by kekekeks** [comment]
You are trying to hide it from constructor when it's already/still hidden. It's shown [way later by ClassicDesktopStyleApplicationLifetime](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs#L104) application startup process.
