### ISSUE TITLE
Segfault on linux with a new unmodified template project

### ISSUE THREAD

**Issue by SparkyTD** [AvaloniaUI/Avalonia#3718]
I have installed [these](https://github.com/AvaloniaUI/avalonia-dotnet-templates) avalonia templates with `dotnet new --install`. After that, I've created a new project with `dotnet new avalonia.app -n TestApp`. The project builds successfully, but if I try to run the generated binary file, I get a segmentation fault. No additional error info is given.

I have noticed that some of my other dotnet projects (not avalonia) are also segfaulting for apparently no reason, and a couple weeks ago they worked fine. This might be a bug in the new version of net core, because I have updated it recently. I'm posting here hoping that someone knows how to fix this.

Steps to reproduce:
- `cd ~`
- `git clone https://github.com/AvaloniaUI/avalonia-dotnet-templates.git`
- `dotnet new --install avalonia-dotnet-templates`
- `dotnet new avalonia.app -n TestApp`
- `cd TestApp`
- `dotnet build`
- `dotnet run` (does nothing)
- `bin/Debug/netcoreapp3.0/TestApp` (Segmentation fault core dumped)

OS: Manjaro Linux (kernel: 5.4.28-1-MANJARO)
Dotnet Version: .NET Core SDK (3.1.103)

**Comment by kekekeks** [comment]
Have you updated to 0.9.6? There were some fixes for manjaro-specific issues since 0.9.0 release.

**Comment by SparkyTD** [comment]
> Have you updated to 0.9.6? There were some fixes for manjaro-specific issues since 0.9.0 release.

Thank you :) Updating to 0.9.6 fixed the issue. Somehow I was assuming that the template included the newest version.
