### ISSUE TITLE
What are the disadvantages of exposing a StyledProperty as an AvaloniaProperty?

### ISSUE THREAD

**Issue by Happypig375** [AvaloniaUI/Avalonia#3722]
To facilitate code sharing between Avalonia and Xamarin.Forms, I an thinking of exposing generic StyledProperties as non-generic AvaloniaProperties so that I can have one `using` clause to define properties for both frameworks. Are there any disadvantages in doing so?

**Comment by Happypig375** [comment]
From https://github.com/AvaloniaUI/Avalonia/issues/3508

Seems like the only problem is a bit of performance loss?

**Comment by grokys** [comment]
Yeah, the main reason is that setting up controls from the XAML compiler is a hot path so we've been trying to optimize things as much as possible there. A plain `AvaloniaProperty` requires several levels of indirection to get to the correct code.

I guess it could be useful for cases like this however, so we could add a special code-path in the XAML compiler for dealing with this. Does a plain `AvaloniaProperty` work properly on our nightly builds?
