### ISSUE TITLE
WinExe (win-x64) app publishing is host OS dependent

### ISSUE THREAD

**Issue by sergey-tihon** [AvaloniaUI/Avalonia#3723]
I am working Avalonia app [MinMe](https://github.com/sergey-tihon/MinMe) and found that `dotnet publish` produce different results on `Windows` and `macOS`

My project file target `netcoreapp3.1`
```xml
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>8</LangVersion>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets/minme-logo.ico</ApplicationIcon>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
```
and `global.json`
```json
{
  "sdk": {
    "version": "3.1.200"
  }
}
```

`dotnet publish -r win-x64 -c release /p:PublishSingleFile=true` works  perfectly when executed on `Windows` but when it executed on `macOS` it works differently:
- it generate file is smaller
- exe does not have application icon
- it starts as console app on windows
<img width="716" alt="image" src="https://user-images.githubusercontent.com/1197905/78179666-4323da80-746a-11ea-9023-e5d5da4c3631.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/1197905/78179760-68b0e400-746a-11ea-8cea-1696489eb2ae.png">

In thee same time compilation of WPF app on macOS does not work completely. It fails with error
> /usr/local/share/dotnet/sdk/3.1.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(59,5): error NETSDK1100: Windows is required to build Windows desktop applications. [/Users/sergey/github/test/WpfApp1/WpfApp1/WpfApp1.csproj]

**Is there a workaround to build `WinExe` application that starts as windows app with app icon?**

p.s. my [MinMe](https://github.com/sergey-tihon/MinMe) contains build scripts `./build.sh` and `.\build.cmd` that compile application for `macOS` and `Windows` and copy build results to `bin` folder. (just in case you need a reproducible sample)

**Comment by kekekeks** [comment]
Please, report any "single file" publish issues at https://github.com/dotnet/runtime/issues
