### ISSUE TITLE
avaloniaui.net SSL certificate is outdated

### ISSUE THREAD

**Issue by TheChilliPL** [AvaloniaUI/Avalonia#3724]
SSL certificate has just expired.
![image](https://user-images.githubusercontent.com/18823939/78230472-a85ee680-74d1-11ea-8389-63022b3ad012.png)
![image](https://user-images.githubusercontent.com/18823939/78230494-b14fb800-74d1-11ea-96e4-c5df110539cb.png)

**Comment by kekekeks** [comment]
Fixed
