### ISSUE TITLE
Transformed text hit test bounds are computed incorrectly

### ISSUE THREAD

**Issue by arklumpus** [AvaloniaUI/Avalonia#3732]
Hello,

First of all, thank you for the amazing work!

I am working on a project for which I need to draw rotated text and shapes and the user needs to be able to interact with both. I have found that when a RotateTransform is applied to a TextBlock, the TextBlock intercepts mouse events that happen within the bounds of the rotated text, rather than within the rotated bounds of the text. The same does not happen when using a Rectangle with the same size and transform as the TextBlock.

For example, consider this window:

![image](https://user-images.githubusercontent.com/32712606/78276951-a9ad0500-750b-11ea-8943-9786f59c3a9a.png)

```XAML
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" Width="200" Height="200"
        x:Class="TestAvaloniaBounds.MainWindow"
        Title="TestAvaloniaBounds">
	<StackPanel>
		<Canvas Width="100" Height="100">
			<Rectangle Width="86" Height="86" Fill="LightPink">
				<Rectangle.RenderTransform>
					<TranslateTransform X="6" Y="5"></TranslateTransform>
				</Rectangle.RenderTransform>
			</Rectangle>
			<Button Content="A" Margin="20, 50, 0, 0"></Button>
			<TextBlock FontSize="18" Text="Rotated text" Background="LightBlue" Cursor="Cross">
				<TextBlock.RenderTransform>
					<TransformGroup>
						<TranslateTransform X="25" Y="25"></TranslateTransform>
						<RotateTransform Angle="45"></RotateTransform>
					</TransformGroup>
				</TextBlock.RenderTransform>
			</TextBlock>
		</Canvas>
		<Canvas Width="100" Height="100">
			<Rectangle Width="86" Height="86" Fill="LightPink">
				<Rectangle.RenderTransform>
					<TranslateTransform X="6" Y="5"></TranslateTransform>
				</Rectangle.RenderTransform>
			</Rectangle>
			<Button Content="B" Margin="20, 50, 0, 0"></Button>
			<Rectangle Fill="LightBlue" Width="98" Height="24" Cursor="Cross">
				<Rectangle.RenderTransform>
					<TransformGroup>
						<TranslateTransform X="25" Y="25"></TranslateTransform>
						<RotateTransform Angle="45"></RotateTransform>
					</TransformGroup>
				</Rectangle.RenderTransform>
			</Rectangle>
		</Canvas>
	</StackPanel>
</Window>
```

In both cases, I would expect the cursor to turn into a cross only inside the light blue area; however, in the first case this happens inside the whole pink area. This also means that button A cannot be clicked. In the second case, it works as expected (cursor turns into a cross only within the blue area, button B is clickable).

This happens at least on Windows and Linux.

Is this a bug? Can you suggest a workaround?

P.S. In my code I am overriding the Render method and directly drawing to the DrawingContext and this still happens, hence the issue may be related to how transformed text is rendered in general, rather than specifically to TextBlocks.

**Comment by Gillibald** [comment]
What version of Avalonia are you using?

**Comment by arklumpus** [comment]
0.9.6

**Comment by Gillibald** [comment]
Just tested. Mixed in master.
