### ISSUE TITLE
Visual Studio - which versions are supported

### ISSUE THREAD

**Issue by focussing** [AvaloniaUI/Avalonia#3736]
On the [website](https://avaloniaui.net/) it says that Visual Studio 2017 is supported. What is the actual state of supported VS versions on Windows and Mac?

**Comment by grokys** [comment]
Yeah, sorry those instructions are out of date, the up-to-date instructions are now in the repository: https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md

We're currently redoing the website, it will be updated soon (you can see a preview at http://95.216.209.17/) - sorry for the confusion!

**Comment by kekekeks** [comment]
Visual Studio 2017 and 2019 are supported via our VS extension
MonoDevelop and forks aren't supported.

On OSX and Linux previewer could be used with JetBrains Rider and [AvaloniaRider plugin](https://github.com/ForNeVeR/AvaloniaRider), binary builds are expected to be available this month.

**Comment by focussing** [comment]
I mean not building the Avalonia itself, but which Visual Studio version do I need for creating cross platform apps on Windows and MACOS using Avalonia.

I really looking forward to starting that; I have a lot of Windows .NET based applications and I want to convert several of them so they work on Windows and Mac.

By the way; nice new website!!

**Comment by kekekeks** [comment]
The only thing you need to build and run apps is .NET Core SDK with IDE of your choice. For XAML completion and previewer you need Visual Studio 2017/2019, Rider support is coming soon.
