### ISSUE TITLE
Textformating With Run Text=......

### ISSUE THREAD

**Issue by JamRemco** [AvaloniaUI/Avalonia#3737]
Hello World,

Its me (again)

Do i need some dependencies/using statements (or otherwise) because i don;t get it to work

**ERROR**
> Unable to resolve type Run from namespace https://github.com/avaloniaui (line 12 position 8) Line 12, position 8.	AvaloniaFirst	C:\Users\Remco\source\repos\AvaloniaFirst\AvaloniaFirst\Window1.xaml	12	

I.m on 
MsVSCE 2019 V16.3.10
Avalonia 0.96

**CODE**
```Xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaFirst.Window1"
        Title="Window1">

  <StackPanel Orientation="Vertical" Spacing="8">
    <TextBlock>A simple TextBlock with unformatted text.</TextBlock>
    <TextBlock>
      <Run Text="A "></Run>
      <Run Classes="code">TextBlock</Run>
      <Run Text=" with "></Run>
      <Run FontWeight="Bold">differing</Run>
      <Run FontStyle="Italic" Text=" styles"></Run>
      <Run FontSize="24" Text=" and fonts"></Run>
      <Run>.</Run>
    </TextBlock>
    <TextBlock>
      <Run Text="A "></Run>
      <Run Classes="code" Foreground="Gray">TextBlock</Run>
      <Run Text=" with "></Run>
      <Run Foreground="Red">differing</Run>
      <Run Foreground="Green" Text=" colors"></Run>
      <Run>.</Run>
    </TextBlock>
    <TextBlock>
      <Run Text="A "></Run>
      <Run Classes="code">TextBlock</Run>
      <Run Text=" with "></Run>
      <Run Foreground="Orange" FontStyle="Italic" Text="{Binding}"></Run>
      <Run>.</Run>
    </TextBlock>
    <TextBlock>
      <Run Text="A "></Run>
      <Run Classes="code">TextBlock</Run>
      <Run Text=" with a "></Run>
      <LineBreak/>
      <Run>line break.</Run>
    </TextBlock>
  </StackPanel>
   
</Window>
```
As always: Regards,

Remco

**Comment by kekekeks** [comment]
`Run` (and the rest of the flow document model) isn't available in 0.9.x branch. You can either use nightly builds of wait for 0.10 release

**Comment by JamRemco** [comment]
O ok. thanx for the quik response

Remco

**Comment by grokys** [comment]
I don't think `Run` is implemented yet on the 0.10 branch either (`master` branch)? It is coming soon however. @Gillibald how far are we away from inlines support?

Going to close this as it's not actually an issue as such.

**Comment by Gillibald** [comment]
Haven't started working on it yet. Implementing Inlines support on top of current text processing API is trivial but not the best performing solution. I need to introduce some caching first. Ideally I could port WPF's TextContainer but that is currently nowhere near complete. Still undecided whether I should port existing code.

**Comment by agnauck** [comment]
is this supported now or still being worked on?

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/5461

I will spend more time on it next month

**Comment by LennartRipke** [comment]
Similar to @flarive34rs; I would love to colorize some words in a single line Text Control (TextBox, TextBlock, RichtTextBox, ...) to provide a very, very basic highlighting of keywords. 

[AvaloniaEdit](https://github.com/AvaloniaUI/AvaloniaEdit) seems a bit to large for single line use.

Thank you for your efforts!
