### ISSUE TITLE
[Feature Request] macOS: Ability to set window appearance

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/Avalonia#3742]
## Environment

* Latest Avalonia (c3c5a737694c47c00b801b784b0f6d4709d7ba3e as of this writing on 3 April 2020)
* macOS 10.14

## Feature Request

I'd like the ability to directly set the `NSWindow` appearance (`NSAppearance`) so that my app can have an easier way about switching between light and dark modes while keeping macOS's native title bar coloring for light vs dark. Right now, you can theoretically set the title bar color, which sets the `NSWindow` appearance to either `NSAppearanceNameVibrantLight` or `NSAppearanceNameVibrantDark`, but then the title bar is set to transparent, which gets rid of the nice native gradient-like effect on the title bar that macOS provides. 

I'm working around this issue in my app right now by doing (some code left out for brevity):

```csharp
if (IsDarkTheme)
{
    if (this.PlatformImpl is WindowImpl)
    {
        // set it to something dark so that appearance is set
        (this.PlatformImpl as WindowImpl).SetTitleBarColor(new Color(255, 53, 53, 53));
        // get the title bar back to being non-transparent
        (this.PlatformImpl as WindowImpl).SetSystemDecorations(SystemDecorations.Full);
    }
}
else
{
    if (this.PlatformImpl is WindowImpl)
    {
        // set it to something light so that appearance is set
        (this.PlatformImpl as WindowImpl).SetTitleBarColor(new Color(255, 223, 223, 223));
        // get the title bar back to being non-transparent
        (this.PlatformImpl as WindowImpl).SetSystemDecorations(SystemDecorations.Full);
    }
}
```

It'd be great to be able to do something like:

```csharp
(this.PlatformImpl as WindowImpl).SetAppearance(AppearanceNames.AppearanceNamesDark);
```

## Proposed Solution

I rigged up some sample code, but didn't like it very much due to the naming of some things and macOS-specific nature, so it's here instead. macOS native stuff would be the only one using `AppearanceNames`...perhaps it should instead be `AvaloniaTheme` with `Light` and `Dark` options instead like #3695 suggests.

```objc
enum AppearanceNames {
    AppearanceNamesLight,
    AppearanceNamesDark,
    AppearanceNamesVibrantLight,
    AppearanceNamesVibrantDark
};

virtual HRESULT SetWindowAppearance(AppearanceNames value) override
    {
        @autoreleasepool
        {
            switch (value)
            {
                case AppearanceNamesLight:
                    [Window setAppearance:[NSAppearance appearanceNamed:NSAppearanceNameAqua]];
                    break;
                case AppearanceNamesDark:
                    if (@available(macOS 10.14, *)) {
                        [Window setAppearance:[NSAppearance appearanceNamed:NSAppearanceNameDarkAqua]];
                    } else {
                        [Window setAppearance:[NSAppearance appearanceNamed:NSAppearanceNameVibrantDark]];
                    }
                    break;
                case AppearanceNamesVibrantLight:
                    [Window setAppearance:[NSAppearance appearanceNamed:NSAppearanceNameVibrantLight]];
                    break;
                case AppearanceNamesVibrantDark:
                    [Window setAppearance:[NSAppearance appearanceNamed:NSAppearanceNameVibrantDark]];
                    break;
            }
            
            return S_OK;
        }
    }
```

I'd be happy to open a PR for this with any suggested changes if ya'll want.

**Comment by kekekeks** [comment]
@Deadpikle Please, don't rush this, there are some existing plans for OSX titlebar styles, we'll document those soon-ish.

**Comment by Gillibald** [comment]
Is there an open issue about introducing a Hunts API. So requesting certain platform feature will be xplat and easy to use?

**Comment by kekekeks** [comment]
I'm afraid that advanced titlebar styles are way too platform-specific to be exposed as xplat API.

**Comment by Gillibald** [comment]
`RequestFeature("TitleBarColor", Colors.Red);`

Just some API that avoids casting to a specific platform implementation. If a platform implementation doesn't support certain features they are ignored.

**Comment by kekekeks** [comment]
I'd rather have a prefixed attached property on the regular `Window`. One isn't supposed to touch `IWindowImpl` since it's technically unstable private API.

**Comment by kekekeks** [comment]
See https://github.com/lukakerr/NSWindowStyles for *some* of the titlebar styles supported by OSX. Those are way too platform-specific to be expressed via xplat API. So we'll need `OSXTitleBarOptions.XXX` set of attached properties.

**Comment by Gillibald** [comment]
Y attached properties should work 👍

**Comment by Deadpikle** [comment]
> @Deadpikle Please, don't rush this, there are some existing plans for OSX titlebar styles, we'll document those soon-ish.

Affirmative. Apologies! 😅
