### ISSUE TITLE
Porting WPF UpdateSourceTrigger 

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#3754]
Having something like the WPF `Binding.UpdateSourceTrigger` (https://docs.microsoft.com/en-us/dotnet/api/system.windows.data.binding.updatesourcetrigger?view=netframework-4.8) in Avalonia would be helpful.

**Comment by mightypanda** [comment]
The missing UpdateSourceTrigger is a headache in some scenarios: 
for example:

- if you bind a numeric value to a visual property, you get unpleasant looking updates in the visual/shape while typing the number.
- If binding fires up a server-sync,  the server gets many more calls that are basically useless, as well as validation errors

**Comment by maxkatz6** [comment]
> If binding fires up a server-sync, the server gets many more calls that are basically useless, as well as validation errors

This part is expected to be managed on lower layer and not by View. With ReactiveUI it's quite simple using Throttle mechanism. It's always possible with some other third-parties.

> if you bind a numeric value to a visual property, you get unpleasant looking updates in the visual/shape while typing the number.


Agree, in some cases for binging between elements we care only about final value after lostfocus, so UpdateSourceTrigger will be really helpful in this case.

**Comment by mightypanda** [comment]
Yes, throttling can help but it is not semantically the same, also for client->server updates it makes sense the whole data is sent as soon as the field gets a input confirmation from the user, which is often modeled as a LostFocus event.

**Comment by dalekseev-monokot** [comment]
Hello, 

Is this feature in your roadmap? is there a chance to see it in the next release?

**Comment by kekekeks** [comment]
For now you can [use behaviors for a workaround](https://github.com/AvaloniaUI/Avalonia/issues/6071#issuecomment-861574988).

```xaml
        <TextBox>
            <Interaction.Behaviors>
                <example:LostFocusUpdateBindingBehavior Text="{Binding Text}"/>
            </Interaction.Behaviors>
        </TextBox>
```

It's a bit more verbose, but should solve your issue.

**Comment by pr8x** [comment]
Made a PR for this: #7797

**Comment by workgroupengineering** [comment]
Hi @Avaloniateam, is there any chance that the feature will be implemented? It's very annoying to add behaviors.

**Comment by MikeCodesDotNET** [comment]
There is a plan to look at the binding system but right now we're focused on shipping v11.

**Comment by heartacker** [comment]
> There is a plan to look at the binding system but right now we're focused on shipping v11.

thanks and add this to milestone V11
