### ISSUE TITLE
Problem with context menu popup swallowing right click.

### ISSUE THREAD

**Issue by igorstefus** [AvaloniaUI/Avalonia#3760]
If context menu is currently opened and if you open new one for different context host it will not pass pointer press event to control hosting context menu although context menu it self will show up.
We noticed this since we have case where items have context menu and can be selected. Because of this behavior when you right click on the first item it is selected and context popups as you would expected it.
However if context menu stays open and you click on another item it will now not be selected but context menu will popup any way.

**Comment by grokys** [comment]
Looking at WPF (and the rest of windows), it seems that some controls swallow the click that dismisses a popup and some don't.

For example, if you open a WPF `ComboBox` and click outside the popup, the click isn't registered on the control you click on. If you do the same with a `ContextMenu`, the click is registered.

I'm taking a look at WPF and UWP to try and work out if they have an API for this behavior, and how it works there.

**Comment by grokys** [comment]
Ok, it seems that in WPF, `Popup` never swallows the click that closes the popup when `StaysOpen="False"`: https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs#L1116

Instead `ComboBox` and `ContextMenu` leave `StaysOpen` at its default of `true` and instead implement their own closing logic:

https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ComboBox.cs#L1716
https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/MenuBase.cs#L161
