### ISSUE TITLE
GridSplitter Out of Range Exception.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#377]
@susloparovdenis Putting a vertical `GridSplitter` at column 0 or a horizontal `GridSplitter` at row 0 throws an `ArgumentOutOfRangeException` when attached to visual tree.

**Comment by susloparovdenis** [comment]
Unlike WPF GridSplitter, I made Perspex GridSplitter has only one Behavior, GridResizeBehavior.PreviousAndNext, because I think it's overhead. So it's not right to put it at first row or column. I should just throw an adequate exception.

**Comment by grokys** [comment]
I realise it's not correct to put it at the first row/column, but IMO it should do nothing rather than throw an exception.

**Comment by grokys** [comment]
This exception is actually currently causing the CI to fail (https://ci.appveyor.com/project/Perspex/perspex), although the exception does occur when run in Visual Studio...

**Comment by jkoritzinsky** [comment]
Fixed as part of #801.
