### ISSUE TITLE
Image source binding not working

### ISSUE THREAD

**Issue by TheChilliPL** [AvaloniaUI/Avalonia#3774]
In my view, I tried to bind image source to a string and it didn't work, despite the exact same code works in a project of a friend of mine. Both of us tried to find the cause of it but we didn't find anything.
```xml
<!-- MainWindow.xaml -->
<Image Source="{Binding ImagePath}"/>
```
```cs
// MainWindowViewModel.cs
public string ImagePath => "/Assets/image.png";
```
Note that writing path directly into the view like below does work.
```xml
<!-- MainWindow.xaml -->
<Image Source="/Assets/image.png"/>
```
Also, I've tried to bind it by Bitmap (with a custom string to bitmap converter too) but couldn't find a way to load AvaloniaResource from code.
Everything was tried on multiple versions of Avalonia, nothing worked.

**Comment by kekekeks** [comment]
Type converters don't work for bindings. It's the common behavior across XAML frameworks.

You need to use a Converter for the binding manually.

**Comment by TheChilliPL** [comment]
I have tried but didn't find a way to load AvaloniaResource.
Additionally, binding Image Source to string did work for a friend of mine in another project, but we haven't been able to find why

**Comment by TheChilliPL** [comment]
Umm, I downloaded the friend's program and after I compiled it, the image binding didn't work. It did, though, with the exe compiled by the friend.

**Comment by FoggyFinder** [comment]
Can you attach reproducible sample?

**Comment by TheChilliPL** [comment]
Oh, and now when my friend compiled his own program, it doesn't work either

**Comment by TheChilliPL** [comment]
I'll try to do something quickly @FoggyFinder

**Comment by FoggyFinder** [comment]
Seems like it's not implemented yet:

#853 

#2208

**Comment by TheChilliPL** [comment]
It did work when my friend compiled it, though. I've got a working sample and he didn't change its code, but it doesn't work anymore and it's not a public program

**Comment by TheChilliPL** [comment]
Here you can see that binding doesn't work
![image](https://user-images.githubusercontent.com/18823939/79053079-d1eae100-7c3a-11ea-804d-fe787e775138.png)

[TestAvaloniaImageBinding.zip](https://github.com/AvaloniaUI/Avalonia/files/4465249/TestAvaloniaImageBinding.zip)

**Comment by TheChilliPL** [comment]
There might be a mistake with it working. I think that version was made in WPF.
On Avalonia, it just doesn't work but additionally, I can't find a way to make it work using a custom converter. Any idea of how to do so?

**Comment by TheChilliPL** [comment]
```cs
var assets = AvaloniaLocator.Current.GetService<IAssetLoader>();
return new Bitmap(assets.Open(new Uri("avares://TestAvaloniaImageBinding/Assets/github-logo.png")));
```
seems to work. I'll try to post a working converter there in case anyone has a similar issue and then I'll close it

**Comment by xuejinfeng1989** [comment]
Note that Bitmap under the Avalonia.Media.Imaging namespace is used instead of Bitmap under System.Drawing
