### ISSUE TITLE
TextBox can't get input method in linux.

### ISSUE THREAD

**Issue by Codexiaoyi** [AvaloniaUI/Avalonia#3779]
TextBox cannot get input method in Linux, resulting in can't input non-English characters.
I know the textbox will be rewritten, but is there a faster solution now?

**Comment by Gillibald** [comment]
Input Method support is on the roadmap but no fixed release date when that will come.

**Comment by Codexiaoyi** [comment]
Ok! I have read the roadmap.If there is no quick temporary solution, then I will wait for the new version. 
thank you for your answer.

**Comment by kekekeks** [comment]
@Codexiaoyi just for the reference: which input method are you using? We are currently planning to implement native ibus and may be other input methods via XIM.

**Comment by Codexiaoyi** [comment]
> @Codexiaoyi just for the reference: which input method are you using? We are currently planning to implement ibus natively and may be other input methods via XIM.

I used sogou,google,ibus in the ubuntu,centos,deepin.I can’t wait to try ibus or other input methods  because I can't type Chinese in the linux, I will keep up with new commits and test it,thank you.
