### ISSUE TITLE
TextBox do not support Chinese charset?

### ISSUE THREAD

**Issue by jzlhll** [AvaloniaUI/Avalonia#3780]
OSX: MacBook Pro (Retina, 15-inch, Mid 2015)
Avalonia: 0.9.7

TextBox input issue.

When input Chinese charset such as "我们"，it shows two blank rectangles.
You can try it with commond + C to paste it.

Maybe it is an issue about unicode / ascii charset, something like this.

**Comment by Gillibald** [comment]
Current TextBox is very limited and needs a rework that will come at some point this year.

**Comment by Codexiaoyi** [comment]
> OSX: MacBook Pro (Retina, 15-inch, Mid 2015)
> Avalonia: 0.9.7
> 
> TextBox input issue.
> 
> When input Chinese charset such as "我们"，it shows two blank rectangles.
> You can try it with commond + C to paste it.
> 
> Maybe it is an issue about unicode / ascii charset, something like this.
> 
> Finally, I found that change the font family will be help.
> If the TextBlock/TextBox FontFamily change to "黑体", "宋体", it works well.
> For Chinese guys or other ones.

您这边在mac上可以正常使用TextBox输入中文吗？

**Comment by jzlhll** [comment]
> > OSX: MacBook Pro (Retina, 15-inch, Mid 2015)
> > Avalonia: 0.9.7
> > TextBox input issue.
> > When input Chinese charset such as "我们"，it shows two blank rectangles.
> > You can try it with commond + C to paste it.
> > Maybe it is an issue about unicode / ascii charset, something like this.
> > Finally, I found that change the font family will be help.
> > If the TextBlock/TextBox FontFamily change to "黑体", "宋体", it works well.
> > For Chinese guys or other ones.
> 
> 您这边在mac上可以正常使用TextBox输入中文吗？

修改TextBox的fontFamily可以解决。

**Comment by Codexiaoyi** [comment]
> 修改TextBox的fontFamily可以解决。

我是在linux上跑，修改fontfamily确实可以解决显示问题，不过还是不能正常打字输入，是可以复制粘贴进去，原因是无法支持输入法。我在前面的issue中提过，官方说在适配输入法，我还是想先找到一个可以暂时替代的方案，如果您有临时的解决方案，麻烦您告诉我一下谢谢。

**Comment by jzlhll** [comment]
> > 修改TextBox的fontFamily可以解决。
> 
> 我是在linux上跑，修改fontfamily确实可以解决显示问题，不过还是不能正常打字输入，是可以复制粘贴进去，原因是无法支持输入法。我在前面的issue中提过，官方说在适配输入法，我还是想先找到一个可以暂时替代的方案，如果您有临时的解决方案，麻烦您告诉我一下谢谢。

mac看来是可以的。linux没试过。也许是linux独有的bug吧。

**Comment by FreezeSoul** [comment]
关注这个问题

**Comment by wuzlai** [comment]
> > > OSX: MacBook Pro (Retina, 15-inch, Mid 2015)
> > > Avalonia: 0.9.7
> > > TextBox input issue.
> > > When input Chinese charset such as "我们"，it shows two blank rectangles.
> > > You can try it with commond + C to paste it.
> > > Maybe it is an issue about unicode / ascii charset, something like this.
> > > Finally, I found that change the font family will be help.
> > > If the TextBlock/TextBox FontFamily change to "黑体", "宋体", it works well.
> > > For Chinese guys or other ones.
> > 
> > 
> > 您这边在mac上可以正常使用TextBox输入中文吗？
> 
> 修改TextBox的fontFamily可以解决。
你好，我现在我也遇到了这个问题，在mac系统显示中文是乱码的。请问是怎么解决的了？ Content="写邮件" FontFamily="宋体" ？？

**Comment by Codexiaoyi** [comment]
> 你好，我现在我也遇到了这个问题，在mac系统显示中文是乱码的。请问是怎么解决的了？ Content="写邮件" FontFamily="宋体" ？？

按理来说是可以的。我在linux发现你想要的字体可能系统没有，所以我干脆找到Avalonia源码，模仿源码的添加字体方式，添加自己的字体并引用，效果不错。

**Comment by wuzlai** [comment]
> > 你好，我现在我也遇到了这个问题，在mac系统显示中文是乱码的。请问是怎么解决的了？ Content="写邮件" FontFamily="宋体" ？？
> 
> 按理来说是可以的。我在linux发现你想要的字体可能系统没有，所以我干脆找到Avalonia源码，模仿源码的添加字体方式，添加自己的字体并引用，效果不错。

你好，我直接修改FontFamily，在mac下还是乱码，能不能给个例子。我参考下你之前 添加的字体代码了。或者麻烦告诉下源代码中哪个目录文件是 自定义字体的了，谢谢了

**Comment by Codexiaoyi** [comment]
> 你好，我直接修改FontFamily，在mac下还是乱码，能不能给个例子。我参考下你之前 添加的字体代码了。或者麻烦告诉下源代码中哪个目录文件是 自定义字体的了，谢谢了

https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/TextBlockPage.xaml
抱歉，例子不能给您，就是模仿上面的37行这样写在全局（记得添加字体文件），我记得Avalonia文档里面也有类似的自定义字体的介绍。

**Comment by wuzlai** [comment]
> > 你好，我直接修改FontFamily，在mac下还是乱码，能不能给个例子。我参考下你之前 添加的字体代码了。或者麻烦告诉下源代码中哪个目录文件是 自定义字体的了，谢谢了
> 
> https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/TextBlockPage.xaml
> 抱歉，例子不能给您，就是模仿上面的37行这样写在全局（记得添加字体文件），我记得Avalonia文档里面也有类似的自定义字体的介绍。

好的， 非常感谢！

**Comment by JasonGrass** [comment]
我这里直接设置系统字体可以解决，将 FontFamily 设置为 ` "Microsoft YaHei,Simsun,苹方-简,宋体-简" `。
详见：[AvaloniaUI TextBox 不能显示中文的问题解决 - J.晒太阳的猫](https://www.cnblogs.com/jasongrass/p/13758003.html )

**Comment by wuzlai** [comment]
> 我这里直接设置系统字体可以解决，将 FontFamily 设置为 `"Microsoft YaHei,Simsun,苹方-简,宋体-简"`。
> 详见：[AvaloniaUI TextBox 不能显示中文的问题解决 - J.晒太阳的猫](https://www.cnblogs.com/jasongrass/p/13758003.html)

谢谢。提供的方法很有效果。解决了大问题，感谢！

**Comment by tianxia467099532** [comment]
ubuntu18.0.4上把系统语言设置成中文简体，运行程序没有响应界面都不会显示出来, 如果把系统语言设置英文，则可以运行成功。

**Comment by chenjing1294** [comment]
As of May 13, 2022, it is still not possible to input Chinese characters

**Comment by Gillibald** [comment]
Only current master supports this. Please try out a current nightly build.

**Comment by kekekeks** [comment]
@chenjing1294 you need to use WenQuanYi Micro Hei font:
https://github.com/AvaloniaUI/Avalonia/blob/4c1afa2dff45991fcb182ef41d86678e0f19a5f8/samples/ControlCatalog/Pages/TextBoxPage.xaml#L86-L89

**Comment by sky92archangel** [comment]
Just add this :

```
<Window.Styles>		 
	<Style Selector="TextBox">
		<Setter Property="FontFamily" Value="Microsoft YaHei,Simsun,苹方-简,宋体-简"/>
	</Style>
	<Style Selector="DataGrid">
		<Setter Property="FontFamily" Value="Microsoft YaHei,Simsun,苹方-简,宋体-简"/>
	</Style>
</Window.Styles>
```
