### ISSUE TITLE
Blank window with SizeToContent

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#3784]
The following XAML:

```xml
<Window xmlns="https://github.com/avaloniaui"                               
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"        
        xmlns:idc="clr-namespace:ControlCatalog.ProportionalStackPanel"
        x:Class="ControlCatalog.MainWindow" 
        SizeToContent="WidthAndHeight">
  <Border Height="12000" Width="20" Background="Red" />
</Window>
```

Produces a blank window until resized.

**Comment by grokys** [comment]
Problem seems to be that the bounds on the `Border` are `0, -5290 ,200, 1200`.

**Comment by grokys** [comment]
Interestingly if one changes the height to `2000` then the red border is shown some way down the window, even though its bounds are `0, -290, 200, 2000`. WTF?

![image](https://user-images.githubusercontent.com/1775141/79262307-651d5400-7e91-11ea-8d59-6eeab99a5222.png)

**Comment by kekekeks** [comment]
@grokys this happens because Window height is constrained by MaxClientSize and our layout can't deal with ClientSize not meeting the needs of the control inside. You can observe the same effect by disabling size constraints in IWindowImpl implementation and having a control with exact size.

**Comment by grokys** [comment]
Ah yeah, I vaguely remember this being talked about. Will try to fix it.

**Comment by kekekeks** [comment]
Also see https://github.com/zkSNACKs/WalletWasabi/issues/1822
