### ISSUE TITLE
where is the NativeControlHost in the latest Released!

### ISSUE THREAD

**Issue by Shadow4walker** [AvaloniaUI/Avalonia#3785]
I'm trying to Update Avalonia Package in some existing project to The latest released
it's use this version of Avalonia(0.9.3-cibuild0006194-beta) when update to the latest v the NativeControlHost goes missing!
how to Update to the latest released and get ride of the missing NativeControlHost control?
this is project which I'm trying to Update 
[CefGlue.Avalonia](https://gitlab.com/joaompneves/cefglue/-/blob/3770/CefGlue.Avalonia/Platform/ExtendedAvaloniaNativeControlHost.cs)
any hint for this please?

**Comment by kekekeks** [comment]
Control host is planned for 0.10 since it involves breaking changes.
