### ISSUE TITLE
TreeView.SelectedItems is keeping items alive

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#3786]
It seems like `TreeView.SelectedItems` keeps the items alive even when they get deleted from the `TreeView.Items` collection.
I do know that SelectionModel is coming up, just wanted to share this to stress the importance of it getting merged rather soon 😅

**Comment by iXinwei** [comment]
from an ameteur : I was even struggling to figure out how to use the TreeView and Binding....
