### ISSUE TITLE
Style Without Trigger, need HELP

### ISSUE THREAD

**Issue by Rukid** [AvaloniaUI/Avalonia#3789]
Hello, in wpf i have style for checkbox

```
<Style x:Key="LEDCheckBox" TargetType="CheckBox">
        <Setter Property="SnapsToDevicePixels" Value="true"/>
        <Setter Property="OverridesDefaultStyle" Value="true"/>
        <Setter Property="IsEnabled" Value="False"/>
        <Setter Property="ToolTipService.ShowOnDisabled" Value="True" />
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="CheckBox">
                    <Ellipse x:Name="Border" 
                          Width="{TemplateBinding Width}" 
                          Height="{TemplateBinding Height}" 
                          Stroke="Gray" StrokeThickness="1">
                    </Ellipse>
                    <ControlTemplate.Triggers>
                        <Trigger Property="IsChecked" Value="True">
                            <Setter TargetName="Border" Property="Fill" Value="#7FFFD4"/>
                        </Trigger>
                        <Trigger Property="IsChecked" Value="False">
                            <Setter TargetName="Border" Property="Fill" Value="#F9B5B5"/>
                        </Trigger>
                    </ControlTemplate.Triggers>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
```

How to use it in avalonia without trigger and converters?

**Comment by danwalmsley** [comment]
`<Style x:Key="LEDCheckBox" TargetType="CheckBox">` can be:
`<Style Selector="CheckBox">`

**Comment by danwalmsley** [comment]
` <Style Selector="CheckBox:checked">
  </Style>
`

To target the control when its checked...

**Comment by danwalmsley** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Default/CheckBox.xaml

if you want to replace the checkbox template,,, start with the default one here.

**Comment by Rukid** [comment]
Thank's alot. If someone interested i changed my code to:
`<Style Selector="CheckBox">
    <Setter Property="IsEnabled" Value="False"/>
    <Setter Property="Template">
      <ControlTemplate>
        <Ellipse x:Name="border"
                 Width="{TemplateBinding Width}"
                 Height="{TemplateBinding Height}"
                 Stroke="Gray" StrokeThickness="1">
        </Ellipse>
      </ControlTemplate>
    </Setter>
  </Style>

  <Style Selector="CheckBox:checked /template/ Ellipse#border">
    <Setter Property="Fill" Value="#7FFFD4"></Setter>
  </Style>

  <Style Selector="CheckBox:unchecked /template/ Ellipse#border">
    <Setter Property="Fill" Value="#F9B5B5"></Setter>
  </Style>
`
