### ISSUE TITLE
ScrollViewer doesn't show scrollbars sometimes with SizeToContent

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#3791]
If you take the following XAML:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:idc="clr-namespace:ControlCatalog.ProportionalStackPanel"
        x:Class="ControlCatalog.MainWindow"
        SizeToContent="WidthAndHeight">
  <ScrollViewer>
    <Border Height="12000" Width="20" Background="Red" />
  </ScrollViewer>
</Window>
```

and run on Windows the content is displayed without a scrollbar, even though the full `Border` isn't visible.

**Comment by danwalmsley** [comment]
related to: https://github.com/zkSNACKs/WalletWasabi/issues/3462

**Comment by grokys** [comment]
This happens because the window has `SizeToContent="WidthAndHeight"` set, which causes the controls in the `Window` to be measured with `Size.Infinity`. When the window is arranged, Avalonia then tries set to a height of 12000 which is larger than the maximum window height allowed by the OS.

This causes the `Arrange` pass to be invoked with a `finalSize` of less than the `DesiredSize` of `ScrollViewer`. The template for `ScrollViewer` contains a `Grid`, and `Grid` does not like this: seems that if you arrange a `Grid` with a size less than its `DesiredSize`, it will ignore the request and just use `DesiredSize`.

This doesn't cause a problem in WPF, because a `Window`'s content is measured with the max window size instead of infinity.

**Comment by grokys** [comment]
There are a few solutions I can see to this:

- Measure the window with the max client size instead of infinity. We used to do this, but that behavior was changed by https://github.com/AvaloniaUI/Avalonia/pull/1021 - unfortunately there's no explanation of why it was changed
  - Maybe it would be tricky to do x-plat and accounting for multiple monitors? The backends currently have a [naive implementation[(https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/X11Window.cs#L918) which doesn't look like it would work well with multiple monitors -- @kekekeks ?
- Measure the window twice, once with infinity and then again if, after setting the window size, it's not what we requested
  - Would result in two measure passes
- Fix `Grid`
  - Might be a good idea, but do we want to risk changing `Grid`'s behavior from that of WPF?

**Comment by danwalmsley** [comment]
I'd bet that very few if anyone is relying on this behavior in Grid, maybe if we fixed it, but all the existing grid tests still passed it would be acceptable to fix this in Grid... might turn out thats not possible though.

**Comment by danwalmsley** [comment]
If there is a nice easy fix, we can also submit it to WPF repo

**Comment by kekekeks** [comment]
>Maybe it would be tricky to do x-plat and accounting for multiple monitors

We'll need `MaxClientSizeChanged` event then.

**Comment by kekekeks** [comment]
Also, keep in mind that `MaxClientSize` isn't a hard limit: window can be manually resized to a larger size. It's mostly needed for auto-sizing purposes.

**Comment by grokys** [comment]
> We'll need MaxClientSizeChanged event then.

Could you explain?

**Comment by danwalmsley** [comment]
@grokys couldnt we say if Grid gets an arrange < what it measured... then we have to remeasure first... or is that a giant hack?

**Comment by grokys** [comment]
> couldnt we say if Grid gets an arrange < what it measured... then we have to remeasure first... or is that a giant hack?

Yep, that's solution 2 in https://github.com/AvaloniaUI/Avalonia/issues/3791#issuecomment-614809655 - and yeah it is a giant hack ;)

**Comment by MaxHillebrand** [comment]
I have tested @danwalmsley [wasabi branch which updates avalonia](https://github.com/danwalmsley/WalletWasabi/tree/test-new-avalonia-layout-fixes), and here the scrollbar issue is fixed!

ACK and thank you all!

![screenshot_20200420_184426](https://user-images.githubusercontent.com/30683012/79777315-5b836880-8337-11ea-94f9-7647ac432a4a.png)
