### ISSUE TITLE
Gtk-CRITICAL error using OpenFileDialog

### ISSUE THREAD

**Issue by AntonioRomi** [AvaloniaUI/Avalonia#3794]
```C#
private Task<string[]> OpenFilesAsync(Window window)
{
    var ofd = new OpenFileDialog
    {
        InitialFileName = "sample",
        AllowMultiple = true,
        Title = Title
     };

     return ofd.ShowAsync(window);
}
```
This code causes displaying error in console:
`Gtk-CRITICAL **: gtk_file_chooser_widget_set_current_name: assertion 'priv->action == GTK_FILE_CHOOSER_ACTION_SAVE || priv->action == GTK_FILE_CHOOSER_ACTION_CREATE_FOLDER' failed`

**Comment by kekekeks** [comment]
fixed in master
