### ISSUE TITLE
Issues with screens API

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#3795]
Screens.FromPoint and Screens.FromVisual do not provide a reliable way to get which screen the window is really on.

Not possible until the window has been shown, and also doesnt take into account what happens when 49% of a window is on 1 monitor and 51% on another.

**Comment by grokys** [comment]
Yeah, I've only just had to use the screens API, and it could use some work:

# Get the screen for a window

As you say, there's no API for this. The only way to do this reliably x-plat would be a native call I think.

# ScreenFromVisual/ScreenFromBounds

The logic for `ScreenFromBounds` looks like it's trying to do something that might be used to get the screen for a window, but it provides its own heuristic which may be different to the OS. I'm struggling to think of another use for this API... Is it used in docking code?

# Screens.ScreenCount

Why does `Screens` expose a `ScreenCount` as well as the `All` collection, which has a `Count` property? I assume it's to prevent having to enumerate the screens but what is the use-case for knowing the number of screens without having more info about these screens?

# Screen.Primary

Should be called `IsPrimary`.

# IScreenImpl

The name `IScreenImpl` suggests that it should be the platform impl for the `Screen` class, but it's not - it's the platform impl for `Screens`. Should be called `IScreensImpl`.

**Comment by danwalmsley** [comment]
win32:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-monitorfromwindow

osx:
seems to suggest use the largest intersection.
https://stackoverflow.com/questions/7850685/determine-which-screen-a-window-is-on-given-the-window-id

x11: @kekekeks ?

**Comment by kekekeks** [comment]
With X11 we could probably save the screen detected here:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/X11Window.cs#L519

**Comment by danwalmsley** [comment]
@kekekeks is that going to be reliable? 

here: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/X11Window.cs#L521

you have a null check. so on some platforms you may not have determined any monitor...

for example here: 
on ubuntu no screen was found, (this was in my code, but it did something similar)
https://github.com/zkSNACKs/WalletWasabi/issues/3554

**Comment by kekekeks** [comment]
Another huge issue with our screens API: it turned out that OSX uses *logical* coordinate space for window locations and sizes. We have a workaround for popup positioner, but it has to be fixed everywhere.

**Comment by kekekeks** [comment]
>you have a null check

That's why I've said "save". The null check is there because top-left corner might be moved outside of the screen bounds. We assume that window hasn't changed its monitor in that case.

**Comment by danwalmsley** [comment]
> Another huge issue with our screens API: it turned out that OSX uses _logical_ coordinate space for window locations and sizes. We have a workaround for popup positioner, but it has to be fixed everywhere.

Thats probably why on OSX StartupWindowLocation = "Center" or "CenterOwner" doesnt work on OSX.

**Comment by danwalmsley** [comment]
> > you have a null check
> 
> That's why I've said "save". The null check is there because top-left corner might be moved outside of the screen bounds. We assume that window hasn't changed its monitor in that case.

but even the first time, is it guarenteed to return a screen, the linked wasabi issue was crashing on first run.

**Comment by kekekeks** [comment]
Constructor can save the closest one, I guess.

**Comment by danwalmsley** [comment]
Note: On OSX, NSWindow has a `screen` property... hopefully this is equivalent to the monitor your own.

**Comment by danwalmsley** [comment]
```
var screen: NSScreen?
The screen the window is on.

var deepestScreen: NSScreen?
The deepest screen the window is on (it may be split over several screens).
```

not sure what it means deepest.
