### ISSUE TITLE
Setting or Binding to Window Height / Width Properties has no effect.

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#3796]
```
        public MainWindow()
        {
            InitializeComponent();

            Observable.Interval(TimeSpan.FromSeconds(0.5))
                .ObserveOn(RxApp.MainThreadScheduler)
                .Subscribe(_ =>
                {
                    Height += 10;
                });
```

This code should make the window increase size every half second.

This is ignored.

**Comment by grokys** [comment]
In addition, popups are no longer sizing correctly :(

![image](https://user-images.githubusercontent.com/1775141/79584443-aea6b280-80ce-11ea-8676-90c052aed2dc.png)

Caused by #3787 I think.
