### ISSUE TITLE
Issue on MacOS with Window at start of app

### ISSUE THREAD

**Issue by oiuldashov** [AvaloniaUI/Avalonia#3801]
Hello.

I have 2 issues on MacOS with Window at start of app:
1. It start not at center of screen with WindowStartupLocation="CenterScreen"
2. I see red rectangle on the Window place for 0.5 seconds when app starts.

Avalonia: 0.9.6

OS: macOS Catalina 10.15.3
Hardware: MacBook Pro (15-inch, 2019) 
Processor: 2,6 GHz 6-Core Intel Core i7
Graphics:Radeon Pro 555X 4 GB; Intel UHD Graphics 630 1536 MB

I had tested this app on another MacBook with same result.

Config of AppBuilder:

        public static AppBuilder BuildAvaloniaApp()
        {
            return AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToDebug()
                .UseSkia()
                .UseReactiveUI();
        }

![example gif](https://user-images.githubusercontent.com/10095333/79787090-1834f400-834f-11ea-9793-2d7cc10edfc3.gif)

**Comment by danwalmsley** [comment]
@oiuldashov any chance of a minimal repro we can debug?

**Comment by mat1jaczyyy** [comment]
I also get red rectangle over at mat1jaczyyy/apollo-studio

**Comment by oiuldashov** [comment]
@danwalmsley https://github.com/oiuldashov/avalonia_red_rectangle_issue

**Comment by Enoq00** [comment]
Hi all. i had same issue on macOS Catalina. Any news???

**Comment by maxkatz6** [comment]
Red flickering was fixed https://github.com/AvaloniaUI/Avalonia/pull/6250
