### ISSUE TITLE
Can not set IsFocused on AutoCompleteBox in XAML

### ISSUE THREAD

**Issue by JamRemco** [AvaloniaUI/Avalonia#3803]
Hello World,

I am Trying to set the focus on the AutoCompleteBox

Error

> System.MethodAccessException: 'Attempt by method 'Poging3.Views.MainWindow.!XamlIlPopulate(System.IServiceProvider, Poging3.Views.MainWindow)' to access method 'Avalonia.Input.InputElement.set_IsFocused(Boolean)' failed.'

I read on an older post that that property is/was Readonly  but the doc's  @ [https://avaloniaui.net/api/Avalonia.Controls/AutoCompleteBox/](url) states: 

![image](https://user-images.githubusercontent.com/58340108/79807086-3825e100-836a-11ea-978e-5a3994d33988.png)

but there is no such property (in xaml)
![image](https://user-images.githubusercontent.com/58340108/79807178-728f7e00-836a-11ea-93c4-13eab3b6d92e.png)

Not sure wich one  is wrong.
If you need to know more,  let me know

Regards,

Remco

**Comment by grokys** [comment]
`IsFocused` is indeed readonly: see https://github.com/AvaloniaUI/Avalonia/blob/756adb5dd5467ba5f0de000008d4c91009bfb2db/src/Avalonia.Input/InputElement.cs#L347-L351

Not sure why the docs are saying it's read/write. I'm in the process of redoing the docs so hopefully will be fixed soon.

In the meantime, you need to call `.Focus()` on your control to focus it.

**Comment by grokys** [comment]
Ah it's just the XML doc comment that was wrong, that has been fixed. Will be fixed on the API reference when I upload the new version.

**Comment by JamRemco** [comment]
Top
