### ISSUE TITLE
Calendar not updating selected date from binding

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#3804]
Avalonia 0.9.9
The Calendar control displays the selected date correctly when first displayed. But when when SelectedDate changes via view model binding it does not update the selected day in the UI until I interact with the control; e.g. move to the next month.

````
<Calendar SelectedDate="{Binding Date}"/>
````

Here is the UI after the bound Date is changed from 21st to the 15th. As you can see, the selected date is still 21 after the bound Date changed to 15.
![image](https://user-images.githubusercontent.com/17591364/79865217-b61dd280-83d2-11ea-941f-9a8c75f305fc.png)

Another issue is the selected day background colour makes the day number unreadable in both light and dark themes on some displays.

**Comment by MikeCodesDotNET** [comment]
Works as expected with v11.
