### ISSUE TITLE
macOSX: Title and Filters not showing in SaveFileDialog

### ISSUE THREAD

**Issue by ElMostafaIdrassi** [AvaloniaUI/Avalonia#3809]
![image](https://user-images.githubusercontent.com/25257376/80045535-3a697600-84f7-11ea-9243-5cd8a5b735e7.png)

Avalonia 0.9.7
.Net Core 3.1
OSX 10.15

Repro : [Link](https://github.com/ElMostafaIdrassi/Misc/tree/master/AvaloniaTestProject)

**Comment by ElMostafaIdrassi** [comment]
But other GUI libraries can show both the filters and the title / message correctly (i.e. wxWidgets used by VeraCrypt).

![image](https://user-images.githubusercontent.com/25257376/80109396-f87b1700-856c-11ea-8b79-332fc68ec5be.png)

Here is the [implementation ](https://github.com/wxWidgets/wxWidgets/blob/master/src/osx/cocoa/filedlg.mm#L306) by wxWidgets.

What I could gather :
- For the title, they call setMessage on the NSSavePanel (while in Avalonia, the title is set using panel.title = ...)
- For the filters, they pass the extensions as an NSArray* to setAllowedFileTypes then call setAllowsOtherFileTypes with NO.

I'm willing to implement these changes and see if they solve the issue, but I cannot seem to be able to build Avalonia on macOS as I'm facing issues / exceptions related to Sharpgen. Do you happen to have some guidelines on that ?

**Comment by danwalmsley** [comment]
@ElMostafaIdrassi you need to install exactly dotnet sdk version: `3.1.101`

**Comment by ElMostafaIdrassi** [comment]
@danwalmsley I'll give it a try and get back to you asap

**Comment by kekekeks** [comment]
Also make sure to install the correct version of `castxml` since the recent update has broken our tooling.

Use 
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/8a004a91a7fcd3f6620d5b01b6541ff0a640ffba/Formula/castxml.rb`

**Comment by ElMostafaIdrassi** [comment]
@danwalmsley @kekekeks Thank you, now I can compile Avalonia and the ControlCatalog project just fine on macOS.

Concerning the issue, it appears that, in order to have all the file types in a dropdown and allow the user to actively select each one, wxWidgets and other GUI libraries create their own **"extra"** view  where they implement the dropdown of file types and all the logic behind manually, then they set the view using NSSavePanel's **setAccessoryView**. I assume this would require some work to implement and to test properly. I'll have a look at it when I'll have some more time.

For the title part of the issue, just setting it to the panel's message solves it.

**Comment by kekekeks** [comment]
`setAccessoryView` is deprecated in OS X v10.5

**Comment by ElMostafaIdrassi** [comment]
@kekekeks Not so sure about that. You might be talking about `setAccessoryView` of `NSPageLayout` which is, as you mentionned, deprecated as stated [here](https://developer.apple.com/documentation/appkit/nspagelayout/1397786-setaccessoryview?language=objc). But for `NSSavePanel`, `setAccessoryView` is merely the setter of the `accessoryView` property (see [here](https://developer.apple.com/documentation/appkit/nssavepanel/1525544-accessoryview?language=objc)). You can double check by navigating to `AppKit/NSSavePanel.h` and see that `accessoryView` is not deprecated. Also, XCode does not warn you for deprecation when you write `[panel setAccessoryView:view]`.

**Comment by danwalmsley** [comment]
@ElMostafaIdrassi so can this issue be closed? or can we expect a PR for the filters?

**Comment by ElMostafaIdrassi** [comment]
@danwalmsley Not in the near future I'm afraid. Therefore, I'm closing the issue and will mention it in a PR if and once I get it all sorted out.
