### ISSUE TITLE
Styles of custom controls

### ISSUE THREAD

**Issue by Rukid** [AvaloniaUI/Avalonia#3812]
i create custom RadioButton 
```
public class RadioToggleButton : RadioButton
    {
        protected override void OnClick()
        {
            bool? wasChecked = this.IsChecked;
            base.OnClick();
            if (wasChecked == true)
                this.IsChecked = false;
        }
    }
```
And when i use it in xaml 

`<userControls:RadioToggleButton x:Name="inputToggle" Grid.Row="1"></userControls:RadioToggleButton>`

i can see only empty space

**Comment by Deadpikle** [comment]
Try:

```csharp
using Avalonia.Styling;

public class RadioToggleButton : RadioButton, IStyleable
{
    Type IStyleable.StyleKey => typeof(RadioButton);

    protected override void OnClick()
    {
        bool? wasChecked = this.IsChecked;
        base.OnClick();
        if (wasChecked == true)
            this.IsChecked = false;
    }
}
```

**Comment by Rukid** [comment]
> Try:
> 
> ```cs
> using Avalonia.Styling;
> 
> public class RadioToggleButton : RadioButton, IStyleable
> {
>     Type IStyleable.StyleKey => typeof(RadioButton);
> 
>     protected override void OnClick()
>     {
>         bool? wasChecked = this.IsChecked;
>         base.OnClick();
>         if (wasChecked == true)
>             this.IsChecked = false;
>     }
> }
> ```

Wow, nice. Thank's alot
