### ISSUE TITLE
Templates for something that is not IControl

### ISSUE THREAD

**Issue by mishun** [AvaloniaUI/Avalonia#3817]
Hi!
That is more of a question that an issue, but should it be possible by design to generate something with template when that something doesn't implement IControl?
I tried writing simple class (closely following DataTemplate implementation):
```c#
    public class StuffTemplate
    {
        public Type DataType { get; set; }

        [Content]
        [TemplateContent]
        public object Content { get; set; }

        public bool SupportsRecycling { get; set; } = true;

        public bool Match(object data)
        {
            if (this.DataType is null)
                return true;
            else
                return this.DataType.IsInstanceOfType(data);
        }

        public object Build(object data)
        {
            if (this.Content is Func<IServiceProvider, object> direct)
                // do stuff...
        }
    }
```
, defined StuffTemplate in XAML with content which is not IControl, and it failed, but failed at the very-very end when it tried to cast result to IControl here:
https://github.com/AvaloniaUI/Avalonia/blob/756adb5dd5467ba5f0de000008d4c91009bfb2db/src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/XamlIlRuntimeHelpers.cs#L28
It seems it should work if only cast to IControl is removed.

**Comment by kekekeks** [comment]
We should probably change it from `ControlTemplateResult` to `TemplateResult<T>`, but that will require changes in compiler.

**Comment by mishun** [comment]
I'm sorry, I don't exactly understand where T for TemplateResult<T> should come from. And compiler just throws object around. It seems instead of a closure containing the line I cited above, just Func<IServiceProvider, ValueTuple<object, INameScope>> can be used and Bob's your uncle :)

**Comment by kekekeks** [comment]
`ControlTemplateResult` is strongly typed. To keep said strong typing, our `DeferredTransformationFactoryV*` method should return `TemplateResult<T>`. Where said T will come from?

**Comment by mishun** [comment]
I don't exactly understand about "strongly typed" part: `return new ControlTemplateResult((IControl)obj, scope)` immediately casts it to object, since `DeferredTransformationFactoryV1`'s return type is `Func<IServiceProvider, object>`.

What I've meant above is that changing `DeferredTransformationFactoryV1`'s return type to `Func<IServiceProvider, (object, INameScope)>`, adding something like:
```c#
class XamlTemplateBase<Arg, Res> : ITemplate<Arg, (Res, INameScope)> where Arg : IServiceProvider
{
    [Content]
    [TemplateContent]
    public object Content { get; set; }

    public Type TargetType { get; set; }

    public (Res, INameScope) Build(Arg arg)
    {
        if (this.Content is Func<IServiceProvider, object> direct)
        {
            var (boxed, scope) = direct((IServiceProvider)arg);
            if (boxed is Res result)
                return (result, scope); // Or TemplateResult<Res>(result, scope)
        }
        throw ...;
    }
}
```
and inheriting `ControlTemplate` from `XamlTemplateBase<IServiceProvider, IControl>` is of course not statically typed, but contains same number of object casts as before, while still allowing client code to use templates for anything.

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/6665
