### ISSUE TITLE
Expose application Delegate on MacOsx so we can subscribe to various OSX Events

### ISSUE THREAD

**Issue by josegomez** [AvaloniaUI/Avalonia#3822]
Avalonia Implements their own Application Delegate on OSX
See: https://github.com/AvaloniaUI/Avalonia/blob/5a2ef35dacbce0438b66d9f012e5f629045beb3d/native/Avalonia.Native/src/OSX/app.mm

The issue here is that this delegate isn't available in managed code, nor are any of the events.

For example when an application is launched from a URL scheme xxx://www.url.com

OSX raises handleGetURLEvent:withReplyEvent: which is where the URL can be captured and processed. There are several other events as they relate to file associations and such that get delivered via event.

Currently there is no way around this except bringing in monomac and re-implementing your own  ApplicationDelegate but this causes you to lose the application Delegate created by avalonia so you end up having to re implement everything exactly as Avalonia does above in managed code.

It would be great if the events could be published in managed code (to avoid needing to bring in MonoMac)

See curent work around implementation: 

https://github.com/sqrldev/SQRLDotNetClient/blob/da7a7160b5e80b5d881a22f6c444178644c7e593/SQRLDotNetClientUI/Platform/OSX/AppDelegate.cs#L134

This works fine but if Avalonia changes their delegate obviously those changes would'nt propagate here so we'd have to keep up with it constantly.

**Comment by kekekeks** [comment]
MonoMac should be capable of extracting the existing instance, so it's likely that's something is wrong with your initialization order.

**Comment by kekekeks** [comment]
Delegate property is extracting the delegate directly from ObjC.

```cs
    public virtual NSObject WeakDelegate
    {
      [Export("delegate", ArgumentSemantic.Assign)] get
      {
        NSApplication.EnsureUIThread();
        NSObject nsObject = !this.IsDirectBinding 
            ? MonoMac.ObjCRuntime.Runtime.GetNSObject(Messaging.IntPtr_objc_msgSendSuper(
                this.SuperHandle, NSApplication.selDelegateHandle)) 
            : MonoMac.ObjCRuntime.Runtime.GetNSObject(Messaging.IntPtr_objc_msgSend(
                this.Handle, NSApplication.selDelegateHandle));
        this.__mt_WeakDelegate_var = (object) nsObject;
        return nsObject;
      }
    }

    public NSApplicationDelegate Delegate
    {
      get
      {
        return WeakDelegate as NSApplicationDelegate;
      }
    }
```

**Comment by kekekeks** [comment]
Actually, delegate might get destroyed since NSApplication only keeps a weak reference. We should probably manually retain our application delegate instance.

**Comment by josegomez** [comment]
> Actually, delegate might get destroyed since NSApplication only keeps a weak reference. We should probably manually retain our application delegate instance.

That would be cool, but wouldn't that mean you need to bring along MonoMac (deprecated?) Can you use Xamarin Mac? I tried before but Xamarin mac won't work / compile on anything but a Mac (though I didn't try very hard)

**Comment by kekekeks** [comment]
We are using ObjC++ with a COM bridge for Cocoa interop, so our code doesn't depend on managed Cocoa bindings.

**Comment by josegomez** [comment]
ah nice!

**Comment by sa-barnaby** [comment]
Is this now possible with Avalonia?

It's possible to register the application as handling a URL scheme as described in https://docs.avaloniaui.net/docs/distribution-publishing/macos#making-the-application-bundle

However I can't see a way of actually listening to the callback in the Mac builds?

**Comment by BaseHead** [comment]
I'm curious is if this is possible on macOS also yet.  My coder said it wasn't 2-3 months ago.  Any progress on it yet?
Thx!
Steve

**Comment by maxkatz6** [comment]
Not planned. You can access most of MacOS APIs directly using .NET 8 MacOS bindings or MonoMac (not recommended) or PInvokes.

URL scheme handling is possible with Avalonia too: https://docs.avaloniaui.net/docs/concepts/services/activatable-lifetime
