### ISSUE TITLE
Changing TextBlock.Text to multiline String causes rendering issue

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#3825]
I've got a TextBlock with text like this: 
```xaml
<TextBlock Text="Original" VerticalAlignment="Center" x:Name="Thing" />
```

From code-behind, if I set the Text to a multi-line string like this:
```cs
Thing.Text = "This is a long line 1\nThis is a long line 2\nThis is a long line 3";
```

The TextBlock will only render the first line fully, while the second line will only visually contain the region that was previously occupied by the original text. Screenshot examples:
![image](https://user-images.githubusercontent.com/13300194/80285247-db3c7900-8723-11ea-910b-99d8e562e7c4.png)
![image](https://user-images.githubusercontent.com/13300194/80285250-e0012d00-8723-11ea-9b1d-512cc1ac926c.png)

Opening DevTools and inspecting the TextBlock causes it to redraw properly, showing all three lines.

cibuild0006806

**Comment by mat1jaczyyy** [comment]
I can't access cibuilds prior to 6492, but I have 6058 cached locally. The example provided works properly on 6058, but not 6492, so it was broken sometime in between those builds.

**Comment by Gillibald** [comment]
Can't repro this on current master
![MultiLine](https://user-images.githubusercontent.com/5928797/80915325-ee69cd00-8d51-11ea-9e4b-a2e4d2c73e36.png)

**Comment by mat1jaczyyy** [comment]
@Gillibald for now you can repro from [mat1jaczyyy/apollo-studio](https://github.com/mat1jaczyyy/apollo-studio) master, I had just reverted the cibuild I'm using to 6058 (where bug doesn't repro) but you should be able to get it just by upgrading Avalonia version. Steps:

1. On the main SplashWindow, open the PreferencesWindow by clicking the gear icon in the top left
2. In the Theme selection segment, select either Dark or Light (change the option) and multiline text saying "You must restart to apply changes" will appear next to it.

I know this kind of repro might be too much to ask for, so I'll try to make a minimal repro later today...

**Comment by Gillibald** [comment]
Latest build has the number 7054

**Comment by mat1jaczyyy** [comment]
@Gillibald I isolated the problem and turns out it's quite a specific setup. Hopefully this should get you a minimal repro of this
[Repro3825.zip](https://github.com/AvaloniaUI/Avalonia/files/4572574/Repro3825.zip)

**Comment by Gillibald** [comment]
Thanks. Will have a look.

**Comment by Gillibald** [comment]
This is a bug with the Grid I think and not related to the TextBlock.

This works:
```
<Grid ColumnDefinitions="Auto,*" RowDefinitions="Auto, Auto">
      <StackPanel Grid.Column="0">
        <TextBlock Text="Needed short" />
        <RadioButton Click="Trigger">Repro Bug</RadioButton>
      </StackPanel>

      <TextBlock Grid.Column="1" x:Name="Problem" Text="Original" />

      <TextBlock Grid.Row="1" Text="This text also needs to be long" />
    </Grid>
```

**Comment by mat1jaczyyy** [comment]
Resizing the window immediately properly redraws and bug is gone

**Comment by Deadpikle** [comment]
I am also experiencing something very similar, but in a `UserControl` that is presented via `ContentControl`. The `ContentControl` is in a `Grid`, but my actual `UserControl` has no `Grid` inside of it. Resizing the window causes the `TextBlock` to redraw properly, so I'm guessing that the above repro demonstrates the same bug I am getting.

I am working around this right now by:

```csharp
MyProp = "";
MyProp = "real value";
```

**Comment by Gillibald** [comment]
When you add a TextBlock that is bound to Bounds.Height of the affected TextBlock does the height change?

**Comment by Deadpikle** [comment]
No, the height does not change. I can see that visually, too -- I have a really long string (directory) and just the last folder part is changing.

I did a test, and if the height changes, the `TextBlock` updates properly. I tested this by doing:

```csharp
MyProp += "a";
```

then spam-clicking my button. As soon as the height changed, the UI updated.

**Comment by Gillibald** [comment]
I have an idea what is happening. Will rework the invalidation a bit and hopefully it fixes your issue.

**Comment by VisualMelon** [comment]
I've been beating my head against this this afternoon with version `0.10.0-preview2`. I only have problem when the background is `null`, so I can address my concern by making the background explicitly transparent. Looking through the sources, I can't work out what is going on, but I'll have another look tomorrow.

**Comment by VisualMelon** [comment]
As best I can tell, the issue is with the constructor of `GlythRunNode`: it doesn't offset the draw operation `Bounds` based on the position. You can get a similar effect if you modify `TextBlock` to render the text offset somewhat.

I think this can be solved by just changing the constructor to take into account the baseline origin and ascent, i.e. change 

https://github.com/AvaloniaUI/Avalonia/blob/0861f663fc87f2d91dbfd11bbea55dafc16cfa7a/src/Avalonia.Visuals/Rendering/SceneGraph/GlyphRunNode.cs#L28

to

            : base(new Rect(baselineOrigin.X + glyphRun.Bounds.X, baselineOrigin.Y + glyphRun.GlyphTypeface.Ascent * glyphRun.Scale + glyphRun.Bounds.Y, glyphRun.Bounds.Width, glyphRun.Bounds.Height), transform)


Adding a non-null background resolves the issue because the dirty rect includes its (correct) bounds.

I'd be happy to put a PR together if it helps.

**Comment by Gillibald** [comment]
I don't see how this can be true. The GlyphRun's bounds don't originate at the baseline

**Comment by VisualMelon** [comment]
@Gillibald `GlyphRun.Bounds` always starts at `0, 0`, i.e. they are independent of the baseline origin. The origin then depends on the requested position and the ascent/descent etc.

This resolved the issue in my testing, which I traced back to the clipping rectangle being too small, and all `GlythRunNode` having the same `Bounds` origin, independent of which 'line' of text it was meant to be. The effect is that every line was occupying the same vertical space as far as the dirty rectangle is concerned.

**Comment by Gillibald** [comment]
The correct fix is to create the bounds with `new Rect(0, -ascent, width, height);`

**Comment by VisualMelon** [comment]
I agree that would make sense for handling the ascent.

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Media/GlyphRun.cs#L558

**Comment by Gillibald** [comment]
Can be changed to
```
return new Rect(0, GlyphTypeface.Ascent * Scale, width, height);
```

**Comment by Gillibald** [comment]
If you want you can test that fix and submit a PR.

**Comment by Gillibald** [comment]
Just thinking about my proposed fix and it turns out I was wrong. GlyphRun's bounds should not care about the baseline origin. You were on the right track.

I think this might work:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Rendering/SceneGraph/GlyphRunNode.cs#L28
`            : base(glyphRun.Bounds.Translate(new Vector(baselineOrigin.X, -baselineOrigin.Y)), transform)`

**Comment by VisualMelon** [comment]
@Gillibald I think you are right that assent should be handled by `GlyphRun`, but it needs to be done in `CalculateBounds` (see #4517)
