### ISSUE TITLE
NumericUpDown in ContextMenu causes AvaloniaInternalException

### ISSUE THREAD

**Issue by arklumpus** [AvaloniaUI/Avalonia#3830]
Hello,

In Avalonia 0.9.9, a ContextMenu containing a NumericUpDown will throw an AvaloniaInternalException 'Was attached to logical tree but cannot find root.' when the ContextMenu is closed. This used to work fine up to 0.9.7 (included).

To reproduce, create an empty Avalonia project, upgrade Avalonia to 0.9.9 and replace the constructor in `MainWindow.xaml.cs`:
```csharp
public MainWindow()
{
    InitializeComponent();
#if DEBUG
    this.AttachDevTools();
#endif

    this.PointerPressed += (s, e) =>
    {
        ContextMenu menu = new ContextMenu()
        {
            Items = new List<MenuItem>()
            {
                new MenuItem()
                {
                    Header = new NumericUpDown()
                }
            }
        };
        menu.Open(this);
    };
}
```
Then, click on the empty window to open the context menu. When you click again on the window closing the context menu, the exception will be thrown.

**Comment by maxkatz6** [comment]
I believe it was fixed already.
Also, it's recommended to use ContextFlyout, if you want to show complex content in the context.
