### ISSUE TITLE
[macOS] Window with HasSystemDecorations="False" can't be maximized

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#3835]
Maximizing a window with `WindowState = WindowState.Maximized;` fails silently on macOS if `HasSystemDecorations` is set to `False`. If it's set to `True`, maximizing from code works. 

Although, the window does move around when attempted, but doesn't resize, so maybe related to #3834?

macOS 10.13 / cibuild0006821

**Comment by mat1jaczyyy** [comment]
I can't access cibuilds prior to 6492, but I have 6058 cached locally. Maximizing works on 6058, but not 6492, so it was broken sometime in between those builds.

**Comment by danwalmsley** [comment]
fixed in https://github.com/AvaloniaUI/Avalonia/pull/3849
