### ISSUE TITLE
Dialog windows are measured with incorrect initial size

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#3843]
After updating to latest Avalonia I've noticed that my app has dialog windows with content that is cut off. I can also repro this in the control catalog by fixing window size to 800x400 and putting such content in:

```
<Grid ColumnDefinitions="*,Auto,*">
          <Rectangle Grid.Column="0" Fill="Red" Height="200" />
          <GridSplitter Grid.Column="1" />
          <ScrollViewer Grid.Column="2" HorizontalScrollBarVisibility="Disabled">
            <Rectangle Width="800" Height="200" Fill="Green" />
          </ScrollViewer>
 </Grid>
```

![image](https://user-images.githubusercontent.com/2588062/80608680-69bc3d80-8a37-11ea-920e-849c38ecf91d.png)

After resizing the window elements will be measured correctly.

**Comment by grokys** [comment]
Seems #3787 fixed this for windows shown normally but not for windows shown as dialogs.
