### ISSUE TITLE
DarkGray is lighter dan Gray in KnownColors.cs

### ISSUE THREAD

**Issue by JamRemco** [AvaloniaUI/Avalonia#3848]
in [Known colors](https://github.com/AvaloniaUI/Avalonia/blob/d6578eba5089e267d9701a6b7380a5830fbe2465/src/Avalonia.Visuals/Media/KnownColors.cs) 
 
DarkGray = 0xffa9a9a9       <- Should be ff8b8b8b
Gray = 0xff808080               <- This is right

mmm strange after googling it. it apears wpf got the same "Error"

Regards

**Comment by kekekeks** [comment]
This is by design.
See https://stackoverflow.com/questions/3811973/why-is-darkgray-lighter-than-gray
