### ISSUE TITLE
Using Source Generators to generate Controls (Code behind)

### ISSUE THREAD

**Issue by Azyyyyyy** [AvaloniaUI/Avalonia#3851]
Right now (as far I'm aware) AvaloniaUI doesn't have a way to add any controls to the code behind of an application. This requires people that are using this having to add each control that they need to control in code themselves and when you are making a complex UI, this adds up quickly.

Microsoft has introduced [C# Source Generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/), this allows extra code to be added before an application gets built, which for this library could allow for controls in code to be added without any input.

Any opinions on this?

**Comment by grokys** [comment]
We've already been talking about this, source generators would be perfect for this functionality!

**Comment by hez2010** [comment]
Also for compiled bindings please (just like what `x:Bind` in UWP did)

**Comment by kekekeks** [comment]
Compiled bindings will be implemented using regular MSIL emission engine. We aren't planning to drop F# support.

**Comment by FoggyFinder** [comment]
> Compiled bindings will be implemented using regular MSIL emission engine. We aren't planning to drop F# support.

Big thanks for this.

There are developers who write Avalonia-app with F#. Don't forget about us :-)

**Comment by dfkeenan** [comment]
I was going to have a crack at this. But then I found there already is one. 
https://github.com/AvaloniaUI/Avalonia.NameGenerator
https://www.nuget.org/packages/XamlNameReferenceGenerator

**Comment by MrJul** [comment]
The name source generators have been bundled with Avalonia since v11.0.
