### ISSUE TITLE
[Linux] Hard dependency on dejavu font

### ISSUE THREAD

**Issue by InfinityGhost** [AvaloniaUI/Avalonia#3859]
# The Issue
Any application that uses Avalonia will completely lock up before `Main()` ever executes if the dejavu font is unavailable. Installing dejavu's dependencies doesn't fix this either, even if a different font is used throughout the entire program's styles and resources.

This seems like a rather odd dependency, especially since its not listed in the runtime requirements doesn't state this dependency. It's especially annoying on bare-bones distributions like Arch, which is where I first discovered this unlisted dependency.

# Reproduction
1. Remove dejavu font
2. Launch app, it will hang without any errors nor any display of not responding 
3. Force quit app
4. Reinstall dejavu font
5. Launching app will progress as normally

**Comment by Gillibald** [comment]
There is no dependency on any font. I don't get how you come to that conclusion.

**Comment by kekekeks** [comment]
Looks like https://github.com/mono/SkiaSharp/issues/1181

Please, check if `SKTypeface.FromFamilyName("Sans")` and `SKTypeface.Default.FamilyName` returns non-null values

It seems that something is wrong somewhere between Skia and libfontconfig

**Comment by kekekeks** [comment]
@Gillibald There also were reports about https://github.com/mono/SkiaSharp/issues/1181 getting fixed by `pacman -S ttf-ms-fonts`. So I suspect that Skia needs something that is provided by both MS core fonts and Dejavu

**Comment by Gillibald** [comment]
Will have a look. Looking forward to a custom font manager with SkiaSharp V2

**Comment by Gillibald** [comment]
Could not find anything hard coded to that font. You might want to try to set the FontFamily explicitly on your window to a font that exists on your system. You have to get the name right because the font manager isn't working properly. Usually aliases are configured but that might be broken for some reason.

**Comment by kekekeks** [comment]
>Looking forward to a custom font manager with SkiaSharp V2

We'll still need to P/Invoke libfontconfig though.

**Comment by Gillibald** [comment]
Are you sure that `ttf-ms-fonts` isn't adding something to fontconfig so the font manager now matches properly?

**Comment by kekekeks** [comment]
It might be adding something to FC configuration
