### ISSUE TITLE
Problem with Bottom-up bitmaps in Skia

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#3865]
Hey,

When using Avalonia.Media.Imaging.Bitmap constructor with scan0 and negative stride (for bottom-up bitmaps), I'm getting ArgumentException for null _image on ImmutableBitmap line 55 since SKImage.FromPixelCopy returns null image.

Any way to fix this?
Thanks

**Comment by kekekeks** [comment]
Does SKImage supports negative stride internally? If it doesn't, please, open an issue in https://github.com/mono/SkiaSharp/

We could transcode the negative stride internally (with a performance impact), but I'm not sure that it's the right way to deal with this problem.
