### ISSUE TITLE
Is there a ribbon control?

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#3873]
Ribbon is used in many places. Can it be developed in time

**Comment by FoggyFinder** [comment]
https://github.com/amazerol/AvaloniaRibbon

**Comment by JamRemco** [comment]
You could use a TabControl With UI elements
or use https://github.com/amazerol/AvaloniaRibbon

Remco

**Comment by jinyuttt** [comment]
thanks
