### ISSUE TITLE
Map display

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#3874]
Does Avalonia have a map presentation solution or GIS component?

**Comment by kekekeks** [comment]
There was a [port](https://github.com/Mapsui/Mapsui/issues/749) attempt for Mapsui library.
![image](https://user-images.githubusercontent.com/1830368/72172043-dfdf5a80-33dc-11ea-9972-288c824a92bd.png)

Not sure about the status, better ask @ahopper

**Comment by ahopper** [comment]
@jinyuttt my port works fine as long as you are using Skia in Avalonia ( the default). I paused before creating a PR for it as I was intending to make the touch side work better but lack of time and my Surface failing ( my only touch device) delayed me.

**Comment by jinyuttt** [comment]
@ahopper 
Avalonia version cannot run on Linux.
![image](https://user-images.githubusercontent.com/13539621/80920601-75936100-8da3-11ea-945a-f40c45598216.png)

**Comment by ahopper** [comment]
@jinyuttt I'll have a look at it this week. I wonder if it is a skia version problem.

**Comment by jinyuttt** [comment]
@ahopper  thanks,
I hope I can get your help. We are planning to develop the project with Avalonia and run it on Linux and windows at the same time.

By the way, is 3D supported? We want to achieve 2D, 2D display.

**Comment by ahopper** [comment]
@jinyuttt this does appear to be a skia version issue see
https://github.com/Mapsui/Mapsui/issues/904#issuecomment-623316222 you can get it going just by copying a file over.

I haven't explored Mapsui enough to know if it has any 3d options (my use is very simple).
There is https://github.com/AvaloniaUI/Avalonia/pull/3386

**Comment by danwalmsley** [comment]
@jinyuttt i think you just need to add the package Avalonia.Skia.Linux.Natives

**Comment by jinyuttt** [comment]
@ahopper Didn't you push it to mapui or update it?

**Comment by ahopper** [comment]
@jinyuttt I updated my fork a while ago but was waiting for 0.10 to be released  before submitting a pr to mapsui.

**Comment by geocoderEU** [comment]
@ahopper Any news on this? Is there anything i could help you with?
