### ISSUE TITLE
Develop controls like devexpress

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#3880]
Does Avalonia plan to borrow some controls from devexpress? Some of devexpress's controls are well implemented. I mean to achieve similar control display effect. For example: datagridcontrol, chartControl

**Comment by jmacato** [comment]
@jinyuttt It depends on DevExpress if they want to do a port to Avalonia since it's their IP.

**Comment by MikeCodesDotNET** [comment]
We now have [Avalonia XPF](https://avaloniaui.net/xpf) for companies looking to reuse their existing 3rd party UI controls while also going cross-platform.
