### ISSUE TITLE
NRE in PropertyAccessorNode StopListeningCore

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#3884]
I just got a n NRE in PropertyAccessorNode StopListeningCore on Avalonia 0.9.9 running on Linux Raspbian.

[crash1.txt](https://github.com/AvaloniaUI/Avalonia/files/4580370/crash1.txt)

it's happening because stoplistening is called before startlistening is finished

**Comment by MrJul** [comment]
Not relevant anymore, this code path doesn't exist anymore in master, when the bindings have been refactored.
