### ISSUE TITLE
Style system suggestions

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#3888]
I've come to prefer Avalonia's styling system to WPF, but I've had a couple thoughts on how to decrease the verbosity of writing Styles for controls:

-As in #3886, when writing a control style/template, if you provide a non-binded local value to a template item, it can't be overridden in related styles (eg ":pointerover" ":pressed", etc...). Right now the only way to overcome this is to either add a binding or write a separate selector targeting that control after the base template style. It's been a while since I last used WPF but I'm pretty sure that Triggers can override local values within a template in WPF. 

-Would it be possible to consolidate the Styles by Type rather than by selector, implementing something similar to WPF's Triggers or the WPF/UWP VisualStateManager? I mention this because currently if you have multiple template items that need to change state given a certain condition (pointerover, etc.), a separate Selector has to be written targeting just that item, which while not hard, can make templating controls long.
I know an exact replica would not work easily with the current system but my thought was, what if a `Style` only matched the type, then each Style had a collection of States. Then add a `Target` property to `Setter` to direct where to apply it. Something like below is what I've thought of:
````
<Style Selector="Button">
      <Setter Property="Template">
        <Border Background="{TemplateBinding Background}"
                BorderBrush="{TemplateBinding BorderBrush}"
                BorderThickness="{TemplateBinding BorderThickness}">
          <TextBlock Text="{TemplateBinding Content}" Margin="{TemplateBinding Padding}"
                     Foreground="{TemplateBinding Foreground}" />
        </Border>
      </Setter>
      <Style.States>
        <State Selector=":pointerover">
          <Setter Target="Border" Property="Background" Value="{DynamicResource ButtonBackgroundPointerOver}" />
          <Setter Target="TextBlock" Property="Foreground" Value="{DynamicResource ButtonForegroundPointerOver}" />
        </State>
      </Style.States>
    </Style>
````

**Comment by kekekeks** [comment]
>Would it be possible to consolidate the Styles by Type rather than by selector
> each Style had a collection of States

See
https://github.com/AvaloniaUI/Avalonia/issues/3593
https://github.com/AvaloniaUI/Avalonia/issues/2769

**Comment by amwx** [comment]
Sorry must've missed those. Glad to know this was already on the radar

**Comment by JamRemco** [comment]
How about this ?  ;) haha

``` Xaml

<Style Selector From ToggleButton.Switch>
      <Setter Property="Template">
		......The usual
      </Setter> 
	 	<State Where State=checked 
			Select /template/ Ellipse#PART_Circle as C, 
				/template/ Border#Part_Border as B>
			Set
				<C:Canvas.Left=25 Fill="White"/>
				<B:Borderbrush="Blue"/>
		</State>

		<State Where State=Unchecked 
			Select /template/ Ellipse#PART_Circle as C, 
				/template/ Border#Part_Border as B>
			Set
				<C:Canvas.Left=6 Fill="Bleu"/>
				<B:Borderbrush="White"/>
		</State>
	
  </Style Selector>


```

Remco

**Comment by maxkatz6** [comment]
I think it can be closed now.
