### ISSUE TITLE
Small bug of element hovering in a list on windows

### ISSUE THREAD

**Issue by SeleDreams** [AvaloniaUI/Avalonia#3891]
I found this bug while trying to see how the window reacted to getting resized.
Basically when we resize a window containing a list, it seems like the list will think that the cursor is hovering over some elements when it isn't the case.

It isn't that big of a deal and doesn't prevent to work at all, but it's something that I think can be considered a bug.

I am using Windows 10 64 bits 1909 and my current project uses .NET Core 3.0

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16335601/81246582-46d1f080-9018-11ea-82c4-c3127af08a6c.gif)

**Comment by ahopper** [comment]
I suspect this is related to https://github.com/AvaloniaUI/Avalonia/pull/2988 where we don't properly null the mouse position when the mouse leaves the client area.  Well done for finding a case to make it fail :)
