### ISSUE TITLE
GridSplitter always splits vertically 

### ISSUE THREAD

**Issue by SeleDreams** [AvaloniaUI/Avalonia#3893]
![image](https://user-images.githubusercontent.com/16335601/81258553-3761a000-9036-11ea-9459-85fb70de2876.png)

I am having this issue where GridSplitter only allows to split vertically and not horizontally

I find it weird because I looked at the source and from what I can see it is supposed to go horizontally if the horizontal alignment is not set to stretch...

**Comment by ahopper** [comment]
I think this is because you are setting Grid.Column instead of Row on the splitter.

**Comment by SeleDreams** [comment]
> 
> 
> I think this is because you are setting Grid.Column instead of Row on the splitter.


![image](https://user-images.githubusercontent.com/16335601/81259255-de930700-9037-11ea-9b04-3de409bf479a.png)
even when I do it has the same effect

**Comment by ahopper** [comment]
Or perhaps I misunderstand, do you want the splitter to be vertical line?

**Comment by SeleDreams** [comment]
Yes, when I said always splits vertically it was more to say that it was splitting to resize vertically when I want it to resize horizontally

**Comment by ahopper** [comment]
I just tried
```
<Grid ColumnDefinitions="*,4,*">
    <TextBlock Text ="aaaaaaaaaaaaaa" Grid.Column="0"/>
    <GridSplitter Grid.Column="1"/>
    <TextBlock Text ="bbbbbbbbbb" Grid.Column="2"/>

  </Grid>
```
and it appears to work

**Comment by SeleDreams** [comment]
Oh so I had to set a third column
I didn't know, thanks for the help

I think the main reason it's difficult is because the documentation has a big lack of examples on how to use controls.
As AvaloniaUI is my first GUI api the lack of infos is a bit confusing

**Comment by ahopper** [comment]
Yep, the control catalog sample is a good place to look (but not in this case) and a search on the repro will normally find an example. https://github.com/AvaloniaCommunity/awesome-avalonia also lists a lot of projects that can be used as examples.

**Comment by Gillibald** [comment]
Avalonia's Grid is exactly the same as WPF's Grid. So if you google `WPF Grid` results should be applicable for Avalonia.
