### ISSUE TITLE
ArgumentException when opening dialog window

### ISSUE THREAD

**Issue by SeleDreams** [AvaloniaUI/Avalonia#3894]
![image](https://user-images.githubusercontent.com/16335601/81270954-bf9e7000-904b-11ea-9819-490a40309bcf.png)

I really don't know what's wrong, I'm just trying to open a file dialog in order to open a file and it doesn't work.

**Comment by SeleDreams** [comment]
fixed, it seems like not specifying a name to the filter makes the whole thing crash, which I did not expect

**Comment by grokys** [comment]
Reopening this as we should probably default to "*.*" if there's no filter given?

**Comment by SeleDreams** [comment]
in the current case I gave a filter to the open file dialog, however I didn't give a name to the filter
