### ISSUE TITLE
Building Avalonia on a Mac fails

### ISSUE THREAD

**Issue by skyflyer** [AvaloniaUI/Avalonia#3899]
I'm trying to build Avalonia (`master`) on Mac OS Catalina following the [instructions](https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md#linuxmacos) and the build fails when trying to build `ControlCatalog.NetCore` project:

```
/Users/johndoe/.nuget/packages/sharpgentools.sdk/1.2.1/build/SharpGenTools.Sdk.targets(173,5): Preprocess error CX0001: /Volumes/Drugi/Users/johndoe/work/dev/Avalonia/src/Avalonia.Native/obj/Debug/netstandard2.0/SharpGen/AvaloniaNative.h:2:10: fatal error: cannot open file '/Volumes/Drugi/Users/johndoe/work/dev/Avalonia/src/Avalonia.Native/obj/Debug/netstandard2.0/SharpGen/avalonia-native.h': No such file or directory [/Volumes/Drugi/Users/johndoe/work/dev/Avalonia/src/Avalonia.Native/Avalonia.Native.csproj]
/Users/johndoe/.nuget/packages/sharpgentools.sdk/1.2.1/build/SharpGenTools.Sdk.targets(173,5): Preprocess error CX0003: Failed to run CastXML. Check previous errors. [/Volumes/Drugi/Users/johndoe/work/dev/Avalonia/src/Avalonia.Native/Avalonia.Native.csproj]
```

Manually copying file only goes so far, and then fails with file not found `stddef.h`.

**Comment by Deadpikle** [comment]
You probably need to [install CastXML](https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md#install-castxml).

**Comment by skyflyer** [comment]
@Deadpikle, I installed it with `brew install castxml`:

```
Warning: castxml 0.3.3 is already installed and up-to-date
To reinstall 0.3.3, run `brew reinstall castxml`
```

I tried reinstalling:
```
❯ brew reinstall castxml
==> Reinstalling castxml
==> Downloading https://homebrew.bintray.com/bottles/castxml-0.3.3.catalina.bottle.tar.gz
Already downloaded: /Users/miha/Library/Caches/Homebrew/downloads/30c3398140f4077c2b0202bf607ce9a61d20bcd31e3117a5b5ec74ce5f098b8f--castxml-0.3.3.catalina.bottle.tar.gz
==> Pouring castxml-0.3.3.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/castxml/0.3.3: 173 files, 27.3MB
```

Then issued `dotnet clean` and `dotnet build` and got the error posted above.

FWIW, `castxml --help` works and produces the help output as expected.

**Comment by kekekeks** [comment]
You need the previous version - https://github.com/AvaloniaUI/Avalonia/blob/e980f942e4373bf3e0b3fc638a76fcae75409850/azure-pipelines.yml#L71

**Comment by skyflyer** [comment]
@kekekeks, this works, thanks.

**Comment by skyflyer** [comment]
Just for future reference: the command to build the xcode project is:

`xcodebuild -derivedDataPath ./ -workspace native/Avalonia.Native/src/OSX/Avalonia.Native.OSX.xcodeproj/project.xcworkspace -scheme 'Avalonia.Native.OSX' -configuration Release`

**Comment by skyflyer** [comment]
This was solved.

1. Need to use a specific version of CastXML (check Azure CI config for specific version)
1. Need to use a specific version of SDK
