### ISSUE TITLE
DataTemplate in a grid ?

### ISSUE THREAD

**Issue by SeleDreams** [AvaloniaUI/Avalonia#3903]
![image](https://user-images.githubusercontent.com/16335601/81368392-f332d600-90ef-11ea-9932-bd47755b4e1b.png)
I am having some issues with what I'm trying to do, basically I want to display a list of properties in a grid with the property at the left, the one at the right and a gridsplitter in the middle moving all rows at once, however, if I place my elements like this, I would get a compilation error as DataTemplate expects the elements to be contained in something, the main issue is that if I place them in an other grid it would be bound by the rows of this grid and if I place them in something else like a StackPanel or something like this it would mess with their layout, is there any way to be able to do what I want to do ?

I've been able to get it to compile by placing the grid in the datatemplate but the result is one grid per item, this isn't the same thing, and moving the gridsplitter doesn't resize all the elements

**Comment by SeleDreams** [comment]
I'm basically trying to get a result similar to a WinForms PropertyGrid generated from a list of items

**Comment by Gillibald** [comment]
This should help: https://wpf.2000things.com/tag/sharedsizegroup/

**Comment by SeleDreams** [comment]
I ended up using DataGrid as it fits more what I was targetting, there's a weird issue though where the first element of the datagrid always stays blue, even when I select something else
![image](https://user-images.githubusercontent.com/16335601/81382731-25076500-910f-11ea-9e9c-c25ca3b092b6.png)

**Comment by JamRemco** [comment]
I think you mean the alternate coloring of the grid
add more rows to your grid and you'l see what i mean.

Like this
![image](https://user-images.githubusercontent.com/58340108/81395623-4292f980-9124-11ea-994c-d21817ddc64f.png)

Regards,

Remco

**Comment by SeleDreams** [comment]
Oh I see, thanks, it was a bit confusing

honestly i'd be ready to pay for a udemy course or something like this simply to have a good introduction to most of at least the basics of avalonia as my main issue all along was that everything assumed we were already a WPF dev etc and didn't take that much time to explain things on the documentation, the tutorial there is only covers the really basic to display a list and add some elements to it but that's all, it doesn't really cover most controls, the different layouts etc

**Comment by SeleDreams** [comment]
I also tried watching some other projects but most projects are pretty complex, I tried looking at AvalonStudio most of the files are kind of paml something like this, and the few xaml files are almost empty for instance

**Comment by JamRemco** [comment]
@SeleDreams  

agreed, the Documentation is a bit lacking. 
However there are some ok starting examles/blogs out there.
Do a search on google...... This dude [https://www.nequalsonelifestyle.com/2019/06/13/avalonia-datagrid-getting-started/](url) got a few good starting examples

I am also new to VMMV, C# and avelonia, -so I feel your pain- it is a bit of a struggle.

I am planning on making tutorial and examples myself when i figured it out.

Have a good journy,

Remco
