### ISSUE TITLE
AutoCompleteBox validation not work

### ISSUE THREAD

**Issue by usUyGBx** [AvaloniaUI/Avalonia#3905]
I think validation problems comes from AutoCompleteBox TextTproperty defined as non-validated.
When I copypaste bellow code from TextBox it helps.

    protected override void UpdateDataValidation<T>(AvaloniaProperty<T> property, BindingValue<T> value)
    {
        if (property == TextProperty)
        {
            DataValidationErrors.SetError(this, value.Error);
        }
    }

    public static readonly DirectProperty<AutoCompleteBox, string> TextProperty =
        TextBlock.TextProperty.AddOwnerWithDataValidation<AutoCompleteBox>(
            o => o.Text,
            (o, v) => o.Text = v,
            defaultBindingMode: BindingMode.TwoWay,
            enableDataValidation: true);

**Comment by rstm-sf** [comment]
Fixed by #4054
