### ISSUE TITLE
Support generic types in DataTemplate.DataType

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#391]
E.g.:

```
<DataTemplate DataType="core:Library{core:ShapeStyle}">
```

**Comment by grokys** [comment]
Looking through the System.Xaml code, it's suggested that you should be able to specify type arguments in parenthesis:

https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/GenericTypeNameParser.cs#L129

Portable.Xaml doesn't seem to support this yet though.

**Comment by pr8x** [comment]
Hey, any plans on supporting this in the near future?

**Comment by grokys** [comment]
Now we have the XAML compiler this might be easier. I'll add it to my list.

**Comment by na2axl** [comment]
Hi @grokys, is there a workaround for that ? I'm facing an issue where this feature is necessary...

**Comment by grokys** [comment]
There's no workaround for XAML currently, XAML in general doesn't support generic types well, so I'm not entirely sure how to add this.

However, you should be able to add `DataTemplate`s with generic types from code, if that would help?

**Comment by na2axl** [comment]
Thank you for your answer @grokys, I've created my `DataTemplate` from code and it works. But it's always strange to me to create a custom `DataTemplate` type for all generic types which need to be templated in my app... Anyway, thanks and good luck :smile:

**Comment by RomanSoloweow** [comment]
Any information on this issue?

**Comment by RomanSoloweow** [comment]
A workaround was found, it will be useful to someone

1. Let's implement our DataTemplate

```C#
    public class MyDataTemplate:IDataTemplate
    {
        public object Value { get; set; }
        public IControl Build(object data) => Build(data, null);
        
        [Content]
        [TemplateContent]
        public object Content { get; set; }
        public IControl Build(object data, IControl existing)
        {
            return existing ?? TemplateContent.Load(Content)?.Control;
        }

        public bool Match(object data)
        {
            if (Value is null)
                return true;
            
            var valueType = Value?.GetType();
            var dataType = data?.GetType();
            var result = valueType == dataType;
            return result;
        }
    }
```

2.  Use it in Xaml

```XAML
<ItemsControl.DataTemplates>
  <controls:MyDataTemplate>
    <controls:MyDataTemplate.Value>
        <base:Property x:TypeArguments="x:Boolean"></base:Property>
    </controls:MyDataTemplate.Value>
  
     ...Your template here...
  
  </controls:MyDataTemplate>
  <controls:MyDataTemplate>
    <controls:MyDataTemplate.Value>
        <base:Property x:TypeArguments="x:String"></base:Property>
    </controls:MyDataTemplate.Value>
  
    ...Your template here...
  
  </controls:MyDataTemplate>
</ItemsControl.DataTemplates>
```

**Comment by grokys** [comment]
Turns out we've actually supported this for a while. The syntax is a bit verbose but it's just using the XAML spec:

```
<DataTemplate>
  <DataTemplate.DataType>
    <x:Type TypeName="scg:List" x:TypeArguments="system:String"/>
  </DataTemplate.DataType>
</DataTemplate>
```

**Comment by kekekeks** [comment]
https://docs.microsoft.com/en-us/dotnet/desktop/xaml-services/xtypearguments-directive

**Comment by jpgarza93** [comment]
> x:Type

what is base: namespace?

**Comment by jpgarza93** [comment]
How can i accomplish something like this?

```    
<UserControl>
        <UserControl.DataTemplates>
                   <DataTemplate>
			<DataTemplate.DataType>
				<x:Type TypeName="sys:Boolean"/>
			</DataTemplate.DataType>

                         <CheckBox IsChecked="true" />
                    </DataTemplate>

	        <DataTemplate>
			<DataTemplate.DataType>
				<x:Type TypeName="sys:String"/>
			</DataTemplate.DataType>

			<TextBox />
		</DataTemplate>
												
	</UserControl.DataTemplates>

        <ContentControl Content="{Binding Type}" />
</UserControl>
```

**Comment by wieslawsoltes** [comment]
> How can i accomplish something like this?
> 
> ```
> <UserControl>
>         <UserControl.DataTemplates>
>                 <DataTemplate>
> 			<DataTemplate.DataType>
> 				<x:Type TypeName="sys:Boolean"/>
> 			</DataTemplate.DataType>
> 
>                         <CheckBox IsChecked="true" />
>                 </DataTemplate>
> 
> 	        <DataTemplate>
> 			<DataTemplate.DataType>
> 				<x:Type TypeName="sys:String"/>
> 			</DataTemplate.DataType>
> 
> 			<TextBox />
> 		</DataTemplate>
> 												
> 	</UserControl.DataTemplates>
> 
>         <ContentControl Content="{Binding Type}" />
> </UserControl>
> ```

Check entire project:
https://github.com/wieslawsoltes/TypeArgumentsDemo/blob/70ffc6f07977e70a7cfb5b69a01c5d5ea1b56273/TypeArgumentsDemo/TestView.axaml#L22

**Comment by jpgarza93** [comment]
> > How can i accomplish something like this?
> > ```
> > <UserControl>
> >         <UserControl.DataTemplates>
> >                 <DataTemplate>
> > 			<DataTemplate.DataType>
> > 				<x:Type TypeName="sys:Boolean"/>
> > 			</DataTemplate.DataType>
> > 
> >                         <CheckBox IsChecked="true" />
> >                 </DataTemplate>
> > 
> > 	        <DataTemplate>
> > 			<DataTemplate.DataType>
> > 				<x:Type TypeName="sys:String"/>
> > 			</DataTemplate.DataType>
> > 
> > 			<TextBox />
> > 		</DataTemplate>
> > 												
> > 	</UserControl.DataTemplates>
> > 
> >         <ContentControl Content="{Binding Type}" />
> > </UserControl>
> > ```
> 
> Check entire project: https://github.com/wieslawsoltes/TypeArgumentsDemo/blob/70ffc6f07977e70a7cfb5b69a01c5d5ea1b56273/TypeArgumentsDemo/TestView.axaml#L22

Sorry, even with this example I am not able to change my contentcontrol based on an Int32, Boolean, or string :(

Would you be able to provide more info? Thank you very much in advance

**Comment by timunie** [comment]
https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src%2FAvalonia.Samples%2FDataTemplates%2FBasicDataTemplateSample

**Comment by jpgarza93** [comment]
> https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src%2FAvalonia.Samples%2FDataTemplates%2FBasicDataTemplateSample

not straight forward. still haven't found a good tutorial on how to use generics to change datatemplates

**Comment by jpgarza93** [comment]
For anyone trying to use generics (String, Double, Int, etc), here is what I did to get it working:

``` c#
public class GenericsDataTemplate : IDataTemplate
{
    [DataType]
    public Type? DataType { get; set; }

    [Content]
    [TemplateContent]
    public object? Content { get; set; }

    public bool Match(object? data)
    {
        if (DataType == null)
            return true;

        if (data is Type type)
            return DataType == type;

        return false;
    }

    public Control? Build(object? data) => Build(data, null);

    public Control? Build(object? data, Control? existing)
    {
        return existing ?? TemplateContent.Load(Content)?.Result;
    }
}
```

then in xaml just do this
![image](https://github.com/AvaloniaUI/Avalonia/assets/79015116/b9122d64-43c6-44e6-ac1b-5ff326320d29)

**Comment by SuperJMN** [comment]
Unfortunately, this doesn't work for x:DataType

**Comment by maxkatz6** [comment]
@SuperJMN can you check this PR? https://github.com/AvaloniaUI/Avalonia/pull/18379
Something like below is expected to work (and fixed in the PR above)
```
x:DataType="{x:Type vm:GenericType, x:TypeArguments=x:String}"
```

**Comment by SuperJMN** [comment]
> [@SuperJMN](https://github.com/SuperJMN) can you check this PR? [#18379](https://github.com/AvaloniaUI/Avalonia/pull/18379) Something like below is expected to work (and fixed in the PR above)
> 
> ```
> x:DataType="{x:Type vm:GenericType, x:TypeArguments=x:String}"
> ```

Whoa! Incredible work, man! I didn't know it was possible to do it as XML attribute! So smooth. Thank you!
