### ISSUE TITLE
Custom data validation on TextBox

### ISSUE THREAD

**Issue by Loen10** [AvaloniaUI/Avalonia#3912]
I'm trying to implement a TextBox that requires you to enter a number, A; that is larger than some other number, B. I want to use the data validation symbol to display the custom error just like it does if I input text instead of a number. How could I do this?

**Comment by JamRemco** [comment]
I asume you got some kind of class/model

anotations  does mabe wat you want?
```C#
 [Range(1, 100, ErrorMessage = "Price must be between $1 and $100")]
    public decimal Price { get; set; }
```
The Reactive way
Advanced [https://reactiveui.net/docs/handbook/user-input-validation/](url)

Or validation on properties on the get;set

Regards, 

Remco

**Comment by derekantrican** [comment]
@JamRemco Not sure if this was intentional, but just wanted to let you know that both your links seem to go to https://github.com/AvaloniaUI/Avalonia/issues/url when clicked on and not what they actually say
