### ISSUE TITLE
Strange behavior in menu

### ISSUE THREAD

**Issue by fredericoregateiro** [AvaloniaUI/Avalonia#3920]
I'm trying to list a recent file list in a "File" Menu:
```xml
<MenuItem Header="Recentes" Items="{Binding RecentFiles}" SelectedItem="{Binding RecentFile}" Command="{Binding OpenRecentFileCommand}" />
```
In the view model:
```csharp
private IEnumerable<string> recentFiles;
public IEnumerable<string> RecentFiles
{
    get => recentFiles;
    set => this.RaiseAndSetIfChanged(ref recentFiles, value);
}

private string recentFile;
public string RecentFile
{
    get => recentFile;
    set => this.RaiseAndSetIfChanged(ref recentFile, value);
}

public ReactiveCommand<string, Unit> OpenRecentFileCommand { get; }
```

Now the strange is when i hover the mouse on one of the `RecentFiles` the command executes, without any mouse click.
How can i remove this behavior? I only want the command execute when the user click on the atual menu.

The project i'm working is open source [where](https://github.com/SolRIA/saft-pt)

**Comment by danwalmsley** [comment]
@fredericoregateiro I think binding SelectedItem may be causing this, try remove selecteditem, it shouldnt be needed I dont think.

**Comment by fredericoregateiro** [comment]
@danwalmsley is the `SelectedItem` is causing this, but should it invoke the command on mouse houver?
How can i get the item the user click? I've try the `CommandParameter` but with no luck.

**Comment by danwalmsley** [comment]
It should only work on click, can you post you command code from viewmodel?

**Comment by danwalmsley** [comment]
> It should only work on click, can you post you command code from viewmodel?

If you bind only to command, your command must be in the item itself

**Comment by danwalmsley** [comment]
> > It should only work on click, can you post you command code from viewmodel?
> 
> If you bind only to command, your command must be in the item itself

So you need a RecenfFileViewModel with an opencommand on it, list of string won’t work

**Comment by fredericoregateiro** [comment]
I'm trying to implement your sugestion:
```csharp
public class RecentFileViewModel : ReactiveObject
    {
        public RecentFileViewModel()
        {
            OpenFileCommand = ReactiveCommand.CreateFromTask(OnOpenFile);
        }

        private string filename;
        public string FileName { get => filename; set => this.RaiseAndSetIfChanged(ref filename, value); }

        public ReactiveCommand<Unit, Unit> OpenFileCommand { get; }
        private async Task OnOpenFile()
        {
            //open file logic
        }
    }
```
But now, how can i implement the xaml?
```xml
<MenuItem Header="Recentes" Items="{Binding RecentFiles}">
???
</MenuItem>
```

**Comment by danwalmsley** [comment]
```
<MenuItem Items="{Binding RecentFiles}">       
        <MenuItem.ItemTemplate>
          <DataTemplate>
            <MenuItem Header="{Binding FileName}" Command="{Binding OpenFileCommand}" />
          </DataTemplate>
        </MenuItem.ItemTemplate>
      </MenuItem>
```

That the pattern you can use for any control that takes a list.

ItemsControl, ItemsRepeature, ListBox, TreeView, ComboBox, etc

**Comment by fredericoregateiro** [comment]
@danwalmsley i tryied and something is off, the command doesn't execute and the Header is displaying the viewmodel tostring:
![menu](https://user-images.githubusercontent.com/6304701/81745222-5a5bdc00-949c-11ea-9d0b-61cb16541ece.png)
What is missing where? I have some Combobox with similar datatemplate and is working fine.

**Comment by toomasz** [comment]
Can confirm it still reproduces, when mouse pointer moves over menu - SelectedItem changes to whatever menu item is under pointer. It's not a correct behavior
