### ISSUE TITLE
Tapped command

### ISSUE THREAD

**Issue by fredericoregateiro** [AvaloniaUI/Avalonia#3921]
I'm trying to map events to commands, how can i do it?

One nice feature is to have Tapped and DoubleTapped commands on controls.

**Comment by danwalmsley** [comment]
@fredericoregateiro you cant bind events to commands, you can implement a behavior like this:
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Gui/Behaviors/CommandOnDoubleClickBehavior.cs

**Comment by fredericoregateiro** [comment]
@danwalmsley thanks, i will try
I've checked the code and it seems to be using the http://wieslawsoltes.github.io/AvaloniaBehaviors/ project, event to command out of the box in avaloniaui would be great.

**Comment by grokys** [comment]
See https://github.com/AvaloniaUI/Avalonia/issues/3766

**Comment by grokys** [comment]
I'll close this issue, let's continue any conversation over at #3766.
