### ISSUE TITLE
Problem with transition on certain bound properties

### ISSUE THREAD

**Issue by noughtmare** [AvaloniaUI/Avalonia#3927]
I'm trying to get transitions to work for me. This is a minimal example that I came up with (`MainWindow.xaml`):
```XML
    <Window.Styles>
      <Style Selector="TextBlock">
        <Setter Property="Width" Value="{Binding Pos}" />
        <!-- <Setter Property="Width" Value="100" /> -->
        <Setter Property="Background" Value="Red" />
        <Setter Property="Text" Value="Hello, World!" />
        <Setter Property="Transitions">
          <Transitions>
            <DoubleTransition Property="Width" Duration="0:0:1" />
          </Transitions>
        </Setter>
      </Style>
      <!-- <Style Selector="TextBlock:pointerover">
        <Setter Property="Width" Value="50" />
      </Style> -->
    </Window.Styles>
    <TextBlock PointerPressed="Handler"></TextBlock>
```

Where Handler is (in `MainWindow.xaml.cs`):
```C#
        private void Handler(object _, PointerPressedEventArgs e)
        {
            var mwvm = ((MainWindowViewModel)DataContext);
            mwvm.Pos = mwvm.Pos != 100 ? 100 : 50;
            e.Handled = true;
        }
```

And `MainWindowViewModel.cs` contains:
```C#
        private double _pos;
        public double Pos { get => _pos; set => this.RaiseAndSetIfChanged(ref _pos, value); }

        public MainWindowViewModel()
        {
            Pos = 100;
        }
```

I expected that this would animate the changing of the width on click, but instead the width acts as if it is not set at all (the TextBox spans the entire window). Uncommenting the comments in the xml above and commenting out the line that binds the width of the TextBox will result in a working program that animates the transition of changing the width when hovering over the TextBox.

I have noticed that this does work on some properties like Opacity, but not certain properties like Width and (this is what I want to do in the end) Canvas.Left and Canvas.Top.

**Comment by noughtmare** [comment]
I have found an ugly fix: put the transition style inside a new class like `.enableTransitions` and only add that class to the `TextBlock` right before changing the property `Pos` (you only have to do this once).

**Comment by grokys** [comment]
@noughtmare there are various PRs currently open to fix problems with transitions:

https://github.com/AvaloniaUI/Avalonia/pull/3853
https://github.com/AvaloniaUI/Avalonia/pull/3854
https://github.com/AvaloniaUI/Avalonia/pull/3895

Hopefully this issue will be resolved by them.

**Comment by noughtmare** [comment]
Thanks @grokys. I will wait for those PRs and use my workaround in the meantime.

**Comment by replaysMike** [comment]
Seems to still be an issue 3 years later.

`Transition has no property specified.`
```csharp
<Setter Property="Transitions">
  <Transitions>
    <TransformOperationsTransition Easing="QuadraticEaseOut" />
  </Transitions>
</Setter>
```

**Comment by replaysMike** [comment]
> Seems to still be an issue 3 years later.
> 
> `Transition has no property specified.`
> 
> ```cs
> <Setter Property="Transitions">
>   <Transitions>
>     <TransformOperationsTransition Easing="QuadraticEaseOut" />
>   </Transitions>
> </Setter>
> ```

I am wrong. As the error clearly states, the correct way requires the Property to be specified:
```csharp
<Setter Property="Transitions">
  <Transitions>
    <TransformOperationsTransition Property="RenderTransform" Easing="QuadraticEaseOut" />
  </Transitions>
</Setter>
```

**Comment by replaysMike** [comment]
got rid of the error, but the transitions updates don't seem to have any effect. I was hoping to have a different transition on pointerover vs pressed but I can't get it to work like I would expect. It only applies the default transition specified but the styles don't override it.

```csharp
<Style Selector="controls|AudioMuteButton:pointerover">
  <Setter Property="RenderTransform" Value="scale(0.8)"/>
  <Setter Property="Transitions">
    <Transitions>
      <TransformOperationsTransition Property="RenderTransform" Easing="QuadraticEaseOut" Duration="0:0:2" />
    </Transitions>
  </Setter>
</Style>
<Style Selector="controls|AudioMuteButton:pressed">
  <Setter Property="RenderTransform" Value="scale(0.6)"/>
  <Setter Property="Transitions">
    <Transitions>
      <TransformOperationsTransition Property="RenderTransform" Easing="BounceEaseOut" Duration="0:0:0.2" />
    </Transitions>
  </Setter>
</Style>
```

**Comment by maxkatz6** [comment]
Seems like original issue was solved long time ago.

@replaysMike the issue with your code is that Transitions value is attached/detached immediately when pseudoclass is changed, resetting the animation. So I don't think having two different transitions collections for two different pseduclasses is possible.

**Comment by replaysMike** [comment]
I wasn't able to come up with an alternative for what I was after, so I just stuck with a single easing function. 🤷
