### ISSUE TITLE
DataGrid

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#3928]
How to realize grouping display of dataggrid, as shown in the figure
![image](https://user-images.githubusercontent.com/13539621/81775329-3c838b00-951f-11ea-831a-0a8c42a9b479.png)

**Comment by JamRemco** [comment]
Did you check out the Controlgallery's datagridPage. There is a datgrid with grouping, not as complex as the example in your question, but it might be worth checking out.

Regards, 

Remco

**Comment by jinyuttt** [comment]
s there an open source implementation?

**Comment by maxkatz6** [comment]
@jinyuttt there is DataGridTemplateColumn type that you can use to merge cells into one.
Here is example from WPF, but similar code should work in Avalonia too.
https://stackoverflow.com/questions/17202389/merge-cells-in-wpf-datagrid

**Comment by maxkatz6** [comment]
I believe this issue is answered. Feel free to reopen if you have another related questions.
