### ISSUE TITLE
Avalonia for Visual Studio

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#3929]
Failed to compile successfully based on document operation..

Severity code description project file line suppress status

Error nu1108 loop detected.

Avalonia -> Avalonia.Desktop 0.9.10 -> Avalonia (>= 0.9.10 ). Avalonia E:\\Study\\Avalonia\\Avalonia\\ Avalonia.csproj One

**Comment by kekekeks** [comment]
MSBuild doesn't support referencing NuGet packages with the same name as your project. Try renaming the project to something else.

**Comment by jinyuttt** [comment]
@kekekeks thanks.
