### ISSUE TITLE
FocusElement

### ISSUE THREAD

**Issue by Jmales** [AvaloniaUI/Avalonia#3941]
Hey guys. I'm migrating an app which was using WPF. Some of my WPF windows have other content inside which need to be focused and thus I do this upon opening:
      
```
    FocusManager.SetIsFocusScope(myCustomContent, true);
    FocusManager.SetFocusedElement(this, myCustomContentView.FocusableElement);
```
If I don't do this and have for example an Input inside my customContent, I  cannot focus it when opening the window.

Now, I've been trying to achieve the same in Avalonia but the **FocusManager** seems like it's completely different from what is was in WPF. Also, **FocusManager.Instance.Scope** seems to be null at all times.

Can you help me? How do I convert those 2 lines of code to Avalonia?

Thanks

**Comment by danwalmsley** [comment]
im not sure on how to use the focus manager, but iv acheived this by implementing behavior like this:

https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Gui/Behaviors/FocusOnAttachedBehavior.cs#L7

**Comment by Jmales** [comment]
Thanks for the answer @danwalmsley. Unfortunately it does not solve the problem in my case!

**Comment by grokys** [comment]
I think our focus code needs a fair bit of work regarding focus scopes. However the fact that the scope is null sounds like a bug. Need to investigate. If you have any more info on how to get a null focus sope that would be helpful.
