### ISSUE TITLE
ribbon

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#3949]
Is it very complex to realize the relatively complete function, as shown in the figure:
![image](https://user-images.githubusercontent.com/13539621/82108445-fe75a980-9760-11ea-95fe-3e633534a9d2.png)

**Comment by JamRemco** [comment]
is tgus a qeustion? Im not sure what you try to say

**Comment by jinyuttt** [comment]
I mean the technical complexity of the implementation. I want to achieve such a display effect

**Comment by kekekeks** [comment]
https://github.com/waliarubal/AvaloniaRibbon

**Comment by JamRemco** [comment]
@kekekeks 
Thats what i told him in a earlier post https://github.com/AvaloniaUI/Avalonia/issues/3873#issuecomment-622949958

@jinyuttt You have to puzzle a bit it is not WinForms ;)

Good luck,

Remco

**Comment by jinyuttt** [comment]
thanks
