### ISSUE TITLE
No longer possible to set a property value to unset

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#3956]
After #3853, it's no longer possible to set a property value to `AvaloniaProperty.UnsetValue`. I don't know if it's intentional, but it breaks some code.

## Repro

Setting the default value of a property to `AvaloniaProperty.UnsetValue` (e.g. in `Button`):

```cs
        public static readonly StyledProperty<object> XProperty =
            AvaloniaProperty.Register<Button, object>(nameof(X), AvaloniaProperty.UnsetValue);

        public object X
        {
            get => GetValue(XProperty);
            set => SetValue(XProperty, value);
        }
```

Not sure if needed, XAML:

```xaml
<Button X="{Binding}" />
```

Throws the exception:

```
System.InvalidOperationException: 'AvaloniaValue.UnsetValue is not a valid value for BindingValue<>.'
```

From: https://github.com/AvaloniaUI/Avalonia/blob/15caf2bcababeb38a2e21826eb436f0cd5de08aa/src/Avalonia.Base/Data/BindingValue.cs#L361

**Comment by grokys** [comment]
@jp2masa could you tell me what setting the default value to `UnsetValue` is supposed to mean?

Note that this is invalid in WPF: https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/PropertyMetadata.cs#L102-L105

The fact that you could do this previously I think was an oversight...

**Comment by jp2masa** [comment]
I agree it doesn't make much sense, it was from a project I depend on, just wanted to know if it was intentional. Thanks!
