### ISSUE TITLE
Simple Q about net core mismatch by build

### ISSUE THREAD

**Issue by JamRemco** [AvaloniaUI/Avalonia#3959]
By building i am Getting this error.

> A compatible installed .NET Core SDK for global.json version [3.1.101] from [C:\Users\Remco\source\repos\Avalonia\global.json] was not found
Install the [3.1.101] .NET Core SDK or update [C:\Users\Remco\source\repos\Avalonia\global.json] with an installed .NET Core SDK:
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]

Should i update Global.json or download an older version [3.1.101] of the SDK

Regards,

Remco

**Comment by kekekeks** [comment]
.NET Core update has somehow broken one of the MSBuild tasks (missing method exception for System.Xml).

**Comment by JamRemco** [comment]
So i should install an older version?

**Comment by Gillibald** [comment]
Yes. You have to install `.Net Core SDK 3.1.101`

**Comment by JamRemco** [comment]
tnx, will do
