### ISSUE TITLE
More building Exceptions

### ISSUE THREAD

**Issue by JamRemco** [AvaloniaUI/Avalonia#3963]
When building controlgallery i got  no error, but when i run/debug it throws a runtime Exception.

> Exception thrown: 'System.BadImageFormatException' in SkiaSharp.dll
Exception thrown: 'System.TypeInitializationException' in Avalonia.Skia.dll

Its probebly me, but if someone have a hint, please let me know.

I realy want to contribute to this awesome project, but somehow Fork and build does not work for me.

Win 10
VSCE 16.5.5

Regards, 

Remco

**Comment by MarchingCube** [comment]
Try running .net core version of the control catalog. I think desktop one has issues at least on win32.

**Comment by JamRemco** [comment]
duh!!!!

Sometimes i am such a dork haha

Tnx,

Remco
