### ISSUE TITLE
WebBrowser Control

### ISSUE THREAD

**Issue by stevendevit** [AvaloniaUI/Avalonia#3964]
Is there a WebBrowser Control for Avalonia? I want to make an app that can run and switch between web based "apps" 

Thanks in advance

**Comment by grokys** [comment]
There are a couple of CEF bindings for Avalonia if that would help?

https://github.com/AvaloniaCommunity/awesome-avalonia#web-browsers

**Comment by stevendevit** [comment]
Yes!! CefGlue is what I needed. Thanks!!
