### ISSUE TITLE
Allow for capturing mouse when menus and context menus are open.

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#3965]
Currently when menus and context menus are open we can still partly interact with the rest of the application via pointer over effects and tooltips (and more). Most of the UI frameworks like WPF/Qt prevent such interaction as it is confusing for the user.

Ideally when context menu is open user should be able to interact with the menu itself and nothing in the main app.

**Comment by kekekeks** [comment]
>user should be able to interact with the menu itself

There are parent menus though.

**Comment by MarchingCube** [comment]
@kekekeks I mean that user should be able to interact with the whole open context or menu hierarchy. Including children but excluding context that does not belong to the menu itself.

**Comment by MarchingCube** [comment]
I've noticed one more pointer capture difference:

WPF:
![context-menu](https://user-images.githubusercontent.com/2588062/83505875-b2e42f00-a4c6-11ea-8460-50d644655530.gif)

Avalonia:
![context-menu-avalonia](https://user-images.githubusercontent.com/2588062/83505879-b4adf280-a4c6-11ea-905f-d3fc03a30bd2.gif)

In WPF items do not capture mouse pointer which allows you to select other menu item even after initial click on a different menu item.
