### ISSUE TITLE
No preview and intellisense in avalonia fork and a exception in Preview sample

### ISSUE THREAD

**Issue by JamRemco** [AvaloniaUI/Avalonia#3966]
Hello world,

2 "issues" but possibly related

**1**
The previewer and IntelliSense are not working
but i can change code and run it.
On the designer surface is states:
> notification: No executable . reference the library from an executable or wait for the solution to finish loading

Other projects (standalone) are working fine.

**2**
When i trie to run the preview App from samples it trows an error:

> Avalonia.Markup.Xaml.XamlLoadException
  HResult=0x80131500
  Message=No precompiled XAML found for Previewer.App, make sure to specify x:Class and include your XAML file as AvaloniaResource
  Source=Avalonia.Markup.Xaml
  StackTrace:
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj) in C:\Users\Remco\source\repos\Avalonia\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 23
   at Previewer.App.Initialize() in C:\Users\Remco\source\repos\Avalonia\samples\Previewer\App.xaml.cs:line 10
   at Avalonia.Controls.AppBuilderBase`1.Setup() in C:\Users\Remco\source\repos\Avalonia\src\Avalonia.Controls\AppBuilderBase.cs:line 293
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in C:\Users\Remco\source\repos\Avalonia\src\Avalonia.Controls\AppBuilderBase.cs:line 162
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider) in C:\Users\Remco\source\repos\Avalonia\src\Avalonia.Controls\AppBuilderBase.cs:line 126
   at Previewer.Program.Main(String[] args) in C:\Users\Remco\source\repos\Avalonia\samples\Previewer\Program.cs:line 10

Regards,

Remco

**Comment by kekekeks** [comment]
You probably need to add 
https://github.com/AvaloniaUI/Avalonia/blob/8b26f4ef255e613e837a01c4e251c97211165a8c/samples/ControlCatalog/ControlCatalog.csproj#L32

**Comment by JamRemco** [comment]
Seems fine to me 
``` Xaml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>    
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
    <AvaloniaResource Include="Assets\*" />
    <AvaloniaResource Include="Assets\Fonts\*" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Regular.ttf" />
    <EmbeddedResource Include="Pages\teapot.bin" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\packages\Avalonia\Avalonia.csproj" />
    <ProjectReference Include="..\..\src\Avalonia.Diagnostics\Avalonia.Diagnostics.csproj" />
    <ProjectReference Include="..\..\src\Avalonia.ReactiveUI\Avalonia.ReactiveUI.csproj" />
    <ProjectReference Include="..\..\src\Avalonia.Controls.DataGrid\Avalonia.Controls.DataGrid.csproj" />
  </ItemGroup>
  
  <Import Project="..\..\build\Serilog.props" />
  <Import Project="..\..\build\BuildTargets.targets" />
</Project>
```

**Comment by kekekeks** [comment]
@grokys our VS extension extracts the previewer binary location from MSBuild props, right?

**Comment by grokys** [comment]
Thanks right:

https://github.com/AvaloniaUI/AvaloniaVS/blob/master/AvaloniaVS/Services/SolutionService.cs#L214-L215

**Comment by kekekeks** [comment]
@grokys they do https://github.com/AvaloniaUI/Avalonia/blob/8b26f4ef255e613e837a01c4e251c97211165a8c/build/BuildTargets.targets#L3

**Comment by kekekeks** [comment]
We probably need to add those to Directory.build.props

**Comment by JamRemco** [comment]
Oke oke 

Can i manualy fix this?

**Comment by grokys** [comment]
@JamRemco add this line to `samples\Directory.Build.props` in `<PropertyGroup>`:

```
      <AvaloniaPreviewerNetCoreToolPath>$(MSBuildThisFileDirectory)..\src\tools\Avalonia.Designer.HostApp\bin\Debug\netcoreapp2.0\Avalonia.Designer.HostApp.dll</AvaloniaPreviewerNetCoreToolPath>
```

**Comment by JamRemco** [comment]
thank you
