### ISSUE TITLE
General: too much dependencies!

### ISSUE THREAD

**Issue by WrongBit** [AvaloniaUI/Avalonia#3971]
Hi all!
I tried to use Avalonia on Win7/.NET FW 4.8; And as you guess I failed (despite declared applicability to .NET FW). This means that your project has clumsy structure and too much dependencies from unnecessary things (say, Serilog - serious?! So needed lib for... GUI?? ).
Obviously we don't need every platform and if I want to run app on Win and Linux, why I should be bored with Android dependencies?? I'm sure project should be splitted on common and platform-depended part, so if right now I need support for Win only, I should not download tens of GIGABYTES of Android support just to compile this Avaborian. Current project structure is unprofessional bloatware.

**Comment by grokys** [comment]
Please, be respectful.

**Comment by kekekeks** [comment]
@WrongBit Avalonia is distributed through nuget.org, you don't need to build the repository to use it.

To use it with .NET 4.x you need to specify the corresponding `TargetFramework` in your csproj file (e. g. `net48` for .NET 4.8)

You can find an example of running with .NET 4.7.2 [here](https://github.com/AvaloniaUI/ControlCatalogStandalone/tree/master/ControlCatalog.NetFX) (Latest Visual Studio and latest SDK are recommended).

Serilog and ReactiveUI dependencies are optional for your application, you can skip adding them.

Have a nice day.
