### ISSUE TITLE
StyleInclude

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#3978]
Is there any relevant usage document and how to use it in XAML files of other projects?

**Comment by JamRemco** [comment]
Hellop world,

There is not much,  but i found a article that might helps you a bit
[https://habr.com/en/post/471342/](url)

Good Luck

Remco

**Comment by FlaviusHouk** [comment]
You can look throught the samples provided [here](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/App.xaml), for example, in this repo.

**Comment by grokys** [comment]
Added an issue on our docs repo to remind us.
