### ISSUE TITLE
Confused : the next version after 0.9.9 is 0.9.10 in stead of 1

### ISSUE THREAD

**Issue by JamRemco** [AvaloniaUI/Avalonia#3979]
Hello world

I got it. .9 becomes. .10 in the last part , but looks like a regression, or at least to me.
It took me a bit to realise its a newer version in stead of an older one. hahaha.

Remco

**Comment by JamRemco** [comment]
Why the thumb down?

**Comment by grokys** [comment]
We follow semantic versioning, which is quickly becoming the standard for versioning software. In fact nuget now recommends that you follow semver, so this is definitely not particular to us.

See semver.org for more details.
