### ISSUE TITLE
DatePicker Calendar popup wilting

### ISSUE THREAD

**Issue by usUyGBx** [AvaloniaUI/Avalonia#3980]
Steps to reproduce:

1. Navigate to ControlCatalog->DatePicker
2. Select some date in the first control by mouse clicking
3. Open same Calendar second time and try to move mouse over popup.

I suspect that it is not Calendar fault but popup itself, because there is another scenario involving popup button and control wilting.

**Comment by JamRemco** [comment]
Yeay thats odd, sometimes the highlighting doesnt work when hovering over the calendar.
It looks like it no longer receives mouseEvents. but the arrowkeys stil work.

It alsp happends when you leave the calendar open en moce the mouse out of the popuparea and then move back.
