### ISSUE TITLE
Documentation does not support development

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#3981]
I don't know how to learn Avalonia, but as a newcomer, I don't think the existing documents can support the project development, and I hope someone can start the document sorting work. Is Avalonia version 1.0 the official version?

**Comment by JamRemco** [comment]
I agreed that the docs aare a bit lacking as i am also relatively new to this.
However, a lot is simular to wpf. 
There are some blogs/sites that can help.
[This guy](https://www.nequalsonelifestyle.com/2019/06/11/avalonia-grid-panel-layout-part1/) got a dozen tuts on avalonia for beginners.

Regards,

Remco

**Comment by grokys** [comment]
Hi @jinyuttt - could you let us know how we could improve the docs please? What in particular did you find lacking?

**Comment by jinyuttt** [comment]
@grokys 
It's mainly Avalonia's keywords, special syntax. As a development document, you can't subjectively think that I'm already a master. actually https://avaloniaui.net/docs It has a skeleton and needs to be improved. For example:

<StyleInclude Source=" avares://Avalonia.Controls.Ribbon/Styles/RibbonStyles.xaml " />

What does styleinclude mean? What does avares mean? What does this sentence mean?

What's the meaning of resm for some projects I've seen? But official documents do not.

**Comment by JamRemco** [comment]
@jinyuttt I feel your frustation i am myself, just start to scratch the surface.

StyleInclude is a bit like Using in c# or Import in VB
Avares means: **AVA**lonia **RES**ource

In the case of (as example)
  ```Xaml 
    <StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml"/>
```
It means 
Include the sty.es as defined in the resource: DefaultTheme.xaml in the library Avalonia.Themes.Default

If you download the source of avalonia(if you not alteady have done that)
There is a project thats called Avalonia.Themes.Default
In that project there is a file called DefaultTheme.xaml
In this file are all the Style Includes for all the styleTrmplates such as buttom.xaml, Treeview.xaml and Textbox.xaml and a lot more .
This way "we" onl;y have to include 1 file.
In the BaseLight/Dark are the brushes defined such as BorderHighlightcolor and NormalBorderBrush 

Hope it helps,

Remco

**Comment by grokys** [comment]
@jinyuttt yeah we all accept that the docs need to be improved. We don't have a docs writer and so it's basically just me.

Regarding `avares` and `resm` they're explained here. Maybe we need to link that page from other parts of the documentation. Where did you come across them?

**Comment by jinyuttt** [comment]
@JamRemco Thank you. I've learned from another question

**Comment by jinyuttt** [comment]
@grokys  
Thank you. Thank you very much for your contribution to the project and for your great help.

I'm just giving you an example of what you need to document. At present, I am learning and consulting open source projects. What we know is confusing.

If the current document is not convenient to organize, I suggest that you link other people's examples directly in the form of a blog post, for example: https://habr.com/en/post/471342/ .

Is this more efficient and can solve immediate problems?
