### ISSUE TITLE
Orientation on HeaderedContentControl

### ISSUE THREAD

**Issue by JamRemco** [AvaloniaUI/Avalonia#3982]
Hello world!

Is there a reason why there is no oriontation property on the HeaderedContentControl?.
I think it makes the control more usefull.
Somewhat like the slider with :horizontal and :vertical states/classes

Regards,

Remco

**Comment by Gillibald** [comment]
`HeaderedContentControl` isn't supposed to be used directly. Having an `OrientationProperty` on it would enforce some orientation support for every control that uses `HeaderedContentControl` as the base.

**Comment by JamRemco** [comment]
Oke i see.

Because of the discusion [here](https://github.com/AvaloniaUI/Avalonia/pull/3913#issue-415604836)
I thought that it might be a nice "job" to give it a proper template.

Regards,

Remco
