### ISSUE TITLE
Corner Radius isnt rendering correcly on Skia

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#3985]
```
<Border Padding="50" BorderThickness="1" CornerRadius="1" BorderBrush="Black" VerticalAlignment="Center" HorizontalAlignment="Center">
            <TextBlock Text="Testing" />
</Border>
```

![image](https://user-images.githubusercontent.com/4672627/82764383-a126cb80-9de4-11ea-90f9-538f961116e5.png)

Image shows avalonia on the left and uwp on the right....

Also corner radius = 2 on UWP / WPF looks better than avalonia... we may have some rounding or calculation issue.

**Comment by Gillibald** [comment]
BoxShadows PR has changed the way borders are rendered. You should test this without that PR being merged.
