### ISSUE TITLE
Allow executing a command on enter key press in TextBox

### ISSUE THREAD

**Issue by MarcusWichelmann** [AvaloniaUI/Avalonia#3992]
When building forms with multiple text boxes and a "Submit" button, it would be very helpful if the submit command would get executed when pressing Enter in any of these text boxes.

Currently it's already possible to iterate through the different input fields by pressing the tab key. But it would be a great addition if pressing the enter key in any of the (single-line) text boxes would trigger a selected command, so the users would not have to press Tab many times until the submit button is selected.

In multi-line text boxes, the submit could happen on Sift+Enter or Ctrl+Enter, just like it's done in most web applications.

Syntax Suggestion:
```XAML
<TextBox Text="{Binding Host}" Command="{Binding ConnectCommand}" />
<TextBox Text="{Binding Port}" Command="{Binding ConnectCommand}" />
<Button Command="{Binding ConnectCommand}" />
```

**Comment by Gillibald** [comment]
``<Button IsDefault="True" Command="...."/>` should work.

**Comment by milkotv** [comment]
Hi @Gillibald, I am unable to do the opposite - clicking on a non-default button and then keep pressing Enter keeps executing the command 

<Button IsDefault="False" Command="...."/>

Any idea what I am doing wrong ?
Thanks

**Comment by zalito12** [comment]
According to the tutorials you can also bind to gestures like this

````
            <TextBox.KeyBindings>
                <KeyBinding  Command="{Binding ConnectCommand}" Gesture="Enter" />
            </TextBox.KeyBindings>
````

But I preffer the OP solution for simple forms or inputs.
