### ISSUE TITLE
Allow RadialGradientBrush to use absolute radius size

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#3995]
Would it be possible to allow the `RadialGradientBrush` to use an absolute size instead of relative? I'm not sure what's the best solution to offer, but something like `RelativePoint` or `RelativeRect`. I'd say RelativeSize, but since Radius is X-Y uniform, that might get confused with the `Size` struct.

I'm trying to implement a pseudo-Reveal effect, which uses the RadialGradientBrush, and the relative size leads to a non-uniform border effect when things are different sizes, e.g.

![image](https://user-images.githubusercontent.com/40413319/82869034-3e702580-9ef3-11ea-84e5-81edf1c5c218.png)

**Comment by Gillibald** [comment]
Looks like this was already documented but somehow got lost:https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Media/RadialGradientBrush.cs#L57

**Comment by grokys** [comment]
Speaking about this with @wieslawsoltes and looks like this property controls this on WPF: https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.gradientbrush.mappingmode?view=net-5.0
