### ISSUE TITLE
AvaloniaProperty.Register validate function missing TOwner parameter.

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#3998]
According the current and previous Avalonia documentation the AvaloniaProperty.Register validate function has the TOwner passed as a parameter but this is missing in the current implementation.

```
validate: A validation/coercion function of type Func<TOwner, TValue, TValue>. The function accepts the instance of the class on which the property is being set and the value and returns the coerced value or throws an exception for an invalid value.
```

The TOwner parameter is useful where you want to validate a property change against other properties of the TOwner class.  For example performing range constraint for a Value property, using MaxValue and MinValue properties that can be set for each instance of the TOwner control.

I see this is listed as a breaking change for v0.10 but unless there is a good reason to remove the TOwner parameter I would ask for it to be reinstated for the above reasons.

Avalonia 0.9.999 cibuild

**Comment by grokys** [comment]
We recently changed AvaloniaProperty validation to follow WPF semantics as people were complaining that it was hard to port controls: https://github.com/AvaloniaUI/Avalonia/pull/3287

As with WPF, if you want to receive an instance of the control you must define a coercion function, which cannot throw but _can_ coerce the value to a valid value.

See the WPF docs for more info: https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/dependency-property-callbacks-and-validation

The docs need updating but as they reflect the state of the current stable release, so they won't be updated until 0.10 is stable (we do need a way to host documentation for multiple versions, but this is a big TODO at the moment).
