### ISSUE TITLE
Managed system dialogs is broken on Linux.

### ISSUE THREAD

**Issue by FlaviusHouk** [AvaloniaUI/Avalonia#4001]
It looks like managed dialogs is not working on current version 0.9.10 (version 0.9.9 works fine). Application is constructed in a way described below.

```
_lifetime = new ClassicDesktopStyleApplicationLifetime() { ShutdownMode = ShutdownMode.OnMainWindowClose };
_builder = AppBuilder.Configure<App>();

_builder.UsePlatformDetect()
             .UseReactiveUI()
             .UseManagedSystemDialogs()
             .LogToDebug()
             .SetupWithLifetime(_lifetime);
```

Here is code to show open file dialog (w is a not null window object):
```
return await openFileDialog.ShowAsync(w);
```

There is such output after execution:
[Binding] Error in binding to "Avalonia.Input.KeyBinding"."Command": "Null value in expression ''." (Avalonia.Input.KeyBinding #53954942)
[Control] DropDown is deprecated: Use ComboBox (Avalonia.Controls.DropDown #29578451)
Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll

OS: Fedora 32 x64.
P. S. This code works on 0.9.9.

**Comment by Toemsel** [comment]
10.02 and this still doesn't work. Please assign a higher priority to this. We have to drop Avalonia now because of a buggy basic feature like a file-dialog.

**Comment by kekekeks** [comment]
@Toemsel 
You probably just need to set the dialog title - https://github.com/AvaloniaUI/Avalonia/issues/5570

It definitely should get fixed on Avalonia side though

**Comment by Toemsel** [comment]
> @Toemsel
> You probably just need to set the dialog title - #5570
> 
> It definitely should get fixed on Avalonia side though

Your suggested solution does work as a workaround. Many thanks.

**Comment by Toemsel** [comment]
I would like to add, that we prefer the native dialog-system. The managed one is not matching the Fluent-Design.
