### ISSUE TITLE
How to feed combobox items depending on another combobox 

### ISSUE THREAD

**Issue by mlengele** [AvaloniaUI/Avalonia#4003]
Dear all, 
I'm new in Avalonia (and in WPF too) ;-).
On my view, I have two combobox. 
What I want to do is that the items of the second combobox are automatically updated following the selected item on the first combobox. 
What I can do for now is to bind and to populate the two comboboxes at initialization, but when I change the selected item on the first combobox, I cannot update the second.
Could You help me to do that? 
Thanks in advance!

**Comment by JamRemco** [comment]
Not sure if i understand exactly your requirement
But if you want something like 

> first combo: Countries
second combo Cities in selected Country

You can try To make a linq query based on the first combobox
and bind the results of query to the second combo.
or filter the data somehow.

Remco

**Comment by mlengele** [comment]
Hi Remco,

It is clearly what I want to do.
How can I proceed ? Do you have an example on which I can based me?

Thanks a lot!

Marc

**Comment by rstm-sf** [comment]
@mlengele hello, you need to use [INotifyPropertyChanged (INPC)](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged). This interface is used in the [MVVM](https://en.wikipedia.org/wiki/Model–view–viewmodel) pattern. [This article](https://medium.com/@worldbeater/reactive-mvvm-for-net-platform-175dc69cfc82) and the [Quickstart](https://avaloniaui.net/docs/quickstart) in the documentation may help you. Also, I recommend to go through the [ToDo Tutorial](https://avaloniaui.net/docs/tutorial) using only the INPC
