### ISSUE TITLE
Routed Attached Event Won't Compile

### ISSUE THREAD

**Issue by seanocali** [AvaloniaUI/Avalonia#4009]
v0.9.10

Per this documentation:
[https://avaloniaui.net/docs/input/events](https://avaloniaui.net/docs/input/events)

I couldn't get it to compile. 

> Error	XAMLIL	Unable to resolve suitable regular or attached property Click on type Avalonia.Controls:Avalonia.Controls.Button (line 16 position 6) Line 16, position 6.	AvaloniaApplication1

 I was able to recreate the problem in a brand new project using the example code.

```
<Border>
  <StackPanel Orientation="Horizontal" Button.Click="CommonClickHandler">
    <Button Name="YesButton">Yes</Button>
    <Button Name="NoButton">No</Button>
    <Button Name="CancelButton">Cancel</Button>
  </StackPanel>
</Border>
```

```
public void CommonClickHandler(object sender, RoutedEventArgs e)
{
    // Handle
}
```

**Comment by grokys** [comment]
Ah yes, looks like that feature isn't yet implemented, sorry @seanocali - my bad, I thought it was implemented.

We hope to have this feature working for 0.10, but in the meantime you'll have to add a click handler to each button separately.

**Comment by yankun** [comment]
Does still not work as of 02/2022. Wouldn't it be nice to update the documentation? Wasted some time to figure out, that I was trying to use a feature which is not yet implemented...

**Comment by maxkatz6** [comment]
Closing in favor of a more specific issue - #9507. Documentation was updated.
