### ISSUE TITLE
ScrollViewer doesn't display scrollbars until resize in modal windows

### ISSUE THREAD

**Issue by arklumpus** [AvaloniaUI/Avalonia#4011]
Hello, this may be related to #3707 .

When a Window with a ScrollViewer is opened _using ShowDialog_, the ScrollViewer does not display the scrollbars until the window is resized.

To reproduce, create a new Avalonia Project and add a new Window `Window1` with the following XAML:

```XAML
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" Width="200" Height="200"
        x:Class="TestAvaloniaScrollbar.Window1"
        Title="Window1">
  <ScrollViewer HorizontalScrollBarVisibility="Visible" VerticalScrollBarVisibility="Visible">
    <Canvas Width="300" Height="300" Background="Red" />
  </ScrollViewer>
</Window>
```

Then, replace the constructor in `MainWindow.xaml.cs`:

```Csharp
public MainWindow()
        {
            InitializeComponent();
#if DEBUG
            this.AttachDevTools();
#endif
            this.PointerReleased += async (s, e) => { await new Window1().ShowDialog(this); };
        }
```

Now, if run the program and click on the window, a `Window1` dialog will appear, without scrollbars. If you slightly resize the window, the scrollbars will appear.

- I have reproduced the issue in 0.9.7, 0.9.9 and 0.9.10; correct behaviour is present in 0.9.4, 0.9.5 and 0.9.6
- In 0.9.9 and 0.9.10, If you use Window1.Show() instead of ShowDialog, the scrollbars appear correctly. In 0.9.7 they do not. 0.9.4, 0.9.5 and 0.9.6 behave correctly with both Show and ShowDialog.
- When running on Windows, the behaviour is what is described above. When running on Linux, the scrollbars appear; however, the dialog does not seem to work as intended (i.e. it is still possible to click on the MainWindow to spawn more instances of Window1, as if Show had been used, rather than ShowDialog).

**Comment by arklumpus** [comment]
Update: this still happens with 0.9.11.

**Comment by danwalmsley** [comment]
@arklumpus what about 0.10.0-preview1?

**Comment by arklumpus** [comment]
It seems to work fine on 0.10.0-preview1 on Windows, thanks!

**Comment by timunie** [comment]
Closing this as @arklumpus said it works since 0.10.0-preview1
