### ISSUE TITLE
TextBox "Clear" button

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#4022]
I noticed, that TextBox in Avalonia hasn't "clear all" button.
It isn't must have feature, but could be useful for some users.

![textbox-clear](https://user-images.githubusercontent.com/3163374/83230751-55fc1800-a158-11ea-8f16-c6939cd8a653.gif)

**Comment by maxkatz6** [comment]
Done with https://github.com/AvaloniaUI/Avalonia/pull/4422
Thanks @jmacato 

![image](https://user-images.githubusercontent.com/3163374/90323517-84f08180-df30-11ea-90f1-d7f8ce9fe9be.png)

**Comment by FG-rgb** [comment]
Hello, is there an example or a documentation how to set a clear button on a textbox?
I don't find any documentation.

**Comment by FG-rgb** [comment]
Ahhh, I found InnerLeftContent and InnerRightContent. If I set InnerRightContent to my own button it seem to work :)

**Comment by FG-rgb** [comment]
Ah, there are also some predefined styles for textbox in Textbox.xaml of themes, like 'clearButton', nice.
