### ISSUE TITLE
Compact Sizing for controls

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#4024]
With latest changes for Fluent theme, some developers would prefer smaller controls.

WinUI's implementation is really simple - they just override global resources with "smaller" values:
https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/dll/DensityStyles/Compact.xaml

![compact](https://user-images.githubusercontent.com/3163374/83235182-7a0f2780-a15f-11ea-967c-b72a91598e67.gif)

**Comment by maxkatz6** [comment]
Even thought it should be difficult to implement after Fluent theme will be ready, I don't think it is really important. For me "compact" styles looks to small. And developer can override those resources without special feature.

**Comment by JamRemco** [comment]
I think it would be usefull. its just like basedark or baselight

**Comment by danwalmsley** [comment]
This will be added and work in the exact same way as winui.

**Comment by maxkatz6** [comment]
Done with https://github.com/AvaloniaUI/Avalonia/pull/4157
