### ISSUE TITLE
Support Incremental (infinity) loading for list controls

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#4025]
While changes in ObservableCollection dynamically shows in list controls using INotifyCollectionChanged interface, there is no way for Avalonia to request/fetch more items. 

UWP has ISupportIncrementalLoading interface to solve that problem. However it requires to create custom collection type which implements INotifyCollectionChanged and ISupportIncrementalLoading (last one doesn't exist in .Net Standard or Core and requires dependency on UWP/WinUI).

Another approach is subscribing on ScrollViewer events in invoke method/command to fetch more items. But it doesn't work out of box and requires writing additional code.

I am not familiar with ReactiveUI, but does it provide that functionality? Probably https://github.com/reactiveui/DynamicData can, but I am not sure, if Avalonia support it out of box.

ISupportIncrementalLoading API from UWP:
```csharp
public interface ISupportIncrementalLoading
{
    Task<LoadMoreItemsResult> LoadMoreItemsAsync(uint count);

    bool HasMoreItems { get; }
}

public struct LoadMoreItemsResult
{
    public uint Count;
}
```

**Comment by kekekeks** [comment]
Has more items in *which direction*?

**Comment by maxkatz6** [comment]
@kekekeks good point. UWP doesn't support any other direction apart from most common - from top to bottom.
There are "official" way to create inverted list, but I am not sure, if it will work with ISupportIncrementalLoading: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/inverted-lists
Also UWP's solution doesn't work with grouped lists out of box.

I hope another frameworks could have better implementation.

**Comment by timunie** [comment]
MahApps has a `ScrollViwerHelper` which can run a command when the end of a scrollviewer was reached. In this command the user can just load more items. 

https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Controls/Helper/ScrollViewerHelper.cs 

I don't know if this is a good choice for Avalonia, but maybe at least worth to mention
