### ISSUE TITLE
Can't Preview the Window

### ISSUE THREAD

**Issue by valkyrienyanko** [AvaloniaUI/Avalonia#4032]
I've created a fresh **Avalonia MVVM Application** and I cannot preview the window as shown below. I've also attached my `.csproj` below.

This [issue](https://github.com/AvaloniaUI/AvaloniaVS/issues/129) seems related but I can't seem to find anything that helps me in it.

![Preview](https://i.imgur.com/YGAcUHS.png)
![Preview2](https://i.imgur.com/2DJ5u4Q.png)

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net461;netcoreapp2.1</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.10" />
    <PackageReference Include="Avalonia.Desktop" Version="0.9.10" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.9.10" />
  </ItemGroup>
</Project>
```

**Comment by Deadpikle** [comment]
👋 
You can only set a `Window` content once -- you have both a button and a text block in there. Try putting them in a stack panel or something else.

e.g.
```xml
<Window ...>
  <StackPanel Orientation="Vertical">
       <Button Content="Click me!"/>
       <TextBlock Text="{Binding Greeting}" />
  </StackPanel>
</Window>

```

**Comment by valkyrienyanko** [comment]
@Deadpikle Thankyou

The problem seems to have gone away on its own. The problem persisted even without the button snippet before. I think what happened is I forgot to build the project? I'm not sure.

What I did
- Waited 2 hours
- Started up VS
- Built the project
- Saw that it was working

**Comment by barkermn01** [comment]
Sorry to wake this up, but i seem to be getting this issue now, 

This is a brand new project from using the WSIX extension in my Visual Studio's 2022, i have not written any code what so ever in this, created the project and built that's it,

![image](https://user-images.githubusercontent.com/37368/149824070-7bdff59c-9e27-45f3-8221-17963b5055c7.png)

**Comment by akejo** [comment]
So for the top right area I want a number of buttons. 0-9, enter and = along widt add, minus, multiplication and division buttons order like a calculator, have som padding between them and
