### ISSUE TITLE
KeyModifiers don't work properly on NumPad

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [AvaloniaUI/Avalonia#4038]
I subscribed to KeyUp event of Image and use both Key and KeyModifiers in handling. On main keyboard it works fine.
But when I am holding Shift and press and release numbers on NumPad I receive:
`Key` is a left or right shift, and `Modifiers` is `None`.

I expect to receive `NumPadX` and `Shift` instead.

I use Avalonia 0.9.10 and .Net Core 3.1 on Windows 10.

**Comment by AngelicosPhosphoros** [comment]
I found that Ctrl and Alt are working but only Shift not works.

**Comment by MarchingCube** [comment]
This is basically how keyboard works on Windows. On my Windows 10 install Avalonia keyboard input is no different than WPF.

https://devblogs.microsoft.com/oldnewthing/20040906-00/?p=37953
