### ISSUE TITLE
Fluent Theme: Things to revisit

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#4039]
- AutoSuggestBox rename
- AutoSuggest box could open above the textbox.
- AutoSuggest box should remove corner radius' that share an edge with the popup...

Attached property can be used... https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/AutoSuggestBox/AutoSuggestBoxHelper.cpp

**Comment by danwalmsley** [comment]
Scrollbar autohide on windows could follow:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.uisettings.autohidescrollbars?view=winrt-19041#Windows_UI_ViewManagement_UISettings_AutoHideScrollBars

**Comment by danwalmsley** [comment]
Slider:
Jump to position on click... Snap to ticks. Popup that follows thumb.

**Comment by maxkatz6** [comment]
ToolTip:
1. Opacity transition doesn't work on ToolTip closing, because we don't wait for animation before we call .Close(). Fixing this issue will affect default style.
2. There is no ToolTip shadow, seems like it should be implemented with BoxShadow. But all another popups should also support it for consistency.

**Comment by maxkatz6** [comment]
Button, ToggleButton, RepeatButton:
Reveal (light effect) and click animation:
![button](https://user-images.githubusercontent.com/3163374/84557274-94b4d500-acf7-11ea-831e-0e6e944f61f2.gif)

**Comment by danwalmsley** [comment]
Menus:

MenuHeight 40px?
Checkbox, and RadioChecked style?
NativeMenu sync... checkbox not working in managed.
Generated submenu sometimes behind... (set parent?)

**Comment by maxkatz6** [comment]
NumericUpDown + ButtonSpinner:
For now only Inline mode. Should be expected to have Compact mode as well.

**Comment by danwalmsley** [comment]
Combobox and others... hidden header presenter adds a few pixels.

**Comment by maxkatz6** [comment]
Focus Adorner (Focus Visual)

- Support negative margin for adorner. Currently it is clipped with adorned control bounds.
- Add properties to customize adorner thickness, brush and margin per control. Or should developers customize it with resource overriding?
- Rename FocusVisual resources to FocusAdorner resources?

@grokys also proposed to reimplement focus adorner layer to work in same way as UWP one (don't allow to use custom adorner, and limit customization with specific props) to remove adorner allocations per control.
