### ISSUE TITLE
WindowStartupLocation Not Working on Unity Desktop

### ISSUE THREAD

**Issue by seanocali** [AvaloniaUI/Avalonia#4046]
Avalonia 0.9.10

'WindowStartupLocation.CenterScreen' and 'WindowStartupLocation.CenterOwner' both work in Windows but the only Linux environment I've been able to test (Ubuntu 20.04) it does not work. Both spawn near the dock without any relation to where they're supposed to spawn.

**Comment by Symbai** [comment]
#3561
