### ISSUE TITLE
DataGrid: Showing row numbers

### ISSUE THREAD

**Issue by danielkupco** [AvaloniaUI/Avalonia#4064]
Is there any way to display row numbers (1, 2, 3...) in DataGrid and how?

I was unable to find anywhere a solution for this, and was thinking of 2 ways of doing this:

1. Show the row numbers within row headers
2. Add a leftmost column (which should not be editable) displaying a row number for each row

It would be good if this feature could be enabled with a simple property setter like
`<DataGrid ShowRowNumbers="True" ... />`

**Comment by maxkatz6** [comment]
You can check how it works in ControlCatalog with Fluent theme now.
It doesn't work with old Default theme though, because of missing template.

**Comment by maxkatz6** [comment]
Fixed with https://github.com/AvaloniaUI/Avalonia/pull/5129
