### ISSUE TITLE
Cannot prevent closing of a window if use async OnClosingHandler

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [AvaloniaUI/Avalonia#4070]
I have code like this in my window class.
```csharp
       {
            // in constructor
            this.Closing += OnStandardClosing;
        }

        private async void OnStandardClosing(object? sender, System.ComponentModel.CancelEventArgs e)
        {
            if(!await CheckMaybeSavingOnClose())
            {
                e.Cancel = true;
            }
        }
```
But my window closes before I am will be able to choose an option before closing.

I tried to switch to syncronous handling by blocking on task but this prevent the second window from interactivity.
The other thing I tried is adding `Task` type to OnStandardClosing but this doesn't compile.

**Comment by kekekeks** [comment]
`async void` is essentially
```cs
task.ContinueWith(_ => <rest of you code>);
return;
```

so your OnStandardClosing returns immediately.

You need to cancel the close right away and close the window manually if `CheckMaybeSavingOnClose` returns true

**Comment by xjsolid** [comment]
Any suggestion about this issue?

**Comment by maxkatz6** [comment]
@xjsolid cancel closing, run async task, and close the window manually if needed.

**Comment by cristinathoughtpennies** [comment]
Hello! What do you mean by "close the window manually"? If I attempt to call Close() I will just hit the OnClosing function again and endlessly loop
