### ISSUE TITLE
Using multiple templates in ItemsRepeater.

### ISSUE THREAD

**Issue by igorstefus** [AvaloniaUI/Avalonia#4075]
Currently repeater will not properly recycle elements for items list where items might use more then one template. This is because recycling in the Repeater doesn't seem to employee logic for picking up recycled elements based on template used.

There is workarounds with `ContentControl` that will work but will negate recycling as actual content of the `ContentControl` will not be recycled.

**Comment by grokys** [comment]
Implemented by #4218
