### ISSUE TITLE
Window transparency macOS sharp edges

### ISSUE THREAD

**Issue by JaggerJo** [AvaloniaUI/Avalonia#4085]
Avalonia Nightly - 0.9.999-cibuild0008131-beta
macOS Catalina

(WindowTransparencyLevel.AcrylicBlur)
<img width="452" alt="image" src="https://user-images.githubusercontent.com/13090415/83940804-0a480f00-a7e7-11ea-826b-a3ca5f739900.png">

(WindowTransparencyLevel.Blur)
<img width="390" alt="image" src="https://user-images.githubusercontent.com/13090415/83940846-43807f00-a7e7-11ea-9880-118e1ff2edc6.png">

(WindowTransparencyLevel.Transparent)
<img width="390" alt="image" src="https://user-images.githubusercontent.com/13090415/83940903-7aef2b80-a7e7-11ea-8dde-9ec9152c6eb6.png">

(WindowTransparencyLevel.None)
<img width="390" alt="image" src="https://user-images.githubusercontent.com/13090415/83940942-a4a85280-a7e7-11ea-95b5-2cf8a2384e0e.png">

**Comment by kekekeks** [comment]
This should be fixed for ages by now
