### ISSUE TITLE
sluggish resize on macOS

### ISSUE THREAD

**Issue by JaggerJo** [AvaloniaUI/Avalonia#4088]
Avalonia 0.9.999-cibuild0008170-beta
macOS Catalina

Resizing a window on macOS is sluggish / laggy. This is even true if the window only contains a single Button.

```fsharp
type MainWindow() =
    inherit Window()
    do
        base.Title <- "Sluggish resize example"
        base.Height <- 400.0
        base.Width <- 400.0
        
        base.Content <- Button ()
        
type App() =
    inherit Application()

    override this.Initialize() =
        this.Styles.Load "resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"
        this.Styles.Load "resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default"

    override this.OnFrameworkInitializationCompleted() =
        match this.ApplicationLifetime with
        | :? IClassicDesktopStyleApplicationLifetime as desktopLifetime ->
            let mainWindow = MainWindow()
            desktopLifetime.MainWindow <- mainWindow
        | _ -> ()

module Program =

    [<EntryPoint>]
    let main(args: string[]) =
        AppBuilder
            .Configure<App>()
            .UsePlatformDetect()
            .UseSkia()
            .StartWithClassicDesktopLifetime(args)
```

**Comment by danwalmsley** [comment]
@JaggerJo sounds like you probably have software rendering, are you using real hardware? or vm?

**Comment by JaggerJo** [comment]
@danwalmsley real hardware. interesting, is software rendering the default ?

**Comment by danwalmsley** [comment]
it shouldnt be, do you have a minimal repro?

**Comment by JaggerJo** [comment]
@danwalmsley the code above is all that I used. (wanted to make sure its not funcUI)

**Comment by danwalmsley** [comment]
Im not an fsharper, if you post me a cs version ill run it here.

**Comment by JaggerJo** [comment]
sure

```csharp
using System;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Markup.Xaml.Styling;

namespace ConsoleApp1
{

    class MainWindow : Window
    {
        public MainWindow ()
        {
            Title = "Sluggish resize example";
            Width = 400.0;
            Height = 400.0;
            Content = new Button();
        }
    }

    class App : Application
    {
        public override void Initialize()
        {
            var styleA = new StyleInclude(baseUri: null);
            styleA.Source = new Uri("resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default");
            Styles.Add (styleA);
            
            var styleB = new StyleInclude(baseUri: null);
            styleB.Source = new Uri("resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default");
            Styles.Add (styleB);
        }

        public override void OnFrameworkInitializationCompleted()
        {
            if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktopLifetime)
            {
                var mainWindow = new MainWindow();
                desktopLifetime.MainWindow = mainWindow;
            }
        }
    }
    
    class Program
    {
        static void Main(string[] args)
        {
            AppBuilder
                .Configure<App>()
                .UsePlatformDetect()
                .UseSkia()
                .StartWithClassicDesktopLifetime(args);
        }
    }
```

**Comment by danwalmsley** [comment]
Reproed here... thanks

**Comment by Zayd-McArdle** [comment]
I have a similar issue when using Avalonia on Manjaro

> Avalonia 0.9.999-cibuild0008170-beta macOS Catalina
> 
> Resizing a window on macOS is sluggish / laggy. This is even true if the window only contains a single Button.
> 
> ```fsharp
> type MainWindow() =
>     inherit Window()
>     do
>         base.Title <- "Sluggish resize example"
>         base.Height <- 400.0
>         base.Width <- 400.0
>         
>         base.Content <- Button ()
>         
> type App() =
>     inherit Application()
> 
>     override this.Initialize() =
>         this.Styles.Load "resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"
>         this.Styles.Load "resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default"
> 
>     override this.OnFrameworkInitializationCompleted() =
>         match this.ApplicationLifetime with
>         | :? IClassicDesktopStyleApplicationLifetime as desktopLifetime ->
>             let mainWindow = MainWindow()
>             desktopLifetime.MainWindow <- mainWindow
>         | _ -> ()
> 
> module Program =
> 
>     [<EntryPoint>]
>     let main(args: string[]) =
>         AppBuilder
>             .Configure<App>()
>             .UsePlatformDetect()
>             .UseSkia()
>             .StartWithClassicDesktopLifetime(args)
> ```

**Comment by maxkatz6** [comment]
@Zayd-McArdle hi! Can you open a new issue with more details and your Avalonia version?

I am going to close this now, as macOS backend was greatly improved since then.
