### ISSUE TITLE
UI controls / grid not scaling with window size on Linux.

### ISSUE THREAD

**Issue by BrandonEugeneWalker** [AvaloniaUI/Avalonia#4089]
Hello!

I recently started working on a project using Avalonia and I've run into a issue I can't seem to figure out.

No mater what size the window is, the elements of the user interface are positioned in the same place with the same size.

I did not define a width or height to the grid used for aligning controls. I have tried assigning the width and height "auto" and "*" and neither of these worked either.

I also tried configuring various min/set/max sizes for the width and height for the window. The window size would change but not the grid or its contents.

Here is a screenshot of the program running:
![Screenshot from 2020-06-07 11-35-33](https://user-images.githubusercontent.com/36686151/83973558-3b8f1080-a8b5-11ea-83dd-64229a684a5e.png)

And here is a link to the XAML file on GitHub:
https://github.com/BrandonEugeneWalker/Click-d-Core/blob/master/ClickdCore/Views/MainWindow.xaml

I'm not sure if this is an issue with Avalonia on Linux or if it is an issue with the XAML code so I thought I would ask here.

Edit:
Pop!_OS 20.04
.netcore3.1
Avalonia 0.9.9

**Comment by Gillibald** [comment]
`Width="Auto" ` means the column is measured with minimal required space. It is not taking available space. Use `Width="*" ` to measure against available space and allow the control to take all that space.

**Comment by BrandonEugeneWalker** [comment]
> `Width="Auto" ` means the column is measured with minimal required space. It is not taking available space. Use `Width="*" ` to measure against available space and allow the control to take all that space.

Thanks for the tip! I had not thought to try * on the definitions.

I tried that out and the result was the same, any other suggestions? I do appreciate it.

**Comment by Gillibald** [comment]
You are using `HorizontalAlignment="Left"` on your controls instead of `Stretch`. So again everything gets measured against minimal required space and isn't taking available space.

**Comment by BrandonEugeneWalker** [comment]
> You are using `HorizontalAlignment="Left"` on your controls instead of `Stretch`. So again everything gets measured against minimal required space and isn't taking available space.

Swapping centered for stretch on the grid fixed the issue, thanks!

**Comment by BrandonEugeneWalker** [comment]
Spoke too soon, the issue was fixed on my Windows VM but not on the Linux machine.

**Comment by BrandonEugeneWalker** [comment]
Here is a screenshot of the Windows VM results:
![Screenshot from 2020-06-07 17-17-12](https://user-images.githubusercontent.com/36686151/83980361-0b5e6680-a8e3-11ea-91c6-545c9b859670.png)

The appearance on the Linux machine is the same as the original screenshot. Clean and rebuild changed nothing.
