### ISSUE TITLE
datagrid master-detail

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#4094]
I still feel a bit inseparable from the control style of windows.

Is there an implementation of DataGrid master-slave table:
![image](https://user-images.githubusercontent.com/13539621/84172262-64c6c100-aaae-11ea-9e15-11807487267f.png)

Is there an implementation of property configuration control:
![image](https://user-images.githubusercontent.com/13539621/84169344-1c59d400-aaab-11ea-9a58-7f968d464e00.png)

**Comment by maxkatz6** [comment]
This feature exists in Windows Community Toolkit, so it should be easier to implement this in Avalonia with same API, since they are both based on Silverlight one.

**Comment by maxkatz6** [comment]
It is possible now to use RowDetailsTemplate in both Default and Fluent themes.
