### ISSUE TITLE
OpenGL Rendering Support

### ISSUE THREAD

**Issue by ilexp** [AvaloniaUI/Avalonia#412]
This is half an issue and half an inquiry.

I'm working on the [Duality](https://github.com/AdamsLair/duality) project and am evaluating different cross-platform UI frameworks to replace WinForms in the long-term future. So par, Perspex is one of my favorites. There are, however, some requirements for my project for which I will need to assure Perspex support:

- A versatile **Docking Control**, including multi window pop-out and drop-in functionality. So far, I'm using [DockPanelSuite](https://github.com/dockpanelsuite/dockpanelsuite) for WinForms. Is there something comparable planned in Perspex?
- **High-DPI Awareness** is something that I currently do not have with WinForms, but intend to support in the long term future. Issue #70 already deals with this, so let's skip that.
- An **OpenGL Rendering Widget** would be by far the most important requirement, so a game scene can be rendered interactively inside a Perspex widget. Issue #6 deals with this, #61 and #18 seem to be somewhat related.
- Also, **Embedding Perspex in OpenGL** would be a big bonus, so I could use Perspex as an ingame UI in addition to using it as the editor's UI system. Issue #216 is related to this.

Given the above list, how likely or doable are each of these points and what's your prediction on future Perspex development with regard to them?

**Comment by ImaBrokeDude** [comment]
Hi Adam! I am not one of the main developers but I am currently working on the docking system that Perspex may use. If it is not used in the core, it will be available as a seperate control library.

**Comment by grokys** [comment]
Hi ilexp,

- Docking - this is not in my plans and I'd expect it to be a community solution. As @ImaBrokeDude mentioned, he's working on something that might be of use.
- DPI Awareness - there is an implementation on the `dpi-aware` branch that needs testing. Please check it out and let me know of any problems!
- OpenGL Suport. I'm not entirely sure what will be needed for this as I have no experience in OpenGL, there are different avenues open to investigation. If it's something you'd be interested in persuing, please let me know.

**Comment by ilexp** [comment]
Thanks for your quick reply.

As far as OpenGL widget support goes, I would imagine that there are two ways to achieve this:

- Asking the operating system for a window handle / equivalent and sync this window with the embedding Perspex widget. This might be enough for third-party libraries to initialize an OpenGL context and render to the native window / area. I'm not sure whether this will have any unwanted interactions with a Perspex Direct2D / DirectX backend though.
- Implementing an OpenGL backend for Perspex, so an OpenGL widget would essentially just be a layouted viewport where user applications can render into.

I am by no means an expert on this though and unfortunately, I don't have the resources to implement an OpenGL backend for Perspex myself at this point - so I'd just leave this open for discussion. Could imagine others being interested in this as well.

**Comment by kekekeks** [comment]
>Also, Embedding Perspex in OpenGL would be a big bonus, so I could use Perspex as an ingame UI in addition to using it as the editor's UI system. Issue #216 is related to this.

Skia backend is using OpenGL for rendering, you just need to somehow pass `FBO` and `glGetProcAddress`. Currenty we are rendering using [EGL](https://github.com/Perspex/libperspesk/blob/master/src/gl.cpp) and [GLKView](https://github.com/Perspex/libperspesk/blob/master/src/pview.mm). Help in sorting out this stuff to support GLX and AGLX will be appreciated.


OpenGL widget is another thing. Writing OpenGL bindings is definitely not our job, so we need to implement native widget embedding support and write some glue code to get OpenTK compatibility.

**Comment by ilexp** [comment]
> OpenGL widget is another thing. Writing OpenGL bindings is definitely not our job, so we need to implement native widget embedding support and write some glue code to get OpenTK compatibility.

Yep, that's exactly what I was thinking about! No need to reinvent the wheel with C# GL bindings, OpenTK can do the job just fine. Also, native widget embedding support sounds like it could in theory be used for other cases as well - if someone wanted a SharpDX widget, for example.

> Skia backend is using OpenGL for rendering, you just need to somehow pass FBO and glGetProcAddress.

Is an external library like Skia really required for this? Couldn't I just implement a backend that hooks up Perspex with OpenGL directly - without an unmanaged library inbetween?

**Comment by grokys** [comment]
> Is an external library like Skia really required for this? Couldn't I just implement a backend that hooks up Perspex with OpenGL directly - without an unmanaged library inbetween?

How would you handle drawing e.g. paths in that scenario?

**Comment by ilexp** [comment]
> How would you handle drawing e.g. paths and text in that scenario?

In my experience, 95% of UIs is just textured boxes with a few basic shapes in addition. Even text can be brought down to textured boxes when pre-rendering the required glyphs. Is complex vector graphics really required for the average UI?

If so, then this could be problematic. Otherwise, it shouldn't be too hard to write some high level drawing methods to generate vertices for OpenGL to submit.

**Comment by ImaBrokeDude** [comment]
Well it isn't just simply a UI framework, I'm sure we want rhe powerful graphics capabilities that WPF but refreshed and modern.

**Comment by ImaBrokeDude** [comment]
I use path more often lately as well as some of the more advanced rendering classes and system to achieve some sexy UIs, some of which are in 3D mode when working with WPF, I would think we could try for the same support or better in Perspex

**Comment by kekekeks** [comment]
>>Is an external library like Skia really required for this? Couldn't I just implement a backend that hooks up Perspex with OpenGL directly - without an unmanaged library inbetween?

Good luck with implementing path support, complex brushes, proper font atlases, etc. 

>Is complex vector graphics really required for the average UI?

We aren't developing a lib for "average UI". We are developing a better WPF with xplat support.

**Comment by ilexp** [comment]
> some of which are in 3D mode when working with WPF, I would think we could try for the same support or better in Perspex

3D mode is totally fine with raw OpenGL though.

> Good luck with implementing path support, complex brushes, proper font atlases, etc.

> We aren't developing a lib for "average UI". We are developing a better WPF with xplat support.

"Average" as I wrote it wasn't meant as a negative trait, or a description of quality, but rather as an observation of what a UI usually needs or does. 

When I look through all the tools and programs I use, I rarely spot any of the complex drawing operations that a full scale vector rendering library provides and personally, I don't think I need much more than textured boxes and a few simple shapes here and there to create a decent UI. But at the same time, a complete vector rendering framework has a certain overhead, and I usually try to reduce that as much as possible.

> Well it isn't just simply a UI framework, I'm sure we want rhe powerful graphics capabilities that WPF but refreshed and modern.

Allright then - but let's assume I don't care about powerful graphics, because the simple stuff is enough for my needs, and I want to keep it that way, but still use Perspex, because it looks really neat otherwise:

In theory, would it be possible to implement an OpenGL backend for Perspex with just the minimal basics? Say I don't need complex brushes or path support, could I just leave them out? Would that work as long as no Perspex widget I use needs them?

**Comment by kekekeks** [comment]
>Would that work as long as no Perspex widget I use needs them?

Well, even simple stuff like checkboxes uses paths, so you need to implement your own theme that avoids using paths at all. Then you can just stub path-related methods in your backend.

**Comment by ilexp** [comment]
> Well, even simple stuff like checkboxes uses paths, so you need to implement your own theme that avoids using paths at all. Then you can just stub path-related methods in your backend.

Hm, that makes sense, yes. Thanks! Especially the part with the theme abstraction to have central control over how things look like sounds awesome :)

Anyway, let's wrap the original questions up a bit:

- A versatile **Docking Control**: 
  - Community-driven solution, @ImaBrokeDude working on one of them
- **High-DPI Awareness**: 
  - Ready for testing in the `dpi-aware` branch, awaiting feedback.
- An **OpenGL Rendering Widget**: 
  - Can be generalized as an embedded native widget, which users could then use to insert their custom OpenGL, DirectX or something-else widget. Not implemented yet, probably needs investigation.
- **Embedding Perspex in OpenGL**: 
  - Theoretically possible with the Skia backend, investigation of the details pending. "Raw OpenGL" backend possible when doing without complex vector rendering - or implementing the required parts.

**Comment by ImaBrokeDude** [comment]
>In theory, would it be possible to implement an OpenGL backend for Perspex with just the minimal basics? Say I don't need complex brushes or path support, could I just leave them out? Would that work as long as no Perspex widget I use needs them?

Depends on how the UI is built I guess, I dont think because iirc, text is rendered through paths (Though that may have only been the case when I did the initial attempt at Perspex for Android.)

**Comment by ilexp** [comment]
> I think as a developer doing UI design, wouldn't Paths do better than your approach? They are resolution agnostic and highly scaleable.

It really depends on the purpose and context of your UI and while paths do have their advantages, sometimes a textured rect or 9-patch is more straight-forward. 

Anyway - I think going deeper into the details of this doesn't really add much to the issue at hand and my point is really not about whether paths are good or bad. Having complex vector graphics is awesome, but when it comes with a certain overhead it's a reason for me to evaluate the positive impact it really has for the typical use cases that I need - and whether I can do without.

**Comment by amerkoleci** [comment]
About embedding, I have huge experience of OpenGL, DirectX11 and DirectX12 too, will take look and try to embed by game engine into Perspex based editor.
@ImaBrokeDude Can you commit somewhere your WIP docking library? So I can try it and help if possible.

**Comment by ImaBrokeDude** [comment]
@amerkoleci , sorry about that, its in the docking branch in VitalElement/AvalonStudio
