### ISSUE TITLE
Make it easier to apply a style to a Window?

### ISSUE THREAD

**Issue by Eladretep** [AvaloniaUI/Avalonia#4131]
Pull request #2374 for issue #2280 made it easier to apply a style to a UserControl. 

Is it worth making the same changes for Window?

It's easy to work around once you know what it is, but it took a while to figure out why the selector for my Window wasn't working and why behaviour was different between a UserControl and a Window.

Would there be a downside to changing the selector to `:is(Window)` and removing the style key?

**Comment by danwalmsley** [comment]
@Eladretep if this is to make custom window chrome, we have new apis coming up...

https://github.com/AvaloniaUI/Avalonia/pull/3967

which allow your app to render right into the client area...
