### ISSUE TITLE
Fluent Light CheckBox is invisible

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#4139]
When unchecked the Fluent Light CheckBox shows nothing
![image](https://user-images.githubusercontent.com/1388864/84947561-4ed68300-b0e2-11ea-878e-3660d6fa7b27.png)

**Comment by JamRemco** [comment]
yeah saw that to today

**Comment by danwalmsley** [comment]
fixed on master, thanks.
