### ISSUE TITLE
Unable to find suitable setter or adder for property XYZ

### ISSUE THREAD

**Issue by marriskleinert** [AvaloniaUI/Avalonia#4142]
Hi :)
The avalonia controls's error behaviour is somehow very unexpectable in my case.
Whenever I add something to the MainWindow.xaml, there are some errors.
Errors like this:

> Unable to find suitable setter or adder for property Command of type Avalonia.Controls:Avalonia.Controls.Button for argument System.Runtime:System.String, available setter parameter lists are:
> Avalonia.UnsetValueType
> Avalonia.Data.IBinding
> System.Windows.Input.ICommand (line 88 position 21) Line 88, position 21. XXX\Views\MainWindow.xaml

The code:

`<TabItem>
          <TabItem.Header>
            <TextBlock VerticalAlignment="Center">History</TextBlock>
          </TabItem.Header>
          <StackPanel>
            <Button Command="RefreshHistory">Reload from database</Button>
            <controls1:DataGrid AutoGenerateColumns="True">
              <controls1:DataGrid.Items>
                <data:Binding Path="JobHistory" />
              </controls1:DataGrid.Items>
            </controls1:DataGrid>
          </StackPanel>
        </TabItem>`

I work with:
- Avalonia v0.9.10
- Avalonia.Controls.DataGrid v0.9.10
- Avalonia.Desktop v0.9.10
- Avalonia.ReactiveUI v0.9.10

Maybe related to #3145

**Comment by kekekeks** [comment]
There is no conversion between `string` and `ICommand`, yes

**Comment by marriskleinert** [comment]
That's true, but the "RefreshHistory" is a ReactiveCommand in the ViewModel.

**Comment by marriskleinert** [comment]
Nevermind I know what was wrong ^^
Stupid mistake

**Comment by SCLDGit** [comment]
What ended up being the solution?

**Comment by maxkatz6** [comment]
@SCLDGit problem in user code
