### ISSUE TITLE
Splash Window - Update isnt propagated to GUI

### ISSUE THREAD

**Issue by henryBTR** [AvaloniaUI/Avalonia#4155]
Hello, im trying to use your example:

        private static void OnStart(object sender, EventArgs e)
        {
            if (sender is IClassicDesktopStyleApplicationLifetime desktop)
            {
                async void AppAsyncLoadingStart()
                {
                    await Task.Delay(10);
                    var splashViewModel = new SplashWindowViewModel();
                    splashViewModel.StartupProgressText = "Loading...";
                    var splash = new SplashWindow { DataContext = splashViewModel };
                    splash.Show();

                    await Task.Delay(10);
                    splashViewModel.StartupProgressText = "Updated loading...";

                    desktop.MainWindow = await GetAppLoadingAsync(splashViewModel);
                    desktop.MainWindow.Show();
                    desktop.MainWindow.Activate();

                    await Task.Delay(10000);
                    splash.Close();
                }

                AppAsyncLoadingStart();
            }
        }

But problem is that after second await operation is splashViewModel.StartupProgressText = "Updated loading..."; ignored and it isnt propagated to GUI SpashWindow TextBlock. There is still possible to see  "Loading..." only. What is wrong please?

Your example:
Window needs a running main loop to function properly. You can use a custom cancellation token for `app.Run` and do the rest of initialization like this:
```cs
private static void AppMain(Application app, string[] args)
{
  var stop = new CancellationTokenSource();

  async void Start()
  {
      await Task.Delay(10);
      var splashViewModel = new SplashViewModel();
      var splash = new SplashWindow {DataContext = splashViewModel};
      splash.Show();
      app.MainWindow = await GetMainWindowAsync(splashViewModel);
      app.MainWindow.Closed += (_, __) => stop.Cancel();
      app.MainWindow.Show();
      app.MainWindow.Activate();
      splash.Close();
  }
  Start();
  app.Run(stop.Token);
}

static async Task<MainWindow> GetMainWindowAsync(SplashViewModel splashViewModel)
{
     // Initialize here
     return new MainWindow();
}
```

_Originally posted by @kekekeks in https://github.com/AvaloniaUI/Avalonia/issues/2674#issuecomment-504494428_

**Comment by henryBTR** [comment]
When you open devtool - and move with mouse in logical three to out textblock then textblock is rerendered and is correct. Looks like some bug with bindings... version 0.9.10.

**Comment by kekekeks** [comment]
You are probably missing INotifyPropertyChanged implementation in your view model.

**Comment by henryBTR** [comment]
No i have there:    

public class ViewModelBase : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected bool SetProperty<T>(ref T field, T newValue, [CallerMemberName]string propertyName = null)
        {
            if (!EqualityComparer<T>.Default.Equals(field, newValue))
            {
                field = newValue;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
                return true;
            }
            return false;
        }
    }
	
	public class SplashWindowViewModel : ViewModelBase
    {
        private string _startupProgressText;

        public string StartupProgressText
        {
            get => _startupProgressText;
            set => SetProperty(ref _startupProgressText, value);
        }

        public void ChangeText(object text)
        {
            StartupProgressText = (string)text;
        }

        public SplashWindowViewModel()
        {

        }
    }

**Comment by kekekeks** [comment]
Try adding `await Task.Delay(100)` after `splashViewModel.StartupProgressText = "Updated loading...";`. Your code might be blocking the UI thread.

**Comment by henryBTR** [comment]
It doesnt help. After 
splash.Show();

first await Task.Delay(10); will help to show window 
splashViewModel.StartupProgressText = "Updated loading...";
but next await Task.Delay(1000);
doesnt help. There is still the same text "Loading..."

It looks that first await Task.Delay(10); after show is killing binding to window gui.

After load is finished... there is still text "Loading..." but viewModel contain correct information "Updated loading...";

Or is there a way how to force Redraw object or Window?

**Comment by henryBTR** [comment]
XAML of window:

<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="clr-namespace:App.ViewModels;assembly=FreeMarketApp"
        x:Class="FreeMarketApp.Views.SplashWindow"
        Title="Loading MyApp" Width="300" Height="300"
        WindowStartupLocation="CenterScreen" HasSystemDecorations="False" CanResize="False" Topmost="True">

    <Design.DataContext>
        <vm:SplashWindowViewModel/>
    </Design.DataContext>
    
    <Grid ColumnDefinitions="*" RowDefinitions="250,*">
        <Image Source="resm:App.Assets.splash.png" Grid.Row="0" Stretch="None" />
        <TextBlock Name='button' TextAlignment="Center" Grid.Row="1" Text="{Binding StartupProgressText, Mode=TwoWay }"/>
    </Grid>

</Window>

**Comment by Shadow4walker** [comment]
> XAML of window:
> 
> ```
> <Window xmlns="https://github.com/avaloniaui"
>         xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>         xmlns:vm="clr-namespace:App.ViewModels;assembly=FreeMarketApp"
>         x:Class="App.Views.SplashWindow"
>         Title="Loading MyApp" Width="300" Height="300"
>         WindowStartupLocation="CenterScreen" HasSystemDecorations="False" CanResize="False" Topmost="True">
> 
>     <Design.DataContext>
>         <vm:SplashWindowViewModel/>
>     </Design.DataContext>
>     
>     <Grid ColumnDefinitions="*" RowDefinitions="250,*">
>         <Image Source="resm:App.Assets.splash.png" Grid.Row="0" Stretch="None" />
>         <TextBlock Name='button' TextAlignment="Center" Grid.Row="1" Text="{Binding StartupProgressText, Mode=TwoWay }"/>
>     </Grid>
> 
> </Window>
> ```

just remove |TextAlignment="Center"| or add |VerticalAlignment="Top"| before it  
like so

> 
	<Grid ColumnDefinitions="*" RowDefinitions="250,*">
		<Image Source="/Assets/avalonia-logo.ico" Grid.Row="0" Stretch="None" />
		<TextBlock Name='button' Grid.Row="1" Text="{Binding StartupProgressText, Mode=TwoWay }" VerticalAlignment="Top" TextAlignment="Center"/>
	</Grid>

**Comment by henryBTR** [comment]
Yes with this change .. it works ok on Windows. 👍 Great!

**Comment by llfab** [comment]
See here here for a sample app: https://github.com/AvaloniaUI/Avalonia/discussions/11083
