### ISSUE TITLE
gis

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#4169]
Is there any map control that can be used in combination, which can support 3D map？

**Comment by kekekeks** [comment]
No ready-to use controls that we know of. 3D will require the upcoming GL control support. Once it's released it should be possible to integrate something like https://github.com/tangrams/tangram-es

**Comment by jinyuttt** [comment]
thank you.

I have verified that Avalonia can be used in our project; it's just that there is no upgraded 3D map, but it doesn't affect our project. 2-D map is enough; I'm looking forward to someone encapsulating the combination of ArcGIS and Avalonia.

Does Avalonia's incorporation mean that Avalonia will change open source or slow update?

Looking forward to Avalonia version 1.0, I feel that the interface of earlier versions is still changing.
