### ISSUE TITLE
Managed System Dialog crash with System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by AidarGiza** [AvaloniaUI/Avalonia#4171]
Program crashes when I attemp to show OpenFileDialog or SaveFileDialog.

`var dialog = new SaveFileDialog();`
`dialog.ShowAsync(UserControl as MainWindow);`

Here's StackTrace:
----------------------------
System.UnauthorizedAccessException: 'Access to the path 'Y:\' is denied.'

    System.IO.DriveInfo.VolumeLabel.get()
    Avalonia.Win32.WindowsMountedVolumeInfoListener.Poll.AnonymousMethod__4_1(System.IO.DriveInfo)
    System.Linq.Enumerable.WhereSelectArrayIterator<TSource, TResult>.ToArray()
    System.Linq.Enumerable.ToArray<TSource>(System.Collections.Generic.IEnumerable<TSource>)
    Avalonia.Win32.WindowsMountedVolumeInfoListener.Poll(long)
    System.Reactive.AnonymousSafeObserver<T>.OnNext(T) in AnonymousSafeObserver.cs
    System.Reactive.Sink<TTarget>.ForwardOnNext(TTarget) in Sink.cs
    System.Reactive.Linq.ObservableImpl.Timer.Periodic._.Tick() in Timer.cs
    System.Reactive.Linq.ObservableImpl.Timer.Periodic._.Run.AnonymousMethod__4_0(System.Reactive.Linq.ObservableImpl.Timer.Periodic._) in Timer.cs
    System.Reactive.Concurrency.Scheduler.SchedulePeriodic.AnonymousMethod__67_0((TState state, System.Action<TState> action)) in Scheduler.Services.Emulation.cs
    ...
    [Call Stack Truncated]
----------------------------

**Comment by jmacato** [comment]
nothing that a simple try/catch can't fix :) will post PR later
