### ISSUE TITLE
Tmds.DBus.DBusException

### ISSUE THREAD

**Issue by cbaal83** [AvaloniaUI/Avalonia#4175]
Hi there,

iam very new to this lib, running on

> Linux IR1581 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

> Distributor ID:	LinuxMint
> Description:	Linux Mint 19.3 Tricia
> Release:	19.3
> Codename:	tricia

dotnet --version gave me:

> 3.1.101

I've followed thoose [instructions](https://github.com/AvaloniaUI/Avalonia/wiki/Build-Avalonia-from-Source). In order to get it working i had to add 2 more things:

> curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
> sudo apt-get install -y nodejs

and:

> sudo apt-get install castxml

Once this build was running, i tried to run "ControlCatalog.NetCore", which killed my Cinnamon Session (fallback) and threw the following exception:

> Tmds.DBus.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.AppMenu.Registrar was not provided by any .service files
>    at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
>    at Tmds.DBus.Connection.CallMethodAsync(Message message)
>    at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
>    at Avalonia.FreeDesktop.DBusMenuExporter.DBusMenuExporterImpl.Init() in /daten/dev/csharp/github/Avalonia/src/Avalonia.FreeDesktop/DBusMenuExporter.cs:line 59

I did'nt want to build Avalonia in the first place, but the current nuget-release also doesn't work for me, throwing the following exception:

> [Visual] Exception in render loop: "System.InvalidOperationException: Failed to create Skia render target surface
>    at Avalonia.Skia.SurfaceRenderTarget..ctor(CreateInfo createInfo)
>    at Avalonia.Skia.DrawingContextImpl.CreateRenderTarget(Size size, Nullable`1 format)
>    at Avalonia.Skia.DrawingContextImpl.CreateLayer(Size size)
>    at Avalonia.Rendering.RenderLayers.Update(Scene scene, IDrawingContextImpl context)
>    at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall)
>    at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite)
>    at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time)" (Avalonia.Rendering.RenderLoop #4032828)

Hope you guys can help me a bit.

Thank you!

**Comment by kekekeks** [comment]
>`Tmds.DBus.DBusException`

You can ignore that, it means that your DE doesn't support dbusmenu protocol and the app will fall back to in-window menu.

> current nuget-release also doesn't work for me

Which version are you using?

**Comment by cbaal83** [comment]
Hi,
version is: 0.9.9.

**Comment by cbaal83** [comment]
I just figured there is a new version "0.9.10"; same issue.

**Comment by kekekeks** [comment]
>which killed my Cinnamon Session (fallback) and threw the following exception

You can try removing this line - https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog.NetCore/Program.cs#L61 but I don't think that a missing DBus service is capable of killing the entire session.

Also, show your `glxinfo` output.

**Comment by cbaal83** [comment]
glxinfo: https://pastebin.com/Pi266zuK

Removing the line didn't help either.

**Comment by kekekeks** [comment]
Does it crash the entire X server or just the window manager? Are there any window-manager related logs?

**Comment by cbaal83** [comment]
Only the window manager is crashing, i will try to find some logs.

**Comment by cbaal83** [comment]
https://pastebin.com/8S3sL55i that's at least something...

could this:

>  ControlCatalog.NetCore: [Binding] Error in binding to 'Avalonia.Controls.NativeMenuItem'.'Command': 'Null value in expression ''.' (NativeMenuItem #5894079)

be the reason?

**Comment by kekekeks** [comment]
That's a binding error that can also be ignored. There is still
> Jun 26 13:14:48 IR1581 ControlCatalog.NetCore: [Visual] Exception in render loop: 'System.InvalidOperationException: Failed to create Skia render target surface#012   at Avalonia.Skia.SurfaceRenderTarget..ctor(CreateInfo createInfo) in /daten/dev/csharp/github/Avalonia/src/Skia/Avalonia.Skia/SurfaceRenderTarget.cs:line 

though. Which is probably caused by 0x0 window size or something like that.


Can't reproduce `metacity` crash with `metacity` from Ubuntu 18.04, might be worth reporting that bug to your distro metacity maintainers.

**Comment by xiangzhai** [comment]
:mips-interest
