### ISSUE TITLE
Offline development

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#4185]
In the absence of network environment, there are many exceptions. All DLLs in normal operation are introduced, and XAML load is still wrong exception:no precompiled xaml found ....

It is suggested to give an example and guide for the development of offline network-free environment

**Comment by kekekeks** [comment]
You need to have all of the required packages in your local nuget cache (either local in %USERPROFILE%\.nuget or on designated nuget cache server). Other than that there are no network requirements.

**Comment by jinyuttt** [comment]
@kekekeks I set up a local nuget server, but found that all downloaded Avalonia libraries and dependent libraries can't be uploaded. Other libraries can. An error of 406 (not acceptable) is reported. What is the reason?

**Comment by kekekeks** [comment]
> An error of 406 (not acceptable) is reported. What is the reason?

That depends entirely on your nuget server. We are using Sonatype Nexus and it accepts libraries without any issues.

There was, however, a fix for `[Content_Types].xml` generation that landed in 0.9.11, might be worth a try.

**Comment by jinyuttt** [comment]
ok, thanks.
