### ISSUE TITLE
Menu mnemonic should ignore right Alt key

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#4186]
Right alt key is used on some locale to input special characters e.g. ęźćńó (Polish Language)

**Comment by MarchingCube** [comment]
I wonder about this, I use 3 layouts (Polish, German, English) and when using English one I can actually use mnemonics using right alt key. If one can use notepad.exe as an example - it is disabled when using right alt (AltGr) on both German and Polish layouts though. Perhaps one can tell if currently active layout is utilizing right alt somehow.

Do you know how WPF is handling it? I see that VS at least is reacting to right alt all the time.

**Comment by wieslawsoltes** [comment]
I don't mind the menu mnemonic showing up on Right Alt key, just that it prevents text input.

So fat did quick search is WPF code base, did not find any special handling for right alt key, will test WPF later.

https://github.com/dotnet/wpf/blob/ac9d1b7a6b0ee7c44fd2875a1174b820b3940619/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/MenuBase.cs#L470

https://github.com/dotnet/wpf/blob/ac9d1b7a6b0ee7c44fd2875a1174b820b3940619/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Menu.cs#L331

https://github.com/dotnet/wpf/blob/ac9d1b7a6b0ee7c44fd2875a1174b820b3940619/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Input/KeyboardNavigation.cs#L3293
