### ISSUE TITLE
InvalidateVisual() and AffectsRender don't invoke render method

### ISSUE THREAD

**Issue by aaechoman** [AvaloniaUI/Avalonia#4197]
```
private double _subcycleSize = 20;
public double SubcycleSize {
    get => _subcycleSize;
    set => SetAndRaise(SubcycleSizeProperty, ref _subcycleSize, value);
}
public static readonly DirectProperty<TimelineGrid, double> SubcycleSizeProperty = AvaloniaProperty.RegisterDirect<TimelineGrid, double>(nameof(SubcycleSize), o => o.SubcycleSize, (o, v) => o.SubcycleSize = v);
public override void Render(DrawingContext context)
{
    //... my render codes
    base.Render(context);
}
static TimelineGrid()
{
        AffectsRender<TimelineGrid>(..., SubcycleSizeProperty, ...);
}

protected override Size ArrangeOverride(Size finalSize)
{
    double width = CycleCount * SubcycleCountPerCycleCount * SubcycleSize;
    double height = 10 * SubcycleSize;

    Width = width;
    Height = height;
    finalSize = new Size(width, height);
    return finalSize;
}

public void StepSizeGrid(double delta)
{
    // .... codes
    SubcycleSize = subcycleSize;
}

```

I can catch property change on OnPropertyChanged but not invoke render. On window resize invoke render method but no changes with changed SubcycleSize. Drawing not refresh. I dont understande and please, help me.

Five lines will be drawn for each second, and an average length of 5 minutes will be a timeline.

![1](https://user-images.githubusercontent.com/52584713/86049882-9acae580-ba5b-11ea-846c-b5211080dd0f.jpg)

**Comment by Aurumaker72** [comment]
Any context on this being closed as completed? I'm encountering a similar issue.

**Comment by timunie** [comment]
@Aurumaker72 if your issue is happening in v11, please open a new issue with a minimal sample to reproduce attached. Answering closed issues will not solve anything.
