### ISSUE TITLE
Optimize Color equality checks #3465 not in Release 0.9.11

### ISSUE THREAD

**Issue by srl17** [AvaloniaUI/Avalonia#4198]
Maybe this is me not understanding how your project puts Pull Requests into the Release branches.

I was going to implement the above change to add color Equality but marchingcube beat me to it earlier this year (pull request was completed in February).  I noticed the code is on the master branch but not on the release 0.9.11 branch.

If the latest releases are not from the current master; what identifies what Pull Requests go into the release branch?

**Comment by maxkatz6** [comment]
Current master branch will be released as 0.10 later this summer.
0.9.11 contains only backported bug fixes.
