### ISSUE TITLE
TextBox and scrolling via PgUp & PgDn

### ISSUE THREAD

**Issue by kiminuo** [AvaloniaUI/Avalonia#4202]
Hi guys,

it seems that TextBox does not handle PgUp & PgDn keyboard strokes 
https://github.com/AvaloniaUI/Avalonia/blob/cda455edfdc6ec684d0f7f1419e77ab225d24e94/src/Avalonia.Controls/TextBox.cs#L514 

Am I correct?
Cheers

**Comment by jmacato** [comment]
@kiminuo yes.. unfortunately it doesnt handle pagedown/up right now

**Comment by nicola36631** [comment]
@kekekeks would it be possible to add the labels "area-accessibility", "enhancement", "help-wanted"?
So that this issue is categorized correctly
