### ISSUE TITLE
Starting an app with WindowState=FullScreen causes nothing to be displayed

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#4204]
If the main window of an app has WindowState="FullScreen" set the app starts and runs but nothing is displayed.
Tested on windows with 0.9.999-cibuild0008870-beta

**Comment by comet56us** [comment]
FYI I think this is a duplicate of #4006

**Comment by ahopper** [comment]
this does not happen on a quick test with 0.10.11
