### ISSUE TITLE
Slider keyboard focus wrong and no keyboard interaction

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#4205]
On 0.9.999-cibuild0008870-beta tabbing to a slider takes you to two track buttons that are no longer used.  There is no way to control the slider from the keyboard.

**Comment by grokys** [comment]
Is this the fluent slider style? If so pinging @jmacato

**Comment by ahopper** [comment]
Both default and Fluent as clicking on the track has changed to match uwp behaviour
