### ISSUE TITLE
SelectingItemsControl does not trigger SelectionChanged event when using multiselect

### ISSUE THREAD

**Issue by ShadowDancer** [AvaloniaUI/Avalonia#4208]
SelectionChanged should be triggerd each time new item is selected, currently it is triggered only when SelectedIndex changes.

See [video](https://i.imgur.com/B9QNoVa.mp4)

Repro steps:
- create multiselect listview, add event listener for SelectionChanged
- select items in listview

Actual results:
- selection changed is triggered only when single item is selected

Expected results:
- selection changed is triggered also each time user selects additional items

**Comment by danwalmsley** [comment]
@ShadowDancer selectingitems control you definately can bind to both `SelectedItem` and `SelectedItems` properties. DataGrid is a beast of its own so I wouldnt know about that.

If the event doesnt fire when selection changes then thats definately a bug though.

**Comment by ShadowDancer** [comment]
@danwalmsley this is not related to `DataGrid`, removed that part from description.

**Comment by grokys** [comment]
@ShadowDancer what version is this on?

**Comment by ShadowDancer** [comment]
It was broken on 0.9 branch for sure, I see it works in 0.10-previews, so closing the ticket
