### ISSUE TITLE
Unable to resolve IsNotNullOrEmpty as static field

### ISSUE THREAD

**Issue by 3400442579** [AvaloniaUI/Avalonia#4212]
XAMLIL	Unable to resolve IsNotNullOrEmpty as static field, property, constant or enum value (line 54 position 16) Line 54, position 16. [C:\Users\jxw\Downloads\MessageBox.Avalonia-master\MessageBox.Avalonia-master\src\MessageBox.Avalonia\MessageBox.Avalonia.csproj]	MessageBox.Avalonia	C:\Users\jxw\Downloads\MessageBox.Avalonia-master\MessageBox.Avalonia-master\src\MessageBox.Avalonia\Views\MsBoxCustomWindow.xaml	54	

vs 16.6.0
Avalonia for vs  0.9.10.0

`<Window xmlns="https://github.com/avaloniaui" 
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="150" d:DesignHeight="100"
        x:Class="MessageBox.Avalonia.Views.MsBoxCustomWindow"
        SizeToContent="WidthAndHeight"
        MinWidth="200"
        MaxWidth="{Binding  MaxWidth}"
        WindowStartupLocation="{Binding LocationOfMyWindow}"
        MinHeight="100"
        CanResize="{Binding CanResize}"
        Title="{Binding ContentTitle}">
        
    <Window.KeyBindings>
        <KeyBinding Gesture="Ctrl+C" Command="{Binding Copy}" />
    </Window.KeyBindings>
    <Window.Styles>
        <Style Selector="TextBox">
            <Setter Property="BorderThickness" Value="0" />
            <Setter Property="TextWrapping" Value="Wrap" />
            <Setter Property="AcceptsReturn" Value="True" />
            <Setter Property="IsReadOnly" Value="True" />
            <Setter Property="ScrollViewer.VerticalScrollBarVisibility" Value="Auto" />
            <Setter Property="ScrollViewer.HorizontalScrollBarVisibility" Value="Disabled" />
        </Style>
        <Style Selector="TextBox.header">
            <Setter Property="FontWeight" Value="Bold" />
        </Style>
        <Style Selector="Button">
            <Setter Property="Margin" Value="15 0 0 0" />
            <Setter Property="MinHeight" Value="24" />
            <Setter Property="MinWidth" Value="75" />
        </Style>

    </Window.Styles>
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="15" />
            <ColumnDefinition Width="Auto" />
            <ColumnDefinition Width="15" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="15" />
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="15" />
            <RowDefinition Height="*" />
            <RowDefinition Height="15" />
            <RowDefinition Height="Auto" />
            <RowDefinition Height="15" />
        </Grid.RowDefinitions>
        
        <Image Grid.Row="1" Grid.Column="1" MaxHeight="50" MaxWidth="50" VerticalAlignment="Top"
              IsVisible="{Binding ImagePath, Converter={x:Static ObjectConverters.IsNotNullOrEmpty}}"
               Source="{Binding ImagePath}" />
        <Grid Grid.Row="1" Grid.Column="3">
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition Height="15" />
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>
            
            <TextBlock Grid.Row="0" Classes="header" Text="{Binding ContentHeader}" 
                       IsVisible="{Binding ContentHeader, Converter={x:Static StringConverters.IsNullOrEmpty}}"/>
            
            <TextBlock Grid.Row="2" Text="{Binding ContentMessage}" />
        </Grid>
      
        
        <ItemsPresenter Items="{Binding ButtonDefinitions}" Grid.Row="3" Grid.Column="1" Grid.ColumnSpan="3"
                        HorizontalAlignment="Right">
            <ItemsPresenter.ItemsPanel>
                <ItemsPanelTemplate>
                    <StackPanel Orientation="Horizontal"
                                VerticalAlignment="Center"
                                HorizontalAlignment="Center" />
                </ItemsPanelTemplate>
            </ItemsPresenter.ItemsPanel>
            <ItemsPresenter.ItemTemplate>
                <DataTemplate>
                    <Button Name="Btn" IsDefault="{Binding IsDefault}"
                            Tag="{Binding TypeName}"
                            Command="{Binding DataContext.ButtonClick, RelativeSource={RelativeSource AncestorType=Window, AncestorLevel=1}}"
                            CommandParameter="{Binding #Btn.Content}"
                            Content="{Binding Name}"
                            Margin="0 0 5 0">
                    </Button>
                </DataTemplate>
            </ItemsPresenter.ItemTemplate>
        </ItemsPresenter>
    </Grid>
</Window>
`

**Comment by FoggyFinder** [comment]
@3400442579 There is no build-in `ObjectConverters.IsNotNullOrEmpty` converter. But there is `StringConverters.IsNotNullOrEmpty`:

Try to use 

```xaml
<Image Grid.Row="1" Grid.Column="1" MaxHeight="50" MaxWidth="50" VerticalAlignment="Top"
       IsVisible="{Binding ImagePath, Converter={x:Static StringConverters.IsNotNullOrEmpty}}"
       Source="{Binding ImagePath}" />
```
