### ISSUE TITLE
 local resources

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#4214]
The projects created by Avalonia application and Avalonia MVVM application have different access to local resources (pictures). Avalonia MVVM application can be obtained directly, but Avalonia application can't. what is the reason for this? Is there any document or example explaining this kind of problem.

<ImageBrush Source="/Assets/RibbonIcons/settings.png"/>

**Comment by kekekeks** [comment]
In MVVM template there is a 
```
    <AvaloniaResource Include="Assets\**" />
```
line in the [project file](https://github.com/AvaloniaUI/avalonia-dotnet-templates/blob/126ea97af62cc622c9d58afd4a8932d22a4cd8c5/app-mvvm/AvaloniaAppTemplate.csproj#L14).

**Comment by jinyuttt** [comment]
How do general projects access resources (pictures)？

**Comment by kekekeks** [comment]
You need to include your resources as AvaloniaResource. They'll be accessible through `avares://`  uri schema (or via relative uris like `/Assets/x.png`

**Comment by jinyuttt** [comment]
ok,thanks
