### ISSUE TITLE
How to align content of ComboBox by center?

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#4215]
Unlike different controls `ComboBox` doesn't have `HorizontalContentAlignment` property.

Is there is any replacement for this? If not can it be added then?

**Comment by maxkatz6** [comment]
@FoggyFinder 
You can set it with style 
```xaml
<Style Selector="ComboBox /template/ ContentControl">
   <Setter Property="HorizontalAlignment" Value="Right" />
</Style>
```

**Comment by maxkatz6** [comment]
@grokys @danwalmsley 
WPF and UWP has HorizontalContentAlignment and VerticalContentAlignment for ComboBox.
Should we add it to Avalonia, even thought there is relatively easy way to set it with selector?
I can add it to my Fluent ComboBox PR.

**Comment by FoggyFinder** [comment]
> @FoggyFinder
> You can set it with style
> 
> ```
> <Style Selector="ComboBox /template/ ContentControl">
>    <Setter Property="HorizontalContentAlignment" Value="Right" />
> </Style>
> ```

Thank you, but can you give a full example?
I've added it like this and it doesn't work:

```xml
<ComboBox.Styles>
    <Style Selector="ComboBox /template/ ContentControl">
        <Setter Property="HorizontalContentAlignment" Value="Center" />
    </Style>
</ComboBox.Styles>
```

![_CmbAv](https://user-images.githubusercontent.com/16510738/86292888-3c883900-bbfa-11ea-9555-f7d28a96aa0a.jpg)

**Comment by maxkatz6** [comment]
@FoggyFinder sorry, I missed that default ComboBox style also defines HorizontalAlignment="Left", so HorizontalContentAlignment will not apply any visible changes.
Try code below:
```
<ComboBox Width="200">
  <ComboBox.Styles>
    <Style Selector="ComboBox /template/ ContentControl">
      <Setter Property="HorizontalContentAlignment" Value="Right" />
      <Setter Property="HorizontalAlignment" Value="Stretch" />
    </Style>
  </ComboBox.Styles>
```

Or just add HorizontalAlignment="Stretch" to ComboBox directly.

**Comment by FoggyFinder** [comment]
Still the same: text is pinned to the left. I tried on `0.9.999-cibuild0008887-beta` version.

I'll try to test on `ControlCatalog` in the morning - maybe it is late and I'm missing something obvious.

**Comment by FoggyFinder** [comment]
Uh, for some reason I can't build Avalonia from source anymore.

error cs0006 metadata file could not be found:
`\Avalonia\src\Avalonia.DesktopRuntime\bin\Debug\netcoreapp2.0\Avalonia.DesktopRuntime.dll`
`\Avalonia\packages\Avalonia\bin\Debug\netcoreapp2.0\Avalonia.dll`

```xaml
        <ComboBox Width="200">
            <ComboBox.Styles>
                <Style Selector="ComboBox /template/ ContentControl">
                    <Setter Property="HorizontalContentAlignment" Value="Center" />
                    <Setter Property="HorizontalAlignment" Value="Stretch" />
                </Style>
            </ComboBox.Styles>
            <ComboBoxItem>Inline Items</ComboBoxItem>
            <ComboBoxItem>Inline Item 2</ComboBoxItem>
            <ComboBoxItem>Inline Item 3</ComboBoxItem>
            <ComboBoxItem>Inline Item 4</ComboBoxItem>
        </ComboBox>
```

![_av2](https://user-images.githubusercontent.com/16510738/86337987-7ab54500-bc5a-11ea-9bc0-ff5bb1aa7d3f.jpg)


Doesn't produce correct result, MCVE is attached:

[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/4862981/AvaloniaApplication1.zip)

**Comment by maxkatz6** [comment]
@FoggyFinder it seems like a problem with properties overriding - https://github.com/AvaloniaUI/Avalonia/issues/2098
HorizontalAlignment is defined in the template, so it can't be overridden with style.

I will implement ComboBox.HorizontalContentAlignment to avoid that problem.

For now you can only replace whole ComboBox template with alignment-center.

**Comment by FoggyFinder** [comment]
I'm closing the issue since PR is merged.

**Comment by stepagrus** [comment]
Solution:

```
  <ComboBox HorizontalContentAlignment="Right">
    <ComboBox.Styles>
      <Style Selector="ComboBoxItem">
        <Setter Property="HorizontalContentAlignment" Value="Right"/>
      </Style>
    </ComboBox.Styles>
  </ComboBox>
```

or

```
<Style Selector="ComboBox.rightAligment">
  <Setter Property="HorizontalContentAlignment" Value="Right"/>

  <Style Selector="^ ComboBoxItem">
    <Setter Property="HorizontalContentAlignment" Value="Right"/>
  </Style>
</Style>
```

using:
```
<ComboBox Classes="rightAligment"/>
```
