### ISSUE TITLE
code edit

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#4217]
I'm testing some demos. I hope to use code to play a window in the main method, or to get window objects. What should I do? In short, I need to read the configuration file and assign values to the window before the window is displayed;

In addition, how can TabControl add a tabitem with code?

**Comment by FoggyFinder** [comment]
I think you should start here:

https://avaloniaui.net/docs

Also I suggest reading the MVVM section especially carefully:

https://avaloniaui.net/docs/quickstart/mvvm

**Comment by jinyuttt** [comment]
@FoggyFinder 
I made a mistake.
First question:

TabControl tab = new TabControl(); TabItem item = new TabItem();

How to add item to tab?

Second question:

In the main method

MainWindow frm=new MainWindow();

report errors;

I'm not going to go through apps, I need to use frm objects.

**Comment by FoggyFinder** [comment]
> How to add item to tab?

```csharp
var tabControl = new TabControl
{
    Items = new[]
    {
        new TabItem()
        {
            Header = "123"
        }
        // the rest of TabItems goes here
    }
};
```

> In the main method MainWindow frm=new MainWindow(); report errors;

It is unclear to me what you're asking. If you give more details I can try to help.

Also, there is a chat [in gitter](https://gitter.im/AvaloniaUI/Avalonia) that fits better for simple questions than issues.
Also, there is a [AvaloniaUi] (https://stackoverflow.com/questions/tagged/avaloniaui) tag on SO.
Also, there is a new Q&A site where you can ask Q as well: [TopAnswers](https://topanswers.xyz/csharp)

**Comment by jinyuttt** [comment]
Default build:
![20200702182801](https://user-images.githubusercontent.com/13539621/86348578-6e4cde80-bc92-11ea-9d1c-b70d1cf2656f.jpg)
What I might need is:
![20200702183041](https://user-images.githubusercontent.com/13539621/86348648-845a9f00-bc92-11ea-9ef1-7f31505ac5fe.jpg)

**Comment by FoggyFinder** [comment]
If you open `App.xaml.cs` you see something like this:

```cs
public override void OnFrameworkInitializationCompleted()
{
    if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
    {
        desktop.MainWindow = new MainWindow();
    }

    base.OnFrameworkInitializationCompleted();
}
```

Here you can set properties based on a config:

```
// read config
var cfg = readConfig();
desktop.MainWindow = new MainWindow()
{
    Title = cfg
};
```

For additional information check [Application lifetimes](https://github.com/AvaloniaUI/Avalonia/wiki/Application-lifetimes#how-do-lifetimes-work) page.

**Comment by jinyuttt** [comment]
ok,thanks.
