### ISSUE TITLE
Popup can't be made transparent by setting Opacity property 

### ISSUE THREAD

**Issue by zenjia** [AvaloniaUI/Avalonia#4224]
I want to create a Dialog like this pic:
 
![dialog-demo](https://user-images.githubusercontent.com/30209122/86534081-2e8f2c80-bf08-11ea-8596-60912cc8d61e.png)
 
Below is the xaml code of dialog content which is a **UserControl** and will be put in the **Child** of **Popup**:

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             x:Class="AvaloniaApplication10.UserControl1">

  <Grid Background="Gray" Opacity="0.5" >

    <Border Width="200" 
            Height="200" 
            BorderBrush="Red" 
            BorderThickness="2" 
            Background="White">
      <TextBlock Text="Hello World Dialog!" />

    </Border>

  </Grid>

</UserControl>
```

I've subscribed the Bounds property of the **MainWindow** to make it to cover the full window. But the problem is **Opacity="0.5"** has not effect. I also has set the **Opacity** property of  the **Popup**, but still not working.
I also have try to custom the **PopupRoot** Style, but still can't make it work.

Is there any way to get this work? Thanks! (The project is Win32)
 
**[EDIT]**
Just tested WPF and UWP, both can be made transparent by set their child's transparency properly.

```
        private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
        {
            Popup po = new Popup();
 
            po.Child = new Border() { Width = 300, Height = 300, 
Background = Brushes.Beige, 
Opacity = 0.5};
            po.StaysOpen = true;
            po.AllowsTransparency = true;
            po.PlacementTarget = sender as FrameworkElement;

            po.IsOpen = true;
        }
```

**Comment by danwalmsley** [comment]
@zenjia this is definately possible in the new 0.10.0-preview1 with TransparencyLevelHint="Transparent"

**Comment by zenjia** [comment]
@danwalmsley  Glad to hear this. btw: When will  0.10.0-preview1 be released? Can't wait. Avalonia is amazing. Although the UI of UWP is pretty but it is built will cpp and too slow to compile, while WPF is too old!

**Comment by danwalmsley** [comment]
It's out now!

**Comment by danwalmsley** [comment]
0.10.0-preview1 is the nuget version

**Comment by ahopper** [comment]
Another way to achieve this is to use a panel covering everything else in your main window and avoid popups altogether.

**Comment by zenjia** [comment]
@ahopper I want to create a customized dialog using Popup, the implementation you mentioned has many restriction comparing with Popup.

**Comment by zenjia** [comment]
@danwalmsley  After updating to 0.10.0-preview1, I can't show the popup in code behind. What's wrong with my code?

```
        private void Button_Click(object sender, Avalonia.Interactivity.RoutedEventArgs e)
        {
            Popup po = new Popup();

            po.Child = new Border()
            {
                Width = 300,
                Height = 300,
                Background = Brushes.Green,
                Opacity = 0.5
            };
           
   
            po.PlacementTarget = sender as Button;
            po.PlacementMode = PlacementMode.Top;

            po.StaysOpen = true;
            po.IsOpen = true;
        }
```

**Comment by ahopper** [comment]
@zenjia yep it was just a possibility, but it may not be as limited as you think. There is an option called OverlayPopups which I guess work much like this.  I swapped out all my popups for panels that slide out or ones that cover the whole main window, I originally did it because at the time Avalonia had repeated issues with nested popups (long time ago) but It gave me the advantage of tranparency independent of os and looked neat so I've stuck with it.

**Comment by zenjia** [comment]
@ahopper  Interesting, but how to implement a dialog using panel? Seems we need access the MainWindow and dynamically insert/remove a panel in it every time when we want to show/close a dialog. That sounds not so elegant.

**Comment by ahopper** [comment]
@zenjia once you have encapsulated the code to do it, it is no more complex  than opening a dialog. I actually reuse a couple of panels for this as it is what I did first :) and I don't nest them. By Inserting/removing as you suggest it could probably be made more generic. Behind the scenes I suspect it is lighter weight than using popups.  I'm not trying to sell the idea, popups are good, I just thought it might give you another option

**Comment by zenjia** [comment]
@ahopper Since a popup will always be the topmost control, a fullscreen panel dialog will not cover a stay-open popup, so to use this implementation, there should be no stay-open poups. That's not good. Anyway, thanks for the suggestion.

**Comment by danwalmsley** [comment]
FWIW you don't need a popup to make that UI. Just put that content over your main window and hide or show it. It will look exactly the same and be more portable. We will investigate why the popup does not open however.
