### ISSUE TITLE
Window control

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#4229]
It is suggested to complete the basic common controls: status bar, toolbar

Avalonia should provide basic controls to facilitate development and management, rather than directly implemented by users. Users should implement styles on basic controls instead of using itemcontrol. Itemscontrol should be the basis of control implementation used in other industries.

**Comment by danwalmsley** [comment]
There are many projects with examples of those kinds of controls. With the resource available its not possible for Avalonia to implement every single control, however solutions are definately available from the community...

https://github.com/AvaloniaCommunity/awesome-avalonia
