### ISSUE TITLE
FluentTheme overrides Window font

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#4230]
The Fluent theme appears to set the font for some controls to `XamlAutoFontFamily` https://github.com/AvaloniaUI/Avalonia/blob/6c02a6e44b3545b1025fb0188b7772e16b8ae7d4/src/Avalonia.Themes.Fluent/Accents/BaseDark.xaml#L157 which as far as I can see is undefined so falls back to the system default. This causes differences cross platform if you are relying on an embedded font set on Window to keep things the same everywhere.  The key can be overridden but this relies on having more knowledge of the theme than I think is right.

**Comment by Gillibald** [comment]
This should only be set on the Window's fluent theme template so a local value still wins and inheritance still works.

**Comment by danwalmsley** [comment]
@ahopper it should be set to...
https://github.com/AvaloniaUI/Avalonia/blob/607be2af1f3817d057152bd38001473759b3d189/src/Avalonia.Themes.Fluent/Accents/Base.xaml#L15

Those XamlAutoFontFamily need removing.

If you want to use the OS font you need to override it..

Fluent theme is optimized for use with a particular font, and relying on the OS font will not produce good results, particularly when it comes to Linux.

**Comment by ahopper** [comment]
This has changed since the issue and I need to retest, the problem was that it was using the system font because of the XamlAutoFontFamily and overriding my use of roboto at window level.

**Comment by ahopper** [comment]
This seems fixed by a recent pr, other than a few unused XamlAutoFontFamily floating around.
