### ISSUE TITLE
Fluent ComboBox dropdown does not scroll on small screens

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#4231]
On the raspberry pi 7" touch screen ComboBox dropdowns disappear off the bottom of the screen with no scrolling.

**Comment by ahopper** [comment]
this is also a problem on mac, no scroll bars appear on the fluent dropdown

**Comment by grokys** [comment]
@danwalmsley can you repro this on OSX? I'm not seeing it on Win32.

**Comment by maxkatz6** [comment]
Closing in favor of https://github.com/AvaloniaUI/Avalonia/issues/6621
