### ISSUE TITLE
Textbox inside a popup control does not handle tapped event when clicking on whitespace.

### ISSUE THREAD

**Issue by pelgenj2** [AvaloniaUI/Avalonia#4239]
When clicking in textbox apart of a popup control, I would expect a tapped event occur. But it is only triggering when I click on the characters in the textbox. Any click in the whitespace does not trigger tapped event.

Snippet of my xaml:

```
<Popup x:Name="ValidateSetupPopup" StaysOpen="True"
           PlacementMode="Left" Margin="20,20"
           HorizontalOffset="500" VerticalOffset="150"
           IsOpen="{Binding ShowSetupPopup}">
```

...

```
<TextBox x:Name="PlanIDValue"
                Text="{Binding ValidateSetup.Plan, Mode=OneWay}"
                Watermark="Scan ID"
                Margin="10" FontSize="14" Focusable="True"/>
```

...

Snippet of my xaml.cs:
```
private TextBox PlanIDValue;
this.PlanIDValue.Tapped += this.TextBox_Refocus;

private void TextBox_Refocus(object sender, EventArgs e)
{
    PopupRoot popupWindow = (sender as TextBox).Parent.VisualRoot as PopupRoot;
    popupWindow.Activate();
    this.PlanIDValue.Focus();
}
```

**Comment by ahopper** [comment]
This appears to be true for a TextBox anywhere (not just in a popup).

**Comment by pelgenj2** [comment]
Hmm it's been a bit since I posted this. I'm surprised no one pick this up yet. 😅

**Comment by gehongyan** [comment]
For developers who found this issue, try using `PointerReleased` instead.

**Comment by YTJVDCM** [comment]
I encountered similar issue when I tried to use DoubleTapped event attached in StackPanel.
DoubleTapped event is executed when I clicked on a TextBlock element which is that in StackPanel, but when I clicked on a whitespace like made by Margin and VerticalAlignment, it doesn't execute.

**Comment by jp2masa** [comment]
Did you set `Background="Transparent"` in the `StackPanel`? It's `null` by default, which disables hit-testing.

**Comment by YTJVDCM** [comment]
It works!
I didn't know that attribute to allow to clicking on whitespace.
Thanks for the help.
