### ISSUE TITLE
Avalonia using latest master build instead of nuget packages

### ISSUE THREAD

**Issue by dinonovak** [AvaloniaUI/Avalonia#4244]
I am trying to set up new avalonia app to use latest master build instead of nugets.
So I set up new avalonia app,
added Avalonia and Avalonia.Desktop nugets. and app runs fine. 

To use latest master branch I cloned master repository,
```
git clone https://github.com/AvaloniaUI/Avalonia.git
git submodule update --init
```

I then built ControlCatalog.NetCore from samples, and used ReplaceNugetCache.ps1 0.9.11 to update local nuget cache with files from this local build.

But now when I am trying to run the app I am getting following error:
```
System.TypeLoadException
  HResult=0x80131522
  Message=Method 'IsEnabled' in type 'Avalonia.Logging.Serilog.SerilogLogger' from assembly 'Avalonia.Logging.Serilog, Version=0.9.11.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
  Source=Avalonia.Logging.Serilog
  StackTrace:
   at Avalonia.Logging.Serilog.SerilogExtensions.LogToDebug[T](T builder, LogEventLevel level)
   at AvaloniaTest1.Program.BuildAvaloniaApp() in C:\Users\dino\source\repos\AvaloniaTest1\AvaloniaTest1\Program.cs:line 75
   at AvaloniaTest1.Program.Main(String[] args) in C:\Users\dino\source\repos\AvaloniaTest1\AvaloniaTest1\Program.cs:line 45
```

<img width="760" alt="Screenshot 2020-07-07 at 23 41 54" src="https://user-images.githubusercontent.com/18152490/86847207-40a9d000-c0ac-11ea-9f71-4fced47e3b5c.png">

Also I am unable to found Avalonia.Logging.Serilog.dll anywhere in avalonia local master code, where is this hiding (should be in Avalonia.Base but when I build it I do not see it there in bin directory)

If I try to comment out .LogToDebug() from AppBuilder.Configure<App>() I am hitting different error:
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime' threw an exception.

Inner Exception 1:
TypeInitializationException: The type initializer for 'Avalonia.Controls.Window' threw an exception.

Inner Exception 2:
FileLoadException: Could not load file or assembly 'System.Reactive, Version=4.4.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
```
<img width="1178" alt="Screenshot 2020-07-07 at 23 54 57" src="https://user-images.githubusercontent.com/18152490/86847840-47851280-c0ad-11ea-99aa-24e5856cca36.png">

**Comment by FoggyFinder** [comment]
You can use nightly builds instead of submodules. It's way easier.

https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

Serilog was removed: #4135
