### ISSUE TITLE
Flickering window behind tooltip

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#4246]
When using Tooltips disappears it causes the Window behind my window to refreshed (?)
Example: 
![Hnet-image](https://user-images.githubusercontent.com/27368554/86891234-2ea94b00-c107-11ea-889e-13bb82a178b1.gif)
You can see every window reacts differently.

**Comment by danwalmsley** [comment]
@kekekeks could be something to do with the hosting code that was merged?

**Comment by kekekeks** [comment]
It looks like that something is affecting the system compositor.

**Comment by danwalmsley** [comment]
@adirh3 do you have acrylic blur on?

**Comment by adirh3** [comment]
@danwalmsley No, it happens with `WindowTransparencyLevel.None` as well.

**Comment by adirh3** [comment]
@danwalmsley Just noticed it only happens with the immediate renderer
