### ISSUE TITLE
FluentLight Theme ToggleButton Checked color changed to white

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#4250]
This was a dark colour in earlier releases, it looks like it has just been copied from the dark theme.

**Comment by danwalmsley** [comment]
How are you reproducing this?

**Comment by ahopper** [comment]
A standard ToggleButton shows it.  Control catalog sort of shows it even though it is a bit broken in LightFluent. 
https://github.com/AvaloniaUI/Avalonia/blob/b575818e7e631d702ccebfd6372a41216bfb0711/src/Avalonia.Themes.Fluent/Accents/FluentBaseLight.xaml#L92 
is the cause I guess.

**Comment by danwalmsley** [comment]
> A standard ToggleButton shows it. Control catalog sort of shows it even though it is a bit broken in LightFluent.
> https://github.com/AvaloniaUI/Avalonia/blob/b575818e7e631d702ccebfd6372a41216bfb0711/src/Avalonia.Themes.Fluent/Accents/FluentBaseLight.xaml#L92
> 
> 
> is the cause I guess.

How are you changing to the LightTheme?

**Comment by ahopper** [comment]
In control catalog with the combo boxes at the bottom right.  It looks fairly clear from the styles that it is being set to white.

**Comment by ahopper** [comment]
Assuming this is by design although it is not the mirror of dark mode.
