### ISSUE TITLE
TextWrapping doesn't work when using TextTrimming

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#4256]
When using `TextWrapping` and `TextTrimming` at the same time, the text never wraps. On WPF it works as expected.

## Repro

```xaml
<TextBlock MaxWidth="40" TextWrapping="Wrap" TextTrimming="CharacterEllipsis" Text="Hello World! Hello World!" />
```

### Avalonia
![avalonia](https://user-images.githubusercontent.com/10765201/87107535-e64d7280-c257-11ea-89b9-db4e56c3615e.png)

### WPF
![wpf](https://user-images.githubusercontent.com/10765201/87107526-ddf53780-c257-11ea-964c-b47b5855bee0.png)

**Comment by Gillibald** [comment]
Hmm y I could make that work but I don't think it is the right behavior. Wpf works a bit different because it trimms text lines after they have been created by the formatter. So the text wraps first and each line that has overflowed is trimmed.

**Comment by Gillibald** [comment]
This API would be ported if we follow WPF's way:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.textformatting.textline.collapse?view=netcore-3.1#System_Windows_Media_TextFormatting_TextLine_Collapse_System_Windows_Media_TextFormatting_TextCollapsingProperties___

https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.textformatting.textline.hasoverflowed?view=netcore-3.1#System_Windows_Media_TextFormatting_TextLine_HasOverflowed

https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.textformatting.textline.hascollapsed?view=netcore-3.1#System_Windows_Media_TextFormatting_TextLine_HasCollapsed

**Comment by Gillibald** [comment]
Okay. I will implement this shortly.
