### ISSUE TITLE
CSC : error CS0006: Metadata file could not be found

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#4257]
When I tried to build project from source I got erros below:

```
CSC : error CS0006: Metadata file could not be found - 

\Avalonia\src\Avalonia.DesktopRuntime\bin\Debug\netcoreapp2.0\Avalonia.DesktopRuntime.dll

CSC : error CS0006: Metadata file could not be found - 

\Avalonia\packages\Avalonia\bin\Debug\netcoreapp2.0\Avalonia.dll
```

Does it mean I should install .Net Core 2.0 ? If so which one precisely?

**Comment by rstm-sf** [comment]
The [question](https://github.com/AvaloniaUI/Avalonia/pull/3571#issuecomment-586396071) seems to have remained open

**Comment by FoggyFinder** [comment]
I've installed `.NET Core 2.0 SDK (v2.1.105)` and now it works

**Comment by ShrutiJaiswal1494** [comment]
I am also getting the same error even after installing `.NET Core 2.0 SDK`. Is there any other way to resolve this?

**Comment by FoggyFinder** [comment]
try to close VS then remove all ".bin"/".obj" folders

**Comment by FoggyFinder** [comment]
@ShrutiJaiswal1494 ^

**Comment by Ianuarius** [comment]
> try to close VS then remove all ".bin"/".obj" folders

Doesn't help
