### ISSUE TITLE
Question about ToggleSwitch

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#4258]
`0.10` introduces the new `ToggleSwitch` control but when I tried to define it like this:

```xaml
        <ToggleSwitch
            Content="Content"
            OffContent="Off"
            OnContent="On" />
```

I got next result

![toggleSwitch](https://user-images.githubusercontent.com/16510738/87131566-41ee1f00-c29d-11ea-88f0-e9ce96c9ce91.jpg)

actually, I would expect to see a toggle.

**Comment by maxkatz6** [comment]
It works only with fluent theme

**Comment by FoggyFinder** [comment]
> It works only with fluent theme

Why so? I do think in this case it should be mentioned explicitly.

Also. Screen is taken with this theme:

```xml
    <Application.Styles>
        <StyleInclude Source="avares://Avalonia.Themes.Fluent/FluentTheme.xaml" />
        <StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/BaseLight.xaml" />
    </Application.Styles>
```

If this is not a `fluent` theme then what should I change to see a toggle?

**Comment by maxkatz6** [comment]
@FoggyFinder 
Check ControlCatalog from master or this new repo https://github.com/AvaloniaUI/XamlControlsGallery to check Fluent theme.
Last one uses next includes:
```
      <StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseDark.xaml"/>
      <StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/FluentDark.xaml"/>
```

But I hope with latest nuget preview you don't need to include Default theme at all. @danwalmsley

**Comment by maxkatz6** [comment]
Also you can try to include only one ToggleSwitch style with related resources:
```
  <StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/BaseDark.xaml" />
  <StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/Base.xaml" />
  <StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/FluentBaseDark.xaml" />
  <StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/FluentControlResourcesDark.xaml" />
  <StyleInclude Source="avares://Avalonia.Themes.Fluent/ToggleSwitch.xaml"/>
```

Haven't tested this tho.

**Comment by FoggyFinder** [comment]
> Last one uses next includes:

Thank you. This finally works :-)
