### ISSUE TITLE
[ Suggestion ] Add rollForward policy to the global.json config

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#4259]
https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#rollforward

**Comment by kekekeks** [comment]
We have SDK version pinned because the concept of backwards compatibility seems to not apply well to the SDK.

**Comment by FoggyFinder** [comment]
> Anything newer than one in our global.json complains about a missing method in XmlSerializer

Are you sure ? I have only `3.1.301` so I add `rollForward` locally every time: without it most projects from solution are unloaded and except #4257 (which seems unrelated) I haven't saw any other issues.

**Comment by grokys** [comment]
The very next patch version after 3.1.101 (3.1.20 I think) broke Avalonia builds (see https://github.com/SharpGenTools/SharpGenTools/issues/164#issuecomment-627802559). This wouldn't be the first time that a .NET update broke our CI builds, so I think not having a roll-forward policy was a good idea.

**Comment by FoggyFinder** [comment]
Okay. Closing the issue then.
Though I personally think it would be better to find the actual reason and fix it ;-)

**Comment by kekekeks** [comment]
The actual reason is most likely a bug in CoreCLR

**Comment by Kryptos-FR** [comment]
I have the latest version of VS 2019 and VS 2019 preview (both with .NET Core 2.1 and 3.1 installed) and if I don't remove the specific version from global.json, not a single project can be loaded.
