### ISSUE TITLE
Blend mode 

### ISSUE THREAD

**Issue by RomanSoloweow** [AvaloniaUI/Avalonia#4261]
![image](https://user-images.githubusercontent.com/29205560/87193110-a9898600-c300-11ea-9677-f34547b5f8a8.png)

**Comment by RomanSoloweow** [comment]
Guys, what about it?

**Comment by danwalmsley** [comment]
Not sure what your asking?

**Comment by RomanSoloweow** [comment]
I would like to know what the fate of this Issue is. Will this feature be done?)
