### ISSUE TITLE
[Feature request] Support internal types in previewer

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#4262]
I usually mark some types defined in XAML as `internal`. This breaks the previewer.

## Description

The type is resolved here:

https://github.com/AvaloniaUI/Avalonia/blob/1ae75006911c94718653246c20a6f72760bc5945/src/Markup/Avalonia.Markup.Xaml/XamlIl/CompilerExtensions/AvaloniaXamlIlCompiler.cs#L122

So it tries to find the first exported type from all assemblies which matches the type's full name:

https://github.com/kekekeks/XamlX/blob/7b8b3013bd42e1992838a525c991f44191da55be/src/XamlX/IL/SreTypeSystem.cs#L73-L83

This obviously won't work for `internal` types. I also believe it shouldn't try to look for the class in all assemblies, only the current assembly (maybe `_configuration.DefaultAssembly` in `AvaloniaXamlIlCompiler`, or passed to `ParseAndCompile` from `AvaloniaXamlIlRuntimeCompiler.LoadSreCore`).

**Comment by kekekeks** [comment]
That will require us to emit [IgnoresAccessChecksToAttribute](https://www.strathweb.com/2018/10/no-internalvisibleto-no-problem-bypassing-c-visibility-rules-with-roslyn/)

**Comment by rstm-sf** [comment]
Just to clarify: for private we also need https://github.com/ForNeVeR/AvaloniaRider/issues/92#issuecomment-716602121
