### ISSUE TITLE
Getting started problem: Cannot add Button to Window

### ISSUE THREAD

**Issue by Plasma** [AvaloniaUI/Avalonia#4266]
Hi team,

I created a new Avalonia app with the .NET Core app template, and it runs fine using the example code:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1">
  Welcome to Avalonia!

</Window>
```

But as soon as I add a Button like some tutorials show, it errors:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1">
  Welcome to Avalonia!

  <Button>Test</Button>

</Window>
```

Error:
```
Unable to find a setter that allows multiple assignments to the property Content of type Avalonia.Controls:Avalonia.Controls.ContentControl (line 1 position 2) Line 1, position 2.	AvaloniaApplication1	MainWindow.axaml	1	
```

Any ideas?

Thank you!

**Comment by maxkatz6** [comment]
Window supports single child, so you can't put two controls inside. 
But you can use containers like StackPanel or Grid. 
'''xaml
<Window ...>
   <StackPanel>
      <TextBlock>Welcome to Avalonia!</TextBlock>
      <Button>Test</Button>
   </StackPanel>
<Window>
'''

Note that I used TextBlock control explicitly instead of plain text.

**Comment by Plasma** [comment]
> ```
>    <StackPanel>
>       <TextBlock>Welcome to Avalonia!</TextBlock>
>       <Button>Test</Button>
>    </StackPanel>
> ```

Thank you, that works!

**Comment by sgf** [comment]
> Window supports single child, so you can't put two controls inside. But you can use containers like StackPanel or Grid.
> 
> ```
> <Window ...>
>    <StackPanel>
>       <TextBlock>Welcome to Avalonia!</TextBlock>
>       <Button>Test</Button>
>    </StackPanel>
> <Window>
> ```
> 
> Note that I used TextBlock control explicitly instead of plain text.

Compared to the web, this design is not good.
