### ISSUE TITLE
Button corner radius

### ISSUE THREAD

**Issue by dayAndnight2018** [AvaloniaUI/Avalonia#4267]
Could you please tell me how to set the corder radius property of a button control?

**Comment by FoggyFinder** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/2549

**Comment by kekekeks** [comment]
We probably need to expose it as a separate property on the Button.

**Comment by dayAndnight2018** [comment]
thanks, i have done with help of a border control outside of the button!
