### ISSUE TITLE
StatusBar

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#4268]
Is there a status bar control?

**Comment by FoggyFinder** [comment]
No.

[Add StatusBar and StatusBarItem #1041](https://github.com/AvaloniaUI/Avalonia/issues/1041)

[StatusBar : Simple StatusBar/StatusBarItem control #1567](https://github.com/AvaloniaUI/Avalonia/pull/1567)

**Comment by Gillibald** [comment]
Closing this because there is already an issue covering this #1041

**Comment by Rushikesh3009** [comment]
How to Hide the status Bar in android phone..?

**Comment by timunie** [comment]
@Rushikesh3009 unrelated question. Please don't ask inside closed issues. Better to open a Q&A discussion or use Telegram support channel
