### ISSUE TITLE
ListBox.SelectedItems not filled from code before view (0.10 Preview 1)

### ISSUE THREAD

**Issue by MonkAlex** [AvaloniaUI/Avalonia#4272]
Create MVVM example project.
Update to 0.10 Preview 1 and compile.

Add code:
```

  public class MainWindowViewModel : ViewModelBase
  {
    public string Greeting => "Welcome to Avalonia!";

    public ObservableCollection<MyClass> Strings { get; } = new ObservableCollection<MyClass>();

    public ObservableCollection<MyClass> Selected { get; } = new ObservableCollection<MyClass>();

    public MainWindowViewModel()
    {
      Strings.Add(new MyClass() { Display = "One" });
      Strings.Add(new MyClass() { Display = "Two" });
      Strings.Add(new MyClass() { Display = "Another" });

      Selected.Add(Strings.Skip(1).First());
    }
  }

  public class MyClass
  {
    public string Display { get; set; }
  }
```

And view:
```
  <StackPanel>
    <StackPanel.DataTemplates>
      <DataTemplate DataType="vm:MyClass">
        <TextBlock Text="{Binding Display}"/>
      </DataTemplate>
    </StackPanel.DataTemplates>
    <ListBox Margin="10" SelectionMode="Multiple" Items="{Binding Strings}" SelectedItems="{Binding Selected}"/>
    <ListBox Margin="10" Items="{Binding Selected}"/>
  </StackPanel>
```
In view two listbox - first for real view (and "two" not selected) and second to see, what classes in VM property `Selected`.
Then, in second listbox "Two" string showed always and cannot be deselect in first listbox. In 0.9 work well.

**Comment by ShadowDancer** [comment]
Repro repository
https://github.com/ShadowDancer/AvaloniaRepro/tree/bug/list_ignores_items

**Comment by grokys** [comment]
@ShadowDancer you reported that this got broken again in 0.10.0-preview5 but I've not been able to reproduce. Do you have a repro? I've tried a simple repro of:

```xml
  <ListBox Items="{Binding Items}" SelectedItems="{Binding SelectedItems}"/>
```

```csharp
    public class ViewModel
    {
        public ObservableCollection<string> Items { get; } = new ObservableCollection<string> { "foo", "bar", "baz" };
        public ObservableCollection<string> SelectedItems { get; } = new ObservableCollection<string> { "bar" };
    }
```

And everything seems to work.

**Comment by ShadowDancer** [comment]
@grokys Just clone repo from previous post (on branch posted in link).

I have similar code, but in my repro i'm also displaying
`<TextBlock Text="{Binding SelectedItems.Count}"/>`
And it is always 2 ("bar" is added twice) I think.

Now when I look on it I should've reported different issue maybe.

**Comment by grokys** [comment]
Ah yes, sorry, missed that. Will investigate.

**Comment by grokys** [comment]
@ShadowDancer just tried your repro (`bug/list_ignores_items` branch) and it seems to work fine. Are you sure it's not working for you?

**Comment by ShadowDancer** [comment]
https://imgur.com/a/cKoED4a
This is clip right after launching the app. You can see "2" in SelectedItems.Count, but list is in single select mode, it should never have 2 items.

![image](https://user-images.githubusercontent.com/766312/92928110-f0017b00-f43e-11ea-842d-2cac908fe3e2.png)

**Comment by grokys** [comment]
Ahh yeah, I missed that 2 items were being reported as selected. Got it now, thanks!
