### ISSUE TITLE
[Suggestion] Ribbon Control

### ISSUE THREAD

**Issue by nlogozzo** [AvaloniaUI/Avalonia#4273]
Could we see a ribbon control in Avalonia? Similar to https://github.com/fluentribbon/Fluent.Ribbon or even a port of Fluent.Ribbon to Avalonia?

**Comment by maxkatz6** [comment]
https://github.com/amazerol/AvaloniaRibbon

See:
https://github.com/AvaloniaUI/Avalonia/issues/3873
https://github.com/AvaloniaUI/Avalonia/issues/3949

**Comment by nlogozzo** [comment]
Oh cool didn't know about that. Other question however, can it be used with the fluent theme (seen here https://user-images.githubusercontent.com/6759207/84751662-7c79da00-afc5-11ea-8780-dda28db70b76.png)?

**Comment by maxkatz6** [comment]
There is no Ribbon control or similar for Fluent Design neither in Avalonia nor in WinUI (not sure if we need it at all honestly).
So you could restyle it, that it will look in-line with other controls.

You can find some inspiration here https://github.com/microsoft/microsoft-ui-xaml/issues/168
Note that Ribbon is usually replaced with CommandBar in UWP/WinUI, that doesn't exist in Avalonia, but could be partially replaced with StackPanel and Buttons.

**Comment by nlogozzo** [comment]
👍 sounds good 
thanks

**Comment by yoshiask** [comment]
I'd like to point out that the Windows Community Toolkit may have a Ribbon control for the 7.0 release

**Comment by cybik** [comment]
Not to necro this thread, but for the record, this also exists:

https://github.com/Splitwirez/AvaloniaRibbon

**Comment by chuongmep** [comment]
Can I know the reason why this topic closed ?

**Comment by maxkatz6** [comment]
@chuongmep there are no plans to add this control.
