### ISSUE TITLE
Vulkan Control?

### ISSUE THREAD

**Issue by define-private-public** [AvaloniaUI/Avalonia#4274]
I see in the upcoming `0.10` release an OpenGL control is included.  To future proof Avalonia better, I think it would be wise to include a sort of Vulkan Control as well.  There are projects out there such as [Silk.NET](https://github.com/Ultz/Silk.NET) which provide cross platform Vulkan bindings (have yet to try them out for myself).

Other widget toolkits such as Qt have [already added Vulkan capability](https://doc.qt.io/qt-5/qvulkanwindow.html).  And I'm sure that more are to follow.

**Comment by kekekeks** [comment]
OpenGLControlBase works on top of generic [OpenGL-textrure-as-Bitmap API](https://github.com/AvaloniaUI/Avalonia/blob/1ae75006911c94718653246c20a6f72760bc5945/src/Avalonia.OpenGL/Imaging/OpenGlTextureBitmap.cs), which is essentially our [D3DImage](https://docs.microsoft.com/en-us/dotnet/api/system.windows.interop.d3dimage) counterpart.

So Vulkan-drawn surfaces can be presented by either wrapping a DXGI-shared handle (win32), `VK_KHX_external_memory` extension (Linux) or IOSurface (OSX/iOS).

Wiring those up is an application-specific task that is outside of the scope of the project, but I'll try to provide some examples of doing that after 0.10 release.

**Comment by chances** [comment]
Note, the `VK_KH*_external_memory` extension has been promoted to [a KHR](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_memory.html).

**Comment by llfab** [comment]
We have finalized a Vulkan integration into WPF using DXGI similar to Microsofts sample implementation [WPFDXInterop](https://github.com/microsoft/WPFDXInterop). Hence, we integrated our Vulkan 3D renderer with DX11 and made interoperability work with WPF DX9 creating our own subclass ```VulkanImage``` with ```D3DImage``` as its base class.

It works "functionally" very nicely. We also integrated the ```VulkanImage``` into a custom WPF ```FrameworkElement``` such that you can instantiate the entire thing via XAML. 

We did a similar thing with OpenGL / Vulkan to make that work in Avalonia. This was a little more direct as you do not also have the breakage between the different DX versions. 

However, both OpenGL / Vulkan integration and DirectX / Vulkan Integration have the following drawbacks:

- Latency: compared to a very native implementation using a swap chain to render to a ```hwnd``` using Windows.Forms and ```FormsHost``` for WPF integration, you can see quite some latency. We are displaying mostly still 3D scenes, so this is not so much a problem. For more demanding environments this seems almost a NoGo.
- Compatibility: both for OpenGL / Vulkan and DirectX / Vulkan we had to used vk extensions (OpenGL extensions) for sharing textures. This seems very demanding regarding GPU and driver capability. Though, it does work on most (even older) Nvidia environments and on most up to date Intel SoC GPU's, we found more incompatibilites than we would be happy with. 
- Cross-platform: we found that you need different code routes on Windows than on Linux. Something that is not so nice to maintain.

Therefore, I would encurage a Vulkan backend for Avalonia to overcome above issues. Maybe that is also an option to overcome the Avalonia rendering "indirection" using EGL/Angle (as WGL seems not a good option on Windows). However, I admit that Vulkan compatibility is not as common as OpenGL, hence, fully replacing the OpenGL Skia backend would not be smart.

**Comment by maxkatz6** [comment]
Implemented with https://github.com/AvaloniaUI/Avalonia/pull/12737
See [GpuInterop samples](https://github.com/AvaloniaUI/Avalonia/tree/master/samples/GpuInterop)

**Comment by danipen** [comment]
Do the [GpuInterop samples](https://github.com/AvaloniaUI/Avalonia/tree/master/samples/GpuInterop) work in macOS?

**Comment by maxkatz6** [comment]
@danipen with Vulkan? No, it doesn't. At least yet, as [MoltenVK](https://github.com/KhronosGroup/MoltenVK) technically can be used on top of Metal.

GPU interop itself is only usable on macOS with OpenGL when Metal is disabled. But since for most users gpu interop isn't necessary, Metal was chosen as a better default with better performance and improved render loop.

**Comment by danipen** [comment]
Thanks @maxkatz6 

So if I understand correctly... at this time, if we want to draw 3D content in an Avalonia control... the most straightforward way is to render it using using OpenGL and change the drawing backend to Open GL in MacOS. 

Additionally if we want to go for Vulkan, macOS would not be supported at this moment.

Is that my assumption correct? Is there any other alternative? Thanks!
