### ISSUE TITLE
How to retreive command line arguments

### ISSUE THREAD

**Issue by define-private-public** [AvaloniaUI/Avalonia#4275]
I'm working on an application right now where I'd like the user to be able to launch the application via a terminal, but also be able to specify a default file to load.  e.g. `myApp image.png`  I'm wondering if there is an easy way for my application to retrieve the command line argument that were passed into it at this part:

```csharp
BuildAvaloniaApp().StartWithClassicDesktopLifetime(args);    // `args` comes from `Program.cs`'s `Main()`
```

E.g. In my `App`'s code, I'd like to be able to retreive those args and parse them to find an initial file:

```csharp
        public override void OnFrameworkInitializationCompleted()
        {
            if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
            {
                desktop.MainWindow = new MainWindow
                {
                    DataContext = new MainWindowViewModel(),
                };
                // Get those `args` somewhere around here and then pass them into a function in the `DataContext`

            }

            base.OnFrameworkInitializationCompleted();
        }
```

I saw that there was this entry on the wiki:
https://github.com/AvaloniaUI/Avalonia/wiki/Application-lifetimes#manual-lifetime-management

AFAICT, it seems like the only way to pass those command line args off to my app's code.  Unless there is another way?

**Comment by ahopper** [comment]
The IClassicDesktopStyleApplicationLifetime.Startup event passes the args.

**Comment by define-private-public** [comment]
Okay, I was able to do this successfully using that event.

I think it would be beneficial to mention this somewhere in the docs.

**Comment by Nikhilsp** [comment]
How did you do it? @define-private-public

**Comment by out4blood88** [comment]
@Nikhilsp I put this in App.axaml.cs:

```
public override void OnFrameworkInitializationCompleted()
{
    var desktopLifetime = ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
    desktopLifetime!.Startup += (sender, args) =>
    {
        // Do stuff with args
        // Create your window
    };
}
```

**Comment by FaridGad** [comment]
@out4blood88 
Your code works but the designer previewer of the .axaml files stops working. It just remains stuck on "The designer is loading".

![grafik](https://github.com/AvaloniaUI/Avalonia/assets/39767505/103d8ee3-e41f-4b8b-8958-761ed8307e53)

**Comment by jakeguti** [comment]
@FaridGad you  have to put that code inside the OnFrameworkInitializationCompleted method.

**Comment by stewpend0us** [comment]
for me "desktop.Args" contained the arguments passed in on the command line
