### ISSUE TITLE
Sample Code For Fluent Window

### ISSUE THREAD

**Issue by nlogozzo** [AvaloniaUI/Avalonia#4276]
Where can the code be found to replicate this design (Including the styles used in App.axaml)?
https://user-images.githubusercontent.com/6759207/84751662-7c79da00-afc5-11ea-8780-dda28db70b76.png
Or in other words, how do create a window that implements the fluent theme?

**Comment by FrankenApps** [comment]
It's in samples/ControlCatalog if you want to run it you need to choose the .Net Core Version.
