### ISSUE TITLE
Compiled bindings do not resolve automatically data type from style selector

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#4278]
/home/ubuntu/projects/Core2D/src/Core2D.UI/Views/Containers/ProjectControl.xaml(51,51,51,51): Avalonia error XAMLIL: Unable to resolve property of name 'IsExpanded' on type 'XamlX.TypeSystem.CecilTypeSystem+CecilType'. (line 51 position 51) Line 51, position 51. [/home/ubuntu/projects/Core2D/src/Core2D.UI/Core2D.UI.csproj]

```XAML
            <TreeView.Styles>
                <Style Selector="TreeViewItem">
                    <Setter Property="IsExpanded" Value="{Binding IsExpanded, Mode=TwoWay}"/>
                </Style>
            </TreeView.Styles>
```

this works, but it's additional step
```XAML
                <Style Selector="TreeViewItem" x:DataType="TreeViewItem">
                    <Setter Property="IsExpanded" Value="{Binding IsExpanded, Mode=TwoWay}"/>
                </Style>
```

**Comment by Sigrec** [comment]
I''m having the same issue with ComboBoxItem but hardcoding the DataType still does not work for me on Avalonia 11 Preview 4

**Comment by maxkatz6** [comment]
I am not sure how it supposed to work. As you can't guess DataContext from the style.
"TreeViewItem" isn't correct data type here all the time, it might be actual data control is binded to.

@Sigrec if setting DataType doesn't work for you, can you create another issue with minimal example to show the issue?
