### ISSUE TITLE
`TryParse` methods should be safe to use

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#4279]
https://github.com/AvaloniaUI/Avalonia/blob/fbdeaad0d5f9f8d38ab3b962fbc3926cfaf8f6fb/src/Avalonia.Visuals/Media/Color.cs#L115-L150

It is quite unexpected that a `TryX` method can raise an exception.

Why the two different approaches are combined in a single method? I see no advantages of doing this.

I do think it would be much better to return `false` in case when `s` parameter is null or empty.

**Comment by grokys** [comment]
@MarchingCube

**Comment by kekekeks** [comment]
BCL `TryParse` methods aren't throwing on `null` strings. So it seems to be the contract for those.

**Comment by MarchingCube** [comment]
I guess I want a bit too far when unifying both, need to change how checks are being done in `Try` variant.
