### ISSUE TITLE
d:DesignWidth/d:DesignHeight are broken for >=0.9.8 and master

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#4303]
Most likely caused by one of those:
https://github.com/AvaloniaUI/Avalonia/pull/3797
https://github.com/AvaloniaUI/Avalonia/pull/3800

**Comment by grokys** [comment]
Will take a look at this.

**Comment by grokys** [comment]
From a bisect, seems to have been introduced by https://github.com/AvaloniaUI/Avalonia/pull/3787

**Comment by GF-Huang** [comment]
`0.10.0-rc1` issue still.

![image](https://user-images.githubusercontent.com/4510984/103854745-2e0c6400-50ec-11eb-8135-f3303c50807a.png)

**Comment by GF-Huang** [comment]
After close the `axaml` file then re-build and re-open the `axaml`, issue solved.
