### ISSUE TITLE
Resources are never converted to target property type

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#4312]
Resources are never converted to target property type (e.g. setting a `double` property from an `int` resource). I think this used to work on 0.9. Not sure if it's by design or a regression.

## Repro

1. Add `xmlns:sys="clr-namespace:System;assembly=netstandard"`
2. Define a resource: `<sys:Int32 x:Key="MyFontSize">12</sys:Int32>`
3. Set the `FontSize` of `TextBlock` to `{StaticResource MyFontSize}`, there are 2 bugs I believe:
  3.1. With style:
    ```xaml
    <Style Selector="TextBlock">
        <Setter Property="FontSize" Value="{StaticResource MyFontSize}" />
    </Style>
    ```
    3.2. Directly:
      ```xaml
      <TextBlock FontSize="{StaticResource MyFontSize}" Text="Some text" />
      ```

**Comment by maxkatz6** [comment]
Can't reproduce anymore
