### ISSUE TITLE
TextBox caret is invisible for right aligned text

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#4315]
## Repro

Control catalog text box page, clicking in the last position of the "Right aligned text" text box, no caret.

I believe this is caused by adding 0.5 here:

https://github.com/AvaloniaUI/Avalonia/blob/5004606400cf07f6a2cbb7a54de7aa6627d87931/src/Avalonia.Controls/Presenters/TextPresenter.cs#L354

Which is actually needed, but causes the caret to be outside the bounds.

**Comment by Andre118** [comment]
Is this still up to date? When checking i had the caret show correctly both in the control catalog and a quick test program. I only checked on desktop however.

**Comment by Gillibald** [comment]
Y this issue is outdated
