### ISSUE TITLE
Help!Help!How to package the avaloniaui by .netcore3.1 in linux or centos

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#4316]
Hello,My Dear:
  I want to find the answer,please help me. How to package the avaloniaui by .netcore3.1 in linux or centos
.i  want to run avalonia in linux or cents,  through the package,not pulish directly code

**Comment by kekekeks** [comment]
https://github.com/qmfrederik/dotnet-packaging

**Comment by wuzlai** [comment]
thank you,handsome,i will try it ,as soon as  early。

**Comment by wuzlai** [comment]
> https://github.com/qmfrederik/dotnet-packaging
> 
> You'll need to add an icon to `/usr/share/icons` and a `.desktop` file to `/usr/share/applications`.
> Both can be added via
> 
> ```
>     <Content Include="myicon.png" CopyToPublishDirectory="PreserveNewest">
>       <LinuxPath>/usr/share/icons/myicon.png</LinuxPath>
>     </Content>
> ```

thank you,handsome,i will try it ,as soon as early。
