### ISSUE TITLE
Unable to Bind IsVisible or Width on DataGrid Columns

### ISSUE THREAD

**Issue by Ace4896** [AvaloniaUI/Avalonia#4326]
In version 0.9.11, the example below results in an `Unable to find suitable setter or adder for property` for the two columns that bind `Width` and `IsVisible` respectively:

```xaml
<DataGrid Items="{Binding Entries}">
    <DataGrid.Columns>
        <DataGridTextColumn Header="ID" Binding="{Binding ID}" Width="Auto" />
        <DataGridTextColumn Header="Field" Binding="{Binding Field}" Width="{Binding $parent[Window].FieldColumnWidth}" />
        <DataGridTextColumn Header="Field" Binding="{Binding Field}" Width="Auto" IsVisible="{Binding $parent[Window].DataContext.IncludeField}" />
    </DataGrid.Columns>
</DataGrid>
```

Where `FieldColumnWidth` is a styled property (of type `DataGridLength`) on the UserControl and `IncludeField` is a property on the ViewModel.

**Comment by joelbyren** [comment]
I was also having this particular problem, doesn't seem to happen too often then, but I would still like it to be fixed.

**Comment by joelbyren** [comment]
You are right, although it must have been very recent? I had 0.10.6 installed and I got the warning, but upgraded to 0.10.8 and it now works. Thanks anyway!
