### ISSUE TITLE
How to put the software on the Mac App Store，Let's say I already have the DMG or  PKG File

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#4329]
Hello,i use viual stidio 2019  to make software,and i already have the DMG or  PKG File，Now，i want to know  how to put the software on the Mac App Store, what shold i do ,examle. how to install an Apple certificate for this software,sinature ....

Can you provide a process？

**Comment by kekekeks** [comment]
The process is roughly the same as for regular OSX apps. For avalonia-specific parts, follow the guild from the docs here - https://avaloniaui.net/docs/packing/macOS

**Comment by wuzlai** [comment]
> The process is roughly the same as for regular OSX apps. For avalonia-specific parts, follow the guild from the docs here - https://avaloniaui.net/docs/packing/macOS

Thank you,i have got it,i will try it flow on steps.

**Comment by danwalmsley** [comment]
@wuzlai feel free to re-open later if needed.

**Comment by wuzlai** [comment]
> @wuzlai feel free to re-open later if needed.

Ok,thank you,I  have finished it.Now  i can successfully publish and package applications for each platform.example windows.linux,osx.
