### ISSUE TITLE
Invalid control Bounds when RenderTransform is applied

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#433]
I think this also affect the input when using pointer event and `GetPosition` relative to transformed control.

![rendertransform](https://cloud.githubusercontent.com/assets/2297442/13127383/596f9380-d5cf-11e5-8e5c-e73c1c2cae1b.PNG)

**Comment by grokys** [comment]
Yes, currently render transforms are just that: they are transforms applied at render time. Hit testing and the diagnostics window aren't currently aware of them.
