### ISSUE TITLE
[ ItemsRepeater ] How to show all items ?

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#4330]
It's unclear why only single item is displayed by default:

MCVE

```xml
  <Grid ColumnDefinitions="*,*">
    <ItemsRepeater Grid.Column="0" Items="{Binding Items}" />
    <ItemsControl Grid.Column="1" Items="{Binding Items}" />
  </Grid>
```

```cs
public class Context
{
    public IEnumerable<string> Items { get; }
    public Context()
    {
        Items = Enumerable.Range(0, 10).Select(v => v.ToString()).ToArray();
    }
}
```

![_itemsRepeater](https://user-images.githubusercontent.com/16510738/87933551-20a7e280-ca96-11ea-9bdf-faa031fb5d0a.jpg)

I'd expect the same view for `ItemsRepeater` as for `ItemsControl` here.

**Comment by grokys** [comment]
Apologies for the brief comment, but I'm on mobile (on vacation). ItemsRepeater needs to be hosted in a scroll viewer to function correctly I believe. It should be the same in upstream WinUi.

**Comment by FoggyFinder** [comment]
Thank you. Yep, works with ScrollViewer.
Not very familiar with WinUi and this wasn't mention explicitly in the docs (or I overlooked it).

**Comment by grokys** [comment]
Reopening this and submitting a fix because it's silly behavior.
