### ISSUE TITLE
[Packing]Notarizing your software,Have you met any of them

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#4338]
![image](https://user-images.githubusercontent.com/7692353/88041171-971f1000-cb7c-11ea-8b18-e0a14e79bfa1.png)
Run xcrun altool --notarize-app -f MyApp.app --primary-bundle-id com.identifier -u username -p password. You can use a password in your keychain by passing `-p "@keychain:AC_PASSWORD", where AC_PASSWORD is the key. The account has to be registered as an Apple Developer.

Now,I've done  the 2th step ,but failed.The exception is “ Error: Is a directory The operation couldn’t be completed. Is a directory”，
I am executing the statement in the current directory. my statement is "root$ xcrun altool --notarize-app --file "TestApp.app"    --primary-bundle-id "com.test.ios" -u "fake@test.com"  -p "0011-o111-111e-z111""
The file structure is as follows:
root$ ls
MyAppEntitlements.entitlements	cert.sh
TestApp.app			sign.sh
TestApp.dmg

**Comment by kekekeks** [comment]
@Deadpikle

**Comment by Deadpikle** [comment]
@wuzlai Looks like I forgot a step when writing those docs. You have to put your `.app` in a `.zip` file before you upload it, then run `xcrun altool` on the `.zip` file. You still staple the .app at the end, though. I will revise the docs and submit a PR for them momentarily.

@kekekeks Thanks for the highlight and bringing this to my attention.
