### ISSUE TITLE
Does not readily build in linux

### ISSUE THREAD

**Issue by gdennie** [AvaloniaUI/Avalonia#4347]
Downloading Avalonia into "Linux Mint 19.1" with DotNet Cli and VSCode with OmiSharp installed, clone the archive, then open the archive folder or src folder...

Some projects failed to load. Appears they weren't built. `Avalonia.Themes.Default/Avalonia.Themes.Default.csproj`, for example.

**Comment by danwalmsley** [comment]
@gdennie do you want to develop / contribute to the framework or build your own application...

if its the latter then you dont need to clone the repo... see http://avaloniaui.net/docs/quickstart

if its the former, you need to follow the instructions here... 
https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md
