### ISSUE TITLE
[0.10 Preview] Grid LayoutUpdated can re-trigger itself

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#4349]
https://github.com/mat1jaczyyy/apollo-studio/tree/avalonia-0.10
Windows 10 1903

I'm migrating my app from `0.9.999-cibuild0006058-beta` to `0.10-preview1`. Opening another window causes the UI to hang, becoming unclickable (although actions like closing windows do work).

To repro, compile and either hit the Preferences gear button in the top-left corner of the Splash window, or hit the New Project button (both of which show a new window). The UI hangs.

**Comment by kekekeks** [comment]
Does it work with hw-acceleration disabled?

**Comment by mat1jaczyyy** [comment]
@kekekeks Tried it with `.With(new Win32PlatformOptions() { AllowEglInitialization = false })` if that's what you mean, still reproes whether I set it to true or false

**Comment by danwalmsley** [comment]
@kekekeks could be some issue with modality.

@mat1jaczyyy are you setting owner window?

Are you using Show or ShowDialog, please point us to exact line of code to look at.

**Comment by mat1jaczyyy** [comment]
@danwalmsley yes, I'm setting Owner before showing the Window so the window can center above the window that launched it. I clear it immediately after showing.

When reproing using Preferences window, https://github.com/mat1jaczyyy/apollo-studio/blob/b81d57da496fe30c81c48bec64dd904447ef6d1b/Apollo/Windows/PreferencesWindow.cs#L395

**Comment by danwalmsley** [comment]
why do you set owner to null? try not doing that.

**Comment by mat1jaczyyy** [comment]
@danwalmsley Still reproes after I delete line 396 (don't clear Owner after showing). The reason for that is to not keep an unnecessary reference to the window that launched it, as that window can get closed in the future.

Even if this is the implementation of the Create method, it still reproes:
```cs
public static void Create(Window owner) {
    Preferences.Window = new PreferencesWindow();
    Preferences.Window.Show();
}
```

I've just tested on macOS 10.13.6 in addition to prior testing on Windows, the hang also reproes there.

**Comment by kekekeks** [comment]
@danwalmsley I've thought that we've made `Owner` to be readonly during that dialogs rework.

**Comment by mat1jaczyyy** [comment]
@danwalmsley 0.10.0-preview3 still repros this bug

**Comment by mat1jaczyyy** [comment]
https://github.com/mat1jaczyyy/apollo-studio/blob/8e2d73c5b05f8b8aa71ec81a2d24210266f3b2f9/Apollo/Components/Dial.xaml#L6

The LayoutUpdated event on this grid kept infinitely looping and calling itself, hanging the UI. Wasn't an issue before. In my case, I only need this to fire once when the layout is first updated, so I was able to unsubscribe the function from the event and break the loop. However, might be an issue for some others.
