### ISSUE TITLE
v0.9.11 Combobox Selecteditem binding not worked

### ISSUE THREAD

**Issue by Enoq00** [AvaloniaUI/Avalonia#4352]
XAML -
<ComboBox  Items="{Binding Sports}" SelectedItem="{Binding SelectedSport}" Width="206" Height="36"></ComboBox>

 VIEWMODEL -
        [Reactive]
        public Sport SelectedSport { get; set; }

        [Reactive]
        public List<Sport> Sports { get; set; }

    public class Sport
    {
        public int Id { get; set; }

        public string Name { get; set; }
   }

**Comment by FoggyFinder** [comment]
Can you provide MCVE? Asking because I think code that you posted is not full enough to check the issue.
