### ISSUE TITLE
Namespace Avalonia.Logging.Serilog not found in 0.10 preview

### ISSUE THREAD

**Issue by GF-Huang** [AvaloniaUI/Avalonia#4356]
![image](https://user-images.githubusercontent.com/4510984/88340876-27bd4200-cd6f-11ea-875b-a081b9ae001f.png)

**Comment by FoggyFinder** [comment]
Serilog was removed: #4135 

Just remove the using :-)

**Comment by GF-Huang** [comment]
@FoggyFinder  Thanks your quick response.

Is it only 0.10 and upper supports that the UI transparent like this:

![image](https://user-images.githubusercontent.com/4510984/88342012-3278d680-cd71-11ea-836a-7015e8eb9d67.png)

**Comment by FrankenApps** [comment]
Yes. That is only supported in 0.10 upwards.
