### ISSUE TITLE
Placeholder TextBlock is missing in default theme in ComboBox

### ISSUE THREAD

**Issue by rumkit** [AvaloniaUI/Avalonia#4359]
Hi, it seems that after implementing PlaceholderTextProperty in ComboBox [(9b24d68)](https://github.com/AvaloniaUI/Avalonia/commit/9b24d68d717c09c2206a75441c3e5a7b8f10cd45) Default theme wasn't updated. As a result the placeholder is only displayed in Fluent theme. Looks like a fix for that is going to be pretty straightforward, should I open a PR for that?

**Comment by danwalmsley** [comment]
@rumkit please submit a PR :)
