### ISSUE TITLE
ProgressBar IsIndeterminate is broken

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#4360]
Repro:
```xaml
<ProressBar IsIndeterminate="True" />
````

It's currently not visible in the control catalog because progress bars are initially in a normal state and are switcher to IsIndeterminate via checkbox.

So, [this commit](https://github.com/AvaloniaUI/Avalonia/commit/a0be18e3f66989e8fd91acb53b025c407fb81e1d) from @jmacato  did not, in fact, fixed it.

**Comment by garyhertel** [comment]
Just ran into this myself. If IsIndeterminate is initialized to true, only the Fluent themes will show the animation by default. The Control Catalog shows this in the ProgressBar tab if you check "Toggle Indeterminate" and switch themes. If does work if you toggle after loading though, but breaks after switching again.

This would be nice to get fixed before the 0.10 release so I don't have to add some workarounds. (although maybe I'll be using the Fluent theme or a variant then...)
