### ISSUE TITLE
Clipboard methods on Windows don't complete (infinite loops).

### ISSUE THREAD

**Issue by dfkeenan** [AvaloniaUI/Avalonia#4363]
Hi,

In the Windows implementation of `IClipboard` the `SetDataObjectAsync`, `GetFormatsAsync` and `GetDataAsync` methods all use a similar pattern:

```C#
while (true)
{
    if (UnmanagedMethods.SomeOlemethod() == 0)
    {
        //exit loop
    }

    await Task.Delay(100);
}
```

If the `Ole` method never succeeds the method call will never end. They should probably be changed to have a retry limit. I have not had any troubles with  `GetFormatsAsync` or `GetDataAsync` but `SetDataObjectAsync` never completes for me.

Cheers,
dfkeenan

**Comment by Gillibald** [comment]
Y it should handle cases other than S_OK https://docs.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-olesetclipboard

**Comment by joaompneves** [comment]
I believe that [this](https://github.com/AvaloniaUI/Avalonia/pull/5103) handles those concerns.

**Comment by dfkeenan** [comment]
> I believe that [this](https://github.com/AvaloniaUI/Avalonia/pull/5103) handles those concerns.

Yeah, that looks like #5103  should take care of this. I'll close this issue.
