### ISSUE TITLE
[Question] How to get PixelFormat and pixels from a Bitmap?

### ISSUE THREAD

**Issue by dfkeenan** [AvaloniaUI/Avalonia#4365]
Hi,

Is there a way to get the `PixelFormat` and pixel data from a `Bitmap`? 

The only way I could think of find is saving the `Bitmap` to a `Stream` and then load it into something like an `SKBitmap`.

Cheers,
dfkeenan

**Comment by kekekeks** [comment]
CopyPixels API is introduced in 11.0
