### ISSUE TITLE
Implement ResizeMode for window

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#437]
Look at this: https://msdn.microsoft.com/en-us/library/system.windows.window.resizemode(v=vs.110).aspx

**Comment by zezba9000** [comment]
I guess ResizeMode has to do with Minimize as well. I wonder if this WPF approach could be translated to Cocoa or GTK etc.

**Comment by jkoritzinsky** [comment]
I think it can be mapped into Cocoa (not sure about the CanResizeWithGrip though. Might just fallback to CanResize). Not positive about GTK.

**Comment by KvanTTT** [comment]
As I remember this option available since GTK 3: [GtkWindow resizable](https://developer.gnome.org/gtk3/stable/GtkWindow.html#GtkWindow--resizable). Avalonia uses GTK 2.

**Comment by kekekeks** [comment]
>GtkWindow:resize-grip-visible has been deprecated since version 3.14 and should not be used in newly-written code.
>Resize grips have been removed.

Resize grips might also cause issues with our way of rendering things. So it will be a boolean property.
For minimizing/maximizing/closing we need separate properties, I think.

**Comment by mat1jaczyyy** [comment]
Shouldn't this be closed by #1522?

**Comment by aguahombre** [comment]
On WIndows with CanResize set false, the Maximize/Restore button is still displayed on the title bar.
The user can still resize the window to full screen.

The Maximize/Restore button should not appear when CanResize is set to false.

**Comment by stevozilik** [comment]
Resizing and Min/Max are seperate concerns. 

I'd like my window to be manually resizable, but hide the buttons

**Comment by mysteryx93** [comment]
This is still pending after 5 years?

**Comment by maxkatz6** [comment]
I will close this issue because CanResize is implemented. For hiding maximize/minimize button we have another issue https://github.com/AvaloniaUI/Avalonia/issues/5147
