### ISSUE TITLE
Custom fonts are broken in 0.10.0-preview1/2 on Windows

### ISSUE THREAD

**Issue by arklumpus** [AvaloniaUI/Avalonia#4370]
There appear to be some issues with the font loader in 0.10.0-preview1 and 0.10.0-preview2 (everything works fine up to 0.9.11). When multiple variations of the same FontFamily are included as EmbeddedResources, not all of them are correctly displayed. Furthermore, there seems to be some race condition, because the ones that are displayed correctly change every time the program is run (even without rebuilding).

In the following screenshot, the window on the left was built with Avalonia 0.9.11 (and looks fine). The other two were built with Avalonia 0.10.0-preview2 (with exactly the same code as the other one), and they show the problem. They were obtained by running twice the same executable (interestingly, the normal and bold font are always fine, it's the other two that change).

![Fonts](https://user-images.githubusercontent.com/32712606/88467843-a9ca7980-cedb-11ea-9f17-3d6aa4ab1d9e.png)

To reproduce, create a new Avalonia project named `TestAvaloniaFonts`. Include the following (GPL-licensed) font files in a subfolder named "StandardFonts": [StandardFonts.zip](https://github.com/AvaloniaUI/Avalonia/files/4976866/StandardFonts.zip). Set the build action for each TTF file to "Embedded Resource" and replace the contents of `MainWindow.xaml` with the following:

```XML
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" Width="450" Height="250"
        x:Class="TestAvaloniaFonts.MainWindow"
        Title="TestAvaloniaFonts" FontSize="30">
  <Grid>
    <Grid.RowDefinitions>
      <RowDefinition Height="1*" />
      <RowDefinition Height="1*" />
      <RowDefinition Height="1*" />
      <RowDefinition Height="1*" />
    </Grid.RowDefinitions>
    <TextBlock FontFamily="resm:TestAvaloniaFonts.StandardFonts.?assembly=TestAvaloniaFonts#Nimbus Mono" VerticalAlignment="Center">Nimbus Mono</TextBlock>
    <TextBlock Grid.Row="1" FontFamily="resm:TestAvaloniaFonts.StandardFonts.?assembly=TestAvaloniaFonts#Nimbus Mono" FontWeight="Bold" VerticalAlignment="Center">Nimbus Mono Bold</TextBlock>
    <TextBlock Grid.Row="2" FontFamily="resm:TestAvaloniaFonts.StandardFonts.?assembly=TestAvaloniaFonts#Nimbus Mono" FontStyle="Oblique" VerticalAlignment="Center">Nimbus Mono Oblique</TextBlock>
    <TextBlock Grid.Row="3" FontFamily="resm:TestAvaloniaFonts.StandardFonts.?assembly=TestAvaloniaFonts#Nimbus Mono" FontWeight="Bold" FontStyle="Oblique" VerticalAlignment="Center">Nimbus Mono Bold-Oblique</TextBlock>
  </Grid>
</Window>
```

I tested this on Windows, macOS and Linux, and the the problem happens _only on Windows_. Any possible workarounds?

**Comment by danwalmsley** [comment]
@Gillibald any ideas?

**Comment by Gillibald** [comment]
Have to run that locally to find out what is happening. Weird that it only fails on Windows. Might be some issue with different font style handling. Will find out.

**Comment by Gillibald** [comment]
Build: 9556 can now be tested

**Comment by Deadpikle** [comment]
I was experiencing this in my project too, and CI build 9556 seems to fix the issue for me.
