### ISSUE TITLE
Menu not dismissed when clicking on main window title area on macOS using v0.9.11

### ISSUE THREAD

**Issue by boonsunsong** [AvaloniaUI/Avalonia#4371]
This is only an issue on macOS, works fine on Windows/Linux using v0.9.11

1. Create DataGrid with menu item column
2. Click menu item in the column to show the menu
3. While menu is still showing, click on the title area of the main window to move the entire app around.
4. \***Bug**\* Menu is still showing and not dismissed

![image](https://user-images.githubusercontent.com/7857138/88469395-2b9fb000-cea6-11ea-8ef2-415a922b4043.png)

**Comment by maxkatz6** [comment]
Fixed
