### ISSUE TITLE
Changing theme breaks scroll bar

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#4372]
When changing theme from default to fluent, the scroll bar is no longer visible.

## Repro

1. Replace `FluentDark` with `SimpleDark` here:

https://github.com/AvaloniaUI/Avalonia/blob/f6376e2ec0e2c143a8de35e8d2cc181b13390301/samples/ControlCatalog/App.xaml.cs#L72

2. Launch control catalog, a vertical scroll bar should be visible:

![a](https://user-images.githubusercontent.com/10765201/88469458-b48c0b00-cee9-11ea-9e3f-3098cfd21a66.png)

3. Switch to `Simple - Dark` (will do nothing, as it's already the current theme), then back to `Fluent - Dark` (now it changes). The scroll bar is not visible (it's in the visual tree, but I think the background is unset so not hit testable as well, scrolling with mouse works as usual):

![b](https://user-images.githubusercontent.com/10765201/88469491-f6b54c80-cee9-11ea-9ff1-cf1f4a5fd2b4.png)

**Comment by maxkatz6** [comment]
Is not reproducible now with switching from default to fluent and back.
