### ISSUE TITLE
Visual Studio Template Problem

### ISSUE THREAD

**Issue by mameolan** [AvaloniaUI/Avalonia#4373]
Hello,

I would just mention that the new (0.9.11) Template is not correct.
In the csproj theses entries are missing:

```
<ItemGroup>
   <Compile Update="**\*.xaml.cs">
     <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
   <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
   </AvaloniaResource>
</ItemGroup>
```

If the files and csproj entries uses **.axaml/.axaml.cs** extension I get an exception "No precompiled Xaml" found.
After changing back to **.xaml/xaml.cs** then the exception do not show up. 

Regards

**Comment by einsteinliu** [comment]
@mameolan  Thank you for providing the workaround, it is really embarrassing that when you follow all official steps to start a new project and it cannot even run.

**Comment by dmrayt** [comment]
Upgrading the Avalonia nuget packages to the pre-release version 0.10.0-preview2 also solve the problem without editing the project file.

But I'm still using 0.9.11, and the same problem occurs when I add a new Avalonia usercontrol using the template because it create axaml files and 0.9.11 doesn't found the precompiled xaml.

The Visual Studio templates are not compatible with 0.9.11 anymore.

**Comment by mameolan** [comment]
I just want to inform you that this happens only on Window 7 with VS Community.
On Windows 10 with VS Professional this does not happen somehow,
Since the Avalonia Team do not sleep the Problem is fixed with Avalonia 0.9.12 nuget version.

Regards

**Comment by einsteinliu** [comment]
@mameolan  unfortunately, it happens on my windows 10 + VS 2019 community, hopefully the nuget in vs nuget package manager will be updated to the new version soon.

**Comment by mameolan** [comment]
@einsteinliu I do not understand. Your project file should look like this:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.12" />
    <PackageReference Include="Avalonia.Desktop" Version="0.9.12" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.9.12" />
  </ItemGroup>
</Project>
```

and the filenames have to be **.axaml/axaml.cs** for the ui controls.
Perhabs you could upload a sample project or log output.
You could also try to clear the nuget package cache. Nuget has sometimes a special KI ;)

Regards

**Comment by einsteinliu** [comment]
@mameolan Thanks for your code, what I want to say is from the VS NuGet Manager market [ Avalonia for Visual Studio ](https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaforVisualStudio), it is still version 0.9.11.0

**Comment by mameolan** [comment]
@einsteinliu The version of the vs addon has nothing to do with the current version I think (@grokys correct me if I'm wrong).

Regards

**Comment by llonikko** [comment]
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
    <Compile Update="**\*.axaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.axaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.12" />
    <PackageReference Include="Avalonia.Desktop" Version="0.9.12" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.9.12" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
  </ItemGroup>
</Project>`

This works. VS 2019 Windows 10 Pro.

**Comment by llonikko** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
    <Compile Update="**\*.axaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.axaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.12" />
    <PackageReference Include="Avalonia.Desktop" Version="0.9.12" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.9.12" />
  </ItemGroup>
</Project>
```
this one works

**Comment by kekekeks** [comment]
@jkoritzinsky we might want to use a custom SDK instead of plain package references. Should also help with keeping referenced Avalonia version consistent through global.json
