### ISSUE TITLE
Broken using of colors / brushes in DataGrid for all themes

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaUI/Avalonia#4376]
Hello!

Broken use of colors / brushes in DataGrid for all themes. F. ex., used [SystemAccentColorDark2 (only fluent)](https://github.com/AvaloniaUI/Avalonia/blob/f6376e2ec0e2c143a8de35e8d2cc181b13390301/src/Avalonia.Controls.DataGrid/Themes/Default.xaml#L191) or [ThemeBackgroundBrush (default)](https://github.com/AvaloniaUI/Avalonia/blob/f6376e2ec0e2c143a8de35e8d2cc181b13390301/src/Avalonia.Controls.DataGrid/Themes/Default.xaml#L193).

Also note the use of colors in relatively dark and light themes. For example, `SystemAccentColorDark2` does not look with light theme

![pic](https://user-images.githubusercontent.com/2669927/88540675-0fbe1a80-d01c-11ea-8407-a5ebb7ccc3c2.png)

**Comment by maxkatz6** [comment]
It also uses resources that isn't defined anywhere. Probably by typo or they existed before.
```
[Binding] Warning: Dynamic resource ''ThemeControlDarkBrush'' was not found in 'avares://Avalonia.Controls.DataGrid/Themes/Default.xaml'. (DynamicResourceExtension #41560081)
[Binding] Warning: Dynamic resource ''ThemeBorderLightBrush'' was not found in 'avares://Avalonia.Controls.DataGrid/Themes/Default.xaml'. (DynamicResourceExtension #10923418)
[Binding] Warning: Dynamic resource ''ThemeBorderLightBrush'' was not found in 'avares://Avalonia.Controls.DataGrid/Themes/Default.xaml'. (DynamicResourceExtension #31201899)
[Binding] Warning: Dynamic resource ''ThemeBorderDarkBrush'' was not found in 'avares://Avalonia.Controls.DataGrid/Themes/Default.xaml'. (DynamicResourceExtension #12381635)

```

**Comment by rstm-sf** [comment]
#4502, #4534
