### ISSUE TITLE
Code obfuscation prevents decompilation about Avalonia+.netcore3.1

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#4379]
Hi,Do you know any free software that prevents decompilation,or Code obfuscation .
Now i complete my work(Avalonia+.netcore3.1),but it need to do somethig for safe.Considering that it is not very useful, I only need to do low-level shell treatment. i have used confuserEx,but it did not work.
Can you give me a way to do it for free?

**Comment by kekekeks** [comment]
CoreRT does a pretty good job on removing MSIL.

**Comment by wuzlai** [comment]
> CoreRT does a pretty good job on removing MSIL.

thank you ,i will learn and try it.
