### ISSUE TITLE
ToggleSwitchKnobStrokeOn and ToggleSwitchKnobStrokeOff keys are not defined in resources

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaUI/Avalonia#4396]
Hello!

[ToggleSwitchKnobStrokeOn](https://github.com/AvaloniaUI/Avalonia/search?q=ToggleSwitchKnobStrokeOn&unscoped_q=ToggleSwitchKnobStrokeOn) and [ToggleSwitchKnobStrokeOff](https://github.com/AvaloniaUI/Avalonia/search?q=ToggleSwitchKnobStrokeOff&unscoped_q=ToggleSwitchKnobStrokeOff) keys are not defined in resources _(It looks like it doesn't throw an exception)_

Maybe it should be `ToggleSwitchStrokeOn` and `ToggleSwitchStrokeOff`, respectively?

**Comment by maxkatz6** [comment]
> It looks like it doesn't throw an exception

DynamicResource shouldn't throw an exception, as it doesn't in WPF. 
On other hand some kind of logging would be helpful.

**Comment by maxkatz6** [comment]
By the way I am not sure about those resources, where are they from.
WinUI doesn't have any Stroke props defined for SwitchKnobOn/SwitchKnobOff - https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/CommonStyles/ToggleSwitch_themeresources.xaml
As well as in VisualStateGroups

**Comment by rstm-sf** [comment]
#4411
