### ISSUE TITLE
Is System.Drawing.Common needed ?

### ISSUE THREAD

**Issue by Nemirtingas** [AvaloniaUI/Avalonia#4399]
Hi,

I am building a cross-platform app, I used in my code the System.Drawing.Image class to read/write images.
Building the project with the .net core docker image builds 3 different System.Drawing.Image libraries for Windows/Linux/MacOS, that is troublesome as I wanted 1 app that could run everywhere.

Here's what I do:

Use System.Drawing.Image
```
Image img = new Image.FromStream(file_stream);
img.Save("test_image.jpg", ImageFormat.Jpeg);
```

Build step:
```
dotnet publish -c Release -r linux-x64 --self-contained=false
dotnet publish -c Release -r osx-x64 --self-contained=false
dotnet publish -c Release -r win-x64 --self-contained=false
mkdir -p ../release
mv bin/Release/netcoreapp3.1/win-x64/publish/* bin/Release/netcoreapp3.1/linux-x64/libSkiaSharp.so bin/Release/netcoreapp3.1/osx-x64/libAvaloniaNative.dylib bin/Release/netcoreapp3.1/osx-x64/libSkiaSharp.dylib bin/Release/netcoreapp3.1/osx-x64/libuv.dylib ../release
mv bin/Release/netcoreapp3.1/linux-x64/publish/test_app ../release/test_app.linux
mv bin/Release/netcoreapp3.1/osx-x64/publish/test_app ../release/test_app.macos
```

Starting the app on Linux make it throw an exception when running the Image code with a Gdip exception (GDI+?)
libgdiplus is already installed on my test box.

I fixed my problem by using SkiaSharp to manage my images but I've deleted System.Drawing.Common.dll from my project, removed the dependencies in the apps.deps.json and it runs fine making me wonder if Avalonia's dependency on System.Drawing is needed ?

**Comment by maxkatz6** [comment]
SkiaSharp is used by default to render Avalonia controls, so it is good idea to reuse same dependency for your tasks. 

I am not sure about System.Drawing exception tho, it looks like not related to Avalonia.

**Comment by Nemirtingas** [comment]
> 
> 
> SkiaSharp is used by default to render Avalonia controls, so it is good idea to reuse same dependency for your tasks.
> 
> I am not sure about System.Drawing exception tho, it looks like not related to Avalonia.

I've opened an issue on .NET Core's github too. But still, after removing the System.Drawing.Common.dll Avalonia works fine. Is it used somewhere ?

**Comment by Nemirtingas** [comment]
My bad, dotnet was using its own version of System.Drawing.Common.dll not the one shipped with the app.
Thats why deleting it had no effect of the app.

**Comment by maxkatz6** [comment]
By the way, it is used in some places https://github.com/AvaloniaUI/Avalonia/search?p=1&q=%22System.Drawing%22&type=

**Comment by Nemirtingas** [comment]
Maybe SkiaSharp can do the same work as System.Drawing, having 1 less dependency ?
