### ISSUE TITLE
Shader errors at startup on Windows 7

### ISSUE THREAD

**Issue by Splitwirez** [AvaloniaUI/Avalonia#4405]
So recently I had a friend of mine test a PR I was working on on Windows 7 by running the ControlCatalog after I compiled it for him, and much to my absolute shock and horror, the compiled ControlCatalog didn't even run at all - my code never even got to execute. After discovering this problem, I compiled a much simpler app, this time using 0.10.0-preview2. The apps was merely an Avalonia window containing a DockPanel, which in turn contained nothing but a TextBlock and a Button. That, too, did not run, as shown below:
![](https://cdn.discordapp.com/attachments/660426424292737043/737447173079302204/unknown.png)
![](https://cdn.discordapp.com/attachments/660426424292737043/737447514902364251/unknown.png)

In both cases, the app runs just fine on Windows 8.1, but not at all on Windows 7. I've spoken to @ahopper and @jmacato , and both suspect that this may be a Skia problem...whatever that means...

**Comment by danwalmsley** [comment]
@kekekeks

**Comment by Splitwirez** [comment]
![image](https://user-images.githubusercontent.com/34009058/89839906-d9fd5380-db3c-11ea-8e98-43c4d6d2250b.png)
@danwalmsley @kekekeks I am so sorry for the false alarm...seems like it's not Windows 7 that's at fault...

**Comment by jcummings2** [comment]
I'm encountering a similar issue - what was the fix or workaround?

**Comment by kekekeks** [comment]
`.With(new Win32PlatformOptions{AllowEglInitialization = false })`

**Comment by jcummings2** [comment]
> `.With(new Win32PlatformOptions{AllowEglInitialization = false })`

On the AppBuilder.

Thank you

**Comment by Splitwirez** [comment]
> `.With(new Win32PlatformOptions{AllowEglInitialization = false })`

*adds to notes*

**Comment by Splitwirez** [comment]
Actually, wait...what's to stop one from doing, say, `.With(new Win32PlatformOptions{AllowEglInitialization = ((!RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) || (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) && (Environment.OSVersion.Version >= new Version(6, 2, 9200, 0))))})`?

**Comment by kekekeks** [comment]
Most likely GPU-driver related. It's recommended to either disable GPU rendering or add that GPU to the blacklist.
