### ISSUE TITLE
DrawingContext.PushClip and DrawingContext.PushPreTransform interact unexpectedly

### ISSUE THREAD

**Issue by arklumpus** [AvaloniaUI/Avalonia#4408]
I have found what seems to be a _very specific_ bug, that manifests itself in two similar ways:

1. If an object is drawn on a DrawingContext with a clipping path and a transform, and then another object is drawn with a transform, then the transform on the second object is not applied.

2. If an object is drawn with a transform, and then another object is drawn with a clipping path and a transform, the first object's transform is also applied to the second object's clipping path (despite having disposed the PushedState).

In both cases, it is possible to restore the expected behaviour by removing the clipping paths, or by drawing another random object (without any clipping or transform) between the two objects.

In the following screenshot, the window on the left shows the bug, while the window on the right shows the correct behaviour restored after adding the black lines.

![image](https://user-images.githubusercontent.com/32712606/88837740-d4b51600-d1d8-11ea-95b2-99c8eaf77226.png)

The bug can be reproduced with the following Control:

```Csharp
public class TestControl : Control
    {
        public override void Render(DrawingContext context)
        {
            Example1(context);
            Example2(context);
        }

        void Example1(DrawingContext context)
        {
            Matrix translate = Matrix.CreateTranslation(200, 150);
            Matrix rotate = Matrix.CreateRotation(Math.PI / 4);

            using (context.PushClip(new Rect(125, 125, 50, 50)))
            {
                using (context.PushPreTransform(translate.Invert() * rotate * translate))
                {
                    context.FillRectangle(Brushes.Red, new Rect(100, 100, 200, 200));
                }

                //The random draw operation could go here, as well.
            }

            //Random draw operation: uncomment the following line to restore expected behaviour.
            //context.DrawLine(new Pen(Brushes.Black), new Point(0, 0), new Point(100, 100));

            using (context.PushPreTransform(translate.Invert() * rotate * translate))
            {
                context.FillRectangle(Brushes.Blue, new Rect(225, 125, 50, 50));
            }
        }

        void Example2(DrawingContext context)
        {
            Matrix translate = Matrix.CreateTranslation(200, 350);
            Matrix rotate = Matrix.CreateRotation(Math.PI / 4);

            using (context.PushPreTransform(translate.Invert() * rotate * translate))
            {
                context.FillRectangle(Brushes.Blue, new Rect(225, 325, 50, 50));
            }

            //Random draw operation: uncomment the following line to restore expected behaviour.
            //context.DrawLine(new Pen(Brushes.Black), new Point(0, 200), new Point(100, 300));

            using (context.PushClip(new Rect(125, 325, 50, 50)))
            {
                using (context.PushPreTransform(translate.Invert() * rotate * translate))
                {
                    context.FillRectangle(Brushes.Red, new Rect(100, 300, 200, 200));
                }
            }
        }
    }
```

I tested this on Avalonia 0.9.11, 0.9.12, 0.10.0-preview1 and 0.10.0-preview2 on Windows, as well as 0.10.0-preview2 on Ubuntu.

Am I using the PushClip and PushPreTransform in the wrong way?

**Comment by MarchingCube** [comment]
@kekekeks This is quite an interesting case:

- `PopClip` causes canvas transform to be restored as well, but `Transform` stays the same on the drawing context.
- It tries to draw this rectangle with a new transform. It also happens that this transform is the same as the one that was used to draw previous rectangle. But Skia canvas already have a different transform and https://github.com/AvaloniaUI/Avalonia/blob/master/src/Skia/Avalonia.Skia/DrawingContextImpl.cs#L528 will prevent transform from being updated.

I wonder - do we really need that equality check in there?

**Comment by kekekeks** [comment]
>I wonder - do we really need that equality check in there?

I think the answer to that would be a relevant benchmark.

**Comment by MarchingCube** [comment]
We don't have a decent setup for benchmarking actual backends. I guess it should be doable now.
