### ISSUE TITLE
Implement WindowStyle for window

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#441]
For usual and dialog windows: https://msdn.microsoft.com/en-us/library/system.windows.windowstyle(v=vs.110).aspx#

**Comment by kekekeks** [comment]
It's not x-plat, there is no equivalent for `ThreeDBorderWindow` and `ToolWindow` in X11 and Cocoa.

Use `HasSystemDecorations` property to remove window border.

**Comment by MihailsKuzmins** [comment]
Now `HasSystemDecorations` is deprecated, so use `SystemDecorations`.

```
SystemDecorations="None"
```
