### ISSUE TITLE
Does anyone know the webview and rich text edit box for Avalonia? i need them.

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#4410]
Does anyone know the webview and rich text edit box for Avalonia? 
About webview ,i find "https://github.com/VitalElement/CefGlue.Core/issues",but i can not use it in Avalonia 0.9,and it is old.Maintenance updates are rare.I do not konw the reason,I wonder if this webview control exists ,my avalonia project need webview.
About rich text edit box,i can not find some demo.Can you help me.

**Comment by maxkatz6** [comment]
I believe CefNet should works fine as WebView
https://github.com/CefNet/CefNet

**Comment by maxkatz6** [comment]
And not sure about RichEditBox, but you can take a look at https://github.com/AvaloniaUI/AvaloniaEdit

**Comment by wuzlai** [comment]
> And not sure about RichEditBox, but you can take a look at https://github.com/AvaloniaUI/AvaloniaEdit

Hi,handsome, I download  'https://github.com/CefNet/CefNet' and 'https://github.com/AvaloniaUI/AvaloniaEdit',but this 2 projects does not run.it has many  error.
About CefNet,there are many problems.
such as 'Reference to undefined class 'CefNet.CefV8Exception'	CefNet	C:\Users\Wuzl\Downloads\CefNet-master\CefNet\EXEC	1	'
' ImmutableAttribute "is not a feature class CefNet (Standard2.1) C:\Users\Wuzl\Downloads\ cefnet-master \CefNet\ Native\Types\cef_cookie_access_filter_t.cs 48'

![image](https://user-images.githubusercontent.com/7692353/88874534-e1298500-d251-11ea-9a82-724706cebfe0.png)
![image](https://user-images.githubusercontent.com/7692353/88874548-ebe41a00-d251-11ea-8c76-af53db092aa4.png)
![image](https://user-images.githubusercontent.com/7692353/88874588-ff8f8080-d251-11ea-8bb8-41bc2489f805.png)



About AvaloniaEidit.there are several problems.
such as 'The severity code states that the project file line does not display status
Error CS0535 'MockPlatformRenderInterface not implement interface members "IPlatformRenderInterface. CreateFormattedText (string, Typeface, double, TextAlignment, TextWrapping, Size, IReadOnlyList < FormattedTextStyleSpan >) "AvaloniaEdit. Tests at C: \ Users \ Wuzl \ Downloads \ AvaloniaEdit - master (1) \ AvaloniaEdit - master \ test \ AvaloniaEdit Tests \ AvaloniaMocks \ MockPlatformRenderInterface cs activities'
'The severity code states that the project file line does not display status
Error CS0246 could not find type or namespace name "IEmbeddableWindowImpl" (missing using directive or assembly reference?) Avaloniaedit.tests C:\Users\Wuzl\Downloads\ AvalonIaEdit-master (1)\AvaloniaEdit-master\ Test \ avaloniaEdit.tests \AvaloniaMocks\ MockWindowingPlatform-cs 23 activity'


![image](https://user-images.githubusercontent.com/7692353/88874486-c3f4b680-d251-11ea-9e8b-aa06dd2f9391.png)

![image](https://user-images.githubusercontent.com/7692353/88874507-cfe07880-d251-11ea-8b48-df7b249a4a98.png)


Neither of these two sets of code can run directly successfully? Have you come across it? Or can you send a copy of the code that you were able to run successfully? Urgent, thank you

**Comment by maxkatz6** [comment]
You don't need to download and rebuild those projects, they both have NuGet packages, that you can install into your application.
https://www.nuget.org/packages/CefNet.Avalonia/
https://www.nuget.org/packages/Avalonia.AvaloniaEdit/0.9.0-preview1
Note, that you probably need 0.9.0-preview1 version of AvaloniaEdit and not stable 0.8.0 (depending on what Avalonia version you are using in your application)

If you still need use source code directly or have another issues with those packages, you should create new issues in their repositories.
FYI @danwalmsley @vmas

**Comment by wuzlai** [comment]
> Avalonia.AvaloniaEdit/0.9.0-preview1

Oh,very good, I use version of avalonia 0.9.10. Can you show me the use guide for CefNet.Avalonia and Avalonia.AvaloniaEdit. How  do I use it directly in the project?  What kind of method should be used? Or labels?

**Comment by maxkatz6** [comment]
Both projects have sample projects
https://github.com/CefNet/CefNet/tree/master/AvaloniaApp
https://github.com/AvaloniaUI/AvaloniaEdit/tree/0.9.0-preview1/src/AvaloniaEdit.Demo

Note, that they use ProjectReference instead of Nuget+PackageReference.

**Comment by wuzlai** [comment]
> 这两个项目都有示例项目
> [https://github.com/CefNet/CefNet/tree/master/AvaloniaApp ](https://github.com/CefNet/CefNet/tree/master/AvaloniaApp)
> https://github.com/AvaloniaUI/AvaloniaEdit/tree/0.9.0-preview1/src/AvaloniaEdit.Demo
> 
> 请注意，它们使用ProjectReference而不是Nuget + PackageReference。

thank you,i will try it . i use Nuget.

**Comment by pr8x** [comment]
There is a giant PR pending on the cefglue repo. It supports latest Avalonia and all kinds of other features (Like JavaScript evaluation). I wonder if/when they will merge this.

https://gitlab.com/xiliumhq/chromiumembedded/cefglue/-/merge_requests/2

**Comment by wuzlai** [comment]
In order to Help others,I  attach the correct solution about the webview for avalonia. i have run successfully.
https://github.com/CefNet/CefNet/issues/19#event-3650896768.
About rich text editors, i still does not find.

**Comment by RusselRillema** [comment]
For any future readers... 

With regards to the webview control, I have use [dotnetbrowser](https://teamdev.com/dotnetbrowser/)
So far I am very happy with it!
