### ISSUE TITLE
Gridsplitter looks ugly in 0.10-preview2

### ISSUE THREAD

**Issue by ShadowDancer** [AvaloniaUI/Avalonia#4412]
![](https://files.gitter.im/547b1838db8155e6700d97d7/hoT1/image.png)

![](https://files.gitter.im/547b1838db8155e6700d97d7/TL5Y/image.png)

Old splitter looks much better. Also it is much thicker.

This is caused by:
```
    <Setter Property="MinWidth" Value="6" />
    <Setter Property="MinHeight" Value="6" />
```
in Avalonia.Themes.Default.GridSplitter.xaml

**Comment by danwalmsley** [comment]
@ShadowDancer isnt the only difference that it is thicker?

**Comment by FoggyFinder** [comment]
Tbh, I like the new one more

**Comment by ShadowDancer** [comment]
@danwalmsley it's thicker, also it does not have three dots at middle (but that's minor thing). For old one you could make it 1px wide, for new one you cannot.

**Comment by ShadowDancer** [comment]
> Tbh, I like the new one more

Maybe with issue title I meant that UI with such thick splitters look ugly.

**Comment by danwalmsley** [comment]
@ShadowDancer its a bit of a mystery then...
![image](https://user-images.githubusercontent.com/4672627/88960247-9d4a7600-d279-11ea-9bac-20d0301795d6.png)

The template was not changed... other than resource colours.

**Comment by maxkatz6** [comment]
@danwalmsley as I understand, it's not related to the Fluent theme. Probably something another impacted on Default one as well.

**Comment by danwalmsley** [comment]
ah probably here:
https://github.com/AvaloniaUI/Avalonia/commit/00263f71e4b7e3a9acb93444e07b10b5e35fa1a4#diff-3ed3c875331dc3d642e31a6be9e88c7d

**Comment by danwalmsley** [comment]
didnt realise we had made major changes...

**Comment by MarchingCube** [comment]
@ShadowDancer From which version is this old picture?

And both old and new one are still fully customizable as you can just override the template. 

Finding a good default is tricky:
- WPF by default will be invisible (it has no min width/height).
- UWP has no grid splitter
- One from Windows Community Toolkit is even thicker (https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp.UI.Controls/GridSplitter/GridSplitter.xaml#L22) as it is 16px wide/high.

We might provide an alternative style with dots/lines perhaps.

**Comment by ShadowDancer** [comment]
Old picture is from 9.10. Indeed they are customizable and I had to override template, but I've created this issue to make avalonia better and more stable. This along with other style changes does not look as if it was planned change, rather bug or oversight.

In my personal opinion I'd change min width/height to 1 or 0, to keep it backwards compatible with existing apps.

**Comment by ShadowDancer** [comment]
@maxkatz6  @danwalmsley should I create PR to revert it? We want version with dots at middle, or the one like fluent just thinner? Or maybe we want something with 3 strips like the in linked picture?

**Comment by danwalmsley** [comment]
We shouldn't revert the commit, the old grid spitter had loads of bugs, we just need to change the template.

**Comment by ShadowDancer** [comment]
I mean revert changes to visuals, not revert entire commit.

**Comment by MarchingCube** [comment]
I would be fine with removing min width/height and just have WPF behavior. So then it is up to the user to configure it.
Every app has pretty much own approach to this (my app is using transparent ones for example) but usually you setup a style once and move on :)

Personally I found old grid splitter (with three dots) as one of the most ugly parts of Avalonia for a long time :)

**Comment by ShadowDancer** [comment]
@MarchingCube yep, the point is that you do not want to do it every time new avalonia is released, right? There's reason people are using default theme and not creating their own from scratch ;)

**Comment by maxkatz6** [comment]
For future we definitely need thicker gridsplitter for mobile, probably using some kind media-query to detect device type. 
For now I see it as thin splitter for default theme, and thick splitter for fluent theme, but with compact option (using Compact.xaml).

What do you think about it?

**Comment by ShadowDancer** [comment]
@maxkatz6 makes sense, but maybe there should be separate theme for mobile? I think fluent goes in that way.

I've created pr to fix width/height. I think something like dots is important from the UI standpoint, as it tells user that this bar can be manipulated (unlike rectangles).
