### ISSUE TITLE
DatePicker ArgumentOutOfRange

### ISSUE THREAD

**Issue by Oxc3** [AvaloniaUI/Avalonia#4414]
When opening DatePicker, an ArgumentOutOfRange exception occurs when formatting DateTimePickerPanelType.Month. The exception occurs due to the month having a value of 2 and FormatDate.Day being 30. I suspect this only occurs on Dates 30 & 31

**Comment by danwalmsley** [comment]
@amrx

**Comment by danwalmsley** [comment]
@amwx

**Comment by amwx** [comment]
@Oxc3 Can you provide a little more context on how this occurred (i.e. code)?
Normal behavior won't allow invalid days based on the month/year in .net DateTime/DateTimeOffset and there is some logic to ensure if you switch from the 31st in one month to February, for example, that the date is moved correctly to avoid this, but I may have missed something. I'll take a look and see what's going on...

**Comment by Oxc3** [comment]
Sorry for the late response. I tested it today and it is working again, which added to my speculation it was the day causing the error. When opening the DatePicker in debug with a system date of 30 or 31st the exception occurs on line 491 of DateTimePickerPanel.cs.

return new DateTime(FormatDate.Year, value, FormatDate.Day).ToString(ItemFormat); where FormatDate.Year = current date, value = 2 and FormatDate.Day = current day (30 or 31). Because the moth = February(2) and the day is 30 or 31 DateTime throws the range exception

**Comment by Oxc3** [comment]
this only happens when you click the DatePicker to open the scroll list. The display is fine.

**Comment by amwx** [comment]
Was able to repro it, and I think I fixed it. Something seemingly minor that I overlooked.

**Comment by Oxc3** [comment]
That was it. I tried the changes and I cannot break it. Thanks.
