### ISSUE TITLE
Feature: alternative "using:" syntax to include namespace to XAML file

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#4417]
Currently Avalonia supports WPF'style namespaces in XAML files, using clr-namespace with assembly.
With that we need to provide long path to assemblies, if namespace isn't contained in current one.
UWP and XF supports another syntax, using "using:" keyword (for UWP it is only one available syntax).
With this we don't need to provide assembly, instead it will internally search for namespace in referenced projects and packages.

Proposal syntax:
```xaml
<Styles xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:sys="using:System"
        xmlns:controls="using:MyNamespaceInAnotherAssembly">
  <Style Selector="controls|MyControl" />
</Window>
```

UWP docs:
https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-namespaces-and-namespace-mapping#mapping-custom-types-to-xaml-namespaces-and-prefixes

Xamarin Forms docs:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/namespaces#declaring-namespaces-for-types

**Comment by maxkatz6** [comment]
In UWP it also works fine, when one namespace is used in multiple assemblies.
For instance, I can reference Microsoft.UI.Xaml package and use controls from its with namespace.
And then I can create new UserControl in local assembly but with same namespace - Microsoft.UI.Xaml.Controls, and reuse same namespace definition:
```xaml
<Page xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:controls="using:Microsoft.UI.Xaml.Controls">
  <controls:NavigationView >
    <controls:NavigationView.Content>
       <controls:CustomControl />
    </controls:NavigationView.Content>
   </controls:NavigationView >
</Page>
```
```csharp
namespace Microsoft.UI.Xaml.Controls
{
    public class CustomControl : UserControl
    {
        public CustomControl()
        {
            Content = new Border
            {
                Background = new SolidColorBrush(Colors.Azure),
                Width = 100,
                Height = 100,
            };
        }
    }
}
```

**Comment by PieroCastillo** [comment]
yes, it should be exist, but that feature must be in the xaml-compiler, 'cause if that executes in the run-time would be very slow

**Comment by jkoritzinsky** [comment]
I added this to the WinUI prototype Xaml compiler based on XamlX, and this is pretty easy to add to the XamlX library.

**Comment by FoggyFinder** [comment]
maybe additional to `using` keyword it is possible to add `open` as well? 

```xml
xmlns:controls="open:Microsoft.UI.Xaml.Controls"
```

**Comment by jkoritzinsky** [comment]
@FoggyFinder what are the semantics of the `open` syntax and how do they differ from the other syntax?

**Comment by FoggyFinder** [comment]
I propose `open` as a synonym to `using` with exactly the same meaning.

Context: 

`open` is import declaration in F#.

[Import Declarations: The open Keyword](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/import-declarations-the-open-keyword)

C#
```csharp
using System.IO;` 
```

F#
```fsharp
open System.IO
```

**Comment by danwalmsley** [comment]
@jkoritzinsky is it possible to assume xmlsn:test="System.Diagnostic" was a clr namespace?

**Comment by maxkatz6** [comment]
"using:" is well known UWP and XF syntax not only for C#, but also for F#/VB/C++ projects as well.
Need to mention, that "using:" isn't just a synonym for "clr-namespace:", but also provides some benefits with automatic assemblies lookup, when "clr-namespace" looks for current assembly or fails, if it wasn't provided explicitly.
On other hand we can just extend "clr-namespace:", so no need to maintain new syntax.

`xmlsn:test="System.Diagnostic"` could be parsed correctly in XamlX, but it will be completely new syntax for XAML language, and namespace name [should be a valid URI](https://www.w3.org/TR/xml-names/#concepts), when "System.Diagnostic" doesn't looks like (not sure though).

**Comment by FoggyFinder** [comment]
> "using:" is well known UWP and XF syntax not only for C#, but also for F#/VB/C++ projects as well.

Just because UWP doesn't care about anything except C#. To use it properly (release mode = .net native) you have to edit gatekeeper config manually. At least for F# for sure. I doubt the situation is better for VB ([which is literally dead for Microsoft](https://devblogs.microsoft.com/vbteam/visual-basic-support-planned-for-net-5-0/)) and C++/CLI.

Also not all developers who use Avalonia have previous UWP/XF/WPF background, besides there are features that specific only to Avalonia already (at least I think so).

From the start Avalonia has better F# support than the rest of .net - ui - frameworks. Providing one alternative synonym for keyword doesn't sound like a big deal but it allows write more idiomatic code.

**Comment by maxkatz6** [comment]
I love it. Done in latest 0.10-preview6.
![image](https://user-images.githubusercontent.com/3163374/97792301-e2e94880-1bb2-11eb-907e-e3f9506d74a2.png)

**Comment by ClassyCircuit** [comment]
How do you use this? Why is there no documentation?

```
<UserControl xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:views="using:Abc.UI.Views"
        x:Class="Abc.UI.Views.MainView">
	<DockPanel>
		<DockPanel>
			<!-- This doesn't work. Namespace is:  Abc.UI.Views.Sidebar -->
			<views:Sidebar.ActivityBarView DockPanel.Dock="Left" Width="50"/>

			<!-- This also doesn't work. -->
			<views:ActivityBarView DockPanel.Dock="Left" Width="50"/>
		</DockPanel>
	</DockPanel>
</UserControl>

```

I don't understand how to resolve views, if they are grouped under directories, like this:

```
- Abc.UI
 - Views
  - Sidebar
   - ActivityBarView.axaml  
  - MainView.axaml
```

**Comment by timunie** [comment]
@ClassyCircuit I believe Sidebar folder adds a new Namespace in your case? Either move SideBar into Views namespace or add `xmlns:SidebarViews="using:Abc.UI.Views.Sidebar"`

**Comment by ClassyCircuit** [comment]
@timunie Yes, sidebar folder adds another namespace. I am providing the root folder for the views and I was expecting that "using" statement would allow searching for namespaces within it.
 I thought "using" replaced "clr-namespace", so that it actually searched in the namespaces under it. What is the usecase for the "using" statement here then?

**Comment by timunie** [comment]
https://docs.avaloniaui.net/docs/basics/user-interface/introduction-to-xaml

**Comment by ClassyCircuit** [comment]
From that link it seems there is no difference between "using" and "clr-namespace", is that correct? Why do we need "using" then?

**Comment by timunie** [comment]
iirc clr-ns requires Assembly to be specified when not in your main prj, but using does not require it. Other than that these are more or less the same. 

> Why do we need "using" then?
Why not? I like that syntax more tbh. For me it's shorter to write and easier to remember.
