### ISSUE TITLE
Mobile backends need to be updated to new dpi scaling system

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#442]
I've merged the `dpi-aware` branch to master, but @kekekeks will need to update the mobile ports to use the new per-window DPI scaling system.

**Comment by jkoritzinsky** [comment]
Have we implemented this yet? I think we have, but that's not my area of expertise.

**Comment by kekekeks** [comment]
I don't quite remember when it was fixed, but I think it was working fine with DPI when I was doing yet-another-overhaul for mobile platforms this February.
