### ISSUE TITLE
ProgressBar causes Segmentation fault

### ISSUE THREAD

**Issue by JemmyHighman** [AvaloniaUI/Avalonia#4421]
New project with the following xaml 
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        x:Class="AvaloniaPreview.Views.MainWindow"
        Height="550"
        Width="450">
        <ProgressBar IsIndeterminate="True"/>
</Window>
```
throws **Segmentation fault (core dumped)** right after launch

Avalonia 10 prev 2 ( FluentDark )
Ubuntu 20.04

**Comment by kekekeks** [comment]
I'm not sure how we've achieved a segfault from a completely managed control, probably reentrancy or a bug in SkiaSharp.

@jmacato

**Comment by jmacato** [comment]
Yeah i encounter this sporadically... seems to be we're passing invalid values to skia again?

**Comment by jmacato** [comment]
ah seems to be a variant of https://github.com/mono/SkiaSharp/issues/1421 https://github.com/AvaloniaUI/Avalonia/issues/4319 goshdarnit...

**Comment by kekekeks** [comment]
So, apparently, ProgressBar pushes a round rect clip for 0,0,200,4 with the corner radius of 3 and Linux NVIDIA blob doesn't particulary like that for some reason, which results in a segfault in the driver.

**Comment by kekekeks** [comment]
Actually, it happens with any rectangle size. Apparently our clipping is too complex for Skia+NVIDIA to handle.

**Comment by kekekeks** [comment]
Apparently, nvidia driver doesn't like to be used with a stencil buffer when it was previously was called from multiple threads (not at the same time, just multiple different ones). I don't have an explanation for this phenomena, but using a single thread for the render timer seems to fix the crash.

**Comment by mattleibow** [comment]
@kekekeks Does this look to be a bug in skia/SkiaSharp, the Nvidia drivers, a combo or something else?

**Comment by kekekeks** [comment]
Most likely Nvidia driver, since it works fine with MESA.
