### ISSUE TITLE
Does avalonia support rich text editors and WebViews

### ISSUE THREAD

**Issue by fengyinyong** [AvaloniaUI/Avalonia#4428]
Hi there:
    I have read the avalonia docs,But I do not find rich text deidors control and webview control.
Therefore, Does avalonia support rich text editors and WebViews.Do you have any demos.
My Team are working on a project with Avalonia and hope that this avalonia will have a better future。

**Comment by maxkatz6** [comment]
Duplicate
https://github.com/AvaloniaUI/Avalonia/issues/4410
