### ISSUE TITLE
System.drawing.Bitmap to Avanlonia.Media.Imaging.Bitmap

### ISSUE THREAD

**Issue by DhananjayHuidrom** [AvaloniaUI/Avalonia#4429]
How to convert System.Drawing.Bitmap to Avalonia.Media.Imaging.Bitmap ?
How to display a System.Drawing.Bitmap to Avalonia Image control?

**Comment by kekekeks** [comment]
Easiest and most stable way - through saving to a MemoryStream and loading that back. You can also create the bitmap from data pointer, but you need to be careful with pixel formats

**Comment by DhananjayHuidrom** [comment]
Using MemoryStream is time consuming in process. Let me know how to create the bitmap from data pointer.
