### ISSUE TITLE
Slider Min/Max Value is not recognized in Xaml

### ISSUE THREAD

**Issue by mameolan** [AvaloniaUI/Avalonia#4430]
Hello,

in Version 0.9.12 if you set Minimum and Maximum in xaml:

```
 <Slider  Orientation="Horizontal"  Width="150"
                                  Minimum="0" Maximum="255"
                                  Value="255" />
```
and move the thumb to the right, then the value is 100.
If you set the min/maximum in code i.e. in the OnTemplateApplied
function then the maximum is 255.

Regards

**Comment by maxkatz6** [comment]
Hi!
Can you check this with 0.10.0-preview2 ?
Slider code was updated for a bit, so that issue is probably fixed now.

**Comment by mameolan** [comment]
Hello @maxkatz6 on Version  0.10.0-preview2 it is working.
