### ISSUE TITLE
Displaying large(r) text files in a TextBlock leads to high memory use and very slow performance

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/Avalonia#4434]
## Environment

* Windows 10 1909
* Visual Studio 16.6.5
* i7 processor/16 GB RAM

## Problem

Sometime between CI Build 8974 (I think; it's what my live app is using and running OK on) and 9703, text performance on display has dramatically decreased.

Basically, if you load a large text file (or probably any large amount of text), performance is really slow. Memory climbs up a bunch (repro uses 289 MB for a 36 KB text file), there are several GCs during the display process, and generally it's just slow. My use case is displaying a license file, which probably can get very large if the app is very extensive.

Here is what a diagnostic session looks like on allocations:

![diagsession](https://user-images.githubusercontent.com/5092399/89236757-6cdb4280-d5bf-11ea-8de8-44df2bf28fff.jpg)

![diagsession2](https://user-images.githubusercontent.com/5092399/89236857-b3c93800-d5bf-11ea-8897-4f73116833a4.jpg)

## Repro

https://github.com/Deadpikle/AvaloniaBugs/tree/master/LargeTextFilePerf

**Comment by Gillibald** [comment]
No idea why the performance is worse in current master it should be better than before. Will have a look what we can improve here.

**Comment by Gillibald** [comment]
Keep in mind TextBlock isn't meant to be used to display large text because it does no virtualization.

**Comment by Gillibald** [comment]
Okay. I have found something. Getting that fixed asap. Thanks for your testing 👍

**Comment by Deadpikle** [comment]
Fixed in #4437 (merged into master on 5 August)

**Comment by Deadpikle** [comment]
@Gillibald 

I'm experiencing this again. Same thing -- loading a large file and text wrapping it. 
![Screenshot 2021-09-09 204844](https://user-images.githubusercontent.com/5092399/132780944-23f37571-b5ec-444d-9a4f-38c39469ff3d.png)

Some time between 0.10.999-cibuild0014103 and 0.10.999-cibuild0015575.

File: 
[Licenses.txt](https://github.com/AvaloniaUI/Avalonia/files/7140489/Licenses.txt)

Code:

```xml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="DotPurple.Avalonia.Views.Dialogs.AboutDialog"
             Width="400"
             Height="400">
  <Border Classes="ContentDialogBorder">
    <Grid MaxHeight="400"
          RowDefinitions="Auto, *, Auto, Auto, Auto">
      <TextBlock Text="About DotPurple"
                 Name="AboutTitle"
                 FontSize="18"
                 Grid.Row="0"/>
      <ScrollViewer Grid.Row="1">
        <StackPanel Orientation="Vertical"
                    VerticalAlignment="Stretch">
          <TextBlock TextWrapping="Wrap"
                     HorizontalAlignment="Left"
                     MaxWidth="350"
                     Margin="5,0,55,0">
        [omitted for brevity]
          </TextBlock>
          <TextBlock Text="Open Source Licenses"
                 FontWeight="Bold"
                     TextWrapping="Wrap"
                 FontSize="14"
                 Margin="0,2,55,2" />
          <TextBlock Name="LicensesText"
                     TextWrapping="Wrap"
                     HorizontalAlignment="Stretch"
                     MaxWidth="350"
                 Margin="0,2,2,2">
          </TextBlock>
        </StackPanel>
      </ScrollViewer>
      <TextBlock Grid.Row="2"
                 HorizontalAlignment="Center"
                 VerticalAlignment="Bottom"
                 FontSize="14"
                 FontWeight="Bold"
                 TextWrapping="Wrap"
                 TextAlignment="Center"
                 Margin="5,5,5,5">
        [omitted for brevity]
      </TextBlock>
      <TextBlock Grid.Row="3"
                 HorizontalAlignment="Center"
                 VerticalAlignment="Bottom"
                 FontSize="14"
                 FontWeight="Bold"
                 Margin="5,5,5,5">
        © 2020
      </TextBlock>
      <Button Content="Close"
              Grid.Row="4"
              Width="75"
              Classes="AccentButton ShadowButton"
              HorizontalAlignment="Right"
              Command="{Binding $parent[UserControl].CloseAction}"/>
    </Grid>
  </Border>
</UserControl>

```

```csharp
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using DotPurple.Avalonia.Controls;
using DotPurple.Avalonia.Helpers;
using DotPurple.Avalonia.Interfaces;
using DotPurple.Helpers;
using System;
using System.IO;
using System.Runtime.InteropServices;

namespace DotPurple.Avalonia.Views.Dialogs
{
    public class AboutDialog : ContentDialog
    {
        private TextBlock _titleText;
        private TextBlock _licenseText;

        public AboutDialog()
        {
            this.InitializeComponent();
            try 
            {    
                if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                {
                    var licensePath = Path.Combine(FileUtilities.GetFullBaseDirectory(), "Licenses.txt");
                    using (TextReader tr = new StreamReader(licensePath))
                    {
                        string myText = tr.ReadToEnd();
                        _licenseText.Text = myText;
                    }
                }
                else 
                {
                    using (TextReader tr = new StreamReader(@"Licenses.txt"))
                    {
                        string myText = tr.ReadToEnd();
                        _licenseText.Text = myText;
                    }
                }
            } 
            catch (Exception e) 
            {
                   // ommitted
            }
            if (_titleText != null)
            {
                _titleText.Text = string.Format("About DotPurple {0}", Utilities.GetAppVersion());
            }
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
            _licenseText = this.Find<TextBlock>("LicensesText");
            _titleText = this.Find<TextBlock>("AboutTitle");
        }

    }
}
```

**Comment by Gillibald** [comment]
I wonder what might have changed. Will have a deeper look.

**Comment by Deadpikle** [comment]
@Gillibald 

As far as I can tell, this works in `0.10.999-cibuild0015044-beta` and is broken in `0.10.999-cibuild0015047-beta`. ([page with commits here](https://github.com/AvaloniaUI/Avalonia/commits/master?before=4f3a1e5d2fcd5a0b202dc85dbc21edc3079f7316+1201&branch=master)). I believe this means this broke in PR #6211 (https://github.com/AvaloniaUI/Avalonia/pull/6211).

**Comment by Gillibald** [comment]
Let me test your scenario against https://github.com/AvaloniaUI/Avalonia/pull/4893
I am currently in the process of finishing up that work

**Comment by Deadpikle** [comment]
@Gillibald  I just re-tested using the latest master, `0.10.999-cibuild0018838-beta` on .NET 5 in both my sample test case and in my actual app. Works great again. Let's assume that it works until otherwise noted. :) Thank you again for all your great work.

**Comment by Gillibald** [comment]
Hey thanks that's good news. I will improve this even further until we release the next major version. Current plan is to introduce a cache that makes sure text is only shaped once between multiple measures so text wrapping of large text will perform even better.
