### ISSUE TITLE
UserControls with custom Render() always render, even if clip rect is empty.

### ISSUE THREAD

**Issue by pgh-arm** [AvaloniaUI/Avalonia#4435]
Controls that do custom rendering, still seem to get rendered even when they aren't visible. i.e. When they look like they have an empty clip rect. This is particularly problematic for complex renders, like multiple graphing controls that process and display lots of data. Further to this, the clip rectangle reported by _this.TransformedBounds.Value.Clip_ is not always up to date at the point the render call takes place (it sometimes appears to lag)...

Placing a scrollable stack of custom controls in a fixed space can be used to move the user controls offscreen and see that their Render() functions are still called.

```
		<ScrollViewer Name="graphScroll" Grid.Column="0" Grid.Row="0" VerticalScrollBarVisibility="Visible">
				<StackPanel Name="processStack">
<!-- insert several instances of a user control -->
				</StackPanel>
		</ScrollViewer>
```

I inserted the following at the top of the user control's Render() function to display the clip rect state and attempted to use that to prevent unnecessary drawing. Which sort of works...

```
	if ( this.TransformedBounds.HasValue && this.TransformedBounds.Value.Clip.IsEmpty )
	{
		System.Console.WriteLine("*Clip: {0} - TransformBounds Clip={1}", this.Tag, this.TransformedBounds.Value.Clip);
		return;
	}
	System.Console.WriteLine("Draw: {0} - TransformBounds Clip={1}", this.Tag, this.TransformedBounds.Value.Clip);
```

...However, the transformed clip rect is not up-to date when the drawing takes place. It appears to lag the render call - this can be reproduced by very-quickly dragging the scroll bar to move the contents of the stack:

Visual behaviour: Clipping up-to-date at time of render:

![image](https://user-images.githubusercontent.com/48486715/89281718-64781b80-d642-11ea-8d52-36b794e6c7dd.png)

Clipping out-of-date at time of render (quick scrollbar motion)

![image](https://user-images.githubusercontent.com/48486715/89281804-85d90780-d642-11ea-970e-b869aca557ad.png)

Question: If this is not a suitable method of preventing unnecessary drawing, then what is the ideal way to achieve this?

**Comment by kekekeks** [comment]
I think the UI thread doesn't check for the current clip since it doesn't do any actual rendering and just saves drawing commands to be replayed on the render thread. I don't think we can even make such decisions on the UI thread because of the [upcoming render-thread animations](https://twitter.com/AvaloniaUI/status/1287788277072891906) support since the final clip rect will be computed on the render thread.

The current fastest way of doing custom rendering is [using custom drawing ops](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/RenderDemo/Pages/CustomSkiaPage.cs) that get executed directly on the render thread. If those gets called when the area is clipped out, that's a bug for certain.


`TransformedBounds` will be probably removed somewhere in 0.11-0.12 timeframe, since it was always a hack.

**Comment by pgh-arm** [comment]
Ah, thank you. It was not obvious that Render clipping was deferred until later. I will test the custom drawing op approach and report back...

**Comment by pgh-arm** [comment]
Using a custom drawing op works: Clipping now appears to work properly, off-screen graphs do not render; but the render thread now continuously throws a series of exceptions:

```
[Visual] Exception in render loop: "System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess()
   at Avalonia.AvaloniaObject.GetValue(AvaloniaProperty property)
   at Avalonia.AvaloniaObject.GetValue[T](AvaloniaProperty`1 property)
   at Avalonia.Skia.DrawingContextImpl.CreatePaint(IPen pen, Size targetSize)
   at Avalonia.Skia.DrawingContextImpl.DrawLine(IPen pen, Point p1, Point p2)
```

These seem to be originating from passing Avalonia.Media.Pen() instances to context.DrawLine().  If I create my own Pen class implementation and pass that instead, then this problem goes away... 

Is there a different Pen implementation I should be using within the ICustomDrawOperation's Render call?

**Comment by Gillibald** [comment]
You need to call ToImmutable to get a thread safe version of your pen

**Comment by pgh-arm** [comment]
Ah, thank you.
