### ISSUE TITLE
<window>Screens.Primary.WorkingArea incorrect values on MacOS

### ISSUE THREAD

**Issue by FloridaMatt** [AvaloniaUI/Avalonia#4445]
Ref MacOS Catalina 10.15.6, Avalonia 0.9.12  

The vertical Position value being reported is too large (57 on my 2014 MacBook Air.

As a result, setting the window's position, width and height to the WorkingArea values places the window outside the actual working area.

MacOS responds to this by reducing the window's dimensions to 100x100, placing it down in the lower left corner of the screen.

This is related to issue #3404

**Comment by maxkatz6** [comment]
Ping me or @danwalmsley if this issue is still reproducible. Desktop scaling was fixed in 0.10 on mac.
