### ISSUE TITLE
NativeMenuItem support for underscore inconsistent

### ISSUE THREAD

**Issue by ChadNedzlek** [AvaloniaUI/Avalonia#4450]
If I create a <NativeMenu> in an attempt to share my UI between Windows and Mac in a reasonable way, and place a <NativeMenuBar> in the UI, the method to declare Alt accelerators causes issues.  I want the menus to be easily navigable by keyboard, so I named them things like "_File". On windows, that does exactly what I'd expect, the menu's just say "File" and Alt+F opens it.  On OSX, the acual text "_File" is shown.  I've included some images below.

I don't think there is any OSX support for such a concept, so it seems like the underscore character should just be stripped out.  Either that or I need to have separate Header information for each OS, which is a lot of overhead.

### OSX
![image](https://user-images.githubusercontent.com/11790765/89571537-b05ec800-d7dc-11ea-9356-26d147746e8e.png)

### Windows
![image](https://user-images.githubusercontent.com/11790765/89571687-f1ef7300-d7dc-11ea-9705-41875bc06f18.png)

**Comment by grokys** [comment]
@danwalmsley i think this was targeted for 0.10 if I remember correctly?
