### ISSUE TITLE
Avalonia.Markup.Xaml.XamlLoadException on MVVM project template with vs19

### ISSUE THREAD

**Issue by mate1213** [AvaloniaUI/Avalonia#4451]
I have a empty template avaloni application, and when I try to run I get the error below. I tried with different frameworks (Core 2.0, 2.1, 2.2, 3.0, 3.1) and I get the same result. The Avalonia version: 0.9.11 (latest based on nuget manager).

![image](https://user-images.githubusercontent.com/36986834/89618015-8e704e80-d88b-11ea-993c-2b9325137f8a.png)

Is there any suggestion what is the problem?
Thanks for the help!

**Comment by FoggyFinder** [comment]
Duplicate of: https://github.com/AvaloniaUI/Avalonia/issues/4426

**Comment by kekekeks** [comment]
I suspect that its somehow related to SDK versions. The problem manifests itself on some machines while on others it doesn't with exactly same source code.

**Comment by grokys** [comment]
@kekekeks not sure: I've seen this at times as well. Usually building with the command-line `dotnet` fixes it.

Anyway, closing this in favor of #4426.
