### ISSUE TITLE
CompileAvaloniaXamlTask Bug

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#4458]
I created a Transition with `IBrush` like this `Transition<IBrush>` to my controls library, in the avalonia previewer runs okay, but when I compile that give me an error.
The screenshot is this:
![image](https://user-images.githubusercontent.com/39932324/89698593-b1c8e700-d8e7-11ea-83b1-76a68ccac1c6.png)
And It gives me this error:
error MSB4018: System.ArgumentException: Member 'Avalonia.AvaloniaProperty' is declared in another module and needs to be imported

**Comment by kekekeks** [comment]
Kinda need the source code to reproduce, screenshot isn't enough.

**Comment by PieroCastillo** [comment]
> Kinda need the source code to reproduce, screenshot isn't enough.

https://github.com/PieroCastillo/Aura.UI/blob/master/src/Aura.UI/TabControlStyles.xaml

the source link is this

**Comment by WenjunHuang** [comment]
Why close this issue?
