### ISSUE TITLE
Combobox SelectedItem sends extra set value

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#4461]
# Intro
I have this model:

```cs
    public sealed class TestModel : INotifyPropertyChanged, IDisposable
    {
        private void OnPropertyChanged(string property)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(property));
        }
        public event PropertyChangedEventHandler PropertyChanged;

        public MyEnum Value
        {
            get => Obj.Value;
            set
            {
                if (value != Obj.Value) // Crash happens here because Obj is null
                {
                    Obj.Value = value;
                    OnPropertyChanged(nameof(Value));
                }
            }
        }

        public static IEnumerable<MyEnum> SelectableValues { get; } = Utils.GetEnumValues<MyEnum>();

        internal MyObj Obj;

        internal ObjectEventModel(MyObj obj)
        {
            Obj = obj;
        }

        public void Dispose()
        {
            Obj = null;
            PropertyChanged = null;
        }
    }
```

And this is the xaml that uses this model

```xaml
<ComboBox Items="{Binding SelectedObject.SelectableValues}" SelectedItem="{Binding SelectedObject.Value}" />
```

My DataContext has an `ObservableCollection<TestModel>` which holds the models. The control has a ComboBox to select the current TestModel (which is then stored in SelectedObject)

```xaml
<ComboBox Items="{Binding Objects}" SelectedItem="{Binding SelectedObject}">
```

# The problem
When I run the following code:

```cs
            foreach (TestModel obj in Objects)
            {
                obj.Dispose();
            }
            SelectedObject = null; // Crash in SelectedObject.Value.set
            Objects.Clear();
```
OR
```cs
            foreach (TestModel obj in Objects)
            {
                obj.Dispose();
            }
            Objects.Clear(); // Crash in SelectedObject.Value.set
```

I get a crash in SelectedObject.Value.set because the ComboBox tried to set the `Value` property to the first item in the ComboBox despite it no longer being bound. If I do not set Obj to null in TestModel.Dispose(), then there's no crash, but I now have a value I did not select stored in Obj.Value (always the first item in TestModel.SelectableValues)

# Expected behavior
ComboBox should not set the value since it is now unbound. No other controls are doing it (NumericUpDown, etc) on the same model.
Personally, given how many problems I've encountered with ComboBox, we should just port the ComboBox from WPF at this point since I'm assuming it's way more functional

**Comment by Kermalis** [comment]
The issue goes away if you bind with x:Static like so:
```xaml
<ComboBox Items="{x:Static uimodels:TestModel.SelectableValues}" SelectedItem="{Binding SelectedObject.Value}" />
```

So the problem is probably in how Items is handled upon being unbound

**Comment by grokys** [comment]
I've tried reproducing this but I don't think I have enough information to reproduce. Here's the code I tried to reproduce it with which was adapted from your repro here:

https://gist.github.com/grokys/722d90147f8b3a6632d5b1bcb362e074

However, it doesn't cause the crash as the issue says. Could I have a full minimal repro please?

**Comment by Kermalis** [comment]
@grokys My repro is here: https://github.com/Kermalis/AvaloniaRepro4461
