### ISSUE TITLE
Implement a package of Avalonia with Visual Code on Fedora 32.

### ISSUE THREAD

**Issue by catafest** [AvaloniaUI/Avalonia#4463]
## Summary
Implement a package of Avalonia with Visual Code on Fedora 32.

## API Changes

Just Linux API to build Linux application for Fedora 32 distro;

## Intended Use Case
I think is easy to create by the development team of this source code and will increase the area of interest for development with these source code.

**Comment by kekekeks** [comment]
Fedora 32 is supported by the stable 0.9.x branch. XAML preview is available with plugins for Visual Studio 2019 (Windows) and JetBrains Rider (all platforms).
