### ISSUE TITLE
WebBrowser？？？

### ISSUE THREAD

**Issue by chancezheng** [AvaloniaUI/Avalonia#4468]
How to use WebBrowser control in the Avalonia Frame?

**Comment by Martin005** [comment]
This was already discussed on #1259 and #3964. Unfortunately, Avalonia doesn't have a WebBrowser control, you can either use bindings as mentioned [here](https://github.com/AvaloniaCommunity/awesome-avalonia#web-browsers) or you can use [Steve Sanderson's WebWindow](https://blog.stevensanderson.com/2019/11/18/2019-11-18-webwindow-a-cross-platform-webview-for-dotnet-core/) if it is sufficient enough for your needs.

**Comment by danwalmsley** [comment]
also:
https://github.com/OutSystems/WebView/tree/CefGlue/update-avalonia-0.10
