### ISSUE TITLE
Can't sort columns in datagrid in 0.10-preview2

### ISSUE THREAD

**Issue by ShadowDancer** [AvaloniaUI/Avalonia#4476]
Repro steps:
1. Create datagrid `<DataGrid Items="{Binding Items}" CanUserSortColumns="True">`
2. Add some data to DataGrid
3. start app and try to sort column by clicking it

Expected result:
Clicking header changes sort direction

Actual result:
Nothing happens

Repository with repro:
https://github.com/ShadowDancer/AvaloniaRepro/tree/bug/cannot_sort_gridview

**Comment by grokys** [comment]
To confirm: this is a regression from 0.9?

**Comment by ShadowDancer** [comment]
Yep

**Comment by HendrikMennen** [comment]
Resizing columns seems to be broken too

**Comment by peters** [comment]
Resizing columns is broken in preview 3 on Windows and Linux.

**Comment by maxkatz6** [comment]
I found why it doesn't work.
With commit https://github.com/AvaloniaUI/Avalonia/commit/bc079008d1748ada1524f84bc6a8c8b36b339fb2 some conditions were inversed probably by mistake.
I will test it and create PR.
