### ISSUE TITLE
Publishing, compiling, and debugging on OS X

### ISSUE THREAD

**Issue by NullVSNone** [AvaloniaUI/Avalonia#4484]
Trying to move a completed project to Catalina, and been having some issues.
Best case would be running a debugger for the project on a Mac device, but haven't found anything on that.

What I've done:

1. On a windows computer, published for osx
2. Transferred `ProjectName` to Mac
3. Ran `chmod +x ProjectName`
4. Executed **ProjectName**

I get:
```zsh
user@User-2 ~ % /Users/user/Documents/PN/ProjectName ; exit;

[Process completed]
```

It seems related to issue https://github.com/AvaloniaUI/Avalonia/issues/3051, except the other one had more information. After the process completed, I don't get any output nor the program window. I have .Net Core 3.1 runtime, the SDK, and Mono installed as well.

I also tried combinations of `dotnet build` and `dotnet run` but that didn't work either.

Main thing I'd like is being able to execute the program, and get a debug output like `Debug.WriteLine` so I can make sure all functionality works on OS X. Then I'll follow the [packing guide for macOS](https://avaloniaui.net/docs/packing/macOS).

**Comment by ahopper** [comment]
dotnet publish -r osx-x64 -c Release -f netcoreapp3.1 /p:PublishTrimmed=true
works for me with absolutely nothing installed on the mac

**Comment by NullVSNone** [comment]
Even though I have .NET Core, I'm getting a macOS popup with:
`“libhostfxr.dylib” cannot be opened because the developer cannot be verified.`

And the terminal where I'm running the project produces:

```zsh
user@User-2 ~ % /Users/user/Documents/PN/ProjectName/ProjectName ; exit;
Failed to load A, error: dlopen(/Users/user/Documents/PN/ProjectName/libhostfxr.dylib, 1): no suitable image found.  Did find:
	/Users/user/Documents/PN/ProjectName/libhostfxr.dylib: code signature in (/Users/user/Documents/PN/ProjectName/libhostfxr.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
The library libhostfxr.dylib was found, but loading it from /Users/user/Documents/PN/ProjectName/libhostfxr.dylib failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366

[Process completed]
```

Running `chmod` recursively and reinstalling .NET Core SDK didn't fix this though. According to the [link provided](https://go.microsoft.com/fwlink/?linkid=2063366), it might be a specific issue due to Catalina?

**Comment by ahopper** [comment]
I have a number of users using my app on mac and I use the build command above, it creates a self contained app. On Catalina you do have to have to convince it that you really want to run it, but it does work.

**Comment by NullVSNone** [comment]
It does create a published folder, including the project and all the various .DLLs. I can't grab `libhostfxr.dylib` though, and trying https://github.com/Jackett/Jackett/issues/5062 didn't work out either.

From your end, your process is:
* Run `dotnet publish -r osx-x64 -c Release -f netcoreapp3.1 /p:PublishTrimmed=true`
* Transfer directory to Mac
* Run `chmod +x publish/ProjectName`
* Open **ProjectName**

And it launches with no issues? On Catalina too?

**Comment by ahopper** [comment]
Yep, that describes my process and it works.  What happens if you try ./ProjectName from a command prompt ?

**Comment by NullVSNone** [comment]
Same thing, attaching screenshot too:

![Screen Shot 2020-08-13 at 5 11 46 PM](https://user-images.githubusercontent.com/66640706/90187653-1ec8fa80-dd88-11ea-8a06-4f103f2135b3.png)

Do you have the **.dylib** in your project folder?

**Comment by Deadpikle** [comment]
Are you code-signing/notarizing your app? If so, that file needs to be code signed as well. Are you doing that?

(Can you also try right-clicking the app and choosing "Open" and seeing if you get the same options? You can also double check Settings -> Security and Privacy -> "Allow Apps downloaded from...")

**Comment by NullVSNone** [comment]
Not code-signing/notarizing the app yet, should I be? 

Right-click and "Open" is the same as just running it, having already run `chmod +x`.

The Security and Privacy setting seems to be it!
I had to click `Allow anyway` on 20+ different files, and then opening them when running **ProjectName**:

![Screen Shot 2020-08-13 at 5 22 05 PM](https://user-images.githubusercontent.com/66640706/90188491-8af82e00-dd89-11ea-8bb9-5c485a39a439.png)

After all of that though, I'm back to the starting point with:

```zsh
Last login: Thu Aug 13 17:23:35 on ttys001
/Users/user/Documents/PN/ProjectName/ProjectName ; exit;
user@User-2 ~ % /Users/user/Documents/PN/ProjectName/ProjectName ; exit;

[Process completed]
```

**Comment by danwalmsley** [comment]
@NullVSNone debugging works in both VSCode and Rider.

**Comment by NullVSNone** [comment]
@danwalmsley VS Code did work for debugging, after I removed the viewmodels called at start. Before then, I got:

```
...
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.7/System.IO.FileSystem.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.ComponentModel.Win32Exception' in System.Diagnostics.Process.dll
No such file or directory
```

After removing the calls, then introducing them directly through events, I got a proper debug message which is:

```
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Object reference not set to an instance of an object.
```

Resolving - the only real issue was that there were no messages if the error causer was introduced on launch.

Debugging and macOS compilation works perfectly, thanks everyone.
