### ISSUE TITLE
Black window screen (but works in 256-color compatibility mode)

### ISSUE THREAD

**Issue by caunt** [AvaloniaUI/Avalonia#4486]
Some our users reports that they see just black window instead of app - https://imgur.com/Avio216
One of them specs:
OS: Windows 7 (https://imgur.com/XMi5vCE)
GPU: ATI Radeon X1950 GT
Avalonia: 0.10.0-preview2

Logger.Sink did not give us any error information and also AppDomain.CurrentDomain.FirstChanceException did no throw any avalonia-related exception.
Also our app renders normally when user change compatibility mode to use 256 colors - https://imgur.com/6hSenne

**Comment by caunt** [comment]
Ok today we got PC with that bug in our hands and tried to comment/uncomment our application code until bug gone.
So we came to the conclusion that was bug with conflicting ClipToBounds and and CornerRadius properties on Border component ("True" and "16" values in our case)

Removing one of that two properties makes our window render again normally. But if both uncommented - window again become black.

**Comment by kekekeks** [comment]
Do you see an messages in stdout/stderr (like "unable to attach stencil buffer") ?

**Comment by caunt** [comment]
> Do you see any messages in stdout/stderr (like "unable to attach stencil buffer") ?

Yes.
[stderr.txt](https://github.com/AvaloniaUI/Avalonia/files/5427411/stderr.txt)

**Comment by caunt** [comment]
Users still sending their feedback that app window is black. So change that we made 2 days ago doesn't affect all users.

**Comment by caunt** [comment]
@kekekeks Users still sending their feedback that app window is black. So change that we made 2 days ago doesn't affect all users.

**Comment by caunt** [comment]
@kekekeks  Another **very** helpful log from stderr:
[stderr.txt](https://github.com/AvaloniaUI/Avalonia/files/5429182/stderr.2.txt)
[systeminfo.txt](https://github.com/AvaloniaUI/Avalonia/files/5429184/stdinfo.txt)

**Comment by kekekeks** [comment]
@danwalmsley @MarchingCube I think we should try to render some reference scene into a texture and fall back to SW rendering if it's broken with the current driver.

**Comment by kekekeks** [comment]
HW acceleration is now disabled by default for Windows 7. We'll investigate the issue later

**Comment by a191046083** [comment]
Hello, I also have three or four users who also encountered this situation, but I checked the code and found that the ClipToBounds and CornerRadius properties mentioned above were not set at the same time. The avalonia 11.0.0 version was used. Their system was windows 7. Adopted RenderingMode = new List < Win32RenderingMode > {Win32RenderingMode. Software} this mode renders them just normal, excuse me this how to program can be perceived, thank you very much! @kekekeks
