### ISSUE TITLE
Read files from Assets folder

### ISSUE THREAD

**Issue by xky0007** [AvaloniaUI/Avalonia#4488]
Somehow I need to read some config.json file located under Assets folder.

I first tried to read by relative path like ` var body = File.ReadAllText(@"./Assets/config.json")`. Then it shows that the target file doesn't exist in ..../bin/Debug/netcoreapp3.1. I guess the debug won't copy Assets folder to build folder.

Secondly, I followed assets instructions here [Assets](https://avaloniaui.net/docs/quickstart/assets)
```
var assets = AvaloniaLocator.Current.GetService<IAssetLoader>();
var fs = new StreamReader(assets.Open(new Uri(@"Assets/config.json")));
```

Still give me the error `System.UriFormatException: 'Invalid URI: The format of the URI could not be determined.'
`

Any correct way to read a file from code in Assets?

Thanks.

**Comment by MagnificentEagle** [comment]
Have you tried including AvaloniaResource in your project file?
```xml
<AvaloniaResource Include="Assets\config.json" />
```
I also had a problem with fonts, I specified AvaloniaResource in the project file and it worked.  Although it costs ``` Assets\* ```, it doesn't work.

**Comment by amwx** [comment]
Make sure it's an AvaloniaResource in the csproj and I believe the Uri needs to be in avares format (at least that's the only way I've gotten it to work):
```
var fs = new StreamReader(assets.Open(new Uri("avares://AssemblyName/Assets/config.json")));
```

**Comment by xky0007** [comment]
> Make sure it's an AvaloniaResource in the csproj and I believe the Uri needs to be in avares format (at least that's the only way I've gotten it to work):
> 
> ```
> var fs = new StreamReader(assets.Open(new Uri("avares://AssemblyName/Assets/config.json")));
> ```

Yeaps. I guess it only support avares format!

Thanks:D

**Comment by xky0007** [comment]
> Make sure it's an AvaloniaResource in the csproj and I believe the Uri needs to be in avares format (at least that's the only way I've gotten it to work):
> 
> ```
> var fs = new StreamReader(assets.Open(new Uri("avares://AssemblyName/Assets/config.json")));
> ```



> Have you tried including AvaloniaResource in your project file?
> 
> ```
> <AvaloniaResource Include="Assets\config.json" />
> ```
> 
> I also had a problem with fonts, I specified AvaloniaResource in the project file and it worked. Although it costs `Assets\*`, it doesn't work.

Maybe fonts are different. But for json file, `Asset\*` looks include them correctly. I just need to change to the correct avares format mentioned by @amwx
