### ISSUE TITLE
High process memory usage in last previews

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/Avalonia#4491]
When i ran last master i realized what process memory is too high for just "hello world" application it was around 130mb when for release it was 30mb.@kekekeks told this is because in last versions process memory usage started to display also usage of video memory.I think its unclear and may scare new developers.After small research and after conversation with @worldbeater i realized what i may turn it off with configuring AppBulider 
` .With(new Win32PlatformOptions
                           {
                               AllowEglInitialization = false
                           })`
But i havent find this in documentation and it take abut 30 minutes for me to find out how to turn it off,so i think would be better to return default value of AllowEglInitialization to false

**Comment by danwalmsley** [comment]
@Takoooooo AllowEglInitialization=false means do not use the GPU to render. This is inefficient and slow and not recommended.

Memory issue is being looked into. Its basically reserving too much memory for graphics even when not used but so far we are not sure why.
