### ISSUE TITLE
Does anyone knows how to change the color of the title bar and display the border line of the datagird

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#4495]
hi， i wat to change the color of the title bar and display the border line of the datagird.Look like this in the image below
Can someone help me? thank you
![image](https://user-images.githubusercontent.com/7692353/90371465-986f2a00-e0a1-11ea-9a31-ae512a95c87d.png)

**Comment by danwalmsley** [comment]
the window titlebar?

**Comment by jmacato** [comment]
@danwalmsley he meant the headers and the cells i think

**Comment by maxkatz6** [comment]
```xaml
<Style Selector="DataGridColumnHeader">
   <Setter Property="Background" Value="Red" />
</Style>
```

Should work.
For more info you can check template - https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls.DataGrid/Themes/Default.xaml

**Comment by wuzlai** [comment]
> titlebar

yeah,you are right,i want it.titlebar is green .There are border lines on all sides

**Comment by maxkatz6** [comment]
HorizontalGridLinesBrush

**Comment by wuzlai** [comment]
> For lines inside of datagrid you need these props: GridLinesVisibility, HorizontalGridLinesBrush, VerticalGridLinesBrush
> For row background you need : RowBackground, AlternatingRowBackground
> For header code in my comment should work - [#4495 (comment)](https://github.com/AvaloniaUI/Avalonia/issues/4495#issuecomment-674982989)

Ok,Thank you very much. i will look it.
