### ISSUE TITLE
Selection Model Issues

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#4496]
- Always selected mode - Add 3 items, select the last item... remove the middle item... this leaves no item selected.
- Crash when removing all items, and then inserting at position 0.
![image](https://user-images.githubusercontent.com/4672627/90382663-f5091f80-e076-11ea-85b1-928c5ee556ca.png)

-- more to come.

**Comment by grokys** [comment]
Both of these issues are related but the second is the most interesting (and hardest to fix). The following unit test demonstrates the problem:

```csharp
 [Fact]
public void Binding_SelectedIndex_Does_Not_Cause_ArgumentOutOfRange()
{
	// Issue #4496 (part 2)
	var items = new ObservableCollection<string>();

	var other = new ListBox
	{
		Template = Template(),
		Items = items,
		SelectionMode = SelectionMode.AlwaysSelected,
	};

	var target = new ListBox
	{
		Template = Template(),
		Items = items,
		[!ListBox.SelectedIndexProperty] = other[!ListBox.SelectedIndexProperty],
	};

	target.ApplyTemplate();
	target.Presenter.ApplyTemplate();
	other.ApplyTemplate();
	other.Presenter.ApplyTemplate();

	items.Add("Foo");
}
```

What happens is:

- `target` has `SelectedIndex` bound to `other.SelectedIndex`
- An item is added: `other` auto-selects the item
- The binding takes affect, setting `target.SelectedIndex = 0`
- `target`'s selection model recieves `CollectionChanged`, saying that an item was inserted at index 0
- So it adjusts the index of the selected item by adding 1 to it, to an index that doesn't exist
