### ISSUE TITLE
Application publishing error

### ISSUE THREAD

**Issue by AidarGiza** [AvaloniaUI/Avalonia#4497]
Can't publish the application. Even when I create new Avalonia MVVM Application.

![image](https://user-images.githubusercontent.com/42112009/90394141-c604a500-e09a-11ea-88b5-711c94458436.png)

Avalonia version 0.9.12
.Net Core 3.1

**Comment by FrankenApps** [comment]
Please post your publishing settings. Have you tried to publishSingleFile and publishSelfContained? Also with the 0.10-previews any setting worked for me.

**Comment by Sorcon** [comment]
Just solved this issue by install Windows6.1-KB947821-v34-x64.msu(maybe not needed) on Windows 7 and edit registry:
HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols
add TLS 1.0, 1.1, 1.2 folders and Server/Client in it. Set dword parameter DisabledByDefault 1 for 1.0 and 1.1 client/server and 0 for 1.2.
![image](https://user-images.githubusercontent.com/16455375/90504525-e47da580-e159-11ea-8320-b003298048f5.png)
![image](https://user-images.githubusercontent.com/16455375/90504536-ea738680-e159-11ea-8f1d-1554d198d79a.png)
![image](https://user-images.githubusercontent.com/16455375/90504546-ef383a80-e159-11ea-965e-992508a8eaf7.png)

**Comment by Sorcon** [comment]
It's not Avalonia issue, it's nuget bug/feature (tls 1.0/1.1 is no longer supported but tls version default set to system default)
