### ISSUE TITLE
Popup with IsOpen set to True in xaml causes exception at runtime

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#4501]
When setting `IsOpen="True"` for a `Popup`, it throws because the visual tree is still initializing I think. Not sure if it's supposed to work.

## Repro

```xaml
<Popup IsOpen="True">
    <TextBlock Text="Hello World!" />
</Popup>
```

If placed as a direct child of `Window`, it doesn't show anything. If placed deeper in the tree, e.g.:

```xaml
<Window ...>
    <StackPanel>
        <Popup IsOpen="True">
            <TextBlock Text="Hello World!" />
        </Popup>
    </StackPanel>
</Window>
```

it throws:

```
System.InvalidOperationException: Attempted to open a popup not attached to a TopLevel
```

If set manually in the `Window` constructor, after `InitializeComponent` (`AvaloniaXamlLoader.Load(this)`) it works as expected.

**Comment by kekekeks** [comment]
It's not supposed to work when window isn't yet shown.

**Comment by Gillibald** [comment]
This works perfectly fine under WPF

**Comment by danwalmsley** [comment]
probably it needs to not throw an exception and defer opening until window is opened (attached to visual tree?)

**Comment by ShadowDancer** [comment]
I think attaching to visual tree doesn't work. I've stumbled upon this some time ago by trying to open combobox in datagrid when row is selected in editorControl.OnAttachedToVisual(Logical)Tree, and it still throws. But maybe that was just DataGrid issue.

**Comment by ShadowDancer** [comment]
@kekekeks what you think about not throwing exceptions and displaying popup when attached to visual tree?

**Comment by kekekeks** [comment]
That should work, yes.

**Comment by kekekeks** [comment]
Note that we also need to wait until window is completely presented, otherwise it might still fail to show the popup properly.

**Comment by ShadowDancer** [comment]
Just tested it and looks like waiting for "AttachedToVisualTree" is enough.

Also the logic I implemented is following:
1. `IsOpen`/`Open` call may open popup, or schedule opening if window is not there.
2. If scheduled, popup will open when attached to visual tree
3. Scheduling is cleared when popup is opened or when closed was requested.

**Comment by kekekeks** [comment]
>Just tested it and looks like waiting for "AttachedToVisualTree" is enough.

wont be enough once we add wayland backend

**Comment by ShadowDancer** [comment]
I don't really have access to machine with wayland backend, could you guide me on how I should check whether window is ready to display?
