### ISSUE TITLE
XCB/XLIB crash on some Linux systems

### ISSUE THREAD

**Issue by capdj** [AvaloniaUI/Avalonia#4518]
Reposting my comment from #4319 as a new issue, as suggested - upgrading to a build with the #4319 / #4424 fix did resolve nvidia crashes for my testers, but caused a user who wasn't experiencing problems previously to get an xlib-related threading crash.

---------------

Tested this on my app - using the latest cibuild does indeed fix the problem one of my users had, where their (Linux, NVidia) system would regularly crash out with segfaults. So that is good!

Unfortunately, another one of my users, who was previously having no problems, is now experiencing regular crashes - that user is running an Intel GPU on Linux. They're seeing crashes with both:

[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has
not been called
[xcb] Aborting, sorry about that.
VTableAvalonia: ../../src/xcb_io.c:259: poll_for_event: Assertion
`!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)

and just

Segmentation fault (core dumped)

That said: This may not be due to the #4424 fix - I upgraded my app from cibuild 8766 to 9704 in order to get this fix, so of course something else could have changed in between, I suppose. But of course it's a little suspicious that this changes the way the rendering works with threads, and then a user immediately gets a graphics crash that mentions threading :(

Searching online suggests that this xcb/xlib issue shows up in all sorts of apps, and does look like a bug in xcb/xlib, so it's unlikely to be Avalonia actually doing anything wrong. But as with the NVidia crashes, if it's possible to work around it so we can run Avalonia apps reliably that would be ideal...

Since I haven't seen this on my PC, I can't test any suggested workarounds easily, but I can get my testers to try things out - will take a day or two to do so, however.

(Follow up: Running my app with UseGpu=false in the AppBuilder does seem to stop the crashes, so it's probably GPU related...?)

**Comment by kekekeks** [comment]
We could probably use a dedicated X11 display connection for GLX calls.

**Comment by ctrl-alt-d** [comment]
Same issue here with

```
          /:-------------:\          dani@fedora 
       :-------------------::        ----------- 
     :-----------/shhOHbmp---:\      OS: Fedora release 33 (Thirty Three) x86_6 
   /-----------omMMMNNNMMD  ---:     Host: Blade Stealth 3.06 
  :-----------sMMMMNMNMP.    ---:    Kernel: 5.13.5-100.fc33.x86_64 
 :-----------:MMMdP-------    ---\   Uptime: 1 hour, 25 mins 
,------------:MMMd--------    ---:   Packages: 2598 (rpm), 13 (flatpak) 
:------------:MMMd-------    .---:   Shell: bash 5.0.17 
:----    oNMMMMMMMMMNho     .----:   Resolution: 3200x1800, 3840x2160 
:--     .+shhhMMMmhhy++   .------/   DE: GNOME 3.38.5 
:-    -------:MMMd--------------:    WM: Mutter 
:-   --------/MMMd-------------;     WM Theme: Adwaita 
:-    ------/hMMMy------------:      Theme: Adwaita [GTK2/3] 
:-- :dMNdhhdNMMNo------------;       Icons: Adwaita [GTK2/3] 
:---:sdNMMMMNds:------------:        Terminal: gnome-terminal 
:------:://:-------------::          CPU: Intel i7-7500U (4) @ 3.500GHz 
:---------------------://            GPU: Intel HD Graphics 620 
                                     Memory: 8157MiB / 15886MiB 
```

```
dotnet --list-sdks
3.1.401 [/home/dani/dotnet/sdk]
5.0.100-rc.1.20452.10 [/home/dani/dotnet/sdk]
5.0.103 [/home/dani/dotnet/sdk]
6.0.100-preview.1.21103.13 [/home/dani/dotnet/sdk]
6.0.100-preview.3.21202.5 [/home/dani/dotnet/sdk]
6.0.100-preview.6.21355.2 [/home/dani/dotnet/sdk]
```

```
libGL error: failed to create drawable
libGL error: failed to create drawable
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
ER.AvaloniaUI: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```


With `UseGpu=false` doesn't hang.
