### ISSUE TITLE
Border render issues

### ISSUE THREAD

**Issue by petedavis** [AvaloniaUI/Avalonia#4521]
Using the following code block yields different results between Avalonia and WPF

Create a new project and paste the following as the body of the MainWindow:

```
    <Grid>
        <Border HorizontalAlignment="Center" VerticalAlignment="Bottom" Height="300" Width="600" BorderBrush="#FFCF5D1D"
                BorderThickness="2 2 2 0" CornerRadius="300 300 0 0" Background="#FF151515"/>
        <Border HorizontalAlignment="Center" VerticalAlignment="Bottom" Height="290" Width="580" BorderBrush="#FFCF5D1D"
                BorderThickness="0 2 0 0" CornerRadius="300 300 0 0" />

    </Grid>
```

### WPF (.net Core)
![image](https://user-images.githubusercontent.com/164331/90726241-8ccd6e80-e300-11ea-9344-92bf86a0fc88.png)

### Avalonia (0.10.0-preview3)
![image](https://user-images.githubusercontent.com/164331/90726632-2eed5680-e301-11ea-9041-792b2cdf0bde.png)

**Comment by petedavis** [comment]
There is still a slight issue with this. The corner radius is not able to extend past 50% of the lengths of the sides. 

![image](https://user-images.githubusercontent.com/164331/90835972-3fe3a980-e38d-11ea-927c-3fc1f31fad72.png)

**Comment by Gillibald** [comment]
Will make some calculations
