### ISSUE TITLE
DrawingPresenters doesnt clip properly

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#4522]
I traced the issue to our skiasharp update (#4222)

Before that PR:

![ezgif-2-f2e33d94ba84](https://user-images.githubusercontent.com/16554748/90729706-8d163b80-e2f9-11ea-8741-cab83397dabf.gif)

After that PR:
![ezgif-2-de2f52a2235a](https://user-images.githubusercontent.com/16554748/90729719-930c1c80-e2f9-11ea-8d2c-ea380a6d97cb.gif)

To repro: replace ImagePage.xaml in ControlCatalog with this: https://pastebin.com/8NUg0fcp and scroll around...

cc @Gillibald and perhaps @mattleibow

**Comment by jmacato** [comment]
@mattleibow yeah sorry i tried doing so but i cant come up with a repro at all...

**Comment by mattleibow** [comment]
Can you recreate this if you create a a new app, and set up a similar view hierarchy? or keep removing until it starts working?

**Comment by jmacato** [comment]
@mattleibow I'll try to make a minimal avalonia repro and link it here

**Comment by jmacato** [comment]
@mattleibow check this minimal repro https://github.com/jmacato/ReproWrongClip

**Comment by danwalmsley** [comment]
fixed on master.

**Comment by BAndysc** [comment]
Before I open a new issue, I wanted to ask first here, I have similar bug on Avalonia 0.10.5
![bug](https://user-images.githubusercontent.com/5689666/120630106-65dec400-c45e-11eb-9f81-c04edc96d457.gif)

Is it known bug? Shall I open a new issue? 
- OS: Mac OS 11
- .NET 5.0
- Apple M1: intel emulation via rosetta
- Avalonia version 0.10.5

**Comment by BAndysc** [comment]
@danwalmsley 
Before I open a new issue, I wanted to ask first here, I have similar bug on Avalonia 0.10.5
![bug](https://user-images.githubusercontent.com/5689666/120630106-65dec400-c45e-11eb-9f81-c04edc96d457.gif)

Is it known bug? Shall I open a new issue? 
- OS: Mac OS 11
- .NET 5.0
- Apple M1: intel emulation via rosetta
- Avalonia version 0.10.5
