### ISSUE TITLE
[Feature request] Add Visual Basic project template

### ISSUE THREAD

**Issue by MyBlueHorizon** [AvaloniaUI/Avalonia#4536]
As another language similar to C# on .Net, it should be easy to add

**Comment by Jogai** [comment]
Is it possible to use VB.net anyways? And if so, how?

**Comment by MikeCodesDotNET** [comment]
We're unlikely to officially support VB.NET as we don't have anyone on the team who knows it.

**Comment by DualBrain** [comment]
Feel free to take a look at some VB templates for Avalonia UI that are available (as source) over at https://github.com/CommunityVB/Templates/avalonia

Will eventually make these available as a nuget package; but they are available now in source and certainly could use some testing/feedback.
