### ISSUE TITLE
how to find the control lifecycle？

### ISSUE THREAD

**Issue by zzuiekwei** [AvaloniaUI/Avalonia#4537]
in wpf ，I can use loaded and unloaded， bug in Avalonia，which event or method can i use？
and how can i know the lifecycle of a control？

**Comment by crener** [comment]
Is there any solution to this?

**Comment by danwalmsley** [comment]
@crener I believe the correct answer to this is...

Controls are attached and removed from visual tree.. attached when they are in the ui, detached when removed.

you should used the AttachedToVisualTree and DetachedFromVisualTree events (or method overrides) to control the lifecycle.

**Comment by maxkatz6** [comment]
Apart from visual tree, there is logical tree with similar events AttachedToLogicalTree and Detached...
In WPF/UWP Loaded/Unloaded event is less specific about it.

You can also use ReactiveUI with its WhenActivated callback/disposal:
https://www.reactiveui.net/docs/handbook/when-activated/
https://avaloniaui.net/docs/reactiveui/activation
