### ISSUE TITLE
[Question] When will be stable release version v1.0.0 ?

### ISSUE THREAD

**Issue by redradist** [AvaloniaUI/Avalonia#4539]
I am curious when will be released stable build of Avalonia  ?

I want to start use it, but actually due to possible breaking changes I cannot ...

**Comment by danwalmsley** [comment]
@redradist I know others are currently working on iOS, and I imagine Android shortly after. Prob 0.10.x or 0.11.0, certainly there will be builds available this year I would hope.

**Comment by jinyuttt** [comment]
I feel like it can't be used in production, and it's very revised.

**Comment by maxkatz6** [comment]
0.10 is stable. Next major release is going to be 11.0.
