### ISSUE TITLE
Customizable title bar  

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#4540]
Is possible a easy  customizable title bar? Like a UWP Window,
I think it do more easy the customizable windows.
The documentation is this `https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar`

**Comment by danwalmsley** [comment]
https://github.com/AvaloniaUI/XamlControlsGallery

has a good example of how to do this.

**Comment by SpyceTewan** [comment]
How exactly does the dragging work? I got my title bar working but can't figure out how to set the dragging area. You said that intransparent elements need `IsHitTestVisible="False"` and I assigned that to everything that should need it, but can't drag the window. I'm guessing there's some code or markup I need to define the drag area, but can't find it in that example.

Help would be appreciated!

**Comment by FrankenApps** [comment]
You have set `CanResize = "False"`, therefore this does not work as expected. One option is to implement the dragging yourself, as I did [here](https://github.com/FrankenApps/Avalonia-CustomTitleBarTemplate/blob/521366625bddf8c295ca9ee1c457201affc4d107/Views/CustomTitleBars/WindowsTitleBar.axaml.cs#L91) in this [branch](https://github.com/FrankenApps/Avalonia-CustomTitleBarTemplate/tree/non-resizable).

**Comment by SpyceTewan** [comment]
Thanks a lot, got it working!

**Comment by Dynesshely** [comment]
Is their any way to custom the title bar but keep the window control box at the same time

**Comment by Dynesshely** [comment]
in linux or mac it would be diffcult but I think it could be done when running in windows

**Comment by charleypeng** [comment]
i just tested in mac it works, but in linux nothing changed.

p.s  it is 2023 now :(

**Comment by timunie** [comment]
@charleypeng 
1. you're answering closed issues - not a good idea in general....
2. Not all Linux distros don't allow us to do this, so nothing we can do on our side. Even if it's year 2023... We cannot do what the operating system does not allow. 
3. We will not provide hacks (even if possible), as we want our API to be stable and reliable. And features that are not documented, we cannot rely on. 
4. If you know how to make 2 working with respecting 3, your contribution is welcome.
