### ISSUE TITLE
0.10.0-preview3 publish crashes when ReadyToRun is enabled

### ISSUE THREAD

**Issue by TheUnlocked** [AvaloniaUI/Avalonia#4543]
Produce Single file enabled:
```
Unhandled exception. System.IO.FileLoadException:
File name: 'Avalonia.DesktopRuntime, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'
   at TestProgram.Program.Main(String[] args)
```
Produce Single file disabled:
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Avalonia.Controls, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Avalonia.Controls, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'
   at TestProgram.Program.Main(String[] args)
```
I am also using the .NET 5 preview. 0.9.0 does not have this issue.

**Comment by adirh3** [comment]
> Produce Single file enabled:
> 
> ```
> Unhandled exception. System.IO.FileLoadException:
> File name: 'Avalonia.DesktopRuntime, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'
>    at TestProgram.Program.Main(String[] args)
> ```
> 
> Produce Single file disabled:
> 
> ```
> Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Avalonia.Controls, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
> File name: 'Avalonia.Controls, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'
>    at TestProgram.Program.Main(String[] args)
> ```
> 
> I am also using the .NET 5 preview. 0.9.0 does not have this issue.

I am publishing R2R successfully using Avalonia 0.10 preview 4, I think I had the same problem as you and fixed it by manually deleting all the "obj" folders in all of my projects.

**Comment by TheUnlocked** [comment]
> I am publishing R2R successfully using Avalonia 0.10 preview 4, I think I had the same problem as you and fixed it by manually deleting all the "obj" folders in all of my projects.

That worked, thank you!
