### ISSUE TITLE
Overloading Avalonia.Media.Imaging classes

### ISSUE THREAD

**Issue by NoralK** [AvaloniaUI/Avalonia#4544]
Greeting,

Am am currently looking at Avalonia for x-platform apps.

I was wondering if there are plans to overload the constructors for the various classes that are defined in System.Drawing.Common, like Bitmap?  An Example would the ability to construct an Avalonia.Media.Imaging.Bitmap without going the route of streams and using System.Drawing.Common items natively in Avalonia, since they are x-platform.  Some thing like this:

```
Avalonia.Media.Imaging.Bitmap resBitmap = Properties.Resources.SomeImage;
```
instead of:
```
MemoryStream memStream = new MemoryStream();
((System.Drawing.Image)Properties.Resources.SomeImage).Save(memStream, ImageFormat.Png);
memStream.Seek(0, SeekOrigin.Begin);  //Throws error if this is this is missed should be caught in Bitmap
Avalonia.Media.Imaging.Bitmap resBitmap = new Avalonia.Media.Imaging.Bitmap(memStream);
```
IMHO - The streams method slows things down and is cumbersome.

Cheers,
Noral

**Comment by rstm-sf** [comment]
It seems like a bad idea to add an extra dependency to the main project. Instead, you can create a separate library where an extension will be defined with a signature similar to the following
```cs
public static Avalonia.Media.Imaging.Bitmap Avalonia.ToAvaloniaBitmap(System.Drawing.Image value)
```

**Comment by danwalmsley** [comment]
@kekekeks @grokys I think we have talked about this before? seems like we could improve api here?
