### ISSUE TITLE
No TypeConverter for Color - Maybe add one

### ISSUE THREAD

**Issue by Robertofon** [AvaloniaUI/Avalonia#4546]
If I create a control with an AvaloniaProperty of type Color, it cannot be conveniently set from XAML

```
public static readonly DirectProperty<Ctl, Color> OnColorProperty =  
          AvaloniaProperty.RegisterDirect<Ctl, Color>(nameof(OnColor),
          o => o.OnColor, (o, v) => o.OnColor = v, olor.Transparent,  BindingMode.Default);
```
This assignment

 `   <adb:Ctl OnColor="Brown" />`

or that
 `   <adb:Ctl OnColor="#FF4455" />`

will fail, because there is no TypeConverter for Color.

In comparison see IBrush:

```
    /// <summary>
    /// Describes how an area is painted.
    /// </summary>
    [TypeConverter(typeof(BrushConverter))]
    public interface IBrush
```

Would it be an Idea to add this to the Avalonia-Code for Color?
Are there reasons there is none? Or should I try to fix this issue? Or anybody else?

**Comment by danwalmsley** [comment]
@Robertofon I think it just needs a type converter adding, feel free to open a PR, should pretty much be a copy and paste of the brush one Im guessing...

a PR will be a good way to force a discussion about it too... issues can often get lost or overlooked.

**Comment by kekekeks** [comment]
Compiler should be using [Color.Parse](https://github.com/AvaloniaUI/Avalonia/blob/256b5b8ecde81683a34b3adbfc6ea4fc68634a23/src/Avalonia.Visuals/Media/Color.cs#L90).

Are you sure that you have the corresponding CLR properties?

**Comment by Robertofon** [comment]
I've added this PR https://github.com/AvaloniaUI/Avalonia/pull/4552
to sohow the problem I'm having.
Direct assignment thrugh xaml works as @kekekeks says. But style setters do not.
\avaloniaui.net\avalonia\src\Avalonia.Styling\Styling\Setter.cs
has the issue somhow hidden in it:
```
              data.result = new PropertySetterInstance<T>(
                    data.target,
                    property,
                    (T)data.value);

```
I dont know what to do. Anyways a TypeConverter does not fix this problem.

**Comment by kekekeks** [comment]
```cs
            Style style = new Style(x => x.OfType<Class1>())
            {
                Setters =
                {
                    new Setter(Class1.TestColorProperty, "#11223344"),
                },
            };
```

This code won't work since XAML compiler is not involved. You need to pass an actual `Color` when constructing styles from code

**Comment by Robertofon** [comment]
Seems like it fixed itself in the meantime - I did not relaize I can upgrade to 0.10 and since then it works

**Comment by Robertofon** [comment]
sorry to make effort
