### ISSUE TITLE
Animation freeze when moving window

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/Avalonia#4551]
I have created quite simple animation and when i try to move window it completely freeze 
there is gif to take a look: http://g.recordit.co/3ThYNfPVh6.gif
and there is gist to test it:https://gist.github.com/Takoooooo/a1dff2c9ef07a3b6a48ff26cddc8a56b

**Comment by jmacato** [comment]
This seems to be a Windows specific issue i suppose? @kekekeks

**Comment by Takoooooo** [comment]
@jmacato I checked it on MacOS.It works but also with issues.When i resize window on few milliseconds window seems to completly  disappears.At the moment i dont have a lot of time to record it but if you wouldnt find time to check it i will record it for you

**Comment by Takoooooo** [comment]
Just to clarify i have checked on MacOS only 0.9.12 version

**Comment by Takoooooo** [comment]
@jmacato I also checked it on macos with last preview.It also have glitcehs when resizing as 9.12.Im not available to record it,but its easy to reproduce
