### ISSUE TITLE
PointerReleasedEventMessage does not fire in VS previewer

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaUI/Avalonia#4555]
Hello!

After fix #4285 (>= preview-2) `PointerReleasedEventMessage` does not fire in VS previewer. It didn't work properly before:
- see [this](https://github.com/wieslawsoltes/AvaloniaBehaviors/blob/12895180c1ef495e9a62bdc86b766976496a3373/samples/BehaviorsTestApplication/Pages/CustomBehaviorControl.xaml#L1) xaml in VS -- we can move the figure, but you cannot let go
- see at the [same](https://github.com/wieslawsoltes/AvaloniaBehaviors/blob/861f6ae3a2f9681eb5ff23aa92bfffd0a4b95231/samples/BehaviorsTestApplication/Controls/CustomBehaviorControl.xaml#L1) xaml, but in preview-1 -- we will not be able to move the figure

Eventhandlers look fine in the extension (see [1](https://github.com/AvaloniaUI/AvaloniaVS/blob/831f0e37078d800827c700dd0910ac16b551e6e5/AvaloniaVS/Views/AvaloniaPreviewer.xaml.cs#L102-L126), [2](https://github.com/AvaloniaUI/AvaloniaVS/blob/831f0e37078d800827c700dd0910ac16b551e6e5/AvaloniaVS/Views/AvaloniaPreviewer.xaml#L21-L22))

**Comment by kekekeks** [comment]
I'm pretty sure that protocol serializer uses Guids instead of names, so it's probably not related to that change.

**Comment by rstm-sf** [comment]
It was an extension problem after all
