### ISSUE TITLE
Memory leak in DrawingContext.DrawGeometry

### ISSUE THREAD

**Issue by arklumpus** [AvaloniaUI/Avalonia#4557]
Hello, there seems to be some sort of leak when repeatedly using the DrawingContext.DrawGeometry method to fill geometries with different shapes.

To reproduce, add the following Control to an empty Window:

```
public class TestControl : Control
    {
        Point mousePosition = new Point();
        Random rnd = new Random();
        int segmentCount = 20;
        double radius = 100;

        protected override void OnPointerMoved(PointerEventArgs e)
        {
            mousePosition = e.GetPosition(this);
            this.InvalidateVisual();
        }

        public override void Render(DrawingContext context)
        {
            //So that we capture the PointerMoved events
            context.FillRectangle(Brushes.White, new Rect(0, 0, this.Bounds.Width, this.Bounds.Height));

            PathFigure fig = new PathFigure() { StartPoint = new Point(mousePosition.X + radius, mousePosition.Y) };

            for (int i = 0; i < segmentCount; i++)
            {
                //Geometry always has the same shape: no leak
                //fig.Segments.Add(new LineSegment() { Point = new Point(mousePosition.X + radius * Math.Cos(i * 2 * Math.PI / segmentCount), mousePosition.Y + radius * Math.Sin(i * 2 * Math.PI / segmentCount)) });

                //Geometry shape changes at every redraw: leak!
                fig.Segments.Add(new LineSegment() { Point = new Point(mousePosition.X + radius * Math.Cos(i * 2 * Math.PI / segmentCount) * rnd.NextDouble(), mousePosition.Y + radius * Math.Sin(i * 2 * Math.PI / segmentCount) * rnd.NextDouble()) });

            }

            fig.IsClosed = true;

            PathGeometry testGeometry = new PathGeometry();
            testGeometry.Figures.Add(fig);

            //Stroke: no leak
            //context.DrawGeometry(null, new Pen(Brushes.Blue), testGeometry);

            //Fill: leak!
            context.DrawGeometry(Brushes.Blue, null, testGeometry);
            
        }
    }
```

Then run the program and quickly move the mouse around in the window. Each time the mouse moves, the control is repainted with a geometry with a different (random) shape; at the same time, the memory usage will go up steadily.

I had a look with the profiler, and it seems to be mostly unmanaged memory:

![image](https://user-images.githubusercontent.com/32712606/91246499-42108400-e750-11ea-924b-7b67fe7d8c53.png)

That `Dictionary<IntPtr, WeakReference> SkiaSharp.HandleDictionary.instances` looks suspicious...

I first noticed this while using AvaloniaEdit: the SelectionLayer there draws the text selection using DrawGeometry, and this causes the control to use increasing amounts of memory as the user selects text regions with different shapes.

The issue:
- Happens with Avalonia 0.10.0-preview1 - 0.10.0-preview3, but not with 0.9.12
- Happens on both Windows 10 and Ubuntu 20.04
- Does not happen if the geometry has the same shape, even though the points making it up are still computed at every redraw: if you replace the relevant line with the commented line in the code above, the control draws a 20-sided polygon centered at the mouse pointer rather than a random shape; in this case, the leak does not occur.
- Does not happen if the geometry is stroked rather than filled (see comments in code).

**Comment by danwalmsley** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/9b73c1027b8bc03b8f2501d0fe4df8d311be7dac/src/Skia/Avalonia.Skia/EllipseGeometryImpl.cs#L15

geometries dont get disposed @kekekeks @grokys

**Comment by grokys** [comment]
Hmm, I was unable to repro this on master:

![V49jdk3gF1](https://user-images.githubusercontent.com/1775141/91903312-50582600-eca3-11ea-99c9-4c34aae53ced.gif)

I wonder if it's been fixed at some point?

**Comment by grokys** [comment]
@danwalmsley is there anything you've committed that might have fixed this?

@arklumpus could you try with current master, or preview 4 if you're unable to? Could be that it's machine dependent somehow?

**Comment by Gillibald** [comment]
SKPath isn't registered anywhere so the weak references held in a dictionary can't be an issue. Probably an older SkiaSharp version being used.

**Comment by grokys** [comment]
Just tried with preview 3 and can indeed repro. Seems to be fixed in preview 4.

Not sure what's changed there, though we have updated SkiaSharp, which I assume must be it as the `Dictionary<IntPtr, WeakReference> SkiaSharp.HandleDictionary.instances` isn't anything in our code AFAICS.

**Comment by grokys** [comment]
BTW, thanks for the fantasic repro @arklumpus !

**Comment by arklumpus** [comment]
Preview 4 fixes it for me too, amazing, thank you!

**Comment by wieslawsoltes** [comment]
I think there is still some leak, my code, everything is cached:

https://github.com/wieslawsoltes/Core2D/blob/404ad16d8d8b205ec7858b6f3355020c31c0be65/src/Core2D.UI/Renderer/Nodes/PathDrawNode.cs#L32

Got 57.5MB to 1.6GB memory usage jump in seconds.

![Core2D-GPU-DrawGeometry](https://user-images.githubusercontent.com/2297442/92109653-b353d500-ede9-11ea-85dc-cc015f7c74f4.gif)
