### ISSUE TITLE
Rectangle is rendered incorrectly, if StrokeThickness is bigger than Height/Width (comparing to WPF)

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#4558]
Steps to reproduce:
1. Create new WPF .Net Core project
2. Add new window:
```xaml
<Window x:Class="WpfApp3.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Background="Black">
  <Rectangle Margin="100" Stroke="White" StrokeThickness="40" Height="10" />
</Window>
```
3. It will be rendered as expected with Height=10
![image](https://user-images.githubusercontent.com/3163374/91248956-e3cdac00-e723-11ea-9d51-de6b893bd82e.png)

4. Create new Avalonia project
5. Add new window:
```xaml
<Window x:Class="AvaloniaApp.MainWindow"
        xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Background="Black">
  <Rectangle Margin="100" Stroke="White" StrokeThickness="40" Height="10" />
</Window>
```
6. It will be rendered with Height bigger than 10
![image](https://user-images.githubusercontent.com/3163374/91249071-22fbfd00-e724-11ea-8c65-a77ab6176e89.png)

**Comment by maxkatz6** [comment]
Found that issue during updating DataGrid theme.
Had to replace Rectangle with Border here - https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml#L591-L596

Now I see, it could be replaced with "<Rectangle Height="1" Fill="{DynamicResource}" />" next time.

**Comment by ygra** [comment]
Note that WPF's Rectangle draws the stroke inward (same as Ellipse, but unlike Path). Where the stroke ends up relative to the geometry may account for the difference here.
