### ISSUE TITLE
Validation via DataAnnotation as well as binding exceptions produce bad UX

### ISSUE THREAD

**Issue by dejfcz** [AvaloniaUI/Avalonia#4559]
With a simple view model that uses `RequiredAttribute`, the result of the validation this:

![image](https://user-images.githubusercontent.com/19493351/91287443-a864c900-e787-11ea-9ea5-58b0314e7ff8.png)

Notice the exception type prefix.

There are two ways how to fix this. First is to use `DataValidationException` in https://github.com/AvaloniaUI/Avalonia/blob/release/0.10.0-preview3/src/Avalonia.Base/Data/Core/Plugins/DataAnnotationsValidationPlugin.cs#L66

Change to
```
                    return new DataValidationException(errors[0].ErrorMessage);
```

(and similar changes required for https://github.com/AvaloniaUI/Avalonia/blob/release/0.10.0-preview3/src/Avalonia.Base/Data/Core/Plugins/DataAnnotationsValidationPlugin.cs#L70 and maybe also https://github.com/AvaloniaUI/Avalonia/blob/release/0.10.0-preview3/src/Avalonia.Base/Data/Core/Plugins/ExceptionValidationPlugin.cs)

This will cause the result to be as expected:
![image](https://user-images.githubusercontent.com/19493351/91287985-58d2cd00-e788-11ea-9174-1634de1ec4af.png)

Similarly, there are problems with binding exception, e.g. from invalid number to a number. This is an issue since there is no validation error displayed on NumericUpDown (#3591), but possibly there are more binding exceptions that even having working validation on NumericUpDown would not solve. It looks like this:

![image](https://user-images.githubusercontent.com/19493351/91288350-ce3e9d80-e788-11ea-8868-44be6520a771.png)

This could be worked around with using `int` field, but `string` property and check if the value on setter is a number of not, and if not, throwing `DataValidationException`. I thought changing `ExceptionValidationPlugin` might fix this, but it did not work for me.

![image](https://user-images.githubusercontent.com/19493351/91288893-70f71c00-e789-11ea-94d5-384bb01dadd9.png)

The second way of fixing this, that might fix both problems (haven't checked), is actually changing the code of `GetExceptionData` (https://github.com/AvaloniaUI/Avalonia/blob/release/0.10.0-preview3/src/Avalonia.Controls/DataValidationErrors.cs#L133), change to:

```
        private static object GetExceptionData(Exception exception)
        {
            if (exception is DataValidationException dataValidationException)
                return dataValidationException.ErrorData;

            return exception.Message;
        }
```

or something similar (haven't tested this one)...

**Comment by Gillibald** [comment]
Contributions are welcome 👍

**Comment by danwalmsley** [comment]
This is better on the more modern fluent template.. and apps like WasabiWallet have defined their own template to further improve this ui.

**Comment by KieranDevvs** [comment]
> This is better on the more modern fluent template.. and apps like WasabiWallet have defined their own template to further improve this ui.

Its really not... After looking at how WasabiWallet do this, its *very* convoluted to simply not display the system exception type along with the message. The default implementation should be a user friendly message (after all... this is a UI library), and if the application requires the design to show the exception type, that's when you would apply a style and converter to override the default implementation.

**Comment by grokys** [comment]
Yeah I agree - if someone would like to submit a PR to fix this, it would be accepted, if not I can probably submit a fix in the next few days.

**Comment by KieranDevvs** [comment]
> Yeah I agree - if someone would like to submit a PR to fix this, it would be accepted, if not I can probably submit a fix in the next few days.

Ill use this as an excuse to contribute to an open source project if you're not already working on it?
