### ISSUE TITLE
SpltiView is invisible in default theme

### ISSUE THREAD

**Issue by ShadowDancer** [AvaloniaUI/Avalonia#4560]
Avalonia version:
0.10.0-preview3

There is no SplitView in Avalonia.Themes.Default. As a result nothing is visible when someone tries to use it.

**Comment by rstm-sf** [comment]
Strange, after this #4439 it should have appeared. See also https://github.com/AvaloniaUI/Avalonia/commit/9afbbe754fa28bfb685a460c78e9ef410320afdd

**Comment by rstm-sf** [comment]
In #4502 was some kind of fix splitview. Have you checked on nightly builds?

**Comment by ShadowDancer** [comment]
I can't compile master for some reason, but if you say it's fixed then i'll assume it is.

**Comment by rstm-sf** [comment]
Sorry if I put it wrong, but I meant it might have been fixed



> I can't compile master for some reason

It is not necessary to build the project, you can use nuggets from [nightly build](It is not necessary to build the project, you can use nuggets from nightly build)
