### ISSUE TITLE
The order of traversing the element tree when creating

### ISSUE THREAD

**Issue by RomanSoloweow** [AvaloniaUI/Avalonia#4564]
**WPF**: tunnel bypass, parent -> children 
**Avalonia**: bubble bypass, children -> parent 

If the parent sets the ViewModel to the child elements (as it was in WPF), now we get null in the child elements, since they are created before parent

**Comment by grokys** [comment]
Could you explain? I have trouble understanding what you're saying here.

**Comment by RomanSoloweow** [comment]
Constructor off child elements works earlier than parent. Initialization to elements begin with children elements.
Example: 
All child elements will be create earlier  than current UserControl.
![image](https://user-images.githubusercontent.com/29205560/91618065-1aa8f980-e992-11ea-80e3-ca9497fc05fd.png)

**Comment by maxkatz6** [comment]
Just want to make it clear.
Are you talking about order of creating control objects or order of attaching control to the visual tree? Or both?

**Comment by grokys** [comment]
> Constructor off child elements works earlier than parent. 

@RomanSoloweow that's not true. You can look at the code generated by the XAML compiler to confirm, for example this XAML:

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:AvaloniaApplication11"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication11.MainWindow"
        Title="AvaloniaApplication11">
  <Border>
    <Button>Hello</Button>
  </Border>
</Window>
```

Produces the following IL (decompiled by ILSpy):

```csharp
static void !XamlIlPopulate(IServiceProvider P_0, MainWindow P_1)
{
	XamlIlContext.Context<MainWindow> context = new XamlIlContext.Context<MainWindow>(P_0, new object[1]
	{
		!AvaloniaResources.NamespaceInfo:/MainWindow.axaml.Singleton
	}, "avares://AvaloniaApplication11/MainWindow.axaml");
	context.RootObject = P_1;
	context.IntermediateRoot = P_1;
	((ISupportInitialize)P_1).BeginInit();
	P_1.Title = "AvaloniaApplication11";
	Border border;
	Border border2 = border = new Border();
	((ISupportInitialize)border2).BeginInit();
	P_1.Content = border2;
	Button button;
	Button button2 = button = new Button();
	((ISupportInitialize)button2).BeginInit();
	border.Child = button2;
	button.Content = "Hello";
	((ISupportInitialize)button).EndInit();
	((ISupportInitialize)border).EndInit();
	((ISupportInitialize)P_1).EndInit();
	StyledElement styled;
	if ((styled = (P_1 as StyledElement)) != null)
	{
		NameScope.SetNameScope(styled, context.AvaloniaNameScope);
	}
	context.AvaloniaNameScope.Complete();
}
```

You can see that the `Border` is created before the `Button`.
