### ISSUE TITLE
ListBox NRE if ListBoxItem and ItemTemplate specified

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/Avalonia#4568]
![image](https://user-images.githubusercontent.com/53405089/91453167-1690b500-e888-11ea-9ebd-369720b99f6b.png)
With this pretty simple configuration listbox always throws exception.Works with 0.9.12 and also with last preview.If you dont set items property on ListBox works ok.To get it work you will need to do awful workaround like this
![image](https://user-images.githubusercontent.com/53405089/91453443-64a5b880-e888-11ea-919c-7739afc98cde.png)
in Append you need to pass your items.Also works if you delete listboxitem

**Comment by grokys** [comment]
This is essentially setting the `Items` property twice as [`Items`](https://github.com/AvaloniaUI/Avalonia/blob/9b8d4d7367548f51cbca2e5500d6942b9503042e/src/Avalonia.Controls/ItemsControl.cs#L102-L107) is the content property.

We definitely should throw a better exception than `NullReferenceException` here, so leaving the issue open, but this will likely never be supported in the way you envisioned.

**Comment by Gillibald** [comment]
It should probably produce `The property 'Items' is set more than once`

**Comment by danwalmsley** [comment]
@Takoooooo let us know what you want to do, and we can help you find a better solution.

You will have a much easier time, if you Bind an ObservableCollection to the Items,... and just insert the item you want prepended to that collection.

**Comment by Takoooooo** [comment]
@grokys @Gillibald @danwalmsley Guys,seems what you have misunderstood me.I set my items only once! Second screenshot its just workaround what could probably make easier to understand the issue.I just want to have kind of header at my listbox(to make workaround on datagrid because it seemed to me too buggy to use it in production).Here is gist to reproduce it
https://gist.github.com/Takoooooo/804ea995ceefff213717d33a9ca8b5cd
And also add to ViewModel this code
`public List<object> MyItems { get; set; } = new List<object>
        {
            new { AllTracks = new List<string> { "blahblah" }}
        };`
And thats all.You will see NRE

**Comment by FoggyFinder** [comment]
> Guys,seems what you have misunderstood me.I set my items only once! 

First:

```xml
      <ListBox.ItemTemplate>
         <DataTemplate>
             <TextBlock Text="{Binding AllTracks.Count}"></TextBlock>
         </DataTemplate>
       </ListBox.ItemTemplate> 
```

Second:

```xml
<ListBoxItem>
    <TextBlock Text="Tracks"></TextBlock>
</ListBoxItem>
```

Do you want to provide "header" for the items?

**Comment by Takoooooo** [comment]
Yes, I would like to make it look the same as in Datagrid. I want this <ListBoxItem> to interact as a header. I want it to be located at the start of my Listbox. It got to look like this
![image](https://user-images.githubusercontent.com/53405089/91477484-148a1e80-e8a7-11ea-8089-07ee5eb1bf8b.png)

**Comment by Gillibald** [comment]
It is easier to create a custom control with a header part instead of your approach. You can use multiple templates. One for your header and one for regular items.

**Comment by Takoooooo** [comment]
Oh, I thought wpf won't throw an exception but it does. It writes what "Items collection must be empty before using ItemsSource.".But I think its really logical. Just to append items to the existing sequence instead of waiting it to be empty. In this case, you will be able to be more variable if you understand what I mean

**Comment by grokys** [comment]
> But I think its really logical.

It may seem logical to you but that doesn't get round the fact that you're setting the `Items` property twice ;)

Even if it were possible to set a property twice, how should `ListBox` know what to do with the extra item? It looks like you want it at the top, but what if someone wanted it at the bottom? There's no way to inform `ListBox` of this.
