### ISSUE TITLE
Layout with Grid with many children is slow.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#457]
Repro:
- Checkout `issue-457` branch.
- Run XamlTestApplication
- Open DevTools (F12)
- Select `Window` in DevTools treeview.
- Look at program output in VS
- Resize main XamlTestApplicationWindow

You will see output in the VS output window like:

```
Grid.MeasureOverride: 541ms
Grid.MeasureOverride: 550ms
Grid.MeasureOverride: 546ms
Grid.MeasureOverride: 541ms
Grid.MeasureOverride: 542ms
Grid.MeasureOverride: 552ms
Grid.MeasureOverride: 558ms
Grid.MeasureOverride: 547ms
Grid.MeasureOverride: 551ms
Grid.MeasureOverride: 554ms
```

This does not appear to be caused by measuring the children, as putting a `Stopwatch` around the `child.Measure` call reports 0ms for each child.

**Comment by jmacato** [comment]
Fixed by #1517
