### ISSUE TITLE
Maximum property in the ProgressBar in Fluent Theme

### ISSUE THREAD

**Issue by kaminova** [AvaloniaUI/Avalonia#4570]
Seems changing Maximum property in ProgressBar does not work in the Fluent Theme:

`<ProgressBar  IsIndeterminate="False" Minimum="0" Maximum="1" Value="{Binding ProgressValue}"  />`

since Maximum is set to 100:
https://github.com/AvaloniaUI/Avalonia/blob/9b8d4d7367548f51cbca2e5500d6942b9503042e/src/Avalonia.Themes.Fluent/ProgressBar.xaml#L15

**Comment by danwalmsley** [comment]
Setting it explicitly as you have done, should override the style... are you certain this is the case...

if not the I think this would be a bug, @grokys

**Comment by kaminova** [comment]
```<ProgressBar IsIndeterminate="False" Value="50" Minimum="0" Maximum="1" Height="20" Width="200" />```
How it looks in Default Theme:
![изображение](https://user-images.githubusercontent.com/45092470/91637117-4fef2f00-ea06-11ea-8113-cd4d449f1a42.png)
How it looks in Fluent Theme:
![изображение](https://user-images.githubusercontent.com/45092470/91637135-672e1c80-ea06-11ea-85d2-edd091e39894.png)

**Comment by kaminova** [comment]
also, i tried to set the `Maximum` property in a style, but it applies to all progress bars: 
```
  <StackPanel Spacing="8">
    <ProgressBar IsIndeterminate="False" Value="50" Minimum="0" Maximum="100" Height="20" Width="200" Classes="mmm" />
    <ProgressBar IsIndeterminate="False" Value="50" Minimum="0" Maximum="100" Height="20" Width="200" />
  </StackPanel>
```
```
<Styles xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <Style Selector="ProgressBar.mmm">
        <Setter Property="Maximum" Value="1" />
        <Setter Property="Foreground" Value="Red" />
    </Style>
</Styles>
```
The result: 
![изображение](https://user-images.githubusercontent.com/45092470/91637848-a6ab3780-ea0b-11ea-83f3-a284a4f8892b.png)

The `Foreground` property applies only to "mmm" class, but the `Maximum` applies to all progress bars. Not sure, probably it's another issue.
