### ISSUE TITLE
Cant create control what inherits from TextBox

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/Avalonia#4571]
I register quite simple control like this.
![image](https://user-images.githubusercontent.com/53405089/91499699-9c355480-e8ca-11ea-8e12-308b00898d39.png)
And add this code to the main window.
![image](https://user-images.githubusercontent.com/53405089/91499975-2da4c680-e8cb-11ea-9928-83cc5333db98.png)
And only text from textbox gets displayed.
![image](https://user-images.githubusercontent.com/53405089/91500013-47dea480-e8cb-11ea-8e7f-cb5aca8ab825.png)
If I change Hyperlinks inherited class to TextBlock it works ok

**Comment by maxkatz6** [comment]
TextBox styles isn't applied on Hyperlink. Its logic is different comparing to WPF/UWP.
To reuse same styles you need to set StyleKey property on Hyperlink.
See https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/DropDown.cs as an example.

**Comment by danwalmsley** [comment]
@Takoooooo inherit `IStyleable`

then add

`Type IStyleable.StyleKey => typeof(TextBox);`
