### ISSUE TITLE
SplitView.Pane does not handle comboboxes

### ISSUE THREAD

**Issue by ShadowDancer** [AvaloniaUI/Avalonia#4575]
Avalonia 0.10-preview4

Repro steps:
1. Create SpltiView with control using popup, eg. Combobox inside
2. Click combobox to expand values list
3. Click item from list

Expected results:
Value in combox is set

Actual results:
Pane closes, while combobox is left open (despite combobox itself being not visible, just pane is floating in middle of nowhere).

![image](https://user-images.githubusercontent.com/766312/91562471-8c0a8d00-e93d-11ea-8308-81321338cb8a.png)
![image](https://user-images.githubusercontent.com/766312/91562485-9036aa80-e93d-11ea-9e44-7bc6b6986460.png)

Repro repository:
https://github.com/ShadowDancer/AvaloniaRepro/tree/bug/list_view_closing_on_combobox_click

**Comment by grokys** [comment]
ping @amwx

**Comment by amwx** [comment]
I'll take a look this weekend
