### ISSUE TITLE
When I add a style by code in a window, this give an error

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#4580]
hello, I created a language manager for avalonia, when I did it, I used this code ```window.Styles.Add(x.Style);```, in avalonia 0.9.12 it works perfectly, but with the 0.10.0preview4, it works bad, that gives me this error in runtime ```System.InvalidOperationException: 'The Styles already has a owner.'```, really, I don't now what's happen.

**Comment by maxkatz6** [comment]
Are you sure, that style hasn't any parent before you add it to the window?

**Comment by PieroCastillo** [comment]
> Are you sure, that style hasn't any parent before you add it to the window?

mmm, that already has a parent, but it worked the same, but now don't

**Comment by grokys** [comment]
@PieroCastillo that's because styles could previously be added to many parents, but now they can't ;) It was changed for performance reasons.

We can add multi-parenting back in but I'd like to understand why you need to be able to have a style added to multiple controls?

**Comment by PieroCastillo** [comment]
> We can add multi-parenting back in but I'd like to understand why you need to be able to have a style added to multiple controls?

mmm, now I want to add styles for an ThemeManager, in fact, I was making that with Avalonia 0.9, but with Avalonia 0.10, this   throw an error "The Styles already has an owner", this occurs with ```SomeControl.Styles.Add(someStyle)``` or  ```SomeControl.Styles.AddRange(someStyles)```
