### ISSUE TITLE
Avalonia.MonoMac NSFileManager GetAttributes & SetAttributes segfaults no matter what I do.

### ISSUE THREAD

**Issue by plasticalligator** [AvaloniaUI/Avalonia#4588]
var attrs = NSFileManager.DefaultManager.GetAttributes(filePath); results in an immediate "Segmentation fault: 11".
Same with SetAttributes.

No matter what voodoo I try, nothing works, wrapping it in a NSAutoreleasePool, using InvokeOnMainThread, or invoking GC.KeepAlive(NSFileManager.DefaultManager). I looked into Avalonia.MonoMac's source and didn't see any major deviations from the standard MonoMac; so I have no idea what is going on here. 

If I feed it an invalid path name I don't get a segmentation fault, and instead get a path not found error in NSError; so clearly it's finding the file, but something is over-releasing.

In Xamarin it works without any special considerations but .NET Core support is only planned for 2021 so that's not exactly a viable option for me.

**Comment by kekekeks** [comment]
I suspect that "standard MonoMac" has the same issue. 
Our fork simply provides a netstandard build and a nuget-package, don't expect it to be really maintained.

We are currently using an ObjectiveC/C++ native library for native interop on OSX, so I'd suggest to either do the same or P/Invoke [libobjc](https://developer.apple.com/documentation/objectivec/objective-c_runtime) directly
