### ISSUE TITLE
Question: Getting Rows in DataGrid

### ISSUE THREAD

**Issue by NoralK** [AvaloniaUI/Avalonia#4590]
How do you iterate over Rows in a DataGrid within code?  The control does not have a Rows method and I could not find anything out about cells.

I would like to do this programmatically and a working example would always help.

Thanks,
Noral

**Comment by maxkatz6** [comment]
Hi!
There is LoadingRow event, you can see an example in the ControlCatalog - https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/DataGridPage.xaml.cs#L16

If you need to get all rows, you can traverse the visual tree, but with virtualization it could be problematic.

**Comment by NoralK** [comment]
Thank you for the prompt response.

It looks like the LoadingRow event would not work for me.  How would you traverse the visual tree?

I am trying to export the DataGrid to a file and I do not know if that would be CSV, JSON or another format at this time.  I am also looking to update cells(programmatically).

**Comment by NoralK** [comment]
I think I have it but it is ugly - MockRecord is my Model class
```
DataGrid myDG = new DataGrid();
var item = myDG.Items.Cast<MockRecord>().ElementAt(1);
item.FirstName="ab";
/*or*/
var myDGItemAsAList = myDG.Items.Cast<MockRecord>().ToList();
/* Here I can get a count of Rows as well :) */
```
However I noticed that the DataGrid does not update with new values.  I have the bind set to Binding="{Binding FileName,Mode=TwoWay}".

**Comment by NoralK** [comment]
Well it works now ... hacked more uglyness.  I would like suggestions on how to change this:
```

            DataGrid myDG = new DataGrid();
            myDG = this.FindControl<DataGrid>("myDG");
            DataGrid myDGNew = new DataGrid();
            var items = myDG.Items.Cast<MockRecord>().ToList();
            var item = myDG.Items.Cast<MockRecord>().ElementAt(1);
            item.FirstName = "ab";

            myDGNew.Items = myDG.Items;
            myDG.Items = null;  // Just to be safe
            myDG.Items = myDGNew.Items;
```

Is there a Roadmap on the DataGrid functionality - there seems to be alot missing from the WPF DataGrid.  Or is there a better way of handling Row/Column/Cell?

Cheers

**Comment by Gillibald** [comment]
Relying on the visual structure of a control is generally a bad idea. Instead, you should model your column definition and generate your export from that model. As mentioned above the content of the DataGrid might be virtualized and that causes issues with your implementation.

**Comment by maxkatz6** [comment]
> Is there a Roadmap on the DataGrid functionality - there seems to be alot missing from the WPF DataGrid. 
There is no actual roadmap for DataGrid itself.
It's quite heavy control that requires more work that we can put on it. New features and fixes comes time by time, often from community.

**Comment by maxkatz6** [comment]
I think this issue was answered. It's not possible to get list of actual rows from DataGrid because of virtualization, but it is possible to handle rows with LoadingRow and it's possible to get items source and cast it to your model.
Feel free to reopen this or create new one if you have questions.

**Comment by cornerbowlsoftware** [comment]
@maxkatz6 How can we set keyboard focus if we can't access the controls?
