### ISSUE TITLE
SkiaSharp import crashes on MacOS Catalina (10.15.6) 0.10-preview4

### ISSUE THREAD

**Issue by vegard-st1** [AvaloniaUI/Avalonia#4592]
It fails silently when Avalonia is trying to calling SKImageInfo.PlatformColorType.ToPixelFormat(). If I downgrade to preview1 it works just fine. So something must have happened between these two versions.

```
internal class PlatformRenderInterface : IPlatformRenderInterface, IOpenGlAwarePlatformRenderInterface
    {
        private readonly ISkiaGpu _skiaGpu;

        public PlatformRenderInterface(ISkiaGpu skiaGpu, long? maxResourceBytes = null)
        {
            DefaultPixelFormat = SKImageInfo.PlatformColorType.ToPixelFormat();
```

**Comment by danwalmsley** [comment]
@vegard-st1 how do I trigger this? Whats the repro?

**Comment by vegard-st1** [comment]
@danwalmsley Starting a new project and upgrading to preview4. Added a reproduction project here:
[SkiaFailing.zip](https://github.com/AvaloniaUI/Avalonia/files/5155550/SkiaFailing.zip)

**Comment by danwalmsley** [comment]
@vegard-st1 that runs on my machine? are you using real machine or VM?

**Comment by vegard-st1** [comment]
@danwalmsley I'm running on the iron, no VM, system data:
MacBook Pro (16-inch, 2019)
2,3 GHz 8-Core Intel Core i9
AMD Radeon Pro 5500M 4 GB

Actually the problem stopped after cleaning the project.

Turns out that it fails when building on lower version -> upgrading to preview4 -> starting project.

**Comment by danwalmsley** [comment]
@vegard-st1 glad to know a clean and build sorted it out. I guess it was still using older nuget for something somehow.
