### ISSUE TITLE
AvaloniaResource files are invisible in F# projects [ Visual Studio ]

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#4602]
```xml
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
```

works in C# projects but not in `.fsproj` ones.
No build error: compiles just fine but VS doesn't list any ".xaml" files in "Solution Explorer". Therefore I have to use `EmbeddedResource`.

**Comment by kekekeks** [comment]
Does `axaml` work?

**Comment by FoggyFinder** [comment]
Nope. With `.axaml` VS goes crazy: 

At first the files were shown but I got Avalonia.Markup.Xaml.XamlLoadException: "No precompiled XAML found for... 

I closed VS, removed "bin"/"obj" and reopened IDE again: this time no exception but files aren't listed.

**Comment by ShadowDancer** [comment]
@FoggyFinder show your fsproj

**Comment by FoggyFinder** [comment]
I was sure I replied here. Seems like it is fixed somewhere already, closing the issue

For those who stick to 0.9.x version see my [answer](https://topanswers.xyz/fsharp?q=1415#a1657) on TopAnswers
