### ISSUE TITLE
[Feature] VNC Output for existing Window

### ISSUE THREAD

**Issue by Int32Overflow** [AvaloniaUI/Avalonia#4608]
Currently it is only possible to select VNC or Linux FrameBuffer/DRM as output medium.
But it would be great, if you could connect to an existing window via VNC (e.g. for remote maintenance)

I've already looked at the source code, but this is a bit too much for my brain...
How do you see that? Is it possible?

**Comment by kekekeks** [comment]
It should be possible to take a screenshot of the window and trigger input events without changes to Avalonia code.

**Comment by Int32Overflow** [comment]
@kekekeks How can I make a screenshot in Avalonia?

It could also be possible to write a wrapper for ILockedFrameBuffer, which copies the data into several Child-ILockedFrameBuffers and creates several identical outputs, or? What do you think?

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.RenderTests/TestBase.cs#L93

**Comment by Int32Overflow** [comment]
> https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.RenderTests/TestBase.cs#L93

@kekekeks Ok thank you. 
One question: The method "Save" will export it as png. How can I get the RGB-Data for the VNC Buffer?

**Comment by pedroveiga99** [comment]
Picking up on this, @maxkatz6 is this still not planned? I think it is a bit limiting not being able to show in VNC and DRM/Framebuffer.

**Comment by maxkatz6** [comment]
@pedroveiga99 you can achieve that with [Avalonia.Headless](https://xpf-docs.avaloniaui.net/docs/advanced/headless-testing) rendering. Making screenshots of each frame and imitating input.
