### ISSUE TITLE
About webview,render html in  avalonia application.

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#4638]
Hi :
Hello,I have a problem that  maybe you once had, I have some html,just to render in the  avalonia application.
I have find a way,it is cefnet. it use google chrome,but this will make the package very large,what is more ,the cefnet must  be synchronized with the latest version of Avalonia.now i only use it in avalonia 0.9.12.but in 0.10.0 preview5 failed.
Are there any solutions that have been successfully applied in the project?I would like to ask you how did you solve the problem? 
thank you.

**Comment by maxkatz6** [comment]
Just for case, if you need to render simple html without css/js and else, you can use Avalonia.HtmlRenderer
https://github.com/AvaloniaUI/Avalonia.HtmlRenderer/pull/7

**Comment by wuzlai** [comment]
> Just for case, if you need to render simple html without css/js and else, you can use Avalonia.HtmlRenderer
> [AvaloniaUI/Avalonia.HtmlRenderer#7](https://github.com/AvaloniaUI/Avalonia.HtmlRenderer/pull/7)

Hi,man.maybe your suggestion can be a new way , can you give mes some demo or guide for Avalonia.HtmlRenderer. i do not konw how to use Avalonia.HtmlRenderer.although  i have read the AvaloniaUI/Avalonia.HtmlRenderer#7.

**Comment by spchamp** [comment]
For HTML display in a sense like of a WebView control with Avalonia, there is a WebViewControl-Avalonia available ([NuGet](https://www.nuget.org/packages/WebViewControl-Avalonia/)) ([GitHub](https://github.com/OutSystems/WebView ))  ([SampleWebView.Avalonia](https://github.com/OutSystems/WebView/tree/master/SampleWebView.Avalonia)). There's also a WebViewControl-Avalonia-RemoteDebugSupport ([NuGet](https://www.nuget.org/packages/WebViewControl-Avalonia-RemoteDebugSupport/)) from the same project. The NuGet package targets .NETStandard 2.0.

It uses CefGlue ([NuGet](https://www.nuget.org/packages/CefGlue.Avalonia/)) ([developer's fork](https://gitlab.com/joaompneves/cefglue)).

**Comment by sunsided** [comment]
Just to add to @spchamp's answer: From what I just learned, WebViewControl-Avalonia will currently not work on Linux. 
According to https://github.com/OutSystems/CefGlue/issues/18#issuecomment-917942591 (October '21):

> Linux support is not in the near future plans.

**Comment by erichiller** [comment]
Another option (although I haven't tried it yet) is [CefNet](www.github.com/cefnet/cefnet)

**Comment by maxkatz6** [comment]
There are different solutions for this problem.
Probably the most popular - to bundle CEF engine with the app using CefGlue or CefNet.
Or to use very simple Avalonia.HtmlRenderer with limited rendering capabilities.
Or to use native web views (Edge, Safari...) via NativeControlHost like here https://github.com/maxkatz6/AvaloniaWebView
