### ISSUE TITLE
KeySpline parsing depends on culture decimal separator

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#4645]
This test fails for me:

https://github.com/AvaloniaUI/Avalonia/blob/19ff17f409f20b849cc27d3225080843a06ce6bc/tests/Avalonia.Animation.UnitTests/KeySplineTests.cs#L17

This is because my `CultureInfo` uses `,` as decimal separator.

Culture is passed here:

https://github.com/AvaloniaUI/Avalonia/blob/19ff17f409f20b849cc27d3225080843a06ce6bc/src/Avalonia.Animation/KeySplineTypeConverter.cs#L20-L23

Then here:

https://github.com/AvaloniaUI/Avalonia/blob/19ff17f409f20b849cc27d3225080843a06ce6bc/src/Avalonia.Animation/KeySpline.cs#L82-L91

I did a quick search and usually `CultureInfo.InvariantCulture` is passed to `StringTokenizer` constructor (https://github.com/AvaloniaUI/Avalonia/search?q=StringTokenizer&type=code).

**Comment by Gillibald** [comment]
That's the reason why tests are failing for me 😅
