### ISSUE TITLE
Designer does not work with fresh project

### ISSUE THREAD

**Issue by DoctorLogiq** [AvaloniaUI/Avalonia#4646]
Upon creating an Avalonia MVVM app, the MainWindow designer does not work. The program runs just fine, but the designer keeps erroring in the console, saying;

```
[Information] 1192 Connection initialized
20:28:02.153 [Error] 1192 UpdateXamlResult error
System.Xaml.XamlException: 'Unable to resolve type MainWindowViewModel from namespace clr-namespace:MyApp.ViewModels;assembly=MyApp (line 5 position 10) Line 5, position 10.' Line number '5' and line position '10'.

``` 

, which is pointing to the `vm:` (ViewModel) namespace.

I tried uninstalling the preview version of Visual Studio 2019 and installing the regular community edition, this didn't fix the issue. This is also a fresh installation on a fresh Windows install which was done yesterday.

The project has not been modified at all.

The extension is installed.

**Comment by Streamfire** [comment]
I've only just started using Avalonia yesterday and ran into this problem too, what fixed it for me was removing
`assembly=MyApp` 
from the namespace declaration.
Wierdly enough i tried to recreate the problem just now and can't get it to not work.

**Comment by MikeCodesDotNET** [comment]
Tested the previewer and it seems to be working.
