### ISSUE TITLE
Avalonia.diagnostics & Microsoft.CodeAnalysis version clash

### ISSUE THREAD

**Issue by MartyIX** [AvaloniaUI/Avalonia#4647]
I can see that https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Diagnostics/Avalonia.Diagnostics.csproj#L27 requires `Microsoft.CodeAnalysis.CSharp.Scripting` version `3.4.0`. However, I have already `Microsoft.CodeAnalysis.CSharp` version `3.6.0` so I have a conflict in my project. 

Can `avalonia.diagnostics` possibly require 3.4+ versions? 

Cheers!

**Comment by SuperJMN** [comment]
Same here!

**Comment by YBAZAN** [comment]
Any news on this point?

**Comment by Gillibald** [comment]
#9244

**Comment by Crauzer** [comment]
This is still an issue, 
![image](https://user-images.githubusercontent.com/18646077/211147310-d4909d69-2f87-4509-92b6-7c8205f0a21e.png)
![image](https://user-images.githubusercontent.com/18646077/211147327-7b1ea952-5bf5-42f6-94b2-36a715502de8.png)

How can I fix this ?

**Comment by kekekeks** [comment]
You need to _directly_ reference a newer version from your project
