### ISSUE TITLE
Selection and ObservableCollection issue

### ISSUE THREAD

**Issue by MagnificentEagle** [AvaloniaUI/Avalonia#4654]
### Reproduction steps (i used ControlCatalog):
1. Add a "Delete" button to the TabControl page:
```xml
<Button Command="{Binding DeleteTab}" Content="Delete"/>
```
2. Change List to ObservableCollection:
```c#
private class PageViewModel : ReactiveObject
{
    private ObservableCollection<TabItemViewModel> _tabs;

    private Dock _tabPlacement;

    public ObservableCollection<TabItemViewModel> Tabs
    {
        get => _tabs;
        set => this.RaiseAndSetIfChanged(ref _tabs, value);
    }

    public Dock TabPlacement
    {
        get { return _tabPlacement; }
        set { this.RaiseAndSetIfChanged(ref _tabPlacement, value); }
    }

    private void DeleteTab()
    {
        Tabs.RemoveAt(0);
    }
}
```
3. Launch the application, click on the button and this will happen:
![8EUjwBGlpR](https://user-images.githubusercontent.com/44552715/92906751-2ab6e380-f43e-11ea-9134-269385d50b2d.gif)

I'm guessing this was broken after the global changes related to the SelectionModel, since TabControl hasn't changed

Used the most recent preview of Avalonia

**Comment by grokys** [comment]
Thanks for the excellent repro! On it now.

**Comment by MagnificentEagle** [comment]
Perhaps this information can be useful.

If you delete any item before the selection, shows the previous item, not the selected one before deletion.
The deleted item is displayed here:
![MvJDM6TwAA](https://user-images.githubusercontent.com/44552715/92991343-b000cd80-f4fc-11ea-8c44-e17bbd4fe873.gif)

And here is the previous one:
![J05gULjRiD](https://user-images.githubusercontent.com/44552715/92991562-2baf4a00-f4fe-11ea-9b86-8ee990210ff1.gif)

When removing the last item, it highlights the first one (I don't think this will be critical).
