### ISSUE TITLE
Any way to change EGL opengl es version?

### ISSUE THREAD

**Issue by dtatarnikov** [AvaloniaUI/Avalonia#4656]
Now OPENGL ES version is hardcoded in EGL
https://github.com/AvaloniaUI/Avalonia/blob/fb9fa9403764691f2edeb2aba586eb7c61cb2d11/src/Avalonia.OpenGL/EglDisplay.cs#L75
Is there any way to change this without overriding all classes? I need OPENGL ES 3.2 profile.

**Comment by danwalmsley** [comment]
#4675 implements this.
