### ISSUE TITLE
Consider separation of builds into desktop, mobile, tests and samples

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaUI/Avalonia#4662]
Hello!

Consider separation of builds into desktop, mobile, tests and samples.

At the moment, we have to wait for builds that are not needed. For example, wait for builds of tests and samples when it is time to check the functionality in reality. Also, maybe it seems to me that it would simplify something like this #4661?

**Comment by kekekeks** [comment]
You arent required to build the entire solution to run the control catalog.

CI build script will always build and check everything.

**Comment by rstm-sf** [comment]
Yes, but if, for example, I need to create my own nugets, then I will have to go through all this too. It would be nice if it was optional

**Comment by kekekeks** [comment]
You can run nuke targets separately and with dependencies skipped

**Comment by rstm-sf** [comment]
Sorry, I did not understand how to skip building tests and samples from Compile
https://github.com/AvaloniaUI/Avalonia/blob/b793c2f17a05080492bdbb8afc38673cb3f65182/nukebuild/Build.cs#L142-L161

**Comment by kekekeks** [comment]
You can skip `Compile` entirely and just run `dotnet build` manually
