### ISSUE TITLE
[Enhancement][Proposal][DevTools] Custom Property Editor  for the value of control properties

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#4665]
I would like to propose to replace [this](https://github.com/AvaloniaUI/Avalonia/blob/fec8341176acf383233e218422c613ad9fc3adbf/src/Avalonia.Diagnostics/Diagnostics/Views/ControlDetailsView.xaml#L25) with DataGridTemplateColumn and select the Template based on the property type, if no match is found the current behavior will be used.

**Comment by kekekeks** [comment]
@grokys
