### ISSUE TITLE
Designer fails to render on first <Image>

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#4669]
I have an axaml file with some images linked as `<Image Stretch="Uniform" Height="25" Width="25" Source="Resources/calendar.png" Margin="5"/>`. The images are marked as `AvaloniaResource` and everything builds and starts just fine (the images are visible once the program is started). But the designer won't render and the Error List shows "The resource [image source] could not be found" (it's always for the first image source).

Any suggestions? Or is this just a bug?

**Comment by kekekeks** [comment]
Looks like a bug, a minimal repro would help.

**Comment by derekantrican** [comment]
Sure, here you go (let me know if you need more info)

1. I created a new Avalonia project & solution
2. Right-clicked on the projected and added an existing item and chose a .png on my computer (had to change the file explorer filter to "All Items")
3. Changed the Build Action for the .png to "AvaloniaResource"
4. Changed MainWindow.axaml to this:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaImageIssue.MainWindow"
        Title="AvaloniaImageIssue">
  <Image Source="settings.png"/>
</Window>
```

The Error List shows "The resource settings.png could not be found" and the designer does not render (briefly it shows the text "Invalid markup" then is replaced by a tiny white square in the middle). Everything builds and runs just fine with my image showing in the running application

**Comment by derekantrican** [comment]
Note that this also seems to fail for the `Window.Icon` property

**Comment by mightypanda** [comment]
I get the same behaviour, still a bug?
