### ISSUE TITLE
UI freezes when using async/await (MacOS & Windows)

### ISSUE THREAD

**Issue by imaxs** [AvaloniaUI/Avalonia#4677]
Hi experts, 
I'm facing a very big trouble...
I just took the code from here https://habr.com/ru/post/505036/ _(it uses  [Nito.AsyncEx 3.0.1](https://blog.stephencleary.com/2013/01/async-oop-2-constructors.html)) but I don't observe asynchrony because the UI freezes.
Is it bug or feature?

I spent a few days looking for a solution, but I haven't found one yet. But I found people who faced the same problem as me. 

Does anyone know a solution?

Source code from URL:
**Model**
```
public class Movie
    {
        public int Id { get; set; }
        public int VoteCount { get; set; }
        public string PosterPath { get; set; }
        public string Title { get; set; }
        public double VoteAverage { get; set; }
        public string Overview { get; set; }
        public string ReleaseDate { get; set; }

        [JsonIgnore]
        public Bitmap Poster { get; set; }
    }
```

**Services**
```
public class MovieService
    {
        readonly string _workingDirectory = Environment.CurrentDirectory;
        public async Task<IEnumerable<Movie>> GetMovies(int pageIndex)
        {
            var folderPath = $"{_workingDirectory}\\Data\\Page{pageIndex}";
            var dataFile = $"page{pageIndex}.json";
            var imageFolder = Path.Combine(folderPath, "Images");
            List<Movie> items;

            //read data
            using (var r = new StreamReader(Path.Combine(folderPath, dataFile)))
            {
                var json = r.ReadToEnd();
                items = JsonConvert.DeserializeObject<List<Movie>>(json);
            }

            //load images
            foreach (var item in items)
            {
                var imagePath = Path.Combine(imageFolder, $"{item.Title}.png");
                item.Poster = await GetPoster(imagePath);
            }
            return items;
        }

       private Task<Bitmap> GetPoster(string posterUrl)
        {
            return Task.Run(() =>
            {
                using var fileStream = new FileStream(posterUrl, FileMode.Open, FileAccess.Read) {Position = 0};
                var bitmap = new Bitmap(fileStream);
                return bitmap;
            });
        }
    }
```

**ViewModel**
```
public class MainWindowViewModel : ViewModelBase
    {
        private MovieService _movieService;
        public MainWindowViewModel()
        {
            InitializationNotifier = NotifyTaskCompletion.Create(InitializeAsync());
        }

        public INotifyTaskCompletion InitializationNotifier { get; private set; }

        private async Task InitializeAsync()
        {
            _movieService = new MovieService();
            var data = await _movieService.GetMovies(1);
        await Task.Delay(1000);
            MyItems = new ObservableCollection<Movie>(data);
        }

        private ObservableCollection<Movie> _myItems;
        public ObservableCollection<Movie> MyItems
        {
            get => _myItems;
            set
            {
                if (value != null)
                {
                    _myItems = value;
                    OnPropertyChanged();
                }
            }
        }
    }
}
```

PS. I also tried several different methods as explained in the documentation but none of them were successful

**Comment by danwalmsley** [comment]
is the GetMovies method long running before it gets to await? everything until the line `item.Poster = await GetPoster(imagePath);` is synchronous and blocking the UI Thread...

You could run all of that inside a Task... with Task.Run or something...

**Comment by imaxs** [comment]
> is the GetMovies method long running before it gets to await?
does it matter? this method is executed inside _async Task InitializeAsync()_ 

> with Task.Run or something
No.

I have a large list of filenames that are loading from a file or a database _(no difference)_ and I need to send it to a Listbox in a View. Since the list is very large, I do data loading asynchronously. Freezing occurs during data transfer to View. I have tried using dispatcher but it doesn't work like WPF. I mean WPF has no problem with that.

**Comment by maxkatz6** [comment]
> does it matter? this method is executed inside async Task InitializeAsync()

It does matter. Marking your class with "async" keyword will not replace all the code invoked inside with async alternatives.
You synchronously reads json file with ReadToEnd method. You should try to replace it with ReadToEndAsync one. 
Calling InitializeAsync from UI thread will block it while app is reading the file. **However** it shouldn't freeze the window for noticeable time. 

I found that code on github - https://github.com/speeedforce/Moviewer
And everything works fine for me on Windows even with sync ReadToEnd.
Can't check it with OSX though. @danwalmsley can you take a look?

**Comment by rstm-sf** [comment]
By the way, using ```Task<IEnumerable<Movie>>``` [is not a good idea](https://www.interact-sw.co.uk/iangblog/2013/11/29/async-yield-return). We need to use Rx, which is available out-of-the-box in Avalonia, or start [using `IAsyncEnumerable<T>`](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/generate-consume-asynchronous-stream).

**Comment by imaxs** [comment]
> However it shouldn't freeze the window for noticeable time.

I am using Avalonia Material and I have a Material style button, when I click on the button another view is shown via ReactiveUI Routing. Freezing is very noticeable in the animation of the material button.

Look at this:
![](https://s1.gifyu.com/images/ex.gif)
_Freeze occurs when I click on the bottom button_

**Comment by imaxs** [comment]
I created an example where this problem is present. Link — [gitlab](https://gitlab.com/imaxs/avalonia-trouble )
![](https://s1.gifyu.com/images/ezgif-4-312bd83582e7.gif)
_Freeze occurs when I click on the right button_

I would also like to report on the bugs/strange behavior of a window, resizing with MinHeight moves it up.
How its work now:
![](https://s1.gifyu.com/images/ezgif-4-5c10b8a9a7af.gif)

Below is how it should look:
![](https://s1.gifyu.com/images/ezgif-4-dfe9a0c38ab8.gif)
