### ISSUE TITLE
AvaloniaProperty variable name requires explicit syntax or it causes build errors

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#4682]
This gave me a headache for quite a few hours until I saw [this comment](https://github.com/AvaloniaUI/Avalonia/issues/3682#issuecomment-601618465)

It seems that when creating an AvaloniaProperty for a UserControl, the format for the variable names is expected like this:
```
AvaloniaProperty xxxxxxxProperty
var xxxxxxx
```

For example:
```
public static readonly AvaloniaProperty<string> MyStringProperty = ....
public string MyString = ...
```

Doing anything else will cause build errors with no obvious reason. For example:
```
public static readonly AvaloniaProperty<string> MyStringProp = ....
public string MyString = ...
```

Gives the error:
"Unable to find suitable setter or adder for property MyString of type AvaloniaPropertyIssue:AvaloniaPropertyIssue.MyUserControl for argument Avalonia.Markup:Avalonia.Data.Binding, available setter parameter lists are:
System.String (line 13 position 26) Line 13, position 26.	AvaloniaPropertyIssue	C:\Users\derek\source\repos\AvaloniaPropertyIssue\AvaloniaPropertyIssue\MainWindow.axaml	13"

(It doesn't even indicate that the problem is with my property name but rather implies that the problem is with the property type itself or possibly even how I'm using the property)

Using "Prop" instead of "Property" on the end of the variable name will cause a build error. This is insane that the name of a variable could cause a build error.

**Comment by kekekeks** [comment]
The explicit naming is required by other XAML frameworks too, e. g. from [WPF documentation](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/dependency-properties-overview?view=netframeworkdesktop-4.8#dependency-properties-back-clr-properties)
>The naming convention of the property and its backing DependencyProperty field is important. The name of the field is always the name of the property, with the suffix Property appended. For more information about this convention and the reasons for it, see Custom Dependency Properties.

Failing to provide convention breaks several things in WPF as well.

**Comment by derekantrican** [comment]
Thanks for bringing that to my attention. Since it's the same as WPF I'll go ahead and close this

**Comment by maxkatz6** [comment]
@tlitookilakin thanks, added to the "defining-properties" page
