### ISSUE TITLE
Xaml Previewer not correctly working VS2019 .net 3.1

### ISSUE THREAD

**Issue by ThuCommix** [AvaloniaUI/Avalonia#4689]
I'm currently trying out the Xaml Previewer and according to the docs it should look like this:

![image](https://user-images.githubusercontent.com/3823625/93469914-73b0e100-f8f1-11ea-89cf-c1f9c8376f4d.png)

but for me it looks like that:

![image](https://user-images.githubusercontent.com/3823625/93469970-85928400-f8f1-11ea-9560-71fd9ffd888e.png)

am I doing something wrong or is it broken?

**Comment by ThuCommix** [comment]
Never mind, I forget to select a width and height.. maybe it should be already defined in the default template.

**Comment by rstm-sf** [comment]
In fact, the problem was this https://github.com/AvaloniaUI/Avalonia/pull/4433
