### ISSUE TITLE
Basic Avalonia App Pegs CPU Under Linux Under 0.10 nightly release

### ISSUE THREAD

**Issue by HankG** [AvaloniaUI/Avalonia#4693]
I was diagnosing some performance issues with ControlCatalog and decided to make the simplest app possible. I created the MVVM template. Then I swapped out the reference Avalonia libraries for the latest 0.10 build. While running on Windows produces basically 0% CPU, and on Mac about 1-2% CPU, on Linux it uses up 100% of a CPU. I attached the JetBrains performance profiler to the app for a few seconds after initialization which may provide some insight into what the app is doing during that time.

![TestAvaloniaPerformanceTrace](https://user-images.githubusercontent.com/1683691/93518633-11f57480-f8fb-11ea-887a-387cc57efc9c.png)

**Comment by maxkatz6** [comment]
@HankG probably it was fixed after https://github.com/AvaloniaUI/Avalonia/pull/4691
Can you check with current master?

**Comment by HankG** [comment]
> @HankG probably it was fixed after #4691
> Can you check with current master?

Sure! Will that be in the NuGet nightly build so available tomorrow?

**Comment by maxkatz6** [comment]
@HankG yes, look for next nightly or preview build.

**Comment by rstm-sf** [comment]
Only myget overflowed again and there are no changes now

**Comment by grokys** [comment]
Just freed up space on myget. We really need to host our own CI feed.

**Comment by HankG** [comment]
I've confirmed that the latest build fixes this bug. CPU use is now comparable to macOS.

**Comment by danwalmsley** [comment]
@HankG thanks... a preview build is coming shortly with that fix included.

**Comment by TobiasBrandt-ReitPteLtd** [comment]
When can we expect this fix to appear on NuGet? As far as I can tell the latest version (0.10.0-preview5) does still have the bug.

**Comment by TobiasBrandt-ReitPteLtd** [comment]
> When can we expect this fix to appear on NuGet? As far as I can tell the latest version (0.10.0-preview5) does still have the bug.

There is now a 0.10.0-preview6 that contains the fix. Thank you!
