### ISSUE TITLE
Position value is ignored in Linux

### ISSUE THREAD

**Issue by renjuashokan** [AvaloniaUI/Avalonia#4699]
Like mentioned in  https://github.com/AvaloniaUI/Avalonia/issues/3454 I'm unable to put  `WindowStartupLocation `  to `CenterScreen`, I calculated position as 

`Position.X = ScreenWidth/2 - WindowWidth/2.`

Then I found out the Position value is not getting updated.

```
     public void setLocation (PixelPoint pos) {
            using (var logger = new ScopeTrace (Debug.Logger, fileName)) {
                var screen = this.Screens.ScreenFromPoint (pos);
                
                var posX = screen.Bounds.Width / 2 - this.Width / 2;
                PixelPoint loc = new PixelPoint ((int) posX, pos.Y);
                logger.Debug ("calculated location is " + loc.ToString ());
                this.Position = loc;
                logger.Debug ("current location is " + this.Position.ToString ());
                if (this.Position != loc) {
                    logger.Error("Unable to update position");  // this is getting printed
                }
            }
        }
```
The function `setLocation` is called from `Opened` function in window.

Am I doing it correctly? or something wrong in the framework?

**Comment by danwalmsley** [comment]
@renjuashokan which version are you using?

**Comment by renjuashokan** [comment]
@danwalmsley version is "0.9.12"

**Comment by danwalmsley** [comment]
Can you try `0.10.0-preview5` and see if you have the issue still?

**Comment by danwalmsley** [comment]
Seems to work on 0.10

**Comment by renjuashokan** [comment]
@danwalmsley  the issue exists in `0.10.0-preview5`

**Comment by danwalmsley** [comment]
Which window manager and Linux distro?

**Comment by kekekeks** [comment]
> // this is getting printed

It will always be printed due to the asynchronous nature of X11. Position property is updated on actual position change notification from XOrg

**Comment by danwalmsley** [comment]
@renjuashokan I will close the issue since we now know why... iv tested the center screen and it does work. Feel free to reopen if you continue to have issues or need help.
