### ISSUE TITLE
Why was the Xaml loader replaced with an exception?

### ISSUE THREAD

**Issue by Triggs9** [AvaloniaUI/Avalonia#4703]
bare with me I am new to navigating around github a bit, but I am currently running into this just blatant exception when code existed in its place before hand.

src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:

Error: "No precompiled XAML found for AvalonStudio.App, make sure to specify x:Class and include your XAML file as AvaloniaResource"

Change log:
https://github.com/AvaloniaUI/Avalonia/commit/76f9c8fdc5831c4571147cf098b082741ea49f44#diff-f6c6084be99fb437fabbdf5e5dab5538

Current file:
at line 19:
https://github.com/AvaloniaUI/Avalonia/blob/d355007c57a71184e56f2d92d49cf83c05401413/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs

I am receiving the error in AvalonStudio here at line 27
https://github.com/VitalElement/AvalonStudio/blob/develop/AvalonStudio/AvalonStudio/App.paml.cs

with the x:Class defined here: https://github.com/VitalElement/AvalonStudio/blob/develop/AvalonStudio/AvalonStudio/App.paml

I am trying to push AvalonStudio and Avalonia into the same development environment and use my local Avalonia project instead of nuget Avalonia projects

some how my code behinds and the .xaml/.paml files are not being associated with each other
I have no clue how to get them associated again, but am currently trying to dig through AppBuilder to see where thats done; Not even sure if thats the correct approach though.

**Comment by kekekeks** [comment]
XAML compiler rewrites MSIL code and replaces that method call with compiled XAML loader. The exception means that XAML wasn't processed by compiler for some reason.

**Comment by kekekeks** [comment]
>I am trying to push AvalonStudio and Avalonia into the same development environment and use my local Avalonia project instead of nuget Avalonia projects

Import https://github.com/AvaloniaUI/Avalonia/blob/master/build/BuildTargets.targets it will enable XAML compiler for your project.

**Comment by danwalmsley** [comment]
Closing issue as this is answered. Please feel free to re-open if you have further questions or need help.

**Comment by Triggs9** [comment]
Thanks, that was the file I needed. I got past that issue using: 

``` xml
<ImportGroup>
    <Import Project="..\..\..\Avalonia\build\BuildTargets.targets" Condition="Exists('..\..\..\Avalonia\build\BuildTargets.targets')" />
</ImportGroup>
```

in my AvalonStudio.csproj file

I am wasn't super familiar with .targets files. I think that was my core issue thanks again for pointing me in the right direction

**Comment by Triggs9** [comment]
I am now getting the same error within Avalonia itself instead of within AvaloniaStudio:

No precompiled XAML found for avares://Avalonia.Controls.DataGrid/Themes/Default.xaml (baseUri: avares://AvalonStudio/App.xaml), make sure to specify x:Class and include your XAML file as AvaloniaResource

in this file line 13:
https://github.com/VitalElement/AvalonStudio/blob/develop/AvalonStudio/AvalonStudio/App.paml

when that project does have a reference to build at line 24:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls.DataGrid/Avalonia.Controls.DataGrid.csproj

**Comment by Triggs9** [comment]
I can't reopen: https://stackoverflow.com/a/21333938
