### ISSUE TITLE
DataGrid clear all text on Ctrl + C, Version: 0.10.0-preview5

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#4713]
When copy data with Ctrl + C all selected rows are emptied
Data is copied to clipboard as expected

Version: 0.10.0-preview5

```
<DataGrid 
                    CanUserReorderColumns="True"
                    CanUserResizeColumns="True"
                    CanUserSortColumns="True"
                    GridLinesVisibility="All"
                    IsReadOnly="True"
                    ClipboardCopyMode="IncludeHeader"
                    Items="{Binding SlicerProperties}">
```

Before Copy:
![UVtools_2020-09-22_17-00-54](https://user-images.githubusercontent.com/113281/93907479-48fdc880-fcf5-11ea-8d8b-33d92fa77fe0.png)

2 row copied
![UVtools_2020-09-22_17-01-02](https://user-images.githubusercontent.com/113281/93907519-5450f400-fcf5-11ea-9128-2be4c4580a21.png)

Ctrl + A & Ctrl +C
![UVtools_2020-09-22_17-01-05](https://user-images.githubusercontent.com/113281/93907551-5e72f280-fcf5-11ea-9271-cfd76fd82976.png)

**Comment by FoggyFinder** [comment]
Any updates?

**Comment by maxkatz6** [comment]
There is a PR to fix this problem
https://github.com/AvaloniaUI/Avalonia/pull/4722

But it is better to solve problem with TwoWay bindings instead, because current DataGrid clipboard implementation should "just work"
https://github.com/AvaloniaUI/Avalonia/issues/4721

**Comment by FoggyFinder** [comment]
Yeah, I saw these PRs/issues, maybe there is some workaround for now?

**Comment by FoggyFinder** [comment]
Answering to myself, an obvious one:
1. Set `ClipboardCopyMode` to `None`
2. Subscribe to `KeyUp` (or similar) event and write logic there

**Comment by sn4k3** [comment]
Further note: 

If `DataGrid.Items` bidding have no setter, it will crash the app

**Comment by timunie** [comment]
Hey @sn4k3 if you're still looking for a solution, you can set `ClipboardContentBinding` and this will let the copy command work as expected. 

Happy coding, Tim

/cc @FoggyFinder

**Comment by timunie** [comment]
Sure 

```xaml
<DataGrid Items="{Binding MyItems}">
    <DataGrid.Columns>
        <DataGridTextColumn Binding="{Binding Title}"
                            ClipboardContentBinding="{Binding Title}"
                            Header="Title"  />
          [ ... ]
    </DataGrid.Columns>
</DataGrid>
```
