### ISSUE TITLE
HotKey doesnt work on ToogleButton, Version: 0.10.0-preview5

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#4714]
```
<ToggleButton
          IsChecked="{Binding ShowLayerImageRotated}"
          HotKey="Ctrl + R"
          ToolTip.Tip="Auto rotate layer preview image at 90º (This can slow down the layer preview) [CTRL+R]"
          />
```
Expected behaviour: Invert checked of ToggleButton (Same action as click on it)

**Comment by maxkatz6** [comment]
It seems HotKey property works only if Command is set on the button/menuitem.

**Comment by sn4k3** [comment]
> It seems HotKey property works only if Command is set on the button/menuitem.

Just tried, didn't for me

**Comment by maxkatz6** [comment]
@sn4k3 and it invokes empty function. HotKey works with only Command now

**Comment by sn4k3** [comment]
Got it, so for my hotkey work in pair with mouse click  is there any way i know the command was called by a click or hotkey? That way i can invert ToogleState on hotkey but not on click

**Comment by sn4k3** [comment]
This is fixed on recent builds
