### ISSUE TITLE
Some control properties are not updated in real time as they are set? Version: 0.10.0-preview5

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#4716]
I just have cloned Slider -> SliderEx just to expose thumb with public getter, don't know if i can get it by code but:

```C#
<uc:SliderEx
          Grid.Column="2"
          Name="Layer.Navigation.Slider"
          Minimum="0"
          Maximum="{Binding SliderMaximumValue}"
          Ticks="{Binding SliderMaximumValue}"
          Value="{Binding ActualLayer}"
          TickFrequency="1"
          TickPlacement="Outside"
          SmallChange="1"
          LargeChange="10"
          IsSnapToTickEnabled="True"
          Margin="0,5,0,5"
          HorizontalAlignment="Right"
          Orientation="Vertical"/>

public uint ActualLayer
        {
            get => _actualLayer;
            set
            {
                if (!SetProperty(ref _actualLayer, value)) return;
                OnPropertyChanged(nameof(CanGoDown));
                OnPropertyChanged(nameof(CanGoUp));
                OnPropertyChanged(nameof(ActualLayerTooltip));
                OnPropertyChanged(nameof(LayerNavigationTooltipMargin));
                OnPropertyChanged(nameof(LayerPixelCountStr));
                OnPropertyChanged(nameof(LayerBoundsStr));
                ShowLayer();
            }
        }

        public Thickness LayerNavigationTooltipMargin
        {
            get
            {
                double top = 0;
                if (LayerSlider?.Track != null)
                {
                    double trackerPos = LayerSlider.Track.Thumb.Bounds.Height / 2 + LayerSlider.Track.Thumb.Bounds.Top;
                    double halfTooltipHeight = LayerNavigationTooltipBorder.Bounds.Height / 2;
                    top = (trackerPos - halfTooltipHeight).Clamp(0,
                        LayerSlider.Bounds.Height - LayerNavigationTooltipBorder.Bounds.Height);
                    
                }
                return new Thickness(
                    0,
                    top,
                    5,
                    0);
            }
        }
```

Video of effect: https://youtu.be/4fbsOdm_SF4

Things i tried without success:
```C#
LayerSlider.InvalidateArrange();
LayerSlider.Track.InvalidateArrange();
LayerSlider.Track.Thumb.InvalidateArrange();
// Subscribe slider Value propertychanged and call OnPropertyChanged(nameof(LayerNavigationTooltipMargin));
```

**Comment by sn4k3** [comment]
It seens this is not the only case, i now suspect that happen with tons of controls.
Another example i found is with ScrollViewer

```C#
Debug.WriteLine(
                $"Offset: {Offset} | \n" +
                $"MAX: {HorizontalScrollBarMaximum},{VerticalScrollBarMaximum} \n" +
                $"ViewPort: {Viewport.Width},{Viewport.Height} \n" +
                $"Relative: {relativeDisplayPoint}");
```

If i increase/descrease content size after display the debug message the `$"MAX: {HorizontalScrollBarMaximum},{VerticalScrollBarMaximum} \n" ` will always shows the previous value instead of new.

Are these updated latter? Any way to force a update to reflect the set value?

**Comment by sn4k3** [comment]
Another case:

```C#
<ComboBox 
        MinWidth="200"
        SelectedItem="{Binding SelectedPresetItem}"
        Items="{Binding Operation.Presets}"/>

public OperationChangeResolution.Resolution SelectedPresetItem
        {
            get => _selectedPresetItem;
            set
            {
                SetProperty(ref _selectedPresetItem, value);
                if (_selectedPresetItem is null || _selectedPresetItem.IsEmpty) return;
                Operation.NewResolutionX = _selectedPresetItem.ResolutionX;
                Operation.NewResolutionY = _selectedPresetItem.ResolutionY;
                Timer timer = new Timer(50);
                timer.Elapsed += (sender, args) =>
                {
                    SelectedPresetItem = null;
                    timer.Dispose();
                };
                timer.Start();
            }
        }
```

Without timer and directly set `SelectedPresetItem = null;` the combobox retains the old SelectedItem, with the timer hack it correctly clears combobox selection

**Comment by sn4k3** [comment]
Another hack to wait for correct bounds size to constrain a textblock.
On my machine the properties are updating in about 20ms after been set, why?

```C#
var timer = new Timer(10)
            {
                AutoReset = true
            };
            timer.Elapsed += (sender, args) =>
            {
                if (Bounds.Width == 0) return;
                DescriptionMaxWidth = Math.Max(Bounds.Width, ToolControl?.Bounds.Width ?? 0)-40;
                Description = toolControl.BaseOperation.Description;
                timer.Stop();
                timer.Dispose();
            };
            timer.Start();
```

**Comment by maxkatz6** [comment]
Model/ViewModel property setter is called before value is updated in the control.
I believe it is expected behavior. It works in same way as in WPF.

However I am not sure if it expected to not allow value updating in setter in case of ComboBox, even though it also has same behavior in WPF. @grokys 

By the way, I would recommend to use MVVM pattern, and do not interact with UI layer from Model/ViewModel layers directly.

**Comment by workgroupengineering** [comment]
i think there is some problem in your INotifyPropertyChanged implementation, try using [this](https://github.com/AvaloniaUI/Avalonia/blob/2d7b559f63ecb527cb9b68abf4fa642b75322976/src/Avalonia.Diagnostics/Diagnostics/ViewModels/ViewModelBase.cs) example.

**Comment by sn4k3** [comment]
> Model/ViewModel property setter is called before value is updated in the control.
> I believe it is expected behavior. It works in same way as in WPF.

So the only workarround to have the updated value is do with timers as i'm doing?
Some properties are not included OnPropertyChanged like Bounds
I'm new to WPF/Avalonia i come from WinForms, that's why this is strange to me

> However I am not sure if it expected to not allow value updating in setter in case of ComboBox, even though it also has same behavior in WPF. @grokys

If i directly set to null after been set to something else, there are rare cases where it blank the field, but very rare... It may due some delay when CPU is busy.
I guess GUI render run/update async from actual code?
Because if sync theres no way this could happen, example:

```
SelectedPresetItem = someobject; 
( Set value, propagate event, update ui, shows some object)
SelectedPresetItem = null; 
( Set value, propagate event, update ui, shows empty)
```


> By the way, I would recommend to use MVVM pattern, and do not interact with UI layer from Model/ViewModel layers directly.

I'm not using MVVM yet, but i'm with Model-View patternm i guess both patterns will produce same effect?

Model: https://github.com/sn4k3/UVtools/blob/master/UVtools.WPF/Controls/Tools/ToolChangeResolutionControl.axaml.cs#L12
View: https://github.com/sn4k3/UVtools/blob/master/UVtools.WPF/Controls/Tools/ToolChangeResolutionControl.axaml#L29

> i think there is some problem in your INotifyPropertyChanged implementation, try using this example.

I changed all my code with that implementation, same happens

**Comment by sn4k3** [comment]
For the first problem about Slider Thumb Bounds i found that a timer with 1ms is enough to fix the position:

```C#
_layerNavigationTooltipTimer.Elapsed += (sender, args) =>
            {
                Dispatcher.UIThread.InvokeAsync(() => RaisePropertyChanged(nameof(LayerNavigationTooltipMargin)));
            };
// ...

public void InvalidateLayerNavigation()
        {
            RaisePropertyChanged(nameof(CanGoDown));
            RaisePropertyChanged(nameof(CanGoUp));
            RaisePropertyChanged(nameof(ActualLayerTooltip));
            //RaisePropertyChanged(nameof(LayerNavigationTooltipMargin));

            RaisePropertyChanged(nameof(LayerPixelCountStr));
            RaisePropertyChanged(nameof(LayerBoundsStr));
            _layerNavigationTooltipTimer.Start();
        }
```

**Comment by ahopper** [comment]
I don't believe anything async or timed or multi threaded is happening, it is just the binding is called synchronously before updating parts of the control. Your timer will happen after the whole process has completed, a post to the ui thread would do the same thing.  It is generally not normal to mix up bindings and direct access to controls.

**Comment by sn4k3** [comment]
> I don't believe anything async or timed or multi threaded is happening, it is just the binding is called synchronously before updating parts of the control. Your timer will happen after the whole process has completed, a post to the ui thread would do the same thing. It is generally not normal to mix up bindings and direct access to controls.

That makes sense and i understand the workflow (Binding callback - my code - UI update) so my code stays in between.
What confuses me now are the set properties, like the example of combo box, but i done some debug and i see whats going on:

```C#
public OperationChangeResolution.Resolution SelectedPresetItem
        {
            get => _selectedPresetItem;
            set
            {
                RaiseAndSetIfChanged(ref _selectedPresetItem, value);
                if (_selectedPresetItem is null || _selectedPresetItem.IsEmpty) return;
                Operation.NewResolutionX = _selectedPresetItem.ResolutionX;
                Operation.NewResolutionY = _selectedPresetItem.ResolutionY;
                Debug.WriteLine($"Before null: {SelectedPresetItem}");
                SelectedPresetItem = null;
                Debug.WriteLine($"After null: {SelectedPresetItem}");
                Timer timer = new Timer(50);
                timer.Elapsed += (sender, args) =>
                {
                    Debug.WriteLine($"After null delayed: {SelectedPresetItem}");
                    //SelectedPresetItem = null;
                    timer.Dispose();
                };
                timer.Start();
            }
        }
```

> Before null: 1080 x 1920 (FHD)
> After null: 
> After null delayed: 

So the value is been set correctly but combobox retains the item view

**Comment by workgroupengineering** [comment]
> 
> 
> > Model/ViewModel property setter is called before value is updated in the control.
> > I believe it is expected behavior. It works in same way as in WPF.
> 
> So the only workarround to have the updated value is do with timers as i'm doing?
> Some properties are not included OnPropertyChanged like Bounds
> I'm new to WPF/Avalonia i come from WinForms, that's why this is strange to me
> 
> > However I am not sure if it expected to not allow value updating in setter in case of ComboBox, even though it also has same behavior in WPF. @grokys
> 
> If i directly set to null after been set to something else, there are rare cases where it blank the field, but very rare... It may due some delay when CPU is busy.
> I guess GUI render run/update async from actual code?
> Because if sync theres no way this could happen, example:
> 
> ```
> SelectedPresetItem = someobject; 
> ( Set value, propagate event, update ui, shows some object)
> SelectedPresetItem = null; 
> ( Set value, propagate event, update ui, shows empty)
> ```
> 
> > By the way, I would recommend to use MVVM pattern, and do not interact with UI layer from Model/ViewModel layers directly.
> 
> I'm not using MVVM yet, but i'm with Model-View patternm i guess both patterns will produce same effect?
> 
> Model: https://github.com/sn4k3/UVtools/blob/master/UVtools.WPF/Controls/Tools/ToolChangeResolutionControl.axaml.cs#L12
> View: https://github.com/sn4k3/UVtools/blob/master/UVtools.WPF/Controls/Tools/ToolChangeResolutionControl.axaml#L29
> 
> > i think there is some problem in your INotifyPropertyChanged implementation, try using this example.
> 
> I changed all my code with that implementation, same happens

Hi, what I suggested is wrong because I assumed you were using the MVVM approach.

The Usercontrol already implements INotifyPropertyChanged.

To use it you must declare a DirectProperty.

ex:

```csharp
        public static readonly DirectProperty<ToolChangeResolutionControl, OperationChangeResolution.Resolution> SelectedPresetItemProperty =
            AvaloniaProperty.RegisterDirect<ToolChangeResolutionControl, OperationChangeResolution.Resolution>(
                nameof(SelectedPresetItem),
                o => o.SelectedPresetItem
                , (o,v)=> o.SelectedPresetItem = v);

        public OperationChangeResolution.Resolution SelectedPresetItem
        {
            get => _selectedPresetItem;
            set
            {
                if (SetAndRaise(SelectedPresetItemProperty ,ref _selectedPresetItem, value))
                {
                    if (_selectedPresetItem is null || _selectedPresetItem.IsEmpty) return;
                    Operation.NewResolutionX = _selectedPresetItem.ResolutionX;
                    Operation.NewResolutionY = _selectedPresetItem.ResolutionY;
                }
            }
        }
```

**Comment by rstm-sf** [comment]
> I'm new to WPF/Avalonia i come from WinForms, that's why this is strange to me

@sn4k3 you can go through [this tutorial](https://avaloniaui.net/docs/tutorial/) without using reactiveui. Also you can look at [this](https://softwareengineering.stackexchange.com/a/300696) answer and [this](https://github.com/oxyplot/oxyplot/tree/develop/Source/Examples/WindowsForms/ExampleBrowser) project. MVP and MVVM are friends with each other, so there is an MVPVM approach and it is very good for winforms

**Comment by sn4k3** [comment]
I still think there's something wrong... Here another problem i'm facing:

```C#
public virtual void ZoomToRegion(Rect rectangle)
        {
            var ratioX = Viewport.Width / rectangle.Width;
            var ratioY = Viewport.Height / rectangle.Height;
            var zoomFactor = Math.Min(ratioX, ratioY);
            var cx = rectangle.X + rectangle.Width / 2;
            var cy = rectangle.Y + rectangle.Height / 2;


            Debug.WriteLine($"Before zoom: {Viewport}");
            Zoom = (int) (zoomFactor * 100); // This function sets the zoom so viewport will change, this set zoom and calls UpdateViewPort()
            Debug.WriteLine($"After zoom, viewport changed: {Viewport}");

            //CenterAt(new Point(cx, cy)); // If i call this here, it will move to the wrong position due wrong viewport

            Timer timer = new Timer(5)
            {
                AutoReset = false,
            };
            timer.Elapsed += (sender, args) =>
            {
                Dispatcher.UIThread.InvokeAsync(() =>
                {
                    // This will fix centerAt position
                    Debug.WriteLine($"1ms delayed viewport: {Viewport}");
                    CenterAt(new Point(cx, cy));
                });
            };
            timer.Start();

        }

private bool UpdateViewPort() //SizedContainer is a panel inside the scrollviewer
        {
            if (Image is null) return false;

            var scaledImageWidth = ScaledImageWidth;
            var scaledImageHeight = ScaledImageHeight;
            var width = scaledImageWidth <= Viewport.Width ? Viewport.Width : scaledImageWidth;
            var height = scaledImageHeight <= Viewport.Height ? Viewport.Height : scaledImageHeight;

            bool changed = false;
            if (SizedContainer.Width != width)
            {
                SizedContainer.Width = width;
                changed = true;
            }

            if (SizedContainer.Height != height)
            {
                SizedContainer.Height = height;
                changed = true;
            }

            if (changed)
            {
                Debug.WriteLine($"Update ViewPort: {DateTime.Now.Ticks}");
                InvalidateArrange();
            }

            return changed;
        }

public virtual void CenterAt(Point imageLocation)
         => ScrollTo(imageLocation, new Point(Viewport.Width / 2, Viewport.Height / 2));
```

Before zoom: 2010, 1254
Update ViewPort: 637372779474876561
After zoom, viewport changed: 2010, 1254
1ms delayed viewport: 1990, 1234
Render: 637372779474982454

Result if i use CenterAt without the timer:
![image](https://user-images.githubusercontent.com/113281/94974857-c3a1c180-0507-11eb-85b2-c1b72969866a.png)


Result using the 1ms timer: (The correct outcome)
![image](https://user-images.githubusercontent.com/113281/94974818-9a813100-0507-11eb-95bf-8ee40cf3bd4c.png)

No mater what control is and if i need to update a property and reuse it just after been set, i need a timer with 1ms or else the old value will always be returned.

Simple example:

> ScrollViewer.Offset = new Vector(20,20);
> Debug(ScrollViewer.Offset) --> 0, 0
> Timer.delay(1) -> Debug(ScrollViewer.Offset) --> 20, 20

My AppBuilder: (Can be related to this?)
```C#
public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .With(new Win32PlatformOptions { AllowEglInitialization = true})
                .With(new X11PlatformOptions { UseGpu = true, UseEGL = true })
                .With(new MacOSPlatformOptions { ShowInDock = true })
                .With(new AvaloniaNativePlatformOptions { UseGpu = true })
                .UseSkia()
                .LogToDebug();
```

**Comment by Gillibald** [comment]
As mentioned above MVVM is the way to go. Via binding you should not have these issues.

**Comment by sn4k3** [comment]
> you should not have these issues.

How? I'm using bindings everywhere since project start, just the app is not a MVVM approach.
At some point with MVVM i will have to run same code as now.

For example, the checkbox where i clear it after been set and it wont clear the text (Via Binding)

Also note that https://github.com/sn4k3/UVtools/blob/master/UVtools.WPF/Controls/AdvancedImageBox.cs is a ScrollViewer extension, all code is for internal calculations of zoom, coordinates, image show, etc so it require a correct reading of base control values like offset, horizontal and vertical bars and others.
If i take that class copy to a MVVM project, and put my control on a view i guess the problem will be still there, because the code is unchanged and so when it reach the part where it changes the viewport and adjust the view position it will still compute the wrong value.

I will try latter setup a new MVVM project and throw some examples in order to replicate this.

**Comment by devel0** [comment]
I have a similar problem, updating INotifyPropertyChanged binded object properties doesn't reflect in TextBlock.Text ; the thing happen in [follow repro](https://github.com/devel0/repros/tree/avalonia/textblock-update) ( *branch: avalonia/textblock-update* )


[code](https://github.com/devel0/repros/blob/e24bd18393cc6647812d8af2c85c37def006d60e/avalonia/app/MainWindow.axaml.cs#L46-L67)

```csharp
    public MainWindow()
    {
        InitializeComponent();

        this.PointerMoved += (a, b) =>
        {
            this.InvalidateVisual();
        };
    }

    public override void Render(DrawingContext context)
    {
        base.Render(context);

        // NOT WORKING
        // ++Value;

        // WORKING
        Dispatcher.UIThread.Post(() => ++Value);

        Debug.WriteLine($"Value:{Value}");
    }
```

The need to use Dispatcher.UIThread seems to be required if property update are under override of Render method, while in others, for example in a button callback, that is not required.

Any observation or direction for better handling ? I need to override Render because I working withing a customized graphic control.

**Comment by timunie** [comment]
> The need to use Dispatcher.UIThread seems to be required if property update are under override of Render method, while in others, for example in a button callback, that is not required.

Yeah, I think Render has it's own thread in 11.0, so it's expected that the event must be redirected to the UIThread.
