### ISSUE TITLE
A UserControl that overrides TabItem does not show up in the TabControl

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#4717]
In vanilla WPF:

MainWindow.xaml:
```
<Window x:Class="MyProjectWPF.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:MyProjectWPF"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <TabControl>
        <TabItem Header="Tab1"/>
        <local:ScrollTab Header="Tab2"/>
        <TabItem Header="Tab3"/>
    </TabControl>
</Window>
```

ScrollTab.xaml:
```
<TabItem x:Class="MyProjectWPF.ScrollTab"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:MyProjectWPF"
             mc:Ignorable="d" 
             d:DesignHeight="450" d:DesignWidth="800">
    <Grid>
            
    </Grid>
</TabItem>
```

ScrollTab.xaml.cs:
```
using System.Windows.Controls;

namespace MyProjectWPF
{
    public partial class ScrollTab : TabItem
    {
        public ScrollTab()
        {
            InitializeComponent();
        }
    }
}
```

Produces the following window:
![image](https://user-images.githubusercontent.com/1558019/93926844-e8f32c00-fccc-11ea-98ae-034d915408cc.png)

But the equivalent in Avalonia produces this window (I can provide exact source code if need be):
![image](https://user-images.githubusercontent.com/1558019/93927033-2b1c6d80-fccd-11ea-9e22-2d8f8aca0d26.png)

*(Note how Tab2 is missing in the Avalonia example)*

Is there something I'm doing wrong or is it simply a bug in Avalonia?

**Comment by MarchingCube** [comment]
Without seeing your Avalonia code I would say that you probably need to define a `StyleKey` that is set to `typeof(TabItem)` (https://github.com/AvaloniaUI/Avalonia/issues/4321) . Otherwise your tab item will no control template.

**Comment by grokys** [comment]
In WPF you have to call `DefaultStyleKeyProperty.OverrideMetadata` to tell WPF to use a different style key than the class you're inheriting from. In Avalonia, this is done automatically, so the reason your control isn't displaying is that there's no theme/default style defined for your control.

In order to use the style of the base class, you need to implement `IStyleable.StyleKey` and return the type of the control whose style you want to use:

```csharp
    public partial class ScrollTab : TabItem, IStyleable
    {
        public ScrollTab()
        {
            InitializeComponent();
        }

        Type IStyleable.StyleKey => typeof(TabItem);
    }
```

**Comment by derekantrican** [comment]
Ah, perfect. That solved my issue!
