### ISSUE TITLE
Add DisplayMemberPath and SelectedValuePath properties

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#4718]
Avalonia seems to be missing the [DisplayMemberPath](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.itemscontrol.displaymemberpath?view=netcore-3.1) property for ItemsControl and the [SelectedValuePath](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.selector.selectedvaluepath?view=netcore-3.1#System_Windows_Controls_Primitives_Selector_SelectedValuePath) property for Selector. This would be useful for higher-level controls like ComboBox. Please add them.

**Comment by maxkatz6** [comment]
Can't it be replaced with item template?

**Comment by derekantrican** [comment]
I found the workaround for `DisplayMemberPath` using something like:

              <ComboBox.ItemTemplate>
                <DataTemplate>
                  <TextBlock Text="{Binding Name}"/>
                </DataTemplate>
              </ComboBox.ItemTemplate>

Is there a similar workaround for `SelectedValuePath`?

**Comment by maxkatz6** [comment]
I don't think it is possible now.
As a workaround you can create additional property in your viewmodel.

**Comment by magom001** [comment]
Seems to a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/1409

**Comment by magom001** [comment]
@derekantrican have you found a simple workaround? It is a no-brainer in wpf.  Displaying a combox in a datagrid is a nightmare without these properties.

**Comment by derekantrican** [comment]
I think I ended up doing what @maxkatz6 suggested and creating another property in the viewmodel

**Comment by WizMe-M** [comment]
> I found the workaround for `DisplayMemberPath` using something like:
> 
> ```
>           <ComboBox.ItemTemplate>
>             <DataTemplate>
>               <TextBlock Text="{Binding Name}"/>
>             </DataTemplate>
>           </ComboBox.ItemTemplate>
> ```

This isn't working with MultiBinding and StringFormat. Next template

                <ComboBox.ItemTemplate>
                    <DataTemplate>
                        <TextBlock>
                            <TextBlock.Text>
                                <MultiBinding StringFormat="{}{1} {0}">
                                    <Binding Path="FirstName" />
                                    <Binding Path="SecondName" />
                                </MultiBinding>
                            </TextBlock.Text>
                        </TextBlock>
                    </DataTemplate>
                </ComboBox.ItemTemplate>

causes `(unset) (unset)` over placeholder when its null.
How could it be fixed?

**Comment by thomaslevesque** [comment]
The lack of DisplayMemberPath is easy to work around with a data template (although excessively verbose). The lack of SelectedValuePath, on the other hand, is really annoying. It really makes the viewmodel much more complicated than it needs to be.

**Comment by CollinAlpert** [comment]
I am also really struggling without SelectedValuePath. This would be really cool to have.

**Comment by ahmedmohammedfawzy** [comment]
I hope this get implemented soon.

**Comment by maxkatz6** [comment]
SelectedValuePath as it is in WPF won't be implemented. We need a reflection friendly solution.
Alternatively, it's possible to implement SelectedValuePath as it is in WPF, but with requiring x:DataType, so compiler will know exact type.

**Comment by thomaslevesque** [comment]
> Alternatively, it's possible to implement SelectedValuePath as it is in WPF, but with requiring x:DataType, so compiler will know exact type.

I assume this would be specified on the DataTemplate?
Sounds good to me! I don't mind having to specify the type, as long as I can use the feature.

**Comment by timunie** [comment]
I feel like `DisplayMemberPath` could be `DisplayMemberBinding (type: IBinding?)` instead. This would have the following benefits imo: 
- Internally it would be converted into a binding anyway
- You can use `CompiledBinding` or `ReflectionBinding` based on your needs
- You can pass StringFormat inside the Binding 
- You can also use `MultiBinding`

I have no idea if that would also work for `ValueMemberPath` in a similar way. 

What do you think? Would this be a good addition to Avalonia?

**Comment by langsisi** [comment]
> SelectedValuePath as it is in WPF won't be implemented. We need a reflection friendly solution. Alternatively, it's possible to implement SelectedValuePath as it is in WPF, but with requiring x:DataType, so compiler will know exact type.

I don't understand how to implement SelectedValuePath

**Comment by timunie** [comment]
@langsisi please see the PR for details: https://github.com/AvaloniaUI/Avalonia/pull/10180
