### ISSUE TITLE
TabItem IsVisible = False will never show up again after set true, 0.10.0-preview5

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#4719]
`<TabItem IsVisible="{Binding boolVarHere}">`

This correctly hides TabItem from TabControl, but when set the variable to true it won't show up ever again

**Comment by maxkatz6** [comment]
@sn4k3 
It works for me with current master.
Can you test it with nightly builds? There were some fixes in SelectionModel that could affect this.

**Comment by sn4k3** [comment]
There's any place i can download the compiled nightly builds? Or i need to compile the master?
I'm currently using nuget package on the project

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

**Comment by sn4k3** [comment]
Still not working, tried with: 0.10.999-cibuild0010903-beta

**Comment by maxkatz6** [comment]
@sn4k3 control should be notified when value was changed.
For instance, it can be achieved using INotifyPropertyChanged or AvaloniaProperty.
In your code you have INotifyPropertyChanged in the Window, but there is no any notifications when HaveGCode is changing.
As solution, you can run OnPropertyChanged(nameof(HaveGCode)) when file is loaded/unloaded and HaveGCode changes its value.

**Comment by sn4k3** [comment]
I force a data context reload on every file load:

```C#
public void ResetDataContext()
        {
            var old = DataContext;
            DataContext = new object();
            DataContext = old;
        }
```

As told with Enable property it work good: When file is closed it got disabled, when file is loaded it got enabled
But i will try `OnPropertyChanged(nameof(HaveGCode))`

**Comment by sn4k3** [comment]
Just tried with OnPropertyChanged(nameof(HaveGCode)). Still doesnt work is IsVisible

**Comment by sn4k3** [comment]
Video: https://youtu.be/FsLMC8s3u-g

**Comment by maxkatz6** [comment]
@sn4k3 can you share some file example, so I can try to reproduce it in the app?

**Comment by sn4k3** [comment]
Sure, try this one

[_BK-12_Ball_Screw_Bearing_Block_1_copy.zip](https://github.com/AvaloniaUI/Avalonia/files/5271855/_BK-12_Ball_Screw_Bearing_Block_1_copy.zip)

**Comment by maxkatz6** [comment]
Thanks. I reproduced it.
Weird that it worked for me after I replaced HaveGCode with simple property and updating value with OnPropertyChanged after 5 seconds delay in window ctor.

I will take a deeper look later.

**Comment by sn4k3** [comment]
Any new on this? i still have this problem with rc1

**Comment by kekekeks** [comment]
@grokys

**Comment by grokys** [comment]
Pinging @Gillibald as he wrote the `TabControl` and may be able to fix it quicker than me.

**Comment by maxkatz6** [comment]
Works now

**Comment by sn4k3** [comment]
> Works now

I still have the problem...
On: 0.10.10

![UVtools_2021-11-01_04-47-55](https://user-images.githubusercontent.com/113281/139623066-017a39d0-efd1-415a-af6e-243af68f5b59.png)

**Comment by sn4k3** [comment]
No longer a problem with v11.
