### ISSUE TITLE
Menu with submenu focus problems on Linux (Ubuntu)

### ISSUE THREAD

**Issue by HendrikMennen** [AvaloniaUI/Avalonia#4729]
On linux (or at least Ubuntu) it is quite hard to use a menu with a submenu because the submenu closes too easily.
If you use it very carefully it sometimes works as you can see here:
![ezgif-2-e1650610abcc](https://user-images.githubusercontent.com/25281882/94004986-d7c62000-fd9d-11ea-9b89-ecd90f5ff111.gif)
(Sorry for the small picture I hope you can see the issue)
Looks like it loses focus if you move your pointer too fast.
On Windows this works without problems.

Tested OS: Ubuntu 18.04, Ubuntu 20.04
Avalonia 0.10 Preview 5

**Comment by maxkatz6** [comment]
It can be reproduced with OverlayPopups=true on Windows as well.

**Comment by HendrikMennen** [comment]
Interesting. I don't know what this option does but setting it to false on linux does not seem to change anything

**Comment by Deadpikle** [comment]
I'm experiencing this as well, but one "workaround" for users is that keyboard navigation to submenus still works.
