### ISSUE TITLE
are there box shadows like css?

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#4730]
hi, i'm design controls for avalonia, and now I wanna port flutter widgets to avalonia, but a lot of these controls have boxshadows, are there the same or similar in avalonia?

**Comment by jmacato** [comment]
Yes, we have drop shadow support in our 0.10 preview builds. @kekekeks @maxkatz6 we should write a doc about these new features later

**Comment by kekekeks** [comment]
box-shadow spec is implemented with standard CSS syntax in 0.10

**Comment by danwalmsley** [comment]
Its on `Border` control.
