### ISSUE TITLE
HotKey dont carrier the CommandParameter and System.NullReferenceException, Version: 0.10.999

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#4735]
```C#
<MenuItem 
          Name="MainMenu.File.Save" 
          Header="_Save" 
          HotKey="Ctrl+S" InputGesture="Ctrl+S"
          IsEnabled="{Binding CanSave}"
          Command="{Binding MenuFileSaveClicked}"
          CommandParameter="true"
          >

public void MenuFileSaveClicked(bool saveAs = false)
        {
            Debug.WriteLine(saveAs);
            if (!CanSave) return;
        }
```

When clicking the button it works as expected, however if use the hotkey it will trigger a NullReferenceException, even when function was a optional parameter

> Exception thrown: 'System.NullReferenceException' in Avalonia.Base.dll
> Object reference not set to an instance of an object.

If i change my `bool saveAs` to `string saveAs = "test"` no thrown exception but still the parameter (saveAs) comes empty ""

Can overcome this with two separate commands for save and saveas, but again this is a inconsistent logic between what we expect from the hotkey to act like user click

**Comment by workgroupengineering** [comment]
related at issue #2446
