### ISSUE TITLE
await window.ShowDialog freezes GUI and window when call from eventclick? Version: 0.10.999

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#4747]
I'm creating the MenuItems on code and bind click event to a function (https://github.com/sn4k3/UVtools/blob/master/UVtools.WPF/MainWindow.axaml.cs#L1196) which shows a new tool window. The problem is with await window.ShowDialog, when using the await keyword everything will freeze (GUI+new window), if i execute without await it shows OK but code continues to run beside the ShowDialog... (https://github.com/sn4k3/UVtools/blob/master/UVtools.WPF/MainWindow.axaml.cs#L2348)

```C#
// In MainWindow ctor():
foreach (var menuItem in new[] { MenuTools, LayerActions})
            {
                foreach (var menuTool in menuItem)
                {
                    if (!(menuTool.Tag is Operation operation)) continue;
                    menuTool.Header = operation.Title;
                    menuTool.Click += (sender, args) => ShowRunOperation(operation.GetType());
                }
            }
// ...
        public Operation ShowRunOperation(Type type)
        {
            var operation = ShowOperation(type);
            RunOperation(operation.Result);
            return operation.Result;
        }

        public async Task<Operation> ShowOperation(Type type)
        {
            var typeBase = typeof(ToolControl);
            var classname = $"{typeBase.Namespace}.Tool{type.Name.Remove(0, Operation.ClassNameLength)}Control";
            var controlType = Type.GetType(classname);
            ToolControl control;

            bool removeContent = false;
            if (controlType is null)
            {
                controlType = typeBase;
                removeContent = true;
                control = new ToolControl(type.CreateInstance<Operation>());
            }
            else
            {
                control = controlType.CreateInstance<ToolControl>();
                if (control is null) return null;
            }

            if (!control.CanRun)
            {
                return null;
            }

            if (removeContent)
            {
                control.IsVisible = false;
            }

            var window = new ToolWindow(control);
            //window.ShowDialog(this);
            await window.ShowDialog(this);
            if (window.DialogResult != DialogResults.OK) return null;
            var operation = control.BaseOperation;
            return operation;
        }
```

Run without "await":
![image](https://user-images.githubusercontent.com/113281/94345787-58944e80-0020-11eb-8db8-ad8eee503bdc.png)

Run with "await": (Everything freezed - no respond)
![image](https://user-images.githubusercontent.com/113281/94345794-5f22c600-0020-11eb-80dc-6273885e5edb.png)

**Comment by kekekeks** [comment]
>return operation.Result;

You are synchronously waiting for the task on the UI thread. That causes a deadlock. Please, read [TAP.docx](https://www.microsoft.com/en-us/download/details.aspx?id=19957) thoroughly.

**Comment by sn4k3** [comment]
> > return operation.Result;
> 
> You are synchronously waiting for the task on the UI thread. That causes a deadlock. Please, read [TAP.docx](https://www.microsoft.com/en-us/download/details.aspx?id=19957) thoroughly.

I was doing the same for all other windows for example: https://github.com/sn4k3/UVtools/blob/master/UVtools.WPF/MainWindow.axaml.cs#L1308
But that was called from a Command Binding, is that different from calling from a regular event?

**Comment by kekekeks** [comment]
Using `async` or `await` doen't cause deadlocks. Using `Task.Result` or `Task.Wait()` does.

**Comment by sn4k3** [comment]
> Using `async` or `await` doen't cause deadlocks. Using `Task.Result` or `Task.Wait()` does.

Thank you for the information. I've update accordingly, it now works.
Will take a look at the document too.
