### ISSUE TITLE
DevTools don't show in non-primary monitor taskbars

### ISSUE THREAD

**Issue by PathogenDavid** [AvaloniaUI/Avalonia#4751]
# Steps to reproduce

I've reproduced this with both [XamlControlsGallery](https://github.com/AvaloniaUI/XamlControlsGallery/tree/29548cf16f518d03472bf96f5a60f9ceadc01074) and [Synfonia](https://github.com/jmacato/Synfonia/tree/a74e6f7b799d8240edf672b590027264095fc91a). (The former uses 0.10.0-preview5 and the latter appears to use the latest CI build.)

I reproduced this on Windows 10 2004. You will need multiple monitors.

1. Ensure you have per-display taskbars enabled with "Show taskbar buttons on" configured as "Main taskbar and taskbar where window is open" or "Taskbar where window is open":

![Screenshot of Windows settings showing the previously described configuration.](https://user-images.githubusercontent.com/278957/94377081-3a902200-00e4-11eb-8b7a-d4592e5e5fb4.png)

2. Start an Avalonia app
3. Open F12 DevTools
4. Drag the DevTools to a non-primary monitor

# Expected behavior

Avalonia DevTools shows up in the taskbar of the non-primary monitor.

# Actual behavior

Avalonia DevTools only shows on the taskbar of the primary monitor.

![Screenshot of Windows desktop showing actual behavior](https://user-images.githubusercontent.com/278957/94377126-ad999880-00e4-11eb-9ec5-071e6bb0e5a5.png)

**Comment by maxkatz6** [comment]
I guess the same problem is with any secondary window?
It shouldn't be DevTools specific.

**Comment by PathogenDavid** [comment]
That's could very well be true, this is just where I observed it while evaluating Avalonia.
