### ISSUE TITLE
The blurred background of a window extends outside the window when it is maximized

### ISSUE THREAD

**Issue by PathogenDavid** [AvaloniaUI/Avalonia#4753]
# Environment

Observed with both [XamlControlsGallery](https://github.com/AvaloniaUI/XamlControlsGallery/tree/29548cf16f518d03472bf96f5a60f9ceadc01074) and [Synfonia](https://github.com/jmacato/Synfonia/tree/a74e6f7b799d8240edf672b590027264095fc91a)  (The former uses 0.10.0-preview5 and the latter appears to use the latest CI build.)

Windows 10 2004

I have multiple monitors. (I don't believe it's relevant in this one, but my exact layout is described in https://github.com/AvaloniaUI/Avalonia/issues/4752)

# Steps to reproduce

1. Maximize the Avalonia window on one monitor
2. Look cloosely at the shared edge of the neighboring monitor

# Expected behavior

Everything looks normal

# Actual behavior

There's a thin strip of bluryness on the neighboring monitor:

![image](https://user-images.githubusercontent.com/278957/94378060-f30d9400-00eb-11eb-9baf-22a7f8edc35f.png)

This screenshot is showing the border between two monitors. To remove any change of ambiguity, here's a meatspace photo:

![image](https://user-images.githubusercontent.com/278957/94378190-12f18780-00ed-11eb-8e37-c500d0d93762.jpg)

**Comment by amwx** [comment]
This is actually an issue with Windows itself. When desiring a blurred window, DWM blurs everything including the dropshadow behind the window (you can see the same blurred outline around the window if you don't maximize it and place the edge of the window over something white, for example). When you maximize a window, Windows makes the window larger than the screen and then clips it down so you don't see the border & shadow, but for some reason the clipping doesn't occur properly when the window is blurred. I don't think there's an actual fix for it unless you want to get real hacky in the WndProc as the window maximizes/restores.

**Comment by PathogenDavid** [comment]
While I do agree Windows probably isn't making things easy on Avalonia here. I've observed this issue with other apps which draw their own window decorations and have noticed fix the issue after an update. (Unfortunately nothing open source comes to mind, although I do feel it was common on Node apps.)

**Comment by maxkatz6** [comment]
Yes, it is common for windowing with old Win32 API.
This also should be fixed after https://github.com/AvaloniaUI/Avalonia/pull/4346 will be merged, because it use WinUI.Composition for acrylic background, that doesn't have this issue.
