### ISSUE TITLE
Unsupported characters (specifically emojis) break the textbox

### ISSUE THREAD

**Issue by PathogenDavid** [AvaloniaUI/Avalonia#4755]
I realize [Emoji aren't supported yet](https://github.com/AvaloniaUI/Avalonia/issues/1817), but I'd expect the � to act appropriately. I'd also worry that other characters besides emojis could cause this.

Note: [This crashes instead after upgrading XamlControlsGallery to the latest CI.](https://github.com/AvaloniaUI/Avalonia/issues/4755#issuecomment-699707032), so this may have been fixed but I can't be sure until #4754 is fixed.

# Environment

Observed in [XamlControlsGallery](https://github.com/AvaloniaUI/XamlControlsGallery/tree/29548cf16f518d03472bf96f5a60f9ceadc01074) (which is using 0.10.0-preview5) while trying to reproduce #4754 with other Avalonia apps.

Windows 10 2004

# Steps to reproduce

1. Use Win+. to insert some emoji or copy paste these ones into the example text box: 😂😂😂
2. Try clicking in the middle of the ��� rendered as a placeholder for the emoji
3. Try pressing backspace a few times to delete the emoji
4. Try pressing delete a few times to forward-delete the emoji
5. Press home
6. Type `aaa`
7. Press end
8. Type `aaa` again
9. Press Ctrl+A and then backspace
10. Paste the emoji again
11. Press home
12. Press right arrow once
13. Type `aaa`

# Expected behavior

Sanity

# Actual behavior

Insanity

1. Works mostly as expected, you see ��� which is what you'd expect until https://github.com/AvaloniaUI/Avalonia/issues/1817 is done. However, the text cursor is at the beginning of the text box rather than the end.
2. You can't set the cursor into the middle of the emoji (it always renders as if it's at the start
3. You can't remove the emoji (maybe makes sense since the text cursor is at the start.)
4. You can't remove the emoji (doesn't make sense.)
5. ✅
6. ✅
7. Text cursor appears between `aaa` and `���` instead of at the end
8. The `aaa` appears at the end as expected, but the text cursor position is totally wrong.

![image](https://user-images.githubusercontent.com/278957/94378644-a8424b00-00f0-11eb-8bfa-faba8d1b823e.png)

9. ✅ The textbox is cleared even though deleting the emojis failed earlier
10. Same as 1
11. ✅
12. The text cursor doesn't advance (not a surprise at this point)
13. The text stops rendering entirely and the text cursor is floating in the textbox:

![image](https://user-images.githubusercontent.com/278957/94378660-e475ab80-00f0-11eb-97d5-e4c269c299c2.png)

-------------

This is possibly a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4754 since it seems to largely deal with the text measuring going haywire.

**Comment by PathogenDavid** [comment]
After modifying `XamlControlsGallery` to use `0.9.999-cibuild*` for the Avalonia package versions (just as Synfonia has), emojis cause a crash just like https://github.com/AvaloniaUI/Avalonia/issues/4754, but it's not clear if the behavior wouldn't just be the same if it wasn't crashing.

**Comment by jmacato** [comment]
Unicode works on `TextBlock`s but not on `TextBox`es, at least until @Gillibald refactors them sometime in the near future.

**Comment by PathogenDavid** [comment]
Makes sense. One thing I forgot to mention in the original issue: This does not happen with all Unicode. (For instance, using "日本語" instead of the three emojis works just fine.)

**Comment by jmacato** [comment]
yeah, Unicode BMP and CJK chars are kinda okay, but the textbox control as it is right now is just terrible when it comes to unicode...

**Comment by PathogenDavid** [comment]
That definitely aligns with my experiences today. I think it's probably a law of the universe that text input controls are either terrible to maintain or shatter in the face of edge cases. There is no in-between.

**Comment by Gillibald** [comment]
Y TextBox needs to properly handle surrogate pairs and grapheme clusters. That isn't currently the case. I will start rewriting the TextBox in October.

**Comment by PathogenDavid** [comment]
Ah, surrogate pairs! I kinda forgot that emojis needed them. Hopefully the new System.Rune stuff makes your life easier in that department.

**Comment by Gillibald** [comment]
This is our equivalent of System.Rune: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Media/TextFormatting/Unicode/Codepoint.cs
