### ISSUE TITLE
NumericUpDown with decimal plates?

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#4756]
I can't find a way to set the decimal plates on a NumericUpDown control, making control always act as ints, for example if i manual input 50.50 it will jump to 5050. After some dig i find that Increment can be used for that porpouse, so with Increment=0.01 i'm able to input decimal numbers with 2 plates. But this is not the optimal for me since i want increments of 1 and 2 decimal plates. There's anyway to do that?
I also find when using FormatString, eg: FormatString="{}{0:#,0.00} %" user will have to erase the % to be able to type the right number or it will jump for a huge number, i tried set number style to Any but the outcome is the same.

```
<NumericUpDown
          MinWidth="100"
          MaxWidth="150"
          Minimum="0.01"
          Maximum="359.99"
          Increment="0.01"
          FormatString="{}{0:#,0.00}"
          Value="{Binding Operation.AngleDegrees}"
          />
```

I'm also geting rounding problems when use the down/up arrows without a FormatString set and increments of 0.01
The value should be a decimal to prevent this or rounded to decimal plates

![image](https://user-images.githubusercontent.com/113281/94381337-ebbca980-0130-11eb-8a09-e55369fc678b.png)

**Comment by maxkatz6** [comment]
Decimal problem was fixed in this PR https://github.com/AvaloniaUI/Avalonia/pull/5981
