### ISSUE TITLE
DatePicker appears to interpret DayFormat as a .NET DateTime format string when it shouldn't

### ISSUE THREAD

**Issue by PathogenDavid** [AvaloniaUI/Avalonia#4757]
# Environment

Observed with [XamlControlsGallery](https://github.com/AvaloniaUI/XamlControlsGallery/tree/29548cf16f518d03472bf96f5a60f9ceadc01074) (with both 0.10.0-preview5 and the latest Avalonia CI build.)

Windows 10 2004

# The Problem

The `DatePicker` control appears to be incorrectly using its `DayFormat` as a .NET `DateTime` format string:

![image](https://user-images.githubusercontent.com/278957/94379384-87c8bf80-00f5-11eb-91f8-e6b4afa1a241.png)

I did not modify the example XAML, but here it is for reference:

```xml
<DatePicker x:Name="Control2" DayFormat="{}{day.integer} ({dayofweek.abbreviated})"
                               YearVisible="False" />
```

**Comment by amwx** [comment]
This is either a copy pasta mistake from the actual WinUI controls gallery or was created from a very early version of the DatePicker PR when I had originally tried to keep the WinUI formatting style (which was removed by request)
@danwalmsley 

`DatePicker` Day/Month/YearFormat properties require the format to be in normal .net datetime formatting, for example for the equivalent from winui (from above) it would be `DayFormat="d (ddd)"`

**Comment by PathogenDavid** [comment]
In that case this issue should probably be moved to https://github.com/AvaloniaUI/XamlControlsGallery/ and reworded to fix the example.
