### ISSUE TITLE
TabControl seemingly does not maintain per-tab scroll position

### ISSUE THREAD

**Issue by PathogenDavid** [AvaloniaUI/Avalonia#4758]
# Environment

Observed with [XamlControlsGallery](https://github.com/AvaloniaUI/XamlControlsGallery/tree/29548cf16f518d03472bf96f5a60f9ceadc01074) (with a slightly modified version to use the latest Avalonia CI build.)

Windows 10 2004

# Steps to reproduce

1. Launch the app
2. Go to the Date and Time page
3. Scroll down to the bottom
4. Switch to the Layout page

# Expected behavior

The page starts out at the top

(This is the behavior if you go straight to the Layout page.)

![image](https://user-images.githubusercontent.com/278957/94379603-18ec6600-00f7-11eb-9ae9-d621c377b3bc.png)

# Actual behavior

The page is already scrolled down slightly

![image](https://user-images.githubusercontent.com/278957/94379589-083bf000-00f7-11eb-89a1-09c1be5ea626.png)

**Comment by PathogenDavid** [comment]
Consider fixing https://github.com/AvaloniaUI/Avalonia/issues/4759 before this one because this bug (probably) makes it easier to reproduce.

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/XamlControlsGallery/blob/29548cf16f518d03472bf96f5a60f9ceadc01074/XamlControlsGallery/Styles/SideBar.xaml#L36

This has nothing to do with the TabControl directly. This is more of an issue withe the custom template. The TabControl'S content is wrapped inside a ScrollViewer and that is shared by all tabs. So to get your desired behavior the ContentTemplate needs to use a ScrollViewer instead.

**Comment by PathogenDavid** [comment]
Ah, I actually looked for that in the DevTools window but I guess I missed it. This issue should probably be move to the XamlControlsGallery repo then.
