### ISSUE TITLE
Is it possible to provide an embedded default font in the assembly

### ISSUE THREAD

**Issue by ghost** [AvaloniaUI/Avalonia#4760]

**Comment by Gillibald** [comment]
There are multiple ways to achieve this:

1. Set FontFamily on your window. Controlts will inherit this unless they have FontFamily explictily set.
2. Write a custom font manager and register it before startup https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Skia.UnitTests/Media/CustomFontManagerImpl.cs

**Comment by GaoJones** [comment]
There is an error in following the steps above

 

- [ ] 
![Uploading 微信图片_20210311152836.png…]()

**Comment by Gillibald** [comment]
You need to reupload the image or just copy/paste the output here

**Comment by 2420228300** [comment]
> There are multiple ways to achieve this:
> 
> 1. Set FontFamily on your window. Controls will inherit this unless they have FontFamily explicitly set.
> 2. Write a custom font manager and register it before startup https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Skia.UnitTests/Media/CustomFontManagerImpl.cs

The method I use in the connection is var typefaceCollection = SKTypefaceCollectionCache.GetOrAddTypefaceCollection(msjhTypeFace.FontFamily); The result is empty, is there a problem?

**Comment by go-nil** [comment]
I think, for users who using the lib, set FontFamily should have been easy. like ```FontFamily = "xxx";```.
It's bad to let users do a lot of complicated things just for a simple result.

sorry!

**Comment by Gillibald** [comment]
What is simple about text processing?

**Comment by go-nil** [comment]
> 

Which is better for users to write one line of code or more than 200 lines of code?
This is why the code should be encapsulated.

**Comment by timunie** [comment]
@go-nil if you have a really good idea how that can work in a x-plat solution like Avalonia, I think a PR is welcome. But keep in mind, we have to consider many different OS and also many different use-cases. I agree we will need more documentation on this topic.

**Comment by jgcodes2020** [comment]
> There are multiple ways to achieve this:
> 
>     1. Set FontFamily on your window. Controls will inherit this unless they have FontFamily explicitly set.
> 
>     2. Write a custom font manager and register it before startup https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Skia.UnitTests/Media/CustomFontManagerImpl.cs

So apparently we aren't supposed to register custom font managers, what now?

**Comment by Blazero** [comment]
> There are multiple ways to achieve this:
> 
>     1. Set FontFamily on your window. Controls will inherit this unless they have FontFamily explicitly set.
> 
>     2. Write a custom font manager and register it before startup https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Skia.UnitTests/Media/CustomFontManagerImpl.cs

Setting FontFamily on the MainWindow works fine for most controls, but it doesn't work for tooltips of button.
Is this intentional or just a bug? How to make it work?
