### ISSUE TITLE
Allow tooltips to have line breaks

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#4763]
Currently there's no way to have tooltips with multilines? Line break or \n wont work... eg:

```C#
<TextBlock
        Grid.Row="2"
        Grid.Column="0"
        ToolTip.Tip="Remove individual or small clusters of pixels in iterations.\nThis settings can remove noise from a layer, but will also remove fine details. Set iterations to 0 to diasble.\nWARNING: Even at low settings this operation has the potential to introduce new islands, as it may remove supporting material from previous layers."
        VerticalAlignment="Center"
        Text="Noise removal iterations:"/>
```

That tooltip will show into a single line with \n visible on text

**Comment by workgroupengineering** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/090f62a0a5b5f25eb635e416ce0f7ea426bc0892/samples/ControlCatalog/Pages/ToolTipPage.xaml#L33-L38

**Comment by sn4k3** [comment]
That did the trick, thank you

**Comment by sn4k3** [comment]
> &#x0a;

That also worked, nice too keep code clean. Thank you
