### ISSUE TITLE
Is it possible create a MarkupExtension?

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#4765]
Hello, now I'm thinking I make a RevealEffect, with this syntax:
```xml
   <Button Content="Text"  Background="{Reveal TintColor=Gray, FallbackColor=Black, CursorRadius=20, Opacity=0.5}"/>
```
But, is it possible? or is there other way to make the same?

**Comment by jp2masa** [comment]
The extension class should have the suffix `Extension` (e.g. `RevealExtension`) and a method `T ProvideValue(IServiceProvider provider)`. Then, to use it in XAML you have to import the namespace (e.g. `xmlns:local="clr-namespace:My.Namespace"`) and use it like: `{local:Reveal ...}`

Also, a complete example (except it doesn't have properties, in your case for example for `TintColor` you would have a property `public Color TintColor { get; set; }` in the extension class):

- Extension class: https://github.com/jp2masa/Movere/blob/0a0f6ff74bbebc546c36558c290a292054f8c38d/src/Movere/LocalizedStringExtension.cs
- Import namespace: https://github.com/jp2masa/Movere/blob/0a0f6ff74bbebc546c36558c290a292054f8c38d/src/Movere/Views/OpenFileDialog.xaml#L3
- Use markup extension: https://github.com/jp2masa/Movere/blob/0a0f6ff74bbebc546c36558c290a292054f8c38d/src/Movere/Views/OpenFileDialog.xaml#L59

**Comment by PieroCastillo** [comment]
thanks you :D
