### ISSUE TITLE
The tutorial is wrong.

### ISSUE THREAD

**Issue by Redageddon** [AvaloniaUI/Avalonia#4766]
I followed the tutorial up to Wiring up the Views and it is not acting how it is supposed to. <https://avaloniaui.net/docs/tutorial/wiring-up-views> it could either be an outdated tutorial, or avalona has a bug

**Comment by maxkatz6** [comment]
Can you tell what is wrong specifically? 
I haven't run code from tutorial now, but it looks fine.

**Comment by rubiksmaster02** [comment]
When i get up to the end of Wiring up the Views and run it, it shows up as blank. I think it is becuase its not detecting Path on any of the bindings. 
![image](https://user-images.githubusercontent.com/53098956/94478945-da06f080-0188-11eb-9a75-27a6d6d7135d.png)

**Comment by maxkatz6** [comment]
Did you set DataContext for your View?
If it works in runtime, but doesn't in the code editor - this could be a bug with Rider (I assume it is a Rider).

**Comment by FoggyFinder** [comment]
@rubiksmaster02 Can you attach the project ? So everyone could check the code.

**Comment by rstm-sf** [comment]
@rubiksmaster02 сan the [next step](https://avaloniaui.net/docs/tutorial/locating-views) help you?
