### ISSUE TITLE
100% cpu between 0.10.0-preview2 and preview3 (linux platform)

### ISSUE THREAD

**Issue by devel0** [AvaloniaUI/Avalonia#4772]
running the same avalonia code ( an empty window generated with `dotnet new avalonia.app -n test-empty` ) on linux ( ubuntu 20.04 ) I got 100% from 0.10.0-preview3 while it was ok before for example in 0.10.0-preview2.

repro:

here (0.10.0-preview2) cpu ok

```sh
git clone https://github.com/devel0/repros.git
cd repros
git checkout avalonia/cpu_ok
cd avalonia/test-empty-cpu100
dotnet run
```

then switch to (0.10.0-preview3) and cpu goes 100%

```sh
git checkout avalonia/cpu_100
dotnet run
```

is there a way to track calls ( enable some debugging ) I see only managed code from dotnet-trace ?

thanks for any direction.

**Comment by FoggyFinder** [comment]
what about nightly build?

**Comment by devel0** [comment]
Thanks,
I confirm that [using nightly build](https://github.com/devel0/repros/blob/avalonia/cpu_ok_nightly/avalonia/test-empty-cpu100/test-empty.csproj#L14-L17) it works without problem.
