### ISSUE TITLE
Avalonia TextBox visibility issue

### ISSUE THREAD

**Issue by mcmikecreations** [AvaloniaUI/Avalonia#4774]
### What is the error:
`[Binding] Binding produced invalid value for "IsVisible" ("System.Boolean"): null (null) (Avalonia.ValueStore #14964341)` twice for every `TextBox`.

### How to reproduce with minimum code:

1. Create a default avalonia application (not mvvm, although it doesn't work there as well).
2. Edit `MainWindow.axaml` code to this:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApp.MainWindow"
        Title="AvaloniaApp">
	<Grid>
		<StackPanel Orientation="Vertical"
					HorizontalAlignment="Stretch"
					Name="propertyContainer"/>
	</Grid>
</Window>
```

3. Edit `MainWindow.axaml.cs` code to this:

```
...
    public class MainWindow : Window
    {
        public StackPanel S => this.FindControl<StackPanel>("propertyContainer");
        public MainWindow()
        {
            InitializeComponent();
#if DEBUG
            this.AttachDevTools();
#endif

            S.Children.AddRange(Enumerable.Range(0, 5).Select(x => new TextBox()));
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
...
```

4. After launching the application I get the error mentioned above twice for every TextBox. It is very annoying and I want my code to be error free.

**Comment by mcmikecreations** [comment]
Forgot to add, it was compiled in debug mode with the latest library version from NuGet.

**Comment by maxkatz6** [comment]
Hi!
Can you check this issue with Avalonia 0.10.0-preview5?
I see these warnings in the Output window only on 0.9.11 version.

**Comment by mcmikecreations** [comment]
I can confirm that the error went away on the 0.10.0-preview5 version. But the code does not compile due to missing `this.AttachDevTools();` method (at least it cannot be found).
