### ISSUE TITLE
can't I add a resource to the Application?

### ISSUE THREAD

**Issue by aboimpinto** [AvaloniaUI/Avalonia#4775]
Hello, 

I'm trying to add my own ViewModelLocator that I have for years and for that I need to add in App.xaml the code: 

    <Application.Resources>
        <local:Locator x:key="locator" />
    </Application.Resources>

and I'm getting the error: 
`/home/esqueleto/myWork/myAvaloniaApp/App.xaml(12,10,12,10): Avalonia error XAMLIL: Unable to find suitable setter or adder for property Resources of type Avalonia.Controls:Avalonia.Application for argument myAvaloniaApp:myAvaloniaApp.Locator, available setter parameter lists are: [/home/esqueleto/myWork/myAvaloniaApp/myAvaloniaApp.csproj]
/home/esqueleto/myWork/myAvaloniaApp/App.xaml(12,10,12,10): Avalonia error XAMLIL: Avalonia.Controls.IResourceDictionary [/home/esqueleto/myWork/myAvaloniaApp/myAvaloniaApp.csproj]
/home/esqueleto/myWork/myAvaloniaApp/App.xaml(12,10,12,10): Avalonia error XAMLIL: System.Collections.Generic.KeyValuePair`2<System.Object,System.Object> [/home/esqueleto/myWork/myAvaloniaApp/myAvaloniaApp.csproj]
/home/esqueleto/myWork/myAvaloniaApp/App.xaml(12,10,12,10): Avalonia error XAMLIL: System.Collections.Generic.KeyValuePair`2<TKey,TValue> (line 12 position 10) Line 12, position 10. [/home/esqueleto/myWork/myAvaloniaApp/myAvaloniaApp.csproj]`

you can see the code and the compilation error here: 
https://github.com/aboimpinto/myAvaloniaApp/pull/1/checks?check_run_id=1185181198

Is there anything that I'm doing wrong?

**Comment by maxkatz6** [comment]
```x:key``` - should be ```x:Key```.

**Comment by maxkatz6** [comment]
@derekantrican had same issue with missing "x:Key" - https://github.com/AvaloniaUI/Avalonia/issues/1020#issuecomment-701097462
I think this error message should also include possible solution of the problem, specifically in the "Resources" case.

**Comment by Gillibald** [comment]
I think there is an issue open to tracking these error messages that need improvement

**Comment by maxkatz6** [comment]
Yes, it is
https://github.com/AvaloniaUI/Avalonia/issues/4466

**Comment by aboimpinto** [comment]
thanks to all ... 
was the "key" that need to capitalized.

I'm using VSCode in my Ubuntu and even with some XAML code completion, this error was not solved caught.
Looks like the code completions on VSCode don't work very well ...

**Comment by aboimpinto** [comment]
this issue can be closed!
