### ISSUE TITLE
TreeView SelectSingleItem causing StackOverFlow

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#4780]
Hey,

The SelectSingleItem in TreeView clearing SelectedItems causing SelectedItemCollectionChanged which cause an update to the SelectedItem and becasue SelectedItems is empty the value that updates is null. https://github.com/AvaloniaUI/Avalonia/blob/2a89ba9b24732a17dc0418e09842fa377580ffa8/src/Avalonia.Controls/TreeView.cs#L220

To repro - 
**Control**
`  
<TreeView Items="{Binding Items}" SelectedItem="{Binding SelectedItem}"/>
`

**ViewModel property**
`
public MyItem SelectedItem
{
    get => _selectedItem;
    set
    {
        if (Equals(value, _selectedItem) || value == null) return;
        _selectedItem = value;
        OnPropertyChanged(nameof(SelectedItem));
    }
}
`
Removing the check for null fixes the issue, but that shouldn't happen if there aren't any null items in the Items to begin with.

In this screenshot you can see that PointerPressed (on an item) caused SelectSingleItem which caused SelectedItems.Clear() which caused the SelectedItem to be update with null.

![image](https://user-images.githubusercontent.com/27368554/94728155-7affd200-0368-11eb-9f37-997b263f1e64.png)

**Comment by danwalmsley** [comment]
https://github.com/AvaloniaUI/Avalonia/tree/fixes/4781-treeview-setting-bound-selected-item-null

created a failing unit test here (issue number in branch is incorrect)
