### ISSUE TITLE
How to perform hit tests on TextBlock on 10.x

### ISSUE THREAD

**Issue by ronbrogan** [AvaloniaUI/Avalonia#4796]
Using Avalonia 9.x I was using functionality to determine what text was clicked on by the user in a text block:
```
private void HexBlock_PointerPressed(object sender, Avalonia.Input.PointerPressedEventArgs e)
{
    var clientRelative = e.GetPosition(this.HexBlock);

    var hit = this.HexBlock.FormattedText.HitTestPoint(clientRelative);

    var pos = hit.TextPosition;
    ...etc
}
```

However, in the 10.x previews, it looks like `FormattedText` was replaced with `TextLayout` - which doesn't support hit testing the laid out text.

Is there a replacement for this functionality?

Also: I was using the `FormattedText.Spans` capability to apply granular coloring to subsets of my text blocks. Is this kind of approach deprecated in favor of something else as well?

**Comment by Gillibald** [comment]
This is currently not directly supported. https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Primitives/AccessText.cs#L84

**Comment by ahopper** [comment]
I'm currently using TextPresenter as a work arround for this.

**Comment by ronbrogan** [comment]
Thanks for the tip @ahopper, that's exactly what I needed.
