### ISSUE TITLE
ItemsRepeater gets confused when changing source.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#4805]
The following repro defines a master-detail view where selecting an item in the `ListBox` on the left displays items on the right:

```
    <Grid ColumnDefinitions="Auto,*">
        <ListBox Items="{Binding Items}" SelectedItem="{Binding SelectedItem}"/>
        <ScrollViewer Grid.Column="1" >
            <ItemsRepeater Items="{Binding SelectedItem.RightItems}"/>
        </ScrollViewer>
    </Grid>
```

```
    public class MainWindowViewModel : ReactiveObject
    {
        private LeftItemViewModel _selectedItem;

        public MainWindowViewModel()
        {
            var random = new Random(0);

            for (var i = 0; i < 30; ++i)
            {
                var item = new LeftItemViewModel($"Left Item {i}");

                if (i != 10)
                {
                    item.RightItems.AddRange(Enumerable.Range(0, random.Next(100)).Select(x => $"Right item {x}"));
                }

                Items.Add(item);
            }
        }

        public AvaloniaList<LeftItemViewModel> Items { get; } = new AvaloniaList<LeftItemViewModel>();

        public LeftItemViewModel SelectedItem
        {
            get => _selectedItem;
            set => this.RaiseAndSetIfChanged(ref _selectedItem, value);
        }
    }

    public class LeftItemViewModel
    {
        public LeftItemViewModel(string name) => Name = name;

        public string Name { get; }
        public AvaloniaList<string> RightItems { get; } = new AvaloniaList<string>();
        public override string ToString() => Name;
    }
```

Note that item 10 has no items. When scrolling through the left items to the bottom and then back up then back down, after item 10 is reached the `ItemsRepeater` stops displaying any items until at some point it wakes up and starts displaying again:

![KtCKO6DiBR](https://user-images.githubusercontent.com/1775141/95088658-86b21680-0723-11eb-9a05-a74bbd30c9a1.gif)

Discovered by @dahlsrud

**Comment by grokys** [comment]
I've tried to repro this in the upstream WinUI `ItemsRepeater` and have been unable to.

**Comment by workgroupengineering** [comment]
I have a similar problem, from what I understand it depends on ScrollViewer, if you use a maximum number of elements that does not open the scroll bar the problem does not occur.

**Comment by grokys** [comment]
Yeah, I've managed to narrow the problem down to the scroll anchoring in `ScrollContentPresenter` which explains why we don't see the problem in WinUI.

**Comment by grokys** [comment]
@workgroupengineering I wonder if you'd have chance to try #4814 to see if it fixes the problem you're seeing?
