### ISSUE TITLE
Focus is lost after selecting an item on ComboBox

### ISSUE THREAD

**Issue by driver1998** [AvaloniaUI/Avalonia#4808]
.NET Core 3.1.8
Avalonia 0.10.0-preview5

XAML:
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="test_avalonia.MainWindow"
        Title="test_avalonia">
    <StackPanel>
        <Button Content="Button"/>
        <ComboBox>
            <ComboBoxItem Content="Item1"/>
            <ComboBoxItem Content="Item2"/>
            <ComboBoxItem Content="Item3"/>
            <ComboBoxItem Content="Item4"/>
            <ComboBoxItem Content="Item5"/>
        </ComboBox>
    </StackPanel>
</Window>
```

At start, the focus is on MainWindow, and I can cycle through controls with Tab key, as expected.
![image](https://user-images.githubusercontent.com/22699485/95113346-e71d7400-0774-11eb-9729-5bfbca565f75.png)

After selecting an item on ComboBox, with either mouse or keyboard, the focus is lost.
![image](https://user-images.githubusercontent.com/22699485/95113447-0d431400-0775-11eb-811e-8eac28de1752.png)

On 0.9.12, it works as expected, the focus is still in the window and I can tab through controls as normal.

**Comment by driver1998** [comment]
Seems to be related to popups.

XAML:
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="test_avalonia.MainWindow"
        Title="test_avalonia">
    
        <StackPanel>
            <StackPanel>
                <ToggleButton x:Name="toggle" Content="Open Popup"/>
                <Popup IsOpen="{Binding #toggle.IsChecked, Mode=TwoWay}" IsLightDismissEnabled="true">
                    <Button Content="Click me"/>
                </Popup>
            </StackPanel>
        </StackPanel>
</Window>
```

Click on "Open Popup", focus is on the button, and the popup show up.
Click on "Click Me", now focus is on "Click me" , **aka controls in the popup**
Dismiss the popup by clicking outside of the popup, and now focus is gone (null).

**Comment by amwx** [comment]
This is related to my recent PR which allows focus to be directed into popup (fixing an issue where Textbox wouldn't work inside a popup). PR created to fix this.
