### ISSUE TITLE
Question on how to show a modal dialog synchronously

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#4810]
In WPF, the `Window.ShowDialog();` method blocks the thread and continues when the dialog is closed (the same way `MessageBox.Show();` works in WinForms). In Avalonia, the [docs](https://avaloniaui.net/docs/controls/window) indicate that `Window.ShowDialog()` executes asynchronously, meaning the thread can continue before the dialog is closed.

Maybe this is a matter of me not being good at async vs sync coding but how would I produce a similar result to WPF/WinForms but using the way Avalonia has been architected? I want to call `ShowDialog` from a non-async method and have execution pause until the dialog is closed.

I've tried the following:

`Task.WhenAll(dialog.ShowDialog(parent));`, `dialog.ShowDialog(parent).Result;`, and `dialog.ShowDialog(parent).Wait();` block the dialog thread and prevents the dialog from loading.

```
Task.Run(() => ShowDialog()).GetAwaiter().GetResult();
private async Task ShowDialog()
{
    Dialog dialog = new Dialog();
    await dialog.ShowDialog(parent);
}
```
throws an exception of System.InvalidOperationException: 'Call from invalid thread'

What is the proper way to do this?

**Comment by sn4k3** [comment]
You have it right, just runit in main UI thread (Outside the task)

So, in your main UI code:

```C#
async void callMyDialog()
{
   Dialog dialog = new Dialog();
   await dialog.ShowDialog(this);
}
```

**Comment by derekantrican** [comment]
Yeah, I've got that much. But how do I wait for that async method to complete from a non-async method? eg:

```
void showDialog()
{
    callMyDialog(); //I want to block the showDialog method from executing at this point until the dialog is closed
}

async void callMyDialog()
{
   Dialog dialog = new Dialog();
   await dialog.ShowDialog(this);
}
```

I've tried using `showDialog().Wait()` or similar (as mentioned above) but then I just get a blank dialog:
![image](https://user-images.githubusercontent.com/1558019/95155230-8a0bc900-0748-11eb-8137-0f3763c94606.png)

**Comment by sn4k3** [comment]
All your calls must be awaitable and marked as async

```C#
void async showDialog()
{
    await callMyDialog(); //I want to block the showDialog method from executing at this point until the dialog is closed
}

async void callMyDialog()
{
   Dialog dialog = new Dialog();
   await dialog.ShowDialog(this);
}

await showDialog();
```

Example:
https://github.com/sn4k3/UVtools/blob/d9cd0022caf0b55d90c0e1ff5f458f7aecdb000b/UVtools.WPF/MainWindow.axaml.cs#L584

**Comment by derekantrican** [comment]
That's exactly the point of this question: how do I do this without my method being async? Is it impossible?

**Comment by sn4k3** [comment]
> That's exactly the point of this question: how do I do this without my method being async? Is it impossible?

but why you want your methods not to be async? 
if you call dialog.ShowDialog(this); without await the ui code executes below, but a await keyword require method be marked as async.

Anyway, you can just call dialog.ShowDialog(this);, and attach an close event if you want to process some data from it in case you dont want to await

**Comment by MarkusAmshove** [comment]
How do you trigger the synchronous `showDialog` method? I think the misunderstanding is how to execute your stuff asynchronous in the first place.

Does it e.g. happen from a click/Command?

**Comment by workgroupengineering** [comment]
```csharp
void showDialog()
{
   dialog.ShowDialog(this).GetAwaiter().GetResult();
}
```

**Comment by jp2masa** [comment]
A workaround (adapted from https://github.com/AvaloniaUI/Avalonia/issues/857#issuecomment-272927078) is this:

https://github.com/jp2masa/dotnet-properties/blob/4584f2f4245d999eb270ece5ec013f9f97c0f8bf/src/dotnet-properties/Services/DialogService.cs#L28-L32

It will block until the dialog closes.

**Comment by derekantrican** [comment]
@MarkusAmshove There's a long line of synchronous methods that call this - it's not just a matter of making the caller (or even the caller's caller) async

@workgroupengineering I had tried that before - that still results in the empty dialog box issue where it prevents the dialog UI from loading.

@jp2masa Ah, thanks to your help I got it! Here is what I ended up using:

    using (var source = new CancellationTokenSource())
    {
        new Dialog().ShowDialog(parent).ContinueWith(t => source.Cancel(), TaskScheduler.FromCurrentSynchronizationContext());
        Dispatcher.UIThread.MainLoop(source.Token);
    }

**Comment by sn4k3** [comment]
@derekantrican if that works fine your you and you use it for multiple windows, consider making extension to ease your code.
Something like: 

```C#
public static void ShowDialogSync(this Window window, Window parent = null)
        {
            if (parent is null) parent = window;
            using (var source = new CancellationTokenSource())
            {
                window.ShowDialog(parent).ContinueWith(t => source.Cancel(), TaskScheduler.FromCurrentSynchronizationContext());
                Dispatcher.UIThread.MainLoop(source.Token);
            }
        }

        public static T ShowDialogSync<T>(this Window window, Window parent = null)
        {
            if (parent is null) parent = window;
            using (var source = new CancellationTokenSource())
            {
                var task = window.ShowDialog<T>(parent);
                task.ContinueWith(t => source.Cancel(), TaskScheduler.FromCurrentSynchronizationContext());
                Dispatcher.UIThread.MainLoop(source.Token);
                return task.Result;
            }

            return default(T);
        }
```

**Comment by derekantrican** [comment]
After doing a bunch of iterating since yesterday (and stumbling into a number of issues) I've improved upon the solution here in a way that still provides the desired functionality (acting like `Window.ShowDialog()` in WinForms & WPF - pausing the current thread until the dialog is closed) but also works simultaneously from the UI thread and from a separate thread like a `BackgroundWorker.DoWork` & `BackgroundWorker.RunWorkerAsync` setup.

```csharp
private MyDialogResult ShowDialog(DialogViewModel dialogViewModel)
{
    MyDialogResult result = MyDialogResult.Cancel;
    using (CancellationTokenSource source = new CancellationTokenSource())
    {
        if (Dispatcher.UIThread.CheckAccess()) //Check if we are already on the UI thread
        {
            Dialog dialog = new Dialog(dialogViewModel);
            dialog.ShowDialog<MyDialogResult>(Parent).ContinueWith(t =>
            {
                result = t.Result;
                source.Cancel();
            });

            Dispatcher.UIThread.MainLoop(source.Token);
        }
        else
        {
            Dispatcher.UIThread.InvokeAsync(() =>
            {
                Dialog dialog = new Dialog(dialogViewModel);
                dialog.ShowDialog<MyDialogResult>(Parent).ContinueWith(t =>
                {
                    result = t.Result;
                    source.Cancel();
                });
            });

            while (!source.IsCancellationRequested) { } //Loop until dialog is closed
        }
    }

    return result;
}
```

Of course, this is based on a MVVM format and could also be "extension-ized" like @sn4k3 's suggestion but should give a good starting point if anyone else comes across this

**Comment by derekantrican** [comment]
For anyone coming here in the future, this is a bad idea if you plan to have your application run on MacOS: #5229 . Use async dialogs instead

**Comment by danipen** [comment]
The following solution provided by @grokys worked for us. 

https://github.com/grokys/ShowDialogSyncAvalonia/blob/master/ShowDialogSyncAvalonia/SyncDialogExtensions.cs

I tested it in macOS high Sierra, Windows 10, Ubuntu 19.04.

**Comment by thomaslevesque** [comment]
The `Dispatcher.UIThread.MainLoop` trick doesn't produce the desired result: the window is not modal, I can still interact with the parent window...

**Comment by thomaslevesque** [comment]
> The `Dispatcher.UIThread.MainLoop` trick doesn't produce the desired result: the window is not modal, I can still interact with the parent window...

Actually, it looks like the problem is with [MessageBox.Avalonia](https://github.com/AvaloniaCommunity/MessageBox.Avalonia). When using a simple `Window`, it works as expected.

**Comment by marcussacana** [comment]
The code provided grokys worked, but a strange bug happens here,
After the ShowDialog returns, the window still open while the event method returns...

My program look like this:

[1] Async Event => [2] calls a sync function => [3] sync function calls ShowDialog

after the ShowDialog returns, the window keep visible
while the Async Event don't return as well.

(Tested under Linux)

Why I call a sync function?
Is an class constructor, that maybe (just maybe) will detect missing information, and create an window to ask the user the required information.
And this method isn't only called by the main window, so then I can't just ensure before call if the all required data is avaiable.

**Comment by SCLDGit** [comment]
Running into this issue in a case where I need to spawn a PIN entry dialog from a callback delegate. I have no control over the library expecting the delegate, and the delegate cannot be async. A simple way of creating a modal dialog that stops the main thread until it returns would be nice to have.

**Comment by maxkatz6** [comment]
@SCLDGit on desktop (and only desktop) you can create this extension in 11.0:
```csharp
internal static T WaitOnDispatcherFrame<T>(this Task<T> task)
{
    if (!task.IsCompleted)
    {
        var frame = new DispatcherFrame();
        task.ContinueWith(static (_, s) => ((DispatcherFrame)s).Continue = false, frame);
        Dispatcher.PushFrame(frame);
    }
    
    return task.GetAwaiter().GetResult();
}
```
But again, if it's possible, it should be avoided even at high cost.

**Comment by timunie** [comment]
My 2 cents here: 
- Display an overlay with a waiting message or similar
- Open the dialog. If the dialog closes, inform the UI about the status
- If positive, hide the overlay

Check out [AwsomeAvalonia](https://github.com/AvaloniaCommunity/awesome-avalonia#controls) for inspiration (for example Aura.UI). Good luck.

**Comment by OmarAbdullwahhab** [comment]
I know it is too late but here is what is the solution using Version 11.x (do not know if its the same for previous versions )
When showing a Window use 
`var result = await xxWindow.ShowDialog<TResponse>(xxOwnerWindow);`
Where `TResponse `is the response type you want return from `xxWindow `
And when closing the `xxWindow ` pass the result you want to the `Close `method as follows
`this.Close(rr);`
Where `rr` is a type of `TResponse`

**Comment by danipen** [comment]
> on desktop (and only desktop) you can create this extension in 11.0:
> 
> ```csharp
> internal static T WaitOnDispatcherFrame<T>(this Task<T> task)
> {
>     if (!task.IsCompleted)
>     {
>         var frame = new DispatcherFrame();
>         task.ContinueWith(static (_, s) => ((DispatcherFrame)s).Continue = false, frame);
>         Dispatcher.PushFrame(frame);
>     }
>     
>     return task.GetAwaiter().GetResult();
> }
> ```

@maxkatz6 using this approach seems to work, however, we're experiencing issues with TextBoxes, at least in macOS. 

When we display a dialog using this mechanism, and the dialog has a `TextBox` it happens that when you hit a key, the character is not visible in the TextBox until you press another key again, or you move the mouse to hover the `TextBox`. It's like hitting the key is not forcing a repaint of the control, and hitting it again, then it's repainted. 

https://github.com/AvaloniaUI/Avalonia/assets/501613/f5ae7dbc-6138-4299-9319-10cdc646f4a6

Is there any workaround for this? Thanks!

**Comment by danipen** [comment]
@kekekeks @maxkatz6 yes, #15425 fixes the issue. Could you please backport it to 11.0.x to be included in the next release?
