### ISSUE TITLE
Scroll ListBox inside neasted grids: System.InvalidOperationException: 'The control already has a visual parent.'

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#4817]
I'm getting this error when scroll a ListBox or resize the window containing the listbox on neasted grids:

>    at Avalonia.Visual.ValidateVisualChild(IVisual c)
>    at Avalonia.Visual.<>c.<.ctor>b__16_0(IVisual visual)
>    at Avalonia.Collections.AvaloniaList`1.Add(T item)
>    at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild()
>    at Avalonia.Controls.Presenters.ContentPresenter.ContentChanged(AvaloniaPropertyChangedEventArgs e)
>    at Avalonia.Controls.Presenters.ContentPresenter.<>c.<.cctor>b__15_0(ContentPresenter x, AvaloniaPropertyChangedEventArgs e)
>    at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass23_0`1.<AddClassHandler>b__0(AvaloniaPropertyChangedEventArgs e)
>    at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 148
>    at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
>    at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
>    at Avalonia.PropertyStore.BindingEntry`1.UpdateValue(BindingValue`1 value)
>    at Avalonia.PropertyStore.BindingEntry`1.OnNext(BindingValue`1 value)
>    at Avalonia.Reactive.SingleSubscriberObservableBase`1.PublishNext(T value)
>    at Avalonia.Reactive.BindingValueAdapter`1.OnNext(T value)
>    at Avalonia.Reactive.SingleSubscriberObservableBase`1.PublishNext(T value)
>    at Avalonia.Data.TemplateBinding.PublishValue()
>    at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
>    at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
>    at Avalonia.PropertyStore.PriorityValue`1.UpdateEffectiveValue(AvaloniaPropertyChangedEventArgs`1 change)
>    at Avalonia.PropertyStore.PriorityValue`1.SetValue(T value, BindingPriority priority)
>    at Avalonia.ValueStore.SetExisting[T](Object slot, StyledPropertyBase`1 property, T value, BindingPriority priority)
>    at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority)
>    at Avalonia.StyledPropertyBase`1.RouteSetValue(IAvaloniaObject o, Object value, BindingPriority priority)
>    at Avalonia.AvaloniaObjectExtensions.SetValue(IAvaloniaObject target, AvaloniaProperty property, Object value, BindingPriority priority)
>    at Avalonia.Controls.Generators.ItemContainerGenerator`1.TryRecycle(Int32 oldIndex, Int32 newIndex, Object item)
>    at Avalonia.Controls.Presenters.ItemVirtualizerSimple.RecycleContainersForMove(Int32 delta)
>    at Avalonia.Controls.Presenters.ItemVirtualizerSimple.set_OffsetValue(Double value)
>    at Avalonia.Controls.Presenters.ItemVirtualizer.set_Offset(Vector value)
>    at Avalonia.Controls.Presenters.ItemsPresenter.Avalonia.Controls.Primitives.IScrollable.set_Offset(Vector value)
>    at Avalonia.Controls.Presenters.ScrollContentPresenter.<>c__DisplayClass50_0.<UpdateScrollableSubscription>b__2(Vector x)
>    at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 44
>    at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 50
>    at System.Reactive.Linq.ObservableImpl.Skip`1.Count._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Skip.cs:line 59
>    at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
>    at Avalonia.Reactive.AvaloniaPropertyObservable`1.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e)
>    at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
>    at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority)
>    at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value)
>    at Avalonia.Controls.Presenters.ScrollContentPresenter.set_Offset(Vector value)
>    at Avalonia.Controls.Presenters.ScrollContentPresenter.OnPointerWheelChanged(PointerWheelEventArgs e)
>    at Avalonia.Input.InputElement.<>c.<.cctor>b__26_11(InputElement x, PointerWheelEventArgs e)
>    at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
>    at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 36
>    at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 150
>    at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
>    at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
>    at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
>    at Avalonia.Input.MouseDevice.MouseWheel(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, Vector delta, KeyModifiers inputModifiers)
>    at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
>    at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
>    at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
>    at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
>    at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
>    at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
>    at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
>    at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
>    at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 17

![image](https://user-images.githubusercontent.com/113281/95280223-6762d880-084c-11eb-88d3-ca5a072797e9.png)
AXAML: https://github.com/sn4k3/UVtools/blob/master/UVtools.WPF/Windows/PrusaSlicerManager.axaml

![image](https://user-images.githubusercontent.com/113281/95280139-3d111b00-084c-11eb-90cd-d267df7b7ae0.png)

**Comment by maxkatz6** [comment]
Your ListBox.Items is bind to a list of ComboBox controls. I think this exception occurs when Avalonia tries to change ComboBox parent for virtualization. Try to set <ListBox VirtualizationMode="None" ... > as a workaround.

It seems to be a bug in ListBox VirtualizationMode=Simple, that is enabled by default. I believe, migration to ItemsRepeater in the ListBox internals should fix this problem. https://github.com/AvaloniaUI/Avalonia/pull/4779

By the way, it's more common way to use ItemTemplate with the ListBox - https://avaloniaui.net/docs/controls/listbox.
You can define ComboBox in that template, and configure TwoWay binding to your model.

**Comment by sn4k3** [comment]
`VirtualizationMode="None"` worked.

> By the way, it's more common way to use ItemTemplate with the ListBox - https://avaloniaui.net/docs/controls/listbox.
> You can define ComboBox in that template, and configure TwoWay binding to your model.

Thank you for the tip, i will take a look

I will keep the issue open as it seens a real issue, fell free to close if not

**Comment by maxkatz6** [comment]
It is a real issue, but there is another one with same bug - https://github.com/AvaloniaUI/Avalonia/issues/4265
Closing this one.
