### ISSUE TITLE
In-App Notifications doesn't work after theme changed

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#4819]
Steps to reproduces:
1. Start ControlCatalog (with FluentLight theme by default).
2. Show example notification.
3. Change theme to FluentDark.
4. Try to show notification again.

**Comment by maxkatz6** [comment]
Also it seems that notifications aren't connected to the logical tree. Or at least DevTools can't find them.

**Comment by jp2masa** [comment]
#4462

**Comment by maxkatz6** [comment]
@jp2masa thanks.
