### ISSUE TITLE
Shape does not update when parent size changes

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#4822]
`Shape` does not correctly update its size when parent resizes and its set to `HorizontalAlignment=Stretch`. I need to manually call `InvalidateMeasure` on it.
Attached a sandbox repro. I think the fix is to remove this `_calculateTransformOnArrange` stuff and always call
`CalculateShapeSizeAndSetTransform` inside `ArrangeOverride`

[path_repro_measure_bug.patch.txt](https://github.com/AvaloniaUI/Avalonia/files/5340981/path_repro_measure_bug.patch.txt)
![bug_av_shape_measure](https://user-images.githubusercontent.com/4670166/95337422-1a195200-08b2-11eb-81a3-b28f93e9e730.gif)

**Comment by Gillibald** [comment]
Panel sems not to have a measure override that updates its children. So this might not be related to Path. TextBox invalidates iteself when the text changes so that why you see updates..

**Comment by grokys** [comment]
> Panel seems not to have a measure override that updates its children

It calls `Layoutable.MeasureOverride` which iterates the visual children and measures them with the `availableSize` so I don't think this is the reason:

https://github.com/AvaloniaUI/Avalonia/blob/ab63c3d2bb2779fb60448cca17ae75b80d6cef82/src/Avalonia.Layout/Layoutable.cs#L619-L629
