### ISSUE TITLE
TextBlock Multiline using \r\n show unknown rectangle characters with Direct2d backend

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#4824]
repro:
`<TextBlock Text="Multiline text&#x0d;&#x0a;next line&#x0d;&#x0a;next line" />`
result:
![image](https://user-images.githubusercontent.com/13854631/95433980-59e74480-0959-11eb-98d3-a29a29ac0d2f.png)

multiline textblock was working fine with 0.9 and it's working fine with skia currently

**Comment by Gillibald** [comment]
Will have a look
