### ISSUE TITLE
Ubuntu 20.04 with display scale not scaling correctly

### ISSUE THREAD

**Issue by dejfcz** [AvaloniaUI/Avalonia#4826]
I've got big resolution on Ubuntu 20.04. It looks like this if the scale is 100%:
![image](https://user-images.githubusercontent.com/19493351/95458699-6de77200-096a-11eb-8892-eb46cb61ecf4.png)

Yet this is not how it is usable for me because everything is very very small on the display.
So I need to have it set at scale 200% and then it looks like this:

![image](https://user-images.githubusercontent.com/19493351/95458762-86f02300-096a-11eb-856c-60d99d649d8b.png)

The thing to notice here is that the "Status Dialog Title" window is still as small as it was on 100% scale, so it is not usable unless your vision is super good and you can master your mouse cursor ... Not ideal UX. Notice how all other windows scaled up well, as they should.

**Comment by kekekeks** [comment]
Since Linux doesn't have any standard API for querying the current desktop environment for the scaling settings, we are using a heuristic based on your resolution and physical size of the display reported by RANDR. You can override those by setting [the corresponding environment variable](https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI).

**Comment by dejfcz** [comment]
Works, thanks.

**Comment by xdrie** [comment]
> Since Linux doesn't have any standard API for querying the current desktop environment for the scaling settings, we are using a heuristic based on your resolution and physical size of the display reported by RANDR. You can override those by setting [the corresponding environment variable](https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI).

Could you point me to the code for calculating that heuristic?

**Comment by xdrie** [comment]
@kekekeks Before falling back to [GuessPixelDensity](https://github.com/AvaloniaUI/Avalonia/blob/554aaec5e5cc96c0b4318b6ed1fbf8159f442889/src/Avalonia.X11/X11Screens.cs#L260), could we instead try querying `Xft.dpi` (via xsettings), like GTK apps do (see debianwiki [MonitorDPI](https://wiki.debian.org/MonitorDPI)

**Comment by kekekeks** [comment]
Xft.dpi isn't multi-monitor aware

**Comment by xdrie** [comment]
Okay, that makes sense. Thank you for clarifying. However perhaps it could be made to set the global scale? This would mirror behavior of GTK applications. But I'm not sure if that's desirable.

**Comment by kekekeks** [comment]
We are currently mirroring the Qt behavior.

**Comment by maxkatz6** [comment]
Could be related [QTBUG-84082](https://bugreports.qt.io/browse/QTBUG-84082)
