### ISSUE TITLE
TextBlock doesn't render properly after text is changed

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#4831]
valid for current master
repro steps:
add  xaml code in a view
```xaml
      <Border>
        <StackPanel Width="300" Spacing="8">
          <TextBlock x:Name="txtChanging" />
          <TextPresenter x:Name="tpChanging" />
        </StackPanel>
      </Border>
```
code behind:
```C#
            var txtChanging = this.Get<TextBlock>("txtChanging");
            var tpChanging = this.Get<TextPresenter>("tpChanging");
            DispatcherTimer.Run(() =>
            {
                var time = DateTime.Now.TimeOfDay.ToString();
                txtChanging.Text = $"TextBlock: {time}";
                tpChanging.Text = $"TextPresenter: {time}";
                return true;
            }, TimeSpan.FromSeconds(1));
```
result:
![2020-10-09_16-02-27](https://user-images.githubusercontent.com/13854631/95586332-369bc280-0a49-11eb-91ca-330951d7e95a.gif)
expected result: TextBlock render the same way as TextPresenter

notes: 

- TextBlock is not hit test friendly most of the time it's like it render nothing after the first change

- Issue is present only with Deferred renderer, with immediate renderer there is no problem

- Hittest is working only for the bottom ~10% of the text

**Comment by Gillibald** [comment]
I know what is happening and have a fix in mind
