### ISSUE TITLE
When to set focus in UserControl to make it work?

### ISSUE THREAD

**Issue by MartyIX** [AvaloniaUI/Avalonia#4835]
Hi,

I have this code for my "Connect form" and I would like to set focus to a text box after the form is displayed. My code looks like this:

```csharp
using Avalonia;
using Avalonia.Controls;
using Avalonia.LogicalTree;
using Avalonia.Markup.Xaml;
using NLog;

namespace Project.AvaloniaGui.Views
{
    /// <summary>
    /// Control representing the connect form.
    /// </summary>
    public class ConnectFormView: UserControl
    {
        public ConnectFormView()
        {
            this.InitializeComponent();
        }

        protected override void OnInitialized()
        {
            base.OnInitialized();

            TextBox? host = this.FindControl<TextBox>("HostTb");
            host!.Focus();
        }

        /// <summary>
        /// Loads the object to the corresponding Avalonia component.
        /// </summary>
        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
```

Unfortunately, even though `TextBox? host = this.FindControl<TextBox>("HostTb");` is not null, there is no effect of `host!.Focus();` line. 

Does anybody know what is wrong? I couldn't find any examples how to work with "focus".

Thanks!

**Comment by maxkatz6** [comment]
You probably need to wait until TextBox will be added to the visual tree.
You can try to use AttachedToVisualTree event and focus inside of it.

**Comment by Gillibald** [comment]
I usually use a behavior for a delayed focus.

**Comment by maxkatz6** [comment]
We can have some kind of TryFocusAsync extension method like it is in UWP
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.focusmanager.tryfocusasync?view=winrt-19041

**Comment by MartyIX** [comment]
> You can try to use AttachedToVisualTree event and focus inside of it.

I have tried that to no avail.

> I usually use a behavior for a delayed focus.

Do you have a sample please?

**Comment by FoggyFinder** [comment]
> I have tried that to no avail.

```cs
public ConnectFormView()
{
     this.InitializeComponent();
     var hostTb = this.FindControl<TextBox>("HostTb");
     if (hostTb != null)
     {
         hostTb.AttachedToVisualTree += (s,e) => hostTb.Focus();
     }
}
```

**Comment by MartyIX** [comment]
Yes, this solves the issue. 

What if one wants to set focus and have access only to ViewModel?

**Comment by maxkatz6** [comment]
You can use events in xaml with BehaviorSDK

**Comment by MartyIX** [comment]
> You can use events in xaml with BehaviorSDK

How can I do that?

**Comment by maxkatz6** [comment]
@MartyIX 
Something like this should work
```
<UserControl ...
        xmlns:i="clr-namespace:Avalonia.Xaml.Interactivity;assembly=Avalonia.Xaml.Interactivity"
        xmlns:ia="clr-namespace:Avalonia.Xaml.Interactions.Core;assembly=Avalonia.Xaml.Interactions">
  <i:Interaction.Behaviors>
    <ia:EventTriggerBehavior EventName="AttachedToVisualTree" SourceObject="{Binding $self}">
      <ia:CallMethodAction TargetObject="{Binding $self}" MethodName="Focus"/>
    </ia:EventTriggerBehavior>
  </i:Interaction.Behaviors>
...
</UserControl>

**Comment by FoggyFinder** [comment]
I thought the goal was opposite: set focus on an element on demand from VM side

**Comment by maxkatz6** [comment]
@FoggyFinder well, there also could be some property IsViewFocused in the ViewModel and DataTriggerBehavior to bind it with the same CallMethodAction.
