### ISSUE TITLE
TextBlock with Text Binding is obfuscating text on change 0.10.999-cibuild0011267-beta

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#4836]
This doesn't happen on previous nightly builds, start to happen with this version.
When updating text via binding it comes obfuscated. This now happens on all my windows when i update a text, however the very first render always show ok 

```C#
<TextBlock
        Grid.Column="2"
        Text="{Binding SingleThreadTDPS}" />

// On click Start:
SingleThreadTDPS = $"Running {SingleThreadTests} tests";
```
Actual code: https://github.com/sn4k3/UVtools/blob/master/UVtools.WPF/Windows/BenchmarkWindow.axaml.cs#L137

Before change text:
![image](https://user-images.githubusercontent.com/113281/95645009-d6416b00-0ab2-11eb-802d-99d89e09769e.png)

After change text (Click start button)
![image](https://user-images.githubusercontent.com/113281/95645020-e6f1e100-0ab2-11eb-97c4-af04805155e4.png)

**Comment by maxkatz6** [comment]
Duplicate 
https://github.com/AvaloniaUI/Avalonia/issues/4831
