### ISSUE TITLE
ComboBox won't open when parent control handles PointerPressed

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#4837]
ComboBox won't open when parent control handles PointerPressed
```
<Border PointerPressed="MouseOnBorder">
        <ComboBox Items="{Binding Items}" Width="200"/>
</Border>
```
```
private void MouseOnBorder(object sender, PointerPressedEventArgs e)
{
      BeginMoveDrag(e);
}
```
Is this intended? it worked fine before https://github.com/AvaloniaUI/Avalonia/pull/4744

**Comment by rstm-sf** [comment]
Perhaps this should also be noted as breaking changes

**Comment by adirh3** [comment]
> Perhaps this should also be noted as breaking changes

This change definitely triggered it, but the main problem is that the `Border` registers the click and not the `ComboBox`.

**Comment by adirh3** [comment]
> Perhaps this should also be noted as breaking changes

This change definitely triggered it, but the main problem is that the `Border` registers the click and not the `ComboBox`.
