### ISSUE TITLE
richtextbox

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#4841]
Is there a RichTextBox like control that can input text, links, set colors, input pictures and other rich functions?

**Comment by derekantrican** [comment]
From what I understand, the answer is "officially, no. But you should look into https://github.com/AvaloniaUI/AvaloniaEdit"

**Comment by maxkatz6** [comment]
Duplicate

https://github.com/AvaloniaUI/Avalonia/issues/3303#issuecomment-562096290
https://github.com/AvaloniaUI/Avalonia/issues/2842
https://github.com/AvaloniaUI/Avalonia/issues/752

**Comment by jinyuttt** [comment]
pictures ？
