### ISSUE TITLE
Black Screen with StartLinuxDrm

### ISSUE THREAD

**Issue by jangernert** [AvaloniaUI/Avalonia#4842]
Hi,

Our company is thinking about porting our kiosk style application from WPF to Avalonia in the not so distant future. Because of this I decided to get my feet wet and write a small tool we needed internally with .NET Core and Avalonia. Great experience so far :+1:
One of the main selling points of Avalonia for us is the ability to run it directly on top of a framebuffer.

But I got stuck running the tool on the drm output. Fbdev is now working after some back and forth (not quite sure how I got it working in the end). But `--drm` only leads to a black screen. So Avalonia seems to be doing something and is trying to draw to the screen.
I don't get any exceptions or other errors when terminating the process like I did earlier while still figuring things out. And kmscube is working fine as well for me.

I'm on a fedora 32 x64 install and am using the avalonia 0.10 preview 5. My system has a AMD RX 580 with the amdgpu driver.
I mirrored the repository onto github hoping this will make it easier to get help: https://github.com/jangernert/BarcodeGenerator

Is there any way I can debug the problem further? Or any obvious thing I'm doing wrong?

edit:
`ControlCatalogStandalone` does work running with `--drm` (but segfaults in desktop mode). Since this sample uses Avalonia 0.9.0 I tried switching back to 0.9.11 without any luck.

Thanks

**Comment by kekekeks** [comment]
> ControlCatalogStandalone does work running with --drm (but segfaults in desktop mode)

Could you elaborate?

Note: `--drm` mode attempts to take implicit ownership over the DRM master, you need to run it from a TTY console for that to succeed.

**Comment by jangernert** [comment]
Regarding ContentControlStandalone:
- I'm in the `ControlCatalog.NetCore` subfolder
- `dotnet run` does nothing and just returns after a few seconds
- `dotnet bin/Debug/netcoreapp3.0/ControlCatalog.NetCore.dll`  segfaults
- switching to TTY3 and running `dotnet bin/Debug/netcoreapp3.0/ControlCatalog.NetCore.dll --drm` works though

**Comment by kekekeks** [comment]
`dotnet run --drm` should work as well. You need to pass `--drm` argument, otherwise Avalonia will attempt to connect to the X server.

**Comment by jangernert** [comment]
Sorry if that wasn't clear: I tried to run the application without `--drm` on my gnome desktop. Not in a separate terminal.

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/4843

**Comment by jangernert** [comment]
I'm trying to verify the fix on my system. The [CI build](https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=11285&view=results) seems to be done. The version string should be `0.10.999-cibuild0011285-beta`, right?
But `dotnet restore` complains it can't find that version: `Nearest version: 0.10.999-cibuild0011267-beta` which is the last master build before that.
Do I need to refresh my sources or wait some more until the build is uploaded to the nuget repository? Sorry if I am missing something here.

**Comment by jangernert** [comment]
Using the "All builds feed" I was able to test the commit. I can confirm a: "Works for me^tm"

Thank you for the quick fix!
