### ISSUE TITLE
Some questions about adding validation to a TextBox

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#4845]
From the bit of research I've done on TextBox validation in Avalonia I've gotten this far:

View.axaml:
```xml
<TextBox Text="{Binding Email}" Margin="5"/>
```

ViewModel.cs:
```csharp
private string email;
public string Email
{
    get
    {
        return email;
    }
    set
    {
        if (string.IsNullOrWhiteSpace(value) || !Regex.IsMatch(value, @"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$"))
        {
            throw new DataValidationException("Invalid email");
        }

        email = value;
        FirePropertyChanged();
    }
}
```

![image](https://user-images.githubusercontent.com/1558019/95693223-181bff80-0be0-11eb-9e04-7a16bd64e120.png)

This works, but I've got a couple questions:

- First, my TextBox does not show a validation error when the window first opens (not until the value of the textbox is changed back). What is the right way to force a validity check when the window first opens?
- Secondly, I would like to be able to test my validation while debugging but it's a bit annoying that the VS debugger shows the thrown exception, forcing me to press "Continue" between every character that I type. Is there a way that I can run the program in debug and yet ignore DataValidationExceptions?
- Finally, is there a way that my viewmodel can check for any current validation issues in the form when the "Ok" button is pressed? (eg in my case above refusing to let the user submit the form if the Email textbox is still showing a validation error)

**Comment by derekantrican** [comment]
Oh, I think I've figured out the second question: I can set VS to ignore DataValidationExceptions. Either changing the settings when seeing that exception thrown, or by pressing `Ctrl + Alt + E`, searching for `Avalonia.Data.DataValidationException` and turning it off

**Comment by maxkatz6** [comment]
@derekantrican not only DataValidationException from property setter is supported by Avalonia.
You can also use DataAnnotations ([example](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/BindingDemo/ViewModels/DataAnnotationsErrorViewModel.cs)), INotifyDataErrorInfo ([example](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/BindingDemo/ViewModels/IndeiErrorViewModel.cs)) and I believe that ReactiveUI Validation should work as well (not Avalonia example, but should be same - [link](https://www.reactiveui.net/docs/handbook/user-input-validation/))

> First, my TextBox does not show a validation error when the window first opens (not until the value of the textbox is changed back). What is the right way to force a validity check when the window first opens?

It should be because of setter wasn't called at startup, and you see default value (empty string) but without any error.

> Finally, is there a way that my viewmodel can check for any current validation issues in the form when the "Ok" button is pressed? (eg in my case above refusing to let the user submit the form if the Email textbox is still showing a validation error)

With INotifyDataErrorInfo approach you have ErrorsChanged event that could be called from button's handler (Command) and HasErrors property that you can implement and check before submitting the form. Although with ReactiveUI it should be way easier.

**Comment by derekantrican** [comment]
Thanks for all the information! I'll have to check out some of those examples you provided.

>It should be because of setter wasn't called at startup, and you see default value (empty string) but without any error.

Yeah, I gathered that much - do you have any suggestions for how to trigger them on startup? Not sure if I could assign values to them on a "Loaded" event but that probably wouldn't be a "proper" way anyway

**Comment by worldbeater** [comment]
We've released a new version of [ReactiveUI.Validation](https://github.com/reactiveui/reactiveui.validation) recently, with plenty of updates and enhancements. Even complex asynchronous validations are supported now (see our [README.md](https://github.com/reactiveui/reactiveui.validation) file for more info). Also, we've added [a sample app targeting Avalonia](https://github.com/reactiveui/ReactiveUI.Validation/tree/main/samples) that shows how to use ReactiveUI.Validation with AvaloniaUI. This should simplify the process of building validations. Remember to install `Avalonia.ReactiveUI` and add a call to `.UseReactiveUI()` if you decide to try out `ReactiveUI.Validation`!

**Comment by derekantrican** [comment]
I've solved my other two questions by implementing the `INotifyDataErrorInfo` that @maxkatz6 mentioned. Thanks for the input!

**Comment by dashenxian** [comment]
@derekantrican Can you share your implementation logic? I want to implement a generic validation, similar to form validation, that disables form submission when there are controls in the form that are not validated to pass.

**Comment by worldbeater** [comment]
@dashenxian you can achieve the described behavior by incorporating `WhenAnyValue` and a `ReactiveCommand` I guess. E.g.

```csharp
// Each time values of UserName and Password properties change,
// the canExecute observable is signalled and the logic that 
// determines if command execution should be allowed is executed.
var canExecute = this.WhenAnyValue(
    x => x.UserName,
    x => x.Password,
    (userName, password) => 
        !string.IsNullOrEmpty(userName) && 
        !string.IsNullOrEmpty(password));

// The command will be unavailable during execution of the LogOnAsync
// method, or while UserName and Password ViewModel properties are 
// nulls or empty strings. In other words, canExecute supplements 
// the default executability behavior, it doesn't replace it.
var login = ReactiveCommand.CreateFromTask(LogOnAsync, canExecute); // ICommand
```

Borrowed from https://www.reactiveui.net/docs/handbook/commands/#controlling-executability
With [ReactiveUI.Validation](https://github.com/reactiveui/reactiveui.validation#inotifydataerrorinfo-support) and their `INotifyDataErrorInfo` implementation this will look like:

```csharp
this.ValidationRule(
    x => x.Username,
    name  => !string.IsNullOrWhiteSpace(name),
    "User name shouldn't be null or white space.");

this.ValidationRule(
   x => x.Password,
   pass => !string.IsNullOrWhiteSpace(pass),
   "Password shouldn't be null or white space.");

var canExecute = this.IsValid();
var login = ReactiveCommand.CreateFromTask(LogOnAsync, canExecute); // ICommand
```

**Comment by dashenxian** [comment]
@worldbeater Thank you very much, that's exactly what I need. Also, isn't it just added thiss. ValidationRule (...), in order to do so, if it is the property label verification is not enough, such as:
```c#
[MaxLength]
public string Username { get; private set; }
```
