### ISSUE TITLE
FullScreen on startup prevents window from being shown

### ISSUE THREAD

**Issue by dougmill** [AvaloniaUI/Avalonia#4846]
I'm using 0.10.0-preview5 on Windows 10. Setting `WindowState=WindowState.FullScreen` after my program has started works fine. If I put `WindowState="FullScreen"` in the main window's xaml file, however, the window never shows.

I put this in the main window's constructor to test things:
```
DispatcherTimer.RunOnce(() => WindowState = WindowState.Maximized, TimeSpan.FromSeconds(1));
DispatcherTimer.RunOnce(() => WindowState = WindowState.FullScreen, TimeSpan.FromSeconds(2));
DispatcherTimer.RunOnce(Show, TimeSpan.FromSeconds(3));
```
If the xaml file omits `WindowState`, the window opens at normal size, then maximizes, then goes fullscreen.
If the xaml file sets `WindowState="Maximized"`, the window opens maximized, waits 2 seconds, then goes fullscreen.
If the xaml file sets `WindowState="FullScreen"`, the window never shows. Even the explicit call to `Show()` does nothing, and checking in a debugger confirmed it does get executed.

**Comment by olliholliday** [comment]
Putting this in the Window constructor or InitialiseComponent has the same result - the window is fully invisible without even a taskbar entry.

```
WindowState = WindowState.FullScreen;
```

**Comment by dougmill** [comment]
It appears there's some initialization that's run after component creation that isn't handling fullscreen. Putting this in the window constructor produces the error:
```
WindowState = WindowState.Maximized;
WindowState = WindowState.FullScreen;
```
Putting this in the window constructor (without setting fullscreen anywhere else) successfully works around it, however:
```
DispatcherTimer.RunOnce(() => WindowState = WindowState.FullScreen, TimeSpan.Zero);
```

**Comment by mgnslndh** [comment]
Not sure this is relevant but having WindowState=FullScreen in XAML works fine on Avalonia 11.0.4 Windows Desktop.

**Comment by timunie** [comment]
I guess this is a leftover issue which is already fixed. As no OS is specified, we can only test on Windows for now. So closing this for now. If someone can still reproduce using 11.0, ping me and we will reopen it. Let us know the OS used.
