### ISSUE TITLE
How does Avalonia Treeview change the node's triangle into a +- symbol

### ISSUE THREAD

**Issue by Aaronlog** [AvaloniaUI/Avalonia#4847]
I would really appreciate it if you could paste in a concrete block of code!

**Comment by maxkatz6** [comment]
Simplest way to do it with custom styles (only for Default theme):
```xaml
<Style Selector="TreeViewItem /template/ ToggleButton#expander:unchecked">
  <Setter Property="Template">
    <ControlTemplate>
      <Border Background="Transparent"
              HorizontalAlignment="Center"
              VerticalAlignment="Top">
        <TextBlock Text="+" />
      </Border>
    </ControlTemplate>
  </Setter>
</Style>

<Style Selector="TreeViewItem /template/ ToggleButton#expander:checked">
  <Setter Property="Template">
    <ControlTemplate>
      <Border Background="Transparent"
              HorizontalAlignment="Center"
              VerticalAlignment="Top">
        <TextBlock Text="-" />
      </Border>
    </ControlTemplate>
  </Setter>
</Style>

<!--  Disable rotation transform from the default theme.  -->
<Style Selector="TreeViewItem /template/ ToggleButton#expander:checked">
  <Setter Property="RenderTransform" Value="{x:Null}" />
</Style>
```

You may prefer replacing TextBlock with custom Path, specify sizes, colors and other.
![image](https://user-images.githubusercontent.com/3163374/95715511-ffd7cf00-0c37-11eb-8b91-590338347485.png)

**Comment by maxkatz6** [comment]
How to use styles in Avalonia - https://avaloniaui.net/docs/styles/styles

**Comment by Aaronlog** [comment]
@maxkatz6 Thanks very much, sir. Now I want to implement vertical and horizontal dashed lines between nodes, what do I do

**Comment by maxkatz6** [comment]
@Aaronlog there are BorderThickness and BorderBrush properties on TreeViewItem.
You can create Style with TreeViewItem selector and set values for these properties in two Setters.

**Comment by Aaronlog** [comment]
@maxkatz6  After setting BorderThickness and BorderBrush properties on the TreeViewItem selector, it still doesn't give me the effect I want，Could you do me one more favor，It would be great if you could paste in a block of code that does this
![treeview](https://user-images.githubusercontent.com/41666145/96071109-0a15f980-0ed4-11eb-8c7a-fd45ab1c2b30.png)

**Comment by mikhailSokolovskiy** [comment]
How to do this in 2024?)

**Comment by timunie** [comment]
@mikhailSokolovskiy best to lookup original styles and modify to your needs I guess you can also override these resources: https://github.com/AvaloniaUI/Avalonia/blob/ac91b14cafcc283748143d56e3c6c428fae36876/src/Avalonia.Themes.Fluent/Controls/TreeViewItem.xaml#L26-L27

**Comment by mikhailSokolovskiy** [comment]
And how lookup orig style. I changed the size of the triangle in this way. but how change this figure in style?
```
<Window.Styles>
        <Style Selector="TreeViewItem /template/ ToggleButton#PART_ExpandCollapseChevron">
            <Setter Property="Width" Value="20"></Setter>
            <Setter Property="Height" Value="20"></Setter>
        </Style>
    </Window.Styles>
```

**Comment by winkmichael** [comment]
Any way to set the amount of indendation with TreeView? Style doesn't seem to expose this option.

**Comment by timunie** [comment]
@winkmichael you just need to override this in App.Resources afaik: https://github.com/AvaloniaUI/Avalonia/blob/5e7963b5453b423d092c87a8b30c913f2c6bdcaa/src/Avalonia.Themes.Fluent/Controls/TreeViewItem.xaml#L23

**Comment by winkmichael** [comment]
Thanks for your comment @timunie , I've tried varations of your suggestion without any luck;

In app.axaml, I have

<Application.Resources>
<x:Double x:Key="TreeViewItemIndent">2</x:Double>
</Application.Resources>

I've also tried in the style like so;

<Style Selector="TreeViewItem">
<Setter Property="Margin" Value="2,0,0,0"/>
</Style>

Thanks again for taking the time to try and help, much appreciated.

**Comment by timunie** [comment]
Could it be you are using not FluentTheme? If so, you have to digg there. Other than that you may need to copy and experiment with original style

**Comment by rabbitism** [comment]
I think indent should be a property of tree view item?

**Comment by winkmichael** [comment]
Thanks for your comments @timunie I've been throwing together attempt after attempt without any luck. I had the fluent theme, but yet it is still being ignore nothing seems to be respected from app.axaml. I even tried to set it right in the view itself below without luck like the sample below.

```
<UserControl
    x:Class="PanelXViews.LeftPanelView"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:vm="clr-namespace:PanelX.ViewModels"
    x:DataType="vm:LeftPanelViewModel"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    d:DesignWidth="250" d:DesignHeight="450">

    <UserControl.Resources>
        <x:Double x:Key="TreeViewItemIndent">2</x:Double>
    </UserControl.Resources>

    <UserControl.Styles>
        <FluentTheme />
    </UserControl.Styles>
  
    <Grid RowDefinitions="Auto,*">
        <!-- Debug Controls -->
        <StackPanel Grid.Row="0" Orientation="Horizontal" Margin="4">
            <Button Content="Reload Tree" Command="{Binding LoadCommand}" Classes="accent" Margin="0,0,4,0"/>
            <TextBlock Text="{Binding RootNodes.Count, StringFormat='Units: {0}'}" VerticalAlignment="Center"/>
        </StackPanel>

        <Border Grid.Row="1" 
                Background="{DynamicResource SecondaryColor}" 
                BorderBrush="Gray" 
                BorderThickness="1" 
                Margin="2"
                Padding="0">
            <TreeView Name="TreeViewControl"
                    ItemsSource="{Binding RootNodes}"
                    Background="{DynamicResource AppBackgroundColor}"
                    SelectedItem="{Binding SelectedNode}">
                <TreeView.ItemTemplate>
                    <TreeDataTemplate DataType="vm:NodeViewModel" ItemsSource="{Binding Children}">
                        <TextBlock Text="{Binding NodeName}" />
                    </TreeDataTemplate>
                </TreeView.ItemTemplate>
            </TreeView>
        </Border>
    </Grid>
</UserControl>
```
