### ISSUE TITLE
Keyboard input problem for macOS Agent Windows

### ISSUE THREAD

**Issue by sshulik** [AvaloniaUI/Avalonia#4849]
If I run Avalonia App as `macOS Agent` OR set `.With(new MacOSPlatformOptions {ShowInDock = false})` Window can't handle any keyboard input. Look like Keyboard input keeps in the previous window (see attached gif)

![ezgif-1-5680ed3760c4](https://user-images.githubusercontent.com/2964570/95727462-d4c69d00-0c82-11eb-854f-cf4926c224ee.gif)

**Comment by kekekeks** [comment]
Have you actually bundled the app and added `LSUIElement` the corresponding `.plist` ?

**Comment by kekekeks** [comment]
Also try calling `NSApplication.SharedApplication.ActivateIgnoringOtherApps(true);` from `PointerPressed` preview (tunnel) handler attached to the window.

NSApplication class can be accessed through can be found in [MonoMac nuget](https://www.nuget.org/packages/MonoMac.NetStandard/), make sure to call `NSApplication.Init()`; from `Main()`

**Comment by sshulik** [comment]
> Have you actually bundled the app and added LSUIElement to its .plist ?
No, if you just run app as agent: add to '~/Library/LaunchAgents/com.myapp.plist' with content like
```
        <key>ProgramArguments</key>
        <array>
            <string>dotnet</string>            
            <string>/Users/[username]/Code/MyApp/Contents/bin/MyApp.dll</string>
        </array>
```
you will see this issue. No `Info.plist` needed. If you run it's like a regular app from the command line - it's work fine. (P.S.: tested on 10.5 Catalina)


> Also try calling NSApplication.SharedApplication.ActivateIgnoringOtherApps(true); from PointerPressed preview (tunnel) handler attached to the window.
> NSApplication class can be accessed through can be found in MonoMac nuget, make sure to call NSApplication.Init(); from Main()
Do you mean this project https://github.com/mono/monomac? Hm, but it's deprecated and too buggy. I have used them to implement the taskbar/status menu but got too many problems with memory corruption and rewrite it with AppKit Interop by myself. Hm... you think it's should be enough to call `ActivateIgnoringOtherApps` for `SharedApplication`? Thanks, I will try... but anyway, its looks like a crutch. Not sure, that it's a good idea to add event handler to each text box in App to make this workaround only for Mac. It's will break cross-platform implementation: at least need to introduce new abstraction to avoid crashes on Windows/Linux.

**Comment by sshulik** [comment]
@kekekeks unfortunately your suggestion with `NSApplication.SharedApplication.ActivateIgnoringOtherApps(true);` not works. Maybe you have any other ideas?

**Comment by kekekeks** [comment]
I think you still need to actually set LSUIElement in an app bundle of some sort, otherwise OS is confused.

**Comment by sshulik** [comment]
Already had tried to do this mix `LSUIElement` and `NSApplication.SharedApplication.ActivateIgnoringOtherApps(true);`. 
BUT the problem is not that Dock icon disappear: problem is that somehow WIndow, which runs as Agent app, can't handle keyboard input. I think it's a more general problem.

**Comment by kekekeks** [comment]
>Hm, but it's deprecated and too buggy

It's sufficient for simple interop scenarios when you don't need to have your own "ObjC" classes.

>problem is that somehow WIndow, which runs as Agent app, can't handle keyboard input

The problem is that OSX gets confused about activation modes and fails to properly transfer the focus to the window. So it's needed to "fix" that somehow.

So, my current suggestion would be to also modify the bundle in memory, like described here: https://lists.qt-project.org/pipermail/interest/2015-November/019937.html (do this as close to the start of `Main` as possible) and manually set NSApplication activation policy to accessory in `FrameworkInitializationCompleted` instead of waiting it to be set by Avalonia in `applicationWillFinishLaunching`

**Comment by sshulik** [comment]
Just for history: in common problem still not solved: if I run the app as Agent app can't handle keyboard input. No fixes can help.
If someone faced which the same problem temporary workaround, which I use: in my system besides the agent app, I have a daemon, which run as root. This daemon runs agent ap as a regular app for each logged-in user through `launchctl`:
``` launchctl asuser {uid} sudo -u {userName} {command} {crgs} ```
where uid - macOS UserId.
