### ISSUE TITLE
Implement Opacity Mask

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#485]

**Comment by grokys** [comment]
Is this related to #359 ?

**Comment by danwalmsley** [comment]
no, see this example, very bottom of this page...

http://mahapps.com/guides/quick-start.html

In this case its used to make a standard set of icons any colour, so the icons says which parts of the visual are opaque and by how much.

This is quite powerful for icons and other effects.

**Comment by danwalmsley** [comment]
actually this is a better explanation of the use case:
http://mahapps.com/guides/icons-and-resources.html

**Comment by grokys** [comment]
Oh yeah, I didn't realise WPF had both opacity masks and path clipping. I'd somehow conflated them both in my head.

**Comment by danwalmsley** [comment]
do you think its a difficult feature to implement?

**Comment by danwalmsley** [comment]
@jkoritzinsky perhaps the implementation of this would be fairly similar to your recent work on path based clipping?

**Comment by jkoritzinsky** [comment]
Looks like it for Direct2D1. Need to do more investigation into how to do it in Skia and Cairo (if possible).

-----Original Message-----
