### ISSUE TITLE
Chinese characters or emoji's doesn't diplay in TextPresenter

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#4859]
example text:
Chinese: 表意文字. Japanese: 和製漢字 emoji: ☚

example xaml:
```xaml
    <Border BorderThickness="2" BorderBrush="Black" HorizontalAlignment="Left" Padding="5">
      <StackPanel>
        <TextBlock Text="TextBlock: Chinese: 表意文字. Japanese: 和製漢字 emoji: ☚" />
        <TextPresenter Text="TextPresenter: Chinese: 表意文字. Japanese: 和製漢字 emoji: ☚" />
      </StackPanel>
    </Border>
```
result (TextBlock is working fine):
![image](https://user-images.githubusercontent.com/13854631/95890760-da100e80-0d8c-11eb-9acf-ce02ce26eabb.png)

**Comment by kekekeks** [comment]
Workaround:
>You need to use a font that has Chinese characters. https://github.com/anthonyfok/fonts-wqy-microhei is a good one
[WenQuanYiMicroHei-01.ttf.zip](https://github.com/AvaloniaUI/Avalonia/files/5703016/WenQuanYiMicroHei-01.ttf.zip)
>
>Place it into Assets, add as AvaloniaResource and add something like
>
>```
><Style Selector="TextBlock">
>    <Setter Property="FontFamily" Value="avares://YourAssemblyName/Assets/Fonts#WenQuanYi Micro Hei" />
></Style>
>```
>to your App.xaml after the theme

**Comment by Gillibald** [comment]
Fixed in current master
