### ISSUE TITLE
Question: How to get multiple css classes that each set a part of the margin?

### ISSUE THREAD

**Issue by 8** [AvaloniaUI/Avalonia#4861]
Hi,

I have a question about the class based styling system and was wondering if there is a solution to my problem:

I would like to mimic the behavior of css, where I can have two separate css classes applied on a single element, where the first sets e.g. `margin-bottom` and the second sets `margin-top`.

In Avalonia, this doesn't work, as Margin is of Type `Thickness` and Thickness is a struct that sets Left, Top, Right and Bottom all at once. Therefore if I apply two classes on one element, the second class basically "wins" and overwrites the value set by the first class with it's value, e.g. 0.

I would have tried setting it to `null`, but the values are not-nullable, I tried setting it to `Double.NaN` but that threw an exception.

Is there some way to avoid that behavior so that those two classes can peacefully co-exist? :)

Take care,
Martin

**Comment by maxkatz6** [comment]
As you said, there is no margin-left (top, right, bottom) properties in the Avalonia (as well as in other XAML frameworks). And you can't update only part of the struct with styles or binding.

What you do can do is create attached property MarginLeft, and in its "value changed" callback you can update margin.Left from C# code (creating new struct with one new and three old values).

**Comment by 8** [comment]
Thanks for your suggestion, I was able to solve the issue by:

1. setting the Thickness properties I do not care about the double.NaN instead of 0.
2. writing a customer Setter that implements `ISetter` replaces double.NaN values in a Thickness property with the current value of the property.

Now I can apply to Classes that both set margin / padding and have them both applied!

Take care,
Martin
