### ISSUE TITLE
TextBlock with restricted height doesn't center vertically properly

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#4866]
Bug applies to `TextBlock` and `TextPresenter` when vertical space is less from what's needed for the font metrics for `VerticalAlignment` - Center and Bottom.
repro
```xaml
    <Border BorderThickness="1" BorderBrush="Black" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="20" Padding="2">
      <StackPanel Orientation="Horizontal" TextBlock.FontSize="30" >
        <TextBlock Text="Auto Height (Centered): " />
        <Border BorderThickness="1" BorderBrush="Black" VerticalAlignment="Center">
          <TextBlock Text="L" VerticalAlignment="Center" />
        </Border>
        <TextBlock Text=" Restricted Height (Not Centered): " />
        <Border BorderThickness="1" BorderBrush="Black" VerticalAlignment="Center" Height="32">
          <TextBlock Text="L" VerticalAlignment="Center"/>
        </Border>
      </StackPanel>
    </Border>
```
result:
![image](https://user-images.githubusercontent.com/13854631/95999066-30895580-0e3e-11eb-99dd-01a47fe2b667.png)

wpf result for reference:
![image](https://user-images.githubusercontent.com/13854631/95999815-f1a7cf80-0e3e-11eb-9ac5-815347ae7976.png)

**Comment by Gillibald** [comment]
![Uploading Screenshot 2020-10-14 185754.png…]()

**Comment by Gillibald** [comment]
The Text has a height of `36px` but the border has a fixed height of `32` so the Text is clipped.

**Comment by Gillibald** [comment]
@grokys How are visuals clipped in that scenario? It looks like the visual isn't centered and the bottom part is cut off.
