### ISSUE TITLE
How to make a custom brush?

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#4885]
Hello, Now I'm thinking make some custom brushes, but I found a problem, first I thought use ```Render(DrawingContext)``` like the Visual class, but the Brush class doesn't have that method, is there a way to do it?

**Comment by maxkatz6** [comment]
I don't think it is possible now. All supported IBrush types is strictly limited to specific platform and implemented internally.
https://github.com/AvaloniaUI/Avalonia/blob/ebdb8aeaa38b2225fec77f1bdbc59dd508e0fc6f/src/Skia/Avalonia.Skia/DrawingContextImpl.cs#L831

**Comment by maxkatz6** [comment]
Although you can try to do something with https://github.com/AvaloniaUI/Avalonia/blob/9b73c1027b8bc03b8f2501d0fe4df8d311be7dac/src/Avalonia.Visuals/Media/VisualBrush.cs
