### ISSUE TITLE
building nuget packages fails

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/Avalonia#4889]
I'm trying to build the nuget packages with:
`$ ./build.sh --target Package --skip CompileHtmlPreviewer`

It is ending with the following errors:

> /usr/local/share/dotnet/sdk/3.1.401/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(198,5): error : Could not find a part of the path '/build/Assets'. [/Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Build.Tasks/Avalonia.Build.Tasks.csproj]
> /usr/local/share/dotnet/sdk/3.1.401/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error NU5046: The icon file 'Icon.png' does not exist in the package. [/Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Avalonia.Base.csproj]
>

The last one is repeated numerous times for other projects.  This shows that two of the generated nuspec files contain an absolute path.  It appears that this should be relative.

`$ find . -type f -name \*.nuspec -exec grep -H '/build/Assets' {} \;`

> ./packages/Avalonia/obj/Release/Avalonia.0.10.999.nuspec:    <file src="/build/Assets/Icon.png" target="Icon.png" />
> ./src/Avalonia.DesktopRuntime/obj/Release/Avalonia.DesktopRuntime.0.10.999.nuspec:    <file src="/build/Assets/Icon.png" target="Icon.png" />
> ./src/Avalonia.Build.Tasks/obj/Release/Avalonia.Build.Tasks.0.10.999.nuspec:    <file src="/build/Assets/Icon.png" target="Icon.png" />

This is my "dotnet --info":

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.401
>  Commit:    39d17847db
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.15
>  OS Platform: Darwin
>  RID:         osx.10.15-x64
>  Base Path:   /usr/local/share/dotnet/sdk/3.1.401/
> 
> Host (useful for support):
>   Version: 3.1.8
>   Commit:  9c1330dedd
> 
> .NET Core SDKs installed:
>   3.1.201 [/usr/local/share/dotnet/sdk]
>   3.1.302 [/usr/local/share/dotnet/sdk]
>   3.1.401 [/usr/local/share/dotnet/sdk]
>   3.1.402 [/usr/local/share/dotnet/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download
>

**Comment by kekekeks** [comment]
The only thing referencing "Icon.png" is "Microsoft.DotNet.ApiCompat/5.0.0-beta.20372.2" project.json section. @danwalmsley 

I don't think we have `build/Assets` anywhere

**Comment by workgroupengineering** [comment]
@mrj001 try this #4890 PR

**Comment by mrj001** [comment]
@workgroupengineering, yes that generates the nuget packages now.  Thanks.

**Comment by mrj001** [comment]
Closing after merge of #4914.
I'm able to build nuget packages from current head.
