### ISSUE TITLE
Window AutoSize + TabControl with ScrollViewer diferent behaviour on Win and Linux, 0.10.999-cibuild0011401-beta

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#4896]
I'm trying to constrain a AutoSized window to screen height, so when window auto height is bigger than screen resolution i adjust a scrollviewer height to achieve this.

My window consists on TabControl, each TabItem have a `<ScrollViewer MaxHeight="{Binding ScrollViewerMaxHeight}">`
On ctor: `ScrollViewerMaxHeight = Screens.Primary.WorkingArea.Height - 700;`
This works fine on windows, however on linux it resize the window when change tab and lost the ability of resize on forwards tab changes. If i remove the ScrollViewer it works again as auto size window

AXAML: https://github.com/sn4k3/UVtools/blob/master/UVtools.WPF/Windows/SettingsWindow.axaml#L149
Code: https://github.com/sn4k3/UVtools/blob/master/UVtools.WPF/Windows/SettingsWindow.axaml.cs#L52
Result: https://youtu.be/hGVqm1N7prA

Also there's any other better way to achieve this?

**Comment by maxkatz6** [comment]
> Also there's any other better way to achieve this?

I would recommend setting initial Width and Height in the SettingsWindow.axaml. It should be same size on Linux and Windows while still allow resizing.

**Comment by danwalmsley** [comment]
@sn4k3 does setting a margin of `0 0 0 700` on the scrollviewer and leaving the max height property alone not work for this?

**Comment by sn4k3** [comment]
@danwalmsley No, it does a big margin on bottom and nothing more. my objective is put scrollviewer into action when content pass the resolution height. It work on windows but on linux you can see it hides content from tabs and stop auto adjusting height and width, so i guess is a AutoSize problem on linux.
Also if you manual resize a autosize window on linux it stop from autoresizing

**Comment by sn4k3** [comment]
Ok i find a workarround to "fix" this.
By simply reset SizeToContent on tab change make linux to work like windows and it re-adjust size to current tab:

```C#
public int SelectedTabIndex
        {
            get => _selectedTabIndex;
            set
            {
                if(!RaiseAndSetIfChanged(ref _selectedTabIndex, value)) return;
                SizeToContent = SizeToContent.Manual;
                SizeToContent = SizeToContent.Height;
            }
        }
```

**Comment by sn4k3** [comment]
Looks like fixed. It dont require the hack anymore
