### ISSUE TITLE
The MenuItem icon is not displayed...

### ISSUE THREAD

**Issue by Aaronlog** [AvaloniaUI/Avalonia#4897]
In my project, the icon of the top-level menu is not displayed, but the icon of the sub-menu can be displayed normally. Do I need to set a property for the top-level menu separately?
![1](https://user-images.githubusercontent.com/41666145/96672525-151acf00-1397-11eb-82a4-1a29f757f70e.png)
![2](https://user-images.githubusercontent.com/41666145/96672533-16e49280-1397-11eb-8e3b-ea411fe35c84.png)

**Comment by maxkatz6** [comment]
You can use Header property.

@danwalmsley probably we should handle Icon for top level menu as well.

**Comment by TinyDinosaur** [comment]
The example code in the documentation doesn't work. Maybe change the documentation for now?

https://avaloniaui.net/docs/controls/menu#menu-icons

**Comment by maxkatz6** [comment]
@TinyDinosaur documentation example works, but only if it's not used in top level menu item.

**Comment by lostmsu** [comment]
Was this fixed? Why is this closed. A workaround is OK, but

**Comment by otac0n** [comment]
This is still an issue.  How do I show the icon in the same size/style in the top-level menu?
