### ISSUE TITLE
Avalonia: Loading resources with resm throws FileNotFound Exception

### ISSUE THREAD

**Issue by marwie** [AvaloniaUI/Avalonia#4902]
Hello,

this is an exception I got using the new Rider support. I raised an issue at their issue tracker, but they said it looks like an Avalonia issue.

Please refer to the following issue for more info

https://youtrack.jetbrains.com/issue/RIDER-52627

**Comment by Gillibald** [comment]
For AvaloniaResource you need to use the avares scheme
