### ISSUE TITLE
Control.Click Routed Event Won't Compile

### ISSUE THREAD

**Issue by Aaronlog** [AvaloniaUI/Avalonia#4910]

**Comment by pr8x** [comment]
Without a proper description or repro nobody is able to help you.

**Comment by kekekeks** [comment]
Probably wrong event handler signature

**Comment by Aaronlog** [comment]
@pr8x @kekekeks  I'm sorry I miswrote the title, Actually,  I want to know is how Avalon will implement a click event like WPF

**Comment by MarchingCube** [comment]
Documentation should be a good starting point: http://avaloniaui.net/docs/quickstart/codebehind#handling-events
