### ISSUE TITLE
How to get TextBox to only accept numbers?

### ISSUE THREAD

**Issue by SpyceTewan** [AvaloniaUI/Avalonia#4915]
I looked around for ages but couldn't find anything on this. I tried setting up validation (which is also very undocumented), but still have issues with that.

My TextBox is supposed to only accept unsigned integers. I think there should be some easy property to set to TextBox to define what types of inputs it can accept. (Android has this)

I tried 
```cs
public uint? AppId {
get => _appId;
set
  {
    if(!(value is uint?))
    {
      throw new DataValidationException("Invalid Steam App Id");
    }

    _appId = value;
  }
}
```
which I got from #4845, but the problem is that the program still closes with `System.ArgumentException: 'f is not a valid value for UInt32. (Parameter 'value')'`, since the property itself doesn't accept strings.

**Comment by SpyceTewan** [comment]
Just to confirm: This exception works when the field is empty, but not when you enter a string.
![image](https://user-images.githubusercontent.com/31664665/96861160-00f0d380-1464-11eb-9c91-6c40df549859.png)

**Comment by lavjamanxd** [comment]
If you want to directly bind the Text property of a TextBox to an uint32, wont work since Text is a string, and the system wont convert it automagically. (i assume that you have that AppId on a ViewModel and you are trying to bind it to the view)

You will need to implement a IValueConverter which converts string->int and then tell the binding to use that.

If you want to have only numbers in the TextBox, most probably the best way is to use behaviors and implement one which checks for the text changed then if theres a non-numeric character in the field, removes it. This way you will have a reusable component for the future.

**Comment by maxkatz6** [comment]
@SpyceTewan as mentioned above, you can use Converter or Behaviors.

Although I would be nice to have UWP [InputScope](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.inputscope?view=winrt-19041#Windows_UI_Xaml_Controls_TextBox_InputScope) alternative (possible values - [link](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.inputscopenamevalue?view=winrt-19041)).
With that this issue could be solved simply ```<TextBox InputScrope="Number" />```
But I believe this feature should be planned and introduced only with IME and mobile in mind @kekekeks.

**Comment by robloo** [comment]
A NumberBox-type control would also be intended for this situation. I admit I'm not familiar with Avalonia enough to know if the arrows can be disabled in the NumericUpDown control.

**Comment by maxkatz6** [comment]
@robloo yes, arrows can be disabled on NumericUpDown with ShowButtonSpinner property.

@SpyceTewan as @robloo mentioned, it probably will be easier for you to use NumericUpDown control instead of TextBox. It has "double Value" property, so you don't need to convert string to number on your side.

**Comment by SpyceTewan** [comment]
Thanks! I managed to get it working using NumericUpDown. One little inconvenience to note is that binding to a uint doesn't work. I understand that it's because the NumericUpDown uses a double, but I feel like this is something that should be possible at some point. Just a small convenience addition I guess.

**Comment by robloo** [comment]
If you make a converter you could get the binding to work directly between uint and double. Glad its working for you though!

**Comment by Dorin-Foaltin** [comment]
@StefanH-AT: have you managed to fully restrict input of invalid characters, like letters (eg: 'a'  or 'b')? 

I'm trying to allow only entering of numbers, and it seems like this should work, but for me it only works after the app is minimized + restored, forcing a redraw. 

I've tried calling InvalidateVisual()/ other methods after KeyDown/ KeyUp/ ValueChanghed, but this doesn't really fix it, so I was thinking maybe you have a work around for it? 

In this gif below, see that I can enter letters, these are not cleared until I minimize and restore the app:

![NumericUpDownRefreshIssue](https://user-images.githubusercontent.com/75241559/121868113-4753b500-cd09-11eb-83de-ed78f67f4d2c.gif)

**Comment by maxkatz6** [comment]
@Dorin-Foaltin handle TextInput with tunnel (preview) strategy https://github.com/AvaloniaUI/Avalonia/issues/5753#issuecomment-817241375

**Comment by SuperJMN** [comment]
I have created this:

https://github.com/SuperJMN-Zafiro/Zafiro.Avalonia/blob/master/Zafiro.Avalonia/NumberBoxBehavior.cs

Usage: 

- nuget add Avalonia.Xaml.Behaviors

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:views="clr-namespace:TextPlays.Views"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        xmlns:i="clr-namespace:Avalonia.Xaml.Interactivity;assembly=Avalonia.Xaml.Interactivity"
        x:Class="TextPlays.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="TextPlays">

    <TextBox>
        <i:Interaction.Behaviors>
            <views:NumericTextBoxBehavior />
        </i:Interaction.Behaviors>
    </TextBox>

</Window>
```
Hope it helps!

**Comment by aboimpinto** [comment]
> I have created this:
> 
> https://github.com/SuperJMN-Zafiro/Zafiro.Avalonia/blob/master/Zafiro.Avalonia/NumberBoxBehavior.cs
> 
> Usage:
> 
> * nuget add Avalonia.Xaml.Behaviors
> 
> ```
> <Window xmlns="https://github.com/avaloniaui"
>         xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>         xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
>         xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
>         xmlns:views="clr-namespace:TextPlays.Views"
>         mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
>         xmlns:i="clr-namespace:Avalonia.Xaml.Interactivity;assembly=Avalonia.Xaml.Interactivity"
>         x:Class="TextPlays.Views.MainWindow"
>         Icon="/Assets/avalonia-logo.ico"
>         Title="TextPlays">
> 
>     <TextBox>
>         <i:Interaction.Behaviors>
>             <views:NumberBoxBehavior />
>         </i:Interaction.Behaviors>
>     </TextBox>
> 
> </Window>
> ```
> 
> Hope it helps!

this is not available anymore ...
