### ISSUE TITLE
Large working set when using .jpgs

### ISSUE THREAD

**Issue by Geektoolkit** [AvaloniaUI/Avalonia#4929]
I noticed that an app I'm working on which uses two images at 1080p had an unusually high (over 400mb) working set. So I did some experiments and found out the following data:
Baseline (Visual studio template which just creates a window) -
at 1080p: 33mb 
at 4k:  78mb 

195.8mb full screened 4k
154.6mb full screen (1080p)
The test file was a1.45 MB JPG file with a resolution of: (4167x4167)

Test File2: 83k file (1920x1080)
Full screen at 4k - 87 megs

TestFile 2 (again): Resized to 1.54 MB with a resolution of (4167x4167)
150mb full screen 1080p

Code was simply adding to the default template: 
<Image Source="C:\Users\joefa\Pictures\testfile.jpg" />

I was running this on a raspberry pi 3A+ with a resolution of 1080p. That means if I hit 2 'large' images the kernel kills the app.  Is there a more efficient way to display a bitmap than image? or a way to lower resources?  Or is this just the cost of the framework?

This is on .10 Preview 3

**Comment by danwalmsley** [comment]
@Geektoolkit here is my reply from gitter:

```
@Geektoolkit we have had a long investigation into this and significant improvments will come in preview6
and when mono/SkiaSharp#1529 is merged
we beleive we will have even further reduction in memory.
btw if you display any image fullscreen its going to take way more than 1.45mb...
the 1.45 mb is just the compressed data
you have to allocate 4bytes per pixel displayed on the screen (at least)
so on a 4k display the minimum video memory to display that jpeg fullscreen is ~35mb
in preview3 im sure it will be allocating double or triple that,
```

**Comment by danwalmsley** [comment]
@Geektoolkit if you would like to try out a nightly build:

`0.10.999-cibuild0011371-beta` has the relevant fixes in... would be good to get your test results on that build.

You need the feed: `https://nuget.avaloniaui.net/repository/avalonia-all/index.json`

**Comment by Geektoolkit** [comment]
I got a 500 error when trying to add that source, so I'll have to try again later.  I tried 11383 from https://www.myget.org/F/avalonia-ci/api/v2 but that ran slightly slower, and I have a feeling the 'v2' in that means a different branch, or just that I'm not getting the latest stuff. I'll have to try again when I get time

**Comment by Geektoolkit** [comment]
This can be closed/resolved. I'm not seeing near the working set as of Preview six...which is great!
