### ISSUE TITLE
Avalonia running on Raspberry PI with Touchscreen

### ISSUE THREAD

**Issue by dinonovak** [AvaloniaUI/Avalonia#4937]
Hi all,
finally got it working with framebuffer.
Big thanx for hint:
```
if (ApplicationLifetime is ISingleViewApplicationLifetime single)
{
    single.MainView = new UserControl1(); // OK
}
```
GUI is finally showing up.

I would like to enable keyborad & mouse under framebuffer - is this possible?

Also any hints on getting touchscreen working are appreciated, I am using 5" 800x480 display with XPT2046 touch controller. Any info on how to get it working is appreciated (plain framebuffer, no X-windows).

**Comment by kekekeks** [comment]
Keyboard and mouse aren't supported, for touch you need to either make sure that it's available via libinput or set it up using evdev (`AVALONIA_USE_EVDEV=1`, `AVALONIA_EVDEV_DEVICE_0=/dev/input/event1:type=touchscreen`)
