### ISSUE TITLE
Spacing of Grid children

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/Avalonia#4940]
Avalonia version: 0.10.0-preview5

Starting with the avalonia.app template, I replaced "Welcome to Avalonia" with the following xaml:
```
   <Border Background="black" BorderThickness="30">
      <Grid RowDefinitions="*,*" 
            ColumnDefinitions="*,*" 
            Width="400" 
            Height="300" 
            Background="Yellow" 
            >
         <Grid.Styles>
            <Style Selector="Image">
               <Setter Property="Margin" Value="0" />
            </Style>
         </Grid.Styles>
         <Image Grid.Row="0" Grid.Column="0" Source="/Assets/Red.png" />
         <Image Grid.Row="0" Grid.Column="1" Source="/Assets/Green.png" />
         <Image Grid.Row="1" Grid.Column="0" Source="/Assets/Black.png" />
         <Image Grid.Row="1" Grid.Column="1" Source="/Assets/Blue.png" />
      </Grid>
   </Border>
```

The various assets are 32x32 bit images with the obvious content.  This is what the resulting window looks like:

![Screen Shot 2020-10-26 at 3 07 01 PM](https://user-images.githubusercontent.com/62225294/97230067-ea69b580-179e-11eb-8d04-563bcd0bc245.png)

The child image controls are flush vertically with both the border and each other.  However, horizontally there is a gap between the images.

Is this supposed to be this way?

**Comment by maxkatz6** [comment]
I believe you need to add HorizontalAlignment="Stretch" to your images

**Comment by mrj001** [comment]
Thanks.  I added these two properties, and it works.
```
               <Setter Property="HorizontalAlignment" Value="Stretch" />
               <Setter Property="Stretch" Value="Fill" />
```
