### ISSUE TITLE
VisualBrush does not work in Avalonia.Skia

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#4944]
```XAML
        <VisualBrush x:Key="TemplateCheckerBoard" TileMode="Tile" Stretch="None" AlignmentX="Left" AlignmentY="Top" SourceRect="0,0,20,20" DestinationRect="0,0,20,20">
            <VisualBrush.Visual>
                <StackPanel Orientation="Horizontal">
                    <StackPanel Orientation="Vertical">
                        <Rectangle Width="10" Height="10" Fill="#FFF0F0F0"/>
                        <Rectangle Width="10" Height="10" Fill="#FFF5F5F5"/>
                    </StackPanel>
                    <StackPanel Orientation="Vertical">
                        <Rectangle Width="10" Height="10" Fill="#FFF5F5F5"/>
                        <Rectangle Width="10" Height="10" Fill="#FFF0F0F0"/>
                    </StackPanel>
                </StackPanel>
            </VisualBrush.Visual>
        </VisualBrush>
```

SkiaSharp:

![SkiaSharp](https://user-images.githubusercontent.com/2297442/97309227-08e4b500-1862-11eb-9b3b-47b67c269ffd.PNG)

The Direct2D1 version works:

![Direct2D1](https://user-images.githubusercontent.com/2297442/97309242-0d10d280-1862-11eb-98cb-e96cce8c2f5f.PNG)

version: 0.10.0-preview6

**Comment by maxkatz6** [comment]
ComboBox with custom data template doesn't work for same reason - it uses VisualBrush internally.

**Comment by kekekeks** [comment]
Try adding `return null;` here https://github.com/AvaloniaUI/Avalonia/blob/849c98aeb767ac10f7b26f21546823791ac5dab5/src/Skia/Avalonia.Skia/Gpu/OpenGl/GlSkiaGpu.cs#L51

**Comment by maxkatz6** [comment]
@kekekeks I can confirm it solved the problem at some point - VisualBrush is rendered now.

Although there is some problem with its rendering:

Closed ComboBox:
![image](https://user-images.githubusercontent.com/3163374/97362096-e0b38100-1876-11eb-9b96-fb58eb84ddc2.png)


Opened ComboBox:
![image](https://user-images.githubusercontent.com/3163374/97362117-e4df9e80-1876-11eb-9b6d-fb66a1c89e31.png)

There is no margins/paddings or alignment problems as I can see from DevTools. And window resize fixes it.

**Comment by wieslawsoltes** [comment]
Looks like GPU issue when using Skia. When I set `AllowEglInitialization = false` VisualBrush works.

**Comment by wieslawsoltes** [comment]
I can actually trigger rendering of `VisualBrush` be displaying element with `BoxShadow` applied.

**Comment by wieslawsoltes** [comment]
> I can actually trigger rendering of `VisualBrush` be displaying element with `BoxShadow` applied.

![BoxShadow](https://user-images.githubusercontent.com/2297442/98646534-cc21bf00-2333-11eb-9e9d-4ebe3b4ebe31.gif)
