### ISSUE TITLE
WinFormsAvaloniaControlHost: Renderer is not started by default

### ISSUE THREAD

**Issue by stepangovorko** [AvaloniaUI/Avalonia#4951]
Renderer is not started by default if Avalonia app is hosted in WinFormsAvaloniaControlHost. 
To reproduce see WindowsInteropTest/EmbedToWinFormsDemo.

As a workaround I can start it manually by using:
((TopLevel)content.GetVisualRoot()).Renderer.Start();

**Comment by jasongf** [comment]
Can you clarify where you added the line of code to the demo to start the renderer?

**Comment by stepangovorko** [comment]
@jasongf try this
![image](https://user-images.githubusercontent.com/72131794/99363507-1fa48780-28b5-11eb-869d-3af1c7459d55.png)

**Comment by jasongf** [comment]
@stepangovorko Intellisense can't find GetVisualRoot as a member of Content. Am I missing a using directive?

**Comment by stepangovorko** [comment]
@jasongf check `Avalonia.VisualTree.VisualExtensions` class

**Comment by jasongf** [comment]
@stepangovorko that's it thank you. 
Add 
`using Avalonia.VisualTree;`
