### ISSUE TITLE
Add SplitButton and ToggleSplitButton porting over from WinUI

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#4959]
Would be great to add these two controls to Avalonia porting over from WinUI. I'll do this myself if I get a thumbs-up.

SplitButton

 * https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.splitbutton?view=winrt-19041

ToggleSplitButton

 * https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.togglesplitbutton?view=winrt-19041

Comparison of button controls:

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/buttons

**Comment by worldbeater** [comment]
Cool stuff! Would be happy to see these awesome buttons in Avalonia 🥰

**Comment by robloo** [comment]
Looks like I have a weekend project then :)

**Comment by robloo** [comment]
To implement this correctly it depends on #5172. 

Otherwise, it should be possible to do something similar to what ComboBox already does. In the future there would likely need to be a breaking change to align the API with WinUI if/when Flyout is added to Avalonia though.

**Comment by robloo** [comment]
Flyouts are in progress. Hopefully can start this soon.

**Comment by Splitwirez** [comment]
@robloo FYI the Flyouts PR has now been merged. Happens that https://github.com/AvaloniaUI/Avalonia/discussions/5893 reminded me of this, so I figured I may as well let you know. I'm sure they'd love to see the `SplitButton` and `ToggleSplitButton` ported over :+1:

**Comment by maxkatz6** [comment]
@Splitwirez @robloo just for case, there are already ports of these controls https://github.com/amwx/FluentAvalonia/blob/master/FluentAvalonia/UI/Controls/Button/SplitButton.cs

In our case, I am not sure, if it should be in core repo or some kind of our own community toolkit.

**Comment by robloo** [comment]
@Splitwirez Yea, it's still on the todo list along with DropDownButton. I'll make time to finish these for 0.11. I dont have a lot of spare time these days.

@maxkatz6 The criteria for whether controls should be added directly to Avalonia is simple in my mind. If the control exists in WPF/WinUI it should be added without having to use a 3rd party library. This significantly increases developer friendliness and adoption. 

.NET UI layers are undergoing significant changes over the past years but I think we are past the difficult part and it will slow down and stabilize. I dont think maintenence burden will be significant long term.

**Comment by pr8x** [comment]
Hey, may I ask what the current state of this is? Is this still being worked?

**Comment by pr8x** [comment]
> Would you be willing to help test?

For sure, we need something like this for Application. Happy to help with testing and feedback once a PR is there 👍
