### ISSUE TITLE
Add DropDownButton porting over from WinUI

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#4960]
Would be great to add a DropDownButton to Avalonia porting over from WinUI. I'll do this myself if I get a thumbs-up from the core team.

 * https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.dropdownbutton?view=winui-2.4

Comparison of button controls:

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/buttons

**Comment by robloo** [comment]
I think I'll finish this one over the weekend. It is a pretty important component in a lot of custom-control scenarios. It's essentially used as a primitive. It is the last prerequisite for the ColorPickerButton.

If anyone objects to adding this, please let me know now.

**Comment by sinatrocious** [comment]
Seems to be a useful control. But [no docs](https://docs.avaloniaui.net/docs/reference/controls/dropdownbutton), even [designer preview](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/DropDownButton.xaml) is pathetic.
