### ISSUE TITLE
"Unable to find type" XAMLIL error message after deleting window from project

### ISSUE THREAD

**Issue by joneuhauser** [AvaloniaUI/Avalonia#4968]
This is a weird one. Versions: AvaloniaUI 0.10.0-pre6, Avalonia for Visual Studio 0.9.11.0

Steps:
1. Create a new Avalonia Project (doesn't matter if MVVM or not)
2. Right click project -> add a new Window
3. Don't change the name of the window, will be named Window1.axaml
4. Delete the Window by deleting the file Window1.axaml. This deletes both Window1.axaml and Window1.axaml.cs.

Try to compile the solution.  An error message occurs: Unable to find type `AvaloniaApplication1.Window1` Line 1, Position 2.

Grep the entire solution for Window1. No result.

Clean and rebuild the solution. The error persists.

Workaround I found:
- Add a window with the same name again.
- Rename the window. Only now will the window name show up in the csproj file
- Delete the renamed window.

Now everything compiles fine again.

**Comment by MarchingCube** [comment]
I found something similar (although incorrectly reported it in the compiler repo) https://github.com/kekekeks/XamlX/issues/37

**Comment by molnard** [comment]
Walkaround solution can be to delete compiled files with:

`git clean -xdf`

and rebuild the solution.

**Comment by MarchingCube** [comment]
This issue seems to appear fairly frequently lately and basically means that deleting XAML files without changing a line of code in a project will end up with this error.

Also in my case forcing 20+ devs to wipe their repo and rebuild for 10 minutes is not the greatest option. @kekekeks Are you going to have time to investigate this sometime?

**Comment by kekekeks** [comment]
That error means that XAML resource is still present in either Roslyn-generated assembly or `obj/$(Configuration)/$(TargetFramework)/Avalonia/resources` file.

[GenerateAvaloniaResources](https://github.com/AvaloniaUI/Avalonia/blob/94fcbfbbe98f6cf9db17631575c975395be30445/packages/Avalonia/AvaloniaBuildTasks.targets#L48) target is supposed to be re-run when resource is deleted, but I guess MSBuild doesn't handle file deletion that well.

**Comment by kekekeks** [comment]
Mkay, reproduced with much simpler project:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <Target Name="TestTarget" 
          BeforeTargets="CoreCompile;CoreResGen"
          Inputs="@(MyResource);$(MSBuildAllProjects)"
          Outputs="list.lst">
    <WriteLinestoFile 
        File="list.lst"
        Overwrite="True"
        Lines="@(MyResource)"
    />
   <Message Importance="high" Text="Files: @(MyResource)"/>
  </Target>
  <ItemGroup>
     <MyResource Include="*.txt"/>
     <UpToDateCheckInput Include="@(MyResource)" />
  </ItemGroup>
</Project>
```
When any of `*.txt` files gets removed `TestTarget` is NOT re-run.

From my point of view that's clearly a bug in MSBuild, but I might be missing something.

**Comment by MarchingCube** [comment]
Perhaps we should report it to https://github.com/dotnet/msbuild?

**Comment by MarchingCube** [comment]
Found one random SO answer claiming that missing inputs won't invalidate targets: https://stackoverflow.com/a/48483825

**Comment by kekekeks** [comment]
Apparently that's by design and we are supposed to do the following:

1) have a separate target that gathers the list of files and writes it to some file with `WriteOnlyWhenDifferent`
2) add said file as an input for our target

An example of doing that is here https://github.com/Szer/GiraffeGenerator/blob/f488a4a0c693cc954557960da19015169e7f8f76/src/GiraffeGenerator.Sdk/build/GiraffeGenerator.Sdk.targets#L34-L46

**Comment by kekekeks** [comment]
MSBuild is doing the same for `Compile` items: https://github.com/dotnet/msbuild/blob/f0eebf2872d76ab0cd43fdc4153ba636232b222f/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3529-L3548
