### ISSUE TITLE
Exception during PathIcon foreground set via style

### ISSUE THREAD

**Issue by soosr** [AvaloniaUI/Avalonia#4970]
This runs smoothly:
```<PathIcon Foreground="{StaticResource SystemAccentColor}">```

This cause exception:
```
<Style Selector="PathIcon">
  <Setter Property="Foreground" Value="{StaticResource SystemAccentColor}" />
</Style>
```

Exception:
> System.InvalidCastException: 'Unable to cast object of type 'Avalonia.Media.Color' to type 'Avalonia.Media.IBrush'.'

**Comment by maxkatz6** [comment]
Was fixed before https://github.com/AvaloniaUI/Avalonia/pull/6815
