### ISSUE TITLE
Flickering on macOS during resize

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#4978]
macOS Catalina (also Big Sur). example of control catalog during resize:

- window title bar is detached from time to time
- flickering at some moments making window background transparent

![macos_flickeringresize](https://user-images.githubusercontent.com/13854631/97709207-a0e0d980-1ac2-11eb-8590-056e6f8f7e12.gif)

**Comment by Deadpikle** [comment]
Flickering is reported in #4500. Not sure if the title bar thing has already been reported.

**Comment by donandren** [comment]
hm yea it's the same issue except the detaching title bar.The only workaround so far to fix completely the issue is to disable gpu on Mac like:
`builder.With(new AvaloniaNativePlatformOptions(){UseGpu=false})`

**Comment by danwalmsley** [comment]
Fixed

**Comment by donandren** [comment]
flickering is gone indeed, but window title bar is still detached from time to time while resizing
