### ISSUE TITLE
Someone Removes my XAML Files Included as EmbeddedResource 

### ISSUE THREAD

**Issue by worldbeater** [AvaloniaUI/Avalonia#4981]
If I add a reference to Avalonia 0.10.0-preview, then all my XAML files get erased from the assembly if I explicitly include them via `<EmbeddedResource>`. The issue could be described clearly by the following `.csproj` file and the comment:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <!-- These two lines should work identically the same, correct? 
             But no, these two lines don't work the same. Looks like someone
             removes the files ending with 'xaml'. If I remove a reference to
             Avalonia, the issue disappears. -->
        <EmbeddedResource Include="NamedControl.xaml" />
        <EmbeddedResource Include="NamedControl.xml" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="0.10.0-preview5" />
    </ItemGroup>
</Project>
``` 

So, the files ending with `xaml` for some unknown reason get stripped out from the assembly. Silently. The files ending with other extensions are left untouched and are kept as embedded resources. Worth noting that the [current docs](https://avaloniaui.net/docs/quickstart/assets#referencing-manifest-resources) say that it is possible to include stuff via `EmbeddedResource`s and don't indicate the limitation described in this issue. The code I execute to extract the resources is given by:

```cs
var assembly = typeof(Program).Assembly;
var names = assembly.GetManifestResourceNames();
if (!names.Any(name => name.EndsWith("NamedControl.xml")))
{
    throw new Exception("This never happens.");
}

if (!names.Any(name => name.EndsWith("NamedControl.xaml")))
{
    throw new Exception("I've been just trolled! 😃");
}
```

**Comment by kekekeks** [comment]
Compiler transforms XAML files to MSIL and indeed strips those as they aren't needed anymore. You can include an additional copy with a different extension.

**Comment by worldbeater** [comment]
Is there a way to somehow make this behavior optional? E.g. via an option in `PropertyGroup` like this one: `<PreserveXamlEmbeddedResources>True</PreserveXamlEmbeddedResources>` Or should we just update the documentation to clarify that one shouldn't attempt to include XAML files via `EmbeddedResource`?
