### ISSUE TITLE
Avalonia supports Irregular window？

### ISSUE THREAD

**Issue by 3400442579** [AvaloniaUI/Avalonia#4982]
Avalonia.Desktop 0.10.0-preview6

Code:
![image](https://user-images.githubusercontent.com/34226979/97767776-5bbbb680-1b59-11eb-84de-51b17144a59d.png)

`<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="Animation.Gui.Views.RegionView"
        Title="RegionView"  
        Background="{x:Null}"
        TransparencyLevelHint="Transparent"
        SystemDecorations="None"
        Width="400" Height="300"
        >
  
     <Grid ColumnDefinitions="Auto,*,Auto" RowDefinitions="Auto,*,Auto">

        <Rectangle  Grid.Row="1" Grid.Column="1" Name="SelectionRectangle"  Stroke="Red" StrokeThickness="5" StrokeDashArray="2,4"/>
   
     </Grid>
</Window>`

![image](https://user-images.githubusercontent.com/34226979/97767668-8fe2a780-1b58-11eb-976a-d2005e36444c.png)

**Transparent area is masked, unable to operate.**

**Comment by PieroCastillo** [comment]
what do you wanna do? drag or resize? if u wanna define a drag-zone for the window, just make a draggable zone, like this:
```xml
<Border Name="DragBorder"/>
```
```c#
public YourClass()
{
   var border1 = this.Find<Border>("DragBorder");
   border1.PointerPressed += (s, e)=>
  {
      this.BeginMoveDrag(e);
  };
}
```

**Comment by 3400442579** [comment]
![image](https://user-images.githubusercontent.com/34226979/97770170-f8874f80-1b6b-11eb-8bec-75ba7753eb67.png)

**Comment by 3400442579** [comment]
![image](https://user-images.githubusercontent.com/34226979/97770266-a5fa6300-1b6c-11eb-8399-13e986b70fbe.png)

**Comment by PieroCastillo** [comment]
oh, I think  you define a height, the following xaml code I use in my examples:
```xml
<Border Background="{DynamicResource ThemeBackgroundBrush}" Name="drag_b" 
				VerticalAlignment="Top" Height="20" Opacity="0"/>
```
and if I'm not wrong you should set the IsHistTestVisible Property in true

**Comment by PieroCastillo** [comment]
try to code based in this code [Line#292](https://github.com/PieroCastillo/Aura.UI/blob/70ac55ab36f194c31dd5df669042cb5acb744a70/Tests/UI.Tests/MainWindow.xaml#L292)

**Comment by 3400442579** [comment]
Like the ScreenToGif  recording window
![image](https://user-images.githubusercontent.com/34226979/97770715-b14f8d80-1b70-11eb-86e1-3036efd5d5a4.png)

**Comment by PieroCastillo** [comment]
Oh, that's beyond my knowledge, mmmm, but I think there should be any way to make what you wanna, you can contact with the main developers

**Comment by kekekeks** [comment]
Try using [SetWindowRgn](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowrgn) / [XShapeCombineRectangles](https://www.x.org/releases/current/doc/libXext/shapelib.html). Not sure about OSX.

**Comment by 3400442579** [comment]
**Not completely transparent！**
![image](https://user-images.githubusercontent.com/34226979/97798931-91e65c80-1c65-11eb-817c-e85e8b6ebc7d.png)


Code:
![image](https://user-images.githubusercontent.com/34226979/97798972-d2de7100-1c65-11eb-989c-c802e8ca0ab9.png)
