### ISSUE TITLE
Avalonia 0.10.0-preview6 X11 mouse pointer events modifiers value always None

### ISSUE THREAD

**Issue by yatli** [AvaloniaUI/Avalonia#4988]

**Comment by capdj** [comment]
I'm seeing this too on preview 6. The following code:

`
    private class TestWindow : Window {
            public override void Show() {
                base.Show();

                Panel p = new Panel();
                p.Background = Brushes.AliceBlue;
                p.PointerWheelChanged += P_PointerWheelChanged;
                p.PointerPressed += P_PointerPressed;
                DockPanel dock = new DockPanel();
                dock.Children.Add(p);
                Content = dock;
                Title = "Test App";
            }

            private void P_PointerPressed(object sender, Avalonia.Input.PointerPressedEventArgs e) {
                Console.WriteLine($"Pointer pressed: {e.KeyModifiers}, {e.GetCurrentPoint(null).Position}");
            }

            private void P_PointerWheelChanged(object sender, Avalonia.Input.PointerWheelEventArgs e) {
                Console.WriteLine($"Pointer pressed: {e.KeyModifiers}, {e.Delta}, {e.GetCurrentPoint(null).Position}");
            }
        }
`

...will print out modifier keys (Control, Shift, Alt...) on Windows when you click or mousewheel over the windows, but not under Linux - the modifiers are always None, as per description.
It did work as expected on earlier versions of Avalonia, so something's broken in the past few months...
