### ISSUE TITLE
Building Avalonia on a Mac is failing

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/Avalonia#4991]
I've updated my local repo to the latest (HEAD = 1cc569472)
I tried to build with this:
`$ ./build.sh --target Package --skip CompileHtmlPreviewer --configuration Debug`

This failed on the CompileNative target with this error:

> In file included from /Users/mj/Documents/develop/avalonia/Avalonia/native/Avalonia.Native/src/OSX/menu.mm:2:
> /Users/mj/Documents/develop/avalonia/Avalonia/native/Avalonia.Native/src/OSX/common.h:4:10: fatal error: 'avalonia-native.h' file not found
> #include "avalonia-native.h"

In searching for the possible cause, I came across issue #3899, which advises that CastXML must be installed, per the [build.md](https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md#install-castxml) file:
> https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md#install-castxml

However, attempting to install this specific version of CastXML no longer works with brew.  The following error results:

> Error: Calling Installation of castxml from a GitHub commit URL is disabled! Use 'brew extract castxml' to stable tap on GitHub instead.

So I tried just installing the latest CastXML (0.3.6).  The build ended with the same error.

I'm not certain if the CastXML/Brew issue is the cause of the the avalonia-native.h file not being found or not.  So this could be two issues.

Given the issue with HomeBrew, please update the build process to use the latest CastXML (or if this is already done, update the build.md file).

If this is not connected to the avalonia-native.h not being found, please advise how do I fix this?

**Comment by kekekeks** [comment]
This was recently changed, `castxml` is no longer required, however you need to run `./build.sh GenerateCppHeaders` to generate `avalonia-native.h`

**Comment by mrj001** [comment]
@kekekeks, thanks.  It built now.  I suggest that the build should be updated such that that target gets run automatically.
