### ISSUE TITLE
RunHtmlPreviewerTests fails when skipping CompileHtmlPreviewer

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/Avalonia#4992]
I build Avalonia with the following command:
`$ ./build.sh --target Package --skip CompileHtmlPreviewer --configuration Debug`

This printed the following summary at the end:

> ═══════════════════════════════════════════════════════
> Target                             Status      Duration
> ───────────────────────────────────────────────────────
> Clean                              Executed        0:00
> CompileNative                      Executed        0:56
> CompileHtmlPreviewer               Skipped         0:00
> Compile                            Executed       10:13
> RunLeakTests                       Skipped         0:00   // (Not(Parameters.SkipTests) && Parameters.IsRunningOnWindows)
> RunDesignerTests                   Skipped         0:00   // (Not(Parameters.SkipTests) && Parameters.IsRunningOnWindows)
> RunRenderTests                     Executed        0:18
> RunCoreLibsTests                   Executed        2:34
> RunHtmlPreviewerTests              Failed          0:00
> RunTests                           NotRun          0:00
> CreateIntermediateNugetPackages    NotRun          0:00
> CreateNugetPackages                NotRun          0:00
> Package                            NotRun          0:00
> ───────────────────────────────────────────────────────
> Total                                             14:03
> ═══════════════════════════════════════════════════════
> 
> Build failed on 2020-11-02 11:47:37 AM. (╯°□°）╯︵ ┻━┻

I believe that when one is skipping the CompileHtmlPreviewer that the corresponding tests should not be run.

As an aside, what are the odd characters on the last line after the date?

**Comment by mrj001** [comment]
The following command line does successfully build:
`$ ./build.sh --target Package --skip-previewer --configuration Debug`

Still, I suppose the '--skip CompileHtmlPreviewer' should work too.

**Comment by rstm-sf** [comment]
`RunHtmlPreviewerTests` is target like `CompileHtmlPreviewer` or `Complie` or `RunRenderTests`

If we use `TriggeredBy` and `.WhenSkipped(DependencyBehavior.Skip)`, then this test will run after creating nugets, which is not logical
https://github.com/AvaloniaUI/Avalonia/blob/cbe4c985b8549455dff37eb6fad97d3262c1023c/nukebuild/Build.cs#L370-L373

Therefore, it seems to me normal behavior that is now
