### ISSUE TITLE
Getting Erro: The "CimpileAvaloniaXamlTask" task failed unexpectedly.

### ISSUE THREAD

**Issue by jonathanBell1** [AvaloniaUI/Avalonia#4993]
I am getting the following compile error: MSB4018 The "CimpileAvaloniaXamlTask" task failed unexpectedly.  This has happened on 3 different projects.  The Projects are simple as I am just learning Avalonia.  All of them would compile several times as I added functionality then at random times I would get this error.  Once I get his error, even if I remove the latest change to get back to the code that compiled correctly before, I still get this error.

**Comment by kekekeks** [comment]
Try compiling with `dotnet build`, it should give you more output
