### ISSUE TITLE
Let's get 10k github stars

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#5001]
I thought I'd use issue 5000 to encourage people to star this great project more than 10k times.
But I was too slow :)

**Comment by wieslawsoltes** [comment]
I think I have stolen the issue 5000 from you, sorry. Anyway let's get those 10k stars!

**Comment by ahopper** [comment]
@wieslawsoltes you were just too quick for me:)

**Comment by PieroCastillo** [comment]
I'm so excited :D

**Comment by ahopper** [comment]
I wonder if we can get to 10k before that other vote is counted :)

**Comment by ahopper** [comment]
Well done Avalonia, 10K stars
