### ISSUE TITLE
Window size behavior

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#5005]
When setting the width and height, the final size is larger than the one set when the TitleBar is displayed.

Avalonia behavior

```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'
        x:Class="Sandbox.MainWindow"
        Width="1024" Height="800">
</Window>
```

![immagine](https://user-images.githubusercontent.com/12531229/98118028-d9115f00-1eaa-11eb-9832-86ff3fac24b3.png)

WPF behavior:
```xaml
<Window x:Class="WpfApp3.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp3"
        mc:Ignorable="d"
        Title="MainWindow" Height="800" Width="1024">
    <Grid>
        
    </Grid>
</Window>
```
![immagine](https://user-images.githubusercontent.com/12531229/98118822-12969a00-1eac-11eb-92b0-c9325441f64a.png)

**Comment by kekekeks** [comment]
I believe we are using client size here for consistency reasons. i. e. one would expect 100x100 Border to fit into 100x100 window. We should probably have separate properties for the full window size for platforms that support it.

**Comment by workgroupengineering** [comment]
I think that a new property is not needed to define the window size, the width and height are already there.
When a developer sets width and height, they would expect it to occupy that area on the Desktop, not as much as it does now if the toolbar is present.

**Comment by kekekeks** [comment]
Note that that behavior isn't really possible with X11, window location is always effective for the client area there.

**Comment by grokys** [comment]
I think the history of this feature was: initially `Width`/`Height` meant window size including decorations, and we had the separate `ClientSize` property for client size. When X11 was added we couldn't make `Width`/`Height` include decorations so rather than have the properties meaning different things on different platforms, we made both `Width`/`Height` and `ClientSize` the same.

**Comment by workgroupengineering** [comment]
Thanks @grokys  for the explanation, I had guessed the reasons a little while reading the X specifications.

I think a solution should be found, maybe I found a workaround for the X server.
But before working on it if you agree to restore the original behavior.

When a developer creates multi-window applications similar to GIMP it is important to know and set the real size.

**Comment by kekekeks** [comment]
Said workaround seems to be window manager specific and can't be used as a general solution

**Comment by workgroupengineering** [comment]
Why do you say it's not generic? Seeing the code use XQueryTree to go back to the root and sum the geometries from XGetGeometry, it doesn't seem tied to a window manager.

if the workaround fails, use the current behavior, otherwise the old one. To make the developer understand, we could add a read-only PrecisePostion or PreciseSize property.

**Comment by kekekeks** [comment]
>Why do you say it's not generic?

Window decorations don't have to be represented by a window, especially when running with XWayland.

**Comment by workgroupengineering** [comment]
> 
> 
> > Why do you say it's not generic?
> 
> Window decorations don't have to be represented by a window, especially when running with XWayland.

Grazie per la spiegazione

**Comment by workgroupengineering** [comment]
Thanks for the explanation, do you like the fallback idea?

**Comment by grokys** [comment]
> But before working on it if you agree to restore the original behavior.

I don't think this would be a good idea because it would mean that `Width`/`Height` mean different things on different platforms, which would cause problems.

I think if we want to expose the size including decorations we'd be best exposing a separate `PixelSize? DesktopSize { get; set; }`  property or similar. I say it should return `PixelSize` instead of `Size` because on Win32 at least desktop desktop coordinates use the physical pixel size instead of the scaled size if I remember correctly. Not sure about the other platforms.

**Comment by maxkatz6** [comment]
We now have window.FrameSize property that includes window decoration bounds. Readonly.
Width and Height are still defining client size, as per reasons above.
