### ISSUE TITLE
Remove NewLine in TextBox only by one backspace press, not two

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#501]
I suppose this happens due to NewLine represented as two chars `\r\n`.

**Comment by danwalmsley** [comment]
I have fixed this in my text editor, will see if code is compatible and submit a pr, remind me if I forget.

**Comment by KvanTTT** [comment]
Hi, @danwalmsley. Do you have any news related to this feature? )

**Comment by grokys** [comment]
Any news on this @danwalmsley ?

**Comment by danwalmsley** [comment]
Ah I looked at it, but the way it was implemented in my text editor depended on my document model, which would be overkill for textbox. Does textbox split the text into lines? Or could textbox check for newline chars when backspace or delete is pressed?
