### ISSUE TITLE
NumericUpDown has no :focus

### ISSUE THREAD

**Issue by Odepax** [AvaloniaUI/Avalonia#5016]
Hello, there!

It seems impossible to style the `NumericUpDown` control differently when it is focused by the user, i.e.

```xml
<Style Selector="NumericUpDown:focus">
   <!-- NumericUpDown is not amused. -->
   <Setter Property="Background" Value="Red"/>
</Style>
```

whereas

```xml
<Style Selector="TextBox:focus">
   <!-- TextBox becomes red on focus like a charm. -->
   <Setter Property="Background" Value="Red"/>
</Style>
```

Is there any workaround?

**Comment by jhofinger** [comment]
May be a bit late for you, but you can access the underlying text box like so:
`<Style Selector="NumericUpDown /template/ TextBox#PART_TextBox:focus">`

**Comment by jhofinger** [comment]
Also, in general, focus-related Events are broken for NumericUpDowns (like LostFocus). Workaround: access the underlying textbox and create an attached property that subscribes to the event you want to

**Comment by grokys** [comment]
This was blocked on not having the `IsKeyboardFocusWithin` property: https://github.com/AvaloniaUI/Avalonia/pull/2808

However that was implemented in https://github.com/AvaloniaUI/Avalonia/pull/2808 so it should not be possible using the `:focus-within` pseudoclass.
