### ISSUE TITLE
InvokeAsync causes program to hang in WPF-based use case

### ISSUE THREAD

**Issue by audinowho** [AvaloniaUI/Avalonia#5018]
I'm using Dispatcher.InvokeAsync to run continuous tasks on the main thread, while giving UI the chance to respond to events. WPF has this as intended behavior: https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/threading-model?view=netframeworkdesktop-4.8

In practice, I'm seeing the opposite of the WPF behavior in Avalonia, and the UI freezes instead.

A simple example, added to the axaml.cs for a single button's Click event:
```
public void Button_Click(object sender, RoutedEventArgs e)
{
	Dispatcher.UIThread.InvokeAsync(TestMethod, DispatcherPriority.SystemIdle);
}

public void TestMethod()
{
	Console.WriteLine("Tick");
	Dispatcher.UIThread.InvokeAsync(TestMethod, DispatcherPriority.SystemIdle);
}
```
Full example in my repo: https://github.com/audinowho/WPFAvaloniaTest/tree/master/AvaloniaTest

Scheduled TestMethods appear to be dequeued immediately after, instead of giving control back to UI to update once before rechecking queue.  Not sure if intended.

**Comment by maxkatz6** [comment]
> I'm using Dispatcher.InvokeAsync to run continuous tasks on the main thread, while giving UI the chance to respond to event

I believe await Task.Yield() usually used for that.
Although I think InvokeAsync approach should also work at least for specific priorities like SystemIdle.

**Comment by kekekeks** [comment]
Should be fixed by the recent dispatcher rework
