### ISSUE TITLE
Dark background in Expander Header in expanded state

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#502]
![Dark background in Expander Header in Expanded state](https://files.gitter.im/Perspex/Perspex/LkI5/thumb/blob.png)
This bug can be reproduced in Perspex ControlCatalog sample app.

**Comment by grokys** [comment]
Could you explain the issue?

**Comment by KvanTTT** [comment]
So, I duplicate here new suggested style (from gitter):
![Expanders](https://files.gitter.im/Perspex/Perspex/znT3/thumb/Expanders.png)
