### ISSUE TITLE
ScrollViewer.HorizontalScrollBarVisibility should be Disabled by default

### ISSUE THREAD

**Issue by FG-rgb** [AvaloniaUI/Avalonia#5020]
AvaloniaUI v0.9.11 or v0.10.0-preview6.
OS: Window 10.

When using a TextBlock with TextWrapping set to Wrap inside a Scrollviewer, the text is not wrapped on overflow.
Steps to reproduce:
Create new empty avalonia project.
Edit MainWindow and add following code as content:
```
<ScrollViewer>
    <TextBlock TextWrapping="Wrap"
      Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at est semper urna vulputate tincidunt sit amet at mauris. Quisque a porta tortor. Duis dapibus ex id pulvinar porttitor. Aliquam mattis nunc erat, quis iaculis risus lobortis et. Fusce pulvinar, nunc id suscipit sodales, lectus enim commodo justo, fermentum tincidunt dolor enim sit amet felis. Morbi a magna libero. Vivamus condimentum justo ligula. In convallis gravida urna, ac convallis nisl porttitor vitae. " />
  </ScrollViewer>
```

Run project.

**Comment by maxkatz6** [comment]
Set HorizontalScrollMode to Disabled on your ScrollViewer.

**Comment by FG-rgb** [comment]
Ok that helps. But that means ScrollViewer HorizontalScrollBarVisibility is set to Hidden by default, because in my mentioned example the text is cut of without scrollbars. The HorizontalScrollBarVisibility should have a better default value.

**Comment by grokys** [comment]
Yeah I think this should be `Disabled` by default, not `Hidden`
