### ISSUE TITLE
How do we handle process uniqueness across platforms

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#5029]
Hi：
Does any one knows that How to deal with processes uniquely  cross-platform.
Now, my back end is. Netcore3.1. The front end is AvaloniaUI. What I want to do is when I click on the application for the first time, when I run it, when I click on the application for the second time, when I click on the application for the third time, the application will not be triggered to run again. This is the only case in which a process is not allowed to run the same application multiple times. I used the following statement, but under Linux, MacOS, it has no effect. Do you know anything about it?

![image](https://user-images.githubusercontent.com/7692353/98884855-e5f60a00-24cb-11eb-9546-e255aad5759e.png)

**Comment by kekekeks** [comment]
UNIX systems do not have a concept of a named mutex. .NET Core tries to emulate those, but I won't recommend relying on that and instead use file locks directly.

MacOS does application instance checks automatically, just package the application into an `.app` bundle and you are good to go

**Comment by wuzlai** [comment]
> UNIX systems do not have a concept of a named mutex. .NET Core tries to emulate those, but I won't recommend relying on that and instead use file locks directly.
> 
> MacOS does application instance checks automatically, just package the application into an `.app` bundle and you are good to go

Thank you very much for your reply. According to your idea, in the macOS environment, we don't have to consider the process by ourselves, which sounds very good. For WIndows, Linux and other systems, I seldom use file locks. My understanding is exclusive locks similar to Java. I searched on the Internet, but I got less information. Can I ask you, if I'm going to use a file lock on a.netcore platform, what kind of data should I look at or how to think about it? Or do you recommend an open source project that USES this solution? Can facilitate me to understand the study. thank you

**Comment by kekekeks** [comment]
```cs
static FileStream _lockFile;
```

```cs
var dir = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),  "YourCompany", "YourApp");
Directory.Create(dir);
try
{
    _lockFile = File.Open(Path.Combine(dir, ".lock"), FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None);
    _lockFile.Lock(0,0);
    return true;
}
catch
{
    return false;
}
```

**Comment by wuzlai** [comment]
> ```cs
> Environment.GetFolderPath
> ```

Thank you very much. I understand the process.

**Comment by wuzlai** [comment]
> ```cs
> static FileStream _lockFile;
> ```
> 
> ```cs
> var dir = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),  "YourCompany", "YourApp");
> Directory.Create(dir);
> try
> {
>     _lockFile = File.Open(Path.Combine(dir, ".lock"), FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None);
>     _lockFile.Lock(0,0);
>     return true;
> }
> catch
> {
>     return false;
> }
> ```

Thank you very much. I understand the process.

**Comment by maxkatz6** [comment]
I am going to close this issue, because it's unrelated to Avalonia and seems to be solved.
@wuzlai feel free to reopen, if you will need.
