### ISSUE TITLE
Rounded border: corner radius cuts border outline off

### ISSUE THREAD

**Issue by ThePBone** [AvaloniaUI/Avalonia#5041]
Hey, I'm trying to create a borderless window with custom decoration. I decided to use a rounded border for this, for example:

```
<Border CornerRadius="20"
        BorderBrush="Gray"
        BorderThickness="2"
        ClipToBounds="True">
	<!-- Content -->
</Border>      
```

Unfortunately, the corner radius cuts the gray border outline off: 
![image](https://user-images.githubusercontent.com/38386967/99132472-a0922380-2616-11eb-87b6-e531ac206c0b.png)

![image](https://user-images.githubusercontent.com/38386967/99134217-19947980-261d-11eb-9a2d-720a0c24220a.png)

Is it possible to outline along the actual (rounded) boundary if a corner radius is set?
Also, I noticed that the border edges look really pixelated. Is there a way to enable anti-aliasing for elements with the `CornerRadius` property in the rendering engine?

Some general system information:
<table>
<tr>
	<td>Version
	<td>0.10.0-preview6
<tr>
	<td>Host
	<td>Arch Linux 5.8.12-arch1-1 (X11)
<tr>
	<td>NET Core SDK
	<td>3.1.108
</table>

**Comment by Gillibald** [comment]
Uniform borders are rendered by Skia

**Comment by ThePBone** [comment]
Tested with a non-uniform border but the issue persists: 
![image](https://user-images.githubusercontent.com/38386967/99145539-1d9db700-2670-11eb-81cc-39a4e5771df9.png)

```
<Border CornerRadius="20,0,0,0"
            BorderBrush="Black"
            BorderThickness="2"
            ClipToBounds="True">
```

**Comment by Gillibald** [comment]
Looks like the stream geometry is still not used https://github.com/AvaloniaUI/Avalonia/blob/d241fa9516dfff7f1a48e6dcf6e2db75f9a77321/src/Avalonia.Controls/Utils/BorderRenderHelper.cs#L28

**Comment by Gillibald** [comment]
The different code path can still be triggered by defining a non uniform border thickness

**Comment by ThePBone** [comment]
It doesn't seem to behave any different:
![image](https://user-images.githubusercontent.com/38386967/99146097-2ba20680-2675-11eb-9887-67c267c98cb7.png)

```
<Border CornerRadius="25,0,0,0"
        BorderBrush="Black"
        BorderThickness="2,4,2,4"
        ClipToBounds="True">
```

I added a breakpoint to the if-statement in `BorderRenderHelper.Update` and it properly sets `_useComplexRendering` to true.

**Comment by ThePBone** [comment]
I did some more testing and I noticed that removing all content from the border solves this:

![image](https://user-images.githubusercontent.com/38386967/99146638-52af0700-267a-11eb-8be2-b5d0b85f0115.png)

**Comment by ThePBone** [comment]
Solved it by applying a small padding to the border element content to avoid overlaps with the rounded window border. Here's my solution if anyone else runs into this issue:
```xml
<Border CornerRadius="20"
        BorderBrush="Black"
        BorderThickness="2"
        ClipToBounds="True" Padding="1"
        Background="{DynamicResource SystemControlBackgroundAltHighBrush}">
    
    <DockPanel HorizontalAlignment="Stretch"
               VerticalAlignment="Stretch"
               Name="ContentWrapper"
               Margin="2,0">
        
        <ui:CustomTitleBar Background="Transparent"></ui:CustomTitleBar>
        
        <DockPanel Background="{DynamicResource SystemControlBackgroundAltHighBrush}">
            <!-- Content -->
        </DockPanel>
        
    </DockPanel>
</Border>
```

![image](https://user-images.githubusercontent.com/38386967/99146888-8e4ad080-267c-11eb-8d30-9abed91a5bf7.png)

**Comment by sekkit** [comment]
> Solved it by applying a small padding to the border element content to avoid overlaps with the rounded window border. Here's my solution if anyone else runs into this issue:
> 
> ```
> <Border CornerRadius="20"
>         BorderBrush="Black"
>         BorderThickness="2"
>         ClipToBounds="True" Padding="1"
>         Background="{DynamicResource SystemControlBackgroundAltHighBrush}">
>     
>     <DockPanel HorizontalAlignment="Stretch"
>                VerticalAlignment="Stretch"
>                Name="ContentWrapper"
>                Margin="2,0">
>         
>         <ui:CustomTitleBar Background="Transparent"></ui:CustomTitleBar>
>         
>         <DockPanel Background="{DynamicResource SystemControlBackgroundAltHighBrush}">
>             
>         </DockPanel>
>         
>     </DockPanel>
> </Border>
> ```
> 
> ![image](https://user-images.githubusercontent.com/38386967/99146888-8e4ad080-267c-11eb-8d30-9abed91a5bf7.png)

Could u plz share this whole xaml to me? tried for several times but still not working

**Comment by ThePBone** [comment]
> Could u plz share this whole xaml to me? tried for several times but still not working

Sure, you need to check [MainWindow.xaml](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient/MainWindow.xaml). The project I implemented this in is fully available on GitHub.
If you are looking for the `ui:CustomTitleBar`, check this out instead: [CustomTitleBar.xaml](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient/Interface/CustomTitleBar.xaml)

**Comment by Sabuto** [comment]
hey all, so i am trying to get this to work i have had a look at the code in https://github.com/AvaloniaUI/Avalonia/issues/5041#issuecomment-825926244 and copied it over but i can't seem to get rid of the starp corners any ideas?[](url) https://ibb.co/ypq94nL

**Comment by maxkatz6** [comment]
See https://github.com/AvaloniaUI/Avalonia/discussions/6857#discussioncomment-1585156

**Comment by Sabuto** [comment]
Thanks for this i assume you are specifically talking about `Win32PlatformOptions.CompositionBackdropCornerRadius` but how do i implement this? i've never used this class before

**Comment by Sabuto** [comment]
> 
> 
> See [#6857 (comment)](https://github.com/AvaloniaUI/Avalonia/discussions/6857#discussioncomment-1585156)

so i read about a bit and it says to do it in the App Builder like `.With(new Win32PlatformOptions { CompositionBackdropCornerRadius = 30})` if that is right it is still not working, is there anything else i need to add?
