### ISSUE TITLE
Segfault when calling System.Drawing.Graphics.DrawString

### ISSUE THREAD

**Issue by icecoldone** [AvaloniaUI/Avalonia#5044]
Hello there,

I just found a strange issue, where calling the DrawString method on a Graphics instance within an Avalonia application leads to a crash without any error messages. Using the templates on https://github.com/AvaloniaUI/avalonia-dotnet-templates I created a basic app, which shows the default window just fine. Then I added the following code to the constructor of the MainWindow:

```
        public MainWindow()
        {
            InitializeComponent();

            Bitmap image = new Bitmap(800,600);
            Graphics gfx = Graphics.FromImage(image);
            gfx.FillRectangle(new SolidBrush(Color.Blue), 0, 0, 800, 600);

            Font font = new Font("Nimbus Sans", 16);
            System.Console.WriteLine(font);
            gfx.DrawString("test", font, new SolidBrush(Color.Black), 50, 50);
            image.Save("test.png");
        }
```

Unfortunately, the application crashes on the DrawString method call. Commenting this line out, the file test.png is created just fine, containing only blue as expected.

The exact code snippet is working in a console application without using Avalonia, resulting in an image containing the text!

Does anyone have an idea or suggestion about how to identify the problem?

I am running the .NET Core SDK binaries from Microsoft (version 3.1.404) on Manjaro Linux.

This is the output of ```dotnet --info```:
```
.NET Core SDK:
 Version:   3.1.404
 Commit:    470f6754b3

Laufzeitumgebung:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/username/dotnet/sdk/3.1.404/

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  3.1.404 [/home/username/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/home/username/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/home/username/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by icecoldone** [comment]
If helpful, this is my project file:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.12" />
    <PackageReference Include="Avalonia.Desktop" Version="0.9.12" />
  </ItemGroup>
</Project>
```

**Comment by kekekeks** [comment]
```
<ItemGroup>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="1.68.3" />
    <PackageReference Include="Avalonia.Skia.Linux.Natives" Version="1.68.0.2" ExcludeAssets="all" />
    <PackageReference Include="SkiaSharp" Version="1.68.3" />
</ItemGroup>
```

See https://github.com/AvaloniaUI/Avalonia/issues/4325#issuecomment-660652331 for more details

**Comment by kekekeks** [comment]
@danwalmsley should we ship an update to 0.9 that uses `SkiaSharp.NativeAssets.Linux` for i386 and x86_84? We can't reference it by default because it would break ARM support.

**Comment by icecoldone** [comment]
That worked perfectly, thank you very much!
