### ISSUE TITLE
Targeting .NET 5 breaks designer

### ISSUE THREAD

**Issue by frederik-hoeft** [AvaloniaUI/Avalonia#5045]
After upgrading our Avalonia MVVM project from .NET Core 3.1 to .NET 5 (version 5.0.100) it seems the Avalonia designer is broken. Giving the  following error message:

![image](https://user-images.githubusercontent.com/43813142/99148516-5b0e3e80-2688-11eb-8fb5-85426aeb3c15.png)

This happens consistently. Just create a new Avalonia MVVM project and set the Target framework to .NET 5.
Interestingly enough compiling and executing the application works just fine.

I'm wondering if there are any known fixes to this (the output path of the binaries changes too after all from `\bin\...\netcoreapp3.1\...` to `net5.0`) so it might just be a config thing? Or is this just due to the current version of the designer being incompatible with this new .NET version.

**Comment by rstm-sf** [comment]
Duplicate of https://github.com/AvaloniaUI/AvaloniaVS/issues/176

You can use [this installer](https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=11867&view=artifacts&type=publishedArtifacts) for now

**Comment by frederik-hoeft** [comment]
Alright the new vsix fixed it. Thanks mate
