### ISSUE TITLE
Is it possible bind to attached property?[QUESTION]

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#5047]
hi, I want to bind a text to an attached property, is this:
```
<TextBox Text="{Binding #mycontrol.Canvas.Top}"/>
```

That does not compile, so I wanna know if there is someway to do it, thanks.

**Comment by maxkatz6** [comment]
Try this
```<TextBox Text="{Binding #mycontrol.(Canvas.Top)}"/>```

**Comment by PieroCastillo** [comment]
Thanks u, that's work correctly!
