### ISSUE TITLE
Vscode extension

### ISSUE THREAD

**Issue by breadnone** [AvaloniaUI/Avalonia#5050]
I know this beats the purpose of Avalonia ide. Me and some of us would pretty much appreciate with just a code completion for vscode.

**Comment by rstm-sf** [comment]
Look at the [PimpMyAvalonia](https://marketplace.visualstudio.com/items?itemName=PrzemyslawOnak.pimp-my-avalonia) extension

**Comment by kekekeks** [comment]
The latest previewer engine can render via HTML+WebSocket (e. g. Rider hosts previewer in a webview). Completion engine is a simple library that can be used by the language server.

What's currently missing for VSCode support is the letter I from the IDE acronym.

**Comment by rstm-sf** [comment]
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/999

**Comment by maxkatz6** [comment]
Closing as a duplicate
