### ISSUE TITLE
Cmd Window when running project

### ISSUE THREAD

**Issue by jsedanoj** [AvaloniaUI/Avalonia#5059]
Hello,

  I have created the simplest Avalonia application with avalonia.mvvm template. It compiles and runs. But I have found a strange behaviour: when I double-click the .exe, an extra Cmd window is spawn (see screenshot). Any idea why and how to remove it?

![image](https://user-images.githubusercontent.com/12848713/99272691-60a28a80-2828-11eb-8682-33b2566bceea.png)

**Comment by pr8x** [comment]
You mean the console? You can disable that. See https://github.com/AvaloniaUI/Avalonia/issues/1705

**Comment by kekekeks** [comment]
`<OutputType>WinExe</OutputType>`

**Comment by jsedanoj** [comment]
> `<OutputType>WinExe</OutputType>`

I don't understand. Do you mean that I need to set it to WinExe? Or that WinExe is wrong? It is WinExe right now (as created by avalonia.mvvm template).

**Comment by jsedanoj** [comment]
> You mean the console? You can disable that. See #1705

Thanks, it shows many potential solutions... but I can't see what is the accepted one.

One of them links to https://github.com/AvaloniaUI/Avalonia/wiki/Hide-console-window-for-self-contained-.NET-Core-application , but it just says to set WinExe OutputType... which I already have. It also says to compile Release, which I already am.

Any further idea?

My .csproj (directly created by `dotnet new avalonia.mvvm`):

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.12" />
    <PackageReference Include="Avalonia.Desktop" Version="0.9.12" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.9.12" />
  </ItemGroup>
</Project>
```

And my build process:

```
dotnet publish -c Release -o published --runtime win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:DebugType=None -p:DebugSymbols=false /p:Version=0.0.0-dev;
```

**Comment by danwalmsley** [comment]
@jsedanoj 
use netcoreapp3.1,
use Avalonia 0.10.0-preview6

should no longer have a console.

**Comment by jsedanoj** [comment]
> @jsedanoj
> use netcoreapp3.1,
> use Avalonia 0.10.0-preview6
> 
> should no longer have a console.

Sorry, still the same. Actually, it is worse now, because upon compiling it ways that `Program.cs(4,24): error CS0234: The type or namespace name 'Serilog' does not exist in the namespace 'Avalonia.Logging' (are you missing an assembly reference?)` (commented out .LogToDebug() for the test).

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.10.0-preview6" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.0-preview6" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.10.0-preview6" />
  </ItemGroup>
</Project>
```

**Comment by rstm-sf** [comment]
Serilog has been [removed](https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#logging)

**Comment by jsedanoj** [comment]
> Serilog has been [removed](https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#logging)

I was not sure, but I knew there was some discussion about it, that's why I just commented out the code. I suppose the avalonia.mvvm template will be updated when 0.10.x leaves preview.

**Comment by jsedanoj** [comment]
Ok, more info: as I said, I am crosscompiling from linux docker (1) and it seems to be the cause of the problem. I have tried building directly in Windows and the cmd window no longer applies.

However, the CI will run on gitlab-ci, so crosscompiling from linux docker is a must... any further idea on how to solve it?

**Comment by FrankenApps** [comment]
I guess you can do something like that: `.\editbin.exe /subsystem:windows myprogram.exe` with editbin, which is included in VisualStudio. I am however aware, that you would need to do that on Linux. I guess you could use Wine or something to run `editbin.exe` or you can just test on Windows and then see for yourself what you have to change in the executable, in order to run it without the console window.

**Comment by jsedanoj** [comment]
> I guess you can do something like that: `.\editbin.exe /subsystem:windows myprogram.exe` with editbin, which is included in VisualStudio. I am however aware, that you would need to do that on Linux. I guess you could use Wine or something to run `editbin.exe` or you can just test on Windows and then see for yourself what you have to change in the executable, in order to run it without the console window.

It works.

I will think on how to run it on CI.

**Comment by ahopper** [comment]
It may be worth opening an issue on netcore for this if the builds are different cross platform.

**Comment by jsedanoj** [comment]
> It may be worth opening an issue on netcore for this if the builds are different cross platform.

I think they know. I understand it is related to this and they are not fixing it right now: https://github.com/dotnet/sdk/issues/9963#issuecomment-454454973

What to you think?

**Comment by kekekeks** [comment]
>However, the CI will run on gitlab-ci, so crosscompiling from linux docker is a must... any further idea on how to solve it?

https://github.com/jmacato/NSubsys

**Comment by jsedanoj** [comment]
> > However, the CI will run on gitlab-ci, so crosscompiling from linux docker is a must... any further idea on how to solve it?
> 
> https://github.com/jmacato/NSubsys

Have you (or anybody) tested it _crosscompiling from linux_?

For me, after adding NSubsys builds correctly, but the Cmd still shows up. Can anybody confirm whether it works crosscompiling?

**Comment by jsedanoj** [comment]
> > I guess you can do something like that: `.\editbin.exe /subsystem:windows myprogram.exe` with editbin, which is included in VisualStudio. I am however aware, that you would need to do that on Linux. I guess you could use Wine or something to run `editbin.exe` or you can just test on Windows and then see for yourself what you have to change in the executable, in order to run it without the console window.
> 
> It works.
> 
> I will think on how to run it on CI.

Well, building on Windows on GitlabCI is possible now (beta): https://docs.gitlab.com/ee/user/gitlab_com/index.html#windows-shared-runners-beta
