### ISSUE TITLE
The design preview shows only a white dot?

### ISSUE THREAD

**Issue by unofficialdev** [AvaloniaUI/Avalonia#5068]
![Image 1](https://user-images.githubusercontent.com/43975116/99476165-9f4c5800-2982-11eb-96b2-e525c6ee363c.png)

Error on the photo I'm having and don't know how to fix it, I've spent all day looking for options, but without any options. Is there any solution for me? thank you very much

**Comment by maxkatz6** [comment]
Check "Avalonia Diagnostics" in the Output view. There might be some information. In the VS Options (Avalonia XAML Editor) you can also change verbosity.
