### ISSUE TITLE
Crash on Big Sur

### ISSUE THREAD

**Issue by NicolasDorier** [AvaloniaUI/Avalonia#5072]
A user reported a problem on Big Sur.

https://github.com/btcpayserver/BTCPayServer.Vault/issues/24 (the crash dump is there)

We are on avalonia 0.9.2 so I will try to update and see how it goes.

**Comment by jmacato** [comment]
@danwalmsley i think the same happened with avalonia master too right?

**Comment by NicolasDorier** [comment]
if so, you should be able to repro by running the btcpayserver vault.

**Comment by donandren** [comment]
from my experience with macOS bigsur, apps with 0.9 avalonia are crashing at start, but working fine with 0.10+

**Comment by danwalmsley** [comment]
Every release Apple break us... there hasnt been a single release they didnt!

**Comment by danwalmsley** [comment]
@NicolasDorier you should update to `0.9.12` which has a lot more stability fixes from `0.9.2`. probably it wont solve this one but a good idea.

**Comment by danwalmsley** [comment]
@NicolasDorier I guess we will release a 0.9.13 service release to fix this shortly.

**Comment by NicolasDorier** [comment]
@danwalmsley thanks you will update to 0.9.13 then.

**Comment by NicolasDorier** [comment]
@danwalmsley any eta for the release?

**Comment by NicolasDorier** [comment]
I will close this, I tried to update to latest avalonia, and it seems to work.

https://github.com/btcpayserver/BTCPayServer.Vault/issues/24#issuecomment-735597361
