### ISSUE TITLE
Unpredictable choice between method overloads when binding to command

### ISSUE THREAD

**Issue by mr146** [AvaloniaUI/Avalonia#5076]
#### Example
XAML part:
```
...
<Button Command="{Binding MyHandler}" />
...
```
Code-behind:
```
...
// [1]
public void MyHandler(string x) {}
// [2]
public void MyHandler() {}
...
```
Expected behavior: [2] is executed
Actual behavior: [1] is executed

If we will swap methods [1] and [2], then [2] will be executed.

Also, the problem appears when `CommandParameter` is specified: the expected behavior is that [1] will be executed always, but actually, it depends on the order of methods.

Bonus: `CommandParameter="zzz"` leads to app termination after button click when the chosen overload receives `int` parameter.

**Comment by grokys** [comment]
My feeling here is that handlers should be one of the following signatures:

```
void Handler();
```

Or

```
void Handler(object? o);
```

The second form with an `object` parameter should be chosen over the first form if present.

Reasoning: `CommandParameter` is an `object` and we don't want to be deciding which overload should be called at runtime: the handler should be decided at runtime. If the user wants to do dynamic dispatch then they would implement `void Handler(object? o)` and dispatch themselves.
