### ISSUE TITLE
Setting Button Foreground sometimes doesen`t work with 

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/Avalonia#5078]
I have ⚙️a symbol, and I need to color it in Cyan. In WPF everything I need to do is
`<Button Foreground="Cyan" Content="⚙️"></Button>`
But for Avalonia, I cant color it anyway. Mb I missed something?

**Comment by maxkatz6** [comment]
What have you tried?

**Comment by Gillibald** [comment]
I have updated the text

**Comment by Takoooooo** [comment]
> What have you tried?

For 0.9.12 Avalonia doesn't recognize ⚙️ symbol at all. For the last preview, it does, but I can't color it anyway. Here what I tried:
`
<Button
     Foreground="Cyan"
     Content="⚙️"/>
`

also
`
<Button
     TextBlock.Foreground="Cyan"
     Content="⚙️"/>
`
and even copying the full style of the Button from source and hardcoding all Foreground properties to Cyan.
And also textblock cant color it too
 ` <TextBlock
    Foreground="Cyan"
     Text="⚙️"/>`

**Comment by Gillibald** [comment]
Color Emoji in general have fixed colors. There are some Emoji's that support different color tones but `gear` isn't one of them.

**Comment by Gillibald** [comment]
The only way to achieve what you want is to use the SVG data of that symbol and recolorize it on your own.

**Comment by Takoooooo** [comment]
> Color Emoji in general have fixed colors. There are some Emoji's that support different color tones but `gear` isn't one of them.

So it is designed in this way and you don't want to support it?

**Comment by maxkatz6** [comment]
@Takoooooo I would say that WPF has poor support for emojis.
@Gillibald is it possible to make emojis monochrome, optionally?

**Comment by Gillibald** [comment]
It is possible to have monochrome Emoji by using a font that has no color glyphs. Just specify the font explicitly. Monochrome Emoji work with the foreground brush.

**Comment by vpenades** [comment]
having the same problem, I've found a simple solution I want to leave here for future reference:

Setting the FontWeight to SemiBold does the trick

```xml
<TextBlock FontWeight ="SemiBold" Text="👤" />
```
