### ISSUE TITLE
Adding TextDecorations to TextBlock cause NRE

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/Avalonia#5080]
I have very simple code
` <TextBlock Text="text">
            <TextBlock.TextDecorations>
                <TextDecoration Location="Underline" />
            </TextBlock.TextDecorations>
        </TextBlock>`
(I know I can do it just by setting a property on TextBlock but I wanted to change the way TextDecoration looks like but every time I got NRE). For WPF it works good, but for Avalonia, it doesn't

**Comment by Gillibald** [comment]
This works in the ControlCatalog. Are you using the latest preview or a CI build? Any stacktrace to share?

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/TextBlockPage.xaml#L58

You probably have to use a TextDecorationCollection explicitly. The XAML compiler isn't constructing one for you.

**Comment by Takoooooo** [comment]
> https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/TextBlockPage.xaml#L58
> 
> You probably have to use a TextDecorationCollection explicitly. The XAML compiler isn't constructing one for you.

I am using the latest preview(6). The suggested workaround works for me, but behavior should be changed. By Constructing TextDecorationCollection every time or by throwing compile-time error.

**Comment by Takoooooo** [comment]
StackTrace
   at MainWindow.!XamlIlPopulate(IServiceProvider , MainWindow )
(thats all)
