### ISSUE TITLE
DataGrid AutoSizingColumns is internal

### ISSUE THREAD

**Issue by Deinonychus71** [AvaloniaUI/Avalonia#5083]
Hello,

Getting the following issue when trying to auto sort columns (AutoSizingColumns="True" on a DataGrid):

`Attempt by method 'xxxxxxxxxxxx.!XamlIlPopulate(System.IServiceProvider, xxxxxxxxxxxListView)' to access method 'Avalonia.Controls.DataGrid.set_AutoSizingColumns(Boolean)' failed.'`

Thanks

**Comment by maxkatz6** [comment]
What Avalonia version and theme (Default or Fluent) are you using?

**Comment by Deinonychus71** [comment]
I've tried with both 0.10.0-preview6 and 0.9.12
I believe I'm using the default theme: 
`avares://Avalonia.Controls.DataGrid/Themes/Default.xaml`

Thanks!

**Comment by maxkatz6** [comment]
AutoSizingColumns property is defined for internal operations in DataGrid, and user shouldn't use them. This property also doesn't exist in WPF/UWP DataGrid. But you can use Width with star sizing to achieve flexible sizes. Example from ControlCatalog:
```
<DataGrid.Columns>
  <DataGridTextColumn Header="Country" Binding="{Binding Name}" Width="6*" />
  <DataGridTextColumn Header="Region" Binding="{Binding Region}" Width="4*" />
  <DataGridTextColumn Header="Population" Binding="{Binding Population}" Width="3*" />
  <DataGridTextColumn Header="Area" Binding="{Binding Area}" Width="3*" />
  <DataGridTextColumn Header="GDP" Binding="{Binding GDP}" Width="3*" />
</DataGrid.Columns>
```

Another problem that user shouldn't see and be able to use AutoSizingColumns from text editor. I think it's related to another issue:
https://github.com/AvaloniaUI/AvaloniaVS/issues/130

I am closing this issue now, but if you have any related questions - feel free to ask or reopen.

**Comment by rstm-sf** [comment]
Hello! With avalonia 0.10 this works for me
![image](https://user-images.githubusercontent.com/2669927/107563312-f6647080-6bf1-11eb-83f9-bd73f90e8d85.png)
