### ISSUE TITLE
[QUESTION] Is there support for Lottie?

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#5084]
Hi, now i wanted to port ProgressRing from WinUI, but I found a problem, this uses an ```AnimatedVisualPlayer``` control, and this uses Lottie to work, my question is, is it possible port lottie to Avalonia? 'cause I found Skia supports Lottie: [Skottie](https://skia.org/user/modules/skottie), and I  assume that would be an evolution for Avalonia

**Comment by maxkatz6** [comment]
I believe it is blocked by SkiaSharp
https://github.com/mono/SkiaSharp/issues/661

**Comment by maxkatz6** [comment]
Also https://github.com/AvaloniaUI/Avalonia/issues/1908

**Comment by PieroCastillo** [comment]
> I believe it is blocked by SkiaSharp
> [mono/SkiaSharp#661](https://github.com/mono/SkiaSharp/issues/661)

I found this project, [LottieSkiaSharp](https://github.com/yinyue200/LottieSkiaSharp), I think that needs some refactoring, and  til wherel I can check, it's crossplatform, https://github.com/yinyue200/LottieSkiaSharp/blob/master/LottieSkiaSharp/LottieSkiaSharp.csproj, in my opinion if that is included in avalonia, it should have a AppBuilder Extension, like ```UseLottie()``` to define that application renders by Skia only

**Comment by PieroCastillo** [comment]
I found this fork, it's more updated, [emmauss/LottieSkiaSharp](https://github.com/emmauss/LottieSkiaSharp)

**Comment by kekekeks** [comment]
Also see  [direct skia context access example](https://github.com/AvaloniaUI/Avalonia/blob/3fe376ab2cb7f4e35b41d8ab10f00c5eaa83cc7f/samples/RenderDemo/Pages/CustomSkiaPage.cs). Note that  ICustomDrawOperation is being called on the render thread, so you need to ensure thread safety in your code

**Comment by danwalmsley** [comment]
Surely we can have an implementation that doesnt rely on Skia and keeps us renderer independent?

**Comment by Gillibald** [comment]
I would wait until NComposition is a thing

**Comment by PieroCastillo** [comment]
> Also see [direct skia context access example](https://github.com/AvaloniaUI/Avalonia/blob/3fe376ab2cb7f4e35b41d8ab10f00c5eaa83cc7f/samples/RenderDemo/Pages/CustomSkiaPage.cs). Note that ICustomDrawOperation is being called on the render thread, so you need to ensure thread safety in your code

nice, I think that can help
