### ISSUE TITLE
[QUESTION] How to run on iOS

### ISSUE THREAD

**Issue by FloVanGH** [AvaloniaUI/Avalonia#5085]
Hi,

I found the iOS example and I created also a custom one. Is there a guide how to run a Avalonia app on the iOS Simulator or device?

**Comment by danwalmsley** [comment]
@FloVanGH ios support is not yet official as its still in development and there are no guides. 

https://github.com/avaloniaUI/xamlControlsGallery/

has an IOS project that is compatible with Rider and it works with the simulator.

**Comment by FloVanGH** [comment]
I manged it to work but cannot run it on my iPhone. I get:

```
error MT2002: Failed to resolve "Avalonia.OpenGL.IWindowingPlatformGlFeature" reference from "Avalonia.OpenGL, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null"
```

**Comment by maxkatz6** [comment]
It works now
