### ISSUE TITLE
Can't update ToolTip while it's visible

### ISSUE THREAD

**Issue by jangernert** [AvaloniaUI/Avalonia#5086]
I have a custom drawn control that renders an image (camera depth images) and tried to create a tooltip that follows the cursor and displays the pixel coordinates and value. The tooltip however does not update once it pops up.

The tooltip content is correct for the mouse position it gets first shown, but then doesn't update once the mouse moves.
Same for the Vertical/Horizontal offsets. Binding them to properties doesn't update them. Getting the tooltip control via x:Name and FindControl doesn't work as the returned tooltip for some reason doesn't have any of these properties. I tried Invalidating the visual of the tooltip and the whole usercontrol. I tried calling arrange with a calculated position directly. I am officially out of ideas.

I am on 0.10 preview 6.

```
<UserControl xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="clr-namespace:SkiaPlayground.ViewModels;assembly=SkiaPlayground"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:SkiaPlayground.Views;assembly=SkiaPlayground"
        HorizontalAlignment="Center"
        VerticalAlignment="Center"
        mc:Ignorable="d"
        x:Class="SkiaPlayground.Views.FloatImageInspector">
        <ToolTip.Tip>
            <ToolTip
                x:Name="ToolTip"
                HorizontalOffset="{Binding HorizontalOffset}"
                VerticalOffset="{Binding VerticalOffset}"
                ShowDelay="100">
                <TextBlock Text="{Binding ToolTipText}" />
            </ToolTip>
        </ToolTip.Tip>
</UserControl>
```

a few lines of the pointer moved event code:

```
HorizontalOffset += delta.X;
VerticalOffset += delta.Y;

var p1 = new SKPoint((float)p.X, (float)p.Y);
var p2 = RenderTransform.Value.Invert().ToSKMatrix().MapPoint(p1);
var x = (int)p2.X;
var y = (int)p2.Y;
try {
    ToolTipText = $"({x}, {y}) = {_image[y, x]}";
}   
catch {
    ToolTipText = $"({x}, {y}) = XXXXX";
}
```

![Screenshot from 2020-11-22 11-31-14](https://user-images.githubusercontent.com/12012494/99901346-6d0a6580-2cb6-11eb-997f-09e53c470146.png)

**Comment by maxkatz6** [comment]
As a workaround - hide and show tooltip again with IsOpen property after pointer moved. It's not optimal, but should work.

**Comment by jangernert** [comment]
How would that work? I can set IsOpen false before updating position and text and true after. But for that to have any effect I would need to render at least 1 frame without tooltip and then the next with again.

Tested it and don't see any effect. But thanks for the idea.

**Comment by ahopper** [comment]
related to https://github.com/AvaloniaUI/Avalonia/issues/2354

**Comment by danwalmsley** [comment]
Fairly sure this can be fixed really easily!

AffectsMeasure / AffectsRender on the ContentProperty perhaps? I know iv worked around it before... but likely this is a really easy fix for someone who wants to dip their toes in Avalonia.

**Comment by Gillibald** [comment]
What about using https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Primitives/OverlayLayer.cs instead? And avoid using a Tooltip?

**Comment by jangernert** [comment]
Thanks, I'll look into it tomorrow and report back. I'm still relatively new to avalonia. And this is an attempt to port an existing wpf control which uses a tool tip.

**Comment by jangernert** [comment]
@Gillibald Sadly the same result. Text simply doesn't update.

```
<UserControl xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="clr-namespace:SkiaPlayground.ViewModels;assembly=SkiaPlayground"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:SkiaPlayground.Views;assembly=SkiaPlayground"
        HorizontalAlignment="Center"
        VerticalAlignment="Center"
        mc:Ignorable="d"
        x:Class="SkiaPlayground.Views.FloatImageInspector">
        <OverlayLayer>
            <TextBlock x:Name="TextBlock" Text="{Binding ToolTipText}" />
        </OverlayLayer>
</UserControl>
```

```
private string ToolTipText { get; set; } = "Some Text";

// mouse move event
try {
            ToolTipText = $"({x}, {y}) = {_image[y, x]}";
}   
catch {
            ToolTipText = $"({x}, {y}) = XXXXX";
}

Console.WriteLine($"{ToolTipText}");
_textBlock.InvalidateVisual();
```

ToolTipText gets set correctly as can be seen in the console output
```
(58, 163) = 52
(57, 163) = 90
(60, 159) = 94
(63, 148) = 59
(68, 124) = 18
(75, 97) = 34
(81, 69) = 14
(93, 49) = 11
```

**Comment by kekekeks** [comment]
>private string ToolTipText { get; set; } = "Some Text";

You haven't implemented INotifyPropertyChanged

**Comment by jangernert** [comment]
Oh wow. That would make sense :D I wasn't aware that `INotifyPropertyChanged` was a thing as well in avalonia. Since the initial value showed up I thought it must be working somehow. Give me a second, and I can probably close the ticket.

**Comment by jangernert** [comment]
Okay, updating the text works as expected, but setting offsets of an tooltip still doesn't. So I guess the initial report is still valid.
Sorry for the additional noise though =(

**Comment by maxkatz6** [comment]
@jangernert can you share more code, how you work with OverlayLayer? Including parts where you move control to new coordinates.

**Comment by jangernert** [comment]
I haven't tried to move the `TextBlock` inside the `OverlayLayer` yet. What I meant was going back to the `ToolTip` version of the code, updating `HorizontalOffset` and `VerticalOffset` still doesn't work with `INotifyPropertyChanged` implemented.
