### ISSUE TITLE
Cannot move window with custom title bar if ImmediateRenderer is used on Windows 10

### ISSUE THREAD

**Issue by Gawson** [AvaloniaUI/Avalonia#5087]
There might be a bug with hit testing for Windows with AvaloniaUI 0.10-preview6. Window with custom title bar cannot be moved if ImmediateRenderer is used. Using Deferred sovles issue. All necessary areas are set to be IsHitTestVisible=false according to examples.
Window have such attributes:
```csharp
ExtendClientAreaToDecorationsHint="True"
ExtendClientAreaChromeHints="NoChrome"
ExtendClientAreaTitleBarHeightHint="-1"
```
If Window in xaml has IsHitTestVisible=false it can be moved even if ImmediateRenderer is used.

**Comment by danwalmsley** [comment]
@Gawson ImmediateRenderer is not for use in production... its simply for testing and debugging the framework and should not be used... It has limitations and this is one of them... HitTesting does not work correctly with immediate rendering.

**Comment by Gawson** [comment]
@danwalmsley Thank you for clarification. I've just implemented base UI with Avalonia and I want to port the whole project from UWP to .Net5 / Avalonia. Renderer was switched to immediate due to poor deferred rendering performance (sliding panel for application tools which runs in fps when app is maximazied at 3000x2000 notebook screen). Switching to immediate solved this issue but broke hit testing. If there were some complete performance guides it would be easier. Probably using different method for such panel will give better results.

**Comment by grokys** [comment]
That's strange - deferred render should usually have much better performance than immediate renderer. If you could get us a minimal repro we might be able to debug what's slowing it down.

**Comment by Gawson** [comment]
It might be related to render timer as smoothness and response time of UI controls is not causing heavy cpu nor gpu usage.
When immediate renderer is used everything seems to run smooth but with deferred animation playback is choppy and strictly depends on window size (bigger is choppier). I've tried enabling / disabling deferred renderer and several approaches to render timer. If render timer is spinning without any delay (see #2945) also deferred runs smooth but without vsync.

I'm using ultrabook with Intel UHD Graphics 620 (Matebook X Pro) and 3000x2000 screen with 200% DPI scaling.

Here is packed project (ugly, senseless but showing the problem):
https://www.dropbox.com/s/sud5km813rymbv5/AvaloniaApplication1.zip?dl=0

![image](https://user-images.githubusercontent.com/6636946/100114125-61af6980-2e71-11eb-9027-28fca13654c0.png)
Image shows the buttons triggering animations.

**Comment by trympet** [comment]
> That's strange - deferred render should usually have much better performance than immediate renderer. If you could get us a minimal repro we might be able to debug what's slowing it down.

I am seeing the same behavior on 0.10.6. 4k display with 200% scaling is handled fine by immediate renderer, but not deferred.
