### ISSUE TITLE
Help.OpenFileDialog does not work for UseManagedSystemDialogs

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#5089]
After opening UseManagedSystemDialogs, OpenFileDialog opens abnormally.

![image](https://user-images.githubusercontent.com/7692353/99934573-52f58380-2d99-11eb-9fda-d77110939ba3.png)

I caught an exception. It was found that there was a problem with the path recognition.
Exception prompt: Could not find a part of the path'/media/wzl/UOS\04020'.
But the place I verified locally is'/media/wzl/UOS 20'. \040 is a space.
I checked the source code, but I haven't seen the idea for the time being. Do you have any friends who know it? What should we do?

![image](https://user-images.githubusercontent.com/7692353/99934493-188be680-2d99-11eb-8800-15a9ff15a71d.png)

![image](https://user-images.githubusercontent.com/7692353/99934516-2b9eb680-2d99-11eb-8d09-98e4730beb33.png)

**Comment by maxkatz6** [comment]
Duplicate 
https://github.com/AvaloniaUI/Avalonia/issues/4844

**Comment by wuzlai** [comment]
> Duplicate

thank you ,i will go to #4844

**Comment by wuzlai** [comment]
> Duplicate
> #4844

Hi，I  reopen the issue.
The problem you recommend is similar to mine, but my special one is that the file dialog opens with a blank space in the default path. I want to re-specify this default path now, otherwise, if I open the file by specifying the path according to the source code, there will be an exception. There are too many examples of paths with Spaces, and there are too many operating systems. Many addresses have Spaces. I searched the Internet, but I didn't see a solution. May I ask whether this problem can be officially fixed? Thank you

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/8134
