### ISSUE TITLE
UI beautification

### ISSUE THREAD

**Issue by dayAndnight2018** [AvaloniaUI/Avalonia#5099]
Is there official UI beautification schedule? The control UIs now are so ordinary！

**Comment by wieslawsoltes** [comment]
You can use fluent theme in `0.10.0-preview6` also take a look at https://github.com/AvaloniaUI/XamlControlsGallery

**Comment by dayAndnight2018** [comment]
> You can use fluent theme in `0.10.0-preview6` also take a look at https://github.com/AvaloniaUI/XamlControlsGallery

Cool! Thanks a lot!

**Comment by dayAndnight2018** [comment]
> You can use fluent theme in `0.10.0-preview6` also take a look at https://github.com/AvaloniaUI/XamlControlsGallery

is there a control for markdown txt to html for text edit and html preview?

**Comment by maxkatz6** [comment]
@dayAndnight2018 

There is new markdown control from community. I haven't tried it, but it looks good.
https://github.com/whistyun/Markdown.Avalonia

And I think the newest WebView implementation using Chromium is this one:
https://github.com/CefNet/CefNet

Also if you need rich text editor, you may be interested in this:
https://github.com/AvaloniaUI/AvaloniaEdit

There are more control here:
https://github.com/AvaloniaCommunity/awesome-avalonia

**Comment by dayAndnight2018** [comment]
> @dayAndnight2018
> 
> There is new markdown control from community. I haven't tried it, but it looks good.
> https://github.com/whistyun/Markdown.Avalonia
> 
> And I think the newest WebView implementation using Chromium is this one:
> https://github.com/CefNet/CefNet
> 
> Also if you need rich text editor, you may be interested in this:
> https://github.com/AvaloniaUI/AvaloniaEdit
> 
> There are more control here:
> https://github.com/AvaloniaCommunity/awesome-avalonia

so warm-hearted ! Thanks a lot!

**Comment by fforjan** [comment]
@maxkatz6 not sure who owns  https://github.com/AvaloniaCommunity/awesome-avalonia but could we add the Markdown component ? I was looking for one and didn't see it on this page

**Comment by maxkatz6** [comment]
@fforjan somebody needs to create PR into this repo. @whistyun may want to do it.

**Comment by dayAndnight2018** [comment]
> @fforjan somebody needs to create PR into this repo. @whistyun may want to do it.

I alse have a suggestion we may collect main materials about Avalonia development to one place! It is difficult to find a reliable solution for Avalonia development！

**Comment by dayAndnight2018** [comment]
My first step to Avalonia! (https://github.com/dayAndnight2018/AvaloniaRelated)
