### ISSUE TITLE
Any way to make a remote render?

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#5105]
Hi there, now I'm making a DraggableTab Control, it's almost completed, that lacks a little detail: there isn't a preview!; for example, when you use some application with drag & drop elements, when these are dragging, shows a preview, and now, I want to make the same, you know some way to make it?

**Comment by maxkatz6** [comment]
I am not sure what exactly do you want. Probably you need VisualBrush to render control to an image and move it with a cursor.

**Comment by PieroCastillo** [comment]
ok, like you can see the follow gif, in the control there's a drag, that's made with DragDrop system, the thing what I wanna make it's a preview, for example, when you use chrome the tab follows the cursor, that's I wanna make 


![au_tabvw](https://user-images.githubusercontent.com/39932324/100381275-a9a3cd00-2fe6-11eb-9785-b921032e8ce5.gif)

**Comment by maxkatz6** [comment]
So you can create VisualBrush of tab header and move it with cursor
