### ISSUE TITLE
Default button does not get invoked when pressing enter from inside an AutoCompleteBox

### ISSUE THREAD

**Issue by LBognanni** [AvaloniaUI/Avalonia#5106]
Hi all, I have a window with an AutoCompleteBox and a Button whose `IsDefault` property is set to `true`.
When pressing the Enter key I would expect the Button's action to be invoked, but instead nothing happens.

I believe this could be fixed by checking `IsDropDownOpen` [here](https://github.com/AvaloniaUI/Avalonia/blob/2e2f9f2bf8f23341bc984ce15808cd55a7d9d4c8/src/Avalonia.Controls/AutoCompleteBox.cs#L1408) instead of always setting `e.Handled = true`

**Comment by LBognanni** [comment]
As a workaround, I subclassed the AutoCompleteBox and this works as expected:

```
    public class AutoCompleteBox : Avalonia.Controls.AutoCompleteBox, IStyleable
    {
        public AutoCompleteBox() : base()
        {
        }

        Type IStyleable.StyleKey => typeof(Avalonia.Controls.AutoCompleteBox);

        protected override void OnKeyDown(KeyEventArgs e)
        {
            if ((e.Key != Key.Enter) || IsDropDownOpen)
                base.OnKeyDown(e);
        }
    }
```

**Comment by maxkatz6** [comment]
@LBognanni makes sense for me.
Do you want to submit a PR?

**Comment by LBognanni** [comment]
@maxkatz6 sure, can do :)
