### ISSUE TITLE
Invalid size returned for Measure Exception

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#511]
This might be a different manifestation of #510 

This commit will repro, please take a look at #510 the instructions to trigger the problem are the same.

https://github.com/VitalElement/AvalonStudio/commit/9de00d3be291869766188b75be3d5ebe0ff58a87

**Comment by grokys** [comment]
Is this still happening?

**Comment by danwalmsley** [comment]
I have to pop out will see if it still happens.

**Comment by jkoritzinsky** [comment]
@danwalmsley I'm going to close this. We can re-open if you find a repro for this.

**Comment by GNUGradyn** [comment]
This issue is still present https://github.com/AvaloniaUI/Avalonia/issues/8624
