### ISSUE TITLE
TextBox cannot enter Chinese, in deepin.Linux system

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#5111]
In Deepin.Linux, after switching the input method to Chinese, the text box is still typing the English letters on the keyboard.
But with Windows 10, everything is fine. You can use input method to input Chinese. There is no idea at present. Please give me some Suggestions. Thank you。
I have read the issue ( https://github.com/AvaloniaUI/Avalonia/issues/2076 ).But still confused

![image](https://user-images.githubusercontent.com/7692353/100426543-ff05da00-30cb-11eb-93f8-c393b517c592.png)

**Comment by Gillibald** [comment]
#4893

We need to implement IME support first before this will work properly

**Comment by wuzlai** [comment]
> #4893
> 
> We need to implement IME support first before this will work properly

Yes, you are right, but I wonder if there are any compromise solutions. I can try to modify the source code and so on, for myself, this situation is quite urgent.

**Comment by dayAndnight2018** [comment]
> In Deepin.Linux, after switching the input method to Chinese, the text box is still typing the English letters on the keyboard.
> But with Windows 10, everything is fine. You can use input method to input Chinese. There is no idea at present. Please give me some Suggestions. Thank you。
> I have read the issue ( #2076 ).But still confused
> 
> ![image](https://user-images.githubusercontent.com/7692353/100426543-ff05da00-30cb-11eb-93f8-c393b517c592.png)

但凡你百度过，就不会有这个问题

https://github.com/dayAndnight2018/AvaloniaRelated/blob/main/develop-on-macOS.md

**Comment by wuzlai** [comment]
> > In Deepin.Linux, after switching the input method to Chinese, the text box is still typing the English letters on the keyboard.
> > But with Windows 10, everything is fine. You can use input method to input Chinese. There is no idea at present. Please give me some Suggestions. Thank you。
> > I have read the issue ( #2076 ).But still confused
> > ![image](https://user-images.githubusercontent.com/7692353/100426543-ff05da00-30cb-11eb-93f8-c393b517c592.png)
> 
> 但凡你百度过，就不会有这个问题
> 
> https://github.com/dayAndnight2018/AvaloniaRelated/blob/main/develop-on-macOS.md

感谢您的回复，这个方案是解决macos下文本框输入和显示中文的乱码问题。网友已经反馈过（https://github.com/AvaloniaUI/Avalonia/issues/3780）。我现在遇到的问题是在deepin.linux等国产系统下，文本框无法输入中文的问题，确切来说是IME不支持，且您提到的这个方案，我也在deepin下测试过，是没有效果的。不知道您有没有好的建议了，谢谢。

**Comment by dayAndnight2018** [comment]
> > > In Deepin.Linux, after switching the input method to Chinese, the text box is still typing the English letters on the keyboard.
> > > But with Windows 10, everything is fine. You can use input method to input Chinese. There is no idea at present. Please give me some Suggestions. Thank you。
> > > I have read the issue ( #2076 ).But still confused
> > > ![image](https://user-images.githubusercontent.com/7692353/100426543-ff05da00-30cb-11eb-93f8-c393b517c592.png)
> > 
> > 
> > 但凡你百度过，就不会有这个问题
> > https://github.com/dayAndnight2018/AvaloniaRelated/blob/main/develop-on-macOS.md
> 
> 感谢您的回复，这个方案是解决macos下文本框输入和显示中文的乱码问题。网友已经反馈过（[https://github.com/AvaloniaUI/Avalonia/issues/3780）。我现在遇到的问题是在deepin.linux等国产系统下，文本框无法输入中文的问题，确切来说是IME不支持，且您提到的这个方案，我也在deepin下测试过，是没有效果的。不知道您有没有好的建议了，谢谢。](https://github.com/AvaloniaUI/Avalonia/issues/3780%EF%BC%89%E3%80%82%E6%88%91%E7%8E%B0%E5%9C%A8%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98%E6%98%AF%E5%9C%A8deepin.linux%E7%AD%89%E5%9B%BD%E4%BA%A7%E7%B3%BB%E7%BB%9F%E4%B8%8B%EF%BC%8C%E6%96%87%E6%9C%AC%E6%A1%86%E6%97%A0%E6%B3%95%E8%BE%93%E5%85%A5%E4%B8%AD%E6%96%87%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E7%A1%AE%E5%88%87%E6%9D%A5%E8%AF%B4%E6%98%AFIME%E4%B8%8D%E6%94%AF%E6%8C%81%EF%BC%8C%E4%B8%94%E6%82%A8%E6%8F%90%E5%88%B0%E7%9A%84%E8%BF%99%E4%B8%AA%E6%96%B9%E6%A1%88%EF%BC%8C%E6%88%91%E4%B9%9F%E5%9C%A8deepin%E4%B8%8B%E6%B5%8B%E8%AF%95%E8%BF%87%EF%BC%8C%E6%98%AF%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C%E7%9A%84%E3%80%82%E4%B8%8D%E7%9F%A5%E9%81%93%E6%82%A8%E6%9C%89%E6%B2%A1%E6%9C%89%E5%A5%BD%E7%9A%84%E5%BB%BA%E8%AE%AE%E4%BA%86%EF%BC%8C%E8%B0%A2%E8%B0%A2%E3%80%82)

你是用虚拟键盘输入的是吗？尝试过实体键盘输入吗？

**Comment by wuzlai** [comment]
> > > > In Deepin.Linux, after switching the input method to Chinese, the text box is still typing the English letters on the keyboard.
> > > > But with Windows 10, everything is fine. You can use input method to input Chinese. There is no idea at present. Please give me some Suggestions. Thank you。
> > > > I have read the issue ( #2076 ).But still confused
> > > > ![image](https://user-images.githubusercontent.com/7692353/100426543-ff05da00-30cb-11eb-93f8-c393b517c592.png)
> > > 
> > > 
> > > 但凡你百度过，就不会有这个问题
> > > https://github.com/dayAndnight2018/AvaloniaRelated/blob/main/develop-on-macOS.md
> > 
> > 
> > 感谢您的回复，这个方案是解决macos下文本框输入和显示中文的乱码问题。网友已经反馈过（[https://github.com/AvaloniaUI/Avalonia/issues/3780）。我现在遇到的问题是在deepin.linux等国产系统下，文本框无法输入中文的问题，确切来说是IME不支持，且您提到的这个方案，我也在deepin下测试过，是没有效果的。不知道您有没有好的建议了，谢谢。](https://github.com/AvaloniaUI/Avalonia/issues/3780%EF%BC%89%E3%80%82%E6%88%91%E7%8E%B0%E5%9C%A8%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98%E6%98%AF%E5%9C%A8deepin.linux%E7%AD%89%E5%9B%BD%E4%BA%A7%E7%B3%BB%E7%BB%9F%E4%B8%8B%EF%BC%8C%E6%96%87%E6%9C%AC%E6%A1%86%E6%97%A0%E6%B3%95%E8%BE%93%E5%85%A5%E4%B8%AD%E6%96%87%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E7%A1%AE%E5%88%87%E6%9D%A5%E8%AF%B4%E6%98%AFIME%E4%B8%8D%E6%94%AF%E6%8C%81%EF%BC%8C%E4%B8%94%E6%82%A8%E6%8F%90%E5%88%B0%E7%9A%84%E8%BF%99%E4%B8%AA%E6%96%B9%E6%A1%88%EF%BC%8C%E6%88%91%E4%B9%9F%E5%9C%A8deepin%E4%B8%8B%E6%B5%8B%E8%AF%95%E8%BF%87%EF%BC%8C%E6%98%AF%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C%E7%9A%84%E3%80%82%E4%B8%8D%E7%9F%A5%E9%81%93%E6%82%A8%E6%9C%89%E6%B2%A1%E6%9C%89%E5%A5%BD%E7%9A%84%E5%BB%BA%E8%AE%AE%E4%BA%86%EF%BC%8C%E8%B0%A2%E8%B0%A2%E3%80%82)
> 
> 你是用虚拟键盘输入的是吗？尝试过实体键盘输入吗？

实体键盘和虚拟键盘都是测试过的了，虚拟键盘方便看效果。目前暂时没有办法。看看大家有没有什么好的办法吧。

**Comment by wuzlai** [comment]
Top it off and ask if you have a good way to deal with it? Is there any specific official arrangement? Could you give priority to this issue? Thank you very much. @Gillibald  @kekekeks

**Comment by danwalmsley** [comment]
This is being worked on. It wont make 0.10... its a huge task, but good progress has already been made.

I would not expect anything until next year though.

**Comment by wuzlai** [comment]
> This is being worked on. It wont make 0.10... its a huge task, but good progress has already been made.
> 
> I would not expect anything until next year though.

Thank you for your reply. Well understood the complexity of the problem and the amount of work involved. Avalonia is easy to use, cross-platform and has a nice interface. Apart from this input method identification problem, there are no other serious use problems. We have basically completed the development of our Avalonia project, and we only need the support function of the Chinese input method at present. We really need this function urgently. We will keep watching it and look forward to seeing a new version to solve this problem soon. thank you

**Comment by Thonnn** [comment]
> > This is being worked on. It wont make 0.10... its a huge task, but good progress has already been made.
> > I would not expect anything until next year though.
> 
> Thank you for your reply. Well understood the complexity of the problem and the amount of work involved. Avalonia is easy to use, cross-platform and has a nice interface. Apart from this input method identification problem, there are no other serious use problems. We have basically completed the development of our Avalonia project, and we only need the support function of the Chinese input method at present. We really need this function urgently. We will keep watching it and look forward to seeing a new version to solve this problem soon. thank you

Hello, I have the same problem as you. Do you already have an alternative solution? If so, can you share it?

**Comment by danwalmsley** [comment]
> > This is being worked on. It wont make 0.10... its a huge task, but good progress has already been made.
> > I would not expect anything until next year though.
> 
> Thank you for your reply. Well understood the complexity of the problem and the amount of work involved. Avalonia is easy to use, cross-platform and has a nice interface. Apart from this input method identification problem, there are no other serious use problems. We have basically completed the development of our Avalonia project, and we only need the support function of the Chinese input method at present. We really need this function urgently. We will keep watching it and look forward to seeing a new version to solve this problem soon. thank you

If this is really urgent, our paid support can make this happen much quicker. Get in touch team@avaloniaui.net, otherwise I expect it may be a few months before this is ready.

**Comment by wuzlai** [comment]
> > > This is being worked on. It wont make 0.10... its a huge task, but good progress has already been made.
> > > I would not expect anything until next year though.
> > 
> > 
> > Thank you for your reply. Well understood the complexity of the problem and the amount of work involved. Avalonia is easy to use, cross-platform and has a nice interface. Apart from this input method identification problem, there are no other serious use problems. We have basically completed the development of our Avalonia project, and we only need the support function of the Chinese input method at present. We really need this function urgently. We will keep watching it and look forward to seeing a new version to solve this problem soon. thank you
> 
> Hello, I have the same problem as you. Do you already have an alternative solution? If so, can you share it?

Hello, there is no solution at the moment. We're waiting, too. If you have ideas, I hope you can study them together.

**Comment by wuzlai** [comment]
> > > This is being worked on. It wont make 0.10... its a huge task, but good progress has already been made.
> > > I would not expect anything until next year though.
> > 
> > 
> > Thank you for your reply. Well understood the complexity of the problem and the amount of work involved. Avalonia is easy to use, cross-platform and has a nice interface. Apart from this input method identification problem, there are no other serious use problems. We have basically completed the development of our Avalonia project, and we only need the support function of the Chinese input method at present. We really need this function urgently. We will keep watching it and look forward to seeing a new version to solve this problem soon. thank you
> 
> If this is really urgent, our paid support can make this happen much quicker. Get in touch [team@avaloniaui.net](mailto:team@avaloniaui.net), otherwise I expect it may be a few months before this is ready.

Thank you very much. I have sent an email to team@avaloniaui.net.

**Comment by codeconscious** [comment]
Hello. I've only very recently tried out Avalonia for the first time and immediately took to it. Being able to run the same application on Windows, Mac, and Linux so easily is simply exhilarating! However, tools I want to develop will use Japanese and other Asian languages, so I was curious approximately how the time frame of release is looking at this point. Apologies if I've overlooked the information on other issue threads or anywhere else. Thank you much.

**Comment by jmacato** [comment]
it'll be done once #4893  is merged so watch that space instead :)

**Comment by codeconscious** [comment]
Thank you very much, @jmacato! I'm looking forward to it.

**Comment by kekekeks** [comment]
@codeconscious you can use WenQuanYi Micro Hei font for now

>You need to use a font that has Chinese characters. https://github.com/anthonyfok/fonts-wqy-microhei is a good one
[WenQuanYiMicroHei-01.ttf.zip](https://github.com/AvaloniaUI/Avalonia/files/5703016/WenQuanYiMicroHei-01.ttf.zip)
>
>Place it into Assets, add as AvaloniaResource and add something like
>
>```
><Style Selector="TextBlock">
>    <Setter Property="FontFamily" Value="avares://YourAssemblyName/Assets/Fonts#WenQuanYi Micro Hei" />
></Style>
>```
>to your App.xaml after the theme

**Comment by codeconscious** [comment]
Thank you very much for the tip, @kekekeks. My application needs to support multiple languages in one TextBox at a time, and your tip led me to try setting the font to "Arial Unicode MS," which is already installed on my system, and that worked! Of course, input via IME doesn't work yet, but this will do for prototyping, at least. I appreciate the assist.

**Comment by Takoooooo** [comment]
Fixed in #4893.

**Comment by protofabcode** [comment]
@wuzlai 您是怎样实现虚拟键盘的，我找了很久都没有找到解决方案，希望可以向您请教

**Comment by protofabcode** [comment]
> > > > In Deepin.Linux, after switching the input method to Chinese, the text box is still typing the English letters on the keyboard.
> > > > But with Windows 10, everything is fine. You can use input method to input Chinese. There is no idea at present. Please give me some Suggestions. Thank you。
> > > > I have read the issue ( #2076 ).But still confused
> > > > ![image](https://user-images.githubusercontent.com/7692353/100426543-ff05da00-30cb-11eb-93f8-c393b517c592.png)
> > > 
> > > 
> > > 但凡你百度过，就不会有这个问题
> > > https://github.com/dayAndnight2018/AvaloniaRelated/blob/main/develop-on-macOS.md
> > 
> > 
> > 感谢您的回复，这个方案是解决macos下文本框输入和显示中文的乱码问题。网友已经反馈过（[https://github.com/AvaloniaUI/Avalonia/issues/3780）。我现在遇到的问题是在deepin.linux等国产系统下，文本框无法输入中文的问题，确切来说是IME不支持，且您提到的这个方案，我也在deepin下测试过，是没有效果的。不知道您有没有好的建议了，谢谢。](https://github.com/AvaloniaUI/Avalonia/issues/3780%EF%BC%89%E3%80%82%E6%88%91%E7%8E%B0%E5%9C%A8%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98%E6%98%AF%E5%9C%A8deepin.linux%E7%AD%89%E5%9B%BD%E4%BA%A7%E7%B3%BB%E7%BB%9F%E4%B8%8B%EF%BC%8C%E6%96%87%E6%9C%AC%E6%A1%86%E6%97%A0%E6%B3%95%E8%BE%93%E5%85%A5%E4%B8%AD%E6%96%87%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E7%A1%AE%E5%88%87%E6%9D%A5%E8%AF%B4%E6%98%AFIME%E4%B8%8D%E6%94%AF%E6%8C%81%EF%BC%8C%E4%B8%94%E6%82%A8%E6%8F%90%E5%88%B0%E7%9A%84%E8%BF%99%E4%B8%AA%E6%96%B9%E6%A1%88%EF%BC%8C%E6%88%91%E4%B9%9F%E5%9C%A8deepin%E4%B8%8B%E6%B5%8B%E8%AF%95%E8%BF%87%EF%BC%8C%E6%98%AF%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C%E7%9A%84%E3%80%82%E4%B8%8D%E7%9F%A5%E9%81%93%E6%82%A8%E6%9C%89%E6%B2%A1%E6%9C%89%E5%A5%BD%E7%9A%84%E5%BB%BA%E8%AE%AE%E4%BA%86%EF%BC%8C%E8%B0%A2%E8%B0%A2%E3%80%82)
> 
> 你是用虚拟键盘输入的是吗？尝试过实体键盘输入吗？

你们是怎样实现在选中textbox后跳出虚拟键盘的？

**Comment by ffufeng** [comment]
> > > > > In Deepin.Linux, after switching the input method to Chinese, the text box is still typing the English letters on the keyboard.
> > > > > But with Windows 10, everything is fine. You can use input method to input Chinese. There is no idea at present. Please give me some Suggestions. Thank you。
> > > > > I have read the issue ( #2076 ).But still confused
> > > > > ![image](https://user-images.githubusercontent.com/7692353/100426543-ff05da00-30cb-11eb-93f8-c393b517c592.png)
> > > > 
> > > > 
> > > > 但凡你百度过，就不会有这个问题
> > > > https://github.com/dayAndnight2018/AvaloniaRelated/blob/main/develop-on-macOS.md
> > > 
> > > 
> > > 感谢您的回复，这个方案是解决macos下文本框输入和显示中文的乱码问题。网友已经反馈过（[https://github.com/AvaloniaUI/Avalonia/issues/3780）。我现在遇到的问题是在deepin.linux等国产系统下，文本框无法输入中文的问题，确切来说是IME不支持，且您提到的这个方案，我也在deepin下测试过，是没有效果的。不知道您有没有好的建议了，谢谢。](https://github.com/AvaloniaUI/Avalonia/issues/3780%EF%BC%89%E3%80%82%E6%88%91%E7%8E%B0%E5%9C%A8%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98%E6%98%AF%E5%9C%A8deepin.linux%E7%AD%89%E5%9B%BD%E4%BA%A7%E7%B3%BB%E7%BB%9F%E4%B8%8B%EF%BC%8C%E6%96%87%E6%9C%AC%E6%A1%86%E6%97%A0%E6%B3%95%E8%BE%93%E5%85%A5%E4%B8%AD%E6%96%87%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E7%A1%AE%E5%88%87%E6%9D%A5%E8%AF%B4%E6%98%AFIME%E4%B8%8D%E6%94%AF%E6%8C%81%EF%BC%8C%E4%B8%94%E6%82%A8%E6%8F%90%E5%88%B0%E7%9A%84%E8%BF%99%E4%B8%AA%E6%96%B9%E6%A1%88%EF%BC%8C%E6%88%91%E4%B9%9F%E5%9C%A8deepin%E4%B8%8B%E6%B5%8B%E8%AF%95%E8%BF%87%EF%BC%8C%E6%98%AF%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C%E7%9A%84%E3%80%82%E4%B8%8D%E7%9F%A5%E9%81%93%E6%82%A8%E6%9C%89%E6%B2%A1%E6%9C%89%E5%A5%BD%E7%9A%84%E5%BB%BA%E8%AE%AE%E4%BA%86%EF%BC%8C%E8%B0%A2%E8%B0%A2%E3%80%82)
> > 
> > 
> > 你是用虚拟键盘输入的是吗？尝试过实体键盘输入吗？
> 
> 你们是怎样实现在选中textbox后跳出虚拟键盘的？

我也想问问这个虚拟键盘是怎么实现的
