### ISSUE TITLE
Notifications don't work in .NET 5

### ISSUE THREAD

**Issue by frederik-hoeft** [AvaloniaUI/Avalonia#5117]
When trying to initialize an instance of `WindowNotificationManager` in .NET 5 it just crashes with the following exception

`System.TypeLoadException: 'Could not load type 'System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken' from assembly 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'`

The `WindowNotificationManager` is referencing `EventRegistrationToken` somewhere, but it seems like Microsoft dropped support for it in .NET 5 (see [Microsoft docs](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.windowsruntime.eventregistrationtoken?view=netcore-3.1)).

The exception actually seems to be thrown in ReactiveUI. Below is the location where Avalonia makes the call to `Observable.FromEventPattern<TemplateAppliedEventArgs>` which internally seems to be dependent on `EventRegistrationToken` as this is where it crashes (somewhere in 3rd party code :neutral_face: )
https://github.com/AvaloniaUI/Avalonia/blob/690ebfa557742cd51125cbd25fbaeb3acb715f13/src/Avalonia.Controls/Notifications/WindowNotificationManager.cs#L65-L69

**Comment by maxkatz6** [comment]
It's not a problem with Avalonia or ReactiveUI, but in System.Reactive.Ling.
I believe it should fixed with its latest version: https://github.com/dotnet/reactive/commit/cd8ff91fc95de96aa3cd6cba0fa50f526b219f64#diff-3b8aac77a13d745775ab55b66e088b33c0af69ab189360e99607db5ee5d51a25

Can you try to reference System.Linq.Async 5.0.0 ?

**Comment by maxkatz6** [comment]
Also it should already work with latest Avalonia nightly build, where System.Reactive version is updated
https://github.com/AvaloniaUI/Avalonia/commit/8c7540ddf15137d96f77cf386dde5eebd49c44df
