### ISSUE TITLE
[Suggestion] Polish the Fluent Theme(Maybe for v0.11)

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#5119]
Hi, I use avalonia since 1 year, and it's very good the framework evolution, but, I've a little issue with the Fluent theme, when any person use the fluent theme, he expects a theme like Windows Fluent Theme, well, the Avalonia Fluent theme is very similar, I even think that in some features is better than windows theme, in contrast,  that lacks some features, for example, the depth, (for me) this is very important,  as that gives more naturalness to the UI, this is an visual example:

![Peek 29-11-2020 00-53](https://user-images.githubusercontent.com/39932324/100534496-88f19800-31dd-11eb-8a35-a7f428c3adf3.gif)
![image](https://user-images.githubusercontent.com/39932324/100534497-8f800f80-31dd-11eb-93cd-5b9f2b2d84e4.png)

well, I think that's enought, the rest is well done :D

**Comment by danwalmsley** [comment]
We are adding new rendering capabilities to support, lighting, shadows, reveal, etc. Thus absolutely will be done when its possible.

**Comment by PieroCastillo** [comment]
> . Thus absolutely will be done when its possible.

nice, I hope till you do it! :D
