### ISSUE TITLE
Why Preview Builds Doesn't work With CoreRt?

### ISSUE THREAD

**Issue by Shadow4walker** [AvaloniaUI/Avalonia#5121]
is takes around 27 Min To Compile 'with V0.10.0-preview6 'and when running compiled app it crash immediately!
the Stable Version 0.9.11 takes around 4 Min and the compiled app running with no prob
is there any way to make Avalonia Preview Builds Works with CoreRT?

**Comment by maxkatz6** [comment]
There is an issue about CoreRT support:
https://github.com/AvaloniaUI/Avalonia/issues/1476

You need to try it with latest nightly builds and with UseWindowsUIComposition disabled (with Win32PlatformOptions in BuildAvaloniaApp method). It should work fine, although I haven't tested it.

**Comment by Shadow4walker** [comment]
> There is an issue about CoreRT support:
> #1476
> 
> You need to try it with latest nightly builds and with UseWindowsUIComposition disabled (with Win32PlatformOptions in BuildAvaloniaApp method). It should work fine, although I haven't tested it.

thanks for the feedback it seems i can't update the Avalonia.Desktop to the latest nightly builds , i keep getting this error 

> Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: Avalonia from 0.10.999-cibuild0011642-beta to 0.10.999-cibuild0011450-beta. Reference the package directly from the project to select a different version. 
 AvaloniaCorert -> Avalonia.Desktop 0.10.999-cibuild0011450-beta -> Avalonia.Native 0.10.999-cibuild0011642-beta -> Avalonia (>= 0.10.999-cibuild0011642-beta) 
 AvaloniaCorert -> Avalonia.Desktop 0.10.999-cibuild0011450-beta -> Avalonia (>= 0.10.999-cibuild0011450-beta)

**Comment by Shadow4walker** [comment]
Update On This 
Packages Updated to the latest latest Nightly Builds '0.10.999' ' and "UseWindowsUIComposition has been set to False" BTW the rd.xml already defined' 
and after waiting more than half an hour for the CoreRt to Finish Compiling the app crash just like before 
by reading crash Dump the Exception hit at 

>public static AppBuilder BuildAvaloniaApp()
=> AppBuilder.Configure<App>() ====> HERE!

**Comment by Shadow4walker** [comment]
it appear the issue was Due to [Missing clrcompression.dll](https://github.com/dotnet/corert/issues/5496/#issuecomment-466191639) even when the app is not using it still required!
All Fixed After this
