### ISSUE TITLE
possible bug with SelectingITemsControl?

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#5123]
hi, now i've a very strange issue, I made a NavigationView, so, I wanted to make an animation when the selected item changed, and now I found the solution, when this occurs I remove and add a pseudoclass on SelectionChanged, this works well, till I found a really serious problem, when the same event (SelectionChanged) is raised in another derivated control(like listbox, tabcontrol, etc) the event is raised in the navigationview too, and I don't know what can it be the reason, if the event is raised in some TabControl, it shouldn't be raised in another control..
![Peek 29-11-2020 23-25](https://user-images.githubusercontent.com/39932324/100568803-375b1300-329a-11eb-9da9-8099722e9039.gif)

I found a temporal solution, add a custom method(e.Handled = true;) foreach SelectingItemControl, but this is quite low, I would want to know if there is a some way to fix this, thanks

**Comment by maxkatz6** [comment]
I am not sure if SelectionChanged should be a routed event.
@grokys can you help here?

**Comment by PieroCastillo** [comment]
:(

**Comment by danwalmsley** [comment]
Any code?

Are you using static Class handers?

**Comment by PieroCastillo** [comment]
[NavigationView.cs](https://github.com/PieroCastillo/Aura.UI/blob/master/src/Aura.UI/Controls/Navigation/NavigationView.cs#L49)
This is the code, the OnSelectionChanged is added to Selectionchanged event with ```this.AddHandler(SelectionChangedEvent, OnSelectionChanged, RoutingStrategies.Bubble);```
