### ISSUE TITLE
Why there is an error?

### ISSUE THREAD

**Issue by dayAndnight2018** [AvaloniaUI/Avalonia#5132]
Why there is still an error? I have code the click handler! 

![image](https://user-images.githubusercontent.com/44399091/100996194-bd75a300-3593-11eb-943f-d81012d6fd0d.png)

**Comment by FoggyFinder** [comment]
Not enough information is provided. Can you give more details?

**Comment by dayAndnight2018** [comment]
> Not enough information is provided. Can you give more details?

okey! It is a shortcoming of the plugin for Rider! It can be compiled successfully.

**Comment by dayAndnight2018** [comment]
By the way, the documents of the avalonia are not enough! I just want to find How to select a file from fiddler when i click a button, If i had no experience about WPF development, it is hard to deal with it!

**Comment by dayAndnight2018** [comment]
The existed documents are lack of examples, or more picture of the control present. It is better there are preview for a control introduction.

**Comment by FoggyFinder** [comment]
> By the way, the documents of the avalonia are not enough!

True, true. But 

a) Documentation is [OpenSource](https://github.com/AvaloniaUI/avaloniaui.net). If something is missing you can create PR with proposal (I'd suggest creating an issue first)

b) There're resources where you can ask Qs:

* Chats
   * gitter: https://gitter.im/AvaloniaUI/Avalonia
   * discord: https://aka.ms/dotnet-discord

* Q&A communities: 
   * StackOverflow: [avalonia](https://stackoverflow.com/questions/tagged/avalonia)
   * TopAnswers: [C#](https://topanswers.xyz/csharp)
   * CoDidact [CoDidact.Software Development](https://software.codidact.com)

**Comment by dayAndnight2018** [comment]
> > By the way, the documents of the avalonia are not enough!
> 
> True, true. But
> 
> a) Documentation is [OpenSource](https://github.com/AvaloniaUI/avaloniaui.net). If something is missing you can create PR with proposal (I'd suggest creating an issue first)
> 
> b) There're resources where you can ask Qs:
> 
> * Chats
>   
>   * gitter: https://gitter.im/AvaloniaUI/Avalonia
>   * discord: https://aka.ms/dotnet-discord
> * Q&A communities:
>   
>   * StackOverflow: [avalonia](https://stackoverflow.com/questions/tagged/avalonia)
>   * TopAnswers: [C#](https://topanswers.xyz/csharp)
>   * CoDidact [CoDidact.Software Development](https://software.codidact.com)

ok, thanks

**Comment by rstm-sf** [comment]
> 
> 
> > Not enough information is provided. Can you give more details?
> 
> okey! It is a shortcoming of the plugin for Rider! It can be compiled successfully.

OnButtonClick is an private?

https://github.com/ForNeVeR/AvaloniaRider/issues/92#issuecomment-716154399 

This has already been fixed in Avalonia, but only available in master

**Comment by dayAndnight2018** [comment]
> > > Not enough information is provided. Can you give more details?
> > 
> > 
> > okey! It is a shortcoming of the plugin for Rider! It can be compiled successfully.
> 
> OnButtonClick is an private?
> 
> [ForNeVeR/AvaloniaRider#92 (comment)](https://github.com/ForNeVeR/AvaloniaRider/issues/92#issuecomment-716154399)
> 
> This has already been fixed in Avalonia, but only available in master

thanks, fix it!
