### ISSUE TITLE
Visual.LogBindingError method from Avalonia.Visuals conflicts with AvaloniaObject.LogBindingError from Avalonia.Base

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaUI/Avalonia#5137]
Hello!

[Visual.LogBindingError](https://github.com/AvaloniaUI/Avalonia/blob/6b68d186635580a55bbaee83f73ed10584e92e6a/src/Avalonia.Visuals/Visual.cs#L488) method from Avalonia.Visuals conflicts with [AvaloniaObject.LogBindingError](https://github.com/AvaloniaUI/Avalonia/blob/6b68d186635580a55bbaee83f73ed10584e92e6a/src/Avalonia.Base/AvaloniaObject.cs#L577) from Avalonia.Base. Because inheritance

How to reproduce?

Add `InternalsVisibleTo` for  `Avalonia.Visuals` to AssemblyInfo.cs file from `Avalonia.Base` and using something from base:
>   Visual.cs(488, 40): [CS0507] 'Visual.LogBindingError(AvaloniaProperty, Exception)': cannot change access modifiers when overriding 'protected internal' inherited member 'AvaloniaObject.LogBindingError(AvaloniaProperty, Exception)'

**Comment by kekekeks** [comment]
One isn't supposed to add `InternalsVisibleTo` between core assemblies, I think.

**Comment by rstm-sf** [comment]
But, I need it to get rid of copy-paste https://github.com/AvaloniaUI/Avalonia/pull/5139. Or is it better not to do that?

**Comment by Gillibald** [comment]
I think there are plans to merge some of the core projects
