### ISSUE TITLE
ColorConverter is missing...

### ISSUE THREAD

**Issue by aboimpinto** [AvaloniaUI/Avalonia#5140]
Hello,
I noticed that ColorConverter, that is part of the System.Windows.Media, is missing in Avalon.Media

here is the definition from Microsoft documentation
https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.colorconverter.convertfromstring?view=net-5.0

This is planned to be added or I can PR this feature?

Paulo Aboim Pinto

**Comment by MarchingCube** [comment]
I guess `Color.Parse` is an equivalent in this case?

**Comment by aboimpinto** [comment]
Yes .. it is ...
when we have this code in C# WPF code, now we have to refactor all those lines ...

**Comment by kekekeks** [comment]
>now we have to refactor all those lines ...

You can add your own `ColorConverter` class that would call `Color.Parse`
