### ISSUE TITLE
SolidColorBrush misses the IsFrozen and Freeze()

### ISSUE THREAD

**Issue by aboimpinto** [AvaloniaUI/Avalonia#5141]
I really never understand this functionality and personally, I never used but I'm trying to port some code from C# WPF to C# Avalonia and this was used.

Is this feature planned or will be not implemented at all? Is there a way to go around this feature?

You can find this feature in the Microsoft documentation
https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.solidcolorbrush?view=net-5.0  

Paulo Aboim Pinto

**Comment by maxkatz6** [comment]
I think ToImmutable is a valid replacement:
http://reference.avaloniaui.net/api/Avalonia.Media/SolidColorBrush/FB6D7F8E

**Comment by aboimpinto** [comment]
Can you explain how can I replace it?

**Comment by maxkatz6** [comment]
Well, it's better to start from what do you need to do with it.
Immutable resources in Avalonia has same advantages as WPF frozen resources with similar behavior.
Although in Avalonia it's used internally in the render system, and I don't think there are real benefits to rely on immutable resources here in the user code.

**Comment by maxkatz6** [comment]
Closing this for https://github.com/AvaloniaUI/Avalonia/issues/6387
