### ISSUE TITLE
How to make label text auto wrap?

### ISSUE THREAD

**Issue by dayAndnight2018** [AvaloniaUI/Avalonia#5143]

**Comment by Gillibald** [comment]
Just host a TextBlock inside the Label

`<Label><TextBlock/></Label>`

**Comment by Gillibald** [comment]
You can also define a `ContentTemplate` that is using a `TextBlock` with `TextWrapping="Wrap"`

**Comment by maxkatz6** [comment]
I haven't tested it, but code below also should work, and it will be more reusable.

Define style:
```
<Style Selector="Label.wrap > TextBlock">
   <Setter Property="TextWrapping" Value="Wrap" />
</Style>
```

And use it in another place:
```
<Label Classes="wrap" Content="Looooooooooong text" />
```

**Comment by dayAndnight2018** [comment]
> Just host a TextBlock inside the Label
> 
> `<Label><TextBlock/></Label>`

I find it when I use a textblock to make it word wrap, it works. But when there is a scrollviewer outside of the textblock, it not work no longer.

**Comment by dayAndnight2018** [comment]
> I haven't tested it, but code below also should work, and it will be more reusable.
> 
> Define style:
> 
> ```
> <Style Selector="Label.wrap > TextBlock">
>    <Setter Property="TextWrapping" Value="Wrap" />
> </Style>
> ```
> 
> And use it in another place:
> 
> ```
> <Label Classes="wrap" Content="Looooooooooong text" />
> ```

thanks, i will hava a try

**Comment by dayAndnight2018** [comment]
> > Just host a TextBlock inside the Label
> > `<Label><TextBlock/></Label>`
> 
> I find it when I use a textblock to make it word wrap, it works. But when there is a scrollviewer outside of the textblock, it not work no longer.

I have found its solution in #5020 , thanks anyway
