### ISSUE TITLE
"Call from invalid thread" if add item to ObservableCollection<T>

### ISSUE THREAD

**Issue by unominhtuan** [AvaloniaUI/Avalonia#5144]
Hello experts, I am a novice to Avalonia, I know this is a known issue. however, I have followed the manual ".UseReactiveUI()" in the program.cs file but the exception is still thrown. I have tried many methods but still cannot resolve this issue. Can someone help me with a solution? Thanks very much. Below is a picture of my code files

![Image 9](https://user-images.githubusercontent.com/43975116/101276823-47b34680-37e2-11eb-99e2-e9ea3b248a24.png)
Exception here.

![Image 53](https://user-images.githubusercontent.com/43975116/101276724-75e45680-37e1-11eb-9b52-d407abe804a1.png)
my viewmodel class and ObservableCollection

![Image 64](https://user-images.githubusercontent.com/43975116/101276733-84cb0900-37e1-11eb-895f-e5d28a8391cf.png)
my app.cs file

![Image 75](https://user-images.githubusercontent.com/43975116/101276743-90b6cb00-37e1-11eb-9fbd-29310bdd150b.png)
my program.cs file

I am using AvaloniaUi v0.9.11 because it is corert compatible

**Comment by FrankenApps** [comment]
Does this happen every time or only on some occasions?
Btw. there is CoreRT Support for preview6. See [here](https://github.com/AvaloniaUI/Avalonia/issues/1476#issuecomment-713406765) what you would need to do.

**Comment by kekekeks** [comment]
It looks like that your OnDeviceAdded callback happens on non-UI thread. Use `Dispatcher.UIThread.Invoke` to schedule a callback on the UI thread.

**Comment by unominhtuan** [comment]
> Điều này xảy ra thường xuyên hay chỉ trong một số trường hợp?
> Btw. có Hỗ trợ CoreRT để xem trước6. Xem [ở đây](https://github.com/AvaloniaUI/Avalonia/issues/1476#issuecomment-713406765) những gì bạn cần làm.
This problem happens every time


> Có vẻ như lệnh gọi lại OnDeviceAdded của bạn xảy ra trên chuỗi không phải giao diện người dùng. Sử dụng `Dispatcher.UIThread.Invoke`để lên lịch gọi lại trên chuỗi giao diện người dùng.

I will try this solution, however, another similar project of mine on wpf without the dispatcher. I will report the result in the next answer. Thank you for taking the time

**Comment by maxkatz6** [comment]
@unominhtuan WPF and UWP have same behavior, that doesn't allow to call INotifyPropertyChanged or INotifyCollectionChanged from non-UI thread, when it's used in the UI.
As mentioned above, you need to use Dispatcher (or SynhronizationContext as a high-level alternative). 
In case of ReactiveUI/DynamicData I believe it's also should be possible to do it in more pretty way, but I am not deeply familiar with it.

**Comment by ahopper** [comment]
wpf did have BindingOperations.EnableCollectionSynchronization on later versions which did allow cross thread use, Avalonia does not have this.

**Comment by unominhtuan** [comment]
Thanks everyone for taking time. I used Dispatcher.UIThread.InvokeAsync(). it works fine

**Comment by Kermel** [comment]
I seem to have a similar problem: My initialization is similar to what unominhtuan described, so:
1) I'm using the UseReactiveUI()
2) In my App.axaml.cs I initialize a MainWindow object, set its DataContext with a ViewModel and call window.Show()
3) In my Window I have a Menu with one MenuItem wher I bound a ReactiveCommand:

public ReactiveCommand<Unit, Unit> SwitchNextTheme { get; }

in the viewmodel's constructor:
SwitchNextTheme = ReactiveCommand.Create(() => styleManager.UseNextTheme());

Clicking on this "Switch theme" menu item ends in the afforementioned Exception.

I tried this:
SwitchNextTheme = ReactiveCommand.Create(() => styleManager.UseNextTheme(), outputScheduler: RxApp.TaskpoolScheduler);

Which doesn't fail, switches the theme but then the menu item is frozen and doesn't work anymore :-(

Please can you help me?

**Comment by Kermel** [comment]
NVM. Got it.

Just in case someboedy has the similar problem: I have configured my own DI container (Castle Windsor) overriding the default Splat Locator (that happens in my App.axaml.cs method OnFrameworkInitializationCompleted)

(something like this:
Locator.SetLocator(new CastleWindsorDependencyResolver(container));
Locator.CurrentMutable.InitializeSplat();
Locator.CurrentMutable.InitializeReactiveUI();
)

Which effectively overriden the stuff executed inside the UseReactiveUI() extension method used in initialization - the solution was to put it back after my registration override:

(i.e. to add
Locator.CurrentMutable.RegisterConstant(new AvaloniaActivationForViewFetcher(), typeof(IActivationForViewFetcher));
Locator.CurrentMutable.RegisterConstant(new AutoDataTemplateBindingHook(), typeof(IPropertyBindingHook));
RxApp.MainThreadScheduler = AvaloniaScheduler.Instance;
)

after my lines

**Comment by Gao996** [comment]
delegate void DoSomeThing();
public MainWindow()
{
DoSomeThing f = fun;
Dispatcher.UIThread.InvokeAsync(new Action(fun));
}
public void fun()
{
    //DoSomeThing
}

**Comment by maxkatz6** [comment]
Answered

**Comment by Flithor** [comment]
But I update the ObservableCollection of ViewModel in the other library whitch not referenced avalonia library... what should I do?

**Comment by timunie** [comment]
You probably need a wrapper class in your Avalonia project. Or use DynamicData which is shipped with reactice ui. It allows add and remove from async task iirc.

**Comment by Flithor** [comment]
EEEK..... That's pain!
Will binding async update be supported in the future?

**Comment by timunie** [comment]
Provide a minimum sample in a new Discussion and we will see if anything is possible
