### ISSUE TITLE
TextBox FontStyle = Italic has no effect on some Font Family

### ISSUE THREAD

**Issue by dayAndnight2018** [AvaloniaUI/Avalonia#5145]
The question is just what looks like the title.
For example:

`
<TextBlock FontFamily="Microsoft YaHei,Simsun,苹方-简,宋体-简" FontStyle="Italic">
      Hello, 你好
</TextBlock>
`

**Comment by kekekeks** [comment]
0.9 or 0.10-preview6?

cc: @Gillibald

**Comment by Gillibald** [comment]
Not all fonts have a italic variant. We currently don't emulate anything. If no italic variant is found the closest match is used.

**Comment by dayAndnight2018** [comment]
> 0.9 or 0.10-preview6?
> 
> cc: @Gillibald

0.10-preview6

**Comment by dayAndnight2018** [comment]
> Not all fonts have a italic variant. We currently don't emulate anything. If no italic variant is found the closest match is used.

maybe its due to the font itself
