### ISSUE TITLE
Disable maximize button in avilonia

### ISSUE THREAD

**Issue by rukhsar29** [AvaloniaUI/Avalonia#5147]
I want to disable maximize button or hide it.

**Comment by kekekeks** [comment]
You can set `CanResize` to `false`

**Comment by rukhsar29** [comment]
Not working in windows.

**Comment by jhofinger** [comment]
See https://github.com/AvaloniaUI/Avalonia/issues/437#issuecomment-493003671. Duplicate?

**Comment by Symbai** [comment]
> You can set `CanResize` to `false`

I can confirm this works fine in Windows 10, maximize button gets disabled. This issue can probably be closed

**Comment by Nickelony** [comment]
Well... on my side, the maximize button doesn't disappear with these settings, so this is still an issue.
Using Avalonia 0.10.10 and Windows 11 (22000.318)

**Comment by mysteryx93** [comment]
Minimize button is still enabled. WIth MessageBox.Avalonia, it's particularly an issue because the minimize/maximize buttons leave very little space for the MessageBox title! And you can minimize the MessageBox!?

**Comment by maxkatz6** [comment]
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/3422
