### ISSUE TITLE
Can I export Controls to Xaml?

### ISSUE THREAD

**Issue by whistyun** [AvaloniaUI/Avalonia#5148]
Like a `System.Windows.Markup.XamlWriter` in WPF,
Is there way to export Controls to Xaml?

**Comment by kekekeks** [comment]
You can try using XamlWriter from [Portable.Xaml](https://github.com/cwensley/Portable.Xaml), but it's not something that is explicitly supported.

**Comment by whistyun** [comment]
Thanks for reply. I try it.
