### ISSUE TITLE
ItemsRepeater: Inserting at front sometimes results in unrendered items

### ISSUE THREAD

**Issue by mike-ward** [AvaloniaUI/Avalonia#5151]
Items added to the front of an ItemsRepeater collection don't always get rendered. Resizing or scrolling reveals the unrendered items.

Example of before and after manually scrolling:

![TweetX Example](https://user-images.githubusercontent.com/567927/101533174-1f9b2300-395b-11eb-8c0b-ef3f7f78987e.png)

See https://github.com/microsoft/microsoft-ui-xaml/issues/3381 for more information.

See https://github.com/microsoft/microsoft-ui-xaml/pull/3699 for bug fix.

**Comment by mike-ward** [comment]
Darn! I'm seeing this issue in 0.10 release still.

**Comment by maxkatz6** [comment]
@mike-ward was it working for you with your PR https://github.com/AvaloniaUI/Avalonia/pull/5203 ?
You can reopen this issue

**Comment by mike-ward** [comment]
Likely not in retrospect. I just applied the change Microsoft made.
Odd, Github is not letting me reopen this.

**Comment by mike-ward** [comment]
I have a minimal sample app now that demonstrates this issue and other issues I'm experiencing with scrolling. I'll open a new issue with references to the demo program.

**Comment by maxkatz6** [comment]
@mike-ward I can reopen this one. Didn't know issue author can't do it.

**Comment by maxkatz6** [comment]
Ah, I see, you already opened new issue.

**Comment by FoggyFinder** [comment]
> @mike-ward I can reopen this one. Didn't know issue author can't do it.

Author can reopen an issue only if they closed it by themself.
