### ISSUE TITLE
Visual Studio Designer doesn't render properly

### ISSUE THREAD

**Issue by alan0428a** [AvaloniaUI/Avalonia#5157]
Hello team,

I've created the "Avalonia MVVM Application" template project from visual studio. I have not modified any code yet, but the MainWindow seems doesn't render properly.

It only renders the text element, but I think it should render a whole window(including title, icon, close button...).
![image](https://user-images.githubusercontent.com/23318971/101734942-0bdaf280-3afc-11eb-8d8d-bca3a49f91f3.png)

However, when I build and run the project, it renders correctly.
![image](https://user-images.githubusercontent.com/23318971/101735156-683e1200-3afc-11eb-882a-93b988fe5d9e.png)

Is there anything I am missing?

Visual Studio Version: Microsoft Visual Studio Professional 2019 Version 16.8.3
OS: Windows 10 Enterprise
Runtime: netcoreapp3.1

**Comment by kekekeks** [comment]
Should be fixed by https://github.com/AvaloniaUI/Avalonia/pull/4433

0.10.0-rc1 comes this week, so you should be able to safely use 0.10.0-preview6

**Comment by alan0428a** [comment]
@kekekeks I updated all related Avalonia packages to 0.10.0-rc1, but the designer exited unexpectedly. Below is the output from Avalonia Diagnostics.

![image](https://user-images.githubusercontent.com/23318971/101853544-ba357500-3b9a-11eb-93a3-ac753aaca699.png)


10:20:10.109 [Verbose]  Started AvaloniaDesigner.StartProcessAsync()
10:20:10.109 [Verbose]  Started PreviewerProcess.StartAsync()
10:20:10.109 [Information]  Starting previewer process for '"C:\Users\alanyu\source\repos\AvaloniaApplication1\AvaloniaApplication1\bin\Debug\netcoreapp3.1\AvaloniaApplication1.dll"'
10:20:10.110 [Debug]  > dotnet.exe "exec --runtimeconfig \"C:\Users\alanyu\source\repos\AvaloniaApplication1\AvaloniaApplication1\bin\Debug\netcoreapp3.1\AvaloniaApplication1.runtimeconfig.json\" --depsfile \"C:\Users\alanyu\source\repos\AvaloniaApplication1\AvaloniaApplication1\bin\Debug\netcoreapp3.1\AvaloniaApplication1.deps.json\" \"C:\Users\alanyu\.nuget\packages\avalonia\0.10.0-rc1\build\\..\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll\" --transport tcp-bson://127.0.0.1:64483/ \"C:\Users\alanyu\source\repos\AvaloniaApplication1\AvaloniaApplication1\bin\Debug\netcoreapp3.1\AvaloniaApplication1.dll\""
10:20:10.613 [Information] 24608 Started previewer process for '"C:\Users\alanyu\source\repos\AvaloniaApplication1\AvaloniaApplication1\bin\Debug\netcoreapp3.1\AvaloniaApplication1.dll"'. Waiting for connection to be initialized.
10:20:11.213 [Error] 24608 <= "Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Avalonia.Base, Version=0.10.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)"
10:20:11.214 [Error] 24608 <= "File name: 'Avalonia.Base, Version=0.10.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'"
10:20:11.215 [Error] 24608 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args)"
10:20:12.673 [Information]  Process exited while waiting for connection to be initialized.
10:20:12.674 [Debug]  Process.StartAsync exited with error
System.ApplicationException: The previewer process exited unexpectedly with code -532462766.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at AvaloniaVS.Services.PreviewerProcess.<StartAsync>d__30.MoveNext() in D:\a\1\s\AvaloniaVS\Services\PreviewerProcess.cs:line 232
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<StartProcessAsync>d__55.MoveNext() in D:\a\1\s\AvaloniaVS\Views\AvaloniaDesigner.xaml.cs:line 441
10:20:12.674 [Verbose]  Finished AvaloniaDesigner.StartProcessAsync()
10:20:12.674 [Information]  Process exited
10:20:12.675 [Verbose]  Started PreviewerProcess.Stop()
10:20:12.676 [Information]  Stopping previewer process
10:20:12.677 [Verbose]  Finished PreviewerProcess.Stop()

Below is my project setting.
```<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.10.0-rc1" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.0-rc1" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.10.0-rc1" />
  </ItemGroup>
</Project>
```

**Comment by kekekeks** [comment]
Delete `bin`/`obj` and rebuild

**Comment by alan0428a** [comment]
Thanks for the reply! The designer works as expected now 👍 
However, I have to remove `using Avalonia.Logging.Serilog;` in Program.cs and modify `LogToDebug()` to `LogToTrace()` to make it successfully compiled. And I also need to remove `this.AttachDevTools()` in `MainWindow.axaml.cs`. Is this the correct syntax in 0.10.0 releases?

My `program.cs` :

```using Avalonia;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.ReactiveUI;
using System;

namespace AvaloniaApplication1
{
    class Program
    {
        // Initialization code. Don't use any Avalonia, third-party APIs or any
        // SynchronizationContext-reliant code before AppMain is called: things aren't initialized
        // yet and stuff might break.
        public static void Main(string[] args) => BuildAvaloniaApp()
            .StartWithClassicDesktopLifetime(args);

        // Avalonia configuration, don't remove; also used by visual designer.
        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToTrace()
                .UseReactiveUI();
    }
}

**Comment by maxkatz6** [comment]
Take a look
https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes

**Comment by alan0428a** [comment]
Awesome! I was trying to find that link LOL
Everything works smoothly now, thanks for the help!
