### ISSUE TITLE
[Mac-OS11] HasSystemDecorations=False + WindowState.Minimized is broken

### ISSUE THREAD

**Issue by kamronbatman** [AvaloniaUI/Avalonia#5158]
I made a simple app with the following properties:
```
    HasSystemDecorations="False"
```
that has a button and attached this click event:
```cs
this.FindControl<Button>("MinimizeButton").Click += delegate { WindowState = WindowState.Minimized; };
```

Unfortunately it doesn't work. If I enable system decorations, it works fine.
I did make a workaround, but it is kind of weird:
```cs
      this.FindControl<Button>("MinimizeButton").Click += delegate
      {
          HasSystemDecorations = true;
          WindowState = WindowState.Minimized;
          HasSystemDecorations = false;
      };
```
There is however something odd about restoring a minimized window (I found out after using that work around). The first time it is restored, the window moves considerably down (vertically) on the screen. Probably can take care of this in another issue though so we aren't tracking too many things here. I assume this is all related to big sur :(

Operating System: OS 11 (Big Sur)
Avalonia Version: 0.9.12
.NET Version: 5.0.100

**Comment by kekekeks** [comment]
@danwalmsley apparently big slur has broken the previous method to get it working

**Comment by maxkatz6** [comment]
Please ping me or @danwalmsley if it's still reproducible
