### ISSUE TITLE
dll missing when Application run on ubuntu

### ISSUE THREAD

**Issue by Junaid-Amjad** [AvaloniaUI/Avalonia#5159]
Hi, I created a small program in windows using some libraries and it worked fine but when i run the program in ubuntu, I got exception of the missing dll. I have searched this issue on internet and most of them said to change the .dll to .so for linux environment. Is this apply for Avalonia or i am going something wrong in this situation. Image is attached below for reference.
![dllMissing](https://user-images.githubusercontent.com/75033105/101739775-d200f080-3ae9-11eb-9bbb-39082897e86d.png)

**Comment by kekekeks** [comment]
You are trying to P/Invoke an windows-only API. Consider using a cross-platform library.
