### ISSUE TITLE
Possible memory Leak, Perspex holding on to Custom Control

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#516]
This has manifested in Avalon Studio, you can use this commit which is an attempt to investigate the problem.

https://github.com/VitalElement/AvalonStudio/commit/42250de2f2eff9a95e8d6cff4ef670da130f1b6c

Step1)
run Avalon studio and open sample project.

2) open a code file, wait 5 seconds it will be closed automatically.

3) Pause and use memory inspector tool to see what is keeping references to AvalonStudio.TextEditor.TextEditor

also EditorViewModel (although I suspect that is just held because TextEditor is held.)

Apologies in advance if it turns out this is not caused by Perspex.

**Comment by danwalmsley** [comment]
After looking in DotMemory it really looks like it must be something in Perspex.

**Comment by danwalmsley** [comment]
![image](https://cloud.githubusercontent.com/assets/4672627/14620465/bd033270-05b4-11e6-92bf-e9df2adbcd6a.png)


![image](https://cloud.githubusercontent.com/assets/4672627/14620458/b6f50a5c-05b4-11e6-9350-24144be59754.png)

**Comment by danwalmsley** [comment]
Have done pr with fixes.

**Comment by grokys** [comment]
I can't see the PR. Have you submitted it?

**Comment by danwalmsley** [comment]
#519 - has a bad title, but that was before I understood more about what was going on.

**Comment by danwalmsley** [comment]
Shall I close this issue?

**Comment by grokys** [comment]
If it's fixed, yeah!
