### ISSUE TITLE
Converter in Styles.Resources gives me exception during build

### ISSUE THREAD

**Issue by aboimpinto** [AvaloniaUI/Avalonia#5162]
Hello, 

on the project 
https://github.com/aboimpinto/MaterialDesign.Avalonia
on the file
https://github.com/aboimpinto/MaterialDesign.Avalonia/blob/master/source/MaterialDesign.PackIcon/Assets/Generic.xaml

I'm loading a converter into my <Style.Resources> tag
when I compile the project I get this error: 

![image](https://user-images.githubusercontent.com/1231687/101773939-bdbef280-3aed-11eb-95cd-7c3b4bbae521.png)

Am I doing something wrong with the converters? I took a look at the documentation and, apart from saying that Avalonia ship if own implementation due to the fact is not available in dotnetstandards, there is no other concerns/differences when using it.
Is this a bug or just miss ussage?

best wishes
Paulo Aboim Pinto

**Comment by kekekeks** [comment]
`local:GeometryConveter`, not `localGeometryConveter`

**Comment by aboimpinto** [comment]
this is stupid ... I'm sorry
