### ISSUE TITLE
Designer does not support "using:" for a namespace from a separate or internal assembly

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaUI/Avalonia#5167]
Hello!

Designer does not support "using:" for a namespace from a separate or internal assembly

[xaml example](https://github.com/rstm-sf/AvaloniaGraphControl/blob/86280930a3d43fb7f3b13fea4105b78fd7052793/sample/MainWindow.xaml#L5)

> [Error] 16040 UpdateXamlResult error
System.Xaml.XamlException: 'Unable to resolve type GraphPanel from namespace using:AvaloniaGraphControl Line 48, position 10.' Line number '48' and line position '10'.
**From VS Exstension 0.9.12**

0.10.0-rc1

**Comment by kekekeks** [comment]
That's probably caused by assembly not being loaded. As a workaround try adding `typeof(GraphPanel).GetTypeInfo() ` to `BuildAvaloniaApp` to force it to be loaded.
