### ISSUE TITLE
Introduce Flyout concept

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#5172]
# Proposal: Introduce Flyout concept
> A flyout is a light dismiss container that can show arbitrary UI as its content. Flyouts can contain other flyouts or context menus to create a nested experience. ([UWP docs](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/flyouts))

## Summary
Our old WPF-like ContextMenu API limits us and doesn't allow to use anything more complex that simple menu.
In same time Flyout has more use cases where it can be effectively used without low-level Popup.

## Rationale
* We need ability to set any custom content inside of context menu (e.g. old MenuFlyout, new Flyout with a content, custom user flyout and maybe NativeMenuFlyout in the future).
* We need ability to use MenuFlyout (currently named as ContextMenu control) in other scenarios, not only "control right-click". For instance, "Button.Flyout" should be displayed on button left-click without any additional code in code behind.
* Current ContextMenu can't be extended to work with native menus. With new FlyoutBase API we can provide some space for that. Low priority, I guess.
* For TextBox we can implement richer context flyout instead of simple menu (as UWP did with [TextCommandBarFlyout](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/command-bar-flyout))

## Scope
| Capability | Priority |
| :---------- | :------- |
| API that can work with either menu control (MenuFlyout) or content control (Flyout) | Must |
| Deprecate ContextMenu property and control  | Should (see open question number 1) |
| Allow MenuFlyout with native menu implementation | Should (see open question number 3) |
| API similar to UWP | Should |

## Important Notes
API proposal without dependency properties (part of UWP API):
```csharp
public abstract class FlyoutBase : AvaloniaObject
{
    bool IsOpen { get; }
    FlyoutPlacementMode Placement { get; set; } // Top, Bottom, Left, Right, Full
    Control? Target { get; set; }
    
    void ShowAt(Control);
    void Hide(); 
    virtual Control CreatePresenter();

    event EventHandler Closed;
    event EventHandler<CancelEventArgs> Closing;
    event EventHandler Opened;
    event EventHandler<CancelEventArgs> Opening;

    static FlyoutBase GetAttachedFlyout(Control);
    static void SetAttachedFlyout(Control, FlyoutBase);
    static void ShowAttachedFlyout(Control);
}

public class Flyout : FlyoutBase
{
    Classes FlyoutPresenterClasses { get; }
    Control Content { get; set; }
}

public class MenuFlyout : FlyoutBase
{
    IList<MenuItem> Items { get; }
}

public class Control
{
    FlyoutBase ContextFlyout { get; set; }
}

public class Button : Control
{
    FlyoutBase Flyout { get; set; }
}

```

And usage from xaml:
```xaml
<Button Content="Hi!">
    <Button.Flyout>
       <MenuFlyout Placement="Bottom">
          <MenuItem Header="I am classic menu item, but show on button left-click." />
       </MenuFlyout>
    </Button.Flyout>
    <Button.ContextFlyout>
       <Flyout Placement="Top">
          <TextBlock Text="I will be shown on button right-click." />
       </Flyout>
    </Button.ContextFlyout>
</Button>
```

Another notes:
1. FlyoutBase is not a control, thus it has not a logical/visual parent and its one instance can be shared between controls. 
2. One FlyoutBase has one internal Popup, which is created lazily with content from CreatePresenter.

## Open Questions
1. Instead of deprecating old functionality, we can introduce Flyout functionality and related attached properties in optional package (Avalonia.WinUI or something like that).
2. UWP doesn't have flexibility in Flyout-popup position customizations, including offsets. In same time our old ContextMenu does, so probably we might want to extend API with this.
3. FlyoutBase uses CreatePresenter method to show controls in the Popup. In similar way we can add another optional method to override, that will return platform specific handler for native implementation with Show and Hide methods - it can be helpful for native menu implementation. Related: https://github.com/AvaloniaUI/Avalonia/issues/3855
4. Difference between Popup and Flyout may not be clear enough. But even with simple Popup we can't put custom content inside of ContextMenu property.

**Comment by robloo** [comment]
Note that Flyout is also a pre-requisite to implement SplitButton the same as WinUI.

> Instead of deprecating old functionality, we can introduce Flyout functionality and related attached properties in optional package (Avalonia.WinUI or something like that).

I think Flyout, like all other controls in WPF/WinUI, is fair game to add to vanilla Avalonia. There shouldn't be any conflicts doing something like this.

> UWP doesn't have flexibility in Flyout-popup position customizations, including offsets. In same time our old ContextMenu does, so probably we might want to extend API with this.

Great idea and it shouldn't be breaking to any code coming over from WinUI.

**Comment by Splitwirez** [comment]
I suppose this isn't very helpful, but...can I just say that I'm really, *really* excited about the possibility of this feature happening?

**Comment by amwx** [comment]
I'd like to work on this, unless something is blocking it or someone else has already started. If not, I'll get a PR started and we can continue the discussion there.

**Comment by maxkatz6** [comment]
@amwx I started some time ago, but haven't much time to continues working on it. And planned to find it somewhere in next months. I pushed my changes here - https://github.com/AvaloniaUI/Avalonia/tree/feature/flyouts

The biggest problem so far is to update ContextMenu to use MenuFlyout internally, so biggest part of code can be reused.
Also I haven't tested this branch with latest changes in the master.
If you want to continue work on it - I will be happy to help if you need, and review PR.

**Comment by amwx** [comment]
> 
> 
> @amwx I started some time ago, but haven't much time to continues working on it. And planned to find it somewhere in next months. I pushed my changes here - https://github.com/AvaloniaUI/Avalonia/tree/feature/flyouts
> 
> The biggest problem so far is to update ContextMenu to use MenuFlyout internally, so biggest part of code can be reused.
> Also I haven't tested this branch with latest changes in the master.
> If you want to continue work on it - I will be happy to help if you need, and review PR.

Cool. I've done some work on this too, so I'll just combine everything. It might be worth splitting into 2 PRs, one with just a base implementation of Flyout, and a second to deal with MenuFlyout as that's a little more involved.

**Comment by maxkatz6** [comment]
Done!

**Comment by RomanSoloweow** [comment]
As I understand Flyout concept now, this is just a more advanced ContextMenu. And can I somehow use it to implement, for example, the context toolbar as in the screenshot. Is the event that opens and closes this element configurable? @maxkatz6 
![image](https://user-images.githubusercontent.com/29205560/116119226-ddcf0700-a6c6-11eb-83f7-f99fef152936.png)

**Comment by maxkatz6** [comment]
> As I understand Flyout concept now, this is just a more advanced ContextMenu

It's more like high-level popup, that can replace old-ContextMenu.
You can put any content into Flyout and invoke it on ContextFlyout:
```
<Control.ContextFlyout>
    <Flyout>
        <local:MyToolBar />
    </Flyout>
</Control.ContextFlyout>
```

And you can use API from this proposal to open Flyout/MenuFlyout instance manually on your event.

**Comment by RomanSoloweow** [comment]
Can I use Flyout and ContextMenu at the same time?

**Comment by maxkatz6** [comment]
@RomanSoloweow no, why would you need it?

**Comment by RomanSoloweow** [comment]
@maxkatz6 in many graphic editors, the context menu and the tool bar exist at the same time.

The context menu appears when you press the right mouse button, and the tool bar appears if the element is selected and remains until the selection is cleared.

![image](https://user-images.githubusercontent.com/29205560/116365711-30ffa180-a80e-11eb-9c6b-00c7bfd46bda.png)
![image](https://user-images.githubusercontent.com/29205560/116365236-bb93d100-a80d-11eb-926d-3ff233ff0c7d.png)

**Comment by maxkatz6** [comment]
You will need to disable light dismiss for the tooltip flyout/popup, so it won't be closed.

**Comment by RomanSoloweow** [comment]
@maxkatz6 can I use Flyout as component and ContextMenu at the same time. If Flyout is outside ContextFlyout?
```
<views:ActivityView.ContextPad>
    <Flyout>
    </Flyout>
</views:ActivityView.ContextPad>
```

**Comment by maxkatz6** [comment]
Flyout can be outside of ContextFlyout. 
Use following methods to attach flyout and show it
```
    static FlyoutBase GetAttachedFlyout(Control);
    static void SetAttachedFlyout(Control, FlyoutBase);
    static void ShowAttachedFlyout(Control);
```
Or you can do it without attaching with instance method:
```
    void ShowAt(Control);
```

**Comment by MarcoMuellner** [comment]
Hi!

Is there any news on this?

**Comment by maxkatz6** [comment]
@MarcoMuellner what's news? It's merged and closed.
We don't have good documentation yet though. But it's the same as in UWP, so you can take a look there.

**Comment by MarcoMuellner** [comment]
@maxkatz6 Ah, sorry, i was just looking up how Flyouts work on Avalonia, so i stumbled upon this issue. Seeing that there was no documentation on it on the page, and this just being closed i assumed that nothing happened with this Issue. Apologies.
