### ISSUE TITLE
Where did all the beautiful things go?

### ISSUE THREAD

**Issue by nitanmarcel** [AvaloniaUI/Avalonia#5173]
Hi! I remember using Avalonia a long time and what I liked about it besides the thing that it's cross platform was the controls it had, but coming back to it looks like everything is default un-styled buttons. I remember it having custom Window with themable status bars and a set of beautiful looking buttons and other controls.

Are they moved in a separate package or there's now a theme available with the elements mentioned above?

**Comment by PieroCastillo** [comment]
you can try the Fluent Theme, is available on Avalonia 0.10.0 rc1, also this version includes BoxShadow(for Border), and adds the AcrylicBorder

**Comment by alan0428a** [comment]
> you can try the Fluent Theme, is available on Avalonia 0.10.0 rc1, also this version includes BoxShadow(for Border), and adds the AcrylicBorder

Is there any example to import the theme?

**Comment by PieroCastillo** [comment]
mmm, put this on your App.xaml
```xml
		 <StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseLight.xaml"/> 
		 <StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/FluentLight.xaml"/> 
```

BaseLight.xaml can be replaced for BaseDark.xaml to change the theme from Light to Dark, or vice versa

**Comment by alan0428a** [comment]
> mmm, put this on your App.xaml
> 
> ```
> 		 <StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseLight.xaml"/> 
> 		 <StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/FluentLight.xaml"/> 
> ```
> 
> BaseLight.xaml can be replaced for BaseDark.xaml to change the theme from Light to Dark, or vice versa

Thanks for the reply. But shouldn't the URI be?
```
<StyleInclude Source="avares://Avalonia.Themes.Fluent/FluentLight.xaml"/>
<StyleInclude Source="avares://Avalonia.Themes.Fluent/FluentDark.xaml"/>
```

**Comment by Gillibald** [comment]
It is even simpler now. Put this into your `Application.Styles`: `<FluentTheme Mode="Dark"/>`

**Comment by PieroCastillo** [comment]
> > mmm, put this on your App.xaml
> > ```
> > 		 <StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseLight.xaml"/> 
> > 		 <StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/FluentLight.xaml"/> 
> > ```
> > 
> > 
> > BaseLight.xaml can be replaced for BaseDark.xaml to change the theme from Light to Dark, or vice versa
> 
> Thanks for the reply. But shouldn't the URI be?
> 
> ```
> <StyleInclude Source="avares://Avalonia.Themes.Fluent/FluentLight.xaml"/>
> <StyleInclude Source="avares://Avalonia.Themes.Fluent/FluentDark.xaml"/>
> ```

well, when the code what I showed to you I have no problem

**Comment by nitanmarcel** [comment]
> you can try the Fluent Theme, is available on Avalonia 0.10.0 rc1, also this version includes BoxShadow(for Border), and adds the AcrylicBorder

Awesome thanks. Tho another question I have, are the old styles compatible with the new version if I use them for previous versions?

**Comment by nitanmarcel** [comment]
Oh, I took a look at the fluent design and I think they are the same to what I had before:

![IMG_20201214_110054_306](https://user-images.githubusercontent.com/41646249/102061155-c5d3a680-3dfb-11eb-86c4-0cb8e6e658fe.jpg)

**Comment by maxkatz6** [comment]
> Tho another question I have, are the old styles compatible with the new version if I use them for previous versions?

In Avalonia 0.10 there are two themes: Default (old) and Fluent (new). Default in 0.10 is compatible with Default from previous 0.9 version. 

> Oh, I took a look at the fluent design and I think they are the same to what I had before.

Your screenshot is not from app with Avalonia, and there wasn't similar build-in theme before, although it is possible to make same design.

**Comment by nitanmarcel** [comment]
> > Tho another question I have, are the old styles compatible with the new version if I use them for previous versions?
> 
> In Avalonia 0.10 there are two themes: Default (old) and Fluent (new). Default in 0.10 is compatible with Default from previous 0.9 version.
> 
> > Oh, I took a look at the fluent design and I think they are the same to what I had before.
> 
> Your screenshot is not from app with Avalonia, and there wasn't similar build-in theme before, although it is possible to make same design.

Hmm, probably, I don't know why I have a feeling that it's from this framework. Probably the theming part got me thinking that

**Comment by nitanmarcel** [comment]
> you can try the Fluent Theme, is available on Avalonia 0.10.0 rc1, also this version includes BoxShadow(for Border), and adds the AcrylicBorder

Any overview of the code that needs to be changed to port the template from the latest version to the pre-release one? I've updated to `0.10.0 rc` and I removed the functions that are not available in the preview version but I still get this error:

**Comment by alan0428a** [comment]
Maybe you can follow the issue  #5157 I created before. I've updated Avalonia to 0.10.0-rc1.

**Comment by nitanmarcel** [comment]
> Maybe you can follow the issue #5157 I created before. I've updated Avalonia to 0.10.0-rc1.

Nah, the problem happens at `.StartWithClassicDesktopLifetime(args)` in:

```
        public static void Main(string[] args) => BuildAvaloniaApp()
            .StartWithClassicDesktopLifetime(args);
```

**Comment by nitanmarcel** [comment]
> Maybe you can follow the issue #5157 I created before. I've updated Avalonia to 0.10.0-rc1.

Thanks for the link. I don't know why it didn't worked before but now works perfectly :)

**Comment by maxkatz6** [comment]
I believe, it was answered
