### ISSUE TITLE
Style selecting a user control that inherits from a base control

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#5174]
I want to apply a style to a custom usercontrol that inherits from Panel like this:
```csharp
    public class CheckBoxControlledPanel : Panel, IStyleable
    {
        Type IStyleable.StyleKey => typeof(Panel);
```
```xml
    <Style Selector="Panel.WriteReq">
      <Setter Property="IsEnabled" Value="..."/>
    </Style>
    <uc:CheckBoxControlledPanel Classes="WriteReq">
```

But my Style does not seem to apply. Is this simply not possible or am I doing something wrong?

**Comment by danwalmsley** [comment]
Use is(Panel) 

http://avaloniaui.net/docs/styles/selectors

`<Style Selector=":is(Button)">`

**Comment by derekantrican** [comment]
Thanks. `<Style Selector=":is(Panel)">` seems to work. After that suggestion, I found that `<Style Selector="Panel">` also works. But none work when combined with the class selector (eg `:is(Panel).WriteReq` or `Panel.WriteReq`). Would this then be a bug?

**Comment by maxkatz6** [comment]
What Avalonia version do you use?

**Comment by derekantrican** [comment]
0.9.12

**Comment by maxkatz6** [comment]
@derekantrican I tried to reproduce the issue, but it works fine for me.
Can you try this project below? Probably we are missing some important detail.

[AvaloniaApplication8.zip](https://github.com/AvaloniaUI/Avalonia/files/5685951/AvaloniaApplication8.zip)

**Comment by derekantrican** [comment]
Yeah, that works for me. Let me try to get a minimum-reproducible version of my app

**Comment by maxkatz6** [comment]
@derekantrican
> I guess that overrides the style's binding?

Exactly. When you set value with a property setter or from xaml while declaring element (<CheckBox IsEnabled=True>), that value will have Local priority, which is higher than Style priority.
In your example you can use SetValue method that allows to pass specific priority.
```csharp
// Replace that
control.IsEnabled = enabled;
// With this
control.SetValue(Control.IsEnabledProperty, enabled, Avalonia.Data.BindingPriority.Style);
```

**Comment by derekantrican** [comment]
Thanks! I didn't know about `SetValue`. I see that this gives priority to the Style binding. Is there a way for both the Style binding and the code-behind `SetValue` to work or is it not possible for both to compete for the same binding? I'd like the end result to be Style takes highest priority but if Style IsEnabled is `true`, then the `SetValue` takes second priority. Maybe my idea of `IsEnabledOverride` should be the way to go?

**Comment by danwalmsley** [comment]
`I know - it's not possible to select a usercontrol with a style`

yes it's possible...

1) add an xmlns statement for the namespace where the control lives.

2) add a style selector like: `ns|MyUserControl`
