### ISSUE TITLE
Avalonia UserControl in WinForms application

### ISSUE THREAD

**Issue by RoboMod** [AvaloniaUI/Avalonia#5175]
I'm trying to use Avalonia embedded into a WinForms application. I added the ControlHost, added my UserControl to the content and used `AppBuilder.Configure<Avalonia.Application>().UseWin32().UseDirect2D1().SetupWithoutStarting();` to bring up Avalonia. But sadly the control keeps to be empty (size is zero or when defining a size the control is filled black). I noticed that the VisualRoot is null and the flag IsAttachedToVisualTree says "false". Does anyone have a tip for me?

**Comment by kekekeks** [comment]
1) UseDirect2D1 isn't needed for winforms, it's in the sample app for WPF, for winforms you can use Skia
2) as of the current master the renderer lifetime has to be managed manually, see https://github.com/AvaloniaUI/Avalonia/issues/4951

**Comment by RoboMod** [comment]
Okay, thanks. 


>     1. UseDirect2D1 isn't needed for winforms, it's in the sample app for WPF, for winforms you can use Skia

I switched to Skia but I can not see that it changed anything.

>     2. as of the current master the renderer lifetime has to be managed manually, see #4951

My problem is that the control does not have a VisualRoot. So `GetVisualRoot()` returns null.

**Comment by kekekeks** [comment]
Are you sure that you've configured your App correctly? Like, added a theme and other stuff?

**Comment by RoboMod** [comment]
Wuhu! Adding themes solved the problem. Thank you very much!

**Comment by vchelaru** [comment]
I know this issue has been closed, but could anyone post an example of how to accomplish this?

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/tree/master/samples/interop/WindowsInteropTest
