### ISSUE TITLE
Unable to run projects from the Samples folder

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#5176]
I got these errors each time I attempt to build `Avalonia` from the source:

```
8>\Avalonia\Avalonia\samples\Sandbox\Program.cs(9,24,9,38): error CS0012: The type 'AppBuilderBase<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Avalonia.Controls, Version=0.9.999.0, Culture=neutral, PublicKeyToken=null'.
8>\Avalonia\Avalonia\samples\Sandbox\Program.cs(9,24,9,38): error CS0117: 'AppBuilder' does not contain a definition for 'Configure'
8>Done building project "Sandbox.csproj" -- FAILED.
```

Some thoughts:

I see that `Avalonia.Win32` project has an alarm mark on `MicroComGenerator` dependent project:

![Avalonia1](https://user-images.githubusercontent.com/16510738/102060854-61b0e280-3dfb-11eb-9d4c-6d3c9e1e2d47.jpg)

but it builds without any errors/warnings.

**Comment by maxkatz6** [comment]
I have this error after enabling/disabling assembly signing in the props file. Probably VisualStudio doesn't rebuild some projects with new signing info. Deleting bin/obj folders and rebuilding everything helps me.

**Comment by FoggyFinder** [comment]
> Deleting bin/obj folders and rebuilding everything helps me.

yeah. I tried to delete literally every .bin/,obj folders then I received a lot of different errors here and there but finally it started to work.
Anyway it feels like something is wrong with dependencies.
