### ISSUE TITLE
A few images won't display

### ISSUE THREAD

**Issue by FloridaMatt** [AvaloniaUI/Avalonia#5179]
I'm having problems with a few images, but can't identify a defining characteristic.  When an Image Source is loaded from a BitMap containing one of the problem images, it appears to load, but the resulting image is not displayed.  And if it's an image of some size (say, 3k x 2k) it takes several seconds to do this.  Ditto for an ImageBrush (which makes some sense). Other images taken with the same iPhone around the same time work fine. 
Avalonia 0.9.12
MacOS Big Sur 11.1
.Net 5.0.101
VS for Mac 8.8.3 build 16 (with the debug shim fix from .Net5.0.1)
[20201205.113816.Jpeg.zip](https://github.com/AvaloniaUI/Avalonia/files/5698013/20201205.113816.Jpeg.zip)

**Comment by kekekeks** [comment]
Try increasing the GPU budget:
```cs
.With(new SkiaOptions { MaxGpuResourceSizeBytes = 0x10000000 }
```

**Comment by FloridaMatt** [comment]
(a) How do I do that on my Mac?  BTW the problem images are the same pixel sizes as the non-problem images.

(b) digging deeper, The Inspector in Mac's Preview app finds that all the problem images I've examined so far are either "Orientation 6 (Rotated 90 CCW)" or Orientation 3 (Rotated 180)".  The ok ones I looked at are "Orientation 1 (Normal).  Mac's Finder and Preview both display all the images correctly.

A side note:  If I change the imagebrush bitmapinterpolation mode from high quality to low, some of the problem portrait images (the orientation 6 ones) now appear but sideways and cropped square...

**Comment by kekekeks** [comment]
I think we don't currently handle image orientation. You might need to decode and rotate images manually: https://github.com/mono/SkiaSharp/issues/836#issuecomment-584895517

**Comment by FloridaMatt** [comment]
This needs to be submitted to Skia as a bug.  The current implementation clearly identifies the situation, but neither handles it correctly nor raises an "unimplemented" exception.  

Since the Avalonia Bitmap object does not expose the orientation of the picture, this bug forces me to load *every* picture into some Exif-capable software such as ImageMagick, fix it if needed, export it to a stream, and then finally load it into the Bitmap.
