### ISSUE TITLE
Watermark of multiline textbox is not where text goes

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#5184]
Screenshot:

![image](https://user-images.githubusercontent.com/1558019/102414517-88158000-3fab-11eb-97f9-01b43ff2eacb.png)

Textbox:

```xml
<TextBox Width="NaN" Height="50" TextWrapping="Wrap" AcceptsReturn="True"
          Text="{Binding Description}" Watermark="New description text" Margin="5"/>
```

When I start typing in the textbox, the text starts at the very top of the textbox. I would expect the watermark to be in the same location

**Comment by kekekeks** [comment]
@Gillibald

**Comment by Gillibald** [comment]
Probably just missing a VerticalAlignment Top
