### ISSUE TITLE
Source code of showcase in README.md?

### ISSUE THREAD

**Issue by KallenW** [AvaloniaUI/Avalonia#5185]
[https://github.com/AvaloniaUI/Avalonia#showcase](Showcase)

It will be great to learn these code samples.

**Comment by FrankenApps** [comment]
These can be found [here](https://github.com/AvaloniaUI/XamlControlsGallery) and [here](https://github.com/jmacato/Synfonia).

**Comment by grokys** [comment]
We should definitely add links to the readme for these.

**Comment by danwalmsley** [comment]
Adding now and closing issue.
