### ISSUE TITLE
https://github.com/AvaloniaUI/Avalonia/wiki/Projects-that-are-using-Avalonia is broken with missing images ?

### ISSUE THREAD

**Issue by fforjan** [AvaloniaUI/Avalonia#5186]
![image](https://user-images.githubusercontent.com/601810/102499989-affaf700-4030-11eb-9694-6a15c11c1ad2.png)
Found in the web browser :
![image](https://user-images.githubusercontent.com/601810/102500135-d6209700-4030-11eb-9c79-f4a17abae035.png)

**Comment by PieroCastillo** [comment]
mmm try to check your internet connection or the browser, it shows to me
![image](https://user-images.githubusercontent.com/39932324/102524753-67aafb80-4067-11eb-88d4-6cf9b6ad5ec5.png)

**Comment by fforjan** [comment]
![image](https://user-images.githubusercontent.com/601810/102532734-44794f80-4059-11eb-9fc8-24cba56091c9.png)

**Comment by fforjan** [comment]
@PieroCastillo  which browser are you using ?

**Comment by PieroCastillo** [comment]
Now I use the latest stable version of Microsoft Edge Chromium, I never have problems with the github web page

**Comment by fforjan** [comment]
Problem appeared this week

**Comment by PieroCastillo** [comment]
so strange, try deleting the cache memory on temp directory

**Comment by rstm-sf** [comment]
This answer should help you https://github.community/t/refused-to-load-the-font-url-because-it-violates-the-following-content-security-policy-directive/1613/14

It can also be cookies or some extensions

**Comment by fforjan** [comment]
interesting, I see the same behavior for Chrome, Edge and not IE.
there was a VPN update change last week so potentially it could be that.

@rstm-sf  the image is loading perfectly, but I can see the CSP header in the request which force to not load the  image :

![image](https://user-images.githubusercontent.com/601810/102543550-52829c80-4068-11eb-92ee-f2516dfd4b94.png)

I'm surprised that my company computer is doing that kind of trick
