### ISSUE TITLE
Open context menu from Command crashes on rc1

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#5187]
In preview6 this worked, however with rc1 it crash the program:

Sample:

```
<Button
              IsEnabled="{Binding SlicerFile.CreatedThumbnailsCount}"
              ToolTip.Tip="Save properties to a file or clipboard"
              Command="{Binding #PropertiesSaveContextMenu.Open}">
              <Button.ContextMenu>
                <ContextMenu Name="PropertiesSaveContextMenu" PlacementMode="Bottom">
                  <MenuItem
                    Command="{Binding OnClickPropertiesSaveFile}"
                    Header="To File">
                    <MenuItem.Icon>
                      <Image Source="/Assets/Icons/file-image-16x16.png"/>
                    </MenuItem.Icon>
                  </MenuItem>

                  <MenuItem
                    Command="{Binding OnClickPropertiesSaveClipboard}"
                    Header="To Clipboard">
                    <MenuItem.Icon>
                      <Image Source="/Assets/Icons/clipboard-16x16.png"/>
                    </MenuItem.Icon>
                  </MenuItem>

                </ContextMenu>
              </Button.ContextMenu>
              <StackPanel Orientation="Horizontal">
                <Image Source="/Assets/Icons/save-16x16.png" />
                <TextBlock Text=" ⮟"/>
              </StackPanel>
            </Button>
```

Problem:

`Command="{Binding #PropertiesSaveContextMenu.Open}"`

As soon i left click button it crashes. Right click still working and open the context menu.
Is there anyway or property that i can set to make left click also open the context menu without the extra code?

> Message: Specified method is not supported.

Strack Trace:
```
   at Avalonia.Controls.ContextMenu.Open()
   at Avalonia.Data.Converters.MethodToCommandConverter.Execute(Object parameter)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__28_9(InputElement x, PointerReleasedEventArgs e)
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 147
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 26
```

**Comment by danwalmsley** [comment]
Are you using any dependencies that also use Avalonia?

Specified method is not supported.

may be caused by binary incompatibility.

**Comment by sn4k3** [comment]
Using all these:
![image](https://user-images.githubusercontent.com/113281/102543911-ed509a80-40ab-11eb-84cd-4401bd0fdd3e.png)

But button comes from stock avalonia

**Comment by maxkatz6** [comment]
From your code.
This line:
> Command="{Binding #PropertiesSaveContextMenu.Open}">

Tries to execute this method, which is not supported:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/ContextMenu.cs#L249

You need to use your code behind (or probably it should be possible with [BehaviorsSDK](https://github.com/wieslawsoltes/AvaloniaBehaviors)) to execute property method ContextMenu.Open(Control) where you pass your button as a parameter.

**Comment by maxkatz6** [comment]
ContextMenu is planned to be reworked with Flyouts -see https://github.com/AvaloniaUI/Avalonia/issues/5172
But not for 0.10 release.

**Comment by sn4k3** [comment]
> You need to use your code behind (or probably it should be possible with [BehaviorsSDK](https://github.com/wieslawsoltes/AvaloniaBehaviors)) to execute property method ContextMenu.Open(Control) where you pass your button as a parameter.

I've a look at Behaviours, but **CallMethodAction** gives no way to put parameters? Or i should use another Behaviour class?

**Comment by maxkatz6** [comment]
Probably it doesn't, I am not sure about that. You also can create your own action, if you will.

**Comment by sn4k3** [comment]
Ok, i will run code behind. Thanks

**Comment by sn4k3** [comment]
Add this function to solve the problem:

```C#
        public void OpenContextMenu(string name)
        {
            var menu = this.FindControl<ContextMenu>($"{name}ContextMenu");
            if (menu is null) return;
            var parent = this.FindControl<Button>($"{name}Button");
            if (parent is null) return;
            menu.Open(parent);
        }
```

Why Open() got discontinued? If it has a parent why not redirect open with the parent?

**Comment by grokys** [comment]
> Why Open() got discontinued? If it has a parent why not redirect open with the parent?

A context menu can now be attached to multiple controls. We could probably just choose the first of those controls and show it on that I guess.

**Comment by sn4k3** [comment]
> A context menu can now be attached to multiple controls. We could probably just choose the first of those controls and show it on that I guess.

That would be safer, otherwise other applications that might use the **Open()** will face same problem. Not to mention the extra complexity of having to pass a parent argument that requires code behind and name attribution
Another approach would raise exception if more than 1 parent attached, but my vote goes for open at first parent

**Comment by kekekeks** [comment]
@grokys I think we should just remove the method already, it's been a while.

**Comment by grokys** [comment]
I need to look at the code to make sure it's possible, but would you be opposed to keeping the method and:

1. Opening on the first attached control; or
2. Opening on the attached control if attached to a single control, throwing otherwise?

If we can do that, it would make the API for the common case more friendly.

**Comment by donandren** [comment]
```C#
item.ContextMenu.Open();// NotSupported
item.ContextMenu.Open(null);//working 
```
 why not `ContextMenu.Open()` call `ContextMenu.Open(null)` instead throw NotSupported?
