### ISSUE TITLE
How to access Button Tooltip from C#?

### ISSUE THREAD

**Issue by alessandrofrancesconi** [AvaloniaUI/Avalonia#5188]
Say I have
`<Button x:Name="MyButton" ToolTip.Tip="Tooltip text" Content="Test"/> `

And in C#
`var btn = this.Get<Button>("MyButton");`

How can I access/edit `Tooltip.Tip` from C#?
Because `btn.Tooltip` does not exists!

**Comment by kekekeks** [comment]
`ToolTip.SetTip(btn, "Text");`

Google "attached properties"

**Comment by alessandrofrancesconi** [comment]
Worked, thanks!
