### ISSUE TITLE
Unable to load 'libSkiaSharp' Linux (Manjaro)

### ISSUE THREAD

**Issue by MarioGK** [AvaloniaUI/Avalonia#5190]
**Describe the bug**
While trying to run the project in debug mode the app is giving a `System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' ` error code, i tried installing skiasharp from the official arch repository didnt solve the issue, the runtime folder is populated with the libSkiSharp.so for every system and i still get the error.
OBS: The project works normally on Windows

**To Reproduce**
Create a project using the official avalonia mvvm template
`dotnet new avalonia.mvvm -o MyApp`
Then update it to .net 5
Build it and try to run it with debug mode or release mode gives the same error

**Expected behavior**
Is that the app at least starts and load the libSkiaSharp

**Screenshots**
![Screenshot from 2020-12-18 17-51-22](https://user-images.githubusercontent.com/8379079/102660556-f9933100-4159-11eb-9eb3-21752b8b383a.png)

**Desktop (please complete the following information):**
- IDE: Rider
 - OS:  Manjaro
 - Version Latest(20.2)

**Additional context**
-Avalonia Preview 0.10.0 RC1
-Avalonia.Native  0.10.0 RC1

**Comment by kekekeks** [comment]
1) find your libSkiaSharp.so location (usually in `~/.nuget/packages/skiasharp.nativeassets.linux/2.80.2/runtimes/linux-x64/native/libSkiaSharp.so`)
2) run `lddtree /path/to/libSkiaSharp.so`

**Comment by danwalmsley** [comment]
> 1. find your libSkiaSharp.so location (usually in `~/.nuget/packages/skiasharp.nativeassets.linux/2.80.2/runtimes/linux-x64/native/libSkiaSharp.so`)
> 2. run `lddtree /path/to/libSkiaSharp.so`

This will tell you the dependencies and probably something is missing...

so the error is not that `libSkiaSharp.so` is missing... its that your system has something it depends on that is missing.

**Comment by MarioGK** [comment]
@kekekeks @danwalmsley Thanks for the help, here is the output
![Screenshot from 2020-12-18 21-54-51](https://user-images.githubusercontent.com/8379079/102676314-bcd83180-417b-11eb-8a4e-9b5f94dfb55b.png)

**Comment by kekekeks** [comment]
`/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 --verify /path/to/skiasharp.so`
`/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 --list /path/to/skiasharp.so`

Also check if a hello-world app using SkiaSharp 2.80.2 works on your machine.

**Comment by MarioGK** [comment]
Running `/lib/ld-linux-x86-64.so.2 --verify libSkiaSharp.so` returns nothing on the terminal`

Running `/lib/ld-linux-x86-64.so.2 --list libSkiaSharp.so` returns this
```
~/.../net5.0/linux-x64 >>> /lib/ld-linux-x86-64.so.2 --list libSkiaSharp.so
	linux-vdso.so.1 (0x00007ffc6ef94000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fab6a5fe000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fab6a5f8000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fab6a5de000)
	libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007fab6a55a000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007fab6a52b000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007fab6a457000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007fab6a40a000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fab6a3d3000)
	libwebp.so.7 => /usr/lib/libwebp.so.7 (0x00007fab6a363000)
	libwebpdemux.so.2 => /usr/lib/libwebpdemux.so.2 (0x00007fab6a35d000)
	libwebpmux.so.3 => /usr/lib/libwebpmux.so.3 (0x00007fab6a351000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fab6a174000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fab6a02c000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fab6a012000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fab69e49000)
	/lib/ld-linux-x86-64.so.2 (0x00007fab6abd3000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007fab69e36000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007fab69d67000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007fab69d40000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007fab69c0c000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007fab69b9a000)
```

@kekekeks Sorry i could not find a pre compiled the hello-world app so i couldnt run it, tried publishing my app and i got the same error

**Comment by MarioGK** [comment]
Any ideas on what should i do to fix this?

**Comment by kekekeks** [comment]
Please, check if a hello-world app using SkiaSharp 2.80.2 works on your machine.

**Comment by MarioGK** [comment]
@kekekeks Hello, thanks for all the help the problem was that i was using the dotnet-sdk from the SNAP store, i installed the version [from AUR](https://aur.archlinux.org/packages/dotnet-sdk-bin/) and it started working, it might be a good idea to add somewhere in the readme to not use snap version of the dotnet sdk.

**Comment by kekekeks** [comment]
Ah, snap, devils kith and kin. Never use it for *anything* related to software development, it's broken by design.

**Comment by EngRajabi** [comment]
How can I fix such a problem in Docker?

**Comment by kekekeks** [comment]
@EngRajabi for docker you usually need to add libfontconfig to your image.

**Comment by EngRajabi** [comment]
If it needs to be fixed without installing this package and only with your Docker and version?
