### ISSUE TITLE
[Question] Can I detect whether an application use Fluent theme?

### ISSUE THREAD

**Issue by whistyun** [AvaloniaUI/Avalonia#5191]
I make a library to provide a Control class that uses resource-key declared in Avalonia.Themes.Default.

Some reousrce-keys such as 'FontSizeNormal' and 'ThemeAccentColor' are not declared in Avalonia.Themes.Fluent, so I have to use a different resource-keys when Fluent theme is used.

Is there a way to detect which theme to use?

**Comment by kekekeks** [comment]
@maxkatz6  @danwalmsley I think we should provide compatibility key names from the fluent theme as well

**Comment by maxkatz6** [comment]
@kekekeks in that case resources with old keys should be DynamicResource, which is not supported now. I.e. one can't write something like:
```<DynamicResource x:Key="FontSizeNormal" ResourceKey="ControlContentThemeFontSize"  />```

I am not sure if simple StaticResource is enough for compatibility between old and new resources.

**Comment by maxkatz6** [comment]
@whistyun for our controls we decided earlier to use separated styles for each theme.
For instance what we have for DataGrid - https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.Controls.DataGrid/Themes

> Is there a way to detect which theme to use?

@danwalmsley can we provide something like that? I don't think we can rely on already registered resources to detect theme.

**Comment by whistyun** [comment]
@maxkatz6 
Thanks for reply.

I realized that I could look into `Application.Styles`, so I think I can determine it with the following code and change Style.
...But is it correct method? Is there anything else I have to look at?

```cs
foreach (var style in Application.Current.Styles)
{
    if (style is FluentTheme)
    {
        // <FluentTheme Mode="Dark|Light" />
    }
    else if (style is StyleInclude incld
              && incld.Source.Host == "Avalonia.Themes.Fluent")
    {
        // perhaps <StyleInclude Source="avares://Avalonia.Themes.Fluent/***.xaml"/>
    }
}
```

**Comment by maxkatz6** [comment]
@whistyun is should work.
However it will fail when user want to fork Fluent theme and make some changes with it - it will be another assembly with another host. It's unlikely though.

**Comment by whistyun** [comment]
Thanks for advice and checking my code.
