### ISSUE TITLE
NullReferenceException when using TwoWay binding with indexer to null DataContext

### ISSUE THREAD

**Issue by antrv** [AvaloniaUI/Avalonia#5194]
**Describe the bug**
NullReferenceException in StringIndexerNode.cs line 137, StringIndexerNode class PropertyType property getter
when binding DataGridTextColumn to the indexer property.

The sample project to reproduce the issue is here https://github.com/antrv/samples/tree/master/Avalonia-Issue-5194

**To Reproduce**
1. Clone the repo, build and run the project
2. See error

**Expected behavior**
No exception. DataGrid is displayed with 2 columns.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Avalonia Version 0.10.0-rc1 (also reproducible in 0.9.12)

**Comment by maxkatz6** [comment]
> A sample repro code and details will be added later today.

I think we will need it, otherwise I can't reproduce.

**Comment by antrv** [comment]
Please find the sample project here https://github.com/antrv/samples/tree/master/Avalonia-Issue-5194

**Comment by maxkatz6** [comment]
@antrv thanks. It's not related to DataGrid, but definitely a bug in Avalonia.
As a workaround you can use Mode=OneWay in your bindings.

**Comment by maxkatz6** [comment]
Tests to reproduce:
```
[Fact] // Success
public void TwoWay_Binding_Should_Not_Fail_With_Null_DataContext()
{
    var target = new TextBlock();
    target.DataContext = null;

    target.Bind(TextBlock.TextProperty, new Binding("Missing", BindingMode.TwoWay));
}

[Fact] // Fails
public void TwoWay_Binding_Should_Not_Fail_With_Null_DataContext_Indexer()
{
    var target = new TextBlock();
    target.DataContext = null;

    target.Bind(TextBlock.TextProperty, new Binding("[0]", BindingMode.TwoWay));
}
```
