### ISSUE TITLE
Proposal: Smooth scrolling for ScrollView

### ISSUE THREAD

**Issue by hez2010** [AvaloniaUI/Avalonia#5195]
**Describe the solution you'd like**
While using a precise touchpad or touch screen:

1. Add momentum to scrolling
2. When the scroll overflows, allow to continue scrolling with damping, and return after the scroll gesture ends

**Proposed effect**
1. scrolling momentum

![1](https://user-images.githubusercontent.com/14960345/102717596-50496800-431e-11eb-9740-5c1c56d7dada.gif)

2. scroll with damping after overflow, and return after the scroll gesture ends

![2](https://user-images.githubusercontent.com/14960345/102717591-4cb5e100-431e-11eb-8cf2-2e2e5003f3fc.gif)

**Comment by kekekeks** [comment]
Have you tried enabling touch input support? ScrollViewer should already have inertial scrolling when interacted via touch gestures.

**Comment by grokys** [comment]
This is definitely implemented, so closing.

**Comment by julian-baumann** [comment]
Is this overflow behavior implemented as well?
When I reach the end of my content, the scrolling just suddenly stops. Would be great to have this bounce effect for touch interactions. It makes scrolling on a touch screen much more enjoyable.
