### ISSUE TITLE
Grid auto with inside DataGrid is not scaling when add items (rc1)

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#5199]
Note: This wasn't a problem in preview6 but experiencing this on rc1
I have a grid with RowDefinitions="Auto,Auto,Auto,Auto,*,Auto,**Auto**"
In the last row i have a data grid which get populated every layer change and on file load. 
Program starts with that datagrid empty, so row is resized to the empty datagrid correctly, but once items are added it no longer scale again, it requires a layer change to clear items and populate the grid over again, then we start to see some items, if i mouse whell over datagrid items starts to show and push grid up, draging vertical bar also works. When grid reach it maximum height due the populated items it works correctly even if i remove all items and repopulate again (file reload)

Video: https://youtu.be/MtyPGoixsg0
Parent grid: https://github.com/sn4k3/UVtools/blob/00179581dd95f00e25b9d15d0343c39c7017d79d/UVtools.WPF/MainWindow.axaml#L317
DataGrid: https://github.com/sn4k3/UVtools/blob/00179581dd95f00e25b9d15d0343c39c7017d79d/UVtools.WPF/MainWindow.axaml#L478

I also tried to use the 3 invalidate methods after populate the datagrid with the items, but no effect

**Comment by maxkatz6** [comment]
Probably related
https://github.com/AvaloniaUI/Avalonia/pull/5161/files
