### ISSUE TITLE
How to custom the ScrollViewer style of the inner scroll bar?

### ISSUE THREAD

**Issue by dayAndnight2018** [AvaloniaUI/Avalonia#5208]
As the title, How can I custom the border radius, background, width, foreground and etc of the scroll bar of a scrollviewer control?

**Comment by maxkatz6** [comment]
ScrollBar is a range-based control, that can be restyled in same way as any other control.
Styling docs: https://avaloniaui.net/docs/styles/styles
Default theme ScrollBar styles: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Default/ScrollBar.xaml
Fluent theme ScrollBar styled: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/ScrollBar.xaml
