### ISSUE TITLE
Handle  SharpDX.SharpDXException: HRESULT: [0x8899000C], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_RECREATE_TARGET/RecreateTarget], Message: There has been a presentation error that may be recoverable. The caller needs to recreate, rerender the entire frame, and reattempt present. I'

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#521]
This occurs every now and again in direct2d, no exact way to reproduce it, happens during render loop...
 
seems if you catch this error and re-render application will work fine.

I can repro in Avalon Studio by running my app and using it heavily for about 10 - 20 minutes.

**Comment by jkoritzinsky** [comment]
Can you still reproduce this? I'm thinking of setting up some debug settings to start making this easier to trace.
