### ISSUE TITLE
Add buildTransitive in nuget

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#5210]
We need to do that before 0.10 since it will technically be a breaking change

**Comment by kekekeks** [comment]
@danwalmsley

**Comment by PieroCastillo** [comment]
what is that?

**Comment by maxkatz6** [comment]
@PieroCastillo https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior

**Comment by workgroupengineering** [comment]
if you want, I add it to all PR #5202.

**Comment by kekekeks** [comment]
@workgroupengineering thanks, just make sure to keep the old `build` directory as well (or add import proxies) to keep compatibility with old SDKs.

**Comment by danwalmsley** [comment]
fixed.
