### ISSUE TITLE
Adding RoutedViewHost into my Window throws exceptions

### ISSUE THREAD

**Issue by Kermel** [AvaloniaUI/Avalonia#5215]
**Describe the bug**
I wanted to introduce Routing in my application so I did the steps described in https://avaloniaui.net/docs/reactiveui/routing. But when I place the RoutedViewHost into my Window xaml, for example as follows:
```
<Window xmlns="https://github.com/avaloniaui"
 ...
xmlns:rxui="http://reactiveui.net"
...
<rxui:RoutedViewHost Grid.Row="0" Router="{Binding Router}">
   <rxui:RoutedViewHost.DefaultContent>
      <TextBlock Text="Default content"
         HorizontalAlignment="Center"
         VerticalAlignment="Center" />
   </rxui:RoutedViewHost.DefaultContent>
</rxui:RoutedViewHost>
```
Running my application  throws the following exception:
ArgumentException: "Don't know how to detect when Avalonia.ReactiveUI.RoutedViewHost is activated/deactivated, you may need to implement IActivationForViewFetcher"

(this occurs when instantiating the main window, stack trace point to the line with "<rxui:RoutedViewHost Grid.Row="0" Router="{Binding Router}">"

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [e.g. 0.9.12] Avalonia, Avalonia.Desktop, Avalonia.ReactiveUI

Can you tell me how to do it?

**Comment by maxkatz6** [comment]
Do you have UseReactiveUI() in your BuildAvaloniaApp method?

**Comment by Kermel** [comment]
Yes

**Comment by maxkatz6** [comment]
Your window also should be ReactiveWindow, not just Avalonia.Window.
Maybe with some project example it might be easier to help.

**Comment by Kermel** [comment]
The Window is ReactiveWindow :(. I will try to prepare some example...

actually I have found a few links regarding this exception but all pointed to some old bug in Reactive.UI hhat has been solved back in 2018 (it was related to tje Design View). Strange thing is that the design view in my project doesnt work (there are some exceptionďs in the avalonia diagnostic logs)
