### ISSUE TITLE
There makes no sense using defaultExtension of SaveFileDialog

### ISSUE THREAD

**Issue by dayAndnight2018** [AvaloniaUI/Avalonia#5216]
just like what in the following image:

![image](https://user-images.githubusercontent.com/44399091/103063120-4b6d0880-45eb-11eb-8fbc-b1a3845cca03.png)

it is no extension info when call saveFileDialog entity's showDialog function, it return the file name with no extensions.

The develop environment is macOS, Rider IDE.

**Comment by dayAndnight2018** [comment]
what I mean is in a winform or wpf application, the dialog will return the file name with given extension automatically.

**Comment by Mikolaytis** [comment]
also default extension is not used in avalonia code on windows. DefaultExtension is not selected by default in windows system dialog in the extensions dropdown.

**Comment by timunie** [comment]
@Stannieman issue is still open and looks like the same you have, unless it's not on mac on your end. So I guess another issue is not needed. However, if you have time to investigate the issue further, a PR maybe welcome.

**Comment by Stannieman** [comment]
It is on macOS, only with StorageProvider instead of classic FileDialog. Will have a look if I can find the problem.
