### ISSUE TITLE
Under Centos, how did one Avalonia project call the executable file generated by the other Avalonia project? For example, Thread.start ("xxx.exe") under Windows.

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#5224]
Under Centos, how did one Avalonia project call the executable file generated by the other Avalonia project? For example, Thread.start ("xxx.exe") under Windows.

**Comment by kekekeks** [comment]
`Process.Start("xxx")` without `exe`.

**Comment by wuzlai** [comment]
> `Process.Start("/full/path/to/xxx")` without `exe`.

thank you,you are right.
