### ISSUE TITLE
After running the avalonia project on ubuntu20.04 and successfully initializing, no window appears (first axaml)

### ISSUE THREAD

**Issue by Aaronlog** [AvaloniaUI/Avalonia#5227]
**Describe the bug**
The Avalonia project ran without a display window

**To Reproduce**
1.Run the command dotnet project.dll on Ubuntu
2.No display window (normally it should be)

**Expected behavior**
When it runs successfully, a window should pop up

**Screenshots**
null

**Desktop (please complete the following information):**
 Ubuntu20.04

**Additional context**
null

**Comment by sakya** [comment]
Can you provide your project? I use Avalonia on Ubuntu 20.04 and it works.
