### ISSUE TITLE
[RC1] Debian 10.5 Openbox on Xorg have no Screen.Primary

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#5228]
Related to: https://github.com/sn4k3/UVtools/issues/115

This come from a customer using my software, it seens Screen.Primary on his system is null. To troubleshoot the problem i sent him a custom build to find out that primary is null.

```C#
public void UpdateMaxWindowsSize()
        {
            Console.WriteLine($"Settings is null?: {Settings is null}");
            Console.WriteLine($"Settings.General is null?: {Settings.General is null}");
            Console.WriteLine($"Settings.General is null?: {Settings.General is null}");
            Console.WriteLine($"Screens is null?: {Screens is null}");
            Console.WriteLine($"ScreenCount: {Screens.ScreenCount}");
            Console.WriteLine($"Screens.Primary is null?: {Screens.Primary is null}");
            App.MaxWindowSize = new System.Drawing.Size(
                Settings.General.WindowsTakeIntoAccountScreenScaling ? (int)(Screens.Primary.WorkingArea.Width / Screens.Primary.PixelDensity) : Screens.Primary.WorkingArea.Width,
                Settings.General.WindowsTakeIntoAccountScreenScaling ? (int)(Screens.Primary.WorkingArea.Height / Screens.Primary.PixelDensity) : Screens.Primary.WorkingArea.Height);
        }
```

His results:

> Settings is null?: False
> Settings.General is null?: False
> Settings.General is null?: False
> Screens is null?: False
> ScreenCount: 2
> Screens.Primary is null?: True
> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
>    at UVtools.WPF.MainWindow.UpdateMaxWindowsSize() in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\MainWindow.axaml.cs:line 463
>    at UVtools.WPF.MainWindow.OnOpened(EventArgs e) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\MainWindow.axaml.cs:line 471
>    at Avalonia.Controls.Window.ShowCore(Window parent)
>    at Avalonia.Controls.Window.Show()
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
>    at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
>    at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 26
> Aborted

I call that funcion on app startup once inside a **protected override void OnOpened(EventArgs e)** from mainwindow.

First time i'm getting this problem, as on other OS'es are working good, Unbuntu and mint working fine with GNOME and Cinnamon

To fix this i will fallback to access to first item on Screens if primary is null

**Comment by kekekeks** [comment]
`xrandr`, `xrandr --version`, `xrandr --listproviders`, `xrandr --listmonitors`

**Comment by sn4k3** [comment]
> `xrandr`, `xrandr --version`, `xrandr --listproviders`, `xrandr --listmonitors`

His output:

xrandr

```
Screen 0: minimum 320 x 200, current 7680 x 2160, maximum 16384 x 16384
VGA-1 disconnected primary (normal left inverted right x axis y axis)
DP-1 connected 3840x2160+3840+0 (normal left inverted right x axis y axis) 621mm x 341mm
   3840x2160     60.00*+  30.00    30.00    24.00    29.97    23.98  
   1920x1080     60.00    50.00    59.94    30.00    24.00    29.97    23.98  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.95  
   1280x1024     75.02    60.02  
   1440x900      59.89  
   1280x960      60.00  
   1280x800      59.81  
   1152x864      75.00  
   1280x768      59.87  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
DP-2-1 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 621mm x 341mm
   3840x2160     60.00*+  30.00    30.00    24.00    29.97    23.98  
   1920x1080     60.00    50.00    59.94    30.00    24.00    29.97    23.98  
   1680x1050     59.95  
   1280x1024     75.02    60.02  
   1440x900      59.89  
   1280x960      60.00  
   1280x800      59.81  
   1152x864      75.00  
   1280x768      59.87  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
DP-2-2 disconnected (normal left inverted right x axis y axis)
DP-2-3 disconnected (normal left inverted right x axis y axis)
```
xrandr --version

```
xrandr program version       1.5.0
Server reports RandR version 1.5
```

xrandr --listproviders

```
Providers: number : 1
Provider 0: id: 0x4a cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 8 associated providers: 0 name:modesetting
```
xrandr --listmonitors

```
Monitors: 2
 0: +DP-1 3840/621x2160/341+3840+0  DP-1
 1: +DP-2-1 3840/621x2160/341+0+0  DP-2-1
```

**Comment by kekekeks** [comment]
Primary screen is disconnected. So there is no active primary screen.

**Comment by sn4k3** [comment]
Ok so the in avalonia the primary screen is always the port 0 from gfx?

**Comment by kekekeks** [comment]
It's the output marked as primary. As you can see in your xrandr output the primary screen is disconnected
>VGA-1 *disconnected* **_primary_** (normal left inverted right x axis y axis)
>DP-1 connected 3840x2160+3840+0 (normal left inverted right x axis y axis) 621mm x 341mm
>DP-2-1 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 621mm x 341mm

**Comment by sn4k3** [comment]
Thank you, will inform the user. Closing this.
