### ISSUE TITLE
Cancellation Token disposed on MacOS

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#5229]
**Describe the bug**

I am using the following code:

```csharp
public static T InvokeSyncOnUIThread<T>(Func<Task<T>> thingToInvoke)
{
    T result = default;

    using (CancellationTokenSource source = new CancellationTokenSource())
    {
        if (Dispatcher.UIThread.CheckAccess())
        {
            thingToInvoke().ContinueWith(t =>
            {
                result = t.Result;
                source.Cancel();
            });

            Dispatcher.UIThread.MainLoop(source.Token);
        }
        else
        {
            Dispatcher.UIThread.InvokeAsync(() =>
            {
                thingToInvoke().ContinueWith(t =>
                {
                    result = t.Result;
                    source.Cancel();
                });
            });

            while (!source.IsCancellationRequested) { } //Loop until dialog is closed
        }
    }

    return result;
}
```

This works fine in Windows, but in MacOS (High Sierra) I get the following exceptions (all seem to be caused by the first `source.Cancel();` line as `Dispatcher.UIThread.MainLoop(source.Token);` seems to have already disposed the token).

They all have the same outer exception, which makes sense:
- Exception: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

And different inner exceptions:

- Inner Exception: System.ObjectDisposedException: The CancellationTokenSource has been disposed
- Inner Exception: SharpGen.Runtime.SharpGenException: HRESULT: [0x80004005], Module: [General], ApiCode: [E_FAIL/Unspecified error], Message: Unknown

**To Reproduce**
Code above provided, but if requested I can make a minimum reproducible example

**Expected behavior**
Expected that `Dispatcher.UIThread.MainLoop(source.Token);` does not dispose the token on Mac

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra 10.13.6
 - Avalonia Version 0.9.12

**Comment by maxkatz6** [comment]
Can you check that code on 0.10?
I am just curious, SharpGenTools is not used there anymore IIRC.

**Comment by maxkatz6** [comment]
@danwalmsley @kekekeks

**Comment by kekekeks** [comment]
You aren't supposed to call `MainLoop` multiple times. The only time it should be called in `Program.Main` either directly or through `StartWithClassicDesktopLifetime`

**Comment by derekantrican** [comment]
Working on getting a 0.10.0 example to see if I can reproduce

@kekekeks - what would be the recommended way to do this instead? This is what was recommended to me in https://github.com/AvaloniaUI/Avalonia/issues/4810#issuecomment-704259221

**Comment by derekantrican** [comment]
Ok, I was able to upgrade my project to 0.10.0-rc1 just enough to get this tested. It does still reproduce with 0.10.0-rc1. The SharpGenTools exception is now replaced with:

- Inner Exception: System.Runtime.InteropServices.COMException (0x80004005): RunLoop failed

**Comment by kekekeks** [comment]
ShowDialog is returning Task for a reason. One is not supposed to wait for it synchronously.

Not sure why RunLoop is allowed to be called on other platforms, we don't support reentrancy, so calling it the second time will most like cause other issues as well.

**Comment by derekantrican** [comment]
I did a lot of reworking of my code to await async dialogs rather than trying to call them synchronously. I *think* I got it all converted over correctly. But I'm glad to say that I'm now no longer seeing the issue
