### ISSUE TITLE
Unable to pull in Xaml Namespaces for Prism (Probably other libraries too)

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#523]
I tried using prism in a Perspex project.

In xaml I need to use this namespace.. either Perspex or OmniXaml cant find this:
xmlns:prism="http://www.codeplex.com/prism"

Then if I change to a clr-namespace... omnixaml  throws showing it can't find the types inside that assembly.

**Comment by grokys** [comment]
Yeah, this will be because we don't have access to the System.Xaml attributes that other libraries use to declare an `xmlns` from PCL. I imagine that there should be a way to work around this using reflection however. 

We should probably support the attributes from all 3 places that they can come from: Perspex, System.Xaml and OmniXaml.

**Comment by jkoritzinsky** [comment]
One way would to be to have OmniXaml search by default for assemblies with an attribute with the type  name `XmlnsNamespaceAttribute` so it can attempt to auto-load no matter the backend.

**Comment by jogibear9988** [comment]
Maybe you could use some Code from here: https://github.com/icsharpcode/WpfDesigner/blob/master/WpfDesign.XamlDom/Project/XamlTypeFinder.cs

**Comment by danwalmsley** [comment]
@jkoritzinsky @grokys this is probably fixed now we use Portable.Xaml?

**Comment by jkoritzinsky** [comment]
I don't think so. Portable.Xaml has its own Xaml attributes (it doesn't use or type forward to the ones in `System.Xaml`) so it wouldn't discover the types from Prism, etc.

**Comment by cm4ker** [comment]
I think it's the same issue https://github.com/AvaloniaUI/DataGrid/issues/6. 
For using custom xmlns you have to define it by XmlnsDefinition. We need module loading system.

**Comment by jmacato** [comment]
potentially fixed by https://github.com/cwensley/Portable.Xaml/pull/112
I'd suggest we update our Portable.Xaml submodule
