### ISSUE TITLE
Problems with Window Customing, the full screen Button is showed when the pointer is over

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#5231]
Description:
This is a minimal bug, occurs with the follow code:
```csharp
public MainWindow()
{
    ExtendClientAreaToDecorationsHint = true;
    ExtendClientAreaTitleBarHeightHint = -1;

    TransparencyLevelHint = WindowTransparencyLevel.AcrylicBlur;
}

protected override void OnApplyTemplate(TemplateAppliedEventArgs e)
{
     base.OnApplyTemplate(e);
     ExtendClientAreaChromeHints =
               ExtendClientAreaChromeHints.PreferSystemChrome |
               ExtendClientAreaChromeHints.OSXThickTitleBar;
}
```

**To Reproduce**
1. Go to the title bar buttons.
2. Put the cursor over next to the Minimize Button.
3. You should see a Color without some button.
4. Press it, the window is going to look like fullscreen.

Screenshots:
![image](https://user-images.githubusercontent.com/39932324/103248575-235a0e00-4939-11eb-91a1-5562193cad14.png)
![image](https://user-images.githubusercontent.com/39932324/103248596-471d5400-4939-11eb-990c-281e464b6942.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Avalonia 0.10.0-rc1

**Comment by maxkatz6** [comment]
Was it fixed?
