### ISSUE TITLE
How does Avalonia implement the Linux taskbar tray

### ISSUE THREAD

**Issue by Aaronlog** [AvaloniaUI/Avalonia#5232]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't find a solution

**Describe the solution you'd like**
Indirectly operate the Avalonia project by implementing the taskbar tray

**Describe alternatives you've considered**

**Additional context**

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/2649
