### ISSUE TITLE
TextBox not support fallback font

### ISSUE THREAD

**Issue by WenjunHuang** [AvaloniaUI/Avalonia#5233]
**Describe the bug**
I used the following code to set the font family of a TextBox to show Chinese characters. But it just uses the first font and ignored the second.
`<TextBox Width="200"
                         FontFamily="Arial, Microsoft YaHei UI"
                         /> `
But the TextBlock control works with this fallback font family setting correctly.
               
**Desktop (please complete the following information):**
 - OS: Windows
 - Version [e.g. 0.10.0-rc1 or 0.9.12]

**Comment by maxkatz6** [comment]
TextBox doesn't supports fallback font. But there is a PR for that:
https://github.com/AvaloniaUI/Avalonia/pull/4893

More info:
https://github.com/AvaloniaUI/Avalonia/issues/4708#issuecomment-696211267

**Comment by WenjunHuang** [comment]
> TextBox doesn't supports fallback font. But there is a PR for that:
> #4893
> 
> More info:
> [#4708 (comment)](https://github.com/AvaloniaUI/Avalonia/issues/4708#issuecomment-696211267)

Got it, Thank you.
