### ISSUE TITLE
Setting Wait cursor does not work on OSX

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#5234]
The following line (executed in Window codebehind) works on Windows but not OSX:

```csharp
this.Cursor = new Cursor(StandardCursorType.Wait);
```
*A variety of other StandardCursorType values DO work on OSX*

Avalonia 0.9.12

**Comment by FloridaMatt** [comment]
Same problem on MacOS Big Sur 11.1 and NetCore 5.0.102

**Comment by kekekeks** [comment]
IIRC some cursors don't work because there is no corresponding native cursor https://developer.apple.com/documentation/appkit/nscursor?language=objc 
Which one should be mapped to `Wait`?

**Comment by kekekeks** [comment]
From apple docs:
>The Application Kit provides two ready-made cursors for commonly used cursor images. You can retrieve these cursors by using the arrowCursor and IBeamCursor class methods. There is no NSCursor instance for the wait cursor, because **the system automatically displays it at the appropriate times**

By "appropriate times" they mean "the application is blocking it's main thread"

**Comment by FloridaMatt** [comment]
I have a case where clicking a button results in a couple seconds of code execution -- just a touch less than it takes for MacOS to pop up the beachball, but just long enough for an impatient person to think the click didn't work.  I can switch the cursor to the Hand, or one of a couple other values, but It would be really useful if Avalonia could provide an Hourglass (or even a mini non-animated beachball).  Is there any way I can create my own cursor image?

**Comment by grokys** [comment]
@FloridaMatt there's an open PR which adds support for custom cursors, but it's waiting on... OSX support! I don't currently have a Mac so I can't implement it unfortunately. I don't know if you'd be in a position to finish it off?

**Comment by danwalmsley** [comment]
> From apple docs:
> 
> > The Application Kit provides two ready-made cursors for commonly used cursor images. You can retrieve these cursors by using the arrowCursor and IBeamCursor class methods. There is no NSCursor instance for the wait cursor, because **the system automatically displays it at the appropriate times**
> 
> By "appropriate times" they mean "the application is blocking it's main thread"

Can confirm, beachball as its referred to on OSX usually indicates a problem... more than please wait.

**Comment by FloridaMatt** [comment]
I'd love to help out, but I'm a Mac newbie, transitioning last year after a couple decades of Windows (I still have my March 93 win32 sdk cd).  I've yet to xcode anything and am still struggling to grok Avalonia.  If only Apple had stayed with Pascal...

**Comment by maxkatz6** [comment]
Custom cursors are now supported in a stable branch. As an alternative for mac not supporting some native types.
