### ISSUE TITLE
DataTemplate without DataType will cause stackoverflow in ContentControl

### ISSUE THREAD

**Issue by flyingxu** [AvaloniaUI/Avalonia#524]
https://github.com/Perspex/Perspex/blob/master/samples/BindingTest/MainWindow.xaml#L62

```
    <ContentControl Content="{Binding SelectedItems[0]}">
          <ContentControl.DataTemplates>
            <DataTemplate DataType="vm:TestItem"> //change this line
              <local:TestItemView></local:TestItemView> //and this line
            </DataTemplate>
          </ContentControl.DataTemplates>
        </ContentControl>
```
When two lines of the code is changed to
```
            <DataTemplate> //remove the DataType
              <Button>1</Button> //change to Button with Text "1"
```
Then a stackoverflow exception will be thrown when running the BindingTest project. (You should switch to ListBox tab to see the excetion.)

The changes are pretty tricky:
1) remove the DataType. 
if the DataType is not removed, everything is fine. (It should be valid xaml if DataType is removed.)
2)Button with Text "1"
if the button's Text is not set (`<Button></Button>`), everything is fine again.

**Comment by danwalmsley** [comment]
I think this could be a manifestation of issue #510 

Thanks, this is probably the minimal repro iv been looking for to reproduce this.

**Comment by jkoritzinsky** [comment]
This is the same bug as #510. I just got a minimal repro and a unit test for it coded. Just need to commit it and start trying to fix the bug...

**Comment by grokys** [comment]
This should be fixed by using `ContentControl.ContentTemplate` which has just been added.
