### ISSUE TITLE
TextBox KeyDown event won’t be fired by some keys 

### ISSUE THREAD

**Issue by protoess1996** [AvaloniaUI/Avalonia#5244]
I add a keydown event handler to a textbox. It will be fire on most cases. But when I press backspace and arrowkeys it won’t be fired. I tested it on Windows and macOS using 0.10.0-rc1

**Comment by maxkatz6** [comment]
Backspace and arrowkeys are handled by TextBox itself.
You need to subscribe on this event with Tunnel flag.

```csharp
var textBox = new TextBox();
textBox.AddHandler(InputElement.KeyDownEvent, TextBox_KeyDown, RoutingStrategies.Tunnel);
```

**Comment by protoess1996** [comment]
Thanks, That helps a lot!
