### ISSUE TITLE
Pen Thickness is not taking into account when calculating bounding boxes/clip rectangles.

### ISSUE THREAD

**Issue by nitroxis** [AvaloniaUI/Avalonia#5249]
When drawing e.g. an ellipse into an image with just the outline, it will always get cut off at the edges because the bounding box appears to only consider the "fill" area, not the whole outline.

A simple repro:
```xml
<Image Width="500" Height="500" Stretch="None">
	<Image.Source>
		<DrawingImage>
			<GeometryDrawing>
				<GeometryDrawing.Pen>
					<Pen Brush="#000000" Thickness="10"></Pen>
				</GeometryDrawing.Pen>
				<EllipseGeometry RadiusX="100" RadiusY="100"></EllipseGeometry>
			</GeometryDrawing>
		</DrawingImage>
	</Image.Source>
</Image>
```

This currently looks like this: 
![20210102123750](https://user-images.githubusercontent.com/2377442/103456508-5fa1bb80-4cf7-11eb-840b-e3fe7b32cbba.png)

If this is intentional behavior, what is the proper way to make this look like a normal circle?

**Comment by kekekeks** [comment]
Probably a bug somewhere here https://github.com/AvaloniaUI/Avalonia/blob/c85fa2b9977d251a31886c2534613b4730fbaeaf/src/Skia/Avalonia.Skia/GeometryImpl.cs#L89

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/commit/cf155200a7493776c97cfc921c684da84ea79fb9

**Comment by nitroxis** [comment]
I checked the method you mentioned but the bounds look correct there:
![20210105053531](https://user-images.githubusercontent.com/2377442/103606933-01075800-4f18-11eb-891d-854f140dedca.png)

This is for the above example geometry, which is correctly calculated at 200x200 for the fill + 10 for the stroke. The bug might be somewhere else?

**Comment by nitroxis** [comment]
Okay I've investigated this a bit more. Seems like the first calls to `GetRenderBounds` from here 
https://github.com/AvaloniaUI/Avalonia/blob/de0774a1b60dce4840bc1c54abc0c36cfb9510a3/src/Avalonia.Visuals/Media/GeometryDrawing.cs#L71
supply a pen with `Thickness` 0. Later, when the method is called from here:
https://github.com/AvaloniaUI/Avalonia/blob/6adb3eaa6317a2f9b98bcb3419be45ae99df112b/src/Avalonia.Visuals/Rendering/SceneGraph/GeometryNode.cs#L27
the pen is correct. I think the `Pen` property is not fully initialized when UpdateScene is called for the first time or something?

**Comment by nitroxis** [comment]
Ah no, `s_boundsPen` is simply an immutable `Pen` with `Thickness` always 0. I guess this is the problem then, it should probably use the real pen?

**Comment by kekekeks** [comment]
@grokys

**Comment by Gillibald** [comment]
GetRenderBounds should not require a `Pen` to work properly. Instead the API should be changed to take a thickness instead.

**Comment by jhofinger** [comment]
I also mentioned this bug here: https://github.com/AvaloniaUI/Avalonia/issues/4913

**Comment by Tenjim** [comment]
I notice that bug is also related to : #8080

**Comment by Whiletru3** [comment]
Hello, this bug is annoying as all the icons are cropped in the interface, is there any plan to fix this ?

Thanks

**Comment by Whiletru3** [comment]
In GeometryDrawing.cs, the GetBounds should be changed from this

```
public override Rect GetBounds()
        {
            return Geometry?.GetRenderBounds(s_boundsPen) ?? Rect.Empty;
        }
```

![image](https://user-images.githubusercontent.com/4248852/171601830-3e828626-2ed4-4375-9764-8762d5cadb12.png)


to this (to take the Pen of GeometryDrawing if exist
```
public override Rect GetBounds()
        {
            IPen pen = Pen ?? s_boundsPen;
            return Geometry?.GetRenderBounds(pen) ?? Rect.Empty;
        }
```

![image](https://user-images.githubusercontent.com/4248852/171601578-9c429808-b05e-4ed3-a15e-7452f45d68ab.png)
