### ISSUE TITLE
Run Avalonia on Raspberry Pi OS Lite

### ISSUE THREAD

**Issue by B8ightY** [AvaloniaUI/Avalonia#5253]
Hi, I would like to run my very simple application on Raspbian buster Lite (the one without desktop, only terminal). The app is just window with one button and one text box. I followed all steps in [this](https://github.com/AvaloniaUI/Avalonia/wiki/Run-an-Avalonia-application-on-Raspberry-Pi) guide. The project also uses NuGet package Avalonia.Skia.Linux.Natives. But when I copied files to raspberry and tried to run with command `sudo dotnet publish/MyApp.dll`, I got following error:

```
Unhandled Exception: System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.AvaloniaX11PlatformExtensions.<>c__0`1.<UseX11>b__0_0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at SmartMirror.Program.Main(String[] args) in C:\Users\User\Documents\Visual Studio 2019\Sources\MyApp\MyApp\Program.cs:line 13
Aborted
```

My app lib versions:
Avalonia 0.9.12
Avalonia Desktop 0.9.12
Avalonia.Skia.Linux.Natives 1.68.0.2
netcoreapp2.0

I tried to install several libs to get X working:
`xserver-xorg xinit libx11-dev libgtk2.0-dev libgtk-3-dev gir1.2-gtk-2.0 gir1.2-harfbuzz-0.0 libcairo2-dev libcairo-perl libcairomm-1.0-dev libpango-perl libsdl2-dev libnss3 x11-xserver-utils`

I even tried set DISPLAY environment variable and run `xhost +` but it says `xhost: unable to open display "" (or :0.0)`. This error occurs on every attempt to run some X app. Nothing worked to get at least one X app running even directly on Raspberry without using SSH. Does anybody have any idea how to solve this issue?  Hopefully it will be just some missing library. Thank you for any help

**Comment by danwalmsley** [comment]
Try 0.10.0-rc1

**Comment by Ingrown29** [comment]
Thank you for your reply @danwalmsley 

> Try 0.10.0-rc1

Did you mean `Avalonia.Diagnostics -Version 0.10.0-rc1` or `Avalonia.Headless -Version 0.10.0-rc1`? Or something else? Sorry I am not such experienced

**Comment by Ingrown29** [comment]
Thank you for your reply @danwalmsley

I updated all Avalonia libs to 0.10.0-rc1 but now I'm getting `Segmentation fault` error.. On the recommended version for Raspbery Pi with desktop it works flawless and also on Windows but on the Raspbian Lite version without GUI doesn't. Any other ideas?

**Comment by Feroks** [comment]
In order to render your application in Terminal you need to use FrameBufferor or DRM (i think).
Here is a sample code:
https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog.NetCore/Program.cs
Check how `--fbdev` and `--drm` args are handled.

I would recommended cloning the repo to explore sample, since there are multiple gotchas.

**Comment by Ingrown29** [comment]
Thank you for help I'll definitely take a look on that sample code and try to make my code work. Later I'll post my findings
