### ISSUE TITLE
Is it possible to embed the libSkiaSharp.so into single file?

### ISSUE THREAD

**Issue by GF-Huang** [AvaloniaUI/Avalonia#5254]
I had try to publish with target `linux-arm` and `single file`, but still get `libSkiaSharp.so`.

![image](https://user-images.githubusercontent.com/4510984/103781537-76d30700-5071-11eb-8686-dda20d773067.png)

**Comment by maxkatz6** [comment]
Do you use .NET 5?
This might help you https://stackoverflow.com/questions/64778283/net-5-excludes-some-libraries-from-single-file-publication

**Comment by GF-Huang** [comment]
> Do you use .NET 5?
> This might help you https://stackoverflow.com/questions/64778283/net-5-excludes-some-libraries-from-single-file-publication

It works! Thank you!
