### ISSUE TITLE
Any suggestions for custom drawing chart?

### ISSUE THREAD

**Issue by GF-Huang** [AvaloniaUI/Avalonia#5255]
I am planning to develop a real-time signal display GUI application using Avalonia. So it requires frequent drawing of square waveforms like the following image. 

Is it same to custom drawing in WPF? Or any other ways? 

What is the best practice in Avalonia?

![image](https://user-images.githubusercontent.com/4510984/103791524-822c2f80-507d-11eb-85e1-279fcc111fb0.png)

**Comment by FrankenApps** [comment]
I would use SkiaSharp for this. There is an official [sample](https://github.com/AvaloniaUI/Avalonia/tree/master/samples/RenderDemo). I have also used this myself for example [here](https://github.com/FrankenApps/MqttDebugger/blob/master/Views/Pages/TimeSeriesPage.cs) for a simple realtime graph.

**Comment by GF-Huang** [comment]
> I would use SkiaSharp for this. There is an official [sample](https://github.com/AvaloniaUI/Avalonia/tree/master/samples/RenderDemo). I have also used this myself for example [here](https://github.com/FrankenApps/MqttDebugger/blob/master/Views/Pages/TimeSeriesPage.cs) for a simple realtime graph.

Thanks your tips.

**Comment by maxkatz6** [comment]
There are some chart-controls for Avalonia. You can take a look for a ready implementation or reuse some ideas:
https://github.com/AvaloniaCommunity/awesome-avalonia#chart--plot

**Comment by Angelore** [comment]
> There are some chart-controls for Avalonia. You can take a look for a ready implementation or reuse some ideas: https://github.com/AvaloniaCommunity/awesome-avalonia#chart--plot

It looks like the only graph visualization option there is a (very) paid library. Are you aware of any others?
