### ISSUE TITLE
Chinese text sometimes become out of shape under HiDPI monitor

### ISSUE THREAD

**Issue by balthild** [AvaloniaUI/Avalonia#5260]
**Describe the bug**

![Snipaste_2021-01-07_15-33-20](https://user-images.githubusercontent.com/2662758/103864596-da0a7b00-50fd-11eb-90ec-b04008ec950c.png)

The font size of first line is 12 and the second line is 10. In the second line, some horizontal strokes in the character `香` becomes thicker.

![100](https://user-images.githubusercontent.com/2662758/103864926-60bf5800-50fe-11eb-86a3-5ae3ff0cbfb9.png)
![150](https://user-images.githubusercontent.com/2662758/103864930-6321b200-50fe-11eb-8458-d67fd992adfc.png)
![200](https://user-images.githubusercontent.com/2662758/103864935-6452df00-50fe-11eb-932e-d441b799c018.png)
![225](https://user-images.githubusercontent.com/2662758/103864943-661ca280-50fe-11eb-945a-40fb1696705e.png)

The four screenshots are captured under the system scaling setting of 100%, 150%, 200 and 225% respectively, and the font size is 12. When scaling factor >= 200%, the overall height of `计算`  is smaller than normal, and the part `厶` in `法` is out of shape (normally the right side should be higher, but it gets lower now).

I guess the problem is caused by font hinting. 

**To Reproduce**

1. Create `TextBlock`s that contains the text `由于目标计算机积极拒绝，无法连接`
2. Run the program on a monitor where scaling > 200%

**Expected behavior**

Text rendered by wordpad.exe (GDI+):

![image](https://user-images.githubusercontent.com/2662758/103866789-49359e80-5101-11eb-9926-55f552aeda14.png)

Text rendered by OneNote (UWP, DirectWrite):

![image](https://user-images.githubusercontent.com/2662758/103866949-8ac64980-5101-11eb-8172-ff66510d2000.png)

Both screenshots are captured when scaling factor = 225%, and the font size is 9.5pt (≈ 12.667 px).

**Desktop (please complete the following information):**

 - OS: Windows 10 (20H2, 19042.685)
 - Version: 0.10.0-rc1

**Comment by Gillibald** [comment]
Avalonia's text rendering isn't DPI aware
