### ISSUE TITLE
Where can I download the Linux-ARM64 architecture bit libskiaSharp.so file

### ISSUE THREAD

**Issue by Aaronlog** [AvaloniaUI/Avalonia#5261]
**Is your feature request related to a problem? Please describe.**
After publishing the Avalonia project as a Linux-ARM64 architecture, the libskiasharp.so file was missing in the Generated directory

**Describe the solution you'd like**
I want the project to run on Linux-ARM64

**Describe alternatives you've considered**

**Additional context**

**Comment by Gillibald** [comment]
What version of Avalonia are you using?

**Comment by Gillibald** [comment]
https://www.nuget.org/api/v2/package/SkiaSharp.NativeAssets.Linux/2.80.2
