### ISSUE TITLE
How to enable acrylic?

### ISSUE THREAD

**Issue by GF-Huang** [AvaloniaUI/Avalonia#5262]
Like this:

![image](https://user-images.githubusercontent.com/4510984/103895712-cbd35380-512b-11eb-9ded-ad55dbcf70ec.png)

**Comment by PieroCastillo** [comment]
First download Avalonia 0.10.0-rc1, next enable the Acrylic in Window setting ```TransparencyLevelHint="AcrylicBlur"```, next of this, 
create an ExperimentalAcrylicBorder, and set the material with an ExperimentalAcrylicMaterial
