### ISSUE TITLE
UI elements very large on Linux HIDPI

### ISSUE THREAD

**Issue by xdrie** [AvaloniaUI/Avalonia#5265]
**Describe the bug**
The size of UI elements on my HIDPI screen are very large, probably unnecessarily doubled in size.
See screenshots for more info.

**To Reproduce**
1. Run the XAML Controls Gallery on a Linux system with X, with DPI set to 192
2. Observe that everything is really big.

**Expected behavior**
See screenshots: I expect the ui element size when running the application to be more reasonable, i.e. matching their size previewer there.

**Screenshots**
It looks fine in the previewer (ignore the background image, it's my IDE theme):
![image](https://user-images.githubusercontent.com/54390138/103975828-fae8c580-5129-11eb-8fbc-4cf3f52ff02f.png)
However this very same application is now huge (this shows comparison)
![image](https://user-images.githubusercontent.com/54390138/103975871-181d9400-512a-11eb-9aed-07569a248e3b.png)

But when I run the application:

**Desktop (please complete the following information):**
 - OS: **Arch Linux, X with DPI set to 192**
 - Version `0.10.0-rc1`

**Additional context**
N/A

**Comment by xdrie** [comment]
Here, for comparison, is the same thing running on a non-HIDPI system (which configuration and OS wise is identical to the other):

Here it can be seen that the application matches the previewer in size.

![image](https://user-images.githubusercontent.com/54390138/103976337-5e272780-512b-11eb-9208-8163d7c04c01.png)

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/4826

**Comment by xdrie** [comment]
Oh, that solves my issue. Thank you!
