### ISSUE TITLE
How to convert `IBrush` to `SKColor`?

### ISSUE THREAD

**Issue by GF-Huang** [AvaloniaUI/Avalonia#5267]
I want draw the `UserControl.Background` property into `SKCanvas` by `SKCanvas.Clear(convert IBrush to SKColor)`

**Comment by maxkatz6** [comment]
If your know that your background always will be a SolidColorBrush (or ImmutableSolidColorBrush), you can cast it and get Avalonia.Color that is simpler to convert.
