### ISSUE TITLE
Unable to assing Resource Image File in Image

### ISSUE THREAD

**Issue by Junaid-Amjad** [AvaloniaUI/Avalonia#5268]
Hi, I am working on the Image Class and i want to assign the source from Resources. 

`ImgLogo.Source = new Bitmap(AppContext.BaseDirectory+ Path.Combine("images", "Strantin_Logo.png"));` This Work
` ImgLogo.Source = (IBitmap)Properties.Resources.Strantin_Logo;` This Won't
This is the error which i faced:
`Cannot convert type 'System.Drawing.Bitmap' to 'Avalonia.Media.Imaging.IBitmap'`
Can you guide me how to convert the Bitmap into IBitmap. 
It is highlighted in this [1290](https://github.com/AvaloniaUI/Avalonia/issues/1290) but my approach is different.

**Comment by maxkatz6** [comment]
> It is highlighted in this 1290 but my approach is different.

What exactly is different in your case? You need to cast "Properties.Resources.Strantin_Logo" to System.Drawing.Bitmap and after that same MemoryStream approach will work.

**Comment by Junaid-Amjad** [comment]
Hi @maxkatz6 if i use `System.Drawing.Bitmap` then assembly exception is thrown 
`Could not load file or assembly 'System.Drawing.Common, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)`

**Comment by maxkatz6** [comment]
@Junaid-Amjad so you need to solve that issue first. Since it's unrelated to Avalonia, you can find help in other places too.
But probably it will be fixed with adding correct version of System.Drawing.Common package.

**Comment by Junaid-Amjad** [comment]
@maxkatz6 i previously worked on winforms and i uses images from Resources.resx, so to build application in avalonia i first read xaml of wpf and then i move to avalonia xaml. I don't know it is possible in avalonia but it is not possible in wpf as indicated [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/dc171eea-b73e-4405-b731-e30dac9c9be0/assign-image-source-from-resource?forum=wpf). If i follow the steps of to load image in wpf [as indicated here](https://stackoverflow.com/questions/35214453/c-sharp-wpf-uri-syntax), then it work successful but not in avalonia as `BitmapImage `class doesnot exist. Although my first approach work so i think may use that.

Also, solution of the assembly is to change the framework to lower which is odd as i only created a new solution. Thanks for the help.
