### ISSUE TITLE
In the case of Chinese input method. The position of the prompt box and the text box of the input method is too far away

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#5272]
In the case of Chinese input method. The position of the prompt box and the text box of the input method is too far away，
Is it possible to move the position of the input method prompt box near the text box where the character is being typed?

The screenshot of the exception is shown below
![image](https://user-images.githubusercontent.com/7692353/104082322-40170f80-5270-11eb-966e-3e3fa46fd0cf.png)

The screenshot of the exception is shown below

![image](https://user-images.githubusercontent.com/7692353/104082379-af8cff00-5270-11eb-99d4-dcef4a4dc6d3.png)

May I ask when this can be optimized? thank  @kekekeks

**Comment by kekekeks** [comment]
That requires us to properly report the cursor position to IME, which will be implemented for Windows and macOS somewhere in 2021 (no ETA yet). 
Linux should work once #5258 is merged

**Comment by protoess1996** [comment]
Also when you hit BackSpace, it will not only delete the word in IME, it will also delete the word in TextBox.

**Comment by wuzlai** [comment]
> That requires us to properly report the cursor position to IME, which will be implemented for Windows and macOS somewhere in 2021 (no ETA yet).
> Linux should work once #5258 is merged

Thank you for your prompt response. I know you have noticed this problem. When will this problem be resolved in 2021? This does not affect the use. The experience is not very good, for novice users.

**Comment by wuzlai** [comment]
> Also when you hit BackSpace, it will not only delete the word in IME, it will also delete the word in TextBox.

Yes. I also encountered this situation.

**Comment by maxkatz6** [comment]
Done
