### ISSUE TITLE
Consider using GitHub discussions instead of gitter or in addition to it

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#5277]
[GitHub discussions](https://docs.github.com/en/free-pro-team@latest/discussions) have more tight integration with GitHub services.

**Comment by shartte** [comment]
Gitter is more like chat, although Discord seems to be coming into fashion more to cover the persistent chatroom angle.
GitHub discussions seem more like a classic forum, or am I misjudging?

**Comment by KvanTTT** [comment]
> Gitter is more like chat, although Discord seems to be coming into fashion more to cover the persistent chatroom angle.

But do we need a chat room? There is hard to find anything and information is not organized.

> p.s.: I thought Github Discussions was intended to draw away "help me"/questions from the issue tracker

Not only "help me" questions, but also idea suggestions.

**Comment by grokys** [comment]
Good suggestion @KvanTTT - I've opened up discussions at https://github.com/AvaloniaUI/Avalonia/discussions

Go discuss! :)
