### ISSUE TITLE
Windows EGL initialization has inconsistent default

### ISSUE THREAD

**Issue by shartte** [AvaloniaUI/Avalonia#5281]
The following line is a bit too clever I believe:
https://github.com/AvaloniaUI/Avalonia/blob/25fe106c235ebb5c6260af5a13d6a79b633c5b82/src/Windows/Avalonia.Win32/Win32GlManager.cs#L24

If `opts` is null, the default is false, since the negation will be applied before the null-coalescing operator.
If `opts` is not null, but `AllowEglInitialization` is null, it defaults to true.

I'll submit a fix PR if you confirm the **intended** functionality is to default to EGL (only on Windows 8 or later).

**Comment by kekekeks** [comment]
We should probably guarantee that we always have an options instance at that point, so there won't be any nulls.

The intended behavior is to enable EGL on Win8+ by default, yes.

**Comment by shartte** [comment]
I'll submit a PR to fix this

**Comment by shartte** [comment]
BTW. Isn't `egl is { }` equivalent to `egl != null` ........

**Comment by danwalmsley** [comment]
yes
