### ISSUE TITLE
Expander header is not stretch

### ISSUE THREAD

**Issue by Soarc** [AvaloniaUI/Avalonia#5284]
There is no way to made full width expander header, without control template modification.

1. Apply fluent style
2. Put expander
3. Add header content with right alignment
4. Header is always aligned to left

```
          <Expander>
            <Expander.Header>
              <Grid ColumnDefinitions="*, Auto">
                <TextBlock Text="{Binding ComponentType}" />
                <Button Grid.Column="1" Padding="0">
                  <Image  Source="{StaticResource AppMinus}" Height="30" />
                </Button>
              </Grid>
            </Expander.Header>
            <ContentControl Content="{Binding}" />
          </Expander>
```

**Expected behavior**
Content aligned to right

**Screenshots**

*Actual result*
![image](https://user-images.githubusercontent.com/3385495/104217350-b96f5780-5454-11eb-925f-5e3aad0df65c.png)

*Expected result:*
![image](https://user-images.githubusercontent.com/3385495/104217666-1bc85800-5455-11eb-8b82-294830abfb75.png)

**Additional context**
This is probably because of following Grid in Expander toggle button template. 
https://github.com/AvaloniaUI/Avalonia/blob/25fe106c235ebb5c6260af5a13d6a79b633c5b82/src/Avalonia.Themes.Fluent/Controls/Expander.xaml#L90

I think it should have `ColumnDefinitions="Auto,*"` . Should I make a pull request with this fix?

**Comment by Fruchtzwerg94** [comment]
I have the same problem. Is there any update or a potential fix / workaround? How did you solved it @Soarc ?

**Comment by GRustamyan-ST** [comment]
> I have the same problem. Is there any update or a potential fix / workaround? How did you solved it @Soarc ?

Just overrided default control template template.

**Comment by Fruchtzwerg94** [comment]
Not the best solution, but also a working one: Binding the width of the header content to the top level width like

```
<Grid Name="Grid_Menu">
    <Expander>
        <Expander.Header>
            <Grid ColumnDefinitions="*,Auto" Width="{Binding #Grid_Menu.Bounds.Width}">
                ...
            </Grid>  
        </Expander.Header>
        ...
    </Expander>
</Grid>
```

**Comment by FG-rgb** [comment]
This Bug is still open. Are there plans to fix that in the next time?

**Comment by maxkatz6** [comment]
Not relevant anymore

**Comment by FG-rgb** [comment]
I have the same Problem in latest Avalonia Version (0.10.7) on a Window 10 Machine, when using Fluent Theme:
My workaround is to overwrite the Template (as mentioned above).

**Comment by Fruchtzwerg94** [comment]
> Still not an issue
> 
> ```
> <StackPanel>
> 	<Expander Header="HorizontalAlignment=Stretch"
> 				HorizontalAlignment="Stretch"/>
> 	<Expander Header="HorizontalAlignment=Center"
> 				HorizontalAlignment="Center"/>
> 	<Expander Header="HorizontalAlignment=Left"
> 				HorizontalAlignment="Left"/>
> </StackPanel>
> ```
> 
> ![image](https://user-images.githubusercontent.com/3163374/155858493-dab9a5e5-8eb6-45f4-944b-d476ca559f7d.png)
> 
> If you have minimal repro, please open new issue. It might be related to something else.

I think your example is not the same since the StackPanel should be I side the header, not outside of the Expander.

**Comment by maxkatz6** [comment]
> not the same since the StackPanel should be inside the header

I see what you mean. It never will work with StackPanel (by design of stack panel), but it must work with Grid. Will open a PR for that.

**Comment by maxkatz6** [comment]
Btw. It's a problem with default expander style. For fluent you can avoid it without changing whole template:
```
  <Style Selector="Expander /template/ ToggleButton#ExpanderHeader">
    <Setter Property="HorizontalContentAlignment" Value="Stretch" />
  </Style>
```
But for convenience I will change default value anyway. It makes more sense.
