### ISSUE TITLE
WebView class. I can't change UserAgent in runtime.

### ISSUE THREAD

**Issue by VictorBozhuk** [AvaloniaUI/Avalonia#5288]
I use the WebView class from Avalonia. I need to use several different versions of UserAgent while the program is running. But the problem is that after initializing the first object of the WebView class, the UserAgent is then unchanged. UserAgent is created once and then it can not be changed in any way. And I need to change it and use two versions of UserAgent depending on the condition.
```
public WebView Browser { get; set; }

private void InitializeComponent()
{
    if (SectionViewModelBase.OldUserAgentRequired == true)
    {
        WebView.UserAgent = "Mozilla/5.0 (Windows NT 6.2; WOW64; rv: 28.0) Gecko / 20100101 Firefox / 28.0";
    }
    else
    {
        WebView.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0";
    }
    AvaloniaXamlLoader.Load(this);
    Browser = this.Find<WebView>("browser");
    Browser.Navigated += Browser_Navigated;
    var ccv = new CookieVisitor();
    CefCookieManager.GetGlobal(null).VisitAllCookies(ccv);
}
```

**Comment by maxkatz6** [comment]
There is no WebView class in Avalonia. 
You need to create issue in related repository.

**Comment by Gillibald** [comment]
You most likely want to open an issue here: https://github.com/OutSystems/WebView

Closing this because we don't maintain that component.
