### ISSUE TITLE
Binding Property Validation

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#529]
I think I'm reasonably happy with the current property validation in the `property-validation-grokys` branch (which has only minor changes from @jkoritzinsky's `property-validation`) but there are two things I'm still not happy with:

- Typing e.g. string "foo" into a `TextBox` bound to an integer property should result in an invalid state being displayed as the value cannot be converted to an int.
- It would nice for validation to be pay-to-play - I'd like to aim for no permanent memory overhead for objects/controls for which property validation doesn't apply

To address these issues, I've been thinking about the following:

- Add a type called e.g. `BindingNotification` which can be consumed by `PerspexObject`'s binding system. This will replace `BindingError`. This type will have:
  * The binding value (or a special value meaning "don't change the current value")
  * An optional exception describing either a conversion error or a validation error
  * A flag indicating whether the exception represents a conversion or validation error
- When an `IObservable<object>` bound to a property produces a `BindingNotification` it:
  * Updates the property value
  * Calls `virtual PropertyValidationChanged(PerspexProperty, Exception)` with the exception. By default this method does nothing.
  * If the exception indicates a binding error, logs the error
- Controls which care about validation override `PropertyValidationChanged` and update a `ValidationState` property *which is defined on the control which requries validation* e.g. `TextBox`

This means:

- Working out the validation state is the purely the responsibility of the binding
- Each time a value is pushed a validation state is present, meaning that a validation error can come earlier in the pipeline than the property accessor (e.g. at the time conversion to the target type fails)
- No extra memory consumed at the `PerspexObject` level, though there will be an extra temporary object created each time the bound value changes

Thoughts?

**Comment by jkoritzinsky** [comment]
I like this idea. Go for it!
