### ISSUE TITLE
Linux frame buffer to use BGRA graphics memory layout

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#5291]
Using Linux frame buffer with StartLinuxFbDev causes the display to be cleared on startup on the Raspberry Pi  3 with the official 7" touch display (possibly other platforms too). I've set my Raspberry PI to boot with a splash screen and launch straight into a kiosk app.
I would like the splash screen to remain displayed until the kiosk app renders its first view.
Currently the screen goes black for several seconds while the app is loading which makes for an unpleasant user experience.

The screen blanking is due to the FbdevOutput class which sets the Linux frame buffer memory layout to RGBA during initialisation. The change from BGRA (default layout) to RGBA clears the screen.

I propose that the code in FbdevOutput is modified to leave the frame buffer in BGRA format. The SkipSharp graphics already works with BGRA format. I have removed the RGBA setup code from a local copy of FbdevOutput  and the display works with correct colours and does not clear the screen.

Is there a good reason for changing to RGBA format?

**Comment by kekekeks** [comment]
There is no particular reason for that pixel format, it's just something that worked during my testing with x86-based laptop

**Comment by aguahombre** [comment]
Can we not by default check the format in FbdevOutput Init and leave it unchanged if it is supported by Skia?

A constructor override could be added if needed to force a particular format.

**Comment by kekekeks** [comment]
That would make sense too, yes

**Comment by aguahombre** [comment]
@kekekeks do you have any objection to me opening a PR to fix this?
My app has unnecessary duplicated LinuxFrameBuffer code to fix this issue and I would like to get rid of it.

**Comment by kekekeks** [comment]
Go ahead. Might as well add support for rbg565.
