### ISSUE TITLE
How does Avalonia publish projects as independent target frameworks that are MIPS

### ISSUE THREAD

**Issue by Aaronlog** [AvaloniaUI/Avalonia#5292]
**Is your feature request related to a problem? Please describe.**
I want to run the Avalonia executable on the MIPS64 architecture

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maxkatz6** [comment]
Have you checked this issue?
https://github.com/AvaloniaUI/Avalonia/issues/4086
