### ISSUE TITLE
[Discussion] How to Deploy

### ISSUE THREAD

**Issue by djthegr8** [AvaloniaUI/Avalonia#5296]
**Is your feature request related to a problem? Please describe.**
Its not written clearly ***anywhere*** how to deploy avalonia apps easily. I am trying SCDs, Framework-Dependents, and ClickOnce while neither of these seem to work.
**Describe the solution you'd like**
A clear and concise description of how to deploy for each platform

**Comment by maxkatz6** [comment]
> Its not written clearly anywhere

In general the process it the same as with any other .NET Core application. And you can find a lot of information about this.
Simple "dotnet publish" works perfectly fine. For example in case if you want self contained app:
```dotnet publish "App.csproj" -c release -f netcoreapp3.1 -r win-x64 --self-contained```

In the output folder you will have ready to run exe file with all dependencies and assets.
For Linux/MacOS it works in same way, but with another runtime identifier.

If you want best practices how to build modern app packages/installers on different platforms, you need to search for .NET documentation or articles on another sites.
In Avalonia docs there is some information about MacOS packages: https://avaloniaui.net/docs/packing/macOS
On Windows you can use MSIX, ClickOnce or something like WiX to build installer.
I am not familiar with Linux, but it shouldn't be a problem either.

**Comment by djthegr8** [comment]
I'm familiar with dotnet publish, but it doesnt work for me

**Comment by maxkatz6** [comment]
Can you provide more information, what exactly doesn't work for you?

**Comment by djthegr8** [comment]
The exe files (executables) simply do not work for me or any other people I send.

**Comment by djthegr8** [comment]
However, is the fact that I'm using `.net5` a possible issue?

**Comment by maxkatz6** [comment]
Do you have any logs from your application or windows event viewer?
You can at least try to catch all global exceptions in Main method and log them.

.NET 5 shouldn't be a problem.

**Comment by djthegr8** [comment]
No exceptions, and (because deployment) i am not using as a console app

**Comment by maxkatz6** [comment]
You mean, application is closing with success result without any errors? Does same code works in DEBUG?
Have you tried to publish avalonia hello world application to test it at minimum?

**Comment by djthegr8** [comment]
No, I haven't published Hello World. The same code works in Debug and Release, and executables hence formed are working

**Comment by djthegr8** [comment]
@maxkatz6 I really don't understand how, but it now works 🥳 so guess I'll close. However, one thing that I wanted to know is packing for android.

**Comment by maxkatz6** [comment]
About android:
https://github.com/AvaloniaUI/Avalonia/pull/4378

**Comment by djthegr8** [comment]
What I conclude from #4378 is that in essence, android support doesn't exist, is that correct?

**Comment by kekekeks** [comment]
*Experimental* support does exist. Proper support is coming this year.

**Comment by sn4k3** [comment]
To publish i'm using a powershell script, you can grab some inspiration here: https://github.com/sn4k3/UVtools/blob/master/CreateRelease.WPF.ps1

**Comment by maxkatz6** [comment]
Closing as resolved.
Ping me if you will have any other questions.

**Comment by silaros88** [comment]
Hi, I also have a question. I moved to Mac and started using Jetbrains Rider. I'm building an app for Windows and when I'm publishing it to an exe and try to open it there first thing which appears is console host window. Is there any chance to make it work without this host window and get an output just like from Visual Studio EXE from Windows?

**Comment by silaros88** [comment]
@sn4k3 I found this https://github.com/AvaloniaUI/Avalonia/issues/6672 and it appears that this is an runtime issue
