### ISSUE TITLE
When you replace dependency injection with autofac, showdialog will report an error

### ISSUE THREAD

**Issue by dashenxian** [AvaloniaUI/Avalonia#5298]
**Describe the bug**
I created a new project
`dotnet new avalonia.app -o MyApp`

then replaced autofac with Autofac, as described by Splat.Autofac, and the showdialog times wrong, if the code for Splat.Autofac is removed, it won't
`System.InvalidOperationException:“Call from invalid thread”`

***Important*
Only ICommand in mvvm mode will report errors, and event bindings under code behind will not report errors

**To Reproduce**
the main code
app.xaml.cs
```c#
public class App : Application
{
    public override void Initialize()
    {
        InitAutofac();
        AvaloniaXamlLoader.Load(this);
    }
    private void InitAutofac()
    {
        // Build a new Autofac container.
        var builder = new ContainerBuilder();

        //builder.RegisterType<MainWindowViewModel>();
        //builder.RegisterType<Student>().As<IStudent>();
        // Creates and sets the Autofac resolver as the Locator
        var autofacResolver = builder.UseAutofacDependencyResolver();
        //var autofacResolver = new AutofacDependencyResolver(builder);
        Locator.SetLocator(autofacResolver);
        // Register the resolver in Autofac so it can be later resolved
        builder.RegisterInstance(autofacResolver);

        // Initialize ReactiveUI components
        autofacResolver.InitializeSplat();
        autofacResolver.InitializeReactiveUI();
        //Container = autofacResolver.Container;
    }

    
    public override void OnFrameworkInitializationCompleted()
    {
        if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
        {
            desktop.MainWindow = new MainWindow();
        }
        base.OnFrameworkInitializationCompleted();
    }
}
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [Windows] 
 - vs2019
 - Version [0.9.12]

**Code**
[MyApp.zip](https://github.com/AvaloniaUI/Avalonia/files/5819754/MyApp.zip)

**Comment by kekekeks** [comment]
The issue is probably related to RxUI rather than AutoFac. Make sure that 
1) you have `UseReactiveUI()` in AppBuilder configuration
2) Values [configured by](https://github.com/AvaloniaUI/Avalonia/blob/e0cd8ae12c89b0a9a5a024563b903959efb9cb5c/src/Avalonia.ReactiveUI/AppBuilderExtensions.cs#L20-L22) `UseReactiveUI()` are not overwritten

**Comment by dashenxian** [comment]
As I understand it, I've done two of the above points, as shown in the following code.
1.
```c#
public static AppBuilder BuildAvaloniaApp()
    => AppBuilder.Configure<App>()
        .UseReactiveUI()
        .UsePlatformDetect()
        .LogToDebug();
```
2.
`autofacResolver.InitializeReactiveUI();`

What am I supposed to do? I only found this tutorial on the official documentation, can I go into more detail? Thank you

**Comment by kekekeks** [comment]
It seems that Autofac overwrites the Splat service locator with its own and doesn't preserve existing registrations.

I'd suggest to add the following lines after `autofacResolver.InitializeReactiveUI();`
```cs
RxApp.MainThreadScheduler = AvaloniaScheduler.Instance;
Locator.CurrentMutable.RegisterConstant(new AvaloniaActivationForViewFetcher(), typeof(IActivationForViewFetcher));
Locator.CurrentMutable.RegisterConstant(new AutoDataTemplateBindingHook(), typeof(IPropertyBindingHook));
```

**Comment by dashenxian** [comment]
It worked, thank you very much. 
Also, I don't know if you can add a replacement dependency injection document or link to your official documentation. I think dependency injection is also an important part of .net core development, especially in the current universal host injection model, do you think?
