### ISSUE TITLE
[Exception] Property Window (Icon) Linux(Fedora) 

### ISSUE THREAD

**Issue by CarlosEX** [AvaloniaUI/Avalonia#5300]
**Describe the bug**
I'm using Linux with Fedora, the build so far works, but when I run the application generates me an Expected. The image is at the root of the application and I only referenced it in the Windows Icon property. What's missing?

**To Reproduce**
1. Add property Icon in Window (Icon="favicon.ico")
2. dotnet run

**Expected behavior**
Unhandled exception. System.IO.FileNotFoundException: The resource favicon.ico could not be found

**Screenshots**
![Screenshot from 2021-01-15 10-10-49](https://user-images.githubusercontent.com/33513870/104733908-2a956000-571e-11eb-8bf6-6418108f23a6.png)

**Desktop (please complete the following information):**
 - OS:fedora.33-x64
 - Version [5.0.102]
 - Avalonia version [0.9.12]
 - 
**Additional context**

**Comment by kekekeks** [comment]
You need to include your icon as `<AvaloniaResource>` in your csproj file and then use project-relative path (e. g. `/favicon.ico`)

**Comment by CarlosEX** [comment]
Thank you so much for the support. I did it like this, and they're not generating the exception anymore. However, no images appear in the form title. Am I making a mistake?

![Screenshot from 2021-01-15 12-39-04](https://user-images.githubusercontent.com/33513870/104817208-77506800-57fe-11eb-8f5b-c1598d8cfd09.png)

**Comment by kekekeks** [comment]
Are you sure that your desktop environment actually shows window icons? Does any other window has an icon?

**Comment by CarlosEX** [comment]
I didn't notice that. Actually the apps I have here, show a layout but I went to repair and are controls with icons. I believe that solves that issue. I am very grateful for the attention, I am very pleased with the results obtained so far.
![Screenshot from 2021-01-16 20-40-28](https://user-images.githubusercontent.com/33513870/104827353-71c54300-583b-11eb-9dbf-18f53cbeea1d.png)
