### ISSUE TITLE
Consider upgrading netcoreapp2.0 to 2.1 or 3.1

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#5301]
Currently some projects (`Avalonia`, `Avalonia.Designer.HostApp`, `Avalonia.DesktopRuntime` and `NativeEmbedSample`) are targeting `netcoreapp2.0` (which is EOL since October 1, 2018). So it would make sense to upgrade to a more recent version, preferably LTS. I believe these are the best options:

- `netcoreapp2.1` (LTS, EOL: August 21, 2021)
- `netcoreapp3.1` (LTS, EOL: December 3, 2022)

For more info, .NET Core support policy: https://dotnet.microsoft.com/platform/support/policy/dotnet-core.

If you agree with this change I can make a PR.

**Comment by kekekeks** [comment]
Those are being run using the target runtime of your application. We are using `netcoreapp2.0` as the *minimum required* API surface.

**Comment by jp2masa** [comment]
I forgot to add that I was using 5.0.102 SDK, and I get this warning:

> C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.

I know that the "supported" SDK would be the one in `global.json` (`3.1.401`), so you may not consider this a valid reason.

Anyway, I agree that it shouldn't be a problem if it was the minimum API surface, however I read a bit more about this ([Framework-dependent apps roll forward](https://docs.microsoft.com/en-us/dotnet/core/versions/selection#framework-dependent-apps-roll-forward)) and, if I understood correctly, there are 2 problems:

- If the user has `2.0.x` and `2.1.y` installed, it will always choose `2.0.x` because it most closely matches the target framework (I believe this is a strong reason to upgrade, at least `Avalonia.Designer.HostApp` and `NativeEmbedSample`).
- It will never run a `2.x` app with `3.y` or `5.z` runtime (this will still be an issue when targeting only 1 .NET Core version, users are forced to have `2.x` runtime installed to run `Avalonia.Designer.HostApp` and `NativeEmbedSample`).

So actually `Avalonia` and `Avalonia.DesktopRuntime`, as they are libraries, may still target `netcoreapp2.0`, but it's not really useful for users, because they shouldn't target it anyway, which would make upgrading to `netcoreapp2.1` practically equivalent.

**Comment by kekekeks** [comment]
Avalonia.Designer.HostApp is run with the user's app .runtimeconfig.json and .deps.json files. The target framework of that "application" doesn't affect the target runtime at all, so you can treat it as a library (it replaces replaces the entry point at certain conditions, but is still a library)


We should update NativeEmbedSample since it's an actual app

**Comment by kekekeks** [comment]
More details on the HostApp usage: https://github.com/AvaloniaUI/Avalonia/wiki/XAML-previewer-protocol

**Comment by rstm-sf** [comment]
If we do not see the need to bump tfm, then it is good to disable this warning

**Comment by maxkatz6** [comment]
We target netstandard2.0 and net6 where it's possible now. Avalonia.Designer.HostApp is a special case as explained above.
