### ISSUE TITLE
Can I now publish my project as a MIPS architecture via dotnet publish

### ISSUE THREAD

**Issue by Aaronlog** [AvaloniaUI/Avalonia#5305]
**Is your feature request related to a problem? Please describe.**
I was very frustrated when I couldn't find a way to publish a project as a MIPS architecture via Dotnet Publis

**Describe the solution you'd like**
Where can I download the libskisharp for Linux-mips64   

**Describe alternatives you've considered**
......

**Additional context**
......

**Comment by kekekeks** [comment]
https://github.com/mono/SkiaSharp/wiki/Building-on-Linux
