### ISSUE TITLE
ListBoxItem selectable

### ISSUE THREAD

**Issue by RomanSoloweow** [AvaloniaUI/Avalonia#5306]
Can I make a specific ListBoxItem not selectable?

In WPF, it seemed to help to set Focusable to false - it did not help
And the IsEnable item blocks the all element in ListBoxItem .

It might be worth adding a property for this

**Comment by maxkatz6** [comment]
It's kind of expected to have SelectionMode=None, but in case of Avalonia it's problematic, because our SelectionMode is flags, where "0x0" value is "Single" and wasn't reserved for "None".

WPF has same behavior though:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.selectionmode?view=net-5.0
Unlike UWP:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewselectionmode?view=winrt-19041

**Comment by maxkatz6** [comment]
@RomanSoloweow although you can use ScrollViewer+ItemsControl instead.

**Comment by RomanSoloweow** [comment]
I need to make not selectable a specific ListBoxItem , not the whole ListBox

**Comment by maxkatz6** [comment]
Try to set IsHitTestVisible and Focusable to false

**Comment by RomanSoloweow** [comment]
I set IsHitTestVisible and Focusable to false but it doesn't work. ListBoxItem is still selectable

**Comment by maxkatz6** [comment]
@RomanSoloweow it works for me with simple style:
```xaml
<Style Selector="ListBox ListBoxItem">
    <Setter Property="IsHitTestVisible" Value="False" />
    <Setter Property="Focusable" Value="False" />
</Style>
```

But it also disables interaction with item content, so probably it doesn't suits your requirements.

**Comment by jp2masa** [comment]
I would say the easiest way (although a bit hacky) is to intercept `PointerPressed` event on the item.

I tried this, and it seems to work (pointer over styles are still applied, but that is easy to disable):

#### XAML

```xaml
<ListBox>
    <ListBoxItem>A</ListBoxItem>
    <ListBoxItem>B</ListBoxItem>
    <ListBoxItem x:Name="c">C</ListBoxItem>
    <ListBoxItem>D</ListBoxItem>
</ListBox>
```

#### C#

```cs
// For example after InitializeComponent(); :

var c = this.Find<ListBoxItem>("c");
c.PointerPressed += (sender, e) => e.Handled = true;
```

**Comment by RomanSoloweow** [comment]
@jp2masa ' solution is almost suitable, but there is a problem: we may need to make different elements unavailable for selection, depending on a certain condition. (it would be nice to be able to bind for this)


But since my Control completely overlaps the ListBoxItem, all clicks of the ListBoxItem go through my Control. After subscribing to PointerPressed on the control, set e.Handled = true and you're done.


```C#
protected virtual void OnPointerPressed(PointerPressedEventArgs e)
{
    if (this.ViewModel.Name.IsNullOrEmpty())
    {
        e.Handled = true;
    }
}

```

_While I still don't think this is a good solution, it works._

**Comment by maxkatz6** [comment]
There is another problem with keyboard selection, but I believe setting Focusable to false should be enough

**Comment by jp2masa** [comment]
To be able to bind, you would have to create an attached property, something like this (includes fix for keyboard selection as suggested by @maxkatz6):

#### C#

```cs
public static class BlockSelection
{
    public static readonly AttachedProperty<bool> IsSelectionBlockedProperty =
        AvaloniaProperty.RegisterAttached<ListBoxItem, bool>("IsSelectionBlocked", typeof(BlockSelection));

    static BlockSelection()
    {
        IsSelectionBlockedProperty.Changed.AddClassHandler<ListBoxItem>(IsSelectionBlockedChanged);
    }
        
    public static bool GetIsSelectionBlocked(ListBoxItem item) => item.GetValue(IsSelectionBlockedProperty);

    public static void SetIsSelectionBlocked(ListBoxItem item, bool value) => item.SetValue(IsSelectionBlockedProperty, value);

    private static void IsSelectionBlockedChanged(ListBoxItem item, AvaloniaPropertyChangedEventArgs e)
    {
        if (!(e.OldValue is bool oldValue) || !(e.NewValue is bool newValue) || oldValue == newValue)
        {
            return;
        }

        if (newValue == true)
        {
            item.PointerPressed += OnItemPointerPressed;
            item.SetValue(ListBoxItem.IsSelectedProperty, false, BindingPriority.LocalValue);
        }
        else
        {
            item.PointerPressed -= OnItemPointerPressed;
        }

        item.SetValue(ListBoxItem.FocusableProperty, !newValue, BindingPriority.Style);
    }

    private static void OnItemPointerPressed(object sender, PointerPressedEventArgs e) => e.Handled = true;
}
```

#### XAML

```xaml
<StackPanel Spacing="8">
    <CheckBox x:Name="c" Content="Block selection" />
    <ListBox>
        <ListBoxItem>A</ListBoxItem>
        <ListBoxItem>B</ListBoxItem>
        <ListBoxItem local:BlockSelection.IsSelectionBlocked="{Binding #c.IsChecked}">C</ListBoxItem>
        <ListBoxItem>D</ListBoxItem>
    </ListBox>
</StackPanel>
```
