### ISSUE TITLE
View bug

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#5307]
**Describe the bug**
When I add button with auto width 
https://github.com/CreateLab/VKTalker/blob/master/VKTalker/Views/MainWindow.xaml#L63

has bug like this (no images till hide image and show again)

https://user-images.githubusercontent.com/33497292/104811970-16319000-5810-11eb-8b26-ec7dcebcfe3a.mp4

but if i comment this button everything work ok

**Expected behavior**
I wanna that picks show in window as is

**Desktop (please complete the following information):**
 - OS: WIndows 10, Linux KDE
 - Version  0.10.0-rc1

**Comment by MikeCodesDotNET** [comment]
I created a project to try and reproduce the issue and found that it works as expected when loading an image from disk. Are you downloading these images to disk by any chance?
