### ISSUE TITLE
NumericUpDown control

### ISSUE THREAD

**Issue by dashenxian** [AvaloniaUI/Avalonia#5318]
**Describe the bug**
When the NumericUpDown control is at a value of 5.6 and Increment is 0.01, if adjusted up, it will appear as 0.570000000000000001 instead of 0.57

**Code**
`<NumericUpDown Value="0.56" Minimum="0" Maximum="10" Increment="0.01"/>`

**Expected behavior**
The value should beThe value should be 0.57

**Screenshots**
![image](https://user-images.githubusercontent.com/18696614/104977045-9129bf00-5a39-11eb-9cd9-a0713d726256.png)
![image](https://user-images.githubusercontent.com/18696614/104977057-95ee7300-5a39-11eb-8295-856e7cf2ae93.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Version  0.9.12

**Comment by dashenxian** [comment]
I know this is an error in floating-point calculations

**Comment by Takoooooo** [comment]
value is double, should we consider making it decimal?

**Comment by Takoooooo** [comment]
I suggest adding up-for-grabs label because the solution to this issue seems pretty easy to me

**Comment by pr8x** [comment]
I think we should port `NumericUpDown.DecimalPlaces` from WPF to correctly round the values: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.numericupdown.decimalplaces?view=net-5.0

**Comment by sn4k3** [comment]
Related: https://github.com/AvaloniaUI/Avalonia/issues/4756
To fix this i'm using FormatString="{}{0:0.00}"
