### ISSUE TITLE
Expose DataGrid.SelectAll() as Public to improve functionality

### ISSUE THREAD

**Issue by hazryder** [AvaloniaUI/Avalonia#5325]
Is there a specific reason that the DataGrid.SelectAll method is constrained to private? Exposing this as public would allow easier customisation in custom controls.

Right now there doesn't appear to be a straightforward way of selecting every item in a DataGrid.

**Comment by maxkatz6** [comment]
This method doesn't exists neither in WPF nor in Silverlight, but exists in some third party toolkits and old windows forms implementation.
Also our list controls have it as well.
So I don't see any reason to not add it to our DataGrid too.
