### ISSUE TITLE
App icon specified in .csproj file doesn't appear on app windows on (at least) Kubuntu Linux and Linux Mint

### ISSUE THREAD

**Issue by Splitwirez** [AvaloniaUI/Avalonia#5329]
**Describe the bug**
On Linux (or at least KDE Plasma?), the icon specified in the .csproj file for an Avalonia project (via `ApplicationIcon`) doesn't appear on the application's windows when it is run.

**To Reproduce**
1. Add the `<ApplicationIcon>ICON_NAME_HERE.ico</ApplicationIcon>` element to a `PropertyGroup` in the .csproj file for an Avalonia project, ensuring that ICON_NAME_HERE refers to the name of an ico file that exists there
2. Build and run the project on Linux (tested on Kubuntu Linux 20.04, and also I *think* on some version of Linux Mint)
3. Look at the application window's presence on the Taskbar/Dock/whatever, and in its titlebar (if it has one, and if the current setup is supposed to show windows' icons in their titlebars)
4. Notice that both are icon't (or, in less playful terms, notice that the app icon is simply...not present)

**Expected behavior**
The icon should appear in the Taskbar/Dock/etc, and titlebar...some Window Managers/Desktop Environments/etc may not show these elements, but a stock install of Kubuntu 20.04 should, and does so successfully for other apps...just not for this one.

**Screenshots**
On Kubuntu 20.04:
![image](https://user-images.githubusercontent.com/34009058/105389892-6761cb00-5be6-11eb-9838-7914eb28c9b3.png)

On whatever version of Linux Mint or whatever it is @jmacato uses:
![image](https://user-images.githubusercontent.com/34009058/105390722-55345c80-5be7-11eb-9415-3b1577c6d04b.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu, Linux Mint
 - Version: 20.04 (Kubuntu), not sure what version of Linux Mint...@jmacato, as it was in his screenshot on Gitter

**Additional context**
https://github.com/mike-ward/Loon is known to be affected by this, as was discovered when I was aiding @mike-ward in documenting how to build this app on Linux earlier today.

Also, it should be noted that I was able to work around the issue by adding 
```xml
Icon="avares://Loon/app.ico"```
to the opening tag of Loon's `Views/MainWindow.xaml`, though this seemed like more of a dumb workaround than anything, so I figured we'd best bring this up just in case.

**Comment by Splitwirez** [comment]
@pr8x Good catch on the labels, thanks

**Comment by kekekeks** [comment]
The problem is that ApplicationIcon isn't really saved anywhere in .NET Core, *I think*.

So we should probably have some special logic in our MSBuild task to package said icon with a well-known name (like `!AppIcon`) so it could be picked by the Window class from `Assembly.GetEntryAssembly()`

**Comment by Splitwirez** [comment]
> The problem is that ApplicationIcon isn't really saved anywhere in .NET Core, _I think_.

If that's so, then...how is it possible that it works on Windows? (which it does)

**Comment by kekekeks** [comment]
On windows it's _most likely_ embedded into the `.exe` launcher file. Windows then discovers the icon and uses it for all iconlesswindows.

**Comment by Splitwirez** [comment]
> On windows it's _most likely_ embedded into the `.exe` launcher file. Windows then discovers the icon and uses it for all iconlesswindows.

That's definitely a thing Windows does, yes...but I've just observed a bit of a wrinkle in your explanation: The icon *is* embedded when building on Linux, as can be determined via software such as Resource Hacker.

Now I'm wondering if Windows may automatically propagate the app executable's icon to its windows, while I guess Linux doesn't. If that's correct, then...this creates a bit of a problem: some Linux users will specify custom icons for their apps via .desktop files.

I don't know if other Linux apps are able to detect whether or not the user has done this and show the custom icon on their window accordingly...but if it can be done, I'd say Avalonia should do so.

If it were my call, I would say that if the user has specified a custom icon for their program, Avalonia should propagate the icon they've provided to any app windows for which no icon is explicitly specified by the app's developer. If they haven't, then I suppose the sensible course of action would be to do the same thing, but with the icon embedded into the program itself.

This leads to two other considerations:
1. What if the user has multiple .desktop files for this app? This is entirely possible, and there's no rule that say the app *has* to be started from a .desktop file at all...I haven't a clue if it's possible to know which one was used to launch the app (if any...)
2. What if the user is using a Desktop Environment that doesn't use .desktop files, but instead uses something else? (I don't know of any of these, but apparently they exist...I know nothing else about them)
3. If all of this can be successfully accounted for, I suspect the Avalonia project templates would need to be updated accordingly, so new apps don't accidentally override all of this. As for existing apps...uh, I guess put out a PSA or something?

**Comment by kekekeks** [comment]
Again, we should properly expose the icon to our resource system and just use it by default.
If you are worried about `.desktop`-assigned window icons, those are matched by `StartupWMClass`

**Comment by qidydl** [comment]
The problem seems to be worse than this; even explicitly specifying the Icon property for a Window doesn't seem to work, at least on Linux (Ubuntu 20.04).

**Comment by kekekeks** [comment]
@qidydl GNOME doesn't have window icons. Try checking with another desktop environment that doesn't randomly remove features.

**Comment by qidydl** [comment]
@kekekeks Maybe I'm not using the right terminology? The bar where I switch between windows displays an icon for each window, but I cannot get it to display one for Avalonia windows. Here's an example running projectM from the command line:

![image](https://user-images.githubusercontent.com/5160192/111871638-9df76000-8961-11eb-9d38-e9457c67bdaf.png)

**Comment by mehmetulukaya** [comment]
Maybe this stackoverflow question can help for Windows:

[](https://stackoverflow.com/questions/59309154/how-add-icon-to-dotnet-desktop-windows-application)

`<ApplicationIcon>nome.ico</ApplicationIcon>
`

`
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationIcon>nome.ico</ApplicationIcon>
  </PropertyGroup>`

**Comment by kekekeks** [comment]
@qidydl WM_ICON property is ignored by GNOME. You need to specify the icon in a .desktop file and ship it with the app in your installation package.

**Comment by fatihbahceci** [comment]
Hello. There are 2 things you should pay attention to
1. You should add your icon to MainWindow's axaml, like this
`<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
         ...
        Icon="/Assets/blabla.ico"
  >
`
2. Your icon shouldn't be fully filled. At least you should let a 1 pixel transparent frame. Yes it's weird but I had same problem with you and this solution worked for me. 
Best regards.
