### ISSUE TITLE
AppBuilder/Designer Problems

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#533]
cc: @kekekeks @jazzay 

This is following on from a conversation we had in gitter: the recent changes to the way `Application` is initialized has broken the designer, as the designer relied on `App` setting up the environment. We spoke about using an `AppBuilder` class, for which I've committed an initial implementation on the `appbuilder` branch but I'm still unclear as to how this will fix the designer.

I think the problem is that we need it to be possible to define the `App` class in a portable assembly, so by definition it cannot setup the environment as the environment isn't known at that point.

In addition, we need to be able to edit XAML files in PCL libraries and currently the designer requires an executable if I understand correctly?

My main questions are what are the plans here; how will `AppBuilder` help is solve these problems?

**Comment by kekekeks** [comment]
1) AppBuilder should completely decouple initialization from App's logic, so we can safely assume what steps are needed to set up things in designer process.

2) Designer needs to have Perspex.Win32 and Perspex.Direct2D in project output directory, it won't be able to initialize rendering otherwise. We need some logic in VS addin to scan for actual package version and add platform assemblies to designer's process lookup list.

**Comment by kekekeks** [comment]
I'll take a look at designer helper this weekend. BTW, scaling in designer will still be broken because of your DPI scaling approach.

**Comment by grokys** [comment]
So you mean that the designer won't rely on `App` to set up the environment? If so that sounds like a good idea to me. We could maybe even have settings in the designer for D2D/Skia etc later on.

I'm fine with leaving designer scaling as a TODO for the moment - it's not a hugely important feature.

If you could take a look at the `appbuilder` branch and let me know if it's how you imagined. It will need to be ported to use the Avalonia name too: I can do that.

**Comment by grokys** [comment]
@kekekeks the `AppBuilder` has been ported from Perspex to Avalonia in `appbuilder-avalonia`
