### ISSUE TITLE
Apparent memory leak with tooltips

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#5336]
When showing many tooltips, memory usage seems to go up, even if showing a tooltip that has already been shown.

Screen recording with memory profiler attached: https://youtu.be/C-x_omWiweY (note that memory usage keeps going up as tooltips are shown, even when I am hovering over items that have already shown a tooltip. Memory usage stagnates when I stop moving the mouse at 0:19, then resumes going back up when I resume showing more tooltips)

Windows 10 (10.0.18363 Build 18363)
Avalonia 0.9.12

(May be related to #3808 which happens when I try to mouse over the tooltips in the same way on MacOS)

**Comment by derekantrican** [comment]
If desired, I can attempt to get a minimum reproducible example, but I have confirmed this is not my code in how I am generating the tooltip text (I tested with caching the tooltip text with the checklist objects and memory still went up).

**Comment by danwalmsley** [comment]
Did you try the new 0.10.0?

**Comment by derekantrican** [comment]
I have not yet, as last time when I tested out one of the release
candidates there were a lot of breaking changes that I had to fix. I may
see if I can upgrade just enough to test this out

**Comment by derekantrican** [comment]
@danwalmsley Both issues seem to be resolved with 0.10.0! Is there any way I can patch 0.9.12 to fix this or am I SOL on this issue until I upgrade to 0.10.0? (There's a few Avalonia-based controls that I use that are having trouble with 0.10.0)

**Comment by pr8x** [comment]
@derekantrican You could try cherrypicking the ToolTip changes from 0.10 but it might not be that easy. I would strongly suggest to upgrade to 0.10 since it brings a lot of stability and performance improvements. What issues do you encounter with 0.10 controls?

**Comment by derekantrican** [comment]
@pr8x #5348 details the main issues I'm facing with 0.10.0, but hopefully I'll come up with some workarounds. Since this is fixed in 0.10.0 I'll close the issue as such
