### ISSUE TITLE
[QUESTION/HELP] FileDialogs and MVVM

### ISSUE THREAD

**Issue by nlogozzo** [AvaloniaUI/Avalonia#5343]
Hi all,

I'm trying to figure out how to use open file dialogs (and other file dialogs) while keeping the MVVM pattern. Obviously the ViewModel shouldn't know anything about the Views. So i'm creating services to use the file dialogs, however the ShowAsync method of the dialogs requires a Window object, requiring me to pass my Window to the ViewModel and then the Service, which completely breaks the MVVM pattern. Is the anyway I can achieve using dialogs and services without requiring me to pass the Window to the service and not break the pattern?

Thanks in advanced!

**Comment by FoggyFinder** [comment]
For Qs there is a Q/A section inside `Discussions`

https://github.com/AvaloniaUI/Avalonia/discussions/categories/q-a

**Comment by nlogozzo** [comment]
Posted in Discussions.

**Comment by KvanTTT** [comment]
By the way, it's possible to convert an issue to a discussion: https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion

**Comment by nlogozzo** [comment]
Oh didn't know...I did it from the app idk if the app has that feature or I just didn't notice
