### ISSUE TITLE
Under macos, the tooltip is always displayed and will not disappear

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#5351]
Hi:
 Under macos, the tooltip is always displayed and will not disappear.
I did a test. The tooltip attribute is added to the button, the value of the tooltip will be displayed when the mouse is moved up, and it will not be displayed when the mouse is moved away. In windows and linux everything is normal, but under macos, this is a problem. After the mouse is moved up, the tooltip will always be displayed and will not disappear.

![image](https://user-images.githubusercontent.com/7692353/105682102-f8a9a800-5f2c-11eb-8cc7-925c38aea12d.png)

![image](https://user-images.githubusercontent.com/7692353/105681743-8042e700-5f2c-11eb-9082-28313e035449.png)

**Comment by maxkatz6** [comment]
What version of Avalonia are you using?
There was couple of fixes in 0.10 related to tooltip visibility.

**Comment by wuzlai** [comment]
> What version of Avalonia are you using?
> There was couple of fixes in 0.10 related to tooltip visibility.

The version is Previre5. The method I found is to use txt.SetValue(ToolTip.IsOpenProperty, false); to close the prompt. Regarding the new version, I will test it later when I have time, thank you
