### ISSUE TITLE
FluentTheme RadioButton and CheckBox MinWidth is to high by default

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#5355]
RadioButton & CheckBox  controls have a high MinWidth (120px) by default, that prevent us from use the control without tweaking MinWidth to use it without a text. Even if a text is set, like "[  ] Yes" MinWidth is superior to the control total width and it will pad.

![image](https://user-images.githubusercontent.com/113281/105715309-59c58180-5f15-11eb-937c-ce4671f3bbfa.png)

In my opinion all controls should have just the right MinWidth to be made visible without user provide a Width at all, respecting it bare functionality.

For now i fixed with:

  ```xaml
  <Style Selector="RadioButton">
      <Setter Property="MinWidth" Value="30"></Setter>
  </Style>

  <Style Selector="CheckBox">
      <Setter Property="MinWidth" Value="30"></Setter>
  </Style>
  ```

**Comment by Gillibald** [comment]
Why do we need a min-width at all?

**Comment by sn4k3** [comment]
> Why do we need a min-width at all?

Yup, if controls can show itself without defining a Width (auto-width) then this can be set to 0

**Comment by maxkatz6** [comment]
Initially was ported from winui - https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/CheckBox/CheckBox_themeresources.xaml#L293

I guess it was added there to achieve uniform layout with multiple checkboxes in one row/column, expecting them to not have width more than 120.
For Avalonia with easier styling system it makes less sense, and default can be unset,
