### ISSUE TITLE
Port new Expander Fluent style from WinUI

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#5358]
See:
https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Expander/Expander_themeresources_v2.5.xaml
https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Expander/Expander.xaml

![image](https://user-images.githubusercontent.com/3163374/105775244-7e7d2180-5f34-11eb-8ad3-e8626aefbb73.png)

(on this screenshot header font size is not part of default fluent template)

**Comment by Splitwirez** [comment]
Currently preparing to take a crack at this. Will submit a PR if successful.

**Comment by maxkatz6** [comment]
Done with https://github.com/AvaloniaUI/Avalonia/pull/5573
