### ISSUE TITLE
Binding to TabControl.Items doesn't work.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#536]
`TabControl` is a special snowflake (i.e. I hate it) and the way that it works makes it really difficult to allow `DataTemplates` that allow automatic creation of tabs from `Items`.

Need to work out how we can fix this, or just :fire: it and tell people to use a `TabStrip` and a `ContentControl`/`Carousel` (not really an option unfortunately).

**Comment by Timboski** [comment]
The `TabControl` does not currently allow individual tabs to be disabled (the disabling applies to the page rather than the header).
Here is a simple example of how the `TabStrip` and `Carousel` can be used:
```
<Window xmlns="https://github.com/avaloniaui" MinWidth="500" MinHeight="200">
  <Grid RowDefinitions="Auto,*">
    <TabStrip Grid.Row="0"  Name="TestStrip">
      <TabStripItem Content="TabName1" />
      <TabStripItem Content="TabName2" />
      <TabStripItem Content="TabName3" IsEnabled="False" Foreground="LightGray" />
    </TabStrip>
    <Carousel Grid.Row="1" SelectedIndex="{Binding #TestStrip.SelectedIndex}">
      <Button>Tab1 Button</Button>
      <TextBox>Tab2 Text</TextBox>
      <TextBlock>Tab3 can't be reached</TextBlock>
    </Carousel >
  </Grid>
</Window>
```
(NOTE: Disabling tabs had previously worked in the Perspex release.)

**Comment by grokys** [comment]
@Timboski : https://github.com/AvaloniaUI/Avalonia/pull/695

Could you see if that works for you?
