### ISSUE TITLE
ExperimentalAcrylicMaterial does not support DynamicResource

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#5360]
I often use the AcrylicMaterial, but this does not work with DynamicResource

1. Create an ExperimentalAcrylicBorder, and create an ExperiementalAcrylicMaterial in Resource Styles
2. Link that with DynamicResource in the ExperimentalAcrylicBorder in ```Material``` property.
3. Debug it, for me that throws ```Unable to cast object of type 'Avalonia.Markup.Xaml.MarkupExtensions.DynamicResourceExtension' to type 'Avalonia.Media.ExperimentalAcrylicMaterial```

System info:
 - Windows 10 20H2, compilation 19042.746
 - Avalonia 0.10.0 stable release
 -  Net 5.0

**Comment by jp2masa** [comment]
`DynamicResource` is just a binding, and the `Material` property seems to be correctly defined. I also tried to repro but it works fine for me. Could you share a repro?
