### ISSUE TITLE
Question: Programmic UI design?

### ISSUE THREAD

**Issue by TheColonel2688** [AvaloniaUI/Avalonia#5365]
I am looking for a Cross-Platform UI framework to build a a HMI visual designer, and runtime.

Avalonia fits the bill for cross platform but, I need something where i can programically create UI controls to that users can click and drag them on to a design window. Is there a way to programmically instanciate objects on to windows with Avalonia rather than just using XAML?

If you aren't familar with industrial HMIs and design software for them. Think Win Forms graphical design editor with click and drag UI design. Only dumbed down. 

I wouldn't be generating C# code I would be generating objects and then serializeing what the user has built in JSON or XML. Then when they want to run there UI design I would load the JSON/XML and rebuild the UI.

Is this doable in Avalonia, and is there enough documentation on programmically creating UI objects to make this practical for someone that is familar with Win Forms but doesn't have a deep understanding of the Avalonia interworkings?

I've looked at the [Modern.Forms](https://github.com/modern-forms/Modern.Forms) project. but that this point he hasn't committed to further development so I don't want to waste my time with a frame work that may be dead.

I'd like to do the designer itself in XAML, my issue is figureing out how to handling the runtime UI Object creation.

**Comment by kekekeks** [comment]
You can manually build object hierarchies from code, yes. You can also use ILSpy to decompile compiled XAML into somewhat readable C#.

For setting up data bindings from code see http://avaloniaui.net/docs/binding/binding-from-code

**Comment by TheColonel2688** [comment]
Other than that page, is there any other documentation on this?

**Comment by kekekeks** [comment]
I don't think there are any other docs, but the process is pretty straightforward: you just create object instances with `new` and set the needed properties from code.

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/8d21c8069d5d2bda1f1554fde3b628afb99da39f/samples/TestApplicationShared/MainWindow.cs#L77 - the example is a bit outdated (it was 5 years already), but the general concept is unchanged.

**Comment by TheColonel2688** [comment]
Sweet, looks like this is pretty doable
