### ISSUE TITLE
FontStyle is broken in the Fluent theme

### ISSUE THREAD

**Issue by arklumpus** [AvaloniaUI/Avalonia#5366]
**Describe the bug**
When the Fluent theme is enabled, setting the FontStyle property of a TextBlock to `Italic` results in text that is sometimes bold, sometimes regular, sometimes light, sometimes demi-bold, but never in italics. The weight of the text appears to change randomly every time the application is launched (_without recompiling_).

**To Reproduce**
1. Create a new Avalonia 0.10.0 application
2. Enable the Fluent theme (I replaced the contents of `Application.Styles` in `App.xaml` with `<FluentTheme Mode="Light" />`)
3. Replace the contents of the main window with something like:
    ```XAML
    <Window xmlns="https://github.com/avaloniaui"
            xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
            xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
            xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
            mc:Ignorable="d" Width="450" Height="250"
            x:Class="TestAvaloniaFonts.MainWindow"
            Title="TestAvaloniaFonts" FontSize="30">
      <Grid>
        <Grid.RowDefinitions>
          <RowDefinition Height="1*" />
          <RowDefinition Height="1*" />
          <RowDefinition Height="1*" />
          <RowDefinition Height="1*" />
        </Grid.RowDefinitions>
        <TextBlock VerticalAlignment="Center">Regular text</TextBlock>
        <TextBlock Grid.Row="1" FontWeight="Bold" VerticalAlignment="Center">Bold text</TextBlock>
        <TextBlock Grid.Row="2" FontStyle="Italic" VerticalAlignment="Center">Italic text</TextBlock>
        <TextBlock Grid.Row="3" FontWeight="Bold" FontStyle="Italic" VerticalAlignment="Center">Bold italic text</TextBlock>
      </Grid>
    </Window>

    ```
4. Compile and run the application multiple times.

**Expected behavior**
The "Italic text" should be in italics, and the "Bold Italic text" should be bold and in italics. 

**Screenshots**
Here are a few examples of the results of running the same application multiple times:
![image](https://user-images.githubusercontent.com/32712606/105930299-b629bd80-6049-11eb-8bfd-71af6b07e0fe.png)

**Desktop (please complete the following information):**
 - OS: this happens at least on Windows 10 and Ubuntu 20.04. I have not tested on macOS.
 - Version: the bug happens at least on 0.10.0-preview6, 0.10.0-rc1, 0.10.0-rc2 and 0.10.0.

**Additional context**
This is very similar to #4370, except that in this case custom fonts actually work, and it is only the default font that is broken. Also, that issue only happened on Windows, while this appears to affect Linux as well. And this only happens when the Fluent theme is enabled.

**Comment by Gillibald** [comment]
Fluent theme uses an embedded font. There was a change to the font lookup recently that might have introduced a bug. Will investigate.

**Comment by Gillibald** [comment]
The fluent theme has no italic variant defined
![Screenshot 2021-01-27 121853](https://user-images.githubusercontent.com/5928797/105984229-1a746d80-609a-11eb-82db-1fb82be73a6c.png)

**Comment by grokys** [comment]
Strange that running the application multiple times produces different results however.

**Comment by grokys** [comment]
Regarding a fix for this: I assume the best thing is for the app that wants italics to include the italic variant itself? Otherwise we'll be increasing the size of the Fluent theme for everyone.

**Comment by arklumpus** [comment]
Does the Inter font have an Italic style at all? I cannot see it in Google Fonts (https://fonts.google.com/specimen/Inter)...

Assuming the proper font file can be found, how would one go about including the font in a library? E.g. I'm building a library with a control that uses text in Italics; should I just include the font file as an embedded resource? Would this cause the file to be included twice if someone uses my library together with another library that does the same?

**Comment by danwalmsley** [comment]
I had only included the variants used by the actual theme. With Fluent the theme design is attached to the font.

I didnt include the italic variant to save space.

**Comment by Gillibald** [comment]
I will come up with a clean way to configure the default in the AppBuilder. That way we can provide an optional font package and you will be able to customize the lookup routine.

**Comment by Gillibald** [comment]
The font manager should always produce the same fallback values when the request doesn't change so this is a bug.

**Comment by Gillibald** [comment]
`typefaces.Values.FirstOrDefault()` isn't producing reliable results because there is no guaranteed ordering for ConcurretDictionary.
I have changed the fallback to trying a regular typeface first and if that fails it returns the system's default
