### ISSUE TITLE
I wanna make a PR, but I need an extern package

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#5372]
Hi there, I found a way to use the Windows Accent Color in Avalonia, but that needs Microsoft.Win32.Registry, this way detect the OS, if the OS is windows uses the Accent Color, else uses the Avalonia Default Accent Color.
I see the avalonia dependecies tree and it's a bit complex, where should be the package?
For the way to use win accent color, see [AccentColorTest](https://github.com/PieroCastillo/AccentColorTest)

**Comment by maxkatz6** [comment]
You should be able to use PInvoke to read value from regedit.

Also it should be possible to use WinRT API through MicroCom to get accent color from UISetting (and probably even subscribe on its changes).
But regedit solution is enough for first implementation as for me.

**Comment by PieroCastillo** [comment]
good idea, but, how can I use pinvoke to get regedit value?

**Comment by Sorien** [comment]
https://social.msdn.microsoft.com/Forums/vstudio/en-US/4b2075bf-bba3-45fa-941c-a145fac56e13/registry-class-using-pinvoke?forum=csharpgeneral

**Comment by jp2masa** [comment]
I think the best way would be to create a service for accent colors on `Avalonia.Visuals` for example and implementing it in `Avalonia.Win32`, and binding it here:

https://github.com/AvaloniaUI/Avalonia/blob/87a8e22f62cd231a9f9c273d364e59fa93e10ed2/src/Windows/Avalonia.Win32/Win32Platform.cs#L105

It shouldn't be a problem to install the registry package in that project. Also in the future it would be easy to add other platforms, implementing that service.

**Comment by danwalmsley** [comment]
Yes, Avalonia.Win32... and that way we can do something on OSX to read accent colour there too.

**Comment by PieroCastillo** [comment]
well, I'll find another way to do it, It's very interesting the way wrote by @jp2masa

**Comment by Sorien** [comment]
Btw you should be able to detect accent color changes by listening to WM_SETTINGCHANGE

**Comment by PieroCastillo** [comment]
I found a way to do it, [AccentColors.cs#L50](https://github.com/sourcechord/FluentWPF/blob/b70731c6d026b2087dbf41656ff53854d48813d8/FluentWPF/Resources/AccentColors.cs#L50); this code works well with Avalonia, that does not have some dependency, it's perfect

**Comment by PieroCastillo** [comment]
WORKS WELL, JUST SEE THIS
![image](https://user-images.githubusercontent.com/39932324/106088553-3147ae00-60f4-11eb-82a1-7fc4b53ab45d.png)
![image](https://user-images.githubusercontent.com/39932324/106088563-36a4f880-60f4-11eb-99b1-570044c1cf7f.png)
![image](https://user-images.githubusercontent.com/39932324/106088594-445a7e00-60f4-11eb-90a0-128a0607b944.png)
in few I'm going to publish the PR :DDDDD
