### ISSUE TITLE
Rotating an ArcSegment via Animation creates artefacts

### ISSUE THREAD

**Issue by darinkes** [AvaloniaUI/Avalonia#5381]
**Describe the bug**
Rotating an ArcSegment via Animation creates artefacts.

**To Reproduce**
1. https://github.com/darinkes/AvaloniaUITests

**Expected behavior**
No artefacts

**Screenshots**
See https://www.youtube.com/watch?v=ijXDyM4Xlhg

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.10.0

**Additional context**
Only happens while executing the Application. Preview in Visual Studio looks fine.
Setting an Background to the hosting Control works around this problem.

**Comment by kekekeks** [comment]
@grokys looks like invalid render bounds calculation

**Comment by darinkes** [comment]
Oh, forgot to mention. Also just happens with Path.StrokeLineCap="Round".

**Comment by DrWenz** [comment]
Can confirm, only happens with StrokeLineCap="Round".
Set background to the hosting grid makes no difference to me.

Artefacts cleaned on window resize.

- OS: MacOS Monterey 12.0.1
- Version 0.10.10

https://user-images.githubusercontent.com/40403356/144754502-5cf5fba8-24eb-4b65-bbae-833b91f11fd0.mov


https://user-images.githubusercontent.com/40403356/144754528-8eba1803-6539-4e0d-87ab-49fddc7f7532.mov

**Comment by timunie** [comment]
Hi @darinkes ,

I think I found the root cause for this issue with the help of @danwalmsley . Submitted a PR for this already. I also tested it in your provided sample. Send you a PR for testing purpose, if you are still interested. 

Happy coding
Tim 

/cc @jmacato @kekekeks @DrWenz
