### ISSUE TITLE
Button disabled when inside DataTemplate

### ISSUE THREAD

**Issue by thiago-tota** [AvaloniaUI/Avalonia#5386]
I have an ItemsControl where Items comes from ViewModel.
The binding happens properly however one of the items of the DataTemplate is a button.
I'm aware if the Command property of the Button is not implemented in the ViewModel the button will be disabled however, this this is not the case.
If I copy the button control outside of the DataTemplate it's properly enabled when I run he application.

Find below the ItemsControl in the axaml file:
```
            <ItemsControl Items="{Binding PermanentMeetings}">
              <ItemsControl.ItemsPanel>
                <ItemsPanelTemplate>
                  <WrapPanel/>
                </ItemsPanelTemplate>
              </ItemsControl.ItemsPanel>
              <ItemsControl.ItemTemplate>
                <DataTemplate >
                  <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                    <TextBlock Text="{Binding Name}" Width="210" Margin="5" />
                    **<Button Content="Open" HorizontalContentAlignment="Center" Width="80" Margin="0,5,5,0"
                            Command="{Binding OpenMeetingCommand}" CommandParameter="{Binding Id}" />**
                  </StackPanel>
                </DataTemplate>
              </ItemsControl.ItemTemplate>
            </ItemsControl>
```
The line in **Bold** is the problem.
And below the axaml form running:
![image](https://user-images.githubusercontent.com/30416982/106317118-91516800-624c-11eb-8456-cbd538b9eca4.png)

Note that the button at the top that is enabled is exactly the same as in the line in Bold inside DataTemplate, I just copied to some part before the ItemsConstorl tag.

Below is part of the ViewModel used by this axaml:
![image](https://user-images.githubusercontent.com/30416982/106317328-f1e0a500-624c-11eb-8749-b76cb0fed877.png)

Please, advise.
Thanks in advance.

Best regards,
Thiago Tota.

**Comment by jp2masa** [comment]
Inside the `DataTemplate` the `DataContext` is the item, so you will have to bind to parent `DataContext`, this probably works: `{Binding $parent.DataContext.OpenMeetingCommand}`.

**Comment by thiago-tota** [comment]
Hi @jp2masa, thank you very much for your reply.
I completely forgot about the the command be in the parent context.
The code you suggested didn't work but gave me the direction that I needed.
I named the ItemsSource control and added ElementName=ItemsSourceControlName, Path=DataContext.OpenMeetingCommand and then worked.

Find below how the final axaml is:
```
            <ItemsControl Items="{Binding PermanentMeetings}" x:Name="ParentListControl">
              <ItemsControl.ItemsPanel>
                <ItemsPanelTemplate>
                  <WrapPanel/>
                </ItemsPanelTemplate>
              </ItemsControl.ItemsPanel>
              <ItemsControl.ItemTemplate>
                <DataTemplate >
                  <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                    <TextBlock Text="{Binding Name}" Width="210" Margin="5" />
                    <Button Content="Open" HorizontalContentAlignment="Center" Width="80" Margin="0,5,5,0"
                            Command="{Binding ElementName=ParentListControl, Path=DataContext.OpenMeetingCommand}" CommandParameter="{Binding Id}" IsEnabled="True"/>
                  </StackPanel>
                </DataTemplate>
              </ItemsControl.ItemTemplate>
```

Thank you very much!!

**Comment by jp2masa** [comment]
Just to add, if you prefer you can also use the syntax: `{Binding #ParentListControl.DataContext.OpenMeetingCommand}`.
