### ISSUE TITLE
Drawing to custom control is shifted one pixel to the left

### ISSUE THREAD

**Issue by Fido789** [AvaloniaUI/Avalonia#5393]
Hello,

I am trying to make a custom control, but bounds for drawing seems to be incorrect, x-coordinate is shifted one pixel to the left, as you can see on the following image:

![image](https://user-images.githubusercontent.com/12424763/106368597-2e92c600-634b-11eb-8d76-d38b6be1df79.png)

**To Reproduce**

1. Run the following project [AvaloniaDrawingIssue.zip](https://github.com/AvaloniaUI/Avalonia/files/5898758/AvaloniaDrawingIssue.zip)
2. See the issue

**Expected behavior**

Red rectangle is fully visible

Am I missing something or is this a bug?

**Comment by grokys** [comment]
Not 100% sure this is what's happening (not had time to look at the repro yet) but Avalonia like most other modern rendering frameworks uses a drawing system where physical pixels are _centered_ on the coordinate you specify. This means that depending on the scaling if your screen, at times a pixel may be shifted left by 1 physical pixel or drawn blurry if you draw at whole pixel coordinates. 

Controls like `Border` account for this automatically, but if you're doing the drawing yourself you'll have to account for it yourself by shifting by half the line width (e.g. 0.5 if you have a 1-pixel line).

A few references for other frameworks:

For WPF: https://stackoverflow.com/a/7663956
For SVG: https://stackoverflow.com/a/34229584
For HTML canvas: https://usefulangle.com/post/17/html5-canvas-drawing-1px-crisp-straight-lines

**Comment by Fido789** [comment]
> Not 100% sure this is what's happening (not had time to look at the repro yet) but Avalonia like most other modern rendering frameworks uses a drawing system where physical pixels are _centered_ on the coordinate you specify. This means that depending on the scaling if your screen, at times a pixel may be shifted left by 1 physical pixel or drawn blurry if you draw at whole pixel coordinates.
> 
> Controls like `Border` account for this automatically, but if you're doing the drawing yourself you'll have to account for it yourself by shifting by half the line width (e.g. 0.5 if you have a 1-pixel line). So instead of drawing a box from say (0,0) to (100, 100) you would draw from (0.5,0.5) to (99.5,99.5).
> 
> A few references for other frameworks:
> 
> For WPF: https://stackoverflow.com/a/7663956
> For SVG: https://stackoverflow.com/a/34229584
> For HTML canvas: https://usefulangle.com/post/17/html5-canvas-drawing-1px-crisp-straight-lines

Yes, that could definitely be it. Shifting by 0.5f seems to fix the issue, I have tried that before. I was just confused that x and y coordinates behave differently and didn't want to introduce more problems then I solve, but after your explanation it seems to be safe to fix it that way.

Thank you, grokys, for the quick and helpful answer!
