### ISSUE TITLE
[Render Animation Bug] Custom Skia Rendering has problems with Avalonia Animation

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#5394]
**Describe the bug**
Animation does not render correctly the Skia custom render.

**To Reproduce**
1. Make an Skia custom render.
2. Add this to control, the render must use any avalonia property; an add the property in ```AffectsRender<Control>```
3. Animate the property.

**Expected behavior**
In Avalonia VS previewer and Window at runtime should be showed the animation with Skia Custom Render.

**Screenshots**

https://user-images.githubusercontent.com/39932324/106369042-44d55d80-631c-11eb-9813-c11c786aae9d.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Version: Avalonia 0.10.0 stable release

**Additional context**
In VS previewer is shower like I expected, but at runtime is crashed.

Code:

[Arc Control Custom Render](https://github.com/PieroCastillo/Aura.UI/blob/master/src/Aura.UI/Rendering/ArcRender.cs)
[Arc Control Source](https://github.com/PieroCastillo/Aura.UI/blob/master/src/Aura.UI/Controls/Colouring/Arc/Arc.cs)
[Arc Control Example with Animation](https://github.com/PieroCastillo/Aura.UI/blob/master/Tests/UI.Tests/MainWindow.xaml)

**Comment by kekekeks** [comment]
`ICustomDrawingOperation:Render` can be (and usually is) called from the render thread. You can't access AvaloniaProperty values from the render thread. You need to embed the values into your custom drawing operation in `Control:Render` call.

**Comment by PieroCastillo** [comment]
yeah, works ok, I found to do the animation I need create a new Rect, just creating a new Rect works the Animation, Thx u
