### ISSUE TITLE
Overlapping Сheckbox in MenuItem

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaUI/Avalonia#5397]
**Describe the bug**
Overlapping Сheckbox in MenuItem

**To Reproduce**
1. Run the RenderDemo
2. Click on "Rendering" at menu
3. See error

**Expected behavior**
Тo Сheckbox overlap in MenuItem

**Screenshots**
![image](https://user-images.githubusercontent.com/2669927/106379542-c7622980-63bd-11eb-901f-5dac00296552.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Current master https://github.com/AvaloniaUI/Avalonia/commit/1a39210febf92e9e87b3ebacca9b56d99e660913

**Additional context**
- Monitor scaling: 125%

**Comment by maxkatz6** [comment]
It's seems to be an issue only with overlay popups
