### ISSUE TITLE
Work out how to handle lazily-evaluated ItemsControl.Items

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#54]
If a lazily-evaluated IEnumerable is assigned to `ItemsControl.Items` then stuff breaks, as the sequence gets re-enumerated every time the control accesses the items.

Some possible solutions:
1. Have two separate properties as in WPF: `Items` and `ItemsSource`. This feels a little messy to me, having two properties to do essentially the same thing, and making one read-only in certain situations etc as in WPF.
2. Change the type of `Items` from `IEnumerable` to `ICollection`.
3. Throw an exception if value doesn't implement `ICollection` or `IList` etc.

@SuperJMN thoughts? Any other ideas?

**Comment by danwalmsley** [comment]
In WPF the Items type is ItemsCollection.

```
ItemCollection : CollectionView, IList, ICollection, 
```

**Comment by grokys** [comment]
The `Items` collection in WPF is a different thing: the equivalent in WPF is `ItemsSource` which is an `IEnumerable`.

**Comment by kekekeks** [comment]
ItemsControl needs to work with finite enumerables anyway, so we might as well use IList there

**Comment by grokys** [comment]
We now have `ItemsSourceView` in the tree (ported from WinUI). We should use this in `ItemsControl` to handle this issue. Unfortunately this will result in breaking changes (templates will need to bind to the `ItemsSourceView` instead of `Items`) so going to fix this as part of other breaking changes in #3388.
