### ISSUE TITLE
TextBox Wordwrap doesn't work without AcceptsReturn enabled

### ISSUE THREAD

**Issue by garyhertel** [AvaloniaUI/Avalonia#5402]
**Describe the bug**
The TextBox.Wordwrap doesn't work without AcceptsReturn also enabled. Pretty minor since I can enable that, but kind of confusing when testing it out and having to look at the Control Catalog to see why it wasn't working.

`<TextBox AcceptsReturn="True" TextWrapping="Wrap" ...`

**To Reproduce**
1. Disable AcceptsReturn on ControlCatalog TextBox that has TextWrapping enabled
1. Go to Control Catalog TextBox
4. See text not wrapping

**Expected behavior**
Text should wrap without AcceptsReturn enabled

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.10.0

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/3618bccd8e1d7d2fbdf5a549dfce6c1c7090ab35/src/Avalonia.Controls/TextBox.cs#L186 this should be set to disabled when TextWrapping is enabled
