### ISSUE TITLE
DataGrid + FluentTheme + Validation with bad visual styles (unreadable error message)

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#5403]
When validation errors shows on a datagrid with a light fluent theme, the error message is not readable due color combination:

![image](https://user-images.githubusercontent.com/113281/106401904-bc8bb100-641e-11eb-8164-f4d5ac07db30.png)

**Comment by maxkatz6** [comment]
We need to revert this PR https://github.com/AvaloniaUI/Avalonia/pull/4964 for DataGrid or better to use separated validation block style for it.
