### ISSUE TITLE
All Styles don't work.

### ISSUE THREAD

**Issue by hopeko** [AvaloniaUI/Avalonia#5406]
Code built on Microsoft Visual Studio Community 2019 Version 16.8.4

**Describe the bug**
All Styles don't work.

**To Reproduce**
1. Create a new Avalonia Empty project
2. Add code to MainWindow.axaml
```cs
  <Window.Styles>
    <Style Selector="Button:pointerover">
      <Setter Property="Background" Value="Red"/>
    </Style>
    <Style Selector="TextBox:focus /template/ Border#border">
      <Setter Property="BorderBrush" Value="Red" />
    </Style>
    <Style Selector="TextBox:pointerover /template/ Border#border">
      <Setter Property="BorderBrush" Value="Red"/>
    </Style>
  </Window.Styles>

  <StackPanel>
    <Button Content="Test" />
    <TextBox Text="Some text" />
  </StackPanel>
```
3. Build the project
4. Start the project

**Comment by maxkatz6** [comment]
Why Button doesn't work:
ContentPresenter inside of template changes background, not the whole button. This behavior is by design, otherwise it would break expected from WPF behavior. See https://github.com/AvaloniaUI/Avalonia/pull/2662#issuecomment-515764732 and related PR.

Why TextBox doesn't work:
There is no Border with name "border" in Fluent theme - https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/TextBox.xaml

Fixed styles:
```xaml
<Style Selector="Button:pointerover /template/ ContentPresenter">
  <Setter Property="Background" Value="Red"/>
</Style>
<Style Selector="TextBox:focus /template/ Border#PART_BorderElement">
  <Setter Property="BorderBrush" Value="Red" />
</Style>
<Style Selector="TextBox:pointerover /template/ Border#PART_BorderElement">
  <Setter Property="BorderBrush" Value="Red"/>
</Style>
```

**Comment by hopeko** [comment]
Why does the app use Fluent theme, not Default. How can I know what theme the app is using and how can I change to another?

**Comment by danwalmsley** [comment]
Theme is defined in your App.xaml

**Comment by hopeko** [comment]
> Theme is defined in your App.xaml

I saw it. Thanks!

**Comment by TesAnti** [comment]
For those who don't want their TextBox appearance change when focus changes(maybe you are making onscreen keyboard as me):
```
<Style Selector="TextBox">
    <Setter Property="BorderThickness" Value="1" />
    <Setter Property="BorderBrush" Value="#ccc" />
</Style>
<Style Selector="TextBox /template/ Border#PART_BorderElement">
    <Setter Property="BorderThickness" Value="1" />
    <Setter Property="BorderBrush" Value="#ccc" />
</Style>
<Style Selector="TextBox:focus /template/ Border#PART_BorderElement">
    <Setter Property="BorderThickness" Value="1" />
    <Setter Property="BorderBrush" Value="#ccc" />
</Style>
```
