### ISSUE TITLE
Tooltip + FluentTheme have a MaxWidth by default?

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#5408]
I'm getting this by default with FluentLight Theme, looks like tooltips have maxwidth set?

![image](https://user-images.githubusercontent.com/113281/106497094-89483100-64b5-11eb-9d1c-9e25586bd9dd.png)

**Comment by maxkatz6** [comment]
Yes.
Tooltip width is limited.
If you are using Tooltip.Tip with string value, it will automatically use text wrapping.
For custom content inside of tooltip you need to set wrapping manually in your text blocks.

Or remove maxwidth

**Comment by rprimora-pricer** [comment]
For me this is being cut off.

![image](https://github.com/AvaloniaUI/Avalonia/assets/91051530/24d47f6c-13f5-4e4c-997b-dbaad36a3642)

This is my axaml for this control.

```axaml
<Border VerticalAlignment="Top" Margin="0,10,0,0" IsVisible="{TemplateBinding Text, Converter={StaticResource StringToBoolConverter}}">
   <Grid ColumnDefinitions="Auto,*">
      <Svg Grid.Column="0" Path="/Assets/Images/Error.svg" VerticalAlignment="Top" Height="24" Width="24"/>
      <TextBlock x:Name="PART_Text" Grid.Column="1" TextTrimming="CharacterEllipsis" Margin="5,3,0,0" Text="{TemplateBinding Text}">
         <ToolTip.Tip>
            <TextBlock Text="{TemplateBinding Text}" TextTrimming="None" TextWrapping="Wrap"/>
         </ToolTip.Tip>
      </TextBlock>
   </Grid>
</Border>
```
