### ISSUE TITLE
I can't clone AvaloniaUI onto my MacBook Pro!

### ISSUE THREAD

**Issue by ajtruckle** [AvaloniaUI/Avalonia#5409]
I have tried multiple times:

```
git clone https://github.com/AvaloniaUI/Avalonia.git
Cloning into 'Avalonia'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (14/14), done.
fatal: the remote end hung up unexpectedly.47 MiB | 2.58 MiB/s
fatal: early EOF
fatal: index-pack failed
```

It happens over and over and over.

**Comment by maxkatz6** [comment]
It's not an issue with Avalonia.

Have you checked possible solutions from the internet?
Something like this one https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed

**Comment by ajtruckle** [comment]
I will try again. But this is a nightmare. It should be a simple task to down and install something like this. But I’ll likely give up.

Last night I managed to download AvalonStudio and it won’t compile because of JSON feed that no longer exists.

Fighting a losing battle. Nothing worked. And this is a very good new laptop with latest updates.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kekekeks** [comment]
>It should be a simple task to down and install something like this

You don't need to download the source code, follow instructions [here](http://avaloniaui.net/docs/quickstart/create-new-project) instead.

**Comment by ajtruckle** [comment]
That does not help. This is Visual Studio for Mac and not Windows. I can't see a "Market Place".

Andy

**Comment by Deadpikle** [comment]
You don't happen to be on Debian 10 and affected by this NuGet bug, do you? https://twitter.com/nuget/status/1355252975678189569

**Comment by ajtruckle** [comment]
I am afraid I do not even know what Debian 10 is. Sorry.

**Comment by pr8x** [comment]
I am closing this since it doesn't seem to be directly related to Avalonia. In case you have further questions about how to get started with Avalonia consider asking about it in the discussions (https://github.com/AvaloniaUI/Avalonia/discussions)
