### ISSUE TITLE
DoubleTapped cannot be generated using touch input

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#5412]
Avalonia 0.10.0
The ```TouchDevice``` never raises```DoubleTapped```  events as the code does not support it.

The ```Gestures.PointerPressed``` method uses the ```ClickCount``` to raise ```DoubleTapped```  events. The ```ClickCount``` comes from the ```MouseDevice.PointerPressed``` or ```TouchDevice.PointerPressed``` events via the ```obsoleteClickCount``` parameter in 
```PointerPressedEventArgs``` . When ```ClickCount``` is > 1 a ```DoubleTapped``` event is raised.

The ```MouseDevice``` raises ````PointerPressed``` events with the ```PointerPressedEventArgs``` ```obsoleteClickCount``` parameter > 1. 

The TouchDevice only ever raises PointerPressed events with obsoleteClickCount =1.

**Comment by kekekeks** [comment]
We should probably remove that ClickCount logic from PointerPressed.
