### ISSUE TITLE
When trying to have multiple styles the Program throws exception

### ISSUE THREAD

**Issue by WakanaYuki** [AvaloniaUI/Avalonia#5416]
**Describe the bug**
When I have multiple styles inside <Window.Styles> Avalonia throws and exception

**To Reproduce**

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
		xmlns:gif="clr-namespace:AvaloniaGif;assembly=AvaloniaGif"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
		MinWidth="800" MinHeight="450"
		Width="800" Height="450"
        x:Class="AnimationTest.MainWindow"
        Title="AnimationTest">
	<Window.Styles>
		<Style Selector="Image#intro">
			<Setter Property="Width" Value="5"/>
			<Setter Property="Height" Value="5"/>
			<Style.Animations>
				<Animation Delay="0:0:1" Duration="0:0:2">
					<KeyFrame Cue="0%">
						<Setter Property="Width" Value="800"/>
						<Setter Property="Height" Value="450"/>
					</KeyFrame>
					<KeyFrame Cue="100%">
						<Setter Property="Height" Value="5"/>
						<Setter Property="Width" Value="5"/>
					</KeyFrame>
				</Animation>
			</Style.Animations>
		</Style>
		<Style Selector="Grid#grd_test">
			<Style.Animations>
				<Animation Delay="0:0:1" Duration="0:0:2">
					<KeyFrame Cue="0%">
						<Setter Property="Opacity" Value="0.0"/>
					</KeyFrame>
					<KeyFrame Cue="100%">
						<Setter Property="Opacity" Value="1.0"/>
					</KeyFrame>
				</Animation>
			</Style.Animations>
		</Style>
	</Window.Styles>
	<Grid Name="grd_intro" MinWidth="1">
		<Image Name="intro" Grid.Column="1"
               Stretch="UniformToFill"
               gif:GifImage.SourceUriRaw="resm:AnimationTest.Assets.intro.gif" gif:GifImage.IterationCount="0"/>
	</Grid>
	<Grid Name="grd_test">
	</Grid>
</Window>
```

**Exception**
XAMLIL	Unable to find a setter that allows multiple assignments to the property Content of type Avalonia.Controls:Avalonia.Controls.ContentControl Line 1, position 2.	AnimationTest	C:\Users\user\source\repos\AnimationTest\AnimationTest\MainWindow.axaml

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Avalonia v0.10.0, .NET 5

**Comment by danwalmsley** [comment]
Wrap it inside <Styles> tags.

**Comment by WakanaYuki** [comment]
Done, sorry didn't notice I need 3 of these `

**Comment by danwalmsley** [comment]
might be that in older version it didnt matter. Prob we will fix this in future... we have other issues open for that.

**Comment by WakanaYuki** [comment]
How would it be done in a new/current version? Inside code or?

**Comment by WakanaYuki** [comment]
@danwalmsley which other issues did you refer to? And is having multiple animation currently possible in code or is it just not working in XAML?

**Comment by maxkatz6** [comment]
@WakanaYuki can you create another issue for animators instead updating this?

**Comment by jp2masa** [comment]
I think the problem here is that the `Window` has 2 children, as stated by the error.

**Comment by WakanaYuki** [comment]
@jp2masa Thank you so much, that was actually the issue, I totally forgot that I have 2 grids in the MainWindow. I was way too focused on the <Style Selector="######"> part...
