### ISSUE TITLE
 About the signature of the package .app under MacOS

### ISSUE THREAD

**Issue by wuzlai** [AvaloniaUI/Avalonia#5418]
I generated the .app package with the demo by myself, referring to the signing steps on the avalonia official website, it can be signed and notarized successfully. But I will include the cefnet project and use the script to make it into an .app package. When taking the steps of signing and notarization under macos, the step of signing is always abnormal. Prompt the following information:

[INFO] Signing app file
/Users/mesign/Documents/cefdemo/cef-84_4-example-master/bin/Sign/AvaloniaApp.app: replacing existing signature
/Users/mesign/Documents/cefdemo/cef-84_4-example-master/bin/Sign/AvaloniaApp.app: code object is not signed at all
In subcomponent: /Users/mesign/Documents/cefdemo/cef-84_4-example-master/bin/Sign/AvaloniaApp.app/Contents/Frameworks/Chromium Embedded Framework.framework
mesign@MeSigndeMacBook-Air Sign % codesign --verify --verbose /Users/mesign/Documents/cefdemo/cef-84_4-example-master/bin/Sign/AvaloniaApp.app
/Users/mesign/Documents/cefdemo/cef-84_4-example-master/bin/Sign/AvaloniaApp.app: code has no resources but signature indicates they must be present

![image](https://user-images.githubusercontent.com/7692353/106689017-3d5ad080-660a-11eb-8c5c-3c64214e7aaf.png)

The signature commands used are as follows:
`#!/bin/basih
APP_NAME="/Users/mesign/Downloads/wzl/mesignapp/mesignapp.app"
ENTITLEMENTS="/Users/mesign/Downloads/wzl/mesignapp/MeSignAPP.entitlements"
SIGNING_IDENTITY="Developer ID Application: MeSince Technology Limited (99M3VBRE6Z)" # matches Keychain Access certificate name
find "$APP_NAME/Contents/MacOS/"|while read fname; do
if [[ -f $fname ]]; then
echo "[INFO] Signing $fname"
codesign --force --timestamp--options=runtime --entitlements "$ENTITLEMENTS" --sign "$SIGNING_IDENTITY" "$fname"
fi
done

echo "[INFO] Signing app file"

codesign --force --timestamp --options=runtime --entitlements "$ENTITLEMENTS" --sign "$SIGNING_IDENTITY" "$APP_NAME"
`

The file structure is as follows:

![image](https://user-images.githubusercontent.com/7692353/106689061-506da080-660a-11eb-8b84-376a18edfeb5.png)
![image](https://user-images.githubusercontent.com/7692353/106689067-54012780-660a-11eb-9a3e-5e238b1c35f6.png)
![image](https://user-images.githubusercontent.com/7692353/106689079-582d4500-660a-11eb-9486-5863b40c1e87.png)
I have searched a lot on the Internet, I hope someone can provide clues, thank you. Personally guess which files may not meet the requirements, but which one cannot be located.

The following is the signing process and the result of verifying the signature
![image](https://user-images.githubusercontent.com/7692353/106689335-c7a33480-660a-11eb-9362-121c7c88706c.png)

Has anyone encountered this situation before and urgently needs help, thank you

**Comment by kekekeks** [comment]
Try adding `--deep` option to codesign.

**Comment by wuzlai** [comment]
> Try adding `--deep` option to codesign.

Thank you for your prompt reply. I added --deep and tested it several times. There was no obvious abnormality during the signing process. It just prompted "A timestamp was expected but was not found.", but the signature was verified (codesign - In the process of verify --verbose), an exception is prompted: code has no resources but signature indicates they must be present. I feel like I'm going crazy.
The following is my order, do you know how to deal with it. For help.

#!/bin/basih
APP_NAME="/Users/mesign/Downloads/wzl/mesignapp/mesignapp.app"
ENTITLEMENTS="/Users/mesign/Downloads/wzl/mesignapp/MeSignAPP.entitlements"
SIGNING_IDENTITY="Developer ID Application: MeSince Technology Limited (99M3VBRE6Z)" # matches Keychain Access certificate name
find "$APP_NAME/Contents/MacOS/"|while read fname; do
    if [[ -f $fname ]]; then
        echo "[INFO] Signing $fname"
        codesign --force --deep  --timestamp --options=runtime --entitlements "$ENTITLEMENTS" --sign "$SIGNING_IDENTITY" "$fname"
    fi
done

echo "[INFO] Signing app file"

codesign --force --deep  --timestamp --options=runtime --entitlements "$ENTITLEMENTS" --sign "$SIGNING_IDENTITY" "$APP_NAME"

Below is the exception message and related screenshots. Could you please help me see if you are free. thank you very much

[INFO] Signing app file
/Users/mesign/Downloads/wzl/mesignapp/mesignapp.app: replacing existing signature
/Users/mesign/Downloads/wzl/mesignapp/mesignapp.app: A timestamp was expected but was not found.
In subcomponent: /Users/mesign/Downloads/wzl/mesignapp/mesignapp.app/Contents/Frameworks/mesignapp Helper.app
mesign@MeSigndeMacBook-Air mesignapp %  codesign --verify --verbose   /Users/mesign/Downloads/wzl/mesignapp/mesignapp.app
/Users/mesign/Downloads/wzl/mesignapp/mesignapp.app: code has no resources but signature indicates they must be present
mesign@MeSigndeMacBook-Air mesignapp % 

![image](https://user-images.githubusercontent.com/7692353/106722731-44e99c00-6641-11eb-9be8-99aecff67aae.png)

**Comment by kekekeks** [comment]
Your internet firewall is misconfigured (could also be ISP issue), see https://developer.apple.com/forums/thread/8187

**Comment by wuzlai** [comment]
> Your internet firewall is misconfigured (could also be ISP issue), see https://developer.apple.com/forums/thread/8187

thank you,My local network is normal. It is normal to use the demo signature notarization, that is, it will not work to sign the package containing the cef file. I am not familiar with macos packages. Can the official teach us how to package this macos package that references the framework? The packaging on the official website is relatively simple.

**Comment by wuzlai** [comment]
> Your internet firewall is misconfigured (could also be ISP issue), see https://developer.apple.com/forums/thread/8187

I suspect it’s the file structure problem. Tip: code has no resources but signature indicates they must be present

**Comment by VamsiKrishna1805** [comment]
Hi @wuzlai , Have you found the solution for this issue? if yes, Please let me know that.

FYI, I tried to codesign and verified it and still facing code has no resources but signature indicates they must be present.
![Code sign issue](https://user-images.githubusercontent.com/57950146/208967304-0ea0455a-032e-402a-a60e-6ff529ab534c.jpg)

**Comment by wuzlai** [comment]
> Hi @wuzlai , Have you found the solution for this issue? if yes, Please let me know that.
> 
> FYI, I tried to codesign and verified it and still facing code has no resources but signature indicates they must be present. ![Code sign issue](https://user-images.githubusercontent.com/57950146/208967304-0ea0455a-032e-402a-a60e-6ff529ab534c.jpg)



> Hi @wuzlai , Have you found the solution for this issue? if yes, Please let me know that.
> 
> FYI, I tried to codesign and verified it and still facing code has no resources but signature indicates they must be present. ![Code sign issue](https://user-images.githubusercontent.com/57950146/208967304-0ea0455a-032e-402a-a60e-6ff529ab534c.jpg)

Sorry, I just saw it today, did you solve it? , I have solved this problem, if you need, you can leave an email. I will take the time to provide you with my signed script

**Comment by VamsiKrishna1805** [comment]
Hi @wuzlai , Thanks for the reply. I resolved this issue.

**Comment by danparisd** [comment]
> > Hi @wuzlai , Thanks for the reply. I resolved this issue.
> 
> Ok, I'm relieved then, good luck.

I'm having this issue. If you can provide some detail as to what to look for I would appreciate it.

**Comment by XamNag** [comment]
Hi @wuzlai  I am facing same issue, can you provide the solution?

**Comment by mohdimas** [comment]
hi @XamNag,
I encounter the same issue, did you find a solution?

**Comment by berkansasmaz** [comment]
I am facing the same issue, can you provide a solution?
