### ISSUE TITLE
Massive perfomance regression from 0.10.0-rc1 to 0.10.0-rc2

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/Avalonia#5419]
**Describe the bug**
For 0.10.0-rc1 it takes about 61mb for "hello world" avalonia application.
![image](https://user-images.githubusercontent.com/53405089/106740710-705d8e00-6623-11eb-921b-77729e8c7956.png)

For 0.10.0-rc2 and above it takes about 123mb for "hello world" avalonia application.
![image](https://user-images.githubusercontent.com/53405089/106740984-ca5e5380-6623-11eb-9ec9-4f4369baa06b.png)

RAM memory usage for every template is the same, but GPU memory  usage has increased a lot

**To Reproduce**
Just run the usual Avalonia template

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by Takoooooo** [comment]
The default value of AllowEglInitialization have changed in https://github.com/AvaloniaUI/Avalonia/commit/e3a7b78ec366c3cade70b36ca0dc41b1ebbd064a#diff-389ceea3d8f7a93304301eeb63774e31101da61f1ba97faceadf9e7bc036ad5c
And it caused some misunderstanding from my side

**Comment by danwalmsley** [comment]
@Takoooooo this was overlooked, sorry about that :)
