### ISSUE TITLE
ItemsControl / Drop Down inserting itself as its own template

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#542]
I did this, index items was just a list of strings....

<DropDown Items="{Binding IndexItems, Mode=TwoWay}" MinHeight="20" />

It gave me a drop down, and each item in the drop down was itself a drop down. instead of just a textblock.

I will post a repro commit shortly.

**Comment by grokys** [comment]
This should now be fixed.
