### ISSUE TITLE
How to use the backend of dynamic rendering? Ex: vulkan / metal / DirectX 12

### ISSUE THREAD

**Issue by zoujiaqing** [AvaloniaUI/Avalonia#5428]
Skia support many rendering backends, such as how do vulkan、metal、D3D, call them in Avalonia?

macOS / iOS : metal
FreeBSD / Linux / Android : vulkan
Windows : DirectX

**Comment by MarchingCube** [comment]
Currently only OpenGL has a builtin support via `OpenGlControlBase`. You can also use raw Skia directly via custom drawing operations (`ICustomDrawOperation`) and this would allow you to interface with your backend of choice. Avalonia still does not give a builtin way of using Direct3D or Vulkan backends but you can provide it yourself via `ISkiaGpu`.

Actual interop also varies based on how do you implement your rendering, if you render to a texture and let Skia use it then it will be simpler than trying to setup a framebuffer from a control.

**Comment by maxkatz6** [comment]
See https://github.com/AvaloniaUI/Avalonia/issues/9925
It's now possible to integrate directx and vulkan as well. Samples here https://github.com/AvaloniaUI/Avalonia/tree/master/samples/GpuInterop
Available in nightly, also will be part of 11.0-preview5 soon.
