### ISSUE TITLE
THE screen is always black when running on the MIPS 64EL

### ISSUE THREAD

**Issue by Aaronlog** [AvaloniaUI/Avalonia#5429]
How can I solve this problem? Do I need to modify the SKIA source code and recompile it

**Comment by kekekeks** [comment]
Provide more info about your environment.
1) Linux distro?
2) X11, XWayland, fbdev, libdrm?
3) With or without GPU acceleration

**Comment by Aaronlog** [comment]
development environment 
1.The Linux distribution  is Ubuntu
2.display library is X11
3.machine has GPU acceleration

**Comment by Aaronlog** [comment]
This is what the interface looks like after the project is run
![D8855BE](https://user-images.githubusercontent.com/41666145/107106156-2b289e80-6865-11eb-84d9-24fde8c0445e.jpg)

**Comment by maxkatz6** [comment]
@Aaronlog Verbose logs can be useful
```
   .LogToTrace(LogEventLevel.Verbose)
```

**Comment by kekekeks** [comment]
Try adding 
```cs
.With(new X11PlatformOptions
{
    UseGpu = false
});
```
to your app builder.

**Comment by Aaronlog** [comment]
@kekekeks When useGPU is set to false, the entire window is not visible, but the taskbar is

**Comment by Aaronlog** [comment]
@maxkatz6 After adding this LogToTrace(logeventlevel.verbose) attribute, I did not see the related log file in the whole project directory. Could you please tell me how to use this log in detail? Thank you very much

**Comment by maxkatz6** [comment]
@Aaronlog Trace logging writes messages to the Trace output.
If you need file logging, you need to implement your Sink with [ILogSink](http://reference.avaloniaui.net/api/Avalonia.Logging/ILogSink/) and set you instance to [Logger.Sink](http://reference.avaloniaui.net/api/Avalonia.Logging/Logger/430541E8).

**Comment by Aaronlog** [comment]
@maxkatz6 Hello, logging has been added, but after the project has run, there are no error messages in the log file.It is still not known what caused the Windows to appear black.By the way, do you have a MIPS running environment?

**Comment by maxkatz6** [comment]
@Aaronlog I don't have anything suitable for development.

**Comment by Gillibald** [comment]
I don't think SkiaSharp has a MIPS build

**Comment by Aaronlog** [comment]
@maxkatz6 
The problem of black screen has been solved. The previous version of SkiaSharp is 1.68.0, but now we want to release it with the version of Avalonia0.10. SkiaSharp 2.80.2 has been compiled, but I don't know how to compile libharfbuzzsharp

**Comment by Gillibald** [comment]
That's the same as the libSkiaSharp bits. Just modify the build script. Both native parts work with gn.
