### ISSUE TITLE
Lines are not being trimmed in single-line TextBox

### ISSUE THREAD

**Issue by luthfiampas** [AvaloniaUI/Avalonia#5438]
**Describe the bug**
If we paste text that contains multiple lines in a TextBox control, those lines are not being trimmed, this causing TextBox's height to change.  Already tried to set `AcceptReturn` to false, and `TextWrapping` to `NoWrap`.

**To Reproduce**
Paste multi-lines text in a single-line TextBox control.

**Expected behavior**
I think if we set `AcceptReturn` to false, we should not allowing multiple lines in a TextBox control. And its seems in the current version, text-pasting is not being handled yet.
https://github.com/AvaloniaUI/Avalonia/blob/df0a9ae8e8e24bd612efe1864c51fef2fbb33163/src/Avalonia.Controls/TextBox.cs#L565-L574

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.10.0-rc1

**Comment by Gillibald** [comment]
We need to introduce `MaxLines` property for this scenario. Everything else works as expected.

**Comment by luthfiampas** [comment]
@Gillibald I was playing around with TextBox lately, and just found another issue with `MaxLength`. Lets say, we have 3 chars in TextBox, 3 chars in clipboard, and MaxLength is set to 5. The paste operation won't put any chars into the TextBox. I think it would be better if we just take 2 chars from the clipboard, put them into the TextBox, ignoring another characters.

So yes, we need to introduce `MaxLines` property, and change `MaxLength` behaviour a little bit when pasting text from the clipboard. What do you think? I'll be happy to submit PR for this :)

**Comment by nielsbosma** [comment]
I'm also interested in a fix for this.

**Comment by RationalFragile** [comment]
This should be reopened in 0.10.18 because the `MaxLines` in `TextBox.cs` is no longer there and pasting new lines in TextBox with `AcceptsReturn = false` still doesn't prevent multiple lines.

**Comment by Gillibald** [comment]
This is fixed in the Avalonia 11 preview

**Comment by zii-dmg** [comment]
Not fixed in Avalonia 11.0.0-rc1.1.
Qt 5 for example replaces newlines with spaces in QLineEdit.

https://github.com/AvaloniaUI/Avalonia/assets/2846896/fcdafa08-31e5-44b0-8cf0-071dcba53e42

**Comment by Gillibald** [comment]
You misunderstood what TextBox.MaxLines is doing. It only limits how many lines are displayed at once. It does not limit text input in any way. If you need to limit the number of explicit linebreaks you need to intercept text input.

**Comment by zii-dmg** [comment]
User can't enter multiline text by keyboard but can by paste. This is not uniform experience.

**Comment by Gillibald** [comment]
This matches WPF's behavior. MaxLines only affects render size but not text size in any way

**Comment by zii-dmg** [comment]
My question is not about MaxLines or other properties. But about default paste behavior for singleline TextBox. I checked WPF - it takes first line.

**Comment by zii-dmg** [comment]
WPF code for paste:
https://github.com/dotnet/wpf/blob/89540c2ac9d6f92146118b456d5c0e191904393e/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorCopyPaste.cs#L973-L976

**Comment by zii-dmg** [comment]
Fixed in #14173 (v11.0.9)
