### ISSUE TITLE
ExperimentalAcrylicBorder's Material seem to ignore FallbackColor

### ISSUE THREAD

**Issue by IvaYan** [AvaloniaUI/Avalonia#5440]
Hi! I'm trying to experiment with ExperimentalAcrylicBorder (no pun intended). I have noticed that it seems to ignore the `FallbackColor` property.

Consider the following code.

```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="acryl.MainWindow"
        TransparencyLevelHint="AcrylicBlur"
        Title="acryl">
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="300" />
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>
        <ExperimentalAcrylicBorder >
            <ExperimentalAcrylicBorder.Material>
              <ExperimentalAcrylicMaterial
                FallbackColor="White"
                TintColor="Black"
                TintOpacity="0.6"
                MaterialOpacity="0.6"
                BackgroundSource="Digger" />
            </ExperimentalAcrylicBorder.Material>
            <StackPanel />
        </ExperimentalAcrylicBorder>
    </Grid>
</Window>
```
This code produces the following window:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/2164810/107151120-feae7880-6971-11eb-84d6-16ae976da95b.png">

I put Mac's Terminal window below to indicate that we can see what's behind the window. Once I make the window inactive (i.e. by selecting another app) the Acrylic border goes gray.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/2164810/107151170-3cab9c80-6972-11eb-9cef-35b7ea89eb5a.png">

According to my experiments, the colour of the area is determined by the `TintColor`, `TintOpacity`, and `MaterialOpacity` properties. The `FallbackColor` seems to be ignored. Is there a way I can redefine the colour used when the window is inactive? According to this [MS docs](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic), "fallback color also replaces acrylic when your app isn’t in the active desktop window". Maybe Avalonia can adopt the same behaviour?

I'm using macOS 10.2 and Avalonia 0.10.0.

**Comment by pr8x** [comment]
I think you mean macOS 11.2 "Big Sur"?

**Comment by danwalmsley** [comment]
@IvaYan in Avalonia fallback colour here is only what you get when you try to use Acrylic on an unsupported system. 
It doesnt get used when inactive.

This is as designed and behavior wont change until we have integrated our composition engine which is in progress.

The conditions for fallback colour are as follows:

- Not OSX or Windows 10
- No GPU available

**Comment by IvaYan** [comment]
@danwalmsley Ok, I see. Is there an issue about the "composition engine" so I can monitor the progress and check the behaviour again?

@pr8x Exactly, that was just a typo.

**Comment by julian-baumann** [comment]
Any updates?
