### ISSUE TITLE
[Bug] ComboBox throws "The control already has a visual parent" error when it's pressed

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#5441]
**Describe the bug**
I tried to make a ThemeChanger (like https://github.com/AvaloniaUI/Avalonia/blob/b6ccad0cf85b17691c3945ed3f02020b06c72956/samples/ControlCatalog/MainView.xaml#L80-L85) but when I press throws an error.

**To Reproduce**
I don't know exactly the causes, so, I'm going to put the code:
[App.xaml.cs](https://github.com/PieroCastillo/Aura.UI/blob/9aa211381d58fbb4a5ce793d76a58f0606025fa5/samples/Aura.UI.Sample/App.axaml.cs#L28-L50)
[MainWindow.xaml](https://github.com/PieroCastillo/Aura.UI/blob/9aa211381d58fbb4a5ce793d76a58f0606025fa5/samples/Aura.UI.Sample/MainWindow.axaml#L267-L270)
[MainWindow.xaml.cs](https://github.com/PieroCastillo/Aura.UI/blob/9aa211381d58fbb4a5ce793d76a58f0606025fa5/samples/Aura.UI.Sample/MainWindow.axaml.cs#L18-L35)

**Expected behavior**
Error when the ComboBox is pressed.

**Screenshots**

Normal App

https://user-images.githubusercontent.com/39932324/107174140-7ba01900-6997-11eb-856a-43721ba8fb70.mp4

App without custom controls

https://user-images.githubusercontent.com/39932324/107174116-69be7600-6997-11eb-9995-13b496e1f6a4.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Version : Avalonia 0.10.0 stable

**Comment by FoggyFinder** [comment]
Duplicate of #4839

**Comment by maxkatz6** [comment]
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4839
But with some additional context

**Comment by maxkatz6** [comment]
@PieroCastillo long story short, the problem is with reusing same combobox items when its template was changed with new children list container.
As a workaround, if you replace your items with binding to Items property and use item template for items, it should be solved.

IIRC problem makes sense only with updating list control template while its open and items can't be reused.

**Comment by PieroCastillo** [comment]
@maxkatz6  THANKSSSSSSSSSSS :DDDDDDDDDDDD
With this code is enough:
```xml
 <ComboBox SelectedIndex="0"
                VirtualizationMode="None"
                SelectionChanged="ChangeTheme">
     <ComboBox.ItemTemplate>
         <DataTemplate>
            <TextBlock Text="{Binding .}"/>
         </DataTemplate> 
     </ComboBox.ItemTemplate>
    <l:ArrayList>
         <sys:String>Fluent Light</sys:String>
        <sys:String>Fluent Dark</sys:String>
   </l:ArrayList>
</ComboBox>
```

**Comment by PieroCastillo** [comment]
now all that remains is to improve the performance of the style system. ;)
