### ISSUE TITLE
Getting filepath from resource

### ISSUE THREAD

**Issue by Ingrown29** [AvaloniaUI/Avalonia#5443]
I need to get absolute filepath of specified file which is later used by another assembly to read that file. I know how to get file using `resm` or `avares` but I was not able to find solution for this and doesn't matter for me if I set build action to AvaloniaResource or Embedded resource or whatever. 

Using `Assembly.GetExecutingAssembly().GetManifestResourceNames()` I only get string `!Avalonia`. Does anyone has an idea how to solve this issue? Thanks in advance

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Platform/IAssetLoader.cs#L77 should provide you with the information you want.

**Comment by Ingrown29** [comment]
Thank you but i have no clue what `baseUri` means.. In other words, I don't understand what's different between `uri` and `baseUri` in the arguments.. Can you explain it to me or maybe provide some example how to use this method? I just want the absolute path of one file providing somethig like `resm:MyAssembly.Assets.Sounds.my_sound.mp3`, that's it.. I don't even need to get all assets in the path

**Comment by jp2masa** [comment]
I think you can pass `null` for the `baseUri`. If that doesn't work, try passing the same uri to both `uri` and `baseUri`.

**Comment by Ingrown29** [comment]
Thanks @jp2masa for your tip but no success again.. I tried it with or without the baseUri as you suggested but no luck.. maybe you will find something wrong in my code.. I'm using this approach:

```
var assets = AvaloniaLocator.Current.GetService<IAssetLoader>();
var paths = assets.GetAssets(new Uri("resm:MyAssembly.Assets.Sounds.my_sound.mp3"), null);
```

I even tried to change the uri to `avares://MyAssembly/Assets/Sounds/my_sound.mp3`.. Of course I also changed the build action on the file to `AvaloniaResource` or `Embedded resource` but no luck.. any ther ideas?

**Comment by jp2masa** [comment]
`GetAssets` is for retrieving a list of assets in a "folder", e.g. `GetAssets("avares://MyAssembly/Assets/Sounds", null)` would return a list with a single URI: `avares://MyAssembly/Assets/Sounds/my_sound.mp3`.

**Comment by Ingrown29** [comment]
Yeah sorry my bad, this works.. but I think we bit misunderstood each other .. this only returns literally the `avares://MyAssembly/Assets/Sounds/my_sound.mp3` and I need absolute filepath on the actual system e.g. `C:\Users\User\Documents\Visual Studio 2019\Sources\MySolution\MyProject\Assets\Sounds\my_sound.mp3`

**Comment by Gillibald** [comment]
There is nothing in the file system. These resources are embedded into the assembly.

**Comment by Ingrown29** [comment]
Oh okay so can you suggest me another approach which will help me get the filepath in file system?

**Comment by jp2masa** [comment]
If you need a file you can create it, open the asset stream, and make a copy.

**Comment by Ingrown29** [comment]
I just solved this by using `System.AppDomain.CurrentDomain.BaseDirectory` + `Assets\Sounds\my_sound.mp3`  and changed `my_sound.mp3` build action to `none` and  copy to output directory to `Copy if newer`.. It works flaweless on Windows and Linux (Raspberry Pi).. so simple and it has nothing to do with avalonia.. but the solution as @jp2masa suggested should work too
