### ISSUE TITLE
Regarding AvalonStudio

### ISSUE THREAD

**Issue by wjk** [AvaloniaUI/Avalonia#5448]
The [AvalonStudio](https://github.com/VitalElement/AvalonStudio) repository appears to be dead. While it is still a valuable project, its license renders the maintenance of forks untenable, since your license requires that every fork’s changes be pushed to upstream. However, when upstream is unmaintained, this makes contribution all but impossible (without violating the license).

@danwalmsley I understand you are the original author of AvalonStudio. I cordially request that you relicense this repository under GPLv3. I believe GPLv3 will address the same issues that AvalonStudio’s own license stipulates (that changes must be shared with everyone; and you want no one to be able to take the program, modify it trivially, and sell it). Unlike your license, GPLv3 places no restriction on where or how the program is distributed, only that the full and unmodified source code is provided to anyone who is given a binary produced from that code. While the GPLv3 does not _strictly_ prohibit selling binaries, doing so is largely pointless. As soon as the first sale is made, your customer can build the project from its source code and distribute the result to anyone free of charge, and under GPLv3 you have no way to stop them. Any changes or additions to AvalonStudio that a third party would make to attempt to differentiate their product must also be shared with everyone under the same terms.

While IANAL, I believe that you need to (or at the very least should) contact the 16 other people who committed to AvalonStudio and ask their permission before changing the license. Pinging their GitHub usernames en masse to this issue would be an efficient way to do that, but it is not my place to do so as I am not the maintainer of AvalonStudio.

Avalonia maintainers: Please accept my apologies for filing this issue that is unrelated to Avalonia proper. Issues at the AvalonStudio repository are not monitored, and I understand @danwalmsley often contributes here, so I thought this is the best way to get his attention. (He lists no email address or other public contact information on his profile; I checked there.)

**Comment by danwalmsley** [comment]
changed to lgpl.
