### ISSUE TITLE
DataGridTemplateColumn doesn't respect FuncDataTemplate SupportsRecycling parameter

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#5453]
**Describe the bug**
DataGrid tries to recycle data templates even if this operation was marked as unsupported.

**To Reproduce**
Create DataGridTemplateColumn template from code behind with hardcode dependency on date context value instead of bindings.

**Expected behavior**
DataTemplate is not recycled, if it was marked as SupportsRecycling = false.

**Desktop (please complete the following information):**

- OS: All
- Version 0.10.0 (must be 0.9 and earlier too).

**Comment by kekekeks** [comment]
That effectively prevents DataGrid from being used with non-type based template selectors
