### ISSUE TITLE
ShowInTaskbar property not working.

### ISSUE THREAD

**Issue by MrVeil303** [AvaloniaUI/Avalonia#5454]
ShowInTaskbar property not working. Taskbar icon not hiding.

1. Set ShowInTaskbar property to false
2. Run

![изображение](https://user-images.githubusercontent.com/50862104/107419776-d87b0b00-6b20-11eb-83b0-e62d55f77cd2.png)
![изображение](https://user-images.githubusercontent.com/50862104/107419840-e9c41780-6b20-11eb-8550-e4ba32e5db6e.png)
![изображение](https://user-images.githubusercontent.com/50862104/107419845-ec267180-6b20-11eb-90e0-0eaa24a1d980.png)

- OS: Windows 10 1809
- Version 0.10.0

P.S. Sorry for my english.

**Comment by MonkAlex** [comment]
Try run without VisualStudio.

**Comment by maxkatz6** [comment]
Probably [UseAppHost](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#useapphost) also can affect this behavior

**Comment by MrVeil303** [comment]
@MonkAlex running without visual studio didn't help

**Comment by MrVeil303** [comment]
Maybe this bug is due to this ?
![изображение](https://user-images.githubusercontent.com/50862104/108377961-3ab4c980-720d-11eb-8f01-9929a449c81b.png)
https://github.com/AvaloniaUI/Avalonia/blob/13e69c40adf33ff942c79d95d887096ee7b0c082/src/Windows/Avalonia.Win32/WindowImpl.cs#L1091
