### ISSUE TITLE
AngleWin32EglDisplay.WrapDirect3D11Texture is crashing

### ISSUE THREAD

**Issue by Tape-Worm** [AvaloniaUI/Avalonia#5455]
In my efforts for providing an interop layer between my graphics API and Avalonia I had need to use the `AngleWin32EglDisplay.WrapDirect3D11Texture` method.  

Unfortunately, it appears to be failing.  When I call it, I get this:
![image](https://user-images.githubusercontent.com/9710137/107433107-245c8e80-6ae6-11eb-80fa-42cf43b739ad.png)

This is how I'm calling it:
```csharp
IntPtr _d3dRtSharedHandle;
EglSurface _glSurface;

var platform = AvaloniaLocator.Current.GetService<IPlatformOpenGlInterface>();

_platform = (EglPlatformOpenGlInterface)platform;

_d3dRtSharedHandle = _target.Texture.GetSharedHandle(); // The shared handle IS working, I've confirmed this.

_glSurface = _angleDisplay.WrapDirect3D11Texture(_platform, _d3dRtSharedHandle);
```

I was able to work around it by calling `AngleWin32EglDisplay.EglInterface.CreatePbufferFromClientBuffer` (which the Wrap method seems to do as well, just has different parameters than what I've got here):
```csharp
_angleDisplay.EglInterface.CreatePbufferFromClientBuffer(_angleDisplay.Handle, EglConsts.EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE, _d3dRtSharedHandle, _angleDisplay.Config, new[]
            {
                    EglConsts.EGL_WIDTH, _target.Width,
                    EglConsts.EGL_HEIGHT, _target.Height,
                    EglConsts.EGL_TEXTURE_TARGET, EglConsts.EGL_TEXTURE_2D,
                    EglConsts.EGL_TEXTURE_FORMAT, EglConsts.EGL_TEXTURE_RGBA,
                    EglConsts.EGL_NONE
            })
```

**Comment by kekekeks** [comment]
`WrapDirect3D11Texture` wraps a *texture* not a DXGI handle. It expects `ID3D11Texture2D` pointer.

See ANGLE EGL extensions docs here for more details: https://github.com/google/angle/tree/master/extensions

**Comment by Tape-Worm** [comment]
Ah, well, that explains that.  My bad.  

Might as well mark this as invalid and close it then.
