### ISSUE TITLE
Should allow binding to CLR properties on AvaloniaObject

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#546]

**Comment by jkoritzinsky** [comment]
We can do this by doing the recursive nesting of the property handlers similar to how validation is done.

**Comment by danwalmsley** [comment]
Does this mean normal bog standard properties without implementing INCP?

**Comment by jkoritzinsky** [comment]
Currently we can't bind to any non `AvaloniaProperty`s on an `AvaloniaObject`. That is what this is fixing. You will still need to implement INPC to be able to get bindings from your data model to the UI to propagate.
