### ISSUE TITLE
When start avalonia app, Can it debug as wpf?

### ISSUE THREAD

**Issue by chancezheng** [AvaloniaUI/Avalonia#5460]
When I start the avalonia app, then alter the content in axaml, the app was not autoupdate, Can it work as wpf, so we can debug easily

**Comment by FoggyFinder** [comment]
You've already created Q:

https://github.com/AvaloniaUI/Avalonia/discussions/5459

do not create issue just because you didn't receive some response in 15 minutes.

**Comment by chancezheng** [comment]
sorry
