### ISSUE TITLE
ContextMenu: Opening a sub-menu will prevent mouse interaction with the parent menu level.

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#5475]
**Describe the bug**

As in the title and in the attached video - if sub-menu shows up and you hover over an element in it then interaction with the parent level of items becomes impossible.

There is also another problem - moving mouse from one parent element to another becomes very laggy if sub-menu begins to open.

**Screenshots**

https://user-images.githubusercontent.com/2588062/107791642-799dd780-6d54-11eb-978e-fafe23bb34f3.mp4

**Desktop (please complete the following information):**

- OS: Windows
- Version: Current master

**Comment by eugenenekh** [comment]
this works fine in released  0.10.0

**Comment by MarchingCube** [comment]
This problem has been introduced a few days after the release it seems. Since there were a few changes in how menu interaction works.

**Comment by grokys** [comment]
Seems to have been caused by #5295
