### ISSUE TITLE
Icon for application

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#548]
Add new property `Icon` to `Window` tag:

`<Window Icon="youricon.ico"></Window>`

**Comment by danwalmsley** [comment]
@jkoritzinsky can we close this one now?

**Comment by KvanTTT** [comment]
I think no. Another pull request has not been merged yet: https://github.com/AvaloniaUI/Avalonia/pull/575

**Comment by grokys** [comment]
#575 has been merged to master.
