### ISSUE TITLE
Adding support at x:ClassModifier

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#5500]
Adding support at x:ClassModifier like wpf, upw

##Current behavior
x:ClassModifier is ignored 

##Aspeted behavior
x:ClassModifier is not ignored

**Comment by kekekeks** [comment]
Adding special support for  `ClassModifier` doesn't really make sense since the partial class is generated by [a Roslyn generator](https://github.com/AvaloniaUI/Avalonia.NameGenerator) that can pick up the modifiers from existing C# class.
