### ISSUE TITLE
MiniMvvm as nuget package.

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#5501]
the same as the title.

**Comment by FoggyFinder** [comment]
for what reason?

**Comment by maxkatz6** [comment]
Avalonia applications can work with any existing MVVM framework that supports netstandard or netcore without dependencies on wpf/uwp/xf. 
As for me MiniMvvm makes sense only internally to not rely on third party libraries in control catalog and other sample projects.

**Comment by MarchingCube** [comment]
Publishing a nuget package would mean that we commit to maintaining this package. Which I think is out of scope for this project.

**Comment by grokys** [comment]
Exactly what @MarchingCube said. If you would like to use the code though, feel free to create your own library based on it!

**Comment by workgroupengineering** [comment]
Hi,
I read that in the future you are considering removing the dependencies from ReactiveUI. If this happens the default MVVM template of Avalonia should depend on another library. MiniMVVM is sufficient in 70% of projects, why depend on an external one when you already have one at home?
When using external libraries it may happen that a feature cannot be implemented if the owner of the library on which the feature depends does not correct a behavior or bug. It has already happened to you with the signing of the assembly.

**Comment by kekekeks** [comment]
@workgroupengineering MiniMVVM was created as a crude ReactiveUI replacement for sample projects, not a full-fledged MVVM framework. Right now it's 3 classes with a stick.

A separate MVVM library needs it's own view locator, probably a routed view host.
But it definitely should not:
- not mirror only a small subset of RxUI APIs
- be tied to Avalonia _UI toolkit_

So it would probably fine to create one (by copy-pasting those 3 classed from MiniMvvm) and even host it as a part of Avalonia or AvaloniaCommunity org.

**Comment by grokys** [comment]
@workgroupengineering we're not planning on removing support for ReactiveUI, we just had to remove it from our samples.
