### ISSUE TITLE
Add tests for hit testing

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#551]
When reviewing the latest PRs from @jkoritzinsky and @donandren I noticed that we don't seem to have unit tests covering this code - we should!

**Comment by jkoritzinsky** [comment]
We have tests for hit testing right here: https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Input.UnitTests/InputElement_HitTesting.cs

**Comment by grokys** [comment]
Oh yeah - ignore this, NCrunch was reporting faulty test coverage it seems and i was too busy to go looking for the tests.

Glad to know that you guys are starting to get to know the code better than me! :)
