### ISSUE TITLE
CanResize="False" and ExtendClientAreaToDecorationsHint="True" do not work together

### ISSUE THREAD

**Issue by Grinch** [AvaloniaUI/Avalonia#5526]
**Describe the bug**
When setting `CanResize="False"` with `ExtendClientAreaToDecorationsHint="True"` you lose the ability to move the window.

**To Reproduce**
Using the following AXAML will reproduce the issue: https://gist.github.com/Grinch/7bfb1d3d7d30bcd1d2164e49be3d1824

**Expected behavior**
Ability to drag the window by the title bar.

**Desktop (please complete the following information):**

- OS: Windows 10 (Build 21318)
- Version: 0.10.0

**Comment by Takoooooo** [comment]
Reproducible only on Windows.
