### ISSUE TITLE
Restarting an application lifetime doesn't work on macOS

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#5527]
**Describe the bug**

Starting with an application lifetime, then shutting it down and starting again doesn't work on macOS.

**To Reproduce**

1. Use this repro on `Sandbox`: https://github.com/jp2masa/Avalonia/commit/3685ac5671e1eda104d3e6a9c24ee20bca400446.
2. Run the `Sandbox` project and press R on the window that opens, it will fail on macOS, should work fine on Windows and Linux.

**Expected behavior**

The window should close, then the app should restart and a new window should open.

**Desktop (please complete the following information):**

- OS: macOS 10.13.6
- Version: 0.10.0

**Comment by kekekeks** [comment]
I don't think OSX properly supports calling `[NSApp run]` multiple times

**Comment by derekantrican** [comment]
@kekekeks Looks like the last update on this was 2.5 years ago. Is this being closed as "won't fix"? Or is there some other update?

**Comment by Gillibald** [comment]
I don't think there are plans to officially support this. It is always safer to restart the entire process.

**Comment by kekekeks** [comment]
It's now possible to run the main loop the second time, no exceptions from avalonia side. If it breaks, it breaks.

**Comment by TheMR-777** [comment]
> It's now possible to run the main loop the second time, no exceptions from avalonia side. If it breaks, it breaks.

So you mean, that we can call the Main() the 2nd time? or the loop presented by @jp2masa now works as expected?
[Anyways, the Avalonia is SUPER great project, my respects ❤️]
