### ISSUE TITLE
Unable to initialize OpenGL

### ISSUE THREAD

**Issue by MikiraSora** [AvaloniaUI/Avalonia#5543]
**Describe the bug**
when program want to use OGL , vs output show error : 
```
[OpenGL] Unable to initialize OpenGL: current platform does not support multithreaded context sharing (String #818892507)
```

**To Reproduce**
1. just clone [XamlControlsGallery](https://github.com/AvaloniaUI/XamlControlsGallery/tree/master/XamlControlsGallery)
2. build netcore project directly within AnyCPU
3. click Media in menu
4. See error in vs ouptut

**Screenshots**
![](https://puu.sh/Hjlqc/2ca24ea6ca.png)

**Desktop (please complete the following information):**
- OS: 
![image](https://user-images.githubusercontent.com/7549173/108821559-bf7e5980-75f8-11eb-996a-48ca8400c909.png)
![image](https://user-images.githubusercontent.com/7549173/108821978-619e4180-75f9-11eb-9cd1-78a52384e256.png)

- Version:
![image](https://user-images.githubusercontent.com/7549173/108821751-0c623000-75f9-11eb-8fa9-1c436795d818.png)

**Comment by kekekeks** [comment]
OpenGL control isn't currently supported with ANGLE, you need to switch to WGL by adding
```
.With(new Win32PlatformOptions { UseWgl = true })
```
to your app builder.

**Comment by MikiraSora** [comment]
> OpenGL control isn't currently supported with ANGLE, you need to switch to WGL by adding
> 
> ```
> .With(new Win32PlatformOptions { UseWgl = true })
> ```
> 
> to your app builder.

I modified as you said
![image](https://user-images.githubusercontent.com/7549173/108825479-09b60980-75fe-11eb-83a3-6f031bdcb370.png)
but program will lag and no response , after seconds it's closed.
vs output
```
程序“[18584] XamlControlsGallery.NetCore.exe”已退出，返回值为 -1073741819 (0xc0000005) 'Access violation'。
```

**Comment by sn4k3** [comment]
> 程序“[18584] XamlControlsGallery.NetCore.exe”已退出，返回值为 -1073741819 (0xc0000005) 'Access violation'。

Same happen to me if i try to use Wgl.

**Comment by Thog** [comment]
Same thing here... However, I cloned the Avalonia and built ``ControlCatalog.NetCore`` with UseWgl and the OpenGL tab work just fine on it so not quite sure what is going on here.

Tested with NVIDIA driver 460.79 on Windows 20H2 (19042) with an RTX 2070 Max-Q.

**Comment by Thog** [comment]
So I investigated it a bit more and reduced this to a small reproducible example at https://github.com/Thog/Avalonia/tree/reproduce-5543

This happens when using ``ProgressBar`` with ``IsIndeterminate`` set to ``True`` while running against NVIDIA OpenGL driver with ``UseWGL = true``.
The crash happen inside NVIDIA OpenGL implementation (``nvoglv64.dll``), inside what seems to be a worker thread (could be related to the "Threaded optimization" feature?)

This kind of crash likely suggest an invalid usage of some OpenGL API to me

**Comment by sn4k3** [comment]
Well i can say that i use the IsIndeterminate on my whole app loadings, but when not using the progress bar my app also crash if i open a combo box

**Comment by MikiraSora** [comment]
I notice when RenderDoc lunach program , It's work fine.
I think OGL doesn't initalize or something failed :( .
Here's pof video: https://puu.sh/HlJ2G/0beeee6a63.mkv

**Comment by emmauss** [comment]
The issue only occurs with the fluent theme for me on nvidia. It doesn't crash when I switch to the default theme.

**Comment by hez2010** [comment]
Same issue here with Intel Iris Plus Graphics 640.

**Comment by ahmedtalaat327** [comment]
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/tmds.dbus/index.json' has timed out after 100000ms.

**Comment by kirant400** [comment]
UseWgl = true it is giving Exception in render loop: 'Avalonia.OpenGL.OpenGlException: Unable to make the context current. Graphics card Nvidia GeForce 1650
