### ISSUE TITLE
ListBox SelectedIndices

### ISSUE THREAD

**Issue by RomanSoloweow** [AvaloniaUI/Avalonia#5544]
Like in WinForms:
https://docs.microsoft.com/ru-ru/dotnet/api/system.windows.forms.listbox.selectedindices?view=netframework-4.8

**Comment by maxkatz6** [comment]
It should be available inside of Selection, which is protected and can be accessed from custom listbox control
https://github.com/AvaloniaUI/Avalonia/blob/fbb35f530768cc08f9b408be440823e0d043ded8/src/Avalonia.Controls/Primitives/SelectingItemsControl.cs#L246

**Comment by grokys** [comment]
`Selection` is exposed in `ListBox` so should be available. As @maxkatz6 says - use `listBox.Selection.SelectedIndexes`.
