### ISSUE TITLE
How to continuously update the UI through multiple return values of a process in realtime? 

### ISSUE THREAD

**Issue by RickyYChan** [AvaloniaUI/Avalonia#5550]
## Situation
I have a python script to make a machine learning classification.
In the .py script, I opened a camera and classify every frame so the .py process is **unstoppable**.
So I must get the return value **in real time**.
I wanna use Avalonia to show the **result** and **do other things**.

## What I've Done
1. I can use C# Console to call .py script;
2. I can use avalonia binding the result of the process, and show **last** output of the process on the view;

## What's the Problem
I cannot open .py script when the app start up and update the UI every time the process provides a return value.
I can get return value continuously on Console App, but dont know how to do in Avalonia.

## Others?
Maybe is to use Dispatcher.UIThread.InvokeAsync or something to solve it but i failed.
Also, I opened the .py script which is the classify process in the constructor, i think it must be wrong.
But run py script in the OnOpened Event of MainWindow will do nothing on the UI.

## Codes
I'll show all the code of the proj:

`MainWindow:`
```Xaml
<TextBlock Text="{Binding MyClassifier.Result}" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Margin="5,5,5,5"/>
```
`MainWindow.Xaml.cs`
```C#
namespace WasteClassifierUI
{
    public class MainWindow : Window
    {
        public Classifier MyClassifier { get; set; }

        public MainWindow()
        {
            InitializeComponent();

            MyClassifier = new Classifier();

            // wont work
            //Dispatcher.UIThread.Post(
            //    () => MyClassifier.RunPythonScript("hello.py"),
            //    DispatcherPriority.Send
            //    );

            
            MyClassifier.RunPythonScript("hello.py");

#if DEBUG
            this.AttachDevTools();
#endif
        }

        private void InitializeComponent() => AvaloniaXamlLoader.Load(this);
        private void OnOpened(object sender, EventArgs e)
        {
            //new PlayVideoView().Show();
        }
    }
}
```
`Class: Classifier.cs`
```C#
public class Classifier
    {
        private string res = string.Empty;

        public string Result
        {
            get { return res; }
            set
            {
                if (
                    value != string.Empty &&
                    value != Environment.NewLine &&
                    value != res &&
                    value != null
                    )
                {
                    res = value;
                }
            }
        }
        public void RunPythonScript(string sArgName, string args = "", params string[] teps)
        {
            Process p = new Process();
            p.StartInfo.FileName = @"python";

            string sArguments = sArgName;
            foreach (string sigstr in teps)
            {
                sArguments += " " + sigstr;
            }
            sArguments += " " + args;
            p.StartInfo.Arguments = sArguments;
            p.StartInfo.UseShellExecute = false;
            p.StartInfo.RedirectStandardOutput = true;
            p.StartInfo.RedirectStandardInput = true;
            p.StartInfo.RedirectStandardError = true;
            p.StartInfo.CreateNoWindow = true;
            p.OutputDataReceived += (sender, e) => Result = e.Data!;
            p.Start();
            p.BeginOutputReadLine();
            p.WaitForExit();
        }
    }
```

## OS
Windows 10
Net5.0

Thanks for your answering! :) 👍 
Have a nice day whatever!

**Comment by maxkatz6** [comment]
First of all, make sure that you set DataContext correctly and you can get your Classifier data from it.

Secondary, if you want UI to handle updates in binding, your class (Classifier for example) needs to implement INotifyPropertyChanged, and invoke PropertyChanged event when some property was changed. Example from WPF, but it will work in same way - [docs](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/how-to-implement-the-inotifypropertychanged-interface?view=netframeworkdesktop-4.8).

And finally, View and TextBlock expect PropertyChanged event to be called on the UI thread, so you need to synhronize it in some way. In your case OutputDataReceived invokes handlers on another thread, different from UI or caller thread, so Dispatcher.UIThread.Post won't work in place where you tried. But this will work, if you wrap your NotifyPropertyChanged (from WPF example) into Dispatcher call:
```csharp
        public string Result
        {
            get { return res; }
            set
            {
                if (
                    value != string.Empty &&
                    value != Environment.NewLine &&
                    value != res &&
                    value != null
                    )
                {
                    res = value;
                    Dispatcher.UIThread.InvokeAsync(() => NotifyPropertyChanged(nameof(Result))); // or post
                }
            }
        }
```

**Comment by maxkatz6** [comment]
Note, in this example (as well as in your code) you have tightly coupled code that might be hard to maintain and expand in the future.
I would suggest to learn some MVVM pattern basics and use MVVM frameworks like ReactiveUI or Prism.Avalonia (there are more of them, but these are most popular I believe). These frameworks will also simplify your work with INotifyPropertyChanged.

**Comment by RickyYChan** [comment]
> Note, in this example (as well as in your code) you have tightly coupled code that might be hard to maintain and expand in the future.
> I would suggest to learn some MVVM pattern basics and use MVVM frameworks like ReactiveUI or Prism.Avalonia (there are more of them, but these are most popular I believe). These frameworks will also simplify your work with INotifyPropertyChanged.

Thank you for your answering!
I've been tried the mvvm template before, but this project is too small to use mvvm i thought, so i'm tring put evering together to make everything faster(almost everything has been done excepted the simple UI, and the deadline is almost here).
If the solution needed to be expanded in the future, i'll tring to rebuild this controlling solution to a mvvm project if i can. :)

And for the first answer:
I've been set the datacontext before the issue was pulled like this:
`App.Xaml.cs`
```C#
public override void OnFrameworkInitializationCompleted()
        {
            if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
            {
                desktop.MainWindow = new MainWindow()
                {
                    DataContext = new MainWindow(),
                };
            }

            base.OnFrameworkInitializationCompleted();
        }
```
And it works.
So I'll trying to follow your answer! 
And very appreciate! 👍 :)

**Comment by RickyYChan** [comment]
> First of all, make sure that you set DataContext correctly and you can get your Classifier data from it.
> 
> Secondary, if you want UI to handle updates in binding, your class (Classifier for example) needs to implement INotifyPropertyChanged, and invoke PropertyChanged event when some property was changed. Example from WPF, but it will work in same way - [docs](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/how-to-implement-the-inotifypropertychanged-interface?view=netframeworkdesktop-4.8).
> 
> And finally, View and TextBlock expect PropertyChanged event to be called on the UI thread, so you need to synhronize it in some way. In your case OutputDataReceived invokes handlers on another thread, different from UI or caller thread, so Dispatcher.UIThread.Post won't work in place where you tried. But this will work, if you wrap your NotifyPropertyChanged (from WPF example) into Dispatcher call:
> 
> ```cs
>         public string Result
>         {
>             get { return res; }
>             set
>             {
>                 if (
>                     value != string.Empty &&
>                     value != Environment.NewLine &&
>                     value != res &&
>                     value != null
>                     )
>                 {
>                     res = value;
>                     Dispatcher.UIThread.InvokeAsync(() => NotifyPropertyChanged(nameof(Result))); // or post
>                 }
>             }
>         }
> ```

Amazing, that works! But there' still a problem.
If the process i opened(such as the "hello.py", which is the test process)will print(output)multiple message like this:
```
> This image most likely belongs to other waste with a 80.201274 percent confidence. Program finished in 45.88 ms.
> This image most likely belongs to recyclable waste with a 99.996090 percent confidence. Program finished in 47.90 ms.
> This image most likely belongs to hazardous waste with a 99.974388 percent confidence. Program finished in 46.88 ms.
> This image most likely belongs to kitchen waste with a 99.999893 percent confidence. Program finished in 46.85 ms.
> This image most likely belongs to recyclable waste with a 57.704127 percent confidence. Program finished in 42.89 ms.
> This image most likely belongs to other waste with a 99.999928 percent confidence. Program finished in 45.88 ms.
> This image most likely belongs to recyclable waste with a 99.929786 percent confidence. Program finished in 42.89 ms.
> This image most likely belongs to kitchen waste with a 63.873065 percent confidence. Program finished in 40.86 ms.
```

What i expected was the UI could show different lines of message when the process print the message.
The truth is, the window will opened aftering the process(the .py script) exit and show the last message, which is:

`> This image most likely belongs to kitchen waste with a 63.873065 percent confidence. Program finished in 40.86 ms.`

And i wanna to know how to call this process asynchronously when the program starts running, and get the return value continuously.  The .py process is a loop program and will check every frame of the camera. So if i work this way, if the final .py process was settled down, the ui window will never start because the .py is unexitable.
It seems that asynchronous operations cannot be used in the constructor, and in the start event of the window, my function does not work. :
`Will show the last message of the process`
```C#
public MainWindow()
        {
            InitializeComponent();

            MyClassifier = new Classifier();
            MyClassifier.RunPythonScript("hello.py");



#if DEBUG
            this.AttachDevTools();
#endif

        }
```
`Will show nothing`
```C#
private void OnOpened(object sender, EventArgs e)
        {
            //new PlayVideoView().Show();
            MyClassifier.RunPythonScript("hello.py");
        }
```

**Comment by RickyYChan** [comment]
> > First of all, make sure that you set DataContext correctly and you can get your Classifier data from it.
> > Secondary, if you want UI to handle updates in binding, your class (Classifier for example) needs to implement INotifyPropertyChanged, and invoke PropertyChanged event when some property was changed. Example from WPF, but it will work in same way - [docs](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/how-to-implement-the-inotifypropertychanged-interface?view=netframeworkdesktop-4.8).
> > And finally, View and TextBlock expect PropertyChanged event to be called on the UI thread, so you need to synhronize it in some way. In your case OutputDataReceived invokes handlers on another thread, different from UI or caller thread, so Dispatcher.UIThread.Post won't work in place where you tried. But this will work, if you wrap your NotifyPropertyChanged (from WPF example) into Dispatcher call:
> > ```cs
> >         public string Result
> >         {
> >             get { return res; }
> >             set
> >             {
> >                 if (
> >                     value != string.Empty &&
> >                     value != Environment.NewLine &&
> >                     value != res &&
> >                     value != null
> >                     )
> >                 {
> >                     res = value;
> >                     Dispatcher.UIThread.InvokeAsync(() => NotifyPropertyChanged(nameof(Result))); // or post
> >                 }
> >             }
> >         }
> > ```
> 
> Amazing, that works! But there' still a problem.
> If the process i opened(such as the "hello.py", which is the test process)will print(output)multiple message like this:
> 
> ```
> > This image most likely belongs to other waste with a 80.201274 percent confidence. Program finished in 45.88 ms.
> > This image most likely belongs to recyclable waste with a 99.996090 percent confidence. Program finished in 47.90 ms.
> > This image most likely belongs to hazardous waste with a 99.974388 percent confidence. Program finished in 46.88 ms.
> > This image most likely belongs to kitchen waste with a 99.999893 percent confidence. Program finished in 46.85 ms.
> > This image most likely belongs to recyclable waste with a 57.704127 percent confidence. Program finished in 42.89 ms.
> > This image most likely belongs to other waste with a 99.999928 percent confidence. Program finished in 45.88 ms.
> > This image most likely belongs to recyclable waste with a 99.929786 percent confidence. Program finished in 42.89 ms.
> > This image most likely belongs to kitchen waste with a 63.873065 percent confidence. Program finished in 40.86 ms.
> ```
> 
> What i expected was the UI could show different lines of message when the process print the message.
> The truth is, the window will opened aftering the process(the .py script) exit and show the last message, which is:
> 
> `> This image most likely belongs to kitchen waste with a 63.873065 percent confidence. Program finished in 40.86 ms.`
> 
> And i wanna to know how to call this process asynchronously when the program starts running, and get the return value continuously. The .py process is a loop program and will check every frame of the camera. So if i work this way, if the final .py process was settled down, the ui window will never start because the .py is unexitable.
> It seems that asynchronous operations cannot be used in the constructor, and in the start event of the window, my function does not work. :
> `Will show the last message of the process`
> 
> ```cs
> public MainWindow()
>         {
>             InitializeComponent();
> 
>             MyClassifier = new Classifier();
>             MyClassifier.RunPythonScript("hello.py");
> 
> 
> 
> #if DEBUG
>             this.AttachDevTools();
> #endif
> 
>         }
> ```
> 
> `Will show nothing`
> 
> ```cs
> private void OnOpened(object sender, EventArgs e)
>         {
>             //new PlayVideoView().Show();
>             MyClassifier.RunPythonScript("hello.py");
>         }
> ```

I've changed the Classifier class in my script by the way.
```C#
public class Classifier : INotifyPropertyChanged
    {
        private string res = string.Empty;

        public string Result
        {
            get { return res; }
            set
            {
                if (
                    value != string.Empty &&
                    value != Environment.NewLine &&
                    value != res &&
                    value != null
                    )
                {
                    res = value;
                    Dispatcher.UIThread.Post(
                        () => NotifyPropertyChanged(nameof(Result)),
                        DispatcherPriority.Send
                        );
                }
            }
        }

        public event PropertyChangedEventHandler? PropertyChanged;
        private void NotifyPropertyChanged([CallerMemberName] string propertyName = "")
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public void RunPythonScript(string sArgName, string args = "", params string[] teps)
        {
            Process p = new Process();
            p.StartInfo.FileName = @"python";

            string sArguments = sArgName;
            foreach (string sigstr in teps)
            {
                sArguments += " " + sigstr;
            }
            sArguments += " " + args;
            p.StartInfo.Arguments = sArguments;
            p.StartInfo.UseShellExecute = false;
            p.StartInfo.RedirectStandardOutput = true;
            p.StartInfo.RedirectStandardInput = true;
            p.StartInfo.RedirectStandardError = true;
            p.StartInfo.CreateNoWindow = true;
            p.OutputDataReceived += (sender, e) => Result = e.Data!;
            p.Start();
            p.BeginOutputReadLine();
            p.WaitForExit();
        }
    }
```

**Comment by RickyYChan** [comment]
> Note, in this example (as well as in your code) you have tightly coupled code that might be hard to maintain and expand in the future.
> I would suggest to learn some MVVM pattern basics and use MVVM frameworks like ReactiveUI or Prism.Avalonia (there are more of them, but these are most popular I believe). These frameworks will also simplify your work with INotifyPropertyChanged.

I've check the code carefully, and almost everything has been done.
Thank you every much! Appreciate! 👍 You're pretty nice!

**Comment by RickyYChan** [comment]
> First of all, make sure that you set DataContext correctly and you can get your Classifier data from it.
> 
> Secondary, if you want UI to handle updates in binding, your class (Classifier for example) needs to implement INotifyPropertyChanged, and invoke PropertyChanged event when some property was changed. Example from WPF, but it will work in same way - [docs](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/how-to-implement-the-inotifypropertychanged-interface?view=netframeworkdesktop-4.8).
> 
> And finally, View and TextBlock expect PropertyChanged event to be called on the UI thread, so you need to synhronize it in some way. In your case OutputDataReceived invokes handlers on another thread, different from UI or caller thread, so Dispatcher.UIThread.Post won't work in place where you tried. But this will work, if you wrap your NotifyPropertyChanged (from WPF example) into Dispatcher call:
> 
> ```cs
>         public string Result
>         {
>             get { return res; }
>             set
>             {
>                 if (
>                     value != string.Empty &&
>                     value != Environment.NewLine &&
>                     value != res &&
>                     value != null
>                     )
>                 {
>                     res = value;
>                     Dispatcher.UIThread.InvokeAsync(() => NotifyPropertyChanged(nameof(Result))); // or post
>                 }
>             }
>         }
> ```

If I work on my way:
```C#
public MainWindow()
        {
            InitializeComponent();

            MyClassifier = new Classifier();

            Dispatcher.UIThread.Post(() => MyClassifier.RunPythonScript("hello.py"), DispatcherPriority.Send);



#if DEBUG
            this.AttachDevTools();
#endif

        }
```
When the window has been showed, the process will be lauched indeed, but the main window will block untill the process shut down:
```Python
def doit(img_path : str):
    img = keras.preprocessing.image.load_img(
    img_path, target_size=(160, 160)
    )
    img_array = keras.preprocessing.image.img_to_array(img)

    img_array = tf.expand_dims(img_array, 0)
    interpreter = tf.lite.Interpreter(
        model_path="trash_model_lite.tflite"
    )
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    interpreter.set_tensor(input_details[0]['index'], img_array)
    c = time.time()
    interpreter.invoke()
    d = time.time()
    output_data = np.squeeze(interpreter.get_tensor(output_details[0]['index']))
    probs = tf.nn.softmax(output_data)
    class_names = ["hazardous waste", "kitchen waste", "other waste", "recyclable waste"]
    print(
        "> This image most likely belongs to {} with a {:2f} percent confidence. Program finished in {:.2f} ms."
        .format(class_names[np.argmax(probs)], 100 * np.max(probs), (d-c) * 1000)
    , flush=True)
doit("sp.jpg")
time.sleep(2)
doit("1.jpg")
time.sleep(2)
doit("2.jpg")
time.sleep(2)
doit("3.jpg")
time.sleep(2)
doit("4.jpg")
time.sleep(2)
doit("5.jpg")
time.sleep(2)
doit("6.jpg")
time.sleep(2)
doit("7.jpg")
```
For this slice of code, what i want is when the function called the UI will update,
but actually the window will block and only the .py exited the window will update the ui and everything will be ok.
I hope update the ui correctly.
:) Thank you!

**Comment by RickyYChan** [comment]
> > First of all, make sure that you set DataContext correctly and you can get your Classifier data from it.
> > Secondary, if you want UI to handle updates in binding, your class (Classifier for example) needs to implement INotifyPropertyChanged, and invoke PropertyChanged event when some property was changed. Example from WPF, but it will work in same way - [docs](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/how-to-implement-the-inotifypropertychanged-interface?view=netframeworkdesktop-4.8).
> > And finally, View and TextBlock expect PropertyChanged event to be called on the UI thread, so you need to synhronize it in some way. In your case OutputDataReceived invokes handlers on another thread, different from UI or caller thread, so Dispatcher.UIThread.Post won't work in place where you tried. But this will work, if you wrap your NotifyPropertyChanged (from WPF example) into Dispatcher call:
> > ```cs
> >         public string Result
> >         {
> >             get { return res; }
> >             set
> >             {
> >                 if (
> >                     value != string.Empty &&
> >                     value != Environment.NewLine &&
> >                     value != res &&
> >                     value != null
> >                     )
> >                 {
> >                     res = value;
> >                     Dispatcher.UIThread.InvokeAsync(() => NotifyPropertyChanged(nameof(Result))); // or post
> >                 }
> >             }
> >         }
> > ```
> 
> If I work on my way:
> 
> ```cs
> public MainWindow()
>         {
>             InitializeComponent();
> 
>             MyClassifier = new Classifier();
> 
>             Dispatcher.UIThread.Post(() => MyClassifier.RunPythonScript("hello.py"), DispatcherPriority.Send);
> 
> 
> 
> #if DEBUG
>             this.AttachDevTools();
> #endif
> 
>         }
> ```
> 
> When the window has been showed, the process will be lauched indeed, but the main window will block untill the process shut down:
> 
> ```python
> def doit(img_path : str):
>     img = keras.preprocessing.image.load_img(
>     img_path, target_size=(160, 160)
>     )
>     img_array = keras.preprocessing.image.img_to_array(img)
> 
>     img_array = tf.expand_dims(img_array, 0)
>     interpreter = tf.lite.Interpreter(
>         model_path="trash_model_lite.tflite"
>     )
>     interpreter.allocate_tensors()
>     input_details = interpreter.get_input_details()
>     output_details = interpreter.get_output_details()
>     interpreter.set_tensor(input_details[0]['index'], img_array)
>     c = time.time()
>     interpreter.invoke()
>     d = time.time()
>     output_data = np.squeeze(interpreter.get_tensor(output_details[0]['index']))
>     probs = tf.nn.softmax(output_data)
>     class_names = ["hazardous waste", "kitchen waste", "other waste", "recyclable waste"]
>     print(
>         "> This image most likely belongs to {} with a {:2f} percent confidence. Program finished in {:.2f} ms."
>         .format(class_names[np.argmax(probs)], 100 * np.max(probs), (d-c) * 1000)
>     , flush=True)
> doit("sp.jpg")
> time.sleep(2)
> doit("1.jpg")
> time.sleep(2)
> doit("2.jpg")
> time.sleep(2)
> doit("3.jpg")
> time.sleep(2)
> doit("4.jpg")
> time.sleep(2)
> doit("5.jpg")
> time.sleep(2)
> doit("6.jpg")
> time.sleep(2)
> doit("7.jpg")
> ```
> 
> For this slice of code, what i want is everytime the function called the UI will update,
> but actually the window will block and only the .py exited the window will update the ui and everything will be ok.
> I hope update the ui correctly.
> :) Thank you!

It works after I changed the method to a asynchronous method.
How stupid am I!
And for the later people with same problem, i'll show my code:
```C#
public class Classifier : INotifyPropertyChanged
    {
        private string res = string.Empty;

        public string Result
        {
            get { return res; }
            set
            {
                if (
                    value != string.Empty &&
                    value != Environment.NewLine &&
                    value != res &&
                    value != null
                    )
                {
                    res = value;
                    Dispatcher.UIThread.InvokeAsync(
                        () => NotifyPropertyChanged(nameof(Result))
                        );
                }
            }
        }

        public event PropertyChangedEventHandler? PropertyChanged;
        private void NotifyPropertyChanged([CallerMemberName] string propertyName = "")
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public async void RunPythonScript(string sArgName, string args = "", params string[] teps)
        {
            await Task.Run(() =>
            {
                Process p = new Process();
                p.StartInfo.FileName = @"python";

                string sArguments = sArgName;
                foreach (string sigstr in teps)
                {
                    sArguments += " " + sigstr;
                }
                sArguments += " " + args;
                p.StartInfo.Arguments = sArguments;
                p.StartInfo.UseShellExecute = false;
                p.StartInfo.RedirectStandardOutput = true;
                p.StartInfo.RedirectStandardInput = true;
                p.StartInfo.RedirectStandardError = true;
                p.StartInfo.CreateNoWindow = true;
                p.OutputDataReceived += (sender, e) => Result = e.Data!;
                p.Start();
                p.BeginOutputReadLine();
                p.WaitForExit();
            }
                );
        }
    }
```
I'm very ingorance. Hope to be a better person. :)
