### ISSUE TITLE
dotnet new -i Avalonia.Templates doesnt work

### ISSUE THREAD

**Issue by steelx** [AvaloniaUI/Avalonia#5554]
Im trying to install Avalonia templates to my system. Im using linux.

`dotnet new -i Avalonia.Templates`

**Expected behavior**
Need to install template so I can select it under "New Solution" from Jetbrains Rider IDE.
![image](https://user-images.githubusercontent.com/3184210/109135097-b6b69080-777c-11eb-9f08-3102709999ff.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/3184210/109134878-853dc500-777c-11eb-8acf-9443188d2ca4.png)

**Desktop (please complete the following information):**
Linux zorinos 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```
╰─ dotnet --info                                                              ─╯
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     zorin
 OS Version:  15
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/ajinkya/dotnet/sdk/5.0.103/

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.103 [/home/ajinkya/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.3 [/home/ajinkya/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.3 [/home/ajinkya/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by CarlosEX** [comment]
Acredito que você precisa instalar este plugin:
https://github.com/ForNeVeR/AvaloniaRider

**Comment by danwalmsley** [comment]
> Acredito que você precisa instalar este plugin:
> https://github.com/ForNeVeR/AvaloniaRider

"I believe you may need to install this plugin"

**Comment by danwalmsley** [comment]
@steelx you didnt show if there was an error or what went wrong?

**Comment by steelx** [comment]
> @steelx you didnt show if there was an error or what went wrong?

Im new to C#. I was trying to install this template from CLI hoping it would appear inside Rider IDE.

**Comment by steelx** [comment]
> Acredito que você precisa instalar este plugin:
> https://github.com/ForNeVeR/AvaloniaRider

Does this plugin allows one to create Avalonia app from a template ?

**Comment by kelson-dev** [comment]
I am also having this issue. I am now able to install the avalonia templates from either Rider (on linux, **with the plugin installed**) or from the CLI. The linux environment is specially Ubuntu 20.04 running in WSL2.

> I get this below message, but there is [no] info of success or error.

`dotnet new --install Avalonia.Templates` gives me the same output. No avalonia packages are installed or mentioned, only default templates are referred to. The same is true if the package version is included as suggested by the[ Nuget page ](https://www.nuget.org/packages/Avalonia.Templates/)

**Comment by grokys** [comment]
The problem here seems to be that `dotnet new -i` on .NET 5 doesn't display any errors if installation fails: https://github.com/dotnet/templating/issues/3752#issuecomment-908165012

> Likely in case above the installation failed, however dotnet new has poor logging for install in 5.0, so the error is not shown.

Try using the .NET 6 (preview) SDK where apparently this has been fixed.

One problem could be that you have additional nuget feeds configure and `dotnet new` is looking in one of these, failing to find the template and exiting without trying nuget.org. See this StackOverflow question: https://stackoverflow.com/questions/44508253/dotnet-new-install-is-looking-at-wrong-nuget-server

**Comment by markopetrovic-neurotech** [comment]
Running into the same issue, tried with .NET 6 and now it says that, no NuGet feeds are configured or they are invalid

**Comment by AntonNah** [comment]
Ubuntu 20.10 not working

**Comment by bussiere** [comment]
Not working either

**Comment by martinandersen3d** [comment]
download the git repository as a zip file.

unpack the zip file

point the install command, to the unzipped folder:

dotnet new install ./avalonia-dotnet-templates-master  
 

Then start a new terminal session and:

dotnet new avalonia.app  
 

enter directory and

dotnet run

Maybe not what you where looking for, but it worked for me.
