### ISSUE TITLE
Popup IsFocusable property has no effect

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#556]
Popup steals focus when it opens even if IsFocusable is false.

**Comment by jkoritzinsky** [comment]
I found a solution for Win32 so I'll get a PR with that soon. Not quite sure how to do it with GTK yet though...

**Comment by danwalmsley** [comment]
@jkoritzinsky awesome that's great thanks

**Comment by danwalmsley** [comment]
@jkoritzinsky did you submit a pr for this?

**Comment by jkoritzinsky** [comment]
Not yet. Still experimenting on it.

**Comment by grokys** [comment]
Just tried this and popup doesn't seem to steal focus. Given that, and the fact that the issue is so old, doesn't have a repro and `IsFocusable` doesn't exist, going to close ;)
