### ISSUE TITLE
Managed OpenFileDialog fails to open without programmatically-specified title

### ISSUE THREAD

**Issue by Splitwirez** [AvaloniaUI/Avalonia#5570]
**Describe the bug**
The managed OpenFileDialog does not open if its `Title` property has not been explicitly set to something other than its default value.

**To Reproduce**
I've created a small repro, which you can download right here:
[avalonia-file-dialog-demo.zip](https://github.com/AvaloniaUI/Avalonia/files/6052053/avalonia-file-dialog-demo.zip)

Just click the buttons to see the differing behavior depending on how `ShowAsync` is called.

**Expected behavior**
A managed OpenFileDialog opens.

**Screenshots**
![image](https://user-images.githubusercontent.com/34009058/109347755-a2889700-7841-11eb-863b-aaa1a824ec33.png)
This exception occurs, but only when the function is called asynchronously. Calling it synchronously fails silently (not sure if that's intended). Something tells me this problem is platform-specific...

**Desktop (please complete the following information):**
- Linux (Kubuntu, version 20.04)

**Additional context**
Happens I stumbled across this problem while trying to get a screenshot of what the managed OpenFileDialog currently looks like, to show to a friend as context for why I was excited about https://github.com/AvaloniaUI/Avalonia/pull/4615 . Funny how such luck works, isn't it?

**Comment by Splitwirez** [comment]
Just checked with a friend who runs Windows (specifically Windows 10, version 20H2)...the dialogs in the repro opened without issue on his machine.

**Comment by Washi1337** [comment]
Can confirm this is the case as well for Linux 5.10.30-1-MANJARO on a pretty minimal Avalonia app using just a single button that opens a new `OpenFileDialog` with `UseManagedSystemDialogs` enabled. Setting the `Title` property before calling `ShowAsync` seems to make it work again.

**Comment by Washi1337** [comment]
Seems to be the case for any `Window` instance, where the `Title` property is set to `null`. 

[X11Window.SetTitle](https://github.com/AvaloniaUI/Avalonia/blob/6a1b5cda2076fb3ea3f93c19505f2dae583c80e5/src/Avalonia.X11/X11Window.cs#L998) does not do any `null` check before calling `Encoding.GetBytes`, causing the exception.

The [Win32 implementation](https://github.com/AvaloniaUI/Avalonia/blob/6a1b5cda2076fb3ea3f93c19505f2dae583c80e5/src/Windows/Avalonia.Win32/WindowImpl.cs#L617) directly moves the Title string into a call to `SetWindowText`, which does accept `null` pointers to be passed on. This probably explains why it does work on Windows 10, but not on Linux running an X server.

**Comment by Washi1337** [comment]
Any progress on this? If not I can start on a PR of my own :)
