### ISSUE TITLE
ComboBox indices are not updated well when bound collection is updated

### ISSUE THREAD

**Issue by emmauss** [AvaloniaUI/Avalonia#5571]
**Describe the bug**
My combobox is bound to a collection that implemets INotifyCollectionChanged. if I clear the collection, add items more than the previous count, the combobox menu updates with all the new items, and the old ones cleared as expected. But selecting any of the items which indices exceed the last index in the previous collection will set the selected index to -1 and clear the box text, even though the item exist in the collection and appears in the menu

**To Reproduce**
1. Create a Combobox, in code or Xaml
2. Set the Items property to an observerable collection with items
3. Clear the items, and add more items than what was in before
4. Select any of the new items with indices greater that the last item in the previous collection
5. Selected Index is set to -1 

**Expected behavior**
Selected Index should be set to the correct index

**Desktop (please complete the following information):**

- OS: Windows 10 20H2
- Version: 0.10.0

**Comment by jmacato** [comment]
@emmauss i was wondering if you can provide a minimal repro for this bug, i cant seem to reproduce this bug here

**Comment by maxkatz6** [comment]
It should have been fixed since 0.10.0

**Comment by emmauss** [comment]
> @emmauss i was wondering if you can provide a minimal repro for this bug, i cant seem to reproduce this bug here

Ok, https://github.com/emmauss/combobox_test

The issue occurs with an implementation of ObservableDictionary. I tested it with two implementations, one on nuget, and a second one, `ObservableDictionary2` in the ui class. They both have issues with the combobox.

**Comment by jmacato** [comment]
Does this video demostrate the issue well?

https://user-images.githubusercontent.com/16554748/128321506-ca6366e6-8601-4db2-8a31-65655b06e8ed.mov

**Comment by jmacato** [comment]
okay i can confirm this bug on Avalonia master. This is a big bug indeed.

**Comment by grokys** [comment]
Added a check to https://github.com/AvaloniaUI/Avalonia/pull/6485 which throws when we encounter which a collection which implements `INotifyCollectionChanged` but not `IList`.

**Comment by jmacato** [comment]
I suppose folks will just have to dynamically transform their lists to IList compatible types.
