### ISSUE TITLE
Fullscreen window width greater than screen width

### ISSUE THREAD

**Issue by radoslawik** [AvaloniaUI/Avalonia#5581]
**Describe the bug**
When the application is in the fullscreen state the width is greater than my screen size. This may cause some elements to be not fully displayed. 

**To Reproduce**

-  Create a new project from `Avalonia MVVM` template
-  Add `ExtendClientAreaToDecorationsHint="true"` to `MainWindow.axaml`
-  Change the alignment of the text to `HorizontalAlignment="Left"`
- Run the app and change the state to fullscreen

**Expected behavior**
The message should be fully visible

**Screenshots**
Screen from the debugger (My screen resolution is **1920**x1080px):
![image](https://user-images.githubusercontent.com/55437425/109521772-f26b9600-7aad-11eb-8e01-f93cb1e32154.png)

Example of the bug:
![image](https://user-images.githubusercontent.com/55437425/109521880-0f07ce00-7aae-11eb-9765-ac6ca4a960be.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 0.10.0

**Additional context**
At first, I thought it is the bug in https://github.com/AvaloniaUI/XamlControlsGallery/issues/8 , but it is reproducible for all windows that use `ExtendClientAreaToDecorationsHint="true"`.

**Comment by Nickelony** [comment]
Issue is still present
https://user-images.githubusercontent.com/20436882/116918648-7843c300-ac50-11eb-9e17-78cf4c3b54de.mp4

**Comment by amwx** [comment]
This is a Win32 thing. To hide the system border when maximized, Windows enlarges the window ~8px on each side, but when the frame is extended, windows doesn't turn this logic off automatically and requires special handling of `WM_NCCALCSIZE` to adjust the client rect which is now the whole window.

The simplest solution though is just to add 8px of padding to the window only when maximized:
````
<Style Selector="Window[WindowState=Maximized]">
        <Setter Property="Padding" Value="8" />
</Style>
````

**Comment by Nickelony** [comment]
> This is a Win32 thing. To hide the system border when maximized, Windows enlarges the window ~8px on each side, but when the frame is extended, windows doesn't turn this logic off automatically and requires special handling of `WM_NCCALCSIZE` to adjust the client rect which is now the whole window.
> 
> The simplest solution though is just to add 8px of padding to the window only when maximized:
> 
> ```
> <Style Selector="Window[WindowState=Maximized]">
>         <Setter Property="Padding" Value="8" />
> </Style>
> ```

Yep, this fixed the issue.

**Comment by amwx** [comment]
> Yep, this fixed the issue.
> Although when un-maximising, I get a weird behaviour like this:
> Look at the edges of the window
> It's not as game-breaking as the extending edges around the window, but it's still a thing :/

Yea that I don't know. It seems for some reason the layout isn't updated until you force a render pass (like hovering over a button or something) when you drag the window from Maximized. I've opened an issue #5874 about that

**Comment by Nickelony** [comment]
I think this can be closed since it has already been fixed.

**Comment by radoslawik** [comment]
It hasn't been fixed yet, the issue can be reproduced in version 0.10.13

**Comment by sekulicb** [comment]
Can confirm, issue still exists and the proposed solution by @amwx doesn't looks nice when you have 27-28" monitor and the app is maximized.

**Comment by DrWenz** [comment]
Can confirm, issue still exists an 0.10.15.
`<Setter Property="Padding" Value="8" />`  is not the best solution but it works for now :)

**Comment by mozesa** [comment]
```xaml
    <Window.Styles>
        <Style Selector="Window[WindowState=Maximized]">
            <Setter Property="Padding" Value="8" />
        </Style>
    </Window.Styles>
```

The workaround works fine on `0.10.18`, no weird behavior when `un-maximising`.

**Comment by kekekeks** [comment]
That's how Windows maximizing works, by design.

**Comment by kulikov-dev** [comment]
It works pefrect for 0.10, but in Avalonia 11 it doesn't work anymore. Any ideas how to fix it?

**Comment by kulikov-dev** [comment]
> It works pefrect for 0.10, but in Avalonia 11 it doesn't work anymore. Any ideas how to fix it?

Well, credit goes to a random guy from the tg channel who showed me this trick. The solution for Avalonia 11 is to bind the margin to the top element in the window, which depends on the window state, like:

```C#
    <Border Margin="{Binding WindowStateMargin}">
```
```C#
        /// <summary>
        /// Margin for main window if state is maximized
        /// </summary>
        private static readonly Thickness _maximizedWindowStateMargin = new(8);

        /// <summary>
        /// Margin for main window if state is normal/hidden
        /// </summary>
        private static readonly Thickness _normalWindowStateMargin = new(0);

        public WindowState WindowState
        {
            get
            {
                return _windowState;
            }

            set
            {
                if (_windowState == value)
                {
                    return;
                }

                _windowState = value;

                WindowStateMargin = _windowState == WindowState.Maximized ? _maximizedWindowStateMargin : _normalWindowStateMargin;

                this.RaisePropertyChanged(nameof(WindowState));
                this.RaisePropertyChanged(nameof(WindowStateMargin));
            }
        }

        /// <summary>
        /// Margin for main window
        /// </summary>
        public Thickness WindowStateMargin { get; private set; }
```
