### ISSUE TITLE
ListBox virtualization gets turned off if control is hidden in different tab in TabControl

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#560]
When the `ListBox` with virtualization enabled is hidden (for example in different tab) looks like virtualization is turned off.

**Comment by grokys** [comment]
Is this still happening? I tried to reproduce by adding tabs to the virtualization test, but I couldn't trigger it. If it is still happening do you have a repro?

**Comment by wieslawsoltes** [comment]
Yes its still happening in `Core2D`. When I have `ListBox` in different tab and load project, switching to this tab causes huge memory spike and eventually crush.
