### ISSUE TITLE
EditBox with AcceptReturn="false" accepts pasting text with CR(LF) characters.

### ISSUE THREAD

**Issue by YevgenijZ** [AvaloniaUI/Avalonia#5600]
**Describe the bug**
EditBox with AcceptReturn="false" accepts pasting text with CR-LF and transforms to multi-line EditBox.

**To Reproduce**
In any app select multi-line text.
Paste selection into EditBox

**Expected behavior**
CR(LF) should be removed when pasting text.

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Windows

**Comment by Gillibald** [comment]
That's by design

**Comment by YevgenijZ** [comment]
This is vey odd, in other apps I've seen either discarding pasted text after first line break or just remove line breaks. Not really pleasant to see TextBox growing twice in height out of sudden.

**Comment by YevgenijZ** [comment]
MaxLines is a good options and it definitely missing, but have a look WPFs TextEditCopyPaste.PastePlainText .
![image](https://user-images.githubusercontent.com/8945897/109842078-5f1f9580-7c52-11eb-9d2c-07891892cc7f.png)

**Comment by Gillibald** [comment]
We can adapt that behavior in a future version of the TextBox. Feel free to submit a PR that addresses this in the current version.
