### ISSUE TITLE
DataGrid is not working

### ISSUE THREAD

**Issue by yiszza** [AvaloniaUI/Avalonia#5624]
![image](https://user-images.githubusercontent.com/42995476/110205796-1287c480-7eb5-11eb-854d-55906218b56c.png)

**Comment by workgroupengineering** [comment]
Add this in window or app

```xml
  <Window.Styles>
    <StyleInclude Source="resm:Avalonia.Controls.DataGrid.Themes.Default.xaml?assembly=Avalonia.Controls.DataGrid"/>
  </Window.Styles>
```

**Comment by yiszza** [comment]
> Add this in window or app
> 
> 在窗口或应用程序中添加这个
> 
> ```
>   <Window.Styles>
>     <StyleInclude Source="resm:Avalonia.Controls.DataGrid.Themes.Default.xaml?assembly=Avalonia.Controls.DataGrid"/>
>   </Window.Styles>
> ```

thanks!
