### ISSUE TITLE
TabItem HeaderTemplate style won't be applied

### ISSUE THREAD

**Issue by VNNCC** [AvaloniaUI/Avalonia#5631]
**Describe the bug**
The styling of the property ``TabItem.HeaderTemplate`` has no effect on the style of the ``TabItem`` in the end.

**To Reproduce**

1. Create a new style for a ``TabItem`` and set the ``HeaderTemplate`` property
```xml
<Style Selector="TabItem">
    <Setter Property="FontSize" Value="21" />
    <Setter Property="HeaderTemplate">
        <DataTemplate DataType="vm:TestVM">
            <TextBlock Text="Test" />
        </DataTemplate>
    </Setter>
</Style>
```
2. Create a new ``TabControl`` and bind to items
3. See error

**Expected behavior**
The header template should be used from the declared style.

**Screenshots**
Actual:
(Calls the ``ToString()`` method from the object)
![image](https://user-images.githubusercontent.com/52937757/110258444-f5c9ba80-7fa2-11eb-9dc4-5b125e9af132.png)

Expected:
Use the defined ``TabItem.HeaderTemplate`` style
![image](https://user-images.githubusercontent.com/52937757/110258397-b8652d00-7fa2-11eb-9beb-e24b56fec51d.png)

**Additional information**
When removing the following part from the ``Avalonia.Controls.Generators.TabItemContainerGenerator`` ``CreateContainer`` method, the style will correctly be applied to the ``TabItem``.
```cs
if (tabItem.HeaderTemplate == null)
{
    tabItem.Bind(TabItem.HeaderTemplateProperty, new OwnerBinding<IDataTemplate>(
        tabItem,
        TabControl.ItemTemplateProperty));
}
```

**Desktop**

- OS: Windows 10
- Version 0.10.0 and 0.10.999-cibuild0013089-beta

**Comment by maxkatz6** [comment]
How are you using TabItem?
Usually it's used inside of TabControl, where ItemTemplate is used for header (which overrides HeaderTemplate in that case) and ContentTemplate for content.

Not sure if it's expected to fallback to HeaderTemplate.

**Comment by VNNCC** [comment]
Alright I tested your suggestion and it works.
