### ISSUE TITLE
ExtendClientAreaToDecorationsHint="True" Ignores Width/Height, etc. Defined Before

### ISSUE THREAD

**Issue by Afanyiyu** [AvaloniaUI/Avalonia#5632]
**Describe the bug**
Setting `ExtendClientAreaToDecorationsHint="True"` in Avalonia Window XAML will ingore some `Window` properties defined before.

**To Reproduce**
```xaml
<!--MainWindow.axaml-->
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        Width="500" Height="600"
        CanResize="False"
        ExtendClientAreaToDecorationsHint="True">
  Welcome to Avalonia!
</Window>
```

The `Width="500" Height="600" CanResize="False"` aren't working properly.

**Expected behavior**
All properties work properly.

**Desktop (please complete the following information):**

- OS: Windows 10.0.21318.1000
- Version 0.10.0

**Additional context**
I use `ExtendClientAreaToDecorationsHint="True"` with instructions in #4540 and found this issue. There are several issues (#4248, #5077, #5526) mentioned this problem with different varieties of properties before. Also, it was [seemed to be fixed](https://github.com/AvaloniaUI/Avalonia/issues/4248#issuecomment-661541591) before v0.10.0 was released, but i found the problem again using v0.10.0.

(To others who have also encountered this problem: You can avoid this by setting other properties after `ExtendClientAreaToDecorationsHint`.

**Comment by Takoooooo** [comment]
I think it works everywhere starting from 0.10.1.Just tested
