### ISSUE TITLE
Adding path processing API for Geometry

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#5634]
We should add the following API because SVG and Lottie needs it:

`Geometry.GetFlattenedPathGeometry`
https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.geometry.getflattenedpathgeometry?view=net-5.0

`ComputeLength`
https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.Direct2D1/Geometry.cs#L125

`ComputePointAtLength`
https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.Direct2D1/Geometry.cs#L148

Example use in WPF:
https://stackoverflow.com/questions/21728753/to-get-length-of-wpf-path

and a sample use on WPF Lottie library:
https://github.com/ascora/LottieSharp/blob/master/LottieSharp/PathMeasure.cs#L19-L21

**Comment by jmacato** [comment]
i think #5683 fixed this? @wieslawsoltes

**Comment by wieslawsoltes** [comment]
> i think #5683 fixed this? @wieslawsoltes

I think Geometry.GetFlattenedPathGeometry is still missing
