### ISSUE TITLE
Binding Converter in DataGridTextColumn

### ISSUE THREAD

**Issue by boonkerz** [AvaloniaUI/Avalonia#5647]
**Describe the bug**
<DataGridTextColumn Header="Status" 
                                    Binding="{Binding Status}" 
                                    Width="*"
                                    Foreground="{Binding  Status, Converter={StaticResource StatusConverter}}">
                </DataGridTextColumn>

converter is not called.
<DataGridTextColumn Header="Status" 
                                    Binding="{Binding Status}" 
                                    Width="*"
                                    Foreground="{Binding Converter={StaticResource StatusConverter}}">
                </DataGridTextColumn>

the Converter will be called but without any data.

JetBrains Rider 2020.3.3
Build #RD-203.7148.23, built on February 17, 2021
Licensed to Rider Evaluator
Expiration date: April 7, 2021
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
.NET Core 3.1.8
macOS 10.16

**Comment by maxkatz6** [comment]
I used converter with DataGridTextColumn and without any problems before.
Can you provide some code or project that can be run and tested?

**Comment by boonkerz** [comment]
`
<DataGridTextColumn Header="Status" 
                                    Binding="{Binding Status}" 
                                    Width="*"
                                    Foreground="{Binding  Status, Converter={StaticResource StatusConverter}}">
</DataGridTextColumn>
`

Converter is not called.

`
<DataGridTextColumn Header="Status" 
                                    Binding="{Binding Status}" 
                                    Width="*"
                                    Foreground="{Binding Converter={StaticResource StatusConverter}}">
</DataGridTextColumn>
`

Converter is called

**Comment by maxkatz6** [comment]
Note that only Binding property has access to the row data context.
You can't access row information from any other property in the column. It's the same behavior as WPF/UWP have.
But you should be able to use CellStyleClasses, something like:
```xaml
<DataGridTextColumn ... CellStyleClasses="customClass" />
```
```xaml
<DataGrid.Styles>
   <Style Selector="DataGridCell.customClass">
       <Setter Property="Foreground" Value="{Binding Status, Converter={StaticResource StatusConverter}}" />
   </Style>
</DataGrid.Styles>
```

**Comment by boonkerz** [comment]
Ok

Now the StatusConverter is called but the Value is not used.

```
<Setter Property="Foreground" Value="green" />
```

works when i use my converter it does not change the color:

```
public class StatusConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value.Equals("RUNNING")) return Color.Green;
            return Color.Red;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value.Equals("RUNNING")) return "green";
            return "red";
        }
    }
```

also tested:

```
public class StatusConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value.Equals("RUNNING")) return "green";
            return "red";
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value.Equals("RUNNING")) return "green";
            return "red";
        }
    }
```

**Comment by maxkatz6** [comment]
@boonkerz it's hard to say from these code pieces what's the problem.
For now I can only say that you need to return IBrush (SolidColorBrush in your case) from the converter to match Foreground property type.
Also check Avalonia logs, there could be details, why binding could not work.

**Comment by boonkerz** [comment]
Thx 

nice hint to IBrush and SolidColorBrush.

Works :)
```
var brush = new SolidColorBrush();
            brush.Color = Colors.Green;
            
            if (value.Equals("running")) return brush;

            brush.Color = Colors.Red;
            
            return brush;
```
