### ISSUE TITLE
Incorrect path to previews in nuget are added to msbuild properties

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaUI/Avalonia#5658]
**Describe the bug**
Incorrect path to previews in nuget are added to msbuild properties. An extra slash is inserted after `buildTransitive\`

**To Reproduce**
1. `dotnet new avalonia.app -o test`
2. Update csproj similar
```xml
<Project InitialTargets="DisplayMessages" Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.10.0" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.0" />
    <PackageReference Include="Avalonia.Diagnostics" Version="0.10.0" />
  </ItemGroup>
  <Target Name="DisplayMessages">
    <Message Importance="High" Text="AvaloniaPreviewerNetCoreToolPath = $(AvaloniaPreviewerNetCoreToolPath)" />
    <Message Importance="High" Text="AvaloniaPreviewerNetFullToolPath = $(AvaloniaPreviewerNetFullToolPath)" />
    <Message Importance="High" Text="AvaloniaBuildTasksLocation       = $(AvaloniaBuildTasksLocation)" />
  </Target>
</Project>
```
3. `dotnet build`

https://github.com/AvaloniaUI/Avalonia/blob/5f076bd536880d009e67b00b8352dcbf76ae1f7b/packages/Avalonia/Avalonia.props#L3-L5

**Comment by kekekeks** [comment]
`dotnet msbuild /t:DisplayMessages` shows correct values here for both Windows and Linux. Are you sure that you are using the right MSBuild version that comes with the SDK?

**Comment by kekekeks** [comment]
Ah, I see, the extra slash is here on Windows which prevents it from parsing the path properly.

**Comment by rstm-sf** [comment]
It looks like this is a feature not working for Windows File Explorer
