### ISSUE TITLE
Can't drag Window extended into TitleBar

### ISSUE THREAD

**Issue by vadd98** [AvaloniaUI/Avalonia#5664]
**Describe the bug**

I extended my Window into the TitleBar. In order to make it draggable, I added a DummyGrid empty on the top of the Window in order to be able to drag the Window from the position of the native TitleBar. I did something like this:

```
	<Grid>
		<reactiveUi:RoutedViewHost Router="{Binding Router}" />
		<Grid x:Name="DummyGrid" Height="20" IsHitTestVisible="False" VerticalAlignment="Top" HorizontalAlignment="Stretch"/>
	</Grid>
```

By the way, even though I put IsHitTestVisible="False" in the DummyGrid, it is still not draggable. 

**To Reproduce**

1. Extend a Window content into the TitleBar
2. Add a dummy control that will act as TitleBar
3. Try to drag

**Expected behavior**
Drag window using a dummy control.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Windows 10, MacOS Big Sur]
- Version [0.10.0]

**Additional context**

**Comment by FrankenApps** [comment]
Did you set `CanResize="false"`?
Otherwise I am pretty sure it works, I have a sample [here](https://github.com/FrankenApps/Avalonia-CustomTitleBarTemplate).

**Comment by vadd98** [comment]
You mean to set `CanResize="false"` on the Window? If yes, why would I have to do that? I want my Window to be resizable.
By the way I downloaded your sample and I didn't find any `CanResize="false"` reference in the MainWindow, even though I can confirm that your sample works.

**Comment by FrankenApps** [comment]
You must not set `CanResize="false"`. There is a problem when you set `CanResize="false"` where you can not drag the window. That is why I asked. Btw. I have also found a workaround for that which can be found [here](https://github.com/FrankenApps/Avalonia-CustomTitleBarTemplate/tree/non-resizable).
However if the sample works, that means that the Issue is in your code and not in Avalonia, so I think this could be closed.

**Comment by vadd98** [comment]
I watched your sample trying to understand why it works and why my code doesn't.
Applying your flow to my code, and so obtaining this:

```
	<DockPanel HorizontalAlignment="Stretch"
	           VerticalAlignment="Stretch"
	           Name="ContentWrapper">

		<control:TitleBarControl VerticalAlignment="Top" HorizontalAlignment="Stretch" IsHitTestVisible="False" />
		
		<DockPanel Background="Transparent" >
			<Grid>
				<reactiveUi:RoutedViewHost x:Name="MainRouter" Router="{Binding Router}" />
			</Grid>
		</DockPanel>
	</DockPanel>
```

Dragging from the TitleBarControl works. By the way doing this the TitleBarControl doesn't overlap the other content.
My aim is to have a transparent TitleBar area that overlaps my pages (and so it takes the different background colors from the pages behind), while in this way I have to separate areas.

Editing the code in this way:

```
	<Grid>
		<reactiveUi:RoutedViewHost x:Name="MainRouter" Router="{Binding Router}" />
                <control:TitleBarControl VerticalAlignment="Top" HorizontalAlignment="Stretch" IsHitTestVisible="False" />
	</Grid>
```
and so putting the TitleBarControl above my pages, I obtain the visual effect I want, by the way dragging stops to work.

My conclusion is that in order to make dragging work, the `IsHitTestVisible="False"` control has to be the "lowest" one, otherwise for some reason the dragging event can't be handled.

Any suggestion about this? My conclusion is right or is this just a case?

**Comment by kekekeks** [comment]
If you want to have non-transparent areas that initiate window drag, you need to manually call `Window::BeginMoveDrag`

**Comment by vadd98** [comment]
> 
> 
> If you want to have non-transparent areas that initiate window drag, you need to manually call `Window::BeginMoveDrag`

Thanks! This was the missing piece, now it works flawlessly.
