### ISSUE TITLE
Animations don't work with DynamicResources

### ISSUE THREAD

**Issue by vadd98** [AvaloniaUI/Avalonia#5672]
**Describe the bug**

I have this animation:

```
                <Style Selector="Button.FailedLogin">
                    <Style.Animations>
                        <Animation Duration="0:0:0.5" PlaybackDirection="Alternate" IterationCount="2"> 
                            <KeyFrame Cue="100%">
                                <Setter Property="Background" Value="{DynamicResource Red}"/>
                                <Setter Property="Foreground" Value="White"/>
                            </KeyFrame>
                        </Animation>
                    </Style.Animations>
                </Style>
```

The Foreground value is actually set to White, while the Background value isn't set to Red. 
I underline that this Red is a custom red I have in my Application.Resources: `<Color x:Key="Red">#FFE9002F</Color>`

If I replace `<Setter Property="Background" Value="{DynamicResource Red}"/>` with `<Setter Property="Background" Value="Red"/>`, and so use the default red, it works flawlessly.

**To Reproduce**

1. Create an animation inside Style.Animations
2. Change the color of a property using a DynamicResource
3. Trigger the animation

**Expected behavior**
Being able to use DynamicResources in Animations

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Windows 10, MacOS Big Sur]
- Version [0.10.0]

**Additional context**

**Comment by maxkatz6** [comment]
It works now
