### ISSUE TITLE
ComboBox IsEditable

### ISSUE THREAD

**Issue by frapendev** [AvaloniaUI/Avalonia#5673]
ComboBox does not provide the IsEditable property.
Would it be possible to add this property to the control so that it works like in WPF?
Thanks!

**Comment by maxkatz6** [comment]
See https://github.com/AvaloniaUI/Avalonia/issues/205#issuecomment-800620660

**Comment by cbrunin** [comment]
Hi, Any news on this one? 
Would be quite helpfull.
