### ISSUE TITLE
Support for mouse buttons 4 and 5

### ISSUE THREAD

**Issue by SteezCram** [AvaloniaUI/Avalonia#5679]
**Is your feature request related to a problem? Please describe.**
For a project, I need to get when the user presses buttons 4 and 5 to mimic the Windows File Explorer navigation. So I add a handler for the `MouseUp` event on my main window to call a method when the user clicks on a button of its mouse.

Unfortunately the property: `InitialPressMouseButton` that has a `MouseButton` type doesn't have a property to handle the mouse buttons 4 and 5 even if the event method has been called.

**Describe the solution you'd like**
To complete the `MouseButton` enum with: `Button4` and `Button5` properties.

**Describe alternatives you've considered**
I cannot find any alternative given that the only way to capture the event is to handle the `MouseUp` event.

**Comment by kekekeks** [comment]
It seems that only https://github.com/AvaloniaUI/Avalonia/blob/554aaec5e5cc96c0b4318b6ed1fbf8159f442889/src/Avalonia.Input/PointerPoint.cs#L85-L94 and the MouseButton enum needs to be updated.
 Probably was an oversight in https://github.com/AvaloniaUI/Avalonia/pull/3033

**Comment by SteezCram** [comment]
Yes thank you, I have achieved to do it with the PointerReleasedEvent.

**Comment by SutandoTsukai181** [comment]
Why was this issue closed? [MouseButton](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Input/PointerEventArgs.cs#L105-L111) and [GetMouseButton](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Input/PointerPoint.cs#L85-L94) were still not updated. Shouldn't they be modified to be up to date with #3033?

**Comment by SteezCram** [comment]
Oh yes sorry, it was a misclick when I close another issue
