### ISSUE TITLE
Add supports Platform compatibility analyzer

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaUI/Avalonia#5698]
Add supports [Platform compatibility analyzer](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/platform-compat-analyzer) (>= .NET 5)

In addition to specifying which platform is available, we can also specify which version of the platform is available
```cs
[SupportedOSPlatform("windows8.0")]
[UnsupportedOSPlatform("windows10.0.19041.0")]
public void ApiSupportedFromWindows80SupportFromCertainVersion();
```

Related issues: #3691

**Comment by maxkatz6** [comment]
You don't need to change project target to use these new attributes. AFAIK you can create internal polyfills and it will just work, even with public API code. 

Something like people did with Nullable before
https://github.com/manuelroemer/Nullable
