### ISSUE TITLE
Horizontal and vertical line render issue with DPI scale of 1.5

### ISSUE THREAD

**Issue by petedavis** [AvaloniaUI/Avalonia#5709]
**Describe the bug**
When a line is horizontal or vertical and has a point with and odd number, there is a rendering issue with DPI scaling the point value by 1.5 that causes the line to no longer snap to a pixel and become aliased.

**To Reproduce**
1. Add the following line to the CanvasPage.xaml:
      `<Line StartPoint="109,195" EndPoint="52,195" Stroke="Black" StrokeThickness="1"/>`
1. Display the ControlCatalog on a display that has a DPI scaling of 1.5

**Expected behavior**
I would expect the line to snap to the device pixels and still appear as a solid horizontal line as shown in the screenshot.

**Screenshots**
With DPI scale of 1.0
![image](https://user-images.githubusercontent.com/164331/112238255-2ba1bb00-8c94-11eb-9fd3-4f24915d81bf.png)

With DPI scale of 1.5
![image](https://user-images.githubusercontent.com/164331/112238234-204e8f80-8c94-11eb-9c0d-a7bca119cafd.png)

**Desktop:**
- OS: Windows
- Version: 0.10.999-cibuild0013089-beta

**Aditional Info:**
In `MeasureCore(Size availableSize)` method, after calling MeasureOverride, the `height=195` and `width=109`
After calling `width = LayoutHelper.RoundLayoutValue(109, 1.5)`, width is now `109.33333333333`

Not too sure if we should be fully implementing `SnapsToDevicePixels` and converting value to an int, or if this is a bug in RoundLayoutValue, and we still need to round the final value?

**Comment by petedavis** [comment]
From a deeper investigation, it looks like this is just the result from Skia rendering on a half pixel boundary, which results in one pixel row for the line, and 25% color in both adjoining pixel rows (in the horizontal case). Rounding isnt causing the issue. 

Looks like a SnapsToDevicePixels feature would be required to resolve this issue.

In the data that I am rendering, I am getting horizontal and vertical lines almost disappearing with 1.5 DPI scaling:

1.5 DPI scaling:
![image](https://user-images.githubusercontent.com/164331/112242384-ae7a4400-8c9b-11eb-8a53-693e7ebe0eea.png)

1.0 DPI scaling:
![image](https://user-images.githubusercontent.com/164331/112242505-ebded180-8c9b-11eb-8f0d-8a68360f9210.png)

**Comment by petedavis** [comment]
Another interesting outcome with lines with a width of 1 and DPI of 1.5 is that you never get a solid line even on even pixel boundaries. Result is 2 rows of 50% color.

![image](https://user-images.githubusercontent.com/164331/112245073-25b1d700-8ca0-11eb-8db6-a0f14d6f6066.png)

```
      <Line StartPoint="50,196" EndPoint="100,196" Stroke="Black" StrokeThickness="1"/>
      <Line StartPoint="100,197" EndPoint="150,197" Stroke="Black" StrokeThickness="1"/>
      <Line StartPoint="150,198" EndPoint="200,198" Stroke="Black" StrokeThickness="1"/>
      <Line StartPoint="200,199" EndPoint="250,199" Stroke="Black" StrokeThickness="1"/>
```

**Comment by petedavis** [comment]
WPF comparison as above. even pixel lines are slightly more solid:
![image](https://user-images.githubusercontent.com/164331/112245695-4af31500-8ca1-11eb-80ac-5ffb5eb6443a.png)

SnapsToDevicePixels reulsts in all lines being equal in with 1 solid pixel row and a 50% color pixel row:
![image](https://user-images.githubusercontent.com/164331/112245821-90afdd80-8ca1-11eb-9105-a73c5a7c8aff.png)

**Comment by mysteryx93** [comment]
So that means Avalonia has SnapToDevicePixels set to False and cannot be changed? It's one of those weird behaviours in WPF that I always disable.

Does it blur images for displaying in-between pixels?

This in-between pixels calculation also have a performance cost.

**Comment by mysteryx93** [comment]
There is UseLayoutRounding property, did you try setting that to True?

**Comment by maxkatz6** [comment]
UseLayoutRounding does the work
