### ISSUE TITLE
MenuItem grayed out after first click 

### ISSUE THREAD

**Issue by Shadow4walker** [AvaloniaUI/Avalonia#5716]
**Describe the bug**
MenuItem grayed out

**To Reproduce**

1. Create a new Avalonia Project
2. Add Avalonia.Controls.DataGrid
3. xaml example

> 	<DataGrid>
		<DataGrid.ContextMenu>
			<ContextMenu Name="DaContextMenu">

				<MenuItem Header="(Selected Item)">
					<MenuItem Header="Log" Command="{Binding SomeCommand}" />
				</MenuItem>

			</ContextMenu>
		</DataGrid.ContextMenu>
		<DataGrid.Columns>
			<DataGridTextColumn Header="Header" />
		</DataGrid.Columns>
	</DataGrid>

4. VM Example

> 
    public class MainWindowViewModel : ViewModelBase
    {
        public MainWindowViewModel()
        {
            SomeCommand = ReactiveCommand.Create(OnSomeCommand);
        }

        private protected void OnSomeCommand()
        {
            var desktop = Application.Current.ApplicationLifetime
                as IClassicDesktopStyleApplicationLifetime;
            var mainWindow = desktop?.MainWindow;
            if (mainWindow == null) throw new NullReferenceException("MainWindows is Null!");

            new SomeView().ShowDialog(mainWindow);
        }

        public ReactiveCommand<Unit, Unit> SomeCommand { get; }
    }
> 
SomeView is just a simple View.
MenuItem grayed out after lost Focus or Something!
after click Log the first time > all works as expected but when try to click again the Log MenuItem grayed out and can't click it anymore

**Comment by maxkatz6** [comment]
Hello @Shadow4walker !
I can't reproduce your issue with DataGrid and ContextMenu, using binding to the same command.
Do you have any project, that can be tested to reproduce this issue?

![23](https://user-images.githubusercontent.com/3163374/112740471-4d789780-8f4b-11eb-8e18-fc840bcfcc73.gif)

**Comment by Shadow4walker** [comment]
@maxkatz6 Thanks for your response
project with the issue [BugTest](https://github.com/Shadow4walker/BugTest)

**Comment by danwalmsley** [comment]
@Shadow4walker without looking into it, id bet that the command throws an exception and doesnt complete...

wrap in a try, catch, finally?

I think ReactiveCommand has an OnException too.

**Comment by Shadow4walker** [comment]
> @Shadow4walker without looking into it, id bet that the command throws an exception and doesnt complete...
> 
> wrap in a try, catch, finally?
> 
> I think ReactiveCommand has an OnException too.

I've tried with Try catch , with no hint on what's going on!

>         
        private protected void OnSomeCommand()
        {
            try
            {
                new SomeView().ShowDialog(new Window());
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            finally
            {
                Console.WriteLine("All Fine!");
            }
        }

you may test with the project i sent above and see by yourself

**Comment by Shadow4walker** [comment]
any update on this? still not fixed in the latest v0.10.3!

**Comment by Shadow4walker** [comment]
the issue appear to be related to ReactiveUi, idk why it's worked in a previous release of Avalonia!
however fixed by using this code
>
        private protected void OnSomeCommand()
        {
            Dispatcher.UIThread.InvokeAsync(() =>
            {
                var desktop = Application.Current.ApplicationLifetime
                    as IClassicDesktopStyleApplicationLifetime;
                var mainWindow = desktop?.MainWindow;
                if (mainWindow == null) throw new NullReferenceException("MainWindows is Null!");

                new SomeView().ShowDialog(mainWindow);
            });
        }

due to that one of the features of Reactive Command is that it disables the command while the operation is in progress and the previous code was never return => based on this [button bound to a ReactiveAsyncCommand gets disabled after one use](https://stackoverflow.com/questions/15114427/reactiveui-button-bound-to-a-reactiveasynccommand-gets-disabled-after-one-use)
