### ISSUE TITLE
ListBox is not always redrawn when Items are changed

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#572]
ListBox is not always redrawn when Items are changed, VistualizationMode is simple.

Reproducable with VirtualizationTest:

- make items count 10
- start clicking add item button

After 3 click new items will be shown:

Video: http://sendvid.com/xw7v0w31

**Comment by grokys** [comment]
Hmm, this should have been fixed a few days ago. Are you sure you're up to date on master? I can't reproduce here.

**Comment by donandren** [comment]
yea after update of latest master it was not happening any more.
Looks like it's fixed in:
https://github.com/AvaloniaUI/Avalonia/commit/04c48bbd5487781fbb915d143613163a8324a387
