### ISSUE TITLE
Specified data type property on a template cannot be used for compiled bindings

### ISSUE THREAD

**Issue by YohDeadfall** [AvaloniaUI/Avalonia#5726]
Found an issue today happening with compiled bindings which I prefer to user whenever possible when the XAML compiler produces an error for a non `DataTemplate` with the specified `DataType` as a property. Haven't tested it yet with `TreeDataTemplate` directly, but we have an class inheriting from it which caused the problem.

With compiled bindings enabled the following XAML will trigger the issue:

```xml
<y:CustomTreeDataTemplate
    DataType="z:SomeType" />
```

But if `x:DataType` pointing to the same type is added, everything goes fine:

```xml
<y:CustomTreeDataTemplate
    x:DataType="z:SomeType"
    DataType="z:SomeType" />
```

Looks like the compiler only understands how to work with the built in types at least or just with data templates.

/cc @grokys

**Comment by maxkatz6** [comment]
It seems to be just simple XDataTypeTransformer 
Something like that https://github.com/AvaloniaUI/Avalonia/blob/master/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/XNameTransformer.cs

cc @kekekeks

**Comment by kekekeks** [comment]
We should probably add a marker attribute or something. Right now the check for DataTemplate is hardcoded here: https://github.com/AvaloniaUI/Avalonia/blob/7842883961d094e08e9def7f30cf32fd573179c7/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlDataContextTypeTransformer.cs#L59-L61
