### ISSUE TITLE
Error on SelectingItemsControl.SelectionMode

### ISSUE THREAD

**Issue by FournyP** [AvaloniaUI/Avalonia#5730]
Hello everyone, I have found a bug with SelectingItemsControl

**Describe the bug**
I have created a SelectingItemsControl in my view.
During the runtime, when I try to show the view, I get an error if I set SelectionMode

**To Reproduce**
1. Create a view with a SelectingItemsControl and a SelectionMode set like this : 
```
<SelectingItemsControl
			Margin="0,0,16,0"
			Padding="0"
			Items="{Binding ActualPath, Mode=OneWay}"
			x:Name="AddressBar"
			SelectionMode="Single">
			<i:Interaction.Behaviors>
				<ia:EventTriggerBehavior EventName="Tapped" SourceObject="{Binding #AddressBar}">
					<ia:InvokeCommandAction Command="{Binding MoveToRepository}" CommandParameter="{Binding SelectedItem, ElementName=AddressBar}"/>
				</ia:EventTriggerBehavior>
			</i:Interaction.Behaviors>
			<SelectingItemsControl.ItemsPanel>
				<ItemsPanelTemplate>
					<StackPanel Orientation="Horizontal" />
				</ItemsPanelTemplate>
			</SelectingItemsControl.ItemsPanel>
			<SelectingItemsControl.ItemTemplate>
				<DataTemplate>
					<StackPanel>
						<TextBlock
							HorizontalAlignment="Center"
							VerticalAlignment="Center"
							Text="{Binding Name}"/>
					</StackPanel>
				</DataTemplate>
			</SelectingItemsControl.ItemTemplate>
		</SelectingItemsControl>
```
2. Run your app
3. See error

**Expected behavior**
A SelectingItemsControl who didn't throw an error when I set SelectionMode

**Screenshots**
![image](https://user-images.githubusercontent.com/64586968/113430826-21419880-93db-11eb-99ef-cd7205097791.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version 1909
- Avalonia Version : 0.10.999-cibuild0013089-beta

Have a good day and thanks for your work.

**Comment by jp2masa** [comment]
I don't think you're supposed to use `SelectingItemsControl` directly, it doesn't even have a default template IIRC.

**Comment by Gillibald** [comment]
SelectingItemsControl is just a base class and should not be used directly. Everything works as expected.

**Comment by grokys** [comment]
Yeah we should probably make it abstract or make the ctor protected to communicate this better.
