### ISSUE TITLE
spectrum

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#5743]
I want to complete the spectrum display, is there any way to achieve it?

Are there any implemented controls?

Can QT components or windows be loaded?

**Comment by kekekeks** [comment]
You mean like this? https://www.youtube.com/watch?v=uWH2Xf9tPwM

**Comment by rstm-sf** [comment]
Do you need something like this?
- https://youtu.be/amZgP-_ZOh0
- https://github.com/ahopper/Patroclus

**Comment by robloo** [comment]
@maxkatz6 ported the ColorSpectrum from WinUI here: https://github.com/maxkatz6/AvaloniaWinUI.ColorPicker

**Comment by PieroCastillo** [comment]
> I want to complete the spectrum display, is there any way to achieve it?
> 
> Are there any implemented controls?
> 
> Can QT components or windows be loaded?

u can use custom skiasharp rendering 
https://github.com/PieroCastillo/Aura.UI/blob/master/src/Aura.UI/Rendering/ArcRender.cs
https://github.com/PieroCastillo/Aura.UI/blob/master/src/Aura.UI/Controls/Colouring/Arc/Arc.cs

**Comment by PieroCastillo** [comment]
if you refer to the color spectum u can use custom skiasharp rendering
https://github.com/PieroCastillo/Aura.UI/blob/master/src/Aura.UI/Rendering/ColorWheelRender.cs
https://github.com/PieroCastillo/Aura.UI/blob/master/src/Aura.UI/Controls/Colouring/ColorWheel/ColorWheel.cs

**Comment by robloo** [comment]
`ColorSpectrum` is planned to be added as a primitive in support of https://github.com/AvaloniaUI/Avalonia/issues/4179. When that is done this can likely be closed.
