### ISSUE TITLE
Windows 10 - Chrome icons not visible using ExtendClientAreaToDecorationsHint

### ISSUE THREAD

**Issue by IceReaper** [AvaloniaUI/Avalonia#5745]
Just started to follow the tutorial: https://avaloniaui.net/docs/advanced-tutorial/create-a-modern-window
As soon as i add "ExtendClientAreaToDecorationsHint", it properly overlays the background on that part too. However the standard window buttons "minimize, maximize/restore, close" are not visible anymore. Clicking where they should be however works.
Either this is a bug, or needs a note on the tutorial, as its images imply the icons are visible.

**Comment by FrankenApps** [comment]
You also need to set 
```
ExtendClientAreaChromeHints="PreferSystemChrome"
```
I think this should be mentioned in the tutorial.

**Comment by chenjing1294** [comment]
> You also need to set.....

The problem is that the shadow around the window disappears, what if I make the shadow show and keep the top right button?
![1](https://user-images.githubusercontent.com/21185657/222933164-28f9eab2-2d51-4499-89f1-845ab8c3dbc1.PNG)

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/9989
