### ISSUE TITLE
TextBox.RaiseEvent -> unexpected NullReferenceException with TextBox.cs (0.10.0 Line 1052/1082)

### ISSUE THREAD

**Issue by postrondev** [AvaloniaUI/Avalonia#5752]
I need to implement a KeyPreview for e derieved TextBox.
I get the NullReferece Exception with Home and End Key
when i call _textBox.ReaiseEvent

despite the fact that document ist set to false, the debugger
enters the true path

`
        protected override void OnKeyDown(KeyEventArgs e)
        {
            e.Handled = SendKey(e);

            base.OnKeyDown(e);
        }

        private bool SendKey(KeyEventArgs e)
        {
            TextBox _textBox = new TextBox();

            _textBox.Text = Text;
            _textBox.SelectionStart = SelectionStart;
            _textBox.SelectionEnd = SelectionEnd;
            _textBox.CaretIndex = CaretIndex;

            KeyEventArgs _e = new KeyEventArgs();

            _e.Device = e.Device;
            _e.Key = e.Key;
            _e.KeyModifiers = e.KeyModifiers;
            _e.Route = e.Route;
            _e.RoutedEvent = e.RoutedEvent;
            _e.Source = _textBox;

            _textBox.RaiseEvent(_e);  //-> throws NullReferenceException  with Home/End Keys

            return KeyDownHandled(_textBox.Text);
        }

        private bool KeyDownHandled(string text)
        {
            bool _keyDownHandled = true;

            if (TryParse(text, out T value))
            {
                ValueObject = value;

                _keyDownHandled = false;
            }

            return _keyDownHandled;
        }

`

**Comment by postrondev** [comment]
issue closed.

use base.AddHandler(InputElement.KeyDownEvent....RoutingStrategies.Tunnel
instead of override OnKeyDown

**Comment by MikeCodesDotNET** [comment]
Can you confirm if this is still an issue with v11?
