### ISSUE TITLE
GridSplitter is stuck when resizing two * columns

### ISSUE THREAD

**Issue by HermanKirshin** [AvaloniaUI/Avalonia#5759]
**Describe the bug**
In some cases grid splitter between two Star-Width columns is either stuck and stops responding to dragging or immediately returns to previous position.

**To Reproduce**

Sample grid:

`
<Grid ColumnDefinitions="Auto,Auto,*,Auto,*,Auto,Auto">
      <Panel Grid.Column="0" Background="Red" />
      <Panel Grid.Column="2" Background="Green" />
      <Panel Grid.Column="4" Background="Blue" />
      <Panel Grid.Column="6" Background="Yellow" />
      <GridSplitter Width="5" Grid.Column="1" ></GridSplitter>
      <GridSplitter Width="5" Grid.Column="3" ></GridSplitter>
      <GridSplitter Width="5" Grid.Column="5" ></GridSplitter>
</Grid>
`

0. Move splitter between star columns - works ok
1. Resize some auto-or fixed width columns (probably multiple times, see attach)
2. Try to move splitter between star columns
3. Splitter is stuck

**Expected behavior**
Because here are no limitations on min/max widths, all splitters are expected to be always movable

**Screenshots**
![splitter_bug](https://user-images.githubusercontent.com/25755704/114324362-34b6d700-9b32-11eb-8406-4489a081bf39.gif)

**Desktop (please complete the following information):**

- OS: Windows 10 (150% scale, just in case)
- Version 0.10.0

**Additional context**
Splitter movement is cancelled here because MathUtilities.AreClose check is not passed:
![image](https://user-images.githubusercontent.com/25755704/114324429-95deaa80-9b32-11eb-9c27-10d32cd38f1e.png)

**Comment by grokys** [comment]
Thanks for reporting this. If you have time could you try the same repro in WPF? If I remember correctly, our `GridSplitter` is ported from there and indeed [that code](https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/GridSplitter.cs#L909) is present upstream.

**Comment by HermanKirshin** [comment]
Sure. Lokks like in WPF it works fine.
Updated code compatible with both frameworks:
`<Grid>
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="Auto" />
      <ColumnDefinition Width="Auto" />
      <ColumnDefinition Width="*" />
      <ColumnDefinition Width="Auto" />
      <ColumnDefinition Width="*" />
      <ColumnDefinition Width="Auto" />
      <ColumnDefinition Width="Auto" />
    </Grid.ColumnDefinitions>
    <StackPanel Grid.Column="0" Background="Red" />
    <StackPanel Grid.Column="2" Background="Green" />
    <StackPanel Grid.Column="4" Background="Blue" />
    <StackPanel Grid.Column="6" Background="Yellow" />
    <GridSplitter Width="5" ResizeBehavior="PreviousAndNext" Grid.Column="1" ></GridSplitter>
    <GridSplitter Width="5" ResizeBehavior="PreviousAndNext" Grid.Column="3" ></GridSplitter>
    <GridSplitter Width="5" ResizeBehavior="PreviousAndNext" Grid.Column="5" ></GridSplitter>
  </Grid>`
![splitter_bug_wpf](https://user-images.githubusercontent.com/25755704/114359759-f692d500-9b7c-11eb-817c-28102937fe70.gif)

**Comment by MarchingCube** [comment]
I remember seeing this a long time ago, looked like a problem with numeric precision. Are you using a screen with higher DPI?

**Comment by HermanKirshin** [comment]
Yes, it is 150% scale. Just checked - bug is not reproduced with 100% scale.

**Comment by MarchingCube** [comment]
@HermanKirshin Can you verify that https://github.com/AvaloniaUI/Avalonia/pull/5767 fixes your issue? I've tested it locally on my own 150% scale screen and it seems to work fine now.
