### ISSUE TITLE
Context menus are getting wrongly clipped and constrained

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#5766]
**Describe the bug**
On win32 context menus behave in mysterious ways and get clipped wrongly or get constrained despite having plenty of space.

**To Reproduce**

1. Open ControlCatalog
2. Go to "ContextMenu" page
3. Move window so "Dynamically Generated" area is outside of the right screen edge
4. Be amused by a completely clipped window
5. Move window so "Dynamically Generated" area is outside of the bottom screen edge
6. Be even more amused by a constrained context menu that can't be used at all

**Expected behavior**
Context menus should be usable even around screen edges

**Screenshots**

Right
![image](https://user-images.githubusercontent.com/2588062/114433379-0b458c00-9bc2-11eb-8810-49407b068885.png)

Bottom
![image](https://user-images.githubusercontent.com/2588062/114433457-244e3d00-9bc2-11eb-82ae-392d272e896f.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version: master

**Additional context**

**Comment by maxkatz6** [comment]
@MarchingCube is it only overlay popups issue? Might be related to https://github.com/AvaloniaUI/Avalonia/issues/5628

**Comment by MarchingCube** [comment]
Is control catalog using overlay popups by default?

**Comment by maxkatz6** [comment]
@MarchingCube overlay popups disabled by default.

Ok, I can reproduce this problem.
![image](https://user-images.githubusercontent.com/3163374/114473630-9fafee80-9bc2-11eb-9a0b-063073538abf.png)

For the second case taskbar should be automatically hidden. Depending on the place where user clicked right button, it could be weirdly cropped or not.
![image](https://user-images.githubusercontent.com/3163374/114473750-cbcb6f80-9bc2-11eb-8381-671fdbbb1833.png)
![image](https://user-images.githubusercontent.com/3163374/114473763-d128ba00-9bc2-11eb-83f9-ce39fe25d2da.png)

**Comment by maxkatz6** [comment]
@kekekeks for popup-positioning on the cursor position, was it supposed to work in the past?
It seems to work fine for any other popup position modes.

**Comment by kekekeks** [comment]
IIRC `Cursor` positioning mode just sets a tiny anchor rect. It shouldn't break popup sizing and it worked fine when popup positioner was initially introduced.

**Comment by MarchingCube** [comment]
Fixed in master.
