### ISSUE TITLE
[Proposal] Enhancements to WindowStartupLocation

### ISSUE THREAD

**Issue by ngarside** [AvaloniaUI/Avalonia#5782]
Looking for feedback if this would be wanted in Avalonia.

**Is your feature request related to a problem? Please describe.**

I need a way to open windows in the corner of the screen, with a margin separating them from the screen edge and taskbar.

**Describe the solution you'd like**

Extend [WindowStartupLocation](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/WindowStartupLocation.cs)

```
public enum WindowStartupLocation
{
	// Existing
	Manual,
	CenterScreen,
	CenterOwner,

	// New
	TopLeft,
	TopRight,
	BottomRight,
	BottomLeft,
}
```

For the screen edge margin, I'd piggyback off of `Layoutable.Margin` (which as far as I can tell isn't used by `Window` currently).

I'm not sure if/how it would work with owned windows, or if it even _should_ work with them.

**Describe alternatives you've considered**

I was planning to create a `Window` subclass for my own project, so if this is outside the scope of Avalonia itself then I'll just continue with that.

**Additional context**

This would likely have issues on wayland, although I haven't checked how `CenterScreen` works on wayland, so maybe it's no different.

**Comment by kekekeks** [comment]
For Wayland that feature won't work at all, so don't worry much about that.
