### ISSUE TITLE
Middle click doesn't work on macos

### ISSUE THREAD

**Issue by IngvarX** [AvaloniaUI/Avalonia#5784]
**Describe the bug**
Middle click doesn't work on Macos. It doesn't generate any events like left/right mouse buttons do

**To Reproduce**
Do middle click and try to catch mouse down/up/click events

**Expected behavior**
Middle click fires events like left/right click do

**Desktop (please complete the following information):**

- OS: Macos
- Version 0.10.0

**Comment by Mikolaytis** [comment]
We need this fix in our app. We will be grateful for 0.10.8 release with that fix
