### ISSUE TITLE
High CPU usage on Raspberry Pi

### ISSUE THREAD

**Issue by canton7** [AvaloniaUI/Avalonia#5785]
**Describe the bug**

A skeleton project (just the default project created by the VS extension, with a blank window) takes about 30% CPU usage on a Raspberry Pi 4.

Tested on net5.0 and netcoreapp3.1, Avalonia version 0.10.0 (the myget versions are failing to restore due to version mismatches).

I've attached a trace captured with `dotnet trace` which can be opened with PerfView [here: trace.zip](https://github.com/AvaloniaUI/Avalonia/files/6320943/trace.zip). A couple of screenshots below:

![image](https://user-images.githubusercontent.com/568104/114934555-ece5c780-9e31-11eb-8593-48ffa838004b.png)

![image](https://user-images.githubusercontent.com/568104/114934440-c7f15480-9e31-11eb-9856-e2096ffa8bed.png)

... it seems to be spending all of its time in unmanaged code, which `dotnet trace` isn't particularly good at picking up!

`strace` shows a lot of activity, a good chunk of it `cacheflush` calls. I've attached the first 1s of strace output [here: strace.txt](https://github.com/AvaloniaUI/Avalonia/files/6320971/strace.txt). 

**To Reproduce**

1. Use VS to create a new empty Avalonia project.
2. Run this on a Rapsberry Pi 4
3. Observe CPU usage

**Desktop (please complete the following information):**

- OS: Raspbian 10
- Version: 0.10.0

**Comment by kekekeks** [comment]
Unmanaged code from dispatcher run loop is `epoll_wait` (basically sleep).
Unmanaged code from `SleepLoopRenderTimer` is `Thread.Sleep`
I wonder why it spends so much time finalizing SkiaSharp's objects since we are disposing most of them except images

**Comment by canton7** [comment]
Thanks for responding so quickly!

How did you figure the CPU time was being spent in `epoll_wait`, rather than in one of the [other unmanaged calls](https://github.com/AvaloniaUI/Avalonia/blob/34c3f05ced2cb7befae192f5d69b82372abd91a9/src/Avalonia.X11/X11PlatformThreading.cs#L202-L247)? Naively, that `XFlush` call looks suspect, as it ties in with the millions of `cacheflush` syscalls being made.

Agreed on the `Thread.Sleep` being the only suspect call in `SleepLoopRenderTimer`, although on Linux at least there's a lot more managed code in the runtime inside `Thread.Sleep` before it hits managed code, which I might expect to show up in the graph.

**Comment by canton7** [comment]
Very naively, we got about 1300 `cacheflush` calls in a second from the strace log. Making the huge assumption that the majority of those come from `XFlush`, that that implies that `RunLoop` is spinning in the order of once every 1ms, which seems a little high.

**Comment by kekekeks** [comment]
Try removing `XFlush` and calling it from `DispatcherTimer.Run(() => ...)` once a second.

**Comment by canton7** [comment]
I'll have to get Avalonia building locally for that -- may take a while I'm afraid!

**Comment by canton7** [comment]
I suspect that `XFlush` stuff is more a symptom than a cause though -- should `MainLoop` be running once every 1ms?

**Comment by kekekeks** [comment]
Might be caused by animations system. It might be not stopping the timer when no animations are running.

@jmacato

**Comment by canton7** [comment]
I've managed to narrow it down to somewhere between 0.8.3 (which is fine) and 0.10.0-preview1 (which has the same issue). I haven't been able to test any versions in between due to a variety of compile-time and runtime errors.

**Comment by govert** [comment]
First I should say that having `dotnet new Avalonia.App` / `dotnet run` just work on the Raspberry Pi is wonderful - thank you!

I'm also seeing the high CPU usage for the default app on a Raspberry Pi 4 + Raspbian 10, while it's fine on Windows. My application is for a battery-powered device, so might be sensitive to the CPU spinning. 

So +1 for being able to reproduce this, and hoping for a fix or workaround.

**Comment by dlukach** [comment]
Would appreciate if this issue gets looked into more, the performance drop on RPI vs windows is very noticeable. I would revert to 0.8.3 but a lot of other stuff I use requires the latest Avalonia.

**Comment by grokys** [comment]
It might be useful if someone could do a git bisect between 0.8.3 and 0.10.0-preview1 (the known good and bad releases mentioned above) on a Pi to try to find the commit that started the problem. Not sure how easy that would be on a Pi itself...

**Comment by kekekeks** [comment]
It might have been caused by this https://github.com/AvaloniaUI/Avalonia/pull/6649

**Comment by aguahombre** [comment]
I'm seeing about 12% idle CPU usage on rPI3A using frame buffer not X11.
So #6649 may not be the only problem as #6649 looks like it is an X11 fix.

**Comment by dlukach** [comment]
I guess we need to see once 10.8 releases

**Comment by canton7** [comment]
Tested with 10.13, .NET 6. The problem is still there.

**Comment by canton7** [comment]
Oh! Having said that, a few deploys later and the CPU is down into the low single digits. I figure this is solved, thanks all!
