### ISSUE TITLE
Allow for getting pointer info when context menu is opening

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#5793]
**Is your feature request related to a problem? Please describe.**
Currently when context menu is being opened it is hard to tell where mouse cursor was when menu was opened. This is useful for contextual options where position matter. For example when you have a 2D canvas and you want your "Paste" option to paste underneath the cursor.

**Describe the solution you'd like**
WPF has a property in the event args: https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.contextmenueventargs.cursorleft?view=net-5.0#System_Windows_Controls_ContextMenuEventArgs_CursorLeft

Although cursor position might not be always available (menu key has been pressed) so it can be optional.
This feature should also work for flyouts (if it doesn't already).

**Describe alternatives you've considered**
Current workaround is to track mouse events separately and just cache it when context menu is opened. But it is tricky and needs quite some setup to function.

**Additional context**

**Comment by maxkatz6** [comment]
Can be done with ContextRequested event. 
With this event it's possible to customize context action having pointer position information.
