### ISSUE TITLE
TextBox Unicode (RTL) text issues

### ISSUE THREAD

**Issue by Zilkode** [AvaloniaUI/Avalonia#5794]
Avalonia.Controls.TextBox has few issues with Unicode text:

1. When using deafult font the text for RTL language the text is reversed. 
Example: for the text אבגד in Hebrew:
![image](https://user-images.githubusercontent.com/43464815/115221780-b13d4d00-a112-11eb-8d33-48af6259ea94.png)

2. Using a custom font such as "Roboto" the TextBox does not show the Unicode characters. example:
Example: for the text אבגד in Hebrew:
![image](https://user-images.githubusercontent.com/43464815/115222024-f5305200-a112-11eb-9a81-73927e6c5f2c.png)

The text is shown properly within TextBlock and all other controls (as far as i tested)
Version: 0.10.0
Environment: Windows 10

**Comment by maxkatz6** [comment]
Known
https://github.com/AvaloniaUI/Avalonia/issues/3777
https://github.com/AvaloniaUI/Avalonia/issues/4755
https://github.com/AvaloniaUI/Avalonia/issues/1809

**Comment by ghersa-mourad** [comment]
I want to work on this issue, can anyone show me what to do ( just hints), i started reading the code , i want to know how the DeferredDrawingContextImpl.DrawText works and what can be the real issue.

**Comment by danielmayost** [comment]
this issue can be closed, is it?
