### ISSUE TITLE
TextBox disable history (undo/redo)

### ISSUE THREAD

**Issue by RomanSoloweow** [AvaloniaUI/Avalonia#5795]
Often Undo - Redo is implemented at the application level, including changing text fields.

Therefore, we need the ability to turn off history.

**Comment by maxkatz6** [comment]
API reference
https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.textboxbase.isundoenabled
And probably
https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.textboxbase.undolimit
