### ISSUE TITLE
NativeControlHost Sizing

### ISSUE THREAD

**Issue by dmtomczyk** [AvaloniaUI/Avalonia#5796]
**Describe the bug**
A control (`LibVLCSharp.VideoView`) is not sizing properly on any platform: Windows, Ubuntu-x64, Ubuntu-ARM64. The control currently requires hard-coded sizing of `Height="400" Width="400"` in order to be visible, but even with that, it does not size properly. The auto-sizing, or lack thereof, is so bad that the control is not usable in any form. 

**To Reproduce**
Steps to reproduce the behavior (on windows):

1. Clone my sample repository from https://github.com/dmtomczyk/bravo-uniform-golf-001
2. Restore NuGet packages if necessary. 
3. Execute program with either Visual Studio or via .exe
4. Click "Start Videos" button and observe sizing of videos compared to the XAML in MainWindow.axaml

**Expected behavior**
A 2x3 grid of `VideoView` controls is visible, with no spacing in-between them, all auto-sizing to fill their respective container(s).

**Screenshots**
[sample_bug_image](https://user-images.githubusercontent.com/26173452/115253384-5566ca00-a0fa-11eb-82d5-d0c0f9fc43bc.png)

**Desktop (please complete the following information):**

- OS: Windows 10[1909], Ubuntu18.04-x64, Ubuntu18.04-ARM64

**Additional context**
From the discussions I've been having over at https://code.videolan.org/videolan/LibVLCSharp/-/issues/458, it might be an issue somewhere in or around `NativeControlHost`, which the `<VideoView/>` control is inheriting from.

**Comment by kekekeks** [comment]
Reproduced with plain `NativeControlHost` and default black XID.

**Comment by kekekeks** [comment]
As a workaround wrap each of your VideoViews into a Panel, e. g. instead of
```

```
use 
```
<Panel  Grid.Row="1" Grid.Column="0">
  <vlcSharp:VideoView x:Name="VideoView0"
          MediaPlayer="{Binding MediaPlayerZero, Mode=TwoWay}"
          IsVisible="True" />
</Panel>
```

See workaround branch here https://github.com/kekekeks/bravo-uniform-golf-001/tree/workaround

**Comment by dmtomczyk** [comment]
@kekekeks Thank you for squeezing this into 0.10.1 !

I've got the updates in my project and it's working as intended now.
