### ISSUE TITLE
How to pay for support

### ISSUE THREAD

**Issue by xizhengchao** [AvaloniaUI/Avalonia#5803]
Excuse me, where can I buy the service and how much is it

**Comment by dmtomczyk** [comment]
@xizhengchao , @ahopper replied on Gitter and posted the link to https://avaloniaui.net/support where you can contact the team to pay for support

**Comment by xizhengchao** [comment]
I've already sent an email, but I haven't replied

**Comment by grokys** [comment]
Apologies @xizhengchao - we've been busy this morning. Sent you an email.

**Comment by xizhengchao** [comment]
hello,How to pay
