### ISSUE TITLE
Third Party TypeConverter Registration

### ISSUE THREAD

**Issue by Seeker1437** [AvaloniaUI/Avalonia#581]
It would be nice to be able to register custom `TypeConverter`s in an external library. Right now it is not so easy.

**Comment by grokys** [comment]
We intend to move to .NET Standard soon which will give us access to the platform `TypeConverter`s.

**Comment by jkoritzinsky** [comment]
Is this handled by Portable.Xaml?

**Comment by jkoritzinsky** [comment]
I took a look at PortableXaml, and it looks like this is automatically handled if you put a `TypeConverterAttribute` on your type.
