### ISSUE TITLE
Make Custom Style Window

### ISSUE THREAD

**Issue by sekkit** [AvaloniaUI/Avalonia#5833]
Wanna make a Windows XP Luna Theme Style Window
Anyway to make round corner window & replace system chrome with XP Style?

**Comment by Splitwirez** [comment]
This is _possible_, yes...it's not entirely a built-in concept, but it absolutely can be done.

That said...are you sure you really should? Fully-custom decorations don't tend to be received as well by macOS and Linux users as by Windows users, so you may want to either think twice before doing this at all, or make it _optional_, so users of your program can enable or disable it as they see fit.

~~Side note: I am extremely curious about _why_ you're looking to do this..~~

**Comment by sekkit** [comment]
Im working on it.
Coz xp luna & win2k theme looked so classical. Just wanna reimpl it to nowadays OS.

**Comment by Gao996** [comment]
who have code， i also want make custom style window.hhhhh

**Comment by kekekeks** [comment]
See MetroWindow here: https://github.com/VitalElement/AvalonStudio.Shell/tree/master/src/AvalonStudio.Shell/Controls

**Comment by sekkit** [comment]
> See MetroWindow here: https://github.com/VitalElement/AvalonStudio.Shell/tree/master/src/AvalonStudio.Shell/Controls

great

**Comment by maxkatz6** [comment]
Answered

**Comment by Gao996** [comment]
Thanks!
