### ISSUE TITLE
CalendarDatePicker CalendarDatePicker Watermark property clears neither with "" nor null

### ISSUE THREAD

**Issue by postrondev** [AvaloniaUI/Avalonia#5835]
`  
  public class CalendarDatePickerTextBox : CalendarDatePicker, IStyleable
    {
        System.Type IStyleable.StyleKey { get { return typeof(CalendarDatePicker); } }

        public CalendarDatePickerTextBox()
        {
        }

        protected override void OnInitialized()
        {
            base.OnInitialized();

            Watermark = ""; // does not work
            Watermark = null; // does not work
            Watermark = " "; // works
        }
    }
`

**Comment by maxkatz6** [comment]
Let me know if it's still an issue
