### ISSUE TITLE
Handling KeyDown events does not prevent TextInput events

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#5849]
**Describe the bug**
In WPF when one handles `KeyDown` then `TextInput` event won't be received.
This is useful when handling single character shortcuts and avoiding weird side effects.
For example in my app user can rebind their shortcuts, one of such shortcuts focuses an input text box. When such letter shortcut is handled we will mark `KeyEventArgs` as handled and focus the text box. After text box gets focused it receives text input for the handled letter and immediately types something in it.

**Expected behavior**
I would expect WPF like behavior where handled `KeyDown` does not produce `TextInput`.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version: master

**Comment by postrondev** [comment]
The concept of handling e.Handled is complitly opposite to the "standard handling"
In all other keyboard event handlings i knows setting e.Handled = true means stop
handling this key here.
in avalonia e. Handled is used to tell you, that the key is already handled, so it does not
matters whatever you set in in you event handler. is is ignored. check TextBox.cs.

So what can you do.

Create an new "control" and set the style to "TextBox"

    public class MyTextBox : TextBox, IStyleable
    {
        System.Type IStyleable.StyleKey { get { return typeof(TextBox); } }

		//this is an excerpt of my own textbox control
        protected override void OnKeyDown(KeyEventArgs e)
        {
			if (any condition of your choice)
            {
                base.OnKeyDown(e); //the keydown event is passed th the avalonia engine
            }
			else
			{
				// handling should stop here
			}
	}

**Comment by maxkatz6** [comment]
> In all other keyboard event handlings i knows setting e.Handled = true means stop
handling this key here.
in avalonia e. Handled is used to tell you, that the key is already handled, so it does not
matters whatever you set in in you event handler. is is ignored. check TextBox.cs.

It's a bit more complicated. Setting "e.Handled" will prevent this specific event from being raised on next control in its route (see [EventRoute.cs#L163](https://github.com/AvaloniaUI/Avalonia/blob/6d819661efaddb74c520474c846e29c500937401/src/Avalonia.Interactivity/EventRoute.cs#L163)). But it won't prevent other handlers in the same route entry from being invoked (see [EventRoute.cs#L171](https://github.com/AvaloniaUI/Avalonia/blob/6d819661efaddb74c520474c846e29c500937401/src/Avalonia.Interactivity/EventRoute.cs#L171), it's just invokes whole delegate without checks before each handled). IIRC it has the same behavior as in WPF/UWP.

**Comment by maxkatz6** [comment]
In this specific issue, KeyboardDevice should check if KeyDown was previously handled for the same raw event:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Input/KeyboardDevice.cs#L196-L247

**Comment by kekekeks** [comment]
It's more complicated than that.
1) KeyboardDevice doesn't necessary have the required information to decide if the event should be ignored
2) Depending on the system text input might be decoupled from actual event presses. Sometimes the app won't see the key press at all

So we should return the "handled" state to the system when possible, but that kinda conflicts with dispatcher priorities.

**Comment by Jeremy-Price** [comment]
FYI: On Mac, setting e.Handled = true suppresses the text event as expected.

**Comment by grokys** [comment]
Looking into this a little more, as @Jeremy-Price says this is handled correctly on macOS - it seems that win32 simply always sends WM_CHAR even if WM_KEYDOWN is marked as handled. WPF has explicit "mitigation" for this in their `HwndSource`:

https://github.com/dotnet/wpf/blob/3ccd6f5545fbebf775262af446f2aff819a2226c/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndSource.cs#L1816-L1857

**Comment by grokys** [comment]
Ok, so it seems that the way to do this is to not call `TranslateMessage` if the `WM_KEYDOWN` is handled, however we have a problem: `TranslateMessage` is called _before_ the `DispatchMessage` which handles the `WM_KEYDOWN` so we don't know whether to call `TranslateMessage` or not.

Looks like WPF does this by first calling the `OnPreprocessMessage` method outside of the `WndProc`, which handles key down messages and returns the handled status.
