### ISSUE TITLE
Confuse `Expander`

### ISSUE THREAD

**Issue by soosr** [AvaloniaUI/Avalonia#5851]
**To Reproduce**

1. Go to an Expander
![image](https://user-images.githubusercontent.com/16364053/116661021-1c4d1600-a994-11eb-93ed-35842f8b2d1e.png)
2. Open it.
![image](https://user-images.githubusercontent.com/16364053/116661061-2a029b80-a994-11eb-9c7f-75f5639d65ac.png)
3. Double click on it.
![image](https://user-images.githubusercontent.com/16364053/116661111-3be43e80-a994-11eb-845a-c1e384bbf547.png)

Arrow says it is open, but not. Need to click twice to open it again.

**Comment by Deadpikle** [comment]
## The Problem

https://github.com/AvaloniaUI/Avalonia/blob/ef38e9dd3a25e513f449a51ef09508af65140841/src/Avalonia.Controls/Expander.cs#L86-L101

Basically, something is going on (or seems to be going on) where the double-click on the internal `Expander` `ToggleButton` is triggering the `ContentTransition` 2x (which makes sense), but starting a 2nd transition before the 1st one ends seems to cause the animations to get out of sync or something. (In other words, the 2nd animation never completes.)

The bug is not experienced with the `FluentTheme` by default as that one has no `ContentTransition` set by default. Setting this on your `Expander` replicates the bug in the `FluentTheme`:

```xml
<Expander.ContentTransition>
    <CrossFade Duration="00:00:00.25" />
</Expander.ContentTransition>
```

### The Workaround

`ContentTransition="{x:Null}"` on your `Expander`

### The Actual Fix

???

A second animation getting cued up is not being executed properly somehow. Ideally I think you'd cancel/stop the current animation and then set up a new one, but...I'm not sure how the animation system works fully.

**Comment by VisualMelon** [comment]
C&P of some stuff I wrote a while back when I looked into it:

> #5851 seems to be due to CrossFade clearing visibility at the end, but setting visibility at the start. It seems necessary to cancel the old fadeout/fadein when a new one is started; however, a mechanism to do this doesn't jump out at me (things like match and the subscription are not current exposed by RunAsync) and even if you can dispose the old animations, you still need to update the visibility after they have finished to avoid the short-term ill effect of things jumping in and out of visibility. The long-term ill effect (the content not presenting) can be resolved by updating the visibility after the animations complete (or during), but this doesn't feel like a good solution. Is anyone aware of another case like this from which I could pattern a solution?
> (Carousel has similar problems with short-term animation weirdness; it explicitly sets visibility at the end of the animation so the 'long term' effects don't appear to occur)

As I recall, It's not that they get out of sync, but the visibility is updated at the start of the fade-in and at the end of the fade-out.

I'm in the same boat as @Deadpikle : cancelling the fade-out before starting the fade-in would make the most sense, but there is no obvious mechanism for doing so.

**Comment by maxkatz6** [comment]
I did some experiment and while it's clear how to fix it in this specific case, it's not clear how to extend current API to support it nicely without hacks below:

```diff
diff --git a/samples/ControlCatalog/App.xaml.cs b/samples/ControlCatalog/App.xaml.cs
index f3ec7b48a..e5fad8884 100644
--- a/samples/ControlCatalog/App.xaml.cs
+++ b/samples/ControlCatalog/App.xaml.cs
@@ -89,7 +89,7 @@ public class App : Application
 
         public override void Initialize()
         {
-            Styles.Insert(0, FluentLight);
+            Styles.Insert(0, DefaultLight);
 
             AvaloniaXamlLoader.Load(this);
         }
diff --git a/src/Avalonia.Controls/Expander.cs b/src/Avalonia.Controls/Expander.cs
index 052b42a23..8b27a05bd 100644
--- a/src/Avalonia.Controls/Expander.cs
+++ b/src/Avalonia.Controls/Expander.cs
@@ -1,3 +1,5 @@
+using System;
+
 using Avalonia.Animation;
 using Avalonia.Controls.Metadata;
 using Avalonia.Controls.Primitives;
@@ -83,19 +85,21 @@ public bool IsExpanded
             }
         }
 
-        protected virtual void OnIsExpandedChanged(AvaloniaPropertyChangedEventArgs e)
+        IDisposable last;
+        protected virtual async void OnIsExpandedChanged(AvaloniaPropertyChangedEventArgs e)
         {
             if (Content != null && ContentTransition != null && Presenter is Visual visualContent)
             {
                 bool forward = ExpandDirection == ExpandDirection.Left ||
                                 ExpandDirection == ExpandDirection.Up;
+                last?.Dispose();
                 if (IsExpanded)
                 {
-                    ContentTransition.Start(null, visualContent, forward);
+                    last = ((CrossFade)ContentTransition).StartCancellable(null, visualContent);
                 }
                 else
                 {
-                    ContentTransition.Start(visualContent, null, !forward);
+                    last = ((CrossFade)ContentTransition).StartCancellable(visualContent, null);
                 }
             }
         }
diff --git a/src/Avalonia.Visuals/Animation/CrossFade.cs b/src/Avalonia.Visuals/Animation/CrossFade.cs
index 0615b854d..9153be002 100644
--- a/src/Avalonia.Visuals/Animation/CrossFade.cs
+++ b/src/Avalonia.Visuals/Animation/CrossFade.cs
@@ -1,5 +1,8 @@
 using System;
 using System.Collections.Generic;
+using System.Reactive.Disposables;
+using System.Reactive.Linq;
+using System.Threading;
 using System.Threading.Tasks;
 using Avalonia.Animation.Easings;
 using Avalonia.Styling;
@@ -109,38 +112,49 @@ public Easing FadeOutEasing
         /// <returns>
         /// A <see cref="Task"/> that tracks the progress of the animation.
         /// </returns>
-        public async Task Start(Visual from, Visual to)
+        public Task Start(Visual from, Visual to)
         {
-            var tasks = new List<Task>();
+            return Task.CompletedTask;// StartCancellable(from, to);
+        }
+        public IDisposable StartCancellable(Visual from, Visual to)
+        {
+            IDisposable opacityDisp = null;
+            CompositeDisposable disposables = new CompositeDisposable();
 
             if (to != null)
             {
-                to.Opacity = 0;
+                opacityDisp = to.SetValue(Visual.OpacityProperty, 0, Data.BindingPriority.Animation);
             }
 
             if (from != null)
             {
-                tasks.Add(_fadeOutAnimation.RunAsync(from));
+                IDisposable subscriptions = null;
+                subscriptions = _fadeOutAnimation.Apply(from, from.Clock, Observable.Return(true), () =>
+                {
+                    if (!disposables.IsDisposed)
+                    {
+                        disposables.Add(from.SetValue(Visual.IsVisibleProperty, false, Data.BindingPriority.Animation));
+                    }
+
+                    subscriptions?.Dispose();
+                });
+                disposables.Add(subscriptions);
             }
 
             if (to != null)
             {
-                to.IsVisible = true;
-                tasks.Add(_fadeInAnimation.RunAsync(to));
-
-            }
+                disposables.Add(to.SetValue(Visual.IsVisibleProperty, true, Data.BindingPriority.Animation));
 
-            await Task.WhenAll(tasks);
-
-            if (from != null)
-            {
-                from.IsVisible = false;
+                IDisposable subscriptions = null;
+                subscriptions = _fadeInAnimation.Apply(to, to.Clock, Observable.Return(true), () =>
+                {
+                    opacityDisp?.Dispose();
+                    subscriptions?.Dispose();
+                });
+                disposables.Add(subscriptions);
             }
 
-            if (to != null)
-            {
-                to.Opacity = 1;
-            }
+            return disposables;
         }
 
         /// <summary>

```

**Comment by maxkatz6** [comment]
Probably we can pass cancellation tokens to async methods (at least it makes sense anyway).
cc @jmacato
