### ISSUE TITLE
Window Heigth and Width properties are Nan on Linux in combination with  WindowState="FullScreen"

### ISSUE THREAD

**Issue by aadslingerland** [AvaloniaUI/Avalonia#5859]
**Describe the bug**
A simple Window defined in MainWindow.axaml with the option  WindowState="FullScreen" works well on Windows 10 and the properties this.Height and this.Width, as seen in  MainWindow.axaml.cs, have correct values. However, when running the same application on a Linux system (Ubuntu 20.04 in my case) the Window becomes fullscreen which is good but the values of the properties this.Height and this.Width are Nan.

**To Reproduce**
1. create a basic non mvvm avalonia application with the option WindowState="FullScreen" added and with the option Opened="OnOpened".
2. make a method in MainWindow.axaml.cs, public void OnOpened(object sender, EventArgs e).
3. add a few debug statements like: Debug.WriteLine("this.Height=" + this.Height); Debug.WriteLine("this.Width=" + this.Width);
4. set a breakpoint (I use Visual Studio 2019 pro).
5. inspect the values of this.Height and this.Width.

**Expected behavior**
Correct values for this.Height and this.Width

**Desktop (please complete the following information):**
Developing on Windows 10 Pro (up to date) with Visual Studio 2019 targeting .NET 5 and Avalonia Version="0.10.0"
Tested on Linux Ubuntu 2.,04 (no values for this.Height and this.Width)

[AvaCanvas2.zip](https://github.com/AvaloniaUI/Avalonia/files/6410846/AvaCanvas2.zip)

**Comment by kekekeks** [comment]
X11 is an asynchronous protocol, so resize event arrives way after than we've sent the open request. I'd suggest to override `ArrangeCore` if you want to get notified about resize events.

**Comment by grokys** [comment]
From your comment in gitter @aadslingerland I see you've solved your problem by subscribing to the `LayoutUpdated` event, so I will close this. Thanks!
