### ISSUE TITLE
WpfAvaloniaHost: WpfTopLevelImpl invalidates whole area on WpfTopLevelImpl.OnRender()

### ISSUE THREAD

**Issue by stepangovorko** [AvaloniaUI/Avalonia#5865]
**Describe the bug**
Check out two gifs:
1. ControlCatalog.Desktop sample
2. WindowsInteropTest sample (hosted in WPF)

(Visualize dirty rects was enabled in DevTools)

**Expected behavior**
Dirty rects visualization will be the same on both scnearios.

1.
![pure](https://user-images.githubusercontent.com/72131794/116852914-7a2c6880-abf5-11eb-94af-cfcd4d8b9ad4.gif)

2.
![wpf_host](https://user-images.githubusercontent.com/72131794/116852962-8ca6a200-abf5-11eb-9224-61ab69718d14.gif)

**Desktop:**

- OS: Windows
- Version: master

**Comment by kekekeks** [comment]
IIRC that's because it is using immediate renderer.

**Comment by stepangovorko** [comment]
@kekekeks Do you have an idea why Deffered renderer is not used here as well as in `WindowImpl`?
I tried to hardcode to use it in `WpfTopLevelImpl`, but it does not redraw the scene until the window is resized (renderer was Started)

my dirty changes in `WpfTopLevelImpl`:
![image](https://user-images.githubusercontent.com/72131794/116864551-53c3f880-ac08-11eb-81b6-e55455db1a8f.png)

**Comment by stepangovorko** [comment]
With this code I got it to work, but nevertheless it is unstable.
![image](https://user-images.githubusercontent.com/72131794/116868669-79083500-ac0f-11eb-89ed-3b9f27bdee22.png)

And you were right, visualizing dirty rects now shows as expected. But I also can see that the performance dropped dramatically.
I still have doubts that the deffered renderer can be used with WPF. @kekekeks how do you think, is it in theory possible or there can be some fundamental issues?

**Comment by maxkatz6** [comment]
@stepangovorko for WPF you can try this example with HwndHost https://github.com/maxkatz6/AvaloniaHwndHostSample

**Comment by kekekeks** [comment]
Which mode are you trying to use? HW-accelerated one or software rendering?

**Comment by kekekeks** [comment]
Actually, our Skia backend only supports software rendering for WPF integration.

DirectX interop with WPF is always hard for some reason since one needs to properly synchronize access to D3DImage's underyling texture and not spend too much time blocking.

Another problem is that ANGLE is not really thread safe (which is why we are trying to avoid rendering from UI thread when possible.

**Comment by stepangovorko** [comment]
@kekekeks 
I just realized that Direct2D is used in `WindowsInteropTest` by default. It is HW-accelerated, but bad performance is expected. With Skia performance issue is gone away. But `WpfAvaloniaHost `at the moment cannot be used with DefferedRenderer out of the box, because of `The calling thread cannot access this object because a different thread owns it` exception in several places in `WpfAvaloniaHost`. 

@maxkatz6 
Many thanks. It is interesting alternative to `WpfAvaloniaHost`. I see there are no such issues I descibed before and it works well with deffered renderer. I will try to use it instead of `WpfAvaloniaHost`.

**Comment by stepangovorko** [comment]
> Actually, our Skia backend only supports software rendering for WPF integration.
> 
> DirectX interop with WPF is always hard for some reason since one needs to properly synchronize access to D3DImage's underyling texture and not spend too much time blocking.
> 
> Another problem is that ANGLE is not really thread safe (which is why we are trying to avoid rendering from UI thread when possible.

Hmm. I used the solution by @maxkatz6 with Skia and AllowEglInitialization=true. From the first look it works.
Am I right that it just seems to me that it works, but in some cases there can be problems?
