### ISSUE TITLE
ICustomHitTest not working

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#5879]
**Describe the bug**
It seems that implementing `ICustomHitTest` on `Shape` doesn't have any effect. It _does_ work with the immediate renderer `UseDeferredRendering=false`) though.

**To Reproduce**

[shape_custom_hittesting_bug.patch.txt](https://github.com/AvaloniaUI/Avalonia/files/6434227/shape_custom_hittesting_bug.patch.txt)

**Expected behavior**
I would expect the custom hit testing to work.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: master

**Comment by grokys** [comment]
Yeah, `ICustomHitTest` [only works with the immediate renderer at the moment](https://github.com/AvaloniaUI/Avalonia/pull/1901). I do notice that WPF seems to allow customizing hit testing by overriding [`HitTestCore`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.visual.hittestcore?view=net-5.0) - it might be that we need to implement this in Avalonia (which it would make sense to do with `ICustomHitTest`).

**Comment by grokys** [comment]
Actually, ignore the above comment. It was implemented for the deferred renderer too in this commit: 

https://github.com/AvaloniaUI/Avalonia/commit/f0eafa70d0d7e8b066cf01cccfe5c6c85774ec20

However note the comment:

```
/// Note that this interface can only used to make a portion of a control non-hittable, it
/// cannot expand the hittable area of a control.

**Comment by mat1jaczyyy** [comment]
Centering the line in the window in this example breaks on immediate renderer, it incorrectly hit tests in the top left corner

**Comment by RomanSoloweow** [comment]
When using a non-shaded Rectangle as an Adorner, the method
https://github.com/AvaloniaUI/Avalonia/blob/7842883961d094e08e9def7f30cf32fd573179c7/src/Avalonia.Controls/Primitives/AdornerLayer.cs#L144
 returns true on the entire area, not just on the borders
