### ISSUE TITLE
windows build step

### ISSUE THREAD

**Issue by 1d8enchanted** [AvaloniaUI/Avalonia#588]
the text of docs/guidelines/build.md says: "The next step is to download the Skia native libraries. Run getnatives.ps1 PowerShell script which can be found under the folder src\Skia\.". There is no such file in src\Skia nor other folders in project.

**Comment by wieslawsoltes** [comment]
This step is not necessary as Avalonia has switched to `SkiaSharp` delivered via NuGet package and the scripts have been removed as no longer needed. The document needs to be updated.

**Comment by grokys** [comment]
Removed the outdated build step in 2a614326e3a2e86563e1a96e70df325401196338
