### ISSUE TITLE
Adorner size error 

### ISSUE THREAD

**Issue by RomanSoloweow** [AvaloniaUI/Avalonia#5880]
I want to do Adorner like this
![image](https://user-images.githubusercontent.com/29205560/117314634-a236f880-ae8f-11eb-99f2-5b0055981f27.png)

But I get this

![image](https://user-images.githubusercontent.com/29205560/117315739-a31c5a00-ae90-11eb-8320-f72877b4a13e.png)

```xaml
<Rectangle Stroke="#4d90ff" 
              StrokeThickness="1.5" 
              StrokeDashArray="3, 2"
              Margin="-5" />
```

**Comment by PieroCastillo** [comment]
I think the ClipToBounds property is true, try to change it at runtime

**Comment by RomanSoloweow** [comment]
It helped, thanks a lot!
