### ISSUE TITLE
DataGrid make cells blank after horizontal scroll with ImmediateRenderer

### ISSUE THREAD

**Issue by macpawluk** [AvaloniaUI/Avalonia#5907]
The issue occurs when `ImmediateRenderer` is being used. When the `DataGrid` has multiple columns and the content can be scrolled horizontally, cells' content disappear as user keeps on scrolling.

**Scenario to reproduce**
I've prepared minimal showcase application, available here: https://github.com/macpawluk/data-grid-immediate-renderer-bug
1. Launch the app
2. Try to scroll the `DataGrid` horizontally

Observe the content is disappearing even though these cells are still visible in the viewport.

**Expected behavior**
Cell's content should stay visible if they remain in the viewport.

**Screenshots**
![DataGridIssue](https://user-images.githubusercontent.com/17114116/117927782-fc561480-b2fa-11eb-82b1-6ba7ed920ade.gif)

![image](https://user-images.githubusercontent.com/17114116/117932394-95d3f500-b300-11eb-9135-5b75a2e752d0.png)

**Desktop**
- OS: Windows, Mac
- Version 0.10.4

**Additional context**
The issue occurs only when using `ImmediateRenderer` - it's important in my case as in the project we use it as a solution for visual glitches on Mac M1 machines.

**Comment by macpawluk** [comment]
I will leave here some more findings that I have on this (**+ workaround**):

I've temporarily switched off `DataGridFrozenGrid` (setting it to always off) and then I was able to observe an interesting situation while playing with the `DataGrid`:

![TooFastScroll](https://user-images.githubusercontent.com/17114116/117950959-fd477000-b313-11eb-9572-6bbe0c7ec29c.gif)

It looks like the rows are scrolled faster than the header. When I inspected `TransformedBounds` property, `M31` element of `Transform` changes exactly two times faster for `DataGridCell` than for `DataGridColumnHeader`. This leads to [this spot](https://github.com/AvaloniaUI/Avalonia/blob/eab18842f7e0a894720e7f1b1a423fe980adadf5/src/Avalonia.Visuals/Rendering/ImmediateRenderer.cs#L308) in the codebase.

**A temporary workaround** for this issue is applying this in app's styles:
```
    <Style Selector="DataGridCell">
        <Setter Property="ClipToBounds" Value="False" />
    </Style>

    <Style Selector="DataGridCell :is(Visual)">
        <Setter Property="ClipToBounds" Value="False" />
    </Style>
```

**Comment by macpawluk** [comment]
@maxkatz6 I've upgraded Avalonia packages to `0.10.18` and I can see the issue is still present. I've updated the show-case repo [here](https://github.com/macpawluk/data-grid-immediate-renderer-bug).

**Comment by maxkatz6** [comment]
@macpawluk fixed in the 11.0 previews.

**Comment by macpawluk** [comment]
@maxkatz6 unfortunately I can't quickly upgrade to the preview version. Are you aware of any patch I could apply to get this fixed? The workaround I gave earlier (`ClipToBounds` to `false`) makes the data grid too slow when there is lots of data, thus I can't really use it. I'd appreciate any hints.

**Comment by macpawluk** [comment]
Here is a workaround that can be used:
```
<Style Selector="DataGridCellsPresenter">
    <Setter Property="ClipToBounds" Value="True" />
</Style>
```

_credits to @donandren_
