### ISSUE TITLE
NullReferenceException when Item Selected in ListBox

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#591]
NullReferenceException "Object reference not set to an instance of an object."
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.ScrollIntoView(Int32 index) in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizerSimple.cs:line 482

Exception is raised only if the VirtualizingStackPanel has been measured with Size(0,0) and the panel.IsFull is always true. It's happening if the ListBox is in panel that's still not visible, but in the visual tree and SelectedItem is set, after the Items.

**Comment by donandren** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Presenters/ItemVirtualizerSimple.cs#L482
At this line if container is null NullReferenceException is raised:
```csharp
                var container = generator.ContainerFromIndex(index);
....
                if (layoutManager != null)
                {
                    layoutManager.ExecuteLayoutPass();

                    if (!new Rect(panel.Bounds.Size).Contains(container.Bounds))
                    {
                        OffsetValue += 1;
                    }
                }
```

**Comment by danwalmsley** [comment]
This is probably related to #598
