### ISSUE TITLE
Add tests/samples for F#

### ISSUE THREAD

**Issue by jschiefer** [AvaloniaUI/Avalonia#593]
How does the Avalonia community feel about support for F#? While F# is not typically used for UI development, it would sure be nice to have a capable cross-platform environment that makes it possible. A very quick conversion of the XamlTestApplication into F# didn't reveal any obvious showstoppers, but there will probably be some issues lurking. For example, shared projects in F# are only supported in Xamarin Studio 6, not on any of the other platforms. 

For reference, problems with the F#/WPF combination include:
- There is no support for partial classes in F#, so there is no code-behind
- There is no obvious mapping of WPF events into F# native events. 
- Similarly, using F# Observables for data bindings doesn't work out of the box. 

I would very much like to see this work, and I would be happy to contribute. But first I'd like to understand how y'all feel about this, and what might be the best way to organize this. Add samples and tests in the form of F# projects? This would create a dependency on the F# compiler, which might not be desirable. Or a separate independent project, maybe?

**Comment by grokys** [comment]
I would love to support F# though I've not had much experience of using it so far. Regarding the issues you mentioned:

- We don't yet have a XAML compiler so we don't use partial classes right now
- So F# doesn't support the C# `event EventHandler Foo` events?
- We use Rx observables for data bindings. Are F# observables easily convertible to these?

As for samples etc - I think the best way to go about that would be to start creating samples in a separate repository and then we can talk about putting some of them in the main repository when we've ironed out any problems.

**Comment by jschiefer** [comment]
F# does support "regular" events (e.g. though lambdas), it is just not very idiomatic. F# observables do implement IObservable<T>, so this all should fit together very nicely. 

I will create a repository and start hacking at this. Do you want me to use this issue here to report on progress and issues?

**Comment by grokys** [comment]
Please do report back here, yes - thanks, and good luck!

**Comment by jschiefer** [comment]
I made a repository [jschiefer/Avalonia.FSharpSamples](https://github.com/jschiefer/Avalonia.FSharpSamples), which is a submodule in the fsharp-samples branch in my clone of this repo. Just in case anybody wants to play along at home :smile:

**Comment by grokys** [comment]
Closing this as you've created the samples!
