### ISSUE TITLE
TextBlock show nonASCII character will mojibake.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [AvaloniaUI/Avalonia#5930]
**Describe the bug**
TextBlock use nonASCII character will mojibake.

**To Reproduce**

1. Set TextBlock.Text contain nonASCII character.

**Expected behavior**
It sould be show correct character, not messy code.

**Screenshots**
![图片](https://user-images.githubusercontent.com/10345361/118395557-a2987600-b67d-11eb-9f63-fed9d085975c.png)

**Desktop (please complete the following information):**

- OS: Windows10
- Version 21H1(19043.985)

**Additional context**
None.

**Comment by Gillibald** [comment]
Can you paste the actual text here?

**Comment by MiyamuraMiyako** [comment]
@Gillibald same as window title: "注意".

**Comment by Gillibald** [comment]
![Screenshot 2021-05-16 134444](https://user-images.githubusercontent.com/5928797/118395859-e6bf5280-b64c-11eb-8356-5835d56cc6ca.png)

Works in current master

**Comment by MiyamuraMiyako** [comment]
Thank you,  I tested and known issue from `MessageBox.Avalonia` lib.
