### ISSUE TITLE
ICustomDrawOperation ignores parent background

### ISSUE THREAD

**Issue by beto-rodriguez** [AvaloniaUI/Avalonia#5932]
**Describe the bug**
When a control implements `ICustomDrawOperation` and the canvas is cleared using a color with an alpha channel, the parent background is lost.

**To Reproduce**

1. Create a new window with a background that allows transparency.

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="using:AvaloniaApplication3"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication3.MainWindow"
        Title="AvaloniaApplication3"
        Background="#c0fafafa"
        Padding="100"
        ExtendClientAreaToDecorationsHint="True"
        TransparencyLevelHint="Blur">
  <local:UserControl1></local:UserControl1>
</Window>
```

2. create a `UserControl` that overrides the `Render` method with an `ICustomDrawOperation` instance, for example  the following `UserControl1` class.

``` c#
public partial class UserControl1 : UserControl
    {
        // ... skipped code

        public override void Render(DrawingContext context)
        {
            var drawOperation = new CustomDrawOp(new Rect(0, 0, Bounds.Width, Bounds.Height));
            context.Custom(drawOperation);
        }

        private class CustomDrawOp : ICustomDrawOperation
        {
            public CustomDrawOp(Rect bounds)
            {
                Bounds = bounds;
            }

            public void Dispose() { }

            public Rect Bounds { get; }

            public bool HitTest(Point p)
            {
                return false;
            }

            public bool Equals(ICustomDrawOperation? other)
            {
                return false;
            }

            public void Render(IDrawingContextImpl context)
            {
                if (context is not ISkiaDrawingContextImpl skiaContext)
                    throw new Exception("SkiaSharp is not supported.");

                using (var p = new SKPaint())
                {
                    p.Color = SKColors.Blue;
                    p.StrokeWidth = 5;
                    p.Style = SKPaintStyle.Stroke;

                    skiaContext.SkCanvas.Clear(SKColors.Transparent); // <-- 
                    skiaContext.SkCanvas.DrawLine(0, 0, 100, 100, p);
                }
            }
        }
    }
```

3. see the issue.

**Expected behavior**
I would expect to see the parent control background.

**Screenshots**
![image](https://user-images.githubusercontent.com/10853349/118406629-351b2400-b642-11eb-84a7-9d0caf74e229.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.4

**Additional context**
You can find more information at: https://github.com/beto-rodriguez/LiveCharts2/issues/36#issuecomment-835780162

**Comment by Gillibald** [comment]
By using a custom drawing operations you get access to the underlying surface that is being used as the window's render target. Clearing the render target results in a loss of the current state. So this is expected. Instead create your own surface and blend the final result into the window's tender target.

**Comment by beto-rodriguez** [comment]
Ok, I see thanks.

For my case it works only removing the `Clear` call.
