### ISSUE TITLE
Avalonia.Win32 is blocked as a "virus" [RESOLVED]

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#5937]
**Describe the bug**

Some of my users are getting this exception on startup:

```
System.IO.FileLoadException: Could not load file or 
assembly 'Avalonia.Win32, Version=0.10.3.0, Culture=neutral, 
PublicKeyToken=c8d484a7012f9a8b'. Operation did not complete successfully 
because the file contains a virus or potentially unwanted software. 
(0x800700E1)

     at 
Avalonia.AppBuilderDesktopExtensions.LoadWin32[TAppBuilder](TAppBuilder 
builder)
    at 
Avalonia.AppBuilderDesktopExtensions.UsePlatformDetect[TAppBuilder](TAppBuilder 
builder) in /_/src/Avalonia.Desktop/AppBuilderDesktopExtensions.cs:line 23
    at Bulk_Edit_Calendar_Events_WPF.Program.BuildAvaloniaApp() in 
C:\Users\derek\source\repos\Bulk Edit Calendar Events\Code\Bulk Edit 
Calendar Events_WPF\Program.cs:line 54
    at Bulk_Edit_Calendar_Events_WPF.Program.Main(String[] args) in 
C:\Users\derek\source\repos\Bulk Edit Calendar Events\Code\Bulk Edit 
Calendar Events_WPF\Program.cs:line 26
```

This is coming from the:

```csharp
public static AppBuilder BuildAvaloniaApp()
	=> AppBuilder.Configure<App>()
		.UsePlatformDetect()
		.LogToTrace()
		.With(new AvaloniaNativePlatformOptions { UseGpu = false });
```

Since the exception message contains the "virus" warning, I think this is Windows Defender (as opposed to some 3rd party virus software). Are there changes that can be made to Avalonia.Win32 to make it "ok" for Windows Defender? This seems like a big issue if Windows Defender is going to start blocking all Avalonia applications.

**Desktop (please complete the following information):**

Here's what I know about what the user has set up:

- OS: Windows 10 Home & Windows 10 Pro
- Version 0.10.3

**Comment by derekantrican** [comment]
Slightly different exception (different assembly & stacktrace), but still "virus" message:

```
System.IO.FileLoadException: Could not load file or 
assembly 'Avalonia.Themes.Default, Culture=neutral, PublicKeyToken=null'. 
Operation did not complete successfully because the file contains a virus 
or potentially unwanted software. (0x800700E1)

    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String 
codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, 
Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
    at 
System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName 
assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext 
assemblyLoadContext)
    at System.Reflection.Assembly.Load(String assemblyString)
    at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(String name) 
in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 243
    at Avalonia.Shared.PlatformSupport.AssetLoader.GetResAsmAndPath(Uri uri) 
in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 192
    at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri) in 
/_/src/Shared/PlatformSupport/AssetLoader.cs:line 203
    at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri, Uri 
baseUri) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 101
    at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in 
/_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 50
    at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in 
/_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 54
    at 
Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost 
owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
    at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) 
in /_/src/Avalonia.Styling/Styling/Styles.cs:line 292
    at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, 
NotifyCollectionChangedEventArgs e) in 
/_/src/Avalonia.Styling/Styling/Styles.cs:line 318
    at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in 
/_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 683
    at Avalonia.Collections.AvaloniaList`1.Add(T item) in 
/_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 206
    at Avalonia.Styling.Styles.Add(IStyle item) in 
/_/src/Avalonia.Styling/Styling/Styles.cs:line 201
    at Bulk_Edit_Calendar_Events_WPF.App.!XamlIlPopulate(IServiceProvider , 
App ) in C:\Users\derek\source\repos\Bulk Edit Calendar Events\Code\Bulk 
Edit Calendar Events_WPF\Windows/App.axaml:line 7
    at Bulk_Edit_Calendar_Events_WPF.App.!XamlIlPopulateTrampoline(App )
    at Bulk_Edit_Calendar_Events_WPF.App.Initialize() in 
C:\Users\derek\source\repos\Bulk Edit Calendar Events\Code\Bulk Edit 
Calendar Events_WPF\Windows\App.axaml.cs:line 19
    at Avalonia.Controls.AppBuilderBase`1.Setup() in 
/_/src/Avalonia.Controls/AppBuilderBase.cs:line 311
    at 
Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime 
lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 180
    at 
Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T 
builder, String[] args, ShutdownMode shutdownMode) in 
/_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 
148
    at Bulk_Edit_Calendar_Events_WPF.Program.Main(String[] args) in 
C:\Users\derek\source\repos\Bulk Edit Calendar Events\Code\Bulk Edit 
Calendar Events_WPF\Program.cs:line 26
```

**Comment by rstm-sf** [comment]
Perhaps this answer will help us somehow? https://stackoverflow.com/a/62933413

**Comment by derekantrican** [comment]
Per https://gitter.im/AvaloniaUI/Avalonia?at=60a2be03c12aec4aa2cf0f21:

> ok initial assessment seems that 0.10.3 is flagged because some blob in the binary maybe matches something in defenders database.
> switching to 0.10.4 will resolve this

**Comment by derekantrican** [comment]
@danwalmsley Just an update that I've seen this across 5 different users today. Since it prevents the application from opening, they won't get any prompt for a fix. Can the 0.10.3 binaries be submitted to https://www.microsoft.com/en-us/wdsi/filesubmission (or whatever the right endpoint is) to resolve this?

**Comment by derekantrican** [comment]
Relevant image from one of my users:

![image](https://user-images.githubusercontent.com/1558019/118566150-4e969b80-b728-11eb-9990-97f809d7e964.png)

**Comment by derekantrican** [comment]
I submitted the files to Microsoft Security. Avalonia.Themes.Default.dll has been removed from misidentification and should be available in the next Windows Defender definition.

Avalonia.Win32.dll is still pending (they could not repro so I added a dump of support files from Windows Defender)

**Comment by derekantrican** [comment]
According to the Microsoft Security team, both files should be clean. Refer to above instructions for downloading the new definition (once it becomes available).

> We have checked the provided logs and found that below file is getting detected.
> SHA1 : EE2A5DC14B1DA3449B4E3624BBEB81EFD83C538C
> File path: C:\Users\derek\source\repos\Bulk Edit Calendar Events\Code\Bulk Edit Calendar Events_WPF\bin\Debug\netcoreapp3.1\Avalonia.Win32.dll
> The file was marked as clean and it will supress the detection.
> We also found the below hash of sample in the submitted logs.
> SHA1 : f21d9a6800b8dffa8ae43a27d41e460232adae89 also clean, determined accordingly.

Please comment on this thread if you find another file besides Avalonia.Win32.dll & Avalonia.Themes.Default.dll that is being flagged and I will submit it to the Microsoft Security team.

**Comment by grayfallstown** [comment]
> > switching to 0.10.4 will resolve this

Facing this with 0.10.4 as well.

**Comment by derekantrican** [comment]
@grayfallstown which assembly? Avalonia.Win32.dll?

**Comment by grayfallstown** [comment]
> @grayfallstown which assembly? Avalonia.Win32.dll?

Win32, Dialog, Desktop

**Comment by derekantrican** [comment]
@grayfallstown I'm not seeing the same issues. Can you submit (or have your users submit) a cab file generated by the following instructions:

1. Open cmd as admin
2. Run `cmd "%ProgramFiles%\Windows Defender"
3. Run `mpcmdrun -GetFiles`
4. Upload resulting cab file to https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by grayfallstown** [comment]
@derekantrican submitted the dll files individually. Did not get the results of all of the submissions yet, but users report that Windows Defender is no longer reporting the files as Trojans as long as they update their Dynamic Signatures.

**Comment by derekantrican** [comment]
Good to hear! It's possible that they were seeing some cached results from the 0.10.3 false positives that also matched 0.10.4

**Comment by grayfallstown** [comment]
@derekantrican From what I've witnessed no.

I've updated to 0.10.4 and got no more warnings. Then I updated my Dynamic Signatures. Again no warning. Released a new Version with 0.10.4. Users reported that they get no more warnings. Most likely they did not update their signatures, at least not all of them as I never told them to.

Only about 4 hours later I got new reports about it being flagged as a Trojan. Again Avalonia.Win32.dll, but this time also Avalonia.Dialog.dll and Avalonia.Desktop.dll and as a different Trojan: Trojan:Win32/Sabsik.FT.A!ml vs Trojan:Win32/Emali.A!cl on 0.10.3.

**Comment by derekantrican** [comment]
Gotcha. Well, that sucks. I haven't heard anything from users about 0.10.4 yet (course I have a less-active community and people may not have gotten the 0.10.4 changes yet). Also don't see any issues with 0.10.4 locally where I did with 0.10.3.

If Microsoft Security can't repro the issue with your dlls, they'll want that cab file. The cab file will have the history of scans and their hashes. So if you can get that from your users, it would be ideal for Microsoft

**Comment by derekantrican** [comment]
This issue is **FIXED** (see above comments on how Microsoft Security has cleared the files and how your users can fix their Defender cache). However, since more people might continue hitting this, I'm going to reopen it for easier visibility (probably can be closed in a few days).

**Comment by derekantrican** [comment]
Since I haven't seen this on my side for a while, I'm going to mark this as "closed" again. I have plenty of users who have opened my application without issue since this was discovered so I imagine most computers have automatically updated their Defender definition to include the fixes

**Comment by DrewNaylor** [comment]
Hopefully this is the right place to put this: Apparently Windows Defender thinks Avalonia.Win32 from v0.10.5 is a trojan again and it deleted the DLL from the NuGet packages directory.

**Comment by derekantrican** [comment]
@DrewNaylor https://github.com/AvaloniaUI/Avalonia/issues/5937#issuecomment-843243410

**Comment by DrewNaylor** [comment]
I'll try that later today. Tried going to the submission page earlier and it gave me a 404 when trying to use it. Maybe it's Firefox, so I'll use Edge instead.

**Comment by grayfallstown** [comment]
Avalonia.Win32.dll and Avalonia.Themes.Fluent.dll flagged as Trojan:Win32/Emali.A!cl by Windows Defender on my and my users systems with virus definition 1.339.1937.0 (latest).
Both files submitted to microsoft for manual analysis.

**Comment by Thowil** [comment]
Please note that Avalonia.Controls.DataGrid.dll is affected as well for me (flagged Trojan:Win32/Emali.A!cl with 1.339.1950.0)

**Comment by costantin324** [comment]
windows defender is at it again, i got the exact same message

**Comment by grayfallstown** [comment]
Submission details
avalonia.win32.dll
Submission ID: 91833e65-8d89-4c11-8960-8e1a0c501c19
Status: Completed
Submitted: Jun 3, 2021 12:20:18
User Opinion: Incorrect detection
Analyst comments:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"



Did not receive the results for Avalonia.Themes.Fluent.dll yet, but it is no longer flagged on my system or VirusTotal.
Avalonia.Controls.DataGrid.dll however is
