### ISSUE TITLE
Hit testing/Visual Bounds not correct for Not Rendered Child descendants in ScrollViewer

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#594]
Hit testing/Visual Bounds not correct for Not Rendered Child descendants in ScrollViewer.
Probably hit testing/bounds are invalid for items that are not rendered during the render cycle.
That is causing issues, as the hit testing is forwarded to controls that are not visible, and the real visible controls are not receiving mouse clicks.

**Comment by donandren** [comment]
In the  branch
#https://github.com/donandren/Avalonia/commit/b5d2e8a681fc0508a827cb7b3d9865d464bbbf7c
easy reproduction can be found wiht folowing steps:

- Start XamlTestApplication

- Select tab Hit Test/ Visual Bounds bug 

- Expand Tree View 'Node 1'

- Click on 'Child 1' - 'Node 2' will be selected instead ''
Child 1

**Comment by donandren** [comment]
![image](https://cloud.githubusercontent.com/assets/13854631/16871167/06c74c70-4a8e-11e6-90de-dbe808b13202.png)

Visualization  of the bug from DevTools

**Comment by jkoritzinsky** [comment]
@donandren For elements that are out of bounds/not rendered, do we need to track their current location or would just making sure that the hit testing bounds for non-rendered elements don't interfere with rendered elements work for you?

**Comment by donandren** [comment]
@jkoritzinsky just to make sure the not visible/not rendered elements are not part of the result of hit testing should be enough for me. No need to track their current location, as they are not in the visible part.

**Comment by grokys** [comment]
Fixed by #626
