### ISSUE TITLE
DataGrid - Selecting Rows / Items not possible

### ISSUE THREAD

**Issue by Konamalunu** [AvaloniaUI/Avalonia#5941]
Hi :)
I am trying to switch from a ListBox to DataGrid solely for visual reasons.
The ListBox behaved like it should, but I like to have evenly placed columns etc.
Also the sorting is very welcome (which I could also implement for a ListBox, but here it is for "free).

**Describe the bug**
Rows are not selectable at all - I am not even talking about the bindings. 
There is also no hover effect or anything similar, if there should be one. 
I tried to bind the items to ObservableCollection and DataGridCollectionView.
Also created a new Repo, but the bug still exists.

**To Reproduce**
Code is placed only in a MainWindow. No other controls are existing or could interfere. 

View:
``` C#
  <Grid ColumnDefinitions="*,*">
    <DataGrid Items="{Binding DataGridCollectionView}" 
              SelectedItem="{Binding SelectedTestItem}" 
              AutoGenerateColumns="True" 
              SelectionMode="Single" />
    
    <TextBlock Background="AliceBlue" Grid.Column="1" Text="{Binding SelectedTestItem.Value}" />
  </Grid>
```

ViewModel:
```C#
public class Test
{
    public string Key { get; set; }
    public string Value { get; set; }
}

public class MainWindowViewModel : ViewModelBase
{
    private Test _SelectedTestItem;

    public DataGridCollectionView DataGridCollectionView { get; set; }
    public Test SelectedTestItem
    {
        get => _SelectedTestItem;
        set => this.RaiseAndSetIfChanged(ref _SelectedTestItem, value);
    }

    public MainWindowViewModel()
    {
        var list = new List<Test>
        {
            new Test { Key = "Test", Value = "Very testlike" },
            new Test { Key = "Hey!", Value = "La la la" },
            new Test { Key = "Hey!", Value = "What is a bleeb?" },
        };

        DataGridCollectionView = new DataGridCollectionView(list);
    }
}
```

**Expected behavior**
Rows should be selected after a click and that should be visually recognizable (other background color something else).

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5621969/118689949-d99a9300-b807-11eb-9e49-8d73d32ce529.png)
(on the right side is a textbox which is showing no text, because nothing is selected on the left side)

**Desktop**
- OS: Windows 10
- Version: 20H2

**Comment by Deadpikle** [comment]
Unless this is a more recent version of Avalonia off `master`, to bind `SelectedItem` in the way you want to, you'll need to also use `Mode=TwoWay`:

`SelectedItem="{Binding SelectedTestItem, Mode=TwoWay}" `

Make sure you also have this (or similar) in your `App.xaml`:

`<StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Default.xaml"/>`

**Comment by Konamalunu** [comment]
> 
> 
> Unless this is a more recent version of Avalonia off `master`, to bind `SelectedItem` in the way you want to, you'll need to also use `Mode=TwoWay`:
> 
> `SelectedItem="{Binding SelectedTestItem, Mode=TwoWay}" `
> 
> Make sure you also have this (or similar) in your `App.xaml`:
> 
> `<StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Default.xaml"/>`
> 
> [See also the docs page](https://docs.avaloniaui.net/docs/controls/datagrid)

Ok, thank you very much. Two way binding actually solved it for me. In some videos I also saw some visual feedback on what row is selected. Do I need to write a style  for that or am I missing something?

Also: 
- The ListBox does not need to have Mode=TwoWay. That makes it really confusing. 
- Unless I have a more recent version than master? Does that mean that it is already fixed in future versions?

**Comment by maxkatz6** [comment]
Yes
https://github.com/AvaloniaUI/Avalonia/pull/5931
