### ISSUE TITLE
StackPanel doesn't trigger PointerPressed / PointerReleased events

### ISSUE THREAD

**Issue by Nickelony** [AvaloniaUI/Avalonia#5942]
**Describe the bug:**
StackPanels don't call PointerPressed / PointerReleased event methods.

**To reproduce:**

1. Create a StackPanel
2. Assign PointerPressed / PointerReleased events
3. Click anywhere on the StackPanel
4. Nothing happens

**Expected behavior:**
The assigned event methods should be executed.

**Desktop:**

- OS: Windows
- Version: 10

**Comment by maxkatz6** [comment]
You need to set ```Background="Transparent"``` on the stack panel.
Without it's not hit testable.

**Comment by Nickelony** [comment]
> You need to set `Background="Transparent"` on the stack panel.
> Without it's not hit testable.

Oh... Didn't know that. I guess that's solved then. :)
