### ISSUE TITLE
Button and ToggleButton doesn't fire the PointerPress when using Left mouse click

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#5952]
**Describe the bug**
Don't know if is intended or not, but seens like an bug, even if a button have it default behaviour of clicking it, it should let us cath this event to process the way we want, for example, detect a click before release the button.
Maybe this is also present on other button events and other controls? So far i found this on `Button` and `ToggleButton`
To overcome this now i'm using the `PointerMoved` but it require at least 1px mouse mouse to get cath while check for `IsLeftButtonPressed`, which seens broken as user prespective

**To Reproduce**
```C#
var btn = this.FindControl<Button>("PasswordRevealBtn");
btn.PointerPressed += (sender, e) =>
{
    Debug.WriteLine("This only happens when clicking with other than left click button");
};
```

**Expected behavior**
PointerPressed to work with left button as it work with other mouse buttons.

**Desktop (please complete the following information):**

- OS: Windows v20H2
- Version 0.10.4

**Comment by maxkatz6** [comment]
See
https://github.com/AvaloniaUI/Avalonia/issues/5244#issuecomment-753239690

**Comment by sn4k3** [comment]
Thanks that worked as expected now!
