### ISSUE TITLE
FileSaveDialog bad behaviour when changing extension type for files with dots on name

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#5954]
**Describe the bug**
When having a default or typed filename containing dots, example: "treefrog_45_cut_0.05mm_1h20m.ctb.heatmap.png" and if we select another extension type from dropdown, it will strip the .jpg but not append the new extension, if we return back to png the extension is set. However if we select another extension then select another and get back to the previous, we get the extension set. Please see the attached GIF: https://i.imgur.com/VD4SmHq.gif
This don't happen when file is clean without the extra dots

**Code**

```C#
public static readonly List<FileDialogFilter> ImagesFullFileFilter = new()
{
    new()
    {
        Name = "PNG Files",
        Extensions = new List<string>
        {
            "png"
        }
    },
    new()
    {
        Name = "JPG Files",
        Extensions = new List<string>
        {
            "jpg",
            "jpeg"
        }
    },
    new()
    {
        Name = "BMP Files",
        Extensions = new List<string>
        {
            "bmp",
        }
    },
    new()
    {
        Name = "TIF Files",
        Extensions = new List<string>
        {
            "tif",
            "tiff",
        }
    },
};

var dialog = new SaveFileDialog
{
    Filters = Helpers.ImagesFullFileFilter,
    InitialFileName = Path.GetFileName(SlicerFile.FileFullPath) + ".heatmap.png",
    Directory = Path.GetDirectoryName(SlicerFile.FileFullPath),
};
var file = await dialog.ShowAsync(ParentWindow);
```

**Expected behavior**
When change extension, trim the last extension on filename and append the selected one

**Desktop (please complete the following information):**

- OS: Windows 10 v20H2
- Version 0.10.5

**Comment by puppetsw** [comment]
I found this issue to be reproduceable outside of Avalonia using MS Word SaveDialog. Appears to be a Windows dialog issue?

![Dialog](https://user-images.githubusercontent.com/79826944/119808280-20cd0600-bf23-11eb-9233-977410807413.gif)

**Comment by sn4k3** [comment]
Most likely, avalonia seens to use windows dialog.
Close this if you fell not related to Avalonia
