### ISSUE TITLE
Binding Error.

### ISSUE THREAD

**Issue by Gao996** [AvaloniaUI/Avalonia#5960]
![捕获](![捕获](https://user-images.githubusercontent.com/51224634/119089578-f7047280-ba3c-11eb-9831-a7044c038c72.PNG)
![1](https://user-images.githubusercontent.com/51224634/119089622-071c5200-ba3d-11eb-8b0e-189f275273b9.PNG)
)
System.MissingMemberException:Could not fin a matching property accessor for '' on 'AvaloniaChatRoomServer,ViewModels.MainWindowViewModel'

**Comment by maxkatz6** [comment]
It should be a property, not a field.
```
public string Hello { get; } = "Hello World!";
```

**Comment by Gao996** [comment]
ok thanks!
![fsd](https://user-images.githubusercontent.com/51224634/119280942-3b268b80-bc66-11eb-83ef-f44349f44277.PNG)
