### ISSUE TITLE
Switching FluentTheme from Light to Dark breaks some controls

### ISSUE THREAD

**Issue by RolandKoenig** [AvaloniaUI/Avalonia#5964]
**Describe the bug**
An InvalidOperationException "The control already has a visual parent" when clicking on the menu item after switching from Light to Dark FluentTheme.
I switch themes like discussed here #2824
I create to instances of FluentThemen in application resources and override the previous active Theme like this:

Application.axaml.cs:
```csharp
public override void OnFrameworkInitializationCompleted()
{
    _resThemeLight = (FluentTheme)this.Resources["ResThemeLight"]!;
    _resThemeDark = (FluentTheme) this.Resources["ResThemeDark"]!;
    this.Styles.Insert(0, _resThemeLight);
    
    //...
}

//...

private void OnMessageReceived_ThemeChangeRequest(ThemeChangeRequestMessage message)
{
    switch (message.Mode)
    {
        case FluentThemeMode.Light:
            this.Styles[0] = _resThemeLight;
            break;

        case FluentThemeMode.Dark:
            this.Styles[0] = _resThemeDark;
            break;
    }
}
```

Application.xaml:
```xml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             x:Class="HappyCoding.AvaloniaThemeSwitch.App">
    <Application.Resources>
        <FluentTheme x:Key="ResThemeLight" Mode="Light" />
        <FluentTheme x:Key="ResThemeDark" Mode="Dark" />
    </Application.Resources>
</Application>
```

**To Reproduce**
See this little project at https://github.com/RolandKoenig/HappyCoding/tree/main/2021/HappyCoding.AvaloniaThemeSwitch

1. Start the application
2. Switch to Dark theme using the menu item
3. Now try to switch back to Light theme using the menu item
4. You get the following error when clicking on the menu item

![error-switching-theme](https://user-images.githubusercontent.com/11254388/119222560-4908cf00-baf5-11eb-9de4-14aace6bc150.png)

**Expected behavior**
Normal behavior of MenuItem

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 20H2

**Comment by maxkatz6** [comment]
New API for theme switching, reuse same FluentTheme instance, but change Mode. 
https://github.com/AvaloniaUI/Avalonia/pull/7256

Or if you want to customize it, use the same approach as in that PR - keep control styles always loaded, but replace resource dictionaries.
