### ISSUE TITLE
Ability to add custom transformers to AvaloniaXamlIlCompiler

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaUI/Avalonia#5967]
I am the developer of [ShowMeTheXaml.Avalonia](https://github.com/AvaloniaUtils/ShowMeTheXaml.Avalonia) and it upsets me that in order for my library to work I need to force users to give each element a unique identifier (this is due to the specifics of the library). I wish I could automate this, but I can't influence the Xaml compilation process in Avalonia.

It would be cool for third party library developers to be able to add their own transformers to the Xaml compilation process.

I can write the bulk of the code for this myself, but am I missing something?  
Maybe there are some points that I don't take into account and, as a result, this feature will not be approved for some other factors (security considerations / idk)?

**Comment by kekekeks** [comment]
The main problem would be the API stability. We can't guarantee that compiler's API will be even remotely stable. Which means that custom transformers might break even on bugfix releases.

Another problem is the compatibility between different compiler plugins.

The third problem is IDE support. If everyone starts writing their own plugins, it would be impossible to implement that with IDE properly.


Roslyn doesn't allow you to rewrite code for a reason.


Regarding your particular library: I think just saving line information in attached properties would be enough and we kinda want that anyway for "Go to code" feature in previewer and possibly devtools.

**Comment by SKProCH** [comment]
Ok, I understand your reasoning. Thanks for the answer.
