### ISSUE TITLE
System.Drawing.Bitmap  Convert  Avalonia.Media.Imaging

### ISSUE THREAD

**Issue by Gao996** [AvaloniaUI/Avalonia#5983]
System.Drawing.Bitmap  Convert   to MemoryStream
MemoryStream Convert to Avalonia.Media.Imaging

No Show Image

Cannot display pictures on the page

**Comment by Gao996** [comment]
solved

**Comment by OaimIsGnay** [comment]
> 解决
请问如何解决opencvsharp获取到的图转为avalonia能用的格式? 谢谢
