### ISSUE TITLE
TextBox text does not display hieroglyphs

### ISSUE THREAD

**Issue by philippranzhin** [AvaloniaUI/Avalonia#5984]
**Describe the bug**
TextBox displays blank characters instead of hieroglyphs, although TextBlock displays them normally

**To Reproduce**

1. Create new solution from template "Avalonia Application"
2. Increment Avalonia Version to 0.10.5
3. Go to MainWindow.axaml
4. Add TextBox with Text="犬"   (犬 - dog on Japanese)
5. See blank character in TextBox in designer
6. Start application
7. See blank character in TextBox in application

**Expected behavior**
Hieroglyph should be displayed instead of blank character

**Screenshots**
![image](https://user-images.githubusercontent.com/28001927/119969145-dc8b4580-bfb6-11eb-8526-463ac9bf13e9.png)
![image](https://user-images.githubusercontent.com/28001927/119969704-908cd080-bfb7-11eb-8742-3c36ae4df9af.png)

**Desktop**

- OS: Windows
- Version 0.10.5

**Additional context**
A minimalistic example of reproduction is here: https://github.com/philippranzhin/AvaloniaTextBoxBugSample/blob/master/AvaloniaApplication5/MainWindow.axaml

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/4893

**Comment by maxkatz6** [comment]
Fixed in master
