### ISSUE TITLE
Rx 3.0 requires NuGet 2.12 or above

### ISSUE THREAD

**Issue by guillerot** [AvaloniaUI/Avalonia#599]
Since the update to Rx 3.0, Avalonia can't be build for Linux (Ubuntu 16.04 in my case)
Rx 3.0 requires Nuget 2.12 or above. Last version available for Linux is 2.8.7.0.

**Comment by wieslawsoltes** [comment]
Avalonia linux/osx CI is using this commands to restore NuGet packages:

```
mkdir -p .nuget
wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
mono .nuget/nuget.exe restore Avalonia.mono.sln
```

**Comment by guillerot** [comment]
Works perfectly. Thanks.
I haven't thought about using nuget.exe for win-x86-commandline instead of restore with MonoDevelop.
Sorry for the disturbance.
