### ISSUE TITLE
The F# MVVM Template does not compile

### ISSUE THREAD

**Issue by inputusernamehere** [AvaloniaUI/Avalonia#5992]
**Describe the bug**
Upon creating a new project using the F# MVVM template, the resulting project does not compile. I did not make any changes to any files. If I instead use the C# MVVM template, it compiles and runs just fine.

**To Reproduce**

I tried to follow the instructions here: https://docs.avaloniaui.net/tutorials/todo-list-app/creating-a-new-project
Specifically I downloaded the VS 2019 extension, and created a new project using the F# MVVM template.

**Expected behavior**
Ideally the bootstrapped project should compile and run. Or if there are any additional steps that need to be taken by the user, they should be added to the tutorial.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**

Windows 10 home, 10.0.19041. Visual studio 2019 16.8.6. Avalonia for VS 0.10.3.0.

**Additional context**
These are the compilation errors I am faced with:

ViewLocator.fs 10 - FS0859 No abstract property was found that corresponds to this override

Program.fs 9 - FS0501 The member or object constructor 'LogToDebug' takes 2 argument(s) but is here given 0. The required signature is '(extension) AppBuilder.LogToDebug<'T when 'T : (new : unit -> 'T) and 'T :> Controls.AppBuilderBase<'T>>(?level: Logging.LogEventLevel, [<ParamArray>] areas: string []) : 'T'.

Program.fs 3 - FS0039 The namespace 'Serilog' is not defined.

MainWindow.xaml.fs 10 - FS0039 The type 'MainWindow' does not define the field, constructor or member 'AttachDevTools'.

**Comment by inputusernamehere** [comment]
These are the changes I made to the bootstrapped F# project to make it compile, by comparing and contrasting against a bootstrapped C# project.

Moved `member __.SupportsRecycling with get() = false` outside of the `interface IDataTemplate with ...` block. This is because this property is not a part of the implementation of the `IDataTemplate` interface.

Change line 11 of Program.fs to `.LogToTrace(LogEventLevel.Warning)`. This is because F# does not understand having an optional argument in front of a params... argument. The template also defaulted to `.LogToDebug` which was marked deprecated.

Remove the `.Serilog` part of line 3 from program.fs: `open Avalonia.Logging.Serilog` -> `open Avalonia.Logging`

Install the Avalonia.Diagnostics nuget package, to add DevToolsExtensions for .AttachDevTools().

**Comment by FoggyFinder** [comment]
There is PR with a fix for the issue

https://github.com/AvaloniaUI/AvaloniaVS/pull/200

I've tried to bring more attention to this PR on gitter but was ignored once or twice :( Maybe you'll get some luck since I gave up here.

**Comment by inputusernamehere** [comment]
Ah I see, I didn't know there was a separate repository. That PR fixes the exact issue I have. I guess I will leave this open for posterity, but feel free to close it.

**Comment by grokys** [comment]
Sorry about that guys, I didn't see it. Will get it merged.
