### ISSUE TITLE
Incorrect TextBox selection coloring for non-left aligned text

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#600]
Text disappears for a moment when I'am trying to select text inside TextBox from right to left:
[video](https://files.gitter.im/AvaloniaUI/Avalonia/WbpT/Invalid_TextBox_selection_for_not_left_aligned_text.mp4)

**Comment by mikel785** [comment]
Reproduced with both gtk-cairo and direct2d-win32 platform implementations.
Going to done with it.

**Comment by mikel785** [comment]
Fixed and tested with gtk and direct2d.
