### ISSUE TITLE
Custom fonts not working

### ISSUE THREAD

**Issue by omerhijazi404** [AvaloniaUI/Avalonia#6001]
**Describe the bug**
I wanted to load and use a custom font, Cascadia Code, in a TextBox like this:
```xaml
<Label Grid.Column="1" FontFamily="/CascadiaCode.ttf#Cascadia Code" Foreground="#F1F1F1">Server URL (has to start with ws:// e.g. ws://localhost:3000)</Label>
```
and I have that file in my project:
![image](https://user-images.githubusercontent.com/65223292/120280868-e962ae80-c2c0-11eb-9731-7d26fc9762e1.png)
And after building, this comes in Diagnostics
```
10:08:05.864 [Error] 5680 UpdateXamlResult error
System.Xaml.XamlException: Could not create glyph typeface for: Cascadia Code.
10:09:25.905 [Error] 5680 UpdateXamlResult error
System.Xaml.XamlException: Could not create glyph typeface for: Cascadia Code.
10:09:28.285 [Information] 5680 Stopping previewer process
10:09:28.286 [Information]  Process exited
10:09:28.286 [Information]  Stopping previewer process
10:09:30.125 [Information]  Starting previewer process for '"C:\Users\HP\Desktop\Socket.IO Screen Share\Client\bin\Debug\net5.0\ScreenShareClient.dll"'
10:09:30.131 [Information] 10820 Started previewer process for '"C:\Users\HP\Desktop\Socket.IO Screen Share\Client\bin\Debug\net5.0\ScreenShareClient.dll"'. Waiting for connection to be initialized.
10:09:31.432 [Information] 10820 Connection initialized
10:09:35.174 [Error] 10820 UpdateXamlResult error
System.Xaml.XamlException: Could not create glyph typeface for: Cascadia Code.
```

**Expected behavior**
For the text (URL) to be shown in the Cascadia Code font

**Screenshots**
![image](https://user-images.githubusercontent.com/65223292/120281570-c5539d00-c2c1-11eb-9009-7fbe89e45288.png)
This is the screen if I use the above XAML markup.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 0.10.4

**Comment by Gillibald** [comment]
`FontFamily="/CascadiaCode.ttf#Cascadia Code"` Vs. `FontFamily="/CascadiaCode.otf#Cascadia Code"`
I think you got the filename wrong

**Comment by omerhijazi404** [comment]
i already tried that
still doesnt work

**Comment by Gillibald** [comment]
Please post your `csproj` file

**Comment by omerhijazi404** [comment]
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <EmbeddedResource Include="Assets/**" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.10.5" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.5" />
    <PackageReference Include="Avalonia.Diagnostics" Version="0.10.5" />
    <PackageReference Include="SocketIOClient" Version="2.2.0" />
  </ItemGroup>
</Project>
```
![image](https://user-images.githubusercontent.com/65223292/120344979-c0fba400-c302-11eb-8685-183cee0b528e.png)

**Comment by kekekeks** [comment]
You are using EmbeddedResource. Those don't support relative paths. Either use AvaloniaResource or properly address the font with resm scheme

**Comment by omerhijazi404** [comment]
that also doesnt work
tried:
```
resm:ScreenShareClient.Assets.CascadiaCode.ttf?assembly=ScreenShareClient#Cascadia Code

**Comment by omerhijazi404** [comment]
Anyone?

**Comment by maxkatz6** [comment]
Have you tried avares using AvaloniaResourse defined in the csproj file?
Do you have minimal project to reproduce the problem?

**Comment by omerhijazi404** [comment]
it works there, in my main project it doesnt
