### ISSUE TITLE
Avalonia.Android nuget abandoned 

### ISSUE THREAD

**Issue by ItsNerd** [AvaloniaUI/Avalonia#6008]
**Describe the bug**
Updates for the Avalonia.Android package on [nuget](https://www.nuget.org/packages/Avalonia.Android/) have not been released for over a year (since Avalonia version 0.8.4)

**Expected behavior**
Package updates are published along with updates to the main Avalonia packages.

**Screenshots**
![image](https://user-images.githubusercontent.com/59473591/120518567-62a1f480-c3da-11eb-9299-ce0dc8362d60.png)

**Comment by kekekeks** [comment]
@jp2masa is it stable enough to be published on nuget.org again?

**Comment by jp2masa** [comment]
Not sure how stable it needs to be for publishing on nuget.org. It's much better than it was a few months ago (it was completely unusable) but there are still a few bugs (IIRC changing orientation breaks in some cases and similar problems). If you consider that kind of bugs is acceptable (in my opinion it is, as the backend is still experimental), then I think it makes sense to publish again.

**Comment by SKProCH** [comment]
I think that even in spite of the bugs, you need to publish the package (even as a prerelease or some other mark that it is unstable)
It takes a time to build all this from the sources yourself
If you don't want to publish this on nuget, then maybe you should consider publishing this on the nightly feed?

**Comment by maxkatz6** [comment]
Nightly packages are available. Stable nuget will be there with next major version. 

Also templates
https://github.com/AvaloniaUI/avalonia-dotnet-templates/pull/79

And sample app
https://github.com/AvaloniaUI/Wordle-onia
