### ISSUE TITLE
Virtualization Exception: Not Handling index = -1 in CreateAndRemoveContainers

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#602]

**Comment by danwalmsley** [comment]
private void CreateAndRemoveContainers()
        {
            var generator = Owner.ItemContainerGenerator;
            var panel = VirtualizingPanel;

            if (!panel.IsFull && Items != null && panel.IsAttachedToVisualTree)
            {
                var memberSelector = Owner.MemberSelector;
                var index = NextIndex;
                var step = 1;

                while (!panel.IsFull)
                {
                    if (index >= ItemCount)
                    {
                        // We can fit more containers in the panel, but we're at the end of the
                        // items. If we're scrolled to the top (FirstIndex == 0), then there are
                        // no more items to create. Otherwise, go backwards adding containers to
                        // the beginning of the panel.
                        if (FirstIndex == 0)
                        {
                            break;
                        }
                        else
                        {
                            index = FirstIndex - 1;
                            step = -1;
                        }
                    }

                    var materialized = generator.Materialize(index, Items.ElementAt(index), memberSelector);

                    if (step == 1)
                    {
                        panel.Children.Add(materialized.ContainerControl);
                    }
                    else
                    {
                        panel.Children.Insert(0, materialized.ContainerControl);
                    }

                    index += step;
                }

                if (step == 1)
                {
                    NextIndex = index;
                }
                else
                {
                    NextIndex = ItemCount;
                    FirstIndex = index + 1;
                }
            }

            if (panel.OverflowCount > 0)
            {
                RemoveContainers(panel.OverflowCount);
            }
        }

**Comment by danwalmsley** [comment]
I get an exception in generator.Materialize because sometimes index = -1
Perhaps this should be a valid case? Not sure what leads to this, I made a quick test of an if statement around it, and seems to fix my problem, but without an expert eye on this I wouldnt know if it was ok to fix like that.

**Comment by donandren** [comment]
I'm experiencing that problem also from time to time

**Comment by grokys** [comment]
No, `index` shouldn't ever be -1 there. That's a bug. If this is the same as #589 it should be easy enough to fix.

**Comment by danwalmsley** [comment]
@grokys hm not sure, it might be same. It happens in my intellisense control when I'm trying fast casing the listbox to be hidden and shown rapidly.

not sure exactly what is causing it, other than that, if that gives a clue?

**Comment by danwalmsley** [comment]
Ok this appears to have been resolved with recent fixes in related issues.
