### ISSUE TITLE
DataGrid : KeyDown event will never fired.

### ISSUE THREAD

**Issue by Panuon** [AvaloniaUI/Avalonia#6027]
**Describe the bug**
KeyDown event will never fired on DataGrid control.

**To Reproduce**
Add KeyDown event handler on DataGrid control, press down key.

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Windows
- Version: 0.10.5

**Additional context**
N/A

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/5753#issuecomment-817241375

**Comment by Panuon** [comment]
Thank you, it works well.

Another question please, how to handle double click event on DataGridRow? In WPF, I can add EventSetter in RowStyle, Is there any way to implement it?

**Comment by maxkatz6** [comment]
You can handle double click on DataGrid and get Source control from event args. It might contain inner cell content, so you will need to traverse by ```VisualParent```s up.
Other way is to subscribe on LoadingRow event and subscribe on any row event you want. Just do not forget to unsubscribe in UnloadingRow.
Probably there is a simples solution with routing events, but I can't say now for sure.

**Comment by Panuon** [comment]
Okay, I will try. Thanks a lot.
