### ISSUE TITLE
av_libglesv2.dll not copied to output directory with win-x(86|64) RID

### ISSUE THREAD

**Issue by trympet** [AvaloniaUI/Avalonia#6028]
**Describe the bug**
When building an Avalonia project, or projects with a transitive dependency on an Avalonia project, `av_libglesv2.dll` is not copied to the output directory unless the RID is set to `win(7|81|10)-x(86|64)`.

~~This throws an exception when AllowEglInitialization is set to true.~~
This causes any DPI scale over 200% to become unusable on Windows due to lag.

**To Reproduce**
1. Create a new Avalonia MVVM project.
2. Set the runtime identifier in csproj:
```xml
<RuntimeIdentifier>win-x64</RuntimeIdentifier>
```
4. Build the project 
5. Observe that the output directory does not contain `av_libglesv2.dll`

**Expected behavior**
The ANGLE assembly should be copied to the output directory for all windows RIDs.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 19043
- Version 0.10.3

**Comment by kekekeks** [comment]
@danwalmsley do you remember if we had copy .targets for the legacy dotnet?

**Comment by trympet** [comment]
This also breaks Desktop Bridge, since AFAIK it forces `win-x(64|86)` RID on the publish profile.

**Comment by danwalmsley** [comment]
@kekekeks I only remember it only worked with win7-x64.. probably we did not have a targets file to copy. Will check package.

**Comment by kekekeks** [comment]
It looks like to be a new SDK issue, so we probably need to add another set of directories to the `runtimes` dir

**Comment by jamsoft** [comment]
I've noticed this on my current project. Without the file in the directory the app runs fine but has a glass see-through chrome on the window. If I place the file in the directory and run the application, it runs fine but with a normal window chrome ...

Is this required but only on Win 7 boxes? It's a bit confusing.
