### ISSUE TITLE
Add support for FormattedText.BuildGeometry and FormattedText.BuildHighlightGeometry

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#6043]
**Is your feature request related to a problem? Please describe.**
In order to do animation on text I need access to text geometry, in WPF this can be done via `FormattedText.BuildGeometry` api.

**Describe the solution you'd like**

Add support for `FormattedText.BuildGeometry` api similar to WPF version:

https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.formattedtext.buildgeometry?view=net-5.0
```
public System.Windows.Media.Geometry BuildGeometry (System.Windows.Point origin);
```

and `FormattedText.BuildHighlightGeometry` api similar to WPF version:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.formattedtext.buildhighlightgeometry?view=net-5.0
```
public System.Windows.Media.Geometry BuildHighlightGeometry (System.Windows.Point origin);
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Nikhilsp** [comment]
Is the BuildGeometery available in Avalonia ? It shows formatted text does not have build geometery.

**Comment by maxkatz6** [comment]
Both APIs are now available in preview
