### ISSUE TITLE
Multiline TextBox caret is moved to wrong column when pressing return

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#6051]
**Describe the bug**

When you have a `TextBox` with `AcceptsReturn="true"`, pressing return moves the caret down a line but doesn't move it to the first column until a character is entered.

**To Reproduce**

- Go to ControlCatalog, `TextBox` page. 
- Focus one of the multi-line text boxes (second column)
- Delete all existing text in the text box
- Type some text and press return

**Expected behavior**

The caret is moved to column 0.

**Screenshots**

https://user-images.githubusercontent.com/1775141/121663084-538c0800-caa6-11eb-80fb-fac8fa339ab2.mp4

**Desktop (please complete the following information):**

- OS: Windows
- Version: `master` (checked back to 0.10.0)

cc: @Gillibald

**Comment by grokys** [comment]
Seems to be caused by the logic which inserts an additional line in the case of trailing newlines here: https://github.com/AvaloniaUI/Avalonia/commit/1a4fd00f2b77d0a648b00ca680227bb164c53ddd

When this blank line is present, it contains a duplicate of the `\r\n` in the previous line - these characters are reported as having a width of 13 each and used to place the caret.

**Comment by Gillibald** [comment]
Y these should have zero with

**Comment by grokys** [comment]
Any idea what the correct fix would be?

- First of all why does `SkPaint.MeasureText` return 13.920455 for a `\r` character?
- Given that it does this, should we just not call `MeasureText` for non-printable chars?
- If so what's the best way to detect non-printable chars?

**Comment by Gillibald** [comment]
LineBreak characters don't need to be measured so we can just assume zero width here. We can't simply fix this in one line that's why my TextPresenter rework exists. I need to continue my work on that rework.

**Comment by Gillibald** [comment]
To detect non printable character you could test the `UnicodeCategory.Control` property of each character. That will cover most cases.

**Comment by grokys** [comment]
>  We can't simply fix this in one line that's why my TextPresenter rework exists. I need to continue my work on that rework.

Understood, just looking for a temporary fix for this issue until that work's finished.
