### ISSUE TITLE
Changing SelectedItem bound property on ComboBox and ListBox is not reflected on View

### ISSUE THREAD

**Issue by blueperspective** [AvaloniaUI/Avalonia#6060]
**Describe the bug**
Using SelectedItem binding, with ComboBox or ListBox, changing the bound property is not reflected on the view.
If the same bound property is used on a TextBox Text binding, the correct value appears.
No errors in output window.
This works fine with SelectedIndex : changing from View or ViewModel updates selected item on listbox and combobox.

**To Reproduce**
Check out https://github.com/blueperspective/avaloniaSelectedItemIssue

**Screenshots**
NOT WORKING: On left hand side, using SelectedIem, no selected item appears (set in viewmodel constructor).
WORKING: On right hand side, using SelectedIndex, selected item appears on both combobox and listbox.
Changing selected item in combobox or listbox updates the other.

![image](https://user-images.githubusercontent.com/22202667/121808542-45cab400-cc59-11eb-9630-e6b3c561bb71.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.6

**Comment by grokys** [comment]
This is because your equality comparison code is incorrect. To demonstrate, at the end of your `MainWindowViewModel` constructor put the following code:

```
            if (Categories.IndexOf(ca2) == -1)
                throw new InvalidOperationException("Equals is broken!");
```

More specifically, this code in `Category` is incorrect:

```
        public override bool Equals(object? obj)
        {
            return Name.Equals(obj);
        }
```

`obj` is a `Category` object, so will never be equal to `Name`. I think you meant to do:

```
        public override bool Equals(object? obj)
        {
            return obj is Category c && Name.Equals(c.Name);
        }
```

If I fix `Category.Equals` in this matter, selection seems to work.

**Comment by blueperspective** [comment]
Ok yes thank you, my bad, I did this for testing on DataGrid, I implemented this a bit too quickly... :(
