### ISSUE TITLE
System.OverflowException in WindowImpl - Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#607]
System.OverflowException in WindowImpl - Arithmetic operation resulted in an overflow
It's happening very rare.
at https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/WindowImpl.cs#L495-L500

+		lParam	{32899776}	System.IntPtr
+		wParam	{4279238656}	System.IntPtr

basically problem is at:	

1. 

(int)wParam >> 16	'(int)wParam >> 16' threw an exception of type 'System.OverflowException'	int {System.OverflowException} and 		

2. 

GetMouseModifiers(wParam)	'GetMouseModifiers(wParam)' threw an exception of type 'System.OverflowException'	Avalonia.Input.InputModifiers {System.OverflowException}

all places that we have those expressions in handle mouse wheel are likely to fail at similar conditions

**Comment by Sorien** [comment]
as i remember you might need to suppress overflow-checking in order for this to work properly or something like that
