### ISSUE TITLE
DrawingContext.DrawText does not render chinese or japanese text

### ISSUE THREAD

**Issue by Mochengvia** [AvaloniaUI/Avalonia#6089]
Here's my code:
```
var formattedText = new FormattedText("Chinese 中文 Japanese 日本語"
                   , new Typeface(FontFamily.Default)
                   , 14
                   , TextAlignment.Left
                   , TextWrapping.Wrap
                   , new Size(double.PositiveInfinity, double.PositiveInfinity));

context.DrawText(Brushes.White, new Point(0, 0), formattedText);
```

Here's the effect
![image](https://user-images.githubusercontent.com/23360265/122341193-c9481600-cf75-11eb-884a-c965ae40581e.png)

- OS: Windows 10
- Version : 0.10.6

**Comment by Gillibald** [comment]
`TextLayout` should work for you

**Comment by Mochengvia** [comment]
Alright... This's a little strange, but it works well.

Edit:
```
var textLayout = new TextLayout("Chinese 中文 Japanese 日本語"
                    , new Typeface(FontFamily.Default)
                    , 14
                    , Brushes.White
                    , TextAlignment.Left
                    , TextWrapping.Wrap);

textLayout.Draw(context);
```

**Comment by Mochengvia** [comment]
Sorry, I have encountered a new problem.
 How can I fix the drawing position of TextLayout? My DrawingContext is in a container similar to a canvas.

**Comment by Gillibald** [comment]
Y that is a bit tricky. You need to push a transform before rendering the layout.

**Comment by Gillibald** [comment]
Current master has this fixed https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBlock.cs#L438

**Comment by Mochengvia** [comment]
ok, thanks a lot.
