### ISSUE TITLE
Tizen support

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#6110]
**Is your feature request related to a problem? Please describe.**
Tizen .Net is popular platform, but I can't use AvaloniaUI for it.

**Describe the solution you'd like**
Tizen Net base on xamarin. And if avalonia may work on xamarin framework. May be it may run on Tizen devices
![изображение](https://user-images.githubusercontent.com/33497292/122650522-27bef100-d13c-11eb-894d-7adb0da538f5.png)

https://developer.samsung.com/tizen/About-Tizen.NET/Tizen.NET.html

**Comment by maxkatz6** [comment]
It would be possible with their workload available on officially
https://github.com/Samsung/Tizen.NET/tree/main/workload

Furthermore, Avalonia architecture allows custom windowing and rendering backends, so it should be possible to create Tizen backend as a third-party project. If there are people who want to participate.

**Comment by MrJul** [comment]
Implemented in #12151
