### ISSUE TITLE
OpenFileDialog closes my application

### ISSUE THREAD

**Issue by ilia19911** [AvaloniaUI/Avalonia#6132]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/6131

<div type='discussions-op-text'>

<sup>Originally posted by **ilia19911** June 24, 2021</sup>
Hi. i am trying build my first application in avalonia with button which opens FileDialog.  Then I click on the button, in axaml InvokeCommandAction is triggered and thereafter program opens ReactiveCommand.  My code looks like this
```csharp
async void RunOpenFile(string parameter)
{
    if (Avalonia.Application.Current.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
    {
        OpenFileDialog openFileDialog = new OpenFileDialog
        {
            Title = "Choose Images",
        };
        openFileDialog.Filters.Add(new FileDialogFilter { Name = "Images", Extensions = { "jpg", "png", "tif" } });
        await openFileDialog.ShowAsync( desktop.MainWindow);
    }
} 
```
But my application just closes without any exceptions.

OS: Ubuntu 20.04
FW: NET5
Avalonia version: 0.10.6 

I will be glad for any help</div>

**Comment by maxkatz6** [comment]
If issue is still reproducible on latest stable branch, please attach stack trace and error message (if available, see [unhandled exceptions page](https://docs.avaloniaui.net/docs/getting-started/unhandledexceptions)). Also check console output and event viewer (windows) or console app (macos).
