### ISSUE TITLE
TextBox does not allow for clearing whitespace only

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#6134]
**Describe the bug**
`TextBox` does not show clear and reveal buttons when whitespace input is used.
This seems to work in WinUI so I wonder if this was intended.

**To Reproduce**

Enter whitespace into a `TextBox`, watermark will disappear but clear button won't appear.

**Expected behavior**

**Screenshots**

Spaces entered into password and text box.

![image](https://user-images.githubusercontent.com/2588062/123304674-82cb5c00-d51f-11eb-9de8-6866ea452515.png)
![image](https://user-images.githubusercontent.com/2588062/123304748-98d91c80-d51f-11eb-974e-e7b43cf882ac.png)

In WinUI:
![image](https://user-images.githubusercontent.com/2588062/123305001-e3f32f80-d51f-11eb-9ad7-718091d84466.png)
![image](https://user-images.githubusercontent.com/2588062/123304976-dccc2180-d51f-11eb-8713-729af09c38fb.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version: master

**Additional context**

cc: @maxkatz6

**Comment by maxkatz6** [comment]
TextBox has ":empty" selector, which for some reason is set when text is null or white space:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBox.cs#L1293

**Comment by MarchingCube** [comment]
This line was written by you so I hoped that you have some idea why 😅

**Comment by maxkatz6** [comment]
@MarchingCube yeah...it didn't help me to understand why :D
