### ISSUE TITLE
Avalonia goes into Loop when I use RowDefinition=Auto containing a Virtualized listbox

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#614]
This may or may not be a bug in Avalonia, (so apologies in advance if not) but its easy to reproduce.

1) Clone Avalon Studio commit
https://github.com/VitalElement/AvalonStudio/commit/74387b611bd53556b24ea9d7dc8495b94c733b0f

2) Clean and Build entire solution.

3) Copy your Avalonia DLLs to replace the nugget onces in AvalonStudio/Packages folder.

4) Compile and run.

5) File -> New Project

6) Select unit test project.

7) Tools packages..

8) Select LocalGCC and select the option from drop down on right, that begins Win32.

9) Click Install.

10) when Package has installed successfully, click ok.

11) Press F5 or Play to compile and begin debug session.

Notice the perspective changes, and debugging controls become visible, with memory viewer on top.
But it should be frozen and stuck in an endless loop.

This is caused by MainWindow.paml Line 63

```
<Grid RowDefinitions="Auto,5,100*">
```

**Comment by danwalmsley** [comment]
Replacing the Auto part to * fixes the problem, but auto should work, so it may be a problem in measure, when using virtualized listbox?

**Comment by donandren** [comment]
not a good idea to have a vertical  Listbox in a row with Auto height, this way the virtualization probably is effectivelly off, as there will be no height restriction of the Listbox. But even in that case exception shouldn';t be thrown just it will be slow as all the listbox items need to be created.

**Comment by danwalmsley** [comment]
@donandren I agree, but the other rows below it, the 5 and 100* do have a height,

so it should basically have assigned the remaining space shouldn't it? so it shouldn't be trying to fill an infinite height.

**Comment by donandren** [comment]
@danwalmsley nope from my understanding about auto length it's not restricting the child control any way. 

> Auto	The size is determined by the size properties of the content object.

https://msdn.microsoft.com/en-us/library/system.windows.gridunittype.aspx

**Comment by danwalmsley** [comment]
@donandren ok agreed. your comments helped me realise the error in my ways...
After setting a Height on my control it prevented the looping. Thanks for being persistant. :)

**Comment by danwalmsley** [comment]
@grokys do you want to close this, or leave open, perhaps an exception could have been thrown?

**Comment by grokys** [comment]
I don't think an exception can really be thrown here...

It would be interesting to see what the behavior of WPF is in this case. I will leave this open until we've investigated that.
