### ISSUE TITLE
Clipping Geometry on Apple M1

### ISSUE THREAD

**Issue by vmelnikov** [AvaloniaUI/Avalonia#6144]
Geometry clipping does not work correctly on Apple M1
![image](https://user-images.githubusercontent.com/909417/123436326-2f1c4980-d5d7-11eb-9b4a-62832b155b29.png)

**Comment by vmelnikov** [comment]
I think something wrong with `SkiaGpuRenderTarget`. Everything is ok if `With(new AvaloniaNativePlatformOptions { UseGpu = false })` added in Program.cs

**Comment by Mikolaytis** [comment]
We have the same issue. It hurts. @vmelnikov thanks for a solution!
I think an update of SkiaSharp skia version up to version 90+ (for example) will fix this... Current version is 80. It was published before m1 mac release AFAIK. Later skia version maybe fixes this issue. Let's wait for a new release from @mattleibow

**Comment by BAndysc** [comment]
@Mikolaytis Sadly latest version 2.88.0-preview.127 on .net6.0, native m1 doesn't fix the problem

**Comment by Mikolaytis** [comment]
@BAndysc wow. thanks a lot for a pretty useful information. any thoughts what can fix it?
I know there is two options of clipping in skia (antialiased and basic). Maybe let's try to switch this option and check it out?

**Comment by iMonZ** [comment]
Any news on that?

**Comment by grokys** [comment]
Investigating this now. Minimal repro:

```
<Border Background="Yellow" Width="200" Height="200" ClipToBounds="True">
    <Image Height="48" Margin="0,200,0,0">
        <Image.Source>
            <DrawingImage>
                <GeometryDrawing Brush="Red" Geometry="F1M14.707,4.707L6,13.414 1.293,8.707 2.707,7.293 6,10.586 13.293,3.293z" />
            </DrawingImage>
        </Image.Source>
    </Image>
```

Output on M1 Mac:

![image](https://user-images.githubusercontent.com/1775141/140763246-99950ba8-63d6-4aa8-9b90-836f175631b3.png)

**Comment by grokys** [comment]
Definitely looks to be a Skia issue. If I add the following code at this line: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Skia/Avalonia.Skia/DrawingContextImpl.cs#L185

```
Canvas.Clear(SKColors.Gold);
```

(i.e. immediately before drawing the geometry)

I get the following output. You can see that the .Clear() call uses the correct clip but the geometry is just ignoring it:

![image](https://user-images.githubusercontent.com/1775141/140775185-a2edf2d2-7c79-4b09-9ebe-2cb03a928280.png)
