### ISSUE TITLE
Can not input chinese to TextBox on Linux (Ubuntu 18.04)

### ISSUE THREAD

**Issue by gaowei123** [AvaloniaUI/Avalonia#6155]
I can let TextBox display chinese by setting the font-family, copy chinese to the textbox working as well, but i can not  input chinese directly. 

![Textbox_Bug](https://user-images.githubusercontent.com/17244869/123910295-d0771700-d9ac-11eb-8300-10d2d1b69e02.png)

**Comment by kekekeks** [comment]
1) which version of Avalonia are you using?
2) Which IM engine are you using? We only support ibus and fcitx.

**Comment by kekekeks** [comment]
What is likely to happen is that we don't enable IME support for western locales by default. So either set `EnableIme=true` in `X11PlatformOptions` or set AVALONIA_IM_MODULE=ibus or AVALONIA_IM_MODULE=fcitx environment variable.

**Comment by gaowei123** [comment]
> What is likely to happen is that we don't enable IME support for western locales by default. So either set `EnableIme=true` in `X11PlatformOptions` or set AVALONIA_IM_MODULE=ibus or AVALONIA_IM_MODULE=fcitx environment variable.

it works after setting `X11PlatformOptions` `EnableIme=true`. 
Really appreciate your help very much.

![code](https://user-images.githubusercontent.com/17244869/123918883-e8539880-d9b6-11eb-89b6-7ba43038005c.png)
![testChinese](https://user-images.githubusercontent.com/17244869/123918917-f0abd380-d9b6-11eb-8193-805557522d8b.png)
