### ISSUE TITLE
Allow to specify x:DataType on `{CompiledBinding ...}` expression

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#6158]
**Is your feature request related to a problem? Please describe.**

With `[AssignBinding]` it's possible to assign a binding descriptor (without instantiating the binding) to a property. With reflection bindings it doesn't matter to which type you're binding since that is resolved lazily when instantiating the binding. With compiled bindings however it's required to provide a `x:DataType` to specify the target type. That works fine when all `AssignBinding` assignments are targeting the same type, but it doesn't work when they target different types:

`<MyControl x:DataType="Foo" FooXBinding="{CompiledBinding X}"  BarXBinding="{CompiledBinding X}" /> `

`BarXBinding` should be a compiled binding to `Bar` not `Foo`.

**Describe the solution you'd like**

Allowing users to specify the DataType directly on the compiled binding expression:

`<MyControl FooXBinding="{CompiledBinding X, DataType={x:Type Foo}}"  BarXBinding="{CompiledBinding X, DataType={x:Type Bar}}" /> `

**Comment by grokys** [comment]
@jkoritzinsky any thoughts?

**Comment by jkoritzinsky** [comment]
This seems like a reasonable request.

We could probably also use this mechanism to help use compiled bindings with some of the DataGrid column binding properties.

**Comment by pr8x** [comment]
I tested this locally and it seems that it doesn't quite work yet (with `[AssignBinding`). 

Repro:
[compiled_binding_data_type_bug.patch.txt](https://github.com/AvaloniaUI/Avalonia/files/8118514/compiled_binding_data_type_bug.patch.txt)

> Severity	Code	Description	Project	File	Line	Suppression State
Error	XAMLIL	Cannot parse a compiled binding without an explicit x:DataType directive to give a starting data type for bindings. Line 6, position 16. [D:\Repositories\Avalonia\samples\Sandbox\Sandbox.csproj]	Sandbox	D:\Repositories\Avalonia\samples\Sandbox\MainWindow.axaml	6

**Comment by pr8x** [comment]
Also, we probably need some UnitTests for this.
