### ISSUE TITLE
On Linux WindowStartupLocation="CenterOwner" not expected behavior

### ISSUE THREAD

**Issue by gfx-alex** [AvaloniaUI/Avalonia#6159]
**Describe the bug**
On Linux OS window called via ShowDialog appear in a random position, although the WindowStartupLocation="CenterOwner" property is set. On Windows OS window positions is correct

**Expected behavior**
When WindowStartupLocation="CenterOwner" window called via ShowDialog appear in Center of owner window independent of platform

**Screenshots**
![avalonia_window_sturtup_location 1](https://user-images.githubusercontent.com/60728271/123998193-ae9c8500-d9ea-11eb-9abf-4737b24f79ba.png)
![avalonia_window_sturtup_location 2](https://user-images.githubusercontent.com/60728271/123998206-b3613900-d9ea-11eb-87fa-bbcdf4f5a444.png)

**Desktop (please complete the following information):**

- OS: Linux Ubuntu 18.04, Ubuntu 20.04, Raspbian
- X11
- Version 10.0.6

**Comment by maxkatz6** [comment]
@kekekeks

**Comment by maxkatz6** [comment]
Duplicates of https://github.com/AvaloniaUI/Avalonia/issues/3454 https://github.com/AvaloniaUI/Avalonia/issues/6159
I will keep one issue with more details

**Comment by maxkatz6** [comment]
it seems it worked in 0.10.3 https://github.com/AvaloniaUI/Avalonia/issues/6115#issuecomment-868224141

**Comment by KorotynskiyA** [comment]
I have the same problem with WindowStartupLocation="CenterOwner" and WindowStartupLocation = "CenterScreen". 

OS: Raspbian, Linux Ubuntu 18.04
Version: 0.10.6, 0.10.7

But with in version 0.10.3 it's work good.

**Comment by maxkatz6** [comment]
Closing as a duplicate
