### ISSUE TITLE
[Bug][Documentation] pseudoclasses styling not working

### ISSUE THREAD

**Issue by AnonymousWalker** [AvaloniaUI/Avalonia#6161]
I wanted to set the style for controls using pseudoclasses (:pointerover, :disabled,...). 
However, I tried the example from the documentation and it's not working. In this example, pointer hover on the button should change the text color to red but it still shows the default grey-ish color.

### https://docs.avaloniaui.net/docs/styling/styles#pseudoclasses

![image](https://user-images.githubusercontent.com/34975907/124159862-9e77ba80-da69-11eb-9a74-8925f26fd76f.png)

Seems like these pseudoclasses are not working properly

**Comment by AnonymousWalker** [comment]
I'm using 0.10.4

**Comment by maxkatz6** [comment]
Thanks, I updated this documentation page.
To keep this repo cleaner, you can create documentation related issues in https://github.com/AvaloniaUI/Documentation
