### ISSUE TITLE
macOS platform-specific keybindings for TextBox

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#6195]
We noticed an odd behavior in keybindings for TextBoxes in macOS:

* <kbd>Cmd</kbd> + <kbd>left</kbd>/<kbd>right</kbd> arrow: 
  * **Expected behavior**: cursor moves to the start/end of the line
  * **Actual behavior**: cursor moves one character left/right
* <kbd>Option</kbd> + <kbd>left</kbd>/<kbd>right</kbd> arrow:
  * **Expected behavior**: cursor moves to the start/end of the previous/next word 
  * **Actual behavior**: cursor moves one character left/right

**Comment by maxkatz6** [comment]
Mostly related to this file https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Input/Platform/PlatformHotkeyConfiguration.cs

**Comment by danipen** [comment]
@mat1jaczyyy @maxkatz6, please could you add the following missing gestures for macOS?

<kbd>Cmd</kbd> + <kbd>Up</kbd>: Go to document start
<kbd>Cmd</kbd> + <kbd>Down</kbd>: Go to document end
<kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>Up</kbd>: Select to document start
<kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>Down</kbd>: Select to document end

Thank you!

**Comment by mat1jaczyyy** [comment]
@danipen sure
