### ISSUE TITLE
Opened windows don't have keyboard focus on macOS

### ISSUE THREAD

**Issue by BAndysc** [AvaloniaUI/Avalonia#6202]
**Describe the bug**
On MacOS, newly opened windows are in weird status when it comes to their focus, keyboard focus. Newly opened windows look like they are focused, their `IsActive` property is `true`, but no keyboard events are received until you click anywhere on the window. The window is receiving pointer events properly tho.

**To Reproduce**
Repro: https://github.com/BAndysc/AvaloniaTestFocus

1. Open application on macOS
2. Press "Open window" button (and do not click anything else now)
3. New window looks like it is active, IsActive is true, textbox looks focused, but no keyboard event is received by the window until you click anywhere in that new window.

**Expected behavior**
It works properly on Windows - the newly opened window should have proper focus - the textbox should receive keyboard events.

**Screenshots**

![bug](https://user-images.githubusercontent.com/5689666/124682989-055efe80-dec4-11eb-9ba9-3e6dbafd1576.gif)

The red dot shows Pointer Events work correctly.

(you can see mouse click effect, before I click on the window, I was typing keys on my keyboard, but they weren't received)

**Desktop (please complete the following information):**

- OS: MacOS BigSur 11.4 on M1 via Rosetta
- Version 0.10.6

**Comment by BAndysc** [comment]
For a further test, I put a breakpoint here: https://github.com/AvaloniaUI/Avalonia/blob/1bfa7a6aa6dd96b02f7dabbd72abb7d4c4f22881/src/Avalonia.Native/WindowImplBase.cs#L211 and I can confirm the key events are not received at all, so I guess it is problem in macos interop code

**Comment by grokys** [comment]
Hi @BAndysc - yeah this has been reported by a customer too. We're in the middle of a bug-bashing session for OSX so hopefully will be fixed in the next day or two.
