### ISSUE TITLE
Pointer in tapping events

### ISSUE THREAD

**Issue by RomanSoloweow** [AvaloniaUI/Avalonia#6203]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/6201

Clicking is preferred, but these events do not reference the IPointer to get the current coordinates and perform the capture.

Need to add an IPointer to the Tapped and DoubleTapped events.

**Comment by maxkatz6** [comment]
To add this property, this event args should be modified
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Input/TappedEventArgs.cs
