### ISSUE TITLE
Feature request: drop-shadow property

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#6207]
**Is your feature request related to a problem? Please describe.**
Right now it's possible to add shadow to very specific controls using BoxShadow, that is working only with Border and ContentPresenter. Its behavior is technically the same as in CSS.
But it's not possible to apply drop shadow effect to any control, including geometry.

**Describe the solution you'd like**
[DropShadows](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/drop-shadow()) property similarly how we have BoxShadows.

**Describe alternatives you've considered**
[WPF Effects](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement.effect?view=net-5.0) API, was mentioned previously here https://github.com/AvaloniaUI/Avalonia/issues/2605
Or UWP-style Composition API with [Compositor.CreateDropShadow](https://blogs.windows.com/windowsdeveloper/2016/09/12/creating-beautiful-effects-for-uwp/) with higher level API on control - [Shadow](https://docs.microsoft.com/en-us/windows/apps/design/layout/depth-shadow)

**Comment by maxkatz6** [comment]
CC @kekekeks

**Comment by mohdimas** [comment]
This will be really useful to have 👍

**Comment by DmitriyYukhanov** [comment]
Looking forward to seeing it implemented too!

**Comment by Flithor** [comment]
Not fully same with css, it not support rem unit.

**Comment by kekekeks** [comment]
Implemented as drop shadow effect
