### ISSUE TITLE
Feature request: text-shadow property

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#6208]
**Is your feature request related to a problem? Please describe.**

Right now it's not possible to implement text with a shadow, unless you define second text block with some offset.

**Describe the solution you'd like**
[TextShadows](https://www.w3schools.com/cssref/css3_pr_text-shadow.asp) similarly how we have BoxShadows

**Describe alternatives you've considered**
Drop shadow for any type of geometry - https://github.com/AvaloniaUI/Avalonia/issues/6207

**Additional context**
It seems even in Skia we have to render text twice manually, but at least we can do it on lower level. [#1](https://groups.google.com/g/skia-discuss/c/iPuPYVUjcLE) [#2](https://stackoverflow.com/questions/48838584/drop-shadow-or-edge-on-text-using-skiasharp)

UPD:
For now it's not that hard to implement simple shadow support with a custom text block control
https://gist.github.com/maxkatz6/24be64ceb9e0b395caa11a69c725658a

**Comment by maxkatz6** [comment]
CC @kekekeks @Gillibald

**Comment by Gillibald** [comment]
TextShadow requires a shader that is applied per GlyphRun. Should be trivial to implement once we get `context.PushLayer(new LayerProperties{ Effect = new DropShadow()})` or similar

**Comment by kekekeks** [comment]
Pushing layer per run might be rather costly especially with CPU rendering. We should check how Chrome handles that.

**Comment by Gillibald** [comment]
You will push a layer per DropShadow instance so normally you will push that layer in the context of a `TextLayout.Draw` etc.

**Comment by kekekeks** [comment]
Yes, but each layer is essentially a draw-to-texture operation. So it's cheaper to draw the entire text a second time with an offset.

Also note that text has to drop shadow as a whole, which I suspect might cause issues with your approach if text runs have different colors.

**Comment by kekekeks** [comment]
Yes, text can be blurred via mask filters, see https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/effects/mask-filters.

I _think_ that doesn't involve a render-to-texture step.

**Comment by maxkatz6** [comment]
It's possible now with `<TextBlock Effect="blur( ... )" />`
