### ISSUE TITLE
Can't use the WinForms interop control; I get an error when I try to place it on a form.

### ISSUE THREAD

**Issue by ekolis** [AvaloniaUI/Avalonia#6233]
**Describe the bug**
I'm trying to use the WinForms interop control from Avalonia v0.10.6 in a .NET 5 project in Visual Studio 2019 v16.10.3. However, when I try to place the control on the form using the VS toolbox, I get an error.

**To Reproduce**

1. Open a .NET 5 WinForms app in Visual Studio 2019.
2. Add references to these NuGet packages: Avalonia, Avalonia.Desktop, Avalonia.Diagnostics, Avalonia,ReactiveUI, Avalonia.Win32.Interoperability.
3. Open a form.
4. Open the toolbox.
5. Drag the WinFormsAvaloniaControlHost onto a form.

**Expected behavior**
The interop control appears on the form.

** Actual behavior **
The error shown above appears.

**Screenshots**
This is the error I get:
![image](https://user-images.githubusercontent.com/2612506/125176240-00d66680-e1a0-11eb-8838-bd6ffb1c1ea7.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Home
- Version  0.10.6

**Additional context**
N/A

**Comment by kekekeks** [comment]
I think it's be unavailable in winforms design-mode since Avalonia has to be initialized before use.

**Comment by ekolis** [comment]
Oh, so I need to create it in code and place it on the form that way?

**Comment by kekekeks** [comment]
Yes. Also manual renderer lifetime control is needed and is currently has to be done in an obscure way:
https://github.com/AvaloniaUI/Avalonia/issues/4951#issuecomment-728763898
