### ISSUE TITLE
DataGrid is always empty

### ISSUE THREAD

**Issue by yellowsink** [AvaloniaUI/Avalonia#6236]
**Describe the bug**
`<DataGrid />` never has any content - it just appears to stay as an empty component.

**To Reproduce**
1. Create a DataGrid in XAML
2. Either bind `Items` to a viewmodel, or add items via code-behind
3. The given items will not show at all

**Expected behavior**
The data bound to `Items` is used to create a table of information.

**Screenshots**
![image](https://user-images.githubusercontent.com/19270622/125208924-5b99bc00-e28d-11eb-8c60-b9d7e0b8b297.png)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version `0.10.6`

**Additional context**
Have tested with and without MVVM, have tested with and without custom columns, have tested with both fields and properties for the member in objects given.

Basically what I wrote on top of the MVVM template:

Class:
```cs
public class Song
{
	public string Name;
	public string Artist;
	public string Album;

	public Song(string name, string artist, string album)
	{
		Name   = name;
		Artist = artist;
		Album  = album;
	}
}
```

In ViewModel:
```cs
public class MainWindowViewModel : ViewModelBase
{
	private SourceList<Song> _songs = new();

	public SourceList<Song> Songs
	{
		get => _songs;
		set => this.RaiseAndSetIfChanged(ref _songs, value);
	}
}
```

In constructor:
```cs
public MainWindow()
{
	DataContext = new MainWindowViewModel();
	
	InitializeComponent();
#if DEBUG
	this.AttachDevTools();
#endif

	((MainWindowViewModel) DataContext!).Songs.Add(new("Start Again", "ONE OK ROCK", "Ambitions"));
```

In XAML
```xml
<DataGrid Items="{Binding Songs.Items}" AutoGenerateColumns="False">

	<DataGrid.Columns>
		<DataGridTextColumn Header="Song" Binding="{Binding Name}" />
		<DataGridTextColumn Header="Artist" Binding="{Binding Artist}" />
		<DataGridTextColumn Header="Album" Binding="{Binding Album}" />
	</DataGrid.Columns>
		
</DataGrid>
```

**Comment by wieslawsoltes** [comment]
Did you add styles in your App.axaml ?

```XAML
<Application.Styles>
    <StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Default.xaml"/>
</Application.Styles>
```
or
```XAML
<Application.Styles>
    <StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Fluent.xaml" />
</Application.Styles>
```

https://docs.avaloniaui.net/docs/controls/datagrid#add-required-styles-to-app-axaml

**Comment by yellowsink** [comment]
Thank you!

**Comment by yellowsink** [comment]
Though the columns etc show, the datagrid still fails to show anything

**Comment by yellowsink** [comment]
hmm no it appears that this component is really really specific about how you use it? very weird...

**Comment by maxkatz6** [comment]
It's not really really specific. Can you share any project how are you trying to do it?
Code pieces from above are fine and probably not enough to see the problem.

Although I don't know about SourceList and what type SourceList.Items is.

**Comment by yellowsink** [comment]
Yeah i'm kinda trying to experiment around with it. SourceList is part of DynamicData / ReactiveUI

**Comment by yellowsink** [comment]
ok ill put my code in a repo - working in a minimal test project right now

**Comment by yellowsink** [comment]
https://github.com/yellowsink/dgtest

**Comment by yellowsink** [comment]
the [change notifications](https://docs.avaloniaui.net/docs/data-binding/change-notifications) page suggests that dynamicdata works but i couldnt find any working examples

**Comment by yellowsink** [comment]
well i kinda can make it work but its janky

**Comment by maxkatz6** [comment]
Your project works for me fine. What exactly is your problem?

**Comment by maxkatz6** [comment]
Checked your previous code on the branch. I don't see any problems with Avalonia.
But it seems you are using SourceList wrong.
You bind to SourceList.Items, which IS NOT bindable property in ReactiveUI (or DynamicData). Neither SourceList implements INotifyPropertyChanged.
Check its documentation https://www.reactiveui.net/docs/handbook/collections/#how-to-use-it
In DataGrid you should use ObservableCollection for that task or anything else that implements INotifyCollectionChanged.

**Comment by yellowsink** [comment]
Ohhhhhh I didnt realise how dynamicdata worked. Thank you so much, and sorry if I wasted your time.
