### ISSUE TITLE
Window Startup Location

### ISSUE THREAD

**Issue by Seeker1437** [AvaloniaUI/Avalonia#624]
It would be a nice feature to be able to start windows in the center of the screen.

WPF had 

CenterScreen - The startup location of a Window is the center of the screen that contains the mouse cursor.
CenterOwner - The startup location of a Window is the center of the Window that owns it, as specified by the Window.Owner property.
Manual - The startup location of a Window is set from code, or defers to the default Windows location.

**Comment by KvanTTT** [comment]
MSDN link: https://msdn.microsoft.com/en-us/library/system.windows.window.windowstartuplocation(v=vs.110).aspx

**Comment by MarqueIV** [comment]
I'm running Avalon Beta 0.6.1 (just downloaded today, Aug 31, 2018) and this feature is still missing.  I thought it said it was merged, or am I misunderstanding something?

**Comment by Kryptos-FR** [comment]
It was merged on March 2nd 2018 but the beta was released on February 19th Looks like it missed the beta release.

**Comment by MarqueIV** [comment]
OOOOooooh!!!  For some reason I thought the beta was just released within the past month or so.  Ok, well hopefully there will be a new one soon. (I tried pulling from the nightlies but it didn't see to work for me.  I'll try and triage that later.)
