### ISSUE TITLE
ListBox.AutoScrollToSelectedItem does not scroll to the selected item when the selected item is updated just after new rows were added

### ISSUE THREAD

**Issue by IvaYan** [AvaloniaUI/Avalonia#6263]
Hello.
I'm trying to make ListBox scroll to a newly added item.

Consider the following code:

```C#
private void AddRowsImpl()
{
    for (var i = 0; i < 10; ++i)
    {
        var row = new RowViewModel { ...};
        
        Rows.Add(row);
    }

    SelectedRow = Rows[^1];
}
```

As we can see we first add items and then make the last one selected. Although the correct item is selected, the ListBox scrolls to the very beginning.

ListBox is created like this:

```XAML
<ListBox Grid.Row="1"
                 AutoScrollToSelectedItem="True"
                 SelectedItem="{Binding SelectedRow, Mode=TwoWay}"
                 VirtualizationMode="None"
                 Items="{Binding Rows}">
```

If we select an item without adding new rows, the ListBox scrolls correctly. The reason might be is that the ListBox does not have ListBoxItem's for the new rows yet.

I managed to dig deeper until found this method:

```C#
internal class ItemVirtualizerNone : ItemVirtualizer
    public override void ScrollIntoView(int index)
    {
        if (index != -1)
        {
            var container = Owner.ItemContainerGenerator.ContainerFromIndex(index);
            container?.BringIntoView();
        }
    }
}
```

with a debugger I managed to see that index is not -1 and `container` is not null, and `BringIntoView()` is actually called, but seems to have no effect.

I have attached a sample project that represents the problem. You need to click the "Add Rows" button. It is expected the ListBox to scroll to the last item.

[mve.zip](https://github.com/AvaloniaUI/Avalonia/files/6826516/mve.zip)

**Comment by timunie** [comment]
Probably this fix https://github.com/AvaloniaUI/Avalonia/pull/9174 can work for the ListBox-Issue as well, in case anyone wants to address this issue.

**Comment by workgroupengineering** [comment]
I try with last ef55b065c3119d233acd44e833bbd1c0b7bc9911 and issue is still present. Now Scroll last item idnex - 1.

**Comment by timunie** [comment]
Does calling the Dispatcher help? Probably it needs some ms to update the Items first?

**Comment by workgroupengineering** [comment]
I tryed, but issue persist.
