### ISSUE TITLE
Avalonia for Visual Studio - F# Avalonia Application template issues

### ISSUE THREAD

**Issue by bent-rasmussen** [AvaloniaUI/Avalonia#6264]
**Describe the bug**
Using Avalonia for Visual Studio and the trying out the F# templates, they appear to be broken with multiple build errors out of the box (see list of errors below). Affected templates:

*  F# Avalonia Application
*  F# Avalonia MVVM Application

As an F# user I'd tend to lean towards Avalonia.FuncUI - but I'm just surveying the available templates and how they work. I'd probably recommend a fix-or-remove action for these templates. :-) Unless of course I'm doing something silly that breaks them out of the box.

**To Reproduce**
Install [Avalonia for Visual Studio](https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaforVisualStudio) extension 0.10.3.0

1. Select "Create a new project"
2. Select "F# Avalonia Application"
3. Select "Next"
4. Select "Create"
5. Build solution (build twice before VS shows actual errors ```¯\_(ツ)_/¯ ```)

**Expected behavior**
No build errors out of the box.

**Screenshots**
Not needed.

**Desktop (please complete the following information):**

- OS: Windows 10
- Extension Version 0.10.3.0
- Visual Studio 2019 (16.10.2)

**Additional context**

***F# Avalonia Application errors:***

```
Severity	Code	Description	Project	File	Line	Source	Suppression State
Error	FS0039	The type 'MainWindow' does not define the field, constructor or member 'AttachDevTools'.	AvaloniaApplication5	...\AvaloniaApplication5\AvaloniaApplication5\MainWindow.xaml.fs	10	Build	N/A
Error	FS0039	The namespace 'Serilog' is not defined.	AvaloniaApplication5	...\AvaloniaApplication5\AvaloniaApplication5\Program.fs	3	Build	N/A
Error	FS0501	The member or object constructor 'LogToDebug' takes 2 argument(s) but is here given 0. The required signature is '(extension) AppBuilder.LogToDebug<'T when 'T : (new : unit -> 'T) and 'T :> Controls.AppBuilderBase<'T>>(?level: Logging.LogEventLevel, [<ParamArray>] areas: string []) : 'T'.	AvaloniaApplication5	...\AvaloniaApplication5\AvaloniaApplication5\Program.fs	8	Build	N/A
```

***F# Avalonia Application fixes:***

`Program.fs` - see inline comments

```fsharp
open System
open Avalonia
//FIXED: open Avalonia.Logging.Serilog - namespace not found - using Avalonia.LoggingExtensions
open AvaloniaApplication4

[<CompiledName "BuildAvaloniaApp">] 
let buildAvaloniaApp () = 
    AppBuilder.Configure<App>()
              .UsePlatformDetect()
              //FIXED: .LogToDebug() - deprecated, should use LogToTrace
              .LogToTrace(Logging.LogEventLevel.Information) //FIXED

[<STAThread>][<EntryPoint>]
let main argv =
    buildAvaloniaApp().StartWithClassicDesktopLifetime(argv)
```

`MainWindow.xaml.fs` - see inline comment

```fsharp
namespace Views

open Avalonia
open Avalonia.Controls
open Avalonia.Markup.Xaml

type MainWindow () as self = 
    inherit Window ()
    #if DEBUG
    do self.AttachDevTools() //FIXED: added reference to Avalonia.Diagnostics Nuget package
    #endif
    do AvaloniaXamlLoader.Load self
```

Upgrade Avalonia Nuget packages to latest version.

***#F Avalonia MVVM Application errors:***

Same as with non-MVVM template, as well as:

```
Severity	Code	Description	Project	File	Line	Source	Suppression State
Error	FS0859	No abstract property was found that corresponds to this override	AvaloniaApplication6	...\AvaloniaApplication6\AvaloniaApplication6\ViewLocator.fs	10	Build	N/A
```

***#F Avalonia MVVM Application fixes:***

Same as with non-MVVM template, as well as:

`ViewLocator.fs` - see inline comment

```fsharp
namespace AvaloniaApplication6

open System
open Avalonia.Controls
open Avalonia.Controls.Templates
open ViewModels

type ViewLocator () =
    interface IDataTemplate with
        //FIXED (no abstract property was found that corresponds to this override): member __.SupportsRecycling with get() = false
        member __.Match data = data :? ViewModelBase
        member __.Build data : IControl =
            let name = data.GetType().FullName.Replace("ViewModel", "View")
            let type' = Type.GetType name
            if type' <> null then
                Activator.CreateInstance(type') :?> IControl
            else
                TextBlock(Text = "Not Found: " + name) :> IControl
```

Upgrade Avalonia Nuget packages to latest version.

**Comment by FoggyFinder** [comment]
Related: #5992
