### ISSUE TITLE
Error: Unable to Start on Linux (EndOfStreamException)

### ISSUE THREAD

**Issue by nlogozzo** [AvaloniaUI/Avalonia#6287]
**Describe the bug**
Sometimes when I go to run my project it works without errors and sometimes when I go to run it, I get just a blank terminal with no window and no error. I find the error below on the Avalonia tab at the bottom of my Rider IDE.
```
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.ReadExact(Byte[] buffer) in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 59
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.Reader() in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 71
```

**To Reproduce**

1. Download Zip [NickvisionApp.zip](https://github.com/AvaloniaUI/Avalonia/files/6855983/NickvisionApp.zip)
2. Open the sln in Rider on Linux or another C# IDE if you have.
3. Run the program. If it runs and opens a window, close the program and run it again.
4. See how no window shows and no error is displayed (If you have AvaloniaRider installed, you can see an Avalonia tab in the Rider IDE which displays the error I showed above.

**Expected behavior**
The MainWindow should show and display on the screen.

**Desktop**
Occurs on both Cinnamon 5 and GNOME 40 desktops on an up-to-date Arch Linux install.
Framework Versions: Avalonia 0.10.6, [FluentAvalonia](https://github.com/amwx/FluentAvalonia) 1.0.7

Side Note: The application has no issues and runs just fine under Windows

**Comment by nlogozzo** [comment]
I think this could be an issue with FluentAvalonia...

**Comment by nlogozzo** [comment]
Tuns out it has nothing to do with Avalonia...something wrong with json serialization

**Comment by kekekeks** [comment]
EndOfStreamException in BsonStreamTransportConnection means that designer process has either crashed or exited before Rider plugin considered closing connection. You can safely ignore that.
