### ISSUE TITLE
Add LocationChanged event to TopLevel

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#629]
I'm trying to get popup to move with its target,

In WPF this could be achieved like so.

http://stackoverflow.com/questions/5736359/popup-control-moves-with-parent

but TopLevel is missing LocationChanged event. If someone can give me some pointers I might be able to do this my selft, just not sure exactly where to trigger the event from, and with what values.

Unless Avalonia can do this in a much simpler way?

**Comment by OronDF343** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/683
