### ISSUE TITLE
Implement MultiDataTrigger like WPF in Style

### ISSUE THREAD

**Issue by Mochengvia** [AvaloniaUI/Avalonia#6291]
I can't implement a function similar to the MultiDataTrigger in the Avalonia Style. 
In WPF, it looks like: 

```
<MultiDataTrigger>
    <MultiDataTrigger.Conditions>
        <Condition Binding="{Binding IsPressed, RelativeSource={RelativeSource Self}, Mode=OneWay}"
                   Value="True" />
        <Condition Binding="{Binding Path=(local:CustomHelper.PressedForeground), Converter={StaticResource {x:Static IsNonnullConverter}}, RelativeSource={RelativeSource Self}, Mode=OneWay}"
                   Value="True" />
    </MultiDataTrigger.Conditions>
    <Setter TargetName="BdrMain"
            Property="Background"
            Value="{Binding Path=(local:CustomHelper.PressedForeground), RelativeSource={RelativeSource TemplatedParent}, Mode=OneWay}" />
</MultiDataTrigger>
```

Is there a similar implementation in Avalonia?

**Comment by pr8x** [comment]
Triggers and Behaviors are covered by https://github.com/wieslawsoltes/AvaloniaBehaviors

**Comment by Mochengvia** [comment]
I saw that this library implements something similar to DataTrigger, but I did not find anything similar to MultiDataTrigger. Moreover, I’m not sure that this can be used to change the Selector

**Comment by Mochengvia** [comment]
I saw that this library implements something similar to DataTrigger, but I did not find anything similar to MultiDataTrigger. Moreover, I’m not sure that this can be used to change the Selector

**Comment by maxkatz6** [comment]
1. You can define class having boolean binding:
```xaml
<Border Classes.my-class="{Binding Property, Converter={x:Static Converter}}" />
```

2. Then you can combine selectors in styles:
```xaml
<Style Selector="Border[IsPressed=True].my-class">
   <Setter />
</Style>
```

It's not exactly the same, but allow to implement quite a lot.

> but I did not find anything similar to MultiDataTrigger. Moreover, I’m not sure that this can be used to change the Selector

To change property - use ChangePropertyAction, to set class (and trigger style selector) - use AddClassAction.
I am not sure if there are composite triggers with Or/And conditions, but I would expect it. @wieslawsoltes

**Comment by Mochengvia** [comment]
After a series of failed experiments, it succeeded.
I will record the solution here for later beginners .

**Comment by Mochengvia** [comment]
What I'm trying to do is to bind a ClickBackground property and a HoverBackground property to the Border in the Button (if they are not Null), and trigger the background color change when the button is hovered or clicked.
These are the key parts of the code: 

![image](https://user-images.githubusercontent.com/23360265/126730958-f872bce4-c3c5-447f-a1e4-ad1964b62324.png)

![avalonia-button](https://user-images.githubusercontent.com/23360265/126731069-7f3ddf4b-882c-47a0-a8ae-f355d9ac3298.gif)

**Comment by maxkatz6** [comment]
Instead of ```{StaticResource IsNotnullConverter}``` you can use ```{x:Static ObjectConverters.IsNotNull}``` - build in converter.
