### ISSUE TITLE
GridLinesBrush in DataGrid does not work

### ISSUE THREAD

**Issue by Mochengvia** [AvaloniaUI/Avalonia#6292]
Avalonia version: 0.10.6
OS: Windows 10

Here is my code:
![image](https://user-images.githubusercontent.com/23360265/126727695-2ddf3569-831f-40ac-87a2-6ca0e8f36538.png)

Here is the effect:
![image](https://user-images.githubusercontent.com/23360265/126727650-52254bd1-d7f7-425c-8297-6ec4338f3c54.png)

In any case, the color of the grid lines will be forced to be set to white.

**Comment by FoggyFinder** [comment]
I wasn't able to replicate. Are you sure you have 

```xml
 <Setter Property="GridLinesVisibility" Value="All" />
```

?
