### ISSUE TITLE
ToolTip from non-focused window should not show (and focus the window)

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#6294]
**Describe the bug**
When I have two windows A and B and have B focused and hover a control in A with a ToolTip it will actually activate/focus A. That seems wrong.

**Expected behavior**
Would expect that it only shows ToolTips from windows that are focused.

**Desktop**

- OS: Windows 10
- Version master

**Comment by Gillibald** [comment]
Open up the Explorer then Open up Notepad and type something. Then just hover over some files in the Explorer and it will show ToolTips. It should still not activate the Explorer window.

**Comment by pr8x** [comment]
Tried with multiple instances of explorer and it didn't show. But yeah, the focusing seems wrong.
