### ISSUE TITLE
TextBox Header

### ISSUE THREAD

**Issue by nlogozzo** [AvaloniaUI/Avalonia#6297]
Can we see a Header (a.k.a Title) property for the TextBox, similarly to how we have the watermark property, that would display above the TextBox
As seen here: [Header Property WinUI](https://www.reflectionit.nl/Images/Blog/Windows10/HeaderTemplate/header.png)

**Comment by maxkatz6** [comment]
Use Label control.
```xaml
<Label Target="MyTextBox" Content="Header" />
<TextBox x:Name="MyTextBox" />
```

Label is way more flexible than having Header/Description as part of text box template.

**Comment by nlogozzo** [comment]
@maxkatz6 Obviousky I've been using a label lol. But it's annoying creating a lebel for each TextBox when I'm doing nothing fancy besides adding some simple text that could be achieved with the header property.

**Comment by maxkatz6** [comment]
@nlogozzo you can create style for TextBox with custom template (copying existing template and adding label/textblock there, reading header value from Tag or custom attached property).
Having UWP background, I agree with you that this property is useful, but it also it was quite limiting.
