### ISSUE TITLE
(Fluent) Tooltip does not auto size to content

### ISSUE THREAD

**Issue by 0x90d** [AvaloniaUI/Avalonia#6305]
**Describe the bug**
I'm using Fluent design and tooltip does not change width/height based on its content. 

**To Reproduce**

```
<Image ToolTip="Bla" ....
<ToolTip.Tip>
                        <Border>
                            <Image Source="{Binding Image}" Stretch="None">
                                <Image.RenderTransform>
                                    <ScaleTransform ScaleX="2" ScaleY="2"  />
                                </Image.RenderTransform>
                            </Image>
                        </Border>
                </ToolTip.Tip>
</Image>
```

**Expected behavior**
In WPF image is scaled properly and is fully visible. In Avalonia image is scaled properly but its zoomed in. I believe the image was scaled AFTER tooltips width and height were set. If there is any workaround please let me know.

**Screenshots**
WPF
![image](https://user-images.githubusercontent.com/46010672/126998436-0bbb56f8-b5e8-4b4e-9625-e6c628e43569.png)
Avalonia Fluent
![image](https://user-images.githubusercontent.com/46010672/126998502-abc5c843-3e17-46de-8b15-55d5eadffda2.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.999-cibuild0014036-beta

**Comment by kekekeks** [comment]
You probably want `LayoutTransformControl`  since render transform _does not affect layout_.

**Comment by 0x90d** [comment]
Thanks!
