### ISSUE TITLE
ContentTemplate in Window does not work

### ISSUE THREAD

**Issue by Mochengvia** [AvaloniaUI/Avalonia#6307]
Avalonia version: 0.10.6
Windows version: Windows 10

Source code:
```
<Style Selector="Window">
    <Setter Property="ExtendClientAreaToDecorationsHint" Value="True" />
    <Setter Property="ExtendClientAreaChromeHints" Value="NoChrome" />
	<Setter Property="ExtendClientAreaTitleBarHeightHint" Value="-1" />
	<Setter Property="ContentTemplate">
	    <Setter.Value>
		<DataTemplate>
		    <Grid>
		        <Grid.RowDefinitions>
		            <RowDefinition Height="Auto" />
		            <RowDefinition />
		        </Grid.RowDefinitions>
		        <Border Background="Red" Height="35" Width="100"/>
			<ContentControl Grid.Row="1" Content="{Binding}"/>
		     </Grid>
		</DataTemplate>
	</Setter.Value>
     </Setter>
</Style>
```

Effect: 
![image](https://user-images.githubusercontent.com/23360265/127114526-b00ac884-0c01-47f9-8e45-69741b434d14.png)

Nothing seems to happen, even if I delete the ContentControl.

**Comment by maxkatz6** [comment]
I believe it should be :is(Window) instead of Window, to match all types inherited from Window

**Comment by Mochengvia** [comment]
I have changed my code, but nothing happened.
It's strange that if I create a clean project and apply the same style code to Window, it will take effect : 
![image](https://user-images.githubusercontent.com/23360265/127250059-53416953-43f1-4faa-8934-4a8674623a90.png)

Here is code of my view:
![image](https://user-images.githubusercontent.com/23360265/127251130-417b124a-5c71-4269-8a77-28a5949318bf.png)

I have removed my Styles from App.xaml:
![image](https://user-images.githubusercontent.com/23360265/127251169-2bf0df97-d3bb-4302-87d0-58298b377a52.png)

What it looks like:
![image](https://user-images.githubusercontent.com/23360265/127251232-f8ed53ab-68c9-4acd-b999-b803fdf912c8.png)

If anyone can provide some possible suggestions, I will try again.

**Comment by maxkatz6** [comment]
We now have styles troubleshooting documentation page, which might help here.
Since it works in the new app, I assume there is something wrong with the app or styles definition order specifically.
https://docs.avaloniaui.net/docs/styling/troubleshooting
