### ISSUE TITLE
NativeControlHost will make the window transparent.

### ISSUE THREAD

**Issue by sudongg** [AvaloniaUI/Avalonia#6308]
**Describe the bug**
After setting ExtendClientAreaToDecorationsHint="True", adding NativeControlHost will make the window transparent.

**To Reproduce**
1.  New Avalonia Application
2.  Add ExtendClientAreaToDecorationsHint="True" in MainWindow.axaml
2.  Add `<NativeControlHost` `x:Name="NativeControlHost"/>` in MainWindow.axaml
3.  Run
4.  The window will become transparent and only the border will be visible.

**Expected behavior**
The window will not become transparent and will have a black background.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version [e.g. 0.10.6]

**Additional context**

**Comment by maxkatz6** [comment]
Should be fixed with https://github.com/AvaloniaUI/Avalonia/pull/7111#event-5742276207

If with next release this issue will still occur, please leave a comment

**Comment by sudongg** [comment]
I tested 0.10.11  Version, the problem has not been fixed.
