### ISSUE TITLE
Implement Popup.AllowTransparency if possible

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#631]
Wpf popup supports transparency if it is explicitly enabled and run in full trust mode. Perhaps Avalonia can implement this by default? Or it might not be technically possible?

**Comment by kekekeks** [comment]
At least on Windows transparent windows involve WS_EX_LAYERED style and updates using `UpdateLayeredWindow` which in turn requies GDI Bitmap as its source. So transparency is kinda expensive from performance point of view and will require lots of changes in renderer for Direct2D and hw-accelerated Skia. For sw-skia we can just replace `SetDIBItsToDevice` with `CreateDIBSection` in our "framebuffer implementation.

**Comment by maxkatz6** [comment]
@danwalmsley can it be closed now?
This seems to solve the problem on Win32. Not sure if it was a problem on OSX or Linux:
https://github.com/AvaloniaUI/Avalonia/pull/4036
