### ISSUE TITLE
Code error in Avalonia.Themes.Default/TabControl.xaml

### ISSUE THREAD

**Issue by Mochengvia** [AvaloniaUI/Avalonia#6318]
I found a code error in master branch, at Avalonia.Themes.Default/TabControl.xaml

![image](https://user-images.githubusercontent.com/23360265/127443500-6f084c36-3b56-447f-9344-a4e26b04e684.png)

This line should be removed, it will cause Margin to overlap repeatedly.

**Comment by maxkatz6** [comment]
> it will cause Margin to overlap repeatedly

Not sure if I understand it. You mean, it will double the margin?

**Comment by H0tCh0colat3** [comment]
> You mean, it will double the margin?

Can confirm. Margin appears to be double what it should be. Also occurs in Fluent Theme as far as I know. The following code can reproduce the issue:

```
<Grid>
  <Grid Background="Orange" Margin="25" VerticalAlignment="Stretch" Name="Reference"/>
  <TabControl Background="LightGreen" Margin="25" VerticalAlignment="Stretch">
    <TabItem Header="Tab 1"></TabItem>
    <TabItem Header="Tab 2"></TabItem>
    <TabItem Header="Tab 3"></TabItem>
  </TabControl>
</Grid>
```

The grid named "Reference" (orange) shows what a margin of 25 should look like. Compare with the tab control (green) which has its margin doubled.

![tab control](https://user-images.githubusercontent.com/32641956/127758501-78779ef9-3271-4918-9ea4-5fb4e9dea60c.PNG)

**Comment by maxkatz6** [comment]
Ok, this Margin should be removed, since control add it automatically

**Comment by Gillibald** [comment]
Can you replace Grid with a Panel? Does it change anything?

**Comment by maxkatz6** [comment]
> Edit: There are scenarios where you don't want properties to apply to the entire control itself. For example, controls that have multiple distinct areas like Expander (both Header and Content). It is common that you don't want properties like Margin or Background to apply to both the Header and the Content areas. Instead it should apply to the Content area and new properties added for the Header. Decisions like this can only be made on a per-control basis and this is why it is all done in the default styles from what I've seen in the past. Having control automatically add a Margin generically is bad.

I would agree for many other properties, such as background or corner radius - they are already included only in the template per control. 
But Margin? As for me it's similar to properties like Width/Height that are expected to be applied only in single possible way, not depending on the control itself. Including mentioned Expander. There is difference comparing to the Padding, which actually depends on the control and can't be applied automatically.

**Comment by robloo** [comment]
@maxkatz6 I can't find a counterexample so you may be right. My initial (and gut) thinking is to treat all properties the same. Of course my example really only works for Padding, Background, etc. As Margin directly affects the practical height/width of the control (as the user sees it) there is another good argument in your favor.

I also thought UWP behaves the way I described. However, I just searched all control templates and only found one `Margin="{TemplateBinding Margin}` case. This is for the `NavigationViewItemPresenter` used in the `ControlTemplate` of the `NavigationViewItem` and it may be a special case.

It is counter-intuitive for me to treat Margin different from other properties. However, the logic in doing so makes sense. I need to backtrack on my statements and you are likely correct. :)
