### ISSUE TITLE
Strange effects when drawing geometry with LinearGradientBrush 

### ISSUE THREAD

**Issue by Mochengvia** [AvaloniaUI/Avalonia#6319]
Avalonia version : v0.10.6
Windows 10

```
var linearBrush = new LinearGradientBrush()
{
    StartPoint = new RelativePoint(0, 0, RelativeUnit.Relative),
    EndPoint = new RelativePoint(0, 1, RelativeUnit.Relative),
};
linearBrush.GradientStops.Add(new GradientStop(Colors.Red, 0));
linearBrush.GradientStops.Add(new GradientStop(Colors.Blue, 1));

drawingContext.DrawGeometry(linearBrush, null, Geometry.Parse($"M100,100 L 110,110 L 120, 90 L 130,150 L140,160 V 200 H 100 Z"));
```

As shown in the picture, the entire area is covered by blue.

![image](https://user-images.githubusercontent.com/23360265/127464488-84e87957-15f3-497c-ac8f-4c18387ce7da.png)

**Comment by grokys** [comment]
Might be fixed by https://github.com/AvaloniaUI/Avalonia/pull/6066 which should be included in 0.10.7 (should be released in the next few days).
