### ISSUE TITLE
OpenFolderDialog crashing application

### ISSUE THREAD

**Issue by imerzan** [AvaloniaUI/Avalonia#6331]
https://github.com/AvaloniaUI/Avalonia/blob/9dbcc98a8709d8b185f6f0dc69df19e6873cb97c/src/Windows/Avalonia.Win32/SystemDialogImpl.cs#L112

I keep getting an exception thrown at this location when attempting to execute .ShowAsync() on a FolderOpenDialog. Here is a summary of my code:
```
private OpenFolderDialog dialog_Source; // Field
{
dialog_Source = new OpenFolderDialog();
dialog_Source.Title = "Select User Folder";
var path = await dialog_Source.ShowAsync(this);
}
```

Runs fine on Win10 x64, and macOS Big Sur (even in Recovery Mode), but I cannot get this to run in Windows PE. I have run other .NET Core apps fine in this environment, so I know it *should* be possible. Running this as a self-contained deployment so it should have all the dependencies. Any ideas?

Exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass2_0.<ShowFolderDialogAsync>b__0() in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 112
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UserBackup.MainWindow.click_button_Source(Object sender, RoutedEventArgs e) in ....MainWindow.axaml.cs:line 87
```

**Comment by Splitwirez** [comment]
@imerzan Does it still fail if you use the managed system dialogs?

**Comment by imerzan** [comment]
@Splitwirez I can check. Is this implemented within Avalonia or do you mean checking `Microsoft.Win32.OpenDileDialog` ?

**Comment by Splitwirez** [comment]
> @Splitwirez I can check. Is this implemented within Avalonia or do you mean checking `Microsoft.Win32.OpenDileDialog` ?

@imerzan It's a feature within Avalonia - there's an extension method called `UseManagedSystemDialogs()` in the `Avalonia.Dialogs` namespace. Just add that to your AppBuilder.

(You'll find that in the form of the `BuildAvaloniaApp()` function in `Program.cs`, unless you've moved it or something)

~~Side note: Loosely speaking, `Microsoft.Win32.FolderBrowserDialog` is more or less the *opposite* of the managed system dialogs.~~

Also, I should probably clarify: although this may allow you to band-aid your way around the initial problem, I'm not entirely certain whether that initial problem is expected under WinPE or a bug of some sort...

**Comment by imerzan** [comment]
OK, I was able to get that to build.

Runs in WinPE, and the folder open dialog opens without any issues, but it appears to be a really archaic interface that doesn't have much functionality.

Trying to get the updated Win7/10 interface since it allows for click-to-unlock on Bitlocker Locked Drives where it automatically prompts for a Bitlocker Recovery Key. The Managed Dialog doesn't appear to have it.

I'm guessing WinPE is missing a system dependency of some sort for the Avalonia Interface, not sure how I could maybe pack it in with my self-contained app.

**Comment by Splitwirez** [comment]
> @Splitwirez OK, I was able to get that to build.
> 
> Runs in WinPE, and the folder open dialog opens without any issues, but it appears to be a really archaic interface that doesn't have much functionality.

@imerzan Yeah, I don't disagree there. That UI is provided by Avalonia itself, and well...I've tried to improve it a bit since the 0.10.x releases, but I'm not sure those improvements would be enough for your use case...



> Trying to get the updated Win7/10 interface since it allows for click-to-unlock on Bitlocker Locked Drives where it automatically prompts for a Bitlocker Recovery Key. The Managed Dialog doesn't appear to have it.

...BitLocker whatnow? Yeah I fear that's...likely beyond my capabilities, unfortunately :C

> I'm guessing WinPE is missing a system dependency of some sort for the Avalonia Interface, not sure how I could maybe pack it in with my self-contained app.

Not sure if that's a thing you can do, nor how, but...best of luck in your search. Hopefully someone else here will have a more...satisfactory answer/solution to offer.

**Comment by imerzan** [comment]
> ...BitLocker whatnow? Yeah I fear that's...likely beyond my capabilities, unfortunately :C

Yeah, its a System Management tool I'm building for my org, we have a lot of systems with full disk encryption (bitlocker).
When using the native Windows File Explorer if you try access a locked disk it will give the Key Identifier and prompt for a recovery key to be entered.
I currently have the tool working via .NET5 (Console) but trying to port it to a GUI.

Most likely encountering a WinPE limitation. Appreciate the help :)
