### ISSUE TITLE
ItemVirtualizer null exception when disposing ListBox

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#634]
I have a repro that can produce this exception.

https://github.com/AvaloniaUI/Avalonia/blob/4ee4ec29be9236e5969578300dea0e5eb841d9b5/src/Avalonia.Controls/Presenters/ItemVirtualizer.cs#L188

It crashes because Controller is null.

**Comment by donandren** [comment]
I'm experiencing that also today

**Comment by danwalmsley** [comment]
My workaround was to disable Virtualization on the ListBox,

I think it happens if the Virtualization didn't happen, but listbox got rendered, so I think it just needs a null check, but would like @grokys to check he agrees that is the correct fix.

**Comment by danwalmsley** [comment]
Posting repo instructions in a min.

**Comment by danwalmsley** [comment]
Don't you need to check if controller is null also?
