### ISSUE TITLE
Add Transform and RelativeTransform properties for Brush'es

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#6343]
**Is your feature request related to a problem? Please describe.**

Add support for `Transform` and `RelativeTransform` (not sure if this one is needed) property for Brush'es (LinearGradientBrush, RadialGradientBrush and VisualBrush).

- [Brush.Transform Property](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.brush.transform?view=net-5.0)
- [Brush Transformation Overview](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/brush-transformation-overview?view=netframeworkdesktop-4.8)

**Describe the solution you'd like**

Add to Brush  two transformation properties: `Transform` and `RelativeTransform`. The properties enable rotate, scale, skew, and translate a brush's contents.

**Describe alternatives you've considered**

Did try manually transform brush properties, but that doesn't really work.

**Additional context**

It is very useful for example when converting Svg paint servers to Avalonia brushes. As paint server can use user space coordinates and bounding box coordinates and can have transform property set for brush transformations. Right now I am using LinearGradientBrush, RadialGradientBrush and VisualBrush and all of them require transform.

SkiaSharp support local matrix parameter when creating shaders for brushes:

- [CreateLinearGradient](https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skshader.createlineargradient?view=skiasharp-2.80.2#SkiaSharp_SKShader_CreateLinearGradient_SkiaSharp_SKPoint_SkiaSharp_SKPoint_SkiaSharp_SKColorF___SkiaSharp_SKColorSpace_System_Single___SkiaSharp_SKShaderTileMode_SkiaSharp_SKMatrix_)

- [CreateRadialGradient](https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skshader.createradialgradient?view=skiasharp-2.80.2#SkiaSharp_SKShader_CreateRadialGradient_SkiaSharp_SKPoint_System_Single_SkiaSharp_SKColorF___SkiaSharp_SKColorSpace_System_Single___SkiaSharp_SKShaderTileMode_SkiaSharp_SKMatrix_)

- [CreateTwoPointConicalGradient](https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skshader.createtwopointconicalgradient?view=skiasharp-2.80.2#SkiaSharp_SKShader_CreateTwoPointConicalGradient_SkiaSharp_SKPoint_System_Single_SkiaSharp_SKPoint_System_Single_SkiaSharp_SKColor___SkiaSharp_SKShaderTileMode_)

- [CreatePicture](https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skshader.createpicture?view=skiasharp-2.80.2#SkiaSharp_SKShader_CreatePicture_SkiaSharp_SKPicture_SkiaSharp_SKShaderTileMode_SkiaSharp_SKShaderTileMode_SkiaSharp_SKMatrix_SkiaSharp_SKRect_)

That is what I use for Svg rendering.

I am converting the svg brushes to WPF xaml here https://github.com/wieslawsoltes/SvgGradientsDemo for reference.

**Comment by maxkatz6** [comment]
Same issue https://github.com/AvaloniaUI/Avalonia/issues/5768

**Comment by wieslawsoltes** [comment]
> Same issue #5768

I should have searched issue before posting this.
