### ISSUE TITLE
Elements with fixed width and HorizontalAlignment set to Center not staying in the Grid column

### ISSUE THREAD

**Issue by D0ctorWh0** [AvaloniaUI/Avalonia#6345]
I have a grid with two columns. The right column contains StackLayout with TextBlock, TextEdit and Button with HorizontalAlignment set to Center. TextEdit also has Width set to a fixed value. When resizing form TextBlock and Button stays in the column, but TextEdit crosses left side of the column.

I experimented and noticed, that if I set the Width property for TextBlock and Button then they will not stay in the Grid column too.

Here is a gif of it:
[bug](https://ibb.co/k5ZRTDv)

Here is my XAML code:
```
<Grid HorizontalAlignment="Stretch">
  <Grid.ColumnDefinitions>
    <ColumnDefinition Width="*"/>
    <ColumnDefinition Width="*"/>
  </Grid.ColumnDefinitions>
  <Rectangle Grid.Column="0" Fill="Aqua"/>
  <Rectangle Grid.Column="1" Fill="Beige"/>
  <StackPanel VerticalAlignment="Center" Grid.Column="1" HorizontalAlignment="Center">
    <TextBlock Text="Hellow World!" HorizontalAlignment="Center"/>
    <TextBox x:Name="TextBox1" Grid.Column="0" Margin="0,10,10,10" Width="200" HorizontalAlignment="Stretch"/>
    <Button Content="Click me!" Name="Button1" HorizontalAlignment="Center" VerticalAlignment="Center"></Button>
  </StackPanel>
</Grid>
```

I am using Windows 10 x64 and Avalonia 0.10.6.

**Comment by maxkatz6** [comment]
But what is expected behavior? As for me everything is correct. 
You set strict "Width" to be "200", so it's ignoring available space.
You probably want "MaxWidth" with HorizontalAlignment="Stretch" instead.
Or, if you want content to be cropped, you need to set StackPanel ClipToBounds="True", so its content will be cropped.

**Comment by D0ctorWh0** [comment]
ClipToBounds looks like what I was thinking of. I was comparing it with WPF behaviour, which is clipping by default, but looks like Avalonia's behaviour is quite different from WPF. Sorry about creating issues about it, guess you get a lot of such from newbies.
