### ISSUE TITLE
Bindings to attached properties dont result in the property setter being called.

### ISSUE THREAD

**Issue by KieranDevvs** [AvaloniaUI/Avalonia#6346]
I've tried to add an attached property with the type of `object?` and then set the property with `{Binding SomethingFromTheViewModel}` and the property setter is never called. If you don't use a bind, i.e a literal value `a` (`ns:AttachedPropertyOwner.Property="a"`) then the setter is called.

To avoid any mistakes, I have created a blank app and copied and pasted the sample code from the documentation: https://docs.avaloniaui.net/docs/data-binding/creating-and-binding-attached-properties

A reproducible project solution can be provided if necessary.

**Comment by maxkatz6** [comment]
> A reproducible project solution can be provided if necessary.

Binding in attached properties works. Reproducible project is required.

**Comment by KieranDevvs** [comment]
> > A reproducible project solution can be provided if necessary.
> 
> Binding in attached properties works. Reproducible project is required.

You are correct, I don't know what I've done but everything seems to be working I can no longer reproduce it. I shall close this issue.
