### ISSUE TITLE
RichTextBox urgent need

### ISSUE THREAD

**Issue by dayAndnight2018** [AvaloniaUI/Avalonia#6348]
RichTextBox shall solve the performance problem of using stackPanel wrapped TextBlock to show color-decorated text. Now I could not find another way to achieve this need.

Both winform and wpf design all consider richtextbox control, why not offering one in avalonia?

**Comment by jmacato** [comment]
Simple, because RichTextBox is a freaking monster that needs to be implemented correctly. We are aware of it missing and @Gillibald is working his best to make it happen. So just sit back, relax and wait for it to be ready whenever it is ready.

**Comment by Gillibald** [comment]
For now use a `TextLayout` and override `Render` in a custom control. That way you will get styled text. Most likely end of August we will get a reworked FormattedText so this will be easier as well. Inlines support still needs several months of work.
