### ISSUE TITLE
Listbox have unselectable Items after Inserting a range of items

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#635]
Reproduction steps from branch https://github.com/donandren/Avalonia/commit/c7ff674cbfdb8f5d674772f0850cda0e01fc81af:

-  Start VirtualizationTest app

- Select Item 5

- Press Add Item (3 Items will be added after Item 5)

Items 6,7,8..17 are not selectable after mouse click

**Comment by grokys** [comment]
Fixed by #640
