### ISSUE TITLE
ListBox has invalid items after recreation of bound collection

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#636]
Reproduction steps from branch https://github.com/donandren/Avalonia/commit/c7ff674cbfdb8f5d674772f0850cda0e01fc81af:

- Start VirtualizationTest app

- Select Item 5

- Press Add Item (3 Items will be added after Item 5)

- Press Recreate

It's expected to have 20 items Recreated 0,1,2 .. 19,
but there are  10 more items after 'Recreated 19'.

**Comment by grokys** [comment]
Fixed by #640
