### ISSUE TITLE
Listbox flickers/disappears under Linux

### ISSUE THREAD

**Issue by hlewin** [AvaloniaUI/Avalonia#6360]
In this example, when scrolling, the content of the whole left card flickers/disappears under Linux. Windows seems to work fine.
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        d:DesignWidth="800" d:DesignHeight="450"
        x:Class="TopologyEditor.MainWindow"
        Title="MainWindow">

    <DockPanel Margin="10">
        <Border Classes="Card">
            <DockPanel VerticalAlignment="Stretch">
                <StackPanel DockPanel.Dock="Top">
                    <TextBlock Text="Test" />
                    <TextBlock Text="Test" />
                    <TextBlock Text="Test" />
                </StackPanel>
                <ListBox HorizontalAlignment="Left" ScrollViewer.VerticalScrollBarVisibility="Visible"
                         Items="{Binding Items}">
                    <ListBox.ItemTemplate>
                        <DataTemplate>
                            <TextBlock Padding="10 0" Text="{Binding Name}" />
                        </DataTemplate>
                    </ListBox.ItemTemplate>
                </ListBox>
            </DockPanel>
        </Border>
        <Border Classes="Card" HorizontalAlignment="Stretch">
        </Border>
    </DockPanel>
</Window>
```
![Screenshot_2021-08-03_11-00-22](https://user-images.githubusercontent.com/25082820/127988521-d9c53e44-86ee-40af-bb5a-7d197ecf572e.png)

**Comment by kekekeks** [comment]
Which GPU are you using? Please, show your glxinfo output.
Try disabling hardware acceleration by adding `.With(new X11PlatformOptions{UseGpu = false})` to your AppBuilder configuration.

**Comment by hlewin** [comment]
It is a GeForce GTX 650 Ti Boost. glxinfo is attached.
`UseGpu=false` fixes the problem.

[glxinfo.txt](https://github.com/AvaloniaUI/Avalonia/files/6924159/glxinfo.txt)

**Comment by Gao996** [comment]
On Linux systems, there is a TabControl and it becomes transparent as soon as the mouse is placed on it
I tried to add the above code but it is not easy to use
![image](https://user-images.githubusercontent.com/51224634/128319282-f0072db2-d80e-4996-a2fe-d25f95931c63.png)
