### ISSUE TITLE
RemoveRange in ItemContainerGenerator failing with ArgumentException

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#637]
RemoveRange in ItemContainerGenerator failing with ArgumentException
An item with the same key has already been added.
at https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Generators/ItemContainerGenerator.cs#L125

**Comment by donandren** [comment]
- Start VirtualizationTest app

- Select Item 2

- Press Add Item (3 Items will be added after Item 2)

- Press Remove Item (the last 3 new added items is expected to be removed)

Exception ArgumentException is thrown instead.

**Comment by grokys** [comment]
Fixed by #640
