### ISSUE TITLE
":is" selector should ignore "StyleKey" property and read real control type

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#6382]
**Is your feature request related to a problem? Please describe.**
Developer needs to inherit default control with its styles (so, override StyleKey to much original control), but then decides to apply additional styles to his new control, without affecting parent (so, can't use StyleKey type in the selector).

Right now, it's not possible to create these additional styles in convenient way - developer needs either use some other class/property as a marker of "inheritor-type" or copy-paste inherited control styles with modifying their selectors to match inheritor type.

It feels reasonable to use ":is" selector, as "is" keyword works in C#. But in fact Avalonia ":is" selector will ignore real type, if StyleKey was set.
Technically, it's not a problem to update ":is" selector behavior, but it will be a breaking change for anybody, who uses custom StyleKey and expects ":is" selector to use it instead. Although, we don't have such examples in Avalonia repo and I don't really know why somebody would need it.

See discussion: https://github.com/AvaloniaUI/Avalonia/discussions/6353

**Comment by grokys** [comment]
@Mikolaytis any reason for your thumbs down on this issue? Would this break things for you?

**Comment by maxkatz6** [comment]
I feel like it's not needed as much as before. Now there is no reason to change StyleKey, it should be enough to assign ControlTheme from another type.
Closing, cc @grokys
