### ISSUE TITLE
Textbox Style Border

### ISSUE THREAD

**Issue by Gao996** [AvaloniaUI/Avalonia#6388]
`    <Window.Styles>
        <Style Selector="TextBox:focus">
            <Setter Property="Text" Value="66666666"></Setter>
            <Setter Property="BorderBrush" Value="{x:Null}"></Setter>
            <Setter Property="BorderThickness" Value="0"></Setter>
        </Style>
    </Window.Styles>`

I set the style like this
The border of the textbox is still blue
But the text becomes 666 indicating that the style is set
What kind of problem is this, please give pointers
thanks

**Comment by Gao996** [comment]
solved!

https://github.com/AvaloniaUI/Avalonia/issues/6403

**Comment by trampster** [comment]
This is not fixed.
