### ISSUE TITLE
Linux TextBox Can not be displayed

### ISSUE THREAD

**Issue by Gao996** [AvaloniaUI/Avalonia#6403]
![image](https://user-images.githubusercontent.com/51224634/128976020-d8f9e05e-9fb6-4c73-8c8e-581f42ce5c6d.png)
This textbox cannot display content on linux

**Comment by maxkatz6** [comment]
Please, do not ignore issue template:
```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**
Add any other context about the problem here.

```

**Comment by maxkatz6** [comment]
Also https://github.com/AvaloniaUI/Avalonia/issues/5828

**Comment by Gao996** [comment]
> 请不要忽略问题模板：
> 
> ```
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> - OS: [e.g. Windows, Mac, Linux (State distribution)]
> - Version [e.g. 0.10.0-rc1 or 0.9.12]
> 
> **Additional context**
> Add any other context about the problem here.
> ```

OK Thanks!

**Comment by Gao996** [comment]
**Describe the bug**
TextBox Can not be displayed.

**To Reproduce**
my MainWindow Code
`SystemDecorations = SystemDecorations.None;
            CanResize = false;
            ExtendClientAreaToDecorationsHint = true;
            ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome;
            ExtendClientAreaTitleBarHeightHint = -1;
            this.PointerPressed += WindowPointerPressed;`
Just realized the style of the form, I don’t know why the textbox is not easy to use

**Expected behavior**
TextBox Show Content.

**Screenshots**
Just like the picture above, just a normal textbox.It's not easy to use only under linux

**Desktop (please complete the following information):**

- OS: [Linux ]
- Version [centos7]

**Additional context**
Thanks!

**Comment by Gao996** [comment]
And I don’t know why all the textboxes will display a blue border after being pressed.I tried to set it up but it doesn't work well.
<textbox:focus>
<setter "broderbrush" x:null>

**Comment by maxkatz6** [comment]
Don't know what's exactly wrong with text box. I remember some linux users might need to include additional fonts. See https://github.com/AvaloniaUI/Avalonia/issues/5828

And about your issue with border, see this discussion https://github.com/AvaloniaUI/Avalonia/discussions/6369

**Comment by Gao996** [comment]
Thanks!
Okay, all the problems are solved. The words are not displayed because the fonts are not quoted.
The value of SKTypeface is Null under linux system.
So I added the following code below:


Color:
![image](https://user-images.githubusercontent.com/51224634/129134896-b8773165-dbc2-4f25-bec1-dad7b39d2063.png)

**Comment by Gao996** [comment]
![image](https://user-images.githubusercontent.com/51224634/129134947-066689e3-2db7-4290-ba05-1fd31ab869be.png)
