### ISSUE TITLE
TTF embedded fonts fails on Windows 11

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#6405]
**Describe the bug**
Attempting to use TrueType Fonts in Windows 11 leads to this kind of crash:

```
System.InvalidOperationException: Could not create glyph typeface for: Cascadia Code
```

I dont have any more detailed stacktrace since wasabi swallowed it.

**To Reproduce**
Use any TTF files, embed them on an avalonia project and run it on Windows 11.

**Expected behavior**
Shouldn't crash.

**Desktop (please complete the following information):**
- OS: Windows 11

**Comment by Gillibald** [comment]
If you want this to be fixed soon you have to debug this on your own. I will not play with Windows 11 any time soon.

Make sure Skia can actually load the typeface https://github.com/AvaloniaUI/Avalonia/blob/master/src/Skia/Avalonia.Skia/SKTypefaceCollectionCache.cs#L34

Step threw the loading process and have a look at what familyName etc. Skia is reporting.

**Comment by jmacato** [comment]
@Gillibald well it isnt much a priority right now so we can leave it until Win11 RTM.

**Comment by jmacato** [comment]
Idk if this is still an issue, somebody shout if i need to reopen this.

**Comment by Gillibald** [comment]
My new dev machine has Windows 11 and I am not facing any issues
