### ISSUE TITLE
Renderer stopped when interacting with window decoration

### ISSUE THREAD

**Issue by luthfiampas** [AvaloniaUI/Avalonia#6411]
**Describe the bug**
Renderer stopped when interacting with window decoration.

https://user-images.githubusercontent.com/57059775/129244287-00c56402-3156-4fa6-96c2-9f2b17e5fff2.mp4

**To Reproduce**
1. Change `Source` property in `Image` control every `n` ms in the different thread by using `Dispatcher`, or..
2. Just create `ProgressBar` in Indeterminate mode
3. Press and hold left mouse button in the title bar, or..
4. Right click in the title bar

**Expected behavior**
Renderer should continue..

**Desktop (please complete the following information):**  
- OS: Windows 10, 8.1, 7
- Version 0.10.6

**Comment by luthfiampas** [comment]
I can confirm that this is also happen in this project https://github.com/AvaloniaUI/Avalonia.GIF/tree/master/AvaloniaGif.Demo.

**Comment by maxkatz6** [comment]
What Windows 10 version? Was WinUI composition disabled in win32 platform options? (It's enabled by default).

**Comment by luthfiampas** [comment]
@maxkatz6
I've already tested in Windows 10, 8.1, 7 with both `UseWindowsUIComposition` set to `false` or `true`. I'm currently running Windows 10 20H2 build 19042.1165. However, in Linux (Ubuntu, Mint) and macOS works just fine. Seems that this problem only occurs in Windows win32.

**Comment by luthfiampas** [comment]
**Edit:** In the described issue, I'm using `DeferredRenderer`. With `ImmediateRenderer`, the render operation stopped just for a few seconds.

**Comment by Takoooooo** [comment]
@luthfiampas May you check if this issue reproducible on master? It was fixed for me in master.

**Comment by Takoooooo** [comment]
This PR fixed that issue for me https://github.com/AvaloniaUI/Avalonia/pull/6361 .Btw it is worth to investigate why multitouch fixes that

**Comment by luthfiampas** [comment]
@Takoooooo Hmm.. Running `ControlCatalog.Desktop` from the master branch, and the issue still persists (can be seen at `ProgressBar` page).  I don't know why, but with `OverlayPopups` set to `true`,  the renderer stopped just for a few secs (can be seen at `RenderDemo` project).

**Comment by Takoooooo** [comment]
@luthfiampas Try out ControlCatalog.NetCore

**Comment by luthfiampas** [comment]
@Takoooooo  Enabling `EnableMultitouch` does seems to fix the issue, which is has not been configured in ControlCatalog.Desktop. But still, there is rendering delay when interacting with window decoration. And rendering stopped when you press and hold right mouse button. This is not happening in macOS or Linux.

https://user-images.githubusercontent.com/57059775/129446338-da16895e-e5aa-4ce3-8f37-3f5768439934.mp4

**Comment by toomasz** [comment]
Issues still persists for me as well (W11)
