### ISSUE TITLE
Win32Platform.Signal should respect DispatcherPriority parameter

### ISSUE THREAD

**Issue by nagya** [AvaloniaUI/Avalonia#6435]
Looks like it could easily be encoded in `lParam`.

**Comment by kekekeks** [comment]
It's "ignored" because the rest of the platform code doesn't respect dispatcher priorities. I think the only platforms where we actually enforce priorities are X11 and fbdev/libdrm.

**Comment by nagya** [comment]
By the rest of the platform you mean mainly the fact that WndProc just handles most events synchronously, as opposed to putting them on the dispatcher queue? That's a good point. My thinking was that even some partial support might be beneficial. E.g. if one does a `Dispatcher.Post(ActionA, DispatcherPriority.SomeHighValue)`, then a bit later same with `(ActionB, SomeLowerValue)`, it's fair to expect that any WndProc messages that were posted inbetween these two calls will be handled after ActionA and before ActionB. It's not much of a guarantee, but seems potentially useful.

**Comment by nagya** [comment]
The specific scenario I'm facing is ActionA's implementation posts ActionB, and any WndProc stuff that's in the queue at that point should be handled before ActionB. With the current behavior, ActionB will be run right after ActionA (assuming no other dispatcher jobs). In other words, high-prio actions should be able to "yield" to WndProc.

**Comment by kekekeks** [comment]
> the fact that WndProc just handles most events synchronously, as opposed to putting them on the dispatcher queue

Yes, that's the main problem. We could probably treat WndProc as DispatcherPriority.Input, but that would still be a bit troublesome to control outside of the GetMessage/DispatchMessage event loop.

**Comment by nagya** [comment]
Can you recommend a way to achieve the desired scenario? We're in a callback posted to the dispatcher, i.e. in the midst of `JobRunner.RunJobs`. Within this callback, we post another callback. Currently, that other callback will always be run in the same `RunJobs` loop without yielding. The desired behavior is that `RunJobs` yields, `WndProc` empites the win32 message queue, and only afer that is the second callback run.

**Comment by kekekeks** [comment]
`DispatcherTimer.RunOnce` with 1ms timeout.

**Comment by nagya** [comment]
> `DispatcherTimer.RunOnce` with 1ms timeout.

This does not seem to preserve the order in which the callbacks are posted (i.e. call RunOnce twice with different delegates and same timeout, second one gets run first, presumably non-deterministically), do you have a recommendation that would have a more stable behavior?

**Comment by kekekeks** [comment]
I guess I could suggest to write your own queue. Something like
```cs
class CallbackQueue
{
    bool _posted;
    Queue<Action> _actions = new();
    
    public void Post(Action a)
    {
         _actions.Add(a);
         if(!_posted)
         {
             _posted  = true;
             DispatcherTimer.RunOnce(() => {
                      _posted = false;
                      while(_actions.Count > 0)
                          _actions.Dequeue()();
             }, TimeSpan.FromMilliseconds(1));
         }
    }
}
```

**Comment by nagya** [comment]
Ok, thanks!
