### ISSUE TITLE
Acrylic Blur does not work on Windows 11

### ISSUE THREAD

**Issue by trympet** [AvaloniaUI/Avalonia#6465]
**Describe the bug**
Win2d acrylic blur does not work on Windows 11 build 22000.160. This also breaks `TransparencyLevel.Blur` if WinUI compositor is enabled.

DWM transparency and blur works fine.

**To Reproduce**

1. Create new project from template
2. Set `TransparencyLevelHint.AcrylicBlur` on the main window.
3. Set background to `null`.
4. Run

This can also be observed in the SampleApp.

**Expected behavior**
The acrylic layer should not be opaque.

**Screenshots**
![image](https://user-images.githubusercontent.com/23460729/130830733-da118dc2-373b-4e54-a3fa-44b480c6c38e.png)

**Desktop (please complete the following information):**
- OS: Windows 11 22000.160
- Version 0.10.3; 0.10.7 (master)

**Additional context**
Side note: `ICompositor3.CreateHostBackdropBrush()` is _not_ broken in this build of windows. `ICompositor2.CreateBackdropBrush()` might be though.

**Comment by PureFoxCore** [comment]
`Background="null"` just crushing application with error `Invalid brush string: 'null'.`

**Comment by Gillibald** [comment]
`Background="null"` -> `Background="{x:Null}"`

**Comment by Nickelony** [comment]
Even though this issue is closed, I still have problems on Windows 11 and Acrylic Blur / Mica effects.
On Windows 10, Acrylic Blur works perfectly fine, on Windows 11 it doesn't work at all.
Using Avalonia 0.10.10.

Even the Avalonia Control Gallery demo doesn't seem to have working acrylic either.

**Comment by maxkatz6** [comment]
@Nickelony that's pretty weird, because I used Acrylic yesterday in control catalog just yesterday on win11. On master branch.

**Comment by Orkunnnn** [comment]
Yep it is still has the issue on Windows 11 (22000.318).

**Comment by patryk9200** [comment]
I have the same issue, Avalonia Control Gallery also doesn't have working mica effect and I can't get it to work on my app to.
UWP apps like system settings have working mica so it's not a problem with power plan for example (it is disabled in power save mode).

I'm now on Windows 11 Insider Preview build 22504.1010.

**Comment by trympet** [comment]
@maxkatz6 Works for me on 22000.318 on 32fe95a2cc428e165b6ef89337a96e15fda65239. Background is not set to AcrylicBlur by default tho, which might cause some confusion.

**Comment by DeXP** [comment]
Still does not works for me. Windows 11 Pro, 22000.376. Avalonia 0.10.10. 
I downloaded https://github.com/AvaloniaUI/Avalonia.MusicStore . Build it with VS 2019 (16.11.7). No transparency.
Workaround: One call of `SetWindowCompositionAttribute` makes it working. Both `Background="Transparent"` and `TransparencyLevelHint="AcrylicBlur"` have to be set. I use the same code as here: https://github.com/riverar/sample-win32-acrylicblur/

**Comment by SomewhereOutInSpace** [comment]
> SetWindowCompositionAttribute shouldn't be used unless you want to release potentially broken application. It's undocumented API and has history of performance problems on older windows versions.
> 
> There must be another fix. Even though acrylic works perfectly with current master in this repo, I haven't tested MusicStore. Might be problem with some combination of custom window decorations.

I'm having the same issue. I tried cloning and building MusicStore in VS 2022 and the acrylic is still erroneously opaque.

**Comment by DeXP** [comment]
> acrylic works perfectly with current master in this repo

Is it? I've just got latest, built it in VS 2022, and runned the "Avalaonia Control Gallery". `Blur` works perfectly:
![ACG-Blur](https://user-images.githubusercontent.com/4019495/146503775-2f353041-0085-404f-8d53-c1f382fe79a9.png)

But `AcrylicBlur` one don't:
![ACG-Acrylic](https://user-images.githubusercontent.com/4019495/146503817-351b253e-74b1-4d55-ac1a-d34932134778.png)

`Mica` doesn't works for me as well:
![ACG-Mica](https://user-images.githubusercontent.com/4019495/146504030-043f31c8-31e0-48ed-9cf1-79d359875204.png)

**Comment by trympet** [comment]
I was able to reproduce by setting `ExtendClientAreaToDecorationsHint="True"`.

**Comment by trympet** [comment]
> > acrylic works perfectly with current master in this repo
> 
> Is it? I've just got latest, built it in VS 2022, and runned the "Avalaonia Control Gallery". `Blur` works perfectly: ![ACG-Blur](https://user-images.githubusercontent.com/4019495/146503775-2f353041-0085-404f-8d53-c1f382fe79a9.png)
> 
> But `AcrylicBlur` don't: ![ACG-Acrylic](https://user-images.githubusercontent.com/4019495/146503817-351b253e-74b1-4d55-ac1a-d34932134778.png)
> 
> `Mica` doesn't works for me as well: ![ACG-Mica](https://user-images.githubusercontent.com/4019495/146504030-043f31c8-31e0-48ed-9cf1-79d359875204.png)
> 
> P.S. I have Nvidia 1060 GPU and Intel i7 CPU, if it's related 🥇

Could you verify you're on master with the latest commit? There should be no difference between Blur and AcrylicBlur if composition is enabled. Also, are you running `ControlCatalog.NetCore`?

**Comment by DeXP** [comment]
Yup, sorry, you are correct - I was running `ControlCatalog.Desktop`. The NetCore version works perfectly.
What's the diffrence between them? My project is able to use `Blur` as well, but not `AcrylicBlur` or `Mica`. It's targeted for net5.0

**Comment by DeXP** [comment]
I've create a minimalistic app for testing AcrylicBlur. VS 2022, Avalonia 0.10.11. https://github.com/DeXP/Avalonia.AcrylicBlur.Sample
I've changed the theme to dark, set width and height of the window, also set TransparencyLevelHint="AcrylicBlur" and Background="Transparent".
But the blur does not working for me. What am I missing?
![image](https://user-images.githubusercontent.com/4019495/147230761-e113c6f4-9494-4db9-8803-305da4f8ea9e.png)

**Comment by trympet** [comment]
> The NetCore version works good. Except the case with `BorderOnly` for `AcrylicBlur` - it makes the window non transparent.

Yes! Not quite sure why that's the case. My guess is that it is a win11 issue, since I'm unable to reproduce on win10. It is likely caused by DwmExtendFrameIntoClientArea with non-zero MARGINS. 

> What's the diffrence between them? My project is able to use Blur as well, but not AcrylicBlur or Mica. It's targeted for net5.0

The projects have different rendering options in their program.cs-file. Netcore / net6.0 uses opengl + winui compositor; netframework uses opengl without winui compositor. Winui compositor is required for acrylic and mica. It is configured in `Win32PlatformOptions`.

You're probably experiencing issues due to the bug above. Try setting `ExtendClientAreaToDecorationsHint` to false. 😄

**Comment by DeXP** [comment]
Thank you very much, @trympet . `UseWindowsUIComposition = true` did the blur for me. [Commit to sample project](https://github.com/DeXP/Avalonia.AcrylicBlur.Sample/commit/254cfd5d06e371f221a3f6929541ce327f43cfe8)
However, I have the same issue as you - transparency do not work when ExtendClientAreaToDecorationsHint set to true 😄

**Comment by gargakshit** [comment]
I got Mica to work with `ExtendClientAreaToDecorationHint` by using `UseWindowsUIComposition = true` along with `ExtendClientAreaChromeHints = PreferSystemChrome`

![Preview of mica composition on Windows 11](https://user-images.githubusercontent.com/15605299/148936509-941736c3-0d38-40ab-8f31-999363d77ec1.png)

```xaml
<Window
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:vm="using:Avalonia.NETCoreMVVMApp1Fs.ViewModels"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
    x:Class="[ClassHere]"
    Icon="/Assets/avalonia-logo.ico"
    Title="[TitleHere]"
    TransparencyLevelHint="Mica"
    Background="{x:Null}"
    ExtendClientAreaToDecorationsHint="True"
    ExtendClientAreaChromeHints="PreferSystemChrome">
    <!-- ... -->
</Window>
```

**Comment by DeXP** [comment]
@gargakshit Does it works for you after publishing the application in Self-contained mode?

**Comment by gargakshit** [comment]
> @gargakshit Does it works for you after publishing the application in Self-contained mode?

Building with `dotnet publish -c Release -o build-release -r win-x64 --self-contained`, it doesn't seem to work. It shows a black screen. Omitting the `--self-contained` flag shows similar results.

**Comment by trympet** [comment]
> > @gargakshit Does it works for you after publishing the application in Self-contained mode?
> 
> Building with `dotnet publish -c Release -o build-release -r win-x64 --self-contained`, it doesn't seem to work. It shows a black screen. Omitting the `--self-contained` flag shows similar results.

Could you try setting the RID to `win10-x64`? `win-x64` has had issues with libgles not being copied to the output directory.

**Comment by DeXP** [comment]
`win10-x64` made `Mica` work for me after publishing. `av_libglesv2.dll` was added. Will the application work on earlier Windows? Like 8 etc.

**Comment by gargakshit** [comment]
> > > @gargakshit Does it works for you after publishing the application in Self-contained mode?
> > 
> > 
> > Building with `dotnet publish -c Release -o build-release -r win-x64 --self-contained`, it doesn't seem to work. It shows a black screen. Omitting the `--self-contained` flag shows similar results.
> 
> Could you try setting the RID to `win10-x64`? `win-x64` has had issues with libgles not being copied to the output directory.

Using the command `dotnet publish -c Release -o build-release -r win10-x64 --self-contained`, it does work for me.

**Comment by gargakshit** [comment]
> `win10-x64` made `Mica` work for me after publishing. `av_libglesv2.dll` was added. Will the application work on earlier Windows? Like 8 etc.

According to Microsoft's [documentation](https://docs.microsoft.com/en-us/windows/apps/design/style/mica#usability-and-adaptability), it appears as a solid fallback color when running on windows versions below 22000. I am not sure how this translates to Avalonia as I personally do not have a windows 8 or 10 machine to test.

**Comment by trympet** [comment]
> `win10-x64` made `Mica` work for me after publishing. `av_libglesv2.dll` was added. Will the application work on earlier Windows? Like 8 etc.

I think `win7-x64` should also work 😁

**Comment by DeXP** [comment]
`win8-x64` works, thank you. `win7-x64` is not able to publish as a single file executable.

**Comment by kekekeks** [comment]
I suspect that some versions of windows require a [compatibility manifest](https://docs.microsoft.com/en-us/windows/win32/sysinfo/targeting-your-application-at-windows-8-1) to work properly.

@maxkatz6 IIRC you've had issues with manifest previously. Could you post instructions here?

**Comment by maxkatz6** [comment]
Well, you can try to add app.manifest file with supported win10 os there. Visual Studio can generate one. It helped me with layered styled windows, probably it can somehow help with winui composition.

**Comment by Bum-Ho12** [comment]
The problem is still there, following the official documentation for the implementation still doesn't work on windows 11 23H2

**Comment by Bum-Ho12** [comment]
AcrylicBlur that is
