### ISSUE TITLE
Need a way to control and check the Z-Order of multiple Avalonia UI windows within the same application

### ISSUE THREAD

**Issue by npolyak** [AvaloniaUI/Avalonia#6479]
Having several windows within the same application, we need a way to check which window covers the other window and we need a way to control it programmatically. Window control has ZIndex property, but currently it does not work. Perhaps someone can make it work for checking and controlling the Z-Order. 
Or we can have a function `Window GetTopWindow(Window w1, Window w2)` which will return the window on top for checking Z-Order and another function `void SetTopWindow(Window w)` to set the window on top without activating it.

**Comment by pr8x** [comment]
The top window can be set via `Window.Activate()` no?

**Comment by npolyak** [comment]
> The top window can be set via `Window.Activate()` no?

I need to control the z-index without activating a window

**Comment by leonidcan** [comment]
Any news on that? I need one window always to be on top other (but it must not be topmost, it just should always keep relative position of it's 'owner'.

**Comment by timunie** [comment]
for windows only you can use Win32 API but that needs to be added on your side. Other OS don't allow this even afaik

**Comment by RomeCore** [comment]
You can make a base window class with static list of active windows, contain timestamps of last OnGotFocus events and order by them. But ALL of windows in your app would be inherited from this window class.

**Comment by grokys** [comment]
Should be fixed by https://github.com/AvaloniaUI/Avalonia/pull/14909
