### ISSUE TITLE
Virtualized ListBox sometimes does not recycle the container of the SelectedItem

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#648]
I'm working on a repro commit for this.

**Comment by danwalmsley** [comment]
I seem to be able to workaround this, by setting SelectedItem to null, then setting SelectedItem immediately.

It is probably happening as I am constantly setting selectedItem to the same value.

**Comment by grokys** [comment]
Did you manage to get a repro? Setting `SelectedItem` to the same value should have no effect, so I don't think that will be the cause...

**Comment by danwalmsley** [comment]
Its one of those where it keeps happening, and then goes away, sometimes its not obvious its happened. Will try and get a repro today if I can. It might be the first and last containers not getting updated actually, its usually when the item I'm looking at is top of the visible portion of the list.

**Comment by grokys** [comment]
Ok, then it's possible that #652 will have fixed it.

**Comment by danwalmsley** [comment]
ok will test...

**Comment by danwalmsley** [comment]
ok I don't think I am seeing this any more, I will keep an eye out a couple more days before closing.

**Comment by danwalmsley** [comment]
Seems to be fixed.
