### ISSUE TITLE
XAML using declarations don't work with nuget packages in the previewer.

### ISSUE THREAD

**Issue by KieranDevvs** [AvaloniaUI/Avalonia#6481]
**Describe the bug**
When referencing a namespace from an external assembly, `using` breaks the previewer in VS2019. When using `clr-namespace` and manually referencing the `assembly=`, the previewer works. In both scenarios, the project compiles successfully (this is just related to the previewer).

**To Reproduce**

1) Create a new Avalonia MVVM project.
2) Manage NuGet packages. 
3) Install: `Avalonia.Xaml.Interactivity@0.10.7`
4) Open `MainWindow.axaml`
5) Insert following namespace: `xmlns:i="using:Avalonia.Xaml.Interactivity"`
6) Declare following component:
```xml
<Button>
    <i:Interaction.Behaviors>

    </i:Interaction.Behaviors>
</Button>
```
7) Build.
8) Notice Build succeeds but previewer throws `invalid markup` with the following error:
```
21:01:40.683 [Error] 21816 UpdateXamlResult error
System.Xaml.XamlException: 'Unable to resolve type Interaction from namespace using:Avalonia.Xaml.Interactivity Line 17, position 6.' Line number '17' and line position '6'.
```
9) Update namespace to following: `xmlns:i="clr-namespace:Avalonia.Xaml.Interactivity;assembly=Avalonia.Xaml.Interactivity"`
10) Rebuild, build succeeds, previewer now works.

**Expected behavior**
Previewer should work when referencing namespaces with the `using` keyword.

**Comment by kekekeks** [comment]
The current workaround is adding GC.KeepAlive(typeof(Name.Of.A.Type.From.Required.Assembly)) at the beginning of `BuildAvaloniaApp` to force the assembly to be loaded.

**Comment by KieranDevvs** [comment]
> The current workaround is adding GC.KeepAlive(typeof(Name.Of.A.Type.From.Required.Assembly)) at the beginning of `BuildAvaloniaApp` to force the assembly to be loaded.

Is there a fix in the works for this?
