### ISSUE TITLE
ToolTips not shown for controls that are at the bottom edge of the screen

### ISSUE THREAD

**Issue by BaseHead** [AvaloniaUI/Avalonia#6498]
Any Control when near the bottom edge of the screen (testing in Win10 now) doesn't show the ToolTip

**To Reproduce**
Add some controls on the bottom edge of your application and move it to the bottom the screen OR just maximize it.

**Expected behavior**
Show the ToolTip instead of flicker  ;-)

Video of the Issue in Action:
https://user-images.githubusercontent.com/1595189/131360060-81911d68-ddd0-41f2-b65d-dea160756bec.mp4

Windows 10 19042.1165

**Comment by maxkatz6** [comment]
Avalonia version?

**Comment by BaseHead** [comment]
sorry.   Avalonia 0.10.7  ;-)

**Comment by sn4k3** [comment]
I can say that problem is been here since 0.10 preview. A trick that make it work is right click and hold the label

**Comment by Takoooooo** [comment]
i can reproduce this bug in 0.9.12 also so that's not regression

**Comment by BaseHead** [comment]
Yeah the Right Click trick does work but my users will never know to do that...hehe

Any progress on this bug? as we have at least 14 controls on the bottom edge of the program  ;-)
we are on AvaloniaUI 0.10.13 now FYI 
thx guys!
Steve

**Comment by BaseHead** [comment]
This looks fixed now in Avalonia 11 Preview 1.  Nice!
Keep up the good work guys!  ;-)
