### ISSUE TITLE
[CI] Ubuntu 16.04 LTS environment is deprecated and will be removed on September 20, 2021.

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#6502]
**Describe the bug**
Ubuntu 16.04 LTS environment is deprecated and will be removed on September 20, 2021. https://github.com/actions/virtual-environments/issues/3287

**Comment by Takoooooo** [comment]
I think we should update https://github.com/AvaloniaUI/Avalonia/blob/master/azure-pipelines.yml line 4 to vmImage: 'ubuntu-18.04' .If anyone would approve that it is the correct fix I can make a PR

**Comment by Gillibald** [comment]
I think the correct change would be to target Ubuntu 20.04 LTS
