### ISSUE TITLE
Porting to XAML/C++WINRT

### ISSUE THREAD

**Issue by tuduongquyet** [AvaloniaUI/Avalonia#6503]
**Is your feature request related to a problem? Please describe.**
Avalonia support .NET application only,

**Describe the solution you'd like**
C++WinRT has better performance, Avalonia can add support for pure XAML/C++ app.

**Comment by FoggyFinder** [comment]
You could try building with [NativeAOT](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT)
