### ISSUE TITLE
DataGrid - Make SelectedItems bindable

### ISSUE THREAD

**Issue by kvalitetskontrollMarkaryd** [AvaloniaUI/Avalonia#6514]
**Is your feature request related to a problem? Please describe.**
Enhancement

**Describe the solution you'd like**
Make SelectedItems bindable. Not a lot to say about it. It should be bindable.

**Describe alternatives you've considered**

**Additional context**

**Comment by maxkatz6** [comment]
dupicate https://github.com/AvaloniaUI/Avalonia/issues/2890
