### ISSUE TITLE
Non-pumping block should be the default and only behavior

### ISSUE THREAD

**Issue by nagya** [AvaloniaUI/Avalonia#6528]
STA threads on Windows have a legacy behavior where they "pump messages", meaning invoke DispatchMessage/WndProc outside of the main event loop when client code waits on a simple lock or semaphore. Other platforms don't do this and it almost always results in incorrect behavior such as reentrancy bugs. It has no place in a modern cross-platform UI toolkit.

Implementation-wise the proposal is to add a Win32-specific subclass of AvaloniaSynchronizationContext that incorporates the logic from NonPumpingSyncContext. This subclass would only be used on Win32 AND only if the UI thread is an STA thread. NonPumpingSyncContext and NonPumpingLockHelper would be removed.

**Comment by kekekeks** [comment]
> It has no place in a modern cross-platform UI toolkit.

We've tried to make the sync context to be non-pumping by default, but it turned out that doing so breaks .NET in various ways. E. g. you get a deadlock in GC.WaitForPendingFinalizers() if you do so.

**Comment by kekekeks** [comment]
If you need the non-pumping behavior in your app, you can simply replace our synchronization context with your own. Avalonia itself does not depend on that pumping behavior.

I guess we could also add an option switch to Win32PlatformOptions. But we can't have that option enabled by default.

**Comment by nagya** [comment]
I see, thanks for the details. I tried just making the UI thread MTA, and it seems to work fine. Do you happen to know what potential downsides that might have?

Also for the record, doing this during initialization has the same effect as creating a custom synchronization context and disabling pumping in it, while allowing keeping the thread STA.

```csharp
NonPumpingLockHelper.Use();
```

**Comment by kekekeks** [comment]
>Do you happen to know what potential downsides that might have?

Drag-n-drop and OLE clipboard might fail to work

**Comment by nagya** [comment]
OK, thanks, will watch out for that. One more thing, I noticed that even if the UI thread is MTA, `SynchronizationContext.Current` is still wrapped sometimes and can this be observed in user code, for example `IRenderer.Paint` is called with a wrapped context. This seems like an unnecessary performance overhead, and it would affect any code that uses the idiom 

```csharp
if (SynchronizationContext.Current == sctxFoo)
   DoSomething();
else
  sctxFoo.Post(_ => DoSomething(), null);
```

Could [the check for STA thread](https://github.com/AvaloniaUI/Avalonia/blob/3aa38398ff28012d7d296966a6df7d86e42f1424/src/Windows/Avalonia.Win32/NonPumpingSyncContext.cs#L38) be moved to the top, so on an MTA thread, it never wraps?

**Comment by nagya** [comment]
BTW, two more issues with `NonPumpingSyncContext`: it seems it tries to handle the `SynchronizationContext.Current == null` case, but would actually fail in such a case, as `_inner` would be null in `Post` etc. The respective base method should be called in this case instead.

Also it should delegate all overridable methods, specifically `OperationStarted` and `OperationCompleted` (and probably also `CreateCopy` altough I never quite understood how and why that's used.)
