### ISSUE TITLE
Long-press on Windows does not invoke context menus

### ISSUE THREAD

**Issue by jonthysell** [AvaloniaUI/Avalonia#6538]
**Describe the bug**
On windows touch devices, pushing and holding acts as a right-click in applications. I see the visual feedback that windows is trying a right click (an expanding square) but nothing happens.

**To Reproduce**

1. Launch an app with a textbox (or other control with a context menu) on a Windows device with a touch screen
2. Long-press (press and hold on the control)
3. See visual indicator Windows is attempting to right-click
4. Nothing happens

**Expected behavior**
See visual indicator Windows is attempting a right-click, context menu launches.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 0.10.7

**Additional context**
N/A

**Comment by maxkatz6** [comment]
Long-tap/Holding event should invoke ContextRequested routed event.
Question is if [Holding](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.holding?view=winrt-20348) event should be a gesture (like we have for touch scrolling) or not.
