### ISSUE TITLE
Incorrect format columns of Grid

### ISSUE THREAD

**Issue by SlavaPerryAyeKruchkovenko** [AvaloniaUI/Avalonia#6542]
When into Grid add Image Grid become incorrect

1. Create Second Grid into first Grid
2. Add Image in second Grid 
3. Columns of first Grid has Incorrect Grid

![image](https://user-images.githubusercontent.com/71411231/132088487-03d2a379-77b5-415a-bfab-0ac9a81e6977.png)
![image](https://user-images.githubusercontent.com/71411231/132088501-f59b54cb-ccda-436f-b82d-1b05eb64538d.png)

- OS: Windows
- Avalonia Version 10.3 VIsual Studio

**Comment by SlavaPerryAyeKruchkovenko** [comment]
<Grid ColumnDefinitions="9*,*" RowDefinitions="*,16*,*" ShowGridLines="True">
      <DockPanel Grid.Column="1">
        <Button Click="ExitApp"/>      
      </DockPanel>
      <Grid Grid.Row="1" RowDefinitions="6*,4*" ShowGridLines="True" Grid.ColumnSpan="2">
        <Image Source="/Assets/avalonia-logo.ico"/>
        <DockPanel Grid.Row="1">
          <Grid RowDefinitions="2*,*,2*,*">
            <Button x:Name="Play"/>
            <Button x:Name="Options" Grid.Row="2"/>
          </Grid>      
        </DockPanel>
      </Grid>
    </Grid>
    
    Xaml Code

**Comment by SlavaPerryAyeKruchkovenko** [comment]
<Grid ColumnDefinitions="9*,*" RowDefinitions="*,16*,*" ShowGridLines="True">
      <DockPanel Grid.Column="1">
        <Button Click="ExitApp"/>      
      </DockPanel>
      <Grid Grid.Row="1" RowDefinitions="6*,4*" ShowGridLines="True" Grid.ColumnSpan="2">
        <Image Source="/Assets/avalonia-logo.ico"/>
        <DockPanel Grid.Row="1">
          <Grid RowDefinitions="2*,*,2*,*">
            <Button x:Name="Play"/>
            <Button x:Name="Options" Grid.Row="2"/>
          </Grid>      
        </DockPanel>
      </Grid>
    </Grid>
    
    Xaml code

**Comment by SlavaPerryAyeKruchkovenko** [comment]
<Grid ColumnDefinitions="9*,*" RowDefinitions="*,16*,*" ShowGridLines="True">
      <DockPanel Grid.Column="1">
        <Button Click="ExitApp"/>      
      </DockPanel>
      <Grid Grid.Row="1" RowDefinitions="6*,4*" ShowGridLines="True" Grid.ColumnSpan="2">
        <Image Source="/Assets/avalonia-logo.ico"/>
        <DockPanel Grid.Row="1">
          <Grid RowDefinitions="2*,*,2*,*">
            <Button x:Name="Play"/>
            <Button x:Name="Options" Grid.Row="2"/>
          </Grid>      
        </DockPanel>
      </Grid>
    </Grid>

**Comment by SlavaPerryAyeKruchkovenko** [comment]
> When into Grid add Image Grid become incorrect
> 
> 1. Create Second Grid into first Grid
> 2. Add Image in second Grid
> 3. Columns of first Grid has Incorrect Grid
> 
> ![image](https://user-images.githubusercontent.com/71411231/132088487-03d2a379-77b5-415a-bfab-0ac9a81e6977.png)
> ![image](https://user-images.githubusercontent.com/71411231/132088501-f59b54cb-ccda-436f-b82d-1b05eb64538d.png)
> 
> * OS: Windows
> * Avalonia Version 10.3 VIsual Studio

Xaml code

<Grid ColumnDefinitions="9*,*" RowDefinitions="*,16*,*" ShowGridLines="True">
      <DockPanel Grid.Column="1">
        <Button Click="ExitApp"/>      
      </DockPanel>
      <Grid Grid.Row="1" RowDefinitions="6*,4*" ShowGridLines="True" Grid.ColumnSpan="2">
        <Image Source="/Assets/avalonia-logo.ico"/>
        <DockPanel Grid.Row="1">
          <Grid RowDefinitions="2*,*,2*,*">
            <Button x:Name="Play"/>
            <Button x:Name="Options" Grid.Row="2"/>
          </Grid>      
        </DockPanel>
      </Grid>
    </Grid>

**Comment by SlavaPerryAyeKruchkovenko** [comment]
Xaml code
![image](https://user-images.githubusercontent.com/71411231/132088669-73d136eb-353c-43f5-9b4d-7c7f2a3cd4c7.png)

**Comment by maxkatz6** [comment]
@SlavaPerryAyeKruchkovenko I can't reproduce your problem. Can you provide more information or project where we can see the problem?

![fxdvb](https://user-images.githubusercontent.com/3163374/132905481-1924a782-c0ea-4b56-9a3b-1c0837bedaa0.gif)

**Comment by SlavaPerryAyeKruchkovenko** [comment]
Image have Grid.ColumSpan = 2

**Comment by maxkatz6** [comment]
Image's parent grid doesn't have any columns in your example. 
Can you share project?
