### ISSUE TITLE
[OSX] Support of `Pitch to Zoom` trackpad gesture as a routed event.

### ISSUE THREAD

**Issue by Mikolaytis** [AvaloniaUI/Avalonia#6545]
**Is your feature request related to a problem? Please describe.**
Pitch to Zoom gesture is a must have feature to support on a macbook. It's used by macbook users everywhere. It's comfortable. Lack of that feature is a big problem in our software.

**Describe the solution you'd like**
I think we need to add an event to handle this in Avalonia, also add a native lib implementation to launch it. 

Apple Documentation - https://developer.apple.com/documentation/appkit/nsresponder/1525862-magnifywithevent

**What do I need?**
I will do a PR by myself. All I need is an API suggestion/approval. Where this event should be, How it should be called, should it be a routed event or not? I think it should be almost like `MouseWheel` routed event and called exactly `PitchToZoom`.

**Comment by JanTamis** [comment]
will this work with windows precision trackpads?
