### ISSUE TITLE
Style setters with dynamic selectors do not pick up data bindings

### ISSUE THREAD

**Issue by yatli** [AvaloniaUI/Avalonia#6557]
Consider this minimal example:

```xaml
<Window.Styles>
    <Style Selector="Border.foo">
        <Setter Property="Background" Value="{Binding Background}"/>
    </Style>
</Window.Styles>

<Border Classes="foo">
    <TextBlock>Hello</TextBlock>
</Border>
```
```c#
public class ViewModel
{
    public IBrush Background => Brushes.Red;
}
```

Works fine and Border picks up the color.
If we remove Classes declaration from xaml and add it from code (`border.Classes.Add("foo")`), it doesn't work.
This also means that pseudo classes (e.g. :pointerover) won't work.

Workaround:
It's not completely broken. If Classes="foo" is specified in XAML, we can remove it from code and add it back dynamically -- and the view will pick up the data bindings correctly.
Again, doesn't work for event trigger pseudo classes because we cannot add them in XAML.

**Comment by grokys** [comment]
Just got around to trying this on current master and it seems to have been fixed. Not sure when, but a lot of time has passed ;)
