### ISSUE TITLE
SelectedItem binding dont work properly then binding ListBox to filtered DataGridCollectionView

### ISSUE THREAD

**Issue by MrReny** [AvaloniaUI/Avalonia#6558]
**Describe the bug**
Then selecting item on ListBox with filtered collection, SelectedItem is set to the not filtered item with id of selected item in filtered collection.
So if you select second item in filtered list, second item in entire list is passed to VM

**To Reproduce**
1) Create ListBox;
2) Bind it to DataGridCollectionView;
3) Filter Collection;
4) Select Item
5) Check if SelectedItem contains valid item

**Expected behavior**
Property recieve selected value

**Screenshots**

![ScreenRecorderProject12_2](https://user-images.githubusercontent.com/25770886/132377389-2ca47867-516d-4a8c-b5e9-51321bb72307.gif)

**Desktop:**

- OS: Windows 10 , Linux Ubuntu 20.04, (Mac not tested)
- Version 0.10.7

**Comment by maxkatz6** [comment]
Why are you using DataGridCollectionView? With ListBox?

**Comment by MrReny** [comment]
@maxkatz6 Where no over easy way to filter SelectingItemsControl items, i used it as workaround.

**Comment by MrReny** [comment]
I can totaly see how it is not considered as intentional use of DataGridCollectionView.
If you think of this behavior as intended, close this issue.

**Comment by wieslawsoltes** [comment]
> @maxkatz6 Where no over easy way to filter SelectingItemsControl items, i used it as workaround.
@MrReny 
You can use DynamicData to filter items

https://github.com/wieslawsoltes/Svg.Skia/blob/6cfeba94b82810f2fa0175e8bacd221dcf2958e5/samples/TestApp/ViewModels/MainWindowViewModel.cs#L65-L76

https://github.com/wieslawsoltes/Svg.Skia/blob/6cfeba94b82810f2fa0175e8bacd221dcf2958e5/samples/TestApp/Views/MainWindow.axaml#L33

https://github.com/wieslawsoltes/Svg.Skia/blob/6cfeba94b82810f2fa0175e8bacd221dcf2958e5/samples/TestApp/ViewModels/MainWindowViewModel.cs#L41

**Comment by MrReny** [comment]
@wieslawsoltes Thnx, works great. And thank you for comprehensive example, i find it difficult to understand ways of usage of DynamicData from their docs.
Closing the issue i guess.
