### ISSUE TITLE
`PathMarkupParser` crashes with `InvalidDataException`: 'Invalid bool rule.'

### ISSUE THREAD

**Issue by Youssef1313** [AvaloniaUI/Avalonia#6577]
**Describe the bug**
`PathMarkupParser` crashing

**To Reproduce**

In a new project, use the following XAML:

```csharp
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1">
  <Button>
    <PathIcon Data="M17.432 11.619c.024.082.04.165.04.247V26.54c0 .37-.271.552-.605.409l-5.339-2.282c-.336-.144-.604-.558-.604-.926V9.066c0-.368.27-.551.604-.409l5.339 2.283a.898.898 0 01.27.188c.09.169.189.333.295.49M9.615 9.07v14.675c0 .368-.27.782-.605.925l-5.339 2.282c-.334.143-.604-.04-.604-.408V11.868c0-.368.269-.782.604-.926l5.34-2.282c.333-.143.604.04.604.41m15.713 4.173V23.74c0 .368-.27.782-.605.926l-5.338 2.282c-.334.143-.604-.04-.604-.41V13.216c1.015 1.231 2.702 3.615 3.136 6.3h.312c.43-2.665 2.087-5.033 3.099-6.272m-3.217-2.39c-2.065 0-3.738-1.705-3.738-3.808 0-2.102 1.673-3.807 3.738-3.807 2.064 0 3.738 1.705 3.738 3.807 0 2.103-1.674 3.808-3.738 3.808M22.054 2c-2.768 0-5.012 2.286-5.012 5.105 0 1.378.531 2.693 1.401 3.611 0 0 2.928 2.912 3.488 6.389h.279c.56-3.477 3.471-6.389 3.471-6.389.873-.918 1.386-2.232 1.386-3.61 0-2.82-2.245-5.106-5.013-5.106"
      VerticalAlignment="Center" />
  </Button>
</Window>
```

**Expected behavior**

Icon similar to:

![image](https://user-images.githubusercontent.com/31348972/132988221-11a4ed51-0bbe-4c6b-b66d-ddc4d922906c.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

Frameworks like UWP and WPF handles this correctly.

**Comment by Gillibald** [comment]
There is no `F` fill-rule command in the path data so the exception is a bit weird. Will have a look shortly.

**Comment by Gillibald** [comment]
So the `a` (elliptical arc) command has a missing boolean flag. Not entirely sure whether this is allowed or not

**Comment by Youssef1313** [comment]
@Gillibald It works on HTML, WPF, and UWP. So I assume it should be allowed?

**Comment by Gillibald** [comment]
The failing part is this sequence: `a.898.898 0 01.27.188` my guess is that `01` isn't parsed as `0`. So the resulting sequence should be `a .898 .898 0 0 1.27 .188`

**Comment by Youssef1313** [comment]
@Gillibald So I guess the fix is to modify `ReadBool` implementation to the following?

```csharp
		private bool ReadBool(ref ReadOnlySpan<char> span)
		{
			span = SkipWhitespace(span);
			if (span.IsEmpty)
			{
				throw new InvalidDataException("Cannot read bool from empty span.");
			}

			var c = span[0];
			span = span.Slice(1);

			switch (c)
			{
				case '0':
					return false;
				case '1':
					return true;
				default:
					throw new InvalidDataException("Invalid bool rule");
			}
		}
```

**Comment by Gillibald** [comment]
Y if my theory is correct that is the right fix. Read just one character. If the character is not a number throw. For a 0 the result is false for non zero the result is true. Negative signs are ignored. I think the that is how the spec defines the flag parsing.

**Comment by Youssef1313** [comment]
> for non zero the result is true

Isn't it supposed to be "just" "1"?

> "M 10 10 a 1 1 0 01 .27 .188z"

The above works in WPF, but the following doesn't:

> "M 10 10 a 1 1 0 02 .27 .188z"

So `2` wasn't considered true.

Same for negative signs, they doesn't seem to be ignored.

**Comment by Gillibald** [comment]
Y it looks like flags are more strict `flag::=("0"|"1")`
