### ISSUE TITLE
Nightly build is broken

### ISSUE THREAD

**Issue by 0x90d** [AvaloniaUI/Avalonia#6578]
I'm looking forward for a version of a recent merged pull request but I've noticed nightly builds are no longer published for quite a while because the build fails: https://dev.azure.com/AvaloniaUI/AvaloniaUI/_release?_a=releases&view=mine&definitionId=2

cc @grokys

**Comment by kekekeks** [comment]
Something is wrong with publishing to MyGet, you can use the "all" feed for now. The only downside about it is that it contains builds from PRs.

**Comment by 0x90d** [comment]
@kekekeks Thank you. Do you have a nuget link for me I can use in VS?

**Comment by 0x90d** [comment]
I've tried the URL from the wiki but it shows me no releases at all: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed#all-builds-feed

**Comment by timunie** [comment]
I think this is fixed now thanks to @danwalmsley 

https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

If this works for you I think this issue can be closed.

Happy coding
Tim
