### ISSUE TITLE
Fix Skia SetForegroundBrush implementation

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#658]
Current implementation does not take into account that multiple brushes can be applied to the same text.

i.e.

"This is a test string"
Then setforeground brush can be applied, black over whole string.

Then setforeground brush can be applied red to "test" part of the string.

Current implementation would just produce black text.

**Comment by danwalmsley** [comment]
@donandren perhaps you can advise on how this might be fixed?

**Comment by donandren** [comment]
@danwalmsley currently SetForegroundBrush is supporting multiple foregrounds, but using the first found range and if there are multiple ranges for the same area it's using the first set, probably that need to be changed - so the used foreground brush is with the smallest possible range of the available foregrounds. I'll submit PR that's pretty easy.

**Comment by danwalmsley** [comment]
Still not resolved, see comments on the PR, thanks for efforts.
