### ISSUE TITLE
[Feature request] NumericUpDown with a ValueLabel property

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#6582]
**Is your feature request related to a problem? Please describe.**
Currently `NumericUpDown` allow a FormatString, but when used with custom text or units, it will mess the value when user edit the value on the box but not when they use the spinner alone, also not pratical and easy to mess up.

**Describe the solution you'd like**

- Have a property, like: `ValueLabel` that allow us to set whatever we want, eg: `mm/min`.
- `ValueLabelPosition` enum(Left, AfterValue, Right), with default to AfterValue

That way we can have a locked text that don't mess with the input and with good integrated design
Here an ugly sample i did, i just put a TextBox disabled after the NumericUpDown to illustrate the solution:

![image](https://user-images.githubusercontent.com/113281/133126866-dd9334e9-6056-4530-b184-267db3c2c096.png)

![image](https://user-images.githubusercontent.com/113281/133126730-4349b819-1c55-4570-a3ab-b798167a8226.png)

![UVtools_2021-09-13_17-54-22](https://user-images.githubusercontent.com/113281/133125349-d2a1aac7-e6aa-49e4-9b3c-8a099a7ce2a1.png)

**Comment by maxkatz6** [comment]
You can do it with TextBox.InnerLeftContent and InnerRightContent.
```xaml
<Style Selector="NumericUpDown /template/ TextBox">
    <Setter Property="InnerRightContent" Value="mm" />
</Style>
```

**Comment by sn4k3** [comment]
> You can do it with TextBox.InnerLeftContent and InnerRightContent.
> 
> ```
> <Style Selector="NumericUpDown /template/ TextBox">
>     <Setter Property="InnerRightContent" Value="mm" />
> </Style>
> ```

That will require a style for each value right? Is any way to do it directly on AXMAL?

**Comment by maxkatz6** [comment]
> That will require a style for each value right

You can use style-classes for different values. 
or
You can create attached property (or use Tag property) and store label text there. Read it next in that setter.

> Is any way to do it directly on AXMAL

You don't need changes outside of AXAML except creating attached property, if you choose that approach.

**Comment by maxkatz6** [comment]
Although I think it might be nice to have InnerLeftContent and InnerRightContent on NumericUpDown directly.
But so far, it's quite easy to achieve this behavior in another way.

**Comment by sn4k3** [comment]
I tried that and i got this:

![UVtools_2021-09-13_19-35-03](https://user-images.githubusercontent.com/113281/133138123-346d685e-dfeb-4beb-9f07-0c166ca9718b.png)

Seens broken, need additional styling... How can i attach additional style to that block `InnerRightContent`, what's the selector path?

However i still think for most people, having a integrated solution like i suggested (Native without have to hack styles) are more convenient and design-wise. It can even accept Content like a button or whatever so we can have a stack of button for options.

**Comment by maxkatz6** [comment]
> Seens broken

It's not broken. It "need additional styling", correct. Because left/right content is not just a text, it can be any content.

> what's the selector path

Same. You can put TextBox inside of it and adjust styling.

**Comment by sn4k3** [comment]
> Same. You can put TextBox inside of it and adjust styling.

Will need a little sample on this, all this styling system is still mistery to me :P 
I tried:

```
<Style Selector="NumericUpDown /template/ TextBox">
        <Setter Property="InnerRightContent">
            <Setter.Value>
                <TextBox Text="mm"/>
            </Setter.Value>
        </Setter>
    </Style>
```

But of course it fail to run

**Comment by maxkatz6** [comment]
I forgot to mention, it should be Template object:
```xaml
<Style Selector="NumericUpDown /template/ TextBox">
        <Setter Property="InnerRightContent">
            <Template>
                <TextBox Text="mm"/>
            </Template>
        </Setter>
    </Style>

```

For example
https://github.com/AvaloniaUI/Avalonia/blob/0b9cd49a11c4ef026d2ed6cf07e7aa718ba5a974/src/Avalonia.Themes.Default/TextBox.xaml#L110

**Comment by sn4k3** [comment]
Ok, that way i got the result i want:

  ```XML
<Style Selector="TextBox.NumericUpDownValueLabel">
      <Setter Property="IsEnabled" Value="False" />
      <Setter Property="IsReadOnly" Value="True" />
      <Setter Property="MinWidth" Value="0" />
      <Setter Property="CornerRadius" Value="0" />
      <Setter Property="VerticalAlignment" Value="Stretch" />
      <Setter Property="VerticalContentAlignment" Value="Center" />
      <Setter Property="HorizontalContentAlignment" Value="Center" />
  </Style>

    <Style Selector="NumericUpDown /template/ TextBox">
        <Setter Property="InnerRightContent">
          <Template>
              <TextBox Classes="NumericUpDownValueLabel" Text="mm"/>
          </Template>
        </Setter>
    </Style>
```

![UVtools_2021-09-13_20-06-13](https://user-images.githubusercontent.com/113281/133141979-92885eaa-4837-4f66-a507-f75a3c0f25e3.png)


That satisfies my request, if you think this request have no light ahead please close it

**Comment by sn4k3** [comment]
Btw is there any way to simplify this:

```C#
    <Style Selector="NumericUpDown.Label_mm /template/ TextBox">
        <Setter Property="InnerRightContent">
          <Template>
              <TextBox Classes="NumericUpDownValueLabel" Text="mm"/>
          </Template>
        </Setter>
    </Style>

    <Style Selector="NumericUpDown.Label_s /template/ TextBox">
        <Setter Property="InnerRightContent">
            <Template>
                <TextBox Classes="NumericUpDownValueLabel" Text="s"/>
            </Template>
        </Setter>
    </Style>

    <Style Selector="NumericUpDown.Label_mmmin /template/ TextBox">
        <Setter Property="InnerRightContent">
            <Template>
                <TextBox Classes="NumericUpDownValueLabel" Text="mm/min"/>
            </Template>
        </Setter>
    </Style>
```

By having only one Selector with multiple templated based on class?

**Comment by maxkatz6** [comment]
Haven't tested it, but something like this:
```xaml
    <Style Selector="NumericUpDown.Label /template/ TextBox">
        <Setter Property="InnerRightContent">
          <Template>
              <TextBox Classes="NumericUpDownValueLabel" />
          </Template>
        </Setter>
    </Style>
    <Style Selector="NumericUpDown.Label.mm TextBox.NumericUpDownValueLabel">
        <Setter Property="Text" Value="mm" />
    </Style>
```

But for lots of variations I would just created attached property.

**Comment by sn4k3** [comment]
That works, but i'm getting some strange black magic here.

```XML
  <Style Selector="TextBox.NumericUpDownValueLabel">
      <Setter Property="IsEnabled" Value="False" />
      <Setter Property="IsReadOnly" Value="True" />
      <Setter Property="MinWidth" Value="0" />
      <Setter Property="CornerRadius" Value="0" />
      <Setter Property="VerticalAlignment" Value="Stretch" />
      <Setter Property="VerticalContentAlignment" Value="Center" />
      <Setter Property="HorizontalContentAlignment" Value="Center" />
  </Style>

  <Style Selector="NumericUpDown.ValueLabel /template/ TextBox">
      <Setter Property="InnerRightContent">
          <Template>
              <TextBox Classes="NumericUpDownValueLabel" />
          </Template>
      </Setter>
  </Style>

  <Style Selector="NumericUpDown.ValueLabel.percent TextBox.NumericUpDownValueLabel">
      <Setter Property="Text" Value="%" />
  </Style>
    <Style Selector="NumericUpDown.ValueLabel.mm TextBox.NumericUpDownValueLabel">
        <Setter Property="Text" Value="mm" />
    </Style>
    <Style Selector="NumericUpDown.ValueLabel.s TextBox.NumericUpDownValueLabel">
        <Setter Property="Text" Value="s" />
    </Style>
    <Style Selector="NumericUpDown.ValueLabel.mmmin TextBox.NumericUpDownValueLabel">
        <Setter Property="Text" Value="mm/min" />
    </Style>
```


```XML
<StackPanel Orientation="Horizontal" Spacing="10">
        <TextBlock VerticalAlignment="Center" Text="X:"/>
        <NumericUpDown
            Classes="ValueLabel percent"
            Width="200"
          Minimum="1"
          Maximum="10000"
          Increment="0.1"
          FormatString="F2"
          Value="{Binding Operation.X}"/>
    
        <TextBlock 
          Margin="10,0,0,0" 
          VerticalAlignment="Center" 
          Text="Y:"
          IsEnabled="{Binding !#ConstrainXY.IsChecked}"/>
        <NumericUpDown 
            Classes="ValueLabel mmmin"
          Width="200"
          Minimum="1"
          Maximum="10000"
          Increment="0.1"
          FormatString="F2"
          Value="{Binding Operation.Y}"
          IsEnabled="{Binding !#ConstrainXY.IsChecked}"
          />
    
        <CheckBox
          Name="ConstrainXY"
          IsChecked="{Binding Operation.ConstrainXY}" 
          Content="Constrain Proportions" />
      </StackPanel>
```

every other class works, but percent does not, i tried to name it differently, give other text value, like mm, and still doesnt work. It seen first style is getting ignored somehow

![UVtools_2021-09-13_20-37-41](https://user-images.githubusercontent.com/113281/133145787-2b9f3c46-07a7-4877-8572-cf9562a7d3fc.png)

**Comment by sn4k3** [comment]
Using custom control
