### ISSUE TITLE
Binding to Current Source does not Re-evaluate on PropertyChanged

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#6602]
Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/6596

## Issue

I have code similar to below:

```xaml
        <ListBox Items="{Binding Mappings}">
            <ListBox.ItemTemplate>
                <DataTemplate DataType="local:IconMappingViewModel">
                    <Grid Background="{Binding ., Mode=OneWay, Converter={StaticResource IconMappingStateToBrush}}">
                            <CheckBox Content="IsPlaceholder"
                                      IsChecked="{Binding IsPlaceholder, Mode=TwoWay}" />
                    </Grid>
                </DataTemplate>
            </ListBox.ItemTemplate>
        </ListBox>
```

The ViewModel has an IsPlaceholder property that can be checked/unchecked in the UI. The Background of the root Grid itself is set using a converter that processes the ViewModel binding source itself `{Binding}` or `{Binding Path=.}`. However, when the IsPlaceholder CheckBox is clicked, the ViewModel is updated but the background color is never re-evaluated. I would expect ANY property changed event within the ViewModel to trigger a re-evaluation of this binding:

`{Binding ., Mode=OneWay, Converter={StaticResource IconMappingStateToBrush}}`

It was discovered that this does work; however, only after scrolling the ListBoxItem out of the visible area. When it's scrolled out then back into view, the background has been updated.

## Expected Behavior

The background of the Grid should change immediately when the IsPlaceholder ComboBox is toggled.

**Comment by ahopper** [comment]
You need to bind to the actual property that is changing i.e. IsPlaceholder, its parent won't fire an ischanged just because one of its properties change and can't know that your converter looks at a child property.

**Comment by robloo** [comment]
This is why you don't debug late at night :)

> You need to bind to the actual property that is changing i.e. IsPlaceholder, its parent won't fire an ischanged just because one of its properties change and can't know that your converter looks at a child property.

I can't do as you suggest because I'm using many properties of the view model, not only IsPlaceholder to determine the background. However, to fix this I need to add a new property to the viewmodel that is calculated and updated based on all other property changes. Then bind to this new property in the view through the converter.

Also note that the reason scrolling out of view and then back into view works is due to ListBox virtualization -- I think. It was entirely reloaded and re-evaluating the bindings which triggered the necessary updates.
