### ISSUE TITLE
Application stuck completely when drawing lots of objects on canvas with Deferred Renderer

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/Avalonia#6622]
**Describe the bug**
I have found one interesting bug in the Deferred renderer. One user shared this project with me. It draws lots of objects on the canvas. In WPF it works bad, but works. In Avalonia 0.10.7 with Deferred renderer, every second fps drops until it would reach 0 fps and everything would stuck completely. With immediate renderer, it would work much better
https://github.com/CreateLab/avalonia.triangle
Here is the example of how it is working with immediate renderer https://recordit.co/mqWUBlVLyS
Here is the example of how it is working with deferred renderer https://recordit.co/BaKton464W (I clicked on the stop button for 10 seconds)
Lag maybe not really noticeable on those videos because they are also low fps but if you will try it by yourself you will understand me.

- OS: Windows 10
- Version 0.10.7

**Comment by workgroupengineering** [comment]
@Takoooooo  
I think it depends on a memory leak, if you look at the videos you will see how fast the memory occupation rises when you use the DeferredRenderer.

**Comment by kekekeks** [comment]
Appears to be fixed in 11.0 (most likely by dispatcher improvements)
