### ISSUE TITLE
Blurry Graphics on Linux

### ISSUE THREAD

**Issue by nlogozzo** [AvaloniaUI/Avalonia#6633]
![image](https://user-images.githubusercontent.com/17648453/134508479-7a81c02e-8241-401f-b205-db5b7e21c3ec.png)
Compared to IntelliJ on the left and my app on the right, the graphics on the right seems to be much more blurry and harder to read. Why is this?

Using Avalonia 0.10.7 with Arch Linux and cinnamon (gtk) desktop environment

**Comment by Takoooooo** [comment]
i think you may feel so because of fonts

**Comment by nlogozzo** [comment]
Are the avalonia app fonts different then the system fonts? How could I change it? @Takoooooo

**Comment by Gillibald** [comment]
Set a the FontFamily on your Window

`FontFamily="$Default"` or if I am not mistaken "FontFamily="x:Static FontFamily.Default"

**Comment by nlogozzo** [comment]
The font doesn't change using either of those lines. Guess i have to just accept this font :man_shrugging:

**Comment by danielmayost** [comment]
Do you scale the screen (150%, 200%, etc.)?

<img src="https://3.bp.blogspot.com/-cuJTGOEtWSY/XLb6yTUNj9I/AAAAAAAACoY/de2vtkWnzOIBezPNYsiGaXtl5gyf9p0uACLcBGAs/s1600/fractional-scaling-x11-ubuntu1904-disco-dingo.png" width="400" height="260">

**Comment by nlogozzo** [comment]
No it's set to 100%. However, I've learned to live with it as I believe it's just differences in the Avalonia font vs the system font giving it a blurry appearance
