### ISSUE TITLE
DragDropEffects.Move does not work on macOS

### ISSUE THREAD

**Issue by ltetak** [AvaloniaUI/Avalonia#6634]
**Describe the bug**
Windows and macOS behave differently. On Windows, I can use both Copy and Move DragDropEffects. On mac, if I use Move effect it always cancels the operation (I can start the drag but when I drop the item it abandons the action and nothing happens).

**To Reproduce**
1. Take DND sample code
2. in DragDrop.DragOverEvent set e.DragEffects = DragDropEffects.Move

**Expected behavior**
DropEvent should be invoked.

**Desktop (please complete the following information):**

- OS: mac
- Version 0.10.7

**Additional context**
I couldn't track the problem beyond the native macOS lib boundary.

**Comment by josephnarai** [comment]
I'm having a similar problem and am wondering if it's related? 

I am using DragDropEffects.Link. The issue I see is that even though I have set AllowDrop on my object:

`DragDrop.SetAllowDrop(HighlightRectangle, true);`

However, the drag drop icon doesn't change when hovering over the HighlightRectangle. Works fine on windows, does not on Mac, and am unable to then execute the drop...

OS: Mac
Avalonia version 10.10

Any clues for debugging would be greatly appreciated.

**Comment by josephnarai** [comment]
Just tried changing to Copy and that works fine, so it seems the issue applies to Move and Link.

**Comment by ltetak** [comment]
@josephnarai yes, Link is the same as Copy. I checked the code a week ago and the problem is in the Avalonia.Native implementation in objective C. I don't have enough skills in objective C but I was able to make Move working but this had broken the Copy. Somebody with better skills should be able to fix this quite easily.

**Comment by josephnarai** [comment]
You mean Link is the same as Move. In my experience, Copy works ok, but Link and Move do not. I can just use Copy in my application for now, but it would be good to have this fixed at some point. Thanks.

**Comment by ltetak** [comment]
sorry... didn't have my morning coffee yet... 
Link works the same as Move (it doesn't work). You can test that even with the Avalonia Sample app.
The problem is somewhere among these lines (if you hardcode ret = NSDragOperationMove (link your case) it does work.
https://github.com/AvaloniaUI/Avalonia/blob/master/native/Avalonia.Native/src/OSX/window.mm#L1971-L1980
Maybe I will be able to do some hotfix after all (at least some draft).

**Comment by ltetak** [comment]
You can see this branch for improved sample app where it is clear that windows implementation is correct but mac is not
https://github.com/AvaloniaUI/Avalonia/compare/master...ltetak:osx_dnd?expand=1
The reason is that draggingSourceOperationMask is always zero for non-Copy effects.

**Comment by josephnarai** [comment]
Thank you.

J

**Comment by ltetak** [comment]
fixed here https://github.com/AvaloniaUI/Avalonia/pull/7015
