### ISSUE TITLE
Weird Cursor on Linux

### ISSUE THREAD

**Issue by nlogozzo** [AvaloniaUI/Avalonia#6635]
Running an Avalonia application under Linux (Arch Linux with cinnamon desktop)
I get a weird cursor that is shown:
![cursor](https://user-images.githubusercontent.com/17648453/134521614-2a183640-f7eb-4a52-b2e5-0e2b2c9b0302.jpeg)

*Sorry for the picture, but when I screenshot the correct cursor is displayed in the screenshot*

**Comment by kekekeks** [comment]
TBH, it looks like that something is wrong with the system settings. We are using a standard XC_top_left_arrow which should be mapped to a normal arrow cursor.

**Comment by nlogozzo** [comment]
You're right, changing my cursor theme fixed the issue. Thanks!

**Comment by kekekeks** [comment]
I've checked GTK and they seem to be using `XC_left_ptr` as their default cursor. Might be worth doing that as well.
