### ISSUE TITLE
TextBlock wraps a trailing character when it has enough space to keep it on the same line

### ISSUE THREAD

**Issue by YohDeadfall** [AvaloniaUI/Avalonia#6643]
**Describe the bug**

`TextBlock` control wraps a trailing character when there's no limits on the size. It should not happen.

**To Reproduce**
Code to reproduce the behavior:

```csharp
<StackPanel>
    <TextBox
        HorizontalAlignment="Center"
        Classes="noClearButton"
        Text="EffectsSettings"
        TextAlignment="Center"
        TextWrapping="Wrap" />
</StackPanel>
```

**Expected behavior**

No wrap should be done since the available size allows to keep the entire string on the same line.

**Screenshots**

While there's `EffectsSettings` set as a text, the text block puts the trailing `s` on a new line.

![image](https://user-images.githubusercontent.com/10694013/134734120-c0850125-f7d4-44a8-8691-bf2fbdd7d067.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version: latest

---

@MarchingCube, it's what we're experiencing.

**Comment by maxkatz6** [comment]
Not sure if it has enough space. Most likely that's because of padding on TextBox.

**Comment by Gillibald** [comment]
I don't think the text is wrapped here this is more a clipping issue. The TextBox might not report the right measurements.

**Comment by YohDeadfall** [comment]
It's not a clipping issue, since with our theme that wrap is visible. Moreover, disabling layout rounding for the text block solves the issue. In our case with the custom theme the presenter's size is `{14.83447265625, Infinity, 64.3310546875, 13.30078125}`, so aligning to the center reduces the width by one pixel and breaks the layout.

Not sure, should the issue be closed or nor, but disabling the rounding solved the problem.

**Comment by Gillibald** [comment]
Current TextBox has a hack that requires multiple measure passes to get text alignment etc. working. Somehow the second time the text is measured there isn't enough space left so wrapping takes place. We should try this with my TextPresenter rework. If that works out well we can try to fix this in the current implementation.

**Comment by Gillibald** [comment]
The combination of `TextAlignment="Center"` and `TextWrapping="Wrap"` will not work here

**Comment by YohDeadfall** [comment]
Yeah, looks like a leftover from times when we had one line non wrapping text.

**Comment by YohDeadfall** [comment]
@Gillibald, I used your PR for our solution, and it doesn't solve this issue.

**Comment by Gillibald** [comment]
`TextWrapping="Wrap"` wraps characters if not enough space is left. `TextWrapping="WrapWithOverflow"` doesn't do that. Are you sure there isn't a fixed width on your TextBox? Are you restyling the TextBox somehow? Pls, verify that the horizontal scrollbar is disabled.

**Comment by Gillibald** [comment]
Small update

I could reproduce an issue with the TextAlignment and the MeasureOverride in my PR chich produces your reported rendering. Trying to fix that now.

**Comment by Gillibald** [comment]
Can't repro the issue anymore
