### ISSUE TITLE
Undo command on TextBox causes crash.

### ISSUE THREAD

**Issue by yusuf-gunaydin** [AvaloniaUI/Avalonia#666]
If you press Ctrl+Z on an empty TextBox it crashes the application.
Also, if the text is set before the TextBox is shown, Ctrl+Z deletes all the text. I don't know if this is expected.

**Comment by grokys** [comment]
Yeah, undo/redo for `TextBox` is messed up, it's definitely not expected behavior! I've been thinking of putting an undo/redo framework I have into Avalonia, but just fixing it in `TextBox` would be good for now.

Related #493, #336

**Comment by grokys** [comment]
Closed #667 .
