### ISSUE TITLE
Binary compatibility cleanup list

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#6666]
Since we are keeping binary compatibility with the latest nuget release, some design choices are sub-optimal in the long term. 
This issue serves as a tracker for breaking changes that should be done during the preparation phase of the next version.

- [X] - https://github.com/AvaloniaUI/Avalonia/pull/6665 - ControlTemplateResult should be completely replaced with `TemplareResult<IControl>`
- [X] - Core libraries merge, see https://github.com/AvaloniaUI/Avalonia/pull/5831
- [X] - AppBuilder (see https://github.com/AvaloniaUI/Avalonia/issues/7052)
- [ ] - WindowRoot (https://github.com/AvaloniaUI/Avalonia/issues/7063)
- [X] - Remove various things that have been `[Obsolete]` for ages, e.g. `DropDown`
- [X] - Separate `class` and `struct` overloads for property registration (https://github.com/AvaloniaUI/Avalonia/pull/7078#discussion_r762976636)
- [x] - Add `[Unstable]` (or something) attributes to platform types to hide them from ApiCompat and properly document our stable API
- [X] - [Standardize Pointer Event Names with WinUI](https://github.com/AvaloniaUI/Avalonia/issues/8058)
- [x] - Make PointerPoint to be a struct rather than a class
- [x] - Remove public constructors for KeyEventArgs, PointerEventArgs and friends.
- [X] - Remove generic virtual methods from the public API
- [x] - Refactor transparency hints
- [x] Remove many unneeded interfaces (`IVisual`, `ILayoutable`, `IControl` etc) and use concrete classes (#9495)

**Comment by grokys** [comment]
Currently `AvaloniaLocator.GetService` can return null if a service isn't found. This results in a lot of potential NREs. Should we change it to throw if the service is not found and add a `TryGetService` method?

**Comment by jp2masa** [comment]
For reference, `Microsoft.Extensions.DependencyInjection` has `GetService` and `GetRequiredService` for this purpose I believe: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceproviderserviceextensions?view=dotnet-plat-ext-6.0#methods.

(I'm personally not a fan of this pattern, but if you want to be consistent with official Microsoft packages I think this is relevant.)

**Comment by danwalmsley** [comment]
Remove ClientSize.

**Comment by danwalmsley** [comment]
Might as well put this here:
Provide windows ARM64 binaries for libgles etc. (all that is needed for just works arm on windows support)
