### ISSUE TITLE
Wrong cursor on Linux for Cursor="Hand" (0.10.7)

### ISSUE THREAD

**Issue by kuiperzone** [AvaloniaUI/Avalonia#6670]
I have a TextBlock defined as:

```
<TextBlock Name="linkText" Grid.Column="0" Text="https://kuiper.zone" VerticalAlignment="Center"
                Foreground="#1d8da3" Cursor="Hand"/>

```
Note the Cursor property.

On Windows, the cursor shows correctly as follows:

![hand_windows](https://user-images.githubusercontent.com/17156238/135754061-57ca680b-cc17-4054-a2ca-ae56f555c92f.jpg)

On Linux, it shows incorrectly as:

![hand_linux](https://user-images.githubusercontent.com/17156238/135754069-2ac64b35-923c-4ddc-b443-9235303c09a2.jpg)

The cursor should be equivalent to that for Windows. What is shown on Linux is a "move cursor".

- OS: Windows 10 vs Fedora 34 (and also POP OS)
- Version 0.10.7

**Comment by kekekeks** [comment]
Hand cursor is mapped to `XC_hand1` which is the same behavior as in GTK. Check if your cursor theme provides the correct cursor for `XC_hand1`

**Comment by kuiperzone** [comment]
I'm running default Adwaita cursor set, but the behaviour is the same with DMZ cursors.

On checking the installed cursors, we can see:

hand = link to hand2
hand1 = move
hand2 = pointer

Note that that there is a softlink just called "hand" which points at hand2 (pointer).

![cursors](https://user-images.githubusercontent.com/17156238/135773851-9711a801-56d4-448e-8cf8-1568914a27f1.jpg)

**Comment by kekekeks** [comment]
GTK cursor mappings: https://github.com/GNOME/gtk/blob/226edf1f917deb1efc6460feffd5b1d3cfafe1fc/gdk/x11/gdkcursor-x11.c#L112

`pointer` is mapped to `XC_hand1`, `grab` is mapped to `XC_hand2`


It seems that cursors are being inconsistent between various themes. e. g. with Ubuntu 18.04 DMZ-White and DMZ-Black have a correct pointer cursor for `hand1` while Adwaita indeed has a grabbing cursor.

**Comment by kekekeks** [comment]
Qt, on the other hand, seems to be using XC_hand2 which consistently has a correct cursor on all cursor themes I have installed on my machine.

**Comment by kuiperzone** [comment]
Thanks for the update.

**Comment by Takoooooo** [comment]
I think it should be closed by https://github.com/AvaloniaUI/Avalonia/pull/6675
