### ISSUE TITLE
FontFamily="monospace" doesn't appear to work on Windows (0.10.7)

### ISSUE THREAD

**Issue by kuiperzone** [AvaloniaUI/Avalonia#6671]
**Describe the bug**
Setting axaml FontFamily="monospace" for a control does not seem have any effect on Windows, but leaves the font at its default.

**To Reproduce**
I have a control as follows:

```
  <TextBox Name="inputBox" Grid.Row="2"
      VerticalAlignment="Stretch" Watermark="Enter Text"
      FontFamily="monospace" AcceptsReturn="True" TextWrapping="Wrap"/>

```

On Linux, the control's font is indeed monospace. When built and run on Windows, however, the font family appears to be default.

**Screenshots**

On Windows:

![not_mono](https://user-images.githubusercontent.com/17156238/135754486-d00aee36-944f-4bcc-874f-3e17185a8458.jpg)

**Desktop (please complete the following information):**

- OS: Windows 10, Fedora 34
- Version 0.10.7

**Additional context**

A hack-fix in application code solves for the moment, but not really a solution:

```
    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
    {
        _inputBox.FontFamily = new FontFamily("Courier New");
        _resultBox.FontFamily = new FontFamily("Courier New");
    }
```

**Comment by RokeJulianLockhart** [comment]
I expect this would necessitate that Windows come with, by default, the same font aliases that Linux's `fontconfig` does.

**Comment by kuiperzone** [comment]
This was an old post! I guess I was translating thinking from CSS. So long as I understand that it's not supported, that's OK.

**Comment by RokeJulianLockhart** [comment]
@kuiperzone, you should be able to achieve the same functionality in a cross-OS manner by installing a font alias on Windows during application installation. However, I suppose it'd just be easier to hardcode the default OS font based upon a conditional statement within the application's code.

**Comment by kuiperzone** [comment]
Thank you. This was an old post, but I was actually wondering the same thing again. I'm also on Linux now. I've got this covered in the application level code in any case. It's good know. Am grateful.
