### ISSUE TITLE
Console Window shown when running GUI on Windows, (0.10.7)

### ISSUE THREAD

**Issue by kuiperzone** [AvaloniaUI/Avalonia#6672]
When running GUI application on Windows, a Console window is also shown.

I am aware of previous issue which seems to have been (partially) resolved:

https://github.com/AvaloniaUI/Avalonia/issues/1705

However, AND FULL DISCLOSURE, what I am doing is building the application on LINUX and then running the output binary on Windows. If, however, I build AND run the app on Windows, the console window does not appear as expected.

However, it should be possible to build on one system and run on another correctly as .NET 5 offers this.

**To Reproduce**
Here is my csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net5.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ApplicationIcon>Assets/app.ico</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
		<AvaloniaResource Include="Assets\**"/>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia" Version="0.10.7"/>
		<PackageReference Include="Avalonia.Desktop" Version="0.10.7"/>
		<PackageReference Include="Avalonia.Diagnostics" Version="0.10.7"/>
	</ItemGroup>
</Project>
```

Here is the publish command, called on Linux:

`dotnet publish -r win-x64 -c Release --self-contained true -p:DebugType=None -p:DebugSymbols=false -o "AppImages/AppDir"`

**Expected behavior**
A console window in addition to min GUI window should not appear.

**Screenshots**

![dos_win](https://user-images.githubusercontent.com/17156238/135755096-2fa11e75-9865-4473-952a-9412a3a6eed5.jpg)

**Desktop (please complete the following information):**

- OS: Windows 10 (built on Fedora 34)
- Version 0.10.7

**Additional context**
Adding NSubsys package reference (as suggested elsewhere in link above) has no effect.

**Comment by kekekeks** [comment]
Note that it's an issue in .NET SDK, not in Avalonia.

I wonder why NSubsys doesn't work for you, perhaps something has changed in the SDK and the target is no longer being called?
@jmacato

**Comment by kuiperzone** [comment]
>Note that it's an issue in .NET SDK, not in Avalonia.

Perhaps you're right. In which case, there may be a fix from MS at some point.

To emphasise, if I build and run an Avalonia app on Windows, there is no problem. It's only when I build on Linux as win-x64 and then run it on Windows that the console windows shows up.

Thanks for the reply.

**Comment by dot-pulsar** [comment]
I have the same problem, it is very annoying. I have to build the application separately through a virtual machine.

**Comment by grokys** [comment]
This looks to me like a problem with the .NET SDK. Most likely MS haven't encountered it because they don't have a cross-platform UI framework, I'd advise opening an issue at https://github.com/dotnet/sdk/issues

**Comment by jmacato** [comment]
I dont support the NSubsys package anymore. I agree with @grokys that it's a SDK issue. 

for reference @kekekeks :

https://github.com/jmacato/NSubsys/blob/master/build/NSubsys.targets

Seems like i wasnt targeting a specific framework back then, should've worked here but it may just be too old right now.

**Comment by kekekeks** [comment]
I guess for now one could copy-paste the [relevant source code from NSubsys](https://github.com/jmacato/NSubsys/blob/b8d26cfe049299eb657411a1cd1d5223cc476955/NSubsys.cs#L31-L76) and run it as a separate console app during the build process.

**Comment by maxkatz6** [comment]
If you want to get it fixed - make as much noise as possible in dotnet repository. They have related issue for that -
https://github.com/dotnet/runtime/issues/3828

You can use NSubsys code to hack-fix console by changing application type. But it won't fix all other missing parts from the exe - it doesn't have ICON, it doesn't have version information, it doesn't have licensing, it's pretty much minimal abstract app host.

Closing as it has nothing to do with Avalonia itself, we can't do job for them here.
