### ISSUE TITLE
Issues with tool tips on Linux and macOS

### ISSUE THREAD

**Issue by arklumpus** [AvaloniaUI/Avalonia#6677]
**Describe the bug**
I have noticed a couple of issues with ToolTips on Linux and macOS. Everything works fine on Windows.

1. On Linux, sometimes the app will hang when a tool tip closes. This is the same as #3536 ; that was fixed for the default theme, but still happens if the Fluent theme is enabled (see my comment to that issue for an updated repro).

2. On macOS, if `ShowDialog` is called while a tool tip is open, the tool tip will remain open until the child window is closed and the mouse is moved again on the parent window. This happens with both the default theme and the Fluent theme.

**To Reproduce**
To reproduce n. 2:

Create a new project and replace the content of the main window with:

```XAML
<Button Content="Show dialog" ToolTip.Tip="Tool tip" Click="ButtonClicked" />
```

Then add the following method to the `xaml.cs` file:

```CSharp
private async void ButtonClicked(object sender, RoutedEventArgs e)
{
    MainWindow win = new MainWindow();
    await win.ShowDialog(this);
}
```

Publish the app for macOS and run it. Now, place the mouse on the button and wait for the tool tip to appear then, without moving the mouse, click on the button: the tool tip will not disappear while the new window opens.

**Expected behavior**
1. Tool tips should not cause the app to hang.
2. Tool tips should disappear when a new window is opened.

**Desktop (please complete the following information):**

- OS: macOS and Linux (tested on Ubuntu 20.04). Everything works as expected on Windows.
- Version: 0.10.7

**Additional context**
Just in case it helps anyone else looking for a quick workaround to this, in my apps I'm having all windows implement this interface:

```CSharp
internal interface IWindowWithToolTips
{
    List<Control> ControlsWithToolTips { get; }
}
```

Then, I replaced all calls to `ToolTip.SetTip` with calls to the following method:

```CSharp
public static void SetToolTip(Control control, object tip)
{
    if (System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.OSX))
    {
        if (control.FindAncestorOfType<Window>() is IWindowWithToolTips win)
        {
            win.ControlsWithToolTips.Add(control);
        }
        else
        {
            control.AttachedToVisualTree += (s, e) =>
            {
                if (control.FindAncestorOfType<Window>() is IWindowWithToolTips win)
                {
                    win.ControlsWithToolTips.Add(control);
                }
            };
        }

        ToolTip.SetTip(control, tip);
    }
    else if (!System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.Linux))
    {
        ToolTip.SetTip(control, tip);
    }
}
```

Finally, I created the following extension method and I am using it in place of the "normal" `ShowDialog` method:

```CSharp
public static Task ShowDialog2(this Window subject, Window owner)
{
    if (System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.OSX))
    {
        if (owner is IWindowWithToolTips win)
        {
            foreach (Control control in win.ControlsWithToolTips)
            {
                if (ToolTip.GetIsOpen(control))
                {
                    ToolTip.SetIsOpen(control, false);
                }
            }
        }
    }

    return subject.ShowDialog(owner);
}
```

This disables tool tips on Linux (which is not ideal, but better than risking that the app hangs) and "manually" closes them on macOS before opening any dialog window.

**Comment by CyberCat2077** [comment]
Have the similar issue on Linux (Ubuntu 21.10) but without a tooltip. 
When I click to close my app window it's hang on. 
Problem faced only on Avalonia 10.10, 10.9, 10.8.
On Avalonia **10.7** works without any problems - app don't hang when windows closing.

**Comment by ltetak** [comment]
The origin of the problem on **macOS** is in the **PointerLeave** event which is used by ToolTipService
https://github.com/AvaloniaUI/Avalonia/blob/7842883961d094e08e9def7f30cf32fd573179c7/src/Avalonia.Controls/ToolTipService.cs#L36
MacOS window implementation does not handle this well. It ignores cases when the mouse does not move above the original window when leaving.
https://github.com/AvaloniaUI/Avalonia/blob/48477574a68d116d3bb64e4b0e31753f0469dd0c/native/Avalonia.Native/src/OSX/window.mm#L1758-L1763
I don't know objective C too well but something like this should do the trick. Is anybody able to implement this correctly? Everything is described in this SO question.
https://stackoverflow.com/questions/8979639/mouseexited-isnt-called-when-mouse-leaves-trackingarea-while-scrolling

**Comment by stepangovorko** [comment]
Hi, the problem with the stuck tooltip on macOS is still (or again) occurring. You can check it in ControlsCatalog under Dialogs on the latest master
