### ISSUE TITLE
MenuFlyout ingnore local DataTemplate

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#6692]
**Describe the bug**

see #6691

MenuFlyout ingnore local DataTemplate and using Application.DataTemplates

**To Reproduce**

1. Run attached prj
2. Right click on TextBlock

**Expected behavior**

using local DataTemplate

**Screenshots**

**Desktop (please complete the following information):**

- OS: Window
- Version  0.10.7

**Additional context**
[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/7311488/AvaloniaApplication1.zip)

**Comment by almightyju** [comment]
Just came across this with using a split button, as per https://github.com/AvaloniaUI/Avalonia/discussions/6691 setting the data template as part of the split button like this works:

```xml
<SplitButton>
	<SplitButton.DataTemplates>
		<DataTemplate DataType="{x:Type my:CustomType}">
			<MenuItem Header="{Binding Name}"  />
		</DataTemplate>
	</SplitButton.DataTemplates>
	<SplitButton.Flyout>
		<MenuFlyout Placement="Bottom" Items="{Binding MyItems}" />
	</SplitButton.Flyout>
</SplitButton>
```

Would be good if the docs had some sort of note about this issue
