### ISSUE TITLE
When TextTrimming=CharacterEllipsis is set for TextBlock the text is trimmed when layout rounding is enabled and it should not

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#6698]
**Describe the bug**

When TextTrimming=CharacterEllipsis is set for TextBlock the text is trimmed when layout rounding is enabled and it should not as there is enough space for text to be rendered.

**To Reproduce**

https://github.com/wieslawsoltes/Avalonia/commits/TextBlockTextTrimmingCharacterEllipsisRepro

Open MainWindow.axaml from Sandbox project is previewer or run the Sandbox app.

**Expected behavior**

The TextTrimming=CharacterEllipsis  is only applied when there is not enough space for text to fully render.

**Screenshots**

![image](https://user-images.githubusercontent.com/2297442/136763527-fedd56e1-10d5-4ca2-9103-7013ef591d17.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version https://github.com/AvaloniaUI/Avalonia/tree/88d94379fe4384e7d4eff577bbda2dba131a6c44

**Additional context**

**Comment by maxkatz6** [comment]
@wieslawsoltes @Gillibald is this still an issue?
