### ISSUE TITLE
Issues launching avalonia form inside other Mac applications

### ISSUE THREAD

**Issue by teocomi** [AvaloniaUI/Avalonia#6699]
Hello,

I've recently started working on an Avalonia App to replace our current WPF one as a way to get OSX support for our [open source suite of desktop tools](https://github.com/specklesystems/speckle-sharp).

Things have worked out very well so far but we've hit a major roadblock in OSX.

The Avalonia app is launched from within a host app (as an addin/plugin) but on OSX we have two undesired behaviors:

1. the Avalonia app bar menu is taking over the host app one, you can see more info in this discussion here: https://github.com/AvaloniaUI/Avalonia/discussions/6565_
2. the lifecycle of the Avalonia app seems to get mixed with the one of the host app, as when the MainWindow closes the host application is shut down as well

I'm not sure if there is an easy solution to this or maybe I'm just not using Avalonia for what it's meant, but it feels like a solution could be within reach! If issue 1. can be resolved, I believe 2. could be ignored as I could have the MainWindow hide instead of fully close.

**Things I've tried so far.**

I've tried using `MonoMac.Avalonia` to access the `NSApplication` and set the main `NSMenu` to not show, but this also affects the host application main menu.
I've also tried changing how the Avalonia app is launched but could not improve things.

This is my code atm:

 ```csharp

 public static AppBuilder BuildAvaloniaApp()
    {
      string path = Path.GetDirectoryName(typeof(App).Assembly.Location);
      string nativeLib = Path.Combine(path, "Native", "libAvalonia.Native.OSX.dylib");
      return AppBuilder.Configure<DesktopUI2.App>()
      .UsePlatformDetect()
      .With(new X11PlatformOptions { UseGpu = false })
      .With(new MacOSPlatformOptions { ShowInDock = false })
      .With(new AvaloniaNativePlatformOptions
      {
        AvaloniaNativeLibraryPath = nativeLib
      })
      .With(new SkiaOptions { MaxGpuResourceSizeBytes = 8096000 })
      .With(new Win32PlatformOptions { AllowEglInitialization = true, EnableMultitouch = false })
      .LogToTrace()
      .UseReactiveUI();
    }


    protected override Result RunCommand(RhinoDoc doc, RunMode mode)
    {
      try
      {

        if (MainWindow == null)
        {
          Doc = doc;
          BuildAvaloniaApp().Start(AppMain, null);
        }
        else
          MainWindow.Show();
      }
      catch (Exception e)
      {
        Console.WriteLine(e);
      }



      return Result.Success;
    }

    void AppMain(Application app, string[] args)
    {
      var viewModel = new RhinoViewModel();
      viewModel.doc = Doc;
      MainWindow = new MainWindow
      {
        DataContext = viewModel
      };
      MainWindow.Show();


      Task.Run(() => app.Run(MainWindow));
    }

```

**Comment by maxkatz6** [comment]
It's possible now to disable it completely (in nightly)
Done with https://github.com/AvaloniaUI/Avalonia/pull/8061
