### ISSUE TITLE
TextBox.TextInput event is not fired

### ISSUE THREAD

**Issue by jinek** [AvaloniaUI/Avalonia#6710]
**Describe the bug**
When typing text into TextBox the event TextInput is not fired.

**To Reproduce**
1. Generate new project based on "Avalonia .NET Core App"
2. Open MainWindow.axaml and add TextBox with attached event handler to it: `<TextBox TextInput="InputElement_OnTextInput" />`
3. Define method at MainWindow.axaml.cs: 
```
        private void InputElement_OnTextInput(object? sender, TextInputEventArgs e)
        {
            throw new System.NotImplementedException();
        }
```
4. Run the project and type some text into textbox
5. Note that text appears in the textbox and no exceptions happen:
![image](https://user-images.githubusercontent.com/10516222/137014098-ea1e1046-6c30-4090-a566-93ba4c172e9e.png)

**Expected behavior**
Exception is thrown.

**Desktop (please complete the following information):**

- OS: linux, Pop!_OS 21.04
- Version 0.10.8

**Additional information**
I have tried to debug and found that TextInput event is marked as `Handled` by TextBox. If we remove Handled = true then user handler is fired.
![image](https://user-images.githubusercontent.com/10516222/137024710-eeaa2c6b-dac5-4449-99f0-d625f3c40714.png)

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/3491

**Comment by maxkatz6** [comment]
1. Any event can be handled in any time, it's not like anyone can guarantee event to never be handler before your handler. That's how routed events work.
2. There is PropertyChanged event, where you can filter by args.Property.

But in general there are already two issues:
https://github.com/AvaloniaUI/Avalonia/issues/6490
https://github.com/AvaloniaUI/Avalonia/issues/418

**Comment by maxkatz6** [comment]
Closing as there are two another related issues.
