### ISSUE TITLE
Unable to force DataGrid sorting from code-behind

### ISSUE THREAD

**Issue by dark-matter-matters** [AvaloniaUI/Avalonia#6714]
**Describe the bug**
A DataGrid sorted column should be refreshable from code-behind.

**To Reproduce**
Create a DataGrid app. Sort values from UI. Update a value from code-behind (async subscription for example). Fire the `DataGridColumnReorderingEvent` after updating the object from the ObservableCollection bound to the DataGrid. 

**Expected behavior**
The sorting should be updated after the event `DataGridColumnReorderingEvent` fired. The following code does nothing :

```c#
// Code fired after receiving a data update, which changes a value concerned by a sorted column
var MainWindow = (App.Current.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime)?.MainWindow;
var DataGrid1 = MainWindow.FindControl<DataGrid>("DataGrid1");

var viewEvent = RoutedEvent.Register<MainWindowViewModel, RoutedEventArgs>(nameof(DataGrid1.ColumnReordering), RoutingStrategies.Bubble);
// new RoutedEvent("DataGridColumnReordering", RoutingStrategies.Bubble, typeof(RoutedEventArgs), typeof(DataGrid)); // also tried this
var eventArgs = new RoutedEventArgs(viewEvent);
DataGrid1.RaiseEvent(eventArgs);
```
Is this supposed to work ? I couldn't find any way to convert `DataGridColumnReorderingEventArgs` to `RoutedEventArgs`, I'm guessing that's the reason why it is not working.

Ideally, we should be able to call [OnColumnReordering](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls.DataGrid/DataGridColumnHeader.cs#L691) but the method is protected. 
```c#
var MainWindow = (App.Current.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime)?.MainWindow;
var DataGrid1 = MainWindow.FindControl<DataGrid>("DataGrid1");

DataGridColumn colToUpdate = DataGrid1.Columns[0];
var reorderingEventArgs = new DataGridColumnReorderingEventArgs(colToUpdate);
DataGrid1.OnColumnReordering(reorderingEventArgs); // access level forbids this call
```

**Desktop (please complete the following information):**

- Win10 x64
- Version 0.11

**Comment by dark-matter-matters** [comment]
@maxkatz6 Oh I see, thanks for the reply. Isn't there a better workaround than removing / adding back the Object from the collection to force sorting?

**Comment by maxkatz6** [comment]
You can use reflection to access private methods from DataGrid class.
But of course it would be better to have public API for that.

**Comment by dark-matter-matters** [comment]
Well I didn't get much success with the following reflexive call : 
```c#
var protectedMethod = DataGrid1.GetType().GetMethod("OnColumnSorting", BindingFlags.NonPublic | BindingFlags.Instance);
foreach(var colToSort in colsToSort) {
   var reorderingEventArgs = new DataGridColumnEventArgs(colToSort);
   protectedMethod?.Invoke(DataGrid1, new object[] { reorderingEventArgs });
}
```
Reflection looked pretty slow in my context anyways. I'll stick to remove/add. Not sure why the sorting is not updated while the value is correctly updated in the UI though.
