### ISSUE TITLE
Running avalonia template project on WSL2 Ubuntu gives Segmentation fault

### ISSUE THREAD

**Issue by tolgaevcimen** [AvaloniaUI/Avalonia#6715]
**Summary**
Running avalonia template project on WSL2 Ubuntu gives Segmentation fault.

**Environment:**

- WSL2 Ubuntu 20.04 x86_64
- .NET SDK 5.0.402
- Target framework: net5.0
- Avalonia 0.10.8
- Avalonia-Desktop 0.10.8

**Reproduce:**

- Install the `dotnet new` Avalonia templates
- create a new `avalonia.app` or `avalonia.mvvm` project
- build it (`dotnet publish -c release --runtime linux-x64 --self-contained`)
- run either `./ProjectName` or `dotnet Project.Name.dll`
- Segmentation fault

**Expected behavior**
The project to run on Ubuntu.

**Screenshots**
![image](https://user-images.githubusercontent.com/3379942/137203702-80a62f48-19ab-46b5-9efa-0d6358bdff41.png)

**Comment by kekekeks** [comment]
It most likely can't connect to X11. Not sure why that segfaults, but I've observed the same behavior lately. Make sure that you have an X server and WSL environment properly configured.

**Comment by tolgaevcimen** [comment]
I'm able to run xcalc and like programs without any problems. Though I suspect it might be related to that, having it working for other applications makes me think there is something else.

**Comment by kekekeks** [comment]
Not necessary, it might be segfaulting somewhere else.

**Comment by maxkatz6** [comment]
Works for me after that fix. If anybody can reproduce it again - ping me.
