### ISSUE TITLE
Other textures than 0 doesn't work in OpenGlControlBase

### ISSUE THREAD

**Issue by BAndysc** [AvaloniaUI/Avalonia#6727]
**Describe the bug**
Binding a texture to non 0 active texture slot breaks rendering completely.
```
GL.ActiveTexture(GL_TEXTURE1);
GL.BindTexture(GL_TEXTURE_2D, _textureHandle);
 ```

Binding a texture to slot GL_TEXTURE0 works as expected.

At first I thought it is buggy OpenGL implementation in macOS and/or M1 CPU/GPU, but I have tested the project on a Windows machine and it turned out it doesn't work as well. So definitely not related to the machine.

Then I thought I am using OpenGL incorrectly, so I have copied the code to an OpenTK project, but it turned out it works as expected (https://github.com/BAndysc/AvaloniaOpenGLProblem/commit/127e162ac4d8f199aa57bf6f4c88db8ad2ac0fd6).

Therefore it looks like it is some bug in the OpenGL Avalonia integration?

**To Reproduce**
1. Clone https://github.com/BAndysc/AvaloniaOpenGLProblem
2. Checkout commit https://github.com/BAndysc/AvaloniaOpenGLProblem/commit/bff5431cf136fe75fa2e9cc913213df6149354e1
3. See the teapot with a texture is working
4. Checkout commit https://github.com/BAndysc/AvaloniaOpenGLProblem/commit/2f1281d18a7ad94594112afbb8529d6e50608a13
5. See nothing is rendered and 1281 errors are printed to the console (when changing pitch/yaw/roll)

**Expected behavior**
Both GL_TEXTURE0 and GL_TEXTURE1 should work the same, just like in case of OpenTK.

**Screenshots**
Working teapot when using GL_TEXTURE0
![image](https://user-images.githubusercontent.com/5689666/137350420-4c7e67fd-9d5d-4711-97f7-cdbe6d703cf8.png)

Nothing is rendered when using GL_TEXTURE1
![image](https://user-images.githubusercontent.com/5689666/137350362-0f4ecd46-1fdc-49e7-9522-e8703dfcfad5.png)

**Desktop:**

Tested on both independent, different computers:
1. Avalonia 0.10.8, macOS Big Sur, ARM Apple M1, .NET 6.0 (native)
2. Avalonia 0.10.8, Windows 11, x86_64, Intel HD Graphics, .NET 5.0

**Additional context**
The repo contains:
1. Working Avalonia version when using GL_TEXTURE0
2. Not working Avalonia version when using GL_TEXTURE1
3. Working OpenTK version when using GL_TEXTURE1, the code is exactly the same, only global ints were changed into opentk's enums

**Comment by BAndysc** [comment]
Activating GL_TEXTURE0 `GL.ActiveTexture(GL_TEXTURE0);` before finishing rendering helps. Basically Avalonia somewhere assumes texture 0 is active, thank you OpenGL global state

**Comment by maxkatz6** [comment]
Should be closed with https://github.com/AvaloniaUI/Avalonia/pull/8734
If it's still an issue, please let us know
