### ISSUE TITLE
TrayIcon: Baloon / Toast notification support

### ISSUE THREAD

**Issue by FG-rgb** [AvaloniaUI/Avalonia#6734]
Hello,

I want to use the new TrayIcon feature.

But I'm missing the possibility to show a balloon / toast notification.

I have the need for a balloon text, or a custom baaloon like in other UI frameworks
E.g. https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.notifyicon.showballoontip?view=windowsdesktop-5.0
Or http://www.hardcodet.net/wpf-notifyicon/comment-page-5

With best regards.

**Comment by Zilkode** [comment]
@FG-rgb If i may suggest.
I had thee same requirement as yours, i spent hours searching the best solution for Windows notification (toast).
Although it's a Windows 10+ solution i find it partial solution for my purpose, until the awesome Avalonia contributors will work on this matter.

Long story short, if you are looking for Windows toast you can use the native UWP ToastContentBuilder
Head to [](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=desktop) for implementation tutorial.

There are a slight adjustments that need to be done though.
In my case i split my platform dependent hookups to different projects, i.e Windows, Linux, Mac.
I add my platform specific packages to my Windows dependency (that way you can drop irrelevant assemblies per platform).
1. add Nuget package Microsoft.Toolkit.Uwp.Notifications to your project.
2.  The following code is straight forward and ready to use for basic usage:
 new ToastContentBuilder()
                .AddArgument("action", "viewConversation")
                .AddArgument("conversationId", 9813)
                .AddText("Andrew sent you a picture")
                .AddText("Check this out, The Enchantments in Washington!")
                .Show();


Hope you find it useful.

**Comment by maxkatz6** [comment]
Closing this feature request, as we have another for native notifications https://github.com/AvaloniaUI/Avalonia/issues/2155
