### ISSUE TITLE
XAML compiler doesn't deal with leading whitespace properly

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#6765]
**Avalonia (0.10.6 - I am currently stuck on this version so please let me know if it's fixed in a later version):**
![image](https://user-images.githubusercontent.com/1558019/138000202-f4dada32-9fc7-48e6-956a-89006d05a0de.png)

```xml
<ToolTip.Tip>
  <TextBlock>
    Returns a Domino build given a:&#x0a;
    - Build Number (e.g. 16.0.11217.10000)&#x0a;&#x0a;
    Returns the last 2 Domino builds given a:&#x0a;
    - Leave Blank for Daily Builds
  </TextBlock>
</ToolTip.Tip>
```

**Vanilla WPF:**
![image](https://user-images.githubusercontent.com/1558019/138000244-7ca782b9-d191-4687-b26e-1a924a72524e.png)

```xml
<StackPanel.ToolTip>
    <TextBlock>
        Returns a Domino build given a:<LineBreak />
        - Build Number (e.g. 16.0.11217.10000)<LineBreak /><LineBreak />
        Returns the last 2 Domino builds given a:<LineBreak />
        - Leave Blank for Daily Builds
    </TextBlock>
</StackPanel.ToolTip>
```

**Expected behavior:**

I would expect the visual result in Avalonia to look the same as the vanilla WPF visual result, but the Avalonia version adds a bunch of space in front of every line after the first line (probably due to the spacing in the xaml file).

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 0.10.6

**Comment by derekantrican** [comment]
Also note that long lines will get cut off in the tooltip:
![image](https://user-images.githubusercontent.com/1558019/138001092-6f331746-1f35-4b88-b7e4-81e8b0f81e76.png)

```xml
<ToolTip.Tip>
  <StackPanel>
    <TextBlock>
      Lorem ipsum dolor sit amet,&#x0a;consectetur adipiscing elit, sed do&#x0a;eiusmod tempor incididunt ut labore et dolore magna aliqua.&#x0a;Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur
    </TextBlock>
  </StackPanel>
</ToolTip.Tip>
```

**Comment by maxkatz6** [comment]
Weird problem with tooltip, it's shouldn't be limited by height, and shouldn't be cut. Do you have any styles on tooltip? Or can you check in devtools what is limiting the height?

**Comment by maxkatz6** [comment]
About whitespaces in the beginning of lines, I believe this PR did fixed it, but wasn't merged.
https://github.com/kekekeks/XamlX/pull/43

@kekekeks what do you think, can it be merged? I am not sure if we consider it as a breaking change.

**Comment by derekantrican** [comment]
I don't have any styles on tooltip. But I can look at devtools when I'm back at work tomorrow

**Comment by derekantrican** [comment]
@maxkatz6 any tips for investigating ToolTip size in devtools? I don't know if I can pause the app with the tooltip open & look at devtools (so I don't have to keep my cursor there) or what else I should be looking for

**Comment by maxkatz6** [comment]
Works good to me. I have only a style for background.

![Screen Shot 2021-10-20 at 3 21 52 PM](https://user-images.githubusercontent.com/3163374/138158192-a1cdbba5-7925-4949-9efa-6e7c8dfaed4c.png)

**Comment by maxkatz6** [comment]
Fixed in master https://github.com/kekekeks/XamlX/pull/43
