### ISSUE TITLE
Italic text is getting clipped

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#6767]
**Describe the bug**
Setting `FontStyle="Italic"` is clipping the end of the text. HorizontalAlignment needs to be left so that the textblock sizes to the text. Some fonts are worse than others like the new Windows 11 font Segoe UI Variable is particularly bad

![image](https://user-images.githubusercontent.com/40413319/138019220-c22337df-5ef4-487d-a0e5-6923f18479ee.png)

````
<TextBlock Text="Arial"
	  FontStyle="Italic"
	  FontFamily="Arial"
	  HorizontalAlignment="Left"
	  VerticalAlignment="Top"
	  Background="#15000000" />

<TextBlock Text="Segoe UI"
	  FontStyle="Italic"
	  FontFamily="Segoe UI"
	  HorizontalAlignment="Left"
	  VerticalAlignment="Top"
	  Background="#15000000" />

<TextBlock Text="Segoe UI Variable Text"
	  FontStyle="Italic"
	  FontFamily="Segoe UI Variable Text"
	  HorizontalAlignment="Left"
	  VerticalAlignment="Top"
	  Background="#15000000" />
````

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win 11
- Version 0.10.8

**Additional context**

**Comment by Gillibald** [comment]
WPF
![Screenshot 2023-05-12 082859](https://github.com/AvaloniaUI/Avalonia/assets/5928797/8312b5c5-9007-453d-ba18-396f8ba9b883)
Avalonia
![Screenshot 2023-05-12 082935](https://github.com/AvaloniaUI/Avalonia/assets/5928797/d2210929-da8b-4299-9fe0-533811bd6de8)
