### ISSUE TITLE
AvaloniaXamlLoader.Load(xaml) no longer produce Window object

### ISSUE THREAD

**Issue by ALIENQuake** [AvaloniaUI/Avalonia#6777]
**Describe the bug**
AvaloniaXamlLoader.Load(xaml) no longer produce Window object

**Expected behavior**
A way to initialize Avalonia Window via loading xaml.

**Additional context**
Hello,

I'm using Avalonia via PowerShell. In order to do this, I'm using PSAvalonia Module. I'm not the author, but I want to update the Avalonia version inside that module from 8.x to 10.x. Unfortunately, this presents a significant challenge due to recent 'Application initialization and lifetime changes'. 

The most important code of the PowerShell Binary Module is here: https://github.com/ALIENQuake/psavalonia/blob/master/src/PSAvalonia/AvaloniaBootstrapper.cs
My fork contains an additional executable so it is possible to debug the module itself directly from c#/VS.

For Avalonia 8.x this code works:
```
public static Window Load(string xaml)
{
    var loader = new AvaloniaXamlLoader();
    return (Window)loader.Load(xaml);
}
```

but after updating to Av 10.x:

1. The AvaloniaXamlLoader is a static class, but even if I'm using AvaloniaXamlLoader.Load(xaml) I'm not receiving Window object `Cannot convert type 'void' to 'Avalonia.Controls.Window'`

```
        public static Window Load(string xaml)
        {
            BootstrapWindow win = new BootstrapWindow(xaml);
            return win;
        }
```

2. Adding this piece of code didn't help either
```
    public class BootstrapWindow : Window
    {
        public BootstrapWindow(string xaml)
        {
            InitializeComponent(xaml);
        }

        private void InitializeComponent(string xaml)
        {
            AvaloniaXamlLoader.Load(xaml);
        }
    }
```

3. AvaloniaXamlLoader.Load can load xaml from Uri, but it also doesn't return Window. According to Docs it should: http://reference.avaloniaui.net/api/Avalonia.Markup.Xaml/AvaloniaXamlLoader/742BE11A

```
public static Window Load(string xaml)
{
    Uri uri = new Uri(xaml, UriKind.Absolute);
    var test = AvaloniaXamlLoader.Load(uri);
    var window = (Window)AvaloniaXamlLoader.Load(uri);
    return window;
}
```

4. Using `var window = (Window)AvaloniaRuntimeXamlLoader.Load(xaml)` also didin't return Window object

Xaml that I'm using:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="PSAvalonia.MainWindow"
        Title="PSAvalonia">
   <StackPanel>
<Button Width="160" Name="button">My Button</Button>
        <TextBox HorizontalAlignment="Left" Margin="12,12,0,0" Name="txtDemo" VerticalAlignment="Top" Width="500" Height="25" />
    </StackPanel>
</Window>
```

Can someone help me with this?

**Comment by MaynardMiner** [comment]
```
public static Window Load(string xaml)
{
    var loader = new AvaloniaXamlLoader();
    return (Window)loader.Load(xaml);
}
```

It's mainly why this doesn't work anymore, and how to work around. I know AvaloniaXamlLoader is now a static method that can be used for a uri, but we've both been trying to make a way to produce a window object for Powershell purposes.

We effectively need a new way to parse a xaml string into a Window object.

**Comment by maxkatz6** [comment]
> Using var window = (Window)AvaloniaRuntimeXamlLoader.Load(xaml) also didin't return Window object

What does it return for you?

There is also a ```AvaloniaRuntimeXamlLoader.Parse<Window>(xaml, assembly)```;
Either way should work and we have tests for it https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Markup.Xaml.UnitTests/Xaml/BasicTests.cs#L176

**Comment by smartguy1196** [comment]
> Just load `PSAvalonia.MainWindow` type before calling the runtime XAML parser. It will discover the assembly if it's already in memory.
> 
> Also, check if that type even exists. 0.8 might have been just ignoring x:Class attribute. In that case you can safely remove `x:Class` attribute

The issue is that PSAvalonia's purpose is to reproduce this https://blog.ironmansoftware.com/wpf-vs-code-powershell/ cross-platform, which means that there is no assembly to load. Just the XAML.

**Comment by smartguy1196** [comment]
Though I do think if I use the Runtime Xaml Loader, I should be able to fix PSAvalonia's issues with 0.10.x. I'll give it a try and come back

**Comment by smartguy1196** [comment]
Initially, I'm getting a build error:

```
AvaloniaBootrapper.cs(28,20): error CS0103: The name 'AvaloniaRuntimeXamlLoader' does not exist in the current context
```

I think I need to update PSAvalonia's dependencies...

**Comment by smartguy1196** [comment]
Alright I got it to work. No help needed, so ignore my comments lol

**Comment by stephannn** [comment]
Sorry to hijack this post, but I cannot really follow.
On Ubuntu 22.04, PWSH 7 and.Net8, I have the same issue that @ALIENQuake was mentioning about the AvaloniaBootstrapper.Load. When I remove the class from the XAML I get just a windows frame with a transparent window that cannot be closed. I also added the mentioned MainWindow class but nothing. By calling the Show-AvaloniaWindow function I get additionally to the transparent window the message:  O_peration is not supported on this platform_.
My current Avalonia Version is 11.0.6.
Thanks
Stephan

**Comment by ALIENQuake** [comment]
@stephannn The PSAvalonia module was never updated to cover the latest Avalonia changes. You might try to get lucky with my [fork](https://github.com/ALIENQuake/psavalonia).

**Comment by stephannn** [comment]
Hi @ALIENQuake,
thanks a lot. I took your AvaloniaBootstrapper.cs and it seems to be working. At least the first test ;)
At first I took the repository from @pinuke and I think I checked also the others forks, but they were all updated 5 years ago the last time. Now I can I start to play around with it a little bit, thanks again!

**Comment by anonhostpi** [comment]
@stephannn You can also try taking a look at my Import-Package module. It is similar to Import-Module which was designed to work with PowerShell .nupkgs.

Import-Package is designed to work with C# .nupkgs which can be installed by PackageManagement (Get-Package, Install-Package, Update-Package, etc).

I originally designed it to play nicely with both Python.NET and Avalonia.Desktop. I used Avalonia, primarily for its dispatcher loop though.

You can find my Python.NET example here: https://www.reddit.com/r/PowerShell/comments/192uavr/turning_powershell_into_a_python_engine/
