### ISSUE TITLE
New Project: Cannot Install Packages

### ISSUE THREAD

**Issue by srsgores** [AvaloniaUI/Avalonia#678]
![image](https://cloud.githubusercontent.com/assets/1750837/17545248/5e750358-5e99-11e6-99a6-addc1f789672.png)

When I create a new application, [as per the directions listed on your Getting Started](https://github.com/AvaloniaUI/Avalonia/blob/master/docs/tutorial/gettingstarted.md)

**Comment by wieslawsoltes** [comment]
You probably need to add in Visual Studio new NuGet Package Source:

Go to `Options`, search for `NuGet` and in `Package Source` click `+` button and input:

Name:  `api.nuget.org`
Source: `https://api.nuget.org/v3/index.json`

**Comment by srsgores** [comment]
Just checked, and I already have that:

![image](https://cloud.githubusercontent.com/assets/1750837/17547066/558f4a74-5ea2-11e6-9008-e6d5cdfc6eb9.png)

**Comment by grokys** [comment]
@srsgores could you check which version of the "NuGet Package Manager for Visual Studio 2015" you have installed? It should be version 3.5.

**Comment by srsgores** [comment]
I just checked, and I have `3.4.4`:

![image](https://cloud.githubusercontent.com/assets/1750837/17579363/b3e9ce50-5f51-11e6-90cd-4c243adde882.png)

I don't see version 3.5.  Where can I find and install it?

**Comment by Mafii** [comment]
Installing Update 3 for Visual Studio 2015 solved the problem for me.

**Comment by srsgores** [comment]
Just installed update.  All is working well.
