### ISSUE TITLE
Window with SystemDecorations set to "BorderOnly" cannot be resized

### ISSUE THREAD

**Issue by macabrett** [AvaloniaUI/Avalonia#6786]
**Describe the bug**
If you have a Window with SystemDecorations="BorderOnly" and CanResize="True", there is no way to grab and resize a window. I'm not sure there's a real difference between "BorderOnly" and "None".

**To Reproduce**

1. Create a new Avalonia project from the template Avalonia.NETCoreMVVMApp (I did this in Rider)
2. On the MainWindow set SystemDecorations="BorderOnly" and CanResize="True"
3. Run the application
4. UNEXPECTED BEHAVIOR: cannot resize the window by dragging from the edges or corners.

**Expected behavior**
A window with SystemDecorations="BorderOnly" and CanResize="True" should be resiable.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 0.10.8

**Additional context**
I am using the fluent theme, same problem for both light and dark versions.

**Comment by tofutim** [comment]
Same on a Mac. No grips to resize. Cannot move window. MacOS Big Sur.
