### ISSUE TITLE
Managed system dialog level up dialog not fully rendered

### ISSUE THREAD

**Issue by bcssov** [AvaloniaUI/Avalonia#6801]
**Describe the bug**
Avalonia 0.10.9 seems to have broken Managed System Dialog Level up button on Fluent theme when using Compact style.
Without compact style
![2021-10-27_8-13-10](https://user-images.githubusercontent.com/5864390/139010343-ebd066d9-c02d-41fb-99f8-45d5c259a152.png)
With compact style
![2021-10-27_8-13-50](https://user-images.githubusercontent.com/5864390/139010371-38c3849e-0498-4514-842c-fbd0c607a453.png)

**To Reproduce**
1. Setup a new empty project
2. In app.xaml add
```StyleInclude Source="avares://Avalonia.Themes.Fluent/DensityStyles/Compact.xaml```
3. Open a file dialog
```            var dialog = new OpenFileDialog
            {
                Title = "test",
                Filters = new System.Collections.Generic.List<FileDialogFilter>() { },
                AllowMultiple = false
            };
            var result = dialog.ShowAsync(this);
```

**Expected behavior**
For the level up button to properly render

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 0.10.9

**Comment by emmauss** [comment]
This looks like you are applying  Fluent Compact style over the base Default theme, and not the base Fluent Theme. The Level Up button in the fluent theme is on the left, and it's a simple geometry path icon, and not a picture.
