### ISSUE TITLE
ScrollBar AutoHide not working as expected

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/Avalonia#6825]
When the ScrollBar is hidden, it still overlaps the window content.  I had expected it to allow the window content to show.  In this screen shot, I've set the background of scrollbars to cyan to highlight this:
![Screen Shot 2021-10-29 at 6 04 19 PM](https://user-images.githubusercontent.com/62225294/139512808-3c5d643f-2a2c-42b9-8719-1e22f8cf61d6.png)

This is the XAML for the window in question.  I've used the mouse to shrink the window until the scroll bar overlaps the content:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:ListBoxScrollBar.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="ListBoxScrollBar.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="ListBoxScrollBar">

  <Design.DataContext>
    <vm:MainWindowViewModel/>
  </Design.DataContext>

    <Window.Styles>
      <Style Selector="Window">
        <Setter Property="Width" Value="400" />
        <Setter Property="Height" Value="400" />
      </Style>
      <Style Selector="ScrollBar">
        <Setter Property="AllowAutoHide" Value="true" />
        <Setter Property="Background" Value="Cyan" />
      </Style>
    </Window.Styles>

  <Grid ColumnDefinitions="*,*">
    <DataGrid Grid.Column="0" Items="{Binding Words}" AutoGenerateColumns="True" VerticalScrollBarVisibility="Visible">
    </DataGrid>
    <ListBox Grid.Column="1" Items="{Binding Strings}">
    </ListBox>
  </Grid>

</Window>

```

**Comment by radoslawik** [comment]
ScrollViewer content always takes all the space available, which will cause overlap if the scrollbar is visible. A simple workaround is to limit the `ScrollContentPresenter` to only one grid column and row inside the `ScrollViewer` template (change [those two lines](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/ScrollViewer.xaml#L28)). This will however change the size of your content when the scrollbar visibility changes.

**Comment by mrj001** [comment]
I don't think I want to change the size of the content when the scrollbar autohides. For some content, I suspect that would cause undesirable re-arranging of the content.

The problem is that when the scrollbar is _not_ visible, it still hides the content that is behind it.  I'm thinking that I should be able to see the content behind the scrollbar when the scrollbar is hiding.

I've simulated my expectation here by cutting out the "background" of the scroll bar that remains behind:
![Screen Shot 2021-10-29 at 6 04 19 PM copy](https://user-images.githubusercontent.com/62225294/140966905-27f03fbf-6c85-4d54-9b2b-3a427a0fc773.png)

I don't mean this simulation to imply that the scroll viewer should change in width when the scroll bar is hidden.  I've just cut out part of my previous screen shot to show that I'd expect the content behind the scrollbar to become visible when the scrollbar is hidden.
