### ISSUE TITLE
ScrollBar AllowAutoHide="false" not honoured by ListBox.

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/Avalonia#6826]
When setting a ScrollBar style with AllowAutoHide set to false, the vertical scroll bar on a List Box does not honour this.

This screenshot shows the issue. The ScrollBar on the DataGrid on the left is showing correctly.  The ScrollBar on the ListBox on the right is still auto-hiding.  I've set the style to a background of cyan to confirm that the style is being applied.

![Screen Shot 2021-10-29 at 6 19 20 PM](https://user-images.githubusercontent.com/62225294/139513403-ef5da4a4-d6e0-4a38-88d4-d30dd31291c6.png)

This is the XAML of the window in the screen shot:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:ListBoxScrollBar.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="ListBoxScrollBar.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="ListBoxScrollBar">

  <Design.DataContext>
    <vm:MainWindowViewModel/>
  </Design.DataContext>

    <Window.Styles>
      <Style Selector="Window">
        <Setter Property="Width" Value="400" />
        <Setter Property="Height" Value="400" />
      </Style>
      <Style Selector="ScrollBar">
        <Setter Property="AllowAutoHide" Value="false" />
        <Setter Property="Background" Value="Cyan" />
      </Style>
    </Window.Styles>

  <Grid ColumnDefinitions="*,*">
    <DataGrid Grid.Column="0" Items="{Binding Words}" AutoGenerateColumns="True" VerticalScrollBarVisibility="Visible">
    </DataGrid>
    <ListBox Grid.Column="1" Items="{Binding Strings}">
    </ListBox>
  </Grid>

</Window>

```

**Comment by radoslawik** [comment]
The `ScrollBar` control is inside the template of `ScrollViewer` and there is a template binding set for its `AllowAutoHide` property, which will override your style. I think this behavior is exactly what we should expect, otherwise, it would not be possible to change any value set by the style.

**Comment by mrj001** [comment]
OK.  I think I understand why this is.  While it did surprise me, it would be more surprising to someone using a ScrollViewer if setting a property on a ScrollBar overrode a property setting on the ScrollViewer

Thanks to @StipecMV for the idea.

Closing this issue as "works as intended".
