### ISSUE TITLE
Weird default style triggers for some basic controls like Button

### ISSUE THREAD

**Issue by tvass83** [AvaloniaUI/Avalonia#6828]
First of all, thanks for bringing us this great product! Really appreciated!

**Describe the bug**
Button and many other controls (like ToggleButton, CheckBox etc) provide default style triggers, like the one for pointerover here:
https://github.com/AvaloniaUI/Avalonia/blob/bbfb2c17d6ddc2b545e378e8b480fae0ac830707/src/Avalonia.Themes.Fluent/Controls/Button.xaml#L45-L46

This (and similarly constructed) trigger(s) (i.e. ones using a TemplateSelector) somewhat contradict with the TemplateBinding in the default ControlTemplate:
https://github.com/AvaloniaUI/Avalonia/blob/bbfb2c17d6ddc2b545e378e8b480fae0ac830707/src/Avalonia.Themes.Fluent/Controls/Button.xaml#L28-L30

As a simple Style like this will not function correctly anymore, at least visually:
```
<Style Selector="Button:pointerover">
    <Setter Property="Background"
            Value="Red" />
</Style>
```

DevTools will show me that the Button has Red background, but the rendering will use the IBrush "ButtonBackgroundPointerOver".

I understand there are several ways to work this around, but why not rely on that TemplateBinding in the first place?
Is there a good reason to use a TemplateSelector in these default style triggers?
If so, what am I missing?

**To Reproduce**
```
<Window.Resources>
    <SolidColorBrush x:Key="ButtonBackgroundPointerOver"
                     Color="Green" />
</Window.Resources>

<Window.Styles>
    <Style Selector="Button:pointerover">
        <Setter Property="Background"
                Value="Red" />
    </Style>
</Window.Styles>

<Button Content="hello" />
```

1. Use the above xaml within a Window
![image](https://user-images.githubusercontent.com/31535082/139557615-986c6081-7b46-4334-acdc-3783b1ba76b6.png)

**Expected behavior**
My Button should render with Red background, instead of Green, when hovering over it.

**Desktop:**
- OS: Windows
- Version 0.10.10

**Comment by tvass83** [comment]
@kekekeks @grokys Would appreciate if one of you guys clarified this a little bit for me.

**Comment by maxkatz6** [comment]
This page should help you with your problem
https://docs.avaloniaui.net/docs/styling/troubleshooting

**Comment by tvass83** [comment]
@maxkatz6 Thanks for your feedback. 
I'm aware of those docs, and I mentioned in the description that I know how to work these issues around.
This issue is more about pointing out a flaw in the default style triggers.

**Comment by tvass83** [comment]
Closing, as it seems to be intentional as per #2662.
Thanks @maxkatz6 for pointing this out!
