### ISSUE TITLE
Modal window dissapears on macOS FullScreen mode

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#6866]
**Describe the bug**
It only happens when you execute the Avalonia as an [Application bundle](https://docs.avaloniaui.net/docs/distribution-publishing/macos). Note that it works as expected when debugging it from Visual Studio code or executing ```dotnet run```.

When using the macOS FullScreen mode, displaying a modal window causes the app to behave erratically. See the following video for further details: https://www.loom.com/share/ab2258452efe470abaa3c3d9bd4cfb08
<a href="https://www.loom.com/share/ab2258452efe470abaa3c3d9bd4cfb08">
<img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/ab2258452efe470abaa3c3d9bd4cfb08-with-play.gif">
  </a>

**To Reproduce**
1. Clone https://github.com/danipen/FullScreenModal
2. Execute ```dotnet restore```
3. Execute ```msbuild -t:BundleApp -p:RuntimeIdentifier=osx-x64 -p:UseAppHost=true```

**Screenshots**
https://www.loom.com/share/ab2258452efe470abaa3c3d9bd4cfb08

**Desktop (please complete the following information):**
- OS: Mac, Big Sur 11.6
- Version 0.10.10

**Additional context**
Note that it only happens when **generating the Application bundle**. It works fine when debugging it from Visual Studio code or executing ```dotnet run```.

**Comment by grokys** [comment]
I've looked into this and it definitely looks like the problem is caused by it being in a bundle. If I extract the binaries from the bundle and run them standalone it works fine.
