### ISSUE TITLE
ContextMenu doesn't close when closing parent window

### ISSUE THREAD

**Issue by berruezo** [AvaloniaUI/Avalonia#6893]
**Describe the bug**
When a ContextMenu is opened inside a window, and then the user closes the window while the ContextMenu is still open, the window closes but the menu is still visible, and can't be closed 

**To Reproduce**
1. Open two windows on an application (in order to avoid the application to exit when closing the window)
2. On one of them, open a ContextMenu
3. Close the window by clicking on the X, while the context menu is still open
4. The window will be closed, and the context menu will still be visible
5. The menu can't be closed, so you can repeat this process over and over

**Expected behavior**
The context menu should disappear when the parent window is closed

**Screenshots**

![image](https://user-images.githubusercontent.com/28261333/140904458-d3cbf9d9-a458-4fca-ba67-15a7b6baaca0.png)

**Desktop (please complete the following information):**

- OS: Linux (Ubuntu 20.04) and macOS
- Version 0.10.9

**Comment by maxkatz6** [comment]
Should have been fixed in 0.10.11
