### ISSUE TITLE
DataGrid SelectedItem not working after each row is clicked by RIGHT mousebutton

### ISSUE THREAD

**Issue by Megapit** [AvaloniaUI/Avalonia#6898]
**Describe the bug**
Hi
I added a plain Avalonia programm to this bug report. 
On the main window there is only a datagrid with 4 lines.
After click on each line with the right mousebutton the "SelectedItem" property is not updated any more.

**Expected behavior**
SelectedItem sould be updated antime it changes

**Desktop (please complete the following information):**
Win10 Pro
VS2019 Pro
.Net 5.0

**Additional context**
attached a file with code
[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/7505593/AvaloniaApplication1.zip)

**Comment by Megapit** [comment]
Hi
I've tryed to Git and compile the complete Avalonia repository and find the bug by myself. 
To be honest it is far beyond my skills. But in the end i was able to copmile it and use the ControlCatalog.NetCore for testing.

Nevermind: I think i found the problem.

in DataGrid.cs there is a an function
 `private bool UpdateStateOnMouseRightButtonDown(PointerPressedEventArgs pointerPressedEventArgs, int columnIndex, int slot, bool allowEdit, bool shift, bool ctrl)`

i changed: 
`// Unselect everything except the row that was clicked on
            try
            {
                UpdateSelectionAndCurrency(columnIndex, slot, DataGridSelectionAction.SelectCurrent, scrollIntoView: false);
            }
            finally
            {
                NoSelectionChangeCount--;
            }`

to:
`// Unselect everything except the row that was clicked on
            try
            {
                **_noSelectionChangeCount++;**
                UpdateSelectionAndCurrency(columnIndex, slot, DataGridSelectionAction.SelectCurrent, scrollIntoView: false);
            }
            finally
            {
                NoSelectionChangeCount--;
            }`

that fixed my problem. 

Can someone who has access to the code confirm this and change the code so that the latest nightly builds in nuget have this changes?

Greets Peter

**Comment by 0x90d** [comment]
> Can someone who has access to the code confirm this and change the code so that the latest nightly builds in nuget have this changes?

I've implemented the missing selection on right click and yes, your change should fix it. Thanks for the PR Peter

**Comment by Megapit** [comment]
> May I ask you where do you get the nightly nuget versions from? As the nightly nuget publish is broken and I'm really looking forward to this fix as well, see #6578 

At the end i pulled the complete stable, made my changes and copied the controls.datagrid.dll to my project.

I only suggest to implement it to nightly nuget so others can have this fix quicker :)
