### ISSUE TITLE
MenuItem.DataTemplates brakes default template/style

### ISSUE THREAD

**Issue by dojo90** [AvaloniaUI/Avalonia#6905]
I originally opened the issue at https://github.com/AvaloniaCommunity/Material.Avalonia/issues/119.
However, it has nothing to do with the `Material.Avalonia` design, as it is 100% based on the same source code as `Avalonia`.

Please refer:

`Avalonia.MenuItem` https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml#L87
`Material.Avalonia.MenuItem` https://github.com/AvaloniaCommunity/Material.Avalonia/blob/dev/Material.Styles/MenuItem.xaml#L55

So, if I can only define the `header` with the `DataTemplate`, what is it intended for or what do I need the `DataTemplate` for?

original Issue
---

When using a `DataTemplate` for the `MenuItem` to dynamically create the `Menu`, the default style seems to be broken

![grafik](https://user-images.githubusercontent.com/17551597/137912294-b06cc9ab-a5c6-46f3-bd53-ec06e7b83fbc.png)

```xaml
<Menu Grid.Column="4" Height="32" Padding="0" Margin="0">
  <MenuItem Height="32" Width="32" Name="FuncMenuItem" Header="{avalonia:MaterialIconExt DotsVertical, Size=24}">
	<MenuItem.DataTemplates>
	  <DataTemplate DataType="app:FuncMenuCommandItem">
		<MenuItem Header="{Binding Name}" Command="{Binding Command}" CommandParameter="{Binding CommandParameter}">
		  <MenuItem.Icon>
			<avalonia:MaterialIcon Kind="{Binding Icon}" Width="24" Height="24" />
		  </MenuItem.Icon>
		</MenuItem>
	  </DataTemplate>
	  <DataTemplate DataType="app:FuncMenuSeparatorItem">
		<Separator/>
	  </DataTemplate>
	</MenuItem.DataTemplates>
  </MenuItem>
</Menu>
```

![grafik](https://user-images.githubusercontent.com/17551597/137912671-6a64dac3-07e3-47f7-b279-20316bc5f907.png)

while using the default xaml definition from the `Material.Demo` application, looks fine.

![grafik](https://user-images.githubusercontent.com/17551597/137912823-d5212717-f2ca-4ce3-b71f-68783255215c.png)

```xaml
<Menu Grid.Column="4" Height="32" Padding="0" Margin="0">
  <MenuItem Height="32" Width="32" Name="FuncMenuItem" Header="{avalonia:MaterialIconExt DotsVertical, Size=24}">
	<MenuItem Header="Hello!" Click="HelloButtonMenuItem_OnClick">
	  <MenuItem.Icon>
		<avalonia:MaterialIcon Kind="Hand" Width="24" Height="24" />
	  </MenuItem.Icon>
	</MenuItem>
	<Separator />
	<MenuItem Header="Action 1" />
	<MenuItem Header="Action 2" />
	<MenuItem Header="Action 3" />
	<Separator />
	<MenuItem Header="Goodbye" Click="GoodbyeButtonMenuItem_OnClick">
	  <MenuItem.Icon>
		<avalonia:MaterialIcon Kind="ExitRun" Width="24" Height="24" />
	  </MenuItem.Icon>
	</MenuItem>
  </MenuItem>
</Menu>
```

working workaraund
---

```cs
// FuncMenu
var funcMenuBuilder = App.Container.GetRequiredService<IFuncMenuBuilder>();
// https://github.com/AvaloniaCommunity/Material.Avalonia/issues/119
// FuncMenuItem.Items = funcMenuBuilder.FuncMenuItems;
var items = new ObservableCollection<TemplatedControl>();
foreach (var item in funcMenuBuilder.FuncMenuItems)
{
	switch (item)
	{
		case FuncMenuSeparatorItem funcMenuSeparatorItem:
			items.Add(new Separator());
			break;
		case FuncMenuCommandItem funcMenuCommandItem:
			var mi = new MenuItem
				{
					Header = funcMenuCommandItem.Name,
					Command = funcMenuCommandItem.Command,
					CommandParameter = funcMenuCommandItem.CommandParameter,
					Icon = new MaterialIcon
					{
						Kind = funcMenuCommandItem.Icon
					}
				};
			items.Add(mi);
			break;
		default:
			throw new ArgumentOutOfRangeException(nameof(item));
	}
}

FuncMenuItem.Items = items;
```

**Comment by maxkatz6** [comment]
It's not a bug, you are not changing template of items by adding new templates to the DataTemplates. Instead you are telling menu to use your templates inside of MenuItem.Content, basically making menuitem inside of menuitem. 

I am pretty sure you want to have something like this: https://github.com/AvaloniaUI/Avalonia/issues/3100#issuecomment-753452752
https://docs.avaloniaui.net/docs/controls/menu

**Comment by dojo90** [comment]
Thanks for the feedback!
How can I implement a type distinction using `Style.Selector`? I currently have two different types (`FuncMenuSeparatorItem` -> `Separator` & `FuncMenuCommandItem` -> `classic MenuItem with command`) and would like to create a separate `DataTemplate` for each.

I currently have no use case in mind for which I can currently use the `DataTemplate`, for which I have to dynamically adapt the MenuItem.Content.

**Comment by maxkatz6** [comment]
Specifically for separator MenuItem you can write this https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml#L263
```xml
  <Style Selector="MenuItem:separator">
```
