### ISSUE TITLE
DataGrid Multibinding

### ISSUE THREAD

**Issue by jangernert** [AvaloniaUI/Avalonia#6906]
I'm trying to use a MultiBinding to bind to a DataGridTextColumn.

```
<DataGrid x:Name="DataGrid" Items="{Binding Data}" AutoGenerateColumns="False" CanUserResizeColumns="True" CanUserReorderColumns="True" IsReadOnly="True">
    <DataGrid.Columns>
        <DataGridTextColumn Header="Length">
            <DataGridTextColumn.Binding>
                <MultiBinding Converter="{StaticResource measurementConverter}" Mode="OneTime">
                    <Binding Path="Length"/>
                    <Binding ElementName="DataGrid" Path="DataContext.RoundingConfiguration"/>
                </MultiBinding>
            </DataGridTextColumn.Binding>
        </DataGridTextColumn>
        <DataGridTextColumn Header="Width" Binding="{Binding Width, Mode=OneTime}" />
        <DataGridTextColumn Header="Height" Binding="{Binding Height, Mode=OneTime}" />
    </DataGrid.Columns>
</DataGrid>
```

```
public class MainWindowViewModel : ViewModelBase
{
    public List<Measurement> Data { get; set; }
    public RoundingConfiguration RoundingConfiguration { get; init; }

    public MainWindowViewModel()
    {
        RoundingConfiguration = new RoundingConfiguration() { D = 0.02f };

        var list = new List<Measurement>();
        for (int i = 0; i < 5; i++)
        {
            float val = 1.0f + 0.01f * i;
            list.Add(new Measurement() { Width = val, Length = val, Height = val});
        }
        Data = list;
    }
}
```

```
public sealed class MeasurementConverter : IMultiValueConverter
{
    public object Convert(IList<object> values, Type targetType, object parameter, CultureInfo culture)
    {
        float dimension = (float)values[0];
        RoundingConfiguration roundingConfiguration = values[1] as RoundingConfiguration;
        uint decimals = 2;
        return dimension.ToString($"N{decimals}", CultureInfo.InvariantCulture);
    }
}
```

The binding to a simple path is not working with the multi binding (`<Binding Path="Length"/>`) but works correctly with the single binding (`Binding="{Binding Width, Mode=OneTime}"`).

This stackoverflow thread suggests that this should work or has worked in the past (with WPF) as the issue was just not converting the return value to a string: https://stackoverflow.com/questions/42592321/multibinding-not-working-in-datagridtextcolumn

`values[0]` in the converter is always "unset" as can be seen in the second screenshot.

The complete minimal sample to reproduce the issue can be found here: https://gitlab.com/JanGernert/datagrid-minimal-sample

![Screenshot from 2021-11-10 10-43-45](https://user-images.githubusercontent.com/12012494/141089497-912fe520-509f-4f55-97b9-4e640a0d0f65.png)

![Screenshot from 2021-11-10 10-46-07](https://user-images.githubusercontent.com/12012494/141089887-b101b0d7-affb-4ae3-905b-6c051d7050de.png)

- OS: Windows 10 & Fedora 35
- Version 0.10.10 & CI build (16d10238a9cbf7de2d71ecd6506db8c73dfd8acc)

**Comment by vikkio88** [comment]
did you ever managed to solve this? the docs on multibinding is really poor unfortunately.

**Comment by maxkatz6** [comment]
@jangernert 
I don't think it's possible or will be possible to use MultiBinding in the DataGrid. It uses `binding` object only to get property metadata. As it does all bindings by itself for the performance instead.
You should use DataGridTemplateColumn with TextBlock inside.

@vikkio88 as we discussed in the chat, your problem is not related to the DataGrid.
