### ISSUE TITLE
[0.10.10] The problem with scaling the UI on Linux

### ISSUE THREAD

**Issue by perfectdev** [AvaloniaUI/Avalonia#6923]
[AvaloniaUI 0.10.10]

The problem with scaling the UI on Linux (on Wayland and X11).
Tested on Fedora 35 and Ubuntu 21.10.
I don't understand where to dig in terms of scale settings
![image](https://user-images.githubusercontent.com/1786586/141429274-ea232464-cbed-4ea4-91a9-f6f0f43e38fd.png)

PS: Everything is fine on Windows and MacOS X.

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/4826

**Comment by perfectdev** [comment]
> #4826
Great. Thank you!
Added for debugging to the debugging configuration in Rider.
![image](https://user-images.githubusercontent.com/1786586/141435025-997dc3f2-0a15-4538-91bb-7b5cd2fb58c6.png)

**Comment by HubKing** [comment]
I don't use Rider. I just created a new project using dotnet command line and it looks like this. Ubuntu 21.10, Wayland, 200%.

![image](https://user-images.githubusercontent.com/10900489/154869029-40add277-4a39-4c7f-9fa4-7c0be35e6df4.png)

The text is very small and it is on the top left corner. If I do it on Windows, the text is bigger and at the centre of the window. Something is wrong with the Linux support.

**Comment by maxkatz6** [comment]
@HubKing have you checked https://github.com/AvaloniaUI/Avalonia/issues/4826 ?

**Comment by HubKing** [comment]
@maxkatz6  The page had a link and it explained the scaling variable only for X11. I am using Wayland. I set `AVALONIA_SCREEN_SCALE_FACTORS='XWAYLAND0=2', and doubled the text size but also the window size, making the window bigger than the screen so the window title bar was not visible. I had to press Alt+Space and choose "Unmaximise". In the code, the window size is set to 800x450 (by default), so why is it this big?

The linked page says that there is no standard way to get scaling factor on Linux. That may be technically true, but if we just limit the environment to popular ones, that is Gnome and KDE, don't the two provide some sort of API to get scaling factors? I don't know well about Gnome API, but I cannot believe that they have no API for getting it. If they do, why not at least just support Gnome and KDE?

**Comment by yavko** [comment]
Why can't there just be a wayland backend, there are many issues with scaling and xwayland, detecting scaling factors probably wont fix much. Especially for multiple monitors xwayland is terrible. Plus xorg is being slowly deprecated. I hope a wayland backend comes soon!
