### ISSUE TITLE
VS2002 release of Avalonia for Visual Studio extension

### ISSUE THREAD

**Issue by flarive** [AvaloniaUI/Avalonia#6927]
Hi avalonia team !

When do you plan to release the VS2022 avalonia extension ?
https://github.com/AvaloniaUI/AvaloniaVS

(VS2022 final have been released a few days ago and the VS2019 extension can't be installed under VS2022)
Thanks a lot !

I'm going to try to compile the extension source code with VS2022 to try to have  a working VS2022 extension.

Thanks !

Eviral

**Comment by Symbai** [comment]
https://github.com/AvaloniaUI/AvaloniaVS/pull/223

**Comment by maxkatz6** [comment]
Closing as a duplicate
@flarive there is opened PR in VS repo, you can try to build that one and report if it worked for you

**Comment by flarive** [comment]
I have downloaded the PR source code and have tried to compile it from my VS2022 pro final but i have this error 👍 Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur		Impossible de charger la tâche "CompareBuildTaskVersion" à partir de l'assembly C:\Users\frederic.larive\.nuget\packages\microsoft.vssdk.buildtools\15.9.3032\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.15.0.dll. Impossible de charger le fichier ou l'assembly 'file:///C:\Users\frederic.larive\.nuget\packages\microsoft.vssdk.buildtools\15.9.3032\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.15.0.dll' ou une de ses dépendances. Tentative de chargement d’un programme de format incorrect. Assurez-vous que la déclaration <UsingTask> est correcte, que l'assembly et toutes ses dépendances sont disponibles et que la tâche contient une classe publique qui implémente Microsoft.Build.Framework.ITask.	AvaloniaVS

**Comment by flarive** [comment]
Can you give me the compiled visx ???
I will test it in VS2022 and give you feedback.

**Comment by Takoooooo** [comment]
@flarive https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=16490&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by sgf** [comment]
> @flarive https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=16490&view=artifacts&pathAsName=false&type=publishedArtifacts


nothing in the link,can find download link.

![image](https://user-images.githubusercontent.com/2557696/143838165-98802a86-e85a-4a22-a230-af808b9d2d6d.png)

**Comment by TheAvonian** [comment]
> > @flarive https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=16490&view=artifacts&pathAsName=false&type=publishedArtifacts
> 
> nothing in the link,can not find download link.
> 
> ![image](https://user-images.githubusercontent.com/2557696/143838165-98802a86-e85a-4a22-a230-af808b9d2d6d.png)

Scroll down past warnings to 'Jobs'
![image](https://user-images.githubusercontent.com/29378966/143923620-b4ce7292-69ca-45cd-aaf1-3039836b1576.png)

Then click the top most job that is there.
It should bring you to a new page in which you just click on the '1 artifact produced' link.
![image](https://user-images.githubusercontent.com/29378966/143923773-720e8727-7b1f-45d6-a931-2b2222504143.png)

Lastly you should have been sent to a page with publish, click the 3 dots on the right of publish and hit download artifacts. 
![image](https://user-images.githubusercontent.com/29378966/143923903-69f5b7bc-9ba6-4c0f-ae2d-b8b32f112520.png)

That should be it.

**Comment by sgf** [comment]
![动画11](https://user-images.githubusercontent.com/2557696/143971933-a0b22c8f-4db2-411a-8f49-139140fc5d86.gif)

thanks,i got it.

**Comment by sgf** [comment]
> That should be it.
![动画11](https://user-images.githubusercontent.com/2557696/143971933-a0b22c8f-4db2-411a-8f49-139140fc5d86.gif)

thanks,i got it.

**Comment by CorruptComputer** [comment]
> @flarive https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=16490&view=artifacts&pathAsName=false&type=publishedArtifacts

This link 404's now (I guess the artifact expired?) so here is one to show the latest builds: https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build?definitionId=6
