### ISSUE TITLE
Circle in path has missing pixels

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#694]
The `TextBox` in the new data validations branch has an error icon that is defined by the following path:

```
<Path Data="M14,7 A7,7 0 0,0 0,7 M0,7 A7,7 0 1,0 14,7 M7,3l0,5 M7,9l0,2" Stroke="{StyleResource ErrorBrush}" StrokeThickness="2"/>
```

In WPF that produces this (zoomed 4x):

![image](https://cloud.githubusercontent.com/assets/1775141/17831361/dcd8e46c-66e6-11e6-87d1-dfc6614d9310.png)

But in Avalonia there are pixels missing from the circle:

![image](https://cloud.githubusercontent.com/assets/1775141/17831363/e723287e-66e6-11e6-9195-8b5338b841aa.png)

**Comment by soerendd** [comment]
I have investigated the problem a bit. It occurs only when using D2D Backend. When using skia under Windows it looks ok

![warning](https://cloud.githubusercontent.com/assets/5188358/22605526/83865e06-ea50-11e6-9a69-b1441043ba4b.png)

**Comment by soerendd** [comment]
After further investigation i can tell that it seems to be a problem with the SwapChaining used in D2D mode. If I use a simple test app with SharpDX and an hwnd render target the circle is painted absolutely correct. I think it has something to do with some blending. If I set the PrimitiveBlend of the DeviceContext (in CreateSwapChain) to PrimitiveBlend.Copy then the circle is painted correct but many other controls are painted wrong.

**Comment by soerendd** [comment]
What is disturbing is that even  arcs seem to be drawn different.
![arc_compare](https://cloud.githubusercontent.com/assets/5188358/22700674/c0438a68-ed5b-11e6-8670-4afee926e55f.png)
WPF draws the outer most left and right pixels correctly. I really do not understand why DXSharp and Avalonia do not the same

**Comment by jkoritzinsky** [comment]
This got fixed at some point and now the right pixels are showing up.
