### ISSUE TITLE
Targeting .NET 6.0 in Visual Studio 2019 is not supported

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#6955]
**Describe the bug**

Targeting .NET 6.0 in Visual Studio 2019 is not supported

**To Reproduce**

1. Build Avalonia in VS 2019

**Expected behavior**
Do not repoort warnings

**Screenshots**
![immagine](https://user-images.githubusercontent.com/12531229/141965519-118ea37c-7b04-4aea-8592-2f84a7e8f930.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

**Comment by danielmayost** [comment]
It seems to me that `VS2019` has no official support for `.NET 6.0`.
I also had problems building `Avalonia` in `VS2019` until I switched to `VS2022` and it worked.

**Comment by rstm-sf** [comment]
.NET 6 not supports in VS 2019 https://docs.microsoft.com/en-us/answers/questions/620284/how-to-target-net-60-with-visual-studio-2019.html

**Comment by maxkatz6** [comment]
We discussed it before, and .NET 6 advantages outweigh the fact you have to install VS2022.

Too bad if Microsoft decided to lock new SDK only for new VS, but it's not something we can deal with.

**Comment by llfab** [comment]
You may want to check this as an intermadiate solution: https://github.com/AvaloniaUI/Avalonia/discussions/7024
