### ISSUE TITLE
Right-to-left Hebrew (and probably Arabic) Text in Avalonia do not handle the left-to-right regions (e.g. numbers) correctly

### ISSUE THREAD

**Issue by npolyak** [AvaloniaUI/Avalonia#6961]
Try to display the following Hebrew text under **default theme** "זה טקסט ערוך. לדוגמה, רוחב החלון הינו 500 וגובהו 200" in an Avalonia TextBlock. The numbers will be displayed as 002 (instead of 200) and 005 (instead of 500)

Under **fluent theme** - Hebrew and non-Hebrew words are displayed correctly but in reverse order - at the word (not at the character) level. Can someone explain why it is happening? Are there any settings that I am not aware of?

**Comment by npolyak** [comment]
There can be a work around by splitting the text into different regions and displaying the numbers as English text, but it is pretty ugly and labor intensive.

**Comment by maxkatz6** [comment]
Related https://github.com/AvaloniaUI/Avalonia/pull/4893

**Comment by Gillibald** [comment]
Current text processing isn't doing any bidi analysis that's why the numbers are displayed wrong. This will be fixed shortly.

**Comment by danielmayost** [comment]
@maxkatz6 it's closed.

**Comment by timunie** [comment]
> @maxkatz6 it's closed.

Closing this issue rn. If that was wrong, please ping me and I'll reopen it.
