### ISSUE TITLE
Exception in animation causes all other animations (some stlyles) stop working

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#6969]
**Describe the bug**
At specific circumstances animations are producing exception like:
```
    System.NotImplementedException : BindingEntry.OnError is not implemented
    ---- System.NullReferenceException : Object reference not set to an instance of an object.
```
and this causes not only errors be logged in output, but the whole Animation/Styling subsystem stop working 
even controls/animations not related to the rubbish animation itself - 
example: expander is no longer expanding/collapsing, other animations stop working

**To Reproduce**
``` xaml
    <CheckBox x:Name="chkTest">
      <StackPanel>
        <StackPanel.Styles>
          <Style Selector="Border[IsVisible=True]">
            <Style.Animations>
              <Animation Duration="0:0:1" FillMode="Both">
                <KeyFrame Cue="0%">
                  <Setter Property="Width" Value="10" />
                </KeyFrame>
                <KeyFrame Cue="100%">
                  <!--invalid value or binding for keyframe-->
                  <Setter Property="Width" Value="{x:Null}" />
                </KeyFrame>
              </Animation>
            </Style.Animations>
          </Style>
        </StackPanel.Styles>
        <TextBlock Text="check to produce animation bug" />
        <Border Height="10" Background="Red" IsVisible="{Binding #chkTest.IsChecked}"  />
      </StackPanel>
    </CheckBox>
```
1. add this example code in any page in control catalog (Carousel page for example)
2. click checkbox to be checked 3 time so it remains checked
3. any other interaction with animations in this page is no longer working

**Expected behavior**
 even animation in style had invalid values in keyframes, other side animations/styles should continue working properly

**Screenshots**

![2021-11-18_16-13-30](https://user-images.githubusercontent.com/13854631/142431839-5946ab4b-2947-479c-afed-3cee6abcf91b.gif)
**Desktop (please complete the following information):**

- OS: tested on windows, but any OS should have this problem

**Additional context**

**Comment by jmacato** [comment]
woah... that's big..  will repro this asap

pinging @grokys

**Comment by jmacato** [comment]
also please post a full stacktrace so that i can compare

**Comment by donandren** [comment]
will be ready very soon with unit test

**Comment by jmacato** [comment]
a unit test would be perfect, thanks!
