### ISSUE TITLE
[Visual Studio 2019] The XamlIL errors does not appear in the Error List

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#6979]
**Describe the bug**
When there is a error in XamlIL Compilation, it does not appear in the Error List but only in Output window.

**To Reproduce**

1. Create new Avalonia Project in VS 2019
2. Edit axaml so that there is a XAMLIL compilation error
3. Build
4. In the error list does not appear error  but only in Output window

**Expected behavior**
Show XamlIL errors on Error List 

**Screenshots**
![immagine](https://user-images.githubusercontent.com/12531229/142603544-2c8f1505-7ab4-4466-a9ec-52d8760282f5.png)
![immagine](https://user-images.githubusercontent.com/12531229/142603595-540455fc-c89e-4eaa-8bb3-d45e72d51496.png)

**Desktop (please complete the following information):**

- OS:  Windows 10
- Version 5cfeb2205ee0770e5ec339b61dacec76487b1cd9
- Visual Studio 2019

**Additional context**

**Comment by kekekeks** [comment]
Was it caused by "Intellisense only" option?

**Comment by workgroupengineering** [comment]
Yes, it is my mistake
