### ISSUE TITLE
Changing value of array element doesn't update UI (using `RaisePropertyChanged`)

### ISSUE THREAD

**Issue by duck-dev** [AvaloniaUI/Avalonia#6986]
**Describe the bug**
Changing a **property** of an array's element and trying to reflect the changes to the UI with `RaisePropertyChanged` works as expected. 
Changing the **value** of an array's element and using `RaisePropertyChanged` however doesn't lead to the expected result. The value changes, a simple debugging process proved that, but the changes don't reflect on the UI.

**To Reproduce**
Working example:
```cs
private static readonly Color _someColor = new(255, 0, 0, 0);
private static readonly Color _otherColor = new(255, 255, 255, 255);

private SolidColorBrush[] BrushArray { get; } = { new(_someColor), new(_otherColor) };

private void SomeMethod()
{
    // Assuming the values truly change here
    BrushArray[0].Color = _someColor;
    BrushArray[1].Color = _otherColor;

    this.RaisePropertyChanged(nameof(BrushArray));
}

// In the XAML, a brush-property binds to an element of this array (e.g. Foreground="{Binding BrushArray[0]}")
```

Not working example:
```cs
private static readonly SolidColorBrush _someBrush = new(new Color(255, 0, 0, 0));
private static readonly SolidColorBrush _otherBrush = new(new Color(255, 255, 255, 255));

private SolidColorBrush[] BrushArray { get; } = { _someBrush, _otherBrush };

private void SomeMethod()
{
    // Assuming the values truly change here
    BrushArray[0] = _someBrush;
    BrushArray[1] = _otherBrush;

    this.RaisePropertyChanged(nameof(BrushArray));
}

// In the XAML, a brush-property binds to an element of this array (e.g. Foreground="{Binding BrushArray[0]}")
```

**Expected behavior**
The changes should be visible in the UI after changing the value of an array's element.

**Desktop (please complete the following information):**

- OS: Linux (Pop! OS 21.04)
- Avalonia Version: 0.10.10 (happened in 0.10.3 too)

**Additional context**
I'm asking myself if that's intended to happen by design or if that's maybe unexpected behaviour yet to be solved. I couldn't find anything about that in previous issues.
I just discovered that and played around a bit with an example to eventually come to the conclusion that this approach doesn't lead to the expected behaviour.

**Comment by maxkatz6** [comment]
In first code if works because SolidColorBrush signals about color changing by itself. No need for additional code. 
In second code there is nothing to tell that item was changed.
You are executing this.RaisePropertyChanged(nameof(BrushArray)), but it's useless in both scenarios, because your array wasn't changed. Because we are in .net it's correct to say array reference wasn't changed. 

In order to get it work, array by itself should signal item changes by index. Something like RaiseProprtyChanged("Item[]"). But simple .NET array doesn't do it. Instead you ObservableCollection - it will signal on item changed by index automatically.

**Comment by maxkatz6** [comment]
To summarize, just change array to ObservableCollection, remove unnecessary RaisePropetyChanged and it will just work. The same way how it works in WPF and other XAML frameworks.

**Comment by duck-dev** [comment]
@maxkatz6 Alright, thank you very much. That makes sense. I forgot that an ObservableCollection notifies the changes automatically.
Glad it's a by-design thing.
