### ISSUE TITLE
AvaloniaXamlLoader.Load(this); throws a InvalidProgramException when using interface in DirectProperty

### ISSUE THREAD

**Issue by Xwilarg** [AvaloniaUI/Avalonia#6988]
**Describe the bug**
 AvaloniaXamlLoader.Load(this); throws a System.InvalidProgramException when trying to create a DirectProperty from an interface

**To Reproduce**
- Create a new project
- Create a ISample interface and a Sample class that implement it
- Create a new user control and create a DirectProperty for ISample
- Try to use the component and property in your main window
- Start the project
AvaloniaXamlLoader.Load(this); will throw the following exception:
```
System.InvalidProgramException: 'Common Language Runtime detected an invalid program.'
```

**Desktop (please complete the following information):**

- OS:
  - Windows 11 Pro Insider Preview Build 22504.rs_prerelease.2111112-1650
  - Windows 10 Pro Version 20H2 Build 19042.1348
  - Ubuntu 21.10
- Version 0.10.10

**Sample Project**
[TestAvalonia.zip](https://github.com/AvaloniaUI/Avalonia/files/7576595/TestAvalonia.zip)

**Comment by jamespfluger** [comment]
@Xwilarg did you ever find a fix for this? It's plaguing all of my projects.

Removing the setter for the property stops the exception from being thrown, but at the cost of not being able to use the property

```
public ISample Sample
{
    get => _sample;
    set => SetAndRaise(SampleProperty, ref _sample, value); // Removing this stops the exception
}
```

**Comment by Xwilarg** [comment]
Nope I didn't, I'm just not using the property anymore

**Comment by jamespfluger** [comment]
I tried digging into it deeper, but I haven't had any luck. For those who come across this in the future:
- You can simplify the example by changing `Sample` and `ISample` to be `string` and still receive the error
- The exception occurs for both `StyledProperty` and `DirectProperty`

**Comment by kekekeks** [comment]
Replace 
```
public static readonly DirectProperty<Component, ISample> SampleProperty =
    AvaloniaProperty.RegisterDirect<Component, ISample>(nameof(Sample), x => x._sample);
```
with 
```
public static readonly DirectProperty<Component, ISample> SampleProperty =
    AvaloniaProperty.RegisterDirect<Component, ISample>(nameof(Sample), x => x._sample, (o, v) => o.Sample = v);
```
