### ISSUE TITLE
Get the position relative to the main window

### ISSUE THREAD

**Issue by KeKl** [AvaloniaUI/Avalonia#699]
Hi,

I have a win32 window embedded in avalonia for graphic rendering.

I have a BoundsTracker like so:

```
var disposable = new BoundsTracker()
       .Track(this)
       .Subscribe(UpdateLayout);
```

In the old releases there was an overload where I could specify 
that I want to track for the parent window.

My question:
How do I get the location where the control has to be positioned?

Regards
Kevin

**Comment by grokys** [comment]
Hi @mikel785 : the `UpdateLayout` method in your example will be called with a `TransformedBounds` struct. This has a `Bounds` property which describes the absolute bounds of the control relative to the window. Does this not work?

**Comment by KeKl** [comment]
Sorry I´ve made a mistake. It is working for relative to the window. But what I really need to determine is where the control has to be positioned, because after that I call a method that will position the win32 window with a native call to SetWindowPos(...), which needs "global" coordinates.

I think I can get this working with an override of ArrangeCore()?

**Comment by grokys** [comment]
Sorry, I'm having difficulty understanding. First when you say "global" coordinates what do you mean? Screen coordinates?

Secondly, what is the "left control"?

**Comment by KeKl** [comment]
I mean client coordinates with global coordinates.

If i have a stackpanel with two controls. The second One is the second in the Visual tree.
The scruct TransformedBounds contains for the second control for example the values x,y,width,height=0,0,300,300 regardless of the size of the first control. The rect in arrangecore() has the values relative to the Main window e.g. x,y,width,height=200,0,300,300.
In the end the struct TransformedBounds describes the rect relative to the previous element in the visual tree. But if i want embedd a native window i need coordinates relative to the Main window.

**Comment by jkoritzinsky** [comment]
@KeKl You can use the `Transform` property of `TransformedBounds` together with the `Bounds` property (multiply them together) to get an axis-aligned bounding box for the location of the control with respect to the main window.

**Comment by grokys** [comment]
Ah apologies @KeKl I forgot that Jeremy had changed that. Yes, what he said ;)
