### ISSUE TITLE
Can't use a event

### ISSUE THREAD

**Issue by MarcelskyXD** [AvaloniaUI/Avalonia#6993]
**Describe the bug**

Can't use the "Click" event of a button

**To Reproduce**

1, Create a button
2. Add a Click event
3. Create button event handler in code-behind

**Expected behavior**
Being able to add the event handler without any problem
**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 64-bit 20H2
- Avalonia Version: 0.10.10

**Comment by MarcelskyXD** [comment]
actually i think my project is just broken

**Comment by maxkatz6** [comment]
> actually i think my project is just broken

Most likely it is. Delete bin/obj files, rebuild project.
Is it running? Is problem just with previewer? Description is not clear enough.
