### ISSUE TITLE
Slider doesn't play well with big thumb size

### ISSUE THREAD

**Issue by yankun** [AvaloniaUI/Avalonia#7011]
**Describe the bug**
Increasing the size of the thumb of a slider brings up the issue that the position of the thumb is not calculated properly on drag, 
relatively to the current position of the thumb. Also clicking on the track will not place the thumb where you expect it to be, the more you are clicking away from the center of the track.

**To Reproduce**
Add a slider, and increase the thumb width.

If the thumb is on the very left, you will notice, that on drag it will jump quit a bit right, before it will move along with the movement of the pointer. On the very right, it will jump to the left. If you place the thumb on the exact middle, this jump will not happen. 

```
<Slider Width="200">
        <Slider.Resources>
            <x:Double x:Key="SliderHorizontalThumbWidth">48</x:Double>
        </Slider.Resources>
</Slider>
```

**Expected behavior**
That the thumb will always move along with mouse cursor, regardless of its size, and that a click on the track will place the thumb center directly under the pointer.

**Screenshots**
![out](https://user-images.githubusercontent.com/374264/143421426-ec80a4b8-1f2b-4436-afe3-669b9da0c385.gif)

**Desktop (please complete the following information):**

- OS: MacOS 12
- Version: 0.10.10

**Comment by yankun** [comment]
I've created a Pull Request fixing this behaviour:

![outfixed](https://user-images.githubusercontent.com/374264/143461506-27d09afd-49d3-4537-81b4-966e48fa43f4.gif)

**Comment by Slasher37** [comment]
How can I change the thumb size on the slider? How and where can I change it?

I tried with the code above but nothing changes.

**Comment by Hunv** [comment]
If someone else finds this issue like me: You can do it this way:

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:sys="using:System"
             ...
             >
...
<Slider
  Orientation="Vertical"
  VerticalAlignment="Stretch"
  >
  <Slider.Resources>
    <sys:Double x:Key="SliderVerticalThumbWidth">48</sys:Double>
    <sys:Double x:Key="SliderVerticalThumbHeight">48</sys:Double>
  </Slider.Resources>
</Slider>
```

If you need horizontal alignment, you need replace the `Vertical` with `Horizontal` off cause.
