### ISSUE TITLE
Select all text in TextBox on tabulation

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#702]
If I press `Tab` key and focus jumps to `TextBox` contol the text in this `TextBox` not selected but it should.

**Comment by robbieknuth** [comment]
WPF and Avalonia have the same behavior. Some other applications (like Chrome) do auto-highlight textboxes. But if the goal is to emulate what WPF does, there is no bug here. Tested on commit 7b4c10a7f8b.

WPF
![wpf_tab_into_textbox](https://cloud.githubusercontent.com/assets/7350266/18534094/df622f9e-7a9c-11e6-8cfb-5a6d699c3c24.gif)

Avalonia
![avalonia_tab_into_textbox](https://cloud.githubusercontent.com/assets/7350266/18534101/ecdae47c-7a9c-11e6-9b23-63e290b3feb3.gif)

**Comment by grokys** [comment]
Yeah, to be honest I think WPF's behavior is wrong: I'd expect auto-selection of text personally.

**Comment by KvanTTT** [comment]
Maybe add "SelectAllOnTab" option with default parameter of "true" for TextBox controls?

**Comment by robbieknuth** [comment]
Sounds reasonable. I've been wanting to get involved in this project, this looks like a good place to start. I'll take a look.

**Comment by grokys** [comment]
To be honest, i'd just make it select all text by default for the moment. I don't know if a property is necessary.

**Comment by KvanTTT** [comment]
I can imagine the following case: Text editor with big multiline text field and another small singleline fields. If tabulation works and we go into this big filed, entire text should not be selected.

**Comment by grokys** [comment]
Hmm, true. What does e.g. Chrome do? Does it allow you to turn the feature on/off? Does it disable it based on whether the input is multi-line? We should try to follow the example of others here.

**Comment by KvanTTT** [comment]
I just tried tabulation in Chrome.
Indeed: it selects all text in singleline text boxes and not change selection in multiline ones. See [video](https://www.youtube.com/watch?v=vmIYA365BIM&feature=youtu.be).

**Comment by grokys** [comment]
That sounds like a good behavior to me. I'd rather not introduce options if we don't have to.

**Comment by robbieknuth** [comment]
PR #745 fixes this issue. If the textbox is single line, select all text. If it has no text or it is a multiline textbox (acceptsreturn is true), then show the caret like before.
