### ISSUE TITLE
Add "readonly" pseudo class to TextBox

### ISSUE THREAD

**Issue by thomaslevesque** [AvaloniaUI/Avalonia#7023]
I need to style a TextBox differently depending on whether it's readonly or not. Currently there's no easy way to do that, because:
- Avalonia doesn't support style triggers
- There's no pseudo class for the readonly state

**Describe the solution you'd like**
Ideally, a new "readonly" pseudo class would be added to `TextBox` (and possibly other edit controls) when `IsReadOnly` is true

**Describe alternatives you've considered**
The only way I can think of is to subclass `TextBox` to be able to add the pseudo class myself, which isn't very convenient

**Additional context**
N/A

**Comment by maxkatz6** [comment]
```Selector="TextBox[IsReadOnly=True]"``` will work.

**Comment by thomaslevesque** [comment]
@maxkatz6 awesome, thanks!

It makes sense, since it's similar to CSS selectors, but it should probably be mentioned [in the docs](https://docs.avaloniaui.net/misc/wpf/styling)

**Comment by maxkatz6** [comment]
@thomaslevesque yes, it's from CSS.
And it is mentioned in docs https://docs.avaloniaui.net/docs/styling/selectors#propertyequals

**Comment by thomaslevesque** [comment]
Ah, yes, I wasn't looking at the right page. Thanks!
