### ISSUE TITLE
how to let the TextBlock display CJK text correctly?

### ISSUE THREAD

**Issue by sgf** [AvaloniaUI/Avalonia#7037]
**Describe the bug** 
cant not correctly display the CJK text 

**To Reproduce**
see the Screenshots

**Expected behavior**
display the CJK text like the TextBlock

**Screenshots**
![image](https://user-images.githubusercontent.com/2557696/143848205-716e76ba-dda6-40d0-88f5-d4e6b1dbaac6.png)

**Desktop (please complete the following information):**

- OS:Windows x64
- Version:20h2

**Comment by sgf** [comment]
Lack of Font Fallback ?

**Comment by kekekeks** [comment]
>You need to use a font that has Chinese characters. https://github.com/anthonyfok/fonts-wqy-microhei is a good one
[WenQuanYiMicroHei-01.ttf.zip](https://github.com/AvaloniaUI/Avalonia/files/5703016/WenQuanYiMicroHei-01.ttf.zip)
>
>Place it into `Assets`, add as `AvaloniaResource` and add something like 
>```
><Style Selector="TextBlock">
>    <Setter Property="FontFamily" Value="avares://YourAssemblyName/Assets/Fonts#WenQuanYi Micro Hei" />
></Style>
>```
>to your `App.xaml` after the theme

**Comment by sgf** [comment]
> > You need to use a font that has Chinese characters. https://github.com/anthonyfok/fonts-wqy-microhei is a good one
> > [WenQuanYiMicroHei-01.ttf.zip](https://github.com/AvaloniaUI/Avalonia/files/5703016/WenQuanYiMicroHei-01.ttf.zip)
> > Place it into `Assets`, add as `AvaloniaResource` and add something like
> > ```
> > <Style Selector="TextBlock">
> >    <Setter Property="FontFamily" Value="avares://YourAssemblyName/Assets/Fonts#WenQuanYi Micro Hei" />
> > </Style>
> > ```
> > to your `App.xaml` after the theme

but this is not good for support unicode (For example, display Arabic Korean Chinese at the same time)

**Comment by Gillibald** [comment]
This is rendered with the reworked TextBox implementation:
![Screenshot 2021-11-29 131249](https://user-images.githubusercontent.com/5928797/143866186-f7477576-e26b-4bbf-9ecb-b438c8b0451b.png)

Some Unicode sequences are split up when they shouldn't and therefore some parts are not rendered properly. Will fix that.

**Comment by sgf** [comment]
> This is rendered with the reworked TextBox implementation: ![Screenshot 2021-11-29 131249](https://user-images.githubusercontent.com/5928797/143866186-f7477576-e26b-4bbf-9ecb-b438c8b0451b.png)
> 
> Some Unicode sequences are split up when they shouldn't and therefore some parts are not rendered properly. Will fix that.

두 사람이 함께 맹세하여 기록한다. 
أَبْجَدِيَّة عَرَبِيَّة‎
微软雅黑
འགོ་བརྗོད་གསར་འགྱུར། 

how about test these ? 😆

**Comment by hunjixin** [comment]
mac have this issue too

**Comment by maxkatz6** [comment]
@Gillibald can it be closed?

**Comment by Gillibald** [comment]
@sgf
![Screenshot 2022-07-11 085642](https://user-images.githubusercontent.com/5928797/178206385-ed5bde7c-8fa6-4a83-b985-3caa3a2ac7bf.png)
@maxkatz6 Y this can be closed

**Comment by John0King** [comment]
@maxkatz6  whitch version does it fix, does it work for "Arabic,Korean,Chinese"  out of box ?  or I need choose some font for  `window` object ?

**Comment by Gillibald** [comment]
Avalonia 11 Preview 4 has this by default
