### ISSUE TITLE
Operator or for Enum in styles

### ISSUE THREAD

**Issue by RomanSoloweow** [AvaloniaUI/Avalonia#7038]
I am unable to list enum values when specifying value in styles.

![image](https://user-images.githubusercontent.com/29205560/143877461-b4df1018-04a0-4386-bc1c-2ba779e4c4f5.png)

**Comment by maxkatz6** [comment]
Use comma, and make sure this enum is a flags enum.

**Comment by RomanSoloweow** [comment]
It worked, thanks!
