### ISSUE TITLE
Implement Toolbar and ToolbarTray as ItemsControl

### ISSUE THREAD

**Issue by KeKl** [AvaloniaUI/Avalonia#705]
Hi,

we don´t have a toolbar and the corresponding toolbartray. It would be nice to implement the toolbartray different than in wpf as a ItemsControl.

**Comment by Junaid-Amjad** [comment]
@KeKl @grokys any update on toolbar?

**Comment by Deadpikle** [comment]
This may or may not fit your needs, but there is a `ToolBar` and `ToolBarTray` available in the [Mechanism for Avalonia](https://github.com/Splitwirez/Mechanism-for-Avalonia/) library.

**Comment by andrewdbond** [comment]
Does something like AvaloniaRibbon help? https://github.com/AvaloniaCommunity/awesome-avalonia#controls

**Comment by maxkatz6** [comment]
Yes, there are some good third party options. We don't plan on adding these controls to the main framework.

**Comment by Tulesha** [comment]
Hello.

I have ported ToolBar and ToolBarTray from WPF. Works fine with Controls and ViewModel items.

[Repository](https://github.com/Tulesha/Avalonia.Controls.ToolBar)
[Nuget package](https://www.nuget.org/packages/Tulesha.Avalonia.Controls.ToolBar/0.0.1)

P.S. Someone already reserved the id **Avalonia.Controls.ToolBar**, so I had to rename it to **Tulesha.Avalonia.Controls.ToolBar**

**Comment by maxkatz6** [comment]
@Tulesha if you want, you can request to add your control to the awesome-avalonia repository - https://github.com/AvaloniaCommunity/awesome-avalonia

> P.S. Someone already reserved the id Avalonia.Controls.ToolBar, so I had to rename it to Tulesha.Avalonia.Controls.ToolBar

Whole "Avalonia." prefix is reserved.
