### ISSUE TITLE
Move AppBuilder to netstandard2.0 library

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#7052]
During the PCL and netstandard1.x eras certain APIs were only available when targeting "full" runtimes (.NET 4.x, .NET Core, Xamarin.Android, Xamarin.iOS). So we've had those in shared code and compiled them into libraries targeting those "full" runtimes while having AppBuilderBase<T> in our PCL/netstandard1.1/netstandard1.3 library. That continued for a while, so we now have several `#if` blocks in that shared code. We should replace those `#if`s with `IsOSPlatform` checks before moving AppBuilder to netstandard2.0.

**Comment by maxkatz6** [comment]
I already did it for my android/ios sdk PR locally, need to cleanup and push to a new PR

**Comment by maxkatz6** [comment]
I already did it for my android/ios sdk PR locally, need to cleanup and push to a new PR
