### ISSUE TITLE
Cannot Set Button Content Image from Style

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#7054]
I have a button with an image content

    <Image x:Key="PlayIcon" Source="/Icons/play.png" />
    <Image x:Key="PauseIcon" Source="/Icons/pause.png" />
    ...
    <Button x:Name="PlayButton" Content="{StaticResource PlayIcon}" />

It is contained in a MediaPlayer control. When IsPlaying property is False, I want to display another icon.

    <Style Selector="local|MediaPlayer[IsPlaying=False] Button#PlayButton /template/ ContentPresenter">
        <Setter Property="Content" Value="{StaticResource PauseIcon}" />
    </Style>

It throws this exception at runtime

    Cannot use a control as a Setter value. Wrap the control in a <Template>.

This works.

        <Setter Property="Content">
            <Template>
                <Image Source="/Styles/Default/Icons/pause.png" />
            </Template>
        </Setter>

However, the downside is that I'm unable to use the declared images at the top of my file. I haven't found a way to use {StaticResource PauseIcon}

Is there a better way to do this?

**Comment by maxkatz6** [comment]
You can't reuse controls from resources. Use Bitmap.
