### ISSUE TITLE
Popup Causing Memory Leaks

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#706]
I have created a new demo in the XamlTestAppliaction, and the MemLeak Repo tab.

Iv made it so when you add tabs, the created tabs contain a dropdown (which contains a popup).

This prevents the tabs being garbage collected when closed.

**Comment by danwalmsley** [comment]
https://github.com/VitalElement/Avalonia/commit/c156e09aa554608abe92e28b0341074e648d62bb

**Comment by danwalmsley** [comment]
The above commit contains XamlTestApp with repro included.
@grokys this bug has been bothering me for months now, finally found a minimal repro.

**Comment by grokys** [comment]
Ok, this seems to be a leak in `DropDown`, caused when controls are placed as the dropdown items instead of binding to view models, i.e.:

````
                <DropDown VerticalAlignment="Center" SelectedIndex="0">
                  <StackPanel>
                    <TextBlock Text="Item 1" FontSize="24" />
                    <TextBlock Text="Item 1 Value" />
                  </StackPanel>
                  <StackPanel>
                    <TextBlock Text="Item 2" FontSize="24" />
                    <TextBlock Text="Item 2 Value" />
                  </StackPanel>
                </DropDown>
```

Can you confirm you're doing something like this in AvalonStudio?
