### ISSUE TITLE
Avalonia Visual Studio 2022 Extension

### ISSUE THREAD

**Issue by michalwitek1232** [AvaloniaUI/Avalonia#7069]
I would like to ask for a version of the extension that works with Visual Studio 2022.

**Comment by workgroupengineering** [comment]
https://github.com/AvaloniaUI/Avalonia/discussions/7034

**Comment by mrmandrake** [comment]
Hi, here a link of my avalonia extension / vs2022 build (tested successfully on a pair of vs 2022 professional instances):

https://drive.google.com/file/d/1CSD79bVENI8fWp1H_sHX__Y-NRUOJK0G/view?usp=sharing

**Comment by maxkatz6** [comment]
Duplicate

**Comment by maxkatz6** [comment]
See https://github.com/AvaloniaUI/AvaloniaVS/issues/206 or https://github.com/AvaloniaUI/Avalonia/issues/6927
