### ISSUE TITLE
bug: Avalonia.Web.Blazor.dll is Too Large

### ISSUE THREAD

**Issue by worldbeater** [AvaloniaUI/Avalonia#7070]
**Describe the bug**

![IMG_20211204_191158_253](https://user-images.githubusercontent.com/6759207/144716495-972a2967-805e-4185-a43e-883248379a67.jpg)

![IMG_20211204_190727_734](https://user-images.githubusercontent.com/6759207/144716380-471b324b-c743-4e5a-8118-8978f4d27e45.jpg)

**To Reproduce**

1. Compile a library dependent on Avalonia.Web.Blazor
2. `Avalonia.Web.Blazor.dll` is 12 Mb huge

**Expected behavior**

Probably including Twitter emojis into the bundle is unnecessary. I'd vote for either removing this asset, or for extracting it into a separate package that could be loaded on demand. It would be even better to exclude all `ttf` files from the `dll` and load them only on demand, as in general different projects with custom designs use their own fonts depending on their design guidelines.

**Comment by Gillibald** [comment]
We don't need to include those fonts. Currently the fluent theme faces the same issue. I think we need to introduce support for loading fonts from some remote source. Aldo long term there will ne a way to setup a custom font manager via app builder.

At the moment skia's font manager is highly limited on wasm.

**Comment by maxkatz6** [comment]
This font was removed from the package
