### ISSUE TITLE
StyledProperty doing nothing

### ISSUE THREAD

**Issue by Abdesol** [AvaloniaUI/Avalonia#7083]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/7081

<div type='discussions-op-text'>

<sup>Originally posted by **Abdesol** December  6, 2021</sup>
I created a custom combo box and it has some properties registered. All of them are working except the SelectedIndex property
The below code is for SelectedIndex property:
```cs
public new static readonly StyledProperty<int> SelectedIndexProperty =
    AvaloniaProperty.Register<CustomComboBox, int>(nameof(SelectedIndex));
public int SelectedIndex
{
    get => GetValue(SelectedIndexProperty);
    set => SetValue(SelectedIndexProperty, value);
}

private static void SelectedIndexPropertyChanged(AvaloniaPropertyChangedEventArgs<int> e)
{
    if (e.Sender is CustomComboBox ctrl)
    {
        ctrl.comboBox.SelectedIndex = e.NewValue.Value;
    }
}
```
All my properties are done in a similar way but I don't know why this one is not working
And also, the change is subscribed to a method too.
```cs
 SelectedIndexProperty.Changed.Subscribe(SelectedIndexPropertyChanged);
```
I am using it in my view like the one below
```xml
<controls:CustomComboBox Grid.Column="0" Name="Sort by"
	 Items="{Binding Sorts}"
	 ItemSelected="{Binding ComboBoxCommand}"
	 SelectedIndex="0">
<controls:CustomComboBox Grid.Column="0" Name="Sort by"
	 Items="{Binding Sorts}"
	 ItemSelected="{Binding ComboBoxCommand}"
	 SelectedIndex="{Binding  Sortby}">
```
It should have been working.

Is there any way to solve it?
Thanks in advance  : )</div>

**Comment by Abdesol** [comment]
I fixed the problem in a weird way.
I changed the property from integer to string. And when there is change, I am applying the change by simply parsing the string to integer.
It is weird but it worked perfectly.

**Comment by maxkatz6** [comment]
I will keep discussion and close this issue

**Comment by maxkatz6** [comment]
Answered in the discussion
