### ISSUE TITLE
Duplicate Accelerator Keys don't work for nested MenuItem Headers

### ISSUE THREAD

**Issue by erri120** [AvaloniaUI/Avalonia#7090]
**Describe the bug**

```xaml
<Menu>
    <MenuItem Header="_File">
        <MenuItem Header="_New Project"/>
        <MenuItem Header="_Open Project"/>
        <MenuItem Header="_Save Project"/>
    </MenuItem>
    <MenuItem Header="_Edit">
        <MenuItem Header="_Find"/>
        <MenuItem Header="_Replace"/>
    </MenuItem>
</Menu>
```

This is a very simple Menu that you can find in most editor-like applications. This is how I expect it to work:

![Rider](https://user-images.githubusercontent.com/16577545/145012338-3b5002dc-b673-489c-82bb-6529e21ef23c.gif)

Both `File` and `Find` start with `F` but they are not on the same level, `Find` is nested inside the `Edit` menu meaning you have to do `Alt+E+F` to get to `Find`. Avalonia does not work this way:

![Avalonia](https://user-images.githubusercontent.com/16577545/145012904-45532663-3a1a-4832-8e5f-3f78068ad860.gif)

As you can see, if the `Edit` menu is open and I press `F`, I expect it to select the `Find` sub-menu item but instead it goes to `File`.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 0.10.10

**Comment by erri120** [comment]
Looking a bit around in the code I guess you'd have to change the [`MenuItemAccessKeyHandler`](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/MenuItemAccessKeyHandler.cs) and [`AccessText`](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Primitives/AccessText.cs) to be aware of what parent `MenuItem` they are in as they currently only work with `char accessKey`:

https://github.com/AvaloniaUI/Avalonia/blob/0ca2f3d5db0d4c5a5a35782e396d40e2ac98f87a/src/Avalonia.Controls/MenuItemAccessKeyHandler.cs#L58-L68

**Comment by TangDave** [comment]
I noticed that this is still a bug in Avalonia - is there a work-around for this?
