### ISSUE TITLE
The Bounds property for RangeBase (templated control?) is {0,0} at startup

### ISSUE THREAD

**Issue by SlenderPlays** [AvaloniaUI/Avalonia#7097]
**Describe the bug**
In an attempted to re-create a custom version of the ProgressBar, I have made a discovery: The Bounds property which is inherited from RangeBase (or perhaps TemplatedControl?) is not set to the control's proper values until after the OnApplyTemplate function is called.

**To Reproduce**
I have created a repository which contains this bug. Visit [this repo](https://github.com/SlenderPlays/AvaloniaBoundsIssue) , download and build. It uses the latest version of Avalonia as of writing this.

[Click here to go to the problem code directly](https://github.com/SlenderPlays/AvaloniaBoundsIssue/blob/master/Controls/CustomSlider.axaml.cs)

**Expected behavior**
The Bounds of a control to be set before OnApplyTemplate is called

**Screenshots**
So, when you first start the app, it looks like this:
![issue1](https://user-images.githubusercontent.com/20498967/145089775-337bac72-2c23-45a7-a0fb-20ebde6b1c50.png)

The indicator (inner bar) is of length 0. If you set a breakpoint at startup, you will get this:
![issue5](https://user-images.githubusercontent.com/20498967/145089856-bb950465-1963-46ae-ba70-44019f0651ec.png)
Bounds is set to {0,0}... not correct imho

If you use the devtools to change the value...
![issue2](https://user-images.githubusercontent.com/20498967/145089924-1705c1a5-0223-48ea-bc84-448f9d1665df.png)
![issue3](https://user-images.githubusercontent.com/20498967/145089935-71d97be6-1d8c-4ace-9400-97eba8a1496c.png)

The bar now works
![issue4](https://user-images.githubusercontent.com/20498967/145089958-b6324c1d-cb4e-4709-94cd-3cd0fe0c4a39.png)

**Desktop (please complete the following information):**

- OS: Windwos 10
- Version: 19041.1288

**Comment by maxkatz6** [comment]
> The Bounds property which is inherited from RangeBase (or perhaps TemplatedControl?) is not set to the control's proper values until after the OnApplyTemplate function is called.

Hard to say, but when you expect it to be set...? 
Bounds is an actual size and relative position of a control. It's known and updated only after layout pass, which calls Measure and Arrange. So initially it always will be empty.

**Comment by SlenderPlays** [comment]
>Hard to say, but when you expect it to be set...?
> Bounds is an actual size and relative position of a control. It's known and updated only after layout pass, which calls Measure and Arrange. So initially it always will be empty.

Honestly, I will not say that I have an ounce of understanding as to how Avalonia inner workings function, but I expected to have a function that is called after the first drawing of the control (or at least after all of its properties are set, and the control is ready to be drawn to screen). I took a look at the [progress bar implementation](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/ProgressBar.cs) and copy-pasted the basic points, and this caused me a lot of confusion as to why the ProgressBar works, and this doesn't. To be honest, I still don't know why the ProgressBar works out-of-the-box with its bounds.

It's honestly been quite a difficult process (that has yet to end) to understand what each overridable methods are, what they do, when they trigger etc. , and its quite likely this bug is actually due to me not being able to understand the workings of templated control (or finding an online resources that attempts at explaining it)

**Comment by MarchingCube** [comment]
If you need accurate bounds you can update your indicator in an arrange call. This is called after measure pass is done so actual bounds are known.

**Comment by SlenderPlays** [comment]
> If you need accurate bounds you can update your indicator in an arrange call. This is called after measure pass is done so actual bounds are known.

Ah, I think I understand. I had no idea that method existed. Taking a look at the original ProgressBar, it had that method overridden ... no idea how I missed >.< 
Thank you people for the insights, and for whoever else is following this chain in the future here is the fix:

```cs
// ... in the CustomSlider classs

protected override Size ArrangeOverride(Size finalSize)
{
    UpdateIndicator(finalSize);
    return base.ArrangeOverride(finalSize);
}
```

[See full code here](https://github.com/SlenderPlays/AvaloniaBoundsIssue)
[See commit which implemented the fix](https://github.com/SlenderPlays/AvaloniaBoundsIssue/commit/7913a3c6c4bd1703963e4aa1358126fb175a4747)
