### ISSUE TITLE
Improve DropDown keyboard behavior

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#71]
DropDown needs a bit of work to match the standard ComboBox keyboard behavior on Windows:
- [x] Arrow keys should change selection when popup not open
- [ ] Changing selection in popup with keyboard shouldn't update selection until Enter pressed
- [x] Pressing Down when no selection and popup open should select first item

**Comment by jkoritzinsky** [comment]
How much of this was fixed by #1166?

**Comment by grokys** [comment]
@jkoritzinsky i think the current status of this issue is correct - just the second item needs addressing.

**Comment by jkoritzinsky** [comment]
Ok. I'm going to push the last part to Beta2 since it's not a bug or a perf-related feature.
