### ISSUE TITLE
DataGridTextColumn Header Dynamic Resource not showing resource string.

### ISSUE THREAD

**Issue by JoostVersteegen** [AvaloniaUI/Avalonia#7107]
DataGridTextColumn Header DynamicResource shows "Avalonia.Markup.Xaml.MarkupExtensions.DynamicResourceExtension", not the resource string. StaticResource works fine.

<DataGridTextColumn Header="{DynamicResource firstName}" Binding="{Binding FirstName}"/>

**Comment by maxkatz6** [comment]
I think you can put TextBlock to the header and set text with dynamic resource. 

Or you can use 0.10.11-rc.2 version (or better wait for a stable one), where this property is bindable.

**Comment by JoostVersteegen** [comment]
That works, thanks.
