### ISSUE TITLE
[BCL] Avoid foreach in BCL whenever possible

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#7109]
**Is your feature request related to a problem? Please describe.**
Mirco optimizations https://www.meziantou.net/fastest-way-to-enumerate-a-list-t.htm

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maxkatz6** [comment]
Not necessary, but foreach over arrays (and spans I think) can be faster than for. So it depends.

**Comment by KvanTTT** [comment]
If I understand correctly, dotnet is able to detect such patterns and eliminate bounds check:

```cs
for (int i = 0; i < array.Length; i++)
{
   // TODO: something with array[i]
}
```

It should not be different with `foreach`.

**Comment by kekekeks** [comment]
@KvanTTT fast `foreach` magic only works for arrays and spans. Lists always use enumerators that check collection version on each item (which is why you can get `InvalidOperationException` with  `Collection was modified` message)

**Comment by workgroupengineering** [comment]
> Not necessary, but foreach over arrays (and spans I think) can be faster than for. So it depends.

`CollectionsMarshal.AsSpan` work only `List<T>` 
`for` on average is about half as fast as `foreach`. 
Using it in the renderloop would improve performance.

**Comment by KvanTTT** [comment]
@kekekeks Yes, I know. It was the answer to the previous message:

> Not necessary, but foreach over arrays (and spans I think) can be faster than for. So it depends.

I meant `for` loop is not slower than `foreach`. But I see from the article that `Foreach_Span` is a bit faster than ordinary `for`, but it's unsafe.
