### ISSUE TITLE
Binding Error in binding to Avalonia.Controls.TextBlock Text Could not find CLR property

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#711]
I have run into issue with data binding in Avalonia (0.4.1-build2016-alpha).

Log output:
```
ReactiveHistorySample.Avalonia.vshost.exe Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBlock"."Text": "Could not find CLR property 'Value' on 'line1'"
ReactiveHistorySample.Avalonia.vshost.exe Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBlock"."Text": "Could not find CLR property 'Value' on 'line2'"
```

Code to reproduce:
https://github.com/wieslawsoltes/ReactiveHistory/blob/4bf4316a7ab78bd32f4ac48a44686c11db98acf4/samples/ReactiveHistorySample.Avalonia/MainWindow.xaml#L49

The issue is present with other binding in linked `MainWindow.xaml` sample, especially for all `.Value` ones I get a lot of log errors `Could not find CLR property`:
```
ReactiveHistorySample.Avalonia.vshost.exe Error: 0 : Binding: Error in binding to "Avalonia.Controls.ContentControl"."Content": "Could not find CLR property 'Value' on 'ReactiveHistorySample.ViewModels.PointShapeViewModel'"
ReactiveHistorySample.Avalonia.vshost.exe Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBox"."Text": "Could not find CLR property 'Value' on 'start21'"
ReactiveHistorySample.Avalonia.vshost.exe Error: 0 : Binding: Error in binding to "Avalonia.Controls.ContentControl"."Content": "Could not find CLR property 'Value' on 'ReactiveHistorySample.ViewModels.PointShapeViewModel'"
```

I have also almost same version in WPF:
https://github.com/wieslawsoltes/ReactiveHistory/tree/4bf4316a7ab78bd32f4ac48a44686c11db98acf4/samples/ReactiveHistorySample.Wpf

The WPF version behaves correctly.

**Comment by wieslawsoltes** [comment]
Screen recording (this shows ListBox items, but when using original binding list is empty):
![2016-09-01_01-45-23](https://cloud.githubusercontent.com/assets/2297442/18150283/fcb8cd26-6fe5-11e6-96d7-7c206768fd47.gif)

**Comment by wieslawsoltes** [comment]
More related issues with binding using latest Avalonia:

![2016-09-02_21-54-25](https://cloud.githubusercontent.com/assets/2297442/18216576/faaa9bf4-7157-11e6-842f-07d5a62311d8.gif)
1. The `Options` tab content disappears after switching tabs
2. The text binding resets to empty string after switching tab

I thinks this is related with previously reposted finding in this issue.

**Comment by wieslawsoltes** [comment]
The disappearing `Options` is caused by my `CachedContentPresenter`, it worked previously, but now its not, replacing it with `ContentControl` solves the first issue from my previous post.

**Comment by wieslawsoltes** [comment]
I think the second issue with binding text resetting to empty string is related to `SelectedItem` setting to null. This happens for DropDown SelectedItem and TreeView SelectedItem as far I have found out.

![2016-09-02_22-20-22](https://cloud.githubusercontent.com/assets/2297442/18217171/8bbb144a-715b-11e6-98ac-a63c1f72916f.gif)

**Comment by grokys** [comment]
Ok, this is because `LineShapeViewModel.Name` is a `ReactiveProperty` which is an `IObservable`.

When the binding system encounters an observable it assumes that you want to bind to the values that the `IObservable` is producing, so it automatically subscribes to the observable - hence the error message:

    "Could not find CLR property 'Value' on 'line1'"

`line1` is the value of the `ReactiveProperty`. You just need to remove the `.Value` part in the binding and it should work correctly.

**Comment by wieslawsoltes** [comment]
@grokys  This does not solve the issue. The `.Value` is intended to be used in binding not the `LineShapeViewModel.Name`.

Than I get the following error:
ReactiveHistorySample.Avalonia.vshost.exe Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBox"."Text": "Could not convert 'line1' to 'ReactiveProperty`1'."

I have tried many combination, with or without `.Value` and none of them work. Not idea how to solve this.

**Comment by wieslawsoltes** [comment]
There is other issue with large gaps/margins set inside `TabControl` and `TabItem` that can not be styled, so to change this I have to copy and modify complete templates.

**Comment by wieslawsoltes** [comment]
This is how it looks when I remove all `.Value` from binding, so all properties are handled as observables:

![2016-09-03_00-29-05](https://cloud.githubusercontent.com/assets/2297442/18219904/93b403f2-716d-11e6-8bd0-d0d41b66e8d8.gif)

**Comment by wieslawsoltes** [comment]
@grokys Is it possible that `ReactiveProperty` way of doing things in WPF is not applicable to Avalonia, can we make it work in Avalonia?

This is how it works in WPF when using bindings to `.Value`:

![2016-09-03_00-31-10](https://cloud.githubusercontent.com/assets/2297442/18219960/05a71544-716e-11e6-9afb-25311491d41c.gif)

**Comment by grokys** [comment]
Ah, I see. I think it might be best to use a specific format for binding to the result of observables and tasks then: we also see this problem when using `ReactiveCommand`... In fact there is a workaround [here](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Markup/Avalonia.Markup/Data/Plugins/ObservableValuePlugin.cs#L29) for that (you could subclass this class and add your own workaound then replace the entry [here](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Markup/Avalonia.Markup/Data/ExpressionObserver.cs#L51) if you wanted to work around it right now).

What should the markup format to bind to the result of a observable/task rather than the object itself be though?

**Comment by grokys** [comment]
Maybe `{Binding Foo.Observable^}` for binding to the output of an observable?

**Comment by grokys** [comment]
The problem with the tab margins should be fixed in my TabControl PR.

**Comment by wieslawsoltes** [comment]
I would prefer to avoid using workarounds, currently this is just issue in sample app, but I intend to use this pattern in my bigger apps and that the solution should be available out of the box in Avalonia.

As for syntax, that is hard one, but I like your proposal.

Those binding to observable would work for two-way binding?

**Comment by grokys** [comment]
Well an observable only goes one way!
