### ISSUE TITLE
The Height property of the TextBox is not respected.

### ISSUE THREAD

**Issue by vita62200** [AvaloniaUI/Avalonia#7119]
The Height property of the TextBox is not respected.

1. Create a new project
2. Create a TextBox with Height property defined

**Expected behavior**
The TextBox with Height=18 should have a height of 18 instead of 32

![image](https://user-images.githubusercontent.com/53830119/145543192-fdbf8208-489d-4df8-9559-9dade4a64467.png)

Desktop (please complete the following information):
Windows 10, Avalonia 0.10.10

**Comment by maxkatz6** [comment]
Check MinHeight property. It has higher priority than Height.
Use dev tools to see what's wrong with control size.
