### ISSUE TITLE
Designer does not work if I use AttachedProperty from library

### ISSUE THREAD

**Issue by HavenDV** [AvaloniaUI/Avalonia#7126]
**Describe the bug**
```
System.Xaml.XamlException: 'Unable to resolve type GridExtensions from namespace using:H.XamlExtensions Line 15, position 4.' Line number '15' and line position '4'.
```
The application works correctly after building and launching

**To Reproduce**

1. Build H.XamlExtensions.Apps.Avalonia and open MainView.axaml.
[H.XamlExtensions-master.zip](https://github.com/AvaloniaUI/Avalonia/files/7696231/H.XamlExtensions-master.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/3002068/145659836-90e05bbf-fa55-412f-9d2d-ce9c79bee798.png)
<img width="1522" alt="image" src="https://user-images.githubusercontent.com/3002068/145659849-aaa1a6d1-bb70-45f0-89a1-4108316c521e.png">

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.10
- VS: 2022 17.1 preview with this extension: https://github.com/AvaloniaUI/AvaloniaVS/pull/223#issuecomment-989329453

**Additional context**
I know that Grid supports RowDefinitions string definition, Avalonia support has been added to this library only to keep the most similar style in xaml for projects that contain WPF/UWP/WinUI/Uno applications besides Avalonia app

**Comment by kekekeks** [comment]
There is currently an issue with previewer that it doesn't load all referenced assemblies automatically for some reason. The workaround is to add `GC.KeepAlive(typeof(TypeFromYourAssembly)` to your `App.xaml.cs`
