### ISSUE TITLE
Button Doesn't Fill Container

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#7128]
I'm converting some WPF code and am seeing some weird behavior here. 2nd button is the WPF code to fill the container and display the button content centered. In Avalonia, the button refuses to take a dynamic size, and will only stretch if I set a fixed size. The first button is what I need to make it look like it should; but then it won't adapt to window resizes.

Something I'm missing, or something Avalonia is missing?

    <UniformGrid Rows="2">
        <Button Width="300" Height="100" VerticalContentAlignment="Center" HorizontalContentAlignment="Center"
                Command="{Binding ShowCommand}">
            <TextBlock Text="Show current time" />
        </Button>
        <Button
            Command="{Binding ActivateCommand}">
            <TextBlock Text="Activate dialog showing current time" />
        </Button>
    </UniformGrid>

**Comment by maxkatz6** [comment]
Same as in WPF, but different default.
VerticalAlignment and HorizontalAlignment

**Comment by mysteryx93** [comment]
OK that works
