### ISSUE TITLE
TextBox tab char not consistent when using mono-spaced font

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#713]
![tabstextbox](https://cloud.githubusercontent.com/assets/2297442/18232563/0e8a670a-72d2-11e6-92fe-52f059841847.png)

Left: Avalonia, Right: WPF

I have found that tab chars are not consistent with WPF text rendering using same font mono-spaced (Consolas, 12).

**Comment by danwalmsley** [comment]
@wieslawsoltes related to this, how do we set the width a tab char renders to?

**Comment by wieslawsoltes** [comment]
Tested with 0.6.0:

![tabs](https://user-images.githubusercontent.com/2297442/36352675-e3bceaf0-14bc-11e8-858a-098ee7d4a0ae.PNG)

The tabs are not rendered correctly on `netcoreapp2.0` on Windows 10.

**Comment by HendrikMennen** [comment]
I noticed that the Direct2D backend supports rendering tabs correctly now :)

**Comment by grokys** [comment]
Just tried with 0.10 and seems `TextBlock` and `TextBox` are unable to display tabs. @Gillibald should they be able to?

**Comment by Gillibald** [comment]
Tabs depending on some column layout that needs to be defined. Without any special processing, they are just some whitespace.

**Comment by Gillibald** [comment]
WPF has a default value for incremental tab stops: https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.textformatting.textparagraphproperties.defaultincrementaltab?view=net-5.0#System_Windows_Media_TextFormatting_TextParagraphProperties_DefaultIncrementalTab that we could support as well. Transforming a tab stop to a fixed with of spaces is kind of trivial to implement.

**Comment by Gillibald** [comment]
For reference: https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/textformatting/TextParagraphProperties.cs#L121
https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/SimpleTextLine.cs#L1597

**Comment by Gillibald** [comment]
How WPF treats tab stops in general: https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/TextMetrics.cs#L98

**Comment by hahn-kev** [comment]
Is there any workaround for this currently? I'm working on a project and tabs are displayed as a little box in a question mark as someone else mentioned.

**Comment by Gillibald** [comment]
Fixed in master
