### ISSUE TITLE
MessageBox in Avalonia Core

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#7135]
MessageBox is a very fundamental feature, and although there is MessageBox.Avalonia, [that implementation still has lots of issues.](https://github.com/AvaloniaCommunity/MessageBox.Avalonia/issues/87)

I think there should be efforts for a good MessageBox integration within Avalonia itself.

**Comment by maxkatz6** [comment]
If you have any ideas, you can write to that issue
https://github.com/AvaloniaUI/Avalonia/issues/670
