### ISSUE TITLE
Force touch screen behavior

### ISSUE THREAD

**Issue by dark-matter-matters** [AvaloniaUI/Avalonia#7143]
**Is your feature request related to a problem? Please describe.**
My Avalonia Application isn't working properly on a touch-screen Debian 10 environement, the input is handled as a mouse and the user cannot scroll through a DataGrid component. The touch-screen detection seems to be faulty, but I couldn't find a way to force it.

**Describe the solution you'd like**
Add an option to force touch-screen behavior even if mouse is (wrongly) detected.

**Describe alternatives you've considered**
```c#
public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToTrace()
                .UseReactiveUI()
                .With(new X11PlatformOptions { EnableMultiTouch = true })
                .With(new Win32PlatformOptions { EnableMultitouch = true });
```

**Additional context**
Project using Avalonia v0.10.10.

**Comment by kekekeks** [comment]
Show `xinput test-xi2` output when user interacts with the touch screen.

**Comment by dark-matter-matters** [comment]
@kekekeks Thanks for your reply. Here's the log file containing the output of the command on the target: 
[xinput_logs.log](https://github.com/AvaloniaUI/Avalonia/files/7712328/xinput_logs.log)  

For additional context, the scroll is working fine on Windows using the VS emulator, but not on the target. It is a PanelPC with a single-touch screen.

**Comment by kekekeks** [comment]
Xorg doesn't recognize your touchscreen as a touchscreen and reports mouse events instead. Not sure if elographics is even capable of generating touch events.

**Comment by dark-matter-matters** [comment]
Is there anything I can do to force the DataGrid component to treat the mouse as a touch device? Perhaps force it at .NETCore level? Any idea why the behavior is different on other components (link with https://github.com/AvaloniaUI/Avalonia/pull/5894 and https://github.com/AvaloniaUI/Avalonia/pull/6342?)  
As a last resort solution, how could I increase the size of the scrollbar without using a ScrollViewer (as I believe that would decrease the performances by removing rows virtualization)? Thanks.

**Comment by kekekeks** [comment]
Check if your touchscreen generates any events with evtest. Note that https://github.com/AvaloniaUI/Avalonia/pull/5894 only handles devices that produce BTN_TOUCH events.

If that works you can try running your app without Xorg if your device supports KMS/DRM of if you are willing to give up on hardware graphics acceleration.
