### ISSUE TITLE
Some font files are OK in version 0.9.12, and errors are reported in version 0.10.10

### ISSUE THREAD

**Issue by RunMonkey** [AvaloniaUI/Avalonia#7154]
**Describe the bug**
I need to use Chinese, but I find that the font 'Arial' cannot run on version 0.10.10 and will report an error. But the same code has no problem with version 0.9.12.
But if you use the font 'Consolas', both versions are OK.
It seems that if there is Chinese in the font, an error will be reported。

**To Reproduce**
[2 solution and 3 pics.zip](https://github.com/AvaloniaUI/Avalonia/files/7712061/2.solution.and.3.pics.zip)

**Comment by Gillibald** [comment]
Your Font is called `Arial MT` not just `Arial`

Try `new FontFamily("resm:AvaloniaFont.Assets?assembly=AvaloniaFont#Arial MT");`

**Comment by RunMonkey** [comment]
> Your Font is called `Arial MT` not just `Arial`
> 
> Try `new FontFamily("resm:AvaloniaFont.Assets?assembly=AvaloniaFont#Arial MT");`

1.new FontFamily("resm:AvaloniaFont.Assets.Arial.ttf?assembly=AvaloniaFont");   I found another creation method，it's OK
2.new FontFamily("resm:AvaloniaFont.Assets?assembly=AvaloniaFont#Arial MT");
Both methods can work, but the second method can't show Chinese. Which is the recommended method?
![resuorceName](https://user-images.githubusercontent.com/15755247/146104110-f077e80a-abd5-4777-8f37-68c27041b7a9.png)
![FontName](https://user-images.githubusercontent.com/15755247/146104146-c7405119-80a7-4f48-ac10-2becf93bf52c.png)

ps: Why does version 0.9.12 support "resm:AvaloniaFont.Assets?assembly=AvaloniaFont#Arial"？

**Comment by RunMonkey** [comment]
hello，Is there any other way to load Chinese font(like simhei.ttf)?  @Gillibald

**Comment by RunMonkey** [comment]
hello，Is this problem still being followed up？
@Gillibald

**Comment by Gillibald** [comment]
I need the actual font file to be able to debug this

**Comment by RunMonkey** [comment]
In the above feedback, the word may be too small to see。
![20211230](https://user-images.githubusercontent.com/15755247/147726521-2657be51-5d43-448f-9cfa-45a403905be2.png)

**Comment by Gillibald** [comment]
Try `new FontFamily("resm:AvaloniaFont.Assets?assembly=AvaloniaFont#SimHei")`

**Comment by RunMonkey** [comment]
it's ok，but How to get English font descriptor? 
The official name is similar to Simsun and simhei. It can be speculated that what if it is an unofficial Chinese name
