### ISSUE TITLE
[Textbox] Bug cursor text pointer

### ISSUE THREAD

**Issue by the57200** [AvaloniaUI/Avalonia#716]
Unable to go all right with the arrow keys except the mouse :
![bug_avalonia_textbox_cursor_pointer](https://cloud.githubusercontent.com/assets/3616612/18256414/6bad8226-73b5-11e6-85ea-275ba1788860.gif)

**Comment by grokys** [comment]
Hi @the57200 could you give some more details about this? How can I reproduce exactly?

**Comment by the57200** [comment]
Create a textbox and insert text, then with the arrow keys move the cursor of the text to left and try to go all right with the arrow keys but it's impossible.

**Comment by grokys** [comment]
Ah! You're right! It seemed so simple I thought there must be something I was missing, but I've just tried it and indeed you can't get to the last character. Will fix now, thanks!
