### ISSUE TITLE
can't show any character in Centos7

### ISSUE THREAD

**Issue by RunMonkey** [AvaloniaUI/Avalonia#7161]
**Describe the bug**
I created a simple demo，bind two different fonts , which can successfully display different fonts in Windows 7, but in CentOS system, it is blank and cannot be displayed. 
Version 0.10.10

**To Reproduce**
Two pictures and a solution
[can not show in centos.zip](https://github.com/AvaloniaUI/Avalonia/files/7717157/can.not.show.in.centos.zip)

**Comment by kekekeks** [comment]
@Gillibald

**Comment by RunMonkey** [comment]
@Gillibald   Hello, excuse me, is this a bug or something wrong with my system？

**Comment by Gillibald** [comment]
What font are you using? That nothing is getting displayed is probably an issue with Skia's font manager. Are there any errors in the console?

**Comment by RunMonkey** [comment]
The console did not output any errors。
How to solve the probably problem of Skia's font manager？
![avaloniaFont](https://user-images.githubusercontent.com/15755247/147186419-6988f4d5-1997-44a4-afe9-6ee90b3fc596.PNG)
