### ISSUE TITLE
Dialogs moved to another screen disappear

### ISSUE THREAD

**Issue by carlosmiei** [AvaloniaUI/Avalonia#7166]
**Describe the bug**
When working on a laptop with an extra monitor, when we open a dialog and try to move it to the other screen, this dialog disappears.

Although this is not a bug per se,  it would be nice to have this behavior fixed since it leads to a bad experience.

**To Reproduce**

1. Open a main window
2. Open a descendant window
3. Move the descendant window to another screen
4. See the window disappearing 

**Expected behavior**
Just like Rider does, the moved window should stay still
**Screenshots**
[Rider behavior](https://user-images.githubusercontent.com/43336371/146207950-38b07602-b64e-4091-83a8-668b54178385.mov)

**Desktop (please complete the following information):**

- OS: MAC
- Version: 10.15.7

**Additional context**

**Comment by grokys** [comment]
This is now fixed - we no longer use native macOS child windows (which have the problem described here) and instead manage our own.

I think it was fixed by https://github.com/AvaloniaUI/Avalonia/pull/8091 though not 100% sure as the PR has no description.
