### ISSUE TITLE
ListBox Virtualization doesnt work when Listbox is not visible

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#719]
The use case is my intellisense control.

I hide the list, update the items and then show it

If its invisible item virtualization doesn't work because it tries to measure all the items, until the container is filled. But if the items are invisible their reported size is 0, so it loads every item in list.

This did work before. I worked around be making my control visible before updating list.

**Comment by donandren** [comment]
I have the same issue actually with a bit different, but still very similar case:
if we have itemscontrol/listbox in a carousel/tabcontrol and that's not the active page.
This means the itemscontrol/listbox is detached from visual tree, but attached to logical.
 When we update collection items basically item containers are updated and probably is best not to do so, as sometimes that can cause some exceptions or invalid behavior based on measure with screen size.

For me the correct behavior should be the ItemVirutalizer don't update item containers while not visible or detached from logical tree.
