### ISSUE TITLE
OpenFolderDialog - Support multi selection

### ISSUE THREAD

**Issue by 0x90d** [AvaloniaUI/Avalonia#7209]
**Is your feature request related to a problem? Please describe.**
The native OpenFolderDialog control currently only supports single selection. At least on Windows it could support multi selection.

**Describe the solution you'd like**
Just like OpenFileDialog support multi selection

**Describe alternatives you've considered**

**Additional context**

**Comment by Sorien** [comment]
are you sure about it? I just tested it at the control catalog and it's working for me...

https://github.com/AvaloniaUI/Avalonia/blob/9bc3ce6ad85f0bbf129b65bf0042308ae3fdb205/src/Avalonia.Controls/SystemDialog.cs#L84

https://github.com/AvaloniaUI/Avalonia/blob/270725e5772513e287da6fbd8d1e2b320774f5a1/src/Windows/Avalonia.Win32/SystemDialogImpl.cs#L39-L42
