### ISSUE TITLE
ScrollViewer with touch inside of rotated LayoutTransformControl

### ISSUE THREAD

**Issue by Giacomo-Gozzi** [AvaloniaUI/Avalonia#7227]
With the component rotated 90 degrees if you touch the top of the screen it will scroll down and vice versa.

Seps:
1) Create a LayoutTransformControl element with RotateTransform angle = 90
2) Create a ScrollViewer element with a series of objects inside
3) Tap the top, the controller will scroll down, tap the bottom, the controller will scroll up.

I expect that instead of scrolling nothing will happen
- OS: Linux Raspberry PI OS
- Version: Master on github at commit 4a3ee85c08e8e792c16473414c11fde316a2ce21

The application does not run with xorg but with linuxframebuffer

**Comment by kekekeks** [comment]
I don't see anything unusual with the scrolling on the current master
https://user-images.githubusercontent.com/1067584/146957556-906a2890-6cc4-4c31-9921-b51eb7e6e8ef.mp4

**Comment by Giacomo-Gozzi** [comment]
I have this problem, the scroll works correctly, while if I make a tap the screen scrolls, the tap positions are ok.

https://user-images.githubusercontent.com/22610788/147053927-09e7f3ee-c0f4-44a7-9317-4e1efb7c21ae.mp4

**Comment by kekekeks** [comment]
I don't think that tap-based scrolling is triggered by Avalonia. Try running `evtest` and `libinput-debug-events` while tapping at the device and see if there are any extra events.

**Comment by Giacomo-Gozzi** [comment]
**- First example, scroll to the top of the screen**

_Event: time 1640185364.579786, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 356
Event: time 1640185364.579786, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 711
Event: time 1640185364.579786, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 372
Event: time 1640185364.579786, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 1
Event: time 1640185364.579786, type 3 (EV_ABS), code 0 (ABS_X), value 711
Event: time 1640185364.579786, type 3 (EV_ABS), code 1 (ABS_Y), value 372
Event: time 1640185364.579786, -------------- SYN_REPORT ------------
Event: time 1640185364.639781, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 370
Event: time 1640185364.639781, type 3 (EV_ABS), code 1 (ABS_Y), value 370
Event: time 1640185364.639781, -------------- SYN_REPORT ------------
Event: time 1640185364.669831, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value -1
Event: time 1640185364.669831, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 0
Event: time 1640185364.669831, -------------- SYN_REPORT ------------_

I have done several tests and the same thing always happens, the second event is as if it were interpreted with inverted axes for example:

**EVENT 1**
   Event: time 1640185364.579786, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 711
   Event: time 1640185364.579786, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 372

**EVENT 2**
   Event: time 1640185364.639781, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 370

event 2 is considered as a movement of the x-axis and not y-axis.



**- Second example, scroll to the end of the screen**

_Event: time 1640185887.069781, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 365
Event: time 1640185887.069781, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 38
Event: time 1640185887.069781, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 375
Event: time 1640185887.069781, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 1
Event: time 1640185887.069781, type 3 (EV_ABS), code 0 (ABS_X), value 38
Event: time 1640185887.069781, type 3 (EV_ABS), code 1 (ABS_Y), value 375
Event: time 1640185887.069781, -------------- SYN_REPORT ------------
Event: time 1640185887.129782, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 376
Event: time 1640185887.129782, type 3 (EV_ABS), code 1 (ABS_Y), value 376
Event: time 1640185887.129782, -------------- SYN_REPORT ------------
Event: time 1640185887.159795, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value -1
Event: time 1640185887.159795, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 0
Event: time 1640185887.159795, -------------- SYN_REPORT ------------_

I have done several tests and the same thing always happens, the second event is as if it were interpreted with inverted axes for example:

**EVENT 1**
   Event: time 1640185887.069781, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 38
   Event: time 1640185887.069781, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 375

**EVENT 2**
   Event: time 1640185887.129782, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 376

event 2 is considered as a movement of the x-axis and not y-axis.

You can see in the first example that the value has decreased and therefore the screen has moved towards the initial part, while in the second example the value has increased and the screen has moved towards the final part of the display

**Comment by BuriKizilkaya** [comment]
Is this issue is solved?
