### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by KeKl** [AvaloniaUI/Avalonia#723]
Hi,

I currently write some docs for development in Markdown.
Which platform should we use for deployment? GitBook?

For the API documentation: There is http://sharpdox.de/en/ which I think is really
nice, e.g. http://sharpdox.de/de/doc/#/type/SharpDox.Build.Roslyn.ParserStrings/index.
Should we go with that?

Regards

**Comment by wieslawsoltes** [comment]
@KeKl Avalonia is using `DocFX` for api documentation. The guidelines and tutorials are written in markdown. See the https://github.com/AvaloniaUI/Avalonia/tree/master/docs folder for mode details.
