### ISSUE TITLE
Throw an Exception if DataTemplate with null DataType is added to DataTemplates collection

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#724]
Id done this by mistake and it was difficult to track down.

Perhaps an error message hinting to use ContentTemplate, ItemTemplate instead would be nice.

**Comment by grokys** [comment]
Unfortunately, this won't work because at the time the XAML engine adds a `DataTemplate` to the `DataTemplates` collection, its `DataType` is set to null... I wonder how other XAML frameworks enforce this?
