### ISSUE TITLE
[Degradation] Context Menu Submenus now changing main menu position on menu open

### ISSUE THREAD

**Issue by Mikolaytis** [AvaloniaUI/Avalonia#7249]
**Describe the bug**
Context Menu Submenus now changing main menu position on menu open.
Occurs after merge of master branch into our private repo. Around a month of commits. 

**To Reproduce**
1. Enable Hosted in-window popups
2. Create a context menu with a submenu. 
2. Set it to a large control
3. open context menu.
4. mouse over submenu
Only works on menus that positioned on mouse. Main Menu is fine.

https://user-images.githubusercontent.com/4997065/147173285-4c61dec9-e9d9-45d3-b6bb-517a6f2f0c27.mp4

**Comment by Mikolaytis** [comment]
I've tried to find a change/pr/commit that caused the issue - looks like this is https://github.com/AvaloniaUI/Avalonia/pull/7071
But i'm not sure.

**Comment by maxkatz6** [comment]
Yes, seems to be affected only for overlay popups, which are disabled by default.

**Comment by Mikolaytis** [comment]
After some debugging I've found that PlacementTargetLayoutUpdated - is fired and caused position change.

**Comment by josephnarai** [comment]
Is there a timeframe for when this fix will be available via nuget?

**Comment by maxkatz6** [comment]
@josephnarai it is available now with 0.10.12.

**Comment by josephnarai** [comment]
Thank you, I'll try it out!



Joseph Narai • Zenso
________________________________
