### ISSUE TITLE
Item virtualization sometimes doesn't work correctly when list is not visible.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#725]
Reported by @donandren with a fix here https://github.com/AvaloniaUI/Avalonia/pull/722.

Need to create a unit test that demonstrates the problem and determine if the fix is correct.

**Comment by grokys** [comment]
@donandren I've been trying to reproduce this in VirtualizationTest, but I've had no luck so far. Any idea how we might be able to repro?

**Comment by jkoritzinsky** [comment]
@donandren Any repro for this? I'm going to close this until we have one. We can re-open if you can make a unit test or repro it in VirtualizationTest in some way.
