### ISSUE TITLE
WarningsAsErrors Nullable Annotation not working in Visual Studio 2022

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#7253]
**Describe the bug**
Build Avalonia source code in Visual Studio

**To Reproduce**

1. Modify part of the code so that a CS8603 type alert is generated.
2. Build
3. No error is thrown

**Expected behavior**
thrown error in Error list of Visual Studio

**Screenshots**

**Desktop (please complete the following information):**

- Version: 0f030a17f0e9498e6ff565c3e3103c30d5df1fbb
- IDE: Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.1.0 Preview 1.1

**Additional context**

**Comment by maxkatz6** [comment]
Note that warnings are marked as errors only for net6 target and not netstandard. So you might need to change intellisense target in VS. Might it be the case for you?

**Comment by workgroupengineering** [comment]
> Note that warnings are marked as errors only for net6 target and not netstandard. So you might need to change intellisense target in VS. Might it be the case for you? Although it shouldn't be buildable anyway.

I found out what the problem is, I did a PR
