### ISSUE TITLE
ProgressBar ShowProgressText not implemented in FluentTheme

### ISSUE THREAD

**Issue by FRvanderVeen** [AvaloniaUI/Avalonia#7255]
I made a Window containing a ProgressBar. My application was using the FluentTheme (which is default for both application templates). I set the property 'ShowProgressText' to true. My progress bar was updating correctly, but no text showed up.

I was wondering why it wasn't working. Eventually I found out that the ControlTemplate was different for Default and Fluent theme:

Default theme (src/Avalonia.Themes.Default/ProgressBar.xaml)
```
<ControlTemplate>
  <Grid>
    <Border Background="{TemplateBinding Background}" BorderBrush="{TemplateBinding BorderBrush}" BorderThickness="{TemplateBinding BorderThickness}" CornerRadius="{TemplateBinding CornerRadius}">
      <Panel>
        <Border Name="PART_Indicator" Background="{TemplateBinding Foreground}" IsVisible="{Binding !IsIndeterminate, RelativeSource={RelativeSource TemplatedParent}}"/>
        <Border Name="PART_IndeterminateIndicator" Background="{TemplateBinding Foreground}" IsVisible="{Binding IsIndeterminate, RelativeSource={RelativeSource TemplatedParent}}"/>
      </Panel>
    </Border>
    <LayoutTransformControl HorizontalAlignment="Center" VerticalAlignment="Center" IsVisible="{Binding ShowProgressText, RelativeSource={RelativeSource TemplatedParent}}" Name="PART_LayoutTransformControl">
      <TextBlock Foreground="{DynamicResource ThemeForegroundBrush}" Text="{Binding Value, RelativeSource={RelativeSource TemplatedParent}, StringFormat={}{0:0}%}" />
    </LayoutTransformControl>
  </Grid>
</ControlTemplate>
```

Fluent Theme (src/Avalonia.Themes.Fluent/Controls/ProgressBar.xaml)
```
<ControlTemplate>
  <Border x:Name="ProgressBarRoot" ClipToBounds="True" Background="{TemplateBinding Background}" BorderBrush="{TemplateBinding BorderBrush}" BorderThickness="{TemplateBinding BorderThickness}" CornerRadius="{TemplateBinding CornerRadius}">          
      <Panel>
        <Panel x:Name="DeterminateRoot">
          <Border CornerRadius="{TemplateBinding CornerRadius}" x:Name="PART_Indicator" Margin="{TemplateBinding Padding}" Background="{TemplateBinding Foreground}" />
        </Panel>
        <Panel x:Name="IndeterminateRoot">
          <Border x:Name="IndeterminateProgressBarIndicator" CornerRadius="{TemplateBinding CornerRadius}" Margin="{TemplateBinding Padding}" Background="{TemplateBinding Foreground}" />
          <Border x:Name="IndeterminateProgressBarIndicator2" CornerRadius="{TemplateBinding CornerRadius}" Margin="{TemplateBinding Padding}" Background="{TemplateBinding Foreground}" />
        </Panel>
      </Panel>          
  </Border>
</ControlTemplate>
```

Is this a bug or am I misunderstanding something?

**Comment by Abdesol** [comment]
Could you describe how we can reproduce the bug?

**Comment by FRvanderVeen** [comment]
I made a small application to demonstrate it [AvaloniaProgressBar.zip](https://github.com/AvaloniaUI/Avalonia/files/7779245/AvaloniaProgressBar.zip)

In app.xaml comment the following line
```<FluentTheme Mode="Light"/>```
and change it to
```<StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml"/>```

As you can see, with the default theme the progressbar contains a '42%' text, with FluentTheme it doesn't

**Comment by robloo** [comment]
I think the Fluent Theme is actually correct for a few reasons:

1. Upstream WinUI has no percentage. Fluent is based on upstream 
2. The text brush color can't simply be foreground. It needs to change so it is visible reguardless of progress percent.

If the desire is to add this, I think it should be easily disabled with new property rather than retemplating.

I do realize since default theme has this, it is undesirable to loose the functionality with Fluent. I would argue it shouldn't have been there to begin with though.

**Comment by maxkatz6** [comment]
@robloo this ShowProgressText was old existing property used only on default theme. When we added Fluent one, this property apparently was ignored. So it worth to add it just for consistency of API.
