### ISSUE TITLE
System.InvalidOperationException: 'The control already has a visual parent.' Menu

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#7257]
**Describe the bug**
Throw System.InvalidOperationException when click on menu

**To Reproduce**

1. Run ControlCatalog.NetCore
2. Go Menu
3. Click on `First` Menu
4. Change Theme to FluentDark
5. Click on `First` Menu

**Expected behavior**
it do not Throw System.InvalidOperationException

**Screenshots**

**Desktop (please complete the following information):**

- Version: dc6df28e77671109e0b75e6b18b30022608c4f78

**Additional context**

**Comment by workgroupengineering** [comment]
It is probably the same problem as #4058.

**Comment by maxkatz6** [comment]
Dup of https://github.com/AvaloniaUI/Avalonia/issues/4839

Caused by materialized controls used as items source, which can't be reused with another parent (after theme was switched, template with itemspresenter is replaced)
