### ISSUE TITLE
Hang on MacOS when moving window from Mac screen to external monitor

### ISSUE THREAD

**Issue by cangosta** [AvaloniaUI/Avalonia#7276]
**Describe the bug**
When moving from mac display to an external display, sometimes the application hangs.

**To Reproduce**

1. Clone the repository: https://github.com/cangosta/AvaloniaHangSolution and make it run
2. Click on 'Open Window Example'
3. Drag the application window into an external display
4. Drag again the application window into the mac display
5. Repeat steps 3 and 4 till you get the busy cursor and a hang
4. Check attached gif

**Screenshots**
https://user-images.githubusercontent.com/848857/147569367-c646ba41-8cda-4fb9-85e2-11f4f08a7d03.mp4

**Desktop (please complete the following information):**

- OS: MacOS BigSur
- Version: happens from versiom v0.10.6 till v0.10.11
- Display:
-- MacBook Pro: 16-inch (3072 × 1920)
-- External Display: 1920x1080

**Additional context**

**Comment by grokys** [comment]
Unable to reproduce here (macOS Monterey 12.0.1) - @danwalmsley @Takoooooo are you able to repro?

**Comment by cangosta** [comment]
Hi @grokys @danwalmsley @Takoooooo, any news here?

**Comment by Takoooooo** [comment]
We talked with this user internally and it turned out to be not Avalonia problem.
