### ISSUE TITLE
Debugging Binding Fails is hard

### ISSUE THREAD

**Issue by mphipps1** [AvaloniaUI/Avalonia#7277]
When Binding fails, it is hard to figure out why. In my most recent case, I had forgotten to make the binding target a property. Yes, that's stupid. Guilty as charged. But something in the Avalonia diagnostics or (maybe better!) a way to see this in the Developer Tools would be really, really helpful. 

Noobs (it's been >10 years since I did any WPF/XAML) will struggle with issues like this. Any help for them would be nice!

Reproduce this: take any Avalonia project with DataContext set. Make the target of the DataContext a field instead of a property. Notice that it fails. Notice that there is no error message anywhere.

**Comment by mphipps1** [comment]
Debug output has some output (I just noticed it), but it also seems wrong - things that **do** bind get a line in the output that says that they do **not** bind (Could not find a matching property accessor for ...). That's really confusing.

**Comment by timunie** [comment]
@mphipps1 have you tried `CompiledBinding` ? It helped me a lot ^^ and is way better than WPF. You will need to define `x:DataType` in your root node.

**Comment by mphipps1** [comment]
I hadn't. I have now. That should *so* be the default. And it should have a documentation page! 
While that does help my situation, there will be people who can't use CompiledBinding, so I will leave the ticket open.

**Comment by maxkatz6** [comment]
We have Compiled Bindings, and there is documentation now (thanks @timunie!). It's not yet enabled by default though.
https://github.com/AvaloniaUI/Documentation/blob/master/docs/data-binding/compiledbindings.md

**Comment by ChadNedzlek** [comment]
Yeah. I'd like this to be better as well.  This doesn't seem "completed" to me.  Whenever a binding fails, I just get a random exception in main, but all the context is gone (it's rethrown from the "Win32DispacherImpl.RunLoop"). But I can't even tell _what_ it's trying to bind to or from. Just something unhelpful like "Unsuported IBinding implementation", and I have no way to know what binding it's even talking about. Or even which FILE it's trying to parse when that happens. A lot more context needs to be provided when a binding fails.
