### ISSUE TITLE
Incorrect Calendar Text Alignment

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#7333]
**Describe the bug**

This one has bothered me for a while. The Calendar has incorrect vertical alignment of text relative to the up/down arrows.

**Screenshots**

![image](https://user-images.githubusercontent.com/17993847/148698733-152826e2-8e6c-4b0f-b74f-f438b6dcef79.png)

**To Reproduce**

N/A

**Expected behavior**

Compared to WinUI/UWP (same as WPF)

![image](https://user-images.githubusercontent.com/17993847/148698793-6169c50b-5707-4cc5-b70b-47690c924192.png)

**Desktop (please complete the following information):**

- OS: All
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

The fix for this should be pretty simple assuming there is nothing strange as far as margins go in the template.

**Comment by timunie** [comment]
Hi @robloo ,

I think a pull request is very welcome, if you want to contribute.

Happy coding
Tim

**Comment by Abdesol** [comment]
Is there someone working on this issue?

**Comment by robloo** [comment]
@Abdesol, no and I have a limitless number of things to work on already :) If it is still open after some time I will probably fit it myself though.
