### ISSUE TITLE
RTL layout

### ISSUE THREAD

**Issue by danielmayost** [AvaloniaUI/Avalonia#7345]
**Describe the solution you'd like**
Currently, Avalonia does not support visual layout right to left, `Checkbox`, `Grid` etc does not implement `FlowDirection` property as in WPF, which is very limiting to design an application aimed at RTL languages (Hebrew, Arabic, Persian etc).

What I know WPF does is Invert the whole coordinate system of the window, including the top panel, and even GradientBrush.

see: https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/bidirectional-features-in-wpf-overview?view=netframeworkdesktop-4.8

**Additional context**
After that and @Gillibald's amazing work(#4893), Avalonia will be perfect and unique as a cross-platform tool that supports all languages.

**Screenshot**
WPF:
<img src="https://user-images.githubusercontent.com/41772276/148998259-099eaeb2-f071-49af-898d-33dd3fdacd1a.png" width=250 height=250>
Avalonia:
<img src="https://user-images.githubusercontent.com/41772276/148998500-4fb1cd09-8722-4755-8fd6-f01d2f1c6fbb.png" width=250 height=250>

Code:
```
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d"
        Title="שלום עולם!" Height="250" Width="250"
        FlowDirection="RightToLeft">
    <StackPanel>
        <RadioButton Content="אבגדהוזח"/>
        <Grid ShowGridLines="True">
            <Grid.ColumnDefinitions>
                <ColumnDefinition></ColumnDefinition>
                <ColumnDefinition></ColumnDefinition>
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition></RowDefinition>
                <RowDefinition></RowDefinition>
            </Grid.RowDefinitions>
            <TextBlock Text="Row0 Column0" Grid.Row="0" Grid.Column="0"/>
            <TextBlock Text="Row0 Column1" Grid.Row="0" Grid.Column="1"/>
            <TextBlock Text="Row1 Column0" Grid.Row="1" Grid.Column="0"/>
            <TextBlock Text="Row1 Column1" Grid.Row="1" Grid.Column="1"/>
        </Grid>
    </StackPanel>
</Window>
```

**Comment by idan-h** [comment]
> **Describe the solution you'd like** Currently, Avalonia does not support visual layout right to left, `Checkbox`, `Grid` etc does not implement `FlowDirection` property as in WPF, which is very limiting to design an application aimed at RTL languages (Hebrew, Arabic, Persian etc).
> 
> What I know WPF does is Invert the whole coordinate system of the window, including the top panel, and even GradientBrush.
> 
> see: https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/bidirectional-features-in-wpf-overview?view=netframeworkdesktop-4.8
> 
> **Additional context** After that and [@Gillibald](https://github.com/Gillibald)'s amazing work([#4893](https://github.com/AvaloniaUI/Avalonia/pull/4893)), Avalonia will be perfect and unique as a cross-platform tool that supports all languages.
> 
> **Screenshot** WPF: <img alt="" width="250" height="250" src="https://user-images.githubusercontent.com/41772276/148998259-099eaeb2-f071-49af-898d-33dd3fdacd1a.png"> Avalonia: <img alt="" width="250" height="250" src="https://user-images.githubusercontent.com/41772276/148998500-4fb1cd09-8722-4755-8fd6-f01d2f1c6fbb.png">
> 
> Code:
> 
> ```
> <Window x:Class="WpfApp1.MainWindow"
>         xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
>         xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>         xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
>         xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
>         mc:Ignorable="d"
>         Title="שלום עולם!" Height="250" Width="250"
>         FlowDirection="RightToLeft">
>     <StackPanel>
>         <RadioButton Content="אבגדהוזח"/>
>         <Grid ShowGridLines="True">
>             <Grid.ColumnDefinitions>
>                 <ColumnDefinition></ColumnDefinition>
>                 <ColumnDefinition></ColumnDefinition>
>             </Grid.ColumnDefinitions>
>             <Grid.RowDefinitions>
>                 <RowDefinition></RowDefinition>
>                 <RowDefinition></RowDefinition>
>             </Grid.RowDefinitions>
>             <TextBlock Text="Row0 Column0" Grid.Row="0" Grid.Column="0"/>
>             <TextBlock Text="Row0 Column1" Grid.Row="0" Grid.Column="1"/>
>             <TextBlock Text="Row1 Column0" Grid.Row="1" Grid.Column="0"/>
>             <TextBlock Text="Row1 Column1" Grid.Row="1" Grid.Column="1"/>
>         </Grid>
>     </StackPanel>
> </Window>
> ```

Correct me if I am wrong, but this issue is not fully solved? The title bar still stays LTR, even when the window's direction flow is RTL.

**Comment by danielmayost** [comment]
Actually, you're right, but since the main problem has been solved, and the rest is a matter of platform-dependent API, it seems to me that this requires a new issue.
