### ISSUE TITLE
ListBox containing Items that have IsVisible = false, are able to be selected and show blank on list

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#7346]
**Describe the bug**
ListBox containing Items that have IsVisible = false, are able to be selected and show blank on list.

**To Reproduce**
```XML
 <ListBox
                  Grid.Row="1"
                  Name="SuggestionsListBox"
                  SelectionMode="Multiple,Toggle"
                  Items="{Binding Suggestions}">
                      <ListBox.ItemTemplate>
                          <DataTemplate>
							  <TextBlock Text="{Binding Message}"
                                         TextWrapping="Wrap"
                                         ToolTip.Tip="{Binding ToolTip}">
								  <TextBlock.IsVisible>
									  <MultiBinding Converter="{x:Static BoolConverters.And}">
										  <Binding Path="Enabled"/>
										  <Binding Path="!IsApplied"/>
									  </MultiBinding>
								  </TextBlock.IsVisible>
                              </TextBlock>
                          </DataTemplate>
                      </ListBox.ItemTemplate>
                </ListBox>
```

**Expected behavior**
IsVisible=False items to now show and be unable to click/select

**Screenshots**
![image](https://user-images.githubusercontent.com/113281/149007820-567ad462-20dc-4560-a4e0-b9978167c240.png)

**Desktop (please complete the following information):**

Operative system: Microsoft Windows 11 X64
Runtime: win10-x64
Framework: .NET 5.0.13
AvaloniaUI: 0.10.11

**Comment by workgroupengineering** [comment]
The behavior is correct, You hide the Textbox not the ListBoxItem.

I think the optimal solution could be such a thing:

```csharp

public  EditorViewModel:BaseViewModel
{

   ....
   public ItemViewModel? SelectedItem
   {
       get => _selectedItem;
       set
       {
            if (RaiseAndSetIfChanged(ref __selectedItem, value)
            {
                RaisePropertyChanged(nameof(Suggestions));
            }
       }
   }

   public IEnumerable<SuggestionViewModel> Suggestions
   {
      get
      {
          if (SelectedItem is null)
              return Array.Empty<SuggestionViewModel>()
          return SelectedItem.Suggestions.Where(s=>s.Enabled && !s.IsApplied);
      }
   }
}

```

**Comment by maxkatz6** [comment]
You also can set IsVisible property on ListBoxItem using a style with selector

**Comment by sn4k3** [comment]
> The behavior is correct, You hide the TextBlock not the ListBoxItem.

Makes sense. Is there a way to set the **ListBoxItem** properties inside data template?

Currently i'm using this:

```C#
public void PopulateSuggestions()
        {
            var suggestionsToApply = new List<Suggestion>();
            var suggestionsApplied = new List<Suggestion>();
            foreach (var suggestion in Suggestions)
            {
                suggestion.SlicerFile = SlicerFile;
                if(!suggestion.Enabled || !suggestion.IsAvailable) continue;
                suggestion.ExecuteIfAutoApply();

                if(suggestion.IsApplied) suggestionsApplied.Add(suggestion);
                else suggestionsToApply.Add(suggestion);
            }

            SuggestionsToApply.ReplaceCollection(suggestionsToApply);
            SuggestionsApplied.ReplaceCollection(suggestionsApplied);
        }

        public async void ApplySuggestionsClicked()
        {
            if (await this.MessageBoxQuestion("Are you sure you want to apply the following suggestions?:",
                    "Apply suggestions?") != ButtonResult.Yes) return;

        }
```

> You also can set IsVisible property on ListBoxItem using a style with setters

How can i achieve that?

**Comment by KriskotooBG** [comment]
Sorry for bumping an old issue but I did not figure out a way to do this in 11.x
Going with the styles setter example results in this:
![image](https://github.com/AvaloniaUI/Avalonia/assets/29774713/aa0e252d-6834-428b-92f9-894b652f4bd6)

Unable to resolve property or method of name 'IsEnabled' on type 'MainWindowViewModel'.
Which makes sense, but I'm not sure how it can be bound to the property

**Comment by rabbitism** [comment]
> Unable to resolve property or method of name 'IsEnabled' on type 'MainWindowViewModel'. Which makes sense, but I'm not sure how it can be bound to the property

You can specify the `x:DataType` in style selector, which should be the data type of elements in `Entries`.
