### ISSUE TITLE
Visual add/remove slow in some scenarios

### ISSUE THREAD

**Issue by wgebczyk** [AvaloniaUI/Avalonia#7352]
**Describe the bug**
For Avalonia app created from scratch with changes as in below gist link, performance differs depending on case:
- VS AXAML designer - works fast (squares are changed/refreshed/rendered fast)
- Runtime Debug or Release - works slow
- Runtime when wrapping local:MyContainer in Viewbox (like in AXAML commented fragment) - works fast

What is the reason of slowness without Viewbox? Why it works fast in VS?
If you change SIZE2 and SIZE3 to non integer value like 10.1, it is faster again.

**To Reproduce**
https://gist.github.com/wgebczyk/771aac47ead2c3c531b1d4fe98aa1c05

**Expected behavior**
Performance wit and without Viewbox is comparable.
Performance in app and designer is comparable.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version 11

**EDIT**: A few more comments.

Digging more into this, I get impression that:
- drawing Rectangle of non integer size makes it speedy once again
- looks like there is some mechanism that tries to detect if drawing "intention" is to be pixel-aligned
- WHAT's that "mechanism"?
- whenever it detects that drawing should be pixel-fraction, then this expensive mechanism/calculation is turned off
- when you have "scene" with many elements (like a few thousand(s) simple rectangles) then removing and adding child visual re-renders ALL of them, even if only 2 elements has changed. This might indicate that Window with many elements, might suffer perf penalty, when only a few small elements are changes in scene tree,
- there seems not to be mechanism to mark some subtree of scene nodes to have drawing buffer (some subtree is rendered first to back buffer, then this buffer is updated ONLY when anything in subtree is changed) and then simply buffer/bitmap is drawn during scene rendering.
- BTW: When trying to implement myself such buffer, I've spotted that blendMode=Clear is not exposed from SKIA - which is sad as I have to workaround that with additional operations.

**Comment by wgebczyk** [comment]
Any comments on that? Any insights into the cause?

**Comment by ahopper** [comment]
I've not run your sample but if the rectangles sometimes overlap with some settings and not with others you may be hitting this https://github.com/AvaloniaUI/Avalonia/issues/3672 . I believe there is a new renderer in the pipeline that should fix that issue.

**Comment by gebcwoj** [comment]
But then how wrapping this in Viewbox help? They still be non-overlapping. Who is working on mentioned issue? I could ask there...

**Comment by ahopper** [comment]
you could set Renderer.DrawDirtyRects = true; in the MainWindow constructor to see what is happening.

**Comment by gebcwoj** [comment]
It seems that with Viewbox, some dirty regions are "merged" into bigger rect. Can you point me to the code where those "dirty rects" are processed/merged?

**Comment by ahopper** [comment]
I just had a play with this, if you make the rectangles smaller so they never overlap it becomes slow even in a viewbox. I suspect rounding is probably changing just how many get merged.

**Comment by gebcwoj** [comment]
OK --- can you point me to c# code where this merging is happening?

**Comment by ahopper** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Rendering/DirtyRects.cs a real crude but simple fix is to merge all if >6 or so areas.  I started a more sophisticated fix but put it on hold as the new renderer was in the pipeline.

If you simply put an InvalidateVisual() in you outer UpdateRandom it works better.  That made me wonder if there might be a case for some sort of render hint for this sort of thing.

**Comment by wgebczyk** [comment]
Ha! I've just finished my quick research :)

My understanding of what is happening:
- We have 'internal class DirtyRects' that tracks regions (rects) for window.
- Whenever we mark as dirty specific visual, it get added to list EXCEPT when it intersect with existing one, then we just expand it.
== If there are many 'Add(Rect rect)', then it might be worth to check if having 'if (!r.TryUnion(rect)) _rects.Add(rect);' would reduce calls/operations - might be not worth is Rect calls are inlined.
- Then we have DeferredRenderer which does 'void RenderToLayers(Scene scene)'
- This beast will repeat below process FOR EACH dirty rect:
== Traverse whole 'scene' visual tree
== Check if subtree overlaps in any way with 'dirty rect'
==== Here we might have 'if (node.ClipBounds.TryIntersect(clipBounds, out var clipBounds)) { ... }' to avoid allocation of intersection if not needed - especially for cases where rect is not overlapping with many visuals.
== Re-render visual

Thoughts:
- RenderToLayers does 'var snappedRect = SnapToDevicePixels(rect, scale)' - this means that if I would expand a little (0.01) of 'pixel' sibilling rects, then there is higher chance to make it overlap and reduce number of dirty regions.
- If you not have too many non-overlapping sibilings in visual tree, then this should be good enough system - there will not be too many disjoint rects and rather you will expand existing ones.
- I saw comment 'TODO: We probably want to put an upper limit on the number of visuals that can be stored and if we reach that limit, assume all visuals are dirty.'
== As this would help, then how this threshold should be calculated? Absolute number? percentage? etc
== Maybe after passing some very low number, this DirtyVisuals/DirtyRects, could be swapped with some K-d tree, BSP etc? And instead of FOREACH RECT, there could be one traverse with check on tree if specific visual is dirty or not - I assume that dirty checks can be made fast.
== Or storing some "bit" of information in Visual itself if is dirty or not...

I could give it a try in my spare time if that would help...

**Comment by grokys** [comment]
Hi @wgebczyk - yes as you noticed the dirty rect code we currently have isn't very good. I don't think there's much point making changes to the rendering code at this point though because we're planning on having a completely rewritten renderer available in the next few months.

**Comment by gebcwoj** [comment]
Thank you for answer.
