### ISSUE TITLE
Lack of anti-aliasing when encapsulating any control in a Border with a set CornerRadius

### ISSUE THREAD

**Issue by JamDoggie** [AvaloniaUI/Avalonia#7358]
**Describe the bug**
Avalonia's renderer does not seem to de-alias rounded corners of a Border correctly when an image is in the corner. Could apply to other controls as well.

**To Reproduce**

1. Create a new Avalonia project.
2. Add an image to your Assets folder, preferably one that is not transparent around the corners so the effect is visible, and one that is is a contrasting color to the background.
3. In the main window, put a Border as the main child of the window, make sure it is the same size as your chosen image, set the CornerRadius of the border to something like 20 or 30 depending on your image size, place an Image tag inside your border with your chosen image URI, then set "ClipToBounds" to "true" on the border. See screenshots for example AXAML.

**Expected behavior**
Avalonia should apply proper anti aliasing to the corners, like the second example screenshot below (taken from chrome).

**Screenshots**
![An example of the problem, taken from a new Avalonia project](https://i.gyazo.com/2622fce20c8d70198ce8c8c9f9e186b9.png)
![Expected behavior, taken from Chrome](https://i.gyazo.com/24a4c9cff43eb796802cde5c7c67bbe0.png)
![Example AXAML that should reproduce the problem in Avalonia 0.10.11 & 0.10.10](https://i.gyazo.com/20fa6e7f498902177e9e57821fe8964f.png)

**Desktop:**

- OS: Windows 11, Windows 10, Ubuntu 20.04 via WSL2, and Manjaro Linux with NVIDIA proprietary drivers.
- Version: 0.10.11 & 0.10.10

**Comment by amwx** [comment]
It's not just with images, but anything that gets clipped via border with corner radius has the same behavior

Looks like `PushClip` in Skia doesn't set the antialias argument on `SKCanvas.ClipRoundRect()`
https://github.com/AvaloniaUI/Avalonia/blob/f29ed1a12781dc3508bbdad3ead7191ebd3db40a/src/Skia/Avalonia.Skia/DrawingContextImpl.cs#L482-L486

**Comment by JamDoggie** [comment]
So would this be as simple as a pull request that includes this argument in this call, then?

**Comment by robloo** [comment]
It does look that simple: https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skcanvas.cliproundrect?view=skiasharp-2.80.2

**Comment by JamDoggie** [comment]
Cool. I'll fork, test, and make a pull request.
