### ISSUE TITLE
TextAlignment Center doesn't work for TextBox

### ISSUE THREAD

**Issue by moucha19** [AvaloniaUI/Avalonia#7362]
**Describe the bug**
TextAligment set to Center is broken in the latest update.

**To Reproduce**

1. Create blank Avalonia MVVM template
2. Change TextBlock in MainWindow.axaml to TextBox
3. Add `TextAlignment="Center"`

**Expected behavior**
Text should be centered and cursor should be behind the last character when typing. However, text is drifting to the right and the cursor is also broken. Example is in the included pictures.

**Screenshots**
_Expected behavior (Avalonia 0.10.10)_
![CorrectTextCentered](https://user-images.githubusercontent.com/43780315/149552942-be0da042-0f07-4d4e-abdc-671ab783eaf9.png)

_Buggy behavior (Avalonia 0.10.11)_
![BuggyTextCentered](https://user-images.githubusercontent.com/43780315/149552941-51f19405-6ecb-4b7f-8f25-d00de383834a.png)

**Desktop:**

- OS: Windows 10 20H2
- Version 0.10.11

**Comment by Gillibald** [comment]
Fixed: #7350

Feel free to reopen if the issue still persists after that fix was released
