### ISSUE TITLE
OnKeyDown Esc not work after using Esc to close menu

### ISSUE THREAD

**Issue by SnowyYANG** [AvaloniaUI/Avalonia#7363]
**Describe the bug**
I write some features with `e.Key == Key.Escape` in MainWindow.OnKeyDown. The features will work if I just press Esc after the window shows. However, if I click to open the menu and using Esc to close the menu, the features will not be triggered again. The workaround is to switch windows and the Esc key will be effective again.

**To Reproduce**

1. Create a menu in MainWindow, write down some code with `if (e.Key == Key.Escape)` in MainWindow.OnKeyDown 
2. Debug
3. Click MenuItem to open menu
4. Press Esc to close menu
5. Press Esc again, nothing happened, some code not run.

**Expected behavior**
After step 4, press Esc again, some code should run.

**Screenshots**
none

**Desktop (please complete the following information):**

- OS: Windows, Mac
- Version 0.10.11

**Additional context**
none

**Comment by Takoooooo** [comment]
I've done code like that and I can't repro the issue, therefore, closing. Feel free to reopen if I've made something wrong.
https://recordit.co/AJKdMmVhPP

**Comment by SnowyYANG** [comment]
> I've done code like that and I can't repro the issue, therefore, closing. Feel free to reopen if I've made something wrong. https://recordit.co/AJKdMmVhPP

I wrote the "The workaround is to switch windows and the Esc key will be effective again". You break the debugger and switched the window, so the Esc works. Try to write some code like changing a TextBlock's text in the window with the Esc key, and it will not work.
