### ISSUE TITLE
Mobile ports

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#737]
I'm wanting to shortly embark on implementing "draw only dirty regions" for Avalonia. This will be a major  change that will probably touch some of the platform-specific APIs.

However, there is a problem with the mobile ports in that:
1. I don't want to break them
2. But I have no way of testing them:
   - I don't have a Mac so I can't even compile the iOS port
   - The android port doesn't currently seem to run so I'm not able to checks for breakage there

I wonder if I could have your feedback on how we should proceed. There are 2 options as far as I can see:
1. Fix up Android(*)  so I can test that. someone else would have to follow the development branch and periodically fix up the iOS port for me
2. I make the changes not thinking about the mobile ports and we clear up the mess when it's finished

@kekekeks @jazzay what are your thoughts?

*: Get ControlCatalog.Android working, remove AndroidTestApplication as even TestApplication is broken currently and should be removed

**Comment by kekekeks** [comment]
Well, you could use double buffering, cache the last frame in offscreen bitmap, update dirty regions and then render it to whatever render target is provided. You won't have to touch platform-specific API during development and after that we could provide platform-specific ways of skipping offscreen-bitmap part.

**Comment by kekekeks** [comment]
I also suspect that you have to redraw the whole frame with opengl anyway, since FBO with the last one is currently locked and can't be used, so we'll need double-buffering support anyway.

**Comment by grokys** [comment]
Yeah, that's probably what I'll end up doing. However, there will still possibly be some changes to the platform API, I'm not sure what's needed yet.

So the question remains regarding the mobile ports. To be honest, even if ControlCatalog.Android worked it would be a help - at least I could try not to break that.

**Comment by grokys** [comment]
Regarding iOS, I really need a mac. What's the cheapest second-hand mac that would be suitable as a build machine? I know nothing about macs.

**Comment by donandren** [comment]
@grokys cheapest method I've used year ago is the virtual machine like: https://goo.gl/0ecLbz.
It worked fast and well for me and I've used XCode and iOS Emulator around 2,3 months. Not sure that's still an option, but worth trying it. If you have enough RAM (16 GB should be enough) and SSD probably it can work well for you.

**Comment by weitzhandler** [comment]
Is there a way to run an Avalonia app with the Android or UWP **mobile** emulators inside VS?
