### ISSUE TITLE
Window Position Not Working

### ISSUE THREAD

**Issue by nlogozzo** [AvaloniaUI/Avalonia#7375]
Hi all,
I'm trying to move a window to the bottom of the screen using the following code: `Position = PixelPoint.FromPoint(new Point(0, Screens.Primary.Bounds.Bottom - Height), 0);` However, the window does not move and stays in the center of the screen. I'm running Fedora 35/GNOME/X11

**Comment by hhyyrylainen** [comment]
Is this a duplicate of: https://github.com/AvaloniaUI/Avalonia/issues/3387 ?

**Comment by maxkatz6** [comment]
Duplicate
