### ISSUE TITLE
Implement TextAlignment=Justify

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#738]

**Comment by danwalmsley** [comment]
in looking at this, Skia doesn't seem to support Justified text, all other backends its very easy, any suggestions?

**Comment by CastelloBrancoTecnologia** [comment]
Not Working 

![image](https://github.com/AvaloniaUI/Avalonia/assets/138352584/90a3f046-e4c6-4001-9441-b834664e4568)


                <TextBlock
                    Margin="0,10,0,0"
                    Text="Descrição:" />
                <Border BorderBrush="Black" BorderThickness="1">
                    <TextBlock
                        Width="400"
                        Height="100"
                        Text="{Binding Expositor.Descricao}"
                        TextAlignment="Justify" />
                </Border>

**Comment by Gillibald** [comment]
You are not enabling text wrap
