### ISSUE TITLE
PastingFromClipboard is not fired when pasting via CTRL+V or context menu 

### ISSUE THREAD

**Issue by AcidJunkie303** [AvaloniaUI/Avalonia#7384]
**Describe the bug**
`TextBox.PastingFromClipboard` event is not fired when pasting in text other than calling `TextBox.Paste()`. That means when I paste in text using CTRL+V (in windows) or via the context menu, this event is not fired.

**To Reproduce**
See bug description

**Expected behavior**
`TextBox.PastingFromClipboard` event is fired in all cases.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Windows 10
- Avalonia Version 0.10.11

**Additional context**
N/A

**Comment by emmauss** [comment]
This is fixed as of 11.0.0-preview4
