### ISSUE TITLE
Main window does not close on rpi linux 

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#7392]
**Describe the bug**
Closing the main window of my app just freezes the app if things are changing on the screen at the time.
The minimize and maximize buttons still work but the window is blank if you click them. No exceptions are reported.

**Desktop (please complete the following information):**

- OS: 32bit Raspbian
- Version 0.10.11 and master 0.10.999-cibuild0018001-beta

**Additional context**

**Comment by kekekeks** [comment]
Please run [dotnet-stack](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-stack) tool to collect stack traces

**Comment by ahopper** [comment]
I'm having trouble getting any sense out of dotnet-stack on rpi, see below.  All hints welcome.

Thread (0x17DF):
  [Native Frames]
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?

Thread (0x17E8):
  [Native Frames]
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?
  ?!?

Thread (0x17EA):
  [Native Frames]
  ?!?
  ?!?

Thread (0x17FB):
  [Native Frames]
  ?!?
  ?!?
  ?!?
  ?!?

Thread (0x18DE):
  CPU_TIME
  ?!?
  ?!?
  ?!?
  ?!?

Thread (0x18DF):
  [Native Frames]
  ?!?
  ?!?
  ?!?
  ?!?

**Comment by ahopper** [comment]
On trying on x64 linux I get a similar thing but also a report of malloc_consolidate(): invalid chunk size on close which maybe my code so I'll close this until I eliminate my code.

**Comment by ahopper** [comment]
This is the dotnet-stack report on linux x64 in the frozen state

Thread (0x2FF1):
  [Native Frames]
  Avalonia.Visuals!Avalonia.Rendering.DeferredRenderer.Dispose()
  Avalonia.Controls!Avalonia.Controls.TopLevel.HandleClosed()
  Avalonia.Controls!Avalonia.Controls.WindowBase.HandleClosed()
  Avalonia.Controls!Avalonia.Controls.Window.HandleClosed()
  Avalonia.X11!Avalonia.X11.X11Window.Cleanup()
  Avalonia.X11!Avalonia.X11.X11Window.Dispose()
  Avalonia.Controls!Avalonia.Controls.Window.CloseInternal()
  Avalonia.Controls!Avalonia.Controls.Window.HandleClosing()
  Avalonia.X11!Avalonia.X11.X11Window.OnEventSync(value class Avalonia.X11.XEvent&)
  Avalonia.X11!Avalonia.X11.X11Window.OnEvent(value class Avalonia.X11.XEvent&)
  Avalonia.X11!Avalonia.X11.X11PlatformThreading.HandleX11(value class System.Threading.CancellationToken)
  Avalonia.X11!Avalonia.X11.X11PlatformThreading.RunLoop(value class System.Threading.CancellationToken)
  Avalonia.Base!Avalonia.Threading.Dispatcher.MainLoop(value class System.Threading.CancellationToken)
  Avalonia.Controls!Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(class System.String[])
  SparkSDR!SparkSDR.Program.Main(class System.String[])

Thread (0x2FFD):
  CPU_TIME
  Avalonia.X11!Avalonia.X11.X11PlatformLifetimeEvents.HandleRequests()
  Avalonia.X11!Avalonia.X11.X11PlatformLifetimeEvents.<.ctor>b__20_0()
  System.Private.CoreLib!System.Threading.Tasks.Task.InnerInvoke()
  System.Private.CoreLib!System.Threading.Tasks.Task+<>c.<.cctor>b__272_0(class System.Object)
  System.Private.CoreLib!System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(class System.Threading.Thread,class System.Threading.ExecutionContext,class System.Threading.ContextCallback,class System.Object)
  System.Private.CoreLib!System.Threading.Tasks.Task.ExecuteWithThreadLocal(class System.Threading.Tasks.Task&,class System.Threading.Thread)
  System.Private.CoreLib!System.Threading.Tasks.Task.ExecuteEntryUnsafe(class System.Threading.Thread)
  System.Private.CoreLib!System.Threading.ThreadPoolWorkQueue.Dispatch()
  System.Private.CoreLib!System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
  System.Private.CoreLib!System.Threading.Thread.StartCallback()

Thread (0x2FFE):
  CPU_TIME
  System.Private.CoreLib!System.Threading.WaitHandle.WaitOneNoCheck(int32)
  System.Private.CoreLib!System.Threading.WaitHandle.WaitOne()
  System.Private.CoreLib!System.Threading.PortableThreadPool+GateThread.GateThreadStart()
  System.Private.CoreLib!System.Threading.Thread.StartCallback()

Thread (0x3001):
  CPU_TIME
  Avalonia.X11!Avalonia.X11.X11Window.get_RenderScaling()
  Avalonia.Skia!Avalonia.Skia.GlRenderTarget.BeginRenderingSession()
  Avalonia.Skia!Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(class Avalonia.Rendering.IVisualBrushRenderer)
  Avalonia.Visuals!Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(class Avalonia.Platform.IDrawingContextImpl&)
  Avalonia.Visuals!Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(class Avalonia.Platform.IDrawingContextImpl&,bool)
  Avalonia.Visuals!Avalonia.Rendering.DeferredRenderer.Render(bool)
  Avalonia.Visuals!Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Render()
  Avalonia.Visuals!Avalonia.Rendering.RenderLoop.TimerTick(value class System.TimeSpan)
  Avalonia.Visuals!Avalonia.Rendering.SleepLoopRenderTimer.LoopProc()
  System.Private.CoreLib!System.Threading.Thread.StartCallback()

Thread (0x3003):
  CPU_TIME
  ?!?
  System.Net.Sockets!System.Net.Sockets.SocketAsyncEngine.EventLoop()
  System.Net.Sockets!System.Net.Sockets.SocketAsyncEngine+<>c.<.ctor>b__14_0(class System.Object)
  System.Private.CoreLib!System.Threading.Thread.StartCallback()

Thread (0x309C):
  [Native Frames]
  ?!?
  System.Private.CoreLib!System.Threading.LowLevelLifoSemaphore.WaitForSignal(int32)
  System.Private.CoreLib!System.Threading.LowLevelLifoSemaphore.Wait(int32,bool)
  System.Private.CoreLib!System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
  System.Private.CoreLib!System.Threading.Thread.StartCallback()

Thread (0x309D):
  [Native Frames]
  ?!?
  System.Private.CoreLib!System.Threading.LowLevelLifoSemaphore.WaitForSignal(int32)
  System.Private.CoreLib!System.Threading.LowLevelLifoSemaphore.Wait(int32,bool)
  System.Private.CoreLib!System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
  System.Private.CoreLib!System.Threading.Thread.StartCallback()

**Comment by ahopper** [comment]
Re opening as there appears to be an opportunity for a deadlock between DeferredRenderer.Dispose() and X11Window.get_RenderScaling()

**Comment by ahopper** [comment]
This can be repro'd on the .netcore version of https://github.com/ahopper/zombieturkey on linux if you close the window whilst things are moving.  The stack trace is basically the same.

**Comment by ahopper** [comment]
X11Window.OnEvent creates a lock on the window close event then waits for the render thread in DeferredRenderer.Dispose(),
the render thread calls X11Window.get_RenderScaling() which shares the same lock so blocks.

**Comment by ahopper** [comment]
I have little experience of the linux back end, what is the purpose of the lock here?
https://github.com/AvaloniaUI/Avalonia/blob/2950c450d4fa21557d4a293b6636b806e63cd386/src/Avalonia.X11/X11Window.cs#L318-L327
If it is just to prevent torn reads of the double on 32 bit platforms it could be replaced with a local lock on set or
```
public double RenderScaling
{
    get { return Interlocked.CompareExchange(ref _scaling, 0.0, 0.0); }
    set { Interlocked.Exchange(ref _scaling, value); }
}
```
or is something more complex going on?

**Comment by kekekeks** [comment]
The entire SyncRoot object looks like a leftover from some previous logic.
