### ISSUE TITLE
Canceling the closing event is not working

### ISSUE THREAD

**Issue by os-lmo** [AvaloniaUI/Avalonia#7393]
**Describe the bug**
If we enable the `Cancel` arg in the `Closing` event, Avalonia is ignoring it and the application closes.
It only happens in `0.10.999-cibuild0017786-beta` version

**To Reproduce**

1. In MacOS, build the demo available [here](https://github.com/heldergoncalves92/Avalonia-Cancel-On-Closing-Event-Is-Ignored)
2. Open the demo
2. Go to the native menu and choose "Quit" (or Cmd + Q)
3. The application closes, and it shouldn't

**Expected behavior**
The application should not close, since we are explicitly canceling the close.

**Screenshots**
We are canceling the close event but it seems not having effect
![image](https://user-images.githubusercontent.com/73111913/150171587-04377599-cb56-41e1-9d14-4480ee30ecef.png)

**Desktop (please complete the following information):**

**Comment by maxkatz6** [comment]
Window is not closing, but whole app is shutting down. It's a special behavior of macos, which doesn't even tried to close windows at this point.
If you need to cancel app shutting down - there is ShutdownRequested event. 
Although as I see from other ticket, there is a problem too https://github.com/AvaloniaUI/Avalonia/issues/7389

**Comment by heldergoncalves92** [comment]
Is this a behavior that changed on purpose? Since versions equal and below `0.10.11` do not have that behavior.
