### ISSUE TITLE
WASM AOT build fails

### ISSUE THREAD

**Issue by wihrl** [AvaloniaUI/Avalonia#7396]
**Describe the bug**
AOT compilation fails.
`wasm-ld: Error  : initial memory too small, 40686144 bytes needed`

**To Reproduce**

1. Create a project with the cross platform template.
2. Publish WASM project with AOT enabled.

![image](https://user-images.githubusercontent.com/57505542/150194542-a08ab1b7-32f2-4b1f-ac7a-05f2e66fc0f0.png)

**Comment by kekekeks** [comment]
```xml
<PropertyGroup>
 <EmccTotalMemory>Insert required memory here</EmccTotalMemory>
</PropertyGroup>
```

**Comment by wihrl** [comment]
Thanks, that worked. Is it normal for the build to take 30 minutes? It's just a hello world with ReactiveUI and DynamicData. I have an 8-core cpu...

**Comment by kekekeks** [comment]
AOT builds are expected to be quite slow, yes.

**Comment by wihrl** [comment]
Welp, that sucks. The original issue is solved.
