### ISSUE TITLE
Trying to load previewer in VS2022: Could not load file or assembly Avalonia.Base

### ISSUE THREAD

**Issue by ps-DaveMeier** [AvaloniaUI/Avalonia#7398]
**Describe the bug**
I built the latest VS2022 Avalonia extension, then added a new Window.axaml. I installed the Avalonia and Avalonia.Desktop nuget packages and don't have any errors when I look at them in the Dependencies/Packages. The paths all look correct and I see Avalonia.Base.dll in there.

**To Reproduce**
See above.

1. Select my Windows.axaml file and choose to "View Designer"

**Expected behavior**
Designer should appear.

**Avalonia Diagnostics Pane**
17:42:45.226 [Information]  Stopping previewer process
17:42:45.227 [Information]  Stopping previewer process
17:42:50.973 [Information] 0 Starting previewer process for '"C:\github\Core-Net6\zzzz\bin\Debug\net6.0-windows\zzzz.dll"'
17:42:51.000 [Information] 39136 Started previewer process for '"C:\github\Core-Net6\zzzz\bin\Debug\net6.0-windows\zzzz.dll"'. Waiting for connection to be initialized.
17:42:51.344 [Error] 39136 <= "Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Avalonia.Base, Version=0.10.11.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'. The system cannot find the file specified."
17:42:51.350 [Error] 39136 <= "File name: 'Avalonia.Base, Version=0.10.11.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'"
17:42:51.352 [Error] 39136 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args)"
17:42:53.125 [Information]  Process exited while waiting for connection to be initialized.
17:42:53.137 [Information]  Process exited
17:42:53.139 [Information]  Stopping previewer process

Windows 10, VS 2022.

![image](https://user-images.githubusercontent.com/89860552/150247528-c4273aec-a877-425e-9d1d-1eebf0bd9563.png)

**Comment by ps-DaveMeier** [comment]
This is a .Net 6 project, currently net6.0-windows until I can swap out the WinForms and then change it to net6.0.

**Comment by ps-DaveMeier** [comment]
I've gotten past this by creating an empty Avalonia project and copying the bootstrapping code to my project.

**Comment by BunnyTub** [comment]
I have this problem too. If it helps, I've migrated from a .NET Framework project up to .NET 9.
