### ISSUE TITLE
Add Rider plugin

### ISSUE THREAD

**Issue by Urgau** [AvaloniaUI/Avalonia#740]
Can you create a plugin for Rider IDE ?

**Comment by kekekeks** [comment]
Rider currently lacks proper plugin SDK. It's also currently impossible to have custom DTO for IDEA<->R# communication. We also need a portable previewer infrastructure (#900). So right now this is blocked by issues on our side and on rider side.

**Comment by Urgau** [comment]
Okay

**Comment by MonkAlex** [comment]
Rider try to add references to avalonia xaml and rename all classes to some <data:Binding> for example. 
What can i do?

![2017-08-19 20-36-37](https://user-images.githubusercontent.com/6784764/29488532-3ae2117c-851e-11e7-9e86-8e9d2899a715.png)

**Comment by kekekeks** [comment]
>What can i do?

Go to https://youtrack.jetbrains.com/issues/RIDER and fill a bug report.

**Comment by MonkAlex** [comment]
Reported as [RIDER-8780](https://youtrack.jetbrains.com/issue/RIDER-8780)

**Comment by 06needhamt** [comment]
Is this still in active development if so I would like to help out wherever possible

**Comment by kekekeks** [comment]
@06needhamt 
We've done everything that's needed to be done on Avalonia side. Now waiting for Rider guys to release a proper SDK.

**Comment by Gaulomatic** [comment]
Are there any new to this?

**Comment by matkoch** [comment]
@kekekeks SDK ships the required parts now as documented [here](https://www.jetbrains.com/help/resharper/sdk/Products/Rider.html). It's pretty fresh, so ping me if you have any problems. We also have a Slack channel that I can invite you to, if you like.

I'm also working on a dotnet project template to get started, but this will probably take time until next week.

**Comment by matkoch** [comment]
@kekekeks there is a template now located [here](https://github.com/matkoch/resharper-sampleplugin). It is a work-in-progress, so if you have any questions, don't hesitate to ping me via GH issues or somewhere privately if you prefer.

**Comment by ingvar1995** [comment]
Rider is ready for writing plugins but still lacks a lot of docs about plugin development process. I started writing such plugin [in my repo](https://github.com/ingvar1995/rider-avalonia-plugin) but it will be really long process due to difficulty of plugin development. For example, right now my plugin has nothing except adding avalonia project types, but even this simple operation isn't obvious to implement and missing docs... Anyway I will keep updating it, Rider is my favorite IDE, I wanna see avalonia support in it!

**Comment by ForNeVeR** [comment]
@ingvar1995 hey sorry if I discourage you, but I don't think we need Avalonia project templates in Rider. Rider supports .NET Core standard templates, and [Avalonia already has them](https://github.com/AvaloniaUI/avalonia-dotnet-templates).

**Comment by ingvar1995** [comment]
This is just for start. Anyway manual installing templates seems to be annoying for me so it's good to have ready template built-in in Rider

**Comment by jinek** [comment]
![image](https://user-images.githubusercontent.com/10516222/56994741-49497100-6ba0-11e9-9f14-c280b956bd5d.png)
For me none of resharper things works in Rider. On screenshot I referenced some unexciting property, no error shown in rider. Suggestions, auto completing, and all this stuff don't work.

**Comment by worldbeater** [comment]
@jinek try using the `EmbeddedResource` directive for embedding Avalonia XAML files, instead of `AvaloniaResource` used by default. Rider doesn't understand the latter one currently, but understands the former. See [an example project](https://github.com/worldbeater/ReactiveMvvm/blob/master/ReactiveMvvm.Avalonia/ReactiveMvvm.Avalonia.csproj#L10) where IntelliSense in XAML is working in Rider.

**Comment by ForNeVeR** [comment]
You guys better file these issues in https://github.com/ForNeVeR/AvaloniaRider
We could teach Rider to enable the XAML features on `AvaloniaResource` and perform other customizations.

**Comment by jinek** [comment]
> 
> 
> @jinek try using the `EmbeddedResource` directive for embedding Avalonia XAML files, instead of `AvaloniaResource` used by default. Rider doesn't understand the latter one currently, but understands the former. See [an example project](https://github.com/worldbeater/ReactiveMvvm/blob/master/ReactiveMvvm.Avalonia/ReactiveMvvm.Avalonia.csproj#L10) where IntelliSense in XAML is working in Rider.

In this keys x:Name components does not generate fields and rider can't generate event handlers

**Comment by kekekeks** [comment]
**\*\*\*important\*\*\***
1) https://youtrack.jetbrains.com/issue/RIDER-39247 - this is the tracking issue for Avalonia support. Go and vote there. That's the only way to get proper avalonia support, we need approximately 100+ votes from their paying customers to get things in motion
2) If you experience issues not listed in that tracking issue, go and file a new one

**Comment by sunmachine** [comment]
@kekekeks I can definitely find at least 10 people. Will need a few days, though.

**Comment by neymecc** [comment]
Finally!

https://www.jetbrains.com/rider/nextversion/

### **"Our biggest news is that we're introducing support for Avalonia! There will be more updates to come, but already there's a lot in there. Rider offers code completion, support for bindings, and quick-fixes to create all sorts of Avalonia properties. The UI previewer is not yet included, but we're working on it. Give the Avalonia support a try, and remember ‐ we'd love to get your feedback on this! "**

**Comment by rstm-sf** [comment]
I think this issue is almost outdated

**Comment by jmacato** [comment]
Yeah i think this is resolved. Closing it now :)
