### ISSUE TITLE
ExtendClientAreaToDecorationsHint breaks winui composition effects

### ISSUE THREAD

**Issue by trympet** [AvaloniaUI/Avalonia#7403]
**Describe the bug**
`DwmExtendFrameIntoClientArea` breaks the winui backdrop effect. This causes Acrylic and Mica backgrounds to turn opaque.
https://github.com/AvaloniaUI/Avalonia/blob/38f726f997b9abfa14b9ea3cfd5c742da0c88fa9/src/Windows/Avalonia.Win32/WindowImpl.cs#L930-L934

**To Reproduce**

1. Create a new MVVM app.
1. Follow the [docs](https://docs.avaloniaui.net/tutorials/music-store-app/creating-a-modern-looking-window) and enable acyrlic on the main window.
1. Ensure`ExtendClientAreaToDecorationsHint="True"` is set on the window.
1. Build and run.
1. Observe an opaque background.
1. Disable ExtendClientAreaToDecorationsHint (e.g. with dev tools) and observe correct behavior.

**Expected behavior**
ExtendClientAreaToDecorationsHint should not break acyrlic.
- If no workarounds are planned, this behavior should be documented.
- The backdrop should fall back to DWM blur if acrylic blur is not available -- [also when composition is enabled](https://github.com/adirh3/Avalonia/blob/d1dea568510f0d00246a9a0a5cb01ef9427e6eca/src/Windows/Avalonia.Win32/WindowImpl.cs#L374).

**Screenshots**
![image](https://user-images.githubusercontent.com/23460729/150357414-b20acb4f-f182-4b98-89f9-07fc6623417a.png)

**Desktop (please complete the following information):**

- OS: Windows 11, 22000.466
- Version: 0.10.11 (fe4197ecd2489a9c8eb7a4f5ee3e72a9d81d0832)

**Additional context**
Not sure if this issue was introduced with Windows 11. If so, perhaps the issue should be forwarded to Microsoft?

Invoking `DwmExtendFrameIntoClientArea` with an empty `MARGINS` resolves the issue.

Related to #6465

**Comment by Founntain** [comment]
Is this issue still beeing worked on? I have the same issue aswell.
Mica effect works fine.
Setting `ExtendClientAreaToDecorationsHint` to `False` makes AcrylicBlur to work setting it to `True` makes the background `White`

OS: Windows 11, 22000.527
Version: Avalonia 0.10.13
