### ISSUE TITLE
TabIndex not working in ItemsControl.DataTemplate by default

### ISSUE THREAD

**Issue by dojo90** [AvaloniaUI/Avalonia#7406]
I have an `ItemsControl` with n-`TextBoxes` which should be accessable by the `Tab`. Actually it is not working. I also tried to give each `TextBox` an own TabIndex (`TabIndex="{Binding TabIndex}"`; 1,2,..). Sadly as you can see in the preview it is not working.

```xaml
<ItemsControl Grid.Row="1" Grid.Column="0" Grid.ColumnSpan="5" Items="{Binding Path=LocalizedTexts}">
  <ItemsControl.ItemTemplate>
    <DataTemplate>
      <Grid>
        <Grid.ColumnDefinitions>
          <ColumnDefinition SharedSizeGroup="A" Width="Auto"/>
          <ColumnDefinition Width="20"/>
          <ColumnDefinition SharedSizeGroup="B" Width="Auto"/>
          <ColumnDefinition Width="20"/>
          <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
        <TextBlock Grid.Column="0" Text="{Binding Locale}" VerticalAlignment="Center"/>
        <TextBlock Grid.Column="2" Text="{Binding OldText}" VerticalAlignment="Center"/>
        <TextBox Grid.Column="4" Text="{Binding Text, Mode=TwoWay}" IsTabStop="True" TabIndex="{Binding TabIndex}"/>
      </Grid>
    </DataTemplate>
  </ItemsControl.ItemTemplate>
</ItemsControl>
```

![Tabindex](https://user-images.githubusercontent.com/17551597/150523204-123c867d-9631-4712-977f-006c5cfa3393.gif)

**Avalonia v0.10.11** on **Windows 10**

**Comment by BAndysc** [comment]
I think it is a feature, not a bug. You need to set `KeyboardNavigation.TabNavigation` property to `Continue` on `ItemsPresenter`.

```
<ItemsControl.Styles>
        <Style Selector="ItemsPresenter">
            <Setter Property="(KeyboardNavigation.TabNavigation)" Value="Continue" />
        </Style>
</ItemsControl.Styles>
```

**Comment by chkr1011** [comment]
I had the same issue in one of my applications and the proposed fix from @BAndysc  works. Now  I wonder if the specified tab navigation should be the default like in WPF. I was very confused that I have to set the value in the first place.

**Comment by dojo90** [comment]
Thanks @BAndysc, your solution brought the desired success. As @chkr1011 already mentioned, I ask myself the same question whether this behaviour should not be implemented by default.

**Comment by maxkatz6** [comment]
Keeping this issue open for changing KeyboardNavigation.TabNavigation default value for list-like controls to match WPF defaults.

**Comment by grokys** [comment]
> Keeping this issue open for changing KeyboardNavigation.TabNavigation default value for list-like controls to match WPF defaults.

I think `KeyboardNavigationMode.Once` for `ItemsControl` is the same for WPF isn't it? See https://stackoverflow.com/questions/1126838/tab-between-list-elements-wpf
