### ISSUE TITLE
Touch input with ScrollViewer regression

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#7410]
**Describe the bug**
When using touch input, interacting with controls within a `ScrollViewer` causes the `ScrollViewer` to jump around and may prevent the touch event from reaching the item. This seems to have regressed between 0.10.10 and 0.10.11 as I can't repro this on 0.10.10

**To Reproduce**
Simple case is just to place a `ListBox` with a bunch of items within a `ScrollViewer` and then attempt to use touch input to select the items. Though you'll need to set `VirtualizationMode` to `None` or even worse things seem to happen and ends with "Control already has a visual parent" exception

A bigger case is to run my FluentAvaloniaSamples app and see that you can't use the NavigationView as the ScrollViewer just scrolls to the bottom.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.11

**Additional context**

**Comment by danielmayost** [comment]
I also had jumps on 0.10.11 and it resolved on 0.10.12.
The problem seems to have been solved.

**Comment by amwx** [comment]
It does seem 0.10.12 has fixed the general issue. Although touch scrolling still breaks the virtualized ListBox for some reason

**Comment by grokys** [comment]
Should now be fixed in 11.0 with the recent changes to virtualization.
