### ISSUE TITLE
BringIntoView not working on newly added control.

### ISSUE THREAD

**Issue by Bil97** [AvaloniaUI/Avalonia#7420]
I am working on a project where a user can add data dynamically. When the content does not fit on screen, The newly added content should come to view. I can't get a way of solving it.
I have tried these three methods:

```C#
textBox.BringIntoView(new Rect(new Size(textBox.Bounds.Width, textBox.Bounds.Height)));
textBox.BringIntoView(Bounds);
textBox.BringIntoView();
```
Each time the content scrolls to the first content.

**To Reproduce**
To reproduce the behavior, check this sample project attatched:

[Bring.zip](https://github.com/AvaloniaUI/Avalonia/files/7921547/Bring.zip)

**Comment by maxkatz6** [comment]
I haven't checked the source code yet, but I guess element wasn't yet added to the visual tree.
You need to wait until AttachedToVisualTree event raises, and call BringIntoView after that

**Comment by Bil97** [comment]
I have tried this but its still not working

```C#
TextBox textBox = new()
{
    Text = $"Hello {_i++}"
};

textBox.AttachedToVisualTree += (s, e) =>
{
    textBox.BringIntoView(new Rect(new Size(textBox.Bounds.Width, textBox.Bounds.Height)));
};
var contentPanel = this.FindControl<Panel>("ContentPanel");
contentPanel.Children.Add(textBox);
```

**Comment by maxkatz6** [comment]
Dispatcher.UIThread.Post(container.ContainerControl.BringIntoView)

**Comment by Bil97** [comment]
Its still not working
I have tried this:
```
Dispatcher.UIThread.Post(textBox.Parent.BringIntoView);
Dispatcher.UIThread.Post(textBox.BringIntoView);

```
Can you modify this and send back a working solution if possible?
[Bring.zip](https://github.com/AvaloniaUI/Avalonia/files/7921868/Bring.zip)

**Comment by maxkatz6** [comment]
Checked your code. Looks fine, although probably you can get more flexibility to use ItemsControl instead of StackPanel there.
About specific problem, dispather priority should be specified, for example "Background":
```
Dispatcher.UIThread.Post(textBox.BringIntoView, DispatcherPriority.Background);
```
Tested with your code and it works.
You need it because at the moment when you just added control to the parent, its sizes and position has not yet calculated, so it can't possibly move it.

**Comment by Bil97** [comment]
Thank you. Its working perfect. I will give the ItemsControl a try.
