### ISSUE TITLE
Add TemplatePartAttribute for Controls

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#7432]
**Is your feature request related to a problem? Please describe.**

Named parts in control templates are not always clear to control authors, designers and other IDE tooling.

**Describe the solution you'd like**

WPF has the TemplatePart attribute used with templated controls. This indicates the named parts of the template, and their type, that are used within code-behind. This information was historically used in designers (Blend) as well as with automated checks to ensure default styles and their templates are complete.

This TemplatePart attribute should be added to avalonia and used for all controls (example from WPF). This should be used for all elements that start with the "PART_" prefix in the name.

```csharp
[TemplatePart(Name="PART_ContentHost", Type=typeof(FrameworkElement))]
public abstract class TextBoxBase
```

 * [Microsoft Docs TemplatePartAttribute ](https://docs.microsoft.com/en-us/dotnet/api/system.windows.templatepartattribute?redirectedfrom=MSDN&view=windowsdesktop-6.0)
 * [Template parts and custom controls (quick tip)](https://www.jeff.wilcox.name/2010/04/template-part-tips/)
 * [WPF TemplateParts](https://paulstovell.com/wpf-part-names/)

**Describe alternatives you've considered**

The alternative is no attribute at all as currently exists.

**Additional context**

Information for PseuodClasses is provided in another attribute. This one should be included as well for completeness.

**Comment by robloo** [comment]
WinUI is now doing something interesting with template parts. Enums are generated for the named parts and then 'magic' strings are removed from code usage. 

First example I saw: https://github.com/microsoft/microsoft-ui-xaml/blob/2a6d2d69c809c141ca7916c9730fd5305487501e/dev/TeachingTip/TeachingTipTemplatePartHelpers.h

**Comment by robloo** [comment]
WPF (MIT License): https://github.com/dotnet/wpf/blob/a71d94d93b4af94061f6cd27c57b1d00efaccaab/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/TemplatePartAttribute.cs

**Comment by maxkatz6** [comment]
I wasn't really thought about code generation, it sounds like a good argument to have this attribute even without support IDE support.
Created issue for that https://github.com/AvaloniaUI/Avalonia.NameGenerator/issues/77
Though there is couple of problems what I see there.

**Comment by robloo** [comment]
> I wasn't really thought about code generation

Neither did I until I noticed what WinUI is doing recently.

**Comment by maxkatz6** [comment]
Created ticket in Rider's YouTrack - https://youtrack.jetbrains.com/issue/RSRP-488276
Though I noticed they did not implemented support for the same attribute in WPF https://youtrack.jetbrains.com/issue/RSRP-330024 .

**Comment by robloo** [comment]
> Though I noticed they did not implemented support for the same attribute in WPF

Well, WPF has been on life support for years now. I can understand they didn't want to invest much. I was already surprised they did full Avalonia support so this has a better chance in my opinion.

Separately, I'll probably add the attributes for all templated controls with a style XAML file next weekend. I imagine I'm going to find naming issues as well (missing PART_ prefix) and we'll have to discuss if a breaking change is worth it. 11.0 is the best time to do this though.
