### ISSUE TITLE
DataGrid.DoubleTapped not fired when using touch

### ISSUE THREAD

**Issue by dojo90** [AvaloniaUI/Avalonia#7439]
**Describe the bug**
Double click with the mouse on a `DataGrid.DataGridRow` works. Double tap with your finger on a touch monitor does **not** work.
```cs
DataGrid.DoubleTapped += (sender, args) =>
{
    // mouse double click works
    // finger double tap does not work
};
```

**To Reproduce**
Create a `DataGrid` (set `IsReadOnly=True`), add some foo stuff to get some rows and double tap with your fingers.

**Expected behavior**
`DataGrid.DoubleTapped` event should be fired when double tap with finger.

**Desktop (please complete the following information):**

```txt
Edition	Windows 10 Pro
Version	21H2
Installiert am	‎06.‎07.‎2021
Betriebssystembuild	19044.1466
Leistung	Windows Feature Experience Pack 120.2212.3920.0
```

- *Avalonia v0.10.11*

**Comment by Takoooooo** [comment]
Should be fixed by this PR.
https://github.com/AvaloniaUI/Avalonia/pull/7213

**Comment by dojo90** [comment]
Ah my mistake! I had seen the issue, but hadn't noticed that it wasn't included in the latest release.
