### ISSUE TITLE
Visual Glitch when creating a window on FullScreen on MacOS

### ISSUE THREAD

**Issue by DavidMendesOS** [AvaloniaUI/Avalonia#7445]
**Describe the bug**
When we create a window while on FullScreen on MacOS there is a visual glitch that makes the new window appear surrounded in a black screen. See attached screenshots.

**To Reproduce**

1. Clone https://github.com/DavidMendesOS/AvaloniaWindowFullScreenGlitch
2. Run the following command to be able to open the app in Mac:
           chmod +x WindowGlitch_Avalonia_0.10.8.app/Contents/MacOS/WindowGlitch
3. Open the app in MacOS
4. Toggle FullScreen 
5. Click the Show Window button

**Expected behavior**
Expected behavior would be the Window being overlayed on top of the original FullScreen Window. See attached image

**Screenshots**
(Ignore the diagonal line - That is an issue with the screenshot and cannot be seen normally)

Bug:
![image](https://user-images.githubusercontent.com/48767678/151337992-c2764238-e2ff-42a9-b156-1b2dbf97fc07.png)

ExpectedBehavior:
![image](https://user-images.githubusercontent.com/48767678/151338496-c1e510ed-7d91-4290-915f-9e8ab8c66905.png)

**Desktop (please complete the following information):**

- OS: [Mac Monterey 12.1]
- Version Avalonia 0.10.8

**Additional context**
Only managed to reproduce after bundling the Mac App. Running it normally via Rider does not exhibit any issues.
I couldn't replicate the same behavior on Avalonia 0.10.7. Only when bumping from 0.10.7 to 0.10.8.

Noteworthy is the fact that it only works on 0.10.7 when setting SystemDecorations has SystemDecorations.BordersOnly.
With the default value for SystemDecorations the bug occurs both on 0.10.7 and 0.10.8.

**Comment by grokys** [comment]
Looks similar to https://github.com/AvaloniaUI/Avalonia/issues/6866 which should have been fixed in 0.10.11.

**Comment by grokys** [comment]
The difference here is that in the repro, the secondary window isn't being opened as a child window. #6867 fixed this for child windows but when a non-child window is opened, it's treated as a new "document" window and so a new fullscreen desktop is created.

Is it intentional that the window is being created as a non-child?

**Comment by grokys** [comment]
Closing this after private discussion - opening the window as a child is the solution.
