### ISSUE TITLE
Shift + PointerWheel does not perform horizontal scrolling on Windows

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#7459]
**Describe the bug**
In many programs out there the user can hold [Shift] while turning the pointer wheel to scroll horizontally. I noticed that Avalonia does not support this right now. IMO this is a common behavior, even if WPF also does not implement this out of the box.

**To Reproduce**

1. Implement a ScrollViewer which can scroll in both directions
2. hold Shift while turning pointer wheel
3. Notice that the scrolling is still vertical

**Expected behavior**
perform horizontal scroll

**Screenshots**
None

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.12

**Additional context**
I have only a windows machine, so I cannot test if this is the same on Linux / Mac etc. 

Possible solutions I have in mind:
- Support this out of the box or 
- Having a property to enable / disable this function or
- using a custom behavior for the ScrollViewer which needs to support this. 

Any feedback is welcome 

@avaloniaui-team if you want, I can do a PR to fix this issue. But first the approach should be clear. 

Have a great weekend 
Tim

**Comment by maxkatz6** [comment]
For additional context, it works on mac. It seems cocoa automatically adjusts wheel events.

**Comment by timunie** [comment]
> For additional context, it works on mac. It seems cocoa automatically adjusts wheel events.

Well then I have to do platform check. Thank you for the info
