### ISSUE TITLE
TextBox navigation bugs

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#746]
Some bugs has been detected with TextBox navigation:
- Invalid navigation on "End" key: last but one caret index instead of last (with TextWrapping).
- Invalid navigation on "Up" and "Down" keys (with TextWrapping).
- End key moves caret on the next line (without TextWrapping). Also see #686.

I prepeared the [video](https://youtu.be/lTYDvhob5SI) for better understanding.

**Comment by grokys** [comment]
This seems now to be fixed.
