### ISSUE TITLE
Incorrect window size compare to WPF and WinForms

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#747]
I set up the Avalonia, WinForms and WPF windows with `width=400` and `height=250`.
But in Avalonia client area have that abovemention measures whereas in WPF and WinForms entire windows have such measures:

![avalonia incorrect window size](https://cloud.githubusercontent.com/assets/1150330/18631226/59062370-7e79-11e6-87b4-f14bfe993447.png)

**Comment by grokys** [comment]
Yes, this is by design: on other operating systems (i.e. X windows) we might not know the size of the window border.
