### ISSUE TITLE
Incorrect Double Click TextBox Selection

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#748]
Avalonia TextBox double click selection completely is not proper. I prepeared a [video](https://youtu.be/y_NOEJQK_n0) with double click selection in different programs (WinForms, WPF, Avalonia, Google Chrome and Notepad++). I like WPF, Chrome and Notepad++ behaviour.

I suggest to select all nearest to cursor characters until not letter or digit.

**Comment by KvanTTT** [comment]
Can we use `gtkMode = true` mode in `PreviousWord` and `NextWord` methods https://github.com/AvaloniaUI/Avalonia/blob/829fed015e006e41e13a714538be70ea939e6d27/src/Avalonia.Controls/TextBox.cs#L498

I checked it and found out that it is what I needed. Such cursor behaviour more expected.

**Comment by grokys** [comment]
Fixed by #763.
