### ISSUE TITLE
VS2022 hot reload feature not available for an Avalonia app

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#7483]
**Describe the bug**
Using the VS2022 [hot reload feature](https://devblogs.microsoft.com/dotnet/introducing-net-hot-reload/) for an Avalonia application does not work as expected. 

**To Reproduce**
1. Create a new Avalonia application using VS 2022.
2. Reference the last 0.10.12 versions of the Avalonia assemblies and .net 6.0 in the csproj 
3. Assign some text to the main window: `this.Content = "Trying hot reload";`
4. Execute the application (F5)
5. Try to change the message.  You see the following errors, and the application is not reloaded.

![image](https://user-images.githubusercontent.com/501613/151713446-d9d294a7-0825-4509-b52e-d0cadeaab62e.png)

And pressing "Edit", the following error appears in the Error list pane:

`CS7038	Failed to emit module 'HotReloadExample': Changing the version of an assembly reference is not allowed during debugging: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' changed version to '2.1.0.0'.
`

**Expected behavior**
The application is hot-reloaded.

**Screenshots**
The following video shows the issue:

https://user-images.githubusercontent.com/501613/151713286-c09d71b1-fcf9-4dd2-b293-183cfbb1347a.mp4

**Desktop**
- Microsoft Visual Studio Community 2022 (64-bit) Version 17.0.5
- Avalonia 0.10.12
- dotnet 6.0

**Comment by timunie** [comment]
fyi, it's the same for rider. 
I think there is already a ticket open for this, see: #5456

**Comment by danipen** [comment]
Ok, I'll follow the conversation in #5456
