### ISSUE TITLE
ComboBox - height changes whether there is selected item or not - 0.10.12

### ISSUE THREAD

**Issue by kuiperzone** [AvaloniaUI/Avalonia#7488]
**Describe the bug**
The height of a ComboBox seems to depend on whether it is empty or whether there is a selected item (even a simple item should as a string). Moreover, with a selected item, the height seems needlessly large and is bigger than other similar controls. See screenshots.

**To Reproduce**

                <ComboBox Grid.Column="0" Grid.Row="1"
                    Name="PreviewCombo"
                    HorizontalAlignment="Stretch"
                    ToolTip.Tip="Color used in preview of windows"
                />

**Expected behavior**
A ComboBox should have a default static height for items (such as string items) whether there is a selected item or not.

NB. Setting the following seems to "fix" this issue:

                    Padding="12 0 0 0"
                    VerticalContentAlignment="Center"

**Screenshots**
If the ComboBox has a selected item, it appears oversized, below:

![image](https://user-images.githubusercontent.com/17156238/151742352-09138483-a029-46b7-a498-923c5dbd1ef3.png)

If the box is initialized without a selected item, note how it is smaller in height.

![image](https://user-images.githubusercontent.com/17156238/151742475-4eac0bcb-0e75-4467-a2d8-33d728a10713.png)

**Desktop (please complete the following information):**

- OS: Fedora
- Version 0.10.12

**Comment by kuiperzone** [comment]
See also https://github.com/AvaloniaUI/Avalonia/issues/7541

**Comment by maxkatz6** [comment]
If it's related, can it be that you have some custom styles that might affect text block from combobox template?

**Comment by kuiperzone** [comment]
Yes. I changed all my TextBlock style selectors as suggested and the problem has gone away. Sorry for any inconvenience.

**Comment by maxkatz6** [comment]
Closing then
