### ISSUE TITLE
Raspberry Pi 3 B Rev 1.2 - Segmentation fault

### ISSUE THREAD

**Issue by mcNets** [AvaloniaUI/Avalonia#7501]
I'm trying to run an Avalonia project on my Raspberry but I always get the same error: **Segmentation fault**.

**Raspberry setup**:

- I burned a SD card with the last Raspbian 32 bit OS.  `(PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)")`
- I updated and upgraded.
- I installed: `sudo apt-get install curl libunwind8 gettext apt-transport-https`

**Using Visual Studio 2022 (17.0.5)**

- I Created a new project using `Avalonia application` template.
- I Changed the target framework: `<TargetFramework>net6.0</TargetFramework>`
- Without any modification I built the linux-arm project: `dotnet publish -r linux-arm -c Release -f net6.0 --self-contained true /p:PublishReadyToRun=true  /p:PublishSingleFile=true`
- I copied the `publish` folder to the Raspberry and granted execution permissions.
- When I try to execute it returns: `Segmentation fault`

**In the Raspberry**

- I installed .Net 6 framework
- I added Avalonia templates: `dotnet new -i Avalonia.Templates`
- I created a new Avalonia project: `dotnet new avalonia.app -o avatest`
- Build the project: `dotnet publish -r linux-arm -c Release -f net6.0 --self-contained true /p:PublishReadyToRun=true  /p:PublishSingleFile=true`
- Granted execution permissions
- When I try to execute it returns: `Segmentation fault`

**Comment by BryanWilkins** [comment]
I also have this issue.  I just upgraded to 0.10.12 as suggested and issue still happens.  Also happens on 0.10.11.  Did NOT happen on 0.10.10.  I verified this by reverting to the .10 version.

**Comment by kekekeks** [comment]
Please, try running with GDB to collect the native backtrace.

**Comment by mcNets** [comment]
@kekekeks  That's what I get:

```
Starting program: /home/pi/Code/AvaTest/bin/Debug/net6.0/linux-arm/AvaTest 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x766e8440 (LWP 2158)]
[New Thread 0x75cff440 (LWP 2159)]
[New Thread 0x752ff440 (LWP 2160)]
[New Thread 0x748ff440 (LWP 2161)]
[New Thread 0x70efe440 (LWP 2162)]
[New Thread 0x6f945440 (LWP 2163)]
[New Thread 0x6eb2d440 (LWP 2164)]

Thread 1 "AvaTest" received signal SIGSEGV, Segmentation fault.
0x6bc7664c in SmcOpenConnection () from /lib/arm-linux-gnueabihf/libSM.so.6

```

**Comment by kekekeks** [comment]
Try adding `.With(new X11PlatformOptions { EnableSessionManagement = false})` to your AppBuilder

CC: @jmacato

**Comment by kekekeks** [comment]
@jmacato check if your code properly handles SMC connection errors, I suspect that it segfault while trying to return us an error.

**Comment by mcNets** [comment]
I've added it to AppBuilder:

```
// Avalonia configuration, don't remove; also used by visual designer.
public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .With(new X11PlatformOptions { EnableSessionManagement = false})
                .LogToTrace();
```

But still getting the same error.

**Comment by ahopper** [comment]
I also see this on a clean Raspberry pi 3 with the latest raspbian 32, I don't see it on a less clean Raspberry pi 4 with an older version of raspbian32.

**Comment by ahopper** [comment]
I think I have got to the bottom of this, need to do a bit more testing but won't have time until after the weekend. If anyone is in a rush smlib.cs needs the signature of SmcOpenConnection changed to something like :-
```
[DllImport(LibSm, CharSet = CharSet.Ansi, CallingConvention = CallingConvention.StdCall)]
        public static extern IntPtr SmcOpenConnection(
            [MarshalAs(UnmanagedType.LPStr)] string networkId,
            IntPtr content,
            int xsmpMajorRev,
            int xsmpMinorRev,
            nuint mask,
            ref SmcCallbacks callbacks,
            [MarshalAs(UnmanagedType.LPStr)] string previousId,
            ref IntPtr clientIdRet,
            int errorLength,
            [Out] byte[] errorStringRet
        );
```

**Comment by mcNets** [comment]
I'll test it later, at home. Thanks

**Comment by mcNets** [comment]
Can I install this package `0.10.999-cibuild0018509-beta`  yet?
