### ISSUE TITLE
Bad Text Antialiasing

### ISSUE THREAD

**Issue by floribe2000** [AvaloniaUI/Avalonia#7504]
**Describe the bug**
The edges of text in text blocks look more blurry than before the last update.

**To Reproduce**
Create a TextBlock control, add any text.
Compare the text in version 0.10.11 or older with the result in version 0.10.12.
The 0.10.12 version looks more blurry.

**Expected behavior**
Text should look the same.

**Screenshots**
These screenshots can show the difference, especially when looking at the text within the box:
Old state (looks better):
![ShipBuilder_old](https://user-images.githubusercontent.com/43866194/152039217-b4789077-baf3-45ee-a604-226f81109706.png)

New state (looks worse):
![ShipBuilder_new](https://user-images.githubusercontent.com/43866194/152039210-032835a8-1eed-435e-8a07-b9176c8d42b8.png)

The difference is not huge but still noticeable, especially on high-dpi monitors.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 0.10.12

**Additional context**
The issue occurs regardless of factors like DPI scaling or resolution. Only tested on a Nvidia GPU.

**Comment by Gillibald** [comment]
Please reference `Install-Package SkiaSharp -Version 2.80.3` directly in your Windows build. Current SkiaSharp preview has disfunction ClearType support.

**Comment by floribe2000** [comment]
Thanks for the solution idea. Unfortunately, this solution does not seem to work because it causes a build error due to conflicting versions.

**Comment by danipen** [comment]
@floribe2000 were you able to workaround this?

**Comment by danipen** [comment]
Is this going to be fixed @Gillibald?

**Comment by Xialtal** [comment]
Also problem exists in version 0.10.21. Text looks more blurred.

**Comment by Gillibald** [comment]
Fixed with Avalonia 11
