### ISSUE TITLE
Feature request: Blur content

### ISSUE THREAD

**Issue by blindmatrix** [AvaloniaUI/Avalonia#7518]
It would be nice to be able to blur content. I'd like to be able to show some sort of overlay which blurs the content beneath it. Currently when I show my "popup"/overlay I also add a border that has the same width and height as the window (or screen, as I'm running this directly on DRM) with a translucent background so the things behind my popup gets dimmed down a bit. It would be amazing it you could blur it instead (or more like blur+dim).

I would probably want to add everything that's supposed to be blurred as children to some component and have my overlays live parallel to that blur-container.

```xml
<UserControl>
	<Grid>
		<BlurContainer BlurRadius="15">
			<RegularApplicationContentComponent />
		</BlurContainer>
		<Grid IsVisible="{Binding IsThisPopupVisible}">
			<APopupComponent />
		</Grid>
	</Grid>
</UserControl>
```

Where BlurContainer.BlurRadius could be animated to allow this to "fade in"

This would require the renderer to extract sub-trees of the scene graph and render them into separate textures and then reapplying them as quads onto the output.

Having BlurRadius="0" (or a separate Enabled="false") could possible skip the separate texture to save on draw calls.

**Describe the solution you'd like**
Like above, or something similar.

**Describe alternatives you've considered**
Being able to provide specific shaders instead, but that would mean cross platform applications might have to provide multiple shaders, or use something like spir-v to transpile them.

*PS. I know this is a tall request ;) I've seen in some issues you're working on a new renderer, so I'm asking anyway*

**Comment by maxkatz6** [comment]
It can ve done now with direct access to skia, if you need. 
https://gist.github.com/kekekeks/ac06098a74fe87d49a9ff9ea37fa67bc

**Comment by kekekeks** [comment]
Implemented via bitmap effects, e. g. `<Grid Effect="blur(5)" ...`
