### ISSUE TITLE
Reactive ToProperty not working

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#753]
I think this may be to do with when scheduler in Avalonia is started... minimal repo

Create a blank application, add a view model, set the viewmodel as the data context for main window.

Add...

```
var input = new Subject<bool>();
            _Updated = input.ToProperty(
                    source: this,
                    property: x => x.Updated);//Now should work

            this.PropertyChanged += (sender, e) =>
            {
                Console.WriteLine(e.PropertyName);
            };



            input.OnNext(true);
            input.OnNext(false);


        }


        private ObservableAsPropertyHelper<bool> _Updated;
        public bool Updated
        {
            get { return _Updated.Value; }
        }
```

Console.WriteLine, never gets called...

**Comment by grokys** [comment]
This doesn't work in WPF either, interesting... Looks like it might be a ReactiveUI bug?

**Comment by jkoritzinsky** [comment]
Is this still a bug since upgrading to current ReactiveUI and switching to their nuget packages?
