### ISSUE TITLE
file save dialog problem

### ISSUE THREAD

**Issue by Nizmas** [AvaloniaUI/Avalonia#7535]
**Describe the bug**
I tried to set Initial directory for save file dialog on llinux, but every time I see only current project directory and full path on file name place

**To Reproduce**
_saveFileDialog = new SaveFileDialog();
_saveFileDialog.InitialDirectory = pathofDirectory;

**Expected behavior**
I expected to see window with directory content... 

**Screenshots**
![Снимок экрана от 2022-02-05 18-50-03](https://user-images.githubusercontent.com/64789614/152644749-9df17513-59bd-43c7-a67d-00f2589d82fa.png)

**Desktop (please complete the following information):**

- OS: Linux Ubuntu 21.10
- Version 0.10.11

**Comment by ClementTsang** [comment]
Also seeing the same issues on Arch Linux 5.17.9, Avalonia 0.10.13.
