### ISSUE TITLE
Enhancement - allow application-wide change to default Fluent fontsize?

### ISSUE THREAD

**Issue by kuiperzone** [AvaloniaUI/Avalonia#7540]
It seems there is no direct way to change the default application font size in the Fluent theme. Setting Window.FontSize does not seem to work for most controls. See linked discussion.

Change - make Fluent controls inherit Window.FontSize?

### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/7539

<div type='discussions-op-text'>

<sup>Originally posted by **kuiperzone** February  5, 2022</sup>
Hi,

I'd like to set an application-wide default font-size. What's the best way to do this?

Currently, this seems to work in the App.axaml:

        <Style Selector=":is(TemplatedControl)">
            <Setter Property="FontSize" Value="{Binding Sizing.AppFontSize}"/>
        </Style>

However, it sets everything and I have difficulty overriding it for certain controls. Is there a better way?</div>

**Comment by robloo** [comment]
A lot of the Fluent styles directly set Font properties including size. These should likely be removed so that they can be properly inherited from the parent/Window.
