### ISSUE TITLE
TextBlock Style Selector seems to match control contents ( 0.10.12)

### ISSUE THREAD

**Issue by kuiperzone** [AvaloniaUI/Avalonia#7541]
I am using Style Selector="TextBlock". It seems that this matches with the contents of other controls, including ComboBox, TextBox and even tooltips. See screenshot.

            <Grid.Styles>
                <Style Selector="TextBlock">
                    <Setter Property="Margin" Value="0 32 0 6"/>
                </Style>
            </Grid.Styles>

            <ComboBox Grid.Column="0" Grid.Row="1"
                Name="PreviewCombo"
                HorizontalAlignment="Stretch"
                ToolTip.Tip="Color used in preview of windows"
            />

**Expected behavior**
Selector should not match the Contents of controls.

![image](https://user-images.githubusercontent.com/17156238/152672758-b2d3cd78-d8cc-4e0e-bb90-c005b58c004d.png)

**Desktop (please complete the following information):**

- OS: Fedora 35
Avalonia: 0.10.12

**Additional context**

**Comment by maxkatz6** [comment]
It's expected. You are using "TextBlock" selector - style system matches it to any text block it can find. All of these controls have text block inside of their template.
You should be very careful with using Style with only control type selector.

In your situation, I believe, you need to use style-classes. Examples can be found [in the docs](https://docs.avaloniaui.net/docs/styling/styles).

**Comment by kuiperzone** [comment]
OK. Thanks for the info.
