### ISSUE TITLE
[BUG] OpenFileDialog: Application crashes when nothing is selected

### ISSUE THREAD

**Issue by Maruhl** [AvaloniaUI/Avalonia#7554]
**To Reproduce**
Use OpenFileDialog and invoke ShowAsync(). Close the Dialog with 'X' or Cancel-Button.

**Expected behavior**
No Exception...

**Screenshots**
Invoking Code:
![grafik](https://user-images.githubusercontent.com/41585619/152826528-86fc359b-659e-43b0-bfa4-d10d4c559fcf.png)

Error:
![grafik](https://user-images.githubusercontent.com/41585619/152826679-ee315c87-7da3-42b3-bbc4-16c035702dcd.png)

- OS: Windows
- Version 10 - 21H2
- Avalonia 0.10.12
- Net 6.0

**Comment by maxkatz6** [comment]
It's internal exception that is handled by avalonia and doesn't fails into the user code.
