### ISSUE TITLE
Avalonia app is locked for quite some time so rebuilds are not possible

### ISSUE THREAD

**Issue by Pyrdacor** [AvaloniaUI/Avalonia#7559]
**Describe the bug**
Running a MVVM avalonia app from VS2022 seems to block the output files for quite a while even though the app isn't running anymore. When I try to build the application again, it can't override the main executable. If have to wait for some minutes to be able to rebuild the application in VS2022 with NET6. The message says "It is locked by system(4)". I tried to kill all processes which might be related without luck. Sometimes it helps to close all designers but not always.

There is no process in the task manager related to the app. It even happens when I am debugging and stop the debugger from VS. So the app is definitely closed.

**To Reproduce**
Build and start a MVVM app. Close the app. Change something and build the app again.

**Expected behavior**
Executable should not be locked if the app isn't running anymore.

**Desktop:**

Windows 7 64 Bit
VS2022 (17.0.5)
NET6

**Comment by kekekeks** [comment]
Does that happen with windows defender and any other AV software disabled?

**Comment by Pyrdacor** [comment]
Unfortunately yes. I can't delete the main executable or rebuild the project even with Windows Defender disabled. No other AV software installed.

**Comment by Pyrdacor** [comment]
Hm it happens with other applications as well so this is most likely some NET6 or VS2022 issue with Win7.
