### ISSUE TITLE
CI Build's NuGet packages not available

### ISSUE THREAD

**Issue by yankun** [AvaloniaUI/Avalonia#7577]
**Describe the bug**
After I get notification that a new CI build is available, it's not showing up in the NuGet source from Avalonia. In fact the last version available is already few days old...

I used this repository source: https://nuget.avaloniaui.net/repository/avalonia-all/index.json

**Comment by Takoooooo** [comment]
it was dead for some time but currently, it works I think, if you want I may re-publish some of your works to the feed in case publish failed before
