### ISSUE TITLE
Splitting a text run causes an argument out of range exception

### ISSUE THREAD

**Issue by YohDeadfall** [AvaloniaUI/Avalonia#7580]
**Describe the bug**

When a text block has not enough space available for splitting its text run, `ShapedTextCharacters.Split` throws an argument out of range exception for `length` which must be greater than zero, but it is in the current case. That zero comes from `TextLineImpl.Collapse` which tries to measure characters for the current run, but `TryMeasureCharacters` there returns zero for `measuredLength`, and therefore, `collapsedLength` is zero too.

**To Reproduce**

In my case the issue is triggered by the tree data grid doing two step measure pass for columns, but the scenario can be simplified just by restricting a text block by 17 pixels in width (comes from `_constraint`) and using any text inside it. In my case the text block uses `"Name"` as the content.

**Expected behavior**

`Split` should correctly handle the parameter and return an empty run first.

**Comment by Gillibald** [comment]
Fixed in master
