### ISSUE TITLE
Child window is not centered when the parent window is minimized

### ISSUE THREAD

**Issue by heldergoncalves92** [AvaloniaUI/Avalonia#7582]
**Describe the bug**
When we show a child window and the parent is minimized, and then we restore the parent window from the minimized state, the child window does not show.

**To Reproduce**
1. Show a window
2. Minimize the window
3. Show a child window with `WindowStartupLocation.CenterOwner`
4. The child window is displayed in the center of the parent window (I can say this because I debugged the Top and Left position values)
5. Restore the parent window from minimized state
6. The child window gets stuck in the original position, and because of that is not visible (In the use case I saw it was something similar to top:-31234 and left:-31234)

To reproduce check this sample app: https://github.com/OS-rafaelduarte/Avalonia_Boilerplate/tree/MinimizedDialogIssue

**Expected behavior**
The child window should be centered when the parent window is restored

**Desktop:**
- OS: Windows (It's fine on macOS)
- Version [Latest]

**Comment by grokys** [comment]
Looking at WPF, what seems to happen here is that when showing a child window to a minimized/maximized parent window, `CenterScreen` is used instead of `CenterOwner: https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs#L3666-L3671
