### ISSUE TITLE
TransformRender property must be set in a Style/Theme at least once for animations to work in an App

### ISSUE THREAD

**Issue by yankun** [AvaloniaUI/Avalonia#7583]
**Describe the bug**
In an Application with a 100% custom Theme, Animations triggered via code (like in the Carousel control) weren't rendered. After the time the Animation should take, Elements "jumped" into the final Position. After a lot of Research we found out that the issue was caused by the lack of setting the RenderTransform Property in a Style of an arbitrary Element to some kind of Transformation, as example ScaleTransform. Doing so, Animations suddenly started working.

In fact you can break Animations on the old "Default Theme" by removing all Transforms on the Expander.xaml, which is actually the only Style in this Theme making use of Transforms.

**To Reproduce**

Create a new Application.
Do not use any Theme delivered with Avalonia.
Copy only minimum required Styles from the Default Theme, like: Window, User Control and Border.
Display a simple Border in the MainWindow.
Animate the Border via code, it will not work.

Enhance the Style of the Border with a Transform like

`<Style Selector="Border">
    <Setter Property="RenderTransform">
      <ScaleTransform ScaleX="1" />
    </Setter>
  </Style>`

And suddenly animations will start working.

**Expected behavior**
Animations should work without the need to set the RenderTransform-Property in a Style file for a Theme.

**Desktop (please complete the following information):**

- OS: Ubuntu Linux and Mac OS

**Comment by kekekeks** [comment]
I believe that should be fixed by https://github.com/AvaloniaUI/Avalonia/pull/11638
