### ISSUE TITLE
avalonia.xplat template cannot be run

### ISSUE THREAD

**Issue by HavenDV** [AvaloniaUI/Avalonia#7584]
**Describe the bug**
https://docs.avaloniaui.net/tutorials/running-in-the-browser
I wanted to test Avalonia WebAssembly, I followed these instructions, I did not change anything in the created template
![image](https://user-images.githubusercontent.com/3002068/153525910-42c585ab-03ae-4e32-a079-ed3704210065.png)

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows/Chrome
- Version 0.10.11

**Additional context**

**Comment by HavenDV** [comment]
The problem is rather trivial - Debug mode doesn't check for `wasm-tools` workload. After installing it everything works.
The most interesting thing is that the Release mode displays the correct message that you need to install the `wasm-tools` workload

**Comment by maxkatz6** [comment]
> The problem is rather trivial - Debug mode doesn't check for wasm-tools workload

It's more a question to the .NET SDK team.

**Comment by HavenDV** [comment]
I think it's just worth noting this in your documentation - https://docs.avaloniaui.net/tutorials/running-in-the-browser

**Comment by maxkatz6** [comment]
Done
