### ISSUE TITLE
Issue with MainWindowViewModel Content Change on Raspberry Pi

### ISSUE THREAD

**Issue by DonaD18** [AvaloniaUI/Avalonia#7600]
**Describe the bug**
When setting the property ViewModelBase Content on the MainWindowViewModel, it seems the change is not always raised to the view, so sometimes the screen seems to freeze.

**To Reproduce**

Create an AvaloniaUI MVVM project using .NET 5.0
Create a property to set the ViewModelBase content within the MainWindowViewModel and bind the MainWindow content to this property.
Allow the user to alter the views content by tapping the screen/pressing a button.
Deploy to a Raspberry pi.
Move between screens using button/touch.

**Expected behavior**
Screen will occasionally freeze as change event fails to be reflected on the view.

**Desktop (please complete the following information):**

- OS: Raspbian Lite (Bullseye) with PIXEL Desktop installed
- Version 5.10.92-v7l+ (I got this running uname -r from CLI)

**Additional context**
It seems that occassionally either the raiseandsetifchanged method fails to raise the change to the view or the set fails. Let me know if any other context is required

Edit:
When debugging on Windows, this issue does not occur. This is only a problem when the application is deployed to the pi device. For reference I am using Visual Studio 2019

**Comment by ahopper** [comment]
A repro project would make this easier to recreate

**Comment by DonaD18** [comment]
Apologies for the late reply... this is an issue I've not been looking at in the last couple weeks. 
I've created a simple project to demonstate this issue. The project is simply a MainWindowViewModel with a content binding and two additional View Models which are being used as the content. Each of these 2 views have a button to swap between the views. 

https://github.com/DonaD18/AvaloniaBugTest

When run on a Raspberry Pi, you should discover an intermittent issue where clicking the button will highlight the button, and will change the view model, however the actual view will not move. This can be confirmed by clicking the button again, as the view will stay the same, showing that the button you are actually interacting with is on the other view. 
 
Let me know if you're able to replicate this on your side. I have tried multiple pis and it seems to be consistent.
