### ISSUE TITLE
Backwards focus navigation doesn't work on Linux

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#7613]
Backwards focus navigation doesn't work on Linux (SHIFT+TAB) but works on Windows.

Version: Avalonia 0.10.12
OS: Garuda Linux (Arch)

**Comment by eumario** [comment]
As of Release of 11.0.6, Shift+Tab navigation is working as intended on Linux platforms.  Could have been fixed either by PR #12751 or #12549 as both have dealt with either the Raw X11 Events for Navigation, or a different Method of handling Key inputs.  Either way, Have tested this on Gnome Arch Linux, with tab, and Shift+Tab working properly in navigating forwards, and backwards through the control order.  Will check on other Desktop WM's when I get a chance.
