### ISSUE TITLE
Inspect (ctrl+shift) doesn't work in Linux

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#7617]
In Windows, you can press F12 to see the DevTools, and then CTRL+SHIFT over a control will select the control in the Tree.

In Linux, you can press F12 to open DevTools. It says at the bottom to press CTRL+SHIFT to inspect, but that doesn't work.

Version: 0.10.12
OS: Garuda Linux (Arch)

**Comment by danipen** [comment]
Reproduced here too.

**Comment by robloo** [comment]
Note that with [#7862 ](https://github.com/AvaloniaUI/Avalonia/pull/7891), you should now be able to use F12 again even after DevTools is open to select the focused control again. This could be a work-around for you.

**Comment by maxkatz6** [comment]
Duplicate of #6673
