### ISSUE TITLE
Toggle Switch Hit-Test bug in Immediate mode

### ISSUE THREAD

**Issue by AndrejBunjac** [AvaloniaUI/Avalonia#7623]
**Describe the bug**
When using Immediate mode rendering - the toggle switch displays some odd behavior. A certain small region to the right does not trigger the IsChecked changed but does trigger the Click. I suspect it has something to do with the fact that the Canvas holding the Ellipses On and Off states shows up as a pointer-over control in Immediate mode and doesn't in Deferred mode (was using the DevTools for this). So whenever I saw that the current pointer-over element was that Canvas the hit-test wasn't working correctly. This does not happen in Deferred mode.

**To Reproduce**

1.  In the Program.cs of Control Catalog replace the line:
                .UsePlatformDetect();
with the following:
                .UsePlatformDetect().With(new Win32PlatformOptions
                {
                    UseDeferredRendering = false
                });

2. Run the application
3. Go to toggle switch page and have any switch in the Checked state.
4. Click on the far left side of the oval.

**Expected behavior**
The switch should still toggle back to unchecked but it doesn't - the click is registered but the checked change isn't.

**Screenshots**
Deferred Mode (correct behavior):
![Deffered Mode Toggle Switch](https://user-images.githubusercontent.com/53874154/154285412-f2016b9f-f684-4a2d-b9e5-06d197c9052c.gif)

Immediate mode (bugged):
![Immediate Mode Hit Test](https://user-images.githubusercontent.com/53874154/154285400-e160bf26-bc48-45ca-9515-d8c592128ebf.gif)

**Comment by robloo** [comment]
This reminded me I needed to file a similar issue encountered during SplitButton development. See #7626 which may be related.

**Comment by timunie** [comment]
UseDeferredRendering is not supported anymore. So I think this issue can be closed. If you encounter similar using latest 11.0 version, let me know how to reproduce.
