### ISSUE TITLE
Infinite loop in CreateTextLines caused by a negative text length on wrapping

### ISSUE THREAD

**Issue by YohDeadfall** [AvaloniaUI/Avalonia#7635]
There's a bug somewhere in Avalonia or HarfBuzzSharp on processing a string using wrapping and center alignment. The string is `A_DefaultEffectsSettings_Medium` and 30 characters long. Everything goes well till `MeasureLength` is invoked for a text run containing `fectsSettings_Medium`, so the range starts at 11 and ends at 30. Paragraph width is 12. Here fun starts:

https://github.com/AvaloniaUI/Avalonia/blob/3138316c0a77342d9fb4a9d79d472726154eaaa3/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs#L361-L380

Initially `lastCluster` is 11 as the range start, but after the first iteration it's 10 because that value is contained by `GlyphCluster`. Looking at the glyph clusters we see the following sequence: `10`, `12`, `13`, and so on till `30`. As you can see `11` is missed here. Therefore, on the next iteration the following line returns `-1`:

https://github.com/AvaloniaUI/Avalonia/blob/3138316c0a77342d9fb4a9d79d472726154eaaa3/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs#L372

**Comment by Gillibald** [comment]
```
    <TextBlock 
        HorizontalAlignment="Center" 
        VerticalAlignment="Center" 
        TextAlignment="Center" 
        Width="50" 
        Text="A_DefaultEffectsSettings_Medium" 
        TextWrapping="Wrap"/>
```
![Screenshot 2022-02-18 064317](https://user-images.githubusercontent.com/5928797/154624896-56a3b845-b11d-40d3-87a2-f257ab92bdc6.png)

I don't get an infinite loop

**Comment by YohDeadfall** [comment]
Will recheck tomorrow, but as far as I remember changes in past months haven't solved the issue. Last time I tried to turn wrapping on where the bug happens two weeks ago.

cc @MarchingCube

**Comment by YohDeadfall** [comment]
Cannot reproduce it, but at the same time I cannot say that it's fixed because text arrangement doesn't work properly.

**Comment by maxkatz6** [comment]
I think @Gillibald will need more details about what's wrong with text arrangement.

**Comment by YohDeadfall** [comment]
We discussed it privately and Benedict said that it can be related to the buggy `ItemsRepeater`. His example without the repeater worked fine, so closing the issue.
