### ISSUE TITLE
GridSplitter does not respect MinHeight of the rows

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#7637]
**Describe the bug**
When set a MinHeight and use a GridSplitter it will not respect that limit but also broke the aligment of the UI

![image](https://user-images.githubusercontent.com/113281/154526275-d5a4253e-ba73-4304-9cee-c346af01f420.png)

https://youtu.be/us7Nrb-GmBQ

**To Reproduce**
```xml
<Grid RowDefenitions="*,Auto,Auto">
   <Grid Grid.Row="0" MinHeight="200" Background="Red"/>
   <GridSplitter Grid.Row="1" ResizeDirection="Rows" ResizeBehavior="PreviousAndNext" Background="White"/>
   <Grid Grid.Row="2" MinHeight="200" Background="Black"/>
</Grid>
```

**Expected behavior**
Splitter to stop when reaching MinHeight/Width of the Row and do not futher resize/move elements

**Desktop (please complete the following information):**

- OS: Windows
- Version: 0.10.12

**Additional context**
This also happens naturally if you resize the main window, auto size and limits are kinda broken and need a serious look in the framework, i'm facing a huge dificulty making complex layouts to fit naturaly and adapt well to any size, it always cut or not having scroll bars.

**Comment by barremob** [comment]
It's the same for columns.
However settings the MinWidth / MinHeight on ColumnDefinitions it works.

```
 <Grid.ColumnDefinitions>
        <ColumnDefinition Width="200" MinWidth="150"></ColumnDefinition>
        <ColumnDefinition Width="6"></ColumnDefinition>
        <ColumnDefinition Width="*"></ColumnDefinition>
        <ColumnDefinition Width="6"></ColumnDefinition>
        <ColumnDefinition Width="200" MinWidth="150"></ColumnDefinition>
      </Grid.ColumnDefinitions>
```

**Comment by sn4k3** [comment]
@barremob that worked for me as well! Thank you!
Only thing is missing now is a `IsVisible` property so we can hide them when not require and that MinHeigth/Width do not show an additional blank space.
