### ISSUE TITLE
CalendarDatePicker - TwoWay binding?

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#7638]
**Is your feature request related to a problem? Please describe.**
I am not sure if this is a bug / a feature request or just by design, so I let you judge.

If you bind to `SelectedDate` you always have to specify that the binding needs to be `TwoWay`, in order to update your ViewModel. I almost always forget to set this, so I end up wondering whats going on until I remember to update my binding. 

`<CalendarDatePicker  SelectedDate="{Binding MyDate, Mode=TwoWay}" />`

**Describe the solution you'd like**
IMO `SelectedDate` should bind `TwoWay` by default

**Describe alternatives you've considered**
Keep it was it is, and just remember it better ^^

**Additional context**
I think in WPF it is also TwoWay. I can send a PR if you find this should be implemented. If not, please close this as by design.

Happy coding
Tim

**Comment by robloo** [comment]
Personally, I think TwoWay binding by default isn't a good idea. Devs need to know to change the default OneWay if they need it. This is just a safety feature to avoid unintentional changes to your view model in my opinion.

**Comment by maxkatz6** [comment]
@robloo but it's CalendarDatePicker. In most scenarios it actually expected to do changes to their view models.

**Comment by robloo** [comment]
Everyone might have their own instinct. Mine is always to default to OneWay. You can argue both sides but there is little point, I just shared my personal opinion. It makes the most sense to follow WPF defaults though so if its TwoWay there, that's fine.

**Comment by timunie** [comment]
@robloo I see this property similar to TextProperty of TextBox which is also TwoWay by default.

**Comment by robloo** [comment]
Sure, a TextBox is basically always editable and has a TextBlock non-editable equivalent. So the usage of a TextBox directly implies TwoWay will be needed so I can see that. A CalendarDatePicker theoretically can be used just to display a date and also has no non-editable equivalent. So whether it is used for editing or just display is ambiguous unlike with text controls. I see both of your viewpoint though.

**Comment by robloo** [comment]
I confirmed you are correct that WPF defaults to TwoWay for all relant properties.

https://github.com/dotnet/wpf/blob/7169fadf191f2348d266b874e7a8da844a21ce98/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DatePicker.cs#L416
