### ISSUE TITLE
DataGrid styles do not update correctly

### ISSUE THREAD

**Issue by affederaffe** [AvaloniaUI/Avalonia#7659]
**Describe the bug**
When switching between fluent themes, DataGrid styles are not updated correctly.

**To Reproduce**
Change fluent themes in the ControlCatalog

**Expected behavior**
Colors and brushes change according to the theme

**Screenshots**
![Screenshot_20220220_192853](https://user-images.githubusercontent.com/68356204/154858086-ec3c6751-e4fe-4e1a-85c9-d0f55eabfc55.png)

**Desktop (please complete the following information):**
- OS: Arch Linux KDE
- Version: 0.10.12

**Additional context**
Brushes and Colors are defined as StaticResources in Avalonia.Controls.DataGrid/Themes/Fluent.xaml, therefore those are not updated when accent colors change. A possible solution I see would be to split them into their own styles like FluentControlResourcesDark and FluentControlResourcesLight.

**Comment by maxkatz6** [comment]
>  A possible solution I see would be to split them into their own styles like FluentControlResourcesDark and FluentControlResourcesLight.

How it will help? It's separated assembly that doesn't know about theme changes. 

It needs theme dictionaries support. Before that you can remove data grid styles and add again as a workaround.

**Comment by sn4k3** [comment]
I think the main problem is that DataGrid is not fully compatible with Fluent DarkMode.
Headers are from LightTheme and hover a header make them all black

![ControlCatalog Desktop_2022-02-24_05-17-43](https://user-images.githubusercontent.com/113281/155462516-d54066eb-c86b-4098-bda2-af030480fe53.png)

**Comment by maxkatz6** [comment]
> I think the main problem is that DataGrid is not fully compatible with Fluent DarkMode.

It's compatible. Problem is only with theme switching. When control was loaded with light theme and then it was switched to the dark. To avoid it you need to exclude and include whole DataGrid styles file after theme changed.

**Comment by 0x90d** [comment]
The only preview I've used is preview 4. In that preview version no workaround was required. In preview 5 I'm experiencing the same / this issue. So I'd guess that something in preview 5 has broken it (again?).
