### ISSUE TITLE
Fluent Checkbox gets Clipped when inside of a MenuItem

### ISSUE THREAD

**Issue by najak3d** [AvaloniaUI/Avalonia#7663]
Here is snapshot from the DesktopControlCatalog "Menu" demo.

Notice how the checkbox's right-side is clipped:

![image](https://user-images.githubusercontent.com/10914515/154876455-2454c399-bf7a-4e42-83c0-df7cdc9c8446.png)

I tried adjusting Margin, Padding, and BorderThickness.    And ONLY setting Margin to -10 finally resolves the clipping, but the checkbox is now touching the left side of the Menu Item, leaving a large gap to the right.    My adjustments to BorderThickness and Padding seemed to have NO EFFECT -- surprisingly.

**Comment by najak3d** [comment]
Inspecting it, shows some of the issue.  The "Bounds of this checkbox is 16 x 32!...  should be more like 32x32.

Setting ClipToBounds = false, resolves the clipping, but seems to be a kludge.   Would be better have the Bounds set correctly in the first place.

![image](https://user-images.githubusercontent.com/10914515/154877007-6cd27ceb-68f2-4c96-b5ae-0174accd1800.png)

**Comment by najak3d** [comment]
Did a little debugging.  For some reason, in this scenario, when it comes time to "Arrange" the Checkbox,  "ArrangeCore()" is called with 'finalRect' size 16x16....  that's too tiny for a checkbox.

![image](https://user-images.githubusercontent.com/10914515/154879602-65d93829-ce2e-4227-9c20-f2f2db351497.png)

**Comment by maxkatz6** [comment]
Because of that at least:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml#L201-L205

Problem with current design that we have to reuse "Icon" property also for checkbox functionality.

**Comment by najak3d** [comment]
What is the appropriate fix here then?

**Comment by najak3d** [comment]
I would think the "expected behavior" should be:
1.  It expands the dimension to fit the ICON, OR
2. At minimum resizes the Icon to fit fully into the assigned dimension.

Why is the **default** behavior of the Arrange() logic to "ignore icon size" and "crop off the pixels that don't fit" ???

**Comment by najak3d** [comment]
Out of interest, where does this Checkbox Icon come from?   I'm not seeing it stored under "Themes.Fluent/Assets", where I would have expected to find it.

**Comment by jp2masa** [comment]
It's a vector image:

https://github.com/AvaloniaUI/Avalonia/blob/7d60054622ccab459b14dd302e8bae3064210346/src/Avalonia.Themes.Fluent/Controls/CheckBox.xaml#L152

**Comment by robloo** [comment]
This definitely needs to be addressed. I have a few ideas:

 1. Make the ContentPresenter use `MinWidth="16"` and `MinHeight="16"`. Without using shared size groups of the Grid item text won't be aligned in all cases though.
 2. Switch to a more standard size for this area... use 32x32 and if an Icon only takes 16x16 thats fine. This along with using MinWidth/MinHeight might be the most robust solution but it's going to change the design a bit (larger menu items).
 3. Add lightweight resources for these dimensions so that it can be re-styled easily when app developers need it.

**Comment by robloo** [comment]
There are more problems here. CheckBox has so many hard-coded sizes and margins it's almost impossible to get it to fit inside a constrained space. This means it has to be customized to make this scenario look good.

If CheckBox has to be customized already... it's probably better just to add new MenuItem types that handle all this internally. Along with RadioBoxes, etc. I think this was mentioned separately some place.
