### ISSUE TITLE
Avalonia WASM - Embed HTML / Blazor Views

### ISSUE THREAD

**Issue by JaggerJo** [AvaloniaUI/Avalonia#7666]
**Is your feature request related to a problem? Please describe.**
Would like to embed an HTML/Blazor View in a Avalonia application running in WASM.

This is needed to (for example) create a camera component because certain browser APIs can only be called from within a user initiated context (which usually means in a button click handler).

**Describe the solution you'd like**
I'd like to embed HTML/Blazor in an Avalonia Application with an HtmlControl or something.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by JaggerJo** [comment]
https://platform.uno/docs/articles/interop/wasm-javascript-1.html

**Comment by maxkatz6** [comment]
Should be possible with NativeControlHost, where platform specific TopLevelImpl should implement ITopLevelImplWithNativeControlHost

**Comment by JaggerJo** [comment]
> Can be possible with NativeControlHost, where platform specific TopLevelImpl should implement ITopLevelImplWithNativeControlHost

I guess ITopLevelImplWithNativeControlHost is not implemented for the WASM host yet?

**Comment by maxkatz6** [comment]
No
