### ISSUE TITLE
Application name is not shown in the gnome top bar

### ISSUE THREAD

**Issue by hhyyrylainen** [AvaloniaUI/Avalonia#7685]
**Describe the bug**
See this image how just the logo (and no name of any kind) is shown when an avalonia app is running on gnome:
![Kuvakaappaus - 2022-02-23 16-58-51](https://user-images.githubusercontent.com/3796411/155346466-6cc4516c-c8ca-4496-96e9-f1f3da265a3a.png)

(top left in the image, to the right of the avalonia icon there should be some kind of name)
I was unable find any info about how to fix that.
I tried grabbing:
```
    <NativeMenu.Menu>
        <NativeMenu />
    </NativeMenu.Menu>
```
from: https://github.com/VitalElement/Xune/blob/main/Xune.Desktop/App.axaml
but that didn't help at all

**To Reproduce**

1. Run commands:
```sh
dotnet new -i Avalonia.Templates
mkdir MyApp
cd MyApp/
dotnet new avalonia.mvvm
dotnet run
```
2. Look at the top left of the screen and notice how the program name is missing

**Expected behavior**
I expected at least something like `MyApp` (which seems to be the executable name generated) to be there, but instead it looks like avalonia tries to use some smarter API to report a different name to gnome but that apparently fails entirely.

If this is a documentation issue rather than a bug, this is still pretty serious (and a pretty big oversight in the templates), and doesn't look very professional at all. The other times I've seen this happen basically have been me messing with a GUI framework and making it accidentally broken.

**Screenshots**
See the first section of this issue

**Desktop (please complete the following information):**

- OS: Linux (Fedora 35)
- Should be the latest templates version (I just ran the avalonia template install command again). Looks like it puts `0.10.12` as the avalonia version in the created MyApp.csproj file

**Additional context**
Problem visible even with the template application.

**Comment by maxkatz6** [comment]
Just for case, have you set Application.Name property?
@kekekeks @jmacato

**Comment by hhyyrylainen** [comment]
If you mean the one in `App.axaml` as an attribute on the first Application XML tag in that file, yes. The template project seems to be missing that, but I have this in another project I'm doing to evaluate avalonia:
```
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="using:GodotPckTool"
             x:Class="GodotPckTool.App"
             Name="GodotPckTool">
```
and that shows the same issue, the name doesn't appear.

**Comment by hhyyrylainen** [comment]
I investigated this and it seems that Avalonia doesn't call `XSetClassHint` which is what sets that text. Experimentally I put some code into `X11Window.SetIcon` to just put a test name on the Window, and a bit surprisingly it actually works:

![Kuvakaappaus - 2022-07-25 16-14-58](https://user-images.githubusercontent.com/3796411/180786365-c717199a-b31e-41f3-aecd-ad3e3967bc1c.png)

Here's the relevant code:
```c#
                var classHint = XAllocClassHint();

                var classHintData = (XClassHint)Marshal.PtrToStructure(classHint, typeof(XClassHint));

                var classTextData = Marshal.StringToHGlobalAnsi("test name");

                classHintData.ResClass = classTextData;
                classHintData.ResName = classTextData;

                Marshal.StructureToPtr(classHintData, classHint, true);

                XSetClassHint(_x11.Display, _handle, classHint);

                XFree(classHint);

                Marshal.FreeHGlobal(classTextData);
```
Note I had to add those class hint function and struct definitions as they didn't seem to exist yet.

I'll try to find the right place and attempt to clean up that code a bit, and then I think I could submit a PR.

**Comment by kekekeks** [comment]
I believe we do set `WM_CLASS` property here - https://github.com/AvaloniaUI/Avalonia/blob/c7c6450004138ca80f1ee668131a83a334726e98/src/Avalonia.X11/X11Window.cs#L1083-L1091

**Comment by hhyyrylainen** [comment]
If I replace my code change with `SetWmClass("test class");` the name stops working.

I based my solution on this StackOverflow answer: https://stackoverflow.com/a/62849688/4371508 which seems to indicate that this special API needs to be used and it is not a normal property that is set like that.

**Comment by hhyyrylainen** [comment]
I think I can figure out the X11Window class changes that will allow setting the application name, but briefly looking at the way the X11 platform etc. is initialized it doesn't look like I can grab `Application.Name` from any convenient place.

**Comment by hhyyrylainen** [comment]
I'll close this as https://github.com/AvaloniaUI/Avalonia/pull/8597 is now merged.
