### ISSUE TITLE
Avalonia.Xaml.Interactions.Core.ChangePropertyAction Bug

### ISSUE THREAD

**Issue by nielsbosma** [AvaloniaUI/Avalonia#7686]
**Describe the bug**

`<ChangePropertyAction TargetObject="{Binding #Foo}" PropertyName="Grid.Row" Value="1" /> `

^ This only works if TargetObject is a Grid. But more than often you want to use the attached Grid. properties on other control types.

I think the problem lies here:

![image](https://user-images.githubusercontent.com/4034492/155364186-6487cdbb-10be-4249-bdf6-64c168347c21.png)

If Foo is a Panel then propertyNames[0]="Grid" and targetType.Name="Panel".

**Desktop (please complete the following information):**

- Windows
- Avalonia 0.10.12

**Comment by wieslawsoltes** [comment]
Should be fixed in 0.10.16, not much more I can do with this action as it uses string for property name, if it still does not work please use ChangeAvaloniaPropertyAction
