### ISSUE TITLE
Button with HOTKEY does not fire "click" event and does not bring a flyout

### ISSUE THREAD

**Issue by jinek** [AvaloniaUI/Avalonia#7695]
Code to reproduce:
```
<Button Content="Basic Flyout" HotKey="F7" Click="Button_OnClick">
            <Button.Flyout>
                <Flyout Placement="Bottom">
                    <Panel Width="100"
                           Height="100">
                        <TextBlock Text="Flyout Content!" />
                    </Panel>
                </Flyout>
            </Button.Flyout>
        </Button>
```
Neither click event is fired nor flyout is shown if F7 is pressed.
Same time any bound command works as expected.

Version 0.10.12
Checked in Windows

**Comment by Symbai** [comment]
No idea about the flyout but why should the (mouse) CLICK event fire when a (keyboard) button was PRESSED? That doesn't sound like an issue to me.

**Comment by workgroupengineering** [comment]
Hotkey only work with command at this moment. See PR #7500

**Comment by jinek** [comment]
> No idea about the flyout but why should the (mouse) CLICK event fire when a (keyboard) button was PRESSED? That doesn't sound like an issue to me.

1) Why do you assume it's "mouse" click?
2) Pressing enter or space raises CLICK event, why hotkey should not?
3) WPF raise CLICK event when hotkey is pressed

**Comment by maxkatz6** [comment]
Works now in master after https://github.com/AvaloniaUI/Avalonia/pull/7500
