### ISSUE TITLE
Status of ProgressRing?

### ISSUE THREAD

**Issue by nlogozzo** [AvaloniaUI/Avalonia#7716]
What's the status of bringing a ProgressRing to Avalonia?
I've seen #6003 and #6792 but there since been closed.
ProgressRing is a fundamental control for Fluent and WinUI controls now a days and it would be great to see it in Avalonia

**Comment by robloo** [comment]
@Splitwirez @Takoooooo

**Comment by robloo** [comment]
Here is an alternate -- different style though.

https://github.com/Deadpikle/AvaloniaProgressRing

**Comment by nlogozzo** [comment]
This is now available: https://github.com/ymg2006/FluentAvalonia.ProgressRing
