### ISSUE TITLE
Can't use Avalonia.Android prerelease version on .NET 6

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [AvaloniaUI/Avalonia#7720]
**Describe the bug**
Can't use preview Avalonia .NET6 Android taget (Avalonia.Android) from repository https://nuget.avaloniaui.net/repository/avalonia-all/index.json.

**To Reproduce**

1. Use this project:  https://github.com/maxkatz6/AvaloniaAndroidTestProject
2. Open in Rider IDE
3. Delete reference of avalonia
4. Go to Nuget and Put this repo https://nuget.avaloniaui.net/repository/avalonia-all/index.json.
5. Install the last version of Avalonia.Android (0.10.999....)
6. That error appears:

Install failed (project: AndroidNet6, package: Avalonia.Android v0.10.999-cibuild0018947-beta) Package restore failed. Rolling back package changes for 'AndroidNet6'. Package Avalonia.Android 0.10.999-cibuild0018947-beta is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Avalonia.Android 0.10.999-cibuild0018947-beta supports: - monoandroid11.0 (MonoAndroid,Version=v11.0) ... on=v6.0) Package Avalonia.Android 0.10.999-cibuild0018947-beta is not compatible with net6.0 (.NETCoreApp,Version=v6.0) / android-x86. Package Avalonia.Android 0.10.999-cibuild0018947-beta supports: - monoandroid11.0 (MonoAndroid,Version=v11.0) - net6.0-android31.0 (.NETCoreApp,Version=v6.0)

**Screenshots**

Error importing library
<img width="960" alt="Error Importing Library" src="https://user-images.githubusercontent.com/18708610/155879171-b0564e9a-d0fa-4f67-917d-254d0c9df0d5.png">

.NET 6 baseline App target Android on Linux
<img width="960" alt="HelloWorld Android App  NET6 Android Target Linux" src="https://user-images.githubusercontent.com/18708610/155879180-d1d0f329-a504-4e94-a3ba-68ee09d8dadd.png">

Avalonia UI Android LIbrary Version
<img width="960" alt="Version Avalonia Android" src="https://user-images.githubusercontent.com/18708610/155879186-cdca8dd2-dfa9-431c-9bf4-6ad764763617.png">

**Desktop (please complete the following information):**

- OS: ArchLinux
- Version: 0.10
- Dotnet SDK: 6.0.200 (Android Workload compiled and installed)

**Comment by maxkatz6** [comment]
Is it Rider EAP? Net6 mobile sdks work poorly on stable Rider.
Can you build the project with command line? 
```
dotnet build -t:Run
```

**Comment by Alexia-AT-Digitecnology** [comment]
I can't import the library because it's incompatible with the system. It needs net6-android31. Who compiled the workload with android 31 when it defaults android 23?

**Comment by Alexia-AT-Digitecnology** [comment]
How do i check if I have monoandroid?

**Comment by maxkatz6** [comment]
I just try to reproduce it with https://github.com/maxkatz6/AvaloniaAndroidTestProject on Windows.
It compiles perfectly fine. But there was a runtime error due newer change in master branch. Fixed test projects to be compatible again.
Both Xamarin Legacy and .NET 6-Android work in Visual Studio Preview and "dotnet build" (only net6).

> Who compiled the workload with android 31 when it defaults android 23?

.NET team. Also, I'm not sure if it's stable yet.
Android workload for Windows works fine.

> How do i check if I have monoandroid?

Do you have Xamarin Legacy SDK installed? Maybe this will help
- https://rider-support.jetbrains.com/hc/en-us/articles/360000557259--Obsolete-How-to-develop-Xamarin-Android-applications-on-Linux-with-Rider
- https://github.com/0xFireball/xamarin-android-linux

> Who compiled the workload with android 31 when it defaults android 23?

"net6.0-android" expands to the "net6.0-android31". If you want to compile your project with older sdk, you can set it explicitly, like "net6.0-android30". 
Avalonia.Android supports down to 21 version (though we might need to set higher value).

**Comment by maxkatz6** [comment]
Great!
