### ISSUE TITLE
ComboBox control does not respond to Microsoft Surface pen

### ISSUE THREAD

**Issue by Maikelsoft** [AvaloniaUI/Avalonia#7728]
**Describe the bug**
The combo box control does not respond to the Microsoft Surface pen.

**To Reproduce**
Create an app with a ComboBox control and run it on a Microsoft Surface computer. Try to change the selection using the pen. The pen is not connected via Bluetooth and Windows is not in tablet mode.

**Expected behavior**
Mouse-over color must be shown when moving the pointer above an item. Tapping an item must select it.

**Desktop:**

- OS: Windows 10

**Comment by maxkatz6** [comment]
Should be fixed with https://github.com/AvaloniaUI/Avalonia/pull/7412

**Comment by Maikelsoft** [comment]
I can now (version 0.10.15) open the ComboBox with the pen, but items cannot be selected by tapping.

**Comment by jp2masa** [comment]
The PR was only merged a few days ago, so it's only available on the [latest nightly builds](https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed).

**Comment by maxkatz6** [comment]
Yes, this one is not an issue anymore with nightly builds. Unfortunately we can't backport wm_pointer as it has breaking changes in api.
