### ISSUE TITLE
Expose X11 platform internals

### ISSUE THREAD

**Issue by ErikApption** [AvaloniaUI/Avalonia#7729]
**Is your feature request related to a problem? Please describe.**
I'm trying to write a xscreensaver using avalonia. This requires to attach the screensaver to the parent window using XReparentWindow. Right now, it is necessary to rewrite all the native calls because AvaloniaX11Platform is not public.

**Describe the solution you'd like**
Make the system platform classes public so that the internals can be accessed for specific purposes. Right now the X11 display in encapsulated in the platform and not accessible by any user - except the internal framework.

**Describe alternatives you've considered**
Alternative is to rewrite your own XLib unsafe class, get the window handle and throw it through the native calls.

**Comment by kekekeks** [comment]
The current policy is that all of platform backend code should not be public since it's not a part of the public API. We are currently considering to hide even more stuff since we have to maintain binary public API compatibility for extended periods of time between major releases.

**Comment by ErikApption** [comment]
> The current policy is that all of platform backend code should not be public since it's not a part of the public API. We are currently considering to hide even more stuff since we have to maintain binary public API compatibility for extended periods of time between major releases.

I hear you - the downside of this approach is that any platform specific extensions cannot rely on any existing Avalonia platform code. This screensaver/child window thing I believe is Linux/X11 specific - how do you see this approached with Avalonia?

**Comment by kekekeks** [comment]
>extensions cannot rely on any existing Avalonia platform code

Yes, that's the price we are paying for binary compatibility. Otherwise we'll have way wider API surface to support and it costs manpower we'd rather use on framework improvements.

WPF is the same, BTW. They don't expose any P/Invoke declarations they are using.

**Comment by jgcodes2020** [comment]
@kekekeks is it possible that you could simply expose _just the display_?

Any X11 app needs the display, and creating a separate X11 connection just to change window properties feels redundant.

**Comment by kekekeks** [comment]
>just the display

_Which_ one? We are already using a separate connection for rendering, because some graphics drivers don't like multithreaded use of a connection.

Also, at some point our X11 event loop could get moved outside of the UI thread, so it won't be safe to touch the display handle.
