### ISSUE TITLE
OpenFileDialog Hangs on Linux

### ISSUE THREAD

**Issue by boematic** [AvaloniaUI/Avalonia#7745]
When using the OpenFileDialog on Ubuntu my application hangs.  No exceptions are thrown or console output.  Same code works on Windows without problems.  Any ideas?

**Comment by boematic** [comment]
Similar behavior except it hangs on Windows now.

**Comment by kekekeks** [comment]
Task returned from `ShowAsync` has to be `await`ed. You can't just use `Task.Wait()` or `Task.Result`. This is by design.

**Comment by boematic** [comment]
Yes, that was the fix.  It now works on both Windows and Linux.  Thanks.
