### ISSUE TITLE
The program cannot be started on Linux , Loongson, Arch

### ISSUE THREAD

**Issue by RunMonkey** [AvaloniaUI/Avalonia#7747]
When I try to start the sample "BindingDemo" on Linux system(CPU:Loongson, instruction set:Arch), there is only an error prompt "segfault". 
Is there any setting that can help me troubleshoot the problem?

ps:this demo can run on Windows,Centos.

**Comment by vabka** [comment]
Can you run any dotnet app on that system?

**Comment by kekekeks** [comment]
>Is there any setting that can help me troubleshoot the problem?

Try running with GDB to collect backtraces.

**Comment by RunMonkey** [comment]
> Can you run any dotnet app on that system? Did you tried to run it in Debug?
Create a default NETCORE application(print hello world) , that can run。
The debug version is running, and there is only one error “segment fault”

**Comment by RunMonkey** [comment]
> > Is there any setting that can help me troubleshoot the problem?
> 
> Try running with GDB to collect backtraces.

 report error from libcoreclr.so，Should I find the runtime provider？
![3](https://user-images.githubusercontent.com/15755247/156865631-f5ca5cce-41e9-4740-b0f0-b4f6895e8280.png)

**Comment by hez2010** [comment]
See https://github.com/dotnet/runtime/issues/59561

**Comment by shushanhf** [comment]
> > > Is there any setting that can help me troubleshoot the problem?
> > 
> > 
> > Try running with GDB to collect backtraces.
> 
> @kekekeks report error from libcoreclr.so，Should I ask runtime developers for help？ ![3](https://user-images.githubusercontent.com/15755247/156865631-f5ca5cce-41e9-4740-b0f0-b4f6895e8280.png)

First, this error is within the version of SDK-LoongArch64-3.1.11 which is not pushed to the upstream.
Second, the root case of this error maybe not the coreclr.

Maybe your LoongArch64's env which not including libskia.so .
I think the best is feedback to the LoongArch64's developers by their server's email for this version of SDK-LoongArch64-3.1.11 .

**Comment by shushanhf** [comment]
> > > Is there any setting that can help me troubleshoot the problem?
> > 
> > 
> > Try running with GDB to collect backtraces.
> 
> @kekekeks report error from libcoreclr.so，Should I ask runtime developers for help？ ![3](https://user-images.githubusercontent.com/15755247/156865631-f5ca5cce-41e9-4740-b0f0-b4f6895e8280.png)

First, this error is within the version of SDK-LoongArch64-3.1.11 which is not pushed to the upstream.
Second, the root case of this error maybe not the coreclr.

Maybe your LoongArch64's env which not including libskia.so .
I think the best is feedback to the LoongArch64's developers by their server's email for this version of SDK-LoongArch64-3.1.11 .

**Comment by shushanhf** [comment]
![Avalonia-BindingDemo-LA64](https://user-images.githubusercontent.com/35673267/165674535-d4c977d3-2a40-48ec-a90a-f891adcb17f6.png)
![Avalonia-BindingDemo-LA64-NET6 0](https://user-images.githubusercontent.com/35673267/165674539-595c195b-d0d6-4ae9-b1cd-17c1cce1f3c8.png)

**Comment by lindexi** [comment]
@RunMonkey and @kekekeks Can this isseus close? And I'm sure it's working on Loongarch right now.
