### ISSUE TITLE
Button.IsCancel still works for detached button + MemoryLeak

### ISSUE THREAD

**Issue by jinek** [AvaloniaUI/Avalonia#7751]
**Describe the bug**
Button.StopListeningForCancel is called only when property IsCancel is set to false and is not called when button is detached from the visual tree.
Additionally that also means that root element holds reference to the button forewer:
```
        private void ListenForCancel(IInputElement root)
        {
            root.AddHandler(KeyDownEvent, RootCancelKeyDown);
        }
```

- Version 0.10.12

**Comment by robloo** [comment]
Note: This issue would also apply for `IsDefault`

I can't speak for the correctness of your solution. However, it should be easy to add the code here from the OnPropertyChanged method here:

https://github.com/AvaloniaUI/Avalonia/blob/d0f3fedbb627c35e6ef69abe3d30a02dcebffdce/src/Avalonia.Controls/Button.cs#L235-L267

**Comment by jinek** [comment]
> Note: This issue would also apply for `IsDefault`
> 
> I can't speak for the correctness of your solution. However, it should be easy to add the code from the OnPropertyChanged method here:
> 
> https://github.com/AvaloniaUI/Avalonia/blob/d0f3fedbb627c35e6ef69abe3d30a02dcebffdce/src/Avalonia.Controls/Button.cs#L235-L267

Now I'm thinking may be that is conceptual issue? May be events automatically should unsubsribe when element is detached?

**Comment by jinek** [comment]
> Note: This issue would also apply for `IsDefault`
> 
> I can't speak for the correctness of your solution. However, it should be easy to add the code from the OnPropertyChanged method here:
> 
> https://github.com/AvaloniaUI/Avalonia/blob/d0f3fedbb627c35e6ef69abe3d30a02dcebffdce/src/Avalonia.Controls/Button.cs#L235-L267

Now I'm thinking may be that is conceptual issue? May be events automatically should unsubsribe when element is detached?

**Comment by robloo** [comment]
We'll need someone from the core team to weigh-in with how things are supposed to work. At first glance, it appears you are correct though and the button should be automatically unsubscribing when adding/removing from the logical tree -- not only when the property value changes. The Command is already handled this way.

Code I would be looking to add to OnAttached/DetachedLogicalTree methods is from the OnPropertyChanged method:

https://github.com/AvaloniaUI/Avalonia/blob/d0f3fedbb627c35e6ef69abe3d30a02dcebffdce/src/Avalonia.Controls/Button.cs#L415-L425

**Comment by maxkatz6** [comment]
Yes. Subscribing and unsubscribing should be done in OnAttached/Detached methods.
We can find it was already done for IsDefault and IsCancel in OnAttachedToVisualTree/OnDetachedFromVisualTree. 
But cleanup is done only for IsDefault, IsCancel was missed. See https://github.com/AvaloniaUI/Avalonia/blame/master/src/Avalonia.Controls/Button.cs#L228-L234

**Comment by maxkatz6** [comment]
Solution is to unsubscribe IsCancel in OnDetachedFromVisualTree method.

**Comment by robloo** [comment]
@maxkatz6 Thanks for confirming. Since I've done some work with Button recently and know my way around this code I'll fix this one. No guarantees on timing but it will be done before 11.0.
