### ISSUE TITLE
DataGrid - Copy cells that are not read-only clears the content

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#7767]
**Describe the bug**
I am on a Windows PC with a German Keyboard-layout. It's common that `[CTRL]+[C]` copies the data into the clipborad without removing the data (Copy, not Cut). cut is `[CTRL] + [X]` in Germany. 

But the DataGrid seems to perform cut instead of copy which is not wanted in my App. 

**To Reproduce**

1. Go to DataGrid-Page in the demo App
2. Click on the editable Tab
3. mark all rows
4. Press `[CTRL]+[C]` 
5. Observe that the text is cleared

**Expected behavior**
Copy doesn't clear the content

**Screenshots**

Before copy: 
![image](https://user-images.githubusercontent.com/47110241/157225532-59e248ff-6601-411b-acca-b21b77600ec4.png)

After copy
![image](https://user-images.githubusercontent.com/47110241/157225566-e3abe57d-2d1c-4d0a-b437-eff12a128ff6.png)

**Desktop (please complete the following information):**

- OS:  Windows
- Latest master

**Additional context**
This does not happy if you set `ClipboardContentBinding`

**Comment by sn4k3** [comment]
This is a old bug: https://github.com/AvaloniaUI/Avalonia/issues/4713
