### ISSUE TITLE
[Bug] Progress bar clipping

### ISSUE THREAD

**Issue by redstonerti** [AvaloniaUI/Avalonia#7785]
Progress bar clipping

Create a progress bar with a border greater than 0, set the current and maximum value to be whatever you want as long as they are the same, and there will be clipping on the right.

![image](https://user-images.githubusercontent.com/48157961/157764593-0fbbf886-fee1-494b-892d-a59f355364e5.png)

Windows 10 build 19044.1526
Avalonia version 0.10.10
.net 6.0

**Comment by ahopper** [comment]
this may well be a bug but why would you ever need a progress bar with the minimum the same as the maximum? Does the clipping occur with normal values?

**Comment by redstonerti** [comment]
> this may well be a bug but why would you ever need a progress bar with the minimum the same as the maximum? Does the clipping occur with normal values?
Sorry, it was really late when writing this. I meant the current value is the same as the maximum, the minimum can be something else e.g. min: 0, max 100, current:100 . I'll edit the original comment.

**Comment by timunie** [comment]
@redstonerti ,

If you want to provide a fix for this on your own, I think a PR would be welcome. If you need assistance I am willing to guide you.

Happy coding
Tim

**Comment by redstonerti** [comment]
> @redstonerti ,
> 
> If you want to provide a fix for this on your own, I think a PR would be welcome. If you need assistance I am willing to guide you.
> 
> Happy coding Tim
@timunie
I'd like to try that, but the thing is I'm very inexperienced when it comes to avalonia. I can barely use it, let alone fix it. I just think it would be more trouble than it's worth for you. Of course, if you are still up to the task, please dm me on discord (Printer#0767).

**Comment by timunie** [comment]
@redstonerti  I am not on discord, but telegram and gitter. Would either one be OK for you?
