### ISSUE TITLE
Support retrieving an Image source from the Window icon

### ISSUE THREAD

**Issue by 0xFireball** [AvaloniaUI/Avalonia#779]
Support retrieving an Image source from the Window icon.

It is currently not possible to use the `WindowIcon` (the `Icon` property of `Window`) as a target for binding to an Image source.

(See https://github.com/AvaloniaUI/Avalonia/issues/776#issuecomment-255551175 for more information)

**Comment by danwalmsley** [comment]
done

**Comment by Flithor** [comment]
Still cannot set or bind to Image.Source from `WindowIcon`.
