### ISSUE TITLE
After drag maximized app, cannot maximize again

### ISSUE THREAD

**Issue by cangosta** [AvaloniaUI/Avalonia#7800]
**Describe the bug**
If we start an app in maximized state, we cannot maximize it again by double clicking the title bar.

**To Reproduce**

1. Clone repo: https://github.com/cangosta/Avalonia_Boilerplate
2. Checkout branch: visual-parent-issue
3. Compile and run the app.
4. You will see a maximized app, drag it a bit to the side
5. Double click the title bar

**Expected behavior**
The app should be maximized again and repositioned in the screen, but is not.

**Desktop (please complete the following information):**

- OS: Mac
- Version 0.10.13

**Comment by TheyCallMeTojo** [comment]
Try ExtendClientAreaToDecorationsHint="False", do you get the same results? I'm on Windows and can not replicate this issue.

**Comment by grokys** [comment]
Should be fixed by https://github.com/AvaloniaUI/Avalonia/pull/7937
