### ISSUE TITLE
IValueConverter throws sporadic 'Call from invalid thread' exception when updating ViewModel Property

### ISSUE THREAD

**Issue by dojo90** [AvaloniaUI/Avalonia#7814]
In general I have the same error as https://github.com/AvaloniaUI/Avalonia/issues/6375

```xaml
<DataTemplate DataType="actors1:ActorCylinderModel">
  <ContentPresenter Content="{CompiledBinding HasError, Converter={x:Static actors2:ActorCylinderModelToMaterialIconConverter.Instance}}" />
</DataTemplate>
```

```cs
public class ActorCylinderModelToMaterialIconConverter : IValueConverter
{
    public static ActorCylinderModelToMaterialIconConverter Instance { get; } = new();
    public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        if (value is bool and true)
            return new MaterialIcon { Kind = MaterialIconKind.AlertOutline, Foreground = Brushes.Red };
        return null;
    }

    public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture) => throw new NotImplementedException();
}
```

The property `HasError` (`bool`) in the viewModel is set by an observable subscription by the task pool schedular. Sporadically, however, the exception `Call from invalid thread` is thrown.

Why is the `IValueConverter.Convert` method sometimes called by the dispatcher and sometimes not?

**v0.10.12**

```
Edition	Windows 10 Pro
Version	21H2
Installiert am	‎06.‎07.‎2021
Betriebssystembuild	19044.1586
Leistung	Windows Feature Experience Pack 120.2212.4170.0
```

**Comment by dojo90** [comment]
I overlooked that there is a discussion (https://github.com/AvaloniaUI/Avalonia/discussions/6376) attached to the existing issue.
However, unlike this issue, I am using the ReactiveUi framework. `AppBuilder.UseReactiveUI()` is set in the `Program.cs`

As kekekeks writes (https://github.com/AvaloniaUI/Avalonia/discussions/6376#discussioncomment-1138124) it is not supported to update the property of the viewModel via a non-ui thread. Is this still up to date?

**Comment by jp2masa** [comment]
> As kekekeks writes ([#6376 (comment)](https://github.com/AvaloniaUI/Avalonia/discussions/6376#discussioncomment-1138124)) it is not supported to update the property of the viewModel via a non-ui thread. Is this still up to date?

I think so. If you want to subscribe to an observable and receive updates on the UI thread you should use `observable.ObserveOn(RxApp.MainThreadScheduler).Subscribe(...)`. More info on the [ReactiveUI - Scheduling docs](https://www.reactiveui.net/docs/handbook/scheduling/).

**Comment by maxkatz6** [comment]
> Is this still up to date?

Yes, and it will be. XAML frameworks visual/logical tree components are single threaded (depending on framework, it can be a thread per window or one global UI thread as it is in Avalonia).

So, answer - always ensure you update your UI components on UI thread. Which means task pool scheduler won't work.
