### ISSUE TITLE
No definition for 'AttachDevTools'

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/Avalonia#7824]
**Describe the bug**
After upgrading nuget packages from 0.9.3 to 0.10.3 I can no longer build the app as VS 2022 throws: `'Window' does not contain a definition for 'AttachDevTools' and no accessible extension method 'AttachDevTools' accepting a first argument of type 'Window' could be found (are you missing a using directive or an assembly reference?)`

I cannot see it has been removed from Avalonia, so what could it be?

**Screenshots**
![image](https://user-images.githubusercontent.com/14368203/158759846-be47edb6-5c1a-479b-8a01-a55c75506e8a.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 0.10.13
- Targeting .NET 6 (previously with Avalonia 0.9 I've targeted .NET Core 3.1)

**Additional context**

**Comment by MarkusKgit** [comment]
Not a bug: https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#devtools

**Comment by jjxtra** [comment]
Added the nuget, still getting the error...

**Comment by bigswede74** [comment]
I am seeing this error even when the Avalonia.Diagnostics package is installed.

'MyView' does not contain a definition for 'AttachDevTools' and the best extension method overload 'DevToolsExtensions.AttachDevTools(TopLevel)' requires a receiver of type 'TopLevel'    \Avalonia.NameGenerator\Avalonia.NameGenerator.AvaloniaNameSourceGenerator\MyView.g.cs

**Comment by maxkatz6** [comment]
@bigswede74 double check if your XAML and C# files are of the same type (or inherit). It's possible that you have defined one as UserControl and another as Window or something like this.

**Comment by bigswede74** [comment]
> @bigswede74 double check if your XAML and C# files are of the same type (or inherit). It's possible that you have defined one as UserControl and another as Window or something like this.

Thanks that worked.
