### ISSUE TITLE
CompiledBindings do not work if the property has the modifier private

### ISSUE THREAD

**Issue by Onebeld** [AvaloniaUI/Avalonia#7835]
**Describe the bug**
The problem is described in the header.

**To Reproduce**

1. Create a window and assign it a DataContext (for example, ViewModel)
2. In ViewModel add a property with type bool and assign it false (be sure to assign the modifier private)
3. In the window add a button and create a CompileBinding for IsEnabeld
4. Run the project and you will see that the button is still active

**Expected behavior**
CompiledBindings work with the modifier private

- Avalonia version 0.10.13

**Comment by maxkatz6** [comment]
Not sure if I understood problem correctly. Because it works as I understand it.
Can you provide an example?

**Comment by Onebeld** [comment]
I have researched this problem in more detail. As it turned out, it is not because of DataContext. Everything is much simpler and funnier. The property has a private modifier, and you need public to work properly. Please explain, is this normal behavior? Please forgive me if I gave wrong information.

**Comment by maxkatz6** [comment]
Yes, you can't access private members from another class in c#. Same in xaml.

**Comment by Onebeld** [comment]
> Yes, you can't access private members from another class in c#. Same in xaml.

Thanks for the explanation! I think I'll close this problem.

**Comment by workgroupengineering** [comment]
I think XAMLIL Build Task should create an exception to report if the problem.
