### ISSUE TITLE
ItemsControl is not arranged properly under some circumstances

### ISSUE THREAD

**Issue by tvass83** [AvaloniaUI/Avalonia#7849]
**Describe the bug**
ItemsControl / ListBox etc. might miss an arrange in certain scenarios, leading to invalid Bounds (e.g. with a Height of 0) and therefore not showing up on the UI.
Issue #2462 might be related.
The same code works as expected in WPF.

**To Reproduce**
Check out the following simple project:
https://github.com/tvass83/AvaloniaIssues/tree/main/InvalidBoundsForItemsControlInAutoGrid

1. Click on 'SubView2' button => note the ItemsControl is displayed properly.
2. Click on 'SubView1' button.
3. Click on 'SubView2' button => ItemsControl is not shown at all. 
4. Check Bounds property for ItemsControl => note Height=0.
5. Resize Window => ItemsControl is displayed properly.

**Expected behavior**
Just like in WPF, ItemsControl shall be properly arranged all the time.

**Desktop (please complete the following information):**
- OS: Windows 10 version 20H2 (OS build 10.0.19042.804)
- Avalonia version: observed in 0.10.6, but still reproducible in 0.10.13.

**Additional context**
This is kind of an evil bug. In complex UIs, it can be really difficult to track down, let alone provide a decent workaround.

**Comment by tvass83** [comment]
@Gillibald @maxkatz6 Any thoughts on this guys?

**Comment by grokys** [comment]
I was hoping that this would be fixed by #9677 but investigating further the problem seems to be at the layout level. When the `ItemsControl` is hidden and re-shown, its `MeasureOverride` is called but then `ArrangeOverride` isn't called to actually arrange it. Needs more investigation.

**Comment by grokys** [comment]
Fixed by #10864.
