### ISSUE TITLE
Cannot write to textbox in a dialog window.

### ISSUE THREAD

**Issue by KeKl** [AvaloniaUI/Avalonia#785]
Hi,

I have a simple window with a TextBox in it.
When I open this window with ShowDialog() I cannot write to the containing TextBox.
When I change the focus to another window and switch back it is possible, so I think
it is a focus bug.

Regards

**Comment by grokys** [comment]
This seems to be a Win32 problem in that the `WM_CHAR` message isn't received. Needs further investigation.
