### ISSUE TITLE
Avalonia listbox very slow (even slower in release mode)

### ISSUE THREAD

**Issue by hheimerd** [AvaloniaUI/Avalonia#7850]
**Briefly**: ListBox lags. When I created the release build, the situation worsened.

**Repo**: https://github.com/hheimerd/Z.Labs/tree/master/ZLabs

**Detail**:
Until recently, I have been using WPF to build Windows applications. Compared to WPF and JS, Avalonia's performance is suspiciously low. I have a ListBox with 15 items (Pages), each item is a VM object rendered with a template.
Scrolling, hover and other animations work with a 0.5-2 second freeze (if you make a Release build, it can freeze for 3-5 seconds). Selecting an item switches the Page (If you make a Release build, it sometimes freezes for 3-8 seconds). There are no complicated calculations, a couple of models created at the beginning and that's it.

**Screenshots**
![image](https://user-images.githubusercontent.com/38163258/159493577-f7b897fa-c25b-4098-b38f-b4058a1ab74b.png)

**Desktop:**

- OS: Windows
- CPU: ryzen 3600
- Version 0.10.13

Thank you in advance! ❤️

**Comment by hheimerd** [comment]
Listbox in View/MainWindow. There are 4 of them

**Comment by hheimerd** [comment]
@ahopper Thank you! Indeed, why

**Comment by hheimerd** [comment]
I just change format from png to jpg and perfrormance became normal.

**Comment by hheimerd** [comment]
I still see a deterioration in performance if I build using Rider "publish to folder" 
- release 
- win-x64
- no self contained

but with dotnet cli all works correctly

**Comment by kekekeks** [comment]
You have 4151x2999 image which occupies 50MB of GPU memory. Alongside with other images It doesn't fit into default Skia GPU cache budget, so it gets evicted and is being reuploaded to GPU memory _on every frame_. Either downscale your image to a reasonable size or increase GPU budget via SkiaOptions.

**Comment by hheimerd** [comment]
@kekekeks Thanks a lot, I forgot that the weight in GPU memory is different. Now everything works correclty everywhere
