### ISSUE TITLE
Changing the Foreground Brush of PathIcon does Nothing

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#7855]
**Describe the bug**

Within Avalonia itself, changing the Foreground color of the `ComboBox`'s DropDownGlyph `PathIcon` in Fluent theme does nothing.

See: https://github.com/AvaloniaUI/Avalonia/pull/7837#discussion_r830514883

 > Strangely this does not work. I can change Data property here just fine but the Foreground property is ignored completely. I can set it to Red here and there will be no effect.
 >
 > If the Foreground is set above in the PathIcon declaration it works fine. If Foreground is set within the template of PathIcon itself it works fine. I can't imagine what priority-type issue is causing the issue here...

This is a big problem in my opinion and I've already seen that it affects `SplitButton` as well. I'm unsure where the issue is and will need someone from the core team to confirm. My guess is the priority of the properties isn't being set correctly for Foreground somehow. I also could be missing something simple...

**To Reproduce**

 1. Go to ComboBox.xaml in the Fluent theme
 2. Modify the "Normal State" as below. The `Foreground` is now set to `Red`
     ```xaml
      <Style Selector="ComboBox /template/ PathIcon#DropDownGlyph">
        <Setter Property="Foreground" Value="Red" />
        <Setter Property="Data" Value="M1939 486L2029 576L1024 1581L19 576L109 486L1024 1401L1939 486Z" />
      </Style>
     ```
 3. Run ControlCatalog. The DropDownGlyph color does not change.
 4. Note that if you modify Data it will be updated just fine.

**Expected behavior**

The color should change.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version: Latest master as of 22-Mar-2022

**Additional context**

**Comment by jmacato** [comment]
@robloo yeah there's something wrong within PathIcon that it doesnt allow propchanges to propagate inside the icons in it. Right now im switching to Image with DrawingImage as source. That one responds to theme changes. but then again we still need to fix PathIcon

**Comment by amwx** [comment]
It's actually a simple fix:
In `FluentControls.xaml`, move the `<StyleInclude>` for PathIcon to the top. The problem is PathIcon declared in `ComboBox` is being overwritten when the actual `PathIcon` file loads - there's a comment in there about `ToolTip` too. Personally I don't like the templated icons thing for reasons I'm not gonna get into here, but that at least with the current styling system, template load order matters

**Comment by robloo** [comment]
Good catch! I was worried that it related to something deeper with the recent local priority commits.

Agree all icons could be redone as we discussed in the past with @maxkatz6. There certainly is a good case to make that these should fully render themselves and not be templated.

**Comment by robloo** [comment]
This fixes ComboBox. SplitButton isn't working still for some reason. Will investigate separately when I have time.

**Comment by amwx** [comment]
> This fixes ComboBox. SplitButton isn't working still for some reason. Will investigate separately when I have time.

IIRC when I was looking at this last night, `SplitButton` had the `:pressed` state on `SplitButton` rather than on the individual buttons within the template as a result of the design changes.

**Comment by alexanderdeman** [comment]
I can confirm this works when directly changing the Fluent theme, but overriding it later doesn't seem to do anything.

I have the most basic MainWindow.axaml:

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaTest.MainWindow"
        Title="AvaloniaTest">
	<StackPanel>
		<ComboBox>
			<ComboBoxItem>Item 1</ComboBoxItem>
			<ComboBoxItem>Item 2</ComboBoxItem>
			<ComboBoxItem>Item 3</ComboBoxItem>
		</ComboBox>
	</StackPanel>
</Window>
```

and App.axaml:

```xml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             x:Class="AvaloniaTest.App">
    <Application.Styles>
        <FluentTheme Mode="Light"/>
	<Style Selector="ComboBox /template/ PathIcon#DropDownGlyph">
		<Setter Property="Foreground" Value="Red" />
	</Style>		
    </Application.Styles>
</Application>
```

Am I missing something?

**Comment by maxkatz6** [comment]
@alexanderdeman are you using stable version? This issue was related to nightly builds only.
In the stable version you do it with different selector, check out default styles:
https://github.com/AvaloniaUI/Avalonia/blob/stable/0.10.x/src/Avalonia.Themes.Fluent/Controls/ComboBox.xaml#L198-L200
```xaml
  <Style Selector="ComboBox /template/ Path#DropDownGlyph">
    <Setter Property="Fill" Value="Red" />
  </Style>
```

**Comment by alexanderdeman** [comment]
My application is using 0.10.15, but the source I was looking at was the master branch which uses a different selector. Your selector works perfectly. Thanks you!
