### ISSUE TITLE
The tray icon's right-click menu does not close when the application is quitting

### ISSUE THREAD

**Issue by user16014368** [AvaloniaUI/Avalonia#7864]
## Describe the bug

_A clear and concise description of what the bug is._

When clicking on the Quit menu entry, in the tray icon's right-click menu, the menu freezes, it doesn't close and the application doesn't quit.

## To Reproduce

_Steps to reproduce the behavior:_

1. **Be under Windows 10**
2. Create a new Avalonia project
3. Add code for the tray icon and its menu
4. Build the project
5. Run the generated application
6. See the tray icon in the system tray
7. Open its menu by right-clicking on it
8. Click on the Quit menu entry and see the icon instantly disappear
9. To actually quit the still running application, you have to click again outside of the menu

**Step 6:** On Windows, this is usually located in the bottom right-hand corner, next to the date and time indicator. To see the application's icon, expanding the icons list may be necessary by clicking the arrow at the very end of the system tray.

**Step 3:**

```
public partial class MainWindow : ReactiveWindow<MainWindowViewModel>
{
    private readonly ICommunicationBus _communicationBus = Locator.Current.GetService<ICommunicationBus>();
    private readonly TrayIcon _trayIcon;

    public MainWindow()
    {
        _trayIcon = new TrayIcon();

        _communicationBus.Listen<Unit>(ComKeys.EXIT_REQUEST)
            .Subscribe(_ => Close());

        AvaloniaXamlLoader.Load(this);

        _trayIcon.Icon = new WindowIcon(AvaloniaLocator.Current.GetService<IAssetLoader>()?.Open(new Uri($"avares://{GetType().Assembly.GetName().Name}/tray.ico")));

        this.Events().Closing.Subscribe(_ =>
        {
            _trayIcon.IsVisible = false;
            _trayIcon.Dispose();
        });

        NativeMenu menu = new();
        NativeMenuItem item = new();

        item.Header = "Quit";
        item.Click += (s, e) =>
        {
            _communicationBus.SendMessage(Unit.Default, ComKeys.EXIT_REQUEST);
        };

        menu.Add(item);

        _trayIcon.Menu = menu;
    }
}
```

## Expected behavior

_A clear and concise description of what you expected to happen._

**The menu is expected to close as soon as step 8 is completed and the application is expected to exit without delay.**

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Note that the application icon is the music note on the left-hand side.**

### After steps 1 to 6

<img width="215" alt="1.png" src="https://user-images.githubusercontent.com/86303424/159756596-8990d60d-5895-4978-b59a-65d6e149a897.png">

### After step 7

<img width="209" alt="2.png" src="https://user-images.githubusercontent.com/86303424/159756614-0ccb1052-b11d-402c-9bd0-92dafa31dad9.png">

### After step 8

<img width="184" alt="3.png" src="https://user-images.githubusercontent.com/86303424/159756615-196783bc-7392-4050-9472-b802d13eea6e.png">

### After step 9, expected after step 8

<img width="184" alt="4.png" src="https://user-images.githubusercontent.com/86303424/159884109-3405d076-d849-4a34-a7b4-441f070e41c8.png">

**Comment by PhantomGamers** [comment]
I ran into this on my end as well and the solution for me was to exit like so:

```cs
exitButton.Click += (s, e) =>
{
    if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime lifetime)
    {
        lifetime.Shutdown();
    }
};
```

Doing this causes the menu to go away right away.
