### ISSUE TITLE
Program.cs(18, 44): [CS1061] 'AppBuilder' does not contain a definition for 'UsePlatformDetect' and no accessible extension method 'UsePlatformDetect'

### ISSUE THREAD

**Issue by bussiere** [AvaloniaUI/Avalonia#7871]
Here is the problem :    

`Program.cs(18, 44): [CS1061] 'AppBuilder' does not contain a definition for 'UsePlatformDetect' and no accessible extension method 'UsePlatformDetect' accepting a first argument of type 'AppBuilder' could be found (are you missing a using directive or an assembly reference?)`

Here is the program : 

```

using System;
using Avalonia;
using Avalonia.ReactiveUI;

namespace AvaloniaCrossPlatformApplication1.Desktop
{
    class Program
    {
        // Initialization code. Don't use any Avalonia, third-party APIs or any
        // SynchronizationContext-reliant code before AppMain is called: things aren't initialized
        // yet and stuff might break.
        [STAThread]
        public static void Main(string[] args) => BuildAvaloniaApp()
            .StartWithClassicDesktopLifetime(args);

        // Avalonia configuration, don't remove; also used by visual designer.
        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>().UsePlatformDetect()
                .LogToDebug()
                .UseReactiveUI();
    }
}
```

My avalonia version is avalonia.0.10.13.nupkg.sha512

i'am using the basic template.

It seems that there is no UsePlatformDetect on Avalonia ...

Any ideas ?

**Comment by kekekeks** [comment]
You need to install Avalonia.Desktop package and target net4xx/netcoreapp*/net5/net6.
