### ISSUE TITLE
ToolTip does not work on SVG

### ISSUE THREAD

**Issue by sebastian2357** [AvaloniaUI/Avalonia#7874]
**Describe the bug**
ToolTip does not work on SVG

**To Reproduce**

1. Put something like the following line:

`<Svg Path="..." ToolTip.Tip="foobar" />`

or

`<Image Source="{SvgImage ...}" ToolTip.Tip="foobar" />`

2. Move pointer over image
3. ToolTip doe not open

**Expected behavior**
The ToolTip will be open as on other controls too.

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10

**Additional context**

Dan Walmsley recommended me this as a workaound:
```
                            <Panel>
                                <Svg ... />
                                <Panel Background="Transparent"
                                       ToolTip.Tip="...." />
                            </Panel>
```

**Comment by Gillibald** [comment]
We don't maintain the SVG control so I don't this is the right place for your issue

**Comment by MarchingCube** [comment]
https://github.com/wieslawsoltes/Svg.Skia is a correct place for this issue.
