### ISSUE TITLE
Avalonia error XAMLIL: Unable to resolve suitable regular or attached property Content

### ISSUE THREAD

**Issue by alex6dj** [AvaloniaUI/Avalonia#7877]
**Describe the bug**
I have a custom `ControlTemplate` to be used in all Pages:

```xml
       <ControlTemplate x:Key="PageTemplate" TargetType="ContentControl">
           <ScrollViewer HorizontalScrollBarVisibility="Disabled"
                         HorizontalAlignment="Stretch"
                         VerticalAlignment="Stretch"
                         VerticalScrollBarVisibility="Auto">
               <ContentControl Margin="18" Content="{TemplateBinding Content}" />
           </ScrollViewer>
       </ControlTemplate>
```

When I set this `ControlTemplate` in the resources of my `MainWindow` it work as espected, but when move his definition to `App.axaml` `Resources` my app fails to build with Error:

2>D:\!Cosas\source\repos\LinkZoneSdk\src\LinkZoneApp\LinkZoneManager\App.axaml(13,27,13,27): Avalonia error XAMLIL: Unable to resolve suitable regular or attached property Content on type Avalonia.Controls:Avalonia.Controls.Control línea 13, posición 27.

This is the way I use this template:

```xml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:controls="clr-namespace:LinkZoneManager.Controls"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="LinkZoneManager.Pages.AboutPage">
    <ContentControl Template="{DynamicResource PageTemplate}" x:Name="PageControl">
        <!--Content-->
    </ContentControl>
</UserControl>
```

**To Reproduce**

**Expected behavior**
I´m new to Avalonia but I think this should work no mather where it is set.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 1903
- Version v0.10.13 - latest stable

**Additional context**

**Comment by timunie** [comment]
I think you are looking for DataTemplate and not ControlTemplate. Please read more about it in the docs https://docs.avaloniaui.net/docs/templates/data-templates

Moreover I highly recommend to make the tutorials which are available in the docs.


Happy coding
Tim

**Comment by alex6dj** [comment]
Hi, thanks for the answer. I will check the link provided, but let make the problem more explicit. Every `Page` view I use in my app start with a `ScrollViewer` with a `Margin="18"` and some other property set, the idea is to have all this in one single part in case I need to change the margin, or add a border. Just want to reuse this template or something similar, this is not really to show a view for some ViewModel or data class, wich is the use of DataTemplates I think.

**Comment by timunie** [comment]
No this Styling.

**Comment by alex6dj** [comment]
> No this Styling.

OK I'll check it out. Thanks for the reply. I close the issue because I think it's not a bug but my lack of knowledge.

**Comment by timunie** [comment]
That is correct. But let me add one last ting: There is also a discussion section here on github for Q/A and there is a telegram channel here: https://t.me/Avalonia . Often you may get answers here. 

Happy coding
Tim

**Comment by alex6dj** [comment]
Yes, thanks again. Im already subscribed to the Telegram channel. Im really new to Avalonia (only 3 days) but think it is amazing. Yet working to understand the styling section. Thank for this great piece of code and for the fast support.

Happy coding :wink:
Alexei
