### ISSUE TITLE
Notification - Hide only if condition is true

### ISSUE THREAD

**Issue by furesoft** [AvaloniaUI/Avalonia#7878]
**Is your feature request related to a problem? Please describe.**
My problem is sometimes I want to display progress notification and the notification is hiding to early. And I don't know how long the action needs to run.

**Describe the solution you'd like**
A Func<bool> to hide after a certain condition is true, not only after time

**Comment by radoslawik** [comment]
It is possible to close the card from your notification control whenever you want

```
if(Parent is NotificationCard card)
{
    card.Close();
}
```
