### ISSUE TITLE
Error while opening a open file dialog in Windows

### ISSUE THREAD

**Issue by cangosta** [AvaloniaUI/Avalonia#7879]
**Describe the bug**

We are having multiple hits of the following error:

System.AggregateException --> System.ComponentModel.Win32Exception: One or more errors occurred. (The parameter is incorrect.)

Avalonia.Win32.SystemDialogImpl+<>c__DisplayClass2_0.Avalonia.Win32.SystemDialogImpl.lambda.<ShowFileDialogAsync>b__VARIABLE()
System.Threading.Tasks.Task`1.InnerInvoke()
System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
XXX.WebViewImplementation.HybridViewImplementationProvider.ShowFileDialog(String title, String initialFolder, String initialFilename, Pair`2[] filters, ITopLevelView topLevelView, Boolean allowMultipleSelection)
XXX.WebViewImplementation.HybridViewImplementationProvider.ShowOpenMultipleFileDialog(String title, String initialFolder, String initialFilename, Pair`2[] filters, ITopLevelView topLevelView)
XXX.Presenter.RuntimeImplementation.lambda.<ShowOpenFileDialog>b__VARIABLE()
prs#aglukxuf.ServiceStudio.Presenter.ITopLevelPresenter.prs#xkxbgklk[bc](Func`1 opd)
XXX.Presenter.RuntimeImplementation.ShowOpenFileDialog(XXX.Presenter.IBaseTopLevelPresenter topLevelPresenter, System.String title, XXX.Runtime/LastUsedFolder lastUsedFolder, System.String initialFilename, XXX.RuntimeCommon.Pair`2<System.String, System.String[]>[] filters, System.Boolean multiple)
XXX.Presenter.RuntimeImplementation.ShowOpenMultipleFileDialog(IBaseTopLevelPresenter topLevelPresenter, String title, LastUsedFolder lastUsedFolder, String initialFilename, FileDialogFilter filter)
XXX.Presenter.Commands.ESpaceCommands.ServerFileOpen.Open(ITopLevelPresenter target)

**To Reproduce**
Could not reproduce

**Desktop (please complete the following information):**

- OS: Windows

**Comment by cangosta** [comment]
Not sure if this is relevant, but we are passing empty string as the initial folder.

**Comment by MarchingCube** [comment]
Which version of Avalonia are you using?

**Comment by timunie** [comment]
@cangosta best thing would be a simple demo App on github which shows your issue.

**Comment by cangosta** [comment]
Hi, I'm using version 0.10.13, but there are also hits in previous versions.

Unfortunately, as stated in the ticket, I could not reproduce it. Can you give me some hints to help reproduce?

**Comment by timunie** [comment]
You could try to do some logging. I personally use Serilog, but any other logger would help as well. 

Also you can wrap your entire program in a big try-catch-statement like this:

```c#
        // In Program.cs

        [STAThread]
        public static void Main(string[] args)
        {
            try
            {
                BuildAvaloniaApp()
                    .StartWithClassicDesktopLifetime(args);
            }
            catch (Exception e)
            {
                Log.Fatal(e, "Something very bad happened");
                throw;
            }
            
            Log.CloseAndFlush();
        }
```

**Comment by maxkatz6** [comment]
It seems they already have this logging, since we can see stacktrace.
These open file dialogs are COM powered, so it is a bit hard to investigate because of interop
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/SystemDialogImpl.cs

I also can assume some input parameters validation might depend on the OS version. @cangosta is it possible to know OS version of these reports?
