### ISSUE TITLE
WriteableBitmap: doesn't display anything on Linux (and I don't know about other platforms)

### ISSUE THREAD

**Issue by maximilien-noal** [AvaloniaUI/Avalonia#7881]
**Describe the bug**

WriteableBitmap doesn't display anything on Linux.
The same code does display an image on Windows.
No platform-specific code is used.

**To Reproduce**

1. Clone this repo: https://github.com/OpenRakis/Spice86
2. Grab a supported DOS game, like Dune or Prince of Persia
3. Run it with the following command line

```bash
Spice86 -e /path/to/executable
```

4. See a black image.

**Expected behavior**

The same image should display on every supported platform.

**Screenshots**

✓ Windows:

![image](https://user-images.githubusercontent.com/1087524/160285194-be90a6e8-3fb8-452c-b2d3-3f9964b6449c.png)

❌ WSL2 (Ubuntu 20.04) and Xubuntu 20.04 (or any other desktop Linux distro):

![image](https://user-images.githubusercontent.com/1087524/160285406-a21b3786-3cb8-4d11-a939-69d1241b9c18.png)

Same result on a desktop PC with a nvidia GPU, and a laptop with a nvidia GPU.

? - Other platforms

I don't have a Mac for example.

**Desktop (please complete the following information):**

- OS: [Ubuntu 20.04]
- Version [0.10.13]

**Additional context**

Here is the code that updates the image, and at the end invalidates the visual on the UI thread (VideoBufferViewModel, view is VideoBufferView.xaml with the associated code-behind file) :

```csharp

public unsafe void Draw(byte[] memory, Rgb[] palette) {
        if (_disposedValue || UIUpdateMethod is null || Bitmap is null) {
            return;
        }
        int size = Width * Height;
        long endAddress = Address + size;

        if (_appClosing == false) {
            using ILockedFramebuffer buf = Bitmap.Lock();
            uint* dst = (uint*)buf.Address;
            switch (buf.Format) {
                case PixelFormat.Rgba8888:
                    for (long i = Address; i < endAddress; i++) {
                        byte colorIndex = memory[i];
                        Rgb pixel = palette[colorIndex];
                        uint rgba = pixel.ToRgba();
                        dst[i - Address] = rgba;
                    }
                    break;
                case PixelFormat.Bgra8888:
                    for (long i = Address; i < endAddress; i++) {
                        byte colorIndex = memory[i];
                        Rgb pixel = palette[colorIndex];
                        uint argb = pixel.ToArgb();
                        dst[i - Address] = argb;
                    }
                    break;
                default:
                    throw new NotImplementedException($"{buf.Format}");
            }
            Dispatcher.UIThread.Post(() => UIUpdateMethod?.Invoke(), DispatcherPriority.MaxValue);
        }
    }

```

Both on Linux and Windows, the case being run is always PixelFormat.Bgra8888.

Using another pixel format (pixel.ToRgba, or pixel.ToBgra) only breaks the Windows use case.

Using random values does display something, so bindings and invalidation are OK.

**Comment by ahopper** [comment]
WriteableBitmap works for me on all platforms so I know the basics work.  You should use RowBytes to get the stride of each line, it is not guaranteed to be the same as Width, but I doubt this causes your problem.  I use AlphaFormat.Premul maybe there is an issue with AlphaFormat.Unpremul.

**Comment by maximilien-noal** [comment]
On another Linux machine, the same code does work:

![image](https://user-images.githubusercontent.com/1087524/160820323-afa3cacf-f1fb-4445-b717-f1dd0306d7ea.png)

So why on too other Linux machine do I get a black image ?

What's the difference in the execution context ?

All Linux and Windows machines so far have a nvidia GPU and the proprietary driver.

> You should use RowBytes to get the stride of each line, it is not guaranteed to be the same as Width, 

Width and Height in the code above comes from the emulator, not WriteableBitmap.
It is used to determine the addresses in emulated memory to show, in order not to show garbage.

> I use AlphaFormat.Premul maybe there is an issue with AlphaFormat.Unpremul.

I tried all combinations I could think of, same results.

Alpha values are set to FF in the uint value.

I don't have a clue, other that *on some Linux machines* it does work.

So this suggests, along with the fact that it always work on Windows, that the error is *not* in user code.

**Comment by ahopper** [comment]
RowBytes should be respected as it is defined by the api, there is no guarantee that the scan lines of the WriteableBitmap are contiguous, it is quite possible that the backend will have RowBytes larger than width, maybe for alignment or other perf reasons, so your pixels could become out of sync.

You could try disabling gpu in app builder to see if that makes any difference.

**Comment by maximilien-noal** [comment]
Neither Image nor WriteableBitmap expose a RowBytes API.

The online documentation doesn't mention it either.

Could you give me an example ?

**Comment by ahopper** [comment]
```
unsafe
  {
      fixed(uint* pPallete = pallete)
      fixed (byte* pBuffer = buffer)
      {
          byte* src = pBuffer;
          uint* pal = pPallete;
          using (var pixels = bm.Lock())
          {
              uint* p0 = (uint*)pixels.Address;
              int stride = pixels.RowBytes / 4;

              for (int y = 0; y < h; y++)
              {
                  uint* p = p0 + y * stride;
                  byte* endp = src + w;
                  while (src < endp)
                  {
                      var val = *src++;
                      *p++ = *(pal+val);
                  }
              }
          }
      }
  }
```

**Comment by maximilien-noal** [comment]
Corrected on my end.

Previously I was able to reproduce this issue with WSL2 and the proprietary nvidia driver.

The issue doesn't manifest itself anymore with this new code:

```csharp

    public unsafe void Draw(byte[] memory, Rgb[] palette) {
        if (_appClosing || _disposedValue || UIUpdateMethod is null || Bitmap is null) {
            return;
        }
        int size = Width * Height;
        long endAddress = Address + size;

        using ILockedFramebuffer pixels = Bitmap.Lock();
        uint* firstPixelAddress = (uint*)pixels.Address;
        int rowBytes = Width;
        long memoryAddress = Address;
        uint* currentRow = firstPixelAddress;
        for(int row = 0; row < Height; row++) {
            uint* startOfLine = currentRow;
            uint* endOfLine = currentRow + Width;
            for(uint* column = startOfLine; column < endOfLine; column++) {
                byte colorIndex = memory[memoryAddress];
                Rgb pixel = palette[colorIndex];
                uint argb = pixel.ToArgb();
                if(pixels.Format == PixelFormat.Rgba8888) {
                    argb = pixel.ToRgba();
                }
                *column = argb;
                memoryAddress++;
            }
            currentRow += rowBytes;
        }
        if (!IsDrawing) {
            IsDrawing = true;
        }
        Dispatcher.UIThread.Post(() => UIUpdateMethod?.Invoke(), DispatcherPriority.MaxValue);
    }

```

it also still works on Windows and on Linux with the nouveau driver for nvidia hardware.

https://github.com/OpenRakis/Spice86/pull/85

Issue closed. Thank you !
