### ISSUE TITLE
Add Loaded/Unloaded Events from WinUI/UWP

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#7908]
**Is your feature request related to a problem? Please describe.**

UWP has the Loaded/Unloaded events which are useful for control authors to connect/disconnect things.

 * [Loaded](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.loaded?view=winrt-22000) : "Occurs when a FrameworkElement has been constructed and added to the object tree, and is ready for interaction."
 * [Unloaded](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.unloaded?view=winrt-22000) : "Occurs when this object is no longer connected to the main object tree."

OnAttachedToVisualTree and OnDetachedFromVisualTree are similar but the sequence these methods/events are called is not the same. OnAttachedToVisualTree is called BEFORE OnApplyTemplate which is a problem if you are connecting events and the like. Therefore, `Loaded` would be invoked just before (or during) the control is first shown to the user -- after both OnApplyTemplate and OnAttachedToVisualTree.

**Describe the solution you'd like**

Add closely equivalent `Loaded`/`Unloaded` events and new `OnLoaded`/`OnUnloaded` methods to `Control`. This will help control authors and apps coming over from WinUI and UWP. It might also simplify some Avalonia controls.

**Describe alternatives you've considered**

**Additional context**

**Comment by amwx** [comment]
Just to add another use case to this: 
For ItemsControls, `Loaded` fires AFTER the Panel and ItemContainerGenerator has run, thus all items are available. In Avalonia, there really is no way currently to know when an `ItemsControl` is truly ready. When I ported `TabView`, they used `Loaded` to do some stuff that relied on having the items in the underlying ListView available which failed in my port because the ICG hadn't run yet in `OnApplyTemplate` or `OnAttachedToVisualTree`. My solution was to listen for the first `Bounds` change notification as that is when the Panel and ICG are created/run and then treat that as `Loaded` and unsub from it after first call, which felt hacky.

**Comment by robloo** [comment]
@amwx This is near the top of my list for next issues to close. I imagine I'll get to it next weekend. Would appreciate a review at that time or even some ideas on good places to raise these events. I'm not very familiar with the control lifecycle in Avalonia at the moment.

**Comment by amwx** [comment]
> @amwx This is near the top of my list for next issues to close. I imagine I'll get to it next weekend. Would appreciate a review at that time or even some ideas on good places to raise these events. I'm not very familiar with the control lifecycle in Avalonia at the moment.

I had a peek at the WPF source and checked a call stack for how this is implemented. Doesn't make a whole lot of sense as its scattered in 10 different places with weirdly named helper classes in typical MS fashion, but it looks like they fire it after the entire layout pass is completed and just before the render pass. The exact details of this are a bit more obscure. 
In Avalonia, it probably could be done in `LayoutManager.ExecuteLayoutPass` as the last step, by keeping track of which elements haven't loaded yet. But, I'm not that familiar with the layout => rendering pipeline other than just generally how it works so one of the core team will probably have better advice.

`Unloaded` is much less of an issue, and I think `DetachedFromVisualTree` does the same thing, and `Unloaded` may not even be needed. Though for parity, it makes sense to include it and can probably be raised at the same time.

**Comment by robloo** [comment]
Here is the code/API I'm planning (some pseudocode).

```csharp
public class Control
{
    public event RoutedEventHandler Loaded;
    public event RoutedEventHandler Unloaded;

    private bool _IsLoaded;

    internal void OnLoadedCore()
    {
        _IsLoaded = true;
        OnLoaded();
    }

    internal void OnUnloadedCore()
    {
        _IsLoaded = false;
        OnUnloaded();
    }

    protected virtual void OnLoaded()
    {
        Loaded?.Invoke(this, RoutedEventArgs);
    }

    protected virtual void OnUnloaded()
    {
        Unloaded?.Invoke(this, RoutedEventArgs);
    }
}
```

**Comment by alexhelms** [comment]
WPF also has the public `IsLoaded` property which I've found useful in the past. Can you also include that property in the implementation?

**Comment by robloo** [comment]
Yes, forgot to add it, but that's what the _IsLoaded field is for. May be a DirectProperty or a CLR property, haven't decided yet and will check WPF.
