### ISSUE TITLE
ScrollViewer containing TreeView sometimes becomes locked out

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#791]
You can reproduce this in Avalon studio:

Open a Solution with lots of projects.

Expand the tree until scrolling is enabled.

Expand the last item in the tree (project)

Then scroll to bottom

Then Collapse the last item and try to scoll up.

Scrolling is broken.

**Comment by danwalmsley** [comment]
You can also reproduce this in the control catalog.

**Comment by grokys** [comment]
Is this still a problem?

**Comment by grokys** [comment]
Closing due to age of issue and lack of activity.
