### ISSUE TITLE
String Interpolation is not using InvariantCulture

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#7944]
**Describe the bug**

I'm creating a bug for this since I've noticed it a few places now. The entire code base using string interpolation needs to be audited and likely fixed in several places. It uses simple string interpolation without taking into account culture.

String interpolation uses string.Format in its implementation which in turn uses CultureInfo.CurrentCulture of the running thread. This changes from system to system. All the places using string interpolation for serialization need to be using the InvariantCulture to ensure there are no differences on different systems with different cultures.

Generally this can be fixed without removing string interpolation entirely, just `.ToString(CultureInfo.InvariantCulture)` (unfortunately a bit verbose) needs to be added instead of using variables directly. Certain types like enum of course won't have an issue but for numerical types this is especially important.

**Comment by grokys** [comment]
Looks like `FormattableString.Invariant($"myFunction({number})")` is the correct solution.

**Comment by robloo** [comment]
Yea, I saw Martin's blob post recommending that a while ago. It might be less verbose in certain situations for sure. I do generally prefer for readability to be specific for each type. I'll definitely take a look at this though and compare the two in more detail.

**Comment by kekekeks** [comment]
![изображение](https://user-images.githubusercontent.com/1067584/162534650-6a25dc4d-1eda-4158-8402-9312f27cd5ee.png)

**Comment by robloo** [comment]
Well, what I had in mind was this:

`return $"{x.ToString(CultureInfo.InvariantCulture)}:{y.ToString(CultureInfo.InvariantCulture)}"`

Agree it is more verbose though and isn't ideal for many parameters.

**Comment by robloo** [comment]
There are 575 occurrences of string interpolation in the source code right now. A lot of these are in logging and exceptions so don't need to change. However, this is a bit too many for me to audit without having a broad knowledge of the code base. I think someone else is going to need to take a look at this.

**Comment by maxkatz6** [comment]
Both ```FormattableString``` and ```{x.ToString(CultureInfo.InvariantCulture)}:{y.ToString(CultureInfo.InvariantCulture)}``` are quite inefficient. Is anybody already familiar with new .NET 6 formatting apis? Is there a solution for us, which possibly can be wrapped into an extension method?

**Comment by robloo** [comment]
This is why I still use string builder in several cases for serialization. With the base libraries still targeting .net standard 2.0 I'm not sure .net 6.0 would help in several cases anyway (not saying there is a solution there either, I don't know).

I find it very strange Microsoft defaults to culture-specific formatting in situations like this and in some of the .IndexOf() type methods. The defaults should be invariant/ordinal in my opinion but that ship has sailed.

**Comment by hez2010** [comment]
@maxkatz6 I think you need to implement your own `StringInterpolationHandler` for this case.

In .NET 6:

```csharp
string Normal (double x, double y)
{
   DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler (1, 2);
   defaultInterpolatedStringHandler.AppendFormatted (x);
   defaultInterpolatedStringHandler.AppendLiteral (":");
   defaultInterpolatedStringHandler.AppendFormatted (y);
   return defaultInterpolatedStringHandler.ToStringAndClear ();
}

string Invariant (double x, double y)
{
   return FormattableString.Invariant (FormattableStringFactory.Create ("{0}:{1}", x, y));
}
```
