### ISSUE TITLE
Switching MainWindow.Content messes up formatting / rendering.

### ISSUE THREAD

**Issue by zezba9000** [AvaloniaUI/Avalonia#795]
When you switch back and forth MainWindow.Content to existing UserControls (already created in memory and once bound) it messes up formatting / rendering.

Here is very simple the repo case: https://www.dropbox.com/s/dj9p0ryuhovvew2/MainWindow_ContentBug.7z?dl=0

**Comment by grokys** [comment]
Hi @zezba9000 I've just tried this out and the problem appears to already be fixed on our CI builds. Please switch to our nightly NuGet feed and update and let me know if that fixes the problem: https://github.com/AvaloniaUI/Avalonia#nuget
