### ISSUE TITLE
Implement NativeMenuItem.IsVisible

### ISSUE THREAD

**Issue by manfromarce** [AvaloniaUI/Avalonia#7952]
**Is your feature request related to a problem? Please describe.**
Changing the visibility of a menu item can be useful in some cases and is currently not available in NativeMenus.

**Describe the solution you'd like**
Implement a NativeMenuItem.IsVisible like on MenuItem.

**Comment by maxkatz6** [comment]
It works if you remove or add elements from the items array. 
But IsVisible property would be helpful.
