### ISSUE TITLE
Infinite loop in ItemsControl.GetNextControl() cause App to hang

### ISSUE THREAD

**Issue by gepa21** [AvaloniaUI/Avalonia#7992]
**Describe the bug**
Infinite loop in ItemsControl.GetNextControl() causes the application to hang.

**To Reproduce**

1. Create an ItemsControl with an ItemTemplate of a Button binding to the context (sample provided)
```
    <ItemsControl Items="{Binding MyItems, Mode=OneWay}">
      <ItemsControl.ItemTemplate>
        <DataTemplate>
          <Button Content="{Binding ., Mode=OneWay}"/>
        </DataTemplate>
      </ItemsControl.ItemTemplate>
    </ItemsControl>
```
2. Run the app
3. Click on a button on the list (to focus it)
4. Press Home/End keys on keyboard

**Expected behavior**
Change focus to proper item.

**Information**
- OS: Windows 10
- Version 0.10.13

**Additional context**
Sample code : [AvaloniaUI_BugRepro.zip](https://github.com/AvaloniaUI/Avalonia/files/8497977/AvaloniaUI_BugRepro.zip)

**Comment by mohdimas** [comment]
we're having the same issue in MacOS Monterey 12.8

**Comment by mohdimas** [comment]
> @mohdimas do you use oneway binding also? remove the oneway stuff on Items and the content.
> 
> Please post stacktrace.


Yes we do use `Mode=OneWay` as well, I'll try to remove the binding mode and see if that fixes it or not.

Stacktrace:
```
ItemsControl.GetNextControl() at /Users/maksim/Library/Application Support/JetBrains/Rider2021.2/resharper-host/SourcesCache/18bac43b1f324cab8e7acc4442be6706d5400/66/ItemsControl.cs:line 495
ItemsControl.OnKeyDown() at /Users/maksim/Library/Application Support/JetBrains/Rider2021.2/resharper-host/SourcesCache/18bac43b1f324cab8e7acc4442be6706d5400/66/ItemsControl.cs:line 308
Subject<(object, RoutedEventArgs)>.OnNext()
EventRoute.RaiseEventImpl()
EventRoute.RaiseEvent()
Interactive.RaiseEvent()
KeyboardDevice.ProcessRawEvent()
InputManager.ProcessInput()
WindowBaseImpl.RawKeyEvent()
WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.RawKeyEvent()
__MicroComIAvnWindowBaseEventsVTable.RawKeyEvent()
[Managed to Native Transition]
__MicroComIAvnPlatformThreadingInterfaceProxy.RunLoop()
PlatformThreadingInterface.RunLoop()
Dispatcher.MainLoop()
ClassicDesktopStyleApplicationLifetime.Start()
ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime<System.__Canon>()
Program.BuildMailbirdApp()
Bootstrapper<App>.Start()
Program.Main()
```

**Comment by timunie** [comment]
@mohdimas in that case I think the issue can be closed now. If you disagree, please let me know.
