### ISSUE TITLE
Selectable TextBlock

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#7995]
**Is your feature request related to a problem? Please describe.**
In modern Apps its common to select some Text from anywhere and copy it to some other app. If there was an easy way to make TextBlock support this it would be really great. 

**Describe the solution you'd like**
Some option to select and copy text from TextBlock

**Describe alternatives you've considered**
Roll my own control, use Behavior or use a read-only TextBox

**Additional context**
This was discussed on Telegram with @Gillibald and @ahopper . The conclusion was it may be a good addition and should be possible with the next Textlayout impl.

**Comment by tristanlabelle** [comment]
@Gillibald , should this be closed with #9245 ?

**Comment by replaysMike** [comment]
For future googlers, the simple answer here is use `SelectableTextBlock`. It's not indicated in the docs that such a thing exists, but it was introduced into the PR with #9245 mentioned above.

**Comment by MarkBrainfire** [comment]
Since 11.0 is released, shouldn't SelectableTextBlock be added to the documentation?

**Comment by timunie** [comment]
@MarkBrainfire opened an issue for docs. If you want to help us out here, your contribution would be welcome.

**Comment by MarkBrainfire** [comment]
Consider it done!
