### ISSUE TITLE
Avalonia.Win32.Interop.Automation is not compatible with trimming and NativeAOT

### ISSUE THREAD

**Issue by hez2010** [AvaloniaUI/Avalonia#8006]
**Describe the bug**
`Avalonia.Win32.Interop.Automation` is not using MicroCom so it's not compatible with trimming

**Expected behavior**
`Avalonia.Win32.Interop.Automation` should use MicroCom so it won't be trimmed by ILLinker (with `/p:TrimmerDefaultAction=Link`).

**Comment by grokys** [comment]
Yeah this is a known problem, unfortunately UIA (the Win32 Automation API) uses just about every COM feature imaginable and MicroCom can't handle this yet.

**Comment by hez2010** [comment]
How about switching to COM source generator once it lands: https://github.com/dotnet/runtime/issues/66674?

**Comment by maxkatz6** [comment]
I wonder if they will actually make it with the .NET 7 release. I don't feel like we will see it in time. 
I also wonder if it can be used with non-windows sdks.

**Comment by hez2010** [comment]
An initial WIP CCW implementation: https://github.com/hez2010/Avalonia/tree/comwrappers
Will push forward later if I get more time to work on this.

**Comment by maxkatz6** [comment]
@hez2010 thanks!
FYI currently Automation isn't a blocker for the NativeAOT or trimming, as it is disabled when dynamic code isn't allowed or COM feature is disabled.
But yes, we need microcom or comwrappers to get all of it work at the same time.

**Comment by hez2010** [comment]
To use COMWrappers, we will have to drop the support for netstandard2.0. Is it okay?

**Comment by maxkatz6** [comment]
@hez2010 no, we can't drop netstandard2.0 support. We still want to support netframework specifically. Including automation. 
But I believe it won't be a huge problem to not use comwrappers for the netstandard, as these targets don't have aggressive trimming nor AOT.
