### ISSUE TITLE
Log to the console for cmd users without opening an extra window for UI users in SingleFile apps.

### ISSUE THREAD

**Issue by LazaroOnline** [AvaloniaUI/Avalonia#8012]
**Problem**
Using `Console.WriteLine("some-text")` doesn't log to the console if you started your app from a console window.

**Expected behaviour**
A desktop application should be able to write to the console window log, to enable the use case of calling an app from the console using command parameters, imagine a calculator application:
- if you double click "calc.exe" it should open the UI (and only the UI, without an extra console window).
- if you open a console prompt and call the app  with parameters like:
`calc.exe -op=sum -args=2,3`
the console should wait for the app to finish and be able to print the result `The sum is 5.` to the console somehow, either with `Console.WriteLine` or some other logging method for this purpose.

This was possible in WPF using dotnet 4.7.
It would be a great way to develop single file apps without having to create a separate calc-cmd.exe application.

> Notice that changing the csproj to use `<OutputType>Exe</OutputType>` is not an option if is going to open a separate console window to the UI users.

> Also note that [this trick](https://www.codegrepper.com/code-examples/csharp/hide+console+window+c%23) of using `[DllImport("kernel32.dll")]` to hide the current console window is not valid if it hides the console window to the user that started the app from the console promt, plus notice that this would only work in windows, ideally it would also work in Mac and Linux.

**Comment by wgraaf** [comment]
Logging to terminal does appear to work on Linux (when app is launched from terminal)

**Comment by kekekeks** [comment]
Please, open an issue in [dotnet/runtime](https://github.com/dotnet/runtime/) or [dotnet/sdk](https://github.com/dotnet/sdk/). Avalonia just provides you with means to show your UI, it does not manage application build and packaging.
