### ISSUE TITLE
AppBuilder not available in Android?

### ISSUE THREAD

**Issue by 0xFireball** [AvaloniaUI/Avalonia#802]
The NuGet package for `Avalonia` on the MonoAndroid framework does not include `Avalonia.DotNetFrameworkRuntime` in the package.
This library is where `AppBuilder` is defined. As a result, I can't use AppBuilder in my code from the NuGet package without building Avalonia from source 🙁

I also noticed that the sample Android projects both reference the `.csproj` for `DotNetFrameworkRuntime` directly.

Thanks!

**Comment by grokys** [comment]
I'm afraid the android and iOS ports aren't working at the moment, as they don't have a maintainer :(

I would like these platforms to be supported but without a full-time maintainer in all likelihood they will be broken until Avalonia stabilizes somewhat.

**Comment by jkoritzinsky** [comment]
This has been fixed

**Comment by 0xFireball** [comment]
Are the Android classes now ready? @jkoritzinsky

**Comment by jkoritzinsky** [comment]
They should be (at least in ci builds). @kekekeks fixed up Android a few days ago. There's still some issues in Android, but it does work much better than before.
