### ISSUE TITLE
Animated GIF support

### ISSUE THREAD

**Issue by SuchByte** [AvaloniaUI/Avalonia#8020]
A option to play animated GIFs on the Image control is still missing in the core of Avalonia. Would be nice to see this feature implemented.

**Comment by Symbai** [comment]
GIFs are outdated, webp is much better. Higher quality on smaller size. It's used on all sites which plays animated images for a good reason. If work is spend it should be on webp.

**Comment by grokys** [comment]
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2481
