### ISSUE TITLE
PART_TextPresenter not found

### ISSUE THREAD

**Issue by Nymu5** [AvaloniaUI/Avalonia#8041]
Using the current build while making a ControlTemplate for a TextBox an issue is showing that PART_TextPresenter could not be found.
In the Avalonia.Controls TextBox.cs the line
`[TemplatePart("PART_TextPresenter", typeof(TextPresenter))]`
is missing in the latest build but already included in current master. Is there any fast way of fixing it?

**Comment by Gillibald** [comment]
Your template is missing a named TextPresenter `PART_TextPresenter`

**Comment by Nymu5** [comment]
Okay, wow... feel really stupid rn. But appreciate your help! Everything's working :)
