### ISSUE TITLE
XAMLC InvalidProgramException at runtime

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#8043]
**Describe the bug**
The XAML compiler generates IL that causes an InvalidProgramException  at runtime if you bind OneWayToSource or TwoWay to a property with the setter = init.

```System.InvalidProgramException: 'Common Language Runtime detected an invalid program.'```

**To Reproduce**
In the view model
```public string Property { get; init; }```

In the view:
```<TextBox Text="{Binding Property}"/>```

Type a character in the TextBox

**Expected behavior**
I would expect this to generate an error at compile time.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.13

**Additional context**

**Comment by maxkatz6** [comment]
Fixed
