### ISSUE TITLE
Custom Fonts Not Working

### ISSUE THREAD

**Issue by CyanCoding** [AvaloniaUI/Avalonia#8054]
**Describe the bug**
On my `Label`, setting the `FontFamily` to a custom file (that isn't installed on my system) gives me the error `System.InvalidOperationException: Could not create glyph typeface for: Segoe MDL2 Assets`.

**To Reproduce**
`<Label FontFamily="/Assets/segMDL2.ttf#Segoe MDL2 Assets" Content="&#xE700;"/>`

My file structure:
`project/Assets/segMDL2.ttf`

You can download the `.ttf` [here](https://aka.ms/SegoeFonts).

**Expected behavior**
I am expecting my font to show up on the Label but the program doesn't launch.

**Desktop (please complete the following information):**

- OS: Linux (Manjaro)

**Comment by robloo** [comment]
I don't see any issues or bugs here. Since the font isn't installed on your system, you will need to reference the .ttf explicitly in XAML and include the .ttf as an AvaloniaResource within your project.

Project file example:
```xml
  <ItemGroup>
    <AvaloniaResource Include="Assets\Fonts\SourceSansPro-Bold.ttf" />
  </ItemGroup>
```

XAML usage example:
```xaml
<Application.Resources>
  <FontFamily x:Key="UIFont">avares://IconManager/Data/FluentUISystem/FluentSystemIcons-Regular.ttf</FontFamily>
</Application.Resources>
```

https://docs.avaloniaui.net/docs/getting-started/assets#including-assets

Note that the above examples are more pseudo-code than something you can copy-paste into your project. We should probably add this example to the docs directly.

Also note that it is against Microsoft's license agreement to use any Segoe Fonts on non-Windows systems. I highly recommend switching to a non-Microsoft alternative if you app is cross-platform:

https://github.com/robloo/SymbolIconManager#pre-built-fonts
https://github.com/robloo/SymbolIconManager/tree/main/Fonts

**Comment by Gillibald** [comment]
`<FontFamily x:Key="SFHeavy">Assets\Fonts\#SF Pro Text</FontFamily>` should also work

**Comment by rprimora-pricer** [comment]
I am trying to get this to work for 2 straight days without luck. I am having issues with Roboto font. This font comes with the following font files:

- Roboto-Black.ttf - Roboto Black
- Roboto-BlackItalic.ttf - Roboto Black
- Roboto-Bold.ttf - Roboto
- Roboto-BoldItalic.ttf - Roboto
- Roboto-Italic.ttf - Roboto
- Roboto-Light.ttf - Roboto Light
- Roboto-LightItalic.ttf - Roboto Light
- Roboto-Medium.ttf - Roboto Medium
- Roboto-MediumItalic.ttf - Roboto Medium
- Roboto-Regular.ttf - Roboto
- Roboto-Thin.ttf - Roboto Thin
- Roboto-ThinItalic.ttf - Roboto Thin

As you can see only some of the files actually belong to Roboto font others have slightly different names. I do not know how Avalonia loads these fonts but I do this:

```axaml
<FontFamily x:Key="UIFont">avares://{MyAssembly}/Assets/Fonts/#Roboto</FontFamily>
```

This allows me to set the font family on the root Window like so:

```axaml
FontFamily="{StaticResource UIFont}"
```

But setting the thin italic on some element has no effect! Particullary, the style is not respected. Weight is.

```axaml
<TextBlock FontWeight="Thin" FontStyle="Italic" Text="Hey!"/>
```

Not until I am very explicit with font family on that particular element like so:
```axaml
<TextBlock FontFamily="Roboto Thin" FontStyle="Italic" Text="Hey!"/>
```

Can someone please explain what is going on with font loading and why these things don't work. Using `FontStyle` and `FontWeight` really beats the purpose if I also have to set `FontFamily`.

**Comment by EvilLord666** [comment]
@rprimora-pricer , i fixed issue with Google fonts loading by setting proper path in font family, consider in my application `App.axaml` i have `x:Class="Wissance.Zerial.Desktop.App"`, therefore i should use `Wissance.Zerial.Desktop` (without .App) as a first part of path to fonts:
```xml
<FontFamily x:Key="RobotoFonts">avares://Wissance.Zerial.Desktop/Assets/Fonts#Roboto</FontFamily>
```

**Comment by rprimora-pricer** [comment]
> @rprimora-pricer , i fixed issue with Google fonts loading by setting proper path in font family, consider in my application `App.axaml` i have `x:Class="Wissance.Zerial.Desktop.App"`, therefore i should use `Wissance.Zerial.Desktop` (without .App) as a first part of path to fonts:
> 
> ```
> <FontFamily x:Key="RobotoFonts">avares://Wissance.Zerial.Desktop/Assets/Fonts#Roboto</FontFamily>
> ```

This is not the issue I am talking about. I can load the fonts it is just that the Italic is not applied on Thin weight.

Also on the matter you are talking about, no one forbids you to change assembly name in the project file. For instance you could change it from **Wissance.Zerial.Desktop** to **wisze** by applying this property in your project property group:

```<AssemblyName>wisze</AssemblzName>```

This would produce an assembly called **wisze.dll/wisze.exe** which would mean that in your assets Uri you would have to use that name instead like so:

`avares://wisze/Assets/Images/myimage.jpeg`

It just so happens that VisualStudio/MSBuild uses your root  namespace as assembly name by default.

Hope I shed some more light on the matter.

**Comment by timunie** [comment]
@rprimora-pricer don't answer closed issues if you are expecting help. Open a new discussion or join us on Telegram

**Comment by Gillibald** [comment]
You are loading 4 font families from one location: `Roboto, Roboto Light, Roboto Medium and Roboto Black`

The font manager tries to load a direct match for the specified combination of `FamilName, Style, Weight, and Stretch`

If it can't find a direct match it tries to find the closest match. And this might fail here.

**Comment by DanielIKKA** [comment]
> You are loading 4 font families from one location: `Roboto, Roboto Light, Roboto Medium and Roboto Black`
> 
> The font manager tries to load a direct match for the specified combination of `FamilName, Style, Weight, and Stretch`
> 
> If it can't find a direct match it tries to find the closest match. And this might fail here.

exactly, you can access ttf metadata on this kind of site https://products.aspose.app/font/metadata/ttf
