### ISSUE TITLE
Update all TemplateParts to Match Convention

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#8057]
**Describe the bug**

Certain controls do not properly name their template parts. These should be renamed to follow convention before the 11.0 release as it is a breaking change for the styles.

This is the breaking-change following PR #7911 and #7994.

Also discussed in #7432 

I will also close this one, just adding to keep track of it.

**Expected behavior**

All template parts should start with the "PART_" prefix as is done in WPF and most controls.

**Screenshots**

N/A

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

**Comment by robloo** [comment]
@Takoooooo @maxkatz6 

I'm waiting on the big styling updates branch to be merged before I do this. However, it still needs to be done before 11.0. If you want, just let me know a good time to open a PR and I can do this quickly.

**Comment by maxkatz6** [comment]
Yes, it should be done after control theme changes, otherwise huge conflicts are unavoidable. 
Also, not really necessary to have this done in first preview versions.

**Comment by robloo** [comment]
Now that all the control theme updates are made, I'm going to go through and update template parts within the next week or so.

**Comment by robloo** [comment]
Adding link to a specific discussion: https://github.com/AvaloniaUI/Avalonia/issues/3538#issuecomment-1141275108

**Comment by robloo** [comment]
Well, I had no visibility on the Preview 1 release date or I would have got this in. However, there is a draft PR now.
