### ISSUE TITLE
Enabling RenderOnlyOnRenderThread with WinUIComposition disabled causes a freeze.

### ISSUE THREAD

**Issue by emmauss** [AvaloniaUI/Avalonia#8062]
**Describe the bug**
Setting DeferredRenderer's `RenderOnlyOnRenderThread` to true while WinUIComposition is disabled on windows will prevent the window from processing any more messages, thus freezing it.

**To Reproduce**

1. Set `UseWindowsUIComposition` option to false.
2. Set `RenderOnlyOnRenderThread` property of the window's renderer to true.
3. Launch the app.

**Expected behavior**
OnPaint messages sent by the window manager will wait till the next render, where it would continue and other window messages can be processed.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 0.10.13

**Additional context**
The `Render(bool forceComposite)` method fails to get a lock after the above issue occurs, prevent rendering from completing. A simple sample demonstrating this can be found here, https://github.com/emmauss/DeferredRendererFreeze .

**Comment by kekekeks** [comment]
DeferredRenderer is removed
