### ISSUE TITLE
Can't focus NumericUpDown

### ISSUE THREAD

**Issue by RivenSkaye** [AvaloniaUI/Avalonia#8069]
**Describe the bug**
`NumericUpDown` elements can not receive focus, but some of its internal children can and should.
Currently when calling `NumericUpDown.Focus()`, nothing happens with regard to visual and keyboard focus.
This seems like a mistake, as one would expect the `TextBox` inside the `NumericUpDown` template to become the focused object, with the caret being put inside of it, possibly selecting the numerical content of the box as well.

**To Reproduce**
- Create a `NumericUpDown` element, either through code behind or XAML
- Grab the element in the code behind, for example on the `LayoutChanged` element of the parent container
- Call `.Focus()` on the element and watch as nothing happens.

**Expected behavior**
The focus and all keyboard input being put onto the `TextBox` inside of the `NumericUpDown` (like how calling `.Focus()` on a `TextBox` works), or the `NumericUpDown` element otherwise becoming focused and taking in user input.

**Desktop (please complete the following information):**

- OS: Windows 10

**Additional context**
I've tried selecting its children elements directly, but I can't seem to access these from the code end of things.

**Comment by RivenSkaye** [comment]
For anyone facing the same issue, with a bit of prodding around, I managed to find a hackjob solution that involves navigating the `VisualTree` starting from the `Parent` and casting the visual element to a `Control`.

```csharp
public static void MyLayoutUpdatedHandler(object? sender, EventArgs? e){
    // The ItemsControl from a template
    var children = ((ItemsControl)sender).Presenter.Panel.LogicalChildren;
    // The panel I use to lay my objects out
    var pnl = (Panel)children[0].Child;
    // The NumericUpDown. This is where the fun begins!
    // For some reason, the VisualChildren Collection is not available on a Control, but it is on an IControl.
    // Could cast the nud to one, I guess, but I need it for other stuff too.
    Control nud = (Control)pnl.Children[^1];
    // It's safe to assume a Parent exists, considering there's always the Window above us
    ((Control)nud.Parent!
        // Grab the NumericUpDown again
        .VisualChildren[^1]
        // Then grab the ButtonSpinner,
        .VisualChildren[0]
        // The Border
        .VisualChildren[0]
        // The Grid
        .VisualChildren[0]
        // The ContentPresenter
        .VisualChildren[0]
        // And finally the TextBox
        .VisualChildren[0]
    ).Focus(); // Focus() on nud should just redirect the call here imo, but it doesn't...
}
```

**Comment by jpmikkers** [comment]
probably the same issue: when clicking a Label with a NumericUpDown as target it does not result in a focused NumericUpDown element.
