### ISSUE TITLE
Use standard Save to Stream pattern in WindowIcon

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#807]
`WindowIcon` currently implements `public Stream Save()`: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/WindowIcon.cs#L34

The standard pattern in .NET seems to be `public void Save(Stream s)` - we should probably follow this.

**Comment by danwalmsley** [comment]
This feature is also broken on Skia backend.
