### ISSUE TITLE
[windows 11] the window property TransparencyLevelHint not working as expected

### ISSUE THREAD

**Issue by seishinkouki** [AvaloniaUI/Avalonia#8073]
**Describe the bug**
the window property TransparencyLevelHint not working as expected

**To Reproduce**
sample new application on windows 11
my axaml:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication2.MainWindow"
        Title="AvaloniaApplication2"
        Background="Transparent"
        TransparencyLevelHint="AcrylicBlur"
        ExtendClientAreaToDecorationsHint="True">
  <TextBlock HorizontalAlignment="Center" VerticalAlignment="Center" Text="test"></TextBlock>
</Window>
```

**Expected behavior**
see Screenshots.

**Screenshots**
when set TransparencyLevelHint to AcrylicBlur
![image](https://user-images.githubusercontent.com/8842321/166624492-50c5551f-d800-4861-b0b3-8159571a929f.png)
when set TransparencyLevelHint to Mica
![image](https://user-images.githubusercontent.com/8842321/166624537-3bfcb593-4589-45d9-8685-2336aa8dc8b8.png)
when set TransparencyLevelHint to Blur
![image](https://user-images.githubusercontent.com/8842321/166624567-7133efda-57f6-4584-8069-68134777245d.png)

**Desktop (please complete the following information):**

- OS: windows 11 [21H2 22000.613]
- Version [0.10.12]

**Additional context**
newer to Avalonia, am i missing something

**Comment by PowerBall253** [comment]
This has been fixed already (see [this issue](https://github.com/AvaloniaUI/Avalonia/issues/6465)), but it hasn't been released yet. You can try using the nightly build.

**Comment by seishinkouki** [comment]
got it, thanks
