### ISSUE TITLE
Skia Backend FormattedText SetForegroundColor doesnt work when length = 1

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#809]

**Comment by danwalmsley** [comment]
Still an issue, it actually seems to always colour a segment of length n-1.

So there is obviously  just a simple >= instead of > or something like that somewhere.

I can fix it be passing in length +1.

**Comment by jkoritzinsky** [comment]
Looks like the issue is here:
https://github.com/AvaloniaUI/Avalonia/blob/c3e36e93393375fec26a80aed047d701f6cc721f/src/Skia/Avalonia.Skia/FormattedTextImpl.cs#L644

**Comment by danwalmsley** [comment]
@jkoritzinsky nice one, will have a look
