### ISSUE TITLE
IAssetLoader.Open(Uri) not working on Windows

### ISSUE THREAD

**Issue by duck-dev** [AvaloniaUI/Avalonia#8096]
**Describe the bug**
Recently I noticed that a specific view couldn't get displayed on my **Windows build**, but it worked perfectly fine on a Linux build. After hours of experimenting and publishing/building the application over and over again, I tracked down the issue to the second line in this example:
```cs
var assets = AvaloniaLocator.Current.GetService<IAssetLoader>();
var asset = assets?.Open(uri); // As soon as this is included, the view can't get displayed
```

`IAssetLoader.Open(Uri)` doesn't function properly **on Windows** (**built on Linux**, targeting Windows). Instead of returning `null`, which would be totally okay, it just prevents/blocks the entire view from getting displayed, as it's used in a class whose instances should be listed in a `UserControl` in this view. I can click my button that assigns the view's ViewModel instance to a property that is being bound to for the displayed content in the window as often as I want, nothing will happen, whereas I expect a different `UserControl` to be displayed (which works perfectly fine on Linux). 
I was able to exclude any other sources that could possibly influence this, so I'm quite certain this must be it. The path is correct, nothing else could interfere with that... the exact same code and project works on Linux.

**To Reproduce**

1. Have a view that should get displayed at some point, containing a `UserControl` that lists instances of a specific class, which contains the problematic code. Here is a really quick example that should be representative or at least help you to understand the issue a bit better:
```xml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:viewModels="clr-namespace:Project.ViewModels"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="Project.Views.ExampleView">

    <UserControl.DataContext>
        <viewModels:ExampleViewModel/>
    </UserControl.DataContext>
    
    <ItemsControl Items="{Binding SomeCollection}">
            <ItemsControl.ItemsPanel>
                <ItemsPanelTemplate>
                    <StackPanel Orientation="Vertical"/>
                </ItemsPanelTemplate>
            </ItemsControl.ItemsPanel>
            <ItemsControl.ItemTemplate>
                <DataTemplate>
                    <Rectangle Width="100" Height="50" Fill="Red"/>
                </DataTemplate>
            </ItemsControl.ItemTemplate>
    </ItemsControl>
</UserControl>
```

```cs
public class ExampleViewModel : ViewModelBase
{
    private ProblematicClass[] SomeCollection { get; } =
    {
        new(), new(), new()
    };
}
```

```cs
public class ProblematicClass
{
    public ProblematicClass()
    {
        string path = Path.Combine(_assetsPath, fileName);
        var uri = new Uri(path);
            
        var assets = AvaloniaLocator.Current.GetService<IAssetLoader>();
        var asset = assets?.Open(uri);
        
        this.ExampleImage = asset is null ? null : new Bitmap(asset);
    }
    
    private Bitmap? ExampleImage { get; }
}
```
2. Publish the Avalonia application on a Linux machine targeting Windows (I built it with the integrated feature in JetBrains Rider, either x64 or x86, doesn't matter)
3. Move the build to a Windows machine
4. Open the application there, try to open the problematic view

**Expected behavior**
If the process of opening the asset fails, it should at least return `null`. The best case scenario would allow me to use this feature on all platforms, no matter where I built it, without this issue, as it does on a Linux machine. My view gets displayed, the desired asset gets found and used to build a `Bitmap` instance out of this, which I can use later on to display a specific image.

**Desktop (please complete the following information):**

- OS: Linux (Pop! OS 21.10), Windows 10 1909
- Version: Avalonia 0.10.13 (latest)

**Additional context**
There is one other thing I noticed too that might be related to this: Each time I build my Avalonia application for Windows on my Linux machine, I get this warning:
```
Microsoft.NET.Sdk.targets(464, 5): [NETSDK1074]: The application host executable will not be customized because adding resources requires that the build be performed on Windows (excluding Nano Server).
```
This might or might not be related to the way Avalonia deals with assets. "resources" is a keyword that tells me this could be related.

**Comment by kekekeks** [comment]
Make sure that the assembly with the asset is actually loaded. The best way would be to add `GC.KeepAlive(typeof(Type.In.Your.Assembly))` to the beginning of `BuildAvaloniaApp`.

**Comment by duck-dev** [comment]
@kekekeks Thank you for your respond. I don't think they are in another assembly. I am able to use a relative path in my AXAML-files and the URI I'm using, which works on Linux, is "avares://MainAssembly/Assets/file-name.ico", where "MainAssembly" is replaced by the application name. As this works on Linux and the assembly referenced in this URI is the same as for all my other files, I don't think the assemblies should be separated.
Keeping this assembly alive doesn't change anything.

**Comment by duck-dev** [comment]
I've tried to investigate this issue further with no success. Should I recognize this as an issue related to Avalonia, the .NET SDK warning I'm getting upon publishing (even with the latest version of .NET 6) or even something else? Is there maybe someone who knows a workaround for this, while still achieving the same goal? 
My intensive researches haven't really lead me anywhere and I've tried so many different things with no result.

**Comment by maxkatz6** [comment]
I don't know what's the reason of this issue. But ```The application host executable will not be customized because adding resources requires that the build be performed on Windows (excluding Nano Server)``` isn't about embed resources, but about [app icon and manifest](https://github.com/dotnet/runtime/issues/3828). From what I remember embed resources worked for me when I built my apps on linux docker.

**Comment by maxkatz6** [comment]
@duck-dev so it seems issue wasn't in Avalonia code, right? Avalonia uses URI for a resource path, so separator should be "/". 
I don't think it would be proper to make assembly paths platform specific.
