### ISSUE TITLE
Embedding fonts?

### ISSUE THREAD

**Issue by 0xFireball** [AvaloniaUI/Avalonia#810]
Hi,
Is there a way to load embedded fonts into the app at runtime? I don't want users to have to install the font files on their system.

**Comment by kekekeks** [comment]
Skia: https://developer.xamarin.com/api/member/SkiaSharp.SKTypeface.FromStream/p/SkiaSharp.SKStreamAsset/System.Int32/
Direct2D: https://github.com/sharpdx/SharpDX-Samples/blob/master/Desktop/DirectWrite/CustomFont/CustomFont.cs

Cairo seems to be lacking that feature for some reason (I also may be blind)

**Comment by BlackDragonBE** [comment]
How do you load in the font exactly?
I now have a SKTypeFace, where can I feed that into Avalonia's available font families?

**Comment by danwalmsley** [comment]
Font embedding or loading isn't yet supported. Can only use fonts installed on the system.

**Comment by jmacato** [comment]
Fixed by #1564 and #1679.
