### ISSUE TITLE
Can't debug an AvaloniaUI application on Visual Studio for Mac

### ISSUE THREAD

**Issue by rafaga** [AvaloniaUI/Avalonia#8101]
**Describe the bug**
You can't debug an Application in Visual Studio for Mac 

**To Reproduce**

Open any AvaloniaUI application using Visual Studio for Mac and  you can't to run it with Debug enabled

**Expected behavior**
Be able to debug the Application on MacOS

**Screenshots**

**Desktop (please complete the following information):**
<img width="751" alt="Captura de Pantalla 2022-05-08 a la(s) 20 56 03" src="https://user-images.githubusercontent.com/1034690/167327842-a5b2c681-cf03-4f53-aa41-3d6cd4697337.png">

- OS: MacOS Monterey 12.3.1
- AvaloniaUI Version 0.10.13
- Visual Studio for Mac 17.0 preview Build 8754
- XCode 13.3.1 (build 13E500a)

**Comment by MikeCodesDotNET** [comment]
This is very strange! 

Can you share the contents of your PropertyGroup from the .csproj? 

It'd also be useful to know if you've tried debugging the same project in JetBrains Rider? You can get a free trial of Rider if you don't have a license.

**Comment by MikeCodesDotNET** [comment]
I've just tested with Visual Studio Preview 17 (build 8904) and it seems fine here.

**Comment by rafaga** [comment]
I put the <PropertyGroup> section

```
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <!--Avalonia doesen't support TrimMode=link currently,but we are working on that https://github.com/AvaloniaUI/Avalonia/issues/6892 -->
    <TrimMode>copyused</TrimMode>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>
```

**Comment by rafaga** [comment]
do you need something else to help you to reproduce the issue ?

**Comment by maxkatz6** [comment]
I would recommend to report this bug to the VS for Mac team as well.

**Comment by rafaga** [comment]
I reported the problem to and they triaged the issue, apparently it was related to the Visual studio installation on my computer. Reinstalled all the IDE and everything works like a charm. Closing the issue. Thank you for your help
