### ISSUE TITLE
[Doc] Opening Dialogs

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#8109]
There is a page (3 pages) in the documentation about [opening dialogs here](https://docs.avaloniaui.net/tutorials/music-store-app/opening-a-dialog). It's a very complicated approach.

I just published [HanumanInstitute.MvvmDialogs](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs) which makes this kind of operation super simple. I think the documentation should be updated to include this *much* simpler approach. With at least a link; the library's usage is well-documented already.

**Comment by timunie** [comment]
Documentation has it's own GitHub repo. You can forward the issue there or open a PR there.

**Comment by mysteryx93** [comment]
OK I posted it there
