### ISSUE TITLE
How do I add the Arabic language to the Avalonia?

### ISSUE THREAD

**Issue by AbdalaMask** [AvaloniaUI/Avalonia#8132]
![image (1)](https://user-images.githubusercontent.com/37013638/168444728-8be7adbd-67e0-440d-acc5-4ccbfde72aff.png)
![image](https://user-images.githubusercontent.com/37013638/168444730-dfbd2d64-61a5-428c-afa2-d9ef5420307c.png)

**Comment by Gillibald** [comment]
What exactly is your issue?

**Comment by AbdalaMask** [comment]
Arabic language to the Avalonia not working to  web and android

**Comment by AbdalaMask** [comment]
![image](https://user-images.githubusercontent.com/37013638/169860110-76f51cbe-55cc-4c3d-a6fd-9b23a1b90c77.png)
Arabic language to the Avalonia not working

**Comment by AbdalaMask** [comment]
![image](https://user-images.githubusercontent.com/37013638/169865477-66ad59b5-1364-4874-84cb-76538dc3965a.png)

**Comment by kekekeks** [comment]
RTL text layot is implemented in 11.0, you probably need to ship your own fonts.
