### ISSUE TITLE
DrawingContext.DrawEllipse Matrix Bug on macOS High Sierra

### ISSUE THREAD

**Issue by Egorkin-enabled** [AvaloniaUI/Avalonia#8135]
**Describe the bug**
If create custom component, override Render method, apply new matrix through context.PushSetTransform, and draw ellipse, then ellipse still will draw in screen space, without changes. But if draw rectangle before, everything renders perfect.

Если создать пользовательский компонент, переопределись функцию Render, применить трансформации через  context.PushSetTransform и нарисовать эллипс, то эллипс будет нарисован так, будто трансформации не принимались. Но если до этого нарисовать прямоугольник, то все отображается прекрасно.

**To Reproduce**

1. Go to 'https://github.com/Egorkin-enabled/AvaloniaMatrixBug'
2. Clone the project.
3. Run the project.

<para/>

1. Перейдите по ссылке 'https://github.com/Egorkin-enabled/AvaloniaMatrixBug'
2. Скопируйте проект.
3. Запустите  проект
5. Наблюдайте ошибку.

**Expected behavior**
Ellipse must be transformed. Эллипс должен быть трансформирован.

**Screenshots**
Without Rect
![Снимок экрана 2022-05-15 в 12 03 48](https://user-images.githubusercontent.com/66767941/168465280-2252da9f-c887-4331-b617-a9babe3153fe.png)
With rect
![Снимок экрана 2022-05-15 в 12 05 21](https://user-images.githubusercontent.com/66767941/168465324-bc081967-b990-4c28-b672-ef7423ae40bd.png)

**Desktop:**

- OS: Mac OS High Sierra (10.13.6)
- Version: both 0.10.13 and 0.10.14

**Additional context**
Code pice is here:
[Views/ErrorControl.axaml.cs](https://github.com/Egorkin-enabled/AvaloniaMatrixBug/blob/main/Views/ErrorControl.axaml.cs)

**Comment by Egorkin-enabled** [comment]
How to avoid this issue?

**Comment by MarchingCube** [comment]
This is a bug that was fixed in https://github.com/AvaloniaUI/Avalonia/pull/7921. Should be included in upcoming 0.10 release.

**Comment by Egorkin-enabled** [comment]
Thank you! I'll wait this release hotly! Any way, Avalonia is amazing!
