### ISSUE TITLE
Bitmap as Resources

### ISSUE THREAD

**Issue by chenjing1294** [AvaloniaUI/Avalonia#8136]
https://docs.avaloniaui.net/docs/controls/button#play-button

The following writing method reports an error at compile time：

```xml
<UserControl.Resources>
    <Bitmap x:key="Play">/Assets/Player/Play.png</Bitmap>
    <Bitmap x:key="Pause">/Assets/Player/Pause.png</Bitmap>
</UserControl.Resources>
```
```xml
<StackPanel.Resources>
  <Bitmap x:key="Play">
    <x:Arguments>
      <x:String>/Assets/play.png</x:String>
    </x:Arguments>
  </Bitmap>
  <Bitmap x:key="Pause">
    <x:Arguments>
      <x:String>/Assets/pause.png</x:String>
    </x:Arguments>
  </Bitmap>
</StackPanel.Resources>
```

**Comment by maxkatz6** [comment]
Duplicate https://github.com/AvaloniaUI/Documentation/issues/251

**Comment by Kryptos-FR** [comment]
@maxkatz6  Link is dead. Where do I find documentation on loading a bitmap as resources from within a axaml file?

**Comment by timunie** [comment]
https://docs.avaloniaui.net/docs/guides/data-binding/how-to-bind-image-files maybe this page is what you are looking for
