### ISSUE TITLE
Despatcher invoke methods need renaming.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#816]
The naming of `Dispatcher.InvokeTaskAsync` is confusing: the Async suffix usually means return a task. Remove this and rename `InvokeTaskAsync` as `InvokeAsync`. I think we only only need one? The task can be explicitly ignore if necessary.

**Comment by kekekeks** [comment]
`InvokeTaskAsync` actually allocates a `TaskCompletionSource` structure, `InvokeAsync` just posts a job to the queue.

**Comment by grokys** [comment]
I notice that the `Job` class actually creates the `TaskCompletionSource`, so it will be created for both methods. Given that, do we really need both? Can't we just have `Task InvokeAsync` and the caller can just ignore the `Task` if they want to?

**Comment by kekekeks** [comment]
We probably need to rework that to reduce allocations when they arent' needed.

**Comment by grokys** [comment]
Ok, could we rename them `Task InvokeAsync` and `void Post`? A non-async method with the `Async` suffix doesn't sit right with me, and the WPF `Dispatcher` calls the async version `InvokeAsync`.

**Comment by kekekeks** [comment]
Post should be OK since it conforms to `SynchronizationContext::Post` behaviour
