### ISSUE TITLE
CreateNativeControlCore returns null in 0.10.14, ok in 0.10.13

### ISSUE THREAD

**Issue by mfkl** [AvaloniaUI/Avalonia#8177]
**Describe the bug**

When implementing my own `NativeControlHost`, I need to override the following method
```
protected override IPlatformHandle CreateNativeControlCore(IPlatformHandle parent)
```

From 0.10.14, `parent` contains a NULL window handle, so naturally the `DumbWindow` handle created from `base.CreateNativeControlCore(parent);` is invalid as well.

**To Reproduce**

1. Clone https://github.com/videolan/libvlcsharp
2. Update the Avalonia nuget dependency in `LibVLCSharp.Avalonia.Sample.csproj` to `0.10.14`.
3. Place a breakpoint in `CreateNativeControlCore` in the Avalonia VideoView.
4. Run the sample

**Expected behavior**
Valid window handle like in previous versions.

**Screenshots**

**Desktop (please complete the following information):**

- OS: tested on Windows but I suspect it may be happening on Linux as well.
- Version 0.10.14

**Comment by maxkatz6** [comment]
I added this assert check in my another PR, but it should be moved to a separated one if we want it backported
https://github.com/AvaloniaUI/Avalonia/pull/8110/files#diff-54579ed150b51ad223ad14936d9c55a5bf0d6b9c9774ef3363080a7bc47c8f10R99

**Comment by mfkl** [comment]
Added
```
<?xml version="1.0" encoding="utf-8"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">

  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>

      <!-- Windows 10 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />

    </application>
  </compatibility>
</assembly>
```
with
```
<ItemGroup>
    <None Update="app.manifest">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```
This isn't working though. Your `NativeEmbedSample.csproj` doesn't seem to make use of the manifest. Wonder why this is necessary for win32 apps?

**Comment by maxkatz6** [comment]
For some newer win32 controls, like WebView, we need LAYERED window support, otherwise nothing is rendered. And for some weird reason developers have to opt-in win10 support in manifest to enable it.
