### ISSUE TITLE
No options to disable Min/Max boxes.

### ISSUE THREAD

**Issue by zezba9000** [AvaloniaUI/Avalonia#820]
There are no Window options to disable the Minimize / Maximize buttons like you can with WPF for example.

**Comment by SuperJMN** [comment]
Do you mean the Minimize / Maximize buttons?

**Comment by zezba9000** [comment]
Yes

**Comment by KvanTTT** [comment]
Actually this issue is duplicate. Another one about `ResizeMode` exists: https://github.com/AvaloniaUI/Avalonia/issues/437.

**Comment by zezba9000** [comment]
Minimize has nothing to do with Windows resizing though. If you want to remove this card then the other needs to be updated to reflect this or this card needs to be updated to be only about the Minimize button.

**Comment by zezba9000** [comment]
I guess ResizeMode has to do with Minimize as well. I wonder if this approach could be translated to Cocoa or  GTK etc.

**Comment by zezba9000** [comment]
Closing issue.

**Comment by SparkyTD** [comment]
Still doesn't seem to be possible to create a "Tool Window" and hide the minimise/maximise/restore buttons. A workaround is to define the following style:
```xml
<Styles xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <Style Selector="Window.tool_window Panel#PART_MinimiseButton">
        <Setter Property="IsVisible" Value="False"></Setter>
    </Style>
    <Style Selector="Window.tool_window Panel#PART_RestoreButton">
        <Setter Property="IsVisible" Value="False"></Setter>
    </Style>
</Styles>
```
And add the `tool_window` class to your tool window.
