### ISSUE TITLE
Avalonia WASM duplicate pointer click on mobile browser

### ISSUE THREAD

**Issue by Oxc3** [AvaloniaUI/Avalonia#8200]
**Describe the bug**
when using a touch device, at least on mobile browsers, a tap on interactive controls will trigger twice due to the touch input as well as a pointer input being triggered. Both Touch.Begin, Touch.End as well as Pointer.LeftButtonDown and Pointer.LeftButtonUp events are fired with a single tap.

**To Reproduce**

1. Start any Avalonia.Web.Blazor project
2. Click on any user input.

**Expected behavior**
A single Touch.Begin and Touch.End events only

**Screenshots**
![Capture](https://user-images.githubusercontent.com/61174136/170399316-abff20c1-69dd-48f1-9b05-c2d259f8a40f.PNG)

- OS: Android, iOS
- Version 0.10.14

**Comment by Oxc3** [comment]
ultimately this is the browser sending the duplicate events so it can mitigated on the html page by eating the mouse events if they come after touch events.
`<body onmousedown="mouse(event)" onmouseup="mouse(event)" ontouchstart="touch(event)" ontouchend="touch(event)">
    <script>
        var touchStart = false;
        var touchEnd = false;
        function mouse(evt) {
            if (evt.type == "mouseup" && touchStart) {
                touchStart = false;
                evt.preventDefault();
                evt.stopPropagation();
            }
            if (evt.type == "mousedown" && touchEnd) {
                touchEnd = false;
                evt.preventDefault();
                evt.stopPropagation();
            }
        }
        function touch(evt) {
            if (evt.type == "touchstart") {
                touchStart = true;
            }
            else if (evt.type == "touchend") {
                touchEnd = true;
            }
        }
    </script>`
it would be a nice to have if Avalonia detected the duplicates, but its not really the applications fault so I am going to mark this closed.

**Comment by maxkatz6** [comment]
There is a workaround, but I think it's still an avalonia bug

**Comment by Oxc3** [comment]
Basically, if the ontouchend event is less then 400ms after ontouchstart (like a button click) the mouse events are also generated by the browser.  After reading javascript articles (not really my area) controls like buttons use the mouse event and ignore the touch events. I don't see an easy way to have the controls be platform aware, nor should they be. Also who knows if browsers change their behavior in the future and I haven't tested on all mobile browsers.

I don't mind adding the event eating code into Avalonia.razor.cs and submitting a pr if you feel that is appropriate. Or I guess this javascript could be added to the xplat template and it will accomplish the same thing.

**Comment by Gillibald** [comment]
We should fix that on our side by taking a timestamp on every touch/mouse event. For pairs that occur in within some specified timeframe we should only handle touch etc.

**Comment by maxkatz6** [comment]
Replacing "onmouse***" and "ontouch***" with single "onpointer***" events should also help. Pretty much any browser supports it, if it can work with webassembly.

**Comment by Oxc3** [comment]
@maxkatz6 is correct switching to onpointer*** does correct the issue. 
- mousedown & touchstart to pointerdown
- mouseup & touchend to pointerup
- mousemove to pointermove
does the trick. 

`
        private void OnPointerMove(Microsoft.AspNetCore.Components.Web.PointerEventArgs e)
        {
            if (e.PointerType == "mouse")
            {
                _topLevelImpl.RawMouseEvent(RawPointerEventType.Move, new Point(e.ClientX, e.ClientY), GetModifiers(e));
            }
        }

        private void OnPointerUp(Microsoft.AspNetCore.Components.Web.PointerEventArgs e)
        {
            if (e.PointerType == "touch")
            {
                _topLevelImpl.RawTouchEvent(RawPointerEventType.TouchEnd, new Point(e.ClientX, e.ClientY),
                    GetModifiers(e), e.PointerId);
            }
            else if (e.PointerType == "mouse")
            {
                RawPointerEventType type = default;

                switch (e.Button)
                {
                    case 0:
                        type = RawPointerEventType.LeftButtonUp;
                        break;

                    case 1:
                        type = RawPointerEventType.MiddleButtonUp;
                        break;

                    case 2:
                        type = RawPointerEventType.RightButtonUp;
                        break;
                }

                _topLevelImpl.RawMouseEvent(type, new Point(e.ClientX, e.ClientY), GetModifiers(e));
            }
        }
        
        private void OnPointerDown(Microsoft.AspNetCore.Components.Web.PointerEventArgs e)
        {
            if (e.PointerType == "touch")
            {
                _topLevelImpl.RawTouchEvent(RawPointerEventType.TouchBegin, new Point(e.ClientX, e.ClientY),
                    GetModifiers(e), e.PointerId);
            }
            else if (e.PointerType == "mouse")
            {
                RawPointerEventType type = default;

                switch (e.Button)
                {
                    case 0:
                        type = RawPointerEventType.LeftButtonDown;
                        break;

                    case 1:
                        type = RawPointerEventType.MiddleButtonDown;
                        break;

                    case 2:
                        type = RawPointerEventType.RightButtonDown;
                        break;
                }

                _topLevelImpl.RawMouseEvent(type, new Point(e.ClientX, e.ClientY), GetModifiers(e));
            }
        }

        private static RawInputModifiers GetModifiers(Microsoft.AspNetCore.Components.Web.PointerEventArgs e)
        {
            var modifiers = RawInputModifiers.None;

            if (e.CtrlKey)
                modifiers |= RawInputModifiers.Control;
            if (e.AltKey)
                modifiers |= RawInputModifiers.Alt;
            if (e.ShiftKey)
                modifiers |= RawInputModifiers.Shift;
            if (e.MetaKey)
                modifiers |= RawInputModifiers.Meta;

            return modifiers;
        }
`

touchmove needs to stay and pointermove needs to only handle "mouse" PointerType events because unless specified as touch-action: none in css the pointermove will be canceled by the browser and switch to built in actions, this does not happen with ontouchmove.
