### ISSUE TITLE
[Wishlist] StringFormat for Bindings

### ISSUE THREAD

**Issue by SuperJMN** [AvaloniaUI/Avalonia#821]
Like in classic Bindings. I personally find it very handy and simple to create expose text without having to modify my ViewModels.

**Comment by grokys** [comment]
Yep! This would be super useful. On my personal wishlist would be to use something like the binding syntax in polymer so you could do:

`<TextBlock Text="The is the value: {foo}"/>`

I'm not sure how this would work though ;)

**Comment by SuperJMN** [comment]
Blows my mind! OmniXAML can give you superpowers using converters. Maybe adding a special one that converts those kind of strings into bindings :)

**Comment by jogibear9988** [comment]
How about a new MarkupExtension, {StringBinding "Hello {name} you are {age} years old" } is smth like this is possible. The extension should create multiple bindings to all used properties inside, so it's refreshed when smth. changed. And maybe it should use https://github.com/scottrippey/SmartFormat.NET for string formating

**Comment by SuperJMN** [comment]
It looks useful @jogibear9988 :)
