### ISSUE TITLE
Consider using GtkFileChooserNative instead of GtkFileChooserDialog

### ISSUE THREAD

**Issue by dylanmccall** [AvaloniaUI/Avalonia#8213]
At the moment, Avalonia's Gtk UI uses [GtkFileChooserDialog](https://docs.gtk.org/gtk3/class.FileChooserDialog.html). This means Avalonia applications running in a sandbox (such as Flatpak or Snap apps) will not be able to open files on the host unless they have been given access ahead of time. We can solve this by using [GtkFileChooserNative](https://docs.gtk.org/gtk3/class.FileChooserNative.html), which has the ability to open a _privileged_ file chooser that grants fine-grained access for a sandboxed application.

Glancing at the relevant code, I don't believe any GtkFileChooserDialog-specific API is being used, so it could be reasonably straightforward to change this code to use GtkFileChooserNative.

**Comment by kekekeks** [comment]
We are manipulating the window created by GtkFileChooserDialog to manually set the transient parent to Avalonia window. Unfortunately the dialog only accepts a _Gtk_Window as a parent and we can only get a _Gdk_Window for our XID using `gdk_x11_window_foreign_new_for_display`.

**Comment by kekekeks** [comment]
I think we should just use xdg-desktop-portal DBus APIs when it's available, that would solve both sandboxing issues and would allow us to use Qt-based dialog when running in KDE environment.

**Comment by dylanmccall** [comment]
Aha, I see that now. Yeah, that's always awkward with these things. That would be perfect, indeed!
