### ISSUE TITLE
Massive memory leak in ContextMenu/MenuItem

### ISSUE THREAD

**Issue by BAndysc** [AvaloniaUI/Avalonia#8214]
**Describe the bug**
ContextMenu (or MenuItem) has a massive memory leak. Basically once they are opened, they are always in the memory. And for me the biggest problem is they usually have a reference to `Command`/`CommandParameter` in DataContext. Via those two fields, this "leak" can extend to the DataContext. And we all know how big this problem can get.

What is more interesting, it doesn't happen in Default theme (the old one), so it is something related to the styles.

(this happens both for ContextMenu and FlyoutMenu)

**To Reproduce**

1. Clone the repo: https://github.com/BAndysc/AvaloniaMenuLeak
2. Run the app
3. The top text shows managed used memory, in the beginning it is less than 3 MBs
4. Press the button `Add control`
5. This will spawn a control, that has a reference to 1GB byte array, so obviously the ram usage will rise up to 1 GB
6. Press `Remove Control`
7. GC will free the control and datacontext almost instantly, and it will go down to 3 MBs, so far so good.
8. Press `Add control` again
9. This time open the context menu in the red content
10. Press `Remove control`
11. Notice this time the memory usage doesn't drop. The control is not freed!

**Expected behavior**
MenuItem should be removed from the memory (clearing `Command` field is just a workaround for leaking datacontext, but menu item is still leaked)

**Desktop:**

- OS: Mac
- Version 0.10.14

**Additional context**
dotMemory proof that there is a unwanted reference to DataContext via MenuItem via styles.
![leak](https://user-images.githubusercontent.com/5689666/170792462-cbac026b-874f-42db-b0fe-acfb2d738f98.png)

**Comment by garyhertel** [comment]
Not sure if this helps any, but I ran into a similar issue a while back and added this workaround:

```csharp
public class CustomMenuItem : MenuItem, IStyleable
{
	Type IStyleable.StyleKey => typeof(MenuItem);

	public CustomMenuItem (string header = null)
	{
		Header = header;
		Items = null; // Clear to avoid weak event handler leaks
	}
}
```

**Comment by maxkatz6** [comment]
I can reproduce this issue even on 0.10.0. Not a regression, quite old leak.

**Comment by BAndysc** [comment]
I wanted to test the fix, I've added avalonia nuget feed, I've tried to use `0.10.999-cibuild0020838-beta` (PR build) and also `0.10.999-cibuild0020844-beta` (after merge build), but I can't build the app using neither of them, both are complaining about unknown FluentTheme
```
  App.axaml(10, 10): [XAMLIL] Unable to resolve type FluentTheme from namespace https://github.com/avaloniaui Line 10, position 10.
  ```
  Has anything changed regarding the style in the master branch, compared to the stable 0.10.14? The theme was important here in this story.

**Comment by maxkatz6** [comment]
> Has anything changed regarding the style in the master branch, compared to the stable 0.10.14?

A lot. 

> The theme was important here in this story.

Add Avalonia.Themes.Fluent nuget package.

**Comment by BAndysc** [comment]
Ah yeah, thanks. The bug is indeed fixed now, but I've found another memory leak, this time only in master branch, already reported it in another issue, thanks for help and fantastic work!
