### ISSUE TITLE
[ScrollBar+Slider] Clicking outside the thumb doesn't scroll

### ISSUE THREAD

**Issue by SuperJMN** [AvaloniaUI/Avalonia#822]
The user expects scrollbars and sliders to scroll when they're clicked outside the thumb.

![image](https://cloud.githubusercontent.com/assets/3109851/21144999/f246637c-c14c-11e6-98f1-af6e826e4296.png)

(The green zone in the picture)

**Comment by aelij** [comment]
Fixed in #1132
