### ISSUE TITLE
There is no method "RaiseAndSetIfChanged" or "RaisePropertyChanged" in ViewModelBase or parent class

### ISSUE THREAD

**Issue by xjsolid** [AvaloniaUI/Avalonia#8222]
HI, I'm using VS2022 with Avalonia for Visual Studio extension installed.
I Create a Avalonia MVVM Application from the template, App runs ok;
In MainWindowViewModel.cs, I'm trying to add these code below:

`public class MainWindowViewModel : ViewModelBase
    {
        public string Greeting => "Welcome to Avalonia!";

        string title = string.Empty;
        public string Title
        {
            get { return title; }
            set
            {
                this.title = value;
                this.
            }
        }
    }`

These is no notification method such as "RaiseAndSetIfChanged" or "RaisePropertyChanged" after I typed "this."
I found ViewModelBase Inherits from ReactiveObject, none of them implement INotifyPropertyChanged;
Is there any steps I missed?

**Comment by maxkatz6** [comment]
ReactiveObject does implement INotifyPropertyChanged https://www.reactiveui.net/api/reactiveui/reactiveobject/
And it has RaiseAndSetIfChanged/RaisePropertyChanged methods.

Could you have some problem with ReactiveUI or nuget?

**Comment by maxkatz6** [comment]
Note, these two methods are part of ReactiveUI namespace as well https://www.reactiveui.net/api/reactiveui/ireactiveobjectextensions/

Visual Studio should have fixes for that.

**Comment by xjsolid** [comment]
After add using ReactiveUI;
It works, thanks for the quick response;
