### ISSUE TITLE
Control fields are always null in UserControls

### ISSUE THREAD

**Issue by SlidyDev** [AvaloniaUI/Avalonia#8231]
**Describe the bug**
When assigning a name to a control (`Name="someControl"`), a field is auto-generated but is never assigned. This issue only happens in UserControls (from my own experience).

**To Reproduce**

1. Create a UserControl
2. Add a Label (or any other control) to it and give it a name (for example `<Label Name="someLabel">Test</Label>`)
3. Try setting its contents through a script (the field will always be null)

**Expected behavior**
For the field to not be null.

**Screenshots**
![image](https://user-images.githubusercontent.com/61495410/171102202-bdf8d12b-2882-4f9d-9c11-1678b5491622.png)
![image](https://user-images.githubusercontent.com/61495410/171103486-b006b65f-7c45-496f-ab65-6b9a39f13863.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 10.0.22000

**Comment by kekekeks** [comment]
Are you sure that your Label isn't a part of a DataTemplate or other deferred-loaded content?

**Comment by SlidyDev** [comment]
> Are you sure that your Label isn't a part of a DataTemplate or other deferred-loaded content?

The same issue happens with any type of control, even panels

**Comment by maxkatz6** [comment]
Can you share simple project to reproduce? With xaml.

**Comment by maxkatz6** [comment]
Thanks. Reproduced and it seems to be known problem with templates: https://github.com/AvaloniaUI/AvaloniaVS/issues/249
Not related to this repository, please follow issue from my link.

**Comment by maxkatz6** [comment]
In short, you need to remove InitializeComponent method body, as it is defined in source generator. And all the properties are initiated inside of source generator impl.

**Comment by maxkatz6** [comment]
PR to fix this incompatibility https://github.com/AvaloniaUI/AvaloniaVS/pull/259
