### ISSUE TITLE
Slider Ticks Missing

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#8278]
Here's a simple slider control. Some ticks are missing?? It also messes up with `IsSnapToTickEnabled` making the control unusable.

    <Slider Minimum="0" Maximum="5" Ticks="1" TickPlacement="TopLeft" />

[![Screenshot-11.png](https://i.postimg.cc/02wfxv7P/Screenshot-11.png)](https://postimg.cc/ppP8Yg06)

Pretty self-explanatory.

- OS: Linux (Garuda)
- Version 0.10.14

**Comment by maxkatz6** [comment]
> Some ticks are missing?

No. Minimum is 0, maximum is 5, and single tick is at position of 1. Looks as expected.
You can either set an array of ticks separated by comma or use TickFrequency property. IIRC same behavior as in WPF.

**Comment by mysteryx93** [comment]
Ah.

**Comment by ClementeGao** [comment]
how to limit only show number
