### ISSUE TITLE
Avalonia Blazor Webassembly shows errors

### ISSUE THREAD

**Issue by DeafMan1983** [AvaloniaUI/Avalonia#8288]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

I have downloaded with git clone from here and I tested before with netcore then it works fine but path to node.mp4 failure cause it looks "doesn't find mp4 file" and I try to copy-past to root directory of Debug or Release then it works fine but X11 BadWindow throws exception cause mplayer can't close while you close Avalonia 's MainWindow then I open Avalonia Source with VSCode wow. Why do you not care with nint / nuint since Net 6.0 has new features of current architecture x86 / x64 conflict like you have Windows 10 Pro 32 Bit then Avalonia MainWindow will crash cause IntPtr is not long just int that is why you should use "nint" and "nuint".
I would like to help you because I don't like if it happened with Avalonia UI like they have big problems.. That is why I want save for Avalonia UI :)

And I try to use Blazor Webassembly and Google Chrome throws exceptions and errors.
![image](https://user-images.githubusercontent.com/57066679/172065179-af8e41e0-e891-4cd1-adc2-ac89a84b2c82.png)

How do I fix? Thanks

I already tried
1. dotnet restore
2. dotnet build <- Please remember to install sudo apt install -fy nodejs then dotnet build
3. dotnet run
4. Copy or open url to browser and press key F12 to open Web-Tools-Console
5. I get many errors. 

I use Net 6.0x latest version with wasm-tools

**Comment by maxkatz6** [comment]
Have you tried to build a project from a template?

**Comment by DeafMan1983** [comment]
@maxkatz6 No I will try later.
if I use `dotnet publish` with samples/ControlCatalog.Web 
and I test with python -m http.server than i ran website and it loads before okay now it looks weird :(

Check my youtube and I have tried like publish directory or run end of usable directory for wasm. https://www.youtube.com/watch?v=SL2vz_0zLUA

**Comment by maxkatz6** [comment]
Please use newer backend without blazor at all. I.e. "Avalonia.Browser" package.
