### ISSUE TITLE
IsEnabled is not working in TrayIcon NativeMenuItems

### ISSUE THREAD

**Issue by milkywayfarer** [AvaloniaUI/Avalonia#8308]
**Describe the bug**
`IsEnabled` property does not work on `NativeMenuItem` in `TrayIcon` `Menu`.

**To Reproduce**
You can use code like this in your `App.xam`:
```
<TrayIcon.Icons>
      <TrayIcons>
        <TrayIcon Icon="/Assets/icon.ico" ToolTipText="{Binding iconHeader}" IsVisible="{Binding trayVisibility}" Clicked="Click">
          <TrayIcon.Menu>
            <NativeMenu>
              ...
              <NativeMenuItem Header="{Binding currentGamePlay}" IsEnabled="False" Command="{Binding PlayGame}"/>
              <NativeMenuItem Header="{Binding ...}" IsEnabled="{Binding isInstalled}" Command="{Binding ...}"/>
              ...
            </NativeMenu>
          </TrayIcon.Menu>
        </TrayIcon>
      </TrayIcons>
    </TrayIcon.Icons>
```
Both setting the value directly and binding it to a VM is not working.

**Expected behavior**
When `IsEnabled=false`, `MenuItem` should not be clickable and should get all the styles that are set by `[IsEnabled=false]` selector.

**Desktop:**

- OS: Windows 10 Pro 21H2
- Version 0.10.14

**Additional context**
I'm trying to hide the `MenuItem` when I do not need it using styles. Having `IsVisible` would be nicer, but using `IsEnabled` made me find this bug.

**Comment by milkywayfarer** [comment]
P.S.: Updated to Avalonia 0.10.15 and bug still exists.

**Comment by Aswathips** [comment]
Hi, I'm also facing the same issue.
Did you get any solutions?

**Comment by milkywayfarer** [comment]
> Hi, I'm also facing the same issue. Did you get any solutions?

No, I just won't use the TrayIcon until it's fixed.

**Comment by Aswathips** [comment]
> No, I just won't use the TrayIcon until it's fixed.

Is there any other way to load the application to the system tray?

**Comment by milkywayfarer** [comment]
> > No, I just won't use the TrayIcon until it's fixed.
> 
> Is there any other way to load the application to the system tray?

You can always use the TrayIcon itself, but menus are bugged at the moment. You can also look up `System.Windows.Forms` reference and it's TrayIcon implementation, although it'll work only on Windows.

**Comment by Aswathips** [comment]
> You can always use the TrayIcon itself, but menus are bugged at the moment. You can also look up `System.Windows.Forms` reference and it's TrayIcon implementation, although it'll work only on Windows.

I want to work on Linux and Mac also.

Did you know about  NotificationTrayIconSharp?
https://github.com/JesseRedfield/NotificationTrayIconSharp

I tried to load the app to the system tray using this package. Everything works perfectly except for changing the TrayIcon at runtime. I can't find any way to change the TrayIcon. Can You help me?

**Comment by FG-rgb** [comment]
If you have a look in the Avalonia Code, you will see that the IsEnabled property is auto update by Command.CanExecute.
Maybe you can solve your problem by specifying the CanExecute parameter on your bound command.
