### ISSUE TITLE
TextBox does not update the text after getting a value

### ISSUE THREAD

**Issue by ahmedmohammedfawzy** [AvaloniaUI/Avalonia#8309]
**Describe the bug**
So I have a basic Text box here
View:

    <TextBox Grid.Column="1"
             Grid.Row="2"
             Width="200"
             Height="32"
             Text="{Binding PollingInterval, Mode=TwoWay}"
             VerticalContentAlignment="Center"
             Margin="0 0 0 20" />

ViewModel:

    public string PollingInterval
    {
        get => _signal.PollingInterval.ToString();
        set => _signal.PollingInterval = value.FilterNumericString();
    }

This text box just takes the value and remove any characters than are not numbers, the problem is that when I enter a string like with text and numbers the text gets filtered correctly and the `_signal.PollingInterval` gets set to correct value and when the getter is called it returns the correct value but for some reason the view does not update

**Comment by ahmedmohammedfawzy** [comment]
> You property never raises a change event so the view will never know that is should update

But the getter actually gets called right after the setter and it returns the filtered value so I do not think that I need to raise the property changed event especially that this was originally working in WPF but now in avalonia it is not working

**Comment by maxkatz6** [comment]
You **need** to raise changes to support scenarios like this.
In WPF there is another way to listen for change notifications with some WPF-magic that often causes memory leaks. See https://www.codeproject.com/Articles/217670/The-Third-Way-of-Change-Notification-The-ValueChan
In avalonia we support changes with only INPC, AvaloniaProperty and IObservable.

**Comment by ahmedmohammedfawzy** [comment]
> You **need** to raise changes to support scenarios like this. In WPF there is another way to listen for change notifications with some WPF-magic that often causes memory leaks. See https://www.codeproject.com/Articles/217670/The-Third-Way-of-Change-Notification-The-ValueChan In avalonia we support changes with only INPC, AvaloniaProperty and IObservable.

I do not fully understand that WPF-magic but I changed the property to raise changes and it still has the same behaviour
(I want to note the the **getter gets invoked by the view but it neglects the value the getter returns for some reason and doesn't update the view**)

    public string PollingInterval
    {
        get => _signal.PollingInterval.ToString();
        set
        {
            _signal.PollingInterval = value.FilterNumericString();
            OnPropertyChanged();
        }
    }

**Comment by maxkatz6** [comment]
Yeah, that's another problem then, as you already found in https://github.com/AvaloniaUI/Avalonia/issues/8317
And https://github.com/AvaloniaUI/Avalonia/issues/3603
