### ISSUE TITLE
TrayIcon.Menu does not hide after NativeMenuItem Command is executed

### ISSUE THREAD

**Issue by FG-rgb** [AvaloniaUI/Avalonia#8312]
**Describe the bug**
In your App.xaml define a tray icon with a menu, like e.g.

```
<TrayIcon.Icons>
    <TrayIcons>
        <TrayIcon Icon="{Binding Path=Manager.CurrentTrayIcon,Mode=OneWay}"
                         ToolTipText="{Binding Path=Manager.Tooltip,Mode=OneWay}">
            <TrayIcon.Menu>
                <NativeMenu>
                    <NativeMenuItem Header="Testing" Command="{Binding Source={x:Static Application.Current},Path=TestCommand,Mode=OneTime}" />
                </NativeMenu>
            </TrayIcon.Menu>
        </TrayIcon>
    </TrayIcons>
</TrayIcon.Icons>
```

**To Reproduce**

1. Open the Tray.
2. Click on 'Testing'
3. The command is executed
4. But the popup window of the tray stays open.

**Expected behavior**
After the command is executed the popup window of the tray should close.

**Desktop (please complete the following information):**

- OS: Windows 10
- Avalonia Version 0.10.15

**Comment by nathanAjacobs** [comment]
Just ran into this also, this is unfortunate. I was trying to find a method to manually close/hide the NativeMenu manually, but I don't think one exists.

**Comment by FG-rgb** [comment]
> Just ran into this also, this is unfortunate. I was trying to find a method to close/hide the NativeMenu manually, but I don't think one exists.

I found a workaround for this. After/when your command is executed run following code to close the tray window:
```
if (Avalonia.Input.FocusManager.Instance?.Current is MenuItem menuItem && menuItem.Parent != null)
{
    var parentWindow = VisualTreeHelper.FindParentOnVisualTree<Window>(menuItem.Parent) as Window;
    parentWindow?.Close();
}
```
