### ISSUE TITLE
Resizing a Window that has ExtendClientAreaToDecorationsHint="True" shows white strips on Windows

### ISSUE THREAD

**Issue by Tetedeiench** [AvaloniaUI/Avalonia#8316]
**Describe the bug**
As soon as ExtendClientAreaToDecorationsHint="True" is set on a window, a white strip appears when resizing. This is disturbing for black-theme applications.

Happens on Windows 11 (and probably others). I suspect Windows chrome at work here.

**To Reproduce**

1. Create an empty window
2. Add Background="Black" to the window
3. Add ExtendClientAreaToDecorationsHint="True" to the window
4. Debug, Resize the window and see the white strip (see screenshot for a gif demo)

**Expected behavior**
The resize should not flicker white, but be of the same color as the Window background.

**Screenshots**
![resize flicker](https://user-images.githubusercontent.com/23140774/172896628-ba6fbb9d-b864-400c-b2e2-bfcc0c3182a3.gif)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 0.10.5

**Additional context**

**Comment by Tetedeiench** [comment]
I spent quite a while on this and couldn't find the underlying issue.

It seems that setting SystemDecorations="None" and managing the resize border manually doesn't trigger this issue when resizing. The default window style does not as well. Adding ExtendClientAreaToDecorationsHint="True" is the option that triggers this.

Sadly, it is the one i'm interested in greatly, as disabling SystemDecorations means implementing my own title bar for every OS, which is strongly discouraged for user experience. My users are bound to report the issue when resizing as well.

I'll try to hunt this in Avalonia's code base, but this isn't exactly my cup of tea, not sure i'll succeed !

**Comment by Tetedeiench** [comment]
This also happens in the controlcatalog built into avalonia. Build & run it (no changes), Set "ExtendClientAreaToDecorationsHint", set the theme to FluentDark, and resize.

**Comment by Tetedeiench** [comment]
Not sure if this is good practice to leave my comments here, but my findings shows the problem lies within the UpdateExtendMargins method : 
https://github.com/AvaloniaUI/Avalonia/blob/709ad86626071dd18b68df53f226fdbee3992151/src/Windows/Avalonia.Win32/WindowImpl.cs#L957

Replacing this call with ```var margins = new MARGINS();``` makes things work fine again.

I'm trying to understand what this function is doing, but it's a tough one !

**Comment by Tetedeiench** [comment]
In The abovementioned method, replacing all the 1 in this code by 0 fixes the issue :
```
 MARGINS margins = new MARGINS();
            margins.cxLeftWidth = **0**;
            margins.cxRightWidth = **0**;
            margins.cyBottomHeight = **0**;
            (...)
margins.cyTopHeight = _extendChromeHints.HasAllFlags(ExtendClientAreaChromeHints.SystemChrome) && !_extendChromeHints.HasAllFlags(ExtendClientAreaChromeHints.PreferSystemChrome) ? borderCaptionThickness.top : **0**;
```

I have 0 idea of what it is doing internally though. I'll look into it again tomorrow, if anyone has a clue or can enlighten me, i'm all for it !

**Comment by maxkatz6** [comment]
I am not an expert in Win32 API, but I am surprised you have this problem only with this property set.
It's common problem in many applications on Windows, including WPF apps, Edge and electron apps. I.e., when you resize window, draw operations aren't fast enough to redraw new area.
But at least in electron apps it's possible to change the color which is used as a filling background.

See https://github.com/AvaloniaUI/Avalonia/discussions/6752

![image](https://user-images.githubusercontent.com/3163374/172960911-ede16394-5f8b-4422-b1a6-2b98107474a1.png)

![image](https://user-images.githubusercontent.com/3163374/172960868-6c876194-cb56-4680-b65c-1f60df67f52a.png)

**Comment by amwx** [comment]
This is actually a well known issue within Windows itself: 
https://github.com/microsoft/microsoft-ui-xaml/issues/5148

Google search will also show this has cropped up in WPF and other UI frameworks.

This is based on my understanding of the issue, and may be incomplete but: The underlying issue is that there is no synchronization between resizing a window and DWM rendering. Normal Win32 apps are fine since they render through GDI, and UWP doesn't have that problem since it's baked into Windows itself and they probably can synchronize the underlying composition SwapChain with DWM. 

In Avalonia, WPF, etc, rendering is done internally to the framework. In Avalonia, rendering is handled usually by Skia. Even when WinUI comp is enabled here, where the backing texture is provided by DWM itself, DWM still doesn't know when Avalonia is finished drawing into the texture. So that border shows because DWM is rendering faster than the entire render-present process, so the window texture is sometimes smaller than the actual window, as its a few frames behind.

To try to answer your confusion in your last post, the `MARGINS` struct here is passed into `DwmExtendFrameIntoClientArea` which tells DWM how to draw the window frame. Setting it to 0 means you want no frame at all, and the entire window becomes the client area. What I don't know is why setting it to 0 removes the issue, but I suspect that DWM optimizes in this case - probably eliminating the step of drawing the border/shadow speeds the entire pipeline up, but that's just a guess.

**Comment by maxkatz6** [comment]
By changing Win32 backend options, you can get slighly different result on modern OS versions, but it won't solve problem completely:
```
                .With(new Win32PlatformOptions
                {
                    UseWindowsUIComposition = true // or false to test other options
                })
```
Which files to modify : https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog.NetCore/Program.cs#L116

With UseWindowsUIComposition Avalonia will use win10 APIs to get render target surface from the window.
Which make me think, UseWindowsUIComposition might give us better resizing experience, but it doesn't work properly with borderless window specifically.

**Comment by Tetedeiench** [comment]
I am currently building the foundation for the port of my application from WPF to avalonia. So, yeah, my window is currently pretty simple.

Again, I am not an expert by any means, so everything I say has to be cross-checked.

I gave a shot to the 0 margin quickfix with a heavy UI ( I just chose the datagrid tab of the controlcatalog as an example). Here's the result :
![resize flicker2](https://user-images.githubusercontent.com/23140774/172998084-32224a76-6920-4661-bc05-612ceb282523.gif)

Basically, the window background is painted transparent when the margins are set to 0. This effectively makes the issue disappear from the user point of view, or appear as a lag that's much less noticeable. It's understandable as well when the layout is heavy (actually, in my case, it will).

A longer term fix would be doing what everyone else does, that is setting the window background to the real background and not white when resizing. According to the stackoverflow post @maxkatz6 linked, it is done here : 
https://github.com/AvaloniaUI/Avalonia/blob/709ad86626071dd18b68df53f226fdbee3992151/src/Windows/Avalonia.Win32/WindowImpl.cs#L773

As you can see, this is set to IntPtr.Zero, which must be the white color. You can change that to another color. But this is not ideal, as this means you have to restart your app on every change, since there doesn't seem to be a way of changing that post-creation. It's still an improvement.

I then stumbled upon this : 
https://stackoverflow.com/questions/3463471/how-to-set-background-color-of-window-after-i-have-registered-it

The message WM_ERASEBKGND is present in Avalonia but unhandled right now. If I can just implement this and make it paint the window background color instead of relying on Windows's default redraw, this issue will be fixed the way everyone does, which is ideal.

Again, as you can see from all I'm writing, i'm not an expert in Win32, this is a shot in the dark at best by a newbie. I'll give it a shot, but my work would have to reviewed thoroughly before being approved, as it's the first time I see avalonia's code !

**Comment by Tetedeiench** [comment]
After spending a few hours with it, I couldn't change the white color fill, even by passing a brush to RegisterClassEx as hbrBackground.

I'm pretty stuck here.

I searched and the 1 pixel margin has been set since the first implementation ( https://github.com/AvaloniaUI/Avalonia/commit/d2bc5505c5eb8ea51533ffe295c696b9009702ea by @danwalmsley if I am correct  ).

As he seems a stellar win32 dev much more capable than myself, perhaps he won't mind being mentioned here (sorry !) and help in this issue ?

Big questions are why the 1-pixel margin (as ,this could qualify as a quickfix for a lot of use cases, that is for everyone that does not set PreferSystemChrome ), and how we could customize the white background shown when resizing (which is a better fix by all means).

**Comment by Tetedeiench** [comment]
Still stuck here, spent another hour on it without much success :(

**Comment by Tetedeiench** [comment]
Couldn't find a fix other than setting the margin to 0 as mentioned above.

@maxkatz6 , could this qualify as a valid fix for this ? Who can tell us if it is ?

**Comment by maxkatz6** [comment]
@Tetedeiench yes, let's do it.
It might be safer to remove this margin only if WinUIComp is used as I mentioned above. But to be honest, I am not sure if it's needed.

**Comment by maxkatz6** [comment]
> As you can see, this is set to IntPtr.Zero, which must be the white color

From my understanding, hbrBackground is completely ignored when WinUIComp is used. I remember changing this color and there was no effect.

**Comment by amwx** [comment]
> > As you can see, this is set to IntPtr.Zero, which must be the white color
> 
> From my understanding, hbrBackground is completely ignored when WinUIComp is used. I remember changing this color and there was no effect.

Correct, WinUIComp renders directly to DWM, hbrBackground only works if the window has a redirection surface (GDI rendering).


The other thing you might be able to try @Tetedeiench, the white background might be because Win32 windows are always light mode: If you don't mind a little p/invoke/Win32 API, you can force a Win32 app to use dark mode. I didn't test this for your case (but this is what I do for dark mode windows), and it won't be a perfect solution, but it might make the background a darker color and make it less noticeable. This works on Windows 10 1809 (build 17763) and later (inc. Win 11), before that it wasn't possible

```C#
[DllImport("dwmapi.dll")]
public static extern int DwmSetWindowAttribute(IntPtr hwnd, DWMWINDOWATTRIBUTE dwAttribute, ref int pvAttribute, int cbAttribute);

public enum DWMWINDOWATTRIBUTE
{
DWMWA_USE_IMMERSIVE_DARK_MODE = 20,
}

int isDark = 1;
DwmSetWindowAttribute(HWND, DWMWINDOWATTRIBUTE.DWMWA_USE_IMMERSIVE_DARK_MODE, ref isDark, Marshal.SizeOf<int>());
```

**Comment by Tetedeiench** [comment]
@amwx Thanks a lot for the workaround - it works perfectly for me until the fix reaches the live version. The background is painted with a dark gray color, which, while different from my window background color, doesn't stand out as much as white, and thus is a very valid and acceptable fix.

![white bars gone](https://user-images.githubusercontent.com/23140774/175807161-abfb82f9-bd72-4dc5-8088-358c0eb25b97.gif)

**Comment by Tetedeiench** [comment]
I'm not used to submitting PRs, please be comprehensive when reviewing it ( this should be OK as the fix is simple).
