### ISSUE TITLE
TextBox ignores any changes while the user is inputting text

### ISSUE THREAD

**Issue by ahmedmohammedfawzy** [AvaloniaUI/Avalonia#8317]
**Describe the bug**
Avalonia TextBox contains a field callled `_ignoreTextChanges` which stops the Textbox from reacting to changes while the user inputs text, I understand that it might be beneficial in some case but in others it causes a lot of unexpected behavior (especially when migrating from WPF because WPF does not has this behavior by default), implementing a property on the text box that disable the `_ignoreTextChanges`  will be really useful

**Comment by maxkatz6** [comment]
See https://github.com/AvaloniaUI/Avalonia/issues/3603
