### ISSUE TITLE
Can not build avalonia blazor app, TS18003 Build:No inputs were found in config file

### ISSUE THREAD

**Issue by GaNacereddine** [AvaloniaUI/Avalonia#8322]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/8321

<div type='discussions-op-text'>

<sup>Originally posted by **GaNacereddine** June 10, 2022</sup>
I created a new blazor web assembly project then added avalonia.Web.Blazor 0.10.15 package 

and when I try to build I get this error 

**TS18003	Build:No inputs were found in config file 'C:/Users/S T R I X/.nuget/packages/avalonia.web.blazor/0.10.15/contentFiles/any/net6.0/tsconfig.json'. 
Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["node_modules"]'.**	

I noticed that the project has a new file tsconfig.js and the content is

      {
        "compilerOptions": {
          "noImplicitAny": false,
          "noEmitOnError": true,
          "removeComments": false,
          "sourceMap": true,
          "target": "ES2020",
          "module": "ES2020",
          "outDir": "wwwroot"
        },
        "exclude": [
          "node_modules"
        ]
      }
</div>

**Comment by GaNacereddine** [comment]
Removing the contentFiles\any\net6.0\tsconfig.json file inside the nuget package folder fixes the issue, could you remove the file from the nuget package?

**Comment by LobsterUberlord** [comment]
The workaround for now is to exclude the `contentFiles` in the project referencing `Avalonia.Web.Blazor`:

```xml
<PackageReference Include="Avalonia.Web.Blazor" Version="$(AvaloniaWebBlazorVersion)">
    <IncludeAssets>all</IncludeAssets>
    <ExcludeAssets>contentFiles</ExcludeAssets>
</PackageReference>
```
