### ISSUE TITLE
CanResize has no effect in Linux

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#8329]
In Linux, I set Window.CanResize=False and it has no effect whatsoever. The window can still be resized.

Now I'm wondering... does Linux even allow non-resizable windows?

- OS: Linux (Garuda)
- Version: 0.10.15

**Comment by kekekeks** [comment]
When `CanResize=false` we set the appropriate flags in `_MOTIF_WM_HINTS`. Check if your window manager supports that been around for 30 years. For example KWin does.

**Comment by mysteryx93** [comment]
Window minimum size is respected. I use KDE Plasma.

**Comment by uthidata** [comment]
Additional info: CanResize="False" only fails if Width and Height are set.
Tested on Avalonia 11.0.2 and KDE Plasma

**Comment by timunie** [comment]
@uthidata interesting. Probably this can lead to a fix. Maybe you can check in source code if you can file a PR to fix it?

**Comment by uthidata** [comment]
@timunie I posted a PR. Just tested with setting Width and Height in axaml, in axaml.cs, with and without CanResize="False". All seems normal now. Is there anything else I could test?

**Comment by timunie** [comment]
@uthidata thank you 🙏 It's in review now by the experts in this area. So if anything is needed, the will let you know.

**Comment by timunie** [comment]
For Wayland, there is a PR #11546 by @affederaffe. Feel free to try it out and post your feedback there.

**Comment by uthidata** [comment]
@timunie It's been a month or so - is it going to get reviewed?

**Comment by timunie** [comment]
It is, but there are some blocking things on the wayland end iirc. I have to say I personally have no idea about Wayland at all, so I trust in the feedback of our experts here. So to sum it up, I cannot give you a due date yet. We hope to get it  merged in the 11.x time frame. All preparations that were needed to do so are done.
