### ISSUE TITLE
Text measurement with TextTrimming="CharacterEllipsis" are wrong

### ISSUE THREAD

**Issue by GaNacereddine** [AvaloniaUI/Avalonia#8334]
**Describe the bug**
We were using the nightly build 0.10.999-cibuild0020667-beta then switched to 0.10.999-cibuild0021055-beta. 

After this update we noticed that the text box with TextTrimming="CharacterEllipsis" is now trimming the text although there is enough available space to it to grow (width direction).  

![image](https://user-images.githubusercontent.com/33737454/173257305-c3aefe81-a3a9-44e2-9d1d-f1b73f4b668e.png)

this effect would disappear on a monitors with resolution
    - 1920 x 1080 (125% scaling) 
the effect will be noticed again on monitors with resolutions 
    - 1920 x 1080 (100% scaling)
    - 3840x2160 (150% scaling)

**Desktop (please complete the following information):**

- OS: Windows 11.

**Additional context**
we solved the issue (at least in our test machines) by inflating the finale size in ArrangeOverride

        protected override Size ArrangeOverride(Size finalSize)
        {
            var measuredSize = base.ArrangeOverride(finalSize.Inflate(new(1)));

            return measuredSize;
        }

**Comment by Gillibald** [comment]
I can't repro the issue with the information you gave me. Please try to reproduce it in the Sandbox or some other minimal project.
