### ISSUE TITLE
4K monitors are 200% scaled and display sizes differ under Windows and Linux.

### ISSUE THREAD

**Issue by ApaulMyLittleAirport** [AvaloniaUI/Avalonia#8346]
I have a 4K monitor with 200% scaling set under both Windows and Linux, but it can display normally under Windows, and the words displayed under Linux are very small.

**Comment by maxkatz6** [comment]
It's a known limitation of linux systems, see https://github.com/AvaloniaUI/Avalonia/issues/4826
