### ISSUE TITLE
Transparent GradientStops create a weird white effect

### ISSUE THREAD

**Issue by SlidyDev** [AvaloniaUI/Avalonia#8358]
**Describe the bug**
When trying to create a fake shadow effect by creating a linear gradient brush with a black and a transparent gradient stop, for some reason the gradient adds a bit of white to the center

**To Reproduce**

```xaml
<Rectangle HorizontalAlignment="Stretch" VerticalAlignment="Top" Height="20">
    <Rectangle.Fill>
        <LinearGradientBrush StartPoint="0%,0%" EndPoint="0%,100%">
            <GradientStop Color="Black" Offset="0"/>
            <GradientStop Color="Transparent" Offset="1"/>
        </LinearGradientBrush>
    </Rectangle.Fill>
</Rectangle>
```

**Expected behavior**
For the gradient to be normal

**Screenshots**
![image](https://user-images.githubusercontent.com/61495410/174441610-e6754d98-0062-44e2-a3f5-37d2da1c2e45.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 10.0.22000

**Comment by jp2masa** [comment]
I don't think this is a bug. Linear gradient is probably doing a linear interpolation between the colors (0, 0, 0, 1.0) and (255, 255, 255, 0) (transparent is defined as white with alpha = 0, [here](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Media/KnownColors.cs#L224)), so for example at 50% it's 0.5 * (0, 0, 0, 1.0) + 0.5 * (255, 255, 255, 0) = (127, 127, 127, 0.5) (some gray with alpha = 0.5). Note that changing the definition of transparent to be black would cause the same problem to all other colors, including white (which probably works as expected with this definition).

So, the correct solution would be for you to use a color built from `Black` RGB components and alpha = 0, which can't be done easily on XAML I think (unless you hardcode the components).

**Comment by SlidyDev** [comment]
Well, while it does work for the original WPF, your explanation does make sense. Either way, thanks a lot!

**Comment by SlidyDev** [comment]
> which can't be done easily on XAML I think

Actually, it's just `#00000000`
