### ISSUE TITLE
Cannot change the DataGridCell background color.

### ISSUE THREAD

**Issue by ApaulMyLittleAirport** [AvaloniaUI/Avalonia#8363]
**Describe the bug**
I tried to change the DataGridCell BorderBrus color with the axaml, but it didn't work ：
```
<Style Selector="DataGridCell /template/ Border#CellBorder">
<Setter Property="BorderBrush" Value="Green"/>
</Style>
```

app.axaml:
```
<FluentTheme Mode="Light" />
<StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Fluent.xaml"/>
```

**Comment by maxkatz6** [comment]
Have you set a BorderThickness?

**Comment by ApaulMyLittleAirport** [comment]
![image](https://user-images.githubusercontent.com/45100828/174715675-e22f0f4b-c151-433b-ac39-536ef72826dc.png)
	<Style Selector="DataGridCell:selected /template/ Border">
					<Setter Property="BorderThickness" Value="2"></Setter>
					<Setter Property="BorderBrush" Value="red"/>
				</Style>

but it didn't work...please...help.....

**Comment by maxkatz6** [comment]
In current 0.10.15 stable release there is no root border that you can style. See https://github.com/AvaloniaUI/Avalonia/blob/release/0.10.15/src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml#L95 . There is only a Grid where you can't set a border.

In current master branch, and nightly builds, there is actual border that can be styled https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml#L60

As a workaround with 0.10.15 you can copy this DataGridCell style from master branch and apply in your app.
