### ISSUE TITLE
ProgressBar ShowProgressText shows value of `Value` property, not % completion as it implies.

### ISSUE THREAD

**Issue by EricEzaM** [AvaloniaUI/Avalonia#8364]
**Describe the bug**
The expectation, due to the % sign at the end of the text in the progress bar, is that it will display the % completion of the progress bar taking into account the minimum and maximum values. It does not however. See the below two examples. I used the ControlCatalog for this example.

Min=0, Max=1, Slider Step = 0.01

https://user-images.githubusercontent.com/41730826/174540690-4a99bf4e-0769-4738-aa9c-128234d19827.mp4

Min=0, Max=1000, Slider Step = 10

https://user-images.githubusercontent.com/41730826/174540753-ce1bac61-90e3-464f-ae7b-4c3a2d18cc85.mp4

ShowProgressText does NOT show the % progress, but rather a rouded integer representation of the value.

**To Reproduce**

Create a progressbar with min != 0, or max != 100.

**Expected behavior**
The progress text should show the % completion, not the Value.

**Desktop (please complete the following information):**

- OS: WIN 10
- Version 0.10.15

**Comment by EricEzaM** [comment]
I agree, those options would be nice to have.

**Comment by timunie** [comment]
I am not a core member, so I can't judge the final solution though. Anyway, if I were you I'd do two things:
1. I'd have my VM to calculate the needed value and bind to that as a work around.
2. I'd do a PR with the solution I prefer and see if I get feedback on the proposal

**Comment by Takoooooo** [comment]
Fixed by https://github.com/AvaloniaUI/Avalonia/pull/8454
