### ISSUE TITLE
TextBox binding for Text updates value twice when changing selected text

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#838]
It should only once with final value.

![2017-01-06_20-26-34](https://cloud.githubusercontent.com/assets/2297442/21730110/7fa33f24-d44e-11e6-9715-0d23c0061c10.gif)

**Comment by grokys** [comment]
I can't reproduce this - I'm using `ReactiveHistory` from master and when i do what you are doing in you video (select the "s" of "start11" and press delete) the observable in `IObservableExtensions` is triggered only once. What am I doing wrong?

**Comment by wieslawsoltes** [comment]
@grokys
Select the "s" of "start11" and then do not press delete but press "x" instead.

**Comment by jkoritzinsky** [comment]
@wieslawsoltes is this still an issue?

**Comment by wieslawsoltes** [comment]
@jkoritzinsky Sorry for the late reply, but I had to convert project to latest Avalonia.

The issue is still there.

![2018-10-13_13-15-24](https://user-images.githubusercontent.com/2297442/46904800-344e0e80-ceea-11e8-9299-1bb6ccde17c7.gif)

**Comment by wieslawsoltes** [comment]
Code to repro:

https://github.com/wieslawsoltes/ReactiveHistory/tree/53eded1d7a51d03c3de036005826cb03d2a01959/samples/ReactiveHistorySample.Avalonia

https://github.com/wieslawsoltes/ReactiveHistory/blob/53eded1d7a51d03c3de036005826cb03d2a01959/src/ReactiveHistory/IObservableExtensions.cs#L37
