### ISSUE TITLE
Duplicate validation when using Mvvm Toolkit's ObservableValidator

### ISSUE THREAD

**Issue by stevemonaco** [AvaloniaUI/Avalonia#8397]
When using Mvvm Toolkit's (`CommunityToolkit.Mvvm` 8.0.0-preview4) source generators with DataAnnotations, the validation methods are called twice and the validation messages are shown twice. While I found workarounds for the duplicate display messages by not using the source generators, I cannot workaround the two validation calls. The Mvvm Toolkit validation is implemented (AFAIK) by taking DataAnnotations and then delivering them via `INotifyDataErrorInfo`.

Example:
```cs
[ObservableProperty]
[NotifyDataErrorInfo]
[MinLength(6)]
private string _testNotifyData = "notify";
```

**To Reproduce**
[Repro project](https://github.com/stevemonaco/AvaloniaDuplicateValidationRepro)

See screenshot for behavior for several sourcegen and non-sourcegen approaches.

See [example call stacks](https://github.com/stevemonaco/AvaloniaDuplicateValidationRepro/blob/master/AvaloniaDuplicateValidationRepro/TrimmedCallStack.txt) to see both Avalonia and Mvvm Toolkit call into `DataAnnotations.Validator.TryValidateProperty` when a single property change occurs. Avalonia goes through its `DataAnnotationsValidationPlugin`.

**Expected behavior**
A single validation error to be displayed and the validation method to be called only once.

**Screenshots**
![Duplicate validations shown](https://raw.githubusercontent.com/stevemonaco/AvaloniaDuplicateValidationRepro/master/AvaloniaDuplicateValidationRepro/validationimage.png)

**Desktop (please complete the following information):**

- OS: Win10
- Version 0.10.15

**Additional context**
I believe the CustomSetProperty and CustomValidateAfter cases show one validation error because Mvvm Toolkit's validation happens after `PropertyChanged` is responded to by Avalonia. Mvvm Toolkit will clear existing errors as shown [here](https://github.com/CommunityToolkit/dotnet/blob/main/CommunityToolkit.Mvvm/ComponentModel/ObservableValidator.cs#L649), but I have never seen multiple validation errors in Mvvm Toolkit's internal collections for any one property while debugging.

**Comment by maxkatz6** [comment]
Not sure if it's a bug. Neither in Avalonia nor CommunityToolkit.

CommunityToolkit assumes that framework won't support validation with attributes, so it does it by itself (using NotifyDataErrorInfo).
And Avalonia just supports both ways to validate - attributes and NotifyDataErrorInfo. 

In result, we have duplicated validation.

You can either remove [NotifyDataErrorInfo] attribute, so only [MinLength] will validate Avalonia app.
Or you can disable attribute validation in Avalonia completely by removing this plugin from `ExpressionObserver.DataValidators` list, [see this source code](https://github.com/AvaloniaUI/Avalonia/blob/14de358749596e0edc4ccc6aa7f5679fb8b94243/src/Avalonia.Base/Data/Core/ExpressionObserver.cs#L36).

**Comment by stevemonaco** [comment]
Thanks for the response, Max.

As per your suggestion, I have fixed the issue by adding the following configuration to the app startup logic in `OnFrameworkInitializationCompleted` before the initial window is created:

```cs
ExpressionObserver.DataValidators.RemoveAll(x => x is DataAnnotationsValidationPlugin);
```

Now, I get one validation call and one validation message as desired while maintaining the ability to write ViewModels in a View-neutral way. Thanks! I'm closing the issue.
