### ISSUE TITLE
Combobox throws excepiton when using DensityStyle Compact

### ISSUE THREAD

**Issue by AronHetLam** [AvaloniaUI/Avalonia#8401]
Using `<FluentTheme DensityStyle="Compact"/>` produces the following exception for each rendered Combobox:
```
Exception thrown: 'System.InvalidCastException' in Avalonia.Base.dll
[Binding]Binding produced invalid value for 'MinHeight' ('System.Double'): '24,24,24,24' ('Avalonia.Thickness')(Viewbox #27556864)
[Binding] Error in binding to 'Avalonia.Controls.Viewbox'.'MinHeight': 'Unable to convert object '24,24,24,24' of type 'Avalonia.Thickness' to type 'System.Double'.' (Viewbox #27556864)
```

There is no exepiton when using `DensityStyle="Normal"`

This causes empty combo boxes to be smaller than the 24 defined by the theme, and initial rendering of Comboboxes to be very slow.

**Expected behavior**
No exception, and Comboboxes displayed as in 2nd screenshot.

**Screenshots**
Result:
![image](https://user-images.githubusercontent.com/5564813/176036000-f7caf64c-5a73-4b1d-8e99-20d9e8772187.png)

How it should look (I set MinHeight to 24 in my axaml):
![image](https://user-images.githubusercontent.com/5564813/176036176-02761ced-cac5-4048-bb66-7d678dab2794.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- version 21H2
- Build 22000.739

**Comment by AronHetLam** [comment]
Might be that this should be `Double` instead of `Thickness`? 
https://github.com/AvaloniaUI/Avalonia/blob/67db0acac7b964100958686c2bae2fac3aa652bc/src/Avalonia.Themes.Fluent/DensityStyles/Compact.xaml#L18

**Comment by maxkatz6** [comment]
Yes, it should be Double
