### ISSUE TITLE
Little mistake in xaml causes too many build errors

### ISSUE THREAD

**Issue by yll690** [AvaloniaUI/Avalonia#8410]
My project basically does not use MVVM. It uses many named controls and little Bindings.

When I make a little mistake in xaml, like missing closing brace in binding, it produces hundreds of errors like `The name 'versionTB' does not exist in the current context`. But the actual error is `1>CSC : error AXN0002: XamlX.XamlParseException: Unexpected token None line 23，position 13`. **And not only the xaml with mistake but ALL xamls produce errors!** This makes it harder to find the actual problem.

So is there any way to continue compile other xamls when some of them have errors?

I use Visual Studio 2022 17.2.5.

**Comment by yll690** [comment]
My project is migrated from WPF so it relies on the generated fields to use the named controls.

**Comment by workgroupengineering** [comment]
You shuld add  [XamlNameReferenceGenerator ](https://www.nuget.org/packages/XamlNameReferenceGenerator/). For more dettails see https://github.com/AvaloniaUI/Avalonia.NameGenerator.

**Comment by yll690** [comment]
> You shuld add [XamlNameReferenceGenerator ](https://www.nuget.org/packages/XamlNameReferenceGenerator/). For more dettails see https://github.com/AvaloniaUI/Avalonia.NameGenerator.

No, I have referenced it.
Actually I have already finished migrating my project from WPF to Avalonia, and it works well. However if I delete a closing brace of binding, hundreds of errors will come.
