### ISSUE TITLE
Introduce DispatcherUnhandledException

### ISSUE THREAD

**Issue by jinek** [AvaloniaUI/Avalonia#8418]
**Is your feature request related to a problem? Please describe.**
Currently, we have to catch exceptions on event handler level to control an execution flow, thus duplicating same code all over the project.

**Describe the solution you'd like**
Anything similar to https://docs.microsoft.com/en-us/dotnet/api/system.windows.application.dispatcherunhandledexception?redirectedfrom=MSDN&view=windowsdesktop-6.0

**Additional context**
As an example of the problem, consider different parts of our application randomly throws PayToExecuteException() and we want to catch it to show a suggestion to pay to the user. In WPF we can subscribe to `DispatcherUnhandledException` and provide the logic once. In Avalonia, currently, we either have to catch the exception in each of the event handler, or replace the exception with `return`/`if` logic thus increasing the codebase.

**Comment by jinek** [comment]
> #5290

Thank you for the link. I've answered there: https://github.com/AvaloniaUI/Avalonia/issues/5290#issuecomment-1171805093

**Comment by jinek** [comment]
Relatively, this is wrong statement.
![image](https://user-images.githubusercontent.com/10516222/176801095-a3cc1487-9393-41a5-ae4f-80ff570c15a0.png)

In fact one can know whether exception has been handled correctly. In fact there is no difference when catch exception on first level up the stack or second or third.
If Avalonia has issues properly handling the exceptions, that should be addressed and fixed, for example, with try/finally constructions how they are intended to be.
Absence of such handler in the loop assumes that we have to duplicate same catch block to several places.

As one more example, consider that we have introduced OperationDeclinedException() which we throw whenever an user cancel dialogs, operations etc.

**Comment by yll690** [comment]
In my projects, I listen `DispatcherUnhandledException` but never mark it handled. I just produce some tips and logs. When use Avalonia, I listen the `AppDomain.UnhandledException` instead.

If the exception only indicate some user operation is failed, we can actually give user a tip and ignore them. In this case, I defined a custom implement of `ICommand` and handle exception in it.

**Comment by jinek** [comment]
> If the exception only indicate some user operation is failed, we can actually give user a tip and ignore them. 

I see your point. The only note from me, is that it's not "ignore". What you described is exactly the process of recovering from the exception. This is normal behavior described by the fundamental c# guidelines.

**Comment by alexhelms** [comment]
> In my projects, I listen `DispatcherUnhandledException` but never mark it handled. I just produce some tips and logs. When use Avalonia, I listen the `AppDomain.UnhandledException` instead.
> 
> If the exception only indicate some user operation is failed, we can actually give user a tip and ignore them. In this case, I defined a custom implement of `ICommand` and handle exception in it.

This is how I also use `DispatcherUnhandledException` in WPF. I believe the user experience of an unhandled exception where the application just abruptly exits is worse than if I was able to intercept the impending crash and at least attempt to show a message box or something that indicated something went wrong before the process has exited. Obviously the exception should be caught somewhere down the stack, but for a new bug where an exception gets through IMO using `DispatcherUnhandledException` to at least informing the user that wasnt supposed to happen.
