### ISSUE TITLE
Windows: bogus font size on first rendered control

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#8434]
Application runs perfectly fine in Linux. On Windows, however, the first control gets displayed with bogus font size.

Win-x64
[![win-x64.png](https://i.postimg.cc/T1NzXX1g/win-x64.png)](https://postimg.cc/ctY9Q2QL)

Win-x86
[![win-x86.png](https://i.postimg.cc/05tRS7nj/win-x86.png)](https://postimg.cc/ThW4MLZv)

- OS: Windows 10 (in VM, tried with and without GPU passthrough, same)
- Version 0.10.15

**Comment by timunie** [comment]
Is the sample you have shown somewhere available?

**Comment by mysteryx93** [comment]
[Published version is here](https://mega.nz/file/vF4UzTKA#3XNGPUMD5OOp_hBzoau9r_URrbanl2uFdUBUBUpDsOk)

[Source code is here](https://github.com/mysteryx93/NaturalGroundingPlayer/tree/master/Player432hz)

I did some more testing. It happens in debug mode too, when I show the About window on startup. It's the popup on startup that seems to be causing the problem on Windows: the first control of either the background or foreground window gets the wrong font rendering.

**Comment by maxkatz6** [comment]
FontSize is inherited property, but it should be set on a each window. Unless you have your own set of window styles.

**Comment by mysteryx93** [comment]
Adding `await Task.Delay(1)` before showing the popup solved the problem (which gets called on ``Opened`` event)

    public ICommand InitWindow => _initWindow ??= ReactiveCommand.CreateFromTask(InitWindowImpl);
    private ICommand? _initWindow;
    private async Task InitWindowImpl()
    {
        if (_settings.Value.ShowInfoOnStartup)
        {
            await Task.Delay(1).ConfigureAwait(true);
            await ShowAboutImplAsync().ConfigureAwait(false);
        }
    }

**Comment by timunie** [comment]
@maxkatz6 if I understood correctly, only the very first control has a wrong font size

**Comment by maxkatz6** [comment]
CC @mysteryx93 @Gillibald is this still an issue?
