### ISSUE TITLE
Automatically disable buttons/menu items when bound command is not found.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#846]
Sometimes it's useful to bind a button/menu item to a command that may not be present in the current view, e.g.:

```
<Window>
    <Menu>
        <MenuItem Header="Save" Command="{Binding CurrentDocument.Save}"/>
    </Menu>
</Window>

```

In this case, when `CurrentDocument` is null, the Save menu item needs to be disabled.

It should be possible to disable the control automatically when a binding error is received on the `Command` property.

**Comment by thomaslevesque** [comment]
> It should be possible to disable the control automatically when a binding error is received on the Command property.

Is the fact that the binding returns `null` considered an error? I'm noticing a strange behavior, and I think it could be related to this feature.

I have a dialog window with dynamic buttons, bound to a list of `DialogButton` (basically, a viewmodel for a button):

```csharp
    public class DialogButton
    {
        public string Text { get; set; } = string.Empty;
        public bool? DialogResult { get; set; }
        public bool IsDefault { get; set; }
        public bool IsCancel { get; set; }
        public ICommand? Command { get; set; }
        public object? CommandParameter { get; set; }
    }
```
The buttons are displayed like this in an `ItemsControl`
```xaml
                <DataTemplate DataType="{x:Type dlg:DialogButton}">
                    <Button Classes="dialogButton"
                            Content="{Binding Text}"
                            IsDefault="{Binding IsDefault}"
                            IsCancel="{Binding IsCancel}"
                            Command="{Binding Command}" 
                            CommandParameter="{Binding CommandParameter}"
                            Click="DialogButton_Click"/>
                </DataTemplate>
```

For some `DialogButton`s, the `Command` property is null. This is normal behavior, and in this case the click should be handled by the `DialogButton_Click` handler. This works fine in WPF, but in Avalonia the button remains disabled if the command is null.

Is there a way to suppress this behavior, and just leave the button enabled if the command binding returns null?

**Comment by thomaslevesque** [comment]
Found a workaround: just add `FallbackValue={x:Null}` on the binding.
That said, I think it shouldn't be necessary. The fact that the binding returns a null value shouldn't be an error; null is a valid value for the `Command` property.
