### ISSUE TITLE
Data Grid - Wrong arrows direction

### ISSUE THREAD

**Issue by KrzysztofDusko** [AvaloniaUI/Avalonia#8476]
**Describe the bug**
see screenshot

**To Reproduce**

1. Run sample from maseter
2. Go to data grid sample
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/69449360/178132667-bdbfae04-da99-402d-ba9d-c5ab211c64b6.png)
(should be)
![image](https://user-images.githubusercontent.com/69449360/178132708-4198dc80-65f2-46ff-8f1a-3bae508a8337.png)

**Desktop (please complete the following information):**
- OS: Windows 11
- Version current master

**Comment by timunie** [comment]
@KrzysztofDusko I've a PR for this. Can you double-check if it's what you requested? See #8493

**Comment by KrzysztofDusko** [comment]
@timunie thanks, PR is perfect
