### ISSUE TITLE
ArgumentNullException in Avalonia.Rendering.SceneGraph.SceneBuilder.Update

### ISSUE THREAD

**Issue by agillet76** [AvaloniaUI/Avalonia#8485]
**Describe the bug**
We are experiencing very sporadic unhandled exceptions that would crash our application.
The exceptions can happened in a few seconds to a few hours of running the application.
Our test application  is displaying a set of Livechart with data refresh at 20Hz
It's mimic displaying sensors data (temperature/pressure value) from devices.

The first exception seems to be fully due to Avalonia, the second one seems to be due to the combination of Avalonia and using LiveChart.

The exceptions are:
![image](https://user-images.githubusercontent.com/92173569/178321571-bb272106-a085-4777-a70e-46c2e11fce8a.png)

and 

![image](https://user-images.githubusercontent.com/92173569/178321597-65c77af7-a65a-4997-97f5-9906a0dea204.png)

**To Reproduce**
We have create a sample application to reproduce the issue.
https://github.com/agillet76/livechart-avalonia-crash

Start the application and wait until the unhandled exception is thrown

**Expected behavior**
The application to run without crashing due to unhandled exceptions

**Desktop (please complete the following information):**

- OS: Windows 10 , .net 6
- Version avalonia 0.10.16   liveChart 2.0.0-beta300

Any help or advice to address the error is greatly appreciate.

**Comment by portkiller** [comment]
@agillet76 I have the same problem. Have you found a solution?
