### ISSUE TITLE
Best way to render 3D

### ISSUE THREAD

**Issue by mblack101** [AvaloniaUI/Avalonia#8506]
I have an application I'm writing that needs to display 3D objects inside an Avalonia control (custom control?). This app needs to run on Windows AND linux (Raspbery Pi 4). My question is more about which package to use that will cause the least pain to implement. I don't care if it's Vulkan or OpenGL (or something else really) I just need it to run on both platforms. 

Any help on this would be greatly appreciated. :)

**Comment by maxkatz6** [comment]
See https://github.com/AvaloniaUI/Avalonia/issues/9925
It's now possible to integrate directx and vulkan as well. Samples here https://github.com/AvaloniaUI/Avalonia/tree/master/samples/GpuInterop
Available in nightly, also will be part of 11.0-preview5 soon.

**Comment by osamakawish** [comment]
Some of that code in the sample seems outdated.

In MainWindow.axaml.cs:

```cs
public MainWindow()
    {
        InitializeComponent();
        this.AttachDevTools();
        // Renderer.Diagnostics does not exist:
        Renderer.Diagnostics.DebugOverlays = RendererDebugOverlays.Fps;
    }
```

Here's the documentation for [IRenderer](https://reference.avaloniaui.net/api/Avalonia.Rendering/IRenderer/) (the type of Renderer) and it also contains no Diagnostics member.

I didn't check for any other code that may also not exist after this.

**Comment by abenedik** [comment]
You can use [Ab4d.SharpEngine](https://www.ab4d.com/SharpEngine.aspx). It is an easy to use 3D rendering engine with all the features for engineering, technical, scientific, architectural or any other 3D graphics use case. It uses the Vulkan API and can work on Windows, Linux, macOS, Android and browser (in browser WebGL is used). It also has great Avalonia interop, so Avalonia controls can be rendered on top of the 3D scene. The library is commercial, but can be used for free for open source projects. Check out the [samples project](https://github.com/ab4d/Ab4d.SharpEngine.Samples) for Avalonia.

Disclaimer:
I am the author of the Ab4d.SharpEngine library.
