### ISSUE TITLE
Embedded WinForms or WPF windows are displayed separately from the parent window

### ISSUE THREAD

**Issue by npolyak** [AvaloniaUI/Avalonia#8517]
I am trying to embed a WinForms or WPF control into Avalonia. Everything worked fine in 0.10.13 version of Avalonia, but starting with 0.10.14 version and till now, I am getting a separate window for the Control.

It is a bit urgent for me. 

Thanks

**Comment by npolyak** [comment]
[NP.Demos.EmbedWinFormsSample.zip](https://github.com/AvaloniaUI/Avalonia/files/9116011/NP.Demos.EmbedWinFormsSample.zip)

**Comment by maxkatz6** [comment]
Add "app.manifest" file with proper suppoeredOS items.

![image](https://user-images.githubusercontent.com/3163374/179115560-fa5438c3-3a1f-4084-8641-59c1b43bf8c8.png)

**Comment by npolyak** [comment]
can you give me a sample of the manifest?

**Comment by npolyak** [comment]
Thanks Max, it really worked!

**Comment by npolyak** [comment]
adding the manifest really helped.
