### ISSUE TITLE
Implement NavigationDirection.Down/Up/Right/Left

### ISSUE THREAD

**Issue by jinek** [AvaloniaUI/Avalonia#8554]
`KeyboardNavigationHandler` only supports focusing with values `NavigationDirection.Next`/`Previous`, but throwing `NotSupportedException` for Down/Up/Right/Left.

Do we have any discussion going on about that?

As I see it's enough to enumerate everything focusable within same visual root and pickup the control which fits in coodrinates/geometry confitions.
I can take it for implementation.

**Comment by jinek** [comment]
I have tried this experimental code, it somehow works:
https://github.com/jinek/Consolonia/pull/79/files#diff-87edd463c680c3814584dca5b6b1069eea554e8f412169d00db01865270f0066R23

**Comment by maxkatz6** [comment]
Yes, there are discussions about it, https://github.com/AvaloniaUI/Avalonia/issues/7607

Custom implementation of IKeyboardNavigationHandler should work fine with 0.10 avalonia as well.
