### ISSUE TITLE
Unicode Characters display properly in TextBlock but not TextBox

### ISSUE THREAD

**Issue by Mbucari** [AvaloniaUI/Avalonia#8557]
**Describe the bug**

**To Reproduce**

Create a TextBlock using the Arial font (Normal), with Text = "＂＜＞✱？⏐"
All characters display correctly. 

Change the TextBlock to a TextBox, and none of the characters display correctly.

**Screenshots**

![Unicode TextBlock](https://user-images.githubusercontent.com/37587114/180084428-67b668ac-6fae-4ea7-8de1-81fbfef6751f.png)

![Unicode TextBox](https://user-images.githubusercontent.com/37587114/180084463-7f7b299f-848a-41ca-a529-7ff39cc2e51d.png)

**Desktop**

- OS: Windows 10
- Version 0.10.16

**Comment by jmacato** [comment]
Unicode support is not ported over in stable releases (0.10.x), it's on the nightly builds. Please see https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed for more info.
