### ISSUE TITLE
Start app without windows?

### ISSUE THREAD

**Issue by MonkAlex** [AvaloniaUI/Avalonia#857]
I want create ask dialog and then do any action. Show\ShowDialog methods only asynchronic, no idea, how to do it and dont close app. Where "ShutdownMode" analog with "OnExplicitShutdown" value from WPF?

```
    static void Main(string[] args)
    {
      InitializeLogging();
      AppBuilder.Configure<App>()
          .UsePlatformDetect()
          .SetupWithoutStarting();

      var dialog = new SimpleDialog();
      // Cannot await, Main not async
      var dialogResult = await dialog.ShowDialog();
      ...
    }
```

**Comment by wieslawsoltes** [comment]
@MonkAlex Try this:
```C#
static void Main(string[] args)
{
    var app = new Application();
    AppBuilder.Configure(app)
        .UsePlatformDetect()
        .SetupWithoutStarting();

    var dialog = new SimpleDialog();
    dialog.Show();
    app.Run(dialog);
}
```

**Comment by MonkAlex** [comment]
@wieslawsoltes its work, but i want dialog with custom buttons, need return it from ShowDialog method.

**Comment by MonkAlex** [comment]
Work this realization, but normal this or not, no idea:

```
    public virtual IButton Show()
    {
      CancellationTokenSource source = new CancellationTokenSource();
      Closed += (sender, args) => source.Cancel();

      var dialog = new Window(this);
      dialog.Closed += (sender, args) => Closed?.Invoke(this, EventArgs.Empty);
      dialog.Show();
      Dispatcher.UIThread.MainLoop(source.Token);
      return dialog.ResultButton;
    }
```

MainLoop code hard for me, don't know, can i use it or not.

**Comment by MonkAlex** [comment]
Ubuntu mono give some error:

> user@userpc:~/CommonLibraries/Dialogs.Avalonia.Example/bin/Debug$ sudo mono Dialogs.Avalonia.Example.exe
> 
> Unhandled Exception:
> System.TypeLoadException: Could not load type 'Avalonia.Input.InputManager' from assembly 'Avalonia.Input, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null'.
>   at Avalonia.Controls.AppBuilder.Setup () [0x0003f] in <167c19a8383b4f95a2847335e6aa9029>:0 
>   at Avalonia.Controls.AppBuilder.SetupWithoutStarting () [0x00000] in <167c19a8383b4f95a2847335e6aa9029>:0 
>   at Dialogs.Avalonia.Example.App.Main (System.String[] args) [0x00016] in <575b80f5b8524e1f98c01702b6072213>:0 
> [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'Avalonia.Input.InputManager' from assembly 'Avalonia.Input, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null'.
>   at Avalonia.Controls.AppBuilder.Setup () [0x0003f] in <167c19a8383b4f95a2847335e6aa9029>:0 
>   at Avalonia.Controls.AppBuilder.SetupWithoutStarting () [0x00000] in <167c19a8383b4f95a2847335e6aa9029>:0 
>   at Dialogs.Avalonia.Example.App.Main (System.String[] args) [0x00016] in <575b80f5b8524e1f98c01702b6072213>:0 
> user@userpc:~/CommonLibraries/Dialogs.Avalonia.Example/bin/Debug$ ls
> Avalonia.Animation.dll        Avalonia.Diagnostics.dll   Avalonia.Interactivity.dll    Avalonia.ReactiveUI.dll      Dialogs.Avalonia.dll              Dialogs.Interfaces.dll
> Avalonia.Base.dll             Avalonia.Direct2D1.dll     Avalonia.Layout.dll           Avalonia.SceneGraph.dll      Dialogs.Avalonia.dll.mdb          Dialogs.Interfaces.dll.mdb
> Avalonia.Cairo.dll            Avalonia.Gtk.dll           Avalonia.Logging.Serilog.dll  Avalonia.Styling.dll         Dialogs.Avalonia.Example.exe      Serilog.dll
> Avalonia.Controls.dll         Avalonia.HtmlRenderer.dll  Avalonia.Markup.dll           Avalonia.Themes.Default.dll  Dialogs.Avalonia.Example.exe.mdb  Serilog.FullNetFx.dll
> Avalonia.DesignerSupport.dll  Avalonia.Input.dll         Avalonia.Markup.Xaml.dll      Avalonia.Win32.dll           Dialogs.Avalonia.exe.mdb
>

**Comment by Gillibald** [comment]
I will introduce ShutdowmMode soon. That is next in my list.

**Comment by jkoritzinsky** [comment]
Has this been fixed by #1662?

**Comment by Gillibald** [comment]
ShutdownMode is fully implemented so it should be fixed.

**Comment by MonkAlex** [comment]
I do on start
```
      BuildAvaloniaApp().SetExitMode(ExitMode.OnExplicitExit).SetupWithoutStarting();
```
Then try to create and show window (remove `Dispatcher.UIThread.MainLoop(source.Token);` after show):
```
      using (DialogTokenSource = new CancellationTokenSource())
      {
        var dialog = new DialogWindow(this);
        dialog.Closed += (sender, args) => CloseImpl();
        DialogTokenSource.Token.Register(() => Dispatcher.UIThread.InvokeAsync(() => dialog.Close()));
        dialog.Show();

        return dialog.ResultButton;
      }
```

And app closed.

How to do it? ~_~

**Comment by MonkAlex** [comment]
https://github.com/MonkAlex/CommonLibraries/tree/exitmode
Simple app, try to use exit mode in last commit.

**Comment by MonkAlex** [comment]
In WPF i can just run app and do nothing. I think, `OnExplicitExit` must enable this behavior.

And, i can run MainLoop without ExitMode configuration, what it changed?

**Comment by Gillibald** [comment]
You don't run the Application anywhere. That wouldn't work with WPF either.
