### ISSUE TITLE
TrayIcon/NativeMenuItem Header as DataBinding  does not update on binded data change

### ISSUE THREAD

**Issue by KuromeSan** [AvaloniaUI/Avalonia#8570]
**Describe the bug**
I have a NativeMenuItem with binding as so  <NativeMenuItem Header="{Binding swearFilterHeader}">
when i change the value of swearFilterHeader, programmatically, it does not update the header in the menu, 

**To Reproduce**
i have the following TrayIcon;
```
  <TrayIcon.Icons>
    <TrayIcons>
      <TrayIcon Icon="/icon.ico" ToolTipText="HI1 Server">
        <TrayIcon.Menu>
          <NativeMenu>
			<NativeMenuItem Header="Chat">
			  <NativeMenu>
				<NativeMenuItem Header="{Binding swearFilterHeader}" Command="{Binding toggleSwearFilter}"/>
			  </NativeMenu>
			</NativeMenuItem>
          </NativeMenu>
        </TrayIcon.Menu>
      </TrayIcon>
    </TrayIcons>
  </TrayIcon.Icons>
```

and the following code for it;
```

public HispViewModel()
{
	swearFilterHeader = (ConfigReader.BadWords ? "Disable" : "Enable") + " Swear Filter";

	toggleSwearFilter = MiniCommand.Create(() =>
	{
		bool enab = !ConfigReader.BadWords;
		ServerStarter.ModifyConfig("enable_word_filter", enab.ToString().ToLowerInvariant());
		ConfigReader.BadWords = enab;
		swearFilterHeader = (ConfigReader.BadWords ? "Disable" : "Enable") + " Swear Filter";
	});
}

public String swearFilterHeader { get; set; }

```

however only the first swearFilterHeader = (ConfigReader.BadWords ? "Disable" : "Enable") + " Swear Filter"; 
when its first initialized actually works, after executing the toggleSwearFilter command it should change it to say "Disable swear filter" or "Enable swear filter" respectively in the tray icons menus.
however instead, the actual menu item stays on whatever it was before .

**Expected behavior**
The text actually change when i change the value of what its bound too.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 22H2 (OS BUILD 22598.200)

**Comment by maxkatz6** [comment]
What Avalonia version are you using?
I also don't see INotifyPropertyChanged implementation on your view model, swearFilterHeader is just a simple property.

**Comment by KuromeSan** [comment]
Avalonia, Avalonia.Desktop, Avalonia.Diagnostics 0.10.17 
XamlNameReferenceGenerator 1.3.4


as for INotifyPropertyChanged, its implemented inside ViewModelBase its practily just copied right from the sample;
```namespace MiniMvvm
{
    public class ViewModelBase : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        protected bool RaiseAndSetIfChanged<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
        {
            if (!EqualityComparer<T>.Default.Equals(field, value))
            {
                field = value;
                RaisePropertyChanged(propertyName);
                return true;
            }
            return false;
        }


        protected void RaisePropertyChanged([CallerMemberName] string propertyName = null)
            => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }```

**Comment by maxkatz6** [comment]
```
public String swearFilterHeader { get; set; }
```
should be
```
private String _swearFilterHeader;
public String swearFilterHeader
{
    get => swearFilterHeader;
    set => RaiseAndSetIfChanged(ref swearFilterHeader, value);
}

```

**Comment by KuromeSan** [comment]
Hey it works now! thanks
