### ISSUE TITLE
Acrylic doesn't work for published apps

### ISSUE THREAD

**Issue by PerfectlyFineCode** [AvaloniaUI/Avalonia#8579]
**Describe the bug**
Acrylic doesn't work when the app has been published, it only works when debugging.

**To Reproduce**

1. Create a new Avalonia MVVM project
2. Set XAML to:
```xml
<Window ...
        TransparencyLevelHint="AcrylicBlur"
        Background="Transparent">

    <Panel>
        <ExperimentalAcrylicBorder  IsHitTestVisible="False">
            <ExperimentalAcrylicBorder.Material>
                <ExperimentalAcrylicMaterial TintColor="Black"
                                             TintOpacity="0.5"
                                             MaterialOpacity="0.65"
                                             BackgroundSource="Digger"/>
            </ExperimentalAcrylicBorder.Material>
        </ExperimentalAcrylicBorder>
    </Panel>
</Window>
```

**Expected behavior**
Acrylic should work for both debug AND published application.

**Screenshots**
![image](https://user-images.githubusercontent.com/70201838/180614663-55b25d75-41b9-43fb-ab67-99c5ddd0ce44.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 21H2
- OS build: 22000.778

**Comment by kekekeks** [comment]
You probably need an application compatibility manifest.

**Comment by maxkatz6** [comment]
Works as expected without manifest. But yes, please try with it.
Avn 0.10.17
Win 25163.1000

![image](https://user-images.githubusercontent.com/3163374/180621484-e26695fe-ce9e-46c8-8fd2-ab960003e7c5.png)

**Comment by maxkatz6** [comment]
It works with and without UseWindowsUIComposition, but without it's very slow and unsupported.
```csharp
public static AppBuilder BuildAvaloniaApp()
    => AppBuilder.Configure<App>()
        .UsePlatformDetect()
        .With(new Win32PlatformOptions
        {
            UseWindowsUIComposition = true // it's enabled by default
        })
        .LogToTrace();
```

**Comment by PerfectlyFineCode** [comment]
[AcrylicBugTest.zip](https://github.com/AvaloniaUI/Avalonia/files/9175427/AcrylicBugTest.zip)
Anything I'm missing?
Added compatability manifest, didn't work.
Tried changing UseWindowsUIComposition to true, didn't work.

Tried the published app on Windows Sandbox, no acrylic there.

**Comment by timunie** [comment]
You're using v0.10.14. If I update to 0.10.17 it works for me

**Comment by PerfectlyFineCode** [comment]
> You're using v0.10.14. If I update to 0.10.17 it works for me
Unfortunately, no change for me.

![image](https://user-images.githubusercontent.com/70201838/180654553-c8fa77aa-181f-4919-8e15-7ae6841534c5.png)

**Comment by timunie** [comment]
How do you publish?

**Comment by timunie** [comment]
Is there any issue probably AOT or trimming?

**Comment by PerfectlyFineCode** [comment]
> How do you publish?

Tried with all the options.

![image](https://user-images.githubusercontent.com/70201838/180654803-3704e1cd-b702-435b-b70c-b27f8152bb4d.png)

**Comment by timunie** [comment]
have you tried x64?

**Comment by PerfectlyFineCode** [comment]
[win-x64.zip](https://github.com/AvaloniaUI/Avalonia/files/9176105/win-x64.zip)
published files, does Acrylic work for you?
For me it doesn't.

**Comment by timunie** [comment]
Let me double-check tomorrow. 

From your screen shots I see you use the UI to publish. I wonder if it's a different if you do it by command line.

**Comment by timunie** [comment]
from command line: 

![image](https://user-images.githubusercontent.com/47110241/180660133-ebc61dde-8a05-4682-8e3f-44052fb11b2a.png)

from UI:

![image](https://user-images.githubusercontent.com/47110241/180660177-80c11e97-051b-488f-9eba-23d7e4dce091.png)


Don't ask me why. I have no idea. I only remembered, I had a similar issue in WPF.

**Comment by maxkatz6** [comment]
@PerfectlyFineCode acrylic in your build works for me, but I see that winui composition wasn't enabled. Even though I decompiled it and saw WinUIComposition=true in your code, it wasn't applied in runtime. Acrylic without winui composition is very buggy and might not work on every OS. 

I wonder if some native dependencies are missed depending on a way how you build it.
You might need to try to build it with runtime identifier win7-x64 instead of win-x64.

**Comment by maxkatz6** [comment]
Might be a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/6028 then

**Comment by PerfectlyFineCode** [comment]
> @PerfectlyFineCode acrylic in your build works for me, but I see that winui composition wasn't enabled. Even though I decompiled it and saw WinUIComposition=true in your code, it wasn't applied in runtime. Acrylic without winui composition is very buggy and might not work on every OS.
> 
> I wonder if some native dependencies are missed depending on a way how you build it. You might need to try to build it with runtime identifier win7-x64 instead of win-x64.

I apologize for a late answer, I just checked now and it is exactly that issue.
Works fine now for me when I compiled it as win7-x64 using CLI instead of VS's GUI.

**Comment by PerfectlyFineCode** [comment]
so duplicate of #6028

**Comment by timunie** [comment]
> I apologize for a late answer

all fine. It's always nice to get a feedback. :+1:
