### ISSUE TITLE
Get rid of Microsoft.CodeAnalysis.* reference

### ISSUE THREAD

**Issue by hez2010** [AvaloniaUI/Avalonia#8582]
Avalonia is currently having Microsoft.CodeAnalysis.* dependencies which are useless and introducing ~10mb size bloating (even with the help of trimming). 
Manually removing those DLLs after publishing doesn't prevent the app from running . 
This kind of dependencies should be removed.

**Comment by kekekeks** [comment]
Build your project in Release configuration. Roslyn is required for [Avalonia.Diagnostics](https://www.nuget.org/packages/Avalonia.Diagnostics) package that [is referenced in Debug configuration in templates](https://github.com/AvaloniaUI/avalonia-dotnet-templates/blob/47391d08335d5f4c3552327335240e153f04d825/templates/csharp/app/AvaloniaAppTemplate.csproj#L24)
