### ISSUE TITLE
Text wrapping not working

### ISSUE THREAD

**Issue by nekdan** [AvaloniaUI/Avalonia#8593]
**Describe the bug**
Text wrapping does not work correctly in ScrollViewer, when the text is written in several languages. 
Property `TextWrapping="Wrap"` in TextBlock of the ScrollViewer component. 

**To Reproduce**

```
          <ScrollViewer
		AllowAutoHide="False"
                HorizontalScrollBarVisibility="Disabled"
                VerticalScrollBarVisibility="Auto">
                <TextBlock
                      FontSize="16"
                      Text="{Binding SelectedItem.Description}"
                      TextWrapping="Wrap" />
           </ScrollViewer>
```
Where `SelectedItem.Description` contains text on russian and english languages.
See error on screenshot.
And there are non-breaking spaces (alt+255) in the text, and in this case they also do not work.

**Expected behavior**
The hyphenation should be by words, not by letters.

**Screenshots**
![Screenshot_11](https://user-images.githubusercontent.com/7727797/180750827-7758fa6e-fef6-4fde-a515-21c85c69b17b.png)

**Desktop (please complete the following information):**

- OS: Windows 11 21H2
- Version Avalonia: 0.10.16

**Comment by timunie** [comment]
@nekdan can you maybe try the same text with latest prerelease or in ControlCatalog? There were many text processing improvements recently for v11.0.

Hint: Don't update in your App as there are some breaking changes in current master. 

How to get prerelease: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

**Comment by rabbitism** [comment]
I think this is fixed in nightly build.

**Comment by maxkatz6** [comment]
Closing as fixed in nightly
