### ISSUE TITLE
TextBox control does not handle Key.Enter for Key.Down correctly

### ISSUE THREAD

**Issue by PumpkinPaul** [AvaloniaUI/Avalonia#860]
In the OnKeyDown(KeyEventArgs e) method for Avalonia.Controls.TextBox, Key.Enter is always handled no matter what the setting of 'AcceptsReturn' is - this means that if a KeyDown handler is added to a specific instance of a TextBox, the handler never receives the event for the enter key.

I would have expected it to behave similar to Key.Tab

e.g.

`
    if (AcceptsReturn)
    {
        HandleTextInput("\r\n");
    }
    else
    {
        base.OnKeyDown(e);
        handled = false;
    }
    break;`

**Comment by danwalmsley** [comment]
Are you on Windows or Linux?

**Comment by PumpkinPaul** [comment]
Sorry, missed this - I was testing on Windows

**Comment by grokys** [comment]
Fixed by https://github.com/AvaloniaUI/Avalonia/pull/1357
