### ISSUE TITLE
Custom NativeControlHost throw System.InvalidOperationException

### ISSUE THREAD

**Issue by DmitryVZuev** [AvaloniaUI/Avalonia#8609]
**Describe the bug**
When creating custom control inherited from NativeControlHost throw

**System.InvalidOperationException: "Unable to create child window for native control host. Application manifest with supported OS list might be required."**

Seen on LibVLCSharp.AvaloniaUI

- OS: . Windows 10
- Version 0.10.17

**Comment by kekekeks** [comment]
You need [an application compatibility manifest with supportedOS section](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#supportedos).

An example can be found here: https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog.NetCore/app.manifest
