### ISSUE TITLE
ComboBox ignoring IsEnable binding changes

### ISSUE THREAD

**Issue by ClumsyDerp** [AvaloniaUI/Avalonia#8620]
**Describe the bug**

When specific text is entered into a `TextBox`, I want to enable/disable a `ComboBox` based on the `TextBox`'s content. For that purpose I created an `event` on `KeyUp` which calls the VMs function to alter the `IsEnable` variable, that's bound to the `ComboBox`'s `IsEnabled` property.

The bool flip is ignored by the `ComboBox`.

My approach may be faulty but it appeared to make the most sense as commands cannot be bound directly to events yet, from what I could gather.

**To Reproduce**

1. Create a MVVM Project
2. MainWindow.axaml:
```
    <Grid ColumnDefinitions="Auto" RowDefinitions="Auto" Margin="4">
        <StackPanel Grid.Row="0" Grid.Column="0" Orientation="Horizontal">
            <TextBox Margin="0,20,0,0" Width="300" MaxWidth="300" Height="25" Text="{Binding TextBoxContent, Mode=TwoWay}" Watermark="Enter abc to disable dropdown" KeyUp="OnTextBoxKeyUp"/>
            <ComboBox Margin="4,20,0,0" SelectedItem="{Binding SelectedDropDownItem}" Items="{Binding DropDownContent}" IsEnabled="{Binding DropDownIsEnabled}"/>
        </StackPanel>
    </Grid>
```
3. MainWindow.axaml.cs
```
private MainWindowViewModel? SpecificViewModel => DataContext as MainWindowViewModel;

private void OnTextBoxKeyUp(object? sender, KeyEventArgs e)
{
    SpecificViewModel.OnTextBoxContentChange();
}
```
4. MainWindowViewModel.cs
```
public MainWindowViewModel()
    {
        DropDownContent = new ObservableCollectionExtended<string> { "Item1", "Item2", "Item3" };
        SelectedDropDownItem = DropDownContent.First();
        DropDownIsEnabled = true; //Init with false does disable the ComboBox
    }

    public string TextBoxContent { get; set; }
    public IObservableCollection<string> DropDownContent { get; }

    public string SelectedDropDownItem { get; set; }

    public bool DropDownIsEnabled { get; private set; }

    public void OnTextBoxContentChange()
    {
        DropDownIsEnabled = TextBoxContent != "abc"; //Y U NO WORK?
    }
```

**Expected behavior**
ComboBox should be disabled if the TextBox Input criteria is fulfilled and (re)enable itself when it is not.

**Desktop (please complete the following information):**

- OS: Linux; EndeavourOS
- NuGet Version 0.10.17

**Additional context**
Can provide a somewhat minimalist MVVM project, should the code snippets not be sufficient.

Cheers.

**Comment by ClumsyDerp** [comment]
Went ahead and tested a `Dispatcher.UIThread.Post()` and `InvokeAsync()` wrapping in both the event handler and the execution method (not simultaneously though), but the behavior persists.

I thought that due to an event triggering the evaluation method a threading issue may be at work.

**Comment by timunie** [comment]
You're missing SetAndRaiseIfChanged in your view model. Your vm needs to inform the ui if a property changed.

**Comment by ClumsyDerp** [comment]
The manual raising of `RaiseAndSetIfChange()`, as suggested, seems to have done the trick.

Admittedly though, it feels slightly icky to have a backing field for the purpose in question but things could be worse ;)

Rather than a bug I suspect it's more of a misunderstanding/misuse on my side.

Feel free to reopen insofar I've ever had any valid point, otherwise consider it closed.

Thanks.

**Comment by timunie** [comment]
All fine, you are welcome 😄. We were all beginners one day. 

I'll add a tutorial to the docs in the future to explain the MVVM thing better.

**Comment by ClumsyDerp** [comment]
Most of my actual project, not notably larger than the sample but a tad anyway, consists of `Records` and `IObservableCollections`, which automatically appear to behave as you'd expected.

For anyone stumbling across this potentially: The backing field with the proposed solution of using `RaiseAndSetIfChanged` can be bypassed by using `ReactiveUI.Fody`, which allows to use the `[Reactive]` / `[ObservableAsProperty]` instead, depending on use case.

Under the hood it'll likely do the same as proposed but keeps the code base a tad cleaner.

If a `ReactiveUI` dependency is undesired the `INotifyPropertyChanged` can still be taken, for those interested in it.
