### ISSUE TITLE
BitmapInterpolationMode LowQuality interpolates pixels instead of using closest neighbor

### ISSUE THREAD

**Issue by HoneyTauOverTwo** [AvaloniaUI/Avalonia#8621]
From what I understand, ``LowQuality`` interpolation mode is supposed to use closest neighbor when scaling a bitmap instead of interpolating the pixels, but Avalonia still interpolates them.

Unintuitively, ``Default`` ``BitmapInterpolationMode`` produces the desired result for ``LowQuality``:

Windows 10:
![Windows10](https://user-images.githubusercontent.com/31476381/181608648-11b34368-065c-489e-99c9-cb009f90d4e4.PNG)

macOS 12:
![macOS12](https://user-images.githubusercontent.com/31476381/181608815-12fb355c-2428-45d6-ac26-921f6c1268d9.PNG)

Here is the code I used to produce those images: https://github.com/HoneyTauOverTwo/AvaloniaBitmapInterpolationMode

**Comment by jmacato** [comment]
@Gillibald iirc you were the one that implemented the BitmapInterpModes before, hope you can check this one out

**Comment by Gillibald** [comment]
Skia's default does not apply any interpolation -> Default
LowQuality still interpolates
With Direct2D1 we can't disable interpolation so thats why there isn't BitmapInterpolationMode.None but I guess we could add BitmapInterpolationMode.None for Skia

**Comment by Gillibald** [comment]
BitmapInterpolationMode.None can be used to disable interpolation
