### ISSUE TITLE
TextBox becomes slow when there are over 2k lines of text and wrapping is enabled

### ISSUE THREAD

**Issue by davidtimovski** [AvaloniaUI/Avalonia#8623]
**Describe the bug**
The `TextBox` appears slow when typing when it has more than 2000 short lines of text inside it and `TextWrapping` is enabled. It gets way worse as the lines increase and becomes unusable at just 4000 lines. It appears that having `TextWrapping="Wrap"` on the `TextBox` adds to this slowdown as one without wrapping performs about 10 times faster but still becomes unusable at about 20000 lines of text.

**To Reproduce**
1. Create an Avalonia application with `<TextBox AcceptsReturn="True" TextWrapping="Wrap" />`
2. Paste in 2000 lines of text
3. Type and observe the performance
4. Remove `TextWrapping="Wrap"` and see that it's faster but still janky after 8000 lines of text

**Expected behavior**
The `TextBox` should be able to handle more lines of text before it starts to become janky.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 0.10.17

Debug vs Release mode doesn't make a difference.

**Comment by maxkatz6** [comment]
Consider using AvaloniaEdit for the huge text boxes https://github.com/AvaloniaUI/AvaloniaEdit

**Comment by colejohnson66** [comment]
It's probably choking because it has to measure everything, even if it's not shown. AvaloniaEdit can do some fancy stuff to only need to measure the text that's visible.

Not saying this isn't an issue, but what would you need a multi thousand line text box for? You get no syntax highlighting or anything.

**Comment by davidtimovski** [comment]
Yeah I wasn't originally intending to end up with thousands of lines. I'm using the `TextBox` for a notes taking app and I happened to use it in a manner where I ended up with some pretty huge notes. I'm moving to AvaloniaEdit now but it's not going to be easy because of how sparse the documentation is.

Thank you for the suggestions.

**Comment by grokys** [comment]
Regarding the lack of docs, it's a port of wpf's AvalonEdit so any docs for that should mostly apply.
