### ISSUE TITLE
Emoji is displayed as ⃞ on win7

### ISSUE THREAD

**Issue by sudongg** [AvaloniaUI/Avalonia#8629]
**Describe the bug**
Emoji displays normally on win 10 but not on win7.

**To Reproduce**
Create a new project and add to MainWindow.axaml
1. `<TextBlock Text="Test 😄" />`
2. Emoji displays normally on win 10
3 Emoji displays  ⃞ on win 7

**Expected behavior**
same as win 10

**Desktop (please complete the following information):**
- OS:Windows 10 19041  and Windows 7 sp1

**Comment by timunie** [comment]
I @sudongg ,

I think this will be available in upcomming v11.0. In the current version, this is not working. 

Happy coding
Tim

**Comment by timunie** [comment]
Let me add: I don't know about win 7, as this is no longer supported event at microsoft.

**Comment by maxkatz6** [comment]
1. You need a compatible font that has emojis. 
2. TextBlock should work in 0.10 as far as I remember, but TextBox supports it only in nightly 11.0 as @timunie said

**Comment by sudongg** [comment]
> 1. You need a compatible font that has emojis.
> 2. TextBlock should work in 0.10 as far as I remember, but TextBox supports it only in nightly 11.0 as @timunie said
The problem only occurs on win7, I have tried using embedded fonts on win7 and seguiemj.ttf is already installed on win7.

**Comment by maxkatz6** [comment]
@Gillibald do you know anything about win7 specific behavior?

**Comment by Gillibald** [comment]
Win7 might not come with a default font that supports Emojis

**Comment by sudongg** [comment]
> Win7 might not come with a default font that supports Emojis other than that there is nothing special
I tried to use embedded fonts and install emojis fonts, but they didn't solve the problem.

**Comment by timunie** [comment]
Can you maybe double-check in your font if all three icons which are not working are available?
