### ISSUE TITLE
0.10.17 Avalonia.LinuxFramebuffer not working

### ISSUE THREAD

**Issue by zxslzx** [AvaloniaUI/Avalonia#8644]
**Describe the bug**
I tested it with ubuntu 20.04 in vmware

**Screenshots**
This is tested on linux.
<img width="400" alt="Snipaste_2022-08-02_15-53-32" src="https://user-images.githubusercontent.com/32009362/182322825-fe313d3e-67de-4c22-adb5-0741477cf636.png">

This is tested on windows.
<img width="324" alt="Snipaste_2022-08-02_15-54-12" src="https://user-images.githubusercontent.com/32009362/182322851-dbb89c90-fff6-498a-97ca-eb4647844b6f.png">

**Comment by kekekeks** [comment]
Most likely VMWare-specific issue, works on real hardware and with QEMU/KVM virtual machine.
Also check that you are handling [the lifetime](https://github.com/AvaloniaUI/Avalonia/blob/f01176825a131afbf6278bfa1bf374033e24a167/samples/ControlCatalog/App.xaml.cs#L93-L96)

**Comment by zxslzx** [comment]
> Most likely VMWare-specific issue, works on real hardware and with QEMU/KVM virtual machine. Also check that you are handling [the lifetime](https://github.com/AvaloniaUI/Avalonia/blob/f01176825a131afbf6278bfa1bf374033e24a167/samples/ControlCatalog/App.xaml.cs#L93-L96)

Reference [the lifetime](https://github.com/AvaloniaUI/Avalonia/blob/f01176825a131afbf6278bfa1bf374033e24a167/samples/ControlCatalog/App.xaml.cs#L93-L96). It has been solved. Thank you very much.
