### ISSUE TITLE
Extending Tab Control

### ISSUE THREAD

**Issue by DanielTyebkhan** [AvaloniaUI/Avalonia#8649]
I am trying to extend the TabControl to make a custom tabbed component, but when I assign to Items in the subclass, no tabs show up.

    using System.Linq;
    using Avalonia.Controls;
    using Avalonia.Media;
    
    namespace MyApp;
    
    public class BugComponent : Panel
    {
        public BugComponent()
        {
            // var left = MakeTabControl(new[] { "left1", "left 2" });
            // var right = MakeTabControl(new[] { "right 1", "right 2", "right 3" });
            // var tabbedGrid = MakeSplitGrid(left, right);
            var left = new CustomTabControl(new[] { "left1", "left 2" });
            var right = new CustomTabControl(new[] { "right 1", "right 2", "right 3" });
            var tabbedGrid = MakeSplitGrid(left, right);
            Children.Add(tabbedGrid);
        }
    
        Grid MakeSplitGrid(Control left, Control right)
        {
            var grid = new Grid
            {
                ColumnDefinitions = new("*, 4, *")
            };
            var splitter = new GridSplitter { Background = Brushes.Black };
            Grid.SetColumn(left, 0);
            Grid.SetColumn(splitter, 1);
            Grid.SetColumn(right, 2);
            grid.Children.Add(left);
            grid.Children.Add(splitter);
            grid.Children.Add(right);
            return grid;
        }
    
        TabControl MakeTabControl(string[] tabNames)
        {
            return new TabControl
            {
                Items = tabNames.Select(n => new TabItem { Header = n, Content = n }),
                
            };
        }
    }
    
    class CustomTabControl : TabControl
    {
        public CustomTabControl(string[] tabNames)
        {
            Items = tabNames.Select(n => new TabItem { Header = n, Content = n });
        }
    }

Running this code produces a screen that appears
<img width="951" alt="image" src="https://user-images.githubusercontent.com/30511534/182478829-8744b226-b1db-4793-b133-8dd531031e98.png">

Switching out the commented lines in the BugComponent constructor to add basic TabControls gives the desired result:
<img width="951" alt="image" src="https://user-images.githubusercontent.com/30511534/182478933-84bb6cf4-01fb-4d0a-ab28-2691bddcc1b4.png">

However, even in this situation, clicking on the tabs doesn't change them. I'm not sure if I'm doing something wrong here or if there are some tab control related bugs. Thanks for any help.

**Comment by jp2masa** [comment]
The default styles only apply to `TabControl`, so `CustomTabControl` has no template, and won't render anything.

You can either change `StyleKey` to `typeof(TabControl)` ([example](https://github.com/AvaloniaUI/Avalonia/issues/4321#issuecomment-660875361)), or copy the default styles and change the selector (i.e. copy [this file](https://github.com/AvaloniaUI/Avalonia/blob/4a6a3a141bfc94f34b7563e89eff463a36601cd2/src/Avalonia.Themes.Fluent/Controls/TabControl.xaml) and replace all `TabControl` in selectors with `CustomTabControl`). The second approach is better if your objective is customizing the control completely.

Also note that for the next major version there will be control templates, which will be preferred for providing the default theme for a control, but the difference is not too big ([new `TabControl` styles for comparison](https://github.com/AvaloniaUI/Avalonia/blob/e7124db116d0c5038353d8d937ac7c354ae84e3d/src/Avalonia.Themes.Fluent/Controls/TabControl.xaml)).

**Comment by DanielTyebkhan** [comment]
Thanks for the reply and examples. I changed the StyleKey and the component shows up, but it still won't let me switch tabs (both in the custom and normal tab control). Any idea why that might be?

**Comment by jp2masa** [comment]
That's probably because you're doing `Items = tabNames.Select(n => new TabItem { Header = n, Content = n })`, which means that enumerating `Items` always creates new `TabItem`s, so when you select an item it can't be found in `Items`. Adding `.ToList()` should work.

**Comment by DanielTyebkhan** [comment]
Makes sense. Thanks for your help. Closing the thread.
