### ISSUE TITLE
Arc StrokeLineCap lost after transition

### ISSUE THREAD

**Issue by kikipoulet** [AvaloniaUI/Avalonia#8659]
Using Transitions with an Arc loose the StrokeLineCap="Round" property using AvaloniaUI 0.10.17

![CircleProgressWithoutTransition](https://user-images.githubusercontent.com/19242427/182633952-1849b37e-0042-47f4-afc6-0820d51b3232.gif)

When adding a transition :
`<Arc.Transitions>
                                <Transitions>
                                    <DoubleTransition
                                        Duration="0:0:0.8"
                                        Easing="CircularEaseOut"
                                        Property="SweepAngle" />
                                </Transitions>
                            </Arc.Transitions>`

![CircleProgressWithTransition](https://user-images.githubusercontent.com/19242427/182634128-6c1c805b-fb2a-43d6-82db-2e75ec6a234f.gif)

The StrokeLineCap property is lost after the Transition is finished

**Comment by kekekeks** [comment]
Looks like a clipping-related bug

**Comment by timunie** [comment]
@kikipoulet can you provide the sample app you have shown in your issue?

**Comment by kikipoulet** [comment]
This is the UserControl from my library SukiUI : https://github.com/kikipoulet/SukiUI/blob/main/SukiUI/Controls/CircleProgressBar.axaml

And this is the code I use for the demo : https://pastebin.com/dMiZTYVj

**Comment by timunie** [comment]
@kikipoulet I think it's the same issue I had back then. I had a PR for this, but I'm not sure if it was backported. See #7778

See dirty rects (you can enable them in dev tool / [F12] ) for reference: 

![image](https://user-images.githubusercontent.com/47110241/183103071-c3dbe1da-814c-4be6-a702-7a22272996f5.png)

**Comment by timunie** [comment]
@kekekeks do you think we can backport the linked PR to 0.10.18?

**Comment by kikipoulet** [comment]
Thanks for the explanation ! Can't wait for 10.18 then :)

**Comment by timunie** [comment]
Created a backport PR. Let's see if it will be merged, can't promise anything ^^
