### ISSUE TITLE
Avalonia passes "unset" as value to converter when used with MultiBinding

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/Avalonia#8672]
**Describe the bug**
In Avalonia every time you add control with MultiBinding and MultiValueConverter your converter will receive "unset" as the value.
![image](https://user-images.githubusercontent.com/53405089/182831680-67029d38-de65-4739-b922-b04d49b72518.png)
It happens only on the initialization stage,later you will receive only correct balues. Also doesen't seem to repro with normal bindings,only when you use TemplateBinding with MultiBinding's.

**To Reproduce**
Consider this repro https://github.com/Takoooooo/AvaloniaConverterBugRepro

**Comment by jp2masa** [comment]
Maybe related to #2623?

**Comment by grokys** [comment]
Might be related, but looks to be a different issue. Will check while I'm fixing this one.

**Comment by Harold2017** [comment]
i used the following shortcut code to bypass the unset value when initialization, post here if someone needed.
```C#
if (values.Any(x => x is UnsetValueType)) return false;
```
