### ISSUE TITLE
IAvaloniaDependencyResolver GetRequiredService isn't in the nuget?

### ISSUE THREAD

**Issue by AsafMahlev** [AvaloniaUI/Avalonia#8673]
**Describe the bug**
I looked at some samples, saw the method `GetRequiredService` which is useful because it doesn't return null.
But it just doesn't seem to exist in my nuget?

**To Reproduce**
1. Download nuget
2. Use AvaloniaLocator
3. It's not there

**Expected behavior**
Have the method GetRequiredService under LocatorExtensions

**Screenshots**
Decompiled method:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/109351094/182871050-9a61ef7b-6a59-4e3a-86fa-0cd40665552c.png">

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)] Windows
- Version [e.g. 0.10.0-rc1 or 0.9.12]: 0.10.17

**Comment by maxkatz6** [comment]
It's part of nightly builds

**Comment by grokys** [comment]
Actually I just ported it to the stable branch (as it was needed to port another PR) so it'll be part of the next stable release.
