### ISSUE TITLE
Canvas: Coordinates are rounded to the nearest integer

### ISSUE THREAD

**Issue by joneuhauser** [AvaloniaUI/Avalonia#8694]
**Describe the bug**
Canvas Children are rendered as if their coordinates (and Canvas.Left / Canvas.Top attached properties) were rounded to the nearest integer.

**To Reproduce**

```
<Canvas Height="100.0" RenderTransformOrigin="0,0" Width="100.0">
		<Ellipse Canvas.Left="3.3" Canvas.Top="3.5" Fill="#ffff0000" Height="3.3" Width="3.3"/>
		<Canvas.RenderTransform>
			<ScaleTransform ScaleX="20" ScaleY="20"/>
		</Canvas.RenderTransform>
	</Canvas>
```
Change the width to 3.3 -> 3.4 -> 3.5. The width is unchanged when setting it to 3.4, and jumps to 4 when setting it to 3.5.

**Expected behavior**
Floating point coordinate are taken into account. The documentations also list them as double: http://reference.avaloniaui.net/api/Avalonia.Controls/Canvas/AF9AD066

It also works that way in WPF.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 
- Vesion: 0.10.17

**Additional Information**:
I'm trying to recreate the SVG unit test pservers-pattern-07-f.svg, and since Avalonia doesn't have a DrawingBrush, I have to use a VisualBrush with a canvas.

**Comment by grokys** [comment]
Can you try setting `UseLayoutRounding="False"` on the canvas?

**Comment by joneuhauser** [comment]
Thanks, that fixes it!
