### ISSUE TITLE
Initial window position is wrong in WSL2

### ISSUE THREAD

**Issue by HermanKirshin** [AvaloniaUI/Avalonia#8696]
**Describe the bug**
When form SizeToContent is set to WidthAndHeight then initial window position is ignored.

**To Reproduce**
Create simple window, set following attributes
`SizeToContent="WidthAndHeight"
WindowStartupLocation="Manual"
Position="100 100"`
and run application under WSL

**Expected behavior**
Form is positioned at specified coordinates

**Desktop (please complete the following information):**

- OS: WSL Ubuntu 22.04
- 0.10.17

**Additional context**
Reproduced only under WSL, works fine on normal Ubuntu.

**Comment by jp2masa** [comment]
I'm assuming you're running it on WSLg, in that case it's possible that it doesn't implement position APIs correctly (see https://github.com/microsoft/wslg/issues/355).

**Comment by kekekeks** [comment]
WSLg provides Linux VM which Wayland compositor which doesn't give access to window coordinates. I suspect that is by design.

**Comment by HermanKirshin** [comment]
By the way it works perfectly if SizeToContent="Manual"

**Comment by kekekeks** [comment]
Ah, that might be caused by WSL ignoring the window position that was set when the window was initially shown.
