### ISSUE TITLE
iOS build fails on MacOS

### ISSUE THREAD

**Issue by byme8** [AvaloniaUI/Avalonia#8697]
**Describe the bug**
The Ios app fails to run with the following error message:
```
/AvaloniaPerformanceTest/avaloniax.iOS/AppDelegate.cs(13,6): error CS0012: The type 'UIResponder' is defined in an assembly that is not referenced. You must add a reference to assembly 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. [/AvaloniaPerformanceTest/avaloniax.iOS/avaloniax.iOS.csproj]
```

**To Reproduce**
I just created a new Avalonia app from CLI. 
It can be reproduced with the following repository: https://github.com/byme8/AvaloniaPerformanceTest

1. Run command in avaloniax.iOS folder: `` dotnet run ``

**Expected behavior**
The app launched in the simulator

- OS: Mac 12.4
- Version 0.10.999-cibuild0019213-beta
- Dotnet 6.0.302

**Comment by maxkatz6** [comment]
See https://github.com/AvaloniaUI/avalonia-dotnet-templates/issues/94#issuecomment-1157100714
You need to use latest possible SDK and latest possible avalonia nightly to keep in compatible.
