### ISSUE TITLE
Impossible to enter whitespace character to TextBox on Linux/Mac (Gtk#)

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#870]
Navigations keys (Left, Top, Right, Down) are not working too.

**Comment by danwalmsley** [comment]
@kekekeks any ideas what this is? Its affecting me also, been trying to debug but cant build on Ubuntu for some reason.

**Comment by grokys** [comment]
Seems to have been introduced by https://github.com/AvaloniaUI/Avalonia/commit/d9607a5fca989531e3ef4689aa13dea9db82cd91 according to `git bisect`.

**Comment by danwalmsley** [comment]
#872 fix merged.
