### ISSUE TITLE
Android: application is not responcive afrer restore

### ISSUE THREAD

**Issue by ili** [AvaloniaUI/Avalonia#8703]
**Describe the bug**
Application is not responcive responcive afrer minimazing/switching to another app & restore.

**To Reproduce**
1. Run `ControlCatalog.Android`,
2. Minimize the app
3. Restore the app
4. Try to switch tabs

This looks like to occure after enabling composition renderer (#8105 #7933)

**Comment by maxkatz6** [comment]
Can you check how it works, if you set
`
.With(new AndroidOptions
{ UseComposition= false; UseDeferredRenderer = true; }
`
?
Basically reverting defaults from https://github.com/AvaloniaUI/Avalonia/pull/8686

**Comment by ili** [comment]
@maxkatz6  i'v tested, reverting options fixes the issue, but i changed directly in `AndroidPlatformOptions`, because 

neither 

```cs
    public class MainActivity : AvaloniaActivity<App>
    {
        protected override AppBuilder CustomizeAppBuilder(AppBuilder builder)
        {
            return base.CustomizeAppBuilder(builder
                    .With(new AndroidPlatformOptions
                    {
                        UseCompositor = false,
                        UseDeferredRendering = true
                    })
                )
                .AfterSetup(_ =>
                {
                    Pages.EmbedSample.Implementation = new EmbedSampleAndroid();
                });
        }
    }
```

nor 

```cs
    public class MainActivity : AvaloniaActivity<App>
    {
        protected override AppBuilder CustomizeAppBuilder(AppBuilder builder)
        {
            return base.CustomizeAppBuilder(builder)
                .With(new AndroidPlatformOptions
                {
                    UseCompositor = false,
                    UseDeferredRendering = true
                })
                .AfterSetup(_ =>
                {
                    Pages.EmbedSample.Implementation = new EmbedSampleAndroid();
                });
        }
    }

```

affects default values, or i just does not understand how to use `With()` :)
