### ISSUE TITLE
Acrylic Blur and Mica background does not work in published APP

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#8705]
**Describe the bug**
Acrylic Blur and other background options do not work in the published APP. But works well in DEBUG mode

**Publish Settings**
+ Configuration: Release
+ Target Framework: net6.0
+ Target Runtime: win-x64
+ Deploy Mode: Framework Depends
+ Publish Single File: true

**To Reproduce**

1. Create a new project
2. Apply acrylic window based on [link](https://docs.avaloniaui.net/tutorials/music-store-app/creating-a-modern-looking-window)
3. Publish this project with the single file option enabled
4. Open the published file, and there is no acrylic effect applied to the window

**Expected behavior**
There should be an acrylic effect shown on the window background.

**Screenshots**
<img width="903" alt="image" src="https://user-images.githubusercontent.com/25716486/183487197-49e3a918-fa4d-4e36-97ae-f57e00e69791.png">

**Desktop (please complete the following information):**

- OS: Windows
- Version 21H2 22000.832 Experience Pack 1000.22000.832.0

**Comment by laolarou726** [comment]
Here is the test repo if needed for reproduction: https://github.com/laolarou726/AcrylicTest

**Comment by kekekeks** [comment]
>Target Runtime: win-x64

Use win7-x64

**Comment by laolarou726** [comment]
@kekekeks Are there any side effects when targeting to win7-x64? For example performance, size of the binary, etc.

**Comment by kekekeks** [comment]
I don't think so
