### ISSUE TITLE
Several cursors inside several TextBox controls on gtk#

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#871]
![several cursors inside several textbox on gtk#](https://cloud.githubusercontent.com/assets/1150330/22403469/0f2edf18-e629-11e6-88c3-ce4072577aaa.png)

**Comment by kekekeks** [comment]
Duplicates #288

**Comment by kekekeks** [comment]
Please, try with GTK3+Skia
