### ISSUE TITLE
Problem with GridLength.ToString()

### ISSUE THREAD

**Issue by npolyak** [AvaloniaUI/Avalonia#8722]
GridLength.ToString() converts the Value in a local culture string, but GridLength.Parse(string s) parses the double string with CultureInfo.InvariantCulture. I think both should behave in the same fashion (I suggest culture invariant).

**Comment by timunie** [comment]
@npolyak do you want to send a PR for this?

**Comment by rabbitism** [comment]
> @npolyak do you want to send a PR for this?

Can I do it?

**Comment by timunie** [comment]
If @npolyak isn't working on it, yes. For sure 👍. Contributions are very welcome.

**Comment by npolyak** [comment]
Yes, please, go ahead - I won't be free to work on it till 5 pm est.
