### ISSUE TITLE
Tooltips aren't positioned correctly when using PlacementMode.Pointer

### ISSUE THREAD

**Issue by SourMesen** [AvaloniaUI/Avalonia#8730]
**Describe the bug**
In recent builds, following the changes done in 6485fa1, tooltips using `PlacementMode.Pointer` no longer appear where the pointer is. Instead they appear where the pointer was when the pointer entered the current control. So when trying to, for example, display tooltips for specific sections of a custom drawn control, the tooltip always appears on the edges of the control, no matter the pointer's position when `ToolTip.SetIsOpen` is called

This seems to be caused by the code over in `PointerOverPreProcessor.cs` which only updates the `_lastPointer` member when the mouse moves over to a different element (`if(element != pointerOverElement)` in `SetPointerOver`).

Moving the line `_lastPointer = (pointer, root.PointToScreen(position));` out of `SetPointerOverToElement` and putting it at the end of `SetPointerOver` instead (after the if condition) makes it update `_lastPointer` whenever the mouse is moved, and fixes the issue on my end (the tooltip seems to behave like it did in 0.10.17 with this fix)

**Expected behavior**
Tooltips using PlacementMode.Pointer should appear where the pointer is when ToolTip.SetIsOpen is called

**Desktop (please complete the following information):**

- OS: Windows 10
- Version master (latest commit)

**Comment by maxkatz6** [comment]
> Moving the line _lastPointer = (pointer, root.PointToScreen(position)); out of SetPointerOverToElement and putting it at the end of SetPointerOver instead (after the if condition) makes it update _lastPointer whenever the mouse is moved, and fixes the issue on my end

This solution looks good to me, I don't see any problems.
Do you want to create a PR with your changes?
