### ISSUE TITLE
DoubleTapped event is not fired correctly when the event source changes

### ISSUE THREAD

**Issue by Georgiks** [AvaloniaUI/Avalonia#8733]
**Describe the bug**
When having a DoubleTapped event on a control, and the control changes during double pressing, the double tapped event is not then correctly emitted for the new control when continuously clicking.

Scenario is a file explorer-like container with items in it, double clicking opens a folder. Opening the folder would present another folder control on the same place, and when user wants to double click that item quickly, it wont work since the gesture is still tied to the previous control.

**To Reproduce**

1. Make a List/GridView of items
2. The items have DoubleTapped event handler, which replaces the content of the List/GridView with another items
3. Double clicking the first item changes the content, don't stop clicking with input device nor move the pointer.
4. Another items is presented under the pointer, however the List/GridView content is not changing due to DoubleTapped event not being produced.
5. Moving the pointer, or pausing clicking for a second and then proceeding again correctly changes the content again (DoubleTapped event is produced)

**Expected behavior**
Double clicking a control would trigger DoubleTapped event, and proceeding with clicking while the underlying control changes should still trigger another double-clicked event when clicking at least twice on the new control.

**Desktop (please complete the following information):**

- OS: Windows
- Version [e.g. 0.10.13]

**Comment by maxkatz6** [comment]
It seems problem is in this method https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Input/Gestures.cs#L92-L114
Gesture is initiated only when there is <= 1 click count. And if user continuously clicks for 3th or 5th time it doesn't reset the gesture.
