### ISSUE TITLE
The PR "Fixes/win32 can resize" is not included in the release

### ISSUE THREAD

**Issue by fr-Pursuit** [AvaloniaUI/Avalonia#8735]
**Describe the bug**
If you have ExtendToClientDecorations = true, and CanResize = false, you can't drag with titlebar on win32.

**Expected behavior**
Being able to drag a window's titlebar when ExtendToClientDecorations = true and CanResize = false

**Desktop (please complete the following information):**

- OS: Windows
- Version 10 21H2

**Additional context**
This bug was fixed in #7755 (which was merged into `master` in March), but isn't included in the release build as of version [0.10.17](https://github.com/AvaloniaUI/Avalonia/blob/release/0.10.17/src/Windows/Avalonia.Win32/WindowImpl.CustomCaptionProc.cs).

**Comment by timunie** [comment]
Will be available in 11.0 I think. Currently many changes are done for next major release.

**Comment by fr-Pursuit** [comment]
Thanks for the precision. Though, shouldn't it also be included in 0.10, since it's only a bugfix?

**Comment by maxkatz6** [comment]
@fr-Pursuit thanks!
It was backported. Will be available with 0.10.18 soon.

**Comment by fr-Pursuit** [comment]
Thanks!
