### ISSUE TITLE
ImageBrush doesn't tile properly

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#874]
If you put a an image smaller than the target control in an `ImageBrush` and set it to tile, it doesn't.

We have lots of tests for the more advanced behaviors of `ImageBrush` but nothing testing the simple behavior!

**Comment by SnowyYANG** [comment]
why is this closed, it's still an issue in 0.10.11

**Comment by maxkatz6** [comment]
@SnowyYANG create a new issue with steps to reproduce. This one is tested and should work fine.
