### ISSUE TITLE
Fail to build application for Android in Release mode

### ISSUE THREAD

**Issue by msnoshain** [AvaloniaUI/Avalonia#8750]
**Describe the bug**
I failed to build application for Android in Release mode.
Error log: [System.ArgumentException: An item with the same key has already been added]

**To Reproduce**

1. Build the Android project in release mode
2. After optimizing and generating assemblies, VS logs the error
3. Click and locate the error

**Screenshots**
![image](https://user-images.githubusercontent.com/85274323/184553503-dfa0f160-a358-470b-9850-b12218b6b488.png)
(C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets)

**Desktop:**
- OS: Windows 11 Insider Preview
- Version 25179.1000

**Additional context**
1. I think there's something wrong with MSBuild script. Somehow an existing key was tried to be added but there's no further info to indicate which key.
2. Everything works well in Xamarin, no MSBuild error.

**Comment by maxkatz6** [comment]
Any repro project? .net sdk version? Avalonia version?

**Comment by msnoshain** [comment]
> Any repro project? .net sdk version? Avalonia version?

I simply create my project with the xplat template and build it.
.net SDK version is 7.0.100-preview.6.22352.1.
Avalonia version is 0.10.999-cibuild0019213-beta

**Comment by msnoshain** [comment]
found solution here: 
https://stackoverflow.com/questions/73183482/an-item-with-the-same-key-has-already-been-added-maui-c-sharp/73221450

It's a bug from .net 7. Building application with .net 6 would solve the problem
