### ISSUE TITLE
Windows - IME Context isn't reset for Popups

### ISSUE THREAD

**Issue by ptpt666** [AvaloniaUI/Avalonia#8758]
**Describe the bug**
ime will be disabled after clicking some controls like combobox

i use chinese ime (sogou) ，when i click textbox after clicking combobox , the ime will be disabled an i can't input chinese words ,i can only input english words.

**To Reproduce**

1. run the app
2. Click on textbox,the ime is ok,i can input chinese words
3. Click on combobox
4. Click on textbox,the ime will be disabled,i can't input chinese

**Expected behavior**
i hope that i can input chinese words

**Screenshots**

https://user-images.githubusercontent.com/6055564/184682349-b92b5dad-da83-41e9-b4a4-557a64e9bbf7.mp4

**Desktop (please complete the following information):**

- OS: Windows 19042
- Version 0.10.17

**Comment by ptpt666** [comment]
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:AvaloniaUITest.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaUITest.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="AvaloniaUITest">

	<Window.Styles>
		<Style Selector="TextBox">
			<Setter Property="FontFamily" Value="Microsoft YaHei,Simsun,苹方-简,宋体-简" />
			<Setter Property="FontSize" Value="15"/>
			<Setter Property="Padding" Value="1"/>
			<Setter Property="VerticalAlignment" Value="Center"></Setter>
		</Style>
		<Style Selector="TextBlock">
			<Setter Property="FontFamily" Value="Microsoft YaHei,Simsun,苹方-简,宋体-简" />
			<Setter Property="FontSize" Value="13"/>
			<Setter Property="Padding" Value="0"/>
			<Setter Property="Margin" Value="5,0"/>
			<Setter Property="VerticalAlignment" Value="Center"></Setter>
		</Style>
		<Style Selector="ComboBox">
			<Setter Property="FontFamily" Value="Microsoft YaHei,Simsun,苹方-简,宋体-简" />
			<Setter Property="AutoScrollToSelectedItem" Value="True"></Setter>
			<Setter Property="VirtualizationMode" Value="Simple"></Setter>
		</Style>
		<Style Selector="AutoCompleteBox">
			<Setter Property="FontFamily" Value="Microsoft YaHei,Simsun" />
		</Style>
	</Window.Styles>
    <Design.DataContext>
        <vm:MainWindowViewModel/>
    </Design.DataContext>

	<StackPanel>
		<TextBlock Text="{Binding Greeting}" HorizontalAlignment="Center" VerticalAlignment="Center"/>
		<TextBox Width="200" Name="TB1"/>
		<ComboBox Name="cb1" Width="200">
			<ComboBoxItem Content="选项1"/>
			<ComboBoxItem Content="选项2"/>
			<ComboBoxItem Content="选项3"/>
			<ComboBoxItem Content="选项4"/>
			<ComboBoxItem Content="选项5"/>
		</ComboBox>
		<DropDown Width="200" InputMethod.IsInputMethodEnabled="True">
			<DropDownItem Content="dd1"/>
			<DropDownItem Content="dd2"/>
			<DropDownItem Content="dd3"/>
			<DropDownItem Content="dd4"/>
			<DropDownItem Content="dd5"/>
		</DropDown>
		<AutoCompleteBox InputMethod.IsInputMethodEnabled="True">
			
		</AutoCompleteBox>
		<Button Content="确定"/>
		<Menu>
			<MenuItem Header="菜单1"/>
			<MenuItem Header="菜单2"/>
			<MenuItem Header="菜单3"/>
			<MenuItem Header="菜单4"/>
			<MenuItem Header="菜单5"/>
		</Menu>
	</StackPanel>
</Window>

**Comment by ptpt666** [comment]
@Gillibald hello,I did a test and found that this problem can be solved as long as the input method is not updated when popping up

just like this:
Avalonia.Win32.WindowImpl.cs:
      public WindowImpl()
        {
            ......
            if (this is not PopupImpl)
                UpdateInputMethod(GetKeyboardLayout(0));
            ......
        }

**Comment by Gillibald** [comment]
Thank's for letting me know

**Comment by BoyFaceGirl** [comment]
> 谢谢你让我知道

文本框内输入中文字符的问题一直没有得到好的解决，文本的根本原因是什么？为什么原声的wpf和winform都没有问题？是否和区域有关？还是中文字体渲染有关？这个问题是阻止我使用avalonia 的主要原因。

**Comment by BoyFaceGirl** [comment]
> 谢谢你让我知道

The problem of inputting Chinese characters in the text box has not been solved. What is the root cause of the text? Why are there no problems with the original WPF and WinForm? Is it related to the region? Or Chinese font rendering? This problem is the main reason that prevents me from using Avalonia.

**Comment by Gillibald** [comment]
@BoyFaceGirl What problem are you referring to? Are you using the Avalonia 11 preview?

**Comment by ptpt666** [comment]
@Gillibald hi,I'v tried the latest version, but the bug still exists, I want to know when this bug will be fixed

**Comment by kekekeks** [comment]
For 0.10.x you need to use a custom font

>You need to use a font that has Chinese characters. https://github.com/anthonyfok/fonts-wqy-microhei is a good one
[WenQuanYiMicroHei-01.ttf.zip](https://github.com/AvaloniaUI/Avalonia/files/5703016/WenQuanYiMicroHei-01.ttf.zip)
>
>Place it into Assets, add as AvaloniaResource and add something like
>
>```
><Style Selector="TextBlock">
>    <Setter Property="FontFamily" Value="avares://YourAssemblyName/Assets/Fonts#WenQuanYi Micro Hei" />
></Style>
>```
>to your App.xaml after the theme

**Comment by ptpt666** [comment]
@Gillibald @kekekeks hi,i've tried the version 11.0.0.0-preview3 ,the bug in this issue is still not handled.i think that  when the popup control pops up, the input method should not be updated. In this way, the input method will not have problems when returning to the text input control

**Comment by ptpt666** [comment]
@Gillibald @kekekeks @maxkatz6 
There's another bug when i tried the version 11.0.0-preview6.
When using the Sogou input method, the textbox cannot input Chinese. When using the Microsoft Pinyin input method, the textbox can input Chinese. However, using these two input methods, the textbox cannot input punctuation such as commas (,) periods (.).

**Comment by timunie** [comment]
@ptpt666 do you think the issue posted in above comment is the same as the original bug report? Somehow I feel it is a different issue and thus should have a fresh new issue report including steps to reproduce.

**Comment by ptpt666** [comment]
> @ptpt666 do you think the issue posted in above comment is the same as the original bug report? Somehow I feel it is a different issue and thus should have a fresh new issue report including steps to reproduce.

ok,i'll post a new issue,thanks
