### ISSUE TITLE
DataGrid become very slow when having a horizontal scroll

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#8759]
**Describe the bug**
DataGrid become very slow when having a horizontal scroll

**To Reproduce**

1. Create a DataGrid with enough data to horizontal and vertical scroll to show up
2. Scroll up and down
3. Notice the slow scrolling
You can also notice it slow when expanding column width and it goes out of bounds and make horizontal scroll visible.

**Expected behavior**
To have same speed behavior as when horizontal scroll bar is hidden

**Screenshots**

https://user-images.githubusercontent.com/113281/184684803-3c9f73da-d391-4a06-af09-fc1033f1836a.mp4

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 0.10.18

**Comment by timunie** [comment]
@sn4k3 you may want to try TreeDataGrid. It has a way better performance I think.

**Comment by KieranDevvs** [comment]
> @sn4k3 you may want to try TreeDataGrid. It has a way better performance I think.

Seems odd that the perf hit only occurs when the horizontal scroll bar is rendered though. Seems like a bug rather than a limitation to me.

**Comment by timunie** [comment]
11.0 preview 1 is out with much improved performance. Maybe you can try your scenario there and double check if it got improved.

**Comment by sn4k3** [comment]
Solved with v11
