### ISSUE TITLE
Allow opening and saving files without extension

### ISSUE THREAD

**Issue by SFGrenade** [AvaloniaUI/Avalonia#8763]
**Is your feature request related to a problem? Please describe.**
In a program to open asset files from games, i want to be able to easily open those files, which sometimes have no extension.

**Describe the solution you'd like**
I want the files to be displayed in the file dialog.

**Describe alternatives you've considered**
I could rename them, but then i would have to rename them back to use them normally.

**Additional context**
https://github.com/AvaloniaUI/Avalonia/blob/95b9492ccf0fd4b8483e6d79b9ea6345c6c8e97b/src/Avalonia.Controls/SystemDialog.cs#L81

https://github.com/AvaloniaUI/Avalonia/blob/95b9492ccf0fd4b8483e6d79b9ea6345c6c8e97b/src/Avalonia.Controls/SystemDialog.cs#L123

**Comment by maxkatz6** [comment]
That's a deprecated API. SystemDialog will be removed in the future. 
Use window.StorageProvider APIs on nightly builds.

**Comment by SFGrenade** [comment]
i tried with the newest nuget build 0.10.18 from like 18 hours ago, but they're not available there.

**Comment by SFGrenade** [comment]
alright!
