### ISSUE TITLE
ListBox in Multiple Selection mode uses wrong hotkeys on Mac OS

### ISSUE THREAD

**Issue by HermanKirshin** [AvaloniaUI/Avalonia#8775]
**Describe the bug**
Currently in multi-select listbox picking separate items requires pressing ctrl + mouse click like in windows. This is wrong because common behavior for lists in mac is Command + click, Ctrl+click is used for context menu.

**To Reproduce**
Create any listbox with SelectionMode = Multiple

**Expected behavior**
In MacOs SelectionMode.Multiple performed with Command+Click

**Desktop (please complete the following information):**

- OS: Mac
- Version Any

**Comment by maxkatz6** [comment]
@Takoooooo

**Comment by Takoooooo** [comment]
@HermanKirshin Have you tried it on 0.10.18? I have fixed this issue recently
https://github.com/AvaloniaUI/Avalonia/pull/8637

**Comment by HermanKirshin** [comment]
@Takoooooo Yes, works fine in 0.10.18. I have missed the new release
