### ISSUE TITLE
Crush when resizing window on Windows 11 on ARM 

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#8777]
**Describe the bug**

```
Unhandled exception at 0x00007FFEA4CB2824 (coreclr.dll) in AvaloniaApplication1.exe: Stack cookie instrumentation code detected a stack-based buffer overrun.
The Common Language Runtime cannot stop at this exception. Common causes include: incorrect COM interop marshalling and memory corruption. To investigate further use native-only debugging.
```

**To Reproduce**

Run new Avalonia app from template on Windows 11 on ARM

Disable WindowsUIComposition to avoids crash.

```
new Win32PlatformOptions() {  UseWindowsUIComposition = false }
```

**Expected behavior**

No crash

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11 on ARM
- Version 0.10.x

**Additional context**

Running inside VM MacOS M1 Parallels

**Comment by timunie** [comment]
Duplicate?

**Comment by wieslawsoltes** [comment]
> Duplicate?

Of which issue ?

**Comment by timunie** [comment]
Oh sorry, looks like it was wrong alarm. Sorry.
