### ISSUE TITLE
ContentPresenter.ContentTemplate is ignored if Content is an object which implements IControl

### ISSUE THREAD

**Issue by tomenscape** [AvaloniaUI/Avalonia#8780]
**Describe the bug**
Display the following XAML:

```xaml
<ContentControl>
    <ContentControl.ContentTemplate>
        <DataTemplate>
            <TextBlock Background="Red" Padding="10">Template</TextBlock>
        </DataTemplate>
    </ContentControl.ContentTemplate>
    <TextBlock>Content</TextBlock>
</ContentControl>
```

The control will be rendered with "Content". It should be rendered with "Template" in a red border.

If `<TextBlock>Content</TextBlock>` is changed to just `Content` (i.e. a raw string), behaviour changes. Now "Template" is displayed, as expected.

**Expected behavior**
`ContentTemplate` should be applied no matter what the `Content` is.

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.17

**Additional context**
This bug is probably related to the changes made when fixing #6224.

**Comment by maxkatz6** [comment]
Not sure about your expected behavior. If content is a control, it might be tricky to put it into a template.  i.e. would require nested content presenter.
How does it work in WPF/UWP?

**Comment by tomenscape** [comment]
Yes, you would need a nested `ContentPresenter` within the `ContentTemplate` if you wanted to actually display the content. I avoided doing this in my example to keep it easier to understand.

Here is a new version which tries to display the content:

```xaml
<ContentControl>
    <ContentControl.ContentTemplate>
        <DataTemplate>
            <Border Background="Red" Padding="10">
                <ContentPresenter Content="{Binding}"/>
            </Border>
        </DataTemplate>
    </ContentControl.ContentTemplate>
    <TextBlock>Content</TextBlock>
</ContentControl>
```

Observed result:

![image](https://user-images.githubusercontent.com/109803929/185607806-f04f7b20-a1f6-4668-a4c1-3e90bfaf15f5.png)

Expected result:

![image](https://user-images.githubusercontent.com/109803929/185607839-2fbe9044-95e0-4a08-8151-630211c309e9.png)

The expected result above is what happens in WPF.

**Comment by tomenscape** [comment]
Doesn't happen in Avalonia 11 preview 1.
