### ISSUE TITLE
Audio and Controller Input?

### ISSUE THREAD

**Issue by Shadowblitz16** [AvaloniaUI/Avalonia#8792]
**Is your feature request related to a problem? Please describe.**
Can we get a audio and gamepad api for avalonia?

**Describe the solution you'd like**
For a audio api it would be nice if we could generate waveforms and load up a audio file and play it with a loop from a specified start and end.
For a gamepad api it would be like any other gamepad api I guess.

**Describe alternatives you've considered**
What haven't I tried.

**Additional context**
I am wanting to use Avalonia for a game and a game editor.

**Comment by maxkatz6** [comment]
Audio input/output is out of the scope of GUI framework like Avalonia. You need to use other solutions specialized in that, like [OpenAL](https://www.openal.org/).

Controller support is planned: https://github.com/AvaloniaUI/Avalonia/issues/6945 https://github.com/AvaloniaUI/Avalonia/issues/7607
