### ISSUE TITLE
Transparent with Opacity not working

### ISSUE THREAD

**Issue by sanme98** [AvaloniaUI/Avalonia#8834]
**Describe the bug**
A window with transparent background and opacity 0.5 got a window in white background only on Windows 11.

**To Reproduce**
Please use the code for MainWindow.axaml after created a new Avalonia Cross-platform UI App and run.
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="Transparent.MainWindow"
		Background="Transparent"
		TransparencyLevelHint="Transparent"
		TransparencyBackgroundFallback="Black"
		Opacity="0.5"
	    ExtendClientAreaToDecorationsHint="True"
        Title="Transparent">
    Welcome to Avalonia!
</Window>
```

**Expected behavior**
A window with 0.5 opacity transparent window should come out

**Screenshots**
Actual result I got:
![image](https://user-images.githubusercontent.com/5364763/187023918-65ca6df7-5ebb-4b84-b37d-dc5aac1b9b02.png)

But in the designer, actually it seems like got some transparent effect.
![image](https://user-images.githubusercontent.com/5364763/187023944-369d36f5-462a-44dc-a67e-824d62412180.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 0.10.18

**Comment by HossamElwahsh** [comment]
Same issue
- OS: Windows 11
- Version:	10.0.22000 Build 22000

**Comment by Merovech** [comment]
As of today I am also seeing the same issue.

* VS 2022
* Avalonia 0.10.18
* Windows 11 10.0.22621 Build 22621

**Comment by timunie** [comment]
Iirc you need to build/publish with win7-x64 modifier, otherwise a needed dll is not copied to the output. Can you try it and double-check if it solves your issue?
