### ISSUE TITLE
The window adorner is not rendering

### ISSUE THREAD

**Issue by ymg2006** [AvaloniaUI/Avalonia#8836]
Hello,
The window adorner is not rendering.

**To Reproduce**
Create a simple Avalonia app.

Add this code to the main window:
```
<Window.Styles> 
    <Style Selector=":is(Control)"> 
      <Setter Property="FocusAdorner"> 
        <FocusAdornerTemplate> 
          <Rectangle Stroke="Red" 
                     StrokeThickness="1"/> 
        </FocusAdornerTemplate> 
      </Setter> 
    </Style> 
  </Window.Styles>
```

Show red adorner when window got focus;

- OS: Windows
- Version 11

**Comment by kekekeks** [comment]
Adorners rendered in a special adorner layer that lives _inside_ of the Window's template. 
So I believe adorners for the Window itself can't work with the current design.
