### ISSUE TITLE
FluentTheme missing - 11.0.0-preview1

### ISSUE THREAD

**Issue by Yanik39** [AvaloniaUI/Avalonia#8841]
Hello,

I was using Fluent Theme at 10.999, but with 11 Preview Fluent Theme is missing.

I had to change to Simple Theme with;
```
    <Application.Styles>
        <SimpleTheme Mode="Light"/>
    </Application.Styles>
```

And Simple Theme throws an error at publish;
```
  XamlX.XamlParseException: Unable to resolve type SimpleTheme from 
  namespace https://github.com/avaloniaui Line 10, position 10.
```

Any ideas?

**Comment by rabbitism** [comment]
Please install package Avalonia.Themes.Fluent. #5593

**Comment by robloo** [comment]
You also need Avalonia.Themes.Simple.

Both themes are now separate nuget packages not included with the main Avalonia nuget itself. This was done AFAIK because Avalonia is now used on a lot of embedded devices that don't want unnecessary code. Avalonia is more modular now.

**Comment by Yanik39** [comment]
Thanks, problem solved.
I read the blog post but couldnt find info about it. It seems mentioned at #5593 

Thanks for your time
