### ISSUE TITLE
ToolTips stay open after calling ShowDialog (macOS)

### ISSUE THREAD

**Issue by nineBananas** [AvaloniaUI/Avalonia#8843]
### Describe the bug 

If `ShowDialog` is called while the pointer is over a control with a tool tip, the tool tip will remain open until the child window is closed and `PointerLeave` is raised. 

### To reproduce

Create a new project and replace the content of the main window with:

```xaml
<Button Content="Show dialog" ToolTip.Tip="Tool tip" Click="ButtonClicked" />
```

Then add the following method to the `xaml.cs` file:

```csharp
private async void ButtonClicked(object sender, RoutedEventArgs e)
{
    MainWindow window = new MainWindow();
    await window.ShowDialog(this);
}
```

Press on the button after launching the application.

### Expected behavior

Tool tips should be closed when a new window is opened.

### Screenshots

![Bug_ToolTip](https://user-images.githubusercontent.com/86360278/187104887-e6ae978b-789e-46bb-8235-f60f56b14bbc.png)

### Desktop :

- OS: macOS Monterey 12.5
- Version: 0.10.18

### Additional context

This bug has already been described in the second part of issue #6677 which is now marked as close. The suggested workaround fixes the issue only if a tool tip is already open when calling `ShowDialog`. For that reason I clear tool tips' content before calling `ShowDialog` and reset it after receiving a result.

**Comment by maxkatz6** [comment]
Fixed in master
