### ISSUE TITLE
Changes in API surface for easier binary compatibility later

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#8844]
This is a tracking issue

1) We should replace `StyledProperty`/`DirectProperty`-typed static fields with `AvaloniaProperty`-typed static fields. Otherwise we can't make a change from DirectProperty to StyledProperty without breaking the binary compatibility
2) We need to revisit our API surface and carefully check if some API should be exposed at all. Having our implementation details exposed as public API prevents us from changing said implementation details
3) ...?

**Comment by grokys** [comment]
The reason for using `StyledProperty<T>` fields is current for performance: if the property were to be `AvaloniaProperty<T>` typed then an extra cast would be required when getting/setting values. I think however that some of the changes in #8571 may make this less of an issue, I'll take a look at what would be involved there.

**Comment by kekekeks** [comment]
Can we change DirectProperty fields to AvaloniaProperty ones? SetAndRaise already accepts `AvaloniaProperty`, so it won't have a performance impact. But it would allow us to upgrade direct properties to styled ones later (at the cost of a cast for that particular property).
