### ISSUE TITLE
StyleProperties not applied to ControlTemplate in Avalonia11

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#8857]
**Describe the bug**
Using Avalonia 11, some `StyledProperties` are not applied to the `ControlTemplate`. It works as expected in `0.10.x`

For example, applying the following `ControlTemplate` to a button and trying to set the **`DashStyle`** property, is ignored:

```xaml
<Button Width="150" Height="75">
    <Button.Styles>
        <Style Selector="Button">
            <Setter Property="Template">
                <ControlTemplate>
                    <DockPanel>
                        <controls:ListBoxHierachyLine Name="PART_LastWorkspaceHierarchyLine"
                                                      Foreground="Gray"
                                                      LineThickness="2"
                                                      Width="45"
                                                      TopOffset="0">
                        <controls:ListBoxHierachyLine.LineDashStyle>
                             <DashStyle Dashes="2,2" Offset="1" />
                        </controls:ListBoxHierachyLine.LineDashStyle>
                    </controls:ListBoxHierachyLine>
                </DockPanel>
            </ControlTemplate>
            </Setter>
        </Style>
    </Button.Styles>
</Button>
```

**To Reproduce**
1. Download the simple repro case from here: https://github.com/danipen/AvaloniaDashStyleBug
2. Execute the application

**Expected behavior**
The lines displayed on the screen should have a dashed style.

**Screenshots**
Executing the sample application in Avalonia `0.10.x` works as expected:
![image](https://user-images.githubusercontent.com/501613/187370497-e8545ba4-9eef-4233-b83e-0f140cb02a4b.png)

Executing the sample application with Avalonia `11.0-preview1` causes the bug:
![image](https://user-images.githubusercontent.com/501613/187370570-7f0c30f7-c03d-493a-94bb-d5acdbefaa07.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10
- Version 11.0-preview-1

**Comment by Takoooooo** [comment]
Seems the problem isn't in the StyledProperties,in the sample you provide you set e.g LineThickness property, which is StyledProperty and everything works as expected.
![image](https://user-images.githubusercontent.com/53405089/187669952-80f89c3a-b749-418f-98e3-53c52e1b9114.png)

**Comment by Takoooooo** [comment]
Also if i add this DashStyle as the Window resource and set it as the Staticresource everything works as expected.
![image](https://user-images.githubusercontent.com/53405089/187670606-a3a1d6d5-8048-477f-98b3-a5d41273d7a9.png)

**Comment by danipen** [comment]
Ok, I can workaround using a static resource in xaml, but maybe this is a regression since it worked fine in `0.10.x`...

**Comment by Takoooooo** [comment]
It actually sets the property but the values are default.
![image](https://user-images.githubusercontent.com/53405089/187671727-b2d10267-8553-4a4f-93af-0acaed3b0fff.png)
If i remove the property set from the XAML the value would be "null"

**Comment by Takoooooo** [comment]
If i am changing StyledProperty type to some random type and set it in the same way everything works as expected so i guess something is wrong with the DashStyle.
![image](https://user-images.githubusercontent.com/53405089/188130084-1c7b5a6e-d437-4afd-8d14-b4d5b4e3ee60.png)
![image](https://user-images.githubusercontent.com/53405089/188130144-9423bb4e-8526-4444-bedd-bc7c5480273c.png)

**Comment by Takoooooo** [comment]
ValueStore for property "Offset" shows only 1 value and the value is correct.
![image](https://user-images.githubusercontent.com/53405089/188138571-7920fb15-8c07-4fd0-afe1-04768297ea2c.png)
Same for "Dashes" property.
![image](https://user-images.githubusercontent.com/53405089/188139099-fcc9f9ee-047b-4c2b-90e1-0628306852a6.png)

**Comment by Takoooooo** [comment]
The problem seems to be in the default constructor, specifically in this line. If i remove it everything works as expected
![image](https://user-images.githubusercontent.com/53405089/188151189-0866561b-4b9a-4554-97a0-2a9697293ab2.png)
