### ISSUE TITLE
Calendar month names are not always visible

### ISSUE THREAD

**Issue by tomenscape** [AvaloniaUI/Avalonia#8864]
**Describe the bug**
It's possible to use `CalendarDatePicker` in such a way that the month names in the year view are not generated. The control displays blank tiles instead.

**To Reproduce**

1. Start the Control Gallery and navigate to the CalendarDatePicker tab
2. Open the calendar pop-up on any of the controls inside the tab
3. Click on the current year, at the top of the pop-up
4. Click outside the pop-up so that it closes
5. Re-open the pop-up
6. Click on the current year again

You will see this:

![image](https://user-images.githubusercontent.com/109803929/187515146-9227fd7e-37b4-45b6-9938-19c355fb0e35.png)

**Expected behavior**
Month names should always be visible in the year view, like this:

![image](https://user-images.githubusercontent.com/109803929/187515670-40769188-1b57-4b62-bff4-9857ffa6103c.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version 11 preview 1

**Comment by rabbitism** [comment]
![1665129771954](https://user-images.githubusercontent.com/14807942/194503953-8fbff09a-2bb9-4dfb-bdba-dcf9766193d7.jpg)
Through devtool I can see the text value is already assigned. 
And it works fine if compositor is disabled. seems to be a regression.
