### ISSUE TITLE
Layout precision error in Avalonia 11

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#8866]
**Describe the bug**
This does look to be an Avalonia issue. minimal repro:

```xaml
  <Border BorderBrush="Black"
          BorderThickness="1"
          Width="82"
          Height="82">
    <Panel Background="White" />
  </Border>
```

The issue only happens when a control (Panel in this case) with an opaque background is added as a child of the border. Looks like the border measurement isn't taking into account the rounded border thickness when laying out the child

**To Reproduce**
1. Create a new Avalonia application, 
2. Paste that xaml code.
3. Execute the application.

**Expected behavior**: Borders should be visible.
**Actual behavior**: Right and bottom borders are not visible (I'm using a 125% DPI screen. Working fine in 100% DPI and 350% DPI).

![image](https://user-images.githubusercontent.com/501613/187641735-ad212dec-63e3-40d7-b86d-16386b58f26e.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Version 11.0-preview1

**Comment by rabbitism** [comment]
You should set UseLayoutRounding as false.

**Comment by danipen** [comment]
Well, yes, using `UseLayoutRounding=false` is a workaround for this minimal repro, but I filled the bug because the same is working as expected in Avalonia `0.10.x` so it seems to be a regression.

**Comment by grokys** [comment]
Yeah it appears that the layout code for `Border` isn't taking into account the layout rounding of its own borders when measuring/arranging the child. It's a regression from 0.10.x that was probably caused by #7867 and later fixes.

**Comment by rabbitism** [comment]
> Well, yes, using `UseLayoutRounding=false` is a workaround for this minimal repro, but I filled the bug because the same is working as expected in Avalonia `0.10.x` so it seems to be a regression.

ok, I don't know how it works before, I just start using last week with 11 preview.
