### ISSUE TITLE
`AlternatingRowBackground` overrides `DataGridRow`'s `Background` style in Avalonia 11?

### ISSUE THREAD

**Issue by IhateTrains** [AvaloniaUI/Avalonia#8876]
**Describe the bug**
I have a DataGrid that I use for displaying logs. It uses a style with a ValueConverter to change row color depending on log level (orange for warnings, for example). With Avalonia 0.10 it worked perfectly. With 11 Preview 1 AlternatingRowBackground overrides the color, so only every other row is correctly colored.

```
<DataGrid Name="LogGrid" Grid.Column="0" Grid.Row="1"
          Margin="0,20,0,0"
          Items="{Binding FilteredLogLines}"
          AutoGenerateColumns="False"
          CanUserReorderColumns="False"
          CanUserSortColumns="False"
          RowBackground="Transparent"
          AlternatingRowBackground="Transparent"
          VerticalScrollBarVisibility="Visible"
          GridLinesVisibility="All"
          >
    <DataGrid.Resources>
        <vc:LogLevelToColorNameConverter x:Key="LogLevelToColorNameConverter"/>
    </DataGrid.Resources>
    <DataGrid.Styles>
        <Style Selector="DataGridRow">
            <Setter Property="Background" Value="{Binding Level, Converter={StaticResource LogLevelToColorNameConverter}}" />
        </Style>
    </DataGrid.Styles>
    <DataGrid.Columns>
        <DataGridTextColumn Header="{ns:Loc LOGTIME}" IsReadOnly="True" Binding="{Binding Timestamp}" />
        <DataGridTextColumn Header="{ns:Loc LOGSEVERITY}" IsReadOnly="True" Binding="{Binding LevelName}" />
        <DataGridTextColumn Header="{ns:Loc LOGMESSAGE}" IsReadOnly="True" Binding="{Binding Message}" />
    </DataGrid.Columns>
</DataGrid>
```

**To Reproduce**
1. Create a DataGrid with `RowBackground="Transparent"` and `AlternatingRowBackground="Transparent"`.
2. Add a style changing DataGridRow's `Background` to some solid color.
3. Add a few rows to the grid.
4. See that `AlternatingRowBackground` overrides the style we set.

**Expected behavior**
DataGridRow's `Background` property should override `AlternatingRowBackground`, like it did in Avalonia 0.10.

**Screenshots**
![image](https://user-images.githubusercontent.com/29546927/187963084-227fe363-f71a-4de8-9de0-6e425d92e633.png)

**Desktop:**

- OS: [Windows 11]
- Version [11.0.0 Preview1]

**Comment by maxkatz6** [comment]
@AvaloniaUI/core what if we remove AlternatingRowBackground and RowBackground properties in 11.0? As users can use more flexible nth-child selector now.
