### ISSUE TITLE
Linked AvaloniaResource items are compiled with incorrect names

### ISSUE THREAD

**Issue by tomenscape** [AvaloniaUI/Avalonia#8877]
**Describe the bug**
The Avalonia resource compiler does not account for resources which are linked into the project from other directories. These resources do not have the expected resource name and cannot be used.

**To Reproduce**

1. Choose a file outside your project directory and find it in the "Add Existing" window in Visual Studio
2. Click on "Add As Link"
  ![image](https://user-images.githubusercontent.com/109803929/187979465-38f0eabf-2c5f-4777-8319-99a060fea758.png)
3. Change the item's compile type to `AvaloniaResource`
4. You will now have something similar to this in your project:
   ```<AvaloniaResource Include="..\..\Resources\about.png" Link="Resources\about.png" />```
5. Compile

The following line will appear in the build output:

```
avares -> name:/../../Resources/about.png, path: [project dir]\..\..\Resources\about.png, size:463, ItemSpec:..\..\Resources\about.png
```

The resource is found and correctly compiled into the assembly, but its name is incorrect. As a result the resource cannot be used.

If you try to use `avares://[assembly]/../../Resources/about.png` as an image source, this exception is thrown:

```
System.IO.FileNotFoundException: 'The resource avares://[assembly]/Resources/about.png could not be found.'
```

**Expected behavior**
The value of the "Link" attribute should be used as the resource name.

**Desktop (please complete the following information):**

- OS: Windows
- Version 11 preview 1

**Comment by kekekeks** [comment]
Path is being extracted from the ItemSpec here - https://github.com/AvaloniaUI/Avalonia/blob/41871e8c7ca9dc9a4f5183c1ba54fc655dfbaa2e/src/Avalonia.Build.Tasks/GenerateAvaloniaResourcesTask.cs#L72

We probably need to have a separate `Source` constructor that accepts a path from the Link
