### ISSUE TITLE
Compiled Binding don't work with a ViewModelLocator 

### ISSUE THREAD

**Issue by Tenjim** [AvaloniaUI/Avalonia#8881]
**Describe the bug**
I want to use CompiledBinding with a ViewModelLocator as a StaticRessource

**To Reproduce**

1. Create a view
2. Declare your viewmodel into App.axaml as a StaticResource
3. Bind your viewmodel and set CompileBindings into the view like this : 
```
DataContext="{Binding MainWindowViewModel, Source={StaticResource ViewModelLocator}}"
x:DataType="viewModels:MainWindowViewModel"
x:CompileBindings="True"
```

**Expected behavior**
Using compiledBinding with my ViewModelLocator

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows/Mac
- Version Avalonia 0.10.17

**Comment by timunie** [comment]
You set DataType to be MainWindowViewModel but you try to bind to ViewLocator. So DataType seems to be wrong.

**Comment by maxkatz6** [comment]
StaticResource returns an object. "object" type doesn't have "MainWindowViewModel" property. You need either cast in the binding or use ReflectionBinding.

**Comment by Tenjim** [comment]
> StaticResource returns an object. "object" type doesn't have "MainWindowViewModel" property. You need either cast in the binding or use ReflectionBinding.

There is a way to cast my StaticRessource in the binding ?

**Comment by timunie** [comment]
See: https://github.com/AvaloniaUI/Avalonia/issues/3635#issuecomment-1178553552 for an example.

**Comment by Tenjim** [comment]
Hi guys, 

Just test this comment and it won't work for me. My ViewModelLocator have all of my viewmodel as a singleton for dependency injection.
I don't understand why we need $parent for this case because we don't need to find ancestor. 

I just trying to cast my ViewModelLocator into my binding, something like this :

`DataContext="{Binding (controls:ViewModelLocator).MainWindowViewModel }"`

Or maybe we can cast a instance of my ViewModelLocator into my axaml.cs and bind on it ? 
Is it possible ?

**Comment by timunie** [comment]
I also think your x:DataType is wrong. It seems to be ViewModelLocator on the root node. Maybe you can prepare a minimal sample and create a new Repo for it. Then we can see what's the best solution.

**Comment by Tenjim** [comment]
Hi, 
I have done a repo to reproduce what is my issue

[my repo](https://github.com/Tenjim/AvaloniaSampleCompiledBinding)

I have added two "TODO Remarks" when I'm struglling using compiledBinding.
