### ISSUE TITLE
Could we use Avalonia Controls to create QRCode image?

### ISSUE THREAD

**Issue by lilongsswang** [AvaloniaUI/Avalonia#8886]
In linux desktop, while non-mono environment is providing, should we find a way out to create a QRCode bitmap?

I mean, this feature, could help us parse QRCode image, and create an Avalonia.Media.Imaging.Bitmap type imagine.

**Comment by robloo** [comment]
See: https://github.com/MikeCodesDotNET/Avalonia-QRCode

There are many ways to do this and a WritableBitmap allows you to generate an image from C#.

This type of thing is probably too specialized to pull into Avalonia itself.

**Comment by mysteryx93** [comment]
Definitely too specialized to put directly in Avalonia.

1. It would make the base libraries heavier when most users don't need it.
2. There are many ways to implement this, and someone who needs it would probably use a library with a more advanced implementation anyway.

**Comment by jmacato** [comment]
I agree with @robloo and @mysteryx93. This is not meant to be included in the core Avalonia library due to being too specialized.

**Comment by lilongsswang** [comment]
Get it, and appreciate your opinions.
