### ISSUE TITLE
The window freezes when clicking on the title bar when "ExtendClientAreaToDecorationsHint = true" (Windows / 0.10.18)

### ISSUE THREAD

**Issue by fr-Pursuit** [AvaloniaUI/Avalonia#8888]
**Describe the bug**

When `ExtendClientAreaToDecorationsHint = true`, the Window freezes (ie: the rendering seems to be temporary halted) when the title bar is pressed.
This is particularly visible if something is moving on the screen (like an indeterminate progress bar), or if the client-drawn title bar has a background that changes color when the window is focused.

**To Reproduce**

- Create a Window with `ExtendClientAreaToDecorationsHint = true`
- Add an indeterminate progress bar to it
- Click on the title bar (without releasing the mouse button)
- See the progress bar being temporarily frozen

You can also:

- Apply a style to the title bar to make its background color change when the Window is focused
- Unfocus the Window
- Click on the title bar (without releasing the mouse button)
- See the title bar's background color not changing instantly when the Window is focused

**Expected behavior**
The rendering should continue to be updated when the title bar is pressed (ie: indeterminate progress bars should continue moving, and the title bar's background color should change instantly when appropriate)

**Desktop (please complete the following information):**

OS: Windows 10 21H2

**Additional context**

In a development environment, the freeze is relatively minor: it only lasts ~1 second (or exactly until the user starts dragging the window), and then the window's rendering resumes as usual (even if the title bar is still pressed)

However, when publishing the application for the `win-x64` platform, the behaviour changes: when clicking on the title bar, the window's rendering is halted until the bar is released, even if the user starts dragging it. In my tests, I published my project as a framework-independant win-x64 executable (it didn't matter if a single file was produced or not, or if native libraries were included for self-extraction or not)

I tracked down the issue to the `Avalonia.Angle.Windows.Natives` package (0.10.18 uses version 2.1.0.2020091801). It contains a native library called `av_libglesv2.dll`, in the `runtimes/win7-x64` directory. It seems to be loaded in the dev environment, but is not included when the application is published for the `win-x64` platform.

I created a modified `Avalonia.Angle.Windows.Natives` package that contains the same library, but in the `runtimes/win-x64` directory, and it did get included when I published the app for `win-x64`. As a result, I got the same, less severe behaviour as I got in my dev env.

An interesting side effect, though, was that the memory usage of the app increased. As stated in #5646 (by [Oxygels](https://github.com/Oxygels)), Avalonia uses ~100 Mo of RAM in its cross-platform state (ex: in the development environment), but has a significantly lower memory usage when published for `win-x64` (In my case, I got it down to ~60 Mo). It seemed the lower memory usage was caused by the app not using the `av_libglesv2.dll` lib bundled with Avalonia. I'm guessing it either used a version of the lib included in the OS, or didn't use it at all (if it's even possible).

**Comment by ymg2006** [comment]
I was wondering if I have made a custom title bar extended to the decorations and an indeterminate progress bar. Neither in debug nor in release mode does it get stopped while dragging the window from my own title bar.
I may add I have implemented custom dragging and custom buttons on windows 11.

**Comment by fr-Pursuit** [comment]
> I was wondering if I have made a custom title bar extended to the decorations and an indeterminate progress bar. Neither in debug nor in release mode does it get stopped while dragging the window from my own title bar. I may add I have implemented custom dragging and custom buttons on windows 11.

Interesting. I guess the problem lies in the code handling the default behavior of the title bar.

On another note, the part about `av_libglesv2.dll` seems to be related to #6028.

**Comment by hez2010** [comment]
I hit the same issue immediately after I published my app using `dotnet publish -c Release -r win-x64`.
