### ISSUE TITLE
ScrollView cannot contain other layouts and ListBoxes

### ISSUE THREAD

**Issue by hui3215** [AvaloniaUI/Avalonia#8892]
**Describe the bug**
When the layout is as follows the code below, the rendering of the program has problems

**To Reproduce**
A black bar appears for page rendering when sliding

```xml
 <ScrollViewer >
        <StackPanel>
            <TextBlock Text="Avalonia" Width="600" Height="400" Background="pink"></TextBlock>
            <ListBox Items="{Binding Type}">
            </ListBox>
        </StackPanel>
    </ScrollViewer>
```

**Expected behavior**
Normal sliding without black areas

**Screenshots**
![QQ截图20220905151604](https://user-images.githubusercontent.com/53279456/188390026-7828328c-87a0-41b0-8473-59021ae67473.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 22 
- Version  0.10.18

**Additional context**

**Comment by timunie** [comment]
Probably you need Wayland support which is WIP? See #8352 

Maybe you can try out the linked PR directly and see if your issue would be solved?

**Comment by maxkatz6** [comment]
Tested on my machine. Works with no issues as you have.
Can you test the same code on another machine? Or try it with 11.0 preview?
Also, keep in mind that ListBox inside of another ScrollViewer won't work very well with virtualization.
