### ISSUE TITLE
Control.DataContextChanged event without old value

### ISSUE THREAD

**Issue by MonkAlex** [AvaloniaUI/Avalonia#890]
Want to read `OldValue` and `NewValue` on event.

**Comment by grokys** [comment]
I'm not sure this is necessary. `OnDataContextChanging`/`DataContextChanged` are intended for very specific use-cases around bindings. If you want the old and new values of the `DataContext` property, you should just be able to use:

```
control.GetObservableWithHistory(Control.DataContextProperty)
```

**Comment by MonkAlex** [comment]
Okay, i have wpf code:

    this.DataContextChanged += OnDataContextChanged;
    private void OnDataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
    {
      var oldValue = e.OldValue as IProcess;
      if (oldValue != null)
        oldValue.StateChanged -= OnStateChanged;

      var value = e.NewValue as IProcess;
      if (value != null)
        value.StateChanged += OnStateChanged;
    }

In avalonia i need change code to this?

    var dataContextObs = this.GetObservableWithHistory(Control.DataContextProperty);
    dataContextObs.Subscribe(OnDataContextChanged);
    private void OnDataContextChanged(Tuple<object, object> sub)
    {
      var oldValue = sub.Item1 as IProcess;
      if (oldValue != null)
        oldValue.StateChanged -= OnStateChanged;

      var value = sub.Item2 as IProcess;
      if (value != null)
        value.StateChanged += OnStateChanged;
    }

Or how do it? WPF events do it simple =)

**Comment by grokys** [comment]
Yes, that would work. If you wanted to use events however you could do it that way too by subscribing to the `PropertyChanged` event handler:

```
            control.PropertyChanged += (s, e) =>
            {
                if (e.Property == Control.DataContextProperty)
                {
                    var oldValue = e.OldValue;
                    var newValue = e.NewValue;
                }
            };
```

What you must realise is that you can do this for *any* `AvaloniaProperty` - in WPF listening to any property change is difficult and `DataContext` is the _exception_ to the rule as it has its own event. In Avalonia, `DataContext` is just another property so we don't need to make an exception to listen to `DataContext` changing.

**Comment by MonkAlex** [comment]
Thanks, its work.
