### ISSUE TITLE
Add `Ctrl+Insert` and `Shift+Insert` as standard hotkeys for text copy/paste

### ISSUE THREAD

**Issue by DmitryZhelnin** [AvaloniaUI/Avalonia#8901]
**Is your feature request related to a problem? Please describe.**

Now only `Ctrl+C` and `Ctrl+V` hotkeys are working for text copy/paste when using `TextBox`.
I believe that `Ctrl+Insert` and `Shift+Insert` should be added too as it works everywhere except Avalonia.

**Comment by maxkatz6** [comment]
We have this default hot key configuration
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Input/Platform/PlatformHotkeyConfiguration.cs

Which can be modified per platform specifics
https://github.com/AvaloniaUI/Avalonia/blob/95b9492ccf0fd4b8483e6d79b9ea6345c6c8e97b/src/Windows/Avalonia.Win32/Win32Platform.cs#L161

Or developer can get this class from the locator and modify in runtime.
Is `Ctrl+Insert` hotkey windows specific or also works on other OSs? From what I remember it comes from DOS times.

**Comment by DmitryZhelnin** [comment]
> Or developer can get this class from the locator and modify in runtime.

That's actually really nice and solves my frustration.


> Is `Ctrl+Insert` hotkey windows specific or also works on other OSs? From what I remember it comes from DOS times.

I've been using it for ages on various Windows OSs and several Linux Distributions (Debian based). Don't know anything about MacOS.

**Comment by comesx4** [comment]
I'm pleased to commit those hotkeys to default setting [PlatformHotkeyConfiguration.cs](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Input/Platform/PlatformHotkeyConfiguration.cs), how about this? @maxkatz6

**Comment by maxkatz6** [comment]
@comesx4 yes, at least for win and lin it makes sense to add these hotkeys. Not sure about macos tho.
