### ISSUE TITLE
`AutoCompleBox` drop-down cannot be reliably opened

### ISSUE THREAD

**Issue by tomenscape** [AvaloniaUI/Avalonia#8903]
**Describe the bug**
Opening the drop-down of `AutoCompleteBox` is unreliable and mysterious, for both users and control consumers. Behaviour is particularly confusing when `MinimumPrefixLength` is 0.

**To Reproduce**

1. Open the Avalonia Control Gallery and focus on an `AutoCompleteBox` with some items defined.
2. Press the down arrow key
3. Nothing happens
4. Type a character that matches an item
5. Cancel the pop-up
6. Press the down arrow key
7. The drop-down opens again
8. Clear the box and type a character or string which doesn't match any items
9. Press the down arrow key
10. Nothing happens.

**Expected behavior**
The autocomplete drop-down should open whenever the down key is pressed, or at least some feedback should be given as to why it did not open.

This bug also means that the drop-down cannot be opened from the outside unless certain pre-conditions that the control decides on are met. I expect setting the `IsDropDownOpen` to always open the drop-down.

**Desktop (please complete the following information):**

- OS: Windows
- Version 11 preview 1

**Comment by tomenscape** [comment]
I'm seeing mixed results here. I just managed to make the popup open by pressing the down key...but I was unable to reproduce that behaviour after restarting my application.

**Comment by timunie** [comment]
Can it be that you handle the key events somewhere else? 

DevTools `[F12]` has a tab to watch events.

**Comment by Artfunkel** [comment]
I can reproduce this in the controls gallery. I briefly debugged the control and the lines I mentioned in the bug report are being executed.

**Comment by tomenscape** [comment]
I can reproduce this in the controls gallery. I briefly debugged the control and the lines I mentioned in the bug report are being executed.

**Comment by tomenscape** [comment]
I see the issue now: the drop-down only opens if there is at least one character typed into the box. I expected it to open even if there are no characters.

**Comment by tomenscape** [comment]
Looks like the weird behaviour when `MinimumPrefixLength == 0` was introduced when fixing #1554.

**Comment by timunie** [comment]
If you find a better way, feel free to provide a PR

**Comment by tomenscape** [comment]
I've been digging into the problem in spare moments, and AutoCompleteBox makes too many assumptions about how it will be used to fit our use case(s). Trying to unpick it all without breaking default behaviour was a nightmare.

One way to move ahead is by extracting the core autocomplete functionality into an attached behaviour, and then wrapping new controls of our own design around it.

**Comment by Philltorian** [comment]
I ran into the same issue a while back, I managed to get the desired effect (arrow down and F4 opens the dropdown when blank) by using the attached behaviour.

[AutoCompleteZeroMinimumPrefixLengthDropdownBehaviour.cs.txt](https://github.com/AvaloniaUI/Avalonia/files/10119037/AutoCompleteZeroMinimumPrefixLengthDropdownBehaviour.cs.txt)

**Comment by timunie** [comment]
Good catch. Are you willing to file a PR to solve this issue? Would be appreciated I think 👍

**Comment by AtomCrafty** [comment]
Yes, already on it 👍
