### ISSUE TITLE
Using text inside TransitioningContentControl results in the text being scaled down while animating

### ISSUE THREAD

**Issue by BaseCrusher** [AvaloniaUI/Avalonia#8917]
**Describe the bug**
When having text inside a TransitioningContentControl and using the CrossFade transition the text displayed is being shrunked for the time of the animation.

**To Reproduce**

1. Create a view with TransitioningContentControl.
2. Place a TextBlock as content for the TransitioningContentControl (Maybe make it the text a litle bigger to see it more easily).
3. Change the content of the TransitioningContentControl.
4. Observe that the text is smaller while the animation is playing

**Expected behavior**
Text should keep it's size when transitioning

**Desktop (please complete the following information):**

- OS: Windows (others might be affected as well)
- Version 0.10.18

**Comment by maxkatz6** [comment]
I suppose it should be fixed with https://github.com/AvaloniaUI/Avalonia/pull/9803
If not, please let me know
