### ISSUE TITLE
WinForms/WPF Embedding does not account for high-DPI screens

### ISSUE THREAD

**Issue by jkoritzinsky** [AvaloniaUI/Avalonia#892]
Start up the WinForms/WPF interop sample on a high DPI screen, and the Control Catalog will not be drawn at the correct scale to account for DPI.

**Comment by kekekeks** [comment]
Fixed by https://github.com/AvaloniaUI/Avalonia/commit/4d3d42b6002621bf7316f6e92aaf09080a34d5a8
