### ISSUE TITLE
Flickering `ComobBox:pointerover` style

### ISSUE THREAD

**Issue by tomenscape** [AvaloniaUI/Avalonia#8926]
**Describe the bug**
The `ComboBox:pointerover` pseudoclass flickers on and off after the user closes the drop-down menu by clicking on the `ComboBox`

**To Reproduce**

1. Edit [the fluent theme's `ComboBox:pointerover` style](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/ComboBox.xaml#L159-L162) to set the control's background to red
2. Start the Control Gallery
3. In the "ComboBox" tab, click on one of the controls to open its drop-down
4. Close the drop-down by clicking on the main `ComboBox` element, but do not release the mouse
5. Move the pointer over the `ComboBox` while holding the mouse down

The red background will flicker on and off for as long as the mouse button is held down and the pointer is over the `ComboBox`. The effect is noticeable even if the user just clicks once without holding the button down.

**Expected behavior**
The red colour should remain active the whole time that the user has their mouse over the control, regardless of which mouse buttons are pressed.

**Screenshots**

https://user-images.githubusercontent.com/109803929/189374629-1fac0863-dd95-44fd-9e2a-a95010d9a662.mp4

In this video I open the drop-down (the PopUp was not captured by my screen recorder) and then close it before dragging the mouse over the `ComboBox`. The background flickers. I then release the mouse button and move the pointer over the `ComboBox` again, and this time the background remains active.

**Desktop (please complete the following information):**

- OS: Windows
- Version 11 preview 1

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/8918#issuecomment-1241420761

**Comment by tomenscape** [comment]
I'll close this since the main issue is fixed, and the secondary issue of styles not updating until the mouse moves is not specific to ComboBox.
