### ISSUE TITLE
How to binding Command Dropdown Avanolia

### ISSUE THREAD

**Issue by LorenVeri** [AvaloniaUI/Avalonia#8933]
I want when user change dropdown item, it command in viewmodal is executed

`
<DropDown
						PlaceholderText="Thời gian"
							Name="ListDateTime"
							Items="{Binding ListDateTime}"
							SelectedIndex="{Binding SelectedSalesPeriod}"
							Height="25"
							VerticalAlignment="Center">
						<DropDown.ItemTemplate>
							<DataTemplate>
								<TextBlock Text="{Binding Name}"/>
							</DataTemplate>
						</DropDown.ItemTemplate>
					</DropDown>
`

**Comment by timunie** [comment]
I don't think this is a bug, but a question. We have a telegram chat for this and a discussion section. Next time please use one of those possibilities. 

Thanks.


To your question: you may use WhenAnyValue in your ViewModel and listen to selected item or index changed.

**Comment by LorenVeri** [comment]
@timunie Can you give detailed instructions? 
I binding list object to dropdown. I have  SelectedDate command, I want when customer click dropdown item SelectedDate is handler

**Comment by timunie** [comment]
https://www.reactiveui.net/docs/handbook/when-any/#:~:text=ReactiveUI%20provides%20several%20variants%20of%20WhenAny%20to%20help,to%20get%20notifications%20when%20property%20on%20objects%20change.

**Comment by timunie** [comment]
If you need further support please provide a sample showing what is not working for you

**Comment by LorenVeri** [comment]
@timunie thank you very much, 
I solved my problem
