### ISSUE TITLE
Chinese character is messy code in Project.Web

### ISSUE THREAD

**Issue by ismlsmile** [AvaloniaUI/Avalonia#8938]
1. Project is created by "Avalonia Cross Platform Application(AvaloniaUI) " template in VS 2022
2. It is ok in Project.Desktop

![1](https://user-images.githubusercontent.com/1876179/189564678-6f136de5-9f24-499f-8969-9e63c109a294.png)

**Comment by rabbitism** [comment]
I think this is something related to fonts. All avalonia web fonts are mono for reason I don't know

**Comment by rabbitism** [comment]
> Embedd a font into your application and define it as a fallback like so:
> 
> https://fonts.google.com/noto/specimen/Noto+Sans+TC
> 
> ```
> .With(new FontManagerOptions
> {
>     FontFallbacks = new[]
>     {
>         new FontFallback
>         {
>             FontFamily = new FontFamily("avares://YourAssembly/FontFolder#Noto Sans TC")  
>         }
>     }
>  }
> ```

Is it possible for Avalonia web apps to utilize system fonts?

**Comment by ly5222518000** [comment]
使用资源中的自定义字体，亲测有效
<TextBlock Text="你好" FontFamily="/assets/fonts/xxx.ttf#xxx"/>
貌似只有ttf的字体有效

**Comment by rabbitism** [comment]
@ly5222518000 Hi, do you know how to use Source Han Sans SC? I cannot find the proper typeface name.

**Comment by memorydream** [comment]
> @ly5222518000 Hi, do you know how to use Source Han Sans SC? I cannot find the proper typeface name.

You should can use some font viewer get it

I use `Typeface.FromFile()` load a font then get font's family name, like this:
```
public CustomFontManagerImpl()
{
        var filePath = Path.Combine(ProgramInfo.BaseDirectory, "Assets/Fonts/SourceHanSansSC-Normal.otf");

        _defaultSKT = SKTypeface.FromFile(filePath);
        _defaultTypeface = new Typeface($"{filePath}#{_defaultSKT.FamilyName}");

        _customTypefaces = new[] { _defaultTypeface };
        _defaultFamilyName = _defaultTypeface.FontFamily.FamilyNames.PrimaryFamilyName;
}
```

Because I got different SourceHanSansSC family name between Windows and Linux

**Comment by maxkatz6** [comment]
> Is it possible for Avalonia web apps to utilize system fonts?

Web browser doesn't have APIs to get system fonts information. So, no.

**Comment by MikiraSora** [comment]
有办法能使用浏览器内置的字体吗
我的Browser项目也是无法显示非英文内容，但如果需要自带字体的话，动辄>10mb的大小。这对于部署以及流量来说是比较难以接受的
