### ISSUE TITLE
[CompositionGenerator] CS0219 The variable 'changesVar' is assigned but its value is never used

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#8940]
**Describe the bug**
CS0219 The variable 'changesVar' is assigned but its value is never used

https://github.com/AvaloniaUI/Avalonia/blob/de28c5ec933388171a0c6a9cffa047fe4208aa68/src/tools/DevGenerators/CompositionGenerator/Generator.cs#L137-L138

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version de28c5ec933388171a0c6a9cffa047fe4208aa68

**Additional context**

**Comment by workgroupengineering** [comment]
> https://github.com/AvaloniaUI/Avalonia/blob/de28c5ec933388171a0c6a9cffa047fe4208aa68/src/tools/DevGenerators/CompositionGenerator/Generator.cs#L137-L138


Can it be removed?

**Comment by kekekeks** [comment]
Probably,yes
