### ISSUE TITLE
ToggleSwitch knob resetting position a while after knob dragging is over (11.0.0-preview1)

### ISSUE THREAD

**Issue by appleneko2001** [AvaloniaUI/Avalonia#8958]
**Describe the bug**
avaloniaUI allows you dragging knob of ToggleSwitch than click it since [commit: 75c10992a9](https://github.com/AvaloniaUI/Avalonia/commit/75c10992a9071f6cd8b1b9e179aa77f5655bfa10). It has worked properly before 11.0.0-preview1. There was a problem I observed is the knob always resetting to zero value when you complete the flow of dragging knob in any state. After some frames it corrects position instead of transitioning movement. 

**To Reproduce**
This can be done on any themes with `ToggleSwitch` knob dragging feature supported. Here I provide how I reproduced this glitch in official Avalonia Control Gallery

1. Go to 'ToggleSwitch'
2. Drag the knob of any `ToggleSwitch` control.
3. Drag to the on state
4. Knob resetting position in a few frames and corrected position after that. The issue I described above.

**Expected behavior**
Knob should moves fine, no position resetting. Here I have Control Gallery built on avalonia 0.10.14 and recorded gif animation:
![1](https://user-images.githubusercontent.com/38249047/190033220-8dfa587d-63e5-48d6-8f32-0f021383549e.gif)

**Screenshots**
Here I recorded gif animations. Those gifs can explain this issue easily.
In Avalonia Control Gallery:
![1](https://user-images.githubusercontent.com/38249047/190032811-a565cc0a-b748-4f7e-8e39-2eaef40fc3f6.gif)

In Material.Avalonia Demo:
![2](https://user-images.githubusercontent.com/38249047/190032976-b395be70-36c3-4979-b1ba-b25eb3d1cc3e.gif)

**Desktop (please complete the following information):**

- OS: Windows OS 21H2
- Version 11.0.0-preview1

**Additional context**
I think something with transition system wrong or [might this line](https://github.com/AvaloniaUI/Avalonia/blob/75c10992a9071f6cd8b1b9e179aa77f5655bfa10/src/Avalonia.Controls/ToggleSwitch.cs#L180) but I dont sure. I cant build avalonia library from my device even I reinstalled my visual studio 2022 and installed dotnet sdks.

**Comment by maxkatz6** [comment]
Can you check if it was fixed after this PR? https://github.com/AvaloniaUI/Avalonia/pull/8918

**Comment by appleneko2001** [comment]
Hi @maxkatz6 !
Ok I try it now, any results I will post comments here. Thanks for pay attention to this issue)

**Comment by appleneko2001** [comment]
No more resetting position now, just no transition now
![1](https://user-images.githubusercontent.com/38249047/190160774-eb850869-6e50-41d7-8a36-064ea464777f.gif)

**Comment by robloo** [comment]
I suppose it's possible something was missed in the renaming of template parts: https://github.com/AvaloniaUI/Avalonia/pull/8793. Just a thought, not saying that's it.

**Comment by maxkatz6** [comment]
Seems to be fixed by https://github.com/AvaloniaUI/Avalonia/pull/8793/files
Please let me know if not.
