### ISSUE TITLE
Avalonia app does not run on Ubuntu

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#897]
After Avalonia updating to the latest alpha (0.4.1-build2658-alpha) app does not work on Ubuntu. It crashes with the following exception:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Avalonia.Gtk.GtkPlatform' threw an exception. ---> System.DllNotFoundException: libglib-2.0-0.dll
```

ControlCatalog app is not working too due to the same error.

**Comment by kekekeks** [comment]
Remove windows-targeted GTK-related binaries from your output directory.
