### ISSUE TITLE
[DataGrid] AvaloniaList<T> implementation of InsertRange does not correctly invoke _collectionChanged

### ISSUE THREAD

**Issue by ghasttear1** [AvaloniaUI/Avalonia#8970]
When trying to use `AvaloniaList<T>` and its `AddRange` method, I found that my `DataGrid` control only updated one element rather than the expected many. After looking into the source I believe I found the problem.

**Problem:**
`InsertRange` in `AvaloniaList<T>` implementation calls `NotifyAdd` which invokes the `_collectionChanged` event with `NotifyCollectionChangedAction.Add` which is meant for single item changes. `InsertRange` should instead be calling with `NotifyCollectionChangedAction.Reset` instead which is meant for large changes.

**Consequences:**
Anyone who attempts to use `AvaloniaList<T>` with the `InsertRange` method or more likely used `AddRange` method with a control that listens to `CollectionChanged` will not be updated correctly.

**Workaround:**
After calling `AddRange` or `InsertRange` use reflection to manually invoke the event with correct `NotifyCollectionChangedAction`.
```cs
var eventDelegate = typeof(AvaloniaList<T>).GetField("_collectionChanged", BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(this) as NotifyCollectionChangedEventHandler;
eventDelegate?.Invoke(this, new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));
```

**To Reproduce**

1. Create a `DataGrid` control in a window. (Using `DataGrid` as that is how I found out the issue and what I have experience with)
2. Bind an `AvaloniaList<T>` to Items.
3. Try update the list with `AddRange` or `InsertRange` using a collection with 2 or more elements.
4. Notice that only 1 element will be added.

**Expected behavior**
After using `AddRange` or `InsertRange` all items should be represented in the `DataGrid`

**Screenshots**
N/A

**Desktop:**
- OS: Linux (openSUSE Tumbleweed)
- Version: 0.10.18

**Comment by rabbitism** [comment]
I believe this is an issue with DataGrid, because it works as expected in ListBox.

**Comment by robloo** [comment]
Also, FYI: https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/2722#issuecomment-452137476

The Silverlight version of the DataGrid (same source using in the UWP Windows Community Toolkit and here in Avalonia) has some issues with supporting only a subset of the collection changed event actions.

**Comment by maxkatz6** [comment]
Yes, it is very specific to a data grid

**Comment by maxkatz6** [comment]
> InsertRange in AvaloniaList<T> implementation calls NotifyAdd which invokes the _collectionChanged event with NotifyCollectionChangedAction.Add which is meant for single item changes. InsertRange should instead be calling with NotifyCollectionChangedAction.Reset instead which is meant for large changes.

It's not correct behavior. On bulk insert there should not be a Reset event. AddRange can be handled correctly and is handled correctly with other items controls, except DataGrid. 

As a workaround, you can have a custom INotifyCollectionChanged collection that will always reset the source.

**Comment by ghasttear1** [comment]
I see, thanks all for clearing up the issue and my mistake in identification of the issue. It seems the issue title and description incorrectly describe the issue, I will probably close this issue and consider making a new one mentioning this issue that is more accurate to the actual issue within data grid.
