### ISSUE TITLE
IsChecked CompiledBinding to code behind sets background incorrectly

### ISSUE THREAD

**Issue by redrabbit007** [AvaloniaUI/Avalonia#8974]
**Describe the bug**
I have a ToggleSwitch where the IsChecked property is set with a CompiledBinding to a property in its own code-behind. The property only has a getter, and can be set to either true or false, it doesn't make a difference in the outcome. When I run the program the ToggleSwitch says off (even if the property is set to true), and the background of the ToggleSwitch is blue as though the switch was on.

**To Reproduce**

Create a new View:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:v="using:AvaloniaCheckedBug.Views"
        xmlns:vm="using:AvaloniaCheckedBug.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaCheckedBug.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="AvaloniaCheckedBug"
        x:DataType="v:MainWindow">
  <ToggleSwitch
    Grid.Row="0"
    IsChecked="{CompiledBinding SomeProperty}" />
</Window>
```

Add the property in the code-behind:

```
using Avalonia.Controls;

namespace AvaloniaCheckedBug.Views
{
  public partial class MainWindow : Window
  {
    public bool SomeProperty { get; } = true;

    public MainWindow()
    {
      InitializeComponent();
    }
  }
}
```

Run the application. The ToggleSwitch will say "off" but have a background set to blue as though it was on.

![image](https://user-images.githubusercontent.com/22695440/190528967-2e05ae85-e14c-40e8-b594-f954b7796a5b.png)

This issue doesn't seem specific to the ToggleSwitch. With a RadioButton the button is just left unchecked, even with the property set to true.

I noticed in the output window I get:
`Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll`

If I change the CompiledBinding to just a Binding the issue goes away.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 0.10.18

**Comment by timunie** [comment]
You only have a getter, so your binding must be one-way. By default IsChecked is two-way. Can you double check what happens if you set `Mode=OneWay` in your Binding?

**Comment by redrabbit007** [comment]
Adding `Mode=OneWay` doesn't seem to make a difference. But adding `DataContext="{Binding $self}"` to the Window fixes the issue.
