### ISSUE TITLE
Global menu bar support

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#898]
Currently there are at least two global menubars that we need to support: OS X and Ubuntu ones.

Preferably we should synchronize items from our own menubar. To do that we probably want to create a property for that menu bar in `Window` and alter `Window`'s template.

GTK has various ways of submitting items to the menu bar.

For OS X there is [gtk_mac_menu_set_menu_bar](https://wiki.gnome.org/Projects/GTK+/OSX/Integration#Documentation_for_the_Carbon_gtk-mac-integration_functions) that should be followed by `gtk_mac_menu_sync` calls when toplevel menu item list is changed.

Ubuntu provides `GtkMenuProxy` module that does some voodoo to detect window's menu, hide it and offload contents to system menubar. That voodoo doesn't always properly work, so it's disabled for some applications (notable example is MonoDevelop).

Starting from GTK3 there is [gtk_application_set_app_menu](https://developer.gnome.org/gtk3/stable/GtkApplication.html#gtk-application-set-app-menu) which sets "application" menu, which seems to be shown before any other menu items (at least on Ubuntu, according to docs). 

We might want to stick to using `gtk_application_set_app_menu`, since on OS X `gtk_mac_menu_set_menu_bar` operates on application level anyway. In this scenario we need to update menubar on window activation.

**Comment by kekekeks** [comment]
Ubuntu Unity is discontinued, so we only need to support OSX now.

**Comment by kekekeks** [comment]
The problem here is that on OSX menu bar is global for the *application*, there is no such thing as window menu. GTK merely emulates "window-owned" menus by appending them to the global menu bar on window activation.

I'm not quite sure if we need to have the same behavior. It might be quite handy since it's the way menus usually work on OSX, so people won't have to add menu items to each window. On the other hand Windows doesn't have the concept of "application" menu.

If we decide to use per-window menus, we need a way to sync menu bar items from our own menu system and a fallback for platforms that don't have global menu.

For the user it would look like:
```xml
<Window>
     <MainMenu>
        <MenuItem Header="Top level item">
             <MenuItem Header="Item"/> 
             <Separator/>
        <MenuItem>
     </MainMenu>
</Window>
```

It would be displayed in <Menu> control on Windows and synced to the main menu on OSX.

The problem here is that we can't really express items with extra controls. Our current way of adding checkboxes to menu items is setting `MenuItem`'s `Icon` property to something that displays a `CheckBox`. Obviously that won't work if we are converting our menu items to `NSMenuItem`. So we need to either add properties like `Image` and `IsChecked`.

We could try to create a [separate NSView for each NSMenuItem](https://developer.apple.com/documentation/appkit/nsmenuitem/1514835-view?language=objc), but that will make said items to look in a non-native way, since we have to do all the drawing manually.

What we could also do is to draw `MenuItem.Icon` property to RenderTargetBitmap and transfer the resulting icon to `NSMenu` image

**Comment by danwalmsley** [comment]
https://stackoverflow.com/questions/3436395/how-i-can-get-the-application-menu-in-cocoa

**Comment by kekekeks** [comment]
It seems that Linux global menu is still alive alive and well across non-Unity desktop environments. Here is the definition file for DBus interface: https://github.com/rilian-la-te/vala-panel-appmenu/blob/master/lib/dbusmenu-importer/com.canonical.dbusmenu.xml

**Comment by kekekeks** [comment]
Mkay, since this feature is getting a lot of interest lately, here is a proposal:

We introduce a `SimpleMenuItem` class derived from `TemplatedControl` with following properties:
- `string` `Header`
- `SimpleMenuItemToggleType` `ToggleType`
- `bool` IsToggled`
- `Bitmap` `Image`
- `AvaloniaList<ISimpleMenuItem>` `Children`

`SimpleMenuItemToggleType` enum: `None`, `Checkbox`, `Radio`. It maps directly to `toggle-type` from dbus-menu. On OSX `Checkbox` maps to the default `onStateImage`  while `Radio` maps to a custom image. At first we can only implement `None` and  `Checkbox`, but this should be an enum to provide backwards compatibility when we add `Radio`.

We make SimpleMenuItem and Separator implement a "marker" interface `ISimpleMenuItem`.

The default template of `SimpleMenuItem` would be a `MenuItem` with properties mapped to our "complex" menus.

`SimpleMenuItem` could later be used for "system-tray" menus for OSX and various Linux distros.

Then we add `MainMenu` control for the window that shows a MenuBar  with items or/and (APPMENU_SHOW_BOTH=1 environment should force us to show both) exports the items to the system.

IWindowImpl should now have `IMenuBarExporterSink MenuBarExporter { get; }` optional property. We might also go with `T GetFeature<T>()` approach for optional features, so exporter would be obtained by `PlatformImpl.GetFeature<ISimpleMenuExporterSink>()`.

Then we would have `SimpleMenuExporter` class that syncs `AvaloniaList<ISimpleMenuItem>` to `ISimpleMenuExporterSink`. The proposed API is 
`public static IDisposable Sync(AvaloniaList<ISimpleMenuItem> items, ISimpleMenuExporterSink sink)`

A separate exporter class is needed for implementing exported tray icon menus later.

**Comment by kekekeks** [comment]
https://github.com/KDE/kwayland/blob/master/src/client/protocols/appmenu.xml - KDE's global menu protocol for Wayland.

**Comment by danwalmsley** [comment]
https://stackoverflow.com/questions/21494005/cocoa-app-without-mainmenu-xib

**Comment by davidhenley** [comment]
Whats the status on this?

**Comment by kekekeks** [comment]
Implemented ages ago

**Comment by davidhenley** [comment]
Can you point me to the documentation? I didn't see it anywhere in the docs.

**Comment by kekekeks** [comment]
It looks like the docs somehow were lost alongside with the 0.9 release announcement.


You can define native menu items using `NativeMenu.Menu` attached property like this: https://github.com/AvaloniaUI/Avalonia/blob/fd64440ea0958898035167339b2f7e61a504a147/samples/ControlCatalog/MainWindow.xaml#L17-L55


To avoid copy-pasting the same items to a regular menu bar you can use `<NativeMenuBar/>` control.

**Comment by davidhenley** [comment]
OK thanks, hope the docs get back up soon!
