### ISSUE TITLE
failed to open packed App on macOS

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#8983]
**Describe the bug**
I used Dotnet.Bundle package and MSBuild command to generate macOS bundle. But the binary failed to start.
However, if I launch the application directly through the command line using:
```

/LauncherX.Avalonia.app/Contents/MacOS/LauncherX.Avalonia

```
The application will start normally.

**To Reproduce**

1. Add Dotnet.Bundle package
2. Add following configuration in .csproj:
```xml

<PropertyGroup Condition="'$(IsOSX)'=='true'">
    <CFBundleName>$(AssemblyName)</CFBundleName>
    <CFBundleDisplayName>$(AssemblyName)</CFBundleDisplayName>
    <CFBundleIdentifier>com.$(username).$(AssemblyName)</CFBundleIdentifier>
    <CFBundleVersion>1.0.0</CFBundleVersion>
    <CFBundlePackageType>APPL</CFBundlePackageType>
    <!--<CFBundleSignature>????</CFBundleSignature>-->
    <CFBundleExecutable>$(AssemblyName)</CFBundleExecutable>
    <CFBundleIconFile>Assets/app.icns</CFBundleIconFile>
    <NSPrincipalClass>NSApplication</NSPrincipalClass>
    <NSHighResolutionCapable>true</NSHighResolutionCapable>
    <CFBundleShortVersionString>1.0</CFBundleShortVersionString>
    <!-- Optional -->
    <NSRequiresAquaSystemAppearance>true</NSRequiresAquaSystemAppearance>
  </PropertyGroup>

```
3. use the following command to build:
```bash

dotnet restore -r osx-x64
dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-x64 -property:Configuration=Release -p:UseAppHost=true

```
4. get the bundle
<img width="114" alt="image" src="https://user-images.githubusercontent.com/25716486/190889544-a68724f6-c816-4bf6-82a6-f701a7e72b20.png">

**Expected behavior**
Application should launch successfully without crashing.

**Screenshots and Logs**
<img width="894" alt="image" src="https://user-images.githubusercontent.com/25716486/190889639-e6851481-002a-4dff-ae1a-948238700ca4.png">

[detail.txt](https://github.com/AvaloniaUI/Avalonia/files/9593215/detail.txt)

**Desktop (please complete the following information):**

- OS: macOS Monterey
- Version 12.6

**Comment by ahopper** [comment]
Your app appears to be throwing a managed exception, try logging it in Main in program.cs . One common cause of this is the current directory is different when a program is run as a .app .

**Comment by mysteryx93** [comment]
Bundle also contains stuff related to requested permissions. If the problem is not related to the working directory, it's probably permission-related.

**Comment by laolarou726** [comment]
> Your app appears to be throwing a managed exception, try logging it in Main in program.cs . One common cause of this is the current directory is different when a program is run as a .app .

But it seems I can run the executable using the terminal command.

**Comment by maxkatz6** [comment]
Also check Console macOS app, as it can contain additional information about your app why it was closed/crashed. Especially if it's related to some permissions or security related problems.

**Comment by ahopper** [comment]
> > Your app appears to be throwing a managed exception, try logging it in Main in program.cs . One common cause of this is the current directory is different when a program is run as a .app .
> 
> But it seems I can run the executable using the terminal command.

running as a .app runs in a different environment to running the exe directly as in your command line, one thing that is different is the working directory another is probably security options.  I have had exactly the same thing happen, logging the exception should tell you the issue.

**Comment by laolarou726** [comment]
Problem solved. I just changed the path for the conf file. Now everything is working as expected!
