### ISSUE TITLE
TextBox Control Input Chinese char, But the View is Messy Code that not Chinese Char? I'm not Override the textbox Style .look Picture

### ISSUE THREAD

**Issue by hubing53** [AvaloniaUI/Avalonia#8985]
![1663487184959_bfc22d18](https://user-images.githubusercontent.com/112156001/190891467-c707b049-1625-4f7f-addf-550f253c0bb0.png)

**Comment by timunie** [comment]
Can you try 11.0 preview1 of Avalonia? This should be supported in this prerelease.

**Comment by rabbitism** [comment]
Or you can set a default FontFamily that supports Chinese characters.
