### ISSUE TITLE
The width property value of the FormattedText type is empty.

### ISSUE THREAD

**Issue by rsdte** [AvaloniaUI/Avalonia#8987]
**Describe the bug**
The the width of the instance is empty when create a instance of the `FormattedText` type. but it is a high value.

**Screenshots**
![图片](https://user-images.githubusercontent.com/39526920/190913774-d22e98a3-f258-4769-aa63-945419e8948b.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 11-preview1

**Additional context**
view Screenshots

**Comment by Gillibald** [comment]
For future reference FormattedText is reporting two different width properties one that includes trailing whitespace and one that doesn't.

https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.formattedtext.widthincludingtrailingwhitespace?view=windowsdesktop-6.0#system-windows-media-formattedtext-widthincludingtrailingwhitespace
