### ISSUE TITLE
Parenthesis reversed in RTL

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#8991]
**Describe the bug**
Text rendering is weird in RTL mode, with parenthesis at the end of line. 

**To Reproduce**

1. Run ControlCatalog sample project
2. Switch to RTL in setting
3. Check `Menu` sample

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/14807942/191086237-e7ce5c58-6939-452f-a16a-55aa14e193af.png)

**Desktop (please complete the following information):**

- OS: [Windows]
- Version [11.0-preview1]

**Additional context**

**Comment by rabbitism** [comment]
Actually I'm not RTL user, I don't know how it should work in reality. It just looks weird to me.

**Comment by Gillibald** [comment]
Y this is a reorder bug
