### ISSUE TITLE
New live previewer architecture + Avalonia.Remote proposal

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#900]
Since we need to run user's code anyway (for custom controls, design-time mock data, etc), previewer will stay out of process. The main issue with the current one is that it's not portable and causes issues with build in visual studio.

Portability issues come from the fact that previewer uses  some kind of reflection and win32 api voodoo to do the following:
1) Load every assembly from build output directory
2) Initialize it with "proper" windowing subsystem
3) Initialize subsystem-specific hacks
4) Pass created window handle to parent process via stdout, so it could be reparented via Win32 API.

That obviously won't work properly with .NET Core and other platforms. It also all happens in a separate executable file, which has to be shipped with VS Extension.

----------------------

So, the new previewer implementation should live in Avalonia itself.
It would be initialized using appbuilder, something like:

```cs
AppBuilder.Configure<App>()
    .UseRemotePreviewer() // <-------
    .UsePlatformDetect()
    .Start<MainWindow>();
```

`UseRemotePreviewer` should analyze environment variables and/or command line arguments to see if it's being run by some kind of IDE. In this case it should attempt to connect to IDE host using provided method.
Command line will look somewhat like:
`--avalonia-start-previewer --avalonia-previewer-transport=tcp://127.0.0.1:15543`

Once connection is established, it will start sending log messages to the host.

It will next setup an offscreen windowing platform emulation and configure compatible rendering engine (for now Skia, since it already can render directly to a byte array), then *bypass further AppBuilder configuration options completely* and straight up call `SetupWithoutStarting`, followed by entering host's command handling mode.

Communication should be done using BSON messages. Host will send XAML updates, input events, scaling options changes and receive back framebuffer updates.

That makes previewer completely platform-agnostic, since you can just run compiled application with some command line options.

----------------------

Base support for remote widgets is worth of having a support that's completely separate from designer, since it potentially provides a lot of value by itself. For example, we could run our devtools directly on Android/iOS and then connect to them via TCP.

DTO (data transfer objects) and Stream-based  for remote widget communications shall live in a separate library `Avalonia.Remote.Protocol` available via NuGet (might be worth including previewer-specific messages in the same library). It will be considered to be a protocol spec, since it directly maps to JSON objects. Each DTO should have a GUID. It should be possible to pass custom messages or substitute transport completely, because it may be required for end-user's application. 

Widget hosting and offscreen platform implementations should live in the main repo/library, since they are coupled to platform interfaces.

We should also provide Avalonia and WPF controls for rendering remote widgets, so it would be easy to use from VS extension and AvalonStudio.

**Comment by kekekeks** [comment]
Roadmap:
- [] Allow to create bitmap directly from memory, since PNG encoding actually takes some time and it's way cheaper to just transfer a huge blob via IPC or local wifi (pull #903)
- [] Allow bitmaps to be disposed (issue #904, not exactly necessary with `WritableBitmap`)
- [] Design `Avalonia.Remote.Protocol` and create a basic implementation over TCP + BSON
- [] Create `OffscreenTopLevelImpl : ITopLevelImpl` that has it's own framebuffer (might also be very useful for embedded devices since they will want double-buffering anyway).
- [] Create wire up offscreeen toplevel with protocol implementation, implement `RemoteConrol` for Avalonia and WPF
- [] Do `UseRemotePreviewer` voodoo
- [] Implement support for remote devtools

**Comment by birbilis** [comment]
Why not make some protocol for sending input events and getting back delta-XAML?

Bitmaps may need to be rendered at client bitdepth etc on the server to be efficient, but don't see how sending uncompressed bitmaps is scalable if used with multiple clients or with fast updates (say video / animated images)

**Comment by kekekeks** [comment]
The whole point of the protocol is to embed widget into something that *can't* dipslay our XAML in it's own process.

**Comment by jkoritzinsky** [comment]
What's left to do in this issue since #1105 was merged in? Should we spin those items out into different, more specific issues now that the remoting infra and new previewer are merged in?

**Comment by kekekeks** [comment]
Input events aren't implemented yet
