### ISSUE TITLE
Scaling issue on Fedora 36 - Gnome 42

### ISSUE THREAD

**Issue by petedavis** [AvaloniaUI/Avalonia#9002]
Avalonia fails to scale apps correctly on Gnome 42 (GTK 4.x?)

**To Reproduce**
Running a new MVVM project from a template:
![image](https://user-images.githubusercontent.com/164331/191387229-cd2d3294-3ef7-4e33-92ac-422af38a9fbc.png)

- OS: Linux Fedora 36 - Gnome 42.0
- Version: 0.10.18
- Screen: Dell XPS 15 3840x2160
- Scale: 200%  

**Additional context**
Check that the same issue occurs on Wasabi Wallet app

![image](https://user-images.githubusercontent.com/164331/191386914-f292c2d2-64da-4674-a7a0-7827f0bad843.png)

**Comment by maxkatz6** [comment]
See
https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI
https://github.com/AvaloniaUI/Avalonia/issues/4826
