### ISSUE TITLE
Property binding somehow failed when view model is not in the same assembly

### ISSUE THREAD

**Issue by cdytoby** [AvaloniaUI/Avalonia#9021]
**Describe the bug**
When I put another view model and use it as DataContext in main view, the property text doesn't show up.
However it shows up in xaml preview.

**To Reproduce**

1. Open this project using Jetbrain Rider, in Windows 10
[Issue_Sample.zip](https://github.com/AvaloniaUI/Avalonia/files/9641811/Issue_Sample.zip)
2. Build and run
3. See error

**Expected behavior**
The text "Initial Set" should be visible in the window.

**Screenshots**
![image](https://user-images.githubusercontent.com/15671368/192165920-27511ec1-a473-4faa-b360-12c204c03bb3.png)

**Desktop (please complete the following information):**

- OS: Windows 10 21H1
- Version 0.10.18

**Additional context**
This is a testing project to see how avalonia works, so this project only contains minimum codes. Also I always put ViewModel seperately in another assembly, so that I can reuse it in different UI frameworks. 
First I tried to move the view model class to the desired assembly with "refactor" feature in Rider, but I got immediate error that InitializeComponent() method doesn't exist. I reverted the refactor, and then created an extra view model, and as soon as DataContext in the axaml file is changed, this error appears again. However this time, I closed and reopened Rider, the error is gone. But I can't get the same result, even the code are the same (almost). I hope you can help me identify the issue, whether it's a bug or not.

**Comment by rabbitism** [comment]
You are creating a control with ViewLocator, it's uses reflection by inferring control's name with viewmodel's name. 
```csharp
public IControl? Build(object? data)
{
    if (data is null)
        return null;

    string name = data.GetType().FullName!.Replace("ViewModel", "View");
    Type? type = Type.GetType(name);

    if (type != null)
    {
        return (Control)Activator.CreateInstance(type)!;
    }

    return new TextBlock { Text = name };
}
```

I don't think it's possible to infer View's name from ViewModel's fullname when they are in different assemblies. 

You should try other methods to assign ViewModels.

**Comment by cdytoby** [comment]
I solved it, and I think your project template is very misleading and should be reworked.

- I didn't write ViewLocator, it's from template, and I also didn't really understand why it does this.
- MainView is a UserControl, and DataContext is `Design.DataContext`, not `UserControl.DataContext`, I didn't really pay attention when I'm using the template.

**Comment by rabbitism** [comment]
> I solved it, and I think your project template is very misleading and should be reworked.
> 
> * I didn't write ViewLocator, it's from template, and I also didn't really understand why it does this.
> * MainView is a UserControl, and DataContext is `Design.DataContext`, not `UserControl.DataContext`, I didn't really pay attention when I'm using the template.

1. I totally agree that ViewLocator is very misleading in basic project template, using naming convention to create viewmodel is also unrealistic in production. I would suggest to use a more intuitive way to create viewmodel for views. 
2. `Deisgn.DataContext` really is only used for IDE previewer, it is not for running app.

**Comment by cdytoby** [comment]
About Design.DataContext, this is also in template, I didn't write this. It should use UserControl.DataContext by default.

**Comment by timunie** [comment]
You can change ViewLocator to anything you like as long as it implements IDataTemplate. Moreover you can define DataTemplates for each ViewModel you have. 

Here is a sample App https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src%2FAvalonia.Samples%2FDataTemplates%2FBasicDataTemplateSample
