### ISSUE TITLE
v11 Open/Save File API Suggestions

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#9029]
I'm looking to mirror Avalonia's new API for Open/Save File/Folders into MvvmDialogs, but there are a few design decisions I'd like to question.

IStorageItem is meant to be a consumption-only API, but there is one location where it needs to be set: `PickerOptions.SuggestedStartLocation`. How is that property supposed to be set?? I don't even know.

Why not simply have a direct nullable Uri property on `IStorageItem`? If you don't want to resolve it automatically for performance reason, it can be lazy-loaded, and the `bool` value is simply repeating whether the value is null or not. I see no benefit to this function and it makes it more complex to use.

```c#
/// <summary>
/// Gets the full file-system path of the item, if the item has a path.
/// </summary>
/// <remarks>
/// Android backend might return file path with "content:" scheme.
/// Browser and iOS backends might return relative uris.
/// </remarks>
bool TryGetUri([NotNullWhen(true)] out Uri? uri);
```

I'll replace this in my API with
```c#
Uri? Path { get; }
```

**Comment by maxkatz6** [comment]
Hi! I answered your question about suggested start location in the another thread - https://github.com/AvaloniaUI/Avalonia/discussions/9014

> Why not simply have a direct nullable Uri property on IStorageItem?

As you mentioned, there is no practical benefit for that. But it rather an API style choice. 
TryGet is a common API pattern in the .NET.

**Comment by mysteryx93** [comment]
Yes, but in terms of usage

    var path = await dialogService.ShowOpenFileDialogAsync(owner, options);

Could become (for desktop)

    var result = await dialogService.ShowOpenFileDialogAsync(owner, options);
    var path = result?.Path;

but with TryGet, the syntax would become a lot more complex for the most commonly-used property. Particularly if you just want to convert the list of IStorageFile into a list of string.

There is one use-case of the TryGet method, which is to ask permission on Android, but that's really a corner-case scenario that could have a dedicated method.

**Comment by maxkatz6** [comment]
> There is one use-case of the TryGet method, which is to ask permission on Android

Not really, as asking for permissions would be an async operation.

**Comment by mysteryx93** [comment]
So that scenario definitely would require a separate method -- thus no benefit for the TryGet for the most commonly-used property.

**Comment by mysteryx93** [comment]
As I'm looking at the API, I'd replace all the `IBookmarkStorageItem` related files with this simple interface

```c#
public interface IBookmarkFileSystem
{
    Task<IDialogStorageFile?> OpenFileBookmarkAsync(string bookmark);

    Task<IDialogStorageFolder?> OpenFolderBookmarkAsync(string bookmark);
    
    Task ReleaseBookmarkAsync(string bookmark);
}
```

You can simplify the API a lot just by adding that single method. Is there any benefit to having the way it's currently structured?

In my case, I'll create a separate interface because `IDialogService` focuses on dialogs, but in your case, it's perfectly fine to have it on `IStorageProvider` with the rest.

In the back-end, do you need to know whether the bookmark is a file or folder to delete it? That's the only issue with my code; I cannot call your ReleaseBookmarkAsync method without first calling OpenFileBookmarkAsync or OpenFolderBookmarkAsync. Thus I'd need 2 Release methods instead of 1...

The only benefit I see to having those extra interfaces is that it allows releasing an already-open bookmark without having to call OpenBookmark again. Pretty weak benefit IMO, for highly-complicated code design.

**Comment by maxkatz6** [comment]
> related files with this simple interface

How this interface would be visible in the API? "topLevel.BookmarkFileSystem"? Or should IStorageProvider implement it?

> cannot call your ReleaseBookmarkAsync method without first calling OpenFileBookmarkAsync or OpenFolderBookmarkAsync.

I see, this simplification makes sense. But in opposite situation, when you have a file/folder object, how would you get the "bookmarkId" from it? Should we keep IStorageBookmarkFile/Folder for that? Or is developer supposed to keep bookmark id for that just for case?

> You can simplify the API a lot just by adding that single Release method. Is there any benefit to having the way it's currently structured?

Currently Release method is available on the file/folder itself. You also don't need to take an instance of "IStorageProvider" everywhere, if you already have a typed file/folder object.

**Comment by mysteryx93** [comment]
You implement on `IStorageProvider`. With `MvvmDialogs`, the programmer uses `IBookmarkFileSystem` since he doesn't refer to the UI directly.

Currently IStorageBookmarkFile doesn't have that BookmarkId property.

I think the easiest for the user would be to have these 3 nullable properties on the StorageFile:
- Url: the cross-platform Url starting with "file://"
- Path: the classic desktop file paths.
- BookmarkId: the bookmark associated with the file

Path is important because it is a serious breaking change when porting existing applications to v11. We just don't know what side-effects changing the path format will have on the rest of the application, and many developers will hold back for safety. It's better to first port by simply adding ".Path" to the result of all file pickers, and then later the developer can adapt to the new Url  format if it's worth the efforts (such as to add mobile support).

As for BookmarkId, when is it available? I suppose, when SaveBookmark has been called, or OpenBookmark has been used? Yes that would make sense. I think that those 3 nullable properties would work wonders.

**Comment by kekekeks** [comment]
Note that even desktop platforms don't allow full file access in some cases. A notable example is macOS app running in sandbox mode. So you can't rely on the full file system access being available.

**Comment by mysteryx93** [comment]
It would be useful to have a property telling whether the full file system is available, or it's running in sandbox (or is there other possibilities?)

Note that on a rooted Android phone you might have access to the full file system.
