### ISSUE TITLE
TextBlock throws "Font family not supported" on Android with string containing "weird" character

### ISSUE THREAD

**Issue by msneijders** [AvaloniaUI/Avalonia#9031]
**Describe the bug**
Rendering text on **Android** using string containing a "weird" character like in this one:

"TEST (AU)" (in unicode: "TEST%9D%20%28AU%29")

(it came out of a test database)

avaloniaui throws a "Font family is not supported" exception.

On Windows it renders like a □ (square) without exception.

**Expected behavior**
I expect it would accept any unicode character without exception, (how it renders it does not really matter).

**Desktop (please complete the following information):**

- Version 11 preview

**Comment by Gillibald** [comment]
Should be fixed by #8963
