### ISSUE TITLE
Bitmap disposal

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#904]
Since bitmaps typically consume tons of memory, it's worth to have an option to explicitly dispose them. However, if bitmap is already used somewhere, application will just crash, and that's not what we want.

So the proposal is to have a static instance of transparent 1x1 bitmap, which will be used as a substitute for `BitmapImpl` in `Bitmap` class. It should be provided by rendering subsystem and never get disposed. That way we won't need complex checks in our rendering code to determine if we can use bitmap or not.

**Comment by grokys** [comment]
Yeah, that sounds like a nice workaround to the problem to me.

**Comment by grokys** [comment]
Although, `scenegraph` holds instances of `IBitmapImpl` (as it needs immutable data). I guess we would need to add an `IsDisposed` property there.
