### ISSUE TITLE
[Avalonia] [Win32] When Window.WindowState=Maximized is set initially on window the Window.OffScreenMargin property is not updated corectly

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#9042]
**Describe the bug**
When `Window.WindowState="Maximized"` is set initially on Window the `Window.OffScreenMargin` property is not updated.

**To Reproduce**

Run SandBox sample:

```XAML
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'
        MinWidth="720" MinHeight="480"
        WindowStartupLocation="CenterScreen"
        ExtendClientAreaTitleBarHeightHint="50"
        ExtendClientAreaToDecorationsHint="True"
        ExtendClientAreaChromeHints="Default, PreferSystemChrome, OSXThickTitleBar"
        Background="Blue"
        Name="MainWindow"
        WindowState="Maximized"
        x:Class="Sandbox.MainWindow">
  <Border Margin="{Binding #MainWindow.OffScreenMargin}" BorderBrush="Red" BorderThickness="1" Background="Green">
    <Button Content="Maximize" VerticalAlignment="Top" Name="MaximizeButton" Click="MaximizeButton_OnClick" />
  </Border>
</Window>
```

```C#
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Presenters;
using Avalonia.Interactivity;
using Avalonia.Markup.Xaml;
using Avalonia.Win32.WinRT.Composition;

namespace Sandbox
{
    public class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
            this.AttachDevTools();
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }

        private void MaximizeButton_OnClick(object sender, RoutedEventArgs e)
        {
            WindowState = WindowState.Maximized;
        }
    }
}
```

**Expected behavior**

When `Window.WindowState="Maximized"` is set initially on Window the `Window.OffScreenMargin` property is updated.

**Screenshots**

The button and caption buttons in title bar are cut of from top:
![image](https://user-images.githubusercontent.com/2297442/192734146-7a17d2f0-2ea8-4365-896b-f447dba12bb3.png)

After restoring and maximizing again the window content is properly drawn

![image](https://user-images.githubusercontent.com/2297442/192734661-a97bfd14-2469-49ab-b8ae-6e03d526a389.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.18, master

**Additional context**

1. ExtendClientArea is called before WindowState.Maximized is set so it actually calculates OffScreenMargin for WindowState.Normal
2. After that WindowState property is set to proper value WindowState.Maximized and _lastWindowState is WindowState.Maximized
3. The WM_SIZE message is processed but _lastWindowState is already changed from WindowState setter so UpdateExtendMargins is not called again

https://github.com/AvaloniaUI/Avalonia/blob/84791dbf2e772cad889d575ef64000b5ba3d637a/src/Windows/Avalonia.Win32/WindowImpl.cs#L293

https://github.com/AvaloniaUI/Avalonia/blob/84791dbf2e772cad889d575ef64000b5ba3d637a/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs#L574

**Comment by Qzername** [comment]
Is there any way to handle with this bug at this moment?

**Comment by apophilipse** [comment]
Has this been fixed? I still have a very similar Bug.

**Comment by timunie** [comment]
@apophilipse should be fixed in latest version of Avalonia 11.x
