### ISSUE TITLE
Opacity and Pointer events don't work as expected in Avalonia 11-Preview

### ISSUE THREAD

**Issue by radiolondra** [AvaloniaUI/Avalonia#9043]
**Describe the bug**
Assigning **PointerEntered** event, which assigns **Opacity=0.8**, and **PointerExited** event, which instead assigns **Opacity=0.0**, to a control (e.g. a panel), once the opacity is set to 0.0 in PointerExited, the control doesn't answer to PointerEntered anymore.

**To Reproduce**
I created a [repo on Github](https://github.com/radiolondra/AvaloniaOpacityTests) to demonstrate the bug. It contains 2 solutions: one (cross) using Avalonia 11-preview, where the bug happens (Desktop project). The other one using Avalonia 0.10.18 where everything works as expected.

**Expected behavior**
11-preview should work fine as 0.10.18

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11-preview1

**Comment by maxkatz6** [comment]
Can you try with latest nightly build? I feel it might have been already fixed.
https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

**Comment by radiolondra** [comment]
It is already using the nightly build (11.0.0-preview1)

**Comment by maxkatz6** [comment]
Preview1 is not a nightly build. It is a public preview. 
Latest nightly is 11.0.999-cibuild0024198-beta or [newer](https://github.com/AvaloniaUI/Avalonia/pull/9037#issuecomment-1260516733) .

**Comment by radiolondra** [comment]
I upgraded Avalonia to 11.0.999-cibuild0024213-beta. Same issue.

**Comment by maxkatz6** [comment]
Seems to be a bug in new compositor renderer. Workaround is to disable it:
```csharp
        public static AppBuilder BuildAvaloniaApp() =>
            AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .With(new Win32PlatformOptions() // or AndroidPlatformOptions ...
                {
                    UseCompositor = false
                })
                .LogToTrace();
```
