### ISSUE TITLE
Default TextBlock Foreground Dark themes does not display correctly in ISingleViewApplicationLifetime environment

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#9053]
**Describe the bug**
 Dark themes does not display correctly in framebuffer environment. The foreground color of the font is black instead of white

**To Reproduce**

1. Run ControlCatalog.NetCore in framebuffer environment `--fbdev`
2. Swithc any Dark theme
3. See error

**Expected behavior**
The foreground color of the font is white like X* Environment

**Screenshots**
### Framebuffer Environment

![immagine](https://user-images.githubusercontent.com/12531229/193076148-a1951c04-2f25-4aa5-8307-a41578944388.png)

### X Environment
![immagine](https://user-images.githubusercontent.com/12531229/193075449-77a5aeb0-80fb-449e-ab3d-2374fffe8740.png)

**Desktop (please complete the following information):**

- OS: **Linux Ubuntu 22.04.1**
- Version 84791dbf2e772cad889d575ef64000b5ba3d637a

**Additional context**

**Comment by workgroupengineering** [comment]
@maxkatz6 do you have any idea what this might depend on?

**Comment by robloo** [comment]
I have also noticed dark Foreground colors instead of light within TextBox after theme changes. Never filed an issue for it but this is likely the same root cause.

**Comment by maxkatz6** [comment]
I am not sure if theme changing is supposed to work very well now.
Does it work properly if theme mode was set initially?

**Comment by maxkatz6** [comment]
Also keep in mind that switching from Simple to Fluent theme or vise-versa isn't supported and not guaranteed.

**Comment by robloo** [comment]
> Also keep in mind that switching from Simple to Fluent theme or vise-versa isn't supported and not guaranteed.

That doesn't make sense to me. One of the main features of ControlTheme is it encapsulates everything needed for a default control style and makes it easy to switch them. Besides, it worked before 11.0 and is supported in ControlCatalog...

**Comment by maxkatz6** [comment]
> That doesn't make sense to me

Similarly, as it is in WPF/UWP, ControlTheme is referenced statically. So, controls wouldn't react on changes when ControlTheme resource was replaced.
Though @grokys was planning to implement this feature, but I suppose it's lower priority one.

How many cases are there in real life application where it can be used?
Also, I believe it's still possible for the application to reference ControlTheme with DynamicResource instead, so this specific control will react on theme changes. But that's not tested.

**Comment by robloo** [comment]
> How many cases are there in real life application where it can be used?

Don't misunderstand, this isn't a priority for me. Use cases are obviously limited mostly to theoretical or developer areas. I was simply surprised this wasn't supported. It would help a lot in testing.

We should remove this from control catalog or make the setting persist across restarts. Otherwise it's not useful right now.

**Comment by robloo** [comment]
Also we are mixing terminology again... light to dark or vice versa changes should work. That was the original issue and also what doesn't always work in TextBox.

**Comment by maxkatz6** [comment]
Yes, I just was clarifying that it was light<->dark change and not fluent-light<->default-dark

**Comment by workgroupengineering** [comment]
> 

Even if I set Fluent Dark as the initial theme, it is not displayed correctly.



> Also keep in mind that switching from Simple to Fluent theme or vise-versa isn't supported and not guaranteed.

That's not the case. I need to switch between light and dark and vice versa.

The use case is to switch the color of the theme based on the ambient light coming from a sensor, to always guarantee excellent visibility.

Same binary, executed without the `--fbdev` flag, displays correctly.

**Comment by workgroupengineering** [comment]
After adding the following lines in "App.xaml" it works as expected

```xaml
  <ControlTheme x:Key="{x:Type TextBlock}" TargetType="TextBlock">
    <Setter Property="Foreground" Value="{DynamicResource TextControlForeground}" />
    <Setter Property="Background" Value="Transparent" />
  </ControlTheme>
```
Now we need to understand why in other platforms it works without the previous xaml.

@maxkatz6 Do you have any ideas?

**Comment by maxkatz6** [comment]
> Is there a way to set UserControl Foreground to TextControlForeground if you don't have a parent in a Style?

Not sure if it should...

> while app runs ISingleViewApplicationLifetime (FrameBuffer, ecc..) inherits Foreground from Usercontrol

It should be inherited from the [EmbeddableControlRoot](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/EmbeddableControlRoot.xaml). Which is missing Foreground property for some reason I guess.
