### ISSUE TITLE
Preview 11 Xaml hexadecimal colors not working

### ISSUE THREAD

**Issue by beto-rodriguez** [AvaloniaUI/Avalonia#9063]
**Describe the bug**
In previous versions we could set hex colors in Xaml, the following snippet used to work, not it does not.

![image](https://user-images.githubusercontent.com/10853349/193378339-f6a1979c-3cbf-4ff9-bb96-872099ca0941.png)

**To Reproduce**
Not sure if it happens on every hex color in Xaml, but it happens in the LiveCharts2 repo.

1. Clone LiveCharts2 at the avalonia preview branch
2. See [this file](https://github.com/beto-rodriguez/LiveCharts2/blob/avalonia-preview/samples/AvaloniaSample/Axes/Multiple/View.axaml) and use the commented XAML instead of the current one.
3. see the exception.

**Expected behavior**
The Xaml to compile

- OS: Windows 11

**Additional context**
The same XAML used to work In version `0.10.18`

**Comment by jp2masa** [comment]
Seems like a mismatch in assembly versions. Check if all projects are using the same version of Avalonia and maybe you need to reopen the solution (or restart VS) to make sure the build tools with the correct version are loaded.

**Comment by Gillibald** [comment]
The issue here is that your brush properties are typed SolidColorBrush instead of IBrush. This prevents using multiple brush implementations. Avalonia 11 creates immutable brushes at compile time for performance reasons and therefore your code doesn't work anymore.

**Comment by beto-rodriguez** [comment]
thanks @Gillibald .

**Comment by beto-rodriguez** [comment]
It works thanks!  but this was a breaking change in case you want to add it to the migration docs.
