### ISSUE TITLE
Control Catalog Screen Page Crash on Windows 

### ISSUE THREAD

**Issue by ShadowMarker789** [AvaloniaUI/Avalonia#9064]
**Describe the bug**
The Control Catalog Screen Page crashes with an unhandled exception on Windows when it calls InvalidateVisual in the middle of an OnRender call. 

**To Reproduce**

1. Check out Master Branch of AvaloniaUI on a Windows machine. (Use Win32 Options UseWindowsCompositor etc) (all defaults)
2. Build and run the ControlCatalog.NetCore
3. Navigate to the Screens Page
4. Unhandled Exception causes Crash 

![CompositingRenderer.cs::82](https://user-images.githubusercontent.com/37165910/193384477-44f46cb0-419c-4a8e-b4fd-311708422602.png)

**Expected behavior**
Expected behaviour is the Screen Page loading and displaying as required. 

**Screenshots**
Additional screenshot 

![ScreenPage.cs::43](https://user-images.githubusercontent.com/37165910/193384522-02bd0561-4ed3-4a4f-939c-31c2c45a2764.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Home
- Version Build 19044

**Additional context**

This can be alleviated by modifying the offending line to do a dispatcher post operation, rather than immediately invalidating the visual in the middle of a render-pass. 

![Dispatcher Post Operation](https://user-images.githubusercontent.com/37165910/193384946-1663d915-f074-4276-bf2b-8e161ee2a750.png)

![Working Screen Page](https://user-images.githubusercontent.com/37165910/193385319-bcb9ff85-8314-4a3d-b44d-65ce2bd454b0.png)

If there's no objections to the change from

```cs
InvalidateVisual();
```

to

```cs
Dispatcher.UIThread.Post(InvalidateVisual, DispatcherPriority.Background);
```

Then I can issue a PR to change this.

**Comment by maxkatz6** [comment]
Yes, it should be replaced with w dispatcher call.
