### ISSUE TITLE
The project doesn't know how run the project with name 'XXXX' and command  'Project'

### ISSUE THREAD

**Issue by UnivexDont** [AvaloniaUI/Avalonia#9075]
**Describe the bug**

**To Reproduce**

1.build successed
2.messagebox when run

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows11 arm M1
- VS2020 preview
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/29479617/193467379-50136e5d-15fa-40ec-a922-441733329712.png">

**Additional context**

**Comment by maxkatz6** [comment]
It doesn't seem to be an issue with Avalonia. Check if you have up to date SDK installed and Visual Studio isn't corrupted.
Also, this might help https://developercommunity.visualstudio.com/t/The-project-doesnt-know-how-to-run-the-/1596305 and https://github.com/MicrosoftDocs/visualstudio-docs/issues/7898
