### ISSUE TITLE
Flicker during window resize on Windows with DirectComposition WS_EX_NOREDIRECTIONBITMAP

### ISSUE THREAD

**Issue by jcoc611-microsoft** [AvaloniaUI/Avalonia#9103]
**Describe the bug**
Rendering on Windows with DirectComposition (`WS_EX_NOREDIRECTIONBITMAP`) causes the client area to flicker on resize, sometimes displaying the content behind the window briefly.

Setup:

```C#
// simplified render loop...
var target = (IRenderTargetWithCorruptionInfo) CreateRenderTarget();

using (var context = (ISkiaDrawingContextImpl) target.CreateDrawingContext(null))
{
    // logic that might take longer than a frame...
}
```

Possibly it can be fixed by presenting the client area with the new size in the handler for `WM_NCCALCSIZE` (DrawingContextImpl)?

**To Reproduce**

1. Run an Avalonia app on Windows with Skia
2. Set up a render loop with `using(var drawingContext = CreateDrawingContext(...))` which takes longer than a frame.
3. Observe some frames flicker rendering the content behind the window.

**Expected behavior**
No flicker, or at least flicker with a solid background instead.

**Screenshots**
Bad case (expected window to never be transparent):
![image](https://user-images.githubusercontent.com/46764777/193915193-30753a2e-d313-471b-b65a-7c539fb40031.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Avalonia Version 0.10.18

**Comment by jcoc611-microsoft** [comment]
We don't interface with DirectComposition directly. We only draw to `SKCanvas` directly but otherwise let Avalonia `ISkiaDrawingContextImpl` handle rendering

**Comment by kekekeks** [comment]
Are you using our `ICustomDrawOperation` API?

**Comment by jcoc611-microsoft** [comment]
No actually we have a class derived from `Avalonia.Controls.Window` in which we directly call the following `Render` method on a private render loop on the UI thread

```C#
class CustomWindow : Avalonia.Controls.Window
{
    private IRenderTargetWithCorruptionInfo? target;

    public void Render(...)
    {
        if (target == null || target.IsCorrupted)
        {
            target?.Dispose();
            target = (IRenderTargetWithCorruptionInfo) CreateRenderTarget();
        }
    
        using (ISkiaDrawingContextImpl context = (ISkiaDrawingContextImpl) target.CreateDrawingContext(null))
        {
            SKCanvas canvas = context.SkCanvas;
    
            canvas.Scale(...);
            // ... actual render with canvas
        }
    }
}
```

**Comment by kekekeks** [comment]
I don't think that's a supported usage scenario. 
Please, try using ICustomDrawOperation (see [example usage](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/RenderDemo/Pages/CustomSkiaPage.cs) here) and check if the issue persists.

**Comment by jcoc611-microsoft** [comment]
The problem doesn't go away using `ICustomDrawOperation` unfortunately (in fact it is more noticeable on my end).

I tried with Avalonia 10 (without `ISkiaSharpApiLeaseFeature`) and in Avalonia 11 (with). Neither improved flicker.

Here is a trivial reproducible example based on the sample:

```C#
using var lease = leaseFeature.Lease();
SKCanvas canvas = lease.SkCanvas;
Thread.Sleep(100);
canvas.DrawRect(canvas.LocalClipBounds, new SKPaint(){ Color = SKColors.White });
```

**Comment by kekekeks** [comment]
I suppose it might be caused by us resizing the surface and visual before rendering rather than creating a new surface and updating the visual after rendering is complete

**Comment by trusktr** [comment]
If you are using Skia, its probably the same issue caused in web apps [described here](https://github.com/w3c/csswg-drafts/issues/9717): resize of canvas after already drawing pixels clears the canvas.
