### ISSUE TITLE
The File Picker Dialogs do not play well when there are diacritics on the paths to files.

### ISSUE THREAD

**Issue by Templayer** [AvaloniaUI/Avalonia#9118]
**Describe the bug**
When using StorageProvider.OpenFilePickerAsync and the saving one, the user selects a path, but the path stored in IStorageFiles is incorrect if it contains diacritics - it needs to be sanitized by using HttpUtility.UrlDecode(pathToFile).

```
An error has occured while trying to save the output: System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/jboksa1/(D)%20Datov%C3%BD%20disk/Bordel/output.txt'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileInfo.OpenWrite()
   at Avalonia.Platform.Storage.FileIO.BclStorageFile.OpenWriteAsync() in /_/src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFile.cs:line 61
   at MSOfficeFileValidator.ViewModels.MainViewModel.<SavePathButtonClicked>b__54_0(Task`1 dialog) in /media/jboksa1/(D) Datový disk/Rider-repo/MSOfficeFileValidator/MSOfficeFileValidator/ViewModels/MainViewModel.cs:line 324
```

**To Reproduce**
Steps to reproduce the behaviour: 

try saving a file selected by using SaveFilePickerAsync when the path leading to it contains diacritics on Linux. (my case was the Czech UTF-8 locale)

**Workaround for opening files (sadly not for saving them...)**
When opening files via OpenFilePickerAsync, I can get the URI manually, UrlDecode it and then load the file manually. This works on Linux and Windows (and I haven't checked the others). 

**Expected behaviour**
Diacritics from the path should be parsed correctly for file pickers.

**Screenshots**
![image](https://user-images.githubusercontent.com/11728067/194570559-c6c1ea35-8428-41f1-9231-78853f43f128.png)
In the upper part of the output textbox, we can see how the file path was properly parsed when using my workaround for the open file picker dialog. In the lower part of the very same printscreen is the result of saving the output textbox - the IStorageFile that I got from the Save File Picker screwed with the diacritics (and I don't have a workaround for that):

**Desktop (please complete the following information):**

- OS: Linux Mint 20.3
- Version: 11.0.0-preview1

**Comment by Templayer** [comment]
EDIT: My workaround doesn't work for the WASM (web app) version, and I'm going to assume it won't work under Android/iOS either.

**Comment by Templayer** [comment]
Here's the repo for my app: https://gitlab.com/templayer/ms-office-file-validator

**Comment by emmauss** [comment]
This seems to be the default behavior with Uri. AbsolutePath is Uri encoded, and you can see that from here
![image](https://user-images.githubusercontent.com/5307160/196140040-3d9964e2-0276-49d1-9eef-ae79592e9b81.png)

Use LocalPath or OriginalString instead.

**Comment by Templayer** [comment]
> This seems to be the default behavior with Uri. AbsolutePath is Uri encoded, and you can see that from here *image*
> 
> Use LocalPath or OriginalString instead.

That's not the problem. If I actually use IStorageFile that the picker picked, it fails horribly, because it doesn't find the file (even WITHOUT me doing anything with the path!). 

Let's see this example for a save button, which fails due to Avalonia INTERNALLY not being able to deal with diacritics:

```
public void SaveButtonClicked()
    {
        try
        {
            FilePickerSaveOptions options = new()
            {
                Title = "Save output as...",
                SuggestedFileName = "output.txt",
                DefaultExtension = ".txt",
                FileTypeChoices = new List<FilePickerFileType>{ new("A simple text file (.txt) with UTF-8")
                    {
                        Patterns = new[]{"*.txt"},
                        MimeTypes = new[]{"text/*"},
                        AppleUniformTypeIdentifiers = new[]{"utf8PlainText"}
                    },
                    new("A simple text file (without extension) with UTF-8")
                    {
                        Patterns = new[] { "*" },
                        MimeTypes = new[] { "text/*" },
                        AppleUniformTypeIdentifiers = new[] { "utf8PlainText" }
                    }
                },
                ShowOverwritePrompt = true
            };
            
            Task<IStorageFile?> dialog = StorageProvider!.SaveFilePickerAsync(options);
            // ReSharper disable once VariableHidesOuterVariable Intentional
            dialog.ContinueWith(delegate(Task<IStorageFile?> dialog)
            {
                try
                {
                    IStorageFile? file = dialog.Result;

                    //https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/DialogsPage.xaml.cs
                    if (file is not null && file.CanOpenWrite)
                    {
                        file.OpenWriteAsync().ContinueWith(delegate(Task<Stream> task)
                    {
                        try
                        {
                            using StreamWriter reader = new(task.Result);
                            reader.WriteLineAsync(OutputTextBoxContent);
                        }
                        catch (Exception e)
                        {
                            Log("An error has occured while trying to save the output: " + e);
                        }
                    });
                    }
                }
                catch (Exception e) { Log("An error has occured while trying to save the output: " + e); }
            });
        }
        catch (Exception e) { Log("An error has occured for the output save dialog: " + e); }
    }
```

file.OpenWriteAsync() will fail WITHOUT me doing ANYTHING with a path.

**Comment by Templayer** [comment]
While Saving is completely broken (see my previous path-less code example), my Open dialog used AbsolutePath. Changing it to OriginalString as you suggested won't help me (LocalPath will, however):

![image](https://user-images.githubusercontent.com/11728067/196160051-0655ec64-0b40-4ce3-816f-50072ee50264.png)

 (Now that I'm looking at it, the problem might be Nemo-specific, as my debugging has different stuff for diacritics than yours - this might also be the source for the save picker problem!)

It almost looks like Nemo feeds the picker with encoded strings. D-8

**Comment by Templayer** [comment]
Here's the repo for my tiny app: https://gitlab.com/templayer/ms-office-file-validator
(I have quite a few changes that I haven't committed, as I'm trying to at least get the WASM version working)

**Comment by maxkatz6** [comment]
@Templayer this bug was fixed with preview2. See https://github.com/AvaloniaUI/Avalonia/commit/e64a5e3b0f9d8ebfdc1158b8d3486323e47c3d81.

We didn't notice it before, as this bug was already fixed in the master at the moment, when you opened this PR. But now it's also available on the nuget.

**Comment by Templayer** [comment]
> @Templayer this bug was fixed with preview2. See [e64a5e3](https://github.com/AvaloniaUI/Avalonia/commit/e64a5e3b0f9d8ebfdc1158b8d3486323e47c3d81).
> 
> We didn't notice it before, as this bug was already fixed in the master at the moment, when you opened this PR. But now it's also available on the nuget.

Excellent.
