### ISSUE TITLE
Avalonia NuGet repository returning a 502 Bad Gateway

### ISSUE THREAD

**Issue by thimok** [AvaloniaUI/Avalonia#9124]
**Describe the bug**
I opened an open source Avalonia project which I cloned from GitHub (Core2D). After Rider is trying to retore the packages, it's stuck restoring them from the Avalonia NuGet package source:
[NU1301] Unable to load the service index for source https://nuget.avaloniaui.net/repository/avalonia-all/index.json.

**To Reproduce**

1. Go to the Core2D repository and clone the repository
2. Open the solution in Rider
3. Restore packages

**Expected behavior**
Packages get retstored

**Screenshots**
![image](https://user-images.githubusercontent.com/20819818/194699389-6a8a0d23-4ed9-4150-ae70-70124b0aa208.png)

![image](https://user-images.githubusercontent.com/20819818/194699398-8cf865e6-0913-4954-bc0c-c4dabd64a310.png)

**Desktop (please complete the following information):**

- OS: Windows 11 Pro
- Version 22H2
- JetBrains Rider 2022.2.3
- AvaloniaRider plugin 1.6.0

**Comment by Gillibald** [comment]
Our Nuget feed is currently not available. We are working on a fix.
