### ISSUE TITLE
Invalid resource type: expected type is "StyledProperty<FontWeight>", actual type is "FontWeight"

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#9139]
**Describe the bug**
Trying to assign the FontWeight as a static resource to TextBlock.FontWeight property, the error shows.

**To Reproduce**

1. Add a resource to Styles.Resources

```xml

<Styles.Resources>
        <FontWeight x:Key="ComboBoxHeaderThemeFontWeight">Normal</FontWeight>
        <FontWeight x:Key="ComboBoxPlaceholderTextThemeFontWeight">SemiLight</FontWeight>
</Styles.Resources>

```

2. Assign it to the property using StaticResource

```xml

<ContentPresenter TextBlock.FontWeight="{DynamicResource ComboBoxHeaderThemeFontWeight}" />

```

3. See error

**Expected behavior**

The value should be assign to the property.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version Avalonia 11.0.0-preview2

**Comment by rabbitism** [comment]
TextBlock.FontWeight is no longer an attached property. You should use TextElement.FontWeight

**Comment by laolarou726** [comment]
Got it! Thank you so much!
