### ISSUE TITLE
`InlineUIContainer` is not rendered, then is rendered in the wrong location

### ISSUE THREAD

**Issue by tomenscape** [AvaloniaUI/Avalonia#9143]
**Describe the bug**

This is a regression in Avalonia 11 preview 2, caused I believe by #8849.

When the text block is first displayed, the inlined element is missing. Redrawing the text block causes it to appear, but at the wrong location.

![image](https://user-images.githubusercontent.com/109803929/194823286-2f41cee5-6cd6-4b64-b617-528694ab34cb.png)

**To Reproduce**

1. Create a `RichTextBlock` with an `InlineUIContainer` in the middle
2. Display it; the inlined control is not shown
3. Trigger a redraw
4. The inlined control is rendered at an incorrect location.

Because this is a test project, we are actually creating our controls in code-behind. Here is the code:

```C#
var rtb = new RichTextBlock { TextWrapping = TextWrapping.Wrap };
rtb.Inlines!.Add("Here is ");
rtb.Inlines.Add(new InlineUIContainer(new HyperlinkButton { Content = "a hyperlink" }));
rtb.Inlines.Add(" to click on");
```

**Expected behavior**
Avalonia 11 preview 1 immediately renders this:

![image](https://user-images.githubusercontent.com/109803929/194823773-bea55d0f-e7f7-48b4-a442-9b01b16a1371.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11 preview 2

**Comment by Gillibald** [comment]
Thanks for the report. Will have a look.
