### ISSUE TITLE
Avalonia 11 Preview Not Usable (for me): InitializeComponent not exist in MainWindow.axaml.cs

### ISSUE THREAD

**Issue by Blazero** [AvaloniaUI/Avalonia#9146]
I created a new project with `Avalonia Application` template in Visual Studio.
Build and Run, no problem.
Then I update the `Avalonia` related packages to 11.0.0-preview2 by NuGet.
Try to build the project, it failed.
Not a single line code changed.

Error 1: CS0103 InitializeComponent not exist (in MainWindow.axaml.cs)
![图片](https://user-images.githubusercontent.com/14362209/194886381-d4496215-6f9e-4473-a68c-ab76b48a8844.png)

Error 2: AXN0002	XamlX.XamlParseException: Unable to resolve type FluentTheme from namespace https://github.com/avaloniaui

**Comment by timunie** [comment]
FluentTheme has now it's own nuget package. Add it to your project and try it again

**Comment by rabbitism** [comment]
for the first issue, if that method is not auto generated, you can add manually. 

```csharp
private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
```

**Comment by Blazero** [comment]
> Add a fluent theme package. See https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes

It works now. The project template should be updated. (Maybe there was one but I haven't found it?)

**Comment by dprevato** [comment]
I just started a new project, using Avalonia 11.0.4 (not a preview), but I still have the error CS0103: The name InitializeComponent does not exist in the current context, in MainWindow.axaml.cs, (that is a partial class), without any code added from my part. All the required DLLs are present, I'm using Community.Toolkit.Mvvm v8.2.1. No idea about how to resolve the problem. Someone can help me?

**Comment by timunie** [comment]
@dprevato please open a new Q&A for it. Inside, please add a minimal sample for us to check. i have the feeling there is somehting wrong with your Avalonia-codegenerator. Thx.

Note answering closed issues is likely to be overseen, so better to ask usign Discussion (Q&A) or on Telegram (https://t.me/Avalonia)

**Comment by toplinuxsir** [comment]
I meet the same problem , I think it's a serious bug , Should  to fixe

**Comment by timunie** [comment]
@toplinuxsir don't answer closed issues. Please open a Q&A filing a minimal sample.

**Comment by YSW33** [comment]
1. 11.0.10 This issue occurred。
2. Can be rolled back to 11.0.7。
