### ISSUE TITLE
Regression: AttachedProperty Setter not called when attached to ControlTemplate

### ISSUE THREAD

**Issue by martinzding** [AvaloniaUI/Avalonia#9170]
**Describe the bug**
After I upgraded to `11.0.0-preview2`, The getter/setters of a user-defined attached property in a control template were not called anymore, breaking some Behaviors. Worked fine in `0.10.18`

**To Reproduce**

1. In a new Avalonia project, create a class with an attached property:
```
public class TestClass
{
    public static readonly AttachedProperty<bool> TestAttachedProperty =
        AvaloniaProperty.RegisterAttached<TestClass, Control, bool>("TestAttached");

    public static bool GetTestAttached(Control obj)
    {
        Debug.WriteLine("Get Attached");
        return obj.GetValue<bool>(TestAttachedProperty);
    }

    public static void SetTestAttached(Control obj, bool value)
    {
        Debug.WriteLine("Set Attached");
        obj.SetValue(TestAttachedProperty, value);
    }
}
```
2. Add a control in `MainWindow` with a template referencing that attached property:
```
    <UserControl>
        <UserControl.Template>
            <ControlTemplate>
                <TextBlock Text="123" Width="30" Height="30" 
                           models:TestClass.TestAttached="True"/>
            </ControlTemplate>
        </UserControl.Template>
    </UserControl>
```

**Expected behavior**
The setter should be called and `"Set attached"` should be printed in the debug output.

**Screenshots**
none

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.0-preview2

**Additional context**

**Comment by maxkatz6** [comment]
I don't think setters are guaranteed to be called. Same with non-attached properties.
Instead users need to handle TestAttachedProperty.Changed observable events.
CC @grokys

**Comment by martinzding** [comment]
Thank you @maxkatz6. Subscribing to the `Changed` event works.

Also found this from the official doc, the setters are not supposed to be called by the system.

> The getter and setter methods should always just set the value and never do anything beyond. In fact they will usually never be called as the Binding system will recognize the convention and set the properties directly where they are stored.
