### ISSUE TITLE
`drmModeGetResources failed` on `11.0.0 Preview 2`

### ISSUE THREAD

**Issue by Coloryr** [AvaloniaUI/Avalonia#9178]
**Describe the bug**
`drmModeGetResources failed` when start, it error in `11.0.0 Preview 2`, but work in `0.10.18`

**To Reproduce**
```
public static void Main(string[] args) => BuildAvaloniaApp()
            .StartLinuxDrm(args, scaling: 1);
```

**Expected behavior**
```
root@orangepizero2:~/Avalonia# dotnet Demo.dll
Unhandled exception. System.ComponentModel.Win32Exception (95): drmModeGetResources failed
   at Avalonia.LinuxFramebuffer.Output.DrmResources..ctor(Int32 fd, Boolean connectorsForceProbe) in /_/src/Linux/Avalonia.LinuxFramebuffer/Output/DrmBindings.cs:line 91
   at Avalonia.LinuxFramebuffer.Output.DrmCard.GetResources(Boolean connectorsForceProbe) in /_/src/Linux/Avalonia.LinuxFramebuffer/Output/DrmBindings.cs:line 171
   at Avalonia.LinuxFramebuffer.Output.DrmOutput..ctor(String path, Boolean connectorsForceProbe, DrmOutputOptions options) in /_/src/Linux/Avalonia.LinuxFramebuffer/Output/DrmOutput.cs:line 47
   at LinuxFramebufferPlatformExtensions.StartLinuxDrm[T](T builder, String[] args, String card, Double scaling, IInputBackend inputBackend) in /_/src/Linux/Avalonia.LinuxFramebuffer/LinuxFramebufferPlatform.cs:line 151
```

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux 
- Version 11.0.0 Preview 2

**Additional context**

**Comment by Coloryr** [comment]
`11.0.0 Preview 5` is same

**Comment by AndreSteenbergen** [comment]
I am getting this same issue as well

System: Radxa model rock 3
Mali g52

Kmscube is running fine

**Comment by AndreSteenbergen** [comment]
![IMG_20230304_235008](https://user-images.githubusercontent.com/7676790/222932142-ed718903-c7ea-44ab-b9dd-9006f74f917a.jpg)
Maybe this helps. This is the output from kmscube

**Comment by AndreSteenbergen** [comment]
Could this be a problem for us as well?
https://github.com/ardera/flutter-pi/issues/13

when I look into /dev/dri/* I see card0, card1, renderD128 and renderD129

**Comment by AndreSteenbergen** [comment]
I get a different error now when I specify the card to use. I don't have an ssh connection to the SBC. But when specifying /dev/dri/card0 I get a EGL_BAD_MATCH error.

at CreateWindowSurface. Maybe that helps

**Comment by AndreSteenbergen** [comment]
![IMG_20230305_003106](https://user-images.githubusercontent.com/7676790/222933414-6aaf6ee1-bf3f-4176-b8ce-344af3008ba8.jpg)
Is a picture of my screen

**Comment by kekekeks** [comment]
The card search order got changed by https://github.com/AvaloniaUI/Avalonia/pull/7749

I think it is now somewhat random since it enumerates cards in filesystem order.

We should probably rewrite our code to scan cards in numeric order and to pick the first one that actually works instead of the first one we can get a file descriptor for.


As a workaround, pass the correct card to the `card` parameter of `StartLinuxDrm`

**Comment by AndreSteenbergen** [comment]
I did I get the above error now: EGL_BAD_MATCH now. I am debugging why I am getting that particular error

**Comment by AndreSteenbergen** [comment]
```
        using (var x = new DrmCard(Card))
        {
            try
            {
                var y = x.GetResources(true);
                y.Dump();
            }
            catch 
            {
            }
        }
```

Now gives:

```
    Connector
        DSI-1
            Id: 154
            Size: 217, 136 mm
            Encode id: 153
            Modes
                800x480
```

**Comment by Coloryr** [comment]
work in `11.0.999-cibuild0033386-beta` when set card0

**Comment by Coloryr** [comment]
![I2%ATE)$8KO)$0J{136LH@H](https://user-images.githubusercontent.com/26276037/232697056-35dbe99a-10d3-4487-b517-65b2fe336a9f.png)

**Comment by Coloryr** [comment]
I'm use Lubancat 2, RK3568

**Comment by mghcool** [comment]
I have the same problem

**Comment by mghcool** [comment]
> 我使用的是 Lubancat 2、RK3568

你目前解决这个问题了吗？能不能说明一下我也用的鲁班猫2

**Comment by Coloryr** [comment]
这边建议你换板子，鲁班猫2的固件bug很多

**Comment by rabbitism** [comment]
> 这边建议你换板子，鲁班猫2的固件bug很多
> 然后渲染不用GPU的，巨卡
> 你去dev/dri看看card有那些
> 我去年看只有card0是工作的

那rk3568用drm效果如何？

**Comment by Coloryr** [comment]
> > 这边建议你换板子，鲁班猫2的固件bug很多
> > 然后渲染不用GPU的，巨卡
> > 你去dev/dri看看card有那些
> > 我去年看只有card0是工作的
> 
> 那rk3568用drm效果如何？

走GPU的话就很好

**Comment by mghcool** [comment]
我找到问题了，是因为使用gbm_surface_create是输入的图像格式不对，应该从XR24改为AR24
``` C#
将
Avalonia.LinuxFramebuffer.Output.LibDrm.GbmColorFormats.GBM_FORMAT_XRGB8888 { get; } = FourCC('X', 'R', '2', '4');
改为
Avalonia.LinuxFramebuffer.Output.LibDrm.GbmColorFormats.GBM_FORMAT_XRGB8888 { get; } = FourCC('A', 'R', '2', '4');
```
这样就可以正常运行。
我使用ildasm将Avalonia.LinuxFramebuffer.dll反编译成il文件，修改上述位置后再用ilasm将修改的il打包成dll文件，将原来程序的替换掉就可以正常运行了

**Comment by Coloryr** [comment]
我用rk3566的orangepi 3B没这问题，估计还是lubancat的驱动问题

**Comment by fengbozs** [comment]
@Coloryr 你好，我使用rk3576，card0是工作的，连接的DSI-1， builder.StartLinuxDrm(args, card: "/dev/dri/card0", scaling: 1);出现：System.ArgumentException: bo is 0
   at Avalonia.LinuxFramebuffer.Output.DrmOutput.GetFbIdForBo(IntPtr bo)
   at Avalonia.LinuxFramebuffer.Output.DrmOutput.Init(DrmCard card, DrmResources resources, DrmConnector connector, DrmModeInfo modeInfo)
   at Avalonia.LinuxFramebuffer.Output.DrmOutput..ctor(DrmCard card, Boolean connectorsForceProbe, DrmOutputOptions options)
   at Avalonia.LinuxFramebuffer.Output.DrmOutput..ctor(String path, Boolean connectorsForceProbe, DrmOutputOptions options)
   at LinuxFramebufferPlatformExtensions.StartLinuxDrm(AppBuilder builder, String[] args, String card, Double scaling, IInputBackend inputBackend)
   at OpsTerminal.App.Program.Main(String[] args) in D:\MyCodes\BHFSolution\OpsTerminal\OpsTerminal.App\Program.cs:line 80 可以指导一下吗？

**Comment by Coloryr** [comment]
> [@Coloryr](https://github.com/Coloryr) 你好，我使用rk3576，card0是工作的，连接的DSI-1， builder.StartLinuxDrm(args, card: "/dev/dri/card0", scaling: 1);出现：System.ArgumentException: bo is 0 at Avalonia.LinuxFramebuffer.Output.DrmOutput.GetFbIdForBo(IntPtr bo) at Avalonia.LinuxFramebuffer.Output.DrmOutput.Init(DrmCard card, DrmResources resources, DrmConnector connector, DrmModeInfo modeInfo) at Avalonia.LinuxFramebuffer.Output.DrmOutput..ctor(DrmCard card, Boolean connectorsForceProbe, DrmOutputOptions options) at Avalonia.LinuxFramebuffer.Output.DrmOutput..ctor(String path, Boolean connectorsForceProbe, DrmOutputOptions options) at LinuxFramebufferPlatformExtensions.StartLinuxDrm(AppBuilder builder, String[] args, String card, Double scaling, IInputBackend inputBackend) at OpsTerminal.App.Program.Main(String[] args) in D:\MyCodes\BHFSolution\OpsTerminal\OpsTerminal.App\Program.cs:line 80 可以指导一下吗？

你驱动没做完，drm不工作

**Comment by fengbozs** [comment]
@Coloryr 是不是要用开源社区的驱动呀？我现在用的官方的闭源驱动

**Comment by fengbozs** [comment]
> 我找到问题了，是因为使用gbm_surface_create是输入的图像格式不对，应该从XR24改为AR24
> 
> 将
> Avalonia.LinuxFramebuffer.Output.LibDrm.GbmColorFormats.GBM_FORMAT_XRGB8888 { get; } = FourCC('X', 'R', '2', '4');
> 改为
> Avalonia.LinuxFramebuffer.Output.LibDrm.GbmColorFormats.GBM_FORMAT_XRGB8888 { get; } = FourCC('A', 'R', '2', '4');
> 这样就可以正常运行。 我使用ildasm将Avalonia.LinuxFramebuffer.dll反编译成il文件，修改上述位置后再用ilasm将修改的il打包成dll文件，将原来程序的替换掉就可以正常运行了

可行，改成A重新编译解决了，谢谢
