### ISSUE TITLE
Toggles switch animation is lost in Avalonia 11

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#9196]
**Describe the bug**
The toggle switch animation that was performed when clicking the toggle switch is now lost in Avalonia 11.

**To Reproduce**

1. Open the Control Catalog.
2. Select the ToggleSwitch tab.
4. Click any toggle switch button.
5. See that the toggle switch does not display the animation.

**Expected behavior**
The toggle switch should display the [animation](https://github.com/AvaloniaUI/Avalonia/blob/c7d10ac09de411a2af0f0d3b7c8febc849179a5b/src/Avalonia.Themes.Fluent/Controls/ToggleSwitch.xaml#L138).

**Screenshots**
Before
![animation-working](https://user-images.githubusercontent.com/501613/195980383-aab5d9aa-4a76-4b7c-81e8-985ca4973696.gif)
After
![animation-not-working](https://user-images.githubusercontent.com/501613/195980390-133d4101-730d-4241-9935-b232bdbcac27.gif)

**Desktop (please complete the following information):**
- OS: Windows (but probably happens in other platforms also)
- Version 11.0-preview2

**Comment by rabbitism** [comment]
I will fix this. related to template part renaming.
