### ISSUE TITLE
RichTextBlock incorrectly layouts nested views

### ISSUE THREAD

**Issue by Dolfik1** [AvaloniaUI/Avalonia#9208]
**Describe the bug**
A nested views inside `RichTextBlock` are incorrectly layouted in the following cases:

1. If RichTextBlock has a padding
2. If nested views are located at the end of the text

**To Reproduce**
See screenshots

**Expected behavior**
1. A nested views must respect padding.
2. A nested views must be correctly located at the end of the text (In my case, it is also important that they correctly add line breaks based on it's size)

**Screenshots**
1. (here is strange space between second border and "Hello")
```xaml
  <RichTextBlock Margin="30">
    <Border 
      Width="10"
      Height="10"
      Background="Red"></Border>
    
    <Border 
      Width="100"
      Height="5"
      Background="Black"></Border>
    
    <Run Foreground="Red">Hello</Run>
    <Run Foreground="Blue">World</Run>
    
  </RichTextBlock>
```
<img width="307" alt="image" src="https://user-images.githubusercontent.com/5128766/196047651-0d429070-7fd4-4cfd-b593-f7d702be94a0.png">

2. (nested views does not respect RichTextBlock's paddings)
```xaml
  <RichTextBlock Padding="30">
    <Border 
      Width="10"
      Height="10"
      Background="Red"></Border>
    
    <Border 
      Width="100"
      Height="5"
      Background="Black"></Border>
    
    <Run Foreground="Red">Hello</Run>
    <Run Foreground="Blue">World</Run>
    
  </RichTextBlock>
```
<img width="281" alt="image" src="https://user-images.githubusercontent.com/5128766/196047700-4a0ec7c3-3527-4ff4-b2b7-7df208c5eab1.png">

3. (nested views are drawn at the beginning of the line)
```xaml
  <RichTextBlock Padding="30">
    
    <Run Foreground="Red">Hello</Run>
    <Run Foreground="Blue">World</Run>
    <Border 
      Width="10"
      Height="10"
      Background="Red"></Border>
    
    <Border 
      Width="100"
      Height="5"
      Background="Black"></Border>
    
  </RichTextBlock>
```
<img width="177" alt="image" src="https://user-images.githubusercontent.com/5128766/196047727-9e87915b-2c43-4fbe-9dbf-2bbf4edacb04.png">

**Desktop (please complete the following information):**

- OS: MacOS 12.5.1
- Version 11.0.0-preview2

**Comment by Gillibald** [comment]
#9147

**Comment by Dolfik1** [comment]
@Gillibald thank you!

I have tested build `11.0.999-cibuild0024849-beta` and it looks much better but there are some issues.

1. Redunant space between red and black rectangle and between black rectangle and "Hello" text.  It is also extra space above rectangles.

<img width="286" alt="image" src="https://user-images.githubusercontent.com/5128766/196098484-c5db16e9-3f86-47a6-a4bb-26fbf5ceed6c.png">

2. Padding is still ignored. And it
<img width="288" alt="image" src="https://user-images.githubusercontent.com/5128766/196099022-d72a8d53-1a36-41fd-996a-1f4b0795ed58.png">

3. This looks much better, but padding is broken.
<img width="259" alt="image" src="https://user-images.githubusercontent.com/5128766/196099294-a800c6f4-61d8-4101-8bc0-79d9f787428c.png">

4. This is same as the 3 but `padding` replaced with `margin`. Here is the same problems as described in 1.
<img width="325" alt="image" src="https://user-images.githubusercontent.com/5128766/196099389-0a62cb97-6388-4375-9e3d-abd09edf82c9.png">

**Comment by Dolfik1** [comment]
There are also some problems with WordWrap (see window width in Title):
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Name="WindowElement"
        Title="{Binding Width, ElementName=WindowElement}">
  <RichTextBlock Margin="30" TextWrapping="Wrap">
    <Run Foreground="Red">Hello</Run>
    <Run Foreground="Blue">World</Run>
    
    <Run Foreground="Black">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dui ante, tempus quis arcu in, sagittis condimentum nisl. Curabitur venenatis ipsum quis orci tristique, quis vehicula neque bibendum. Pellentesque consequat</Run>
    <Border 
      Width="10"
      Height="10"
      Background="Red"></Border>
    
    <Border 
      Width="100"
      Height="5"
      Background="Black"></Border>
    <Run>  </Run>
    <Run Foreground="Black">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dui ante, tempus quis arcu in, sagittis condimentum nisl. Curabitur venenatis ipsum quis orci tristique, quis vehicula neque bibendum. Pellentesque consequat</Run>
  </RichTextBlock>
</Window>
```

1. The "m" letter in word "ipsum" moved to new line (see text after black `Border` element)
<img width="978" alt="image" src="https://user-images.githubusercontent.com/5128766/196132842-5e8abb9d-3196-4c1e-8a0a-db17a0af4136.png">

2.
<img width="944" alt="image" src="https://user-images.githubusercontent.com/5128766/196133468-d47a4ae3-a841-42c4-a861-622b1504d4df.png">

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/9212/commits/6b6911026873a373f4c72a854fe0485347243e48

**Comment by timunie** [comment]
should have been closed in https://github.com/AvaloniaUI/Avalonia/pull/9245, so closing this now.
