### ISSUE TITLE
How to auto scroll

### ISSUE THREAD

**Issue by highspeeder** [AvaloniaUI/Avalonia#9213]
I have a textbox wrapped by a scrollviewer.
Is there a way to automatically scroll down to the bottom when the text of the textbox changes? I hope don't violate the mvvm rules.

```
<ScrollViewer x:Name="LogSV" VerticalScrollBarVisibility="Auto" HorizontalScrollBarVisibility="Auto">
    <TextBox x:Name="LogText" Text="{Binding Log}" IsReadOnly="True" Focusable="False"/>
</ScrollViewer>
```

**Comment by timunie** [comment]
You may want to create a custom behavior for this. I think it's okay to use with MVVM. 

check out Avalonia.Behavios repo for ideas and how it works.

**Comment by highspeeder** [comment]
are you saying this?
https://github.com/wieslawsoltes/AvaloniaBehaviors

**Comment by timunie** [comment]
Yes. It has some great samples. But it also has some kind of learning curve. So play around with it in a smaller sample until you feel comfortable with it. Atm I can't provide a working snippet as I can't test on my own rn.

**Comment by timunie** [comment]
One more hint: Next time if you have a question, please use either the discussion page or join us on telegram or gitter. Thank you.
