### ISSUE TITLE
Binding SolidColorBrush.Color in a control template yields binding error

### ISSUE THREAD

**Issue by billhenn** [AvaloniaUI/Avalonia#9218]
**Describe the bug**

A binding error occurs when my custom templated control is first loaded when binding a `SolidColorBrush.Color` to a styled property.  The binding works fine after that.

**To Reproduce**

I have a basic control that inherits `TemplatedControl` and has a `Color` property on it:

```
public static readonly StyledProperty<Color> ColorProperty =
	AvaloniaProperty.Register<ArcadeControlBase, Color>(nameof(Color), Colors.Transparent);

public Color Color {
	get => GetValue(ColorProperty);
	set => SetValue(ColorProperty, value);
}
```

In the control's template:

```
<Rectangle Width="10" Height="10">
	<Rectangle.Fill>
		<SolidColorBrush Color="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=Color}" />
	</Rectangle.Fill>
</Rectangle>
```

This yields an error in the VS Output tool window:

```
[Binding]Error in binding to '#00000000'.'Color': 'Null value in expression '{empty}' at '$self.TemplatedParent'.'(SolidColorBrush #59182880)
```

**Expected behavior**

There should be no binding error.

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.0-preview2

**Comment by maxkatz6** [comment]
@grokys should we change severity of this log line to Warning? As it only indicates that at some point of initialization templated parent was still null, which is normal before control is completely loaded.

**Comment by maxkatz6** [comment]
@billhenn specifically in your case there is no problems with bindings. When control is created and binding initialized, TemplatedParent is still null. It will be set later in the object lifetime, when control is attached to the visual tree.

**Comment by maxkatz6** [comment]
Same issue
https://github.com/AvaloniaUI/Avalonia/issues/9219
https://github.com/AvaloniaUI/Avalonia/issues/8100
https://github.com/AvaloniaUI/Avalonia/issues/5762
https://github.com/AvaloniaUI/Avalonia/issues/5163

**Comment by billhenn** [comment]
@maxkatz6 thank you for the additional information.  I come from WPF and am new to Avalonia.  This really threw me off for a half hour trying to figure out if I was doing something wrong before posting.

I would highly suggest that messages like this only be written to the Output if there is a legit issue.  I (and most devs) try to keep my Output completely clean so that I can clearly identify when there are problems I need to address.  It's really distracting to see the Output get clogged up with a ton of these messages, and makes it harder to identify real problems.

Considering how many others have reported similar things, hopefully that's an indication that some kind of suppression of this message is needed.  Appreciate it!

**Comment by grokys** [comment]
More context: https://github.com/AvaloniaUI/Avalonia/issues/9219#issuecomment-1282464261

**Comment by maxkatz6** [comment]
@lukaszossowski you can filter these messages by overriding value of `Log.Sink` property.

Closing as a duplicate
