### ISSUE TITLE
Avalonia solution is not loading in VS 2015

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#922]
Some projects can not be loaded:

![avaloniasolutionisnotloading](https://cloud.githubusercontent.com/assets/1150330/23853323/1d5ea0f0-07fd-11e7-9a4a-d4aa41fff7eb.png)

**Comment by danwalmsley** [comment]
I think we now require VS2017?

**Comment by KvanTTT** [comment]
This is strange, VS2017 released recently and many users did not update their IDE.  Can we support both versions of solution and projects for VS2015 and VS2017?

**Comment by fubar-coder** [comment]
That's not possible. The new .NET Core csproj file is only supported by VS2017.

**Comment by danwalmsley** [comment]
The community edition is available for free, otherwise you can continue to use Avalonia in vs2015 by using nuget packages.

**Comment by grokys** [comment]
Leaving open until we update https://github.com/AvaloniaUI/Avalonia/blob/master/docs/guidelines/build.md

**Comment by grokys** [comment]
Updated build instructions 068c63be9c10bd563058f7b1043321f48b3b4072
