### ISSUE TITLE
Update SkiaSharp to the newest version (>= 1.56.2)

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#923]
In this version very important bug fixed: [The Platform needs to be either x64 or x86 to support Skia in Windows](https://github.com/mono/SkiaSharp/issues/44). Moreover, this is not a beta, but release.

**Comment by OronDF343** [comment]
There is another problem with this: Avalonia.Skia.Desktop targets x86 only. This prevents targeting x64 (or AnyCPU)
