### ISSUE TITLE
Rendering exception on Android

### ISSUE THREAD

**Issue by CeSun** [AvaloniaUI/Avalonia#9230]
The interface is not refreshed, the default is dark gray, and the interface will be refreshed normally after clicking on the input box.

![image](https://user-images.githubusercontent.com/54771283/196489256-382a330c-d7c5-44ec-b301-82b51b826074.png)
![image](https://user-images.githubusercontent.com/54771283/196489377-d3117699-7144-418d-845d-54b2578c0a7f.png)
![image](https://user-images.githubusercontent.com/54771283/196489442-4ff3c608-48d6-47e2-a6d1-1264cd2fdec7.png)

MyPhone: OnePlus 8Pro
Soc: Qualcomm 865
System: Color OS13.0 (based Android 13)

**Comment by CeSun** [comment]
![Screenshot_2022-10-19-12-01-26-89_9d47e5dab23090ee94dafae00e04cd43](https://user-images.githubusercontent.com/54771283/196594819-4a0b800f-28f9-466d-b000-9f76450796fd.jpg)

**Comment by emmauss** [comment]
This may be an issue with Android 13. Not sure if it's from custom roms, as it doesn't affect google's emulators. Does the Ui refresh when you switch to a different app, and then back again using the Recent Apps

**Comment by tristanlabelle** [comment]
Same issue here. This is my first time trying Avalonia, I created the cross-platform app template and deployed it to my physical Google Pixel 4 running Android 13 / API 33. I saw the splash screen icon and then it transitioned to the right into a gray screen. Switching between other apps eventually makes the app contents appear.

On the emulator (Google Pixel 5 running Android 13 / API 33), I also see the gray screen but it transitions to the app contents shortly thereafter.

If there are ideas, I'm happy to put breakpoints and see if I can figure something out.

**Comment by maxkatz6** [comment]
@tristanlabelle seems like this issue is specific for some devices and/or OS version. As on emulator and my android 11 it works well. And it worked well for more people.
Can you try latest nightly build, to double check if [that PR](https://github.com/AvaloniaUI/Avalonia/pull/9154) could have fixed this problem. Or I believe you can try "11.0.0-preview3" version from nuget, it should include that PR as well.

Also, does Pixel 4 officially has Android 13? If not, do you use custom ROM? I wonder if I can try to install it on my One Plus 7T Pro and reproduce this issue (and I anyway wanted to 'upgrade' it).

**Comment by tristanlabelle** [comment]
@maxkatz6 , quick reply! I updated to `11.0.0-preview3` and it has the PR because I had to change my Activity declarations to match the sample in the PR. Unfortunately I'm still seeing the same issue of the gray screen until switching out and back in.

My Google Pixel 4 was offered Android 13 when it came out without having to do anything special. This month is its official end of support date so I may not see Android 14.

**Comment by CeSun** [comment]
> @tristanlabelle seems like this issue is specific for some devices and/or OS version. As on emulator and my android 11 it works well. And it worked well for more people. Can you try latest nightly build, to double check if [that PR](https://github.com/AvaloniaUI/Avalonia/pull/9154) could have fixed this problem. Or I believe you can try "11.0.0-preview3" version from nuget, it should include that PR as well.
> 
> Also, does Pixel 4 officially has Android 13? If not, do you use custom ROM? I wonder if I can try to install it on my One Plus 7T Pro and reproduce this issue (and I anyway wanted to 'upgrade' it).

The phone I'm using is a OnePlus 8 Pro, unfortunately he's now using custom Rom: Color OS.
Tried the nightly build version and the latest preview version, but the screen is still black, and a new crash bug has been added.

**Comment by maxkatz6** [comment]
Installed pixel experience and was able to reproduce this problem.

No clue so far, what was changed in Android to break avalonia rendering.
Old renderer (UseComposition=False) or framebuffer (UseGPU=false) don't make a difference.
Renderer is starting properly.
Renderer.Paint is also called after surface created (three times actually, but that's old).
Surface isn't corrupted.
Dirty rects are pushed.

If anybody has any ideas, it would help.

**Comment by tristanlabelle** [comment]
I investigated and found that the `SurfaceView` is not being hole-punched to allow the surface underlay to see through.

This should be done by `SurfaceView.dispatchDraw`, whose [source code](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/SurfaceView.java) is:

```java
@Override
protected void dispatchDraw(Canvas canvas) {
    if (mDrawFinished && !isAboveParent()) {
        // draw() is not called when SKIP_DRAW is set
        if ((mPrivateFlags & PFLAG_SKIP_DRAW) == PFLAG_SKIP_DRAW) {
            // punch a whole in the view-hierarchy below us
            clearSurfaceViewPort(canvas);
        }
    }
    super.dispatchDraw(canvas);
}
```

As a workaround, we can do the hole-punching ourselves by overriding `DispatchDraw` in [Avalonia.Android.Platform.SkiaPlatform.TopLevelImpl.ViewImpl](https://github.com/AvaloniaUI/Avalonia/blob/6a3a2817cf731d6f40840bf3dca058664103fd07/src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs#L149):

```cs
protected override void DispatchDraw(AndroidGraphics.Canvas canvas)
{
    base.DispatchDraw(canvas);

    // Workaround issue #9230 on where screen remains gray after splash screen.
    // base.DispatchDraw should do the below but it does not.
    var paint = new Paint();
    paint.SetColor(0);
    paint.BlendMode = BlendMode.Clear;
    canvas.DrawRect(0, 0, Width, Height, paint);
}
```

There is probably a better solution by understanding why either `mDrawFinished` or `mPrivateFlags` have values which prevent `clearSurfaceViewPort` from being called, but this is getting far past my understanding of Android rendering.
