### ISSUE TITLE
Crash after button click on Android platform

### ISSUE THREAD

**Issue by CeSun** [AvaloniaUI/Avalonia#9237]
**Describe the bug**
![image](https://user-images.githubusercontent.com/54771283/196626584-3bdf100a-43fc-43ad-b7c3-8356d06b4142.png)
Add a button to an empty avalonia project and do not bind any events, it will crash on multiple clicks on the Android platform
Exception: `System.NullReferenceException: 'Object reference not set to an instance of an object.'`
Stack:
![image](https://user-images.githubusercontent.com/54771283/196595039-715dbac3-f825-430b-8da3-d06d22d1d2f8.png)

- OS: Andorid 13
- Version 11.0.0-preview2

**Comment by timunie** [comment]
Probably more information could be useful. When does the issue happen? Do you have a sample code which will cause  the issue? Which version of Avalonia do you use? What's your OS?

We have an issue template for a good reason. If you want to do us a favor, please use it next time. Thank you for your understanding.

**Comment by CeSun** [comment]
> Probably more information could be useful. When does the issue happen? Do you have a sample code which will cause the issue? Which version of Avalonia do you use? What's your OS?
> 
> We have an issue template for a good reason. If you want to do us a favor, please use it next time. Thank you for your understanding.

Sorry, the description has been updated.

**Comment by timunie** [comment]
Thank you 😊

Now let's see if anyone is able to fix the root cause

**Comment by emmauss** [comment]
The issue isn't from Button being clicked. It's because focus was switched from the textbox to the button while the keyboard was active. This might be fixed in https://github.com/AvaloniaUI/Avalonia/pull/9164 . Could you test with the latest master packages?

**Comment by CeSun** [comment]
> The issue isn't from Button being clicked. It's because focus was switched from the textbox to the button while the keyboard was active. This might be fixed in #9164 . Could you test with the latest master packages?

So, to solve this problem, do I have to build from source?
When will the next pre-release be released?

**Comment by timunie** [comment]
You can use nightly builds for now: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

**Comment by CeSun** [comment]
> You can use nightly builds for now: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

Thank you. I'll try it tomorrow (now, it's midnight here)😁😁

**Comment by CeSun** [comment]
> You can use nightly builds for now: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

There doesn't seem to be a version higher than preview-2 in the nightly build repository.

![image](https://user-images.githubusercontent.com/54771283/197102977-48be7595-aab1-4b30-b00b-0832eb213e89.png)

**Comment by maxkatz6** [comment]
@CeSun Try build and feed from this commit https://github.com/AvaloniaUI/Avalonia/pull/9164#issuecomment-1276272352

**Comment by CeSun** [comment]
So I need to build the library myself from source, right?

**Comment by CeSun** [comment]
> @CeSun Try build and feed from this commit [#9164 (comment)](https://github.com/AvaloniaUI/Avalonia/pull/9164#issuecomment-1276272352)

So I need to build the library myself from source, right?

**Comment by maxkatz6** [comment]
@CeSun no. Follow instructions from https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed, but make sure you are using "avalonia-all" feed. 
From that comment https://github.com/AvaloniaUI/Avalonia/pull/9164#issuecomment-1276272352
Feed is https://nuget.avaloniaui.net/repository/avalonia-all/index.json
And version is 11.0.999-cibuild0024598-beta

**Comment by CeSun** [comment]
> @CeSun no. Follow instructions from https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed, but make sure you are using "avalonia-all" feed. From that comment [#9164 (comment)](https://github.com/AvaloniaUI/Avalonia/pull/9164#issuecomment-1276272352) Feed is https://nuget.avaloniaui.net/repository/avalonia-all/index.json And version is 11.0.999-cibuild0024598-beta

Still not working very well, because this nuget link is really slow...I'll just wait for the release.

**Comment by timunie** [comment]
> > You can use nightly builds for now: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed
> 
> There doesn't seem to be a version higher than preview-2 in the nightly build repository.
> 
> ![image](https://user-images.githubusercontent.com/54771283/197102977-48be7595-aab1-4b30-b00b-0832eb213e89.png)

Hey @CeSun the nuget feed was outdated. Please use the new nightly feed you can find here: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

**Comment by CeSun** [comment]
> > > You can use nightly builds for now: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed
> > 
> > There doesn't seem to be a version higher than preview-2 in the nightly build repository.
> > 
> > ![image](https://user-images.githubusercontent.com/54771283/197102977-48be7595-aab1-4b30-b00b-0832eb213e89.png)
> 
> Hey @CeSun the nuget feed was outdated. Please use the new nightly feed you can find here: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

I've tried this nuget source, it's slow, it always times out, and there's only a small chance of getting the latest package version list.
I don't think it's my network problem, because accessing the root of the nuget url is fast, although it returns me an error.

**Comment by CeSun** [comment]
> > > You can use nightly builds for now: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed
> > 
> > 
> > There doesn't seem to be a version higher than preview-2 in the nightly build repository.
> > ![image](https://user-images.githubusercontent.com/54771283/197102977-48be7595-aab1-4b30-b00b-0832eb213e89.png)
> 
> Hey @CeSun the nuget feed was outdated. Please use the new nightly feed you can find here: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

it worked.
