### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by KluDev** [AvaloniaUI/Avalonia#9242]
On the following page

https://github.com/AvaloniaUI/Avalonia/wiki/Build-Avalonia-from-Source

The link to [.NET Core - All Supported OS's](https://linkify.me/A2dP68D)

is broken!

**Comment by timunie** [comment]
Are you able to fix it and provide a PR for the fix?

**Comment by robloo** [comment]
This whole wiki page should probably move over to the docs website now IMO. The wiki should really go away.

As far as the link, this looks like the best page now: https://dotnet.microsoft.com/en-us/download/dotnet

**Comment by maxkatz6** [comment]
Up to date instructions are here https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md
I will delete this wiki page (as most of them should be).
