### ISSUE TITLE
Add DrawingBrush

### ISSUE THREAD

**Issue by billhenn** [AvaloniaUI/Avalonia#9258]
I wanted to implement a vector-based tile brush and noticed that a WPF-like `DrawingBrush` (where we can provide a geometry) doesn't seem to be available.

Is `DrawingBrush` something that is planned to be added?

**Comment by maxkatz6** [comment]
Alternatively, ImageBrush can be updated to support sources other than IBitmap.
For reference, Image class Source accepts IImage, where you can set a drawing.

Workaround for now, either to use VisualBrush or avoid brushes (by replacing them with Image).

**Comment by timunie** [comment]
IImage sounds like a good idea. Probably not too difficult to implement.

**Comment by kekekeks** [comment]
Fixed by https://github.com/AvaloniaUI/Avalonia/pull/10419
