### ISSUE TITLE
Avalonia should have a logo!

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#926]

**Comment by grokys** [comment]
Yeah, I asked a friend to do one, but he doesn't seem to have got round to it yet. Maybe it's time to look elsewhere.

**Comment by jkoritzinsky** [comment]
Yeah I really think we need a logo.

**Comment by KvanTTT** [comment]
What ideas?

**Comment by M-Curtis** [comment]
@grokys what sort of colours and style would you like??

**Comment by SlowLogicBoy** [comment]
For me first thing that came to mind, when saw this post, was something like:
![image](https://cloud.githubusercontent.com/assets/3121637/26490465/08614f6c-4214-11e7-9a1b-a05e8ee60e89.png)
I'm no UX and/nor designer, just an Idea :)

**Comment by Sorien** [comment]
http://urbanjungle.ca/2014/01/inspirational-alphabet-logo-design-series-letter-a-logo-designs/ first one

**Comment by tmteam** [comment]
Variation of  </A>  are awesome! Just style it to Html5 or something like.

**Comment by Worldbeater** [comment]
Hey guys! I've just created some stuff for you :)
![avalonia_style](https://user-images.githubusercontent.com/6759207/28480094-d3c6c7ac-6e67-11e7-899f-a54146c2b661.jpg)

**Comment by kekekeks** [comment]
![logo](https://i.imgur.com/qEGP8PJ.png)

**Comment by Sorien** [comment]
![untitled-1](https://user-images.githubusercontent.com/1270275/28719529-8246b412-73aa-11e7-900d-7fbe5de2dd3f.png)

**Comment by kekekeks** [comment]
Logo update from @Worldbeater

[![default](https://user-images.githubusercontent.com/1067584/30994702-18922ffc-a4be-11e7-86eb-41d21473ba69.png)](http://temp.keks-n.net/avalonia_outline.svg)

[![default](https://user-images.githubusercontent.com/1067584/30994710-21e0bfec-a4be-11e7-96a1-cc26ab9bc3b8.png)](http://temp.keks-n.net/avalonia_pure.svg)

[![default](https://user-images.githubusercontent.com/1067584/30994635-c587fbfc-a4bd-11e7-9555-59c26e91ab72.png)]((http://temp.keks-n.net/avalonia_pure.svg))

**Comment by jkoritzinsky** [comment]
We have the logo set up on the Github org now so I'm going to close this. Thanks to everyone who helped us pick a logo!!

**Comment by grokys** [comment]
Do we have the source for the logo in the repository?

**Comment by worldbeater** [comment]
> Do we have the source for the logo in the repository?

Almost yes @grokys 😄 
Just added SVG version of this pic.
![image](https://user-images.githubusercontent.com/6759207/34915614-86a99d74-f93a-11e7-9d80-3b8cd7d48c45.png =100x100)

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/static-images/tree/master/logo
