### ISSUE TITLE
Scrolling a ListBox with virtualization messes up the keyboard focus

### ISSUE THREAD

**Issue by megazyz** [AvaloniaUI/Avalonia#9269]
**Describe the bug**
Scrolling a ListBox with VirtualizationMode=Simple changes the keyboard focus to another item when the focused item gets out of view. The issue does not occur when VirtualizationMode is None.

**To Reproduce**

1. Create a new project in Visual Studio using the Avalonia MVVM Application template.
2. Add an Items property to MainWindowViewModel: `public List<int> Items { get; set; } = new(Enumerable.Range(0, 1000));`
3. Replace the greeting TextBlock to a ListBox in MainWindow.axaml: `<ListBox Items="{Binding Items}" VirtualizationMode="Simple"/>`
4. Run the application
5. Click on an item in the ListBox
6. Press Up Arrow or Down Arrow keys to make the keyboard focus adorner visible
7. Start scrolling down using the scrollbar or the mouse wheel (not the keyboard), and keep scrolling
8. Every time the focused item gets out of the viewport, a new item receives the keyboard focus.
9. Change VirtualizationMode to None to make the issue disappear

The issue is also visible in the VirtualizationDemo sample.

**Expected behavior**
The keyboard focus should not change while scrolling.
The virtualization code should not recycle the element having the keyboard focus.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 0.10.18, 11.0.0-preview2

**Comment by megazyz** [comment]
I'm going to create a pull request to fix this

**Comment by megazyz** [comment]
Sorry, I got lost, we need an expert here.

**Comment by maxkatz6** [comment]
> The keyboard focus should not change while scrolling.
The virtualization code should not recycle the element having the keyboard focus.

Not sure how possible it is.
I wonder, if it was solved in WPF or UWP. Can somebody check?

**Comment by maxkatz6** [comment]
Also, if ItemsRepeater and DataGrid have the same problem (probably have)

**Comment by megazyz** [comment]
It works in WPF.

**Comment by amwx** [comment]
I know it works in WinUI, if you have one of the WinUI control galleries, it's easy to repro. 

If you inspect the Native View of `Selector` in UWP, you can see they have several fields specifically for holding the current focus information for the items:
![image](https://user-images.githubusercontent.com/40413319/197916813-b44ae217-401f-4318-8fc3-246271657768.png)

And the `ViewManager` for `ItemsRepeater` holds focus info too, although I haven't tested that it works:
https://github.com/AvaloniaUI/Avalonia/blob/34d24a0f398c2ade43895004c38694b4613779b2/src/Avalonia.Controls/Repeater/ViewManager.cs#L25

**Comment by megazyz** [comment]
Checking the visual children of a ListBox using the debugger shows that WPF keeps the focused element alive in the visual tree, and does not reuse it for displaying other items.

**Comment by megazyz** [comment]
I cannot reproduce this for ItemsRepeater and DataGrid.

**Comment by megazyz** [comment]
Using ItemsRepeater in ListBox may be a possible solution, see #2594
