### ISSUE TITLE
NRE when constructing TextDecorations from XAML

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#9282]
```xaml
<TextBox>
    <TextBox.TextDecorations>
      <TextDecoration ... />
    </TextBox.TextDecorations>
</TextBox>
```

Gives me a NRE inside  	

`Avalonia.Markup.Xaml.dll!Avalonia.Markup.Xaml.XamlIl.Runtime.XamlIlRuntimeHelpers.DeferredTransformationFactoryV2.AnonymousMethod__0(System.IServiceProvider sp) Line 32	C#`

**Comment by Gillibald** [comment]
XamlX reuires you to construct a collection in advance

```
<TextBox>
    <TextBox.TextDecorations>
        <TextDecorationCollection>
            <TextDecoration ... />
        </TextDecorationCollection>
    </TextBox.TextDecorations>
</TextBox>
```

**Comment by pr8x** [comment]
Ah I see. I think in other places it works like that though? I guess because they default initialize the collection (and it's not null there)

**Comment by pr8x** [comment]
Either way we could think about making the error a bit nicer here.
