### ISSUE TITLE
Window positioned on wrong(?) monitor

### ISSUE THREAD

**Issue by Splitwirez** [AvaloniaUI/Avalonia#9286]
**Describe the bug**
In Avalonia 0.10.18, an Avalonia window would position itself on the monitor currently being interacted with when first opened. For whatever reason, after migrating to 11.0.0-preview2, they always appear on, at least in my case, my leftmost monitor...which isn't even my primary monitor.

**To Reproduce**

1. `dotnet new avalonia.app`
2. Change version of all Avalonia `PackageReference`s to `11.0.0-preview2`
3. Add another `PackageReference` for `Avalonia.Themes.Fluent` (again, version `11.0.0-preview2`)
4. `dotnet run`

**Expected behavior**
Avalonia windows appear on the monitor currently being interacted with, instead of inexplicably ~~trying to use my reflexes to snap my neck~~ appearing all the way to the top-left of the leftmost monitor.

**Desktop:**

- OS: Linux (Kubuntu 20.04, x64)
- Version 11.0.0-preview2

**Additional context**
I'm guessing nobody else here is dumb enough to put their primary monitor/laptop on the right, besides myself? I've seen other apps suffer similar mental breakdowns whilst trying to comprehend this monitor arrangement, but *an entire GUI framework*? That could hit *every* app that uses Avalonia...

**Comment by grokys** [comment]
Strange, I have my primary monitor on the right, and I'm not seeing this.

**Comment by maxkatz6** [comment]
On macOS and windows app is correctly finding out that my primary monitor is the right one. ~Causing some pain, because I opened it from the Rider on the left.~
I guess some linux distros might have a better opinion, where to open the window. Or it's a bug in linux backend in avalonia.
