### ISSUE TITLE
KeyBindings do not work on Gtk3 backend

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#929]
Avalonia version 0.4.1-build2859-alpha
```XAML
<UserControl.KeyBindings>
    <KeyBinding Command="{Static Editor:ProjectEditorCommands.ToolCubicBezierCommand}" Gesture="B"/>
</UserControl.KeyBindings>
```

Code to reproduce: https://github.com/wieslawsoltes/Core2D/blob/01af1ed099058c7b037811d8a37fd88bd193b732/src/Core2D.Avalonia/Views/ContainerViewControl.xaml#L26

**Comment by kekekeks** [comment]
GTK backend is discontinued
