### ISSUE TITLE
Focusable bug on a textbox

### ISSUE THREAD

**Issue by Buubuulle** [AvaloniaUI/Avalonia#9305]
**Describe the bug**
When deactivating Focusable on a TextBox it is still possible to take the focus.

**To Reproduce**

1. Create a textbox
2. Disable the Focusable property 
3. Right click and cut/paste text
4. You have the focus

**Expected behavior**
Disable the contextmenu when the Focusable property is set to false

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Version 0.10.18

**Comment by comesx4** [comment]
Tested the same step on WPF,  the contextmenu shown same, and the copy&paste&cut woking too, so I don't think it's a bug.

**Comment by maxkatz6** [comment]
Should be fixed in 11.0
