### ISSUE TITLE
`TransformedBounds` is never set with composition renderer

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#9308]
**Describe the bug**
![image](https://user-images.githubusercontent.com/40413319/198914195-5121479b-adde-45f8-a4d0-08b34e080091.png)

Also affects `HitTestCustom` if visual doesn't implement `ICustomSimpleHitTest` since the fallback is to test the point in the `TransformedBounds`
https://github.com/AvaloniaUI/Avalonia/blob/af1c316f53e246cdbe4fbd4983d677b667b45d66/src/Avalonia.Base/Rendering/ICustomSimpleHitTest.cs#L27-L28

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

**Comment by maxkatz6** [comment]
I believe it's by design and TransformedBounds was planned to be removed and alternative solutions provided.
CC @kekekeks

**Comment by kekekeks** [comment]
We can add `GetTransformedBounds` method which would read the most-recent value. We can't have a property with change notification.

**Comment by amwx** [comment]
BTW this is fine - I was only using indirectly from `.HitTestCustom()` which I've removed now anyway. 

Was this in the change log with the new renderer? If so, that's my bad. If not I'd add it. This threw me for a loop briefly after moving to 11.0 and [This comment](https://github.com/AvaloniaUI/Avalonia/pull/9307#issuecomment-1296400430) indicates other libraries use this property
