### ISSUE TITLE
Avalonia.ReactiveUI routing system applies styles after loading the content

### ISSUE THREAD

**Issue by vikkio88** [AvaloniaUI/Avalonia#9310]
**Describe the bug**
I have a simple app and I use routing of avalonia.reactiveui, until Avalonia 10.18 everything worked fine, I tried to upgrade to 11-preview3 and I see the content of the View loading without any style applied to it for a split second, then the styles gets applied, and the same when I navigate back.

**To Reproduce**
1. Use Avalonia.ReactiveUI routing as described on the [main doc](https://docs.avaloniaui.net/guides/deep-dives/reactiveui/routing).
2. Navigate around the app.
3. You should see the content loading unstyled then loading the style between 300-500 ms in.

**Expected behavior**
Navigation should work as it was for 10.18

**Screenshots**
Bug happening from 7 seconds onwards: [https://streamable.com/94axk7](https://streamable.com/94axk7).

Same app, Avalonia 10.18 bug not happening [https://streamable.com/z0j0hs](https://streamable.com/z0j0hs).

**Desktop**

- OS: Windows, Mac, Linux (ubuntu)
- Version 11-preview3

**Additional context**
The project I am working on is opensourced [here](https://github.com/vikkio88/FDSim).

It was setup to use Ava11Preview [here](https://github.com/vikkio88/FDSim/commit/22e04de15d946adb3b0165dfcec2f9e2384e98da)

Reverted to 10.18 [here](https://github.com/vikkio88/FDSim/commit/2ed71fb2a376835c62bf717f6e2bc2bfa0cf37ca)

**Comment by vikkio88** [comment]
if it helps I tried also by putting a null transition and did do the same

**Comment by maxkatz6** [comment]
Should be fixed with https://github.com/AvaloniaUI/Avalonia/pull/9803
