### ISSUE TITLE
Flyout: make setter of `IsOpen` property public

### ISSUE THREAD

**Issue by DmitryZhelnin** [AvaloniaUI/Avalonia#9350]
**Is your feature request related to a problem? Please describe.**
Right now there is no possibility to show/hide flyout via binding to some `bool` property of viewmodel.

**Describe the solution you'd like**
I'd like to bind `IsOpen` property of flyout to my viewmodel.
For example I have flyout with `ListBox` and want to close it when user changes selected item.
I'd like to do it by settings `IsFlyoutOpened = false` inside my viewmodel.

``` xaml
<Button Content="Click Me">
    <Button.Flyout>
        <Flyout IsOpen="{Binding IsFlyoutOpened}">
            <ListBox Items="{Binding MyListBoxItems}" SelectedItem="{Binding SelectedItem}" />
        </Flyout>
    </Button.Flyout>
</Button>
```

**Describe alternatives you've considered**
As a workaround I can listen to changes of `SelectedItem` property in code behind and call `Flyout.Hide` when selected item changes.
But that's not mvvm friendly.

**Comment by amwx** [comment]
duplicate/related to #6081

One of the main points of Flyouts are they can be shared among multiple controls so the concept of a settable `IsOpen` doesn't make sense - it could open somewhere entirely differently than you're expecting. Flyouts aren't really meant to be a replacement to popups but a higher level abstraction that allows sharing. 
In your case, a normal popup might be better or write a behavior that can translate your binding into showing/hiding the flyout, if you really don't like the code behind option.

**Comment by DmitryZhelnin** [comment]
Thanks for the reply. I totally missed the "shared" concept of flyouts.
Please close the issue :)

**Comment by maxkatz6** [comment]
To add from what @amwx already said:
In your code you use `Button.Flyout` - flyout that will be opened when button is clicked. Adding a mutable IsOpen here would conflict with this higher-level control behavior.
But keeping IsOpen as a public but readonly property still allows for other controls and styles to react, when it is open or not.
