### ISSUE TITLE
Window content doesn't render [Windows on Arm64]

### ISSUE THREAD

**Issue by olifink** [AvaloniaUI/Avalonia#9353]
**Describe the bug**
(This is a follow-up issue to #8776 ) 
On Windows on Arm (Microsoft DevKit 2023) the current `master` shows an empty window and doesn't render any content.

**To Reproduce**

1. Build on Windows on Arm64 
2. Run `ControlCatalog.NetCore` target
4. Only the frame shows transparently without content, it can be moved, resized and closed normally, just no content is rendered.

**Expected behavior**
Control Catalog window should be shown

**Screenshots**

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/323250/199814479-b40a608f-993b-4154-9040-c3459f42e49f.png">

**Desktop (please complete the following information):**

- OS: Windows an Arm 64
- Version: master 4670536b82044e9cc21d2d3f03c98e1781453efb
 
**Additional context**
Interestingly the same problem shows for the ControlCatalog.Desktop target which runs under x86_64 emulation.
Also, can be reproduced using the packages created by #9342 `11.0.999-cibuild0025688-beta` in an empty project.

**Comment by olifink** [comment]
not sure if it's relevant at all, but these are the only errors showing in the debug output

```
[Binding]Error in binding to 'Avalonia.Controls.NativeMenuItem'.'Command': 'Null value in expression '{empty}' at ''.'(NativeMenuItem #18389930)
[Binding]Error in binding to 'Avalonia.Controls.NativeMenuItem'.'IsChecked': 'Null value in expression '{empty}' at ''.'(NativeMenuItem #18389930)
[Binding]Error in binding to 'Avalonia.Controls.NativeMenuItem'.'Command': 'Null value in expression '{empty}' at ''.'(NativeMenuItem #31291646)
[Binding]Error in binding to 'Avalonia.Controls.NativeMenuItem'.'IsChecked': 'Null value in expression '{empty}' at ''.'(NativeMenuItem #31291646)
[Binding]Error in binding to 'Avalonia.Controls.NativeMenuItem'.'Command': 'Null value in expression '{empty}' at ''.'(NativeMenuItem #13189358)
[Binding]Error in binding to 'Avalonia.Controls.NativeMenuItem'.'IsChecked': 'Null value in expression '{empty}' at ''.'(NativeMenuItem #13189358)
[Binding]Error in binding to 'Avalonia.Controls.MenuFlyout'.'Items': 'Null value in expression '{empty}' at ''.'(MenuFlyout #55467050)
[Binding]Error in binding to 'Avalonia.Controls.CalendarDatePicker'.'SelectedDate': 'The ValidatedDateExample field is required.'(CalendarDatePicker #28788263)
[Binding]Error in binding to 'Avalonia.Controls.ColumnDefinition'.'Width': 'Null value in expression '{empty}' at ''.'(ColumnDefinition #25952117)
```

**Comment by olifink** [comment]
So after more experimenting it *looks exactly like* when no Theme is given on x64 in **App.axaml** 

But it has `<FluentTheme Mode="Light"/>` set and also a reference via

`<PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.999-cibuild0025688-beta" />`

still, contrary to not setting the theme in x64 where it then obviously wouldn't show in MyApp.App.Styles the theme actually appears to at least be loaded correctly

![image](https://user-images.githubusercontent.com/323250/200122072-f554e2a3-864a-47c2-9896-b53d7d9fdccc.png)

@maxkatz6 any other ideas where to look? it seems fail somewhere down the rendering pipeline

also, if I try set `TransparencyLevelHint="AcrylicBlur"` on the window the blur shows as it should, but that is probably coming from the compositor and not the renderer:
![image](https://user-images.githubusercontent.com/323250/200121217-2804a551-bb1e-4738-aba6-937bd3687afb.png)

**Comment by ahopper** [comment]
do you see any render exceptions in the output window when run in the debugger.  I am seeing the same thing using GylphRuns with a very recent master and exceptions are shown in vs

**Comment by olifink** [comment]
@ahopper when I run the **samples/RenderDemo** project I see an issue with `glyphOffsets` being Null where it shouldn't 

`Exception thrown: 'System.NullReferenceException' in Avalonia.Skia.dll`

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/323250/200335070-d0a43cab-73fc-4bf9-ad24-d5611a8286d1.png">

**Comment by olifink** [comment]
@Gillibald maybe you an idea, it might be related to a recent commit from you 
 17b2834d21f7e7acd63586b69f8ece4d7099f131

**Comment by olifink** [comment]
when I change the `glyphOffsets` which is null to `glyphIndices` in the loop counter I can get the FPS overlay working at least
<img width="501" alt="image" src="https://user-images.githubusercontent.com/323250/200355550-98282d1a-6fa8-43cd-a996-a4d2f17729be.png">

still, nothing else renders though, but it's nice to at least see something happening in the window now
