### ISSUE TITLE
Avalonia extension not available for Visual Studio 2017

### ISSUE THREAD

**Issue by OronDF343** [AvaloniaUI/Avalonia#936]
The Visual Studio extension only supports 2015. Is there a way to install it from a nightly build feed, or is it not ready yet?

**Comment by grokys** [comment]
Yeah, sorry - we've not had chance yet to update it to 2017. The extension is kind of without a maintainer at the moment, so we need to find some time.

**Comment by fonix232** [comment]
Since the extension only adds a project template and a few file templates, it is perfectly safe to just add the v15.0 install target to the VSIX manifest:

    <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[15.0]" />

or expand the existing one with 15.0 as the "up to" version.

**Comment by kekekeks** [comment]
Ehm, actually it adds XAML autocomplete and previewer that are broken in VS2017

**Comment by fonix232** [comment]
Ah, you're right. Since I haven't used it in 2015, and tried it with 2017 only, I didn't notice those being broken (i.e. missing).

**Comment by OronDF343** [comment]
For now is there any way to develop with Avalonia in VS2017 without the extension? I tried to create a new project manually based on the samples and I keep getting either DXGI_ERROR_INVALID_CALL or a blank window.

**Comment by kekekeks** [comment]
It's probably related to Direct2D backend issues after moving to DX11. Try with Skia.

**Comment by OronDF343** [comment]
That fixed it, thanks!

**Comment by kekekeks** [comment]
#869

**Comment by theweavrs** [comment]
Any update on this?

**Comment by kekekeks** [comment]
You can either build from source or use this buld (experimental) - https://www.dropbox.com/s/i0l0qlt4jrxr7ou/AvaloniaVS.vsix?dl=0

Known issues:
- Sometimes you need to reopen editor to make completion work
- Sometimes you need to reload solution to make previewer work (usually after changing `TargetFrameworks` or unloading/reloading projects)

**Comment by taynes13** [comment]
I just migrated the extension to VS 2017 (I haven't found way how to make it running in both VS 2015 and VS 2017 at the same time). Dunno if it is of any use to somebody else so I shall create pull request of it or I just use it till somebody with better knowledge of VS extension projects will do proper upgrade. 

Code is in branch VS2017 in my cloned repo https://github.com/taynes13/AvaloniaVS/tree/vs2017

**Comment by grokys** [comment]
@taynes13 from what I understand, `master` on https://github.com/AvaloniaUI/AvaloniaVS now works with VS2017 (see the message above yours). Not sure if your changes have all been addressed there?

**Comment by taynes13** [comment]
@grokys you're right, this commit https://github.com/AvaloniaUI/AvaloniaVS/commit/497b66109b6a5d6440a0b06eda6fe5e19456a640 seems to do equivalent thing (and more)

**Comment by kekekeks** [comment]
Extension is now updated with new project templates. 

Also added a duct tape measure for outdated/invalid project info.
![image](https://i.imgur.com/UqFhTgy.png)
