### ISSUE TITLE
UI lockup on arm32 on rpi

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#9367]
**Describe the bug**
the ui locks up on arm32 on rpi using 11.0.999-cibuild0025731-beta

**To Reproduce**

create an app from the basic template, update to 11.0.999-cibuild0025731-beta and
put ```<Slider />``` in MainWindow.axaml, run and move the slider, here it stops working and the window becomes unresponsive.
I don't believe it is specific to the slider, a much bigger app with no slider visible does the same thing.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

**Comment by jp2masa** [comment]
Maybe it's the same as #9323?

**Comment by ahopper** [comment]
Neither dotnet-stack or gdb give anything useful. I've never been able to get dotnet-stack to show symbols on arm32.

**Comment by ahopper** [comment]
> Maybe it's the same as #9323?

yes it does seem very similar although I don't see the same exception.

**Comment by ahopper** [comment]
setting UseCompositor to false appears to prevent the lockup.  I tested on windows 32 bit to see if I could recreate the issue on another 32 bit platform but could not make it lockup

**Comment by ahopper** [comment]
#9817 seems to have fixed this for my app. Thanks
