### ISSUE TITLE
Generated MenuItems cannot bind to commands or methods with strongly typed parameters with inline style

### ISSUE THREAD

**Issue by stevemonaco** [AvaloniaUI/Avalonia#9372]
**Describe the bug**
When generating `MenuItem`s from `Items` with an inline style, a binded command with a parameter will throw an exception if the `RelayCommand<T>` is not of type `object`. Binding to a method with a strong type (not `object`) will show a disabled menu parent with no child items. Method binding issue may be related to https://github.com/AvaloniaUI/Avalonia/pull/8905.

**To Reproduce**
[Full repro with multiple scenarios](https://github.com/stevemonaco/AvaloniaDynamicMenuTest)

```xml
<MenuItem Header="Recent Files" Items="{Binding RecentFiles}">
	<MenuItem.Styles>
		<Style Selector="MenuItem">
			<Setter Property="Command" Value="{ReflectionBinding #menu.DataContext.OpenRecentFileWithStringCommand}" />
			<Setter Property="CommandParameter" Value="{Binding}" />
			<Setter Property="Header" Value="{Binding}" />
		</Style>
	</MenuItem.Styles>
</MenuItem>
```
RecentFiles is an `ObservableCollection<string>`

![image](https://user-images.githubusercontent.com/1782158/200268413-7268a314-a1a5-4e96-80d3-d4d4527dabbe.png)

[MenuItem.TryUpdateCanExecute](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/MenuItem.cs#L604) is the last Avalonia location of the crash. Mvvm Toolkit ends with a `CanExecute` and `ThrowArgumentExceptionForInvalidCommandArgument`. This scenario works when I change to `RelayCommand<object>` and cast the parameter to `string`.

Alternatively, applying a top-level selector instead of inline does work with strongly typed parameters:
```xml
<!-- Top-level selector handling everything -->
<Style Selector="MenuItem.recentCommand > MenuItem">
	<Setter Property="Header" Value="{Binding}" />
	<Setter Property="CommandParameter" Value="{Binding}" />
	<Setter Property="Command" Value="{ReflectionBinding #menu.DataContext.OpenRecentFileWithStringCommand}" />
</Style>
...
<MenuItem Header="StringCommand.recentCommand">
	<MenuItem Classes="recentCommand" Header="Recent Files" Items="{Binding RecentFiles}" />
</MenuItem>
```

**Expected behavior**
I expect to bind to commands with strongly typed parameters. T is `string` in the repro. The inline style approach was mentioned in other issues about dynamic menu generation as well as the [docs](https://docs.avaloniaui.net/docs/controls/menu#dynamically-creating-menus).

**Desktop (please complete the following information):**

- OS: Win10
- Version: 0.10.18 and 11-preview3

**Comment by RaphaelBuquet** [comment]
This might be the same issue as #3100.
It turns out that adding a <Style> to <MenuItem.Styles> applies the style to _that menu item_ as well as its children. Not just its children.
A solution is detailed here: https://github.com/AvaloniaUI/Avalonia/issues/3100#issuecomment-753452752
