### ISSUE TITLE
'XOpenDisplay failed' error under WSL2 Ubuntu-22.04 (WSL1 Ubuntu 20.04 works fine)

### ISSUE THREAD

**Issue by bairog** [AvaloniaUI/Avalonia#9373]
**Describe the bug**
When I try to run an application create from a template on **WSL2** Ubuntu-22.04 it fails with the following error:
```
Exception thrown: 'System.Exception' in Avalonia.X11.dll
An unhandled exception of type 'System.Exception' occurred in Avalonia.X11.dll: 'XOpenDisplay failed'
Stack trace:
 >   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
 >   at Avalonia.Controls.AppBuilderBase`1.Setup()
 >   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
 >   at AvaloniaApplication1.Program.Main(String[] args) in D:\AvaloniaApplication\AvaloniaApplication1\Program.cs:line 12
```
**WSL1** Ubuntu-20.04 starts correctly. 
I have Windows 10 Pro **21H2** and Visual Studio 2022 Pro 1**7.3.6**. My WSL distros:
![image](https://user-images.githubusercontent.com/44995181/200286951-e854ca5e-4777-4f6d-8406-8664fe04ee40.png)
My launchSettings.json:
```
{
  "profiles": {
    "AvaloniaApplication1": {
      "commandName": "Project"
    },
    "WSL1 - Ubuntu-20.04": {
      "commandName": "WSL",
      "environmentVariables": {
        "DISPLAY": ":0" //,
        //"GDK_GL": "gles" // use this line when running under WSL on Windows 11
      },
      "distributionName": "Ubuntu-20.04"
    },
    "WSL2 - Ubuntu-22.04": {
      "commandName": "WSL",
      "environmentVariables": {
        "DISPLAY": ":0" //,
        //"GDK_GL": "gles" // use this line when running under WSL on Windows 11
      },
      "distributionName": "Ubuntu-22.04"
    }
  }
}
```
I use "commandName": "WSL" not "WSL2" as [MS article](https://learn.microsoft.com/en-us/visualstudio/debugger/debug-dotnet-core-in-wsl-2) states that:

> Starting in Visual Studio 2022 Preview 3, the command name in the Launch Profile changed from WSL2 to WSL.

I use [vcXsrv](https://sourceforge.net/projects/vcxsrv/) (an X11 server for Windows) and start it in "Multiple windows" mode and then "no client" mode.

**Desktop (please complete the following information):**
- OS: WSL2 Ubuntu-22.04
- Version: 0.10.18

**Additional context**
Reproduced only under WSL2, works fine on WSL1 and normal Ubuntu.

**Comment by timunie** [comment]
Hi @bairog 

From this link I learned that in the newer version Ubuntu uses Wayland: https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop 

We have a PR for supporting this open, see #8352 . Maybe you can try this PR out on your machine?

**Comment by bairog** [comment]
Hi @timunie 
> From this link I learned that in the newer version Ubuntu uses Wayland: https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop

Do I understand correctly that WSL does not have GUI, so **/etc/gdm3/custom.conf** doesn't exist, which means that I cannot switch default Wayland back to Xorg?
> We have a PR for supporting this open, see #8352 . Maybe you can try this PR out on your machine?

I've downloaded that PR but looks like project targets **.NET 7.0 RC2**.  We are not allowed to use prerelease versions of .NET SDKs - so I will try again tomorrow evening when Visual Studio 2022 **17.4.0** and .NET 7.0 will be released :)

**Comment by timunie** [comment]
> Do I understand correctly that WSL does not have GUI, so /etc/gdm3/custom.conf doesn't exist, which means that I cannot switch default Wayland back to X11?

Sorry, that's beyond my knowledge.

**Comment by kekekeks** [comment]
Missing X11 display is an issue with WSL itself, not Avalonia

**Comment by mikelor** [comment]
@kekekeks and @timunie  Other GUI apps work on WSL with Ubuntu 22.04. I filed an issue on [microsoft/wsl](https://github.com/microsoft/WSL/issues/11777) to report an issue with Git Credential Manager which fails for with this same error. Chrome runs fine. I also reported this issue on [Git Credential Manager](https://github.com/git-ecosystem/git-credential-manager/issues/1592#issue-2251033389)

I just downloaded and tried to run [Chronify](https://chronify.me/) another Avalonia based app and it fails just like Git Credential Manager.

The common thread with this error is that they are both Avalonia based.

**Comment by maxkatz6** [comment]
@mikelor Avalonia doesn't do anything special, but opens a display connection https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/X11Platform.cs#L57. Something like this should work on properly configured machine. Let's see what WSL response is.

**Comment by mikelor** [comment]
So, I found the issue. Looks like a change in WSL's networking and DNS Tunneling as described here.
https://github.com/microsoft/WSL/issues/11698#issuecomment-2176996205

export DISPLAY=$(ip route | grep default | awk '{print $3}'):0.0

Thanks for reading.

**Comment by timunie** [comment]
@mikelor I'm not using wsl rn, so can't judge on my own. Do you think this change should be on Avalonia side? If so, so may want to provide a PR to help others as well.
