### ISSUE TITLE
Avalonia 11.0-Preview3 System.ArgumentNullException:“Value cannot be null. Arg_ParamName_Name”

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#9378]
**Describe the bug**
The exception will throw when changing the value of ResourceDictionaries or updating Style.

**To Reproduce**
Update the resource dictionary will trigger the exception.

```
 	Avalonia.Base.dll!Avalonia.Media.FontFamily.FontFamily(System.Uri baseUri, string name)	
 	Avalonia.Skia.dll!Avalonia.Skia.FontManagerImpl.TryMatchCharacter(int codepoint, Avalonia.Media.FontStyle fontStyle, Avalonia.Media.FontWeight fontWeight, Avalonia.Media.FontStretch fontStretch, Avalonia.Media.FontFamily fontFamily, System.Globalization.CultureInfo culture, out Avalonia.Media.Typeface fontKey)	
 	Avalonia.Base.dll!Avalonia.Media.FontManager.TryMatchCharacter(int codepoint, Avalonia.Media.FontStyle fontStyle, Avalonia.Media.FontWeight fontWeight, Avalonia.Media.FontStretch fontStretch, Avalonia.Media.FontFamily fontFamily, System.Globalization.CultureInfo culture, out Avalonia.Media.Typeface typeface)	
 	Avalonia.Base.dll!Avalonia.Media.TextFormatting.TextCharacters.CreateShapeableRun(Avalonia.Utilities.ReadOnlySlice<char> text, Avalonia.Media.TextFormatting.TextRunProperties defaultProperties, sbyte biDiLevel, ref Avalonia.Media.TextFormatting.TextRunProperties previousProperties)	
 	Avalonia.Base.dll!Avalonia.Media.TextFormatting.TextCharacters.GetShapeableCharacters(Avalonia.Utilities.ReadOnlySlice<char> runText, sbyte biDiLevel, ref Avalonia.Media.TextFormatting.TextRunProperties previousProperties)	
 	Avalonia.Base.dll!Avalonia.Media.TextFormatting.TextFormatterImpl.CoalesceLevels(System.Collections.Generic.IReadOnlyList<Avalonia.Media.TextFormatting.TextRun> textCharacters, Avalonia.Utilities.ArraySlice<sbyte> levels)	
 	Avalonia.Base.dll!Avalonia.Media.TextFormatting.TextFormatterImpl.ShapeTextRuns(System.Collections.Generic.List<Avalonia.Media.TextFormatting.TextRun> textRuns, Avalonia.Media.TextFormatting.TextParagraphProperties paragraphProperties, out Avalonia.Media.FlowDirection resolvedFlowDirection)	
 	Avalonia.Base.dll!Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(Avalonia.Media.TextFormatting.ITextSource textSource, int firstTextSourceIndex, double paragraphWidth, Avalonia.Media.TextFormatting.TextParagraphProperties paragraphProperties, Avalonia.Media.TextFormatting.TextLineBreak previousLineBreak)	
 	Avalonia.Base.dll!Avalonia.Media.TextFormatting.TextLayout.CreateTextLines()	
 	Avalonia.Controls.dll!Avalonia.Controls.TextBlock.CreateTextLayout(string text)	
 	Avalonia.Controls.dll!Avalonia.Controls.TextBlock.Render(Avalonia.Media.DrawingContext context)	
 	Avalonia.Base.dll!Avalonia.Rendering.Composition.CompositingRenderer.UpdateCore()	
 	Avalonia.Base.dll!Avalonia.Rendering.Composition.CompositingRenderer.Update(System.Threading.Tasks.Task batchCompletion)	
 	Avalonia.Base.dll!Avalonia.Rendering.Composition.Compositor.Commit()	
 	Avalonia.Base.dll!Avalonia.Rendering.Composition.CompositingRenderer.Dispose()	
 	Avalonia.Controls.dll!Avalonia.Controls.TopLevel.HandleClosed()	
 	Avalonia.Controls.dll!Avalonia.Controls.WindowBase.HandleClosed()	
 	Avalonia.Win32.dll!Avalonia.Win32.WindowImpl.AppWndProc(System.IntPtr hWnd, uint msg, System.IntPtr wParam, System.IntPtr lParam)	
 	Avalonia.Win32.dll!Avalonia.Win32.WindowImpl.WndProc(System.IntPtr hWnd, uint msg, System.IntPtr wParam, System.IntPtr lParam)	
 	[本机到托管的转换]	
 	[托管到本机的转换]	
 	Avalonia.Win32.dll!Avalonia.Win32.WindowImpl.Dispose()	
 	Avalonia.Controls.dll!Avalonia.Controls.Primitives.PopupRoot.Dispose()	
 	System.Reactive.dll!System.Reactive.Disposables.AnonymousDisposable<(Avalonia.Controls.Primitives.IPopupHost, System.Reactive.Disposables.CompositeDisposable)>.Dispose()	
 	Avalonia.Controls.dll!Avalonia.Controls.Primitives.Popup.CloseCore()	
 	Avalonia.Controls.dll!Avalonia.Controls.ComboBox.OnPointerReleased(Avalonia.Input.PointerReleasedEventArgs e)	
 	System.Reactive.dll!System.Reactive.Subjects.Subject<(object, Avalonia.Interactivity.RoutedEventArgs)>.OnNext((object, Avalonia.Interactivity.RoutedEventArgs) value)	
 	Avalonia.Base.dll!Avalonia.Interactivity.EventRoute.RaiseEventImpl(Avalonia.Interactivity.RoutedEventArgs e)	
 	Avalonia.Base.dll!Avalonia.Interactivity.EventRoute.RaiseEvent(Avalonia.Interactivity.IInteractive source, Avalonia.Interactivity.RoutedEventArgs e)	
 	Avalonia.Base.dll!Avalonia.Interactivity.Interactive.RaiseEvent(Avalonia.Interactivity.RoutedEventArgs e)	
 	Avalonia.Base.dll!Avalonia.Input.MouseDevice.MouseUp(Avalonia.Input.IMouseDevice device, ulong timestamp, Avalonia.Input.IInputRoot root, Avalonia.Point p, Avalonia.Input.PointerPointProperties props, Avalonia.Input.KeyModifiers inputModifiers, Avalonia.Input.IInputElement hitTest)	
 	Avalonia.Base.dll!Avalonia.Input.MouseDevice.ProcessRawEvent(Avalonia.Input.Raw.RawPointerEventArgs e)	
 	Avalonia.Base.dll!Avalonia.Input.InputManager.ProcessInput(Avalonia.Input.Raw.RawInputEventArgs e)	
 	Avalonia.Controls.dll!Avalonia.Controls.TopLevel.HandleInput(Avalonia.Input.Raw.RawInputEventArgs e)	
 	Avalonia.Win32.dll!Avalonia.Win32.WindowImpl.AppWndProc(System.IntPtr hWnd, uint msg, System.IntPtr wParam, System.IntPtr lParam)	
 	Avalonia.Win32.dll!Avalonia.Win32.WindowImpl.WndProc(System.IntPtr hWnd, uint msg, System.IntPtr wParam, System.IntPtr lParam)	
 	[本机到托管的转换]	
 	[托管到本机的转换]	
 	Avalonia.Win32.dll!Avalonia.Win32.Win32Platform.RunLoop(System.Threading.CancellationToken cancellationToken)	
 	Avalonia.Base.dll!Avalonia.Threading.Dispatcher.MainLoop(System.Threading.CancellationToken cancellationToken)	
 	Avalonia.Controls.dll!Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(string[] args)	
>	LauncherX.Avalonia.dll!LauncherX.Avalonia.Program.Main(string[] args) Line 15	C#

```

**Expected behavior**
Resources should update successfully without throw any exception.

**Screenshots**
<img width="603" alt="image" src="https://user-images.githubusercontent.com/25716486/200437024-eb270197-b825-4b54-9eef-3ba9ea81e7fd.png">

**Desktop (please complete the following information):**

- OS: Windows 11
- Version Avalonia 11.0 Preview3

**Comment by timunie** [comment]
@laolarou726 is your other issue probably related? #9387

**Comment by laolarou726** [comment]
I think so? But I didn't find any connection between them.

**Comment by timunie** [comment]
> I think so? But I didn't find any connection between them.

I think its any Font or Text that is causing this issue.

**Comment by Gillibald** [comment]
Are you using explicit font fallbacks?

I would need the actual text that is causing the issue. Looks like the font manager tries to find a matching font and fails to resolve a valid one.

**Comment by laolarou726** [comment]
@Gillibald @timunie  I just created a repo to repro this issue: https://github.com/laolarou726/FontExceptionTest

**Comment by Gillibald** [comment]
That repository isn't public

**Comment by laolarou726** [comment]
> That repository isn't public 

Just change to public repo. Sorry about that.

**Comment by timunie** [comment]
I cannot reproduce your issue with latest VS: 

before clicking the button: 
![image](https://user-images.githubusercontent.com/47110241/201111999-1662f1ea-7673-4154-9d9b-2331b966958c.png)

after: 
![image](https://user-images.githubusercontent.com/47110241/201111904-43bfba5c-9e45-46aa-810d-9dbc06f6d72a.png)


As you can see in the xaml, the line you mentioned is uncommented. I added the font file name explicitly, but this seems to make no difference for me, but worth a try for you. @Gillibald can it be the issue that the font file name was omitted?

**Comment by timunie** [comment]
at least it will crash if there is a typo in the font name.

**Comment by laolarou726** [comment]
> at least it will crash if there is a typo in the font name. 

Can you try to comment that line I mentioned? If you comment it. The exception will show up.

**Comment by laolarou726** [comment]
@timunie Sorry, the button is a little bit confusing. You don't need to click the button to trigger the exception. You just need to coment 

```xaml

<Setter Property="FontFamily" Value="/Assets/Font/#Segoe Fluent Icons" />

```

and then startup the program. You will see the exception.

**Comment by timunie** [comment]
In that case Avalonia will render a rectangle to indicate a char is missing. This is the normal behavior for all App that I know. I get no excpetion and I can interact with the button. 

![image](https://user-images.githubusercontent.com/47110241/201277022-4a254cd8-e1a6-4eeb-ab4e-9fd1bc1384a1.png)

I'm using Windows 10, I don't know if Win 11 is different here, but hard to imagine.

**Comment by laolarou726** [comment]
> In that case Avalonia will render a rectangle to indicate a char is missing. This is the normal behavior for all App that I know. I get no excpetion and I can interact with the button. 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/47110241/201277022-4a254cd8-e1a6-4eeb-ab4e-9fd1bc1384a1.png)
> 
> 
> 
> I'm using Windows 10, I don't know if Win 11 is different here, but hard to imagine. 

That's strange, I'll get this exception if I don't specify the font family.

**Comment by timunie** [comment]
can you probably test the same sample I run above again and send a screen record of your debugging until it fails? I wonder if I have overseen something.

**Comment by laolarou726** [comment]
@timunie Here is the screen record:

![Record](https://user-images.githubusercontent.com/25716486/201288920-775851be-b499-4e84-b9de-d9c988b04442.gif)

**Comment by timunie** [comment]
Thank you 👍 . I wonder if this issue is related to your language? I think my knowledge is too limited for this issue. 

@Gillibald I think if one knows what's going on, it's you.

**Comment by laolarou726** [comment]
@timunie @Gillibald Do I need to provide more info to help to resolve this issue?

**Comment by Gillibald** [comment]
We don't support mixing embedded and system fonts in a fallback sequence

**Comment by laolarou726** [comment]
> We don't support mixing embedded and system fonts in a fallback sequence. If you need a global fallback you can specify a different default font via FontManagerOptions
> 
> 
> 
> This isn't valid: https://github.com/laolarou726/FontExceptionTest/blob/master/FontExceptionTest/Assets/Style/FontStyles.axaml#L6

It seems this problem is not because this Style. I tried to remove FontStyles.axaml and also comment the codes in the TestTheme.cs. This exception still shows.

**Comment by timunie** [comment]
I still cannot reproduce. Can you try to run on a different machine?

**Comment by laolarou726** [comment]
@timunie I'll give a try on other computers later

**Comment by laolarou726** [comment]
> I still cannot reproduce. Can you try to run on a different machine? 

![image](https://user-images.githubusercontent.com/25716486/202087045-1bd0331e-4a0a-4f7b-8930-765420d76837.png)

Tried on another computer. The exception still shows.

**Comment by Gillibald** [comment]
Can't repro either

![Screenshot 2022-11-16 080729](https://user-images.githubusercontent.com/5928797/202109849-4fdf56cc-0451-4053-826d-ddcf135f3865.png)

**Comment by laolarou726** [comment]
> Can't repro either
> 
> ![Screenshot 2022-11-16 080729](https://user-images.githubusercontent.com/5928797/202109849-4fdf56cc-0451-4053-826d-ddcf135f3865.png)

hmm, that's really strange. I can repro on other computers. Is that possible to relate to OS's language settings or different kinds of stuff?

**Comment by Gillibald** [comment]
Y could be

**Comment by laolarou726** [comment]
> Y could be

How should I setup the test environment to help you guys to figure out the actual problem?

**Comment by timunie** [comment]
I think we need to setup your language configuration on a VM. Which languages do you use for your OS and also for VS?

**Comment by laolarou726** [comment]
> I think we need to setup your language configuration on a VM. Which languages do you use for your OS and also for VS? 

I'm using Simplified Chinese for both OS and VS.

**Comment by laolarou726** [comment]
It seems this issue has been resolved in the latest nightly build. SO I'll just close it.
