### ISSUE TITLE
PublishAot does not work

### ISSUE THREAD

**Issue by ivanjx** [AvaloniaUI/Avalonia#9380]
**Describe the bug**
`PublishAot` is a new feature to publish a dotnet app with NativeAOT starting in NET 7. Published app with this wont run at all.

**To Reproduce**

1. Create new avalonia project.
2. Set target framework to `net7.0`.
3. Add `<PublishAot>true</PublishAot>` and `<StripSymbols>true</StripSymbols>`.
4. Run `dotnet publish -r win-x64 -c Release`.
5. Try to run the generated binary inside the `publish` folder.

**Expected behavior**
App runs and works fine.

**Desktop (please complete the following information):**

- OS: Windows
- Version 10

**Additional context**
https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/

**Comment by wieslawsoltes** [comment]
You need to add roots file is csproj as trimming might remove some necessary stuff:
```
  <ItemGroup>
    <TrimmerRootDescriptor Include="Roots.xml" />
  </ItemGroup>
```

Roots.xml
```
<linker>

  <!-- App -->

  <assembly fullname="YourAppDllName" preserve="All" />

  <!-- Avalonia Themes -->

  <assembly fullname="Avalonia.Themes.Fluent" preserve="All" />

</linker>
```
See example here: https://github.com/wieslawsoltes/NodeEditor/pull/39/files

**Comment by ivanjx** [comment]
is it really required to exclude the entire app namespace? that kinda defeats the purpose of nativeaot

**Comment by wieslawsoltes** [comment]
> is it really required to exclude the entire app namespace? that kinda defeats the purpose of nativeaot

You can try without it, but right now there is issue with themes that use StyleInclude

**Comment by wieslawsoltes** [comment]
> > is it really required to exclude the entire app namespace? that kinda defeats the purpose of nativeaot
> 
> You can try without it, but right now there is issue with themes that use StyleInclude

You could try fine-tune roots file to just include those entries

**Comment by ivanjx** [comment]
thanks @wieslawsoltes but i still could not make my sample app working
[avalontest.zip](https://github.com/AvaloniaUI/Avalonia/files/9958851/avalontest.zip)

**Comment by maxkatz6** [comment]
@ivanjx you are using 0.10 version. 11.0 has a way better support for the AOT.

**Comment by ivanjx** [comment]
any updated docs about the rd.xml content or is it still the same one with the corert sample?

**Comment by maxkatz6** [comment]
>  or is it still the same one with the corert sample?

Yes.

> any updated docs about the rd.xml content

MS documentation should have some in general, but I don't have any link right now.

**Comment by wieslawsoltes** [comment]
> any updated docs about the rd.xml content or is it still the same one with the corert sample?

https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#root-descriptors

**Comment by wieslawsoltes** [comment]
> any updated docs about the rd.xml content or is it still the same one with the corert sample?

https://github.com/dotnet/linker/blob/main/docs/data-formats.md#descriptor-format

**Comment by ivanjx** [comment]
https://github.com/AvaloniaUI/Documentation/issues/367
