### ISSUE TITLE
UseReactiveUI() causes OverflowException for x86 windows startup

### ISSUE THREAD

**Issue by glen-nicol** [AvaloniaUI/Avalonia#9388]
Affected versions: 11.0.0-preview2 & 11.0.0-preview3
Works in 11.0.0-preview1

Steps to reproduce:
1. create new project from template
2. make necessary changed to package references to target preview version
3. Add UseReactiveUI() to AppBuilder
4. Change target platform to x86
5. Run program (previewer also doesn't load and has error below)

### Error when running:
Exception Type: System.OverflowException

Stacktrace:
```
at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 729
at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 30
```

### Error from previewer
```
[Error] 39660 <= "Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Avaloniax86Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'."
[Error] 39660 <= "   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)"
[Error] 39660 <= "   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)"
[Error] 39660 <= "   at System.Reflection.Assembly.LoadFile(String path)"
[Error] 39660 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 167"
[Error] 39660 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args) in /_/src/tools/Avalonia.Designer.HostApp/Program.cs:line 47"
```

I looked at file histories for the ReactiveUI package reference, the UseReactiveUI() extension and the WindowImpl.AppWndProc.cs file and don't see any obvious changes that would correspond to the preview 2 release.

Any ideas? I am currently cloning the repo so I may be able to debug directly if I have some guidance.

**Comment by timunie** [comment]
> I am currently cloning the repo so I may be able to debug directly if I have some guidance.

That's great. At a first idea I'd add your sample code to the `Samples > Sandbox` project. Hopefully the debugger stops and you can probably debug it. 

Happy coding
Tim

**Comment by jp2masa** [comment]
Probably related to #9209?

**Comment by maxkatz6** [comment]
@glen-nicol can you test this PR or build from there? https://github.com/AvaloniaUI/Avalonia/pull/9400

**Comment by glen-nicol** [comment]
Sorry sorry sorry, I need to re-enable notifications for my github account. I actually haven't been able to get Avalonia to build locally so I am not sure I can test that change in isolation. But I did see that this change is included in preview4 and my program seems to run when I update to that preview. Thanks!
