### ISSUE TITLE
XAML Previewer Doesn't Work Unless I move Code Outside of MainWindowViewModel Constructor

### ISSUE THREAD

**Issue by jwill222** [AvaloniaUI/Avalonia#9399]
**Describe the bug**
Hi I'm pretty new to Avalonia. I have some code that initializes a udpclient object in my MainWindowViewModel constructor. So I have something like this 

```
public MainWindowViewModel()
        {
            UdpClient client = new UdpClient(20000);

        }
```

When I go to my MainWindow.axml, the previewer does not work. I end up getting this error message:

```
15:35:14.217 [Error] 19640 UpdateXamlResult error
System.Xaml.XamlException: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```

I've run netstat on my PC and verified that port is not already open before I try the XAML Previewer. I do notice however that after I double-click on the MainWindow.axml and check netstat again, the port appears to have opened up. I'm guessing the XAML Previewer actually runs the application so that's why?

It doesn't matter what port number I put in, it continues to throw the error. If I move that code that's in the constructor to something other than the constructor, then I don't get that error message anymore.  This problem is only with the XAML Previewer. Even with the code in constructor, my application seems to build and run fine, it just seems to break the XAML Previewer. Any thoughts on what this could be? Thanks!

OS: Windows 10 
Avalonia Version 0.10.18

**Comment by maxkatz6** [comment]
> I'm guessing the XAML Previewer actually runs the application so that's why?

Exactly. That's expected behavior.
If you don't want some parts of code to be executed under the previewer process, check `Design.IsDesignMode` property.

**Comment by jwill222** [comment]
Ok so can you give me an example of how I would do that?

**Comment by maxkatz6** [comment]
```
    if (!Design.IsDesignMode)
    {
        // run code only when not in designer mode 
    }
```

**Comment by jwill222** [comment]
Thanks!


On Nov 9, 2022, at 5:25 PM, Max Katz ***@***.***> wrote:

﻿

    if (!Design.IsDesignMode)
    {
        // run code only when not in designer mode
    }
