### ISSUE TITLE
DataGrid Memory Leak

### ISSUE THREAD

**Issue by jhimes144** [AvaloniaUI/Avalonia#9414]
**Describe the bug**
`DataGrid` keeps a `NotifyCollectionChangedEventHandler` open on `Items` when `Items` is bound to a view model even after its removed from logic/visual tree. Memory leak happens when view model is not eligible to be garbage collected. I have a singleton view model that I bind to a new view instance every time the user navigates to the page.

Because of this open handle, `DataGrid` is never disposed, causing thousands of `Shapes.Rectangle` instances to survive GC.

**To Reproduce**
- Create a view model with an `ObservableCollection` of any type, populate it with a generous amount of items upon view model construction
- Create instance of view model that is referenced as a singleton (making it ineligible for garbage collection)
- Create a view with `DataGrid`, bind Items to view model's `ObservableCollection`, create dummy columns so that rows will be rendered.
- Create presentation that instantiates a new view for every navigation, `DataContext` being set to the same view model
- Navigate between view in question and elsewhere, thereby causing a new view to be instantiated and bound to view model. Repeat this a few times.
- Observe memory leak

**Expected behavior**
Memory leak does not occur.

**Screenshots**
Screenshot of Instance Retention Graph created using Redgate Ants Profiler. This graph indicates surviving objects AFTER the view has been destroyed and successfully GC'd. Note `WindchimeDataGrid` is my own inheritance of `DataGrid`, however it only contains 10 lines of code to modify selection behavior and I've recreated this bug with the normal `DataGrid`.

Also note my view model at the top, which is referenced ultimately as a single instance in my DI Container.

![retentionGraph](https://user-images.githubusercontent.com/20263191/201281967-0cfc2d0a-06a4-4201-ad0f-d8766d7a6c30.PNG)

**Desktop :**
Windows 10,0.19044

**Comment by timunie** [comment]
Hi @jhimes144 ,

looks like you have investigated this issue already quite deeply. If you think you have a solution for it, a PR is very welcome from my experience.

Happy coding
Tim

**Comment by jhimes144** [comment]
@timunie I cannot completely confirm just yet, but after taking a dive to see if I could make a fix, it appears as this has already been fixed for the upcoming release. Looking at the latest release, code has been added to handle detach and attaching to the tree and doing the proper event handle open/close logic. This code isn't present in 10.18.0

**Comment by timunie** [comment]
Maybe you can use the latest preview in a test branch of your App. But you will find several breaking changes, so be careful.

**Comment by adirh3** [comment]
@jhimes144 I experienced similar issue, and this fixed it - https://github.com/AvaloniaUI/Avalonia/pull/7948
Doesn't seemed to be backported into `0.10.x`, did you check with `11-preview`s?

**Comment by maxkatz6** [comment]
@adirh3 might have been missed or decided as not worth of a new release.
I can backport it, but I can't guarantee if 0.10.19 will even exist in near future, as we work on 11.0 now and keep 0.10 unimpactful.

**Comment by jhimes144** [comment]
In version 11 this issue is fixed.

**Comment by timunie** [comment]
@adirh3 @jhimes144 is it important for you to have this backported? tbh I think this is not worth the effort. If you agree, I'll just close this issue.

**Comment by jhimes144** [comment]
@timunie Thanks for asking! I'm good. Setting the collection to null when the user navigates away does the trick.

**Comment by jhimes144** [comment]
@timunie Thanks for asking! I'm all set, setting the collection to null fixes the issue. I accidently closed with comment, I'll let you guys do that.
