### ISSUE TITLE
Error logged to output window when binding to Run.Text

### ISSUE THREAD

**Issue by tristanlabelle** [AvaloniaUI/Avalonia#9422]
**Describe the bug**
When binding to the `Run.Text` property, an error is logged to the output window, even though the binding works properly.

**To Reproduce**

Add this xaml to an Avalonia project, like `MobileSandbox`:

```xaml
<TextBlock>
  <Run Text="{Binding MyText}"/>
</TextBlock>
```

Create the corresponding MyText property on the ViewModel.

Run the program and see output window:

`[Binding]Error in binding to 'Avalonia.Controls.Documents.Run'.'Text': 'Null value in expression '{empty}' at ''.'(Run #4861097)`

The binding eventually re-executes and works, but this behavior does not happen when binding `<TextBlock Text="{Binding MyText}"/>` directly.

**Expected behavior**
There should not be an error produced in the output window.

**Desktop:**

- OS: Windows 11
- Version 0.11.0-preview4

**Comment by RobertBeekman** [comment]
I've noticed this is causing slow layout passes because the logging takes relatively long. Any time frame on a fix would be appreciated because right now it makes `Run` unusable in complex views if you need smooth animations

**Comment by grokys** [comment]
I'm working on a binding refactor which should give the binding system enough information to know when and when not to log errors. In the meantime, if this is causing problems you can [turn off logging in the AppBuilder](https://docs.avaloniaui.net/docs/getting-started/logging-errors-and-warnings)

**Comment by ashelleyPurdue** [comment]
Is still have this exact same problem in version 11.0.10.  Are you sure the refactor fixed it?

**Comment by timunie** [comment]
Need to test 11.1 rc2 to judge that, not 11.0.10 😉
