### ISSUE TITLE
AZERTY keyboard mapping to QWERTY Key event on macOS

### ISSUE THREAD

**Issue by Energizer188** [AvaloniaUI/Avalonia#9424]
**Describe the bug**
I'm using an Azerty keyboard. When I run my Avalonia app on macOS, the key event maps as a qwerty. For example if I press 'A' key it raises a 'Q' KeyDown and KeyUp event. The TextInputEvent works correctly though, meaning the 'A' key raise a text input with 'a' text.
When I run my application on windows I got no problem, the mapping is correct.

On mac I've tested with two azerty keyboards : the one integrated in the M2 MacBook pro, and a remote keyboard, same result. 
The problem is not due to my Mac settings because the mapping is correct in other application.

**To Reproduce**

Try to run an avalonia app on mac with an azerty keyboard, listen to keydown event on the MainWindow and look at e.Key property.

**Expected behavior**
I expect the mapping to be correct. Because even if the text input works correctly, it remains a problem for KeyBindings and HotKeys.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11 (works correctly) and Macbook Pro M2 Ventura 13.0
- Version : tested with both 0.10.18 and 11 preview : it doesn't work in either case

**Additional context**

**Comment by Tenjim** [comment]
Hi guys, this issue come from mapping on qwerty hardcoded on Mac Avalonia native . there is some workaround/idea about it ?
