### ISSUE TITLE
Splash screen ends too soon

### ISSUE THREAD

**Issue by lukaszossowski** [AvaloniaUI/Avalonia#9425]
**Describe the bug**
Main view does not get fully loaded before splash activity ends. The app starts with splash screen, then slides in the actual app window showing only background and only after a moment shows the main view.

**To Reproduce**
Create a project from avalonia cross platform template and run it on Android phone.

**Expected behavior** 
Splash screen should end when main view is loaded in main window and ready to show with the slide in animation.

**Platform**
Android

**Additional context**
Perhaps I am wrong about how it should work but it seems pointless to me to have the splash screen show first only to end before the actual app is fully loaded. I have circumvented it previously with setting the main activity to start directly without splash screen and setting the window background to look like the splash screen which is closer to the desired effect (though the main view still blinks black before loading) but now on preview 4 it seems that splash screen is required to start the app.

**Comment by emmauss** [comment]
This issue has been fixed in the latest dotnet templates. In projects created from the old templates, the `LaunchMode` value in MainActivity should be changed to `LaunchMode.SingleTop`.

**Comment by lukaszossowski** [comment]
> This issue has been fixed in the latest dotnet templates. In projects created from the old templates, the `LaunchMode` value in MainActivity should be changed to `LaunchMode.SingleTop`.

Thanks, that does work! A bit of a shame that the native (I think) slide in animation is hidden this way, but the behaviour is as expected - splash screen ends and goes straight to the specified main avalonia view.
