### ISSUE TITLE
Nested ItemsRepeater causes virtualization bugs

### ISSUE THREAD

**Issue by christosk92** [AvaloniaUI/Avalonia#9427]
**Describe the bug**

Whenever virtualization is enabled on an ItemsRepeater, it causes unexpected bugs such as out of order data collections.

**To Reproduce**
1) Have an items repeater inside another ItemsRepeater representing a grouped structure.
2) make sure virtualization is enabled for the root ItemsRepeater.
3) Groups appear out of order, in a random order.

**Expected behavior**

Items appear in order as they were added.

**Screenshots**

https://user-images.githubusercontent.com/13438702/201458257-ef9b7414-e3eb-4246-9d9d-1bf1d02c6a7f.mov

**Desktop (please complete the following information):**
macOS Monterey 12.6
Avalonia version 0.10.18
- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

XAML code:
```xml
     <ScrollViewer>
               <ItemsRepeater   
                   Items="{Binding Items, Mode=OneTime}">
                <ItemsRepeater.Layout>
                    <StackLayout DisableVirtualization="False" Orientation="Vertical"/>
                </ItemsRepeater.Layout>
                <ItemsRepeater.ItemTemplate>
                <DataTemplate x:CompileBindings="True" x:DataType="avaloniaTest2:GroupView">
                    <Grid RowDefinitions="Auto,*">
                        <TextBlock Text="{Binding Title, Mode=OneTime}"/>
                        <ItemsRepeater Grid.Row="1" Items="{Binding Items,
                                 Mode=OneTime}">
                            <ItemsRepeater.Layout>
                              <StackLayout Orientation="Horizontal" DisableVirtualization="True"/>
                            </ItemsRepeater.Layout>
                            <ItemsRepeater.ItemTemplate>
                                <DataTemplate x:DataType="avaloniaTest2:TestItem">
                                    <StackPanel Margin="20" Spacing="8" Width="175" x:Name="PART_Container">
                                        <Image Source="{Binding Cover, Mode=OneWay}"/>
                                        <TextBlock Text="{Binding Title, Mode=OneTime}"
                                                   FontSize="12" Foreground="#6c6e70" 
                                                   ToolTip.Tip="{Binding Title, Mode=OneTime}">
                                            <TextBlock.OpacityMask>
                                                <LinearGradientBrush StartPoint="100%,0%" EndPoint="80%,0%">
                                                    <LinearGradientBrush.GradientStops>
                                                        <GradientStop Color="#00FFFFFF" Offset="0.1" />
                                                        <GradientStop Color="#FFFFFFFF" Offset="1" />
                                                    </LinearGradientBrush.GradientStops>
                                                </LinearGradientBrush>
                                            </TextBlock.OpacityMask>
                                        </TextBlock>

                                        <TextBlock Text="{Binding Description}" 
                                                   FontSize="10" Opacity=".8" ToolTip.Tip="{Binding Description}">
                                            <TextBlock.OpacityMask>
                                                <LinearGradientBrush StartPoint="100%,0%" EndPoint="80%,0%">
                                                    <LinearGradientBrush.GradientStops>
                                                        <GradientStop Color="#00FFFFFF" Offset="0.1" />
                                                        <GradientStop Color="#FFFFFFFF" Offset="1" />
                                                    </LinearGradientBrush.GradientStops>
                                                </LinearGradientBrush>
                                            </TextBlock.OpacityMask>
                                        </TextBlock>
                                    </StackPanel>
                                </DataTemplate>
                            </ItemsRepeater.ItemTemplate>
                        </ItemsRepeater>
                    </Grid>
                </DataTemplate>
            </ItemsRepeater.ItemTemplate>
        </ItemsRepeater>
    </ScrollViewer>
```

**Comment by maxkatz6** [comment]
Possibly related 
https://github.com/AvaloniaUI/Avalonia/issues/9288
https://github.com/AvaloniaUI/Avalonia/issues/5695
https://github.com/AvaloniaUI/Avalonia/issues/5271

**Comment by christosk92** [comment]
Changing the outer ItemsRepeater to ``ItemsControl`` does indeed fix this, but of course you miss out on the amazing performance of ItemsRepeater....

**Comment by christosk92** [comment]
@maxkatz6 Hm... I was able to fix the issue by seperating the ItemTemplates, and putting them in the ``Window.Resources``. For some reason the items appear in correct order now, with good performance. 

Do you have any idea why this might be a fix?

**Comment by christosk92** [comment]
After closer inspection, it appears that the ItemsRepeater is fetching wrong items? 

Note in the screenshot the text of "Title" and "Subtitle"
<img width="1148" alt="Screenshot 2022-11-12 at 14 37 20" src="https://user-images.githubusercontent.com/13438702/201459131-db1e8a0d-1976-4d72-b534-a5ea03c4cab1.png">

In the example, Title = Item 6, but Subtitle = Subtitle 1.

If you look at how these groups are generated, there is no way these should be different, as they are generated by the same index
<img width="800" alt="image" src="https://user-images.githubusercontent.com/13438702/201459177-50f6e58e-1444-441b-9187-3c025a1c0859.png">

**Comment by Dolfik1** [comment]
I also ran into wrong order issues in my project but I did not study the problem in more detail.

**Comment by TheXamlGuy** [comment]
We have been seeing the exact same issue on porting one of our WPF app to Avalonia. This has unfortunately put that on hold for now. I understand the issue goes upstream to WinUI so it may be a difficult one to resolve.

**Comment by grokys** [comment]
Strange: it would be helpful if someone could try the same repro in WinUI to see if the problem occurs upstream or if it's a problem in the Avalonia implementation, if anyone has time.

**Comment by christosk92** [comment]
Issue does not occur in WinUI (tested in Windows app sdk 1.2)

**Comment by Dolfik1** [comment]
> Issue does not occur in WinUI (tested in Windows app sdk 1.2)

Could you test #9288 in WinUI? I have no Windows-based desktop right now

**Comment by TheXamlGuy** [comment]
Also may be worth looking at ModernWPF's port of ItemsRepeater, which I believe is a direct port of WinUI's, see if they have same issues - https://github.com/Kinnara/ModernWpf

**Comment by christosk92** [comment]
Looks like #9677 might be addressing the issue. Excited for the next release!

**Comment by christosk92** [comment]
I’ve tested it with the masters RC and I cannot replicate the issue anymore.
I’m assuming it’s been fixed with the new virtualization stuff?

Lmk if anyone else sees the same results

**Comment by jmacato** [comment]
@christosk92 seems like we can close this then :)
