### ISSUE TITLE
$parent binding does not work with DynamicResource

### ISSUE THREAD

**Issue by ivanjx** [AvaloniaUI/Avalonia#9442]
**Describe the bug**
`$parent` binding does not work with `DynamicResource`.

**To Reproduce**

does not work:
```
<Button Foreground="{DynamicResource ThemeForegroundBrush}">
	<Viewbox Width="11">
		<Path Data="..."
			  Fill="{Binding $parent[Button].Foreground}"
			  Stretch="UniformToFill"/>
	</Viewbox>
</Button>
```
works:
```
<Button Foreground="Red">
	<Viewbox Width="11">
		<Path Data="..."
			  Fill="{Binding $parent[Button].Foreground}"
			  Stretch="UniformToFill"/>
	</Viewbox>
</Button>
```
```
<Button>
	<Viewbox Width="11">
		<Path Data="..."
			  Fill="{DynamicResource ThemeForegroundBrush}"
			  Stretch="UniformToFill"/>
	</Viewbox>
</Button>
```

**Expected behavior**
binding to parent's property with dynamic resource works.

**Desktop (please complete the following information):**

- OS: Windows
- Version 10

**Comment by timunie** [comment]
Do I remember that you had a minimal sample showing the issue? If so, please link it here again. If I read it wrong on telegram, just ignore me.

**Comment by ivanjx** [comment]
nevermind i think it is because i use `/template/ ContentPresenter` as my selector.
