### ISSUE TITLE
Compilation Error with Compiled Bindings on Static Properties with CrossGen

### ISSUE THREAD

**Issue by colejohnson66** [AvaloniaUI/Avalonia#9449]
**Describe the bug**
When using a `CompiledBinding` to a `static` property, compilation succeeds and the application runs, but with the binding results in nothing. In our case, that's an empty `<TextBlock>` But when we publish with CrossGen (for ARM), we get errors in `Microsoft.NET.CrossGen.targets`.

**To Reproduce**

1. Use a `CompiledBinding` to a static property.
2. Observe no compilation errors when debugging.
3. Observe an exception when compiling with CrossGen.

**Expected behavior**
An error during compilation from Avalonia, not CrossGen.

**Code**
View model:
```cs
public static string EasyMesurVersion => GlobalVars.VERSION;
```

View:
```
<TextBlock
    Grid.Row="0" Grid.Column="2"
    Text="{CompiledBinding EasyMesurVersion}" />
```

**Screenshots**
In debug mode, the resulting text is just empty:

![image](https://user-images.githubusercontent.com/11381599/202007665-b4a996ff-6a6b-46af-a0dd-f8db95e1a38e.png)

**Additional context**
- Avalonia 0.10.18

```
C:\<trimmed>\Microsoft.NET.CrossGen.targets(464,5): Error  : Error: One or more errors occurred. (Code generation failed for method '[easyMESUR]CompiledAvaloniaXaml.XamlIlHelpers.easyMESUR<trimmed>ViewModel,easyMESUR.EasyMesurVersion!Getter(object)')
C:\<trimmed>\Microsoft.NET.CrossGen.targets(464,5): Error  : System.AggregateException: One or more errors occurred. (Code generation failed for method '[easyMESUR]CompiledAvaloniaXaml.XamlIlHelpers.easyMESUR<trimmed>ViewModel,easyMESUR.EasyMesurVersion!Getter(object)')
...
```

**Comment by colejohnson66** [comment]
Changing the `<TextBlock>` to this fixes the exception:

```cs
<TextBlock
    Grid.Row="0" Grid.Column="2"
    x:CompileBindings="False"
    Text="{Binding EasyMesurVersion}" />
```

**Comment by timunie** [comment]
@colejohnson66 for a static property that doesn't change over time I'd just use 

```xml 
<TextBlock Text="{x:Static my:MyVM.MyProperty}" />
```

It's most likely a bug anyway, so don't close this issue 😆 .

**Comment by colejohnson66** [comment]
@timunie Yes, that would be the correct way of doing it 🤷🏻. Initially, the property wasn't static, but then we realized it could be. With normal bindings, the version still appeared, but switching to `CompiledBinding` broke it. So, yeah, PEBKAC.

And yes, it's definitely a bug that the XAML compiler didn't spew any errors.

@maxkatz6 As for the `[area-trimming]` tag, I'm not sure that's relevant; We have trimming disabled in our publish config. It was causing issues in other areas, and we didn't want to put in effort to resolve them.

**Comment by maxkatz6** [comment]
AOT also doesn't like compiled bindings with a static properties:
```
  ILC: Method '[Avalonia.Dialogs]CompiledAvaloniaXaml.XamlIlHelpers.Avalonia.Dialogs.AboutAvaloniaDialog,Avalonia.Dialogs.IsDevelopmentBuild!Getter(object)' will always throw because: Invalid IL or CLR metadata
  ILC: Method '[Avalonia.Dialogs]CompiledAvaloniaXaml.XamlIlHelpers.Avalonia.Dialogs.AboutAvaloniaDialog,Avalonia.Dialogs.Version!Getter(object)' will always throw because: Invalid IL or CLR metadata
```

**Comment by colejohnson66** [comment]
Is this a XamlX bug then?
