### ISSUE TITLE
different control sizes when compiled with native aot

### ISSUE THREAD

**Issue by ivanjx** [AvaloniaUI/Avalonia#9453]
**Describe the bug**
some controls shows a bit differently in terms of sizes with native aot enabled.

**To Reproduce**

1. run the repro and observe the controls look.
2. publish as native aot with `dotnet publish -r win-x64 -c Release`
3. run the exe inside `publish` folder and observe the differences

**Expected behavior**
the controls looks exactly the same

**Desktop (please complete the following information):**

- OS: Windows
- Version 10

**Additional context**
[avalonfont.zip](https://github.com/AvaloniaUI/Avalonia/files/10023098/avalonfont.zip)

**Comment by TheXamlGuy** [comment]
I reckon we need a side by side screenshot showing the differences, if possible.

**Comment by ivanjx** [comment]
normal:
![image](https://user-images.githubusercontent.com/12814796/202223631-ed6ad4a5-dc79-4b36-8878-3461d6c1b4f3.png)

aot:
![image](https://user-images.githubusercontent.com/12814796/202223699-2ad58e46-bed8-43a2-a954-5026cd210c8f.png)

**Comment by maxkatz6** [comment]
For reference https://github.com/AvaloniaUI/Avalonia/pull/9443
