### ISSUE TITLE
Random behavior with TransitioningContentControl

### ISSUE THREAD

**Issue by chris835** [AvaloniaUI/Avalonia#9463]
**Describe the bug**
Switching content with the TransitioningContentControl works randomly. Sometimes it works, sometimes there's nothing at all shown, and sometimes the content shows up with a delay.

**To Reproduce**
I've put a minimal reproducible example here: https://github.com/chris835/tcctest

**Expected behavior**
The control should properly switch to the new content when set.

**Desktop**
- OS: Windows
- Version: 0.10.18 and 11.0.0-preview4

**Comment by maxkatz6** [comment]
Should be fixed with https://github.com/AvaloniaUI/Avalonia/pull/9803

**Comment by danielmayost** [comment]
Tested
