### ISSUE TITLE
Window crashed

### ISSUE THREAD

**Issue by huangfuhao** [AvaloniaUI/Avalonia#9471]
windows11 platform
![新建 BMP 图像](https://user-images.githubusercontent.com/116789821/202833184-017bd5f7-9c39-41b7-a2df-19aaef591e2a.png)
   在 Avalonia.Win32.OpenGl.WglRestoreContext..ctor(IntPtr gc, IntPtr context, Object monitor, Boolean takeMonitor)
   在 Avalonia.Win32.OpenGl.WglGlPlatformSurface.RenderTarget.BeginDraw()
   在 Avalonia.Skia.GlRenderTarget.BeginRenderingSession()
   在 Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer)
   在 Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(IDrawingContextImpl& context)
   在 Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall)
   在 Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite)
   在 Avalonia.Rendering.DeferredRenderer.Paint(Rect rect)
   在 Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   在 Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   在 Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)

**Comment by timunie** [comment]
@huangfuhao please provide more info about the issue. Best would be to fill the issue template we provide. Also a simple sample showing the crash would be great. 

As for now, I have no idea what to do to reproduce your issue. 

🙏 Thx

**Comment by hez2010** [comment]
I'm seeing you are still using the DeferredRenderer so you are using Avalonia 0.10. 
Can you try upgrading to Avalonia 11 to see if this issue is still there?

**Comment by huangfuhao** [comment]
I am using Avalonia  0.10.18
It is crashed sometimes,  Avalonia applcation form idle to active on windows11 platform.
I just switch from a Application  to Avalonia application, it crashed sometimes.

AppBuilder
 .With(new Win32PlatformOptions
                {
                    UseWgl =true,
                    AllowEglInitialization =true,
                })

**Comment by hez2010** [comment]
Wgl can sometimes fail to create context. Can you set `UseWgl = false` and try again?

**Comment by huangfuhao** [comment]
It works well if I set UseWgl = false

**Comment by maxkatz6** [comment]
In master it shouldn't crash, but restart rendering.
But in either way, UseWgl isn't needed anymore, as OpenGL control works without it now.
