### ISSUE TITLE
NET7 - InitializeComponent method can't be resolved

### ISSUE THREAD

**Issue by WizMe-M** [AvaloniaUI/Avalonia#9482]
**Describe the bug**
I have updated my app from `net6.0` to `net7.0`. After that, method `InitializeComponent()` became unresolvable.
However compiler build my app and Avalonia application runs how it should be.

**To Reproduce**
1. Change in .csproj `TargetFramework` property to `net7.0` (example below)
2. Create new Window in project
3. Edit code in window's code-behind (example below)
4. See error on `InitializeComponent()`
5. Run app
6. See this code works and window was initialized (screenshot below)
7. Look project dependencies
8. See no Source Generators

Csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="Roots.xml"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.0.0-preview4"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.0.0-preview4"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.0-preview4"/>
        <PackageReference Include="XamlNameReferenceGenerator" Version="1.3.4"/>
    </ItemGroup>
</Project>
```

Window:
```
using Avalonia.Controls;

namespace Sample;

public partial class SampleWindow : Window
{
    public SampleWindow()
    {
        InitializeComponent(); // Cannot resolve symbol 'InitializeComponent'
    }
}
```

**Expected behavior**
- Method `InitializeComponent` resolved. 
- Project has Source Generators (Avalonia.NameGenerator.AvaloniaNameSourceGenerator) 
- Method was generated in corresponding Window.g.cs

**Screenshots**
Unresolvable method (NET7):
![image](https://user-images.githubusercontent.com/64501652/202894506-6279a69e-7cea-46e8-812f-1b22a0fca392.png)

Running app (NET7):
![image](https://user-images.githubusercontent.com/64501652/202894471-c7053ae5-5094-4e07-a8f1-dc65b046e48a.png)

Expected g.cs (NET6):
![image](https://user-images.githubusercontent.com/64501652/202895051-e030f72a-2844-409e-a405-5ee2b8fc7265.png)

Expected Dependencies (NET6):
![image](https://user-images.githubusercontent.com/64501652/202895090-7e8ce076-9bc2-409e-a581-939f60d4097e.png)

Actual Dependencies (NET7):
![image](https://user-images.githubusercontent.com/64501652/202895112-6bc6ba2f-5da1-48f0-bc17-71bf4b9fff2b.png)

**Desktop:**
- OS: Windows 10 Pro 22h2
- Avalonia versions: 0.10.18 and _11.0.0-preview4_
- IDE: Rider 2022.2.4
- Plugin: AvaloniaRider 1.0.0.2140933520

**Comment by kekekeks** [comment]
If your app compiles, it's a Rider bug.
