### ISSUE TITLE
Android textbox bug.

### ISSUE THREAD

**Issue by CeSun** [AvaloniaUI/Avalonia#9486]
**Describe the bug**
When entering text into the Textbox (only numbers will trigger), the third character and subsequent characters will be inserted into the Textbox from the second position

**To Reproduce**
ditto

**Expected behavior**
ditto

**Screenshots**
Video can reflect

**Android(please complete the following information):**

- OS: Android 
- Version 13

**Comment by CeSun** [comment]
![Screenshot_2022-11-21-00-46-08-82_1ce19a26cb0bd9a1fa272bb91976022b.jpg](https://user-images.githubusercontent.com/54771283/202914630-10d685d1-f1af-422c-ba22-fad6d59e837e.jpg)
Continuous input 1 to 9.

**Comment by Gillibald** [comment]
#9486 duplicate
