### ISSUE TITLE
Long Crossfade Duration breaks RoutedViewHost

### ISSUE THREAD

**Issue by DmitriyYukhanov** [AvaloniaUI/Avalonia#9513]
**Describe the bug**
When setting CrossFade Duration to 1, the animation breaks and doesn't play, breaking the app.
But it works fine if Duration set to 0.9.

**To Reproduce**

1. Build and run the attached project:
[BugDuration.zip](https://github.com/AvaloniaUI/Avalonia/files/10066231/BugDuration.zip)

2. See no animation happens.
3. Open MainWindow.axaml and change <CrossFade Duration="1" /> to <CrossFade Duration="0.9" /> at line 35.
4. Build and run app again.
5. See animation plays now.

**Expected behavior**
I expect animation to work fine with any Duration, be it 0.5 seconds or 10 minutes.

**Screenshots**
See bug repro at the following video:
https://user-images.githubusercontent.com/883587/203285771-e8bca7d3-bb25-4458-b4b3-c7af33c59f20.mp4

**Desktop (please complete the following information):**

- OS: Win 11 22H2
- Version 11.0.0-preview.4

**Comment by maxkatz6** [comment]
I believe it should be fixed on master after ContentControl fixes last month.
Let me know if it isn't.
