### ISSUE TITLE
Some items disappear when animating RoutedViewHost navigation

### ISSUE THREAD

**Issue by DmitriyYukhanov** [AvaloniaUI/Avalonia#9514]
**Describe the bug**
I've noticed some items in View suddenly disappear when RoutedViewHost switching the page.

**To Reproduce**

1. Build and run attached project:
[BugRoutedViewHost.zip](https://github.com/AvaloniaUI/Avalonia/files/10066796/BugRoutedViewHost.zip)
2. After app starts, see "Some Caption" TextBlock and TabControl below are removed from page while it fades and switched to the Second page.
3. See all items from second page disappear too when it fades and navigates back to the Main page.
4. I'm not changing anything on page myself, it just executes the following method:

```
    private async void ReproduceBug()
    {
        await Task.Delay(3000);
        Router.Navigate.Execute(SecondPage);
        await Task.Delay(3000);
        Router.NavigateBack.Execute();
        await Task.Delay(3000);
        ReproduceBug();
    }
```

**Expected behavior**
I expect all items to fade evenly and page to not change its configuration while it's animating.

**Screenshots**
See the repro at the video:
https://user-images.githubusercontent.com/883587/203304501-b189afc9-42fa-4dc4-8dd7-143c5654bbdb.mp4

**Desktop (please complete the following information):**

- OS: Win 11 22H2 at 125% UI scale
- Version 11.0.0-preview.4

**Comment by DmitriyYukhanov** [comment]
Changing RoutedViewHost.PageTransition from CrossFade to PageSlide doesn't help.

**Comment by grokys** [comment]
Seems to be caused by #6111 - canceling the animation doesn't work. Looks like the cause might be that previously with the old value store the two animations ran concurrently, but with the new value store only a single binding is active per-property which breaks these transitions.

**Comment by DmitriyYukhanov** [comment]
I confirm this is fixed now in latest nightly version. Thank you!
