### ISSUE TITLE
Remove usages to BinaryFormatter

### ISSUE THREAD

**Issue by hez2010** [AvaloniaUI/Avalonia#9518]
**Describe the bug**
BinaryFormatter serialization is obsolete and should not be used. See https://aka.ms/binaryformatter for more information.

This obsoletion becomes an error in net7.0 and results in build failure. The usages to BinaryFormatter in Avalonia.Win32 should be removed. Maybe we can use [Cysharp/MemoryPack](https://github.com/Cysharp/MemoryPack) instead of BinaryFormatter?

**Comment by kekekeks** [comment]
Unfortunately it's required to access clipboard objects which are serialized via BinaryFormatter by existing WinForms and WPF apps.
