### ISSUE TITLE
Avalonia won't render if av_libglesv2.dll exists

### ISSUE THREAD

**Issue by hez2010** [AvaloniaUI/Avalonia#9519]
**Describe the bug**
Avalonia won't render if av_libglesv2.dll exists, and it yields a transparent window.

**To Reproduce**

1. Build CC.NetCore
2. Copy av_libglesv2.dll to the artifact directory
3. Run the built CC.NetCore

**Screenshots**

![image](https://user-images.githubusercontent.com/14960345/203346390-c1095962-f341-44ae-b811-f36be422e2dd.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version: master branch

**Comment by maxkatz6** [comment]
> Build CC.NetCore
> Copy av_libglesv2.dll to the artifact directory
> Run the built CC.NetCore

That's weird steps to reproduce. Does it work properly, if build with "win7-x64" runtime identifier?

Also, are there any exceptions thrown, if you enable catching all exceptions in the debugger?

**Comment by hez2010** [comment]
The issue only repros with avalonia.angle.windows.natives 2.1.18905.20220610.
If I copy the av_libglesv2.dll from 2.1.0.2020091801, the issue no longer repro.

**Comment by maxkatz6** [comment]
Ah, I see. It's not with currently used version, but with a newer one.
