### ISSUE TITLE
DataGrid does not refresh if source updated outside view

### ISSUE THREAD

**Issue by Gundz** [AvaloniaUI/Avalonia#9527]
**Describe the bug**
In Avalonia 0.11.0-Preview4 when updating (add or delete) the Items of a DataGrid when the view is not displayed (in another TabItem for example) the DataGrid doesn't get refreshed.

The issue doesn't happen in 0.18.0

**To Reproduce**

```
public class TestModel : ViewModelBase
{
    public string Name { get; }

    public TestModel( string name )
    {
        Name = name;
    }
}

public class MainWindowViewModel : ViewModelBase
{
    private ObservableCollection<TestModel> _items = new();
    public ObservableCollection<TestModel> Items
    {
        get => _items;
        set => this.RaiseAndSetIfChanged( ref _items, value );
    }

    public void Clear()
    {
        Items.Clear();
    }

    public void AddItems()
    {
        for ( int ii = 0; ii < 10; ii++ )
        {
            Items.Add( new TestModel( $"Item: {ii}" ) );
        }
    }
}
```

```
    <Window.DataTemplates>
        <DataTemplate DataType="vm:TestModel">
            <TextBlock Text="{Binding Name}" />
        </DataTemplate>
    </Window.DataTemplates>

    <DockPanel>
        <StackPanel DockPanel.Dock="Top" Orientation="Horizontal">
            <Button Command="{Binding Clear}" Content="Clear" />
            <Button Command="{Binding AddItems}" Content="Add Items" />
        </StackPanel>

        <TabControl>
            <TabItem Header="A">
                <Grid ColumnDefinitions="*,*">
                    <DataGrid Grid.Column="0" Items="{Binding Items}">
                        <DataGrid.Columns>
                            <DataGridTextColumn x:DataType="vm:TestModel" Header="Name" Binding="{Binding Name}" />
                        </DataGrid.Columns>
                    </DataGrid>

                    <ListBox Grid.Column="1" Items="{Binding Items}" />
                </Grid>
            </TabItem>

            <TabItem Header="B">
            </TabItem>
        </TabControl>
    </DockPanel>
```

1. Click the `Add Item` Button
2. Switch to Tab "B"
3. Click the `Clear` Button
4. Switch to Tab "A"
5. The Items in the DataGrid have not been cleared (the ListBox is here for reference).

Same issue when clicking `Add Items` in the "B" Tab, the added Items are not displayed in the DataGrid.

**Expected behavior**

The removed items should not be shown.

**Desktop:**

- Windows 10 Pro 22H2
- Tested with  Version 0.11.0-Preview1 and Version 0.11.0-Preview4.

**Comment by enisn** [comment]
After switching the tab, DataGrid even won't listen to PropertyChanged events anymore. 

I tried to invoke property changed event for ItemsSource property in viewmodel while activating but it doesn't affect. 
```csharp
 this.WhenActivated(delegate (CompositeDisposable _)
  {
      // I expected here re-draw rows here but nothing happens.
      this.RaisePropertyChanged(nameof(Items));
  });
```

**Comment by almightyju** [comment]
This is caused by this code in the DataGrid:
https://github.com/AvaloniaUI/Avalonia/blob/7580b704dff69b648b1fe73ebd7071b0c20bd4f0/src/Avalonia.Controls.DataGrid/DataGrid.cs#L2110-L2118

Simply not unwiring events seems to work but I don't know what the resolution should be while keeping the intended behaviour. 

Looking at the commit https://github.com/AvaloniaUI/Avalonia/commit/bbf3099a8f9f482f851f6cfe497f22c8ca95bbcf indicates the problem was a ViewModel/Collection keeping the DataGrid from being garbage collected, but that strikes me as an intended thing, if the ViewModel isn't being released then why would you expect the view for it to be released.

**Comment by enisn** [comment]
Any update on this?

**Comment by timunie** [comment]
@enisn the issue has the help wanted label. So if you or anyone else want to file a PR to solve the issue, feel free to do. Also testing latest master again could be useful.

**Comment by alexandrehtrb** [comment]
I just faced this issue, here is my temporary solution: switch to the tab that shows the DataGrid, update its ItemsSource, then switch back to the tab that was visible before.

**Comment by liugangnhm** [comment]
any update?

**Comment by liugangnhm** [comment]
> I just faced this issue, here is my temporary solution: switch to the tab that shows the DataGrid, update its ItemsSource, then switch back to the tab that was visible before. This makes the DataGrid view to be updated.

this solve my issue, just use a index bindind

```
                    CurrentTabIndex = 1;
                    UpdateDatasource
                    CurrentTabIndex = 0;
```

**Comment by almightyju** [comment]
I just tested this on master and I can't seem to reproduce it so I'm inclined to say it's fixed. Has anyone tried rc-1.1?

**Comment by liugangnhm** [comment]
> I just tested this on master and I can't seem to reproduce it so I'm inclined to say it's fixed. Has anyone tried rc-1.1?

nothing changed at all, try the below demo
[AvaloniaDataGridTest.zip](https://github.com/AvaloniaUI/Avalonia/files/11933212/AvaloniaDataGridTest.zip)
