### ISSUE TITLE
`AvaloniaXamlReportImportance` does not seem to be respected

### ISSUE THREAD

**Issue by alexrp** [AvaloniaUI/Avalonia#9535]
**Describe the bug**
The `AvaloniaXamlReportImportance` MSBuild property does not seem to actually be respected. Its default value, `low`, should in fact disable informational messages in a normal `dotnet build` (w/o `-v:n`), yet `GenerateAvaloniaResourcesTask` still outputs such messages:

```
$ dotnet build
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  GenerateAvaloniaResourcesTask -> Root: C:\Users\alex\source\repos\test, 0 resources, Output:obj\Debug\/Avalonia/resources
  test -> C:\Users\alex\source\repos\test\bin\Debug\test.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.53
```

**To Reproduce**
`dotnet build` in an Avalonia project.

**Expected behavior**
No informational messages from `GenerateAvaloniaResourcesTask`.

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10.0.25236.1010

**Comment by maxkatz6** [comment]
Was previously fixed https://github.com/AvaloniaUI/Avalonia/issues/8971
