### ISSUE TITLE
`GenerateAvaloniaResourcesTask` runs transitively on projects that reference an Avalonia project

### ISSUE THREAD

**Issue by alexrp** [AvaloniaUI/Avalonia#9539]
**Describe the bug**

`GenerateAvaloniaResourcesTask` and various other Avalonia tasks/targets will transitively run in projects that reference an Avalonia-based project. This is wasteful and unnecessary if the referencing project doesn't itself use Avalonia.

(This happens because Avalonia puts its MSBuild files in `buildTransitive`.)

**To Reproduce**

1. Create a library project A that uses Avalonia.
2. Create an executable project B that references project A.
3. Run `dotnet build` in project B.
4. Observe that `GenerateAvaloniaResourcesTask` runs for both projects.

**Expected behavior**

Avalonia's tasks/targets should not run in project B as it doesn't directly reference/use Avalonia.

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10.0.25247.1000

**Comment by kekekeks** [comment]
That behavior was introduced due to lots of complaints about our task _not_ running when package was added transitively. I guess we can't make everyone happy.

**Comment by kekekeks** [comment]
I suppose we could add a check that skips our targets if there are no `AvaloniaResource`/`AvaloniaXaml` project entries.

**Comment by alexrp** [comment]
> That behavior was introduced due to lots of complaints about our task _not_ running when package was added transitively. I guess we can't make everyone happy.

Heh, that's fair. 🙂

I would argue it's bad build hygiene, and people who need the build logic should reference the `Avalonia` package accordingly.

> I suppose we could add a check that skips our targets if there are no AvaloniaResource/AvaloniaXaml project entries.

That might be a reasonable compromise. That said, worth noting that stuff like this is still going to creep into referencing projects:

https://github.com/AvaloniaUI/Avalonia/blob/ee487bf4cfea4eab36949cc220bdbc935e5d9540/packages/Avalonia/AvaloniaBuildTasks.props#L2-L6
