### ISSUE TITLE
Invalid ToolTip Size

### ISSUE THREAD

**Issue by affederaffe** [AvaloniaUI/Avalonia#9548]
**Describe the bug**
The size of ToolTips seem to be measured incorrectly as its always (0, 0), causing them to not show.
On X11, it displays a black square (fallback size), on the experimental Wayland backend it crashes due to the invalid size.

**To Reproduce**

1. Go to the ToolTips page in the ControlCatalog
2. Hover over one of the boxes

**Expected behavior**
The ToolTip should be shown

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version: git master

**Comment by grokys** [comment]
Looks like this might be happening on other OSs too? https://github.com/AvaloniaUI/Avalonia/issues/9561

**Comment by ShadowMarker789** [comment]
> Looks like this might be happening on other OSs too? #9561. Should we close this issue and track it there as that one indicates it's not platform specific?

Can you confirm no tooltip was shown at all on your platform?
