### ISSUE TITLE
System.Reactive reference pulls in all of WPF/SWF when TFM is `net7.0-windows10.0.19041.0` or higher

### ISSUE THREAD

**Issue by alexrp** [AvaloniaUI/Avalonia#9549]
Consider this empty console app project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Direct2D1" Version="11.0.0-preview4" />
  </ItemGroup>
</Project>
```

If you do `dotnet build` and take a peek in `bin/Debug/net7.0-windows10.0.19041.0/win10-x64`, you'll notice something curious:

```
-rwxr-xr-x 1 alex 197609  8616056 Oct 19 16:40 PresentationCore.dll
-rwxr-xr-x 1 alex 197609    39088 Oct 19 16:40 PresentationFramework-SystemCore.dll
-rwxr-xr-x 1 alex 197609    34952 Oct 19 16:40 PresentationFramework-SystemData.dll
-rwxr-xr-x 1 alex 197609    34976 Oct 19 16:40 PresentationFramework-SystemDrawing.dll
-rwxr-xr-x 1 alex 197609    34960 Oct 19 16:40 PresentationFramework-SystemXml.dll
-rwxr-xr-x 1 alex 197609    30848 Oct 19 16:40 PresentationFramework-SystemXmlLinq.dll
-rwxr-xr-x 1 alex 197609   456864 Oct 19 16:40 PresentationFramework.Aero.dll
-rwxr-xr-x 1 alex 197609   460936 Oct 19 16:40 PresentationFramework.Aero2.dll
-rwxr-xr-x 1 alex 197609   239776 Oct 19 16:40 PresentationFramework.AeroLite.dll
-rwxr-xr-x 1 alex 197609   272544 Oct 19 16:40 PresentationFramework.Classic.dll
-rwxr-xr-x 1 alex 197609   682120 Oct 19 16:40 PresentationFramework.Luna.dll
-rwxr-xr-x 1 alex 197609   338080 Oct 19 16:40 PresentationFramework.Royale.dll
-rwxr-xr-x 1 alex 197609 16226464 Oct 19 16:40 PresentationFramework.dll
-rwxr-xr-x 1 alex 197609  1234088 Oct  7 05:04 PresentationNative_cor3.dll
-rwxr-xr-x 1 alex 197609  1288352 Oct 19 16:40 PresentationUI.dll
-rwxr-xr-x 1 alex 197609  1628288 Oct 19 16:40 ReachFramework.dll
... snip ...
-rwxr-xr-x 1 alex 197609    16512 Oct 19 03:24 System.Windows.Forms.Design.Editors.dll
-rwxr-xr-x 1 alex 197609  5335168 Oct 19 16:40 System.Windows.Forms.Design.dll
-rwxr-xr-x 1 alex 197609   960672 Oct 19 16:40 System.Windows.Forms.Primitives.dll
-rwxr-xr-x 1 alex 197609 13342848 Oct 19 16:40 System.Windows.Forms.dll
... snip ...
-rwxr-xr-x 1 alex 197609  1958000 Oct 19 06:34 wpfgfx_cor3.dll
```

Interestingly, changing TFM to `net7.0-windows10.0.18362.0` (or lower) does not pull in WPF/SWF. The same is of course true when changing TFM to simply `net7.0` or similar.

After some `project.assets.json` detective work, I figured out why:

https://github.com/dotnet/reactive/blob/85f1eb7c53e27cccdbeee3e0b044916168843fcc/Rx.NET/Source/src/System.Reactive/System.Reactive.csproj#L3-L21

As you can see, System.Reactive is multitargeted for `net5.0` **and** `net5.0-windows10.0.19041`, with the latter TFM pulling in all of WPF/SWF. 🤦

In an ideal world, the fix here would be for System.Reactive to not assume that a `windows` TFM necessarily implies `UseWPF=true` and `UseWindowsForms=true`. But judging by [this upstream issue](https://github.com/dotnet/reactive/issues/1461), it doesn't seem like anything is likely to change here anytime soon, despite this assumption being obviously wrong. I'm not sure what, if anything, can be done on the Avalonia side.

**Comment by maxkatz6** [comment]
Yes, that's a problem with the System.Reactive, and we can't do much about it, unfortunately. 

Developers can exclude some references from being copied to the output directory, something like `<Reference Exclude="PresentationFramework.dll" />`, but that isn't really user friendly. 

The best I can advice - make more noise in the System.Reactive repository, bringing up seriousness of this problem.

**Comment by maxkatz6** [comment]
Or we might actually try to remove this dependency at all. I will try and see this week. Hopefully, it won't affect any public API.

**Comment by maxkatz6** [comment]
Well, we use ISubject in the public API unfortunately. It should be considered when bindings API cleanup is done: https://github.com/AvaloniaUI/Avalonia/issues/9512.

**Comment by maxkatz6** [comment]
@idg10 it could work, yes. But as for now, there is very little need for `System.Reactive` in the framework itself. As we mostly have custom IObservable implementations, and only had to reimplement a small surface of observable extensions: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Reactive/Observable.cs.
Not to mention, [size improvements](https://github.com/AvaloniaUI/Avalonia/pull/9749#issuecomment-1362972278) we got by avoiding additional dependencies. I am afraid, we don't see reasons for us to add `System.Reactive` as a dependency back. Except maybe only for user code, or part of our templates.
