### ISSUE TITLE
Windows Build Server Failing to build

### ISSUE THREAD

**Issue by jcoder58** [AvaloniaUI/Avalonia#955]
The windows build server has failed with build errors for the past month.  And the few times is was successful, ControlCatalog.Desktop.exe crashes with no error.  The last successful build where Control Catalog worked for me was [1.2923](https://ci.appveyor.com/project/AvaloniaUI/Avalonia/build/0.1.2923).

**Comment by wieslawsoltes** [comment]
Regarding windows build server that's know issue with Xamarin https://bugzilla.xamarin.com/show_bug.cgi?id=54467. Should be fixed in 15.2 release of VS2017.

**Comment by grokys** [comment]
Hacked around for the moment by https://github.com/AvaloniaUI/Avalonia/commit/a8555ea240cb024d7ea9fde026790f45b7b6fa90
