### ISSUE TITLE
Simplify `ToggleButton` Events with One `IsCheckedChanged` Event 

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#9556]
**Is your feature request related to a problem? Please describe.**

`ToggleButton` currently uses the old standard of having separate events for `Checked`, `Unchecked` and `Indeterminate`. This is unnecessary and in new controls in WinUI there is now only one `IsCheckedChanged` event which indicates this property has changed to one of the three states. The IsChecked property can then be read in the event handler to get all information.

**Describe the solution you'd like**

It would be great for `ToggleButton` to have a single `IsCheckedChanged` replacing all others and matching what is done in `ToggleSplitButton`.

**Additional context**

This will break compatibility with older apps. I'm curious what others think about this change and if it should be done as non-breaking first (added alongside the older events which will be marked obsolete).

**Comment by timunie** [comment]
@robloo if we change it for `ToggleButton`, we should also change it for other checkable controls like `CheckBox, RadioButton, MenuItem, ...`. Otherwise I think the API is different for different controls which should be avoided imo.

**Comment by robloo** [comment]
@timunie True, but those get the change automatically since they derive from `ToggleButton`. It's good to note they are affected though I don't see a ToggleMenuItem in Avalonia.
