### ISSUE TITLE
Feature: Theme-awareness

### ISSUE THREAD

**Issue by hez2010** [AvaloniaUI/Avalonia#9560]
**Is your feature request related to a problem? Please describe.**
When the theme of system changed, an event will be propagated through the window event loop (at least on Windows). I would like to have an API that can subscribe to theme changes.

**Describe the solution you'd like**
```diff
  class Window
  {
+    public event EventHandler<string> SystemThemeChanged;
  }
```

**Implementation**
On Windows, an `WM_SETTINGCHANGE` will be posted to the event loop, we can check the `lparam` (which is a pointer to string) to determine whether it's a theme changed event. Other platforms (such as Android, iOS and macOS) should have similar things.

**Usage**
```xaml
<Window SystemThemeChanged="OnSystemThemeChanged" />
```

```csharp
private void OnSystemThemeChanged(object sender, string theme)
{
    Console.WriteLine($"System theme has been changed to {theme}");
}
```

**Comment by robloo** [comment]
This should really be integrated with https://github.com/AvaloniaUI/Avalonia/pull/8166.

Ideally, the application itself has a theme variant property which is inherited down the tree. The application can also raise an `ActualThemeChanged` changed event along with the `SystemThemeChanged` event proposed above. In UWP each control also has an `ActualThemeChanged` event.
