### ISSUE TITLE
Combined with cefnet, after the focus leaves the program, it returns to the program page, and the input method switch fails in the input box. 

### ISSUE THREAD

**Issue by xionger3015** [AvaloniaUI/Avalonia#9564]
Sorry, my English is terrible；
Combined with cefnet, after the focus leaves the program, it returns to the program page, and the input method switch fails in the input box. 
结合cefnet ，第1步焦点进入页面输入框，可以切换输入法，能输入中文，第2步焦点离开页面或者该程序后，第3步再返回页面里，在输入框中输入法切换失败，不能输入中文了。
Look at the code first；
![1669714108903](https://user-images.githubusercontent.com/119378518/204492590-173e0e13-902b-4c95-9bfd-1ad62aa69bc4.jpg)
![1669714108886](https://user-images.githubusercontent.com/119378518/204492647-b42d843b-3016-42a0-bd65-3900f45d3010.jpg)

**Comment by lovexionger** [comment]
![image](https://user-images.githubusercontent.com/119378518/204682105-2633f0a9-be49-4d59-930a-94cab5b743b3.png)

**Comment by rabbitism** [comment]
Let me try to translate. 
Step 1: input in webview, IME works.
Step 2: focus on other controls or outside the window.
Step 3: focus back on this page, IME cannot switch between English and Chinese.

Can you share this project with us via Github repo? 
你能把项目上传到Github repo分享出来吗？

**Comment by rabbitism** [comment]
I'm not sure if this is an issue with Avalonia 0.10.x, as IME was not working well on those versions. I tried to upgrade to V11 but build failed as CefNet is not compatible with Avalonia preivew yet.

**Comment by lovexionger** [comment]
@rabbitism 
Sorry, Thank you for waiting. I finally uploaded it.
https://github.com/lovexionger/xiongavatest.git
