### ISSUE TITLE
Improve exception message for missing XAML resource

### ISSUE THREAD

**Issue by mgnslndh** [AvaloniaUI/Avalonia#9594]
**Describe the bug**

I included a style resource but accidentally used the wrong file extension `.xaml` instead of the, in my case, correct `.axaml`:

```
<Application.Styles>
      <StyleInclude Source="avares://Assembly/Themes/Theme.xaml" />
</Application.Styles>
```

When running this app you will get an exception with a message similar to this:
 
```
'No precompiled XAML found for avares://Assembly/Themes/Theme.xaml (baseUri: avares://AppAssembly/App.axaml), make sure to specify x:Class and include your XAML file as AvaloniaResource'
```
This was a bit missleading to me because when I troubleshooted the problem I focused on the `x:Class` and `AvaloniaResource` part of the message. I did not even notice the wrong extension.

My file had "Avalonia XAML" as "Build Action" and did not have (does not need?) a `x:Class` attribute. The only problem was that I used `.xaml` instead of `.axaml`.
 
**To Reproduce**

1. Create simple Avalonia app project
2. Create Avalonia class library with a Styles resource (Build Action: Avalonia XAML) with `.axaml` extension
3. Include style resource in app using the `.xaml` extension
4. Run app
5. Exception thrown

**Expected behavior**

I would like a better exception message so that it is easier to figure out that you made a simple error of using the wrong file extension. 

If the resource could not be found it might be useful if the AvaloniaXamlLoader would check if the resource exists but with the other file extension and in that case throw with a appropriate message ("No precompiled XAML found for `resource.xaml` Make sure to use the correct file extension because there is resource with the same name ending in `.axaml`")

Or possibly just change the message to:

```
'No precompiled XAML found for avares://Assembly/Themes/Theme.xaml (baseUri: avares://AppAssembly/App.axaml), make sure to verify the resource URI is correct, specify x:Class and include your XAML file as AvaloniaResource'
```

**Screenshots**

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs#L35-L78

**Desktop**

- OS: Windows
- Version 11.0.0-preview4

**Comment by maxkatz6** [comment]
In the current master runtime loader is not used, and instead compiler directly injects correct calls into the IL. 

So, there is another error would be shown in this case
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/GroupTransformers/XamlIncludeGroupTransformer.cs#L119

**Comment by maxkatz6** [comment]
Linking with https://github.com/AvaloniaUI/Avalonia/issues/4466

**Comment by mgnslndh** [comment]
In that case the new exception message is much more clear. 

It might be overkill then to have the loader diagnose the problem and trying to find a resource with the same name but different extension (axaml/xaml) and having a different message in case there is a chance that the wrong extension was used. 

I mean it would be _nice_ if Avalonia told me I probably used the wrong file extension but not necessary and maybe it is trying to be too clever. On the other hand it might be a common misstake since many developers are used to the .xaml extension.
