### ISSUE TITLE
`DashStyle.Dashes` is null by default

### ISSUE THREAD

**Issue by tomenscape** [AvaloniaUI/Avalonia#9595]
**Describe the bug**
Following the changes made in #8895, `DashStyle.Dashes` is null by default. Each instance of the type should assign its own empty collection as a default value, or the property should be marked as nullable.

**To Reproduce**
```C#
var dashStyle = new DashStyle();
dashStyle.Dashes.Add(0.5); // NullReferenceException
```

**Expected behavior**
The default value should be an empty collection, or the property should be marked as nullable.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version (git master)

**Comment by maxkatz6** [comment]
Seems like it is an expected breaking change.

> or the property should be marked as nullable.

This should be done. Yes.
