### ISSUE TITLE
Dev tools throw when tree contains elements that don't inherit from Control

### ISSUE THREAD

**Issue by aelij** [AvaloniaUI/Avalonia#960]
Reason: `VisualTreeNode` downcasts `IVisual` to `Control`

**Comment by grokys** [comment]
Yes, we should handle this case, however I'm interested to know what your use-case is for elements that don't inherit from `Control`? I didn't really envision people inheriting from classes below `Control`; they're  separate classes mainly for encapsulation.

**Comment by aelij** [comment]
When porting AvalonEdit, there was a control that inherited from Visual, since all it had to do is render. It didn't need measure, arrange, tooltips, etc. Even in WPF it was definitely possible to have non-FEs in the visual tree. Since these classes are not abstract, it make sense to support them.

**Comment by grokys** [comment]
Fixed by #969
