### ISSUE TITLE
ProgressBar Fill Issue w/ Padding & Border

### ISSUE THREAD

**Issue by Sigrec** [AvaloniaUI/Avalonia#9602]
**Describe the bug**
![image](https://user-images.githubusercontent.com/53946709/205397762-1eec364e-94cc-4cc6-b9a5-632e807f93ee.png)

**To Reproduce**
Create progress bar with its Value = Maximum and set the padding and borderhickness

**Expected behavior**
![image](https://user-images.githubusercontent.com/53946709/205397954-17b3707f-c09c-430f-878e-50c04459fa62.png)

**Desktop (please complete the following information):**

- OS: [Windows 11]
- Version [11.0.0-preview4]

**Additional context**

**Comment by comesx4** [comment]
#9371 fixed it, but not merged yet.
