### ISSUE TITLE
[Perf] Avoid Cast in SceneBuilder.PropagateLayer

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#9604]
In follow lines
https://github.com/AvaloniaUI/Avalonia/blob/bbd2cfaed4ad0516776c5c66efc5639abf7b4256/src/Avalonia.Base/Rendering/SceneGraph/SceneBuilder.cs#L447-L454

`node.Children` is `IReadOnlyList<IVisualNode>`, when foreach run, every item of Children  is cast to VisualNode for retrieve the LayerRoot

**Comment by kekekeks** [comment]
Note that SceneGraph/SceneBuilder will be removed before 11.0 release
