### ISSUE TITLE
WeakEventManager design issues

### ISSUE THREAD

**Issue by aelij** [AvaloniaUI/Avalonia#961]
The `WeakEventManager` is designed to work as a singleton. However, multiple events can have the same signature (`<TEventSource, TEventHandler, TEventArgs>`). Without distinguishing the instances using the event name, multiple different events could wind up being registered to the same instance.

Additionally, it's impossible to inherit from this class an use the `StartListening` and `StopListening` overrides to automatically register to the source event (rather than using the `DeliverEvent` method directly in every invocation).

I've used a slightly different design [here](https://github.com/aelij/AvaloniaEdit/blob/master/src/AvaloniaEdit/Utils/WeakEventManagerBase.cs). The class itself is no longer a singleton. Instead, for each event, a derived class should be created. I've also modified the signatures of the `DeliverEvent` method so automatic registration would be simple. For example:

```csharp
public sealed class UpdateStarted : WeakEventManagerBase<UpdateStarted, TextDocument, EventHandler, EventArgs>
{
    protected override void StartListening(TextDocument source) => source.UpdateStarted += DeliverEvent;

    protected override void StopListening(TextDocument source) => source.UpdateStarted -= DeliverEvent;
}
```

**Comment by grokys** [comment]
cc @kekekeks

**Comment by kekekeks** [comment]
@aelij @grokys Do we even have `WeakEventManager`? 
[WeakSubscriptionManager](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Utilities/WeakSubscriptionManager.cs) asks for a name of the event and uses it as a key.

**Comment by aelij** [comment]
Yes, in `Avalonia.ReactiveUI`

**Comment by kekekeks** [comment]
Well, it's not a part of Avalonia, we just ship a compatible build of ReactiveUI.

**Comment by grokys** [comment]
Ah, that's not ours - that's part of ReactiveUI. Use the one that @kekekeks linked instead, that one's ours.

**Comment by aelij** [comment]
Oh, now I see it's a submodule :) Alright, I'll open an issue there.
