### ISSUE TITLE
Make "Duplicate setter" error show at design/preview time

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#9612]
**Is your feature request related to a problem? Please describe.**

With the recent changes for styling, an exception is now thrown if duplicate setters are placed in the same Style/ControlTheme block:
```Xaml
<!-- This was previously swallowed, now throws a runtime exception -->
<Style Selector="Control">
    <Setter Property="Height" Value="20" />
    <Setter Property="Height" Value="32" />
</Style>
```

The problem is this exception is thrown only at runtime, which is really inconvenient, and it really should be caught in the designer when the Xaml is parsed. 

As a side note, +1 for the error message with this though. Including the full Selector (including where nested) was really helpful to find out where I was mistakenly doing this.

**Comment by maxkatz6** [comment]
Ideally, we need warnings support in the XAML compiler. Which later can be configured by the developer as errors if they will.
But before that, it shouldn't be too hard to add a transformer with validation in the compiler.
