### ISSUE TITLE
ViewModelViewHost, RoutedViewHost transitions are broken

### ISSUE THREAD

**Issue by deryaza** [AvaloniaUI/Avalonia#9621]
**Describe the bug**
When using any of these controls, transitions became constantly fail to reach its final state.
For `CrossFade`, page is being partially or almost fully transparent.
For `PageSlide`, page is being bring in and out, so the view is not visible.

And it seems that TransitioningContentControl is not affected if you simply put it on a window, so it's probably has something to do with how reactiveUi controls triggers transition.

Just as a note, latest change in blame window shows some cancellation changes, but I believe it is not directly related, since it worked well around two months ago from now.

**To Reproduce**

reproduces very well if you use viewmodelviewhost

**Comment by deryaza** [comment]
It's probably related, but the main issue is kind of different 

![devenv_svglixS1qf](https://user-images.githubusercontent.com/46353085/205685997-2519b80a-565e-48a7-9005-70dab3bbe0c8.gif)

And I forgot to clarify that it reproduces on the latest commit, not from nugget packages

**Comment by timunie** [comment]
Related to https://github.com/AvaloniaUI/Avalonia/issues/9387 ?

**Comment by deryaza** [comment]
#9642 fixed this
