### ISSUE TITLE
Cannot type `Key.Space` into a `TextBox` inside a `SelectingItemsControl`

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#9623]
**Describe the bug**
[`SelectingItemsControl.OnKeyDown` handles certain `KeyEventArgs` events.](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Primitives/SelectingItemsControl.cs#L589)

The event being marked as handled causes `Avalonia.Win32.WindowImpl.AppWndProc` [to set its `_ignoreWmChar` field](https://github.com/AvaloniaUI/Avalonia/blob/5d785ca99ad8d24bece6ff3f2c3dc0fad367fcde/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs#L739) and not to raise an event when the WM_CHAR message is subsequently received, which finally causes `Avalonia.Input.KeyboardDevice.ProcessRawEvent` [not to create a `TextInputEventArgs` event](https://github.com/AvaloniaUI/Avalonia/blob/5d785ca99ad8d24bece6ff3f2c3dc0fad367fcde/src/Avalonia.Base/Input/KeyboardDevice.cs#L239).

The space key is thus never seen by `TextBox`, even though it has keyboard focus when the key is pressed.

**To Reproduce**
Create a window with this XAML:

```xaml
<ListBox>
    <TextBox/>
</ListBox>
```

Try typing into the text box. You will not be able to type a space character.

**Expected behavior**
Normal text input.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11preview4

**Comment by timunie** [comment]
I think we need to have a check if any input control has the key-board focus and, if that's the case, skip this function entirely.

**Comment by timunie** [comment]
@tomenscape I wonder if this PR https://github.com/AvaloniaUI/Avalonia/pull/9629 fixes your issue. Can you check your app with latest nightly build? 

/cc @emmauss

**Comment by tomenscape** [comment]
This fixes the bug. I can now type spaces. However, there are some weird behaviours:

- If I press Ctrl+Space then a space character is added _and_ I deselect the list item.
- If I press Space when the text box is focused but the list item is not selected, a space character is added _and_ I select the list item. (In addition to the Ctrl+Space method above, this state can be entered by navigating to the `TextBox` with the tab key.)

These are of course less serious issues than not being able to type space at all.

**Comment by timunie** [comment]
Thanks for the tests. So yes, I still think we should not handle selection if the control that has keyboard focus (or the original sender) is an input control.

**Comment by timunie** [comment]
@tomenscape as you seem to have the issue analyzed in more details, are you able to provide a PR for it?

**Comment by tomenscape** [comment]
I don't have a PR, I've just debugged how things work today. Changing text input events seems like a pretty big undertaking, and might break backwards compatibility too.

**Comment by timunie** [comment]
For 11.0 this may be a valid action. In that case it cannot be backported.

**Comment by grokys** [comment]
Can this be closed now that #11221 is merged?

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/11221 only affected TreeViewItem

**Comment by workgroupengineering** [comment]
Hi, I have a similar problem with the following xaml:

```xaml
    <ListBox ItemsSource="{Binding Models}"
            Grid.IsSharedSizeScope="True">
      <ListBox.DataTemplates>
        <DataTemplate DataType="l:Model">
          <Grid>
            <Grid.ColumnDefinitions>
              <ColumnDefinition Width="Auto" SharedSizeGroup="a"/>
              <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <TextBlock Text="{Binding Id}"/>
            <TextBox Text="{Binding Description}"/>
          </Grid>
        </DataTemplate>
      </ListBox.DataTemplates>
    </ListBox>  
```
Regression is introduced with pr #11455 when keyboard interaction is moved from `SelectingItemsControl` to `ListBox`
the fix for pr #9629 has been lost.

Regression is introduced with pr #11455 when keyboard interaction is moved from `SelectingItemsControl` to `ListBox`
the fix for pr #9629 has been lost.

Can I redo the fix of pr#9629 on the Listbox?

**Comment by timunie** [comment]
@workgroupengineering you are good to go. The PR will be accepted 👍 

Thanks for looking into it. 

🙏 Please add a unit test for this as we really need to make sure this will not happen again.

**Comment by maxkatz6** [comment]
Is it still reproducible in the latest builds?

**Comment by timunie** [comment]
I have just double-checked the repo shown in the issue description. Seems to work on my side, so closing this for now. @TomEdwardsEnscape ping me if it still happens to you, best with a sample to reproduce.
