### ISSUE TITLE
Avoid boxing/unboxing in AvaloniaObject Get/SetValue

### ISSUE THREAD

**Issue by aelij** [AvaloniaUI/Avalonia#963]
Since the entire property system is typed, I believe it should be possible to store typed values.

For example, we can have a type parameter in `PriorityValue<T>` and use a non-generic interface `IPropertyValue` in the dictionary. Then in the generic `GetValue` method, we could just cast and get the value.

**Comment by grokys** [comment]
Yes, it would be nice if we could avoid boxing in the property system. One thing to bear in mind though is that values will need to be boxed for markup anyway as XAML bindings etc aren't typed.

**Comment by aelij** [comment]
If you don't mind, I'll give it a shot. I don't believe it would complicate things at all.

**Comment by grokys** [comment]
Sure, give it a shot!

**Comment by grokys** [comment]
This was implemented in https://github.com/AvaloniaUI/Avalonia/pull/3255
