### ISSUE TITLE
AvaloniaProperty callback on AddOwner should dispatch only to new owner type

### ISSUE THREAD

**Issue by aelij** [AvaloniaUI/Avalonia#964]
For example:

```csharp
class X
{
   public static readonly AvaloniaProperty<int> P = AvaloniaProperty.Register<X, int>(...);
}

class Y : X
{
   static X()
   {
      P.Changed.Subscribe(...); // subscribe only to changes on Y (or derived);
   }
   public static readonly AvaloniaProperty<int> P = X.P.AddOwner<Y>();
}
```

**Comment by jkoritzinsky** [comment]
You should use `P.Changed.AddClassHandler<Y>` instead of `Subscribe` to only get the changes on `Y`.

**Comment by grokys** [comment]
Yes, what @jkoritzinsky said is true, however in your example, the `X.P.AddOwner<Y>` call is a no-op because if `Y` will inherit property `X` anyway.

**Comment by aelij** [comment]
@grokys @jkoritzinsky Thanks, that would solve my problem.

@grokys You're right, didn't mean an example with inheritance.
