### ISSUE TITLE
NativeMenuItemSeparator does not work in exported managed menu on Windows

### ISSUE THREAD

**Issue by xecrets** [AvaloniaUI/Avalonia#9643]
When using <NativeMenuItemSeparator /> and then <NativeMenuBar /> to place it in Windows, the horizontal line is not shown. Instead a greyed out menu item named "Avalonia.Controls.NativeMenuItemSeparator" is shown.

**To Reproduce**

1. Clone Avalonia repo from github on a Windows machine.
2. Checkout branch 'origin/releases/11.0.0.-preview4'
3. Build in Visual Studio 2022 17.4.1
4. Run 'ControlCatalog.NetCore'
5. Select the 'Menu' page sample
6. Expand the top leftmost item 'File'.

**Expected behavior**
I expected a horizontal line for the separator.

**Screenshots**
![image](https://user-images.githubusercontent.com/5602123/205973687-5f664919-f318-4867-acbe-a40a81a9d806.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0.0-preview4

**Comment by grokys** [comment]
Looking into this further, the code was broadly the same as the code in this PR before #8732 which removed this line as it was marked `[Obsolete]`.

https://github.com/AvaloniaUI/Avalonia/commit/00c08235cc698d1842693e2a1850d32319f6f3e3#diff-2ab349e1a3f8df96884580b65454a784da493eac9d69ac68ecc8d159a7555bf0L14

And the previous code was added by @kekekeks in this commit:

https://github.com/AvaloniaUI/Avalonia/commit/465273c883125861d0dcb692e3d12d8f8d70d34e#diff-3e3821b2fbb03908d076a3f3d10c710ce1af457ffa658badfb90c5f42f6f8e74R8

@kekekeks given that setting the header to `"-"` is a hack, and that removing it makes native menu separators break, what is the correct fix?

**Comment by maxkatz6** [comment]
@grokys we can revert change in this file. Or we can merge https://github.com/AvaloniaUI/Avalonia/pull/9655.
Either way it is a hack, and new PR being bigger one. But I think if we inherit separator from NativeMenuItem for now, it should be easily possible to remove ReflectionBinding from the templates as well.

Alternatively, we can change NativeMenuBar items generator to generate MenuItem/Separator with all the bindings from the code.

**Comment by grokys** [comment]
> But I think if we inherit separator from NativeMenuItem for now, it should be easily possible to remove ReflectionBinding from the templates as well.

That's what #9655 does, right? Probably we should merge that PR then as anything is better than the current broken state, and if it allows us to remove `ReflectionBinding`, even better.
