### ISSUE TITLE
AvaloniaProperty.Changed observer should be typed

### ISSUE THREAD

**Issue by aelij** [AvaloniaUI/Avalonia#965]
* Add `AvaloniaPropertyChangedEventArgs<T>`
* Also, it would be nice if it were possible to subscribe from the `AvaloniaProperty.Register` method instead of requiring a static ctor

**Comment by grokys** [comment]
I assume this will be needed by #963?

**Comment by aelij** [comment]
There's no hard dependency (can always box during the creation of the args), but it's preferable.

**Comment by maxkatz6** [comment]
Done with https://github.com/AvaloniaUI/Avalonia/pull/4648
