### ISSUE TITLE
Unable to resolve type SplitButton from namespace https://github.com/avaloniaui

### ISSUE THREAD

**Issue by NekoLemon** [AvaloniaUI/Avalonia#9656]
**Describe the bug**
When I am tring to add a split button to my program, it hints me that "Unable to resolve type SplitButton from namespace https://github.com/avaloniaui". As I've tried to use DataGrid and met the same problem, I try to add NuGet package Avalonia.Control.SplitButton, but there is no such a package.

**To Reproduce**
1. Open Visual Studio 2022.
2. Create an Avalonia MVVM Program.
3. Use \<SplitButton\> Control.
4. See error.

**Environment**
Windows 11 + Visual Studio 2022 + AvaloniaUI 0.10.18

**Comment by maxkatz6** [comment]
It's not available in 0.10.18.
This control was added in 11.0-preview versions.

**Comment by NekoLemon** [comment]
Allright, maybe this should be written in document.
