### ISSUE TITLE
`ExtendClientAreaToDecorationsHint` Creates a window with hard edges on Windows 11

### ISSUE THREAD

**Issue by StarlkYT** [AvaloniaUI/Avalonia#9660]
**Describe the bug**
Setting `ExtendClientAreaToDecorationsHint` to true shows a window with hard edges on Windows 11, unlike how it was on Avalonia 0.10 where it used to create a window with smooth edges.

**To Reproduce**

1. Create a cross-platform Avalonia project.
2. Go to the main class library project, and inside `Views/MainWindow.axaml`.
3. Add `ExtendClientAreaToDecorationsHint=True`.

**Expected behavior**
How it looks in Avalonia 11.0 (https://imgur.com/a/ZwZluhq), it is supposed to look like (https://imgur.com/gbQehdm).
Also the caption button's hover colour is weird, and you can not move the window at all.

**Desktop (please complete the following information):**

- OS: Windows 11 Pro
- Version 22H2

**Comment by nathanAjacobs** [comment]
I found more info on this, I tested with Avalonia 11.0 preview 4,

I included a runtime identifier like win-x64 in the csproj for example:

```.xml
<RuntimeIdentifier>win-x64</RuntimeIdentifier>
```

The window is then created with rounded corners, but now it also has the issue of the window background not keeping up with the window resize (same as issue #8316). Is this a regression or is this fix not included with 11.0 preview 4?
