### ISSUE TITLE
Direct3DInteropSample don't build

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#9666]
**Describe the bug**
Direct3DInteropSample don't build after 3e936052442205635cdc995cb074a75a8a003394
**To Reproduce**

1. Build Avalonia.sln
2. See error

**Expected behavior**
build

**Screenshots**

**Desktop (please complete the following information):**

- OS:  Windows
- Version any
**Additional context**

**Comment by kekekeks** [comment]
I think it should be removed since it doesn't work anymore and has never actually worked with Skia backend.
