### ISSUE TITLE
VectorEventArgs becomes internal in latest avalonia 11

### ISSUE THREAD

**Issue by squirrelfeng** [AvaloniaUI/Avalonia#9668]
Before I could use new VectorEventArgs  instance to create customer control event, like below. But now I cannot because it says VectorEventArgs is internal constructor. Is there an alternative solution? Thanks!

var arg = new VectorEventArgs
            {
                Handled = e.Handled,
                Route = e.Route,
                RoutedEvent = MovedFinishedEvent,
                Source = e.Source,
                Vector = e.Vector
            };

**Comment by robloo** [comment]
Discussed most recently here:

 * https://github.com/AvaloniaUI/Avalonia/pull/8860#issuecomment-1312819342
 * https://github.com/AvaloniaUI/Avalonia/pull/9534#issuecomment-1328052233

It's a bigger problem for control authors. @kekekeks @danwalmsley @grokys @maxkatz6

**Comment by timunie** [comment]
Looks like we will revert this change as the impact was underestimated. If you have a free minute feel free to send us a PR making VectorEventArgs public again. 

Have a nice Sunday

**Comment by hez2010** [comment]
Note that the missing constructors of various `EventArgs` also blocks the adoption from RyuJinx, see https://github.com/Ryujinx/Ryujinx/pull/3997

> Some controls are broken due to certain `EventArgs` initializers being made private (Embedded Window on Windows broken)

**Comment by maxkatz6** [comment]
It's public in latest master again.
