### ISSUE TITLE
DataGridCheckBoxColumn TwoWay binding only updates underlying property when focus is lost (11.0.0-preview4)

### ISSUE THREAD

**Issue by jhimes144** [AvaloniaUI/Avalonia#9676]
Consider the following axaml code...
`<DataGridCheckBoxColumn Header="Selection" Binding="{Binding Selected, Mode=TwoWay}"/>`
When the check box is checked the underlying property in the view model does not get set until the checkbox cell looses focus. This is different than how the normal `CheckBox` control works. It updates the underlying `IsChecked` property when the user changes the check state, this behavior is more desirable.

**To Reproduce**
1. Create a DataGrid with the aforementioned axaml code. 
2. Create an Items enumeration to bind to Items.
3. Create a view model for items, with Selected as a property that participates in change notifications. Thru `INotifyPropertyChanged`
4. Observe behavior

**Expected behavior**
Datagrid checkboxs behave as normal checkboxs do in terms of when the underlying property indicating check status is set.

- OS: Windows 10
- Version: 11.0.0-preview4

**Workaround**
Using a template column like so gives the desired behavior.
```
<DataGridTemplateColumn>
	<DataTemplate>
		<CheckBox IsChecked="{Binding Selected, Mode=TwoWay}"/>
	</DataTemplate>
</DataGridTemplateColumn>
```

**Comment by timunie** [comment]
I think it's the nature of `DataGrid` that the binding will only be updated after the cell has left the editing mode. In cases wehre this is not intended I personally use a `DataGridTemplateColumn` where I place a `CheckBox` into the `CellTemplate`. You may need to adjust the `Style` for the `CheckBox` a bit in order to look good in the data grid.

**Comment by jhimes144** [comment]
@timunie I think that is a sound argument. I'll close this ticket.
