### ISSUE TITLE
Inertia scrolling on mobile is clunky (11.0.0-preview4)

### ISSUE THREAD

**Issue by jhimes144** [AvaloniaUI/Avalonia#9687]
**The Problem**
Inertia scrolling on mobile feels very clunky, almost unusable. When scrolling through a long list, the scrolling often stops dead requiring the user to make another gesture to get it going again. In addition, scrolling with a `ListBox` is very clunky, as the `ListBox` is trying to fit items in the scroll, a behavior that in my opinion is desirable on desktop, but not on mobile.

**Desired Outcome**
A smoother scrolling experience on mobile.

**Additional context**
Disclaimer: I have not tested IOS yet.

**Version**
11.0.0-preview4

**Comment by grokys** [comment]
Should be partially fixed by #9677 which implements smooth scrolling by default for `ListBox`. I think our inertial scrolling still needs some work though, as even after that PR it still feels rather clunky.
