### ISSUE TITLE
Support odd number of values in `StrokeDashArray` (Skia)

### ISSUE THREAD

**Issue by DmitryZhelnin** [AvaloniaUI/Avalonia#9692]
**Is your feature request related to a problem? Please describe.**
`StrokeDashArray` property of `Shape` class has different requirements for Direct2D1 and Skia renderers.
In Skia it must have even number of elements. Direct2D1 supports any number.

**Describe the solution you'd like**
In case of odd number of elements we can pass doubled array of dashes to Skia library.
E.g.
`StrokeDashArray="1,4,2"`
becomes
`new float[] {1, 4, 2, 1, 4, 2}`

For even elements number no changes required.

I can create a PR if needed.

**Comment by grokys** [comment]
That would be good @DmitryZhelnin - the best solution would be to follow WPF and UWP's behavior, so if they allow an odd number of elements, we should too.
