### ISSUE TITLE
Closing window does not unregister window class and can lead to RWM atom table exhaustion

### ISSUE THREAD

**Issue by 0xDB6** [AvaloniaUI/Avalonia#9693]
**Describe the bug**
Whilst doing extensive memory leak tests for a long-running application, I noticed that my Avalonia app fails to create new windows after instantiating and immediately closing ~16k windows:

```
Failed after 15851 windows.
System.ComponentModel.Win32Exception (8): Not enough memory resources are available to process this command.
   at Avalonia.Win32.WindowImpl.CreateWindow() in /_/src/Windows/Avalonia.Win32/WindowImpl.cs:line 835
   at Avalonia.Win32.WindowImpl..ctor() in /_/src/Windows/Avalonia.Win32/WindowImpl.cs:line 175
   at Avalonia.Win32.Win32Platform.CreateWindow() in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 314
   at Avalonia.Controls.Window..ctor() in /_/src/Avalonia.Controls/Window.cs:line 221
   at AvaloniaMemLeakTest.Views.MainWindow..ctor() in ...\AvaloniaMemLeakTest\AvaloniaMemLeakTest\Views\MainWindow.axaml.cs:line 7
   at AvaloniaMemLeakTest.App.<>c__DisplayClass3_0.<OnFrameworkInitializationCompleted>b__1() in ...\AvaloniaMemLeakTest\AvaloniaMemLeakTest\App.axaml.cs:line 49
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 205
--- End of stack trace from previous location ---
   at AvaloniaMemLeakTest.App.<>c.<<OnFrameworkInitializationCompleted>b__3_0>d.MoveNext() in ...\AvaloniaMemLeakTest\AvaloniaMemLeakTest\App.axaml.cs:line 47
```

The error message that appears is rather misleading though, as it is not the system RAM that got exhausted, but instead the RWM atom table (verifiable using [JordiCorbilla's Atom table monitor](https://github.com/JordiCorbilla/atom-table-monitor): 

![image](https://user-images.githubusercontent.com/120456350/207303267-b3c4a6ff-06c4-4257-a00c-f96718cce1ab.png)
(Note: the drop after the first spike is me closing the process, confirming that the window class registrations are indeed cleaned up when the process exits.)

**During my investigation I have identified these key issues:**

UnregisterClassA() returns 0, i.e. did not succeed. This indicates that the window class my still be registered, as the atom table monitor confirms. This may be caused by the following:

1. The Unicode version of RegisterClassEx is used to register the randomly generated window class of the Avalonia window, wheras  unregistering uses the ANSI version. Mismatching encodings may lead to the class not being found by name, though I haven't verified that yet
2. UnregisterClassA() is called while DestroyWindow hasn't finished execution yet. I suspect this to be the culprit, as the window class cannot be unregistered as long as any window still uses it ([MSDN](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-unregisterclassa#remarks)).

![image](https://user-images.githubusercontent.com/120456350/207300332-f72d7010-fb3d-4658-b32f-1f3b7710c755.png)

**To Reproduce**

1. Create and close windows in a loop (Note: Although this rather extreme piece of code demonstrates the issue very quickly, it does also happen during 'normal' execution with sensible timings for opening and closing windows.)

Example code: 

``` csharp
public partial class App : Application
    {
        public override void Initialize()
        {
            AvaloniaXamlLoader.Load(this);
        }

        public override void OnFrameworkInitializationCompleted()
        {
            base.OnFrameworkInitializationCompleted();

            var t = Task.Run(async () =>
            {
                int count = 0;
                try
                {
                    while (true)
                    {
                        await Dispatcher.UIThread.InvokeAsync(() =>
                        {
                            Window win = new MainWindow();
                            win.Close();
                        });

                        count++;
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed after {count} windows.");
                    Console.WriteLine(ex.ToString());
                }
            });
        }
    }
```

**Expected behavior**
Windows can be created indefinitely without exhausting the RWM atom table. This is the behavior currently displayed by dotnet/wpf.

**Desktop (please complete the following information):**

- OS: Windows, all supported versions. (Confirmed on Windows 10 21H2, build 19044.2251 and Windows Server 2019, build 17763.3650)
- Version 0.10.18 through 11.0.0 preview 4

**Additional context**
Although this issue is rarely noticeable in most applications, it does affect long-running applications which open a lot of windows over time.
See also [Atom table leak after window running on a separate thread closes (Check the demo)](https://github.com/dotnet/wpf/issues/3971) over at dotnet/wpf for a similar, but different, issue.

**Comment by 0xDB6** [comment]
The problem is caused by `DestroyWindow()` sending `WM_DESTROY`, which gets handled by the `WndProc` while `DestroyWindow()` is still executing. The `WndProc` calls `Dispose()`, which eventually makes the call to `UnregisterClass()`, with `DestroyWindow()` still executing. This operation is invalid, which causes 'UnregisterClass()' to fail.

![image](https://user-images.githubusercontent.com/120456350/207542933-67592841-05df-444d-b23d-b97194b33bd0.png)

**Comment by kekekeks** [comment]
We probably need to reuse the same window class instead of registering a new one for each window.

**Comment by kekekeks** [comment]
Since aren't handling WM_CREATE anyway, we can just call `SetWindowLong`(`Ptr`) to replace GWL_WNDPROC.

**Comment by 0xDB6** [comment]
I'm preparing a pull request based on deferred execution of `UnregisterClass`, which would solve this issue. FWIW WPF registers a new window class for every window too. That's fine IMO if it gets cleaned up correctly.
