### ISSUE TITLE
ItemTemplate is not applied on Menu/MenuItem

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#9696]
**Describe the bug**
ItemTemplate defined for Menu/MenuItem is not applied to their submenus. 

**To Reproduce**
![image](https://user-images.githubusercontent.com/14807942/207319117-0e8e61e0-c102-4ac5-8e85-1dabf2f9c577.png)
Items is bound to a list of string in VM. In this case I would expect both menu item shows 123, but it still shows the original bound value.

**Expected behavior**
ItemTemplate should be applied to submenus as HeaderTemplate. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 11.0-preview4

**Additional context**
Copy from discussion #9684

**Comment by grokys** [comment]
I think this is something that I fixed in https://github.com/AvaloniaUI/Avalonia/pull/9677. I don't have time to check right now but if you have time to confirm if it's fixed or not that would be nice!

**Comment by rabbitism** [comment]
@grokys, Thaks for reply, I was about to try but I didn't find that particular build in avalonia feed. Maybe will try after it is merged.
