### ISSUE TITLE
[AngleWin32PlatformGraphics] code will never run

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#9701]
https://github.com/AvaloniaUI/Avalonia/blob/cd0020eb755b5867e1bf6d39d3472c857ece1c68/src/Windows/Avalonia.Win32/OpenGl/Angle/AngleWin32PlatformGraphics.cs#L92-L132

@kekekeks Can it be removed?

**Comment by kekekeks** [comment]
Whoops, the line before was supposed to be used only for debugging.
