### ISSUE TITLE
SaveFileDialog does not append file extension to file name

### ISSUE THREAD

**Issue by Mbucari** [AvaloniaUI/Avalonia#9704]
**Describe the bug**
When saving a file with `FilePickerSaveOptions` or `SaveFileDialog`, the dialog doesn't append the file extension to the user's selected file name.

**To Reproduce**
```C#
var saveFileDialog = new SaveFileDialog
{
	Title = "Where to export Library",
	Filters = new()
	{
		new() { Name = "Excel Workbook (*.xlsx)", Extensions = new() { "xlsx" } }
	}
};

var fileName = await saveFileDialog.ShowAsync(this);
//fileName has no file extension
```

**Expected behavior**
After the `FilePickerSaveOptions` and `SaveFileDialog` close, the user-selected file name should have the file extension of selected `FileTypeChoices`.

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.0-preview4

**Comment by maxkatz6** [comment]
Note, that a new API is used with 11.0 https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.Base/Platform/Storage
For instance, win32 implementation is here https://github.com/AvaloniaUI/Avalonia/blob/1f2aef4873c68c40e94bc85428efc5f7e59e2ac9/src/Windows/Avalonia.Win32/Win32StorageProvider.cs

SaveFileDialog is only redirecting calls to IStorageProvider 
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Platform/Dialogs/SystemDialogImpl.cs#L42

**Comment by maxkatz6** [comment]
I also not sure if SaveFileDialog.Filters should even add the extension to the file.
Instead, you should set DefaultExtension, if you want a default one.

**Comment by jp2masa** [comment]
I think there's something slightly wrong here. At least on Windows, each filter has a corresponding default extension, which is appended automatically if the specified file name doesn't have an extension. For example, saving a web page on Firefox has options for web page (.htm, .html) and text file (.txt, .text), and it appends the correct extension automatically (html in the first case and txt in the second, so it's not picking the first extension in the list I guess).

**Comment by Mbucari** [comment]
> Note, that a new API is used with 11.0

Yes, I tested with both the deprecated `SaveFileDialog` and the new `!StorageProvider.SaveFilePickerAsync()`.

> I also not sure if SaveFileDialog.Filters should even add the extension to the file.

Version 0.10.18 does add the file extension to the file name. If that feature has been removed, then we need some way to know what file type the user selected when saving the file so we may add the correct file extension ourselves. Currently there is no way for the caller to know which file type the user selected.

**Comment by Mbucari** [comment]
Here's an example using` StorageProvider`.
```C#
var options = new FilePickerSaveOptions
{
	Title = "Where to export Library",
	SuggestedStartLocation =  new Avalonia.Platform.Storage.FileIO.BclStorageFolder(Configuration.Instance.Books),
	ShowOverwritePrompt = true,
	FileTypeChoices = new FilePickerFileType[]
	{
		new("Excel Workbook (*.xlsx)") { Patterns = new[] { "xlsx" } },
		new("CSV files (*.csv)") { Patterns = new[] { "csv" } },
		new("JSON files (*.json)") { Patterns = new[] { "json" } },
		new("All files (*.*)") { Patterns = new[] { "*" } },
	}
};

var selectedFile= await StorageProvider.SaveFilePickerAsync(options);
```
If I save a file without manually typing the file extension, `selectedFile` will not have the file extension, and I have no idea which  `FilePickerFileType` the user selected.
