### ISSUE TITLE
TextBox FontSize property doesn't have any affect.

### ISSUE THREAD

**Issue by henrydunphy** [AvaloniaUI/Avalonia#9706]
When setting TextBox Fontsize property nothing happens. I have tried both through code and the xaml side with no effect. This appears to be a bug on most controls including buttons. Luckily for buttons I have a work around. The workaround for buttons doesn't work on TextBox I'm guessing because it doesn't have the same hierarchy.

Attempts:
XAML file
`<TextBox Name="UserInputTextBox" FontSize="35" />`

code behind (using reactive UI):
```
public partial class LoginView : ReactiveUserControl<LoginViewModel>
{
    private ListBox _userNameListBox => this.FindControl<ListBox>("UserNameListBox");
    private TextBox _userInputTextBox => this.FindControl<TextBox>("UserInputTextBox");


    public LoginView()
    {
        InitializeComponent();

        this.WhenActivated(disposables => {
            this.Bind(ViewModel, vm => vm.UserInput, v => v._userInputTextBox.Text).DisposeWith(disposables);
            this.OneWayBind(ViewModel, vm => vm.SubmitEnabled, v => v._userInputTextBox.IsEnabled).DisposeWith(disposables);

            _userInputTextBox.FontSize = 35;
        });
    }
}
```

Button workaround:
```
		<Style Selector=".LoginButton > TextBlock">
			<Setter Property="FontSize" Value="35" />
			<Setter Property="Foreground" Value="White" />
		</Style>
```

**Comment by maxkatz6** [comment]
Do you have a minimal project to reproduce? This issue is pretty weird and seems to not be a common one.

**Comment by henrydunphy** [comment]
Im not sure what you mean by minimal project. I can't share the whole project as it's proprietary. Do you mean it is not common because people aren't changing the FontSize? Or the fact that FontSize doesn't affect anything? I am using the [Material Avalonia ](https://github.com/AvaloniaCommunity/Material.Avalonia) package to get some basic UI styling, but I wouldn't think that overrides when I'm setting the FontSize attribute.

**Comment by Gillibald** [comment]
` <TextBox FontSize="44" Text="Hello World"/>`
![Screenshot 2023-01-26 161149](https://user-images.githubusercontent.com/5928797/214872581-0a2acf80-3eb5-44f6-b7f3-909ceb20d0f8.png)

Can't see any issues

**Comment by timunie** [comment]
In that case either create a minimal repo or ask the question in Material Avalonia. I'm pretty sure they probably have it set somewhere in styles.

https://github.com/AvaloniaCommunity/Material.Avalonia/blob/13d79e48689ca058a40ba30f06e7ef246ec7e763/Material.Styles/Button.xaml#L28

**Comment by henrydunphy** [comment]
I'll ask the question there but I can override the Button FontSize it's the TextBox Im struggling with. Any idea how I would override it here. It looks like its using the control's FontSize property, but as I said trying to set it doesn't do anything.
https://github.com/AvaloniaCommunity/Material.Avalonia/blob/13d79e48689ca058a40ba30f06e7ef246ec7e763/Material.Styles/TextBox.xaml
