### ISSUE TITLE
Improving pointer behavior in SelectingItemsControls

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/Avalonia#9707]
Currently, Avalonia's pointer behavior in SelectingItemsControls differs from other UI frameworks. In Avalonia, selecting an item (in a ComboBox/ListBox/TabControl/Menu) is all done on PointerPressed. In addition we also allow selection using the right mouse button. In other frameworks (all of Windows (Win32 and Xaml), Qt, gnome on linux for alternate OS comparison) invokes or selects with only the left mouse button and on pointer up. The only exception to this rule is top level menu items in a MenuBar (Windows HMENU or Qt menubar, for example) where the dropdown opens on pointer down. The menu items in the drop down though still invoke on pointer up.

We also don't clear the ":pressed" state if the pointer is pressed but dragged outside the bounds of the item.

Advantages to using only left button and pointer up:
- You can cancel an accidental pointer/mouse press - just drag the mouse outside the bounds of the item and release and the capture releases, but the item itself doesn't select/invoke
- Not handling right mouse means the item won't get selected if a ContextMenu/Flyout is opened on the item. (Add one to a ListBoxItem and you'll see the ListBoxItem get selected before the menu opens)
- The current behavior renders the `:pressed` pseudoclass less important since the pointer-triggered action has already happened, but the pressed visual state indicates you're about to do something to this item

I don't think this is too big of a change to actually implement. It will break the current behavior, but it will align it with other UI frameworks and what I think others would expect. Two things to consider with the change though: pointer up should only invoke/select the captured control (moving to another item and releasing should not select that item). And, `MenuItem` will need to adapt whether its toplevel or actually in a menu - this might be the more complicated bit?

With the other items control related changes going on, this might be a good time to adjust this - though it is of different scope to that PR.

**Comment by grokys** [comment]
Yep, there are various problem with out selection logic, mainly caused by the fact that selection follows focus, which is incorrect. I hope to address this some time soon, though if you want to help out let me know and I can discuss my (vague) plans with you ;)
