### ISSUE TITLE
Avalonia 11.0.0-preview4 program don't start with --drm argument

### ISSUE THREAD

**Issue by PetSerVas** [AvaloniaUI/Avalonia#9709]
**Describe the bug**
Avalonia 11.0.0-preview4 DRM project ported from
https://docs.avaloniaui.net/guides/deep-dives/running-on-raspbian-lite-via-drm
not working on **Orange Pi3 Lts** with **Debian Server 11** 
version 0.10.18 working fine
By default, it is not returned card0
![image](https://user-images.githubusercontent.com/3917519/207777350-bfa58953-c466-4c27-a362-ccfe22e68ac1.png)
Code fixed this problem: **builder.StartLinuxDrm(args, scaling: 1, card: "/dev/dri/card0")**

**To Reproduce**
Source code:
**drm10**  - Avalonia 0.10.18
**drm11**  - Avalonia 11.0.0-preview4
(https://github.com/PetSerVas/AvaloniaDrm)

**Expected behavior**
Program start

**Screenshots**
![image](https://user-images.githubusercontent.com/3917519/207623726-4f118b04-06cf-41d1-a938-3e3d9def6e2c.png)

**Desktop (please complete the following information):**

- OS: Debian GNU/Linux 11 (bullseye)
- Version: 11.5

**Comment by kekekeks** [comment]
Regression, introduced by https://github.com/AvaloniaUI/Avalonia/pull/7749

**Comment by kekekeks** [comment]
Duplicate #9178
