### ISSUE TITLE
Child element don't work for named elements in selectors

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#971]
`StackPanel#Name Button` doesn't get applied

**Comment by grokys** [comment]
I think this is an OmniXaml issue - the `Button` is getting added to the `StackPanel` before `StackPanel.Name` is set, so when styling is applied it looks like the `StackPanel` doesn't have a name. I need to try the test with Portable.Xaml to check what the behavior there is.

**Comment by jkoritzinsky** [comment]
@grokys Did you check if the behavior is different with Portable.Xaml?

**Comment by grokys** [comment]
This now works correctly.
