### ISSUE TITLE
Properties in styles don't get applied if specified for base control

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#973]
```
<Style Selector="Control.active">
  <Setter Property="Border.Background" Value="Red" />
</Style>
```

**Comment by grokys** [comment]
I think you need to use `:is(Control).active` here - the default `OfType` selector matches the _exact_ type.

**Comment by grokys** [comment]
Actually, thinking about this some more, I think we need to swap the behaviors - by default `TypeName` should apply to a class and derived classes because you may well want to derive from a class and use the same styles, so repoening this.

**Comment by jkoritzinsky** [comment]
@grokys Do you still want to change the behavior of the selectors here?

**Comment by grokys** [comment]
No, I don't think I do at this point, it would be too big a breaking change and I'm not even sure it makes sense.
