### ISSUE TITLE
Ubuntu22.04.1 display error

### ISSUE THREAD

**Issue by BonanzaBegin** [AvaloniaUI/Avalonia#9740]
myAvalonia app set 
Setter Property="SystemDecorations" Value="None"
it works well  on windows/Ubuntu20.04.3 ,
but it works badly on Ubuntu22.04.1  some areas become tansparent or black when i scroll the listbox how can i fix the problem?
here are the show pictures
![5f2f48e49c35e47ba85b8df75cc1151](https://user-images.githubusercontent.com/58451874/208329686-8daced33-bc40-4ab1-ba52-3427fdb26092.png)
![22622f57bdfb8739930141cdd12d963](https://user-images.githubusercontent.com/58451874/208329694-045915f7-d003-4c03-8612-464b7296669a.png)
![4c65fd9a79b1061a9fafadd02be309e](https://user-images.githubusercontent.com/58451874/208329699-822dbe4d-d153-43c5-8b23-59fd67ba0725.png)
![8ce5cf701fd0f54551d35e8b291eb57](https://user-images.githubusercontent.com/58451874/208329737-e840ba1c-7d8e-4651-9d59-6b66f05e839d.png)

**Comment by BonanzaBegin** [comment]
It seems when  thecontrol's background is set to Transparent, it will cause this problem,how can i fixed it?

**Comment by Quetzalcoatl2435** [comment]
Disable GPU rendering. It happens on all Linux distros I've tried with GPU rendering enabled.

`BuildAvaloniaApp().With(new X11PlatformOptions { UseGpu = false }).StartWithClassicDesktopLifetime(args);`
