### ISSUE TITLE
MultiBinding using TemplateBinding with built in Converters doesn't work

### ISSUE THREAD

**Issue by almightyju** [AvaloniaUI/Avalonia#9766]
**Describe the bug**
If using a MultiBinding with TemplateBindings and those template bindings have a converter the multi binding doesn't work

**To Reproduce**
Create the following custom control
```xaml
<TextBlock x:Name="DisplayText"
		   ...>
  <TextBlock.IsVisible>
	<MultiBinding Converter="{x:Static BoolConverters.And}">
	  <TemplateBinding Property="MyObjectProp" Converter="{x:Static ObjectConverters.IsNull}" />
	  <TemplateBinding Property="HideDisplayText" Converter="{x:Static BoolConverters.Not}" />
	</MultiBinding>
  </TextBlock.IsVisible>
</TextBlock>
```

Set MyObjectProp to new object(), set HideDisplayText to false and the control will still be visible when it shouldn't be

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.0-preview4

**Additional context**
This looks to be an issue because a TemplateBinding needs a target type in order to use a converter:
https://github.com/AvaloniaUI/Avalonia/blob/eb4e9ae565c9a0e426c3ab2f8d27958a2ca98d30/src/Markup/Avalonia.Markup/Data/TemplateBinding.cs#L141-L144

But a MultiBinding passes in null as the target property causing the target type to be null
https://github.com/AvaloniaUI/Avalonia/blob/eb4e9ae565c9a0e426c3ab2f8d27958a2ca98d30/src/Markup/Avalonia.Markup/Data/MultiBinding.cs#L86

Using a custom multi binding works, but it would be nice if the built in converters worked

**Comment by timunie** [comment]
I think im that case Binding with RelativeSource=TemplatedParent should work. TemplateBinding is a special one which should be really light weight, so it doesn't work in every case. 

If it's intended to work in your case I connet say.

**Comment by almightyju** [comment]
> I think im that case Binding with RelativeSource=TemplatedParent should work. TemplateBinding is a special one which should be really light weight, so it doesn't work in every case.

I just tried with 
```xaml
<MultiBinding Converter="{x:Static BoolConverters.And}">
    <Binding Path="MyObjectProp" RelativeSource="{RelativeSource TemplatedParent}" Converter="{x:Static ObjectConverters.IsNull}" />
    <Binding Path="!HideDisplayText" RelativeSource="{RelativeSource TemplatedParent}" />
</MultiBinding>
```
and it does indeed work, should have tried that. Much better workaround, thanks!
