### ISSUE TITLE
The designer window is keep loading forever.

### ISSUE THREAD

**Issue by mossbee** [AvaloniaUI/Avalonia#9775]
I just have installed Avalonia and created my first program. I follow the instruction on Avalonia's official dos: https://docs.avaloniaui.net/docs/getting-started
But the designer screen is keep showing "The designer is loading". I waited for hours, but it has not been loading yet.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/69780142/209431333-c3c5b0ee-d5f7-4846-989f-2193c34ea524.png">
But when I run the program, I can see the results, like this:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/69780142/209437729-f47fa8e9-0fb0-4fbd-b358-67367711e47f.png">

**Comment by timunie** [comment]
Have you installed the needed plugin? https://docs.avaloniaui.net/docs/getting-started/ide-support#avalonia-visual-studio-extension

**Comment by mossbee** [comment]
Yes I did, I got it here

**Comment by James-Morrell** [comment]
@mossbee have you tried restarting VS? Does it persist?

Also this should be in the VS Plugin Issues rather than in the avalonia issues?
[https://github.com/AvaloniaUI/AvaloniaVS/issues](https://github.com/AvaloniaUI/AvaloniaVS/issues)

**Comment by maxkatz6** [comment]
There are similar issues in the AvaloniaVS repository as it was pointer above.
Also, in some cases it is caused by errors in the project itself. You can check avalonia previewer logs in the Visual Studio (output window).
