### ISSUE TITLE
Codesign for MacOS

### ISSUE THREAD

**Issue by robinne** [AvaloniaUI/Avalonia#9780]
**Describe the bug**
Followed these instructions for deploying an .app application for MacOS https://docs.avaloniaui.net/docs/distribution-publishing/macos
Running into two issues. 1) there are 3 folders created in the myapp.app that cannot be code-signed.
myapp.app>Contents>MacOS>runtimes: "browser-wasm", "unix", and "win".
Deleting each folder will allow for code signing.

2) Cannot code sign and then run the myapp.app, unless I remove "--options=runtime" from codesign. 

codesign --force --timestamp **--options=runtime** --entitlements "$ENTITLEMENTS" --sign "$SIGNING_IDENTITY" "$fname"

When this option is present, the myapp.app no longer runs on local machine. Removing that option and code signing, allows myapp.app to run after being signed. The option is required in order to be notarized by apple, so removing it will not allow the app to be deployed.

**To Reproduce**

Create an Avalonia project for desktop.
Release the app using dotnet.bundle to create an ".app" file/program. as per instructions above.
Run the .app, it should open your program.
Codesign as per instructions above.
Fails to codesign.

bundle format unrecognized, invalid, or unsuitable
In subcomponent: /xxxx/SignedMacOS/MyApp.app/Contents/MacOS/runtimes/browser-wasm/nativeassets/net7.0

Remove the 3 folders mentioned above and codesign again.
Should succeed.
Run the .app program. Does not open.

**Expected behavior**
Codesign should sign the .app output from dotnet.bundle.
Program should open as expected.

**Screenshots**

**Desktop (please complete the following information):**

MacOS Monterey 12.6.1

**Additional context**

The program cannot run at all, not even enough to log information to a file.

**Comment by kekekeks** [comment]
> "browser-wasm", "unix", and "win".

If you have those directories, you aren't specifiying the runtime identifier during publishing.

**Comment by robinne** [comment]
I can't believe I did that. I had this in the project file and removed it from the command. Thank you so much, all works as expected!
