### ISSUE TITLE
Choose what to do with floating point types

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#9782]
The situation right now:

Layout, render transform and our `Matrix` (3x3) type are using `double`, because that's what WPF, UWP, Xamarin.Forms and MAUI are using
Our drawing backends (both Skia and Direct2D) are using `float` because that's what GPU is actually using for rendering
Our `CompositionVisual` and friends are using `float` and `System.Numerics` `float`-based types because that's what is used by Windows.UI.Composition and by rendering backends.

However `DrawingContext` and `IDrawingContextImpl` accept `double` values. So composition engine converts float to double only for that double to be converted back to float later.

So we probably want at least `IDrawingContextImpl` to use `float` based types. 

The main question here is: do we actually want to keep using `double`s everywhere else? Using `float` type saves memory and improves performance.

Do we even know _why_ they are used or are we just keeping them because there was no `MathF` class 15 years ago? 

Some background:
- CoreGraphics is using `double` as `CGFloat` when running on 64-bit CPUs
- Flutter is using `double` at least for layout too

**Comment by Mikolaytis** [comment]
I think that going full float and MathF is a huge benefit. 
Also using Vector2 from System.Numerics over existing Vector(double,double)  is a good idea because of intrinsics inside it.

**Comment by kekekeks** [comment]
Using `double` for transforms and offsets, 8000 pixels of good precision isn't enough.
