### ISSUE TITLE
OpenFileDialog Obsolete shows CS0618 wrning

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#9787]
**Describe the bug**

When I using OpenFileDialog and other system dialogs. Visual Studio shows: Use Window.StorageProvider API or TopLevel.StorageProvider API. Is there any alternative APIs to use?

**To Reproduce**

Create a new OpenFileDialog instance. Warning shows.

**Screenshots**

<img width="796" alt="image" src="https://user-images.githubusercontent.com/25716486/209484295-df24cafe-b7a7-4eff-8c51-e8bde188bfa3.png">

**Desktop (please complete the following information):**

- OS: Windows 11 22H2
- Version 11.0.0-preview4

**Comment by jp2masa** [comment]
The APIs you should use are those in the message: `Window.StorageProvider` or `TopLevel.StorageProvider`.

For example, instead of:

```cs
var fileDialog = new OpenFileDialog() { ... };
var result = await fileDialog.Show(window);
```

It should be:

```cs
var options = new FilePickerOpenOptions() { ... };
var result = await window.StorageProvider.OpenFilePickerAsync(options);
```

**Comment by laolarou726** [comment]
> The APIs you should use are those in the message: `Window.StorageProvider` or `TopLevel.StorageProvider`.
> 
> For example, instead of:
> 
> ```cs
> var fileDialog = new OpenFileDialog() { ... };
> var result = await fileDialog.Show(window);
> ```
> 
> It should be:
> 
> ```cs
> var options = new FilePickerOpenOptions() { ... };
> var result = await window.StorageProvider.OpenFilePickerAsync(options);
> ```

Thanks! Helped a lot!
