### ISSUE TITLE
Bounds property is not correct due to DPI scaling

### ISSUE THREAD

**Issue by Hanprogramer** [AvaloniaUI/Avalonia#9788]
**Describe the bug**
The `Bounds` property is not correct to pixel size on the screen and have to be manually scaled according to the display scaling. My device scaling is 150% and the `Bounds` shows 66, but when i actually manually calculated the size it's about 100 pixel ish, so i tested by multiplying it to 1.5 and it's correct.

**To Reproduce**
```CS
        protected override unsafe void OnOpenGlRender(GlInterface gl, int fb)
        {
            Gl.ClearColor(Color.Firebrick);
            Gl.Clear((uint)(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit));
            Gl.Enable(EnableCap.DepthTest);
            Gl.Enable(EnableCap.Blend);
            Gl.BlendFunc(BlendingFactor.SrcAlpha, BlendingFactor.OneMinusSrcAlpha);
            Gl.Viewport(0,0, (uint)(Bounds.Width*1.5f), (uint)(Bounds.Height*1.5f));
```

**Expected behavior**
Bounds property being correct to pixel size displayed

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Version Unknown

**Additional context**
Avalonia 0.10.18

**Comment by Hanprogramer** [comment]
This is how i fixed mine
```CS

            // Avalonia is not scaling properly on Windows, so have to manually does it
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                var scaling = Win32Native.GetScreenScaling(this);
                Gl.Viewport(0, 0, (uint)(Bounds.Width * scaling), (uint)(Bounds.Height * scaling));
            }
            else
                Gl.Viewport(0, 0, (uint)(Bounds.Width), (uint)(Bounds.Height));
```

```CS

        public static double GetScreenScaling(Control control)
        {
            var toplevel = (TopLevel)control.GetVisualRoot();
            if (toplevel.PlatformImpl is WindowImpl platformImpl)
            {
                return platformImpl.DesktopScaling;
            }
            return 1;
        }
```

**Comment by ahopper** [comment]
If I understand correctly this is expected behaviour, Bounds and other Avalonia drawing units are in device independent units just like WPF so in normal use things are about the right size what ever resolution screen is used.

**Comment by emmauss** [comment]
Like @ahopper explained, this is expected behavior. 

To get the pixel size from bounds, you can use this, 
```var pixelSize = PixelSize.FromSize(Bounds.Size, PlatformImpl.RenderScaling);``` in a `Window` derived class. `PlatformImpl.RenderScaling` is accessible from any `TopLevel`.
