### ISSUE TITLE
DataGrid Column Headers too wide due to Fluent hardcoding sort icon width

### ISSUE THREAD

**Issue by garyhertel** [AvaloniaUI/Avalonia#9791]
**Is your feature request related to a problem? Please describe.**

In the base/default themes, there is no space permanently allocated to the sort icon spot in the DataGrid column header. However, in Fluent this got hardcoded to 32 pixels. This ends up wasting a lot of space if you have a lot of columns and short content in the cells (i.e. checkboxes or small numbers). This can cause every column to be twice as wide as necessary meaning a lot less information can be shown at once.

Fluent Theme:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml#L163

Base Theme:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls.DataGrid/Themes/Simple.xaml#L68

**Describe the solution you'd like**

Can the sort icon not hardcode the width like the default theme, or can this be made configurable? I understand there might be a slight benefit in a few cases where the transition from not showing the sort icon to showing it can be better with the hardcoded width, but I would prefer the ability to show more columns instead as that's always useful, and sorting only sometimes useful.

**Describe alternatives you've considered**

I tried using xaml to override this behavior, but wasn't able to figure it out. Any suggestions on how to do this through xaml would be appreciated too (although I would imagine most would prefer to make this to configurable?)

**Additional context**

Fluent Theme:
![DataGridColumnsWithFluent](https://user-images.githubusercontent.com/32446542/209579927-80088e92-589c-47ea-9966-6fae50e0c626.png)

Base Theme:
![DataGridColumnsWithBaseFont16](https://user-images.githubusercontent.com/32446542/209579969-353a5c2c-640a-4d83-ad95-4efe52251a25.png)

**Comment by VMelnalksnis** [comment]
@garyhertel Did you find some workaround for this? I also tried (and failed) to fix this in v11 by overriding the style with selectors, and ended up just copying the `ControlTheme` for `DataGridColumnHeader` and modifying it.

**Comment by timunie** [comment]
@VMelnalksnis you cannot override local values via style selector as local values have higher priority. So yeah, you need to override the ControlTheme for now. If anyone has some free time, a PR would be welcome which fixes this issue.

**Comment by VMelnalksnis** [comment]
I'd be willing to contribute, but I'm not certain what the expected behavior is. From the mentioned issue I see that the datagrid fluent theme is supposed to be touch friendly, so I'm guessing the default width and extra padding was added due to that. Maybe the `MinWidth` on the `SortIcon` can be set based on `OwningColumn.CanUserSort`?

**Comment by timunie** [comment]
@VMelnalksnis I think introducing a DynamicResource for it could be a valid solution. 

```xml
<x:Double x:Key="DataGridSortIconMinWidht">20</x:Double>

... 

MinWidth="{DynamicResource DataGridSortIconMinWidht}"
```

**Comment by VMelnalksnis** [comment]
Ok, I'll make a PR once community contributions are resumed after v11.

**Comment by timunie** [comment]
I think issues marked with help-wanted and bug fixes label and bug fixes are okay to contribute to.

**Comment by VMelnalksnis** [comment]
Ah, alright, the pinned update said critical bug fixes only.

**Comment by maxkatz6** [comment]
> Ah, alright, the pinned update said critical bug fixes only.

This one is pretty minor and easy to review, so I personally can review it.
