### ISSUE TITLE
ProgressTextFormat on ProgressBar apparently does not exist

### ISSUE THREAD

**Issue by LinUwUxCat** [AvaloniaUI/Avalonia#9792]
**Describe the bug**
When using the attribute ProgressTextFormat on a ProgressBar, you get an error `Unable to resolve suitable regular or attached property ProgressTextFormat on type Avalonia.Controls:Avalonia.Controls.ProgressBar`.

**To Reproduce**

In MainWindow.axaml, put something like `<ProgressBar Maximum="{Binding Maximum}" Value="{Binding Current}" ProgressTextFormat="Downloaded {0}MB out of {3}MB"/>`. 

**Expected behavior**
The application would launch with the corresponding text within the progress bar.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**

- OS: Linux (Pop!_OS 22.04 LTS)
- Version : 0.10.18

**Additional context**
This is kinda weird because the [docs](https://docs.avaloniaui.net/docs/controls/progressbar) and the [source code](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/ProgressBar.cs#L112) reference this property but it seems to simply not exist for me.

**Comment by timunie** [comment]
I think it's only available in 11.0 previews for now.

**Comment by LinUwUxCat** [comment]
oh i see. That would make sense, but it's weird that such an information is present in the docs if it's only a preview feature...
