### ISSUE TITLE
Fonts loaded from Assets seem to be rendered thinner then they should be

### ISSUE THREAD

**Issue by BaseCrusher** [AvaloniaUI/Avalonia#9797]
**Describe the bug**
When loading in a Font the rendering seems to be way thinner then it actually should be

**To Reproduce**

1. Create a simple Avalonia Project.
2. Add a custom font (I got mine from google fonts)
3. Add the font to the application
4. Run the application

**Expected behavior**
Fonts should look similar to how they are displayed in other apps.

**Screenshots**
Actual:
![image](https://user-images.githubusercontent.com/12885003/209783128-05a76f04-3dd6-4f4d-a934-292cf763b29f.png)
Expected
![image](https://user-images.githubusercontent.com/12885003/209782941-eccb1e25-8d98-4e6a-96cf-ae2fdf30bd53.png)

**Desktop (please complete the following information):**

- OS: Windows 10

**Comment by robloo** [comment]
We need to know which version of Avalonia you are using. There have been a lot of changes to text processing.

What application is producing the "expected" image? Is it WPF?

**Comment by BaseCrusher** [comment]
Right I shoudl have been more precise.

Avalonia version: 11 Preview 4

Expected is how it looks when the font is used in the browser. Though as far as I know fonts are standardized. So If the fonts options that are used in the browser are set to the same as in Avalonia or WPF there should be no difference.

Here also the link to the font I used in the example: https://fonts.google.com/specimen/Roboto+Mono?preview.text=0123&preview.text_type=custom&category=Monospace

But this also occurs with other fonts.

Hope this answers all questions :)

**Comment by BaseCrusher** [comment]
So I have just tested it with preview 8 and it still seems like, the text is not rendered as expected.

**Comment by Gillibald** [comment]
So you have set RenderOptions.TextRenderingMode="Alias" and it did nothing?

**Comment by BaseCrusher** [comment]
Ok, i have retested it. The issue was on my side. I have used a font with wght, which contains all types of the font in a single file, but Avalonia doesn't seem to recognize it. Having the font types in separate files works without any issue. I think it would be good, to remark it somewhere.

**Comment by Gillibald** [comment]
Variable fonts are not fully supported yet. This will come with Avalonia 11.X
