### ISSUE TITLE
Automatic installation package generation

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#981]
At lease for OSX app bundle, .deb packages and linux-distro-agnostic .zips, since they can be generated entirely in managed code. 

We need a custom tool even for zip archives because of UNIX file access permissions that don't exist on Windows.

**Comment by jkoritzinsky** [comment]
What's the status on this?

**Comment by kekekeks** [comment]
It will probably live in a separate repo. Currently I've made some progress by adding `deb` package support to [Packaging.Targets](https://github.com/qmfrederik/dotnet-packaging). It's still needed to create a separate msbuild task for generating avalonia-specific file entries.

No progress on OSX support yet.

**Comment by kekekeks** [comment]
I think it shouldn't be a release blocker since it won't depend on anything and can be released separetely.

**Comment by x2bool** [comment]
If anyone is interested I've built a custom MSBuild task and dotnet cli tool for bundling macOS .app packages: https://github.com/egramtel/dotnet-bundle

**Comment by manijak** [comment]
So currently there is no way to publish an .app for macOS via Avalonia? 

I've tried the `dotnet-bundle` method but the outputed application is corrupted and cannot be opened.

**Comment by kekekeks** [comment]
No *automatic* way. See https://github.com/AvaloniaUI/Avalonia/issues/1948#issuecomment-427457994 for manual packaging instructions.
