### ISSUE TITLE
TextBox inherited don't paint 

### ISSUE THREAD

**Issue by jmmortega** [AvaloniaUI/Avalonia#9816]
Describe the bug

When create a custom textbox using the original implementation (inherit TextBox class) this can't paint.

Create a custom class that inherit TextBox, put this new implementation in a XAML. This textbox doesn't paint.

Expected behavior

Custom implementation of textbox should be paint correctly

Screenshots

![Screenshot 2022-12-30 at 10 33 53](https://user-images.githubusercontent.com/4325509/210055530-54303c17-d66c-4091-a853-db492f00e15f.png)

**Desktop (please complete the following information):**

- OS: Mac Os Ventura 13.1 (M1) This bug it's replicable in Android and iOS also.
- Version: 11.0.0-preview4 (Also replicable in 0.10.8)

**Comment by timunie** [comment]
You need to add a Style for your new Control or override `IStyleable.Stylekey=typeof(TextBox)`

**Comment by jmmortega** [comment]
Thanks @timunie !
```
public class CustomTextBox : TextBox, IStyleable
{
    public Type StyleKey => typeof(TextBox);
}
```

Newbie here in Avalonia, sorry to raise a bug too early.

**Comment by timunie** [comment]
All fine. You can also join telegram chat or use discussuins.
