### ISSUE TITLE
XAML Standard

### ISSUE THREAD

**Issue by Suriman** [AvaloniaUI/Avalonia#982]
Are there any plans to support [XAML Standard ](https://github.com/Microsoft/xaml-standard)in Avalonia?

**Comment by kekekeks** [comment]
No plans yet, it's still an early draft. We should provide them with some feedback and ideas, though.

**Comment by wieslawsoltes** [comment]
For reference I have submited few issues based on Avalonia implementation:
* https://github.com/Microsoft/xaml-standard/issues/47  Allow Grid RowDefinitions and ColumnDefinitions defined in attributes
* https://github.com/Microsoft/xaml-standard/issues/60 Add shorthand syntax for Binding to a named control
* https://github.com/Microsoft/xaml-standard/issues/86 Add ToolTip support
* https://github.com/Microsoft/xaml-standard/issues/87 Add TreeView control with hierarchical data binding
* https://github.com/Microsoft/xaml-standard/issues/88 Add ItemsControl support
* https://github.com/Microsoft/xaml-standard/issues/89 Add VirtualizingStackPanel control
* https://github.com/Microsoft/xaml-standard/issues/90 Add ContextMenu support

**Comment by jkoritzinsky** [comment]
I'm tracking our XAML standard implementation status in #1282
