### ISSUE TITLE
PropertyChanged not recognized after posting to SynchronizationContext.Current

### ISSUE THREAD

**Issue by CooperMidnight** [AvaloniaUI/Avalonia#9837]
(EDIT: I've changed the title to reflect the second post. Let me know if you'd like me to just replace the contents of this post)

**Describe the bug**
In my Avalonia MVVM app, I have a command on the view model that creates a `Progress<int>` and passes it as a parameter to a different `Task`- returning function to receive progress updates. The handler for the `Progress<int>` object updates a `Status` property on the view model. After the inner function completes, further updates to the `Status` property are ignored.

I have paused during debugging in Visual Studio and verified that the function is in the "main" thread at the time of execution. I've also tried adding a `Dispatcher.UIThread.VerifyAccess()` call just to be doubly sure.

NOTE: This behavior _only_ goes on for as long as the command handler continues executing. The next time the button is clicked, the entire cycle repeats (including the first status change happening correctly)

**To Reproduce**
I have reduced the problem to the following minimal repro. Note that when the body of `OnProgressUpdated` is changed to be empty, the last status change (`"Command finished."`) is reflected in the view.

```
// MainWindowViewModel.cs
using ReactiveUI;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Input;

namespace BugDemo.ViewModels;

public class MainWindowViewModel : ViewModelBase
{
    private string _status;

    public MainWindowViewModel()
    {
        Test = ReactiveCommand.CreateFromTask(TestCore);
        _status = "Nothing";
    }

    public ICommand Test { get; } = default!;

    public string Status
    {
        get => _status;
        private set => this.RaiseAndSetIfChanged(ref _status, value);
    }

    private async Task TestCore()
    {
        Status = "Starting command.";
        await Task.Delay(100);
        var progress = new Progress<int>(OnProgressUpdated);
        await DoWorkAsync(progress);
        Status = "Command finished."; // This is never shown
    }

    private void OnProgressUpdated(int value)
        => Status = $"Status updated: {value}";

    private static async Task DoWorkAsync(IProgress<int> progress)
    {
        foreach (var i  in Enumerable.Range(1, 10))
        {
            await Task.Delay(100);
            progress.Report(i);
        }
    }
}
```

```
<!-- MainWindow.axaml -->
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:BugDemo.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="BugDemo.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="BugDemo">

    <Grid>
        <StackPanel>
            <Button HorizontalAlignment="Center"
                    VerticalAlignment="Center"
                    Content="click me"
                    Command="{Binding Path=Test, Mode=OneWay}" />
            <TextBlock Text="{Binding Path=Status, Mode=OneWay}" />
        </StackPanel>
    </Grid>

</Window>

```

**Expected behavior**
The last status change (`"Command finished."`) is reflected in the view.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Windows 10 Pro x64 21H2
- Version 0.10.18

**Additional context**
Could this instead be a bug in ReactiveUI?

**Comment by CooperMidnight** [comment]
Update: What `Progress<T>` does behind the scenes is capture `SynchronizationContext.Current` and use that to post the updates. I've taken that knowledge and further reduced the minimal repro to the following code sample.

```
using ReactiveUI;
using System.Threading;
using System.Windows.Input;

namespace BugDemo.ViewModels;

public class MainWindowViewModel : ViewModelBase
{
    private string _status;

    public MainWindowViewModel()
    {
        Test = ReactiveCommand.Create(TestCore);
        _status = "Nothing";
    }

    public ICommand Test { get; } = default!;

    public string Status
    {
        get => _status;
        private set => this.RaiseAndSetIfChanged(ref _status, value);
    }

    private void TestCore()
    {
        Status = "Starting command.";
        var context = SynchronizationContext.Current!;

        context.Post(o => Status = "New status", null);

        Status = "Command finished."; // Never shows
    }
}
```

**Comment by maxkatz6** [comment]
Seems to work as expected. At least from Avalonia side how it handles synchronization context.
From my experience, default Progress type has a very annoying behavior with its usage of SynchronizationContext, when it's not necessary. But it is relatively easy to create own implementation of IProgress interface.

> PropertyChanged not recognized after posting to SynchronizationContext.Current

The problem in your code is that Post is asynchronous method, and it is executed after current context's code is completed.

See:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs#L33
Or WPF implementation:
https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/DispatcherSynchronizationContext.cs#L79

By calling SynchronizationContext.Post application schedules a new job on the UI thread which will be executed according to the priority after current job.
If job needs to be awaited, then either Send method should be used (which can block current thread, if called from non-UI thread), or same Post but with some synchronization object like TaskCompletionSource. BCL Progress implementation does neither.

**Comment by CooperMidnight** [comment]
@maxkatz6 Ah, what a trivial mistake on my part. Thank you 😅
