### ISSUE TITLE
Segmentation fault attaching debugger .NET 7

### ISSUE THREAD

**Issue by mkj-stonehill** [AvaloniaUI/Avalonia#9844]
**Describe the bug**
Attaching the debugger (in Visual Studio 2022) over SSH to an Avalonia application built with .NET 7 running on a Raspberry Pi causes the application to segmentation fault.  Building the application with .NET 6 works correctly.

**To Reproduce**
1. Create simple "Welcome to Avalonia" application on Windows using Visual Studio 2022.
2. Publish to local folder, Configuration=Debug, Target Framework=net7.0, Target Runtime=Portable
3. Copy folder to Raspberry pi (I'm running latest Bullseye build, with latest .NET framework installed).
4. Verify application works by running a shell, cd to the folder, and run dotnet foo.dll
5. In Visual Studio, click Debug | Attach to process...
6. Set Connection Type to SSH, and set Connection target to log in to the Pi
7. Click the dotnet process (running the test app), and click Attach.
8. The application (on the Pi) will segmentation fault.

**Expected behavior**
Expect debugger to be able to attach to the running process.  Note that if application is built using .NET 6.0, everything works as expected.

**Screenshots**

**Desktop (please complete the following information):**

```
 $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
Microsoft Visual Studio Community 2022
Version 17.4.3
VisualStudio.17.Release/17.4.3+33205.214
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA613
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

AvaloniaPackage Extension   1.0
AvaloniaPackage Visual Studio Extension Detailed Info

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

C# Tools   4.4.0-6.22580.4+d7a61210a88b584ca0827585ec6e871c6b1c5a14
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Extensibility Message Bus   1.4.1 (main@2ee106a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Linux Core Dump Debugging   1.0.9.33020
Enables debugging of Linux core dumps.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.4.19 (8c0a575)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2246202+61cc048d36a3fc9246d2f04625988b19a18ab8f0
Provides languages services for ASP.NET Core Razor.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.4.0-6.22580.4+d7a61210a88b584ca0827585ec6e871c6b1c5a14
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.33020
Visual C++ for Linux Development

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.4.0.312 (d17-4@be7e8d1)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.4.0.138 (remotes/origin/d17-4@d36bba3cc9)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.1.0.1 (d17-4/13ba222)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a96bde9
    Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
    SQLite: xamarin/sqlite/3.39.3@23e1ae7
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a

**Additional context**

**Comment by kekekeks** [comment]
Since the only different thing is the runtime version, I believe that it's a bug in .NET Runtime

**Comment by mkj-stonehill** [comment]
I thought the same thing; that's why I tried a simple console app (no Avalonia involved at all).  That works fine (both .NET 6 and 7).  So it seems to be some sort of interaction between Avalonia (or the native libraries it loads) and the .NET runtime...?

**Comment by kekekeks** [comment]
Are you using 32 bit ARM? We've seen some JIT bugs on armhf with recent .NET versions.

**Comment by mkj-stonehill** [comment]
Yes, I'm running the 32-bit version of Bullseye on the Pi.  Does the 64-bit ARM JIT compiler also have problems?  I'm not sure yet if I can get 64-bit versions of all of the native libraries I need, but if the JIT problem is just 32-bit, I can make more of an effort.

**Comment by kekekeks** [comment]
64-bit ARM has first-class support in .NET since it's used by Azure. 32-bit ARM isn't used by Azure, so they are removing it completely in .NET 9.
