### ISSUE TITLE
ScrollViewer lag on scroll start on Android

### ISSUE THREAD

**Issue by kikipoulet** [AvaloniaUI/Avalonia#9846]
On Android, the ScrollViewer start scrolling after the finger movement started and then "jump" directly to the new position without animation. 

But when scrolling in the opposite side of the scroll before scrolling, the scroll is normal and smooth.

https://user-images.githubusercontent.com/19242427/210284177-e1cee4ed-5319-42f3-b6f3-e2fa2f16e6a1.mp4

The video shows finger touches, you can clearly see the problem with the "Settings" title animation.

**Comment by maxkatz6** [comment]
Is it preview4 or latest master nightly build?
Asking in context of these latest PRs which should have fixed jumping problem https://github.com/AvaloniaUI/Avalonia/pull/9804 https://github.com/AvaloniaUI/Avalonia/pull/9824

**Comment by kikipoulet** [comment]
It is indeed preview4 👍
