### ISSUE TITLE
PointerWheelChanged event gives incorrect PointerWheelEventArgs.Delta value (intermittent)

### ISSUE THREAD

**Issue by kuiperzone** [AvaloniaUI/Avalonia#9858]
**Describe the bug**
The PointerWheelChanged event occasionally (say 1 in 20) gives incorrect PointerWheelEventArgs.Delta value.

**To Reproduce**
See the screenshot below. I have an event linked up to PointerWheelChanged of a UserControl. The e.Delta.Y occasionally gives an incorrect positive value when consistently moving the mouse wheel only one way. It doesn't appear to fail the other way, i.e. give a negative when it should be positive.

**Screenshots**

![image](https://user-images.githubusercontent.com/17156238/210382856-85c62b1f-4e53-4536-a59f-56948d8f24a1.png)

**Desktop (please complete the following information):**

- OS: Fedora 37
- Version 0.10.18

**Additional context**

**Comment by timunie** [comment]
Hi @kuiperzone ,

can you test it with latest nightly builds as well? There were may fixes in rendering, hittesting etc. You probably need to create a simple test App. If you have such a small test App, you can also shere it via new GitHub Repo. Thx 😄. 

Happy coding
Tim

**Comment by kuiperzone** [comment]
Hi Tim,

Built a minimal app and did some testing against 0.11 preview 4. The exercise caused me to consider that it might be my hardware -- I seem to have a mouse with a trigger sensitive wheel. When I tried with an different brand mouse, I could not repeat the problem.

Looks like a false positive.

**Comment by timunie** [comment]
> Hi Tim,
> 
> Built a minimal app and did some testing against 0.11 preview 4. The exercise caused me to consider that it might be my hardware -- I seem to have a mouse with a trigger sensitive wheel. When I tried with an different brand mouse, I could not repeat the problem.
> 
> Looks like a false positive.

Thx for testing. Maybe it's also worth to try your device in a different environment like python or LibreOffice Basic in order to verify if the problem only occurs in Avalonia or not. If the same issue appears also in other frameworks I'd close this issue.

**Comment by kuiperzone** [comment]
Mmmm. Not sure about this. I don't experience any problem with my mouse in general use, for example, when wheeling thru code in Visual Code.

My mouse is blue tooth Tecknet. When I tried with an older wired Microsoft mouse, I couldn't reproduce the problem.

**Comment by kuiperzone** [comment]
Yup - think it's my mouse. Just managed to reproduce it while scrolling in the browser. Doesn't happen enough to cause me a problem, but the effect is there.

Think you can close this.

**Comment by timunie** [comment]
As the issue seems to be hardware related, there is nothing we can do on our side. closing this issue.
