### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#986]
Is there a way to inject dependencies into a user defined controls, maybe similar to how ASP.NET does it with Controllers?

```csharp
public class MyControl : UserControl
{
    public MyControl(IMyDependency dep)
    {
        // ...
    }
}
```

**Comment by grokys** [comment]
There's not currently any way to do this, at least from XAML, as XAML doesn't currently support such a thing, unfortunately.
