### ISSUE TITLE
Add support for window transparency

### ISSUE THREAD

**Issue by sgf** [AvaloniaUI/Avalonia#987]
![borderlesswindow](https://cloud.githubusercontent.com/assets/2557696/26264796/a756f1a2-3d10-11e7-8a06-896f03361650.png)

**Comment by WarFollowsMe** [comment]
HasSystemDecorations = false and then make your own header. Good example [AvaloniaStudio](https://github.com/VitalElement/AvalonStudio)

**Comment by sgf** [comment]
Cool !

**Comment by kekekeks** [comment]
Windows with transparent areas aren't supported at the moment. On Linux/OS X it should be a fairly easy task, on windows it would be a bit complicated (`UpdateLayeredWindow` is slow, so [this approach](https://msdn.microsoft.com/en-us/magazine/dn745861.aspx) should be used instead, which in turn introduce compatibility issue, since `WS_EX_NOREDIRECTIONBITMAP` was introduced only in Win8).

**Comment by kekekeks** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa969508(v=vs.85).aspx seems to be another option for Win7

**Comment by OronDF343** [comment]
I am also in need of this feature (to be able to port my application over correctly from WPF).
How does WPF handle transparent windows on Windows 7?

**Comment by OronDF343** [comment]
The second option (DWM_ENABLE_BLURBEHIND) is what I used once before to get the same result, although I don't remember which options I used and if it ended up working in WinForms. I'll see if I can find my old code later.

**Comment by mavericken** [comment]
It appears that WPF uses WS_EX_LAYERED on Windows 10 even, so this talk about having to do WS_EX_NOREDIRECTIONBITMAP would be a straight upgrade from WPF.

**Comment by derekantrican** [comment]
I think this is fixed with 0.10.0 & `TransparencyLevelHint="AcrylicBlur"`, correct?

**Comment by kekekeks** [comment]
Transparency now works for Win10, Linux and macOS

**Comment by derekantrican** [comment]
@kekekeks 
Actually, what is the lowest OS version support for transparency in OSX? I can't seem to get transparency to work in 10.13.6 with `TransparencyLevelHint` or `Background="Transparent"` with Avalonia 0.10.0 but `Background="Transparent"` worked in OSX 10.13.6 with Avalonia 0.9.12

**Comment by kekekeks** [comment]
@danwalmsley regular transparency has used to work with all OSX versions, something got broken.
