### ISSUE TITLE
Unexpected behaviours when using Expander in ListBox

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#9871]
**Describe the bug**
It seems ListBox is reusing the containers and keeps Expander's IsOpen property.

**To Reproduce**

https://github.com/laolarou726/ExpanderInListBoxTest

**Expected behavior**

Expanders that didn't open should keep closed when scrolling down

**Screenshots**

![record](https://user-images.githubusercontent.com/25716486/210649729-263e5de5-3d7e-45bc-9e58-3fb9b494640b.gif)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 22H2

**Comment by laolarou726** [comment]
Just found a new bug, when the content of the Expander is greater than the viewport. ListBox will not show the full content of the Expander unless you change the size of the window:

![record1](https://user-images.githubusercontent.com/25716486/210650936-c9549b78-5706-4e65-b3ac-ad76e18938f3.gif)

I just add this demo in the repo: https://github.com/laolarou726/ExpanderInListBoxTest

Is there any way to fix this bug?

**Comment by maxkatz6** [comment]
Not sure if it's a bug.
When binding to a list with template, expander will be reused. Which means if it was opened once, same container will be opened for another data item.

You can handle it by binding Expander.IsExpanded to a data property.
Or you can add an attached property that will listen for Expander Loaded/AttachedToVisualTree event and reset some of its properties.
Or you can disable virtualization at all, so no containers will be reused. `ListBox VirtualizationMode="None'`

**Comment by laolarou726** [comment]
> Not sure if it's a bug.
> 
> When binding to a list with template, expander will be reused. Which means if it was opened once, same container will be opened for another data item.
> 
> 
> 
> You can handle it by binding Expander.IsExpanded to a data property.
> 
> Or you can add an attached property that will listen for Expander Loaded/AttachedToVisualTree event and reset some of its properties.
> 
> Or you can disable virtualization at all, so no containers will be reused. `ListBox VirtualizationMode="None'`

How about another issue? When Expander's height is greater than the viewport. ListBox failed to show the whole content of the Expander.

**Comment by maxkatz6** [comment]
@laolarou726 another issue should be fixed with https://github.com/AvaloniaUI/Avalonia/pull/9677
Not sure if it was reported anywhere.

**Comment by laolarou726** [comment]
> @laolarou726 another issue should be fixed with https://github.com/AvaloniaUI/Avalonia/pull/9677
> 
> Not sure if it was reported anywhere.

hmm, in this repro I'm using the latest nightly build. It should already contains the following fix. Did I miss something?

**Comment by maxkatz6** [comment]
That PR wasn't yet merged, so it's not part of the master branch nightly builds.

**Comment by timunie** [comment]
But you can test the PR via: https://github.com/AvaloniaUI/Avalonia/pull/9677#issuecomment-1356889433 , if you want to.

**Comment by laolarou726** [comment]
> @laolarou726 can you confirm that another issue was fixed for you? If so, this issue can be closed.

@maxkatz6 @timunie I just confirmed the issue was fixed! Thank you so much!
