### ISSUE TITLE
what is AggregatePackage.NuGet.Sdk used for?

### ISSUE THREAD

**Issue by SimonCropp** [AvaloniaUI/Avalonia#9874]
i noticed https://github.com/jkoritzinsky/AggregatePackage.NuGet.Sdk is now archived and https://www.nuget.org/packages/AggregatePackage.NuGet.Sdk is unlisted.

is it still required? removing it seems to still build fine

**Comment by SimonCropp** [comment]
@jkoritzinsky ping

**Comment by jkoritzinsky** [comment]
It's not used any more. I created it a long time ago for creating the merged Avalonia NuGet package, but we ended up going a different route that was more stable.

**Comment by maxkatz6** [comment]
Our list of SDKs used in the project wasn't updated in ages. We don't use MSBuild.Sdk.Extras anymore too, for example.
Only Microsoft.Build.Traversal is still used.
https://github.com/AvaloniaUI/Avalonia/blob/master/global.json
