### ISSUE TITLE
Pending changes for the IStorageProvider API

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#9876]
New IStorageProvider was added in one of the first 11.0 previews. Some developers already tested it, and some places can be or should be updated before the release.

- [x] Add new TryGet*** methods as a safe way to read folder/file.
``` csharp
+ Task<IStorageFile?> TryGetFileFromUri(Uri fileUri); // with an extension accepting string that will be converted to "file://" uri?
+ Task<IStorageFolder?> TryGetFolderFromUri(Uri folderUri); // with an extension accepting string?
+ Task<IStorageFolder?> TryGetWellKnownFolder(WellKnownFolder); // the only supported way on Browser and iOS.
```
- [x] Remove BclStorageFile/Folder classes from the public API as it was intended to be reusable implementation of the file/folder for the backend, but instead it is overused as a hack to get path, limiting application with specific platforms in an ugly way.
- [x] Remove CanOpenWrite and CanOpenRead from the file API, as it always returns "true" on current backends and doesn't make sense
- [x] Change `Task<IReadOnlyList<IDialogStorageItem>>` GetItemsAsync to `IAsyncEnumerable<IDialogStorageItem> GetItemsAsync`
- [x] Add IStorageFolder methods to create subfolder and possibly subitems
- [x] Add methods to delete, rename or move file (note, none of these methods are in standard for the Browser support, but works in the Chromium based browsers)
- [x] As it was discussed in https://github.com/AvaloniaUI/Avalonia/issues/9029 we can replace TryGetUri with `Uri? Path { get; }`. Original reasoning to use TryGetUri was because it could potentially fail with some backend. When in fact every backend returns at least a relative Uri (even if it contains only a file name, it's still a valid relative path).
- [x] Remove public `ITopLevelImplWithStorageProvider` with `TopLevelImpl.TryGetFeature` design pattern. Need further discussion and can be done in the future (assuming we don't guarantee API stability for the Impl classes/interfaces).

Out of IStorageProvider scope, but in scope of IStorageFile/IStorageFolder specifically
- [x] Integrate with drag n drop API (makes it possible to implement drag n drop for mobile and browser backends) https://github.com/AvaloniaUI/Avalonia/pull/10389
- [ ] Integrate with Share API https://github.com/AvaloniaUI/Avalonia/pull/9253
- [ ] https://github.com/AvaloniaUI/Avalonia/issues/10628

Mostly based on discussions in https://github.com/AvaloniaUI/Avalonia/discussions/9014 and https://github.com/AvaloniaUI/Avalonia/discussions/9868, but there were move discussions in the issues and telegram chats.

**Comment by maxkatz6** [comment]
I am planning to pick up BclStorageFile/Folder replacement with TryGet*** methods before 11.0 release.
Everything else either will go to 11.1 or somebody will have time to implemented before. Marking as "help wanted" for that.

**Comment by maxkatz6** [comment]
Possible API for the Move/Rename/Create methods:
```diff
+public enum NameCollisionOption
+{
+     FailIfExists,
+     ReplaceExisting
+}
public interface IStorageItem
{
+    Task DeleteAsync();
+    Task RenameAsync(string desiredName, NameCollisionOption option);
}
public interface IStorageFile
{
+    Task MoveAsync(IStorageFolder destinationFolder, string desiredNewName, NameCollisionOption option);
+    Task CopyAsync(IStorageFolder destinationFolder, string desiredNewName, NameCollisionOption option);
}
public interface IStorageFolder
{
+    Task<IStorageItem?> GetItemAsync(string name); // as an alternative to GetItemsAsync
+    Task<IStorageFolder> CreateFolderAsync(string desiredName, NameCollisionOption option);
+    Task<IStorageFile> CreateFileAsync(string desiredName, NameCollisionOption option);
}
```
Yes, almost the same API from UWP. But these methods should work with browser sandbox as well.

As it's only additions to the API, it can be done in 11.x releases timeline as well.

**Comment by workgroupengineering** [comment]
Why did you choose this design for TryGet***?
A .net developer expects a signature similar to:

```csharp

Task<bool> TryGet(string key, [MaybeNullWhen(false)] out string value)
{
    value = default(string);
    return Task.FromResult(false);
}

**Comment by majeric** [comment]
Where's the documentation that informs the developer how upgrade using the new API?

**Comment by maxkatz6** [comment]
https://docs.avaloniaui.net/docs/concepts/services/storage-provider/
https://docs.avaloniaui.net/docs/concepts/services/storage-provider/storage-item
https://docs.avaloniaui.net/docs/concepts/services/storage-provider/bookmarks
https://docs.avaloniaui.net/docs/concepts/services/storage-provider/file-picker-options

**Comment by Smibu** [comment]
`RenameAsync` method is still missing. Should this be reopened or should I open a separate issue?

Related discussion: https://github.com/AvaloniaUI/Avalonia/discussions/19152

**Comment by maxkatz6** [comment]
@Smibu can you open a new issue?
I suppose we might prefer this API, for consistency with IStorageItem.MoveAsync:
```
+public enum NameCollisionOption
+{
+     FailIfExists,
+     ReplaceExisting
+}
public interface IStorageItem
{
+    Task MoveAsync(IStorageFolder destinationFolder, string desiredNewName, NameCollisionOption option);
}
```
