### ISSUE TITLE
Convert.ToDouble(String) won't work

### ISSUE THREAD

**Issue by CarosCave** [AvaloniaUI/Avalonia#9939]
I did a new Avalonia Project with the "Avalonia .NET Core App" template. I use the code below to convert String to Double:

```csharp
string strDouble = "100,1"; // 100,1      
double dblDouble = Convert.ToDouble(strDouble); // 100.099999999999
```

Also rounding like 
```csharp
double rndDouble = Math.Round(dblDouble, 1);
```
has no effect.

A .NET console or a WPF app will convert the string "100,1" correct  to a double 100,1 (100.1).

![screenshot convert to double](https://user-images.githubusercontent.com/15948931/211219780-53f2b217-3d16-41ac-8a7f-c849e155abbc.png)

**Comment by maxkatz6** [comment]
Not related to the Avalonia.
