### ISSUE TITLE
Border BorderDashArray is disabled when BorderThickness is a non uniform value.

### ISSUE THREAD

**Issue by SalBakraa** [AvaloniaUI/Avalonia#9942]
**Describe the bug**
When setting `BorderThickness` to a non uniform value, the border stops being a dashed border.

**To Reproduce**

1. Create the following View:

`BorderIssueShowcaseView.axaml`:

```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="400" d:DesignHeight="400">
	
	<Border Width="200" Height="100" BorderBrush="black"
	        BorderThickness="5 4"
	        BorderDashArray="5,1">
		
		<TextBlock Text="Hello, World!" Margin="10" />
	</Border>
</UserControl>
```

2. Open IDE previwer or Run the application

**Expected behavior**

Each segment of the border would appear dashed.

**Screenshots**

Uniform Thickness:

![HDMI-0-20230110-010914](https://user-images.githubusercontent.com/81700377/211420817-b47acc80-3e20-4e8e-9d55-812af6dc7499.png)

Non Uniform Thickness:

![HDMI-0-20230110-010921](https://user-images.githubusercontent.com/81700377/211420838-8023ee7f-f9b3-45a8-9c56-8c811d47b1a2.png)

**Desktop (please complete the following information):**

- OS: Linux (Arch)
- Avalonia Version: 0.10.18

**Additional context**

I noticed this issue when I wanted to display grid lines in Grid and have every other row have dashed bottom border giving the grid alternating border shapes similar to the Samsung Calendar app looks. I honestly think a better api should be provided for native grid lines instead of directly creating the borders myself.

![f75d589d-9c1a-4783-85b6-ea0db2a6b198](https://user-images.githubusercontent.com/81700377/211421034-cf3ca6ae-2dbc-48b9-82d4-3bc9206e48bf.jpg)

**Comment by grokys** [comment]
Pinging @RomanSoloweow who implemented this feature

**Comment by robloo** [comment]
@SalBakraa Line dash support is being removed from `Border` for this and related issues.

You will now need to construct a shape yourself to do what you want. This is the same as WPF.
