### ISSUE TITLE
Segfault when launching application

### ISSUE THREAD

**Issue by Anthonywolfe** [AvaloniaUI/Avalonia#9945]
**Describe the bug**
When launching my application 9 out of 10 times it crashes due to a signal 11 segmentation fault seemingly related to libfontconfig. 

My application is purpose built for a embedded device running a custom ARM64 linux kernel but after commenting out the code that communicates with the hardware directly leaving only the Main window and a few empty user controls I still experienced the crash.

/usr/lib/libfontconfig.so.1(+0x217e0)[0xffff9840a7e0]
/usr/lib/libfontconfig.so.1(+0x21960)[0xffff9840a960]
/usr/lib/libfontconfig.so.1(FcPatternGetString+0x5c)[0xffff9840c9ac]
/home/petalinux/App/runtimes/linux-arm64/native/libSkiaSharp.so(+0x41bf0c)[0xffff9885ef0c]
??:0(??)[0xffff28ad426c]

**To Reproduce**

**Expected behavior**

**Screenshots**
I've attached the crashdump as outputted by catchsegv
[catchsegv_Dump.txt](https://github.com/AvaloniaUI/Avalonia/files/10378198/catchsegv_Dump.txt)

**Desktop (please complete the following information):**

- OS: [Linux, Petaliunx 2022.2]
- Version [0.10.18]

**Additional context**
I did previously have this issue https://github.com/AvaloniaUI/Avalonia/issues/4427 and resolved it via FontManagerOptions as suggested in the issue

```
        public static AppBuilder BuildAvaloniaApp()
        {
            GC.KeepAlive(typeof(SKBitmapImage).Assembly);
            GC.KeepAlive(typeof(SKBitmapControl).Assembly);
            GC.KeepAlive(typeof(SvgImageExtension).Assembly);
            GC.KeepAlive(typeof(Avalonia.Svg.Skia.Svg).Assembly);
            return AppBuilder.Configure<MainApp>()
                .UseReactiveUI()
                .UsePlatformDetect()
                .With(new FontManagerOptions() { DefaultFamilyName = "Liberation Mono" })
                .With(new X11PlatformOptions { })
                .UseSkia()
                .LogToTrace();
        }
```

**Comment by kekekeks** [comment]
Since the crash happens in libfontconfig, I don't think we can do much from our side.

You can try using https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies to remove libfontconfig dependency completely and just ship required fonts with the application.

**Comment by Anthonywolfe** [comment]
Adding 

```
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.88.3" ExcludeAssets="all"/>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.3" />
```
to my csproj seems to have fixed it.

And by "ship required fonts with the application" do you mean including them as resources like described here https://docs.avaloniaui.net/docs/getting-started/assets#including-assets ?
