### ISSUE TITLE
Code-behind name generation not working for inline text elements like Run, 11.0.0-preview4

### ISSUE THREAD

**Issue by djeikyb** [AvaloniaUI/Avalonia#9958]
I have no wpf experience and am very new to Avalonia. I'm trying to port rxui's ["compelling example"][0] from wpf to Avalonia. The rxui [full wpf github project][1], my [port in progress github][2]. This example uses code-behind bindings like `x:Name="SomeName"`. I'm using the 11.0.0-preview4 version of Avalonia to get access to `Avalonia.Controls.Documents.Run`.

I'm having trouble using the code-behind binding with the new Run tag:

    <TextBlock Grid.Column="1" TextWrapping="WrapWithOverflow" Margin="6" VerticalAlignment="Center">
      <Run FontSize="14" FontWeight="SemiBold" x:Name="titleRun"/>

I expect RxuiCompellingExample.NugetDetailsView.g.cs to be generated with code for Avalonia.Controls.Documents.Run, but none is. I see a property for the named iconImage, but not any for the named Run tags:

    // <auto-generated />

    using Avalonia;
    using Avalonia.Controls;
    using Avalonia.Markup.Xaml;

    namespace RxuiCompellingExample
    {
        partial class NugetDetailsView
        {
            internal global::Avalonia.Controls.Image iconImage;

            /// <summary>
            /// Wires up the controls and optionally loads XAML markup and attaches dev tools (if Avalonia.Diagnostics package is referenced).
            /// </summary>
            /// <param name="loadXaml">Should the XAML be loaded into the component.</param>

            public void InitializeComponent(bool loadXaml = true)
            {
                if (loadXaml)
                {
                    AvaloniaXamlLoader.Load(this);
                }

                iconImage = this.FindControl<global::Avalonia.Controls.Image>("iconImage");
            }
        }
    }

I suspect this is because the name generator is looking for classes that are some type of [control][3]. I don't think the Run class meets this criteria.

Not entirely sure if this report belongs in the name generator repo or here!

I'm on macos 13.1, m1 / apple silicon.

[0]: https://www.reactiveui.net/docs/getting-started/compelling-example
[1]: https://github.com/reactiveui/ReactiveUI.Samples/tree/main/wpf/getting-started/ReactiveDemo
[2]: https://github.com/djeikyb/RxuiCompellingExample
[3]: https://github.com/AvaloniaUI/Avalonia.NameGenerator/pull/100/files

**Comment by maxkatz6** [comment]
If it doesn't work with `this.FindControl<Run>("titleRun")`, then it's a bigger issue and not just a generator.
And I would expect these Find/Get methods to work only with INamed elements, while Run is not.
Not sure what changes are required to implement INamed on Run though.

**Comment by amwx** [comment]
> If it doesn't work with `this.FindControl<Run>("titleRun")`, then it's a bigger issue and not just a generator. 

Just tested, `FindControl<T>` doesn't work (expected), but `Find<T>` does

<br />

> And I would expect these Find/Get methods to work only with INamed elements, while Run is not. 

It is. Run (Inlines) is a `StyledElement` which implements `INamed`.

Not really sure how the generator works, but I think it uses the xaml compiler right? I tried to add `INamed` to `DefinitionBase` to solve #6276 but it turns out that's not enough to get XamlX to recognize the Name property and actually register it, so it seems the xaml compiler only respects `INamed` on controls or something deeper in the hierarchy than just `StyledElement`.
