### ISSUE TITLE
Simplify Fluent Theme Style Selectors

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#9976]
**Is your feature request related to a problem? Please describe.**
As discussed in https://github.com/AvaloniaUI/Avalonia/discussions/9657 , After the change of LocalValue priority, it is possible to set some of TemplateBinding properties directly from the control, but not the template part. This will simplify the style selector, as well as simplify developer's effort to customize control appearance. 

Take `Button` as Example, developer wants to set background to red on hover:
**Before Change**
current slice of `ControlTheme`:
```xaml
<ControlTheme x:Key="{x:Type Button}" TargetType="Button">
  <Setter Property="Background" Value="{DynamicResource ButtonBackground}" />
  <Setter Property="Template">
    <ControlTemplate>
      <ContentPresenter x:Name="PART_ContentPresenter"
        Background="{TemplateBinding Background}"/>
    </ControlTemplate>
  </Setter>
  <Style Selector="^:pointerover /template/ ContentPresenter#PART_ContentPresenter">
    <Setter Property="Background" Value="{DynamicResource ButtonBackgroundPointerOver}" />
  </Style>
</ControlTheme>
```
If a developer have no deep understanding of fluent them, and try to customize this button's appearance as below, it will fail. 
```xaml
<Style Selector="Button:pointerover">
      <Setter Property="Background" Value="Red"/>
</Style>
```
The only way to achieve this is to style as below:
```xaml
<Style Selector="Button:pointerover /template/ ContentPresenter#PART_ContentPresenter">
      <Setter Property="Background" Value="Red"/>
</Style>
```

This is very unintuitive. Developer has to go to review the source code of Button Fluent Theme, to 
1. Identify that this pseudo class is indeed styled on template part
2. Find out the part name to re-style

**After Change**

Change Button Theme to below:
```xaml
<ControlTheme x:Key="{x:Type Button}" TargetType="Button">
  <Setter Property="Background" Value="{DynamicResource ButtonBackground}" />
  <Setter Property="Template">
    <ControlTemplate>
      <ContentPresenter x:Name="PART_ContentPresenter"
        Background="{TemplateBinding Background}"/>
    </ControlTemplate>
  </Setter>
  <!-- Style is applied on Button but not template part -->
  <Style Selector="^:pointerover"> 
    <Setter Property="Background" Value="{DynamicResource ButtonBackgroundPointerOver}" />
  </Style>
</ControlTheme>
```
Then below style works
```xaml
<Style Selector="Button:pointerover">
      <Setter Property="Background" Value="Red"/>
</Style>
```
And below style also works so it is not breaking existing styles if user already spend efforts to style on template part. 
```xaml
<Style Selector="Button:pointerover /template/ ContentPresenter#PART_ContentPresenter">
      <Setter Property="Background" Value="Red"/>
</Style>
```

**Describe the solution you'd like**
If a control's property is consumed by a template part via TemplateBinding, and that part is the only consumer of this property, then this template part should be restyled through template parent instead of template part itself. This impacts many controls.

**Comment by robloo** [comment]
There were again reasons pointed out why this can't be done: https://github.com/AvaloniaUI/Avalonia/discussions/9657#discussioncomment-4408972.

There were changes since it was first brought up though: https://github.com/AvaloniaUI/Avalonia/pull/2662 (where it was also determined not possible).

**Comment by rabbitism** [comment]
@robloo actually the behavior is not as described as @grokys commented, if user set a local value for button background, they can still set `:pointerover` style to template part to achieve the goal, which means developer takes equal effort to change `:pointerover` color if local value is set, and takes less effort to change if local value is not set.

**Comment by maxkatz6** [comment]
> if user set a local value for button background, they can still set :pointerover style to template part to achieve the goal

Yes, they still can apply another style for the template part. But I am not sure about it being equal effort.

I personally liked `Button:part(ContentPresenter)` or `Expander:part(ExpanderHeader)` syntax to at least simplify this problem. Also consistent with CSS. Don't remember how that discussion ended though aside from moving any more styling changes to the 11.x or 12.0.

**Comment by amwx** [comment]
> Change Button Theme to below:
> 
> ```
> <ControlTheme x:Key="{x:Type Button}" TargetType="Button">
>   <Setter Property="Background" Value="{DynamicResource ButtonBackground}" />
>   <Setter Property="Template">
>     <ControlTemplate>
>       <ContentPresenter x:Name="PART_ContentPresenter"
>         Background="{TemplateBinding Background}"/>
>     </ControlTemplate>
>   </Setter>
>   
>   <Style Selector="^:pointerover"> 
>     <Setter Property="Background" Value="{DynamicResource ButtonBackgroundPointerOver}" />
>   </Style>
> </ControlTheme>
> ```
> 
> Then below style works
> 
> ```
> <Style Selector="Button:pointerover">
>       <Setter Property="Background" Value="Red"/>
> </Style>
> ```
> 

It works only if you never want to set the background outside of the ControlTheme. Add a Background to the actual Button instance in xaml, and the pointerover style won't work (this is what grokys was saying in your linked discussion about local value priority):

```Xaml
<Button Background="Blue" Content="Button" />
```

With the styling set as you have above, the button will always be blue - even when the pointer is over the button where you want it Red. This is because `Background="Blue"` on the button instance results in setting `Button.Background` to `Blue` with LocalValue priority - and LocalValue can only be overridden by Animation priority. So, if the pseudoclass selectors don't target the specific template item like you have (`Selector="Button:pointerover"`) that selector tries to set `Button.Background`, but is setting with StyleTrigger priority, which is lower and won't apply unless you remove the local value.

So we use full Selector with template part (`Selector="Button:pointerover /template/ ContentPresenter#PART_ContentPresenter"`) because now we're working with a TemplateBinding which can be overridden by StyleTrigger priority. WPF and UWP work exactly the same way.

**Comment by rabbitism** [comment]
@amwx Yes you are correct. What misleads me is that, in WPF style triggers has lower priority than template parent. I took this knowledge but seems it's not applicable in avalonia.
