### ISSUE TITLE
ScrollViewer.ScrollToEnd() seems not working

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#9992]
**Describe the bug**

ScrollViewer.ScrollToEnd() method is not working, content still remains in the same position.

**To Reproduce**

1. Create a ScrollViewer
2. Add some vertical contents to activate the vertical scroll bar
3. Call ScrollViewer.ScrollToEnd()
4. See the error

**Expected behavior**

ScrollViewer should go to the end of the content.

**Screenshots**

ScrollViewer's style:
```xaml
<Style Selector="ScrollViewer">
        <Setter Property="Background"
                Value="Transparent" />
        <Setter Property="Template">
            <ControlTemplate>
                <Grid ColumnDefinitions="*,Auto" RowDefinitions="*,Auto">
                    <ScrollContentPresenter Name="PART_ContentPresenter"
                                            Grid.Row="0"
                                            Grid.Column="0"
                                            Grid.RowSpan="2"
                                            Grid.ColumnSpan="2"
                                            Background="{TemplateBinding Background}"
                                            CanHorizontallyScroll="{TemplateBinding CanHorizontallyScroll}"
                                            CanVerticallyScroll="{TemplateBinding CanVerticallyScroll}"
                                            Content="{TemplateBinding Content}"
                                            Extent="{TemplateBinding Extent, Mode=TwoWay}"
                                            Margin="{TemplateBinding Padding}"
                                            Offset="{TemplateBinding Offset, Mode=TwoWay}"
                                            Viewport="{TemplateBinding Viewport, Mode=TwoWay}">
                        <ScrollContentPresenter.GestureRecognizers>
                            <ScrollGestureRecognizer
                                CanHorizontallyScroll="{TemplateBinding CanHorizontallyScroll}"
                                CanVerticallyScroll="{TemplateBinding CanVerticallyScroll}" />
                        </ScrollContentPresenter.GestureRecognizers>
                    </ScrollContentPresenter>
                    <ScrollBar Name="PART_HorizontalScrollBar"
                               AllowAutoHide="{TemplateBinding AllowAutoHide}"
                               Orientation="Horizontal"
                               LargeChange="{Binding LargeChange.Width, RelativeSource={RelativeSource TemplatedParent}}"
                               SmallChange="{Binding SmallChange.Width, RelativeSource={RelativeSource TemplatedParent}}"
                               Maximum="{TemplateBinding HorizontalScrollBarMaximum}"
                               Value="{TemplateBinding HorizontalScrollBarValue, Mode=TwoWay}"
                               ViewportSize="{TemplateBinding HorizontalScrollBarViewportSize}"
                               Visibility="{TemplateBinding HorizontalScrollBarVisibility}"
                               Grid.Row="1"
                               Focusable="False" />
                    <ScrollBar Name="PART_VerticalScrollBar"
                               AllowAutoHide="{TemplateBinding AllowAutoHide}"
                               Orientation="Vertical"
                               LargeChange="{Binding LargeChange.Height, RelativeSource={RelativeSource TemplatedParent}}"
                               SmallChange="{Binding SmallChange.Height, RelativeSource={RelativeSource TemplatedParent}}"
                               Maximum="{TemplateBinding VerticalScrollBarMaximum}"
                               Value="{TemplateBinding VerticalScrollBarValue, Mode=TwoWay}"
                               ViewportSize="{TemplateBinding VerticalScrollBarViewportSize}"
                               Visibility="{TemplateBinding VerticalScrollBarVisibility}"
                               Grid.Column="1"
                               Focusable="False" />
                    <Panel x:Name="PART_ScrollBarsSeparator" Grid.Row="1" Grid.Column="1"
                           Background="{DynamicResource ScrollViewerScrollBarsSeparatorBackground}" />
                </Grid>
            </ControlTemplate>
        </Setter>
    </Style>
```

**Desktop (please complete the following information):**

- OS: Windows 11 22H2
- Version: Latest Avalonia nightly build

**Comment by maxkatz6** [comment]
IIRC, "Scroll***" methods work the best after items were materialized. Which usually happens only on next layout pass.
So, it makes sense to always add dispatcher call with layout priority.

I think, default API can be changed to async and be called on the dispatcher automatically.

**Comment by laolarou726** [comment]
> IIRC, "Scroll***" methods work the best after items were materialized. Which usually happens only on next layout pass. So, it makes sense to always add dispatcher call with layout priority.
> 
> I think, default API can be changed to async and be called on the dispatcher automatically.

I think I can create a PR later?

**Comment by grokys** [comment]
There aren't an examples of where you're calling `ScrollToEnd` here so it's hard to say what's going wrong, but I assume you're calling it in the constructor or something?

In this case, @maxkatz6 is correct that a layout pass would be needed before `ScrollToEnd` can work.

> I think, default API can be changed to async and be called on the dispatcher automatically.

However I disagree with this, there are a _lot_ of cases where you don't need to do this (the majority in fact).

**Comment by laolarou726** [comment]
> There aren't an examples of where you're calling `ScrollToEnd` here so it's hard to say what's going wrong, but I assume you're calling it in the constructor or something?
> 
> 
> 
> In this case, @maxkatz6 is correct that a layout pass would be needed before `ScrollToEnd` can work.
> 
> 
> 
> > I think, default API can be changed to async and be called on the dispatcher automatically.
> 
> 
> 
> However I disagree with this, there are a _lot_ of cases where you don't need to do this (the majority in fact).

Basically I have an ItemsControl in the ScrollViewer.

I'm calling ScrollViewer.ScrollToEnd() in the event where the items source of ItemsControl is changed. So it should be in the UI thread. If I only use ScrollToEnd() without Dispatcher priority the content will not refresh. So maybe is a bug or something related to virtualization?

**Comment by grokys** [comment]
Without an actual repro it's difficult to say for sure, but indeed in your case it sounds like you will need a layout pass to complete before being able to scroll to the end. That's not a bug, it's simply how it works - the contents of the `ItemsControl` are updated on layout.

That doesn't mean that _all_ cases of scrolling to the end require a layout pass however, so I think the PR should be closed.
