### ISSUE TITLE
Designer does no load when Microsoft.Extensions.Configuration appsettings.json file is used

### ISSUE THREAD

**Issue by bigswede74** [AvaloniaUI/Avalonia#9996]
**Description**
Designer does no load and is always stuck showing "The designer is loading...". There is an error message "The previewer process exited unexpectedly, see output window for more details. The output window shows an error about not finding the appsettings.json file as seen below. 

**To Reproduce**

1. Create a base avaloniaUI applicaion
2. Add appsettings.json file
3. Use Microsoft.Extensions.Configuration to load the json file
4. Open designer and see error

10:02:50.084 [Information] 20484 Started previewer process for '"C:\repo\AvaloniaApp\bin\Debug\net6.0\AvaloniaApp.dll"'. Waiting for connection to be initialized.
10:02:50.858 [Information] 20484 Connection initialized
10:02:54.057 [Error] 20484 <= "Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation."
10:02:54.062 [Error] 20484 <= " ---> System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The expected physical path was 'C:\repo\appsettings.json'."
10:02:54.065 [Error] 20484 <= "   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)"
10:02:54.067 [Error] 20484 <= "   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)"
10:02:54.069 [Error] 20484 <= "   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()"
10:02:54.071 [Error] 20484 <= "   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)"
10:02:54.075 [Error] 20484 <= "   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()"
10:02:54.076 [Error] 20484 <= "   at AvaloniaApp.App.AddConfiguration() in C:\repo\AvaloniaApp\App.axaml.cs:line 52"
10:02:54.078 [Error] 20484 <= "   at AvaloniaApp.App..ctor() in C:\repo\AvaloniaApp\App.axaml.cs:line 34"
10:02:54.081 [Error] 20484 <= "   at System.RuntimeType.CreateInstanceOfT()"
10:02:54.083 [Error] 20484 <= "   --- End of inner exception stack trace ---"
10:02:54.084 [Error] 20484 <= "   at System.RuntimeType.CreateInstanceOfT()"
10:02:54.087 [Error] 20484 <= "   at System.Activator.CreateInstance[T]()"
10:02:54.090 [Error] 20484 <= "   at Avalonia.Controls.AppBuilderBase`1.<>c__45`1.<Configure>b__45_0() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 87"
10:02:54.092 [Error] 20484 <= "   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 306"
10:02:54.094 [Error] 20484 <= "   at Avalonia.Controls.AppBuilderBase`1.SetupWithoutStarting() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 167"
10:02:54.097 [Error] 20484 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.AppInitializer`1.ConfigureApp(IAvaloniaRemoteTransportConnection transport, CommandLineArgs args, Object obj) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 154"
10:02:54.099 [Error] 20484 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 179"
10:02:54.100 [Error] 20484 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args) in /_/src/tools/Avalonia.Designer.HostApp/Program.cs:line 47"
10:02:56.606 [Information]  Process exited
10:02:56.607 [Information]  Stopping previewer process
10:02:56.606 [Error]  Connection error
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<ReadExact>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<Reader>d__16.MoveNext()

**Expected behavior**
The designer should load properly

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 0.10.18

**Additional context**
The application targets .net 6

**Comment by jack775544** [comment]
I am currently using Avalonia with Microsoft.Extensions.Configuration (via Microsoft.Extensions.Hosting however) and it is able to load appsettings file just fine.

The interesting part about your stack trace is this `The configuration file 'appsettings.json' was not found and is not optional. The expected physical path was 'C:\repo\appsettings.json'.` when you can see further down in your stack trace that you application is in `C:\repo\AvaloniaApp\`. Are you trying to load the file using something like `../appsettings.json` in your application?

Based off of this information, you have a couple of different approaches
* Change the location that the application is loading the json file from if it is not loading from the current directory
* Make a dummy appsettings file at that location to keep the previewer happy
* Make the appsettings.json file an optional configuration source

**Comment by bigswede74** [comment]
Resolution of the appsettings.json works fine when the application runs, it is the previewer that is looking for that odd file path. 

*Loading appsettings.json*
```csharp 
var builder = new ConfigurationBuilder()
  .SetBasePath(Directory.GetCurrentDirectory())
  .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
```

I changed appsettings.json file to be optional as shown below.

```csharp 
var builder = new ConfigurationBuilder()
  .SetBasePath(Directory.GetCurrentDirectory())
  .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
```
