### ISSUE TITLE
The type initializer for 'Avalonia.Xaml.Interactivity.Interaction' threw an exception.

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#9999]
**Describe the bug**

I just removed Avalonia.ReactiveUI from my project. Then this exception shows.

FileNotFoundException: Could not load file or assembly 'System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system could not find file

**To Reproduce**

1. Remove Avalonia.ReactiveUI from the project
4. See the error

**Expected behavior**

The program should run normally without System.Reative package

**Screenshots**

<img width="953" alt="image" src="https://user-images.githubusercontent.com/25716486/213067536-f5418dca-303c-4714-ab7d-53abf4677fec.png">

**Desktop (please complete the following information):**

- OS: Windows11 22H2
- Version: Latest Avalonia nightly build

**Comment by maxkatz6** [comment]
> The program should run normally without System.Reative package

Behaviors SDK relies on reactive package. It needs to be recompiled (it probably will be with preview5) or you can add this package in your app.
